### ISSUE TITLE
Refactor the entire SQL system

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#10000]
### Describe your feature request or suggestion in detail

At the moment the SQL system we use has proven over and over again to be bad and not sustainable.

Just recently a commit got pushed wich accidentally had the sql_rev insert commented out, which fucked up the DB updates for anyone who pulled that commit before the comment was re-added.

This did not get discovered until a week later and 44 SQL commits after which had to manually be updated. See (https://github.com/azerothcore/azerothcore-wotlk/commit/0d6b8dba181dfee5e928a7d6571adb283a8ceb5e)

And not to speak about the fucked ACDB releases that takes place where you either have to check out a commit, and then update to latest to update, or to drop the entire databases. See [this](https://discord.com/channels/217589275766685707/316952484566532107/900291496912228383) for reference.

### Describe a possible solution to your feature or suggestion in detail

Personally, I have not yet come up with the perfect system. But there are some things we definitely need to drop and fix asasp.

- We need to drop the sql_rev thing, which causes SQL fixes to be skipped (even though they are said to be applied) if the sql_rev is missed to be inserted
- Perhaps we drop the entire version_db_* crap 
- start relying on the updates table, and thus being able to edit committed files
- Start to only support the AUTO DB UPDATER as it is idiot-proof and does everything for you
- rewrite the db_assambler (if it is actually needed for some docker thing) to work as the AUTO DB UPDATER
- improve the ACDB Releases A LOT. Where you can just update your core as normal and it works.

### Additional context

If there is anything else that I am missing, please comment it under so we once and for all can get a good way of handling our SQL fixes.

**Comment by FrancescoBorzi** [comment]
> We need to drop the sql_rev thing, which causes SQL fixes to be skipped (even though they are said to be applied) if the sql_rev is missed to be inserted

As I told you that's part of the SQL pending import process we have which allow us to avoid manually setting file names to the new SQL files, which would cause more problems. So we can't just "drop" it, instead suggest a concrete alternative solution/improvement

**Comment by Kitzunu** [comment]
> Personally, I have not yet come up with the perfect system. But there are some things we definitely need to drop and fix asasp.

That is the issue we have. I don't have the perfect solution yet. So suggestions are welcome :)

**Comment by FrancescoBorzi** [comment]
> rewrite the db_assambler (if it is actually needed for some docker thing) to work as the AUTO DB UPDATER

@Kitzunu this is a valid point but you are mixing up different topics here. Please open a ticket with the list of things that the Bash DB updater needs to be improved, the list you provided here contains multiple topics together and it's not really helpful tbh.
