### ISSUE TITLE
Consecutive faction changes require server restart

### ISSUE THREAD

**Issue by febaut** [azerothcore/azerothcore-wotlk#10008]
### Current Behaviour

When you do a faction change `.character changefaction`, the first time will work but if you do it again it doesn't apply and you get an error as if you were choosing the same faction:

- Horde troll as initial faction: 
![image](https://user-images.githubusercontent.com/88860233/148109265-7624b956-6905-416b-bd4c-aa8e2f694a3d.png)
- Alliance Night elf after first changefaction
![image](https://user-images.githubusercontent.com/88860233/148109581-6e6bfdc4-b07f-44fb-bb11-477a9c10e698.png)

_Also it prints this errors in console_ 

```
Character GUID Full: 0x0000000000000005 Type: Player Low: 5 has skill 733 that does not exist.
ActionButton loading problem, will be deleted from db...
```
- Now, when I try to go back to Horde troll: 
![image](https://user-images.githubusercontent.com/88860233/148110229-c43275f9-ce83-4105-9d43-99067640185c.png)

And is like that unless you restart the server between faction changes.

### Expected Blizzlike Behaviour

Should allow to do as many faction changes as one want without restarting.

### Steps to reproduce the problem

1. Create an horde or alliance character
2. .char changefaction
3. After the change, do .char changefaction again

### Extra Notes

Tried with an old revision of AC and it works fine. 
Also I compared the CharacterHandler.cpp files, they are pretty different so maybe during the update someting was forgotten. 

### AC rev. hash/commit

AzerothCore rev. b0a98b6ec9b4+ 2021-12-11 17:09:15 +0000 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1i  8 Dec 2020)
Using Boost version: 1.74.0
Using MySQL version: 50733
Using CMake version: 3.19.3
Compiled on: Windows 10.0.19042

### Operating system

Windows 10

### Custom changes or Modules

- mod-ah-bot
- mod-promotion-AzerothCore

**Comment by Kitzunu** [comment]
How old revision did you try on where it worked?

**Comment by Nyeriah** [comment]
This might be a cache issue. Try .cache refresh and check if you can perform the faction change afterwards

**Comment by febaut** [comment]
@Kitzunu is about a year old.
@Nyeriah yeah .cache refresh works

**Comment by Shineslippers** [comment]
For me even `chache` clear doesn't help
```
Character GUID Full: 0x0000000000000001 Type: Player Low: 1 has skill 101 that does not exist.
Character GUID Full: 0x0000000000000001 Type: Player Low: 1 has skill 754 that does not exist.
```

![WoWScrnShot_011122_234851](https://user-images.githubusercontent.com/85256266/149020123-ec2bdc59-74e7-4d34-913e-1e11e6c20671.jpg)
