### ISSUE TITLE
Completing "Craftman's Writ - Runecloth Bag" may use the equipped bags causing item loss

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#10016]
### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2726

Delivering the quest Craftman's Writ can remove an equipped Runecloth Bag instead of one in the inventory, and as consequence, all the items inside it are lost.

Recorded on ChromieCraft's PTR1.

https://user-images.githubusercontent.com/22718174/148140764-1e6c93d5-298c-4297-af21-1f20a6ceeef8.mp4

### Expected Blizzlike Behaviour

It should not remove equipped bags at all, only ones in the inventory.

### Source

You normally cannot destroy/vendor an equipped bag that has items in it.

### Steps to reproduce the problem

1. Start quest "Craftman's Writ - Runecloth Bag" (`.additem 22611` to get the item that begins the quest)
2. Get your 8 bags (`.additem 14046 8` if you don't want to craft them)
3. Have at least one of the required bags equipped and with items inside it
4. Deliver the quest (`.go c 54805` if you don't want to walk)
5. Equipped bag has been removed with the items.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

Reproduced on ChromieCraft's PTR1: AzerothCore rev. 5c4750a52604 2022-01-04 15:57:38 +0000 (master branch)

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by febaut** [comment]
Theres a function inside PlayerQuest.cpp that seems to be missing an argument. Said argument checks if the item is equipped. I've added it and it does fix the item deletion if equipped. However, the quest is completed if you have the items equipped, and if you hand it like that, will remove only the items that are not equipped but will reward anyway. 
Example: if you equip 4 of the 8 necessary a bags and add some items inside them, the quest removes 4 but still rewards the player. 

It seems not to be okay at all. My question is about Blizz behaviour. Equipped items sum to quest required items counter?

**Comment by Bogir** [comment]
It looks like there should be one more variable "bool checItemsForQuest" which will exclude searching of items stored in character_inventory table and have bag=0, slot = 1-18 (equipped), slot =19-22 (bags allready used and installed in bagpack slots),  slot = 39-66 (placed in character's bank) AND slot = 67-73 (bags used and installed in bank )

So, we must skip all items at bank=0 slot 1-73 
Now server is finding and returning all of them because all of them has the same owner_guid  and stored in character_inventory  table:
https://github.com/azerothcore/azerothcore-wotlk/blob/ea8404f9819754e6a650aa3cf9729391a1a066dc/src/server/game/Entities/Player/PlayerStorage.cpp#L356
