### ISSUE TITLE
slog->OutDebug - Native debugging not working

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1002]
##### SMALL DESCRIPTION:

Seems like anything with "sLog->outDebug" is not showing up in console/logs

##### CURRENT BEHAVIOUR:

if you add something like:

    sLog->outDebug(LOG_FILTER_NONE, "Debug test.");

and you set your loglevel to 3, you still don't see the debug message in console.

Warden debug logs are also never shown, I suppose it's the same bug.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Add this in a dummy script `sLog->outDebug(LOG_FILTER_NONE, "Debug test.");`
2. Set your loglevel to max (3 I think)
3. Check in the console

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

99b534ddafcb5a2cdbf2f54794beb8d336f916fe

##### OPERATING SYSTEM:

Linux deb 9

**Comment by AyaseCore** [comment]
I just checked the logic of the code.It is not an issue.We just need to teach people how to use it.


**We can see it here. We need to edit DebugLogMask**
```
void Log::outDebug(DebugLogFilters f, const char * str, ...)
{
    if (!(m_DebugLogMask & f)) //We can see it here. 
        return;

    if (!str)
        return;
```

**We need to edit DebugLogMask to 0x11111111 = 286331153**
```
#
#    Debug Log Mask
#        Description: Bitmask that determines which debug log output (level 3)
#                     will be logged.
#        Possible flags:
#
#                  64 - Anything related to network input/output,
#                        such as packet handlers and netcode logs
#
#                       Simply add the values together to create a bitmask.
#                       For more info see enum DebugLogFilters in Log.h
#
#             Default: 0 (nothing)

DebugLogMask = 286331153
```

and ` if ( m_logLevel > LOGL_DETAIL )` .So we need to edit LogLevel to 3.
```
#
#    LogLevel
#        Description: Server console level of logging
#        Default:     0 - (Minimum)
#                     1 - (Basic)
#                     2 - (Detail)
#                     3 - (Full/Debug)
LogLevel = 3
```

-----------
I'm not sure what it's for:"LOG_FILTER_NONE"
It's not used? or all undefined to use it?
if not used. we needn't to change something.

**Comment by BarbzYHOOL** [comment]
This is not working, or I'm not using the right debug mask.

Where is the list?

Why `DebugLogMask = 286331153` (note I already tried 64 long ago without success)

**Comment by BarbzYHOOL** [comment]
LOG_FILTER_NONE is probably to display the debug all the time no matter the debug mask?

**Comment by BarbzYHOOL** [comment]
All the masks are in `common/Logging/Log.h`. Now I'd like to know if it works with warden "LOG_FILTER_WARDEN" because when I tried it didn't seem to
