### ISSUE TITLE
content of one or more guild bank tabs randomly disappears

### ISSUE THREAD

**Issue by tfleschenberg** [azerothcore/azerothcore-wotlk#10026]
### Current Behaviour

Almost all content of one or more random guild bank tabs randomly disappears, often solvable with client restart but not always. Other players may still see and access the content while its invisible to the affected player.
Checked with more than one client, and with more than one player.
Client cache was also cleared but didn't solve the problem.

### Expected Blizzlike Behaviour

Just working normally

### Steps to reproduce the problem

Open guild bank, check tabs, close guild bank and repeat till it happens (random).

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. 75aeec80a40a 2022-01-05 03:34:25 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 100512
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-9-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/azeroth-server/data/maps. Total size: 252191207 bytes
vmaps directory located in /opt/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/azeroth-server/data/mmaps. Total size: 2196365052 bytes
Using deDE DBC Locale as default. All available DBC locales: deDE
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2022_01_05_00
Using Character DB Revision: 2021_12_26_01
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Debian 11 x64

### Custom changes or Modules

None

**Comment by Shineslippers** [comment]
Can you provide some screenshots. How it looks?

**Comment by tfleschenberg** [comment]
Yes, it just took me a while to get the bug again.
Bug:
![WoWScrnShot_010522_223103](https://user-images.githubusercontent.com/9384628/148292623-3a163b5e-ef68-48cb-9810-92423c625498.jpg)
20 seconds later after relog:
![WoWScrnShot_010522_223123](https://user-images.githubusercontent.com/9384628/148292661-3c05b66f-8061-44c8-be8a-a524038d3112.jpg)

Same at this tab:
![WoWScrnShot_010522_223105](https://user-images.githubusercontent.com/9384628/148292730-75458301-909d-4fd2-bfb1-3add2aa012d5.jpg)
21 seconds later after relog:
![WoWScrnShot_010522_223126](https://user-images.githubusercontent.com/9384628/148292750-5fafedd3-6e87-40c4-8341-3c6823d909d2.jpg)

**Comment by SoulSeekkor** [comment]
This has been super frustrating for us, it occurs with us on a server of 5 people total constantly.  We have to logoff and back on to fix it or do a /reload ui to resolve it (temporarily).
