### ISSUE TITLE
Guild bank max stacks per day ist bugged

### ISSUE THREAD

**Issue by tfleschenberg** [azerothcore/azerothcore-wotlk#10041]
### Current Behaviour

Recently i discovered that the max stacks per day setting for the guild bank is bugged. The entered value is saved modulo 256 thus limited to the range between 0 and 255.

### Expected Blizzlike Behaviour

Accept values above 255

### Steps to reproduce the problem

press o
click guild
click options
select a rank
select a tab
enter value above 255 at stacks per day
click accept
click options again and see the changed value for stacks per day

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. 75aeec80a40a 2022-01-05 03:34:25 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 100512
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-9-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/azeroth-server/data/maps. Total size: 252191207 bytes
vmaps directory located in /opt/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/azeroth-server/data/mmaps. Total size: 2196365052 bytes
Using deDE DBC Locale as default. All available DBC locales: deDE
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2022_01_05_00
Using Character DB Revision: 2021_12_26_01
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Debian 11 x64

### Custom changes or Modules

None

**Comment by Kitzunu** [comment]
iirc it's a client limitation. But dont quote me on it

**Comment by tfleschenberg** [comment]
The last AC version I used (11/2021) did not have this limitation, I had set all my tabs to 999 stacks per day and it was displayed that way.

**Comment by Kitzunu** [comment]
Maybe due to https://github.com/azerothcore/azerothcore-wotlk/commit/3591f69662d62bacd1e71fb5aa23734518857565 or

**Comment by Kitzunu** [comment]
@IntelligentQuantum

**Comment by tfleschenberg** [comment]
I guess its caused by /src/server/game/Handlers/GuildHandler.cpp line 189:

rightsAndSlots[tabId] = GuildBankRightsAndSlots(tabId, uint8(packet.TabFlags[tabId]), uint8(packet.TabWithdrawItemLimit[tabId]));

the TabWithdrawItemLimit is forced to uint8.

In before commit https://github.com/azerothcore/azerothcore-wotlk/commit/3591f69662d62bacd1e71fb5aa23734518857565 it was:

rightsAndSlots[tabId] = GuildBankRightsAndSlots(tabId, bankRights, slots);

**Comment by tfleschenberg** [comment]
I have removed the cast to uint8 and the problem is gone:

https://github.com/tfleschenberg/azerothcore-wotlk/blob/master/src/server/game/Handlers/GuildHandler.cpp#L189

and I created a pull request for that:

https://github.com/azerothcore/azerothcore-wotlk/pull/10047
