### ISSUE TITLE
Pull of Ancient Core Hound doesn't trigger Molten Destroyer pull with Molten Giant

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#10040]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2737

![WoWScrnShot_010522_182943](https://user-images.githubusercontent.com/80590226/148275854-a5fa2a8d-3e29-4e31-95d8-8e5771353036.jpg)
On Screenshot you can see that we pulled Giant without Destroyer

Tester:

The issue is confirmed. Pull of [Ancient Core Hound](https://wowgaming.altervista.org/aowow/?npc=11673)(56669) doesn't trigger [Molten Destroyer](https://wowgaming.altervista.org/aowow/?npc=11659)(56709) pull with [Molten Giant](https://wowgaming.altervista.org/aowow/?npc=11658)(56708)

https://user-images.githubusercontent.com/85256266/148407742-9b934ed5-069c-4235-a110-7893747440e4.mp4

### Expected Blizzlike Behaviour

Guess Molten Giant and Molten Destroyer in Molten core should be linked with each other

### Steps to reproduce the problem

.go c 56708
pull dog near molten giant

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by T1ti** [comment]
I think raid creatures are suppsoed to have a bigger aggro range
