### ISSUE TITLE
Dreadnaught' Battlegear Last Set Bonus (Cheat Death)

### ISSUE THREAD

**Issue by jads147** [azerothcore/azerothcore-wotlk#10051]
### Current Behaviour

Dreadnaught' Battlegear last set bonus effect proc's at 100% health.

### Expected Blizzlike Behaviour

Dreadnaught' Battlegear last set bonus effect should proc at 20% health and should only proc once.

### Steps to reproduce the problem

Happens everytime.

### AC rev. hash/commit

AzerothCore rev. 017772043d9d 2022-01-05 23:22:43 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.74.0
Using MySQL version: 80027
Using CMake version: 3.20.2
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/build/bin/RelWithDebInfo/data/maps. Total size: 252191207 bytes
vmaps directory located in C:/build/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/build/bin/RelWithDebInfo/data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2022_01_05_04
Using Character DB Revision: 2021_12_26_01
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
[Cheat Death](https://wowgaming.altervista.org/aowow/?spell=28845) proc at any % of health and resresheing every time on damage. YPlayers can't get T3, just in case.

https://user-images.githubusercontent.com/85256266/148584985-e6f448c7-0142-4bdd-8226-99d2599173ec.mp4

**Comment by Nefertumm** [comment]
```diff
diff --git a/src/server/scripts/Spells/spell_warrior.cpp b/src/server/scripts/Spells/spell_warrior.cpp
index aa45f27b2..0d7f8d67a 100644
--- a/src/server/scripts/Spells/spell_warrior.cpp
+++ b/src/server/scripts/Spells/spell_warrior.cpp
@@ -829,6 +829,31 @@ class spell_warr_retaliation : public AuraScript
     }
 };
 
+class spell_warr_t3_9p_bonus : public AuraScript
+{
+    PrepareAuraScript(spell_warr_t3_9p_bonus);
+
+    bool CheckProc(ProcEventInfo& eventInfo)
+    {
+        return eventInfo.GetActionTarget() && eventInfo.GetActionTarget()->GetHealthPct() <= 20.f;
+    }
+
+    void HandleProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
+    {
+        PreventDefaultAction();
+        if (Unit* target = eventInfo.GetActionTarget())
+        {
+            target->CastSpell(target, 28846, true);
+        }
+    }
+
+    void Register() override
+    {
+        DoCheckProc += AuraCheckProcFn(spell_warr_t3_9p_bonus::CheckProc);
+        OnEffectProc += AuraEffectProcFn(spell_warr_t3_9p_bonus::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
+    }
+};
+
 void AddSC_warrior_spell_scripts()
 {
     RegisterSpellScript(spell_warr_mocking_blow);
@@ -854,4 +879,5 @@ void AddSC_warrior_spell_scripts()
     RegisterSpellScript(spell_warr_sweeping_strikes);
     RegisterSpellScript(spell_warr_vigilance);
     RegisterSpellScript(spell_warr_vigilance_trigger);
+    RegisterSpellScript(spell_warr_t3_9p_bonus);
 }
```

I tried to fix it, but I couldn't figure out the refreshing part. I tried with recovery_time in SpellMgr, eventInfo->SetProcCooldown, with spell_proc_event table too, but none of them worked. If anyone knows how to fix that part, my code is above.

**Comment by TheDdraig** [comment]
Try this:

``INSERT INTO `spell_proc_event` (`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES
(28845, 0, 4, 0, 0, 0, 0, 0, 0, 0, 600000);``
