### ISSUE TITLE
Arena Spoils chest from the challenge in BRD arena has too quick despawn

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#10057]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2740

After Theldren and his team is killed, a chest called Arena spoils spawns in the middle of the arena. It despawns after about 1 second, thus looting is impossible (especially since even with autoloot a message pops up about the item being BOP and slows down the looting time). This makes getting important items such as Ironweave mantle impossible.

Tester:

The issue is confirmed. [Arena Spoils](https://wowgaming.altervista.org/aowow/?object=181074) chest from the challenge in BRD has too quick despawn

https://user-images.githubusercontent.com/85256266/148573357-468de25a-88b2-4218-b4ff-905f9e77c260.mp4

### Expected Blizzlike Behaviour

The chest should not despawn or despawn after a much bigger window of time. 

### Steps to reproduce the problem

.additem 21986 
.go xyz 568 -195 -53 230 1
place banner
pass through event

### Extra Notes

Side effect of https://github.com/azerothcore/azerothcore-wotlk/issues/9998 ?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
> Side effect of #9998 ?

No. The gameobjects that were deleted were those that did not have any spawn records in the database and in any core or scripts. Which is why there are still custom objects left in the database as they are still used in some form or another
