### ISSUE TITLE
Feature: multiple creature ids

### ISSUE THREAD

**Issue by neifion-00000000** [azerothcore/azerothcore-wotlk#10050]
### Describe your feature request or suggestion in detail

Creature spawnpoints (xyzo coordinates) often have multiple id types that can spawn.  An easy example of an area is Fel Rock in Teldrassil, every mob inside there other than the named mobs has a 2nd type.  (Many times only some mobs in the area have 2 types so these cases should be confirmed by sniffs, but in that cave every mob does)  

From all research so far, it seems there can only be 2 types.  It has also been proposed that a chance field could be added alongside it.

### Describe a possible solution to your feature or suggestion in detail

Two solutions were discussed, an indexing method,  and directly in the creature template.  There is some complications with the modelid field in creature, but that field is an old mangos redundancy and should be removed most likely anyway.

**Comment by T1ti** [comment]
theorycally pools are exactly for that, but they're anoying to use
A simple solution for shared spawnpoint would be to ahve multiple creature template columns in the creature table, just like a creature_tempalte can have multiple displays

**Comment by neifion-00000000** [comment]
> theorycally pools are exactly for that, but they're anoying to use A simple solution for shared spawnpoint would be to ahve multiple creature template columns in the creature table, just like a creature_tempalte can have multiple displays

yeah this is what we are leaning toward, there is complication with the modelid but malcrom believes we can remove that column, though that will lead to some specific cases that need fixed, it is a depreciated field.

**Comment by T1ti** [comment]
why is there a modelid in creature in the first place ?

**Comment by neifion-00000000** [comment]
> why is there a modelid in creature in the first place ?

mangos artifact, largely, before there was modelid in creature_template

**Comment by malcrom** [comment]
It will be a rare occurrence for when the model needs to be set on spawn. Hard to check 90000+ spawns for an issue. may end up wiping and wait for reports to fix model on spawn in SAI. 

Right now I'm thinking id1,id2,chance1. Make id2 default 0 and chance1 default 100 to always spawn id1. We would then be able to add a second id and lower the chance of id1 being selected. 

Below are examples of a single and dual spawn point:

```
-- Winterfall Den Watcher spawn point
INSERT INTO `creature` (`guid`,`id1`,`id2`,`chance1`,`map`,`zoneId`,`areaId`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`wander_distance`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`,`ScriptName`,`VerifiedBuild`) VALUES
(41035, 7440, 0, 100, 1, 0, 0, 1, 1, 0, 0, 6914.6646, -5149.913, 696.0513, 1.166961431503295898, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0),

-- Winterfall Ursa or Winterfall Shaman spawn point
INSERT INTO `creature` (`guid`,`id1`,`id2`,`chance1`,`map`,`zoneId`,`areaId`,`spawnMask`,`phaseMask`,`modelid`,`equipment_id`,`position_x`,`position_y`,`position_z`,`orientation`,`spawntimesecs`,`wander_distance`,`currentwaypoint`,`curhealth`,`curmana`,`MovementType`,`npcflag`,`unit_flags`,`dynamicflags`,`ScriptName`,`VerifiedBuild`) VALUES
(41024, 7438, 1739, 50, 1, 0, 0, 1, 1, 0, 0, 6780.277, -5049.571, 722.91614, 3.535489320755004882, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0),
```

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/dfac47a5629367caf5e3db3106f2160b1f3d7ce3
