### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10056]
### Current Behaviour

https://gist.github.com/mpfans/76f13a6733beacba97ab6696a75d0c06

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/2e6213d526602f8e3a5ec35a9f6fd4c3e9820157

### Operating system

ubuntu 20.04

**Comment by Nyeriah** [comment]
Thanks for your report, however, it has already been reported here: https://github.com/azerothcore/azerothcore-wotlk/issues/9995

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9712

It should be caused by this pr
