### ISSUE TITLE
Swimmer in Dalaran

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#10055]
### Current Behaviour

Dalaran Visitor ,sometimes will swimming on floor but not running.

### Expected Blizzlike Behaviour

just running , no swimming

### Steps to reproduce the problem

.go c 28674
watch

### Extra Notes

[Dalaran Visitor](https://youtu.be/6q1aDehK43U)

### AC rev. hash/commit

c7510d21b803+

### Operating system

Ubuntu 20.04

**Comment by acidmanifesto** [comment]
Thank you for the video and your time. So current The smart script, creature template movement  is correct, the Dalaran Visitor is suppose to fly, BUT suppose to be on a flying machine mount. Will be looking into this in getting this corrected.

**Comment by acidmanifesto** [comment]
npcs 32596 and  32596 are inproper ctms. a pr will be put in shortly

**Comment by Shineslippers** [comment]
Can you check this one too https://github.com/chromiecraft/chromiecraft/issues/1796

**Comment by acidmanifesto** [comment]
> 32596

i am heading to a appoint right now. but i can later on today.

**Comment by Shineslippers** [comment]
I'll create new report then. Thank you.

**Comment by anzz1** [comment]
have you tried with this https://github.com/azerothcore/azerothcore-wotlk/commit/2d4e17fd16326b27f100977ac8a542ad56d57934
