### ISSUE TITLE
 Defias Prisoner and Stormwind City Guards waypoint incomplete

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#10060]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1796

![WoWScrnShot_090221_134204](https://user-images.githubusercontent.com/89823720/133953874-ec71d7c7-e23b-45b7-a414-6584635cecdb.jpg)

Tester:

The issue is confirmed. [Defias Prisoner](https://wowgaming.altervista.org/aowow/?npc=1706) and [Stormwind City Guard](https://wowgaming.altervista.org/aowow/?npc=37063)s has script issues. Disappear animation at Stockade entrance is also weird

![WoWScrnShot_010722_201956](https://user-images.githubusercontent.com/85256266/148582570-c549b8bc-14b6-4c1e-a6a5-382dccfdf787.jpg)

### Expected Blizzlike Behaviour

Goup should not be walking on top of eachother

### Source

Wowpedia [Defias Prisoner](https://wowpedia.fandom.com/wiki/Defias_Prisoner?oldid=2364805)
> A Defias Prisoner can also be found at the Stormwind Harbor, escorted by 4 Stormwind City Guards from The Bravery to the Stormwind Stockade. In that case he is friendly and cannot be aggroed or attacked.

### Steps to reproduce the problem

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
not a script issue, but an issue with Waypoints and creature groups :)

**Comment by acidmanifesto** [comment]
This is currently smart script 1706, which runs the actionlist 170600 which summons the guards.
