### ISSUE TITLE
[SQL] Structure ERROR?

### ISSUE THREAD

**Issue by Add3rall** [azerothcore/azerothcore-wotlk#1006]
Im new here, so Im not sure if im just retard missing something or your DB is a ported mess with TrintiyCore.

Most of the Quest_Template structure has conflicts by default, examples:

QuestType -> QuestInfoID
Method -> QuestType
Add TimeAllowed to the struct, im kinda lazy to fill them.
Add AllowableRaces to the struct aswell..
NextQuestIdChain -> RewardNextQuest...
RewardXPId -> RewardXPDifficulty...
RewardMoney
etc...

Just, why?
Doesnt make sense.

**Comment by Add3rall** [comment]
Quest_Template_Addon missing aswell

**Comment by Add3rall** [comment]
holiday_date doesnt exist as well
game_event struct missmatch

**Comment by BarbzYHOOL** [comment]
This is pretty much the result of TC changing the names all the time and we haven't updated.

Feel free to update all of this or unify it with better names (because TC will keep changing names anyway) and make a Pull Request.
