### ISSUE TITLE
Reunited (in Zul'Drak) - quest not working

### ISSUE THREAD

**Issue by Deltharis** [azerothcore/azerothcore-wotlk#1007]
##### SMALL DESCRIPTION:
Quest "Reunited" (https://www.wowhead.com/quest=12663/reunited) is impossible to complete, leaves the character stuck in the air.

##### CURRENT BEHAVIOUR:
https://www.wowhead.com/quest=12663/reunited is a quest only available after you've completed quest series starting with https://www.wowhead.com/quest=11989/truce (though mirror quest if you haven't -https://www.wowhead.com/quest=12664/dark-horizon - possibly works the same way, just with changed dialogue, worth checking) 
Here, after talking to questgiver (https://www.wowhead.com/npc=28503/overlord-drakuru) he asks you to go to https://www.wowhead.com/npc=28666/gorebag who basically gives you a bat tour of the area, while Drakuru whispers some lore to you. However, right after second whisper (at around 33.51, 69.22 Zul'Drak, maybe 20 seconds into the tour) the bat drops you in the air. The character is stuck, able to turn around and start casting, but actually unable to cast (instant spells that can only target yourself like paladin seals appear to cast, but do not give you the effect) or move. Waiting does not fix it.

##### EXPECTED BEHAVIOUR:
Player should properly do the tour (visiting all the places and getting all the whispers), get dropped at the same place he started at and quest should get status "completed"

##### STEPS TO REPRODUCE THE PROBLEM:
Sorry, don't know how to make it easy to reproduce:
1. complete quest series starting at https://www.wowhead.com/quest=11989/truce and ending in Drak'Tharon dungeon (not sure if neccessary - possibly https://www.wowhead.com/quest=12664/dark-horizon which is the quest you get without this step is bugged the same way, worth checking)
2. get quest https://www.wowhead.com/quest=12661/infiltrating-voltarus
3. Go to https://www.wowhead.com/npc=28503/overlord-drakuru and start https://www.wowhead.com/quest=12663/reunited
4. Talk to https://www.wowhead.com/npc=28666/gorebag and start the bat tour
5. Notice how the tour breaks.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
7a5ed0c5bbcb62e0f26e8b8718b28b0bef8488e1

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
VAS AutoBalance

##### OTHER CUSTOMIZATIONS:
I'm using http://www.ac-web.org/forums/showthread.php?232758-AzerothCore-AzerothCore-wotlk-Solo-Friendly-Repack-with-Eluna repack v1.3, not sure if something else is changed

**Comment by BarbzYHOOL** [comment]
Someone confirms?

**Comment by LukasVolgger** [comment]
Cannot reproduce this issue on commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4

![image](https://user-images.githubusercontent.com/55922592/100504649-daae0a00-316c-11eb-97f9-89451e85031f.png)

Funfact - If use a BFA models, you stuck in a bat's ass:
![image](https://user-images.githubusercontent.com/55922592/100502941-5c516800-316c-11eb-8719-cac692871466.png)
