### ISSUE TITLE
Some of Garr's Firesworn are respawn like usual NPCs

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#10080]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2747

Every add alive at the point in time Garr dies, will respawn like the trash does respawn (or on server restart, couldnt verify that yet).

Tester: 

The issue is confirmed. Garr's [Firesworn](https://wowgaming.altervista.org/aowow/?npc=12099) are respawn like usual NPCs. GUIDs `16399` and `56619`

![WoWScrnShot_011022_224528](https://user-images.githubusercontent.com/85256266/148657687-23f1e408-bc50-46a0-856c-26f8dc86edda.jpg)

### Expected Blizzlike Behaviour

Adds shouldnt respawn

### Source

[https://classic.wowhead.com/guides/garr-molten-core-strategy-wow-classic](https://classic.wowhead.com/guides/garr-molten-core-strategy-wow-classic)

### Steps to reproduce the problem

.go c id 12057
kill garr and firesworns
close server
change PC time for example +1 day
start server
.go c id 12057

hope there is exist faster way

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Grimfeather** [comment]
this still happens.
10112 did not fix it.

just those 2 firesworn
16399 and 56619
