### ISSUE TITLE
[Quest] The Ectoplasmic Distiller - Mux's Quality Goods does not contain Goblin Rocket Fuel

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10095]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2753

![image](https://user-images.githubusercontent.com/20357406/148675924-55c9e517-0668-4740-a527-e6427d164049.png)

Tester:

The issue is confirmed. The chance of getting the correct amount of 8 [Goblin Rocket Fuel] is 81,6%.

![image](https://user-images.githubusercontent.com/62797536/148679622-10ebcb81-9dc5-4805-a8ba-259279e2c66b.png)

### Expected Blizzlike Behaviour

The chance of getting 8 [Goblin Rocket Fuel] and [Discombobulator Ray] out of [Mux's Quality Goods] should be 100%.

### Source

https://wowwiki-archive.fandom.com/wiki/Quest:The_Ectoplasmic_Distiller
https://classic.wowhead.com/quest=8921/the-ectoplasmic-distiller#comments:id=2752413
https://classic.wowhead.com/item=22320/muxs-quality-goods#comments:id=2659660
https://classic.wowhead.com/item=22320/muxs-quality-goods#comments:id=2659745

### Steps to reproduce the problem

Original report:

.additem 22320
open bag
sometimes doesn't give you the rocket fuel.

Tester:

`SELECT * FROM item_loot_template WHERE entry = "22320";`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Discombobulator Ray should be 100% as well.

**Comment by ishidinho** [comment]
Updated the "Expected Blizzlike Behaviour".
