### ISSUE TITLE
[SPELL/hunter]

### ISSUE THREAD

**Issue by ockap** [azerothcore/azerothcore-wotlk#1009]
Aspect of the Viper doesn't regen mana while using Volley

 rev. ddc8a1ae6ebf+

Operating system: Debian 8

Modules:  No

Other Customizations:  No

**Comment by Ali-Khazaee** [comment]
Blizlike

**Comment by talamortis** [comment]
![image](https://user-images.githubusercontent.com/6143065/44622971-57314e80-a8bb-11e8-8c3b-50fba48bfbd8.png)

**Comment by Ramys** [comment]
evil of wow brazil players
90% bugged server WoW BR
