### ISSUE TITLE
Feature: allow Random Battleground at lower levels

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#10098]
### Describe your feature request or suggestion in detail

Random Battleground (RBG) is by default only available at level 80. It would be nice to change this via `worldserver.conf`, ideally by specifying something like:

- `MinLevelRBG`
- `MaxLevelRBG`

having both of them default at `80`.

**Comment by IntelligentQuantum** [comment]
is this part handled by server ?

**Comment by Helias** [comment]
partially, if I remember correctly to add the option you need to edit the client :(, we could investigate and find a workaround for it
We can solve using:
- patch for the client, changing PvPDifficulty dbc and the .lua file that shows the BGs options for joining
- make an hack server-side converting any join low-level into `random battleground` but the player will always read `warsong gulch` or `arathi basin`, we could try to send a different text to the player when he clicks to join but need a bit of investigation

**Comment by IntelligentQuantum** [comment]
> partially, if I remember correctly to add the option you need to edit the client :(, we could investigate and find a workaround for it We can solve using:
> 
>     * patch for the client, changing PvPDifficulty dbc and the .lua file that shows the BGs options for joining
> 
>     * make an hack server-side converting any join low-level into `random battleground` but the player will always read `warsong gulch` or `arathi basin`, we could try to send a different text to the player when he clicks to join but need a bit of investigation

If you need it for chromiecraft, You can use npc for this or for user friendly you can add it to the player bag xD

btw i will try to do it with patch

**Comment by Helias** [comment]
We need it for chromiecraft indeed

**Comment by Kitzunu** [comment]
We should not push something into the core that requires client updates. That's module stuff imo

**Comment by Nyeriah** [comment]
If we’re to require a npc, why not a command? Like low level arena

**Comment by Helias** [comment]
@Kitzunu totally agree, we could make a module for it
@Nyeriah good idea, I think it's the best option

**Comment by UltraNix** [comment]
@FrancescoBorzi And about rewards for finished randon bg (honor, etc)?

**Comment by UltraNix** [comment]
Implemented in https://github.com/UltraNix/mod-low-level-rbg.
