### ISSUE TITLE
Using Taming Rod item of Taming the Beast quest on creature doesn't remove combat after successful cast

### ISSUE THREAD

**Issue by BurlyBeard** [azerothcore/azerothcore-wotlk#10104]
### Current Behaviour

When doing the Dwarven Hunter Quest, you are given a taming rod to tame 3 different animals. Each time you use the rod to tame an animal, it becomes your pet but you become stuck in combat and cannot leave it, and because you are in combat you cannot log out of that character or exit the game. Force closing the client and logging back in, shows that you are still in combat.

### Expected Blizzlike Behaviour

When using the taming rod and the pet becomes no longer aggressive to you, you should drop out of combat. 

### Steps to reproduce the problem

1. Become level 10 with a Dwarven hunter and pick up your level 10 quest in Kharinos.
2. Go and tame a Large Craig Boar. It will be hostile until you complete the taming, and then will no longer be hostile, will be a pet and you will remain in combat and unable to do anything that being in combat would prevent you from doing.
3. Turn in the quest and you still remain in combat.
4. Repeat with the other two animals you need to tame to complete the chain.

### Extra Notes

I have only tested this on the Dwarven quest.

### AC rev. hash/commit

.server debug
AzerothCore rev. ea8404f98197 2022-01-06 14:21:00 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.74.0
Using MySQL version: 80027
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19042
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/Data/maps. Total size: 252191207 bytes
vmaps directory located in C:/Build/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Build/Data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2022_01_06_08
Using Character DB Revision: 2021_12_26_01
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Windows 10 x64

**Comment by dantav** [comment]
I  can confirm this happens.

**Comment by Shineslippers** [comment]
The issue is confirmed. Using [Taming Rod](https://wowgaming.altervista.org/aowow/?search=taming+rod) on creature doesn't remove combat after successful cast

![WoWScrnShot_011022_142428](https://user-images.githubusercontent.com/85256266/148758919-2513de58-2ad4-477a-9e56-12c5d4234261.jpg)

.additem 15908
.go c id 1196
tame a bear
