### ISSUE TITLE
 Connection of mmaps in worldserver

### ISSUE THREAD

**Issue by LipeBreno** [azerothcore/azerothcore-wotlk#1010]
in worldserver.conf should have the lines to link word to mmaps, I did not find them ... could someone help me?

**Comment by BarbzYHOOL** [comment]
no because we don't understand your question

**Comment by talamortis** [comment]
incorrect template used. will close.

**Comment by LipeBreno** [comment]
Following:
In order for the mmaps to be found in the worldserver, it needs a directory like this example from Trinity:
mmap.enablePathFinding = 0
switch to
mmap.enablePathFinding = 1

Updates.EnableDatabases = 0
change to:
Updates.EnableDatabases = 15

Updates.SourcePath = ""
change to:
Updates.SourcePath = "../../../Core" (Source Code directory you cloned from GitHub)

Updates.MySqlCLIPath = ""
change to:
Updates.MySqlCLIPath = "C: / Program Files (x86) / MySQL / MySQL Server 5.5 / bin / mysql.exe"

--- I could not find these directories to link them to the worldserver ...

**Comment by BarbzYHOOL** [comment]
We don't use that update system.
