### ISSUE TITLE
Mmap Pathfinding on Ocean or even Shallow water global issue, charge, follow, path through terrain when shortcut used

### ISSUE THREAD

**Issue by WORISX** [azerothcore/azerothcore-wotlk#10119]
### Current Behaviour

General issue, if a creature is aggroed from behind some terrain and both points are in water, shortcut is created without checking terrain, 

https://user-images.githubusercontent.com/97387012/148825066-3e7f660f-d8f8-475d-86de-09786e327d0d.mp4

### Expected Blizzlike Behaviour

If shortcut is used we should check terrain to avoid going into textures when charging, when chasing, follow, etc

### Source

Can be seen on several videos on youtube, ill paste them soon, ofc, it's not the right behaviour, you won't see creatures go through textures on retail and you can't charge, blink or do stuff through textures on ocean or shallow water on retail.

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/97387012/148831911-ae437faf-6608-4141-88e6-ed3cadaf75c6.png)

Do steps on video on the provided coords.

### AC rev. hash/commit

ae795fbcaa49eef18d11daf614c636eaf05b5a8f

### Operating system

Windows 10 x64, Debian 10

**Comment by Kitzunu** [comment]
ac rev commit

**Comment by WORISX** [comment]
> ac rev commit

Done

**Comment by acidmanifesto** [comment]
I can not help but to this this may be wrong which may be causing the issue in the video
https://github.com/azerothcore/azerothcore-wotlk/blob/4af723590fcc161e338acb3ce82586a57d732e2e/src/server/game/Movement/MovementGenerators/PathGenerator.cpp#L177-L198

**Comment by WORISX** [comment]
> I can not help but to think this may be wrong which may be causing the issue in the video
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/4af723590fcc161e338acb3ce82586a57d732e2e/src/server/game/Movement/MovementGenerators/PathGenerator.cpp#L177-L198

This should be considered as critical isnt it? Since this is happening anywhere, or at least be considered as priority high
