### ISSUE TITLE
Boss in Pit of Saron Can not kill

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#10123]
### Current Behaviour

Boss tyrannus at last position is unattackable ,can not enter combat, so can not be killed

### Expected Blizzlike Behaviour

boss should enter combat

### Steps to reproduce the problem

1. enter instance pit of saron
2. kill boss garfrost and boss  krickandick
3. wait in front of boss tyrannus 
4. watch , no trigger to enter combat, and boss was unattackable

### AC rev. hash/commit

da7f4da51639+

### Operating system

Ubuntu 20.04

**Comment by opcode02** [comment]
I believe Tryrannus is also bugged right before the cave entrance, and this is why he isn't attackable later. He never triggers the event after you kill the undead (2 groups of 5) going up the hill.

**Comment by Shineslippers** [comment]
As i understand there is issue with pack before cave. It doesn't summon/trigger it >>> no cave event, no boss trigger.

![WoWScrnShot_011222_001606](https://user-images.githubusercontent.com/85256266/149022993-854bf064-fb5c-483f-97e3-b7bb20d0792f.jpg)

**Comment by Wowkasu** [comment]
Dungeon can not be passed completely! You can only kill two bosses. The passing algorithm fails and does not continue.
on the picture:
![2022-02-16 11-29-37 World of Warcraft](https://user-images.githubusercontent.com/68443208/154224483-1ae22f6c-5940-43dd-988b-887e3d587c2a.jpg)

1. Silvana is standing still and not going anywhere.
2. No ghouls appear.
3. Two packs of mobs do not appear on the slope.
4. Scourgelord Tyrannus does not fly to the top and the final battle with him is not possible
