### ISSUE TITLE
Elixirs override flasks

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10129]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2765

If you are using an elixir while a flask is active, the flask is replaced by the elixir.

Tester:

The issue is confirmed. Both types of elixirs, guardian and battle, replace the effect of flasks on use.

### Expected Blizzlike Behaviour

Having a flask active should prevent the player from using a battle or guardian elixir. This should also affect Jujus.

### Source

> Subsequent flasks imbibed will overwrite the effects of the former and prevent a player from using other elixirs.
(source: https://legacy.zam.com/wiki/Flasks_%28WoW%29)

### Steps to reproduce the problem

Original report:
1. Use a flask
2. Use an elixir

I tested with [Flask of Supreme Power] and [Arcane Elixir].

Tester:
1. `.additem 13512`
2. `.additem 13447`
3. Use [Flask of Supreme Power]
4. Use [Elixir of Sages] (guardian elixir)
5. `.additem 13512`
6. `.additem 12451`
7. `.additem 12384`
8. Use [Flask of Supreme Power]
9. Use [Juju Power] (battle elixir)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
I don't see any bug here. If flask count as Battle and Guardian elixir, then it should be overriden.
