### ISSUE TITLE
Wailing Caverns - Evading NPCs in shallow water

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10131]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2764

Every mob in the dungeon, that is standing in the shallow water is evading, when the player that has aggro isn't in his melee range. The mobs aren't able to move too.

Tester:

I cannot confirm this behavior for every mob in the dungeon, as the reporter said. But I found some mobs where I can confirm, see below.

### Expected Blizzlike Behaviour

Original report:
The mobs should behave like there's no water at all and should be able to move. 

### Steps to reproduce the problem

1. Pull the mobs of Wailing caverns back to the shallow water that leads to the start of the dungeon
2. Stay further than melee range
3. Watch some of the NPCs reset

### Extra Notes

I can confirm that the following NPCs reset when entering the water:
* Deviate Crocolisk: https://wowgaming.altervista.org/aowow/?npc=5053
* Deviate Shambler: https://wowgaming.altervista.org/aowow/?npc=5761
* Deviate Lasher: https://wowgaming.altervista.org/aowow/?npc=5055
* Evolving Ectoplasm: https://wowgaming.altervista.org/aowow/?npc=3640
* Nightmare Ectoplasm: https://wowgaming.altervista.org/aowow/?npc=5763

![WoWScrnShot_011122_170637](https://user-images.githubusercontent.com/62797536/148982476-0a9cde1a-14e1-40ba-9be3-8a84e4712a24.jpg)

![WoWScrnShot_011122_170843](https://user-images.githubusercontent.com/62797536/148982500-a815795b-c1b3-40e9-8253-2767f7584330.jpg)

![WoWScrnShot_011122_172230](https://user-images.githubusercontent.com/62797536/148982513-b08b177e-650d-47f6-8399-5fc15d378e2a.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Thanks for the report. I will get to it when i get home
