### ISSUE TITLE
Smartscript errors (With crash warnings)

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1014]
Hey,

Server is finally stable after revert, and it's up for 18 days already, without crash.
But, gonna make separate reports towards DB, SAI and etc Errors.

Intro will be copy / paste.

Master build
Linux, Debian 9
Premium Account module
Hash 4d7c06c
Nothing custom

Link to errors as well -> https://pastebin.com/rE7ULB4W

2018-08-05 16:33:54 SmartScript: Action target Creature(entry: 19763) is not using SmartAI, action skipped to prevent crash.
2018-08-05 16:37:53 SmartScript: Action target Creature(entry: 19764) is not using SmartAI, action skipped to prevent crash.
2018-08-05 16:39:15 SmartScript: Action target Creature(entry: 19766) is not using SmartAI, action skipped to prevent crash.
2018-08-26 06:37:01 SmartScript: Action target Creature(entry: 27807) is not using SmartAI, action skipped to prevent crash.
2018-08-26 07:32:17 SmartScript: Action target Creature(entry: 32367) is not using SmartAI, action skipped to prevent crash.
2018-08-26 07:32:17 SmartScript: Action target Creature(entry: 32364) is not using SmartAI, action skipped to prevent crash.
2018-08-26 07:32:17 SmartScript: Action target Creature(entry: 32365) is not using SmartAI, action skipped to prevent crash.
2018-08-05 21:38:14 SmartScript: Action target Creature(entry: 17405) is not using SmartAI, action skipped to prevent crash.
2018-08-24 22:44:52 SmartScript: Action target Creature(entry: 26872) is not using SmartAI, action skipped to prevent crash.

**Comment by BarbzYHOOL** [comment]
I don't understand this error.

I think it's because these creatures are the target of another creature with a smart_script but they are missing their own smart_script.


```
server/game/AI/SmartScripts/SmartScript.cpp:                        sLog->outError("SmartScript: Action target for SMART_ACTION_SET_COUNTER is not using SmartAI, skipping");
server/game/AI/SmartScripts/SmartScript.cpp:                    sLog->outErrorDb("SmartScript: Action target for SMART_ACTION_SEND_TARGET_TO_TARGET is not using SmartAI, skipping");
server/game/AI/SmartScripts/SmartScript.h:                sLog->outErrorDb("SmartScript: Action target Creature(entry: %u) is not using SmartAI, action skipped to prevent crash.", c ? c->GetEntry() : (me ? me->GetEntry() : 0));

```

**Comment by Knindzagxg** [comment]
Few of them are Vendors, that's why it's wierd. 
Will try to fix some of them once i'm home today.

**Comment by Meltie2013** [comment]
Here's a small fix for the issues here. There might be a database mismatch here though.
```
-- Manni SAI
set @entry := 19763;
update creature_template set AIName = "SmartAI" where entry = @entry;
delete from smart_scripts where entryorguid = @entry and source_type = 0;
insert into smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) values
(@entry, 0, 1, 0, 38, 0, 100, 512, 0, 1, 0, 0, 80, @entry * 100 + 00, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Manni - On Data set 0 1 - Run Script (Phase 1)");

-- Moh SAI
set @entry := 19764;
update creature_template set AIName = "SmartAI" where entry = @entry;
delete from smart_scripts where entryorguid = @entry and source_type = 0;
insert into smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) values
(@entry, 0, 1, 0, 38, 0, 100, 512, 0, 1, 0, 0, 80, @entry * 100 + 00, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Moh - On Data set 0 1 - Run Script (Phase 1)");

-- Jakk SAI
set @entry := 19766;
update creature_template set AIName = "SmartAI" where entry = @entry;
delete from smart_scripts where entryorguid = @entry and source_type = 0;
insert into smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) values
(@entry, 0, 1, 0, 38, 0, 100, 512, 0, 1, 0, 0, 80, @entry * 100 + 00, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Jakk - On Data set 0 1 - Run Script (Phase 1)");

-- Update other Creatures SAI that doesn't exist
update creature_template set AIName = "" where entry in (17405, 26872, 27807, 32364, 32365, 32367);
```

**Comment by BarbzYHOOL** [comment]
Knindza, you'll report if you don't see these errors anymore plz!

**Comment by Knindzagxg** [comment]
Will do no worries.

**Comment by poszer** [comment]
@Knindzagxg Can we close this issue, it's fixed, no?
