### ISSUE TITLE
[BWL] Vaelastrasz the Corrupt doesn't use fire nova

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10154]
CURRENT BEHAVIOUR:

~~She~~ they appears to not be using fire nova

EXPECTED BLIZZLIKE BEHAVIOUR:

Should use fire nova

SOURCE:

https://classic.wowhead.com/guides/vaelastrasz-the-corrupt-blackwing-lair-strategy

STEPS TO REPRODUCE THE PROBLEM:

Go to bwl second  boss, with two players

NOTES

AC HASH/COMMIT:
0c35369
OPERATING SYSTEM:
Windows 11
MODULES:
mod-progression-system
CUSTOMIZATIONS:

**Comment by T1ti** [comment]
Very important comment : Vael is a HE

**Comment by acidmanifesto** [comment]
I identify as a AH-64 apache attack helicopter.

**Comment by temperrr** [comment]
Fixed

**Comment by Nefertumm** [comment]
Can't reproduce it on 7115f353ccdf9c872c8599389b059db4a24edfb4
![image](https://user-images.githubusercontent.com/19627365/149526618-c91a188c-4579-49ec-bbdb-bd3825f339d3.png)
