### ISSUE TITLE
server crash 2

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10167]
### Current Behaviour

crash log 1

https://gist.github.com/mpfans/3f0017381a2e1d3976db771962cb5763

crash log 2

https://gist.github.com/mpfans/35353b589b6974e4ec66b086dc2b2de0

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

b2df4aa970706442c1748f144b37a913dec1cc9c  + PR 10025

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
crash again

https://gist.github.com/mpfans/b30879a9dd8f7c32850cd825ee488ce8

**Comment by mpfans** [comment]
crash!!!!!!!

https://gist.github.com/mpfans/4971f4cb89fa12ca7228b5a070a832d7

**Comment by Nyeriah** [comment]
Could you try this? https://github.com/azerothcore/azerothcore-wotlk/pull/10120

Thank you very much for testing it, but please don't spam if it is the same crash log

**Comment by mpfans** [comment]
> Could you try this? #10120
> 
> Thank you very much for testing it, but please don't spam if it is the same crash log

update to e6e76f971b4c03ab818912b9e45c08703e9153f1  + PR 10120,testing
