### ISSUE TITLE
Metamorphosis - incorrect armor calculation for weapons, necks, rings and trinkets with armor

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10172]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2780

Currently the final demonology talent Metamorphosis, when activated, does not increase the armor as much as it should. Some item armor is not increased at all, and others dont have their armor increased enough.

Tester:

The issue is confirmed. There is an incorrect armor calculation for weapons, necks, rings and trinkets with armor.
Armor Calculation with factor 6 for rest of equipment is correct.

### Expected Blizzlike Behaviour

Original report:
According to the tooltip, when taken (screenshot with the tooltip provided), the form should increase armor from items by 600%. This should include any items, like weapons, rings, trinkets etc.

Tester:
The following item slots have to be included in the armor calculation of Metamorphosis:
* weapons
* necks
* rings
* trinkets

### Source

![WoWScrnShot_011322_172652](https://user-images.githubusercontent.com/61918356/149360589-7e5777cd-b725-42e6-bc4a-fce23a1b2dfe.jpg)
![WoWScrnShot_011322_172643](https://user-images.githubusercontent.com/61918356/149360615-48ed190b-cbb3-4c0a-8161-556c9e0f69b3.jpg)
![WoWScrnShot_011322_173539](https://user-images.githubusercontent.com/61918356/149360669-8a2e7855-ef2d-4727-97db-944d3c322433.jpg)
![WoWScrnShot_011322_173540](https://user-images.githubusercontent.com/61918356/149360692-26bc8440-7280-4ef9-ae3c-daf724b5772b.jpg)

### Steps to reproduce the problem

Original report:
Activate metamorphosis and calculate the increased armor, as well as check the armor conversion from weapons, trinkets and rings.

Tester:
* `.learn 47241`
* `.additem 943`
* `.additem 15855`
* `.additem 11811`
* `.additem 9417`
* only equip the items above
* cast Metamorphosis
* watch armor not increase

Before Metamorphosis:
![image](https://user-images.githubusercontent.com/62797536/149515212-35150203-82bb-442c-b401-5b29b508cb66.png)

With Metamorphosis:
![image](https://user-images.githubusercontent.com/62797536/149515182-8cab3766-05be-44a2-a034-bba5fb6d3a58.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Nope. Only body/shield pieces of your armor count as base for this aura. It's blizzlike.

**Comment by ishidinho** [comment]
@UltraNix Do you have a source for this? I found nothing.

**Comment by UltraNix** [comment]
@ishidinho https://github.com/TrinityCore/TrinityCore/commit/96a447dc8e4ef717cf78fda4e05a48fdd6d9a5e7
