### ISSUE TITLE
Iceblock and Divine Shield can reset bosses

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10183]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2752

![image](https://user-images.githubusercontent.com/80590226/148661123-a1df6ebb-b9c4-4359-b6a4-ec0b4bde1180.png)

We did alt run, and I was on mage, we wiped on 1% hp and hunter used feign dead, I used Iceblock and fight did reset, Iceblock shouldn't reset boss it is not Invisibility.

Tester:

The issue is confirmed for both spells Iceblock and Divine Shield.

![WoWScrnShot_011422_165759](https://user-images.githubusercontent.com/62797536/149546568-2de96e61-87c7-4f68-b249-3cc5c043b93f.jpg)

![WoWScrnShot_011422_170008](https://user-images.githubusercontent.com/62797536/149546572-65e83f7b-1db0-467b-a0b9-fae2979ff958.jpg)

### Expected Blizzlike Behaviour

Original report:
Iceblock shouldn't reset boss it is not Invisibility.

Tester:
Same for Divine Shield.

### Steps to reproduce the problem

Original report:
1. Form raid group and make sure that you're last alive or have hunter alive who can FD
2. Let him FD
3. Use Iceblock and fight is reset

Tester:
4. Use Divine Shield and fight is reset

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86f1b87fe60f462a8045ee169b72fe1104140100

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
No but you are immune to attacks and damage. I'd like if you could provide some evidence of how it should work.

Because logically, if you are immune to attack and there is no others to attack a mob would evade. But if you find something on it, that would be appreciated

**Comment by ishidinho** [comment]
@Kitzunu You can see evidence in my screenshots. The Core Hound guard of Golemagg are still attacking me, because they act normal as they should. It seems to be a problem with bosses.

You are not immun to attacks. You are immun to attacks damage.

You can find evidence in the rest of the world anywhere. Just pull mobs and ice block. They will never reset and they never resetted in the past.

**Comment by UltraNix** [comment]
I can't reproduce it on this boss.

**Comment by ishidinho** [comment]
@UltraNix Can you provide a clip how you try to reproduce it?
I was able to reproduce it first try with the original reporters instructions.

**Comment by UltraNix** [comment]
@ishidinho https://imgur.com/a/eEDD79V

**Comment by ishidinho** [comment]
@UltraNix 

https://user-images.githubusercontent.com/62797536/149809507-7d467e2d-ac53-448c-a95a-3119f96aa6ea.mp4

**Comment by Nefertumm** [comment]
I can see a difference between the videos, on Ultranix's the boss is already attacking him, while on ishidinho's the boss didn't reach him. Could that be related?

**Comment by UltraNix** [comment]
@ishidinho Still the same.
https://imgur.com/a/lQH7gSv

**Comment by UltraNix** [comment]
@ishidinho
