### ISSUE TITLE
Feature: Sniffed vs hand-made/hack historic

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#10204]
### Describe your feature request or suggestion in detail

It would be really cool if we had a library or some sort of archive where we could log the things that were sniffed and the things that are hand-made or possibly hacks.

Some database entities got the VerifiedBuild column but I'm not sure if that is informative enough.

### Describe a possible solution to your feature or suggestion in detail

Create some sort of table or change log where we could keep track of this. Not really sure about the best design.

VerifiedBuild column needs its size updated, data gets truncated if you try to log the most recent retail builds.

**Comment by Kitzunu** [comment]
We also now have CreateObject field, I think this might be enough to close this?
