### ISSUE TITLE
Knot Thimblejack's Cache loot - some items should not be dropped by mobs

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#10214]
### Original issue: 
https://github.com/chromiecraft/chromiecraft/issues/2802

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/84640316/149617492-e881f160-a467-4bb4-96a9-eb4346b052c4.png)

### Expected Blizzlike Behaviour

these should only drop from the cache in DM. Not from a random lvl 80 mob.

### Source

https://tbc.wowhead.com/item=18519/pattern-shifting-cloak

### Steps to reproduce the problem

keira 3 or mysql.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by nolt** [comment]
Hmm so you provided bad source then... I understood that Fel shouldnt frop only one recipe not all...

**Comment by baranzadeoglu** [comment]
> Hmm so you provided bad source then... I understood that Fel shouldnt frop only one recipe not all...

really meant it as an example. Title and the screenshot should imply better.

**Comment by nolt** [comment]
Well ok, in that case this need to be revieved one more time with deeper sources of loot tables.

**Comment by nolt** [comment]
@baranzadeoglu 
I modified AC issue title to be more accurate to your CC issue.

**Comment by nolt** [comment]
Rest of the drop to check:
```
+-------+-------+--------+------------------------------------------------+
| entry | Item  | Chance | Comment                                        |
+-------+-------+--------+------------------------------------------------+
| 11448 | 18240 |   0.78 | Gordok Warlock - Ogre Tannin                   |
| 11448 | 18414 |   0.02 | Gordok Warlock - Pattern: Belt of the Archmage |
| 11448 | 18416 |   0.02 | Gordok Warlock - Pattern: Inferno Gloves       |
| 11448 | 18418 |   0.02 | Gordok Warlock - Pattern: Cloak of Warding     |
| 11448 | 18514 |   0.02 | Gordok Warlock - Pattern: Girdle of Insight    |
| 11448 | 18518 |   0.02 | Gordok Warlock - Pattern: Hide of the Wild     |
| 11450 | 18240 |   0.14 | Gordok Reaver - Ogre Tannin                    |
| 11450 | 18414 |   0.02 | Gordok Reaver - Pattern: Belt of the Archmage  |
| 11450 | 18415 |   0.02 | Gordok Reaver - Pattern: Felcloth Gloves       |
| 11450 | 18416 |   0.02 | Gordok Reaver - Pattern: Inferno Gloves        |
| 11450 | 18418 |   0.02 | Gordok Reaver - Pattern: Cloak of Warding      |
| 13022 | 18240 |   0.02 | Whip Lasher - Ogre Tannin                      |
| 14351 | 18240 |   0.28 | Gordok Bushwacker - Ogre Tannin                |
| 14351 | 18417 |   0.07 | Gordok Bushwacker - Pattern: Mooncloth Gloves  |
| 14385 | 18240 |    100 | Doomguard Minion - Ogre Tannin                 |
+-------+-------+--------+------------------------------------------------+
```

**Comment by nolt** [comment]
I checked it here https://tbc.wowhead.com/ and this loot seems to be not right. I propose to delete it.

**Comment by acidmanifesto** [comment]
issue was auto closed due to it being linked to a pr that only fixed a partial of the issue. i apologize for the confusion if any.
