### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by cvvmusic** [azerothcore/azerothcore-wotlk#1022]
The discrepancy between the replicas of Jaina and Uther in the Halls of Reflection (Errors in the table "creature_text")

**Comment by BarbzYHOOL** [comment]
Is it linked to https://github.com/azerothcore/azerothcore-wotlk/issues/773 ?

**Comment by cvvmusic** [comment]
@BarbzYHOOL maybe... I 10 hours ago fixed this problem... Now this dungeon works for me.

**Comment by cvvmusic** [comment]
@BarbzYHOOL Download http://rgho.st/7Tt5G275k (Pass: 345345)

**Comment by BarbzYHOOL** [comment]
thank you but what is that? 59mb :(

**Comment by cvvmusic** [comment]
@BarbzYHOOL This is Clear DB in Zip. Compressed SQL file

**Comment by BarbzYHOOL** [comment]
we can't use that lol

if you made a SQL query to fix the issue (like `UPDATE table WHERE ...`) this is what we need ! Or `INSERT INTO creature_text ...`

**Comment by cvvmusic** [comment]
@BarbzYHOOL To be honest, I've done quite a lot of fixes in the database, fixing and integrating replicas from locales_broadcast_text into the creature_text table, so you understand, this is a complete Russification "Reflection Halls, Saron's Pits" and a partial fix in "Icecrown Citadel"... I did not create additional SQL files that update this or that table, but I corrected the table to a direct via HeidiSQL

**Comment by BarbzYHOOL** [comment]
Ok, but we can't use this.
