### ISSUE TITLE
GM command not working while GM mode is on

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1023]
##### SMALL DESCRIPTION:

`.gob near` doesn't work while GM mode is on but works when it's off o_0
And maybe other GM commands.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele orgrimmar
2. .gm on
3. .gob near
4. doesn't work
5. .gm off
6. .gob near
7. works

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

4a9e3f190a6d627ea9165fc1803c1761ebe0f92e

##### OPERATING SYSTEM:

Debian 9

**Comment by poszer** [comment]
Confirmed. Same thing on Windows OS

**Comment by Asherdoom** [comment]
confirm. GM mode off and can use gm commands.

**Comment by Ercules76** [comment]
The problem in on phasemask, in gm mode it was set to 0xFFFFFFFF and when launch the query (in this case .gob near) the staement return NULL. The phaseMask is a value for the query
`SELECT guid, id, position_x, position_y, position_z, map, (POW(position_x - ?, 2) + POW(position_y - ?, 2) + POW(position_z - ?, 2)) AS order_ FROM gameobject WHERE map = ? AND (POW(position_x - ?, 2) + POW(position_y - ?, 2) + POW(position_z - ?, 2)) <= ? AND (phaseMask & ?) <> 0 ORDER BY order_`
maybe there is a problem on sql ORM with 32bit value. On TC the phaseMask is different

**Comment by Ercules76** [comment]
I found the issue, when prepare the statement the value setting is in float, and in a 32bit float the max number is different from an int32 (if i remember the mantissa is 24bit)
