### ISSUE TITLE
ICC Professor Putricide will disappear after the player drinks the potion behind him

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#10232]
### Current Behaviour

ICC Professor Putricide will disappear after the player drinks the potion behind him.

AzerothCore rev. 94e43d11a1e6+ 2022-01-15 01:29:55 +0000 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1

### AC rev. hash/commit

none

### Operating system

windows 10 x64

### Custom changes or Modules

mod-anticheat
mod-eluna-lua-engine

**Comment by Bogir** [comment]
Please fill `Steps to reproduce the problem`

**Comment by fullofstarschen** [comment]
It's fixed in e8f34b2,now it works.
