### ISSUE TITLE
Shatterspear Trolls respawn too quick

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10236]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2824

https://wowgaming.altervista.org/aowow/?npc=10919#drops:0+2+1+13-14
These trolls located inbetween Darkshore / Winterspring / Felwood / Moonglade currently have an incredibly fast respawn timer. Unknown what their natural respawn time is, but as they have loot tables, this can be taken advantage of to gain large amounts of gold without much effort/time spent.

![image](https://user-images.githubusercontent.com/63965160/149960713-f3965a67-fb24-427d-ae7b-111948eed16b.png)

Tester:

The issue is confirmed for NPCs [Shatterspear Drummer](https://wowgaming.altervista.org/aowow/?npc=11196) and [Shatterspear Troll](https://wowgaming.altervista.org/aowow/?npc=10919). These NPCs despawn 30s after loot and respawn after 25s that.

### Expected Blizzlike Behaviour

Tester:
[This video](https://youtu.be/cFxbcbK-DaM?t=185) from Classic WoW mentions a downtime of 2 to 3 minutes.

[This video](https://www.youtube.com/watch?v=88HxIzabPq4) confirms that (watch at the clock in the top right corner).

### Steps to reproduce the problem

Original report:
1. Travel To shatterspear village
2. Group up mobs
3. Kill trolls
4. ...?
5. Profit

Tester:
* `.go creature 79470`
* kill NPC
* watch respawn

![WoWScrnShot_011822_161955](https://user-images.githubusercontent.com/62797536/149971918-67ccaca2-9913-4372-9b9c-d70cd9a6a0cd.jpg)

Affected NPCs:

`SELECT guid, spawntimesecs FROM creature WHERE creature_id1 = "10919" OR creature_id1 = "11196";`

| guid | spawntimesecs | 
| ---: | ---: | 
| 79470 | 25 | 
| 79473 | 25 | 
| 79476 | 25 | 
| 79483 | 25 | 
| 79489 | 25 | 
| 79491 | 25 | 
| 79492 | 25 | 
| 79493 | 25 | 
| 79494 | 25 | 
| 79496 | 25 | 
| 79499 | 25 | 
| 79508 | 25 | 
| 79510 | 25 | 
| 79514 | 25 | 
| 79515 | 25 | 
| 79517 | 25 | 
| 79519 | 25 | 
| 79521 | 25 | 
| 79523 | 25 | 
| 79525 | 25 | 
| 79527 | 25 | 
| 79529 | 25 | 
| 79531 | 25 | 
| 79537 | 25 | 
| 85375 | 25 | 
| 85378 | 25 | 
| 85379 | 25 | 
| 85380 | 25 | 
| 85529 | 25 | 
| 85530 | 25 | 
| 85545 | 25 | 
| 85546 | 25 | 
| 85547 | 25 | 
| 85548 | 25 | 
| 85549 | 25 | 
| 85550 | 25 | 
| 85551 | 25 | 
| 85552 | 25 | 
| 85553 | 25 | 
| 85554 | 25 | 
| 85555 | 25 | 
| 85556 | 25 | 
| 85557 | 25 | 
| 85562 | 25 | 
| 85558 | 25 | 
| 85559 | 25 | 
| 85560 | 25 | 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
@malcrom can you check those npcs, please? <3
