### ISSUE TITLE
Some portal trainers have wrong dialogues for mages

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10256]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2834

Portal Trainers [Elissa Dumas](https://wowgaming.altervista.org/aowow/?npc=4165) and [Lunaraa](https://wowgaming.altervista.org/aowow/?npc=16755) have incorrect dialogue when speaking with a Mage class player.

Current message is the one present for non-mage classes:
_"I do not believe you posses the mental acuity to grasp the nature of portal magic"_
![WoWScrnShot_012022_043832](https://user-images.githubusercontent.com/79346412/150270460-43f9063a-f283-4116-8fcc-1f77d937c2a3.jpg)
![WoWScrnShot_012022_044046](https://user-images.githubusercontent.com/79346412/150270466-f8eb93ff-9511-49ed-b34f-be6a4490dbbd.jpg)

Tester:

The issue is confirmed. There two cases for the Horde, too.

![WoWScrnShot_012022_101221](https://user-images.githubusercontent.com/62797536/150309278-5cf6ea08-4602-4906-8c42-e0cbbd82d062.jpg)

![WoWScrnShot_012022_101356](https://user-images.githubusercontent.com/62797536/150309282-a4b0c712-8f50-4675-9249-bcdf9c85d186.jpg)

### Expected Blizzlike Behaviour

The dialogue should be:
_"As a mage, you are one of a select group that can conjure a portal to transport you back to this very place. I can teach you if you are ready"_

### Source

The correct dialogue other portal trainers have:

![WoWScrnShot_012022_045053](https://user-images.githubusercontent.com/79346412/150270515-cb08d578-96bb-4588-a269-36bfceb6a863.jpg)

![WoWScrnShot_012022_044108](https://user-images.githubusercontent.com/79346412/150270526-34138269-bf81-47b4-9403-252a184707d5.jpg)

### Steps to reproduce the problem

_1. Get a mage.
2. Toss a mage into Darnassus or Exodar's Portal Trainer.
3. Tell the mage to check what dialogue Trainer has._

### Extra Notes

_(Darnassus) Elissa Dumas_ 
DB GUID: **46320** Entry: **4165**

_(Exodar) Lunaraa_ 
DB GUID: **57746** Entry: **16755**

_(Silvermoon) Narinth_
DB GUID: **57647** Entry: **16777**

_(Silvermoon) Narinth_
DB GUID: **38072** Entry: **2492**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Sathrenor** [comment]
>Stormwind trainer has incorrect dialogue and Thunder Bluff has a default "greetings" for non-mages.


_(Stormwind City) Larimaine Purdue_ 
DB GUID: **90441** Entry **2485**

_(Thunder Bluff) Brigitte Cranston_
DB GUID: **24768** Entry **5957**

>Also Correction:

_(Undercity) Lexington Mortaim*_
DB GUID: **38072** Entry: **2492**

**Comment by Sathrenor** [comment]
**Request to reopen**

Ysuria [DB GUID: **94505** Entry:  **27703**] in Theramore has incorrect dialogue for non-mages. It should be:
_"My teachings are only of use to mages. I cannot help you, <class>."_

Source: https://wowpedia.fandom.com/wiki/Ysuria

![WoWScrnShot_020922_235811](https://user-images.githubusercontent.com/79346412/153304703-7537582b-161d-4b13-b6c2-c1ae7a996a63.jpg)
