### ISSUE TITLE
MOVEMENTFLAG_CAN_FLY and MOVEMENTFLAG_FLYING don't work for players

### ISSUE THREAD

**Issue by erictemponi** [azerothcore/azerothcore-wotlk#1025]
##### SMALL DESCRIPTION:
If you fly, MOVEMENTFLAG_CAN_FLY and MOVEMENTFLAG_FLYING don't turn on on a player that is from level 0 account.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Write some script that tests if a player has MOVEMENTFLAG_CAN_FLY and MOVEMENTFLAG_FLYING;
2. Log in a account level 0 and create a character;
3. Use a hack or something to make you character fly and test the script.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/f66e0dc99e33ba3d4bcc1b2b2a689509bb50c816

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Anticheat: https://github.com/azerothcore/mod-anticheat

##### OTHER CUSTOMIZATIONS:
Nothing

**Comment by BarbzYHOOL** [comment]
You should've provided the test script ;)

**Comment by UltraNix** [comment]
Not able to test it. Close it.
