### ISSUE TITLE
Bug with exploring

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10268]
Original CC Issue: https://github.com/chromiecraft/chromiecraft/issues/2833

### Current Behaviour

So ran into a bit of a bug when trying to finish up on exploring. I stopped xp around my 20s so my friend and I stayed close together in terms of questing and xp and dungeon spam to just get gear or just running around getting nodes for my profs. Well when I went into SFK or zones it did not mark that I explored it.

### Expected Blizzlike Behaviour

Should register as explored regardless if xp is awarded for it.

### Source

Source per user was just a SS:
![shadowfang](https://user-images.githubusercontent.com/98065709/150241882-c7489f28-8d60-4710-a349-906c4f3110da.JPG)

### Steps to reproduce the problem

1. Turn XP off
2. Explore area

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b5075e9a0a203bb0ee44b232a09e4f5452a39c63

### Operating system

Windows 10 x64 Pro

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by schell244** [comment]
Maybe related relog issue:
Map parts which are wronly explored after relog are not counted for the achievment and those parts will break the explore achievment for the map.
https://github.com/azerothcore/azerothcore-wotlk/issues/7737#issuecomment-974800353

**Comment by UltraNix** [comment]
I can't reproduce it. Event with XP turned off, I can exploring areas and see progres in achievement.
