### ISSUE TITLE
Hunter Pet Dies Instantly When Revived

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10267]
Original CC issue: https://github.com/chromiecraft/chromiecraft/issues/2831

### Current Behaviour

Since today (19.01.2022) I am seeing strange behaviour with my pet (im a hunter).

If the pet dies and then I Revive it (or we both get resurrected from the spirit healer in a BG), the pet dies instantly when revived. I need to revive it once more for it to actually work.

### Expected Blizzlike Behaviour

Pet should be revived right from the first time and not die instantly when revived.

### Steps to reproduce the problem

1. Hunter with a pet
2. Kill the pet
3. Mount up (so the corpse dissapears)
4. Cast Revive Pet
5. Pet gets ressurected and dies instantly
6. Cast Revive Pet again
7. Now pet gets revived as it should

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b5075e9a0a203bb0ee44b232a09e4f5452a39c63

### Operating system

Windows 10 x64 Pro

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Nefertumm** [comment]
@UltraNix can this be related to the last commit about revive pet?

**Comment by valleyss** [comment]
exactly, this Behaviour happened as same as mine.

**Comment by UltraNix** [comment]
@Nefertumm Which one?

**Comment by UltraNix** [comment]
I can't reproduce it.
