### ISSUE TITLE
Effect of "Glyph of Mage Armor" can work without glyph before rebuff

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10264]
Original CC issue: https://github.com/chromiecraft/chromiecraft/issues/2817

### Current Behaviour

Effect of "Glyph of Mage Armor" can work without glyph before rebuff

### Expected Blizzlike Behaviour

Glyph effect should disappear if glyph removed/replaced

### Source

Per original CC issue by user: 
Obvious bug. I don't think any proof is needed here

### Steps to reproduce the problem

1. Use "Glyph of Mage Armor"
2. Use "Mage Armor"
3. Clear/replace "Mage Armor"
4. Look at the unchanged amount of mp5

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b5075e9a0a203bb0ee44b232a09e4f5452a39c63

### Operating system

Windows 10 x64 Pro

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
@acidmanifesto `Steps to reproduce` looks suspicious. If I still have glyph, why the refreshed Mage Armor should have different values?

**Comment by acidmanifesto** [comment]
@UltraNix so this is not a issue? It was a cross post from a cc issue? I will need to know what to tell the original ticket maker on cc before closing

**Comment by acidmanifesto** [comment]
Ah disregard. I see you addressed it on the cc issue. Thank you much.

**Comment by Gultask** [comment]
Confirmed Blizzlike in WotLK Classic
