### ISSUE TITLE
Witch Doctor Zum'rah not dropping loot at all 

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10262]
Original CC Issue Linked: https://github.com/chromiecraft/chromiecraft/issues/2811

### Current Behaviour

after 6 runs in a row nothing has dropped from him what so ever only thing that is dropped is the chest but it doesnt contain any gear just cloth

### Expected Blizzlike Behaviour

should act like every other dungeon boss and at least drop something every kill

### Steps to reproduce the problem

1. Kill then loot the npc.

### Extra Notes

**Notes from original report that was provided:** 
Fix his loot table

**Notes from MDic on the issue:**
NPC info: https://tbc.wowhead.com/npc=7271/witch-doctor-zumrah
As of current All i can say is our loot for this npc is matching with the Universal Database for Loot (UDB) which is based on consolidated sniffs. However wowhead's loot and loot drop is collected thru datamining thru a addon that does get diluted pretty bad from repack and pserver players.
However that is all I can confirm. Now if there are more loot that drops at a different chance that may not of been sniffed I will welcome a second opinion and research of the matter.
![image](https://user-images.githubusercontent.com/16887899/150349617-5d8a906d-6047-4ec8-be25-5c6d460b1922.png)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b5075e9a0a203bb0ee44b232a09e4f5452a39c63

### Operating system

Windows 10 x64 Pro

### Custom changes or Modules

mod-ah-bot
mod-cfbg
mod-chat-transmitter
mod-chromie-xp
mod-desertion-warnings
mod-duel-reset
mod-eluna-lua-engine
mod-ip-tracker
mod-low-level-arena
mod-multi-client-check
mod-pvp-titles
mod-pvpstats-announcer
mod-queue-list-cache
mod-server-auto-shutdown
lua-carbon-copy
lua-exchange-npc
lua-custom-worldboss
lua-level-up-reward
lua-recruit-a-friend
lua-send-and-bind
lua-temp-announcements
lua-zonecheck
lua-zone-debuff

**Comment by UltraNix** [comment]
https://classic.wowhead.com/npc=7271/witch-doctor-zumrah#comments:id=3126114
Honestly I don't see any bug here.
