### ISSUE TITLE
Authserver bug?

### ISSUE THREAD

**Issue by d3tr0l** [azerothcore/azerothcore-wotlk#1027]
After launching the auth, there is this weird line of sql "query" and i am not sure if it is supposed to be there...because i never seen it before in the previous versions.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I believe, it is bug in the code, i did fresh compile, everything is working fine. So, it should not be there?

##### CURRENT BEHAVIOUR:
You launch the authserver.exe and there is this bug:
https://i.imgur.com/wffXYmn.png
I have highlighted that thing.

##### STEPS TO REPRODUCE THE PROBLEM:
1. clone git from day 15. Sep. 2018
2. compile with x64 debug, windows
3. launch authserver.exe

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
commit 205e8eb14e800e81143ea29d8eee2ee22ebecf3c

##### OPERATING SYSTEM:
Win 10 x64, latest update

##### MODULES:
no

##### OTHER CUSTOMIZATIONS:
none

Happening only to me? Is it even a bug or broken code?

##### EDIT:
With a fresh authserver.conf the issue is not there. So i guess i must have changed something, then this started happening. If someone could be that good and explain why is this happening.

**Comment by Meltie2013** [comment]
Its not a bug, you have debug logging enabled. You have it set to 3 instead of 0 or 1.

Ref: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/authserver/authserver.conf.dist#L79

**Comment by d3tr0l** [comment]
Thank you, i was originally thinking, the debug output goes to logfile only :)
