### ISSUE TITLE
server forzen

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10288]
### Current Behaviour

![image](https://user-images.githubusercontent.com/18187177/150495575-bac4cd50-c34c-4027-9388-95588b0e1b38.png)

Enter in the console
`server restart 10` not work.

`save all` not work

`CTRL+C` can end process and gdb.txt
https://gist.github.com/mpfans/ceafba718fb6ed99155e1aaf6bf9d06c

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

a25ef74de3b18cfe6a239ab5874dc78c73929bc5

### Operating system

ubuntu 20.04

### Custom changes or Modules

mod-multi-client-check
mod-anticheat

**Comment by FALL1N1** [comment]
Do you have any firewall or port forwarding setup? Usually getting stuck at Connected (and then the realms pop up) means that you have issues with the worldserver connection.

**Comment by Mitradis** [comment]
any actions for reproduce this problem? What you do in game. This is local server? How many people played when this happened?

**Comment by Winfidonarleyan** [comment]
@mpfans need maximum detailed info:
- Last logging
- `.ser debug`
- ~ players online
- etc

**Comment by acidmanifesto** [comment]
Marked as Waiting For More Info from Author.
