### ISSUE TITLE
Could not compile mod-1v1-arena

### ISSUE THREAD

**Issue by adink1** [azerothcore/azerothcore-wotlk#10290]
### Current Behaviour

I updated it today and found that the module mod-1v1-arena could not be compiled when compiling

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. Update to the latest version
2. Download mod-1v1-arena module
3. compile

### AC rev. hash/commit

/home/ubuntu/azerothcore/modules/mod-1v1-arena/src/npc_arena1v1.cpp:44:9: fatal error: unknown type name 'Tokenizer'
        Tokenizer toks(blockedTalentsStr, ',');
        ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:104: modules/CMakeFiles/modules.dir/mod-1v1-arena/src/npc_arena1v1.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1116: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### Operating system

ubuntu20.4

### Custom changes or Modules

mod-1v1-arena

**Comment by Kitzunu** [comment]
Make an issue on the mod repo
