### ISSUE TITLE
LOG - Improve the logging system

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1029]
##### SMALL DESCRIPTION:

With LogLevel = 3 there is a lot of "useless" information like tons of things loaded, damage done by creatures etc

##### EXPECTED BEHAVIOUR:

We should not see all of this unless we specify a debug log mask like
`16 - Anything related to DB AI, such as SAI, EAI, CreatureAI`

In fact, we should maybe try to port the Logging system from TC which seems way more complete just by looking at the conf: https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/worldserver/worldserver.conf.dist

##### CURRENT BEHAVIOUR:

Too much useless info, it's probably because a lot of the debug msg in worldserver have LOG_NO_FILTER and so it's spamming the console

##### STEPS TO REPRODUCE THE PROBLEM:

1. Set LogLevel = 3 in worldserver.conf
2. Watch the madness ensuing

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9d2fa9a8c9fcb128c1883eb399e018b7e1752154

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/4af4cbd3d966a05c584f4b6c63f69517dad0677d
