### ISSUE TITLE
[PvP stats] Ladder on website appears to mismatch factions after last update and display incorrect results

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10308]
Original CC Issue: https://github.com/chromiecraft/chromiecraft/issues/2842

### Current Behaviour

Looking at the PvPStats ladder vs in-game Score screen after the website maintenance performed on 19th January 2022 reveals that website is not properly handling the crossfaction module, mismatching factions and can also reward wrong team with a win.
Examples of mismatched factions:
https://chromiecraft.com/apps/pvpstats/battleground.php?id=30222
https://chromiecraft.com/apps/pvpstats/battleground.php?id=30248
https://chromiecraft.com/apps/pvpstats/battleground.php?id=30260
All three suggests that I was alliance winning side (which in fact I am) but in the BG I was on the horde side, which actually won the game. You can see it by looking on Bonus Honor column.
For comparison here is the in-game Score screen from the last fight.
![WoWScrnShot_012222_005430](https://user-images.githubusercontent.com/71841180/150621691-6fbd7244-1116-4733-b29a-9184f55e5572.jpg)

This one https://chromiecraft.com/apps/pvpstats/battleground.php?id=30222 also shows that it is possible to allocate win to wrong team if the faction gets mismatched - was assigned to Horde with other player, who left before the end, enemies were in Alliance, we had the draw but my team captured the flag as the last team so we won. Website system still gave points to enemies.

### Expected Blizzlike Behaviour

PvPStats ladder status matches the results displayed in in-game Score screen, properly assigning factions, displaying proper winning time and correctly calculating points for the wins.

### Steps to reproduce the problem

1. Create a character eligible to participate in any Battleground battle
2. Queue for BG
3. Proceed with the Battleground scheme (flag cap, or points battle) to win
4. Take a screen shot on in-game Score screen
5. Open PvPStats ladder from Chromiecraft website's Tools section
6. Find the BG match you have recently played
7. Pay attention to result of the battle, win points from the match and what factions have been assigned to each player, comparing it to the screenshot of in-game Score screen

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Kitzunu** [comment]
Make an issue on the repo for that website thing

**Comment by acidmanifesto** [comment]
> Make an issue on the repo for that website thing

Website thing? This is reference to the pvp score board that shows after a match.

**Comment by FrancescoBorzi** [comment]
> Make an issue on the repo for that website thing

This is a valid bug, because the problem is not in the web app but in the core. I will fix it.

The problem is where the core store the value (`pvpstats_battlegrounds.winnerfaction`), which is now swapped.

https://www.azerothcore.org/wiki/pvpstats_battlegrounds#winnerfaction

The bug has been introduced by this change: https://github.com/azerothcore/azerothcore-wotlk/commit/08f1e861952fdaf48db2ca6c55f73688a3839a49
