### ISSUE TITLE
Feature: GM Command to rename a guild

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#10319]
### Describe your feature request or suggestion in detail

When moderating, we sometime have to rename a guild since it might be way too offensive like `<Gnomes are Better than you>` (please no ban  :D ). Because there are no command about renaming a guild, we have to do a SQL query like the following and then the guild name change would be applied after the server restarts.
```sql
UPDATE `acore_characters`.`guild` SET `name`='Wholesome' WHERE  `guildid`=1;
```

### Describe a possible solution to your feature or suggestion in detail

There is already the `.guild` command which gives the following result.
```### USAGE: .guild ...
Possible subcommands:
|- guild create
|- guild delete
|- guild info
|- guild invite
|- guild rank
|- guild uninvite
```
I am thinking of adding `.guild rename [guild id or old guild name between quotes] "new guild name here between quotes"`

**Comment by Kitzunu** [comment]
You will still require to restart the worldserver as a guild is created on load or create. therefore a restart in necessary. https://github.com/TrinityCore/TrinityCore/commit/678cade1163080263bdea9e349fbb67b7af15ea7#

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10323
