### ISSUE TITLE
Quest The Ring of Blood: The Blue Brothers

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10316]
### Current Behaviour

This quest is also buggy and not complete.

![unknown (1)](https://user-images.githubusercontent.com/58153179/150650035-9f0c9690-186d-4e13-9965-6d24086c251e.png)
![unknown (2)](https://user-images.githubusercontent.com/58153179/150650037-57a62b0b-32c3-434a-b445-22fa5d1a7d12.png)
![unknown (3)](https://user-images.githubusercontent.com/58153179/150650041-9240226f-1bda-4962-ae10-5db209e374c8.png)
![image](https://user-images.githubusercontent.com/58153179/151392108-c10f2283-0d8c-475c-94be-962e169e8c8a.png)

### Expected Blizzlike Behaviour

Objectives
Defeat the Murkblood Twins that call themselves the Blue Brothers.

The Blue Brothers Defeated
Suggested Players [5]

### Source

https://wowwiki-archive.fandom.com/wiki/Quest:The_Ring_of_Blood:_The_Blue_Brothers

### Steps to reproduce the problem

Above

### AC rev. hash/commit

AzerothCore rev. b5ab409614bf+ 2022-01-18 20:25:17

### Operating system

Debian 10 x64

### Custom changes or Modules

None

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/153755054-ea971682-789f-418e-bf52-3d4e28e52d5a.png)

**Comment by htc16** [comment]
@mpfans

**Comment by mpfans** [comment]
639dcec71fa6a299f3e3306a568e6b0a59da9038  work
