### ISSUE TITLE
Command: Character Change Faction

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10315]
### Current Behaviour

When switching factions using the command:

`.character changefaction $name
`

unlocks virtually all flight points

![unknown](https://user-images.githubusercontent.com/58153179/150649843-0337bc25-ce9f-4aa0-a2d8-bd5e5f6f076d.png)

### Expected Blizzlike Behaviour

Above

### Steps to reproduce the problem

Above

### AC rev. hash/commit

AzerothCore rev. b5ab409614bf+ 2022-01-18 20:25:17

### Operating system

Debian 10 x64

**Comment by Kitzunu** [comment]
confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/378539ce7f0fedf5c5a631ca724aef530c664f1a

**Comment by acidmanifesto** [comment]
Fixed via https://github.com/azerothcore/azerothcore-wotlk/pull/9729
