### ISSUE TITLE
Lunar festival commonors wishing a happy Midsummer

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#10321]
### Current Behaviour

Pretty much as the title says. Human commoners in Stormwind are wishing a happy Midsummer/fire festival in January.
![image](https://user-images.githubusercontent.com/68164076/150662509-bc2c090a-5beb-4f46-9fcc-681b09ee6dfb.png)

However, the chat bubble are correct
![image](https://user-images.githubusercontent.com/68164076/150662488-4ee0389e-1d9e-48b2-b01d-19968c78851e.png)

### Expected Blizzlike Behaviour

Should be giving lunar festival gossip during lunar festival.

### Steps to reproduce the problem

.go c 91621, 91619

### AC rev. hash/commit

259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

windows 10

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/150666124-7d2c51cc-baa9-4ef2-aa67-6d728637936e.png)
o_O

**Comment by ishidinho** [comment]
There is also a ticket for this on CC: https://github.com/chromiecraft/chromiecraft/issues/2850.

Affected GUIDs for Human Commoners are:
* `91618`
* `91619`
* `91620`
* `91621`

**Comment by UltraNix** [comment]
Looks okay.
