### ISSUE TITLE
SWP - Kalecgos not Killable

### ISSUE THREAD

**Issue by PsYchoNauTek** [azerothcore/azerothcore-wotlk#10335]
### Current Behaviour

You can't kill Kalecgos, 1st boss at SWP because at low health there is no portal coming up to switch the realms to free Kalcgos mind from Sarthorvar.

### Expected Blizzlike Behaviour

He should open up a rift portal at HP near death so you can go in there and free Kalecgos from Sarthrovar.

### Steps to reproduce the problem

1. .go cr 54810
2. damage Kalecgos untill near death
3. portal should open up but it doesn't

### AC rev. hash/commit

22ec66566c26

### Operating system

Host: Windows Server 2019 | Client: Windows 10 x64

**Comment by Nefertumm** [comment]
Can't confirm. Remember you have to be in a party because the portal can't spawn on the tank. :)
![image](https://user-images.githubusercontent.com/19627365/151220722-d2765887-9506-4296-b276-b11aaf161bb5.png)

**Comment by PsYchoNauTek** [comment]
indeed... totally forgot that the portal doesn't spawn on tank. sry for the false issue then! =)
