### ISSUE TITLE
Cannot open door in Deadmines

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10340]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2855

After killing the first boss and opening the door, If you enter the door and use the lever to close the door, it stays stuck and the inside and outside levers wont open the door.

Tester:

The issue is confirmed. The door does not open after using the lever.

![WoWScrnShot_012422_101135](https://user-images.githubusercontent.com/62797536/150755949-17311cc5-d1d7-484b-a0dc-ee9894766f28.jpg)

There was a PR in 2016 to address this issue: https://github.com/azerothcore/azerothcore-wotlk/pull/269.

### Expected Blizzlike Behaviour

For the door to open/close when using the levers.

### Source

I don't believe a source is needed regarding a stuck door.

### Steps to reproduce the problem

1. Enter deadmines
2. Kill first boss
3. Open door
4. Go inside door
5. Use lever right after door to close the door
6. boom stuck

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Windows 10 21H1 19043.1415

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by devovh** [comment]
## Hello,

```bash
Open: \src\server\game\AI\SmartScripts\SmartScript.cpp
```

## Add:
```bash
        case SMART_ACTION_ACTIVATE_GOBJECT:
            {
                ObjectList* targets = GetTargets(e, unit);
                if (!targets)
                    break;

                for (ObjectList::const_iterator itr = targets->begin(); itr != targets->end(); ++itr)
                {
                    if (IsGameObject(*itr))
                    {
                        GameObject* go = (*itr)->ToGameObject();

                        // Activate
+			(*itr)->ToGameObject()->SetLootState(GO_READY);
                        if (go->GetGoType() != GAMEOBJECT_TYPE_DOOR)
                        {
                            go->SetLootState(GO_READY);
                        }
+                      (*itr)->ToGameObject()->UseDoorOrButton(0, e.action.activateObject.alternative ? true : false, unit);
                        go->UseDoorOrButton(0, !!e.action.activateObject.alternative, unit);
                        LOG_DEBUG("sql.sql", "SmartScript::ProcessAction:: SMART_ACTION_ACTIVATE_GOBJECT. Gameobject {} activated", go->GetGUID().ToString());
                    }
                }

                delete targets;
                break;
            }
```

**Comment by wraix** [comment]
Confirmed experienced this bug first hand on the ChromieCraft server yesterday.
