### ISSUE TITLE
Crash on shutdown

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#10346]
### Current Behaviour

https://gist.github.com/Nyeriah/5a769452c348c895c1419ab52bbc246d

### Expected Blizzlike Behaviour

Don't crash

### Steps to reproduce the problem

.server restart 1200

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
does the crash happen before or after you receive the exit code?

**Comment by Nyeriah** [comment]
It happens before the thing that saves all players (never got the message sent), so it might have something to do with it, not sure @Winfidonarleyan probably knows more about this

**Comment by Winfidonarleyan** [comment]
I test in my core, no crash, hmm
![image](https://user-images.githubusercontent.com/18329778/150835739-996325c3-d282-49b0-82e6-6b0bda2dac8d.png)

**Comment by Kitzunu** [comment]
`The program '[6680] worldserver.exe' has exited with code 2 (0x2).`

I cannot reproduce on windows https://github.com/azerothcore/azerothcore-wotlk/commit/fcee2c4ffe76c739362df7db69644b985eb5056e

Can you try to update to latest master and remove modules @Nyeriah ?

**Comment by Nyeriah** [comment]
> `The program '[6680] worldserver.exe' has exited with code 2 (0x2).`
> 
> I cannot reproduce on windows [fcee2c4](https://github.com/azerothcore/azerothcore-wotlk/commit/fcee2c4ffe76c739362df7db69644b985eb5056e)
> 
> Can you try to update to latest master and remove modules @Nyeriah ?

I've updated to the latest revision but unfortunately can't remove modules as its happening on CC live

**Comment by Kitzunu** [comment]
Can you test it locally with the modules? Because it seems it is not a core issue

**Comment by Nyeriah** [comment]
If it doesn't happen anymore and we can't reproduce it I'll just close it, but since it happened twice now I have to open issues to raise awareness.

 It doesn't happen always and I'm certain I won't be able to reproduce it on the local server, but the issue needs to be opened anyway in case anyone else is experiencing this or has any idea why it is happening

**Comment by Kitzunu** [comment]
I am inclined to think it is some module script causing it as from the stack trace the two last lines that reference our files are

```
#3  ExecuteScript<WorldScript>(std::function<void (WorldScript*)>) (executeHook=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Scripting/ScriptMgrMacros.h:63
#4  ScriptMgr::OnShutdown (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Scripting/ScriptDefines/WorldScript.cpp:103
```
```cpp
void ScriptMgr::OnShutdown()
{
    ExecuteScript<WorldScript>([&](WorldScript* script)
    {
        script->OnShutdown();
    });
}
```
```cpp
template<typename ScriptName>
inline void ExecuteScript(std::function<void(ScriptName*)> executeHook)
{
    if (ScriptRegistry<ScriptName>::ScriptPointerList.empty())
        return;

    for (auto const& [scriptID, script] : ScriptRegistry<ScriptName>::ScriptPointerList)
    {
        executeHook(script);
    }
}
```

**Comment by Nyeriah** [comment]
We don't have any modules that use this hook, it's an empty hook call. If it was any specific module it'd print the module script directly in the crash log :) 

At least there would definitely be at least a single reference about it

**Comment by Nyeriah** [comment]
Closing next Wednesday if no crashes occur and noone else mentions this happening
