### ISSUE TITLE
Feature: switch to `fmt::format`

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#10356]
### Describe your feature request or suggestion in detail

We can replace old C format style (printf and other) to new `fmt::format`

### Additional context

First (seconds) PR for example - #10355

## TODO:
- [x] #10355
- [x] #10366
- [ ] https://github.com/azerothcore/azerothcore-wotlk/pull/6896

**Comment by Kitzunu** [comment]
What if we change FMT_LOG to LOG

And old LOG to OLD_LOG or something. So everyone just defaults to using fmt style logging and then we can convert old later?

**Comment by Winfidonarleyan** [comment]
Logging after assert

**Comment by Winfidonarleyan** [comment]
No end, just start

**Comment by Kitzunu** [comment]
Need try to fix fmt for c++20 first.
Maybe it is possible to use c++17 version of fmt?

**Comment by Winfidonarleyan** [comment]
> I'll say this is pretty done

End after replace 
https://github.com/azerothcore/azerothcore-wotlk/blob/030716421f17bf94d1729a7efd2dce022abee95d/src/common/Utilities/StringFormat.h#L30

**Comment by Kitzunu** [comment]
Just replace it to StringFormatFmt?

**Comment by Winfidonarleyan** [comment]
> Just replace it to StringFormatFmt?

Yes
