### ISSUE TITLE
PvP Heal reduction bug?

### ISSUE THREAD

**Issue by Fo-rek** [azerothcore/azerothcore-wotlk#10357]
### Current Behaviour

There seems to be something wrong with healing reduction, in the tests performed classes like priest & druid were not affected by spells like mortal strike (war) or wound poisson (rogue).
However warrior was affected (using Enraged Regeneration) and reduct heal from talents  was also confirmed.

![penance](https://user-images.githubusercontent.com/24786115/151001261-e723970b-4f61-4098-ae1f-df74629f823f.jpg)
![penancewound](https://user-images.githubusercontent.com/24786115/151001356-2723519b-1b7a-4226-b3cc-80fbaeda14b9.jpg)

![druid](https://user-images.githubusercontent.com/24786115/151001294-d2c788e9-e0ff-4a32-b48b-4d7fc96f7323.jpg)

### Expected Blizzlike Behaviour

Applying this type of spells or poisons healing should be reduced, (Wound poison Healing effects reduced by 25%)

### Source

https://wowwiki-archive.fandom.com/wiki/Reduced_healing

### Steps to reproduce the problem

1. Enemy heals himself without reduced healing spells on him
1. Apply any spell from the list (https://wowwiki-archive.fandom.com/wiki/Reduced_healing) on the enemy target.
2. Enemy heals himself again, (Now his healing should be reduced, but is not)

### Extra Notes

Did not find any discussion of the subject. I am posting this to get a first impression or if it has been discussed previously, I will improve the report with more evidence.

### AC rev. hash/commit
https://github.com/azerothcore/azerothcore-wotlk/commit/58507e2fe8e6

### Operating system

Debian 10

**Comment by pangolp** [comment]
Hello people, good morning. The hash is correct. The compilation was done by me. Forek is a friend, who is helping me to test the maximum level pvp content. I think there is a bug with the github actions that places the tags.

**Comment by Nefertumm** [comment]
Confirmed f8f2d56bf6d159ebaa58fa2f174c9ba86859ac06
