### ISSUE TITLE
Black Lotus at 35.70, 20.60 in Eastern Plaguelands is hidden

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10370]
Original Post: https://github.com/chromiecraft/chromiecraft/issues/2868

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Black Lotus node
  20264 (Entry: 176589) - [Black Lotus X:3152.229980 Y:-3727.000000 Z:133.804001 MapId:0] 
  Found near gameobjects (distance 10.000000): 1 
in Eastern Plaguelands cannot be reached.

### Expected Blizzlike Behaviour

The node should be on the ground and be able to be picked.

### Source

[Black Lotus spawns](https://wowgaming.altervista.org/aowow?object=176589)

### Steps to reproduce the problem

Go to location.
Make sure the node shows up on minimap.
do .gobject near.
Fail to find the node on the ground.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ZhengPeiRu21** [comment]
I have investigate this issue and find that the only difference is that this node Z coordinate appears too high, so it is above ground. All other Black Lotus spawns are on ground level. I don't know if this is the reason for it to prevent the spawning, though; I could try move Z coordinate down to see if that will fix the spawning.

**Comment by UltraNix** [comment]
![obraz_2022-02-05_164800](https://user-images.githubusercontent.com/80540499/152648665-8f42ba2e-9044-4de6-b902-216b99e976f7.png)
Everything is okay with that herb. It is just pooled, that's why you see it via command, but in world.
