### ISSUE TITLE
Deep Freeze damages players with temporary immunity

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10386]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2714

[Deep Freeze](https://wowgaming.altervista.org/aowow/?spell=44572) right now deal damage on temporary immune target to stun, like in my case ,during bladestorm 

Tester:

The issue is confirmed. Tested with [[Free Action Potion]](https://wowgaming.altervista.org/aowow/?item=5634).

https://user-images.githubusercontent.com/62797536/151334461-2f10b01f-a454-4a81-8d30-aabfd6ae1a80.mp4

### Expected Blizzlike Behaviour

Deep freeze should not damage players cause the spell say :" it damage target permanently immune to stuns " (like bosses pve ), and shoould never damage players ( cause players are never permanently immune , just temporary) , so if a mage cast a deep freeze during a bladestorm or similar effect , it should just say immune without damaging the target

### Source

https://wowpedia.fandom.com/wiki/Deep_Freeze

### Steps to reproduce the problem

cast bladestorm or similar 
use deep freeze on them
![WoWScrnShot_010222_171556](https://user-images.githubusercontent.com/96992763/147884674-073ab4a1-7505-4b84-84a1-6a55050a0ecd.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
@UltraNix can you look at it? I tag you because you did the last change to deep freeze 😄
