### ISSUE TITLE
Deep Freeze not consuming Fingers of Frost

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10385]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2853

[Deep Freeze](https://wowgaming.altervista.org/aowow/?spell=44572) doesn't consume the [Fingers of Frost](https://wowgaming.altervista.org/aowow/?spell=44545) buff, allowing 4 spells benefit from a single proc.

i think the issue is with stun inmune mobs, because i have done it both in
dungeon and raid bosses, ill try to find a stun inmune mob to test it.

https://www.youtube.com/watch?v=ot3CVTGLRRA

Tester:

The issue is confirmed. Deep Freeze does not consume Fingers of Frost, if target is not stunnable. Tested on bosses.

https://user-images.githubusercontent.com/62797536/151333347-33668967-5866-4012-8128-66337f858cb9.mp4

Note: The reported linked a video, where he damages a player with temporary immunity. This is a known bug, handled in ticket https://github.com/azerothcore/azerothcore-wotlk/issues/10386.

### Expected Blizzlike Behaviour

Deep Freeze should consume Fingers of Frost when used.

### Steps to reproduce the problem

Get both Fingers of Frost and Deep Freeze talents on a frost mage, get a proc and cast frostbolt deep freeze cold snap frostbolt deep freeze.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@ishidinho Cannot reproduce it. Works okay to me.
![Uploading obraz_2022-02-06_174239.png…]()
