### ISSUE TITLE
Ore Nodes Stack-Spawning 

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10382]
Original Post: https://github.com/chromiecraft/chromiecraft/issues/2881

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

In some zones in the Eastern Kingdoms (Hillsbrad Foothills and Duskwood from what I've personally seen), certain ore spawns seem to double up (Silver/Tin in HF) or in some cases, mass overlap of several ore nodes (Roland's Doom mine in southeast Duskwood, where the Worgen are for the Scythe of Elune quest). 

### Expected Blizzlike Behaviour

In Hillsbrad Foothills, the nodes for Tin and Silver should usually be Tin, rarely Silver. As for Roland's Doom in Duskwood, there should only be a few kinds of nodes that spawn at once, thereby excluding the others that may also spawn in their place (

### Source

Silver/Tin source:
https://classic.wowhead.com/guides/classic-mining-best-farming-basics-early-ores#silver-ore

_Silver Ore comes from Silver Vein, which is a rare version of Tin Vein._

### Steps to reproduce the problem

1. Head to Hillsbrad Foothills
2. Find an ore node (this example is directly south of Tarren Mill by the pond)
3. Ensure no one has mined the node for some time

4. ![image](https://user-images.githubusercontent.com/92193061/151282704-ad08bd34-61e3-48df-b078-01f960edd879.png)

5. ![image](https://user-images.githubusercontent.com/92193061/151282632-efbe337b-1612-4356-b84c-e40a78a5d688.png)

### Extra Notes

From what I can personally tell, it's ore nodes spawning in and not force-excluding others from spawning on top of them when that node is already occupied. I suspect it's an issue across the EK, but I haven't yet seen it outside of mid-lower level zones in the EK. Stranglethorn Vale is clear, from what I remember, but I will continue investigating and seeing if there are any other ore nodes like these spawning in a strange manor in other places on Azeroth.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by virgo77** [comment]
Hi!
Not sure if what I noticed is exactly the same here, but I can't say if it is the AzerothCore that pops too much ores at launch or if the ores pops time after time.

Here are some examples:
Eastern Kingdoms > Redridge Mountains: [image](https://mega.nz/file/dPYDmSZB#jwS-NLQJoQpoRUsmID5lRCejQLYakMcX9aSNpcsLW4M) (look at the minimap) / [video](https://mega.nz/file/oHBzwCxa#NgoLiRN-e-KbYuHsz6QpUHXe8sWhN8XxBHcYR9dl9KQ)
Eastern Kingdoms > Tirisfal Glades: [image](https://mega.nz/file/UfQFXIZI#MkgmQwqKNqE_yXnX7dR9Dva6h1LwSFr-A4ZCkGDvZqA)
Kalimdor > Durotar: [image 1](https://mega.nz/file/4SRDRaRZ#m2dDC63vzMVZ9QGPx60uEQ5Kw2Ye6S_4Eu5iecNYaus) / [image 2](https://mega.nz/file/AHJDyayZ#W7S7x72MPAcN1KH7csP7FuRSUY-RNkPJcHItsiAFsGw) / [image 3](https://mega.nz/file/YeJzEChC#ZFr3bygm89UCWyE3YKOrGU3hPRAw58oWFtl62HVwacc) / [video](https://mega.nz/file/tSJh1Y7J#20gzT0L3C_WoNIs60Fae0LY8ppiBxvNeAEOYSWaMA6s) (look at the minimap)
Kalimdor > Tanaris: [video 1](https://mega.nz/file/YWB3iKJD#v_UecpdnSUvCe02SbODQtyZMBjcBn8jR0Nq40uU3QeY) / [video 2](https://mega.nz/file/JORTyApS#F9PIEGCpxtFZOc1e7JbtCt_TUejU31Qp8gpWpH5-KUI) / [video 3](https://mega.nz/file/AHIlhaJI#dpGIZGH1UdCbhc8wKEIXaHu1EFidskg9i47dFpqF2Cc)
Kalimdor > Thousand Needles: [image](https://mega.nz/file/gGI3kCYR#_NCV8rUfD_vM3ECkL1GOZ8XcNL9dsx9fPQx17LMDFsw) (JACKPOT!!!)

What I can say is that the ores pops again very quickly, between 2 and 5 minutes after mining. So, yes it's pretty cool when farming and leveling mining profession but... i'm not sure it's really logical! :)

Hope it can help ^^

Thanks a lot

V.

**Comment by Buggyswires** [comment]
Duskwood confirmed. There are two multi-spawn nodes in Roland's Doom

I checked the cave after a comment on reddit about the messy ore spawns:
https://www.reddit.com/r/wowservers/comments/z3h9my/comment/ixnbpdl/?utm_source=share&utm_medium=web2x&context=3
