### ISSUE TITLE
I can't get on a horse when I use ShadowDance

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10395]
### What client do you play on?
Original Post: https://github.com/chromiecraft/chromiecraft/issues/2883
ruRU

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

I can't get on a horse when I use ShadowDance (last talent of Rogue).

### Expected Blizzlike Behaviour

you can ride a horse in Shadowdance

### Steps to reproduce the problem

1. Use Shadowdanse
2. Try to use mount

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
<details><summary>SpellWork</summary>

```
ID - 51713 Shadow Dance
=================================================
Description: Enter the Shadow Dance for $d, allowing the use of Sap, Garrote, Ambush, Cheap Shot, Premeditation, Pickpocket and Disarm Trap regardless of being stealthed.
ToolTip: Can use opening abilities without being stealthed.
Category = 0, SpellIconID = 2959, activeIconID = 0, SpellVisual = (11827,0), SpellPriority = 0
Family SPELLFAMILY_ROGUE, flag [0] 0x00000000 [1] 0x02000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00050010 (SPELL_ATTR0_ABILITY, SPELL_ATTR0_NOT_SHAPESHIFT, SPELL_ATTR0_DONT_AFFECT_SHEATH_STATE)
AttributesEx1: 0x00020400 (SPELL_ATTR1_NO_THREAT, SPELL_ATTR1_UNAUTOCASTABLE_BY_PET)
=================================================
Skill (Id 39) "Subtlety"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 60, base 60, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00
RecoveryTime: 60000 ms, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
Duration: ID (32)  6000, 0, 6000
Power POWER_ENERGY, Cost 0 %
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 275 (SPELL_AURA_MOD_IGNORE_SHAPESHIFT), value = 1, misc = 0 (0), miscB = 0, periodic = 0
SpellClassMask = 80000780 00002020 00000000
	+ 703 - Garrote (Rank 1)
	+ 921 - Pick Pocket
	+ 1833 - Cheap Shot
	+ 1842 - Disarm Trap
	+ 2070 - Sap (Rank 2)
	+ 6770 - Sap (Rank 1)
	+ 8631 - Garrote (Rank 2)
	+ 8632 - Garrote (Rank 3)
	+ 8633 - Garrote (Rank 4)
	+ 8676 - Ambush (Rank 1)
	+ 8724 - Ambush (Rank 2)
	+ 8725 - Ambush (Rank 3)
	+ 11267 - Ambush (Rank 4)
	+ 11268 - Ambush (Rank 5)
	+ 11269 - Ambush (Rank 6)
	+ 11289 - Garrote (Rank 5)
	+ 11290 - Garrote (Rank 6)
	+ 11297 - Sap (Rank 3)
	+ 14183 - Premeditation
	- 14902 - Cheap Shot
	- 21060 - Blind
	- 24337 - Ambush
	+ 26839 - Garrote (Rank 7)
	+ 26884 - Garrote (Rank 8)
	+ 27441 - Ambush (Rank 7)
	- 30986 - Cheap Shot
	- 30998 - Cheap Shot (SERVERSIDE)
	- 34097 - Riposte
	- 34099 - Riposte
	- 34242 - Cheap Shot (SERVERSIDE)
	- 34654 - Blind
	- 34694 - Blind
	- 39669 - Ambush
	- 41390 - Ambush
	- 41392 - Riposte
	- 41393 - Riposte
	- 41397 - Confusion
	- 42972 - Blind
	+ 48675 - Garrote (Rank 9)
	+ 48676 - Garrote (Rank 10)
	+ 48689 - Ambush (Rank 8)
	+ 48690 - Ambush (Rank 9)
	+ 48691 - Ambush (Rank 10)
	+ 51724 - Sap (Rank 4)
	- 56404 - Startling Flare

Effect 1:  NO EFFECT

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 36 (SPELL_AURA_MOD_SHAPESHIFT), value = 0, misc = 13 (13), miscB = 0, periodic = 0
SpellClassMask = 00000400 00000000 00000000
	+ 1833 - Cheap Shot
	- 14902 - Cheap Shot
	- 30986 - Cheap Shot
	- 30998 - Cheap Shot (SERVERSIDE)
	- 34242 - Cheap Shot (SERVERSIDE)

```

</details>

not due to the spell it self. Something in the core must limit it.
