### ISSUE TITLE
Large Increase in Update Time Diff

### ISSUE THREAD

**Issue by LannyE** [azerothcore/azerothcore-wotlk#10407]
### Current Behaviour

I updated my core from rev. f8f2d56bf6d1 to rev. fbb50210aa06 and I noticed a large increase in the "Update Time Diff".

Rev. f8f2d56bf6d1 = Update time diff: 96. Players online: 0.
Rev. fbb50210aa06 = Update time diff: 353. Players online: 0.

This seems like a pretty drastic change.  I made no change to the configs.  Just updated the core, added all the modules (updated transmog and AH-bot) then started in the new core.  At that point I noticed the large time difference.  

Anyone else seeing this?

### Expected Blizzlike Behaviour

Time differences shouldn't sway that much between commits.  

### Steps to reproduce the problem

Start AC Worldserver
Look at Update time Diff and compare to time Diff of older revs.

### AC rev. hash/commit

rev. f8f2d56bf6d1 and rev. fbb50210aa06

### Operating system

Windows

### Custom changes or Modules

Modules I run:
> 1v1arena <-- I did update the cpp of this for the new Log changes so it would compile.  Will send the PR later.  
> mod_ahbot <--This was updated with Log changes between AC Revs
> GainHonorGuard
> mod_pvptitles
> SoloLfg
> Solocraft
> transmog <--This was updated with Log changes between AC Revs

**Comment by Nyeriah** [comment]
@acidmanifesto this could be caused by the delays added

@Winfidonarleyan any ideas?

**Comment by Kitzunu** [comment]
@LannyE could you try to revert https://github.com/azerothcore/azerothcore-wotlk/commit/674b168addbc35f1faaa2e72eacee6edf5e0d457 my guess it is the 0.4s delays that happens everytime a unit calls it

**Comment by acidmanifesto** [comment]
> @acidmanifesto this could be caused by the delays added
> 
> @Winfidonarleyan any ideas?

most likely could be the issues. we can always revert if need be and see about debating it with alternative solutions. I only mess with this locally and solo.

**Comment by LannyE** [comment]
I reverted to rev. b085ee6 which is the commit before the Delay was added and the "Update Time Diff" improved to normal levels.

Rev. b085ee6 = Update time diff: 74. Players online: 0.

**Comment by Alastro-Kraken** [comment]
To fix this without disrupting other things it would need to be done in a delayed manner, like I said on that other PR - put killed unit and killer in a container, and process it every 400ms.
Ideally this would be done so for other things too, would solve bugs like #1968 too, but that's so far above my current skill it's not even funny.
