### ISSUE TITLE
Shattrath: not lore frendly npc + 27047 creature text

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#1041]
In Shattrath on Scryers Tier (inside) placed non lore-frendly NPC cupboard-professions trainers.

DELETE FROM `creature` WHERE `guid`=41780;
DELETE FROM `creature` WHERE `guid`=41779;
DELETE FROM `creature` WHERE `guid`=41775;
DELETE FROM `creature` WHERE `guid`=41723;
DELETE FROM `creature` WHERE `guid`=41674;
DELETE FROM `creature` WHERE `guid`=41320;
DELETE FROM `creature` WHERE `guid`=40603;
DELETE FROM `creature` WHERE `guid`=40602;
DELETE FROM `creature` WHERE `guid`=40601;
DELETE FROM `creature` WHERE `guid`=40518;
DELETE FROM `creature` WHERE `guid`=40517;
DELETE FROM `creature` WHERE `guid`=40516;
DELETE FROM `creature` WHERE `guid`=40510;
DELETE FROM `creature` WHERE `guid`=40266;

Error from 27047 NPC about not creature text.
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `TextRange`, `comment`) VALUES (27047, 0, 0, '', 12, 0,  0, 0, 0, 0, 0, 0, '');

**Comment by BarbzYHOOL** [comment]
What is the issue?

**Comment by Meltie2013** [comment]
Can you run this query and post the faction ids for the listed guids?

```
select a.guid as spawnId, b.entry as entry, b.name as creature, b.faction as factionId 
from creature as a inner join creature_template as b on a.id = b.entry 
where a.guid in (41780, 41779, 41775, 41723, 41674, 41320, 40603, 40602, 40601, 40518, 40517, 40516, 40510, 40266);
```

Might have incorrect data.

**Comment by d3tr0l** [comment]
https://www.wowhead.com/npc=33608/alchemy invalid issue. These NPC's ARE lore friendly/blizzlike. No issue with 27047 NPC. Invalid issue report. + Next time please use the issue template in https://github.com/azerothcore/azerothcore-wotlk/issues/new . Can be closed. Tested.

**Comment by d3tr0l** [comment]
If there is an issue, these NPC's in shattrath (training bookcases) propably should not rotate, when you talk to them and move little bit around or if you do not stand in face2face angle. Since, they are NPC's and not Objects, i am not sure if this can be improved.

**Comment by BarbzYHOOL** [comment]
@Meltie2013 

```

spawnId | entry | creature | factionId
-- | -- | -- | --
40266 | 33608 | Alchemy | 1744
40510 | 33609 | Blacksmithing | 1744
40516 | 33610 | Enchanting | 1744
40517 | 33611 | Engineering | 1744
40518 | 33612 | Leatherworking | 1744
40601 | 33613 | Tailoring | 1744
40602 | 33614 | Jewelcrafting | 1744
40603 | 33615 | Inscription | 1744
41320 | 33616 | Herbalism | 1744
41674 | 33617 | Mining | 1744
41723 | 33618 | Skinning | 1744
41775 | 33619 | Cooking | 1744
41779 | 33621 | First Aid | 1744
41780 | 33623 | Fishing | 1744

```

**Comment by Meltie2013** [comment]
@BarbzYHOOL Seems the data is correct on your end. I think people need to learn to update their databases correctly.

**Comment by BarbzYHOOL** [comment]
Ok so it's invalid and this "fix"

```
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `TextRange`, `comment`) VALUES (27047, 0, 0, '', 12, 0,  0, 0, 0, 0, 0, 0, '');
```

is not a real fix (again :P), it doesn't add the text, it adds an empty text if I'm right
