### ISSUE TITLE
[BWL] Halls of Strife spawned creatures issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10418]
### Current Behaviour

There are drakonids in the halls of strife
There are few whelps in the halls of strife
There are no taskmasters in the halls of strife
There are Death Talon Wyrmkin

### Expected Blizzlike Behaviour

There should be no drakonids in the halls of strife
there should be more whelps
there should be taskmasters
There should be no Death talon wyrmkin

Overal, the halls are very empty, it should be busy. See source;

### Source

https://youtu.be/oQUFxe47CKw?t=694

### Steps to reproduce the problem

.go c id 12468

### AC rev. hash/commit
fb8a38c7b3067414a8aaa4450756cc9f9143239a

### Operating system

Linux

### Custom changes or Modules

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by FrancescoBorzi** [comment]
not sure if this is completely fixed as the original solution got partially reverted in:

https://github.com/azerothcore/azerothcore-wotlk/pull/10865

cc @UltraNix
