### ISSUE TITLE
Bug Quest Sabotage

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10413]
### Current Behaviour

Part 8/9 is buggy, impossible to complete.

![image](https://user-images.githubusercontent.com/58153179/151643148-bee0fd9d-ca4d-494a-895e-7ed1748f3734.png)

https://user-images.githubusercontent.com/58153179/151643609-3386749b-4c36-41c8-9581-a51bfbc66111.mp4

### Expected Blizzlike Behaviour

Make your way to the wagons and activate these charges. Once they're set, get clear! The explosion will expose you if you're too close.

https://www.wowhead.com/quest=12676/sabotage

### Steps to reproduce the problem

Above

### AC rev. hash/commit

AzerothCore rev. e8f34b23096d+ 2022-01-25 23:15:51

### Operating system

Debian 11 x64

**Comment by Bogir** [comment]
After you are using Explosive Charges and wagon was broken, then `Scourgewagons destroyed` must set to 1/5 ? Right?

**Comment by htc16** [comment]
@mpfans

**Comment by mpfans** [comment]
@UltraNix   It was fixed once before, but the bug occurred again after the smart script was recently changed, and this quest could not be completed
