### ISSUE TITLE
Crash on command while server running and players online: reload all

### ISSUE THREAD

**Issue by d3tr0l** [azerothcore/azerothcore-wotlk#1042]
EXPECTED BLIZZLIKE BEHAVIOUR:

the command should perform without crash. command done inside console, not ingame.

STEPS TO REPRODUCE THE PROBLEM:
launch auth+world ... login into game...into server console type: reload all
and then just wait for tables reloading and crashing

BRANCH(ES):

master
AC HASH/COMMIT:

commit 205e8eb
-> have not updated since
OPERATING SYSTEM:

Win 10 x64, latest update
MODULES:

no
OTHER CUSTOMIZATIONS:

none

If you can not reproduce the crash, i will post logs.

**Comment by Meltie2013** [comment]
I don't think MySQL version has anything to do with the crash during a reload from in-game. Sounds like more of a internal thing. Pretty sure a table in the reload chain is not up to date within the table structures or your command functions are faulty.

**Comment by d3tr0l** [comment]
Weird. I got the database installed and updated properly. Although i get few warnings when importing the db files to mysql. But that is all the time. So is the fault only on my side or is this a issue?

**Comment by BarbzYHOOL** [comment]
I have a recent AC and it does not crash

**Comment by d3tr0l** [comment]
Barbz do you get some warnings when importing the databases to fresh install? Maybe my db import got somehow screwed up idk. Do you have the db on InnoDB?

**Comment by Meltie2013** [comment]
@d3tr0l Appears to be a computer problem on your end mate. I can clearly see the freeze detection kicked in.

**Comment by d3tr0l** [comment]
> 
> 
> @d3tr0l Appears to be a computer problem on your end mate. I can clearly see the freeze detection kicked in.

So maybe poorly configured mysql server? For example, low resources settings.

**Comment by Meltie2013** [comment]
No... I am pretty sure its your computer.
a) not enough memory installed on your computer
b) you have bad CPU usage.

To run most cores, you need 5GB+ to run them decent enough without issues.

**Comment by d3tr0l** [comment]
My cpu never goes over 25% of usage and memory usage is below 80% all the time. I have 8gb ram. I will try this with different mysql server. I am using atm one included in wamp package which sucks. And i am using the my-innodb-heavy-4G configuration file.

**Comment by d3tr0l** [comment]
Can be closed. My bad. The max core stuck time set to default was the cause of this issue. Increased the time by 10 seconds and now it is wirking fine.

**Comment by BarbzYHOOL** [comment]
hmm i can reproduce this issue
I set MaxCoreStuckTime = 1 and it crashed :D

It seems the intended behaviour though but it's not the first time this setting causes issues
