### ISSUE TITLE
[BWL] Broodlord Lashlayer does not reset.

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10421]
### Current Behaviour

When you wipe on Broodlord Lashlayer, he just stands there and doesn't regenerate hp

### Expected Blizzlike Behaviour

He should go back to where he spawned and get full hp again

### Steps to reproduce the problem

.go c id 12017

### AC rev. hash/commit
fb8a38c7b3067414a8aaa4450756cc9f9143239a

### Operating system

Linux

### Custom changes or Modules

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
@temperrr I can't reproduce it. Please, record a video.

**Comment by temperrr** [comment]
I'll try to get it on video

**Comment by temperrr** [comment]
Hmm on the PTR he is completely broken now. Full on Evade mode.

**Comment by temperrr** [comment]
![Screenshot from 2022-01-31 11-06-18](https://user-images.githubusercontent.com/20357406/151774445-95b67a93-7d65-4cf5-9160-aa431a5d7432.png)

**Comment by UltraNix** [comment]
And have you defeated previous bosses?

**Comment by temperrr** [comment]
That could be related this time

**Comment by temperrr** [comment]
lemme do it correctly this time then...

**Comment by temperrr** [comment]
I think it was a fluke ,closing it for now and see if it happens again during further testing.
