### ISSUE TITLE
CD with RDF

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#10445]
### Current Behaviour

player in same group can enter the same cold downed heroic dungeon with diffrent phase with RDF

### Expected Blizzlike Behaviour

RDF H mode should not make player's cd

### Steps to reproduce the problem

none

### AC rev. hash/commit

AzerothCore rev. e8f34b23096d+ 2022-01-25 23:15:51 +0100 (master branch) (Win64, RelWithDebInfo, Static)

mod-anticheat

mod-eluna-lua-engine

### Operating system

windows 10 x64

**Comment by Kitzunu** [comment]
Wrong. HC dungeons in wotlk do give you a one day lockout.

**Comment by Nyeriah** [comment]
> Wrong. HC dungeons in wotlk do give you a one day lockout.

Nope, not if you queue RDF, specific only. RDF never saves

**Comment by Alastro-Kraken** [comment]
>Nope, not if you queue RDF, specific only. RDF never saves

RDF saves (so you can't do a specific heroic the same day you cleared it in RDF), but it ignores existing locks (so you can do a specific heroic, then do it again if it's rolled in RDF).

**Comment by Kitzunu** [comment]
Works as it should. I am locked for Violet Hold, but can still get it in RDF

![image](https://user-images.githubusercontent.com/24550914/152647883-37447ec8-b251-489b-bfd8-ba53fd4bd97d.png)

And you cannot specific queue locked dungs

![image](https://user-images.githubusercontent.com/24550914/152648027-33359965-fedc-469e-ba4e-95cc82c84829.png)

**Comment by fullofstarschen** [comment]
> 
You can get in,but with no Boss in it.If your teammates are not locked,you can't see them,and both of you couldn't finish this RDF.

**Comment by fullofstarschen** [comment]
Both of you couldn't finish this RDF if you are the only Tank or Healer.

**Comment by Kitzunu** [comment]
Do you mean that the dungeons you are locked to doesnt reset when you queue with RDF?

**Comment by fullofstarschen** [comment]
Yes,and also RDF should not saves.

**Comment by Kitzunu** [comment]
It should
