### ISSUE TITLE
[Raid/ICC] boss Sister Svalna can not killed

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#10444]
### Current Behaviour

Afte boss Sister Svalna cast spell Impaling Spear,player can't pick it ,and boss keep unattackable

### Expected Blizzlike Behaviour

the Impaling Spear should be pickable

### Steps to reproduce the problem

1，combat to Sister Svalna with 2 charachters
2，waiting for boss cast spell Impaling Spear
3，try if Impaling Spear was pickable

### AC rev. hash/commit

AzerothCore rev. e8f34b23096d+ 2022-01-25 23:15:51 +0100 (master branch) (Win64, RelWithDebInfo, Static)

mod-anticheat

mod-eluna-lua-engine

### Operating system

windows 10 x64

**Comment by fullofstarschen** [comment]
fixed，thanks！

**Comment by nachtwolfarg** [comment]
> This issue reappeared,with #10946

I think you should open another issue, or maybe @Nyeriah could reopen this one.

At my server we're having this same issue.
