### ISSUE TITLE
Skinning Scorpid Workers in Valley of Trials

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10447]
https://github.com/chromiecraft/chromiecraft/issues/2902

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The Scorpid Workers which are spawning in the Valley of Trials are dropping higher lever skinables like Medium Leather, hides, or Red whelp scales.
![WoWScrnShot_012922_180802](https://user-images.githubusercontent.com/6341546/151670491-cc9061d6-62f6-45ff-a40e-d9f7e8e0034f.jpg)
![WoWScrnShot_012922_180820](https://user-images.githubusercontent.com/6341546/151670492-40463188-ca74-409e-bf3d-09d7e8be0446.jpg)
![WoWScrnShot_012922_180833](https://user-images.githubusercontent.com/6341546/151670493-a61cf560-5fd0-4ffc-99ba-8e2d17a278d5.jpg)

### Expected Blizzlike Behaviour

The skinning drop should be changed according to the NPC level. 

### Source

- https://www.wowhead.com/npc=3124/scorpid-worker
- Medium Leather, [(https://www.wowhead.com/item=2319/medium-leather)](url)
- Medium Hide, [(https://www.wowhead.com/item=4232/medium-hide)](url)
- Light Hide [(https://www.wowhead.com/item=783/light-hide)](url)
- Light Leather.  [https://www.wowhead.com/item=2318/light-leather](url)
- Red whelp scale [https://www.wowhead.com/item=7287/red-whelp-scale](url)

### Steps to reproduce the problem

1. Check the drop list of the Scorpid Worker
2. Skin the Scorpid 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by betayi** [comment]
there are a lot of diffrent level creature's template skinloot field use the same entry of skin_loot_template ,it's a multi effect issue
