### ISSUE TITLE
Shadowcraft and Darkmantle set energy proc too high 

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10448]
https://github.com/chromiecraft/chromiecraft/issues/2901

### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

The 6 piece set bonus of Shadowcraft and 4 piece bonus of Darkmantle that has a chance to restore 35 energy when attacking is proccing too frequently (I believe it is set to 3 ppm?).

### Expected Blizzlike Behaviour

Darkmantle and Shadowcraft energy proc chance should be much lower, at around 1 ppm. This was confirmed by theorycrafters in Rogue discord and it seems to also match with comment from WotLK.

### Source

https://classic.wowhead.com/spell=27787/rogue-armor-energize#comments
By wingo667 on 2019/12/21 (Classic)
Proc rate was determined to be around 1 PPM per weapon, but it doesn't proc on yellow attacks (so weapon speed effectively doesn't matter). With Slice'n Dice and a bit of hit gear or talents, it should restore >72 energy per minute, for >12% more yellow DPS.

https://www.wowhead.com/spell=27787/rogue-armor-energize#comments
By 43387 on 2009/04/14 (Patch 3.1.0)
I got proc range somewhere between 2% and 4% so I can't say how good is that, and clearly relentles strikes seem way more relayable source of energy returns.

### Steps to reproduce the problem

Equip 4 pieces of Darkmantle gear as a rogue and test on dummy.

### Extra Notes

This makes rogue much more stronger than intended.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by TheDdraig** [comment]
Are we able to find retail footage of this or confirm on retail? I ask because currently spell: 27787 is set to 3% ppm there is no internal cd in the database this may need to be set to fix the issue.

**Comment by godnesso** [comment]
It was confirmed by controlled testing in rogue classic discord to be 1 PPM. There should be no internal cooldown. Just change from 3 to 1

**Comment by godnesso** [comment]
To provide some evidence, this was taken from Rogue Classic Discord where someone attacked a dummy for multiple hours to provide a big enough sample size to roughly determine the proc chance of the set, which is 1 PPM. There is no reason to believe Blizzard retroactively changed the proc chance of this set, and it is highly unlikely to find footage of someone using this set in WotLK (where the size of the sample would be far too small to accurately determine the proc chance). 
![darkmantle](https://user-images.githubusercontent.com/65633456/152705426-c466256c-28b0-44eb-a286-597bf36c4ced.JPG)

https://classic.warcraftlogs.com/reports/caB4YJ9ptPwr7dFR#fight=last&view=events
Within the provided logs from the test (first link), you can see occurances of the effect proccing twice within 2 seconds, which rules out an internal cooldown.
![proc](https://user-images.githubusercontent.com/65633456/152705572-987074ac-e3b8-4e42-bff5-b1652954290a.JPG)
