### ISSUE TITLE
Archavon's Log not working

### ISSUE THREAD

**Issue by mortymo** [azerothcore/azerothcore-wotlk#10450]
### Current Behaviour

The Archavon's Log in Wintergrasp Fortress is not recording wins/losses. 

### Expected Blizzlike Behaviour

it should record all wins/losses

### Steps to reproduce the problem

Just visit Wintergrasp. 
run .bf timer 1 1
run .bf timer 1 5 

Check the log book after. 

### AC rev. hash/commit

d97c95c3fae6

### Operating system

debian 10 x64

**Comment by Alexander990608** [comment]
Anybody???
