### ISSUE TITLE
Can't buff druids with Fortitude

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#10451]
### Current Behaviour

You can't buff druids in bear form with power word: fortitude
![image](https://user-images.githubusercontent.com/47818697/151698797-264b774b-3e85-4ca3-90f3-e3e2536c4c9d.png)

### Expected Blizzlike Behaviour

You should be able to buff druids with power word fortitude regardless of them being in bear form

### Steps to reproduce the problem

go bear form 
try to cast pw: f

### AC rev. hash/commit

3d6724e448f3

### Operating system

Ubuntu 20.04

**Comment by Nyeriah** [comment]
Not just druids

![image](https://user-images.githubusercontent.com/47818697/153293028-27ab2c06-bff9-4bba-8a66-2c4a161edf5b.png)

**Comment by Nyeriah** [comment]
@UltraNix could you please have a look into this one when you got the time?

**Comment by UltraNix** [comment]
@Nyeriah Cannot reproduce it.

**Comment by avarishd** [comment]
Is this still present? No issues on local.
