### ISSUE TITLE
Quest: The Stone Watcher - bugged!

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10458]
https://github.com/chromiecraft/chromiecraft/issues/2899
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

I have now 3 characters that are stuck on this quest. Inserted the Discs into the pedestal. the Hologram appears and I can get this quest from him, BUT after accepting this quest he wont talk to me anymore or offer any way to 'find out more'.
He should be offering a dialogue to do and after than a new quest.
Now the problem is even worse, because the Hologram disappears after a while WITH the Discs stuck inside the pedestal, and no way to make him appear again!
GAME OVER for this quest.
I even tried re-spawning him with another character that had the same quest, deleting the quest, taking it again, but nothing helps...
Please fix these 2 characters that are now stuck: Lexxie, Lindasweet
thanks
PS. I had the same problem like a week ago on my Warlock, and then returned and it worked, but this time nothing helps...

### Expected Blizzlike Behaviour

a functional quest without bugs

### Source

https://classic.wowhead.com/quest=2946/seeing-what-happens
https://classic.wowhead.com/quest=2954/the-stone-watcher

### Steps to reproduce the problem

insert disc, talk to hologram, accept new quest, and then he wont talk to you...

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/5cc5499336d91b5e004efca9b839910a1e9ddd6e
