### ISSUE TITLE
[Alterac Valley] You can pull mini bosses at last boss room without him (reset)

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10460]
https://github.com/chromiecraft/chromiecraft/issues/2897

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

It is possible to pull 1 by 1 of boss adds and reseting boss/adds but only to keep add you're killing.
That way, people destroy 2 towers, boss is then guarded by 2 guards, tank pull 1, they reset boss and another guard, and kill guard solo.

### Expected Blizzlike Behaviour

Whenever boss resets, adds should as well.

### Steps to reproduce the problem

1. Need more people for this, can't reproduce it solo on local AC prob
2. Pull one of adds
3. Get out of range carefully, use spells like vanish, FD when you have aggro on boss
4. Boss resets and his adds continues to get killed by group

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Hyperbearr** [comment]
So I think the way this is reported is wrong slightly. 

The warmasters shouldn't leash at all unless combat with them is dropped completely - in fact they should go on killing sprees and attempt to wipe the whole team no matter how far you run. The flipside of this is that it should be possible to pull the warmasters 1 by 1 using things like feign death or shadowmeld. 

Video 1 - Warmasters dont reset: https://www.youtube.com/watch?v=mTR1ZwylbvU
Video 2 - Warmasters dont reset: https://www.youtube.com/watch?v=TENLFRWVThc
Video 3 - Warmasters cleaning up without Drek - 1 leashes back early and they have split aggro tables: https://youtu.be/jgDuSyY7MrY?t=325

It is/was also possible to pull Drek'thar without adds as per this video:
https://www.youtube.com/watch?v=aprAvcnIJRk

and Vann without adds as per: https://www.youtube.com/watch?v=RNOoWu9AiBQ

These videos demonstrate that the bosses aren't inherently leashed to their adds and it should be possible to pull the boss without pulling the adds through the usual uses of game mechanics. 

Q: So why the work arounds in Videos 1, 2 and 5?
A: Convenience is the reason these tactics were thought up, they're far more reliable in pseudo-pug environments (pre-made discords, AV pugs etc) than trying to utilise FD, pet pulls or tank taunts + player deaths.

**Comment by UltraNix** [comment]
@Hyperbearr So for you there is no bug here?

**Comment by Hyperbearr** [comment]
> @Hyperbearr So for you there is no bug here?

I think there are some small bugs around the edges in terms of aggro radius/warmaster positioning. There is definitely a bug around warmasters resetting when kited too far out of the room (as per the videos, they should basically never reset), but being able to pull vann/drek alone through clever use of game mechanics definitely isn't the bug and is 100% blizzlike behaviour as per the evidence provided.

**Comment by UltraNix** [comment]
Okay, then close. Report other issues as a seperate tickets.

**Comment by temperrr** [comment]
![image](https://user-images.githubusercontent.com/20357406/154931054-6cedc554-7ff6-4da3-889b-633fd6fe8ff3.png)
https://wowpedia.fandom.com/wiki/Alterac_Valley?oldid=2388875

Thank you for your research, however, in tbc AV has changed a bit. See my source above.

**Comment by Hyperbearr** [comment]
Good to know, weird that hasn't been pushed on TBC Classic. 

Do we know if the warmasters resetting upon exiting the boss room is blizzlike WOTLK behaviour or not? I guess it must be if they're leashed to their generals?

**Comment by Nyeriah** [comment]
Reseting once leaving warroom is blizzlike, happens today on retail, there's a line ingame for it, and last I checked that part worked?
