### ISSUE TITLE
Pridewing Wyvern has no death animation

### ISSUE THREAD

**Issue by pagimu** [azerothcore/azerothcore-wotlk#10466]
### Current Behaviour

when I killed that creature (entry 4012) they standing still and shows no death animation.

### Expected Blizzlike Behaviour

They shows death animation

### Steps to reproduce the problem

1. Go to Stonetalon Mountains (middle of the map)
2. Kill creature entry 4012 (Pridewing Wyvern) 

### AC rev. hash/commit

cbe3da09b8a3+

### Operating system

Windows 10 x64 Pro

**Comment by claudiodfc** [comment]
It's the new models patch issue
