### ISSUE TITLE
Clamlette Magnifique triggers 1 minute cooldown on waters

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10476]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2911

Consuming [Clamlette Magnifique](https://wowgaming.altervista.org/aowow/?item=33004) (item id 33004) causes all drinking items to go on 1 minute cooldown.

Tester:

The issue is confirmed.

Edit: The reporter added that this does not only affect mage conjured water. It also affects waters you can buy from the Inn Keeper like Morning Glory Dew (`8766`).

Before using [Clamlette Magnifique]
![WoWScrnShot_020122_114431](https://user-images.githubusercontent.com/62797536/151955314-bd69315f-fa1c-44af-a19e-3e4c4c4f1318.jpg)

After using it
![WoWScrnShot_020122_114439](https://user-images.githubusercontent.com/62797536/151955637-a08dd62d-7a75-47c9-af7f-601af4e37e2a.jpg)

### Expected Blizzlike Behaviour

No cooldown should be triggered apart from a regular 1 second cooldown shared with other consumables. Corresponding Wowhead page says "Cooldown: 1 second."  No 1 minute cooldown mentioned in any wow database. 

### Source

https://www.wowhead.com/item=33004/clamlette-magnifique
https://wowpedia.fandom.com/wiki/Clamlette_Magnifique

### Steps to reproduce the problem

Original report:
1. Consume Clamlette Magnifique (item id 33004)
2. 1 minute cooldown is placed immediately on any water item.

Tester:
1. `.additem 33004`
2. `.additem 22018`
3. `.additem 8079`
4. `.additem 30703`
5. `.additem 8078`
6. `.additem 8077`
7. `.additem 3772`
8. `.additem 2136`
9. `.additem 2288`
10. `.additem 5350`
11. Buy waters from Inn Keeper
11. Use [Clamlette Magnifique]
12. Watch the other items cooldowns

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d6724e448f35ea981d64aff868ce700ab0cbde3

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
https://www.wowhead.com/wotlk/item=33004/clamlette-magnifique#shared-cooldown
Not a bug.
