### ISSUE TITLE
OpenSSL 1.1 on windows

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1047]
##### SMALL DESCRIPTION:

People report issues about windows and openssl 1.1.

##### AC HASH/COMMIT:

f2d16c3003ec17c31e57561e463ddd51097b4e12

##### OPERATING SYSTEM:

Windows 10

##### FIXES TO PORT

Work has already been done by cmangos :D 

https://github.com/cmangos/mangos-wotlk/commit/8000462ad7a3a616ebd997a1e4c6c86e1719980e

https://github.com/cmangos/mangos-wotlk/commit/eddeff7fe9ba49ee1dc2ae7df31c0b1fca4bf247 (improvement for linux)

**Comment by Viste** [comment]
OK WILL BE FIXED
