### ISSUE TITLE
Sindragosa wipes the group but shouldn't

### ISSUE THREAD

**Issue by PsYchoNauTek** [azerothcore/azerothcore-wotlk#10497]
### Current Behaviour

When you kill the 2 Rimefang dragons Sindragosa does appear. When she is about to land she does wipe the full raidgroup
Even if some ppl still are at Valithras bossroom they getting killed!

### Expected Blizzlike Behaviour

Sindragosa should not wipe the raidgroup on landing!

### Steps to reproduce the problem

1. Go to sindragosa (has no guid since is tempspawned from script)
2. Kill the trashmobs
3. Wait untill she lands
4. Now you should instantly die when she is about to land.

### AC rev. hash/commit

0ca0a85c2fff

### Operating system

Host: Windows Server 2019 | Client: Windows 10 x64

### Custom changes or Modules

1v1 Arena
AutoBalance
Individual XP
AHbot
Congrats on levelup
Fireworks on levelup
Phased duels
Double XP weekend
Solo-LFG
Transmogger
Worldchat

**Comment by Rastrian** [comment]
Still happening, gonna try to fix this later.

**Comment by PsYchoNauTek** [comment]
> Still happening, gonna try to fix this later.

For info:

When disabling the spell Sindragosa's Fury she does not wipe the raid on landing.
Maybe you can do something with that information for the fix =)
