### ISSUE TITLE
Dungeon Set Quests from NPC Bodley (ID 16033) Have Incorrect Ordering

### ISSUE THREAD

**Issue by ZhengPeiRu21** [azerothcore/azerothcore-wotlk#10495]
### Current Behaviour

It currently is possible to accept the quests from the "More Components of Importance" series (quest IDs 8985-8988) before completing their required previous quest, quest 8970 "I See Alcaz Island In Your Future...". The PrevQuestIDs and NextQuestIDs in the database for this quest series is appear correct, so I do not know why this quest is showing available early.

The "More Components of Importance" quests are incorrectly appearing now after completing the quest from the first "Components of Importance" series (quest IDs 8962-8965). 
![Capture](https://user-images.githubusercontent.com/98835050/152213684-fec38dd1-b099-4444-886d-1a30ad5f1971.PNG)

### Expected Blizzlike Behaviour

These quests should lead to their corresponding "The Left Piece of Lord Valthalak's Amulet" quest (IDs 8966-8969), which leads to 8970, after which the "More Components" series should appear. 

### Source

This guide gives correct quest order: https://classic.wowhead.com/guides/dungeon-sets-1-2-quests-wow-classic

### Steps to reproduce the problem

1. Complete quest in "Components of Importance" series (IDs 8962-8965)
2. See that "More Components of Importance" quest are available along with correct "The Left Piece" series quest.

### Extra Notes

The DB quest_template_addon for the quests seems correct.

Here is data for "Components of Importance" quests:
![Capture](https://user-images.githubusercontent.com/98835050/152214050-3cc8953a-fc38-4038-af11-3922d964b337.PNG)

Data for Amulet Left Piece follow-up quests:
![Capture](https://user-images.githubusercontent.com/98835050/152214246-656f37db-f0c4-4910-a3c0-d16212c6298b.PNG)

Data for "I See Alcaz Island In Your Future...":
![Capture](https://user-images.githubusercontent.com/98835050/152214375-dffcf1e2-33ff-4783-8f4d-6fdff342bd7b.PNG)

Data for "More Components" series:
![Capture](https://user-images.githubusercontent.com/98835050/152214449-74360db6-b77d-4ffe-b3c4-935a1e9f8c7b.PNG)

### AC rev. hash/commit

AzerothCore rev. c4074be3b64f (custom branch with some small changes but nothing that should affect this quest ordering)

### Operating system

Windows 10 x64

### Custom changes or Modules

Minor core tweaks on my branch but nothing that should affect this. Please feel free to test with clean build if not sure.

**Comment by Nefertumm** [comment]
Already known. https://github.com/azerothcore/azerothcore-wotlk/issues/9825

**Comment by ZhengPeiRu21** [comment]
Sorry, I did not find that duplicate issue. I will comment there with the information here regarding PrevQuestID and NextQuestID as I feel it may be helpful for solving this problem. Thank you @Nefertumm!
