### ISSUE TITLE
2 factors authentification (OTP)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1049]
##### SMALL DESCRIPTION:

We don't have 2 factors authentification.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It uses token_key and requires a website/app API but then it works ingame 
https://cdn.discordapp.com/attachments/383652396175458304/498211568354328588/OP4kPd9.png

##### CURRENT BEHAVIOUR:

We have token_key in the auth account table but not the code for it :P

##### SOLUTION

TrinityCore has it coded both for 3.3.5 and Legion. Look at the "TOTP" files here https://github.com/TrinityCore/TrinityCore/tree/3.3.5/src/server/authserver/Authentication

##### BRANCH(ES):

master

**Comment by Sdyess** [comment]
Is this not 2 factor auth?

**Comment by BarbzYHOOL** [comment]
Yes, proves how much I know about this

**Comment by ForesterDev** [comment]
Code should be generated by third-party programs, f.e. Google Authenticator

**Comment by BarbzYHOOL** [comment]
yes

**Comment by Sdyess** [comment]
Do we have a web interface to interact with this? This relies on time syncing and some other place to verify your identity. Seems pointless to include until such is provided from another project.

**Comment by BarbzYHOOL** [comment]
If it's not included, it will never be "provided" by another project.

Also TC and maybe mangos has it working for a long time.

Note: the developer of blizzlikeCMS wanted to add this for AzerothCore and we realized it was missing, so as you can see, if it's not added, there is no chance that a third party makes use of it :P

**Comment by brussens** [comment]
2FA on AC works for my project. I transferred it manually from TC, the rules are still a query, it works perfectly, it is checked on production.
PS: I would do PR, but I'm afraid I can't stand the style of the code.

**Comment by BarbzYHOOL** [comment]
>  PS: I would do PR, but I'm afraid I can't stand the code style.

What do you mean? which style? @brussens

**Comment by brussens** [comment]
@BarbzYHOOL , I am developing mostly on PHP, where there is an code style standart. I think that AC has the same) I'm afraid that I also can not get through TRAVIS)

**Comment by BarbzYHOOL** [comment]
@BarbzYHOOL if you make the PR maybe we can quickly review/edit it?

**Comment by brussens** [comment]
@BarbzYHOOL In general, nothing particularly difficult to implement)

**Comment by BarbzYHOOL** [comment]
@brussens thank you very much ;) you should join us on the discord too

**Comment by brussens** [comment]
@BarbzYHOOL I'm already there) I asked not so long ago about two-factor authentication. You just answered me, sort of like )
