### ISSUE TITLE
anticheat mod looks like not work

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#10504]
### Current Behaviour

i build anticheat mod in my server , but is looks not work, speed hack is alse can be used, and traveler 3.3.5 also can work.

### Expected Blizzlike Behaviour

when player use speed hack or traveler 3.3.5 or something hack it should be kicked it offline and record.

### Steps to reproduce the problem

i used all the newest version

### AC rev. hash/commit

none

### Operating system

ubuntu 21

**Comment by Bogir** [comment]
Thanks, but we know
What did you expect from free module?

**Comment by Kitzunu** [comment]
Please open an issue on the module's repo
