### ISSUE TITLE
Feature: pool_pool table implementation

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#10527]
### Describe your feature request or suggestion in detail

The core is loading `gameobjects` and `pool_gameobjects`, but not `pool_pool` or at least, I haven't found it. There's no prepared statements and on core load, class `ObjectMgr` only loads gameobjects and joins in the pool_gameobject, saving this ID on a variable.

Gameobjects are supposed to be placed into deeper pools, as sniffs prove on PRs like #9430 . There are coordinates on the map where there can spawn both a copper node or a tin, for example and currently this doesn't work because once a node is consumed, it disappears due to not belonging to any pool.

### Describe a possible solution to your feature or suggestion in detail

Before a gameobject spawns, the core must check how many can spawn from each pool_pool and then select the gameobjects to spawn from pool_gameobject. They will still belong to 1 pool, however it must know what are the conditions for that pool, based on the limit imposed by pool_pool.

This probably needs to be loaded on start up.

**Comment by Kitzunu** [comment]
This should probably be a bug report ngl.

This also includes all pools, not only gameobject
