### ISSUE TITLE
New GM command to display string

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1052]
##### SMALL DESCRIPTION:

A new GM command ".string #ID" to display a string from the database directly ingame.

##### DESCRIPTION:

When we make custom strings with HTML colors for example (actually stored in trinitystring table, yes, we should rename it -_-), we need to test the end result depending on when the string is shown.
A command to display it directly would be very useful. We could make a macro with `.reload acorestring` and `.string 999` to quickly test it.

How should it work?

1) Each string has an ID, so the command could be like this:

```
Command:
.string #id

Example:
.string 999
```

It would show the server's language/locale by default from column `content_default`

2) OPTIONALLY (I suggest to focus on 1) first) we could also add a parameter to display other languages in columns `content_loc1` etc:

```
Command:
.string #id #content_loc_id
Or:
.string #content_loc_id #id

Example:
.string 999 1
.string 1 999
```

**Comment by Sdyess** [comment]
I feel like ".string" is really non descriptive as to what it does. I think a better command name would be suited, i.e. like matching what the table is called and possibly changing the name of the table from something other than trinity_string to also be something more descriptive.

**Comment by BarbzYHOOL** [comment]
I think .string is good but if you have a better name, np. And for the table name, trinity wasn't very inspired but I guess the most logical name would be "strings" lol

Also we can add the default help when typing .string it says what it's about.

**Comment by gengarshadowball** [comment]
I don't understand the concept, would please elaborate? Why would you want to save random strings on a miscelaneous table?

**Comment by Viste** [comment]
Very dangerous command. Working with strings, not the best part of C++.

**Comment by BarbzYHOOL** [comment]
it's not more dangerous than using anything that makes use of strings already -__-, each string is already called somewhere else so it's already "dangerous"

the goal is ONLY to show up what the string looks like because we can format the strings with colors etc...

actually, if we want to style a string, we have to repeat the command that displays the string and that's not practical at all depending on when the string is triggered

**Comment by peti446** [comment]
Just as a small update, trinitystring is not the name anymore as it is now acore_string.
