### ISSUE TITLE
Arthas 25 H

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#10534]
### Current Behaviour

In arthas 25H, several bugs were found in the encounter:

1- Paladin's Judgment of Light heals arthas

2- Face 2 of arthas the Reaper of Souls kills instantly with more than 100K of Damage

 - The boss when he throws reaper must be instantaneous and does not wait 5 seconds to throw it (https://wotlk.ultimowow.com/?spell=73798)

 Damage Example : The Lich King's Soul Reaper hits Benzin, dealing 43530 Shadows.(1501410 Resisted) (696568 Absorbed) (2763193 overcapacity)

3 - When the Valkyries are stunned, it makes them Jump out of the stun in the position where they should be without being stunned

4- The horrors often come out of graphics.

5 - The Totem of the shamans and the pets of the players even in passive mode take agro

6- The enraged Horores many times the damage they do is superior to 150K and the tanks with the defensive thrown kill them.
7-The warrior's charge does not work when he brings you a valkyrie, (Out of ICC if the warrior's charge works well)

8 - The flash of light should leave a heal over time on the player who has the sacred shield on (This even outside of icc does not work)

### Steps to reproduce the problem

Enter icc 25h and start the fight with arthas 

### Extra Notes

Server: [www.sking.nat.cu](www.sking.nat.cu)

### Operating system

Debian x64

**Comment by Tony931023** [comment]
@FrancescoBorzi  @Kitzunu

**Comment by Kitzunu** [comment]
Add commit/hash

**Comment by Tony931023** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/666aca2a633cd80af0a5588f68ae6576b6648581 latest server update

**Comment by Xyloo77** [comment]
Confirmado

**Comment by steel385** [comment]
Confirmed

**Comment by PabloE1** [comment]
Confirmed

**Comment by Voyka91** [comment]
Confirmed

**Comment by Voyka91** [comment]
Confirmado y faltan algunos x comentar

**Comment by Kyu1234** [comment]
Confirmed

**Comment by Tony931023** [comment]
> Confirmado y faltan algunos x comentar

Por favor algun bug mas encontrado en arthas decirlo

Please any more bug found in arthas tell

**Comment by Nefertumm** [comment]
'Confirmed' is not enough, please add hash commit to the issue.

**Comment by acidmanifesto** [comment]
确认的

**Comment by Fullknyfe** [comment]
Concuerdo con lo reportado.

**Comment by Nefertumm** [comment]
@Tony931023 if you don't stop your players to comment 'Confirmed' in spanish, I'll lock the issue.

**Comment by Tony931023** [comment]
@Nefertumm I think that is not in my hands, each user is free to leave their opinion regarding the issue, apart from several people who confirm that they have this error, it does not mean that they come from the same server, even if they do not give a solution or do not have the knowledge to do it, it is not bad that several people confirm that they have the same error, AzerothCore is a community, perhaps nobody had previously dared to present this problem with arthas, they simply came looking for a solution, found the reported problem and gave their humble opinion with a confirmed So that they know what is happening, I cannot force people to write in English either.

**Comment by Kitzunu** [comment]
I will close this issue for two reasons.

1. You are reporting 9 different issues in 1 report. Please open new issues that contain only one bug per report.
2. You are not following the bug report template. Open new issues and follow and fill in the template as it should.
