### ISSUE TITLE
[Class quest][Rogue] 20 - The touch of Zanzil (Alliance) - Quest doesn't complete

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10568]
https://github.com/chromiecraft/chromiecraft/issues/2978

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Start quest, lay down. Doc Mixilpixil runs around, nothing happens.

### Expected Blizzlike Behaviour

Quest should complete

### Source

https://user-images.githubusercontent.com/76611816/152675019-c016cd6b-a9ed-48b9-984f-6c0db8ff40f3.mp4

### Steps to reproduce the problem

1. Be a Dwarf Rogue
2. Get to lvl 20, get the Rogue quest for the thistle tea
3. Get to the lockbox in Westfall, get poisoned by the Touch of Zanzil
4. Be a dwarf, heal it with Stoneform cause you can
5. Return the quest, guy thinks you are still sick of the touch of Zanzil even though you are not (Completely normal phenomenon)
6. Go to Doc Mixilpixil to get cured of the Posion you don't have
7. Get poisoned by the doc so he can cure you of it.
8. Lay down, enjoy the gnome running around
8. Quest gets stuck. You have the poison again.
9. Abandon quest, restart it, now already poisoned when you get the quest
10. Video displays the rest

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=2608

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
Fixed in this commit #11046
