### ISSUE TITLE
Invalid goals of quest "The Ring of Blood: The Blue Brothers" (9967)

### ISSUE THREAD

**Issue by brussens** [azerothcore/azerothcore-wotlk#1056]
Invalid goals of quest "The Ring of Blood: The Blue Brothers" (9967)

##### SMALL DESCRIPTION:

The quest is counted in the murder of one of the two NPCs, when it should be counted in the murder of both.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest counts when both NPCs are killed.

##### CURRENT BEHAVIOUR:

Quest counts when killing one of the NPC.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Take the quest 9967.
2. Kill one of two quest NPC.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Last revision.

##### OPERATING SYSTEM:

Debian 9 x64

##### MODULES:

Anticheat. Transmogrification.

##### OTHER CUSTOMIZATIONS:

None.

##### Screenshots:
![wowscrnshot_101918_130730](https://user-images.githubusercontent.com/2656715/47216276-12063600-d3ad-11e8-8e4a-5d43ff5a0e81.jpg)
![wowscrnshot_101918_130750](https://user-images.githubusercontent.com/2656715/47216277-12063600-d3ad-11e8-936c-10d4677d8caa.jpg)
![wowscrnshot_101918_130806](https://user-images.githubusercontent.com/2656715/47216279-12063600-d3ad-11e8-8b27-d8347a563003.jpg)
![wowscrnshot_101918_130809](https://user-images.githubusercontent.com/2656715/47216280-12063600-d3ad-11e8-84b0-d7eec8b71bef.jpg)

**Comment by a4501150** [comment]
Update quest_template set requiredNpcOrGo2 = another npc’s entry in creature_template and it’s required amount

**Comment by BarbzYHOOL** [comment]
More info here https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130261/quest+template

**Comment by brussens** [comment]
@a4501150 yes, it's works. But it not blizzlike behavior. See on screenshots.
![wowscrnshot_102018_074717](https://user-images.githubusercontent.com/2656715/47251368-9bb11480-d43c-11e8-996e-a03965639b7a.jpg)
![wowscrnshot_102018_074710](https://user-images.githubusercontent.com/2656715/47251369-9c49ab00-d43c-11e8-879d-aab03a2297b4.jpg)
Blizzlike implies the lack of display of the required count killed NPC.

**Comment by a4501150** [comment]
> @a4501150 yes, it's works. But it not blizzlike behavior. See on screenshots.
> ![wowscrnshot_102018_074717](https://user-images.githubusercontent.com/2656715/47251368-9bb11480-d43c-11e8-996e-a03965639b7a.jpg)
> ![wowscrnshot_102018_074710](https://user-images.githubusercontent.com/2656715/47251369-9c49ab00-d43c-11e8-879d-aab03a2297b4.jpg)
> Blizzlike implies the lack of display of the required count killed NPC.

Umm not quite understand. What is blizzard behavior？you mean the goal shows “kill two brothers” 1/1 ?   If we wanna achieve this and the two NPCs have different entry then we must use script to handle this quest

**Comment by alexkulya** [comment]
@brussens 
The fix I did on SunwellCore, here it is also nice.
<pre>
DELETE FROM `smart_scripts` WHERE `entryorguid` = 18399 AND `source_type` = 0 AND `id` > 3;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 18471 AND `source_type` = 0 AND `id` > 27;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
-- Murkblood Twin - Store Variable Decimal
(18399, 0, 4, 0, 6, 0, 100, 0, 0, 0, 0, 0, 63, 1, 1, 0, 0, 0, 0, 19, 18471, 200, 0, 0, 0, 0, 0, "Murkblood Twin - On Just Died - Set Counter"),
-- Gurgthock - Counter 2 = Quest Complete, Reset Counter, Self Data 11 11
(18471, 0, 28, 29, 77, 0, 100, 0, 1, 2, 0, 0, 26, 9967, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, "Gurgthock - On Counter Set 1 2 - Quest Credit 'The Ring of Blood: The Blue Brothers'"),
(18471, 0, 29, 30, 61, 0, 100, 0, 0, 0, 0, 0, 63, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Gurgthock - On Counter Set 1 2 (Link) - Reset Counter"),
(18471, 0, 30, 0, 61, 0, 100, 0, 0, 0, 0, 0, 45, 11, 11, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Gurgthock - On Counter Set 1 2 (Link) - Set Data 11 11 (Self)");
</pre>

**Comment by brussens** [comment]
@alexkulya its really good) Thx a lot) Its works perfectly!)
