### ISSUE TITLE
[Class Quest][Death Knight] 12720 - How to Win Friends and Influence Enemies

### ISSUE THREAD

**Issue by TonyMacDonald1995** [azerothcore/azerothcore-wotlk#10575]
### Current Behaviour

Attacking Scarlet Crusade enemies with Keleseth's Persuaders equipped does not trigger quest dialogue and complete quest.

### Expected Blizzlike Behaviour

Should have chance on hit for Scarlet Crusade to say various dialogue and ultimately end with

> Crusader says: I'll tell you everything! STOP! PLEASE!
> Crusader says: We... We have only been told that the "Crimson Dawn" is an awakening. You see, the Light speaks to the High 
> General. It is the Light...
> Crusader says: The Light that guides us. The movement was set in motion before you came... We... We do as we are told. It is what must be done.
> Crusader says: I know very little else... The High General chooses who may go and who must stay behind. There's nothing else... You must believe me!
> You say: LIES! The pain you are about to endure will be talked about for years to come!
> Crusader says: NO! PLEASE! There is one more thing that I forgot to mention... A courier comes soon... From Hearthglen. It...
> Scarlet Preacher dies from the torture.

and mark the quest ready for turn in.

### Source

https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies

### Steps to reproduce the problem

1. Create Death Knight
2. Progress to quest "How to Win Friends and Influence Enemies"
3. Open Ornately Jeweled Box
4. Equip Keleseth's Persuaders
5. Attack Scarlet Crusade enemies in New Avalon

### AC rev. hash/commit

AzerothCore rev. f73f131315e2 2022-02-06 22:57:20 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.78.0
Using MySQL version: 100605
Using CMake version: 3.22.1
Compiled on: Linux 5.15.16-1-MANJARO
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 252191207 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2199390740 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_02_06_00
Using Character DB Revision: 2022_01_29_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Manjaro x64

**Comment by ChibaPet** [comment]
Also seeing this.

**Comment by kheina** [comment]
the proper solution to this (to get the persuaders to work as intended) is in TrinityCore's codebase

```sql
update item_template set spellppmRate_1 = 1 where entry = 39371; -- persuader
```
https://github.com/TrinityCore/TrinityCore/blob/49cf605ef158cffe047d13b14920e47d4568e62f/sql/old/3.1.3/05131_world_scripts_dk.sql#L3

**Comment by heyitsbench** [comment]
Unable to reproduce on 8ef8ddad24b8d85c66549692143a8110caa8eae0, took some time but a Scarlet Preacher did end up doing the RP and gave credit for the quest.
