### ISSUE TITLE
Health and Mana Low Regen

### ISSUE THREAD

**Issue by virgo77** [azerothcore/azerothcore-wotlk#10573]
### Current Behaviour

Hi!
I noticed that when we start to gain a greater level, the HP and Mana are lower to regen
Actually, i play a hunter and HP and Mana are very slow to regen as long as the level is greater

### Expected Blizzlike Behaviour

HP and Mana are faster to regen, even in combat or not.

### Steps to reproduce the problem

Just play and test the regen on each level (GM Command or not)

### AC rev. hash/commit

AzerothCore rev. dfa28e4f7dfe 2022-02-01 18:01:42 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows Server 2022 Standard

### Custom changes or Modules

None. I test as is.

**Comment by duncrafter** [comment]
This could be intended behavior, as HP tends to outstrip health regeneration after lvl 15.

**Comment by T1ti** [comment]
that's normal.

**Comment by duncrafter** [comment]
Health regeneration rate was changed in Cata:
https://wowpedia.fandom.com/wiki/Health_regeneration

**Comment by ZhengPeiRu21** [comment]
Though this is working as intended, if you would like to change the rate to something higher on your own server, you can add value to gtoctregenhp_dbc table to override it.

**Comment by duncrafter** [comment]
Or change global health regeneration modifier in worldserver.conf
