### ISSUE TITLE
 [BWL] Chromaggus - Brood Affliction Bronze

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10584]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Two issues currently:
1) Chromaggus applies Brood Affliction: Bronze to the raid too frequently
2) Brood Affliction: Bronze re-stuns the target every fifth second, with a duration of 4 seconds, meaning you'd spend 80% of the fight stunned. 

### Expected Blizzlike Behaviour

Correct behaviour:
Less frequent casts
The stun from Brood Affliction: Bronze should be a randomised and significantly longer interval. 

### Source

https://youtu.be/2Gbe5x1PNJQ?t=225

Rogue with the debuff gets stunned once every 30 seconds on average with a small variation in intervals

### Steps to reproduce the problem

Pull Chromaggus with multiple characters
Receive the Bronze Affliction near instantly on all characters
Stun continues to maintain an 80% up-time indefinitely

### Extra Notes

Reported: https://github.com/chromiecraft/chromiecraft/issues/2952

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Hmm.
Wowhead/DBC files say that Bronze Affliction should stun target every 5 sec.

**Comment by UltraNix** [comment]
@temperrr Also need an info: so all people should get the same affliction, e.g. all players get bronze and then all players get blue. Or maybe every player can get different affliction. eg. tank get bronze and healer get blue.

**Comment by temperrr** [comment]
Hmm wowpedia report
![image](https://user-images.githubusercontent.com/20357406/153709139-b56a51b8-5692-4b99-b014-276e96d1979f.png)
https://wowwiki-archive.fandom.com/wiki/Chromaggus

All players will get the same affliction per pulse. This is random. Video in original report also shows the rogue being affected but up to 30 seconds he is not stunned by the bronze one. 

I am not sure where to find more helpful information for you.

**Comment by UltraNix** [comment]
Okay. This "random intervals" looks weird to me. I will try to do more reserach.
