### ISSUE TITLE
[Love is in the Air] Apothecary Hummel not work

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10588]
### Current Behaviour

Today is the first day of Valentine's day. I have a conversation with apothecary Hummel and can't start the battle

![image](https://user-images.githubusercontent.com/18187177/152997116-3380a62c-8907-4f81-8b24-8cfca8d2cd54.png)

![image](https://user-images.githubusercontent.com/18187177/152997002-d70e3cac-a833-4b95-955e-f430eabd5f92.png)

### Expected Blizzlike Behaviour

Talk to apothecary Hummel and fight!

### Steps to reproduce the problem

1. debug lfg
2. talk `Apothecary Hummel`
3. No response

### AC rev. hash/commit

AC> AzerothCore rev. 7b041946e163+ 2022-02-04 23:39:05 +0000 (master branch) (Unix, RELWITHDEBINFO, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80028
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-91-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/polly/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/polly/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/polly/data/mmaps. Total size: 2199390740 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_02_04_13
Using Character DB Revision: 2022_01_29_00
Using Auth DB Revision: 2022_01_23_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

ubuntu 20.04

### Custom changes or Modules

> List enable modules:
- mod-anticheat
- mod-multi-client-check

**Comment by Nyeriah** [comment]
Got broken here https://github.com/azerothcore/azerothcore-wotlk/commit/2af6e0ee20999dcbfdd41e2316fb778f9114efae#diff-70182e99034c06b40138007002d0dd5ec586c1a01f7a38cffd6e2540785d6eb6
