### ISSUE TITLE
[Love is in the Air] Flirt With Disaster achievement not working

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10585]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2987

I got drunk and smashed, i use a perfume "Enchantress" Perfume from the event vendor, i throught a Handful of Rose Petals on Sraaz, then i kiss him and the achievement is not completed

Edit (@ishidinho): Same problem with the Horde achievement, too.

![WoWScrnShot_020822_100438](https://user-images.githubusercontent.com/62797536/152953908-65f65e92-548a-45b7-9726-28c2cc580dc3.jpg)

### Expected Blizzlike Behaviour

Should i got the achievement completed if i follow all the steps i said before.

### Steps to reproduce the problem

First i found the npc Sraaz walking around the center of Ironforge, then I got drunk and smashed, i used a perfume "Enchantress" Perfume from the event vendor, i throught a Handful of Rose Petals on Sraaz, then i kiss him and the achievement is not completed

Edit (@ishidinho):
1. `.go creature 31804`
2. Used [[Flagon of Mead]](https://wowgaming.altervista.org/aowow/?item=2594) three times until I got smashed
3. Put on [["Enchantress" Perfume]](https://wowgaming.altervista.org/aowow/?item=49857).
4. Used [[Handful of Rose Petals]](https://wowgaming.altervista.org/aowow/?item=22218) on [Jeremiah Payson](https://wowgaming.altervista.org/aowow/?npc=8403)
5. `/kiss` on Jeremiah Payson

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by lemondsMs** [comment]
hi 

Test this
 Put on [ ["VICTORY" Perfume]](https://wowgaming.altervista.org/aowow/?item=49856).

**Comment by ishidinho** [comment]
Oh, great. It worked with VICTORY.
So, we should check again with every perfume on both sides, Horde and Alliance.

**Comment by Underminus** [comment]
Historically it has been only Victory, Forever and Enchantress Perfumes that work. Interesting to see that Victory works but Enchantress doesn't.

**Comment by ishidinho** [comment]
@Underminus Do you have a source for that?
