### ISSUE TITLE
The title disappears after re-entering the game.

### ISSUE THREAD

**Issue by ockap** [azerothcore/azerothcore-wotlk#1059]
The title disappears after re-entering the game.

rev. 1d5407a9d929+

Operating system: Debian 8

Modules: No

Other Customizations: No

**Comment by BarbzYHOOL** [comment]
this makes no sense

**Comment by poszer** [comment]
What title exactly?

**Comment by ockap** [comment]
any title.

**Comment by poszer** [comment]
Well thats the problem from your side. You did something wrong im sure.

**Comment by poszer** [comment]
@ockap Well thats the problem from your side. You did something wrong im sure.

**Comment by Melanholyx** [comment]
but this is right, titles dissapearing on my server aswell!

**Comment by poszer** [comment]
@Melanholyx Than you have done something wrong too. Im using AC on 3 machines, and doesnt have this issue on any of them.
Tell me, On what AC version you are?

**Comment by BarbzYHOOL** [comment]
create a VALID github issue
