### ISSUE TITLE
quest 13003, cannot be done

### ISSUE THREAD

**Issue by cshaaa** [azerothcore/azerothcore-wotlk#106]
**Description**:
i cannot get on the dragon,and the quest cannot be completed
**Branch(es)**: master 
**AC hash/commit**:  f81ec2b
**Modules**: no
**Operating system**:  debian 8.x

**Comment by DantestyleXD** [comment]
Quest can be completed.
Correct dragons are spawn at Phasemask 4 and you can grab them with the item.
Try with .gm on command, you will see them.

I found some wrong mechanics and I will report them.
Thank you

----------------------------
Server: Local (Repo AzerothCore)
Last commit hash tested: 0ba91d7c3ee994607a6e0437ab47c2c79ba1ab0a
O.S.: Windows 10
Compiler: MS Visual Studio 2013
