### ISSUE TITLE
Quest An Undead's best friend

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10609]
### Current Behaviour

Can't feed the puppies!

![image](https://user-images.githubusercontent.com/58153179/153255222-497789c3-70c7-463b-932c-8637abbd226a.png)
![image](https://user-images.githubusercontent.com/58153179/153255242-1aa16638-3baf-4d4e-aa4b-6f586e9f4d2a.png)

### Expected Blizzlike Behaviour

As is usual practice, the undead at the saronite quarry to the southwest starve plaguehounds to keep them extra aggressive. Use the shade to get up close and feed some of those hounds and I promise you they'll be content to leave you alone, if not side with the hand that fed them.
Don't get too close to those things until you've fed them though. Their noses don't fall victim to your shade's elusiveness.

https://www.wowhead.com/quest=13169/an-undeads-best-friend

### Steps to reproduce the problem

above

### AC rev. hash/commit

AzerothCore rev. 7bed30a52db4+ 2022-02-09 11:11:13

### Operating system

Debian 11 x64

**Comment by Meramaf** [comment]
Confirm it. Steps to reproduce the problem

1. .quest add 13169 
2. .go xyz 8118.26 2816 565 571 2.3
3. .learn 58524  (Control Eidolon Watcher)
4.  Cast Feed Hungering Plaguehound 58562 on NPC 30952

**Comment by Bmtcoder** [comment]
confirm
