### ISSUE TITLE
Quest Is that your Goblin part 9 of 16

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10608]
### Current Behaviour

there is no way to attack the NPC to advance the quest

![image](https://user-images.githubusercontent.com/58153179/153254848-ebd3d727-e4ca-47ee-b39c-b72cb4699402.png)
![image](https://user-images.githubusercontent.com/58153179/153254592-dab59ccb-241e-44aa-bde4-fcf659c59b29.png)

### Expected Blizzlike Behaviour

https://www.wowhead.com/quest=12969/is-that-your-goblin#map

### Steps to reproduce the problem

above

### AC rev. hash/commit

AzerothCore rev. 7bed30a52db4+ 2022-02-09 11:11:13

### Operating system

Debian 11 x64

**Comment by PsYchoNauTek** [comment]
can confirm that!

**Comment by nyhmii** [comment]
There is a simple fix. The Fix is 2 quests down the line, and use the same FLAGS and SMART_SCRIPT entries as the 6 sisters when dueling. The EASIEST FIX is to  .set faction permanent 190 (the duel starts then).

**Comment by htc16** [comment]
@mpfans

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10988  fixed
