### ISSUE TITLE
Cross faction can talk with expression (/E)

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10600]
### Current Behaviour

in game use `/E` ,Cross faction can talk.... `/S` work.

![image](https://user-images.githubusercontent.com/18187177/153105561-00cc66e6-a65b-4f16-955c-faf1ce70c7b3.png)
![image](https://user-images.githubusercontent.com/18187177/153105653-61252052-86f3-4817-8b26-e216f7f33254.png)
![image](https://user-images.githubusercontent.com/18187177/153105731-d2e58c6a-e525-4037-8b09-a5c5f864917e.png)

### Expected Blizzlike Behaviour

Unable to use / E to talk, it can only show that the other party has made a strange action

### Steps to reproduce the problem

1.Create two new accounts and establish roles in different faction
2.Two people stand together, and then use /E to make an expression respectively

### AC rev. hash/commit

AC> AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/7b041946e163224cb82ba85e734c9a757fa4209f+ 2022-02-04 23:39:05 +0000 (master branch) (Unix, RELWITHDEBINFO, Static)
Using SSL version: OpenSSL 1.1.1f 31 Mar 2020 (library: OpenSSL 1.1.1f 31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80028
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-91-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/polly/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/polly/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/polly/data/mmaps. Total size: 2199390740 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_02_04_13
Using Character DB Revision: 2022_01_29_00
Using Auth DB Revision: 2022_01_23_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

ubuntu 20.04

### Custom changes or Modules

List enable modules:

mod-anticheat
mod-multi-client-check

**Comment by UltraNix** [comment]
It's completely blizzlike. As it's an emote chat, you can write there anything you want.
