### ISSUE TITLE
Quest The Air Stands Still

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10607]
### Current Behaviour

is supposed to use the horn to summon a Knight of Ebon Blade

![image](https://user-images.githubusercontent.com/58153179/153254147-e8713e85-c01e-4c5a-9c6e-bccb71966567.png)
![image](https://user-images.githubusercontent.com/58153179/153254344-7e4a44ac-1da4-4845-b006-61006409a8c8.png)
![image](https://user-images.githubusercontent.com/58153179/153255722-126f9ab5-f47b-42dc-87f0-e8dadcecbdc0.png)

### Expected Blizzlike Behaviour

https://www.wowhead.com/quest=13125/the-air-stands-still#map

### Steps to reproduce the problem

above

### AC rev. hash/commit

AzerothCore rev. 7bed30a52db4+ 2022-02-09 11:11:13

### Operating system

Debian 11 x64

**Comment by nyhmii** [comment]
Managed to Fix the issue. Ill post the Smart_scripts Sql update soon.

**Comment by nyhmii** [comment]
Go to each respective point. This requires you to  .cast #spell in order

Example at thhe respctive NPC's(targets)
.cast 57910
.cast 57911

Morgrain
.cast 57890
.cast 57892

.cast 57916
.cast 57917

This fixed the issue when using the "War Horn Of Archerus"

**Comment by htc16** [comment]
@mpfans

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12349 

fixed
