### ISSUE TITLE
[Outland] Impossible "Master Enchantment": NPC Felannia

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10606]
### Current Behaviour

Outland Master Enchanting Npcs are opening an Enchanting Suplies Npc window, so it is not possible to evolve the Enchanting profession to Master enchanting and follow the progress in the profession.

![image](https://user-images.githubusercontent.com/58153179/153253330-b9ea672d-f7c6-4dcb-bfdf-6e84eed3a7cf.png)
![image](https://user-images.githubusercontent.com/58153179/153252759-2db4325f-53cf-4cef-b735-5d2e6873ca47.png)
![image](https://user-images.githubusercontent.com/58153179/153252810-02349152-a989-4608-be6f-b2f4f45f3abd.png)

### Expected Blizzlike Behaviour

easy to understand

### Steps to reproduce the problem

above

### AC rev. hash/commit

AzerothCore rev. 7bed30a52db4+ 2022-02-09 11:11:13

### Operating system

Debian 11 x64

**Comment by htc16** [comment]
More details of the problem:

The Master Enchanting option appears in the normal **dk**, he is not an enchanter... In the picture above, it does not appear.

![image](https://user-images.githubusercontent.com/58153179/153297054-d90a205d-1e66-4342-b093-d6cd4e1684cc.png)

**Comment by duncrafter** [comment]
Felannia currently has no gossip menu assigned (which would be needed to select vendor or trainer function) and is missing the Gossip npcflag.

**Comment by htc16** [comment]
> Felannia currently has no gossip menu assigned (which would be needed to select vendor or trainer function) and is missing the Gossip npcflag.

@UltraNix

**Comment by htc16** [comment]
@mpfans

**Comment by mpfans** [comment]
639dcec71fa6a299f3e3306a568e6b0a59da9038

work
