### ISSUE TITLE
Quest The Bones of Nozronn

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10610]
### Current Behaviour

This mission does not end.

![image](https://user-images.githubusercontent.com/58153179/153256250-69db93cd-ac9a-43ec-a281-6ab5e751f665.png)
![image](https://user-images.githubusercontent.com/58153179/153255885-ad38bc21-16a7-4923-8a65-d5915c0376b1.png)

### Expected Blizzlike Behaviour

https://www.wowhead.com/quest=12544/the-bones-of-nozronn

### Steps to reproduce the problem

above

### AC rev. hash/commit

AzerothCore rev. 7bed30a52db4+ 2022-02-09 11:11:13

### Operating system

Debian 11 x64

**Comment by mpfans** [comment]
@UltraNix   It was fixed once before, but the bug occurred again after the smart script was recently changed, and this quest could not be completed,tyvm
