### ISSUE TITLE
db error on latest versions 

### ISSUE THREAD

**Issue by Riveir** [azerothcore/azerothcore-wotlk#10625]
### Current Behaviour

 
![2022-02-05 (7)](https://user-images.githubusercontent.com/96812524/153505399-d8476434-726b-4c61-8de7-86d95516a266.png)

So I am using the most recent version of the core (AzerothCore rev. cfb171efda7e 2022-02-05 16:32:25 -0500 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) as of the posting of this issue as well as the most current version of the ah-bot mod. 
commit hash cfb171efda7e1376c3f771f3fca517a4a30bbe67

> Incorrect value '-34040' for type 'unsigned int'. Value is raw ? 'false'
> Table name 'npc_vendor'. Field name 'item'

### Expected Blizzlike Behaviour

Not sure 

### Steps to reproduce the problem

Compile core

### Extra Notes

I was asked to post this as a core issue though at first thought it was an issue with AH-bot

### AC rev. hash/commit

cfb171efda7e1376c3f771f3fca517a4a30bbe67

### Operating system

windows 10 64

### Custom changes or Modules

AH-Bot

**Comment by Riveir** [comment]
Just compiled again with this commit 5febb28b4c59a7beb1f4be840cbeb32bd1c3d68e

**Comment by Kitzunu** [comment]
Nothing in the load function is pointing to unit as item https://github.com/azerothcore/azerothcore-wotlk/blob/5febb28b4c59a7beb1f4be840cbeb32bd1c3d68e/src/server/game/Globals/ObjectMgr.cpp#L8693

cc @Winfidonarleyan

**Comment by Riveir** [comment]
![2022-02-11](https://user-images.githubusercontent.com/96812524/153687293-89f6564d-2055-4b8f-bac5-19ad04f2c20d.png)

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-ah-bot/blob/21e8bc6763531e02f3cda597ec0d9963315eaa7f/src/AuctionHouseBot.cpp#L794

**Comment by Kitzunu** [comment]
Open an issue on the mod repo @Riveir
