### ISSUE TITLE
Rogue talent: Ruthlessness

### ISSUE THREAD

**Issue by Swordalife** [azerothcore/azerothcore-wotlk#10629]
### Current Behaviour

Apparently no active effect at the moment of submission (11.02.2022  14:00)

### Expected Blizzlike Behaviour

The talent should grant a combo point (60% chance of triggering at 3/3) after a finishing move is done by the player.

### Source

https://wotlkdb.com/?spell=14161

### Steps to reproduce the problem

Leveled 5 levels without a single proc.

### AC rev. hash/commit

Not sure

### Operating system

Windows 11

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/10328
