### ISSUE TITLE
Assertion Failed Movespline.cpp

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#1063]
**Description:**
Dunno why, For the first time I see this error/crash.  (Movespline.cpp Assertion Failed)
I'll include crash log.

**Current behaviour:** Tell us what happens
The server just crashed after 8 days.

**Reference**
Screenshot of error: https://prnt.sc/l9tggt
Crash Log: [1d5407a9d929+_worldserver.exe_[24-10_4-27-3].txt ](https://gist.github.com/poszer/b2520777cb3e887a11105f90c3ec3056)

**Branch(es):** 0.x / 1.x / master (Specify the branch(es) affected by this issue)
Master

**Operating system:**
Win Server 2012 R2 x64

**Modules:** Are you using modules? if yes, list them
Transmog, BossAnnouncer, DuelReset, Buffer, BeastMaster.

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/552 there is a temporary fix here but it's a critical issue :(

**Comment by poszer** [comment]
@BarbzYHOOL Okay, this is serious problem now. In 2 days, 2 crash ( Yesterday in 4:27, Today in 4:34 )

Crash Log: [1d5407a9d929+_worldserver.exe_[25-10_4-34-3]  ](https://gist.github.com/poszer/b0fd6ba96877a60c7f2ca98d708d9d57)

**Comment by BarbzYHOOL** [comment]
apply the fix then

**Comment by poszer** [comment]
@BarbzYHOOL Yeah. I'll try with it :triumph:

**Comment by grimgravy** [comment]
trinitycore fixed the problem of this type[https://github.com/TrinityCore/TrinityCore/pull/22582/commits/2d43be202fb489b94bdbf4adc10e27fa49deada5](url)

**Comment by poszer** [comment]
@grimgravy  Hmm, thanks for reply

**Comment by poszer** [comment]
Reopened 
Crash Log: [7f3a0c3eaae5+_worldserver.exe_[1-11_3-50-3].txt  ](https://gist.github.com/poszer/8f029a93fafbf430e613aa43790efeb9)

**Comment by poszer** [comment]
Temp fix :
[49525db](https://github.com/azerothcore/azerothcore-wotlk/pull/1066/commits/49525dbe3c37913fa6023312ebaa3605b6abbd95)

**Comment by BarbzYHOOL** [comment]
stop opening and closing poszer, it will be closed automatically
