### ISSUE TITLE
Boss in Pit of Saron Can not kill

### ISSUE THREAD

**Issue by adink1** [azerothcore/azerothcore-wotlk#10630]
### Current Behaviour

Boss tyrannus at last position is unattackable ,can not enter combat, so can not be killed

### Expected Blizzlike Behaviour

boss should enter combat

### Source

No response

### Steps to reproduce the problem

1,enter instance pit of saron
2,kill boss garfrost and boss krickandick
3,wait in front of boss tyrannus
4,watch , no trigger to enter combat, and boss was unattackable

### Extra Notes

No response

### AC rev. hash/commit

#10440

### Operating system

Ubuntu 20.04

### Custom changes or Modules

No response

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/10123

**Comment by adink1** [comment]
The same problem as last time reappeared, in the latest version

**Comment by Wowkasu** [comment]
Dungeon can not be passed completely! You can only kill two bosses. The passing algorithm fails and does not continue.
on the picture:
1. Silvana is standing still and not going anywhere.
2. No ghouls appear.
3. Two packs of mobs do not appear on the slope.
4. Scourgelord Tyrannus does not fly to the top and the final battle with him is not possible
![2022-02-16 11-29-37 World of Warcraft](https://user-images.githubusercontent.com/68443208/154223693-7c6b6ac0-5996-4952-88fc-7332b095bbc5.jpg)
