### ISSUE TITLE
Agnetta Tyrsdottar cannot enter combat

### ISSUE THREAD

**Issue by adink1** [azerothcore/azerothcore-wotlk#10655]
### Current Behaviour

Mission: Is That Your Goblin?
Agnetta Tyrsdottar cannot enter combat, After the dialogue, you will be out of the battle, unable to fight.

### Expected Blizzlike Behaviour

challenge and fight

### Steps to reproduce the problem

1. Talk to Agnetta Tyrsdottar
2. fighting

### AC rev. hash/commit

[e1711e2](https://github.com/azerothcore/azerothcore-wotlk/commit/e1711e28f79ea7c00968ac486a5207d9b252c232)

### Operating system

Ubuntu20.04

**Comment by adink1** [comment]
Son of Hodir reputation quest

**Comment by avarishd** [comment]
Closed by #10988
