### ISSUE TITLE
[BWL] Lord Victor Nefarius shoots lasers during Vaelastrasz RP 

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10661]
### Current Behaviour

During the Vaelastrasz RP, Lord Victor Nefarius shoots multiple lasers through the room.

![WoWScrnShot_021322_161518](https://user-images.githubusercontent.com/62797536/153760337-909c0964-02ef-4d04-8251-17495a04aab5.jpg)

![WoWScrnShot_021322_161527](https://user-images.githubusercontent.com/62797536/153760339-69e6ca77-da03-475a-a3e8-35c0b2aa891f.jpg)
 

### Expected Blizzlike Behaviour

He should cast one laser towards Vaelastrasz as seen here: https://youtu.be/7STH3FbP2po?t=597

### Steps to reproduce the problem

1. `.go creature 84512`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

**Comment by acidmanifesto** [comment]
This is insanely awesome and I vote we keep this in the game. Our founding father Pussywizard would be soo proud of us.

**Comment by TheDdraig** [comment]
Who doesnt like disco lights while fighting a boss?

**Comment by malcrom** [comment]
Yeah I've see. This. Number of targets needs to be set to one on spellmgr.cpp

**Comment by Nyeriah** [comment]
Target conditions alone won't work?

**Comment by Nefertumm** [comment]
> Target conditions alone won't work?

Yes, they should work.

**Comment by temperrr** [comment]
NOOOOOOOOOOoooooooooo :(
