### ISSUE TITLE
dungeon reset on death with dungeon finder

### ISSUE THREAD

**Issue by Orystal** [azerothcore/azerothcore-wotlk#10679]
### Current Behaviour

Dungeon reset after character death

### Expected Blizzlike Behaviour

Monsters should not spawn after exiting the dungeon by death

### Steps to reproduce the problem

Die in dungeon alone and return for corpse using dungeon tool in solo

### AC rev. hash/commit

AzerothCore rev. 49191da0f856+ 2022-02-13 10:15:15 +0000 (master branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-solocraft
mod-solo-lfg

**Comment by dunjeon** [comment]
That is a SoloLFG module issue - post the error there.

**Comment by Kitzunu** [comment]
Closing per previous comment
