### ISSUE TITLE
Improve ".pinfo" command (display IP and acc_name)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1067]
##### SMALL DESCRIPTION:

We don't seem to have a command to check the IP and the account_name of a player ingame

##### EXPECTED BEHAVIOUR:

Maybe we could add it to the existing command ".pinfo" since that command is rather shitty actually

##### AC HASH/COMMIT:

4b6342b42f6f3421c25da7b176c6438a4da88543

**Comment by BarbzYHOOL** [comment]
Even better screenshot https://image.prntscr.com/image/qgh8-dxlTWCtyHGhOEKaYw.png (but formatting is quite easy)

**Comment by Viste** [comment]
> Even better screenshot https://image.prntscr.com/image/qgh8-dxlTWCtyHGhOEKaYw.png (but formatting is quite easy)

get 403 when go to link

**Comment by BarbzYHOOL** [comment]
yes, it's improved (i need to fix the link tho), we can add much useful info to .pinfo
