### ISSUE TITLE
[Spell] [Paladin] Divine Shield not Immunity Frost Trap and other slowdown effect

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#10671]
### Current Behaviour

Divine Shield not Immunity Hunter's Frost Trap and  Death Knight's Desecration

### Expected Blizzlike Behaviour

Divine Shield should Immunity slowdown effect

### Steps to reproduce the problem

1.cast 642
2.an other player use Frost Trap or Scourge Strike

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Windows 10 x64

**Comment by r0m1ntik** [comment]
UP, confirm on https://github.com/azerothcore/azerothcore-wotlk/commit/24a80a16e6d850b445361cac907f748fa9235c20
