### ISSUE TITLE
Some herbs give a "That is already being used" error

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10682]
Original CC issue: https://github.com/chromiecraft/chromiecraft/issues/2908
### Current Behaviour

PR CC Report. Possible Gameobject issue maybe:
Very rarely, there are some herbs that cannot be gathered (even if you have enough herbalism skill). Trying to right click on them gives a "That item is already being used" error.

### Expected Blizzlike Behaviour

All Herbs should be able to be gathered.

### Steps to reproduce the problem

Personal Notes to help reproduce the issue by the user:

So far, I have been unable to create new bugged herbs.

However, the Silverleaf node at (56.47, 54.70) in Teldrassil is bugged as of 1430 ET, Jan 31.
The Peacebloom node at (61.79, 61,29) in Teldrassil is also bugged as of 1430 ET, Jan 31.

These nodes have been bugged since at least 1340 ET, Jan 28. Both of them are on the main ChromieCraft server.

### Extra Notes

I have tried to gather the nodes on two different characters. Both of them hit the same error with only those herbs, while being able to gather other herbs just fine. From this, I believe this is a server side issue and not a character specific issue.

Some staff suggested that it might be a bug related to gathering at max range due to a discrepancy between client-side and server-side range checks, which was fixed some time ago. I tested by standing directly on top of the herb while gathering - the same error occurred.
I also tested on the public test server by gathering some herb nodes as close to max range as I could, but I was unsuccessful in creating a new bugged herb node.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d6724e448f35ea981d64aff868ce700ab0cbde3

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
I can't reproduce it on my local.
