### ISSUE TITLE
[VMAPS] Crash INSTANT

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#1068]
##### STEPS TO REPRODUCE THE PROBLEM:

1. Compile the source!
2. Download latest data from https://github.com/wowgaming/client-data/releases
3. when start worldserver Get this error -> ERROR: VMap file './vmaps/000.vmtree' is missing or points to wrong version of vmap file. Redo vmaps with latest version of vmap_assembler.exe.
4. if i disable vmap with conf files and set them to 0 server run without VMAP 

##### BRANCH(ES): Latest - Master!

master

**Comment by poszer** [comment]
Dowload data files from this link, and try with them:
DBC, MAPS, VMAPS, MMAPS

https://mega.nz/#!utg3hKJL!TtSzcWxVkvxF4HJvor8LFWhrBwwpH2pHpI-xHGr-HZo
