### ISSUE TITLE
Hunter Pet and Combat Issues related

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#10683]
CC ISSUES: 
https://github.com/chromiecraft/chromiecraft/issues/2928
https://github.com/chromiecraft/chromiecraft/issues/2934

### Current Behaviour

CC Issue:
https://github.com/chromiecraft/chromiecraft/issues/2928
When entering combat with hunter pet, after the target (mob) is dead, it takes up to 10 seconds for the player to leave combat.

Without pet (dismissed) leaving combat is working properly (and it takes about 2 seconds after the target is dead).

Currently using Devilsaur as pet. Cant say if its related with pet using any of its abilities, as I couldn't find those affecting it.

This applies to PVP as well. It seems that pet is keeping me in combat for way longer than it should be. It sometimes takes around 10 seconds to drop combat, which is gamebreaking.

CC Issue:
https://github.com/chromiecraft/chromiecraft/issues/2934
Currently when you feign death in PVP (with macro, so you can /stoppattack /petpassive too), it drops combat, but then immediately you enter combat again, without doing anything or being attacked and u have to wait up to 10 seconds to leave combat again.

This seems to be related with - [Hunter] Dropping combat takes way too long when pet is active https://github.com/chromiecraft/chromiecraft/issues/2928 as without Pet, Feign Death is dropping combat properly.

### Expected Blizzlike Behaviour

Player should leave combat when fighting with pet just as fast as fighting without pet (probably around 2 seconds after target is dead).

Feign Death should drop combat and not reenter combat automatically again, if there isnt anything attacking you or you attacking anything. You should be able to mount up right away after FD, for example.

### Steps to reproduce the problem

CC Issue:
https://github.com/chromiecraft/chromiecraft/issues/2934

Create a hunter and summon your pet
Engage higher level mob (I tested in Blasted Lands) with hunter and pet
After mob is dead, count the seconds it takes to leave combat

(steps without pet, where it works normally)

Create a hunter
Engage higher level mob (I tested in Blasted Lands) with pet dismissed
After mob is dead, count the seconds it takes to leave combat

CC Issue:
https://github.com/chromiecraft/chromiecraft/issues/2934

Create a hunter with pet
Enter BG
Attack a player with both pet and your character
Call pet back and Feign Death

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
Cannot reproduce it.

**Comment by slicplaya** [comment]
I now have this bug as well. I can also confirm, and also add, using Feign Death drops combat, then immediately re enters. Even if doing so twice, and even if using shadowmeld with pet on passive. Any dot on the pet also keeps the player in combat until the ENTIRE duration is gone. Even if it's a debuff from say a shadow priest adding shadow dmg etc. After I had a weird bug with my pet dropping through the map in a BWL raid, the pet has been combat bugging since. I'm going to test a different pet and see if it persists.
Feign Death is properly dropping combat, but the pet seems to continuously be in a state of combat for a long period of time ie 10-14 seconds. Using Feign death or Shadowmeld will drop combat but instantly re enter because of how the pet is linked to the hunter and some weird combat bugged state. If a player puts a debuff or dot on the pet, both will be stuck in combat until it's dispelled and time passes or the duration finishes. This is insanely huge for PvP. Please address this issue. It's insanely frustrating.

**Comment by Kitzunu** [comment]
Open a new issue.
