### ISSUE TITLE
Quest The Gift That Keeps On Giving - Class DK

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10699]
### Current Behaviour

The Gift of the Harvester item does not breed ghouls.

![image](https://user-images.githubusercontent.com/58153179/154150125-a6b9d287-7e1a-4ba8-975d-59b05e6a6f8f.png)

### Expected Blizzlike Behaviour

[Gothik the Harvester](https://www.wowhead.com/npc=28658/gothik-the-harvester) at Death's Breach has given you the [Gift of the Harvester](https://www.wowhead.com/item=39253/gift-of-the-harvester) to use on Scarlet Miners. Create 5 [Scarlet Ghouls](https://www.wowhead.com/npc=28845/scarlet-ghoul) with the device and return the ghouls to Gothik.

https://www.wowhead.com/quest=12698/the-gift-that-keeps-on-giving

### Steps to reproduce the problem

This quest is for the Death Knight class, just accept it, as pointed out above.

### AC rev. hash/commit

AzerothCore rev. 49191da0f856+ 2022-02-13 10:15:15

### Operating system

Windows 10

### Custom changes or Modules

None

**Comment by htc16** [comment]
@mpfans

**Comment by mpfans** [comment]
tested 639dcec71fa6a299f3e3306a568e6b0a59da9038

work

**Comment by Bartucian** [comment]
Does not work.
