### ISSUE TITLE
DB/Quest: Thrusting Hodir's Spear script

### ISSUE THREAD

**Issue by DantestyleXD** [azerothcore/azerothcore-wotlk#107]
**Description**:
From the issue #106, I did execute some test for resolve the issue.
There are some wrong mechanics that cannot leave players to complete the quest.

**Current behaviour**: 
1 - When the player is on the drake can't dodge the NPC attacks by the vehicle's spell
2 - (Minor) Less "waypoints" block the drake to go around "10/20" yards from the place where player starts event
3 - (Minor) Wrong place of one spell on the second drake bar (Button 5 and Button 6)

**Expected behaviour**: 
1 - Using the Dodge vehicle's spell, with the correct timing, players can dodge the drake attack adviced by a message "DODGE"
2 - Drake need to go around for the entire zone (Sons of Hodir's base include)
3 - On the second bar, there are two spell and need to be at Button 2 and Button 6

**Steps to reproduce the problem**:
1. Do .quest add 13003, .gm on for see drakes without phase's spell, .gm fly on and .go xyz 7322.151367 -2393.083496 807.835083 (near there are drakes call "Wild Wyrm"
2. Use the quest item on a Wild Wyrm drake
3. Try to complete the quest without use .mod hp command =P

**More information**:
Quest ID: 13003
Creature ID: 30275
Dodge Spell ID: 56704
Button 5 -> Button 2 Spell ID: 56706
Video for the correct event: https://www.youtube.com/watch?v=7fH8YstRmAQ

**Branch(es)**: 
master

**AC hash/commit**:
0ba91d7c3ee994607a6e0437ab47c2c79ba1ab0a

**Modules**:
Nothing

**Operating system**: 
Windows 10
##

**Comment by DantestyleXD** [comment]
Update:
**Current behaviour: **
1 - Player can dodge by spell but only in ONE exactly moment.
Spell can dodge the attack only in an exactly moment immediatly after the sound of message.
New Issue:
4 - In phase 2, if you do nothing, you can stay on the drake's jaws and no happen. 

**Expected behaviour: **
1 - Spell need grants a dodge for 2 seconds but I tested immediatly before the attack and 2 seconds before and no dodge.
4 - If you do nothing, drake will kill your character.

**Comment by Si1ker** [comment]
There are stuff missing like alerts/emotes but I was not able to confirm the "parry" issue with its ability (number 2).
