### ISSUE TITLE
Hero Mode The Nexus Boss Anomalus cannot be killed

### ISSUE THREAD

**Issue by adink1** [azerothcore/azerothcore-wotlk#10718]
### Current Behaviour

Hero mode The Nexus BOSS Anomalus in the second stage of the release of space-time rift no mobs out

### Expected Blizzlike Behaviour

There must be a little monster coming out

### Steps to reproduce the problem

1. team up The Nexus
2. Battle with Anomalus
3. Anomalus starts to summon mobs
4. Mobs do not appear, Anomalus cannot be killed

### AC rev. hash/commit

dbd7680f5bb7c5ab2076e01196c6ec6e277c065d

### Operating system

Ubuntu 20.04

**Comment by fullofstarschen** [comment]
I can confirm this,i have to edit spell.dbc to to solve this issue.

**Comment by Meramaf** [comment]
Confirm

**Comment by avarishd** [comment]
rev. de50ce3
Could not reproduce.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/c251c948-475f-4ee5-a0be-2d02173db894)
