### ISSUE TITLE
Trial of Champions Stage 1 Error

### ISSUE THREAD

**Issue by adink1** [azerothcore/azerothcore-wotlk#10717]
### Current Behaviour

When the Champion's Trial starts, the NPC in the middle does not leave, the first stage cannot end, and the BOSS cannot end when only 1% HP is left.

### Expected Blizzlike Behaviour

should end normally

### Steps to reproduce the problem

1. Team into the instance
2. Talk to NPC
3. (NPC didn't walk away) Start the fight
4. The final boss does not die or leave

### AC rev. hash/commit

dbd7680f5bb7c5ab2076e01196c6ec6e277c065d

### Operating system

Ubuntu 20.04

**Comment by adink1** [comment]
It can be confirmed that this problem only occurs on the alliance side
After entering the instance, talk to the NPC. After the champion of the three teams appears, the NPC should exit the stage, but he still remains in the middle of the field.

**Comment by fullofstarschen** [comment]
There is also a very badly bug. When the NPC is still remains, the  box can be refreshed and looted  again and again, and you can get the Emblem of Triumph indefinitely in this battle.

**Comment by Tony931023** [comment]
confirmed a very old error that has not yet been solved

**Comment by UltraNix** [comment]
Cannot reproduce it.

**Comment by mpfans** [comment]
If you want to fight to the end, there will be a camp champion 1HP following you and attacking, but you can't attack him

**Comment by UltraNix** [comment]
@mpfans Still nothing - none of the NPC have 1 hp upon  entering 2nd phase of the encounter.

**Comment by mpfans** [comment]
Maybe 5 players will appear?

**Comment by UltraNix** [comment]
I can't test it on 5 accounts.

**Comment by Tony931023** [comment]
@UltraNix 

https://user-images.githubusercontent.com/4868094/204133014-b59707c9-5dce-48b0-a6db-d43a8abfff04.mp4

**Comment by mpfans** [comment]
> 

yes... sometimes one, sometimes two champions

**Comment by UltraNix** [comment]
I tried trillion timer on horde and alliance with different NPCs setup - works okay to me. 
Sorry, but I can't help with that.

**Comment by DoubleSpout** [comment]
> Maybe 5 players will appear?

I have test 5 players, on alliance characters. On normal or hard model, the bug still occur. Boss left 1% hp, attack us, and it can not be selected, so we have to use gm command `.die` to kill him.

**Comment by DoubleSpout** [comment]
> I tried trillion times on horde and alliance chars, with different NPCs setup - works okay to me. Sorry, but I can't help with that.

may be new version fix this problem?  My server git commit:

Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Thu Nov 17 23:35:05 2022 +0000

    chore(DB): import pending files

    Referenced commit(s): e54be1e5e607d9fc30b2e2b998fee46486fece39

shall I need to update to lastest version?

**Comment by smellbee** [comment]
this bug still exists, rev [a3a835edc4c19fd506bda12d3995670410fde28f ](https://github.com/azerothcore/azerothcore-wotlk/commit/a3a835edc4c19fd506bda12d3995670410fde28f) 

make this instance totally unplayable

**Comment by avarishd** [comment]
Re-created the same attempts as the video above with alliance characters, 10 attempts with 3 characters with different variation of overkills (just in case) and **could not reproduce**.

If the bug still persist and someone can reproduce, it should be labeled as Priority-High.
