### ISSUE TITLE
Trial of the Champion - Black Knight NPC

### ISSUE THREAD

**Issue by Halokillerman7** [azerothcore/azerothcore-wotlk#1072]
Despawning Boss. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Hops off his ride and starts to kill your party like a normal instance boss.

##### CURRENT BEHAVIOUR:
Hops off his ride and despawns with or without GM mode active can not see him.
https://imgur.com/a/6eGcbzY

##### STEPS TO REPRODUCE THE PROBLEM:
Run into Trial of Champion and kill the npcs until the boss appears. Did not test with full party.

**Comment by Perkebme** [comment]
Darnassian intrusion shows a wrong spot on the map

**Comment by poszer** [comment]
Yeah, wrong spot

**Comment by poszer** [comment]
@BarbzYHOOL Yess. It's a valid issue
