### ISSUE TITLE
[Love is in the Air] Crown Hoodlum are level 1

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10725]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/3070

The mobs you have to kill for "Crushing the Crown" are level 1.

https://user-images.githubusercontent.com/91145640/154291923-00c34e90-b5f6-4e45-aa20-20086a97bdba.mp4

Tester:

The issue is confirmed.

![image](https://user-images.githubusercontent.com/62797536/154652815-0c5b3154-a8b8-4277-a75c-f428c6375be1.png)

### Expected Blizzlike Behaviour

They should be level 33-34 because the repeatable quest changes depending on the level of your character / zone.

### Source

https://wowwiki-archive.fandom.com/wiki/Crown_Hoodlum

Relevant Quest: https://wowgaming.altervista.org/aowow/?quest=24648

### Steps to reproduce the problem

`.go creature 244617`

1. Go to Dustwallow Marsh 61.55, 39.41.

One Example GUID:

DB GUID: 244617, current GUID: 8001.
Current Entry: 38006 of (38006, 0, 0).
DisplayID: 30578 (Native: 30578).

### Extra Notes

Now, I checked WotlK databases and they say they should be level 1, but that doesn't make any sense. They should have the correct level for the repeatable quest / zone.

Also, one Sentry Point Guard that patrols the road kills one of the Crown Hoodlums every time it goes near, not sure if this should happen.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Closed via https://github.com/azerothcore/azerothcore-wotlk/pull/11009
