### ISSUE TITLE
Taming The Beast Quest line

### ISSUE THREAD

**Issue by Halokillerman7** [azerothcore/azerothcore-wotlk#1073]
##### EXPECTED BLIZZLIKE BEHAVIOUR:
When turning in the quest after using the taming rod the creature should despawn but does not.

##### CURRENT BEHAVIOUR:
When turning in the quest after using the taming rod the creature should despawn but does not. 
This causes new players doing the quest to get confused on why they can not tame the 2nd beast or 3rd one. This happened as a Tauren Hunter in the 2nd town. 
If the pet gets stuck some where it does not despawn breaking the quest for the player until he finds where the npc has gotten stuck then it returns to his side when found.

I am unsure if this happens to all the quest for hunters as there are multiple quests for this.

##### STEPS TO REPRODUCE THE PROBLEM:
Create Tauren Hunter
Quest till 2nd Town
Easiest way to get this to happen or see the issue is to turn on modify speed 5-10 while you do the quest.

**Comment by poszer** [comment]
You're not right. I don't see any problem here. Actually it's working fine o.O
I have tested it, without problem ( Walk normal, without .mod speed while doing quest. I'm sure you re going too far from pet, that's why he get stucked ) :key:  
[My pic 1](http://prntscr.com/li8jvy)
[My pic 2](http://prntscr.com/li8mkc)
[My pic 3](http://prntscr.com/li8p6j)
[My pic 4](http://prntscr.com/li8p9x)
[Check this video, how it work](https://youtu.be/_dATKg-y4Lk?t=28)

**Comment by Halokillerman7** [comment]
The quest work fine if your careful and the pet keeps up but if you grind threw quickly before the pets timer you have no way to despawn them. I have had multiple reports of the issue and replicated it by modify speed higher and losing said tamed creature that does not despawn causing issues for the player. Confused players and staff have no way to track the npc when it’s out of sight as it seems to just vanish and go gray on the task bar until found again by its master. A despawn at turn in is what supposed to happen from what I remember on retail with the quest. Also when said npc is lost the tame timer does not count down for the creature causing it to remain on the hunters task bar until log out.

**Comment by poszer** [comment]
> 
> 
> The quest work fine if your careful and the pet keeps up but if you grind threw quickly before the pets timer you have no way to despawn them. I have had multiple reports of the issue and replicated it by modify speed higher and losing said tamed creature that does not despawn causing issues for the player. Confused players and staff have no way to track the npc when it’s out of sight as it seems to just vanish and go gray on the task bar until found again by its master. A despawn at turn in is what supposed to happen from what I remember on retail with the quest. Also when said npc is lost the tame timer does not count down for the creature causing it to remain on the hunters task bar until log out.

Well, like i said, i have tested this and everything is fine for me. So, Let's wait if anyone report same issue.

**Comment by Halokillerman7** [comment]
Do the same quest just .modify speed 5 and run away from the said unit and continue doing the 2nd part of said quest and avoid the spot ya lost it while doing 2nd part you will see the issue i may take a video later showing the issue.

**Comment by Halokillerman7** [comment]
https://youtu.be/aFsmhOq_wuM
Had to lose the plainstalker on the mountain side had issues losing it this time first few times i did it was easy. But to replicate .modify speed 5+ and .gm fly on. Watch video above to see the issue i recorded 2nd quest after that first part did not record very well but ya get to see the issue in that vid.

**Comment by poszer** [comment]
I understand. But i can't understand why you have to modify speed ? And also how to tame it , when you already have have pet, who is dead. Ofc, you can't, you can try X times, but it will be unsuccesful. I have tested it normally, without any speed modifications, and i can confirm that, it's working fine. 
From 10 times giving try, 10 was succes.
But with modify speed, like i said in first comment:, it's posible to get this issue.

>Walk normal, without .mod speed while doing quest. I'm sure you re going too far from pet, that's why he get stucked / Actually Lost ( Can't follow you).

**Comment by Halokillerman7** [comment]
The Pet is not dead.
Taming Rod given by quest Taming The Beast is how you tame said NPC for set time that does not count down once said pet is lost/stuck and not in range of player.
Steps to reproduce to show easiest way to replicate the issue to find and see the issue first hand.

As i have shown in the vid and said before.
Do the first quest, Lose/Stuck the pet, Leave the area/zone its in, Pet despawns or something?, Player is unable to dismiss the temp-pet or continue on the taming quest.

**Comment by Halokillerman7** [comment]
*facepalm* the pet is not dead and the modify speed and such is to show you how to see the said issue first hand unless you want to run around and attempt to get the mob stuck on random gobjects around  the zone and lose the tamed beast highly doubt you want to spend hours attempting this. The taming was to show you players are unable to continue their Taming The Beast Quest and continue on the 2nd Taming The Beast+ quest. Most players will be completely confused as they just turned in the quest but still see the pet in task bar and unable to continue the next quest. Also another way was just reported to me that if you tame the said creature and hearthstone back to town this issue is also replicated once again causing the npc to glitch out of warcraft existence until found again by the player if they *remember* where it is and most of the time they do not.

**Comment by poszer** [comment]
Whatever. I have tested it with mod speed just now, going far away and ofc issue i appear.
So, with .mod speed i can confirm it

**Comment by Halokillerman7** [comment]
See :P

**Comment by Mitradis** [comment]
Open this issue becouse this problem not solved. And additionat - when manual dismiss quest pet he start attack player and not disappear.

**Comment by poszer** [comment]
It worked perfectly. Check commits, something fcked it again

**Comment by FrancescoBorzi** [comment]
it would be nice to understand which commit fucked it up so we can fix it

**Comment by Stoabrogga** [comment]
Talamortis' commit never fixed the issue, it just removes the charm aura from the pet if it leaves visibility range.

**Comment by Stoabrogga** [comment]
At first glance I think this can be solved via SAI, but the issue seem to affect all 18 hunter quests (3 for each race). I can look into this, but it will take some time.

**Comment by Mitradis** [comment]
all who deny the existence of a problem play on this server? or only look in code? i think this guys not played.

**Comment by Mitradis** [comment]
stop using GM comands for test, just take normal quest! NOT WORKING!
https://i4.imageban.ru/out/2019/09/07/611fd5514202f2b607ea8034e52ceff9.jpg
