### ISSUE TITLE
GM command available on player account

### ISSUE THREAD

**Issue by Orystal** [azerothcore/azerothcore-wotlk#10734]
### Current Behaviour

Some commands like .account .server are available on a level 0 player account with
AllowPlayerCommands = 0

### Expected Blizzlike Behaviour

No server commands are available on Blizzard servers

### Steps to reproduce the problem

Type .server on a level 0 account with
AllowPlayerCommmands=0 in worldserver.conf

### AC rev. hash/commit

AzerothCore rev. 49191da0f8566a513a7313fa8215e67c7cb996ab+ 2022-02-13 10:15:15 +0000 (master branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
By design
