### ISSUE TITLE
Alterac Valley - Bosses immune to disarm

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10753]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

As of this morning's patch (midday on 19th Feb), the bosses in Alterac Valley (Vanndar and Drek) are immune to disarm. 

This apparently wasn't an intentional change (as per discord) and isn't Blizzlike. 

### Expected Blizzlike Behaviour

Bosses can be disarmed by Warriors and Rogues. 

### Source

Only one patch reference to disarm: https://wowpedia.fandom.com/wiki/Drek%27Thar
Change was to be made immune to disarm in patch 5.4 (implying he wasn't immune before): https://wowpedia.fandom.com/wiki/Patch_5.4.7

Wowhead comment from 3.3.3 pointing to lack of disarm/dismantle immunity: https://gyazo.com/635a1f3b52677fe6ddb3b28a65b6f4d0

### Steps to reproduce the problem

Attempt to disarm
Get immuned

### Extra Notes

original report: https://github.com/chromiecraft/chromiecraft/issues/3101
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
Caused by https://github.com/azerothcore/azerothcore-wotlk/pull/10730 . Reverting it fixes the issue.
