### ISSUE TITLE
[BWL] Razorgore Mind Control issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10769]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

1. Orb gives debuff after channeling
~~2. You cannot interrupt the channeling~~

### Expected Blizzlike Behaviour

1. Debuff should start at start of channeling
~~2. You should be able to interrupt the channeling.~~

### Steps to reproduce the problem

Go to BWL and use mind control

### Extra Notes
https://wowpedia.fandom.com/wiki/Razorgore_the_Untamed?oldid=2380334
https://github.com/chromiecraft/chromiecraft/issues/3095

Our previous source was wrong :(

###Server

ChromieCraft PTR

### AC rev. hash/commit

rev. 982be6de0081

### Operating system

Ubuntu 20.04

### Modules

mod-anticheat (master) 
mod-autobalance (master)
mod-cfbg (master)
mod-chromiexp (master)
mod-chromiecraft (master)
mod-desertion-warnings (master)
mod-duel-reset (master)
mod-eluna-lua-engine (master)
mod-ip-tracker (master)
mod-low-level-arena (master)
mod-multi-client-check (master)
mod-progression-system (master)
mod-pvp-titles (master)
mod-pvpstats-announcer (master)
mod-queue-list-cache (master) 
mod-rdf-expansion (master) 
mod-save-inventory (master)
mod-server-auto-shutdown (master)
mod-spellsystem-extended (master)

### Customizations

Acore_eventScripts (master)
Acore_SendAndBind (master)
Acore_TempAnnouncements (master)
Acore_ZoneDebuff (master)

**Comment by UltraNix** [comment]
@temperrr Any proof that mind control should interruptable?
https://www.youtube.com/watch?v=i5Ot-5eHrD8 I don't see on this video.

**Comment by temperrr** [comment]
Can't find it either so lets not change it.
