### ISSUE TITLE
The ScriptName of a scripted NPC is not assigned to a manually created NPC until the server is restarted. 

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#10778]
### Current Behaviour

If you spawned NPCbuffer or any other scripted NPC with gossip menus - dialogues are not initiated until server restarted

### Expected Blizzlike Behaviour

Some time ago all spawned NPC was shown all items of their dialogues right after spawn without server restart. 

### Steps to reproduce the problem

1. add any module with scripted NPC, compile and start server
2. log in to world and spawn nesessary NPC `.npc add XXXXX`
3. Try to open his gossip dialogue. It will show only default greetings.
4. Restart server and try to open this dislogue again - everything is fine

### Extra Notes

I think this can have a bad effect not only when using modules, but also in other cases of dynamic NPC spawning in instances or others.

### AC rev. hash/commit

c9586a106b4b

### Operating system

win server

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/157779553-3b43330c-5ee3-4b65-9e0a-28fef74b4746.png)
![изображение](https://user-images.githubusercontent.com/25766571/157779601-4cef4aa8-68ba-470a-bfa0-d8a7a6ee74e8.png)

**Comment by Bogir** [comment]
but it assigned if this is temporary spawn
![изображение](https://user-images.githubusercontent.com/25766571/157780892-906d14d0-1831-4268-9920-7fa5292948cc.png)

**Comment by Bogir** [comment]
GameObjects also not seen until server restarted

after spawn:

![изображение](https://user-images.githubusercontent.com/25766571/157944417-d8504ac5-7acf-4b88-b4ab-781fc2babce6.png)

after restart:

![изображение](https://user-images.githubusercontent.com/25766571/157943685-202da70e-fb59-400f-9476-41995edbe63d.png)

**Comment by Bogir** [comment]
This all suggests that mods like **GuildHouse** will not be able to work.

**Comment by Bogir** [comment]
Perhaps, it was broken by https://github.com/azerothcore/azerothcore-wotlk/pull/8715 
@acidmanifesto need help

**Comment by acidmanifesto** [comment]
oof... that pr was from over 5 months ago and definately was not the cause of the current issues as it allow scripts to be read per guids of the npc and the gameobjects. I created a npc ai today and i am not having that issue although, i am not entirely too sure why some people are having this issue why some other people do not. Will attempt to investigate later i guess when i have time. But i will have a challenge as i am not having the issue on my end.

**Comment by Bogir** [comment]
> oof... 
I created a npc ai today

It was NPC listed in `Creatures.CustomIDs` in worldserver.conf ?

**Comment by acidmanifesto** [comment]
No. No gossip. Still wip at the moment. But i havnt a issue with it showing its gossip

**Comment by Bogir** [comment]
Does this NPC have core Script or just SmartScript for gossip?

**Comment by acidmanifesto** [comment]
> Does this NPC have core Script or just SmartScript for gossip?

Core.

**Comment by Bogir** [comment]
https://youtu.be/nDiEyXbDaFc

:(

**Comment by acidmanifesto** [comment]
so the issue may be because we dont have a way to actual RELOAD the scripts like tc does on npc add. Never had apparently.
If we did then the feature was removed well before my involvement with Azerothcorecore.
Commits to refact would be:
https://github.com/TrinityCore/TrinityCore/commit/3123c278b9f7dca36d4edcafc95f40f37ec3e4eb
https://github.com/TrinityCore/TrinityCore/commit/1b909f9dacf21c7d3a6f9eb48afd168f52801bd4
https://github.com/TrinityCore/TrinityCore/commit/445746c402485fcac60c02842d0cb5e0dd605e5c

Whoever can fun with that.

**Comment by Bogir** [comment]
> so the issue may be because we dont have a way to actual RELOAD the scripts like tc does on npc add.
> Whoever can fun with that.

try to switch to any commit before this https://github.com/azerothcore/azerothcore-wotlk/pull/8715
Dialogues work fine

**Comment by acidmanifesto** [comment]
@Bogir please test https://github.com/azerothcore/azerothcore-wotlk/pull/11102
