### ISSUE TITLE
Command : .wp show off drop all creature table

### ISSUE THREAD

**Issue by Intemporel** [azerothcore/azerothcore-wotlk#10779]
### Current Behaviour

I don't know why but this command just erase the entire `creature` table in the database `acore_world`.

### Expected Blizzlike Behaviour

Only delete waypoints helping creature

### Source

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_wp.cpp#L1051-L1108

### Steps to reproduce the problem

1. I've targeted the creature
2. I just write `.wp show off`

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/400caec7099addf7329396800341c0f9070da734

### Operating system

Ubuntu 21.04

**Comment by Bogir** [comment]
Confirm
It erased almost all 146k records  in `creature` table, except 43  records
![изображение](https://user-images.githubusercontent.com/25766571/154999680-7a5ace6c-892b-4bbe-ae01-6a5a4c5e7152.png)

**Comment by Bogir** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/400caec7099addf7329396800341c0f9070da734/src/server/scripts/Commands/cs_wp.cpp#L1070

reason - Creature can't be taken by such method

**Comment by Nefertumm** [comment]
No, that's not the reason.
https://github.com/azerothcore/azerothcore-wotlk/blob/400caec7099addf7329396800341c0f9070da734/src/server/scripts/Commands/cs_wp.cpp#L1053-L1054

https://github.com/azerothcore/azerothcore-wotlk/blob/dfac47a5629367caf5e3db3106f2160b1f3d7ce3/src/server/database/Database/Implementation/WorldDatabase.cpp#L83

The command is deleting everything that has id2 = 0 or id3 = 0

**Comment by Intemporel** [comment]
Maybe it's needed to change `OR` by `AND` in this sql statement, and only creature with id1, id2 AND id3 will be erased.

https://github.com/azerothcore/azerothcore-wotlk/blob/dfac47a5629367caf5e3db3106f2160b1f3d7ce3/src/server/database/Database/Implementation/WorldDatabase.cpp#L83

OR maybe we need to prepare a new statement only for this command ?

**Comment by Nefertumm** [comment]
No.
https://github.com/azerothcore/azerothcore-wotlk/blob/400caec7099addf7329396800341c0f9070da734/src/server/scripts/Commands/cs_wp.cpp#L1053-L1054
Add below this the following lines:
```cpp
stmt->SetData(1,1);
stmt->SetData(2,1);
```

That should do the trick
