### ISSUE TITLE
The GM command cannot be used（.go）

### ISSUE THREAD

**Issue by mspzyzh** [azerothcore/azerothcore-wotlk#10777]
### Current Behaviour

The GM command cannot be used（.go）

https://user-images.githubusercontent.com/13333156/154965488-181b4baf-4a58-4fd3-aa26-2681177c1eef.mp4

### Expected Blizzlike Behaviour

use .go command

### Steps to reproduce the problem

Use command
.go -1401.768677 -77.580559 158.93483 1 0 0 

### AC rev. hash/commit

AzerothCore rev. 3e6424151af4+ 2022-02-20 10:19:56 +0100 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 100512
Using CMake version: 3.18.4
Compiled on: Linux 5.13.19-4-pve
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azerothcore/data/maps. Total size: 252191207 bytes
vmaps directory located in /root/azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azerothcore/data/mmaps. Total size: 2199390740 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_02_19_04
Using Character DB Revision: 2022_02_16_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Debian 11x64

**Comment by mspzyzh** [comment]
> you need to use .go xyz [x, y, z, orientation, map]

It used to be available

**Comment by benjymansy123** [comment]
> > you need to use .go xyz [x, y, z, orientation, map]
> 
> It used to be available

Just because it used to be available doesn't mean it has to stay available.

**Comment by Bogir** [comment]
Just checked
`.go -4602.68	-1683.32	503.32`
works fine

**Comment by mspzyzh** [comment]
> 刚刚检查工作正常`.go -4602.68 -1683.32 503.32`

I can't use it
![屏幕截图(8)](https://user-images.githubusercontent.com/13333156/154994187-d7718afa-50a3-4069-bd29-c42deab439c5.png)
