### ISSUE TITLE
Shaman's Elemental Focus Clearcasting

### ISSUE THREAD

**Issue by Awkakelen** [azerothcore/azerothcore-wotlk#10780]
### Current Behaviour

Hi, right now Clearcasting stacks are used even when i hit mob by melee atack or when I use spell that doesn't require mana. Also clearcasting is depleting when I'm getting hit while my Water Shield / Lightning Shield is ON (sic!).

### Expected Blizzlike Behaviour

Clearcasting stacks should be used when I use spell that requires mana. ONLY.

### Source

Talent description.

### Steps to reproduce the problem

1. Get Elemental Focus Talent
2. Land a Critical Strike from spell
3. Use melee/ use no-mana spell / get hit with lightning/water shield

### AC rev. hash/commit

AzerothCore rev. f82c60526b99 2022-02-19 01:39:59 +0000 (master branch) 

### Operating system

Windows 10 x64

**Comment by temperrr** [comment]
https://github.com/chromiecraft/chromiecraft/issues/2960

**Comment by Gultask** [comment]
Also happens with Flametongue Weapon procs according to a CC Discord user
