### ISSUE TITLE
Command : .npc move without targetting will crash the worldserver

### ISSUE THREAD

**Issue by Intemporel** [azerothcore/azerothcore-wotlk#10783]
### Current Behaviour

AS i explain in title, `.npc move` without targetting crash the worldserver

### Expected Blizzlike Behaviour

Just nothing, or a message `You must select a creature`

### Source

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_npc.cpp#L703-L762

### Steps to reproduce the problem

1. Select nothing
2. use `.npc move`

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/400caec7099addf7329396800341c0f9070da734

### Operating system

Ubuntu 21.04

**Comment by Bogir** [comment]
Confirm
rev, c9586a106b4b

**Comment by Intemporel** [comment]
I found the problem, even if the creature doesn't exist, the command script try to get her `lowguid`...
We just need to put :

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_npc.cpp#L706

after (instead of before) :

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_npc.cpp#L708-L709
