### ISSUE TITLE
Character Dying

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#10787]
### Current Behaviour

Bug when I travel from Northumbria to Kalimdor, my character dies on the way back to Orgrimmar
3rd time I go with zeppelin to Orgrimmar and when I enter it appears dead

![image](https://user-images.githubusercontent.com/58153179/155120860-01e86fd3-c133-428f-af90-fda3cc3649f5.png)

### Expected Blizzlike Behaviour

I believe it's a recent bug, because it wasn't like that.

### Steps to reproduce the problem

Bug when I travel from Northumbria to Kalimdor, my character dies on the way back to Orgrimmar
3rd time I go with zeppelin to Orgrimmar and when I enter it appears dead

### AC rev. hash/commit

AzerothCore rev. 400caec7099a+ 2022-02-21 02:36:48

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
can you post the combat log? Did you die of falldamage?

**Comment by htc16** [comment]
> 

It wasn't from a fall, when you load the screen to Orgrimmar I was born dead

**Comment by Kitzunu** [comment]
Thats why I want you to give a screenshot of the combat log. Because my bets are that it is from fall damage

**Comment by htc16** [comment]
![20220222_075654](https://user-images.githubusercontent.com/58153179/155209842-8341e1fe-924c-4e04-b5ac-2e149d41b8d1.jpg)

**Comment by benjymansy123** [comment]
And that photo is not of the combat log.

**Comment by htc16** [comment]
> 

I will run more tests and report back.

**Comment by Kitzunu** [comment]
Not heard of anyone else experiencing this. so will close for now

**Comment by htc16** [comment]
@Kitzunu 

my character died again like that, the difference being that I had the client screen minimized. Could you please test if the client's minimized screen could do this?

At that time I was returning by zeppelin to Orgrimmar.

**Comment by htc16** [comment]
More details:
Hunter lvl 66, Orc, I got in the boat, mounted the dog mount at 100% speed, and minimized the screen and when I came back at some point he had died.
