### ISSUE TITLE
authserver carsh

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10788]
### Current Behaviour

authserver can work ,but it crashes at intervals

crash log:
```
#----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location '/home/azerothcore/src/server/database/Database/Field.cpp:149'
# Function 'GetBinarySizeChecked'
# Condition 'data.value && (data.length == length)'
# Message 'Expected 32-byte binary blob, got no data (0 bytes) instead'
 
#----------------------------------------------------------------------#
Segmentation fault (core dumped)
```

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

3e6424151af45eb3238dbd510cc69d534a3a7ac0

### Operating system

ubuntu 20.04

### Custom changes or Modules

- mod-anticheat

**Comment by Kitzunu** [comment]
Can you attach the whole crashlog please

**Comment by Kitzunu** [comment]
Otherwise it will be impossible to know what caused it

**Comment by htc16** [comment]
> ### Current Behaviour
> authserver can work ,but it crashes at intervals
> 
> crash log:
> 
> ```
> #----------------------------------------------------------------------#
>  
> >> ASSERTION FAILED
> 
> # Location '/home/azerothcore/src/server/database/Database/Field.cpp:149'
> # Function 'GetBinarySizeChecked'
> # Condition 'data.value && (data.length == length)'
> # Message 'Expected 32-byte binary blob, got no data (0 bytes) instead'
>  
> #----------------------------------------------------------------------#
> Segmentation fault (core dumped)
> ```
> 
> ### Expected Blizzlike Behaviour
> none
> 
> ### Source
> _No response_
> 
> ### Steps to reproduce the problem
> none
> 
> ### Extra Notes
> _No response_
> 
> ### AC rev. hash/commit
> [3e64241](https://github.com/azerothcore/azerothcore-wotlk/commit/3e6424151af45eb3238dbd510cc69d534a3a7ac0)
> 
> ### Operating system
> ubuntu 20.04
> 
> ### Custom changes or Modules
> * mod-anticheat

Are you using any websites? You need to make sure that the site that created this account supports azerothcore. Because I'm normally using the latest rev on my computer.

**Comment by mpfans** [comment]
> > ### Current Behaviour
> > authserver can work ,but it crashes at intervals
> > crash log:
> > ```
> > #----------------------------------------------------------------------#
> >  
> > >> ASSERTION FAILED
> > 
> > # Location '/home/azerothcore/src/server/database/Database/Field.cpp:149'
> > # Function 'GetBinarySizeChecked'
> > # Condition 'data.value && (data.length == length)'
> > # Message 'Expected 32-byte binary blob, got no data (0 bytes) instead'
> >  
> > #----------------------------------------------------------------------#
> > Segmentation fault (core dumped)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Expected Blizzlike Behaviour
> > none
> > ### Source
> > _No response_
> > ### Steps to reproduce the problem
> > none
> > ### Extra Notes
> > _No response_
> > ### AC rev. hash/commit
> > [3e64241](https://github.com/azerothcore/azerothcore-wotlk/commit/3e6424151af45eb3238dbd510cc69d534a3a7ac0)
> > ### Operating system
> > ubuntu 20.04
> > ### Custom changes or Modules
> > 
> > * mod-anticheat
> 
> Are you using any websites? You need to make sure that the site that created this account supports azerothcore. Because I'm using the latest rev on my computer and I'm not normally crashing.

yes.. use FusionGEN...  support azerothcore and srp6

**Comment by Kitzunu** [comment]
@Winfidonarleyan

**Comment by htc16** [comment]
I know fusiongen has made some recent updates on this, make sure the bug isn't there.  Open an issue there in the fusiongen repository with this error reported above.

**Comment by htc16** [comment]
https://github.com/FusionGen/FusionGEN/issues/115

**Comment by Winfidonarleyan** [comment]
> > > ### Current Behaviour
> > > authserver can work ,but it crashes at intervals
> > > crash log:
> > > ```
> > > #----------------------------------------------------------------------#
> > >  
> > > >> ASSERTION FAILED
> > > 
> > > # Location '/home/azerothcore/src/server/database/Database/Field.cpp:149'
> > > # Function 'GetBinarySizeChecked'
> > > # Condition 'data.value && (data.length == length)'
> > > # Message 'Expected 32-byte binary blob, got no data (0 bytes) instead'
> > >  
> > > #----------------------------------------------------------------------#
> > > Segmentation fault (core dumped)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Expected Blizzlike Behaviour
> > > none
> > > ### Source
> > > _No response_
> > > ### Steps to reproduce the problem
> > > none
> > > ### Extra Notes
> > > _No response_
> > > ### AC rev. hash/commit
> > > [3e64241](https://github.com/azerothcore/azerothcore-wotlk/commit/3e6424151af45eb3238dbd510cc69d534a3a7ac0)
> > > ### Operating system
> > > ubuntu 20.04
> > > ### Custom changes or Modules
> > > 
> > > * mod-anticheat
> > 
> > Are you using any websites? You need to make sure that the site that created this account supports azerothcore. Because I'm using the latest rev on my computer and I'm not normally crashing.
> 
> yes.. use FusionGEN...  support azerothcore and srp6

Maybe incorrect support? In CC no problem
