### ISSUE TITLE
[Dungeon] You can avoid the dungeon lockout

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10799]
### Current Behaviour

You can avoid the dungeon lockout of five dungeons per hour. You just need to die in the dungeon, release spirit, reset dungeon and walk back in.

### Expected Blizzlike Behaviour

If you reset a dungeon while being a spirit you should be resurrected at the dungeon portal when trying to walk back in.

### Steps to reproduce the problem

1. Enter a dungeon, kill one mob, walk out, reset dungeon
2. Enter dungeon again, kill one mob, walk out, reset dungeon
3. Enter dungeon again, kill one mob, walk out, reset dungeon
4. Enter dungeon again, kill one mob, walk out, reset dungeon
5. Enter dungeon again
6. Kill one mob
7. Get killed by an enemy
8. Release spirit
9. Reset dungeon
10. Walk back in an start your sixth dungeon during the hourly lockout

### AC rev. hash/commit

https://github.com/chromiecraft/chromiecraft/commit/8449b2c1a868eefbc93bddf584899b5dad71b3d1

### Operating system

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by DepTypes** [comment]
Returning
```cpp
player->SendTransferAborted(mapid, TRANSFER_ABORT_TOO_MANY_INSTANCES);
return Map::CANNOT_ENTER_TOO_MANY_INSTANCES;
```
from
`Map::EnterState MapMgr::PlayerCannotEnter(uint32 mapid, Player* player, bool loginCheck)`

Will repop you at the entrance as expected.

The checks for groups and `!player->isDead()` are wrong?

**Comment by Lynethris** [comment]
PR Work.
![WoWScrnShot_022622_193615](https://user-images.githubusercontent.com/100411212/155855136-5c82acd9-2cb0-4ea4-8093-c01d933cdd45.jpg)
