### ISSUE TITLE
 Sartharion OS10 / 25 Spawns too many mobs

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1079]
Sartharion OS10 / 25 Spawns too many mobs

##### SMALL DESCRIPTION:

Sartharion OS10 / 25 -  https://www.wowhead.com/npc=28860/sartharion When the boss reaches 10% he soft enrages, making him spawn adds. Currently there are 50(10man) and 75(25man) adds being spawned. https://www.wowhead.com/npc=30643/lava-blaze

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only 10 mobs should be spawned upon soft enrage

##### CURRENT BEHAVIOUR:

Sartharion OS10 / 25 -  https://www.wowhead.com/npc=28860/sartharion When the boss reaches 10% he soft enrages, making him spawn adds. Currently there are 50(10man) and 75(25man) adds being spawned. https://www.wowhead.com/npc=30643/lava-blaze

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill Sartharion OS10/25 and watch the adds spawn

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Ubuntu

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:
 None

**Comment by disclosurez** [comment]
> 
> 
> Sartharion OS10 / 25 Spawns too many mobs
> ##### SMALL DESCRIPTION:
> 
> Sartharion OS10 / 25 - https://www.wowhead.com/npc=28860/sartharion When the boss reaches 10% he soft enrages, making him spawn adds. Currently there are 50(10man) and 75(25man) adds being spawned. https://www.wowhead.com/npc=30643/lava-blaze
> ##### EXPECTED BLIZZLIKE BEHAVIOUR:
> 
> Only 10 mobs should be spawned upon soft enrage
> ##### CURRENT BEHAVIOUR:
> 
> Sartharion OS10 / 25 - https://www.wowhead.com/npc=28860/sartharion When the boss reaches 10% he soft enrages, making him spawn adds. Currently there are 50(10man) and 75(25man) adds being spawned. https://www.wowhead.com/npc=30643/lava-blaze
> ##### STEPS TO REPRODUCE THE PROBLEM:
> 
>     1. Kill Sartharion OS10/25 and watch the adds spawn
> 
> 
> ##### BRANCH(ES):
> 
> master
> ##### AC HASH/COMMIT:
> ##### OPERATING SYSTEM:
>  fc4b52b 
> Ubuntu
> ##### MODULES:
> 
> None
> ##### OTHER CUSTOMIZATIONS:
> None

**Comment by Pondaveia** [comment]
@disclosurez Can you provide proof of the expected result?

**Comment by Hacaw** [comment]
I **can not** reproduce this issue as described.

I think someone already lowered the number of adds.

TESTING
---
#Scenario-1 (RAID 10-N): 
.die on Sartharion 
22 mobs are spawned

#Scenario-2 (RAID 25-N):
.die on Sartharion 
22 mobs are spawned

#Scenario-3 (RAID 10-N)
.damage until Sartharion is at 90% hp
22 mobs are spawned

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Thx for checking @Hacaw!
