### ISSUE TITLE
disables spell not working

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#10796]
### Current Behaviour

i used all the newest version.
i added a spell in spell_dbc, is worked.
`INSERT INTO spell_dbc SET ID=123101, Attributes=192, ProcChance=101, RangeIndex=1, EquippedItemClass=-1, Effect_1=6, EffectDieSides_1=1, EffectBasePoints_1=99999, ImplicitTargetA_1=1, EffectAura_1=34, EffectChainAmplitude_1=1, EffectChainAmplitude_2=1, EffectChainAmplitude_3=1, SchoolMask=1`
alse when player login, i used eluna auto cast this spell, this also working
`player:CastSpell(player, 123101)`

but i used table disables to disable this spell in Warsong Gulch (battleground), but is not worked
`INSERT INTO disables SET sourceType=0, entry=123101, flags=1+16+32, params_0=489, params_1=4572`

### Expected Blizzlike Behaviour

spell 123101 should working in everywhere but Warsong Gulch (battleground).
but now in Warsong Gulch (battleground) is also worked.

### Steps to reproduce the problem

see Current Behaviour

### AC rev. hash/commit

no

### Operating system

ubuntu 21

**Comment by Kitzunu** [comment]
Add commit hash

**Comment by Kitzunu** [comment]
Also remember it disables you to use the spell. I am unsure if it will prevent an already existing aura. 

Aka you use the spell to get aura outside, and it will persist in the BG but you cannot recast it
