### ISSUE TITLE
[BRD] Anub'shiah drops two rare items

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#10797]
### Current Behaviour

[Anub'shiah](https://wowgaming.altervista.org/aowow/?npc=9031) in BRD is currently dropping two rare items. It seems that [Carapace of Anub'shiah](https://wowgaming.altervista.org/aowow/?item=11678) is always dropping.

![WoWScrnShot_022222_154417](https://user-images.githubusercontent.com/62797536/155302068-67f1cb51-628c-4bc2-b98f-6ea7dc381fdf.jpg)

![WoWScrnShot_022222_104824](https://user-images.githubusercontent.com/62797536/155302099-5dd2a049-0d8d-4244-8107-cc2e255f6d48.jpg)

### Expected Blizzlike Behaviour

Anub'shiah should only drop one rare item out of his loot table.

### Steps to reproduce the problem

Query: `SELECT entry, item, groupid, comment FROM creature_loot_template WHERE entry = "9031" AND groupid > 0;`

| entry | item | groupid | comment | 
| ---: | ---: | ---: | --- | 
| 9031 | 11675 | 1 | Anub'shiah - Shadefiend Boots | 
| 9031 | 11677 | 1 | Anub'shiah - Graverot Cape | 
| 9031 | 11678 | 2 | Anub'shiah - Carapace of Anub'shiah | 
| 9031 | 11731 | 1 | Anub'shiah - Savage Gladiator Greaves | 

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/74358058601809a537f12614d3f03d90c08085dc

### Operating system

Ubuntu 20.04

##### MODULES:

None.

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

Local AC

**Comment by temperrr** [comment]
This seems to be the correct behaviour as checking various database result in the same loot table. Do you have any proof for this?

**Comment by temperrr** [comment]
Correct is has a 15 or 20 % extra chance to drop the carapace aswell

**Comment by TheSCREWEDSoftware** [comment]
Can't reproduce, he has a chance to drop more than 1 rare. He ha 2 group loots.  The image above represents it correcly, I dont know about values but it's intended.
