### ISSUE TITLE
Compile warning

### ISSUE THREAD

**Issue by cshaaa** [azerothcore/azerothcore-wotlk#108]
**Description**:
[ 71%] Building CXX object src/scripts/CMakeFiles/scripts.dir/Outland/TempestKeep/Eye/boss_astromancer.cpp.o
[ 71%] Building CXX object src/scripts/CMakeFiles/scripts.dir/Outland/TempestKeep/Eye/boss_alar.cpp.o
/home/chensh/acore/azerothcore/src/game/Server/WorldSession.cpp: In member function ‘void WorldSession::InitializeQueryCallbackParameters()’:
/home/chensh/acore/azerothcore/src/game/Server/WorldSession.cpp:1085:51: warning: passing NULL to non-pointer argument 1 of ‘void QueryCallback_2<Result, ParamType1, ParamType2, chain>::SetFirstParam(ParamType1) [with Result = Trinity::AutoPtr<PreparedResultSet, ACE_Thread_Mutex>; ParamType1 = unsigned int; ParamType2 = AsynchPetSummon*; bool chain = false]’ [-Wconversion-null]
     _loadPetFromDBFirstCallback.SetFirstParam(NULL);
                                                   ^
[ 71%] Building CXX object src/game/CMakeFiles/game.dir/Server/WorldSocketMgr.cpp.o
[ 71%] Building CXX object src/game/CMakeFiles/game.dir/Server/WorldSocket.cpp.o

**Branch(es)**:  master
**AC hash/commit**:  0ba91d7
**Modules**:  no
**Operating system**:  debian8.x

**Comment by ShinDarth** [comment]
currently there are a lot of warnings, why did you report this in particular?

**Comment by cshaaa** [comment]
I just have  only this one?

**Comment by ShinDarth** [comment]
@cshaaa on a clean build?

**Comment by cshaaa** [comment]
yes
no any other model
