### ISSUE TITLE
Paladin - Holy Shock Spell not working on friendly target at max range.

### ISSUE THREAD

**Issue by Jpizzle31** [azerothcore/azerothcore-wotlk#10802]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Casting any rank of the paladins holy spec talent ability Holy Shock (https://wowgaming.altervista.org/aowow/?spell=20930#see-also) only works at 20 yards even when being cast on friendly targets.

### Expected Blizzlike Behaviour

Tooltip states ranges as: 20yd enemy and 40yd friendly. Should be castable at 40 yards on friendly targets.

### Source

All wiki entries on the ability state the range as 20yd enemy and 40yd friendly.
https://wowgaming.altervista.org/aowow/?spell=20930#see-also
https://wotlk.evowow.com/?spell=20930
ingame tooltip states the same.

### Steps to reproduce the problem

1.get friendly target such as another player
2. max range another heal like flash of light(range 40yd)
3. attempt to cast holy shock at the same range
4. if not castable move closer until it is 
5. find yourself at 20 yards

### Extra Notes
Origanle Post: 

https://github.com/chromiecraft/chromiecraft/issues/3128

Notes: 

Bug is Valid.  Was able to reproduce the issue with a friendly target. Holy shock does not work as intended at 40 yards on the friendly target. It only works on Friendly target at 20 yards. 

![image](https://user-images.githubusercontent.com/95531594/155359313-2c001651-8529-4580-af2c-b24982c3f695.png)

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by mpfans** [comment]
Confirmed,The priest's penance has the same bug

**Comment by ishidinho** [comment]
@Jpizzle31 Can you please change title and add behavior for the priests spells?
