### ISSUE TITLE
[Elwynn Forest] Random NPC Human Peasant voice lines are heard.

### ISSUE THREAD

**Issue by Jpizzle31** [azerothcore/azerothcore-wotlk#10805]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

While walking through Elwynn Forest you can hear the Human Peasant's voice lines randomly.

Proof: https://www.youtube.com/watch?v=HszrA0N5kjU

### Expected Blizzlike Behaviour

You shouldn't hear those voice lines.

### Steps to reproduce the problem

    1. Walk around Elwynn Forest, close to the bridge next to Eastvale Logging Camp. (Around 76.79, 71.74)

### Extra Notes

Original: 

https://github.com/chromiecraft/chromiecraft/issues/3094

Note: 

Can confirm that there are voices being heard in this area as seen in the image below. Sounds as if someone is clicking NPC and they are replying to action. 

![image](https://user-images.githubusercontent.com/95531594/155409762-2f4a4d21-1791-4c9f-9e1d-a606bb70d7c8.png)

Voices are saying: What? More Work? , No one else Available? 

I have located the Sounds bit: it is coming from NPC - Eastvale Peasant 
However, this is some distance from where you start healing the voices by the bridge. Also, the Voices are triggering without anyone interacting with the NPC. 

![image](https://user-images.githubusercontent.com/95531594/155411880-5e861b1a-1938-43cc-88e8-d25e5f626821.png)

_No response_

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@49191da

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by benjymansy123** [comment]
Could be related to https://github.com/azerothcore/azerothcore-wotlk/issues/4303

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10813

**Comment by Gultask** [comment]
Still an issue in the CC PTR and a local AC as well. It's as fendwe said in the CC issue:
>The sound bits are played every time an Eastvale Peasant talks to Supervisor Raelen to start a new round of logging.
This can be heard as soon as those npcs are in visual range/can be targeted. (https://github.com/chromiecraft/chromiecraft/issues/3094#issuecomment-1066735634)

I'm far from knowledgeable about these things but wouldn't https://github.com/azerothcore/azerothcore-wotlk/pull/9525 also solve this issue?
