### ISSUE TITLE
Archavon the Stone Watcher Voa 10/25

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1080]
Archavon the Stone Watcher Voa 10/25 Throws player in air

##### SMALL DESCRIPTION:

Archavon the Stone Watcher Voa 10/25 stomp ability throws players in the air

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Archavon the Stone Watcher Voa 10/25 stomp ability should not throw player in the air
https://www.wowhead.com/spell=60880/stomp

##### CURRENT BEHAVIOUR:

it's throwing the player so high that he takes more than half of his health as fall damage.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run VoA and attack Archavon the Stone Watcher
2. 
3. 

##### BRANCH(ES):

master

**Comment by Pondaveia** [comment]
Just checked the code and the 25 man spell is the one from wowhead. Can someone confirm this issue? Players should be knocked down.

**Comment by Knindzagxg** [comment]
Yeah, i can confirm mate.
Will post in other one as well, checked Rockshards and Stomp as well.

https://www.youtube.com/watch?v=iOFr86DrfpU
