### ISSUE TITLE
bug in Trial of the Crusader

### ISSUE THREAD

**Issue by blacknightt1** [azerothcore/azerothcore-wotlk#10807]
### Current Behaviour

Hi, there are some bugs in Instance Trial of the Crusader that are very important

1. When entering this instance, there is an npc named Barrett Ramsey that you should be able to start the instance by talking to this npc, which is not possible and you can not talk to this npc.
2. When we start boss Twin Val’kyr, there are two orb examples called Dark Vortex and Light Vortex, which by clicking on each one, you should get the color of that orb, which is also a bug.
3. In-game dummies (dummy) that test dps, etc. also move with their target, which is also a bug.

### Expected Blizzlike Behaviour

1. When entering this instance, there is an npc named Barrett Ramsey that you should be able to start the instance by talking to this npc, which is not possible and you can not talk to this npc.
2. When we start boss Twin Val’kyr, there are two orb examples called Dark Vortex and Light Vortex, which by clicking on each one, you should get the color of that orb, which is also a bug.

### Source

1. https://db.3x3x5.ir/?spell=66058
2. https://db.3x3x5.ir/?spell=66046

### Steps to reproduce the problem

The following video I took from this bug and There are 10 and 25 people with this bug and I tested it
https://youtu.be/D14KkolsHBA

### Extra Notes

Due to the bugs I explained above in the new version

1. AzerothCore rev. 23cd1883d67a + 2022-02-23 13:55:47 +0000 (main directory) (Win64, RelWithDebInfo, Static)

There is an older version of it

1. AzerothCore rev. bd956b5a5750 + 2021-09-13 18:59:16 +0000 (main branch) (Win64, RelWithDebInfo, Static)

I installed and checked that fortunately this (old) version does not have the bugs mentioned above

### AC rev. hash/commit

AzerothCore rev. 23cd1883d67a + 2022-02-23 13:55:47 +0000 (main directory) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10

### Custom changes or Modules

1. [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
2. [mod-transmog](https://github.com/azerothcore/mod-transmog)

**Comment by nestormourino** [comment]
We're having same issue:

Barrett Ramsey can be activated after walking in/out the instance, wich is buggy.
Twins vortex are also bug as described in the issue.

**Comment by fullofstarschen** [comment]
I confirm this, [https://github.com/azerothcore/azerothcore-wotlk/issues/10443](url)

**Comment by nestormourino** [comment]
@Azcobu can you check this out and label it?

At my server we're at [204043c](https://github.com/azerothcore/azerothcore-wotlk/commit/204043ccd21fdf0857eca6c4dbcb6d1634d937ef) and still having this mayor issue.

**Comment by Bogir** [comment]
1 . - can't confirm. Barrett Ramsey opens his dialogue and starts Instance on first click

**Comment by Alexander990608** [comment]
> 1 . - can't confirm. Barrett Ramsey opens his dialogue and starts Instance on first click


I tested by myself, you should wait like 30-40 seconds before speaking with the Barnett Ramsey, somehow i re-entered the raid and i could speak with him, sometimes you cannot speak with him when you enter first time in raid. And when you kill Tein Val'kyr, you should speak with Barnett Ramsey, but sadly it starts after like 1 min after you killed boss.

**Comment by Azcobu** [comment]
@nestormourino - I'm not currently working on AC so can't confirm these issues, but have applied relevant labels.

For issues with Barrett Ramsey, see https://github.com/azerothcore/azerothcore-wotlk/issues/10334.
