### ISSUE TITLE
Petition Signs

### ISSUE THREAD

**Issue by Seigneur-fantome** [azerothcore/azerothcore-wotlk#10816]
### Current Behaviour

Hello, when i want invit user to sign charter, they can't do it...
![Capture d’écran 2022-02-24 232224](https://user-images.githubusercontent.com/79913664/155617496-169aae06-d05c-4adf-be51-f6dc82ab0d19.png)
.

### Expected Blizzlike Behaviour

user can sign charter...

### Steps to reproduce the problem

buy charter
invite user to sign charter... and nothing

### AC rev. hash/commit

AzerothCore rev. 47cce46e4001+ 2022-02-15 00:09:53 +0000 (master branch) (Win64, Release, Static)

### Operating system

windows11

### Custom changes or Modules

> Anticheat
> mod_LuaEngine
> mod_multilogin
> mod_pvptitles

**Comment by Kitzunu** [comment]
This works

**Comment by heyitsbench** [comment]
I did actually have an issue with an arena team charter on my local AC install. I could request a signature just fine, and the player would receive the request, but attempting to sign the charter did not work no matter what I did.

**Comment by Kitzunu** [comment]
That would mean it is impossible to create an arena team. I find it very odd there has been no mention of such issue for over a year and a half

**Comment by heyitsbench** [comment]
I'm not saying it's a consistent issue, picking up a 2v2 team charter instead of the 3v3 one I was working with made it work immediately. All I know is that the first charter I tried refused to work.
