### ISSUE TITLE
Tenebron - SARTHARION {OS10 / 25} Eggs are hatching too fast

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1081]
Eggs are hatching too fast when fighting Tenebron or SARTHARION

##### SMALL DESCRIPTION:

**PRIO!*Tenebron OS10 / 25 - https://www.wowhead.com/npc=30452/tenebron  This boss opens a portal with eggs inside. These hatch after about 20-25 sec and enter the world that the player is in. If you enter the portal to kill the eggs, the whelplings that are supposed to hatch from the eggs are ALREADY hatched inside the twilight world. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Eggs should not hatch until entering the twilight portal, no mobs should be spawned for 20 seconds or so

##### CURRENT BEHAVIOUR:

SARTHARION/Tenebron OS10 / 25 - https://www.wowhead.com/npc=30452/tenebron  This boss opens a portal with eggs inside. These hatch after about 20-25 sec and enter the world that the player is in. If you enter the portal to kill the eggs, the whelplings that are supposed to hatch from the eggs are ALREADY hatched inside the twilight world. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run OS10/25 and kill Tenebron/Satharion
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

fc4b52b036a33f1207acca8c93a4c9ef3f9baa10

**Comment by Pondaveia** [comment]
Can anyone confirm this issue?

**Comment by Pondaveia** [comment]
I confirm this issue
