### ISSUE TITLE
[Ulduar] Razorscale walking mid-air, instead of flying

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#10812]
### Current Behaviour

Razorscale walks mid-air , instead of flying. Regardless of combat or not

https://user-images.githubusercontent.com/46330494/155573927-c8523b88-d840-4d23-bbec-20e1638783f5.mp4

### Expected Blizzlike Behaviour

Should fly

### Source

https://www.youtube.com/watch?v=O2Ws1KnE64w

### Steps to reproduce the problem

1. .go c 137612 
2. Look up in the sky, Razorscale will be walking, instead of flying.

### Extra Notes

This appears to affect quite a bunch of npcs with this behaviour.
Linked with #10814
Perhaps related to (creature_movement_override)?

### AC rev. hash/commit

3e6424151af4

### Operating system

Windows 10 

### Custom changes or Modules

None

**Comment by mpfans** [comment]
@UltraNix has dealt with the same problem before

**Comment by acidmanifesto** [comment]
Whats the npc id for that? That looks like disable gravity being used instead of the can fly mask

**Comment by mpfans** [comment]
> Whats the npc id for that? That looks like disable gravity being used instead of the can fly mask

Razorscale  ID 33186

#10814 

Malygos  ID 28859

**Comment by avarishd** [comment]
> Whats the npc id for that? That looks like disable gravity being used instead of the can fly mask

I tried to see if that would fix it before opening the issue, but apparently not.
