### ISSUE TITLE
Skeletal Flayer and Slavering Ghoul in WPL have 20 yard when Rooted

### ISSUE THREAD

**Issue by Jpizzle31** [azerothcore/azerothcore-wotlk#10810]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Both Skeletal Flayer and Slavering Ghoul mobs have huge melee ranges. Melee attacking from much beyond 5-yard distance.

### Expected Blizzlike Behaviour

Melee attacks should only work within 5 yards.

### Steps to reproduce the problem

Use Frost Nova or other movement-stopping abilities on mobs.
Receive melee damage more than 5 yards away from the enemy.

### Extra Notes

Original: 

https://github.com/chromiecraft/chromiecraft/issues/3119

Note: 

In the first image, I did a within a 10-yard test and the NPC did not attack like posted in the Bug report. However, when I Frost Nova the NPC and moved well beyond 10 yards the NPC begin to attack while still being Frost Nova. I have to confirm this to be accurate there is a Range in which the Rooted NPC will attack when they should not. 

![image](https://user-images.githubusercontent.com/95531594/155536414-c836dddf-ca00-400b-9065-fffbdbf9d449.png)

![image](https://user-images.githubusercontent.com/95531594/155536508-542abd4e-90b6-487b-aeee-9c90bea3bb58.png)

_No response_

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@ccc9bb6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10869
