### ISSUE TITLE
ICC Lich King not killable after 10% health

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/azerothcore-wotlk#10821]
### Current Behaviour

if lk has under 10% life, he is unkillable.

Phase 3 on Levitating LK absorbs all damage

### Expected Blizzlike Behaviour

the event must be ended

### Steps to reproduce the problem

1. go to icc
2. try to kill LK

### AC rev. hash/commit

ede21e1174cd279655762d938cc9157032bc35be

### Operating system

Windows 10 x64, Ubuntu 20

**Comment by Alexander990608** [comment]
Don't forget to add, on Heroic mode if you get inside of the Frostmourne, the platform disappears in 2-3 secs. :) And yes, LK is unkillable, confirmed!

**Comment by Kisskam** [comment]
I confirm that when he is at 10% health and his weapon breaks, he can no longer be killed.

* I put this with a translator because I don't speak English

**Comment by Ramys** [comment]
I just tested it, and it really doesn't die at 10% health.
Confirmed!
