### ISSUE TITLE
Archavon the Stone Watcher Voa 10/25 rocks shard spell

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1082]
Archavon the Stone Watcher Voa 10/25 Rocks shard spell not working

##### SMALL DESCRIPTION:

Archavon the Stone Watcher Voa 10/25 rocks shard spell - https://www.wowhead.com/spell=58678/rock-shards ability is aimed at himself and not players, (Shooting his feet.) He should be shooting on a random target making him run away and being able to dodge them

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Archavon the Stone Watcher Voa 10/25 rocks shard spell - https://www.wowhead.com/spell=58678/rock-shards ability  should be shooting on a random target making him run away and being able to dodge them

##### CURRENT BEHAVIOUR:

Archavon the Stone Watcher Voa 10/25 rocks shard spell - https://www.wowhead.com/spell=58678/rock-shards ability is aimed at himself and not players, (Shooting his feet.) He should be shooting on a random target making him run away and being able to dodge them

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run VoA and attack Archavon the Stone Watcher
2. 
3. 

##### BRANCH(ES):

master

**Comment by Pondaveia** [comment]
Can someone confirm this bug?

**Comment by Knindzagxg** [comment]
Yeah, i confirm this one as well.

https://www.youtube.com/watch?v=iOFr86DrfpU

**Comment by Knindzagxg** [comment]
Bump, needs a Dev.

**Comment by Stoabrogga** [comment]
I'll look into this
