### ISSUE TITLE
Judgement of Light, Judgement of Wisdom healing/mana regen proc

### ISSUE THREAD

**Issue by Dejanos** [azerothcore/azerothcore-wotlk#10820]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

Originally reported:  https://github.com/chromiecraft/chromiecraft/issues/3100

### Current Behaviour

When you attack a target affected by Judgement of Light or Judgement of Wisdom your mana stops regenerating. 

Proc might be considered a cast so if you don't have mana regen while casting you don't get any while the healing (or proc from Judgement of Wisdom) happens.

Judgement of Light:

https://user-images.githubusercontent.com/91145640/154801597-4f442d3a-57d7-4eec-9d99-823e95401c44.mp4

Judgement of Wisdom:

https://user-images.githubusercontent.com/91145640/154801776-e3c2d36e-e527-4d85-bbf2-72f18a8be634.mp4

### Expected Blizzlike Behaviour

Mana regeneration shouldn't stop.

### Steps to reproduce the problem

1. Use Judgement of Light/Wisdom without any MP5.
2. Check mana regen on judgment proc.

### Extra Notes

Bug found by Omniknight.

Issue regarding the current JoL, JoW debuff behaviour.

Describing Issue: Once party/raid targets auto attack the target with JoL/JoW debuff, when the proc effects for healing/mana regen activates, the proc is registered as an instant cast/spell, mitigating mana regeneration by around 45%, as that is the issue once spells or casts have been used. Therefore, when Judgment debuff healing/mana regen procs on auto attack, players who auto attacked the debuffed target will stop regenerating mana completely if they have no mana regen and players with some or high mana regen will experience a loss of mana regeneration of around 45% as is stated for spells and casts.

Possible issue cause: Cause could be that the proc is being registered as the instant cast/spell, therefore mitigating mana regen on auto attack proc for all players involved in the raid/party.
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
It is like that because you use spells with mana cost.

**Comment by UltraNix** [comment]
It's like this because you cast spell with mana cost. I thinks it's okay.
