### ISSUE TITLE
Naxx 10/25 Thaddius - Positive / Negative charge not working correctly

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1083]
Naxx 10/25 Thaddius - Positive / Negative charge not working correctly

##### SMALL DESCRIPTION:

Naxx 10/25 Thaddius - Positive / Negative charge not working correctly

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The positive/negative charge in this encounter should allow players to stand on the correct charge and not receive damage.

##### CURRENT BEHAVIOUR:

The wrong charge is being activated, for example players are getting damage if they stand at either the positive or negative charge at the right time

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run Thaddius in Naxx
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

fc4b52b036a33f1207acca8c93a4c9ef3f9baa10

**Comment by BarbzYHOOL** [comment]
That makes me think we have like 4 PRs about Naxxramas that you should try as I showed you in private. Example: https://github.com/azerothcore/azerothcore-wotlk/pull/1032

**Comment by comix1988** [comment]
@Nefertumm 
I've tested Thaddius now, but I can't find any problems with the damage from the electrical charges.
Tested in a nax 25:
- If two players with opposite electric charge are close they take 4500 damage every 5 seconds;
- if the charges are equal, a buff is applied that increases the damage by 10%;
- If two players with the same charge are close together, they do not take damage;

![wowwiki](https://user-images.githubusercontent.com/22867608/55582979-0c18cd00-5721-11e9-8f4e-064f7d81d2d8.png)
![capt](https://user-images.githubusercontent.com/22867608/55582980-0de29080-5721-11e9-8d17-a01e77aeb67f.png)

https://youtu.be/k9fzQ7OVWvo

tested on master branch with commit 5105333968e2f3b1e421ba739c4aac703523f873

**Comment by disclosurez** [comment]
seems fixed
