### ISSUE TITLE
Darnassus Shield Merchant Caynrus holding blue/white box.

### ISSUE THREAD

**Issue by Halokillerman7** [azerothcore/azerothcore-wotlk#1084]
##### EXPECTED BLIZZLIKE BEHAVIOUR:
Not holding a blue/white box.

##### CURRENT BEHAVIOUR:
Caynrus(4240) is holding a blue and white box.
https://imgur.com/XC4ZW3x
https://imgur.com/SSo4Eob

##### STEPS TO REPRODUCE THE PROBLEM:
Go to location on map and look a the vendor
https://imgur.com/SSo4Eob

##### STEPS TO FIX THE PROBLEM
creature_equip_template > 4240 > ItemID1 > 1961 orginal > Replace with 0 or delete
As shown below on wowhead he does not hold anything.
https://wow.zamimg.com/uploads/screenshots/normal/606476-caynrus.jpg

**Comment by poszer** [comment]
Confirmed :+1: 
[Picture](http://prntscr.com/ljpjeo)

**Comment by talamortis** [comment]
@Halokillerman7  it looks like you have sent the fix aswell 

> creature_equip_template > 4240 > ItemID1 > 1961 orginal > Replace with 0 or delete

Are you able to do a PR

**Comment by poszer** [comment]
> 
> 
> @Halokillerman7 it looks like you have sent the fix aswell
> 
> > creature_equip_template > 4240 > ItemID1 > 1961 orginal > Replace with 0 or delete
> 
> Are you able to do a PR

I'll do it now

**Comment by Halokillerman7** [comment]
Thanks never did a PR and forgot to look at it to do one.

**Comment by BarbzYHOOL** [comment]
On wowhead, you took the newest models screenshots, but look at an old screenshot: https://wow.zamimg.com/uploads/screenshots/normal/44841-caynrus.jpg @Halokillerman7 @poszer

**Comment by Halokillerman7** [comment]
Yeah I was not sure if that’s was correct fix or not wowhead didn’t show any screens with a shield

**Comment by BarbzYHOOL** [comment]
maybe we could put a shield instead in his hand lol

**Comment by Halokillerman7** [comment]
That I saw

**Comment by Halokillerman7** [comment]
Yeah I think it needed swapped to show the model shield

**Comment by poszer** [comment]
> 
> 
> On wowhead, you took the newest models screenshots, but look at an old screenshot: https://wow.zamimg.com/uploads/screenshots/normal/44841-caynrus.jpg @Halokillerman7 @poszer

Yeah, if you want, i'll update it to hold shield :rofl:

**Comment by Xgap** [comment]
> > On wowhead, you took the newest models screenshots, but look at an old screenshot: https://wow.zamimg.com/uploads/screenshots/normal/44841-caynrus.jpg @Halokillerman7 @poszer
> 
> Yeah, if you want, i'll update it to hold shield 🤣

try this

```
DELETE FROM `creature_equip_template` WHERE `CreatureID`=4240 AND `ID`=1;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`) VALUES (4240, 1, 35, 0, 0, 12340);
```

**Comment by BarbzYHOOL** [comment]
post screenshot :D

**Comment by Xgap** [comment]
> post screenshot :D

checked and working 👍 
[Picture](http://funkyimg.com/i/2Nsr5.png)

**Comment by poszer** [comment]
Ok, i'll update it

**Comment by poszer** [comment]
> 
> 
> Ok nice, even though it's not a shield :P

Updated, [ab3984a](https://github.com/azerothcore/azerothcore-wotlk/pull/1089/commits/ab3984a10d32033c766c5d1d42ce8b4d9ddd7677)
