### ISSUE TITLE
Gravis Slipknot fix

### ISSUE THREAD

**Issue by Whyy0416** [azerothcore/azerothcore-wotlk#10848]
### Current Behaviour

Commit `a9326d292ef238b9b7c4c8fe981aa79ed0133b4b` has a wrong column name `ID` at 

> "UPDATE `creature_equip_template` SET `ItemID1` = 4560, `VerifiedBuild` = 0 WHERE `CreatureID` = 14221 AND `ID` = 1;"  

So that this SQL execute with failed return, but somehow it wrote to database successful.
I checked 5.00 database basic SQL, confirm this issue still there.

### Expected Blizzlike Behaviour

Gravis Slipknot should be fixed instead of a giant sword in game.

### Steps to reproduce the problem

1.type `.go creature 86756`

### Extra Notes

 1).Chage this commit to

> "UPDATE `creature_equip_template` SET `ItemID1` = 4560, `VerifiedBuild` = 0 WHERE `CreatureID` = 14221 AND `ID1` = 1;"

2),Re-execute this commit.

### AC rev. hash/commit

23cd1883d67a0f7c3bb421a05e9ab6e00fd40b66

### Operating system

Windows 10 x64

### Custom changes or Modules

none

**Comment by benjymansy123** [comment]
#8300

**Comment by Whyy0416** [comment]
I noticed this fix has been merged, But when I check this commit I found it doesn't fix. This issue also remain in released 5.00 database.
This commit has move respawn point to  717.6572, -846.4034, 160.7536. But here is in 5.0 database basic file:

>  (86756, 14221, 0, 0, 0, 0, 0, 1, 1, 1, 692.679, -934.641, 164.951, 2.86531, 72000, 0, 0, 1469, 0, 0, 0, 0, 0, '', 0),

Also there's no data in waypoint_data.sql that id equals to 867560.
