### ISSUE TITLE
duplicated creature guid

### ISSUE THREAD

**Issue by Whyy0416** [azerothcore/azerothcore-wotlk#10849]
### Current Behaviour

Commit `c6934b0619b95f65c8de457d7de4544eea05d6c8` and commit `f5419a45a71ec91d5729c97f0d0bb73124322a9b` use a duplicated creature guid (24181 - 24186). So Spirestone Warlord respawn point is covered by Un'Goro Develsaur.

### Expected Blizzlike Behaviour

Both Spirestone Warlord and Un'Goro Develsaur should spawn properly.

### Steps to reproduce the problem

1. type `.go creature 24187` 
2. there is only 3 Spirestone Warlord in Lower Blackrock Spire

### AC rev. hash/commit

23cd1883d67a0f7c3bb421a05e9ab6e00fd40b66

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by malcrom** [comment]
Please supply commit links not hash codes.

**Comment by Whyy0416** [comment]
Sorry about that. Here's links:
[https://github.com/azerothcore/azerothcore-wotlk/pull/10079](url)
[https://github.com/azerothcore/azerothcore-wotlk/pull/10171](url)

**Comment by Whyy0416** [comment]
Confirm this is solved by
chore(DB/Creature): LBRS guid conflict resolve #10194
