### ISSUE TITLE
Quest Precarious Predicament does not complete

### ISSUE THREAD

**Issue by Jackomighty** [azerothcore/azerothcore-wotlk#10840]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When escort is finished, quest is not automatically completed and waypoint of the quest is near the player instead of questgiver Lexlort (guid=6882)

### Expected Blizzlike Behaviour

Quest should be completed when escort is completed aka. when all 3 creatures related to the questline despawn.

### Source

https://classic.wowhead.com/quest=4121/precarious-predicament#comments:id=2961292

### Steps to reproduce the problem

.teleport burningsteppes
.go c 10
.quest add 4122 (required quest for Precarious Predicament)
.quest complete 4122
Accept quest Precarious Predicament manually from the NPC.
Damage NPC until it becomes friendly and use quest item on him.
Follow the rest of the quest until you end up at Searing Gorge where NPC-s related to the quest despawn.

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/2982

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None
=

### Server

ChromieCraft
-

**Comment by mielipiru** [comment]
Still reproducible. The "Prisoner Transported" step doesn't complete after NPCs have spoken on Searing Gorge side. Quest cannot be turned in afterwards, due to missing step.

**Comment by whipowill** [comment]
Confirming this bug still exists in the game.

**Comment by howtokana** [comment]
Can also confirm, still exists.
