### ISSUE TITLE
Some old commit issue and fix

### ISSUE THREAD

**Issue by Whyy0416** [azerothcore/azerothcore-wotlk#10846]
### Describe your feature request or suggestion in detail

1.Commit "cda264cfe11397defa79008e772c7a10dfac8ffe" insert 2 wrong spawn points to Death Howl, the map value should be 1. It's been a while when I found this issue, but I forgot to report it.
Solution: "UPDATE `creature` SET `map` = 1 WHERE `guid` IN (152290,152291);"

2.Commit "a9326d292ef238b9b7c4c8fe981aa79ed0133b4b" has a wrong column `ID` at "UPDATE `creature_equip_template` SET `ItemID1` = 4560, `VerifiedBuild` = 0 WHERE `CreatureID` = 14221 AND `ID` = 1;"  So that this SQL execute with failed return, but somehow it wrote to database successful. I checked 5.00 database basic SQL, confirm this issue still there.
Solution: 1).Chage this commit to
"UPDATE `creature_equip_template` SET `ItemID1` = 4560, `VerifiedBuild` = 0 WHERE `CreatureID` = 14221 AND `ID1` = 1;"
2),Re-execute this commit.

 3.Commit "a82d8a69822e88be3820c8aa219b4ef2843718dc" hasn't repair Burning Blade npcs weapon.
Solution: "UPDATE `creature` SET `equipment_id` = 1 WHERE `id1` IN (4663,4664,4665,4666,4667);"

4.Commit "c6934b0619b95f65c8de457d7de4544eea05d6c8" and commit "f5419a45a71ec91d5729c97f0d0bb73124322a9b" use a duplicated creature guid (24181-24186). So Spirestone Warlord respawn point is covered by Un'Goro Develsaur.

**Comment by Kitzunu** [comment]
1. Open a bug report
2. Only one bug per report
