### ISSUE TITLE
./acore.sh docker client-data failed on macbook m1

### ISSUE THREAD

**Issue by yagche** [azerothcore/azerothcore-wotlk#10851]
### Current Behaviour

Running: docker-compose run --rm ac-build bash acore.sh client-data
[+] Running 0/1
 ⠋ ac-database Pulling                                                     4.9s
no matching manifest for linux/arm64/v8 in the manifest list entries
error: Uncaught (in promise) Error: Failed with error: 18, however,
            it's not related to this Deno script directly. An error occurred within
            the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///Users/chenyang/azerothcore-wotlk/apps/docker/docker-cmd.ts:290:17)
    at async Promise.all (index 0)
    at async file:///Users/chenyang/azerothcore-wotlk/apps/docker/docker-cmd.ts:240:5

### Expected Blizzlike Behaviour

apps/docker/docker-cmd.ts should be modified to work on macbook m1

### Steps to reproduce the problem

1. git clone https://github.com/azerothcore/azerothcore-wotlk.git
2. cp conf/dist/config.sh conf/config.sh
3. ./acore.sh docker client-data

### AC rev. hash/commit

743c028e31740afebe73afa15ee0ed2e1b4926da

### Operating system

mac os 12.2.1 macbook air m1

**Comment by Kitzunu** [comment]
Mac os 12 not supported. Maybe @FrancescoBorzi <mac lover> can take a look to support it

**Comment by yagche** [comment]
macOS is moving to arm, if you support macOS, you should support arm. 
i tried setup the project without using the docker script before, the step of "./acore.sh docker client-data" is actually downloading some files, it should work on arm.

**Comment by Kitzunu** [comment]
Nobody has had an interest in ARM so nobody implemented it.

**Comment by yagche** [comment]
docker supports build and run x86 images on macbook m1, it looks like this:
`docker buildx build --platform linux/amd64`
https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images
