### ISSUE TITLE
guild bank is gone when restart the server

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#10863]
### Current Behaviour

guild bank is gone when restart the server
i try to build an other guild, and get a new guild bank
but when the server restart , it is gone .
i search the character db, it is exsist, but not in game.

### Expected Blizzlike Behaviour

guild bank not work when the server restart

### Steps to reproduce the problem

i used the 13days ago version.
81f6de5

### AC rev. hash/commit

.

### Operating system

ubuntu 21

**Comment by Nyeriah** [comment]
Thanks for taking the time to report this but your core is outdated and needs updating. Please update your core before opening issues. This was already fixed.
