### ISSUE TITLE
quest id 9967 is can not finished

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#10864]
### Current Behaviour

quest id 9967 is can not finished
this quest is the quest id 9962's next step

### Expected Blizzlike Behaviour

it should finish when kill the brothers.

### Steps to reproduce the problem

i used the 13days ago version.
81f6de5
finish the quest id 9962 ,
the lead the next step quest id 9967

### AC rev. hash/commit

.

### Operating system

ubuntu 21

**Comment by Kisskam** [comment]
I confirm that the mission is not completed by killing the 2 brothers.

*I don't speak English, I use a translator to be able to communicate.

**Comment by 5266869** [comment]
yes, please fix it. thanks
