### ISSUE TITLE
some very minor "bugs" in c9586a106b4b+

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/azerothcore-wotlk#10896]
### Current Behaviour

There seem to be some GM commands not working properly

Like the .modify speed commands doesnt work
Chat window says they work when u write it but player speed doesnt change
The only .modify speed command that works is .modify speed all

The .npc info command show wrong numbers for Faction, NPCflags, Entry and DisplayID
looks like this
https://i.ibb.co/SBh7GHs/NPCINFO.png
Basically the Faction and NPCflags is the entry and entry and display ID is always 0 on all NPCs

The creature_equip_template doesnt trigger in game on new changes but u can work around this by using SmartAI to equip weapons instead

### Expected Blizzlike Behaviour

read above

### Steps to reproduce the problem

Read above

### AC rev. hash/commit

 c9586a106b4b+

### Operating system

Windows 10

### Custom changes or Modules

A lot of database changes but no changes in the command table in the database which I assume handles this

**Comment by adink1** [comment]
.npc info

**Comment by Kitzunu** [comment]
works.

**Comment by Sulan2** [comment]
Managed to figure out one part of this, the problem with NPC info was an outdated acore_string database

Now just need to figure out why NPCs doesnt spawn with weapons...
