### ISSUE TITLE
Elemental Mastery gets used up by all spells

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#10903]
### Current Behaviour

The instant-cast effect of Elemental Mastery, the Elemental Shaman talent, gets used up by spells other than those listed with the ability. All offensive abilities use up the effect.

### Expected Blizzlike Behaviour

Elemental Mastery should make Lightning Bolt, Chain Lightning or Lava Burst be instant cast and it should consume the effect when only one of those is cast.

### Steps to reproduce the problem

1. Learn the Elemental Mastery talent
2. Use the ability
3. Use any of the offensive abilities Shaman has

### AC rev. hash/commit

742a568

### Operating system

Debian 11 x64

**Comment by PsYchoNauTek** [comment]
can confirm that
