### ISSUE TITLE
[BWL] Trash packs are not linked together

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10907]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

1. Trash packs can be pulled in half or less.

### Expected Blizzlike Behaviour

1. Trash packs should be linked

### Extra Notes
Some may be linked already, just nothing all that should be linked: 

![image](https://user-images.githubusercontent.com/20357406/156915126-2daf125c-5e31-45e8-8e30-434e077ee76c.png)
Death Talon Wyrmguard 84592
84591 84590 84589 84573
![image](https://user-images.githubusercontent.com/20357406/156915396-6e5bf933-4b17-405e-be6d-7aaf677adfe9.png)
84634 84628 84635 

![image](https://user-images.githubusercontent.com/20357406/157276765-a1351494-da64-488c-8d07-ed2a92e77dc7.png)

this whole pack (.go c 84558)

![image](https://user-images.githubusercontent.com/20357406/157277049-2632cbe4-6d7e-443f-b565-3094bff32210.png)
this whole pack (.go c 84557)

![image](https://user-images.githubusercontent.com/20357406/157277129-557ff00e-ed74-4dab-8d33-b0f7a2d0c405.png)
(.go c 84625)

![image](https://user-images.githubusercontent.com/20357406/157277210-2e58a757-a46a-417d-99e6-c152761c3519.png)
(.go c 84840)

![image](https://user-images.githubusercontent.com/20357406/157277276-ce82d65a-098c-4170-8119-b309872e01ce.png)
(.go c 85756)
 
![image](https://user-images.githubusercontent.com/20357406/157277345-c49b9ddc-1569-4a79-a212-7c913044eb80.png)
(.go c 85759)

###Server

ChromieCraft PTR

### AC rev. hash/commit

rev. 982be6de0081

### Operating system

Ubuntu 20.04

### Modules

mod-anticheat (master) 
mod-autobalance (master)
mod-cfbg (master)
mod-chromiexp (master)
mod-chromiecraft (master)
mod-desertion-warnings (master)
mod-duel-reset (master)
mod-eluna-lua-engine (master)
mod-ip-tracker (master)
mod-low-level-arena (master)
mod-multi-client-check (master)
mod-progression-system (master)
mod-pvp-titles (master)
mod-pvpstats-announcer (master)
mod-queue-list-cache (master) 
mod-rdf-expansion (master) 
mod-save-inventory (master)
mod-server-auto-shutdown (master)
mod-spellsystem-extended (master)

### Customizations

Acore_eventScripts (master)
Acore_SendAndBind (master)
Acore_TempAnnouncements (master)
Acore_ZoneDebuff (master)

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10436
Strange, some of them are already done here. Are they still not working?

**Comment by temperrr** [comment]
Hmm ill double check

**Comment by temperrr** [comment]
Updated the issue @Nefertumm
