### ISSUE TITLE
Lock and Load，the talent of hunters，doesn't work with Black Arrow

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#10919]
### Current Behaviour

Lock and Load，the talent of hunters，doesn't work with Black Arrow，it never triggers.
but the traps triggers Lock and Load well.

### Expected Blizzlike Behaviour

Lock and Load should be triggered by Black Arrow by chance.

### Steps to reproduce the problem

1,create a character of hunter,
2,test Lock and Load with Black Arrow.

### AC rev. hash/commit

5ed4db09e3c8+

### Operating system

windows 10 x64

**Comment by Sulan2** [comment]
Hey I dont work for acore but I feel this might be a problem with the spell.dbc file instead of a server problem

If u download stoneharrys spelleditor (which is incredible) and import the spell.dbc into it and search for ID 56453 which is the lock and load proc
In Effects -> Effects 2 -> spell effects 1 and 2 -> Spell class mask 2, is there a box ticked for expolsive shot here?

**Comment by fullofstarschen** [comment]
![e1](https://user-images.githubusercontent.com/58200693/158004060-21a5ec5d-567d-4b12-96aa-5f30da0df15a.png)
![e2](https://user-images.githubusercontent.com/58200693/158004061-432970ee-9e3f-4549-ab5e-65542d268b8f.png)
I don't understand the code,and I can't find where expolsive shot is...

**Comment by Sulan2** [comment]
if u scroll down in the box with the names of all spells on the right side, is there IDs for explosive shot there?

**Comment by Sulan2** [comment]
Sry I was thinking about this the wrong way, u can forget about my last comments

Search for Lock and load in the spell editor
The IDs
56342
56343
56344

Are the ones proccing the trigger, all of these should have in Effects -> Effects 1 -> Procs On periodic effect done and on trap trigger box checked
All of these should also have effects -> effects 2 -> spell effect 1 -> Misc Value = 2

if this doesnt work it might work to remove the spell script made located in the database acore_world -> spell_script_names called 
-56342 spell_hun_lock_and_load

**Comment by fullofstarschen** [comment]
All of the above is active, I will try to remove spell script from acore_world，thank you!

**Comment by fullofstarschen** [comment]
The spell script removed but not work.

**Comment by Sulan2** [comment]
when u look at the IDs 
56342
56343
56344

Does all of these in spell effects 2 have a spell effect called 6 apply aura and apply aura name 4 spell aura dummy?

**Comment by fullofstarschen** [comment]
I checked that,it is like this
![1112](https://user-images.githubusercontent.com/58200693/158086375-9bf2a443-600c-4d69-8c48-59b7ce1cfc4b.png)
I use standard Data V13

**Comment by Sulan2** [comment]
Looks identical to mine that is working, do u have a very old version of ACore? 
Are u 100% sure it doesnt work? it can be hard to proc it from black arrow, if u change the tick time for black arrow it might be easier to test it

**Comment by fullofstarschen** [comment]
I have the latest version,
I use a macro like this, 
/cast blackarrow 
/target myself
.cooldown

**Comment by Sulan2** [comment]
Ive never heard of that .cooldown command not sure what it does but it still procced for me
I use .cheat cooldown on
Anyway if u try this on a dummy and shoot black arrow on it then target yourself dont u loose combat pretty fast and the dot effect goes away?

**Comment by fullofstarschen** [comment]
I'm not sure,let's see if someone has the same problem.Thank you.

**Comment by UltraNix** [comment]
Fixed by #11862
