### ISSUE TITLE
Core/Gossip: quest_greeting_locale doesn't work

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#10913]
### Current Behaviour

quest_greeting_locale table doesn't work, it just fetches the English texts.

### Expected Blizzlike Behaviour

Should fetch the locales

### Steps to reproduce the problem

Enter data into quest_greetings_locale

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d927ce6facd4150f5da448a1b147ab89a18335a6

### Operating system

W11

**Comment by Winfidonarleyan** [comment]
I try fix this
