### ISSUE TITLE
Issue in Quest  “The Air Stands Still “

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#10924]
### Current Behaviour

When player use the War Horn of Acherus to summon a knight of the Ebon Blade for help,nothing happend.

### Expected Blizzlike Behaviour

The War Horn of Acherus can summon a knight of the Ebon Blade.

### Steps to reproduce the problem

1,Get the quest The Air Stands Still,
2,Go to the  exactly place and use War Horn of Acherus,
3,watch what happend.

### AC rev. hash/commit

 5ed4db09e3c8+

### Operating system

windows 10 x64

**Comment by malcrom** [comment]
This is a very poor issue report. please add ids or links to wowhead,

**Comment by fullofstarschen** [comment]
Sorry,please reproduce that just like this:
1, .quest add 13125
2,Go to the exactly place and use War Horn of Acherus,
3,watch what happend.

**Comment by Tony931023** [comment]
fix https://github.com/azerothcore/azerothcore-wotlk/pull/12349 

Close issues

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/1704c78caa9ffa88996874224417d9111524a924
