### ISSUE TITLE
wrong dismount

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10945]
### Current Behaviour

Mount a flying mount. After passing through this area, the mount will be released

.go xyz 6966.457520 -1050.787476 1005.334900

### Expected Blizzlike Behaviour

This position should not disarm the mount

### Steps to reproduce the problem

1.mount a flying mount
2. .go xyz 6966.457520 -1050.787476 1005.334900
3.you will automatically release the mount

### AC rev. hash/commit

acd3ed8759477e6059b31f88377a790f3a0d8133

### Operating system

Ubuntu20.04

**Comment by Bogir** [comment]
What is the number of the map?

**Comment by mpfans** [comment]
map 571 ,only copy `.go xyz 6966.457520 -1050.787476 1005.334900` can get there

**Comment by fullofstarschen** [comment]
I can confirm this,players die just for pass by this area.

**Comment by mpfans** [comment]
It is caused by the wrong judgment of Z coordinate

**Comment by mpfans** [comment]
tested,work now ,but `.go xyz 6965.391602 -1063.848999 863.463440` unable to summon flying mount, need further fix.
