### ISSUE TITLE
[BWL] Blackwing Warlocks are all dead

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10950]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

1. All Blackwing Warlocks are dead / not there.
![image](https://user-images.githubusercontent.com/20357406/157410603-6d155c41-e6ec-4f31-b28f-b0dde9977560.png)
![image](https://user-images.githubusercontent.com/20357406/157410642-b7b20c6d-1cc4-4e61-a86e-e6f96b8b3e4a.png)

### Expected Blizzlike Behaviour

1 They should be alive

### Extra Notes
 all db guids of dead ones:
 84542 84541 84553 84560  84561  84598 84599 84653 84652 85581 85601  85757 85775
 

###Server

ChromieCraft PTR

### AC rev. hash/commit

rev. 982be6de0081

### Operating system

Ubuntu 20.04

### Modules

mod-anticheat (master) 
mod-autobalance (master)
mod-cfbg (master)
mod-chromiexp (master)
mod-chromiecraft (master)
mod-desertion-warnings (master)
mod-duel-reset (master)
mod-eluna-lua-engine (master)
mod-ip-tracker (master)
mod-low-level-arena (master)
mod-multi-client-check (master)
mod-progression-system (master)
mod-pvp-titles (master)
mod-pvpstats-announcer (master)
mod-queue-list-cache (master) 
mod-rdf-expansion (master) 
mod-save-inventory (master)
mod-server-auto-shutdown (master)
mod-spellsystem-extended (master)

### Customizations

Acore_eventScripts (master)
Acore_SendAndBind (master)
Acore_TempAnnouncements (master)
Acore_ZoneDebuff (master)

**Comment by Nefertumm** [comment]
![image](https://user-images.githubusercontent.com/19627365/157583087-6831b25e-906f-4dda-9c36-e1c55d198f22.png)
![image](https://user-images.githubusercontent.com/19627365/157583140-32e9443b-8b2f-4a94-91b3-38b8f85a78ae.png)

I couldn't reproduce it. Did you do something extra? Which bosses did you kill?

**Comment by Nefertumm** [comment]
I found the issue, it was some fucked up thing with linked_respawn.
