### ISSUE TITLE
[BWL] Nefarian adds should be random selected

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10952]
### Current Behaviour

1) randomly spawning any of the available drakonids

### Expected Blizzlike Behaviour

Minions during phase 1 should be selected randomly but only 2 kinds + always chromatic one.
Chromatic one should be more rarely spawned as the other kinds.

### Source

https://classic.wowhead.com/guides/nefarian-blackwing-lair-strategy

### Steps to reproduce the problem

Go to nef in BWL

### AC rev. hash/commit

707968ee95f5c670eb0babb3a708603940ed368d
### Operating system

Manjaro x64

### Custom changes or Modules

~

**Comment by Kitzunu** [comment]
You are not using a valid hash.

If you are experiencing this while on a PR you should report the error on that PR
