### ISSUE TITLE
[BWL]  Nefarian Reset mechanics

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10951]
### Current Behaviour

1) Dying during phase transition results in no reset, you can also spawn multiple nefs this way to farm him possibly?
2) Dying after killing nef but with adds still alive results in nef's body despawning and you able to summon him again. 

### Expected Blizzlike Behaviour

1) Dying during phase transition should result in a reset
2) Dying after killing nef should not cause the body to reset or allow you to respawn a new boss, as you could have obtained the loot already.

### Source

`

### Steps to reproduce the problem

Go to nef in BWL

### AC rev. hash/commit

707968ee95f5c670eb0babb3a708603940ed368d

### Operating system

Manjaro x64

### Custom changes or Modules

~

**Comment by Kitzunu** [comment]
You are not using a valid hash.

If you are experiencing this while on a PR you should report the error on that PR

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/157524171-9355eb1c-e880-4e58-ae8c-b0917d8d7097.png)
![image](https://user-images.githubusercontent.com/18535853/157524214-d00d229b-2e67-4750-b2a7-6c0017ba2d0b.png)
Please create a pull. My main branch is damaged

**Comment by FrancescoBorzi** [comment]
@pklloveyou thank you, we will make a PR with your contribution.

> My main branch is damaged

I can help you fix it if you want

**Comment by pklloveyou** [comment]
@FrancescoBorzi After waiting for #10900 merging, I'll just recreate a main branch

**Comment by Nefertumm** [comment]
Thanks @pklloveyou, I'm going to look at it and if it works, I'll just open a PR :)
