### ISSUE TITLE
[BWL] Killing Razorgore with the Eggs still alive should wipe the raid

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#10964]
### Current Behaviour

If you kill razorgore, event just ends

### Expected Blizzlike Behaviour

You should destroy all the eggs first before killing razorgore, else the whole raid wipes and he resets.

### Source

BWL research by Nyeriah.
![image](https://user-images.githubusercontent.com/20357406/157603698-3012eb0a-c4e6-4ca8-a78c-b22cdc4942f2.png)

### Steps to reproduce the problem

1. Go to BWL
2. Kill Razorgore without killing the eggs

### AC rev. hash/commit

707968ee95f5c670eb0babb3a708603940ed368d

### Operating system

Manjaro x64

### Custom changes or Modules

-

**Comment by FALL1N1** [comment]
Does he kill all /instant death/ or just enrages, because I honestly don't remember? If he just kills all is it this spell? https://classic.wowhead.com/spell=20038

**Comment by Nyeriah** [comment]
Yes, I'm already working on this..
