### ISSUE TITLE
[Ulduar] `Salvaged Siege Engine` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#10967]
### Current Behaviour

When the 'salvaged siege engine'(id 33060) is controlled by someone, when another player boarded the 'salvaged siege engine' passenger seat, he has no skills and can't perform any operations. He can only log out and re-enter the game,re entering the game will be kicked out of the co pilot position

https://youtu.be/YRORIAnMdUo

### Expected Blizzlike Behaviour

When boarding the 'salvaged siege engine', if there are players in the main driving position, they will automatically log in to the co pilot position and control the fort

### Steps to reproduce the problem

1. Two characters enter the same Ulduar , and start the dialogue to fight
2. character a mount a `Salvaged Siege Engine`(id 33060)
3. character b mount same a  `Salvaged Siege Engine`

### AC rev. hash/commit

e2d7dc9bd7fc636469e46b82587a92f43e7825d9

### Operating system

ubuntu 20.04

**Comment by pangolp** [comment]
I had made a similar report some time ago, I add it here, so when it is solved, both topics will be closed. https://github.com/azerothcore/azerothcore-wotlk/issues/1317

**Comment by UltraNix** [comment]
Duplicate.
