### ISSUE TITLE
Crash bind to reset instance

### ISSUE THREAD

**Issue by Lynethris** [azerothcore/azerothcore-wotlk#10965]
### Current Behaviour

A crash server come ofen after a reset instance. 

### Expected Blizzlike Behaviour

None

### Source

The source seems to have been located by @SilentCLD (sources #10819 ) : 

![Screenshot 2022-03-10 145234](https://user-images.githubusercontent.com/100411212/157675974-a5d9687d-dcc4-4b31-8f89-3d21579e3570.png)

Dump file:
[6e35325a9cef_worldserver.exe_[10-3_8-30-50].zip](https://github.com/azerothcore/azerothcore-wotlk/files/8221231/6e35325a9cef_worldserver.exe_.10-3_8-30-50.zip)

Worldserver error:
![Screenshot 2022-03-10 083129](https://user-images.githubusercontent.com/100411212/157611427-582592ca-b98e-4e64-aee2-5f2d63096378.png)

### Steps to reproduce the problem

1. binding to an instance
2. gracefully restarting the server
3. instance unbind all

### AC rev. hash/commit

AzerothCore rev. 6e35325a9cef

### Operating system

Windows 11

**Comment by Nefertumm** [comment]
Confirmed.

**Comment by mpfans** [comment]
my server on https://github.com/azerothcore/azerothcore-wotlk/commit/e2d7dc9bd7fc636469e46b82587a92f43e7825d9

not crash.

**Comment by Nefertumm** [comment]
I could reproduce the crash taking a save on whatever instance, go to gmisland (or whatever location you like), restart the server, log back again and run the command .ins unbind all

**Comment by mpfans** [comment]
> I could reproduce the crash taking a save on whatever instance, go to gmisland (or whatever location you like), restart the server, log back again and run the command .ins unbind all

Tell me the detailed steps of reproduction. In addition Did you install the module? Is it caused by the module?

**Comment by Bogir** [comment]
About https://github.com/azerothcore/azerothcore-wotlk/pull/10819
3-rf condition `else if (me->IsSummon()...` called if first can't be reached `if (me)`
So, what `me` in 3-rd condition must have? Nullptr?

**Comment by Lynethris** [comment]
> About #10819 3-rf condition `else if (me->IsSummon()...` called if first can't be reached `if (me)` So, what `me` in 3-rd condition must have? Nullptr?

Just to be sure. I mentioned the crash for the first time in this PR but this PR it's not the source. I encounter this crash also in the current master branch.

**Comment by Kitzunu** [comment]
Cam you post the call stack on gist so I dont need to download stuff please

**Comment by Lynethris** [comment]
> Cam you post the call stack on gist so I dont need to download stuff please
I don't know if this is what you want (I can't post directly the dump memory file) : 

[6e35325a9cef_worldserver.exe_[10-3_8-30-50].txt](https://github.com/azerothcore/azerothcore-wotlk/files/8224344/6e35325a9cef_worldserver.exe_.10-3_8-30-50.txt)

**Comment by Lynethris** [comment]
> Cam you post the call stack on gist so I dont need to download stuff please

I'm sorry the call stacks is too big (548ko).

**Comment by SilentCLD** [comment]
> About #10819 3-rf condition `else if (me->IsSummon()...` called if first can't be reached `if (me)` So, what `me` in 3-rd condition must have? Nullptr?

@Bogir I think you misread, first it checks if `me` is valid and if it is then `me->IsSummon()..` can be called. It is nested not an else
https://github.com/azerothcore/azerothcore-wotlk/blob/d1b7c7ccc98d309be276b9c4a24254ec01f52af3/src/server/game/AI/SmartScripts/SmartScript.cpp#L3841.

**Comment by Lynethris** [comment]
> Cam you post the call stack on gist so I dont need to download stuff please

I'm sorry. I discovered gist github today. Calls stack here : https://gist.github.com/Lynethris/f930afc29f5372eb0a37fb9a88430c64

**Comment by Winfidonarleyan** [comment]
1f90a18a5888a12a9b3bc32a0d4804baf81d51fe

I've tried many times, but I can't reproduce this problem

**Comment by DepTypes** [comment]
I could reproduce this bug by logging 2 characters.
Entering a dungeon, killing one NPC.
Exit dungeon
Server restart with admin command

After restart use reset instances. 

```cpp
bool InstanceSaveMgr::DeleteInstanceSaveIfNeeded(InstanceSave* save, bool skipMapCheck)
{
        // ....
        delete save; // Attempt to delete locked mutex
        return true;
    }
    return false;
}
```

Deleting the `InstanceSave` instance here is not possible because it's called from where the mutex is locked until return from here.

```cpp
bool InstanceSave::RemovePlayer(ObjectGuid guid, InstanceSaveMgr* ism)
{
    std::lock_guard<std::mutex> guard(_lock);
    m_playerList.remove(guid);

    // ism passed as an argument to avoid calling via singleton (might result in a deadlock)
    return ism->DeleteInstanceSaveIfNeeded(this->GetInstanceId(), false);
}
```

Walking back up the call stack. The delete could be called here instead after the lock has been released:
```cpp
bool InstanceSaveMgr::PlayerUnbindInstance(ObjectGuid guid, uint32 mapid, Difficulty difficulty, bool deleteFromDB, Player* player /*= nullptr*/)
{
       // ...
        InstanceSave* tmp = itr->second.save;
        w->m[difficulty].erase(itr);
        tmp->RemovePlayer(guid, this);
        return this->DeleteInstanceSaveIfNeeded(tmp->GetInstanceId(), false); // return true here to make sure we break all loops
    }
    return false;
}
```
