### ISSUE TITLE
Venture Co. Strip Miners Don't Melee Players Half The Time

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1096]
##### SMALL DESCRIPTION:
Venture Co. Strip Miners in Stranglethorn often don't run to the player when aggro'd. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When a Venture Co. Strip Miner is aggro'd, it throws dynamite and then runs to the player to melee them.

##### CURRENT BEHAVIOUR:
When a Venture Co. Strip Miner ( https://wowgaming.altervista.org/aowow/?npc=674 ) is aggro'd from a distance, they will do one of 3 things: 
1) Throw dynamite, and then resume their mining animation far from the player until the dynamite cooldown is finished.
2) Throw dynamite, and then move toward the player in a fragmented way, alternating stopping to mine and running until the player is reached. 
3) Run to the player and melee them. 

Maybe similar issue to https://github.com/azerothcore/azerothcore-wotlk/issues/540 ?

##### STEPS TO REPRODUCE THE PROBLEM:
1.  .go xyz -12981 -343 9 0
2.  Aggro a few Venture Co. Strip Miners.
3.  Try running away from them.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
50aace0e52218ec7aa97a2b592140b30b192c996

##### OPERATING SYSTEM:
Windows 10

**Comment by poszer** [comment]
Confirmed

**Comment by BarbzYHOOL** [comment]
look if TC has fixed it :P

**Comment by wetbrownsauce** [comment]
Just tested on a fresh compile of Trinity and a similar problem exists. Over there, the Strip Miners will run to the player to melee them as expected, however, as soon as they use their throw dynamite ability, they stop in place and never attempt to pursue the player just like here.

**Comment by BarbzYHOOL** [comment]
Ok, then it requires to modify the smart_ai in the database, probably a "good  first issue" to fix
