### ISSUE TITLE
/src/CFBG.cpp:338:9: fatal error: no member named 'GetTeamStartLoc' in 'Battleground'

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#10973]
### Current Behaviour

i used the newest azerothcore version,
when i build it , fatal error.
/src/CFBG.cpp:338:9: fatal error: no member named 'GetTeamStartLoc' in 'Battleground'

### Expected Blizzlike Behaviour

when update rebuild

### Steps to reproduce the problem

when update rebuild

### AC rev. hash/commit

/src/CFBG.cpp:338:9: fatal error: no member named 'GetTeamStartLoc' in 'Battleground'

### Operating system

ubuntu 21

**Comment by Nyeriah** [comment]
Please update your modules and try again.

**Comment by 5266869** [comment]
it was updated, it is the newest, it also cannot work
