### ISSUE TITLE
Quest “A Change of Heart ” “Choose Your Path” series issues

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#10986]
### Current Behaviour

“A Change of Heart ”  When you finish this quest,you can get a new ring instead the old one,but if you finish this quest in battle status,you can get the new one without lost the old one,so you can get two rings.The same  issue with “Choose Your Path” series quests.

### Expected Blizzlike Behaviour

When you finish the quest,you should lost the old one.

### Steps to reproduce the problem

1,Use a Mage and enter the Citadel,
2,Find NPC and get the quest,summon water elemental to attack the enemy far away,
3,Finish the quest when you are in battle status,
4,check the rings.   

### Extra Notes

I think this is because the ring can't be dismounted  in battle status.

### AC rev. hash/commit

5ed4db09e3c8

### Operating system

windows 10 x64

**Comment by SKingOWN** [comment]
Confirmed!
