### ISSUE TITLE
Hunter Pets Spell bonus not increasing?

### ISSUE THREAD

**Issue by Melanholyx** [azerothcore/azerothcore-wotlk#1098]
##### SMALL DESCRIPTION:
well when pet uses rabid and do auto attacks, pet melee attack power increasing 5% per hit stack up 5x times, but at this time pet Spell bonus not increasing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
i think when pet stacks his attack power while using rabid, spell bonus will be increasing aswell, cause spell bonus increasing according pet melee attack power.

##### CURRENT BEHAVIOUR:
atm spell bonus increasing when hunter attack power increasing for example with trinkets or aspect or pet spells : call of the wild and furious howl.

##### STEPS TO REPRODUCE THE PROBLEM:
1. just get any pet , with talented Rabid.
2. use Rabid and let pet do some melee attack to enemy,

##### BRANCH(ES):
master

AC HASH/COMMIT:
[50aace0](https://github.com/azerothcore/azerothcore-wotlk/commit/50aace0e52218ec7aa97a2b592140b30b192c996)

##### OPERATING SYSTEM:
Windows 10

**Comment by poszer** [comment]
False report. Actually it's working normally. Pet  AP is increasing, and seriously i don't know where you read that about Spell Bonus :thinking: 



![rabid](https://user-images.githubusercontent.com/41213210/49466276-ee356d00-f7ff-11e8-9a76-4f1912dbc88a.png)

**Comment by Melanholyx** [comment]
u get it wrong let me explain better before u say its invalid or wontfix,
FIRST SCREEN PET have  1621 Power and Spell bonus is +744
![wowscrnshot_120518_000026](https://user-images.githubusercontent.com/28813102/49469501-1e413800-f821-11e8-8285-d61ac97e5afc.jpg)
SECOND SCREEN I USED Trueshot aura + dragonhawk wich increased my AP and pet AP well.  so after pet ap increased spell bonus increased aswell right?(from +744 to +867) so it means spell bonus coming from pet AP
![wowscrnshot_120518_000034](https://user-images.githubusercontent.com/28813102/49469559-36b15280-f821-11e8-8c4e-8dffbd5acde6.jpg)
THIRD SCREEN  PET AP increased with rabid talent, SPELL BONUS STAYS to 867 and not increased isnot that bug? if pet spell bonus depends on pet power, then pet power increased after screen2 but spell bonus stays !
![wowscrnshot_120518_000052](https://user-images.githubusercontent.com/28813102/49469612-652f2d80-f821-11e8-8130-5c11df421315.jpg)

i think this is bug!

**Comment by poszer** [comment]
Still you re not right. Just find me any Video or the information text where it say that there will be Spell Bonus while having talent spend on Rabid. Also on these pictures, your AP is increased what talent provide, and that's okay. Have tested it already on other emu, there is nothing increased from this talent except Power!

**Comment by BarbzYHOOL** [comment]
if it's a hidden effect (which I doubt), it should be in the dbc

**Comment by BarbzYHOOL** [comment]
yeah i think it reads it from the dbc too

**Comment by BarbzYHOOL** [comment]
If you have proofs of validity, I'll reopen the issue.
