### ISSUE TITLE
Event after finishing quest "Alien Egg" is missing

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/azerothcore-wotlk#1099]
##### SMALL DESCRIPTION:
The event after finishing the quest "Alien Egg" is missing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After finishing the quest an egg should spawn, hatching a young Arikara. The creature then flies around, kills a dog and vanishes.

##### CURRENT BEHAVIOUR:
nothing happens

##### STEPS TO REPRODUCE THE PROBLEM:
- .quest remove 4821
- .quest add 4821
- .additem 12467
- .go creature id 10539
- finish quest

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
fc4b52b036a33f1207acca8c93a4c9ef3f9baa10

##### OPERATING SYSTEM:
Ubuntu 16.04

##### MODULES:
https://github.com/azerothcore/mod-vas-autobalance
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster

##### OTHER CUSTOMIZATIONS:
none

**Comment by BarbzYHOOL** [comment]
Prob any vanilla core has this fixed
