### ISSUE TITLE
Onyxia's visual bug

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#10998]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60
### Current Behaviour

Sadly i forgot take a screenshot during the battle, but happened on the two raids of my guild from last night. Basicly the visual bug was Onyxia doing a flying animation when she was on phase 1 and phase 3.

### Expected Blizzlike Behaviour

She should be with her claws over the ground attacking the tank without the flying animation from phase 2

### Steps to reproduce the problem
I was with my guild on Onyxia's Lair and when the tank pulled the boss, she started doing the animation like she was flying on phase 2.

### Extra Notes

Bug found by: Josarth.

### Triager notes: 
As Josarth explains it, Onyxia seems to hovering through the wall while being fought, making most of her claw attacks happen through the floor, I experienced the same issue while killing her this week, and also remember Guild Master and officers of my guild being scared she is going to stay stuck in the floor, being unable to be looted once killed.

### Video of the encounter and the issue from PTR:
https://streamable.com/c8b8tg

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Lynethris** [comment]
For more information, this bug comes when onyxia fly but through the Map. This often happens when a warrior charge. You can reproduce this with .GM fly on

**Comment by Dejanos** [comment]
> For more information, this bug comes when onyxia start to fly towards a player but through the Map. This often happens when a warrior charge. You can reproduce this with .GM fly on

She shouldn't be flying at all in phase 1 when this is occurring? It literally happens every time, and I engaged her with my paladin on PTR in melee range and she did the same as you can see in the video.
Have checked phase 1 from here: https://www.youtube.com/watch?v=yIdSGd0ykNA
