### ISSUE TITLE
Crash after the use command.

### ISSUE THREAD

**Issue by DevRival** [azerothcore/azerothcore-wotlk#110]
**Description**: Crash after the use command.

**Current behaviour**: When you use any command on a crash occurs.

**Steps to reproduce the problem**:

1. .mod run
2. .add

**Branch(es)**: 1.x 

**AC hash/commit**:  [2406235](https://github.com/azerothcore/azerothcore-wotlk/commit/24062354c16d0ae0ac4636a992eb751988ba06e2)

**Operating system**:   Windows 10

**Comment by Helias** [comment]
I can confirm, with the command .modify the core crashes.

Core rev: bf1a1b5cec9932b078782b81c67a9ea9e5496063

**Comment by ShinDarth** [comment]
same here with https://github.com/azerothcore/azerothcore-wotlk/commit/d641365b3b8e

also it appears it only crashes when using abbreviations (e.g. `.mod` instead of `.modify`)
