### ISSUE TITLE
 Darkmoon Card: Blue Dragon healing spellcast behavior 

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11026]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60
### Current Behaviour
![Blue Dragon](https://user-images.githubusercontent.com/100415626/158389705-4a3ce536-de93-4e2b-9054-416a65aafed2.png)

Darkmoon card blue dragon currently has a chance to proc on Glyph of Holy Light aoe heals, as well as Healing Over TIme spells and other Glyph heals, which is not Blizzlike, I go into more detail in TRIAGER NOTES. I suspect this also occurs on multi-target heals (I.e. Wild Growth/Prayer of Healing/Circle of Healing giving 5 chances to proc).

### Expected Blizzlike Behaviour

Darkmoon Card: Blue Dragon should only proc on the original spell cast and not on the effects which should not be considered as spellcasts.

### Source
https://www.wowhead.com/item=46051/meteorite-crystal Original WOTLK comments.

### Steps to reproduce the problem

Cast 100 heals as Holy Paladin with Holy Light + HL Glyph on 5 targets and see trinket proc way too often. Same for healing over time spells which should be 1 spellcast only.
### Extra Notes

Bug found by Hyperbearr.

### Triager notes:
I would like to add that I do think that bug reporter is wrong in this case, Beacon + target heal is supposed to each give a chance of 2% proc. 

![Meteorite Crystal](https://user-images.githubusercontent.com/100415626/158389769-76adaeb3-7141-47a9-9852-51f1727b7432.png)

I back up my argument with trinket Meteorite Crystal, which works on the same principle, or is also "Triggered by a spellcast", except that on each spellcast healer or caster get a buff for each spell, stacking up to 20, 1 for each spellcast. What it would do for Beaconed + healed target is double the buff stack amounts from +1 to +2, counting Beaconed target on each heal.  That behavior indeed got changed but with the first patch of Cataclysm, making this behavior Blizzlike throughout WOTLK. 

![meteorite](https://user-images.githubusercontent.com/100415626/158386522-86d02c76-0870-4140-a4b1-bc811cafaf23.jpg)

Upon testing from the comments from my test what is working as intended:

DRUID: All hots give only 1 proc on initial cast, HOTs do not give proc chance as intended (Did not test Lifebloom as we do not have that spell yet).

PRIEST: Glyph of Power Word: Shield does not give additional spellcast stacks on its 20% damage absorb shield on using the spell, Renew HOT does not give additional spellcast chance, Penance gives 3 stacks or spellcasts as intended. 

SHAMAN: Riptide HOT does not proc additional spellcast ticks as intended, Chain Heal gives 3 spellcast ticks as intended (4 with glyph), 

PALADIN: Beacon of Light when active gives one additional spellcast proc as intended when healing other targets.

### **What is NOT working as intended:** 

1. PALADIN: 
Each person healed with Glyph of Holy Light right now is registered as 1 spellcast, making initial 5 targets that stand nearby and are healed by Glyph AOE as 5 spellcasts, Beaconed target 6 and aditional Holy Light use as 7, meaning Glyph Proc is probably registered as a spell in the script behavior. 

Video: https://streamable.com/3b1n62

2. SHAMAN: 
Call of the Elements dropping all totems on the ground currently does not count anything as spellcast, opposed to Blizzlike behavior counting each totem dropped as 1 spellcast, 4 all together. It does not count any totem drops as spellcasts at all.

It does not count Earth Shield as a spellcast on use, but it does count each Earth Shield tick on healing the target as a spellcast, I am not sure if this is Blizzlike behavior, this can be related to why Nature's Swiftness buff was consumed on tank being healed by a tick of Earth Shield upon taking damage, it recognized it as a spellcast.

Video: https://streamable.com/13yefn

3. PRIEST: 
DISCLAIMER! I am not 100% sure on this one as I could not find Blizzlike source, but right now, Holy Nova when used as damaging AOE spell gives 1 spellcast for each target it damages, and 1 spellcast for each party or raid member it healed, making it insanely easy to proc Darkmoon Card: Blue Dragon when standing near 15-20 raid members or a lot of mobs to damage, in my opinion this is not Blizzlike behavior but I am not 100% sure.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Can you update the main issue with was is not working then? (and leave out everything that is working)

**Comment by neifion-00000000** [comment]
Blue Dragon research:  

2% flat chance, target # don't matter  

no icd, it can proc on itself if you're so lucky to have it happen, but amount of targets doesn't matter, casted on >25 targets 25 times in a row without a proc once, did same thing, got 3 procs on another occasion, certainly is not based on amount of targets that falls well outside the margin of error

**Comment by Contrubius** [comment]
> Blue Dragon research:
> 
> 2% flat chance, target # don't matter
> 
> no icd, it can proc over itself if you're so lucky to have it happen (single buff but it refreshes), but amount of targets doesn't matter, casted on >25 targets 25 times in a row without a proc once, did same thing, got 3 procs on another occasion (unsure total casts that time, about the same or maybe a few more), certainly is not based on amount of targets as that falls well outside the margin of error

I thought it's a well known fact 2% trinkets overall don't have a GCD because of their low proc rate.
Also, are you sure 25x25 is a good test that falls outside the margin of error? I did approx 1000 casts just to make sure. You can test the trinket with Meteorite Crystal, which is a WOTLK version with on use proc with the same spellcast effect as I stated before, or Pendant of the Violet Eye TBC trinket to confirm what exactly can or cannot proc the effect. To my understanding, both trinkets work differently in classic to how they used to in vanilla WOTLK.

**Comment by neifion-00000000** [comment]
I have the Blue Dragon trinket I am able to test it in wotlk, and yeah ~1000 chances would have yielded more procs if it was within the margin of error, the odds of it being 2% are effectively null.  There is a 99.99% chance it is within 0.673% of 0.3% if it was a proc-per-target and not proc-per-cast

**Comment by neifion-00000000** [comment]
(It would also be used in WOTLK now by shamans if it was that good, because their gearing objective is to make sure they can cast chain indefinitely as first priority, and this would prolly never stop being BIS because it would allow you to gear other slots with less mp5)

**Comment by Contrubius** [comment]
> (It would also be used in WOTLK now by shamans if it was that good, because their gearing objective is to make sure they can cast chain indefinitely as first priority, and this would prolly never stop being BIS because it would allow you to gear other slots with less mp5)

Why do Meteorite Crystal or Pendant of the Violet Eye grant a stack for each Chain Healed person, or Beaconed target + healed target for Hpala with the same trinket spellcast effect, tho?

I'm not gonna discuss resto sham playstyle tho, they are not chain heal bots.

**Comment by neifion-00000000** [comment]
why blizzard is inconsistent with mechanics is diving deeper into stuff I won't ever know the answer to, this specific case those trinkets were written xpacs apart.  Its very clear they had a lot of people writing a lot of things in a lot of different ways though the more data I gather trying to solve things.

**Comment by Contrubius** [comment]
> 

Ok, thanks for the reply.
