### ISSUE TITLE
Certain players' stats don't save when logged out.

### ISSUE THREAD

**Issue by youhuowa** [azerothcore/azerothcore-wotlk#11024]
### Current Behaviour

certain players' stats don't save when logged out. It seems that only Draenei or Blood Elf has this issue.
player stats only save when the time reached "PlayerSaveInterval = 60000" setting in the worldserver.conf

when the character login, the worldserver console pops up these error messages

AC> Character GUID Full: 0x0000000000000025 Type: Player Low: 37 has skill 150 that does not exist.
ActionButton loading problem, will be deleted from db...

AC> Character GUID Full: 0x0000000000000029 Type: Player Low: 41 has skill 150 that does not exist.
SQL(p): INSERT INTO character_skills (guid, skill, value, max) VALUES (41, 150, 1, 75)
 [ERROR]: [1062] Duplicate entry '41-150' for key 'character_skills.PRIMARY'

I tried to delete skill 150 in the character_skills in acore_charactor, 
the first log in and out is function properly, then it goes wrong again
I referred to the skillline_dbc in acore_world, it's empty there

### Expected Blizzlike Behaviour

player stats save property when logged out

### Steps to reproduce the problem

1. log into the game
2. move for a distance/buy an item
3. log out and log in again,
4. the character remains in the 1st place/the item disappears, sometimes some actionbar slots will be empty.

https://user-images.githubusercontent.com/101615180/158306801-cd31cef4-8bbb-4f62-9366-46146e60b618.mp4

### AC rev. hash/commit

AzerothCore rev. ab0822c6f653 2022-03-14

### Operating system

Windows 11 wsl Ubuntu20.04

### Custom changes or Modules

> List enable modules:
- mod-1v1-arena
- mod-ah-bot
- mod-congrats-on-level
- mod-custom-login
- mod-npc-all-mounts
- mod-npc-free-professions
- mod-reward-played-time
- mod-world-chat

no custom changes

**Comment by Bogir** [comment]
can't confirm

https://user-images.githubusercontent.com/25766571/158311540-503d3a4c-be44-4760-a1b8-0f6c55c7028a.mp4

**Comment by youhuowa** [comment]
figured it out
delete character spell 828 first then delete character skill 150
it's the modules "mod-npc-all-mounts" conf problem, should leave "AllMountsNPC.TeachBengalTiger = 0"
or he will teach your character spell 828 which requests skill 150,I suppose,referer to https://wotlk.evowow.com/?skill=150#spells
