### ISSUE TITLE
Items quests loot party

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#1105]
##### SMALL DESCRIPTION:
The quest items when we are in party with a companion, remain in the npc and can only be looteados by 1 of the members of the group.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It is hoped that they can be looteados, apparently there is a flag in the items that is the 2048. The problem is that they have to be filtered and studied item by item because they are not all loot party.

##### CURRENT BEHAVIOUR:
Example: https://www.wowhead.com/item=1129/ghoul-fang

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill an npc with a partner while partying.
2. Try to lootear both the item.

##### BRANCH(ES):

master

**Comment by poszer** [comment]
Just tested changes with 2 characters. It should be like this, right @pangolp  ?

![ovak](https://user-images.githubusercontent.com/41213210/49702708-acd7ff80-fbfb-11e8-9108-ca51db8dfbdb.png)

**Comment by pangolp** [comment]
That's right @poszer . There are items that only let one of the group grab, the other does not let him strip.

**Comment by poszer** [comment]
> You can check it, with the missions of the starting levels, like the one of the dranei. There we find the first error and then investigate and is problem of the flag.

Did you try to change flag? Doesn't work?

**Comment by pangolp** [comment]
Yes, if you change it works, but it's 5000 mission items and not all of them are to be grabbed in a group.

example:

```sql
SET @ITEM:=22889;
UPDATE `item_template` SET `Flags`=`Flags`|2048 WHERE `entry`=@ITEM;
```

**Comment by poszer** [comment]
> Yes, if you change it works, but it's 5000 mission items and not all of them are to be grabbed in a group.
> 
> example:
> 
> ```sql
> SET @ITEM:=22889;
> UPDATE `item_template` SET `Flags`=`Flags`|2048 WHERE `entry`=@ITEM;
> ```

Yeah, i understand. Do this, and tell me is your issue fixed with it 
[da845a4078f7a208db8611049a2a73855914482b](https://github.com/poszer/azerothcore-wotlk/commit/da845a4078f7a208db8611049a2a73855914482b)

**Comment by pangolp** [comment]
No, the mistake goes on. Putting the flag works, but the problem is that you have to check item by item.
[<a href="http://subefotos.com/ver/?4ef69b4daaa4e6af0d6d17aeacc093e5o.png" target="_blank"><img src="http://thumbs.subefotos.com/4ef69b4daaa4e6af0d6d17aeacc093e5o.jpg" /></a>](url)

**Comment by wetbrownsauce** [comment]
I used the following as a band-aid fix for my server

>UPDATE `item_template`
SET
`Flags` = `Flags` + 2048
WHERE (`class` = 12) AND (`Flags` < 2048) AND (`bonding` = 4);

that way it affects any item with class 12 (quest item) and bonding 4 (quest item). probably misses some stuff, but so far i've had no issues

**Comment by pangolp** [comment]
Run this query:

```sql
SELECT `entry`, `name`, `class`, `flags`, `bonding` FROM `item_template` WHERE `entry` IN (50380, 22889);
```

And it is likely that the solution you are talking about is the right one.
[<a href="http://subefotos.com/ver/?b4a812998044a1cf48bb6f7409d0e422o.png" target="_blank"><img src="http://thumbs.subefotos.com/b4a812998044a1cf48bb6f7409d0e422o.jpg" /></a>](url)

**Comment by pangolp** [comment]
```sql
UPDATE `item_template` 
SET `Flags` = `Flags` | 2048 
WHERE `class` = 12 AND `subclass` = 0 AND `bonding` = 4;
```

The only thing I'd change about the practice is:

1) + by |
2) remove `flags`<2048
Because you have quest items, whose flags are better at that value and that way the items didn't want fixed.

Change I'm thinking that it seems strange that in the last DB of trinity, they in the flags of items do not have in many cases the 2048. Could it be that they have applied a fix from the core?

**Comment by pangolp** [comment]
```sql
SELECT COUNT(`entry`) FROM `item_template`
WHERE `class` = 12 AND `subclass` = 0 AND `Flags` < 2048 AND `bonding` = 4;
```

If I make that query, it returns me that only 2510 items would be fixed. And I think there are many more.

If I make this query:

```sql
SELECT COUNT(`entry`) FROM `item_template`
WHERE `class` = 12 AND `subclass` = 0 AND `Flags` > 2048 AND `bonding` = 4;
```

It returns 376 unfixed items.

**Comment by wetbrownsauce** [comment]
> Because you have quest items, whose flags are better at that value and that way the items didn't want fixed.    

I'm not really sure what this means, sorry.   

I never said it was the right fix, it is a band-aid fix that intentionally targets quest items with flags < 2048 since majority of them fit the criteria, and only a few outliers remain. 

I imagine a core fix would be the proper fix unless there exists packet sniffs showing all quest items having flags >= 2048

**Comment by pangolp** [comment]
I use a translator to communicate, maybe a lot of words sound strange to you. But don't worry, I value your contribution very much, I hadn't noticed the `bonding` attribute. I think the solution could be this:

```sql
UPDATE `item_template`
SET
Flags` = `Flags` | 2048
WHERE `class` = 12 AND `subclass` = 0 AND `bonding` = 4;
```

**Comment by pangolp** [comment]
What he wants to put with that phrase is that if you use ``flags`<2048 many items would be excluded. That's 376.

**Comment by BarbzYHOOL** [comment]
@pangolp why closed if there is a fix included?

**Comment by pangolp** [comment]
Nose, I thought it had to be closed, since the problem was apparently solved with that SQL. At least I tried it on my server and for now I had no problems.

Todavía nunca subí modificaciones en SQL. Viste que me cuesta un poco el manejo de git aun.

**Comment by wetbrownsauce** [comment]
I've been running that modification on my server for a long time now. Loving it.

**Comment by FrancescoBorzi** [comment]
@pangolp just a general note: it's better to keep the issues open until the fix is on **master** branch

es mejor dejar los issues abiertos hasta que su corrección esté en master

**Comment by sucofog** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a49544cc187d3a156b4615907d6b82057364fcc4 ?

**Comment by pangolp** [comment]
@FrancescoBorzi If, now I understand it, it happens that since I am new in this, I closed the subject believing that we already had the solution. But from now on I will leave them open.

@sucofog If, now I understand it, it happens that since I am new in this, I closed the subject believing that we already had the solution. But from now on I will leave them open.

**Comment by FrancescoBorzi** [comment]
this is the blizzlike behaviour, only some special items are supposed to be shared (for example when there is only 1 available in 1 specific container).

**Comment by Kuiriel** [comment]
Hey, this is awesome. I'm really happy for the fix, it makes it far less grindy for the kids to play with us while still being able to experience the classic story (five people seeking 10 things each = 50+ kills gah). The modability of AzerothCore and the work of all you good folk makes me really happy - I can play this, but with tweaks now to manage moderation so it's not quite as life consuming as it used to be. Or so I tell myself. 

I've been testing it out and the updated quest drops do drop properly per person. They are in the bags. There was an interesting bug at the beginning though - the kids picked up a scorpid worker tail each, but the quest objectives on the right said '0/8 scorpid tails' only. It was listed correctly in the quest log though. Some time later it seems to be updating correctly in the objectives log.

Weirdly enough the quest back at the cave actually says they want you to turn in 10, not 8.

**Comment by Kuiriel** [comment]
I thought I wrote a post, it disappeared or was deleted..? Testing... if this works, will edit it with details.

**Comment by ZhengPeiRu21** [comment]
> _Hey, this is awesome. I'm really happy for the fix, it makes it far less grindy for the kids to play with us while still being able to experience the classic story (five people seeking 10 things each = 50+ kills gah). The modability of AzerothCore and the work of all you good folk makes me really happy - I can play this, but with tweaks now to manage moderation so it's not quite as life consuming as it used to be. Or so I tell myself._
> 
> I've been testing it out and the updated quest drops do drop properly per person. They are in the bags. There was an interesting possible collection of bugs at the beginning though -
> 
>     1. At first when the kids picked up a scorpid worker tail each, the quest objectives on the right still said '0/8 scorpid tails' only. It was listed correctly in the quest log though (1/8). Some time later it seems to be updating correctly in the objectives log.
> 
>     2. The starting quests in Durotar ask for 10 scorpid tails and 10 boars when you read the quest, but when you have it in the quest log or on objectives it asks for 8 only. Quest listed as complete when 8/8 but couldn't be handed in until 10/8. Cactus Apples were supposed to need only 6, but instead I'm up to 10 on that too. I think this is 'Classic' numbers required but the quest log is borked.
> 
> 
> The latter or both of these might be related to [mod-individual-progression]](https://github.com/ZhengPeiRu21/mod-individual-progression) though, I'mma just trying to be helpful in case someone notices the same for this here too because I was mighty glad about the SQL for quest drops.

1 is an AzerothCore issue of the quest log not always updating right away - I have notice this as well. I do not know if there is an open issue for it; you may want to open an issue for more discussion. I do not know if this delay is seen on official servers as well and client is just slow to update, but I guess we are sometimes missing sending an update packet.

2 is an Individual Progression issue. Quest requirements were updated to match Vanilla but descriptions sometimes were not updated to reflect the change. The required gameplay is correct and accurate to Vanilla but the text is wrong; please open an issue in the Individual Progression repo if you notice any of these and I will fix the descriptions.

**Comment by wetbrownsauce** [comment]
> I used the following as a band-aid fix for my server
> 
> > UPDATE `item_template`
> > SET
> > `Flags` = `Flags` + 2048
> > WHERE (`class` = 12) AND (`Flags` < 2048) AND (`bonding` = 4);
> 
> that way it affects any item with class 12 (quest item) and bonding 4 (quest item). probably misses some stuff, but so far i've had no issues

This is ancient, sorry for necro, but my above sql should instead look like this:

UPDATE `item_template`
SET
`Flags` = `Flags` + 2048
WHERE `class` = 12 AND `bonding` = 4 AND `Flags` & 2048 = 0;

The WHERE clause checks that the item class and bonding are of quest item, and the last part checks that the item flags do not already contain 2048. 

I use + 2048 in the SET instead of | 2048 because the WHERE clause already handles the necessary checks.

For anyone who stumbles upon this in the future, this sql statement should make all lootable quest items shared so that playing with friends doesn't require killing 2x, 3x, or 4x of every mob. Cheers.

**Comment by sudlud** [comment]
Using | 2048 ensures it's repeatable and you don't need to check the flags in the where clause

**Comment by pangolp** [comment]
I created a mod for this, you could develop the idea a little bit more, because it just encompasses an item model, but you could expand a lot more. https://github.com/pangolp/mod-quest-loot-party
