### ISSUE TITLE
Many creatures broken due to CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE requirement for scripted movement of creatures

### ISSUE THREAD

**Issue by SilentCLD** [azerothcore/azerothcore-wotlk#11057]
### Current Behaviour

As of PR #7008 any creature that should control its own movement in scripts (C++ or SAI) requires `CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE` (512) to be set in flags_extra on its template.
More specifically, if the creature does not have this flag then a SAI calling set fly will not work as movement flags are recalculated after this check: 
https://github.com/azerothcore/azerothcore-wotlk/blob/b01aa11f18034ee79484215a868d10594c6e18fe/src/server/game/Entities/Creature/Creature.cpp#L3222-L3224

Only 9 creatures have this flag set in creature_template (`SELECT * FROM creature_template WHERE flags_extra & 512`)

Here's some creatures I know of that are affected:
Nerub'ar Broodkeeper - 36725
The Lich King - 36597 (This has also been addressed in PR #10882)
Murg "Oldie" Muckjaw - 23340
Trope the Filth-Belcher - 23342
Corlok the Vet - 23344
Wing Commander Ichman - 23345
Wing Commander Mulverick - 23346
Captain Skyshatter - 23348

How should this be fixed?
- Should all affected creatures have this flag?
- Should scripts be setting fly/hover etc another way?
- Are the templates missing something to prevent this?
- What if the script only wants a temporary override over movement flags?

### Expected Blizzlike Behaviour

None

### Steps to reproduce the problem

The Dragonmaw Race quest line can be tested, specifically `Dragonmaw Race: The Ballad of Oldie McOld` (11064)
Even though SAI sets the fly flag the core will disable it on its next update cycle. This causes the npc to fall to the ground while trying to fly, making the quest near if not impossible to complete.

### AC rev. hash/commit

AzerothCore rev. e8d3292533c7

### Operating system

Windows 10

**Comment by UltraNix** [comment]
This is an intended behavior. If mob in on the groun, then it should not allowed be flying. Correct your SAI to use the flying action when it has to start fly (or provide proper `creature_template_movement` data).

**Comment by Kitzunu** [comment]
I think it is like nix said, need updating c_t_m for the creatures
