### ISSUE TITLE
[ICC][Lich king]Valkyries stunned with Jump

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#11050]
### Current Behaviour

IN P3:
When the Valkyries are stunned, it makes them Jump out of the stun in the position where they should be without being stunned

### Expected Blizzlike Behaviour

Valkyries are stunned without move anymore

### Steps to reproduce the problem

1.Go to Lich king and fight
2.IN P3 ,try to stun Valkyries

### Extra Notes

form https://github.com/azerothcore/azerothcore-wotlk/issues/10534

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/666aca2a633cd80af0a5588f68ae6576b6648581

### Operating system

Windows 10 x64

**Comment by Tony931023** [comment]
I reported this a while ago along with other errors found in LK 25H, it is in phase 2 of arthas, mainly when a tauren uses the racial or two players applied a stun on the same valkyrie, the stun only works well when it is applied by a rogue,

When leaving the stun, the valkyries jump to the position they would have in their journey if they had not been stunned.

**Comment by lionking404** [comment]
y en arthas 25h en la tercera face sale de la espada un espiritus enfurecido eso no deberia de pasar..

**Comment by lionking404** [comment]
As in lk 25h, in the third phase after going down 2 or 3 times to the sword an enraged spirit comes out from the same sword, that should not happen

**Comment by lyzdtc2** [comment]
Is there any way to fix it?

**Comment by sogladev** [comment]
These valkyr's act as vehicles that board players. Is wonder if this issue is only present when a valkyr picks up a player. Does a valkyr without a player update correctly? And a valkyr with a player does the teleport bug?
