### ISSUE TITLE
Porting from Maczuga/SunwellCore

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#11069]
I didn't check recently it but I am saving the list of possible TODOs from https://github.com/azerothcore/azerothcore-wotlk/issues/1141

- [ ] https://github.com/Maczuga/SunwellCore/commit/9fb7429c4310c218a0adbdda45b174ff2db9eb11 Note: with this commit, you will see a buggy hp in princes in ICC so take care
- [ ] https://github.com/Maczuga/SunwellCore/commit/5d9826cac236af7f4601e55f4b10e666fc2f8ebb
- [ ] https://github.com/Maczuga/SunwellCore/commit/fb94e1d061b58f74ada40aacc545ba9042caccfb
- [ ] https://github.com/Maczuga/SunwellCore/commit/fffefd59fa278b52a1a427479ba0a83024678356
- [ ] https://github.com/Maczuga/SunwellCore/commit/b00da9c95ccbd5b8edb5d0c4b9a854c062ff7b7e
- [ ] https://github.com/Maczuga/SunwellCore/commit/0f9366b9bfbc73985faa397fe16fe982bb0dc2f2
- [ ] https://github.com/Maczuga/SunwellCore/commit/4cab5e60703d261357e48bd4929d6687cc51701c
- [ ] https://github.com/Maczuga/SunwellCore/commit/5eb4ca77d18de30048541273a68dee4e2af2717b
- [ ] https://github.com/Maczuga/SunwellCore/commit/4e308b87c7a6b09adb27bf00e0d8615302dca4b7
- [ ] https://github.com/Maczuga/SunwellCore/commit/998d1e6448641b6f0fb1da512c567558572010dc
- [ ] https://github.com/Maczuga/SunwellCore/commit/afb89cb7c99fcd90c1fe4bf23f7b57395c8397e2
- [ ] https://github.com/Maczuga/SunwellCore/commit/31a60fdaab1eb4502821fd0dcf6d15bbf11e600e
- [ ] https://github.com/Maczuga/SunwellCore/commit/8c11d41e56704f1ad8522cef1b0af2093f342463
- [ ] https://github.com/Maczuga/SunwellCore/commit/065336c79c94411520ac9ee908f59dd7fdbbaf3d
- [ ] https://github.com/Maczuga/SunwellCore/commit/ef25174df07d7fa282e5aaa6e79ee8c0bc0d819e

**Comment by Kitzunu** [comment]
Closing as there is no reason to cherrypick random stuff from sunwell, also one of those is already a module irrc
