### ISSUE TITLE
[BWL] Chromaggus Time Lapse should half threat and restore threat on time lapse expire

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11060]
### Current Behaviour

Currently it does not reduce threat or restore it.

### Expected Blizzlike Behaviour

![image](https://user-images.githubusercontent.com/20357406/158763412-636e2837-c6d2-40c7-9c3c-79f7916c5c64.png)

### Source

https://classic.wowhead.com/guides/chromaggus-blackwing-lair-strategy

### Steps to reproduce the problem

.go c 84639 

### Extra Notes

84639 84648 84650

### AC rev. hash/commit

b01aa11f1803

### Operating system

Ubuntu

### Custom changes or Modules

mod-anticheat (master)  (conf disabled)
mod-autobalance (master)
mod-bg-item-reward (master)
mod-cfbg (master)
mod-cta-switch (master
mod-chromiexp (master)
mod-chromiecraft (master)
mod-desertion-warnings (master)
mod-duel-reset (master)
mod-eluna-lua-engine (master)
mod-ip-tracker (master)
mod-low-level-arena (master)
mod-multi-client-check (master)
mod-progression-system (master)
mod-pvp-titles (master)
mod-pvpstats-announcer (master)
mod-queue-list-cache (master) 
mod-rdf-expansion (master) 
mod-save-inventory (master)
mod-server-auto-shutdown (master)
mod-spellsystem-extended (master)
Acore_eventScripts (master)
Acore_SendAndBind (master)
Acore_TempAnnouncements (master)
Acore_ZoneDebuff (master)

**Comment by UltraNix** [comment]
@temperrr 
```
Time Lapse : Bronze - Stun for 6 seconds, reduces maximum health points to half. This ability used to permanently reduce threat, but does not do so as of patch 2.0.1
```
Should we restore it? Maybe on progression_module?

**Comment by UltraNix** [comment]
@temperrr 
`
Time Lapse : Bronze - Stun for 6 seconds, reduces maximum health points to half. This ability used to permanently reduce threat, but does not do so as of patch 2.0.1
`
Restore it on progression module?
