### ISSUE TITLE
Restore zeppelin

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#11071]
This is related to https://github.com/azerothcore/azerothcore-wotlk/issues/1141

- [ ] https://github.com/Falstring/Dalaran-Core/blob/3605a709de0b6b73c05dcb0bd2eb772d7b0bcf86/src/server/scripts/World/zeppelins.cpp  Zeppelins - Related to this PR https://github.com/azerothcore/azerothcore-wotlk/pull/907 () removed gossip menu options 1969 and 1971  - need to put them back with missing zeppelin master gossip menus)

**Comment by Kitzunu** [comment]
Closing as we can't use leaked code
