### ISSUE TITLE
Inner Fire (id:10952) buff tooltip

### ISSUE THREAD

**Issue by ficsko47** [azerothcore/azerothcore-wotlk#11074]
### Current Behaviour

The spell itself is working as intended, buff tooltip (left to minimap) shows wrong value after learning Improved Inner Fire talent (id:14771) and Glyph of Inner Fire (id:42402), says 1395 (rank 6 base value) before and after taking the talent/glyph. The numbers inside character info and spell tooltip are correct.

### Expected Blizzlike Behaviour

Buff tooltip should show correct values after taking the talent/glyph
![Screenshot 2022-03-18 190650](https://user-images.githubusercontent.com/101889186/159059121-acf4c982-6044-40cf-8ff2-50995658cbb4.jpg)
![Screenshot 2022-03-18 190731](https://user-images.githubusercontent.com/101889186/159059217-b8652976-411a-445d-9966-bd47229d97c9.jpg)

### Steps to reproduce the problem

1. Learn rank 6 Inner Fire
2. Learn Glyph of Inner Fire
3. Compare number in character info with buff tooltip

### Extra Notes

Not a game breaking bug I guess

### AC rev. hash/commit

[19:16:53] AzerothCore rev. e8d3292533c7 2022-03-16 01:18:36 +0000 (master branch) (Unix, RelWithDebInfo, Static)
[19:16:53] Connected players: 491. Characters in world: 416.
[19:16:53] Connection peak: 616.
[19:16:53] Server uptime: 2 day(s) 6 hour(s) 52 minute(s) 4 second(s)
[19:16:53] Update time diff: 23ms, average: 11ms.

### Operating system

Windows 10 x64

**Comment by Nyeriah** [comment]
Tooltips are hardcoded in the client and don't change according to talents
