### ISSUE TITLE
Karazhan - Prince Malchezaar's Amplify Damage applies to too many targets

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1108]
##### SMALL DESCRIPTION:
Amplify Damage should be applied to one random target every time it is cast, it currently applies to multiple.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
In phase 3, Prince Malchezaar repeatedly uses Amplify Damage throughout the fight, which applies to a single random target. 

##### CURRENT BEHAVIOUR:
[Amplify Damage](https://wowgaming.altervista.org/aowow/?spell=39095) in phase 3 is applied to all players when used. 

##### STEPS TO REPRODUCE THE PROBLEM:
Method A:
1. Engage Prince Malchezaar with 2+ players
2. In phase 3 Amplify Damage will be repeatedly applied to all players

Method B:
1.  .learn 39095
2.  go to area populated with mobs
3.  target one mob and cast Amplify Damage, all mobs in 100yards will be debuffed

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
8906d1ea26659484617620b6b61e50f2ff41315d

##### OPERATING SYSTEM:
Windows 10

**Comment by wetbrownsauce** [comment]
So I got this working properly, but I'm not too good with c++ so I don't know if this is acceptable, input would be great.  

old:
```
            if (phase == 3)
            {
                if (AmplifyDamageTimer <= diff)
                {
                    Unit* target = NULL;
                    target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);

                    if (target)
                    {
                        DoCast(target, SPELL_AMPLIFY_DAMAGE);
                        AmplifyDamageTimer = urand(20000, 30000);
                    }
                }
                else
                    AmplifyDamageTimer -= diff;
            }
```

Change DoCast to AddAura:
```
            if (phase == 3)
            {
                if (AmplifyDamageTimer <= diff)
                {
                    Unit* target = NULL;
                    target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);

                    if (target)
                    {
                        target->AddAura(SPELL_AMPLIFY_DAMAGE, target);
                        AmplifyDamageTimer = urand(20000, 30000);
                    }
                }
                else
                    AmplifyDamageTimer -= diff;
            }
```

When using DoCast, amplify damage applies to all targets in a 100 yard range, but it should only apply to one target chosen at random by the boss. AddAura applies it only to his chosen target. Is there a better/cleaner way to do this?

**Comment by wetbrownsauce** [comment]
Tested further. 

-Amplify Damage cannot be reflected before or after the above change.
-Amplify Damage can be avoided/removed with immunities like Divine Protection before and after the above change.

Minor bug:
-Due to the aura being applied and not cast, the small visual effect around the target on application (similar to a mage's amplify magic spell effect) does not show visually.

**Comment by talamortis** [comment]
Will take a look at the issue after the new year.

**Comment by wetbrownsauce** [comment]
Prior to adding the change, amplify damage cannot be spell reflected anyway
