### ISSUE TITLE
Crash after the use command.

### ISSUE THREAD

**Issue by Draztal** [azerothcore/azerothcore-wotlk#111]
Description: Crash after the use command.

Current behaviour: When you use any command on a crash occurs.

Steps to reproduce the problem:

    .commands

Branch(es): 1.x

Operating system:  Ubuntu 15.04 (GNU/Linux 2.6.32-042stab116.2 x86_64)

**Comment by DevRival** [comment]
Confirm. @ShinDarth Why do you have upgraded the chat system?

**Comment by Yehonal** [comment]
New chat system is cross-platform reliable since it uses c++11 vectors instead of old malloc

It allows to compile with clang on linux too

**Comment by Yehonal** [comment]
However it should be solved with https://github.com/azerothcore/azerothcore-wotlk/commit/edd5f4a19267b55fe015150d653969f46ecd50a4

Could you test it please?

**Comment by ShinDarth** [comment]
@Draztal this issue has been already resolved, please update your core.

Also, please include your core revision hash (example: https://github.com/azerothcore/azerothcore-wotlk/commit/edd5f4a19267b55fe015150d653969f46ecd50a4) when opening an issue

**Comment by DevRival** [comment]
@ShinDarth сrash with .mod and .add a corrected, but there was another.

**Comment by DevRival** [comment]
.commands crash core.

**Comment by ShinDarth** [comment]
ok I can confirm that:

it happens only in game (it does not crash on console)

**Comment by DevRival** [comment]
I could not check everything. I think simply the error output to the chat command information.
