### ISSUE TITLE
Mekgineer's Chopper[Bug]

### ISSUE THREAD

**Issue by Friwa28** [azerothcore/azerothcore-wotlk#11108]
### Current Behaviour

When a player in a group sits on  Mekgineer's Chopper then he shows that he is sitting in the cradle. And for another player, this character stands still. 
translate.google.ru 

### Expected Blizzlike Behaviour

Must be in sync

### Steps to reproduce the problem

Create 2 Accounts. 1 account to summon a Mekgineer's Choppe 2 accounts to get into a Mekgineer's Choppe

### AC rev. hash/commit

Last dev

### Operating system

Debian 11

### Custom changes or Modules

no

**Comment by Kitzunu** [comment]
Add a valid hash/commit that you use, dont just say latest. run the server debug command

**Comment by Friwa28** [comment]
Add
