### ISSUE TITLE
Console Commands are failing with the wrong text.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#1110]
SMALL DESCRIPTION:
Many console commands are producing the following text. How did this get broken in the past year? It used to work as intended not too long ago.

```
AC>.character erase
[DEPRECATED]: use ".list gobject" instead.
Syntax: .go object #object_guid
Teleport your character to gameobject with guid #object_guid
```

EXPECTED BLIZZLIKE BEHAVIOUR:
These commands should either produce a "Command not found" or the actual comamand's help reference text.

STEPS TO REPRODUCE THE PROBLEM:
At the AC console or in the game try to use various commands and the text will appear on MANY of them.

BRANCH(ES):
master

AC HASH/COMMIT:
d55c44c

OPERATING SYSTEM:
Windows 7/10

MODULES:
None

OTHER CUSTOMIZATIONS:
None

**Comment by BarbzYHOOL** [comment]
wtf, this is related to this apparently: https://github.com/azerothcore/azerothcore-wotlk/commit/e8aff9feac0fdcce5591b9c6e5e1eb1f77d57bc7

**Comment by StygianTheBest** [comment]
This was caused by bad data in an earlier commit. It has been resolved.
