### ISSUE TITLE
[ICC]Change H mode issue

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#11118]
### Current Behaviour

Teamleader can't change normal mode to H mode while a teammate hasn't complete ICC in normal mode.

### Expected Blizzlike Behaviour

If the teamleader had complete ICC in normal mode before,he can change to H mode or change back to normal mode,even with teammates never complete the ICC. 

### Steps to reproduce the problem

1

### AC rev. hash/commit

9f4f824336de

### Operating system

windows 10 x64

**Comment by Bogir** [comment]
no one was inside the IСС at that moment ?

**Comment by fullofstarschen** [comment]
I mean both of them are in the ICC and the leader can change the mode.

**Comment by Bogir** [comment]
I get this error in console whei I'm in
![изображение](https://user-images.githubusercontent.com/25766571/159851921-86c90a7d-182c-4bdd-9c77-2109baef1fe9.png)

**Comment by Winfidonarleyan** [comment]
As far as I know, you can't change the difficulty level if someone is inside

**Comment by fullofstarschen** [comment]
> As far as I know, you can't change the difficulty level if someone is inside

Only ICC can do this,and another special case you may have noticed that the nomal mode has the same ID as H mode in ICC.

**Comment by Nyeriah** [comment]
The last time I researched about ICC's dynamic mode, I was told that was something implemented during cataclysm prepatch, and you can't/shouldn't be able to switch difficulties with players inside/it should follow the same rule as all others, except the cooldowns are indeed shared

**Comment by fullofstarschen** [comment]
For some reasons, the WOW version lags behind others in my countries. When we change from TBC to WLK, other countries have  CTM prepatch already. Yes,ICC's dynamic mode, that's what we got from the first.
