### ISSUE TITLE
Stuck mobs

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#1112]
and to many.
https://i5.imageban.ru/out/2018/12/12/618a203d24ac3dabef903b7aa5cbab04.jpg
https://i5.imageban.ru/out/2018/12/12/8b248075e803f50eae68472e72a5b049.jpg
https://i2.imageban.ru/out/2018/12/12/a726213c5cdeff54c7ed6d44a90dc233.jpg
https://i6.imageban.ru/out/2018/12/12/1e57ae3e38fe44d2a9e241b0a1532c25.jpg
https://i3.imageban.ru/out/2018/12/12/5ccecb462f0ce7eec6052cdb7d891774.jpg
https://i2.imageban.ru/out/2018/12/12/e178d376bfa9d32fa2c01b19106c235e.jpg
https://i3.imageban.ru/out/2018/12/12/4e8540ef8fa51a15e2ad32a74b59b272.jpg
https://i6.imageban.ru/out/2018/12/12/7687a31b33f18d6e760b76052c0628ca.jpg

**Comment by poszer** [comment]
Use template while reporting issue.

**Comment by BarbzYHOOL** [comment]
Please, open a valid issue, it's very hard for us to deal with your screenshots.

**Comment by poszer** [comment]
Confirmed. Wrongly spawned, too much of them, and also they re stucked. (Low respawn time 2m)
Deleting them from the base is the correct fix.
Thanks for reporting @Falstring 
P.s Also next time fill template please, it's hard without details to reproduce this.

**Comment by Falstring** [comment]
> Confirmed. Wrongly spawned, too much of them, and also they re stucked. (Low respawn time 2m)
> Deleting them from the base is the correct fix.
> Thanks for reporting @Falstring
> P.s Also next time fill template please, it's hard without details to reproduce this.

I think you tagged the wrong person. :D @poszer

**Comment by poszer** [comment]
> > Confirmed. Wrongly spawned, too much of them, and also they re stucked. (Low respawn time 2m)
> > Deleting them from the base is the correct fix.
> > Thanks for reporting @Falstring
> > P.s Also next time fill template please, it's hard without details to reproduce this.
> 
> I think you tagged the wrong person. :D @poszer

Yes :rofl:
