### ISSUE TITLE
Rogue - Deadly Poison damage tick reset on refresh

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#11126]
### What client do you play on?
https://github.com/chromiecraft/chromiecraft/issues/3237
enGB

### Faction

- [ ] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Deadly Poison, the rogue-exclusive weapon enhancement, when used on a weapon, causes the rogue to apply a debuff on an enemy when attacking with that weapon, which deals damage every 3 seconds. The debuff can stack up to 5 times.

Whenever the debuff is applied and/or refreshed, it takes 3 seconds for Deadly Poison to deal damage. Deadly Poison could, in theory, deal no damage at all because the rogue could refresh the debuff too quickly.

### Expected Blizzlike Behaviour

Deadly Poison is supposed to deal damage every 3 seconds. Reapplying Deadly Poison should not prevent its damage from ticking.

### Source

wotlk video proof
https://www.youtube.com/watch?v=rJi7E_-HQOQ
https://www.youtube.com/watch?v=t5ztnfMFpCI
https://www.youtube.com/watch?v=Ggi5LePCEvo
in every video you will clearly see deadly poison tick roughly every 3 seconds thanks to MSBT damage text addon

### Steps to reproduce the problem

Create Rogue character
Learn dagger skill
.maxskill
.add 5549 2
.add 2892 2
Attack dummy and see 0 deadly poison damage done

### Extra Notes

This makes rogue much weaker than intended.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccb6d3e5a1401df8c9e99a384b9a5eead62441a1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Algorak** [comment]
Same goes for the snake bite from the hunter I think! All spells that are refreshed by spells have the problem.
