### ISSUE TITLE
Glyphic scroll/memorandum/letter/rune/tablet all have the same text

### ISSUE THREAD

**Issue by Psaliet** [azerothcore/azerothcore-wotlk#11143]
The glyphic race-based item given to starting mages of respective races is bugged. Regardless of which item it is, be it glyphic scroll or glyphic memorandum or otherwise, they all have the same text: to go and speak to marrek nurrybit, the gnome mage trainer.

**Comment by Winfidonarleyan** [comment]
?

**Comment by Psaliet** [comment]
Make a new mage of any race, then accept the quest to talk to the mage trainer. The quest involves receiving a glyphic item which must be turned in to the trainer. That item has text which should be unique to every race. Instead, the text for every race is the same, and is the text that belongs to gnome mages only. That is the bug.

**Comment by Kitzunu** [comment]
Dont ignore the issue template, open a new issue and fill it in properly

**Comment by Psaliet** [comment]
I’m sorry. I’ll do as you have said
