### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by Madera95** [azerothcore/azerothcore-wotlk#11155]
### Current Behaviour

Debian 10
CMake-Version: 3.21.0
Clang-Version: 15.0.0

Compile-Command: cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1

Console-Output: https://pastebin.com/86mnnCJa
CMakeError-Log: https://pastebin.com/Yegb5jG7

### Expected Blizzlike Behaviour

No direct error in the game

### Steps to reproduce the problem

Root reinstalled several times & started the compile with different versions

### AC rev. hash/commit

Newest

### Operating system

Debian 10

**Comment by Tony931023** [comment]
what is the hash/commit you are using?

**Comment by Madera95** [comment]
I did the compile 5 minutes before creating it with the latest AC.

**Comment by Tony931023** [comment]
It could be that it is giving some batting with debian (if I remember correctly some dependencies change with respect to ubuntu), because in ubuntu 20.04 it compiles perfectly

**Comment by Kitzunu** [comment]
Add commit/hash, dont just say latest.

And we dont support Clang 15 https://github.com/azerothcore/azerothcore-wotlk/security/policy
