### ISSUE TITLE
About lambda error handling: addqueryholdercallback (characterdatabase. Delayqueryholder (holder))

### ISSUE THREAD

**Issue by hahalmtdhl** [azerothcore/azerothcore-wotlk#11158]
The purpose is to simulate players logging in to the game, It was normal until it was updated: #5611

Through breakpoint debugging, I can get the account and password normally, but the new lambad callback doesn't work properly

Thank you in advance for your help! I wish you all the best!

Below is my code:

`
bool FakeBot::FakePlayerLogin()
{
    SessionMap const& Sessions = sWorld->GetAllSessions(); 
    for (auto const& AccountMap : m_AllAccount) 
    {
        uint32 AccountId = AccountMap.first;
        if (Sessions.find(AccountId) != Sessions.end())
          continue;            

        if (m_BotAccount[AccountId].size() < AccountMax)
        {
            for (auto const& PlayerGuid : AccountMap.second)
            {

                ObjectGuid PGUID = ObjectGuid(HighGuid::Player, PlayerGuid);

                Player* FakeBot = ObjectAccessor::FindPlayer(PGUID);

                if (FakeBot && FakeBot->IsInWorld())
                    continue;

                auto const itr = m_BotPlayers.find(PlayerGuid);
                if (itr != m_BotPlayers.end())
                    continue;

                WorldSession* FakerSession = new WorldSession(AccountId, "", nullptr, SEC_PLAYER, 2, time(NULL), LOCALE_zhCN, 0, false, true, 0);
                if (!FakerSession)
                {
                    delete FakerSession;
                    continue;
                }

                FakerSession->SetplayerLoading(true);
               
                std::shared_ptr<LoginQueryHolder> holder = std::make_shared<LoginQueryHolder>(AccountId, PGUID);

                if (!holder->Initialize())
                {
                    FakerSession->SetplayerLoading(false);
                    continue;
                }

                //The new version is handled, but he has some problems
                FakerSession->AddQueryHolderCallback(CharacterDatabase.DelayQueryHolder(holder)).AfterComplete([FakerSession](SQLQueryHolderBase const& holder)
                {
                        FakerSession->HandlePlayerLoginFromDB(static_cast<LoginQueryHolder const&>(holder));
                });

                //Handling of old versions
                //LoginQueryHolder* holder = new LoginQueryHolder(AccountId, PGUID);
                //if (!holder->Initialize())
                //{
                //    delete holder;
                //    FakerSession->SetplayerLoading(false);
                //    continue;
                //}

                //auto NowLoginCallback = CharacterDatabase.DelayQueryHolder((CharacterDatabaseQueryHolder const&)(Holder));
                //CharacterDatabaseQueryHolder* ParamHolder;
                //NowLoginCallback.get(ParamHolder);
                //FakerSession->HandlePlayerLoginFromDB((LoginQueryHolder&)ParamHolder);

                Player* GameBot = FakerSession->GetPlayer();
                if (!GameBot)
                {
                     LOG_ERROR("Custom Tab","Fakeer << Guid: %u AccId: %u LoadError", PlayerGuid, AccountId);
                    FakerSession->LogoutPlayer(false);
                    delete FakerSession;
                    continue;
                }
                return true;
            }
        }
    }

    return false;
}`

**Comment by hahalmtdhl** [comment]
> 目的是模拟玩家登录游戏，在更新之前是正常的：[更新](https://github.com/azerothcore/azerothcore-wotlk/pull/5611)
> 
> 通过断点调试，可以正常获取账号和密码，但是新的lambad回调不能正常工作
> 
> 预先感谢您的帮助！祝你一切顺利！
> 
> 下面是我的代码：
> 
> ` bool FakeBot::FakePlayerLogin() { SessionMap const& Sessions = sWorld->GetAllSessions(); for (auto const& AccountMap : m_AllAccount) { uint32 AccountId = AccountMap.first; if (Sessions.find(AccountId) != Sessions.end()) 继续；
> 
> ```
>     if (m_BotAccount[AccountId].size() < AccountMax)
>     {
>         for (auto const& PlayerGuid : AccountMap.second)
>         {
> 
>             ObjectGuid PGUID = ObjectGuid(HighGuid::Player, PlayerGuid);
> 
>             Player* FakeBot = ObjectAccessor::FindPlayer(PGUID);
> 
>             if (FakeBot && FakeBot->IsInWorld())
>                 continue;
> 
>             auto const itr = m_BotPlayers.find(PlayerGuid);
>             if (itr != m_BotPlayers.end())
>                 continue;
> 
>             WorldSession* FakerSession = new WorldSession(AccountId, "", nullptr, SEC_PLAYER, 2, time(NULL), LOCALE_zhCN, 0, false, true, 0);
>             if (!FakerSession)
>             {
>                 delete FakerSession;
>                 continue;
>             }
> 
>             FakerSession->SetplayerLoading(true);
>            
>             std::shared_ptr<LoginQueryHolder> holder = std::make_shared<LoginQueryHolder>(AccountId, PGUID);
> 
>             if (!holder->Initialize())
>             {
>                 FakerSession->SetplayerLoading(false);
>                 continue;
>             }
> 
>             //The new version is handled, but he has some problems
>             FakerSession->AddQueryHolderCallback(CharacterDatabase.DelayQueryHolder(holder)).AfterComplete([FakerSession](SQLQueryHolderBase const& holder)
>             {
>                     FakerSession->HandlePlayerLoginFromDB(static_cast<LoginQueryHolder const&>(holder));
>             });
> 
> 
>             //Handling of old versions
>             //LoginQueryHolder* holder = new LoginQueryHolder(AccountId, PGUID);
>             //if (!holder->Initialize())
>             //{
>             //    delete holder;
>             //    FakerSession->SetplayerLoading(false);
>             //    continue;
>             //}
> 
>             //auto NowLoginCallback = CharacterDatabase.DelayQueryHolder((CharacterDatabaseQueryHolder const&)(Holder));
>             //CharacterDatabaseQueryHolder* ParamHolder;
>             //NowLoginCallback.get(ParamHolder);
>             //FakerSession->HandlePlayerLoginFromDB((LoginQueryHolder&)ParamHolder);
> 
>             Player* GameBot = FakerSession->GetPlayer();
>             if (!GameBot)
>             {
>                  LOG_ERROR("Custom Tab","Fakeer << Guid: %u AccId: %u LoadError", PlayerGuid, AccountId);
>                 FakerSession->LogoutPlayer(false);
>                 delete FakerSession;
>                 continue;
>             }
>             return true;
>         }
>     }
> }
> 
> return false;
> ```
> 
> }`

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/160248557-cb7d7a30-356b-4117-8cb5-f2e9bfec5b72.png)

**Comment by hahalmtdhl** [comment]
> ![изображение](https://user-images.githubusercontent.com/25766571/160248557-cb7d7a30-356b-4117-8cb5-f2e9bfec5b72.png)
> 
> the methods you need have not changed much

You're great. Can you tell me what to do?

**Comment by hahalmtdhl** [comment]
I don't know what to do anymore

**Comment by Kitzunu** [comment]
Do not ignore the issue template. Reopen a new issue and follow the template.
