### ISSUE TITLE
Passenger Bug on Mounts 

### ISSUE THREAD

**Issue by Bmtcoder** [azerothcore/azerothcore-wotlk#11159]
### Current Behaviour

Hello Guys
i am not professional in using github 
i am using last version of azerothcore 3.3.5 , there is a bug on passenger sloted mounts like :
Travelers Tundra Mammoth or engineering motors.
when second player  jumps into Motor or mammoth  (as passenger) , in driver (Mount owner rider) wow client, it dosent appear and visible on the mount. (doesnt look like he is in the vehicle)
when passenger ejecting , it make refresh on driver (Mount owner rider) wow client.
also when driver make ejects repair npc (Travelers Tundra Mammoth) , the status of slot dosent refresh (under mini map)
if you have free time , please check this bug

### Expected Blizzlike Behaviour

real time refresh

### Steps to reproduce the problem

1- learn  a passenger style mount traveler's tundra mammoth or engineering motors
2-client 1 cast as driver
3-client 2 jumpup as passenger
4-check mount owner client (there is no passenger on mount)

### AC rev. hash/commit

[#11136](https://github.com/azerothcore/azerothcore-wotlk/pull/11136)

### Operating system

Windows 10

### Custom changes or Modules

-

**Comment by NoM0Re** [comment]
Hey,
I can confirm the problem.
The Passenger client is in it, but for the driver client the passenger is just standing there and it doesnt look like he is in the vehicle.
Tested on https://github.com/azerothcore/azerothcore-wotlk/pull/11136
(Please add to ur Issue)

**Comment by Kitzunu** [comment]
Add hash/commit dont just write latest. Otherwise, it will be closed.

Also when confirming it is very helpful if you share the hash/commit you are on.

**Comment by acidmanifesto** [comment]
i am really sorry, i am trying to read and understand the initial post from the topic creator and I seriously can not understand what is being said or described,

**Comment by Kitzunu** [comment]
@acidmanifesto I think that if you are on Traveling Tundra Mamoth and a player in your party hops on it the "owner" of the mount doesn't see that player on the mount.

**Comment by Bmtcoder** [comment]
> @acidmanifesto I think that if you are on Traveling Tundra Mamoth and a player in your party hops on it the "owner" of the mount doesn't see that player on the mount.

sorry for my english.
yes ,  also when ejecting repair/shop npc , slot status of mount (under mini map) doesn't show as free slot .
also same story on in engineering motor mounts (Mechano-Hog / Mekgineer's Chopper)

**Comment by smellbee** [comment]
confirmed,   any news on this?

**Comment by ChibaPet** [comment]
Exists in TrinityCore too: https://github.com/TrinityCore/TrinityCore/issues/20136

**Comment by smellbee** [comment]
> Exists in TrinityCore too: [TrinityCore/TrinityCore#20136](https://github.com/TrinityCore/TrinityCore/issues/20136)

maybe sunwell core fixed it.
 I remember in 2020, this bug doesn't exist, but later commit (I can't find which) breaks it

**Comment by heyitsbench** [comment]
The UI element for the mount is kind of odd. With the traveler's tundra mammoth, ejecting the mounted vendor passengers through the UI will eject the passengers, and you won't be able to eject them again, but their spot on the UI is still filled in yellow, where it should become grey. Walking out of an instance with no vendors also doesn't show the UI element at all when you come out. For the record, I am comparing my observations to the Classic PTR.

**Comment by howdya** [comment]
This issue still exist on the last updated version.

**Comment by wefgame** [comment]
This issue still exist on the last updated version.

**Comment by ikkj** [comment]
The problem still exists

**Comment by Nyeriah** [comment]
Thanks for the confirmation, however, being open is already a good indication that the issue persists most of the time

**Comment by sogladev** [comment]
[Comparing to TC335](https://github.com/TrinityCore/TrinityCore/blob/b5ebf0281d471801b983b753f8f635271d4cffc6/src/server/game/Handlers/MovementHandler.cpp#L712) on ACore `MSG_MOVE_ROOT` packets are sent. Removing these lines fixes the above issue plus some others related to vehicles. I've linked some clips to illustrate
```
diff --git a/src/server/game/Handlers/MovementHandler.cpp b/src/server/game/Handlers/MovementHandler.cpp
index ef7560e76..a87a7eea8 100644
--- a/src/server/game/Handlers/MovementHandler.cpp
+++ b/src/server/game/Handlers/MovementHandler.cpp
@@ -987,6 +987,2 @@ void WorldSession::HandleMoveRootAck(WorldPacket& recvData)
     mover->UpdatePosition(movementInfo.pos);
-
-    WorldPacket data(MSG_MOVE_ROOT, 64);
-    WriteMovementInfo(&data, &movementInfo);
-    mover->SendMessageToSet(&data, _player);
 }
@@ -1032,6 +1028,2 @@ void WorldSession::HandleMoveUnRootAck(WorldPacket& recvData)
     mover->UpdatePosition(movementInfo.pos);
-
-    WorldPacket data(MSG_MOVE_UNROOT, 64);
-    WriteMovementInfo(&data, &movementInfo);
-    mover->SendMessageToSet(&data, _player);
 }
```
sending `MSG_MOVE_ROOT` was added in https://github.com/azerothcore/azerothcore-wotlk/commit/0c8fb1ea73372e052643ea02d7c30379fba1d547
<details><summary>video clips</summary>

https://github.com/user-attachments/assets/1766df3f-9667-44f4-a39a-5c582a42e6b2

https://github.com/user-attachments/assets/9769b53f-de39-4635-9b54-1ccb9d917621


https://github.com/user-attachments/assets/6089f69a-49b7-4bc8-9032-0588ec578f14


https://github.com/user-attachments/assets/313e575d-2640-4a7b-a80f-795f0b3c1e41



</details>
