### ISSUE TITLE
About lambda error handling: addqueryholdercallback (characterdatabase. Delayqueryholder (holder)) 

### ISSUE THREAD

**Issue by hahalmtdhl** [azerothcore/azerothcore-wotlk#11160]
### Current Behaviour

The purpose is to simulate players logging in to the game, It was normal until it was updated: #5611

Through breakpoint debugging, I can get the account and password normally, but the new lambad callback doesn't work properly

Thank you in advance for your help! I wish you all the best!

### Expected Blizzlike Behaviour

Login processing should be performed normally

### Steps to reproduce the problem

Below is my code:
`
bool FakeBot::FakePlayerLogin()
{
SessionMap const& Sessions = sWorld->GetAllSessions();
for (auto const& AccountMap : m_AllAccount)
{
uint32 AccountId = AccountMap.first;
if (Sessions.find(AccountId) != Sessions.end())
continue;

    if (m_BotAccount[AccountId].size() < AccountMax)
    {
        for (auto const& PlayerGuid : AccountMap.second)
        {

            ObjectGuid PGUID = ObjectGuid(HighGuid::Player, PlayerGuid);

            Player* FakeBot = ObjectAccessor::FindPlayer(PGUID);

            if (FakeBot && FakeBot->IsInWorld())
                continue;

            auto const itr = m_BotPlayers.find(PlayerGuid);
            if (itr != m_BotPlayers.end())
                continue;

            WorldSession* FakerSession = new WorldSession(AccountId, "", nullptr, SEC_PLAYER, 2, time(NULL), LOCALE_zhCN, 0, false, true, 0);
            if (!FakerSession)
            {
                delete FakerSession;
                continue;
            }

            FakerSession->SetplayerLoading(true);
           
            std::shared_ptr<LoginQueryHolder> holder = std::make_shared<LoginQueryHolder>(AccountId, PGUID);

            if (!holder->Initialize())
            {
                FakerSession->SetplayerLoading(false);
                continue;
            }

            //The new version is handled, but he has some problems
            FakerSession->AddQueryHolderCallback(CharacterDatabase.DelayQueryHolder(holder)).AfterComplete([FakerSession](SQLQueryHolderBase const& holder)
            {
                    FakerSession->HandlePlayerLoginFromDB(static_cast<LoginQueryHolder const&>(holder));
            });

            //Handling of old versions
            //LoginQueryHolder* holder = new LoginQueryHolder(AccountId, PGUID);
            //if (!holder->Initialize())
            //{
            //    delete holder;
            //    FakerSession->SetplayerLoading(false);
            //    continue;
            //}

            //auto NowLoginCallback = CharacterDatabase.DelayQueryHolder((CharacterDatabaseQueryHolder const&)(Holder));
            //CharacterDatabaseQueryHolder* ParamHolder;
            //NowLoginCallback.get(ParamHolder);
            //FakerSession->HandlePlayerLoginFromDB((LoginQueryHolder&)ParamHolder);

            Player* GameBot = FakerSession->GetPlayer();
            if (!GameBot)
            {
                 LOG_ERROR("Custom Tab","Fakeer << Guid: %u AccId: %u LoadError", PlayerGuid, AccountId);
                FakerSession->LogoutPlayer(false);
                delete FakerSession;
                continue;
            }
            return true;
        }
    }
}

return false;`

### AC rev. hash/commit

![image](https://user-images.githubusercontent.com/18229643/160250047-396cc209-8c12-4fd5-90d0-ffc5b918e9f4.png)

### Operating system

WIN10 19044.1586

### Custom changes or Modules

eluna

**Comment by hahalmtdhl** [comment]
@ZhengPeiRu21 I see your < playerbot > code is perfect, and I have some problems You should be able to help me. I don't know if you are willing to.

**Comment by Kitzunu** [comment]
that rev doesnt exist. If you are trying to fix something open a PR and someone can look at your code and help you there
