### ISSUE TITLE
After the Rune of DK is used, the rune has no cooling prompt

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11186]
### Current Behaviour

https://youtu.be/jt1DmnFubjI

After the Rune of DK is used, the rune has no cooling prompt ,When `Not enough runes` is prompted, the rune in the upper left corner still indicates that 2 runes are available.

### Expected Blizzlike Behaviour

When using a spell, the rune energy bar in the upper left corner should enter the cooling state, just like the skill spell
![image](https://user-images.githubusercontent.com/18187177/160359476-de056dcd-7b85-4ea5-9660-2f17a5af77a9.png)

### Steps to reproduce the problem

1. .Cast a spell that requires runes
2. Check whether the rune energy bar changes

### Extra Notes

from 3890f5f0001c94445da6e8047521d42f2b875559 to 9e7d1e2a3af7b70c6f2f5ed3d23ea4c9c65c2454 
Then there was a bug

### AC rev. hash/commit

9e7d1e2a3af7b70c6f2f5ed3d23ea4c9c65c2454

### Operating system

ubuntu 20.04

**Comment by Bmtcoder** [comment]
Hi
I can confirm the problem.

**Comment by r0m1ntik** [comment]
Confirm on [e8e8c3](https://github.com/azerothcore/azerothcore-wotlk/commit/e8e8c345906220d2c3dda2066b9baf14172b9897)

**Comment by muctwanted** [comment]
I confirm this bug waiting for a solution)
