### ISSUE TITLE
[server] cast spell delay

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11204]
### Current Behaviour

server cast spell delay.... my server 32H 32  G  bandwidth 100Mb...

Spell delay approx. 0.5 seconds

Console display
 ```
2022-03-28 20:46:27 INFO  [time.update] Update time diff: 167. Players online: 1101.
2022-03-28 20:51:27 INFO  [time.update] Update time diff: 137. Players online: 1114.
2022-03-28 20:56:27 INFO  [time.update] Update time diff: 132. Players online: 1124.
2022-03-28 21:01:27 INFO  [time.update] Update time diff: 143. Players online: 1122.
2022-03-28 21:06:28 INFO  [time.update] Update time diff: 140. Players online: 1135.
2022-03-28 21:16:28 INFO  [time.update] Update time diff: 169. Players online: 1154.

```

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

9e7d1e2a3af7b70c6f2f5ed3d23ea4c9c65c2454

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
`Update time diff: 150. Players online: 1186.`

**Comment by FrancescoBorzi** [comment]
to fix that we need to understand what exactly is triggering that delay.. when the Update time diff is higher than ~10 ms, then there is some problem. However, this is very weird because on ChromieCraft we always have 10-11ms server diff even with 1000 players online.

maybe something specific is triggering this? needs more investigation @mpfans ... try to understand what triggers the delay

**Comment by Nyeriah** [comment]
@mpfans are you still running the cast spell delay PR? Might be why.

**Comment by Winfidonarleyan** [comment]
Show modules list

**Comment by Kitzunu** [comment]
Run grafana. Maybe it can help to pinpoint stuff causing it in the world

**Comment by mpfans** [comment]
> 

no... PR 10522 will cause the server to crash

**Comment by mpfans** [comment]
> Show modules list

`mod-anticheat` and `mod-multi-client-check`

**Comment by mpfans** [comment]
> Run grafana. Maybe it can help to pinpoint stuff causing it in the world

What do you need to monitor?

**Comment by mpfans** [comment]
`cmake ../ -DCMAKE_INSTALL_PREFIX=/home/accore/run/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS=0 -DSCRIPTS=static -DCMAKE_BUILD_TYPE=RELWITHDEBINFO`

Do I need to improve the compiled commands?

**Comment by Kitzunu** [comment]
> > Run grafana. Maybe it can help to pinpoint stuff causing it in the world
> 
> What do you need to monitor?

You can monitor a lot that can help solve the issue. To show if other bad stuff is causing it

**Comment by mpfans** [comment]
> Configuration options that can help you:
> 
> ```ini
> #
> #    LoginDatabase.WorkerThreads
> #    WorldDatabase.WorkerThreads
> #    CharacterDatabase.WorkerThreads
> #        Description: The amount of worker threads spawned to handle asynchronous (delayed) MySQL
> #                     statements. Each worker thread is mirrored with its own connection to the
> #                     MySQL server and their own thread on the MySQL server.
> #        Default:     1 - (LoginDatabase.WorkerThreads)
> #                     1 - (WorldDatabase.WorkerThreads)
> #                     1 - (CharacterDatabase.WorkerThreads)
> 
> LoginDatabase.WorkerThreads     = 1
> WorldDatabase.WorkerThreads     = 1
> CharacterDatabase.WorkerThreads = 1
> 
> #
> #    LoginDatabase.SynchThreads
> #    WorldDatabase.SynchThreads
> #    CharacterDatabase.SynchThreads
> #        Description: The amount of MySQL connections spawned to handle.
> #        Default:     1 - (LoginDatabase.WorkerThreads)
> #                     1 - (WorldDatabase.WorkerThreads)
> #                     2 - (CharacterDatabase.WorkerThreads)
> 
> LoginDatabase.SynchThreads     = 1
> WorldDatabase.SynchThreads     = 1
> CharacterDatabase.SynchThreads = 2
> 
> #
> #    ThreadPool
> #        Description: Number of threads to be used for the global thread pool
> #                     The thread pool is currently used for:
> #                      - Signal handling
> #                      - Remote access
> #                      - Database keep-alive ping
> #                      - Core freeze check
> #                      - World socket networking
> #        Default:     2
> 
> ThreadPool = 2
> 
> #
> #    MapUpdateInterval
> #        Description: Time (milliseconds) for map update interval.
> #        Default:     100 - (0.1 second)
> 
> MapUpdateInterval = 100
> 
> #
> #    MapUpdate.Threads
> #        Description: Number of threads to update maps.
> #        Default:     1
> 
> MapUpdate.Threads = 1
> 
> #    Network.Threads
> #        Description: Number of threads for network.
> #         Default:    1 - (Recommended 1 thread per 1000 connections)
> 
> Network.Threads = 1
> ```

This setting is still delayed

**Comment by Winfidonarleyan** [comment]
> > Configuration options that can help you:
> > 
> > ```ini
> > #
> > #    LoginDatabase.WorkerThreads
> > #    WorldDatabase.WorkerThreads
> > #    CharacterDatabase.WorkerThreads
> > #        Description: The amount of worker threads spawned to handle asynchronous (delayed) MySQL
> > #                     statements. Each worker thread is mirrored with its own connection to the
> > #                     MySQL server and their own thread on the MySQL server.
> > #        Default:     1 - (LoginDatabase.WorkerThreads)
> > #                     1 - (WorldDatabase.WorkerThreads)
> > #                     1 - (CharacterDatabase.WorkerThreads)
> > 
> > LoginDatabase.WorkerThreads     = 1
> > WorldDatabase.WorkerThreads     = 1
> > CharacterDatabase.WorkerThreads = 1
> > 
> > #
> > #    LoginDatabase.SynchThreads
> > #    WorldDatabase.SynchThreads
> > #    CharacterDatabase.SynchThreads
> > #        Description: The amount of MySQL connections spawned to handle.
> > #        Default:     1 - (LoginDatabase.WorkerThreads)
> > #                     1 - (WorldDatabase.WorkerThreads)
> > #                     2 - (CharacterDatabase.WorkerThreads)
> > 
> > LoginDatabase.SynchThreads     = 1
> > WorldDatabase.SynchThreads     = 1
> > CharacterDatabase.SynchThreads = 2
> > 
> > #
> > #    ThreadPool
> > #        Description: Number of threads to be used for the global thread pool
> > #                     The thread pool is currently used for:
> > #                      - Signal handling
> > #                      - Remote access
> > #                      - Database keep-alive ping
> > #                      - Core freeze check
> > #                      - World socket networking
> > #        Default:     2
> > 
> > ThreadPool = 2
> > 
> > #
> > #    MapUpdateInterval
> > #        Description: Time (milliseconds) for map update interval.
> > #        Default:     100 - (0.1 second)
> > 
> > MapUpdateInterval = 100
> > 
> > #
> > #    MapUpdate.Threads
> > #        Description: Number of threads to update maps.
> > #        Default:     1
> > 
> > MapUpdate.Threads = 1
> > 
> > #    Network.Threads
> > #        Description: Number of threads for network.
> > #         Default:    1 - (Recommended 1 thread per 1000 connections)
> > 
> > Network.Threads = 1
> > ```
> 
> This setting is still delayed
> 
> 

These are basic settings, you need to change them for your server

**Comment by mpfans** [comment]
@FrancescoBorzi  gave some settings. After adjustment, the delay decreased significantly Close this issue

**Comment by zoo0074** [comment]
> @FrancescoBorzi gave some settings. After adjustment, the delay decreased significantly Close this issue

I encountered the same problem as you, may I ask how you resolved it?

**Comment by FrancescoBorzi** [comment]
@zoo0074 I don't remember which suggestions I gave, maybe @mpfans can help.

But it's better to continue the discussion elsewhere: https://www.azerothcore.org/wiki/how-to-ask-for-help
