### ISSUE TITLE
RBAC: Role based Access Control

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1121]
It would be nice to have the [RBAC](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130095/RBAC+Role+based+Access+Control) system in AzerothCore

This is also part of https://github.com/azerothcore/azerothcore-wotlk/issues/1118

**Comment by BarbzYHOOL** [comment]
@Deku :P :pray:

**Comment by Deku** [comment]
As I mentioned time ago, RBAC using const numbers isn't suitable for AC since we must support modules, so we must implement RBAC with namespaced string permissions. Sadly, right now I don't have the time to take on this.

**Comment by FrancescoBorzi** [comment]
Personally, I don't think supporting RBAC is critical for AzerothCore.

However I thought it was still worth to mention it and open a thread to give a bit of visibility, in case someone wanted to work on this task.

**Comment by brussens** [comment]
Properly prepared RBAC is quite difficult. However, there are real implementations in other programming languages. Worth a look at them. For example, the rich implementation in my favorite Yii framework.

**Comment by FrancescoBorzi** [comment]
It looks like there is no real interest in doing such a big work, closing this.
