### ISSUE TITLE
[BWL] Blackwing technicians event before vael restart after a crash/restart

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#11211]
### Current Behaviour

When you enter in the vael room, the blackwings techicians flee. But this mini event restart each time after a crash/restart with dead technicians. (look funny on the video xD)

### Expected Blizzlike Behaviour

This event happens only once time by active instance. Even after a crash/restart.

### Source

Local server : https://youtu.be/NOZlmd69G3U

### Steps to reproduce the problem

1. Go to the vaelastraz room
2. Close worldserver or do !serv restart 1
3. Reconnect IG and see the scene

### AC rev. hash/commit

AzerothCore rev. bd2844bb2d24

### Operating system

Windows 11

**Comment by UltraNix** [comment]
@Lynethris Event with the boss and Nefarius should occur only once per instance as well?

**Comment by UltraNix** [comment]
On `.gm off` these mobs are not visible - looks okay.
