### ISSUE TITLE
Lichking's 3rd and last phase bug

### ISSUE THREAD

**Issue by Catchbad** [azerothcore/azerothcore-wotlk#11219]
### Current Behaviour

Greetings,

Another bug was found regarding "The Lich King" ( 36597 ), in his 40%-10% phase he casts a spell called "Harvest Soul" ( 68980 ) while you are targeted and get transported to the new platform you drop down like there is no platform in there at all. 
Havn't tested all the difficulties but 10Normal but I assume that it is the same in all.

### Expected Blizzlike Behaviour

The idea behind the spell is to go there and kill/interrupt an add trying to kill Lich King's dad, but sadly there is no platform to do so:).

### Source

https://www.wowhead.com/npc=36597/the-lich-king#article

### Steps to reproduce the problem

Step 1 : Gather 2-3 people and move to "The Lich King" platform, get him to 40% ( you have to experience all the phases, get him to 70% turn your gm off attack so he starts the phase and after that get him to 40% attack experience the edge phase again ) 
Step 2 : while having someone as a tank ( The Lich King's Target ) the other players/gms should wait to be targeted by Lich King's spell called : Harvest Soul
Step 3 : Enjoy Your Flight:)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9f4f824336dec127300f71ab577ce416056cc776

### Operating system

Windows 2022

**Comment by Ramys** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/11146

**Comment by fullofstarschen** [comment]
In fact,in this phase,you can kill the add and return to the platform if you are a hunter or mage like and you don't move from the beginning.Unfortunately when you are a warrior like and have to move,you will drop down,also if you a a healer you will fail for you can't  help  Lich King's dad at all.

**Comment by Meramaf** [comment]
This Issue with Platform is not fixed.

**Comment by Dr-Arayashiki** [comment]
There are servers where this is fixed, why isn't it also fixed on the main page itself? :(

**Comment by heyitsbench** [comment]
> There are servers where this is fixed, why isn't it also fixed on the main page itself? :(

Feel free to contact those servers and ask them to submit their fix to the core. :)

**Comment by Dr-Arayashiki** [comment]
> > There are servers where this is fixed, why isn't it also fixed on the main page itself? :(
> 
> Feel free to contact those servers and ask them to submit their fix to the core. :)

Believe me, I already contacted the servers, but without success.... :(

**Comment by tabooo** [comment]
still bug
