### ISSUE TITLE
Lich King 10% Phase

### ISSUE THREAD

**Issue by Catchbad** [azerothcore/azerothcore-wotlk#11229]
### Current Behaviour

Greetings,

In my previous "The Lich King" bug I forgot to mention the bug in his 10% phase when you get "The Lich King" to 10% hp after the RP ( he kills you, his father's soul comes to aid us e.t.c e.tc ) when he is in the air and you are supposed to kill him, he doesn't take any damage at all, even GM's cannot kill him with .damage command.

### Expected Blizzlike Behaviour

After he reaches 10% hp, he will be vulnerable and we are able to kill him without any harm from "The Lich King".

### Steps to reproduce the problem

Step 1: Get "The Lich King" 70%, experience the phase
Step 2: Get "The Lich King" 40%, experience the phase
Step 3: Get "The Lich King" Wait for the RP to end, then when he is up in the air being choked by some spells deal damage to him, and you gonna realize he doesn't take any damage.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9f4f824336dec127300f71ab577ce416056cc776

### Operating system

Windows 2022

**Comment by Ramys** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/11146

**Comment by Bogir** [comment]
This will be fixed when  #11146 will be merged

**Comment by Nefertumm** [comment]
Closed by e139ed1c0bbd342b300083e1ffbfdb883cb1b009
