### ISSUE TITLE
Duel bug on accept

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#11224]
### Current Behaviour

When you throw a duel, the count goes on and during the count you can hit the AoE spell or give a fear there, but the PvP flag changes after 3 seconds

[https://streamable.com/6oykuf](https://streamable.com/6oykuf)

### Expected Blizzlike Behaviour

You can only hit after the end countdown.

### Steps to reproduce the problem

1. offer a duel to one player

2. As soon as the report starts, use any Aoe spell

### AC rev. hash/commit

[fed66a342977b3d57ada6b5623d641c8fbd1aa30](https://github.com/azerothcore/azerothcore-wotlk/commit/fed66a342977b3d57ada6b5623d641c8fbd1aa30)

### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by Bogir** [comment]
I can confirm it.
Before the counter starts the duel, you can hit the enemy with an AOE attack, but must not.

**Comment by mpfans** [comment]
confirmed.. You can cast spells on friendly targets at the beginning of the countdown

**Comment by Bmtcoder** [comment]
I can confirm it.

**Comment by muctwanted** [comment]
I confirm this bug waiting for a solution)
