### ISSUE TITLE
[CORE][COMPILE] player.cpp error compilation

### ISSUE THREAD

**Issue by virgo77** [azerothcore/azerothcore-wotlk#11228]
### Current Behaviour

I don't know where to post this compile error, so I try here. So, I apologize if it is not the good way

In the latest core update, when I compile I get 1 warning and 3 messages, about Player.cpp

About the warning:
- Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4389	'==': signed/unsigned mismatch (compiling source file .\src\server\game\Entities\Player\Player.cpp)	game	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility	5307	

About the 3 messages:
- Severity	Code	Description	Project	File	Line	Suppression State
Message		see reference to function template instantiation '_InIt std::_Find_unchecked1<_InIt,_Ty>(_InIt,const _InIt,const _Ty &,std::false_type)' being compiled	game	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility	5342	

- Severity	Code	Description	Project	File	Line	Suppression State
Message		see reference to function template instantiation '_InIt std::_Find_unchecked<const unsigned int*,_Ty>(const _InIt,const _InIt,const _Ty &)' being compiled	game	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility	5348	

- Severity	Code	Description	Project	File	Line	Suppression State
Message		see reference to function template instantiation '_InIt std::find<std::_Array_const_iterator<_Ty,1>,int32>(_InIt,const _InIt,const int &)' being compiled	game	.\src\server\game\Entities\Player\Player.cpp	6971	

And if i double click on a message, VC++2019 is getting about 230 warning on lots of ".h" files saying that "enum type 'blablabla' is unscoped..."

Tonight, I read that the PlayerGossip.cpp got some changes [here](https://github.com/azerothcore/azerothcore-wotlk/commit/fed66a342977b3d57ada6b5623d641c8fbd1aa30)
Maybe it's because of that?

Again, I really apologize if it is not the good way to open a core issue

### Expected Blizzlike Behaviour

none. It's a core issue post

### Steps to reproduce the problem

Just pull an update and compile 'Release' or 'RelWithDebInfo'

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/bd2844bb2d247ad69145fdb12acc6b213a087ac0

### Operating system

Windows Server 2022 Standard, Debian 11, MariaDB 10.5.12

### Custom changes or Modules

[Modules]
AH Bot
Transmog
DK Skip Start Area

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/runs/5728319196?check_suite_focus=true MSVC build all passing.

Update Visual Studio to >=16.11

**Comment by virgo77** [comment]
Hi Kitzunu, thanks for your answer.
Effectively, I updated to VC2019 16.11 and it seems to be good. But I still saw these messages in the compile window:
```
20>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(5307,21): warning C4389: '==': signed/unsigned mismatch (compiling source file D:\GAMES\BLIZZARD\WORLD_OF_WARCRAFT\AZEROTHCORE\core.modded\src\server\game\Entities\Player\Player.cpp)
20>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(5342): message : see reference to function template instantiation '_InIt std::_Find_unchecked1<_InIt,_Ty>(_InIt,const _InIt,const _Ty &,std::false_type)' being compiled
20>        with
20>        [
20>            _InIt=const unsigned int *,
20>            _Ty=int32
20>        ] (compiling source file D:\GAMES\BLIZZARD\WORLD_OF_WARCRAFT\AZEROTHCORE\core.modded\src\server\game\Entities\Player\Player.cpp)
20>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(5348): message : see reference to function template instantiation '_InIt std::_Find_unchecked<const unsigned int*,_Ty>(const _InIt,const _InIt,const _Ty &)' being compiled
20>        with
20>        [
20>            _InIt=const unsigned int *,
20>            _Ty=int32
20>        ] (compiling source file D:\GAMES\BLIZZARD\WORLD_OF_WARCRAFT\AZEROTHCORE\core.modded\src\server\game\Entities\Player\Player.cpp)
20>D:\GAMES\BLIZZARD\WORLD_OF_WARCRAFT\AZEROTHCORE\core.modded\src\server\game\Entities\Player\Player.cpp(6971): message : see reference to function template instantiation '_InIt std::find<std::_Array_const_iterator<_Ty,1>,int32>(_InIt,const _InIt,const int &)' being compiled
20>        with
20>        [
20>            _InIt=std::_Array_const_iterator<uint32,1>,
20>            _Ty=uint32
20>        ]
```
I don't know if it's impacting the core stability but I preferred to talk about.

Just one question: VC2022 is recently out. Do you think it's a good idea to install this new build, or is it better to wait for now?

Good night (in France, it's time to sleep ^^)

**Comment by acidmanifesto** [comment]
I recently migrated to vs 2022 and i notice significant speed up in compiling.

**Comment by Kitzunu** [comment]
You can ignore all Warnings.

**Comment by virgo77** [comment]
oki doki, thanks to both of you!
I think I will install 2022 so, if compiling is a bit faster ^^
