### ISSUE TITLE
DeathKnight Runes.

### ISSUE THREAD

**Issue by Catchbad** [azerothcore/azerothcore-wotlk#11233]
### Current Behaviour

Greetings
There is this bug regarding DeathKnight's Rune powers, they are not visible nor cooldown trackable.
With this bug, it looks like you always have runes to spend even tho it might be in cooldown, and it's really hard to play without having a track of your runes, even with add-ons you cannot track them.

### Expected Blizzlike Behaviour

Death Knight Normaly Has 6 runes, 2 blood , 2 frost and 2 unholy runes and under some circumstances, it turns into death runes.Normally

### Source

Couldn't find any source for it.

### Steps to reproduce the problem

Step 1 : Create A Dk
Step 2 : Check under your character's unit frame you gonna realize that its empty.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9f4f824336dec127300f71ab577ce416056cc776

### Operating system

Windows 2022

**Comment by pklloveyou** [comment]
The mistake here https://github.com/azerothcore/azerothcore-wotlk/pull/10908

**Comment by Nefertumm** [comment]
CC @UltraNix

**Comment by mpfans** [comment]
duplicate https://github.com/azerothcore/azerothcore-wotlk/issues/11186
