### ISSUE TITLE
Ranged attacks can cross terrain

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#11234]
### Current Behaviour

As shown in the figure:
![image](https://user-images.githubusercontent.com/18535853/160980820-63067998-4cd9-4bab-b52d-fc11bf28ce27.png)
![image](https://user-images.githubusercontent.com/18535853/160981257-fc3df847-ec31-4273-8d9c-8bfd0b37874c.png)

### Expected Blizzlike Behaviour

Ranged attacks should not cross terrain

### Steps to reproduce the problem

1. Use mage or hunter.
2. ``` .go xyz -10473.21 1525.89 62.0  0 ```
3. Stand where you are and attack the creature above.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e139ed1c0bbd342b300083e1ffbfdb883cb1b009

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
It's not a bug. Terrain does not block LoS. It's blizzlike.
More info: https://github.com/TrinityCore/TrinityCore/issues/25654#issuecomment-728155804

**Comment by pklloveyou** [comment]
ok Thank you
