### ISSUE TITLE
While turning in quests the NPC's prioritize the wrong marker

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#11237]
Original CC Issue: https://github.com/chromiecraft/chromiecraft/issues/2989

### Current Behaviour

Wrong quest giver status (Icon Markers above head) priorty are given out of priority and order.

### Expected Blizzlike Behaviour

Per CC Report:
I'm pretty sure NPC's should always show the turn in quest marker above their head (?) if there's a quest to be delivered even if it can deliver a new quest (!).

Also, the turn in quest marker should appear in the minimap.

### Steps to reproduce the problem

For this particular example:

Don't do the quest "The First and the Last".
Complete the quest "A Gift for The King of Stormwind".
Turn in "A Gift..."

### AC rev. hash/commit

[e8e8c34](https://github.com/azerothcore/azerothcore-wotlk/commit/e8e8c345906220d2c3dda2066b9baf14172b9897)

### Operating system

Windows 11 x64 Pro

### Custom changes or Modules

- anticheat module

**Comment by pklloveyou** [comment]
You can try to restore it https://github.com/azerothcore/azerothcore-wotlk/pull/9962

**Comment by UltraNix** [comment]
@pklloveyou ??

**Comment by pklloveyou** [comment]
Sometimes the repair is not displayed after completing the task ”？“
