### ISSUE TITLE
[server] crash log - battleground queue assert

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11241]
### Current Behaviour

crash log

https://gist.github.com/mpfans/632ebafae6bca8e7653179af6a3760dc

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

fed66a342977b3d57ada6b5623d641c8fbd1aa30 + PR https://github.com/azerothcore/azerothcore-wotlk/pull/11225

### Operating system

ubuntu 20.04

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/11165

**Comment by mpfans** [comment]
crash again 

https://gist.github.com/mpfans/0ef2ba09e560a29d73f2555d0ccfc27a

**Comment by Nefertumm** [comment]
Not the same as the first one though. Open another issue with that one, seems related to Auction House

**Comment by mpfans** [comment]
ok

**Comment by Nefertumm** [comment]
Did you apply the PR I linked above?

**Comment by mpfans** [comment]
crash again 

https://gist.github.com/mpfans/0bc5edb2eaf2f1c1cccf03ea1592e41e

**Comment by mpfans** [comment]
> Did you apply the PR I linked above?

no

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/eee2d68a1d1eb8cfdfcb393fa1191eedc9b07dfa
