### ISSUE TITLE
SQL format string does not match database for table: skilllineability_dbc'

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#11243]
### Current Behaviour

REPLACE INTO skilllineability_dbc SET ID=39001, SkillLine=270, Spell=123111, MinSkillLineRank=1, AcquireMethod=2
when i insert this data to acore_world.skilllineability_dbc and startup the server, it reported this problem
# Location '/home/azerothcore/src/server/shared/DataStores/DBCDatabaseLoader.cpp:116'
# Function 'Load'
# Condition 'sqlColumnNumber == result->GetFieldCount()'
# Message 'SQL format string does not match database for table: 'skilllineability_dbc''

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

# Location '/home/azerothcore/src/server/shared/DataStores/DBCDatabaseLoader.cpp:116'
# Function 'Load'
# Condition 'sqlColumnNumber == result->GetFieldCount()'
# Message 'SQL format string does not match database for table: 'skilllineability_dbc''

### Operating system

ubuntu 21

**Comment by Kitzunu** [comment]
Dont ignore the template
