### ISSUE TITLE
Black Lotus (35.7, 20.6) from Eastern Plaguelands not obtainable

### ISSUE THREAD

**Issue by Annamaria-CC** [azerothcore/azerothcore-wotlk#11268]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The herb is invisible, under the ground or inside the cauldron, doing it impossible to grab.

https://wowgaming.altervista.org/aowow/?object=176589

### Expected Blizzlike Behaviour

The herb should be grabbable

### Steps to reproduce the problem

I went to coordinate 35.7, 20.6 from Eastern Plaguelands and i tried to grab the Black Lotus tracked on the minimap and it wasn't possible.

### Extra Notes

https://wowgaming.altervista.org/aowow/?object=176589
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3192 
![image](https://user-images.githubusercontent.com/20357406/161432706-b593bda5-221a-4bd9-957b-a2e1340e1f87.png)
![image](https://user-images.githubusercontent.com/20357406/161432715-fc0f3843-ccda-4c15-85d5-a8be7a0e64ed.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
@temperrr is this with all herbs or just one herb? what is the guid of the object?

**Comment by temperrr** [comment]
@acidmanifesto 
Just that herb, see screenshot

**Comment by Gultask** [comment]
I'm certain that node isn't sniffed. To move them just needs to update their coords.
After that it's possible to delete the pool_gameobject entry for it to make it 100% chance to spawn to check if the new position is ok.
```
UPDATE `gameobject` SET `position_x`=X, `position_y`=Y, `position_z`=Z WHERE `guid`=XXXX;
DELETE FROM `pool_gameobject` WHERE `guid`=XXXX;
```

**Comment by neifion-00000000** [comment]
this node location is actually real, though I was instructed to fix these z coordinate issues last time I brought it up
