### ISSUE TITLE
Rallying Cry of the Dragonslayer never happens

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11267]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Upon handing in the Head of Onyxia for the final step that grants the trinket/neck/ring, the head doesn't appear above Major Mattingly, he doesn't perform his RP/yell and he doesn't drop Rallying Cry of the Dragon Slayer on players in Stormwind.

Our guild mate also relayed that his buff didn't occur on horde side either. 

### Expected Blizzlike Behaviour

He should yell out his flavour text.
The head should be mounted in the arch. 
Players should receive Rallying Cry of the Dragonslayer. 

### Steps to reproduce the problem

Complete head of onyxia quest chain.

### Extra Notes
Also does not work for horde side.
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3073
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nelnamara** [comment]
I've been looking through the quests, the Stormwind_City.cpp and creature scripts and could not find evidence of the spell anywhere.  I figure Mattingly might have a creature script in the city.cpp but there isn't 
Playing with the quest the best I was able to see was the ability to learn the spell (Nice) But no....
I was going to look at the Onyxia script but it doesn't make much sense it would be there.

Maybe a creature script needs to be added to the 2 city cpp files if they are not elsewhere.

**Comment by mspzyzh** [comment]
I have the same problem
