### ISSUE TITLE
Feature: Arena Spectator NPC.

### ISSUE THREAD

**Issue by devovh** [azerothcore/azerothcore-wotlk#11263]
### Describe your feature request or suggestion in detail

After the rework Battleground, there is a problem with Arena Spectator NPC. The problem is with GetBattlegroundList which has been changed or removed - this refers to this change that was made here: 

https://github.com/devovh/azerothcore-wotlk/commits/master

### Describe a possible solution to your feature or suggestion in detail

The GetBattlegroundList functions should be added with similar action as before the rework.

**Comment by acidmanifesto** [comment]
Is this a bug report or a feature suggestion?

**Comment by devovh** [comment]
Both at the same time. This mod is available publicly from another author, it worked correctly until the battleground revert.

**Comment by acidmanifesto** [comment]
If this is a bug report for the core then please feel out the appropiate template. If there is issues with the module then you will need to fill out a issue report on the module's git itself. This bug report/feature request is insanely all over the place and is not in the right spots as suggested. Until this issues gets posted appropiately i will need to close this.
