### ISSUE TITLE
Feature: Error reporting for vmap assembler

### ISSUE THREAD

**Issue by LordArcanine** [azerothcore/azerothcore-wotlk#11266]
### Describe your feature request or suggestion in detail

Working with custom maps or the client make big problems with the collision extraction.

Mapextractor and vmapextractor easy report when a wmo give error but sadly vmapassembler only crash without giving a error message that descrive the wmo that is giving problems (or m2), this is speccially problematic for the devs that make custom maps or modificarion to original maps.

For example when my vmapassembler try to assemble the map 1 giving only a windows crash report with not significant error, the problem is i cant learn whats the wmo or m2 that is giving the error and i have no way to fixing it.

### Describe a possible solution to your feature or suggestion in detail

The solution is to make vmapassembler give a detailed report of what m2 or wmo is giving the error and why.

This will help a lot

**Comment by Kitzunu** [comment]
Run it through command prompt, dont just run the bat file.
