### ISSUE TITLE
 [Profession] Unable to change leatherworking specialization

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11262]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Decided to change my leatherworking specialization from elemental to tribal.

Unlearning the elemental leatherworking worked fine at the trainer. Then went to Steamwheedle Port in Tanaris to use the book "Soothsaying for Dummies" to learn tribal LW.

I can interact with the book (can open it) but clicking any of the LW specs as new one does absolutely nothing.

Obviously tested with addons off and cleared cache. Tested on PTR too, same problem.

![WoWScrnShot_033122_105331](https://user-images.githubusercontent.com/43609330/161006600-45713148-189a-4318-bea7-6cde2ca28f46.jpg)

### Expected Blizzlike Behaviour

The Soothsaying for Dummies -book should let you learn new LW specialization after unlearning the old one.

### Steps to reproduce the problem

- Learn leatherworking and complete the elemental specialization quest in Searing Gorge (NPC Sarah Tanner for alliance, id 7868).
- Unlearn the specialization from same NPC
- Go to Steamwheedle Port in Tanaris and try to learn new specialization using the "Soothsaying for Dummies" book

### Extra Notes
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3272

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kosiak** [comment]
@Nefertumm Inside npc_profession.cpp change `GOSSIP_SENDER_MAIN` to `GOSSIP_SENDER_LEARN` on Lines 1275,1276,1277 will work as intended.

**Comment by Nefertumm** [comment]
k I didn't have time to really look into, but if that works, feel free to open a PR with your solution 👍

**Comment by Kosiak** [comment]
Dont think i will be near a pc anytime soon. Thats why posted in here :)
