### ISSUE TITLE
ICC 25N bug libramonte

### ISSUE THREAD

**Issue by d3athbl0w** [azerothcore/azerothcore-wotlk#1126]
Description: ICC 25n crash libramorte

Current behaviour:

When activating libramorte in icc 25n the worldserver crash.

Expected behaviour:

Steps to reproduce the problem:

1. Start the fight
2. wait the crash

AC hash/commit: AzerothCore Last Rev

Operating system: Windows server 2016

Modules:-

Other Customizations:-

**Comment by BarbzYHOOL** [comment]
Add the commit hash please and I'll reopen
