### ISSUE TITLE
Lok'delar and Rhok'delar should not be mutually exclusive

### ISSUE THREAD

**Issue by Samsequel** [azerothcore/azerothcore-wotlk#11271]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Hunters who have completed the Ancient Petrified Leaf questline must choose either Rhok'delar or Lok'delar, obviously the choice is Rhok'delar, having to "transform" the item to obtain its counterpart.

This is pre-patch 1.8 behaviour.

### Expected Blizzlike Behaviour

We are playing on patch 3.3.5a, where hunters are supposed to be able to claim Lok'delar for free from Vartus the Ancient after they have obtained Rhok'delar.

### Source

World of Warcraft patch 1.8 Notes :  https://wowwiki-archive.fandom.com/wiki/Patch_1.8.0
"The ability to transform Rhok'delar and Lok'delar has been removed, but you can talk to Vartrus the Ancient to receive the item you currently don't possess."

Lok'delar history : https://wowpedia.fandom.com/wiki/Lok%27delar,_Stave_of_the_Ancient_Keepers
[Patch 4.0.3a] (2010-11-23): Removed.
[Patch 1.8.0] (2005-10-10): The ability to transform Rhok'delar and Lok'delar has been removed.
[Patch 1.5.0] (2005-06-07): Lok'delar, Stave of the Ancient Keepers now sheathes properly.
[Patch 1.4.0] (2005-04-19): Added.

No change was made to Lok'delar after the 1.8.0 change until 4.0.3a when it was removed.

### Steps to reproduce the problem

step 1. obtain the Ancient Petrified Leaf
step 2. fantasize about Rhok'delar and Lok'delar
step 3. complete the Ancient Petrified Leaf questline
step 4. obtain Rhok'delar
step 5. ???
step 6. cry

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3222

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
This is actually working as intended

**Comment by davegrier** [comment]
This twinstar forum post is reposting an old guide for the quest that explicitly notes both items should be obtainable
https://forum.twinstar.cz/threads/the-hunt-for-rhokdelar-guide.91106/
![image](https://user-images.githubusercontent.com/14080595/193166665-7c40f12c-993b-4a84-879b-1d15e44e5411.png)
The patch notes reading "receive the item you currently don't possess" means pretty clearly, though not 100% unambigiously, to me as a native English speaker to mean that the second item would be provided, rather than an exchange.

**Comment by Gultask** [comment]
![image](https://user-images.githubusercontent.com/100873791/193166680-f499d002-5b52-48d2-bfdc-e2cb41e64833.png)

The broadcast_text IDs are different from what is shown in the game currently.

![image](https://user-images.githubusercontent.com/100873791/193167065-3e3dd884-29c3-460c-b6e3-523d99afb12a.png)

Furthermore, in WoW Classic (based on an older patch, and thus already excludes the ability to transform the weapon) has the spell creating both weapons at once: https://youtu.be/P-ijgwVuRf8?t=1411

Also, copy-pasting from the CC issue:

> [However, I found another source that claims it was possible to have both items at the same time](https://www.engadget.com/2012-05-19-weapons-of-lore-rhokdelar-longbow-of-the-ancient-keepers.html): "But [Rhok'delar](http://www.wowhead.com/item=18713) wasn't without its issues, mainly concerning the ability to change the bow into a staff but not being able to use both staff and bow at the same time. This was eventually changed so that hunters could have both Rhok'delar and its counterpart, [Lok'delar, Stave of the Ancient Keepers](http://www.wowhead.com/item=18715), after completing the Rhok'delar quest chain."

**Comment by Gultask** [comment]
Thanks to Tebec for this info. Wowhead screenshots contain pictures of both items being used at the same time.

![image](https://user-images.githubusercontent.com/100873791/193170541-a6b25199-7a2d-4469-9914-938f2beb3f16.png)
