### ISSUE TITLE
[Warrior][Spell/Ability] Execute, Intercept and Slam cannot be dodged or parried, bypasses Deterrence.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11289]
### Current Behaviour

Execute (Spell ID: 20662), Intercept (Spell ID: 30151) and Slam (Spell ID: 11605) cannot be parried or dodged.
Most notable when facing against a hunter using Deterrence (Spell ID: 19263).

### Expected Blizzlike Behaviour

Execute, Intercept and Slam should be able to be parried and dodged, and without bypassing Deterrence.

### Source

I've not found any sources that indicate that these spells could bypass Deterrence.
If they would be able to, it would've been explicit in the spell's description, like how Overpower's description states "The Overpower cannot be blocked, dodged or parried." or Chaos Bolt's "Chaos Bolt cannot be resisted, and pierces through all absorption effects."

### Steps to reproduce the problem

- Use Execute, Slam or Intercept on a Hunter with the Deterrence aura up.

### Extra Notes

I've also tested 200 executes without using Deterrence and have seen 0 dodges.
Execute (Spell ID: 20662)
Intercept (Spell ID: 30151)
Slam (Spell ID: 11605)
Deterrence (Spell ID: 19263)

Originally Reported: https://github.com/chromiecraft/chromiecraft/issues/3264 & https://github.com/chromiecraft/chromiecraft/issues/3285

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Windows 10.

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
Slam cannot be dodged/parried/blocked. It has special attr - comes from Blizzard files. Not all spells have this mentioned in its descriptions/tooltips.

**Comment by UltraNix** [comment]
As for the Intercept - https://github.com/azerothcore/azerothcore-wotlk/commit/83183fea81081a972ab975f01823deaf08d7a6e4

**Comment by Gultask** [comment]
Ahhh, my mistake. Sorry this was one of the first issues I triaged and I wasn't 100% aware of how to search for duplicates, etc in the ac git. I'll keep it in find for any future issues I go through.

**Comment by Gultask** [comment]
I don't think Intercept should be able to bypass Deterrence, though, this https://github.com/azerothcore/azerothcore-wotlk/pull/6421#issuecomment-864297535 seems to indicate that it was an unintentional side effect of the fix.
"Read all the comments, and want to answer a question. Yes, this DOES deflect warrior charge/intercept stuns"([source](https://www.wowhead.com/spell=19263/deterrence#comments:id=1042488))

**Comment by TarekMadara** [comment]
Hey, just wanted to point out that warriors's intercept is still bypassing deterrence

**Comment by UltraNix** [comment]
@TarekMadara Just open a new ticket about it as this one is already closed.
