### ISSUE TITLE
(Creature): Northspring Harpy underground in Feralas

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#11282]
### Current Behaviour

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/3292 by **Silkarx**
= = = = = = = = = = = = = = = = = = =

Northspring Harpy is currently under map, and needs Z coords change.

![image](https://user-images.githubusercontent.com/61223313/161578312-0f46cd4f-4751-42a1-8b6c-68b2b5cde084.png)

![image](https://user-images.githubusercontent.com/61223313/161578385-fbe17745-4f59-4229-94a0-44a7826fa8fc.png)

![image](https://user-images.githubusercontent.com/61223313/161578197-13d11dcc-5bf6-41ff-be64-ba7fa2160570.png)

### Expected Blizzlike Behaviour

not under map lol like this cute gnome 🐱 

![image](https://user-images.githubusercontent.com/61223313/161577475-fdcdb762-1c1a-42e6-ba8a-37f4fa054c35.png)

### Source

logic

### Steps to reproduce the problem

.go c 51729

### Extra Notes

🐱 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/856aed6fc6ad34fd07f1aa9df2a39c710ffd5b33

### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by FrancescoBorzi** [comment]
@acidmanifesto please don't forget to apply the content labels and project

**Comment by acidmanifesto** [comment]
> @acidmanifesto please don't forget to apply the content labels and project

Good catch. I forgot to apply it to this one.

**Comment by FrancescoBorzi** [comment]
@acidmanifesto why Generic?

**Comment by FrancescoBorzi** [comment]
no worries, just wondering if there was a specific reason, fixed!
