### ISSUE TITLE
Building modules with non-MSBuild

### ISSUE THREAD

**Issue by grabthar** [azerothcore/azerothcore-wotlk#11280]
### Current Behaviour

The generate solution "configure" step is broken on Windows non MSBuild types when using the module eluna lua engine

### Expected Blizzlike Behaviour

Configure step success

### Steps to reproduce the problem

Configure the project

### Extra Notes

Detail: Error is in: azerothcore-wotlk/modules/CMakeLists.txt (L365)
set(MSVC_CONFIGURATION_NAME $(ConfigurationName)/)
$(ConfigurationName) Can't have value on non MSBuild build type and is not interpreted from build command.

Replace:  L365
```
    if (MSVC)
      set(MSVC_CONFIGURATION_NAME $(ConfigurationName)/)
```
   
With:

```
     if("${CMAKE_MAKE_PROGRAM}" MATCHES "MSBuild")
         set(MSVC_CONFIGURATION_NAME $(ConfigurationName)/)
     else()
         # This should support make-like generators do (nmake, ninja)
         set(MSVC_CONFIGURATION_NAME ${CMAKE_BUILD_TYPE}/)
     endif()
```
      
     

### AC rev. hash/commit

446546fb9668761e3ca28c0ff5b93034122cac99

### Operating system

Windows

### Custom changes or Modules

-Platform is Win32
-Using non MSBuild Build type (NMake / Ninja...)
-Using Module Eluna LuaEngine

**Comment by benjymansy123** [comment]
Then this would be an issue to raise with the Eluna module, not AzerothCore, no?

**Comment by grabthar** [comment]
Nope because this is located in the core
azerothcore-wotlk/modules/CMakeLists.txt

**Comment by Kitzunu** [comment]
@Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
If you know how to fix it, it's time to create a pr

**Comment by Kitzunu** [comment]
Closing as we only support MSBuild/msvc
