### ISSUE TITLE
RealmCrash when team cancel skirmish arena and get into queue of rated arenas

### ISSUE THREAD

**Issue by nestormourino** [azerothcore/azerothcore-wotlk#11281]
### Current Behaviour

We've disabled all arena system, because by doing this steps the entire realm crash.

By joining skirmish, leaving queue and joining rated arenas is crashing the realm.

### Expected Blizzlike Behaviour

-

### Steps to reproduce the problem

1. Make a arena team
2. Invite your team mate into your party
3. Join queue of skirmish arena
4. Cancel queue and inmediatly join rated arenas queue.

### AC rev. hash/commit

446546f

### Operating system

Debian 10 x64

### Custom changes or Modules

Anticheat
Chat transmitter
Duel reset
Transmog
World chat

**Comment by r0m1ntik** [comment]
confirm, critical bug

**Comment by UltraNix** [comment]
Crashlog needed.

**Comment by nestormourino** [comment]
@mpfans could you please test and label this? It's critical.

**Comment by Kitzunu** [comment]
Add a crashlog.

**Comment by Kitzunu** [comment]
here's a crashlog for you guys https://gist.github.com/Kitzunu/663bc3e7937c61ae75a133116487cbb7

**Comment by UltraNix** [comment]
@Winfidonarleyan 
```
group->DoForAllMembers([this, ginfo](Player* member)
      {
          ASSERT(m_QueuedPlayers.count(member->GetGUID()) == 0);
          m_QueuedPlayers[member->GetGUID()] = ginfo;
          ginfo->Players.emplace(member->GetGUID());
      });
```
Why you added ASSERT here? You assign later `m_QueuedPlayers[member->GetGUID()] = ginfo;`, so it does not matter if that `m_QueuedPlayers` is already populated by this key.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/162600873-04efefaa-9152-4a69-8e83-9411e0d5b6b1.png)
I did this and found no mistakes

**Comment by mpfans** [comment]
testing
