### ISSUE TITLE
Bug: Logger\Appender not working for Modules

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#11297]
### Current Behaviour

Currently while maintaing the [Anticheat Module.](https://github.com/azerothcore/mod-anticheat) I notice the logger and appender is not actually working at all. Current work around is not to have logger and appender for it at all in world server and let it spam into the server.log file. Which may prove a bit cumberson at times when attempting to look thru the server.log files for particulars that are and are not anticheat related.

I set the following in the world conf

```
Appender.Anticheat=2,3,15,anticheat.log,a
Logger.module=4,Console Server Anticheat

```
So with that being set we do get a Anticheat.log file being shown and being created. But nothing gets logged into it at all. It is a empty file.

### Expected Blizzlike Behaviour

Not Blizzlike Related. Core related.

### Steps to reproduce the problem

1.  set in the world conf
 ```
Appender.Anticheat=2,3,15,anticheat.log,a
Logger.module=4,Console Server Anticheat

```
2. compile azerothcore with [Anticheat Module.](https://github.com/azerothcore/mod-anticheat)

3. load up and notice anticheat.log file is there and created, but does not actually have anything logged into it.

### AC rev. hash/commit

[b709a22](https://github.com/azerothcore/azerothcore-wotlk/commit/b709a22ddc4a12331fa9b3946d619a7211e0c570)

### Operating system

Windows 11 x64 Pro

### Custom changes or Modules

- [Anticheat Module.](https://github.com/azerothcore/mod-anticheat)

**Comment by Winfidonarleyan** [comment]
Need fix loading modules config
