### ISSUE TITLE
[server]worldserver crash 3

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11303]
### Current Behaviour

crash log
https://gist.github.com/mpfans/907b7ac6745fd7d93051c89b07cf74af

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/285504e79d25c84b88413fdfad17c2b83fefda86

### Operating system

ubuntu 20.04

**Comment by UltraNix** [comment]
#11241
