### ISSUE TITLE
[ulduar]Siege Tank error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11314]
### Current Behaviour

The console can see the following error message

![image](https://user-images.githubusercontent.com/18187177/162162885-07629a61-dd5f-42a9-be73-1c4f0021cf53.png)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/285504e79d25c84b88413fdfad17c2b83fefda86

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
It should be that the siege tank has two players and got on the third player

@UltraNix

**Comment by porkserver** [comment]
No console errors 
got in and out of siege engines left instance came back in got new siege engines
Defeated Flame Leviathan and Vehicles respawned without incident.
![Screen Shot 2022-04-09 at 9 23 28 PM](https://user-images.githubusercontent.com/273302/162598474-55b39f5f-7de0-406e-85b1-aab125bfc4ab.png)
![Screen Shot 2022-04-09 at 9 22 35 PM](https://user-images.githubusercontent.com/273302/162598478-41a59790-7065-41ca-b673-aa5c033e61ad.png)
![Screen Shot 2022-04-09 at 9 21 53 PM](https://user-images.githubusercontent.com/273302/162598479-87adf21c-7b46-4b7d-b9b7-52cef1a20867.png)
