### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Catchbad** [azerothcore/azerothcore-wotlk#11329]
### Current Behaviour

https://gist.github.com/Catchbad/9132f5a479e8759a79e3a535cee6882c

### Expected Blizzlike Behaviour

What we all want is a server without crashes 😄 so I don't know how it should be, that's why I'm here

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://gist.github.com/Catchbad/9132f5a479e8759a79e3a535cee6882c

### Operating system

Windows 2022

**Comment by Kitzunu** [comment]
Report shows unknown rev. Closing till a real commit/hash has been put
