### ISSUE TITLE
[Item] Triggered Spells do not Proc

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/azerothcore-wotlk#11335]
### Current Behaviour

Triggered Spell Proc 75465 from Item 54572 Charred Twilight Scale do not Proc

https://wotlkdb.com/?item=54572

Triggered Spell Proc 71602 from Item 50353 Dislodged Foreign Object do not Proc 

https://wotlkdb.com/?item=50353

### Expected Blizzlike Behaviour

Both items have a 10% Proc Chance to Triggered Spell

### Steps to reproduce the problem

add items 54572 and 50353
Test Proc Chance from this items

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68

### Operating system

Windows 10 x64, Ubuntu 20

**Comment by r0m1ntik** [comment]
Confirm

**Comment by Meramaf** [comment]
#11487 https://github.com/azerothcore/azerothcore-wotlk/pull/11487
