### ISSUE TITLE
[server] world crash 

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11331]
### Current Behaviour

crash log
https://gist.github.com/mpfans/c01d227cf52ee18a5a92f9fdb30cc1da

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68

### Operating system

ubuntu 20.04

**Comment by Kitzunu** [comment]
can you reproduce  it?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/6efc08f42e8ae731776517b187a79ba2ad546ec7/src/server/game/Entities/Pet/Pet.cpp#L556

cc @Winfidonarleyan

**Comment by mpfans** [comment]
> can you reproduce it?

sry... no

**Comment by mpfans** [comment]
There have been several crashes in recent days, but I don't know if this reason is only once
