### ISSUE TITLE
[Mage][Talent] Finger of Frost / Ghost charge (FoF shatter combo)

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11338]
### Current Behaviour

- Ghost charge not working.

### Expected Blizzlike Behaviour

- Should be able to weave in a 3rd spell on a FoF proc which you can clearly see on this [video](https://youtu.be/8ET2Ct9_Ma8?t=117), slow it down to 0.5 and watch the mage do fb (proc) > fb > fb > deep freeze combo on a single proc. Mentioned this on my previous post https://github.com/chromiecraft/chromiecraft/issues/2537 . I Think the way to make it work is to add a small delay to both the proc and consume which seems to be the case if you pay attention to the video ( This might be how procs worked in retaiI in general or this could all be purely a latency thing but I see this same "delay" as well when [Arcane concentration](https://wowgaming.altervista.org/aowow/?spell=12577) procs in other videos). Either way adding like a 300-500ms delay to both the proc and consume should fix this while also preventing issues like a consecutive FoF charge being consumed because of this "delay". It just has to be less than 1 second so you don't run into rare high haste occasion where ppl can weave in 2 abilities in that gap.

### Source

https://www.mmo-champion.com/threads/641024-FrostBite-Fingers-of-Frost-question
>Also, if you have FoF, you can actually cast 2 Frostbolts, the last one followed up with an Ice Lance - because that casting the Ice Lance instantaneously after the Frostbolt, you can practically achieve the shatter bonus three times, creating a "third" FoF charge.

>No, the charge is consumed on spell cast. The reason you can fit an Ice Lance in is network lag.
The FoF Shatter is basically a bug, as it goes directly against the talent tooltip that clearly states "your next 2 spells cast".
A normal Shatter combo relies on travel time, a game mechanic, to work, but this one can be impossible to pull to a player with the wrong amount of latency. Hence, if Blizzard intends for our DPS to be balanced around this, they have to make it more clear. The people over at EJ (Lhivera especially) are considerably vocal against this mechanic.

https://www.mmo-champion.com/threads/710176-Ghost-fingers-of-frost

>It works the same way as queueing spells, you get a FoF proc, frostbolt, frostbolt->ice lance. It actually works better on frostbite/novas, as you can FB-IL-IL if you have enough haste and are far enough away. It's pretty cute.
The idea is to cast it while you still have the buff or they still have the debuff. Latency is a factor, but you don't need particularly low latency, just not like, 800.

https://www.youtube.com/watch?v=8ET2Ct9_Ma8 Throughout this video you can see examples of everything I described happening including Frostbite always proccing with FoF. This is noticeable because every time you see the "Deep Freeze" yellow text (which represents a FoF proc) you also see an "immune" on the boss since you can't freeze bosses.

>A mage can use a "third" charge due to network latency. This is faciliated by using a spell with a [cast time](https://wowpedia.fandom.com/wiki/Casting_speed) greater than then [GCD](https://wowpedia.fandom.com/wiki/GCD) to consume the second charge, and then using an instant cast spell [Deep Freeze] or  [Ice Lance] are the best options for this) right as the spell finishes casting.

2 video sources were provided by [this comment in the CC Discord](https://discord.com/channels/788063059926712341/825732076975554571/958413698047807598): [1](https://www.youtube.com/watch?v=4X-GB9GB7Ic) and [2](https://www.youtube.com/watch?v=lr-ghl-CEL8)

[Another Post](https://www.mmo-champion.com/threads/704461-3-3-3-Mage-PvE-Guide-to-Frost-Basics)
>What ghosting FoF means is you can use an instant cast directly after using the second charge of your FoF proc, effectively applying 3 charges to your spells. Doing so will increase the crit chance of all spells cast by 50% and allow for you to use DF, your 30 second atomic bomb.]

Edit:
>Since Frostfire Bolt benefits from Ice Shards and Shatter, it is ideal to use its instant-castability immediately after the second Frostbolt during a Fingers of Frost proc.  Since the last Fingers of Frost charge is not consumed until the second spell hits the target, both the Frostbolt and the Frostfire Bolt will benefit from Fingers of Frost, resulting in what is commonly known as a Shatter Combo. ([source](https://frostisthenewblack.wordpress.com/2010/01/19/3-3-frost-mage-raiding-cheat-sheet/))

### Steps to reproduce the problem

1. Go to a dummy with only Fingers of Frost specced,
2. When at only 1 charge of Fingers of Frost, attempt (and fail) to cast Deep Freeze.

### Extra Notes

Originally Reported: https://github.com/chromiecraft/chromiecraft/issues/3123

Edit: Comment made by the original poster [bonfax4](https://github.com/bonfax4):

> [Spell batching guy you linked in discord](https://discord.com/channels/788063059926712341/825732076975554571/958502106191503450) made me do a little research and I think this might be an overall issue rather than just fingers itself. Spell queue which was introduced in tbc https://girlmeetswow.blogspot.com/2007/10/stopcasting-in-23-return-to-button.html . I believe this problem should be fixed once this is implemented. I had the idea this was added in cata but in cata they just added the ability to control to queue window rather than having a default value. I remember having to deal with the spell queue window interaction with instant casts to fully optimize boomkin gameplay in cata in order to make better use of eclipses and the behavior would make sense if you apply the same logic to fingers. You can read about it [here](https://web.archive.org/web/20110923151831/http://elitistjerks.com/f73/t110353-balance_cataclysm_4_2_a/#Advanced_Techniques) @ Advanced techniques section.
>Just tested on warmane pvp realm and fingers is fixed (wasn't back when i played there like a year ago) there and ghost charge does indeed work with the spell queue system implemented.
>Edit: You could maybe add a temporary/hackish fix and make it consume on-hit (while also making the cast that procs not consume its own proc) and it would behave mostly how it should behave btw. I don't see a spell queue system being added any time soon, not even accounting the amount of testing it would prob require as well.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Kitzunu** [comment]
are these two reports or just one? Because if this describes two different bugs, please open a new issue describing one bug per issue.

**Comment by Gultask** [comment]
Ah ok I was wondering if I should create 2 different reports.

**Comment by bonfax4** [comment]
I think a post for spell queuing needs to be made but either way [here's](https://wowhats.wordpress.com/2010/03/07/lag-wow-and-you/) some proof it did exist in wotlk. Also [here](https://www.mmo-champion.com/threads/638015-Spell-queuing)
