### ISSUE TITLE
[PvP] Leaving battleground sometimes doesn't clear dots/debuffs

### ISSUE THREAD

**Issue by Dejanos** [azerothcore/azerothcore-wotlk#11332]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Sometimes after battleground has ended and you are teleported back to the location you were before joining, dots/debuffs from battleground aren't cleared. Have had this happen on multiple characters and and multiple bgs, have even died couple times in Stormwind after being teleported back and the dots etc have been just doing their dmg.

### Expected Blizzlike Behaviour
Dots/debuffs should be cleared when exiting battleground as far as I know. I works so most of the time, but sometimes they just aren't cleared.

### Source

Blizzlike is to have all BG debuffs and enemy spells cleared from you and teleport back to your location with full health at the end of BG.

### Steps to reproduce the problem
1. Queue a Battleground on PTR or on Live.
2. Try to have a debuff/damaging dot on you when BG ends
3. Exit Battleground and check if you have a dot or a debuff on yourself.
### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3114

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@Dejanos I'm not sure if it's blizzlike. Can you send some proofs from Blizzard?

**Comment by Dejanos** [comment]
> @Dejanos I'm not sure if it's blizzlike. Can you send some proofs from Blizzard?

I have been searching and looking at PvP videos for the past 3 hours, after not being able to find vanilla WOTLK videos that could match the profile, I started searching classic TBC ones, after being unable to find one, I settled for arenas. Best I could find is 
[Warlock losing harmful Priest dots upon leaving arena](https://youtu.be/2RsBShPnGBE?t=1160)
[Taking some damage after the end of the arena and unable to drop from 100% hp, even from the last tick of Garrote](https://youtu.be/2RsBShPnGBE?t=1642)
[Moonfire, Insect Swarm and Bleed effects being removed on leaving arena](https://youtu.be/2RsBShPnGBE?t=2075)

All the other BGs and arenas I watched (And I watched around 30 for this research were having players unable to drop below 100% hp upon the end of arena/bg) 

Will try to find more research if needed.

**Comment by Nyeriah** [comment]
I never died to a dot after leaving battlegrounds ever, I think it's safe to assume debuffs should go away

**Comment by UltraNix** [comment]
@Nyeriah But that DoT was applied on you after battleground?

**Comment by UltraNix** [comment]
@Nyeriah @Dejanos ??

**Comment by Dejanos** [comment]
> @Nyeriah @Dejanos ??

I gave my sources above, they are from arena in TBC, but it should be the same principle. Cannot find a video of a Battleground one. The person upon the end of the fight gets all harmful damaging debuffs removed, and slows/stuns/silences remain.
