### ISSUE TITLE
Update latest supported MySQL version

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1134]
Currently the latest version of MySQL that we officially support is 5.6.

This version is supported by Oracle until **February 2021**, see: https://en.wikipedia.org/wiki/MySQL#Release_history

We should update it  before that date.

![image](https://user-images.githubusercontent.com/75517/50343475-51750e00-0527-11e9-8bc4-8187c74e9649.png)

**Comment by Viste** [comment]
As i see in https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/cmake/macros/FindMySQL.cmake we support 5.7 and to add 8.0

**Comment by FrancescoBorzi** [comment]
@viste the problem is not only the script to find the library, but the format of some sql queries. Currently it is possible to use 5.7 with azerothcore, but you have to override the default sql mode. We should make it work out of the box.

**Comment by Viste** [comment]
oh I understood, did not look into queries.
start full research after new yr and open pull with updates
Also i guess need add mariadb support ( i use 10.2 with sunwell and az without problems but 10.3 as i remember get errors on build)

**Comment by FrancescoBorzi** [comment]
Tracking issues that prevents usage of MySQL 5.7 with https://github.com/azerothcore/azerothcore-wotlk/labels/MySQL%205.7%20support

**Comment by FrancescoBorzi** [comment]
@Viste FYI: I linked a couple of issues with that tag. However, I think that in order to be fully compatible with 5.7 we also need to merge the sql updates into the main file after them.

**Comment by FrancescoBorzi** [comment]
we should deprecate mysql <= 5.5. since it's no longer supported, see this commit: https://github.com/TrinityCore/TrinityCore/commit/33c723685f5fe86644c5fecfcad0b7a8bed8e15d
