### ISSUE TITLE
[server] world carsh 0410

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11347]
### Current Behaviour

crash log 

https://gist.github.com/mpfans/06340b95ce498c2f4500879041c8607a

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68

### Operating system

ubuntu 20.04

**Comment by UltraNix** [comment]
#11281
