### ISSUE TITLE
[server]world crash 

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11368]
### Current Behaviour

crash log:

https://gist.github.com/mpfans/e7ce32c6f3981b07250b15b8a75738c4

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68  + PR (https://github.com/azerothcore/azerothcore-wotlk/pull/11346)

### Operating system

ubuntu 20.04

**Comment by UltraNix** [comment]
No usefeull info in this crashlog.
