### ISSUE TITLE
Clean pending group invites

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1136]
##### SMALL DESCRIPTION:

Issue for https://github.com/azerothcore/azerothcore-wotlk/pull/892

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Remove pending group invites when we can't invite someone to a group (if group has just been disbanded)
Remove pending group invites when we can't invite someone to a group (full group)

##### CURRENT BEHAVIOUR:

Not happening

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

fffb925201894029748d5e53a6c78f2511858003

**Comment by Kitzunu** [comment]
on current retail how it works is:

If you are in a group with another player and invite a third.
Then before the third accepts you disband the group.
When the third then accepts, no group will be formed
