### ISSUE TITLE
[Hunter] Rapid Recuperation talent forces character to stand up

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#11365]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/3325

Each mana tick from the 'on kill' effect of the Rapid Recuperation talent forces your character to stand up, if your character was sitting down.

This has the side effect of 'canceling' attempts to eat/drink until Rapid Recuperation wears off.

[AoWoW database link to Rapid Recuperation talent.](https://wowgaming.altervista.org/aowow/?spell=53232)

[AoWoW database link to the 'on kill' mana restoration effect of the talent.](https://wowgaming.altervista.org/aowow/?spell=58882)

[AoWoW database link to the Rapid Killing talent, which is required for the 'on kill' portion of Rapid Recuperation to work.](https://wowgaming.altervista.org/aowow/?spell=34949)

Tester:

The issue is confirmed on local AC.

### Expected Blizzlike Behaviour

Mana ticks from the 'on kill' effect of the Rapid Recuperation talent should _not_ force your character into a standing position.

### Source

(Having trouble finding video evidence for this one)

### Steps to reproduce the problem

Original report:
Spec into Rapid Killing and Rapid Recuperation.

Trigger the 'on kill' effect of Rapid Recuperation by killing a target that yields experience/honor, then attempt to sit down and/or eating/drink while Rapid Recuperation is restoring your mana.

Notice how every mana tick of Rapid Recuperation forces your character back into a standing position, which cancels any eating/drinking you were attempting to do.

Tester:
1. Learn Rapid Recuperation talent
2. Kill enemy that yields experience
3. Sit down
4. Character stands up at every mana regeneration tick

### Extra Notes

Tested as a female night elf hunter.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Works okay.
