### ISSUE TITLE
[Hunter] Lock and Load talent not proccing

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#11363]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/3044

I have spent around 20 minute trying to get a proc of Lock and Load from the spells mentioned in the title, but I had no luck. It has a 6% proc rate according to talents:

![image](https://user-images.githubusercontent.com/36760053/153835663-cd2f7418-7475-411a-9df5-e8dd5f664642.png)

I tested it on the training dummies in Orgrimmar. Proc works perfectly with Freeze and Frost Traps.

Tester:

I can confirm that the talent does not proc from Black Arrow, Immolation Trap and Explosive Trap.

There was a fix https://github.com/azerothcore/azerothcore-wotlk/pull/8441 for Frost Trap in past.

### Expected Blizzlike Behaviour

According to the talent description, it should work. 

### Steps to reproduce the problem

1. Roll a survival hunter
2. Talent Lock and Load
3. Try to use Black Arrow/Immolation Trap/Explosive Trap on NPC (I used target dummy)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by pklloveyou** [comment]
``` UPDATE `spell_proc_event` SET `procPhase`=0 WHERE `entry` = -56342; ```

**Comment by avarishd** [comment]
Linked with: https://github.com/azerothcore/azerothcore-wotlk/issues/10919 

Setting PPM, as Pklloveyou suggested, to 0 (taken from DBC) corrects the issue.

**Comment by UltraNix** [comment]
Fixed by #11862
