### ISSUE TITLE
[Zul'Gurub] High Priestess Jeklik - Bats issues in P2

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#11379]
### Current Behaviour

In P2, some bats not targetable that stay at the floor.

<details>

![WoWScrnShot_041222_165012](https://user-images.githubusercontent.com/100411212/163015402-1efb7f78-5fc2-47f0-8731-66605e329311.jpg)

</details>

### Expected Blizzlike Behaviour

In P2, some bats stay in the air (not targetable) and launch Throw Liquid Fire.

### Source

https://youtu.be/KEzw9Hc_UhU?t=192 - You can see a bat to launch a Liquid Fire

https://youtu.be/xVvvRa_TEEg?t=99 - You see any bats at the floor during the P2

### Steps to reproduce the problem

Engage Jeklik and go in P2

### AC rev. hash/commit

e13f427

### Operating system

Windows 11

**Comment by Lynethris** [comment]
Wait for more researches. I have found this in wow fandom : "She will eventually start to summon bats that drop bombs on your raid."
