### ISSUE TITLE
Warrior Class Call debuff gets applied to all classes and they all take 30% increased damage, Warriors are not stuck in Berserker Stance

### ISSUE THREAD

**Issue by Dejanos** [azerothcore/azerothcore-wotlk#11375]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour
Warrior Class Call debuff from Nefarian affects all members currently, and increases damage they take by 30%

Rogue being affected by Warrior Class Call.
![WoWScrnShot_041222_000935](https://user-images.githubusercontent.com/100415626/162945251-bf91d8c3-5adb-40c6-bfc2-26862972f7a3.jpg)

Rogue taking 30% increased damage in Combat Log after being affected by  Warrior Class Call debuff,
![warr class call](https://user-images.githubusercontent.com/100415626/162945369-55ccea6c-d048-4b99-9f6e-7d5046b5d3fc.png)

Also: Warriors are not stuck in Warrior Berserker Stance on Warrior Class Call, they have no stance selected.

Warrior has no stance on Warrior Class Call.
![WoWScrnShot_041222_001705](https://user-images.githubusercontent.com/100415626/162945518-9b3e16c5-8c45-4dcf-8c5b-09dfc572ddb1.jpg)

### Expected Blizzlike Behaviour

    1. Only Warriors should get Warrior Class Call debuff from Nefarian.
    2.  Warrios should be stuck in Berserkers Stance instead not having any stance at all on Warr Class Call.
    3.  At the end of the debuff Warriors must manually return to their desired stance as provided in the video.

### Source
Only Warrs should be affected by Warrior Class Call debuff.
[Warrior stuck in Berserker stance on Warrior Class Call.](https://youtu.be/ljhnqPRRyME?t=226)
### Steps to reproduce the problem

   1. Enter BWL.
   2. Engage Nefarian.
   3. Watch all raid members getting Warrior Class Call debuff and 30% increased damage.
   4. See Warrior not getting stuck in Berserker Stance on Warr Class call, instead it has no stance selected at all.

### Extra Notes
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3334

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/11384
