### ISSUE TITLE
Chicken in Southshore has bad coordinates

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11373]
Originally Reported: https://github.com/chromiecraft/chromiecraft/issues/3320

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Chicken stands and walks on top of the shroud of the Southshore stables
![image](https://user-images.githubusercontent.com/38561765/162650225-4fe1d147-8887-4e4a-8dc9-7ecd45672de0.png)
![image](https://user-images.githubusercontent.com/38561765/162650213-0593cf98-f4bb-457d-b8a6-fac9061c91e0.png)

### Expected Blizzlike Behaviour

Chicken should not be on the roof.

### Source

[This video from WoW Classic does not show a chicken on the roof.](https://youtu.be/xM6DNc4glHw?t=3787)
Chicken was not placed on the roof in TBC Classic:
![image](https://user-images.githubusercontent.com/38561765/162846149-694bc815-9365-4ca7-bbdb-412a8fadc084.png)

### Steps to reproduce the problem

1. Teleport to Southshore in Hillsbrad Foothills/.go creature 15403
2. Walk to the east-most building in Southshore (The stables)
3. Observe the chicken on the roof

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Fixed by 7a99e0ba82db88da2b632d701acdacb900b0b8be.
