### ISSUE TITLE
[Quest][Darkshore][NPC: Grimclaw / Terenthis] Grimclaw erratically spawning and undergoing its RP event.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11374]
### Current Behaviour

Grimclaw (ID: 3695) spawns and undergoes its rp event with Terenthis without any quests being completed and turned in. Turning in How Big a Threat 2/2 (ID: 985) will spawn another one, possibly breaking the event and leading to unresponsive quest giver.

### Expected Blizzlike Behaviour

Grimclaw (ID: 3695) should only spawn once, after turning in How Big a Threat 2/2 (ID: 985) to Terenthis.

### Source

(https://youtu.be/pa4SuHwKULM?t=2710) shows the proper spawning location of Grimclaw, which is inside Auberdine, not in the Grove of the Ancients.

### Steps to reproduce the problem

1. `.list c 3695` `.go c GUID` and find a Grimclaw spawned by itself
2. `.quest add 985` `.quest complete 985` `.go q ender 985` and turn in
3. go down the road to Ashenvale and find other Grimclaws spawned with no GUID

### Extra Notes

Originally Reported in: https://github.com/chromiecraft/chromiecraft/issues/3188 https://github.com/chromiecraft/chromiecraft/issues/3313 https://github.com/chromiecraft/chromiecraft/issues/3216 https://github.com/chromiecraft/chromiecraft/issues/3296

NPC info of a broken Grimclaw that spawned by itself, going the wrong way with broken pathing
![WoWScrnShot_041222_004657](https://user-images.githubusercontent.com/100873791/162877373-a7b50412-531c-445f-b997-160df20dfec9.jpg)

NPC info of one of the Grimclaws spawned after turning in quest 985
![WoWScrnShot_041222_004525](https://user-images.githubusercontent.com/100873791/162877561-e8c2054f-6e40-49f5-909c-3fd544be4ea6.jpg)

NPC info of the other Grimclaw spawned after turning in quest 985
![WoWScrnShot_041222_004610](https://user-images.githubusercontent.com/100873791/162877638-fe7eeddf-388e-40da-b7f5-9c82cb9b0b41.jpg)

`.list 3695` only lists 1 Grimclaw, which is the one with the broken pathing that spawned by itself

Possibly related to: https://github.com/azerothcore/azerothcore-wotlk/pull/10926, https://github.com/azerothcore/azerothcore-wotlk/pull/9714

Edit: The video in https://github.com/azerothcore/azerothcore-wotlk/pull/9714 (https://github.com/azerothcore/azerothcore-wotlk/pull/9714#issuecomment-1008463056) leads me to believe that Grimclaw is also spawning at the wrong 'end' of its route. Currently, Grimclaw spawns near the Grove of the Ancients in south Darkshore and walks all the way to Auberdine, delaying the rp event with Terenthis. After the dialogue Grimclaw currently despawns at the same location it spawned in the video.

I should also list the related quests in case someone decides to search for them: How Big a Threat, A Lost Master, Escape Through Force, Escape Through Stealth, Thundris Windweaver, Sentinel Selarin, Trek to Ashenvale.

**Edit 2:**
https://youtu.be/pa4SuHwKULM?t=2710 shows the proper behaviour for the quest, Grimclaw spawns nearby, not near the Grove of the Ancients,

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0e35b681fb74045953b0babae5273f121dcaa05f

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by htc16** [comment]
This problem is confirmed.
