### ISSUE TITLE
[Zul'Gurub] High priestess Jeklik - Missing spells

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#11381]
### Current Behaviour

Actually, the boss cast Sonic burst and terrifying screech in P1.

Not cast Curse of Blood in P2.

![WoWScrnShot_041222_175724](https://user-images.githubusercontent.com/100411212/163004380-a62954c5-ebd8-4539-a9fe-981363e56c9f.jpg)

### Expected Blizzlike Behaviour

She should cast Sonic burst, Swoop, Pierce armor and blood leech in P1 and Curse of Blood in P2.

To Do:

- Adds Swoop (https://classic.wowhead.com/spell=18144/swoop), Pierce armor (https://classic.wowhead.com/spell=6016/pierce-armor), and blood leech (https://classic.wowhead.com/spell=22644/blood-leech)

- Add Curse of blood in P2 (https://www.wowhead.com/spell=16098/curse-of-blood)

### Source

https://wowpedia.fandom.com/wiki/High_Priestess_Jeklik_(tactics)

https://youtu.be/ZJoKmit_ess?t=1

### Steps to reproduce the problem

Engage Jeklik and look logs chat in everythings

### Extra Notes

IDs from Wowhead are maybe not good because spells seems duplicate wich differents values

_No response_

### AC rev. hash/commit

e13f427

### Operating system

Windows 11

**Comment by Lynethris** [comment]
Updated with one spell missing in P2 (Curse of blood)
