### ISSUE TITLE
Unable to change realm after entering to one of them.

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#11388]
### Current Behaviour

Unable to change realm after entering to one of them. But if you not entered to world, you can choose and enter to one of the listed realms 

See video

https://discord.com/channels/217589275766685707/284323424032129024/963712657146388490

### Expected Blizzlike Behaviour

You can choose and enter to one of the listed realms in any time if went out from the other realms

### Steps to reproduce the problem

1. start one server with ID 1 and port 8585
2. start second server with ID 2 and port 8586
3. add realms to realmlist table of auth database
4. log in to auth section
5. now you can choose the server and switch between them
6. enter to one of them and leave it to previous screen
7. now you can't switch the servers.
8. If you completelly log out and login again - you will be able to switch servers.

### AC rev. hash/commit

AzerothCore rev. e13f4271897e+ 2022-04-11 17:04:42 +0000

### Operating system

Win7 x64

### Custom changes or Modules

none

**Comment by Meltie2013** [comment]
The cause when you try to switch realms after logging into the world first.

https://github.com/azerothcore/azerothcore-wotlk/blob/4ac565699fcb7b88fcc15db97ec9f14a0894f331/src/server/authserver/Server/AuthSession.cpp#L850

Fix to solve this issue.
```cpp
Acore::Crypto::SHA1::Digest zeros = { };
```

**Comment by Bogir** [comment]
> ```c++
> Acore::Crypto::SHA1::Digest zeros = { };
> ```

Tested and works!

Could you open the PR ?
