### ISSUE TITLE
[Death Knights] DK's `Summon Gargoyle`

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11387]
### Current Behaviour

DK's `Summon Gargoyle` (spell 49206)

Gargoyle's damage value is too low.without DK's attack power

![image](https://user-images.githubusercontent.com/18187177/163121191-cc6a8dc5-a688-4740-a9e0-9b5761489bbe.png)

### Expected Blizzlike Behaviour

![image](https://user-images.githubusercontent.com/18187177/163119709-2d41a535-4bdb-436e-8cc3-8ea3b730edd1.png)

A Gargoyle flies into the area and bombards the target with Nature damage modified by the Death Knight's attack power.

### Source

https://www.wowhead.com/spell=49206/summon-gargoyle#comments
```
Current status of gargoyle:
-scales with all physical haste benefits at the same rate as the player
-attack power coefficient is 0.4
-base damage per strike is 120
-does not inherit any crit from the player
-does not inherit any +damage % modifiers from the player, such as bone shield, desecration, or blood presence
-player stats are taken as a snapshot when the gargoyle is launched; that is, when you cast this spell, however much attack power and haste is the amount your gargoyle strikes will be basing themselves off of.

Based on extensive ingame testing done today, June 27th, 2009
```

### Steps to reproduce the problem

1.  `.learn 49206`
2.  `.cast 49206`
3. look gargoyle's damage value

### AC rev. hash/commit

a35e411fdd86f3b44e7b5f1a36b1ba2d43887a68

### Operating system

ubuntu 20.04

**Comment by r0m1ntik** [comment]
Confirm

**Comment by mpfans** [comment]
> 

tested,work.. Please submit a PR, thank you!
