### ISSUE TITLE
Naxxramas - Incorrect conversation between Kel'Thuzad and The Lich King/Incorrect timing on triggering convo/door open

### ISSUE THREAD

**Issue by NizeGuy** [azerothcore/azerothcore-wotlk#1138]
##### SMALL DESCRIPTION:

Upon killing Sapphiron, the Lich King and Kel'thuzad don't start speaking until you reach the door to Kel'thuzad that is open.  The wrong text appears as well as the wrong sound files.  Ex:

https://i.stack.imgur.com/9LhDp.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The conversation should be triggered with Sapphiron's death, not walking up to Kel'thuzad's door.  Kel'thuzad's door should be closed until the conversation is over.  The correct text for the conversation is:

> Kel'Thuzad yells: Your forces are nearly marshalled to strike back against your enemies, my liege.
> The Lich King yells: Soon we will eradicate the Alliance and Horde, then the rest of Azeroth will fall before the might of my army.
> Kel'Thuzad yells: Yes, Master. The time of their ultimate demise grows close... What is this?
> The Lich King yells: Invaders...here?! DESTROY them, Kel'Thuzad! Naxxramas must not fall!
> Kel'Thuzad yells: As you command, Master!
> Kel'Thuzad yells: Come, heroes... By the will of the Lich King, you shall be destroyed.

The correct sound files are:
Sound/Creature/Kelthuzad/Na_Kelthuzad_Dialogue01.ogg
Sound/Creature/Lichking/Na_Lichking_Dialogue01.ogg
Sound/Creature/Kelthuzad/Na_Kelthuzad_Dialogue02.ogg
Sound/Creature/Lichking/Na_Lichking_Dialogue02.ogg
Sound/Creature/Kelthuzad/Na_Kelthuzad_Dialogue03.ogg

(in that order)

##### CURRENT BEHAVIOUR:
When you kill Sapphiron, you won't trigger the LK/KT audio or emotes until you walk to the door.  It has LKs Valirithia Dreamwalker intro text, and Vanilla LK's voice audio is heard.
The door is wide open when it should be closed until the end of the conversation.

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Kill Sapphiron
2.  Walk to Kel'thuzad's door
3.  Watch/Listen for emote and speech

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
#fffb925

##### OPERATING SYSTEM:
Win10

**Comment by poszer** [comment]
I'll post fix tonight when i come home

**Comment by Dreaxxx** [comment]
poszer , do you know how to make blizzlike like 3.0 with the activation of ramp in Naxxramas for accessing Sapphiron and Kelthuzad only after the 4 wings down ?

**Comment by poszer** [comment]
> poszer , do you know how to make blizzlike like 3.0 with the activation of ramp in Naxxramas for accessing Sapphiron and Kelthuzad only after the 4 wings down ?

If there is problem with it, open Issue and describe problem

**Comment by ColdIronWow** [comment]
I don't see anything from @poszer, so I'm going to give this a shot.  It looks like all the correct lines are present in the DB but we're triggering the wrong ones in code.  The door also opens on Sapphiron's death, instead of at the conclusion of the voicelines.
