### ISSUE TITLE
Faction change - Brown Kodo doesn't get removed/exchanged

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#11383]
### Current Behaviour

When faction changing from Horde to an Alliance race the mount Brown Kodo doesn't get exchanged/removed.

### Expected Blizzlike Behaviour

It should be removed or exchanged. (Needs research)

### Source

I have never seen an night elf with a brown kodo on retail.

### Steps to reproduce the problem

1. Make Horde
2. Get Brown Kodo
3. Faction Change

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e13f4271897efa089466fdb633f9a1d9c55feb53

### Operating system

Windows 10

**Comment by Gultask** [comment]
![WoWScrnShot_042622_070337](https://user-images.githubusercontent.com/100873791/165276236-248a5047-3e58-498f-8b01-3bafd05cda46.jpg)

Yup, can confirm in a local AC

**Comment by Gultask** [comment]
Uhh.

![WoWScrnShot_042622_072436](https://user-images.githubusercontent.com/100873791/165279890-85f027ed-2df8-451a-9e07-2eea213682d3.jpg)
