### ISSUE TITLE
Update quest_template 

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#11393]
### Current Behaviour

Doing a comparison with TC I found several changes in the quest_template table

### Expected Blizzlike Behaviour

- ID: 183 LogDescription: (FIX https://github.com/azerothcore/azerothcore-wotlk/pull/11394/commits/810d9210677c5d791971943c7310ff3b9637bfde)

ACore: Talin Keeneye would like you to kill 8 Small Crag Boars.
TCore: Talin Keeneye would like you to kill 12 Small Crag Boars.

- ID: 287 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Senir Whitebeard at Kharanos in Dun Morogh.
TCore: Return to Senir Whitebeard at Shimmer Ridge in Dun Morogh.

- ID: 317 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Pilot Bellowfiz at Steelgrill's in Dun Morogh.
TCore: Return to Pilot Bellowfiz at The Tundrid Hills in Dun Morogh.

- ID: 416 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Mountaineer Kadrell at Thelsamar in Loch Modan.
TCore: Return to Mountaineer Kadrell at Grizzlepaw Ridge in Loch Modan.

- ID: 543 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Count Remington Ridgewell at Stormwind Keep in Stormwind City
TCore: Return to Count Remington Ridgewell at Northshire Valley in Elwynn Forest.

- ID: 806 QuestCompletionLog: (FIX https://github.com/azerothcore/azerothcore-wotlk/pull/11394/commits/4ca6f1bf800c2b8c1e2750041af0fc85094bf8b2)

ACore: Did you find Fizzle, $N? He, and rest of the Burning Blade, must be scoured from our lands!
TCore: Return to Orgnil Soulscar in Durotar.

- ID: 932 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Tallonkai Swiftroot at Dolanaar in Teldrassil.
TCore: Return to Tallonkai Swiftroot at Lake Al'Ameth in Teldrassil.

- ID: 1013 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Keeper Bel'dugur at Apothecarium in the Undercity.
TCore: Return to Keeper Bel'dugur at Lordamere Lake in Alterac Mountains.

- ID: 1195 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Zangen Stonehoof in Thunder Bluff.
TCore: Return to Zangen Stonehoof at The Golden Plains in Mulgore.

- ID: 1886 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Mennet Carkad at Undercity in the Rogues' Quarter.
TCore: Return to Mennet Carkad at Ruins of Lordaeron in Tirisfal Glades.

- ID: 1899 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Mennet Carkad at Undercity in the Rogues' Quarter.
TCore: Return to Mennet Carkad at Ruins of Lordaeron in Tirisfal Glades.

- ID: 2199 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Talvash del Kissel at the Mystic Ward in Ironforge.
TCore: Return to Talvash del Kissel in Wetlands.

- ID: 2204 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Talvash del Kissel at the Mystic Ward in Ironforge.
TCore: Return to Talvash del Kissel in Wetlands.

- ID: 2459 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Tallonkai Swiftroot at Dolanaar in Teldrassil.
TCore: Return to Tallonkai Swiftroot at Lake Al'Ameth in Teldrassil.

- ID: 5283 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Grumnus Steelshaper in Ironforge.
TCore: Return to Grumnus Steelshaper in Dun Morogh.

- ID: 6024 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Mound of Dirt in The Eastern Plaguelands
TCore: Return to Mound of Dirt in The Hinterlands.

- ID: 6561 QuestCompletionLog :_(OK no change in AC)_

ACore: Return to Bashana Runetotem at Elder Rise in Thunder Bluff.
TCore: Return to Bashana Runetotem at The Golden Plains in Mulgore.

- ID: 7461 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Shen'dralar Ancient in Dire Maul.
TCore: Return to Shen'dralar Ancient at Dalaran Crater in Alterac Mountains.

- ID: 8355 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Talvash del Kissel at the Mystic Ward in Ironforge.
TCore: Return to Talvash del Kissel in Wetlands.

- ID: 9339 LogDescription: _(OK no change in AC)_

ACore: Return the Flame of Stormwind to (NAME).
TCore:

- ID: 9339 QuestDescription: _(OK no change in AC)_

ACore: This flame, stolen from the heart of Stormwind itself, floods you with warmth. This raw power is foreign to you, but the (NAME) might know more...
TCore:

- ID: 9365 LogDescription: _(OK no change in AC)_

ACore: Return the Flame of Stormwind to (NAME).
TCore:

- ID: 9365 QuestDescription: _(OK no change in AC)_

ACore: This flame, stolen from the heart of Stormwind itself, floods you with warmth. This raw power is foreign to you, but the (NAME) might know more...
TCore:

- ID: 12032 AreaDescription: _(OK no change in AC)_

ACore:
TCore: Oacha'noa's compulsion obeyed.

- ID: 12032 ObjectiveText1: _(OK no change in AC)_

ACore: Oacha'noa's compulsion obeyed
TCore:

- ID: 14351 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Bragor Bloodfist at the Royal Quarter in the Undercity.
TCore: Return to Bragor Bloodfist at Lordamere Lake in Silverpine Forest.

- ID: 14352 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Bragor Bloodfist at the Royal Quarter in the Undercity.
TCore: Return to Bragor Bloodfist at Lordamere Lake in Silverpine Forest.

- ID: 14356 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Bragor Bloodfist at the Royal Quarter in the Undercity.
TCore: Return to Bragor Bloodfist at the Royal Quarter in Undercity.

- ID: 14418 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Aleric Hawkins at Undercity in the Hall of the Dark Lady.
TCore: Return to Aleric Hawkins at Lordamere Lake in Silverpine Forest.

- ID: 14419 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Andron Gant at Undercity in the Apothecarium.
TCore: Return to Andron Gant at Lordamere Lake in Alterac Mountains.

- ID: 14420 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Mennet Carkad at Undercity in the Rogues' Quarter.
TCore: Return to Mennet Carkad at Ruins of Lordaeron in Tirisfal Glades.

- ID: 14421 QuestCompletionLog: _(OK no change in AC)_

ACore: Return to Mennet Carkad at Undercity in the Rogues' Quarter.
TCore: Return to Mennet Carkad at Ruins of Lordaeron in Tirisfal Glades.

### Source

TrinityCore Database 3.3.5

### Steps to reproduce the problem

*

### Extra Notes

I will check the differences one by one, with external links like wowhead, and other pages

### AC rev. hash/commit

AzerothCore rev. 4ac565699fcb 2022-04-13 11:57:04 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04

**Comment by Kosiak** [comment]
Id 416 it was fixed by me and its correct. So every single one needs to be checked not ac vs tc but with sources from internet.

**Comment by Kitzunu** [comment]
This should be referenced by real sources. Not just copy paste from TC. Use Wayback machiene and check wowhead via that.

**Comment by Tony931023** [comment]
https://github.com/TrinityCore/TrinityCore/issues/27913

**Comment by Ovahlord** [comment]
This happens when people without sniffs keep touching things that have been verified via sniffs. The quest template is one of the holy tables that nobody is allowed to touch once it's been set up. Most of Trinity's entries are in fact correct. However, even they do have a couple mismatches in completionlogs because some modifications slipped under the rug.

https://gist.github.com/Ovahlord/7508b507dcdbce01d7ca7513706d2eef there. These are official sniffed values so feel free to compare them and be surprised that most of ACs changes were once again wrong.

And for the love of god, never ever blindly trust anything on WoW head. Especially the old WoWhead was full of fake und unreliable data

**Comment by Bogir** [comment]
> And for the love of god, never ever blindly trust anything on WoW head. Especially the old WoWhead was full of fake und unreliable data

So, what we should answer to players, who refer to the WoWhead in their bugreports? "We will not fix it because provided info on WoWhead may be fake!"?

**Comment by Kosiak** [comment]
@Ovahlord  (416,'Bring 8 Tunnel Rat Ears to Mountaineer Stormpike in Algaz Station.',
https://wowpedia.fandom.com/wiki/Rat_Catching
Everything wrong on this one so how can we trust anything else.

**Comment by Kitzunu** [comment]
@Kosiak actually, sniffed values are never wrong. And the wowpedia link is from current state of wow, not from wotlk

**Comment by Kosiak** [comment]
> @Kosiak actually, sniffed values are never wrong. And the wowpedia link is from current state of wow, not from wotlk

I never said sniffs are wrong. I said the text he provided is wrong. Any information u will find in there classic, tbc, present wowhead, wowpedia, wowwiki any youtube videos state all same info. From the time they added that quest it was 12 ears and quest giver was Mountaineer Kadrell in Thelsamar. There is disscusion i had with Lukas on pr for that quest. [LINK](https://github.com/azerothcore/azerothcore-wotlk/pull/11008)

**Comment by Tony931023** [comment]
If we can't trust wowhead to catch any bugs then we're lost as most users look for information there for any bugs.
mission 416 has no modifications according to what I had said that it did not need changes in AC.
the mission that needed changes was 183 that had an error in the description of the objectives that were not kill 8 Small Crag Boars, but 12 Small Crag Boars,

Only you can decide if it's right or wrong
