### ISSUE TITLE
Combos Points In Malygos P2

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#1140]
##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Eye of Eternity 10 or 25 players 
2.  Engage Malygos
3. Go to P2 and take a disk with combos points class

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

2d57529

##### OPERATING SYSTEM:

Debian 9

##### Other Descriptions: I'v find this fix on trinitycore project about the same problem 
https://github.com/TrinityCore/TrinityCore/pull/19914/commits/41352915516f803fddbe3833216fb3280a2219c5

**Comment by Pondaveia** [comment]
This included fix wont do. The Player AI is different from TC to AC. Simply importing won't do you need to script this differently.
