### ISSUE TITLE
[BWL] Broodlord Lashlayer does not have random cooldowns on Mortal Strike, Blast Wave

### ISSUE THREAD

**Issue by manacute** [azerothcore/azerothcore-wotlk#11407]
### Current Behaviour

After the initial lower cooldowns, Broodlord uses both abilities on set intervals.

### Expected Blizzlike Behaviour

Abilities should have a small range for cooldowns.

### Steps to reproduce the problem

1. Fight Broodlord
2. Count how long it takes between Mortal Strikes and Blast Waves

### Extra Notes

Tested on ChromieCraft PTR, occurred on live server as well. I think the issue stems from [line 109 and 113](https://github.com/azerothcore/azerothcore-wotlk/blob/4dcab1f7bc706701a5e4756e1b5e87533502da42/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_broodlord_lashlayer.cpp#L109) of Broodlord's scripts, as most ScheduleEvent calls seem to use urand() to pass the cooldown time as a single argument, instead of passing the minimum and maximum separately.

### AC rev. hash/commit

2f5a5dffcb5ec1b718a16e6a6f4ea0ea9fc6f37f

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by Lynethris** [comment]
We need sources before for confirm the issue. Please repport this before on CC bugtracker for be confirm by triager.

**Comment by Lynethris** [comment]
Sorry I have misunderstund your post. I have record 2min of fight with broolord for count the delay: https://youtu.be/ihJHpj6hNBU

Time code for:
- Cleave: 0:00 / 0:8 / 0:15 / 0:21 / 0:29 / 0:35 / 0:43 / 0:49 / 0:57 / 1:05 / 1:11 / 1:18 / 1:25 / 1:31 / 1:39 / 1:45 / 1:53 / 1:57 / 2:07
- Mortal strike: 0:11 / 0:16 / 0:36 / 0:41 / 1:01 / 1:28 / 1:31 / 1:52 / 1:56

Resume delay between two cast:
- Cleave: 8 / 7 / 6 /  8 / 6 / 8 / 5 / 8 / 8 / 6 / 7 / 7 / 6 / 8 / 6 / 8 / 4 / 10 
- Mortal strike: 11 / 5 / 15  / 5 / 19 / 27 / 3 / 21 / 4
