### ISSUE TITLE
Big list of commits to port from other projects [$200]

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1141]
**This is barely formatted, if someone from the team wants to edit this and make it look organized and clean, go on.**

This is a list of commits to port from other projects (mangos, trinity, or any core in fact).

# SUNWELL CORE (Maczuga's)

- [ ] https://github.com/Maczuga/SunwellCore/commit/9fb7429c4310c218a0adbdda45b174ff2db9eb11 Note: with this commit, you will see a buggy hp in princes in ICC so take care
- [ ] https://github.com/Maczuga/SunwellCore/commit/5d9826cac236af7f4601e55f4b10e666fc2f8ebb
- [x] https://github.com/Maczuga/SunwellCore/commit/bacf23abde1251fdc3245688f716403b03923a54
- [ ] https://github.com/Maczuga/SunwellCore/commit/fb94e1d061b58f74ada40aacc545ba9042caccfb
- [ ] https://github.com/Maczuga/SunwellCore/commit/fffefd59fa278b52a1a427479ba0a83024678356
- [x] https://github.com/Maczuga/SunwellCore/commit/5163f56b8242432ce30de204d109cdf59b933a95
- [x] https://github.com/Maczuga/SunwellCore/commit/045a5da4b9ae1909a74a2740151dbc918ffc983c
- [ ] https://github.com/Maczuga/SunwellCore/commit/b00da9c95ccbd5b8edb5d0c4b9a854c062ff7b7e
- [ ] https://github.com/Maczuga/SunwellCore/commit/0f9366b9bfbc73985faa397fe16fe982bb0dc2f2
- [ ] https://github.com/Maczuga/SunwellCore/commit/4cab5e60703d261357e48bd4929d6687cc51701c
- [ ] https://github.com/Maczuga/SunwellCore/commit/5eb4ca77d18de30048541273a68dee4e2af2717b
- [ ] https://github.com/Maczuga/SunwellCore/commit/4e308b87c7a6b09adb27bf00e0d8615302dca4b7
- [ ] https://github.com/Maczuga/SunwellCore/commit/998d1e6448641b6f0fb1da512c567558572010dc
- [x] https://github.com/Maczuga/SunwellCore/commit/0b3db851160db597e5967c101c19bd8fd9a31950
- [ ] https://github.com/Maczuga/SunwellCore/commit/afb89cb7c99fcd90c1fe4bf23f7b57395c8397e2
- [ ] https://github.com/Maczuga/SunwellCore/commit/31a60fdaab1eb4502821fd0dcf6d15bbf11e600e
- [x] https://github.com/Maczuga/SunwellCore/commit/7b1945a5621125111d31d7e4398dc8df94aedeb0
- [ ] https://github.com/Maczuga/SunwellCore/commit/8c11d41e56704f1ad8522cef1b0af2093f342463
- [x] https://github.com/Maczuga/SunwellCore/commit/ae300d8f8fa06b5c7a21ade9e9262e7ed2f1b9a9
- [ ] https://github.com/Maczuga/SunwellCore/commit/065336c79c94411520ac9ee908f59dd7fdbbaf3d
- [ ] https://github.com/Maczuga/SunwellCore/commit/ef25174df07d7fa282e5aaa6e79ee8c0bc0d819e
- [x] https://github.com/Maczuga/SunwellCore/commit/1fdbd9c27bed448b7607a2cacee914269e2bdf52

# TRINITY CORE

Not classified :
- [x] https://github.com/TrinityCore/TrinityCore/commit/a1f2f30c145f6ad9c4baeffeff32618e71ff537c & https://github.com/TrinityCore/TrinityCore/commit/2ff76e828f7c757b5120aba41947a6d63e082e17
- [x] https://github.com/TrinityCore/TrinityCore/commit/d57307f63d8deb51003d61163adccce4e2c1bd47 LOS problem
- [ ] https://github.com/TrinityCore/TrinityCore/commit/59db2eeea0a35028779fd76372ae06cc98c8086f Dynamic respawn NPC / GOB but there are MORE COMMITS fixing this feature on TC
- [ ] https://github.com/TrinityCore/TrinityCore/commit/dae3ae069651ed3f35f975091af59a33181ef0e0 On first login - Styx merged it without any problem
- [x] https://github.com/TrinityCore/TrinityCore/commit/7dfd472f8dff6ce067572e2887c2beb56d9ba9de Proper client timeout detection (fall anticheat)
- [ ] https://github.com/TrinityCore/TrinityCore/commit/508c9d2fc1b20dc2cb40df533e823e1dfe2becc3  Better addon communication
- [ ] https://github.com/TrinityCore/TrinityCore/commit/ce947814c6fa2c32c0908f1e7088ce971f74d365 https://github.com/azerothcore/azerothcore-wotlk/issues/1506

IMPORTANT:

- [ ] https://github.com/TrinityCore/TrinityCore/pull/18771 SEEMS RATHER IMPORTANT (prob hard)
- [ ] https://github.com/TrinityCore/TrinityCore/pull/19914 
- [ ] https://github.com/TrinityCore/TrinityCore/pull/19767/files
- [ ] https://github.com/TrinityCore/TrinityCore/pull/21282/ Core/Creature: implement automatic distance correction for melee combat
- [ ] https://github.com/TrinityCore/TrinityCore/pull/18128 Core/Movement: Using player position extrapolation to smooth range checks
- [ ] https://github.com/TrinityCore/TrinityCore/pull/21193 Core/Movement: Correct the allowed distance to target before a repositioning is necessary.
- [x] https://github.com/TrinityCore/TrinityCore/commit/469f2d3ade168de0b5be18112008c337067a8e03 CMake: Use inherited dependencies in database, shared and game
- [x] https://github.com/TrinityCore/TrinityCore/commit/2a3546ca36468b81d673bdb27315006144af3165
Core/Skills: Use SkillLineAbility.dbc to determine player initial spells  - skill assignment done in a new table `playercreateinfo_skills`
- [ ] https://github.com/TrinityCore/TrinityCore/pull/23864  NPC movement: implement smooth waypoint transition 

MINOR - EASY TO ADD :

- [ ] https://github.com/TrinityCore/TrinityCore/pull/20305/commits/6b226cf735e23bdb40c2dcaba644e0ebbb620cb2
- [x] https://github.com/TrinityCore/TrinityCore/pull/19438 NEED TO SEE IF IT BREAKS OTHER SPELLS (added here https://github.com/azerothcore/azerothcore-wotlk/pull/1696 )
- [x] https://github.com/TrinityCore/TrinityCore/pull/19055/files
- [x] https://github.com/TrinityCore/TrinityCore/commit/62f7debffdb0a45cec0744ddb29460214febc9b8
- [x] https://github.com/TrinityCore/TrinityCore/commit/1a6d0b8d951534754c5a82a7a861f415c1b2f2ca
- [x] https://github.com/TrinityCore/TrinityCore/commit/4d654f548b29bf61552d9f90da8254ecea91b63e
- [x] https://github.com/TrinityCore/TrinityCore/commit/015c6b56e965d3c7f80d5109915237482c631b03
- [x] https://github.com/TrinityCore/TrinityCore/pull/20202/commits/f455d9db1f9e461cb0090ddd4d95f40a2edac11d For neutral guard AI? Added here but didn't seem very useful https://github.com/azerothcore/azerothcore-wotlk/pull/2643
- [ ] https://github.com/TrinityCore/TrinityCore/pull/19352/files Add missing parameter TARGET to smart_scripts 
- [ ] https://github.com/TrinityCore/TrinityCore/commit/132538db1dfb3c495294eeb5acfead59dea02b5c Better grouphandling - Modify group invite behavior while creating group to be blizzlike

# DALARAN CORE

- [ ] https://github.com/Falstring/Dalaran-Core/blob/3605a709de0b6b73c05dcb0bd2eb772d7b0bcf86/src/server/scripts/World/zeppelins.cpp  Zeppelins - Related to this PR https://github.com/azerothcore/azerothcore-wotlk/pull/907 () removed gossip menu options 1969 and 1971  - need to put them back with missing zeppelin master gossip menus)

# OTHERS

- [ ] CLUSTERING

Got idea from Fall1n who has done it on SunwellCore in his private core
https://www.reddit.com/r/wowservers/comments/8u1s8i/spell_attro_cu_fake_delay_does_it_work_only_on/e1c2ol6/
https://bitbucket.org/lukaasm/hellground-wowemu/commits/d09c115242ee9f57da7eed11e8c764f7faeb2f70

- [ ] CROSS REALMS

On a firestorms leak (legion/mop) like [DynastyCore](https://github.com/TheGhostGroup/DynastyCore)

- [ ] Funny command for GM to mount any creature

https://github.com/vmangos/core/commit/b53a0f10b77a8a46d5621c4ca8ee4614553cc516 it's already possible ingame but the command is rather complex, i don't remember it exactly

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL I think it would be more useful to have them split in separate issues; which can be single or grouped by feature

**Comment by BarbzYHOOL** [comment]
Yeah but it's better than sitting in my computer.

**Comment by Nefertumm** [comment]
For this commit https://github.com/TrinityCore/TrinityCore/commit/a1f2f30c145f6ad9c4baeffeff32618e71ff537c add this one too https://github.com/TrinityCore/TrinityCore/commit/2ff76e828f7c757b5120aba41947a6d63e082e17

**Comment by Nefertumm** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d922bc936bd2109bf6332dd84a0d4d31c2b2cba5 -> This commit was reverted by Trinity

**Comment by BarbzYHOOL** [comment]
Feel free to edit the issue with ur new findings nefertumm (since you already edited once :P)

**Comment by retrydev** [comment]
Maczuga/SunwellCore@9fb7429 
Do not apply this commit, otherwise you will see a buggy hp in princes in ICC

**Comment by FrancescoBorzi** [comment]
yes... be careful about what you import

**Comment by Viste** [comment]
for  TrinityCore/TrinityCore@59db2ee Better blizzlike NPC / GOB spawning

need also include all fix commits >_<

**Comment by FrancescoBorzi** [comment]
can we split this in separate issues and assign them to https://github.com/azerothcore/azerothcore-wotlk/milestone/5 ?

**Comment by BarbzYHOOL** [comment]
Here are more of them I had noted long ago:

IMPORTANT - HARD TO ADD :
https://github.com/TrinityCore/TrinityCore/pull/18771 NOT MERGED YET BUT SEEMS RATHER IMPORTANT

IMPORTANT - MEDIUM :
https://github.com/TrinityCore/TrinityCore/pull/19914
https://github.com/TrinityCore/TrinityCore/pull/19767/files (LOTS OF FILES BUT EASY TO ADD)

IMPORTANT - EASY TO ADD :
https://github.com/TrinityCore/TrinityCore/pull/19906

MINOR - EASY TO ADD :
https://github.com/TrinityCore/TrinityCore/pull/20305/commits/6b226cf735e23bdb40c2dcaba644e0ebbb620cb2
https://github.com/TrinityCore/TrinityCore/pull/19438 NEED TO SEE IF IT BREAKS OTHER SPELLS
https://github.com/TrinityCore/TrinityCore/pull/19055/files
https://github.com/TrinityCore/TrinityCore/commit/62f7debffdb0a45cec0744ddb29460214febc9b8
https://github.com/TrinityCore/TrinityCore/commit/1a6d0b8d951534754c5a82a7a861f415c1b2f2ca
https://github.com/TrinityCore/TrinityCore/commit/4d654f548b29bf61552d9f90da8254ecea91b63e
https://github.com/TrinityCore/TrinityCore/commit/015c6b56e965d3c7f80d5109915237482c631b03

For neutral guard AI? :
https://github.com/TrinityCore/TrinityCore/pull/20202/commits/f455d9db1f9e461cb0090ddd4d95f40a2edac11d

Add missing parameter TARGET to smart_scripts :
https://github.com/TrinityCore/TrinityCore/pull/19352/files

Core/Creature: implement automatic distance correction for melee combat
https://github.com/TrinityCore/TrinityCore/pull/21282/

Core/Movement: Using player position extrapolation to smooth range checks
https://github.com/TrinityCore/TrinityCore/pull/18128

Core/Movement: Improve player movement
https://github.com/TrinityCore/TrinityCore/pull/18771

Core/Movement: Correct the allowed distance to target before a repositioning is necessary.
https://github.com/TrinityCore/TrinityCore/pull/21193

Better grouphandling
Modify group invite behavior while creating group to be blizzlike:
https://github.com/TrinityCore/TrinityCore/commit/132538db1dfb3c495294eeb5acfead59dea02b5c


Got idea from Fall1n who has done it on SunwellCore in his private core
https://www.reddit.com/r/wowservers/comments/8u1s8i/spell_attro_cu_fake_delay_does_it_work_only_on/e1c2ol6/
https://bitbucket.org/lukaasm/hellground-wowemu/commits/d09c115242ee9f57da7eed11e8c764f7faeb2f70


Zeppelin
See this PR https://github.com/azerothcore/azerothcore-wotlk/pull/907 () removed gossip menu options 1969 and 1971  - need to put them back with missing zeppelin master gossip menus)
https://github.com/Falstring/Dalaran-Core/blob/3605a709de0b6b73c05dcb0bd2eb772d7b0bcf86/src/server/scripts/World/zeppelins.cpp


----------

ADDED TO THE ORIGINAL POST

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi plz add it to the original post and mark the obsolete comments as resolved (click on `Hide`) I don't know what your commit is for lol

**Comment by Viste** [comment]
reopen plz

**Comment by FrancescoBorzi** [comment]
A big bounty (150 dollars) has been posted from our @heyaapl, for which I'm very thankful.

We need to do the following: go to the list and filter the imports that we are really sure that can and should be imported. Completing such imports will be the criteria to earn the bounty.

**Comment by gengarshadowball** [comment]
On the commit TrinityCore/TrinityCore@6b226cf the worldserver is a tad different from what we have on azerothcore so further research is required to add this feature or implement it without their changes.

**Comment by gengarshadowball** [comment]
https://github.com/TrinityCore/TrinityCore/pull/19055/files This is already implemented, should tick the checkbox

**Comment by gengarshadowball** [comment]
commit Maczuga/SunwellCore@7b1945a also already present on the database table quest_template_addon

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi

**Comment by BarbzYHOOL** [comment]
I added another one to the list that is about making the waypoint transition smooth (instead of a sudden change of direction)

Note: that the author Ovahlord seems to make really cool stuff :P  Maybe can find more in these https://github.com/TrinityCore/TrinityCore/pulls?q=is%3Apr+author%3AOvahlord+is%3Aclosed

**Comment by BarbzYHOOL** [comment]
Not added to the list yet but here is a list of several commits, suggested by the great Jackpoz https://github.com/azerothcore/forum/issues/24#issuecomment-594810696

If someone adds it to the list, delete or edit this comment

**Comment by Helias** [comment]
This big list of commits is really huge, I don't think that it's easy to do at all.

If split this issue in multiple issues, and reduce the amount of this epic issue only on the "SUNWELL CORE (Maczuga's)", I can try to port them all.
The bottom issues seem very big and difficult (like Clustering or CROSS-realm), the TC ones are almost done or closed PRs, may we can move all the TC commits into another issue and put a bounty of 100$ on it and move the bottom ones into another issue.

What do you think? @BarbzYHOOL @Yehonal @FrancescoBorzi @Knindzagxg @Kitzunu

**Comment by felwyn** [comment]
I agree with @Helias though I wasnt asked. It just seems like a huge list and much more than doing creating extra posts for each section.

**Comment by Helias** [comment]
bump

**Comment by FrancescoBorzi** [comment]
I've removed the bounty from here so we can open separate issues and assign the bounties on them accordingly.

Suggestions are welcome.

**Comment by claudiodfc** [comment]
@FrancescoBorzi SkilLineAbility.dbc can be ticked

**Comment by FrancescoBorzi** [comment]
closing to move the bounty elsewhere as this is not going anywhere specific
