### ISSUE TITLE
Import procedure breaks loading large SQL files

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#11417]
### Current Behaviour

Our import procedure breaks loading large SQL files. If you remove the procedure, they load just fine, otherwise it requires updating SQL max_packet_allowed size.

For example: https://github.com/azerothcore/azerothcore-wotlk/commit/44145a62166aa5913e2e9adedb190e274d0395f3

If you remove the CREATE PROCEDURE... part, the file loads fine, but as it is, MySQL chokes loading it and goes away. Not familiar with the issue but I guess the PROCEDURE makes the whole thing go in a single transaction commit? Anyway, as mentioned, removing the procedure makes the file load just fine.

The initial setup, for example, never has any issues because the procedure is not used at any time.

### Expected Blizzlike Behaviour

SQL shouldn't choke on large files.

### Steps to reproduce the problem

Enable db updater, start your server

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/43cf7754414bd70e6a40e383d5d0de43e4813087

### Operating system

Win11 x64

**Comment by Kitzunu** [comment]
As long as we get https://github.com/azerothcore/azerothcore-wotlk/pull/9572 so the CIs dont need to rely on db assambler we can remove it

**Comment by Bogir** [comment]
> As long as we get #9572 so the CIs dont need to rely on db assambler we can remove it

No! Please do not remove it )
db_assembler works more faster then autoupdater

**Comment by Nyeriah** [comment]
@Bogir we are talking about the import procedure, not the database assembler, the database assembler is already deprecated, you may use it at your own peril.

Although, removing the procedure might make the autoupdater faster as well

**Comment by Tony931023** [comment]
apart from what @Nyeriah  describes, in the sql update of @ZhengPeiRu21  you have to try not to make them so big and try to do it in several pr for example that sql writes missions with empty values
Example:  
line 20600 -> REPLACE INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES
line 20632 -> ('48', 'zhCN', '', '0'),

Other errors: line 19494 -19498
``sql
('2854', 'zhCN', '<HTML><BODY><H1 align=\"center\">部落军官军阶</H1><BR/><P align=\"center\">第二部分</P><IMG src=\"Interface\\PvPRankBadges\\PvPRank09\" align=\"left\"/><BR/><P align=\"right\">百夫长</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank08\" align=\"left\"/><BR/><P align=\"right\">军团士兵</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank07\" align=\"left\"/><BR/><P align=\"right\">血卫士</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank06\" align=\"left\"/><BR/><P align=\"right\">石头守卫</P><BR/><BR/></BODY></HTML>', '0'),
('2855', 'zhCN', '<HTML><BODY><H1 align=\"center\">部落士兵军阶</H1><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank05\" align=\"left\"/><BR/><P align=\"right\">一等军士长</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank04\" align=\"left\"/><BR/><P align=\"right\">高阶军士</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank03\" align=\"left\"/><BR/><P align=\"right\">中士</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank02\" align=\"left\"/><BR/><P align=\"right\">步兵</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank01\" align=\"left\"/><BR/><P align=\"right\">斥候</P><BR/><BR/></BODY></HTML>', '0'),
('2856', 'zhCN', '<HTML><BODY><H1 align=\"center\">联盟军官军阶</H1><BR/><P align=\"center\">第二部分</P><IMG src=\"Interface\\PvPRankBadges\\PvPRank09\" align=\"left\"/><BR/><P align=\"right\">护卫骑士</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank08\" align=\"left\"/><BR/><P align=\"right\">骑士队长</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank07\" align=\"left\"/><BR/><P align=\"right\">骑士中尉</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank06\" align=\"left\"/><BR/><P align=\"right\">骑士</P><BR/><BR/></BODY></HTML>', '0'),
('2857', 'zhCN', '<HTML><BODY><H1 align=\"center\">联盟士兵军阶</H1><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank05\" align=\"left\"/><BR/><P align=\"right\">士官长</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank04\" align=\"left\"/><BR/><P align=\"right\">军士长</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank03\" align=\"left\"/><BR/><P align=\"right\">中士</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank02\" align=\"left\"/><BR/><P align=\"right\">下士</P><BR/><BR/><IMG src=\"Interface\\PvPRankBadges\\PvPRank01\" align=\"left\"/><BR/><P align=\"right\">步兵</P><BR/><BR/></BODY></HTML>', '0'),
('2858', 'zhCN', '安东尼·雷·斯塔克$B$B1961——2005', '0'),
``
