### ISSUE TITLE
[Zul'Gurub] High Priestess Venoxis - Holy Nova 

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#11416]
### Current Behaviour

The boss cast the spell if he have at least 3 target affected. 

### Expected Blizzlike Behaviour

The boss should cast holy nova even if he have only two targets affected (himslef and the boss)

### Source

https://youtu.be/mHYXjf4TLUc?t=87

### Steps to reproduce the problem

Engage Venoxis

### AC rev. hash/commit

13993a0

### Operating system

Windows 11

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/13993a0b5b45430ea7bc4868283494f0362f2a1e/src/server/scripts/EasternKingdoms/ZulGurub/boss_venoxis.cpp#L219-L221

There is script for it

**Comment by Lynethris** [comment]
> https://github.com/azerothcore/azerothcore-wotlk/blob/13993a0b5b45430ea7bc4868283494f0362f2a1e/src/server/scripts/EasternKingdoms/ZulGurub/boss_venoxis.cpp#L219-L221
> 
> There is script for it

I didn't see the comment. So it's wrong. Like we can see on video, the boss can cast the spell (but only two tarrgets are affected: boss and tank).

**Comment by Kitzunu** [comment]
Okay, but could it have been changed in BC/Wrath?

**Comment by Lynethris** [comment]
> Okay, but could it have been changed in BC/Wrath?

From wow fandom, no changes before cata (where the spell have been remove). Nothing find on wowhead.
https://wowpedia.fandom.com/wiki/High_Priest_Venoxis_(Classic)

Globaly this raids doesn't have  really change with BC and Woltk. It's only with cata. I have try to find a source on woltk but it's hard because it's only in solo.

**Comment by Maelthyrr** [comment]
After new some test, I did a mistake. Seems to work fine.
