### ISSUE TITLE
Priest Penance

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#11423]
### Current Behaviour

Priest spell [Penance](https://wotlk.evowow.com/?spell=52984) when you get hit it ticks only 2 times instead of 3, the last tick doesn't go through.

### Expected Blizzlike Behaviour

In any case should be 3 ticks.

### Steps to reproduce the problem

1. Create priest
2. Take talents on disc priest [Penance](https://wotlk.evowow.com/?spell=52984) or learn 52984
3. enter the second character, throw a duel
4. hit with an auto attack for example, and try to cast penance.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/49978883ce335c90b345a35e0ca6fc4a70e95cff
### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by temperrr** [comment]
Hey do you mean if yo utake a hit during the channel it should still cast 3? If so, do you have a source?

I just tested it an it hits 3 times unless you take damage.

**Comment by r0m1ntik** [comment]
@temperrr I just tested it an it hits 3 times **unless you take damage**. It works yes.
Ano works as it should everywhere, except here, I have been in WoW for 12 years in the gameplay. Unfortunately, I did not find the source, but I know that this should not be the case as it is now.

**Comment by mpfans** [comment]
I tested it. I didn't find any bugs

Can you elaborate on how to reproduce it?

**Comment by r0m1ntik** [comment]
@mpfans https://streamable.com/7cddpo

**Comment by Nyeriah** [comment]
Yes, its a channeled spell, the attacks interrupt the tickets, nothing wrong here
