### ISSUE TITLE
(esES - esMX) Update quest_template_locale to 100%

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#11421]
### Current Behaviour

Update of the quest_template_locale table to 100% in: esES and esMX

### esES and esMX 
* These quests have been marked as obsolete by Blizzard and cannot be obtained or completed.
- [9754](https://es.classic.wowhead.com/quest=9754)
- [10215](https://es.classic.wowhead.com/quest=10215)
- [12445](https://es.classic.wowhead.com/quest=12445)
- [12731](https://es.classic.wowhead.com/quest=12731)
- [12923](https://es.classic.wowhead.com/quest=12923)
- [13541](https://es.classic.wowhead.com/quest=13541)

### Steps to reproduce the problem

*

### Extra Notes

Update some translations that contain error

### AC rev. hash/commit

AzerothCore rev. 4ac565699fcb 2022-04-13 11:57:04 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
What is the purpose of this issue?

**Comment by Tony931023** [comment]
make a list with the translations that have errors to fix them in a PR
