### ISSUE TITLE
Data collection AddOn

### ISSUE THREAD

**Issue by eTzmNcbkrng** [azerothcore/azerothcore-wotlk#11426]
### Describe your feature request or suggestion in detail

With the expected release of Wrath Classic from Blizzard, I think it would be a good idea for AC to develop an AddOn that can collect data from Blizzard’s Wrath Classic servers.

Obviously there are already addons like MobInfo and GatherMate that track NPC stats/loot and node spawn points but I think it would be valuable to have a background addon that collects more comprehensive data.

Example, instead of plainly tracking NPC loot, also tie it to the quests the player currently has, this would give more accurate numbers drop rates of quest items.

I recall there being a lot of contention about flee mechanics, perhaps this addon could monitor NPC movement speed relative to HP.

The amount of data I’d like to see collected to improve the AC project could potentially be quite large so to keep performance degradation to a minimum I don’t think it would be necessary to display this information in game and perhaps a small client could be developed that uploads and resets SavedVars every so often.

I’m sure there are many more data points that others can think of that would be worth collecting.

### Describe a possible solution to your feature or suggestion in detail

As above.

### Additional context

I’m on the fence about playing Wrath Classic, but if I can benefit the AC project by doing so I’d certainly feel a lot better about paying Blizzard.

**Comment by eTzmNcbkrng** [comment]
Oh just thought of another feature, have a way for the addon to allow the user to open a “Help Request” visible to other users of the addon.
Let’s say I want to test or confirm a bug logged on AC GitHub, I log into the game and open a Help Request saying I need a Level 58 Death Knight, all other users of the addon (on the same server at least) could see this request and whisper the person who logged it.

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/sniffing-and-parsing

We sniff for official data.
