### ISSUE TITLE
[Item] Demon Forged Breastplate (ID: 12628) missing spell-coefficency in its proc.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11435]
https://github.com/chromiecraft/chromiecraft/issues/3348

### What client do you play on?

enUS

### Faction

- [x] Alliance
- [x] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [x] 60

### Current Behaviour

Demon Forged Breastplate doesn't scale with SP
Attaching a video under here:
https://youtu.be/kPiSK0vhYHM

### Expected Blizzlike Behaviour

It should scale for about 40% of your spell power.

### Source

https://youtu.be/r02IrY0gNI0?t=216 For classic dungeon farming guide, which covers Demon Forged Breastplate Spellcoefficency.
https://youtu.be/xwQ4BqteDVI?t=32 Covers a WoW Classic nerf that was later reverted to its original values of 40% SP
https://wowpedia.fandom.com/wiki/Demon_Forged_Breastplate a wiki link, which outlines any patches that has been done to the item. Since there is no explicit statement, that the spell-coefficency is removed, it is acceptable to believe that it carried over all the way to Wrath client. 

https://web.archive.org/web/20110629022303/https://www.wowhead.com/item=1168/skullflame-shield#comments:40
From Patch 4.0.3:
>You appear correct, I was organizing my bank on my Paladin and after waving my cursor over [Skullflame Shield] showing 1373-1374 life steal (and 76-128 fire damage oddly enough) I also checked my Demon Forged Breastplate. That showed 656-660 life.

Skullflame Shield has a 100% SP coef. Meaning that that player has (1373,5-35)=1338,5 SP, so 40% of that is 535,4. And 535,4 + 120 = 655,4.

### Steps to reproduce the problem

1. Wear item 12628 as a paladin with a significant amount of SP
2. Pull a large amount of mobs
3. Observe that in every proc, each tick will be around 30 life steal, which adds up to 120 in one proc.

### Extra Notes

Item ID: 12628
Proc Spell ID: 16611
Curiously, there is another issue with the item that I wasn't able to reproduce. It apparently wasn't proccing at all in the first test 
Hasie did, and the same occurred to me too. After switching items around or unequipping and later re-equipping the same items caused the proc to start working. I tried to reproduce the issue several times but wasn't able to.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4ac565699fcb7b88fcc15db97ec9f14a0894f331

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
rev. b263f45
Seems to have been fixed. (without spell_bonus_data modification)

First is with 0 SP
Second is with 792 SP
792 *0.4 = 316 + 120 (base) = 436 / 4 (ticks) = 109 per tick
![f54977efc962546a46db2352221e7874](https://user-images.githubusercontent.com/46330494/221166417-7b8f861d-3d56-43c3-b9df-0169c24cc1fb.png)
