### ISSUE TITLE
Trial of the Crusader -Floor needs to be re-broken by Arthas to get to Anub'arak

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#1143]
##### SMALL DESCRIPTION:
You need to keep speaking to the NPC to get Arthas to come out and break the floor so you can get to Anub after a wipe, and Anub doesn't respawn unless you talk to that NPC.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Once the lich king comes out and destroys the floor after the Twin Val'kyr are defeated, the floor should stay broken, and when a wipe on Anub'arak occurs, players zoning into the raid should simply fall to Anub below, and not be forced to talk to the NPC that breaks the floor again.

When he is in the ground before you walk towards him, he comes up and says:
> Anub'arak yells: Ahhh, our guests have arrived, just as the master promised.

This should only happen once, if you wipe he should be sitting on the ground waiting for you to pull him in full view

##### CURRENT BEHAVIOUR:
The floor needs to be re-broken after a wipe on Anub'arak and Anub doesn't respawn unless you talk to the NPC.  Tested on 10, 10H, 25, 25H.

Anub'arak is being forced to do his intro each time, when it should be once, and then re-spawn in full view of players when a wipe occurs.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go into any difficulty of the ToC raid
2. Do the first 4 bosses and go down to Anub'arak
3. Wipe and attempt to zone back in.  You will need to re-initiate the RP to get to Anub and get him to spawn.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
#fffb925

##### OPERATING SYSTEM:
Win10

**Comment by NizeGuy** [comment]
Incorrectly reported Nerubian Burrower scripting as an error; did some digging in the scripts and found that Submerge won't be cast unless below 80% health.  Unsure if this is Blizzlike, but upon realization that it is scripted, it works.  Removed from original post and added on to the second issue.

**Comment by NizeGuy** [comment]
> 
> 
> Can you please provide evidence of this? Thanks.

Hello, apologies for the long wait.  I took a break from WoW and did not get the requested evidence.  Here is a video of me pulling Anub'arak on 25 Heroic, dying and flying back.  As you can see in the video, the floor needs to be broken again.  Blizzlike behavior is the floor remains broken, and Anub'arak only does his initial roleplay once.  After the first wipe, he should be above-ground, waiting to be attacked again.

https://youtu.be/EqZoOt6VFl8
