### ISSUE TITLE
[ICC] Sindragosa KILL ALL RAID on Start of Phase 2

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#11439]
### Current Behaviour

On the start of second phase after SPELL_FROST_BEACON and SPELL_ICE_TOMB target is die with no reason in combat jornal

### Expected Blizzlike Behaviour

target dont die

### Steps to reproduce the problem

1) go icc any mode
2) go fight with sindragosa
3) wait for fly phase

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/03a6413080752294bd47b9e4e9ef0287dc1d4833

### Operating system

Debian 11 x64

**Comment by fullofstarschen** [comment]
confirm.
It's all right in e13f4271897e 2022-04-11.

**Comment by PsYchoNauTek** [comment]
can confirm that!

looks like with the rewright of the evade reasons it bugged her out directly when she enters the far spot of the air event when she should turn around to the raid.
Tried a bit around tho in script... managed it that the raid doesn't get wiped on her p2 reset, but she still does reset her... =/
