### ISSUE TITLE
[Tempest Keep] Kael'thas Sunstrider

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#11447]
### Current Behaviour

cant attack the targets on this boss
if kill adepts by .damage Kael'thas also cant attack

### Expected Blizzlike Behaviour

can attack the targets on this boss

### Steps to reproduce the problem

1) Go Kael'thas Sunstrider

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/61de612641fdf0639b447c01a3e1a677ae5685a1

### Operating system

Debian 11 x64

**Comment by 5266869** [comment]
hello, sorry about disturb you , is this issue fixed?

**Comment by Nyeriah** [comment]
The major problem here is that report lacks information. You’re not meant to be able to attack them to begin with. It currently has no information anyone could work with. Reports like this hardly get the attention they deserve, because they hardly report anything at all…

**Comment by Nyeriah** [comment]
@zqgmzq Please don't spam useless messages.

**Comment by zqgmzq** [comment]
@Nyeriah 
ok)
but bugs like illidan evade and this is critical
2 big and important bosses cant be killed
the problem with illidan has been known for a year
and nobody wants to fix it)

**Comment by Nyeriah** [comment]
I'm not sure you understand how opensource projects work. People volunteer their free time to provide fixes, nobody's obligated to fix anything **you** deem critical, regardless of how long has it been bugged.

It will eventually be fixed, once someone takes interest into those issues.

Demanding fixes doesn't help.

**Comment by zqgmzq** [comment]
do not pay attention, you can close the report then
i fixed it in 2 minutes
just need to find where and who broke)
Thanks for @IntelligentQuantum
