### ISSUE TITLE
[BWL] Death Talon Wyrmguard Bronze power

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11448]
### Current Behaviour

Brood Power bronze affects more then 1 target
You get a new brood power on a new pull of same mobs

### Expected Blizzlike Behaviour

Brood Power bronze can only affect 1 target at a time.
If you wipe on the mobs they should still have the same brood power

### Source

https://www.youtube.com/watch?v=Nltw_4eQMSE
https://www.youtube.com/watch?v=y0wNnd86sn4

Best view:
https://youtu.be/MyH-OWhjxW4?t=1438

### Steps to reproduce the problem

go to bwl with a few chars
aggro death talon wyrmguard packs till you get bronze one
watch as your whole raid dances around

### AC rev. hash/commit

7ecd73867419c807c9869ebeb73c7ca4e39cd1c8

### Operating system

Manjaro x64

**Comment by UltraNix** [comment]
@temperrr What about other powers? Works okay?

**Comment by temperrr** [comment]
Ehh, I think they do

**Comment by UltraNix** [comment]
@temperrr I cannot confirm the 1st bug. It casts the spell only on one target.

**Comment by temperrr** [comment]
Just get 5 chars in, you'll see it happen

**Comment by UltraNix** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/ab990647e3e9885af1c7d6f16cc8f03c130d20da
Didn't work? It's not an AOE spell.

**Comment by temperrr** [comment]
Yea that didnt work

**Comment by UltraNix** [comment]
Hmm, that spell should damage nearby allies, as I can see.

**Comment by temperrr** [comment]
to me it looks like some kind of disease spreading rather quickly, hard to describe.

**Comment by temperrr** [comment]
Yea and as you take damage, you also get whirlwind effect

**Comment by UltraNix** [comment]
I guess the 2nd option.

**Comment by temperrr** [comment]
But we don't want to fix the second bug before we fix the first bug, as having 3 of bronze power these will make progression impossible atm ;p
