### ISSUE TITLE
[Black Temple] Illidan Start of Phase 5

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#11440]
### Current Behaviour

After SPELL_SHADOW_PRISON Illidan is EVADE and Combat Stoped
May be not every time (50/50)

### Expected Blizzlike Behaviour

Continue combat

### Steps to reproduce the problem

1) Go Black Temple to Illidan

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/03a6413080752294bd47b9e4e9ef0287dc1d4833

### Operating system

Debian 11 x64

**Comment by Valoriaz** [comment]
can confirm it

**Comment by zqgmzq** [comment]
@AzerothCoreDev, somebody can fix it?

**Comment by hahalmtdhl** [comment]
@FrancescoBorzi The problem is still not fixed However, it is shown here that it has been completed:
[done](https://github.com/azerothcore/azerothcore-wotlk/projects/16#card-54332579)

**Comment by hahalmtdhl** [comment]
Which update caused Illidan's error?

**Comment by zqgmzq** [comment]
@hahalmtdhl, i use before build from 03.2021 - Its ok
If i find after what it broken i write here

**Comment by frizar** [comment]
any update? it's not fixed yet

**Comment by hahalmtdhl** [comment]
> 

Never fixed

**Comment by yuanf225** [comment]
Maybe it needs to be fixed according to the progress of chromiecraft

**Comment by benjymansy123** [comment]
For future reference to anyone in this thread and/or anyone reading, saying "not fixed yet" or something to that line adds nothing. Saying something more like "still an issue as of commit [whatever]" is at least somewhat helpful.

**Comment by UltraNix** [comment]
#9038
