### ISSUE TITLE
Build broken on macOS Mojave

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1144]
> ➜  build git:(master) make -j 4
Scanning dependencies of target Recast
Scanning dependencies of target g3dlib
Scanning dependencies of target gsoap
Scanning dependencies of target Detour
[  0%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourAlloc.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/Recast.cpp.o
[  1%] Building CXX object deps/gsoap/CMakeFiles/gsoap.dir/soapC.cpp.o
[  1%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/AABox.cpp.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourAssert.cpp.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourCommon.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastAlloc.cpp.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMesh.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastAssert.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastArea.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastContour.cpp.o
[  1%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Any.cpp.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshBuilder.cpp.o
[  1%] Building CXX object deps/gsoap/CMakeFiles/gsoap.dir/soapServer.cpp.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshQuery.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastFilter.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastLayers.cpp.o
[  2%] Building CXX object deps/gsoap/CMakeFiles/gsoap.dir/stdsoap2.cpp.o
[  2%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMesh.cpp.o
[  2%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNode.cpp.o
[  2%] Linking CXX static library libDetour.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libDetour.a(DetourAssert.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libDetour.a(DetourAssert.cpp.o) has no symbols
[  2%] Built target Detour
[  2%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryFormat.cpp.o
[  2%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMeshDetail.cpp.o
Scanning dependencies of target sharedPCH.cpp_dephelp
[  2%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryInput.cpp.o
[  2%] Building CXX object src/common/CMakeFiles/sharedPCH.cpp_dephelp.dir/PrecompiledHeaders/sharedPCH.cpp.o
[  3%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRasterization.cpp.o
[  3%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRegion.cpp.o
[  3%] Linking CXX shared module libsharedPCH.cpp_dephelp.so
[  3%] Built target sharedPCH.cpp_dephelp
[  3%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/BinaryOutput.cpp.o
Scanning dependencies of target collisionPCH.cpp_dephelp
[  3%] Linking CXX static library libRecast.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libRecast.a(RecastAssert.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libRecast.a(RecastAssert.cpp.o) has no symbols
[  3%] Building CXX object src/common/Collision/CMakeFiles/collisionPCH.cpp_dephelp.dir/PrecompiledHeaders/collisionPCH.cpp.o
[  3%] Built target Recast
[  3%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Box.cpp.o
Scanning dependencies of target revision.h
[  3%] Built target revision.h
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Capsule.cpp.o
[  4%] Linking CXX static library libgsoap.a
Scanning dependencies of target gamePCH.cpp_dephelp
[  4%] Linking CXX shared module libcollisionPCH.cpp_dephelp.so
[  4%] Built target gsoap
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/CollisionDetection.cpp.o
[  4%] Built target collisionPCH.cpp_dephelp
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/CoordinateFrame.cpp.o
Scanning dependencies of target authPCH.cpp_dephelp
[  4%] Building CXX object src/server/authserver/CMakeFiles/authPCH.cpp_dephelp.dir/PrecompiledHeaders/authPCH.cpp.o
[  4%] Building CXX object src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o
Scanning dependencies of target ScriptPCH.cpp_dephelp
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Crypto.cpp.o
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Cylinder.cpp.o
[  4%] Building CXX object src/server/scripts/CMakeFiles/ScriptPCH.cpp_dephelp.dir/PrecompiledHeaders/ScriptPCH.cpp.o
[  4%] Linking CXX shared module libauthPCH.cpp_dephelp.so
[  4%] Built target authPCH.cpp_dephelp
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/debugAssert.cpp.o
Scanning dependencies of target worldPCH.cpp_dephelp
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/FileSystem.cpp.o
[  4%] Building CXX object src/server/worldserver/CMakeFiles/worldPCH.cpp_dephelp.dir/PrecompiledHeaders/worldPCH.cpp.o
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/fileutils.cpp.o
[  4%] Linking CXX shared module libworldPCH.cpp_dephelp.so
[  4%] Built target worldPCH.cpp_dephelp
[  4%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/format.cpp.o
Scanning dependencies of target generate_sharedPCH.cpp
[  4%] Generating sharedPCH.h.pch
[  5%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/g3dfnmatch.cpp.o
[  5%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/g3dmath.cpp.o
[  5%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Line.cpp.o
[  6%] Linking CXX shared module libgamePCH.cpp_dephelp.so
Undefined symbols for architecture x86_64:
  "ACE_RW_Mutex::~ACE_RW_Mutex()", referenced from:
      ACE_RW_Thread_Mutex::~ACE_RW_Thread_Mutex() in gamePCH.cpp.o
  "ACE_RW_Thread_Mutex::ACE_RW_Thread_Mutex(char const*, void*)", referenced from:
      ___cxx_global_var_init in gamePCH.cpp.o
      ___cxx_global_var_init.2 in gamePCH.cpp.o
      ___cxx_global_var_init.4 in gamePCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/game/libgamePCH.cpp_dephelp.so] Error 1
make[1]: *** [src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/LineSegment.cpp.o
[  6%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Log.cpp.o
[  6%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix3.cpp.o
[  6%] Built target generate_sharedPCH.cpp
[  6%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Matrix4.cpp.o
[  6%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/MemoryManager.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/PhysicsFrame.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Plane.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/prompt.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Quat.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Random.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Ray.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/ReferenceCount.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/RegistryUtil.cpp.o
[  7%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Sphere.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/stringutils.cpp.o
[  8%] Linking CXX shared module libScriptPCH.cpp_dephelp.so
Undefined symbols for architecture x86_64:
  "ACE_RW_Mutex::~ACE_RW_Mutex()", referenced from:
      ACE_RW_Thread_Mutex::~ACE_RW_Thread_Mutex() in ScriptPCH.cpp.o
  "ACE_RW_Thread_Mutex::ACE_RW_Thread_Mutex(char const*, void*)", referenced from:
      ___cxx_global_var_init in ScriptPCH.cpp.o
      ___cxx_global_var_init.2 in ScriptPCH.cpp.o
      ___cxx_global_var_init.4 in ScriptPCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/scripts/libScriptPCH.cpp_dephelp.so] Error 1
make[1]: *** [src/server/scripts/CMakeFiles/ScriptPCH.cpp_dephelp.dir/all] Error 2
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/System.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/TextInput.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/TextOutput.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Triangle.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/uint128.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/UprightFrame.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector2.cpp.o
[  8%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector3.cpp.o
[  9%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector4.cpp.o
[  9%] Linking CXX static library libg3dlib.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libg3dlib.a(RegistryUtil.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libg3dlib.a(RegistryUtil.cpp.o) has no symbols
[  9%] Built target g3dlib
make: *** [all] Error 2

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/2d575299d355e79cf8a1357cd88e707252b52e11

##### OPERATING SYSTEM:

macOS Mojave

##### MODULES:

no modules

##### OTHER CUSTOMIZATIONS:

no customizations

**Comment by konighter** [comment]
Anyone solved it?

**Comment by FrancescoBorzi** [comment]
@konighter no but you can still install AzerothCore on macOS using docker:

http://www.azerothcore.org/wiki/Install-with-Docker

![image](https://user-images.githubusercontent.com/75517/54301392-21d22100-45bf-11e9-8718-04f0e00b5b36.png)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/runs/1037438472?check_suite_focus=true
