### ISSUE TITLE
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#11450]
### Current Behaviour

Spam in Logs:
Unit::HandleProcTriggerSpell: Spell 71201 (effIndex: 0) has unknown TriggerSpell 0. Unhandled custom case?

### Expected Blizzlike Behaviour

No Spam in Logs

### Steps to reproduce the problem

Run Core with players

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/61de612641fdf0639b447c01a3e1a677ae5685a1

### Operating system

Debian 11 x64

**Comment by Kitzunu** [comment]
Need make it debug and not error log

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/164420229-c9b9a8ae-0e11-4015-9269-169aa8cba41a.png)

**Comment by Kitzunu** [comment]
Acxtually no, it should not be makred as debug as this is actually a bug. Need to find out why it is trying to use spells with no TriggerSpell

**Comment by Kitzunu** [comment]
@mpfans your screenshot is not related to this issue, TriggerSpell 1206 is supposed to be a serverside spell that is not existing on AC. Please open a new report.

**Comment by Kitzunu** [comment]
@Lynethris if you close an issue that has been resolved, please link the commit that fixed it.

https://github.com/azerothcore/azerothcore-wotlk/commit/778d1bb9fa30f59357d1e4d8192a51e3021f7286

**Comment by Lynethris** [comment]
Oh, my bad. With you last comment to mpcfan, I didn't seen that he doesn't the author (and that isn't the same issue). I reopen it, sry.

**Comment by Kitzunu** [comment]
This was fixed https://github.com/azerothcore/azerothcore-wotlk/commit/778d1bb9fa30f59357d1e4d8192a51e3021f7286
