### ISSUE TITLE
[The Hinterlands] Rhapsody's Kalimdor Kocktail missing "on completion" dialogue and roleplay

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11454]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [] Horde

### Content Phase:

- [] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour
[Rhapsody Shindigger](https://wowgaming.altervista.org/aowow/?npc=5634) during the [Rhapsody's Kalimdor Kocktail](https://wowgaming.altervista.org/aowow/?quest=1452) quest do not start the drinking event.

![WoWScrnShot_042022_132344](https://user-images.githubusercontent.com/100415626/164220851-383f454a-8e16-4a5e-9382-f7510bb640e3.jpg)

### Expected Blizzlike Behaviour
Shindigger should start the following dialogue event after turning the quest:

Rhapsody Shindigger says: Time to brew up a Kalimdor Kocktail! Hiccup!
Rhapsody Shindigger says: That should do it! Hiccup!
Rhapsody Shindigger chugs his drink.
Rhapsody falls down.
Rhapsody Shindigger says: Hiccup!
Rhapsody Shindigger says: Ok, who pushed me down? Was it you, ? Someone turn the lights back on. Hiccup!
Rhapsody gets back up and walks back to his keg.
Rhapsody Shindigger says: One more sip of the ol' fire water and I'll be ready to talk. Hiccup! Cheers!
Rhapsody Shindigger says: So, Kalamah, I'm ready to tell you what happened in the Swamp of Sorrows. Hiccup!

### Source
https://wowpedia.fandom.com/wiki/Rhapsody%27s_Kalimdor_Kocktail?diff=1569356&oldid=1569287
Revision from 11 August 2008

[Found this quest completion on Classic WoW as additional resource and proof of the Blizzlike behavior.](https://youtu.be/TZ6sz5sxo4Q?t=1616)

### Steps to reprodude the problem

Go to the Stormwind
   1. Start the quest [In Search of The Temple](https://wowgaming.altervista.org/aowow/?quest=1448)
   2. Follow the chain up to [Rhapsody's Kalimdor Kocktail](https://wowgaming.altervista.org/aowow/?quest=1452)
   3. Turn the above quest
   4. Observe the reaction (Or more like it's lack)

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3381
Bug found by Sathrenor.

Rhapsody Shindigger:
DB GUID: 92848
Entry: 5634

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
Sniff complete.
