### ISSUE TITLE
[Minor] Sergeant Yohwa's gossip spelling

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11453]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [] Horde

### Content Phase:

- [] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

There is a needles "ad:" part before <son/lass>.

![bug report](https://user-images.githubusercontent.com/100415626/164213255-c1fb8a39-0cd8-4836-bc4e-f79efdc00c9d.jpg)

### Expected Blizzlike Behaviour

Same, but without "ad:" part.

Original quote: 

> You watch where you step around here, <son/lass>. You might not be part of our outfit, but that doesn't mean I won't take a cane to you if you fall out of line! 

### Source

https://wowpedia.fandom.com/wiki/Sergeant_Yohwa

### Steps to reproduce the problem

1. Go to SV Rebel Camp and speak with NPC.

### Extra Notes
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3383
Bug found by Sathrenor.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/d686a7c573d7f914ccd6b1d5228d6fc8bdc494d9
