### ISSUE TITLE
Tempest Keep last boss (the prince) have a big problem

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#11477]
### Current Behaviour

Tempest Keep last boss (the prince) have a big problem
at P1, 4 little boss all come out and when i kill all of this 4 little bosses,
it is also can not continue, do not into the P2.
i am sorry about my poor english,
please check it out, thanks.
i used the newest version (newest version AC source code and rebuild)

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

ubuntu 21

**Comment by zqgmzq** [comment]
i reported about it 
https://github.com/azerothcore/azerothcore-wotlk/issues/11447
