### ISSUE TITLE
Bash script installer is broken

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1147]
##### SMALL DESCRIPTION:

The installer (file `installer.sh`) doesn't work. It exits without error but does nothing.

##### EXPECTED BEHAVIOUR:

https://www.youtube.com/watch?v=j1HI6pLZZvM

##### STEPS TO REPRODUCE THE PROBLEM:

Run the installer on a clean Ubuntu 18.04 installation.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/db25b814e2587f51e3ec8a62186012c2380aaef3

##### OPERATING SYSTEM:

Ubuntu 18.04

##### MODULES:

No modules

##### OTHER CUSTOMIZATIONS:

No customizations

**Comment by Kitzunu** [comment]
Still an issue?

**Comment by FrancescoBorzi** [comment]
I asked Yehonal to check this in the past, but I haven't tested this recently.

**Comment by FrancescoBorzi** [comment]
I had asked @Yehonal to check this in the past, but I haven't tested this recently.

**Comment by Yehonal** [comment]
I was using the acore dashboard recently, never had that issue

However, you don't have to use the installer.sh but the ./acore.sh dashboard that you can see inside the root folder of the project.

That is the single-source-of-truth of all our user bash scripts
