### ISSUE TITLE
almost all raid dungeon have problem

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#11479]
### Current Behaviour

after i updated the newest version (the newest version AC source code),
almost all raid dungeon have problem:
we can not enter the dungeon when everyone dead in the dungeon，
it always said the dungeon is battling.
for now , tempest keep, black temple, karazhan have sure had this problem.

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

ubuntu 21

**Comment by Bogir** [comment]
in what revision did it still work? What was your previouse revision?

**Comment by 5266869** [comment]
i do not remember it , almost like the day of 2022-03-13

**Comment by Bogir** [comment]
Incorrect info at all

**Comment by 5266869** [comment]
what Incorrect ? 
the issue or previouse revision ?

**Comment by 5266869** [comment]
i am sure the issue , and i updated the newest version (the newest version AC source code). but my map files used v13 (https://github.com/wowgaming/client-data).
previouse revision i said almost like the day of 2022-03-13, it means not sure the date, sorry about my poor english.
