### ISSUE TITLE
[Ghostlands] Swimming in Lake Elrendar breaks/ends combat with several surrounding NPCs.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11474]
https://github.com/chromiecraft/chromiecraft/issues/3388

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When attacking Enemy NPC's under Lake Elrendar (Ghostlands), they don't fight back. They just stay in place and reset with full HP, basically making them invulnerable and making the following quests imposible to complete:

1. Spirits of the Drowned
2. Vanquishing Aquantion

### Expected Blizzlike Behaviour

All Enemy NPC's in lake elrendar should be able to fight back and enter in combat normally under the water.

### Steps to reproduce the problem

1. Go to Lake Elrendar, in Ghostlands
2. Attack any Enemy NPC's under the lake Elrendar

### Extra Notes

https://user-images.githubusercontent.com/100873791/164568572-3bf440ca-9c6c-4aa7-818d-42cd4524399e.mp4

I clearly remember doing this quest at least a week ago. ~~Only the 2 related NPCs seem affected by the bug, and entering the water while engaged in combat with another NPC will **not** break combat.~~
Edit: [Nerubis Guard](https://wowgaming.altervista.org/aowow/?npc=16313) is also affected, the nearby [shadowpine](https://wowgaming.altervista.org/aowow/?npc=16341) [trolls](https://wowgaming.altervista.org/aowow/?npc=16340), however, are not.
Edit 2: Also affects the [Lynxes](https://wowgaming.altervista.org/aowow/?npc=16348) and [Bats](https://wowgaming.altervista.org/aowow/?npc=16354)

https://wowgaming.altervista.org/aowow/?quest=9174
https://wowgaming.altervista.org/aowow/?quest=9274
[Ravening Apparition](https://wowgaming.altervista.org/aowow/?npc=16327) ID: 16327
[Vengeful Apparition](https://wowgaming.altervista.org/aowow/?npc=16328) ID: 16328

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Possibly related to https://github.com/azerothcore/azerothcore-wotlk/pull/11425?
I tried to recreate the issue with the mobs in Eastern Plaguelands to see if the issue was larger than just this, but they're fine. I'll take another look around though.

**Comment by Nyeriah** [comment]
A regression from this: https://github.com/azerothcore/azerothcore-wotlk/commit/93a8d4fb6337eac9058ac445b30e31328c4ccf74
