### ISSUE TITLE
[Blacksmith] Unfired Plate Gauntlets shouldn't need a quest prerequisite to be looted.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11472]
https://github.com/chromiecraft/chromiecraft/issues/2343

### Current Behaviour

Item [Unfired Plate Gauntlets](https://wowgaming.altervista.org/aowow/?item=12812) requires the player to have the quest [Fiery Plate Gauntlets](https://wowgaming.altervista.org/aowow/?quest=5124) for it to be lootable from object [Unfired Plate Gauntlets](https://wowgaming.altervista.org/aowow/?object=176089).

### Expected Blizzlike Behaviour

The only prerequisite for looting the item is being a Blacksmith. Having the quest is unnecessary.

### Source

>Successfully looted [Fiery Plate Gauntlets](https://www.wowhead.com/?item=12812) without having the quest in my log.
Was previously bugged.([source](https://www.wowhead.com/quest=5124/fiery-plate-gauntlets#comments:id=700130))

>I'm guessing that this quest is only available to blacksmiths as the required [Unfired Plate Gauntlets](https://www.wowhead.com/item=12812) can only be looted by a blacksmith (3.3.5)
>Yep. Just tried to pick them up as my druid (ench/tailoring) and couldn't loot them. They disappeared after I clicked them.

>Post-shattering, that [object](https://www.wowhead.com/object=176089) is still lootable by blacksmiths, but there's really no point, because that [item](https://www.wowhead.com/item=12812) was only used in this quest, which is no longer obtainable. (4.2.2)

>The quest has been removed, but you can still pick up the Unfired Plate Gauntlets.(5.3.0)

From at least 3.1.1 onwards, it seems that the quest item can be looted only by blacksmiths without needing to have any quest as a pre-requisite.

### Steps to reproduce the problem

.go LBRS
.setskill 164 225
loot the object Unfired Plate Gauntlets, and see it empty.
.quest add 5124
wait for the object to respawn
loot it again and find the item inside

### Extra Notes

Object [Unfired Plate Gauntlets](https://wowgaming.altervista.org/aowow/?object=176089) ID: 176089
87949 (Entry: 176089) - [Unfired Plate Gauntlets X:-18.862600 Y:-360.394012 Z:-31.426800 MapId:229]
Item [Unfired Plate Gauntlets](https://wowgaming.altervista.org/aowow/?item=12812) ID: 12812
Quest [Fiery Plate Gauntlets](https://wowgaming.altervista.org/aowow/?quest=5124) ID: 5124

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Windows 10

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Kitzunu** [comment]
Giving sources from post WotLK is useless as the quest was deprecated in 4.0.3

But I did find one wowhead comment from 3.1.1 confirming they looted the item without quest required. So seems legit
