### ISSUE TITLE
Stats of (summoned) pets not affected by global modfiers

### ISSUE THREAD

**Issue by duncrafter** [azerothcore/azerothcore-wotlk#11480]
### Current Behaviour

Health and Mana of enemy pets are currently not affected by global modifiers from worldserver_config.

Ex.: With Rate.Creature.Normal.HP = 0,5,, a Crawler (pet of Murloc Hunters in Westfall) should about 170-180 instead of the normal 350 hp.

### Expected Blizzlike Behaviour

Modifiers from worldserver.conf should affect enemy pets in the same way as any other mobs.

### Steps to reproduce the problem

1. Change global modifiers in worldserver.conf.
2. Target pet mob

### Extra Notes

Probably has the same root cause as https://github.com/azerothcore/azerothcore-wotlk/issues/9291
Health and mana formulas contain creature_template modifiers as floating values:

> float factorHealth = owner->GetTypeId() == TYPEID_PLAYER ? std::min(1.0f, cinfo->ModHealth) : cinfo->ModHealth;
        float factorMana = owner->GetTypeId() == TYPEID_PLAYER ? std::min(1.0f, cinfo->ModMana) : cinfo->ModMana;
 SetCreateHealth(std::max<uint32>(1, stats->BaseHealth[cinfo->expansion]*factorHealth));
        SetModifierValue(UNIT_MOD_HEALTH, BASE_VALUE, GetCreateHealth());
        SetCreateMana(stats->BaseMana * factorMana);
        SetModifierValue(UNIT_MOD_MANA, BASE_VALUE, GetCreateMana());

So it should probably work, or do we need an extra hook for worldserver.conf in Pet.cpp?

### AC rev. hash/commit

f13723097400d04cc9169dba1403255600bc575a

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-learnspells
mod-autobalance
mod-transmog
mod-arac

**Comment by duncrafter** [comment]
I may have found a solution. Global modifiers are sorted by creature rank (Normal, Elite etc.) and a certain modfier is only applied when a creature possesses the correct rank.

I found this line in Creature.cpp before the code for modifiers: `    uint32 rank = IsPet() ? 0 : cInfo->rank;`
My knowledge of coding is limited, but I think this means the creature's rank is only pulled from the database when it isn't a pet.

So all pets would have no applicable rank information and the following lines of code would go unused.

**Comment by UltraNix** [comment]
I don't think we want this. These modifiers should affect "normal" (not tamed) creatures, but not pets as they get modifiers from passive scaling auras or from players.

**Comment by UltraNix** [comment]
I don't think we want this. These modifiers should affect "normal" (not tamed) creatures, but not pets as they get modifiers from passive scaling auras or from players.
Just change their passive aura effects amounts.
