### ISSUE TITLE
[Hunter] Unable to issue pet attack commands while the Deterrence aura is active.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11488]
https://github.com/chromiecraft/chromiecraft/issues/3399

### Current Behaviour

While the Deterrence aura is active and the hunter's pet is not already in combat, the hunter will not be able to issue any hostile/attack actions or abilities to their pet.

### Expected Blizzlike Behaviour

The pet should follow the hunter's commands despite Deterrence being active.

### Steps to reproduce the problem

Cast [Deterrence](https://wowgaming.altervista.org/aowow/?spell=19263) (ID: 19263) while the pet is set to Defensive/Passive.
Order the pet to do an offensive action or /petattack a npc that it is not engaged in combat with the pet (for example, switching targets)
Notice the pet will not follow the hunter's commands

### Extra Notes

Pet not following hostile commands.
https://user-images.githubusercontent.com/100873791/164838025-8196aca6-f272-45fc-aabb-52dcf8f2008e.mp4

Pet will execute non-agressive commands and doing so will curiously cause it to engage in combat.
https://user-images.githubusercontent.com/100873791/164838107-b919edc3-d8e3-4791-9508-9f905930ed56.mp4

Pet will not execute special attacks while already in combat.
https://user-images.githubusercontent.com/100873791/164838129-323f6c96-a15e-4f62-b2c9-0990f3a533cd.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/343732ee0beef702181009e26c41722b87f9cbe2

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
No. Pet cannot attack if owner is pacified.
