### ISSUE TITLE
[Minor] [Desolace] Gelkis Rumbler NPC has multiple issues

### ISSUE THREAD

**Issue by freepizzas-dev** [azerothcore/azerothcore-wotlk#11486]
### Current Behaviour

The Gelkis Rumbler NPC in Desolace has problems with its spells.

Gelkis Rumbler casts Rock Shell (which is also broken on this NPC -- it never causes Enrage, just like [Issue 5077](https://github.com/azerothcore/azerothcore-wotlk/issues/5077)), when I don't think it should be able to.

Gelkis Earthcaller never casts [Summon Gelkis Rumbler.](https://tbc.wowhead.com/spell=9653/summon-gelkis-rumbler#used-by-npc) They should use this spell to resummon their minions.

I suspect the Earthcaller mob is supposed to summon the minion on spawn, the minion shouldn't be it's own world spawn, and the Earthcaller mob re-summons the mob whenever possible/necessary.

~~I also don't think Gelkis Rumbler is supposed to be wandering around the area before being summoned by Gelkis Earthcaller in battle.~~

Gelkis Rumbler is supposed to be <Gelkis Earthcaller's Minion>, hang out before combat, and not disappear when Gelkis Earthcaller dies.

### Expected Blizzlike Behaviour

Gelkis Rumbler shouldn't cast Rock Shell.
Gelkis Earthcaller should cast Summon Gelkis Rumbler in battle.
Gelkis Rumbler should be <Gelkis Earthcaller's Minion>.

### Source

Gelkis Rumbler - no Rock Shell: https://tbc.wowhead.com/npc=4661/gelkis-rumbler
Gelkis Earthcaller - Summon Gelkis Rumbler: https://tbc.wowhead.com/spell=9653/summon-gelkis-rumbler#used-by-npc

Video from retail https://youtu.be/BRv_iAAGqvk?t=160

I can't find any references online to Gelkis Rumbler being able to cast Rock Shell like that.

Note the comment on wowhead about the centaur re-summoning Gelkis Rumbler after defeating it, and the commenter suggesting you defeat the centaur first so that the re-summon doesn't happen.

It's hard to find evidence that an NPC *shouldn't* be there, and this isn't hard evidence, but note that [another Github project indeed removed permanent spawns of Gelkis Rumbler from their DB.](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/667)
### Steps to reproduce the problem

1. Go to Desolace (35, 82).
2. Observe Gelkis Rumbler wandering around the area, not marked as <Gelkis Earthcaller's Minion>.
3. Begin combat with Gelkis Earthcaller. Defeat Gelkis Rumbler first. Observe Gelkis Rumbler casting a broken Rock Shell spell, which never Enrages.
4. Notice that Gelkis Earthcaller never re-summons Gelkis Rumbler after defeating it.

### AC rev. hash/commit

343732ee0bee

### Operating system

Windows 10 x64/Any

**Comment by Gultask** [comment]
I found it odd too that a spell almost exclusive to TBC mobs was found in some random mob in the Old World. TBC Wowhead doesn't mention that the Rumbler possesses this spell.
However, I've found a video containing a Rumbler roaming around alongside the Earthcaller: https://youtu.be/43iofjBtis0?t=186

**Comment by freepizzas-dev** [comment]
Great find, thanks! Nice to have a solid record of blizzlike behavior for this mob.
