### ISSUE TITLE
Feature: issue review

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#11498]
### Describe your feature request or suggestion in detail

close all the issues that were resolved at the time and are still open, even issues from 2017 that maybe are already resolved

### Describe a possible solution to your feature or suggestion in detail

a simple suggestion to go cleaning the more than 1.1k of open Issues

### Additional context

98a007cddbf34b53f14317a320ef1d2da9d303a8

**Comment by Nyeriah** [comment]
Hey,

This isn't quite a suggestion to me, it's just the work that needs to be done. If you're aware of anything that was already fixed, please comment in the issue so we can closed it.

Thanks again!
