### ISSUE TITLE
[Warrior][PVP]Warrior died when using Shield Block with high resilience

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#11492]
### Current Behaviour

character attack warrior with  above 2 Bilion damage

### Expected Blizzlike Behaviour

High resilience is OK to cast Shield Block

### Steps to reproduce the problem

1.Using a Warrior to test with 1450+ resilience
2.Equip shield
3.Cast Shield Block
4.Use another character to attack warrior

You can see damage above 2 Bilion

### AC rev. hash/commit

965fb6f

### Operating system

Windows 10 x64

**Comment by muctwanted** [comment]
Not only a warrior, but also a paladin, I confirm that it is, this bug is triggered by the blocking stat.

**Comment by r0m1ntik** [comment]
#11239

**Comment by UltraNix** [comment]
Why this is not on critical prio?
