### ISSUE TITLE
died from some dungeon bosses then can not enter dungeon

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#11502]
### Current Behaviour

for now , the three faces(black temple), the grandmother, big gray wolf (karazhan), the prince (tempest keep),
this bosses are sure, if players all died at it , when the dungeon will always be battling area, no one can enter.

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

ubuntu 21 x64

**Comment by Kitzunu** [comment]
enter hash/commit
