### ISSUE TITLE
Hunter's battle pet dies

### ISSUE THREAD

**Issue by Panda8k** [azerothcore/azerothcore-wotlk#11505]
### Current Behaviour

After the hunter's battle pet dies, it is revived and the pet skill action bar disappears,It must be dismissed and then re-summoned.

### Expected Blizzlike Behaviour

Resurrection after death, action bar does not disappear

### Steps to reproduce the problem

1.pet dies
2.resurrect pets
3.View the pet action bar

### AC rev. hash/commit

none

### Operating system

Debian 10 x64

**Comment by Kitzunu** [comment]
Add commit hash
