### ISSUE TITLE
[Zul'Gurub] High Priestess Mar'li - Hatch Eggs

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11532]
### Current Behaviour

At pull 4 Spawns of Mar'li spawn directly under the boss.
Periodically the Spawn of Mar'li will spawn beneath a random player (boss too, maybe).
Can also spawn during spider phase.

[Footage of the fight in a local AC](https://www.youtube.com/watch?v=4mFZkX55IA4)

### Expected Blizzlike Behaviour

Mar'li spawns 4 Spawn of Mar'li on pull, hatching them from 4 eggs around her.

Mar'li should periodically cast [Hatch Eggs](https://wowgaming.altervista.org/aowow/?spell=24083) at the nearest Spider Egg to spawn one Spawn of Mar'li, activating one of the egg objects in the process, making it burst with the green goo vfx. Egg object entry: 179985

Spawn of Mar'li spawns at the hatched egg, not a player

Timer should be 25 to 30 seconds after pull and every 20 seconds after.

Mar'li should not cast Hatch Eggs in her spider form

### Source

https://user-images.githubusercontent.com/100873791/165079260-881ad33a-2c1e-41ad-a818-f6d24c7c6e28.mp4

WotLK fight recording, edited to appropriate speed because the [source](https://www.youtube.com/watch?v=AGWBIMIDWhQ) is sped-up 2x. Timer seems to be 20 seconds between each egg hatching.

https://www.youtube.com/watch?v=H40AGahQPAU&t=385s Timer seems to be the same

https://wowpedia.fandom.com/wiki/High_Priestess_Mar'li_(Classic)

### Steps to reproduce the problem

1. Observe the eggs are not being hatched, the adds spawn at a random player, and that they can spawn during spider phase.

### Extra Notes

[Spawn of Mar'li](https://wowgaming.altervista.org/aowow/?npc=15041) (ID: 15041)
The 4 eggs that should hatch on pull.
![egg](https://user-images.githubusercontent.com/100873791/165108688-7214ab28-4c68-42ce-b13c-baa3525e59e6.jpg)
![egg](https://user-images.githubusercontent.com/100873791/165108706-e6153b3c-9ebb-4f2e-9f0a-d06f3768cf87.png)

[Hatch Egg](https://wowgaming.altervista.org/aowow/?spell=24083) ID: 24083

I've also seen this spell: https://classic.wowhead.com/spell=24082/hatch-spider-egg which is 1 lower in its ID. Could be related? I thought it could be the one she casts at the start of the encounter.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/66fa80d9eada38051713d550b742e1514ad27bda

### Operating system

Windows 10

### Custom changes or Modules

- mod-eluna

**Comment by Lynethris** [comment]
Some changes and other fixes here if needed : https://github.com/TrinityCore/TrinityCore/pull/23212
