### ISSUE TITLE
Cant get creature / object from modules via map

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#11539]
### Current Behaviour

```
map->GetCreature(ObjectGuid)
map->GetGameObject(ObjectGuid)
```
cant return creature or gameobject if called from modules.

Maybe some other methods also returns nothing

### Expected Blizzlike Behaviour

I phoned to Blizzard and MS, they don't know what to say )

### Steps to reproduce the problem

try to use some code like this line
https://github.com/Nelnamara/mod_guildhouse/blob/0ec07426aef85a5233abf87b0659032743fdb45d/src/mod_guildhouse.cpp#L81

It not return creature

### AC rev. hash/commit

tested 10 revisions (1 year back) 
from
f13723097400  (26/04/2022)
to
599e6834a1a8  (30/04/2021)

### Operating system

Win7 x64

### Custom changes or Modules

https://github.com/Nelnamara/mod_guildhouse

**Comment by ZhengPeiRu21** [comment]
I have noticed this as well while working on Playerbot module. We have mostly worked around the issue but it would be very good to have it fixed. Some related stack traces can be found in the Playerbots repo if they are helpful to resolve.

**Comment by Bogir** [comment]
Last time it worked in revision 91081f4ad8fed98d7bdc9c0ae13d05c86032df9f from Aprill 26 2021 
And was broken with implementing ObjectGuid class in the next revision - f4c226423dc0811efccf8135b46bc7ff46aab940

So, may be @UltraNix can help to solve this bug?

**Comment by UltraNix** [comment]
Just fix your module. Guid is stored per map and it is not anymore created on spawnId loaded from db, just as in that code you linked.

**Comment by weiyu7615688** [comment]
@Bogir 
Did you solve it？

**Comment by Nyeriah** [comment]
I'll "fix" it

**Comment by weiyu7615688** [comment]
I really need this, and if you can fix this, that would be great.
@Nyeriah

**Comment by Nyeriah** [comment]
Use the new functions once https://github.com/azerothcore/azerothcore-wotlk/pull/14802 is merged

**Comment by weiyu7615688** [comment]
It solved my problem very well，thanks.
@Nyeriah
