### ISSUE TITLE
Trial of Crusader Heroic.. Lord Jaraxxus freeze

### ISSUE THREAD

**Issue by Valoriaz** [azerothcore/azerothcore-wotlk#11538]
### Current Behaviour

If you die during a fight especially during the knockback from the minions, the server crashes with no crash log or anything like that. The world server also stays running but nobody can connect. 
At first this error only appeared with a Retribution Paladin..but every day it hits more and more classes/specializations

https://wotlkdb.com/?npc=34780

### Expected Blizzlike Behaviour

The Server didnt Crash and you can re-enter the Raid.

### Source

-

### Steps to reproduce the problem

1. Create a Paladin and Spec to Retribution
2. Fight against the Lord and die
3. See what Happen (maybe try 3-4 times if the bug didnt appear)

### AC rev. hash/commit

AzerothCore rev. a1707b2d1417 2022-04-25 9:29:44 Master Branch (win64, Debug, Static)

### Operating system

Windows Server 2019

### Custom changes or Modules

mod-ah-bot
mod-autobalance
mod-learn-spells
mod-skip-dk-starting-area
mod solo-lfg
mod-solocraft
mod-transmog

**Comment by zqgmzq** [comment]
confirmed

**Comment by zqgmzq** [comment]
Add Server Crash to issue name

**Comment by Kitzunu** [comment]
if it is a crash there should be a crashlog. Please include it.

**Comment by Valoriaz** [comment]
The Server didnt "Crash" everyone get kicked from the Server and nobody can login again ..til the server would be restarted manually

**Comment by PsYchoNauTek** [comment]
Can Confirm that issue!

Right when somebody dies when the Infernals are up server freezes

**Comment by PsYchoNauTek** [comment]
the error message u get btw is not directly the freeze issue...

the function had a bit of a refactor and got changed from naming a bit...
reverted that to the changes which maxtor coder did 2,5 years ago... doesn't give me any errors now anymore on the velocity stuff

here u can look on it how it should look like so it doesn't give the velocity error:

https://app.bountysource.com/issues/87382051-fix-core-creaturegroups-fix-movesplineinitargs-validate-errors

**Comment by Kitzunu** [comment]
Go into config add enable freeze detector and give the crashlog please.

**Comment by mpfans** [comment]
The test was not frozen many times

https://youtu.be/efDR4o04z30

AC version :9bebd6a05e4a251a87a1d22b347da2e0a6a13336
