### ISSUE TITLE
[server]worldserver crash0427

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11548]
### Current Behaviour

crash log:

https://gist.github.com/mpfans/38c4739fdf31063a6de57eba80f9312d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

4ec69ba3edfecd21d3cac843200515e87512bb8f + PR [11493 ](https://github.com/azerothcore/azerothcore-wotlk/pull/11493) + PR [11495](https://github.com/azerothcore/azerothcore-wotlk/pull/11495)

### Operating system

ubuntu 20.04

**Comment by Kitzunu** [comment]
update your core https://github.com/azerothcore/azerothcore-wotlk/commit/8d3c183345b475db51ddd8ead61ad60862a40288 already fixed this.
