### ISSUE TITLE
Wrong DB errors about mail_loot_template

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1155]
Revision: b1b48b9

The core is currently reporting the following errors:

> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 90 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 119 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 124 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 140 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 180 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 183 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 216 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 217 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 218 isn't mail template id and not referenced from loot, and then useless.
> 2018-12-26 15:46:14 Table 'mail_loot_template' entry 270 isn't mail template id and not referenced from loot, and then useless.

However those errors are wrong. They say those entries are "useless", but **they are not**. If you remove them, some things will break. Some tests performed by @wetbrownsauce proved that if you remove them:

> Quest 7735 No longer includes a Rugged Armor Kit in the mail sent to the player after handing in.
> Quest 9671 No longer includes A Letter from the Admiral in the mail sent to the player after handing in. (which is important since it begins the next quest in the chain).
> Quest 10588 No longer includes a Letter from Shattrath in the mail sent to the player after handing in.
> Quest 13960 & possibly also 13959 No longer include the pet in the mail sent to the player after handing in.

Further investigation is needed to understand why the errors are displayed, however there is something wrong for sure.

**Comment by wetbrownsauce** [comment]
Everything which involve those mail templates are as follows for testing purposes:

- [7735 - Pristine Yeti Hide](https://wowgaming.altervista.org/aowow/?quest=7735) (mail_loot_template id 119)
- [8644 - Stonefort the Elder](https://wowgaming.altervista.org/aowow/?quest=8644) (mail_loot_template id 90)
- [8651 - Ironband the Elder](https://wowgaming.altervista.org/aowow/?quest=8651) (mail_loot_template id 124)
- [8682 - Skyseer the Elder](https://wowgaming.altervista.org/aowow/?quest=8682) (mail_loot_template id 140)
- [9671 - Urgent Delivery](https://wowgaming.altervista.org/aowow/?quest=9671) (mail_loot_template id 180)
- [10588 - The Cipher of Damnation](https://wowgaming.altervista.org/aowow/?quest=10588) (mail_loot_template id 183)
- [13960 - Back to the Orphanage](https://wowgaming.altervista.org/aowow/?quest=13960) (mail_loot_template id 270)


mail_loot_templates 216, 217, 218 aren't from quests, I believe they are maybe brew of the month club.

**Comment by StygianTheBest** [comment]
I posted this on Discord a while back. All are related to quests, so my guess is sorting this out will fix some uncovered quest bugs too. Lucky Red Envelope's are from the Lunar Festival Event. Then we have Brewfest, and a few other quests.
```

90  - 21746 - lucky red envelope
119 - 15564 - rugged armor kit
124 - 21746 - lucky red envelope
140 - 21746 - lucky red envelope
180 - 24132 - leter admiral
183 - 31698 - letter shattrath
216 - 37902 - springtime stout
217 - 37903 - blackrock lager
218 - 37904 - stranglethorn brew
270 - 46544, 46545 - curious wolvar pup, curious oracle hatchling

Table 'mail_loot_template' entry 90 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 119 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 124 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 140 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 180 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 183 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 216 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 217 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 218 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 270 isn't mail template id and not referenced from loot, and then useless.
```
