### ISSUE TITLE
[ZG] Gahz'ranka - Massive Geyser NPC does not cast Water

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11563]
### Current Behaviour

When summoned from the spell Massive Geyser (Spell ID: 22421), the NPC Massive Geyser (NPC ID: 14122) does not cast Water (Spell ID: 22422) but instead performs a melee attack.
Edit: The water splash visual effect works.

### Expected Blizzlike Behaviour

Massive Geyser should cast Water (ID: 22422) and not perform melee attacks.

### Source

https://youtu.be/wRQCZkunULk?t=37

### Steps to reproduce the problem

1. `.additem 19975 5`
2. `.additem 19974`
3. `.go xyz -11695 -1770 13 309` Teleports to Pagle's Pointe

1. Engage Gahz'ranka
2. Observe the combat log once the Massive Geyser is summoned

### Extra Notes

When used by players against other players, Massive Geyser seems to work fine.

Most WotLK videos show Massive Geyser not having any effects. That is because Water can miss, and since the Geyser will be at a lower level than the player, it misses often. Here's a video showing the Geyser successfully casting Water on a level 80 player: https://youtu.be/JEmFTdr65UY?t=236

Edit: From looking at a couple of videos I'd say that the timer for Massive Geyser is near the 12-30s window

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Windows 10

**Comment by Maelthyrr** [comment]
Have you check if it's knockback players ? There are a comment about this in the code.

**Comment by Gultask** [comment]
@Maelthyrr yes, when the Massive Geyser NPC casts Water it has a knockback effect, but I'm pretty sure the knockback is working if you use .learn 22422 or .learn 22421 on a player character

**Comment by avarishd** [comment]
Knockback works, set unit_flag to 131072 (PACIFIED - Creature will not attack) and it's fixed

**Comment by Maelthyrr** [comment]
It's ok  :) , just to sure because in the code, there is a comment that say not working.
