### ISSUE TITLE
DB errors about `achievement_criteria_data`

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1156]
Revision: b1b48b9

The table `achievement_criteria_data` produces the following startup errors:

> 2018-12-26 15:46:14 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4989 Type: 19), ignored.
> 2018-12-26 15:46:14 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4988 Type: 19), ignored.
> 2018-12-26 15:46:14 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5620 Type: 73), ignored.
> 2018-12-26 15:46:14 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5632 Type: 73), ignored.
> 2018-12-26 15:46:14 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 5619 Type: 73), ignored.
> 2018-12-26 15:46:14 Table `achievement_criteria_data` has data for non-supported criteria type (Entry: 4987 Type: 19), ignored.

We tried to remove them from the database and this is the feedback from testing by @wetbrownsauce:

> As for the achievement_criteria changes, most of the affected achievements are actually statistics for number of 5 player, 10 player, and 25 player instances entered. These don't appear to work before or after the PR, so the changes in their db table make no difference aside from removing start up warnings/errors.

**Comment by wetbrownsauce** [comment]
Some additional info about the specific entries referenced in case it can help with testing:

- Entry 4987 in achievement_criteria.dbc is linked to Entry 932 in achievement.dbc which is "Total 5-player dungeons entered".
- Entry 4988 in achievement_criteria.dbc is linked to Entry 933 in achievement.dbc which is "Total 10-player raids entered".
- Entry 4989 in achievement_criteria.dbc is linked to Entry 934 in achievement.dbc which is "Total 25-player raids entered".
- Entry 5619 in achievement_criteria.dbc is linked to Entry 1241 in achievement.dbc which is "Mal'Ganis defeated (Caverns of Time: Stratholme)".
- Entry 5620 in achievement_criteria.dbc is linked to Entry 1515 in achievement.dbc which is "Mal'Ganis defeated (Heroic CoT: Stratholme)".
- Entry 5632 in achievement_criteria.dbc is linked to Entry 1103 in achievement.dbc which is "Lich King 5-player dungeons completed (final boss killed)".

**Comment by StygianTheBest** [comment]
I posted this on Discord a while back. All are related to quests, so my guess is sorting this out will fix some uncovered quest bugs too. Lucky Red Envelope's are from the Lunar Festival Event. Then we have Brewfest, and a few other quests.
```

90  - 21746 - lucky red envelope
119 - 15564 - rugged armor kit
124 - 21746 - lucky red envelope
140 - 21746 - lucky red envelope
180 - 24132 - leter admiral
183 - 31698 - letter shattrath
216 - 37902 - springtime stout
217 - 37903 - blackrock lager
218 - 37904 - stranglethorn brew
270 - 46544, 46545 - curious wolvar pup, curious oracle hatchling

Table 'mail_loot_template' entry 90 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 119 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 124 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 140 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 180 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 183 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 216 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 217 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 218 isn't mail template id and not referenced from loot, and then useless.
Table 'mail_loot_template' entry 270 isn't mail template id and not referenced from loot, and then useless.
```

**Comment by grimgravy** [comment]
remove achievement_criteria_data can not be added (type 19, 73)

**Comment by FrancescoBorzi** [comment]
@grimgravy what do you mean?

**Comment by grimgravy** [comment]
[Achievement_Criteria.dbc](https://wowdev.wiki/DB/Achievement_Criteria) type 19(COMPLETE_RAID)
[achievement_criteria_data](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129964/achievement+criteria+data) type 12(TYPE_MAP_DIFFICULTY)
in the game does not have difficulty statistics
