### ISSUE TITLE
[Quest] A Necessary Distraction

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#1159]
##### SMALL DESCRIPTION:

While doing quest, and killing these Sunfury Warlocks or Summoners, the Azaloth attacking you too, which is wrong. Also while banished he should be immune, not attackable ( The Banish state is wrong too, doesn't apply Visual on Azaloth)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Azaloth can be found south side of the Black Temple. He's currently being held "banished" by several Sunfury blood elves. Players will need to kill Sunfury Warlocks or Summoners (not necessarily the ones holding Azaloth) until one drops a  [Scroll of Demonic Unbanishing]. Use the scroll on the demon to release him. You do not need to defeat Azaloth, but he will attack you ( After you use Scroll on him ).
Until that he should be Immune while Banished
[Here is link of video](https://youtu.be/1pTminRkW68?t=29)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .quest add 10688  and .quest add 10637
2.  .go xyz -3878.602783 364.436432 129.075577 530
3. Try to attack Summoners ( Sunfury Warlocks )
4. The Azaloth will attack you too when you get near him which is wrong (He should be immune)
5. Also the Visaul on on him is wrong ( While Banished )
6. After using the Scoll on him, the look is same ( Which is wrong )
PS. Quest can be done, SAI need to be updated

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

585d293

##### OPERATING SYSTEM:

Windows Server 2012 R2

**Comment by FrancescoBorzi** [comment]
@poszer please fill the `AC HASH/COMMIT:` field

**Comment by DARKENE** [comment]
Hi @Confirm

If can't to compelete this quest, other quest not done! (Important)

please fixed.

**Comment by poszer** [comment]
> Hi
> Confirm
> If can't to compelete this quest, other quests not done! (Important)
> please fixed.
> 
> 80% send reports , 5% solving problems"fixs"
> 
> what is the problem, why the team is weak?

Bcoz of people like you. Simple

**Comment by FrancescoBorzi** [comment]
@DARKENE this is a learning project where people work in their free time. So why don't you learn and help us fixing things too? :)

**Comment by DARKENE** [comment]
I know, But the project will to been abandoned.

that's a pity .

**Comment by FrancescoBorzi** [comment]
It will not as long as there will be people working on it. You can increase the chances that it will not by joining our team.

And, to be honest, for being a WoW emulation project in 2019 I think we are doing great.

**Comment by peti446** [comment]
Still an issue, here is some references: 
https://www.youtube.com/watch?v=Nn_fDNtOKUw
https://www.youtube.com/watch?v=VYiVWn8qBcw


Tested on https://github.com/azerothcore/azerothcore-wotlk/commit/003fa8773144dede989e67448bd2ffdee5222d36
