### ISSUE TITLE
Not work quest The Great Fras Siabi 

### ISSUE THREAD

**Issue by Chrisjiajun** [azerothcore/azerothcore-wotlk#116]
Quest:The Great Fras Siabi  (ID: 5214)
Error condition:Error gameobject

Steps to reproduce the problem:
.quest add 5214	.go 3482 -3292 132 329	（gameobject entry=176248）

AC hash/commit:
1f16a06

Modules:
Nothing

Operating system: 
Windows 10

**Comment by HeartWell** [comment]
Maybe close?

**Comment by ShinDarth** [comment]
@HeartWell did you test the suggested fix?

**Comment by HeartWell** [comment]
Don't work. And how do you make the merge without checking?

**Comment by talamortis** [comment]
just input the sql into the database then restart the server and test

**Comment by HeartWell** [comment]
Realy? You think i stupid?

**Comment by ShinDarth** [comment]
@HeartWell  why did you ask to close this? I didn't understand what you mean

**Comment by talamortis** [comment]
@ShinDarth  could you test i think @HeartWell has a bit of a problem.

**Comment by ShinDarth** [comment]
sorry I am without dev environment at the moment

**Comment by HeartWell** [comment]
You did merge I thought fixed and can be closed, but is not.

**Comment by ShinDarth** [comment]
ok

**Comment by talamortis** [comment]
@HeartWell do you have error as you enter the quary?

**Comment by Krath** [comment]
The fix works fine. The query returns errors because of the "--Fix #116" line.

**Comment by talamortis** [comment]
Removed the comment :)

**Comment by ShinDarth** [comment]
@Krath if you test the PR, please leave feedback here: https://github.com/azerothcore/azerothcore-wotlk/pull/167
