### ISSUE TITLE
[Hunter] Volley should not allow auto shots to be made during its channeling

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11613]
https://github.com/chromiecraft/chromiecraft/issues/3437

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

While channeling Volley, Auto Shots continue to fire during the channel.

### Expected Blizzlike Behaviour

Auto Shot should pause while Volley is channeling. All skills that require the hunter to channel, should Queue up the shot timer for Auto Shot, but not release the shot until channeling is finished.

### Source

I've tried to look for as many sources as possible where auto-shot is being fired before Volley.

https://youtu.be/FYziN8llxh0?t=300
https://youtu.be/L1BoDfyij2A?t=178
https://youtu.be/YHtsRRj8VoU?t=116
https://youtu.be/8LwN82kribA?t=167
https://youtu.be/3mIl31Vlvj4?t=143

https://www.warcraftmovies.com/movieview.php?id=123709
>Around 3:12 mark they cast a spell, which enacts auto shots. As they are still targeting ony, they cast volley, which stops all actions besides volley. Another mark at 4:05, they cast auto shot, and instantly after cast volley. You'll notice autos are suspended during volley channel time.

### Steps to reproduce the problem

Volley a mob with Auto Shot active ie /startattack. witness Auto Shot casting during the channel.

### Extra Notes

I know that this was also posted here https://github.com/azerothcore/azerothcore-wotlk/issues/7067 but the original poster in CC contested it so we investigated a bit further (thanks @Cooties-cc) and gathered all the evidence we could.

From the original poster:
>SPELL_ATTR2_NOT_RESET_AUTO_ACTIONS is correct. It does NOT reset Auto Shots, the timer still continues while channeling, but while channeling volley it should pause(lock) all other actions including Auto Shot.
>Trinity has SPELL_ATTR2_DO_NOT_RESET_COMBAT_TIMERS tag on Volley and it locks/pauses Auto Shot but still allows the timer to continue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by slicplaya** [comment]
Ty sir

**Comment by Gultask** [comment]
I'll add something that I only noticed today. While channeling, if you target an enemy with right-click, with will give the error message "Cannot attack while channeling"
Don't know how I missed that before.
