### ISSUE TITLE
[ZG] Edge of Madness - Issues with Gri'lek

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11611]
### Current Behaviour

Timer for Avatar is incorrect.
Not immune to taunt.
Entangling Roots is missing.
Avatar does not wipe all threat.

### Expected Blizzlike Behaviour

Timer for Avatar is around 20-30s after pull and every 45s after the first cast, with somewhat 5s variation. The buff duration is 15s so it should be ~30s of normal form, 15s of Avatar.
Should be immune to taunt, always.
Should periodically cast Entangling Roots on main target, dispellable.
Avatar should wipe all threat for the entire raid.

### Source

https://youtu.be/meLZivsuuZM?t=5450 Shows the threat wipe, normal phase lasting between 28s to almost 40s, and the entangling roots

https://www.youtube.com/watch?v=CW-boIS3ijc Vanilla-era footage, exactly 30s before another avatar phase

https://youtu.be/RS10NBtNu6g

### Steps to reproduce the problem

If the Summoning Event is implemented:
`.event stop 28`
`.event stop 29`
`.event stop 30`
`.event start 27`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Gri'lek

else:
`.go xyz -11905 -1911 66 309`
`.npc add temp 15082`

### Extra Notes

Gri'lek's Event ID: 27
Gri'lek (NPC ID: 15082)
Avatar (ID: 24646)
Ground Tremor (ID: 6524)
Entangling Roots (Probably ID: 24648)

Edit: After reviewing the sources, the timers look like:
Avatar: 20-30s after pull, 40-50s every one after that.
Roots: 12-18s
Tremor: uncertain, but *maybe* 12-26s. It seems to coincide somewhat with Avatar but it's probably coincidence.

There's also another, unknown, spell that Gri'lek occasionally casts on himself: https://youtu.be/RS10NBtNu6g?t=305

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d1b690e3fa89897b6eada5fc8ec11354227cf2d5

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask What is the timer for Roots?

**Comment by Gultask** [comment]
In vanilla-era footage I found 12-18s, but more concentrated in 12-16s, not reaching 18s or 19s very often. I tried looking at V/Cmangos and TC but neither had Roots. I'll re-watch the vanilla footage in a bit.

**Comment by UltraNix** [comment]
I set it to 10-20s
