### ISSUE TITLE
[Stratholme] Crimson Guardsman can be pulled separately from Conjurors and Initiates

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11623]
https://github.com/chromiecraft/chromiecraft/issues/3459

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When you pull (taunt) other mobs like Crimson Initiate (https://wowgaming.altervista.org/aowow/?npc=10420) or Crimson Conjuror (https://wowgaming.altervista.org/aowow/?npc=10419) at Stratholme Living Side, the Crimson Guardsman (https://wowgaming.altervista.org/aowow/?npc=10418) alongside them doesn't get pulled. 

### Expected Blizzlike Behaviour

When you taunt one mob of this pack of Scarlet Crusade NPCs at Stratholme Undead, every mob on that pack should be pulled too. Aggro is not working well on that mob.

### Steps to reproduce the problem

1. create level 60 character with ranged spells/attacks
2. `.go xyz 3633 -3112 135 329`
3. attack either a Guardsman or any other Crimson mob
4. see that not everyone is aggroed

### Extra Notes

Triager: In Keira3 the Guardsman has a different faction from the Conjurors and Initiates (Guardsman has faction ID 89 while the other two have faction ID 67)
Crimson Guardsman: (ID: 10418)
Crimson Conjuror (ID: 10419)
Crimson Initiate: (ID: 10420)

https://user-images.githubusercontent.com/100873791/166828843-9cde9592-4630-453c-9b4c-e54d219c2c14.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
Looks like both of them are Scarlet crusade, we might need some sniffs to check their correct faction id to change it. Im going to search, with luck there is already one sniff of that zone.

![image](https://user-images.githubusercontent.com/87535580/166932716-3d1766ae-9e68-44d5-8739-77484f76db6a.png)

**Comment by Gultask** [comment]
They are the only outliers too. Sorcerers, Priests, Gallants, Conjurors, Initiates, Defenders, Cannon Master, Monks, Battle Mages, Inquisitors, Archivist and even Balnazzar.

The skellies are faction 21 and they are hostile to the Guardsmen, while the other npcs are not.
But if you teleport to the entrance of the Scarlet Bastion, you'll see skeletons and guardsmen fighting each other which I just found out IS blizz-like: https://youtu.be/3yAOdhlXotw?t=475
So maybe it's intended after all?

**Comment by Gultask** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/12979
