### ISSUE TITLE
[BWL] Nefarian Pala class call blocks Everlasting Affliction

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11624]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

![Everlasting affliction](https://user-images.githubusercontent.com/100415626/166898065-9975df95-f8c5-447a-83de-a4f98fb707f9.png)

While Nefarian is bubbled from Paladin class call, Corruption is not getting refreshed by Haunt and Shadowbolt, Drain Life or Drain Soul casts.
On picture: Cooldown of Corruption is not getting refreshed by Haunt, Shadow Bolt or Drain Life on Paladin Class Call
![WoWScrnShot_050522_001234](https://user-images.githubusercontent.com/100415626/166835125-db42a8c0-9e10-4ccb-910d-32b19bc6d9e6.jpg)

EDIT: It has been brought to my attention by @Never6 that the same issue can be applied to Shadow Priest talent "Pain and Suffering" Mind Flay cannot refresh Shadow Word: Death on Paladin Class Call so it is likely related.

![Pain and Suffering](https://user-images.githubusercontent.com/100415626/166898277-3c6d8ab0-f6c8-4a62-b995-54be684703ec.png)

### Expected Blizzlike Behaviour

The bubble effect should affect only melee abilities. Apparently, the refresh from Everlasting Affliction might be counted as physical instead of magic.

### Steps to reproduce the problem

1.Spec into [Everlasting Affliction](https://db.rising-gods.de/?search=everlasting+affliction)
2, Engage Nefarian
3, Wait for Paladin class call
4, Cast [Corruption](https://db.rising-gods.de/?spells=7.9.355&filter=na=Corruption)
5,  Cast [Haunt](https://db.rising-gods.de/?spells=7.9.355&filter=na=Haunt) or [Shadow bolt](https://db.rising-gods.de/?spells=7.9.593&filter=na=Shadow%20bolt)
6. Notice that corruption is not getting refreshed

### Extra Notes
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3462

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/49191da0f8566a513a7313fa8215e67c7cb996ab

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Si1ker** [comment]
uff

![image](https://user-images.githubusercontent.com/61223313/167263481-46e8c37a-38ba-4c13-89a1-ebd36eb1a6a4.png)

**Comment by Dejanos** [comment]
> ?
> 
> ![image](https://user-images.githubusercontent.com/61223313/167263481-46e8c37a-38ba-4c13-89a1-ebd36eb1a6a4.png)

Almost impossible to find a Blizzlike raid source for Vanilla raids for spells that originated in WOTLK, the spell has no issues refreshing cooldowns in normal behavior, but does not refresh on Paladin class call which disables Physical damage, and therefore is not correlated, so I went with common sense, it is possible that bug persisted on Blizzard's side, but it will be unable to be tested until WOTLK Classic comes out and Warlocks get Everlasting Affliction.
