### ISSUE TITLE
Refresh NPC repeatedly

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11637]
### Current Behaviour

`Krolmir, Hammer of Storms` (quest id 13010) ,It will cause repeated refresh of NPC(creature id 30331)

https://youtu.be/N9WrL8Syk1Y

like https://github.com/azerothcore/azerothcore-wotlk/issues/5926

### Expected Blizzlike Behaviour

Whether you have a mount or not, you will be forced to dismount and sit on the king's shoulder

### Steps to reproduce the problem

1. `.quest a 13010 `
2. `.go xyz 7345.899902 -2812.949951 798.488281 571`
3. summon a mount
4.  talk `King Jokkum`(creature id 30105)
5. a new  `King Jokkum` (creature id 30331) will be refreshed ,but you didn't sit on the king's shoulder
6. dismount
7.The former king does not disappear

### AC rev. hash/commit

59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
apply https://github.com/azerothcore/azerothcore-wotlk/commit/56982f9ebabd90acbf0e066d3ec70a3f2d16dfda,

quest 13010 not complete

**Comment by mpfans** [comment]
@UltraNix

**Comment by UltraNix** [comment]
@mpfans Why re-open already closed by commit issue? Just open a new one.
