### ISSUE TITLE
[PTR] [ZG]: Son of Hakkar doesnt leave a poison cloud.

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11636]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

When [Son of Hakkar](https://db.rising-gods.de/?npc=11357) dies, Players nearby gets afflicted by the[ Poisonous Blood ](https://db.rising-gods.de/?spell=24320#triggered-by) cloud that he leaves on the ground.
But the Green poison cloud is missing on the Son of Hakkar Corpse.
![Poison Cloud](https://user-images.githubusercontent.com/100415626/166902696-52734545-5fca-4d61-94c2-342c90085e89.png)

### Expected Blizzlike Behaviour
[The Poison Cloud](https://db.rising-gods.de/?spell=24320#triggered-by) on [Son of Hakkar's](https://db.rising-gods.de/?npc=11357) Corpse is missing.
Players that are far away from the Son when it dies, Should be able to run in to the cloud later to get the [poisonous blood poison](https://db.rising-gods.de/?spell=24320#triggered-by).

This is a important mechanic for Hakkar fight.

### Source
[Official WoW Classic tactics explanation revolving the Son of Hakkar.](https://youtu.be/1S-4yBsgw5Q?t=936)
[
Son of Hakkar on Death Poisonous Blood in action on Classic WoW.](https://youtu.be/IWWV3CWLThI?t=194)

[Son of Hakkar WoWwiki, the spell in question is marked as unconfirmed, but it is apparent by the videos and sources.](https://wowpedia.fandom.com/wiki/Son_of_Hakkar)
### Steps to reproduce the problem
1. Kill [Son of Hakkar ](https://db.rising-gods.de/?npc=11357)in Zul'Gurub.
2. See he is not using [Poisonous Blood](https://db.rising-gods.de/?spell=24320#triggered-by) cloud on death.
### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3454
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by TheDdraig** [comment]
The SAI is setup to cast upon death, however the cloud does not stay on the cloud and I'm unable to find any info on how long it supposed to stay. If you can find this info, such as is the cloud supposed to last until despawn. https://www.wowhead.com/spell=24320/poisonous-blood this shows the debuff is tied into a spell effect script.

**Comment by Dejanos** [comment]
> The SAI is setup to cast upon death, however the cloud does not stay on the cloud and I'm unable to find any info on how long it supposed to stay. If you can find this info, such as is the cloud supposed to last until despawn. https://www.wowhead.com/spell=24320/poisonous-blood this shows the debuff is tied into a spell effect script.

From the video source I provided it seems the Poisonous Blood is a radius of 8 yards and from the video it stays on the ground for exactly 10 seconds.
