### ISSUE TITLE
Mirror bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11634]
### Current Behaviour

When the player get the quest  `Mending Fences` (quest id 12915) and kills the quest monster, loot the item `Slag Covered Metal` (item id 41556), then right-click `Slag Covered Metal` to get the quest `The Refiner's Fire` (quest id 12922), If the`The Refiner's Fire` is completed and the quest is returned, the player will not be able to complete `Mending Fences` (quest id 12915),because the Mirror has changed, you will not be able to see the target monster of the  `Mending Fences` (quest id 12915) quest.

### Expected Blizzlike Behaviour

if player have `Mending Fences` (quest id 12915) ,does not switch mirror

### Steps to reproduce the problem

1. `.quest a 12915`
2. `.quest a 12922`
3. `.quest c 12922`
4. `.go xyz 7217.320312 -3636.736084 824.563965 571`
5. Return the quest
6. `.go xyz 7306.065918 -3160.722412 837.451050 571`
7. you cannot see the target monster of the `Mending Fences` (quest id 12915)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

ubuntu 20.04

**Comment by UltraNix** [comment]
Cannot reproduce it. Was able to complete and reward both quest at the same time.

**Comment by UltraNix** [comment]
@mpfans
