### ISSUE TITLE
[Warlock] - Clunky Conflagrate ability

### ISSUE THREAD

**Issue by vtihomirov** [azerothcore/azerothcore-wotlk#11641]
### Current Behaviour

There is almost 1 second delay between immolate debuff application and Conflagrate usage availability.
A message in the combat log states (You can't do that yet).

https://youtu.be/J1Wg3jQaylA

### Expected Blizzlike Behaviour

There shouldn't be any usage delay between immolate debuff application and Conflagrate availability, if immolate is applied you should be instantly able to use Conflagrate.

### Source

https://youtu.be/u1DW76nu20c?t=68

### Steps to reproduce the problem

1. Create a warlock character.
2. Learn Conflagrate skill from the destruction talent tree.
3. Go to training dummy and see if you can reproduce the video: https://youtu.be/J1Wg3jQaylA

### AC rev. hash/commit

AzerothCore rev. 6a58d1ee69fd 2022-05-05 05:04:53 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80029
Using CMake version: 3.16.3
Compiled on: Linux 5.13.0-40-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 291218471 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196330140 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS deDE 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by avarishd** [comment]
Source isn't even from wrath.
https://github.com/chromiecraft/chromiecraft/issues/1136 
Bonus source to the link above - https://youtu.be/IMoYxz3avF0?t=85

**Comment by vtihomirov** [comment]
> [chromiecraft/chromiecraft#1136](https://github.com/chromiecraft/chromiecraft/issues/1136) Source isn't even from wrath.

Will close this as it seems blizzlike by the reports. Thanks for the quick response :+1:
