### ISSUE TITLE
 can move `Valkyrion Must Burn` 

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11643]
### Current Behaviour

When the player obtains the quest `Valkyrion Must Burn` (id 12953), mount a `Valkyrion Harpoon Gun`(creature id 30066) and then move the `Valkyrion Harpoon Gun`(creature id 30066) 

https://youtu.be/mHoJfsUbw6A

### Expected Blizzlike Behaviour

`Valkyrion Harpoon Gun`(creature id 30066) it has a fasten position and cannot be moved

### Steps to reproduce the problem

1. `.go xyz 7354.860352 -80.268097 777.624817 571`
2. `.quest a 12953`
3. mount a `Valkyrion Harpoon Gun`
4.  use the `ADWS` of the keyboard to move it

### AC rev. hash/commit

59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

ubuntu 20.04

**Comment by Gultask** [comment]
Didn't work at first but if I dismounted the harpoon gun and mounted back up again it could be moved.
Tested on https://github.com/azerothcore/azerothcore-wotlk/commit/6a58d1ee69fdc9ac310c2d9de436289c132d1fef
