### ISSUE TITLE
[Warrior] Spell Charge (ID: 100) does not initiate auto-attacks.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11653]
https://github.com/chromiecraft/chromiecraft/issues/3460

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Tab targeting (or left-click targeting) a mob and using charge (rank 1) results in your character stood in melee range of the mob, doing nothing. (Note: if auto attack is enabled with right-click prior to charging, charge does not turn it off)

https://user-images.githubusercontent.com/100873791/167181052-b60060a7-fbb1-4302-b8e6-dc7929895081.mp4

### Expected Blizzlike Behaviour

Charge should start your auto attack.

### Source

Triager: I've found 4 videos, none of them are from WotLK, however. Note that when charge starts, the character pulls out their weapon.
https://youtu.be/VufhWXi4K14?t=192 and at 4:50 6:10 6:46
https://youtu.be/u6y22hDEALo?t=88
https://youtu.be/9RSvCXut4VY?t=441
~~https://youtu.be/0x85I_VLjJE?t=5~~ Auto-attack is started before the Charge happens.
https://youtu.be/9wm18nghVi8?t=810 is from WoW Clasic

### Steps to reproduce the problem

1. Left-click a creature
2. Use Charge (ID: 100)

### Extra Notes

OP: As for a source, I'm not sure if it's good enough, but the wowhead spell link has the tag "Attack on Charge to Unit", link: https://www.wowhead.com/spell=100/charge

See also: https://github.com/azerothcore/azerothcore-wotlk/pull/7235 https://github.com/azerothcore/azerothcore-wotlk/pull/10541 https://github.com/azerothcore/azerothcore-wotlk/pull/7316 https://github.com/azerothcore/azerothcore-wotlk/pull/8978
And sorry for the unreliable sources, I'll update the issue if I find better ones.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by benjymansy123** [comment]
Can confirm, charge sets you to auto-attack on TBC Classic.

**Comment by Gultask** [comment]
@benjymansy123 Hey, Benjy, could you give us a video of it? OBS Studio is pretty good for recording stuff if you don't have a recording software, and it's free too.

**Comment by benjymansy123** [comment]
https://youtu.be/q1UA4FYA0a4

First test with tab targetting, second with left click, third with right click.

**Comment by Gultask** [comment]
Thanks for helping us out, benjy! ❤️
