### ISSUE TITLE
logs table no data

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11660]
### Current Behaviour

updated to e4e458f3fad3b82bbfbdf6b1f4f2bb6b152591d7 + PR 11656

`auth.logs` table  no data. There is data before updating the AC core.

Now players will not record IP information or chat records when logging in, which works before updating the AC core

With my worldserver.conf
```
Appender.Console=1,4,0,"1 9 3 6 5 8"
Appender.Server=2,5,15,Server.log,w
Appender.GM=2,5,15,gm_%s.log
Appender.DBErrors=2,5,0,DBErrors.log
Appender.DB=3,5,0

Logger.root=2,Console Server
Logger.commands.gm=4,Console GM
Logger.diff=3,Console Server
Logger.mmaps=4,Server
Logger.scripts.hotswap=4,Console Server
Logger.server=4,Console Server
Logger.sql.sql=2,Console DBErrors
Logger.sql=4,Console Server
Logger.time.update=4,Console Server
Logger.module=4,Console Server

Logger.chat.log=5,DB
Logger.chat.log.addon=4,DB

Logger.entities.player.character=4,DB
Logger.entities.player=4,DB
```

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

updated to e4e458f3fad3b82bbfbdf6b1f4f2bb6b152591d7 + PR #11656

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
Sorry, I queried the wrong server

**Comment by acidmanifesto** [comment]
> Sorry, I queried the wrong server
> 
> 

https://github.com/azerothcore/azerothcore-wotlk/pull/11601
