### ISSUE TITLE
[server]world crash0508

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11679]
### Current Behaviour

crash log:

https://gist.github.com/mpfans/a957c7006fcff4f56e1718c201ba074d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

aeb260c3cc14dfb5bfb0a3cd2540db534c993df3 + PR #11656

### Operating system

ubuntu 20.04

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/11650
