### ISSUE TITLE
Compile failure on Linux (Raspberry Pi 4)

### ISSUE THREAD

**Issue by xathian** [azerothcore/azerothcore-wotlk#11698]
### Current Behaviour

Compilation fails very quickly after beginning. CMake appears to run fine with no errors. This is the entire Make from start to fail

pi@RaspberryPi4:/home/pi/azerothcore/build# make -j 4
[  0%] Building CXX object deps/fmt/CMakeFiles/fmt.dir/src/format.cc.o
[  0%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourAlloc.cpp.o
[  0%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/Recast.cpp.o
[  0%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/AABox.cpp.o
[  0%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourAssert.cpp.o
[  0%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourCommon.cpp.o
[  0%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastAlloc.cpp.o
[  0%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMesh.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastAssert.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastArea.cpp.o
In file included from /home/pi/azerothcore/deps/g3dlite/source/AABox.cpp:14:
In file included from /home/pi/azerothcore/deps/g3dlite/include/G3D/AABox.h:20:
In file included from /home/pi/azerothcore/deps/g3dlite/include/G3D/Array.h:19:
In file included from /home/pi/azerothcore/deps/g3dlite/include/G3D/MemoryManager.h:15:
In file included from /home/pi/azerothcore/deps/g3dlite/include/G3D/ReferenceCount.h:16:
/home/pi/azerothcore/deps/g3dlite/include/G3D/AtomicInt32.h:129:31: error: invalid output constraint '=a' in asm
                            : "=a" (nz)
                              ^
/home/pi/azerothcore/deps/g3dlite/include/G3D/AtomicInt32.h:161:31: error: invalid output constraint '=a' in asm
                            : "=a" (ret)
                              ^
In file included from /home/pi/azerothcore/deps/g3dlite/source/AABox.cpp:14:
In file included from /home/pi/azerothcore/deps/g3dlite/include/G3D/AABox.h:20:
In file included from /home/pi/azerothcore/deps/g3dlite/include/G3D/Array.h:20:
/home/pi/azerothcore/deps/g3dlite/include/G3D/System.h:528:19: error: invalid output constraint '=a' in asm
                : "=a" (timelo),
                  ^
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshBuilder.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastContour.cpp.o
3 errors generated.
make[2]: *** [deps/g3dlite/CMakeFiles/g3dlib.dir/build.make:63: deps/g3dlite/CMakeFiles/g3dlib.dir/source/AABox.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:719: deps/g3dlite/CMakeFiles/g3dlib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object deps/fmt/CMakeFiles/fmt.dir/src/os.cc.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNavMeshQuery.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastFilter.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastLayers.cpp.o
[  1%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNode.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMesh.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMeshDetail.cpp.o
[  1%] Linking CXX static library libfmt.a
[  1%] Linking CXX static library libDetour.a
[  1%] Built target Detour
[  1%] Built target fmt
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRasterization.cpp.o
[  1%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastRegion.cpp.o
[  1%] Linking CXX static library libRecast.a
[  1%] Built target Recast
make: *** [Makefile:130: all] Error 2

### Expected Blizzlike Behaviour

It should compile?

### Steps to reproduce the problem

1. Git source
2. Run CMake
3. Make

### Extra Notes

CMake version 3.16.3
Clang 11
Clang++ 11

### AC rev. hash/commit

774c41b

### Operating system

Raspbian 10 (Debian 10 buster)

**Comment by Kitzunu** [comment]
Raspberry PI is not supported, also this is an error in dependencies.

**Comment by xathian** [comment]
Holy shit you're useless
