### ISSUE TITLE
Crash on group queue

### ISSUE THREAD

**Issue by Nefertumm** [azerothcore/azerothcore-wotlk#11697]
### Current Behaviour

https://gist.github.com/Nefertumm/c5174f71c21a09be4988e36709b15f24

note that the branch is not master, but the issue is present on master anyway.

Also happened on ChromieCraft.

https://gist.github.com/Nefertumm/c3108bc1c5754a7aa543df81dd96e94b

### Expected Blizzlike Behaviour

No crash and probably a message error telling you something about your group is already on queue.

### Steps to reproduce the problem

1. Group up with 3 players.
2. Queue to bg as group.
3. Leave the queue with the leader
4. Try to queue again as group in the same bg and other bgs as well.
5. If not crashed already, leave the queue with the other chars and try to requeue again with the leader as group.

### AC rev. hash/commit

a3bf902c6d488b22cf295b0081223101acd78d57

### Operating system

W11

### Custom changes or Modules

mod-cfbg and a bunch others, basically the same as CC uses.

**Comment by Kitzunu** [comment]
How to reproduce? Sounds odd to me that you are able to queue twice.

**Comment by Nefertumm** [comment]
The steps to reproduce it are there already...

**Comment by Kitzunu** [comment]
Oh im blind

**Comment by UltraNix** [comment]
@Nefertumm Your steps do not work. I cannot queue as a leader again if someone is still in the queue.

**Comment by UltraNix** [comment]
@Nefertumm These "Steps to reproduce" do not work. I can't queue up for bg as a leader again if there is someone in the queue already.

**Comment by Nefertumm** [comment]
@UltraNix Leave the queue with other characters in group after trying to queue again with the leader

**Comment by UltraNix** [comment]
Still the same. No crash if someone else left the queue.
If all left the queue, then I can queue up again and no crash.

**Comment by Nefertumm** [comment]
https://user-images.githubusercontent.com/19627365/168441321-c742b900-1299-4cf3-9215-d807794d2c30.mp4

There you go, sometimes it crashes "easily" and sometimes it doesn't. :/

**Comment by UltraNix** [comment]
Sorry, but even with this video I can't reproduce it :(
