### ISSUE TITLE
[Tallents/Palladin] Infusion of Light (ID - 53569/53576) - Second Effect Dont Work

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#11707]
### Current Behaviour

Work:
Your Holy Shock critical hits reduce the cast time of your next Flash of Light by 1.5 sec or increase the critical chance of your next Holy Light by 20%.

Dont Work:
In addition, causes your Flash of Light to heal targets with Sacred Shield for an additional 100% over 12 sec.

### Expected Blizzlike Behaviour

Tallent fully work

### Steps to reproduce the problem

1) Take Infusion of Light tallent in holy spec
2) Use Sacred Shield on friendly player
3) Use Flash of Light on friendly player

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/32b7531295f7e3d776d3c39ec215c200aa1da312

### Operating system

Debian 11 x64

**Comment by Kitzunu** [comment]
@Nyeriah maybe included in the generic issue of 2nd dbc effects not working

**Comment by UltraNix** [comment]
![obraz_2022-07-24_124301875](https://user-images.githubusercontent.com/80540499/180643538-970cfb4f-1132-4dc9-9757-658d124fc26f.png)
Works okay.
