### ISSUE TITLE
[Silithus] Issues with Abyssal Lords loot tables.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11712]
https://github.com/chromiecraft/chromiecraft/issues/3485

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

1. Can get both epic and rare (purple and blue) gear items from single kill of a boss (both live and PTR).

Details:

On PTR, I noticed that for some kills I can get all 3 gear items (elemental focus bands, rare shoulder, and rare wrist) from 1 kill. (Don't know how to attach a screeshot.) Then I recalled that this also happened on live. (I got earthen guard and a cloth hit shoulder from one of my recent kill of the rock giant boss.) I wonder whether it means the drop rate of the three items are independent on each other and whether this is blizzlike.

### Expected Blizzlike Behaviour

Only one piece of gear should drop at a time.

### Source

There was no comment mentioning the possibility of more than one piece of gear dropping.
>He dropped Scepter, the Epic cape and essence of earth ([source](https://classic.wowhead.com/npc=15204/high-marshal-whirlaxis#comments:id=2798664))

>Dropped the bracers and the scepter. No neck ([source](https://classic.wowhead.com/npc=15305/lord-skwol#comments:id=2918575))

>got the shield, scepter & 2 essences. ([source](https://classic.wowhead.com/npc=15205/baron-kazum#comments:id=2918355))

>The scepter drops with a rate of 100%. The epic ring with a rate of about 50% or instead of it, the prince drops a blue item for shoulders or wrists. ([source](https://classic.wowhead.com/npc=15203/prince-skaldrenox#comments:id=2824987))

https://youtu.be/65ZLfNHtC78?t=217
https://youtu.be/N9lv_ygjUbw?t=169
https://youtu.be/hs7qspfr1f8?t=10
https://youtu.be/zvHNPnQ8E8E?t=221
https://youtu.be/CbNno7Uxk-M?t=165

### Steps to reproduce the problem

1. `.additem 20451` `.additem 20422` `.additem 20408` `.additem 20406` `.additem 20407`
2. equip them all
3. summon a Abyssal Lord from a Greater Windstone
4. loot and respawn until you see an epic and a rare, or 2 rares drop at the same time

### Extra Notes

Prince Skaldrenox (ID: 15203)
Baron Kazum (ID: 15205)
Lord Skwol (ID: 15305)
High Marshal Whirlaxis (ID: 15204)

All loot tables look something like:

![image](https://user-images.githubusercontent.com/100873791/167758553-f42bf37e-51b4-4a39-a511-f6f5b48c5789.png)

The original poster claimed that the drop rates could be different between Live Chromiecraft and the CC PTR.
I don't know the technical parts of CC's loot tables so I wouldn't have been able to provide a decent answer and it would be a difficult bug to reproduce so I thought it was best to leave that part out of the AC report.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by hanabi5** [comment]
Where's evidence that they don't drop at the same time?
