### ISSUE TITLE
[LBRS] Crystal Fang summons infinite spiders.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11718]
https://github.com/chromiecraft/chromiecraft/issues/3494

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Crystal Fang spawns a billion spiders throughout the fight,

### Expected Blizzlike Behaviour

Crystal Fang only spawns 4 spiderlings at the beggining of the fight and upon death. 

### Source

![WoWScrnShot_050622_154919](https://user-images.githubusercontent.com/32701428/167886098-51c7f3ff-42a4-4ad8-82e6-5e0b7380c695.jpg)

![image](https://user-images.githubusercontent.com/32701428/167885855-f14b6620-2482-49ea-957b-a65cc525e740.png)

https://www.youtube.com/watch?v=IOvs2lMmQtE

~~https://youtu.be/syeB4KMpT-Y?t=145~~

### Steps to reproduce the problem

.go c id 10376

### Extra Notes

White Spider Meat

Triager: The SmartAI has the boss repeating the Summon Spire Spiderling (ID: 16416) spell every 5-10s

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by ChrisCGalbraith** [comment]
It looks like the spell 16416 summons 8 spiderlings. Comment on the vanilla video you linked from 2006 says that she spawns 8 spiders on death - and it looks like she summons 8 on death in the multiboxing one from the combat log (but who knows what core that uses).

Vanilla video doesnt appear to show it spawning 8 spiderlings after being pulled, the multiboxing one does.

Where are you getting that it should be 4 spawns then another 4 spawns?

**Comment by Gultask** [comment]
Ah sorry, for some reason I didn't realize that the multi-boxing video was no good, that was a dumb mistake from my part. But thanks for the new source! If it is 4 spiderlings at pull and 4 on death, together with the other Spire Spider it would add up to 12 total, and it is possible to see [starting here](https://youtu.be/bQhAE9H2K9c?t=485) around 11-12 spiderlings dying.

**Comment by ChrisCGalbraith** [comment]
I think you're right there's about 12 at the end. 4 before the fight, 4 from the elite spider then 4 from crystal fang dying - Ill set up a PR for him to spawn 4 adds when dying tomorrow.

Do you know if Crystal Fang is meant to have 4 spiderlings around him, or does he take the place of a regular elite spider and there just happens to always be small adds in that spot?

**Comment by Gultask** [comment]
Very sorry for the delay. But I think maybe?

Comparing the [previous video](https://youtu.be/bQhAE9H2K9c?t=439) to [this one from WoW Classic](https://youtu.be/pnOM3mBlTa0?t=4229), you can see a common Spire Spider in the same wander location as Crystal Fang.
