### ISSUE TITLE
[Shaman][T1] The Earthfury set bonus 3/8 does not apply to all totems and creates tooltip inconsistencies.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11720]
https://github.com/chromiecraft/chromiecraft/issues/3493

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

#### OP: ####
There seems to be a mismatch in areas of effect of Totems as reported in Tooltip description, observable with / without the Earthfury (3) bonus (vid. https://wotlkdb.com/?itemset=207; also https://wotlkdb.com/?spell=21895#modifies reporting only effect over Totem of Wrath). 

This bug is easily subject to reproduction. The issue would involve mostly verifying the DB and confirm if there is an error in the Tooltip information, if there is an error with the (3) piece bonus, or both.

Evidence provided below:
1) Image for reference of bonused / unbonused Totem ranges as described in Tooltip: https://imgur.com/a/AbkNDQc
Note that distance values referred are listed below, namely for (E)arth, (F)ire, (W)ater, (A)ir totems.

a) for unbonused gear: (E)30-(F)40-(W)30-(A)30
b) for bonused gear: (E)40-(F)50-(W)50-(A)40

So apparently, Earthfury (3) bonus is basically adding +10yds range to the bonus effect of totems.

However, this behavior does not reflect exactly what we can observe in game.

2) In the second screenshot, I have started a duel with another character that is located at some 41yd. distance (right in the limit of my Flame Shock spell, 40yd range): https://imgur.com/a/FKYJqzt 
Four totems are active, while wearing Earthfury (3) bonus gear (The Tooltip in the lower, right corner confirms that Stonesking AoE is 40yd., so we should expect this totem's effect to reach right before reaching our target)

3) Walking closer to my target, we can confim that, right before reaching 40yd. distance from the totems, the effect of all 4 of them is still active: https://imgur.com/a/lZ8S09O

However, on exceeding this 40yd. distance from the totem's location, only (E)Stoneskin and (F) Totem of Wrath are still active. 
This observation does not match the distances referred by tooltip, where the range of Stoneskin should not exceed 40yd. Besides, Water Totem (Mana Spring Totem) should also be reaching, as its quoted to have 50yd. bonused AoE.

4) Same mismatch can be observed when testing the "unbonused" totem AoE: https://imgur.com/a/8dBpA6U

In this case, we can observe that the Totems AoE expires after exceeding 30yd. distance. The values reported by Tooltip might be fine this time for Totem of Wrath (supposed to have 40yd. unbonused AoE) but stoneskin is still working (where it is reported to reach only within 30yd.), so in this case the totem effect should not apply.

I don't know if there was some kind of "standardization" for Totems AoE, but in any event is pretty confusing and looks like a bug that maybe you can investigate as affecting both PvE / PvP content in all ranges for this class.

#### Triager: ####
Ok, I've tested everything in-game and got these results:
Tooltip Range is the range, in yards, that is displayed on the totem's tooltips without and with the set bonus.
Effect Range is the actual range, in yards, of the totem's effects and buffs. Again, 'unbuffed' means without the set bonus and 'buffed' means with the set bonus.

| Totem  | Tooltip Range (unbuffed/buffed) | Effect Range (unbuffed/buffed)  |
| ------------- | ------------- | ------------- |
| Wrath  | 40/50  | 40/50  |
| Flametongue  | 30/30  | 30/30  |
| Frost Resistance  | 30/40  | 30/40  |
| Stoneskin  | 30/40  | 30/40  |
| Strength of Earth  | 30/40  | 30/40  |
| Tremor  | 30/40  | 30/35?  |
| Windfury  | 30/30  | 30/30  |
| Wrath of Air  | 30/40  | 30/40  |
| Nature Resistance  | 30/40  | 30/40  |
| Healing Stream  | 30/50  | 30/30  |
| Mana Spring  | 30/50  | 30/40  |
| Cleansing  | 30/40  | 30/30  |
| Mana Tide  | 30/40  | 30/30  |
| Fire Resistance  | 30/40  | 30/40  |

So we have inconsistencies with displayed range with Mana Tide, Cleansing, Healing Stream and Tremor
And the bonus is not being applied at all to Windfury and Flametongue tooltips or effects

### Expected Blizzlike Behaviour

Tooltips references should match observable values.
All beneficial Totems should have their ranges increased by 10y

### Source

[From Wowpedia](https://wowpedia.fandom.com/wiki/The_Earthfury):
1.7.0 Patch Notes:
>The Earthfury set bonus that increases the range of totems now works with the Mana Tide Totem.

2.1.0 Patch Notes:
>The set bonus that increases totem radius now works on  Wrath of Air Totem.

Interestingly, the set bonus description is blizz-like:
>Does anyone know if the 3 set bonus stacks with the resto talent? (3.0.1)
>
>>Actually if you click on the spell link in wowhead it says "Apply Aura: Add Flat Modifier (6) Value: 10". So I'm assuming this would increase it to 40y, especially since it was commented that this does work as I mention for the pally T2 bonus and auras. (3.3.2)
>>([source](https://www.wowhead.com/item-set=207/the-earthfury#comments:id=361617))

>Since totems now are ALREADY at 30 yd. range, this increases the range to 40 yds. ([source](https://web.archive.org/web/20121104045851/http://www.wowhead.com:80/spell=21895#comments:id=1048196))

### Steps to reproduce the problem

1. Plant totems with / without Earthfury bonused (3) set
2. Calculate distance of AoE of different totems
3. Compare these distances with the values reported by Tooltips.

### Extra Notes

[Increased Totem Radius](https://wowgaming.altervista.org/aowow/?spell=21895) (ID: 21895)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Tooltip are clientside and cannot be changed in serverside code.
The bonus works itself.
Not all totems listed by you are included , e.g. Stoneclaw - it's not a "affect friendly targets" totem.
https://classic.wowhead.com/spell=21895/increased-totem-radius Here you can see the list of affected totems.
