### ISSUE TITLE
[Mage/mmaps] Blink's destination is slightly above its expected destination

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#11721]
### Current Behaviour

On a very flat surface on the ground, I use [Blink](wotlkdb.com/?spell=1953) and I end up in the air for a fraction of a second.

https://user-images.githubusercontent.com/22718174/167959364-e3d9186e-269c-4e23-b831-5b223264b95a.mp4

While being underwater, after a few [Blink](wotlkdb.com/?spell=1953)s, I end up at the surface of the water.

https://user-images.githubusercontent.com/22718174/167959507-a91b1895-b1ad-49ea-9fa9-16ed2075731f.mp4

### Expected Blizzlike Behaviour

After blinking, I should have my hooves on the ground (or at the same level in the water).

### Source

Back in 2008, [Blink](wotlkdb.com/?spell=1953) places the character on the ground. https://www.youtube.com/watch?v=nlrEsEKCU3s

In 2011, you also have multiple examples of the player having his feet on the ground. https://www.youtube.com/watch?v=_ddFox7jwn4&t=145s

I highly doubt it has been changed for 2010 and got reverted for Cataclysm.

### Steps to reproduce the problem

`.learn 1953`
Use [Blink](wotlkdb.com/?spell=1953)

### Extra Notes

You cannot mount up when falling from the [Blink](wotlkdb.com/?spell=1953).
Until your hooves are on the ground, you cannot run when falling from the [Blink](wotlkdb.com/?spell=1953). Instead, you have a slow movement until you land.

I think https://github.com/azerothcore/azerothcore-wotlk/pull/11663 might have broken it, but I feel [Blink](wotlkdb.com/?spell=1953) is in a better shape than it used to be.

### AC rev. hash/commit

AzerothCore rev. 1ad79e19011d 2022-05-11 11:41:00 +0000 (master branch)

Also happens on ChromieCraft: AzerothCore rev. c7f74e563758 2022-05-11 06:35:25 +0000 (master branch)

### Operating system

Windows 10 x64

### Custom changes or Modules

Only have mod-eluna but no scripts.

**Comment by acidmanifesto** [comment]
This would be in regards to the recent blink pr that was merge. It was the original setup by tc that was replaced with the newer version that relied on maps and vmaps, which our blink originally was tc's current. So its a bit of swap around in this case.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/170241476-5bdadc33-8626-4f36-bcf6-f3c6d9349eef.png)
Delete it

**Comment by acidmanifesto** [comment]
> ![image](https://user-images.githubusercontent.com/18535853/170241476-5bdadc33-8626-4f36-bcf6-f3c6d9349eef.png)
> Delete it

That was done to prevent undermeshing and falling thru terrain, or so i am informed when it use to be the tc version of blink.
