### ISSUE TITLE
azerothcore mistake to abandon the profession

### ISSUE THREAD

**Issue by SHARQIPAGIDURDONASI** [azerothcore/azerothcore-wotlk#11724]
### Current Behaviour

![WoWScrnShot_051222_182153](https://user-images.githubusercontent.com/50262686/168084935-c678ba72-9479-401d-aedd-5084fcfbef59.jpg)
![WoWScrnShot_051222_182156](https://user-images.githubusercontent.com/50262686/168084945-0a57a18b-bca9-409f-86cb-b4ce231b133a.jpg)
![WoWScrnShot_051222_182206](https://user-images.githubusercontent.com/50262686/168084947-d609ec6f-60a4-448f-bdf7-f3f9c048fb63.jpg)
![WoWScrnShot_051222_182210](https://user-images.githubusercontent.com/50262686/168084950-035202dd-8825-449b-a8f5-520c080f3e41.jpg)
![WoWScrnShot_051222_182217](https://user-images.githubusercontent.com/50262686/168084951-8d547a72-cbb2-495f-9f17-ea190ad0ec58.jpg)
![WoWScrnShot_051222_182222](https://user-images.githubusercontent.com/50262686/168084955-c2d68529-cb64-4229-960c-44e66a93030e.jpg)
![WoWScrnShot_051222_182228](https://user-images.githubusercontent.com/50262686/168084957-c49a4185-cebe-4ab5-a53b-49764ba4bf33.jpg)
![WoWScrnShot_051222_182235](https://user-images.githubusercontent.com/50262686/168084963-fc592f88-8dae-4df5-926b-833f3674cc30.jpg)
![WoWScrnShot_051222_182239](https://user-images.githubusercontent.com/50262686/168084965-bee6713b-ac6a-4e34-bcab-89d4902fff37.jpg)
![WoWScrnShot_051222_182241](https://user-images.githubusercontent.com/50262686/168084968-82fdad1c-96a6-4a2f-9759-05ba31a2762a.jpg)
![WoWScrnShot_051222_182244](https://user-images.githubusercontent.com/50262686/168084973-b7fb1200-c983-4ed4-8f19-ec64d8010c02.jpg)

### Expected Blizzlike Behaviour

how to get rid of the problem?

### Source

how to get rid of the problem?

### Steps to reproduce the problem

how to get rid of the problem?

### Extra Notes

how to get rid of the problem?

### AC rev. hash/commit

how to get rid of the problem?

### Operating system

how to get rid of the problem?

### Custom changes or Modules

how to get rid of the problem?

**Comment by SHARQIPAGIDURDONASI** [comment]
I have been following this problem since 2019 year but it has not been corrected yet

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/2330#issuecomment-602671464

**Comment by SHARQIPAGIDURDONASI** [comment]
![image](https://user-images.githubusercontent.com/50262686/168119799-65edb9f8-a138-4d86-b374-ca870c87c93b.png)

**Comment by IntelligentQuantum** [comment]
Change SkillId to SkillLine

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/mod-npc-free-professions/blob/master/src/ProfessionNPC.cpp#L169

**Comment by SHARQIPAGIDURDONASI** [comment]
[cs_learn.txt](https://github.com/azerothcore/azerothcore-wotlk/files/8682232/cs_learn.txt)
