### ISSUE TITLE
World of Warcraft 3.3.5a frames stuttering

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#11738]
### Current Behaviour

it's not a server error.
After updating the computer, clean installation windows\drivers etc. I noticed with disappointment frames stuttering. i installed an older Classic version, for check, and found there even more frequent stuttering (https://www.youtube.com/watch?v=wgmNtlj_qMs).
On 3.3.5a it's not that noticeable, but it's there.
Please don't write noobs questions about vsync, scan windows and etc stuped proposals. I am a IT specialist. And I don't have any problems in the other 30 games that I have tested. I tried everything, even use d3d9 wrappers.
It makes the game uncomfortable for me.
New i5 12600 32GB 1060(6GB) M2 SSD 1TB. Windows 10 Pro 21H2 19044.1586.

### Expected Blizzlike Behaviour

smoothly

### Steps to reproduce the problem

updating the computer

### AC rev. hash/commit

5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

**Comment by Mitradis** [comment]
in google i see many questions "World of Warcraft classic stuttering". I read and try everything on the first 10 pages. I noticed that there are a lot of new messages from people with new hardware.

**Comment by Nyeriah** [comment]
Hey,

I appreciate your willingness to take part in our community and report issues, however, the GitHub is not a discussion board and the issue tracker serves the purpose of reporting bugs found in the emulator only, so I will be closing this.

For questions regarding the client, you could try joining our discord and asking your question at #support-general. I'm sure you will eventually find people with similar problems.

Additionally, users have reported suttering and client lag when they had the hardware cursor option on. Have you tried disabling it? It's usually the first thing to try when facing this problem.

Best regards.
