### ISSUE TITLE
[ZG] Bloodlord Mandokir - Various issues with melee physical spells

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11747]
### Current Behaviour

Overpower is not being cast.
~~Mortal Strike is only being used when the main target is below 50% health~~ Fixed by #11854

### Expected Blizzlike Behaviour

Overpower is only used if the main target dodges. It seems to have an internal cooldown of about 6-8s
Mortal Strike can be used whenever within a timer, and the target does not need to be below 50% HP.
Cleave is cast when a certain number of people are near or in front of Mandokir. May need more research to determine conditions for the cast.

### Source

https://youtu.be/XNm7HWagRKs?t=47
shows MS being cast while player has >50% HP and OP being cast only after a dodge, with a short cooldown.

### Steps to reproduce the problem

1. `.go xyz -12212 -1959 133 309`
2. Kill the Vilebranch Speaker and start the encounter.

### Extra Notes

Bloodlord Mandokir (ID: 11382)
Mortal Strike (ID: 16856)
Overpower (ID: 24407)

~~There are some written sources that indicate that a Cleave spell is cast but I've not seen it in video and it is missing in most, if not all, WoW Classic guides.~~ Silker found video evidence from Vanilla and the ID from another core.

My observed timers are:
Mortal Strike 14-28s
Overpower 6-8s Cooldown

In written guides I've seen the existence of a 'Execute' Spell existing, but I've found no good footage of it yet
>Ability  [Execute](https://www.wowhead.com/?spell=7160) — Used when Mandokir's current target falls below 20% health. Deals approximately 5000 physical damage. ([source](https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic)))

Execute (ID: 7160)
I contest the existence of Execute until I find a good source, since most attacks when the target is below 20% HP would kill them anyway.
https://youtu.be/BCfUnfSpDmM?t=210 shows normal attack damage for the killing blow
https://youtu.be/PdvZirl8vls?t=85 so does this one.

The only semi-source I found was a comment in a WoW Classic video that was the RL and MT mentioning that Mandokir "hit me for 5k once."

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

**Comment by Si1ker** [comment]
"There are some written sources that indicate that a Cleave spell is cast but I've not seen it in video and it is missing in most, if not all, WoW Classic guides."
The [cleave](https://github.com/Si1ker/azerothcore-wotlk/blob/ohgan-fixes/src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp#L354) spell you say, is from the Vilebranch NPC which is required to call Mandokir. People in the comments just got confused about it.

**Comment by Si1ker** [comment]
@Gultask seems the cleave spell is correct, look at the video, multiple players are affected by a "cleave spell effect visual"

Okk at 2:12 https://youtu.be/PdvZirl8vls?t=132

![image](https://user-images.githubusercontent.com/61223313/170142511-39b98418-72a3-4e92-9e16-5e33723d9c00.png)

**Comment by Gultask** [comment]
Then it probably has a condition to only cast it if it has a certain number of players around him because he does not cleave in WotLK videos. Thanks for noticing it! I'll see if I can find more.

**Comment by Si1ker** [comment]
@Gultask even wowhead **wow classic guide** on Broodlord confirms it lol !

![image](https://user-images.githubusercontent.com/61223313/170177156-c4a08942-bc9c-4974-961a-30816d515a97.png)
Source: https://classic.wowhead.com/guides/bloodlord-mandokir-zul-gurub-strategy

**Comment by Gultask** [comment]
Yeah I had seen that as well, but my source priority is WotLK footage > Vanilla footage > Classic footage. Classic sources can sometimes differ from retail in varying degrees (Renataki, for example, is broken in Classic). So after a couple of hours watching and re-watching WotLK footage of Mandokir, I've never seen a Cleave. Although **it does** make sense that it's conditional, with at least x number of people needed in a frontal cone to trigger the spell, and I hadn't thought of that.

At least Execute had an ID associated with it in some guides, but we now have to find which is the ID for Cleave 😬
