### ISSUE TITLE
Warrior's block casuse insta death

### ISSUE THREAD

**Issue by SakuraH96** [azerothcore/azerothcore-wotlk#11743]
### Current Behaviour

Using Shield block + Shield Wall is causing Warrior to take 2b damage from players attacking them.

### Expected Blizzlike Behaviour

Not cause player to die instantly

### Steps to reproduce the problem

Turn on Shield Block
Turn on Shield Wall
Get one player to attack you

### AC rev. hash/commit

Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.74.0
Using MySQL version: 80029
Using CMake version: 3.22.3
Compiled on: Windows 
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2199390740 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_03_09_01
Using Character DB Revision: 2022_03_01_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List enable modules:
- mod-eluna-lua-engine
- mod-transmog

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
My guess is an overflow during block calculations

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/11492

**Comment by UltraNix** [comment]
@SakuraH96 Cannot reproduce it.
