### ISSUE TITLE
Server crashes randomly

### ISSUE THREAD

**Issue by Valoriaz** [azerothcore/azerothcore-wotlk#11765]
### Current Behaviour

Server crash randomly

https://gist.github.com/Valoriaz/cd0df83213caf064d097e134cf8c965c

### Expected Blizzlike Behaviour

-

### Source

-

### Steps to reproduce the problem

-

### Extra Notes

i noticed if someone fly through Zul Drak .. near Gundrak the Server crashes too

### AC rev. hash/commit

AzerothCore rev.0c0a2eac3b0e 2022-05-12 10:43:04 -400 (master branch) (Win64, Debug, Static)

### Operating system

Windows Server 2019

### Custom changes or Modules

mod-ah-bot
mod-autobalance
mod-eluna
mod-learn-spells
mod-reagent-bank
mod-skip-dk-starting-area
mod-solo-lfg
mod-solocraft
mod-transmog

**Comment by UltraNix** [comment]
Looks like a loop, but not a very good crashlog.
@Valoriaz You server is built on RelWithDebInfo mode?
What is your gdb config?

**Comment by Valoriaz** [comment]
My Server is built as Debug
i cant use gdb..im using windows

**Comment by UltraNix** [comment]
Could you build your server in RelWithDebInfo? It's better in terms of performance, but yout still have nice crashlogs ;)

**Comment by Valoriaz** [comment]
Sure

**Comment by UltraNix** [comment]
@Valoriaz Any new crashlog?

**Comment by Valoriaz** [comment]
All fine .. can be closed
