### ISSUE TITLE
Implement Quest Tracker

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1176]
This is also part of: https://github.com/azerothcore/azerothcore-wotlk/issues/1118

---

This is a feature I've previously implemented for TC: https://github.com/TrinityCore/TrinityCore/commit/e806fc8a02dbde324dd9654b0165a7cac5ae7086

It can be used with: https://github.com/FrancescoBorzi/TC-Quest-Tracker

It would be nice to have it in AzerothCore too.

**Comment by BarbzYHOOL** [comment]
Awesome

**Comment by FrancescoBorzi** [comment]
Original PR (that has more details): https://github.com/TrinityCore/TrinityCore/pull/13353
