### ISSUE TITLE
[ZG] Mandokir - Ohgan hack

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#11764]
### Current Behaviour

Actually the summon of Ohgan is hacked.

### Expected Blizzlike Behaviour

It's seems to be a spell. Look if we can fix this properly.

### Steps to reproduce the problem

Look the code

### AC rev. hash/commit

5474b00

### Operating system

Windows 11

**Comment by grimgravy** [comment]
the hack is justified
