### ISSUE TITLE
[Black Temple] Illidan Start of Phase 5

### ISSUE THREAD

**Issue by hahalmtdhl** [azerothcore/azerothcore-wotlk#11769]
### Current Behaviour

When Illidan releases: Spell_ SHADOW_ Prison, Illidan will be released from combat and his health will be restored to 100%

### Expected Blizzlike Behaviour

We should not get out of battle We should continue to fight until we finally enter the plot

### Steps to reproduce the problem

1. Kill all bosses of the dark temple (excluding Illidan)

2. Talk with Akama and wait for Akama to open the door and enter the platform

3. Talk with Akama, enter the plot, and wait to activate Illidan battle

4. After killing the fire element, you will continue to fight Illidan. When Illidan's HP is low, it will release spell_ SHADOW_ PRISON. At this time, the player and Illidan are all separated from the battle, the battle is reset, and Akama returns to the original position

### AC rev. hash/commit

0c0a2eac3b0e3eb850a63517d51829a2191e83a1

### Operating system

Win10

### Custom changes or Modules

Eluna

**Comment by UltraNix** [comment]
#9038

**Comment by hahalmtdhl** [comment]
i saw moved this from To do to Done .

Which submission fixed this problem?

**Comment by Maelthyrr** [comment]
> i saw moved this from To do to Done .
> 
> Which submission fixed this problem?

Look issue share by UN.

**Comment by hahalmtdhl** [comment]
Are there any specific links? Thank you.

**Comment by Maelthyrr** [comment]
> Are there any specific links? Thank you.

Issue is always open and is not fixed for thé moment. Your issue is just a duplicate issue. This is the reason why it was closed.

**Comment by Maelthyrr** [comment]
> > Are there any specific links? Thank you.
> 
> Issue is always open and is not fixed for the moment. Your issue is just a duplicate issue. This is the reason why it was closed.

**Comment by hahalmtdhl** [comment]
Thank you for your clarification
