### ISSUE TITLE
Zul'Farrak stairs, Sgt. Bly has no chat option until Weeglu Blastfuse is talked to

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#11773]
### Current Behaviour

Checked on CC, and CC's PTR. Immediately after the stairs event. Weegli Blastfuse will have the chat option "Can you blow up that door now", and Sergeant Bly will have the chat option along the lines of "I'm tired of helping you", which turns the NPCs hostile. However, the option to talk to Bly is not there until you talk to the goblin and have him blow the door. While this makes this part dummy proof, it's not blizzlike.

### Expected Blizzlike Behaviour

Should be able to talk to Bly at any time after the stairs event triggering the battle with the NPCs (goblin included) 

### Source

https://youtu.be/N1a5hc4Uh-M?t=528 From wow classic

https://www.wowhead.com/npc=7607/weegli-blastfuse#comments:id=20478

https://www.wowhead.com/npc=7607/weegli-blastfuse#comments:id=581407:reply=129073

### Steps to reproduce the problem

.tele zulfarrak
Do the stairs event
Try and talk to Bly before talking to Weegli Blastfuse

### Extra Notes

All guides say "Talk to the goblin first" and "Don't kill the goblin" They should not have to say that if talking to the goblin was the only option, and he is never attackable.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

windows 10

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by avarishd** [comment]
After looking for some source between 3.3.0 (LFG) and pre 4.0.1 (Maybe it was changed in order to not brick LFG runs, allegedly)
Here is what I mange to find (sadly, nothing in that period of time):
Pre 3.3.0 https://youtu.be/Bpza0P9t7CE?t=256 - you can see him running in the background as a neutral 
Pre 3.3.0 https://youtu.be/ZmnmUIoe9f0?t=253 - same, running as a neutral
TBC - https://youtu.be/StOHpluqlC4?t=510 - neutral 
TBC - https://youtu.be/W-PyIv_N764?t=109 - (scuffed) They speak with him before fighting and he "escapes" towards the Hydra's room (eventually dying)

**Comment by Stump876** [comment]
Understandable, though I personally do remember getting locked out in retail in vanilla from impatient people, and the aruguments that followed. But by the time Wrath came around it was common knowledge to let him blow the door first, so I can't say for sure how his mechanics worked at that time if you didn't.
