### ISSUE TITLE
Overlapping Barrel of Milk/Food Crate in Stormwind

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#11776]
### Current Behaviour

![image](https://user-images.githubusercontent.com/22718174/168496002-bcf4ef20-2e23-462b-9505-e6e53d48e624.png)

### Expected Blizzlike Behaviour

They should not be overlapping.

### Source

Uhh, none. :)

### Steps to reproduce the problem

`.go gameobject 31401` (Food Crate)
or
`.go gameobject 33607` (Barrel of Milk)

### Extra Notes

Similair issue https://github.com/azerothcore/azerothcore-wotlk/issues/6646 (fix: https://github.com/azerothcore/azerothcore-wotlk/pull/7705)

### AC rev. hash/commit

AzerothCore rev. 1ad79e19011d 2022-05-11 11:41:00 +0000 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-eluna (no script installed)

**Comment by Gultask** [comment]
Should be pooled together. Probably in pool_pools as well if there's a limit to how many can spawn in the zone 😬

Here's some examples how to use pool_gameobject and pool_pools: https://github.com/azerothcore/azerothcore-wotlk/pull/13597
