### ISSUE TITLE
Midsummer Some Summer/Festival scorchlings missing

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#11789]
### Current Behaviour

Many locations are missing the scorchling that finishes the quest  `Incense for the Summer/Fesival Scorchling` Festival Scorchling is for horde. Summer Scorchling is for alliance. 

### Expected Blizzlike Behaviour

Scorchlings should be present at the fires. 

### Source

[Alliance missing scorchlings](https://tbc.wowhead.com/npc=26401/summer-scorchling)
Azuremyst, Telaar (Nagrand), Area 52 (Netherstorm), Wildhammer Strongold (Shadowmoon Valley), Allerian Stronghold (Terokkar), Telredor (Zangermarsh)

[Horde missing scorchlings](https://tbc.wowhead.com/npc=26520/festival-scorchling)
Eversong, Razor Hill (Durotar), Sun Rock Retreat (Stonetalon), Area 52 (Netherstorm), Shadowmoon Village (Shadowmoon Valley),

### Steps to reproduce the problem

After porting to each location I suggest to macro a `/tar summer` to check alliance fires and `/tar festival` for horde
Alliance:
.go c 248584 Azuremyst 
.go c 248593 Area 52 (Netherstorm)
.go c 245660 Telaar (Nagrand)
.go c 245662 Wildhammer Strongold (Shadowmoon Valley)
.go c 248586 Allerian Stronghold (Terokkar)
.go c 248589 Telredor (Zangermarsh)

Horde:
.go c 245687 Eversong
.go c 245689 Tranquillien (Ghostlands)
.go c 254685 Razor Hill (Durotar)
.go c 254696 Sun Rock Retreat (Stonetalon)
.go c 94779 Sepulcher (Silverpine) This scorchling is there, but under the fire and hard to see.
.go c 248594 Area 52 (Netherstorm)
.go c 248587 Shadowmoon Village (Shadowmoon Valley)

### Extra Notes

https://github.com/azerothcore/azerothcore-wotlk/issues/6500

### AC rev. hash/commit

78f66ce05e8c

### Operating system

windows 10

**Comment by heyitsbench** [comment]
I have a (hopefully) comprehensive sniff of the various locations with bonfires, so if/when parsing is available, the creatures/gobjects can be placed appropriately.
