### ISSUE TITLE
Cannot Accept Quests

### ISSUE THREAD

**Issue by whipowill** [azerothcore/azerothcore-wotlk#11788]
### Current Behaviour

When the ``worldserver.conf`` has the ``Quests.IgnoreAutoAccept`` turned ON, some quests cannot be accepted at all.  For me this was the started quests in Mulgore:

- Attack on Camp Narache
- Rites of the Earthmother

I was not able to accept either of these quests.  When I went back into the config and turned OFF ``Quests.IgnoreAutoAccept``, rebooted the server, and relogged I was able to accept them.

### Expected Blizzlike Behaviour

Despite having autoaccept turned off, I should still be able to accept them clicking "Accept" on the quest dialogue.

### Steps to reproduce the problem

See above.

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. 78f66ce05e8c 2022-05-17 00:38:34 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80029
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-109-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2107913100 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autobalance

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/bcd9ad5066a86402aa5c917cd6d2ed227a33709e
