### ISSUE TITLE
Move hardcoded texts of zone_sholazar_basin (Still At It)to the Database

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11797]
### Current Behaviour

src/server/scripts/Northrend/zone_sholazar_basin.cpp

[
            AddGossipItemFor(player, GOSSIP_ICON_CHAT, "I'm ready to start the distillation, uh, Tipsy.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);](https://github.com/azerothcore/azerothcore-wotlk/blob/3255e1cdf7b2d2ff4b69dfcf4a5f5f256c0112a3/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L473)

![image](https://user-images.githubusercontent.com/18187177/168957606-78f8e58e-7b26-4f65-b9bd-60234895a790.png)

https://github.com/azerothcore/azerothcore-wotlk/blob/3255e1cdf7b2d2ff4b69dfcf4a5f5f256c0112a3/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L264

![image](https://user-images.githubusercontent.com/18187177/168957632-d6d45f46-514c-46ae-883e-df7a1cc04bb6.png)

https://github.com/azerothcore/azerothcore-wotlk/blob/3255e1cdf7b2d2ff4b69dfcf4a5f5f256c0112a3/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L831

![image](https://user-images.githubusercontent.com/18187177/168958251-280404d0-b535-4593-909f-842665317071.png)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. `.quest a 12644`
2. talk `"Tipsy" McManus`

### AC rev. hash/commit

822aff29e680d7ddce1064abf8a543999c914c98

### Operating system

Ubuntu20.04

**Comment by Maelthyrr** [comment]
Same issue here : https://github.com/azerothcore/azerothcore-wotlk/issues/4165
