### ISSUE TITLE
Refresh NPC repeatedly too

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11799]
### Current Behaviour

update to 7d3809330b5f7104b98a400edc87754e2f4f536b

`Krolmir, Hammer of Storms` (quest id 13010) ,It will cause repeated refresh of NPC(creature id 30331)

https://youtu.be/JUBYknvGY5E

### Expected Blizzlike Behaviour

Whether you have a mount or not, you will be forced to dismount and sit on the king's shoulder

### Steps to reproduce the problem

1. `.quest a 13010 `
2. `.go xyz 7345.899902 -2812.949951 798.488281 571`
3.  talk `King Jokkum`(creature id 30105)
4. a new  `King Jokkum` (creature id 30331) will be refreshed 
5. The king will take you away. When you come back from the quest, you can see two kings
6.The former king does not disappear

### AC rev. hash/commit

822aff29e680d7ddce1064abf8a543999c914c98 + PR #11742

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
@UltraNix please

**Comment by UltraNix** [comment]
Just tested on newest version - everything works okay.

**Comment by mpfans** [comment]
I know how to repeat this bug. When you are on a flying mount, a king will appear when you talk to the king, one at a time

**Comment by mpfans** [comment]
https://youtu.be/c8bYpgJQDd0
