### ISSUE TITLE
Command ".send items" does not work correctly [Required for web store]

### ISSUE THREAD

**Issue by SKingOWN** [azerothcore/azerothcore-wotlk#11806]
### Current Behaviour

The mail arrives, but without the items inside.

### Expected Blizzlike Behaviour

Items must arrive in the mail.

### Steps to reproduce the problem

1. Login with gm account.
2. Execute command .send items Playername "Mail subject" "Mail body" 16829
3. Execute command .mail to confirm that the mail arrives has not objects inside.

### AC rev. hash/commit

AzerothCore rev. c5368816fa67 2022-05-18 05:36:57 -0300 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80029
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-109-generic
Worldserver listening connections on port 8056
Realmlist (Realm Id: 1) configured in port 8056
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 291014951 bytes
vmaps directory located in ../data/vmaps. Total size: 658130721 bytes
mmaps directory located in ../data/mmaps. Total size: 2107913100 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-cfbg
- mod-duelreset
- mod-transmog

### Operating system

Ubuntu 20.04

**Comment by SKingOWN** [comment]
Problem found: now it is mandatory to specify the quantity even if it is 1.
Example: 
NOT WORK: .send items Playername "Mail subject" "Mail body" 16829
WORK: .send items Playername "Mail subject" "Mail body" 16829:1

**Comment by temperrr** [comment]
I would say it works like it should

**Comment by Kitzunu** [comment]
Works as it should imo, I dont see why we shouldnt specify 1
