### ISSUE TITLE
[Paladin] [Spell] Flash of Light not applying HoT on Sacred Shield target

### ISSUE THREAD

**Issue by emilohlund-git** [azerothcore/azerothcore-wotlk#11804]
### Current Behaviour

There's nothing happening

### Expected Blizzlike Behaviour

If 
1. The target has Sacred Shield applied
2. You (As a Paladin) have specced in to Infusion of Light
3. You cast Flash of Light on the target
the target should acquire a HoT for 50% (Rank 1) or 100% (Rank 2) of the Flash of Light healing value. (Spell ID: 66922)

### Source

https://wotlk.evowow.com/?spell=53576 (Infusion of Light)
https://wotlk.evowow.com/?spell=66922 (Flash of Light, heal over time Spell)

### Steps to reproduce the problem

1. Give yourself the Infusion of Light talent
2. Cast Sacred Shield on yourself
3. Cast Flash of Light on yourself

### Extra Notes

I saw an old issue on this, it is however deprecated since the code base has changed:
https://github.com/azerothcore/azerothcore-wotlk/issues?page=2&q=is%3Aissue+is%3Aopen

### AC rev. hash/commit

[#9061](https://github.com/azerothcore/azerothcore-wotlk/pull/9061)

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by emilohlund-git** [comment]
Added the commit, sorry!

**Comment by Meramaf** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/14d933eddc57ea121e1a01d6d2e0977a8f654253

**Comment by UltraNix** [comment]
Already fixed.
