### ISSUE TITLE
[Teldrassil/Shadowglen] NPC Tarindrella (ID: 1992) has wrong MovementType

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11801]
https://github.com/chromiecraft/chromiecraft/issues/3515

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

NPC Tarindrella in Night elves starting area (Shadowglen) is idle.

### Expected Blizzlike Behaviour

NPC Tarindrella in Night elves starting area (Shadowglen) should have random movement in a small radius.

### Source

https://youtu.be/NsyLRaUTUX0?t=1909
https://youtu.be/hvLRq2vxdEs?t=1006
https://youtu.be/760F0vAbK2w?t=769

### Steps to reproduce the problem

1. Create night elf character
2. Find Tarindrella NPC in Shadowglen
3. Check her behavior

### Extra Notes

https://classic.wowhead.com/npc=1992/tarindrella#starts

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c058791ed65ff55607eb1643b94ac69343c8834

### Operating system

Windows 11 21H2 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/169731033-ffa34d00-e384-4062-82fe-5a1c4e974d85.png)
The wander distance should be 7

This is sniffed data and if someone wants to use it go for it, I'm just moved.  Else I've bookmarked this and will check back later.

**Comment by Gultask** [comment]
Thank you, neifion! ❤️
