### ISSUE TITLE
Many things about Coilskar Cistern and Oronok's Farm

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#11816]
### Current Behaviour

1. [Earthmender Wilda](https://www.wowhead.com/npc=21027/earthmender-wilda) is already free. She should be in the cave.
You may find her with `.go c 86832`.
You may do her escort quest but, a lot of mobs are missing from the cave so a lot of roleplay is missing.
Earthmender Wilda doesn't attempt to help the player with the fights as well as the mobs in the cave doesn't try to stop her from escaping the cave, she just walks by, unharmed by the mobs in the way.

![image](https://user-images.githubusercontent.com/22718174/169628578-f4526998-bbd9-46f5-ab6d-75119e223cb9.png)

2. Killing [Keeper of the Cistern](https://www.wowhead.com/npc=20795/keeper-of-the-cistern) should free [Earthmender Wilda](https://www.wowhead.com/npc=21027/earthmender-wilda) but Keeper of the Cistern is at the surface, and also point 1.
You may find her with `.go c 86872` but she's at the surface.

![image](https://user-images.githubusercontent.com/22718174/169629183-57334417-60c4-427c-a1d9-a6c06892d2ce.png)

3. A lot of [Coilskar Assassin](https://www.wowhead.com/npc=21044/coilskar-assassin) and [Captured Water Spirit](https://www.wowhead.com/npc=21029/captured-water-spirit) are on the surface while they are supposed to be in the cave.

![image](https://user-images.githubusercontent.com/22718174/169629244-6cd82ec9-0d0a-4c8b-9294-75942ec70a9a.png)

4. A lot of [Domesticated Felboar](https://tbc.wowhead.com/npc=21195/domesticated-felboar) are missing inside Oronok's Farm. You may find how it should be in the source part of the report.

![WoWScrnShot_052022_231415](https://user-images.githubusercontent.com/22718174/169633191-916fc748-c33e-4136-9d00-e8f0ec39f3d3.jpg)

### Expected Blizzlike Behaviour

See Current Behaviour.

### Source

Points 1, 2 and 3: https://www.youtube.com/watch?v=i_CpElkm5q4

Point 3 and 4: https://www.youtube.com/watch?v=fF3Od5DaVTc

### Steps to reproduce the problem

Meh, too much.

### Extra Notes

Mom, can I have a Domesticated Felboar at Oronok's Farm?
We already have a Domesticated Felboar at Oronok's Farm!
![image](https://wow.zamimg.com/uploads/screenshots/normal/53955-domesticated-felboar.jpg)
(wowhead screenshot above)

Domesticated Felboar at Oronok's Farm:
![image](https://user-images.githubusercontent.com/22718174/169632620-42f37df6-56d2-4666-84c5-c390ad39341f.png)

### AC rev. hash/commit

AzerothCore rev. 324112ff4fcb 2022-05-19 19:13:06 -0300 (master branch)

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-eluna (no scripts)

**Comment by Gultask** [comment]
Assigning it to myself unless someone else wants to rebuild the area
