### ISSUE TITLE
[NPC] `Domesticated Felboar` grants xp, has loots, and are skinnable

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#11817]
### Current Behaviour

You may gain xp from killing a [Domesticated Felboar](https://www.wowhead.com/npc=21195/domesticated-felboar).
![image](https://user-images.githubusercontent.com/22718174/169633991-b2f21f12-285a-4fd9-9f30-e91f0315c8f0.png)

You may loot them for... loot.
You may also skin them.
![image](https://user-images.githubusercontent.com/22718174/169633957-650e0dff-70cc-4717-9b8f-80cfdff66d4e.png)

### Expected Blizzlike Behaviour

No speed leveling.
No loot.
No leather farming.

### Source

Wowhead comments: https://www.wowhead.com/npc=21195/domesticated-felboar
Wowpedia changelogs: https://wowpedia.fandom.com/wiki/Domesticated_Felboar

### Steps to reproduce the problem

`.character level 67`
`.go c 77837`
`.damage 9999`
You've got XP!
Loot everything if it has loot.
Notice it has the skinning option (or you're missing the skinning level requirement).

### AC rev. hash/commit

AzerothCore rev. 324112ff4fcb 2022-05-19 19:13:06 -0300 (master branch)

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-eluna (no scripts)

**Comment by acidmanifesto** [comment]
https://www.wowhead.com/wotlk/npc=21195/domesticated-felboar#skinning
skinning loot was introduced in 3.0.1

**Comment by benjymansy123** [comment]
> skinning loot was introduced in 3.0.1

But was removed in [3.2?](https://www.wowhead.com/npc=21195/domesticated-felboar#comments:id=803455)

**Comment by acidmanifesto** [comment]
> > skinning loot was introduced in 3.0.1
> 
> But was removed in [3.2?](https://www.wowhead.com/npc=21195/domesticated-felboar#comments:id=803455)

correct.
after research this issue is consider valid, this was one of those unique cases where the sniffs were from a earlier wraith version of it being introduced where it was removed in later versions of wraith.
![image](https://user-images.githubusercontent.com/16887899/174438026-4147fea7-a14a-41f9-98a3-b9221977af3c.png)

**Comment by benjymansy123** [comment]
Ah, I see.
