### ISSUE TITLE
Missing 'Rotlimb Cannibals'

### ISSUE THREAD

**Issue by virgo77** [azerothcore/azerothcore-wotlk#11853]
### Current Behaviour

In the Eversong Woods, inside The Dead Scar, there's normally a group of 4 Rotlimb Cannibals that are running to Ranger Jaela and her group of Eversong Rangers. But it seems that in this core, this group is not 'poping'

### Expected Blizzlike Behaviour

The working mini-event, every 5 minutes (maybe more)

### Source

https://tbc.wowhead.com/npc=15655/rotlimb-cannibal

In this link, it says that this NPC was added in TBC Classic 2.5.x (so, like in the original TBC 2.4.x)

### Steps to reproduce the problem

none

### AC rev. hash/commit

AzerothCore rev. 9e35f8418769+ 2022-05-17 18:47:40 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 11 (I've left WinServer2k22 ^^)

### Custom changes or Modules

AH Bot
Transmog
DK Skip

**Comment by SoglaHash** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21327 mentions a total  of 3 attacks

- [x] Fairbreeze Village https://github.com/azerothcore/azerothcore-wotlk/pull/12934
.go xyz 8678 -6790 94

- [x] The Dead Scar https://github.com/azerothcore/azerothcore-wotlk/pull/12724
.go xyz 9370 -6966 19

- [ ] Tranquillien
.go xyz 7619 -6795 78

I wasn't able to find a reference video for the Tranquillien attack or changes in other projects
