### ISSUE TITLE
Visibility in arena

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#11851]
### Current Behaviour

Visibility in the arena stopped working correctly. If you move away from the target, then it will disappear from the map and you will no longer see it.

```
#    Visibility.Distance.Continents
#    Visibility.Distance.Instances
#    Visibility.Distance.BGArenas
#        Description: Visibility distance to see other players or gameobjects.
#                     Visibility on continents on retail ~90 yards. In BG/Arenas ~180.
#                     For instances default ~120.
#                     Max limited by active player zone: ~ 333
#                     Min limit is max aggro radius (45) * Rate.Creature.Aggro
#        Default:     90  - (Visibility.Distance.Continents)
#                     120 - (Visibility.Distance.Instances)
#                     180 - (Visibility.Distance.BGArenas)

Visibility.Distance.Continents = 180
Visibility.Distance.Instances = 120
Visibility.Distance.BGArenas = 180
```

Video: https://streamable.com/wfgjwn

### Expected Blizzlike Behaviour

The target must not be lost.

### Steps to reproduce the problem

1. Go in arena and test.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/305a2689e965346dc7c12a87650fab08696b0a10

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
what is the range you are at? Can you do .dist and target the opponent at the furthest range before it derenders?

**Comment by r0m1ntik** [comment]
@Kitzunu it was a one-time bug, I couldn't repeat it again.
