### ISSUE TITLE
Movement (moving in fear across the bridge)

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#11850]
### Current Behaviour

When using fear(any) on the bridge, we block movement and in the arena, fear brings to the very edge, which leads to the player falling to the bottom.

videos: https://streamable.com/pm2nnl
            https://streamable.com/dad2i0

### Expected Blizzlike Behaviour

should generate a valid place to move, and the arena should not go all the way to the edge.

### Steps to reproduce the problem

1. Climb any bridge
2. Use fear

### AC rev. hash/commit

[#305a26](https://github.com/azerothcore/azerothcore-wotlk/commit/305a2689e965346dc7c12a87650fab08696b0a10)

### Operating system

Ubuntu 20.04

**Comment by r0m1ntik** [comment]
@UltraNix https://github.com/azerothcore/azerothcore-wotlk/pull/11586/files

**Comment by UltraNix** [comment]
@r0m1ntik Related to mmaps.
