### ISSUE TITLE
[achievement] `Conqueror of Ulduar` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11860]
### Current Behaviour

Now you can do this on different raid CDs

### Expected Blizzlike Behaviour

Achievement requires that in a raid CD, no player can die in all boss wars

### Source

https://www.wowhead.com/achievement=2904/conqueror-of-ulduar#8fccbf1

### Steps to reproduce the problem

1. no gm mode kill a boss
2. .instance unbind all
3. no gm mode kill other boss
4. You will find that achievements will light up two bosses

### Extra Notes
It also needs a raid CD    of  `The immortal`  achievement and work

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/305a2689e965346dc7c12a87650fab08696b0a10

### Operating system

Ubuntu20.04

**Comment by avarishd** [comment]
Wrong, https://www.wowhead.com/achievement=2904/conqueror-of-ulduar#comments:id=664994 your progress goes into the achievement (for each boss).

For The Immortal/Undying there is no progress, you have to do it in 1 ID.

**Comment by mpfans** [comment]
> Wrong, https://www.wowhead.com/achievement=2904/conqueror-of-ulduar#comments:id=664994 your progress goes into the achievement (for each boss, no matter if it's the same ID or not).
> 
> For The Immortal/Undying there is no progress, you have to do it in 1 ID.

OK, you're right But the player has achieved success after 2 months

**Comment by mpfans** [comment]
Light up 2 boss achievements in the first week and 3 boss achievements in the second week

**Comment by avarishd** [comment]
That's how it works. There is no time restrain on that achievement.
["All it says now is that you must perform perfect, deathless, one-shot kills of each boss in Ulduar at some point on the raid's lifetime. Nothing more."](https://www.wowhead.com/achievement=2904/conqueror-of-ulduar#comments:id=664994)

**Comment by avarishd** [comment]
I tried on XT-002, with 2 characters. 
1) Wiped 
2) .tele dala
3) pull again, kill normaly
4) NO achievement progress 

It's properly saved in DB as well
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp#L1037-L1056

**Comment by mpfans** [comment]
ok.... close this issue.. tyvm @avarishd
