### ISSUE TITLE
DB restructuring - world - game_event

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1187]
This is part of: https://github.com/azerothcore/azerothcore-wotlk/issues/1118

**General note**: not all structure differences can or should be imported. Every change must be first verified. If a structure change is not suitable, we just close the issue.

---

About the field `announce`, if this is a missing feature we could just create it and mark it as UNUSED in our documentation until we implement it. Investigation is needed here.

The other 2 fields can be adapted. This also helps with MySQL 5.7 support because of removing `DEFAULT '0000-00-00 00:00:00'`.

```diff
--- Dumping structure for table acore_world.game_event
+-- Dumping structure for table tc_world.game_event
 DROP TABLE IF EXISTS `game_event`;
 CREATE TABLE IF NOT EXISTS `game_event` (
   `eventEntry` tinyint(3) unsigned NOT NULL COMMENT 'Entry of the game event',
-  `start_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Absolute start date, the event will never start before',
-  `end_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Absolute end date, the event will never start afler',
+  `start_time` timestamp NULL DEFAULT NULL COMMENT 'Absolute start date, the event will never start before',
+  `end_time` timestamp NULL DEFAULT NULL COMMENT 'Absolute end date, the event will never start after',
   `occurence` bigint(20) unsigned NOT NULL DEFAULT '5184000' COMMENT 'Delay in minutes between occurences of the event',
   `length` bigint(20) unsigned NOT NULL DEFAULT '2592000' COMMENT 'Length in minutes of the event',
   `holiday` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'Client side holiday id',
   `holidayStage` tinyint(3) unsigned NOT NULL DEFAULT '0',
   `description` varchar(255) DEFAULT NULL COMMENT 'Description of the event displayed in console',
   `world_event` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '0 if normal event, 1 if world event',
+  `announce` tinyint(3) unsigned DEFAULT '2' COMMENT '0 dont announce, 1 announce, 2 value from config',
   PRIMARY KEY (`eventEntry`)
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by FrancescoBorzi** [comment]
see also: https://github.com/TrinityCore/TrinityCore/commit/425b181544a21d2246fdf0261ba76a37e2510883

thanks @Nefertumm for pointing it.

**Comment by BarbzYHOOL** [comment]
What do you mean with "This also helps with MySQL 5.7 support because of removing DEFAULT '0000-00-00 00:00:00'." ?

**Comment by dunjeon** [comment]
5.7 has default: STRICT_TRANS_TABLES and NO_ZERO_DATE
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL in short, mysql 5.7 and higher doesn't like values like `'0000-00-00 00:00:00'` (unless you change the default settings)

**Comment by BarbzYHOOL** [comment]
Ah ok but we got 0000 000 in tons of tables :'(

**Comment by BarbzYHOOL** [comment]
is there an issue opened about this?

**Comment by dunjeon** [comment]
@BarbzYHOOL  Don't worry about the number of 0000 000. One or many are easily corrected.  Truth is, I've been using 5.7 for AC since July 2017
