### ISSUE TITLE
Mobs should be tapped by aggro, not damage. 

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#11888]
### Current Behaviour

When you engage a mob with a non damaging spell it does not tap the mob.
Example: Corruption doesn't tap the mob, until it ticks.

### Expected Blizzlike Behaviour

To instantly tap the mob when aggroing with a spell/threat.

### Source

https://wowwiki-archive.fandom.com/wiki/Patch_3.0.8
https://wowpedia.fandom.com/wiki/Patch_3.0.8
Patch 3.0.8 (2009-01-20): All player spells which cause a creature to become aggressive to you will now also immediately cause the creature to be tapped.

### Steps to reproduce the problem

1. Do a non damaging spell on a mob
2. notice it doesn't tag it

### Extra Notes
Can perhaps be a worldconfig option (if confirmed)
_No response_

### AC rev. hash/commit

4f2f9d8

### Operating system

Windows 10, Docker

**Comment by Maelthyrr** [comment]
Should be fix with https://github.com/azerothcore/azerothcore-wotlk/issues/5985 . Just need time to publish the rewrite (but it is progressing well ;) )
