### ISSUE TITLE
Talisman of Ascendance procs from all spellcasts and auto attacks opposed to only Healing/Damage spellcasts

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11881]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour
The trinket applies +spell power buff on any spell cast as well as auto attacks and physical damage, instead of only on damage or healing spells.

### Expected Blizzlike Behaviour

![Talisman of Ascendance](https://user-images.githubusercontent.com/100415626/170673654-8319425d-aeec-4d03-84c9-50b786db6d6c.png)

Description: Use: [Your next 5 damage or healing spells cast within 20 seconds will grant a bonus of 40 spell power, stacking up to 5 times. Expires after 6 damage or healing spells or 20 seconds, whichever occurs first.](https://wotlkdb.com/?spell=28200) (1 minute cooldown)

### Source
![Talisman auto attacks](https://user-images.githubusercontent.com/100415626/170673808-50b2beab-61da-4318-946b-6d2a8ecbc30d.png)

### Steps to reproduce the problem
1. Activate trinket
2. Use any non-damage or non-healing spells as well as auto attacks and physical damage.
3. The stacks are applying.

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3545

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Dejanos** [comment]
Issue is linked to  #8676 and has been reported before, I have not noticed.
