### ISSUE TITLE
reaching seafloor removes aquatic form

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11885]
### Current Behaviour

When you reach seafloor, quite often you get out of aquatic form
![afbeelding](https://user-images.githubusercontent.com/20357406/170703638-dd1b7805-93d4-469e-9f70-a329b2bb6d73.png)

### Expected Blizzlike Behaviour

You should stay in aquatic form

### Steps to reproduce the problem

1. Go to sea
2. go in aquatic form
3. go to sea floor
4. get out of form automatically as if you reach land

### AC rev. hash/commit

cdd27bfff6cc

### Operating system

Ubuntu

**Comment by Gultask** [comment]
Took a look for this CC issue: https://github.com/chromiecraft/chromiecraft/issues/3557

It's not 100%, but I found it easier to reproduce it by swimming down in an angle. I found it similar to how if you move the same way with `.gm fly on` you'll take a little bit to 'snap' back to ground walking.

https://user-images.githubusercontent.com/100873791/170807706-e4b51957-e346-434d-88a8-b91e67837c9d.mp4
