### ISSUE TITLE
Some spells can hit through floor/roofs.

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11884]
### Current Behaviour

![afbeelding](https://user-images.githubusercontent.com/20357406/170702585-945123a3-d771-4f53-81fa-f0a9bfe6e75e.png)
See that I am hitting the trashfin below.

Starfall does the same
Searing totem hits through floor

### Expected Blizzlike Behaviour

AOE/starfall/searing totem should not hit through floor

### Steps to reproduce the problem

1. Go to BFD "moonshrine ruins"
2. Use any abiliies above the water
3. Hit creatures below
4

### AC rev. hash/commit

cdd27bfff6cc

### Operating system

Ubuntu

**Comment by Gultask** [comment]
I think Typhoon (ID: 50516) might do the same? I remember cooties-cc showing that it had a very high vertical range.

**Comment by Gultask** [comment]
Can't reproduce it in BFD either. But I remember that last sunday our guild had somehow managed to pull Broodlord Lashlayer from the rooms below. I tried reproducing it but couldn't.

![WoWScrnShot_060522_183511](https://user-images.githubusercontent.com/100873791/173196886-f308e176-bd31-445a-a107-199d949d573b.jpg)
