### ISSUE TITLE
Evergreen Herb Casing contain random herbs. Instead it should be Morrowgrain or Mutated Morrowgrain

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#11882]
### What client do you play on?

ruRU

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [X] 60

### Current Behaviour

Evergreen Herb Casing contain random herbs.

![WoWScrnShot_052722_114705](https://user-images.githubusercontent.com/100415626/170676065-4c992da1-803b-483b-b5b0-eebc9b3a41a8.jpg)

![WoWScrnShot_052722_114612](https://user-images.githubusercontent.com/100415626/170676093-7685d1a1-4e0c-442e-aae1-60460c35fd75.jpg)

### Expected Blizzlike Behaviour

As of 3.2 patch should no longer contain random herbs. Instead, they should contain only Morrowgrain and Mutated Morrowgrain.

### Source
![patch note](https://user-images.githubusercontent.com/100415626/170675720-7333aeb6-586d-41b9-8417-2c5f1149cc7b.png)

https://www.wowhead.com/item=11024/

>By hackersmuse on 2009/08/07 (Patch 3.1.3)		
As of 3.2, these no longer have a chance to contain random herbs.
You will either find Morrowgrain or useless grey "Mutated Morrowgrain" (no wowhead link available at the time of this post).
A nerf for those of us who would make these to farm herbs :(
On the plus side for questers, the cooldown to make them has been reduced to 5 seconds (used to be 10 minutes).

https://www.wowhead.com/item=11040
https://www.wowhead.com/item=49209

### Steps to reproduce the problem

1. .additem 11024
2. View loot in it

### Extra Notes
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3543

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
random herbs is correct
