### ISSUE TITLE
Warrior Charge ability still not commencing auto attacks unless target is right clicked

### ISSUE THREAD

**Issue by Dejanos** [azerothcore/azerothcore-wotlk#11899]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Using Charge (Rank 3, but that shouldn't make a difference) on an enemy does not automatically start auto attacking the enemy targeted and charged.

[Using Charge without right clicking the target on NPC ](https://streamable.com/v7dp3d)

[Using Charge without right clicking the target in PvP](https://streamable.com/7l0ffm)

[Using Charge on right click on NPC](https://streamable.com/7y9wfz)

[Using charge on right click in PvP](https://streamable.com/ojta6x)
### Expected Blizzlike Behaviour

Upon using Charge (Any and all ranks) you should start auto attacking the targeted enemy once you reach melee distance of them.

### Source

TBC Classic as demonstrated here: https://www.youtube.com/watch?v=q1UA4FYA0a4

### Steps to reproduce the problem

1. Left-click a creature
2. Use Charge (ID: 11578)

### Extra Notes
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3558
Was previously reported here:
https://github.com/chromiecraft/chromiecraft/issues/3460
https://github.com/azerothcore/azerothcore-wotlk/issues/11653

And was closed here:
https://github.com/azerothcore/azerothcore-wotlk/pull/11693

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by T1ti** [comment]
Related to this flag most likely 
![image](https://user-images.githubusercontent.com/40864460/172298589-97f5a3e1-ef30-4a93-994b-5d047eab21ed.png)

**Comment by T1ti** [comment]
Why did you not implement the spell attribute flag and instead hardcoded it to all charges ?
