### ISSUE TITLE
[World boss] Lethon - Draw spirit doesn't work

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#11891]
### Current Behaviour

The payer get the debuff but it's all. No adds spawn, no visual, no stun.

### Expected Blizzlike Behaviour

Everyone within 100 yards of Lethon will be stunned for 5 seconds and a Spirit Shade will walk out of their body. While stunned, each player will take 657 to 843 shadow damage every 2 seconds. The shades will walk toward Lethon and will heal him if they reach him. Each shade will heal Lethon for 15000 HP. The shades have 500 health each and are immune to AoE spells.

### Source

https://wowpedia.fandom.com/wiki/Lethon_(Classic)

https://youtu.be/AorovKZpoA0?t=32

### Steps to reproduce the problem

1. Engage Lethon
2. .damage until 75% of this life

### AC rev. hash/commit

fbd5e98

### Operating system

Windows 11

**Comment by temperrr** [comment]
Other issue is resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/12029
