### ISSUE TITLE
[Quest] The Air Stands Still questitem not working

### ISSUE THREAD

**Issue by NoM0Re** [azerothcore/azerothcore-wotlk#11893]
### Current Behaviour

When u have the boss in target u can use the questitem on him and its only blowing his horn at 2/3 bosses.

[Salranax the Flesh Render]
[Underking Talonox]

[High Priest Yath'amon] is working

### Expected Blizzlike Behaviour

That a Deathknigt is coming out of a portal when the Item is used on a boss from the quest like in the screenshot

![WoWScrnShot_052722_233944](https://user-images.githubusercontent.com/1629787/170792744-87547126-a919-435d-b679-459d462e4111.jpg)

### Source

https://www.youtube.com/watch?v=BmOmqDySvT8 (not this patch)

### Steps to reproduce the problem

1. .q a 13125
2. .go c 43483
3. target one of the three bosses around that area and try using the questitem on them

### Extra Notes

https://www.wowhead.com/quest=13125/the-air-stands-still

(https://www.wowhead.com/npc=30829/salranax-the-flesh-render)
(https://www.wowhead.com/npc=30830/underking-talonox)
(https://www.wowhead.com/npc=30831/high-priest-yathamon)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/2337342fc772e7029f135a1a0b863b793280c33f

### Operating system

Windows

**Comment by Tony931023** [comment]
fix https://github.com/azerothcore/azerothcore-wotlk/pull/12349 

Close issues
