### ISSUE TITLE
You can get skill point in gathering professions after object disappeared

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#11918]
### Current Behaviour

You can trigger a second gathering cast on the same object by right-click spamming the object during the first cast.

This behavior has been observed for **Pick Lock**, **Herbalism** and **Mining**. Skinning should be tested as well.

![picklock1](https://user-images.githubusercontent.com/62797536/170983355-18fb177f-3a8c-4de0-9bcb-15ef29ffde0d.jpg)
Picture 1: Pick Locking a footlocker.

![picklock2](https://user-images.githubusercontent.com/62797536/170983418-ba65376c-6ceb-46b0-ad15-704bb5fb1e73.jpg)
Picture 2: A second gathering cast can be done on the game object that disappeared.

Note that you cannot loot the object a second time this way, but if you did not a skill point from the first cast, you can get a skill point from the second one. Short: This issue makes leveling of gathering professions easier.

### Expected Blizzlike Behaviour

You should be able to cast gathering only once.

### Steps to reproduce the problem

1. Go to a game object, you want to gather (footlocker, herbs and minerals).
2. Gather it.
3. Spam right-click on the game object during the first cast.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
This is blizzlike. If you have auto loot turned off you can repeatedly "loot" the object in question to gain a skill point, no spamming required. But only one point pet item. Unless you're referring to 2 skill points off the same item.
https://github.com/chromiecraft/chromiecraft/issues/1491#issuecomment-903194332
