### ISSUE TITLE
[Onyxia] Onyxia Warders

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#11929]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Two issues:

There are too many Onyxia warders, there are 8-9 total warders

Other issue is that the patrols are wrong for both the main and excess warders

### Expected Blizzlike Behaviour

There should be 5: 
- 1 between entrance and the spot where you land after jumping
- 3 that patrol the entire tunnel length
- 1 static at the end in the alcove

Other issue is that the patrols are wrong for both the main and excess warders

### Source

https://www.youtube.com/watch?v=mIoKaLbMaT8

From Maelthyrr:

The pathway is the same between classic and woltk. 

- 3.3.5: 
https://www.youtube.com/watch?v=G2yc_Uw89vQ

- Classic:
https://www.youtube.com/watch?v=mR7xDgbF9-E&t=880s
https://youtu.be/5kx6k3A8ytM?t=77

### Steps to reproduce the problem

Enter onyxia's lair 

### Extra Notes

Originaly reported: https://github.com/chromiecraft/chromiecraft/issues/2955

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6f20b9ece71984f1a11469e65ede8accda05653e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
I don't believe there are supposed to be five, but rather four. Based on the retail Wrath video source, I counted three patrolling and the static one at the end of the tunnel (which wasn't seen in the video due to a cut). I also only counted these four in the Classic/Classic Era video sources. Also lined up with my observations on Wrath Classic for both 10m and the level 60 time-travelling version, though I haven't checked 25m yet.
