### ISSUE TITLE
Durations for commands `mute` and `deserter [bg/instance] add` should be the same format as `ban`

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#11920]
### Describe your feature request or suggestion in detail

Make all the commands use the same duration format that the `ban` command uses such as  `4d20h6m9s` for 4 days, 20 hours, 6 minutes and 9 seconds.

If you wish to mute Angrygnome for a day, which is 1440 minutes then you will have to type `.mute Angrygnome 1440 Being a gnome`. Instead, I would like to only type `.mute Angrygnome 1d Being a gnome` because it is a lot easier to read.

There is also the `deserter bg add` and `deserter instance add`. The duration is in seconds. If you wish to grant a gnome a 13 days battleground deserter then type the following command when having them targetted: `.deserter bg add 1123200`
This number is ridiculous and unreadable unlike `.deserter bg add 13d`.

### Describe a possible solution to your feature or suggestion in detail

Make all the commands use the same duration format that the `ban` command uses such as  `4d20h6m9s` for 4 days, 20 hours, 6 minutes and 9 seconds.

### Additional context

Looking on the [GM commands wiki](https://www.azerothcore.org/wiki/gm-commands), there are these two commands that might need a similar treatment.

`.npc add move #creature_guid [#waittime]`
`.npc set spawntime #time`

The implementation of the feature may require an update on the [GM command wiki](https://www.azerothcore.org/wiki/gm-commands).

For anything that might **needs** to work with the old durations, if there are letters in the duration, it is the `4d20h6m9s` duration format otherwise, it would be in seconds for the `deserter` command and minutes for the `mute` command.

**Comment by Gozzim** [comment]
Gonna take care of this and other commands with time parameters to have an overall uniform format.
