### ISSUE TITLE
[Shaman] After removing Glyph of Totem of Wrath the Buff from the Totem should be gone

### ISSUE THREAD

**Issue by NoM0Re** [azerothcore/azerothcore-wotlk#11939]
### Current Behaviour

When u use the [Glyph of Totem of Wrath](https://wotlkdb.com/?item=45776) and cast [Totem of Wrath](https://wotlkdb.com/?spell=57722), u will get the buff [Totem of Wrath](https://wotlkdb.com/?spell=63283).

When u remove or change the Glyph u still have the buff and the additional spell power by 30% of the bonus spell power granted by your Totem of Wrath.

### Expected Blizzlike Behaviour

When u remove or change the Glyph u should get the buff removed.

### Steps to reproduce the problem

log into a shaman
.level 79
.learn all class
.additem 50458
.additem 45776 (Glyph) and use it
use [Totem of Wrath](https://wotlkdb.com/?spell=57722)
now u have the buff check ur spellpower
remove the glyph with shift rightclick
check ur spellpower
click the buff away
check ur spellpower

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a8eb0ef7b53680f532a5c106d6398ae64d87b073

### Operating system

Windows

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12168

**Comment by Gultask** [comment]
https://github.com/chromiecraft/chromiecraft/issues/2815
