### ISSUE TITLE
[Shaman] Fire/Earth Elementar Cooldown can be ignored by Call of the Elements after 2mins

### ISSUE THREAD

**Issue by NoM0Re** [azerothcore/azerothcore-wotlk#11937]
### Current Behaviour

[Fire Elemental Totem](https://wotlkdb.com/?spell=2894) and [Earth Elemental Totem](https://wotlkdb.com/?spell=2062) Cooldown is both 10mins and Category Cooldown is 2 minutes.

BUT when u use [Call of the Elements](https://wotlkdb.com/?spell=66842), [Call of the Spirits](https://wotlkdb.com/?spell=66843) or [Call of the Ancestors](https://wotlkdb.com/?spell=66844)
u can skip the 10min Cooldown after 2mins on the Fire Elemental Totem and Earth Elementar.

Extra Note:
u can NOT spawn the totem by simply trying to spawn the Fire Elemental Totem when its on Cooldown.

### Expected Blizzlike Behaviour

Fire Elemental Totem got 10min Cooldown u can use [Call of the Elements](https://wotlkdb.com/?spell=66842), [Call of the Spirits](https://wotlkdb.com/?spell=66843) or [Call of the Ancestors](https://wotlkdb.com/?spell=66844) but the Totems are not spawning because of the Cooldown.

### Steps to reproduce the problem

- log into a shaman
- .level 79
- .learn all class
- .additem 50458
- use fire elemental totem then wait 2 min
- use [Call of the Elements](https://wotlkdb.com/?spell=66842), [Call of the Spirits](https://wotlkdb.com/?spell=66843) or [Call of the Ancestors](https://wotlkdb.com/?spell=66844) with fire ele totem in it and see what happens
- try the same with earth elemental totem

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a8eb0ef7b53680f532a5c106d6398ae64d87b073

### Operating system

Windows

**Comment by NoM0Re** [comment]
https://user-images.githubusercontent.com/1629787/172127102-23f72579-053d-4080-88c8-e4681f7652f1.mp4

**Comment by Maelthyrr** [comment]
Confirmed on my local.

**Comment by mpfans** [comment]
Confirmed

**Comment by NoM0Re** [comment]
#11938
#11939
pls aswell
