### ISSUE TITLE
A bug in Unit::CalculateMeleeDamage

### ISSUE THREAD

**Issue by Nirn90** [azerothcore/azerothcore-wotlk#11962]
### Current Behaviour

Here is the code from Unit.cpp line 1468
```text
    damage += CalculateDamage(damageInfo->attackType, false, true);
    // Add melee damage bonus
    damage = MeleeDamageBonusDone(damageInfo->target, damage, damageInfo->attackType);
    damage = damageInfo->target->MeleeDamageBonusTaken(this, damage, damageInfo->attackType);
```
The damage value gets overwritten. Shouldn't it be += instead?
    

### Expected Blizzlike Behaviour

None

### Source

None

### Steps to reproduce the problem

None

### AC rev. hash/commit

14d933eddc57ea121e1a01d6d2e0977a8f654253

### Operating system

None

**Comment by UltraNix** [comment]
No. It should be overriden, as these function calculates damage based on prev values of this variable.
`damage = MeleeDamageBonusDone(damageInfo->target, **damage**, damageInfo->attackType);`
`damage = damageInfo->target->MeleeDamageBonusTaken(this, **damage**, damageInfo->attackType);`
