### ISSUE TITLE
First aid trainers cannot learn skills

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#11979]
### Current Behaviour

First aid trainers in 'Hellfire Peninsula' cannot learn first aid skills Now there are only sales brochures They used to be a trainer

(creature id 18990 or 18991)

You can see that they have a list of skills
`SELECT * FROM npc_trainer  WHERE ID = 18990 or  ID = 18991; `

`SELECT * FROM creature_template  WHERE entry = 18990  OR entry = 18991;` 
Looking at the `npcflag` = 208 , you can see that they are a trainer and a vendor
![image](https://user-images.githubusercontent.com/18187177/172351699-e581c19e-d072-4884-afe8-c31d84737e26.png)

### Expected Blizzlike Behaviour

You can learn first aid skills from them and sell some goods  (creature id 18990 or 18991 )

### Steps to reproduce the problem

1. '.go c id 18990'(horde is 18991)
2. Talk to him

### AC rev. hash/commit

94e7338fe6a2f103fac4d3ad777b4592f9af7f81

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
This commit broke them

https://github.com/azerothcore/azerothcore-wotlk/commit/dd15fa706d6aa2f841b0a521fd9ebd03fdb0f97f

**Comment by Tony931023** [comment]
Exactly after that PR there are several errors found, such as quest 10994 when invoking NPC 23002 does nothing, you have to increase the flag +1 (GOSIP - If creature has more gossip options, add this flag to bring up a menu.) to make it work
