### ISSUE TITLE
Modules no longer compile on Linux

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#11978]
### Current Behaviour

Modules no longer compile on linux
They get completely skipped

### Expected Blizzlike Behaviour

Modules compile on linux

### Steps to reproduce the problem

1. compile with https://github.com/chromiecraft/azerothcore-wotlk/commit/4fbec972a8fe55d73744205322298791ded0c204
2. compile with any module
3. see that they dont compile
4. revert https://github.com/chromiecraft/azerothcore-wotlk/commit/4fbec972a8fe55d73744205322298791ded0c204
6. see that modules compile

### AC rev. hash/commit

70f3891352744ede66b12c3e1b2e52d3d5794564

### Operating system

Ubuntu x 64

### Custom changes or Modules

mod-progression-system
mod-eluna
mod-cfbg
mod-transmog

and more

**Comment by temperrr** [comment]
I have the same issue on my local manjaro installation

**Comment by tkn963** [comment]
> I have the same issue on my local manjaro installation

What compiler do you use on Ubuntu and Manjaro?

**Comment by temperrr** [comment]
What cmake settings do you use

**Comment by tkn963** [comment]
> What cmake settings do you use

cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/azerothcore -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DSCRIPTS=static

**Comment by temperrr** [comment]
Odd I use the same

**Comment by tkn963** [comment]
I don't know if it affects every module available, do you? I mainly use my own modules but I do use the skip dk starting area and ah bot modules on top of those. They all function for me.

**Comment by temperrr** [comment]
Ok I fixed it on my local with adding 
"-DMODULES=static;" to the end of cmake.

The other two servers use acore to build. I guess there must be an error there.
