### ISSUE TITLE
Cannot Compile Map Extraction Tools on windows

### ISSUE THREAD

**Issue by Mindary-Warlock** [azerothcore/azerothcore-wotlk#11973]
### Current Behaviour

When trying to compile map_extractor, mmaps_generator, vmap4_assambler or vmap4_extractor i always get the same
syntaxerrors:

![grafik](https://user-images.githubusercontent.com/87987908/172198105-d99f16e4-8ddb-4473-9b61-dafb865ba65d.png)

Already did compile Azerothcore a couple times - i never had errors before compiling on the very same device.

Thanks for your help :-)

Greetings.

### Expected Blizzlike Behaviour

No errors while compliling map_extractor, mmaps_generator, vmap4_assambler or vmap4_extractor.

### Steps to reproduce the problem

![grafik](https://user-images.githubusercontent.com/87987908/172199020-087c0803-4680-4b42-8e77-e7b4dc39ea05.png)

Compile map_extractor, mmaps_generator, vmap4_assambler or vmap4_extractor using "ALL_BUILD".

Using the installationguide: https://www.azerothcore.org/wiki/installation

### AC rev. hash/commit

14d933e

### Operating system

Windows 10 x64

**Comment by acidmanifesto** [comment]
Is this issue about a linux or a windows compile issue? Im getting a bit confused with the topic and info provided.

**Comment by Mindary-Warlock** [comment]
Operating system

Windows 10 x64 - Tho a windows compile issue.

**Comment by acidmanifesto** [comment]
> Operating system
> 
> Windows 10 x64 - Tho a windows compile issue.

So just to clarify. This is windows only and not linux?

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/11614
