### ISSUE TITLE
DK [Glyph of Disease] 

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#11970]
### Current Behaviour

[[Glyph of Disease]](http://wotlk.cavernoftime.com/item=45805) effect does not refresh Chill, Blood Plague on a Death Knight while under Anti-Magic Shell

### Expected Blizzlike Behaviour

When using the Pestilence ability, the duration of diseases and their secondary effects on the target is updated.
https://www.warcraftmovies.com/movieview.php?id=157009 7:35

### Steps to reproduce the problem

1. We study the symbol of the disease.
2. We impose on the dk dots. 2nd uses anti-magic shell
3. We use the ability of pestilence;

### Extra Notes

None

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/14d933eddc57ea121e1a01d6d2e0977a8f654253

### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by UltraNix** [comment]
Tested - everything works okay.
