### ISSUE TITLE
Realm Selection menu showing wrong number of characters

### ISSUE THREAD

**Issue by Luckdemon** [azerothcore/azerothcore-wotlk#11990]
Original report: https://github.com/chromiecraft/chromiecraft/issues/3566

To reproduce:
1. Make 2 characters
2. Delete 1

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Realm selection menu shows more characters than are selectable by the player.
![image](https://user-images.githubusercontent.com/38561765/170901487-4f56e1d3-56f2-4702-b271-4956af6a8c4d.png)

### Expected Blizzlike Behaviour

Number of characters in the realm selection menu should reflect selectable characters on the realm.

### Source

Common sense.

### Steps to reproduce the problem

Unknown

### Extra Notes

Could be related to a deleted character I had when I first started on CC. 100% consistent between game launches and logins.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by benjymansy123** [comment]
Looks like this is an issue related to auth.realmcharacters. The table has the `numchars` declared in the table, but it never seems to be able to go down.

**Comment by heyitsbench** [comment]
A related issue to this: When creating a character, the server consults the `numchars` column to determine how many characters the account has, so if this column and the actual number of characters are desynchronized, the server will tell the client that they've reached the maximum character count prematurely.

**Comment by heyitsbench** [comment]
Interestingly enough, I had my realmlist player count desync on Blizzard's PTR. I believe this happened because they wipe the characters between their PTR runs, and mine got swept up in that. [Here's the video I recorded](https://user-images.githubusercontent.com/38561765/209418396-725af72c-8264-443e-8f0c-86f1c1222ba4.mp4). It seems this value got fixed upon my logging in to that realm.
