### ISSUE TITLE
[EPIC] Keeping compatibility with TC database

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#12]
I open this issue to collect all issues about this "epic".

Would be nice to keep Database Structure and SOAP Interface compatible with latest versions of TrinityCore as much as possible. Offering a legacy interface for TC Soap for example.
This to allow developers to create external tools and sql mods that can easily communicate/work for both server applications.
##

**Comment by ShinDarth** [comment]
This should help: https://github.com/AzerothCore/azerothcore-wotlk/pull/27

**Comment by ShinDarth** [comment]
This helped too: https://github.com/azerothcore/azerothcore-wotlk/pull/154

it would be nice to track the differences left

**Comment by ShinDarth** [comment]
see https://github.com/azerothcore/azerothcore-wotlk/issues/236
