### ISSUE TITLE
Visual Stuido 2013 Compile error

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#120]
**Description**:

**Current behaviour**: Tell us what happens
Getting 3 errors and 1 warning.

**Errors**:

1. error C2664: 'std::atomic_long::atomic_long(const std::atomic_long &)' : cannot convert argument 1 from 'int' to 'const std::atomic_long &'	E:\AzerothCore\src\game\Server\WorldSocketMgr.cpp	50	1	game

2. error C2664: 'std::atomic_long::atomic_long(const std::atomic_long &)' : cannot convert argument 1 from 'int' to 'const std::atomic_long &'	E:\AzerothCore\src\game\Scripting\ScriptMgr.cpp	154	1	game

3. error LNK1104: cannot open file '..\game\Debug\game.lib'	E:\AzerothCore\build\src\worldserver\LINK	worldserver

Warning
1. Warning	1	warning C4018: '>=' : signed/unsigned mismatch	E:\AzerothCore\src\game\Handlers\MiscHandler.cpp	401	1	game

**Operating system**:  Windows 10 x64 Bit

**Program Used to compile**: Visual Stuido 2013

**Comment by DantestyleXD** [comment]
Same errors here

----------------------------
Server: Local (Repo AzerothCore)
Last commit hash tested:  2407208eb6288db753a5611fb0a81205aee03410
O.S.: Windows 10
Compiler: MS Visual Studio 2013

**Comment by ShinDarth** [comment]
@talamortis @DantestyleXD  can you please tell us which is the latest commit that works for you?

you can change commit using:

`git checkout COMMIT_HASH`

**Comment by hero2880** [comment]
I also like this, the first version can be compiled successfully; later versions have failed. Also used VS2013. However, the recent compilation of TC and SINGLECORE succeed.

**Comment by ShinDarth** [comment]
@hero2880 what is the LATEST commit that you can successfully compile?

**Comment by hero2880** [comment]
@ShinDarth ，it‘s’ Version July 28, I was successful compilation at July 30.

**Comment by ShinDarth** [comment]
@talamortis  @DantestyleXD  @hero2880 can you guys please test it using Visual Studio 2015?

By the way, Visual Studio 2013 is deprecated now: https://community.trinitycore.org/topic/12805-visual-studio-2013-end-of-life/

**Comment by Chrisjiajun** [comment]
Me too, I hope to fix. 
error CMake and Visual Studio 2015,Only use Visual Studio 2013.

**Comment by talamortis** [comment]
CMake works correctly, in 2015 i get over 100 errors. when i compile with 2013 i only get them two.

**Comment by ShinDarth** [comment]
@talamortis did you try a clean build with VS 2015 ?

**Comment by cnmir2** [comment]
CMake works correctly, in 2015 i get over 100 errors. when i compile with 2013 i only get them two. 

same !

**Comment by Yehonal** [comment]
@cnmir2 in 2015 do you have errors about mysql libs?

**Comment by DevRival** [comment]
@Yehonal I have error for MySQL in mvs2015)

**Comment by talamortis** [comment]
Yes its to do with MYSQL LIB

**Comment by talamortis** [comment]
Ok, i managed to get it to compile with VS 2013 using the old sunwell code for WorldSocketMgr.cpp, ScriptMgr.cpp and ScriptMgr.h but when i run the server i get the error  

C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xtree(238): Assertion failed: "Standard C++ Libraries out of range" && 0

C:\Program Files\Microsoft Visual Studio 12.0\VC\include\xtree(237): Assertion failed: map/set iterator not dereferencable

**Comment by ShinDarth** [comment]
@talamortis  forget about sunwellcore and try to:

- replace [this line](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/game/Server/WorldSocketMgr.cpp#L48) with `m_Connections((std::atomic<long>)(0)),`

- replace [this line](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/game/Scripting/ScriptMgr.cpp#L153) with `: _scriptCount(0), _scheduledScripts((std::atomic<long>)(0))`

I'm not sure about that, and I can't test it since I don't have Windows, but you can try it

**Comment by talamortis** [comment]
@ShinDarth ok i will test this code, but any idea's why im getting the other errors?

**Comment by ShinDarth** [comment]
I have not

**Comment by Chrisjiajun** [comment]
@ShinDarth THX！already been fixed.

**Comment by Chrisjiajun** [comment]
@ShinDarth i run the server i get the error 

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(237) : Assertion failed: map/set iterator not dereferencable
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(238) : Assertion failed: "Standard C++ Libraries Out of Range" && 0
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(237) : Assertion failed: map/set iterator not dereferencable
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(238) : Assertion failed: "Standard C++ Libraries Out of Range" && 0
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(237) : Assertion failed: map/set iterator not dereferencable
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtree(238) : Assertion failed: "Standard C++ Libraries Out of Range" && 0

over and over again

**Comment by Abyssking** [comment]
You can also use (ATOMIC_FLAG_INIT) instead of converting values it will return 0 in ATOMIC Format...
m_Connections(ATOMIC_FLAG_INIT)
_scheduledScripts(ATOMIC_FLAG_INIT)

**Comment by ShinDarth** [comment]
thanks, can anyone of the Windows guys try what @Abyssking said and let us know?

**Comment by Abyssking** [comment]
MS2015, Error Is snprintf and it may be handle with using _snprintf instead of snprintf but, it seems using mobile toolkit for compiling! 
@ShinDarth my own compile fixed with this, but for the warning, I guess we may use the uint8 converting to fix the warning : '>='! but i guess only, take compile and let us know! 
i Wounder... anyone have any knowledge about it?

**Comment by Yehonal** [comment]
The issue @Abyssking seems to be realated to this @ShinDarth changes: https://github.com/azerothcore/azerothcore-wotlk/commit/a4589f71d5906281581303b4d9430ea65f79c31a#diff-dab343a82b0ca3cdd0534b597a6ea63f

i'm trying to fix it

**Comment by ShinDarth** [comment]
can all the windows guys update their core revision and try it again?

the issue should have been solved

**Comment by Abyssking** [comment]
@ShinDarth I try it, set a external mysql is a little twisted but anyway, it's done good exclude the 'snprintf', i have vsscanf and vsprinf error in my crash log,
http://pastebin.com/jxJvJPAv
this crash happens when my gm character have transactions like teleport or other transactions that i guess is a little special i have Race (0) Problem Too.

**Comment by talamortis** [comment]
@Abyssking update your core @Yehonal fixed this earlier :) and #137 has already been reported

**Comment by Yehonal** [comment]
About mysql, now it's the same process of trinitycore, however mysql
sources included with repo compiled well for you, you can use the
MYSQL_USE_SOURCES cmake def.

About crash. Did you tested latest commit? It could be related

Your crash log is not good, you need to compile in debug mode

Il 04/Set/2016 20:12, "Abyssking" <notifications@github.com> ha scritto:

**Comment by Abyssking** [comment]
@Yehonal yup, I used 4 last commit and i used debug mode, but i check it completely tnx..

**Comment by talamortis** [comment]
@Abyssking are you still getting this problem? as im getting the same problem :)

**Comment by Abyssking** [comment]
@talamortis I don't use the new commits but my last build have crash without reason, log, and even Windows Not Reponsing Error...

**Comment by talamortis** [comment]
Does not support VS2013 Update to VS2015
