### ISSUE TITLE
[Bloodmyst Isle] Fenissa the Assassin (ID: 22060) missing waypoints and spawn points.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12006]
### Current Behaviour

There are 2 spawn points (77280 and 77281) and both are stationary without wandering.

### Expected Blizzlike Behaviour

> She has three seperate spawnpoints and paths. She is a rather unusual 'rare' in that she spawns and coexists in ALL THREE points. I've checked it twice: following all three of the paths, finding her in one of them, leaving her 'alive', running to the other places, finding her there too, and only then killing her and running back to kill her other incarnations.
> 
> The paths are the following:
> 1: The vector coil top
> On top of the vector coil are two pylons. Fenissa starts at one of those, then follows the path downhill, along the base of the coil where you have to place the charges to blow it up, then up the path on the far side to the second pylon. When she reaches it, she will retrace her steps, going back and forth.
> 
> 2: The camps and the path at the bottom of the vector coil
> At the bottom of the hill there are three camps with Sunhawk Pyromancers and Defenders, non-elite. The westernmost of these is the camp with the Sun Portal, where the Sunhawk fight Void Critters. Fenissa starts in this camp, not far from the path that leads up the hill of the Vector Coil. She does not go uphill to the Coil, but stays on the lower part of the path, walking towards the northeastern camp. This is also the point where Matis the Cruel tends to halt. She continues on to the middle of the northeastern camp. Then she stoops and retraces her path to the western camp, again walking back and forth.
> 
> 3: The Cryo Core
> This path is circular, unlike the other two. She follows a counterclockwise path just inside the hills that form the outer rim of the impact crater. Part of her route leads her a little further in, but she seldom nears the Cryo Core itself, except on the southernmost part where there is very little room between the core and the mountainside. Walk a clockwise path and you'll be sure to find her.

### Source

https://tbc.wowhead.com/npc=22060/fenissa-the-assassin#comments

### Steps to reproduce the problem

.go c id 22060

### AC rev. hash/commit

8151fcda22c6

### Operating system

Windows 10

**Comment by neifion-00000000** [comment]
(Numbering Based on Above)

SQL Will need reformatted.  Wait times and emotes need figured out.

Path 1 Vector Coil -- kneel emotes at each end

-- Pathing for  Entry: 22060
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-1970.9095,`position_y`=-10545.881,`position_z`=176.9451 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-1970.9095,-10545.881,176.9451,0,0,0,0,100,0),
(@PATH,2,-1940.0586,-10560.943,177.81454,0,0,0,0,100,0),
(@PATH,3,-1946.3624,-10587.011,172.94002,0,0,0,0,100,0),
(@PATH,4,-1961.7201,-10607.221,165.48112,0,0,0,0,100,0),
(@PATH,5,-1988.8058,-10612.373,162.95183,0,0,0,0,100,0),
(@PATH,6,-2013.801,-10602.308,154.4991,0,0,0,0,100,0),
(@PATH,7,-2038.0187,-10619.16,146.1079,0,0,0,0,100,0),
(@PATH,8,-2037.1124,-10638.802,140.50319,0,0,0,0,100,0),
(@PATH,9,-2012.5981,-10662.126,122.97834,0,0,0,0,100,0),
(@PATH,10,-1976.1384,-10684.696,112.91368,0,0,0,0,100,0),
(@PATH,11,-1947.3251,-10695.539,110.90299,0,0,0,0,100,0),
(@PATH,12,-1908.1012,-10710.498,111.27751,0,0,0,0,100,0),
(@PATH,13,-1875.1051,-10702.744,111.70239,0,0,0,0,100,0),
(@PATH,14,-1855.2137,-10689.97,112.97398,0,0,0,0,100,0),
(@PATH,15,-1824.9171,-10668.398,136.08665,0,0,0,0,100,0),
(@PATH,16,-1819.2031,-10647.129,144.38739,0,0,0,0,100,0),
(@PATH,17,-1812.0326,-10612.489,148.245,0,0,0,0,100,0),
(@PATH,18,-1833.3806,-10588.412,157.1347,0,0,0,0,100,0),
(@PATH,19,-1867.1841,-10566.302,174.33784,0,0,0,0,100,0),
(@PATH,20,-1877.4294,-10545.098,177.00142,0,0,0,0,100,0),
(@PATH,21,-1867.1841,-10566.302,174.33784,0,0,0,0,100,0),
(@PATH,22,-1833.3806,-10588.412,157.1347,0,0,0,0,100,0),
(@PATH,23,-1812.0326,-10612.489,148.245,0,0,0,0,100,0),
(@PATH,24,-1819.2179,-10647.147,144.46405,0,0,0,0,100,0),
(@PATH,25,-1824.9171,-10668.398,136.08665,0,0,0,0,100,0),
(@PATH,26,-1855.2137,-10689.97,112.97398,0,0,0,0,100,0),
(@PATH,27,-1875.1051,-10702.744,111.70239,0,0,0,0,100,0),
(@PATH,28,-1908.1012,-10710.498,111.27751,0,0,0,0,100,0),
(@PATH,29,-1947.3251,-10695.539,110.90299,0,0,0,0,100,0),
(@PATH,30,-1976.1384,-10684.696,112.91368,0,0,0,0,100,0),
(@PATH,31,-2012.5981,-10662.126,122.97834,0,0,0,0,100,0),
(@PATH,32,-2037.1124,-10638.802,140.50319,0,0,0,0,100,0),
(@PATH,33,-2038.0187,-10619.16,146.1079,0,0,0,0,100,0),
(@PATH,34,-2013.801,-10602.308,154.4991,0,0,0,0,100,0),
(@PATH,35,-1988.8058,-10612.373,162.95183,0,0,0,0,100,0),
(@PATH,36,-1961.7201,-10607.221,165.48112,0,0,0,0,100,0),
(@PATH,37,-1946.3624,-10587.011,172.94002,0,0,0,0,100,0),
(@PATH,38,-1940.0586,-10560.943,177.81454,0,0,0,0,100,0);
-- 0x204CB04240158B0000003E0000187A4E .go xyz -1970.9095 -10545.881 176.9451

Path 2 Camps -- kneel emotes at a couple spots

-- Pathing for  Entry: 22060
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-2062.9329,`position_y`=-10801.382,`position_z`=69.16798 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-2062.9329,-10801.382,69.16798,0,0,0,0,100,0),
(@PATH,2,-2032.4478,-10792.326,79.548546,0,0,0,0,100,0),
(@PATH,3,-2011.9824,-10776.279,85.89645,0,0,0,0,100,0),
(@PATH,4,-1988.4141,-10782.808,89.01292,0,0,0,0,100,0),
(@PATH,5,-1956.8325,-10795.888,88.076256,0,0,0,0,100,0),
(@PATH,6,-1941.5137,-10813.049,83.2548,0,0,0,0,100,0),
(@PATH,7,-1942.2377,-10845.413,71.92745,0,0,0,0,100,0),
(@PATH,8,-1928.1111,-10873.158,65.57274,0,0,0,0,100,0),
(@PATH,9,-1907.5723,-10881.021,64.005844,0,0,0,0,100,0),
(@PATH,10,-1882.5653,-10890.086,67.090805,0,0,0,0,100,0),
(@PATH,11,-1869.1376,-10890.733,66.91844,0,0,0,0,100,0),
(@PATH,12,-1863.5938,-10877.981,66.82205,0,0,0,0,100,0),
(@PATH,13,-1857.8864,-10870.527,66.82205,0,0,0,0,100,0),
(@PATH,14,-1864.6426,-10848.86,66.77268,0,0,0,0,100,0),
(@PATH,15,-1857.8864,-10870.527,66.82205,0,0,0,0,100,0),
(@PATH,16,-1863.5938,-10877.981,66.82205,0,0,0,0,100,0),
(@PATH,17,-1869.1376,-10890.733,66.91844,0,0,0,0,100,0),
(@PATH,18,-1882.5653,-10890.086,67.090805,0,0,0,0,100,0),
(@PATH,19,-1907.4796,-10881.057,64.12523,0,0,0,0,100,0),
(@PATH,20,-1928.1111,-10873.158,65.57274,0,0,0,0,100,0),
(@PATH,21,-1941.4618,-10813.143,83.373695,0,0,0,0,100,0),
(@PATH,22,-1956.7793,-10795.982,88.01302,0,0,0,0,100,0),
(@PATH,23,-1988.4141,-10782.808,89.01292,0,0,0,0,100,0),
(@PATH,24,-2011.9735,-10776.271,85.738,0,0,0,0,100,0),
(@PATH,25,-2032.4478,-10792.326,79.548546,0,0,0,0,100,0),
(@PATH,26,-2062.9329,-10801.382,69.16798,0,0,0,0,100,0),
(@PATH,27,-2090.1667,-10768.454,68.06485,0,0,0,0,100,0);
-- 0x204CB04240158B0000003E00001879BC .go xyz -2062.9329 -10801.382 69.16798

Path 3 Cryo Core 

-- Pathing for  Entry: 22060
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-2070.419,`position_y`=-11257.795,`position_z`=68.73054 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-2070.419,-11257.795,68.73054,0,0,0,0,100,0),
(@PATH,2,-2103.6235,-11253.354,67.19258,0,0,0,0,100,0),
(@PATH,3,-2134.2869,-11264.738,67.698784,0,0,0,0,100,0),
(@PATH,4,-2140.428,-11280.03,65.155426,0,0,0,0,100,0),
(@PATH,5,-2138.178,-11312.154,62.253426,0,0,0,0,100,0),
(@PATH,6,-2136.1165,-11343.568,62.17387,0,0,0,0,100,0),
(@PATH,7,-2126.4175,-11372.446,64.164536,0,0,0,0,100,0),
(@PATH,8,-2098.3645,-11381.112,63.737923,0,0,0,0,100,0),
(@PATH,9,-2076.6472,-11386.729,63.017952,0,0,0,0,100,0),
(@PATH,10,-2055.42,-11392.572,61.29661,0,0,0,0,100,0),
(@PATH,11,-2030.3889,-11375.75,63.414944,0,0,0,0,100,0),
(@PATH,12,-2022.589,-11355.197,64.74541,0,0,0,0,100,0),
(@PATH,13,-2019.8142,-11323.221,65.71863,0,0,0,0,100,0),
(@PATH,14,-2031.3025,-11303.861,67.92053,0,0,0,0,100,0),
(@PATH,15,-2026.8136,-11290.435,69.10076,0,0,0,0,100,0),
(@PATH,16,-2026.6367,-11276.236,68.70916,0,0,0,0,100,0),
(@PATH,17,-2042.9447,-11261.928,68.52818,0,0,0,0,100,0);
-- 0x204CB04240158B0000003E00001CE01C .go xyz -2070.419 -11257.795 68.73054

**Comment by neifion-00000000** [comment]
https://www.youtube.com/watch?v=dqFrvwqBzbk

If anyone wants to put in the proper emotes.  waypoint_data does not work for this creature as for some reason waypoints override normal mob behaviors

SAI is the only way this will work at the moment, and I really don't like SAI, it seems extremely convoluted for no reason.

**Comment by Gultask** [comment]
Fixed
