### ISSUE TITLE
Warrior Quest Chain for lvl20+ Gear Cannot Be Completed

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12007]
https://github.com/chromiecraft/chromiecraft/issues/3372

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Completing Fire Hardened Mail (1701) does not unlock quests Burning Blood (1705) Iron Coal (1708) and Sunscorched Shells (1710)

It does unlock the race-exclusive crumb quests [Grimand Elmore](https://wowgaming.altervista.org/aowow/?quest=1700), [Klockmort Spannerspan](https://wowgaming.altervista.org/aowow/?quest=1704) and [Mathiel](https://wowgaming.altervista.org/aowow/?quest=1703) to their respective races.

### Expected Blizzlike Behaviour

After turning in Fire Hardened Mail, quests 1705, 1708 and 1710 should all be unlocked and available by going to their questgivers, ignoring the crumb quests if they aren't available.

### Source

Sniffs and Classic research from @neifion-00000000 

Also thanks to Tebec for pointing this out.
>The race tags on the above is just which NPC Furen will send you to after he gives you your armor. The other two NPC's will give you their quest if you locate them manually, so you can get an (almost) full set of Fire Hardened if you are willing to run to them and do their errands.
>
>About Draenei, it seems they don't get a note from Furen to give to one of the other smiths. But the quests should get unlocked anyway. The Human smith is around the corner from Furen so it is a quick check for a curious Draenei.:) ([source](https://www.wowhead.com/quest=1701/fire-hardened-mail#comments:id=152454))

### Steps to reproduce the problem

1. `.quest add 1701` `.quest complete 1701` `.go q ender 1701`
2. turn in the quest, depending on your race one crumb quest should have unlocked.
3. `.go q starter 1705` `.go q starter 1708` `.go q starter 1710`
4. check if the quests Burning Blood, Iron Coal and Sunscorched Shells are available to be taken.

### Extra Notes

From @neifion-00000000:

![image](https://user-images.githubusercontent.com/91289495/173171295-d6a3cff0-415b-407f-b133-f0abb1f6927d.png)
Putting this here so it doesn't get lost, but in researching this I found something else wrong, these should drop 1-2 1x not 1-2x

(Same with Charred Horns 1-3 1x not 1-3x)
![image](https://user-images.githubusercontent.com/91289495/173172014-c7bb9038-5ff1-4ba2-9c25-0b5cb3175f6a.png)

Also these mobs have interesting pathing that might be worth looking into.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7518a7ccd69369b366f29d314baf3a72a61c3045

### Operating system

Ubuntu 20.04
Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by neifion-00000000** [comment]
currently working on this one, simultaneously checking the follow-ups in case of same issue
