### ISSUE TITLE
DB restructuring - world - spell_proc_*

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1202]
This is part of: https://github.com/azerothcore/azerothcore-wotlk/issues/1118

**General note**: not all structure differences can or should be imported. Every change must be first verified. If a structure change is not suitable, we just close the issue.

---

This looks a bit confusing. Basically we have two tables `spell_proc` and `spell_proc_event`, while on TC there is only `spell_proc`.

We need to investigate to understand if this is something that SC devs did (in that case we most likely want to keep things as they currently are) or if it was a refactoring made in TC (in that case we can just import it).

```diff
--- Dumping structure for table acore_world.spell_proc
+-- Dumping structure for table tc_world.spell_proc
 DROP TABLE IF EXISTS `spell_proc`;
 CREATE TABLE IF NOT EXISTS `spell_proc` (
-  `spellId` mediumint(8) NOT NULL DEFAULT '0',
-  `schoolMask` tinyint(4) NOT NULL DEFAULT '0',
-  `spellFamilyName` smallint(5) unsigned NOT NULL DEFAULT '0',
-  `spellFamilyMask0` int(10) unsigned NOT NULL DEFAULT '0',
-  `spellFamilyMask1` int(10) unsigned NOT NULL DEFAULT '0',
-  `spellFamilyMask2` int(10) unsigned NOT NULL DEFAULT '0',
-  `typeMask` int(10) unsigned NOT NULL DEFAULT '0',
-  `spellTypeMask` int(10) unsigned NOT NULL DEFAULT '0',
-  `spellPhaseMask` int(11) NOT NULL DEFAULT '0',
-  `hitMask` int(11) NOT NULL DEFAULT '0',
-  `attributesMask` int(10) unsigned NOT NULL DEFAULT '0',
-  `ratePerMinute` float NOT NULL DEFAULT '0',
-  `chance` float NOT NULL DEFAULT '0',
-  `cooldown` float unsigned NOT NULL DEFAULT '0',
-  `charges` int(10) unsigned NOT NULL DEFAULT '0',
-  PRIMARY KEY (`spellId`)
-) ENGINE=MyISAM DEFAULT CHARSET=utf8;
-
-
--- Dumping structure for table acore_world.spell_proc_event
-DROP TABLE IF EXISTS `spell_proc_event`;
-CREATE TABLE IF NOT EXISTS `spell_proc_event` (
-  `entry` mediumint(8) NOT NULL DEFAULT '0',
-  `SchoolMask` tinyint(4) NOT NULL DEFAULT '0',
+  `SpellId` int(11) NOT NULL DEFAULT '0',
+  `SchoolMask` tinyint(3) unsigned NOT NULL DEFAULT '0',
   `SpellFamilyName` smallint(5) unsigned NOT NULL DEFAULT '0',
   `SpellFamilyMask0` int(10) unsigned NOT NULL DEFAULT '0',
   `SpellFamilyMask1` int(10) unsigned NOT NULL DEFAULT '0',
   `SpellFamilyMask2` int(10) unsigned NOT NULL DEFAULT '0',
-  `procFlags` int(10) unsigned NOT NULL DEFAULT '0',
-  `procEx` int(10) unsigned NOT NULL DEFAULT '0',
-  `ppmRate` float NOT NULL DEFAULT '0',
-  `CustomChance` float NOT NULL DEFAULT '0',
+  `ProcFlags` int(10) unsigned NOT NULL DEFAULT '0',
+  `SpellTypeMask` int(10) unsigned NOT NULL DEFAULT '0',
+  `SpellPhaseMask` int(10) unsigned NOT NULL DEFAULT '0',
+  `HitMask` int(10) unsigned NOT NULL DEFAULT '0',
+  `AttributesMask` int(10) unsigned NOT NULL DEFAULT '0',
+  `ProcsPerMinute` float NOT NULL DEFAULT '0',
+  `Chance` float NOT NULL DEFAULT '0',
   `Cooldown` int(10) unsigned NOT NULL DEFAULT '0',
-  PRIMARY KEY (`entry`)
+  `Charges` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  PRIMARY KEY (`SpellId`)
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by Kitzunu** [comment]
I suppose this is the "new" proc system from Ariel-

- We can handle with procs using DB now
- spell_proc_event table is useless now, replaced by spell_proc (command .reload spell_proc_events will not work anymore, replaced by .reload spell_proc)
- Now we can control in wich phase of cast spell will proc (on cast, on hit, on finish, etc)
- Now drop charges will work, without stuck anymore.
- Now we can fix any issues related with procs

So this system would bring a lot of good, but also make some spells bug out and behave differently. Not to forget that there are a lot of commits to be ported over to make it work correctly.

**Comment by FrancescoBorzi** [comment]
yes, we only port things if we are 100% to not break anything

**Comment by Kitzunu** [comment]
Question is, is it worth breaking stuff for a more proper and "good" way to fix it later?

**Comment by FrancescoBorzi** [comment]
mmh it depends on this "later", ideally we should not break it. So we can have this work in a separate branch and merge it with master only once all the bugs are fixed

**Comment by Kitzunu** [comment]
The only problem there would be that nobody would test it since everyone uses the latest master, now fortunately for us is that my "old" server just imported this and is testing every spell in the game for upcoming bugs. 
However, the first part would be to import it, which would be a hell of a pain in itself :D
