### ISSUE TITLE
Warlocks are able to be refunded a soul shard for summoning a demon despite still having the demon summoned.

### ISSUE THREAD

**Issue by EternitysEnd** [azerothcore/azerothcore-wotlk#12058]
### Current Behaviour

You can summon a demon that consumes a soul shard (i.e. everything but the imp,) mount up on any mount, log out, log back in, and the soul shard will be back in your bags. Upon dismounting, the summoned demon will also appear to follow you again.

This can be observed here: https://youtu.be/cKSOPdGip1g (Recorded on the CC PTR)

### Expected Blizzlike Behaviour

In my testing, the demon did not leave your side when mounting up. Don't know if this was changed in Wrath or what, but it's worth pointing out. Regardless, upon logging back in, I did not have the soul shard back in my bags, but I did still have the voidwalker summoned.

This can be observed here: https://youtu.be/REkB2txojwQ (Recorded on Live TBC Classic)

### Source

World of Warcraft®: The Burning Crusade® Classic®

### Steps to reproduce the problem

1. Create a warlock character
2. Use .additem 6265 3, .learn 697, and .learn 5784
3. Summon the voidwalker
4. Mount your felsteed
5. Log out and back in
6. Observe the shard back in your bags
7. Dismount the steed
8. Observe the demon still summoned

### Extra Notes

Additional issue: Relogging back into the game after said issue, dismounting, remounting. You would gain additional Soul Shards. The process is repeatable.

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@c0ab2ab

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
[lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Luckdemon** [comment]
https://github.com/chromiecraft/chromiecraft/issues/3607
Just linking and confirming these issues, definitely generates extra soul shards without despawning the minion.

To add, to chain this ability to generate soul shards, when you log in mounted you have to dismount and re-mount to be able to generate another soul shard.

**Comment by mpfans** [comment]
@EternitysEnd please tested it
