### ISSUE TITLE
Can't finish the quest 'Kaw the Mammoth Destroyer'

### ISSUE THREAD

**Issue by t375152973** [azerothcore/azerothcore-wotlk#12054]
### Current Behaviour

Can't finished quest 'Kaw the Mammoth Destroyer'.
He mounted on his mount,but when i kill the mount ,he just became unharmabled and run to his appeared location.
I can't kill him to get the quest object.

### Expected Blizzlike Behaviour

He mounted on his mount,but when i kill the mount.Then i will kill him to get the quest object droped to the groud.

### Steps to reproduce the problem

1.get quest 'Kaw the Mammoth Destroyer' on Borean Tundra.
2.get to the place where Kaw stayed.
3.mount on Emaciated Mammoth Bull and kill Moria/Kaw

### AC rev. hash/commit

AzerothCore rev. 14d933eddc57+ 2022-06-04 09:33:50 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.79.0
Using MySQL version: 50738
Using CMake version: 3.23.2
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Data/maps. Total size: 291014339 bytes
vmaps directory located in C:/Data/vmaps. Total size: 658130553 bytes
mmaps directory located in C:/Data/mmaps. Total size: 2107917800 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows Server 2020

**Comment by DorizarN** [comment]
Bumping this up since Kaw still resets after you've killed the mammoth Moria.

**Comment by EricksOliveira** [comment]
same mistake with me.

**Comment by 0xCiBeR** [comment]
This is still an issue on latest build

**Comment by Ligthsx** [comment]
This error continues in the last rev of November 2023
