### ISSUE TITLE
Creature random target chooses pets and totems

### ISSUE THREAD

**Issue by noisiver** [azerothcore/azerothcore-wotlk#12068]
### Current Behaviour

The SmartAI target type `SMART_TARGET_HOSTILE_RANDOM`, and possibly `SMART_TARGET_HOSTILE_RANDOM_NOT_TOP`, has a chance of targeting Shaman Totems and warlock and hunter pets. ~The same can be said for some random target c++ functions~.

### Expected Blizzlike Behaviour

Creatures shouldn't target shaman totems, or player pets, when selecting a random target.

### Steps to reproduce the problem

**SmartAI**
1. Create a shaman and set its level to 80
2. Learn the totems spells and grab all totem items so that you can cast totems
3. Teleport to Utgarde Pinnacle (.tele utgardepinnacle) and enter the instance
4. Kill the first set of creatures inside the instance until you can access the first **Scourge Hulk**
5. Cast **Call of the Elements**
6. Engage the **Scourge Hulk** but don't kill it
7. Look out for all the times Volatile Infection is cast and who it targets

**Boss AI**
~1. Create a warlock and set its level to 80 and create another character of any class
2. Summon any pet as the warlock
3. Teleport to Utgarde Pinnacle (.tele utgardepinnacle)
4. Go through the instance until you reach **Svala Sorrowgrave**
5. With both characters nearby, engage the boss
6. Fight her until she uses performs her sacrifice player event with the sword coming down from above
7. Repeat the boss until she teleports the warlock pet as the player sacrifice~

### Extra Notes

~The Svala Sorrowgrave issue is not frequent enough when playing with a full group, it has only happened once in four runs of the instance with a full group where she grabbed the warlocks Felhunter and tried to sacrifice it. The second character being there with the warlock is to make sure there aren't any issues because there's only one character available aside from the pet.~

The Scourge Hulk example can be seen here : https://youtu.be/SKAOKre57rc

### AC rev. hash/commit

84295280c3fe16e337276c17511b2d1db1df3962

### Operating system

Debian 11 x64

### Custom changes or Modules

Eluna

**Comment by Nyeriah** [comment]
I'm not entirely sure but I think there's a playerOnly option in SAI. There is one in C++ for those cases

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12069

**Comment by tkn963** [comment]
> I'm not entirely sure but I think there's a playerOnly option in SAI. There is one in C++ for those cases

I don't think there is. There's random hostile and variantions of that like not top threat hostile etc but nothing that says players only.

**Comment by temperrr** [comment]
we need to be able to sent a parameter with it to be able to do that, it just selects a random UNIT from threat list atm.

**Comment by tkn963** [comment]
> 

I noticed that if you set `target_param1` to 1 it'll only target players. For some reason this isn't shown on the wiki. The question is if it should be true for all entries of `target_type` 5 (SMART_TARGET_HOSTILE_RANDOM)? If it is in fact supposed to, I could create a PR updating all those rows, unless it's easier to set it to true in the core.

**Comment by Nyeriah** [comment]
I think that is definitely not the same as some abilities should target pets, hunter soloing would be extremely broken otherwise, as you can send the pet and not engage and mobs won't do anything

**Comment by tkn963** [comment]
> I think that is definitely not the same for every creature as some abilities should target pets, hunter soloing would be extremely broken otherwise, as you can send the pet and not engage and mobs won't do anything

I realized. It's not the way of fixing it. It should ignore totems at all costs but not other pets. It stopped working anyway, for whatever reason. I'm trying to figure out how to update the core to fix this but I can't figure it out.

**Comment by tkn963** [comment]
![image](https://user-images.githubusercontent.com/5157047/174854806-d324ae2e-f7ad-40cc-9893-dedbf5bd76c7.png)
This seem to work fine but the question is if it's efficient and good enough but be accepted by AC.

**Comment by Nyeriah** [comment]
Are we sure totems are never valid random targets? wasn't there a tank totem or something? stoneclaw? or was that added on a later expansion?

**Comment by tkn963** [comment]
> 

Oh god, there is. I totally forgot. Damn, I thought I found the solution. Although I can't imagine it would be targeted by a random ability - but as always I could be wrong. My change wouldn't affect the threat itself, the totem can still pull aggro and be killed either way.

**Comment by tkn963** [comment]
I wanted to update this issue with some information I found.

https://vanilla-wow-archive.fandom.com/wiki/Shaman_totem

```
Totems are immune to AoEs and DoTs, and must be specifically attacked to be destroyed.
```

I don't think random target spells are supposed to target the totems regardless of which type of totem it is.

**Comment by UltraNix** [comment]
Already resolved and fixed.
