### ISSUE TITLE
Fear movement can cause player to clip out-of-bounds

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12079]
https://github.com/chromiecraft/chromiecraft/issues/3606

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Victims of fear effects sometimes glitch out of bounds. I noticed this happening in Arathi Basin in Lumber Mill where victims of Fear effects glitch under the map. In Warsong Gultch, in Alliance base on the path to roof, feared players sometimes run through the wall behind the table.

### Expected Blizzlike Behaviour

Fear should not make you glitch out of bounds.

### Steps to reproduce the problem

1. Queue Arathi Basin
2. Go to Lumber Mill
3. Fear enemy player
4. Enemy player sometimes falls through the map

Triager:
This spot seemed to reproduce this problem fairly often: `.go xyz 805.342651 -4412.438477 40.045872 1 4.757246`

### Extra Notes

Player glitched behind wall after having warlock [Fear] used on them. Screenshot taken from live server.

![WoWScrnShot_061222_131243](https://user-images.githubusercontent.com/94015041/173233273-2c5fb4bf-75c3-48bd-b3d5-1e3442ef7d3b.jpg)

Thanks to minthes and Syn for providing video evidence!

On the PTR realm with commit https://github.com/azerothcore/azerothcore-wotlk/commit/6ffb8aae6eaf

https://user-images.githubusercontent.com/22718174/174215893-040b0641-9183-4ea0-b894-8c070d4f55f3.mp4

https://user-images.githubusercontent.com/22718174/174216261-e84580be-7f6d-445d-a83b-e6d1407de416.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by r0m1ntik** [comment]
confirm
