### ISSUE TITLE
 azerothcore-wotlk failed to build on MSVC

### ISSUE THREAD

**Issue by Apriltanq** [azerothcore/azerothcore-wotlk#12073]
### Current Behaviour

Hi, all
Azerothcore_wotlk fails to build on MSVC. Could you help look?

### Expected Blizzlike Behaviour

For Azerothcore_wotlk should be run pass on the windows.

### Steps to reproduce the problem

1. git clone https://github.com/azerothcore/azerothcore-wotlk F:\gitP\azerothcore\azerothcore-wotlk
2. cd F:\gitP\azerothcore\azerothcore-wotlk
3. set _CL_=%_CL_% /D_HAS_DEPRECATED_RESULT_OF=1
4. mkdir build_x86 
5. cd F:\gitP\azerothcore\azerothcore-wotlk\build_x86 
6. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DTOOLS=ON -DBUILD_TESTING=ON .. 2>&1
7. msbuild /m /p:Platform=Win32 /p:Configuration=Release AzerothCore.sln /t:Rebuild 2>&1

### AC rev. hash/commit

None

### Operating system

Windows 10 x64

### Custom changes or Modules
[build.log](https://github.com/azerothcore/azerothcore-wotlk/files/8925028/build.log)

Error Massage
error C2059: syntax error: ')' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2952:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Random.h(72,34): error C2334: unexpected token(s) preceding ':'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2956:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Random.h(77,2): error C2143: syntax error: missing ')' before ';' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2957:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Random.h(77,2): error C2059: syntax error: ')' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2958:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Random.h(77,2): error C2238: unexpected token(s) preceding ';' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2959:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Containers.h(30,1): error C2059: syntax error: 'namespace' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2960:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Containers.h(31,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2961:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Containers.h(76,1): error C2059: syntax error: 'namespace' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2962:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Containers.h(76,18): error C2039: 'Containers': is not a member of 'Acore' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2964:     47>F:\gitP\azerothcore\azerothcore-wotlk\src\common\Utilities\Containers.h(77,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2965:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\list(24,1): error C2059: syntax error: 'namespace' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2966:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\list(24,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2967:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xnode_handle.h(23,1): error C2059: syntax error: 'namespace' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2968:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xnode_handle.h(23,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2969:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xtree(24,1): error C2059: syntax error: 'namespace' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2970:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\xtree(24,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2971:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\map(25,1): error C2059: syntax error: 'namespace' [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]
	Line 2972:     47>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\map(25,1): error C2334: unexpected token(s) preceding '{'; skipping apparent function body [F:\gitP\azerothcore\azerothcore-wotlk\build_x86\src\test\unit_tests.vcxproj]

**Comment by Apriltanq** [comment]
> 
Azerothcore_wotlk commit: 36f0a7757bde9573262f298aa1eaf6765af8295e

**Comment by Apriltanq** [comment]
@Kitzunu We have used the latest VS version to test, when you update VS to the latest version, you will see the same problem, but now you cannot.

**Comment by Kitzunu** [comment]
Use vs 22 then
