### ISSUE TITLE
[ZG] Hazza'rah Illusion - Should be immune to AOE

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12084]
### Current Behaviour

You can AoE illusions

### Expected Blizzlike Behaviour

Immune to AoE

### Source

https://phoenix-remulos.net/zg.html#madness

https://youtu.be/TgMwr_HkmAU?t=120

### Steps to reproduce the problem

1. Summon Haza'rah

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4bc99f8070cf8f38452e18585a0ff668478a8510

### Operating system

Windows 11

**Comment by Gultask** [comment]
Good catch I missed that one. And it's pretty important too. :)
