### ISSUE TITLE
[ZG] Gri'lek focus when grow'up

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12088]
### Current Behaviour

When grow'up focus the same target and announce it.

### Expected Blizzlike Behaviour

When he grow up, he should target and announce the random player target. This player will need to chase him. 
When go back, he return on the highest threat.

### Source

https://phoenix-remulos.net/zg.html#madness

https://wowwiki-archive.fandom.com/wiki/Gri%27lek_(original)

### Steps to reproduce the problem

If the Summoning Event is implemented:
.event stop 28
.event stop 29
.event stop 30
.event start 27
.additem 19931
.go xyz -11905 -1911 66 309
use the brazier and engage Gri'lek

else:
.go xyz -11905 -1911 66 309
.npc add temp 15082

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4bc99f8070cf8f38452e18585a0ff668478a8510

### Operating system

Windows 11

**Comment by Gultask** [comment]
I remembered seeing something about that. Found it again.

>Note as of [patch 1.10.2](https://wowpedia.fandom.com/wiki/Patch_1.10.2), he will not fixate on a single target while enraged. Recommendation is to play pingpong with him. ([source](https://wowpedia.fandom.com/wiki/Gri'lek_(Classic)))

Undocumented change, so ehh...
