### ISSUE TITLE
[ZG] Hight Prietess Jeklik - Start imrovement

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12081]
### Current Behaviour

She can start the combat during the event animation when engage

### Expected Blizzlike Behaviour

She should done totaly this animation before to go on a player et start the combat.

### Source

https://youtu.be/4xRYhc66vXk

### Steps to reproduce the problem

1. Engage the combat with jeklik

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4bc99f8070cf8f38452e18585a0ff668478a8510

### Operating system

Windows 11

**Comment by Gultask** [comment]
More problems on pull: https://github.com/chromiecraft/chromiecraft/issues/3623
If you pull without dealing damage (miss) she will not transform and will instead just swim through the air.
