### ISSUE TITLE
Installation fails during import of SQL.

### ISSUE THREAD

**Issue by nathanradavies** [azerothcore/azerothcore-wotlk#12097]
### Current Behaviour

During first launch on Docker, the command ```./acore.sh docker start:app``` fails with the following error:
```
ac-worldserver_1         | ERROR 1060 (42S21) at line 3: Duplicate column name 'artkit0'
ac-worldserver_1         |
ac-worldserver_1         | Applying of file '/azerothcore/data/sql/updates/db_world/2022_06_14_01.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
ac-worldserver_1         | Could not update the World database, see log for details.
```

### Expected Blizzlike Behaviour

Server should start

### Steps to reproduce the problem

1. Follow steps on "Install with Docker" page here: https://www.azerothcore.org/wiki/install-with-docker#install-with-docker
2. Reach Step 3: Run the containers

### Extra Notes

A fix has been proposed in Discord by user ```Vale the Violet Mote```
"I'm just going to comment out these lines
```
ALTER TABLE `gameobject_template_addon`
    ADD COLUMN `artkit0` INT NOT NULL DEFAULT 0 AFTER `maxgold`,
    ADD COLUMN `artkit1` INT NOT NULL DEFAULT 0 AFTER `artkit0`,
    ADD COLUMN `artkit2` INT NOT NULL DEFAULT 0 AFTER `artkit1`,
    ADD COLUMN `artkit3` INT NOT NULL DEFAULT 0 AFTER `artkit2`;
```
no point to them since they already exist"

### AC rev. hash/commit

2cde0c35ba52ac9ca9b2db167d3f20f46db0ca9c

### Operating system

Windows 11 running Docker version 20.10.16, build aa7e414

### Custom changes or Modules

None

**Comment by Kitzunu** [comment]
Cannot reproduce on windows and all CIs passing

**Comment by Knaspin** [comment]
Can also confirm this on my Docker setup after upgrading from an existing database (from https://github.com/azerothcore/azerothcore-wotlk/commit/2bef6b497d24) to newly compilef one (from https://github.com/azerothcore/azerothcore-wotlk/commit/2db5f9a231be84092ea9eb2122a4f78ddd28652f).


Error:

```
Updating World database...
>> Applying update "2022_06_14_01.sql" '90B07D9'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1060 (42S21) at line 3: Duplicate column name 'artkit0'

Applying of file '/azerothcore/data/sql/updates/db_world/2022_06_14_01.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.
Closing down DatabasePool 'acore_world'.
Asynchronous connections on DatabasePool 'acore_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_world' closed.
Closing down DatabasePool 'acore_characters'.
Asynchronous connections on DatabasePool 'acore_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_characters' closed.
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.
```

**Comment by GwendolineFct** [comment]
Same problem with building/running from commit 61c64bbf3049d1548c55f56dc872ab03f073904f on debian 10 

importing WORLD - updates ...
ERROR 1060 (42S21) at line 2972: Duplicate column name 'artkit0'

**Comment by CrisisModel** [comment]
I am also having the same issue from commit 73bd2b4 on Arch with Docker.
```
azerothcore-wotlk-ac-worldserver-1  | ERROR 1060 (42S21) at line 3: Duplicate column name 'artkit0'
azerothcore-wotlk-ac-worldserver-1  | 
azerothcore-wotlk-ac-worldserver-1  | Applying of file '/azerothcore/data/sql/updates/db_world/2022_06_14_01.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
azerothcore-wotlk-ac-worldserver-1  | Could not update the World database, see log for details.
azerothcore-wotlk-ac-worldserver-1  | Closing down DatabasePool 'acore_world'.
```

**Comment by Kitzunu** [comment]
Haven't checked github in a while, saw this now.

It's very odd that you are experiencing this as artkit0 only exists once (1) in the entire directory. But we will squash the db in the coming days so I will leave it open until then.

**Comment by nathanradavies** [comment]
Thank you @Kitzunu and for all the work you and all the volunteers do on AC.

**Comment by benjymansy123** [comment]
> But we will squash the db in the coming days so I will leave it open until then.

Would it be possible to fit this in before that squash? :3 https://github.com/azerothcore/azerothcore-wotlk/issues/11005

**Comment by Jboonie** [comment]
Can confirm, running into the issue today on the latest pull.

**Comment by NexieJolt** [comment]
Newcomer here, I can't get the server to run even with some tweaks found on discord. Waiting for this fix so I can try this core out for the first time. :)

**Comment by Alex-Garay** [comment]
I can confirm this is still an issue and it happens with a few other updates, not just the Akit0 column.

**Comment by dustxdustx** [comment]
These BUGs in sql are  petrified.

**Comment by dustxdustx** [comment]
Unfortuely ,This bug has be ingored for long time.

**Comment by benjymansy123** [comment]
> Unfortuely ,This bug has be ingored for long time.

It's not that the bug is being ignored, it's just that the solution hasn't happened yet.

**Comment by dustxdustx** [comment]
unfortunately,How  make the developer notice this bug?  I can't update my database for three months.....

**Comment by fegger-ducksify** [comment]
There is a PR for that waiting for approval #12419

**Comment by Kitzunu** [comment]
update to latest and it should work
