### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ShinDarth** [azerothcore/azerothcore-wotlk#121]
We should solve all warnings:

https://travis-ci.org/azerothcore/azerothcore-wotlk
##

**Comment by Yehonal** [comment]
Working on this old issue

**Comment by Yehonal** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/3dde305068cad85aeee5b283bf46e2898c6f0a15

**Comment by Yehonal** [comment]
Done ;) since now before accept a PR / Make a commit, we must be sure that it doesn't generate any warnings using -DWITH_WARNING option in cmake

we can also check it via travis build logs

**Comment by ShinDarth** [comment]
@Yehonal good job, please edit the documentation accordingly with this new requirement.
