### ISSUE TITLE
Characters below level 10 should not be allowed to join a raid group

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12107]
### Current Behaviour

Any char can join a raid group

### Expected Blizzlike Behaviour

a char below level 10 cannot join a raid group

### Source

https://wowpedia.fandom.com/wiki/Patch_3.3.0
![image](https://user-images.githubusercontent.com/20357406/174472458-a91b73e2-4773-4b69-b952-602c39fa1a40.png)

### Steps to reproduce the problem

1. make raid group with 2  level 10+
2. try inviting a level 10-

### AC rev. hash/commit

82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

ubuntu x64

**Comment by Kitzunu** [comment]
This Opcode handles raid convertion

https://github.com/azerothcore/azerothcore-wotlk/blob/82cfd1b8d4147f09564e692f13effc4142178d72/src/server/game/Handlers/GroupHandler.cpp#L612-L631

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12110 @temperrr
