### ISSUE TITLE
[Quest] Fire At Will!

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1210]
##### SMALL DESCRIPTION:
The quest [Fire At Will!](https://wowgaming.altervista.org/aowow/?quest=10911) in Blades Edge Mountains is very buggy. Cannons follow the player, imps do not move, and cannon attacks player when dismissed despite not being target-able. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- [Death's Door Fel Cannon](https://wowgaming.altervista.org/aowow/?npc=22443) should never move.
- [Unstable Fel-Imp](https://wowgaming.altervista.org/aowow/?npc=22474) should move toward the player/cannon.
- [Death's Door Fel Cannon](https://wowgaming.altervista.org/aowow/?npc=22443) should not attack player when no longer being controlled.
[Quest Video](https://www.youtube.com/watch?v=6_AOkxleLS0)

##### CURRENT BEHAVIOUR:
- [Death's Door Fel Cannon](https://wowgaming.altervista.org/aowow/?npc=22443) follows the player around like a pet when controlled. 
- [Unstable Fel-Imps](https://wowgaming.altervista.org/aowow/?npc=22474) that spawn during event don't move unless the player moves into their aggro range.
- When dismissing the [Fel Cannon](https://wowgaming.altervista.org/aowow/?npc=22443), it begins attacking the player, but cannot be targeted - forcing the player to run away and drop threat. 

##### STEPS TO REPRODUCE THE PROBLEM:
1.  `.quest add 10911`
2.  `.go xyz 2245, 5481, 154, 530`
3.  Use quest item near Fel Cannon to control it.
4.  Move around to see cannon follow you.
5.  Use cannon ability "Artillery on the Warp-Gate" to shoot nearby gate.
6.  Spawned Imps only attack when in aggro range
7.  Dismiss cannon (right click unit frame -> dismiss) to see it attack you.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
0e16853157cff17dcd59aac490fbd5db3da0b727

##### OPERATING SYSTEM:
Windows 10

**Comment by wetbrownsauce** [comment]
Looks like this issue is still open on TC as well. There has been some preliminary work in the comments on the SAI but still needs work. 

[Trinitycore Quest Fire At Will](https://github.com/TrinityCore/TrinityCore/issues/6828)

**Comment by grimgravy** [comment]
will soon be available
