### ISSUE TITLE
Sen'jin Fetish missing alternate model ids

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1211]
##### SMALL DESCRIPTION:
The companion [Sen'jin Fetish](https://wowgaming.altervista.org/aowow/?spell=63712) should have 3 different model ids, choosing one at random when summoned. It currently only has one.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
According to [Warcraft Pets](https://www.warcraftpets.com/wow-pets/undead/voodoo-companions/senjin-fetish/):
>When summoned, this pet will randomly appear using one of three different models

- [Youtube Video Proof](https://www.youtube.com/watch?v=cDVyQxWHD7k)
- [See Also](https://wow.zamimg.com/uploads/screenshots/normal/123316-senjin-fetish.jpg)

The pet should also float above the ground.

##### CURRENT BEHAVIOUR:
Currently only one model is used, pet summons in the air but then falls to the ground. It may also be too large in-game. 

##### STEPS TO REPRODUCE THE PROBLEM:
1.  `.additem 45606`
2.  Summon the pet multiple times.
3.  Only one model every time.

Note: until PR #1208 is merged, 50% of the time there will be no model when summoned. 

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
0e16853157cff17dcd59aac490fbd5db3da0b727

##### OPERATING SYSTEM:
Windows 10

**Comment by poszer** [comment]
Missing models in database. Will try to find ID's for them, so we can close this
