### ISSUE TITLE
ZG: Missing waypoints/Spawns

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12124]
### Current Behaviour

Several areas in ZG do not have patrolling creatures.
![image](https://user-images.githubusercontent.com/20357406/174572627-ce01f19d-35ce-4e02-b100-65e316da86fb.png)
![image](https://user-images.githubusercontent.com/20357406/174572657-fafcdfef-2f39-4608-ab4f-9e29bbbc97ff.png)

### Expected Blizzlike Behaviour

There should be patrols

### Steps to reproduce the problem

1. Go to zulgurub on the coloured areas
2. notice lack of patrols.

### AC rev. hash/commit

713cddc1ba534cd29b5d62c3f2fb4ed2626003c9

### Operating system

Manjaro x64

**Comment by neifion-00000000** [comment]
@Nefertumm @temperrr 

As I sort threw the packets I'll post at least 50 patrols waypoints here it looks like.  I will check to make sure these aren't unnecessary but it looks like all the patrols are "made up" so far so it'll be good to have the real ones, plus the first one was very troublesome--off the get the first patrol I checked was in a formation with a mob that was supposed to be standing around in another pack.

https://www.youtube.com/watch?v=j6h-3olj2KU&list=PLSfgJrfivjI7CWVQUrrEZxjm8x3SgRfDn  Will eventually be a playlist of all the patrols once youtube allows it.


(1) Serpent pack (Entrance)
Notes:  Currently in AC/CC PTR this pack is using incorrect coordinates as well as formations have a mob that doesn't belong to it as part of its pack.  The mob placement in this area might be worth looking at honestly.
When witnessed this was a 2x Razzashi Serpent pack.

-- Pathing for  Entry: 11371
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-11874.843,`position_y`=-1325.8516,`position_z`=78.68711 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-11874.843,-1325.8516,78.68711,0,0,0,0,100,0),
(@PATH,2,-11888.364,-1338.8317,74.93052,0,0,0,0,100,0),
(@PATH,3,-11904.724,-1344.1305,75.75995,0,0,0,0,100,0),
(@PATH,4,-11905.38,-1360.0092,70.85077,0,0,0,0,100,0),
(@PATH,5,-11901.88,-1377.7013,68.11927,0,0,0,0,100,0),
(@PATH,6,-11884.866,-1380.3492,66.02857,0,0,0,0,100,0),
(@PATH,7,-11880.479,-1399.4225,62.97413,0,0,0,0,100,0),
(@PATH,8,-11878.038,-1407.888,62.201817,0,0,0,0,100,0),
(@PATH,9,-11894.919,-1416.4415,57.01041,0,0,0,0,100,0),
(@PATH,10,-11921.158,-1428.7435,46.9667,0,0,0,0,100,0),
(@PATH,11,-11894.919,-1416.4415,57.01041,0,0,0,0,100,0),
(@PATH,12,-11878.038,-1407.888,62.201817,0,0,0,0,100,0),
(@PATH,13,-11880.479,-1399.4225,62.97413,0,0,0,0,100,0),
(@PATH,14,-11884.866,-1380.3492,66.02857,0,0,0,0,100,0),
(@PATH,15,-11901.88,-1377.7013,68.11927,0,0,0,0,100,0),
(@PATH,16,-11905.361,-1360.0527,70.93378,0,0,0,0,100,0),
(@PATH,17,-11904.724,-1344.1305,75.75995,0,0,0,0,100,0),
(@PATH,18,-11888.364,-1338.8317,74.93052,0,0,0,0,100,0),
(@PATH,19,-11874.843,-1325.8516,78.68711,0,0,0,0,100,0),
(@PATH,20,-11863.753,-1313.4701,78.72681,0,0,0,0,100,0);
-- 0x204CB026A00B1AC000050900003094B0 .go xyz -11874.843 -1325.8516 78.68711





(2) Gurubashi Berserker otw to bats
Note:  Currently in AC/CC PTR this pack is using incorrect coordinates, though the general path is fine.

-- Pathing for  Entry: 11352
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-11966.846,`position_y`=-1528.8047,`position_z`=41.97195 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-11966.846,-1528.8047,41.97195,0,0,0,0,100,0),
(@PATH,2,-11999.917,-1520.9025,58.9844,0,0,0,0,100,0),
(@PATH,3,-12023.279,-1518.9547,72.43448,0,0,0,0,100,0),
(@PATH,4,-12028.042,-1500.1376,77.62198,0,0,0,0,100,0),
(@PATH,5,-12029.563,-1488.6721,79.530396,0,0,0,0,100,0),
(@PATH,6,-12033.312,-1478.7206,80.10852,0,0,0,0,100,0),
(@PATH,7,-12066.744,-1478.9442,101.670784,0,0,0,0,100,0),
(@PATH,8,-12100.744,-1478.7441,128.72264,0,0,0,0,100,0),
(@PATH,9,-12066.744,-1478.9442,101.670784,0,0,0,0,100,0),
(@PATH,10,-12033.312,-1478.7206,80.10852,0,0,0,0,100,0),
(@PATH,11,-12029.563,-1488.6721,79.530396,0,0,0,0,100,0),
(@PATH,12,-12028.042,-1500.1376,77.62198,0,0,0,0,100,0),
(@PATH,13,-12023.279,-1518.9547,72.43448,0,0,0,0,100,0),
(@PATH,14,-11999.917,-1520.9025,58.9844,0,0,0,0,100,0);
-- 0x204CB026A00B160000050900003094AF .go xyz -11966.846 -1528.8047 41.97195

**Comment by neifion-00000000** [comment]
(3) Bridge Entrance Patrol
Note:  Currently very wrong coordinates.

-- Pathing for  Entry: 11350
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-11915.182,`position_y`=-1309.0254,`position_z`=77.85016 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-11915.182,-1309.0254,77.85016,0,0,0,0,100,0),
(@PATH,2,-11900.22,-1322.3068,77.35016,0,0,0,0,100,0),
(@PATH,3,-11891.567,-1333.3414,75.761086,0,0,0,0,100,0),
(@PATH,4,-11883.896,-1344.9625,74.07407,0,0,0,0,100,0),
(@PATH,5,-11884.932,-1366.6774,69.18043,0,0,0,0,100,0),
(@PATH,6,-11881.251,-1392.7772,64.10792,0,0,0,0,100,0),
(@PATH,7,-11884.669,-1407.5942,61.118076,0,0,0,0,100,0),
(@PATH,8,-11898.967,-1416.9801,55.54923,0,0,0,0,100,0),
(@PATH,9,-11914.943,-1429.737,46.979885,0,0,0,0,100,0),
(@PATH,10,-11920.759,-1446.3221,42.852036,0,0,0,0,100,0),
(@PATH,11,-11927.813,-1477.2751,32.164944,0,0,0,0,100,0),
(@PATH,12,-11938.073,-1520.2743,42.869736,0,0,0,0,100,0),
(@PATH,13,-11940.487,-1533.6138,39.66779,0,0,0,0,100,0),
(@PATH,14,-11947.255,-1542.4147,39.66779,0,0,0,0,100,0),
(@PATH,15,-11943.104,-1557.1871,39.79279,0,0,0,0,100,0),
(@PATH,16,-11943.644,-1566.9681,41.143223,0,0,0,0,100,0),
(@PATH,17,-11945.308,-1590.3102,36.837807,0,0,0,0,100,0),
(@PATH,18,-11947.825,-1619.8463,41.207428,0,0,0,0,100,0),
(@PATH,19,-11951.434,-1633.3173,38.97269,0,0,0,0,100,0),
(@PATH,20,-11968.02,-1647.7539,35.483604,0,0,0,0,100,0),
(@PATH,21,-12000.128,-1644.0223,34.706413,0,0,0,0,100,0),
(@PATH,22,-12025.215,-1640.9318,38.757927,0,0,0,0,100,0),
(@PATH,23,-12041.77,-1650.1912,40.77353,0,0,0,0,100,0),
(@PATH,24,-12059.076,-1670.9088,42.50792,0,0,0,0,100,0),
(@PATH,25,-12060.682,-1706.4213,45.026535,0,0,0,0,100,0),
(@PATH,26,-12047.378,-1730.9137,50.612717,0,0,0,0,100,0),
(@PATH,27,-12060.682,-1706.4213,45.026535,0,0,0,0,100,0),
(@PATH,28,-12059.076,-1670.9088,42.50792,0,0,0,0,100,0),
(@PATH,29,-12041.77,-1650.1912,40.77353,0,0,0,0,100,0),
(@PATH,30,-12025.215,-1640.9318,38.757927,0,0,0,0,100,0),
(@PATH,31,-12000.128,-1644.0223,34.706413,0,0,0,0,100,0),
(@PATH,32,-11968.145,-1647.8522,35.503624,0,0,0,0,100,0),
(@PATH,33,-11951.559,-1633.4141,38.973248,0,0,0,0,100,0),
(@PATH,34,-11947.825,-1619.8463,41.207428,0,0,0,0,100,0),
(@PATH,35,-11945.308,-1590.3102,36.837807,0,0,0,0,100,0),
(@PATH,36,-11943.644,-1566.9681,41.143223,0,0,0,0,100,0),
(@PATH,37,-11943.104,-1557.1871,39.79279,0,0,0,0,100,0),
(@PATH,38,-11947.255,-1542.4147,39.66779,0,0,0,0,100,0),
(@PATH,39,-11940.487,-1533.6138,39.66779,0,0,0,0,100,0),
(@PATH,40,-11938.073,-1520.2743,42.869736,0,0,0,0,100,0),
(@PATH,41,-11927.813,-1477.2751,32.164944,0,0,0,0,100,0),
(@PATH,42,-11920.759,-1446.3221,42.852036,0,0,0,0,100,0),
(@PATH,43,-11914.943,-1429.737,46.979885,0,0,0,0,100,0),
(@PATH,44,-11898.967,-1416.9801,55.54923,0,0,0,0,100,0),
(@PATH,45,-11884.669,-1407.5942,61.118076,0,0,0,0,100,0),
(@PATH,46,-11881.251,-1392.7772,64.10792,0,0,0,0,100,0),
(@PATH,47,-11884.932,-1366.6774,69.18043,0,0,0,0,100,0),
(@PATH,48,-11883.896,-1344.9625,74.07407,0,0,0,0,100,0),
(@PATH,49,-11891.567,-1333.3414,75.761086,0,0,0,0,100,0),
(@PATH,50,-11900.22,-1322.3068,77.35016,0,0,0,0,100,0);
-- 0x204CB026A00B15800005100000309A03 .go xyz -11915.182 -1309.0254 77.85016

**Comment by neifion-00000000** [comment]
(4) Bat boss room-- 1 bat patrol in back (to your right on entering area) ( https://youtu.be/j6h-3olj2KU?t=1383 - https://youtu.be/j6h-3olj2KU?t=1410 )
Note:  This pack is a mess.

-- Pathing for  Entry: 11368
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-12051.524,`position_y`=-1427.2681,`position_z`=130.14175 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-12051.524,-1427.2681,130.14175,0,0,0,0,100,0),
(@PATH,2,-12056.444,-1439.4609,130.26523,0,0,0,0,100,0),
(@PATH,3,-12064.653,-1446.329,130.2684,0,0,0,0,100,0),
(@PATH,4,-12076.898,-1450.6375,130.39133,0,0,0,0,100,0),
(@PATH,5,-12088.711,-1450.2057,130.85104,0,0,0,0,100,0),
(@PATH,6,-12064.653,-1446.329,130.2684,0,0,0,0,100,0),
(@PATH,7,-12056.444,-1439.4609,130.26523,0,0,0,0,100,0);
-- 0x204CB026A00B1A000005100009309A02 .go xyz -12051.524 -1427.2681 130.14175



(5)	1 circle bat patrol en route ( https://youtu.be/j6h-3olj2KU?t=1414 - https://youtu.be/j6h-3olj2KU?t=1434 )
Note: idk where this one is currently... since this area is 100% patroling mobs, it might not be a bad idea to just reconstruct this whole area based on the patrols

-- Pathing for  Entry: 11368
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-12139.658,`position_y`=-1462.6881,`position_z`=130.72519 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-12139.658,-1462.6881,130.72519,0,0,0,0,100,0),
(@PATH,2,-12145.165,-1472.5826,130.72519,0,0,0,0,100,0),
(@PATH,3,-12150.585,-1480.6031,130.72519,0,0,0,0,100,0),
(@PATH,4,-12155.898,-1487.2714,130.88535,0,0,0,0,100,0),
(@PATH,5,-12162.413,-1488.4478,130.95273,0,0,0,0,100,0),
(@PATH,6,-12166.849,-1484.3025,130.72519,0,0,0,0,100,0),
(@PATH,7,-12169.933,-1475.3961,130.72519,0,0,0,0,100,0),
(@PATH,8,-12168.736,-1461.0402,130.72519,0,0,0,0,100,0),
(@PATH,9,-12165.8,-1451.5284,131.1915,0,0,0,0,100,0),
(@PATH,10,-12159.837,-1446.8896,131.52573,0,0,0,0,100,0),
(@PATH,11,-12154.368,-1448.3627,131.15585,0,0,0,0,100,0),
(@PATH,12,-12148.044,-1460.6128,130.72519,0,0,0,0,100,0),
(@PATH,13,-12142.502,-1469.3756,130.72519,0,0,0,0,100,0),
(@PATH,14,-12139.423,-1477.193,130.72519,0,0,0,0,100,0),
(@PATH,15,-12142.655,-1487.7107,130.81308,0,0,0,0,100,0),
(@PATH,16,-12150.853,-1489.0536,131.22275,0,0,0,0,100,0),
(@PATH,17,-12157.748,-1478.774,130.72519,0,0,0,0,100,0),
(@PATH,18,-12158.351,-1465.1509,131.22519,0,0,0,0,100,0),
(@PATH,19,-12156.007,-1450.0975,130.72519,0,0,0,0,100,0),
(@PATH,20,-12153.582,-1446.1135,131.67294,0,0,0,0,100,0),
(@PATH,21,-12146.194,-1444.6774,132.9537,0,0,0,0,100,0),
(@PATH,22,-12139.783,-1452.6754,130.72519,0,0,0,0,100,0);
-- 0x204CB026A00B1A000005100007309A02 .go xyz -12139.658 -1462.6881 130.72519

(6)				1 complex bat patrol,

SoonTM gnite for now tho

(7) East Wall Front circle patrols in room 1/3 
-- Pathing for  Entry: 11368
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-12214.109,`position_y`=-1477.2382,`position_z`=130.93126 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-12214.109,-1477.2382,130.93126,0,0,0,0,100,0),
(@PATH,2,-12211.264,-1469.974,130.7252,0,0,0,0,100,0),
(@PATH,3,-12214.149,-1461.742,130.81232,0,0,0,0,100,0),
(@PATH,4,-12235.612,-1459.0533,130.7252,0,0,0,0,100,0),
(@PATH,5,-12255.216,-1470.7734,130.62447,0,0,0,0,100,0),
(@PATH,6,-12255.078,-1483.8112,130.62447,0,0,0,0,100,0),
(@PATH,7,-12246.08,-1488.4501,131.03218,0,0,0,0,100,0),
(@PATH,8,-12233.38,-1491.1652,133.18355,0,0,0,0,100,0),
(@PATH,9,-12222.606,-1482.8005,130.99913,0,0,0,0,100,0);
-- 0x204CB026A00B1A000005100004B09A02 .go xyz -12214.109 -1477.2382 130.93126

**Comment by temperrr** [comment]
@neifion-00000000 

Can you add the rest of them 1 comment per waypoint (or 2) :3

**Comment by neifion-00000000** [comment]
> @neifion-00000000
> 
> Can you add the rest of them 1 comment per creature (or 2) :3

Yup definitely.  

(12) Serpents across 2nd bridge

-- Pathing for  Entry: 11371
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-12057.339,`position_y`=-1734.9985,`position_z`=51.701015 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-12057.339,-1734.9985,51.701015,0,0,0,0,100,0),
(@PATH,2,-12064.325,-1723.6598,48.64299,0,0,0,0,100,0),
(@PATH,3,-12081.199,-1711.9126,50.009007,0,0,0,0,100,0),
(@PATH,4,-12083.754,-1694.3141,47.727253,0,0,0,0,100,0),
(@PATH,5,-12075.137,-1685.36,44.9919,0,0,0,0,100,0),
(@PATH,6,-12060.942,-1668.3538,42.789413,0,0,0,0,100,0),
(@PATH,7,-12053.68,-1652.7511,43.139984,0,0,0,0,100,0),
(@PATH,8,-12040.667,-1640.4402,40.75351,0,0,0,0,100,0),
(@PATH,9,-12023.091,-1633.9069,38.15856,0,0,0,0,100,0),
(@PATH,10,-12013.497,-1648.2031,37.284782,0,0,0,0,100,0),
(@PATH,11,-11993.206,-1638.6372,34.66549,0,0,0,0,100,0),
(@PATH,12,-11970.971,-1640.5399,35.773155,0,0,0,0,100,0),
(@PATH,13,-11952.981,-1647.8049,39.700054,0,0,0,0,100,0),
(@PATH,14,-11970.971,-1640.5399,35.773155,0,0,0,0,100,0),
(@PATH,15,-11993.206,-1638.6372,34.66549,0,0,0,0,100,0),
(@PATH,16,-12013.497,-1648.2031,37.284782,0,0,0,0,100,0),
(@PATH,17,-12023.091,-1633.9069,38.15856,0,0,0,0,100,0),
(@PATH,18,-12040.667,-1640.4402,40.75351,0,0,0,0,100,0),
(@PATH,19,-12053.68,-1652.7511,43.139984,0,0,0,0,100,0),
(@PATH,20,-12060.942,-1668.3538,42.789413,0,0,0,0,100,0),
(@PATH,21,-12075.137,-1685.36,44.9919,0,0,0,0,100,0),
(@PATH,22,-12083.754,-1694.3141,47.727253,0,0,0,0,100,0),
(@PATH,23,-12081.199,-1711.9126,50.009007,0,0,0,0,100,0),
(@PATH,24,-12064.325,-1723.6598,48.64299,0,0,0,0,100,0);
-- 0x204CB026A00B1AC00005100002309A02 .go xyz -12057.339 -1734.9985 51.701015

**Comment by neifion-00000000** [comment]
(15) Berserker from Zanzas Rise to the fast moving Tiger Cub spot

-- Pathing for  Entry: 11352
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-11977.521,`position_y`=-1753.175,`position_z`=52.679806 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-11977.521,-1753.175,52.679806,0,0,0,0,100,0),
(@PATH,2,-11954.122,-1805.8005,52.859722,0,0,0,0,100,0),
(@PATH,3,-11931.607,-1808.4896,51.387363,0,0,0,0,100,0),
(@PATH,4,-11901.063,-1811.8312,51.262363,0,0,0,0,100,0),
(@PATH,5,-11865.95,-1811.2943,51.134724,0,0,0,0,100,0),
(@PATH,6,-11831.555,-1812.5005,51.024055,0,0,0,0,100,0),
(@PATH,7,-11818.492,-1834.661,50.14477,0,0,0,0,100,0),
(@PATH,8,-11804.356,-1849.8798,47.525387,0,0,0,0,100,0),
(@PATH,9,-11818.492,-1834.661,50.14477,0,0,0,0,100,0),
(@PATH,10,-11831.555,-1812.5005,51.024055,0,0,0,0,100,0),
(@PATH,11,-11865.95,-1811.2943,51.134724,0,0,0,0,100,0),
(@PATH,12,-11901.063,-1811.8312,51.262363,0,0,0,0,100,0),
(@PATH,13,-11931.607,-1808.4896,51.387363,0,0,0,0,100,0),
(@PATH,14,-11954.122,-1805.8005,52.859722,0,0,0,0,100,0),
(@PATH,15,-11957.259,-1768.3782,53.47521,0,0,0,0,100,0);
-- 0x204CB026A00B16000005100000309A04 .go xyz -11977.521 -1753.175 52.679806

**Comment by neifion-00000000** [comment]
(16) Also that fast moving Tiger Cub

**Comment by neifion-00000000** [comment]
(17) 1 Berserker otw to spider boss

**Comment by neifion-00000000** [comment]
(21) 					Spider Packs 2/2

**Comment by neifion-00000000** [comment]
(22) Berserker starting on the far east of Zanza's Rise to Hakkari Grounds

**Comment by neifion-00000000** [comment]
(23) Two Priests Traveling Around (SAI needed prolly)

**Comment by neifion-00000000** [comment]
(24) Another Two Hakkari Wanderers (SAI needed prolly)

**Comment by neifion-00000000** [comment]
(25) Naze of Shirvallah Berserker

**Comment by neifion-00000000** [comment]
(26) Zulian Cub 1/2

**Comment by neifion-00000000** [comment]
(29) Two Serpent 2/2

**Comment by neifion-00000000** [comment]
(30) First Panther Patrol

**Comment by neifion-00000000** [comment]
(31) Temple of Bethekk Berserker

**Comment by neifion-00000000** [comment]
(32) Second Panther Patrol

**Comment by neifion-00000000** [comment]
(34) Gurubashi Patrol 1/2

**Comment by neifion-00000000** [comment]
(35) Razzashi Patrol

**Comment by neifion-00000000** [comment]
(37) Gurubashi Patrol 2/2

**Comment by neifion-00000000** [comment]
(38) Undead Patrol (SAI needed prolly)

**Comment by neifion-00000000** [comment]
(39) Imp Duo Patrol

**Comment by neifion-00000000** [comment]
(40) Imp Trio 1/3 Circle

**Comment by neifion-00000000** [comment]
(42) Imp Trio 3/3 Back and Forth

**Comment by neifion-00000000** [comment]
(43) Altar of the Blood Guard North Son of Hakkari

**Comment by neifion-00000000** [comment]
(46) Altar of the Blood Guard South Son of Hakkari

**Comment by neifion-00000000** [comment]
(49) South Bottom Soulflayer Pack

**Comment by neifion-00000000** [comment]
(50) North Bottom Soulflayer Pack

**Comment by neifion-00000000** [comment]
(51)  Oop I found one more Berserker ( circle https://www.youtube.com/watch?v=CamK8RRoDrc )
-- Pathing for  Entry: 11352
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-12304.316,`position_y`=-1828.3707,`position_z`=130.3816 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-12304.316,-1828.3707,130.3816,0,0,0,0,100,0),
(@PATH,2,-12316.513,-1835.5278,130.3816,0,0,0,0,100,0),
(@PATH,3,-12333.007,-1831.8125,130.3816,0,0,0,0,100,0),
(@PATH,4,-12302.664,-1882.1113,130.38538,0,0,0,0,100,0),
(@PATH,5,-12292.008,-1899.5505,130.28304,0,0,0,0,100,0),
(@PATH,6,-12277.654,-1913.2064,130.3583,0,0,0,0,100,0),
(@PATH,7,-12253.349,-1920.6671,130.39581,0,0,0,0,100,0),
(@PATH,8,-12232.099,-1935.3337,130.39581,0,0,0,0,100,0),
(@PATH,9,-12253.349,-1920.6671,130.39581,0,0,0,0,100,0),
(@PATH,10,-12277.654,-1913.2064,130.3583,0,0,0,0,100,0),
(@PATH,11,-12292.008,-1899.5505,130.28304,0,0,0,0,100,0),
(@PATH,12,-12302.664,-1882.1113,130.38538,0,0,0,0,100,0),
(@PATH,13,-12308.578,-1866.2955,130.3816,0,0,0,0,100,0),
(@PATH,14,-12321.762,-1855.7916,130.3816,0,0,0,0,100,0),
(@PATH,15,-12319.301,-1837.3279,130.3816,0,0,0,0,100,0),
(@PATH,16,-12333.007,-1831.8125,130.3816,0,0,0,0,100,0),
(@PATH,17,-12316.513,-1835.5278,130.3816,0,0,0,0,100,0),
(@PATH,18,-12304.316,-1828.3707,130.3816,0,0,0,0,100,0),
(@PATH,19,-12291.655,-1821.4,130.38538,0,0,0,0,100,0),
(@PATH,20,-12321.201,-1840.0312,130.3816,0,0,0,0,100,0),
(@PATH,21,-12326.542,-1865.9154,130.3816,0,0,0,0,100,0),
(@PATH,22,-12333.967,-1876.9497,130.3084,0,0,0,0,100,0),
(@PATH,23,-12345.774,-1883.2954,130.3084,0,0,0,0,100,0),
(@PATH,24,-12357.866,-1904.3063,130.4747,0,0,0,0,100,0),
(@PATH,25,-12345.774,-1883.2954,130.3084,0,0,0,0,100,0),
(@PATH,26,-12333.967,-1876.9497,130.3084,0,0,0,0,100,0),
(@PATH,27,-12326.542,-1865.9154,130.3816,0,0,0,0,100,0),
(@PATH,28,-12321.201,-1840.0312,130.3816,0,0,0,0,100,0),
(@PATH,29,-12291.655,-1821.4,130.38538,0,0,0,0,100,0);
-- 0x204CB026A00B160000055E000230FE1A .go xyz -12304.316 -1828.3707 130.3816

**Comment by temperrr** [comment]
@neifion-00000000 

I cant figure out which pack is which for 8 and 9 can you tell me their composition?

**Comment by temperrr** [comment]
> ```
> >>>>Evidence for larger wander distance for Tiger Cubs or some other movement gimmicks
> ```
> 
> wander_distance can be at least 17, and one has complex movement behavior moving around and wandering
> 
> Further evidence shows all cubs are 17 wander_distance except 1-2 (and unsure if they are blocked by terrain or are actually less)

should I make a query to change all cubs wander distance to 17 ?

**Comment by neifion-00000000** [comment]
> > ```
> > >>>>Evidence for larger wander distance for Tiger Cubs or some other movement gimmicks
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wander_distance can be at least 17, and one has complex movement behavior moving around and wandering
> > Further evidence shows all cubs are 17 wander_distance except 1-2 (and unsure if they are blocked by terrain or are actually less)
> 
> should I make a query to change all cubs wander distance to 17 ?

likely, some minor checking might be needed to make sure they don't move too much (instance locations are all "wrong" for movetype 1 mobs, so its possible they might wander too much after being fixed and need relocated)

**Comment by neifion-00000000** [comment]
> @neifion-00000000
> 
> I cant figure out which pack is which for 8 and 9 can you tell me their composition?

The circle packs are all led by 1 small bat followed by 2 elite bats with additional 3 smaller bats, it looked like there were not enough mobs in the bat area on AC.

**Comment by temperrr** [comment]
> > @neifion-00000000
> > 
> > I cant figure out which pack is which for 8 and 9 can you tell me their composition?
> 
> The circle packs are all led by 1 small bat followed by 2 elite bats with additional 3 smaller bats, it looked like there were not enough mobs in the bat area on AC.  There are 4 circle packs, 1 pack that has the same composition of the circle pack (usually not pulled except on accident), and the wandering pack.
> 
> The only unique pack is the one marked by moon in the video, the wandering pack.
> 
> That with the 2 humanoids packs make up all of the mobs in that entire area

Ye I added some extra spawns already. I'll fix up the last two

**Comment by neifion-00000000** [comment]
(52) UD Patrol within area around pit

**Comment by neifion-00000000** [comment]
Fun stats patrol 51, has the most waypoints (most by distance it would prolly be a berserker, or the complex bat patrol if all by distance of points traveled)

![image](https://user-images.githubusercontent.com/91289495/176540705-1f2645ed-22cd-4695-9943-29f7a0256f84.png)
