### ISSUE TITLE
New AreaTrigger don't work

### ISSUE THREAD

**Issue by rodriguescr** [azerothcore/azerothcore-wotlk#1213]
##### SMALL DESCRIPTION:

Made a new Area Trigger in Orgrimmar to teleport to a VIP Room. But does not work.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should teleport me to MAP 803 that i created.

##### CURRENT BEHAVIOUR:

If i do a ".go trigger 6000" it teleports me to the current location of the trigger, i assume it it's working correctly but it do not teleport me to map 803.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Edit the AreaTrigger.dbc and add a new line with id 6000 and a location in Orgrimmar.
2.  Edit table acore_world.areatrigger with the same data as AreaTrigger.dbc
3.  Edit table acore_world.areatrigger_teleport and add teleport location or id 6000.
4.  Upload AreaTrigger.dbc to server data/dbc folder.
5.  Create MPQ with AreaTrigger.dbc file in it.
6.  Launch game and do .go trigger 6000.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit ccb925b856f8bf355a3bc040d30c9d1ab53936c0 (HEAD -> master, origin/master, origin/HEAD)

##### OPERATING SYSTEM:

Ubuntu 16.04

##### MODULES:

None.

##### OTHER CUSTOMIZATIONS:

Just the MAP 803 created. No other modification.

**Comment by Nefertumm** [comment]
Not blizzlike. Join us on discord for this kind of stuff.
