### ISSUE TITLE
Midsummer commoners not present in any cities.

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#12144]
Original Chromiecraft report  https://github.com/chromiecraft/chromiecraft/issues/3650 

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

There are supposed to be Midsummer Commoner NPC's that start a breadcrumb quest [The Master of Summer Lore](https://wowgaming.altervista.org/aowow/?quest=11970) for Alliance, and [Spinner of Summer Tales](https://wowgaming.altervista.org/aowow/?quest=11971) for Horde, in all capitals and neutral cities. They are currently missing.

### Expected Blizzlike Behaviour

They should be present during the Midsummer world event and give the quest for their faction (except goblin).
    - Stormwind: [Human Commoner (also in Dalaran)](https://wowgaming.altervista.org/aowow/?npc=18927)
    - Ironforge: [Dwarf Commoner](https://wowgaming.altervista.org/aowow/?npc=19148) & The Great Forge [Gnome Commoner](https://wowgaming.altervista.org/aowow/?npc=19172)
    - Darnassus: [Night Elf Commoner](https://wowgaming.altervista.org/aowow/?npc=19173)
    - Exodar: [Draenei Commoner](https://wowgaming.altervista.org/aowow/?npc=19171)
    - Orgimmar: [Orc Commoner](https://wowgaming.altervista.org/aowow/?npc=19175)
    - Thunderbluff: [Tauren Commoner](https://wowgaming.altervista.org/aowow/?npc=19175)
    - Undercity: [Forsaken commoner](https://wowgaming.altervista.org/aowow/?npc=19178)
    - Silvermoon: See [Tauren Commoner](https://wowgaming.altervista.org/aowow/?npc=19175) Though I do believe this should be [Blood Elf Commoner](https://wowpedia.fandom.com/wiki/Blood_Elf_Commoner)  as shown by the previous link and [this one](https://wowgaming.altervista.org/aowow/?quest=11971) showing them as quest givers for horde in Dalaran as well.
    - Ratchet, Gadgetzen, Booty Bay, Everlook, and Shattrath: [Goblin commoner](https://wowgaming.altervista.org/aowow/?npc=20102)
     - Dalaran: Outside of the Horde and Alliace sanctuaries and banks. Check the links above

### Source

https://wowgaming.altervista.org/aowow/?quest=11970
https://wowgaming.altervista.org/aowow/?quest=11971

### Steps to reproduce the problem

1. Go to any capital or neutral city to their supposed locations
2. Notice no NPCs

### Extra Notes

- [Human Commoner (also in Dalaran)](https://wowgaming.altervista.org/aowow/?npc=18927)
- [Dwarf Commoner](https://wowgaming.altervista.org/aowow/?npc=19148)
- [Gnome Commoner](https://wowgaming.altervista.org/aowow/?npc=19172)
- [Night Elf Commoner](https://wowgaming.altervista.org/aowow/?npc=19173)
- [Draenei Commoner](https://wowgaming.altervista.org/aowow/?npc=19171)
- [Orc Commoner](https://wowgaming.altervista.org/aowow/?npc=19175)
- [Tauren Commoner](https://wowgaming.altervista.org/aowow/?npc=19175)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Worth pointing out, there are also two Draenei Commoners on the dock on the west coast of Azuremyst Isle that are also missing.

**Comment by sudlud** [comment]
Would a PR be accepted that places the NPCs based on estimated positions from the Videos until maybe sniffs are available?
