### ISSUE TITLE
Ragged Scavenger and Young Scavenger

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1215]
##### SMALL DESCRIPTION:

exactly the same problem as the following one, but on wolves entry 1509 and 1508.
https://github.com/azerothcore/azerothcore-wotlk/issues/667

Wolves attack when we are near them with a right click even if we have not touched them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The solution :
`UPDATE creature_template SET flags_extra =+ 2 WHERE entry IN (1509, 1508);`

##### STEPS TO REPRODUCE THE PROBLEM:

1. create an undead
2. go to the wolf
3. stay near and right clic

##### BRANCH(ES):

master

**Comment by FrancescoBorzi** [comment]
@Maurowin thanks for your report. You also included a fix, it would be nice if you could also open a PR.

Useful resources:

- [How to open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request)
- [How to deal with SQL files](https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files)

**Comment by Maurowin** [comment]
I tried a lot yesterday... im so dump.. I can't do it even with the guide

**Comment by FrancescoBorzi** [comment]
@Maurowin no worries. We can guide you step by step, let's talk in the chat

**Comment by Maurowin** [comment]
im in support-general chanel under Le0dagan name

**Comment by Maurowin** [comment]
Ok, all right

**Comment by poszer** [comment]
Tested, the fix included is fine

**Comment by poszer** [comment]
> 
> 
> Need pr :)

Will do it
