### ISSUE TITLE
[quest]`Find the Ancient Hero` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12153]
### Current Behaviour

The quest requires that `Subjugated Iskalder` be brought to `The Bone Witch`. After that, the quest cannot be completed

### Expected Blizzlike Behaviour

The quest requires that `Subjugated Iskalder` be brought to `The Bone Witch`. After that, the quest can be completed

### Steps to reproduce the problem

1. .q a 13133
2. .go c id 30718
3. talk it
4. when he becomes `iskalder`, then use `The Bone Witch's Amulet` for `iskalder`
5. bring 'iskalder' back to 'The Bone Witch'

### AC rev. hash/commit

38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

**Comment by r0m1ntik** [comment]
confirm

**Comment by UltraNix** [comment]
Fixed with 8d7e82e06be5b94f2398be9ba2c8888357c92ac8

**Comment by mpfans** [comment]
update to a7b27238238fd5683c8da25b0d8c13e3b5cf4a1b

The same bug 

@UltraNix
