### ISSUE TITLE
Feature: Elemental weapon damage

### ISSUE THREAD

**Issue by aradep** [azerothcore/azerothcore-wotlk#12165]
### Describe your feature request or suggestion in detail

**Suggestion:** When a weapon has a dmg_type1 other than 0, the damage dealt by it on autoattack will be that school of damage.

Currently on AzerothCore when you set a weapon to deal purely spell damage, it still deals physical damage on hit. Weapons dealing all spell damage isn't exactly blizzlike, but it works on vanilla cores so it should be possible to implement as a custom feature.

### Additional context

![image](https://user-images.githubusercontent.com/61268368/175765437-96b1e917-a93e-48df-8116-205165d2f896.png)
![image](https://user-images.githubusercontent.com/61268368/175765433-71100497-546f-4438-a9e2-39b74ae92501.png)
![image](https://user-images.githubusercontent.com/61268368/175765440-cffc7a65-74ee-4fd5-9216-233678b1ceac.png)

**Comment by Gultask** [comment]
Seconding this. Wands should be able to be affected by elemental resistances/vulnerabilities but currently aren't, even though the damage in the combat log is stated as being elemental.

It was noted in ChromieCraft BWL: https://github.com/chromiecraft/chromiecraft/issues/3610
Some sources that wands should deal elemental damage and be affected by res/vuln:
https://classic.wowhead.com/guide=10025/chromaggus-wand-list

>As a vanilla warlock, the only times I used a wand were on Broodlord in BWL (I was specifically banned from casting shadow bolt) and on chromatic trash/Chrommagus, with a wand of a damage type the raid didn't have a lot of access to (like nature or arcane). ([source](https://www.reddit.com/r/classicwow/comments/7hhrog/comment/dqrgqn9/?utm_source=reddit&utm_medium=web2x&context=3))

**Comment by davegrier** [comment]
Pre-emptively checking in on this feature request as Frost damage wands will be important for Viscidus in AQ40

**Comment by Nyeriah** [comment]
Frost damage wands deal frost damage correctly

**Comment by davegrier** [comment]
> 

Whatever is happening under the hood, they don't meaningfully deal elemental damage if they don't interact with elemental weaknesses and immunities 
![image](https://user-images.githubusercontent.com/14080595/190515514-789a3aa2-4a48-451d-9c5e-63b475beaaf8.png)
