### ISSUE TITLE
NPC WAYPOINT 

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1216]
##### SMALL DESCRIPTION:

In the small town of Brill (undeads area) when you click on an NPC that follows a waypoint, it stops correctly but does not resume its path.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After we talk to them and after a moment they have to go back on their way

##### CURRENT BEHAVIOUR:

does not go back on their way

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to Brill
2. right clic on npc with waypoint
3. stop tolk with him
4. see if they resume its path

##### BRANCH(ES):

master

**Comment by poszer** [comment]
@Maurowin Include name of NPC, please  Also if you can, write in game .gps when you are near that npc, and you will see cordinate, write them here ( xyz) .
It will be easier to reproduce issue. 
In this way how you fill template issue, i dont know what is that Npc.
Thanks

**Comment by Stoabrogga** [comment]
Cannot confirm this. After talking to Gordo (creature ID 10666) he continues on his path after waiting a few minutes. I also did check the following NPCs:
- Deathguard Lundmark (ID 5725)
- Deathguard Terrence (ID 1738)

They all resume on their paths after talking to them.

**Comment by Maurowin** [comment]
So few minutes its to long. Maybe few secondes. Where can we see retail delay ?

**Comment by poszer** [comment]
Ok, i have tested this, and i cannot confirm this.
For example, there is creature Gordo ( Creature GUID 28413) who's using waypaths and also giving Quest ( If you talk with him, taking quest, and going to do it, the creature will Stay for some seconds there - Which is correct. Here is a one [Video](https://www.youtube.com/watch?v=bI7L2Qe-ToA) of quest where you can clearly see that creature is still without movement, even if the Player has  finished interaction with him )
Also the creatures like :
1. Junior Apothecary Holland (Creature GUID 28412 )
2. DeathGuard Bartholomew (Creature GUID 34111)
3. Hamlin Atkins (Creature GUID 38292)

When you talk with them, all of them continue waypoint in max 100 seconds 
![questtaken0_02](https://user-images.githubusercontent.com/41213210/51004269-2ab06300-153a-11e9-979a-8a00726ffdaf.png)
![killedmob0_42](https://user-images.githubusercontent.com/41213210/51004270-2ab06300-153a-11e9-9ce4-c68e5e394f73.png)
