### ISSUE TITLE
[ZG] Hakkar - Blood Siphon

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12189]
### Current Behaviour

Blood Siphon not stun the raid.

### Expected Blizzlike Behaviour

When siphon blood is cast, Hakkar should stun the entire raid for 8sec, and drain the life of players. But if a player get debuff[ Poisonous Blood](https://classic.wowhead.com/spell=24321/poisonous-blood), the drain will instead damage Hakkar.

### Source

https://classic.wowhead.com/guides/hakkar-the-soulflayer-zul-gurub-strategy

### Steps to reproduce the problem

1. Engage Hakkar
2. Wait that he cast blood siphon

### AC rev. hash/commit

[76e9e19](https://github.com/azerothcore/azerothcore-wotlk/commit/76e9e19f0cd8c4f552f547532581884c1af3028c)

### Operating system

Windows 11

**Comment by UltraNix** [comment]
The stun affects only Hakkar, not the entire raid. The raid members are immuned to stuns and dazed effects.
https://youtu.be/AlxAjMU_wTA?t=45
https://youtu.be/AlxAjMU_wTA?t=135
