### ISSUE TITLE
ZG Areatriggers are wrong

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12187]
### Current Behaviour

Bridge does not trigger the yell from hakkar
Enterance area trigger does trigger the yell from hakkar

### Expected Blizzlike Behaviour

Entering area trigger should call this emote
![image](https://user-images.githubusercontent.com/20357406/175805788-d0fa800b-c633-4264-8b75-20e60ffafaf9.png)
![image](https://user-images.githubusercontent.com/20357406/175805796-b5b2cba2-6541-4a3a-892d-3fa8eac006d4.png)

Entering the bridge +- a few seconds (5-10) hakkar should yell
![image](https://user-images.githubusercontent.com/20357406/175805792-e7e05795-9586-449f-ad3b-bd0d88a41dea.png)
![image](https://user-images.githubusercontent.com/20357406/175805800-8ec6ff98-d58e-47b4-a5bf-1d5bea342412.png)

### Source

TBC PTR

### Steps to reproduce the problem

1. enter zul'gurub
2. get emote on entrance
3. go to first bridge
4. get yell from hakkar

### AC rev. hash/commit

76e9e19f0cd8c4f552f547532581884c1af3028c

### Operating system

Manjaro x64

**Comment by neifion-00000000** [comment]
note to self to adjust the duration field on the creature_text for this to get the delay correct

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/176101578-4ac75363-5cee-402a-a032-f55e100553ed.png)
oops found another one

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/176102162-f05628a7-f3aa-4922-8db0-1efbd52da627.png)
Both of these happened at delays after entering UD boss/EoM
