### ISSUE TITLE
[server] world 4 crashes in 3 days

### ISSUE THREAD

**Issue by SKingOWN** [azerothcore/azerothcore-wotlk#12181]
### Current Behaviour

All crash logs here:
https://gist.github.com/SKingOWN/d78211e71e3894ea6ae975e22b861881

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

61c64bbf3049d1548c55f56dc872ab03f073904f

### Operating system

Ubuntu 20.04

### Custom changes or Modules

anticheat
cfbg
duelreset
transmog

**Comment by SKingOWN** [comment]
Crash at this function Object::GetGuidValue() in Object.cpp

**Comment by UltraNix** [comment]
@SKingOWN This is your local server? Looks like loading skill being on transport (ship or elevator). Can you confirm my suspicious?

**Comment by SKingOWN** [comment]
I have this server active with more than 500 users connected every day. As the crash does not happen very often and due to the number of connected clients, I have not been able to identify exactly how to reproduce it.

**Comment by SKingOWN** [comment]
@UltraNix However, when a client disconnects on a transport, another reconnection crash sometimes occurs. I am preventing this other crash by teleporting home everyone who is disconnected in a transport at the time it is reconnected (temporary solution); but even then the crash that I reported here occurs.

**Comment by SKingOWN** [comment]
Other crash that may be related:
```
Thread 1 "worldserver" received signal SIGSEGV, Segmentation fault.
0x0000000000e20fbc in Map::SendInitSelf (this=<optimized out>, player=0x7ffcdef5d680) at /home/me/azerothcore-wotlksrc/server/game/Maps/Map.cpp:2532
2532	        transport->BuildCreateUpdateBlockForPlayer(&data, player);
#0  0x0000000000e20fbc in Map::SendInitSelf (this=<optimized out>, player=0x7ffcdef5d680) at /home/me/azerothcore-wotlksrc/server/game/Maps/Map.cpp:2532
#1  0x0000000000e20869 in Map::AddPlayerToMap (this=0x7fffa0d8bb40, player=0x7ffcdef5d680) at /home/me/azerothcore-wotlksrc/server/game/Maps/Map.cpp:526
#2  0x000000000110c9ad in WorldSession::HandlePlayerLoginFromDB (this=0x7fff7bf95800, holder=...) at /home/me/azerothcore-wotlksrc/server/game/Handlers/CharacterHandler.cpp:885
#3  0x00000000011aaeca in std::function<void (SQLQueryHolderBase const&)>::operator()(SQLQueryHolderBase const&) const (this=0x7ffed4b30da0, __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#4  SQLQueryHolderCallback::InvokeIfReady (this=0x7ffed4b30d80) at /home/me/azerothcore-wotlksrc/server/database/Database/QueryHolder.cpp:92
```

**Comment by UltraNix** [comment]
@SKingOWN Show me the whole crashlog.

**Comment by UltraNix** [comment]
@SKingOWN ??

**Comment by Kitzunu** [comment]
Closing as no updates
