### ISSUE TITLE
ZG Hoodoo Piles not working correctly

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12186]
### Current Behaviour

Hoodoo Piles are mind controlling everyone walking near them

### Expected Blizzlike Behaviour

They should have a % chance to mind control the user interacting with it after a short amount of time after looting

### Source

TBC PTR

### Steps to reproduce the problem

1. go to zg
2. loot hoodoo pile
3. get random chacne to be mind controlled

### AC rev. hash/commit

76e9e19f0cd8c4f552f547532581884c1af3028c

### Operating system

Manjaro x64

**Comment by UltraNix** [comment]
Works okay. Trap is activated only if I click on the pile.

**Comment by temperrr** [comment]
@UltraNix 

It stays in combat/spreads to more people which shouldnt happen

**Comment by Gultask** [comment]
https://github.com/chromiecraft/chromiecraft/issues/3651
