### ISSUE TITLE
Feature: Does Smart AI -> Event 25 Reset need to include first spawn?

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/azerothcore-wotlk#12195]
### Describe your feature request or suggestion in detail

The Smart AI system already have 37 AI_Init to handle this, would it be possible to remove the spawn part from Reset?

A reset to me is always when a NPC have been in combat at least once

Spawn in Reset prevents you from creating certain things on a custom server or u need to find work around ideas all the time to do it instead.

**Comment by UltraNix** [comment]
Use 11 - SMART_EVENT_RESPAWN

**Comment by Sulan2** [comment]
> Use 11 - SMART_EVENT_RESPAWN

This still doesnt fix what I mean

Lets say u have a raid who wipes on a boss, aka the boss doesnt die it just Resets, so u want to have an Event that happens on all resets (all wipes) but not the first time it spawns because there havent been any wipes yet

If u remove Spawn from reset, Reset together with 37 AI Init will have the possibility to handle all situations 

I understand why u wouldnt want to change this by looking at different SmartAI settings for different creatures its obvious that it has been created as a shortcut to have 1 way to let a lot of thrash mobs re cast buffs on themselves by just having to use 1 Event instead of 2

But if u want to go custom and be creative this limits you to easily work so therefor Is it possible to remove this myself and get the server to work?

**Comment by UltraNix** [comment]
OnRespawn --> boss is spawned/respawned
OnEvade --> boss evades
OnReset - boss is spawned/respawned or evades

Choose what you want

**Comment by Sulan2** [comment]
> OnRespawn --> boss is spawned/respawned OnEvade --> boss evades OnReset - boss is spawned/respawned or evades
> 
> Choose what you want

I want a Non spawned RESET I dont want anything u describe
The word Reset means to re set something that has happend, not to re set something that havent happend yet

Spawn = First time it spawns = 37 AI INIT
Respawn = NPC dies once and spawns again = 11 Respawn
Evade = NPC cannot reach player postions and therefor runs back = 7 Evade
Reset = NPC looses combat with players and returns to its start postion after being in combat once = 25 Reset

This way u cover all possible outcomes but 25 Reset also contains the function of 37 Ai Init in ACore for some reason

**Comment by Sulan2** [comment]
Lets say u created a NPC that u wanted to open a door everytime it resets but not when it spawns, how would u do this?

**Comment by Nyeriah** [comment]
> Lets say u created a NPC that u wanted to open a door everytime it resets but not when it first spawned, how would u do this?

Evade or JustReachedHome depending on when you want the door to open.

**Comment by UltraNix** [comment]
`I want a Non spawned RESET I dont want anything u describe`
Then you want OnEvade. This is the only event that calls Reset (besided respawn).

**Comment by Sulan2** [comment]
Cheers guys both those worked, so Evade included more than I thought it did
I thought Evade was only when the evade mechanic is getting triggered

With this said, what exactly is the differnce between Evade and Reached Home?

**Comment by Nyeriah** [comment]
Evade fires as soon as the creature evades, e.g turns its back and starts moving home (before it reaches home position).
Reached home will only fire once it is idle, resting at home position.
