### ISSUE TITLE
Mac OS X Debug build broken

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#122]
**Description**:

On Mac OS X El Capitan 10.11.6 using Clang, the compilation works under Release mode but does not work under Debug mode.

Compile error: [http://paste.ubuntu.com/23112223/](http://paste.ubuntu.com/23112223/)

`[  0%] Built target gamefwPCH.cpp_dephelp
[  0%] Built target gsoap
[  0%] Built target Detour
[  1%] Built target Recast
[  1%] Built target collisionPCH.cpp_dephelp
[  1%] Linking CXX shared module libsharedPCH.cpp_dephelp.so
[  1%] Generating collisionPCH.h.pch
[  6%] Built target g3dlib
Undefined symbols for architecture x86_64:
  "ACE_OS_Thread_Descriptor::~ACE_OS_Thread_Descriptor()", referenced from:
      ACE_Thread_Descriptor_Base::~ACE_Thread_Descriptor_Base() in sharedPCH.cpp.o
  "typeinfo for ACE_OS_Thread_Descriptor", referenced from:
      typeinfo for ACE_Thread_Descriptor_Base in sharedPCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [modules/worldengine/nucleus/src/libsharedPCH.cpp_dephelp.so] Error 1
make[1]: *** [modules/worldengine/nucleus/src/CMakeFiles/sharedPCH.cpp_dephelp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target revision.h
[  6%] Linking CXX shared module libauthPCH.cpp_dephelp.so
[  6%] Linking CXX shared module libworldPCH.cpp_dephelp.so
[  6%] Linking CXX shared module libgamePCH.cpp_dephelp.so
[  6%] Generating gamefwPCH.h.pch
[  6%] Linking CXX shared module libScriptPCH.cpp_dephelp.so
Undefined symbols for architecture x86_64:
  "ACE_OS_Thread_Descriptor::~ACE_OS_Thread_Descriptor()", referenced from:
      ACE_Thread_Descriptor_Base::~ACE_Thread_Descriptor_Base() in authPCH.cpp.o
  "typeinfo for ACE_OS_Thread_Descriptor", referenced from:
      typeinfo for ACE_Thread_Descriptor_Base in authPCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/authserver/libauthPCH.cpp_dephelp.so] Error 1
make[1]: *** [src/authserver/CMakeFiles/authPCH.cpp_dephelp.dir/all] Error 2
Undefined symbols for architecture x86_64:
  "ACE_OS_Thread_Descriptor::~ACE_OS_Thread_Descriptor()", referenced from:
      ACE_Thread_Descriptor_Base::~ACE_Thread_Descriptor_Base() in worldPCH.cpp.o
  "typeinfo for ACE_OS_Thread_Descriptor", referenced from:
      typeinfo for ACE_Thread_Descriptor_Base in worldPCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/worldserver/libworldPCH.cpp_dephelp.so] Error 1
make[1]: *** [src/worldserver/CMakeFiles/worldPCH.cpp_dephelp.dir/all] Error 2
Undefined symbols for architecture x86_64:
  "ACE_OS_Thread_Descriptor::~ACE_OS_Thread_Descriptor()", referenced from:
      ACE_Thread_Descriptor_Base::~ACE_Thread_Descriptor_Base() in gamePCH.cpp.o
  "typeinfo for ACE_OS_Thread_Descriptor", referenced from:
      typeinfo for ACE_Thread_Descriptor_Base in gamePCH.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "ACE_OS_Thread_Descriptor::~ACE_OS_Thread_Descriptor()", referenced from:
      ACE_Thread_Descriptor_Base::~ACE_Thread_Descriptor_Base() in ScriptPCH.cpp.o
  "typeinfo for ACE_OS_Thread_Descriptor", referenced from:
      typeinfo for ACE_Thread_Descriptor_Base in ScriptPCH.cpp.o
ld: symbol(s) not found for architecture x86_64
make[2]: *** [src/game/libgamePCH.cpp_dephelp.so] Error 1
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [src/game/CMakeFiles/gamePCH.cpp_dephelp.dir/all] Error 2
make[2]: *** [src/scripts/libScriptPCH.cpp_dephelp.so] Error 1
make[1]: *** [src/scripts/CMakeFiles/ScriptPCH.cpp_dephelp.dir/all] Error 2
[  6%] Built target generate_gamefwPCH.cpp
[  6%] Built target generate_collisionPCH.cpp
make: *** [all] Error 2
`

*\* Additional Information *\* 

clang version:
`Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

cmake version: `3.5.2`

**Steps to reproduce the problem**:
1. Replace CMake param `-DCMAKE_BUILD_TYPE=Release` with `-DCMAKE_BUILD_TYPE=Debug`
2. Compile

**Branch(es)**: master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/00d04e94a75d754f4f587830d4d316fb9fbb7397

**Operating system**:  Mac OS X El Capitan 10.11.6

**Modules**:  none

**Other Customizations**: none
##

**Comment by Deku** [comment]
Is this still an issue?

**Comment by ShinDarth** [comment]
I haven't tested it since then. We can close this and in case someone else has the same issue we can reopen it.

**Comment by ppishero** [comment]
I have the same problem，I don't know how to solve this problem.

**Comment by Pondaveia** [comment]
Stupid question but could make a difference. Is your fork updated?

**Comment by BarbzYHOOL** [comment]
lol i think we can close this @FrancescoBorzi no?

**Comment by FrancescoBorzi** [comment]
We need to test on a recent AC version to check if the issue is still there. There is a good chance that it's still broken...

**Comment by FrancescoBorzi** [comment]
Tested a newer AC version (https://github.com/azerothcore/azerothcore-wotlk/commit/49e4ae7e9ce3) on macOS Catalina.

I'm happy to say that both the `Release` and `Debug` build work fine on mac! Closing this.
