### ISSUE TITLE
WINDOW 64X DEBUG Pattern-Aura superposition problem

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#1220]
SMALL DESCRIPTION:
I use'RelWithDebInfo model compile' ‘’WINDOW 64X DEBUG ‘’version,Same aura can overlap effects

Note: Compile using 'Release mode' and there will be no superposition problem

EXPECTED BLIZZLIKE BEHAVIOUR:
The same spell will appear
"A more powerful spell is already active"
The above tips are correct.

CURRENT BEHAVIOUR:
spell:48161-spell:48162[Can overlap]
spell:48169-spell:48170[Can overlap]

STEPS TO REPRODUCE THE PROBLEM:

1. Need a full priest role
2.Use it for yourself,spell:48161-spell:48162
3.You will see that the same spells overlap.

BRANCH(ES):
master

AC HASH/COMMIT: [0e16853 ](https://github.com/azerothcore/azerothcore-wotlk/commit/0e16853157cff17dcd59aac490fbd5db3da0b727)

OPERATING SYSTEM: WINDOW 7
MODULES: None
OTHER CUSTOMIZATIONS: None

**Comment by boom8866** [comment]
WINDOW 64X DEBUG There are a lot of problems

**Comment by FrancescoBorzi** [comment]
I don't have Windows. Can anyone that has Windows check this?

**Comment by BarbzYHOOL** [comment]
@Nefertumm @dunjeon maybe?

**Comment by dunjeon** [comment]
I don't use debug, but I'll take a look.

**Comment by boom8866** [comment]
I plan to turn off this problem, because I used the DEdebug mode you recommended. I'm sorry
