### ISSUE TITLE
[ZG] Jin'do the Hexxer - Hex should not reset the encounter & Missing conditions for the spell - Low Priority

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12203]
### Current Behaviour

 - If the boss casts Hex on the player when they're running solo, the encounter will reset.
 - If the player tries to solo the boss, he will cast Hex on the player.

### Expected Blizzlike Behaviour

 - If there are no other valid targets in the boss' threat table, he should keep attacking the hexxed player.
 - If there is only a single player alive in the raid or zone, the boss will not cast Hex.

### Source

https://youtu.be/bWTIVsbrjGo?t=68 2-man footage. Boss casts Hex at the timestamp. The other player is not fighting the boss at the time, so the boss kept attacking the hexxed player.

https://www.youtube.com/watch?v=I3oveygDBY4 The second player dies early in the fight. Hex is not cast after that.

https://www.youtube.com/watch?v=WiXSvVwmPic Only a single player is left alive. Hex is not cast.

### Steps to reproduce the problem

.go c id 11380
Go solo, see if Hex is cast or not.
Go with at least 2 characters, allow one to die, and then see if the boss still casts Hex
Go with 2 characters, place one far away from the fight, see if Hex resets the boss

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4cbe846d2221dc861598c473394e810942cde210

### Operating system

Windows 10

**Comment by Maelthyrr** [comment]
Here, the tank is hit by hex : https://youtu.be/gdLSg2JWYCA?t=104

And on wowhead, they said: With[ Hex](https://classic.wowhead.com/spell=24053/hex), Jin'do transforms the person on top of their threat table (usually the main tank) into a frog. When Hex happens, Jin'do starts attacking the second highest person on the threat table. Hex is dispellable, so you can simply have one of the other tanks taunt Jin'do while waiting for the dispell on the main tank. Another way to dealing with Hex is to simply use a Druid tank, as Hex counts as a Polymorph effect, which Bear Form Druids are immune to. This would also mean you only need one tank for this fight.

https://classic.wowhead.com/guides/jindo-the-hexxer-zul-gurub-strategy

**Comment by Gultask** [comment]
Thank you for the info!

I'll take another look at it when I can.

**Comment by Gultask** [comment]
First off. Thank you! I'd hate to cause a regression. That teaches me to not read wikis/guides
It even happens several times **in the video I linked**: https://youtu.be/bWTIVsbrjGo?t=68 🥴 
so yeah, I messed up here.

So I have 2 ideas as to why Hex isn't cast in solo videos:

1. It is only cast when there are at least 2 players in the raid and alive.
2. Brain Wash Totem resets the CD/scheduling, delaying Hex.

Either way, it shouldn't reset the boss, which is what currently happens. And that is more easily provable than either of those hypotheses.

Thanks again <3

**Comment by Maelthyrr** [comment]
For this:  Brain Wash Totem resets the CD/scheduling, delaying Hex,  it's more complicated to prove this. But we can simply add like others bosses, a condition where the boss  doesn't  a mind control if there are only one people alive and not charmed.

**Comment by Gultask** [comment]
True, and after reviewing the WotLK videos it seems that Hex is only cast if there's at least 2 people alive in the raid/zone.

Hex is only cast in this video: https://youtu.be/bWTIVsbrjGo?t=68
But not in these:
https://www.youtube.com/watch?v=I3oveygDBY4 where the other character dies very early in the fight
https://www.youtube.com/watch?v=WiXSvVwmPic where the rest of the party is dead

So that is the probable behaviour.

As for the Mind Control/Brain Wash, Jin'do looks a bit peculiar to me since he resets differently than the other bosses. It takes "longer" for him to reset, allowing the charm to not affect the encounter too much. I'm going to open another issue about it once I gather sufficient evidence for all the minor details, if possible.

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12233
