### ISSUE TITLE
[quest] `What Book? I Don't See Any Book.` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12213]
### Current Behaviour

Defeating  `"Dirty" Larry` will not complete the quest 
https://youtu.be/_MzjAYs6pFU

### Expected Blizzlike Behaviour

Defeating  `"Dirty" Larry` will complete the quest 

### Source

https://www.youtube.com/watch?v=cle1Tg3q5E0

This video works

### Steps to reproduce the problem

1 .q a 10231
2. go c id 19720
3.  Dialogue he starts fighting and defeats him

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

**Comment by Tony931023** [comment]
Confirmed, this quest is bug
