### ISSUE TITLE
[ulduar] unable to start the battle with `Razorscale` 

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12214]
### Current Behaviour

 unable to start the battle with `Razorscale` 
https://youtu.be/df5nSPRP3j4
### Expected Blizzlike Behaviour

Dialog 'expedition commander' to start fighting

### Steps to reproduce the problem

1. .go c id 33210
2. Dialog 'expedition commander' 

### Extra Notes
from https://github.com/azerothcore/azerothcore-wotlk/commit/8151fcda22c6167211d1c08788791fe1ad9e2c44 to https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec, Then it will not work

https://github.com/azerothcore/azerothcore-wotlk/commit/8151fcda22c6167211d1c08788791fe1ad9e2c44 work..

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec not work

### AC rev. hash/commit

38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

**Comment by NoM0Re** [comment]
Confirmed, got the same issue u can choose the gossip and its starts after 8secounds it breaks.

Tested on Windows:
https://github.com/azerothcore/azerothcore-wotlk/commit/4cbe846d2221dc861598c473394e810942cde210
