### ISSUE TITLE
[raid]`The Eye of Eternity` unable to start battle

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12211]
### Current Behaviour

Touch 'the Focusing Iris' and you cannot fight' Malygos'

### Expected Blizzlike Behaviour

Touch 'the Focusing Iris' and you can fight' Malygos'

### Steps to reproduce the problem

1. .go xyz 3864.879883 6987.100098 152.042007 571 
2. enter `The Eye of Eternity`
3. Touch 'the Focusing Iris' 

### Extra Notes

from https://github.com/azerothcore/azerothcore-wotlk/commit/8151fcda22c6167211d1c08788791fe1ad9e2c44 to https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec, Then it will not work

https://github.com/azerothcore/azerothcore-wotlk/commit/8151fcda22c6167211d1c08788791fe1ad9e2c44 work..

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec not work

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

**Comment by NoM0Re** [comment]
Confirmed, got the same issue.
Tested on Windows:
https://github.com/azerothcore/azerothcore-wotlk/commit/4cbe846d2221dc861598c473394e810942cde210
