### ISSUE TITLE
[QUEST] Ulag the cleaver

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1222]
##### SMALL DESCRIPTION:

After clicking on the rune, we must wait until the seal is lifted. However, you do not see a seal and you have to click on the door manually

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Like video
https://www.youtube.com/watch?v=TssjgNMJuPk&t=10s
![2019-01-02 1](https://user-images.githubusercontent.com/31663279/50609814-1d0f3380-0ed1-11e9-9a23-622cab9e2dfa.png)

##### CURRENT BEHAVIOUR:

The quest is currently as in the video below
https://www.youtube.com/watch?v=xrUCOwy3S8s

##### STEPS TO REPRODUCE THE PROBLEM:

1. learn quest id 1819
2. clic on the rune
3. see

##### BRANCH(ES):

master

**Comment by grimgravy** [comment]
[TrinityCore Fixation](http://dev.qyh.name:800/snet-dev-group/TrinityCore/commit/029c4232a7f53b32cd233502eb7078e64f37e87e)
[SQL AC](https://pastebin.com/Fhx2PUFk)

**Comment by FrancescoBorzi** [comment]
@grimgravy thanks! It would be nice if you could open a PR :)

**Comment by poszer** [comment]
Tested in game with fix included. It's okay ( Players can now click on that ''Mausoleum Trigger'' and the doors are opening. The NPC Ulag the cleaver coming outside on Horse and attacking player)  - Just like on the Video. Will create PR for it. Thanks @grimgravy

**Comment by pklloveyou** [comment]
Why not C++scripts

**Comment by pklloveyou** [comment]
`/*######
## go_mausoleum_trigger
######*/

enum Mausoleum
{
    QUEST_ULAG      = 1819,
    NPC_ULAG        = 6390,
    GO_DOOR         = 176594
};

class npc_ulag_the_cleaver : public CreatureScript
{
public:
	npc_ulag_the_cleaver() : CreatureScript("npc_ulag_the_cleaver") { }

	CreatureAI* GetAI(Creature* creature) const
	{
		return new npc_ulag_the_cleaverAI(creature);
	}

	struct npc_ulag_the_cleaverAI : public ScriptedAI
	{
		npc_ulag_the_cleaverAI(Creature* creature) : ScriptedAI(creature) { }

		void Reset()
		{
			me->CastSpell(me, 23246, true);
			me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
			me->NearTeleportTo(me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY(), me->GetHomePosition().GetPositionZ(), me->GetHomePosition().GetOrientation());
		}

		void EnterCombat(Unit* /*who*/)
		{
			if (GameObject* pDoor = me->FindNearestGameObject(GO_DOOR, 50.0f))
				pDoor->SetGoState(GO_STATE_READY);
			me->RemoveAurasDueToSpell(23246);
			me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
		}
	};
};

class go_mausoleum_trigger : public GameObjectScript
{
public:
    go_mausoleum_trigger() : GameObjectScript("go_mausoleum_trigger") { }

    bool OnGossipHello(Player* player, GameObject* go)
    {
        if (player->GetQuestStatus(QUEST_ULAG) != QUEST_STATUS_INCOMPLETE)
            return false;

        if (GameObject* pDoor = player->FindNearestGameObject(GO_DOOR, 30.0f))
        {
			pDoor->SetGoState(GO_STATE_ACTIVE);
			player->SummonCreature(NPC_ULAG, 2391.103f, 335.246f, 40.02f, 2.2345f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 10000);
			if (Creature * pTrigger = player->FindNearestCreature(NPC_ULAG, 50.0f))
			{
				pTrigger->CastSpell(pTrigger, 23246, true);
				pTrigger->GetMotionMaster()->MoveFollow(player, 1.0f, 3.0f);
			}
            return true;
        }

        return false;
    }
};

void AddSC_tirisfal_glades()
{
    new npc_calvin_montague();
	new npc_ulag_the_cleaver();
    new go_mausoleum_trigger();
}`

**Comment by pklloveyou** [comment]
`/*######
## go_mausoleum_trigger
######*/

enum Mausoleum
{
    QUEST_ULAG      = 1819,
    NPC_ULAG        = 6390,
    GO_DOOR         = 176594
};

class npc_ulag_the_cleaver : public CreatureScript
{
public:
	npc_ulag_the_cleaver() : CreatureScript("npc_ulag_the_cleaver") { }

	CreatureAI* GetAI(Creature* creature) const
	{
		return new npc_ulag_the_cleaverAI(creature);
	}

	struct npc_ulag_the_cleaverAI : public ScriptedAI
	{
		npc_ulag_the_cleaverAI(Creature* creature) : ScriptedAI(creature) { }

		void Reset()
		{
			me->CastSpell(me, 23246, true);
			me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
			me->NearTeleportTo(me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY(), me->GetHomePosition().GetPositionZ(), me->GetHomePosition().GetOrientation());
		}

		void EnterCombat(Unit* /*who*/)
		{
			if (GameObject* pDoor = me->FindNearestGameObject(GO_DOOR, 50.0f))
				pDoor->SetGoState(GO_STATE_READY);
			me->RemoveAurasDueToSpell(23246);
			me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
		}
	};
};

class go_mausoleum_trigger : public GameObjectScript
{
public:
    go_mausoleum_trigger() : GameObjectScript("go_mausoleum_trigger") { }

    bool OnGossipHello(Player* player, GameObject* go)
    {
        if (player->GetQuestStatus(QUEST_ULAG) != QUEST_STATUS_INCOMPLETE)
            return false;

        if (GameObject* pDoor = player->FindNearestGameObject(GO_DOOR, 30.0f))
        {
			pDoor->SetGoState(GO_STATE_ACTIVE);
			player->SummonCreature(NPC_ULAG, 2391.103f, 335.246f, 40.02f, 2.2345f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 10000);
			if (Creature * pTrigger = player->FindNearestCreature(NPC_ULAG, 50.0f))
			{
				pTrigger->CastSpell(pTrigger, 23246, true);
				pTrigger->GetMotionMaster()->MoveFollow(player, 1.0f, 3.0f);
			}
            return true;
        }

        return false;
    }
};

void AddSC_tirisfal_glades()
{
    new npc_calvin_montague();
	new npc_ulag_the_cleaver();
    new go_mausoleum_trigger();
}`

**Comment by pklloveyou** [comment]
`
UPDATE `gameobject_template` SET `flags` =114 WHERE `entry` IN (176594);
UPDATE `creature_template` SET `ScriptName` ="npc_ulag_the_cleaver" WHERE `entry` IN (6390);
`

**Comment by pklloveyou** [comment]
UPDATE gameobject_templateSETflags=114, ScriptName="" WHER Eentry IN (176594); 
UPDATE creature_template SET ScriptName="npc_ulag_the_cleaver" WHERE entry IN (6390);

**Comment by FrancescoBorzi** [comment]
whatever **can** be moved to SAI (without any breaks), it **should** be moved to SAI

**Comment by Viste** [comment]
SAI faster then C++
