### ISSUE TITLE
NPC Summoning spells and nonresponsive worldserver

### ISSUE THREAD

**Issue by duncrafter** [azerothcore/azerothcore-wotlk#12239]
### Current Behaviour

When some mobs use a spell to summon another creature, all game procedures exept player movement stop and worldserver.exe becomes nonresponsive.

Tested on Edwin van Cleef (ID 639), summons Defias Blackguard (ID 636) through VanCleef's Allies (ID 5200)
and Lupine Horrors (ID 3863), summons Lupine Delusion (ID 5097) through Summon Lupine Delusions (ID 7132).

### Expected Blizzlike Behaviour

Creature should be summoned without issue.

### Steps to reproduce the problem

Ex.:
1. Enter Shadowfang Keep.
2. Aggro Lupine Horror.
3. Wait for spell cast

### Extra Notes

This bug seems to just affect mobs with have neither data in pet_levelstats table nor pet type =Summon_Pet (Demons, Mage elementals etc.)

### AC rev. hash/commit

e92428940539d178e08012db6e2681690d2308aa

### Operating system

Windows 7 x64

### Custom changes or Modules

Transmog
Autobalance
Arac
Learnspells

**Comment by Kitzunu** [comment]
If you enable freeze detector in configs the server will crash at a freeze and we can debug the crashlog.

**Comment by Kitzunu** [comment]
Closing, has not heard anything like it since
