### ISSUE TITLE
[MONSTER] Vile fin minor oracle

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1223]
##### SMALL DESCRIPTION:

This caster only makes melee attacks

##### EXPECTED BLIZZLIKE BEHAVIOUR:

he can also use nature-type spells
http://wowwiki.wikia.com/wiki/Vile_Fin_Minor_Oracle

##### CURRENT BEHAVIOUR:

This caster only makes melee attacks

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to creature 1544
2. attack him
3. look if he cast spell

##### BRANCH(ES):

master

**Comment by grimgravy** [comment]
correction(TrinityCore)

-- Vile Fin Minor Oracle SAI
SET @ENTRY := 1544;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,0,0,3400,4800,11,9532,64,0,0,0,0,2,0,0,0,0,0,0,0,"Vile Fin Minor Oracle - In Combat - Cast Lightning Bolt"),
(@ENTRY,0,1,0,0,0,100,0,11000,16000,12000,16000,11,2607,0,0,0,0,0,4,0,0,0,0,0,0,0,"Vile Fin Minor Oracle - In Combat - Cast Shock"),
(@ENTRY,0,2,0,1,0,100,0,500,1000,600000,600000,11,324,0,0,0,0,0,1,0,0,0,0,0,0,0,"Vile Fin Minor Oracle - Out of Combat - Cast Lightning Shield"),
(@ENTRY,0,3,0,16,0,100,0,324,1,15000,30000,11,324,0,0,0,0,0,1,0,0,0,0,0,0,0,"Vile Fin Minor Oracle - On Friendly Unit Missing Buff Lightning Shield - Cast Lightning Shield"),
(@ENTRY,0,4,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,0,0,0,0,0,0,0,0,"Vile Fin Minor Oracle - Between 0-15% Health - Flee For Assist (No Repeat)");

**Comment by Maurowin** [comment]
nice, i will test it today, can you make an PR?

**Comment by poszer** [comment]
Tested with this @grimgravy fix. Working fine now, the creature Casting spells

**Comment by poszer** [comment]
> 
> 
> @poszer can you please create a pr and merge it?

I'll do it

**Comment by FrancescoBorzi** [comment]
@poszer please leave the issue open until the solution is **on master**
