### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by maradaka** [azerothcore/azerothcore-wotlk#1224]
When I try to compile it gives me those errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol SSLeay_version referenced in function "int __cdecl ace_main_i(int,char * * const)" (?ace_main_i@@YAHHQEAPEAD@Z)	authserver	C:\sursa\azerothcorea\build\src\server\authserver\Main.obj	1	

Error	LNK1120	1 unresolved externals	authserver	C:\sursa\azerothcorea\build\bin\Release\authserver.exe	1	

Error	LNK2019	unresolved external symbol SSLeay_version referenced in function "int __cdecl ace_main_i(int,char * * const)" (?ace_main_i@@YAHHQEAPEAD@Z)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\Main.obj	1	

Error	LNK2019	unresolved external symbol CRYPTO_num_locks referenced in function "void __cdecl OpenSSLCrypto::threadsCleanup(void)" (?threadsCleanup@OpenSSLCrypto@@YAXXZ)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(OpenSSLCrypto.obj)	1	

Error	LNK2019	unresolved external symbol CRYPTO_set_locking_callback referenced in function "void __cdecl OpenSSLCrypto::threadsCleanup(void)" (?threadsCleanup@OpenSSLCrypto@@YAXXZ)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(OpenSSLCrypto.obj)	1	

Error	LNK2019	unresolved external symbol CRYPTO_THREADID_set_numeric referenced in function "void __cdecl threadIdCallback(struct crypto_threadid_st *)" (?threadIdCallback@@YAXPEAUcrypto_threadid_st@@@Z)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(OpenSSLCrypto.obj)	1	

Error	LNK2019	unresolved external symbol CRYPTO_THREADID_set_callback referenced in function "void __cdecl OpenSSLCrypto::threadsCleanup(void)" (?threadsCleanup@OpenSSLCrypto@@YAXXZ)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(OpenSSLCrypto.obj)	1	

Error	LNK2019	unresolved external symbol EVP_CIPHER_CTX_init referenced in function "public: __cdecl ARC4::ARC4(unsigned int)" (??0ARC4@@QEAA@I@Z)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(ARC4.obj)	1	

Error	LNK2019	unresolved external symbol HMAC_CTX_init referenced in function "public: __cdecl HmacHash::HmacHash(unsigned int,unsigned char *)" (??0HmacHash@@QEAA@IPEAE@Z)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(HMACSHA1.obj)	1	

Error	LNK2019	unresolved external symbol HMAC_CTX_cleanup referenced in function "public: __cdecl HmacHash::~HmacHash(void)" (??1HmacHash@@QEAA@XZ)	worldserver	C:\sursa\azerothcorea\build\src\server\worldserver\shared.lib(HMACSHA1.obj)	1	

Error	LNK1120	8 unresolved externals	worldserver	C:\sursa\azerothcorea\build\bin\Release\worldserver.exe	1

**Comment by dunjeon** [comment]
Download OpenSSL 1.1.1a

**Comment by maradaka** [comment]
It works! Thank you!

**Comment by FrancescoBorzi** [comment]
this thread looks more suitable for stackoverflow
