### ISSUE TITLE
[Shaman] Elemental Mastery aura (16166) is consumed by instant cast spells.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12264]
https://github.com/chromiecraft/chromiecraft/issues/3713
https://github.com/chromiecraft/chromiecraft/issues/3017

### Current Behaviour

Aura 16166 is consumed by instant cast spells.

### Expected Blizzlike Behaviour

>Cast time of your next Lightning Bolt, Chain Lightning or Lava Burst spell is reduced by 100%.

### Source

I've found no evidence implying that this aura is consumed by instant cast spells.

### Steps to reproduce the problem

`.aura 16166`
cast any instant cast spell such as Earth Shock 8042

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10

**Comment by tkn963** [comment]
I created a bug report for this in May but would be happy if it got some attention because it's a real issue.

Linking the issue I created so that the person who creates a PR for it can set to close both reports.

https://github.com/azerothcore/azerothcore-wotlk/issues/10903

**Comment by Gultask** [comment]
@tkn963 Ah, sorry about that. I forgot to check for duplicates before making the report. Thanks for pointing it out.
