### ISSUE TITLE
[Fishing] Character remain stuck in fishing channeling after clicking the bobber prematurely

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12260]
https://github.com/chromiecraft/chromiecraft/issues/3701

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

[Fishing](https://wowgaming.altervista.org/aowow/?spell=7738) keeps channelling after clicking the bobber before the fish get hooked, making character stuck in animation until he recasts fishing or other channelling spell.

**Note:** This does not affect cancelling fishing by moving.

https://www.youtube.com/watch?v=V-CLBW1u2uw

### Expected Blizzlike Behaviour

All animations and channelling should be naturally cancelled once the player stop fishing (for any reason)

### Steps to reproduce the problem

1. `.additem 6256`
2. `.learn 7620`
3. cast Fishing
4. click the bobber before a fish is hooked
5. see that the channeling is not cancelled

### Extra Notes

https://user-images.githubusercontent.com/100873791/176953966-f1728270-2c95-4852-8e30-569c6345fc81.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by FallenDev** [comment]
I will add that this is still an active bug as of commit: [fix(Core/Movement)](https://github.com/azerothcore/azerothcore-wotlk/commit/0f4e8f07ff097586ae1162b231f2afb7e6fb0c8d) (12/11/2022) 

To reproduce:
1. Cast Fishing
2. Click the bobber before a fish is hooked
3. Channeling will then not cancel unless fishing is cast again or another channeling spell

Operating System: Windows Server 2022

Modules:
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-autobalance](https://github.com/azerothcore/mod-autobalance)
[mod-solocraft](https://github.com/azerothcore/mod-solocraft)
[mod-solo-lfg](https://github.com/azerothcore/mod-solo-lfg)
[mod-anticheat](https://github.com/azerothcore/mod-anticheat)
[mod-accountbound](https://github.com/noisiver/mod-accountbound)
[mod-weekendbonus](https://github.com/noisiver/mod-weekendbonus)
