### ISSUE TITLE
Incorrect horde graveyard for Darnassus 

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#12277]
### Current Behaviour

When dieing as horde in Darnassus you are ported to the Southern Darkshore graveyard
![image](https://user-images.githubusercontent.com/68164076/177011055-c90b3a5c-1cc0-4fb0-979c-5ec30536c17b.png)

### Expected Blizzlike Behaviour

You should spawn at the Teldrassil graveyard by Dolanaar

### Source

https://classic.wowhead.com/teldrassil#comments:id=2846130
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/46077429?page=1
https://wowpedia.fandom.com/wiki/Darnassus scroll down to patch changes.
![image](https://user-images.githubusercontent.com/68164076/177011354-e0e41db5-f8f6-4274-a895-9536641ec525.png)

### Steps to reproduce the problem

1. be horde
2. .tele darn
3. .gm off
4. die a glorious death worthy of songs and notes in the history books detailing your heroic stand again the tyrannical elves
5. release 
6. spend 10 minutes running back to your corpse, or less depending on how long you have to wait for the boat

### Extra Notes

I like turtles

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

windows 10

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by acidmanifesto** [comment]
currently dolnnar is set to faction 469, alliance. i will do a pr shortly to correct it after testing.
