### ISSUE TITLE
[ZG] Jin'do the Hexxer - Boss shouldn't reset so quickly

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12275]
### Current Behaviour

Boss resets immediately upon breaking combat.

### Expected Blizzlike Behaviour

Boss should emote a dance for a couple of seconds before returning to his original position and resetting. This is due to Brain Wash Totem working even when the player runs solo.

Everything besides the boss should reset first. Totems and Shades should disappear, but the boss stays for a couple of seconds before returning.

I believe it's 5 seconds between the first "reset" that starts the emote and the hard "reset" that properly resets the boss.

### Source

https://youtu.be/rTFP5VYf3zw?t=126 A full reset happening. The "soft resets" happen throughout the video.

### Steps to reproduce the problem

1. `.go c 49655` solo.
2. Engage the boss, see if resets are occurring immediately

### Extra Notes

Low-prio due to being mainly a solo problem.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/16f2983307aeeb39bd263e3e923c93c16488444f

### Operating system

Windows 10

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12233
