### ISSUE TITLE
Midsummer braziers stacking in capitol cities

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#12303]
Orginal Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/3677

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

![image](https://user-images.githubusercontent.com/58770211/175660372-9db122af-870d-44f9-9136-c9d34dca62e7.png)
Bonfires seems to have multiple spawns stacked and slightly rotated

### Expected Blizzlike Behaviour

Only one bonfire should be up.

### Steps to reproduce the problem

1. head to an enemy captiol city fire
2. steal the flame
3. watch the fire spawn an additional red fire
4. Repeat

### Extra Notes

Not going lie, this looks badass

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04
Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
They are literally  stacking now. 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/02844cb0-d4e7-434d-866c-30c2779d6754)

**Comment by sudlud** [comment]
can't repdroduce on 3a31411b9

Level 80 Horde Troll Priest
.gm off
.event start 1
teleport to ironforge fire
.go xyz -4706.378 -1221.6877 501.65958 0
click on flame

observe getting quest item "flame of ironforge" into inventory
get some damage from the fire

observe no additional bonfire beeing spawned

---

it looks like this got fixed with PR #16618

**Comment by sudlud** [comment]
so I think this issue and chromiecraft/chromiecraft/issues/3677 could be closed as fixed with PR #16618

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/c0bbb5248354dadad653f20a4d4bdbd70af0df4c
