### ISSUE TITLE
Glyph of Kilrogg

### ISSUE THREAD

**Issue by Cinnamohn** [azerothcore/azerothcore-wotlk#12300]
### Current Behaviour

Glyph of Kilrogg does not apply the speed increase correctly, and flight is slower than intended.

### Expected Blizzlike Behaviour

With the glyph, Eye of Kilrogg should move faster on ground than without it, and flight should use the speed bonus from the dbc.

### Steps to reproduce the problem

1. .tele crystalsong (anywhere with flight enabled)
2. .cast 126 (Eye of Kilrogg) - It moves at the correct speed
3. Cancel the channel
4. .addaura 58081 to self
5. Cast it again - It moves slower on ground and can fly at the same speed

### Extra Notes

spell_warl_eye_of_kilrogg is manually adjusting its speed and applying flight, which overrides the glyph's effect (58081). There is also an unused spell called Eye of Kilrogg Passive (DND) (58083) that does what the script is failing to do properly.

### AC rev. hash/commit

5c53af2

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
Already fixed.
