### ISSUE TITLE
Irondeep Shaman - wrong lvl for 60-AV

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#12310]
Originally reported at https://github.com/chromiecraft/chromiecraft/issues/3732

### Current Behaviour

wrong level / 63-64

### Expected Blizzlike Behaviour

Quick Facts
-- Level: 53 - 54

### Source

https://classic.wowhead.com/npc=11600/irondeep-shaman

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

**Comment by acidmanifesto** [comment]
53 to 54 in wotlk.
https://www.wowhead.com/wotlk/npc=11600/irondeep-shaman
