### ISSUE TITLE
[ZG] Broodlord didn't level up after a death player

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12323]
### Current Behaviour

When a player die, broodlord didn't level up

### Expected Blizzlike Behaviour

Broodlord should level up after a player death. He will grow bigger, deal more damage and take less physical damage

### Source

https://classic.wowhead.com/guides/bloodlord-mandokir-zul-gurub-strategy

### Steps to reproduce the problem

1. Engage Bloodlord with 3 char
2. Wait Threatening gaze and don't do nothing. He will charge you, and let him kill the char
3. Look if he level up

### AC rev. hash/commit

[32ba21d](https://github.com/azerothcore/azerothcore-wotlk/commit/32ba21d02900bc4f236af029c24ac2de27390db5)

### Operating system

Windows 11

**Comment by Luckdemon** [comment]
Bloodlord Mandokir is supposed to level up after 3 kills, not one.

https://youtu.be/76NOEKuRBdY?t=163
This video shows a dead player and no level up

also the wowpedia page for ZG classic: https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic)
Level Up — Bloodlord Mandokir levels up every time he kills 3 players. Permanently increases size and damage done by 10%.

When we tested ZG a few days ago, he leveled up correctly after 3 kills.

**Comment by benjymansy123** [comment]
Also in the provided [source](https://classic.wowhead.com/guides/bloodlord-mandokir-zul-gurub-strategy), they mention this:
> However, this comes at a price: Every three players killed will "level" Mandokir up (with a full leveling animation and even a grats from [Jin'do the Hexxer](https://classic.wowhead.com/npc=11380/jindo-the-hexxer)!).
