### ISSUE TITLE
Hunter traps have trigger issues

### ISSUE THREAD

**Issue by q67732897** [azerothcore/azerothcore-wotlk#12332]
### Current Behaviour

The trigger of the hunter trap is not normal, sometimes it can trigger, sometimes it can't trigger

### Expected Blizzlike Behaviour

Hunter Trap can be triggered by monsters in any situation

### Source

[https://youtu.be/DPM1iHSu_oo](url) 
Here is the demo video

### Steps to reproduce the problem

Find monsters and place more traps, sometimes the traps will not trigger

### AC rev. hash/commit

AzerothCore rev. ff3e53ec0e95 2022-07-09 01:36:37 +0800 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80029
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in data/maps. Total size: 291014951 bytes
vmaps directory located in data/vmaps. Total size: 658130721 bytes
mmaps directory located in data/mmaps. Total size: 2320900676 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autobalance
- mod-cfbg
- mod-eluna
- mod-npc-buffer
- mod-npc-free-professions
- mod-solo-lfg
- mod-transmog

### Operating system

windows 10

**Comment by WORISX** [comment]
I am having the same issue, the traps usually won't trigger, im also on AzerothCore rev. ff3e53ec0e95, specially on frost trap, that spell won't even trigger in most of the cases

**Comment by Stump876** [comment]
I suggest posting in https://github.com/azerothcore/azerothcore-wotlk/issues/11432 to reopen, instead of creating a new issue.

**Comment by benjymansy123** [comment]
Is the response not to open a new issue if the original issue was closed with a PR/commit?

**Comment by Stump876** [comment]
I don't think so. Not if the PR didn't fix the issue. If it's a new issue then yes. But I could be wrong, now you got me wondering. I haven't really dug into this to check it out. But I've been seeing it pop up a lot recently.

**Comment by Gultask** [comment]
I think I may have found a good spot to reproduce it.
`.go xyz -0.390734 -80.707031 -41.333252 542 3.919968`

I'll pull the latest changes and try again. If it's consistent I'll go ahead and confirm the issue.

**Comment by mpfans** [comment]
@UltraNix

**Comment by WORISX** [comment]
It is not only about triggering @UltraNix there is also another issue inside this, sometimes the trap will trigger without casting it's effect, IE, frost trap gameobject will be spawned 13809 (frost trap spell) will trigger gameobject (164639) and if a creature or a player is getting on the radius gameobject will be activated and despawned, but won't cast nothing at all, probably related to LOS or probably another issue that isn't related to how the LOS checks are being made, CastSpell is involved on this.

**Comment by mpfans** [comment]
@q67732897 @Gultask @WORISX   Please test as soon as possible
