### ISSUE TITLE
[ZG] Jin'do the Hexxer - A couple of very minor remaining issues regarding resets.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12338]
### Current Behaviour

1. When the boss starts to reset and begins his dancing animation, he cannot be attacked and just evades instead until he returns to his spawn point.
2. When running solo, Brain Wash Totem will not cast its spell.

### Expected Blizzlike Behaviour

1. When he resets, he starts dancing and everything else (totems, shades) despawn, but he can still be attacked and is able to restart combat if the players wishes to do so.
2. When running solo, Brain Wash Totem should still work.

### Source

https://youtu.be/rTFP5VYf3zw?t=126 A full reset happening. The "soft resets" happen throughout the video.

### Steps to reproduce the problem

1. `.go c 49655` solo, engage boss
2. wait for a Brain Wash Totem cast, see if it works.
3. after the Brain Wash wears off, try to attack the boss to restart combat (you should have a 4-5s window before he completely resets)

### Extra Notes

**Bugs 1 and 2 SHOULD NOT BE FIXED SEPARATELY or there will be regressions.** The grace period in the resets is because the Brain Wash Totems should MC solo players. It allows them to restart combat with the boss, so that the encounter is possible solo.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/1d6dc750fa37184525f3de2837cbd57230ee62ab

### Operating system

Windows 10

**Comment by Maelthyrr** [comment]
I don't understand, the boss shouldn't mind control the player if there  are only one player alive ?

**Comment by Gultask** [comment]
Jin'do is a bit unique as in he **does** Mind Control solo players, but his unique reset behaviour allows for solo players to resume combat after they've been mind controlled.

However, this issue is just cosmetic and his current behaviour allows him to be soloed without any problems, so I'm adding the trivial label before I go to sleep, since he is fine now, just deviating a bit from the 'blizzlike' behavior.

So this shouldn't be worked on.
