### ISSUE TITLE
worldserver exception

### ISSUE THREAD

**Issue by WowChenEd** [azerothcore/azerothcore-wotlk#12343]
### Current Behaviour

1. first login in
2. create a paladin
3. worldserver console show
 minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(42) : Assertion failed: c >= -1 && c <= 255
![image](https://user-images.githubusercontent.com/17425810/178132675-827df952-7f1a-477a-8d93-5403189e4438.png)

### Expected Blizzlike Behaviour

no exception show

### Steps to reproduce the problem

1. first login in
2. create a paladin
3. worldserver console show

### AC rev. hash/commit

AzerothCore rev. 1d6dc750fa37 2022-07-09 21:38:58 +0000 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.74.0
Using MySQL version: 80029
Using CMake version: 3.23.1
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/wow335-server-ac/data/maps. Total size: 291014951 bytes
vmaps directory located in E:/wow335-server-ac/data/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/wow335-server-ac/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

windows 10 x64

### Custom changes or Modules

None

**Comment by acidmanifesto** [comment]
What race?

**Comment by WowChenEd** [comment]
> What race?

BLOOD ELF

**Comment by WowChenEd** [comment]
![image](https://user-images.githubusercontent.com/17425810/178141301-6debe664-ec4a-44c0-bf38-dabb9ccd39fc.png)
i rebuild it, now it crashed when start wow .

**Comment by acidmanifesto** [comment]
We will need to know a list of all modules used and custom changes made to be able to assist you. So far no one is having that issue. What is the link to the latest revision of azerothcore you are using?

**Comment by WowChenEd** [comment]
> We will need to know a list of all modules used and custom changes made to be able to assist you. So far no one is having that issue. What is the link to the latest revision of azerothcore you are using?

azerothcore version is : 1d6dc750fa37184525f3de2837cbd57230ee62ab
transmog version is : a381c75e3f189a0a03ac51766cc5dfbb975223e1
both are latest version.

**Comment by Kitzunu** [comment]
can't repro
