### ISSUE TITLE
wrong npc creature

### ISSUE THREAD

**Issue by WowChenEd** [azerothcore/azerothcore-wotlk#12345]
### Current Behaviour

![image](https://user-images.githubusercontent.com/17425810/178132896-98bf556d-6d06-4da0-8d50-daba2d13521d.png)

shattered sun warriors are warlock's ghost ?

### Expected Blizzlike Behaviour

shattered sun warriors should be blood elf.

### Steps to reproduce the problem

1. go to 
![image](https://user-images.githubusercontent.com/17425810/178133001-641f38c5-2cf3-413e-8e80-7880309bb698.png)

### AC rev. hash/commit

AzerothCore rev. 1d6dc750fa37 2022-07-09 21:38:58 +0000 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.74.0
Using MySQL version: 80029
Using CMake version: 3.23.1
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/wow335-server-ac/data/maps. Total size: 291014951 bytes
vmaps directory located in E:/wow335-server-ac/data/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/wow335-server-ac/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

windows 10 x64

### Custom changes or Modules

None

**Comment by benjymansy123** [comment]
[Known issue](https://github.com/azerothcore/azerothcore-wotlk/issues/10795)
