### ISSUE TITLE
Eluna Player:ResetPetTalents() will case worldsever error shutdown after the server change the code

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#12363]
### Current Behaviour

when I use eluna  Player:ResetPetTalents() ,the server down. but 6mouth before it has no problem.
I try use game NPC that training the hunter to reset pet's talent, the server ok.
I reporrt the bug to eluna, they confirmed the issue , but they think this is world server problem:

the error message in DBErrors.log: 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND spell IN (63900,62765,62760,62759,62762,62758,52825,53203,53182,53477,5347' at line 1
Error while parsing SQL. Core fix required.

See the eluna issues link    https://github.com/azerothcore/mod-eluna/issues/51

### Expected Blizzlike Behaviour

the new code will compatible with eluna  command  Player:ResetPetTalents() , and worked just like at hunter training NPC reset pet's talents.

### Steps to reproduce the problem

run  eluna script  Player:ResetPetTalents() , the server down.

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53 2022-05-25 05:00:05 -0300 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1l 24 Aug 2021 (library: OpenSSL 1.1.1l 24 Aug 2021)
Using Boost version: 1.77.0
Using MySQL version: 80028
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 54345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2107913100 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

debian 11 x64

### Custom changes or Modules
eluna
_No response_

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/184525858-5bca96b9-3b62-4c9f-bb38-7ecbaab65843.png)
Can not reproduce anymore. Thanks @Nefertumm for looking into it.
If it keeps happening for you, please provide details about your environment and comment here @kissingers .
