### ISSUE TITLE
problem in emulator azerothcore rev. 1d6dc750fa37+2022-07-09 (master branch)

### ISSUE THREAD

**Issue by guason9721** [azerothcore/azerothcore-wotlk#12364]
### Current Behaviour

when a mj enters an icc or halion gang the worldserver closes without leaving an error in the server.text it only closes, that only happens when an mj enters an instance of icc or rubi tabernacle. what could be the error before updating the emulator I could enter now I enter and the world server closes, I put "gm off" but when I kill a BOSS the worldserver still closes....

### Expected Blizzlike Behaviour

You should be able to enter to be able to control the players

### Steps to reproduce the problem

1. enter a gang with gm off, when killing a boss the server closes well that happens on my server.
2. after killing the BOSS it closes and no error appears so you can check the problem

### AC rev. hash/commit

azerothcore rev. 1d6dc750fa37+2022-07-09 (master branch)

### Operating system

windows 10

**Comment by zylok520** [comment]
1d6dc750fa37_worldserver.exe_[11-7_17-1-26].dmp

**Comment by Kitzunu** [comment]
Cannot reproduce
