### ISSUE TITLE
Knight's talent skills Spiritual Attunement work with wrong logic 

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#12362]
### Current Behaviour

At the  \acore\src\server\game\Entities\Unit\Unit.cpp     7498 line

// Spiritual Attunement
                    case 31785:
                    case 33776:
                        {
                            // if healed by another unit (victim)
                            if (this == victim)
                                return false;

                            // dont allow non-positive dots to proc
                            if (!procSpell || !procSpell->IsPositive())
                                return false;

                            // heal amount
                            basepoints0 = int32(CalculatePct(std::min(damage, GetMaxHealth() - GetHealth()), triggerAmount));
                            target = this;

                            if (basepoints0)
                                triggered_spell_id = 31786;
                            break;
                        }

where  if (!procSpell || !procSpell->IsPositive())  will case the direct healing spell not effect. only continuous healing spell will work.

another is std::min(damage, GetMaxHealth() - GetHealth())  at 335 I remember when the knight's HP is full,  the  healing spell still  add mana . So i think std::min might change to std::max

link before I submited  https://github.com/azerothcore/azerothcore-wotlk/issues/11868

### Expected Blizzlike Behaviour

 The direct healing spell will work normal when Spiritual Attunement talent selected.

### Steps to reproduce the problem

1 Knight click 2 point spiritual attunement talents.
2 try use direct  spell  to heal knight ,mana don't add.

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53 2022-05-25 05:00:05 -0300 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1l 24 Aug 2021 (library: OpenSSL 1.1.1l 24 Aug 2021)
Using Boost version: 1.77.0
Using MySQL version: 80028
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 54345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2107913100 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

debian 11 x64

**Comment by Nyeriah** [comment]
Could you provide some sources to support this claim? Both of your statements seem wrong.

![image](https://user-images.githubusercontent.com/47818697/178302781-9430de39-c1c2-4389-a56a-635270656da5.png)

Countless sources also claim overhealing should be ignored. So if you're at full HP you get no mana, but if you're at 80% you'll get the proportional amount for how much you were healed.

**Comment by kissingers** [comment]
The main problem is " !procSpell || !procSpell->IsPositive()",  where  "!procSpell"  not fit the onetime healing like "Holy Light", "Flash of Light" ,"Healing Touch", "Flash Heal"... , only fit the continuous healing like "Rejuvenation", "Renew".  This is bug. might "procSpell" meams continuous healing, are there a "DirectSpell" to judge no continuous healing?

The amount healed,  it's controversial effective healed or over healed, so second problem not sure.

**Comment by Nyeriah** [comment]
That's just the name of the variable that stores the spell that caused the spirtual attunement to proc, it's not actually a proc spell

**Comment by kissingers** [comment]
I think " !procSpell || !procSpell->IsPositive()"  may change to "!procSpell && !procSpell->IsPositive()".

**Comment by Nyeriah** [comment]
```!procSpell``` is a null pointer check, it's unpredictable what could happen without it, the problem isn't there

**Comment by kissingers** [comment]
but when I  // the two line, all  "Holy Light", "Flash of Light" ,"Healing Touch", "Flash Heal"... work ok, if not, they doesn't work. only   "Rejuvenation", "Renew" work every jump healing.
>  // if (!procSpell || !procSpell->IsPositive())
>  //                           return false;

**Comment by Nyeriah** [comment]
@UltraNix opinions? proc flags maybe?

**Comment by UltraNix** [comment]
`if (!procSpell || !procSpell->IsPositive())` that check must be there to be sure that talent procs only from spells and only from positive spells.

**Comment by UltraNix** [comment]
![obraz_2022-07-12_083601136](https://user-images.githubusercontent.com/80540499/178424701-7ae8a809-45f4-4cd1-888f-c1bb88308818.png)
Tested with Healing Touch which is direct healing spell - works okay.
I see no bug here.

**Comment by Nyeriah** [comment]
Okay, thanks for checking

Thanks for the report but it seems this is working as intended, there are no issues currently

**Comment by TheDdraig** [comment]
Just tested this, it does not work tested on holy paladin and druid no idea how this person got it to work, but it also doesnt work on CC and theres been others who have tested and confirmed. It's wise to test on all capable healing classes but as typing this it does not work. Dunno what UltraNix is smoking, but my combat log shows the heal but not the gain of mana so unless theres a fix that has been done and has not been shared, yeah it doesnt work.

**Comment by kissingers** [comment]
Yes, I test again, all direct heating doesn't work, but hot heating ok, just pure core no any other plusin,  So I think might
if (!procSpell || !procSpell->IsPositive())
where procSpell  means "Process Spell" "(Continuous Spell )"   , not an "Immediately Spell" , so  "Immediately Spell" doesn't work.

**Comment by w5860363** [comment]
@Nyeriah Does not work, the skill does not work in combat, it works in non-combat situations
So I think we should reopen the issue
