### ISSUE TITLE
Feature: 32 bit stats for players and pets (currently 16 bit) [$100]

### ISSUE THREAD

**Issue by MellianStudios** [azerothcore/azerothcore-wotlk#12386]
### Describe your feature request or suggestion in detail

Hello

DISCLAIMER: I didn't test each class and each pet so i can't say for sure that this applies to all stats but probably it does.

So as title says currently all stats (except damage but that's not really a stat) are 16 bit so for example if player gets more than 65535 crit it overflows and reset to 0. I'm not sure if AC is supposed to be blizzlike focused or universal because if blizzlike then this change has no meaning no benefit and only causes slightly more RAM usage and that would influence decision if this will be accepted. However that impact is probably negligible.

I'm not exactly sure how to do it but i think it just requires to go through code and change type of variables related to stats to int 32 and then test ingame that it works for all player and pet stats.

This will be placed as bounty. Thank you.

**Comment by acidmanifesto** [comment]
We need a link to the bounty.

**Comment by heyitsbench** [comment]
> We need a link to the bounty.

https://app.bountysource.com/issues/109973073-feature-32-bit-stats-for-players-and-pets-currently-16-bit

**Comment by acidmanifesto** [comment]
@Helias @FrancescoBorzi  can you attach the bounty to the issue ^^. I am not certain how to do that or how it is is done or if it is linking needing to be done on bountysource which i do not have a account for.

**Comment by heyitsbench** [comment]
Typically in my experience it was usually a bot that edited the issue to attach it, but that bot hasn't been working (I believe since bountysource began having issues last year)

**Comment by acidmanifesto** [comment]
bot stuff is out of my area of responsibility and access. we will need to rely on the maintainers to ensure it is appropiately linked. this way both the bounty make and bounty claimer are documented.

**Comment by Helias** [comment]
the bounty bot does not work properly sometimes, anyway, the bounty is there, so anyone can claim the bounty if he fixes this issue and here the label bounty is already present.
I've just added the 100 $ in the title

**Comment by acidmanifesto** [comment]
> the bounty bot does not work properly sometimes, anyway, the bounty is there, so anyone can claim the bounty if he fixes this issue and here the label bounty is already present. I've just added the 100 $ in the title

ok if we are good to go i will go ahead and green like the review and merge
