### ISSUE TITLE
Table character.account_tutorial not storing data

### ISSUE THREAD

**Issue by rodriguescr** [azerothcore/azerothcore-wotlk#1238]
##### SMALL DESCRIPTION:

Characters created have to read tutorials all the times thei log in. AC not storing that they are already read.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Tutorials would be read just the first time the character log in.

##### CURRENT BEHAVIOUR:

When you login, all the times, you have to click to close all tutorials as the AC server don't store the info that they are already read in the DB table.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Compile and start AC normally.
2. Login to the game and close all tutorials.
3. Close the game and login again.
4 . All tutorials reapeear.

##### EXTRA NOTES:

It works on Mangos and TrinityCore.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit aa949479d75f1060a622004ea75c2b15e3e999d7 (HEAD -> master, origin/master, origin/HEAD)

##### OPERATING SYSTEM:

Ubuntu 16.04

##### MODULES:

none

##### OTHER CUSTOMIZATIONS:

none

**Comment by wetbrownsauce** [comment]
I can only replicate this with the config option:
`GM.StartLevel = 80`

When starting from 1, leveling to 80, clearing all tutorials and restarting client, tutorials stay gone. When instant 80, clear tutorials and restarting client, tutorials all come back. 

Might be worth testing on a non-gm account with `StartPlayerLevel = 80` to see if this is specific to GM accounts or all instant-80 players

**Comment by rodriguescr** [comment]
Hi,
I tested with normal player account. It still won't populate the account_tutorial table. I've leveld the character to level 7 testing some quests, still didn't populated.

**Comment by BarbzYHOOL** [comment]
@wetbrownsauce check your table if it's empty or not though

btw this table is called "account_tutorial" and is in "characters" DB, dunno if that makes any sense

**Comment by wetbrownsauce** [comment]
@BarbzYHOOL 

>EDIT:: Double checked between my level 1 server and instant-80 server. account_tutorial table is populated in the start level 1 server but empty in the instant-80 server. I've still only tested the instant-80 with GM accounts though.

**Comment by BarbzYHOOL** [comment]
ok, @Nefertumm talked about this thing about instant level 80 issue with achievements, and apparently it's the same issue with tutorials

I bet it's hardcoded for each case in top of that :(

**Comment by cjl3230** [comment]
The problem seems to have reappeared.
