### ISSUE TITLE
[ZG] Bloodlord Mandokir - Intimidating Shout is not being cast.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12380]
### Current Behaviour

Boss isn't casting the Intimidating Shout after the random charge that occurs every 30-40s

### Expected Blizzlike Behaviour

Boss should always cast Intimidating Shout after the random Charge.

### Source

See: https://github.com/azerothcore/azerothcore-wotlk/issues/11749

### Steps to reproduce the problem

1. `.go xyz -12212 -1959 133 309`
2. Kill Vilebranch Speaker
3. engage boss, wait until the random charge happens and see if he shouts

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask Cannot reproduce it. Works everytime for me okay.

**Comment by Gultask** [comment]
Mhm. It seems exclusive to the CC PTR and not locals. I can't imagine where the problem lies.
