### ISSUE TITLE
[ZG][SPELL][SHAMAN]  zandalarian hero charm wrong trigger if used with Chain* spells

### ISSUE THREAD

**Issue by Markus909** [azerothcore/azerothcore-wotlk#12383]
### Current Behaviour

Using this item with a chain lighthing/heals (shaman) it reduces its spell power for every target damaged by the spell (-17, -17, -17, ...)..
If the chain-lighting proc the talent Lightning Ovearload, it also procs double spell power reduction on trinket's bonus .

### Expected Blizzlike Behaviour

Use: [Increases your spell power by 204 for 20 sec. Every time you cast a spell, the bonus is reduced by 17 spell power.](https://wotlk.evowow.com/?spell=24658) (2 minutes cooldown)

The bonus spell power should be reduced only on cast, even an istant cast, but only on casted spells.

### Source

tolltip of trinket   -> https://wotlk.evowow.com/?item=19950

### Steps to reproduce the problem

1. equip the trinket
2. use it to empower your spell power
3. cast a chain-lightning on multi target. 
4. check the buff counter

### Extra Notes

it also remove a stack if the shaman is using Lightning Shield, and be hitted by an enemy.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

windows 10 x64

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
[lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by UltraNix** [comment]
@Markus909 I don't understand the report. -17 is for every target or maybe is multiplicative (-17,-34,-41, etc). If the 1st case, so this is completely blizzlike.

**Comment by Markus909** [comment]
@UltraNix the buff counter lower for every target, instead of every spells.
So, if i cast chain-lightining and i hit 3 target i get -17*3= -51 spell power bonus.

**Comment by UltraNix** [comment]
Okay.
