### ISSUE TITLE
NPC chatting window closes when untargetting the NPC for no target

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#12399]
### Current Behaviour

This seems to be a recent behaviour.
You may talk to a NPC to open a chatting window but whenever you decide to untarget them (ending up with yourself having nothing targetted), the chatting window closes itself.

I promise, I did not hit the `Escape` key on my keyboard.

https://user-images.githubusercontent.com/22718174/178861945-551e3aae-0fda-4ba2-a7fc-c212101ca690.mp4

### Expected Blizzlike Behaviour

Untargetting them should not close the window because it doesn't close if you target anything else than the NPC you've got the discussion window opened.

### Source

I did manage to replicate how it used to work using the following.
AzerothCore rev. 92aec9fc3e8f 2022-06-22 20:21:52 +0000 (HEAD branch) (Win64, RelWithDebInfo, Static)
Git commands I used to rollback all the way there:
`git clone https://github.com/azerothcore/azerothcore-wotlk .`
`git checkout 92aec9f`
`git reset --hard`

Results when I tried:

https://user-images.githubusercontent.com/22718174/179337168-074300e2-3781-40a2-b64b-6d203e1d136e.mp4

### Steps to reproduce the problem

Clear cache.
Disable all addons (I know, my recording has addons, I also did try without addons).

This option has to be unchecked.
![image](https://user-images.githubusercontent.com/22718174/178862242-82e32b3c-4d68-4f22-a246-55707b885c3c.png)

Right click to talk to a NPC that has some form of dialog window like these.
`.go c 35194`
![image](https://user-images.githubusercontent.com/22718174/178863729-373a1ca4-7c07-46c6-8e84-e89bfaec0874.png)

In my recordings, I used this NPC.
`.go c 79714`

### AC rev. hash/commit

First saw on ChromieCraft using the following.
AzerothCore rev. 35dfcf588f62+ 2022-07-12 11:33:26 +0000 (master branch) (Unix, RelWithDebInfo, Static)

Reproduced on my local AzerothCore rev. 02fa20b6380b 2022-07-13 20:54:01 +0000 (master branch)

### Operating system

Windows 10 x64

### Custom changes or Modules

No modules on my local AC.
Also experienced on ChromieCraft.

**Comment by tkn963** [comment]
I can confirm this as an issue.
