### ISSUE TITLE
[AQ20] Anubisath Guardian do not cast any abilities

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12416]
### Current Behaviour

Mob: https://wowgaming.altervista.org/aowow/?npc=15355
Anubisath Guardian do not cast any abilities

### Expected Blizzlike Behaviour

Anubisath Guardian should cast multiple random abilities.

### Source

https://wowwiki-archive.fandom.com/wiki/Anubisath_Guardian
https://classic.wowhead.com/npc=15355/anubisath-guardian#abilities;mode:20player

### Steps to reproduce the problem

.go c id 15355

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/3762

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10 Pro

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by kerricsson** [comment]
I'll add important note - they should cast not absolutely random, but paired raidom abilitites - https://forum.elysium-project.org/topic/22965-aq20-raid-guide-by-sheepler/ - Anubisath Guardian: These guys are like AQ40 ones in mechanics, but slightly easier. They have one spell from 5 pairs of spells:
-Meteor (AOE dmg reduced by # of targets it hits) or Plague (1 person gets plague (AOE Dot, like Hakkar's corruption), he runs away from raid and gets extra heals)
-Shadowbolt Volley (Hits ranged-only for moderate dmg (1k), ranged come closer) or Thunderclap (2k dmg, melee beware of your HP)
-Reflect Magic: Frost+Shadow or Arance+Fire.
-Explode or Enrage: At 10% or so they start exloding - Burn them down in both cases.
-Summons adds: Warrior (Thunderclap, Knockback (no threat loss)) or Swarmguard (Cleave). Throw grenades on summon. Can be feared/stunned. Kill adds after Guardian.

And https://classic.wowhead.com/npc=15355/anubisath-guardian#comments:

"I think the possibilities are not completely random.  They seem to come from different "tables", and there's one ability from each table.
There's a "reflect" table, which determines whether the mob has Arcane/Fire reflect or Shadow/Frost reflect.
There's an "AoE" table, which determines whether the mob has Shadowstorm (hits distant targets) or Thunderclap (hits close targets).
There's an "affliction" table, which determines what the mob casts on random party members: Meteor (raid should clump up) or Plague (raid should spread out).
There's a "summon" table, which determines what mobs"

**Comment by UltraNix** [comment]
@Maelthyrr 
![obraz_2022-08-06_182013982](https://user-images.githubusercontent.com/80540499/183257390-30b6da11-0890-449e-a312-e50a3e297783.png)
Works okay to me.

**Comment by Nyeriah** [comment]
It was fixed here: https://github.com/azerothcore/azerothcore-wotlk/pull/12537

I am sorry
