### ISSUE TITLE
[AQ20] Buru the Gorger - Missing animation for phase 2 transition.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12417]
### Current Behaviour

- [ ] No animation for phase 2 transition.

### Expected Blizzlike Behaviour

- [ ] Has an animation when changing to phase 2 where its carapace explodes.

### Source

https://youtu.be/t5A1FJmJbPQ?t=212

### Steps to reproduce the problem

1. `.go c id 15370`
2. `.damage 600000`

### Extra Notes

There's an NPC called Buru the Gorger Transform Visual (15507) in the DB and a transform spell.

https://github.com/chromiecraft/chromiecraft/issues/3758

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/cc52712ac12e3d6a16aabcbd13807924c64aeb1e

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask https://youtu.be/mgcGY4lf0qY?t=289
No animation here from wotlk video.

**Comment by Gultask** [comment]
Huh, I thought it was a bug but it seems widespread from looking at several videos.

It even seems that it got fixed in the Cata pre-patch (Nov 2010): https://youtu.be/fka5rJ0JfWk?t=146

**Comment by UltraNix** [comment]
That's why always watch <=wotlk videos, not classic.

**Comment by UltraNix** [comment]
@Gultask Can be closed?

**Comment by Gultask** [comment]
@Nefertumm What do you think? Could this be a client-side issue?

**Comment by Nefertumm** [comment]
If it was a bug but blizzard fixed it later, then our philosophy is fix what blizzard didn't at that time.

**Comment by Nefertumm** [comment]
In addition, if the boss moves, it cancels its phase transition, so I don't think it's a client side issue.

**Comment by UltraNix** [comment]
@Nefertumm In the video I linked I see no movement that cancels that visual. 
It's not about our philosophy - that visual is not present in wotlk and that's all. You can try to sniff, but I'm sure it's not fixable in wotlk.

**Comment by Nefertumm** [comment]
It's an odd behaviour, yes, I tried morphing into Buru and casting the spell and it does the full animation, but for some reason the boss cant cast it fully... Anyway, this is not a priority issue tbh, since it's only visual.

**Comment by UltraNix** [comment]
@Nefertumm I morhped to Buru and casted that spell I still see no visual.

**Comment by Nefertumm** [comment]
Oh well, seems like it's working like a charm, lol 🤣

**Comment by UltraNix** [comment]
I'm closing this.
