### ISSUE TITLE
How to debug event glitch?

### ISSUE THREAD

**Issue by ChibaPet** [azerothcore/azerothcore-wotlk#12427]
### Discussed in https://github.com/azerothcore/azerothcore-wotlk/discussions/12421

<div type='discussions-op-text'>

<sup>Originally posted by **ChibaPet** July 17, 2022</sup>
Two weeks in a row now my kid has fished up 40 Speckled Tastyfish for the Stranglethorn Fishing Extravaganza, but Riggle Bassbait tells her the "We already have all our winners" text, even though no one else has turned it in. I then got the 40 on one of my characters and he gives me the same text, but he'll let me turn in the quest anyway. My daughter doesn't get the turn-in option.

As much as seeing this fixed, I'd like to know how to go about debugging it. Presumably the event state exists in the database, but I'm not finding where, and I'd love pointers. I followed through https://github.com/azerothcore/azerothcore-wotlk/issues/6973 and that led me to GameEventMgr.cpp, and thence to GameEventMgr::SaveWorldEventStateToDB. That suggests I look at CHAR_INS_GAME_EVENT_SAVE and I see that wanting to update acore_characters.game_event_save, but that's empty.

I started using AzerothCore in February so the related changes and database ought to have existed. I'm confused about how the event can be active but the NPC emits a message suggesting it's completed, and how two different characters can get different responses if the event state is saved in one place. Different players/characters have won the competition for the last several weeks so it *has* worked, but last week and this things seem to be a bit strange.

For kicks, I just rebuilt using source from this morning, but it didn't make a difference.

Thanks in advance for clues.</div>

**Comment by tkn963** [comment]
You have to use Discord for questions, not GitHub. If you happen upon an issue then you report that by filling out the pre-defined template for a bug report, unless you decide to fix it yourself in which case you create a pull request by, again, using the pre-defined template.

**Comment by ChibaPet** [comment]
I'd like to start fixing them myself but I was hoping for some guidance. I don't use Discord given a general aversion to non-free software, so if that's an insuperable barrier I'll have to rethink how I'm spending some hobby time. Thank you for the reply.

**Comment by schell244** [comment]
@ChibaPet I just reworked the Stranglethorn Fishing Extravaganza event script, maybe have a look at https://github.com/azerothcore/azerothcore-wotlk/pull/12506

**Comment by ChibaPet** [comment]
@schell244 Thank you, I'm doing a fresh build with your new code, and I'll report back if it resolves the issue.

**Comment by ChibaPet** [comment]
Oh, not merged yet. Whoops. Sorry for the noise. I'll look at snagging patches to test it.

**Comment by schell244** [comment]
( Might be easier to just checkout on the branch https://www.azerothcore.org/wiki/how-to-test-a-pr )

**Comment by Kitzunu** [comment]
Closing as there already is a discussion open for this.

Just going to point to some links tho about debugging
https://www.azerothcore.org/wiki/run-worldserver-and-authserver-in-visual-studio
https://www.azerothcore.org/wiki/how-to-restart-and-debug
