### ISSUE TITLE
[Quest] Time-lost Proto Drake not spawned

### ISSUE THREAD

**Issue by maradaka** [azerothcore/azerothcore-wotlk#1242]
Time-Lost Proto Drake Dragon should be spawned at 4 points in StormPeaks.

Is not spawned after I completed the two quests before the last one.

It should be spawned, so we can kill him and get Time Lost Proto Drake mount

##### CURRENT BEHAVIOUR:
No spawn 

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
Nope.

##### OTHER CUSTOMIZATIONS:
No extra scripts!

Commit - https://github.com/azerothcore/azerothcore-wotlk/commit/6cd70a36a9e67ebaecc694ade39ae829e7da0568
It's the last revision I dont know the number because it says unknown in the console. I attached a picture with the road the Proto should do.
![timelost](https://user-images.githubusercontent.com/32881224/50785087-3a207980-12b8-11e9-8539-7f5c0dbf1bcf.jpg)

**Comment by FrancescoBorzi** [comment]
@maradaka please add your AC version (commit hash)

**Comment by maradaka** [comment]
Sorry, it says Revision unknown but it's the last one!

**Comment by FrancescoBorzi** [comment]
@maradaka you can just copy and paste the commit URL. Choose your version from this list:

https://github.com/azerothcore/azerothcore-wotlk/commits/master

**Comment by maradaka** [comment]
Commit - 6cd70a36a9e67ebaecc694ade39ae829e7da0568

Link: https://github.com/azerothcore/azerothcore-wotlk/commit/6cd70a36a9e67ebaecc694ade39ae829e7da0568

**Comment by maradaka** [comment]
The problem is the spawn points. It doesn't spawn where it should spawn.

**Comment by poszer** [comment]
First .go creature 1975840 ( Kill that dragon / Vyragosa since The spawn timer begins when the corpse despawns ) --> Fly around that marked places from pictures until you get him. 
It's rare mount and you have to wait around 2-8 hours for he's spawn. 
Also, he has a 1/8 chance of spawning instead of a Vyragosa, btw Both of them (Vyragosa/TLPD) fly the same routes.

**Comment by maradaka** [comment]
So you say that it's working?

**Comment by poszer** [comment]
> 
> 
> So you say that it's working?

Im sure, since i already seen him in game, at this location
![screenshot_5](https://user-images.githubusercontent.com/41213210/50786802-dba5cc00-12b4-11e9-8f94-953ddd100ba4.png)

Also i'll test it right now to see will he spawn

**Comment by maradaka** [comment]
Ok, if you test it, i let this open

**Comment by poszer** [comment]
> 
> 
> Ok, if you test it, i let this open

Sure

**Comment by poszer** [comment]
Force killing Vyragosa, for faster spawn and there is he!
Spawned on same guid as Vyragosa 1975840  ( .go creature 1975840 ) <-- Test it :small_airplane: 
1. .go creature 1975840
2. Kill Vyragosa
3. Respawn Vyragosa
4. Repeat all steps, until you teleport near TLPD :smiley: 
![screenshot_6](https://user-images.githubusercontent.com/41213210/50787919-19582400-12b8-11e9-8658-2b6abd106642.png)
![screenshot_7](https://user-images.githubusercontent.com/41213210/50787921-19582400-12b8-11e9-82ca-991b6dfb4f9c.png)

Good luck

**Comment by maradaka** [comment]
Thank you very much!
