### ISSUE TITLE
several pets (and spells calling in pets like water elemental) are not attacking only running to target and doing nothing

### ISSUE THREAD

**Issue by MellianStudios** [azerothcore/azerothcore-wotlk#12431]
### Current Behaviour

testing was done on level 80 on target dummy and/or random icecrown mobs
autocasting for pet spells was always enabled
at the time of testing it was done on latest revision

**pets and spells with issues**

_for some of these pets there was also inconsistent behavior between aggresive defensive and passive some attacked while in passive some didnt, if the pet has issue of not starting attacking even aggresive didnt help_

mage water elemental - runs to target and does nothing, attacks only if i manually click waterbolt, being in combat or attack target prior to summoning doesnt help

dk ghoul with talent master of ghouls - runs to target and does nothing, if i manually click gnaw or claw it start attacking normally from that point , being in combat or attack target doesnt make it to attack, after autocasting huddle it agains stops doing anything

hunter chimaera - runs to target does nothing, start attacking normally after manually casting growl or frostborn breath or bite

druid force of nature - runs to target and does nothing

shaman feral spirit - runs to target does nothing, after manually casting bash starts attacking normally

**pets and spells working**

dk ghoul if talent master of ghouls was not learnt
dk gargoyle
priest shadowfiend
warlock imp
warlock felguard
hunter kurken
hunter core hound
hunter hound
hunter tallstrider
hunter spirit tiger
shaman fire elemental totem

**DISCLAIMER** pets which are not listed were not tested. I cant guarantee 100% accuracy of this testing it took several hours anyway and i dont have time for in depth testing

### Expected Blizzlike Behaviour

I'm not really sure what to say i think it's obvious that this is wrong and they should just start attacking by themselves if they are send to attack

### Steps to reproduce the problem

create any of listed characters and use pet/spell there is nothing special needed to reproduce it

### AC rev. hash/commit

cc52712 refactor (Core/AI)

### Operating system

ubuntu 20.04

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12402

**Comment by maluramichael** [comment]
@MellianStudios the warlock imp is working for you? i created a warlock, learned the imp spell, set him to aggressive and attacked an enemy. He just followes me and does not attack.
