### ISSUE TITLE
Professor Putricide Trap doesn't work in Icecrown Citadel

### ISSUE THREAD

**Issue by Rastrian** [azerothcore/azerothcore-wotlk#12439]
### Current Behaviour

The current professor putricide trap after fight with festergut and rotface is not working, when you enter in the room the trap doesn't activate.
The non activation of this trap also doesn't spawn the professor putricide in the right spot and with the right flags.

### Expected Blizzlike Behaviour

When enter in the trap room, the doors should close and also the insects should drop below the player, after some phases of insects the trap should end and the door for the professor putricide will open.

### Source

This video shows how the trap should work and also the right spot of spawning of Professor Putricide.
[https://www.youtube.com/watch?v=IzPe9MeaUU4](https://www.youtube.com/watch?v=IzPe9MeaUU4)

### Steps to reproduce the problem

1. Create an character
2. Go to Icecrown Citadel
3. Defeat the bosses and go to professor putricide trap entrance
4. Try trigger the trap

### AC rev. hash/commit

35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Docker

### Custom changes or Modules

mod-1v1-arena
mod-anticheat
mod-cfbg
mod-desertion-warnings
mod-eluna
mod-transmog
mod-npc-spectator

**Comment by benjymansy123** [comment]
What was the reason for this being closed?
