### ISSUE TITLE
Cleansed Timberling scaling to player level

### ISSUE THREAD

**Issue by andovcr** [azerothcore/azerothcore-wotlk#12446]
### Current Behaviour

When turning in Planting the Heart (quest ID: 941), the player is rewarded with the Cleansed Timberling Heart (item ID: 5218) which summons a Cleansed Timberling guardian that matches the player's current level.

### Expected Blizzlike Behaviour

The Cleansed Timberling guardian should be a static level 7 regardless of player level.

### Source

[](https://classic.wowhead.com/item=5218/v-timberling-heart#comments)

### Steps to reproduce the problem

1. be level 8 or higher
2. use item ID: 5218 to summon guardian
3. see guardian is above level 7

### Extra Notes

Not sure if I filled this report out correctly, but it's a fairly simple bug.

### AC rev. hash/commit

AzerothCore rev. 02fa20b6380b+ 2022-07-13 20:54:01 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 11 x64

**Comment by Gultask** [comment]
Fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/12625
