### ISSUE TITLE
[Naxxramas] SmartAI causes segmentation fault

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#12465]
### Current Behaviour

Trying to enter the room of Anub'Rekhan in The Arachnid Quarter causes the server to crash. The culprit in this case is `SMART_EVENT_NEAR_PLAYERS`.

### Expected Blizzlike Behaviour

Triggering these SmartAI functions shouldn't cause a crash.

### Steps to reproduce the problem

1. Enter Naxxramas
2. Walk into the room of Anub'Rekhan in The Arachnid Quarter

### Extra Notes

These issues are more than likely not limited to Naxxramas but that's the one that I was told about and have tested.

Debugger when triggering the crash:
![image](https://user-images.githubusercontent.com/5157047/180310156-77e12168-0810-43e4-8442-c1b632915eb8.png)

### AC rev. hash/commit

757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Debian 11 x64

**Comment by q67732897** [comment]
###
[0bb794f32f27_worldserver.exe_[22-7_11-22-57].txt](https://github.com/azerothcore/azerothcore-wotlk/files/9164355/0bb794f32f27_worldserver.exe_.22-7_11-22-57.txt)
I also had the same problem
