### ISSUE TITLE
Quest "Into The Realm of Shadows" - Class: Death Knight

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#12461]
### Current Behaviour

This quest is very simple, kill the knight, steal the horse and deliver.

When you do this and when you are going to deliver the horse, the NPC says that the quest is completed but does not complete the quest.

### Expected Blizzlike Behaviour

[The horse you stole has been taken to the Realm of Shadows. It is there that my dark rider will slay the beast and raise it as a deathcharger. Do you think yourself brave enough to enter the Realm of Shadows in pursuit of the deathcharger?

If you accept, I will transport you to the shadow world. Once there, seek out a dark rider in the open fields south of us. To emerge victorious you must slay him, overtake his deathcharger and return it to Death's Breach. Issue the Horseman's Call should you succeed.]

https://www.wowhead.com/wotlk/quest=12687/into-the-realm-of-shadows

### Steps to reproduce the problem

[![IMAGE ALT TEXT](http://img.youtube.com/vi/rH2-0AuCyZE/0.jpg)](http://www.youtube.com/watch?v=rH2-0AuCyZE "Video")

Class: Death Knight

https://www.wowhead.com/wotlk/quest=12687/into-the-realm-of-shadows

### AC rev. hash/commit

757375f98242

### Operating system

Ubuntu

### Custom changes or Modules

No

**Comment by htc16** [comment]
Could you just confirm this bug?
@UltraNix

**Comment by acidmanifesto** [comment]
I am able to confirm it. Its on my to do list to handle.

**Comment by htc16** [comment]
> I am able to confirm it. Its on my to do list to handle.

Thx

**Comment by mpfans** [comment]
@UltraNix  please

**Comment by mpfans** [comment]
This is the highest priority

**Comment by acidmanifesto** [comment]
So pretty much the runner up info i had jolted down dealt with me looking at 1 of the 3 smartai linked scripted Salazaar the horseman scripts. I suspected the issue may be dealing with smartscripts entry 28653  which is the 1st salazaar the horseman guid, the other being guid 28788 but is a several line smart script . I believe we have a bad spell cast on target with smartscript entry 28653  which gave the credit of the horse delivery. In TC 335 they have it all hard scripted. where we have it all smart scripted. The flaw is with the smart scripting.

In my notes is the following:

Currently in Azerothcore the single line i suspect with the smart script issue is:
```
DELETE FROM `smart_scripts` WHERE `entryorguid`=28653 AND `source_type`=0 AND `id`=0 AND `link`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(28653, 0, 0, 0, 8, 0, 100, 512, 52264, 0, 0, 0, 0, 41, 500, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Salanar the Horseman - On Spell Hit - Despawn Target');
```
Break down would show 
SMART_ACTION_SET_REACT_STATE                    = 8,      // state
SMART_ACTION_THREAT_ALL_PCT                     = 14,     // Threat%
SMART_TARGET_ACTION_INVOKER                 = 7,    // Unit who caused this Event to occur
