### ISSUE TITLE
 SmartAI CPP update case some problem

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#12498]
### Current Behaviour

Many problems occurred after the change of the SmartAI module, including the second step of the Nagrand Arena mission, the blue twins could not be completed. Karazhan's Void Dragon, after opening the red, green and blue doors, can not see the door to the boss line, etc.
I think this might cased by "Commits on Jul 18, 2022"  6ac7dfa
https://github.com/azerothcore/azerothcore-wotlk/commits?author=IntelligentQuantum

### Expected Blizzlike Behaviour

When the source code was not synchronized 10 days ago, it was normal, but after synchronizing master 3 days ago, these problems appeared.

### Steps to reproduce the problem

1 Nagland arena to pick up the task, the second step after playing the blue twin brothers task can not be completed
2 Karazhan Void Dragon, after the door open, can't see the line connection line to the boss.  But the player blocked the middle, the effect is present after try blocking.

### AC rev. hash/commit

AzerothCore rev. 2d4e93dc3e2d+ 2022-07-22 21:20:14 -0400 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100515
Using CMake version: 3.18.4
Compiled on: Linux 5.15.35-3-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 54345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2320900760 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0

### Operating system

debian 11

**Comment by mpfans** [comment]
update to https://github.com/azerothcore/azerothcore-wotlk/commit/a7b27238238fd5683c8da25b0d8c13e3b5cf4a1b

Then retest

**Comment by kissingers** [comment]
I Have update to a7b2723 but still same problems.
https://github.com/azerothcore/azerothcore-wotlk/commit/a7b27238238fd5683c8da25b0d8c13e3b5cf4a1b 

the quest ID is "9967" , name "The Ring of Blood: The Blue Brothers", if I back to 15 July, the quest is ok.
git checkout cc52712ac12e3d6a16aabcbd13807924c64aeb1e

The Karazhan's Void Dragon which creature ID 15689,  when I back to 15 July, The boss still no line to the door,  because sql change can't back to before, so it not SmartAI CPP change problem, it might a database or other fix change problem.

**Comment by pklloveyou** [comment]
@kissingers you are right

**Comment by Nefertumm** [comment]
All should be alright by now, would you mind re-testing?

**Comment by kissingers** [comment]
Update to #12143 278845f
the question ID "9967" test ok.   

But The Karazhan's Void Dragon which creature ID 15689 still no line to boss (now the problem is can't see the line, but if stay between boss and the door, the line effect will have) 
#11779 cc52712  case problem still have.

**Comment by Nefertumm** [comment]
Did it worked before that commit, right?

**Comment by kissingers** [comment]
Yes, before  # 11779 cc52712 only one commit  is  [52d60] , the line to boss are still ok.

https://github.com/azerothcore/azerothcore-wotlk/commit/02fa20b6380b991634198de9a295abac11152d60

**Comment by kissingers** [comment]
update to 4378493acc8a78b5d4d47ca15441a476c57b16d2

The Karazhan's Void Dragon which creature ID 15689 still no line to boss (now the problem is can't see the line, but if stay between boss and the door, the line effect will have)

I can sure flow update case the problem.
https://github.com/azerothcore/azerothcore-wotlk/pull/11779 cc52712

**Comment by pklloveyou** [comment]
@kissingers Try PR above
