### ISSUE TITLE
Chat Logs to be reimplemented

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#125]
**Description**: Restore Chat log system

**Current behaviour**: Seems that old sunwellcore devs partially removed the chat log system from their repository ( leaving configurations and some useless variables ).

**Expected behaviour**: We should re-import the old chat log system. We can find a working version that should be compatible with our code in old TC commits, such as: https://github.com/TrinityCore/TrinityCore/commit/06d0560f152824a0bbd4488883eff682d54c96c8

**Steps to reproduce the problem**: in worldserver.conf, enabling chatlog won't work

**Branch(es)**:  1.x 

**AC hash/commit**:  de714fdae75239157073966554df3880fc1c93ba

**Operating system**:  Linux
##

**Comment by falzard** [comment]
If I'm right, the chatlog is completely empty?

I hope someone can fix this, that would be very helpful!

**Comment by Yehonal** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/3b2fb0949bac62b5070f82a2e3e3e7ed19bd6dd5
