### ISSUE TITLE
Quest marks display on world map in places they shouldn't be

### ISSUE THREAD

**Issue by anjachan** [azerothcore/azerothcore-wotlk#12509]
### Current Behaviour

Some quests do funny stuff like on images. It happened with other quests too (for example, from Silverpine Forest - they were displayed on Teldrassil map)

### Expected Blizzlike Behaviour

Those quest marks just shouldn't be here

### Source

https://user-images.githubusercontent.com/93767462/178467792-177da2d8-7dfe-4ea3-ad2c-fc160b323398.png
https://user-images.githubusercontent.com/93767462/178467834-f9483a2c-09f0-4111-b7f7-ee4709c57e16.png

### Steps to reproduce the problem

1. The quest I have is "The Champion of the Banshee Queen" (https://wowgaming.altervista.org/aowow/?quest=5961). Take it, then switch your map to Felwood/Barrens (maybe even other locations)
2. I'm sure it happens to other quests, but it's pretty random

### Extra Notes

Original post by [JustVityok](https://github.com/JustVityok): https://github.com/chromiecraft/chromiecraft/issues/3767#issue-1301855384

When I tried copying the steps to cause the bug, quest (The Champion of the Banshee Queen; id 5961) given in the bug report worked correctly for me. But I remembered having the same issue with the different quest (Unfinished Gordok Business; id 1318) showing me that the quest should be done in SilverPrine forest. 

My reproduction of the problem: https://youtu.be/ha0if-vLtPc

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 7

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Ovahlord** [comment]
this is very likely a client bug since the database data is indeed correct so unless the packet got screwed up badly or you're using some weird quest addon, this is pretty much a wontfix. The comments of your linked issue also tell it's a client addon that fucks it up so yeah, lol.

**Comment by temperrr** [comment]
Closed because we couldnt verify this issue ourselfves on this particulair quest.
