### ISSUE TITLE
Wrong spellpower coefficients for early ranks of class spells

### ISSUE THREAD

**Issue by Ovahlord** [azerothcore/azerothcore-wotlk#12510]
### Current Behaviour

As a result of a discussion here, I went ahead and was going over some spells which (oh surprise) have wrong spellpower coefficients which make lower ranks WAY more powerful than they should be. Blizzard scales their coefficients over the early stages so classes such as Mages are not overpowered at level 1. This 'feature' has later been replaced in 4.x onwards by introducing level based spell scaling but prior to that they just used weaker spellpower scaling for lower ranks of their spells.
These scalings diminish with each higher rank so at rank 5 spells have reached their full spellpower scaling potential.
And yes, this will massively nerf low level caster classes when all entries have been applied but I'll go ahead and provide some mage values.

These data are inside of the dbc and until you port the dbc-side handling of the coefficients, here are some db fixes to demonstrate how impactful that change is on lower levels.

```
-- Frost Bolt
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.172 WHERE `entry`= 116; -- R1
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.283 WHERE `entry`= 205; -- R2
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.488 WHERE `entry`= 837; -- R3
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.743 WHERE `entry`= 7322; -- R4

-- Fireball
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.123 WHERE `entry`= 133; -- R1
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.271 WHERE `entry`= 143; -- R2
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.5 WHERE `entry`= 145; -- R3
UPDATE `spell_bonus_data` SET `direct_bonus`= 0.793 WHERE `entry`= 3140; -- R4
```

### Expected Blizzlike Behaviour

Early ranks of spells do scale less with spell power.

### Source

Just look into the spell.dbc file and get all values from there. They are right there and the client uses these values to generate the tool tips. You can't be more official than that.

### Steps to reproduce the problem

1. Use one of the two spells without these changes and observe insane damage values.
2. apply the file and try again
3. No longer be OP.

### Extra Notes

As I said, TrinityCore has automated the process of handling spellpower coefficients from dbc so it's more worth porting that handling rather than updating all entries one by one.

### AC rev. hash/commit

26079bd5283da4362407d802230089a4cb1a5697

### Operating system

Win 11

**Comment by Maelthyrr** [comment]
@Ovahlord does it this commit https://github.com/TrinityCore/TrinityCore/commit/9f0051c4e5d8de7e216bf3e55b759583e52ff681 ?

**Comment by Ovahlord** [comment]
No, 3.3.5 has a different implementation. you've been looking in the wrong branch

**Comment by acidmanifesto** [comment]
This was something i made mention of this issue before but i guess my explaination wasn't as clear as it should and was told I was wrong based on something called "theory crafting"(?). Hopefully your write up would be alot more clear then when i mentioned it a few months ago.

**Comment by TheDdraig** [comment]
I can comfirm Ovahlord is correct, wow tools even backs this up with the introduction of spell scaling from 4.0 onwards
![image](https://user-images.githubusercontent.com/62179779/180646963-6fd26989-12db-4916-be73-e86d18a31446.png)

I also did a search for the spell.dbc fields in 3.5 which shows coefficient

![image](https://user-images.githubusercontent.com/62179779/180647407-aaec37d2-148c-4d60-82fb-0e0642550cd5.png)

I then searched in the database under spell.dbc table which seems to have them un-named so unsure if they are correctly implemented or no one has used it.

![image](https://user-images.githubusercontent.com/62179779/180647445-8aa444a6-af3f-4fe3-9d78-cb9764722aa0.png)

If you look after PowerDisplayID it will show Field227, Field228, Field229. Hope I'm on the same track, but yes that would need to be changed. Thats a good find, lol

**Comment by TheDdraig** [comment]
Also it seems the new wrath classic is using something different, would be safe to say they are now using the scaling system:

![image](https://user-images.githubusercontent.com/62179779/180647682-31621550-852c-437c-bde9-2aeb759c0286.png)

**Comment by Ovahlord** [comment]
> Also it seems the new wrath classic is using something different, would be safe to say they are now using the scaling system:
> 
> ![image](https://user-images.githubusercontent.com/62179779/180647682-31621550-852c-437c-bde9-2aeb759c0286.png)

Modern clients have split the spell.dbc into more storages. The coefficient is stored in spelleffect.db2

**Comment by TheDdraig** [comment]
Aha I see, well yeah this really needs to be changed since if the data is already in the dbc, then it shouldnt need all these hotfixes. I would hate to think how many spells are impacted by this. Hope you didnt mind me spamming all the screenshots, kinda just wanted to prove its fucked and needs to be fixed. Although awesome you have better values and damn 0.172 seems a huge difference to 0.857 xD

**Comment by Ovahlord** [comment]
yeah, this change is quite a game changer for low level content. No longer ez gg rushing

**Comment by neifion-00000000** [comment]
I mean, I kinda disagree that its that overpowered but you're correct that it's wrong and should be fixed.

They did this change before they made every rank cost the same, so its balancing was to prevent people from downranking spells, there isn't enough spell damage gear at low levels and only one enchant (the one that drops in Molten Core) can be applied to items that can be worn by low levels.

**Comment by ZhengPeiRu21** [comment]
I will create a fix for this. Thanks Ovahlord for reporting the issue.
