### ISSUE TITLE
emote command allow chat between factions

### ISSUE THREAD

**Issue by IngMak** [azerothcore/azerothcore-wotlk#1251]
##### SMALL DESCRIPTION:
write in chat: /e hello world
enemy factions can understand language.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
with default worldserver.conf enemy factions can`t understand messages.

##### CURRENT BEHAVIOUR:
using chat command "/e" allow chat between enemy factions with default .conf

##### STEPS TO REPRODUCE THE PROBLEM:
0. loggin with two characters from opposite factions (1 horde, 1 alliance)
1. write in chat: /e hello, can we be friends?

check chat is legible between factions.

##### EXTRA NOTES:
TC have this issue.
i think chathandler have to be reviewed.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
 cfa2f86 

##### OPERATING SYSTEM:

windows/linux

##### MODULES:
anticheat

**Comment by poszer** [comment]
Issue confirmed

**Comment by poszer** [comment]
Client side problem :
[battle.net topic](https://us.battle.net/forums/en/wow/topic/2661227432)
