### ISSUE TITLE
[ZG] Gurubashi Axe Thrower - Axe Flurry has the wrong behaviour

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12525]
### Current Behaviour

Axe Flurry channeling causes Axe Flurry (24020) to hit everyone nearby at once.

### Expected Blizzlike Behaviour

Every second, while channeling, the channeling should trigger Axe Flurry (24020) cast at a random target (probably either the current target and/or anyone in the creature's threat table), to a total of 10 times.
Every second, while channeling, the channeling should trigger Axe Flurry (24071) at all nearby targets, to a total of 10 times.

### Source

sniffs from TBCC

### Steps to reproduce the problem

1. `.go c id 11350` with 2 characters.
2. see if only one gets hit by Axe Flurry (24020) at a time.

### Extra Notes

The channeling is triggered by spell 24018, I think.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a7b27238238fd5683c8da25b0d8c13e3b5cf4a1b

### Operating system

Windows 10

**Comment by temperrr** [comment]
needs spellscript adjustment then
