### ISSUE TITLE
creature curmana & curhealth are useless

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#12534]
### Current Behaviour

They are never used and always get overwritten with template generated data

![image](https://user-images.githubusercontent.com/47818697/180784871-9bc8da20-81ef-47f3-ba85-e471a71fcd5a.png)

AddCreData in ObjectMngr.cpp

### Expected Blizzlike Behaviour

Probably should drop both columns

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/accb01f1800c8495bd5153e849ce19a2af5ede62

### Operating system

Win11 x64

**Comment by Kitzunu** [comment]
They are read in void ObjectMgr::LoadCreatures()

Also I don't think we should remove them becuase iirc ther are some creatures that use these to update the health to be < max hp

**Comment by Nyeriah** [comment]
Hm I tried settin current mana, didn't work, got overwritten with template data, but I will be closing this

**Comment by Kitzunu** [comment]
then there's some other issue I guess :shrug:
