### ISSUE TITLE
Death Knight - spell death and decay 

### ISSUE THREAD

**Issue by kaniel** [azerothcore/azerothcore-wotlk#12542]
### Current Behaviour

sometime  Death Knight‘s (death and decay) spell (49938) execute does no Damage ，and  is same of Paladin’s (dedication)  spell(48819) . I try fix it in database or code.  I don't know how fix it. 

### Expected Blizzlike Behaviour

In game, sometime  Death Knight‘s (death and decay) spell execute does no Damage

### Source

Paladin’s  same

### Steps to reproduce the problem

Paladin’s  same

### AC rev. hash/commit

1

### Operating system

ubuntu16.04 x64,win10 x64

### Custom changes or Modules

  |     +- mod-ah-bot
  |   +- mod-custom-login
  |   +- mod-multi-client-check
  |   +- mod-npc-services
  |   +- mod-premium
  |   +- mod-world-chat

**Comment by kaniel** [comment]
thx for everyone  reply，

**Comment by heyitsbench** [comment]
Please include your AC revision hash.

**Comment by kaniel** [comment]
#ifndef __REVISION_H__
#define __REVISION_H__
 #define _REVISION                  ""
 #define _HASH                      "unknown"
 #define _DATE                      "1970-01-01 00:00:00 +0000"
 #define _BRANCH                    "Archived"
 #define _CMAKE_COMMAND             R"(/usr/local/bin/cmake)"
 #define _CMAKE_VERSION             R"(3.17.5)"
 #define _CMAKE_HOST_SYSTEM         R"(Linux 4.15.0-142-generic)"
 #define _SOURCE_DIRECTORY          R"(/home/aoce/ac/azerothcore-wotlk617)"
 #define _BUILD_DIRECTORY           R"(/home/aoce/ac/azerothcore-wotlk617/tobuild)"
 #define _MYSQL_EXECUTABLE          R"(/usr/bin/mysql)"
 #define VER_COMPANYNAME_STR        "AzerothCore"
 #define VER_LEGALCOPYRIGHT_STR     "(c)2016-2022 AzerothCore"
 #define VER_FILEVERSION            0,0,0
 #define VER_FILEVERSION_STR        "unknown 1970-01-01 00:00:00 +0000 (Archived branch)"
 #define VER_PRODUCTVERSION         VER_FILEVERSION
 #define VER_PRODUCTVERSION_STR     VER_FILEVERSION_STR
#endif // __REVISION_H__

**Comment by heyitsbench** [comment]
Do `.server debug` in the worldserver console and provide the information it says.

**Comment by kaniel** [comment]
release 4.0  283ffb20e83f5302e6feccc4adaa288ade9398b8

acore.json
 "name": "azerothcore-wotlk",
  "version": "7.0.0-dev.0",
  "license": "AGPL3"

**Comment by kaniel** [comment]
.server debugAC> .server debug
AC> AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithReInfo, Static)
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.79.0
Using MySQL version: 50737
Using CMake version: 3.17.5
Compiled on: Linux 4.15.0-142-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/aoce/ac/wotlkserver/data/maps. Total size: 291014339 bytes
vmaps directory located in /home/aoce/ac/wotlkserver/data/vmaps. Total size: 658130553 bytes
mmaps directory located in /home/aoce/ac/wotlkserver/data/mmaps. Total size: 2107918268 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-custom-login
- mod-multi-client-check
- mod-npc-services
- mod-premium
- mod-world-chat

**Comment by kaniel** [comment]
I tested using multiple versions  of AC.  can't solve this problem

**Comment by Kitzunu** [comment]
You are using a year old version of the core. Update to latest and try again. Closing for now =)
