### ISSUE TITLE
(DB/creature): Unable to attack a mob 

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#12554]
Originally reported at https://github.com/chromiecraft/chromiecraft/issues/3849

* Picture from self-testing: The issue is with pos Z, at server start the add (from DB perspective) is in the air while the model is at ground which makes a player think it is well-landed and ready for interaction.
![image](https://user-images.githubusercontent.com/61223313/181142713-c9a84471-332c-4bc2-970b-0b7a0696fb6b.png)

### Current Behaviour

While in Ashenvale in Feral Druid form, i'm unable to hit this particular mob, or initiate a fight with it
Approaching the mob from all angles or trying to hit it with abilities or autoattack does nothing
The mob ignores me entirely, does not move, and i receive this message: "Out of range" "You are too far away"
To note this mob has probably spawn on top of this structure that might cause its weird behaviour

### Expected Blizzlike Behaviour

Expect to initiate a fight with the mob and hit it / being hit by it

### Source

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by Gultask** [comment]
> ????

It's just a part of triage, linking the issue in the CC repo so it's considered valid.
