### ISSUE TITLE
AQ40: Bug trio | Vem Charge

### ISSUE THREAD

**Issue by WORISX** [azerothcore/azerothcore-wotlk#12566]
### Current Behaviour

When Vem charges and the path is ended, no matter on which point inside the room, he just regenerates his life completely after the charge is done, so it's impossible to kill him with normal behaviours.

### Expected Blizzlike Behaviour

He should not regenerate hp at the end of the charge, just a normal charge and keep his hp unmodified after charge is done.

### Source

https://www.youtube.com/watch?v=5T5GCUSzYr0&t=111s WoW Classic

### Steps to reproduce the problem

1. .go c 87603
2. Engage bug trio, kill yauj and and kri.
3. Use 2 characters for test, attack Vem with both characters.
4. Make his life down to 70% for example using some spells.
5. Let him charge on any of both characters
6. See how he recovered hp to 100%

### Extra Notes

I honestly don't know what's happening, at first thought it was a problem of mmaps, los or something like that, but i don't think there's any type of issue with that, dunno.

- There is some kind of weird issue going on with them actually, scarabs can spawn infinitely, making worldserver process to lag and create high update diff timers, yauj should only spawn 10 scarabs on death, but he's spawning a ton of them.
- Kri is creating also tons of posion clouds when he dies, just as same as yauj that spawns a ton of scarabs which can cause worldserver to freeze
- Both 3 bug trio bosses movement are weird, they can just stop attacking until you go and get onto their melee reach.
- They can die and also sometimes corpse of the last boss will dissapear without having a chance of looting it.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/18b7b6c273e732db59695ba50b972ed058187b4d

### Operating system

Windows 10 x64, Debian 10

### Custom changes or Modules

mod-transmog

**Comment by Nefertumm** [comment]
I can confirm there is something wrong with first and second items of extra notes just by looking at the code. It seems when I rewrote the fight, I forgot to add a check.
