### ISSUE TITLE
Wyvern Sting (Dot) is shown as a buff

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#12565]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour
Original Report:
![image](https://user-images.githubusercontent.com/50233983/180623745-e0d840d2-6ec0-495f-bd47-a6d9fcade34b.png)

Shown as a buff, can right click to remove

Additional (From local AC (rev. 757375f98242)):
![image](https://user-images.githubusercontent.com/53914190/181388991-da72a42a-8c04-4bc4-944f-551d20ff8c31.png)
![image](https://user-images.githubusercontent.com/53914190/181388999-e1e6b0fa-e819-490d-ab83-6c5a826ea41e.png)

### Expected Blizzlike Behaviour

Debuff

Additional Notes:
While there is no source, I don't think it's controversial for a poison to be a debuff.

### Steps to reproduce the problem

Find a hunter that has it talented
Duel or whatever
Have it cast on you

### Extra Notes
https://wowgaming.altervista.org/aowow/?spell=19386

Original Report:
https://github.com/chromiecraft/chromiecraft/issues/3846

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Tony931023** [comment]
should only be dispelled by poison dispel spells

**Comment by UltraNix** [comment]
Works okay to me.

**Comment by Tony931023** [comment]
I tried it again now and it works fine, it no longer comes out as a buff (photo number 2 of the report),

**Comment by jamadaha** [comment]
Just tested again on rev AzerothCore rev. d4b3de773d51 2022-08-18 09:44:36 -0300 (master branch) (Unix, Release, Static).
Seems to be an issue for me still.

https://user-images.githubusercontent.com/53914190/185403192-79b50efb-6ba3-47e7-acfd-b71e033870ce.mp4

**Comment by Tony931023** [comment]
> Just tested again on rev AzerothCore rev. [d4b3de7](https://github.com/azerothcore/azerothcore-wotlk/commit/d4b3de773d51d067105fca695e24481fb432a83d) 2022-08-18 09:44:36 -0300 (master branch) (Unix, Release, Static). Seems to be an issue for me still.
> Sting.mp4
@UltraNix

**Comment by UltraNix** [comment]
@Tony931023 
![WoWScrnShot_082022_100831](https://user-images.githubusercontent.com/80540499/185735673-3fa97afa-88fe-4376-916d-afa7351ed136.jpg)
![WoWScrnShot_082022_100836](https://user-images.githubusercontent.com/80540499/185735677-6a8e3d1a-c77a-45a3-8f95-b93e2a38d649.jpg)
I see no bug here - works everything okay.

**Comment by AnchyDev** [comment]
I am observing the same issue on 8b95418 is it possible it got fixed after that?

**Comment by AnchyDev** [comment]
Based on a hunch and observing both of your images I have tested each rank of the spell.
Rank 1, 2 & 3 incorrectly apply a buff.
Rank 4, 5 & 6 correctly apply a debuff.

**Comment by UltraNix** [comment]
@AnchyDev Nice catch
