### ISSUE TITLE
[AQ20] Qiraji Gladiator (15324)

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12586]
### Current Behaviour

Casts Vengeance (25164) at 30% or less HP.
Timers for other spells may need tweaking.

### Expected Blizzlike Behaviour

Casts Vengeance (25164) immediately on their partners' death (Qiraji Gladiators always comes in pairs) and will cast it again as long as the other remains dead and they're in combat, even if the group wiped and pulled again.
Recasts Vengeance after 60 of the last Vengeance cast.

From 15 minute sniffs and timestamps, the timers I've gotten come closer to:

 - Trample (5568): Repeat 6000-17000
 - Uppercut (10966): Repeat I'd say 6000-16000

### Source

Retail sniffs

### Steps to reproduce the problem

1. `.go c id 15324`
2. kill one of the pair, see if the other casts Vengeance.
3. `.combatstop` and pull again, see if it can cast Vengeance again.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/bba9b9ce79f49532fd7e217423649f657e267ad0

### Operating system

Windows 10

**Comment by kerricsson** [comment]
I can confirm that issue still actual and not fixed at  AzerothCore rev. 6ad764c520c2 2022-08-07 01:05:05 -0700 (master branch) (Unix, Debug, Static)
