### ISSUE TITLE
bug(Core/Mail) Inverted `mail_server_template` columns.

### ISSUE THREAD

**Issue by AnchyDev** [azerothcore/azerothcore-wotlk#12592]
### Current Behaviour

Filling the fields for the alliance or horde columns in `mail_server_template` are inverted so if you want only horde to receive an item, alliance instead receive it and vice versa.

### Expected Blizzlike Behaviour

Alliance and horde should received items for their respective columns and not be backwards.

### Source

-

### Steps to reproduce the problem

1. Setup a row in the `mail_server_template` in `acore_characters` to send any item to alliance only.
2. Login and check to see if the item is in the mail.

### Extra Notes

This is something I observed on a friends server so I went and inspected the code and it looks like all of the ternary operators are backwards. Need someone to test because I don't have access to a build server right now.

The problem lies within [ObjectMgr::SendServerMail](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Globals/ObjectMgr.cpp) in the ObjectMgr on line 9878 - 9879.

```cpp
draft.AddMoney(player->GetTeamId() == TEAM_ALLIANCE ? rewardMoneyH : rewardMoneyA);
if (Item* mailItem = Item::CreateItem(player->GetTeamId() == TEAM_ALLIANCE ? rewardItemH : rewardItemA, player->GetTeamId() == TEAM_ALLIANCE ? rewardItemCountH : rewardItemCountA))
```

### AC rev. hash/commit

7ecd73867419c807c9869ebeb73c7ca4e39cd1c8

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
Can confirm this issue on https://github.com/azerothcore/azerothcore-wotlk/commit/bba9b9ce79f49532fd7e217423649f657e267ad0.
![image](https://user-images.githubusercontent.com/38561765/182009732-d99f989a-f521-4882-9bcd-17cc23615299.png)
![image](https://user-images.githubusercontent.com/38561765/182009735-5ef350b3-c3e7-49f0-aaee-7c1aa330debc.png)
