### ISSUE TITLE
Can't open worldserver & authserver

### ISSUE THREAD

**Issue by Krath** [azerothcore/azerothcore-wotlk#126]
Hey everyone, I'm having a problem with a fresh compile. I can't open worldserver nor authserver. They just close instantly without displaying anything. No logs are being created and I can't really understand what happens.

I've compiled it with both Visual studio 2013 and Visual studio 2015. Nothing changes.
Has anyone encountered this problem?

**Comment by DevRival** [comment]
Check out all the sql added to the database. And configs worldserver.conf.dist move to a folder with the server config files is with bronchiectasis .dist. I have no idea why, but it helped me.

**Comment by Krath** [comment]
I just realized that the "Release" compiled does that. No problems with Debug or RelWithDebugInfo.
I keep getting C++ errors on Debug version tho.

**Comment by ShinDarth** [comment]
Do not open them directly. First open the console, then execute the worldserver so you can see which errors you get (same for authserver)

**Comment by DantestyleXD** [comment]
Or create a bat file with:
`authserver.exe
pause`
or worldserver.exe

**Comment by Krath** [comment]
Ok, I have got it fixed. Thanks everyone for the tips :)

**Comment by franklampardahar** [comment]
@krath dude how you fix this problem?!

**Comment by ShinDarth** [comment]
@franklampardahar better to use chat/forum for support
