### ISSUE TITLE
Void Specter Dragon of Karazhan

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/azerothcore-wotlk#12604]
### Current Behaviour

Void Gate Stage
In the room entrance to the left, right, and directly opposite each have a void door point, whenever you enter the stage, the three points will each refresh a different color void door, and after 10 seconds from the three doors at the same time issued three corresponding color light shot to the BOSS, now the problem is that the three light no actual display effect, not visible to the naked eye.

### Expected Blizzlike Behaviour

After the appearance of the void door, should appear from the door at the same time, red, green and blue light shot to the void dragon.

### Steps to reproduce the problem

Open the team mode into Karazhan, directly with the Void Dragon battle until the appearance of three void doors can see the problem of not showing light. (red line green line blue line)

### AC rev. hash/commit

AzerothCore rev. bad616c68a66+ 2022-07-27 12:47:50 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1l  24 Aug 2021 (library: OpenSSL 1.1.1l  24 Aug 2021)
Using Boost version: 1.74.0
Using MySQL version: 50737
Using CMake version: 3.22.4

### Operating system

Windows 7 x64

**Comment by pklloveyou** [comment]
Try PR above

**Comment by zxnhrdz** [comment]
@pklloveyou  Thanks a lot, the problem is solved!
