### ISSUE TITLE
I can't compile so that the error doesn't appear, what should I do to fix it?

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#12607]
### Current Behaviour

I can't compile so that the error doesn't appear, what should I do to fix it?

does not compile in Visual Studio Authserver.exe and Worldserver.exe
at the end it gives 2 errors
![2022-08-02_17-48-29](https://user-images.githubusercontent.com/98691968/182404187-e803949d-e595-47b9-ac18-ad6556661cfb.png)

### Expected Blizzlike Behaviour

When I build, Visual Studio does not compile in Visual Studio Authserver.exe and Worldserver.exe
at the end it gives 2 errors

### Steps to reproduce the problem
```
CMake version: 3.24.0-rc5
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
The CXX compiler identification is MSVC 19.31.31105.0
The C compiler identification is MSVC 19.31.31105.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++20 standard
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.31.31105.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Enable NOMINMAX
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe
fatal: not a git repository (or any of the parent directories): .git


    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* AzerothCore revision            : unknown 1970-01-01 00:00:00 +0000 (Archived branch)

* Install core to                 : C:/Program Files/AzerothCore
* Install configs to              : C:/Program Files/AzerothCore

* Build applications              : Yes (all)
* Build tools                     : No
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : Yes - "hierarchical"

Found Boost: C:/local/boost_1_74_0 (found suitable version "1.74.0", minimum required is "1.74") found components: system filesystem program_options iostreams regex 
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Looking for _strtod_l
Looking for _strtod_l - found
Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib  
Looking for C++ include filesystem
Looking for C++ include filesystem - found
Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Check if compiler accepts -pthread
Check if compiler accepts -pthread - no
Found Threads: TRUE  
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD

* Apps build list (all):
  |
  +- apps
  |   +- authserver
  |   +- worldserver
  |

Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
* Script configuration (static):
  |
  +- worldserver
  |   +- Commands
  |   +- Custom
  |   +- EasternKingdoms
  |   +- Events
  |   +- Kalimdor
  |   +- Northrend
  |   +- OutdoorPvP
  |   +- Outland
  |   +- Pet
  |   +- Spells
  |   +- World
  |

* Modules configuration (static):
  |

* Modules config list:
  |

Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done
```

![2022-08-02_17-48-29](https://user-images.githubusercontent.com/98691968/182404324-81569c69-4dbd-4e1f-b5ef-a85bc1cbe916.png)

### Extra Notes

no

### AC rev. hash/commit
```
CMake version: 3.24.0-rc5
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
The CXX compiler identification is MSVC 19.31.31105.0
The C compiler identification is MSVC 19.31.31105.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++20 standard
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.31.31105.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Enable NOMINMAX
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe
fatal: not a git repository (or any of the parent directories): .git


    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* AzerothCore revision            : unknown 1970-01-01 00:00:00 +0000 (Archived branch)

* Install core to                 : C:/Program Files/AzerothCore
* Install configs to              : C:/Program Files/AzerothCore

* Build applications              : Yes (all)
* Build tools                     : No
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : Yes - "hierarchical"

Found Boost: C:/local/boost_1_74_0 (found suitable version "1.74.0", minimum required is "1.74") found components: system filesystem program_options iostreams regex 
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Looking for _strtod_l
Looking for _strtod_l - found
Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib  
Looking for C++ include filesystem
Looking for C++ include filesystem - found
Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Check if compiler accepts -pthread
Check if compiler accepts -pthread - no
Found Threads: TRUE  
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD

* Apps build list (all):
  |
  +- apps
  |   +- authserver
  |   +- worldserver
  |

Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
* Script configuration (static):
  |
  +- worldserver
  |   +- Commands
  |   +- Custom
  |   +- EasternKingdoms
  |   +- Events
  |   +- Kalimdor
  |   +- Northrend
  |   +- OutdoorPvP
  |   +- Outland
  |   +- Pet
  |   +- Spells
  |   +- World
  |

* Modules configuration (static):
  |

* Modules config list:
  |

Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done
```

### Operating system

Windows 7 x64

### Custom changes or Modules

no

I forgot to say that the lib files do not see here for these 2 lines
![2022-08-02_18-00-03](https://user-images.githubusercontent.com/98691968/182407121-064c4d7d-fa4a-43a7-a214-a92aa70e23ff.png)

**Comment by acidmanifesto** [comment]
Judging by your screen shot. You did not hit generate after you hit configured on cmake to build the splytion for visual studios.

**Comment by MegaserverRU** [comment]
> Судя по вашему снимку экрана. Вы не нажали кнопку Создать после того, как нажали кнопку Настроить в cmake для создания решения для Visual studios.

can I get more precise information I don't understand English well, thank you in advance

**Comment by MegaserverRU** [comment]
I also did all these actions before starting compilation
![2022-08-02_18-14-28](https://user-images.githubusercontent.com/98691968/182410017-e58610a5-53d7-44c8-833c-2e1966a7b2c4.png)

**Comment by heyitsbench** [comment]
![image](https://user-images.githubusercontent.com/38561765/182410235-1ce59a00-da32-4562-a75c-8b0ba2b70c71.png)
Left button, middle button, right button.

**Comment by acidmanifesto** [comment]
Nothing in the logs you posted shows you pressed the generate button. Also we no longer support visual studio 2017 as well. We support visual studio 2019 and newer 
Please refer to the guide on the official wiki.
https://www.azerothcore.org/wiki/windows-requirements

**Comment by MegaserverRU** [comment]
the same thing
with TrinityCore, such problems have never occurred
![2022-08-02_18-14-28](https://user-images.githubusercontent.com/98691968/182411009-a535fe6f-348d-4f43-8d1c-0b019d975bdf.png)
![2022-08-02_18-18-33](https://user-images.githubusercontent.com/98691968/182411011-cdf35817-ab90-4888-9e4d-ab485a6ba286.png)


CMake version: 3.24.0-rc5
Selecting Windows SDK version 10.0.19041.0 to target Windows 6.1.7601.
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++20 standard
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.31.31105.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Enable NOMINMAX
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe
fatal: not a git repository (or any of the parent directories): .git


    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* AzerothCore revision            : unknown 1970-01-01 00:00:00 +0000 (Archived branch)

* Install core to                 : C:/Program Files/AzerothCore
* Install configs to              : C:/Program Files/AzerothCore

* Build applications              : Yes (all)
* Build tools                     : No
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : Yes - "hierarchical"

Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD

* Apps build list (all):
  |
  +- apps
  |   +- authserver
  |   +- worldserver
  |

Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
* Script configuration (static):
  |
  +- worldserver
  |   +- Commands
  |   +- Custom
  |   +- EasternKingdoms
  |   +- Events
  |   +- Kalimdor
  |   +- Northrend
  |   +- OutdoorPvP
  |   +- Outland
  |   +- Pet
  |   +- Spells
  |   +- World
  |

* Modules configuration (static):
  |

* Modules config list:
  |

Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done
Generating done

**Comment by MegaserverRU** [comment]
Everything is installed as it says there
https://www.azerothcore.org/wiki/windows-requirements

**Comment by acidmanifesto** [comment]
You are not hiting the generate button according to your logs you posted. But you did hit the generate button on your log and ss for tc. You need to hit the generate button as well for azerothcore. Follow the steps in the wiki i posted. We have picture in the wiki guide to better assist.

**Comment by MegaserverRU** [comment]
I clicked the create button as shown above

**Comment by Winfidonarleyan** [comment]
> > @MegaserverRU ю андерстанэнд ру лангвага?
> 
> да я по русски говорю )

зайди в дс к нам в ру рум

![image](https://user-images.githubusercontent.com/18329778/182414125-aaee4004-7637-48f8-9506-af96b2b6390e.png)

**Comment by MegaserverRU** [comment]
> > > @MegaserverRU ю андерстанэнд ру лангвага?
> > 
> > 
> > да я по русски говорю )
> 
> зайди в дс к нам в ру рум
> 
> ![изображение](https://user-images.githubusercontent.com/18329778/182414125-aaee4004-7637-48f8-9506-af96b2b6390e.png)

Можно ссылку на канал пожалуйста?

**Comment by MegaserverRU** [comment]
Всем спасибо за участие в помощи, проблема решена.
Thank you all for participating in the help, the problem is solved.
