### ISSUE TITLE
Trial of the Champion

### ISSUE THREAD

**Issue by kaniel** [azerothcore/azerothcore-wotlk#12612]
### Current Behaviour

The Black Knight (1) - Emblem of Triumph  kill npc  and this boss is gone，

### Expected Blizzlike Behaviour

The Black Knight (1) - Emblem of Triumph  kill npc  and this boss is gone

### Source

None

### Steps to reproduce the problem

None

### Extra Notes

None

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.0.2g  1 Mar 2016 (library: OpenSSL 1.0.2g  1 Mar 2016)
Using Boost version: 1.79.0
Using MySQL version: 50737
Using CMake version: 3.17.5
Compiled on: Linux 4.15.0-142-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/waoc/acs/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/waoc/acs/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/waoc/acs/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-premium

### Operating system

ubuntu16.04

### Custom changes or Modules

- mod-premium

**Comment by kaniel** [comment]
5e946efaf400f05ee0e2c8312bfdacb42c7bc36f

**Comment by Maelthyrr** [comment]
Could you review your issue ? Current behavior is thé same thing than blizzlike behavior. And we need a step to repruodice this. So please fill correctly the issue pathern if you want that someone work on this. Thanks 😊

**Comment by zylok520** [comment]
![image](https://user-images.githubusercontent.com/32879123/184249792-adf4471f-eb59-496e-84e8-4dfa58b3ff81.png)

Black knight has disappeared

**Comment by Kitzunu** [comment]
I dont understand
