### ISSUE TITLE
[Server Freeze] Lord Jaraxxus Heroic freeze on grp wipe at add phases

### ISSUE THREAD

**Issue by PsYchoNauTek** [azerothcore/azerothcore-wotlk#12613]
### Current Behaviour

At Trials of Crusader Heroic when the group is wiping at one of Jaraxxus add phases (so either Mistress of Pain or Felflame Infernal) the server is freezing.

### Expected Blizzlike Behaviour

Groups should be able to wipe without freezing the server!

### Steps to reproduce the problem

1. Go into ToC 10/25 Heroic
2. Proceed to Jaraxxus
3. Start the fight with Jaraxxus
4. When the first Mistress of Pain/Felflame Infernal is appearing and starts to attack you, hit .gm on
5. Now u will see the server Freezing

### Extra Notes

Did even try to handle the adds via Eluna... same problem...
Also when taking out the ScriptName at the creature_template table and restarting the server it is the same... so it definitly is not about the Jaraxxus script... 

### AC rev. hash/commit

AzerothCore rev. e13f4271897e

### Operating system

Windows Server 2k19

### Custom changes or Modules

Eluna
Skip DK area
CFBG
Weapon Visualist
Transmogger
Anticheat
Duelreset
Accbound Mounts
5-Man Scaled Raids (Spelltimers changed, spelldamage changed, hp and melee of raidcreatures changed)
Retroports added

**Comment by heyitsbench** [comment]
Is this not a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/11538?

**Comment by PsYchoNauTek** [comment]
> Is this not a duplicate of #11538?
don't think so
since your case only is about the infernals and not about the whole adds of jaraxxus ^^

**Comment by Ovahlord** [comment]
use the freeze detector in config and provide a crashlog that follows after that

**Comment by PsYchoNauTek** [comment]
[unknown_worldserver.exe_[3-8_9-9-56].txt](https://github.com/azerothcore/azerothcore-wotlk/files/9248875/unknown_worldserver.exe_.3-8_9-9-56.txt)

**Comment by ImmortalusDev** [comment]
It is because of while loops here

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_lord_jaraxxus.cpp#L121

**Comment by PsYchoNauTek** [comment]
> It is because of while loops here
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_lord_jaraxxus.cpp#L121

confirmed!
working good with the changed while loop to an if statement

**Comment by PsYchoNauTek** [comment]
closing issue since got solved with the linked fix(Core) =)
