### ISSUE TITLE
[BG/Mage] `Water Elemental` is ressurected at graveyard without the talent while having `Glyph of Eternal Water` in offspec

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#12638]
### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/3837

You may be ressurected at the graveyard by the Spirit Guide and have a Water Elemental ressurect with you while you don't have the talent nor its glyph.

### Expected Blizzlike Behaviour

If you don't have the Water Elemental talent, you should never have a Water Elemental pet.

### Source

Uhh... none! :D

### Steps to reproduce the problem

https://user-images.githubusercontent.com/22718174/183102076-25f1db2d-556e-439a-8161-9e30574ee739.mp4

**Setup**
-Be a mage.
-`.character level 50` (minimum level to learn the talent)
-`.modify money 10000000` (be rich enough to learn dual spec)
-`.go c 98820` (Dalaran mage trainer so you may learn dual spec)
-Learn dual spec
-Switch to your dual spec
-`.additem 50045` ([Glyph of Eternal Water](https://wotlkdb.com/?item=50045))
-Apply the [Glyph of Eternal Water](https://wotlkdb.com/?item=50045) on your offspec.
-Learn [Summon Water Elemental](https://wotlkdb.com/?spell=31687) from the frost talent tree
-`/cast Summon Water Elemental`
-`.debug bg` (will enable 1v0 battlegrounds)

**Replicating the bug**
-Queue and join a battleground. (uhh... seem to be at this moment that the server register that you must have your Water Elemental when being ressurected)
-Leave battleground.
-Change talent sets to the one that doesn't have [Glyph of Eternal Water](https://wotlkdb.com/?item=50045).
-`.deserter bg remove` (remove deserter so you may quickly join another battleground)
-Queue and join a battleground. (this time, you don't have the glyph or the skill to summon the Water Elemental but it seems to keep the previous behavior that you need the Water Elemental when being ressurected)
-Wait 2 minutes until you may leave the waiting room (so you won't be teleported into the waiting room when you die).
-Target yourself and `.die` and release spirit
-Be ressurected by the Spirit Guide.
-Notice you have the Water Elemental by your side while you are not supposed to be able to summon it.

### Extra Notes

You may carry the Water Elemental by leaving the battleground.

### AC rev. hash/commit

AzerothCore rev. a4c809f13c81 2022-08-03 16:54:21 -0400 (master branch)

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by pklloveyou** [comment]
@Synful-Syn 
Player.cpp
![image](https://user-images.githubusercontent.com/18535853/183316347-e65dbdac-5a69-427d-965a-8d7bd533b340.png)
Try replacing this line of code with
``` 
 else if (getClass() == CLASS_HUNTER || (getClass() == CLASS_MAGE && HasAura(31687)) || getClass() == CLASS_WARLOCK)
```
