### ISSUE TITLE
Newest Vmaps not loaded

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#1264]
##### BRANCH(ES):

master

##### MODULES:

Np

**Comment by Winfidonarleyan** [comment]
@Franklampardst Move all files 
- From `./data/maps/maps` to `./data/maps`
- From `./data/mmaps/mmaps` to `./data/mmaps`
- From `./data/vmaps/vmaps` to `./data/vmaps`

**Comment by Franklampardst** [comment]
@Winfidonarleyan  no there is another problem after maps updates!

**Comment by Stoabrogga** [comment]
@Franklampardst 
You'll have to use a newer commit. The vmap update took place 8 days ago in commit 59d4e1d3a806a4f2f48f535be366bde1b24d737e and the commit you mentioned is 16 days old.
See https://github.com/azerothcore/azerothcore-wotlk/wiki/Installation#5-download-the-data-files

**Comment by Franklampardst** [comment]
@Stoabrogga Tnq . now this can be close!

**Comment by BarbzYHOOL** [comment]
Watch the master branch or the discord #announces next time if you face this sort of issue
