### ISSUE TITLE
 ICC marrowgar SPELL BONE STORM BUG

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#1265]
ICC marrowgar SPELL BONE STORM BUG

##### SMALL DESCRIPTION:
BONE STORM now selects random players every time

##### EXPECTED BLIZZLIKE BEHAVIOUR:
BONE STORM should always select the farthest player!

##### CURRENT BEHAVIOUR:
BONE STORM now selects random players every time

##### STEPS TO REPRODUCE THE PROBLEM:
1. Find three players
2. .go c 200992
3. Three points and one line
4. attack!

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
Did not find

##### OPERATING SYSTEM:
Windows 7/64

##### MODULES:
NO MODULES

##### OTHER CUSTOMIZATIONS:
NO CUSTOM

**Comment by pklloveyou** [comment]
`
					case EVENT_BONE_STORM_MOVE:
						{
							if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == POINT_MOTION_TYPE)
							{
								events.RepeatEvent(1);
								break;
							}
							events.RepeatEvent(5000);
							Unit* unit = SelectTarget(SELECT_TARGET_FARTHEST, 0, 90.0f,true);
							if (!unit)
							{
								if (unit = SelectTarget(SELECT_TARGET_FARTHEST, 0, 175.0f, true))
									if (unit->GetPositionX() > -337.0f)
									{
										EnterEvadeMode();
										return;
									}
							}
							if (unit)
								me->GetMotionMaster()->MoveCharge(unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ(), 25.0f, 1337);
							break;
						}
						break;
`
Do I get this right?

**Comment by JorgeSally** [comment]
From what I read here : http://wowwiki.wikia.com/wiki/Lord_Marrowgar it seems the bone storm is launched when you get farther but work fine
"While in his Bone Storm Lord Marrowgar will randomly target and charge a raid member" in the DPS description section

**Comment by pklloveyou** [comment]
Thank you very much~ :) JorgeSally
