### ISSUE TITLE
[ZG] Player can summon multiple Gahz'ranka at once.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12662]
### Current Behaviour

Using Mudskunk Lure several times in sequence can result in summoning Gahz'ranka multiple times.

### Expected Blizzlike Behaviour

Only one Gahz'ranka should be able to be spawned per instance.

### Steps to reproduce the problem

1. `.additem 19975 20`
2. `.additem 19974 20`
3. `.go xyz -11695 -1770 13 309`
4. click the Mudskunk Lure item several times fast
5. see if multiple Gahz'ranka spawns

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/3894

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8987b8f0352c9594a23e795a0a24ea4509475c51

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
This should do: https://github.com/azerothcore/azerothcore-wotlk/pull/12663

**Comment by Gultask** [comment]
:o
Lightning fast.
