### ISSUE TITLE
[AQ20] Ayamiss issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12675]
https://github.com/chromiecraft/chromiecraft/issues/3759

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [x] 60

### Current Behaviour

Mob: https://wowgaming.altervista.org/aowow/?npc=15369

2. Hive'Zara Swarmers should be spawned on air, not on the ground.
3. At 70% health, Ayamiss doesn't land and can't be tanked.

### Expected Blizzlike Behaviour

2. Hive'Zara Swarmers should be spawned on air.
3. At 70% health, Ayamiss will land and can now be tanked.

### Source

2. https://www.youtube.com/watch?v=vZ78PHwMMpE 1:06:040
3. https://classic.wowhead.com/guides/ayamiss-the-hunter-ruins-of-ahnqiraj-strategy - "Phase 2 - Grounded
At 70% health, Ayamiss will land and can now be tanked by your standard tanks."

### Steps to reproduce the problem

For 1 and 2:
1. Go to AQ20 at PTR.
2. Engage the boss.
3.  Hive'Zara Swarmers do not spawns in the air
4. observer that it takes 50% for him to go down and not 30

For 2:
1. Go to AQ20 at PTR.
3. Observe that boss is not landing down.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR -  AzerothCore rev. 1d6dc750fa37 2022-07-09 21:38:58 +0000 (master branch) (Unix, Debug, Static)

**Comment by Si1ker** [comment]
1- ?????????
![image](https://user-images.githubusercontent.com/61223313/183742229-9dbcf008-de44-42bd-a263-98cc4b20717a.png)

2- ????????
![image](https://user-images.githubusercontent.com/61223313/183742701-35b186e9-f5e9-4a6b-a24c-d24ec8c91c5a.png)

rev 5fe01e2

xd

**Comment by Nyeriah** [comment]
1) the adds spawn grounded currently
2) the boss moves to player position instead of landing with the waypoints

Both addressed here: https://github.com/azerothcore/azerothcore-wotlk/pull/12665

**Comment by temperrr** [comment]
> 1- ?????????
> ![image](https://user-images.githubusercontent.com/61223313/183742229-9dbcf008-de44-42bd-a263-98cc4b20717a.png)
> 
> 2- ????????
> ![image](https://user-images.githubusercontent.com/61223313/183742701-35b186e9-f5e9-4a6b-a24c-d24ec8c91c5a.png)
> 
> rev 5fe01e2
> 
> xd

Please use more then question marks to get the point across. Thanks.
