### ISSUE TITLE
Queuing Specific Dungeon and leaving does not give deserter

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12676]
https://github.com/chromiecraft/chromiecraft/issues/3230
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

When queuing for any specific dungeon using the RDF tool, a player does not get Deserter debuff upong leaving the party, leaving the current system vulnerable to people who farm for specific item in a specific dungeon on a particular boss, and leaving before dungeon is complete if the desired item does not drop. This can be particularly painful if the said person is a healer or a tank, which makes them almost irreplaceable.

### Expected Blizzlike Behaviour

Wowhead Blizzlike comment stating that  you do get a Deserter debuff even if you leave a specific dungeon group.

![Blizzlike RDF](https://user-images.githubusercontent.com/100415626/159671150-5ff0b45f-2cfb-4102-b388-4039af7ca095.png)

### Source

https://www.wowhead.com/spell=71041/dungeon-deserter#comments

### Steps to reproduce the problem

1. Queue for any specific dungeon.
2. Leave when you get inside.
3. See you did not get a Deserter debuff.

### Extra Notes

I discovered this the first time when I was in a hurry to join an UBRS group before finishing my specific dungeon RDF. Tested again on PTR.

Video detailing the issue: https://streamable.com/hher3z

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e8d3292533c7e5d18af15d9bffabd581bacbadf9

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by SoglaHash** [comment]
I can't reproduce the missing debuff. I tested 2 scenarios described below. I saw debugger go into `player->AddAura(LFG_SPELL_DUNGEON_DESERTER, player);` and apply the debuff ingame everytime when it should've. Seems to be working correctly afaik

Party 1 full 5man party q 
1. try 20 seconds logout, log back in, did not leave party and no debuff
2. right click uninvite option is available and kicked player
no debuff
2. leave party 
debuff
3. leave party with 3 members in group
no debuff

Party 2 q 3 man premade + 2 solo q 
1. leave as premade member
debuff
2. leave as solo player
debuff
3. leave with 3 members in group 
no debuff

**Comment by SoglaHash** [comment]
I tested some scenarios below. I was able to reproduce your specific case but found that it works fine for some other cases. There's a wowhead comment that states that specific dungeon q should not give a cooldown and no deserter debuff upon leaving, only q'ing as random should. However I found that q'ing as random for Scholomance does not give a debuff either as the dungeon is not being correctly labelled as LFG_TYPE_RANDOM.   https://www.wowhead.com/wotlk/spell=71328/dungeon-cooldown
![wowheadRDF](https://user-images.githubusercontent.com/74299960/184962411-48da8103-3f7f-4dc3-90ba-608d67018f63.png)


lvl 56 Party 1 full party q daily RDF
20 seconds logout
log back in
still in party and no debuff  ✅
right click uninvite option available
no debuff ✅
leave party 
debuff  ✅
leave party
no debuff ✅

lvl 56 Party 2 3 man premade + 2 solo q daily RDF
leave as party member
debuff ✅
leave as group member 
debuff ✅
leave  
no debuff ✅

lvl 56 Party 3 3 solo specific dungeon, 2 party RDF
leave as premade RDF q 
debuff ✅
leave as specific dungeon q
debuff ✅

lvl61 Party 4 specific dungeon3 solo, 2 party
leave as premade 
no debuff ❔✅
leave as solo
no debuff ❔✅

lvl 61 Party 5 4 grouped RDF, 1 solo specific scholomance
leave as solo specific q
no debuff ❔✅
leave as grouped RDF
no debuff ❔❌

In the code as of now: When q'ing random RDF you receive a LFG_SPELL_DUNGEON_COOLDOWN aura which is needed to receive the debuff when leaving.  

The selectedRandomLfgDungeon when q'ing as Scholomance returns LFG_TYPE_DUNGEON aka no RDF and won't give the dungeon cooldown... Needs more investigating
```
                if ((randomDungeon || selectedRandomLfgDungeon(player->GetGUID())) && !player->HasAura(LFG_SPELL_DUNGEON_COOLDOWN))
                {
                    randomDungeon = true;
                    // if player is debugging, don't add dungeon cooldown
                    if (!m_Testing)
                    {
                        player->AddAura(LFG_SPELL_DUNGEON_COOLDOWN, player);
                    }
                }
```

**Comment by SoglaHash** [comment]
OK figured it out. Scholomance isn't labelled as a RDF dungeon in the DBC nor in database. Same thing for UBRS. Seems like another Blizzlike bug to me. Thoughts?
https://wow.tools/dbc/?dbc=lfgdungeons&build=3.3.5.12340#page=1
Database `lfgdungeons_dbc`
```
14	Gnomeregan
18	Scarlet Monastery - Graveyard
22	Uldaman
26	Maraudon - Orange Crystals
30	Blackrock Depths - Prison
32	Lower Blackrock Spire
34	Dire Maul - East
36	Dire Maul - West
38	Dire Maul - North
40	Stratholme - Main Gate
163	Scarlet Monastery - Armory
164	Scarlet Monastery - Cathedral
165	Scarlet Monastery - Library
272	Maraudon - Purple Crystals
273	Maraudon - Pristine Waters
274	Stratholme - Service Entrance
276	Blackrock Depths - Upper City
285	The Headless Horseman
286	The Frost Lord Ahune
287	Coren Direbrew
288	The Crown Chemical Co.
```

**Comment by temperrr** [comment]
> OK figured it out. Scholomance isn't labelled as a RDF dungeon in the DBC nor in database. Same thing for UBRS. Seems like another Blizzlike bug to me. Thoughts?
> https://wow.tools/dbc/?dbc=lfgdungeons&build=3.3.5.12340#page=1
> Database `lfgdungeons_dbc`
> ```
> 14	Gnomeregan
> 18	Scarlet Monastery - Graveyard
> 22	Uldaman
> 26	Maraudon - Orange Crystals
> 30	Blackrock Depths - Prison
> 32	Lower Blackrock Spire
> 34	Dire Maul - East
> 36	Dire Maul - West
> 38	Dire Maul - North
> 40	Stratholme - Main Gate
> 163	Scarlet Monastery - Armory
> 164	Scarlet Monastery - Cathedral
> 165	Scarlet Monastery - Library
> 272	Maraudon - Purple Crystals
> 273	Maraudon - Pristine Waters
> 274	Stratholme - Service Entrance
> 276	Blackrock Depths - Upper City
> 285	The Headless Horseman
> 286	The Frost Lord Ahune
> 287	Coren Direbrew
> 288	The Crown Chemical Co.
> ```

UBRS is not a rdf dungeon.  Just lbrs is.

**Comment by SoglaHash** [comment]
It's listed in https://wow.tools/dbc/?dbc=lfgdungeons&build=3.3.5.12340#page=1&colFilter%5B1%5D=upper%20black . I'll remove it from the PR;
