### ISSUE TITLE
[Warsong Gulch] [PVP] When the game ends with 0-0 score, Horde wins in all cases.

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12688]
https://github.com/chromiecraft/chromiecraft/issues/3692
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

In a Warsong Gultch match where both teams fail to capture the flag, Horde wins by default. No matter the situation. Even if Alliance team picks up Horde flag while their flag is still within their control. If they don't cap before the game ends, Horde wins.
Alliance players get 1x[Warsong Gultch Mark Of Honor].
Horde players get 3x[Warsong Gultch Mark Of Honor].

### Expected Blizzlike Behaviour

When the score is 0-0, the game should end in a tie. Each participant gets 2x[Warsong Gultch Mark Of Honor].

### Source

https://wowpedia.fandom.com/wiki/Warsong_Gulch?oldid=2530636 (see Mechanics).

"If neither side has captured a flag, then the game ends in a tie. Each player on the winning team receives three, and each player on the losing team receives one mark. In the case of a tie, all participants receive two marks."

### Steps to reproduce the problem

1. Queue Warsong Gultch.
2. Wait for game to finish without touching any flag. Or, have Alliance team pick flag without capping it. Or, both teams pick it up but neither capture it. (Keep score 0-0)
3. Horde wins.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Need to check if https://github.com/azerothcore/azerothcore-wotlk/issues/11717 needs to be closed then.

**Comment by temperrr** [comment]
this is only when nobody picks up the flag
