### ISSUE TITLE
Group & Target mana doesn't always update

### ISSUE THREAD

**Issue by noisiver** [azerothcore/azerothcore-wotlk#12694]
### Current Behaviour

While in a group, mana value seen by other players won't update unless it's triggered by something else. That something else include things like health regenerating, getting flagged as afk, changing targets etc

### Expected Blizzlike Behaviour

Mana is supposed to update for other players as frequently as health does as long as it's not full

### Steps to reproduce the problem

1. Create two characters, having one of them be able to cast heal spells really helps
2. Create a group with these characters
3. Cast heals on yourself on one of them and wait for the mana to naturally regenerate (level 1 makes this easy)
4. Check the mana value seen by the other player, it shouldn't be full

### Extra Notes

To hopefully explain the issue a little better, this is what the second character sees before the first one uses up their mana:
![image](https://user-images.githubusercontent.com/5157047/184008908-dcadaafa-efd2-4c7b-b2ac-d02848f8a55a.png)

This is what the second character sees after the first character has used up most of their mana **and** regenerated to full:
![image](https://user-images.githubusercontent.com/5157047/184008963-feb00078-6f85-4ce2-8a59-61fe609c4c4f.png)

This is only a huge issue for me because it makes it impossible to track how much mana a healer has before a pull unless they change target frequently.

Updates to the player in other ways, such as being flagged as afk, triggers an update to the mana. I know this because I sat around seeing if mana ever updated and it only did so when I went afk.

I tested this with absolutely **no** addons to make sure it can't be that.

### AC rev. hash/commit

a22ba935ef6b03cfb94278f7825961716762308a

### Operating system

Debian 11 x64

**Comment by tkn963** [comment]
Hunter pets doesn't seem to update their power either.

**Comment by tkn963** [comment]
I've done some more testing and it seems like the mana doesn't update for players you target either. As seen in the picture below, what the second player sees is different from the actual value.

![image](https://user-images.githubusercontent.com/5157047/184510383-4887c446-6f11-4106-a6c6-1bd72c463639.png)

**Comment by tkn963** [comment]
I tested this on 5 different clients, one I installed from the DVD and patched myself and one being the ChromieCraft client, and I can rule out it being an issue with the client just like I did with addons.

It only seem to happen with natural generation of mana, not if you drink or use a spell like innervate. Pet focus I can't for the life of me figure out why it's not working since other player powers - like rage - works just fine.

It would be nice if anyone could confirm this issue so I can stop going insane from looking at it.

**Comment by AnchyDev** [comment]
Can confirm on 8f73d4b that the mana does not want to update for my ChromieCraft client. I used the steps you provided to reproduce it. 

![Evidence](https://cdn.discordapp.com/attachments/284323424032129024/1008499031976198174/unknown.png)

**Comment by tkn963** [comment]
I found that this is kind of crucial in PvP. A sneaky rogue wants to kill a healer, he sees that one has low mana when in fact they have full mana. He doesn't see that unless they target something or casts a spell etc.

Perhaps someone could add tags to this because it seems like I can't.

**Comment by tkn963** [comment]
I have done some testing to see where in the chain it stops updating the mana visible to other players.

It's this one that doesn't get triggered correctly: https://github.com/azerothcore/azerothcore-wotlk/blob/b2e449fd15e38b4778a42650f388b8213cf62a6a/src/server/game/Entities/Player/Player.cpp#L1948

If I temporary move that line out of the if and let it update without the 2 second wait time, it does show the correct value. Perhaps someone more knowledgeable could have a look at it to see why it stops updating correctly.
