### ISSUE TITLE
Fishing Error

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#127]
**Description**: can not fish from a ledge  

**Current behaviour**: Go to bootybay fish. doesnt work u have to be on the same hight as the water. also can not loot grey items. (can from dalaran fountain)

**Expected behaviour**: should be able to fish from ledges.

**Branch(es)**:  1.x 
**AC hash/commit**:  

**Operating system**:  Windows 10
##

**Comment by sucofog** [comment]
This is still bug or its fixed, did you test?

**Comment by d3tr0l** [comment]
still bugged it is hard to fix because of TC's vmap and playerpos handler etc. Broken some time around implementation of the new system for this stuff

**Comment by sucofog** [comment]
@talamortis @d3tr0l We need to find a fix for this, pretty bad bug.......

**Comment by sucofog** [comment]
https://bitbucket.org/maczuga/sunwellcore/commits/1749037808d1de4f963b65aef117decacf78a8aa?at=master#chg-src/tools/map_extractor/CMakeLists.txt 

maybe fix?

**Comment by d3tr0l** [comment]
i do not think it is no fresh vmaps issue but someone try it please. noticed when you do. gm fly on you can actually fish.... or some more skilled dev mod the spells. cpp fishing part to hack fix /override z coordinate? fool the server to think player is actually standing on the water level and not on vmap object above which is blocking the mechanics.

**Comment by sucofog** [comment]
![image](https://cloud.githubusercontent.com/assets/734950/20650656/28cee638-b4d4-11e6-8231-41e9d4bb078c.png)

You can currently fish, but getting in the very very ledge

**Comment by sucofog** [comment]
Yes, with .gm fly on fishing works.

**Comment by d3tr0l** [comment]
@sucofog indeed but i believe it works that way only with disabled vmaps you should enable them as for blizzlike pathing etc. which does mean, there is issue with calculating where to throw fishing bobber too even if we manage to override the z coordinate.

**Comment by sucofog** [comment]
We have got this same code of TrinityCore/TrinityCore@11f6eb9

But still bugged

**Comment by d3tr0l** [comment]
this needs attention of somebody experienced with mapping vmaps and movement system. there was same or similar issue on TC bugtracker, but it got magically closed with no feedback just with non-working fix/solution.

**Comment by d3tr0l** [comment]
worth of shot maybe? i am spamming i guess, cant do any compile and test myself i am not at home. https://github.com/TrinityCore/TrinityCore/commit/23a5c5e855e09ff506ffad060379825b8615fa8b

**Comment by sucofog** [comment]
Don't worry, hmm, i don't thing that commits solves this, dates from too old, AC merged his last commit with TC on 2014 November i think, so this commit is added i think.

**Comment by ShinDarth** [comment]
@sucofog that does not mean that every commit from trinitycore were imported until 2014, we have only some of them

**Comment by sucofog** [comment]
I'm gonna take a look, but i'm currently on doing rest of the locales

**Comment by sucofog** [comment]
Checked commit TrinityCore/TrinityCore@23a5c5e

It's already added onto AC.

**Comment by d3tr0l** [comment]
yup but maybe lets try to revert the commit. but idk if it does not break another stuff depending on this. some ppl mentioned, that actually reverting it helped but again others did not achieved any solution with that.

**Comment by HeartWell** [comment]
``` diff
From 086c474bcf16705dc4c8cd224e1aae19c575f932 Mon Sep 17 00:00:00 2001
From: HeartWell <heartwell@list.ru>
Date: Sun, 27 Nov 2016 22:21:16 +0300
Subject: [PATCH] Core/Fishing: Fix error in most of places, when player is
 standing on some bridge and receives error "You can't use that here".

---
 src/server/game/Entities/Object/Object.cpp | 8 +++++---
 src/server/game/Spells/Spell.cpp           | 4 ++--
 2 files changed, 7 insertions(+), 5 deletions(-)

diff --git a/src/server/game/Entities/Object/Object.cpp b/src/server/game/Entities/Object/Object.cpp
index dbdd264..5ddd507 100644
--- a/src/server/game/Entities/Object/Object.cpp
+++ b/src/server/game/Entities/Object/Object.cpp
@@ -2535,14 +2535,16 @@ bool WorldObject::GetClosePoint(float &x, float &y, float &z, float size, float
     // angle calculated from current orientation
     GetNearPoint(forWho, x, y, z, size, distance2d, GetOrientation() + angle);
 
+    if (!forWho)
+        return true;
+
     if (fabs(this->GetPositionZ()-z) > 3.0f || !IsWithinLOS(x, y, z))
     {
         x = this->GetPositionX();
         y = this->GetPositionY();
         z = this->GetPositionZ();
-        if (forWho)
-            if (const Unit* u = forWho->ToUnit())
-                u->UpdateAllowedPositionZ(x, y, z);
+        if (const Unit* u = forWho->ToUnit())
+            u->UpdateAllowedPositionZ(x, y, z);
     }
     float maxDist = GetObjectSize() + size + distance2d + 1.0f;
     if (GetExactDistSq(x, y, z) >= maxDist*maxDist)
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index 87e74fc..ebc2bee 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -1299,12 +1299,12 @@ void Spell::SelectImplicitCasterDestTargets(SpellEffIndex effIndex, SpellImplici
         {
              float min_dis = m_spellInfo->GetMinRange(true);
              float max_dis = m_spellInfo->GetMaxRange(true);
-             float dis = (float)rand_norm() * (max_dis - min_dis) + min_dis;
+             float dis = frand(min_dis, max_dis);
              float x, y, z, angle;
              angle = (float)rand_norm() * static_cast<float>(M_PI * 35.0f / 180.0f) - static_cast<float>(M_PI * 17.5f / 180.0f);
              m_caster->GetClosePoint(x, y, z, DEFAULT_WORLD_OBJECT_SIZE, dis, angle);
 
-            float ground = m_caster->GetMap()->GetHeight(m_caster->GetPhaseMask(), x, y, z, true, 120.0f);
+            float ground = m_caster->GetMap()->GetHeight(m_caster->GetPhaseMask(), x, y, z, true, 50.0f);
             float liquidLevel = VMAP_INVALID_HEIGHT_VALUE;
             LiquidData liquidData;
             if (m_caster->GetMap()->getLiquidStatus(x, y, z, MAP_ALL_LIQUIDS, &liquidData))
-- 
2.8.1.windows.1

**Comment by sucofog** [comment]
Testing @HeartWell

**Comment by sucofog** [comment]
LOL

![image](https://cloud.githubusercontent.com/assets/734950/20685090/34f03c2a-b5b3-11e6-956a-15a0556866af.png)

Yes, well at least now you can fish from the ledge/bridge, any idea to solve this? It does not detected building floor

**Comment by d3tr0l** [comment]
well describe it detailed please. does it throw bobber into random places or only under player? does it work from bridges and edge of ledges too? if yes it might be good temporary hackfix. does it break another game mechanics? like deaths grip or los spells or warrior charge etc

**Comment by HeartWell** [comment]
You do not interfere take and check my temporary solution, if you will find the damage from this patch can write.

**Comment by StygianTheBest** [comment]
I had a user run into this problem today. Not being able to fish from a dock is kinda lame. What's the gameplan for getting this fixed? I'd be happy to help if anyone has ideas.

**Comment by Viste** [comment]
@StygianTheBest you have temp fix posted early. if you know C++ like you say in other topic, do the shit ))
or you can wait when someone other do it like you always do ) only make attantion on the problem and w8

**Comment by StygianTheBest** [comment]
@Viste Spend less time whining and trying to redeem your low self-esteem and more time probing deeper into problems you do not understand. Does this temp fix allow targeting fish schools from a dock? Oh.. you don't know. Does applying some of the ideas discussed at TrinityCore cause additional problems or reveal other bugs in the code that are likely worse than this bug? I looked into it and have asked if anyone here has any ideas beyond what is posted here. Definitely not looking to waste time giving you a podium to run your mouth. Do us all a favor and post this bullshit in russian next time, that way nobody will waste time reading it.

**Comment by talamortis** [comment]
please keep it clean guys be polite

**Comment by Viste** [comment]
@StygianTheBest you only asking and w8 for fixed so plz shut up )

**Comment by StygianTheBest** [comment]
@Viste Your tall tales of how you were playing WoW in 2004 from your parent's basement in Russia were far more entertaining than your incessant whining.

**Comment by StygianTheBest** [comment]
I did not encounter this problem on the latest TrinityCore, it worked perfectly from the docks at Booty Bay.

**Comment by Yehonal** [comment]
Old bug but new fix: https://github.com/azerothcore/azerothcore-wotlk/pull/709
