### ISSUE TITLE
[AQ40] Prophet Skeram - Earth Shock 

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12714]
### Current Behaviour

Casts Earth Shock occasionally

### Expected Blizzlike Behaviour

Casts Earth Shock (26194) every **1200ms** while its victim is not melee attacking the target with melee auto-attacks.
If the victim is in melee range but not auto-attacking the boss, the latter will cast Earth Shock
If the victim is not auto-attacking but only casting spells, the boss will cast Earth Shock
This behaviours extends to the images as well.

### Source

Retail
https://youtu.be/jj7NRJoMAVs?t=51 the images still cast Earth Shock even while they are in melee range

### Steps to reproduce the problem

1. `.go xyz -8295.55 2102.6 118.2 531 3.6`
2. engage the boss, enter melee range
3. select your character's portrait to cancel auto-attacks, see if boss casts Earth Shock
4. initiate auto-attacks on the boss, see if he stops casting Earth Shock
5. cast a spell such as Frostbolt (113), see if the boss resumes casting Earth Shock
6. `.damage 117000`
7. see if the same behaviour is applied to the images

### Extra Notes

I believe this is to avoid having a single player tanking all three images.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3771a7120d962bbe7cca70a1c1440b4acba440a5

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask You say that Earth Shock shoud be casted every 1200ms if player is not melee attacking. But the player's weapon speed might be much slower than 1200ms - what's then? E.g. player has 2.2 weapon speed, melee attack the boss, then must wait another 2.2, but boss will wait only 1.2s to cast Earth Shock (because boss does not know if player will wait and strike again or just stop melee attacking and and that's why is starting that 1.2s timer).

**Comment by Gultask** [comment]
Basically Earth Shock isn't cast if the player right-clicks the boss and is in melee range. I should've mentioned that in the issue, sorry.
Auto-shots from hunters, for example, don't count. It has to be melee from a player or a pet.

**Comment by UltraNix** [comment]
But it's not an answer to my doubts :P

**Comment by Gultask** [comment]
😛 
It's not the auto-attacks themselves, it's the player being in a hostile stance, or whatever it's called.

**Comment by UltraNix** [comment]
I think you don't understand me :(

**Comment by Gultask** [comment]
😄 Sorry!
This should make it clearer.

https://user-images.githubusercontent.com/100873791/184548679-eb6a194f-d3bc-4d04-9d6d-df502951a38a.mp4
