### ISSUE TITLE
The Missing Diplomat: Private Hendel gets stuck on bridge and can't continue RP.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#12718]
### Current Behaviour

Currently, upon subduing Private Hendel, if he is still on the dock and not on land, he can get stuck on the bridge and fail to continue his RP, prohibiting the quest credit from being given.

### Expected Blizzlike Behaviour

Private Hendel should get to whatever spot he needs to and credit should be given.

### Source

Common sense, also Temper.

### Steps to reproduce the problem

1. .quest add 1324
2. Fight Private Hendel
3. Try again until you observe the issue.

### Extra Notes

Possibly related to https://github.com/chromiecraft/chromiecraft/issues/3442.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Gultask** [comment]
1. `.quest add 1266`
2. `.go xyz -2897.153809 -3349.867432 31.299358 1 6.278478` don't move any further.
3. Complete quest 1266, take the next quest
4. Proceed with the quest, see if it plays normally

**Comment by mpfans** [comment]
The quest can be completed after the server is restarted, but this bug will appear after repeated several times

**Comment by Gultask** [comment]
In my experience the culprit seems to be more about positioning. As I restarted the worldserver every time to try it out and I spent the better part of a day on this guy 😭

**Comment by acidmanifesto** [comment]
Whats the details with being "stuck on the birdge"?
Is he stuck in it, ontop of it, under it?

**Comment by Gultask** [comment]
It's strange. I once saw him getting physically stuck, not being able to reach his waypoint. Most times it's just that WP_REACHED never fired.

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/215420950-b4179fd7-7d7f-4e7e-9f5e-edd7169d7ca2.png)

I think this commit may fix this issue
https://github.com/azerothcore/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

**Comment by mpfans** [comment]
Still unresolved

![image](https://user-images.githubusercontent.com/18187177/215440028-7382d5ce-68c0-4794-8cd1-a05a91b70cd1.png)
