### ISSUE TITLE
Weather system broken

### ISSUE THREAD

**Issue by ChibaPet** [azerothcore/azerothcore-wotlk#12711]
### Current Behaviour

In Winterspring, it should never rain:

~~~
MariaDB [acore_world]> select * from game_weather where zone = '618';
+------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+------------------+------------------+-------------------+--------------------+--------------------+---------------------+------------+
| zone | spring_rain_chance | spring_snow_chance | spring_storm_chance | summer_rain_chance | summer_snow_chance | summer_storm_chance | fall_rain_chance | fall_snow_chance | fall_storm_chance | winter_rain_chance | winter_snow_chance | winter_storm_chance | ScriptName |
+------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+------------------+------------------+-------------------+--------------------+--------------------+---------------------+------------+
|  618 |                  0 |                 25 |                   0 |                  0 |                 20 |                   0 |                0 |               20 |                 0 |                  0 |                 25 |                   0 |            |
+------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+------------------+------------------+-------------------+--------------------+--------------------+---------------------+------------+
~~~

and yet, it's raining right now. I've also observed it raining in Tanaris recently, which should only have sandstorms.

### Expected Blizzlike Behaviour

https://wowpedia.fandom.com/wiki/Weather_effects#Kalimdor_and_Eastern_Kingdoms

### Steps to reproduce the problem

Wait in a zone that should never see rain, and eventually it'll rain.

### AC rev. hash/commit

AzerothCore rev. 59e45c251eb5 2022-04-27 20:18:44 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100515
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-13-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/acore/data/maps. Total size: 291218471 bytes
vmaps directory located in /opt/acore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/acore/data/mmaps. Total size: 2196330140 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS deDE 
Using World DB: ACDB 335.7-dev
Using World DB Revision: 2022_04_24_01
Using Character DB Revision: 2022_04_19_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-transmog

### Operating system

Debian

### Custom changes or Modules

mod-transmog

**Comment by SoglaHash** [comment]
I looked at the data (weather_table) and put it in https://gist.githubusercontent.com/SoglaHash/3ef2c827b06e70e2468767915f7a9222/raw/8babc8cfb13ce8fb4f22226b7164500edb296663/gistfile1.txt for easier rading

like

| zone name           | `zone` | spring_rain_chance | spring_snow_chance | spring_storm_chance | summer_rain_chance | summer_snow_chance | summer_storm_chance | fall_rain_chance | fall_snow_chance | fall_storm_chance | winter_rain_chance | winter_snow_chance | winter_storm_chance |
|---------------------|--------|--------------------|--------------------|---------------------|--------------------|--------------------|---------------------|------------------|------------------|-------------------|--------------------|--------------------|---------------------|
| Dun Morogh          | 1      | 0                  | 25                 | 0                   | 0                  | 15                 | 0                   | 0                | 25               | 0                 | 0                  | 25                 | 0                   |
| Badlands            | 3      | 0                  | 0                  | 20                  | 0                  | 0                  | 20                  | 0                | 0                | 20                | 0                  | 0                  | 15                  |

I can add by saying, Isle of Quel'danas and Western Plaguelands both have rain_chances > 0 but aren't listed on 
https://wowpedia.fandom.com/wiki/Weather_effects#Kalimdor_and_Eastern_Kingdoms 

There's also a closed issue discussing weather https://github.com/azerothcore/azerothcore-wotlk/issues/6341

**Comment by SoglaHash** [comment]
I changed the setting in `worldserver.conf.dist` and managed to get weather updates every 20 secs and was able to reproduce the issue.
```
#
#    ChangeWeatherInterval
#        Description: Time (in milliseconds) for weather update interval.
#        Default:     600000 - (10 min)
ChangeWeatherInterval = 20 
```

https://user-images.githubusercontent.com/74299960/184511763-9882d956-7d7c-4c73-bd6a-079a583f4940.mp4

Looks like it's raining even though the chance is set to `0`
