### ISSUE TITLE
[ZG] Bloodlord Mandokir - Ohgan should cast Thrash within a timer

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12739]
https://github.com/chromiecraft/chromiecraft/issues/3900

### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Handled through aura 3471.

### Expected Blizzlike Behaviour

Should be used roughly every 15s, perhaps 12-18s

### Source

https://vanilla.warcraftlogs.com/reports/W2h8ZXkL6yHmRr1d#fight=16&hostility=1&type=casts&source=78&ability=3391
https://vanilla.warcraftlogs.com/reports/KnTHvJ2MP1rpLBzb#fight=29&hostility=1&type=casts&source=70&ability=3391
https://vanilla.warcraftlogs.com/reports/wLMHcJFy2Xt4TzrW#fight=28&type=casts&hostility=1&source=100&ability=3391
https://vanilla.warcraftlogs.com/reports/ByRmbpQa6MJ1VzGn#fight=13&hostility=1&source=65&type=casts&ability=3391
https://vanilla.warcraftlogs.com/reports/F3z748rMxCNv2LfT#fight=21&type=casts&hostility=1&source=75&ability=3391
https://vanilla.warcraftlogs.com/reports/zLXtDVC9Zmdfnpj2#fight=24&hostility=1&type=casts&source=58&ability=3391
https://vanilla.warcraftlogs.com/reports/Ya2CB17AfXmh3xc9#fight=20&type=casts&hostility=1&source=60&ability=3391
https://vanilla.warcraftlogs.com/reports/Qbnkd18WgGjFfqLa#fight=41&type=casts&hostility=1&source=68&ability=3391
https://vanilla.warcraftlogs.com/reports/yCWL6amKfYNxHhPR#fight=26&type=casts&hostility=1&source=81&ability=3391
https://vanilla.warcraftlogs.com/reports/V642LCy3GXhJf9Kb#fight=24&type=casts&hostility=1&source=59&ability=3391
https://vanilla.warcraftlogs.com/reports/k7XM4aWQcDybGBZv#fight=16&type=casts&hostility=1&source=44&ability=3391

### Steps to reproduce the problem

1. `.go c id 11382`
2. see if Ohgan casts Thrash within a timer.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Si1ker** [comment]
16sec
16sec - 16sec- 15sec
16sec - 18sec - 14sec
13sec - 16sec - 13sec
14sec - 16sec - 15sec - 16sec
15sec - 19sec - 15sec - 18sec
15sec - 19sec - 15sec - 14sec
13sec - 13sec - 17sec
17sec
14sec - 19sec - 13sec

indeed 12-18 seems the sweet spot 🐱
