### ISSUE TITLE
[AQ20] General Rajaxx - Waves 6 chain pull waves 7

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12745]
### Current Behaviour

Wave 6 chain pulls Wave 7 because some mobs of the wave path around the center object to the wrong side

### Expected Blizzlike Behaviour

the waves shouldnt pull others wavrs

### Steps to reproduce the problem

- .tele aq20
- Do Rajaxx waves until the waves 6

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/3920

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

**Comment by Maelthyrr** [comment]
Probably the same issue than with hakkar and in BWL. 

During my debug with Hakkar, it's seems that come from CallAssistance functions in GridNotifier

**Comment by Maelthyrr** [comment]
> Probably the same issue than with hakkar and in BWL. 
> 
> During my debug with Hakkar Trashs, it's seems to come from CallAssistance functions in GridNotifier

**Comment by temperrr** [comment]
I noticed 1 of the pack of 6 going the right side round, pulling wave 7.
