### ISSUE TITLE
Player ({}) tries to learn already active spell: {}

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#12742]
### Current Behaviour

When visiting a class or weapons instructor, on most occasions, the following message appears on the console.

```
Player (GUID Full: 0x0000000000000005 Type: Player Low: 5) tries to learn already active spell: 266
Player (GUID Full: 0x0000000000000005 Type: Player Low: 5) tries to learn already active spell: 3018
Player (GUID Full: 0x0000000000000005 Type: Player Low: 5) tries to learn already active spell: 196
Player (GUID Full: 0x0000000000000005 Type: Player Low: 5) tries to learn already active spell: 198
```

![learn_already](https://user-images.githubusercontent.com/2810187/184584205-b8774e9b-d4ce-41f4-ab27-affff8fe9122.png)

These messages are some examples.

### Expected Blizzlike Behaviour

Because it is the first time we learn the skill, the message should not appear in the console. Since the spell or skill is not yet known to the player. However, the emulator interprets it as if he has them.

### Source

It does not happen only with these spells/skills, but at least these are some examples.

- https://www.wowhead.com/spell=63645/activating-primary-spec
- https://www.wowhead.com/spell=63644/activating-secondary-spec
- https://www.wowhead.com/spell=199/two-handed-maces
- https://www.wowhead.com/spell=3918/rough-blasting-powder
- https://www.wowhead.com/spell=3919/rough-dynamite
- https://classic.wowhead.com/spell=3920/crafted-light-shot
- https://classic.wowhead.com/spell=4073/mechanical-dragonling

#### Case 1

1. Create a new character.
2. Raise it to level 40.
3. Go to the class instructor, and try to learn the double specialization of talents.
4. Check the console.

#### Case 2

1. Go to the weapons instructor of any capital city
2. Learn some skills and check the console.

### Extra Notes

None

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3771a7120d96

### Operating system

Windows 10

### Custom changes or Modules

None

**Comment by acidmanifesto** [comment]
I recommend we move it to LOG_DEBUG since this seems more of a diagnostic even message then a actual error.
https://github.com/azerothcore/azerothcore-wotlk/blob/b2e449fd15e38b4778a42650f388b8213cf62a6a/src/server/game/Entities/Player/Player.cpp#L3215

**Comment by pangolp** [comment]
Maybe it could be a solution, however, what I don't understand, is why he thinks we are learning 2 or more times the spell, when it is the first time we do it. That is what seems really strange to me. There must be some validator that is wrong for sure, related to the trainer. Because at the moment, it happened only with trainers, I don't know if it happens also with other type, like achievements.

**Comment by Kitzunu** [comment]
Should debug why this is happening

**Comment by Kitzunu** [comment]
Sure, if it is intended then thats fine

**Comment by pangolp** [comment]
Thanks.
