### ISSUE TITLE
[Silithus] Followup Envelopes should always contain a new task

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12748]
https://github.com/chromiecraft/chromiecraft/issues/3930

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Followup envelopes for tactical and logistical quests in Silithus can open up empty (actually, they to this more often than not).

### Expected Blizzlike Behaviour

they should always contain at least one quest item to start another mission.
the quest items might be unique tho, thus it can still happen that you cannot loot the envelope or it being empty, because the one it is supposed to contain is already in your inventory.
but, the envelope should never be empty from the beginning.

### Source

https://classic.wowhead.com/guides/wow-classic-field-duty-cenarion-circle-silithus

### Steps to reproduce the problem

.additem 21386
or
.additem 20805
or
.additem 21133

and open them

### Extra Notes

Lack of a groupID, most likely.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
I tried to use this query. Source is Vmangos. But for some reason it did not work with item 20805. It only dropped either one specific item (XI) or nothing at all.

```
DELETE FROM `item_loot_template` WHERE (`Entry` IN (20805, 21133, 21386));
INSERT INTO `item_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(20805, 20807, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing I'),
(20805, 20939, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing II'),
(20805, 20940, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing III'),
(20805, 21262, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing VIII'),
(20805, 21265, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing IX'),
(20805, 21514, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing XI'),
(21133, 20943, 0, 0, 0, 1, 1, 1, 1, 'Followup Tactical Assignment - Tactical Task Briefing X'),
(21133, 20945, 0, 0, 0, 1, 1, 1, 1, 'Followup Tactical Assignment - Tactical Task Briefing II'),
(21133, 20947, 0, 0, 0, 1, 1, 1, 1, 'Followup Tactical Assignment - Tactical Task Briefing IV'),
(21133, 20948, 0, 5, 0, 1, 1, 1, 1, 'Followup Tactical Assignment - Tactical Task Briefing V'),
(21133, 21167, 0, 0, 0, 1, 1, 1, 1, 'Followup Tactical Assignment - Tactical Task Briefing VIII'),
(21133, 21245, 0, 0, 0, 1, 1, 1, 1, 'Followup Tactical Assignment - Tactical Task Briefing I'),
(21386, 21378, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing I'),
(21386, 21379, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing II'),
(21386, 21380, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing III'),
(21386, 21381, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing IX'),
(21386, 21384, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing VIII'),
(21386, 21514, 0, 0, 0, 1, 1, 1, 1, 'Followup Logistics Assignment - Logistics Task Briefing XI');

```

**Comment by pangolp** [comment]
Does the envelope always have to contain the quest item? Because I did a couple of tests, I don't know if they were correct, and I only received the quest items 2 times. I used the additem command, 15 times and this was the result.

![WoWScrnShot_081522_215053](https://user-images.githubusercontent.com/2810187/184762821-c9834a21-a401-4159-a05a-451b4274c1c0.jpg)

**Comment by Gultask** [comment]
Ah, it was a problem with faction-exclusive items, that's why we aren't seeing certain drops 😛

**Comment by temperrr** [comment]
You can use condition to make it drop / not drop so it wont consider it
