### ISSUE TITLE
when  runing  ./acore.sh db-assembler import-updates ,report "ERROR 1091 (42000) at line 54: Can't DROP 'taxiPath'; check that column/key exists"

### ISSUE THREAD

**Issue by dustxdustx** [azerothcore/azerothcore-wotlk#12741]
### Current Behaviour

when  runing  ./acore.sh db-assembler import-updates ,report **"ERROR 1091 (42000) at line 54: Can't DROP 'taxiPath'; check that column/key exists"**,and suspend the process of database updating。

### Expected Blizzlike Behaviour

  runing  ./acore.sh db-assembler import-updates and it be exec success.

### Steps to reproduce the problem

1.  cd /azerothcore-wotlk
2.  git pull
3. ./acore.sh db-assembler import-updates

### AC rev. hash/commit

 AC> AzerothCore rev. 3771a7120d96 2022-08-12 22:52:52 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80029
Using CMake version: 3.16.3
Compiled on: Linux 5.15.35-1-pve
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autobalance
- mod-custom-login
- mod-eluna

### Operating system

Ubuntu 20.04.3 LTS in docker container

**Comment by ThatEuler** [comment]
This issue also happens when making a new acore-docker setup.

```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1091 (42000) at line 3: Can't DROP 'taxiPath'; check that column/key exists

Applying of file '/azerothcore/data/sql/updates/db_characters/2022_08_07_00.sql' to database 'acore_characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Character database, see log for details.
```

the affected image

```
[
    {
        "Id": "sha256:d5a3a0625f1a6d1f79bfb27f849e9394706219f7e499fe5da62584d6b952882d",
        "RepoTags": [
            "acore/ac-wotlk-worldserver:master"
        ],
        "RepoDigests": [
            "acore/ac-wotlk-worldserver@sha256:cc49f9e66ba449d1460451527c6810026fc843f29288b17313349ac801d1efe6"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-08-15T15:27:54.414038434Z",
```

**Comment by Kitzunu** [comment]
db-assembler is dropped and no longer in use. Automatic DB importer is launched when the servers are launched

**Comment by dustxdustx** [comment]
@Kitzunu  AS you  said :Automatic DB importer is launched when the servers are launched,  I change Updates.EnableDatabases = 7 in worldserver.conf. 
and run  /azerothcore-wotlk/acore.sh run-worldserver, It can''t startup  succcessed. error information as blow：

Updating Auth database...
>> Auth database is up-to-date! Containing 2 new and 29 archived updates.
 
Updating Character database...
>> Applying update "2022_08_07_00.sql" 'AC27074'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1091 (42000) at line 3: Can't DROP 'taxiPath'; check that column/key exists

Applying of file '/azerothcore-wotlk/data/sql/updates/db_characters/2022_08_07_00.sql' to database 'acore_characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Character database, see log for details.
Closing down DatabasePool 'acore_world'.
Asynchronous connections on DatabasePool 'acore_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_world' closed.
Closing down DatabasePool 'acore_characters'.
Asynchronous connections on DatabasePool 'acore_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_characters' closed.
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.
exit code: 1

**Comment by dustxdustx** [comment]
@Kitzunu  reopen the Issue,please

**Comment by Kitzunu** [comment]
I just did a squash yesterday. Update your core and this is fixed

**Comment by dustxdustx** [comment]
@Kitzunu 
I flowing these steps:
1.git pull 
2./acore.sh compiler build
3.. /startup.sh
4.world server can't start
when I  run  tmux attach -t world-session
 console information  as blow:

Opening DatabasePool 'acore_characters'. Asynchronous connections: 1, synchronous connections: 2.
DatabasePool 'acore_characters' opened successfully. 3 total connections running.
 
Opening DatabasePool 'acore_world'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool 'acore_world' opened successfully. 2 total connections running.
 
Updating Auth database...
>> Auth database is up-to-date! Containing 1 new and 31 archived updates.
 
Updating Character database...
>> Applying update "2022_08_07_00.sql" 'AC27074'...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1091 (42000) at line 3: Can't DROP 'taxiPath'; check that column/key exists

Applying of file '/azerothcore-wotlk/data/sql/archive/db_characters/7.x/2022_08_07_00.sql' to database 'acore_characters' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the Character database, see log for details.
Closing down DatabasePool 'acore_world'.
Asynchronous connections on DatabasePool 'acore_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_world' closed.
Closing down DatabasePool 'acore_characters'.
Asynchronous connections on DatabasePool 'acore_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_characters' closed.
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.
exit code: 1
worldserver terminated, restarting...
worldserver Terminated after 0 seconds, termination count: : 6
worldserver Restarter exited. Infinite crash loop prevented. Please check your system
