### ISSUE TITLE
[Loot] Incorrect Idol of Brutality drops

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#12757]
### Current Behaviour

[Idol of Brutality](https://wowgaming.altervista.org/aowow/?item=23198) can drop from NPCs it is not supposed to drop from.

![idolofbrutality](https://user-images.githubusercontent.com/62797536/184849574-a08e85fa-a6b2-497c-a00e-02ffb4ff1135.jpg)

### Expected Blizzlike Behaviour

Idol of Brutality should only drop from [Magistrate Barthilas](https://wowgaming.altervista.org/aowow/?npc=10435) in Stratholme.

### Source

List of incorrect drops:

```
SELECT entry, item, chance, comment
FROM creature_loot_template
WHERE item = '23198'
  AND entry != '10435'; -- Magistrate Barthilas
```

| entry | item | chance | comment | 
| ---: | ---: | ---: | --- | 
| 6560 | 23198 | 0,02 | Stone Guardian - Idol of Brutality | 
| 9817 | 23198 | 0,02 | Blackhand Dreadweaver - Idol of Brutality | 
| 9818 | 23198 | 0,02 | Blackhand Summoner - Idol of Brutality | 
| 9819 | 23198 | 0,02 | Blackhand Veteran - Idol of Brutality | 
| 10083 | 23198 | 0,02 | Rage Talon Flamescale - Idol of Brutality | 
| 10318 | 23198 | 0,02 | Blackhand Assassin - Idol of Brutality | 
| 10319 | 23198 | 0,02 | Blackhand Iron Guard - Idol of Brutality | 
| 10366 | 23198 | 0,02 | Rage Talon Dragon Guard - Idol of Brutality | 
| 10399 | 23198 | 0,02 | Thuzadin Acolyte - Idol of Brutality | 
| 10405 | 23198 | 0,02 | Plague Ghoul - Idol of Brutality | 
| 10407 | 23198 | 0,02 | Fleshflayer Ghoul - Idol of Brutality | 
| 10413 | 23198 | 0,02 | Crypt Beast - Idol of Brutality | 
| 10416 | 23198 | 0,02 | Bile Spewer - Idol of Brutality | 
| 10417 | 23198 | 0,02 | Venom Belcher - Idol of Brutality | 
| 10422 | 23198 | 0,02 | Crimson Sorcerer - Idol of Brutality | 
| 10424 | 23198 | 0,02 | Crimson Gallant - Idol of Brutality | 
| 10447 | 23198 | 0,02 | Chromatic Dragonspawn - Idol of Brutality | 
| 10463 | 23198 | 0,02 | Shrieking Banshee - Idol of Brutality | 
| 10464 | 23198 | 0,02 | Wailing Banshee - Idol of Brutality | 
| 10469 | 23198 | 0,02 | Scholomance Adept - Idol of Brutality | 
| 10476 | 23198 | 0,02 | Scholomance Necrolyte - Idol of Brutality | 
| 10477 | 23198 | 0,02 | Scholomance Necromancer - Idol of Brutality | 
| 10680 | 23198 | 0,05 | Summoned Blackhand Dreadweaver - Idol of Brutality | 
| 10814 | 23198 | 0,02 | Chromatic Elite Guard - Idol of Brutality | 
| 11257 | 23198 | 0,02 | Scholomance Handler - Idol of Brutality | 
| 11340 | 23198 | 0,07 | Hakkari Blood Priest - Idol of Brutality | 
| 11350 | 23198 | 0,02 | Gurubashi Axe Thrower - Idol of Brutality | 
| 11351 | 23198 | 0,02 | Gurubashi Headhunter - Idol of Brutality | 
| 11357 | 23198 | 0,04 | Son of Hakkar - Idol of Brutality | 
| 11361 | 23198 | 0,02 | Zulian Tiger - Idol of Brutality | 
| 11365 | 23198 | 0,02 | Zulian Panther - Idol of Brutality | 
| 11371 | 23198 | 0,02 | Razzashi Serpent - Idol of Brutality | 
| 11372 | 23198 | 0,02 | Razzashi Adder - Idol of Brutality | 
| 11582 | 23198 | 0,02 | Scholomance Dark Summoner - Idol of Brutality | 
| 11830 | 23198 | 0,02 | Hakkari Priest - Idol of Brutality | 
| 12100 | 23198 | 0,02 | Lava Reaver - Idol of Brutality | 
| 12101 | 23198 | 0,02 | Lava Surger - Idol of Brutality | 
| 12121 | 23198 | 0,02 | Drakan - Idol of Brutality | 
| 13996 | 23198 | 0,02 | Blackwing Technician - Idol of Brutality | 
| 14532 | 23198 | 0,02 | Razzashi Venombrood - Idol of Brutality | 
| 14821 | 23198 | 0,02 | Razzashi Raptor - Idol of Brutality | 
| 14825 | 23198 | 0,02 | Withered Mistress - Idol of Brutality | 
| 15043 | 23198 | 0,02 | Zulian Crocolisk - Idol of Brutality | 
| 15209 | 23198 | 0,02 | Crimson Templar - Idol of Brutality | 
| 15211 | 23198 | 0,02 | Azure Templar - Idol of Brutality | 
| 15213 | 23198 | 0,02 | Twilight Overlord - Idol of Brutality | 
| 15250 | 23198 | 0,02 | Qiraji Slayer - Idol of Brutality | 
| 15307 | 23198 | 0,02 | Earthen Templar - Idol of Brutality | 
| 15325 | 23198 | 0,02 | Hive'Zara Wasp - Idol of Brutality | 
| 15343 | 23198 | 0,02 | Qiraji Swarmguard - Idol of Brutality | 
| 15462 | 23198 | 0,02 | Spitting Scarab - Idol of Brutality | 
| 15754 | 23198 | 0,12 | Greater Anubisath Warbringer - Idol of Brutality | 

### Steps to reproduce the problem

1. Check query above

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5734630e7e3004d98b0c1a9165986ebe629238b8

### Operating system

Ubuntu 20.04

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pebeto** [comment]
You're wrong. Actually, in WOTLK databases that item is dropped by other mobs. You're basing your issue in the TBC database.

[Twinstar Source](https://wotlk-twinhead.twinstar.cz/?item=23198)
[WotlkDB Source](https://wotlkdb.com/?item=23198)

**Comment by acidmanifesto** [comment]
> You're wrong. Actually, in WOTLK databases that item is dropped by other mobs. You're basing your issue in the TBC database.
> 
> [Twinstar Source](https://wotlk-twinhead.twinstar.cz/?item=23198)
> [WotlkDB Source](https://wotlkdb.com/?item=23198)

Those sources are pserver dbs not udb or retail datamined.
