### ISSUE TITLE
worldserver.exe SQL ERROR after compiling latest commit with latest DB updates

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1276]
Broken DB or Broken Code ?

##### SMALL DESCRIPTION:

[ERROR]: In mysql_stmt_prepare() id: 3, sql: "SELECT CreatureID, GroupID, ID, Text, Type, Language, Probability, Emote, Duration, Sound, BroadcastTextId, TextRange FROM creature_text"
[ERROR]: Unknown column 'CreatureID' in 'field list'
DatabasePool acore_world NOT opened. There were errors opening the MySQL connections. Check your SQLDriverLogFile for specific errors.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just run worldserver.exe and the error messages will show.
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

3b281e2

##### OPERATING SYSTEM:

Win 10/7

##### MODULES:

mod-account-achievements
mod-buff-command
mod-customlogin
mod-eluna-lua-engine
mod-instance-reset
mod-npcallmounts
mod-npcbeastmaster
mod-npcbuffer
mod-npcenchanter
mod-npc-free-professions
mod-npcgambler
mod-premium
mod-solocraft
mod-transmog
mod-vas-autobalance

##### OTHER CUSTOMIZATIONS:

No

**Comment by BarbzYHOOL** [comment]
You're missing some updates 

 [ERROR]: Unknown column 'CreatureID' in 'field list'

**Comment by poszer** [comment]
Apply updates

**Comment by gtao725** [comment]
I did apply them all, except the 2019_01_12 which I left out because it complained about an sql syntax error

**Comment by gtao725** [comment]
srry i meant 2019_01_12_01. I am trying to import it manually now without using db_assembler

**Comment by gtao725** [comment]
ok the manual import worked. Thx guys!
