### ISSUE TITLE
[AQ20] Ossirian - Number of crystals that can be up simultaneously is too low.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12762]
### Current Behaviour

Only 1 crystal can be up at a time, excluding the initial crystal.

### Expected Blizzlike Behaviour

A matter of debate:
 - Retail has 6.
 - Comments from Wowhead claim at least 5 in 4.0.3
 - WotLK footage shows at least 3

### Source

https://youtu.be/4ekKACUEMAE?t=141 shows 3.

there are few of them in the area (5+) ([source](https://www.wowhead.com/object=180619/ossirian-crystal#comments:id=1374817) Patch 4.0.3)

This is the scouting mechanic, that by using the crystals along the sides of the arena it forces them to spawn using the 3 spawn points in the center
>this will almost guarantee all three crystals being ready constantly in the center of the map. ([source](https://wowwiki-archive.fandom.com/wiki/Ossirian_the_Unscarred))

### Steps to reproduce the problem

1. `.go xyz -9397 1947 87 509 2.5`
2. Engage Ossirian.
3. Count the crystals that spawned. Ignore the crystal that was already present there.
4. See if using one respawns another somewhere else so that the number of crystal up simultaneously is always constant.

### Extra Notes

Keep in mind that:

1. One crystal in particular (the one that is already present before the boss is engaged) **is completely separate from this issue** and is supposed to have a different behaviour from the rest of them.
2. There are 11 spawn points that they can spawn from. Several of them are obscured by pillars so they cannot be seen if the player does not move.
3. Mechanics change in-between expansions. For example: Cataclysm decreased Razorgore MC debuff from 60s to 10s.

More info here: https://github.com/azerothcore/azerothcore-wotlk/issues/12472

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask
`WotLK footage shows at least 3`
It inclcudes the starting crystal?
