### ISSUE TITLE
Apply 2019_01_12_01.sql fail

### ISSUE THREAD

**Issue by brussens** [azerothcore/azerothcore-wotlk#1278]
##### SMALL DESCRIPTION:

Friends, I want to raise the problem of apply last DB updates, because it appears due to the restriction of the mysql `max_allowed_packet` directive.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Execute multiple files in HeidiSQL

##### EXTRA NOTES:

It is worth adding a note to the wiki that the size of the `max_allowed_packet` directive should be changed (for me, a change in the value of 128 * 1024 * 1024 * 3 worked) or split `data/sql/updates/db_world/2019_01_12_01.sql` file.
```mysql
/* Use in mysql console */
set global max_allowed_packet = 128 * 1024 * 1024 * 3;
```

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

latest

##### OPERATING SYSTEM:

WIN10 X64 with MariaDB 10.3

##### MODULES:

None.

##### OTHER CUSTOMIZATIONS:

None.

**Comment by poszer** [comment]
Confirmed

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/1279

**Comment by FrancescoBorzi** [comment]
@brussens can you please test my PR #1279

**Comment by brussens** [comment]
Maybe it's better to split this file into two parts?

**Comment by brussens** [comment]
Changing this directive to production servers is not the best solution.

**Comment by FrancescoBorzi** [comment]
@brussens we're fixing it, no worries :)
