### ISSUE TITLE
Champion's Trial : The Black Knight

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#12798]
### Current Behaviour

The fight with the black knight starts but disappears when getting off the mount

### Expected Blizzlike Behaviour

he should start the fight normally and do his normal phases

### Source

https://wowpedia.fandom.com/wiki/Trial_of_the_Champion#The_Black_Knight

### Steps to reproduce the problem

go to champion's trial
complete the two initial events.
talk to the npc to start the fight
wait for the dialogue to end and the black knight gets off the mount
watch as it disappears

### Extra Notes

other reports related to Champion's Trial

#12794 -> champion's trial the NPC does not kneel after the end of the fight, with hp 1 he continues the attack further 
#12612 ->  Trial of the Champion
#10717 -> Trial of Champions Stage 1 Error

### AC rev. hash/commit

560a74e757da51cb45a35d00b845e1d621a1b54c

### Operating system

Ubuntu 20.04

**Comment by Tony931023** [comment]
https://user-images.githubusercontent.com/4868094/185721366-e04c0e1a-4715-402c-8e96-ce3356fdfe7c.mp4

**Comment by Tony931023** [comment]
If you use .resp all after the kk is gone you can start the fight.
Sorry for the poor quality of the video

https://user-images.githubusercontent.com/4868094/185721688-a9515e67-0a94-4dbb-9984-d486a9ec06a0.mp4

**Comment by Tony931023** [comment]
@UltraNix Could you give this PR a review since it has been broken for a while

**Comment by UltraNix** [comment]
@Tony931023 #12807

**Comment by Tony931023** [comment]
i will compile and test the fix
