### ISSUE TITLE
champion's trial the NPC does not kneel after the end of the fight, with hp 1 he continues the attack further

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#12794]
### Current Behaviour

we start the standard dialogue in the champion's trial
, everything is fine, we killed the phase with the horses, we start beating the bosses, var has 1 hp left, he has to sit on his knee, so no, he beats like he's not himself, and you can't put him down

### Expected Blizzlike Behaviour

![WoWScrnShot_081922_180314](https://user-images.githubusercontent.com/98691968/185659677-c839bcdf-6395-4ca5-b0ed-86d5aadd88da.jpg)

champion's trial the NPC does not kneel after the end of the fight, with hp 1 he continues the attack further

### Steps to reproduce the problem

we start the standard dialogue in the champion's trial
, everything is fine, we killed the phase with the horses, we start beating the bosses, var has 1 hp left, he has to sit on his knee, so no, he beats like he's not himself, and you can't put him down

### AC rev. hash/commit

we start the standard dialogue in the champion's trial
, everything is fine, we killed the phase with the horses, we start beating the bosses, var has 1 hp left, he has to sit on his knee, so no, he beats like he's not himself, and you can't put him down

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-1v1-arena, mod-ah-bot, mod-anticheat, mod-cfbg, mod-congrats-on-level, mod-guildhouse, mod-learn-spells, mod-npc-buffer, mod-npc-enchanter, mod-npc-gambler, mod-pocket-portal, mod-transmog

**Comment by Tony931023** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12807#issuecomment-1221328365

**Comment by Kitzunu** [comment]
Add Hash/Commit from .server debug

**Comment by Tony931023** [comment]
@Kitzunu  this Hash/Commit works with the one I tried it with https://github.com/azerothcore/azerothcore-wotlk/commit/560a74e757da51cb45a35d00b845e1d621a1b54c

**Comment by MegaserverRU** [comment]
part solved
