### ISSUE TITLE
world_update.sql typo

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1281]
##### SMALL DESCRIPTION:
`-- DB update 2019_01_13_00 -> 2019_01_14_00`
```
DELETE FROM `creature_text` WHERE `entry` IN (14392);
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`) VALUES 
(14392, 0, 0, 'NEFARIAN IS SLAIN! people of Orgrimmar, bow down before the might of $N and his allies for they have laid a blow against the Black Dragonflight that is sure to stir the Aspects from their malaise! This defeat shall surely be felt by the father of the Black Flight: Deathwing reels in pain and anguish this day!', 14, 0, 100, 0, 0, 0, 'Overlord Runthak', 9867),
(14392, 1, 0, 'Be lifted by $N accomplishment! Revel in his rallying cry!', 14, 0, 100, 0, 0, 0, 'Overlord Runthak', 9868);
```
`creature_text` does not have an `entry` column. The now merged PR #1160 changed the column name from `entry` to `CreatureID`.

See:
```
ALTER TABLE `creature_text` CHANGE `entry` `CreatureID` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0';
```

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
c90afdd9e2b6604bb126b4e37821bc5b596957ad

##### OPERATING SYSTEM:
Windows 10

**Comment by BarbzYHOOL** [comment]
for the uppercase stuff it never was an issue for me (but maybe because I changed strict name checking in mysql)


Why it changed to creatureID, entry was quite nice as it's the general name for an ID

Well this should be a very easy fix though

**Comment by wetbrownsauce** [comment]
It was changed to CreatureID to match TC, since the entry in creature_text references creature_template.entry

**Comment by BarbzYHOOL** [comment]
> It was changed to CreatureID to match TC, since the entry in creature_text references creature_template.entry

yeah damn hard to mix compatibility with TC and better practices/innovations haha
