### ISSUE TITLE
[AQ20] Buru - Damage Reduction in Phase 1 is not blizzlike.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12826]
https://github.com/chromiecraft/chromiecraft/issues/3979

### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

For the entire first phase, damage to the boss is reduced by 99%

### Expected Blizzlike Behaviour

Damage must not be reduced. Buru should take normal damage.
The data on wowwiki and wowhead guide, as well as some others, is incorrect. Boss never got 99% damage reduction.

[Wowhead comments](https://classic.wowhead.com/npc=15370/buru-the-gorger#comments):
" By kreghx on 2006/12/09 Patch 2.0.1		
Strategy 5: Treat Buru as a Lava Surger. That is, everyone comes into melee range with him. This way, the melee can keep up a consistent dps as he won't run around constantly. The tanks should wear their dps gear during this fight, as there is no tanking involved.

The key to this part of the fight seems to be having your priests spamming Prayer of Healing in your highest dps groups, forgetting about actually tanking Buru and just going all out. Don't forget to Sunder him anyway though - 2250 less armour is a huge difference in dps." 
- this strat is not possible if he has a damage reduction

Discussion on blizzard forum:
- https://us.forums.blizzard.com/en/wow/t/ptr-aq20-is-buru-the-gorger-working-as-intented/559268/19
- https://us.forums.blizzard.com/en/wow/t/no-egg-buru/625311/6

 - Logs
 https://vanilla.warcraftlogs.com/reports/AVD7acpxgqMCH9zW#fight=13&type=damage-taken&hostility=1&source=57

Damage reduction definitely wasn't on wow classic. I don't have 100% proofs about the original wow. As proof, I can only provide a few videos from 2006, where you can clearly see the boss taking normal damage.

### Source

 https://classic.wowhead.com/npc=15370/buru-the-gorger#comments
 - Logs:
 https://vanilla.warcraftlogs.com/reports/AVD7acpxgqMCH9zW#fight=13&type=damage-taken&hostility=1&source=57
 - Some videos:
 https://www.youtube.com/watch?v=C5cUB4QOFds
 https://www.youtube.com/watch?v=3iWljIAVmlg
 https://www.youtube.com/watch?v=eXDwwKelA9w
 https://www.youtube.com/watch?v=7iNKrlVf96Y
 https://www.youtube.com/watch?v=JrQflmHhxdg

### Steps to reproduce the problem

1. Hit boss with any spell

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12822
