### ISSUE TITLE
[vs] Compilation errors MariaDB

### ISSUE THREAD

**Issue by Mutevazi** [azerothcore/azerothcore-wotlk#1282]
##### CURRENT BEHAVIOUR:

Please tell me how to solve?

##### ERRORS:

1. Error C2065 CR_INVALID_CONN_HANDLE: undeclared identifier shared D:\azerothcore-wotlk\src\common\Database\MySQLConnection.cpp 492
2. Error C2051 The value of the expression for the selection is not a constant shared D:\azerothcore-wotlk\src\common\Database\MySQLConnection.cpp 492
3. Error LNK1181 cannot open the input file "..\..\common\Release\shared.lib" authserver D:\Azeroth\Maria\src\server\authserver\LINK 1

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

WIN 10 x64 MariaDB 10.3
VS 15 (2017)

**Comment by FrancescoBorzi** [comment]
@Mutevazi is it a clean AzerothCore source code or you applied any modifications/modules ?

**Comment by Mutevazi** [comment]
> @Mutevazi is it a clean AzerothCore source code or you applied any modifications/modules ?

clean

**Comment by Viste** [comment]
try MariaDB 10.1 with 10.2+ you got errors becouse we don't support it.
In 10.2 some func are changed and there is no compatibility between mysql and maria here
for exemple you got error on:
case CR_INVALID_CONN_HANDLE:
what is deleted in mariadb 10.2

**Comment by Mutevazi** [comment]
> try MariaDB 10.1 with 10.2+ you got errors becouse we don't support it.
> In 10.2 some func are changed and there is no compatibility between mysql and maria here
> for exemple you got error on:
> case CR_INVALID_CONN_HANDLE:
> what is deleted in mariadb 10.2


Good friend, give me time to check.

**Comment by Viste** [comment]
@Mutevazi don't worry i update my mariaDB on server to 10.3 and open pull for add compatibility

**Comment by Mutevazi** [comment]
@Viste This error comes out again... MariaBD 10.2

**Comment by Winfidonarleyan** [comment]
> try MariaDB 10.1

**Comment by Mutevazi** [comment]
@Winfidonarleyan Now we will try.

**Comment by Viste** [comment]
@Mutevazi as i say you need 10.1 or lower on 10.2 and higher you get errors

**Comment by Viste** [comment]
@Mutevazi no problem! i done PR for support 10.2+ if you can test will be nice #1284

**Comment by brussens** [comment]
MariaDB is compatible with Mysql, so when preparing a compilation in Cmake, you can use the DEV library of the usual Mysq. After compilation you can use MariaDB server.
![screenshot](https://user-images.githubusercontent.com/2656715/51228912-6f3d6380-196b-11e9-827f-d6631a324248.jpg)

**Comment by Viste** [comment]
@brussens bad idea use mysql dev library with MariaDB 10.2+

**Comment by Mutevazi** [comment]
@brussens hmm.... im not have ur interface -> [screenshot](https://i.imgur.com/adUW40I.png)

**Comment by brussens** [comment]
@Viste Well, why? Libraries have BC, so nothing terrible for local use will happen.
@Mutevazi i use advanced configuration.
