### ISSUE TITLE
Mistake mod-anticheat

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#12829]
### Current Behaviour

How can this be fixed?
![2022-08-23_10-05-51](https://user-images.githubusercontent.com/98691968/186094569-a87359b4-d20b-436f-ad45-f47602825c76.png)

[1136] Column count doesn't match value count at row 1
Unhandled MySQL errno 1136. Unexpected behaviour possible.
SQL(p): INSERT INTO account_banned VALUES (3, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()+0, Server, Anti cheat module Auto Banned Account for Reach Cheat Threshhold, 1)
 [ERROR]: [1062] Duplicate entry '3-1661238008' for key 'PRIMARY'

### Expected Blizzlike Behaviour

no

### Source

no

### Steps to reproduce the problem

After the anti-cheat is triggered, such an error appears, how can it be fixed?

### Extra Notes

no

### AC rev. hash/commit

AzerothCore

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-anticheat

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/mod-anticheat/issues/new/choose

**Comment by heyitsbench** [comment]
Close this issue, it's not related to AC. And in the future, please fill out the template completely and correctly.
