### ISSUE TITLE
[Shaman] Visual effect weapon enchants missing

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#12831]
### Current Behaviour

No visual on weapon

### Expected Blizzlike Behaviour
![image](https://user-images.githubusercontent.com/20357406/186229025-8ecd1fe3-e398-4588-960f-aae9098de7ec.png)

### Source

Screenshot taken from Retail Wotlk  Clasic PTR prepatch

### Steps to reproduce the problem

1. enchant weapon with flametongue, rockbitter, windfury or earthliving

2. see no visual

### AC rev. hash/commit

4cd3b9c20371

### Operating system

 Ubuntu 20.04

### Custom changes or Modules

Chromiecraft modules.

**Comment by UltraNix** [comment]
In case of any visual stuff, we need old wotlk - because they might've changed these visuals on classic.

**Comment by temperrr** [comment]
yep you are correct, no visual. shit :(
