### ISSUE TITLE
Warrior abilities BUG - (Bloodsurge level 10)

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#12832]
### Current Behaviour

It turns out that here on azerothcore when he activates the slam instant is released, but the BUFF doesn't end, as you can confirm in the video below.

So you can hit non-stop with SLAM active and no countdown.

![bug](https://user-images.githubusercontent.com/58153179/186239492-2f5cf91f-641c-4817-a910-d772a94c7a0b.jpg)

[![IMAGE ALT TEXT](http://img.youtube.com/vi/NSXr_egFdFg/0.jpg)](https://www.youtube.com/watch?v=NSXr_egFdFg "Video")

### Expected Blizzlike Behaviour

Expected Blizzlike Behaviour:

[![IMAGE ALT TEXT](http://img.youtube.com/vi/vAsFw0s5plI/0.jpg)](https://www.youtube.com/watch?v=vAsFw0s5plI"Video")

### Steps to reproduce the problem

1. Use the Warrior
2. Test Bloodsurge and compare with the first video (wrong)
3. Confirm that the second video should be correct.

### AC rev. hash/commit

4cd3b9c20371

### Operating system

Windows

**Comment by Gultask** [comment]
https://github.com/chromiecraft/chromiecraft/issues/3269

1. `.learn 11605` `.cheat cooldown` `.cheat power`
2. `.aura 46916`
3. Cast multiple Slam without the buff being consumed
