### ISSUE TITLE
Error time events in the calendar.

### ISSUE THREAD

**Issue by Mutevazi** [azerothcore/azerothcore-wotlk#1287]
##### SMALL DESCRIPTION:

If you create a guild event or an event for a player, then the set time is reduced by 3 hours.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Open calendar
2. Create event
3. Select a time (for example, 10:00 AM) and click save.
4. Click on the event created and see the selected time.
If you put 10:00 AM will show 07:00 AM

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Windows 10 x64

##### MODULES:

clear

**Comment by wetbrownsauce** [comment]
@Mutevazi please include your AC Hash/commit in your issue

**Comment by brussens** [comment]
@wetbrownsauce this behavior is very old. I fix it in file `src/common/Packets/ByteBuffer.h`.
The next changes fix it behavior (my timezone Europe/Moscow).
```cpp
#ifdef OS_WIN
    return uint32(mktime(&lt));
#else
    return uint32(mktime(&lt));
#endif
```

**Comment by FrancescoBorzi** [comment]
@brussens thanks for your suggestion, can you please [open a PR with it](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request)?

**Comment by brussens** [comment]
@FrancescoBorzi ok, no problem. But i think this needs in tests.

**Comment by FrancescoBorzi** [comment]
of course all PRs will be tested before merging them

**Comment by brussens** [comment]
ok. 10 min please.

**Comment by Mutevazi** [comment]
@brussens Good Job. ty bro ^^

**Comment by brussens** [comment]
Thanks :)
