### ISSUE TITLE
Quest proof of demise available without prerequisite quest

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#12873]
Original chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/3855 Confirmed

### What client do you play on?

ruRU

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

[Proof of Demise](https://tbc.wowhead.com/quest=374) available without prerequisite [quest](https://tbc.wowhead.com/?quest=427)

### Expected Blizzlike Behaviour
		
Should not be able to get this quest until the first quest in the "At War With the Scarlet Crusade" quest line https://tbc.wowhead.com/quest=427/at-war-with-the-scarlet-crusade is completed

### Source

https://tbc.wowhead.com/quest=374/proof-of-demise#comments:id=52484
`You are required to have completed https://tbc.wowhead.com/?quest=427 before this quest becomes available`

### Steps to reproduce the problem

1. .go c 29798
2. Talk to Deathgaurd Burgess and notice he gives the quest [Proof of Demise](https://tbc.wowhead.com/quest=374) without doing any quests to unlock it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by pangolp** [comment]
```sql
UPDATE `quest_template_addon` SET `PrevQuestID`=427 WHERE `ID`=374;
```
@acidmanifesto I don't know if that is enough, the problem is that I would have to update the emulator first, because I have it a bit outdated. Or maybe I should add some conditional to the quest, so that it only allows the player to take it, if he has completed the quest mentioned. Because what I propose, I think it is when it is a chain, and in this case, I think it is not a chain, they are quests that depend on another quest.

**Comment by pangolp** [comment]
They are now testing another alternative.

```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND `SourceEntry`=374;

INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19, 0, 374, 0, 0, 8, 0, 427, 0, 0, 0, 0, 0, '', 'Enable quest 374, only if the player has completed quest 427.');
```

**Comment by pangolp** [comment]
Now I create the PR and link it. It seems that with the conditions, it is enough.
