### ISSUE TITLE
AQ20 - General Rajaxx Kaldorei Elites unattackable by horde

### ISSUE THREAD

**Issue by Sneften** [azerothcore/azerothcore-wotlk#12896]
Original post from Chromiecraft: [#4006](https://github.com/chromiecraft/chromiecraft/issues/4006) Confirmed on ptr.

**What client do you play on?**
enGB

**Faction**
Horde

**Content Phase:**
60

**Current Behaviour**
Horde faction can't attack the Kaldorei Elites even though neutral with Cenarion Circle 

**Expected Blizzlike Behaviour**
Both factions should be able to attack the Kaldorei elites before gaining friendly reputation with Cenarion Circle.

**Source**
https://github.com/chromiecraft/chromiecraft/issues/3987

**Steps to reproduce the problem**
Start event with a horde character. 

**Extra Notes**
For the Horde character, [Andorov](https://classic.wowhead.com/npc=15471/lieutenant-general-andorov) show as friendly even though neutral with Cencarion Circle.

**AC rev. hash/commit**
https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

**Operating system**
Ubuntu 20.04

**Modules**
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
[lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)
Customizations
None

**Server**
ChromieCraft

**Comment by Maelthyrr** [comment]
I close. Same answers than this: https://github.com/chromiecraft/chromiecraft/issues/3987
Sniffed by @Gultask on ptr classic. You can kill them because at begin you don't the rep to be frienbdly.

**Comment by Sneften** [comment]
Hi @Maelthyrr! Then its a bug the other way around or am i not understanding you correctly? 
"Horde characters can't kill Kaldorei elites even though Neutral with Cenarion Circle".
Also check extra notes.

**Comment by Gultask** [comment]
The faction they are setbat is correct. The problem is that the script is set to modify their faction, causing only alliance players to be able to target and attack them.

Once I get home I'll reopen the issue :)

**Comment by Maelthyrr** [comment]
> Hi @Maelthyrr! Then its a bug the other way around or am i not understanding you correctly? "Horde characters can't kill Kaldorei elites even though Neutral with Cenarion Circle". Also check extra notes.

Sorry, I didn't read extra note. So yes, it's an issue. I repon. Can you modify the post to only show the issue with the horde faction?

**Comment by UltraNix** [comment]
Everything works okay. Just open your `Reputation` tab and set `AtWar` with Cenarion Circle. This rep starts with non-attackable option for players.
