### ISSUE TITLE
[AQ40] Battleguard Sartura aggro range

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#12899]
### Current Behaviour

Boss have small aggro radius.

### Expected Blizzlike Behaviour

Boss should have an extremely long aggro range

### Source

1. https://classic.wowhead.com/guides/battleguard-sartura-temple-of-ahnqiraj-strategy - Additionally, the boss has an extremely long aggro range and will be "body-pulled" from a great distance, so when mounted up and running in, Warriors need to be leading the group towards the boss.
2. https://youtu.be/W7z9kV3iJ_w?t=235

### Steps to reproduce the problem

1. Enter AQ40.
2. Try to engage The Prophet Skeram at difference distances

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/3809

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

**Comment by Si1ker** [comment]
"extremely long" ? xd

![image](https://user-images.githubusercontent.com/61223313/187528337-72653a41-eca1-4559-8624-0265fdc133c4.png)

**Comment by UltraNix** [comment]
I watched multiple videos and also I don't see that "extremely long" aggro range.
