### ISSUE TITLE
[AQ40] Being in combat nearby critters should cause them to attack the player.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#12909]
### Current Behaviour

Qiraji Scarab (15316) and Qiraji Scorpion (15317) do not react to nearby combat.

### Expected Blizzlike Behaviour

They should engage the players that are nearby & in combat. I believe there's a mechanic called combat pulse.

### Source

Retail

### Steps to reproduce the problem

1. `.go c id 15316` or `.go c id 15317`
2. pull a nearby trash mob, see if the critters react.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9724c07528ab2746bd8e38fdc9a062f4854d788c

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask Show me that proof from retail.

**Comment by Gultask** [comment]
Sure, I also needed to sniff to make sure.

In sniffs I see that it 'pulses' on pull and every 3.6s and the range I noticed to be around 10y, maybe a tiny bit less.

https://user-images.githubusercontent.com/100873791/188311791-3c910c9e-f0ad-4ac0-8ed2-9a35bf2917f8.mp4
