### ISSUE TITLE
[Scarab Lord] Head of the Broodlord Lashlayer does not drop for every raid member with the quest.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#12915]
### Current Behaviour

If multiple people have the quest [Only One May Rise](https://www.wowhead.com/wotlk/quest=8288) and kill [Broodlord Lashlayer](https://www.wowhead.com/wotlk/npc=12017), only one [Head of the Broodlord Lashlayer](https://www.wowhead.com/wotlk/item=20383) will drop from the boss.

### Expected Blizzlike Behaviour

The boss should drop one head for every player in the raid group with the quest.

### Source

[Various](https://www.wowhead.com/wotlk/item=20383/head-of-the-broodlord-lashlayer#comments:id=181246) [Wow](https://www.wowhead.com/wotlk/item=20383/head-of-the-broodlord-lashlayer#comments:id=275027)[head](https://www.wowhead.com/wotlk/item=20383/head-of-the-broodlord-lashlayer#comments:id=3081834) [comments](https://www.wowhead.com/wotlk/item=20383/head-of-the-broodlord-lashlayer#comments:id=342879:reply=42290), [an archived Wowpedia article](https://wowpedia.fandom.com/wiki/Head_of_the_Broodlord_Lashlayer?oldid=798684), and the [Wrath Wowhead tooltip](https://user-images.githubusercontent.com/38561765/187628725-f38fd6bc-ee8b-4e3d-9a73-5d3f9779c0c7.png).

### Steps to reproduce the problem

1. Get two players in a raid group together.
2. `.quest add 8288` for both players.
3. Teleport them to BWL and kill Broodlord Lashlayer.
4. Observe that only one head drops.

### Extra Notes

Originally reported at: https://github.com/chromiecraft/chromiecraft/issues/4019

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9724c07528ab2746bd8e38fdc9a062f4854d788c

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by Nyeriah** [comment]
Odd, the item has the flags to drop for everyone

**Comment by heyitsbench** [comment]
> Odd, the item has the flags to drop for everyone

It looks like something was wrong with my DB. I retested on the CC PTR, and [the head did drop for both players in the raid.](https://user-images.githubusercontent.com/38561765/187654882-ff14325a-09c6-43db-845e-5341a57026c3.png)
