### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#12923]
### Current Behaviour

This started happening out of nowhere, my server doesn't have 5 people playing simultaneously and it still bugged somehow.

![image](https://user-images.githubusercontent.com/58153179/187894974-e60c3d76-159c-4274-a41e-b5dcef959f83.png)

Complete log.

[gdb.log](https://github.com/azerothcore/azerothcore-wotlk/files/9469214/gdb.log)

### Expected Blizzlike Behaviour

Above

### Steps to reproduce the problem

I don't know how to reproduce, it fell and I was sleeping and now it doesn't turn on anymore.

### AC rev. hash/commit

ce27bbbc86b7

### Operating system

Ubuntu

**Comment by Nyeriah** [comment]
Do you have custom gameobjects by any chance?

**Comment by htc16** [comment]
> Do you have custom gameobjects by any chance?

No

**Comment by htc16** [comment]
> Do you have custom gameobjects by any chance?

Do you have any idea how I can turn on the server?

**Comment by Nyeriah** [comment]
From the log it looks like it is crashing when trying to load gameobject data. I can only suggest dropping your database and trying fresh as it seems something might be compromised

**Comment by htc16** [comment]
> 

Okay, thanks and I'll do that.

**Comment by htc16** [comment]
Could this have something to do with the auto-restart mod?

**Comment by htc16** [comment]
Guys, I'm not sure what happened, but even going back to a backup from 1 day ago I couldn't solve the problem, so I recompiled everything again and then it worked, the server turned on the initial dB.

Anyway, I'm closing the issue as I'm not sure where the bug went.
