### ISSUE TITLE
Question about honor gains from BGs compared to WOTLK Classic

### ISSUE THREAD

**Issue by Sulan2** [azerothcore/azerothcore-wotlk#12922]
### Current Behaviour

I notice on my ACore server that the amount of honor gained in BGs are way off compared to in WOTLK Classic and ive been trying to figure out what exactly is the right version

I did some testing comparing level 70 BGs

Alterac Valley
kill galv/balinda & Capture tower/bunker.
WOTLK Classic 121 Honor - ACore 3.3.5 326 Honor

Defeat Drek/Van 
WOTLK Classic 161 + 81 per captured tower/bunker Honor - ACore 3.3.5 1085 + 434 per captured tower/bunker Honor

Warsong Gulch
capture flag WOTLK Classic 121 Honor - ACore 3.3.5 285 Honor

Arathi Basin 
 WOTLK Classic 57 Honor per 250 points - ACore 3.3.5 123 Honor per 250 points
 
 Does Blizzards Classic version use before 3.3.5 honor gain values?

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

.

**Comment by Nyeriah** [comment]
Classic wrath can't be used as comparison for a lot of things, this might just be yet another of them. We are not looking forward emulating classic wrath at this time.

**Comment by Sulan2** [comment]
> Classic wrath can't be used as comparison for a lot of things, this might just be yet another of them. We are not looking forward emulating classic wrath at this time.

I was just curious if u thought it might sound like Blizzard fucked up and use values from earlier patches of WOTLK?

**Comment by Kitzunu** [comment]
Wrath Classic is on earlier patches, so yes.

**Comment by Sulan2** [comment]
Thought id just throw in another random question here, do u guys know in ACore what it is that sets baseline for some spells for classes?

For example Auto shot 75 is active on start for hunters.
If u unlearn it and relogg u get it again
if u put it in the talent trees it still active on start
If u remove it from playercreateinfo_action table so its not on a button on creation its still in the spellbook.

Something forces it to always be in the spellbook? DBC or database?

**Comment by Kitzunu** [comment]
DBC

**Comment by Sulan2** [comment]
> DBC

Thanks, got it to work
