### ISSUE TITLE
Adding bots to azerothcore latest build

### ISSUE THREAD

**Issue by PolluxTroy0** [azerothcore/azerothcore-wotlk#1293]
Hi,
I'd like to know if there is a way to add your work (IKE3 playerbot (Lidocian version)) on latest release from azerothcore ? I'd like to play solo on my own server with bots.
Thanks for your time. Regards.

**Comment by FrancescoBorzi** [comment]
Hi, welcome to AzerothCore. Your is more a generic help/information question and not a bug report.
Please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/How-to-ask-for-help

Feel free to join our chat to discuss: https://discordapp.com/channels/217589275766685707/284406375495368704
