### ISSUE TITLE
Feature: Bump VerifiedBuild to work with recent build numbers.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#12959]
### Describe your feature request or suggestion in detail

Currently the VerifiedBuild column's datatype is set to `SMALLINT`. This means that its signed range ends at `32767`. This means that, assuming my understanding of the column is correct, this column isn't compatible with any build version beyond Battle for Azeroth, and that includes the majority of Classic builds.

I suggest modifying this column to be compatible with modern builds.

### Describe a possible solution to your feature or suggestion in detail

I suggest bumping the column datatype to `MEDIUMINT` so that the signed range ends at `8388607` which hopefully shouldn't be a build number we come to anytime soon.

**Comment by yuanf225** [comment]
What do you mean, I can use a non-335 (12340) version of the client for the game?

**Comment by heyitsbench** [comment]
> What do you mean, I can use a non-335 (12340) version of the client for the game?

No. The current use of the VerifiedBuild column (to my knowledge) functions purely as a comment for users/devs, to keep track of the build number a particular entry and its contents were observed on. 

As an example, for the creature_equip_template entry for creature 26081, the VerifiedBuild column has the value 18019. If this value is to be trusted, that means that the creature in question was observed to be carrying the gear as described in the entry on [patch 5.4.7hotfix3](https://wowwiki-archive.fandom.com/wiki/Patch_5.4.7hotfix3). Currently, this column can only store values going up to a certain patch in BfA and Classic Vanilla, but if we wanted to store any values from DF/Wrath Classic and denote them in the VerifiedBuild column, we can't as the datatype doesn't support it.
