### ISSUE TITLE
[server]World crashes when a hunter cast readiness in raid

### ISSUE THREAD

**Issue by fullofstarschen** [azerothcore/azerothcore-wotlk#12971]
### Current Behaviour

World crashes when a hunter cast readiness in raid.

### Expected Blizzlike Behaviour

none.

### Steps to reproduce the problem

none.

### AC rev. hash/commit
c172ac6e8721

[c172ac6e8721_worldserver.exe_[5-9_7-7-15].txt](https://github.com/azerothcore/azerothcore-wotlk/files/9485696/c172ac6e8721_worldserver.exe_.5-9_7-7-15.txt)

### Operating system

win10x64

### Custom changes or Modules

mod-anticheat
mod-eluna

**Comment by ZhengPeiRu21** [comment]
Would you please test if the linked PR is resolve this issue?
