### ISSUE TITLE
Redundant Gathering Nodes

### ISSUE THREAD

**Issue by DavuKnight** [azerothcore/azerothcore-wotlk#12970]
### Current Behaviour

The information about the Gathering Nodes has come from a number of locations over time and has many data issues. One of those issues is redundant nodes. 2 or more nodes of the same type within a small distance of each other.

### Expected Blizzlike Behaviour

Nodes seldom ever show up close enough together to both be harvested without moving.

### Steps to reproduce the problem

Its RNG so its hard to spot. 2 nodes geographically close have to both spawn.

### Extra Notes

This is a data issue no so much an in game issue. 

### AC rev. hash/commit

AzerothCore rev. a347e3fca86f+ 2022-09-01 16:03:48 -0400 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1q  5 Jul 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.74.0
Using MySQL version: 80030
Using CMake version: 3.24.1
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../../../data/maps. Total size: 291014951 bytes
vmaps directory located in ../../../data/vmaps. Total size: 658130721 bytes
mmaps directory located in ../../../data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod_Kafta

### Operating system

Windows 10

**Comment by DavuKnight** [comment]
Current Approach to fix this is sql that remove the nodes that are redundant.  Created an issue report to track any concerns as we progress with the fix.

**Comment by DavuKnight** [comment]
set @distance = 6;
 CREATE TEMPORARY TABLE IF NOT EXISTS _listOfOriginalNodes AS Select min(nguid) from
(
select oguid,nguid,sqrt(((o.position_x-n.position_x)*(o.position_x-n.position_x))+((o.position_y-n.position_y)*(o.position_y-n.position_y))+((o.position_z-n.position_z)*(o.position_z-n.position_z))) as distance 
from
(SELECT guid as oguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) o
join
(SELECT guid as nguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) n
on
o.entry = n.entry
) d
where 
distance < @distance
group by oguid
having count(*)>1;
CREATE TEMPORARY TABLE IF NOT EXISTS _listOfNodesThatAreRedundent AS 
Select distinct nguid from
(
select oguid,nguid,sqrt(((o.position_x-n.position_x)*(o.position_x-n.position_x))+((o.position_y-n.position_y)*(o.position_y-n.position_y))+((o.position_z-n.position_z)*(o.position_z-n.position_z))) as distance 
from
(SELECT guid as oguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) o
join
(SELECT guid as nguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) n
on
o.entry = n.entry
and
oguid != nguid

) d
where 
distance < @distance
and
nguid Not in (Select * from _listOfOriginalNodes);

Delete acore_world.gameobject from acore_world.gameobject join _listOfNodesThatAreRedundent on nguid = guid;

**Comment by acidmanifesto** [comment]
>

Back ticks helps alot so we dont end up with missing characters, or end up with unintended bold and italizations.
```
set @distance = 6;
CREATE TEMPORARY TABLE IF NOT EXISTS _listOfOriginalNodes AS Select min(nguid) from
(
select oguid,nguid,sqrt(((o.position_x-n.position_x)(o.position_x-n.position_x))+((o.position_y-n.position_y)(o.position_y-n.position_y))+((o.position_z-n.position_z)(o.position_z-n.position_z))) as distance
from
(SELECT guid as oguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) o
join
(SELECT guid as nguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) n
on
o.entry = n.entry
) d
where
distance < @distance
group by oguid
having count()>1;
CREATE TEMPORARY TABLE IF NOT EXISTS _listOfNodesThatAreRedundent AS
Select distinct nguid from
(
select oguid,nguid,sqrt(((o.position_x-n.position_x)(o.position_x-n.position_x))+((o.position_y-n.position_y)(o.position_y-n.position_y))+((o.position_z-n.position_z)*(o.position_z-n.position_z))) as distance
from
(SELECT guid as oguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) o
join
(SELECT guid as nguid,entry,position_x,position_y,position_z FROM acore_world.gameobject o join acore_world.gameobject_template t on o.id = t.entry where type=3) n
on
o.entry = n.entry
and
oguid != nguid

) d
where
distance < @distance
and
nguid Not in (Select * from _listOfOriginalNodes);

Delete acore_world.gameobject from acore_world.gameobject join _listOfNodesThatAreRedundent on nguid = guid;
```

**Comment by DavuKnight** [comment]
this at the moment would delete approx. 1100 redundent gameobjects of type=3.

**Comment by DavuKnight** [comment]
So after some discussion we are actually going to proceed under the assumption that any data that puts two nodes of ANY kind withen a 6 foot area is a faulty set of data. However we wont update that data until we have a known good sniff of the data to replace it with since theres no way to know which is the right data and which is sthe bad data. Simply assuming the earliest data is the correct data is a bad assumption.

**Comment by Gultask** [comment]
These nodes should be pooled in the DB. Approaches made by deleting spawns or through core changes might not be blizzlike, as nodes close to each other is something that can happen in retail, although infrequently.

In cases like Hillsbrad, each of those stacked nodes should be pooled with each other, and these pools should be pooled in a larger pool.

Here's a PR, for reference: https://github.com/azerothcore/azerothcore-wotlk/pull/13597

Closing as this is a well-known issue. We just need more time/volunteers to do it in the DB.
