### ISSUE TITLE
NPC server crash 36627/rotface

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#12980]
### Current Behaviour

I've encountered a crash on the server here, namely on Rotface https://www.wowhead.com/wotlk/ru/npc=36627/rotface
we started playing with friends and literally beat him for a couple of minutes as the server crashed.

But unfortunately there is no log file because Reliz was compiled and not the Debug version, Because there is not enough computer power to check for the Debug version, If someone can please see what the problem might be? We were played by 7 people.

### Expected Blizzlike Behaviour

I do not know what to write here, but there should not be a crash on a rotten board

### Steps to reproduce the problem

we started playing with friends and literally beat him for a couple of minutes as the server crashed.

### Extra Notes

no

### AC rev. hash/commit

AC rev. c172ac6e8721+

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-1v1-arena, mod-ah-bot, mod-anticheat, mod-cfbg, mod-custom-login, mod-guildhouse, mod-learn-spells, mod-npc-buffer, mod-npc-enchanter, mod-premium, mod-transmog

**Comment by acidmanifesto** [comment]
Please bud in debug or release wirh debug and peovide the crash logs with revision.

**Comment by MegaserverRU** [comment]
> Please bud in debug or release wirh debug and peovide the crash logs with revision.

I can't provide a crash log with the debug version the system is weak

**Comment by acidmanifesto** [comment]
> > Please bud in debug or release wirh debug and peovide the crash logs with revision.
> 
> I can't provide a crash log with the debug version the system is weak

Without the crash logs or reproduction steps we can not assist in anything reported here as it does not tell us any information.

**Comment by MegaserverRU** [comment]
> > > Please bud in debug or release wirh debug and peovide the crash logs with revision.
> > 
> > 
> > I can't provide a crash log with the debug version the system is weak
> 
> Without the crash logs or reproduction steps we can not assist in anything reported here as it does not tell us any information.

And how do I check for Debug versions if the system is weak(((

**Comment by MegaserverRU** [comment]
If you can't help, then you can close this problem ((((
Because unfortunately I can't provide the log itself with the Debug version, the system starts to be very stupid

**Comment by acidmanifesto** [comment]
> > > > Please bud in debug or release wirh debug and peovide the crash logs with revision.
> > > 
> > > 
> > > I can't provide a crash log with the debug version the system is weak
> > 
> > Without the crash logs or reproduction steps we can not assist in anything reported here as it does not tell us any information.
> 
> And how do I check for Debug versions if the system is weak(((

Build it in debug or release with debug. As for system being weak, i am not entirely sure I understand what you mean.

**Comment by MegaserverRU** [comment]
My computer starts to get very dull in Debug mode and due to the fact that the computer is lagging a lot, I can't check in any way in Debug, I can only play on the release

**Comment by MegaserverRU** [comment]
Crash is due to peta Hunt
Now about tested

**Comment by MegaserverRU** [comment]
Crash is due to peta Hunt
Now about tested
The pet was removed and there was no crash, namely, the server crashes with the pet

![WoWScrnShot_090622_200109](https://user-images.githubusercontent.com/98691968/188696728-e7f41832-218d-4c57-88c9-adb2948beb03.jpg)

**Comment by MegaserverRU** [comment]
It is Hunt's different pets that cause crashes even on the professor

**Comment by MegaserverRU** [comment]
This spec causes Hunt to crash because when he sang on sindragosa in the citadel of the icy crown, the server crashed
![WoWScrnShot_090622_215224](https://user-images.githubusercontent.com/98691968/188718534-e87cb431-7cc6-48c6-946f-5355d036e442.jpg)
 https://www.wowhead.com/wotlk/ru/spell=23989

**Comment by MegaserverRU** [comment]
I managed to make a debug version that's what causes the crash how to fix it?
[Crashes.zip](https://github.com/azerothcore/azerothcore-wotlk/files/9508108/Crashes.zip)

**Comment by ZhengPeiRu21** [comment]
Would you please check if linked PR will now fix this issue?

**Comment by MegaserverRU** [comment]
> Would you please check if linked PR will now fix this issue?

I checked, it works well, it no longer causes the server to stop and does not crash

**Comment by MegaserverRU** [comment]
> Would you please check if linked PR will now fix this issue?

I checked, it works well, it no longer causes the server to stop and does not issue a crash, but after you check on the dummies, a crash appears again

**Comment by ZhengPeiRu21** [comment]
Thank you for testing. I have changed the fix to I think work better. Would you please try it again and now if it works?

**Comment by MegaserverRU** [comment]
> Thank you for testing. I have changed the fix to I think work better. Would you please try it again and now if it works?

I checked happy New year, everything works well in the Citadel of the Ice Crown, I also checked on the mannequins and everything works well there. If I find something, I'll let you know.
