### ISSUE TITLE
Field Marshal is Gone

### ISSUE THREAD

**Issue by Sajgon66** [azerothcore/azerothcore-wotlk#12990]
### Current Behaviour

Field Marshal Snowfall is gone, unless it was done on purpose. I am not sure there is a case for Horde.

### Expected Blizzlike Behaviour

Field Marshal Showfall exists until the end of war effort

### Steps to reproduce the problem

Go to Ironforge military ward and see for it self.

### Extra Notes

https://classic.wowhead.com/npc=15701/field-marshal-snowfall

### AC rev. hash/commit

is that necessary?

### Operating system

Debian 12

**Comment by heyitsbench** [comment]
Is this issue not better suited for https://github.com/chromiecraft/chromiecraft/issues?

And yes, it is necessary.

**Comment by 55Honey** [comment]
This repo only accepts issues for AzerothCore itself. Please follow the advice from heyitsbench.
