### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by BungiSk** [AzerothCore/azerothcore-wotlk#13]
https://github.com/callmephil/SunWellCore/issues/71
https://github.com/callmephil/SunWellCore/issues/69
https://github.com/callmephil/SunWellCore/issues/58
https://github.com/callmephil/SunWellCore/issues/51
big problems
https://github.com/callmephil/SunWellCore/issues/43
https://github.com/callmephil/SunWellCore/issues/60
https://github.com/callmephil/SunWellCore/issues/63
etc...thx for fix.

**Comment by Yehonal** [comment]
Please open an issue for each bug and , if possible, test it with our core before.

Closed.
