### ISSUE TITLE
Quest 14151 has `RequiredSkillPoints` = 450 but max possible skill is 412, quest can't be done.

### ISSUE THREAD

**Issue by zhuay112** [azerothcore/azerothcore-wotlk#13003]
### Current Behaviour

Quest 14151 has `RequiredSkillPoints` = 450 but max possible skill is 412, quest can't be done.
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (425), skipped

### Expected Blizzlike Behaviour

mysql
Quest 14151 has `RequiredSkillPoints` = 450 but max possible skill is 412, quest can't be done.
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (425), skipped

### Steps to reproduce the problem

Quest 14151 has `RequiredSkillPoints` = 450 but max possible skill is 412, quest can't be done.
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (425), skipped

### AC rev. hash/commit

Quest 14151 has `RequiredSkillPoints` = 450 but max possible skill is 412, quest can't be done.
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (420), skipped
Skill condition specifies invalid skill value (425), skipped
Skill condition specifies invalid skill value (425), skipped

### Operating system

windows 10

**Comment by Nyeriah** [comment]
This happens if your server is capped to a specific level

**Comment by zhuay112** [comment]
> This happens if your server is capped to a specific level

I changed the original level 80 to level 60. Is that the reason? 
How to solve it?

**Comment by Nyeriah** [comment]
Yes, that's the reason. Ignore it, it doesn't mean anything
Or you could completely delete the quests from your database, that would also get rid of the errors

**Comment by zhuay112** [comment]
ok, thanks for your answer
