### ISSUE TITLE
Majordomo Executus Broken RP

### ISSUE THREAD

**Issue by ZhengPeiRu21** [azerothcore/azerothcore-wotlk#13019]
### Current Behaviour

After defeat, Majordomo Executus slowly clips through the textures and moves to his position near Ragnaros to summon.

### Expected Blizzlike Behaviour

He should surely not do what he now does. I think he should teleport to the new location instantly.

### Steps to reproduce the problem

1. Defeat Majordomo Executus in MC
2. Talk through all gossip
3. Watch his walk away through the floor

### Extra Notes

Originally reported https://github.com/ZhengPeiRu21/mod-individual-progression/issues/20.
I was able to reproduce on a clean build of AC master.

### AC rev. hash/commit

AzerothCore rev. d40e3340fb83 2022-09-08

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
He shouldn’t have the gossip flag until he teleports. Maybe a regression from the gossip flag check PR

**Comment by Nyeriah** [comment]
He shouldn’t have the gossip flag until he teleports. Maybe a regression from the gossip flag check PR

**Comment by Gultask** [comment]
Probably fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/13128
