### ISSUE TITLE
[Instance] ShadowLabyrinth Mind Control targeting issues

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#13024]
### Current Behaviour

The two players affected by the spell will not attack each other
https://www.wowhead.com/wotlk/spell=33676/incite-chaos

### Expected Blizzlike Behaviour

Controlled players attack each other

### Steps to reproduce the problem

1.two player
2.modify hp
3.go cr 66937
4.wait

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e5efa47f7fc6640e1d03fcd4f261400e99221728

### Operating system

Windows 10 x64

**Comment by Gultask** [comment]
Seems like an issue with Mind Control in general to me. In AQ and ZG MC'ed palyers will attack critters and can sometimes attack other MC'd players as well.
