### ISSUE TITLE
[AQ40] Battleguard Sartura - Sundering Cleave

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13047]
### Current Behaviour

Spams Sundering Cleave while whirlwinding.

### Expected Blizzlike Behaviour

Sundering Cleave should not be linked to Whirlwind (26083)
Queues Sundering Cleave every 2.4-3s outside of whirlwind phase.
A failed cast results in an immediate retry.

### Source

Retail

### Steps to reproduce the problem

`.go c id 15516`
see how often Sundering Cleave is queued

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3dde9d904c0d9a25e60d28a90f946579f2b8be33

### Operating system

Windows 10

**Comment by Gultask** [comment]
Wait I might've got something wrong here.

**Comment by UltraNix** [comment]
https://legacy-wow.com/aq40-boss-guide-battleguard-sartura/#sundering-cleave
