### ISSUE TITLE
After update 1ddd884d6a69b2fde6647c6af24cee987dba9510  Some spells are no spell bonus effect

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#13056]
### Current Behaviour

Such as warlock's spell 17962 has no bonus effect.

### Expected Blizzlike Behaviour

these will have bonus effect.

### Steps to reproduce the problem

just cast the spell with equip and test again without equip

### AC rev. hash/commit

AzerothCore rev. 25f88caa428d+ 2022-09-18 22:09:47 -0300 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100515
Using CMake version: 3.18.4
Compiled on: Linux 5.15.35-3-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 54345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2320900760 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

debian 11 x64

### Custom changes or Modules

- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-server-auto-shutdown
- mod-transmog

**Comment by kissingers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/1ddd884d6a69b2fde6647c6af24cee987dba9510

**Comment by ZhengPeiRu21** [comment]
I will investigate.

**Comment by heyitsbench** [comment]
I can test on WotLK Classic, just have to know how, as `just cast the spell with equip and test again without equip` isn't quite descriptive enough.

**Comment by heyitsbench** [comment]
Equipping and unequipping all of the gear given as a PTR 70 template makes no difference on the spell damage or any effects, if that's all that needs to be tested.

**Comment by kissingers** [comment]
Yes I lookup in spell_bonus before version, there is also no spell 17962. but before this version, this spell is Warlock's main one cycle spell, at any 3.13 and 3.35 it have  bonus effect.

**Comment by ZhengPeiRu21** [comment]
Bench's test seems to speak that this spell should not have influence from spell bonus. If it had it before, that was a bug. The official server does not have this influence by spell bonus. Sorry if I am not understand you correctly!

**Comment by acidmanifesto** [comment]
https://www.wowhead.com/wotlk/spell=17962/conflagrate
Has a buff for fire damage ever 2 seconds. I do not have any record and can not find any record of any spell bonus from that spell that is given.

**Comment by kissingers** [comment]
According to the normal understanding, even if the spell does not has the spell bonus, but according to the skill description, after cast 17962 devour the current sacrifice, should be calculated by 60% of the current sacrifice damage, that is, indirectly has the spell bonus of the sacrifice, and should not be calculated by the base damage of the sacrifice.

**Comment by ZhengPeiRu21** [comment]
We maybe will need more Warlock playing expert to share if they are also experiencing this trouble. This spell does have custom scripting but it seems to be properly passing all effect indexes for bonus calculation. It was also not changed in the linked PR so I would be surprising if this PR is influence it. WoWhead comment do seem to be talking about spell damage bonus, but DBC files do not include it. It is possible that the server-side custom scripting needs to be improve to fix this and add custom add the spell damage bonus, but this would not have been changed by the PR and would have always been this issue.

**Comment by heyitsbench** [comment]
And if need be, **detailed** testing steps for Wrath Classic would be appreciated to check blizzlike behavior.

**Comment by kissingers** [comment]
Also 31801 have very low bonus bug, with the description, it should 5 times, totle 97,  but real test only 3*5=15
![image](https://user-images.githubusercontent.com/33601959/191067173-a1b25e02-977e-426b-92d3-1aed3f739216.png)
 it can Stacked 5 times, every one time only 14, 14*5=70 ,   but with description, it should  97*5/5=97
![image](https://user-images.githubusercontent.com/33601959/191067813-46d68a37-ca0b-4cca-a0e3-cdd165de5cb9.png)

**Comment by ZhengPeiRu21** [comment]
Spell 31801 adds aura 31803 which has the correct DBC coefficient of 0.013. This is match the description of the ability and the value that was in the spell_dbc table before the update. Do you have a screenshot of the damage is different with the older version? It should be the same. If it is different than before the PR, that could be a bug.

**Comment by andrevarella** [comment]
> Spell 31801 adds aura 31803 which has the correct DBC coefficient of 0.013. This is match the description of the ability and the value that was in the spell_dbc table before the update. Do you have a screenshot of the damage is different with the older version? It should be the same. If it is different than before the PR, that could be a bug.

i have a database with the values of spell_bonus_data before the pr to delete them, and spell 31803 looks like this
![image](https://user-images.githubusercontent.com/102264970/191082767-55fc8f7f-48c5-4ce7-b232-3cdcea2a156e.png)

**Comment by ZhengPeiRu21** [comment]
> > Spell 31801 adds aura 31803 which has the correct DBC coefficient of 0.013. This is match the description of the ability and the value that was in the spell_dbc table before the update. Do you have a screenshot of the damage is different with the older version? It should be the same. If it is different than before the PR, that could be a bug.
> 
> i have a database with the values of spell_bonus_data before the pr to delete them, and spell 31803 looks like this ![image](https://user-images.githubusercontent.com/102264970/191082767-55fc8f7f-48c5-4ce7-b232-3cdcea2a156e.png)

The ap_dot_bonus does not appear in the DBC. Do we know where this data is source? If with the ap_dot_bonus is give the correct damage, we may need to restore the spell_bonus override for any spells that have this bonus, but I am curious of if that is really the proper way to handle spells with AP Bonus.

**Comment by Ovahlord** [comment]
Stop hacking shit and fix it properly. This spell needs to be triggered via spellscript and its basepoints must be overriden by using the Dot's aura amount and multiplying it against its max ticks.

**Comment by ZhengPeiRu21** [comment]
> Stop hacking shit and fix it properly

I think this is also our same goal. Haha. There is currently some handling for this script here:
https://github.com/azerothcore/azerothcore-wotlk/blob/972bcc31132147614f0c5a35aa55770bc217236e/src/server/game/Spells/SpellEffects.cpp#L392

Would you suggest to remove this and add a SpellScript to spell_warlock.cpp? I am thinking that is maybe a cleaner implementation.

I am curious of your opinion of the ap_dot_bonus of spell 31803. I am not sure where that value is come from and feel there should be a correct "not hacking" way to fix it. Do you know where this value is come from? Do you have a suggested implementation?

**Comment by kissingers** [comment]
![image](https://user-images.githubusercontent.com/33601959/191799389-5fefe004-d770-4d81-a3b8-2a48ea803f0c.png)
In addition, the knight's devotion skills, 27173, panel damage 8 seconds caused 1492 damage, the actual test only 824 damage, the higher AP the actual damage ratio the lower. Overall, the knight's several sustained spell damage skills are much lower, and the previous than the overall damage less than 2/3 of the original, currently reduced to the lowest end of the DPS, and it used to be more balanced.

**Comment by ZhengPeiRu21** [comment]
As Ovahlord pointed out, the old solution was an incorrect hack, though it did provide more correct damage values. I think we should continue to try and implement proper fixes for fully correct behavior, which will mean we will need new handling for many of these spell.

For a temporary fix until this is complete, adding back all of the SQL data to the spell_bonus table should restore old behavior, as that will override the DBC values now being read.

**Comment by kissingers** [comment]
According to the current of bonus effect, defensive talent of the knight can't tank the group of monsters, because he will always be OT.

**Comment by kissingers** [comment]
> As Ovahlord pointed out, the old solution was an incorrect hack, though it did provide more correct damage values. I think we should continue to try and implement proper fixes for fully correct behavior, which will mean we will need new handling for many of these spell.
> 
> For a temporary fix until this is complete, adding back all of the SQL data to the spell_bonus table should restore old behavior, as that will override the DBC values now being read.

Ok I try add SQL data before to temporary fix it, thanks!
