### ISSUE TITLE
[Docker] Error docker-compose up

### ISSUE THREAD

**Issue by Nephelion** [azerothcore/azerothcore-wotlk#1305]
[Docker] Error docker-compose up

##### SMALL DESCRIPTION:
When use command [docker-compose up] After compile with docker Errored

##### EXTRA NOTES:
Error

> Step 8/11 : RUN chmod 755 azerothcore/apps/db_assembler/db_assembler.sh;     /az erothcore/apps/db_assembler/db_assembler.sh 1                                     ---> Running in c5f85b2f1147                                                    ': No such file or directory                                                     Service 'ac-database' failed to build: The command '/bin/sh -c chmod 755 azeroth core/apps/db_assembler/db_assembler.sh;     /azerothcore/apps/db_assembler/db_as sembler.sh 1' returned a non-zero code: 127

--

===
I test more changes from commit https://github.com/azerothcore/azerothcore-wotlk/commit/76772e434d5d01f996adb03b44698fc352e0fd7c#diff-58b62ab6edcc2363b1add8382ec5163d - roll back and more test .but dont work

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/b578bce1d1b7de2254ec2aacb19bed40a0732997

##### OPERATING SYSTEM:
windows 10 Enterprise

##### MODULES:
nothing - clean

##### OTHER CUSTOMIZATIONS:
nothing

**Comment by FrancescoBorzi** [comment]
@nephelion are you running it from the root **azerothcore-wotlk** directory?

**Comment by Nephelion** [comment]
@FrancescoBorzi 
NOPE
D:\test\source\

**Comment by FrancescoBorzi** [comment]
As the guide says, you have to run all commands from the same directory where the azerothcore sources are.

**Comment by Nephelion** [comment]
@FrancescoBorzi sry thats wrong on my translate your text
yes I'm run from root


PC@DESKTOP-CH9JBUO MINGW64 /d/test/source (master)                    
$ docker-compose up



but source is not my root drive

**Comment by FrancescoBorzi** [comment]
can you try the following?

- `docker-compose down`
- `docker system prune -a` WARNING: this will clean ALL your docker images and containers on your system
- try to install again

if it give again error, can you please post the full log ?

**Comment by FrancescoBorzi** [comment]
@Nephelion can you try this branch? https://github.com/azerothcore/azerothcore-wotlk/pull/1308

**Comment by FrancescoBorzi** [comment]
`git pull`
`git checkout fix-windows-docker`
`docker-compose down`
`docker-compose up`

**Comment by Nephelion** [comment]
i tested more change .but not work
i tested your branch + / before azerothcore
i test
RUN chmod 755 /azerothcore/apps/db_assembler/db_assembler.sh   [with and without /]
RUN /azerothcore/apps/db_assembler/db_assembler.sh 1
and tested before this commit https://github.com/azerothcore/azerothcore-wotlk/commit/76772e434d5d01f996adb03b44698fc352e0fd7c#diff-58b62ab6edcc2363b1add8382ec5163d

**Comment by FrancescoBorzi** [comment]
@Nephelion can you post the full error of when you tried that branch ?

**Comment by Nephelion** [comment]
@FrancescoBorzi  like first error

http://pasted.co/387415b2

**Comment by FrancescoBorzi** [comment]
Ok @Nephelion I made some changes and tested on macOS, for me it works.

I don't have Windows at the moment, but the setup I've tried macOS is similar to Windows because both of them use Docker Desktop.

Can you update your sources to latest master and try again?

**Comment by FrancescoBorzi** [comment]
that warning is not an issue, don't worry I got it too

**Comment by Nephelion** [comment]
@FrancescoBorzi  complete build and compile with error for new branch update https://github.com/azerothcore/azerothcore-wotlk/pull/1308

full log without build log 
http://pasted.co/1ccdf586

how revert pull and update master ? for new test

**Comment by Nephelion** [comment]
@FrancescoBorzi  last commit https://github.com/azerothcore/azerothcore-wotlk/commit/62b05683f5271121599480b7e38751737bfad8cf compile complete but  Error docker-compose up


error
http://pasted.co/4d377553

**Comment by Nephelion** [comment]
i searched and read more 10 guide about error 127 i  think need some update or install something 
i searching again

**Comment by FrancescoBorzi** [comment]
@Nephelion good! feel free to reach us on [Discord](https://discordapp.com/channels/217589275766685707/284406375495368704)

**Comment by FrancescoBorzi** [comment]
@Nephelion can you provide the versions of your `docker`,  `docker-compose` and Docker Desktop?

Those are mine:

![image](https://user-images.githubusercontent.com/75517/51353413-e0d2fa00-1ab0-11e9-914a-77085d3c42b2.png)

![image](https://user-images.githubusercontent.com/75517/51353428-eaf4f880-1ab0-11e9-8c9d-882a71dd9430.png)

**Comment by Nephelion** [comment]
C:\WINDOWS\system32>docker --version
Docker version 18.09.1, build 4c52b90

C:\WINDOWS\system32>docker-compose --version
docker-compose version 1.23.2, build 1110ad01

**Comment by Nephelion** [comment]
try copy db_assembler.sh
COPY db_assembler.sh /azerothcore/apps/db_assembler/db_assembler.sh
then run it
RUN ./db_assembler.sh 1
but

Step 8/13 : COPY db_assembler.sh /azerothcore/apps/db_assembler/db_assembler.sh  Service 'ac-database' failed to build: COPY failed: stat /var/lib/docker/tmp/doc ker-builder715175190/db_assembler.sh: no such file or directory


and found something for runing .sh files
RUN sh ./azerothcore/bin/acore-db-asm 1
but

Step 9/12 : RUN sh ./azerothcore/bin/acore-db-asm 1                               ---> Running in a00da849c23a                                                    : not foundre/bin/acore-db-asm: line 2:                                          ./azerothcore/bin/acore-db-asm: line 3: syntax error: bad substitution           : not foundre/bin/acore-db-asm: line 4:                                          ': No such file or directoryembler.she: line 5: can't open '/                    Service 'ac-database' failed to build: The command '/bin/sh -c sh ./azerothcore/ bin/acore-db-asm 1' returned a non-zero code: 2

and something found about 
[#!/bin/sh at the beggining of the shell script.]

maybe help 
please share a discord

**Comment by FrancescoBorzi** [comment]
@Nephelion so we have the exact same versions

https://discordapp.com/channels/217589275766685707/284406375495368704

let's discuss it tomorrow or this weekend

**Comment by FrancescoBorzi** [comment]
@Nephelion have you tried to "Switch

https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

**Comment by Nephelion** [comment]
no i dont switch linux
but i delet docker and use old install steps [Traditional setup]

**Comment by FrancescoBorzi** [comment]
@Nephelion I meant the Docker Desktop settings... I didn't mean changing your operating system..

**Comment by mhhussain** [comment]
I’m on a fresh install in win-10 64 bit.

**Comment by FrancescoBorzi** [comment]
@Nephelion @mhhussain the issue with Docker on Windows has been fixed. Thank you very much for reporting this issue.

In your case, you need to clean up your environment and restart the install procedure again.

- Delete the `azerothcore-wotlk` sources directory
- Stop all docker containers `docker-compose down`
- Delete all docker images on your system & reset docker `docker system prune -a`

Then start again following the [Docker setup instructions](https://github.com/azerothcore/azerothcore-wotlk/wiki/Install-with-Docker).

![AzerothCore on Windows 10 with Docker](https://user-images.githubusercontent.com/75517/51561998-966ec600-1e80-11e9-939e-d522c71de459.png)
