### ISSUE TITLE
Sons of Hodir questline

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#1306]
##### EXPECTED BLIZZLIKE BEHAVIOUR:

the quest item: Slag Covered Metal (id:41556)
should be dropped normally like any other quest item,
from the mob: Stormforged Iron Giant (id: 29375)
1- but Not Drop!
2- important-> when you get quest complete and go to anvil to give that anvil not give another quest , this mean quest line is bug !

##### STEPS TO REPRODUCE THE PROBLEM:

1. add item 41556 and get quest
2. complete quest and get to anvil
3. when you delivery quest to anvil anvil don't give another quest !

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/6ef7c403139cde2cd2f97cb3b93d75e543bb017c

##### OPERATING SYSTEM:

7 64 bit

##### MODULES:

duelreset

**Comment by Viste** [comment]
cant confrim

**Comment by Franklampardst** [comment]
> cant confrim

you can test it and give screen shot?!

**Comment by poszer** [comment]
As i know, you must have this quest [Mending Fences](https://www.wowhead.com/quest=12915/mending-fences) in order for this item to drop.
![slagcoveredmetal](https://user-images.githubusercontent.com/41213210/51325997-7731fc00-1a6e-11e9-8ebf-e4dc49d2ee6c.png)

Also, read [This - Reputation](https://www.wowhead.com/faction=1119/the-sons-of-hodir)
