### ISSUE TITLE
Feature Suggestion : Smart Script convert entryorguid to entry, guid

### ISSUE THREAD

**Issue by malcrom** [azerothcore/azerothcore-wotlk#13063]
### Describe your feature request or suggestion in detail

Currently NPCs can load smart scripts by entry or by -guid which is not ideal. There is no way to know if a guid has it's own SAI without a long search through the table and you have to rewrite the combat AI every time you do some thing different.

I'm suggesting two separate fields if guid is zero all guids will load script, if guid has value only spawn with same value will load it.

I already have this system working, Pictures below. I may explain this better later but atm I am tired.

### Additional context

![smartscriptssql](https://user-images.githubusercontent.com/709267/191137863-c045afcc-5b18-44c7-a2cd-e379fc19397c.png)
![skelly2](https://user-images.githubusercontent.com/709267/191137866-ef1dd1d1-a750-48ca-8683-f9783a445138.png)
![skelly1](https://user-images.githubusercontent.com/709267/191137876-293f2930-e3f8-4b5c-b11c-e3478a47b938.png)

**Comment by Nyeriah** [comment]
@malcrom i don’t understand. What is the issue?
