### ISSUE TITLE
dungeons ahn kahel the old kingdom boss herald volazj

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13068]
### Current Behaviour

problem for spell Insanity Boss Herald Volazj dungeons Ahn Kahel The Old Kingdom its not working

### Expected Blizzlike Behaviour

Drive all players in the room to Insanity. During this time, players are phased and can't attack the Herald, but will be forced to fight 4 Twisted Visages. Used at 66% and 33% of Volazj's health left

### Source

https://www.wowhead.com/npc=29311/herald-volazj#abilities-normal-5-player

### Steps to reproduce the problem

Start the boss and wait for the insanity spell to start
You will find that the insanity spell does not work well

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5f839a4be933f944c0df46c233066e37966c263

### Operating system

windows 10

**Comment by avarishd** [comment]
#7796
