### ISSUE TITLE
halls of stone dungeons Bran Bronzebeard disappears after the start of the final boss

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13079]
### Current Behaviour

Problem for dungeons Halls of Stone last boss Sjonnir The Ironshaper
The main problem is the bronze beard He disappears after the boss starts
He must be alive until the last moment when the boss is killed to finish the quest

### Expected Blizzlike Behaviour

Bronzebeard must survive until the last moment when the boss is killed to complete the quest
https://www.youtube.com/watch?v=YR3ieuowaYQ
time started 20:22 finished 24:29
### Source

https://www.wowhead.com/wotlk/npc=27978/sjonnir-the-ironshaper
https://www.wowhead.com/wotlk/achievement=2154/brann-spankin-new

### Steps to reproduce the problem

Just start the boss, then you will notice that after starting the last boss Bran Bronzebeard will disappear!

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5f839a4be933f944c0df46c233066e37966c263

### Operating system

windows 10

**Comment by Gultask** [comment]
Hey, again like in your other bug report, could you update the title so that it's clearer what it's about? :)

It makes it easier to developers and other contributors such as testers.
