### ISSUE TITLE
[Brewfest] Race for tokens daily not working

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13077]
original report https://github.com/chromiecraft/chromiecraft/issues/4102. confirmed on ptr
### Current Behaviour

Clicking "i want to race for tokens" does not start the "there and back again!" daily quest for tokens

### Expected Blizzlike Behaviour

completion of "there and back again!" quest from the npc Neill Ramstein (https://wowgaming.altervista.org/aowow/?npc=23558) and Ram Master Ray (https://wowgaming.altervista.org/aowow/?npc=24497) should unlock a repeatable daily for extra tokens

### Source

https://www.wowhead.com/wotlk/guides/brewfest-event-achievements#repeatable-quests

### Steps to reproduce the problem

.go creature 88857
.quest add 11122
.quest complete 11122
click dialogue "I Want to race for token"

### Extra Notes

https://www.wowhead.com/wotlk/quest=11122/there-and-back-again
![image](https://user-images.githubusercontent.com/11332559/191530079-99c78e0f-71fd-41a9-8c59-92610d0d303c.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Windows 11

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Tereneckla** [comment]
This is not quite right. It is not a repeatable quest
Selecting "Do you still need help shipping..." and then "I'm ready for work for you today..." should give you a ram for 4 minutes and each turn of delivering a keg gives you 2 tokens and adds 30 minutes to the timer
This is doable again after 18 hours

https://wowpedia.fandom.com/wiki/Neill_Ramstein
https://www.wowhead.com/wotlk/npc=23558/neill-ramstein#comments

**Comment by heyitsbench** [comment]
Yes, this `I want to race for tokens!` I believe should only show up to the player after a certain amount of time after completing the quest the first time. Until then, only the steps Tereneckla mentioned are available.

**Comment by BeefSteaker** [comment]
interesting. horde dont seem to have a similar option 
![image](https://user-images.githubusercontent.com/11332559/191539969-9dfba20b-1627-40e2-949e-0ae58440955c.png)

**Comment by Tereneckla** [comment]
Judging by the comments he should have.
Initiated with "Do you still need some help moving kegs from the crash site... ?"

https://www.wowhead.com/wotlk/npc=24497/ram-master-ray#comments

**Comment by BeefSteaker** [comment]
[this report](https://github.com/chromiecraft/chromiecraft/issues/4107) could be related? Seems like there are multiple issues with those npc's dialogue options

**Comment by heyitsbench** [comment]
[Still uploading, but this was recorded from the Wrath Classic PTR on a fresh character.](https://www.youtube.com/watch?v=8bwrwnmPTPg)
