### ISSUE TITLE
[AQ40] Battleguard Sartura - Boss and adds should reset aggro while Whirlwind aura is up.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13072]
### Current Behaviour

Aggro reset happens on a timer separate from Whirlwind.

### Expected Blizzlike Behaviour

The boss should:

- Reset aggro at the same time when Whirlwind (26083) is cast.
- Reset aggro every 1.2-7.5s while whirlwinding (7.5 taken from mangos. Exact max timer is unknown to me)
- Reset aggro after Whirlwind fades.

Adds follow the same behaviour with their own Whirlwind (26038)

### Source

Retail and https://youtu.be/JHOGWVd7OjQ

### Steps to reproduce the problem

1. `.go c id 15516`
2. engage the boss and monitor aggro changes

### Extra Notes

In retail, the boss also adds 100000 threat to a random player whenever she resets aggro, but that behaviour is not seen in WotLK videos.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5f839a4be933f944c0df46c233066e37966c263

### Operating system

Windows 10

**Comment by UltraNix** [comment]
`
Reset aggro at the same time when Whirlwind (26083) is cast.
Reset aggro every 1.2-7.5s while whirlwinding (7.5 taken from mangos. Exact max timer is unknown to me)
Reset aggro after Whirlwind fades.
`
What is the purpose of resetting agro during whirlwind when boss do not attack and only casting aoe whirlwind? Very odd.

**Comment by UltraNix** [comment]
Honestly, I don't understand the mechanic at all.
The boss should reset aggro for everyone, or only for one random player (which would be weird)?
Or maybe boss should just fixate on one target?

**Comment by UltraNix** [comment]
@Gultask You need to explain to me the whole mechanic because I don;t understand this. Is it reset threat or fixating random players? Boss should reset all threat on whirlwind cast? Then every 7 sec change target or maybe again reset threat? And this mechanic works only during whirlwind?

**Comment by Gultask** [comment]
I'm not sure why this mechanic exists or how *exactly* it works. But I did notice it in several videos and in my own experiences.
I believe it's to keep the boss and adds constantly moving around to deal as much damage as possible.
I've also noted a source that claims that the adds "have no aggro table" but I believe that's hyperbole since they're almost always Whirlwinding and thus dropping aggro.

**Comment by Gultask** [comment]
What I've seen is that it drops aggro when the aura is first cast. But then it can or cannot drop aggro again while the aura is up. the 2s-7s timer is from another emu.
