### ISSUE TITLE
[Brewfest] Neill Ramstein & Ram Master Ray gossip options

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13082]
original report https://github.com/chromiecraft/chromiecraft/issues/4107 . confirmed on ptr
### Current Behaviour

The 3 may I have another racing ram gossip options are visible without conditions and do nothing.
![image](https://user-images.githubusercontent.com/11332559/191574129-260fe77e-ca45-49b8-b5dd-c8fb67b8f9a3.png)
![image](https://user-images.githubusercontent.com/11332559/191574146-6b694676-d3fa-43c2-80f2-8cc37a83188d.png)

### Expected Blizzlike Behaviour

gossip options should not be duplicated and should remount to ram

### Steps to reproduce the problem

.go c 88857
talk to him
select gossip options

### Extra Notes

Quests:
https://wowgaming.altervista.org/aowow/?quest=11318
https://wowgaming.altervista.org/aowow/?quest=11122
https://wowgaming.altervista.org/aowow/?quest=11293
https://wowgaming.altervista.org/aowow/?quest=11294
Neil:
https://wowgaming.altervista.org/aowow/?npc=23558

possibly related to https://github.com/azerothcore/azerothcore-wotlk/issues/13077

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by heyitsbench** [comment]
Do we have a blizzlike source for when this gossip option should appear?
