### ISSUE TITLE
quest line_life_without_regrets is bugged 

### ISSUE THREAD

**Issue by cnmir2** [azerothcore/azerothcore-wotlk#131]
**Description**:
.quest add 13242 
.quest add 13347
**Current behaviour**: Tell us what happens
the aliance and horde quest bugs 
**Expected behaviour**: Tell us what should happen instead
quest_life_without_regrets is very classic quest maybe hard to fixed !
**Steps to reproduce the problem**:
1. .quest add 13242  .quest add 13347
2. then go on quest 
3. but the sequnce qusest could not finished 

4  .go -8444.8 339.5 121.3 0
 .go 2845.29 6193.2 85.8 571
.go  1912 -4151.7 40.6 1
.go  1336.34 -4374.32 26.19 1
.go  1962.69 235.92 39.77 0

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master
**AC hash/commit**:  
ac
**Operating system**:  
win7
**Modules**:  Are you using modules? if yes, list them
not
**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
not
##

**Comment by Krath** [comment]
Maybe this can help the devs:

https://github.com/TrinityCore/TrinityCore/commit/3002839bfec1c69e00a191d82e569b647cd4fdb8

**Comment by poszer** [comment]
Fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/1479
