### ISSUE TITLE
problem for boss Devourer of Souls dunegons forge of souls

### ISSUE THREAD

**Issue by fantomlancer** [azerothcore/azerothcore-wotlk#13115]
### Current Behaviour

problem and bug in the dungeons the forge of souls boss Devourer of Souls when the boss is tunted and brought to the ladder section, the boss becomes buggy and disappears in an instant and does not cast any spells after appearing

### Expected Blizzlike Behaviour

After the boss reappears, spell and cast again

### Source

https://www.wowhead.com/wotlk/npc=36502/devourer-of-souls

### Steps to reproduce the problem

After the boss reappears, spell and cast again

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d2610941bd54ed5b4e661a4dbcff7583c9d6e44b

### Operating system

windows 10

**Comment by LukasVolgger** [comment]
Hi! You already opened the same issue a week ago here https://github.com/azerothcore/azerothcore-wotlk/issues/13039. Please be patient, not all issues can be fixed immediatly. And please paste your commit hash.  Thanks!
