### ISSUE TITLE
Brewfest Ram should not dismount in the Mystic Ward pool

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13131]
original issue https://github.com/chromiecraft/chromiecraft/issues/4111. confirmed on ptr
### Current Behaviour

Brewfest Ram dismounts in the pool in the Mystic Ward in Ironforge.

### Expected Blizzlike Behaviour

Brewfest Ram should not dismount due to a puddle.

### Source

https://www.youtube.com/watch?v=Owl8IS1CSqw&t=60s  (player in distance)

### Steps to reproduce the problem

    .tele ironforge
    .aura 43883
    Go to the Mystic Ward.
    Observe the issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/04db1914d839060501eacaa13b6fd1e5d274677c

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by heyitsbench** [comment]
That's not a good source. The ram only dismounts in the water of the pool, that video doesn't show that.

**Comment by BeefSteaker** [comment]
> That's not a good source. The ram only dismounts in the water of the pool, that video doesn't show that.

Ah ok. Do you have anything from the wrath classic PTR? I don't have access myself

**Comment by heyitsbench** [comment]
As denoted in the original report, the issue didn't happen on the Wrath PTR in my testing, but I'll get a video for good measure.

**Comment by heyitsbench** [comment]
It's not the PTR (since I can't get in :P) but it's live. [Here you go.](https://www.youtube.com/watch?v=PIJ7R0U10-A)
