### ISSUE TITLE
[Terokkar Forest] Quests 10929, 10930, worms disappear in a second

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#13144]
### Current Behaviour

For these two quests, mobs simply disappear without having time to appear literally in a second, you can't even take a target
https://www.wowhead.com/quest=10929/fumping
https://www.wowhead.com/quest=10930/the-big-bone-worm

### Expected Blizzlike Behaviour

Worms should appear and attack you so that they can be killed, but they disappear.

### Source

no

### Steps to reproduce the problem

After using the reels, the Worms should appear and attack you so that they can be killed, but they disappear.

### Extra Notes

no

### AC rev. hash/commit

fd08f6150f0b+

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-1v1-arena. mod-ah-bot. mod-anticheat. mod-cfbg. mod-congrats-on-level. mod-custom-login. mod-guildhouse. mod-instance-reset. mod-learn-spells. mod-npc-buffer. mod-npc-enchanter. mod-premium. mod-transmog

**Comment by ishidinho** [comment]
Can confirm. They evade and immediately despawn.
![image](https://user-images.githubusercontent.com/62797536/207854554-8d55c99b-a2df-4e98-8b29-18e1e4ee15d4.png)
