### ISSUE TITLE
Feature: openssl 3

### ISSUE THREAD

**Issue by MellianStudios** [azerothcore/azerothcore-wotlk#13159]
### Describe your feature request or suggestion in detail

Please somebody finally change openssl to be version 3. Version 3 is out for over a year it is somewhat common issue among people installing AC especially on ubuntu 22.04.

There was this attempt https://github.com/azerothcore/azerothcore-wotlk/pull/11600 but it has been closed months ago for some reason. There is also reference to other repo seems to me like it is pretty much done it just needs to be modified for AC.

This should also include PR to be made to wiki changing openssl references to reflect that now AC is on v3

**Comment by heyitsbench** [comment]
[Open bounty.](https://app.bountysource.com/issues/111732756-feature-openssl-3) ($50 as of this comment.)

**Comment by MellianStudios** [comment]
compiled and logged in successfully on ubuntu 22.04
![image](https://user-images.githubusercontent.com/10326275/194774727-9a4585eb-ac65-4cf3-b8db-1c72cdf02a8c.png)

**Comment by Winfidonarleyan** [comment]
> compiled and logged in successfully on ubuntu 22.04 ![image](https://user-images.githubusercontent.com/10326275/194774727-9a4585eb-ac65-4cf3-b8db-1c72cdf02a8c.png)

thanks for test

**Comment by MellianStudios** [comment]
im not sure if its related but during compilation there are warnings from openssl 3 about deprecation of MD5

**Comment by Kitzunu** [comment]
> im not sure if its related but during compilation there are warnings from openssl 3 about deprecation of MD5

@Winfidonarleyan yes this is related.

**Comment by Winfidonarleyan** [comment]
> im not sure if its related but during compilation there are warnings from openssl 3 about deprecation of MD5

can provide build log?

**Comment by Kitzunu** [comment]
https://www.openssl.org/docs/man3.0/man3/MD5_Init.html I remember seeing this when I tried to support openssl 3.0

**Comment by MellianStudios** [comment]
`[ 45%] Building CXX object src/server/game/CMakeFiles/game.dir/Warden/WardenMac.cpp.o
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenMac.cpp:86:5: warning: 'MD5_Init' is deprecated [-Wdeprecated-declarations]
    MD5_Init(&ctx);
    ^
/usr/include/openssl/md5.h:49:1: note: 'MD5_Init' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenMac.cpp:87:5: warning: 'MD5_Update' is deprecated [-Wdeprecated-declarations]
    MD5_Update(&ctx, mod->CompressedData, len);
    ^
/usr/include/openssl/md5.h:50:1: note: 'MD5_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenMac.cpp:88:5: warning: 'MD5_Final' is deprecated [-Wdeprecated-declarations]
    MD5_Final((uint8*)&mod->Id, &ctx);
    ^
/usr/include/openssl/md5.h:51:1: note: 'MD5_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenMac.cpp:255:5: warning: 'MD5_Init' is deprecated [-Wdeprecated-declarations]
    MD5_Init(&ctx);
    ^
/usr/include/openssl/md5.h:49:1: note: 'MD5_Init' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenMac.cpp:256:5: warning: 'MD5_Update' is deprecated [-Wdeprecated-declarations]
    MD5_Update(&ctx, str.c_str(), str.size());
    ^
/usr/include/openssl/md5.h:50:1: note: 'MD5_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenMac.cpp:258:5: warning: 'MD5_Final' is deprecated [-Wdeprecated-declarations]
    MD5_Final(ourMD5Hash, &ctx);
    ^
/usr/include/openssl/md5.h:51:1: note: 'MD5_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
6 warnings generated.
[ 45%] Building CXX object src/server/game/CMakeFiles/game.dir/Warden/WardenWin.cpp.o
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenWin.cpp:143:5: warning: 'MD5_Init' is deprecated [-Wdeprecated-declarations]
    MD5_Init(&ctx);
    ^
/usr/include/openssl/md5.h:49:1: note: 'MD5_Init' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenWin.cpp:144:5: warning: 'MD5_Update' is deprecated [-Wdeprecated-declarations]
    MD5_Update(&ctx, mod->CompressedData, length);
    ^
/usr/include/openssl/md5.h:50:1: note: 'MD5_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
/home/rymercyble/wow/azerothcore/src/server/game/Warden/WardenWin.cpp:145:5: warning: 'MD5_Final' is deprecated [-Wdeprecated-declarations]
    MD5_Final((uint8*)&mod->Id, &ctx);
    ^
/usr/include/openssl/md5.h:51:1: note: 'MD5_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
3 warnings generated.
`

**Comment by heyitsbench** [comment]
> [Wall of text]

https://gist.github.com/

**Comment by MellianStudios** [comment]
@heyitsbench 
![image](https://user-images.githubusercontent.com/10326275/194942954-01855bea-3ce1-401a-b98c-bf1f47f4333d.png)

**Comment by Winfidonarleyan** [comment]
I'll fix it tomorrow.

**Comment by MellianStudios** [comment]
@Winfidonarleyan how does it look ? there are still md5 deprecation warning during compilation

**Comment by MellianStudios** [comment]
i confirm its fine and so bounty is fulfilled

**Comment by Winfidonarleyan** [comment]
> i confirm its fine and so bounty is fulfilled 


I won't be able to get the reward anyway.
