### ISSUE TITLE
[Character / Player] - Tavern and Rest Bar

### ISSUE THREAD

**Issue by virgo77** [azerothcore/azerothcore-wotlk#13164]
### Current Behaviour

I think there's a bug with the player rest bar.

Yesterday, I was level 30 and about 40% XP bar (purple. Not blue)
I went to a tavern having a rest for about 24h, and when I returned on my character, the Rest Bar was full. So I got a 200% bonus until level 31.

And for me, it's not as short as this. Logically, it takes about 2 weeks to fill at max this 200% bonus. So, in 24h, we should get only 1 step (notch?) of the XP Bar. Not the entire XP bar!

### Expected Blizzlike Behaviour

-

### Steps to reproduce the problem

just reach level 30 and about 40% of XP
then go in a tavern, and have a rest for about 24h
Et voila: you have a full rest bar and 200% XP bonus ^^

### AC rev. hash/commit

AzerothCore rev. 6c3fc2603b46+ 2022-09-26 09:41:20 -0400 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Debian 11.5 for core // W11 for game client // all are up to date

### Custom changes or Modules

ag-bot
skip dk starter
transmog

**Comment by ZhengPeiRu21** [comment]
I am not able to reproduce this bug. Is your rest rate in your worldserver.conf set to 1? I am knowing of an issue where the end marker for the rested part of the XP bar does not appear on first log in until gaining, but I think this is an original client bug, and is also visual only.

**Comment by virgo77** [comment]
Hi! Thanks for your quick reply Oo
Effectively, I have this in the wordserver.conf file:
Rate.Rest.InGame                 = 1
Rate.Rest.Offline.InTavernOrCity = 1
Rate.Rest.Offline.InWilderness   = 1

Maybe I have some changes to do inside this file?

**Comment by virgo77** [comment]
Hi ZhengPeiRu21, how R U?

So look, in this picture, you can see that:
1. I am level 31
2. I used all the 200% rest bar. You can see my purple XP bar, and the last 14 exp points after killing a mob (chat box)
3. I am actually at Darkshire
4. And I used 3 stacks (on 20) of my XP bar

It is 23h15 in France (11.15 pm, Paris Time) and I quit the game in the Tavern. I will not play until tomorrow as I will not be at home before midnight. So, I will try to connect and check for my XP Bar and the Rest XP Bonus.
Note that I disabled the Graphics Update I usually enable to get the game most beautiful. So I use the genuine MPQ files for this test.

So, goodnight, sleep well and see you later :)

Bye! V.

![WoWScrnShot_092822_231317](https://user-images.githubusercontent.com/23108339/192891686-7f65c038-5d1a-43ea-a911-6bdeadea4bbb.jpg)

**Comment by ZhengPeiRu21** [comment]
> Hi ZhengPeiRu21, how R U?
> 
> So look, in this picture, you can see that:
> 
>     1. I am level 31
> 
>     2. I used all the 200% rest bar. You can see my purple XP bar, and the last 14 exp Rested Bonus points after killing a mob (chat box)
> 
>     3. I am actually at Darkshire
> 
>     4. And I used 3 stacks (on 20) of my XP bar
> 
> 
> It is 23h15 in France (11.15 pm, Paris Time) and I quit the game in the Tavern. I will not play until tomorrow as I will not be at home before midnight. So, I will try to connect and check for my XP Bar and the Rest XP Bonus. Note that I disabled the Graphics Update I usually enable to get the game most beautiful. So I use the genuine MPQ files for this test.
> 
> So, goodnight, sleep well and see you later :)
> 
> Bye! V.
> 
> ![WoWScrnShot_092822_231317](https://user-images.githubusercontent.com/23108339/192891686-7f65c038-5d1a-43ea-a911-6bdeadea4bbb.jpg)

Thank you, this sounds like a good reliable test. Please let us know the result!

**Comment by virgo77** [comment]
Hello!
So. Here is a picture with the Rest XP Bonus. It takes about 6 and a half more, as you can see. I'm not that in 24h the resting bonus should grow so fast. As I remember, it should take about 2 weeks to get a full XP Bonus bar. So, it should be about just 1 or 1 & 1/2 stack in one day. Not 6.

For me, it's a bug. But a "good" one if we want to pex fast :)

Good night

V.

![WoWScrnShot_093022_002713](https://user-images.githubusercontent.com/23108339/193154258-6c53ff49-f92b-42c3-a8d0-8114da71d29e.jpg)

**Comment by virgo77** [comment]
Glad to help :)
++

**Comment by virgo77** [comment]
Erm, sorry to 'spam' but I would like to ask a question please: I don't remember if it was like this when it was WotLK Vanilla but, do you know if the Rest Bar is "static"? I mean, since many years now, in retail, when you are under a full Rest Bar, and you gain XP, the Rest Bar is just going a bit forward (never when finishing quests to the quest giver). So, was it working like this in 2008/2010? Or was the Rest Bar a static one?
If you remember this, just let me know :)
Thanks a lot

**Comment by ZhengPeiRu21** [comment]
The rest bar should not move when gain any XP where the rest bonus is applied (defeating mobs.) In these case, the rest indicator should not move because it decreases by the same amount the bar increases. If gaining other XP such as quest XP, the amount of available rest XP stays the same, so the indicator will move forward by the same amount as non-rest XP gained.

**Comment by virgo77** [comment]
Hi ZhengPeiRu21! Thanks for your reply, you exactly right. I tried less than 1 minute and it's exactly what you said.
So I can say that my memory is not as good as I thought ^^
Thanks again :)
Have a good day
V.
