### ISSUE TITLE
[Shaman] Swing timer reset

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13179]
original report https://github.com/chromiecraft/chromiecraft/issues/4145
### Current Behaviour

Maelstrom weapon is working correctly only at 5 stacks.
While at 4 or lower, casting Lightning bolt resets the swing timer, that shouldn't happen.

### Expected Blizzlike Behaviour

Casting lightning bolt/chain lightning while at 1-4 stacks of Melstrom shouldn't reset swing timer.
People on wrath call it lightning bolt weaving - basically casting lightning bolt before your next melee swing so you don't waste any Maelstrom stacks. - viz. lower

### Source

From Icy-veins: Cast Weaving is using one or more Maelstrom Weapon stacks to cast a spell, typically Lightning Bolt or Chain Lightning, in between swings of your typically slow weapons. While casting, normally, resets your swing timer, this does not happen with Maelstrom Weapon-Hasted casts, allowing you to cast spells with less than 5 stacks as long as you start the cast early enough in your swing timer that it will finish before the swing would happen.

https://youtu.be/GJruGPGVA7c?t=41
https://youtu.be/WUWppQKmLoQ?t=251

### Steps to reproduce the problem

.learn 403
learn talents up to Maelstrom weapon 5/5
get 1-4 stacks
cast lightning bolt

### Extra Notes

Weakaura for swing timer/maelstrom tracking

`!WA:2!nAv3YTTXvyXHnUoyAsLORvQDDIzuN8JJRLTvKDsBg3yczsl6qrkdc9JDCl5cGLeBeiW6flKO0DHtNokZ0R4JaVOxLR4f9bqpbNHtN8a4R7v6jONDbOKSsY0Ed4UN9S753VVdZTzHyRLx8olENc9k4vW7W3DIdXDhpreFLOGiXtYNp)65VZI37vorcpQWm7q(SMbSdoGi8kAhffiz8rYi3DPIywu4f39fI(n60jMkZ5KEpFX(zcgtcD9JeRhXcLoRuUUDzRrP60KDa9ngNUo145YLl)esIe1VbxIVCSXWyAqh9LbdbXvl8(wXsIqA40HfYI9nmXFKgdKcw3UOhD1puKT8VpYJ6K0PJ9(CQy1Y1wVYg1mL4glsIGS0GyoniOQxSXRItCO7sdLnrTz9h3ALsnTB10UKLTzc(4o8aY(uHviPhn2WsRQZQusG0)KRUUGIx1Q56LRvBysyMlyKfSL96s5Z18LjebTyLKGGIB5ZK0Jspnnx9MJe0UyaQCxRUIOe(qsiRhrf03hMTYrusmTPuqd7k9)LW7yggfsN4HHIsJwQatetDJc9IhOuv9oWnn7ryHvGpbVaCt4pa3cwe)DUZlzbMh)Yn3Jf2TOK1JkkkOOlv0jPRzqeXRIJKeGr58w9sWYVHjM7CNh(udl3asCSALzmwqvlg3rG5j0rjss(JtR)vuIuoKtZvSkxUEwDVAiAK8oOp3H11Wk2fns(ryk1sNjInogR8urijyZ0En2iv8XsBogZc7ejstqglLW8gVXUwBTUzZLlTu)cUFYHfhXq1BgLiCPxBg4TmGl(FYbVjyCKl2f7fTxOQU4BQ0QnCP3(dHFZ)uKetRJoB7HQMeDf)Q8zxJqdILIOEf3Is4rHW1HIW7dlaxXaUk87GRbVl8Egyc93cxgMh(9g85uDR7sTt7dwlYJ(9Za)z2X7qP8sQSN0s54(WBdgyFAmrQkKuF4b)P5H3zcMduitvBqO3HxIxqs7lBf7tqVE7mSf)kAH6pPjIwXzlGBo8KZw4dI5ZEMRFky7vPsNcXmlTHDd(L0cryyKkZ6UfZt6Bwc3ECQHy9PEAHF7K0A7ZYCNJ0N)njXswN9bmziWGqjBK(a3Pem5hM5XHs(SveSdk(0eINQBPOT9RfOtF5jAz7HTmBji8bBLTi1G7YIzob02zX4z4B4ZvTE9YwTmByB3ynRQpEv7jNyAf9ZvYIGTFn7Oovtz0yd7AvRx(hM0niAVkc6ltOHU7V(V4olU09sJo1bJvFM(cduBuxEItIugf2a5irUJrkX10a3lR1FAKnuT5eQ38hHnFpEQeFt1H(ARB7ZC3jKghNxFJMAGIEzngkEoTbmt5ED8PSU(YsWDRalPaKWY6V3t)9(6VFeugUWQF5cF93z8WzMbUHIF58Ce3()nRb8qdZdII6Ld(14lyaZzafmG3aNiG8jd7nf0yrc4(K8WNL3ApvNtj4lmeSq18dSHV04LV7nEC)pFNLF538sRtBtGV0yWuCQp85WF8WBpkMte7O7(U8r61P5XTZbxudSNOfAfj1Kc54Z9A7vOqW64tbwNaf0d9sza(xyaEnnO(6JtjeTveIAiEkIFawLA5tc9ARxPMq0gr)MkrWTZiaGQF)mA6NZ04J4)SuTkhIPYZKQpNK5oVKboKSXK5rKl8v(Nn(Fwo4bpbPnGAzChilanJ7yEyT8qJf(aoSUg0dpfSGMGnSX3cBMd2sHuHTHNL6Hph(A(7)JOv4TudfAXfuxMIgop8IRnd)g)C65TpYBYCBj9XPi(yfCF4Va)vWZSooXcApkfwwRCfB(79Z9gP7(P444zlSu65boxbCZbTAF4LYc0W)FduvqODSwTH2JtDknlXpHrdpHynZGEW)aKxxHXU)pcJPrDVsxFmXPMEQ(ULk9OhXNf7xk5POiPEuV1i99H()TFfSc6hL9p)PmSR)JeQPqyPpdGvqJXElJH6oRyMh1s7XPnd2OdNiO8pUQAQzhIl9fRqq64WUMeXl2O6ToD3TAQUaI9w5Z2TU9tx9Jx7U0X6hzvn7XdeY0hBW0)5xk27uUkijNLwK)uaVvScUa7Pa6k8A27X88OHw1lVzzle3d77dxi34ibd)7eAu5OvByv95nQBxQgc5rkf1iXc7(V3()(`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Gultask** [comment]
Confirmed in WotLK Classic PTR.
