### ISSUE TITLE
[Ulduar] Salvaged Siege Engine 

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#1317]
##### SMALL DESCRIPTION:

When a second player gets on, he doesn't occupy the empty space.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When a player is on the vehicle, the second player should automatically move to the free place. However, this does not happen. 

##### CURRENT BEHAVIOUR:

https://www.wowhead.com/npc=33060/salvaged-siege-engine

Currently, if a player climbs when a partner is already there, he gets buggy and the only way to get back to normal is to disconnect. Since he doesn't have the button to get out of the vehicle.

<a href="http://subefotos.com/ver/?8cb967dd9e1b5f970beeb1c6aba72d8ao.jpg" target="_blank"><img src="http://thumbs.subefotos.com/8cb967dd9e1b5f970beeb1c6aba72d8ao.jpg" /></a>

##### STEPS TO REPRODUCE THE PROBLEM:

1. Assemble a raid of at least 2 players.
2. Get in the vehicle and ask a partner to do it.
3. It is important that we are in the part where the vehicle is driven. If we are in the back, the problem does not reproduce.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

62b05683

##### OPERATING SYSTEM:

- Debian 9
- Windows 7

**Comment by pangolp** [comment]
Most players do this:
- You go up first, you go into the shooting zone.
- The second player climbs up and drives the vehicle.

But if you want to climb to the shooting position, directly being a driver, you bugueas. The only way is to disconnect and when you re-enter, you are out of the vehicle, as if you had never climbed.

Apparently there are 3 positions.
- Driver
- Pyrite
- Cannon

**Comment by Franklampardst** [comment]
Confirmed!

**Comment by pangolp** [comment]
It's a problem that the CT still didn't find the return. Apparently it would be a visual problem. But basically what I should do is check if the driver's cabin is occupied and if so, send it to the other free space, but instead, it sends you to a place where you have no control and the only way out is to disconnect and reconnect.

**Comment by Franklampardst** [comment]
@pangolp yea in that place you can take damage and die! must reconnect to fix that issue

**Comment by comix1988** [comment]
tested today and the problem is still present

**Comment by comix1988** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/1778

**Comment by BarbzYHOOL** [comment]
When a player enters the passenger seat (there is only one atm), the pilot can't eject the passenger, seems like a tiny bug.

The empty seat also gives an icon when hovering it, i don't know why.

The seat with the NPC can not be emptied and don't know if the NPC does anything. This may be blizzlike according to a comment on TC.
