### ISSUE TITLE
Server motd not showing

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1318]
##### SMALL DESCRIPTION:

The server motd (welcome message) is not showing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Show the server welcome message.

##### STEPS TO REPRODUCE THE PROBLEM:

Login in game

##### EXTRA NOTES:
The message that should be shown is set in `worldserver.conf`:

`Motd = "Welcome to an AzerothCore server."`

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/ccaa74a9a77b202714b62803fbfeec3b659697c5

##### OPERATING SYSTEM:

Ubuntu 18.04

**Comment by poszer** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/1319
