### ISSUE TITLE
High Admiral "Shelly" Jorrik incorrect respawn timer

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13201]
original issue https://github.com/chromiecraft/chromiecraft/issues/4149
### Current Behaviour

Respawn rate is quick, aproximately 5 mins

### Expected Blizzlike Behaviour

~8-48 hours respawn

### Source

https://www.wowhead.com/wotlk/npc=26081/high-admiral-shelly-jorrik#comments:id=940200:reply=453272
![image](https://user-images.githubusercontent.com/11332559/193431100-47a25c90-6762-4c6b-852a-d035e2b14241.png)
![image](https://user-images.githubusercontent.com/11332559/193431113-b91460b3-4d7b-46a3-b387-2e45107db9eb.png)
![image](https://user-images.githubusercontent.com/11332559/193431121-041bff5c-8165-4dfb-bdba-394597ad80c6.png)

### Steps to reproduce the problem

.go c 1975960
at war with booty bay
/tar high
.damage 4000

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=26081

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by BeefSteaker** [comment]
see also https://github.com/azerothcore/azerothcore-wotlk/issues/13200

**Comment by acidmanifesto** [comment]
Merging PR https://github.com/azerothcore/azerothcore-wotlk/pull/13714 autoclosed this issue. 
Reopening since it was listed as a partial fix and not a full fix in the PR.

**Comment by BeefSteaker** [comment]
Closing as we don't have dynamic spawn times on azerothcore. 
It's as fixed as it can be currently

**Comment by heyitsbench** [comment]
If the issue is not blizzlike or has been fixed, it's fine to close outright. If the issue is being closed due to a dependent higher level issue, try to at least link it to the open issue asking for that feature. In this case, that issue would be https://github.com/azerothcore/azerothcore-wotlk/issues/5751.

**Comment by BeefSteaker** [comment]
Thanks, yes I'll do that in the future.
