### ISSUE TITLE
[Qaston System] Sacred shield kill the player if he takes damage

### ISSUE THREAD

**Issue by Maelthyrr** [azerothcore/azerothcore-wotlk#13217]
### Current Behaviour

When sacred shield is cast on a player, he will die if he takes damages

### Expected Blizzlike Behaviour

The player should not die

### Source

https://www.wowhead.com/wotlk/spell=58597/sacred-shield

### Steps to reproduce the problem

1. Create a paladin
2. Learn sacred shield
3. Cast on myself or another char

### Extra Notes

Confirmed during the test here: https://github.com/azerothcore/azerothcore-wotlk/commit/cbd3fd0967fd94a2a9eb96aaf55ebd69f32aa918

### AC rev. hash/commit

[5fc6807](https://github.com/azerothcore/azerothcore-wotlk/commit/5fc680799ace6a0fc111fc449293a8cf119fe517)

### Operating system

Windows 11

**Comment by adsavulescu** [comment]
same for priest with power word: shield, player instantly dies when attacked with this buff on, maybe its a shield thing?

**Comment by Gultask** [comment]
Can confirm for both spells: `.learn 48066` `.learn 53601`

https://user-images.githubusercontent.com/100873791/193488251-f2a87f71-3e27-4696-b2d3-bf30d05b60fe.mp4


https://user-images.githubusercontent.com/100873791/193488253-363d4949-01cc-43e1-bb02-e76159851b8d.mp4

**Comment by Gultask** [comment]
This seems a bit widespread with Absorb types. Also happens on Guardian Spirit

![image](https://user-images.githubusercontent.com/100873791/193677288-4766909d-195e-4b4a-af62-2da44efa24db.png)
![image](https://user-images.githubusercontent.com/100873791/193677414-67c49a06-7d49-45b6-8aed-d8265a085ffb.png)
