### ISSUE TITLE
[QAston] MoltenCore proc without corruption

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#13218]
### Current Behaviour

The spell MoltenCore proc without corruption

### Expected Blizzlike Behaviour

Should only proc with the spell corruption active

### Source

https://www.wowhead.com/wotlk/spell=47247/molten-core

### Steps to reproduce the problem

1. Create a warlock
2. Get the talent
3. Cast immolate on the target without cast Corruption before

### Extra Notes

Confirmed during the test here: https://github.com/azerothcore/azerothcore-wotlk/commit/cbd3fd0967fd94a2a9eb96aaf55ebd69f32aa918

### AC rev. hash/commit

[5fc6807](https://github.com/azerothcore/azerothcore-wotlk/commit/5fc680799ace6a0fc111fc449293a8cf119fe517)

### Operating system

Windows 11

**Comment by Gultask** [comment]
Molten Core doesn't proc at all.

**Comment by v-mstrs** [comment]
Can't recreate.

**Comment by Gultask** [comment]
> Disclaimer: QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
