### ISSUE TITLE
[QAston] Stormstrike doesn't apply damage bonus from elemental spells

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#13223]
### Current Behaviour

Stormstrike doesn't apply damage bonus from elemental spells 

### Expected Blizzlike Behaviour

Stormstrike should apply damage bonus from elemental spells

### Source

https://www.wowhead.com/wotlk/spell=17364/stormstrike

### Steps to reproduce the problem

1. Create a shaman
2. Get Stormstrike talent
3. Use  stormstrike and then nature spell
4. Look if you get damage bonus

### AC rev. hash/commit

[5fc6807](https://github.com/azerothcore/azerothcore-wotlk/commit/5fc680799ace6a0fc111fc449293a8cf119fe517)

### Operating system

Windows 11

**Comment by Gultask** [comment]
Aura is applied. It's not consumed, however.

![image](https://user-images.githubusercontent.com/100873791/193896753-e183e846-21fb-4886-bf37-e1b65ff60f2f.png)
