### ISSUE TITLE
[QAston] Paladin - Ardent Defender cannot save player from death

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13236]
### Current Behaviour

When character reaches negative health, they die even though they should be healed for 30% of their HP. I believe this is related to QAston problems with absorbs.

https://user-images.githubusercontent.com/100873791/193494960-276b102e-4b5d-4285-a2e6-c2f50b7892fa.mp4

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

Spec into Ardent Defender (Protection tree).
Die due to damage from a creature.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/590525b86ce31ec2e8773bb62c95efc00d24b7c7

### Operating system

Windows 10

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/13271
