### ISSUE TITLE
Table 'acore_world.spell_proc_event' doesn't exist

### ISSUE THREAD

**Issue by williamchai** [azerothcore/azerothcore-wotlk#13231]
### Current Behaviour

Following steps in https://www.azerothcore.org/acore-docker/
After running `docker-compose up` the `acore-docker-ac-worldserver-1` container failed with error:
`ERROR 1146 (42S02) at line 3 in file: '/azerothcore/data/sql/updates/db_world/2022_08_27_08.sql': Table 'acore_world.spell_proc_event' doesn't exist`

### Expected Blizzlike Behaviour

`docker-compose up` should not fail

### Source

Did a `grep spell_proc_event -r updates` and found `updates/db_world/2022_10_02_01.sql` dropped the `spell_proc_event` table during the `ac-db-import` run but later when `ac-worldserver` starts it run all the sql in updates folder again which in `updates/db_world/2022_08_27_08.sql` it reference `spell_proc_event` table and fail.

### Steps to reproduce the problem

1. docker-compose pull
2. docker-compose up ac-db-import
3. docker-compose up

### AC rev. hash/commit

5fc680799ace6a0fc111fc449293a8cf119fe517

### Operating system

MacOS with docker

**Comment by Karmiven** [comment]
had same issue
did git pull for core and for eluna module
now works without this problem

**Comment by UltraNix** [comment]
@Nyeriah Can we close this one?

**Comment by Nyeriah** [comment]
Hm, I don't use docker. So I don't know.

**Comment by UltraNix** [comment]
I belive this problem was connected with Qaston new proc system implementation which is now reverted.

**Comment by williamchai** [comment]
I can verify if it's fixed tomorrow!

**Comment by acidmanifesto** [comment]
I did a fresh rebuild yesterday and updated today and had no issues.

**Comment by williamchai** [comment]
Thanks!
