### ISSUE TITLE
[QAston] Shiv does not apply poisons.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13257]
### Current Behaviour

Shiv spell does not apply poisons from off-hand

### Expected Blizzlike Behaviour

Casting Shiv should apply any poison in the off-hand

### Source

WotLK Classic PTR

### Steps to reproduce the problem

Create a rogue
`.additem 8927 20` `.add 8985 20` `.add 10922 20`
Apply any of these to the off-hand
Cast Shiv, see that none work.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/590525b86ce31ec2e8773bb62c95efc00d24b7c7

### Operating system

Windows 10

**Comment by Tolky** [comment]
It works flawlessly now, should close.

**Comment by Kitzunu** [comment]
No because this issue is not related to the current state of the core, but what comes when the proc system is upgraded
