### ISSUE TITLE
[QAston] Glyph of Backstab doesn't work

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13265]
### Current Behaviour

Casting Backstab on a target while having the glyph does not increase Rupture's timer

### Expected Blizzlike Behaviour

It should do as it says in the tooltip.

https://user-images.githubusercontent.com/100873791/193699998-8c853d73-808d-4aba-90f5-211ef4ea0c4a.mp4

### Steps to reproduce the problem

Use a rogue.
`.add 42956`
Apply glyph, apply Rupture on target.
Cast Backstab, see Rupture timer not changing.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/590525b86ce31ec2e8773bb62c95efc00d24b7c7

### Operating system

Windows 10

**Comment by Tolky** [comment]
Should close, it works now.

**Comment by Kitzunu** [comment]
No because this issue is not related to the current state of the core, but what comes when the proc system is upgraded
