### ISSUE TITLE
[QAston] Talent Master of Subtlety does not work.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13274]
### Current Behaviour

Aura is never applied on stealth

![image](https://user-images.githubusercontent.com/100873791/193701109-2ced044d-4f0f-41c6-9724-7576d62d210a.png)

### Expected Blizzlike Behaviour

Aura is applied on stealth and receives a timer upon leaving stealth.

https://user-images.githubusercontent.com/100873791/193701294-761b8c1d-a40f-424d-a466-d1e8c9c3b9eb.mp4

### Steps to reproduce the problem

Spec into Master of Subtlety (Subtlety tree)
Enter Stealth, see if aura is applied.
Leave Stealth, see if aura receives a timer.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/be423a91b53538c92b28f14759f01c474bb8b277

### Operating system

Windows 10

**Comment by Tolky** [comment]
Works fine now.

**Comment by Kitzunu** [comment]
this issue is not related to the current state of the core, but what comes when the proc system is upgraded

This applies to anything labeled QAston
