### ISSUE TITLE
[QAston] Talent Overkill does not work

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13273]
### Current Behaviour

Overkill aura is never applied on stealth

![image](https://user-images.githubusercontent.com/100873791/193700392-4352b8d7-eae7-4d23-a754-0c9e9527be8f.png)

### Expected Blizzlike Behaviour

Overkill aura should be present

![image](https://user-images.githubusercontent.com/100873791/193700484-e29ac833-42a3-40f6-b9a1-017a73f96cb3.png)

https://user-images.githubusercontent.com/100873791/193700650-87b54e98-6a37-4bdf-86f8-ba9966e244f9.mp4

### Steps to reproduce the problem

Spec into Overkill (Assassination tree)
Enter Stealth, see if aura procs
Leave Stealth, see if aura has a timer now

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/be423a91b53538c92b28f14759f01c474bb8b277

### Operating system

Windows 10

**Comment by Tolky** [comment]
It works, but it also gives you a combo point when you miss.

**Comment by Kitzunu** [comment]
No because this issue is not related to the current state of the core, but what comes when the proc system is upgraded
