### ISSUE TITLE
[QAston] Talent Hot Streak gives worldserver error

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13284]
### Current Behaviour

`AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 44448 proc, because the spell does not have an entry in Spell.dbc.`

~~Haven't found any other errors from this spell. It seems to proc correctly.~~

The proc is not consumed. I don't know how I missed this sorry.

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/be423a91b53538c92b28f14759f01c474bb8b277

### Operating system

Windows 10

**Comment by temperrr** [comment]
removes the error, however, it does not remove the 10 second instant cast of pyroblast buff so you can spam it for 10 seconds.
