### ISSUE TITLE
[QAston] Enduring Winter Replenishment effect has no internal cooldown

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13288]
### Current Behaviour

It has no internal cooldown

### Expected Blizzlike Behaviour

Should only proc every 6s

### Source

Tooltip

### Steps to reproduce the problem

1. Spec into Enduring Winter
2. Spam Frostbolt

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/be423a91b53538c92b28f14759f01c474bb8b277

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
