### ISSUE TITLE
[QAston] Regression of Flurry

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13299]
### Current Behaviour

Attacking with 2 weapons of the same speed consumes two charges of Flurry

### Expected Blizzlike Behaviour

See: https://github.com/azerothcore/azerothcore-wotlk/pull/13002 and linked issues

### Source

^

### Steps to reproduce the problem

1. Equip 2 of the same weapon or with different weapons with the same speed
2. .aura 16280
3. attack a target, see how many charges are consumed

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e05f61d1b3873a217798078169455591422a1766

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
