### ISSUE TITLE
[QAston] Decimation worldserver error

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13309]
### Current Behaviour

`AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 63158 proc, because the spell does not have an entry in Spell.dbc.`

### Expected Blizzlike Behaviour

May need help here as I found no other errors with this talent

### Steps to reproduce the problem

Spec into Decimation (Demonology tree)
Damage a target until it reaches <35% HP
Cast Shadow Bolt/Incinerate/Soul Fire
Cast Soul Fire

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e05f61d1b3873a217798078169455591422a1766

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
