### ISSUE TITLE
[QAston] Worldserver freeze

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13305]
### Current Behaviour

```
#----------------------------------------------------------------------#

>> ASSERTION FAILED

# Location 'I:\azerothcore-wotlk\src\server\game\Spells\Auras\SpellAuras.cpp:518'
# Function 'Aura::_UnapplyForTarget'
# Condition 'auraApp->GetRemoveMode()'

# Debug info: 'Id: 47836 Caster: GUID Full: 0x0000000000000012 Type: Player Low: 18
Owner: MapID: 571 X: 7477.72 Y: -1242.66 Z: 907.835 O: 0.977521
GUID Full: 0xf13000731d001782 Type: Creature Entry: 29469  Low: 6018 Entry 29469
Name: Ice Steppe Rhino
AliveState: true UnitMovementFlags: 134217729 ExtraUnitMovementFlags: 0 Class: 1
AIName: SmartAI ScriptName:  WaypointPath: 0 SpawnId: 98754'

#----------------------------------------------------------------------#
```

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

Cast Seed of Corruption
Pass the damage threshold for it to explode

https://user-images.githubusercontent.com/100873791/193935896-d0392a84-2644-4294-b565-4d2f73ca5673.mp4

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e05f61d1b3873a217798078169455591422a1766

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
