### ISSUE TITLE
[QAston] Demonic Pact has no cooldown and every attack procs it

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13307]
### Current Behaviour

It can proc non-stop without a cooldown
It procs on every attack, regardless if crit or not

### Expected Blizzlike Behaviour

It should have a 20s cooldown
It should only proc on pet critical strikes

### Steps to reproduce the problem

Spec into Demonic Pact (Demonology Tree)
`.add 6265 5`
Summon Felguard
See that every attack procs Demonic Pact

### Extra Notes

Possibly related to https://github.com/azerothcore/azerothcore-wotlk/issues/13247

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e05f61d1b3873a217798078169455591422a1766

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
