### ISSUE TITLE
[QAston] Glyph of Corruption doesn't proc

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13313]
### Current Behaviour

It doesn't proc

### Expected Blizzlike Behaviour

It should behave like the talent Nightfall from the Affliction tree, which I'm pretty sure is working correctly. Having both Nightfall and this Glyph causes the chance to stack

> The effects of this glyph stack with the Affliction talent  [[Nightfall]](https://wowpedia.fandom.com/wiki/Nightfall_(warlock_talent)), effectively boosting your chance to get an instant cast [Shadowbolt](https://wowpedia.fandom.com/wiki/Shadowbolt) by 3.84% due to chance that Nightfall's and Glyph's can proc at same time, giving exactly same buff. However if you don't have  [[Nightfall]](https://wowpedia.fandom.com/wiki/Nightfall_(warlock_talent)), gives a normal effect. ([source](https://wowpedia.fandom.com/wiki/Glyph_of_Corruption))

### Steps to reproduce the problem

1. `.add 42455`
2. Multi-dot Corruption

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/00eea376f193aa425c5d5a6174f51848305f6903

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer: QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
