### ISSUE TITLE
[QAston] Nether Protection doesn't proc

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13311]
### Current Behaviour

Regardless of how many spells you are hit with. Nether Protection never procs.

### Expected Blizzlike Behaviour

There should be a 30% chance, when hit with a spell, to proc Nether Protection

### Steps to reproduce the problem

Use 2 characters
Spec into Nether Protection (Destruction tree)
Cast a spell such as Frostbolt (116) on the warlock repeatedly
See if Nether Protection procs

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e05f61d1b3873a217798078169455591422a1766

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
