### ISSUE TITLE
Worldserver Validating Spell Script Effect Error 

### ISSUE THREAD

**Issue by LannyE** [azerothcore/azerothcore-wotlk#13318]
### Current Behaviour

I just updated my build and I am now getting these errors when I start the world server.
![image](https://user-images.githubusercontent.com/65646022/193974907-95f6b34f-0fb5-4d8b-8e3c-bb78e18b501e.png)

From the Server Log:
Spell `26467` Effect `Index: EFFECT_0 AuraName: 42` of script `spell_item_persistent_shield` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
Spell `49217` Effect `Index: EFFECT_0 Target: 16` of script `spell_dk_wandering_plague` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `49654` Effect `Index: EFFECT_0 Target: 16` of script `spell_dk_wandering_plague` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `49655` Effect `Index: EFFECT_0 Target: 16` of script `spell_dk_wandering_plague` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `54748` Effect `Index: EFFECT_0 AuraName: 42` of script `spell_mage_burning_determination` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed
Spell `61685` Effect `Index: EFFECT_0 AuraName: 4` of script `spell_pet_charge` did not match dbc effect data - handler bound to hook `OnEffectProc` of AuraScript won't be executed

Is this from the QAston update?  Is it just me seeing this?  

### Expected Blizzlike Behaviour

No errors on worldserver startup.

### Steps to reproduce the problem

Updated and compiled server.
Startup Worldserver 

### AC rev. hash/commit

AzerothCore rev. 00eea376f193 2022-10-05 01:42:25 +0200 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

Windows Server

### Custom changes or Modules

mod_ahbot
GainHonorGuard
mod_pvptitles
SoloLfg
Solocraft
transmog

**Comment by FDGHBSGd** [comment]
I have the same problem

**Comment by zylok520** [comment]
I have the same problem

**Comment by zylok520** [comment]
check this 2022_10_02_01.sql

**Comment by pklloveyou** [comment]
Always make bug

**Comment by Gultask** [comment]
Will be fixed in the latest commit. I'd keep the issue open as it's related to QAston, though.

**Comment by Nefertumm** [comment]
Update to latest commit, the error will disappear. I'm closing the issue.
