### ISSUE TITLE
[QAston] Empowered Imp does not proc

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13310]
### Current Behaviour

When an Imp achieves a critical Firebolt, the effect from Empowered Imp does not proc

### Expected Blizzlike Behaviour

Critical strikes from Imp should proc Empowered Imp's effect

### Steps to reproduce the problem

Spec into Empowered Imp (Destruction tree)
`.add 6265 5` `.add 18970`
Summon Imp, let it critically hit
See no proc from Empowered Imp

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e05f61d1b3873a217798078169455591422a1766

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
