### ISSUE TITLE
worldserver close

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#1331]
##### BRANCH(ES): 

master

##### OPERATING SYSTEM:
Debian 8

##### MODULES:
anticheat

**Comment by FrancescoBorzi** [comment]
@Franklampardst thanks for your report, can you investigate the cause of this failure?

**Comment by poszer** [comment]
Maybe anticheat command? @Franklampardst

**Comment by Franklampardst** [comment]
@poszer No bro i told you without any crash log and not crash only closed world server without any problem.

**Comment by Franklampardst** [comment]
@FrancescoBorzi i'm not sure but i think when instances reset time worldserver get closed! but not have any crash or error on server.log

**Comment by poszer** [comment]
We can't help you without any informations ( logs ). You should investigate why your server crashing. Also, you should build your core as RelWithDebInfo ( And include your log ) so we can see what's happening. I'm closing this now, since issue doesn't provide us detailed informations.
