### ISSUE TITLE
[QAston] Regression of Eye of Kilrogg

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13312]
### Current Behaviour

Glyph of Kilrogg does not apply the speed increase correctly, and flight is slower than intended.

### Expected Blizzlike Behaviour

With the glyph, Eye of Kilrogg should move faster on ground than without it, and flight should use the speed bonus from the dbc.

### Steps to reproduce the problem

1. .tele crystalsong (anywhere with flight enabled)
2. .cast 126 (Eye of Kilrogg) - It moves at the correct speed
3. Cancel the channel
4. .addaura 58081 to self
5. Cast it again - It moves slower on ground and can fly at the same speed

### Extra Notes

https://github.com/azerothcore/azerothcore-wotlk/pull/12952

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/00eea376f193aa425c5d5a6174f51848305f6903

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disclaimer 
QAston was reverted. The issues were not closed because we will reimplement it in the future and closing them would be counter productive.

https://github.com/azerothcore/azerothcore-wotlk/commit/ad4ce0895f04e633e259941aee470c138700ee8e
