### ISSUE TITLE
[command] reset talents does not set offline player at_login flag to reset talents

### ISSUE THREAD

**Issue by drozco** [azerothcore/azerothcore-wotlk#13325]
### Current Behaviour

Issuing the command 'reset talents player' at server console for an offline player does not cause their talents to be reset at login.

### Expected Blizzlike Behaviour

Should reset talents for offline player.

### Source

No source, but server feedback when issuing the command suggests it should work.

### Steps to reproduce the problem

1. Execute 'reset talents player' at server console (may also happen with GM ingame command) using offline player.
2. Server response is 'Talents of player will reset at next login.'
3. Observe in character database the field at_login for that player does not change to flag 4 - AT_LOGIN_RESET_TALENTS.  The pet talent reset flag IS set, however (16 - AT_LOGIN_RESET_PET_TALENTS.)  Value will read 16, but should be OR of both flags with a value of 20.
4. Login the player account and observe talents are not reset.

### Extra Notes

This is coded with the same behavior in the latest commit of Trinitycore, so it's probably been this way for a long time.
PR is coming soon, already have a fix.

### AC rev. hash/commit

f386e35d8cf2ccba87d8db106b1702e99fd11fa2

### Operating system

Windows 10

**Comment by acidmanifesto** [comment]
closed via https://github.com/azerothcore/azerothcore-wotlk/pull/13326
