### ISSUE TITLE
Talent Fiery Payback proc has no internal cooldown

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13345]
https://github.com/chromiecraft/chromiecraft/issues/3770

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The spell not have internal CD so it procs lot of times , and procs even like 2-3 times in a row that make every melee disarmed to hit a fire mage. 

### Expected Blizzlike Behaviour

The talent is from Fire tree https://wowgaming.altervista.org/aowow/?spell=64353#teaches-spell has 2 ranks , the first part works perfectly, the second part https://wowgaming.altervista.org/aowow/?spell=64346 ha no ICD (internal cooldown)  that is 1 min with a proc chance of 5% rank 1 and 10 % rank 2 

### Source
https://www.wowhead.com/wotlk/spell=64346/fiery-payback
https://wowgaming.altervista.org/aowow/?spell=64346

### Steps to reproduce the problem

1. `.aura 64349` (Fiery Payback) on target
2. `.mod hp 1000000000` `.damage 800000000` on target
3. `.additem 5551` or any other `.lookup item fast test` on self
4. Attack the target that is below <35% HP
5. See how often Fiery Payback procs. Remember that diminishing effects still apply.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by sassouiabd** [comment]
Hello,
Its seems invalid to me, the talent linked from wowhead is a spell and not a talent : 
(https://www.wowhead.com/wotlk/spell=64346/fiery-payback) (you can see its 1min on use spell)

You can read the comment on wow head about it not having an ICD : 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/51038094/c37e5681-852e-456b-b4ab-3b05bd6575d3)

**Comment by Tereneckla** [comment]
and the ICD has been set to 0 again already
https://github.com/azerothcore/azerothcore-wotlk/pull/15981

**Comment by sassouiabd** [comment]
So this issue is outdate and should be closed
