### ISSUE TITLE
Creatures with empty or NULL `auras` field in their creature_addon entry is overriding creature_template_addon auras.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13351]
### Current Behaviour

```
SELECT DISTINCT `id1` FROM `creature` WHERE `guid` IN (SELECT `guid` FROM `creature_addon` WHERE `guid` IN (SELECT `guid` FROM `creature` WHERE `id1` IN (SELECT `entry` FROM `creature_template_addon` WHERE `auras` NOT IN (''))) AND `auras` IN ('', NULL));
```

(1642, 6511, 10405, 12160, 14880, 15977, 16029, 16341, 16537, 17160, 22394, 23037, 26333, 26426, 26624, 26811, 26812, 27202, 27292, 28402, 28583, 28838, 32180, 32185, 33430, 34134);

For example: creature 1642 (Northshire Guard) has no Detect Stealth auras if they patrol:
![image](https://user-images.githubusercontent.com/100873791/194732809-8661bea8-7364-49ef-9fa2-e914d8217afc.png)

### Expected Blizzlike Behaviour

"creature_template_anything should be the base for all creatures and creature_anything acts as the override."

### Steps to reproduce the problem

Compare the auras in the creature_template_addon table of this creature list with the auras applied on patrolling creatures of the same id.
(1642, 6511, 10405, 12160, 14880, 15977, 16029, 16341, 16537, 17160, 22394, 23037, 26333, 26426, 26624, 26811, 26812, 27202, 27292, 28402, 28583, 28838, 32180, 32185, 33430, 34134);

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/667e584041c79c514591776bd34c5cc6e4d7755d

### Operating system

Windows 10

**Comment by Ovahlord** [comment]
that's intended behavior. Creature addons are suposed to override creature template addons entirely regardless if the auras field is empty or not. There is no such thing such as fallback values in this case and that's by design.

**Comment by Gultask** [comment]
kk. Thanks for clearing that out! I thought it would be the case as well. Already submitted a PR to add the missing auras ^^
