### ISSUE TITLE
[CRASH] Talking to NPCs in azure watch crashes server

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#1336]
##### SMALL DESCRIPTION:
Talking to NPCs in Azurewatch crashes the server

##### EXPECTED BLIZZLIKE BEHAVIOUR:
No crash

##### CURRENT BEHAVIOUR:
The server crashes, the console says that broadcast text 2000005143 is missing. I've tested different classes and levels but sooner or later they all seem to cause the same crash. The crash doesn't seem to be any particular NPC it just crashes after talking to between 1 and 10 NPCs.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make a new Draenei (any class)
2. Teleport to azure watch .tele azurewatch
3. Talk to NPCs

##### EXTRA NOTES:
Below is the server log, crash log is attached.

Crash log:
[unknown_worldserver.exe_[21-1_8-57-19].txt](https://github.com/azerothcore/azerothcore-wotlk/files/2777983/unknown_worldserver.exe_.21-1_8-57-19.txt)

Command: .levelup 19 [Player: Testor (35l) (Account: 12) X: -3961.639893 Y: -13931.200195 Z: 100.614998 Map: 530 (Outland) Area: 3526 (Ammen Vale) Zone: Azuremyst Isle Selected:  (0l)]
Command: .tele azurewatch [Player: Testor (35l) (Account: 12) X: -3961.639893 Y: -13931.200195 Z: 100.614998 Map: 530 (Outland) Area: 3526 (Ammen Vale) Zone: Azuremyst Isle Selected:  (0l)]
MonsterChatBuilder: `broadcast_text` id 2000005143 missing

C:\Emulators\MMOs\World of Warcraft\Backups and other stuff\Compiling Mangos\Git\azerothcore\src\server\game\Grids\Notifiers\GridNotifiersImpl.h:540 in Trinity::LocalizedPacketDo<class Trinity::MonsterChatBuilder>::operator () ASSERTION FAILED:
  data->GetOpcode() != MSG_NULL_ACTION
[0x94a92]
[0x82d24]
[0x82c4a]
[0x8f8c0]
[0x46a16f]
[0x46c442]
[0x43e0ef]
[0x3c78a2]
[0xf7265]
[0x31a11d]
[0x37a85a]
[0x2fd9d2]
[0x2fccb6]
[0x34d71d]
[0x4ccf09]
ACE_Task_Base::svc_run()+0x41 [0x95441]
ACE_Thread_Adapter::invoke_i()+0x69 [0x959c9]
ACE_Thread_Adapter::invoke()+0x71 [0x95941]
o_ceil()+0x4e [0x1c4ce]
BaseThreadInitThunk()+0x14 [0x13034]
RtlUserThreadStart()+0x21 [0x73691]

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
 a8621e4

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
VAS Autobalance, Individual XP

##### OTHER CUSTOMIZATIONS:
None

**Comment by Franklampardst** [comment]
Cant confirm :+1:

**Comment by poszer** [comment]
Please, write the name of that NPC

**Comment by Trystanosaurus** [comment]
It's different each time. When it first happened it was talking to Tuluun the shaman trainer, the most recent time it's happened it was Dulvi the mining trainer. It's heppened with others too.

It seems like you just have to run around opening as many gossip windows as possible and it'll happen sooner or later.

The error message however is always the same, I've not been able to find who's trying to use broadcast_text 2000005143 in the database or scripts though:
MonsterChatBuilder: `broadcast_text` id 2000005143 missing

\server\game\Grids\Notifiers\GridNotifiersImpl.h:540 in Trinity::LocalizedPacketDo<class Trinity::MonsterChatBuilder>::operator () ASSERTION FAILED:
  data->GetOpcode() != MSG_NULL_ACTION

**Comment by poszer** [comment]
Confirmed, there is issue in that zone. I didn't speak with any creatures, just moving around and crash appear
![screenshot_8](https://user-images.githubusercontent.com/41213210/51505639-09782e00-1de8-11e9-855f-8f7078ad7f00.jpg)

**Comment by Winfidonarleyan** [comment]
Try apply sql in `world` DB
```sql
UPDATE `waypoint_scripts` SET `dataint` = 13572 WHERE `guid` = 346;
```
And test again

**Comment by Trystanosaurus** [comment]
That SQL fix has worked for me so far, at least it's been in game for half an hour without any crash, and it usually had happened within minutes.

**Comment by poszer** [comment]
Ok i have tested with this sql fix, looks okay. Server is up some hours, and server didn't crashed. Thanks @Winfidonarleyan

**Comment by FrancescoBorzi** [comment]
Good job @Winfidonarleyan 

We should also make the core robust enough to avoid crashes because of DB values

**Comment by poszer** [comment]
> Good, i will create PR.

Nice, create it  and merge since we already tested it

**Comment by BarbzYHOOL** [comment]
> We should also make the core robust enough to avoid crashes because of DB values

what do you mean? a general conditional check to avoid stupid crashes like that ?
