### ISSUE TITLE
The quest "Holiness and filth" for obtaining the legendary weapon Dark Sorrow does not work

### ISSUE THREAD

**Issue by xBarselonx** [azerothcore/azerothcore-wotlk#13360]
### Current Behaviour

This quest (https://ru.wowhead.com/quest=24545/%D1%81%D0%B2%D1%8F%D1%82%D0%BE%D1%81%D1%82%D1%8C-%D0%B8-%D1%81%D0%BA%D0%B2%D0%B5%D1%80%D0%BD%D0%B0#comments) gives [Highlord Darion Mograine](https://ru.wowhead.com/npc=37120) in [Icecrown Citadel](https://ru.wowhead.com/quests/raids/icecrown-citadel) after gaining the appropriate alignment with [Ashen Pact] https://ru.wowhead.com/faction=1156/%D0%BF%D0%B5%D0%BF%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D1%81%D0%BE%D1%8E%D0%B7). To start the quest, you need to find [Light's Vengeance](https://ru.wowhead.com/item=49869) in an abandoned cave, but after killing mobs and one elite mob, the item is used but does not drop into the bag

### Expected Blizzlike Behaviour

Come into the cave, you will take away the hanging hammer, coming closer, the Lich King will take you into chains and start summoning a lot of mobs, they have few lives, but there are a lot of them =) to take the hammer, I did the following: quickly run up in the hammer and start killing mobs, like only the distance between you and the nearest mobs will be fast enough to use the hammer. The hammer goes up and starts killing the little ones - the first stage is passed.
We drink if there is little hp, we approach the hammer and use it, an elite mob of which appears and we kill it, we take the hammer.
The cave is located in the dragon's graveyard. There is also a change of vases present, so that the current one who has this quest can see what is happening there.

### Steps to reproduce the problem

1. Reputation with the Ashen Alliance until friendly
2. Accept the quest https://ru.wowhead.com/quest=24545/%D1%81%D0%B2%D1%8F%D1%82%D0%BE%D1%81%D1%82%D1%8C -%D0%B8-%D1%81%D0%BA%D0%B2%D0%B5%D1%80%D0%BD%D0%B0#comments
3. Start his task

### Extra Notes

-

### AC rev. hash/commit

[00:55:07] Using SSL version: OpenSSL 1.1.1n 15 Mar 2022 (library: OpenSSL 1.1.1n 15 Mar 2022)
[00:55:07] Using Boost version: 1.79.0
[00:55:07] Using MySQL version: 80011
[00:55:07] Using CMake version: 3.24.2
[00:55:07] Compiled on: Windows 10.0.19044
[00:55:07] Worldserver listening connections on port 8085
[00:55:07] Realmlist (Realm Id: 1) configured in port 8085
[00:55:07] VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
[00:55:07] MMAPs status: Enabled

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
Add hash/commit
