### ISSUE TITLE
The Rogue's blade dances with ridiculously high damage

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#13368]
### Current Behaviour

after update to commits on Oct 9, 2022  092710ff191d428e8fb1c4eccf0730eca7f37cca  
The Rogue's blade dances with ridiculously high damage, the direct attack is normal, but the nearby another attack very high.

https://user-images.githubusercontent.com/33601959/194840382-20e02af9-9d85-4914-af5e-3eccf1f34325.mp4

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

Rogue cast blade dances spell 13877 in a group creature, the direct object is normal, but other will die for each attack.

### AC rev. hash/commit

AzerothCore rev. 8a334e821099 2022-10-10 02:46:48 +0700 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100515
Using CMake version: 3.18.4
Compiled on: Linux 5.15.60-1-pve
Worldserver listening connections on port 54346
Realmlist (Realm Id: 2) configured in port 54346
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2320900760 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

debian 11 x64

### Custom changes or Modules

> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-server-auto-shutdown

**Comment by Gultask** [comment]
Confirmed. See https://github.com/azerothcore/azerothcore-wotlk/commit/e390087efd6b04a3583012df03781e57fef8a128
