### ISSUE TITLE
Horde Warsong Gulch gates dont despawn

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13375]
original issue https://github.com/chromiecraft/chromiecraft/issues/3721
### Current Behaviour

The gates that fall down when a battle starts on the horde side never despawn

https://user-images.githubusercontent.com/11332559/194896032-1f13e6cd-9b56-4f97-ae0f-22f6003a5963.mp4

### Expected Blizzlike Behaviour

They should despawn a few seconds after the battle starts

### Source

https://youtu.be/BPRXfYA5AqI?t=11

bit sped up, but they run through the gate and he looks back shortly afterwards. It already despawned at that time

### Steps to reproduce the problem

.debug bg
queue WSG

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by drozco** [comment]
Don't know if this helps to identify the gate or not, but it's called Doodad_RazorfenDoor01 and 02 on the other side of the room.

**Comment by drozco** [comment]
OK I can do a PR that will fix this, but someone needs to confirm the actual despawn time.  I tested it with 10 seconds after the doors open.  Seems to look OK.
Video: https://youtu.be/7Mb2HUzojP4

**Comment by heyitsbench** [comment]
Looks like in [this video](https://www.youtube.com/watch?v=GjjhNIMYd5Y) the gate despawns fast enough where it's gone before the rogue makes it to the floor change in the middle of the room. I'd estimate five seconds between when the gate starts its fall animation and its fadeout.

**Comment by drozco** [comment]
Yeah I can see it better in that video.  I'll set 5 sec and see if that works OK.
