### ISSUE TITLE
[RDF] Can't Vote to Kick an Offline Player if They Had a Pending Loot Roll

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13378]
origina lissue https://github.com/chromiecraft/chromiecraft/issues/3723
### Current Behaviour

It's not possible to vote to kick an offline player if they had a pending loot roll. The system will always report with the "cannot vote to kick during loot rolls" error, even after the loot rolls have completed.

This is a problem because that player can never be removed and forces the group to continue on without being able to queue for a replacement.

NOTE: this has happened to me a couple times. Once during the UBRS rend event (player went offline) and the other I can't remember where. Possibly this is specific to the UBRS rend event? Not sure.

### Expected Blizzlike Behaviour

allow vote-to-kick after loot rolls have completed, even for offline players.

### Source

https://wowpedia.fandom.com/wiki/Vote_Kick?oldid=3128790

mentions offline players can be kicked
![image](https://user-images.githubusercontent.com/11332559/194929715-514a863e-61e9-4ebb-8ed7-7ec5166f9655.png)

### Steps to reproduce the problem

    Start an RDF group.
    Have an item drop from a mob that requires rolls.
    Have a player go dc/go offline (alt-F4 or click X on client window). Don't logout or exit game as that will force the player to leave the group.
    Once said player is showing as offline, wait for loot rolls to be completed. Try to vote for a kick. An error message should be shown preventing the vote, even though loot rolls are actually completed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by drozco** [comment]
Does it matter if the player clicked a roll before they DC?
Do the loot rolls time-out 60 sec or does it award the loot as soon as everyone (still online) rolls?

**Comment by BeefSteaker** [comment]
When I tested it, I didn't roll on it no

**Comment by UltraNix** [comment]
@BeefSteaker Just tested and see no problems with kicking offline player when loot roll is over.

**Comment by BeefSteaker** [comment]
hmm, yeah i dont seem to be able to replicate it any more
