### ISSUE TITLE
Thaurissan Firewalker dont melee when interrupted

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13370]
original report https://github.com/chromiecraft/chromiecraft/issues/4166
### Current Behaviour

Interupting Thaurissan Firewalker's flame buffet causes them move bit forward then stops at around 15-20yards from his target.

mob then stands still until silence expires

https://user-images.githubusercontent.com/11332559/194881027-2aa18a30-b747-4e41-b1fc-30da14bcd53f.mp4

### Expected Blizzlike Behaviour

Mob should melee the player until silence expires

### Source

https://youtu.be/48OJk0RUNiE?t=180

### Steps to reproduce the problem

.learn 2139
.go c 4609
find Thaurissan Firewalker
/cast counterspell

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=7037

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by avarishd** [comment]
fixed by the sai cast flag64 pr
