### ISSUE TITLE
Perception human racial is too stronk

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#13377]
### Current Behaviour

![image](https://user-images.githubusercontent.com/20357406/194918750-fe07a0cc-4cb7-4aed-b627-627abdb3ac9b.png)
Human racial on rogue (no talents for stealth on druid) 25 yards range
Extra detection talent on rogue 

### Expected Blizzlike Behaviour

Same setup on retail ptr
![image](https://user-images.githubusercontent.com/20357406/194918841-674684dd-65da-4419-95e1-c018881dede3.png)
the talent should cause 1 more step backwards in extra visibility

### Source

Retail PTR

### Steps to reproduce the problem

Human rogue
take 
![image](https://user-images.githubusercontent.com/20357406/194918916-b55fc148-d2b1-423a-82e3-b778e4dc26f2.png)
see insane distance detection on use with the racial.

### AC rev. hash/commit

667e584041c7

### Operating system

Windows x11

**Comment by heyitsbench** [comment]
💪
