### ISSUE TITLE
[Quest] At The Enemy's Gates

### ISSUE THREAD

**Issue by Revan2107** [azerothcore/azerothcore-wotlk#13380]
### Current Behaviour

WowHead: https://www.wowhead.com/quest=13855/at-the-enemys-gates

Boneguard Scout and Boneguard Lieutenant aren't counts as slain when you are killing them on tournament mount.

Video of the bug: https://youtu.be/eOLxnxRpfIU

### Expected Blizzlike Behaviour

Boneguard Scout and Boneguard Lieutenant should be counted in quest as slain if you are killing them on Silver Tournament mount

### Steps to reproduce the problem

1. Talk to Airae Starseeker and get At The Enemy's Gates quest.
2. Mount the Toutnament Horse near Ice Crown Citadel enter.
3. Try to kill Boneguard Scout and Boneguard Lieutenant using horse's skills.

### Extra Notes

Works OK if kill them manually

Logs in worldserver console:
![image](https://user-images.githubusercontent.com/53276857/194940087-13871d7f-98cd-42aa-8528-2c0d89917f2f.png)

### AC rev. hash/commit

AzerothCore rev. 667e584041c7+ 2022-10-09 00:54:17 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.67.0
Using MySQL version: 80030
Using CMake version: 3.24.1
Compiled on: Linux 4.19.0-22-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azeroth-server/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod_world_chat

### Operating system

Debian 10

**Comment by heyitsbench** [comment]
Known issue: #12849.
