### ISSUE TITLE
[Minor] Un'goro's Crystal Pylons' dialogue

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13387]
original issue https://github.com/chromiecraft/chromiecraft/issues/4045
### Current Behaviour

Clicking on the bubble in any of the three pylons in the following quest after [Crystals of Power](https://wowgaming.altervista.org/aowow/?quest=4284) gives only a quest credit, but does not open the follow up dialogue

https://www.youtube.com/watch?v=lK5gk5hgaZ8

### Expected Blizzlike Behaviour

Clicking examine should advance to the next section of text

### Source

wrath classic 

https://user-images.githubusercontent.com/11332559/195127906-407135f4-47e9-4874-89a0-5270724889c0.mp4

### Steps to reproduce the problem

.quest add 4285
.quest add 4287
.quest add 4288

.tele ungoro

.go xyz -7200 -2327 -226
.go xyz -6280 -1558 -231
.go xyz -7426 -355 -232

### Extra Notes

Pylons:
North: 17598 (Entry: 164955)
West: 17599 (Entry: 164956)
East: 17600 (Entry: 164957)

Northern pylon dialogue
![image](https://user-images.githubusercontent.com/11332559/195128128-973a56e6-4ab9-4e78-b8e0-d776d3c81b15.png)

Eastern pylon dialogue
![image](https://user-images.githubusercontent.com/11332559/195128775-ac0d77fa-6b27-43be-a814-bf9822e8c2cd.png)

Western pylon dialogue
![image](https://user-images.githubusercontent.com/11332559/195129696-1aa9f3f5-a66f-4fb9-bbe3-8aa3f642281a.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by The-GhostRider** [comment]
- Video Test: [[Fix-Report] - Un'goro's Crystal Pylons](https://youtu.be/OULpkAXSs1Q)

<img src="https://github.com/chromiecraft/chromiecraft/assets/1884642/ec362c64-7d6c-4139-9c81-34d5903cad10" width="300">
