### ISSUE TITLE
Dun Morogh wrong graveyard

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13391]
original issue https://github.com/chromiecraft/chromiecraft/issues/4041
### Current Behaviour

Dying at (24,53) and all that cave takes you to Kharanos Spirit Healer (48,55)

https://user-images.githubusercontent.com/11332559/195177646-ba3e1beb-f00e-44d6-ba4e-113067395082.mp4

### Expected Blizzlike Behaviour

Ressurecting at Iceflow Lake SH (36,46)

### Source

https://user-images.githubusercontent.com/11332559/195177685-e28f1c2d-a6f8-45ea-a96c-fe087460cdd1.mp4

### Steps to reproduce the problem

.tele ironforge
.go xyz -5578 632 398
die

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win 10 x64

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by heyitsbench** [comment]
Possible regression? https://github.com/azerothcore/azerothcore-wotlk/issues/5199

**Comment by acidmanifesto** [comment]
What faction goes where?

**Comment by acidmanifesto** [comment]
also does this effect just alliance or both alliance and horde?

**Comment by BeefSteaker** [comment]
horde go to the correct graveyard, its just alliance

.tele ironforge
.go xyz -5578 632 398
gets you there

this is the full xyz i get
![image](https://user-images.githubusercontent.com/11332559/196258826-e0a98a87-d20f-405f-b204-dba424020664.png)

**Comment by acidmanifesto** [comment]
> 

thank you. working on this now
