### ISSUE TITLE
basic .Vip Commands (In Lua) Azerothcore Elunalua

### ISSUE THREAD

**Issue by QcSynzOfficial** [azerothcore/azerothcore-wotlk#13396]
### Describe your feature request or suggestion in detail

I want to make it like u need to activate your Vip account by doing
".vip activate" but you need the item in your inventory to do it. And it need to put in the Auth database Vip to 1

.Vip                               "To see all Vip Commands"
.vip activate                  "Need item to activate it and put 1 in the database in Vip"
.vip buffs                       "Give options to add how much buff you want to it"
.vip respawn                  "Respawn Creatures"
.vip island                      "Teleport to Vip Island (Unique Coords)"
.vip changerace             "Character change race"
.vip changefaction         "Character change faction"
.vip customize                "Character customisation"
.vip morph                      "Morph command"
.vip key                            "Give you the key to the vip instance"
.vip maxskills                   "Maxskills"

### Describe a possible solution to your feature or suggestion in detail

![Screenshot_4](https://user-images.githubusercontent.com/11411617/195393117-21bcea9e-3f6e-446c-a588-9818ab14a975.png)

### Additional context
Need to work on my Azerothcore Revision :)

_No response_

**Comment by IntelligentQuantum** [comment]
@55Honey  God of Lua

**Comment by 55Honey** [comment]
It's doable but my plate is full currently. I might be able to look into it, just not soon.

**Comment by QcSynzOfficial** [comment]
:) Thx guys

**Comment by 55Honey** [comment]
https://github.com/55Honey/Acore_Vip
It is not finished and untested. Feel free to provide feedback. I'll look further into it when I can.

**Comment by QcSynzOfficial** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/11411617/195952291-16072949-7d21-49e0-8b42-6655cb6252d1.png)
When doing 
.vip activate (With the item in my bag)

**Comment by 55Honey** [comment]
Please update to the latest mod-eluna when you can. chatHandler was added a while back and provides a lot of new options.

**Comment by 55Honey** [comment]
https://github.com/55Honey/Acore_Vip/pull/1
This is supposed to close the issue. Feel free to test it. I'll look further into it asap.

**Comment by 55Honey** [comment]
There has never been a bounty placed on this issue according to https://app.bountysource.com/issues/112469535-bounty-bounty-50-basic-vip-commands-in-lua-azerothcore-elunalua
@QcSynzOfficial  you will need to uphold your request.
