### ISSUE TITLE
[BWL] Death Talon Wrymguards respawn regression

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13394]
original report https://github.com/chromiecraft/chromiecraft/issues/4172
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Death Talon Wrymguards in BWL have a custom / far from blizzlike respawn behavior.
If they reset with less than 2 alive, the remaining one will respawn.
This allows for the group of 3 mobs to be split into a pull of one followed by a pull of the remaining two with usage of feign death.

### Expected Blizzlike Behaviour

The 3 guards shouldnt be separatable / splitable.
And if they not all 3 are killed, the full pack should respawn.

### Source

https://github.com/chromiecraft/chromiecraft/issues/3321
regression of https://github.com/azerothcore/azerothcore-wotlk/pull/11512

### Steps to reproduce the problem

2 chars required.
pull one with hunter, attack one with 2nd char, FD with hunter. only one mob stays infight due to inproper linking.

### Extra Notes

so far these mobs have not being fixed fully. Luckily, the Anubisath Sentinals at the entrance of AQ40 have the correct behavior regarding: getting in combat, staying linked, respawning on reset.
Please, use the Anubisath Sentinals as a template for the behavior of the Wrymguards to fix them.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Not quite. The respawn is correct. The problem seems to be that they do not enter combat with the whole raid group when pulled, which makes the FD pulls possible.

They respawn whenever one evades, but since 2/3 aren't in combat, they can't evade.

**Comment by balleny** [comment]
Issues persists, not fixed - please reopen

**Comment by heyitsbench** [comment]
> Issue persists, not fixed - please reopen

[That's because it was reverted](https://github.com/azerothcore/azerothcore-wotlk/pull/14494). See #14537.
