### ISSUE TITLE
[MSVC][std:c++latest] Azerothcore-wotlk failed to build with msvc due to error C2280 on Windows 

### ISSUE THREAD

**Issue by shizhuoer** [azerothcore/azerothcore-wotlk#13409]
### Current Behaviour

Hi all,
Azerothcore-wotlk failed to build with msvc due to error C2280 on Windows. Could you please help look at this issue?

**Error info:**
 F:\gitP\azerothcore\azerothcore-wotlk\src\server\game\Instances\InstanceScript.cpp(344,1): error C2280: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string(std::nullptr_t)': attempting to reference a deleted function [F:\gitP\azerothcore\azerothcore-wotlk\build_amd64\src\ser
       ver\game\game.vcxproj]

**log**
[build.log](https://github.com/azerothcore/azerothcore-wotlk/files/9782948/build.log)

**VS version: VS2022**

### Expected Blizzlike Behaviour

For Azerothcore_wotlk should be run pass on the windows.

### Source

No response

### Steps to reproduce the problem

1.git clone https://github.com/azerothcore/azerothcore-wotlk F:\gitP\azerothcore\azerothcore-wotlk
2.cd F:\gitP\azerothcore\azerothcore-wotlk
3 mkdir build_amd64 & cd build_amd64
4.set BOOST_ROOT=F:\tools\boost_1_77_0\x64
5.set MYSQL_ROOT=F:\tools\mysql_5_7_35\mysql-5.7.35-winx64
6.set OPENSSL_ROOT=F:\tools\OpenSSL\64
7.cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DTOOLS=ON -DBUILD_TESTING=ON ..
8.set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64 & set _CL_= /std:c++latest
9.msbuild /m /p:Platform=x64 /p:Configuration=Release AzerothCore.sln /t:Rebuild

### Extra Notes

No response

### AC rev. hash/commit

None

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
This might be due to you specifying `\std:c++latest` which could point to C++23 (unreleased version) I would suggest that you instead specify `\std:c++20` to make sure you build with C++20 which is what AC currently supports.

However, this error message is good as it found a flaw. I just want to prepare you for more if you intend on using C++latest
