### ISSUE TITLE
Blade Flurry + Fan of Knives deals overkill damage and overheal enemy

### ISSUE THREAD

**Issue by Revan2107** [azerothcore/azerothcore-wotlk#13402]
### Current Behaviour

Using [Blade Flurry](https://www.wowhead.com/wotlk/spell=13877/blade-flurry) + [Fan of Knives](https://www.wowhead.com/wotlk/spell=51723/fan-of-knives) deal overdamage (a ten-digit number) and overheal (also a ten-digit number) an enemy.

Video og the Bug: www.youtube.com/watch?v=ZrLpB0Tx2oE 

### Expected Blizzlike Behaviour

Causing 105% weapon damage with daggers, and 70% weapon damage with all other weapons by Fan of Knives + 20% damade increasing by Blade Flurry + additional splash damage for each nearby enemy.

### Steps to reproduce the problem

0. (Optional) Use Deadly Poison IX on off-hand and Instant Poison IX on main-hand.
1. Use Blade Flurry.
2. User Adrenaline Rush (to spam FoK faster).
3. Spam Fan of Knives in сrowd of enemies (for example [Hardknuckle Forager](https://www.wowhead.com/wotlk/npc=28098/hardknuckle-forager)).
4. (Optional) During the FoK spaming try to change you autoattack target(s) by right click.

### AC rev. hash/commit

AzerothCore rev. 667e584041c7+ 2022-10-09 00:54:17 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.67.0
Using MySQL version: 80030
Using CMake version: 3.24.1
Compiled on: Linux 4.19.0-22-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azeroth-server/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod_world_chat

### Operating system

Debian 10

### Custom changes or Modules

mod_world_chat

**Comment by Revan2107** [comment]
I have spotted it's much more depends on Blade Flurry than on FoK. To reproduce try to use Blade Flurry switch targets by right click

**Comment by sidyhe** [comment]
the warrior's spell 12723 has this problem too
