### ISSUE TITLE
[AQ40] Viscidus freezing phase thawing

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13401]
original issue https://github.com/chromiecraft/chromiecraft/issues/4177
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

only checked by reading the code here:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp

Viscidius has three freezing phases, slow, freeze, solid.  solid lasts for 15 seconds and then drops to stage zero of freezing

https://user-images.githubusercontent.com/11332559/195649984-f83b9f3b-d5e8-4ca8-bc4d-12aa3718be80.mp4

### Expected Blizzlike Behaviour

according to
https://www.icy-veins.com/wow-classic/viscidus-guide-strategy-abilities-loot

each freezing phase requires a certain amount of hits to be landed within the phase. if not, the previous freezing state (0, 1 or 2) should be fallen back into and a new 15s timewindow starts, in which the required hits have to be achieved again to advance, or thaw again

### Source
![image](https://user-images.githubusercontent.com/11332559/195650904-648f99fa-c3b5-4c00-9bce-baf1448e43c1.png)
https://wowpedia.fandom.com/wiki/Viscidus?oldid=1633939

![image](https://user-images.githubusercontent.com/11332559/195650822-a9d7d659-5656-4529-9295-795ecd823d0c.png)
https://www.icy-veins.com/wow-classic/viscidus-guide-strategy-abilities-loot

![image](https://user-images.githubusercontent.com/11332559/195651402-b59d14ab-0dc7-4f8b-bf15-0136b3b9356b.png)

### Steps to reproduce the problem

.go c 87938
freeze him fullly
wait 15 seconds

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
The issue was initially created, because it seemed that the fallback to a previous state was not implemented at all.
Last I checked, we only had one kind of check: 15 seconds to shatter him in the last freezing state.
but, there was nothing implemented, which would reset him back into the previous state, e.g. from stage 2/3.

**if you managed to advance into the first freezing stage, you have 15 seconds to advance to the next freezing state, otherwise, he will fallback into the previous/lower state. This is not implemented.**

Currently, only implemented is the drop from the last frozen state to an unfrozen state if the amount of hits required arent reached within 15 seconds.

**Comment by balleny** [comment]
another correction (although i cannot confirm it fully yet)
1) there are three freezing states, each requiring about 50 hits within 15 seconds to advance into the next. once fully frozen 2) begins
2) similarly, you are required a certain amount of hits to shatter him from the frozen state.

for 1) it seems that if you dont manage to apply the required amount of hits to get into the next sub-phase, he should jump back to the previous level, starting a new 15 seconds window

for 2) it seems that if you dont manage to apply sufficient amount of physical hits given each time 15 sec time window within each subphase to keep shattering, he will thaw fully, back into the initial state

unfortunately, its hard to find a prove by video - maybe someone could verify on retail

**Comment by Gultask** [comment]
In retail, Viscidus does **not** thaw between phases. However, we have to remember that the boss was changed in MoP to allow soloing, so this could still be valid. But it'll need confirmation.
