### ISSUE TITLE
[AQ40] The Prophet Skeram Copy kill saves raid CD

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13417]
https://github.com/chromiecraft/chromiecraft/issues/4214
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15263
During encounter with Prophet Skeram Copy after split, when copy being killed, it enables raid CD. That's not intended behaviour because Skeram can be not killed but it will be already raid CC - raid state will save for people. Screenshot - 
![изображение](https://user-images.githubusercontent.com/104144379/195993477-8ebb95bb-9115-47ce-bf1f-58212cf340de.png)

### Expected Blizzlike Behaviour

Only The Prophet Skeram kill should enable CD, not his copy.

### Source

Nothing solid, but all other bosses dont lock unless killed

not sure if classic has the same messages, but no message here either way https://youtu.be/-tNMCO7_LiY?t=502

### Steps to reproduce the problem

1. .tele aq40
2. Engage Prophet Skeram.
3.  .damage 500000
4. Kill one of his copy at 1st split.
5. Observe system message that "You are now saved to this instance"

### Extra Notes

im guessing theyre supposed to be seperate mobs based on wowhead info

real
https://www.wowhead.com/classic/npc=15263
fakes
https://www.wowhead.com/classic/npc=176525

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. 2e6f6e26da8f 2022-10-12 14:39:02 -0400 (master branch) (Unix, Debug, Static)

**Comment by Gultask** [comment]
This (https://www.wowhead.com/classic/npc=176525) one is definitely a Classic or SoM change. That ID is ridiculously high 😛

**Comment by BeefSteaker** [comment]
Yeah that makes sense. Just first thing I saw
