### ISSUE TITLE
[AQ40] Fankriss the Unyielding should not have 5 mobs before fight around him

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13419]
https://github.com/chromiecraft/chromiecraft/issues/4218
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15510
Fankriss the Unyielding  has 5 Venkiss Drones before fight around him. Screenshot - ![изображение](https://user-images.githubusercontent.com/104144379/195993717-97786814-099a-467f-a97d-8335a9283764.png).

### Expected Blizzlike Behaviour

Fankriss the Unyielding should not have 5 mobs before fight around him.

### Source

https://youtu.be/-tNMCO7_LiY?t=1688

### Steps to reproduce the problem

1. .tele aq40
2. .go xyz -8000 1280 -50
3. Observe that he has  5 Venkiss Drones before fight around him.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Win10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. 2e6f6e26da8f 2022-10-12 14:39:02 -0400 (master branch) (Unix, Debug, Static)

**Comment by Gultask** [comment]
This is correct.
![image](https://user-images.githubusercontent.com/100873791/195995983-160f298b-b097-4df0-ba14-2f3d4a3569f3.png)
While I don't know where they got the '8' from. They are sniffed creatures and should be there before the fight.
