### ISSUE TITLE
[AQ40] Anubisath Sentinel - Thorns

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13433]
https://github.com/chromiecraft/chromiecraft/issues/4228
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Thorns ability doesn't deal any damage

https://user-images.githubusercontent.com/11332559/196043677-ebf21c6c-9df9-48c4-a624-7a9288ccca09.mp4

### Expected Blizzlike Behaviour

Should deal damage on player attacks according to tooltip

### Source

https://core-raiding.dk/ahnqiraj-40/aq40-guides-and-videos

multiple comments referencing thorns, dont mention as last priority, which you can assume they would if it werent working
![image](https://user-images.githubusercontent.com/11332559/196043709-c791d7fd-9377-43a1-8cb6-8eb3c5994bdc.png)
![image](https://user-images.githubusercontent.com/11332559/196043778-4012aa99-315b-4721-b87c-8e997b6ba2ce.png)
https://www.wowhead.com/wotlk/npc=15264/anubisath-sentinel#comments;mode:40player

### Steps to reproduce the problem

Attack the one with the thorns

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
Invalid, I couldn't reproduce. Keep in mind the damage won't show in logs.
