### ISSUE TITLE
[WARRIOR] Deep wounds behavior related to non-physical critical strike

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13431]
https://github.com/chromiecraft/chromiecraft/issues/4226
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Present in the Arms Warrior talent tree, Deep Wounds ( https://wowgaming.altervista.org/aowow/?spell=12867 ) tooltip states it can proc from any critical strike, not just critical strikes which are both melee-range and physical. This is due to spell critical chance rating and melee critical chance rating being fused together and normalized in WOTLK. 

Therefore, spell crit from items or enchant should be able to proc Deep Wounds. Yet currently on both the live chromiecraft realm and PTR realm, Deep Wounds can only be procced by Physical-melee critical strikes, and none of the items mentionned above.

### Expected Blizzlike Behaviour

Without this bug, a few enchantements and items should be able to proc Deep Wounds if they crit, such as but non-limited to : 

- Fiery weapon enchant : https://wowgaming.altervista.org/aowow/?item=11207 
- Fiery gauntlet : https://wowgaming.altervista.org/aowow/?item=12631
- Storm Gauntlers : https://wowgaming.altervista.org/aowow/?item=12632
- Fiery Blaze Enchant : https://wowgaming.altervista.org/aowow/?item=5421
- Stormchops : https://wowgaming.altervista.org/aowow/?item=33866

You get the idea ! Basically ANY item or enchant which has a proc effect able to crit, should be able to proc Deep Wounds. 

### Source

**Wowhead comments** : 

https://www.wowhead.com/item=33866/stormchops#comments:id=624481

https://www.wowhead.com/wotlk/spell=12867/deep-wounds : 

Sorry i can't link those for some reasons, but numerous comments on this wowhead page mention Deep Wounds proccing from anyhing : 

- User [davidthemonkey](https://www.wowhead.com/wotlk/user=davidthemonkey) mention it proccing from a trinket dealing holy spell damage ( https://www.wowhead.com/wotlk/item=39889/horn-of-argent-fury#comments ) ;

- User [90137](https://www.wowhead.com/wotlk/user=90137) state that even though the damage is solely physical and based on weapon damage, it can proc from any critical strike. ; 

- User [353796](https://www.wowhead.com/wotlk/user=353796) mention that Deep wounds procs from "ANYTHING you critically strike with according to other posts (melee critical strikes, trinkets, ranged weapons, abilities, etc)"

**Blizzard bluepost saying it's not a bug, but deciding to change it for WOTLK classic** : 

https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-october-14-deep-wounds-and-fiery-weapon-329368 

**Youtube videos ( From WOTLK Classic retail but before the blizzard's change mentionned above)** : 

https://www.youtube.com/watch?v=eutQ-HGcWFY 

https://www.youtube.com/watch?v=EXt7Mn5Gh9c

**My own research :** 

Once i read all those wowhead comments from back in the day, i went through all the original WOTLK patchnote from 3.0.2 to 3.3.5 version of the game, and blizzard NEVER changed Deep Wounds behavior related to spell crit. It just went unnoticed until Classic WOTLK in 2022. 

### Steps to reproduce the problem

Just create a warrior character with Deep Wounds talented, equip high critical chance gear, use items and enchant mentionned above and see Deep wounds not proccing. 

### Extra Notes

I am sorry, i am not a dev and i have absolutely no idea how to fix this.

I would assume you *just* would have to change Deep Wounds ( https://wowgaming.altervista.org/aowow/?spell=12867 ) flag for it to proc from any critical strike and not just melee-physical one. I think it wouldn't be complicated or take much time

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Ovahlord** [comment]
This is correct.

Proc flag 0x00011154, chance = 100, charges - 0
=================================================
  02 Deal Melee Swing
  04 Deal Melee Ability
  06 Deal Ranged Attack
  08 Deal Ranged Ability
  12 Deal Harmful Ability
  16 Deal Harmful Spell

these are the proc flags and they clearly imply that non-melee spells and abilities can also trigger the proc.

**Comment by lingxDEV** [comment]
Blizzard addressed this in Classic WotLK saying it's actually an unintended bug that was never meant to exist. It was fixed on Classic servers: https://www.wowhead.com/wotlk/news/wrath-classic-hotfixes-october-14-deep-wounds-and-fiery-weapon-329368

Not sure how we go about that, but regardless of if it was fixed or not in retail WotLK, do we really want a bug to exist on AC, just because it wasn't discovered/fixed back in the day?

This particular bug is actually gamebreaking and I don't personally think we should implement this mechanic.

Happy to hear more inputs about this.

**Comment by Nyeriah** [comment]
Reopening as reported as not fixed by the original author. 

cc @UltraNix

**Comment by UltraNix** [comment]
Fiery Weapon:
![FieryWeapon](https://user-images.githubusercontent.com/80540499/201467214-f69e499b-853f-48a4-ab89-a227602ade18.jpg)

Stormchops:
![Stormchops](https://user-images.githubusercontent.com/80540499/201467230-037bb795-df2d-43da-8b84-5b4e21581144.jpg)

Everything works okay.
