### ISSUE TITLE
Hearthstone "forgets" where its set after relog

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13446]
original issue https://github.com/chromiecraft/chromiecraft/issues/4241
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

On relog, the text in hearthstone/ethereal portal get reset.

alliance to "your inn", horde to "Dun Morogh".

![image](https://user-images.githubusercontent.com/11332559/196209613-f8e261a7-50eb-4b82-8644-7fba63cb71a9.png)

https://user-images.githubusercontent.com/11332559/196209707-f5ee6b00-289e-41a4-b20b-41930cd71f7d.mp4

### Expected Blizzlike Behaviour

Hearthstone tooltip should remember where its set

### Source

Wrath classic
https://user-images.githubusercontent.com/11332559/196209933-a080f517-617e-4ed4-b56b-2dc2ef2a3035.mp4

### Steps to reproduce the problem

Set any hearth
log out of char and back in

### Extra Notes

hearthstones were recently changed by https://github.com/azerothcore/azerothcore-wotlk/pull/13389 , could be related?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
@BeefSteaker is this a text only issue? or is the  Homebind Location reverting when using a homebind function?

**Comment by BeefSteaker** [comment]
No, location is still correct
text only as far as i can tell

**Comment by acidmanifesto** [comment]
as far as i can tell and still can tell, the pr makes no changes to the tool tip settings. 
I will see when i have more time later one today to look into it further. But this may of been a pre-exsisting issue prior to PR https://github.com/azerothcore/azerothcore-wotlk/pull/13389 that went unnoticed.

**Comment by acidmanifesto** [comment]
> I have a weakaura that shows where I'm hearthing to, first time ive noticed it was wrong was this morning.
> 
> I'll see if I have any recent footage of it

I was fully and utterly wrong. My pr did do something. Got the fix done. typing up the PR now.

**Comment by heyitsbench** [comment]
I apologize I didn't catch this during my testing.

**Comment by acidmanifesto** [comment]
> > I was fully and utterly wrong. My pr did do something. Got the fix done. typing up the PR now.
> 
> Lmao, at least you know what to fix then

You have entirely too much faith in me when im sober.
