### ISSUE TITLE
Hallows end Accepting the quest "let the fires come" doesn not summon the horseman

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#13441]
### Current Behaviour

Accepting the quest "Let the fires come" does nothing

### Expected Blizzlike Behaviour

It should begin the horseman event in the town.

### Source

https://www.wowhead.com/quest=12135/let-the-fires-come#comments:id=870117

### Steps to reproduce the problem

1. .event start 12
2. As alliance .go c 86848 (Azure Watch), 20424 (Kharanos), 11006 (Goldshire),
2. As horde .go c 19346(Razor Hill), 20425 (Brill), 17338 (Falconwing)
3. Accept the quest "let the fires come" from the matron to attempt to begin the event

### Extra Notes

Partial revert of https://github.com/azerothcore/azerothcore-wotlk/issues/8077

### AC rev. hash/commit

7ee14d44bf23

### Operating system

windows 10

**Comment by Meramaf** [comment]
I think this broked after this commit

https://github.com/azerothcore/azerothcore-wotlk/pull/12402

**Comment by Meramaf** [comment]
QUEST_STATUS_REWARDED not work on core. And OnQuestRewarded to.

**Comment by acidmanifesto** [comment]
atm a wip is in progress to correct the issue
https://github.com/azerothcore/azerothcore-wotlk/pull/13460

**Comment by acidmanifesto** [comment]
related to : https://github.com/azerothcore/azerothcore-wotlk/issues/13458
