### ISSUE TITLE
Table `command` have non-existing command 'spy', skip.

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1344]
##### SMALL DESCRIPTION:
Spy command added a new DB startup error that you can also reproduce each time you use `server info` in your console:

> AC>server info
AC>Table `command` have non-existing command 'spy', skip.
Table `command` have non-existing command 'spy', skip.
Table `command` have non-existing command 'spy', skip.
Table `command` have non-existing command 'spy', skip.
Table `command` have non-existing command 'spy', skip.
Table `command` have non-existing command 'spy', skip.
AzerothCore rev. 71e0ad005b01 2019-01-22 20:43:40 +0100 (master branch) (Unix, Debug)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 18 minute(s) 31 second(s).
Update time diff: 10ms, average: 10ms.
AC> 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/71e0ad005b0191b561616c0cfecc212782e065f4

##### OPERATING SYSTEM:

GNU/Linux

##### MODULES:

No modules, clean AzerothCore

**Comment by Deku** [comment]
@FrancescoBorzi is 6c233c4d8c49cd8f014f2df497d7c8a646b2bf74 applied in the database?

**Comment by sucofog** [comment]
AddSC not declared on ScriptLoader.cpp for commandscripts

**Comment by Deku** [comment]
It's declared but not invoked. Thanks for pointing that out.
