### ISSUE TITLE
[AQ40] Grasp of C'Thun does not disappear after boss is dead.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13443]
### Current Behaviour

title

### Expected Blizzlike Behaviour

GUIDs 6660, 6663, 6665 should disappear after C'Thun is dead

### Steps to reproduce the problem

1. `.go xyz -8665 2015 108.6 531 1`
2. See Grasp of C'Thun
3. Kill C'Thun
4. `.go xyz -8665 2015 108.6 531 1`
5. See if Grasp of C'Thun still there

### Extra Notes

Id is 180745

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/048d82ae69b26b52154f58380c3a86f79ed6a5c6

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask What about this https://github.com/azerothcore/azerothcore-wotlk/issues/12800#issuecomment-1221300069?

**Comment by Gultask** [comment]
While I can't explain that particular, I'm certain that the Grasp of C'Thun despawns on C'Thun's death, there is no reason for it to not happen. This is actually a regression after the header or instance.cpp file was changed to the better system.
