### ISSUE TITLE
The Headless Horseman cannot be summoned in LFG Dungeon

### ISSUE THREAD

**Issue by entropiccode** [azerothcore/azerothcore-wotlk#13458]
### Current Behaviour

Finishing the "Call the Headless Horseman" quest by turning in the Dreary Candle at the Loosely Turned Soil does not summon the Headless Horseman as expected, despite the quest finishing successfully.  Additionally, the gossip menu on the Pumpkin Shrine, "Call the Headless Horseman", does nothing.

### Expected Blizzlike Behaviour

Turning in the quest "Call the Headless Horseman" at the Loosely Turned Soil summons the Headless Horseman as expected.

Using the "Call the Headless Horseman" gossip menu on the Pumpkin Shrine summons the Headless Horseman.

### Steps to reproduce the problem

1. Join dungeon via the LFG tool.
2. Speak to Pumpkin Shrine to pick up quest "Call the Headless Horseman"
3. Turn in quest at the Loosely Turned Soil just behind the Pumpkin Shrine
4. Speak to Pumpkin Shrine and choose the gossip option "Call the Headless Horseman"

### Extra Notes

Looking over the SQL, the gossip option for "Call the Headless Horseman" doesn't appear to be tied to anything.

The quest "Call the Headless Horseman" does reference the "go_loosely_turned_soil" script defined in hallows_end.cpp.

### AC rev. hash/commit

AzerothCore rev. 64a891f5ab62+ 2022-09-02 12:37:11 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04.1 LTS (Docker installation)

### Custom changes or Modules

> List enable modules:
- mod-1v1-arena
- mod-account-achievements
- mod-accountbound
- mod-ah-bot
- mod-archmage-timear
- mod-assistant
- mod-auto-resurrect
- mod-boss-announcer
- mod-cfbg
- mod-congrats-on-level
- mod-costumes
- mod-duel-reset
- mod-eluna
- mod-gain-honor-guard
- mod-groupquests
- mod-guildfunds
- mod-guildhouse
- mod-humpdaybonus
- mod-instance-reset
- mod-npc-beastmaster
- mod-npc-buffer
- mod-npc-smol-buffer
- mod-npc-titles-tokens
- mod-pvp-titles
- mod-skip-dk-starting-area
- mod-solo-lfg
- mod-solocraft
- mod-transmog
- mod-weekendbonus

**Comment by maikale** [comment]
I have this problem too someone help thanks in advance

**Comment by tkn963** [comment]
I can't speak for the quest since I don't have that issue at all but the gossip option has a PR that you could try.

https://github.com/azerothcore/azerothcore-wotlk/pull/13460

**Comment by pagimu** [comment]
I have the same problem too with the headless horseman in the Dungeon. Thanks for help.
