### ISSUE TITLE
Database import 2019_01_12_07.sql error

### ISSUE THREAD

**Issue by ide1234000** [azerothcore/azerothcore-wotlk#1345]
##### SMALL DESCRIPTION:

When I executed '\azerothcore-wotlk\data\sql\updates\db_world 2019_01_12_07.sql' it not works.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

 executed successfully

##### CURRENT BEHAVIOUR:

[Err] 2006 - MySQL server has gone away
[Err] CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
SELECT COUNT(*) INTO @COLEXISTS
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'version_db_world' AND COLUMN_NAME = '2019_01_12_06';
IF @COLEXISTS = 0 THEN LEAVE proc; END IF;
START TRANSACTION;
ALTER TABLE version_db_world CHANGE COLUMN 2019_01_12_06 2019_01_12_07 bit;
SELECT sql_rev INTO OK FROM version_db_world WHERE sql_rev = '1546089286503990307'; IF OK <> 'FALSE' THEN LEAVE proc; END IF;
--
-- START UPDATING QUERIES
--

INSERT INTO version_db_world (`sql_rev`) VALUES ('1546089286503990307');

-- ----------------------------
-- Insert data npc_text
-- ----------------------------

INSERT INTO `npc_text`(`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Probability0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`, `text1_0`, `text1_1`, `BroadcastTextID1`, `lang1`, `Probability1`, `em1_0`, `em1_1`, `em1_2`, `em1_3`, `em1_4`, `em1_5`, `text2_0`, `text2_1`, `BroadcastTextID2`, `lang2`, `Probability2`, `em2_0`, `em2_1`, `em2_2`, `em2_3`, `em2_4`, `em2_5`, `text3_0`, `text3_1`, `BroadcastTextID3`, `lang3`, `Probability3`, `em3_0`, `em3_1`, `em3_2`, `em3_3`, `em3_4`, `em3_5`, `text4_0`, `text4_1`, `BroadcastTextID4`, `lang4`, `Probability4`, `em4_0`, `em4_1`, `em4_2`, `em4_3`, `em4_4`, `em4_5`, `text5_0`, `text5_1`, `BroadcastTextID5`, `lang5`, `Probability5`, `em5_0`, `em5_1`, `em5_2`, `em5_3`, `em5_4`, `em5_5`, `text6_0`, `text6_1`, `BroadcastTextID6`, `lang6`, `Probability6`, `em6_0`, `em6_1`, `em6_2`, `em6_3`, `em6_4`, `em6_5`, `text7_0`, `text7_1`, `BroadcastTextID7`, `lang7`, `Probability7`, `em7_0`, `em7_1`, `em7_2`, `em7_3`, `em7_4`, `em7_5`, `VerifiedBuild`) VALUES (6, 'Hundreds of various diagrams and schematics begin to take shape on the pages of the book. You recognize some of the diagrams while others remain foreign but familiar.', 'Hundreds of various diagrams and schematics begin to take shape on the pages of the book. You recognize some of the diagrams while others remain foreign but familiar.', 11875, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO `npc_text`(`ID`, `text0_0`, `text0_1`, `BroadcastTextID0`, `lang0`, `Probability0`, `em0_0`, `em0_1`, `em0_2`, `em0_3`, `em0_4`, `em0_5`, `text1_0`, `text1_1`, `BroadcastTextID1`, `lang1`, `Probability1`, `em1_0`, `em1_1`, `em1_2`, `em1_3`, `em1_4`, `em1_5`, `text2_0`, `text2_1`, `BroadcastTextID2`, `lang2`, `Probability2`, `em2_0`, `em2_1`, `em2_2`, `em2_3`, `em2_4`, `em2_5`, `text3_0`, `text3_1`, `BroadcastTextID3`, `lang3`, `Probability3`, `em3_0`, `em3_1`, `em3_2`, `em3_3`, `em3_4`, `em3_5`, `text4_0`, `text4_1`, `BroadcastTextID4`, `lang4`, `Probability4`, `em4_0`, `em4_1`, `em4_2`, `em4_3`, `em4_4`, `em4_5`, `text5_0`, `text5_1`, `BroadcastTextID5`, `lang5`, `Probability5`, `em5_0`, `em5_1`, `em5_2`, `em5_3`, `em5_4`, `em5_5`, `text6_0`, `text6_1`, `BroadcastTextID6`, `lang6`, `Probability6`, `em6_0`, `em6_1`, `em6_2`, `em6_3`, `em6_4`, `em6_5`, `text7_0`, `text7_1`, `BroadcastTextID7`, `lang7`, `Probability7`, `em7_0`, `em7_1`, `em7_2`, `em7_3`, `em7_4`, `em7_5`, `VerifiedBuild`) VALUES (7, 'The assortment of images, shapes, and markings come together before your eyes. The book seems to know your skill with leatherworking and offers you a choice - but be warned - you may only select one and once you have done so, may not change your mind!:', 'The assortment of images, shapes, and markings come together before your eyes. The book seems to know your skill with leatherworking and offers you a choice - but be warned - you may only select one and once you have done so, may not change your mind!:', 11892, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '',
[Msg] Finished - Unsuccessfully
--------------------------------------------------

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run bash apps/db_assembler/db_assembler.sh
2. select 2 and 3
3. import world_base.sql and world_updates.sql

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

4ba0932

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

mod-transmog

##### OTHER CUSTOMIZATIONS:

None

**Comment by ide1234000** [comment]
I use MySQL 5.6.41 in Windows 10

**Comment by poszer** [comment]
> I use MySQL 5.6.41 in Windows 10

Ok, delete your base (auth,char,world). And run apps/db_assembler/db_assembler.sh
When the command window appear, **Press 5, Import All**. And wait when process finish. 
Run server and tell me is it okay now :smiley:

**Comment by FrancescoBorzi** [comment]
@ide1234000 the problem is here:

> [Err] 2006 - MySQL server has gone away

Which is a common error: https://stackoverflow.com/search?q=2006+-+MySQL+server+has+gone+away

More specifically, the problem is probably that your mysql is set to not support big queries.

The solution is to run this query BEFORE importing the sql updates:

```SET GLOBAL max_allowed_packet=128*1024*1024;```

This is more a support request than a bug, please read this: https://github.com/azerothcore/azerothcore-wotlk/wiki/How-to-ask-for-help

**Comment by BarbzYHOOL** [comment]
???????????, @FrancescoBorzi but your change to the db_assembler is not working or what?

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL he's importing the file manually, not using the `db_assembler`.

**Comment by BarbzYHOOL** [comment]
haha ok
