### ISSUE TITLE
World Server Crash 

### ISSUE THREAD

**Issue by zranger1** [azerothcore/azerothcore-wotlk#13455]
### Current Behaviour

World server hangs during startup on:

Updating World database...
>> Applying update "2022_10_17_00.sql" 'DC064D3'...

Worldserver closes without displaying or logging any message.  

Crash Log:
https://gist.github.com/zranger1/0249542724eecdf7013bd2579013505f

Slightly simpler Stack/Var dump from running it in Visual Studio Debugger:
https://gist.github.com/zranger1/e4d348ed17eb68f2b679f1fdc214e13e

### Expected Blizzlike Behaviour

Worldserver should start.

### Steps to reproduce the problem

Build w/VS2022, retail or debug.  No docker or other containerization.  Just Windows 10.

Start authserver (works)
Start worldserver (fails)

### AC rev. hash/commit

AzerothCore rev. 07d4144c1239 2022-10-17 20:21:22 -0300 (master branch) (Win64, Debug, Static) (worldserver-daemon)

### Operating system

Windows 10 Pro

**Comment by Regrad** [comment]
My server has also stopped refreshing. It shuts down after trying to apply any update.

**Comment by Kitzunu** [comment]
Can you try doing it with RelWithDebInfo? to get less clutter, it might also be an issue of just Debug.

**Comment by zranger1** [comment]
It behaves the same way on release, relwithdebinfo and debug.  The relwithdebinfo log is identical to the debug for all practical purposes.  

I wound up putting a breakpoint on line 502 of DBUpdater.cpp, and could step through and watch it happen (but can't yet see exactly why). 

Roughly what's going on is that
    ```ApplyFile() in E:\github\azerothcore-wotlk\src\server\database\Updater\DBUpdater.cpp```
is calling
   ```CreateChildProcess() in E:\github\azerothcore-wotlk\src\common\Utilities\StartProcess.cpp```
and eventually causing an exception in boost::process with the message "Empty Environment"

When the exception is thrown,  env parameter passed has the following contents, which is strange because earlier, it seems to have been able to retrieve the proper environment.
```
 boost::process::detail::windows::basic_environment_impl<char> | {_data={ size=0 } _env_arr={ size=0 } _env_impl=0x000001f9594e3530 {0x0000000000000000 <NULL>} } | boost::process::detail::windows::basic_environment_impl<char>
```
Could this this have something to do with the new code for of passing the mySQL password via the environment?  
I'll keep debugging, but I'm new to this codebase, and have been dodging boost for a long time.   Probably anybody with more familiarity would figure it out faster.

**Comment by Winfidonarleyan** [comment]
> My server has also stopped refreshing. It shuts down after trying to apply any update. I think this happens after an update [c855e8d](https://github.com/azerothcore/azerothcore-wotlk/commit/c855e8d227a73b8328fb3d0a7a9eb99347a60738)

Yes, this commit breaks core for windows

**Comment by Winfidonarleyan** [comment]
> It behaves the same way on release, relwithdebinfo and debug. The relwithdebinfo log is identical to the debug for all practical purposes.
> 
> I wound up putting a breakpoint on line 502 of DBUpdater.cpp, and could step through and watch it happen (but can't yet see exactly why).
> 
> Roughly what's going on is that `ApplyFile() in E:\github\azerothcore-wotlk\src\server\database\Updater\DBUpdater.cpp` is calling `CreateChildProcess() in E:\github\azerothcore-wotlk\src\common\Utilities\StartProcess.cpp` and eventually causing an exception in boost::process with the message "Empty Environment"
> 
> When the exception is thrown, env parameter passed has the following contents, which is strange because earlier, it seems to have been able to retrieve the proper environment.
> 
> ```
>  boost::process::detail::windows::basic_environment_impl<char> | {_data={ size=0 } _env_arr={ size=0 } _env_impl=0x000001f9594e3530 {0x0000000000000000 <NULL>} } | boost::process::detail::windows::basic_environment_impl<char>
> ```
> 
> Could this this have something to do with the new code for of passing the mySQL password via the environment? I'll keep debugging, but I'm new to this codebase, and have been dodging boost for a long time. Probably anybody with more familiarity would figure it out faster.

just revert commit c855e8d

**Comment by acidmanifesto** [comment]
Can you update to the latest revision? 
The issue was corrected in https://github.com/azerothcore/azerothcore-wotlk/commit/563596bc69ed2feabf76bf5377acf5159f951604
Ensure you rerun cmake before compiling.

**Comment by acidmanifesto** [comment]
Ok. So just following up. I did update to the absolute latest revision before i had to head out and i can confirm there is a issue with windows build when apply sqls. I went ahead and made mention of it in the staff room.

**Comment by acidmanifesto** [comment]
You can use this as a temporary work around until the issue is resolve
https://github.com/azerothcore/azerothcore-wotlk/pull/13465

**Comment by zranger1** [comment]
Tested & working.  Thanks!

**Comment by acidmanifesto** [comment]
> Tested & working.  Thanks!    

Please keep in mind this is only a temporary solution for the time being until a permanent solution is made.
