### ISSUE TITLE
The Ice Grave in Sindaga P3 does not shield the player from the icy grip

### ISSUE THREAD

**Issue by FDGHBSGd** [azerothcore/azerothcore-wotlk#13464]
### Current Behaviour

The Ice Grave in Sindaga P3 does not shield the player from the icy grip

### Expected Blizzlike Behaviour

-

### Source

---

### Steps to reproduce the problem

--

### Extra Notes

-

### AC rev. hash/commit

-

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-transmog

**Comment by FDGHBSGd** [comment]
Icecrown Citadel    Sindragosa

**Comment by Kitzunu** [comment]
Add hash/Commit
