### ISSUE TITLE
NPC Lupos (521) dealing Shadow Damage even when tamed

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#13475]
### Current Behaviour

If you tame Lupos (ID=521), the wolf will continue to deal shadow damage

### Expected Blizzlike Behaviour

Pets are normalized. When tamed, Lupos should deal physical damage like all other wolves.

### Steps to reproduce the problem

tame Lupos
observe damage type

### Extra Notes

The pet therefore bypasses all kinds of armor values on bosses/npcs.
As most npcs dont have shadow resi, the pet will deal a significantly higher amount of damage compared to other wolves tamed.

Discoverd on ChromieCraft

### AC rev. hash/commit

AzerothCore rev. b427e8e18cb6+ 2022-10-17 04:28:24 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Unix

**Comment by heyitsbench** [comment]
Should be fixed with 670d5724cb099c6fc6b162a23e20be90db0a205b.
