### ISSUE TITLE
[Bounty] Feature: add discord webhook support

### ISSUE THREAD

**Issue by 0xCiBeR** [azerothcore/azerothcore-wotlk#13502]
### Describe your feature request or suggestion in detail

Add support for sending logs and events to discord via Webhook URLs https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

### Describe a possible solution to your feature or suggestion in detail

Include it by default in the core

Should run Async

Should have support for embeds.

**Comment by 0xCiBeR** [comment]
Posted a bounty for this [here](https://app.bountysource.com/issues/112985824-feature-add-discord-webhook-support)

**Comment by Jacckii** [comment]
If you want support for discord webhooks, then here is a working solution. https://gist.github.com/Jacckii/09b9d77693e3123ddde8e652eb461d7d

Since there wasn't any info about where and for what are you going to use this feature, I left the including this into the core as an exercise for you. It's just straightforward c&p the code no need to edit anything, it works straight out of the box.

**Comment by Winfidonarleyan** [comment]
https://github.com/WarheadCore/WarheadBand/commit/f11b73fdff8394f7fdd749958af3ff1a5d122e4b

**Comment by 0xCiBeR** [comment]
> If you want support for discord webhooks, then here is a working solution. https://gist.github.com/Jacckii/09b9d77693e3123ddde8e652eb461d7d
> 
> Since there wasn't any info about where and for what are you going to use this feature, I left the including this into the core as an exercise for you. It's just straightforward c&p the code no need to edit anything, it works straight out of the box.
> 
> If there are no additional requests, please close the issue so the bounty can be claimed.

Hey thanks for the work, would only be missing some work on sending embeds in webhooks.

**Comment by Jacckii** [comment]
@0xCiBeR Hey, I've added the option to send embeds. I have updated the Gist with the source code for you. It's fully tested, and I even made an example for you with preview how the output looks like
https://gist.github.com/Jacckii/09b9d77693e3123ddde8e652eb461d7d
