### ISSUE TITLE
Force of nature's Treants not scaling with haste rating

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13531]
https://github.com/chromiecraft/chromiecraft/issues/4288
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Treants spawned by the balance druid talent Force of Nature (https://wowgaming.altervista.org/aowow/?spell=33831) are currently not benefitting from the druid's haste rating. 

### Expected Blizzlike Behaviour

It should work similarly to unholy deathknight's summon gargoyle (https://wowgaming.altervista.org/aowow/?spell=49206) as in "it should snapshot with the player current haste stat when summoned".

So you could use stuff like Haste Potion ( https://wowgaming.altervista.org/aowow/?item=22838 ) or even MCP ( https://wowgaming.altervista.org/aowow/?item=9449 ) before casting Treant so they fully benefit from haste. 

### Source

**Wowhead comment from back in the day :** 

https://www.wowhead.com/wotlk/spell=/force-of-nature#comments : 

![image](https://user-images.githubusercontent.com/11332559/197409851-47078294-fed7-44fd-826c-0d65597891b1.png)
![image](https://user-images.githubusercontent.com/11332559/197409866-6524d0dd-1189-40d3-8a0b-27b26ac430b2.png)

**Youtube video (for WOTLK retail but according to the previously mentionned wowhead comments, that's how it worked at the time anyway) :** 

https://www.youtube.com/watch?v=fzcP1dz_oB4 *

Small disclaimer about this video : Beside the clickbait title, he mention a bug in the video. The bug he mention isn't treant scaling with haste, but the fact that you can abuse spec-swap going to use treants in feral spec.

### Steps to reproduce the problem

1. Create a druid
2. .learn 33831
3. .level 59
4. .setskill 160 300 300
5. .additem 22838 & 9449
6. Use MCP ( https://wowgaming.altervista.org/aowow/?item=9449 ) + Haste potion ( https://wowgaming.altervista.org/aowow/?item=22838 ) in order to have massive haste, making the difference more noticeable. 
7. You'll see no difference between 0 haste and 900 haste rating.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by boom8866** [comment]
https://wowgaming.altervista.org/aowow/?spell=49206 )  According to the feedback, the stone ghost may have the same problem
