### ISSUE TITLE
[Rather be Fishin'] Eels cannot swim upward to attack you

### ISSUE THREAD

**Issue by FallingSnow** [azerothcore/azerothcore-wotlk#13551]
### Current Behaviour

Eels seem unable to swim upward and just follow you around at their current height.

The eels also moves very slowly. I assume this might be because the server calculation believes the eel is moving up at an angle and thus it's horizontal vector is lower.

https://user-images.githubusercontent.com/2512197/197927477-adb3d52c-11ab-42b5-8482-5d0d84d36e63.mp4

### Expected Blizzlike Behaviour

Eels should be able to swim upward.

### Steps to reproduce the problem

1. Go to the northern lake in Terokkar Forest.
2. Attack an eel while swimming above the water.
3. The eel will not be able to come up and attack you.

### Extra Notes

Location: Outlands -> Terokkar Forest -> Silmyr Lake

The orb dropped by the eels also seems to be much higher than it should be (you are too far to loot ever when standing directly on the orb). See https://youtu.be/9nOWoaV-PYc?t=124 for expected behavior.

### AC rev. hash/commit

Azerothcore rev. 48fccc851d84+ 2022-04-06

### Operating system

Linux x64 (Docker)

### Custom changes or Modules

- Auction house

**Comment by Gultask** [comment]
That's a general and long-standing problem with mmaps. Creatures seem to **refuse** to swim, and will rather "walk" along the the surface of the floor or the surface of the water.
