### ISSUE TITLE
[AQ40] Ouro can be taunted

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#13565]
### Current Behaviour

Boss can be taunted.

[Video of boss being taunted](https://streamable.com/mdcsx3)

### Expected Blizzlike Behaviour

Ouro should not be tauntable during the encounter.

### Source

https://vanilla.warcraftlogs.com/reports/DdwvJnPcXF9jh1Wk#fight=63&type=summary&source=40&view=events&eventstart=8468135

Log from WoW Classic and boss being immune to single warrior taunt used in the encounter.

![ouro taunt immune](https://user-images.githubusercontent.com/100415626/198262917-fc38c9e3-c567-4f02-a897-0ecbae9c099c.png)

![taunt casted once](https://user-images.githubusercontent.com/100415626/198262937-12120150-ee26-48ca-9578-324a27138672.png)

Reddit theorycrafting mentioning boss is taunt immune:  https://www.reddit.com/r/classicwow/comments/hys41j/ouro_question/

### Steps to reproduce the problem

1. Pull Ouro
2. Taunt him

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4310

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10.

**Comment by Pyromanihack** [comment]
Suggestion to fix the bug:
UPDATE `creature_template` SET `flags_extra` = 257 WHERE (`entry` = 15517);
