### ISSUE TITLE
Hair Colour Changes when Cycling through Blood Elf Facial Hair and Hair Styles

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13566]
https://github.com/chromiecraft/chromiecraft/issues/4317
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

When cycling through male blood elf facial hair options, upon reaching a particular one (thin strip in middle of chin, just below mouth), it reverts the hair colour to blonde. One is able to change the colour while using that facial hair, so it seems to be connected to the act of switching to it rather than its mere presence. Likewise, changing hair style also resets colour.

### Expected Blizzlike Behaviour

Hair colour should not change when selecting different options.

### Source

wrath classic, but it doesnt happen for any other race and its too weird to find a source from retail

https://user-images.githubusercontent.com/11332559/198343387-a12e93fe-2d17-4efd-a4a0-4f69b3d104e7.mp4

### Steps to reproduce the problem

1. Enter character creator
2. Select male Blood Elf
3. Set hair colour to anything but blonde
4. Cycle through facial hair options until hair colour changes.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/47bf00ad2f40a40025c9f48c1c7943fd986ce04a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

HD Patches

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
This is a client issue and almost definitely related to the HD patch.

**Comment by BeefSteaker** [comment]
My bad, i need to remember to check this
