### ISSUE TITLE
Can we implement two realm lists with the same realmid?Feature: 

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#13568]
### Describe your feature request or suggestion in detail

![image](https://user-images.githubusercontent.com/18535853/198420447-d5c39870-72b8-4219-9d8b-17178fc26f53.png)
For example, we have two network IPs, so that both networks can connect to the same server

**Comment by bbwow** [comment]
this is two world, one account  characters.

**Comment by pklloveyou** [comment]
@bbwow I have implemented this function

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/198650384-574d0363-35e4-4ec0-94f8-c0ce64b3717b.png)

**Comment by pklloveyou** [comment]
I can log in to the same server through both networks

**Comment by yuanf225** [comment]
What are the benefits of doing this, load balancing and high availability?

**Comment by noisiver** [comment]
> What are the benefits of doing this, load balancing and high availability?

I'm curious about that too. I would like to say, judging by the little information available, that it lets you have the same characters on multiple realms?

**Comment by pklloveyou** [comment]
Allow multiple networks to connect to the same realm

**Comment by noisiver** [comment]
I still don't see the point, I'm afraid. If it all runs through the same authserver and sends the data to the same worldserver - or at least the same network server-side - what would it change?

**Comment by yuanf225** [comment]
It would be great if HA could be implemented by pointing two world servers to one domain, which could reduce server pressure

**Comment by yuanf225** [comment]
It would be great if HA could be implemented by pointing two world servers to one realmid, which could reduce server pressure

**Comment by noisiver** [comment]
Wouldn't that mean that if people from different regions want to play together, they can't?

High availability would more or less require battle.net to be implemented.

**Comment by pklloveyou** [comment]
This function refers to the server with multiple IPs, and users can choose the best (Network operator)IP to connect to the world server

**Comment by noisiver** [comment]
I see. Thank you for clearing that up for me!

**Comment by Kitzunu** [comment]
I still dont understand. You are still creating different realms, why would you use the same ID for them?

**Comment by Nyeriah** [comment]
Different authservers directing to the same worldserver?

**Comment by IntelligentQuantum** [comment]
> This function refers to the server with multiple IPs, and users can choose the best (Network operator)IP to connect to the world server

You can run another authserver on another vps without creating a new realm
Note: Just authserver

**Comment by Kitzunu** [comment]
But why. You will still have the worldserver by itself, so it wont gain any improvements?

**Comment by IntelligentQuantum** [comment]
It affects the player's ping

**Comment by Nyeriah** [comment]
That's curious, afaik authserver only handles the authentication process and after that is forward to the worldserver you're connecting to it directly, so I wonder how does it affect ping.

**Comment by noisiver** [comment]
I don't get it either. If the worldserver, the same one that the player connects to every time, doesn't move but the authserver does - logically it should have no effect whatsoever. It must be some kind of magic.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/200574079-0fb3b998-b7a3-4c18-a3f9-ae32cf93843a.png)

**Comment by ChibaPet** [comment]
This appears to be closed now, but the obvious use I see, that hasn't been mentioned, is that this would allow for a worldserver to run behind a NAT without requiring hairpinning for internal clients to connect.  The notion of running another authserver is probably sufficient for this, and has merits of its own.

**Comment by Vrozaksen** [comment]
Hi! This thread helped me setup same server for 2 different networks. First one for local network and second one for VPN (just making safe semi-public server using Wireguard VPN for people to access my server) :))
