### ISSUE TITLE
QuestCompletionLog (CompletedText) not working in locales

### ISSUE THREAD

**Issue by PolluxTroy0** [azerothcore/azerothcore-wotlk#1357]
Clean build from latest master branch.

In template_quest, the column "QuestCompletionLog" seems to be the column "CompletedText" in template_quest_locale". After i tried to add some data (for frFR), in game, data stay in english.

So, maybe this column is not coded in core ?

AzerothCore rev. 2729b35bb378+ 2019-01-19 12:07:26 +0100 (master branch) (Win32, Release) (worldserver-daemon)

**Comment by FrancescoBorzi** [comment]
@PolluxTroy0 please add your AC commit hash version. "Latest master" makes sense now but later we won't have track of which version you were using when you got this issue.

**Comment by PolluxTroy0** [comment]
AzerothCore rev. 2729b35bb378+ 2019-01-19 12:07:26 +0100 (master branch) (Win32, Release) (worldserver-daemon)

**Comment by LukasVolgger** [comment]
There is no issue. The table you looking for is quest_request_items_locale. 

Here ist the locale Text for CompletionText.

The problem is, that the columns in quest_template doesn't match with the locales columns.
