### ISSUE TITLE
Sell prices are unaffected by durability loss.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13626]
https://github.com/chromiecraft/chromiecraft/issues/4326

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently items that have durability, when damaged/broken, are sold for full price to vendors.

### Expected Blizzlike Behaviour

The cost of repairing said item should be tacked on the price paid by the vendor.

### Source

[World of Warcraft: Classic](https://github.com/vmangos/core/issues/1664).

### Steps to reproduce the problem

1. `.additem 13253`
2. Target yourself and use either `.damage 10000` or `.die` and take the resurrection sickness a few times to drop the durability of the [Hands of Power](https://www.wowhead.com/wotlk/item=13253).
3. Sell the item to a vendor.
4. Observe the discrepancy between the price noted by the tooltip in your inventory and the price the vendor pays.

### Extra Notes

Might need to take reputation deductions into account as well, unsure as of yet.

Vmangos' implementation: https://github.com/vmangos/core/pull/1676

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Tried just transplanting the vmangos implementation into AC. The money given to the player was off by a single copper (Tooltip said 90,20, received 90,21) and buyback price reflected the price as if it were undamaged. Probably need to investigate not only any rep discounts, but also the behavior of buyback prices.

**Comment by heyitsbench** [comment]
Tested on Wrath Classic PTR. Buyback price as well as durability is supposed to remain the same as the sell price, so if you sell the item with no money you'd still be able to buy it back. This price/durability is *not* impacted whatsoever by reputation (Neutral compared to Exalted, didn't test any other standing states) nor if the vendor you're selling to can actually repair the item or not. The tooltip issue unsurprisingly doesn't seem to happen on live servers.
