### ISSUE TITLE
Sarkoth npc not hostile but neutral

### ISSUE THREAD

**Issue by Asherdoom** [azerothcore/azerothcore-wotlk#1363]
SARKOTH (scorpid NPC neutral instead of hostile

##### SMALL DESCRIPTION: 
Sarkoth should be the only hostle scorpid ins tarter area, but is neutral (yellow)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
He should be hostile (name in red and attack on sight)

as per Wowwiki infos
https://wowwiki.fandom.com/wiki/Sarkoth

##### CURRENT BEHAVIOUR:
he is just passive

##### STEPS TO REPRODUCE THE PROBLEM:
create horde npc>valley of trials>Accept quest SARKOTH!>mount the small cliff>you find npc

##### EXTRA NOTES:
N/A

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
commit 987095e2c9da04b6ac9efcd2639a012cc72552d7

##### OPERATING SYSTEM:
Mac OSX 1.11
![screenshot_012719_101318](https://user-images.githubusercontent.com/16918614/51801446-b1449000-221c-11e9-9f88-5975156fdb38.jpeg)

**Comment by poszer** [comment]
Mobs in starting zones are neutral. Just looking old videos, this is correct. When you attack Npc, it will attack you too.

**Comment by BarbzYHOOL** [comment]
In tbc he's hostile but maybe it was changed in wotlk

**Comment by poszer** [comment]
Faction is wrong, will update soon
