### ISSUE TITLE
[BUG] Combat Range with SmartAI

### ISSUE THREAD

**Issue by alex2972** [azerothcore/azerothcore-wotlk#13630]
### Current Behaviour

Hey guys if u guys are running the latest azerothcore version, please test this
Go to valley of trials and pull a lvl 3 scorpion with a ranged attack and then stay still
The scorpion should come all the way to melee range and attack you, but instead it stands a decent distance away from you, i thought it might be the model but i changed the models and it still happens. So then i found out it has something to do with the SmartAI, once i removed SmartAI from the scorpion, the problem was fixed. But that was just the beggining
Turns out lots of creatures with SmartAI (if not all of them) have this bug
Which didn't use to happen in older versions of Azerothcore

### Expected Blizzlike Behaviour

Mobs get in melee range and fights, instead of standing outside of range.

### Steps to reproduce the problem

1) Go to valley of trials
2) pull a lvl 3 scorpion with a ranged attack 
3) stay still

![escorpion](https://user-images.githubusercontent.com/117167443/199219946-44897596-936f-4b0b-9a6d-da9502d6dc45.png)

### Extra Notes

![Captura de pantalla 2022-11-01 080142](https://user-images.githubusercontent.com/117167443/199219641-fc8d6d92-f4ff-42ca-89a7-a83fde292dcd.png)

### AC rev. hash/commit

![Captura de pantalla 2022-11-01 080142](https://user-images.githubusercontent.com/117167443/199219641-fc8d6d92-f4ff-42ca-89a7-a83fde292dcd.png)

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
4cf0906a9164 <- Oct 2022 Update your core. This is way too old to be making issues on.

**Comment by Kitzunu** [comment]
Nevermind, Just saw this was opened in November 😅

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/17543
