### ISSUE TITLE
Race/Class stats seem to be incorrect.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#13645]
### Current Behaviour

Certain race/class/level combinations seem to be incorrect with regards to base stats. Using Night Elf Druid as an example, here are the stats taken from the CC PTR using the `.levelup` command for levels [1](https://user-images.githubusercontent.com/38561765/199390682-3536daa7-5bd6-42fc-8ebb-d1ca14829005.png), [2](https://user-images.githubusercontent.com/38561765/199390710-f2df28c2-325e-4c6e-b834-11e771c32cb3.png), [3](https://user-images.githubusercontent.com/38561765/199390745-1cc311bd-7f11-4c3d-854b-960ae4f72684.png), [4](https://user-images.githubusercontent.com/38561765/199390785-7ef1ec98-9abc-4802-9bb9-9bc86cff577c.png), and [5](https://user-images.githubusercontent.com/38561765/199390814-c40966a5-fe2b-4992-9592-d8ae6a79bb9f.png).

### Expected Blizzlike Behaviour

Taken from a Night Elf Druid at levels [1](https://user-images.githubusercontent.com/38561765/199391274-05203b7d-d5dc-4d90-a237-2dff7176b626.png), [2](https://user-images.githubusercontent.com/38561765/199391314-25a72416-80e6-424b-a558-1ca194b94c47.png), [3](https://user-images.githubusercontent.com/38561765/199391337-ef85b2a8-3502-4bb8-b6f9-2e0bcadc57f7.png), [4](https://user-images.githubusercontent.com/38561765/199391342-c40dd0f3-c44f-4dc0-8679-7dc36c1e51e5.png), and [5](https://user-images.githubusercontent.com/38561765/199391351-173b27f1-34c1-435f-a8ed-0ff7ac1c014d.png).

### Source

World of Warcraft: Wrath Classic.

### Steps to reproduce the problem

1. Make a character.
2. Observe.

### Extra Notes

It is *very* likely that this issue extends to many, most, or all of the race, class, and level combinations.

Would be nice to know where the currently used stats came from.

### AC rev. hash/commit

1954ca9e3327e298a3d88e85f226b9a517f08185

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Kitzunu** [comment]
iirc TC has this all sniffed, check their DB for values

**Comment by heyitsbench** [comment]
> iirc TC has this all sniffed, check their DB for values

Their table related to this issue is the same as ours, as seen in [this issue](https://github.com/TrinityCore/TrinityCore/issues/28305).

**Comment by heyitsbench** [comment]
Compiling as many base stat values as possible into a spreadsheet [here](https://docs.google.com/spreadsheets/d/1yH2ip7GL168K0s-qxcECcLvN5iKx_oS3iFzqdM87SBs/edit?usp=sharing).

**Comment by Kitzunu** [comment]
It's fine, we just need to level every class to 80 kek

**Comment by heyitsbench** [comment]
Also found a [Wowpedia page](https://wowpedia.fandom.com/wiki/Base_attributes?oldid=2344534) listing all the base attributes, though at the time Wrath was out it was far from complete. Seems to line up more with Wrath Classic than our current values.

**Comment by heyitsbench** [comment]
If/when all of the PRs that referenced this issue are merged, this issue will be resolved.

**Comment by heyitsbench** [comment]
The way I want these stats to be stored (i.e. race modifiers in one table, base class level stats in another) is apparently what TC is already doing in their master branch. If I'm up to it, I might submit a PR to bring that over to AC.

**Comment by heyitsbench** [comment]
> If I'm up to it, I might submit a PR to bring that over to AC.

I was up to it. The opened PR would serve the purpose of all ten of the PRs that have referenced this issue already.
