### ISSUE TITLE
[AQ40] Twin Emperors Blizzard frequency

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#13647]
### Current Behaviour

Vek'lor Blizzard is cast every 5 to 12 seconds on Twin Emperors in Temple of Ahn Quiraj. Sometimes experiencing up to 3 Blizzards at the same time, while on Classic videos Vek'lor never casts more than 1 Blizzard.

### Expected Blizzlike Behaviour

Watching some videos, it seems that blizzard is casted a max of twice between teleports, usually just once.
Unfortunately, it is only tracked in public combatlogs if people are affected by the debuff or take damage (being affected by the debuff should be sufficient tho for tracking)

a random cast frequency between 10 to 20 seconds seems more reasonable. Sometimes it can be 30 seconds between a single Blizzard.

### Source

e.g.
https://www.youtube.com/watch?v=4CmadeEllDk
https://vanilla.warcraftlogs.com/reports/RyYpF9arvbf7XZCm#fight=31&type=auras&view=events&spells=debuffs&ability=26607
https://vanilla.warcraftlogs.com/reports/2MDX7whKZg8PCb6d#fight=42&view=events&type=auras&spells=debuffs&ability=26607

Logs are a bit tricky, cause 1) people may run into it after it has been cast already (esp. considering that it is no real threat in classic)

### Steps to reproduce the problem

Check Twin Emperors source code.

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4312

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10

**Comment by Gultask** [comment]
We've taken the timers from packets we got from Retail SL sniffing. They've never proven wrong so far but it's possible.
I'll take another and record it to make sure. Unfortunately we don't have the manpower to take those sniffs from WotLK Classic. Especially since it can take several runs to do so, plus a long time to take all the samples needed.

**Comment by Gultask** [comment]
Cmangos uses 15-30, Vmangos uses 15-20. TC also uses 15-?

**Comment by Si1ker** [comment]
> 

literally, any of those are better than the 5s, 12s currently used.

**Comment by Gultask** [comment]
I don't disagree but this is what I got from sniffing:

![image](https://user-images.githubusercontent.com/100873791/199788945-ea8d9eff-9d62-460e-8e71-734caf2ba7fa.png)

So there must be a mechanic I'm missing

**Comment by Si1ker** [comment]
> 

@Gultask , so the total range from that is 5-30. right?
On another note, could the timer possibly start right after the swap instead of the initial engagement?

**Comment by Gultask** [comment]
>so the total range from that is 5-30. right?

Not really. From what I saw so far in Retail and videos there's never a max timer, only a minimum. so the range we use is only an approximation anyway.

>On another note, could the timer possibly start right after the swap instead of the initial engagement?

Now there's an idea. I will try that.

**Comment by ImmortalusDev** [comment]
It is casted every 12s.

**Comment by Gultask** [comment]
Ok. Two things:

1. Teleport does not reschedule Blizzard
2. Yes. I was indeed wrong. For some reason failed casts were being logged as complete ones in the parser. All of the casts below 10s were failed casts.
3. I'll make a PR. Sorry for the delay, I wanted to deal with this last week, preferrably.
