### ISSUE TITLE
Bartlett's Bitter Brew flight point teleport

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13654]
https://github.com/chromiecraft/chromiecraft/issues/4381
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Use Bartlett's Bitter Brew Before choosing a flight path ([Bartlett's Bitter Brew] (https://www.wowhead.com/tbc/item=37498/bartletts-bitter-brew) ). After getting a gryph cancel Nauseus buff that makes you vomit. Get insta teleported to flight destination. 

https://user-images.githubusercontent.com/11332559/199580100-86cf4b67-71de-48c4-a5e6-0886c7bd679f.mp4

### Expected Blizzlike Behaviour

No teleport

### Source

its such a notable glitch is would almost definitely be mentioned somewhere
https://www.wowhead.com/wotlk/item=37498/bartletts-bitter-brew#comments

### Steps to reproduce the problem
.additem 37498
use flight path
cancel nausea buff mid flight

### Extra Notes

~~appears to be visual only, character is not visible to others, and npc's are not loaded~~ if you wait for the flight to have finished it saves your new location

https://user-images.githubusercontent.com/11332559/199581038-d0e9716d-34cd-4a31-bc07-6de73e378324.mp4

https://wowgaming.altervista.org/aowow/?item=37498

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10 

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Logging out while under this effect and logging back in resets your viewpoint to be along your flightpath properly.

**Comment by BeefSteaker** [comment]
If you allow the flight to finish it does save the location you got to though
