### ISSUE TITLE
[AQ40] Ouro's Sand Blast doesn't always  hit highest threat target in a frontal cone

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#13651]
### Current Behaviour

[Sand Blast](https://classic.wowhead.com/spell=26102/sand-blast) does not always target and hit frontal highest threat target in a frontal cone.
A very helpful comment made by [Cooties-cc](https://github.com/Cooties-cc) regarding the current behavior of the spell and boss model:

> Correct on direction of sand blast being bugged. Perhaps this is what the ticket should pertain to. We noticed in our attempts before a kill, that sand blast was never in the direction the boss was facing past the initial pull. It wasn't till I noticed that hunter pets are scripted to always be behind their target, and thus, hunter pets showed that the back of the boss was not always linked to his model direction. It was a big key to figuring out why the raid was still getting sand blasts, but also a big bug. I thought I had seen a post up about this after we had done it, but maybe was worded wrong.

### Expected Blizzlike Behaviour

Should always have an effect on targets in 180-degree cone in the direction Ouro

### Source

https://www.wowhead.com/classic/guide/ouro-temple-of-ahnqiraj-strategy

### Steps to reproduce the problem

1. Pull Ouro
2. Wait for sand blast cast

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4311

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10

**Comment by Gultask** [comment]
fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/13578
