### ISSUE TITLE
[AQ40] C'thun Giant Claw Tentacle can hit from far away

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#13669]
### Current Behaviour

C'thun Giant Claw Tentacle can hit from far away.

### Expected Blizzlike Behaviour

C'thun Giant Claw Tentacle should only hit people in melee range.

### Source

![Giant tentacle melee](https://user-images.githubusercontent.com/100415626/199750354-feeedad4-7cda-4c66-b737-c96f2c710707.png)

https://www.wowhead.com/wotlk/npc=15728/giant-claw-tentacle

### Steps to reproduce the problem

1. .go xyz -8670.49 1953.46 108.9 531 0.363
2. Enter C'thun Phase 2

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4379

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10

**Comment by Gultask** [comment]
@Contrubius How far away? It's reach is pretty large.

**Comment by Gultask** [comment]
Nvm I saw the video 😛

**Comment by Si1ker** [comment]
Solved by PR #13693

SPELL_THRASH was the cause, proofs:

![image](https://user-images.githubusercontent.com/61223313/200074963-8955ed4a-2191-4b7f-bfef-0dcdcea716fd.png)

![image](https://user-images.githubusercontent.com/61223313/200074971-c2b51819-ab3c-4087-a2b4-2a8171538092.png)
