### ISSUE TITLE
[AQ40] Eye of C'thun casting Eye Beams after Eye Tentacles spawn before Dark Glare

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#13668]
### Current Behaviour

Before Dark Glare, when the Eye Tentacles spawn, Eye of C'thun casts one or two Eye Beams.

### Expected Blizzlike Behaviour

Before Dark Glare, when the Eye Tentacles spawn, Eye of C'thun should not cast any Eye Beams and should immediately start to channel Dark Glare.

### Source

Videos from WoW Classic:
https://youtu.be/SCeLoLmg3us?t=3413

https://youtu.be/ZbC21q203oQ?t=100

https://youtu.be/TWNdKnDQ-JM?t=55

### Steps to reproduce the problem

1. .go xyz -8670.49 1953.46 108.9 531 0.363
2. Start the C'thun fight

### Extra Notes

[Wowhead](https://www.wowhead.com/wotlk/npc=15589/eye-of-cthun)
[Aowow](https://wowgaming.altervista.org/aowow/?npc=15589)

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4377

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Windows 10

**Comment by Gultask** [comment]
Keep in mind that this only affects **the first Dark Glare**. Dark Glare and Eye Tentacle spawns are not related in any other way and do not interact with each other, as the timers are independent.

**Comment by Contrubius** [comment]
My bad. So should I edit it to say First Glare?

čet, 3. stu 2022. 20:04 Gultask ***@***.***> je napisao:

**Comment by valery445** [comment]
In our guild runs on 02.11 and on PTR, this bug occurs with every Dark Glare, not only the first one. Not sure what do you mean by only affecting the first.

**Comment by Gultask** [comment]
Oh?
That might mean some unintentional scheduling issue then. As the Eye Tentacle spawns shouldn't be linked to Dark Glare in any way other than a similar first timer.
I was talking about Blizzlike behaviour. Sorry I should've specified that, I forgot.

**Comment by UltraNix** [comment]
@Gultask So the only thing to change is the timer?

**Comment by Gultask** [comment]
@UltraNix And remove the re-scheduling for Ete Tentacle spawn after Dark Glare, if there is any.
