### ISSUE TITLE
missing Bonechewer Devastator and Bonechewer Backbreaker spawns

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13678]
https://github.com/chromiecraft/chromiecraft/issues/4364
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

1. In the room with her only one Bonechewer Backbreaker.
2. Lisaile Fireweaver according to information from the web base, respawns 8 minutes.

### Expected Blizzlike Behaviour

1.
>By 51520 (207 – 1·0) on 2007/05/16 (Patch 2.0.12)		
She will have 3 "bodyguards" in the same room, all evenly spaced so you can pull them.
1 Pull left guard, and kill
2 Kill Lisaile
3 Kill the right guard, just get close since he is usually a spellcaster.
4 Pick up note where there right guard was previously standing, this starts the quest unseen hand as stated by boggus.
5 The 3rd guard which is behind the wall in an entrance can be avoided,

https://www.youtube.com/watch?v=oJKc6W7ECYs - 1:15 (2xBonechewer Devastator and 2xBonechewer Backbreaker)

### Source

https://www.wowhead.com/tbc/quest=10003
https://www.wowhead.com/tbc/quest=10002
https://www.youtube.com/watch?v=oJKc6W7ECYs - 1:15

### Steps to reproduce the problem

.go cr 84701

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
again, same numbers as other DBs, so will require a sniff
