### ISSUE TITLE
Fire Brigade Practice missing spanish translation

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13676]
https://github.com/chromiecraft/chromiecraft/issues/4360
### What client do you play on?

esES

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

Seasonal NPC has missing translation

-Quests has the objective "Fight Fires" instead of Spanish text

![imagen](https://user-images.githubusercontent.com/117111663/199119881-796d776c-4b08-4925-af1f-72c6cff0afc2.png)

-When Turning Quest it has missing translation

![imagen](https://user-images.githubusercontent.com/117111663/199120105-41c8ea91-b223-487e-8483-30e6707cffae.png)

### Expected Blizzlike Behaviour

Text Should be localized

### Source

![imagen](https://user-images.githubusercontent.com/117111663/199119791-f5e8f534-e12b-44b7-a4a5-bb404c5ed121.png)

### Steps to reproduce the problem

.go c id 24519

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
@BeefSteaker Quest ID for this pls? :3

**Comment by heyitsbench** [comment]
Found it, [this is the expected text](https://user-images.githubusercontent.com/38561765/199774978-ebac1e5c-a228-4391-a0c5-da9545c590b4.png).

**Comment by M4th3m4tic4l** [comment]
It would be easier to look for a Spanish video of the mission and that's it XD

**Comment by heyitsbench** [comment]
> It would be easier to look for a Spanish video of the mission and that's it XD

All that was needed was a macro. 😛

**Comment by Valdifer** [comment]
Entrando en wowhead puedes buscar por el título y sacar las traducciones, igualmente he tardado como 3 minutos en hacerlo

INSERT INTO quest_offer_reward_locale (ID, locale, RewardText, VerifiedBuild) VALUES
	(11360, 'esES', '¡Estás mojado y lleno de ceniza! ¡Tienes que haber estado apagando fuegos!$b$b¡Bien hecho! Como miembro honorífico de la brigada de bomberos, te ruego que regreses si alguna vez te necesitamos.', 0),
	(11439, 'esES', '¡Estás mojado y lleno de ceniza! ¡Tienes que haber estado apagando fuegos!$b$b¡Bien hecho! Como miembro honorífico de la brigada de bomberos, te ruego que regreses si alguna vez te necesitamos.', 0),
	(11440, 'esES', '¡Estás mojado y lleno de ceniza! ¡Tienes que haber estado apagando fuegos!$b$b¡Bien hecho! Como miembro honorífico de la brigada de bomberos, te ruego que regreses si alguna vez te necesitamos.', 0);
	
	UPDATE quest_template_locale SET ObjectiveText1 = 'Apaga fuegos' WHERE id = 11360 AND (locale = 'esES' OR locale = 'esMX');
	UPDATE quest_template_locale SET ObjectiveText1 = 'Apaga fuegos' WHERE id = 11439 AND (locale = 'esES' OR locale = 'esMX');
	UPDATE quest_template_locale SET ObjectiveText1 = 'Apaga fuegos' WHERE id = 11440 AND (locale = 'esES' OR locale = 'esMX');

INSERT INTO quest_request_items_locale (ID, locale, CompletionText, VerifiedBuild) VALUES 
	(11360, 'esES', 'Hola, $N. ¿Has estado perfeccionando tu técnica como bombero? ¡No te olvides del area de práctica al norte!', 0),
	(11439, 'esES', 'Hola, $N. ¿Has estado perfeccionando tu técnica como bombero? ¡No te olvides del area de práctica al norte!', 0),
	(11440, 'esES', 'Hola, $N. ¿Has estado perfeccionando tu técnica como bombero? ¡No te olvides del area de práctica al norte!', 0);

Saludos

**Comment by M4th3m4tic4l** [comment]
Thanks Valdifer
