### ISSUE TITLE
Dalaran infernal and gold gain spam from NPC

### ISSUE THREAD

**Issue by Asherdoom** [azerothcore/azerothcore-wotlk#1369]
DALARAN weird infernals and npc gains

##### SMALL DESCRIPTION:
combat log flooded with npc earning golds (see screeen) plus infernals wandering in a shop where they are not supposed to exist (they are near weekly quest givers AND insto this shop that is located as sson as you enter/exit sewers and fly point of dalaran

![screenshot_012719_145622](https://user-images.githubusercontent.com/16918614/51804842-3ee7a600-2244-11e9-849f-ce105aed59a4.jpeg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
both of these 2 things should not happen

##### CURRENT BEHAVIOUR:
as per screenshot they flood combat log which can cause crash if enough players are around i believe plus risk bugging it

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
commit 987095e

##### OPERATING SYSTEM:
Linux

**Comment by FrancescoBorzi** [comment]
@Viste can you please have a look? He is using `staging`

**Comment by Maurowin** [comment]
He is in GM mode

**Comment by poszer** [comment]
Its Invisible Stalker ( Floating ). And you can see it just in GM mode. That Creature must be there.
