### ISSUE TITLE
Race (0) not found in DBC: wrong DBC files?

### ISSUE THREAD

**Issue by Krath** [azerothcore/azerothcore-wotlk#137]
**Current behaviour**: Whenever I get in game with every character, the console displays this error : Race (0) not found in DBC: wrong DBC files?

**Steps to reproduce the problem**:

1. Create a character
2. Log into the game

It also skips the character's movie at the beginning.

**Branch(es)**: master

**AC hash/commit**:  ce219ce7e45cef460e806394431ef71802f7677b

**Operating system**:  Windows 10 x64

**Comment by talamortis** [comment]
can confirm :)

**Comment by Abyssking** [comment]
I send my logs over here too !!!!

Server.log : http://pastebin.com/vYsj7hgP
CrashLog : http://pastebin.com/jxJvJPAv

**Comment by Zaklinac** [comment]
Confirm. And bad ID announcer on Alliance side https://snag.gy/2qXw6L.jpg

**Comment by Yehonal** [comment]
Error fixed with https://github.com/azerothcore/azerothcore-wotlk/commit/ce07d52235dfdf46b656b6f5e8307f328b313eeb
