### ISSUE TITLE
DBC.Locale  dont's work.

### ISSUE THREAD

**Issue by rushpixy** [azerothcore/azerothcore-wotlk#13701]
### Current Behaviour

eluna: player:GetDbcLocale()   =0   whatever  DBC.Locale = x
GetDbcLocale()  is from  the locale of client dbc .

### Expected Blizzlike Behaviour

config it in worldserver.conf

### Steps to reproduce the problem

1

### AC rev. hash/commit

1

### Operating system

ubuntu 20.4

**Comment by Kitzunu** [comment]
I will close for a couple of reasons:

1. Seems to be an Eluna issue
2. You are not filling in the template at all. You are missing steps to reproduce the problem and hash/commit. 

Feel free to fill it in properly. or open an issue on Eluna and I can reopen =)
