### ISSUE TITLE
[TBC Progression] Profession cooldowns

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13710]
https://github.com/chromiecraft/chromiecraft/issues/4396
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

Certain crafting abilities from multiple professions do not trigger a cooldown

### Expected Blizzlike Behaviour

during TBC content, those crafts were limited by a cooldown.

tailoring 3 days 20h cooldown
https://www.wowhead.com/tbc/spell=31373/spellcloth
https://www.wowhead.com/tbc/spell=36686/shadowcloth
https://www.wowhead.com/tbc/spell=26751/primal-mooncloth

alchemy 20h cooldown
https://www.wowhead.com/tbc/spell=29688/transmute-primal-might

### Source

![image](https://user-images.githubusercontent.com/11332559/200127109-7dcdb839-1941-4bfa-aa6c-dd8471e2449d.png)

https://www.wowhead.com/tbc/spell=31373/spellcloth
https://www.wowhead.com/tbc/spell=36686/shadowcloth
https://www.wowhead.com/tbc/spell=26751/primal-mooncloth

### Steps to reproduce the problem

(for spellcloth)

.learn 3908
.learn 31373
.additem 21842 2
.additem 22457 2
.additem 21884 2

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
If I understand correctly, this is not an issue with AC. If anything, it'd be an issue with the progression module CC uses, though I'm not sure this is an issue that would be handled by that module.

**Comment by BeefSteaker** [comment]
yeah just realised that myself. its still mentioned on the wrath wowhead, but looking into it further it was removed in 3.0.8
