### ISSUE TITLE
[TBC] Making spellcloth doesn't spawn level 70 Angered Nether-wraith

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13711]
https://github.com/chromiecraft/chromiecraft/issues/4404
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

After making spellcloth no [Angered Nether-wraith](https://www.wowhead.com/tbc/npc=17870/angered-nether-wraith) are spawned

### Expected Blizzlike Behaviour

Spellcloth can only be created in [Netherstorm](https://www.wowhead.com/tbc/zone=3523/netherstorm) and will spawn a hostile level 70 [Angered Nether-wraith](https://www.wowhead.com/tbc/npc=17870/angered-nether-wraith).

### Source

https://www.wowhead.com/tbc/spell=31373/spellcloth

### Steps to reproduce the problem

1. Learn tailoring
2. .setskill 197 350 350
3. .additem 24316
4. learn spellcloth
5. .tele netherstorm
6. .additem 21842 10
7. .additem 22457 10
8. .additem 21884 10
9. make spellcoth
10. observe if mobs are spawned

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by v-mstrs** [comment]
Doesn't seem to be the case (anymore?), spawns just fine.

**Comment by Gultask** [comment]
Here: https://github.com/azerothcore/azerothcore-wotlk/pull/15284
I didn't see the issue before, ty for testing again.
