### ISSUE TITLE
[AQ40] C'thun stomach tentacles are moving

### ISSUE THREAD

**Issue by shaszun** [azerothcore/azerothcore-wotlk#13722]
### Current Behaviour

Tentacles inside C'thun stomach are moving, not sure how it's triggered. Probably some spell with a CC. We had also big eyes tentacle in second phase moving after fear or other CC. Pets might be the cause too, other possible cause might be the aggro of people outside of the stomach.

### Expected Blizzlike Behaviour

Stomach tentacles and big eyes tentacles should be rooted in place.

### Steps to reproduce the problem

1. Get C'thun to phase 2.
2. Get inside it's stomach

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/8e0b6aca1a47...bb9e80ded1ec

### Operating system

Windows 10

**Comment by Gultask** [comment]
They are rooted. And placing fear on them (.aura 51240) isn't moving them so it must be something else. Pets have been a problem with rooted NPCs before so it could be related.

**Comment by shaszun** [comment]
It's hard to find it, when you have 25 people in the raid. This is the second bug, which require RNG to kill the boss and makes it a lot harder than expected. If the tentacles is at the wall, only range can kill it.

**Comment by Gultask** [comment]
I've not been able to see it with pets either, so far. They're staying in place for me no matter what I try.

**Comment by shaszun** [comment]
It might not be a specific spell. I spoke a bit with my guildies. They said that the tentacles inside were aggroed by people outside. Probably that's why they move in their direction, but can't leave the stomach.

**Comment by Gultask** [comment]
Fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/13732
