### ISSUE TITLE
Secrets of the Flamebinders, Thinning the Ranks

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1374]
##### SMALL DESCRIPTION:
The chain order of these quests does not work.
This requires PR #1351 to be applied, otherwise these quests aren't even available. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- The quest [Secrets of the Flamebinders](https://wowgaming.altervista.org/aowow/?quest=12222) should close the quest [Thinning the Ranks](https://wowgaming.altervista.org/aowow/?quest=12223), and vice-versa (completing one should close the other, making it unavailable).

- The quest [The Thane of Voldrune](https://wowgaming.altervista.org/aowow/?quest=12255) should require completing 1 of either [Secrets of the Flamebinders](https://wowgaming.altervista.org/aowow/?quest=12222) or [Thinning the Ranks](https://wowgaming.altervista.org/aowow/?quest=12223)

##### CURRENT BEHAVIOUR:
- The quest [Secrets of the Flamebinders](https://wowgaming.altervista.org/aowow/?quest=12222) does not close the quest [Thinning the Ranks](https://wowgaming.altervista.org/aowow/?quest=12223), and vice-versa (both can be completed).

- The quest [The Thane of Voldrune](https://wowgaming.altervista.org/aowow/?quest=12255) can be taken without completing the pre-requisite quest (1 of either [Secrets of the Flamebinders](https://wowgaming.altervista.org/aowow/?quest=12222) or [Thinning the Ranks](https://wowgaming.altervista.org/aowow/?quest=12223))

##### STEPS TO REPRODUCE THE PROBLEM:
1.  .quest add 12294
2.  .go creature 119620
3.  Hand in quest
4.  .go creature 120547
5.  Quest The Thane of Voldrune is already available
6.  Complete either Secrets of the Flamebinders or Thinning the Ranks
7.  Whichever you complete, the other does not become unavailable

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
987095e2c9da04b6ac9efcd2639a012cc72552d7

##### OPERATING SYSTEM:
Windows 10

**Comment by wetbrownsauce** [comment]
Re-tested, issue still exists as described.

**Comment by Kitzunu** [comment]
Actually, if you are going acording to WoWPedia and WoWWiki then you need to complete

A [74] Thinning the Ranks & A [74] Secrets of the Flamebinders

to unlock A [74] The Thane of Voldrune

not one or the other.
