### ISSUE TITLE
[BWL] Razorgore the Untamed resets encounter upon casting Conflagrate when soloing

### ISSUE THREAD

**Issue by entropiccode** [azerothcore/azerothcore-wotlk#13761]
### Current Behaviour

When fighting Razorgore the Untamed solo, in Phase 2 if he casts Conflagrate it will reset the entire encounter as if the player had died.

### Expected Blizzlike Behaviour

When fighting Razorgore the Untamed solo, in Phase 2 if he casts Conflagrate he will continue to attack the player, as there are no other targets to swap to.

### Steps to reproduce the problem

1. Start encounter against Razorgore the Untamed in BWL
2. Destroy all of the eggs while Mind Controlling Razorgore to initiate Phase 2
3. Wait for Razorgore to cast Conflagrate.

### Extra Notes

Seems to be caused by this bit of code in boss_razorgore.cpp
```
case EVENT_CONFLAGRATION:
    DoCastVictim(SPELL_CONFLAGRATION);
    if (me->GetVictim() && me->GetVictim()->HasAura(SPELL_CONFLAGRATION))
        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1))
            me->TauntApply(target);
    events.ScheduleEvent(EVENT_CONFLAGRATION, 30000);
    break;
```
If I am understanding this correctly, upon casting Conflagration he looks for a new target to start attacking.  Given that when soloing there are no other targets for Razorgore to switch to, the encounter just resets as though the player had died.

I originally assumed that it was the Confusion loss of control effect caused by Conflagration causing the reset, as Mind Control will also reset encounters when soloing.  However this behavior persists even with the Confusion effect removed from the Conflagration spell.

This behavior and others like it should have checks to switch aggro back to the player when that player is solo instead of resetting the encounter.

### AC rev. hash/commit

AzerothCore rev. 64a891f5ab62+ 2022-09-02 12:37:11 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80031
Using CMake version: 3.16.3
Compiled on: Linux 5.15.0-47-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 291014951 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Ubuntu 22.04.1 LTS (Docker installation)

### Custom changes or Modules

- mod-1v1-arena
- mod-account-achievements
- mod-accountbound
- mod-ah-bot
- mod-archmage-timear
- mod-assistant
- mod-auto-resurrect
- mod-boss-announcer
- mod-cfbg
- mod-congrats-on-level
- mod-costumes
- mod-duel-reset
- mod-eluna
- mod-gain-honor-guard
- mod-groupquests
- mod-guildfunds
- mod-guildhouse
- mod-humpdaybonus
- mod-instance-reset
- mod-npc-beastmaster
- mod-npc-buffer
- mod-npc-smol-buffer
- mod-npc-titles-tokens
- mod-pvp-titles
- mod-skip-dk-starting-area
- mod-solo-lfg
- mod-solocraft
- mod-transmog
- mod-weekendbonus

**Comment by entropiccode** [comment]
Okay, while I'm not comfortable enough in C to write the code to properly resolve this issue, I was able to stop it from happening by commenting some lines.  The following sections in the file boss_razorgore.cpp are causing this behavior:

```
bool CanAIAttack(Unit const* target) const override
        {
            return !(target->GetTypeId() == TYPEID_UNIT && !secondPhase) && !target->HasAura(SPELL_CONFLAGRATION);
        }
```
```
case EVENT_CONFLAGRATION:
    DoCastVictim(SPELL_CONFLAGRATION);
    if (me->GetVictim() && me->GetVictim()->HasAura(SPELL_CONFLAGRATION))
        if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1))
            me->TauntApply(target);
    events.ScheduleEvent(EVENT_CONFLAGRATION, 30000);
    break;
```

I made the following changes, and the encounter no longer resets on Conflagration cast:
```
bool CanAIAttack(Unit const* target) const override
        {
            //return !(target->GetTypeId() == TYPEID_UNIT && !secondPhase) && !target->HasAura(SPELL_CONFLAGRATION);
            return !(target->GetTypeId() == TYPEID_UNIT && !secondPhase);
        }
```
```
case EVENT_CONFLAGRATION:
    DoCastVictim(SPELL_CONFLAGRATION);
    //if (me->GetVictim() && me->GetVictim()->HasAura(SPELL_CONFLAGRATION))
    //    if (Unit* target = SelectTarget(SelectTargetMethod::Random, 1))
    //        me->TauntApply(target);
    events.ScheduleEvent(EVENT_CONFLAGRATION, 30000);
    break;
```

**Comment by BeefSteaker** [comment]
i beleive theres already a pr for this https://github.com/azerothcore/azerothcore-wotlk/pull/13161

**Comment by balleny** [comment]
simply put, razorgore should try to attack the highest, non-conflagurated threat target.
if all players in the threat table are affected by conflag, the highest person in the threat table should be attacked.
