### ISSUE TITLE
Dark portal missing animations /npc

### ISSUE THREAD

**Issue by Asherdoom** [azerothcore/azerothcore-wotlk#1376]
Missing npc on dark portal /stairs of destiny

##### SMALL DESCRIPTION:
pit lord and felguards and demons missing into stairs of destiny attack event (they are patrolling path of glory but VERY slow, looks almost immobile! they reach after good 10 minutes the stairs of destiny but atack in small packs
![screenshot_012819_102836](https://user-images.githubusercontent.com/16918614/51839309-a7d42a00-22e7-11e9-910a-7da5d432200e.jpeg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This is how is supposed to be
![03_conflict](https://user-images.githubusercontent.com/16918614/51839412-ec5fc580-22e7-11e9-8daa-11e262dd6f3e.jpg)
![51bc99b070b4403ca9c777d4d067071a 92b10be6](https://user-images.githubusercontent.com/16918614/51839416-eec21f80-22e7-11e9-88cd-95016928d5e9.jpg)

##### CURRENT BEHAVIOUR:
horde/alliance npc arrive to the stairs and then afk there await despawning

##### STEPS TO REPRODUCE THE PROBLEM:
just enter trhough the dark portal

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
commit 987095e

##### OPERATING SYSTEM:
Linux

**Comment by Maurowin** [comment]
confirm

**Comment by Viste** [comment]
@Maurowin what branch are you use master or stage?

**Comment by Maurowin** [comment]
@Viste Master
