### ISSUE TITLE
Using Secondary Talents set makes "Mounts" tab disapear

### ISSUE THREAD

**Issue by Revan2107** [azerothcore/azerothcore-wotlk#13764]
### Current Behaviour

I have bought and learned riding mount but it is disapear as soon as I used Secondary Talents Set.

Video of the bug: https://youtu.be/-bkVh_iux8Y

### Expected Blizzlike Behaviour

All mounts should stay after Secondary Talets Set has been used.

### Steps to reproduce the problem

1. Learn riding skill.
2. Buy mount.
3. Learn second specialization.
4. Use second specialization.
5. Open "Pets" tab.
6. There aren't "Mounts" tab over there.

### Extra Notes

Character has been migrated from TrinityCore database

### AC rev. hash/commit

AzerothCore rev. 636df195147f+ 2022-10-19 10:57:29 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.67.0
Using MySQL version: 80030
Using CMake version: 3.24.1
Compiled on: Linux 4.19.0-22-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azeroth-server/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List enable modules:
- mod-globalchat

### Operating system

Debian 10

**Comment by Revan2107** [comment]
@heyitsbench fow new character it doesn't happen. I also spotted I don't have "Dual Talent Specialication" achievement. Maybe that's a reason.

![image](https://user-images.githubusercontent.com/53276857/200958571-c83ed2ad-5748-4470-af21-5c19fe2f40f3.png)

**Comment by heyitsbench** [comment]
> @heyitsbench fow new character it doesn't happen. I also spotted I don't have "Dual Talent Specialication" achievement. Maybe that's a reason.

I'm willing to bet that it's due to the transfer from TC to AC in that case.
