### ISSUE TITLE
Roetten Stonehammer wrong gossip DB entry

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13766]
https://github.com/chromiecraft/chromiecraft/issues/4447
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

I am playing on Chromiecraft. This npc:
https://www.wowhead.com/classic/npc=5637/roetten-stonehammer
has the following gossip entry:
"My wind riders are trained to fly quickly through the hot barrens air."
This is obviously the wrong gossip (the npc is a dwarf in Ironforge)

### Expected Blizzlike Behaviour

I suspect the NPC has no gossip text at all, look at this video:
https://www.youtube.com/watch?v=8AxkRQXwkDA&t=12s

### Source

[https://www.wowhead.com/classic/npc=5637/roetten-stonehammer
shows](https://www.wowhead.com/wotlk/npc=5637/roetten-stonehammer)
shows no gossip for this NPC. The current one is obviously wrong. Gossip should be removed.

wrath classic no gossip
![image](https://user-images.githubusercontent.com/11332559/201133138-acf9ccd6-865b-4dfa-842a-a9b025db8597.png)

### Steps to reproduce the problem

1.teleport to npc 5637
2. no
3. no
4. right-click on npc

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
For the record, feel free to not copy the issue 1:1 from the CC report. Including [easy] in the issue title is one such thing you don't need to bring over. 😉
