### ISSUE TITLE
(DB/NPC): Mistress of Doom

### ISSUE THREAD

**Issue by Volkyte** [azerothcore/azerothcore-wotlk#1377]
Mistress of DOOM visual bug

##### SMALL DESCRIPTION:
npc hovering the terain (like 15 yards) and glitching in the air
![screenshot_012819_104414](https://user-images.githubusercontent.com/16918614/51840121-fc78a480-22e9-11e9-8eaa-25c16597f835.jpeg)
![screenshot_012819_104415](https://user-images.githubusercontent.com/16918614/51840125-000c2b80-22ea-11e9-906c-6de576370748.jpeg)
![screenshot_012819_104418](https://user-images.githubusercontent.com/16918614/51840133-039fb280-22ea-11e9-8d8b-322d04a2d577.jpeg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
they should not fly

##### CURRENT BEHAVIOUR:
as per screenshot

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
commit 987095e

##### OPERATING SYSTEM:
linux

**Comment by poszer** [comment]
Please while opening issue, fill template " Steps to reproduce problems ". For example :
1. .go creature XXX
2. Creature should be on ground / Not flying

**Comment by Asherdoom** [comment]
1 Go to hellfire peninsula
2 go pools of aggronar in the north-northeast area of hellfire
3 go to the biug skeleton (Aggronar skeleton) on the right you find a black like altar where an elite Man'anri Eredar is situated
5 get into the stairs there and wait
6 mistress of doom making diagonal patrol is floating in the air

sorry for late reply inserted here the steps to follow as correction.

**Comment by comix1988** [comment]
.go creature 68725

**Comment by poszer** [comment]
Waypoint is okay, but NPC fail while walking through water. 
[Video Included](https://youtu.be/i8J_-rXdu98)

**Comment by JamesGent** [comment]
Issue is still live. NPC walks normally/fine for most of her journey, and then floatwalks/breaks on her way from one point to the next.

Repro steps: .go creature 68725

![Desktop 27-11-2020 17-13-56-364](https://user-images.githubusercontent.com/61194190/100472346-003b0500-30d4-11eb-8b57-b1c35d2046f0.png)

**Comment by buddiman** [comment]
This seems to be fixed at https://github.com/azerothcore/azerothcore-wotlk/commit/dafef5bd7859b330cc5c835ee463107944cc915f

I observed the npc with the guid of 68725 around 15 minutes now and she is pathing just fine. No floatwalking or similar.

**Comment by FrancescoBorzi** [comment]
thanks @buddiman for letting us know!
