### ISSUE TITLE
Consecration sometimes not doing damage.

### ISSUE THREAD

**Issue by coolnow6996** [azerothcore/azerothcore-wotlk#13777]
### Current Behaviour

Consecration not doing damage sometimes, its 50/50 if it does damage or not. 

### Expected Blizzlike Behaviour

Does damage if u put it down. 

### Source

Have shadow play footage of it not working on 2 characters. 

### Steps to reproduce the problem

Click Consecration. 
......
Profit?

### Extra Notes

N/A

### AC rev. hash/commit
AzerothCore rev. 2ad56371130a 2022-11-09 08:47:33 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected Players: 275. Characters in world: 233.
Connection Peak: 483.
Server uptime: 3 day(s) 3 hour(s) 9 minute(s) 34 second(s)
Update time diff: 10ms, average: 10ms.

### Operating system

Windows 10 x64

### Custom changes or Modules

None, just some lightweight addons.

**Comment by Kitzunu** [comment]
Add AC hash/commit, otherwise it will be closed... There is a reason some fields are marked mandatory to fill in...

run .server debug command in the console and paste the entire output

**Comment by coolnow6996** [comment]
Alright 1 sec.

**Comment by coolnow6996** [comment]
How do i edit the current issue? sorry I've never used this before.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/201473914-caba731d-9686-4576-8008-c7c93d197de3.png)
![image](https://user-images.githubusercontent.com/24550914/201473923-5a481d80-e67f-498c-b3ca-b93d8b93ef90.png)

**Comment by coolnow6996** [comment]
I can only run .server info or .server motd. 

Im new to this sorry.

**Comment by Kitzunu** [comment]
It's fine, send the output of server info.

**Comment by coolnow6996** [comment]
Updated

**Comment by Gultask** [comment]
We'd appreciate the footage as well as the position the player is in is fairly important here.

**Comment by coolnow6996** [comment]
Can i upload them to youtube as unlisted and send the link here?
wont take me long

**Comment by coolnow6996** [comment]
I also want to mention, it works 100% of the time out of an instance, or so it seems.

**Comment by Gultask** [comment]
Yup. That's fine.

**Comment by coolnow6996** [comment]
Just rendering it now, few mins.

**Comment by coolnow6996** [comment]
https://www.youtube.com/watch?v=wd5isFI5CvY&ab_channel=FuryJosh

**Comment by coolnow6996** [comment]
It shows it working once throughout the first clip. not breaking LOS

**Comment by coolnow6996** [comment]
You guys fixed it already?

**Comment by coolnow6996** [comment]
Will keep an eye out if it happens again, wp <3

**Comment by Gultask** [comment]
@coolnow6996 It isn't merged yet. I'll post it in #changelog-chromie if it's merged before the server updates ^^

**Comment by coolnow6996** [comment]
Ahh cool :)
