### ISSUE TITLE
Razorgore the Untamed unable to cast destory egg spell.

### ISSUE THREAD

**Issue by jasanhell1** [azerothcore/azerothcore-wotlk#13770]
### Current Behaviour

Phase 1: When player is controlling Razorgore the Untamed, we need to destroy all the eggs to go Phase 2.

But when player is controlling Razorgore the Untamed and using the destroy egg spell. The spell is not casting. 

### Expected Blizzlike Behaviour

when player is controlling Razorgore the Untamed and using the destroy egg spell. The spell should be casting.

### Steps to reproduce the problem

1. spell=19873 can be casting.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/tree/f5454969d12daa2316b3e9c244307bba73c83de3

### Operating system

Windows 11 x64

### Custom changes or Modules

NPCBOT
Mod-AutoBalance
Mod-ahbot
Mod_LuaEngine
Mod-RacialTraitSwap
Mod-RandomEnchants
Mod-SkipDKModule
Mod-Solocraft
Mod-SoloLfg

**Comment by jasanhell1** [comment]
![WoWScrnShot_111022_200106](https://user-images.githubusercontent.com/35847663/201263195-b4e33f0d-dea1-47df-9faa-3080a16cf4bc.jpg)

**Comment by heyitsbench** [comment]
Does this issue occur with no modules installed?

**Comment by jasanhell1** [comment]
> Does this issue occur with no modules installed?

I tested. NPCBot problem. I will report in there.

Thank you.
