### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Magaaston** [azerothcore/azerothcore-wotlk#13771]
### Current Behaviour

hello everyone, an error occurs when compiling the server, please help me solve the problem, I understood that something needs to be updated, but I don't understand that there is no information on the Internet either

CMake Error at src/cmake/compiler/clang/settings.cmake:27 (message):
  Clang: AzerothCore requires version 10.0.0 to build but found 7.0.1
Call Stack (most recent call first):
  src/cmake/platform/unix/settings.cmake:53 (include)
  src/cmake/macros/CheckPlatform.cmake:27 (include)
  CMakeLists.txt:94 (include)

### Expected Blizzlike Behaviour

I didn't understand what to write here;(

### Steps to reproduce the problem

I do not know what to do

### AC rev. hash/commit

#
# This file is part of the AzerothCore Project. See AUTHORS file for Copyright information
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#

if ((USE_COREPCH OR USE_SCRIPTPCH) AND (CMAKE_C_COMPILER_LAUNCHER STREQUAL "ccache" OR CMAKE_CXX_COMPILER_LAUNCHER STREQUAL "ccache"))
  message(STATUS "Clang: disable pch timestamp when ccache and pch enabled")
  # TODO: for ccache https://github.com/ccache/ccache/issues/539
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Xclang -fno-pch-timestamp")
endif()

# Set build-directive (used in core to tell which buildtype we used)
target_compile_definitions(acore-compile-option-interface
  INTERFACE
<c/cmake/compiler/clang/settings.cmake" 138L, 4540C           1,1       Наверху

### Operating system

Debain 10

**Comment by LukasVolgger** [comment]
Hello Maagaston.  This is the wrong place for compilation problems.  Better check out the Discord server and ask for help there.  In addition, the error message tells you that you need to update Clang, if you google it you will definitely find how to do it.

AzerothCore Discord: https://discord.gg/sTFcpudK
