### ISSUE TITLE
Twin spires missing cap/timer

### ISSUE THREAD

**Issue by Asherdoom** [azerothcore/azerothcore-wotlk#1378]
Zangarmarsh twins spires should be cappable /timed

##### SMALL DESCRIPTION:
Spires in zangarmarsh do not trigger cap time/countdown timercapping bar when enar them as player

##### EXPECTED BLIZZLIKE BEHAVIOUR:
https://wowwiki.fandom.com/wiki/Twin_Spire_Ruins
described in here
![screenshot_012819_110021](https://user-images.githubusercontent.com/16918614/51840928-2d59d900-22ec-11e9-9999-b023e07bd08c.jpeg)
as you can see no timer no capping bar and no possession icons on top of screens.
This is not crucial in wotlk but for tewinks still be useful because allow em in dungeon to collect shards for pvp level 70 gear.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
commit 987095e

##### OPERATING SYSTEM:
Linux

**Comment by comix1988** [comment]
try to set "pvp on"

**Comment by poszer** [comment]
Please diable gm mode while doing that. Also, if you are not in gm mode, enable Player Vs Player mode on your characters.  I have tested this, and everything is correct, working. As the proof i'm including some Images from two beacons controlled ( west & east )
![screenshot_4](https://user-images.githubusercontent.com/41213210/51893673-e03a3d80-23a5-11e9-90b7-5554175b670c.jpg)
![twinspire](https://user-images.githubusercontent.com/41213210/51893674-e0d2d400-23a5-11e9-8ccf-875d2e74b49e.jpg)
![maptwin](https://user-images.githubusercontent.com/41213210/51893675-e0d2d400-23a5-11e9-96df-35d9087159ca.jpg)
![barincreasing](https://user-images.githubusercontent.com/41213210/51893676-e0d2d400-23a5-11e9-88db-1f337fdb7b43.jpg)
![screenshot_3](https://user-images.githubusercontent.com/41213210/51893677-e0d2d400-23a5-11e9-8525-42dc9ecbbb0d.jpg)
