### ISSUE TITLE
[Mana-Tombs] Ethereal Crypt Raider does not use "Enrage"

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13790]
### Current Behaviour

Ethereal Crypt Raider does not use "Enrage"

### Expected Blizzlike Behaviour

Must use enrage at low HP. 

According to TrinityCore, this is >25% health
https://github.com/TrinityCore/TrinityCore/issues/24808
>(@ID,0,4,5,2,0,100,1,0,25,0,0,11,8599,0,0,0,0,0,1,0,0,0,0,0,0,0,"Ethereal Crypt Raider - Between 0-25% Health - Cast 'Enrage' (No Repeat)"),

In the video, he uses enrage at about 15%
https://youtu.be/_xrZl5eAheU?t=57
![4565](https://user-images.githubusercontent.com/32459796/201491149-93ec7746-2000-43dc-aca5-52f4f7258447.jpg)

### Source

https://youtu.be/_xrZl5eAheU?t=57
https://github.com/TrinityCore/TrinityCore/issues/24808

### Steps to reproduce the problem

.tele mt
.go cr 83305

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Windows 10 x64

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)

**Comment by BeefSteaker** [comment]
they have it in their smartai, they just dont do it for some reason
![image](https://user-images.githubusercontent.com/11332559/201549196-b912a700-5d30-4d82-8b84-33c4ec4f99d1.png)

**Comment by Gultask** [comment]
Try adding a triggered flag in CastFlags. I can't remember which one it is but it's in the wiki for smart_scripts

**Comment by BeefSteaker** [comment]
Tried that, they still only cast soul strike
