### ISSUE TITLE
[Blood Furnace] Shadowmoon Warlock incorrect use of Fel Power

### ISSUE THREAD

**Issue by clovaek** [azerothcore/azerothcore-wotlk#13819]
### Current Behaviour

[Shadowmoon Warlock](https://wowgaming.altervista.org/aowow/?npc=17371) casts [Fel Power](https://wowgaming.altervista.org/aowow/?spell=33111) on Felguard Brute while in combat with the player.

### Expected Blizzlike Behaviour

[Shadowmoon Warlock](https://wowgaming.altervista.org/aowow/?npc=17371) should cast [Fel Power](https://wowgaming.altervista.org/aowow/?spell=33111) sporadically when out of combat, on his [Felguard Brute](https://wowgaming.altervista.org/aowow/?npc=18894) or [Felguard Annihilator](https://wowgaming.altervista.org/aowow/?npc=17400)

Video shows no casts of Fel Power during combat.

### Source

tbc classic
https://youtu.be/8Gk4d2v0JbA?t=1956

2008 wotlk
https://youtu.be/zFtU0-Ze_NU?t=306

### Steps to reproduce the problem

.go creature 138234
drop combat and observe shadowmoon warlock not casting fel power
engage and observe shadowmoon warlock casting fel power

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=17371
https://wowgaming.altervista.org/aowow/?npc=18894
https://wowgaming.altervista.org/aowow/?npc=17400
https://wowgaming.altervista.org/aowow/?spell=33111
https://www.wowhead.com/wotlk/npc=17371/shadowmoon-warlock

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2ad56371130ab7e9a96f2a92b167a6eeb895e44f

### Operating system

Ubuntu 20.04

**Comment by Santaria94** [comment]
Confirmed. Also the same behavior in Wrath Classic
https://youtu.be/QgYxSueBUBQ?t=1252 - 20:52, 21:28
