### ISSUE TITLE
[Leatherworking] Drums do not apply Tinnitus debuff

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#13834]
### Current Behaviour

If any of the Leatherworking Drums are used, no debuff is applied.

### Expected Blizzlike Behaviour

When used, everyone affected receives the Tinnitus (51120) debuff that prevents any other drum buffs from being applied.

### Source

>I've never had this buff applied to me, now that wrath is out. I do, however, note that drums cannot be applied to level 80 characters.
Sadness- perhaps they just decided they couldn't really work around these?
>>Not only does this prevent drum rotation, it's rather akin to a group-wide cd. So basically if someone in the group you're in screws up and uses a drum that you don't benefit from, you can't use another drum yourself.

>Caused by receiving a drum buff. Effectively prevents drum rotations, meaning there's no reason to have more than one drummer per group.

https://www.wowhead.com/spell=51120/tinnitus

### Steps to reproduce the problem

1. `.add 29529`
2. `.learn 51302`
3. `.setskill 165 450`
4. Use Drums, see if debuff applies

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5cf7d3d198f678b95f2d28de27350707fa656845

### Operating system

Windows 10

**Comment by balleny** [comment]
Not sure about that source. Exactly one comment further down, we see a comment stating on a later patch (3.0.1 vs 2.4.3 that this debuff is not getting applied.
https://www.wowhead.com/spell=51120/tinnitus#comments:id=381993
> This debuff currently doesn't exist/activate on beta. At least it didn't when I wasn't in a party.

Looking at
https://wowpedia.fandom.com/wiki/World_of_Warcraft:_Burning_Crusade_Classic

and the comments here
https://www.wowhead.com/wotlk/item=29528/drums-of-war#comments
https://www.wowhead.com/wotlk/item=29529/drums-of-battle#comments

And the added drums for TBC Classic (which arent part of our client!)
https://www.wowhead.com/wotlk/item=185848/greater-drums-of-battle#comments
https://www.wowhead.com/wotlk/item=185852/greater-drums-of-war

as well as the wiki
https://wowwiki-archive.fandom.com/wiki/Drums_of_Battle
https://wowwiki-archive.fandom.com/wiki/Drums_of_War

indicate that the debuff wasnt a thing in original TBC AND Wotlk. Only the on-use CD of 2 mins applied.
(this is also what I recall from playing it a decade ago).

Any chance you have a video from 15 years ago showing the debuff being applied, e.g. during pre-patch (hence people still level 70 and used to drum)?

**Comment by UltraNix** [comment]
https://dotesports.com/wow/news/blizzard-adds-tinnitus-debuff-to-leatherworking-drums-in-wow-burning-crusade-classic
`While the Tinnitus debuff is a part of WoW history, it wasn’t added to the game until Patch 3.0 when Wrath of the Lich King was released, making it a significant change to TBC Classic.`

**Comment by balleny** [comment]
> https://dotesports.com/wow/news/blizzard-adds-tinnitus-debuff-to-leatherworking-drums-in-wow-burning-crusade-classic `While the Tinnitus debuff is a part of WoW history, it wasn’t added to the game until Patch 3.0 when Wrath of the Lich King was released, making it a significant change to TBC Classic.`

seems fine. I was mostly trying to verify, cause the patch notes for wrath did not list this change at all. at least I havent found them in the early patches
