### ISSUE TITLE
[Slave Pens] Coilfang Observer should not use Magma Splash

### ISSUE THREAD

**Issue by clovaek** [azerothcore/azerothcore-wotlk#13840]
### Current Behaviour

[Coilfang Observer](https://wowgaming.altervista.org/aowow/?npc=17938) casts [Magma Splash](https://wowgaming.altervista.org/aowow/?spell=34672)

### Expected Blizzlike Behaviour

[Coilfang Observer](https://wowgaming.altervista.org/aowow/?npc=17938) should not cast [Magma Splash](https://wowgaming.altervista.org/aowow/?spell=34672)

### Source

wowhead:
https://www.wowhead.com/wotlk/npc=17938/coilfang-observer#abilities;mode:normal

### Steps to reproduce the problem

.go creature 52353
wait until it uses magma splash on the player

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=17938
https://www.wowhead.com/wotlk/npc=17938/coilfang-observer
https://wowgaming.altervista.org/aowow/?spell=34672
https://www.wowhead.com/wotlk/spell=34672/magma-splash

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2ad56371130ab7e9a96f2a92b167a6eeb895e44f

### Operating system

Ubuntu 20.04

**Comment by UltraNix** [comment]
@clovaek 
https://www.wowhead.com/wotlk/spell=32191/heavy-dynamite
This spell is used by this NPC. And this spell triggers Magma Splash.

**Comment by UltraNix** [comment]
Not a bug.
