### ISSUE TITLE
[Slave Pens] Quagmirran should turn towards the taunter during acid spray

### ISSUE THREAD

**Issue by clovaek** [azerothcore/azerothcore-wotlk#13841]
### Current Behaviour

[Quagmirran](https://wowgaming.altervista.org/aowow/?npc=17942)'s [Acid Spray](https://wowgaming.altervista.org/aowow/?spell=38153) will target the taunter after being taunted, but his body will still point towards the old target

### Expected Blizzlike Behaviour

When [Quagmirran](https://wowgaming.altervista.org/aowow/?npc=17942) is taunted during [Acid Spray](https://wowgaming.altervista.org/aowow/?spell=38153), his body should point towards the taunter

### Source

tbc classic:
https://youtu.be/N4k1Malqmi0?t=1438

### Steps to reproduce the problem

with multiple partymembers:
.go 80260
wait for him to cast acid spray
taunt it during acid spray when it doesn't aim for the taunter

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=17942
https://www.wowhead.com/wotlk/npc=17942/quagmirran
https://wowgaming.altervista.org/aowow/?spell=38153

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2ad56371130ab7e9a96f2a92b167a6eeb895e44f

### Operating system

Ubuntu 20.04

**Comment by Gultask** [comment]
@clovaek You can get the correct AC hash used in Chromiecraft from here: https://github.com/chromiecraft/azerothcore-wotlk

**Comment by clovaek** [comment]
@Gultask woops. i was using the one from the CC github i think?

**Comment by Gultask** [comment]
Yup, it's no big deal, don't worry ^^
