### ISSUE TITLE
DB local error

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#13851]
### Current Behaviour

quest 3121 zhCN error
creature_questender quest 3121 npc id= 36208 not id=3216

### Expected Blizzlike Behaviour

Correct localization description

### Source

DELETE FROM `quest_template_locale` WHERE `locale`='zhCN' AND `ID`= 3121;
INSERT INTO `quest_template_locale` (`ID`, `locale`, `Title`, `Details`, `Objectives`, `EndText`, `CompletedText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `VerifiedBuild`) VALUES (3121, 'zhCN', '奇怪的要求', '在莫沙彻营地北边拉瑞斯小亭的夏拉什·火刃有我所需要的东西！他调配出了一种混合物，我需要用它来……好吧，你以后会知道的。$B$B快点出发，快点出发，去找夏拉什。拿着这个东西，这是一颗皱缩的徽记，我答应夏拉什用此来交换草药。这是某个可怜侏儒的徽记，我在森林里撞见了他，然后就……我敢说夏拉什会很高兴得到这个东西的。$B$B你可以在菲拉斯里找到夏拉什。', '将皱缩的头颅交给菲拉斯的夏拉什·火刃。', '', '', '', '', '', '', 0);

### Steps to reproduce the problem

1.quest add 3121
2.go cr 3415

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/2ae3f40847a6c439c6c1ca1c2361b52979e06f5c

### Operating system

windows 10

**Comment by Nefertumm** [comment]
@ZhengPeiRu21 could you check this?

**Comment by yuanf225** [comment]
https://www.wowhead.com/wotlk/quest=3121/a-strange-request
see here

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21 could you check this?

Sorry, I missed this ping earlier. I will take a look.

**Comment by w5860363** [comment]
> https://www.wowhead.com/wotlk/quest=3121/a-strange-request 看这里
creature_questender quest 3121 npc id=36208
