### ISSUE TITLE
Error message-About spell_script_names

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#13858]
### Current Behaviour

_SpellScript::_Validate: Spell `52285` did not pass Validate() function of script `spell_dk_will_of_the_necropolis` - script will not be added to the spell
_SpellScript::_Validate: Spell `52286` did not pass Validate() function of script `spell_dk_will_of_the_necropolis` - script will not be added to the spell

### Expected Blizzlike Behaviour

NA

### Steps to reproduce the problem

start the world

### AC rev. hash/commit

[1c35d8c](https://github.com/tbcstar/azerothcore-wotlk/commit/1c35d8ca00f5effae1b41c2f5a0e9fdd09fb229d)

### Operating system

 Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)

### Custom changes or Modules

[mod-eluna](https://github.com/azerothcore/mod-eluna)

**Comment by Kitzunu** [comment]
Im sure it is something on your end, otherwise the CI would fail on Github. This error is not skipped in CI build

**Comment by yuanf225** [comment]
okay,
