### ISSUE TITLE
Druid‘s  fly quest.  The  item 32364   can't  get.

### ISSUE THREAD

**Issue by rushpixy** [azerothcore/azerothcore-wotlk#13854]
### Current Behaviour

23002 npc is error.

### Expected Blizzlike Behaviour

get item item 32364

### Steps to reproduce the problem

.quest add 10994
.go xyz 3723.1184  -3995.0283  95.52347

### AC rev. hash/commit

AzerothCore rev. 5cf7d3d198f6 2022-11-13 18:41:10 -0300 (master branch) (Unix, Release, Static)

### Operating system

debian

**Comment by Kitzunu** [comment]
Add commit

**Comment by rushpixy** [comment]
please reopen

**Comment by rushpixy** [comment]
Druid can't finish flying quest.
