### ISSUE TITLE
VS release error

### ISSUE THREAD

**Issue by czz3288067** [azerothcore/azerothcore-wotlk#1386]
6>D:\AZ\azerothcore-wotlk\src\server\game\Entities\Creature\CreatureGroups.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss

13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
13>  WheatyExceptionReport.cpp
9>  instance_magisters_terrace.cpp
13>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file D:\AZ\azerothcore-wotlk\src\common\Debugging\WheatyExceptionReport.cpp)
13>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file D:\AZ\azerothcore-wotlk\src\common\Debugging\WheatyExceptionReport.cpp)
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(112): error C2001: newline in constant
9>  boss_selin_fireheart.cpp
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(113): error C2059: syntax error: 'ACE_Singleton<Log,ACE_Thread_Mutex>::instance'
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(113): error C2001: newline in constant
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(114): error C2143: syntax error: missing ')' before ';'
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(116): error C2001: newline in constant
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(117): error C2059: syntax error: 'ACE_Singleton<Log,ACE_Thread_Mutex>::instance'
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(117): error C2001: newline in constant
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(118): error C2143: syntax error: missing ')' before ';'
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(120): error C2001: newline in constant
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(121): error C2059: syntax error: 'ACE_Singleton<Log,ACE_Thread_Mutex>::instance'
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(121): error C2001: newline in constant
9>  boss_vexallus.cpp
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(122): error C2001: newline in constant
9>  instance_uldaman.cpp
13>D:\AZ\azerothcore-wotlk\src\server\authserver\Main.cpp(123): error C2143: syntax error: missing ')' before ';'

6>d:\az\azerothcore-wotlk\src\server\game\server\worldsocket.cpp(724): warning C4715: 'WorldSocket::ProcessIncoming': not all control paths return a value

14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
14>  WheatyExceptionReport.cpp
14>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file D:\AZ\azerothcore-wotlk\src\common\Debugging\WheatyExceptionReport.cpp)
14>C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared (compiling source file D:\AZ\azerothcore-wotlk\src\common\Debugging\WheatyExceptionReport.cpp)
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(121): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(122): error C2059: syntax error: 'ACE_Singleton<Log,ACE_Thread_Mutex>::instance'
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(122): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(123): error C2143: syntax error: missing ')' before ';'
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(125): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(126): error C2059: syntax error: 'ACE_Singleton<Log,ACE_Thread_Mutex>::instance'
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(126): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(127): error C2143: syntax error: missing ')' before ';'
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(129): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(130): error C2059: syntax error: 'ACE_Singleton<Log,ACE_Thread_Mutex>::instance'
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(130): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(131): error C2001: newline in constant
14>D:\AZ\azerothcore-wotlk\src\server\worldserver\Master.cpp(132): error C2143: syntax error: missing ')' before ';'
15>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
15>  Building Custom Rule D:/AZ/azerothcore-wotlk/CMakeLists.txt
15>  CMake does not need to re-run because D:/AZ/build/CMakeFiles/generate.stamp is up-to-date.
========== Build: 13 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by Winfidonarleyan** [comment]
@czz3288067 Please add In your issue:
1. BRANCH(ES):
2. AC HASH/COMMIT:
3. OPERATING SYSTEM: (Maybee win 8.1?)
4. MODULES:
5. OTHER CUSTOMIZATIONS:

**Comment by czz3288067** [comment]
BRANCH:azerothcore-wotlk（no change）
AC HASH/COMMIT:
OPERATING SYSTEM: win7 x64
MODULES:none
OTHER CUSTOMIZATIONS:none

**Comment by Winfidonarleyan** [comment]
Need `AC HASH/COMMIT:`

**Comment by czz3288067** [comment]
Author: AzerothCoreBot <azerothcorebot@gmail.com>  2019-01-30 06:25:54
Committer: AzerothCoreBot <azerothcorebot@gmail.com>  2019-01-30 06:25:54
Parent: d16c17c044c2b9acb6c61313ae775b7ba8bdde2e (feat(conditions): prevent adding bad contitions + align enums with TC (#1381))
Child:  4cd25ed0cacadd03b300d3d66fb66c24d8d96e4e ([Core / Spell] Fixed Amplify Damage)
Child:  0f67f9d5f0956bf82d5d6842fdee68f6f302a5d3 (Merge branch 'master' into staging)
Branches: master, remotes/origin/master, remotes/origin/staging, remotes/origin/talamortis-patch-1
Follows: v1.0.2
Precedes: 

SHA1 ID:fc1fad4e32fedd486a8fe8ca30d2f8c3040b6d55

**Comment by czz3288067** [comment]
BOOST:boost_1_66_0-msvc-14.1-64
CMAKE:cmake-3.8.2-win64-x64
GIT:Git-2.20.1-64-bit
MYSQL:mysql-installer-community-5.6.43.0
OPENSSL:Win64OpenSSL-1_1_1a

**Comment by poszer** [comment]
Download this version of OpenSSL : 
[Click here](http://slproweb.com/download/Win64OpenSSL-1_0_2q.exe)

**Comment by talamortis** [comment]
you have the wrong version of OpenSSL. please look in the requirements to make sure you have all the correct stuff installed to configure AC before opening an issue.

**Comment by BarbzYHOOL** [comment]
Why do you guys tell him to use openssl 1.0.2??? Viste and Nefertum fixed openssl 1.1 on windows

**Comment by BarbzYHOOL** [comment]
Maybe it's still bugged

**Comment by FrancescoBorzi** [comment]
@Viste @Nefertumm can you please have a look at this?

**Comment by BarbzYHOOL** [comment]
at least it's not related to openssl, right? @czz3288067 you still use open ssl 1.1 right?

**Comment by czz3288067** [comment]
@BarbzYHOOL Yes, i still use Win64OpenSSL-1_1_1a.

**Comment by Viste** [comment]
@czz3288067 i know about 2 bugs in pr #1232 and for make fix to #1232 i need time related PR from staging branch,

**Comment by czz3288067** [comment]
@Viste OK，thank you!

**Comment by BarbzYHOOL** [comment]
Ok so openssl is detected then

**Comment by heijing-iw7** [comment]
> I reinstalled the system and VS2017, solved most of the problems, except this
> 
> 6>d:\az\azerothcore-wotlk\src\server\game\server\worldsocket.cpp(724): warning C4715: 'WorldSocket::ProcessIncoming': not all control paths return a value
> 
> Same as this:[VS] Compilation warning #1296

would pls tell me how to fix the most of the problems, I most got the same issues as you
