### ISSUE TITLE
[Netherstorm] Ethereum Jailor spawned too often

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#13877]
### Current Behaviour

There seem to be approx 20 Ethereum Jailors spawned in Netherstorm

### Expected Blizzlike Behaviour

Judging by the comments in wowhead, there should be far fewer jailors (e.g. 2) up at any time.

### Source

https://www.wowhead.com/wotlk/npc=23008/ethereum-jailor#comments

### Steps to reproduce the problem

.tele ultris
fly around the manaforge

### AC rev. hash/commit

AzerothCore rev. ece089dad721 2022-11-16 04:32:49 +0000 (master branch) (Unix, Debug, Static)

### Operating system

Ubuntu

### Custom changes or Modules

ChromieCraft PTR

**Comment by Santaria94** [comment]
Confirmed. The comments state that this is a random spawn that can spawn in place of one of the other NPCs in the area.

>By Random0214 (2,350 – 1·10·23) on 2008/02/07 (Patch 2.3.3)		
The reason you cannot find any after looking for them for hours is that, if there are no enemies dead, then nothing can respawn. If everything spawned isn't a jailor, kill some and he may spawn in their place. This would be what FallingDown did, but maybe successfully.

>30549 on 2007/10/23 (Patch 2.2.3)
There might be a single and a global cooldown on the repop timers for these guys. As example: In TBC, fishing nodes in Nagrand and Terokkar have a global cooldown. Meaning there cant be say, more than 6 nodes in one area at one time. But there can be 3 different types of nodes that spawn in the exact same place. And that particular spawn point has a single cooldown on its own (will always repop in 45 min) but the one type has a longer cooldown (repops in 1:30 min). So you may not see more than 2 at a time, but there will be more "in Queue" to pop once there is room for them.

**Comment by Gultask** [comment]
I posted a PR to pool them. Proving that they share spawns will take more serious investigation and a reconstruction of the area.
