### ISSUE TITLE
[Nagrand] Quest - A Visit With the Greatmother

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13886]
### Current Behaviour

1. "The Totem of Kar'dash" + "Message to Garadar" unlock quest "A Visit With the Greatmother" without "Forge Camp: Annihilated"
2. "Forge Camp: Annihilated" unlock quest "A Visit With the Greatmother" without "The Totem of Kar'dash" + "Message to Garadar"

### Expected Blizzlike Behaviour

All three quests are required to unlock quest "A Visit With the Greatmother"

### Source

https://www.wowhead.com/quest=10044

>robtm on 2007/01/30 (Patch 2.0.6)
Murkblood Invaders isn't required. I got this quest without having done that one. This chain was available to me after the Altruis chain, so that one is a confirmed requirement.

>Rasore on 2007/02/04 (Patch 2.0.6)
Confirmed you need the escort quest. I've just finished all the other pre-requisites and was not offered this quest. The quest is called the "totem of Kar'dash" (there is an alliance version too): http://www.wowhead.com/?quest=9868 Confirmed that once I had done this quest, I was able to start this chain.

>Avilister on 2007/03/23 (Patch 2.0.10)
You must complete all of the Blademaster's quests to get this. All the way through Message to Garadar (http://www.wowhead.com/?quest=9934)

>Wyr3d on 2015/08/12 (Patch 6.2.1)
For the record, I made sure to complete The Totem of Kar'dash before the other quest lines, and it did not become available. Blademaster is done, still not available. Robtm states Murkblood isn't required since he completed it without doing those, that means the prerequisites must be the Atruis chain (prolly the final quest) and the escort quest. EDIT: It was Forge Camp: Annihilated

### Steps to reproduce the problem

.go cr 63870
.quest add 9868
.quest add 9934
.quest comp 9868
.quest comp 9934
Check if the quest "A Visit With the Greatmother" is available

.quest rem 9868
.quest rem 9934
.quest add 10011
.quest comp 10011
.go quest ender 10011
.go cr 63870
Check if the quest "A Visit With the Greatmother" is available

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/afebbb816cb7fe84fbec0c46beb532b8b5215dbe

### Operating system

Windows 10 x64

**Comment by Gultask** [comment]
Nice find!
