### ISSUE TITLE
[Nagrand] Quest - Patience and understanding

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13897]
### Current Behaviour

Sal'salabim becomes an enemy after right-clicking on it, no gossip is shown. It is also possible to right-click on it when it is evading, in which case it forgets its starting position the next time it evades. If you repeat this, then you can run away with him to another location, which will make it difficult for other players to complete the quest further.

Also, when he becomes an enemy, some phrase in the demon language is missing.

### Expected Blizzlike Behaviour

There must be a special string that will start the fight with him.
https://youtu.be/Ritc7LZk_4k?t=113

https://www.wowhead.com/npc=18584
>Arualiaa (2,047 – 11·15) 18.12.2017 (7.3.2)		
He speaks in fake Demonic, that is: it doesn't translate. Doing his quest with a demon hunter still has him speak in gibberish, which was pretty disappointing.

### Source

https://youtu.be/Ritc7LZk_4k?t=113
https://www.wowhead.com/npc=18584

### Steps to reproduce the problem

.go cr 66742
.quest add 10004
Right click and run away
When he stops chasing you, chase him down and right-click.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/afebbb816cb7fe84fbec0c46beb532b8b5215dbe

### Operating system

Windows 10 x64

**Comment by v-mstrs** [comment]
Completed as of https://github.com/azerothcore/azerothcore-wotlk/pull/15505
