### ISSUE TITLE
[Nagrand] The Ring of Blood: Skra'gath

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13907]
### Current Behaviour

1. Doesn't gain magic reduction after taking the first magic damage.
2. Does not use Piercing Shadow. Also probably not immune to interruption.
3. Doesn't use Dark Shriek.
4. Doesn't remove threat after using Shadow Burst.

### Expected Blizzlike Behaviour

1. After taking the first magic damage, must reduce damage by 75% to this magic school. Has the right abilities for it.
https://www.wowhead.com/tbc/spell=34331/damage-reduction-arcane
https://www.wowhead.com/tbc/spell=34333/damage-reduction-fire
https://www.wowhead.com/tbc/spell=34334/damage-reduction-frost
https://www.wowhead.com/tbc/spell=34336/damage-reduction-holy
https://www.wowhead.com/tbc/spell=34335/damage-reduction-nature
https://www.wowhead.com/tbc/spell=34338/damage-reduction-shadow

https://www.wowhead.com/tbc/npc=18401/
>By DarkFerret (1,654 – 1·23) on 2007/04/26 (Patch 2.0.12)		
Resistant to the first school of magic used against him.

The Death Knight deals Frost Damage and Skra'gath gets buff.
https://youtu.be/ivPcGMH-mbg?t=20

2. 0:27 - uses "Piercing Shadow" with interrupt immunity
https://youtu.be/ivPcGMH-mbg?t=25

3. I learned this ability in the game. The visual effect is like a thunderclap. In the video you can see:
https://youtu.be/ivPcGMH-mbg?t=33 - 0:35
https://youtu.be/ivPcGMH-mbg?t=49 - 0:50
https://youtu.be/ivPcGMH-mbg?t=60 - 1:01

4. This is stated in the ability tooltip itself, also a comment from wowhead:

https://www.wowhead.com/quest=9972/the-ring-of-blood-skragath#comments
>By 117913 (2,830 – 1·5·29) on 2009/03/24 (Patch 3.0.9)
He does a agro swap/drop every so often. Usually after he does the AOE attack, he will randomly swap the lead agro with someone else on the list. It is very hard to make up that agro at this level without true taunts. Best bet, if the healer gets on the top of the list just have them run around until he does the agro swap around. Healer might want to position themselves up on the hills overlooking the circle. This way the boss has to run all the way around the wooden spikes, then the healer can jump down into the pit, so the boss then has to run all the way around again. Hopefully enough time will have passed that he will swap agro again.

https://www.wowhead.com/tbc/spell=32324/shadow-burst
>Let forth a burst of energy knocking all nearby enemies back, dealing 160 to 240 Shadow damage and **removing all threat**.

### Source

https://www.wowhead.com/tbc/npc=18401/
https://www.wowhead.com/quest=9972/the-ring-of-blood-skragath#comments
https://youtu.be/ivPcGMH-mbg

### Steps to reproduce the problem

.go cr 66480
.quest add 9972

### Extra Notes

Also, this and other guys from this quest line are not immune to CC. However, comments about these bosses being impossible or very hard to kill solo hint that all bosses should be immune to all CC types.

https://www.wowhead.com/tbc/npc=18398
https://www.wowhead.com/tbc/npc=18399
https://www.wowhead.com/tbc/npc=18400
https://www.wowhead.com/tbc/npc=18401
https://www.wowhead.com/tbc/npc=18402

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/afebbb816cb7fe84fbec0c46beb532b8b5215dbe

### Operating system

Windows 10 x64

**Comment by Gultask** [comment]
Correct spell for Eviscerate is 15962, the one which was being used was 15691, lol
The weird part is that 15962 doesn't do that much more damage...
