### ISSUE TITLE
[QUEST] dragonmaw race: wing commander ichman - texture bug

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1390]
DESCRIPTION:

NPC "wing commander ichman" go in texture during the event.

EXPECTED BLIZZLIKE BEHAVIOUR:

NPC "wing commander ichman" don't go in texture during the event.

CURRENT BEHAVIOUR:

During the flying race ichman go in texture inside the mountain as seen in the video.

https://youtu.be/mc41JwcYQZE

STEPS TO REPRODUCE THE PROBLEM:

- .quest add 11013 
- .quest add 10870
- .go creature 77645 and complete quest
- .go creature 28402 and complete quest
- .go creature 78787 take and complete quest "Earning Your Wings..."
- relog becouse we have by-pass questline and npc become enemies
- .add quest 11068 and .quest complete 11068
- take the quest "wing commander ichman" from ichman and follow him in the race event 

https://wowgaming.altervista.org/aowow/?quest=11069  ---> link quest
https://wowgaming.altervista.org/aowow/?npc=23345 ---> link NPC

BRANCH(ES):
staging

AC HASH/COMMIT:
commit 987095e

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by LukasVolgger** [comment]
Confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4

**Comment by FrancescoBorzi** [comment]
@LukasVolgger thanks for doing some bug triage, for this and the other issues.

**Comment by heyitsbench** [comment]
Almost certainly resolved with https://github.com/azerothcore/azerothcore-wotlk/commit/e34ce755c8f1c809116298f84b8f2686157a2d77.
