### ISSUE TITLE
[Zangarmarsh] NPC - Marshfang Ripper

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13926]
### Current Behaviour

1. At the beginning of the fight, he has 100% mana.
2. Has passive mana regeneration.
3. Does not use "Arcane Explosion" (unknown ID)

### Expected Blizzlike Behaviour

https://www.wowhead.com/npc=18130/marshfang-ripper

>By 49198 (472 – 2·4) on 2007/06/07 (Patch 2.1.1)		
**Although these guys don't have mana to begin with**, they can still be mana tapped by Blood Elves (because of their mana drain) to get your charges up

>By 77947 (1,424 – 1·10) on 2008/04/22 (Patch 2.4.1)		
They also definitely have an ability to use Arcane Explosion, even though it is not listed as one of the abilities here.

https://youtu.be/mVuYOEBrFiA?t=36 - 0:38 you can see the cast of "Arcane Explosion"

![111](https://user-images.githubusercontent.com/32459796/203727125-d5d11cd1-d3d9-4114-96ab-830831f1b6ae.jpg)

### Source

https://www.wowhead.com/npc=18130/marshfang-ripper
https://youtu.be/mVuYOEBrFiA?t=36

### Steps to reproduce the problem

.go cr 64622

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4a2964e10a03a2b6ba2077e6b362b8a6ba6675fb

### Operating system

Windows 10 x64

**Comment by Nyeriah** [comment]
![image](https://user-images.githubusercontent.com/47818697/204119451-07a839a1-9207-4aa2-bc26-9386bf1fb66a.png)
