### ISSUE TITLE
Shadowlord Deathwall

### ISSUE THREAD

**Issue by Asherdoom** [azerothcore/azerothcore-wotlk#1392]
Shadowlord Deathwall not flying and visual bugs

##### SMALL DESCRIPTION:
Shadowlord Deathwall is situated in shadowmoon valley in temple of karabor (black temple) ramp on the RIGHT side is not flying but he MUST fly because he is involved in the following quest:
NPC INFO: https://wowwiki.fandom.com/wiki/Shadowlord_Deathwail
QUEST: https://wowwiki.fandom.com/wiki/Quest:The_Ata%27mal_Terrace

CREATURE ID: 20699 (also present in the screenshots are the npc infos)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Flying on top the part of karabor temple patrolling the area,

##### CURRENT BEHAVIOUR:
as per screenshot hes static and doing nothing.
![screenshot_013119_141651](https://user-images.githubusercontent.com/16918614/52072089-11ac3800-2563-11e9-8e8c-fa43ea7bc1e2.jpeg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go shadowmoon valley
2. Gt to Ata'mal terrace
3. You will just see npc static

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
commit c60d1ee

##### OPERATING SYSTEM:
Linux

**Comment by poszer** [comment]
Missing waypoint
