### ISSUE TITLE
[Zangarmarsh] NPC - Bloodscale Enchantress

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13930]
### Current Behaviour

They only use "Arcane Missiles"

### Expected Blizzlike Behaviour

Also they should use Freezing Circle and Ice Barrier

https://www.wowhead.com/tbc/npc=18088
>By 6934 (35,600 – 13·116·150) on 2006/12/07 (Patch 2.0.1)		
Wow, watch out for these. They're non elites but they'll cast "frostbite" on you. This spell causes 2200+ damage and roots you in place

>By wx3yjm74 on 2008/01/28 (Patch 2.3.3)		
Subject: "Re: Bloodscale Enchantress"
They have some kind of freezing circle attack which seems to do 2200 frost damage and pins you to the ground for 12 seconds. It's really easy to spot though, as it has a casting time, then some ice cubes around the enchantress and a blue circle under you will appear and you have well enough time to simply walk away from it.
Furthermore she has arcane missiles which hit me for 158 arcane damage, times five (790 total for me).

>By 83214 (16,604 – 5·30·128) on 2008/03/03 (Patch 2.3.3)		
In addition to the spell above, it can use Arcane Missiles, which does roughly 170 arcane damage per second for 5 seconds, and Ice Barrier.

https://wowwiki-archive.fandom.com/wiki/Bloodscale_Enchantress
>Freezing Circle: While the Enchantress is frozen or rooted resorting to using Arcane Missiles as her primary attack, she will uncommonly cast a timed spell called Freezing Circle. A blue circle marks the spot where the spell hits, much like Meteor in Diablo II. Ice blocks will form around the circle slowly, be sure to get out of the targeted area once all six blocks of ice are completed since it deals around 2k to 3k damage and can crit for 5k further freezing you in place for 12 seconds in the area.

Important comment.  Ice barrier before they begin casting Freezing circle
https://www.wowhead.com/spell=34787/freezing-circle
>170459 on 2008/07/06 (Patch 2.4.1)
They put up an ice barrier before they begin casting it, so unless you can do enough damage to break the barrier, your earth shock/pummel/kick won't interrupt it.

### Source

https://www.wowhead.com/tbc/npc=18088
https://www.wowhead.com/spell=34787/freezing-circle
https://wowwiki-archive.fandom.com/wiki/Bloodscale_Enchantress

### Steps to reproduce the problem

.go cr 63990

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4a2964e10a03a2b6ba2077e6b362b8a6ba6675fb

### Operating system

Windows 10 x64

**Comment by BeefSteaker** [comment]
Confirmed. 
they do have Freezing circle in their smart ai, but are missing Ice barrier
![image](https://user-images.githubusercontent.com/11332559/203814839-2903f189-a9bc-4650-92c6-7d2ca7066ee3.png)
