### ISSUE TITLE
[Zangarmarsh] NPC - Rajis Fyashe

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13931]
### Current Behaviour

1. Freezing Circle does not work. She casts it but nothing happens.
2. Not immune to CC

### Expected Blizzlike Behaviour

1. This ability is also used by some other NPCs. Description from the article.
https://wowwiki-archive.fandom.com/wiki/Bloodscale_Enchantress
>Freezing Circle: While the Enchantress is frozen or rooted resorting to using Arcane Missiles as her primary attack, she will uncommonly cast a timed spell called Freezing Circle. A blue circle marks the spot where the spell hits, much like Meteor in Diablo II. Ice blocks will form around the circle slowly, be sure to get out of the targeted area once all six blocks of ice are completed since it deals around 2k to 3k damage and can crit for 5k further freezing you in place for 12 seconds in the area.

Video:
https://youtu.be/w58-16Q4CEc?t=50

2. I found comments like this about CC immunities, but maybe there should be more types
>By moptop (1,242 – 9·14) on 2007/01/19 (Patch 2.0.5)		
Same as Rajah, unable to be snared/rooted. Although easier than Rajh, still fairly hard to solo.

>By 83214 (16,604 – 5·30·128) on 2008/03/01 (Patch 2.3.3)		
Immune to Mind Control.

### Source

https://www.wowhead.com/npc=18044
https://youtu.be/w58-16Q4CEc?t=50

### Steps to reproduce the problem

.go cr 63801

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4a2964e10a03a2b6ba2077e6b362b8a6ba6675fb

### Operating system

Windows 10 x64

**Comment by BeefSteaker** [comment]
Confrimed, an animation on the ground happens (although not the full animation for freezing circle) but nothing else
