### ISSUE TITLE
[Blade's Edge Mountains] NPC - Bladewing Bloodletter

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13943]
### Current Behaviour

Only use Poison Spit if he attack first and don't repeat it
It also seems to have problems with "Blood Leech", does not always use it

### Expected Blizzlike Behaviour

https://youtu.be/FW8RC2gotn4?t=91 - 1:32 He casts Poison Spit and heals himself a bit after that (more than 50% health). Repeats Poison Spit when the debuff expires.
https://www.wowhead.com/tbc/spell=37839/poison-spit
https://www.wowhead.com/tbc/spell=37838/blood-leech

### Source

https://www.wowhead.com/tbc/npc=21033/bladewing-bloodletter
https://youtu.be/FW8RC2gotn4?t=91

### Steps to reproduce the problem

.go cr 73844

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0

### Operating system

Windows 10 x64

**Comment by BeefSteaker** [comment]
confirmed, poison spit is scripted as on aggro, and blood leech could be to do with being dropped 40% to 20% qucikly
![image](https://user-images.githubusercontent.com/11332559/204136001-ca5cad54-74cb-47b2-bd47-c65c9762f70c.png)
