### ISSUE TITLE
In the Trial of the champion, the difficulty of dungeons is 5 people in the normal mode, and the non gm mode enters the copy, and the last drop of blood fights with me. This is a bug, see the picture

### ISSUE THREAD

**Issue by ssdphp** [azerothcore/azerothcore-wotlk#13941]
### Current Behaviour

第一步：地下城难度为5人普通
第二步：第一阶段的3个boss杀完后，剩下一个boss剩一滴血杀我，不脱离战斗。
![QQ图片20221126022623](https://user-images.githubusercontent.com/16387049/204039322-389bc08b-e3b0-4825-a2b4-2209485a68a5.png)

### Expected Blizzlike Behaviour

boss脱离战斗，不影响继续下一个阶段

### Steps to reproduce the problem

第一步：非gm模式进入地下城难度为5人普通的冠军的试炼（Trial of the champion）
第二步：第一阶段的3个boss杀完后，剩下一个boss剩一滴血杀我，不脱离战斗。
![QQ图片20221126022623](https://user-images.githubusercontent.com/16387049/204039322-389bc08b-e3b0-4825-a2b4-2209485a68a5.png)

### AC rev. hash/commit

无

### Operating system

Windows 10 x64

### Custom changes or Modules

无

**Comment by heyitsbench** [comment]
Please add your revision hash/commit from `.server debug`.

**Comment by Nyeriah** [comment]
Please use English when reporting issues. We will have difficulty understanding what the problem is as most of our developers don’t speak Chinese.
