### ISSUE TITLE
Zeppelin "The Cloudkisser" losing control console

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/azerothcore-wotlk#1394]
##### SMALL DESCRIPTION:
The zeppelin "The Cloudkisser", which moves between Tirisfal Glades and Vengeance Landing, loses it's control console.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The control console should stay on the zeppelin.

##### CURRENT BEHAVIOUR:
The control consol falls down and then floats through the air while the zeppelin moves.

##### STEPS TO REPRODUCE THE PROBLEM:
- ```.go 1988.7 -6086.86 13.3416 571```
- sometimes the console is visible in the grass while the zeppelin is docked:
 ![1](https://user-images.githubusercontent.com/38475780/52089928-295ddd80-25b0-11e9-8fe8-b5df126b9e56.jpg)
- it is missing on the zeppelin:
  ![2](https://user-images.githubusercontent.com/38475780/52089983-4a263300-25b0-11e9-94a4-25ec3222b814.jpg)
- when the zeppelin is moving, it floats through the air:
 ![3](https://user-images.githubusercontent.com/38475780/52090008-65913e00-25b0-11e9-96ad-f791689fe6ef.jpg)

##### EXTRA NOTES:
None

##### BRANCH(ES):
Master

##### AC HASH/COMMIT:
fc1fad4e32fedd486a8fe8ca30d2f8c3040b6d55

##### OPERATING SYSTEM:
Ubuntu 16.04

##### MODULES:
https://github.com/azerothcore/mod-vas-autobalance
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster

##### OTHER CUSTOMIZATIONS:
None

**Comment by BarbzYHOOL** [comment]
:rofl:

**Comment by BarbzYHOOL** [comment]
What does it do @pklloveyou?

**Comment by Stoabrogga** [comment]
Thanks for the tip @pklloveyou . I did not know that the console was an NPC. Fixed it through this statement:
```UPDATE `creature` SET `position_x` = 10.5731, `position_y` = -7.65137, `position_z` = -16.6839, `orientation` = 0 WHERE `guid` = 142823;``` (see PR #1400).

**Comment by BarbzYHOOL** [comment]
why is it a creature?

**Comment by BarbzYHOOL** [comment]
but why? shouldn't we change it?

**Comment by BarbzYHOOL** [comment]
same on wowhead, just weird ^^
