### ISSUE TITLE
The elevator in the world not work

### ISSUE THREAD

**Issue by ide1234000** [azerothcore/azerothcore-wotlk#1396]
The elevator in the world not work

##### SMALL DESCRIPTION:

The elevator cross through character and character stays on the ground

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The character can follow the elevator movement

##### CURRENT BEHAVIOUR:

The elevator cannot carry any passengers...

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go 4176.14 5282.05 26.6939 571
2. Try to take the elevator in front of you
3. (Maybe every elevator in the world can't work)

##### BRANCH(ES):

master

##### AC HASH/COMMIT: 

c60d1ee

##### OPERATING SYSTEM:

Ubuntu 16.04 64

##### MODULES:

mod-duel-reset
mod-learn-spells

**Comment by ide1234000** [comment]
This problem also exists on Windows 10.

**Comment by Deku** [comment]
When the elevator comes from above and goes through, you have to jump to get above the gameobject,
because the gameobject doesn't go below ground height

**Comment by wetbrownsauce** [comment]
Confirmed bug on rev 89df9b9086111f478d22d34d19a830b00646191c

[Gfycat Webm of glitch 1](https://giant.gfycat.com/SpotlessYellowBrownbutterfly.webm)
[Gfycat Webm of glitch 2](https://giant.gfycat.com/SafeWealthyGuppy.webm)

**Comment by BarbzYHOOL** [comment]
hmm the screenshots show a critical issue (can't go to undercity lol)

**Comment by wetbrownsauce** [comment]
The high label said gamebreaking issues (I assume preventing access to a city is gamebreaking), and critical is reserved for crashes, lag, security, etc. /shrug

**Comment by FrancescoBorzi** [comment]
There are different levels of gamebreaking, such bug should be solved asap since it's quite annoying.

We are going to improve this label system anyway

**Comment by FrancescoBorzi** [comment]
The fix has been tested and merged to master. Please update to latest version.
