### ISSUE TITLE
[The Underbog] NPC - Hungarfen - Underbog Mushroom

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13979]
### Current Behaviour

Underbog Mushroom spills a puddle immediately. It doesn't give a debuff to the player, instead it spams a huge amount of damage. But it gives a debuff to the boss and other mushrooms, which deals damage to them

### Expected Blizzlike Behaviour

1. The Underbog Mushroom should appear small and gradually grow. After about 15-20 seconds, it explodes and leaves behind a Spore Cloud.

https://youtu.be/EYmGCbnIb4c?t=632
10:33 - Underbog Mushroom spawning
10:47-10:52 - Underbog Mushroom explodes

2. If the player is standing in Spore Cloud, they will receive the corresponding debuff that deals damage every 2 seconds. If the player does not immediately run out of the Spore Cloud, then approximately every 3 seconds receives an additional stack (maximum 5)
https://www.wowhead.com/tbc/spell=34168/spore-cloud - this spell, as I understand it, adds debuffs every 3 seconds
https://www.wowhead.com/tbc/spell=31689/spore-cloud - debuff stacks

https://youtu.be/_LRpztnnao8?t=630 - 10:30 warrior demonstrates how it works

3. I didn't find a video where the boss is standing in a cloud, but I think it's logical that his ability should not kill him

### Source

https://www.wowhead.com/tbc/npc=17770
https://www.wowhead.com/tbc/npc=17990

https://youtu.be/EYmGCbnIb4c?t=632
https://youtu.be/_LRpztnnao8?t=630

### Steps to reproduce the problem

.go cr 138367

### Extra Notes

Maybe fix it
https://github.com/TrinityCore/TrinityCore/pull/26567

Similar issue
https://github.com/azerothcore/azerothcore-wotlk/issues/13924

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0

### Operating system

Windows 10 x64

**Comment by clovaek** [comment]
This seemed to work fine after the underbog got reworked? Or atleast the mushrooms did much less damage.

Did 2 consecutive underbog runs today where spore cloud started ticking as soon as the mushroom spawned every 0.10s
Same on PTR
![image](https://user-images.githubusercontent.com/98345440/208123557-ce02f5da-53c8-4e96-931b-81345c5cb9c3.png)

**Comment by Santaria94** [comment]
> This seemed to work fine after the underbog got reworked? Or atleast the mushrooms did much less damage.
> 
> Did 2 consecutive underbog runs today where spore cloud started ticking as soon as the mushroom spawned every 0.10s Same on PTR ![image](https://user-images.githubusercontent.com/98345440/208123557-ce02f5da-53c8-4e96-931b-81345c5cb9c3.png)

The dungeon rework was only about adding spawns, waypoints, cosmetic effects, based on sniffs, if I understood Gultask's words correctly. I tested the dungeon after this rework.

**Comment by kerricsson** [comment]
Hello, yes, I can confirm this bug. Most annoying bug at dungeons at current brackets, leads to multiple drama at RDF when tank wants to skip it and other people do not want it.  
So, when developers will return from holidays, please prioritize this bug and fix it. 
Thank you in advance.
