### ISSUE TITLE
world server crash with crash log

### ISSUE THREAD

**Issue by clid951** [azerothcore/azerothcore-wotlk#13986]
### Current Behaviour

crash log:

https://gist.github.com/clid951/4e26787140372d6820686167a0f67d96

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

debian 11 x64

### Custom changes or Modules

mod-anticheat
mod-cfbg
mod-eluna
mod-individual-xp
mod-racial-trait-swap
mod-skip-dk-starting-area
mod-transmog
mod-world-chat

**Comment by acidmanifesto** [comment]
Racial trait swap module not azerothcore related. Open issue on the racial trait swap module git and we can see what modifications you have thats causing the crash.
