### ISSUE TITLE
[The Underbog] NPC - Underbog Lord - aggro radius

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13983]
### Current Behaviour

Pretty small aggro range

### Expected Blizzlike Behaviour

Should be bigger and seems to be level independent

https://www.wowhead.com/npc=17734/underbog-lord
>By enyapjm (1,716 – 6·22) on 2011/12/20 (Patch 4.3.0)		
These still have a very large agro radius, even to a level 85 character.

https://youtu.be/_LRpztnnao8?t=1735 - 28:58
https://youtu.be/EYmGCbnIb4c?t=2650 - 44:12

### Source

https://youtu.be/_LRpztnnao8?t=1735 - 28:58
https://youtu.be/EYmGCbnIb4c?t=2650 - 44:12

### Steps to reproduce the problem

.tele underbog
.go xyz 280.749817 -169.079193 36.874214

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0

### Operating system

Windows 10 x64

**Comment by Ovahlord** [comment]
This might be a case for sniffing because if even level 85 characters can get aggro'd from far away, there's either an area trigger involved or a hidden ping aura on the lords that just causes it to aggro whatever it hits

**Comment by Gultask** [comment]
No areatriggers since they patrol and no auras that can be sniffed. It's very visible here because detection ranges are calculated from exact distance, which is thus skewed for large creatures if set to the default 20y.
