### ISSUE TITLE
[Ulduar] [Assembly of Iron] boss cannot be killed normally

### ISSUE THREAD

**Issue by ssdphp** [azerothcore/azerothcore-wotlk#13985]
### Current Behaviour

According to the order of large, medium and small, kill one big, medium and two bosses normally and leave the smallest boss. Wait for the last boss to release the lightning vine skill.

### Expected Blizzlike Behaviour

The boss should fly normally, and the player should be able to kill normally

### Steps to reproduce the problem

1. Prepare a new CD for Ulduar 10/25 players
2. Select gm account to open gm mode
3. .go creature 136316 is sent to the front of the boos, and the gm mode is turned off
4. Kill the big and middle bosses and leave the smallest boss
5. Wait for the final boss to release the lightning vine skill

https://user-images.githubusercontent.com/16387049/204455472-1586495f-7a1e-4869-b153-2f26fc9a4abf.mp4

### Extra Notes

Thank you all AZ developers for your hard work

### AC rev. hash/commit

AzerothCore rev. 55957fbb6e24+ 2022-11-24 18:23:27 -0300 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1c  28 May 2019 (library: OpenSSL 1.1.0j  20 Nov 2018)
Using Boost version: 1.74.0
Using MySQL version: 50727
Using CMake version: 3.21.3
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/wlk335/build/bin/Release/data/maps. Total size: 291014951 bytes
vmaps directory located in E:/wlk335/build/bin/Release/data/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/wlk335/build/bin/Release/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna
- mod-transmog

### Operating system

Windows 10 x64

### Custom changes or Modules

none

**Comment by sxwenjie** [comment]
Well, someone could fix it. Thank you very much

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14940
