### ISSUE TITLE
[The Underbog] NPC - The Black Stalker - Levitate

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#13988]
### Current Behaviour

1. Does not move the levitation target.
2. Also, the second debuff "Suspension" doesn't seem to work correctly. Sometimes the player does not get it (it looks like he is the current target of the boss), and if he does, then the debuff timer does not work like in the video.
https://www.wowhead.com/tbc/spell=31719/suspension
3. If there are several targets, then the target of levitation can be the current target of the boss

### Expected Blizzlike Behaviour

https://youtu.be/sr6ryq4_-74?t=8618 - 2:23:40
1. The Black Stalker moves the levitation target
2. Also pay attention to the "Suspension" timer:
2:23:42 - 19 sec
2:23:43 - 9 sec
2:23:44 - 4 sec
3. I assume levitation should not be used on the boss's current target. Druid fight solo with her and does not get levitation even once for the whole fight
https://youtu.be/84EwSSiXjJ8?t=732 - 12:12

### Source

https://youtu.be/sr6ryq4_-74?t=8618 - 2:23:40
https://youtu.be/84EwSSiXjJ8?t=732 - 12:12
https://www.wowhead.com/tbc/spell=31704/levitate
https://www.wowhead.com/tbc/spell=31719/suspension

### Steps to reproduce the problem

.go cr 138323

### Extra Notes

Rework The Black Stalker (TrinityCore). Maybe fix the problems indicated in the report.
https://github.com/TrinityCore/TrinityCore/pull/28040/commits/36745618356f4742459bbe4cfbabaaa3d9e26369

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0

### Operating system

Windows 10 x64

**Comment by kerricsson** [comment]
Can confirm, did around 20 times and no levitation was casted.
