### ISSUE TITLE
[teleport bug] Thousand needles (only for Gm account)

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1398]
<DESCRIPTION:

If you fly in Thousand needles you are teleported automatically at "the waethered nook". Fly in kalimdor is reserved for gm accounts only

EXPECTED BLIZZLIKE BEHAVIOUR:

do not be teleported

CURRENT BEHAVIOUR:

be teleported

https://youtu.be/VAMPjVrBsh8  ----> video link

STEPS TO REPRODUCE THE PROBLEM:

.go -4980.1 -1644.8 -2.19 1.24 1  and fly in front of you

BRANCH(ES):
staging

AC HASH/COMMIT:
commit 987095e

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by lineagedr** [comment]
Related to the: Test of faith quest. https://youtu.be/6mfse8eBKrs?t=40

**Comment by comix1988** [comment]
> 
> 
> Related to the: Test of faith quest. https://youtu.be/6mfse8eBKrs?t=40

thank you, I did not know that quest. Sorry for wrong report
