### ISSUE TITLE
[QUEST BUG] assault by air both side (ally-horde)

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1399]
DESCRIPTION:

Both side:
The mission does not work properly, i can complete it but the ymirheim spear gun do not shoot and make really easy to complete it.

Only alliance side:
this quest is obtainable only after completing the quest "joining the assault" but here it is not like that.

EXPECTED BLIZZLIKE BEHAVIOUR:

both side:

ymirheim spear gun must attack airplane

![cattura](https://user-images.githubusercontent.com/22867608/52138044-65468080-264c-11e9-91a1-70088bf03759.PNG)

Only alliance side:

before being available "assault by air" you must complete the quest "joining the assault".

first quest : https://wowgaming.altervista.org/aowow/?quest=13341
second quest: https://wowgaming.altervista.org/aowow/?quest=13309

CURRENT BEHAVIOUR:

view description

STEPS TO REPRODUCE THE PROBLEM:

alliance: 
- .go cerature 121745 (you can see the quest "assault by air" is already available before you have complete "joining assault")
- accept quest "assault by air" and take airplane;
- you can go AFK becouse the airplane does not suffer damage;
Horde:
- .go cerature 122316
- .quest add 13340 and complete it;
- accept quest "assault by air" and take airplane;
 - you can go AFK becouse the airplane does not suffer damage;
                 
BRANCH(ES):
staging

AC HASH/COMMIT:
commit 987095e

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by comix1988** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/855

**Comment by poszer** [comment]
Closing this, duplicate. Comment on issue that is already opened if something more need to be fixed. 
https://github.com/azerothcore/azerothcore-wotlk/issues/855
Thanks
