### ISSUE TITLE
crossfaction bg

### ISSUE THREAD

**Issue by ahuraa** [AzerothCore/azerothcore-wotlk#14]
please add crossfaction bg

**Comment by boom8866** [comment]
why?
The effective for private server?

**Comment by Yehonal** [comment]
@ahuraa this is a very custom feature and could be implemented in future as a custom module installable for Azeroth Core

**Comment by ahuraa** [comment]
please add it i very very search for it and can't found

**Comment by Bodeguero** [comment]
@ahuraa I'll be checking if I can add this CFBG script and some more!

**Comment by ahuraa** [comment]
please add it why with? please add

**Comment by Yehonal** [comment]
closing this , it will be implemented as an external module in future.
