### ISSUE TITLE
A few unimplemented opcodes/commands.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#14000]
### Current Behaviour

The opcodes `MSG_MOVE_TELEPORT_CHEAT` (0x00C6), `CMSG_MOVE_CHARM_PORT_CHEAT` (0x00E0), and `CMSG_MOVE_SET_RAW_POSITION` (0x00E1) are all unimplemented and result in a "Received not allowed opcode" message in the worldserver console.

### Expected Blizzlike Behaviour

These should be implemented.
The `MSG_MOVE_TELEPORT_CHEAT` opcode might be used as a teleport within the map the player is currently in.
The `CMSG_MOVE_CHARM_PORT_CHEAT` opcode seems to be [used to teleport to a target](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/305945-cataclysm-new-console-commands-list.html), don't know if it's specific to players or creatures as well. Worth pointing out that it uses a different name on [Wowdev.wiki](https://wowdev.wiki/Opcodes), specifically `MSG_MOVE_SET_RAW_POSITION_ACK`, but it does use the 'charmport' command.
The `CMSG_MOVE_SET_RAW_POSITION` opcode may be used similarly to worldport, but not sure.

### Source

Unless a GM leaks or makes mistakes, N/A.

### Steps to reproduce the problem

1. Open `Wow.exe` with the `-console` argument.
2. Log in to a character.
3. Use the tilde (`) key to open the console once in-game.
4. Try to use any of the following commands: `port`, `charmport`, `setrawpos`.
5. Observe the lack of action and errors in the worldserver console.

### Extra Notes

This is obviously something that should only be allowed to GMs, but since the worldport command is already implemented, I figured I might as well point out these ones aren't implemented.

### AC rev. hash/commit

11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Kitzunu** [comment]
Make one report per opcode, otherwise it will just be harder to keep track of the issue. Thanks
