### ISSUE TITLE
Archmage Leryda missing text

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14005]
### Current Behaviour

Upon attempting to interact with [Archmage Leryda](https://wowgaming.altervista.org/aowow/?npc=18253), nothing will happen.

### Expected Blizzlike Behaviour

She should [talk to you](https://user-images.githubusercontent.com/38561765/204109645-7f43de6a-928f-4fbd-be3b-3106c67c87f8.png).

### Source

https://user-images.githubusercontent.com/38561765/204109645-7f43de6a-928f-4fbd-be3b-3106c67c87f8.png

### Steps to reproduce the problem

1. go c 3957
2. Try to talk with her

### Extra Notes

I tried to increase my reputation with The Violet Eye to friendly, honored, revered and exalted, but nothing changes

https://github.com/chromiecraft/chromiecraft/issues/4508

### AC rev. hash/commit

AzerothCore rev. 55957fbb6e24

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
I know this is an issue I opened on the CC tracker, but if you're using a screenshot as a source, at least add context to it saying where it's taken from, whether retail, classic PTR/live, or retail Wrath footage.

**Comment by FallenDev** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5641 

There is a workaround mentioned here.

**Comment by heyitsbench** [comment]
> There is a workaround mentioned here.

Not that it's too much of a concern for AC itself, but given how close CC is to content brackets involving Leryda, I feel that a workaround fix might not be preferable, just my two cents though.
