### ISSUE TITLE
[Vault of Archavon] `Koralon the Flame Watcher` loot bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#14019]
### Current Behaviour

`Koralon the Flame Watcher` loot have a bug

alliance can pickup 6 items in 25 player raid mode, while  horde players can only pickup 4 items

https://youtu.be/1zfaLBYLxA0

### Expected Blizzlike Behaviour

all the players can only pickup 4 items

### Steps to reproduce the problem

1. characters A alliance
2. characters B horde
3. goto VOA
4. killed `Koralon the Flame Watcher` and loot

### AC rev. hash/commit

11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

Ubuntu20.04

**Comment by mpfans** [comment]
@UltraNix tyvm

**Comment by UltraNix** [comment]
@mpfans But alliance and horde players in one raid?
