### ISSUE TITLE
Diminishing returns on CC

### ISSUE THREAD

**Issue by dkapte** [azerothcore/azerothcore-wotlk#14016]
### Current Behaviour

It seems that crowd control fails to trigger the Diminishing returns on a player.
Example is Utgarde Keep. The first enemy (Dragonflayer Weaponsmith) casts Concussion Blow a 5 second stun. If you get attacked by 5 enemies you are chain stunned for 20 seconds or more as there is no Diminishing return triggered.

### Expected Blizzlike Behaviour

On multiple applications of crowd control, diminishing return kicks in and lowers the time the crowd control lastst on the 2nd , 3rd , 4th etc application of the same crowd control method.

### Source

Source is every enemy that has the ability to crowd control , example is first enemies in Utgarde Keep

### Steps to reproduce the problem

Encounter crowd control enemy, like first enemies in Utgarde Keep
Let them do the CC 5 times and see no diminishin returns

### AC rev. hash/commit

--

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
Add commit/hash and a source that confirms that this is intended for all mobs
