### ISSUE TITLE
Unknown column 'id1' in 'where clause'

### ISSUE THREAD

**Issue by bruceshao** [azerothcore/azerothcore-wotlk#14011]
### Current Behaviour

Updating World database...
>> Applying update "2022_08_21_18.sql" 'A17B668'...
ERROR 1054 (42S22) at line 3 in file: '/azerothcore/data/sql/updates/db_world/2022_08_21_18.sql': Unknown column 'id1' in 'where clause'

Applying of file '/azerothcore/data/sql/updates/db_world/2022_08_21_18.sql' to database 'acore_world' failed! If you are a user, please pul
l the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use au
to-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.

### Expected Blizzlike Behaviour

find error and repair

### Steps to reproduce the problem

./acore.sh docker start:app

All others refer to official documents use docker mode

### AC rev. hash/commit

commit 11530ecb95a35f66a2c220781172c57e0749ac48
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Sun Nov 27 13:13:33 2022 +0000

    chore(DB): import pending files
    
    Referenced commit(s): bbe8dd85c2d39b6305792f48919928163e060f6f

branch is master

### Operating system

centos7.8

**Comment by Kitzunu** [comment]
Something on your end. This was made a year ago with no issues.
