### ISSUE TITLE
Chinese wow 3.3.5 13930 crash again

### ISSUE THREAD

**Issue by EvilCalf** [azerothcore/azerothcore-wotlk#14013]
### Current Behaviour

![image](https://user-images.githubusercontent.com/35754619/205077398-8f676c52-be1c-4290-becf-941081dacbbb.png)

The result as the issues #2564
[2022-12-01 22.02.23 Crash.txt](https://github.com/azerothcore/azerothcore-wotlk/files/10133409/2022-12-01.22.02.23.Crash.txt)

It is the same performance，but i clone the newest azcore.

### Expected Blizzlike Behaviour

no crash

### Steps to reproduce the problem

1、build the acore
2、use wow13930 to Extractor data
3、finish all the step to install acore and start it
4、run wow.exe and crash

### AC rev. hash/commit
11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

windows11

**Comment by lyrl** [comment]
主流的是3.3.5 12340

**Comment by 55Honey** [comment]
> 主流的是3.3.5 12340

I'm sorry, I don't read Chinese.

**Comment by acidmanifesto** [comment]
Adjust the RealmBuildInfo to reflect the following.
'''
static RealmBuildInfo const PostBcAcceptedClientBuilds[] = { 
    { 13930, 3, 3, 5, 'b' }, 
    { 12340, 3, 3, 5, 'a' }, 
    { 0, 0, 0, 0, ' ' } }; 

static RealmBuildInfo const PreBcAcceptedClientBuilds[] =
 { 
    { 0, 0, 0, 0, ' ' } 
};
'''
13930 is a unqiue wotlk build for chinese locale clients.
It isnt natively support in azerothcore.

This issue will be closed as you are using a a incompatible client with azerothcore as we only support 12340.
