### ISSUE TITLE
Fengus Ferocity self casted lvl 8 Paladin

### ISSUE THREAD

**Issue by pewpewgit** [azerothcore/azerothcore-wotlk#14023]
### Current Behaviour

Level 8 paladin somehow casts fengus ferocity on herself.

### Expected Blizzlike Behaviour

Not being able to buff fengus ferocity.

### Source

Idk how to source something that is not supposed to happen.

### Steps to reproduce the problem

1. Was fighting Grimscale murlocs in bloodelf starting area.
2. Somehow casted fengus ferocity.
3. Now have fengus ferocity.

### Extra Notes

![image](https://user-images.githubusercontent.com/117426478/205364757-70bc1262-3d7c-482b-8668-5b9ec2f02a1a.png)
![image](https://user-images.githubusercontent.com/117426478/205364820-e6e9334e-79af-4e88-a89e-362811e0d877.png)
![image](https://user-images.githubusercontent.com/117426478/205364876-e247fdd9-4e79-4452-bd91-e98a4026b8a7.png)

### AC rev. hash/commit

Idk how this works

### Operating system

Windows 10

### Custom changes or Modules

None

**Comment by 55Honey** [comment]
That's not a bug, a GM has cast this on all players and also sent a message along with it.
But thanks for watching out!
