### ISSUE TITLE
[Sethekk Halls] The Talon King's Coffer (187372) can only be looted by one player

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14068]
### Current Behaviour

The Talon King's Coffer (187372) can only be looted by one player. After looting it returns to being non-selectable

### Expected Blizzlike Behaviour

Should be lootable from everyone in the dungeon group

### Source

behind the last boss in sethekk halls called Talon king ikiss it 100% drops the shadow labyrinth key and can be looted by all ([source](https://www.wowhead.com/object=187372/the-talon-kings-coffer#comments:id=774513))

### Steps to reproduce the problem

1. Use 2 characters
2. `.go xyz 81.6 286.7 26.62936 556 3.1`
3. Kill Talon King Ikiss
4. Try to loot with 2 characters

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6

### Operating system

Windows 10

**Comment by Gultask** [comment]
One more thing: The chest obviously shouldn't despawn when interacted with.

```
UPDATE `gameobject` SET `spawntimesecs`=0 WHERE `guid`=44719 AND `id`=187372;
```

**Comment by UltraNix** [comment]
I cannot reproduce it - both characters get the key.

**Comment by Gultask** [comment]
I can't reproduce it anymore either. Interesting.
But thanks for checking!
