### ISSUE TITLE
Custom text in requirement_note does not work for dungeon_access_requirement

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14069]
### Current Behaviour

No text is sent to the player

### Expected Blizzlike Behaviour

Text is sent.

### Steps to reproduce the problem

1. `.tele theblackmorass`
2. try to enter the instance in Normal Mode
3. no text is shown

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
Custom text *does* work for the heroic mode of Black Morass at least.

**Comment by Gultask** [comment]
And for Pit of Saron, Halls of Reflection, etc
