### ISSUE TITLE
[dungeon_access_requirements] leader_only does not work for LFG

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14070]
### Current Behaviour

When an access requirement is set to leader_only, it is not enforced through LFG and the group must enter the instance manually

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

`.quest add 10285` `.quest reward 10285` on one character
rest of the group does not complete quest
attempt to enter Opening the Dark Portal using LFD

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6

### Operating system

Windows 10

**Comment by UltraNix** [comment]
@Gultask You mean queing the LFD while being in group?
