### ISSUE TITLE
Suggestion: Easier way to handle GUID-specific SmartAI so it does not affect Entry SAI

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14077]
### Describe your feature request or suggestion in detail

There are 3 main issues surrounding GUID-specific SAI:

1. Too many rows

Taking a well-built, complex SAI for a single entry, it could have 10+ rows of SAI scripting. However, if there are some behaviour specific to each GUID, then the only way to accomplish this task would be to increase the number of rows multiplicatively, unnecessarily bloating the DB with duplicate rows for scripts that already exists.

2. Retroactively fixing SAI scripts becomes harder for each GUID-specific entry there is

If a timer is determined to be wrong in one spell cast, then one would need to fix it for all GUIDs of the same entry. If new rows need to be added, then good luck.

3. Impossible to work with dual IDs

Dual IDs for creatures is a proven behaviour. However, it cannot work with GUID-specific SAI, as it would overwrite the combat AI with one for another creature, causing melee creatures to cast spells, for example.

### Describe a possible solution to your feature or suggestion in detail

1. A new source_type that is linked to creature_addon. This will play OOC, and will switch over to source_type 0 when IC

2. A method for GUID-specific SAI to link back to their entry SAI automatically, by having the GUID-specific SAI with negative row IDs, for example.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6

### Operating system

Windows 10

**Comment by Gultask** [comment]
Video for Blackheart: https://youtu.be/JLRoJmfw4u0

**Comment by Nyeriah** [comment]
It can be observed in several if not all instances. Mobs walking towards a pack, doing talk emote, and the other mobs standing reply with talk emote, etc. observed this in ubrs before

**Comment by Gultask** [comment]
SSC has several packs like that. Now that you mention it I should make a list of all examples I can think of, at least for reference.

Also it needs to be said: These interactions can be and likely are GUID-specific, since:

1. They can differ in IDs. In Auchenai Crypts 2 different creatures can use different IDs to spawn, but they both do the same mechanic of casting a particular spell at a dummy creature.
2. The same creature IDs can be doing something else entirely throughout the instance.

**Comment by Gultask** [comment]
Shattered Halls as well has quite a complicated setup.
![image](https://user-images.githubusercontent.com/100873791/205701428-a33a9664-bdf6-4d2f-a84f-655522b20461.png)

**Comment by Gultask** [comment]
Several locations in The Mechanar and The Shattered Halls have one-way waypoints. I.e. they don't patrol but instead have their waypoints triggered on spawn or on areatrigger reached.

**Comment by ZhengPeiRu21** [comment]
Anything is possible to implement - I think we just need to design it to be easiest to use. I am having difficulty think of a table that we could implement that would not be redundant with SmartAI. Do you have any ideas of what table you would like to see that would make this easiest? If we can create the design, code the logic should not be difficult.

**Comment by Gultask** [comment]
I'm looking it seeing how many interactions there could possibly be before trying my hand at some sort of design, because I got stuck at that point 😛 
The hardest part to me is in how groups will respond. Perhaps there'll need to be some interaction between creature_formations.

**Comment by Gultask** [comment]
I've been thinking of some examples and I think it'd be best if the implementation is done by setting a value in the creature table.
And with not being constrained by creature IDs, the scripts should have independent IDs so that they can be shared across various creatures. Too many creatures share an emote-on-a-timer script that could be a single script used by many creatures.

**Comment by Gultask** [comment]
Another feature could be that it could also be assigned in creature_summon_groups as a way to solve waypoints and scripting for creatures summoned through this method.

**Comment by Gultask** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/15976 :)
