### ISSUE TITLE
[Shadowmoon Valley] Too few Ravenous Flayer Egg spawns

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14083]
### Current Behaviour

Below 10 spawns

### Expected Blizzlike Behaviour

At least 20

### Steps to reproduce the problem

`.list object 184684`

### Extra Notes

Other cores also have low numbers.
Already have a sniff with plenty of spawns. Waiting on WPP. This is just a reminder for myself or if someone wishes to do it first.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6

### Operating system

Windows 10

**Comment by avarishd** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/14238
