### ISSUE TITLE
[Blade's Edge Mountains] NPC - Fey Drake - Blink

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#14080]
### Current Behaviour

1. Seems Fey Drake to use himself as a target for Blink and teleport behind him.
2. Very often uses a blink at the end of the cast of Mana Burn and interrupts it.

### Expected Blizzlike Behaviour

1. He should use his current target as the target for Blink.
https://youtu.be/CHq9dRcSvoM?t=192 - 3:14
2. Must wait for Mana Burn to finish and then only use Blink

### Source

https://www.wowhead.com/tbc/npc=20713
https://youtu.be/CHq9dRcSvoM?t=192 - 3:14

### Steps to reproduce the problem

.go cr 73082

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11530ecb95a35f66a2c220781172c57e0749ac48

### Operating system

Windows 10 x64

**Comment by Gultask** [comment]
If anyone can do

```
UPDATE `smart_scripts` SET `target_type`=2 WHERE (`entryorguid` = 20713) AND (`source_type` = 0) AND (`id` IN (1));
```
and see if it works. If it does feel free to open a PR.

**Comment by Samsequel** [comment]
works
