### ISSUE TITLE
arthas' tears gm command does not exist (item 142141)

### ISSUE THREAD

**Issue by Devendas** [azerothcore/azerothcore-wotlk#14093]
### Current Behaviour

https://wotlkdb.com/?object=142141#links
does not exist when using gm command .additem 142141.

### Expected Blizzlike Behaviour

it should spawn arthas' tears in backpack or bags(s)

### Source

https://wotlkdb.com/?object=142141#links

### Steps to reproduce the problem

(as a gm or level 4 account) .additem 142141

### Extra Notes

i explored the world and they DO exist in game at correct places.

### AC rev. hash/commit

![20221207_215253](https://user-images.githubusercontent.com/119780316/206352495-1d9ebff7-9e06-485e-8c72-59f5c1442db7.jpg)

### Operating system

windows 10 x64

### Custom changes or Modules

none

**Comment by heyitsbench** [comment]
You're using `.additem` for an object ID number. Arthas' Tears are item ID [8836](https://wotlkdb.com/?item=8836).
