### ISSUE TITLE
[AQ40] Viscidus oozes are moving too slow

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14098]
https://github.com/chromiecraft/chromiecraft/issues/4538
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

Today in AQ40 we managed to kill all oozes (globules) in one freeze phase because globules moved like they're 99% slowed.

![WoWScrnShot_120722_194801](https://user-images.githubusercontent.com/80590226/206270245-c3c699a6-ac97-4ea3-b100-d92b1a744ef8.jpg)

### Expected Blizzlike Behaviour

Should move faster

### Source

https://www.youtube.com/watch?v=wlVWKkWQ1dM&ab_channel=DragonwindDen

From 1:04

### Steps to reproduce the problem

.go c id 15299
deal enough cold damage to freeze and then white damage to split

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14100
