### ISSUE TITLE
Karazhan chess can't begin

### ISSUE THREAD

**Issue by rushpixy** [azerothcore/azerothcore-wotlk#14101]
### Current Behaviour

the npc of chess can't  dialog

### Expected Blizzlike Behaviour

begin chess.

### Steps to reproduce the problem

.tele kara 
talk with king。
start chess

### AC rev. hash/commit

AzerothCore rev. 721711d70f31 2022-12-02

### Operating system

ubuntu 20.4

**Comment by heyitsbench** [comment]
Duplicate of #779.
