### ISSUE TITLE
[Paladin] Sense Undead spell problem with quest The Tome of Valor

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#14135]
### Current Behaviour

https://www.wowhead.com/classic/spell=5502/sense-undead

On the paladin, when completing the quest [Tome of Valor](https://www.wowhead.com/classic/quest=1794/the-tome-of-valor), the ability Sense for Undead is given, but when you get level 20, you can learn it from the trainer without completing the quest, which is not correct.

### Expected Blizzlike Behaviour

This ability can only be obtained by completing a quest.

### Steps to reproduce the problem

1. Create palading with level 20
2. .q add 1794
3. Go to paladin spell trainer

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+ 

### Operating system

Debian 11

### Custom changes or Modules

None

**Comment by heyitsbench** [comment]
[If you do the Paladin quests at level 20, you can get this spell for free. =)](https://www.wowhead.com/wotlk/spell=5502/sense-undead#comments:id=541447)

[As of patch 3.0.8, this ability seems to now be buyable from trainers. However, if you want to save the money, then this quest is a good thing to do.](https://www.wowhead.com/wotlk/spell=5502/sense-undead#comments:id=582142)

[Note you can both buy this spell from a pally trainer or learn it through a 3 chain lvl 20 questline, so if youre going to do the quest don't bother buying the spell.](https://www.wowhead.com/wotlk/spell=5502/sense-undead#comments:id=1012208)
