### ISSUE TITLE
How to break into Alcatraz

### ISSUE THREAD

**Issue by maradaka** [azerothcore/azerothcore-wotlk#1419]
I am trying to get Kara master key, the quest needs to be accomplished by finishing alcatraz instance, alcatraz also needs key but the quest to get this last one is not available.
https://www.wowhead.com/quest=10704/how-to-break-into-the-arcatraz
https://www.wowhead.com/quest=10205/warp-raider-nesaad

This nether-stalker khay'ji is not giving the starting quest.
https://www.wowhead.com/npc=19880/nether-stalker-khayji

All info are on wowhead links.

COMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/9af2a461f65316ce4c21c9668dd62515b8e4f370

**Comment by poszer** [comment]
1. Assisting the Consortium, a 'go talk to' quest (1200XP/72s)
2. Consortium Crystal Collection, kill a dreadlord called Pentatharon and get a crystal from him
3. A Heap of Ethereals repeatable quest also for Consortium reputation.
1st chain ends here : 25800XP, 510 Consortium reputation OR around 15g at 70

4. Warp-Raider Nesaad [Level 69] : http://www.wowhead.com/?quest=10205, a go-kill-him quest.
5. Request for Assistance [Level 69] : http://www.wowhead.com/?quest=10266 , find Gahruj at 47,57
6. Rightful Repossession [Level 69] : http://www.wowhead.com/?quest=10267 , get 10 boxes from around Mana Forge: Duro
7. An Audience with the Prince [Level 69] : http://www.wowhead.com/?quest=10268 , Nexus-Prince Haramad at 44,35 or so in the Stormspire.
8. Triangulation Point One [Level 69] : http://www.wowhead.com/?quest=10269 , use the Triangulation Device at 66, 33
9. Triangulation Point Two [Level 70] : http://www.wowhead.com/?quest=10275 , same thing at 28,41
10. Full Triangle [Level 70] : http://www.wowhead.com/?quest=10276 , Find Culuthas at 53, 21, 70 Elite demon.

2nd chain ends here: 1600 Consortium reputation, 71450 XP or around 60 gold if you're 70.

11. Special Delivery to Shattrath [Level 70] : http://www.wowhead.com/?quest=10280 , pretty obvious.
12. How To Break Into the Arcatraz [Level 70] : http://www.wowhead.com/?quest=10704 , the Bottom Shard of the Arcatraz Key : Pathaleon the Calculator in The Mechanar and the Top Shard of the Arcatraz Key : Warp Splinter in The Botanica. Pretty obvious if you know where they're located, huh.

The quest chain doesn't stop here, there's also
13. Harbinger of Doom [Level 70] after : http://www.wowhead.com/?quest=10882

After this 3rd quest chain, you get around 40g and your Key to the Arcatraz : http://www.wowhead.com/?item=31084

**Comment by maradaka** [comment]
Thank you very much!
