### ISSUE TITLE
[Trial of the Crusader] `Anub'arak` hero mode bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#14204]
### Current Behaviour

When fighting with `Anub'arak` in hero mode, the refreshed `Frozen Sphere`  will fall from the air. When P2 hits the ground and casts `Impale`, `Impale` will disappear when `Impale` hits `Frozen Sphere`. it works normally in normal mode

10&25 hero mode
![image](https://user-images.githubusercontent.com/18187177/207215850-ff984a08-6367-4903-949e-d515589d1c13.png)

10&25  normal mode
![image](https://user-images.githubusercontent.com/18187177/207219536-16b4df57-7050-4c68-aed8-bc85cb4d5d69.png)

### Expected Blizzlike Behaviour

`Frozen Sphere`  should be suspended in the air

### Steps to reproduce the problem

1. 10 hero or 25 hero mode enter Trial of the Crusader
2. fighting with `Anub'arak`

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/da429f65da6d9d781d0e6bfd148bfd8a502beb98

### Operating system

Ubuntu20.04

**Comment by mpfans** [comment]
@UltraNix  please

**Comment by UltraNix** [comment]
@mpfans I don't understand that report.
