### ISSUE TITLE
All raid members puted into combat， can't enter raid.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#14201]
### Current Behaviour

the player been  die in raid.   can't enter raid.  tips :   don't convert zone in combat.
this  happened  in   karazhan and  Zul'Aman

### Expected Blizzlike Behaviour

enter  raid。

### Steps to reproduce the problem

1

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6 2022-12-02

### Operating system

ubuntu 20.4

**Comment by Nefertumm** [comment]
Is this still valid? Could anyone check? @azerothcore/testers
