### ISSUE TITLE
Pets not reacting to taunt abilities.

### ISSUE THREAD

**Issue by Sneften** [azerothcore/azerothcore-wotlk#14217]
Original report: https://github.com/chromiecraft/chromiecraft/issues/4544
**Current Behaviour**
Pets do not react to direct taunt abilities. 

**Expected Blizzlike Behaviour**
 If a pet is:
- set to defensive/aggressive
- actively attacking a target

it should be affected by direct taunt abilities, forcing it to switch targets.
This does not include Aoe taunt's such as Challenging Roar.

**Source**
https://vanilla-twinhead.twinstar.cz/?issue=11428
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/42529631
The mechanic even seems to still work on patch 9.1: https://www.youtube.com/watch?v=GIUSSIsn1yw

**Steps to reproduce the problem**
require 1 hunter with pet, one warrior with taunt and a third target.

hunters pet attacks third target, warrior taunts pets, nothing happens

**AC rev. hash/commit**
https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

**Operating system**
Ubuntu 20.04

**Modules**
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

**Server**
ChromieCraft

**Comment by heyitsbench** [comment]
> **Expected Blizzlike Behaviour** If a pet is:
> * actively attacking a target

What happens if the pet is taunted while aggressive/defensive but not attacking a target? Are they supposed to attack the taunter or stay passive?
