### ISSUE TITLE
Critical BUG in emote

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#14214]
### Current Behaviour

Guys, I would like to report a critical bug in the emote system.  I don't really know how to reproduce, but there is a player on my server who abuses the emote system making the chat log fill up and the server crashes.  From what I've seen, he joins 4 players or more, I think he activates a macro system and after attacking some monsters together he makes all the characters release an emote and after a few seconds the server crashes.  Realizing this, I increased the minimum level to drop emote and it is partially solved, however the emote system is useless.

### Expected Blizzlike Behaviour

Up

### Steps to reproduce the problem

Up

### AC rev. hash/commit

790f444ffac0

### Operating system

Windows

**Comment by heyitsbench** [comment]
Please include a crash log and revision hash/commit so the issue can be investigated.

**Comment by htc16** [comment]
No crash, no log.  All I know is because my GM was invisible near these characters and at the moment my chat log filled with emote and in seconds the server was stuck but not crashed, but inaccessible.

**Comment by heyitsbench** [comment]
Lack of a crash log I can understand if the server doesn't crash, but server logs are generated in real time, not on shutdown.

**Comment by htc16** [comment]
Perhaps a feature that limits emote spam per second per character.  Even empty emotes.

**Comment by htc16** [comment]
That's ok, but it's not generating log by GDB, because the server doesn't shut down, it hangs and overloads the CPU.

**Comment by heyitsbench** [comment]
> Perhaps a feature that limits emote spam per second per character.

For the record, this already exists. I made a macro that spammed `/hug` And autoclicked it and basically immediately got kicked from the server, no hang, no crash. This issue likely *needs* logs to fix.

**Comment by htc16** [comment]
That's exactly it.  But this player is putting 4 characters together and after attacking some bugs in the undead class area.

**Comment by htc16** [comment]
> > Perhaps a feature that limits emote spam per second per character.
> 
> For the record, this already exists. I made a macro that spammed `/hug` And autoclicked it and basically immediately got kicked from the server, no hang, no crash. This issue likely _needs_ logs to fix.

Just to make a point, the emote that the characters released is not `/hug`.
I'll try to find out what it was.

**Comment by htc16** [comment]
@heyitsbench 

look, the guy did it again!

![WoWScrnShot_121322_171253](https://user-images.githubusercontent.com/58153179/207434930-189a8036-4104-4e0b-88a9-10a27f25d512.jpg)
![WoWScrnShot_121322_171249](https://user-images.githubusercontent.com/58153179/207434938-709facf9-75c7-4cc3-b6e4-787781b3c9fb.jpg)
![WoWScrnShot_121322_171150](https://user-images.githubusercontent.com/58153179/207434941-24d33f1f-0d6d-40da-a42b-ee6e699e7b79.jpg)
![WoWScrnShot_121322_171147](https://user-images.githubusercontent.com/58153179/207434943-d26b4685-6f24-4127-b5d1-8d723d5bf475.jpg)
![WoWScrnShot_121322_171145](https://user-images.githubusercontent.com/58153179/207434944-c0a4addc-a67c-43e1-be12-2c20c007c299.jpg)
![WoWScrnShot_121322_171131](https://user-images.githubusercontent.com/58153179/207434947-d7922738-3002-4bc6-970d-4a929f28d5cd.jpg)
![WoWScrnShot_121322_171125](https://user-images.githubusercontent.com/58153179/207434952-1daca1d6-795e-4220-809a-d8e93280202f.jpg)
![WoWScrnShot_121322_171116](https://user-images.githubusercontent.com/58153179/207434954-b8e9d600-8cb9-406c-a7ce-f79a65306051.jpg)
![WoWScrnShot_121322_171105](https://user-images.githubusercontent.com/58153179/207434955-b4f26ed0-9550-411b-b859-f21bb3c4f188.jpg)
![WoWScrnShot_121322_171100](https://user-images.githubusercontent.com/58153179/207434956-5555b29b-7432-46a7-8f1c-56711721e34e.jpg)
![WoWScrnShot_121322_171058](https://user-images.githubusercontent.com/58153179/207434958-6968355f-2845-49ec-a3d5-715cf668c32c.jpg)
![WoWScrnShot_121322_170900](https://user-images.githubusercontent.com/58153179/207434960-c3c2b4f1-6c66-46e9-82e6-f6b3564e17f9.jpg)

I have thousands of it, I don't know if it has something to do with it.
![image](https://user-images.githubusercontent.com/58153179/207435125-db917a92-c4f6-4f07-9d89-e457404f59f1.png)

and nothing in GDB
![image](https://user-images.githubusercontent.com/58153179/207435399-b121d189-227a-4b3f-97f3-4a4bde4b63aa.png)

**Comment by htc16** [comment]
and the server is still on, but inaccessible.

**Comment by acidmanifesto** [comment]
> and the server is still on, but inaccessible.

No gm cmds respond thru the console?

**Comment by htc16** [comment]
the only thing that works is if i go above the limit for players not to use that emote feature.

![image](https://user-images.githubusercontent.com/58153179/207436394-3f12dda8-e56c-4988-ba24-3e9a993dcebb.png)

**Comment by htc16** [comment]
As it seems to me, the guy is writing something using a fictitious command maybe, and putting `..somethinghere`

**Comment by htc16** [comment]
> > and the server is still on, but inaccessible.
> 
> No gm cmds respond thru the console? Whats the memory usuage?

![image](https://user-images.githubusercontent.com/58153179/207438286-fc999794-2f2a-442c-80df-819b3c95e983.png)

![image](https://user-images.githubusercontent.com/58153179/207438330-fd202566-4abf-44af-b5d5-188f00028b66.png)

**Comment by acidmanifesto** [comment]
> > > and the server is still on, but inaccessible.
> > 
> > 
> > No gm cmds respond thru the console? Whats the memory usuage?
> 
> ![image](https://user-images.githubusercontent.com/58153179/207438286-fc999794-2f2a-442c-80df-819b3c95e983.png)
> 
> ![image](https://user-images.githubusercontent.com/58153179/207438330-fd202566-4abf-44af-b5d5-188f00028b66.png)

is the huge spike when it happened?

**Comment by htc16** [comment]
That, coincidentally reporting here, was just now.

**Comment by acidmanifesto** [comment]
> That, coincidentally reporting here, was just now.

i am only home for a little bit before i have to head out for another few hours.
what i can tell atleast from your ss is this:
they made a custom Emote using /e and typing out something. it's only understandable by your faction, so it comes out as "says something unintelligible."

**Comment by acidmanifesto** [comment]
now unless we know what is being sent. such as logging chat logs to help, example here:https://www.azerothcore.org/wiki/logging-configuration

the only way you are going to find out what to do is to have debugger attached to the build when it happens.
ensure it is compiled as release with debug or as debug.

**Comment by htc16** [comment]
The guy doing this just tried again and gave up trying after I leveled the emote.

**Comment by htc16** [comment]
> now unless we know what is being sent. such as logging chat logs to help, example here:https://www.azerothcore.org/wiki/logging-configuration
> 
> the only way you are going to find out what to do is to have debugger attached to the build when it happens. ensure it is compiled as release with debug or as debug.

as I said above, I use the server in compiler mode, and it didn't generate a log, because I don't know, but the server isn't crashing, it's just becoming infinitely unreachable and only comes back online if I restart.

**Comment by acidmanifesto** [comment]
also check your worldserver conf in the CHAT SETTINGS
we have features for auto kick and stictlink checking and message count flood with mute time.

also add to the world conf:


Appender.chat.log=2,4,15,chat.log,a
Logger.chat.log=4,Console Server

I think that should log every darn thing into a chat.log file.

**Comment by htc16** [comment]
Ok, I'm going to start making use of these resources that you presented. I'm going to take it easy, because it's been almost 1 week that this has been happening non-stop and I've been monitoring to see how to solve it and all the players are angry, because the server doesn't stop crashing.

**Comment by Kitzunu** [comment]
Go into config, enable freeze detection, recieve crash log

**Comment by htc16** [comment]
> Go into config, enable freeze detection, recieve crash log

GDB?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/3251e7f4219a5b573118b2d974da370b3c2e5f21/src/server/apps/worldserver/worldserver.conf.dist#L474

**Comment by AnchyDev** [comment]
Looking at the screenshot, I think that is the use of the /e emote command. Have you tried making a horde character to view what is being sent through the emote? Maybe he's maxing out the character limit or sending invalid characters?

**Comment by UltraNix** [comment]
You can try to put some opcode limit on `CMSG_MESSAGECHAT` packet in `GetMaxPacketCounterAllowed`

**Comment by htc16** [comment]
> also check your worldserver conf in the CHAT SETTINGS we have features for auto kick and stictlink checking and message count flood with mute time.
> 
> also add to the world conf:
> 
> Appender.chat.log=2,4,15,chat.log,a Logger.chat.log=4,Console Server
> 
> I think that should log every darn thing into a chat.log file.

Guys, I think these measures above helped me in something, because the player was playing normally on the server and he didn't crash anymore.  I will keep this issue closed and if there is still something again I will reopen it.
