### ISSUE TITLE
NPC: Strange Winged Goblin waypoints

### ISSUE THREAD

**Issue by Nefertumm** [azerothcore/azerothcore-wotlk#1421]
##### SMALL DESCRIPTION:

Just a missing waypoint i guess, i saw it in console.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The npc should have a waypoint or just delete waypoint data.

##### CURRENT BEHAVIOUR:

[https://imgur.com/a/2ZN8b6J](https://imgur.com/a/2ZN8b6J)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just execute the worldserver

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/37d9ef012608a1ddaa839f7e6b63e22fcd821d90

##### OPERATING SYSTEM:

Windows 10, Ubuntu (not sure about the version)

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No, fresh install.

**Comment by comix1988** [comment]
![goblin](https://user-images.githubusercontent.com/22867608/52366299-af16d880-2a49-11e9-9db7-dfac45d3fb94.png)

I found this on wowpedia, maybe this npc has been removed in the 3.3.0 patch

**Comment by BarbzYHOOL** [comment]
temp fix = remove his waypath 

or invent one :D

**Comment by FrancescoBorzi** [comment]
or we might just removed it...

**Comment by poszer** [comment]
Wrath of the Lich King Patch 3.3.0 (2009-12-08): Removed. 
We should do the same
