### ISSUE TITLE
All enemy 'red' nameplate npc showing as neutral 'yellow'.

### ISSUE THREAD

**Issue by Bernabo** [azerothcore/azerothcore-wotlk#14227]
### Current Behaviour

All creatures are showing as neutral. Ones normally marked 'red' are now 'yellow'. 

### Expected Blizzlike Behaviour

Creates such as 'defias brotherhood' npc should aggro and show as enemy. Currently marked as neutral 'yellow' name plate. 

### Steps to reproduce the problem

Create a Human character and run over to the defias brotherhood area. All npc's are yellow. 

### AC rev. hash/commit

current / ACDB 335.8-dev

### Operating system

Ubuntu

**Comment by heyitsbench** [comment]
https://www.reddit.com/r/wowservers/comments/79v8h3/comment/dp5ours/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Bernabo** [comment]
The more ya know! Thanks!
