### ISSUE TITLE
Hunter can't loot any items form creature thoes killed by his pet.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#14237]
### Current Behaviour

Hunter don't do any things self, noly control his pet kill any creature,  then try loot the creature. always loot nothing.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 1386f86bc2ba+ 2022-12-14 08:45:36 +0000 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100515
Using CMake version: 3.18.4
Compiled on: Linux 5.15.64-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 54345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2320900760 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-server-auto-shutdown

### Operating system

debian 11 x64

**Comment by Nyeriah** [comment]
If the pet kills the mob on their own you are not entitled to any reward (experience, loot, reputation etc.), that’s intended. However if you deal damage to it you should be able to get the rewards

**Comment by kissingers** [comment]
OK, I see.

**Comment by Gultask** [comment]
If I recall correctly only 1 point of damage is necessary to be entitled to loot/credit.
