### ISSUE TITLE
GEODATA

### ISSUE THREAD

**Issue by vahzxz** [azerothcore/azerothcore-wotlk#1424]
**SMALL DESCRIPTION:**
Geodata does not work correctly.
https://www.youtube.com/watch?v=S5aRgQJ0VVk&t=19s

**Correct work:**
Valkyrie should fly above the ground, not in textures

**##### EXTRA NOTES:**
It works on trinity.

**##### BRANCH(ES):**
master

**##### AC HASH/COMMIT:**
[37d9ef0](https://github.com/azerothcore/azerothcore-wotlk/commit/37d9ef012608a1ddaa839f7e6b63e22fcd821d90)

**##### OPERATING SYSTEM:**
Debian 9

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Viste** [comment]
lol on trinity you say its don't work here you say its work ))
Your video is recorded on the core of trinity, you've been burned by your chat)))
Используй https://www.deepl.com/translator для перевода))
короче заканччивай врать везде, где только можешь :)
