### ISSUE TITLE
Winter Reveler model is not correct

### ISSUE THREAD

**Issue by Purple-23** [azerothcore/azerothcore-wotlk#14257]
### Current Behaviour

There are a few "Winter Reveler" models throughout the world that are not using the correct model. It appears that the models are supposed to be "Human Male Winter Reveler" or "Orc Male Winter Reveler" but occasionally the NPC "Winter Reveler" will be spawned in and the model is all white and unfinished.

![Screenshot 2022-12-16 182720](https://user-images.githubusercontent.com/120799273/208247897-20f6c2de-01d7-4814-9290-c349967db578.png)

This CMangos issue regarding the winter revelers is pretty much the issue I am having:

[https://github.com/cmangos/issues/issues/1815](url)

### Expected Blizzlike Behaviour

The model should not be unfinished like this.  I believe the game event npc guid 15760 should not be pulled into  the world at all since that appears to be the npc that is unfinished.

### Steps to reproduce the problem

If building an azerothcore server yourself, following the instructions on the site, I would imagine this model would appear in a city or town wherever there are Winter Revelers anywhere.  

### AC rev. hash/commit

.server debug
AzerothCore rev. 4a2964e10a03 2022-11-21 23:22:24 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.79.0
Using MySQL version: 80031
Using CMake version: 3.25.0
Compiled on: Windows 10.0.22621
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Build/bin/RelWithDebInfo/Data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 4563
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-autobalance
- mod-individual-progression
AC>

### Operating system

windows 11

### Custom changes or Modules

AH Bot
Individual Progression
Autobalance

**Comment by Riveir** [comment]
Essentially just changing the model id to use the one trinitycore used in their core is an acceptable fix imo. See below.


USE acore_world;

REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) 
VALUES (15760, 0, 0, 0, 0, 0, 15744, 1520, 0, 0, 'Winter Reveler', NULL, NULL, 6813, 30, 40, 0, 35, 1, 1, 1.14286, 1, 1, 18, 1, 0, 0, 1, 2000, 2000, 1, 1, 1, 36864, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, '', 12340);

**Comment by Purple-23** [comment]
This worked flawlessly!  Thank you so much!

**Comment by Synful-Syn** [comment]
Should have been closed by a pull request. It is still a bug on AzerothCore.
```
AzerothCore rev. 721711d70f31+ 2022-12-02 08:59:47 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.78.0
Using MySQL version: 80027
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 1
No modules enabled
```

**Comment by heyitsbench** [comment]
For the record, the suggested fix is only a hackfix.

**Comment by Stump876** [comment]
Bench's CC report https://github.com/chromiecraft/chromiecraft/issues/4561

**Comment by Riveir** [comment]
> For the record, the suggested fix is only a hackfix.

Agreed. However it was better than nothing at the time.
