### ISSUE TITLE
Naturalist Bite doesn't chat when freed

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14259]
### Current Behaviour

Does not yell anything
Does not mention freeing making noise
When you free him the NPCs spawn right next to him

### Expected Blizzlike Behaviour

Yells "Hey! Over here! Yeah, over here... I'm in this cage!!!" when a player enters the room
Says "Uh oh! It would appear that all of the noise you've been making has attracted some unwanted attention!" after stepping out of his cage
NPCs spawn out of the tunnel and the Coilfang Champion yells "Intrudersss with the prisssoner! Kill them !!!"

### Source

https://youtu.be/N4k1Malqmi0?t=1360

### Steps to reproduce the problem

1. .go c 79441
2. free the npc and see what he says
after this you can notice that 3 Coilfang spawn directly over you

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/4573

https://github.com/azerothcore/azerothcore-wotlk/issues/8559
this issue mention the incorrect path of npcs that spawn after you free Naturalist Bite

### AC rev. hash/commit

2fbe8e47f55d

### Operating system

Windows 10 x64

**Comment by Gultask** [comment]
I've sniffed the waypoints and chats, they're present in that issue linked: https://github.com/azerothcore/azerothcore-wotlk/issues/8559
