### ISSUE TITLE
Wing Commander Brack missing flight to spinebreaker post 

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14264]
https://github.com/chromiecraft/chromiecraft/issues/4586
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

[Wing Commander Brack](https://wowwiki-archive.fandom.com/wiki/Wing_Commander_Brack) does not offer gossip option to fly to Spinebreaker Post

### Expected Blizzlike Behaviour

Gossip option should be present

### Source

![image](https://user-images.githubusercontent.com/11332559/208263817-44103824-b6cd-4436-b865-463721c0e058.png)

https://wowwiki-archive.fandom.com/wiki/Spinebreaker_Post

![image](https://user-images.githubusercontent.com/11332559/208263868-31d87fce-d7a6-471a-b735-6ca2c3ed35b7.png)

### Steps to reproduce the problem

.go c id 19401

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=34578

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
rev. de50ce3
Could not reproduce, gossip is there WHILE you are on the quest.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/99956aef-7380-4336-8ccc-774ade9cc9eb)
