### ISSUE TITLE
Modules doesn't work

### ISSUE THREAD

**Issue by franciscotom28** [azerothcore/azerothcore-wotlk#14260]
Hello everyone, a few days ago i managed to run my own server and works fine, the problem is as the title say, any modules loads correctly, the DB imports works were easy to deal with and worked great and generate the build just like the instructions told me so but the moment i load the worldserver it gives me these error messages:
![imagen](https://user-images.githubusercontent.com/28004960/208249390-0f1d3b25-6459-47b0-80eb-77dc4352af1a.png)

I tried to apply solutions from other posts but i can't see where do i fail to implement them, i give also a screenshot of the build made with cmake:
![imagen](https://user-images.githubusercontent.com/28004960/208249418-049dd962-4aa1-4048-b39d-5416e96fbe13.png)

**Comment by acidmanifesto** [comment]
On my side with current revision https://github.com/azerothcore/azerothcore-wotlk/commit/2fbe8e47f55dd460e0f3a9ec9b8167ad0da22ceb i am having no such issue.
Ensure the -master in the folder name of the modules are not present. for example.
mod-transmog-master should be mod-transmog.
Delete cmake and re-run it. 
when you load up your solution besure to clean the solution before building.

**Comment by Kitzunu** [comment]
1 issues here.

1. You are not following the bug issue template https://github.com/azerothcore/azerothcore-wotlk/issues/new?assignees=&labels=&template=bug_report.yml

As per your issue, it looks to me you only generated it in CMake and then started worldserver. You need to recompile your source after Generating the code from CMake
