### ISSUE TITLE
Stonescythe Alpha/Whelp/Ambusher Desperate Defense 

### ISSUE THREAD

**Issue by Sneften** [azerothcore/azerothcore-wotlk#14266]
Original reports:
https://github.com/chromiecraft/chromiecraft/issues/4588
https://github.com/chromiecraft/chromiecraft/issues/4587

**Current Behaviour**
[Stonescythe Alpha](https://www.wowhead.com/npc=16929/stonescythe-alpha#comments:id=47834) and [Stonescythe Ambusher](https://www.wowhead.com/tbc/npc=16928/stonescythe-ambusher#abilities) does not cast Desperate Defense at all.
[Stonescythe Whelp](https://www.wowhead.com/npc=16927/stonescythe-whelp#comments:id=47831) casts Desperate Defense to soon, ~90%
No emote text in the chat when Desperate Defense is initiated.
Mobs move while Desperate  Defense is active.
Desperate Defense buff is not removed when target is struck.

**Expected Blizzlike Behaviour**
Desperate Defense should be cast by all mobs around 50% HP.
_Stonescythe Alpha/Whelp/Ambusher defends himself in desperation._ is posted in chat log when Desperate Defense is cast.
Should not move while Desperate Defense is active.
When target is struck while it has Desperate defense it should enrage and buff should disappear.

**Source**
From Wotlk Classic
![Screenshot 2022-12-17 220023](https://user-images.githubusercontent.com/103856689/208265859-8d57bd87-d1af-4d41-968c-ec10439df8ea.png)
![Screenshot 2022-12-17 220822](https://user-images.githubusercontent.com/103856689/208266070-508d10dd-96f9-4569-970f-b20945109cfb.png)

**Steps to reproduce the problem**
.go c 58812
attack

**AC rev. hash/commit**
https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

**Operating system**
Ubuntu 20.04

**Modules**
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

**Server**
ChromieCraft

**Comment by Tereneckla** [comment]
Desperate Defense should not disappear when struck
Desperate Rage can stack up to 5, each hit during Desperate Defense adds one stack

**Comment by Sneften** [comment]
> Desperate Defense should not disappear when struck Desperate Rage can stack up to 5, each hit during Desperate Defense adds one stack

Ok im not 100% sure how its really working but on wotlk classic right now the buff disappears, atleast visually.

**Comment by Ovahlord** [comment]
The buff has an absorb aura that absorbs 1000 damage. So the aura disappearing happens when the shield is broken. The aura itself has proc flags so when being hit, the proc triggers a rage stack. However, you can skip the stacking up to 5 when you break the absorb aura with strong hits.

Additionally there are two serverside spells involved. One is most likely for rooting the creature in place, the other one is a periodic dummy serverside aura which might be handling the emotes.

**Comment by Sneften** [comment]
![image](https://user-images.githubusercontent.com/103856689/208288794-f9678d97-051e-41c3-8cc5-341581a5e5b7.png)

**Comment by Sneften** [comment]
https://github.com/chromiecraft/chromiecraft/issues/4781
