### ISSUE TITLE
Ramparts - Nazan gets stuck in air when quickly killing Vazruden

### ISSUE THREAD

**Issue by Samsequel** [azerothcore/azerothcore-wotlk#14279]
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

When Nazan drops of Vazruden and you hit Vazruden below 50% very quickly, Nazan gets stuck in the air as if there is a floor

### Expected Blizzlike Behaviour

Nazan should not get stuck

### Source

---

### Steps to reproduce the problem

1. Go to ramparts
2. Quickly kill Vazruden

### Extra Notes

https://www.wowhead.com/tbc/npc=17537/vazruden
Script name: boss_vazruden

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by neifion-00000000** [comment]
![image](https://user-images.githubusercontent.com/91289495/208460172-4833e723-bd38-4903-b668-40ee77d352b1.png)
this is more of a general issue with corpses not falling to the ground on kill (even player corpses should fall when player releases)

**Comment by acidmanifesto** [comment]
Just dropping this here for reference as i got absolutely blitz when npc id's are not posted.
https://www.wowhead.com/tbc/npc=17537/vazruden

**Comment by UltraNix** [comment]
@Samsequel I can't reproduce it. Everytime I kill Vazruden, Nazan properly descend.

**Comment by Samsequel** [comment]
Hmm, it seems to always happen when the dragon is on the right side when engaging (facing to the platform) and you kill vazruden quickly after dropoff.

**Comment by UltraNix** [comment]
Still nothing.
@Samsequel Could you record video of this?

**Comment by Samsequel** [comment]
Sure

**Comment by Samsequel** [comment]
Hmm, I see, I will try to record it on live when it happens again, I cant seem to find what exactly is causing it indeed.
