### ISSUE TITLE
[Terokkar Forest] NPC - Neophyte Guardian

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#14292]
### Current Behaviour

A strange NPC that is located next to the neutral quest camp. He attacks players who are not friendly to the Aldor, but they cannot attack him back.
.go cr 85563

### Expected Blizzlike Behaviour

It probably shouldn't be there. Wowhead has no information about him at all, no spawn points, no comments
https://www.wowhead.com/npc=21312/neophyte-guardian

### Source

https://www.wowhead.com/npc=21312/neophyte-guardian

### Steps to reproduce the problem

.go cr 85563

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Windows 10 x64

**Comment by Sneften** [comment]
Hey Santaria! I was unable to find this NPC in wotlk classic.
