### ISSUE TITLE
Scout Jyoba should be dead

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14295]
### Current Behaviour

While his HP is shown as dead he can be attacked by alliance and will fight back

### Expected Blizzlike Behaviour

He's a corpse
Dead

### Source

https://wowgaming.altervista.org/aowow/?npc=18035

Tested in game

![WoWScrnShot_121922_170832](https://user-images.githubusercontent.com/82369562/208470531-1f02cc39-1d51-4fc5-8b21-ccfc7b7fbf12.jpg)

### Steps to reproduce the problem

1. Be alliance
2. .go c 84372
3. attack him

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/4606

### AC rev. hash/commit

2fbe8e47f55d

### Operating system

 Windows 10 x64

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14799
