### ISSUE TITLE
[QUEST] "data rescue" bug

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1429]
<DESCRIPTION:

the "data rescue" quest inside gnomeregan can't be completed

EXPECTED BLIZZLIKE BEHAVIOUR:

after obtaining the various cards from Matrix Punchograph 3005 A-B-C, when you interact with Matrix Punchograph 3005 D you get [Prismatic Punch Card] to complete the quest

![schermata 2019-02-08 10 00 34](https://user-images.githubusercontent.com/22867608/52468246-6c0f4f00-2b88-11e9-9e9c-ec43006677a3.png)

CURRENT BEHAVIOUR:

after obtaining [Red Punch Card] the Matrix Punchograph 3005-D does't let the quest complete.

STEPS TO REPRODUCE THE PROBLEM:

.quest add 2930
.go -862.1 395.7 -316.4 90
.add 9281
talk with Matrix Punchograph 3005-D 

BRANCH(ES):
staging

AC HASH/COMMIT:
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by zato90** [comment]
I have also encountered this problem but also using the cage the ferret is not summoned because it does not find nearby tubers. I tried in all the istance.

**Comment by poszer** [comment]
Fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/1443

**Comment by comix1988** [comment]
@poszer I remember that this fix was not imported. Looking at the sql file of the pr-1443  I don't see references to the quest data rescue

**Comment by poszer** [comment]
> @poszer I remember that this fix was not imported. Looking at the sql file of the pr-1443 I don't see references to the quest data rescue

You re right. Will try to fix issue with it
