### ISSUE TITLE
[Hellfire Peninsula] Magtheridon Channelers are pulled by distance when they are passive

### ISSUE THREAD

**Issue by Valdifer** [azerothcore/azerothcore-wotlk#14306]
### Current Behaviour

In Magtheridons Lair, channelers are pulled by distance

### Expected Blizzlike Behaviour

In Magtheridons Lair, channelers should be ignoring players and being pulled when someone attack them

### Source

Wowhead: https://www.wowhead.com/tbc/es/guide/magtheridons-lair-raid-overview-burning-crusade-classic

### Steps to reproduce the problem

1. .go xyz -99 -8 1 544
2. bodypull channelers

### AC rev. hash/commit

AzerothCore rev. a131d2f7e8de+ 2022-12-12 12:59:07 +0000 (master branch)

### Operating system

Windows 10.0.19044

### Custom changes or Modules

- mod-1v1-arena
- mod-account-achievements
- mod-ah-bot
- mod-anticheat
- mod-autobalance
- mod-bg-reward
- mod-cfbg
- mod-cta-switch
- mod-custom-login
- mod-desertion-warnings
- mod-duel-reset
- mod-dynamic-xp
- mod-eluna
- mod-emblem-transfer
- mod-ip-tracker
- mod-low-level-rbg
- mod-npc-services
- mod-pvp-titles
- mod-pvpscript
- mod-racial-trait-swap
- mod-rdf-expansion
- mod-solo-lfg
- mod-transmog
- mod-weekend-xp
- mod-world-chat

**Comment by Santaria94** [comment]
I confirm. Players should be able to take positions in the room before the start of the fight.
https://www.youtube.com/watch?v=PVL-m0CvfI0
