### ISSUE TITLE
[Hellfire Peninsula] NPC - Arzeth the Merciless 

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#14331]
### Current Behaviour

If you use the Staff of the Dreghood Elders and kill Arzeth, then the next time he spawns, he will appear without using his waypoints.
https://www.wowhead.com/item=29513/staff-of-the-dreghood-elders
https://www.wowhead.com/npc=19354/arzeth-the-merciless

### Expected Blizzlike Behaviour

Should correctly use waypoints after respawning

### Source

https://www.wowhead.com/npc=19354/arzeth-the-merciless
https://www.youtube.com/watch?v=7Vjug-aByEM

### Steps to reproduce the problem

.quest add 19354
.go cr 69051
use Staff of the Dreghood Elders from quest
.damage 100000
.resp

### Extra Notes

Original report: https://github.com/chromiecraft/chromiecraft/issues/4619

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Windows 10 x64

**Comment by avarishd** [comment]
When he REspawns he doesn't follow the path, until a combat update, regardless if he was killed with or without the staff.
Also his path should end at 10, rest of the points are duplicates.
 ```sql
 SELECT * FROM waypoint_data WHERE id=690510 
 ```
