### ISSUE TITLE
Halaa mechanics not working properly

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#14355]
CC report https://github.com/chromiecraft/chromiecraft/issues/4642 confirmed on my local c05c45c51d3d

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

1. Able to capture Halaa with guards alive
2. Fire Bomb dot does not work
![image](https://user-images.githubusercontent.com/68164076/209406226-313d1499-26ec-4bf6-bb1b-e244a2f0d0e0.png)
3. No announcement that "Halaa is defenseless!"

### Expected Blizzlike Behaviour

Alive guards block capturing Halaa
Fire Bombs should also leave a dot that deals 1% of the targets damage per second
Once all gaurds are dead an announcement should be made that "Halaa is defenseless" allowing the capture bar to move.

### Source
https://youtu.be/3H0dqAzcnS4?t=156
https://wowpedia.fandom.com/wiki/Halaa
> Once all 15 NPC defenders are dead, a LocalDefense/WorldDefense message "Halaa is defenseless!" signifies that Halaa may be captured by having more players than the opposing faction on the plateau itself. 

Bomb text itself
![image](https://user-images.githubusercontent.com/50233983/208964498-d8eeccec-d704-490f-865b-b17044290b47.png)

### Steps to reproduce the problem

.tele halaa as alliance and flag to cap
Switch to horde
.go gameobject 100342
Cap the Roost
Take a wyvern and attack guards with bombs notice no DOTs
Fly to the center of Halaa to cap it with gaurds still alive
If bored kill the gaurds and notice no announcement that "Halaa is defenseless"

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=24538
Tester notes: Just something odd. Several of the gaurds were "ghosts" on my local but only on aliance, and not every time ( I captured back and forth while testing `.go c 3110499` was one that almost always popped as a ghost.
![image](https://user-images.githubusercontent.com/68164076/209407164-245ca613-a977-446b-9301-7a0a52311365.png)
![image](https://user-images.githubusercontent.com/68164076/209406453-cd86b01c-7571-4894-84c1-a1a560a6dbff.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Valdifer** [comment]
As far i saw, the  Halaani guard of alliance being ghost it always happen with the same model ID
![image](https://user-images.githubusercontent.com/37176834/209815712-6ae62291-c0ee-408c-8c37-d41247b58ac5.png)
Taking a look to the capture point because it should be not capturable and in the code its supposed to be capturable = false but something isnt working ok

**Comment by Tereneckla** [comment]
Yes, all the npcs should switch instantly including guards
That part is working fine right now

**Comment by Valdifer** [comment]
Got the bomb working too, but i have to fix a small thing there

**Comment by Stump876** [comment]
I'm not sure if it's too late to add something to this, so i just opened a new issue. https://github.com/azerothcore/azerothcore-wotlk/issues/15489

**Comment by Valdifer** [comment]
> I'm not sure if it's too late to add something to this, so i just opened a new issue. #15489

No, its not too late Dw, when i finish the hell NPCS patrol (That thing is making my mind blow) i will take a look, but seems to be when the handler player kills gets activated doesnt check zones
