### ISSUE TITLE
Isla Starmane's Cage does not close

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#14352]
Original CC report https://github.com/chromiecraft/chromiecraft/issues/4657 confirmed on my local c05c45c51d3d

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

![image](https://user-images.githubusercontent.com/50233983/209356768-6d62b021-4470-44cf-bb76-bb2c1a6adec9.png)

### Expected Blizzlike Behaviour

The cage should stay open for a while, but should be closed by the time she respawns.

### Source
https://youtu.be/0fj4A4uJo_A
https://wowgaming.altervista.org/aowow/?npc=18760

### Steps to reproduce the problem

.go c 67040
Do the quest/fail the quest/kill her on the quest
Wait

### Extra Notes

Tester notes: 
She will attack the gaurds on respawn causing an endless loop of her dying and respawning because the cage never closes.
![image](https://user-images.githubusercontent.com/68164076/209378252-48010539-98a4-4769-9314-b08ef0147648.png)

While I could not find source on how long the cage stays open, from my research it's been closed every time the quest has been accepted

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Upped the priority since without the cage and npc_flags being reset the nearby mobs will kill Starmane
