### ISSUE TITLE
Feature: port PTR 3.4.1 ulduar item level update

### ISSUE THREAD

**Issue by smellbee** [azerothcore/azerothcore-wotlk#14372]
### Describe your feature request or suggestion in detail

ulduar items have been buffed with level being increased by 6 - 13，up to level 252.

so， is there any way to port this feature？

**Comment by Kitzunu** [comment]
You can change the itemlevel of an item in item_template https://www.azerothcore.org/wiki/item_template#itemlevel

But it will not be done on AC
