### ISSUE TITLE
[Quest] He Will Walk The Earth... missing rewards

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14381]
https://github.com/chromiecraft/chromiecraft/issues/4676
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

No quest rewards
![image](https://user-images.githubusercontent.com/11332559/209694345-75886502-5587-4bb9-9e54-4d418ab55502.png)

### Expected Blizzlike Behaviour

Rewards 
![image](https://user-images.githubusercontent.com/11332559/209694382-f41efe39-05e5-4d08-a003-de23775f1d16.png)

### Source

![image](https://user-images.githubusercontent.com/11332559/209694486-f88271eb-efbe-4ca2-8ded-fe08ff957f2c.png)

https://www.wowhead.com/wotlk/quest=9866/he-will-walk-the-earth#comments:id=25087

### Steps to reproduce the problem

.quest add 9866
.quest complete
.go c id 18067

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Here's the sniff of this quest from Wrath Classic:
```
SMSG_QUERY_QUEST_INFO_RESPONSE
Entry: 9866
Has Data: True
Quest ID: 9866
QuestType: 2 (Normal)
QuestLevel: 67
QuestScalingFactionGroup: 0
QuestMaxScalingLevel: 255
QuestPackageID: 0
QuestMinLevel: 64
QuestSortID: 3518
QuestInfoID: 0 (None)
SuggestedGroupNum: 0
RewardNextQuest: 0
RewardXPDifficulty: 3
RewardXPMultiplier: 1
RewardMoney: 0
RewardMoneyDifficulty: 0
RewardMoneyMultiplier: 1
RewardBonusMoney: 0
[0] (RewardDisplaySpell) SpellID: 0 (0)
[1] (RewardDisplaySpell) SpellID: 0 (0)
[2] (RewardDisplaySpell) SpellID: 0 (0)
RewardSpell: 0
RewardHonor: 0
RewardKillHonor: 0
RewardArtifactXPDifficulty: 0
RewardArtifactXPMultiplier: 1
RewardArtifactCategoryID: 0
StartItem: 0
Flags: 648 (Sharable, ExpansionOnly, HiddenRewards)
FlagsEx: 0 (None)
FlagsEx2: 0 (None)
[0] RewardItems: 0
[0] RewardAmount: 0
[0] ItemDrop: 0
[0] ItemDropQuantity: 0
[1] RewardItems: 0
[1] RewardAmount: 0
[1] ItemDrop: 0
[1] ItemDropQuantity: 0
[2] RewardItems: 0
[2] RewardAmount: 0
[2] ItemDrop: 0
[2] ItemDropQuantity: 0
[3] RewardItems: 0
[3] RewardAmount: 0
[3] ItemDrop: 0
[3] ItemDropQuantity: 0
[0] RewardChoiceItemID: 0
[0] RewardChoiceItemQuantity: 0
[0] RewardChoiceItemDisplayID: 0
[1] RewardChoiceItemID: 0
[1] RewardChoiceItemQuantity: 0
[1] RewardChoiceItemDisplayID: 0
[2] RewardChoiceItemID: 0
[2] RewardChoiceItemQuantity: 0
[2] RewardChoiceItemDisplayID: 0
[3] RewardChoiceItemID: 0
[3] RewardChoiceItemQuantity: 0
[3] RewardChoiceItemDisplayID: 0
[4] RewardChoiceItemID: 0
[4] RewardChoiceItemQuantity: 0
[4] RewardChoiceItemDisplayID: 0
[5] RewardChoiceItemID: 0
[5] RewardChoiceItemQuantity: 0
[5] RewardChoiceItemDisplayID: 0
POIContinent: 0
POIx: 0
POIy: 0
POIPriority: 0
RewardTitle: 0
RewardArenaPoints: 0
RewardSkillLineID: 0
RewardNumSkillUps: 0
PortraitGiver: 0
PortraitGiverMount: 0
PortraitGiverModelSceneID: 0
PortraitTurnIn: 0
[0] RewardFactionID: 941
[0] RewardFactionValue: 3
[0] RewardFactionOverride: 0
[0] RewardFactionCapIn: 7
[1] RewardFactionID: 0
[1] RewardFactionValue: 0
[1] RewardFactionOverride: 0
[1] RewardFactionCapIn: 7
[2] RewardFactionID: 0
[2] RewardFactionValue: 0
[2] RewardFactionOverride: 0
[2] RewardFactionCapIn: 7
[3] RewardFactionID: 0
[3] RewardFactionValue: 0
[3] RewardFactionOverride: 0
[3] RewardFactionCapIn: 7
[4] RewardFactionID: 0
[4] RewardFactionValue: 0
[4] RewardFactionOverride: 0
[4] RewardFactionCapIn: 7
RewardFactionFlags: 0
[0] RewardCurrencyID: 0
[0] RewardCurrencyQty: 0
[1] RewardCurrencyID: 0
[1] RewardCurrencyQty: 0
[2] RewardCurrencyID: 0
[2] RewardCurrencyQty: 0
[3] RewardCurrencyID: 0
[3] RewardCurrencyQty: 0
AcceptedSoundKitID: 890
CompleteSoundKitID: 878
AreaGroupID: 0
TimeAllowed: 0
ObjectiveCount: 0
AllowableRaces: 32767
TreasurePickerID: 0
Expansion: 1
LogTitle: He Will Walk The Earth...
LogDescription: Deliver the news to Farseer Corhuk at Garadar.
QuestDescription: Will you do me one last honor, $N? I do not wish to return to Garadar. I believe that my destiny lies elsewhere - that I will serve a greater purpose someday.$B$BPlease, return to Farseer Corhuk and tell him that I will not be returning. That I cannot return. I must walk the earth... He will understand.
AreaDescription: 
PortraitGiverText: 
PortraitGiverName: 
PortraitTurnInText: 
PortraitTurnInName: 
QuestCompletionLog: 
```

Shows nothing in terms of item rewards.

**Comment by BeefSteaker** [comment]
Found this vid from WoD that shows them still available https://youtu.be/Df4vS74ud-o?t=49

Would be weird if they removed only to add again. I'd check classic, but I don't have access to my pc till the new year

**Comment by heyitsbench** [comment]
> I'd check classic, but I don't have access to my pc till the new year

I can give it a look later this week on the PTR, it'd be quite odd if the sniffs didn't line up in-game, but that'd be knowledge to keep in mind for later. 🤔

**Comment by Ovahlord** [comment]
Flags: 648 (Sharable, ExpansionOnly, HiddenRewards)  the rewards are hidden according to the flags so the items you get from it seem to be not sent by retail. I've verified these fields with a cataclysm sniff as well. so yeah. either we're on the wrong quest or the rewards are serverside

**Comment by Sneften** [comment]
I tested on classic and the rewards you mention in the post are avalible. 👍

**Comment by heyitsbench** [comment]
> Flags: 648 (Sharable, ExpansionOnly, HiddenRewards) the rewards are hidden according to the flags so the items you get from it seem to be not sent by retail. I've verified these fields with a cataclysm sniff as well. so yeah. either we're on the wrong quest or the rewards are serverside

Thank you, didn't know that flag even existed. 😛

**Comment by neifion-00000000** [comment]
recently did a full nagrand let me check
