### ISSUE TITLE
Ticket closed by console will result in closedBy/resolvedBy value of 16777215

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1438]
##### DESCRIPTION:

The current core code tries to put `-1` as `resolvedBy` and `closedBy` columns of the `gm_ticket` table whenever a ticket is closed not by a GM player but via the `worldserver` console.

This will result in having the value `16777215` in those columns instead of the expected `-1` value.

Can be confusing if you already have a player with such guid.

##### CAUSE OF THE ISSUE:

The cause of the issue is that on AzerothCore we have those fields as `UNSIGNED`. So they cannot be lower than 0.

##### BEHAVIOUR IN TC:

In TrinityCore those columns are **NOT** unsigned (so they are signed).

However I think that **just putting those columns as signed could be wrong too**.

Simply because they are supposed to match with the GUID of the player (`characters.guid`) which is `guid` INT(10) UNSIGNED` (max possible value is `4.294.967.295`).

If we put those columns as signed, their maximum value will lower to `2.147.483.647` and might be an issue if there are characters with a guid higher than that number.

![image](https://user-images.githubusercontent.com/75517/52521014-0e0a6680-2c71-11e9-8da8-3e272b844633.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Open a ticket
2. Close it using the `worldserver` console with the command `ticket close ID_TICKET`
3. Check `gm_ticket` table

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/0c71d0e56ee12c241bc4028258275b2ddd7636db

##### OPERATING SYSTEM:

Ubuntu 18.04 (64 bit)

##### MODULES:

No modules

##### OTHER CUSTOMIZATIONS:

No customizations

**Comment by JamesGent** [comment]
Can confirm still acts in this way. I show in the screenshot one ticket opened by a character & closed by a character, and then a ticket opened/closed by the console.

![Desktop 27-11-2020 18-22-21-611](https://user-images.githubusercontent.com/61194190/100476456-89a30500-30dd-11eb-9a9c-1e82318a8eaa.png)
