### ISSUE TITLE
Polymorph and Seduction duration in PvP

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14386]
Original issue: https://github.com/chromiecraft/chromiecraft/issues/4258

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Polymorph lasting 10 seconds in pvp - tested in arathi basin, on my local server

### Expected Blizzlike Behaviour

It should last 8 seconds

### Source

https://wowwiki-archive.fandom.com/wiki/Diminishing_returns

https://www.wowhead.com/guide/diminishing-returns-in-pvp-6024

### Steps to reproduce the problem

1. Join a battleground
2. Have an enemy Mage use Polymorph on you
3. Check duration

### Extra Notes

Seduction's Succubus has the same behaviour

### AC rev. hash/commit

3b5ceb43636a 2022-12-25

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
if you open the history of the article and go back before cata release date (before december 2010), it is stated that poly and seduction are 10 seconds.
https://wowwiki-archive.fandom.com/wiki/Diminishing_returns?oldid=2366039

**Comment by balleny** [comment]
https://youtu.be/EzJt1m5VEXA?t=58

seems like an invalid ticket to me

**Comment by sassouiabd** [comment]
invalid to me too, those CC are 10 sec in wrath : 
Mage: https://youtu.be/QOsL3oT6zTU?t=45
Shamen Hex: https://youtu.be/QOsL3oT6zTU?t=14

Issue to close.
