### ISSUE TITLE
[QUEST] The Shimmering Frond

### ISSUE THREAD

**Issue by Azzaleo** [azerothcore/azerothcore-wotlk#1439]
DESCRIPTION:

The quest [The Shimmering Frond] is acceptable in Horde side [ID: 931]

EXPECTED BLIZZLIKE BEHAVIOUR:

Horde players can't accept this quest.

CURRENT BEHAVIOUR:

It's possible accept the quest but (obviously) it's not possible to deliver it, because you have to speak with an Ally NPC.

STEPS TO REPRODUCE THE PROBLEM:

1- .go 10849 2053 1327 1
(with an Horde player)

2- You can accept the quest but (obviously) you can't deliver it (because the NPC is Ally, like the quest)

https://wowwiki.fandom.com/wiki/Quest:The_Shimmering_Frond

BRANCH(ES):
staging

AC HASH/COMMIT:
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by comix1988** [comment]
confirm
https://wowwiki.fandom.com/wiki/Quest:The_Shimmering_Frond

![cattura](https://user-images.githubusercontent.com/22867608/52522770-03a89680-2c8a-11e9-8d50-68c47ba0cc97.PNG)
