### ISSUE TITLE
[quest] `The Fate Of The Fallen` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#14395]
### Current Behaviour

`The Fate Of The Fallen` quest cannot be completed

### Expected Blizzlike Behaviour

quest can be completed

https://www.youtube.com/watch?v=a9NMWtdHPxk

### Steps to reproduce the problem

1.  `.q a 14107`
2.  `.go xyz 7856.000488 2170.591797 370.094208 571`
3.  `.additem 47035`
4. Use `Light-Blessed Relic` for `Fallen Hero's Spirit`

### AC rev. hash/commit

48ab864b98de6551d7317b6e7b613f231fd5155b

### Operating system

Ubuntu20.04

**Comment by mpfans** [comment]
@UltraNix  tyvm

**Comment by heyitsbench** [comment]
Can confirm, quest credit is not given when using the item on the creatures.
