### ISSUE TITLE
Wrathguard Flame Wave is not scripted

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#14397]
https://github.com/chromiecraft/chromiecraft/issues/4678

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

When Wrathguards use Flame Wave they just put a patch of fire under their feet

### Expected Blizzlike Behaviour

Flame Wave is a spell with cast time that creates a line of fire in front of the Wrathguard

### Source

https://youtu.be/E1i84M1aupY?t=33
https://www.wowhead.com/wotlk/npc=18975/wrathguard#comments:id=81324

### Steps to reproduce the problem

Engage one and wait for it to use the spell

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=18975

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/790f444ffac09bfb9193fbd18aa7c2d730a02600

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
This is what the waypoints for Flame Wave looks like:
![image](https://user-images.githubusercontent.com/100873791/209903262-eecaf749-ce0f-44a5-9cc6-aeddaafb0338.png)

**Comment by Gultask** [comment]
I'll see if I can do something in SAI later today.

**Comment by Samsequel** [comment]
There is another spell that triggers a creature that would cast the spell on itself, so basically we spawn those triggers in coordinates + path and let the creature use the current spell and be done :3

**Comment by Gultask** [comment]
It's not a set path/coords. It can be cast anywhere

**Comment by Sneften** [comment]
[#4718](https://github.com/chromiecraft/chromiecraft/issues/4718) linking this issue here aswell. Same spell, same problem.
