### ISSUE TITLE
[QUEST] "A Pawn on the Eternal Board" some bugs

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1442]
**DESCRIPTION:**

Quest "A Pawn on the Eternal Board" has a some bugs:
1- it's impossible to complete;
2- has various graphic bugs;

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The quest is part of a long chain of the Brood of Nozdormu faction. it's simple to complete, you just have to watch an animation outside the doors of Ahn'Quiraj and then deliver it.

https://www.youtube.com/watch?v=YL4YQWtK5Ao   example 1
https://www.youtube.com/watch?v=V_wU8PhIIWU    example 2

**CURRENT BEHAVIOUR:**
I try to expose the various bugs:
1- the conversation in the movie does't get to the end, it ends at this point "The sands of time will halt, but only for a moment! I will conjure the barrier."This does't allow the quest to complete.

![discorso](https://user-images.githubusercontent.com/22867608/52532293-ab71a300-2d22-11e9-8250-dc125cb46922.png)

2- visually the dragons fly incorrectly, you need to review the waypoints;
3- visually the dragon spells don't apply anything to the mobs;
4- visually the gate door of Ahn'Quiraj does't appear;

https://youtu.be/I4zavAx4XdQ video link

**STEPS TO REPRODUCE THE PROBLEM:**

1- .modify reputation 910 42000
2- .quest add 8303
3- .go -8234 -4640 2.3 1  complete quest and take "long forgotten memories" quest
4- .go -8027 1542 2.6 1 complete quest and take "A Pawn on the Eternal Board"  quest
5- wait for the end of the movie

**BRANCH(ES):**
staging

**AC HASH/COMMIT:**
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

**OPERATING SYSTEM:**
linux

**MODULES:
OTHER CUSTOMIZATIONS:**

**Comment by StygianTheBest** [comment]
Duplicate

- https://github.com/azerothcore/azerothcore-wotlk/issues/543
