### ISSUE TITLE
[Dragonblight] Seeds of the Lashers - Quest

### ISSUE THREAD

**Issue by FallenDev** [azerothcore/azerothcore-wotlk#14431]
### Current Behaviour

Npc sends you to Emerald Dragonshrine to hunt for Lasher Seeds. 
Lasher Seeds should drop from mobs, but after hunting thirty Lashers none have dropped.

### Expected Blizzlike Behaviour

Npc sends you to Emerald Dragonshrine to hunt for Lasher Seeds. 
Lasher Seed quest item should drop from mobs, and be apart of their loot table while on "Seeds of the Lashers" questline.

### Source

Comment Section here: https://www.wowhead.com/wotlk/quest=12458/seeds-of-the-lashers#comments players have mentioned you should be able to complete the quest in approximately 5 kills. (Drop rate: 1 almost every to every other kill; 60 - 70%?)

### Steps to reproduce the problem

1. Accept Questline from Lord Itharius at Wyrmrest Temple
2. Travel to Emerald Dragonshrine
3. Kill Emerald Lashers
4. Loot Emerald Lashers

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/7fa0aeeca7418e5b4fc75e4d895189008c3d7b5e

### Operating system

Windows 11 x64

### Custom changes or Modules

mod-autobalance
mod-ah-bot
mod-solo-lfg
mod-anticheat
mod-solocraft

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/210914708-e396ca04-b996-4a91-804c-b8af8d01035a.png)

works
