### ISSUE TITLE
Spiritual Attunement does not work with every heal (Paladin)

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14430]
### What client do you play on?

deDE - enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour
Spiritual Attunement does not work properly with every heal. During testing some heals worked sometimes and sometimes not:
- When overhealed it does not give mana back even for the effective healed value. 
- Certain heals did not seem to give any mana back at all but might have been an issue with the testing method.

### Expected Blizzlike Behaviour

Spiritual Attunement is a passive ability from talents:
"A passive ability that gives the Paladin mana when healed by other friendly targets' spells.  The amount of mana gained is equal to 5% (10% rank 2) of the amount healed."
It should proc from all heals, the amount of mana gained is only coming from effective healed value. This includes heals in which some of the heal is healed effectively and some overhealed.

### Source

https://www.wowhead.com/wotlk/spell=31785/spiritual-attunement
https://www.wowhead.com/wotlk/spell=31785/spiritual-attunement#comments:id=314925:reply=65307

### Steps to reproduce the problem

1. Have a Paladin with Protection specialization with Spiritual Attunement (1/2 or 2/2).
2. Take damage, burn some mana (get into combat) and enable floating combat text for easier visualization (take care to not use abilities that could give you mana as well (BoS, SoW, JoW)).
3. Have a healer heal you with different heals, sometimes with and without overhealing.
4. Expect mana gain (5-10% of healed value) but mana gain only happens sometimes.
5. Try other mana gain methods which work just fine (Revitalise, Innervate, etc.)

### Extra Notes

I tested the issue in my local server using a priest as "friend healer"
I found this closed issue, maybe it's related https://github.com/azerothcore/azerothcore-wotlk/issues/12362

### AC rev. hash/commit

a2018edade7e 2022-12-29

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Link the the chromie GitHub issue
https://github.com/chromiecraft/chromiecraft/issues/4373
