### ISSUE TITLE
[Dragonblight] Cycle of Life - Quest

### ISSUE THREAD

**Issue by FallenDev** [azerothcore/azerothcore-wotlk#14432]
### Current Behaviour

Npc asks you to kill 5 Emerald Skytalons. 
Killing Emerald Skytalons does not count towards quest.

### Expected Blizzlike Behaviour

After killing a Emerald Skytalon, the quest should add to the counter.

### Source

Here is a breakdown of the quest: https://wowpedia.fandom.com/wiki/Cycle_of_Life 

### Steps to reproduce the problem

1. Accept Questline from Nishera the Garden Keeper within the Emerald Dragonshrine
2. Kill Emerald Skytalons

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/7fa0aeeca7418e5b4fc75e4d895189008c3d7b5e

### Operating system

Windows 11 x64

### Custom changes or Modules

mod-autobalance
mod-ah-bot
mod-solo-lfg
mod-anticheat
mod-solocraft

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/210914631-3757e35b-1089-42f9-8e67-576f60bce2db.png)

works
