### ISSUE TITLE
[Quest] "Trapping the Light Fantastic" does not work

### ISSUE THREAD

**Issue by smellbee** [azerothcore/azerothcore-wotlk#14447]
### Current Behaviour

https://www.wowhead.com/quest=10674/trapping-the-light-fantastic

it used to work 2 years ago, but now quest doesn't work.
After placing a [trap](https://www.wowhead.com/item=30852/multi-spectrum-light-trap) under small lights, nothing happens.

### Expected Blizzlike Behaviour

After placing the [trap](https://www.wowhead.com/item=30852/multi-spectrum-light-trap) under the small lights, they should fly into the [trap](https://www.wowhead.com/item=30852/multi-spectrum-light-trap), and the counter should increase.
This [video](https://youtu.be/9NcGB0hZc00?t=36) shows how the quest should work.

### Steps to reproduce the problem

1.Create an Alliance character
2 .character level 70
3  .go xyz 1910 5562 263 530
4  Complete multiple quests from [Toshley](https://www.wowhead.com/npc=21691/toshley)
5  Take quest [Trapping the Light Fantastic](https://www.wowhead.com/quest=10674/trapping-the-light-fantastic)
6  .go xyz 2712 5306 266 530
7  Use [Multi-Spectrum Light Trap](https://www.wowhead.com/item=30852/multi-spectrum-light-trap)

### AC rev. hash/commit

[https://github.com/azerothcore/azerothcore-wotlk/commit/304ac8fa839b68c684d954332768264bfdbfd7c3](https://github.com/azerothcore/azerothcore-wotlk/commit/304ac8fa839b68c684d954332768264bfdbfd7c3)

### Operating system

debian10

**Comment by stefannovak** [comment]
No longer works again

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/0345f7be-33a7-4c24-b27c-7b26e6364a64" />
