### ISSUE TITLE
Mana Tombs Quest bugged - Someone Else's Hard Work Pays Off

### ISSUE THREAD

**Issue by SimonMakwarth** [azerothcore/azerothcore-wotlk#14442]
### Current Behaviour

When excort is completed Cryo-Engineer Sha'heen despawns and quest is not completed. 

### Expected Blizzlike Behaviour

When excort i done Cryo-Engineer Sha'heen runs out of the Room and quest is completed. 

### Steps to reproduce the problem

1. Obtain quest ‘ Safety Is Job One’
2. Turn in quest inside Mana tombs
3. Start excort quest in question
4. At the end of quest the mob wait for Cryo-Engineer Sha'heen to despawn without completing quest. 

### AC rev. hash/commit

Dunno what this is

### Operating system

Pop!_os Linux distro

**Comment by heyitsbench** [comment]
> Dunno what this is

As the template told you, you get the revision hash from the `.server debug` command. Also, please include a source, even for obvious issues.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/210134567-13dbb5b5-63b7-4574-aa82-0928c953ce1e.png)

It clearly says how to find the information
