### ISSUE TITLE
[Druid] Some idol bugs

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#14479]
https://github.com/chromiecraft/chromiecraft/issues/4073

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Not all of these are currently available, but I did all of them:

Spell Coefficient of the spell does not apply to the spellpower gained by these idols:
https://wowgaming.altervista.org/aowow/?item=45270
https://wowgaming.altervista.org/aowow/?item=46138
https://wowgaming.altervista.org/aowow/?item=40711
https://wowgaming.altervista.org/aowow/?item=25643
https://wowgaming.altervista.org/aowow/?item=27886
https://wowgaming.altervista.org/aowow/?item=22398

Idol adds the specified value to every damage instance of the spell Moonfire:
https://wowgaming.altervista.org/aowow/?item=23197

### Expected Blizzlike Behaviour

Spell Coefficient applies to the idols mentioned

23197 just adds spellpower to the spell (with applying coefficient)

### Source

Tooltip of the Idols
> Increases the spell power of your Spell by X

Spell power is affected by the spell coefficient

### Steps to reproduce the problem

.add 45270
.add 46138
.add 40711
.add 25643
.add 27886
.add 22398
.add 23197

Equip Idol and cast their spell (easiest to see with the lowest rank where the downranking penalty should make it basically null)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/97ec08dc36394b2bc23f26f484ef0a60f81f6c7e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Information source?

**Comment by UltraNix** [comment]
So, these bonuses should be treated as normal spell power(and then only % of these values are taken into the real value)?

**Comment by Tereneckla** [comment]
Yes

**Comment by UltraNix** [comment]
So, e.g. Idol of the Crying Wind gives 374 spell power. Insect Swarm coeff is 0.2 per dot. So 374/7 = 53 * 0.2 = 10.6 --> and this is what is added to IS dot amount.

**Comment by Tereneckla** [comment]
Assuming the person is not suffering from downranking penalties on insect swarm, then yes
The items should just add to the spell power of the spell

Druid with 1000 spell power and crying wind idol has 1374 spell power for the purpose of insect swarm
