### ISSUE TITLE
[Hellfire Ramparts] Omor The Unscarred uses spell Orbital Strike

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14471]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4429

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

[Omor The Unscarred](https://wowgaming.altervista.org/aowow/?npc=17308) casts [Orbital Strike](https://wowgaming.altervista.org/aowow/?spell=30637) while the player is in melee range

![omor](https://user-images.githubusercontent.com/82369562/210220880-3ec65685-e6f0-4761-a47d-908c49e0e4ab.png)

### Expected Blizzlike Behaviour

Omor The Unscarred should not use the spell Orbital Strike

### Source

wotlk 2008 fight:
https://youtu.be/cQ9gO4jeQ7o?t=201
wowhead abilities:
https://www.wowhead.com/wotlk/npc=17308/omor-the-unscarred#abilities;mode:normal

### Steps to reproduce the problem

.go xyz -1197.796997 1678.449707 91.886002 543 0.456575
X: -1197.796997 Y: 1678.449707 Z: 91.886002 Orientation: 0.456575
engage Omor The Unscarred and move to melee
wait for him to cast Orbital Strike

### Extra Notes

aowow:
https://wowgaming.altervista.org/aowow/?npc=17308
https://wowgaming.altervista.org/aowow/?spell=30637
wowhead:
https://www.wowhead.com/wotlk/npc=17308/omor-the-unscarred

### AC rev. hash/commit

3c317c1076d8 2022-12-30

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Santaria94** [comment]
As far as I know, it should toss melee players into the air. But another ability with a similar effect should probably be used.
https://youtu.be/cQ9gO4jeQ7o?t=129 - 2:10 moment on the same video
