### ISSUE TITLE
[server] world carsh 0102

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#14470]
### Current Behaviour

crash log:

[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/10331035/gdb.txt)

crash after a little anticheat report a jail event
![image](https://user-images.githubusercontent.com/33601959/210220351-c339b2e3-bf10-4416-a2ad-20fae2c6f971.png)

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 3c317c1076d8+ 2022-12-30 22:09:06 +0000 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.64-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 44345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2320900760 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-server-auto-shutdown

### Operating system

debian 11 x64

**Comment by Kitzunu** [comment]
Open an issue on anti cheat repo

**Comment by Kitzunu** [comment]
Also dont upload txt files, use Gist

**Comment by acidmanifesto** [comment]
> 
> crash after a little anticheat report a jail event> ![image](https://user-images.githubusercontent.com/33601959/210220351-c339b2e3-bf10-4416-a2ad-20fae2c6f971.png)
> 
Just a small observation from that screenshot the anticheat  is modified on the user end.
