### ISSUE TITLE
[Hunter] Exotic hunter pets are too small

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14488]
https://github.com/chromiecraft/chromiecraft/issues/4742

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Exotic hunter pets are smaller than they should be 
![image](https://user-images.githubusercontent.com/11332559/210378577-e1388ec2-6fdd-4b3f-bec3-627d3c4047b2.png)

### Expected Blizzlike Behaviour

They should be significantly larger

### Source

side effect of:
https://github.com/azerothcore/azerothcore-wotlk/pull/14425

### Steps to reproduce the problem

1. `.learn 1515` `.learn 883` `.learn 2641`
2. `.learn 53270` (Beast Mastery)
3. `.character level 60`
4. `.cheat god` `.go c id 6498`
5. Tame the Devilsaur
6. modify the character level to see if the pet scales accordingly
7. dismiss pet and call it again to see if changes stay
8. dismiss pet, `.save`, logout and log back in to see if changes stay

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/c05c45c51d3d...3ad652d8ab96

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Comparison between max level in AC:
![image](https://user-images.githubusercontent.com/100873791/210414036-de402f4d-03bc-4e67-baaf-332d50412be1.png)

And in Retail:
![image](https://user-images.githubusercontent.com/100873791/210414073-34312bd1-e9a7-4f77-97ac-82fdcb641e81.png)
([source](https://wow.zamimg.com/uploads/screenshots/normal/101490-devilsaur.jpg))

**Comment by Ovahlord** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/f09564b9d01ff372506f76f2345b99e3485738d5  this may solve your problem

**Comment by Kitzunu** [comment]
mm I maybe worked around it
