### ISSUE TITLE
[QUEST] Echeyakee bug

### ISSUE THREAD

**Issue by zato90** [azerothcore/azerothcore-wotlk#1448]
##### SMALL DESCRIPTION:
the mob "Echeyakee" isn't spawned

##### EXPECTED BLIZZLIKE BEHAVIOUR:
the mob can be found to the north-east of The Crossroads
https://wotlk-twinhead.twinstar.cz/?quest=881#.

##### CURRENT BEHAVIOUR:
the mob "echeyakee" cannot be founded in game despite having used the command .go creature.

##### STEPS TO REPRODUCE THE PROBLEM:
.quest add 881
.go 453 -3033
kill "Echeyakee"

##### BRANCH(ES):
staging

##### AC HASH/COMMIT:
commit 987095e

##### OPERATING SYSTEM:
Windows 10

**Comment by wetbrownsauce** [comment]
You have to use the [quest item](https://wotlk-twinhead.twinstar.cz/?item=10327) to spawn Echeyakee. It is not there in the world normally.

**Comment by poszer** [comment]
Like @wetbrownsauce  said, you have to use item to spawn him. Closing
