### ISSUE TITLE
Improve auto import messages for SQL scripts

### ISSUE THREAD

**Issue by Deku** [azerothcore/azerothcore-wotlk#1449]
Currently, the auto import script puts as title "Import pending SQL update file" which makes difficult to find an specific update using the History view in the data/sql folders.

Suggestion: Add the original commit title or hash so it is easier to explore. Example: "Import pending SQL update file from 694b406b8bf339255aeaf1481da027339a9b93e0"

![captura](https://user-images.githubusercontent.com/800655/52587491-efdf6a80-2e18-11e9-8a6b-2f694382421f.PNG)

**Comment by Deku** [comment]
As suggested on Discord, an option would be adding the commit hash using
`git log --diff-filter=A <file.sql> | egrep 'commit*'`

**Comment by BarbzYHOOL** [comment]
very good suggestion

so like this

```
COMMIT_HASH = git log --diff-filter=A <file.sql> | egrep 'commit*'

 - if [ "$TRAVIS_BUILD_ID" = "1" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ -n "$GITHUB_API_KEY" ]]; then git add -A . && git diff --cached --quiet || git commit -am "Import pending SQL update file (commit $COMMIT_HASH)" && git push https://$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_BRANCH; fi
```

?

@Stoabrogga

**Comment by FrancescoBorzi** [comment]
be aware that if an import fails, the next time the bot will run it will import multiple pending files, that possible belonged to different PRs

**Comment by BarbzYHOOL** [comment]
Stoa made a PR for this!
