### ISSUE TITLE
BRD The Imperial Seat - extreme large mob aggro range

### ISSUE THREAD

**Issue by howdya** [azerothcore/azerothcore-wotlk#14492]
### Current Behaviour

Once attack a mob in The Imperial Seat, all the mobs Including the emperor will enter the combat to attack the player. The emperor will yell "Hail to the king, baby!"

### Expected Blizzlike Behaviour

only the mobs nearby should enter the combat.

### Steps to reproduce the problem

1. enter in BRD. 
2. go to The Imperial Seat    .GO XYZ 1379 -723 -92
3. attack one mob.

### AC rev. hash/commit

(https://github.com/azerothcore/azerothcore-wotlk/commit/3ad652d8ab96b6d9cefe9c998bc6d19b1d448e18 2023-01-03)

### Operating system

UBUNTU 20.04

**Comment by Gultask** [comment]
Which mob in particular? They could be in a formation that includes the Emperor.

**Comment by howdya** [comment]
Not a particular mob but any mob in The Imperial Seat area

**Comment by Gultask** [comment]
Oh I see it now. Yeah that's bad.

**Comment by Gultask** [comment]
Thanks for the report, howdya!
