### ISSUE TITLE
Cannot loot Copper or Silver in Dungeons

### ISSUE THREAD

**Issue by xnartan** [azerothcore/azerothcore-wotlk#14499]
### Current Behaviour

I am not receiving any Copper or Silver when looting mobs in Dungeons.
I have tried in Ragefire Chasm and The Deadmines.

### Expected Blizzlike Behaviour

I should receive the copper or silver from the dead mob.

### Steps to reproduce the problem

1. Go into a dungeon
2. Kill a mob
3. loot the mob
4. Check to see if the copper or silver was received

### AC rev. hash/commit

fb08f8e905b9

### Operating system

Ubuntu 20.04.5 LTS

**Comment by Valdifer** [comment]
When you mean killing, you killing with gm command .die or killing them normal kill?

**Comment by xnartan** [comment]
normal kill, in combat.

**Comment by Gultask** [comment]
Could you record a video? I've never heard of this happening before. And the servers running the latest revision seem fine.

**Comment by xnartan** [comment]
https://user-images.githubusercontent.com/121960688/210669515-33a6482d-5aa0-4253-ad90-a958197fda41.mp4

**Comment by ZhengPeiRu21** [comment]
Are you using any modules? One user recently was mention a similar issue when using the auto-balance module.

**Comment by xnartan** [comment]
I am not using any modules.

**Comment by Kitzunu** [comment]
Your core is from November closing as outdated and can't reprodyce on latest rev. Update to latest and try again.
