### ISSUE TITLE
[ITEM] Activation Crystals - The Violet Hold

### ISSUE THREAD

**Issue by FedeFlag** [azerothcore/azerothcore-wotlk#1450]
SMALL DESCRIPTION:

The Violet Hold crystals not working correctly

EXPECTED BLIZZLIKE BEHAVIOUR:

Source WowWiki: "Using them will activate the defense systems and kill off most mobs", Not using these while in heroic mode will award the achievement Money achievement Defenseless, so long as prison seal integrity is at 100% as well"

Many times these crystals are used vs "Ichoron" Boss (for shot trashes going to the boss)

CURRENT BEHAVIOUR:

Using one "Activation Crystal" now = Do 13k damage for trash (really useless to use)

STEPS TO REPRODUCE THE PROBLEM:

1. Enter "The Violet Hold" dungeon located on Dalaran (or .tele Violethold)
2. Start the Dungeon speaking with "Lieutenant Sinclari" (and activating the crystals by selecting on the first entry)
3. Wait for the first wave of trash and press on one of the clickable crystals around the room.

EXTRA NOTES:

Link: https://wowwiki.fandom.com/wiki/Activation_Crystal

BRANCH(ES):
staging

AC HASH/COMMIT:
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by Kitzunu** [comment]
I cannot find anything that suports that these should one shot creatures. All I can find is

> Activating a crystal will hit each mob with Arcane Lightning for 13000 Arcane damage on normal difficulty.
https://wowwiki.fandom.com/wiki/Defense_Control_Crystal

**Comment by Knindzagxg** [comment]
Personal experience -> They should kill all small trash mobs, and double will kill Guardians.

Also, you can find more info on wiki, for Original Violet Hold.

"Note: if you are having trouble downing the mobs, there are Defense Control Crystals located on the walls around the room. Activating one of these crystals will damage all the mobs in the room, killing all but bosses or portal keepers. Each crystal can be used only once. "

https://wowwiki.fandom.com/wiki/Violet_Hold_(original)

**Comment by Kitzunu** [comment]
Ah didnt find that page :D

**Comment by Knindzagxg** [comment]
There was a lot of changed / modifications on wiki pages xP
That's why i always check Original unless i remember how it worked 10 years ago xD

**Comment by Kitzunu** [comment]
Haha yea, I didnt even know there was a version like that :P

Anyhow I am working on it now

**Comment by Kitzunu** [comment]
This is what I got so far
```sql
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 30837);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(30837, 0, 0, 0, 1, 0, 100, 0, 4000, 4000, 1000, 1000, 0, 11, 57930, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Defense System - Out of Combat - Cast \'Arcane Lightning\''),
(30837, 0, 1, 0, 1, 0, 100, 2, 4000, 4000, 0, 0, 0, 11, 58152, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Defense System - Out of Combat - Cast \'Arcane Lightning\' (Normal Dungeon)'),
(30837, 0, 2, 0, 1, 0, 100, 2, 4000, 4000, 1000, 1000, 0, 11, 57912, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Defense System - Out of Combat - Cast \'Arcane Lightning\' (Normal Dungeon)');
```
What I don't understand is why the creature is ignoring the repeat cast of spell 57912, I have it to repeat every 1s, but it don't just ignores it

**Comment by Knindzagxg** [comment]
Think it have be done via cpp.

All small adds should die instant, and if we try to repeat, we might get issue with Guardian or Boss.

**Comment by Kitzunu** [comment]
Nah, it is easy to restrict via Conditions, the only issue is that the one spell that should be cast on Guardians and Portal Keepers is not recasting X  times to get them to 50% HP

**Comment by Ragelezz** [comment]
Still buggy ? Also this should be done (if its still available) via cpp not db since its instance script related.
