### ISSUE TITLE
Core/Vehicle  HandleChangeSeatsOnControlledVehicle

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#14516]
### Current Behaviour

error HandleChangeSeatsOnControlledVehicle, Opcode: 1179, Player 6 tried to switch seats but current seatflags 1662027787 don't permit that.

### Expected Blizzlike Behaviour

Single person can switch to co pilot to use anti-aircraft guns

### Steps to reproduce the problem

1: .npc add temp 33109
2: Click the co pilot

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8d2dda24ed85e835953156d1df429567bfc6fea8

### Operating system

windows 10

**Comment by w5860363** [comment]
Still occurring in ULDs

**Comment by sogladev** [comment]
Removing these lines in `SpellInfoCorrections` enables swaps again

Not sure why these were disabled, maybe to prevent a crash?

```
diff --git a/src/server/game/Spells/SpellInfoCorrections.cpp b/src/server/game/Spells/SpellInfoCorrections.cpp
index 0e3c9833a..de6e0735c 100644
--- a/src/server/game/Spells/SpellInfoCorrections.cpp
+++ b/src/server/game/Spells/SpellInfoCorrections.cpp
@@ -4960,6 +4960,2 @@ void SpellMgr::LoadSpellInfoCorrections()
     vse->m_flags &= ~VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE;
-    vse = const_cast<VehicleSeatEntry*>(sVehicleSeatStore.LookupEntry(3011)); // Salvaged Demolisher, Ulduar - not allow to change seats
-    vse->m_flags &= ~VEHICLE_SEAT_FLAG_CAN_SWITCH;
-    vse = const_cast<VehicleSeatEntry*>(sVehicleSeatStore.LookupEntry(3077)); // Salvaged Demolisher Seat, Ulduar - not allow to change seats
-    vse->m_flags &= ~VEHICLE_SEAT_FLAG_CAN_SWITCH;
```
