### ISSUE TITLE
Visual studio compile error

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#1451]
##### SMALL DESCRIPTION:
After https://github.com/azerothcore/azerothcore-wotlk/commit/d4ab165888cafeb6c568fbd9eb8306e30c9228bf I get an error compiling in Visual Studio 2017.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The core compiles correctly.

##### CURRENT BEHAVIOUR:
I get the following error compiling the core. I tried deleting my local repository and making a fresh clone but still got the same.
![error](https://user-images.githubusercontent.com/25745474/52629196-721f6b80-2eb9-11e9-98e5-aa5f8b908282.png)

I'm using..
Visual Studio Community 2017, version 15.5.6 (details in the code below).
CMake 3.11.0
OpenSSL 1.0.2n
MySQL 5.6.39 - InnoDB
Windows 10

```
Microsoft Visual Studio Community 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA657
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA657
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA657
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/d4ab165888cafeb6c568fbd9eb8306e30c9228bf

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
VAS Autobalance and Individual XP, though I've tried without and got the same error.

##### OTHER CUSTOMIZATIONS:
None

**Comment by FrancescoBorzi** [comment]
@Trystanosaurus @maikale 

can you please let me know if this solves your issue? https://github.com/azerothcore/azerothcore-wotlk/pull/1455

I cannot reproduce since I'm not on Windows

**Comment by maikale** [comment]
> @Trystanosaurus @maikale
> 
> can you please let me know if this solves your issue? #1455
> 
> I cannot reproduce since I'm not on Windows

oke wait

**Comment by Trystanosaurus** [comment]
I've just had a go now and it seems to compile and run properly now.

**Comment by maikale** [comment]
> > @Trystanosaurus @maikale
> > can you please let me know if this solves your issue? #1455
> > I cannot reproduce since I'm not on Windows
> 
> oke wait

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file '..\scripts\Release\scripts.lib'	worldserver	C:\Users\PC\Desktop\Build2\src\server\worldserver\LINK	1	
Warning	C4715	'WorldSocket::ProcessIncoming': not all control paths return a value	game	c:\users\pc\desktop\azerothcore-wotlk-master\src\server\game\server\worldsocket.cpp	724

**Comment by FrancescoBorzi** [comment]
@maikale are you trying that PR? can you post the full error?

**Comment by FrancescoBorzi** [comment]
@maikale please update to latest `master` and do a **clean** compile.

If you still have this problem, please open a new issue and include the full error that you get.

Thank you.

**Comment by maikale** [comment]
> @maikale please update to latest `master` and do a **clean** compile.
> 
> If you still have this problem, please open a new issue and include the full error that you get.
> 
> Thank you.

Now works thanks.

**Comment by CyberMist2** [comment]
I have same issue on windows 10 64bit

**Comment by Winfidonarleyan** [comment]
Try preview `16.6.0`
![image](https://user-images.githubusercontent.com/18329778/81469636-43a15500-9210-11ea-891e-d55a6786067a.png)
