### ISSUE TITLE
Unable to switch the region while the battle is in progress

### ISSUE THREAD

**Issue by SliderBeen** [azerothcore/azerothcore-wotlk#14521]
### Current Behaviour

boss_sartharion, the player will enter the dungeon after death, release the corpse to re-enter the dungeon, and prompt that the region cannot be switched during the battle

### Expected Blizzlike Behaviour

the player can  enter the dungeon after death

### Steps to reproduce the problem

1.start battle with boss_sartharion
2.enter the portal
3.player die
4.release the corpse to re-enter the dungeon

### AC rev. hash/commit

no

### Operating system

ubuntu 20.0.4

**Comment by Kitzunu** [comment]
Add hash/commit.

**Comment by SliderBeen** [comment]
update hash/commit.
