### ISSUE TITLE
Blazing speed doesn't proc with absorb shield active

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14524]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4510

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

At the moment the mage fire tree talent [Blazing Speed[(https://www.wowhead.com/wotlk/spell=31642/blazing-speed) only procs when being hit without an absorb shield active. Massive negative implications for pvp. 

### Expected Blizzlike Behaviour

Blazing speed should proc even with an active absorb shield (mana shield etc.).

### Source

- Tested with large groups of npcs (~20) hitting the mage with an absorb shield active - no blazing speed procs in 5 minutes.
- https://www.wowhead.com/wotlk/spell=31642/blazing-speed#comments

### Steps to reproduce the problem

Test melee and ranged hits on a mage with the blazing speed talent and an active damage absorb shield.

### Extra Notes

Doesn't work either with [Power Word: Shield](https://www.wowhead.com/spell=27607/power-word-shield)
Tested in my local server during pvp

### AC rev. hash/commit

8d2dda24ed85 2023-01-06

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14254
