### ISSUE TITLE
Map BattleGround Warsong Gulch  you can shoot spells through the central mountains and rocks

### ISSUE THREAD

**Issue by Fireevil** [azerothcore/azerothcore-wotlk#14529]
### Current Behaviour

Map Warsong Gulch you can shoot spells through the central mountains and rocks
![54495-garganta-grito-de-guerra](https://user-images.githubusercontent.com/88008285/211110616-38d1a2fc-2d37-4db4-94f5-7ad0cd905164.jpg)

### Expected Blizzlike Behaviour

You shouldn't be able to apply spells to a player through an obstacle.

### Steps to reproduce the problem

1- begin the bg Warson Gulch
2-try to attack through the rock or mountain
3- you can attack your rival through the mountain or rock 

### AC rev. hash/commit

commit = b89eea6 
b89eea668a28f608b71cc4289bc2d76b237fe294

### Operating system

Windows 10 x64

### Custom changes or Modules

none

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/apps/worldserver/worldserver.conf.dist#L403

**Comment by heyitsbench** [comment]
Unless you have a legitimate source saying otherwise, this is blizzlike, and has already been documented as such.

**Comment by Fireevil** [comment]
I have it activated but continue with the bug

**Comment by heyitsbench** [comment]
> I have it activated but continue with the bug

Read the description of the config; set it to 0 to not allow spells to pass through objects.

**Comment by Fireevil** [comment]
aaa ok ok thank you very much for your answer
