### ISSUE TITLE
[pet] Hunter pet is too big

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#14525]
### Current Behaviour

updated this commit https://github.com/azerothcore/azerothcore-wotlk/commit/8d2dda24ed85e835953156d1df429567bfc6fea8
 Hunter pet is too big

![GN}@A`0I4_C1(MZS%WE3(OL](https://user-images.githubusercontent.com/18187177/211024040-efc2dfd9-2c4e-4f53-96e8-a3cd2440b55e.jpg)

### Expected Blizzlike Behaviour

Hunter pets should not be so big

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8d2dda24ed85e835953156d1df429567bfc6fea8

### Operating system

Ubuntu20.04

**Comment by Kitzunu** [comment]
Ah big bear.
Ok so this needs finetuning

**Comment by mpfans** [comment]
Many pets are too big, such as spiders and crabs

**Comment by Kitzunu** [comment]
test this https://github.com/azerothcore/azerothcore-wotlk/pull/14526

**Comment by mpfans** [comment]
> test this #14526

Because there are too many online players, it needs to be tested when the next crash occurs

**Comment by Kitzunu** [comment]
Ok, I tested myself and all pets are the old sizes again except for the Exotic pets, which the original issue was about

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/211031782-353d0856-2422-4ea8-a09f-9b0239ca60d5.png)

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/211031958-d4956b56-3316-4ce3-889b-b2e7957aa3ee.png)

**Comment by YinDeGuan** [comment]
> ![image](https://user-images.githubusercontent.com/24550914/211031958-d4956b56-3316-4ce3-889b-b2e7957aa3ee.png)

bro , How can a hunter bring more than one pet? Modules or configurations?
