### ISSUE TITLE
Karazhan: Boss Midnight's damage  is error.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#14571]
### Current Behaviour

arazhan: Boss Midnight.  the id 15550 and 16152 .   the boss damage  20000.  the player hp is 14000 in level 70.

### Expected Blizzlike Behaviour

the damage is correct.

### Steps to reproduce the problem

.tele kara

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6 2022-12-02

### Operating system

ubuntu 20.4

**Comment by Nefertumm** [comment]
Duplicated and https://github.com/azerothcore/azerothcore-wotlk/issues/15837 has more info about it.
