### ISSUE TITLE
boss_volazj bug

### ISSUE THREAD

**Issue by SliderBeen** [azerothcore/azerothcore-wotlk#14574]
### Current Behaviour

after boss_volazj cast Insanity, it will not  enter to insanity phase

### Expected Blizzlike Behaviour

after boss_volazj cast Insanity, it will enter to insanity phase

### Steps to reproduce the problem

1. go to the boss_volazj 
2. enter combat
3. attack boss and wait boss cast insanity

### AC rev. hash/commit

[3442463](https://github.com/azerothcore/azerothcore-wotlk/commit/cdcb0ceff7249e072d53c6e4a4f2460ff3442463)

### Operating system

ubuntu 20.0.4

**Comment by avarishd** [comment]
duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7796
