### ISSUE TITLE
Feature: get automatically the data version

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#14575]
### Describe your feature request or suggestion in detail

related of https://github.com/azerothcore/azerothcore-wotlk/pull/14527
we should create a bash script which via github API gets automatically the last data version present in the wowgaming client-data release

**Comment by Yehonal** [comment]
This is not really a good idea because you could download then a version that is not supported by the revision you are using (let's say that you have not updated your core yet).

I would instead define it somewhere in the acore.json we have in the root folder and use it. To have everything in one place.
We can even implement that logic with Deno that is easier to read the json

**Comment by heyitsbench** [comment]
> This is not really a good idea because you could download then a version that is not supported by the revision you are using (let's say that you have not updated your core yet).

I'm admittedly speaking as a bit of a novice here, but couldn't you grab the version as defined by your core's [mmap version](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/common/Collision/Maps/MapDefines.h#L16)?

**Comment by Yehonal** [comment]
> > This is not really a good idea because you could download then a version that is not supported by the revision you are using (let's say that you have not updated your core yet).
> 
> I'm admittedly speaking as a bit of a novice here, but couldn't you grab the version as defined by your core's [mmap version](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/common/Collision/Maps/MapDefines.h#L16)?

For such operations we normally use bash/deno, we can't access to that value directly (unless you parse c++ or you move that value out of c++ in something like json/yml). An alternative would be to rewrite it in C++ and include it within the core and as a standalone tool, similar to what we've done with the db assembler. In any case, we need to refer to a static value

**Comment by Kitzunu** [comment]
Easiest solution:

1. Extract the data yourself
2. Download it from the link.

Updating the script everytime isnt needed, just a "nice to have" for those that are lazy
