### ISSUE TITLE
All disarm effects leave target with no shield

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14578]
https://github.com/chromiecraft/chromiecraft/issues/4787
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Several disarm effects remove shield/off hand when they shouldnt

### Expected Blizzlike Behaviour

Shield generally shouldnt be disarmed, unless specified by the spell description.

### Source

https://www.mmo-champion.com/threads/653814-Hunter-Disarm-bugged -> please see mention: "How do we put this blizzard has given disarm to fire mages/rogues/warriors/spriests and if im not mistaken all disarm ranged wpns included but doesnt touch the off hand accept for rogues disarm."

https://wotlkdb.com/?spell=676
![image](https://user-images.githubusercontent.com/11332559/211320803-75e557f0-9268-4591-a7a0-8996bfcf7e28.png)

https://wotlk.evowow.com/?spell=51722
https://wotlk.evowow.com/?spell=53209
https://www.wowhead.com/wotlk/spell=64044/psychic-horror
https://wotlk.evowow.com/?spell=64353

### Steps to reproduce the problem

1. have MH + shield
2. get disarmed by spell such as 676
3. Note shield is also disarmed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
`ID - 51722 Dismantle`
`Description: Disarm the enemy, removing all weapons, shield or other equipment carried for $d.`
Description is clear.

`ID - 676 Disarm
Description: Disarm the enemy's main hand and ranged weapons for $d.`
![image](https://user-images.githubusercontent.com/80540499/221403885-448cc7ac-e0c9-4ead-8d67-11b76b35c7a2.png)


`ID - 64044 Psychic Horror
Description: You terrify the target, causing them to tremble in horror for $d and drop their main hand and ranged weapons for $64058d.`

`ID - 64346 Fiery Payback
Description: Disarm the enemy's main hand and ranged weapons for $d.`
Only ranged and main. No shields.

Also, you cannot switch weapons while being disarmed.

Everything works okay here.

**Comment by vvranceanu** [comment]
> Also, you cannot switch weapons while being disarmed.

Can you please provide some reference for this?
