### ISSUE TITLE
[Hunter] Improved Barrage

### ISSUE THREAD

**Issue by monsterman45** [azerothcore/azerothcore-wotlk#14585]
### Current Behaviour

Improved Barrage talent not preventing 100% pushback during Volley spell

### Expected Blizzlike Behaviour

3 points in Improved Barrage should reduce pushback entirely

### Source

Talent description itself.

### Steps to reproduce the problem

1. Put three points into Improved Barrage on a hunter
2. Let an enemy melee hit you while casting Volley
3. Observe pushback

### AC rev. hash/commit

fb08f8e905b9

### Operating system

Ubuntu 20.04.5 LTS

**Comment by avarishd** [comment]
rev. de50ce3
Could not reproduce.
