### ISSUE TITLE
[Hunter] Careful Aim

### ISSUE THREAD

**Issue by monsterman45** [azerothcore/azerothcore-wotlk#14586]
### Current Behaviour

Careful Aim no longer adjusts attack power to the character's Intellect rating.

### Expected Blizzlike Behaviour

Level 3 Careful Aim should add attack power equal to 100% of total Intellect.

### Source

Talent description.

### Steps to reproduce the problem

1. Put three points into Careful Aim on a hunter
2. Equip/Unequip an item with Intellect only, not Strength or Agility
3. Observe any changes in ranged Attack Power

### AC rev. hash/commit

fb08f8e905b9

### Operating system

Ubuntu 20.04.5 LTS

**Comment by avarishd** [comment]
rev. de50ce3
Could not reproduce,

86AP from level 80 intellect + 78AP from 78 Intellect from the necklace. (164 total)

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/2e90ae40-390e-47c9-8bbd-9962f4d18449
