### ISSUE TITLE
Glyph of healing wave + Purification Talent

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14588]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4636

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

https://wowgaming.altervista.org/aowow/?item=41534
Glyph of healing wave is getting bonus from https://wowgaming.altervista.org/aowow/?spell=16178 talent

### Expected Blizzlike Behaviour

Glyph of healing wave doesnt double dip with the talent

### Source

https://www.youtube.com/watch?v=qc3Ieqo1CQo&t=863s&ab_channel=Teamy
Timestamp 5:00

"The resto shaman's only healing sources that are NOT increased by purification talent are Chained Heal (4P/T10) and Glyph of Healing Wave"

https://www.wowhead.com/wotlk/item=41534/glyph-of-healing-wave#comments

### Steps to reproduce the problem

Use glyph of healing wave `.additem 41534`
heal another player
get purification talent
Glyph's healing is increased

### AC rev. hash/commit

cdcb0ceff724 2023-01-07

### Operating system

Ubuntu 20.04 - Windows 10 x65

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Tested and works okay.
Purification works on Healing Wave and then the healing from Glyph is just % of that increased healing. No double dip.
