### ISSUE TITLE
[NPC] Worg Master Kruush adds

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14598]
https://github.com/chromiecraft/chromiecraft/issues/4709
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

When Worg Master Kruush he emotes "Worg Master Kruush calls for his worgs." but does not actually do it
Feng and Ripp run away when they reach low hp

### Expected Blizzlike Behaviour

Him calling for his worgs puts the worgs into combat
Feng and Ripp run away when Worg Master Kruush dies

### Source

Pulling: https://youtu.be/Vg9vv2EtcYA?t=35

Worg Master Dies: https://youtu.be/Vg9vv2EtcYA?t=50

### Steps to reproduce the problem

.go zonexy 68.4 73.6 3483

Pull him from range
(aggro his worgs because they will not be in combat with you)
Kill the Worg Master

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=19442
https://wowgaming.altervista.org/aowow/?npc=19459
https://wowgaming.altervista.org/aowow/?npc=19458

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c05c45c51d3d414ab3bec40e3e4bc2b5c10a977e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
In wowhead comments it's mentioned that they flee 2 times, once at or under 20% and once when he dies. I'll leave both in, can always remove the 20% flee. Maybe @heyitsbench has some info on correct behavior if they flee at 20% or not.
