### ISSUE TITLE
[Core/Spell] Tranquilizing Shot -  Removing 4 buffs

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/azerothcore-wotlk#14608]
### Current Behaviour

Tranquilizing Shot - Removing 4 buffs instead of 1.

### Expected Blizzlike Behaviour

Tranquilizing Shot Must only remove 1 puff at a time.

### Source

https://www.wowhead.com/spell=19801/tranquilizing-shot

### Steps to reproduce the problem

1. Create Hunter lvl 80
2. Trainer https://www.wowhead.com/spell=19801/tranquilizing-shot
3. Use Tranquilizing Shot on a Player with 5 Buff.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97a01b430dd3f2b0ba4d6c63bb5c0d7c4f5c5cab

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-1v1-arena
mod-anticheat
mod-boss-announcer
mod-cfbg
mod-eluna
mod-npc-beastmaster
mod-npc-enchanter
mod-npc-free-professions
mod-npc-spectator
mod-transmog
mod-world-chat

**Comment by avarishd** [comment]
rev. de50ce3305ee3e61cc62f01c2dfdf4d7ec3b56bc
Could not reproduce

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/2a728ab2-2dc8-4c32-8c93-b0f66358c386
