### ISSUE TITLE
[TBC] Blade of Unquenched Thirsts' Lifesteal proc scales with Spellpower

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#14604]
### Current Behaviour

~~https://www.wowhead.com/wotlk/item=31193/blade-of-unquenched-thirst has a proc which steals life of the target.
This proc currently scales 1:1 with spellpower~~

### Expected Blizzlike Behaviour

~~The proc shouldnt be influenced by spellpower~~

### Source

https://www.wowhead.com/wotlk/item=31193/blade-of-unquenched-thirst#comments

### Steps to reproduce the problem

.additem 31193
.additem 19379 (or any other spellpower gear)
autoattack a target with HP (not a targeted dummy with 1 life, from which you cannot steal life)

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/f9c159cf81df9389052706c9857052b8869bf001 2023-01-04 13:46:51 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu

### Custom changes or Modules

ChromieCraft

**Comment by balleny** [comment]
Scaling actually seems to be correct and blizzlike.
Proc rate might be too high tho.

**Comment by Tereneckla** [comment]
Don't think it should scale 1:1 with spellpower
![image](https://user-images.githubusercontent.com/50233983/214382636-ef84d4cf-cbc9-4630-826a-2553e61a2f7f.png)
https://www.wowhead.com/wotlk/item=31193/blade-of-unquenched-thirst#comments:id=646757

Current state is really absurd
![image](https://user-images.githubusercontent.com/50233983/214389826-d280f68f-e842-4913-9a26-25447e91738d.png)
