### ISSUE TITLE
Infernal hound should be demon type and not tamable

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14616]
### Current Behaviour

Infernal hound from the Dark Portal opening kruul event are set as beasts and can be tamed

### Expected Blizzlike Behaviour

Infernal hounds should be demons

### Source

Retail (blurry)
![image](https://user-images.githubusercontent.com/11332559/211628647-2d576ca2-b5e1-4bbd-982d-d9e533dd6ebd.png)
https://youtu.be/WslqTn2ljj0?t=3

Classic
![image](https://user-images.githubusercontent.com/11332559/211628591-33941ca6-1b8e-4ffc-ab3d-19f3358cd0e9.png)
https://youtu.be/WslqTn2ljj0?t=3 (set speed slow)

### Steps to reproduce the problem

.learn 1515
.learn 53270
.npc add temp 19207
attempt to tame

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/compare/3ad652d8a..f9c159cf8

### Operating system

Windows 10

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by heyitsbench** [comment]
Checked this mob out on Wrath Classic PTR on a hunter, turns out it still is a beast, but trying to use Tame Beast on it gives a [`Creature not tameable.` message](https://user-images.githubusercontent.com/38561765/228134223-37fda623-72b5-4883-a5d1-4edd120ddd41.png). Don't know what the verdict is on this issue, but there's some info for it.
