### ISSUE TITLE
[Shaman] LOS cleasing totem, Healing stream totem and Mana tide totem

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14625]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4680

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Cleasing totem, healing stream totem amd Mana tide totem get line of sight

### Expected Blizzlike Behaviour

totems don't get LOS

### Source

there is one example with healing stream totem https://youtu.be/SY7NCm7sT34?t=619

### Steps to reproduce the problem

1. call totems
2. hide yourself behind one wall

### AC rev. hash/commit

592a26cb8c46 2023-01-11

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@Pyromanihack Never heard about it. Could you show me another example, but not from arena/bg (LoS on bgs/arenas is allowed on retail)?

**Comment by Pyromanihack** [comment]
Healing Totem
[healing totem.webm](https://user-images.githubusercontent.com/82369562/212469404-0ea77a7a-48b5-4be7-93bd-2976ea279a73.webm)

Mana Tide Totem
[mana tide.webm](https://user-images.githubusercontent.com/82369562/212469415-4a06e228-c034-459f-8e24-6dbc457674b4.webm)

each one was tested in Elwynn Forest. I forgot to show the Combat log, but i checked out of video and the effect doesn't show neither in the Combat log

**Comment by UltraNix** [comment]
I meant - sources from retail that totems should ignore LoS.

**Comment by Pyromanihack** [comment]
I think this confirms the theory, I tested in the same place as in the previous video (as you can see in the combat log)
[healing totem PTR.webm](https://user-images.githubusercontent.com/82369562/212475246-21da2d44-9431-4f70-99fe-dedf03b4695d.webm)

This is the how combat log works on CC
[healing totem LOCAL.webm](https://user-images.githubusercontent.com/82369562/212475389-cf097d34-82b0-45a1-8797-688616633177.webm)

The same it's for Mana Tide Totem [PTR.webm](https://user-images.githubusercontent.com/82369562/212475486-1689a4b2-17b6-4d55-abfa-4f31ce90f5f3.webm)

Cleansing Totem:
[cleansing totem LOCAL.webm](https://user-images.githubusercontent.com/82369562/212476202-0dab2208-c2ab-49c3-9ff7-84578451e91c.webm)
