### ISSUE TITLE
[QUEST] "The Lost Supplies" Bugged

### ISSUE THREAD

**Issue by Azzaleo** [azerothcore/azerothcore-wotlk#1462]
DESCRIPTION:

Quest "The Lost Supplies" not initiable.

EXPECTED BLIZZLIKE BEHAVIOUR:

Opening (clicking) one of the four "Scattered Crate" (ID: 28604) situated on Swamp of Sorrows ( https://vanilla-twinhead.twinstar.cz/?object=28604#map ), you can loot "Lost Supplies" (ID: 6172) giving you the quest "The Lost Supplies" (ID: 1423).

CURRENT BEHAVIOUR:

You can't start the quest because boxes are empty (not giving you the quest item).

STEPS TO REPRODUCE THE PROBLEM:

1- .go -9979 -3690 22 0
2- Click the box in front of you.

BRANCH(ES):
staging

AC HASH/COMMIT:
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by CookieMonsterDev** [comment]
Can't find info on the 'Loot Chance' of the item. Your link says 100% but is from Vanilla. This link says 2%
https://wotlk.evowow.com/?object=28604

**Comment by Azzaleo** [comment]
Nono, your link say 0.02%, is a suicide! 😅

**Comment by Azzaleo** [comment]
Nono, your link say 0.02%, is a suicide! 😅
Yesterday I opened like 30-40 of this crates, but nothing, its an impossible quest.

**Comment by poszer** [comment]
> Nono, your link say 0.02%, is a suicide! 
> Yesterday I opened like 30-40 of this crates, but nothing, its an impossible quest.
So, is it correct 0.02 as drop chance?  Everyone will skip this quest if this is correct :rofl: 

`UPDATE `gameobject_loot_template` SET `Chance`=100 WHERE `Item`=6172;`
Should be maybe ?

**Comment by FrancescoBorzi** [comment]
just quick notes:
- `0.02` would definitely be too low
- that link might also be not correct

**Comment by poszer** [comment]
> just quick notes:
> 
> * `0.02` would definitely be too low
> * that link might also be not correct

Yeah lol

**Comment by CookieMonsterDev** [comment]
Well I couldn’t find any info on it. So I didn’t want to make a PR with wrong values. I figured 0.2 was too low.

**Comment by Stoabrogga** [comment]
Hmm, the comments here imply that the drop chance was 100%:
https://wow.gamepedia.com/The_Lost_Supplies#Notes
https://www.wowhead.com/quest=1423/the-lost-supplies

**Comment by CookieMonsterDev** [comment]
> `UPDATE `gameobject_loot_template`SET`Chance`=100 WHERE `Item`=6172;`

Then poszer sql will fix it, as I did the same and it works.

**Comment by FrancescoBorzi** [comment]
@poszer please open PR

**Comment by poszer** [comment]
> @poszer please open PR

Okay
