### ISSUE TITLE
[NPC] Sunfury Geologist

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14638]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4724

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

After getting low and running away in fear they stay at range and do nothing

Most have random 5yd movement

### Expected Blizzlike Behaviour

They revert to the initial behavior of mostly rock throwing
Most of them should be static and mine away at some rocks

### Source

Common sense
[geologist.webm](https://user-images.githubusercontent.com/82369562/212124239-5401f3a3-14f5-47d6-8ac3-3f31310cbcb3.webm)

### Steps to reproduce the problem

.go c 70741
.damage 6000
Wait for fleeing to end

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=19779

[here](https://github.com/TrinityCore/TrinityCore/issues/24937) there's something related to Sunfury Geologist' SAI
(19779,0,0,0,0,0,100,0,0,0,2300,3900,0,11,36645,64,0,0,0,0,2,0,0,0,0,0,0,0,0,"Sunfury Geologist - In Combat CMC - Cast 'Throw Rock'"),
(19779,0,1,0,9,0,100,0,0,5,5000,9000,0,11,35918,32,0,0,0,0,2,0,0,0,0,0,0,0,0,"Sunfury Geologist - Within 0-5 Range - Cast 'Puncture Armor'"),
(19779,0,2,0,2,0,100,1,0,15,0,0,0,25,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Sunfury Geologist - Between 0-15% Health - Flee For Assist (No Repeat)")

### AC rev. hash/commit

592a26cb8c46 2023-01-11

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Sneften** [comment]
Here's a clip of expected behaviour:

https://user-images.githubusercontent.com/103856689/212471399-ba14cb82-0352-4e8a-9880-254ff41e8217.mp4

- Don't run away in fear.
- Throw rock is not used frequently and only if you are out of meele range.
