### ISSUE TITLE
Worldserver crash.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#14631]
### Current Behaviour

When trying to complete the quest [Into the Realm of Shadows](https://www.wowhead.com/wotlk/quest=12687), upon riding the [Acherus Deathcharger]() into Death's Breach and summoning [Salanar the Horseman](), he [says his congratulations](https://user-images.githubusercontent.com/38561765/211982930-9d077ad4-2623-45e5-b156-d5a6b0b95732.png), character gets credit for the quest, and then the server crashes.

### Expected Blizzlike Behaviour

No crash.

### Source

N/A

### Steps to reproduce the problem

1. Create a death knight.
2. Complete the initial quest chain to the point of getting [Into the Realm of Shadows](https://www.wowhead.com/wotlk/quest=12687) available.
3. Try to complete the quest.

### Extra Notes

[Here's the crash log](https://gist.github.com/heyitsbench/5ada72ca6d11af43d6bc7d890aa2daab).

This crash does occur on my own branch and fork with the changes from the Worgoblin module, but it happens across races, not just custom ones. Based on a glance at the crash log from my eyes, it doesn't *look* like my fault, but I will test on a clean core later to make 100% sure.

### AC rev. hash/commit

159670201d84

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)
[mod-worgoblin](https://github.com/heyitsbench/mod-worgoblin)

**Comment by heyitsbench** [comment]
[It does still crash on](https://gist.github.com/heyitsbench/97a25c6fc34ce9e24a839bb34f5a0871) 592a26cb8c46 with only [mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template) installed.

**Comment by acidmanifesto** [comment]
> [It does still crash on](https://gist.github.com/heyitsbench/97a25c6fc34ce9e24a839bb34f5a0871) 592a26cb8c46 with only [mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template) installed.

The link logs suggest it crashes via smart scripts doing a temp summon.

**Comment by Nyeriah** [comment]
Null pointer on timed action list... perhaps trying to reach a creature that has already despawned

It's crashing in GetGuidValue
