### ISSUE TITLE
[Gruul] Growth is queued, instead of flat timer

### ISSUE THREAD

**Issue by IskrenPlashkov** [azerothcore/azerothcore-wotlk#14649]
### Current Behaviour

After the 30 second cd runs out, Growth is queued to be used after all other currently queued abilities.

### Expected Blizzlike Behaviour

Every flat 30 seconds Gruul should cast growth.

### Source

https://wowpedia.fandom.com/wiki/Gruul_the_Dragonkiller_(tactics)

### Steps to reproduce the problem

Engage Gruul;
Survive 30 seconds;

### Extra Notes

This bug delays the dmg increase and thus makes the fight easier.

### AC rev. hash/commit

/

### Operating system

All

**Comment by heyitsbench** [comment]
Please include the core revision.
