### ISSUE TITLE
[QUEST] "Fall From Grace" Bugged

### ISSUE THREAD

**Issue by Azzaleo** [azerothcore/azerothcore-wotlk#1464]
DESCRIPTION:

Quest "The Lost Supplies" not completable.

EXPECTED BLIZZLIKE BEHAVIOUR:

Speak with "Fallen Hero of the Horde" (ID:7572), accept the only quest you can accept (quest ID: 2784) speak with the same NPC (clicking on the different dialog tabs), complete the quest.

CURRENT BEHAVIOUR:

You can't complete the quest because the dialogs do not allow you to move on (Click on the same string but it does not go on).

STEPS TO REPRODUCE THE PROBLEM:

1- .go -10632 -3009 29 0
2- Speak with NPC "Fallen Hero of the Horde"
3- Accept the only quest you can accept, called "Fallen From Grace"
4- Speak again with this NPC and click: Why are you here? > Continue with your story. > Tragic..

LINKS:
https://wow.gamepedia.com/Fall_From_Grace_(quest)
https://www.wowhead.com/npc=7572/fallen-hero-of-the-horde

BRANCH(ES):
staging

AC HASH/COMMIT:
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by Azzaleo** [comment]
Tested, now work perfectly!

**Comment by BarbzYHOOL** [comment]
@Azzaleo thank you azzaleo, can you please comment on the Pull Request page next time?

And are you on our discord? You know we need help testing PRs :P it's really important

**Comment by boom8866** [comment]
Don't you test this submission? 
 Quest:2702 Can't dialogue
