### ISSUE TITLE
Bleeding Hollow Archers prefer to melee

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14642]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4734

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

They run into melee

### Expected Blizzlike Behaviour

They prefer to use their archery skills

### Source

The Archer class is made up of archers

### Steps to reproduce the problem

1. `.gm on`
2. ` .go c 202645`
3. Clean a little to test properly
4. Attack from range the Archers and look at their behaviour

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=17270

### AC rev. hash/commit

592a26cb8c46 2023-01-11

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by clovaek** [comment]
they run straight to melee range in all versions i've checked
wotlk 2008: https://youtu.be/oOCVydMtJ2U?t=36
tbc classic: https://youtu.be/xF-1Pl1PygM?t=101 (starts off with a los pull, but the archer chases the tank in melee, next archer pack has a non los pull)
wotlk classic ptr: https://youtu.be/CCiBxjHp-CY

**Comment by Tereneckla** [comment]
next video from your wotlk 2008 source: https://youtu.be/cQ9gO4jeQ7o?t=53
It also is normal for many ranged to continue being melee if you only slowly move away

**Comment by clovaek** [comment]
my bad, i missed that one.

i guess they are completely broken on the classic releases since i can't get them to cast multi shot or aimed shot at all. they just freeze during root and they run towards you on multiple ranged pulls + after stuns.
