### ISSUE TITLE
[Gruul] Ground slam knocks back, instead of random direction

### ISSUE THREAD

**Issue by IskrenPlashkov** [azerothcore/azerothcore-wotlk#14648]
### Current Behaviour

When Gruul uses ground slam all players are knocked back towards the wall.

### Expected Blizzlike Behaviour

When Gruul uses ground slam all players must be knocked in random direction towards the wall.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot
https://wowpedia.fandom.com/wiki/Gruul_the_Dragonkiller_(tactics)

### Steps to reproduce the problem

Engage Gruul;
Survive until ground slam is cast

### Extra Notes

Being knocked in random direction adds an additional layer of complexity to the fight.
Currently players can effectively spread preemptively, greatly reducing dmg taken from shatter.

### AC rev. hash/commit

/

### Operating system

All

**Comment by heyitsbench** [comment]
Please include the core revision.
