### ISSUE TITLE
[High king Maulgar] Charge does not work

### ISSUE THREAD

**Issue by IskrenPlashkov** [azerothcore/azerothcore-wotlk#14650]
### Current Behaviour

HKM never charges a player.

### Expected Blizzlike Behaviour

When boss is under 50 % hp he should gain the Charge ability.
This should not a threat reset.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot

### Steps to reproduce the problem

Engage high King Maulgar
Bring Boss under 50 % hp
Wait

### AC rev. hash/commit

.

### Operating system

All

**Comment by heyitsbench** [comment]
Please include the core revision.
