### ISSUE TITLE
[High King Maulgar] Krosh doesnt have buff on pull

### ISSUE THREAD

**Issue by IskrenPlashkov** [azerothcore/azerothcore-wotlk#14651]
### Current Behaviour

Krosh Firehand doesnt have the 75% spell dmg reduction buff on pull (the one mages spellsteal). He casts it few seconds after pull, usually after 2 fireballs.

Also the Buff, once eventually spell stolen, only lasts for 20 seconds.

### Expected Blizzlike Behaviour

He should have the buff on pull, before starting to cast anything.
Once mage uses spellsteal buff should last 2 minutes.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot

_No response_

### Steps to reproduce the problem

Enage HKM.
Attempt to spellsteall imediatelly after pull.

### AC rev. hash/commit

.

### Operating system

All

**Comment by heyitsbench** [comment]
Why not report these on the [ChromieCraft](https://github.com/chromiecraft/chromiecraft/issues) tracker if you can't fill out the required fields?
