### ISSUE TITLE
Rohok does not teach blacksmithing recipes

### ISSUE THREAD

**Issue by Tehmirror** [azerothcore/azerothcore-wotlk#14674]
### Current Behaviour

My character currently has 305/375 blacksmithing. The trainer for that skill level is Rohok for the horde. When talking to Rohok he refuses to teach me the recipes.
![image](https://user-images.githubusercontent.com/89776779/212483460-d429db7b-4806-4dd7-b0bf-f9637a591335.png)

### Expected Blizzlike Behaviour

Rohok should offer a few blacksmithing recipes.

### Source

https://www.wowhead.com/tbc/npc=16583/rohok

### Steps to reproduce the problem

Talk to Rohok with a blacksmithing skill of 305 (I only have one character with BS and it works consistent with him)

### AC rev. hash/commit

592a26cb8c46 2023-01-11 02:40:03 -3000

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
Can't reproduce. Works for me
