### ISSUE TITLE
Antonio Perelli - missing texts

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#14686]
### Current Behaviour

Antonio Perelli does not say anything when perfoming his waypoints.

### Expected Blizzlike Behaviour

Antonio Perelli should talk when reaching certain waypoints.

### Steps to reproduce the problem

1. Find Antonio Perelli in Elwynn Forest

### Extra Notes

TC commit -- https://github.com/TrinityCore/TrinityCore/commit/4f1f6a23642bc2f2d960b85815042544d0d72d70

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/cdcb0ceff7249e072d53c6e4a4f2460ff3442463

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/16156.
