### ISSUE TITLE
[Hunter] Wolfs-type pet's hunter move slowly than normal

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14699]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4785

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When you have a pet belonging to Wolf-type, he moves slower than every other pet.
[CC pet velocity.webm](https://user-images.githubusercontent.com/82369562/212944440-32f0283b-6157-4e4b-bc4a-fc2e9b69220c.webm)

### Expected Blizzlike Behaviour

Wolf should run at normal speed

### Source

I tested the velocity in my local server and in PTR, and as you can see in Retail the pet moves faster
[PTR pet velocity.webm](https://user-images.githubusercontent.com/82369562/212944872-d36d6036-8917-44b3-baac-bfe6c4c05953.webm)

### Steps to reproduce the problem

1. `.learn 1515`
2. Tame a wolf-type beast (e.g. `.go c 79631`)
3. Attack with your pet and observe its speed

### AC rev. hash/commit

b3e37226745a 2023-01-16

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by NinjaSoftworks** [comment]
Confirmed on CC Live.

**Comment by Kitzunu** [comment]
Dont upload files. Upload them to youtube or something.

**Comment by Pyromanihack** [comment]
There's some kind of reason for this?

**Comment by Kitzunu** [comment]
Yea, nobody wants to download files they dont know what they are.

**Comment by Pyromanihack** [comment]
Good to know 😉

**Comment by Nyeriah** [comment]
If you use one of the accepted formats the files will trigger the video player, instead of showing as an upload as happened here. In that case, it would be fine, and even preferred

**Comment by Gultask** [comment]
Yep. .mp4 embeds itself very well in GitHub. You can use https://handbrake.fr/ to convert files.

**Comment by Kitzunu** [comment]
Ah nice, I did not know that
