### ISSUE TITLE
[Core] Worldserver spam and lag

### ISSUE THREAD

**Issue by Nefertumm** [azerothcore/azerothcore-wotlk#1469]
##### SMALL DESCRIPTION:

Since i updated my repo with latest commit, i'm getting this:
https://imgur.com/a/vqALqO4
and with that, i'm getting spikes of update time, which causes lag.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Worldserver should stay clean and only notifying the update time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Update AC to the latest commit.
2. See if you get the same problem than I.

##### EXTRA NOTES:

I reverted 51b8773528d7cf526d926ddb6edee2b0a8aec17f and now it's working fine again.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

23e7ae6a2f65983f66ade719c5768c57abcec3a6

##### OPERATING SYSTEM:

Windows 10 / Ubuntu

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

Nothing

**Comment by GitVerge** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/51b8773528d7cf526d926ddb6edee2b0a8aec17f#diff-2094dfd21434b2fec5f1ba58018139f7R101

and

https://github.com/azerothcore/azerothcore-wotlk/commit/51b8773528d7cf526d926ddb6edee2b0a8aec17f#diff-2094dfd21434b2fec5f1ba58018139f7R93

This default might be set to a higher value or just put the output as debug?

**Comment by comix1988** [comment]
![schermata 2019-02-15 18 10 05](https://user-images.githubusercontent.com/22867608/52872564-1f5de200-314d-11e9-8b4f-97efca6a5724.png)

confirm

**Comment by BarbzYHOOL** [comment]
Just for curiosity: `Recored update time`? what is this ? what does it mean? where is it from?

**Comment by FrancescoBorzi** [comment]
we should definitely investigate on this, maybe @Viste or @Nefertumm can give a hint here

**Comment by GitVerge** [comment]
it's from the world update. I think the purpose of it is to have an output if a specific part of the code takes more time to update than expected. In this case the maximum time is set to 100ms for each process by default.

**Comment by BarbzYHOOL** [comment]
"recored" means nothing and I 've never seen it before

**Comment by GitVerge** [comment]
it was introduced with this pr, probably a typo for recorded lol

**Comment by BarbzYHOOL** [comment]
@GitVerge which PR?

**Comment by GitVerge** [comment]
@BarbzYHOOL https://github.com/azerothcore/azerothcore-wotlk/commit/51b8773528d7cf526d926ddb6edee2b0a8aec17f#diff-2094dfd21434b2fec5f1ba58018139f7R93

**Comment by Viste** [comment]
lol this messages is normal case they shows real update time not this fake diff=10

**Comment by Viste** [comment]
and lag on your server still exist but now you don't know about that
