### ISSUE TITLE
[Item] Zaxxis Insignia not dropping

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14691]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4750

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Item not dropping.

### Expected Blizzlike Behaviour

The item to drop without any prerequisites.

### Source

Drop rate should be 50% from all 3 types of NPC.

https://www.wowhead.com/wotlk/item=29209/zaxxis-insignia

The items should be droppable without completing any of the quests.

https://www.youtube.com/watch?v=7tHrLzUqkGc&ab_channel=PhoenixGaming

### Steps to reproduce the problem

1. `.go c 70061`
2. Kill the Zaxxis without taking [A Heap of Ethereals](https://www.wowhead.com/wotlk/quest=10262/a-heap-of-ethereals)
3. Look if the item is dropped

### AC rev. hash/commit

0df153b8ddaa 2023-01-13

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
At the moment https://www.wowhead.com/wotlk/quest=10265/consortium-crystal-collection is the only thing set as a prerequisite. This needs to be confirmed.

**Comment by avarishd** [comment]
@heyitsbench 🚀

**Comment by heyitsbench** [comment]
Confirmed, insignias should drop with no quests taken/completed.
