### ISSUE TITLE
Unholy weapon enchant doesn't proc

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#14706]
Original Issue: https://github.com/chromiecraft/chromiecraft/issues/4801

### What client do you play on?

enGB - enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

It doesn't proc

### Expected Blizzlike Behaviour

It does proc.
Wowhead comments from 3.1.0
https://www.wowhead.com/wotlk/spell=20033/enchant-weapon-unholy-weapon#comments:id=695874

### Source

[check above.](https://www.wowhead.com/wotlk/spell=20033/enchant-weapon-unholy-weapon#comments:id=695874)

As of patch 3.3, in addition to the damage reduction effect it also inflicts additional damage on target when it procs:

From the patch notes:
"Enchant Weapon - Unholy: This enchantment now inflicts Shadow damage in addition to its original effect."

### Steps to reproduce the problem

1. `.setskill 333 430`
2. `.learn 20033`
3. `.additem 12808 4`
4. `.additem 14344 4`
5. Enchant a weapon and use it on a NPC

### AC rev. hash/commit

b3e37226745a 2023-01-16

### Operating system

Debian 11 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/221400847-d1b2c62a-1b8d-490d-8baa-b4e15d5e211c.png)
Works okay.
