### ISSUE TITLE
[Hellfire Ramparts] Omor The Unscarred moves to the player's position on aggro

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14701]
https://github.com/chromiecraft/chromiecraft/issues/4428

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

[Omor The Unscarred](https://wowgaming.altervista.org/aowow/?npc=17308) moves to the player's position at the start of combat and when victim changes

### Expected Blizzlike Behaviour

Omor The Unscarred does not move to the player's position when combat starts, as is shown in the linked video. He starts casting spells when the player is out of range.

### Source

wotlk 2008 fight:
https://youtu.be/cQ9gO4jeQ7o?t=201

### Steps to reproduce the problem

.go xyz -1197.796997 1678.449707 91.886002 543 0.456575
X: -1197.796997 Y: 1678.449707 Z: 91.886002 Orientation: 0.456575
engage Omor The Unscarred from a ranged position
observe him moving to your location

### Extra Notes

Did a ranged spell pull on both CC & wotlk classic PTR. Can't really test bodypulling right now since I'm too high level on wotlk PTR. On CC a body pull results in the same movement for me.

CC PTR: https://youtu.be/G0HyowTvX1U

WOTLK PTR: https://youtu.be/4uRk-LLFZ-o

edit: wotlk ptr bodypull: https://youtu.be/4EFXB8G1vFI
he runs to the player if you bodypull him on wotlk ptr aswell

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Maelthyrr** [comment]
Are you sure about this ? Because on these two videos he moves:

- https://www.youtube.com/watch?v=sTvXdAwLPPw
- https://www.youtube.com/watch?v=7WI8g3a4Npg

Or maybe the mechanic is more complex.

**Comment by Gultask** [comment]
That's combat movement. Noticeable with nearly all caster NPCs to some extent. If you are within combat range they can move to continue melee buy at something like >10y they don't move.

In the first video Omor switches targets midway but does not move into range as he instead casts his ranged spell.

**Comment by Maelthyrr** [comment]
> That's combat movement. Noticeable with nearly all caster NPCs to some extent. If you are within combat range they can move to continue melee buy at something like >10y they don't move.
> 
> In the first video Omor switches targets midway but does not move into range as he instead casts his ranged spell.

Oh, fine sorry.

**Comment by Gultask** [comment]
No need to apologize:)
