### ISSUE TITLE
Eluna Engine Module not Compiling with 

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1470]
##### SMALL DESCRIPTION:

Eluna Engine Module from AzerothCore not compiling with Latest commit 23e7ae6. Throws some serious errors.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The module should compile as it did before the latest commit.

##### CURRENT BEHAVIOUR:

Throws errors during compilation in VS2017 Community Edition every time. Once module is removed it compiles just fine.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just compile with Eluna module.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

23e7ae6

##### OPERATING SYSTEM:

Win 7/10

##### MODULES:

None except Eluna which throws the errors.

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by FrancescoBorzi** [comment]
@gtao725 Thanks for your report. However, one commit was just reverted, can you please try again on latest master?

Also this issue should be reported in the module repo, so please open it there if the issue is still on `master`.
