### ISSUE TITLE
BUG Position Map

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#14702]
### Current Behaviour

Exactly in that place, if it is tested with a GM or a player, the result is the same: easy to fall into that position and impossible to leave later.

![image](https://user-images.githubusercontent.com/58153179/213012217-b92bec44-e81b-40bc-98c0-67f9cd20a05c.png)

### Expected Blizzlike Behaviour

I think it's a relatively inexplicable problem and easy to discover.

### Steps to reproduce the problem

.go xyz -14450.082031 492.454987 26.168053 0 0.774351

and voila, you don't leave anymore!

### AC rev. hash/commit

cd6e0d7e0b78

### Operating system

Windows

**Comment by Kitzunu** [comment]
Without the command, I cannot reproduce falling in there.

Also I doubt there is anything we can do about it. But to me it looks like you can't fall in unless you teleport there.

**Comment by htc16** [comment]
> Without the command, I cannot reproduce falling in there.
> 
> Also I doubt there is anything we can do about it. But to me it looks like you can't fall in unless you teleport there.

Then you are wrong, I don't know if you saw it but the command is there, you just have to copy it and test it. Furthermore, the bug was discovered by players on my server who fell into this error.

.go xyz -14450.082031 492.454987 26.168053 0 0.774351
.go xyz -14450.082031 492.454987 26.168053 0 0.774351
.go xyz -14450.082031 492.454987 26.168053 0 0.774351
.go xyz -14450.082031 492.454987 26.168053 0 0.774351
.go xyz -14450.082031 492.454987 26.168053 0 0.774351

**Comment by Kitzunu** [comment]
Yea I am telling you that I cannot fall into there unless I teleport.

With the command yea sure. Without the command, I can find no way to fall there. I have tried running and jumping from different angles but it is impossible to fall down

**Comment by htc16** [comment]
> Yea I am telling you that I cannot fall into there unless I teleport.
> 
> With the command yea sure. Without the command, I can find no way to fall there. I have tried running and jumping from different angles but it is impossible to fall down

Ok! ;)
