### ISSUE TITLE
NPC's stuck

### ISSUE THREAD

**Issue by damangguomoniqi** [azerothcore/azerothcore-wotlk#14712]
### Current Behaviour

![屏幕截图(2)](https://user-images.githubusercontent.com/84113561/213371568-1e0d87c6-c529-498d-ad0f-dc500e066608.png)

### Expected Blizzlike Behaviour

NPCS should down the steps

### Source

1

### Steps to reproduce the problem

1

### Extra Notes

1

### AC rev. hash/commit

1

### Operating system

Windows 10 x64

### Custom changes or Modules

1

**Comment by damangguomoniqi** [comment]
OK

**Comment by Kitzunu** [comment]
H

**Comment by acidmanifesto** [comment]
> ### Current Behaviour
> 
> ![屏幕截图(2)](https://user-images.githubusercontent.com/84113561/213371568-1e0d87c6-c529-498d-ad0f-dc500e066608.png)
> 
> 
> ### Expected Blizzlike Behaviour
> 
> NPCS should down the steps
> 

Turn off gm mode. 233
