### ISSUE TITLE
[High King Maulgar] Krosh Firehand doesn't cast Spell Shield buff as first cast on pull

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#14718]
### Current Behaviour

https://wotlkdb.com/?npc=18832 doesnt have the 75% spell dmg reduction buff (https://wotlkdb.com/?spell=33054) on pull. He casts it few seconds after pull, usually after casting https://wotlkdb.com/?spell=33051 twice.

### Expected Blizzlike Behaviour

He should be casting Spell Shield buff as his first spell, and Greater Fireball right after that.

### Source

https://www.icy-veins.com/tbc-classic/gruuls-lair-guide-strategy-abilities-loot
[Video guide source](https://youtu.be/DhaKamqqIjo?t=164)

### Steps to reproduce the problem

1. Engage [HKM](https://wotlkdb.com/?npc=18831).
2. Tank Krosh Firehand
3. See he is not casting Spell Shield as his first cast.

### Extra Notes

With this issue in place https://wotlkdb.com/?npc=18832 usually 1 shots 1-2 ppl before he can be properly tanked.

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4811

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Windows 10

**Comment by Gultask** [comment]
22:40:46.219 -- AI Reaction Timestamp
22:40:47.378 -- Cast

So around 3 packet cycles in my case.
