### ISSUE TITLE
[Magtheridon] Magtheridon casts Blast Nova before Quake

### ISSUE THREAD

**Issue by Contrubius** [azerothcore/azerothcore-wotlk#14721]
### Current Behaviour

Magtheridon casts Blast Nova approximately every 50 seconds, after it he casts Quake. This means that he uses all other abilities that are back from cd before this one. After Quake spell is finished, Magtheridon should immediately start casting Blast Nova

### Expected Blizzlike Behaviour

[Magtheridon ](https://wotlkdb.com/?npc=17257)should begin casting Blast Nova approximately every 50 seconds, right after Quake.

### Source

https://www.icy-veins.com/tbc-classic/magtheridons-lair-guide-strategy-abilities-loot
[World first video kill, keep an eye on the Blast Nova Weakaura](https://youtu.be/PVL-m0CvfI0)

### Steps to reproduce the problem

1. Engage https://wotlkdb.com/?npc=17257
2. Kill all 5 https://wotlkdb.com/?npc=18829
3. Survive for 60 seconds

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/4814

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Windows 10

**Comment by balleny** [comment]
and also very important: blast nova can apparently occur earliest 20 seconds after transition into the last phase
https://github.com/DeadlyBossMods/DBM-BCC/blob/8ffd08ab87ff88e49fe5007bafbb0d84a9c75fc7/DBM-Outlands/Magtheridon.lua#L70

**Comment by Kitzunu** [comment]
It is very appreciated if you include spell id's in the report. Preferably visible not behind a link
