### ISSUE TITLE
Missing property in config file

### ISSUE THREAD

**Issue by Dezaimasu** [azerothcore/azerothcore-wotlk#14743]
### Current Behaviour

When new config variable(s) is added to .dist file, it's not added to your config file(s), thus leading to this error:
![image](https://user-images.githubusercontent.com/1636242/213921720-c7c91b0e-1d29-48d1-a537-307927cc9dbc.png)

Maybe it's somehow related to this recent change https://github.com/azerothcore/azerothcore-wotlk/pull/14707 because It's the first time I see these errors in console.

### Steps to reproduce the problem

1. Use some old commit to setup the server and create new config files. For example this commit fd08f6150f0bacfcc3ea5e999e8b22cb20ba7ccd , it has no `StartHeroicPlayerMoney` config variable, which was added in the next commit 6a357da28c715ca9c3fdc1bffdf48bf1ef845024
2. Pull latest changes with new variables added to `authserver.conf.dist` or `worldserver.conf.dist`
3. Compile the server and try to run it
4. Check the errors in authserver/worldserver console.

### Extra Notes

According to this https://www.azerothcore.org/wiki/server-setup#config-files-worldserverconf--authserverconf on your **first** setup you should create two config files from .dist templates.
According to this https://www.azerothcore.org/wiki/keeping-the-server-up-to-date no further changes should be made to these config files when updating the server.

Maybe it's just the documentation missing instructions about keeping your .conf files up-to-date.

### AC rev. hash/commit

5f3f32f2fd19

### Operating system

Windows 10 x64

### Custom changes or Modules

none

**Comment by Kitzunu** [comment]
This is correct. Add the values yourself into the .conf file

**Comment by Dezaimasu** [comment]
Sure, no problem. 
No offense, but shouldn't it be mentioned somewhere on "Keeping the Server Up-to-Date" wiki page? It's not very obvious.

**Comment by heyitsbench** [comment]
> No offense, but shouldn't it be mentioned somewhere on "Keeping the Server Up-to-Date" wiki page? It's not very obvious.

The change that made this a requirement was very recent, so the wiki hasn't been updated with it. If you'd like to submit a PR to the wiki to reflect this new step, feel free to.
