### ISSUE TITLE
Bloodsail Charts missing spawn locations

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14744]
https://github.com/chromiecraft/chromiecraft/issues/4852
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

[Bloodsail Charts](https://wowgaming.altervista.org/aowow/?object=2086) only has one spawn location

![image](https://user-images.githubusercontent.com/11332559/213927788-c5eb10be-f2cc-4757-a8f0-b32559a20e37.png)

### Expected Blizzlike Behaviour

Should have at least 3 spawn locations

### Source

![image](https://user-images.githubusercontent.com/11332559/213927844-36301763-3a5f-40b6-94b7-e76e6db800ac.png)
https://www.wowhead.com/wotlk/object=2086/bloodsail-charts#comments

![image](https://user-images.githubusercontent.com/11332559/213927879-dee5033a-4242-4902-8a67-7246e9426555.png)

https://youtu.be/FI-cO6QFsxc?t=290

### Steps to reproduce the problem

.quest add 604
.tele wildshore

### Extra Notes

https://wowgaming.altervista.org/aowow/?object=2086
https://www.wowhead.com/wotlk/quest=604/the-bloodsail-buccaneers

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Side note, a boat (on top of which should be a chart) is reversed.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/51111f20-cedb-476f-8146-9688ed0e8f3f)
