### ISSUE TITLE
[Escape From Durnholde] Thrall Escort Event could use a rewrite

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#14758]
### Current Behaviour

- [ ] Thrall bytes2 is wrong
- [ ] Thrall does not move to Armorer to knock him out
- [ ] Armorer moves while knocked out i.e. Is never rooted
- [ ] Skarloc's Mount is selectable
- [ ] Skarloc Mount does not despawn or 2 spawns I can't quite remember
- [ ] Thrall kills Skarloc's Mount, event for it doesn't play
- [ ] Barn event is entirely wrong
- [ ] Taretha does not have gossip
- [ ] Taretha event does not play
- [ ] Tarren Mill Guards and other NPCs don't despawn
- [ ] Erozion doesn't have gossip at the end

### Expected Blizzlike Behaviour

Not what's up there.

Unreadable outline for the event >:)
https://github.com/Gultask/Research-Wotlk/issues/2#issuecomment-1399551029

### Source

Retail Sniffs

### Steps to reproduce the problem

`.go c id 17876`

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/443c75daa4664c0595c123717af9c9e520b6fd04

### Operating system

Windows 10

**Comment by acidmanifesto** [comment]
Could? Should? Or does need?

**Comment by Gultask** [comment]
It's functioning but all kinda wrong

**Comment by Gultask** [comment]
If someone wants to do this bug me to fix the formatting of what I wrote up.
