### ISSUE TITLE
Creating planar essences can activate omen of clarity

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#14768]
https://github.com/chromiecraft/chromiecraft/issues/4900
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

Currently creating greater planar essence and lesser planar essence can proc omen of clarity.

https://user-images.githubusercontent.com/50205200/214948379-1c50a237-26a1-49f9-a38d-1ac0fb2500af.mp4

### Expected Blizzlike Behaviour

Creating a greater or lesser essence or  a crystalized or eternal element should not proc omen of clarity.

### Source

I will argue for the expected behavior by pointing to the spell's description on 3.3.5:
"Each of the Druid's damage spells, healing spells, and auto attacks has a chance of causing the caster to enter a Clearcasting state.  The Clearcasting state reduces the Mana, Rage or Energy cost of your next damage, healing spell or offensive ability by 100%."

And the provided video showing an outrageous amount of procs, which I believe renders this behavior an indefensible bug.

### Steps to reproduce the problem

.learn 16864
.add 22446 10
Click the essences back and forth

### Extra Notes

This behavior is very easy to abuse as creating either of these does not trigger a GCD, allowing a druid to macro it into spammable abilities and essentially create a bottomless mana well for themselves.

Affected items that I found are 35622, 35623, 35624, 35625, 35627, 36860, 34056, 22447, 16202, 11174, 11134, 10998, 10938, 34055, 22446, 16203, 11175, 11135, 11082, 10939

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3fee40be7dac90ca99f73e6ae809b18ed7135ef6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by QuantaCosta** [comment]
This works as intened if we refer to vanilla wotlk (3.3.5a) and was slightly adapted/tinkered with wotlk classic (3.4.X) as link provided below states. It's basically up to the AC heads to decide which of those two versions of OoC behaviour they prefer, respectively how close to the vanilla 3.3.5a behaviour they want to stick.
https://github.com/JamminL/wotlk-classic-bugs/issues/66#issuecomment-1182017571

**Comment by Tereneckla** [comment]
This is not about instant cast spells
This is about infinitely spammable, cooldownless item creation proccing it
This bug generates as many ooc procs as you can click/macro

The link you give also says that tradeskills don't proc, which converting trade items kinda falls into

**Comment by Kitzunu** [comment]
So it is missing an ICD?

**Comment by bonfax4** [comment]
Have a look into https://github.com/chromiecraft/chromiecraft/issues/4356 if you're tinkering with the talent

**Comment by QuantaCosta** [comment]
> This is not about instant cast spells This is about infinitely spammable, cooldownless item creation proccing it This bug generates as many ooc procs as you can click/macro
> 
> The link you give also says that tradeskills don't proc, which converting trade items kinda falls into

It says tradeskills are not supposed to proc it.
Which leads me back again to the general question of AC's philosophy:
Recreate 3.3.5a version or a "polished modification". If the latter is the case, providing any sources of evidence prior to 3.4.X (classic wotlk) is meaningless from this point onward (for any version-related bug reports).
Don't get me wrong: I've watched the video & i see how gamechaning this is. I'm absolutely with you.
But there are many instances of these "questionable" mechanics, some of them are as extensive as it would require to rewrite entire actual core mechanics.

**Comment by Nyeriah** [comment]
Strict 3.3.5a version, we take no interest in 3.3.4 changes.
However, there have been deviations in the past were **blizzlike game-breaking bugs** were fixed.

**Comment by Tereneckla** [comment]
> > This is not about instant cast spells This is about infinitely spammable, cooldownless item creation proccing it This bug generates as many ooc procs as you can click/macro
> > The link you give also says that tradeskills don't proc, which converting trade items kinda falls into
> 
> It says tradeskills are not supposed to proc it. Which leads me back again to the general question of AC's philosophy: Recreate 3.3.5a version or a "polished modification". If the latter is the case, providing any sources of evidence prior to 3.4.X (classic wotlk) is meaningless from this point onward (for any version-related bug reports). Don't get me wrong: I've watched the video & i see how gamechaning this is. I'm absolutely with you. But there are many instances of these "questionable" mechanics, some of them are as extensive as it would require to rewrite entire actual core mechanics.

Which leads back to me asking why you think that this is 3.3.5a behaviour

**Comment by QuantaCosta** [comment]
> > > This is not about instant cast spells This is about infinitely spammable, cooldownless item creation proccing it This bug generates as many ooc procs as you can click/macro
> > > The link you give also says that tradeskills don't proc, which converting trade items kinda falls into
> > 
> > 
> > It says tradeskills are not supposed to proc it. Which leads me back again to the general question of AC's philosophy: Recreate 3.3.5a version or a "polished modification". If the latter is the case, providing any sources of evidence prior to 3.4.X (classic wotlk) is meaningless from this point onward (for any version-related bug reports). Don't get me wrong: I've watched the video & i see how gamechaning this is. I'm absolutely with you. But there are many instances of these "questionable" mechanics, some of them are as extensive as it would require to rewrite entire actual core mechanics.
> 
> Which leads back to me asking why you think that this is 3.3.5a behaviour

https://www.wowhead.com/wotlk/spell=16864/omen-of-clarity#comments

By 331656 (...) on 2009/10/16 (Patch 3.2.2)
"As people have mentioned, this (and other "on spell cast" procs) will proc off of professions, talent switches, and other non-combat abilities. It does this because everything in wow that has a cast time (and a few things that don't) is considered a spell, as an example, look up a craftable item on here, go to its info page, and then click on the name of the item (not the icon), and you'll end up on the page for the spell that creates that item."

By 370776 (...) on 2009/06/24 (Patch 3.1.3)
"Other people have mentioned this can proc when doing professions.

Omen of Clarity can also proc when switching talent sets."

https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity

Under "Notes" it states:
"Essentially everything except shapeshifting can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability [Lifeblood](https://wowwiki-archive.fandom.com/wiki/Lifeblood) can trigger it."

The first link i posted also mentions OoC procs from virtually anything that is labeled as "spell", proven by video footage.

**Comment by Tereneckla** [comment]
Virtually anything does not mean everything or including converting this stuff

**Comment by QuantaCosta** [comment]
"Other people have mentioned this can proc when doing professions.

You classified essence conversion as "tradeskill".
Professions = Tradeskills (which includes material conversion & crafting processes)

**Comment by Nyeriah** [comment]
Considering how harmful this is to gameplay, it seems like we would rather have this behavior gone regardless of it being a "blizzlike" bug, thus it would fall under those "blizzlike bugs AC fixes".
