### ISSUE TITLE
Lunar Festival Elders Achievement

### ISSUE THREAD

**Issue by Logandros** [azerothcore/azerothcore-wotlk#14775]
### Current Behaviour

Although you can complete the quests as Horde and Alliance, completion only counts toward the achievement related to your current characters faction. Yeah you can talk to and complete the quest cross-faction but it doesn't register towards the achievement. So the quest works, it's just not registering the achievement or achievement progress. TLDR you can get the Horde Elder Achievement as Horde but you cannot get the Alliance Elder Achievement as Horde and both are required for:

https://wotlkdb.com/?achievement=913

### Expected Blizzlike Behaviour

Completing the Elder quests within opposing faction cities should register towards the achievements listed, regardless of the players current faction:

https://wotlkdb.com/?achievement=914
https://wotlkdb.com/?achievement=915

### Steps to reproduce the problem

Login as Horde
Track Achievement https://wotlkdb.com/?achievement=915 Elders of the Alliance
Complete any of the 3 quests, you will see achievement progress does not register and therefore cannot be completed.

### AC rev. hash/commit

AzerothCore rev. 716a822b4821 2023-01-26 14:58:12 -0500 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.81.0
Using MySQL version: 80031
Using CMake version: 3.25.1
Compiled on: Windows 10.0.25284
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in D:/BUILD STUFF/data/az_db_wotlk/maps. Total size: 291014951 bytes
vmaps directory located in D:/BUILD STUFF/data/az_db_wotlk/vmaps. Total size: 658130721 bytes
mmaps directory located in D:/BUILD STUFF/data/az_db_wotlk/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows 10

**Comment by sudlud** [comment]
just tested this on 6cd3b2a32cd97ed6824e8a20891b74e97fe34286
I've  tried to reproduce this issue but to me it seems to work as expected:

- Achievement "Elders of the Horde", relevant Quests:
-> 8677 Darkhorn the Elder
-> 8648 Darkcore the Elder
-> 8678 Wheathoof the Elder

- Achievement "Elders of the Alliance", relevant Quests:
-> 8866 Bronzebeard the Elder
-> 8718 Bladeswift the Elder
-> 8646 Hammershout the Elder

create Level 1 Horde Troll Priest

.level 10 (for achievement menu access)

.quest add 8677
.quest add 8648
.quest add 8678
.quest reward 8677
.quest reward 8648
.quest reward 8678
receive achievement "Elders of the Horde"

.quest add 8866
.quest add 8718
.quest add 8646
.quest reward 8866
.quest reward 8718
.quest reward 8646
receive achievement "Elders of the Alliance"

observe progress of achievement "To Honor One's Elders"

**Comment by sudlud** [comment]
So in my opinion this issue could be closed, as it seems to work in the latest version?

**Comment by Kitzunu** [comment]
Feel free to ping me in disc/here next time
