### ISSUE TITLE
Cant get creature / object from modules via map

### ISSUE THREAD

**Issue by weiyu7615688** [azerothcore/azerothcore-wotlk#14800]
### Current Behaviour

map->GetCreature(ObjectGuid)
map->GetGameObject(ObjectGuid)

### Expected Blizzlike Behaviour

I don't know

### Steps to reproduce the problem

try to use some code like this line
https://github.com/Nelnamara/mod_guildhouse/blob/0ec07426aef85a5233abf87b0659032743fdb45d/src/mod_guildhouse.cpp#L81

### AC rev. hash/commit

tested 10 revisions (1 year back)
from
https://github.com/azerothcore/azerothcore-wotlk/commit/f13723097400d04cc9169dba1403255600bc575a (26/04/2022)
to
https://github.com/azerothcore/azerothcore-wotlk/commit/599e6834a1a852d3c5601c82a0aeffc1ff7c771c (30/04/2021)

### Operating system

 Windows 10 x64

### Custom changes or Modules

https://github.com/azerothcore/mod-guildhouse

**Comment by Nyeriah** [comment]
Exact copy of: https://github.com/azerothcore/azerothcore-wotlk/issues/11539#issuecomment-1408673954

**Comment by acidmanifesto** [comment]
This is a exact dupe/ copypasta of https://github.com/azerothcore/azerothcore-wotlk/issues/11539

Please post anything related on that issue please.
