### ISSUE TITLE
ZulFarrak copy Sandfury Executioner takes all players offline.

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/azerothcore-wotlk#14816]
### Current Behaviour

Kill the Sandfury Executioner and get the Executioner's Key to open the cage. Once the NPC is released, all players will be offline. If the offline player is caused to log in again in the copy, all players will be offline again.

### Expected Blizzlike Behaviour

Kill Sandfury Executioner, get Executioner's Key, open the cage, and wait for NPC to go to the position. Refresh monsters under the stairs to attack NPC and players.

### Steps to reproduce the problem

The player who caused offline in the copy cannot go online, as long as all players will automatically go offline again as soon as they go online.

### AC rev. hash/commit

AzerothCore rev. 69b2fbca74d7+ 2023-01-29 15:14:19 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.74.0
Using MySQL version: 50737
Using CMake version: 3.22.4
Compiled on: Linux 5.4.0-137-generic
Worldserver listening connections on port 8084
Realmlist (Realm Id: 1) configured in port 8084
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014339 bytes
vmaps directory located in ./vmaps. Total size: 658130553 bytes
mmaps directory located in ./mmaps. Total size: 2192911220 bytes
Using zhCN DBC Locale as default. All available DBC locales: enUS koKR frFR deDE zhCN zhTW esES
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-137-generic x86_64)

### Custom changes or Modules

> List enable modules:
- mod-eluna

**Comment by Nyeriah** [comment]
Update your core.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/50e2eb8593bf164f0fbd2cec46bd950eb08c2b04

**Comment by zxnhrdz** [comment]
Thank you very much for your answer.
