### ISSUE TITLE
Segmentation fault (core dumped) when pick up box in Dungeons Blackrock Spire 

### ISSUE THREAD

**Issue by jerrytt** [azerothcore/azerothcore-wotlk#14823]
### Current Behaviour

go to Dungeons Blackrock Spire "Hall of blackhand" - The rookery room:

open "father flame" , and server will crash . Segmentation fault (core dumped)

There is no other information .

set Appender.Server=2,5,0,Server.log,w  ==> Appender.Server=2,6,0,Server.log,w

there no additinal log :

dmesg :

[Tue Jan 31 21:24:49 2023] worldserver[348381]: segfault at 44 ip 0000559a6e7f3414 sp 00007f261edfd400 error 4 in worldserver[559a6de0b000+12ff000] likely on CPU 0 (core 0, socket 0)
[Tue Jan 31 21:24:49 2023] audit: type=1701 audit(1675171489.749:124925): auid=1000 uid=1000 gid=1000 ses=6 pid=348339 comm="worldserver" exe="/home/jtang/azeroth-server/bin/worldserver" sig=11 res=1
[Tue Jan 31 21:52:17 2023] worldserver[373087]: segfault at 44 ip 0000564169b16414 sp 00007fd6707fd400 error 4 in worldserver[56416912e000+12ff000] likely on CPU 0 (core 0, socket 0)
[Tue Jan 31 21:52:17 2023] audit: type=1701 audit(1675173137.223:125045): auid=1000 uid=1000 gid=1000 ses=6 pid=373065 comm="worldserver" exe="/home/jtang/azeroth-server/bin/worldserver" sig=11 res=1

### Expected Blizzlike Behaviour

should pick up the item without crash

### Source

https://github.com/azerothcore/azerothcore-wotlk.git

commit 69b2fbca74d71dd9401ab1acc00f15267b9f8583 (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Sun Jan 29 15:14:19 2023 +0000

    chore(DB): import pending files
    
    Referenced commit(s): 2aeeee9c83c530d45a7d3d124969b980e9ff4072

### Steps to reproduce the problem

very simple:
1. go to Dungeons Blackrock Spire "Hall of blackhand" - The rookery room:
2. open the open "father flame" . server crash.

### AC rev. hash/commit

AC> server debug
AC> AzerothCore rev. 69b2fbca74d7 2023-01-29 15:14:19 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.7 1 Nov 2022 (library: OpenSSL 3.0.7 1 Nov 2022)
Using Boost version: 1.80.0
Using MySQL version: 100904
Using CMake version: 3.25.2
Compiled on: Linux 6.1.6-arch1-3
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna
AC> 

### Operating system

Archlinux

### Custom changes or Modules

- mod-eluna

**Comment by jerrytt** [comment]
![2023-01-31-231040_1591x916_scrot](https://user-images.githubusercontent.com/1201045/215802587-b0b105b9-d26f-468d-b8eb-811426a88133.png)

**Comment by Nyeriah** [comment]
Update your core

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/50e2eb8593bf164f0fbd2cec46bd950eb08c2b04
