### ISSUE TITLE
[Hellfire Peninsula] Trainer Rohok has no trainer dialogue option

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#14820]
### Current Behaviour

Trainer Rohok has no trainer dialogue option even if the player has blacksmithing

### Expected Blizzlike Behaviour

There should be a trainer option, but it looks like there should be some conditions for it to be available.

If the player does not have blacksmithing, then this option should not be available.
https://www.wowhead.com/wotlk/npc=16583/rohok#comments
>By 248848 (182 – 3) on 2008/11/18 (Patch 3.0.3)		
Interestingly, you can't learn Apprentice Blacksmithing from this guy. Maybe this is the case with all the Masters, I don't know.
I quit Jewelcrafting to pick up Blacksmithing, since there were so many JC's in my guild already. I then had to go to the old world to start BS.

https://youtu.be/5ds-iZSSauk?t=101 - 1:42
https://youtu.be/FRMZy227xVI?t=80 - 1:21

I could not find exact information on the conditions for the availability of this option. Maybe it's just the presence of blacksmithing, but maybe also its level should have a certain value.

### Source

https://www.wowhead.com/wotlk/npc=16583/rohok#comments
>By 248848 (182 – 3) on 2008/11/18 (Patch 3.0.3)		
Interestingly, you can't learn Apprentice Blacksmithing from this guy. Maybe this is the case with all the Masters, I don't know.
I quit Jewelcrafting to pick up Blacksmithing, since there were so many JC's in my guild already. I then had to go to the old world to start BS.

https://youtu.be/5ds-iZSSauk?t=101 - 1:42
https://youtu.be/FRMZy227xVI?t=80 - 1:21

### Steps to reproduce the problem

.learn 51300
.setskill 164 450

.go cr 57556

### Extra Notes

Original report: https://github.com/chromiecraft/chromiecraft/issues/4863

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by heyitsbench** [comment]
CC: @Gultask
