### ISSUE TITLE
WLK_Dungeon_The Oculus : dragon summoned by Amber Essence  Ruby Essence or Emerald Essence will float on air , can not be mounted 

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#14837]
### Current Behaviour

as title, 
after kill the boss 1 ,npc should give you 1 item choice of dragon selection. Amber Essence, Ruby Essence , Emerald Essence
use it, dragon summoned will float on air , can not be mounted , then all content after this step can not continue.

### Expected Blizzlike Behaviour

after use this item ,dragon should fly to groud beside player , then can be mounted

### Steps to reproduce the problem

1. go into dungeon The Oculus
2. add item 37859 (37860,37815)
3. use item ,watch the dragon summoned

### AC rev. hash/commit

69b2fbca74d7+

### Operating system

Ubuntu 20.04

**Comment by cctvzj** [comment]
you can test the commit

**Comment by betayi** [comment]
worked, nice job!

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14830
