### ISSUE TITLE
Core/Crash instance object summon

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#14844]
### Current Behaviour

After the sync patch, e.g. opening the Dark Gate and returning to Statholm
The portal crashes when summoning monsters

### Expected Blizzlike Behaviour

https://github.com/azerothcore/azerothcore-wotlk/commit/bf30c66ba48cede909a98cb132959c979c032b3b
The problem can be solved by rolling back the patch

### Source

https://github.com/azerothcore/azerothcore-wotlk/commit/bf30c66ba48cede909a98cb132959c979c032b3b

### Steps to reproduce the problem

1.Go to the dark swamp and wait for the monster to refresh
2.Approach the monster Crash occurs

### Extra Notes

Crash log [7338fc22e0f2+_worldserver.exe_[1-2_14-44-39].txt](https://github.com/azerothcore/azerothcore-wotlk/files/10564024/7338fc22e0f2%2B_worldserver.exe_.1-2_14-44-39.txt)
DMP https://drive.google.com/file/d/1umASgOTSj55s_9W9A5WX54xNXOgoMVpt/view?usp=sharing

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/bf30c66ba48cede909a98cb132959c979c032b3b

### Operating system

Windows Server 2016

**Comment by Nyeriah** [comment]
**Please always update your core before reporting crashes.**

Your core is outdated and needs to be updated. The crash you are reporting has already been fixed here: https://github.com/azerothcore/azerothcore-wotlk/commit/50e2eb8593bf164f0fbd2cec46bd950eb08c2b04

Thanks for your time

**Comment by Kitzunu** [comment]
Also for future reference, always upload your crashlog to GIST so people dont need to download random shit
