### ISSUE TITLE
Assert at login when compiled in DEBUG

### ISSUE THREAD

**Issue by symrwl** [azerothcore/azerothcore-wotlk#14840]
### Current Behaviour

win-10，mysql-8，vs-2022，opessl-3.0.7，cmake-3.25.2，boost-1.81.0。
server info
AzerothCore rev. 7338fc22e0f2 2023-01-30 18:23:06 +0000 (master branch) (Win64, Debug, Static)
Connected players: 2. Characters in world: 2.
Connection peak: 2.
Server uptime: 22 minute(s) 21 second(s)
Update time diff: 10ms, average: 11ms.

`minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(36) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(42) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(36) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(42) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(36) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(42) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(36) : Assertion failed: c >= -1 && c <= 255
minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp(42) : Assertion failed: c >= -1 && c <= 255`

### Expected Blizzlike Behaviour

The compilation and operation are all normal. The above prompt will appear after logging in to the role.
However, all aspects of the game are running normally, only the above prompt appears.
Excuse me, how can I solve the problem prompted by the console?

### Steps to reproduce the problem

Each time you select a character to enter the game, this prompt will appear on the worldserver console.

### AC rev. hash/commit

AzerothCore rev. 7338fc22e0f2 2023-01-30 18:23:06 +0000 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 3.0.7 1 Nov 2022 (library: OpenSSL 3.0.7 1 Nov 2022)
Using Boost version: 1.81.0
Using MySQL version: 80032
Using CMake version: 3.25.2
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/bin/Debug/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Build/bin/Debug/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Build/bin/Debug/Data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows 10 x64

### Custom changes or Modules

There are no changes and modules, and the newly compiled core on January 30.

**Comment by Kitzunu** [comment]
For testing purpose, can you try in RelWithDebInfo? Might be a Debug bug

**Comment by symrwl** [comment]
The above error occurred when compiling with debug before. Now RelWithDebInfo compiles, everything is normal and perfect! thank you!

**Comment by Kitzunu** [comment]
Cannot reproduce
