### ISSUE TITLE
table quest_greeting_locale doesn't work

### ISSUE THREAD

**Issue by xfxfxff** [azerothcore/azerothcore-wotlk#14845]
### Current Behaviour

The greeting of NPC  Tallonkai Swiftroot（塔隆凯·捷根，ID 3567）shows English. I try to translate, and I add a recode into the table "quest_greeting_locale", but it doesn't work, it still shows English not Chinese.
![bug](https://user-images.githubusercontent.com/3389676/216292550-1ef7d6ac-26d4-417f-9a07-30d570b9e63b.png)

### Expected Blizzlike Behaviour

It should show the text that I add into the table "quest_greeting_locale" :
很好$n，很高兴看到像你这样的$c正在积极参与保护森林。

### Steps to reproduce the problem

1. zhCN client
2. Create a Night Elf character
3. Speak to Tallonkai Swiftroot（塔隆凯·捷根）

### AC rev. hash/commit

AzerothCore rev. 7338fc22e0f2+ 2023-01-30 18:23:06 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80032
Using CMake version: 3.22.1
Compiled on: Linux 5.15.79.1-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/xfxfx/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/xfxfx/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/xfxfx/azeroth-server/data/mmaps. Total size: 2192910800 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

ubuntu 20.04

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/216464760-aa2d8d69-a098-46f3-b74f-0ebcc709dab3.png)
如果您能共享本地化数据，我们将非常高兴

**Comment by xfxfxff** [comment]
Thanks for reply!
I only translate two records for experiment. If you need, here is an INSERT sentence that I exported from table quest_greeting_locale:


INSERT INTO `quest_greeting_locale` (`ID`, `type`, `locale`, `Greeting`, `VerifiedBuild`) VALUES
	(2080, 0, 'zhCN', '泰达希尔的创建是个伟大的成就，但是现在世界必须转变以重获平衡。', 0),
	(3567, 0, 'zhCN', '很好$n，很高兴看到像你这样的$c正在积极参与保护森林。', 0);

&nbsp;


陈晓璠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 上午6:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [azerothcore/azerothcore-wotlk] table quest_greeting_locale doesn&#39;t work (Issue #14845)





 

 如果您能共享本地化数据，我们将非常高兴

**Comment by shenkai4257** [comment]
之前好像有一个版本有过说明，说acore有几个数据库不再从_locale进行本地化，可以试试直接在quest_greeting 数据库中进行汉化。从维护方便来看 还是用最初的通过locale数据库进行本地化方便。

**Comment by Nyeriah** [comment]
> 之前好像有一个版本有过说明，说acore有几个数据库不再从_locale进行本地化，可以试试直接在quest_greeting 数据库中进行汉化。从维护方便来看 还是用最初的通过locale数据库进行本地化方便。

Please use English, we cannot understand Chinese.

**Comment by xfxfxff** [comment]
> 之前好像有一个版本有过说明，说acore有几个数据库不再从_locale进行本地化，可以试试直接在quest_greeting 数据库中进行汉化。从维护方便来看 还是用最初的通过locale数据库进行本地化方便。

原来如此，感谢！话说直接汉化quest_greeting表的话，来回切换客户端的语言就做不到了，不理解何故废弃该表。。。

**Comment by xfxfxff** [comment]
> > 之前好像有一个版本有过说明，说acore有几个数据库不再从_locale进行本地化，可以试试直接在quest_greeting 数据库中进行汉化。从维护方便来看 还是用最初的通过locale数据库进行本地化方便。
> 
> Please use English, we cannot understand Chinese.

he/she said Azerothcore's localization no longer reads tables *_locale from a previous version

**Comment by acidmanifesto** [comment]
它最後一次工作是什麼時候？
When was the last time it worked?

**Comment by Roxtedy** [comment]
> 它最後一次工作是什麼時候？ Когда в последний раз это работало?

Never

**Comment by Roxtedy** [comment]
> 它最後一次工作是什麼時候？ When was the last time it worked?

problem has been going on since 2022

**Comment by acidmanifesto** [comment]
> > 它最後一次工作是什麼時候？ When was the last time it worked?
> 
> problem has been going on since 2022

Was it not a problem before 2022? It would be helpful to know so we can narrow down any commits that may of broke it.

**Comment by Roxtedy** [comment]
> Was it not a problem before 2022? It would be helpful to know so we can narrow down any commits that may of broke it.

I do not know, but the first mention was on March 6

**Comment by acidmanifesto** [comment]
> > Was it not a problem before 2022? It would be helpful to know so we can narrow down any commits that may of broke it.
> 
> I do not know, but the first mention was on March 6

Thank you. That will be a good start for us to look at.

**Comment by Roxtedy** [comment]
> > > Was it not a problem before 2022? It would be helpful to know so we can narrow down any commits that may of broke it.
> > 
> > 
> > I do not know, but the first mention was on March 6
> 
> Thank you. That will be a good start for us to look at.

I checked the version dated Mar 6, 2022. I started with a comment azerothcore#10526 where the quest_greetingstable function was implemented. My test showed that it initially does not work. I checked the version from TC everything works there. I checked the fix #14532 from Jan 7, 2023, it also did not fix the problem.

**Comment by Roxtedy** [comment]
> Is it only an issue with chinese client?

At moment, only the russian and chinese clients are known

**Comment by Roxtedy** [comment]
Sorry i have no way to check the korean(krKR) client

**Comment by Roxtedy** [comment]
I want to add that there is a Spanish translation even if the quest_greeting_locale table is empty. It doesnt disappear

**Comment by Siigonis** [comment]
The Russian database has the same problems. I found that greetings in Azeroth should be translated in the npc_text_locale section. 
![image](https://user-images.githubusercontent.com/129796104/229792358-ea104044-28f7-4fc1-bdf9-b0f3fa2146f3.png)
![image](https://user-images.githubusercontent.com/129796104/229792418-3af41f2d-64f9-4b20-9b86-85aa1a1b29b7.png)

**Comment by coachkoganal-art** [comment]
The same goes for the Russian client, the table doesn't work, and it takes the value from npc_text
