### ISSUE TITLE
[IcecrownCitadel] professor putricide disappeared after killing rotface or festergut!

### ISSUE THREAD

**Issue by tcct1234** [azerothcore/azerothcore-wotlk#14854]
### Current Behaviour

[IcecrownCitadel] professor putricide disappeared after killing rotface or festergut!

### Expected Blizzlike Behaviour

professor putricide will not disappear

### Steps to reproduce the problem

kill rotface or festergut

### AC rev. hash/commit

AzerothCore rev. c3dd1b7a5ca0 2023-02-01 10:11:28 -0300 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.81.0
Using MySQL version: 80032
Using CMake version: 3.24.202208181-MSVC_2
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in D:/dataac/maps. Total size: 291014339 bytes
vmaps directory located in D:/dataac/vmaps. Total size: 658130553 bytes
mmaps directory located in D:/dataac/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

 Windows 10 x64

**Comment by Kitzunu** [comment]
Easy win

**Comment by tcct1234** [comment]
You can't reach the final boss without killing professor putricide

**Comment by XiongTianyi0116** [comment]
the same~can't see professor putricide

**Comment by ZhxChen** [comment]
can't see professor putricide

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14862#event-8439007810
