### ISSUE TITLE
[The Shattered Halls] Missing Target Dummies in Sparring Hall

### ISSUE THREAD

**Issue by v-mstrs** [azerothcore/azerothcore-wotlk#14874]
### Current Behaviour

No target dummies

### Expected Blizzlike Behaviour

Target dummies in Sparring hall

### Source

https://youtu.be/luwriRn_eQ8?t=233 
https://youtu.be/gAhZe5QEgLc?t=1488

### Steps to reproduce the problem

Go to Sparring Hall inside The Shattered Halls

### AC rev. hash/commit

716a822b4821

### Operating system

Linux Mint 21.1

### Custom changes or Modules

None

**Comment by Gultask** [comment]
Like other dungeons in TBC-era. Shattered Halls is highly custom and has not made use of any sniffs in its initial construction. It'll receive a rework. Although I'm not sure if we'll be able to re-create it exactly with the current system we have in store for AC
