### ISSUE TITLE
Quest: enticing negolash

### ISSUE THREAD

**Issue by unrealking04** [azerothcore/azerothcore-wotlk#1488]
Quest: enticing negolash

##### SMALL DESCRIPTION:
the quest cannot be completed

##### CURRENT BEHAVIOUR:
the ruined lifeboat, object situed in x -14653 y 152,51 z 3,68 map 0
cannot permit to complete the quest

##### STEPS TO REPRODUCE THE PROBLEM:
1.go to x -14653 y 152,51 z 3,68 map 0
2. .add 4457 10;
3.add 4595 5
4.speek to ruined lifeboat

##### BRANCH(ES):
commit: https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

##### OPERATING SYSTEM:
LINUX

**Comment by Nefertumm** [comment]
Same thing that your other issue, please, give us more info about the quest, like the id or a link to a wotlk database. Thanks!

**Comment by FrancescoBorzi** [comment]
closing until reporter fix the report

**Comment by sudlud** [comment]
quest is completable on 9bf77e86604a0cf0342370393e72cba4adc6b256

.go xyz -14654 150 4 0
.q add 8554
.additem 4457 10
.additem 4595 5
open quest menu on the boat
hand in quest `enticing negolash`, observe negolash spawning to be killed for quest 8554
