### ISSUE TITLE
[Crash] 80000003 BREAKPOINT

### ISSUE THREAD

**Issue by Valoriaz** [azerothcore/azerothcore-wotlk#14888]
### Current Behaviour

My Worldserver randomly crashes with the Errorcode : 80000003 BREAKPOINT and the  Fault address:  00007FFA40D4ACE2 01:0000000000069CE2 C:\Users\Administrator\Desktop\Server\Server\libmysql.dll

1-3 Players are Online when this Happen

### Expected Blizzlike Behaviour

Didnt Crash

### Steps to reproduce the problem

Didnt know how to reproduce - Here are all my crashes from Yesterday and Today

https://gist.github.com/Valoriaz/b0f0401d860d4b012f32c9e86ae74d03

### AC rev. hash/commit

AzerothCore rev. b80470545da4 2023-02-05 12:39:37 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.7 1 Nov 2022 (library: OpenSSL 3.0.7 1 Nov 2022)
Using Boost version: 1.81.0
Using MySQL version: 80032
Using CMake version: 3.25.2
Compiled on: Windows 10.0.17763
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Win Server 2019

### Custom changes or Modules

> List enable modules:
- mod-account-achievements
- mod-accountbound
- mod-autobalance
- mod-cfbg
- mod-individual-xp
- mod-learn-spells
- mod-reagent-bank
- mod-reward-played-time
- mod-solo-lfg
- mod-solocraft
- mod-transmog
- mod-weekend-xp

**Comment by acidmanifesto** [comment]
Quick look via mobile suggest reward play time module on all of them.
```
00007FF726BDE30D 00000044DF1FF8E0 reward_system::OnBeforeUpdate+18D C:\Users\Administrator\Desktop\Server\Source\azerothcore-wotlk\modules\mod-reward-played-time\src\reward_system.cpp line 44
```

**Comment by Valoriaz** [comment]
Update the gist Link

**Comment by Valoriaz** [comment]
> Quick look via mobile suggest reward play time module on all of them.
> 
> ```
> 00007FF726BDE30D 00000044DF1FF8E0 reward_system::OnBeforeUpdate+18D C:\Users\Administrator\Desktop\Server\Source\azerothcore-wotlk\modules\mod-reward-played-time\src\reward_system.cpp line 44
> ```

had the same issue with ahbot aswell - i tried to recompile without the ahbot but same issue

**Comment by acidmanifesto** [comment]
The logs would suggest its trying to access a table that isnt there.
Did u apply the sql to the characters table from the module?

https://github.com/azerothcore/mod-reward-played-time/blob/master/sql/characters/reward_system.sql

**Comment by Valoriaz** [comment]
yep, and for ahbot aswell

**Comment by acidmanifesto** [comment]
> yep, and for ahbot aswell

Please double check. Your call stack dealing with the abort shows the sql returning a null and not finding the table.

https://gist.github.com/Valoriaz/b0f0401d860d4b012f32c9e86ae74d03#file-b80470545da4_worldserver-exe_-5-2_15-49-36-txt-L247

**Comment by Valoriaz** [comment]
the Table exist..i "re-apply" the sqls and wait for the reward ingame..if the error occours I reply here

**Comment by Nyeriah** [comment]
> > > Quick look via mobile suggest reward play time module on all of them.
> > > ```
> > > 00007FF726BDE30D 00000044DF1FF8E0 reward_system::OnBeforeUpdate+18D C:\Users\Administrator\Desktop\Server\Source\azerothcore-wotlk\modules\mod-reward-played-time\src\reward_system.cpp line 44
> > > ```
> > 
> > 
> > had the same issue with ahbot aswell - i tried to recompile without the ahbot but same issue
> 
> https://github.com/azerothcore/mod-reward-played-time/blob/master/src/reward_system.cpp#L44
> 
> Did u apply the sqls from the modules?

Bad syntax in the query linked here, param should not be in quotes

**Comment by Valoriaz** [comment]
My server run smooth 24 hours. Re-batch the sql fix my crashes - Thank you all for the quick response and help. 😃
