### ISSUE TITLE
Unable to Start Auth/World

### ISSUE THREAD

**Issue by SoulSeekkor** [azerothcore/azerothcore-wotlk#14882]
### Current Behaviour

I'm not sure which commit broke things but roughly a week or so ago I did a pull and rebuilt the server from source (I do so regularly) and after rebuild I cannot start authserver or worldserver.

Both simply output this and stop:
Wrong Loggers configuration. Review your Logger config section.
Creating default loggers [root (Error), server (Info)] to console

This makes no sense, no changes have been made to the config files, the worldserver.conf.dist exists and the logging section matches yours and I only modify worldserver.conf which doesn't even have any of those settings changed.

### Expected Blizzlike Behaviour

It would start like it did before a week or two ago as I haven't changed anything expect did a git pull.

### Steps to reproduce the problem

Honestly I don't know, I've blown away the 'build' folder and rebuilt from scratch and it simply doesn't start, no logs are generated except the message which does no help... The logger section is there with all default settings, I haven't changed that.

### AC rev. hash/commit

58f0f86292ec93029dbbe99a7dc91524ebaaa9f9

### Operating system

Ubuntu 20.04.5

### Custom changes or Modules

|   +- mod-ah-bot
  |   +- mod-autobalance
  |   +- mod-character-tools
  |   +- mod-congrats-on-level
  |   +- mod-guildhouse
  |   +- mod-money-for-kills
  |   +- mod-reagent-bank-account
  |   +- mod-solo-lfg
  |   +- mod-solocraft
  |   +- mod-starter-guild
  |   +- mod-transmog

**Comment by Kitzunu** [comment]
Add those settings to .conf

.dist is not read anymore

**Comment by SoulSeekkor** [comment]
I was afraid of that, could I have some insight as to the change?  Was it Docker related?  This makes managing the server much more difficult from a source perspective, having the separate conf file for overrides only worked quite nice and cleanly and negated breaking changes/additions to the rest of the config.

**Comment by Kitzunu** [comment]
No, more so that we already initialize 99% of all configs in the core already, and having the .dist allows mismatching core + dist. The .conf file still just works as a override apart for the 1% we cant initialize through the core

**Comment by SoulSeekkor** [comment]
So I only need to add that Logger section (and whatever it may complain about after) to my conf file?  I noticed with authserver.conf I pretty much added the entire thing in there to get it to run again.

**Comment by Kitzunu** [comment]
Yea, as I said anything that doesnt have default values in core and is critical for run.

It can and will complain about all missing, but wont stop working

**Comment by SoulSeekkor** [comment]
Looks like I have to include the entire config, it complains about basically every setting not being there on start unfortunately; super ugly.  I don't know if there's something to have feedback for this but the way it used to be was super clean and easy to manage, this is incredibly unclear what's happening and not intuitive... Just my 2 cents.  Thank you for the help to get this running again, but this feels incredibly dirty.

**Comment by Kitzunu** [comment]
Yes it complaints they are not there, but it wont break anything

**Comment by SoulSeekkor** [comment]
Sounds good thanks again!  Any chance the non-required ones could be yellow warnings instead of the red text in the console?  Looks like a mass of issues to correct and they keep popping up (I'd just moved to using the entire config to avoid it).  I did notice that many of the messages that state a config value is missing suggests a default value that doesn't match up with the .dist file as well?
