### ISSUE TITLE
Quest: Stone of Inner Binding

### ISSUE THREAD

**Issue by unrealking04** [azerothcore/azerothcore-wotlk#1489]
<
![screenshot 20](https://user-images.githubusercontent.com/47576138/52959975-f8472080-3397-11e9-8197-03ba4a0675b2.png) the object haven't the interrogative and esclamative symbol
>

<the quest is completable but i can see the yellow interrogative symbol and found it with carbonite

##### SMALL DESCRIPTION:
<the quest is completable but i can see the yellow interrogative symbol and found it with carbonite>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
<the stone must have the symbol of quest complete>

##### STEPS TO REPRODUCE THE PROBLEM:
<1.have the quest breaking the keystone
  2.additem rod of order
  3. go to x:-1532 y:-2164 z:17 map 0

##### BRANCH(ES):

master

##### OPERATING SYSTEM:
linux

##### MODULES:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by Nefertumm** [comment]
Can you bring us more info about the object (entry at least)?

**Comment by Maurowin** [comment]
you are lvl 80 maybe its low level quest. Low level quests are not displayed with the exclamation mark

**Comment by FrancescoBorzi** [comment]
closing until reporter fix the report
