### ISSUE TITLE
ICC and Ruby Sanctum ，No heroic difficulties.

### ISSUE THREAD

**Issue by weiyu7615688** [azerothcore/azerothcore-wotlk#14895]
### Current Behaviour

ICC and Ruby Sanctum ，cant access to the heroic difficulties.

### Expected Blizzlike Behaviour

i dont konw

### Steps to reproduce the problem

I compiled the latest source code，Still inaccessible.

### AC rev. hash/commit

#6e8e70a

### Operating system

win10

### Custom changes or Modules

tranmog

**Comment by Nyeriah** [comment]
Please explain your issue in detail. Add screenshots if you feel like it would help understanding what your problem is.

**Comment by Kitzunu** [comment]
You need to complete the appropriate achievement to access HC versions of these raids.
