### ISSUE TITLE
The boss level of Valentine's Day and Wine Festival is incorrect.

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/azerothcore-wotlk#14899]
### Current Behaviour

Apothecary Hummel --- Grade 62
Coren Direbrew --- Grade 60

### Expected Blizzlike Behaviour

Apothecary Hummel --- Grade 82
Coren Direbrew --- Grade 80

### Steps to reproduce the problem

When the player's role level is 80, there is no difficulty because the boss level is too low. As a result, the fighting process will soon end.

### AC rev. hash/commit

AzerothCore rev. 6e8e70aa1a55+ 2023-02-07 16:44:17 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.74.0
Using MySQL version: 50737
Using CMake version: 3.22.4
Compiled on: Linux 5.4.0-137-generic
Worldserver listening connections on port 8084
Realmlist (Realm Id: 1) configured in port 8084
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014339 bytes
vmaps directory located in ./vmaps. Total size: 658130553 bytes
mmaps directory located in ./mmaps. Total size: 2192911220 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Ubuntu 20.04.3 LTS

### Custom changes or Modules

> List enable modules:
- mod-eluna

**Comment by heyitsbench** [comment]
First off, please attach sources to any and every issue you make where applicable.

Second off, as of e7e119283 both of these creatures have the levels you say is expected. You have some sort of custom changes in your DB changing the creature levels.
