### ISSUE TITLE
Perry Gatner does not seem to perform in the World's End Tavern.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#14913]
### Current Behaviour

No performance in the World's End Tavern.

### Expected Blizzlike Behaviour

Perry Gatner should perform stand-up comedy skits/routines in the tavern every so often, varying depending on the day. Shattrath Saul should also introduce Gatner beforehand.

### Source

[Wowpedia](https://wowpedia.fandom.com/wiki/Perry_Gatner?oldid=2517313)

### Steps to reproduce the problem

1. `.tele shattrath`
2. Go to the tavern.
3. Wait.
4. Observe no performance.

### AC rev. hash/commit

e7e119283f776746f34f409480c567e87f078483

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Kitzunu** [comment]
This should be scripted. Perhaps the times are screwed? Try to start event 86 manually

**Comment by heyitsbench** [comment]
> This should be scripted.

You are somewhat right, my mistake. It does have quite a lot of issues with it though (unsurprisingly), I take it I should just open a new issue for those?

**Comment by Kitzunu** [comment]
E
Asies
T that way
