### ISSUE TITLE
Error when doing a new installation [1054] Unknown column 'ProcFlags' in 'field list'

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#14935]
### Current Behaviour

When compiling the source code and executing the worldserver (Everything from 0) it automatically executes the implementations and updates automatically from the database everything does well, but when Loading Spell Proc Conditions and Data... it shows the following error

Loading Spell Proc Conditions and Data...
[1054] Unknown column 'ProcFlags' in 'field list'
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
Caught signal 6

LOG: https://gist.github.com/Tony931023/7947937ad42ae5a355ebcac96153473f

### Expected Blizzlike Behaviour

*

### Steps to reproduce the problem

1 - make a new clean build
2 - run worldserver

### Extra Notes

Server version: 10.6.12-MariaDB-1:10.6.12+maria~ubu2004 mariadb.org binary distribution

### AC rev. hash/commit

AzerothCore rev. 77f63d582d4a 2023-02-09 10:30:27 -0500

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
AzerothCore rev. d336b63f50e8 2023-02-10 21:33:14 +0000 (testbranch branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.80.0
Using MySQL version: 80028
Using CMake version: 3.22.2
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /build/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in /build/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /build/bin/RelWithDebInfo/data/mmaps. Total size: 2192912164 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

Works.
Probably an outdated module or something you are using
