### ISSUE TITLE
[IcecrownCitadel]Lichking Spell Harvest Soul Bug

### ISSUE THREAD

**Issue by ZhxChen** [azerothcore/azerothcore-wotlk#14933]
### Current Behaviour

Lichking's 3rd  phase (10 normal), the Lich King casts a spell called "Harvest Soul"（ID:68980). Players hit this skill and did not teleport to Frostmourne inside.
In 10 Heroic, the Lich King continues to casts the spell "Harvest Soul"  （ID:74296).until all players are dead.

### Expected Blizzlike Behaviour

 Lich King casts a spell called "Harvest Soul", If the player not die will be teleport to Frostmourne inside.

### Source

https://youtu.be/plGSe-sE398?t=539

### Steps to reproduce the problem

1.Lichking's 3rd  phase
2.Lich King casts a spell called "Harvest Soul"

### AC rev. hash/commit

 b491b2f6f8d5

### Operating system

ubuntu22.04

**Comment by Lhw-Arthas** [comment]
The same in 25 heroic.

**Comment by ZhxChen** [comment]
roll back to Dec 2022 version

**Comment by Dr-Arayashiki** [comment]
If I knew how to work with it it could help, but I think it's in the LK Script :(

**Comment by qwe900** [comment]
#15573
