### ISSUE TITLE
[QUEST] Meats to Orgrimmar

### ISSUE THREAD

**Issue by zato90** [azerothcore/azerothcore-wotlk#1494]
##### SMALL DESCRIPTION:
the NPC Zargh doesn't give the quest

##### EXPECTED BLIZZLIKE BEHAVIOUR:
speak whith Zargh and accept the quest
https://vanilla-twinhead.twinstar.cz/?quest=6365

##### CURRENT BEHAVIOUR:
can't see the exclamative point and the NPC doesn't give the quest

##### STEPS TO REPRODUCE THE PROBLEM:
1- go to 52.6, 29.8 in the barrens
2- speak to Zargh
3- accept the quest

##### BRANCH(ES):
staging

##### AC HASH/COMMIT:
commit 987095e
##### OPERATING SYSTEM:
linux

**Comment by comix1988** [comment]
@zato90 
This quest is only assigned to orcs or trolls.
Maybe you're tauren or blood elf or undead?

**Comment by FrancescoBorzi** [comment]
Closing unless it gets confirmed
