### ISSUE TITLE
boss "Kirtonos the Herald"   sommoned out of instance_scholomance. never show up.

### ISSUE THREAD

**Issue by jerrytt** [azerothcore/azerothcore-wotlk#14944]
### Current Behaviour

Quest - http://old.wowhead.com/quest=5384
Item to summon him - http://old.wowhead.com/item=13523
BOSS: https://www.wowhead.com/npc=10506/kirtonos-the-herald

src/server/scripts/EasternKingdoms/Scholomance/instance_scholomance.cpp
Position KirtonosSpawn = Position(315.028, 70.5385, 102.15, 0.385971);

on my server this Position is out of  instance_scholomance . 
and after give the task item , boss never show. 

.go xyz  315.028 70.5385 102.15 289
this cmd will teleport out of instance .

### Expected Blizzlike Behaviour

boss should show

### Steps to reproduce the problem

.go xyz  315.028 70.5385 102.15 289
.additem 13523

click the fire. boss never show up.

### AC rev. hash/commit

AzerothCore rev. 0ed7813e84f5+ 2023-02-05 00:05:20 +0100 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
Calendar deletion of old events.
Starting up Auction House Listing thread...
AC> .server debug
AC> AzerothCore rev. 0ed7813e84f5+ 2023-02-05 00:05:20 +0100 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.7 1 Nov 2022 (library: OpenSSL 3.0.7 1 Nov 2022)
Using Boost version: 1.81.0
Using MySQL version: 100904
Using CMake version: 3.25.2
Compiled on: Linux 
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

archlinux

**Comment by patou01** [comment]
Can confirm the issue on latest.

I suspect there's been a change in the AI handling recently that is causing this. The script seems to never start. The boss is supposed to spawn, fly around a bit and then come inside. I'll look a bit further into it and see for a fix.
