### ISSUE TITLE
Core/Characters: normalizePlayerName

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#14955]
### Current Behaviour

Now there is normalizePlayerName() and CheckPlayerName().

We should have these checks in CheckPlayerName() to send the correct error message
### Expected Blizzlike Behaviour

-

### Steps to reproduce the problem

-

### AC rev. hash/commit

AzerothCore rev. 515d35bd003a+ 2023-02-12 02:25:18 +0100 (testbranch branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1o  3 May 2022 (library: OpenSSL 1.1.1o  3 May 2022)
Using Boost version: 1.80.0
Using MySQL version: 80028
Using CMake version: 3.22.2
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /build/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in /build/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /build/bin/RelWithDebInfo/data/mmaps. Total size: 2192912164 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

W11

**Comment by Kitzunu** [comment]
There's no need for this.
Client does these checks already for char creation

**Comment by heyitsbench** [comment]
What about hacking attempts/client edits?

**Comment by Kitzunu** [comment]
They are still checked on account creation with normalizePlayerNames. I wanted to add the check into CheckPlayerName just to send a correct error message, but it is pointless.
