### ISSUE TITLE
[Netherstorm] Kirin'Var Apprentice not casting abilities

### ISSUE THREAD

**Issue by v-mstrs** [azerothcore/azerothcore-wotlk#14960]
### Current Behaviour

Kirin'Var Apprentice not casting abilities

### Expected Blizzlike Behaviour

Kirin'Var Apprentice casting Throw Hammer and occasionally Hammer Stun

### Source

https://youtu.be/CTraItJtIlQ?t=13
https://www.wowhead.com/wotlk/npc=20409/kirinvar-apprentice#abilities

### Steps to reproduce the problem

Interact with mob

### AC rev. hash/commit

1738e242e498

### Operating system

Linux Mint 21.1

**Comment by avarishd** [comment]
After watching a bunch of videos, there was not a single time where Throw Hammer was casted or applies.
Maybe @heyitsbench can shed some light?
