### ISSUE TITLE
Еndless enchantments

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#1497]
##### SMALL DESCRIPTION:
Еndless enchantments.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After using must be disappear.

##### CURRENT BEHAVIOUR:
Can be used infinity.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Using items:
44874
44872
44873
44871
44879
44878
44877
44876

##### BRANCH(ES):
AzerothCore rev. 23d78ce6bc75 2019-02-18 18:22:36 +0700 (master branch) (Win64, Release)

**Comment by poszer** [comment]
Closing this.  I can't understand the issue reported. 
Next time provide more details, how we can reproduce this problem. 
Anyway, thanks for report @Mitradis

**Comment by Helias** [comment]
Confirmed, they don't disappear

**Comment by poszer** [comment]
Ok, know what's the problem. Will post fix soon

**Comment by poszer** [comment]
@Mitradis  Could you please test the referenced PR.

**Comment by Mitradis** [comment]
yes #1590 is same, this thread can be close

**Comment by poszer** [comment]
@Mitradis Did it fix your opened issue?

**Comment by poszer** [comment]
You provide wrong ID's. All of them are marked as '' This item is not available to players.'' . 
Use other ID's for correct Enchantment.
Closing this
