### ISSUE TITLE
Peeling crocodiles in BlackMorass, no skins but have a small probability of producing gems

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#14985]
### Current Behaviour

.go c 36942
kill and try peeling the crocodiles, alomost no skins(less then 1%) , but have a small probability of  get gems
this happened after later week update

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 65f031c34017+ 2023-02-12 23:43:33 -0300 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.64-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-save-inventory
- mod-server-auto-shutdown

### Operating system

debian 11 x64

**Comment by acidmanifesto** [comment]
Whats the source for the skinning and gem loot?
Please dont say wowhead.

**Comment by Tereneckla** [comment]
Saying they should have a 100% chance of scraps or leather and no gems at all just is sensible
Doesn't need a source

**Comment by kissingers** [comment]
Who learn the skinning skill 32678,  .go c 36942,  kill the crocodiles around and skinning the died crocodiles body, will get little skins such as  item id 21887(<1%) , but might get gems such as item id 32229.

**Comment by kissingers** [comment]
Normaly will get more skins such as item id 21887, and will not get gems such as item id 32229.

**Comment by Gultask** [comment]
> this happened after later week update

Yeah they were using the wrong IDs previously. I'll fix that.

**Comment by Gultask** [comment]
![image](https://user-images.githubusercontent.com/100873791/218564652-2257214e-2de9-456c-96c9-36294e9d8f06.png)

??? Who made this???
