### ISSUE TITLE
[Quest] That's Abominable! - Causes world server to crash

### ISSUE THREAD

**Issue by DarkLordExodus** [azerothcore/azerothcore-wotlk#14984]
### Current Behaviour

On this quest you are supposed to kill Hulking Abominations in Icecrown, however as soon as you kill this mob the world server crashes. This is the crash report that I get once you kill this mob:

Revision: AzerothCore rev. 65f031c34017 2023-02-12 23:43:33 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Date 12:2:2023. Time 21:53 
//=====================================================
*** Hardware ***
Processor: Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz
Number Of Processors: 24
Physical Memory: 67074240 KB (Available: 54719796 KB)
Commit Charge Limit: 77035712 KB

*** Operation System ***
Windows 10 Professional (Version 10.0, Build 19045)

//=====================================================
Exception code: C00000FD STACK_OVERFLOW
Fault address:  00007FF683E46637 01:0000000000F75637 C:\AzerothCore\Build\bin\RelWithDebInfo\worldserver.exe

Registers:
RAX:00000000000041D0
RBX:000001C266045A20
RCX:000001C2656D9C48
RDX:000001C25E9E0440
RSI:0000000000000000
RDI:000001C25E9E0440
R8: 0000000000000000
R9: 000000A8D2001000
R10:000000A8D2003000
R11:0000000000000000
R12:0000000000000000
R13:000001C2656D9C48
R14:0000000000000000
R15:000001C200000001
CS:RIP:0033:00007FF683E46637
SS:RSP:002B:00000000D2005FB8  RBP:66045A20
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010287

Call stack:
Address   Frame     Function      SourceFile

### Expected Blizzlike Behaviour

You should be able to kill this mob to obtain Chilled abomination guts.
![image](https://user-images.githubusercontent.com/63383032/218368267-3e6bb85d-d48d-417d-9403-6c8d146510a3.png)

### Steps to reproduce the problem

- Kill any Hulking Abomination in Icecrown
![image](https://user-images.githubusercontent.com/63383032/218369085-b43a08cd-39ef-42c6-b1c4-f6391bf75c75.png)

### AC rev. hash/commit

![image](https://user-images.githubusercontent.com/63383032/218369639-8156c0bb-ef50-459b-93f5-68a80914f31a.png)

### Operating system

Windows 10  x64

### Custom changes or Modules

Transmog Module

**Comment by Tony931023** [comment]
Exactly when you have quest 13264 it crashes the server in my case to make it crash I had to do several tests

ex:
1 - q a 13264
2 - kill Hulking Abominations in Icecrown

sometimes it crashes the first time, other times it crashes like this:

1 - q  a 13264
2- q c 13264
3 - kill Hulking Abominations in Icecrown
4 - Leave the quest
5 - q a to 13264
6 - kill Hulking Abominations in Icecrown

**Comment by Tony931023** [comment]
Crash Log: https://raw.githubusercontent.com/ShadowNet-Cuba/crash/master/gdb.txt

**Comment by UltraNix** [comment]
@Tony931023 Tested and got 0 crashes. Please submit some video.

**Comment by DarkLordExodus** [comment]
The issue has been resolved with the latest build.
