### ISSUE TITLE
[Crash]  Server Crash 0213

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#14989]
### Current Behaviour

[gdb.zip](https://github.com/azerothcore/azerothcore-wotlk/files/10722626/gdb.zip)

Since I can't upload log to gist.github.com ,so I have to upload here.
The crash maybe cased by blacktemplate laster second bosses( 4 boss) 

some messenge:
Thread 8 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb5bff700 (LWP 3160341)]
0x0000000000ff8749 in std::vector<unsigned char, std::allocator<unsigned char> >::_M_default_append (this=<optimized out>, __n=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/vector.tcc:613
613	    {
#0  0x0000000000ff8749 in std::vector<unsigned char, std::allocator<unsigned char> >::_M_default_append (this=<optimized out>, __n=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/vector.tcc:613
#1  0x0000000000000001 in ?? ()
#2  0x0000000000000005 in ?? ()
#3  0x000000000126892b in ByteBuffer::append (this=<error reading variable: Unhandled dwarf expression opcode 0xff>, src=<error reading variable: DWARF-2 expression error: DW_OP_GNU_uninit must always be the very last op.>, cnt=<error reading variable: DWARF-2 expression error: DW_OP_GNU_uninit must always be the very last op.>) at /root/acore/src/server/shared/Packets/ByteBuffer.cpp:134
#4  0x0000000000b4e90e in ChatHandler::BuildChatPacket (data=<error reading variable: Unhandled dwarf expression opcode 0xff>, chatType=<error reading variable: Unhandled dwarf expression opcode 0xb4>, language=<error reading variable: Unhandled dwarf expression opcode 0xb4>, senderGUID=..., receiverGUID=..., message="干得好！", chatTag=<optimized out>, senderName="击碎者加西奥斯", receiverName="", achievementId=0, gmMessage=<optimized out>, channelName="") at /root/acore/src/server/game/Chat/Chat.cpp:200
#5  0x0000000000b4e204 in ChatHandler::BuildChatPacket (data=..., chatType=<optimized out>, language=<optimized out>, sender=<optimized out>, receiver=<error reading variable: Unhandled dwarf expression opcode 0xb4>, message="干得好！", achievementId=<optimized out>, channelName="", locale=LOCALE_zhCN) at /root/acore/src/server/game/Chat/Chat.cpp:298
#6  0x000000000115a1b5 in CreatureTextBuilder::operator() (this=<optimized out>, data=<error reading variable: Unhandled dwarf expression opcode 0xff>, locale=<error reading variable: Unhandled dwarf expression opcode 0xff>) at /root/acore/src/server/game/Texts/CreatureTextMgr.cpp:39
#7  0x0000000001159e1c in CreatureTextLocalizer<CreatureTextBuilder>::operator() (this=<error reading variable: Unhandled dwarf expression opcode 0xff>, player=<error reading variable: Unhandled dwarf expression opcode 0xff>) at /root/acore/src/server/game/Texts/CreatureTextMgr.h:150
#8  0x000000000115ac0d in Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >::Visit (this=<error reading variable: Unhandled dwarf expression opcode 0xff>, m=...) at /root/acore/src/server/game/Grids/Notifiers/GridNotifiers.h:601
#9  VisitorHelper<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, Player> (v=<error reading variable: Unhandled dwarf expression opcode 0xff>, c=...) at /root/acore/src/common/Dynamic/TypeContainerVisitor.h:44
#10 VisitorHelper<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > (v=..., c=...) at /root/acore/src/common/Dynamic/TypeContainerVisitor.h:50
#11 VisitorHelper<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > (v=<error reading variable: Unhandled dwarf expression opcode 0xff>, c=...) at /root/acore/src/common/Dynamic/TypeContainerVisitor.h:51
#12 VisitorHelper<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (v=..., c=...) at /root/acore/src/common/Dynamic/TypeContainerVisitor.h:57
#13 TypeContainerVisitor<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > >::Visit (this=<error reading variable: Unhandled dwarf expression opcode 0xab>, c=...) at /root/acore/src/common/Dynamic/TypeContainerVisitor.h:91
#14 Grid<Player, TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> > > (this=<optimized out>, visitor=...) at /root/acore/src/server/game/Grids/Grid.h:96
#15 NGrid<8u, Player, TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::VisitGrid<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > (this=<optimized out>, x=<optimized out>, y=<error reading variable: Unhandled dwarf expression opcode 0xab>, visitor=...) at /root/acore/src/server/game/Grids/NGrid.h:103
#16 0x000000000115a8b9 in Map::Visit<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > > (this=<error reading variable: Unhandled dwarf expression opcode 0xff>, cell=<error reading variable: Unhandled dwarf expression opcode 0xff>, visitor=<error reading variable: Unhandled dwarf expression opcode 0xff>) at /root/acore/src/server/game/Maps/Map.h:877
#17 Cell::VisitCircle<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > > (this=<optimized out>, visitor=<error reading variable: Unhandled dwarf expression opcode 0xff>, map=<error reading variable: Unhandled dwarf expression opcode 0xff>, begin_cell=..., end_cell=...) at /root/acore/src/server/game/Grids/Cells/CellImpl.h:143
#18 0x000000000115a57e in Cell::Visit<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > > (this=<error reading variable: Unhandled dwarf expression opcode 0xff>, standing_cell=<error reading variable: Unhandled dwarf expression opcode 0xff>, visitor=..., map=..., x_off=<error reading variable: Unhandled dwarf expression opcode 0xff>, y_off=<error reading variable: Unhandled dwarf expression opcode 0xff>, radius=<error reading variable: Unhandled dwarf expression opcode 0xb0>) at /root/acore/src/server/game/Grids/Cells/CellImpl.h:101
#19 0x000000000115a063 in Cell::Visit<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> >, TypeMapContainer<TypeList<GameObject, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > > > > > (this=0x7fffb5400690, standing_cell=..., visitor=..., map=..., obj=<error reading variable: Unhandled dwarf expression opcode 0xff>, radius=<optimized out>) at /root/acore/src/server/game/Grids/Cells/CellImpl.h:66
#20 Cell::VisitWorldObjects<Acore::PlayerDistWorker<CreatureTextLocalizer<CreatureTextBuilder> > > (center_obj=<optimized out>, visitor=<error reading variable: Asked for position 1 of stack, stack only has 0 elements on it.>, radius=<optimized out>, dont_load=<error reading variable: Unhandled dwarf expression opcode 0xff>) at /root/acore/src/server/game/Grids/Cells/CellImpl.h:203
#21 0x0000000001157644 in CreatureTextMgr::SendChatPacket<CreatureTextBuilder> (this=<error reading variable: Unhandled dwarf expression opcode 0xff>, source=<optimized out>, builder=..., msgType=<optimized out>, target=<optimized out>, range=<optimized out>, teamId=TEAM_NEUTRAL, gmOnly=<error reading variable: Asked for position 1 of stack, stack only has 0 elements on it.>) at /root/acore/src/server/game/Texts/CreatureTextMgr.h:254
#22 0x0000000001154f32 in CreatureTextMgr::SendChat (this=<optimized out>, source=<optimized out>, textGroup=<error reading variable: Unhandled dwarf expression opcode 0xff>, target=<optimized out>, msgType=<error reading variable: Asked for position 1 of stack, stack only has 0 elements on it.>, language=<optimized out>, range=<optimized out>, sound=<optimized out>, teamId=<optimized out>, gmOnly=<error reading variable: Unhandled dwarf expression opcode 0xff>, srcPlr=<error reading variable: Unhandled dwarf expression opcode 0xff>) at /root/acore/src/server/game/Texts/CreatureTextMgr.cpp:303
#23 0x0000000000000004 in ?? ()
#24 0x0000000000000000 in ?? ()

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/65f031c34017b203aa1db3bced000fb10b52ff90+ 2023-02-12 23:43:33 -0300 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n 15 Mar 2022 (library: OpenSSL 1.1.1n 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.64-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

List enable modules:

mod-anticheat
mod-bg-reward
mod-cfbg
mod-eluna
mod-multi-client-check
mod-npc-beastmaster
mod-pvp-titles
mod-save-inventory
mod-server-auto-shutdown

### Operating system

debian 11 x64

**Comment by Kitzunu** [comment]
1. Dont upload files, use PASTEBIN if you cannot use GIST.
2. Dont just dump data into an issue. If for some reason you cannot use PasteBin or Gist, at least wrap it in a codeblock with hidden details.

Like this:
```
<details><summary>Details</summary>

\```
DUMP DATA HERE

\```
</details>
```
