### ISSUE TITLE
Reck, Shield Wall, Retaliation go on cooldown when logging off

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14997]
https://github.com/chromiecraft/chromiecraft/issues/5025
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

all 3 of these abilites dont share a cool down and this is correct behaviour
however whenever i leave a dungeon, or logout all three of these abilities will go on cool down
Example: I pop recklessness for last boss in dungeon i have not used shield wall or retaliation so both are off cooldown
When I teleport out of dungeon all 3 abilites will now be on cooldown when it should only be recklessness

https://user-images.githubusercontent.com/11332559/218500694-ff9a1236-8b9e-415b-9d7e-006d79fe907b.mp4

### Expected Blizzlike Behaviour

These abilites sharing a cooldown got removed in patch 3.0.2 and It works just fine normally they just all go on cooldown whenever i leave a dungeon or logout

### Source

https://vanilla-wow-archive.fandom.com/wiki/Shield_Wall#:~:text=Notes-,As%20of%20patch%203.0.,these%20talents%20usable%20in%20PvP.

### Steps to reproduce the problem

.learn 871
.learn 20230
.learn 1719

use any and log out
attempt to use any of the other two

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=871
https://wowgaming.altervista.org/aowow/?spell=20230
https://wowgaming.altervista.org/aowow/?spell=1719

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
I can't confirm it.
