### ISSUE TITLE
Dissension Amongst the Ranks... kills only credited for the person who deals the killing blow

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#14996]
https://github.com/chromiecraft/chromiecraft/issues/5026
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

When the crazed colossus are killed in a group, only the person who deals the killing blow will get credit for the quest (both people in our group had tabards equipped).

### Expected Blizzlike Behaviour

The kills should count for everyone, however the player who deals the killing blow must be wearing the quest tabard according to the wowhead comments.

### Source

quest is "Suggested players: 3" and there are no comments about killing more than 5.
its even suggested its bugged so you get too many kills credited
![image](https://user-images.githubusercontent.com/11332559/218496488-455acbcf-f23c-4875-9273-de7f4e06d5d9.png)

https://www.wowhead.com/tbc/quest=10769/dissension-amongst-the-ranks#comments

### Steps to reproduce the problem

.quest add 10776
.go c id 19823
kill them in a group

### Extra Notes

![image](https://user-images.githubusercontent.com/114075548/218331483-115a9ccb-4572-4419-a458-a5e4928806a6.png)
location of crazed colossus

This was noted on the alliance version of the quest, with 2 alliance players.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Spectralus** [comment]
Confirmed bugged killing count with also 1 alliance player and 2 hordes in group. Person who does the killing blow gets the kill. Tabards were equipped.
