### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by ahuraa** [AzerothCore/azerothcore-wotlk#15]
CMake Error at modules/dep/mysqllite/CMakeLists.txt:257 (add_version_info):
  Unknown CMake command "add_version_info".

**Comment by Yehonal** [comment]
which version of cmake are you using? are you on windows or linux?

please do not open issues that are not descriptive at all. Othewise will be closed

**Comment by BungiSk** [comment]
Not working compile in cmake in windows. errors

**Comment by ahuraa** [comment]
windows error 

cmake 3.3.2

i compile sunwellcore bot this can't

**Comment by Bodeguero** [comment]
I fixed erro in CMake - no problem!

**Comment by Yehonal** [comment]
@Bodeguero could you share with us how did you fix it?

Personally , i don't have any problem with windows.

I'm compiling with VS community 14 2015 both 32 and 64 bit

**Comment by Bodeguero** [comment]
Yes I am doing some updates on your project soon send via Pull Request!

Look:
AuthServer:
![logo](http://image.prntscr.com/image/698bfceeaf3848d692e20016494f7c3c.jpg)

WorldServer:
![logo](http://image.prntscr.com/image/d483e678e3f24815ac84bcae4a6a9cce.jpg)

I compile on Linux and Windows - the mistakes that I've had I fixed missing now send to my [GitHub](https://github.com/Bodeguero/AzerothCore_3.3.5)! 

I hope the community like! :facepunch:

**Comment by Yehonal** [comment]
Nice! thank you :)

**Comment by Bodeguero** [comment]
@Yehonal  no problem - i tested this project and this much more advanced than the very TrinityCore - for this reason I will be helping in this project! :facepunch:

**Comment by Yehonal** [comment]
related to: https://github.com/AzerothCore/azerothcore-wotlk/issues/16
