### ISSUE TITLE
Suggestion: creature_summon_groups should take waypoints

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#15040]
### Describe your feature request or suggestion in detail

Too many summons have waypoints scripted in them. This is not something SAI can handle as one entry can have several different waypoints.

### Describe a possible solution to your feature or suggestion in detail

Should have a `waypoint` field linking back to waypoints.sql, and a `waypoint_delay` field to deal with delayed movement.

**Comment by Gultask** [comment]
Another thing. Some spawned groups are formations, with follow mechanics. I'm not sure how this would be accomplished without adding many columns

**Comment by Nyeriah** [comment]
Only concern I have about this is DB consistency/normalization, as I think those cases are exceptions when we come to think of it and the vast majority don't have path/formations

**Comment by Gultask** [comment]
From what I can remember Slave Pens, Escape From Durnholde and the Manaforge quests in Netherstorm have waypoints and formations.
Tbh I feel like making them actual guids in the `creature` table spawns that only spawn on command might be a better option, as then we'd be able to add all of these without any issues.

**Comment by Gultask** [comment]
Alternatively, pre-spawns fixes every problem here, also with summons with formations and/or specific scripting.
Summon_groups can't tackle everything without massive reworks.
