### ISSUE TITLE
[World] Server crash 0213

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#15045]
### Current Behaviour

https://pastebin.com/b5B2RY2t

 When fight in outland blacktemplate with illidari_council, the server crash. But not alway happen, only crash one time.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/65f031c34017b203aa1db3bced000fb10b52ff90+ 2023-02-12 23:43:33 -0300 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n 15 Mar 2022 (library: OpenSSL 1.1.1n 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.64-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

List enable modules:

mod-anticheat
mod-bg-reward
mod-cfbg
mod-eluna
mod-multi-client-check
mod-npc-beastmaster
mod-pvp-titles
mod-save-inventory
mod-server-auto-shutdown

### Operating system

debian 11 x64

**Comment by Tony931023** [comment]
update your core to the latest version:  https://github.com/azerothcore/azerothcore-wotlk/commit/bd6034e1a9f5ba18dff1261edaea4494727412a2  and try again to see if it doesn't crash

**Comment by kissingers** [comment]
OK, I try update and test it, thanks.

**Comment by heyitsbench** [comment]
> update your core to the latest version: [bd6034e](https://github.com/azerothcore/azerothcore-wotlk/commit/bd6034e1a9f5ba18dff1261edaea4494727412a2) and try again to see if it doesn't crash

I highly doubt the three commits between the report commit and latest fix this crash, based on the log.

**Comment by Tony931023** [comment]
Yes, but just in case, it's a miracle, but when I updated the core to the latest version, I couldn't replicate this crash anymore. https://github.com/azerothcore/azerothcore-wotlk/issues/14984

**Comment by heyitsbench** [comment]
Helps that your linked crash log mentions a file that *did* see changes in the recent commits. The log in this issue does not mention any recently changed files.

**Comment by kissingers** [comment]
> Helps that your linked crash log mentions a file that _did_ see changes in the recent commits. The log in this issue does not mention any recently changed files.

Yes, the same as yesterday, I just past the log to pastebin. now I patch to last master update, test 3 times myself,  no crash. I will test tonight with our friends.

**Comment by kissingers** [comment]
As no crash since update to laster version, so close this first.
