### ISSUE TITLE
[Ulduar]Can not enter Ulduar after server restarted

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#15044]
### Current Behaviour

After apply PR#14977,when server restart,Ulduar instance is broken and alway's in combat
At first time ,client crashed , after relogin and go instance,it shows instance is in combat

server log(at first time):
2023-02-14 01:12:49 Map 603 could not be created for player GUID Full: 0x0000000000000001 Type: Player Low: 1, porting player to homebind

### Expected Blizzlike Behaviour

1.RT

### Source

Maybe instance_ulduar.cpp

### Steps to reproduce the problem

1.Go to Ulduar and combat with mimiron
2.Leave combat(die or GM on)
3.Restart server
4.Go to Ulduar with GM off, you can receive  Map 603 could not be created for player GUID Full: 0x0000000000000001 Type: Player Low: 1, porting player to homebind @console and player stuck with no one
5.Alt+F4 to exit client and relogin
6.Enter Ulduar again,you can receive zone in combat notice
7.Revert to PR#14987 and problem solved

### AC rev. hash/commit

[bd6034e](https://github.com/azerothcore/azerothcore-wotlk/commit/bd6034e1a9f5ba18dff1261edaea4494727412a2)

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
That's not how the source field is supposed to be filled out.

**Comment by Nyeriah** [comment]
Reset your `instance` table as you might have compromised data, I can't reproduce this issue. In either case, https://github.com/azerothcore/azerothcore-wotlk/pull/15041 should help
