### ISSUE TITLE
impossible to start the fight with Sapphiron 

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15043]
### Current Behaviour

Impossible to initiate combat with Sapphiron in 10 and 25 player modes, when you hit it it gives evade, if you use .damage with an admin account life is restored again

### Expected Blizzlike Behaviour

must let start the fight correctly

### Steps to reproduce the problem

1. Go Naxx
2. Go Sapphiron 
3. Start the fight

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/bd6034e1a9f5ba18dff1261edaea4494727412a2

### Operating system

Ubuntu 20.04

**Comment by bgcfb** [comment]
You shuld kill 4 fianl BOSSes under before

**Comment by Tony931023** [comment]
In Wotlk classic we go directly to this boss to obtain the key to the Eye of Eternity

**Comment by bgcfb** [comment]
> assic we go directly to this boss to obtain the

In old Wotlk 3.3.5 you should kill all BOSSes
In new Wotlk 3.4.0 P2 you can kill sapphiron directly

**Comment by bgcfb** [comment]
If you want change it just comment here in instance_naxxramas.cpp line 655

        bool CheckRequiredBosses(uint32 bossId, Player const* /* player */) const override
        {
            switch (bossId)
            {
                case BOSS_SAPPHIRON:
                    if (!AreAllWingsCleared())
                    {
                        //return false;
                    }
                    break;
                default:
                    break;
            }
            return true;
        }

**Comment by Tony931023** [comment]
ty @bgcfb  ♥

**Comment by Tony931023** [comment]
@bgcfb 

https://wowpedia.fandom.com/wiki/Patch_3.3.0

    Players no longer need to kill the final bosses in all four wings of this dungeon in order to teleport to [Sapphiron](https://wowpedia.fandom.com/wiki/Sapphiron_(tactics)). Teleportation orbs have been added to allow players access back and forth from [Sapphiron's lair](https://wowpedia.fandom.com/wiki/Sapphiron%27s_Lair).

**Comment by heyitsbench** [comment]
Says nothing about being able to fight the boss, just that you can go to his lair prematurely.

**Comment by bgcfb** [comment]
@Tony931023 Maybe you are right

**Comment by heyitsbench** [comment]
For the record, please provide a source for any and all issues.

**Comment by Si1ker** [comment]
Current state: you can have to kill 4 wings before Sapphi which was removed during 3.3 - done here #12696
Blizzlike: As AC runs 3.3.5a , there should be no requirement to teleport into Sapphiron's Lair.

[Patch 3.3.0](https://wowpedia.fandom.com/wiki/Patch_3.3.0) (2009-12-08): Players no longer need to kill the final bosses in all four wings of this dungeon in order to teleport to [Sapphiron](https://wowpedia.fandom.com/wiki/Sapphiron_(tactics)). Teleportation orbs have been added to allow players access back and forth from [Sapphiron's lair](https://wowpedia.fandom.com/wiki/Sapphiron%27s_Lair).
[source](https://wowpedia.fandom.com/wiki/Naxxramas)

**Comment by smellbee** [comment]
@Si1ker     I don't think this need a fix in core, maybe this should be done in progression-system

**Comment by heyitsbench** [comment]
> I don't think this need a fix in core, maybe this should be done in progression-system

Why do you feel that way? It's already been made clear that this issue needs correction in the core to emulate 3.3.5a behavior, why should it be relegated to a progression module?
