### ISSUE TITLE
[quest]Gorgron the dragon eater

### ISSUE THREAD

**Issue by Asherdoom** [azerothcore/azerothcore-wotlk#1505]
Gorgron the dragoneater totem placement

##### SMALL DESCRIPTION:
You can place all 3 totems on top of each other after killing Gorgron the dragoneater

##### EXPECTED BLIZZLIKE BEHAVIOUR:
you should place them in a triangular way around his corpse.

##### CURRENT BEHAVIOUR:
you can place each other nearby  (stacking on same pixel)

##### STEPS TO REPRODUCE THE PROBLEM:

1. go blade's edge mountain
2.  accept quest https://www.wowhead.com/quest=10802/gorgrom-the-dragon-eater
3. kill the boss
4. Place totems

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
commit [987095e]

##### OPERATING SYSTEM:
linux

**Comment by poszer** [comment]
Just taking a look on the old videos of this quest, and i think these req items are not required to be spawned in triangular way , also there isn't any information how these totems are spawned, so i think this can stay like this. Quest is acceptable, can be completed, everything works.
Tested several times, for me it's perfect. 
![try2](https://user-images.githubusercontent.com/41213210/54649342-19d81c80-4aaa-11e9-8969-9cf8ede4d089.png)
![try1](https://user-images.githubusercontent.com/41213210/54649343-1a70b300-4aaa-11e9-9738-b9ab4eeaad0d.png)
Closing this. Anyway thanks for report @Asherdoom
