### ISSUE TITLE
worldserver.exe Error logging

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#1506]
“worldserver.exe” A packet error occurred during operation

SMALL DESCRIPTION:
When "worldserver.exe" encountered DDOS attack traffic, there would be an error packet
![xs kz2p ua vvxmwr e ba](https://user-images.githubusercontent.com/16046064/53119175-c0caa680-3546-11e9-87e2-19d5580d557d.png)

EXPECTED BLIZZLIKE BEHAVIOUR:

Program error problem

CURRENT BEHAVIOUR:

Program error problem

STEPS TO REPRODUCE THE PROBLEM:

EXTRA NOTES:
BRANCH(ES):
staging

AC HASH/COMMIT:
commit [[987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)]

OPERATING SYSTEM:
ubuntu
MODULES:
OTHER CUSTOMIZATIONS:

**Comment by BarbzYHOOL** [comment]
We have several Pull Requests about DOS and DDOS i think, so check them out

@Viste @FrancescoBorzi

**Comment by BarbzYHOOL** [comment]
Example @boom8866 https://github.com/azerothcore/azerothcore-wotlk/pull/1207

**Comment by boom8866** [comment]
@BarbzYHOOL  https://github.com/TrinityCore/TrinityCore/commit/ce947814c6fa2c32c0908f1e7088ce971f74d365

This update is recommended
File encountered packet too small problem crash occurred

**Comment by FrancescoBorzi** [comment]
@boom8866 can you open a PR with that?

**Comment by pklloveyou** [comment]
```c++
		case CMSG_PING:
		{
			try
			{
				return HandlePing(*new_pct);
			}
			catch (ByteBufferPositionException const&)
			{
			}
			return -1;
		}
		case CMSG_AUTH_SESSION:
		{
			if (m_Session)
			{
				sLog->outError("WorldSocket::ProcessIncoming: Player send CMSG_AUTH_SESSION again");
				return -1;
			}
			try
			{
				return HandleAuthSession(*new_pct);
			}
			catch (ByteBufferPositionException const&)
			{
			}
			return -1;
		}
```
I don't know if it's working。
