### ISSUE TITLE
[Quest] Deathblow to the Legion

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15085]
https://github.com/chromiecraft/chromiecraft/issues/4951
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Talking to Adyen opens a popup window
Kaylaan does not become unattackable when he gets low hp (this really breaks the quest)

### Expected Blizzlike Behaviour

Adven has a gossip window
Kaylaan becomes unattackable

### Source

https://www.youtube.com/watch?v=Uub5rh4zE3M

### Steps to reproduce the problem
.go zonexy 36.46 18.4 3900
.quest add 10409
Use the quest item to make the portal
Step through the portal
Talk to Adyen

### Extra Notes

https://wowgaming.altervista.org/aowow/?quest=10409

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
IDs near 60k are from MoP
This NPC is entirely custom/hacked. From the Sunwell days, I assume.

![image](https://user-images.githubusercontent.com/100873791/219823939-51f0b5ac-7068-46f7-a539-ff5e93578c34.png)

**Comment by Gultask** [comment]
Excuse me, it was previously a port from OregonCore, it seems: https://github.com/OregonCore/OregonCore/blob/0f4d552fce1242f49f625d9ac54f7f3aa0c349a9/src/scripts/Outland/netherstorm.cpp#L2468
