### ISSUE TITLE
Strange Problem With Gm Accounts

### ISSUE THREAD

**Issue by Abyssking** [azerothcore/azerothcore-wotlk#151]
Hey All, I found a problem and i wounder how but it is...

If you enter to a instance with gm account (.gm on) the server will crash. (tested on IceCrown)
If you invite a person with gm account (.gm on) your Wow.exe will crash.

Please checkout this report and share your experience with us.
Thank you all.
##

**Comment by mars8022** [comment]
vs 2015 BUILD used gm command sitll crash.

Exception code: C0000005 ACCESS_VIOLATION
Fault address:  739A2E47 01:00031E47 C:\Windows\system32\ucrtbase.DLL

Registers:
EAX:7FFFFFFF
EBX:00000009
ECX:00000009
EDX:00000007
ESI:00000009
EDI:00000010
CS:EIP:0023:739A2E47
SS:ESP:002B:3842F170  EBP:3842F178
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010287

Call stack:
Address   Frame     Function      SourceFile
739A2E47  00000000  strnlen+B7
73A1AFF5  00000000  _cgetws_s+2E75
739FBAD8  00000000  __stdio_common_vsscanf+2408
739FF5AF  00000000  __stdio_common_vsprintf+1F
00494186  00000000  0001:002F3186 G:\SunWell\worldserver.exe
00495FE4  00000000  0001:002F4FE4 G:\SunWell\worldserver.exe
0030415A  00000000  0001:0016315A G:\SunWell\worldserver.exe
00304BEB  00000000  0001:00163BEB G:\SunWell\worldserver.exe
0046EACA  00000000  0001:002CDACA G:\SunWell\worldserver.exe
001F87C4  00000000  0001:000577C4 G:\SunWell\worldserver.exe
001C12A8  00000000  0001:000202A8 G:\SunWell\worldserver.exe
001C09C5  00000000  0001:0001F9C5 G:\SunWell\worldserver.exe
001AB8F7  00000000  0001:0000A8F7 G:\SunWell\worldserver.exe
0049B645  00000000  0001:002FA645 G:\SunWell\worldserver.exe
0049B546  00000000  0001:002FA546 G:\SunWell\worldserver.exe
739EF794  00000000  _crt_at_quick_exit+104
76D8337A  00000000  BaseThreadInitThunk+12
772B92E2  00000000  RtlInitializeExceptionChain+63
772B92B5  00000000  RtlInitializeExceptionChain+36
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
739A2E47  00000000  strnlen+B7

73A1AFF5  00000000  _cgetws_s+2E75

739FBAD8  00000000  __stdio_common_vsscanf+2408

739FF5AF  00000000  __stdio_common_vsprintf+1F

00494186  00000000  0001:002F3186 G:\SunWell\worldserver.exe

00495FE4  00000000  0001:002F4FE4 G:\SunWell\worldserver.exe

0030415A  00000000  0001:0016315A G:\SunWell\worldserver.exe

00304BEB  00000000  0001:00163BEB G:\SunWell\worldserver.exe

0046EACA  00000000  0001:002CDACA G:\SunWell\worldserver.exe

001F87C4  00000000  0001:000577C4 G:\SunWell\worldserver.exe

001C12A8  00000000  0001:000202A8 G:\SunWell\worldserver.exe

001C09C5  00000000  0001:0001F9C5 G:\SunWell\worldserver.exe

001AB8F7  00000000  0001:0000A8F7 G:\SunWell\worldserver.exe

0049B645  00000000  0001:002FA645 G:\SunWell\worldserver.exe

0049B546  00000000  0001:002FA546 G:\SunWell\worldserver.exe

739EF794  00000000  _crt_at_quick_exit+104

76D8337A  00000000  BaseThreadInitThunk+12

772B92E2  00000000  RtlInitializeExceptionChain+63

772B92B5  00000000  RtlInitializeExceptionChain+36

**Comment by Abyssking** [comment]
@mars8022,
If you compiling with vs2015 you need to install or use mysql-5.7.14-win32 lib and include else you must use mysql-5.7.14-winx64. (may fix C:\Windows\system32\ucrtbase.DLL)
if your operating system is x64 please compile x64 version. (may fix C:\Windows\system32\ucrtbase.DLL)
check out, you already compile project as debug (not release).
use your core on compiled computer not anothor.( may fix C:\Windows\system32\ucrtbase.DLL)

**Comment by mars8022** [comment]
needs to use 5.7.14 libmysql.dll?

**Comment by Abyssking** [comment]
@mars8022 i Used it's completely work, except server crashes on same times...

**Comment by Yehonal** [comment]
Please do not use mysql 5.7 , we require 5.6 

https://github.com/azerothcore/azerothcore-wotlk/wiki/Requirements#windows

However @mars8022 your call stack doesn't have any info about code, did you compile in Debug mode?

**Comment by Viste** [comment]
not confrim all is ok with gm accounts
