### ISSUE TITLE
DBErrors.log file

### ISSUE THREAD

**Issue by sxwenjie** [azerothcore/azerothcore-wotlk#15118]
### Current Behaviour

Table `achievement_reward` (Entry: 4530) has mail Subject but does not have Sender data set.
Table `achievement_reward` (Entry: 4530) has mail text (Body) set but does not have Sender data set.
Table `achievement_reward` (Entry: 4583) has mail Subject but does not have Sender data set.
Table `achievement_reward` (Entry: 4583) has mail text (Body) set but does not have Sender data set.
Table `achievement_reward` (Entry: 4584) has mail Subject but does not have Sender data set.
Table `achievement_reward` (Entry: 4584) has mail text (Body) set but does not have Sender data set.
Table `achievement_reward` (Entry: 4597) has mail Subject but does not have Sender data set.
Table `achievement_reward` (Entry: 4597) has mail text (Body) set but does not have Sender data set.

### Expected Blizzlike Behaviour

After starting the wow server, the DBErrors.log file is generated. I don't know if it will affect the game

### Steps to reproduce the problem

After starting the wow server, the DBErrors.log file is generated. I don't know if it will affect the game

### AC rev. hash/commit

NO

### Operating system

ubuntu 20.04

**Comment by heyitsbench** [comment]
`NO` is not a valid revision hash. CI builds don't have this issue. Sounds like it's something specific to you.
