### ISSUE TITLE
Odur 1 BOSS AND Illidan P3  BUG REPORT

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15116]
### Current Behaviour

1: The co-driver of Odur 1 BOSS siege tank can't get on the car, the role is stuck, and there is no skill. Please repair it as soon as possible

2: Illidan P3 will be released from the war when it is in the cage. Please repair it as soon as possible

### Expected Blizzlike Behaviour

1: The co-driver of Odur 1 BOSS siege tank can't get on the car, the role is stuck, and there is no skill. Please repair it as soon as possible

2: Illidan P3 will be released from the war when it is in the cage. Please repair it as soon as possible

### Steps to reproduce the problem

1: The co-driver of Odur 1 BOSS siege tank can't get on the car, the role is stuck, and there is no skill. Please repair it as soon as possible

2: Illidan P3 will be released from the war when it is in the cage. Please repair it as soon as possible

### AC rev. hash/commit

1: The co-driver of Odur 1 BOSS siege tank can't get on the car, the role is stuck, and there is no skill. Please repair it as soon as possible

2: Illidan P3 will be released from the war when it is in the cage. Please repair it as soon as possible

### Operating system

WIN10

**Comment by heyitsbench** [comment]
A) Fill out the issue correctly.
B) This is two issues. Make two different issues.
C) Pretty sure there are existing reports for both of these.
