### ISSUE TITLE
Kologarn doesn't release the character from his right fist after death

### ISSUE THREAD

**Issue by aebline** [azerothcore/azerothcore-wotlk#15110]
### Current Behaviour

When facing Kologarn solo, he grabs you with one of his fists (the right one) and never releases you, even though you die from Stone Grip. The only way to unstuck your charater is to log out and then back in, so that you get teleported to the nearest graveyard.

Location: Ulduar
Affected creature: Kologarn (npc=32930)

### Expected Blizzlike Behaviour

The moment you die from Stone Grip you should be immediatly teleported to the graveyard without having to log out.

### Steps to reproduce the problem

1. Engage Kologarn in Ulduar
2. Wait until he grabs you with his right arm and kills you

### AC rev. hash/commit

AzerothCore rev. 25c77a59c955 2023-02-14 05:17:08 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1q  5 Jul 2022 (library: OpenSSL 1.1.1q  5 Jul 2022)
Using Boost version: 1.79.0
Using MySQL version: 80030
Using CMake version: 3.24.0

### Operating system

Windows 10 x64

### Custom changes or Modules

- Mod Autobalance
- Mod Transmog

**Comment by Kitzunu** [comment]
so close it
