### ISSUE TITLE
[QUEST] wanted: boss grog'ak

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1512]
DESCRIPTION:

ally players can get this [quest](https://wowwiki.fandom.com/wiki/Quest:WANTED:_Boss_Grog%27ak) id 9820

EXPECTED BLIZZLIKE BEHAVIOUR:

the quest can only be obtained from horde players

CURRENT BEHAVIOUR:

read the description

STEPS TO REPRODUCE THE PROBLEM:

- create a alliance pg;
- .go 279.7 7866.6 24.1 530
- you can take the quest

![quest](https://user-images.githubusercontent.com/22867608/53204617-568c3180-362c-11e9-8b36-e7c6bad83bc5.png)

BRANCH(ES):
staging

AC HASH/COMMIT:
commit: [aade455](https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by VengefulWoW** [comment]
I will make a fix
