### ISSUE TITLE
[Quest] Against the Legion cannot be started by alliance characters

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15129]
https://github.com/chromiecraft/chromiecraft/issues/5039
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

After completing the quest "Altruis" as alliance (either https://wowgaming.altervista.org/aowow/?quest=10640 or https://wowgaming.altervista.org/aowow/?quest=10689, depending on whether you are doing Aldor or Scryers rep) there are 2 quests available:
- "Against the Illidari" (https://wowgaming.altervista.org/aowow/?quest=10668)
- "Against All Odds" (https://wowgaming.altervista.org/aowow/?quest=10669)

However, the quest Against the Legion doesn't display and can't be started. The other two quests are available to start as expected.

### Expected Blizzlike Behaviour
It should be possible to start all 3 quests.
- "Against the Legion" (https://wowgaming.altervista.org/aowow/?quest=10641)
- "Against the Illidari" (https://wowgaming.altervista.org/aowow/?quest=10668)
- "Against All Odds" (https://wowgaming.altervista.org/aowow/?quest=10669)

### Source

Quest chain is detailed in many comments on wowhead, for example https://www.wowhead.com/wotlk/quest=10640/altruis#comments:id=156127

### Steps to reproduce the problem

Be alliance
.go c 65809
.quest add 10689
Turn in quest
Observe takeable quests

### Extra Notes

The aowow page https://wowgaming.altervista.org/aowow/?quest=10641 seems to incorrectly show the quest as requiring "Forge Camp: Annihilated" to be completed. I tried completing that to see if Against the Legion would then be startable, but it still wasn't.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3f2364befeda2fe09fb495e2cb81f2974e6f59e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Si1ker** [comment]
It's not a alliance-only issue.
Orc lvl 69 - Only got Against all the Odds and Against the Illidari / Missing Against the Legion.

(Live ChromieCraft, ofc)

**Comment by ZhengPeiRu21** [comment]
> It's not a alliance-only issue. Orc lvl 69 - Only got Against all the Odds and Against the Illidari / Missing Against the Legion.
> 
> (Live ChromieCraft, ofc)

Thanks for the update - that's very useful to know. I've done a quick check and it is not an obvious fix, but I think we should be able to work it out. I think the issue is related to quest grouping.
