### ISSUE TITLE
[Server] Crash 0219

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#15122]
### Current Behaviour

https://pastebin.com/sQuPZLGA

Crash after this update and till now.
https://github.com/azerothcore/azerothcore-wotlk/pull/15059

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 5b602508808a 2023-02-19 05:59:10 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.85-1-pve
Worldserver listening connections on port 54346
Realmlist (Realm Id: 2) configured in port 54346
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-save-inventory
- mod-server-auto-shutdown

### Operating system

debian 11 x64

**Comment by boom8866** [comment]
When the selected character is reading and entering the game, the progress has been 100%, but cannot enter the game normally! Then log in with the same account and this kind of crash will occur
