### ISSUE TITLE
Can't get into the game

### ISSUE THREAD

**Issue by xBarselonx** [azerothcore/azerothcore-wotlk#15134]
### Current Behaviour

After the latest update does not enter the game. When selecting a character loading bar comes to the end and then may continue indefinitely. Before the update everything was normal. Errors and warnings when compiling and further launching the server was not.

### Expected Blizzlike Behaviour

Going into the game as your character with no problem.

### Steps to reproduce the problem

1. get the latest updates
2. compile the server
3. run authserver and worldserver
4. run the game client

### AC rev. hash/commit

How, if I can not enter the game?

### Operating system

Windows 10 x64

### Custom changes or Modules

https://github.com/azerothcore/mod-ah-bot
https://github.com/azerothcore/mod-npc-services

**Comment by Nyeriah** [comment]
Please update your core, it is outdated as this has already been fixed.
