### ISSUE TITLE
[BUG] gm fly at draenei isles

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1513]
**DESCRIPTION:**

there are flight problems of the GM pg near water in the draenei islands

**EXPECTED BLIZZLIKE BEHAVIOUR:**

fly normally

**CURRENT BEHAVIOUR:**

when you fly just above the water there seems to be some invisible wall that doesn't rise upwards

**STEPS TO REPRODUCE THE PROBLEM:**

.go -4239.3 -11970 -1.4 530
try to fly upwards

**BRANCH(ES):**
staging

**AC HASH/COMMIT:**
commit: [aade455](https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1)

**OPERATING SYSTEM:**
linux

**MODULES:
OTHER CUSTOMIZATIONS:**

**Comment by talamortis** [comment]
sorry but this is not an issue, you are not supposed to be able to fly on this isle.

**Comment by comix1988** [comment]
With a gm account
The title is "gm fly"

**Comment by BarbzYHOOL** [comment]
I don't understand the issue either @comix1988  :(

**Comment by comix1988** [comment]
it's a minor bug but it's still a bug.
if a gm flies in those islands near the water this bug occurs.

**Comment by GitVerge** [comment]
if it doesn't affect the gameplay of normal players what's the reason to change it? can we prove that this wasn't this way on retail? :confused:

**Comment by BarbzYHOOL** [comment]
well it can waste a GM's/dev's time by confusing him

**Comment by RaistlinAstragon** [comment]
I replicated this issue also with a new blood elf character with GM powers. With fly activated, also in Eversong Woods near Silvermoon, if you press SPACE+W for flying the movement texture of the character is randomly changing from "swim straight" to "back swimming" while flying. In previous versions of AzerothCore, I confirm this minor bug was not present.

**Comment by talamortis** [comment]
@RaistlinAstragon this happens on all servers i have tested and even azerothcore v1.0 this has always been the case for these. I personally think that this issue needs closing as its is not intended game play to be able to fly in these area's! its just a waste of time trying to fix this when we are focusing on blizzlike content.

**Comment by poszer** [comment]
I think we should close this. This is not issue, since it doesn't break anything for players. Also
