### ISSUE TITLE
Death Bringer Saurfang ICC: Muradin Bronzebeard dialogue is saying horde.

### ISSUE THREAD

**Issue by speedrunz** [azerothcore/azerothcore-wotlk#15132]
### Current Behaviour

Muradin Bronzebeard in ICC has a part dialogue in horde version.

### Expected Blizzlike Behaviour

It should only say the Dialogue from the alliance.

### Steps to reproduce the problem

1. Go to ICC as alliance.
2. Go to Deathbringer Saurfang encounter.

### AC rev. hash/commit

AzerothCore rev. 07ac386e61bd+ 2023-01-15

### Operating system

Ubuntu 20.04

### Custom changes or Modules

None

**Comment by pangolp** [comment]
@azerothcore/developers Does anyone know why this could be happening?
The funny thing is, if I perform this query in the database...
```sql
UPDATE `creature` SET `id1`=37200 WHERE `guid`=200982;
```
The dialogues are executed correctly.
Although the most likely thing is that they will be ruined in the other faction.

**Comment by pangolp** [comment]
There is already another report on this topic.
I think this issue is repeated.
https://github.com/azerothcore/azerothcore-wotlk/issues/8921

**Comment by pangolp** [comment]
We are going to close this issue, because it is already reported.
Thanks anyway for the report.
We will continue discussing it in the other.
