### ISSUE TITLE
conf option to read ONLY from the `namesreserved_dbc` and `namesprofanity_dbc` tables and skip the actual dbc files

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#15142]
Is there a conf option to read ONLY from the `namesreserved_dbc` and `namesprofanity_dbc` and skip the actual dbc files?

_Originally posted by @55Honey in https://github.com/azerothcore/azerothcore-wotlk/issues/14956#issuecomment-1435951365_

Recently the reserved names and profanity system was changed. There should be a way to (de-)activate the dbc table and the dbc files individually via conf option.

**Comment by acidmanifesto** [comment]
Should be easily done. Whats the commit with those changes?

**Comment by acidmanifesto** [comment]
Should be easily done. Whats the commit with those changes?

**Comment by Kitzunu** [comment]
There is a conf option to disable them (which includes _dbc). You still have the `reserved` table in auth that you can use
