### ISSUE TITLE
Quest: Heroes of Old (2702)

### ISSUE THREAD

**Issue by unrealking04** [azerothcore/azerothcore-wotlk#1514]
Quest: Heroes of Old (2702) quest cannot be completed.

##### SMALL DESCRIPTION:
<the quest start at the fallen hero of the horde and will complete at Thund Splithoof for the nex quest of the chain,but the npc does not spawn>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
<https://www.youtube.com/watch?v=p52Jpb1Xu28 in this video you can watch how the quest should works
>

##### CURRENT BEHAVIOUR:
<the NPC does not spawn>

##### STEPS TO REPRODUCE THE PROBLEM:
<1.complete all the previus 3 quest to get "Hero of old (part 4 of 5)"

![screenshot 31](https://user-images.githubusercontent.com/47576138/53252630-a5cf7200-36bf-11e9-851d-b766a356ec38.png)

  2. speek with NPC "Fallen hero of the horde" (7572)
![screenshot 33](https://user-images.githubusercontent.com/47576138/53252681-c1d31380-36bf-11e9-9098-e33b5781f224.png)

 3.the npc Thund Splithoof do not spawn and can't complete the quest and go forward in the chain.

##### BRANCH(ES):

staging

##### AC HASH/COMMIT:
wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

##### OPERATING SYSTEM:
linux

**Comment by comix1988** [comment]
I confirm. When we talk to the NPC "fallen hero of the horde" we can not summon Thund Splithoof.

steps:
.go creature 35237
.quest add 2681
.quest complete 2681  and rewared it
take the quest "Hero of old" ,speak with the fallen hero of the horde and click " Hero, i have a urgent business with Thund Splithoof"

**Comment by Knindzagxg** [comment]
Apply fix.
.reload  smart_scripts
.npc  add 7572 just to test and delete after. Spwned NPC will work after next server restart

Video bellow as well.

`UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 7572;

DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 7572);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(7572, 0, 0, 1, 62, 0, 100, 0, 881, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, ''),
(7572, 0, 1, 2, 61, 0, 100, 0, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, ''),
(7572, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, ''),
(7572, 0, 3, 4, 62, 0, 100, 0, 840, 2, 0, 0, 11, 11024, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ''),
(7572, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, '');`

https://www.youtube.com/watch?v=5NCzJSiE8Xs&feature=youtu.be

**Comment by poszer** [comment]
> ```sql
> UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 7572;
> 
> DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 7572);
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
> (7572, 0, 0, 1, 62, 0, 100, 0, 881, 0, 0, 0, 26, 2784, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, ''),
> (7572, 0, 1, 2, 61, 0, 100, 0, 0, 0, 0, 0, 26, 2801, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, ''),
> (7572, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, ''),
> (7572, 0, 3, 4, 62, 0, 100, 0, 840, 2, 0, 0, 11, 11024, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ''),
> (7572, 0, 4, 0, 61, 0, 100, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, '');
> ```

Nice fix! Tested, working. The Npc is spawned, and quest can be completed. WIll create PR for this, and tag you as Author @Knindzagxg
