### ISSUE TITLE
worldserver crash and no log

### ISSUE THREAD

**Issue by ryoting** [azerothcore/azerothcore-wotlk#15148]
### Current Behaviour

When the player uses some plug-ins to log in to the game on the client side, he will Stuck on the progress bar of the character logging into the game. At this time, the worldserver.exe on the server side will automatically close, and no logs.

### Expected Blizzlike Behaviour

none

### Source

openssl 1.1.1t
mysql8.0.32
boost1.81

### Steps to reproduce the problem

1.

### AC rev. hash/commit

9aed091 and latest 

### Operating system

windows server,windows 10

**Comment by Kitzunu** [comment]
Your core is old. It was fixed here https://github.com/azerothcore/azerothcore-wotlk/commit/abedfe245f176fd421a91301d97ba89a73251ab6
