### ISSUE TITLE
Level 65 WotLK food heals too much.

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#15152]
https://github.com/chromiecraft/chromiecraft/issues/5081
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Food that requires level 65 such as [Salted Venison](https://wowgaming.altervista.org/aowow/?item=33454), [Tundra Berries](https://wowgaming.altervista.org/aowow/?item=35949), and [Crusty Flatbread](https://wowgaming.altervista.org/aowow/?item=33449) heal roughly 10k more than they should over time period of 30 seconds. Approximate health gain over 30 seconds is 28k (including passive regen). 

Here are proofs with two different foods:

https://user-images.githubusercontent.com/107246426/220288086-b7ebb970-89ca-4da5-bf81-912f352a7687.mp4

https://user-images.githubusercontent.com/107246426/220288621-0b82be36-191c-48a6-ab0d-f8f9c8fc2e94.mp4

### Expected Blizzlike Behaviour

Each of these foods (and several others that require 65) should provide this [buff](https://wowgaming.altervista.org/aowow/?spell=43180). It should heal 616 health per second over 30 seconds summing up to 18480 health. 

### Source

https://www.wowhead.com/wotlk/spell=43180/food
https://wowgaming.altervista.org/aowow/?spell=43180

### Steps to reproduce the problem

1. .additem 33454
2. Target self
3. .mod hp 30000
4. .damage 29999
5. Eat the food
6. Observe how you are nearly full hp after 30 seconds of eating with around 28k health instead of ~18k.

### Extra Notes

Here is a list of items that gain the same buff while eating: https://wowgaming.altervista.org/aowow/?spell=43180#used-by-item

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ChrisCGalbraith** [comment]
Have you checked other food for other levels? I quickly tried an [Alterac Swiss](https://wowgaming.altervista.org/aowow/?item=8932) and it looks like I went from <100 to around 4k. Even with basic health regen included this feels like a little too much.

**Comment by Apathyxia** [comment]
Eating [Skethyl Berries](https://wowgaming.altervista.org/aowow/?item=27856) got me to ~6.7k hp. Eating [Soft Banana Bread](https://wowgaming.altervista.org/aowow/?item=4601) healed me roughly 2k hp when neglecting base regeneration. My base regen is 13 health per second. So, indeed, it seems like foods do heal too much in general (~50% too much).

**Comment by Tereneckla** [comment]
It looks the multiplicator for sitting is applied to the health regen from food

HP from eating the venison fully : 27960
HP from sitting for 30 seconds: 256
HP from standing for 30 seconds: 176
256/176 ≈ 1.5
(27960-256)/1.5 = 18496 ≈ healing from the venison

Measuring inaccuracies are a given, but it's close enough
