### ISSUE TITLE
 Icecrown Citadel 10 and 25-person heroic mode, Professor channel, wipe out.

### ISSUE THREAD

**Issue by skygitbaby** [azerothcore/azerothcore-wotlk#15162]
### Current Behaviour

After completing "Noth the Plaguebringer" and "Heigan the Unclean", there will be a lot of worms on the way to Professor. If it is Icecrown Citadel raid, 10-man heroic mode or 25-man heroic mode, there will be a skill to wipe out all people, including NPCBOTS. It has been experimented many times, can this problem be solved?

### Expected Blizzlike Behaviour

there will be a skill to wipe out all people

### Steps to reproduce the problem

The first step is to finish the 10-man or 25-man Icecrown Citadel raid in Normal mode. The second step is to enter the 10-man or 25-man Hero mode raid and defeat “Putricide” and “Rotface”. The third step is to go to Professor Putricide and trigger the bug trap.

### AC rev. hash/commit

All the members of the team died due to excessive damage as seen in the battle record.

### Operating system

Windows 10 x64

### Custom changes or Modules

Only used Trinity-Bots module, no other modules.

**Comment by noisiver** [comment]
I don't fully understand the issue to begin with but Noth and Heigan are a part of Naxxramas, how do those relate?
