### ISSUE TITLE
Server crash - I don't know what it was connected with

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#15178]
### Current Behaviour

[b3e37226745a+_worldserver.exe_[23-2_14-15-41].txt](https://github.com/azerothcore/azerothcore-wotlk/files/10813362/b3e37226745a%2B_worldserver.exe_.23-2_14-15-41.txt)

### Expected Blizzlike Behaviour

no

### Source

no

### Steps to reproduce the problem

I don't know what it was connected with

### Extra Notes

no

### AC rev. hash/commit

b3e37226745a+

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-npc-beastmaster and many others

**Comment by MegaserverRU** [comment]
![2023-02-23_14-48-22](https://user-images.githubusercontent.com/98691968/220904767-e0baaf7e-835c-454c-af1a-451bedfdf832.png)

**Comment by Nyeriah** [comment]
Please upload your logs using github.gist or pastebin. This looks like a crash caused by the pet generation name PR on a russian client

**Comment by MegaserverRU** [comment]
[Crashes.zip](https://github.com/azerothcore/azerothcore-wotlk/files/10813757/Crashes.zip)
I can only upload it this way, unfortunately I can't upload it any other way

**Comment by MegaserverRU** [comment]
> github.gist

https://gist.github.com/MegaserverRU/24dc71da9f612099ea98abf59c2915cb

**Comment by MegaserverRU** [comment]
https://gist.github.com/MegaserverRU/a93f3127b0155f7b1a283596660c9ec9

**Comment by MegaserverRU** [comment]
This crash occurred when the shaman player was on the world bosses custom_worldboss.lua

**Comment by Kitzunu** [comment]
Closing as it is not related to the core, but custom lua stuff

**Comment by MegaserverRU** [comment]
And what should ordinary users do now? How to fix it?

**Comment by MegaserverRU** [comment]
> Closing as it is not related to the core, but custom lua stuff

And what should ordinary users do now? How to fix it?
