### ISSUE TITLE
Enemies damaged by the player but killed by pet damage are not lootable

### ISSUE THREAD

**Issue by VerboseLamp** [azerothcore/azerothcore-wotlk#15179]
### Current Behaviour

Enemies killed by pets (such as Hunter and Warlock pets) and some pseudo-pet abilities (like Shaman's Searing Totem) are not lootable when the pet receives the killing blow, **even if the player has tagged the mob with a damaging attack or ability** and contributed to killing it.

### Expected Blizzlike Behaviour

Enemies killed by pet damage should yield lootable corpses, so long as the player has contributed damage to the kill.

### Source

Stock retail/classic behavior easily reproduced on any job with pet or pseudo pet abilities.

### Steps to reproduce the problem

Step 1: Tag an enemy with an attack or ability that causes any amount of damage to the target.
Step 2: Stop casting/attacking the enemy and allow the pet to get the killing blow on it.
Step 3: Verify the attack that causes the killing blow in the combat log.

### AC rev. hash/commit

AzerothCore rev. 590ab7c67f9d 2023-02-15 05:26:25 -0300 (main branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.8 7 Feb 2023 (library: OpenSSL 3.0.8 7 Feb 2023)
Using Boost version: 1.81.0
Using MySQL version: 80032
Using CMake version: 3.25.2
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List enable modules:
- DungeonRespawn
- mod-ah-bot
- mod-autobalance
- mod-eluna
- mod-individual-progression
- mod-reagent-bank
- mod-solo-lfg
- mod-starter-guild
- mod-transmog

### Operating system

Windows 10 x64

### Custom changes or Modules

- DungeonRespawn
- mod-ah-bot
- mod-autobalance
- mod-eluna
- mod-individual-progression
- mod-reagent-bank
- mod-solo-lfg
- mod-starter-guild
- mod-transmog

**Comment by bgcfb** [comment]
Comfirmed ,I have same problem

**Comment by Maelthyrr** [comment]
To get the loot you need "to do at least 50% + 1 damage to get loot/exp" (Blizzlike behavior). You can read the discussio  here: https://github.com/azerothcore/azerothcore-wotlk/pull/11969

Can you check if it's the case here?

**Comment by Nyeriah** [comment]
> To get the loot you need "to do at least 50% + 1 damage to get loot/exp" (Blizzlike behavior). You can read the discussio here: #11969
> 
> Can you check if it's the case here?

Not the case for player pets. One hit is enough to get credit, it was coded that way. However, I am not sure about the killing blow situation. @UltraNix should know more about this

**Comment by Logandros** [comment]
I've noticed this as well, it's really an issue when you solo content with npcbots. I thought it was just bad rng in my last ZG run but now I'm wondering if something has changed to make it more prevalent.

**Comment by frizzon** [comment]
I've seen this too, although I am using the Beastmaster module and only seems to happen when using a hunter pet on a non-hunter character. 
Haven't tested it on other pet classes like warlocks or DKs

**Comment by UltraNix** [comment]
1 hit made by player is enough to get loot and killing blows (kil credit etc).
