### ISSUE TITLE
The newly generated DB error report, I hope to help improve the whole program

### ISSUE THREAD

**Issue by kasting** [azerothcore/azerothcore-wotlk#15186]
### Current Behaviour

CreatureTextMgr: Could not find TextGroup 0 for Creature 鲁伯特上尉 (GUID Full: 0xf130009105000243 Type: Creature Entry: 37125  Low: 579). Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 阿尔纳斯上尉 (GUID Full: 0xf130009102000240 Type: Creature Entry: 37122  Low: 576). Ignoring.
Table `graveyard_zone` incomplete: Zone 0 Team 0 does not have a linked graveyard.
WaypointMovementGenerator::LoadPath: creature 火烟虐待者 (GUID Full: 0xf130000a9d004b8d Type: Creature Entry: 2717  Low: 19341) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 火烟猎龙者 (GUID Full: 0xf130000a9c004b90 Type: Creature Entry: 2716  Low: 19344) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 火烟萨满 (GUID Full: 0xf130000a9e004b91 Type: Creature Entry: 2718  Low: 19345) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 火烟猎龙者 (GUID Full: 0xf130000a9c004b92 Type: Creature Entry: 2716  Low: 19346) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 火烟秘法师 (GUID Full: 0xf130000b5b004b93 Type: Creature Entry: 2907  Low: 19347) doesn't have waypoint path id: 0
CreatureTextMgr: Could not find TextGroup 0 for Creature 阿尔纳斯上尉 (GUID Full: 0xf13000910200029f Type: Creature Entry: 37122  Low: 671). Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 布兰登上尉 (GUID Full: 0xf1300091030002a0 Type: Creature Entry: 37123  Low: 672). Ignoring.
Table `graveyard_zone` incomplete: Zone 0 Team 0 does not have a linked graveyard.
CreatureTextMgr: Could not find TextGroup 0 for Creature 布兰登上尉 (GUID Full: 0xf130009103000344 Type: Creature Entry: 37123  Low: 836). Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 鲁伯特上尉 (GUID Full: 0xf130009105000346 Type: Creature Entry: 37125  Low: 838). Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 阿尔纳斯上尉 (GUID Full: 0xf1300091020002ef Type: Creature Entry: 37122  Low: 751). Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 布兰登上尉 (GUID Full: 0xf1300091030002f0 Type: Creature Entry: 37123  Low: 752). Ignoring.
CreatureTextMgr: Could not find Text for Creature(尼德斯) Entry 15689 in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 布兰登上尉 (GUID Full: 0xf130009103000267 Type: Creature Entry: 37123  Low: 615). Ignoring.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 33579 SourceType 0 EventType 38 TargetType 19 using non-existent Text id 4 for talker 33579, ignored.
WaypointMovementGenerator::LoadPath: creature 黑暗符文雷鸣者 (GUID Full: 0xf1300083da00251c Type: Creature Entry: 33754  Low: 9500) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 黑暗符文劫毁者 (GUID Full: 0xf1300083db0025ab Type: Creature Entry: 33755  Low: 9643) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 黑暗符文雷鸣者 (GUID Full: 0xf1300083da0025ac Type: Creature Entry: 33754  Low: 9644) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature 黑暗符文劫毁者 (GUID Full: 0xf1300083db0025ad Type: Creature Entry: 33755  Low: 9645) doesn't have waypoint path id: 0
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 29523 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 31190, ignored.
CreatureTextMgr: Could not find TextGroup 0 for Creature 布兰登上尉 (GUID Full: 0xf13000910300024d Type: Creature Entry: 37123  Low: 589). Ignoring.
CreatureTextMgr: Could not find TextGroup 0 for Creature 格隆戴尔上尉 (GUID Full: 0xf13000910400024e Type: Creature Entry: 37124  Low: 590). Ignoring.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 2629300 SourceType 9 EventType 60 TargetType 2 using non-existent Text id 0 for talker 1964, ignored.
SmartScript: Action target for SMART_ACTION_SET_COUNTER is not using SmartAI, skipping
WaypointMovementGenerator::LoadPath: creature 结晶看管者 (GUID Full: 0xf130006e4700002b Type: Creature Entry: 28231  Low: 43) doesn't have waypoint path id: 0

### Expected Blizzlike Behaviour

In the report, I think some AI is missing

### Steps to reproduce the problem

In a particular instance, trigger the story

### AC rev. hash/commit

AzerothCore rev. 1e19770e2fcf 2023-02-21 19:26:35 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.81.0
Using MySQL version: 80031
Using CMake version: 3.25.2
Compiled on: Windows 10.0.20348
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014339 bytes
vmaps directory located in ./vmaps. Total size: 658130553 bytes
mmaps directory located in ./mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna
- mod-zone-difficulty

### Operating system

WINDOWS

**Comment by Nyeriah** [comment]
It looks like your database import failed. Try emptying your database and restarting your server so the autoupdater populates it.

**Comment by qq462518439** [comment]
> It looks like your database import failed. Try emptying your database and restarting your server so the autoupdater populates it.

I have the exact same error report!I tried a whole new compilation and a whole new database and the problems still persisted
