### ISSUE TITLE
Travis build takes too long

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/azerothcore-wotlk#1518]
##### SMALL DESCRIPTION:
Travis build takes too long.

##### EXPECTED BEHAVIOUR:
A Travis run took around 30 minutes using Ubuntu 14.04, e.g.:
commit ffa7b7a286d1f59b7a726e18110310add630701c
Travis run: https://travis-ci.org/azerothcore/azerothcore-wotlk/builds/470475874

##### CURRENT BEHAVIOUR:
After commit a0595b73e3fcfde53a205a3c3b760353ed14e9bd, through which the Travis configuration was updated to use Ubuntu 16.04, a run took nearly 40 minutes, see for example this commit:
commit 54a6817bbba2a77189ee24d02e9d4eac690f4628
Travis run: https://travis-ci.org/azerothcore/azerothcore-wotlk/builds/471299612

##### STEPS TO REPRODUCE THE PROBLEM:
Just look at the Travis runs.

##### EXTRA NOTES:
I tried to reduce the duration of Travis runs by using ccache, but if a central component of the core is changed ccache won't work because everything has to be recompiled. The timeout which terminates the build after 45 minutes can be used to fill the cache and you can start the Travis job once again manually, but this is rather ugly. The main problem here is that Travis only allows 50 minutes build time. After this duration it will just kill the process.

Does someone has an idea why the build takes 10 minutes longer on Ubuntu 16.04 than on Ubuntu 14.04?

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
Every commit after a0595b73e3fcfde53a205a3c3b760353ed14e9bd

##### OPERATING SYSTEM:
Ubuntu 16.04

##### MODULES:
not relevant

##### OTHER CUSTOMIZATIONS:
not relevant

**Comment by BarbzYHOOL** [comment]
If we had donations we could get https://travis-ci.com/plans haha
