### ISSUE TITLE
Bag issue

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#152]
**Description**:
When your bags are full and u equipt a fishing rod, from 2x one handed weapon, it equipts the fishing pole 1 weapon goes into bag and the other goes into the mailbox from "customer support"

**Expected behaviour**: Tell us what should happen instead
Should get an error about the bag space and shouldnt be able to equipt if not enough bag space for weapons 

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Branch(es)**: master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
Windows 10

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
##

**Comment by sucofog** [comment]
Weird bug lol

**Comment by Viste** [comment]
maeby need made config option for this, i think i know where is that shit place

**Comment by Pondaveia** [comment]
@Viste any news on this?

**Comment by Viste** [comment]
I've already forgotten about it lol not hard to fix btw

**Comment by poszer** [comment]
Confirmed. really weird bug lol
