### ISSUE TITLE
AzerothCore does not support MySQL versions below 5.7 and MariaDB 10.5

### ISSUE THREAD

**Issue by marcodifresco** [azerothcore/azerothcore-wotlk#15204]
### Current Behaviour

I got some updates for the Ubuntu Server 22.04 I am using for AzerothCore, but now AzerothCore is not launching giving the error:
`AzerothCore does not support MySQL versions below 5.7 and MariaDB 10.5`

I do have MariaDB 10.5:
```
# mysql --version
mysql  Ver 15.1 Distrib 10.5.19-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

### Expected Blizzlike Behaviour

The server starting

### Steps to reproduce the problem

1. Update Ubuntu Server;
2. Update AzerothCore to the latest version;
3. Run AzerothCore.

### AC rev. hash/commit

b263f4518..bae273c77  master     -> origin/master

### Operating system

Ubuntu Server 22.04

**Comment by Kitzunu** [comment]
Make sure to install  `libmariadb-dev-compat`, `mariadb-client`, `libmariadbclient-dev`

There's no issues serverside as it works for everyone else. So something on your end.

**Comment by marcodifresco** [comment]
Thanks.

Indeed libmariadbclient-dev was not updated with the rest of the mariadb packages.

**Comment by wbrione** [comment]
AzerothCore rev. 33ef56b00210+ 2024-01-05 09:48:50 +0000 (master branch) (Unix, RelWithDebInfo, Static) (dbimport)
<Ctrl-C> to stop.

(...)

     AzerothCore 3.3.5a  -  www.azerothcore.org

> Using configuration file:       /azerothcore/env/dist/etc/dbimport.conf
> Using SSL version:              OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
> Using Boost version:            1.74.0
 
Configuration field WorldDatabaseInfo was overridden with environment variable.
Configuration field CharacterDatabaseInfo was overridden with environment variable.
Configuration field LoginDatabaseInfo was overridden with environment variable.
Configuration field LogsDir was overridden with environment variable.
Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 8.0.35
MySQL server ver: 5.5.5-10.6.16-MariaDB-1:10.6.16+maria~ubu2004 
Connected to MySQL database at mariadb
AzerothCore does not support MySQL versions below 5.7 or MariaDB versions below 10.5.

Found server version: 50505. Server compiled with: 80035.
DatabasePool Login NOT opened. There were errors opening the MySQL connections. Check your log file for specific errors

###########################

root@a21acac0df43:/# mysql -V
mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

###########################

So @Kitzunu... If MariaDB 10.5+ is support... Why docker image has not have the requirements already installed (e.g.: libmariadb-dev-compat, mariadb-client, libmariadbclient-dev, and so) ???
