### ISSUE TITLE
Rename auth.realmlist.port to auth.realmlist.worldserver_port

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1521]
Quick suggestion:

Rename column `port` in `realmlist` table in the `auth` db to `worldserver_port` because each time I'm like "is it for authserver or worldserver?" :P

**Comment by FrancescoBorzi** [comment]
I think this should just be documented in the wiki

**Comment by BarbzYHOOL** [comment]
why have to open a wiki page for that?

else we can name it "turtle" instead of port and then we open the wiki to see what turtle means

**Comment by Nefertumm** [comment]
I'm against this change.

**Comment by FrancescoBorzi** [comment]
... also it would create a difference with the TC auth, and might cause issues to people using the same authserver with TC and AC.. I'm not sure if the benefit would be worth risking to fucks things up :)

**Comment by Nefertumm** [comment]
> ... also it would create a difference with the TC auth, and might cause issues to people using the same authserver with TC and AC.. I'm not sure if the benefit would be worth risking to fucks things up :)

That's why I'm against this change.

**Comment by BarbzYHOOL** [comment]
We'll always be in the shadow of TC, let's keep their bad stuff!

It would be better to rename but I know in practice it's better (for now) to stay on the safe side though. I'm just (half) joking.

**Comment by Viste** [comment]
there is should be Realm server if be true, but now Realm server is part of worldserver so that info in DB is right

**Comment by Viste** [comment]
and its not TC stuff, its mangos the father of the TC and AC https://github.com/cmangos/mangos-wotlk/blob/master/sql/base/realmd.sql#L159

**Comment by JamesGent** [comment]
This was a rename suggestion which didn't seem to stick. No comments in 20 months so I will close it and if you want to suggest the rename again (if it's still relevant at all) then feel free to make a new one.
