### ISSUE TITLE
Hunter: Deterrence spell [$5]

### ISSUE THREAD

**Issue by TheHighlord** [azerothcore/azerothcore-wotlk#1522]
##### SMALL DESCRIPTION:
Hunter Deterrence spell not working correctly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
https://wotlk.evowow.com/?spell=19263
Parry chance increased by 100%, chance for ranged attacks to miss you increased by 100%, 100% chance to deflect spells, and unable to attack.

##### CURRENT BEHAVIOUR:
Currently the spell isnt parrying the melee damage at all.
https://youtu.be/D77rxBRFzTo

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Play as a hunter
2. Taunt a mob
3. Cast Deterrence
4. See you won't parry mob's melee damage.

**Comment by talamortis** [comment]
please fill out the correct template.

**Comment by comix1988** [comment]
I confirm.
look at my video where i spam deterrence.

[link](https://youtu.be/_pVGlK4LMkY)

**Comment by TheHighlord** [comment]
https://www.youtube.com/watch?v=QadZiD8JX_4&feature=youtu.be

Then check this out. :)

**Comment by comix1988** [comment]
@TheHighlord in your video you take damage from disease.
Disengage prevent damage from melee attacks.

**Comment by TheHighlord** [comment]
> @TheHighlord in your video you take damage from disease.
> Disengage prevent damage from melee attacks.

Nope. The mob also gives me melee attack, also I tried it on the boars too.

**Comment by talamortis** [comment]
You have placed a bounty on this but what hash are you using?

**Comment by TheHighlord** [comment]
> You have placed a bounty on this but what hash/commit are you using?

I am using [0a49447](https://github.com/azerothcore/azerothcore-wotlk/commit/0a49447f05d00ede689cd36e4c646547c2fee857)

**Comment by Nefertumm** [comment]
Try this:
```diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 1fd6ccb9..29a7b17d 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -2318,7 +2318,7 @@ MeleeHitOutcome Unit::RollMeleeOutcomeAgainst(const Unit*  victim, WeaponAttackTy
if (tmp > 0                                         // check if uni t _can_ parry
     && (tmp -= skillBonus) > 0
-    && roll < (sum += tmp))
+    && roll < (sum += tmp) || (victim->HasAura(19263) && victim->Ha sInArc(M_PI, this)))
{
#if defined(ENABLE_EXTRAS) && defined(ENABLE_EXTRA_LOGS)
    sLog->outStaticDebug ("RollMeleeOutcomeAgainst: PARRY <%d, %d)" , sum-tmp, sum);
```

**Comment by TheHighlord** [comment]
I don't get it... then why this was working for @comix1988 ?

**Comment by Nefertumm** [comment]
You are missunderstanding. Deterrence doesn't work and he confirmed it. The only thing he told you that you was taking damage from poison too, which is correct. 
I think he meant deterrence should prevent damage from melee attacks.

**Comment by GitVerge** [comment]
Actually I'm also wondering why do we have different results on each video. Could you guys try with latest rev?

**Comment by comix1988** [comment]
@GitVerge @Nefertumm look at my video, at the second 0:06 I take damage melee even with the buff of deterrence. It's a bug.

**Comment by TheHighlord** [comment]
Haha, yeah I tought @comix1998 just wanted to be sarcastic when he confirmed it. Then it is indeed a valid issue.
