### ISSUE TITLE
Object::GetGuidValue  crash

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#15228]
### Current Behaviour

https://gist.github.com/boom8866/a254016e488121c949a5306aeff0bf64

### Expected Blizzlike Behaviour

no

### Source

no

### Steps to reproduce the problem

no

### Extra Notes

no

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8635ab01706a76f2476d7c918b6165b98ca960bf

### Operating system

Debian 10 x64

### Custom changes or Modules

 Anticheat.conf.dist
 BGReward.conf.dist
 CFBG.conf.dist
mod_LuaEngine.conf.dist
GMChatColor.conf.dist
 VIPChatColor.conf.dist
Individual-XP.conf.dist
InstanceBuff.conf.dist
mod_multilogin.conf.dist
ServerAutoShutdown.conf.dist
SkipDKModule.conf.dist
SoloLfg.conf.dist
transmog.conf.dist
UnbindInstance.conf.dist
mod-zone-difficulty.conf.dist

**Comment by walkline** [comment]
It should already be fixed - https://github.com/azerothcore/azerothcore-wotlk/pull/17021
