### ISSUE TITLE
ICC: Bug with Bone Spike Graveyard at Lord Marrowgar

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15226]
### Current Behaviour

In combat with  Lord Marrowgar when he casts [Bone Spike Graveyard](https://www.wowhead.com/wotlk/spell=69057/bone-spike-graveyard) on you it does not Impale you or deal damage to you, and allows you to move and attack the enemy directly.

When a player destroys Bone Spike Graveyard, the player who should be impaled is returned to the original position where [Bone Spike Graveyard](https://www.wowhead.com/wotlk/spell=69057/bone-spike-graveyard) was cast,

https://youtu.be/zxothU17Fjw

### Expected Blizzlike Behaviour

It should impale you and deal x amount of damage per second and prevent you from moving until the [Bone Spike Graveyard](https://www.wowhead.com/wotlk/spell=69057/bone-spike-graveyard) is destroyed

### Source

[Bone Spike Graveyard](https://www.wowhead.com/wotlk/spell=69057/bone-spike-graveyard)
https://wowpedia.fandom.com/wiki/Lord_Marrowgar

### Steps to reproduce the problem

1. te icec , with at least two players, invite a party and turn it into a raid
2. enter and go to  Lord Marrowgar
3. start the fight with a pj
4. wait until he throws Bone Spike Graveyardto the other play

### AC rev. hash/commit

8635ab01706a76f2476d7c918b6165b98ca960bf

### Operating system

Ubuntu 20.04

**Comment by Tony931023** [comment]
needs: 80, Priority-High, Instance - Raid - Northrend

**Comment by Tony931023** [comment]
This gets corrupted when I apply this change https://github.com/azerothcore/azerothcore-wotlk/pull/14789 by @Nyeriah 

You can try to go back to commit ee4de44c5a5d6c123c0492d3fa00a60295dfbe62 that problem is not found here.

```
git checkout ee4de44c5a5d6c123c0492d3fa00a60295dfbe62
git switch -c ee4de44c5a5d6c123c0492d3fa00a60295dfbe62 
 ```
You can try to go back to commit ee4de44c5a5d6c123c0492d3fa00a60295dfbe62 that problem is not found here

repeat the compilation process on the new branch and test that Bone Spike Graveyard has no errors

If you go back to the main branch and now try the commit bf30c66ba48cede909a98cb132959c979c032b3b you will find the errors of this iss

```
git switch -c master 
git checkout bf30c66ba48cede909a98cb132959c979c032b3b
git switch -c bf30c66ba48cede909a98cb132959c979c032b3b
```

**Comment by Nyeriah** [comment]
Test https://github.com/azerothcore/azerothcore-wotlk/pull/15238

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/15238
