### ISSUE TITLE
Server crash. I can't understand why

### ISSUE THREAD

**Issue by MegaserverRU** [azerothcore/azerothcore-wotlk#15248]
### Current Behaviour

https://gist.github.com/MegaserverRU/a93f3127b0155f7b1a283596660c9ec9
[Crashes.zip](https://github.com/azerothcore/azerothcore-wotlk/files/10880851/Crashes.zip)

### Expected Blizzlike Behaviour

I was in the dungeon with the death knight class and fought with the boss https://www.wowhead.com/wotlk/npc=27483/king-dred
![WoWScrnShot_030323_102413](https://user-images.githubusercontent.com/98691968/222692606-dc445388-7704-497c-9ba5-33d93bae112d.jpg)

### Source

no

### Steps to reproduce the problem

no

### Extra Notes

no

### AC rev. hash/commit

b3e37226745a+

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-eluna

**Comment by KillMean** [comment]
you can close the problem. it is related to the taming of animals module for all classes
https://www.azerothcore.org/catalogue.html#/details/123951676

**Comment by KillMean** [comment]
a death knight tames a pet and fashion, and if you click on the spell summon a pet, a death knight pet will appear, not the one you tamed, and the server will crash https://www.azerothcore.org/catalogue.html#/details/123951676

**Comment by Nyeriah** [comment]
Module crash
