### ISSUE TITLE
Add .cheat explore

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1524]
Follow up to this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/1412

Command `.cheat explore` wasn't added because troublesome:

```
('cheat explore',   2, 'Syntax: .cheat explore #flag\r\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\nUse a #flag value of 1 to reveal, use a #flag value of 0 to hide all maps.'),
```

**Comment by poszer** [comment]
Actually it's added but in the misc command list. So i would suggest to remove it from here, and put in the cs_cheat script.
https://github.com/azerothcore/azerothcore-wotlk/blob/4fa60c06b2ddda61da057354ec38b8015b747900/src/server/scripts/Commands/cs_misc.cpp#L85

**Comment by BarbzYHOOL** [comment]
and it's working?
