### ISSUE TITLE
All Item generation with a random suffix should use the RandPropPoints.dbc to get their suffix factor

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15257]
https://github.com/chromiecraft/chromiecraft/issues/5117
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Wrong generation, for example https://wowgaming.altervista.org/aowow/?item=30684 has 57 int, https://wowgaming.altervista.org/aowow/?item=30683 has 43 int
(same skew with the other values)

### Expected Blizzlike Behaviour

Items use the RandPropPoints.dbc to get their suffix factor
The examples have 55 and 41 int respectively

### Source

https://www.wowhead.com/wotlk/item=30684/ravagers-cuffs
https://www.wowhead.com/wotlk/item=30683/gliders-greaves

![image](https://user-images.githubusercontent.com/50233983/222835671-06a8a029-0ac7-4cdd-98b3-47446bf898cd.png)
ID = Item Level
Row of 115 has factors of 55 and 41 for 2 types of epic items

### Steps to reproduce the problem

.add 30684 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/73e289ad95c551b9ba4822c6149bcc98c3422665

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
These factor are there to get entry from ItemRandomSuffixStore and get needed enchantments.

**Comment by Tereneckla** [comment]
Yes, ItemRandomSuffix holds the the name of a suffix with IDs to enchantments and weights for those enchantments

RandPropPoints holds itemlevel and 4 values for each rarity (epic, rare, uncommon)
With the value of RandPropPoints according to itemlevel and itemslot x the weights from ItemRandomSuffix you get the stats of the enchant

Ravager Cuffs (ItemLevel 115, Wrists are column 3) -> PropPoints 41
of Intellect (enchant 2804, weight 10000) -> 2804 is Intellect
So we get 41 * 100.00% Intellect on the item

Azerothcore currently puts 43 Int on those bracers

**Comment by UltraNix** [comment]
![asfdsdf](https://user-images.githubusercontent.com/80540499/224508141-5511b1f2-3e4a-425e-a9b0-e28e505378e6.png)

**Comment by Tereneckla** [comment]
I got my files from the client that is available to download on the chromiecraft side and it matches with the values on wowhead

**Comment by UltraNix** [comment]
But now you see why the values are different - dbc files.
Mine are generated via tools.

**Comment by Tereneckla** [comment]
I just found that the ones on my client and on wowhead differ from the ones we currently have
