### ISSUE TITLE
[server] world server crash0304

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#15261]
### Current Behaviour

crash log:

https://gist.github.com/mpfans/7125a0743dc0d0af7afd23dbe6c316cf

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/7a78146498f8064da99cf899d2d8b33030d2f0ef

### Operating system

Ubuntu20.04

**Comment by Kitzunu** [comment]
Your core is outdated. the lines from the crashlog does not match with the current core.
