### ISSUE TITLE
The problem with custom races.

### ISSUE THREAD

**Issue by GrunzaTape** [azerothcore/azerothcore-wotlk#1526]
##### SMALL DESCRIPTION:

If I change the character's appearance, I get a broken model when I get back.

##### STEPS TO REPRODUCE THE PROBLEM:

1. ChrRaces.dbc
2. Goblin (9). (Male - 32550) (Female - 32551) (DisplayID)
3. Queldorei (15). (Male - 32552) (Female - 32553) (DisplayID)
4. Completely filled: CharSections, Barber, CreatureModelData etc..
I'll add it.
If you copy it and run it on TrinityCore, you won't see any errors and races work correctly.

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Win 10 x64 / MySQL  5.6

##### MODULES:

clear list

##### SCREENSHOTS:

![Image alt](https://media.discordapp.net/attachments/415944535718494208/548794735658270740/unknown.png?width=966&height=421)
![Image alt](https://media.discordapp.net/attachments/415944535718494208/548796319523799061/unknown.png?width=966&height=404)

**Comment by Mutevazi** [comment]
idk, but I have the exact same problem with adding any races. At first, I thought I had a problem with models, and that's what it turns out to be.

**Comment by brussens** [comment]
Checked it out. Problem not confirmed.

**Comment by FrancescoBorzi** [comment]
@GrunzaTape @Mutevazi @brussens thanks a lot for reporting/confirming/unconfirming. However please post your AC version (commit hash) whenever you report/confirm/unconfirm an issue.

**Comment by Viste** [comment]
Can't confrim no problems here

**Comment by avatar789** [comment]
The problem really is, I suffered zandalar and voidelf with polymorph and druid forms, the model crashes
![WoWScrnShot_052920_000136](https://user-images.githubusercontent.com/5444058/83254501-0dd10a00-a1d9-11ea-826b-fe00b154ee1a.jpg)
![WoWScrnShot_052920_130515](https://user-images.githubusercontent.com/5444058/83254504-0f9acd80-a1d9-11ea-99c8-cf44e685c630.jpg)

**Comment by Helias** [comment]
We need a way to reproduce the bug locally

**Comment by avatar789** [comment]
> We need a way to reproduce the bug locally

https://github.com/azerothcore/azerothcore-wotlk/issues/3092#issue-627915993
