### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by assada** [azerothcore/azerothcore-wotlk#15272]
### Current Behaviour

Some fatal errors on rebuild image (recompile AC)
build log with errors: https://gist.github.com/assada/57d19e06620699d22e158a85972427db

### Expected Blizzlike Behaviour

no compile error

### Steps to reproduce the problem

1. clone `master@edb9df9347a14454341bbf2be6fd13be8d9fe4b4`
2. `./acore.sh docker build`

### AC rev. hash/commit

edb9df9347a14454341bbf2be6fd13be8d9fe4b4

### Operating system

Debian 22.10

### Custom changes or Modules

mod-transmog

**Comment by Kitzunu** [comment]
I dont know how the dashboard works.

But all CI pass so something on your end. Most likely you need to rerun CMake
