### ISSUE TITLE
[SPELL][AURA][ICCBOSS]Gas Spore - Festergut

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1528]
##### SMALL DESCRIPTION:
After the explosion of the [https://www.wowhead.com/spell=69279/gas-spore](url) a spell of 
Festergut ( https://www.wowhead.com/npc=36626/festergut) 
the debuff ( [https://www.wowhead.com/spell=69290/blighted-spores](url) )  is not applied for every single one Spore that exploded  , is applied just one debuf olso if the players are hit by 2 o 3 spore

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After the explosion of a Gas Spore should be a applied on the player a debuff called https://www.wowhead.com/spell=69290/blighted-spores that  debuff should stack every time that u're in range of explosion of a Gas Spore for example.. there 3 players in the room and each one of them have a gas spore on the head after the explosion of the Gas spore if all of them are in the same point should be applied 3 stacks of https://www.wowhead.com/spell=69290/blighted-spores#triggered-by on each player , but for example if just 2 players have the Gas Spore on the head but all 3 players or more are in the same point should be applied 2 stacks of the spell https://www.wowhead.com/spell=69290/blighted-spores#triggered-by olso on the players that don't have the gas spore on the head if they are in the range of the explosion , when the debuff finish to do damage should be applied on each player that has 3 2 o1 stack of the debuff  https://www.wowhead.com/spell=69290/blighted-spores#triggered-by just a one stack of an another debuff  called inoculated https://www.wowhead.com/spell=69291/inoculated that will reduce the damage taken  and will stacks up to 3 times 

https://www.youtube.com/watch?v=cQYVvu-2a60 FROM 1.34 TO 2.50 EASY AND FAST EXPLENATION 

##### CURRENT BEHAVIOUR:
Every time that 2 or 3 people that have the gas spore on the head are in the same point the debuff https://www.wowhead.com/spell=69290/blighted-spores#triggered-by is applied just 1 time not stacking  for every explosion that hit the players after the debuff is finish is applied correctly the other debuff called https://www.wowhead.com/spell=69291/inoculated 

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go Inside Icc and Find the Boss Festergut in 2 or more people  ( https://www.wowhead.com/npc=36626/festergut) 
2. start the fight and wait until the boss uses the spell Gas Spore , all player that have and don't have the gas spore on the head have to go in the same point
3. After the explosion of the gas spore u will see that will be applied just one debuff on every player that was in the range of the explosion of the 2 , 3 gas spore 

##### EXTRA NOTES:
High Prio Icc Boss 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by Nefertumm** [comment]
Confirmed.

**Comment by GMKyle** [comment]
I don't know how this worked on retail but i found this:

It's not possible to gain more than one stack of Inoculation at the same time, that is standing within 5 yards of more than one spore results in higher damage taken, but not extra Inoculation stacks. 

https://wowwiki.fandom.com/wiki/Festergut

**Comment by mik1893** [comment]
the mechanics here are a bit tricky. 
When Gas Spore hits, applies debuff blighted spores. Different players with gas spores are considered the different casters. Now, blighted spores cannot stack from different casters (the flag SPELL_ATTR3_STACK_FOR_DIFF_CASTERS is not on the spell), so it won't stack. It makes sense that 2 separate debuffs are not applied otherwise it would be tricky to avoid putting inoculation twice.

I've checked teh code we have at the moment and i think part of the logic is wrong. Gas Spores is casted by Festergut, the triggered spell should be triggered by festergut himself (same caster), so it should be allowed to stack properly. at the end of the damage effect, anyway only one inoculation should be given.

Might have a look later if i have time

**Comment by GitVerge** [comment]
I've made a fix for myself long ago, it is a hack but works perfectly, in case someone really needs it:

```
class spell_festergut_blighted_spores : public SpellScriptLoader
{
    public:
        spell_festergut_blighted_spores() : SpellScriptLoader("spell_festergut_blighted_spores") { }

		class spell_festergut_blighted_spores_AuraScript : public AuraScript
		{
			PrepareAuraScript(spell_festergut_blighted_spores_AuraScript);

			bool Validate(SpellInfo const* /*spell*/)
			{
				if (!sSpellMgr->GetSpellInfo(SPELL_INOCULATED))
					return false;
				return true;
			}

			void ExtraEffectOne(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
			{
				if (InstanceScript* instance = GetTarget()->GetInstanceScript())
					if (Creature* festergut = ObjectAccessor::GetCreature(*GetTarget(), instance->GetData64(DATA_FESTERGUT)))
						festergut->AI()->SetData(DATA_INOCULATED_STACK, GetStackAmount());
			}

			void ExtraEffectTwo(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
			{
				if (GetDuration() < 500) {
					if (Aura* a = GetTarget()->GetAura(sSpellMgr->GetSpellIdForDifficulty(SPELL_INOCULATED, GetTarget())))
					{
						if (a->GetDuration() < a->GetMaxDuration() - 7000)
							GetTarget()->CastSpell(GetTarget(), SPELL_INOCULATED, true);
					}
					else
						GetTarget()->CastSpell(GetTarget(), SPELL_INOCULATED, true);
				}
			}

			void Register()
			{
				AfterEffectApply += AuraEffectApplyFn(spell_festergut_blighted_spores_AuraScript::ExtraEffectOne, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
				OnEffectRemove += AuraEffectRemoveFn(spell_festergut_blighted_spores_AuraScript::ExtraEffectTwo, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
			}
		};

        AuraScript* GetAuraScript() const override
        {
            return new spell_festergut_blighted_spores_AuraScript();
        }
};

```

**Comment by GMKyle** [comment]
like i said, after reading https://wowwiki.fandom.com/wiki/Festergut it's working like it should

**Comment by Kitzunu** [comment]
Gonna close as marked not confirmed for 2 years
