### ISSUE TITLE
[ITEM][ICC] GUNSHIP BATTLE

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1529]
Description: The Goblin Rocket Pack the item needed for the third ICC boss, the Gunship Battle, should disappear once the opposing ship is killed.

https://wowwiki.fandom.com/wiki/Goblin_Rocket_Pack

Current behavior: The item remains in the Bags even after the fight is over.

Expected behavior: Once the Gunship Battle is won, the Goblin Rocket Pack should disappear   

"Once the Gunship Battle has been won, this item will vanish"

https://wowwiki.fandom.com/wiki/Goblin_Rocket_Pack

Steps to Reproduce the Problem: 

Take the item, win the Gunship Battle, notice it stays in bags or on the Players!

##### EXTRA NOTES:
Low Prio Bug

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by lineagedr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp#L648

Add:

> // Destory Goblin Rocket Pack
					Map::PlayerList const &PlayerList = me->GetMap()->GetPlayers();
					if (!PlayerList.isEmpty())
						for (Map::PlayerList::const_iterator itr = PlayerList.begin(); itr != PlayerList.end(); ++itr)
							if (Player* pPlr = itr->GetSource())
								pPlr->DestroyItemCount(49278, 1, true);

**Comment by lineagedr** [comment]
Add this code after https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp#L648

       // Destory Goblin Rocket Pack
        Map::PlayerList const &PlayerList = me->GetMap()->GetPlayers();
		if (!PlayerList.isEmpty())
			for (Map::PlayerList::const_iterator itr = PlayerList.begin(); itr != PlayerList.end(); ++itr)
				if (Player* pPlr = itr->GetSource())
					pPlr->DestroyItemCount(49278, 1, true);

**Comment by Viste** [comment]
@lineagedr plz open PR for add this to main repo

**Comment by Kaev** [comment]
I made the PR for lineagedr now.
