### ISSUE TITLE
[PVP/PVE][SPELL] FIRE NOVA 

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1530]
##### SMALL DESCRIPTION:
The Shaman spell Fire Nova have not range limit , not the range of the damage of the spell that is activated on the totem https://wow.gamepedia.com/Magma_Totem , the range of activation of the spell from the totem 
 https://wotlk-twinhead.twinstar.cz/?spell=1535 (spell fire nova ) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
 The shaman spell Fire Nova should have a range of 30 yard   , 36 if improved with talent , of activation from the totem https://wow.gamepedia.com/Magma_Totem

https://wotlk-twinhead.twinstar.cz/?spell=1535

##### CURRENT BEHAVIOUR:
Infinite Range of Activation from the totem https://wow.gamepedia.com/Magma_Totem

##### STEPS TO REPRODUCE THE PROBLEM:
summon https://wow.gamepedia.com/Magma_Totem , don't waste time the totem will disappear  , go far from the totem , more than 36  yard or more and u will see that the spell Fire Nova can be activated 

##### AC HASH/COMMIT:

44272f1

**Comment by GitVerge** [comment]
Right, I'll probably fix this one during this week

**Comment by FrancescoBorzi** [comment]
@GitVerge I can help you, no problem. Just ping me in chat.

**Comment by Viste** [comment]
@Heisenberg520 check plz #1566
