### ISSUE TITLE
Netherstorm: Shutting Down Manaforge Coruu cant be finished

### ISSUE THREAD

**Issue by Yarusha-ret** [azerothcore/azerothcore-wotlk#15303]
What client do you play on?
enUS

Faction
Horde

Content Phase:
65-69

Current Behaviour
NPC Caledis Brightdown gives you the quest: Shutting down manaforge coruu.

you need to kill overseer seylanna and get [Coruu Access Crystal], then click in the manaforge mechanism to shutdown the manaforge..
As i said before i did all those steps and get the yellow "Quest complete" announce, then i go to the npc to finish the quest but he ask me for [Coruu Access Crystal] i dont know why because it is my bag.

Expected Blizzlike Behaviour
It should let me finish the quest because i have the item in my bag and i already shutdown the manaforge.

Source

![image](https://user-images.githubusercontent.com/127250808/223545161-0632dea6-11ad-44cd-a7f5-17e4748f6c84.png)
![image](https://user-images.githubusercontent.com/127250808/223545204-57607d80-6232-47c3-8e54-88649af2a2f0.png)

Steps to reproduce the problem
Kill overseer Seylanna and pick [Coruu Access Crystal].
Click the mechanism to shut down manaforge coruu.
Defend the mechanism while it is shutting down (even when you have invisible npc hitting you).
go back to NPC Caledis Brightdown.
Finish the quest without problem.
Extra Notes
No response

AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/5b602508808a134e5df6051af7774952df00a7d0

Operating system
Ubuntu 20.04

Modules
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft

**Comment by balleny** [comment]
you likely completed the quest in a group. someone else initiated the shutdown.
currently, it is buggy that only the person initiating the shutdown is getting credited - even if it is displayed for all group members

**Comment by avarishd** [comment]
Can confirm.
It's currently rewarding only the one who has started the gossip. Probably changing to invoker_party will fix it.
