### ISSUE TITLE
[EQUIP][AURA][PVP/PVE] LIBRAM - SIGIL - RELIC -TOTEM !! 

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1531]
##### SMALL DESCRIPTION:
LIBRAM - SIGIL - RELIC- TOTEM ACTIVATION IN SOME CASES DOESN'T WORK PROPERLY 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The buff of the relic /totem /libram / sigil should procs when is equipped and u start a fight , when is not equipped u start a fight and after u equip it , when u switch a libram with an another libram in fight ,when u're in fight and the proc of the first libram is active and u switch the libram with a secondo one ,the buff of the first libram have not to disappear when the first libram is switched with the second one and the buff of the second libram have to activate olso if the first buff of the first libram is not expired 

A lot of pro Paladin Players in offy used to switch during the fight this 2 libram to have the 2 buff active at the same time  - https://wotlk.evowow.com/?item=50455 - https://wotlk.evowow.com/?item=47661

at this moment on azeroth core in not possible for the reasons that i've explained 

##### CURRENT BEHAVIOUR:
If a Pally / Shaman / Dk / Druid starts a fight without any relic (Libram / Totem / Sigil) equipped and equips it during the fight / combat, the relic will NOT activate until the combat finish and starts a new fight. If you start the fight with the relic equipped and then it is removed or replaced with a different relic, the relic buff disappears, if it is replaced with a second relic, the buff of the first disappears and the buff of the second relic that is equipped does not activate, the effect of the relic should be active both if the relic is equipped with the fight started and in case of replacement or if it is unequipped or in the case of a replacement of the relic with a second relic should lead to the activation of the buff of the second relic while still keeping the buff of the first relic active until it's expiration, this does not happen - 

https://wotlk.evowow.com/?items=4&filter=ty=7:8:9:10

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Dk/paladin/druid/shaman equip a relic/sigil/totem/libram
2 follow what i've wrote in current behaviour

##### EXTRA NOTES:

 HIGH PRIO BUG 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by gengarshadowball** [comment]
This actually makes a lot of sense, however, can you provide some footage that proves this? It's not that I don't believe, I'll actually look into it but need to make it official.
Maybe someone can provide confirmation too?

**Comment by lineagedr** [comment]
I'm pretty sure it's intended after equiping an item with a proc it has a 30 second cooldown before it can be used.

**Comment by JamesGent** [comment]
Libram swapping is apparently a thing but I can't confirm whether or not it is supposed to work in the way written above. 

I can confirm it doesn't work as written above. Here's some reading materials that discuss libram switching.

https://www.wowhead.com/forums&topic=114916

http://forum.warmane.com/showthread.php?t=320438

https://www.wowhead.com/item=50455/libram-of-three-truths

**Comment by UltraNix** [comment]
https://www.mmo-champion.com/threads/669987-3-2-2-Question?p=6735211&viewfull=1#post6735211
https://www.mmo-champion.com/threads/668034-Sigil?p=6694453&viewfull=1#post6694453
https://www.mmo-champion.com/threads/669955-Idol-Changes-Feral-DPS?p=6734702&viewfull=1#post6734702
You cannot get two proc from two different sigils/totems/relics/idols. It's Blizzlike.
