### ISSUE TITLE
Feature: change acore_world sql itemextendedcost_dbc can see the require item just like change itemExtendedCost.dbc

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#15310]
### Describe your feature request or suggestion in detail

When add npc_vendor item for sell, need change  itemExtendedCost.dbc, if only change sql itemextendedcost_dbc will not see the require item. if can change code, so just change database itemextendedcost_dbc also can see the item list?

**Comment by heyitsbench** [comment]
If you're asking to be able to see the changes to `itemextendedcost_dbc` without changing the .dbc file, that can't be done without modifying the client (afaik), which is not something AC can really do.

**Comment by kissingers** [comment]
> If you're asking to be able to see the changes to `itemextendedcost_dbc` without changing the .dbc file, that can't be done without modifying the client (afaik), which is not something AC can really do.

I see, that limited by client. close it. thanks!
