### ISSUE TITLE
[PVE/RAID][SPELL][AURA][MOB][ICCMOB] Lady Deathwhisper -  Cult Adherent Empowered

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1532]
##### SMALL DESCRIPTION:
 Lady Deathwhisper add  Adherent Empowered

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Lady Deathwhisper add Cult Adherent ( http://www.wowhead.com/npc=37949/cult-adherent ) when Empowered  ( http://www.wowhead.com/spell=70901/dark-empowerment ) should not be interruptable when casts by any spell 

##### CURRENT BEHAVIOUR:

The Cult Adherent spell when Empowered are interruptable by any silence 

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go inside Icc 25 h and start the fight with The Lady Deathwisper after u've cleaned all the room
2. wait until the mobs spawn 
3. try to silence the Cult Adherent Empowered 

##### EXTRA NOTES:

High Prio 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by Nefertumm** [comment]
Hmm maybe this issue is invalid, according to wowwiki:

> Buffed Adherents become "Empowered Adherents", adding an uninterruptible AOE spell to their abilities

So the only spell that can't be interruptable is [Deathchill Blast](https://www.wowhead.com/spell=70906/deathchill-blast)
