### ISSUE TITLE
how to give the tank bonus at random 5H 

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#15326]
### Describe your feature request or suggestion in detail

![F989B5D8CB437842A488363ED13C7C25](https://user-images.githubusercontent.com/96576214/224463642-f2e73a85-a41c-421b-bd8e-1ed3b0f34b4a.png)

how to give the tank bonus at random 5H 
please see the pictrue,
there is a little bag at the tank,
is it in 335 client ?
how do i start using it and change the bonus?
thanks very much

**Comment by Kitzunu** [comment]
Not the place to ask questions
