### ISSUE TITLE
[Server]World server crash on exit by guild bank

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#15332]
### Current Behaviour

https://gist.github.com/bgcfb/68e8f442594fb43fa06f045e85d5106f

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

shutdown or restart server after some hours 

### AC rev. hash/commit

[#7413727](https://github.com/azerothcore/azerothcore-wotlk/commit/74137279204bfef05e2e0044210e61b030b12b76)

### Operating system

Windows 10 x64

**Comment by acidmanifesto** [comment]
Same thing as the other report. We are not having this issue of existing the guild bank.
872125e3793e is not a known revision in azerothcore as shown in your gist and is not related to the hash you posted in your issue.
![image](https://user-images.githubusercontent.com/16887899/224500671-994ce90e-5ed1-4ed2-9f6f-9200fde7adba.png)
Undo whatever modificaitons you have made and try again. If not you are welcome to come to the discord to talk to someone in the custom channel for assistance with your custom core.
