### ISSUE TITLE
[ICCBOSS][MOBS] Lady Deathwisper second phase - Adds

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1533]
##### SMALL DESCRIPTION:
During the second phase of the Boss of Icc: 
The Lady Deathwisper ( https://www.wowhead.com/npc=36855/lady-deathwhisper  )   adds that spawn 
( https://www.wowhead.com/npc=37949/cult-adherent  -https://www.wowhead.com/npc=37890/cult-fanatic ) during the second phase  after used the spell  Dark Martyrdom 
( https://www.wowhead.com/spell=70903/dark-martyrdom#used-by-npc ADHERENT )
( https://www.wowhead.com/spell=71236/dark-martyrdom FANATIC )  
don't spawn the adds that should appear in their replacement 
( https://www.wowhead.com/npc=38010/reanimated-adherent - https://www.wowhead.com/npc=38009/reanimated-fanatic ) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After casting the spell Dark Martyrdom the Add should explode and spawn the Reanimated - adherent and the Rehanimeted fanatic . 

##### CURRENT BEHAVIOUR:
During the First Phase this adds ( THE SAME ADDS)  works but during the second phase when the Lady Deathwhisper have no more the mana shield  this adds don't works as intended 

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go Inside Icc any difficulty ( 10n/h-25n/h) and after have cleaned all the room of the Lady Deathwhisperstart the fight  

2. see that in the first phase this adds works correctly 

3. see that in the second phase this adds explodes but don't spawn anything 

##### EXTRA NOTES:
THIS SIMPLIFY A LOT THE FIGHT , IN THE SECOND PHASE THE ADD CAN JUST BE IGNORED BY THE DPS AND A SECOND TANK CAN JUST TAKE THEM FAR FROM THE RAID AND LET THEM EXPLODE 

HIGH PRIO !

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by Nefertumm** [comment]
During the second phase, Lady's adds shouldn't cast Dark Martyrdom.

**Comment by Heisenberg520** [comment]
Hey, hi man , why u say that ? The Adds are the SAME that spawn in the first phase , why the should not use dark martyrdom if is a spell of the mobs ? I don’t understand , they should explode buu spawn the other mobs, and for that reason u have to do dps on them
