### ISSUE TITLE
[Server]World server crash by AchievementMgr SQLQuery

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#15331]
### Current Behaviour

https://gist.github.com/bgcfb/7401877163b0056e67b571578bcbe517

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

[#7413727](https://github.com/azerothcore/azerothcore-wotlk/commit/74137279204bfef05e2e0044210e61b030b12b76)

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
The code looks okay here.

**Comment by bgcfb** [comment]
> The code looks okay here.

Yes,Maybe it is a DB error?

**Comment by UltraNix** [comment]
I don't know.

**Comment by acidmanifesto** [comment]
> > The code looks okay here.
> 
> Yes,Maybe it is a DB error?

what did you modify in the core? i am not finding this revision in your git history.
![image](https://user-images.githubusercontent.com/16887899/224495946-3ed182b6-0cb5-4ba7-8603-1989aaadd0c2.png)

**Comment by bgcfb** [comment]
> > > The code looks okay here.
> > 
> > 
> > Yes,Maybe it is a DB error?
> 
> what did you modify in the core? i am not finding this revision in your git history. ![image](https://user-images.githubusercontent.com/16887899/224495946-3ed182b6-0cb5-4ba7-8603-1989aaadd0c2.png)

It's my fork code.did not modify server core but some instance fix

**Comment by acidmanifesto** [comment]
> did not modify server core but some instance fix

That's what modifing the core is...

**Comment by bgcfb** [comment]
> > did not modify server core but some instance fix
> 
> That's what modifing the core is...

......I think I just modified instance scripts is not affect this crash

**Comment by acidmanifesto** [comment]
> ......I think I just modified instance scripts is not affect this crash

Regardless if you "THINK" you modified the core or not, and then also "Thinking" the modification is not the results of the core modifications you have done, we are not having this issues with our end. You are welcome to ask for help in the Custom Channel in our discord. but as of right now, that revision is not in our git history and we can not help with custom cores outside of what we provide as stock.

**Comment by bgcfb** [comment]
I am not running a stock azerothcore server because something must be modify for bug players and localization
The  issue is also exist in stock
I just report it for help master code, fix it or not fix it is your choice
