### ISSUE TITLE
Visual-Bug command .cheat god (low priority)

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1534]
DESCRIPTION:

the command.cheat god must be allowed to the gm not to receive damages

EXPECTED BLIZZLIKE BEHAVIOUR:

-

CURRENT BEHAVIOUR:

For example, the marrowgar bone spikes bring the life of the GM up to 1 without killing it

STEPS TO REPRODUCE THE PROBLEM:

.cheat god

go to marrowgar in 2 player and wait that he cast bone spike

![bone spike](https://user-images.githubusercontent.com/22867608/53511272-58d50c80-3ac0-11e9-828f-987c82be7158.png)

BRANCH(ES):
master

AC HASH/COMMIT:
commit: [15e4d2e](https://github.com/azerothcore/azerothcore-wotlk/commit/15e4d2e21f68a019b3c753831ffcbf5a29033272)

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by JamesGent** [comment]
![Desktop 28-11-2020 16-51-05-728](https://user-images.githubusercontent.com/61194190/100521165-ee239a00-3199-11eb-8a12-842281455849.png)

Can confirm cheat god sometimes still takes damage and goes to 1 but never dies.
