### ISSUE TITLE
Earthmender Wilda / quest: Escape from coilskar

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#15367]
CC report https://github.com/chromiecraft/chromiecraft/issues/5148

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

This quest is not always repeatable. She spawns underwater once someone completes it. Server reset will fix it.
![image](https://user-images.githubusercontent.com/68164076/224567427-bfc054a2-1a5e-484c-92cc-38d00eac4a23.png)
She will surface and help you attack. But you cannot accept the quest while she is underwater.

When you accept the quest she will tread water for a brief moment and will despawn and fail the quest.

On my local, the bubble spanws for a second but the lightning "pops" it when I get into range. This might be just visual or my client. But she stays in the correct position.
![image](https://user-images.githubusercontent.com/68164076/224571271-8fb0200b-5bfc-443e-bfb7-160bdcbef820.png)
![image](https://user-images.githubusercontent.com/68164076/224571298-e321914a-b80b-4361-b00c-f604a11b5561.png)
![image](https://user-images.githubusercontent.com/68164076/224571366-8ae85249-b9c1-4ab1-8183-d5c486480c26.png)

Once the keeper is killed and she's released, she will "Swim" down to her location. Again visual, but it kind of ruins the RP experiance.
![image](https://user-images.githubusercontent.com/68164076/224571490-052dd648-8427-4338-bf1a-7a70b63f39d3.png)

From there everything operates just fine if done properly.
Going to do it again she was spawned in the water
![image](https://user-images.githubusercontent.com/68164076/224573699-463d82c0-718d-47c2-8402-d051bccc376f.png)

Trying to check and see if the retail bug was present, I bugged it further by going and checking on the keeper's spawn. I went too far away and failed the quest, however the elementals still followed her back to her spawn point, and the proceeded to bug out all the surrounding mobs
![image](https://user-images.githubusercontent.com/68164076/224573024-31659920-a2eb-41af-96a4-8b0b3248cf0a.png)
![image](https://user-images.githubusercontent.com/68164076/224573049-e842bd17-a319-4ed8-85c9-dc8a1c97fca7.png)
However, she did respawn properly this time. 
![image](https://user-images.githubusercontent.com/68164076/224573089-a7fcf41a-c08b-4832-84a5-f074fb09f509.png)

Once the keeper respawns she killed the elementals.

### Expected Blizzlike Behaviour

Initially this works fine, it just occasionally can't be repeated. Her re-spawning is broken

Side note: Apparently there was a TBC classic bug. The escort takes longer than the respawn for the keeper, so someone killing the keeper again during the escort would freeze the NPC. https://www.wowhead.com/tbc/quest=10451/escape-from-coilskar-cistern#comments:id=5218639 I was unable to test this I just bugged it further as decribed above.

### Source

https://www.wowhead.com/npc=21027/earthmender-wilda#comments
https://youtu.be/CdUORA8ABGI

### Steps to reproduce the problem

1. .go c 25118 (be at least level 68)
2. Kill the keeper
3. Watch Earthmender Wilda swim down and thank you
4. Accept the quest to escort
5. Complete it
6. Abandon it and see where she spawns.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03d47897ece3e0a615aac05222d9fbd98b33717d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Stump876** [comment]
I think I figured it out, But I'm out of time and can't continue playing around with it. 

Kill the Keeper before Earthmender Wilda spawns. When then when Earthmender Wilda does spawn, aggroing mobs will drop her right into the water. 
![image](https://user-images.githubusercontent.com/68164076/224578208-5dffefaa-f00d-4ce9-8c27-94832714a831.png)
![image](https://user-images.githubusercontent.com/68164076/224578221-da06777f-197a-4f06-9c5f-4284d43d3f55.png)

Then killing the keeper with mobs aggrod will bug her out in the water.  
![image](https://user-images.githubusercontent.com/68164076/224578273-899fd333-3f8b-4abd-9f5c-c3ff43c101e1.png)
![image](https://user-images.githubusercontent.com/68164076/224578298-e6029199-2cbe-40f4-a70c-52a658352978.png)

**Comment by Gultask** [comment]
Setting her to passive on spawn fixes the issue. And I think I managed to make the respawn script play consistently.
The problem with the swimming in the air, however, I can't fix. If you `.list aura` her, you'll notice that she still has a bubble effect on her, but it isn't showing.

I don't know what could be triggering the despawn, but moving some scripts around seemed to work for me.
