### ISSUE TITLE
[quest] kodo roundup 

### ISSUE THREAD

**Issue by zato90** [azerothcore/azerothcore-wotlk#1536]
##### SMALL DESCRIPTION:
after bringing the kodo to the field does not add the kodo to complete the quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
after using "kodo kombobulator" on a kodo, it must be brought to Scrabblescrew 's camp (60.9,61.9 of Desolace). all must be done until you bring 5 Kodos.

##### CURRENT BEHAVIOUR:
after bringing the kodo to Scrabblescrew 's camp (60.9,61.9 of Desolace), does not add the kodo to complete the quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 5561
2. go to (55,62 of Desolace)
3. use "kodo kombobulator" on a kodo
4. bring it back to Scrabblescrew 's camp (60.9,61.9 of Desolace)
##### BRANCH(ES):

staging

##### AC HASH/COMMIT:

commit 987095e

##### OPERATING SYSTEM:
Linux

**Comment by Seebaby** [comment]
So with me on the server the Quest works super could not detect any problems.

You also have to address the Kodo who you are in the camp then he counts first that tells him the Npc but also that they should examine him.


BRANCH(ES): master

AC HASH/COMMIT: AzerothCore rev. 5348d9cbe590 2019-03-03 16:33:17 +0100 (master branch) (Win64, Release)

![wowscrnshot_030619_151330](https://user-images.githubusercontent.com/179698/53887518-be764b00-4022-11e9-90f6-40443b5bb7f0.jpg)

**Comment by poszer** [comment]
The quest is working and can be completed.
When returning them, get them to Smeed. Once he talks, then speak with your tamed Kodo to dismiss it and then go off for the next one. :smiley:
