### ISSUE TITLE
[ICCMOB][PVE][SPELL] Lady Deathwhisper- Second Phase "Dark Martyrdom"

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1538]
##### SMALL DESCRIPTION:
During the second phase of the Boss of Icc:
The Lady Deathwisper ( https://www.wowhead.com/npc=36855/lady-deathwhisper ) adds that spawn
( https://www.wowhead.com/npc=37949/cult-adherent -https://www.wowhead.com/npc=37890/cult-fanatic ) during the second phase should not use the spell Dark Martyrdom
( https://www.wowhead.com/spell=70903/dark-martyrdom#used-by-npc ADHERENT )
( https://www.wowhead.com/spell=71236/dark-martyrdom FANATIC )

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The Lady Deathwisper ( https://www.wowhead.com/npc=36855/lady-deathwhisper ) adds that spawn
( https://www.wowhead.com/npc=37949/cult-adherent -https://www.wowhead.com/npc=37890/cult-fanatic ) during the second phase should not use the spell Dark Martyrdom
( https://www.wowhead.com/spell=70903/dark-martyrdom#used-by-npc ADHERENT )
( https://www.wowhead.com/spell=71236/dark-martyrdom FANATIC )

Tankspot Offy raid - same behaviour 10h and 25 h  https://youtu.be/W64bCmigL1Q 

##### CURRENT BEHAVIOUR:
During the First Phase this adds ( THE SAME ADDS) works but during the second phase when the Lady Deathwhisper have no more the mana shield this adds don't works as intended

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go Inside Icc  ( 10h-25h) and after have cleaned all the room of the Lady Deathwhisper start the fight
2. see that in the first phase this adds works correctly and use the Dark Martyrdom how should be 
3. see that in the second phase this adds use that spell the Dark Martyrdom that they should not use 

##### EXTRA NOTES:
HIGH PRIO !

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by Nefertumm** [comment]
Stop opening this "issue". It's not the normal behaviour of the boss.

**Comment by Heisenberg520** [comment]
Man read the repart, on our server the adds during the second phase
explodes and u sayd dont have to cast Martyrtom , is a different report u
dont have even read ti D: i’ve report a different things

Il giorno gio 28 feb 2019 alle 20:26 Nefertumm <notifications@github.com>
ha scritto:

**Comment by Heisenberg520** [comment]
Before i’ve report that explodes and dont spawn adds , but Watching tour
report i’ve understand that dont have to spawn nothing , but they still
explode and dont have to explode

Il giorno gio 28 feb 2019 alle 20:28 Massimiliano Lo Bello <
massimiliano.lobe@gmail.com> ha scritto:

**Comment by Nefertumm** [comment]
My apologies. I'll test it when i have time :)

**Comment by Heisenberg520** [comment]
On Shin Test server , i'm a tester

**Comment by Nefertumm** [comment]
Related #761

**Comment by Nefertumm** [comment]
Our Lady is a complete mess, i'll work on it.

**Comment by comix1988** [comment]
Me and Heisenberg520 are testing it @Nefertumm
