### ISSUE TITLE
Core/Loot: Can't get item (entry 33470) from creature (entry 31691)

### ISSUE THREAD

**Issue by chendh123** [azerothcore/azerothcore-wotlk#1539]
##### SMALL DESCRIPTION: Can't get item (entry 33470) from creature (entry 31691).

lootid 31691
![image](https://user-images.githubusercontent.com/15760697/53565994-f8b09a00-3b95-11e9-859c-d778c1ecd9b7.png)
![image](https://user-images.githubusercontent.com/15760697/53566043-1ed63a00-3b96-11e9-891d-b30b8b954bae.png)

From confing:
```.ini
Rate.Drop.Item.Poor             = 1
Rate.Drop.Item.Normal           = 2
Rate.Drop.Item.Uncommon         = 2
Rate.Drop.Item.Rare             = 2
Rate.Drop.Item.Epic             = 2
Rate.Drop.Item.Legendary        = 2
Rate.Drop.Item.Artifact         = 2
Rate.Drop.Item.Referenced       = 2
Rate.Drop.Money                 = 2
```
```
#
#    Rate.Drop.Item.ReferencedAmount
#        Description: Multiplier for referenced loot amount.
#        Default:     1

Rate.Drop.Item.ReferencedAmount = 2
```

Why can't get item 33470, but get two 43852?

**Comment by chendh123** [comment]
creature_loot_template
Entry	Item	Reference	Chance	QuestRequired	LootMode	GroupId	MinCount	MaxCount	Comment
31691	26041	26041	100	0	1	0	1	1	

reference_loot_template
Entry	Item	Reference	Chance	QuestRequired	LootMode	GroupId	MinCount	MaxCount	Comment
26041	33470	0	100	0	1	0	1	7	
35063	43852	0	70	0	1	1	1	1	
35063	33435	0	0	0	1	1	1	1

**Comment by poszer** [comment]
@chendh123 You mean, you can't get Frostweave Cloth as drop from creature Faceless Lurker in Icecrown ?
https://wotlk.evowow.com/?item=33470
https://wotlk.evowow.com/?npc=31691#drops

**Comment by chendh123** [comment]
@poszer  yes.

**Comment by poszer** [comment]
> @poszer yes.

Nice catch. Will post fix soon :smiley:

**Comment by FrancescoBorzi** [comment]
@chendh123 can you please test the PR from @poszer that solves this issue?

The PR is: https://github.com/azerothcore/azerothcore-wotlk/pull/1583

You can find this useful: http://www.azerothcore.org/wiki/How-to-test-DB-only-changes

**Comment by chendh123** [comment]
Why is it not effective to use two references?
What's wrong with the original configuration?
creature_loot_template
![image](https://user-images.githubusercontent.com/15760697/54531969-9216e300-49c1-11e9-98ec-687dce533aac.png)
reference_loot_template
![image](https://user-images.githubusercontent.com/15760697/54531995-a4911c80-49c1-11e9-8f94-fc5a4ff88019.png)

**Comment by chendh123** [comment]
Thanks.  @Stoabrogga
