### ISSUE TITLE
Instance/Ulduar: Winter Jormungars pop out all at once.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15401]
### Current Behaviour

The [Winter Jormungars](https://www.wowhead.com/wotlk/npc=34137) all pop out at once when approaching their snow mound.

[Here is a video of this happening](https://youtu.be/AiPEJpUWV5U).

### Expected Blizzlike Behaviour

They should slowly pop out one after another with a few seconds delay between each.

### Source

[Retail Wow (Well after WotLK)](https://youtu.be/RbaCgkZRY9s?t=1591) as well as Wrath Classic.

### Steps to reproduce the problem

1. Enter Ulduar and clear your way up to Hodir's entryway.
2. Approach a snow mound.
3. Observe what some might describe as a bad time.

### AC rev. hash/commit

a1c644fd3971085d25d16700384110feda6bfdab

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
Pretty sure the range on these snow mounds is too wide as well, but that's a separate issue.

**Comment by avarishd** [comment]
https://youtu.be/OEw2JFRFrwI?t=3544 wotlk classic
