### ISSUE TITLE
Instance/Ulduar: Kologarn keeps falling after he dies.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15400]
### Current Behaviour

When [Kologarn](https://www.wowhead.com/wotlk/npc=32930) is killed and becomes too far from player view, he obviously cannot be seen by the player. When a player returns to Kologarn and he becomes visible once again, he is shown upright but immediately falls back to his corpse state.

[Here is a video of this happening](https://www.youtube.com/watch?v=7BhMaiNbgdc).

### Expected Blizzlike Behaviour

Kologarn should not pop back up only to fall again, instead he should stay down. Like the coward he is.

### Source

Assumption.

### Steps to reproduce the problem

1. Enter Ulduar.
2. Defeat Flame Leviathan and XT-002 Deconstructor.
3. Make your way to Kologarn.
4. Kill the mister.
5. Leave.
6. Come back.
7. Observe.

### AC rev. hash/commit

a1c644fd3971085d25d16700384110feda6bfdab

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
Upon further deliberation (and stepping out of some tunnel vision), I have come to the conclusion that Kologarn should actually make a bridge with his corpse upon his demise. He does not do that.

**Comment by heyitsbench** [comment]
Interestingly, my character still collides with and can walk on top of the bridge, but it is very much not there visually.

**Comment by Kitzunu** [comment]
iirc the bridge is actually a gameobject that spawns on death. Just need to make sure kologarn stays afloat on death

**Comment by Kitzunu** [comment]
But the entire fight needs a rewrite. A lot of stuff missing

**Comment by yukijean** [comment]
In addition, Cologne's eyes will not chase the player in most cases, but will only be put in place.

**Comment by heyitsbench** [comment]
> In addition, Cologne's eyes will not chase the player in most cases, but will only be put in place.

Separate issue, should make a new report for it if one doesn't already exist.

**Comment by yukijean** [comment]
@Kitzunu @heyitsbench I solved the problem of eyeliner today, but I don't know how to upload the modified script --

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/how-to-create-a-pr

**Comment by yukijean** [comment]
@Kitzunu The webpage cannot be opened~~~Can I send you the CPP file via email and you can help me upload it

**Comment by heyitsbench** [comment]
Adding a `me->SetDisableGravity(true);` somewhere in this function:
https://github.com/azerothcore/azerothcore-wotlk/blob/54ab8dafc25f317459dac7757e33ea80b7b2dcf1/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp#L297-L328
does resolve the issue, but something about that solution feels...off. Also I have discovered he is supposed to have the uninteractible flag set on death as well, something which doesn't happen on AC.
