### ISSUE TITLE
Add GM as friend but that Friend Always Offline in Friend List

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1540]
##### SMALL DESCRIPTION:

When adding another player of gmlevel 2 or 3 to the friend list, it adds ok but the status is always grey saying "unknown" even when that player is online. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Players of gmlevel 2 or 3 should also have their online/offline status displayed correctly in Friend List.

##### CURRENT BEHAVIOUR:

When adding another player of gmlevel 2 or 3 to the friend list, it adds ok but the status is always grey saying "unknown" even when that player is online. 

When the added player is of gmlevel 0 or 1, then everything works as normal and their status appears just fine in the Friend List.

FYI - these are the configs used in worldserver.conf

GM.AllowFriend = 1
GM.AllowInvite = 1

Also clearing client WTF and cache did not help.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create 1st account of gmlevel 0 or 1. Create character called test1
2.  Create 2nd account of gmlevel 3 or 2. Create character called test2
3.  Bring both characters online.
4.  Add test2 to test1's friend list.
5.  You will see in test1's Friend List that test2 is ALWAYS OFFLINE.
6.  Now add test1 to test2's Friend List.
7.  You will see the online/offline status of test1 is displayed correctly.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5348d9c

##### OPERATING SYSTEM:

Win 7/10/Svr 2008 R2/Svr 2016

##### MODULES:

Tested with and without any modules, same result.

##### OTHER CUSTOMIZATIONS:

No, tested with fresh db without customizations.

**Comment by gtao725** [comment]
Read the following from: https://wow.gamepedia.com/GM_Island

"
Notes
Before patch 1.8, players could add GMs to their friends list, and they would be seen to be located at GM Island. However, since patch 1.8, it is no longer possible to add a GM to friends lists.
Against popular belief, there is very little on the island. A small doghouse, a rowboat and a dock that connects to it, a single building, a few trees and a graveyard.
For a brief while in the EU servers, during patch 2.1.1, players could add GMs to their friend list. This was due to a malfunction in their title-system. After this was fixed, the GM stayed on your friend list. You could see them log in every hour at least and you could see their level and where they were.
"
Could someone pls confirm if this is the case by design? GM/Admin level chars cannot be seen on Friend List by other players (including other GM/Admin) ?

**Comment by poszer** [comment]
I think you can do that just while adding ( SEC_MODERATOR) which is rank 1.

**Comment by gtao725** [comment]
> I think you can do that just while adding ( SEC_MODERATOR) which is rank 1.

Thx @poszer but how do you mean? I don't quite understand what you mean, sorry I am not too familiar with the definition of SEC_MODERATOR and what you can do with it. All I want is to be able to see other GMs (gmlevel 2 and gmlevel 3) on the Friend List, if it is not possible by design then I will close this issue.

**Comment by poszer** [comment]
> > I think you can do that just while adding ( SEC_MODERATOR) which is rank 1.
> 
> Thx @poszer but how do you mean? I don't quite understand what you mean, sorry I am not too familiar with the definition of SEC_MODERATOR and what you can do with it. All I want is to be able to see other GMs (gmlevel 2 and gmlevel 3) on the Friend List, if it is not possible by design then I will close this issue.

You have it in config too allow or no Gm's in friend list  : 

#
#    GM.AllowFriend
#        Description: Allow players to add GM characters to their friends list.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

GM.AllowFriend = 0

But showing them online/offline that is not blizzlike. So, i'll close this
