### ISSUE TITLE
Two BUGs of IcecrownCitadel

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15409]
### Current Behaviour

1: The ice dragon monster in front of IcecrownCitadel's third brother didn't fly down in the normal way, but flashed directly below, which felt like the loss of the model, but this problem was not very serious
2: The bug of Sindagoza is very serious. When the small monster in front is handled, Sindagoza will be automatically activated and the whole group will be killed after landing. There is no way.

### Expected Blizzlike Behaviour

1：The ice dragon monster should slowly fly down and enter the battle
2：After dealing with the small monster in front of Sindagosa, it is still flying in the sky. When it approaches, it will enter the battle, and will not be killed by the whole group. The following normal fighting process.

### Steps to reproduce the problem

There is no way to solve the two BUGs. I don't know whether it is caused by the model problem or other problems. Sindagosa can only be resurrected once after the death of the whole group

### AC rev. hash/commit

AZEROTHCORE REV.4134C2DADA78+ 2023-03-14 06:35:16 +0000（主分支）（WIN64.RELWITHDEBINFO，静态）

### Operating system

window server 2019

**Comment by Kitzunu** [comment]
One bug per report.
