### ISSUE TITLE
Quest issues before "Battle for the Undercity"

### ISSUE THREAD

**Issue by ide1234000** [azerothcore/azerothcore-wotlk#1541]
##### SMALL DESCRIPTION:

Before do quest "Battle for the Undercity" start, Alliance and Horde is missing follow quest and portal to th Undercity

You can see these on my test Video: https://youtu.be/uNpvKjCvonw
##### EXPECTED BLIZZLIKE BEHAVIOUR:

For Alliance: After the quest "The Killing Time"(13371) starts, there should be appear a portal to outside the Undersity sewer gate.

For Horde: It should have a follow quest "A Life Without Regretafter"(13266) and a portal when the "Herald of War"(13257) was done.

##### CURRENT BEHAVIOUR:

Alliance: 
1. When the quest "The Killing Time"(13371) starts, there is no portal to the Undercity.
2. I can't see the relevant NPC in specific place (the GM character can see them after re-login, the normal character can't see them)

Horde: 
1. After the quest "Herald of War"(13257) starts, Perhaps missing a portal to Orgrimmar.
2. When quest "Herald of War"(13257) is completed，No follow-up quest and missing a portal to the Undercity

##### STEPS TO REPRODUCE THE PROBLEM:

1. For Alliance:  .add quest 13370 and start the quest.
2. For Horde: .add quest 13257 and start it.
3. Or you can see the video: https://youtu.be/uNpvKjCvonw

##### EXTRA NOTES:

None
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9643ccd

##### OPERATING SYSTEM:

Ubuntu 16.04 64

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

None

**Comment by BarbzYHOOL** [comment]
Follow up of https://github.com/azerothcore/azerothcore-wotlk/pull/1479

**Comment by Nefertumm** [comment]
Sorry about that, miss click. Not related to my pr, its related about the whole quest chain.

**Comment by ide1234000** [comment]
Great job for your PR! Hope these quest chain can fix in the future.

**Comment by gtao725** [comment]
Can the broken quests in the chain also be ported from Dalaran WoW?

**Comment by Nefertumm** [comment]
Sure

**Comment by pklloveyou** [comment]
DELETE FROM `creature_queststarter` WHERE `quest` = "13266";
INSERT INTO `creature_queststarter` VALUES (31412, 13266);
INSERT INTO `creature_queststarter` VALUES (32363, 13266); -- NEW

DELETE FROM `spell_area` WHERE `spell` = "60815";
INSERT INTO `spell_area` VALUES (60815, 14, 13242, 13266, 0, 690, 2, 1, 74, 11);
INSERT INTO `spell_area` VALUES (60815, 14, 13347, 13370, 0, 1101, 2, 1, 74, 11);
INSERT INTO `spell_area` VALUES (60815, 85, 13371, 13377, 0, 0, 2, 1, 74, 11);
INSERT INTO `spell_area` VALUES (60815, 1497, 13371, 13377, 0, 0, 2, 1, 74, 11);
INSERT INTO `spell_area` VALUES (60815, 1637, 13242, 13266, 0, 690, 2, 1, 74, 11);
INSERT INTO `spell_area` VALUES (60815, 1637, 13347, 13370, 0, 1101, 2, 1, 74, 11);

**Comment by FrancescoBorzi** [comment]
@pklloveyou thanks, can you please open PR with that? We can provide assistance if needed

**Comment by pklloveyou** [comment]
I use online translation to communicate, communication difficulties

**Comment by ide1234000** [comment]
> ```sql
> DELETE FROM `creature_queststarter` WHERE `quest` = "13266";
> INSERT INTO `creature_queststarter` VALUES (31412, 13266);
> INSERT INTO `creature_queststarter` VALUES (32363, 13266); -- NEW
> 
> DELETE FROM `spell_area` WHERE `spell` = "60815";
> INSERT INTO `spell_area` VALUES (60815, 14, 13242, 13266, 0, 690, 2, 1, 74, 11);
> INSERT INTO `spell_area` VALUES (60815, 14, 13347, 13370, 0, 1101, 2, 1, 74, 11);
> INSERT INTO `spell_area` VALUES (60815, 85, 13371, 13377, 0, 0, 2, 1, 74, 11);
> INSERT INTO `spell_area` VALUES (60815, 1497, 13371, 13377, 0, 0, 2, 1, 74, 11);
> INSERT INTO `spell_area` VALUES (60815, 1637, 13242, 13266, 0, 690, 2, 1, 74, 11);
> INSERT INTO `spell_area` VALUES (60815, 1637, 13347, 13370, 0, 1101, 2, 1, 74, 11);
> ```

The quest "A Life Without Regretafter" is ok, but no portal appears.

**Comment by gtao725** [comment]
> > ```sql
> > DELETE FROM `creature_queststarter` WHERE `quest` = "13266";
> > INSERT INTO `creature_queststarter` VALUES (31412, 13266);
> > INSERT INTO `creature_queststarter` VALUES (32363, 13266); -- NEW
> > 
> > DELETE FROM `spell_area` WHERE `spell` = "60815";
> > INSERT INTO `spell_area` VALUES (60815, 14, 13242, 13266, 0, 690, 2, 1, 74, 11);
> > INSERT INTO `spell_area` VALUES (60815, 14, 13347, 13370, 0, 1101, 2, 1, 74, 11);
> > INSERT INTO `spell_area` VALUES (60815, 85, 13371, 13377, 0, 0, 2, 1, 74, 11);
> > INSERT INTO `spell_area` VALUES (60815, 1497, 13371, 13377, 0, 0, 2, 1, 74, 11);
> > INSERT INTO `spell_area` VALUES (60815, 1637, 13242, 13266, 0, 690, 2, 1, 74, 11);
> > INSERT INTO `spell_area` VALUES (60815, 1637, 13347, 13370, 0, 1101, 2, 1, 74, 11);
> > ```
> 
> The quest "A Life Without Regretafter" is ok, but no portal appears.

That seems to me like now the correct data is in the db but the script still needs to be added to link the quest chain together and generate the correct portals for both alliance and horde side.

**Comment by gtao725** [comment]
Also after applying the DB sql, the scene where Jaina walks out of the Stormwind Portal to warn Thrall still doesn't happen, the Stormwind Portal just stays there with an actionable click symbol but it does nothing.

**Comment by gtao725** [comment]
Also for the horde side of "Heralds of War" (Quest ID: 13257), As soon as the player accepts the quest a portal to Orgrimmar is supposed to open behind High Overlord Saurfang in Warsong Hold, right now there is no portal and players have to get to Orgrimmar on their own.

**Comment by Stoabrogga** [comment]
I'll look into this.
