### ISSUE TITLE
IcecrownCitadel

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15410]
### Current Behaviour

The bug of Sindagoza is very serious. When the small monster in front is handled, Sindagoza will be automatically activated and the whole group will be killed after landing. There is no way.

### Expected Blizzlike Behaviour

After dealing with the small monster in front of Sindagosa, it is still flying in the sky. When it approaches, it will enter the battle, and will not be killed by the whole group. The following normal fighting process.

### Steps to reproduce the problem

I don't know how to solve it. I used all kinds of methods after landing

### AC rev. hash/commit

AZEROTHCORE REV.4134C2DADA78+ 2023-03-14 06:35:16 +0000（主分支）（WIN64.RELWITHDEBINFO，静态）

### Operating system

window server 2019

**Comment by Nyeriah** [comment]
Sindragosa blasts the raid as she approaches the platform dealing lethal damage based on distance, thus players must move to the entrance in order to survive the damage

**Comment by yukijean** [comment]
@Nyeriah It is not possible to query what skill killed in the battle record

**Comment by yukijean** [comment]
@Tony931023 Is it the whole group's second kill after the completion of Sindagoza breath?

**Comment by Tony931023** [comment]
> Is it the whole group's second kill after the completion of Sindagoza breath?

every time the players die sindragosa returns to draw the breath

**Comment by yukijean** [comment]
@Tony931023 Have you ever seen the whole regiment die after Sindagosa fell to the ground?

**Comment by Tony931023** [comment]
> @Tony931023 Have you ever seen the whole regiment die after Sindagosa fell to the ground?

I think I don't explain myself well or I don't understand [I don't speak English], by which I mean that when you are in the encounter with Sindragosa and the entire raid wipes, the event does not restart with Sindra already on the floor, but Sindra appears flying again and kill the whole raid

**Comment by yukijean** [comment]
@Tony931023 My English is not very good. I understand what you mean. We met the same situation, that is, Cindagosa will directly second the whole group.

**Comment by yukijean** [comment]
@Nyeriah Can I fix this? Thank you

**Comment by yukijean** [comment]
@Nyeriah Can I fix this? Thank you

**Comment by Nyeriah** [comment]
> @Nyeriah Can I fix this? Thank you

You may fix it, sure

**Comment by yukijean** [comment]
@Nyeriah Sorry, I have the wrong number. Can you fix it here? The experience of Sindagoza is very bad, and the whole group will die once or more

**Comment by yukijean** [comment]
@Nyeriah Hello, are you still there? Can you help me out?

**Comment by speedrunz** [comment]
@Kitzunu  I can confirm that this is happening. Players still get hit with Sindragosa's ice blasts in its first landing before the fight starts. Before, this can be avoided by hiding behind inside the room with LoS, but now players are entirely wiped.

**Comment by yukijean** [comment]
Hello, have you ever tested Algalon? Will it refresh after the group is destroyed? Cindagosa, will the whole group be killed in seconds? thank you




---Original---
From: "Julio A. Leyva ***@***.***&gt;
Date: Thu, Mar 16, 2023 20:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [azerothcore/azerothcore-wotlk] IcecrownCitadel (Issue #15410)




  
@Tony931023 Have you ever seen the whole regiment die after Sindagosa fell to the ground?
  
I think I don't explain myself well or I don't understand [I don't speak English], by which I mean that when you are in the encounter with Sindragosa and the entire raid wipes, the event does not restart with Sindra already on the floor, but Sindra appears flying again and kill the whole raid
