### ISSUE TITLE
Random dungeon （LFG）will save the player's copy progress BUG

### ISSUE THREAD

**Issue by a3396616601** [azerothcore/azerothcore-wotlk#1542]
Sorry, my English is really not good, please forgive me!
description:
After the player finishes the random dungeon, the copy progress will not be saved.
This problem does not exist in (sunwellcore). Make sure everything is normal.
But in az I used the core of April 1, 2017 and tested this problem in the latest core!
Can this be solved? Or give a little solution! I am a C++ self-learning programmer with poor technology! Thank you!
This question is really annoying. .

**Comment by Maurowin** [comment]
Hello, can you follow this http://www.azerothcore.org/wiki/Contribute#how-to-open-an-issue to open a issue.
