### ISSUE TITLE
Cannot Select Flight Path End Nodes

### ISSUE THREAD

**Issue by LeFroid** [azerothcore/azerothcore-wotlk#15479]
### Current Behaviour

Certain flight paths are not selectable after being discovered, even when there is a valid path from the source flight master to the target flight master.

### Expected Blizzlike Behaviour

The end node should be selectable so the player can fly from the source to target nodes.

### Source

https://wow.allakhazam.com/wiki/Category:Flight_Points_%28WoW%29

### Steps to reproduce the problem

As Alliance player, for example:
1) Discover Ironforge, Menethil Harbor, Thelsamar, Refugee Pointe, and Southshore flight paths.
2) Go to Ironforge Flight Master and try to fly to Refugee Pointe or Southshore (should work, not able to select currently)
3) Go from Ironforge to Menethil Harbor and try to fly to Refugee Pointe or Southshore (should work, not able to select currently)

### Extra Notes

![image](https://user-images.githubusercontent.com/2191538/226191662-437e03a6-6357-49c9-be81-d812d7b7af16.png)
![image](https://user-images.githubusercontent.com/2191538/226191792-a7d4b96e-313f-4356-9909-08386065ddba.png)

### AC rev. hash/commit

f9ebf0d37ac81f994f0955ffae873409b82ff180

### Operating system

Linux x64

### Custom changes or Modules

- mod-ah-bot
- mod-eluna
- mod-progression-system
- mod-skip-dk-starting-area
- mod-solocraft
- mod-transmog
- mod-weekend-xp
- mod-zone-difficulty

**Comment by heyitsbench** [comment]
[Cannot](https://user-images.githubusercontent.com/38561765/226191972-26fee892-c035-458c-b67b-47cedc67b5b4.png) [reproduce.](https://user-images.githubusercontent.com/38561765/226192075-f9875f6c-bd15-42d7-9152-edc74c0c2036.png) Could be either a client or an addon issue.

**Comment by LeFroid** [comment]
After switching to a fresh client with no addons, it is working. Thanks for checking, I'll close this
