### ISSUE TITLE
Creatures with aura ID - 31261 Permanent Feign Death (Root) cannot aggro players

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#15484]
### Current Behaviour

Title

### Expected Blizzlike Behaviour

They should be able to aggro onto players. If they don't then it's because of a lack of unit_flags

### Steps to reproduce the problem

Apply: https://github.com/azerothcore/azerothcore-wotlk/pull/15482/files
`.go c id 20869`

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/684bb1793ddb6303b49e809a4d1d8e31bca3b862

### Operating system

Windows 10

**Comment by Gultask** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_generic.cpp#L1698

There are only 3 possible flags Feign Death auras can apply: UNIT_DYNFLAG_DEAD, UNIT_FLAG2_FEIGN_DEATH
and UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT. Some auras can apply only 2 flags

spell_gen_feign_death_all_flags applies all 3 flags
spell_gen_feign_death_no_dyn_flag applies no UNIT_DYNFLAG_DEAD (does not make the creature appear dead)
spell_gen_feign_death_no_prevent_emotes applies no UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT

**REACT_PASSIVE should be handled directly in scripts since not all creatures should be passive. Otherwise
creature will be not able to aggro or execute MoveInLineOfSight events. Removing may cause more issues
than already exists**

**Comment by UltraNix** [comment]
![image](https://user-images.githubusercontent.com/80540499/227730082-94fb0009-9ee0-4b9e-b2a6-84c4dc3f1ab1.png)
Works okay to me.

**Comment by Gultask** [comment]
Ah, sorry I ported from TC

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/15496
