### ISSUE TITLE
Icecrown Fortress found another bug

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15501]
### Current Behaviour

Deathbringer Saurfang activates the battle after completing the conversation with the NPC, but at this point, he will withdraw from the battle. Deathbringer Saurfang runs back into the door, and no matter how many times the conversation is completed, the BOSS will withdraw from the battle and run back into the door

### Expected Blizzlike Behaviour

Deathbringer Saurfang will complete the dialogue with the NPC and activate the battle. After the normal process is completed, the BOSS will continue inside the Icecrown Fortress

### Steps to reproduce the problem

Unable to resolve. If this BOSS is not cleared, you cannot enter the interior of Icecrown Fortress

### AC rev. hash/commit

AzerothCore rev. 29fba5fe38e9+ 2023-03-19 21:00:11 -0300 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

WINDOWS SERVER 2019

**Comment by Nyeriah** [comment]
This is also what happens when you don’t kill all of the required bosses

**Comment by yukijean** [comment]
@Nyeriah @Tony931023 Thank you for your reply. It's my question. Previously, when the third BOSS killed the BOSS with instructions, a bug would appear. If the third BOSS was killed normally, there would be no problem. I have closed this question
