### ISSUE TITLE
cant start docker container

### ISSUE THREAD

**Issue by rhu25** [azerothcore/azerothcore-wotlk#15506]
### Current Behaviour

./acore.sh docker start:app

it shows following error

`ranhu@Rans-MacBook-Pro azerothcore-wotlk % ./acore.sh docker start:app
NOTICE: file </Users/ranhu/Desktop/azerothcore-wotlk/conf/config.sh> not found, we use default configuration only.
Deno version check:
Version 1.26.0 is already installed

Running: docker compose --profile app up
[+] Running 1/0
⠿ Container azerothcore-wotlk-ac-database-1 Running 0.0s
Attaching to azerothcore-wotlk-ac-authserver-1, azerothcore-wotlk-ac-database-1, azerothcore-wotlk-ac-db-import-1, azerothcore-wotlk-ac-worldserver-1
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./env/dist/bin/dbimport": stat ./env/dist/bin/dbimport: no such file or directory: unknown
error: Uncaught (in promise) Error: Failed with error: 1, however,
it's not related to this Deno script directly. An error occurred within
the script called by the command itself
throw new Error(Failed with error: ${status.code}, however,                 ^     at Command.<anonymous> (file:///Users/ranhu/Desktop/azerothcore-wotlk/apps/docker/docker-cmd.ts:268:17)     at async Promise.all (index 0)     at async main (file:///Users/ranhu/Desktop/azerothcore-wotlk/apps/docker/docker-cmd.ts:324:7) ranhu@Rans-MacBook-Pro azerothcore-wotlk % git status On branch master Your branch is up to date with 'origin/master'.

### Expected Blizzlike Behaviour

no error

### Steps to reproduce the problem

1. ./acore.sh docker build
2. ./acore.sh docker client-data
3. ./acore.sh docker start:app

### AC rev. hash/commit

`ranhu@Rans-MacBook-Pro azerothcore-wotlk % ./acore.sh docker start:app
NOTICE: file </Users/ranhu/Desktop/azerothcore-wotlk/conf/config.sh> not found, we use default configuration only.
Deno version check:
Version 1.26.0 is already installed

Running: docker compose --profile app up
[+] Running 1/0
⠿ Container azerothcore-wotlk-ac-database-1 Running 0.0s
Attaching to azerothcore-wotlk-ac-authserver-1, azerothcore-wotlk-ac-database-1, azerothcore-wotlk-ac-db-import-1, azerothcore-wotlk-ac-worldserver-1
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./env/dist/bin/dbimport": stat ./env/dist/bin/dbimport: no such file or directory: unknown
error: Uncaught (in promise) Error: Failed with error: 1, however,
it's not related to this Deno script directly. An error occurred within
the script called by the command itself
throw new Error(Failed with error: ${status.code}, however,                 ^     at Command.<anonymous> (file:///Users/ranhu/Desktop/azerothcore-wotlk/apps/docker/docker-cmd.ts:268:17)     at async Promise.all (index 0)     at async main (file:///Users/ranhu/Desktop/azerothcore-wotlk/apps/docker/docker-cmd.ts:324:7) ranhu@Rans-MacBook-Pro azerothcore-wotlk % git status On branch master Your branch is up to date with 'origin/master'.

### Operating system

mac

**Comment by Kitzunu** [comment]
Looks like you use very outdated source

**Comment by rhu25** [comment]
@Kitzunu im using master branch, then which branch i should use?

**Comment by rhu25** [comment]
@Kitzunu i am on master branch and follow exactly steps from https://www.azerothcore.org/wiki/install-with-docker#clone-the-azerothcore-repository
