### ISSUE TITLE
Ulduar quest chain Ancient Gate of the Keepers

### ISSUE THREAD

**Issue by indigowowserver** [azerothcore/azerothcore-wotlk#15518]
### Current Behaviour

after testing raid on 25 and 10 for the quest to open the gate for Ancient Gate of the Keepers
this following item for quest does not drop in the chests 
1- thorims-sigil
https://www.wowhead.com/wotlk/quest=13610/thorims-sigil
2- Thorim's Sigil
https://www.wowhead.com/wotlk/quest=13610/thorims-sigil
3 -13821
https://www.wowhead.com/wotlk/quest=13821/heroic-freyas-sigil

best regards

### Expected Blizzlike Behaviour

its should drop in each boss chest so you can open the gate.

### Source

https://www.youtube.com/watch?v=uv1uEXyp95w

### Steps to reproduce the problem

do the quest line for last boss in ulduar

### AC rev. hash/commit

![server debug](https://user-images.githubusercontent.com/128375191/226464229-b68c2adf-7bb7-40d4-991c-f7bedc0db71c.png)

### Operating system

windows 10 x64

**Comment by avarishd** [comment]
rev. 9703900182d1b1331555fba778dc96f992da2e22
Could not reproduce for either 10 or 25.
<details>

![WoWScrnShot_032123_095437](https://user-images.githubusercontent.com/46330494/226548083-a8091483-f7c6-4840-aa81-716afa92b3d0.jpg)
![WoWScrnShot_032123_095709](https://user-images.githubusercontent.com/46330494/226548089-c2864c56-b166-439d-a983-7aa6632bab30.jpg)
![WoWScrnShot_032123_095742](https://user-images.githubusercontent.com/46330494/226548094-1267bb78-917a-41e3-9583-ab415f308161.jpg)
![WoWScrnShot_032123_100217](https://user-images.githubusercontent.com/46330494/226548102-e30da9cb-567e-4dbc-9956-00ec53b4a25c.jpg)
![WoWScrnShot_032123_100252](https://user-images.githubusercontent.com/46330494/226548325-efd57f7a-5c35-4eb1-9d29-d5a6e307783f.jpg)

https://user-images.githubusercontent.com/46330494/226548403-d49bc2f3-dc24-41a7-9f6c-478ab206107e.mp4

</details>

**Comment by indigowowserver** [comment]
thats great but on 25 it isnt working

**Comment by avarishd** [comment]
I tested 25 (in the comment) it worked the same way as 10m.

**Comment by indigowowserver** [comment]
i just tested . sorry for misunderstanding . only raid leader can loot the item . thank you next time i will try to test all roles
