### ISSUE TITLE
Outcast's Cache (entry=31800) and Unmarked Bag of Gems (entry=25419) items aren't grouped, therefore can be empty.

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#15537]
Original Issues: 
https://github.com/chromiecraft/chromiecraft/issues/4829
https://github.com/chromiecraft/chromiecraft/issues/4666

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

item=31800 Outcast's Cache and Unmarked Bag of Gems (entry=25419) loot bags can be empty, and give loot randomly instead of in a fixed way.
Items looted aren't grouped.

### Expected Blizzlike Behaviour

Bag should contain 1-2 healing potions, 1x random scroll and 1x belt or boots.

### Source

https://www.wowhead.com/wotlk/item=31800/outcasts-cache#comments
https://youtu.be/-M_wbi7PlBY?t=39
https://youtu.be/NbJPI0gXVMw?t=463

### Steps to reproduce the problem

`.add 31800 50`     or `.add 25419 50`
Behold randomized loot.
Also sometimes find bag empty.

### AC rev. hash/commit

7559dfc3cd0f

### Operating system

Ubuntu 20.04 - Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
https://github.com/chromiecraft/chromiecraft/issues/4666 Related?

**Comment by Zelfie** [comment]
Hey just to add to this. The initial post was about the outcast's cache, and mentioned Unmarked Bag of Gems, but it also affects the other items rewarded from the different levels of "Membership Benefits"
item=25424 Gem Stuffed Envelope
tem=25422 Bulging Sack of Gems
item=25423 Bag of Premium Gems

I don't have any sources to hand, but gems should be pooled in some way so it can't be depressingly empty.
