### ISSUE TITLE
Bug: Risen Ally infinite Ghoul explosions

### ISSUE THREAD

**Issue by Scortas** [azerothcore/azerothcore-wotlk#15538]
### Current Behaviour

When you use risen ally on an ally the most powerful ability it has can be infinitely spammed. The ability simply called explosion can be done multiple times.

### Expected Blizzlike Behaviour

Explosion ability is supposed to kill the ghoul upon usage. It has very high AoE damage and currently is pretty OP.

### Source

https://wotlkdb.com/?spell=47496

### Steps to reproduce the problem

1. Die in a group.
2. Get resurrected as a ghoul
3. Start spamming explosion

### AC rev. hash/commit

AC> AzerothCore rev. bda4394cee23 2023-03-09 16:30:49 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80032
Using CMake version: 3.22.1
Compiled on: Linux 5.19.0-35-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/user/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/user/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/user/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List enable modules:
- mod-TimeIsTime
- mod-account-achievements
- mod-ah-bot
- mod-autobalance
- mod-gain-honor-guard
- mod-individual-xp
- mod-instance-reset
- mod-npc-beastmaster
- mod-npc-enchanter
- mod-solo-lfg
- mod-solocraft
- mod-transmog

### Operating system

Ubuntu 22.04

### Custom changes or Modules

List enable modules:
- mod-TimeIsTime
- mod-account-achievements
- mod-ah-bot
- mod-autobalance
- mod-gain-honor-guard
- mod-individual-xp
- mod-instance-reset
- mod-npc-beastmaster
- mod-npc-enchanter
- mod-solo-lfg
- mod-solocraft
- mod-transmog

**Comment by avarishd** [comment]
duplciate of https://github.com/azerothcore/azerothcore-wotlk/issues/2605
