### ISSUE TITLE
Icecrown Fortress: The Bug of the Lich King

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15542]
### Current Behaviour

When the Lich King enters 10% of his blood, the frozen NPC disappears directly, causing the plot behind the Lich King to not be triggered, and for a period of time, the Lich King's terrain will recover and then disappear.

### Expected Blizzlike Behaviour

When the Lich King reaches 10%, the player dies, the NPC thaws, and then resurrects the player to watch the plot.

### Steps to reproduce the problem

Don't know how to solve it~

### AC rev. hash/commit

AzerothCore rev. 2f52fc9a85cd+ 2023-03-22 09:09:43 +0000 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

### Operating system

WINDOWS SERVER 2019

**Comment by q67732897** [comment]
Yes, I also encountered the same problem, I hope to repair it
This is a video demonstration：https://youtu.be/XNh4jblXpts

**Comment by Tony931023** [comment]
Exactly this is happening, and it is serious since it does not allow the event to be completed

@Nyeriah Please Help

**Comment by Tony931023** [comment]
@Nyeriah Thanks for the quick help, you're the best.
