### ISSUE TITLE
The Quest Completed text will not be translated from english to german

### ISSUE THREAD

**Issue by Seebaby** [azerothcore/azerothcore-wotlk#1554]
SMALL DESCRIPTION:

The quest is not translated correctly from English to German 
Quest name True translated
Details True Translated
Objectives Votes Oversees
CompletedText Is not translated although available in quest_template_locale

CURRENT BEHAVIOUR:

CompletedText Not translated

STEPS TO REPRODUCE THE PROBLEM:

Create Character
Accept Quest 
Finish Quest 
View CompletedText is not translated

EXTRA NOTES:

BRANCH(ES):
master

AC HASH/COMMIT:
AzerothCore rev. 5348d9cbe590 2019-03-03 16:33:17 +0100 (master branch) (Win64, Release)

OPERATING SYSTEM:
Win10

MODULES:
transmog

I hope I filled everything in correctly.

**Comment by pangolp** [comment]
Good evening, what search are you referring to? Any particular or all searches? I'm not quite clear.

**Comment by Seebaby** [comment]
The translation from English to German from the CompletedText table is not done.

Wow Client German
Wow cache deleted

![ubersetzung](https://user-images.githubusercontent.com/179698/53972023-539a4200-40fe-11e9-9758-0e72821689ec.jpg)

**Comment by pangolp** [comment]
It is possible that many translations are not done, the truth is that I only see the subject of Spanish because of the other languages much I do not understand. It would be necessary to complete them if they are missing.

**Comment by Bogir** [comment]
Localization dependences still are broken.

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can you please have a look at this?

**Comment by Winfidonarleyan** [comment]
Look my PR

**Comment by FrancescoBorzi** [comment]
@Seebaby @Bogir @pangolp can you please test the PR from @Winfidonarleyan?

**Comment by pangolp** [comment]
A thousand apologies, but the part of testing I really don't understand well, even when I have to do a PR I have terrible problems.

**Comment by FrancescoBorzi** [comment]
@pangolp no problem, we can help you. Just let us know what you don't understand

**Comment by pangolp** [comment]
Generally, the problem I have is that when I create a new branch, in the case of Windows (in linux I didn't try it) as I need to compile the whole core again, even if I have already compiled it once. That part isn't quite clear to me and that's why sometimes it's difficult for me to help you with the testing issue.
