### ISSUE TITLE
Some daily quests are not available after update 0322

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#15549]
### Current Behaviour

.go c 96761
or
.go c 84722

the NPC has no daily quests for service

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 826ac63af385+ 2023-03-22 12:02:11 -0400 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.85-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

debian 11

### Custom changes or Modules

> List enable modules:
- mod-anticheat
- mod-autozc
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-reward-played-time
- mod-save-inventory
- mod-server-auto-shutdown

**Comment by q67732897** [comment]
@kissingers 你烹饪熟练度没有达到对应的需求,熟练度达到了就会触发日常任务的！

**Comment by kissingers** [comment]
> @kissingers 你烹饪熟练度没有达到对应的需求,熟练度达到了就会触发日常任务的！

满了,我只是重启了下服务器,就都显示出来了,有点奇怪,先关闭吧
