### ISSUE TITLE
Language command problem

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#15555]
### Current Behaviour

I used this recipe
No more messages can be sent
No command works
![WoWScrnShot_032423_005308](https://user-images.githubusercontent.com/52524476/227369451-22288a86-ce42-408d-a39b-246e3f278512.jpg)

### Expected Blizzlike Behaviour

This command is for all languages

### Steps to reproduce the problem

Gm Account
.Learn all my lang

### AC rev. hash/commit

rev. c7fbf89e96c1

### Operating system

window server 2019 64bit

### Custom changes or Modules

mod-anticheat
mod-boss-announcer
mod-cfbg
mod-duel-reset
mod-level40
mod-level65
mod-quick-teleport

**Comment by Nyeriah** [comment]
You end up learning languages that are disabled and cannot be used with that command, such as Draconic and I believe Titan. AFAIK those langues are disabled client side and you can't use them to speak if you choose them, which seems to have been the case here.

**Comment by poryagholami** [comment]
> You end up learning languages that are disabled and cannot be used with that command, such as Draconic and I believe Titan. AFAIK those languages are disabled client side and you can't use them to speak if you choose them, which seems to have been the case here.

So what is it?
Is it used to mute gm?

**Comment by Kitzunu** [comment]
No issue. Nyeriah is correct and the command does what it says it does
