### ISSUE TITLE
(Instance/Karazhan): Nightbane is targettable/attackable before the fight starts.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15558]
### Current Behaviour

[Nightbane](https://wowgaming.altervista.org/aowow/?npc=17225) can be both targetted and attacked while resting on the mountain range in the Karazhan instance. This does not start the fight, he only starts flying in place.

### Expected Blizzlike Behaviour

Nightbane should not be targettable and not attackable while at rest before the encounter.

### Source

[Retail, circa patch 7.3.5](https://youtu.be/o0o-2ks2qnw?t=378).

### Steps to reproduce the problem

1. `.additem 24490`, `.tele karazhan`
2. Make a raid group.
3. Enter Karazhan.
4. `.go xyz -10994.63 -1766.50 140.73`
5. Target and attack Nightbane.
6. Observe that step 5 is possible.

### Extra Notes

Due to the nature of the issue, I doubt anyone was able to test this around retail 3.3.5a, nor will it be able to be tested on Classic. While it is definitely possible this behavior was added post-WotLK, I personally can't see any reason why that would be the case.

### AC rev. hash/commit

5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by damnablebear** [comment]
I could not reproduce this in testing https://github.com/chromiecraft/chromiecraft/issues/4882 on the ChromieCraft PTR realm.

**Comment by heyitsbench** [comment]
> I could not reproduce this in testing CC-4882 on the ChromieCraft PTR realm.

It seems the issue was fixed by fcf7ceea42b0bfcd7a0c5cdc06a08f6c77faf204.
