### ISSUE TITLE
ICC: Sindragosa did not reset correctly

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15557]
### Current Behaviour

when the raid dies in the encounter against sindragosa, the event is not restarting as it should be, sindragosa should appear on the platform, and currently flies out again as if it were the first time you entered the room

https://youtu.be/wuCac1cpcfk
### Expected Blizzlike Behaviour

when dying in the sindragosa encounter he must reappear in the center of the platform

### Steps to reproduce the problem

1. go icc
2. go sindrgosa
3. enter combat and dead
4. revive

### Extra Notes

that happens since the implementation of https://github.com/azerothcore/azerothcore-wotlk/pull/14789

needs Label: "Instance - Dungeon - Northrend", 80,  Confirmed, Priority-High, 

### AC rev. hash/commit

5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

**Comment by indigowowserver** [comment]
yes i confirm . this is a must fix issue . i tried it myself

**Comment by Andyk10** [comment]
Yes, I confirm this bug too, which will result in a significant loss of mana before the battle even begins.

**Comment by qwe900** [comment]
some one has a retail video of this ?

**Comment by Dr-Arayashiki** [comment]
> some one has a retail video of this ?

![image](https://user-images.githubusercontent.com/122452427/228976717-d5b0f072-7780-4b3e-92d0-999c00c12bf2.png)
she keeps flying on the background after she evades
and just lands once player moves to the middle
she does not clean when she lands for the second time

unfortunately I didn't find any video, just an image that @Nyeriah  sent

**Comment by Dr-Arayashiki** [comment]
@qwe900 did you understand how it works?
the problem is not when he starts, but when he should come back and fly until the tank catches him in the middle of the room

**Comment by Dr-Arayashiki** [comment]
@qwe900 

> some one has a retail video of this ?

I know it's not from an original server, unfortunately I can't find it, but that's how it works... look at it flying in the background waiting to be pulled

https://youtu.be/NN8oVxKLsmM?t=11019

**Comment by Dr-Arayashiki** [comment]
> some one has a retail video of this ?
some friends of mine recorded it for me straight from the blizzard server
https://drive.google.com/file/d/1tnJ2EIGcFG08cnAHDcjln4njpcco6wQA/view?usp=share_link

**Comment by Dr-Arayashiki** [comment]
> some one has a retail video of this ?

@qwe900 @Nyeriah 
some friends of mine recorded it for me straight from the blizzard server

https://drive.google.com/file/d/1tnJ2EIGcFG08cnAHDcjln4njpcco6wQA/view?usp=share_link
