### ISSUE TITLE
Smart action SET_REACT_STATE does not work until the target resets.

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#15563]
### Current Behaviour

Currently If you set a creature's reactstate while it is in combat, nothing will happen.

### Expected Blizzlike Behaviour

Should behave like script reactstate, if you set passive while in combat it should instantly become passive, not wait until it resets.

### Steps to reproduce the problem

Make a simple SAI, 3s in combat, set react state passive. Notice nothing happens until the mob resets, then it is passive.

### Extra Notes

You can force the creature to become passive, while in combat, if you combine it with 224 SMART_ACTION_ATTACK_STOP (should align that with TC, 46)

### AC rev. hash/commit

5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
REACT_STATE as the name implies its how they behave towards approaching units while outside combat, there’s nothing wrong here, it also doesn’t do anything if you change it in CPP if they are in combat/already have targets in their threat list

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/4ff81ebf221c0853df340133903a95e45f7736cc/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_forgemaster_garfrost.cpp#L140
Is the SetTarget() what makes it work in script?

**Comment by Nyeriah** [comment]
me->SendMeleeAttackStop()

the empty SetTarget() just clears his current target focus from the UI

**Comment by avarishd** [comment]
Thanks, had no idea it worked that way, my bad.
