### ISSUE TITLE
Bloodforged Guard and Gold-Trimmed Cuffs shouldn't stay in a reference loot template

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#15586]
Original Issues: 
https://github.com/chromiecraft/chromiecraft/issues/4847
https://github.com/chromiecraft/chromiecraft/issues/4848

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

[Bloodforged Guard](https://wowgaming.altervista.org/aowow/?item=30986#dropped-by) and [Gold-Trimmed Cuffs](https://wowgaming.altervista.org/aowow/?item=30520) are a quest reward but also drops from NPCs

### Expected Blizzlike Behaviour

shouldnt drop from NPCs

### Source

https://www.wowhead.com/wotlk/item=30986/bloodforged-guard
https://www.wowhead.com/item=30520/gold-trimmed-cuffs

### Steps to reproduce the problem

Search in the DB for the reference 6002

### AC rev. hash/commit

825d0dc2bb4b

### Operating system

Ubuntu 20.04 - Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
To add to this: they are found among the BoE greens in reference_loot_template entry id 4110 as the two last entries. simply removing them using 2 queries should work here
