### ISSUE TITLE
ICC: Bug of Little Monster

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15587]
### Current Behaviour

The trap was triggered in front of BOSS 1, but the spider on its head did not come down and was still suspended in mid air.

### Expected Blizzlike Behaviour

The trap is triggered in front of BOSS 1, and the spider on its head will come down, similar to the small monster in the room in front of Cindagosa. It can be killed normally.

### Steps to reproduce the problem

Unable to resolve

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

WINDOWS 2019

**Comment by yukijean** [comment]
Can anyone help solve this problem? Thank you.

**Comment by qwe900** [comment]
234f1d1 
try this

**Comment by yukijean** [comment]
Okay, can you fix the problem that the Algalon group doesn't refresh after it dies out




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azerothcore/azerothcore-wotlk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上7:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azerothcore/azerothcore-wotlk] ICC: Bug of Little Monster (Issue #15587)





 
234f1d1
 try this

**Comment by qwe900** [comment]
> Okay, can you fix the problem that the Algalon group doesn't refresh after it dies out
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "azerothcore/azerothcore-wotlk" ***@***.***&gt;; 发送时间:&nbsp;2023年3月28日(星期二) 晚上7:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [azerothcore/azerothcore-wotlk] ICC: Bug of Little Monster (Issue #15587) [234f1d1](https://github.com/azerothcore/azerothcore-wotlk/commit/234f1d14399a80dd3f77f75df0272696c3fb60fd) try this — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

create
a new issue and discribe the problem, i dont unsterstand what u mean

**Comment by yukijean** [comment]
#15539&nbsp;Look at this problem. It's a malignant bug, but no one has fixed it



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azerothcore/azerothcore-wotlk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azerothcore/azerothcore-wotlk] ICC: Bug of Little Monster (Issue #15587)





  
Okay, can you fix the problem that the Algalon group doesn't refresh after it dies out
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "azerothcore/azerothcore-wotlk" @.&gt;; 发送时间:&nbsp;2023年3月28日(星期二) 晚上7:50 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [azerothcore/azerothcore-wotlk] ICC: Bug of Little Monster (Issue #15587) 234f1d1 try this — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
create
 a new issue and discribe the problem, i dont unsterstand what u mean
