### ISSUE TITLE
Worldserver spams systemd log

### ISSUE THREAD

**Issue by FallingSnow** [azerothcore/azerothcore-wotlk#1562]
##### SMALL DESCRIPTION:
While using a systemd service to run worldserver, worldserver spams systemd with new lines.

This is most likely due to systemd setting [stdin to `/dev/null`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#StandardInput=).

Systemd service:
```
[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver

[Install]
WantedBy=default.target
```

I'm not sure if the fix should be applied on the Azerothcore side or Systemd side.

Using `StandardInput=tty` or `StandardInput=data` and `StandardInputText=""` in the systemd service file does seem to work but worldserver no longer logs to systemd and CPU usage jumps to 100% on one core.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit 5348d9cbe590686971a8945e986094d3cc2c8a44 (grafted, HEAD -> master, origin/master, origin/HEAD)

##### OPERATING SYSTEM:

Linux Divinity 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

None

**Comment by FallingSnow** [comment]
Btw here is an excerpt of the spam that fills megabytes of my logs:

```
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
Mar 08 13:52:03 Divinity worldserver[8647]: AC>
```

**Comment by masterking32** [comment]
Change 
`[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver

[Install]
WantedBy=default.target`

to 

`[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver  > /dev/null 2>&1 &

[Install]
WantedBy=default.target`

**Comment by masterking32** [comment]
Change 
```
[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver

[Install]
WantedBy=default.target
```

to 

```
[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver  > /dev/null 2>&1 &

[Install]
WantedBy=default.target
```

**Comment by FallingSnow** [comment]
Issue still remains the same with the updated config. Spam remains. :(

For the time being I've been using:
```
[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver
StandardInput=tty
TTYPath=/dev/tty2 
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=default.target
```

But I'd rather not dedicate a real tty to worldserver.

> It's about linux not AzerothCore ... close that.

I'm not so sure about that. I'm starting to lean towards the idea that worldserver should be either checking if [stdin is a tty](https://linux.die.net/man/3/isatty) or no longer requesting input when [reading `EOF` from stdin](https://stackoverflow.com/questions/20272388/how-to-check-if-stdcin-is-associated-with-a-terminal-or-a-pipe) (this would probably work best since systemd's default behavior results in `EOF`).

**Comment by FallingSnow** [comment]
Now I'm tripping out because it seems like worldserver does check for `EOF`...
https://github.com/azerothcore/azerothcore-wotlk/blob/832bccd9fa8ae5f3dd20eaeed244e74cd700f2de/src/server/worldserver/CommandLine/CliRunnable.cpp#L148-L192

[Systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) on StandardInput:
> If null is selected, standard input will be connected to /dev/null, i.e. all read attempts by the process will result in immediate EOF.

> This setting defaults to null.

Worldserver uses readline, and [readline's docs](http://man7.org/linux/man-pages/man3/readline.3.html):
> readline returns the text of the line read.  A blank line returns the
       empty string.  If EOF is encountered while reading a line, and the
       line is empty, NULL is returned.  If an EOF is read with a non-empty
       line, it is treated as a newline.

[`feof` docs](http://www.cplusplus.com/reference/cstdio/feof/):
> Checks whether the end-of-File indicator associated with stream is set, returning a value different from zero if it is.

I'm kind of lost because doesn't this mean that worldserver should be starting then stopping immediately?

**Comment by FrancescoBorzi** [comment]
Interesting. I had this issue only when trying to dockerize AC and I solve the issue giving by default:

`tty: true`

but I can't reproduce the issue on traditional setup

**Comment by FallingSnow** [comment]
Yeah, that's similar to what I'm doing. I'm just providing a tty to fix the issue. I wish there was a less hacky fix.

**Comment by FallingSnow** [comment]
So after doing some thinking, I think
```cpp
else if (feof(stdin)) 
{ 
    World::StopNow(SHUTDOWN_EXIT_CODE); 
}
```
should be changed to something like
```cpp
else
{ 
    break;
}
```

I don't think it's wise to stop the worldserver if you read a EOF. That's something that should be handled by signals like `SIGINT`.

**Comment by FallingSnow** [comment]
Well I feel like an idiot. After going through the source code I realized it only starts the CLI thread if config option `Console.Enable` is true. So I set `Console.Enable = 0` and wallah, it works.

Here is the final working systemd.service for worldserver:
```
[Unit]
Description=Azerothcore Worldserver Service
After=network.target

[Service]
Type=simple
ExecStart=/opt/azeroth-server/bin/worldserver
# Need to sleep to give worldserver time to bind to its port before reporting ready
ExecStartPost=/usr/bin/sleep 1

[Install]
WantedBy=default.target
```

**Comment by oscxc** [comment]
> 

This helpd me. Good work!

**Comment by oscxc** [comment]
> Well I feel like an idiot. After going through the source code I realized it only starts the CLI thread if config option `Console.Enable` is true. So I set `Console.Enable = 0` and wallah, it works.
> 
> Here is the final working systemd.service for worldserver:
> 
> ```
> [Unit]
> Description=Azerothcore Worldserver Service
> After=network.target
> 
> [Service]
> Type=simple
> ExecStart=/opt/azeroth-server/bin/worldserver
> # Need to sleep to give worldserver time to bind to its port before reporting ready
> ExecStartPost=/usr/bin/sleep 1
> 
> [Install]
> WantedBy=default.target
> ```

This helpd me. Good work!
