### ISSUE TITLE
[PVE/SPELL][ICCBOSS/SPELL] Absorb spell and buff  vs Conjure Flame

### ISSUE THREAD

**Issue by Heisenberg520** [azerothcore/azerothcore-wotlk#1569]
##### SMALL DESCRIPTION:

The spell of the Priest https://www.wowhead.com/spell=17/power-word-shield make the player not able to share the spell https://www.wowhead.com/spell=71718/conjure-flame of the boss of icc https://www.wowhead.com/npc=37973/prince-taldaram#abilities

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The spell of Taldaram https://www.wowhead.com/spell=71718/conjure-flame is  a Sphere of fire that he casts and fly targetting a Player , the other player should share the damage that the Sphere of fire does going near the targetted player  to reduce the damage that the sphere does exploding near the targetted player and on the player 

##### CURRENT BEHAVIOUR:
The player that are buffed with the spell  https://www.wowhead.com/spell=17/power-word-shield does not share the damage of the sphere to reduce the final damage of the explosion of the sphere  , they take damage but the size of the sphere , that is an indicator of how much damage the sphere will do , remain the same, the size of the sphere is only reduced if the players that are sharing the damage are not shielded . THIS HAPPEN OLSO WITH OTHER TYPES OF ABSORB AND ABSORB BUFF OR SPELL !!!

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go inside icc , u will need at leat 5 -6 players 
2. start the fight the Princes , wait until taldaram casts his Conjure Flame
3. See that when the player that is targetted and run away, the players that are positioned beteween the sphere and player does not reduce the size and the final damage of the sphere if some or all of them are shielded , they will take damage but  the sphere will not count them as if they've take damage from it

##### EXTRA NOTES:
HIGH PRIO , THE DISCI PRIEST WILL BE USELESS DURING THIS FIGHT AND IS AN IMPORTANT HEALING CLASS IN 25 N AND 25 H ICC 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

**Comment by JamesGent** [comment]
Can confirm still bugged.
