### ISSUE TITLE
[Warlock Spell] Conflagrate

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#1571]
Warlock Spell Conflagrate

##### SMALL DESCRIPTION:
The warlock spell Conflagrate not work properly , after apply immolate on the target , conflagrate can be use after 1 seconde , and should be use instantly

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The spell Conflagrate should be ready to use instantly after target immolated.

##### CURRENT BEHAVIOUR:
Actually , Conflagrate is ready to use aproximately 1 seconde after the target was immolate.

##### STEPS TO REPRODUCE THE PROBLEM:

 1. Create a destruction Warlock and take Conflagrate talent
 2. Cast immolate on a monster and ser the delay to use Conflagrate

##### BRANCH(ES):

master

##### OPERATING SYSTEM: Debian 9

**Comment by talamortis** [comment]
Im sure this issue has been addressed before. it was already deemed to be blizzlike

See Here https://github.com/azerothcore/azerothcore-wotlk/issues/298
and Here https://github.com/azerothcore/azerothcore-wotlk/issues/832

**Comment by vhiperdev** [comment]
It's correct as it was in retail it worked this way with a delay of 0.07

https://www.youtube.com/watch?v=yq3N1fP3a24&feature=youtu.be&t=194
