### ISSUE TITLE
the function of “reset all instances” cannot be used

### ISSUE THREAD

**Issue by ErickChen30323** [azerothcore/azerothcore-wotlk#15730]
### Current Behaviour

After installing the latest version and logging into the game, I found that the function of “reset all instances” cannot be used. [However, if i use the GM command, I can still reset it]

### Expected Blizzlike Behaviour

I want to confirm whether this is a bug or a problem with my usage or configuration.

### Steps to reproduce the problem

just use this function "reset all instances"

### AC rev. hash/commit

no

### Operating system

ubuntu 22

**Comment by Kitzunu** [comment]
It works. That just resets instances you dont get locked to
