### ISSUE TITLE
BUG of Icecrown Fortress Cindagosa

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15733]
### Current Behaviour

Previously, we fixed the problem of Xindagoza killing everything in the ground, but now there is a small problem. After Xindagoza destroyed the regiment, BOSS disappeared and came down from the sky again.

### Expected Blizzlike Behaviour

Whether it's a battle of Kart or the death of the annihilating regiment, Sindagosa should be directly on the platform and should no longer fly down from the sky.

### Steps to reproduce the problem

I don't know how to solve it

### AC rev. hash/commit

AZEROTHCORE REV.4134C2DADA78+ 2023-03-14 06:35:16 +0000（主要支持）（WIN64.RELWITHDEBINFO，静态）

### Operating system

WINDOWS SERVER 2019

**Comment by Dr-Arayashiki** [comment]
The staff is working to try to solve the problem in sindragosa, this problem is already open in: https://github.com/azerothcore/azerothcore-wotlk/issues/15557

**Comment by yukijean** [comment]
@Dr-Arayashiki Okay, I didn't notice, so I closed this issue
