### ISSUE TITLE
[NPC][WOTLK] Archmage Timear

### ISSUE THREAD

**Issue by Xandrice** [azerothcore/azerothcore-wotlk#1574]
##### SMALL DESCRIPTION:
NPC Archmage Timear (31439) does not give daily quests to give emblems. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You should receive a quest from this NPC once a day to clear a heroic dungeon.

https://wowgaming.altervista.org/aowow/?search=Proof+of+Demise%3A

##### CURRENT BEHAVIOUR:
This NPC does not give any quests whatsoever. 

##### STEPS TO REPRODUCE THE PROBLEM:
1. Teleport to Dalaran, Head towards Violet Hold and turn left. 
2. Talk to Archmage Timear

##### EXTRA NOTES:
NPC Archmage Lan'dalock (ID 20735) gives similar quests but his quests are weekly. 

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
26ae2ce

##### OPERATING SYSTEM:
Windows 10 Professional

##### MODULES:
Transmog

##### OTHER CUSTOMIZATIONS:
Anti-Cheat

I hope this is somewhat correct, This is my first issue I've ever written so bare with me. I can provide more information as needed also.

**Comment by talamortis** [comment]
Patch 3.3.0 - This NPC no longer gives quest so this is working as intended since we are patch 3.3.5. 

![image](https://user-images.githubusercontent.com/6143065/54457482-70b3be00-4759-11e9-94fc-e42970598096.png)
