### ISSUE TITLE
Modules install

### ISSUE THREAD

**Issue by kurigvin** [azerothcore/azerothcore-wotlk#15743]
### Current Behaviour

Error

### Expected Blizzlike Behaviour

no

### Steps to reproduce the problem

/usr/bin/ld: ../../../modules/libmodules.a(ModulesLoader.cpp.o): в функции «AddModulesScripts()»:
/home/server/wowserver/azerothcore/build/modules/gen_scriptloader/static/ModulesLoader.cpp:53: неопределённая ссылка на «Addmod_1v1_arena_masterScripts()»
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:194: src/server/apps/worldserver] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:1105: src/server/apps/CMakeFiles/worldserver.dir/all] Ошибка 2
make: *** [Makefile:149: all] Ошибка 2

### AC rev. hash/commit

no

### Operating system

Debian 11

**Comment by heyitsbench** [comment]
Remove master from the folder name. Next time make a report for the module. This is not an AC issue.

And attach the commit you're running AC on. You won't get support if you just say "no".

**Comment by acidmanifesto** [comment]
> Remove master from the folder name. Next time make a report for the module. This is not an AC issue.
> 
> And attach the commit you're running AC on. You're not liable to get support if you just say "no".

Pretty much this.

**Comment by kurigvin** [comment]
Thank you
