### ISSUE TITLE
[BUG] Character change race/faction does not update DB

### ISSUE THREAD

**Issue by Turczynek** [azerothcore/azerothcore-wotlk#15757]
### Current Behaviour

"Character GUID Full: 0x000000000000000c Type: Player Low: 12 has skill 760 that does not exist.
ActionButton loading problem, will be deleted from db..."

Command:
.character changefaction
.character changerace

The bug is that it doesn't update or remove the racial of the previous race.
This error shows up every time we enter a character whose race we changed

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

1. Use command .character changerace
2. Logout and change race
3. Login in character that changed the race
4. See log console

### AC rev. hash/commit

.

### Operating system

Windows 10

### Custom changes or Modules

Eluna module

**Comment by wefgame** [comment]
why was it closed, the problem remained

**Comment by heyitsbench** [comment]
> why was it closed, the problem remained

Because no revision hash was provided.
