### ISSUE TITLE
Suggestion: New parameter in INVOKER_PARTY taget_type to also target pets

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#15755]
### Describe your feature request or suggestion in detail

https://github.com/azerothcore/azerothcore-wotlk/pull/15749

**Comment by avarishd** [comment]
Can use param1 as an option to select pets. (Off by default)

**Comment by Kitzunu** [comment]
Pet me 😘

It should include pet & guardian in that case
