### ISSUE TITLE
(Creature): Anchorite Yazmina has inaccessible vendor items.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15769]
### Current Behaviour

Could not tell you why, but [Anchorite Yazmina](https://wowgaming.altervista.org/aowow/?npc=23734) has the vendor flag and has items listed as being sold by her on AoWoW, though they aren't accessible in-game.

### Expected Blizzlike Behaviour

She shouldn't sell anything at all. I also doubt she should have the flag/items attached to her at all.

### Source

Wrath Classic

### Steps to reproduce the problem

1. Observe the base of data.

(Optionally)
2. `.tele valgarde`
3. Interact with Yazmina.
4. Observe her lack of selling. (Which is good!)

### AC rev. hash/commit

d4e87f2791c7bc321a4f7bfcf062e12c3d529bdb

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by avarishd** [comment]
[During the early beta, she was a Reagent Supplier to a Grand Master First Aid Trainer.](https://wowpedia.fandom.com/wiki/Anchorite_Yazmina)

https://www.wowhead.com/wotlk/npc=23734/
