### ISSUE TITLE
problem Creature StormForged Giant 

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#15770]
### Current Behaviour

This npc should not be stopped by any magic
![WoWScrnShot_040223_021229](https://user-images.githubusercontent.com/52524476/229322723-52ab5806-1903-4ba0-974e-3ed419588f7a.jpg)

### Expected Blizzlike Behaviour

In the original version
All spells that stop this npc
have been deactivated

### Source

Flags selection: mechanic_immune_mask
604118544

### Steps to reproduce the problem

.go c 126983

### AC rev. hash/commit

rev. c8c042d326fc

### Operating system

window server 2019 64bit

**Comment by heyitsbench** [comment]
Please describe what the issue is more clearly, and please include an actual source for the expected behavior.

**Comment by Kitzunu** [comment]
My guess is that he's supposed to be CC immune
But I'd like that sniffed :D

**Comment by poryagholami** [comment]
> Please describe what the issue is more clearly, and please include an actual source for the expected behavior.

This npc has a higher rank than other npc
I played on the Warmin server
These levels had no effect
Stun / fear / freeze and ...
Here, however, it is the opposite, all the levels work

**Comment by poryagholami** [comment]
> My guess is that he's supposed to be CC immune But I'd like that sniffed :D

No, I said that the levels that stop the npc should be disabled according to what I said
The database is easy to solve the problem

**Comment by heyitsbench** [comment]
> The database is easy to solve the problem

Then feel free to submit a PR. And don't forget an actual source for the behavior.

**Comment by Kitzunu** [comment]
What bench said. And I want to add to that, that Warmane is not a source. It is a private server
