### ISSUE TITLE
CMake finds Apple's readline library instead of GNU's readline library

### ISSUE THREAD

**Issue by bahboom** [azerothcore/azerothcore-wotlk#15775]
### Current Behaviour

cmake finds Apple's readline library instead of GNU's readline library.  Eventually causing compilation error.

I also already have brew installed readline and libedit.

### Expected Blizzlike Behaviour

Able to compile code on Mac.

### Steps to reproduce the problem

1) Check out code on a Mac computer
2) Run cmake and look for cmake logs similar to below:
-- Found Readline library: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libreadline.tbd
-- Include dir is: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include

3) Run make and look for errors similar to below:
/azerothcore-wotlk/src/server/apps/worldserver/CommandLine/CliRunnable.cpp:69:18: error:
      no member named 'rl_done' in the global namespace
               ::rl_done = 1;
               ~~^
/azerothcore-wotlk/src/server/apps/worldserver/CommandLine/CliRunnable.cpp:121:7: error:
      no member named 'rl_event_hook' in the global namespace
    ::rl_event_hook = &Acore::Impl::Readline::cli_hook_func;
    ~~^
2 errors generated.

### AC rev. hash/commit

d4e87f2791c7bc321a4f7bfcf062e12c3d529bdb

### Operating system

macOS Catalina

**Comment by Kitzunu** [comment]
All I can tell you is that the macOS CI is passing.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/actions?query=workflow%3Amacos-build+branch%3Amaster+event%3Apush

**Comment by bahboom** [comment]
My bad, I somehow missed the wiki on explicitly setting the readline lib paths.  The readline library installed via homebrew is in a different directory though (/usr/local/Cellar/readline). I guess I was just lazy in wanting the readline cmake file to find it.

cmake ../ \
-DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/  \
-DTOOLS_BUILD=all \
-DSCRIPTS=static \
-DMYSQL_ADD_INCLUDE_PATH=/opt/homebrew/include/mysql \
-DMYSQL_LIBRARY=/opt/homebrew/lib/libmysqlclient.dylib \
-DREADLINE_INCLUDE_DIR=/opt/homebrew/opt/readline/include \
-DREADLINE_LIBRARY=/opt/homebrew/opt/readline/lib/libreadline.dylib \
-DOPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/include" \
-DOPENSSL_SSL_LIBRARIES="$OPENSSL_ROOT_DIR/lib/libssl.dylib" \
-DOPENSSL_CRYPTO_LIBRARIES="$OPENSSL_ROOT_DIR/lib/libcrypto.dylib"
