### ISSUE TITLE
Grunda Bronzewing in Honor Hold is not riding on a golden gryphon

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#15781]
original bugreport on CC by bench: https://github.com/chromiecraft/chromiecraft/issues/5318

### What client do you play on?
enUS

### Faction
Alliance

### Content Phase:
61-64

### Current Behaviour

[Grundra Bronzewing](https://wowgaming.altervista.org/aowow/?npc=35101) is not mounted atop a gryphon.

### Expected Blizzlike Behaviour

She should be mounted atop a gryphon.

### Source

Wrath Classic

edit by Elthehablo: also visible in screenshot on https://www.wowhead.com/wotlk/npc=35101/grunda-bronzewing

### Steps to reproduce the problem

1. `.tele honorhold`
2. Walk up to Bronzewing.
3. Observe Bronzewing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by Dr-Arayashiki** [comment]
I fixed this little problem, but I don't know how to submit a fix to the branch

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/how-to-create-a-pr

**Comment by elthehablo** [comment]
> 

specifically for your contribution probably: https://www.azerothcore.org/wiki/how-to-create-a-db-pr

**Comment by heyitsbench** [comment]
```sql
UPDATE `creature_template_addon` SET `mount` = 17697 WHERE `entry` = 35101;
```
Source: 45854 sniff.

**Comment by Kitzunu** [comment]
What does 45854 stand for?

**Comment by heyitsbench** [comment]
> What does 45854 stand for?

Build number.

**Comment by Kitzunu** [comment]
Ahhh makes sense
