### ISSUE TITLE
Loop index leak into item amount given when opening container

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15789]
### Current Behaviour

![image](https://user-images.githubusercontent.com/50233983/229380826-3ceeb3d3-acfb-4ff2-a0a2-38dd34bd2ae1.png)

I cannot even say that is the current behavior as I was unable to reproduce this behavior, but
I got 0 Shirts, 1 Sash, 2 Boots, 3 Pants which is the order the items are in and counting up from 0

### Expected Blizzlike Behaviour

Item amount is not influenced by the index of a loop
In the case of this container it would be 1 of each
https://wowgaming.altervista.org/aowow/?item=22746#contains

### Steps to reproduce the problem

Open many containers I guess
I opened 200 myself after this occurence but no "luck"

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by Kitzunu** [comment]
Loot isnt indexed though, so that wouldnt be possible. It is just calculated by chance.
And the amount of an item that can be dropped is dependant on min/max counts set in DB.

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/229382188-7191c412-f435-4fe5-bb40-2cf8a328fa9d.png)
The min/max count of the items is 1
I also wrote loop index not loot index

**Comment by Kitzunu** [comment]
Well then we have an issue.

**Comment by Dr-Arayashiki** [comment]
eu não sei o que acontece ai, aqui esta normal  rsrsrs
![image](https://user-images.githubusercontent.com/122452427/229383688-6dd51b03-a85d-4991-a6c8-f6327c19e655.png)

**Comment by Dr-Arayashiki** [comment]
> Well then we have an issue.

or not 🐰

**Comment by Dr-Arayashiki** [comment]
@Tereneckla 
Have you tried to open without using all these modules?

**Comment by heyitsbench** [comment]
> or not 🐰

They already said it wasn't a consistent issue, *highly* unsurprising that it didn't happen to you just opening it once.

**Comment by Dr-Arayashiki** [comment]
> > or not 🐰
> 
> They already said it wasn't a consistent issue, _highly_ unsurprising that it didn't happen to you just opening it once.

on the first screenshot i really only opened it once but i opened it at least 26 times and the behavior was normal so i dunno :(

**Comment by Tereneckla** [comment]
@Dr-Arayashiki I could not reproduce it at all so far

A full playthrough of the one time it happened would be to get the container, leave it in the bank for ~5 months and then open it at 2023-04-02T21:29:16+00:00

**Comment by Nyeriah** [comment]
> @Dr-Arayashiki I could not reproduce it at all so far
> 
> A full playthrough of the one time it happened would be to get the container, leave it in the bank for ~5 months and then open it at 2023-04-02T21:29:16+00:00

Seriously? It only happened once?

**Comment by Tereneckla** [comment]
Yes
