### ISSUE TITLE
creature_onkill_reputation cannot handle floating point reputation rewards

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#15799]
original CC post: https://github.com/chromiecraft/chromiecraft/issues/5328

originally by @v-mstrs 

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Reputation is an integer value

### Expected Blizzlike Behaviour

Nexus Terror in Heroic Mana-Tombs awards 22 and 23 reputation, alternatively. From which it can be inferred that they award 22.5 reputation

### Source

https://www.wowhead.com/npc=19307/nexus-terror

### Steps to reproduce the problem

1. set dungeon difficulty to heroic
2. `.tele manatombs`
3. enter dungeon
4. `.gm on` for safety :p 
5. find a Nexus Terror and kill it and see you will only receive 22 rep

### Extra Notes

might need check on retail, although wowpedia is a relatively good source for these kinds of values

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

Linux Mint 21.1

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
Alternates perfectly between 22 and 23. If it was random I'd notice getting 22 or 23 twice in a row

**Comment by Tereneckla** [comment]
That definitely is .5 then, same behavior as human rep bonus

**Comment by Gultask** [comment]
Yeah that's what I was going to say. If I had a human in retail I'd test killing enemies that award odd-numbered rep values
