### ISSUE TITLE
[Pit of Saron]: Scourgelord Tyrannus doesn't restart when you die

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15824]
### Current Behaviour

Scourgelord Tyrannus doesn't restart when you die

### Expected Blizzlike Behaviour

should reset the event correctly when you die against Scourgelord Tyrannus

### Steps to reproduce the problem

1 . go Pit of Saron
2. kill the first two bosses
3. go to Scourgelord Tyrannus start combat and die

### Extra Notes

only tested in 5 player heroic mode, but in normal mode for sure there must be the same problem

### AC rev. hash/commit

f10928fa5cd845278b75f5c93c972a4b71216045

### Operating system

Ubuntu 20.04

**Comment by Tony931023** [comment]
@Nyeriah when you have some time check this, the same problem that happened with the previous icc bosses

**Comment by sylar1015** [comment]
we met the same issue, as we can not finish the dungeon, we can not enter the next dungeon either .

**Comment by Tony931023** [comment]
This video is in Heroic mode Pit of Saron. When you die in the first attempt and want to fight against Tyranus again, only the dragon flying appears and Tyranus doesn't appear anymore.

https://www.youtube.com/watch?v=k0gtEUIqak0

**Comment by pklloveyou** [comment]
UPDATE `creature_template` SET `flags_extra` = `flags_extra` &~ 2147483648 WHERE `entry` IN (36658);

**Comment by Tony931023** [comment]
> ```sql
> UPDATE `creature_template` SET `flags_extra` = `flags_extra` &~ 2147483648 WHERE `entry` IN (36658);
> ```

tested and works fine, thanks @pklloveyou  ♥

**Comment by kambire** [comment]
again the same problem

**Comment by manstfu** [comment]
# How to trigger on normal mode:

Evade while fighting with boss, boss should respawn on Rimefang

**.npc info on Normal mode**
![image](https://github.com/user-attachments/assets/cdf347b6-2eeb-4eeb-a399-169349d38484)

https://github.com/user-attachments/assets/f6fdd6db-35b1-400a-b781-6570cbeb2469

 # How to trigger on heroic mode:
Die while fighting, boss should respawn on Rimefang

**.npc info on Heroic mode**
![image](https://github.com/user-attachments/assets/12658f40-43a2-42d3-960a-b60cef99d893)


https://github.com/user-attachments/assets/9e19c906-7bb9-43c8-bdc8-1e6e7acfa80c

**Comment by MrFuriogaming** [comment]
Hello, I am new to this.
I'm going through all the comments.
I saw that this is still open. I would like to share a custom LUA solution that I paid for. Maybe it can help someone, until they manage to add it to the code.
Here is the code:
**local Trigger = 100002
local function OnUpdate(event, creature)
    local Tyrannus = creature:GetCreaturesInRange(150, 36658, 0, 1)
    local TyrannusDead = creature:GetCreaturesInRange(150, 36658, 0, 2)
    local Rimefang = creature:GetCreaturesInRange(150, 36661, 0, 1)

    if #TyrannusDead == 1 then
        return false
    end

    if #Tyrannus == 0 and #Rimefang == 1 then
        print(“>> [TyrannusFix]: Rimefang & Tyrannus Restarted!”)
        PerformIngameSpawn(1, 36661, creature:GetMapId(), creature:GetInstanceId(), 1017.3, 168.974, 642.926, 5.2709)
        Rimefang[1]:RemoveFromWorld()
    end

end

local function Main()
    ClearCreatureEvents(Trigger)
    
    RegisterCreatureEvent(Trigger, 7, OnUpdate)
end

RegisterServerEvent(33, Main)**

**Comment by Talamorts1** [comment]
@MrFuriogaming I have applied a fix please see the above

**Comment by manstfu** [comment]
> @MrFuriogaming I have applied a fix please see the above

Can you PR it?

**Comment by Talamorts1** [comment]
My main account is banned so i cant :)

**Comment by Talamorts1** [comment]
> > @MrFuriogaming I have applied a fix please see the above
> 
> Can you PR it?

i cant, as ive got custom stuff on my source but you are more than welcome to submit a PR for me :)

**Comment by blinkysc** [comment]
I submitted PR for you @Talamorts1

**Comment by Talamorts1** [comment]
> I submitted PR for you @Talamorts1

did you test?

**Comment by blinkysc** [comment]
No not yet, I put in the PR it needed a test though. Still working atm but will when I get off

**Comment by blinkysc** [comment]
Just test and seems like it works correctly
<img width="1607" alt="Screenshot 2024-12-28 at 6 18 10 PM" src="https://github.com/user-attachments/assets/6b377773-0592-4c27-bce9-c7cbc54b7aed" />

**Comment by Talamorts1** [comment]
![image](https://github.com/user-attachments/assets/c8c2e371-04ba-4bf9-a7f8-0f4cabc07c4d)

@Nyeriah - I don't see him respawned with the new changed. please read what the function does before assuming thanks.

**Comment by Nyeriah** [comment]
Let me get this straight. You come here, suggest things that were already suggested by everybody else and not accepted as they were hacks. Does not bother checking anything you suggest, starts pulling things out of thin air without even bothering to go in-game and check the boss (as then you would have realized he is a temporary spawn, and therefore CANNOT be respawned, so your latest fix would never have worked).

Nonetheless, you proceed to suggest things you neither bothered to test or verify, but went on with the atittude.

And now you attack the ones who spent the last couple of hours working on a proper fix, disregarding the fact I already have a PR open and ALREADY told you I was working on it.

We have no need of toxic people here. Thanks for your contributions, but this clearly isn't the place for you.
