### ISSUE TITLE
Crash world ICC boss_sister_svaln 

### ISSUE THREAD

**Issue by Fireevil** [azerothcore/azerothcore-wotlk#15856]
### Current Behaviour

crash worldserver start combat whit boss_sister_svaln 
same to what happened with putricide in last rev

00007FF77839244F  000000869E5FEF30  instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::CheckRequiredBosses+F  C:\Servidor De Prueba\azerothcore-wotlk\src\server\scripts\Northrend\IcecrownCitadel\instance_icecrown_citadel.cpp line 1460
00007FF778669912  000000869E5FEF60  BossAI::_JustEngagedWith+72  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\AI\ScriptedAI\ScriptedCreature.cpp line 607
00007FF77839FF2D  000000869E5FEFA0  boss_sister_svalna::boss_sister_svalnaAI::JustEngagedWith+5D  C:\Servidor De Prueba\azerothcore-wotlk\src\server\scripts\Northrend\IcecrownCitadel\icecrown_citadel.cpp line 1050
00007FF7786C0E4E  000000869E5FEFF0  Unit::SetInCombatState+1BE  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.cpp line 13698
00007FF7786C109A  000000869E5FF020  Unit::SetInCombatWith+DA  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.cpp line 13524
00007FF778613381  000000869E5FF1C0  CreatureAI::DoZoneInCombat+161  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\AI\CreatureAI.cpp line 135
00007FF7783A0C4A  000000869E5FF1F0  boss_sister_svalna::boss_sister_svalnaAI::MovementInform+7A  C:\Servidor De Prueba\azerothcore-wotlk\src\server\scripts\Northrend\IcecrownCitadel\icecrown_citadel.cpp line 1130
00007FF77866D197  000000869E5FF220  MotionMaster::DirectDelete+27  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Movement\MotionMaster.cpp line 853
00007FF77866D21F  000000869E5FF260  MotionMaster::DirectExpire+6F  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Movement\MotionMaster.cpp line 182
00007FF778677B1A  000000869E5FF380  MotionMaster::UpdateMotion+6A  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Movement\MotionMaster.cpp line 121
00007FF7786CA6A7  000000869E5FF3F0  Unit::Update+4A7  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Entities\Unit\Unit.cpp line 537
00007FF7787EDA0B  000000869E5FF5D0  Creature::Update+E6B  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Entities\Creature\Creature.cpp line 698
00007FF778AF29ED  000000869E5FF600  Acore::ObjectUpdater::Visit<Creature>+7D  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Grids\Notifiers\GridNotifiers.cpp line 346
00007FF7787478D5  000000869E5FF630  VisitorHelper<Acore::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >+15  C:\Servidor De Prueba\azerothcore-wotlk\src\common\Dynamic\TypeContainerVisitor.h line 51
00007FF77874774C  000000869E5FF680  Map::Visit<Acore::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >+8C  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Maps\Map.h line 879
00007FF77875FA26  000000869E5FF6F0  Map::VisitNearbyCellsOf+186  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Maps\Map.cpp line 735
00007FF77875EDE4  000000869E5FF8F0  Map::Update+234  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Maps\Map.cpp line 797
00007FF77875EB87  000000869E5FF920  InstanceMap::Update+17  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Maps\Map.cpp line 3028
00007FF778C69C62  000000869E5FF960  MapUpdateRequest::call+32  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Maps\MapUpdater.cpp line 45
00007FF778C6975C  000000869E5FF990  MapUpdater::WorkerThread+DC  C:\Servidor De Prueba\azerothcore-wotlk\src\server\game\Maps\MapUpdater.cpp line 158
00007FF778C6916F  000000869E5FF9C0  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+F  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\thread line 56
00007FFE0C6E6B4C  000000869E5FF9F0  _recalloc+5C
00007FFE0EE24DE0  000000869E5FFA20  BaseThreadInitThunk+10
00007FFE0EF9E40B  000000869E5FFAA0  RtlUserThreadStart+2B

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e2cfb5c5a95a38c278d76db8deecdb2596d543aa

[e2cfb5c](https://github.com/azerothcore/azerothcore-wotlk/commit/e2cfb5c5a95a38c278d76db8deecdb2596d543aa)

### Operating system

windows 10

**Comment by pklloveyou** [comment]
Attempt to remove https://github.com/azerothcore/azerothcore-wotlk/pull/15810
