### ISSUE TITLE
Illidan's bug

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15855]
### Current Behaviour

Illidan did not fly after entering p2, but walked on the ground, which was a mistake.

### Expected Blizzlike Behaviour

Illidan flew after entering p2, and dropped the Isenos blade to summon the Fireman.

### Steps to reproduce the problem

Don't know how to solve it

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

window server 2019

**Comment by heyitsbench** [comment]
This should be fixed with the recent rewrite.
