### ISSUE TITLE
Professor's bug at Icecrown Fortress

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15869]
### Current Behaviour

The position of the professor's refresh is incorrect, and the attack is not collapsing now, but it also does not lose blood

### Expected Blizzlike Behaviour

Kill the professor normally and continue with the subsequent boss

### Steps to reproduce the problem

I don't know how to handle it

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

WINDOW SERVER 2019

**Comment by yukijean** [comment]
![微信图片_20230407210811](https://user-images.githubusercontent.com/124695463/230614366-d14b744e-a836-4199-af3b-51f52f667fdd.png)
BOSS should not appear here, but on the experimental platform

**Comment by yukijean** [comment]
Got the problem

**Comment by yukijean** [comment]
@Tony931023 Would it be convenient for you to test the professor? It feels strange that he won't move during the transition phase

**Comment by Dr-Arayashiki** [comment]
> ![微信图片_20230407210811](https://user-images.githubusercontent.com/124695463/230614366-d14b744e-a836-4199-af3b-51f52f667fdd.png) BOSS should not appear here, but on the experimental platform

here it is normal, try a .die on it and then a .resp all to see if it returns to position
![image](https://user-images.githubusercontent.com/122452427/230678660-46b1736e-212a-40c7-997b-a20dfd89705a.png)

**Comment by yukijean** [comment]
@Dr-Arayashiki Did you stop when you killed the professor normally?

**Comment by yukijean** [comment]
@Dr-Arayashiki Did you stop when you killed the professor normally?

**Comment by Dr-Arayashiki** [comment]
> @Dr-Arayashiki Did you stop when you killed the professor normally?

I just arrived in the room and he was there, the fact is that I did the bosses before him, I didn't go straight to the room

**Comment by yukijean** [comment]
My boss position is normal now, but in the process of killing, the professor stopped at the turn stage, which felt strange.

**Comment by yukijean** [comment]
![微信图片_20230408203311](https://user-images.githubusercontent.com/124695463/230721325-c6310276-d373-411e-873c-2048b9602d1d.png)
@Dr-Arayashiki  When the professor is transitioning, he just stands here in a daze and doesn't have any skills. You can try again

**Comment by Dr-Arayashiki** [comment]
> ![微信图片_20230408203311](https://user-images.githubusercontent.com/124695463/230721325-c6310276-d373-411e-873c-2048b9602d1d.png) @Dr-Arayashiki When the professor is transitioning, he just stands here in a daze and doesn't have any skills. You can try again

you would have to consult a reliable source to confirm, but indeed in the current script the boss hangs for a while on transition and attacks again.
