### ISSUE TITLE
[Gruul's Lair] High King Maulgar: Krosh Firehand spells

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#15866]
originally reported by balleny at: https://github.com/chromiecraft/chromiecraft/issues/4873
also reported by NinesCC at: https://github.com/chromiecraft/chromiecraft/issues/5345

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

![image](https://user-images.githubusercontent.com/123340833/230521145-19dc45c4-eb74-4758-a454-ac50747b5b5b.png)

Krosh Firehand is the NPC to the far right. It's meant to be tanked by a mage. Currently his spells Fireball and Spell Shield have a few issues:

**Fireball** 
The damage calculation is set at the moment the fireball is cast, regardless of having or not Spell Shield when it lands.

Description of how the fight develops currently:
- Mage Pulls and starts the encounter
- Krosh casts 1st fireball, it travels and hits the mage for 10k.
- Krosh casts 2nd fireball, travels. Krosh then casts Spell Shield and here Mage spell steals it. Fireball still hits for 10k regardless of Spell Shield buff on the tank. 

**Spell Shield**
Krosh's time between Spell Shield casts is too far apart.
After the Spell Shield buff expires, Krosh will recast the Spell Shield on himself after the 4th fireball cast while the mage has no shield. That combined with the Fireball behavior described before, means the mage takes 4 full damage fireballs.

### Expected Blizzlike Behaviour

**Fireball**
- Krosh should never open with fireball.
- Fireball damage should be reduced when it lands on the target with the Spell Shield buff
- Full damage only when it lands with the target with no Spell Shield buff

**Spell Shield**
- It should be the first spell Krosh casts upon pull.
- Should reduce magic damage taken by 75% whenever the buff is active
- When Spell Shield Fades, the next one should be only 1 Fireball apart. In other words: it should be recast at 30 second intervals approximately.

### Source

TBC Classic Footage
https://youtu.be/AJdLBp02KPs?t=14

Original TBC Footage
https://youtu.be/gqhS0qqqv1s?t=60

Another Original TBC Footage example
https://youtu.be/ZcgMzrI70FE?t=13

- Mage pulls, Krosh runs to the mage while casting Spell Shield, then proceeds to cast Fireball.
- When Spell Shield Fades, the next one is only 1 Fireball apart.

Mechanics
https://wowpedia.fandom.com/wiki/High_King_Maulgar

### Steps to reproduce the problem

1. teleport gruul
2. pull Krosh
3. watch his behavior

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
has already been reported and worked on here:
https://github.com/chromiecraft/chromiecraft/issues/4873

**Comment by elthehablo** [comment]
> 

fixed

**Comment by elthehablo** [comment]
> has already been reported and worked on here: [chromiecraft/chromiecraft#4873](https://github.com/chromiecraft/chromiecraft/issues/4873)

yeah I edited the labels. your report is referenced now
