### ISSUE TITLE
Gob Move command not refreshing Gobject position to players [$20]

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#1588]
**SMALL DESCRIPTION:**
```
.gobject move GUID X Y Z
```
Doesn't refresh gobject position to players in zone.
Players must relog to see changes.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Players should'nt have to relog to see gameobject updated coords.

**STEPS TO REPRODUCE THE PROBLEM:**
1. Add a new gameobject using `.gob add` command
2. Go away from the spawned gameobject
3. Use `.gps` to have other X Y Z position
4. Move the spawned gameobject using `.gob move GUID X Y Z`
5. Observe that the gameobject's position haven't been updated to the client
6. Relog
7. Observe that the gameobject's position have been updated

**EXTRA NOTES:**
You can watch the video that describes the problem : 
https://mega.nz/#!450VECyZ!43iY4JWQzg2ICgdetG26LeS4K3YHT8EZXKQFOCyDAtk

I think the .gob turn command could have the same issue.

**BRANCH(ES):**
master

**AC HASH/COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/a7b4c909f3f27c729633983b7cee8ad30b058863

##### OPERATING SYSTEM:
Windows10

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by gboisen** [comment]
I know this currently works on TrinityCore

https://github.com/TrinityCore/TrinityCore/issues/21729

Heres the fixed issue from theirs that might help someone find a fix

**Comment by FrancescoBorzi** [comment]
Maybe one of those two commits fixes the issue:

- https://github.com/TrinityCore/TrinityCore/commit/0a0312b705ecb1a318fd3abe545b571a3a349a9c
- https://github.com/TrinityCore/TrinityCore/commit/38e05e33a84fe1081f0f00f4b522bb077b600943

**Comment by gengarshadowball** [comment]
These commits are the fix but their gameobjects are much more complex and include quartenion vectors so, to include these fixes one would need to import a big majority of their gameobject structure.

**Comment by FrancescoBorzi** [comment]
@gengarshadowball I see. Let's avoid creating bg PRs. Let's import stuff in small pieces, whenever possible.

**Comment by gengarshadowball** [comment]
I'll see how we can break this down in small pieces then, is it ok to try to implement quartenion for gobs?

**Comment by Yehonal** [comment]
> These commits are the fix but their gameobjects are much more complex and include quartenion vectors so, to include these fixes one would need to import a big majority of their gameobject structure.

Could you point me the commit where they introduced the quartenion?

**Comment by Yehonal** [comment]
Anyway, the fix is essentially here: https://github.com/TrinityCore/TrinityCore/commit/38e05e33a84fe1081f0f00f4b522bb077b600943

The trick is to temporary despawn and respawn the object to update the client

**Comment by Rochet2** [comment]
> The trick is to temporary despawn and respawn the object to update the client

And important to note that the object will need a new guid. From the linked commit:

> // Generate a completely new spawn with new guid
 // 3.3.5a client caches recently deleted objects and brings them back to life
 // when CreateObject block for this guid is received again
 // however it entirely skips parsing that block and only uses already known location

**Comment by gengarshadowball** [comment]
I've search for it and didn't find anything, just this old commit on G3D:
https://github.com/TrinityCore/TrinityCore/pull/14146

**Comment by JamesGent** [comment]
Unclaimed bounty available here for anyone who wants to fix this. Lots of TC reading material available to help someone fix this.

**Comment by FrancescoBorzi** [comment]
added 15$ more to the bounty, so it's currently 20$ in total

**Comment by UltraNix** [comment]
The problem with saving comes from here: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/GameObject/GameObject.cpp#L278
```
// xinef: hackfix - but make it possible to use original WorldRotation (using special gameobject addon data)
// pussywizard: temporarily calculate WorldRotation from orientation, do so until values in db are correct
if (addon && addon->invisibilityType == INVISIBILITY_GENERAL && addon->InvisibilityValue == 0)
    SetWorldRotation(rotation);
else
    SetWorldRotationAngles(NormalizeOrientation(GetOrientation()), 0.0f, 0.0f);
```
If there is no `addon` entry, gameobject will always calculate its rotation based on orientation.
