### ISSUE TITLE
Localization Ruru

### ISSUE THREAD

**Issue by igorkur** [azerothcore/azerothcore-wotlk#159]
Good time of day . Powered by core localization Ruru.

Thank you !

**Comment by DevRival** [comment]
Вырезано все, хотя делается легко) Добавил broadcasttext и все стало идеально)

**Comment by igorkur** [comment]
class BroadcastTextBuilder 
Вы про это ?

**Comment by DevRival** [comment]
И не только, там все связанно с npc_text, creature_text и так далее.

**Comment by igorkur** [comment]
Суть ясна что как здесь https://bitbucket.org/pak3935/sunwellcore/commits/db58f8ae1a4942622b368840aee474787a528a6f

**Comment by DevRival** [comment]
О нет, тут натыкано все что надо и нет. И база не та, я вручную переписывал все столбцы.

**Comment by igorkur** [comment]
А у вас есть код на локализацию ?

**Comment by DevRival** [comment]
Да полностью все.

**Comment by igorkur** [comment]
А вы не могли бы поделится ?

**Comment by DevRival** [comment]
Нет, это приват разработка.

**Comment by igorkur** [comment]
Ясно все с вами =)

**Comment by ShinDarth** [comment]
@igorkur @DevRival  please our [chat](https://gitter.im/azerothcore/azerothcore) or our [forum](http://azerothcore.altervista.org/forum/) to discuss, this is the issue tracker and it is supposed to be used only for bug reporting
