### ISSUE TITLE
[Priest] Shadowfiend damage too high

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15906]
https://github.com/chromiecraft/chromiecraft/issues/5381
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Shadowfiends damage is extremly high compared to wotlk classic ptr damage

hits without spellpower (30 cause of talents) range from 230 to 480
![WoWScrnShot_041023_122429](https://user-images.githubusercontent.com/12682004/230884303-2ac76ddf-7457-4609-91d4-fd7c5fbbb90e.jpg)

with 492 spellpower range from 420 to 583
![WoWScrnShot_041023_123713](https://user-images.githubusercontent.com/12682004/230886173-604bc823-719e-4724-bf52-593910825a76.jpg)

### Expected Blizzlike Behaviour

damage on ptr with 30 spellpower range from 129 to 165
![Screenshot_20230410_123338](https://user-images.githubusercontent.com/12682004/230885642-d23afb8d-1b5a-4dd9-82de-1ddc007a7b28.png)

with 500 spellpower (the 641 is a crit) range from 310 to 360
![Screenshot_20230410_123444](https://user-images.githubusercontent.com/12682004/230885741-bfdb19ec-789c-4c9f-b6ce-67d170afa068.png)

### Source

https://wowgaming.altervista.org/aowow/?spell=34433
shows a scaling of 65%, likely based on the comment in wowhead:

https://www.wowhead.com/wotlk/spell=34433/shadowfiend#comments:id=155304
> Benefits from your +dmg with a ~65% coefficient (6.5% per hit)

but, patchnotes on wowwiki show:
https://wowpedia.fandom.com/wiki/Shadowfiend
> Wrath of the Lich King [Patch 3.1.0](https://wowpedia.fandom.com/wiki/Patch_3.1.0) (2009-04-14): Health scaling increased. Now receives 30% of the master's spell power.

### Steps to reproduce the problem

.

### Extra Notes

talents used
![WoWScrnShot_041023_122253](https://user-images.githubusercontent.com/12682004/230883963-194298b0-0513-4c56-b46f-77cc82f7bcd2.jpg)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
hi @Tereneckla why those this closed? i dont see a linked PR / fix, and also wasnt able to locate any in close timely proximity to the 10th of April
https://github.com/azerothcore/azerothcore-wotlk/pulls?page=1&q=is%3Apr+is%3Aclosed+merged%3A2023-04-03..2023-04-11

**Comment by heyitsbench** [comment]
Closed as a duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/15905.

**Comment by balleny** [comment]
ah, ok gotcha. that also explains why https://github.com/chromiecraft/chromiecraft/issues/5381 was still open
