### ISSUE TITLE
ICC/ Sindragosa BUG

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#15917]
### Current Behaviour

It is wrong for Sindragosa to disappear and then slowly fly down from the world after leaving the war or the group is destroyed

### Expected Blizzlike Behaviour

When Sindragosa withdraws from the war or the group is destroyed, it should directly stand on the platform and go online, rather than re coming down from the sweet mouth

### Steps to reproduce the problem

I don't know how to handle it

### AC rev. hash/commit

AzerothCore rev. fd6941de7c7e+ 2023-04-09 23:44:52 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.78.0
Using MySQL version: 80032
Using CMake version: 3.26.0-rc1
Compiled on: Windows 10.0.17763
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Build/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Build/bin/RelWithDebInfo/data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-autobalance
- mod-eluna
- mod-weekend-xp

### Operating system

WINDOWS SERVER 2019

**Comment by Nyeriah** [comment]
This isn’t what happens on retail
