### ISSUE TITLE
[Hunter] Snake Trap

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15910]
https://github.com/chromiecraft/chromiecraft/issues/5357
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour
Damage against a target with 4641 Armor as a level 70 hunter
![image](https://user-images.githubusercontent.com/50233983/230974118-84a91721-ff66-4719-9e8d-9b1a4c7c3a19.png)
![image](https://user-images.githubusercontent.com/50233983/230974160-e31c86c1-ad96-47e9-bad8-cddef8cb3e6f.png)

They follow the hunter as sort of guardians
They count as pets and get damage bonuses from the beast mastery talents

### Expected Blizzlike Behaviour

These values probably are for level 80
Vipers hit for ~38-53 damage
Venomous Snakes hit for ~16-24 damage

Overall I'd say Vipers should deal ~1/5th of the current damage and Venomous Snakes 1/10th

They guard the original trap placement area when there is nothing to attack around
beast mastery talents have no influence

### Source

Looks like a lvl 73 hunter:
Snakes hits are ~12-14 and ~25-30
https://youtu.be/ULZYl0cVMlc
https://wowpedia.fandom.com/wiki/Snake_Trap?oldid=2341652

You can see them head back to the trap placement area here
https://youtu.be/ULZYl0cVMlc?t=200
https://youtu.be/ULZYl0cVMlc?t=214

On wotlk classic at level 70:
![image](https://user-images.githubusercontent.com/50233983/230973816-fb0d9f54-74d7-42c8-8dc2-41f18c7ef2d3.png)
![image](https://user-images.githubusercontent.com/50233983/230972802-6505ec79-5868-428f-9cf6-e94d8db5fdde.png)
![image](https://user-images.githubusercontent.com/50233983/230972807-d9961631-4bc3-493a-9292-322dbf64b9ca.png)
![image](https://user-images.githubusercontent.com/50233983/230972819-ff13cb66-cfec-485e-8e8b-5ab8fe2c18d2.png)

With 4641 Armor at level 70 that base damage means;
Venomous Snake 9-11 -> 21-26 damage per hit
Viper: ~20 -> ~47 damage per hit

### Steps to reproduce the problem

.cast 34600

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=19833
https://wowgaming.altervista.org/aowow/?npc=19921
https://wowgaming.altervista.org/aowow/?spell=34600

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by minthes** [comment]
Snake Trap is completely broken right now in pvp.
I wonder if it's possible to make this issue a priority.

**Comment by heyitsbench** [comment]
Beast Lore info for these creatures onClassic PTR:
Level 70
[Venomous Snake](https://wowgaming.altervista.org/aowow/?npc=19833): [Data](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/61b4d779-0c14-43c7-85ef-441d13e4348e)
[Viper](https://wowgaming.altervista.org/aowow/?npc=19921): [Data](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/dc4d97b8-746d-477f-991b-01acf4e45959)
Level 80
[Venomous Snake](https://wowgaming.altervista.org/aowow/?npc=19833): [Data](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/7e237c49-2ccd-4f47-95d9-6a3287d9b011)
[Viper](https://wowgaming.altervista.org/aowow/?npc=19921): [Data](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/f06681aa-2275-4943-974e-935223a98e25)
