### ISSUE TITLE
[Rogue] Distract interrupts spell casts

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15913]
https://github.com/chromiecraft/chromiecraft/issues/5385
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Distract interrupts spell casts

### Expected Blizzlike Behaviour

Distract does not interrupt spell casts

### Source

Rogues don't need yet another CC

No mention anywhere that it does
https://www.wowhead.com/wotlk/spell=1725/distract#comments
https://wowwiki-archive.fandom.com/wiki/Distract

This one even says a targeted spellcast gets "interrupted" because the caster is facing another direction at the end of the cast, not because of Distract itself
https://www.wowhead.com/wotlk/spell=1725/distract#comments:id=2746339

### Steps to reproduce the problem

2 Chars
Cast one reasonably long spell with the first one
Use Distract from the other Char

For example:
.cast 688    (Summon Imp)

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=1725

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by balleny** [comment]
also interrupts the capturing of flags in arathi basin and alterac valley battlegrounds

**Comment by Tereneckla** [comment]
Which is a spellcast, so I didn't specifically mention it

**Comment by balleny** [comment]
maybe. it used to be "opening" of an object some time in the past iirc

**Comment by laasker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellEffects.cpp#L2704

i believe a fix would be to add " | UNIT_STATE_CASTING" 
after 
'if (unitTarget->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_STUNNED | UNIT_STATE_FLEEING'

**Comment by Kitzunu** [comment]
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellEffects.cpp#L2704
> 
> i believe a fix would be to add " | UNIT_STATE_CASTING" after 'if (unitTarget->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_STUNNED | UNIT_STATE_FLEEING'

No, this will cause distract to not work on anyone casting. Which is wrong.

**Comment by Kitzunu** [comment]
Issue due to 
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellEffects.cpp#L2707
```cpp
unitTarget->SetFacingTo(unitTarget->GetAngle(destTarget));
```

This causes two issues
1. interrupts cast
2. interrupts walking.

Distract should only change your direction, even in movement. In cata the spell was changed to stop movement.

**Comment by laasker** [comment]
> No, casting units also should change facing direction



> > https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellEffects.cpp#L2704
> > i believe a fix would be to add " | UNIT_STATE_CASTING" after 'if (unitTarget->HasUnitState(UNIT_STATE_CONFUSED | UNIT_STATE_STUNNED | UNIT_STATE_FLEEING'
> 
> No, this will cause distract to not work on anyone casting. Which is wrong.

Oh my bad, i didnt think about that
