### ISSUE TITLE
[Dungeon] Culling Of Stratholme does not start the event

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15912]
### Current Behaviour

Upon reaching the entrance and talking to Arthas, the event should start, Arthas does nothing, he remains standing in the same place

### Expected Blizzlike Behaviour

it should start the event without any problem

### Steps to reproduce the problem

1. enter Dungeon Culling Of Stratholme

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/c9973f3a80b19efc67fa441e66adbf9e0d3a7c6d

### Operating system

Ubuntu 20.04

**Comment by Tony931023** [comment]
@Nyeriah Do you think you can help us with this? I would greatly appreciate it

**Comment by Sedatyf** [comment]
Hi @Tony931023,
Thank you for your bug ticket. But with the AzerothCore revision 49820e475e63 I could start the dungeon. You first need to speak to Chromie in the inn's basement, dispel 5 "Plagued Grain Crates" then speak to Chromie again at the entrance of Stratholme.
![image](https://user-images.githubusercontent.com/59012307/233097644-1b5c297a-223f-4f92-8e69-3675872e00d7.png)
![image](https://user-images.githubusercontent.com/59012307/233097838-4fdcba85-2919-42a0-9157-ffc6af669db8.png)

**Comment by Tony931023** [comment]
Yes, after I updated to a later version and the dungeon started normally, I had forgotten to close the issues thanks @Sedatyf
