### ISSUE TITLE
[Pet/ICC] Vile Spirit only attacks pets

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/azerothcore-wotlk#15911]
### Current Behaviour

in the 3rd phase of the fight against Arthas Vile Spirit only attacks pets and not players

### Expected Blizzlike Behaviour

should attack random players

### Steps to reproduce the problem

1- go ICC
2 - go Arthas

### Extra Notes

https://youtu.be/vyW1ceHyhBo

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/c9973f3a80b19efc67fa441e66adbf9e0d3a7c6d

### Operating system

Ubuntu 20.04

**Comment by smellbee** [comment]
confirmed,  this is a long existed bug

not only the Vile Spirit, but including lots of summoned creatures

such as Toravon the Ice Watcher, frozen orb, when summoned, it seeks pet for first priority,

lich king, phase 1:  
summoned SHAMBLING HORRO  and  DRUDGE GHOUL
attack pet only when summoned.

it actually breaks the fight process

**Comment by smellbee** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/15585

**Comment by smellbee** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/15559

**Comment by tabooo** [comment]
Still bug
