### ISSUE TITLE
[Paladin] Seal of Command/Corruption deal too much damage (again)

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#15925]
### Current Behaviour

220*0.36 = 79
Seal of Command hits for 94
![image](https://user-images.githubusercontent.com/50233983/231539003-2b025d78-9617-4997-ae70-4b5a78a77770.png)

220*0.33 = 72.6
Seal of Corruption hits for 86
![image](https://user-images.githubusercontent.com/50233983/231539156-113f08b8-1dc7-46d6-988f-074a07544acb.png)

### Expected Blizzlike Behaviour

Seal of Command deals 36% of weapon damage
Seal of Corruption deals 33% of weapon damage

### Source

...

### Steps to reproduce the problem

.learn 20375
.learn 53736
Unequip your weapon for low variance in the damage
Use the Seal, attack a dummy

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=20375
https://wowgaming.altervista.org/aowow/?spell=53736
https://wowgaming.altervista.org/aowow/?spell=31801

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/539801377fb96f2c3377e051fa9264315501fd1e

### Operating system

Windows 10

**Comment by Tereneckla** [comment]
They also still double dip on the percentage damage increases -> https://github.com/azerothcore/azerothcore-wotlk/issues/14988

**Comment by Tereneckla** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/15193 causes this surplus damage

**Comment by pklloveyou** [comment]
It's really too high

**Comment by kokotivyjebani** [comment]
If we average the damage (911-1113 =~ 1012) and calculate the average hit of SoC (353) to the equation, we get the percental damage of SoC on target dummy level 70 (unbuffed).

**(353/1012)x100 = 34.88%**

SoC is supposed to do 36% of mw damage. This is based on 77 hits so there may be a little deviation (1.12% to be exact).

How is it not working properly?

![SoC Chromie](https://user-images.githubusercontent.com/130693107/231838010-272a2cd8-8819-46d3-99ea-2280ef899edb.jpg)
