### ISSUE TITLE
[Bug report]: (Naxxramas，patchwerk boss will not automatically patrol)

### ISSUE THREAD

**Issue by luoxiao5566** [azerothcore/azerothcore-wotlk#15937]
### Describe the bug

In the Naxxramas dungeon，patchwerk boss requires players to actively approach the player's visible range before starting a battle in order to automatically patrol。

### To reproduce

1.Go to 'Naxxramas'
2.Move to the patchwerk boss room and wait for the boss to patrol within your line of sight (the boss will never come, you need to approach the boss)

### Expected behavior

There is no need for players to trigger the automatic patrol of the B boss, it will patrol on its own on a fixed route。

### Desktop

Windows

### Smartphone

AzerothCore rev. af05a8ba6a43 2023-04-07 14:10:05 -0300 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by Helias** [comment]
issue transferred to the right repository

**Comment by Kitzunu** [comment]
Add hash or it will be closdd

**Comment by luoxiao5566** [comment]
> Add hash or it will be closdd

How to add  hash

**Comment by Si1ker** [comment]
Naxxramas related = assign to me
