### ISSUE TITLE
Trigger Creatures with more than 1 model are visible.

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#15932]
### Current Behaviour

If a trigger creature has more than 1 model, it causes the 2nd one to be visible.

https://user-images.githubusercontent.com/46330494/231692668-d127cda7-32b3-41ec-8853-dbc6640e4add.mp4

### Expected Blizzlike Behaviour

Kitzunu's comment below.

### Source

https://www.youtube.com/watch?v=d3UGjMSl5eI&t=128s

### Steps to reproduce the problem

.go c id 22798
Toggle GM mode

### Extra Notes

https://www.wowhead.com/wotlk/npc=22798/dnd-prophecy-1-quest-credit#models

### AC rev. hash/commit

ea82506a25162fbccd8fe789481e22da99b3ef7c

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
Partially true. ModelId1 should be a visible model for GMs, ModelId2 should be an invisible model for players

```cpp

                    if (cinfo->flags_extra & CREATURE_FLAG_EXTRA_TRIGGER)
                    {
                        if (target->IsGameMaster() && AccountMgr::IsGMAccount(target->GetSession()->GetSecurity()))
                        {
                            if (cinfo->Modelid1)
                                displayId = cinfo->Modelid1;    // Modelid1 is a visible model for gms
                            else
                                displayId = 17519;              // world visible trigger's model
                        }
                        else
                        {
                            if (cinfo->Modelid2)
                                displayId = cinfo->Modelid2;    // Modelid2 is an invisible model for players
                            else
                                displayId = 11686;              // world invisible trigger's model
                        }
                    }
                }
```

**Comment by Kitzunu** [comment]
I mean we could hackfix it coreside kek

**Comment by avarishd** [comment]
Yes, we should and I wouldn't even call it a hackfix. 
https://github.com/azerothcore/azerothcore-wotlk/pull/17309
.go c id 17168

**Comment by heyitsbench** [comment]
Could implement display probabilities. 👀

**Comment by Kitzunu** [comment]
the fuck is that 👀

**Comment by heyitsbench** [comment]
> the [expletive] is that 👀

https://github.com/azerothcore/azerothcore-wotlk/issues/5463

**Comment by chaosua** [comment]
so the main bug is described there https://github.com/azerothcore/azerothcore-wotlk/issues/15932
