### ISSUE TITLE
[Bug report]: (Naxxramas，the helper summoned by boss Gothik will not actively attack)

### ISSUE THREAD

**Issue by luoxiao5566** [azerothcore/azerothcore-wotlk#15936]
### Describe the bug

In the dungeon of Naxxramas, the helper summoned by boss Gothik will not actively attack, and the same applies when the gate opened。

### To reproduce

1.Go to 'Naxxramas'
2.Start Gothik  battle

### Expected behavior

the helper summoned by boss Gothik can actively attack, and the same applies when the gate opened。

### Desktop

Windows

### Smartphone
AzerothCore rev. af05a8ba6a43 2023-04-07 14:10:05 -0300 (master branch) (Win64, RelWithDebInfo, Static)

**Comment by Helias** [comment]
issue transferred to the right repository

**Comment by Nyeriah** [comment]
@Helias the exact same issue was transferred 5 times

**Comment by Kitzunu** [comment]
Add hash or it will be closed

**Comment by Si1ker** [comment]
Naxxramas related = assign to me
