### ISSUE TITLE
Kirin'Var Ghost spell Soulbind not working as intended

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#15945]
Original issue: https://github.com/chromiecraft/chromiecraft/issues/4950

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

65-69

### Current Behaviour

Currently Soulbind cast from a Kirin'Var Ghost reflects zero damage.
![WoWScrnShot_041423_092636](https://user-images.githubusercontent.com/82369562/231974091-f71d79c8-326b-4859-9a21-2f9499a139da.jpg)

### Expected Blizzlike Behaviour

It should be reflecting 50% of all incoming damage back.

### Source

Video of someone fighting two of the mobs at the timestamp linked (00:52):
https://youtu.be/hUMNJMuTZ8I?t=52

The player absorbs reflected damage at 1:06

### Steps to reproduce the problem

`.go c 84257`
Damage a Kirin'Var Ghost until it casts soulbind on you
Continue inflcting damage on it and check combat logs to see zero reflected damage

### Extra Notes

These mobs should also be spawned in and replacing the Tormented Souls once the Tormented Souls are aggro'd

Kirin'Var Ghost: https://wowgaming.altervista.org/aowow/?npc=20480
Tormented Soul: https://wowgaming.altervista.org/aowow/?npc=20512
Soulbind: https://wowgaming.altervista.org/aowow/?spell=36141

### AC rev. hash/commit

539801377fb9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Also *some* (mangos-wotlk db) [Tormented Citizens](https://www.wowhead.com/wotlk/npc=21065/tormented-citizen#comments) should transform into [Ghosts](https://www.wowhead.com/wotlk/npc=20480/kirinvar-ghost#comments) and [Spectres](https://www.wowhead.com/wotlk/npc=20496/kirinvar-spectre#comments). Needs to be checked on live.
https://youtu.be/s7hvoujn_d0?t=29
