### ISSUE TITLE
[Karazhan] Spectral Performer are not immune to all crowd control and taunts

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#15972]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Not immune to all crowd control and taunts

### Expected Blizzlike Behaviour

immune to all crowd control and taunts

### Source

![image](https://user-images.githubusercontent.com/11332559/232295587-cc138087-bdde-4760-b373-42e4c714580c.png)

https://www.wowhead.com/tbc/npc=16473/spectral-performer#comments

### Steps to reproduce the problem

 .npc add 16473

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/00e42645b8b6

### Operating system

Linux Mint 21.1

### Customizations

None

### Server

Local

**Comment by Si1ker** [comment]
@BeefSteaker remember to include somewhere the link between issues:

" Originally reported at https://github.com/chromiecraft/chromiecraft/issues/5426 "
