### ISSUE TITLE
[Shadow Labyrinth] Boss Spell Timers

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#15971]
### Current Behaviour

.

### Ambassador Hellmaw

ID - 33547 Fear: 23-33s
ID - 33551 Corrosive Acid: 23050-30350
ID - 26662 Berserk: 3min

### Blackheart the Inciter

Note: Incite Chaos re-schedules timers since combat is dropped

ID - 33676 Incite Chaos: First 24s Repeat 50-70s
ID - 33707 War Stomp: 16950-26350
ID - 33709 Charge: 30-50s

### Vorpil

ID - 33841 Shadow Bolt Volley: 9700ms-20s
ID - 38791 Banish: 17-28s
ID - 33563 Draw Shadows: First 36400ms Repeat: 36400-44950ms
ID - 39363 Rain of Fire: 1s after Draw Shadows
ID - 33618 Great Sacrifice: On Death

### Murmur

ID - 33657 Resonance: First 5s, Repeat 6-18s
ID - 33711 Murmur's Touch: 14600-25500ms
ID - 33923 Sonic Boom: First 28s, Repeat 34-40s
ID - 39365 Thundering Storm: First 5s, Repeat 6050ms-10s
ID - 38797 Sonic Shock: 3650-9150ms

### Steps to reproduce the problem

.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/527eaa10bf10b85d95867b48190f49dbf1a87f02

### Operating system

Windows 10

**Comment by elthehablo** [comment]
are any of these different on heroic?
