### ISSUE TITLE
wow client login stuck at conneting

### ISSUE THREAD

**Issue by yonggangding** [azerothcore/azerothcore-wotlk#15980]
### Current Behaviour

I cloned the Acore-wotlk(4fa75f3), installed required tools, complied and built all source codes, set up sql database step by step. Everything works well until I start MySql->Authserver.exe->worldserver.exe and login, it stcuked at conneting. I checked the crash folder and find a message bellow:

*************************************************************
Physical Memory: 16449800 KB (Available: 6413096 KB)
Commit Charge Limit: 33227016 KB

*** Operation System ***
Windows 10 Professional (Version 10.0, Build 19045)
```
//=====================================================
Exception code: C0000420 assertion error。

Assertion message: #----------------------------------------------------------------------#
 
>> ASSERTION FAILED

# Location 'C:\Users\yonggang.ding\Downloads\AzerothCore\repos\azerothcore-wotlk\src\common\Cryptography\ARC4.cpp:31'
# Function 'Acore::Crypto::ARC4::ARC4'
# Condition 'result == 1'
 
#----------------------------------------------------------------------#

```
### Expected Blizzlike Behaviour

connect correctly

### Steps to reproduce the problem

1. clone acore-wotlk repo
2. complie and build
3. launch mysql, authserver and worldserver

### AC rev. hash/commit

[527eaa10bf10_worldserver.exe_[17-4_14-32-35].txt](https://github.com/azerothcore/azerothcore-wotlk/files/11247540/527eaa10bf10_worldserver.exe_.17-4_14-32-35.txt)

### Operating system

Win10 X64

**Comment by yonggangding** [comment]
> > What version open ssl are you using?
> 
> If you are using 3.0 then please copy over the legacy.dll file over to the folder where the worldserver.exe is at.

yeah, open ssl 3.0 x64 version was used, I did copy the legacy.dll to the folder where the worldserver.exe is at.
![1](https://user-images.githubusercontent.com/27206370/232644548-f7b1f1a4-5014-4eba-ac04-1ac9f2af1b2d.png)

**Comment by yonggangding** [comment]
> > > What version open ssl are you using?
> > 
> > 
> > If you are using 3.0 then please copy over the legacy.dll file over to the folder where the worldserver.exe is at.
> 
> yeah, open ssl 3.0 x64 version was used, I did copy the legacy.dll to the folder where the worldserver.exe is at. ![1](https://user-images.githubusercontent.com/27206370/232644548-f7b1f1a4-5014-4eba-ac04-1ac9f2af1b2d.png)

interesting, I re-copy the legacy.dll again, it works well now， thanks for you help.

**Comment by yonggangding** [comment]
> > What version open ssl are you using?
> 
> If you are using 3.0 then please copy over the legacy.dll file over to the folder where the worldserver.exe is at.

interesting, I re-copy the legacy.dll again, it works well now， thanks for you help.

**Comment by alexpec1** [comment]
After I changed WIN11 to WIN10, I also used Mysql8.1 version, and after compiling, I was also stuck in the login screen, the same prompt as you, and after a while, worldserver crashed, which bothered me all day. I just saw the answer above, I went to the bin folder of OPENSSL under the C drive and copied the legacy.dll over and it worked, the legacy.dll I downloaded from the internet and put it in didn't work, thanks to you guys.
