### ISSUE TITLE
(Spells): Magic Rooster is castable while mounted.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15985]
### Current Behaviour

[Magic Rooster](https://wowgaming.altervista.org/aowow/?spell=65917) is castable while mounted.

### Expected Blizzlike Behaviour

This mount should not be castable while mounted.

### Source

Assumption, but it seems likely that it would have been mentioned somewhere, like Wowhead comments if it was.

### Steps to reproduce the problem

1. `.additem 49290`, `.additem 8631`
2. Learn the mounts.
3. Cast the saber mount.
4. Cast the rooster mount.
5. Observe both mounts active.

### Extra Notes

There is an [open PR](https://github.com/TrinityCore/TrinityCore/pull/28902) for TC's 3.3.5 branch to remove this flag.

### AC rev. hash/commit

9fcacc5c06910305e0175445f486aca77a9e7c92

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
This apparently [is a blizzlike bug that was found during retail Wrath](https://www.wowhead.com/wotlk/item=49290/magic-rooster-egg#comments:id=929888), no idea if this is a case we want to correct.

CC: @Kitzunu

**Comment by Kitzunu** [comment]
harmless bug
