### ISSUE TITLE
(DB/Dungeons): The Black Morass has incorrect quest requirement.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15987]
### Current Behaviour

The Black Morass dungeon requires the quest "Return to Andormu" in order to enter.

### Expected Blizzlike Behaviour

The dungeon should only require "The Caverns of Time" to enter.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.tele cavernsoftime`
2. `.quest add 10279`, `.quest add 10277`
3. `.quest reward 10279`, `.quest reward 10279`
4. Enter The Black Morass.
5. Observe you cannot.

### AC rev. hash/commit

9fcacc5c06910305e0175445f486aca77a9e7c92

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Si1ker** [comment]
Invalid

![image](https://user-images.githubusercontent.com/61223313/233216821-ab73cb9a-1338-415c-8f8e-8532e705ff43.png)
https://www.wowhead.com/tbc/quest=10285/return-to-andormu#comments:id=5177320

------------------

![image](https://user-images.githubusercontent.com/61223313/233217108-aee5f0e0-2106-4380-bef2-c525e060c6de.png)
https://www.wowhead.com/tbc/guide/attunement-dungeons-raids-burning-crusade-classic#6-the-black-morass

------------------

don't this..
![image](https://user-images.githubusercontent.com/61223313/233217268-121939ce-c1fd-4720-ade1-f089b1961b5f.png)

**Comment by heyitsbench** [comment]
> don't this..

Most of the time it's a well enough source.
