### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by iMerdjaoui** [AzerothCore/azerothcore-wotlk#16]
Hello,
I got this error : 
```
CMake Error at modules/dep/mysqllite/CMakeLists.txt:257 (add_version_info):
  Unknown CMake command "add_version_info".
```
Cmake version : 3.6.0-rc2
Compiling on windows server 2012

**Comment by Bodeguero** [comment]
@iMerdjaoui i compile on Linux and Windows - the mistakes that I've had I fixed missing now send to my [GitHub](https://github.com/Bodeguero/AzerothCore_3.3.5)! 

Look:
AuthServer:
![logo](http://image.prntscr.com/image/698bfceeaf3848d692e20016494f7c3c.jpg)

WorldServer:
![logo](http://image.prntscr.com/image/d483e678e3f24815ac84bcae4a6a9cce.jpg)

I hope the community like! :facepunch: 

PS: Forgive me for the mistakes in English - I use the Google translator :innocent:

**Comment by Yehonal** [comment]
Is this problem still persist on latest revision?

**Comment by iMerdjaoui** [comment]
Yes, sadly.

**Comment by Bodeguero** [comment]
@iMerdjaoui Could send the complete log of the error?
