### ISSUE TITLE
[QUEST] DK Zone - Into the Realm of Shadow 

### ISSUE THREAD

**Issue by diluh** [azerothcore/azerothcore-wotlk#1601]
**Description:**

Into the realm of shadows = id 12687
does not have the target to catch the horse.

**Current behaviour:** 
target of the horse and the warrior becomes enemy and we can not get on the horse

**Expected behaviour:** The DK must attack the horse and when the creature on top of the horse dies, the DK must pick up the horse
https://www.youtube.com/watch?v=AFcO8U9wlfM

**Steps to reproduce the problem:**

do quest
Branch(es): Master

**AC hash/commit:** https://github.com/azerothcore/azerothcore-wotlk/commit/c53437bc759662f51230495e5cc069c1d280679b

**Operating system:** Ubuntu server 18.04 LTS

Modules: Are you using modules? if yes, list them
Not
Other Customizations: Are you using any core/db patches or other customizations? If yes please specify them here.
Not

**Comment by poszer** [comment]
You have to kill the rider, and take he's horde. Just tested this, the quest is working fully.
Just like the quest say : 

> Salanar the Horseman at Death's Breach has challenged you to slay the Dark Rider of Acherus and take his Acherus Deathcharger.

So, kill Dark Rider, and after that take he's horse, and finish quest.

Images while doing quest : 
![download (1)](https://user-images.githubusercontent.com/41213210/54791719-571fe400-4c3b-11e9-8608-65b60fbd6c5b.png)
![download (2)](https://user-images.githubusercontent.com/41213210/54791720-571fe400-4c3b-11e9-8290-5ffa0d2c6af6.png)
![download (3)](https://user-images.githubusercontent.com/41213210/54791721-57b87a80-4c3b-11e9-9d32-c1f5e8944d40.png)
![download (4)](https://user-images.githubusercontent.com/41213210/54791722-57b87a80-4c3b-11e9-866a-d6b81405dbc0.png)
![download](https://user-images.githubusercontent.com/41213210/54791723-57b87a80-4c3b-11e9-8c46-a18532fd0503.png)

Closing this.
