### ISSUE TITLE
command .guid  BUG

### ISSUE THREAD

**Issue by 127y** [azerothcore/azerothcore-wotlk#16017]
### Current Behaviour

command .guid  BUG

### Expected Blizzlike Behaviour

command .guid  BUG

### Steps to reproduce the problem

command .guid  BUG

### AC rev. hash/commit

command .guid  BUG

### Operating system

windows10 X64

**Comment by Sedatyf** [comment]
Hi,
Thank you for the report but there is a lot of things that isn't right in your ticket:
- You need to precise hash/commit in your post
- You need to explain why is it bug 
- You need to explain how is it supposed to be
- You need to precise a better way to reproduce
