### ISSUE TITLE
Hunter - Auto Shot

### ISSUE THREAD

**Issue by lingxDEV** [azerothcore/azerothcore-wotlk#16037]
### Current Behaviour

Auto Shot will go off instantly with no delay.

### Expected Blizzlike Behaviour

Auto Shot should have to "load up" before being fired based on bow/gun speed.

### Source

Classic WotLK

### Steps to reproduce the problem

Watch the videos.

Classic WotLK: https://streamable.com/oyps50
AC: https://streamable.com/oc8ngk

### AC rev. hash/commit

d1c8180

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by GoonBoiBarry** [comment]
Just to add to/clarify this issue, auto-shot still uses the weapon speed of the ranged weapon you're using, but there is supposed to be a delay after any movement regardless of weapons swing timer where you load the weapon for 0.5 seconds.

**Comment by hofik19** [comment]
Commenting on the issue as it looks like there should be no delay in auto shot. WotLK Classic could be bugged at the time of original report [https://us.forums.blizzard.com/en/wow/t/hunters-auto-shot-is-not-behaving-as-it-originally-did-in-wotlk/1335976/7](url)
[https://www.youtube.com/watch?v=7dwOsHpoeTY](url) - (WotLK Classic) you can see the hunter stops and the Auto-Shot is fired instantly (grey bar is AS timer)
[https://www.youtube.com/watch?v=nsyYBZCjNoM](url) - (Original WotLk) at 0:24 you see auto-shot instantly after hunter stops moving
