### ISSUE TITLE
Karazhan: Loot - Enchants have a 100% drop rate

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#16032]
Original issue: https://github.com/chromiecraft/chromiecraft/issues/4867

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Enchants seems to have a 100% drop rate inside Karazhan

### Expected Blizzlike Behaviour

Enchants are rare drops from:
Moroes: [[Formula: Enchant Weapon - Mongoose]](https://wowpedia.fandom.com/wiki/Formula:_Enchant_Weapon_-_Mongoose)
Illhoof: [[Formula: Enchant Weapon - Soulfrost]](https://wowpedia.fandom.com/wiki/Formula:_Enchant_Weapon_-_Soulfrost)
Aran: [[Formula: Enchant Weapon - Sunfire]](https://wowpedia.fandom.com/wiki/Formula:_Enchant_Weapon_-_Sunfire)

### Source

Wowhead
https://www.wowhead.com/wotlk/item=22559/formula-enchant-weapon-mongoose
It has a 8% chance on that website, its certainly not a 100% drop.
Karazhan Loot List
https://wowpedia.fandom.com/wiki/Karazhan_loot

### Steps to reproduce the problem

1. Enter Karazhan
2. Get the enchanting profession so you can see the drops
3. Kill Moroes, Illhoof or Aran
4. Check the drop rate.

### Extra Notes

They were made 100% in wotlk
https://wowpedia.fandom.com/wiki/Patch_3.1.0#Enchanting

Should be reduced for progression though

### AC rev. hash/commit

49820e475e63

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
The drop rate of those enchants has been increased to 100% in 3.1
https://www.wowhead.com/wotlk/item=22559/formula-enchant-weapon-mongoose#comments:id=949922
https://www.wowhead.com/wotlk/item=22561/formula-enchant-weapon-soulfrost#comments:id=684111
https://wowpedia.fandom.com/wiki/Patch_3.1.0#Enchanting
![image](https://user-images.githubusercontent.com/50233983/214025605-d01061c7-0a7e-4d0b-9d1f-9bccb30c7ae8.png)
