### ISSUE TITLE
creature_template_spell doesn't skip empty indexes.

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#16047]
### Current Behaviour

Fills the empty slots.
![57b0386ec0da65a710b360d6b92542c4](https://user-images.githubusercontent.com/46330494/233479824-ba99ce79-0e28-4ad9-a9fe-206be33c1ea6.png)

### Expected Blizzlike Behaviour

Should respect index order and leave empty slots.
![fca8f841239539558dd62ea005d2d6cc](https://user-images.githubusercontent.com/46330494/233480110-c8e8f93a-04b8-40dc-a7db-8e02ec5421f8.png)

### Source

https://youtu.be/g5Lo1PPLz5k?t=8

### Steps to reproduce the problem

.npc add temp 16803
.posses

### Extra Notes

https://github.com/azerothcore/azerothcore-wotlk/issues/4139

### AC rev. hash/commit

d75bcf0f67ea923ab82751e4b124b35d1cb76f29

### Operating system

Windows 10

**Comment by Si1ker** [comment]
years later, now I understand what Kitzunu meant here lol
https://github.com/azerothcore/azerothcore-wotlk/issues/4139#issuecomment-753528388

**Comment by Nyeriah** [comment]
creature_template_spell isn't sniffed to my knowledge

cc @Gultask

**Comment by heyitsbench** [comment]
> creature_template_spell isn't sniffed to my knowledge

Doesn't make much sense for it to have a VerifiedBuild column if it's not sniffed. TC's documentation on the table words it to be a parsed deal as well.

**Comment by Nyeriah** [comment]
Never seen it in my parses but I never looked into this specifically tbh, Gultask should know better

**Comment by Gultask** [comment]
:)
```
ServerToClient: SMSG_PET_SPELLS_MESSAGE (0x2C25) Length: 73 ConnIdx: 1 Time: 04/20/2023 19:10:53.404 Number: 966
PetGUID: Full: 0x203B10000000AE0000001F0000415B91 Creature/0 R3780/S31 Map: 0 Entry: 696 Low: 4283281
CreatureFamily: 0
Specialization: -1
TimeLimit: 0
(PetModeAndOrders) ReactState: Defensive
(PetModeAndOrders) CommandState: Stay
(PetModeAndOrders) Flag: 0
(ActionButtons) [0] Action: 7
(ActionButtons) [0] SpellID: 2
(ActionButtons) [1] Action: 8
(ActionButtons) [1] SpellID: 3148
(ActionButtons) [2] Action: 9
(ActionButtons) [2] SpellID: 10277
(ActionButtons) [3] Action: 0
(ActionButtons) [3] SpellID: 0
(ActionButtons) [4] Action: 0
(ActionButtons) [4] SpellID: 0
(ActionButtons) [5] Action: 0
(ActionButtons) [5] SpellID: 0
(ActionButtons) [6] Action: 0
(ActionButtons) [6] SpellID: 0
(ActionButtons) [7] Action: 0
(ActionButtons) [7] SpellID: 0
(ActionButtons) [8] Action: 0
(ActionButtons) [8] SpellID: 0
(ActionButtons) [9] Action: 0
(ActionButtons) [9] SpellID: 0
ActionsCount: 0
CooldownsCount: 0
SpellHistoryCount: 0
```

**Comment by Si1ker** [comment]
Wotlk Classic (3.4) still has the same order as it used to have in "Wotlk Vanilla" (2008).

https://youtu.be/g5Lo1PPLz5k?t=4

**Comment by Kitzunu** [comment]
From what I gather we cannot have empty spell slots for creatures. As far as I can tell this is some client thing.
This means to create gaps there needs to be a spell filled.

This is a really fast and bad hack fix for anyone who desperately wants to fix this I guess lol


```sql
INSERT INTO spell_dbc (`id`, `name_lang_enus`) VALUES
(100103, 'DummySpell1'),
(100104, 'DummySpell2'),
(100105, 'DummySpell3'),
(100106, 'DummySpell4'),
(100107, 'DummySpell5'),
(100108, 'DummySpell6'),
(100109, 'DummySpell7'),
(100110, 'DummySpell8');
```
```diff
diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index 3d0c018ba..2b2b701ea 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -475,7 +475,26 @@ bool Creature::InitEntry(uint32 Entry, const CreatureData* data)
         m_defaultMovementType = IDLE_MOTION_TYPE;
 
     for (uint8 i = 0; i < MAX_CREATURE_SPELLS; ++i)
-        m_spells[i] = GetCreatureTemplate()->spells[i];
+    {
+        if (GetCreatureTemplate()->spells[i])
+            m_spells[i] = GetCreatureTemplate()->spells[i];
+        else if (i == 0)
+            m_spells[i] = 100103;
+        else if (i == 1)
+            m_spells[i] = 100104;
+        else if (i == 2)
+            m_spells[i] = 100105;
+        else if (i == 3)
+            m_spells[i] = 100106;
+        else if (i == 4)
+            m_spells[i] = 100107;
+        else if (i == 5)
+            m_spells[i] = 100108;
+        else if (i == 6)
+            m_spells[i] = 100109;
+        else if (i == 7)
+            m_spells[i] = 100110;
+    }
 
     return true;
 }
```
