### ISSUE TITLE
ICC:Professor's bug

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#16050]
### Current Behaviour

When testing ICC, a serious problem was discovered. When teaching in 10 person normal mode, everything was normal, but when teaching in 10 person H mode, the professor remained motionless during the transition phase.

### Expected Blizzlike Behaviour

In the 10 person H mode, the combat process should be the same as in the 10 person normal mode. During the transition phase, the boss stunned the team, spoke, and then transformed

### Steps to reproduce the problem

I don't know how to handle it

### AC rev. hash/commit

AzerothCore rev. 58d1419add78+ 2023-04-21 10:04:42 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

WINDOWSERVER 2019

### Custom changes or Modules

- mod-1v1-arena
- mod-anticheat
- mod-autobalance
- mod-eluna
- mod-weekend-xp

**Comment by pklloveyou** [comment]
As far as I know, the hero mode professor should not prohibit team movement

**Comment by yukijean** [comment]
@pklloveyou Perhaps I didn't express it clearly, but in H mode, the professor didn't move at all on his test bench during the transition phase. After the normal transition phase, the boss will deform and continue to attack the player
