### ISSUE TITLE
[Warlock] Siphon Life counts as a healing spell for procs

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#16064]
### Current Behaviour

Procs trinkets such as [Binding Light](https://wowgaming.altervista.org/aowow/?item=47728) or [Scarab of the Infinite Cycle](https://wowgaming.altervista.org/aowow/?item=28190)

### Expected Blizzlike Behaviour

Does not proc helpful/healing effects

### Source

Can not find anyone ever have used it and it also is rare for such talents to proc things

### Steps to reproduce the problem

.learn 172
.learn 63108
.add 28190

Cast Corruption on something and wait for a proc

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=63108

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/fc7d2aedb0e05e65788fe424f9324b137946b1cf

### Operating system

Windows 10

**Comment by v-mstrs** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4039a3eb475039be9f4a2fd547ea2f82fff41558
