### ISSUE TITLE
ShadowLabirynth creature 18787 right half can't be selected when in combat

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#16071]
### Current Behaviour

.go c  146138
.gm off
Will see  many creature with  ID 18787, but only 146135 can select , other right side creature will not be selected. and the left side all can be selected.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 5dc6f9cf78f1+ 2023-04-23 21:03:18 +0000 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.104-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-autozc
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-reward-played-time
- mod-save-inventory
- mod-server-auto-shutdown
- mod-zone-difficulty

### Operating system

debian 11 x64

**Comment by Gultask** [comment]
Can you show a screenshot?
It should look like this:

![image](https://user-images.githubusercontent.com/100873791/233896292-d6face91-ef4c-439c-827d-52f980adb1ca.png)

The ones that are down cannot be selected, which is blizzlike. They aggro on approach and become selectable then

**Comment by kissingers** [comment]
![image](https://user-images.githubusercontent.com/33601959/233897416-67f5beff-d544-4777-beee-46e7cef6d11b.png)

the left side are died at start, but right are alive, when close the left side will in combat and can select, but the right will not select

![image](https://user-images.githubusercontent.com/33601959/233897643-a1e93d18-78fd-42c6-8a46-bcdfde30e8b5.png)

**Comment by Gultask** [comment]
Seems like I forgot to change the template unit_flags for Heroic 😅 

Here:

```
UPDATE `creature_template` SET `unit_flags` = `unit_flags`&~33554432 WHERE (`entry` = 20662);
```

If you want to open a PR with the update, feel free to

**Comment by kissingers** [comment]
> Seems like I forgot to change the template unit_flags for Heroic 😅
> 
> Here:
> 
> ```
> UPDATE `creature_template` SET `unit_flags` = `unit_flags`&~33554432 WHERE (`entry` = 20662);
> ```
> 
> If you want to open a PR with the update, feel free to

Thank you, I can test because I always update the server to newer, but not good at sql fix, I only can wright some lua ...
So may you fix it in any ShadowLabirynth PR?

**Comment by Gultask** [comment]
You just need to run that in the acore_world database, but I can make a PR, yes.
It might take a few days though, since we have a squash coming

**Comment by kissingers** [comment]
![image](https://user-images.githubusercontent.com/33601959/233899817-38362f29-52c0-4027-b19f-c75886790363.png)
I learn a way for `unit_flags`&~33554432 , thank you!  but it seems already has the flags,  I think if the problem is the right side is alive at first, so can't fit the smartAI or any other condition?

**Comment by Gultask** [comment]
You need to remove the flags. 

The SAI removes and adds the flags when necessary. I removed the flags from the Normal Mode but forgot for the Heroic version, so that's the reason for the mismatch. You just need to remove the flag for it to work

**Comment by kissingers** [comment]
fixed, thank you!  learn another  ~    for sql....
