### ISSUE TITLE
[Shattered Halls] Gauntlet of Flame - Blood Guard Porung

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#16072]
### Current Behaviour

Basically missing

### Expected Blizzlike Behaviour

https://github.com/Gultask/Research-Wotlk/issues/7#issuecomment-1519378502

### Source

Retail Sniffs

### Steps to reproduce the problem

`.go xyz 268.566 313.1756 -2.52402 540 0.09`

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5dc6f9cf78f11b89214b9d878ec89e30d58388bc

### Operating system

Windows 10

**Comment by Si1ker** [comment]
[cmangos](https://github.com/cmangos/mangos-tbc/blob/6fb24c859360c4ce39845e71570f043c47440181/src/game/AI/ScriptDevAI/scripts/outland/hellfire_citadel/shattered_halls/shattered_halls.cpp)

**Comment by Gultask** [comment]
> [cmangos](https://github.com/cmangos/mangos-tbc/blob/6fb24c859360c4ce39845e71570f043c47440181/src/game/AI/ScriptDevAI/scripts/outland/hellfire_citadel/shattered_halls/shattered_halls.cpp#L293)

Waypoints and GUIDs in .cpp 🥴

**Comment by heyitsbench** [comment]
> Waypoints and GUIDs in .cpp 🥴

If it worky it worky.

**Comment by Si1ker** [comment]
> > [cmangos](https://github.com/cmangos/mangos-tbc/blob/6fb24c859360c4ce39845e71570f043c47440181/src/game/AI/ScriptDevAI/scripts/outland/hellfire_citadel/shattered_halls/shattered_halls.cpp#L293)
> 
> Waypoints and GUIDs in .cpp 🥴

@Gultask 
I didn't mean to point to a specific line sorry xd
I meant to point out the entire file to take some ideas as to how mangos had the entire gauntlet system
