### ISSUE TITLE
[NPC] Librarian Garren [Fix included]

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1609]
https://www.wowhead.com/npc=25291/librarian-garren#abilities

While talking with Garren there's option to give u water breathing trough gossip.

How to test:

1. .go cre 114935
2. Talk with him and select water breathing option.

Problem:

Nothing happen when you chose option for water breathing.

Fix bellow:

```sql
-- Creating a new SmartAI script for [Creature] ENTRY 25291 (name: Librarian Garren)

-- Table creature_template
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 25291;

-- Table smart_scripts
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 25291);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(25291, 0, 0, 0, 62, 0, 100, 0, 9761, 0, 0, 0, 11, 52909, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, '');
```

.reload creature_template 25291
.reload smart_scripts
.npc  add 25291

Try talking with him now.
If everything is ok, delete NPC u just spawned, and server restart.
Main NPC will work after restart.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg can you please open a PR with your fix ?

**Comment by poszer** [comment]
Tested without this commit @Knindzagxg  was right. You can't click on that water breathing menu.
Tested with this commit and it's working now.
Will create PR for it, thanks @Knindzagxg
