### ISSUE TITLE
[instance sunwell] the creature 25368 have a spell 46557 will cast a very high damage 

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#16099]
### Current Behaviour

.go c 25368
.mod hp 999999999
.gm off 
.gm vi on
if hited by the spell 46557, after 4 hot the gm die.

![image](https://user-images.githubusercontent.com/33601959/234796504-643f2383-18bd-47ab-ba65-7c90fe2bfef1.png)

or use hunter 
.learn 46557
cast the spell  to test

![image](https://user-images.githubusercontent.com/33601959/234794702-6b02ef4d-32b6-4495-b87b-b53610f8941f.png)

### Expected Blizzlike Behaviour

the damage not so large

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. d24f5ec955ac+ 2023-04-26 04:51:03 +0000 (HEAD branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.104-1-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-autozc
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-reward-played-time
- mod-save-inventory
- mod-server-auto-shutdown
- mod-zone-difficulty

### Operating system

debian 11 x64

**Comment by Tereneckla** [comment]
Each tick deals 25% of your health
Of course you die in 4 ticks
