### ISSUE TITLE
[Hellfire Peninsula] Hollow Dark Shaman and Grillok "Darkeye"  should not place a fire nova totem 

### ISSUE THREAD

**Issue by Annamaria-CC** [azerothcore/azerothcore-wotlk#16097]
Original issue; https://github.com/chromiecraft/chromiecraft/issues/5510
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

61-64

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=16873
NPC: https://wowgaming.altervista.org/aowow/?npc=19457
Their https://wowgaming.altervista.org/aowow/?spell=32062 Fire Nova totem (Fire Nova Totem VII) should deal 413 to 459 fire damage to enemies within 10 yd but it deals 1500+ fire damage. Screenshot: 
![изображение](https://user-images.githubusercontent.com/104144379/234417989-1a64262b-bb83-49e1-b631-d17802e3afb9.png)

### Expected Blizzlike Behaviour

They should not cast fire nova totem at all, tried with 3 units attack for a bit so its also not an target check

### Source

WOTLK CLASSIC

### Steps to reproduce the problem

1. Go to Bleeding Hollow Dark Shaman or  Grillok "Darkeye" and engage fight.
2. Wait them to place Fire Nova totem.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. df77b5f4f79d 2023-04-24 08:13:07 -0300 (master branch) (Unix, Debug, Static)

**Comment by avarishd** [comment]
Grillok "Darkeye" does place a fire nova totem 
https://youtu.be/AfMVmZbUFFM?t=54 
https://youtu.be/vySNmeX0C-w?t=127
https://youtu.be/T3-YrH0CjJM?t=157 (does 726 on the pet)

Damage is due to FIre Nova Totem VII casting  46551 (1665-1935 dmg)
FNT V casts Rank 5 Fire Nova
Judging by that FNT VII should cast Rank 7 (749-836 dmg)

**Comment by heyitsbench** [comment]
> Judging by that FNT VII should cast Rank 7 25537 [...]

Can confirm, spell 25537 casted by 15483 in 2.5.3 42328.
