### ISSUE TITLE
problem in (HeroicCharactersPerRealm)

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#16104]
### Current Behaviour

The number of characters for an account is 10
But I made 6 characters and it tells me that the characters are full. I also looked at the database and I have 6 characters in total.

![image](https://user-images.githubusercontent.com/52524476/234907828-f300261a-cffb-449e-931c-175026bf1a98.png)
![WoWScrnShot_042723_183927](https://user-images.githubusercontent.com/52524476/234907864-0098cefa-924b-4f1d-a897-b6a9b23b5af1.jpg)
![WoWScrnShot_042723_183938](https://user-images.githubusercontent.com/52524476/234907881-746c2071-d014-4dd7-a63a-f55f8bd062d6.jpg)

### Expected Blizzlike Behaviour

must be the character relative to the worldserver control

### Source

None

### Steps to reproduce the problem

In worldserver, set the number of characters to 10
And see, can you make 10 characters?

### Extra Notes

None

### AC rev. hash/commit

rev. c2f6f5b88153

### Operating system

window server 2019 64bit

**Comment by heyitsbench** [comment]
> Yes, because it was set to 1 by default

![Default](https://user-images.githubusercontent.com/38561765/234914381-4ebebf5c-470a-4b21-b6b2-6576516da2c1.png)
