### ISSUE TITLE
disconnection and memory problems 

### ISSUE THREAD

**Issue by rookis1** [azerothcore/azerothcore-wotlk#16108]
After deploying the server with ubunbu20.04, I connected with the client and found that the memory usage of the server has been around 3G. Even if I allocated 16G of memory to the server, it still can only use a small part. This is normal. of it? Because in the process of using the client to connect to the game, there will be server freezes and unexpected disconnections. Is it a problem caused by too low memory usage?

**Comment by Kitzunu** [comment]
This is not a forum for questions. Only for bugs.

To answer, no that is not normal and I havent heard of anything like it.

I suggest you ask on Discord or in discussions
