### ISSUE TITLE
problem in (Warden.ClientResponseDelay)

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#16100]
### Current Behaviour

Even when the internet has a good speed
It kicks out the player every 10 minutes

### Expected Blizzlike Behaviour

It seams
There must be a very big swing during these 10 minutes for the player to be kicked

### Source

None

### Steps to reproduce the problem

Activate a hero and take 10 minutes

### Extra Notes

None

### AC rev. hash/commit

rev. c2f6f5b88153

### Operating system

window server 2019 64bit

**Comment by heyitsbench** [comment]
I deleted a few of the more recent entries in `warden_checks` (795+) and I seem to have stopped getting kicked. It seems these checks were added in the [most recent squash](https://github.com/azerothcore/azerothcore-wotlk/pull/16069/commits/bb8e0e9f1d8b4e586f78a8dc52d1cbca560e0126), I can't find them in any previous PR. Is there a reason these were thrown into a squash PR without mention?
CC: @Gultask

**Comment by poryagholami** [comment]
> I deleted a few of the more recent entries in `warden_checks` (795+) and I seem to have stopped getting kicked. It seems these checks were added in the [most recent squash](https://github.com/azerothcore/azerothcore-wotlk/pull/16069/commits/bb8e0e9f1d8b4e586f78a8dc52d1cbca560e0126), I can't find them in any previous PR. Is there a reason these were thrown into a squash PR without mention? CC: @Gultask

These problems are new because there are no such problems in the updates of a few days ago

**Comment by poryagholami** [comment]
![image](https://user-images.githubusercontent.com/52524476/234910558-ee7ded22-5831-4309-af3a-d68ff405e4a7.png)
I think there is a problem here

**Comment by Nyeriah** [comment]
> I deleted a few of the more recent entries in `warden_checks` (795+) and I seem to have stopped getting kicked. It seems these checks were added in the [most recent squash](https://github.com/azerothcore/azerothcore-wotlk/pull/16069/commits/bb8e0e9f1d8b4e586f78a8dc52d1cbca560e0126), I can't find them in any previous PR. Is there a reason these were thrown into a squash PR without mention? CC: @Gultask

Without going into further detail as it could cause further compromise, there's no possible way for Warden to work in an opensource environment effectively without having its measures completely defunct after each update almost instantly

**Comment by heyitsbench** [comment]
> Without going into further detail as it could cause further compromise, there's no possible way for Warden to work in an opensource environment effectively without having its measures completely defunct after each update almost instantly
> 
> The new measures were tested before and were running without issues during our tests, so we are to wonder what has caused issues with it in the latest update

Well one question I have is why weren't these checks proposed in a separate PR, rather than going unmentioned in a squash PR?

**Comment by Nyeriah** [comment]
I already covered that question. There wouldn't be a point in ever commiting them as them being public already invalidates the point of having them shared in a public repository completely. Reason why most warden development is never shared I assume, and why many hacks and cheats are not detected by the native anticheat feature

**Comment by Kitzunu** [comment]
Going to close as fixed by 91486ac46faf8c978e2d46771dbba103736efe87
