### ISSUE TITLE
Recipe: Captain Rumsey's Lager 

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#16116]
https://github.com/chromiecraft/chromiecraft/issues/5518
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Very very very very very very very rarely drops from the Shattrath fishing daily and the Dalaran fishing and cooking dailies

### Expected Blizzlike Behaviour

Has a higher chance to drop from the mentioned dailies and also can drop from the cooking daily crates

### Source

https://www.wowhead.com/wotlk/item=34834/recipe-captain-rumseys-lager
https://wowgaming.altervista.org/aowow/?item=34834

The values from wowhead shouldn't be taken at face value as usual. Especially not from the Barrel of Fish and Crate of Meat

https://wowpedia.fandom.com/wiki/Recipe:_Captain_Rumsey%27s_Lager
![image](https://user-images.githubusercontent.com/50233983/235337059-4c09df4a-94c3-47b4-b68d-13e1b448467f.png)

### Steps to reproduce the problem

DB

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=34834

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
0.35% & 1.7% drop chance in reference tables. Looks good to me

**Comment by Tereneckla** [comment]
1.7% chance in the reference, the reference has a chance of 5% for the bag of fishing treasure (34863 and 35348)
Even with just taking the 1.7% chance wowhead has ~double that chance recorded and is statistically relevant enough (apart from people looting that already have the recipe which would just push the number up)
Wowhead also has twice the chance in 46007 and twice the chance in 44113

Not to mention: It also is missing from 33844 and 33857

**Comment by elthehablo** [comment]
Unfortunately it is going to be really hard to find a proper source for this unless we get someone to do this every single day on wotlk classic lol. What does TC and other projects have for this?
