### ISSUE TITLE
[Ulduar] Spinning Up Mimiron P4  [$90]

### ISSUE THREAD

**Issue by Naxxramas-Server** [azerothcore/azerothcore-wotlk#1611]
[Ulduar] Spinning Up Mimiron P4 

##### SMALL DESCRIPTION:
Mimiron Spinning up spell in P4 doesn't work

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When Mimiron arrive in P4 , the VX-001 have to use the spell Spinning-Up like in the P2

##### CURRENT BEHAVIOUR:
Actually , VX-001 use the Spinning up only on P2 and not on P4 , and if we uncomment this line : https://github.com/azerothcore/azerothcore-wotlk/blob/03bfbf4f7e43f6b8064e6846e0bf2503958c17bc/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp#L1376 , VX-001 use the spell , but visual is not correct with damage done by the spell ...

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Enter Ulduar 10 or 25 players
2. Travel to Mimiron and engage him
3. See the VX-001 P2 is correct but not in P4

##### BRANCH(ES):

master

**Comment by Viste** [comment]
do you have more info about it? wowwiki or somthing

**Comment by Naxxramas-Server** [comment]
You can see that in all official videos like :

https://youtu.be/ZjecQKcGuD4

See at 6:13 the spinning up in P4

**Comment by Nefertumm** [comment]
> but visual is not correct with damage done by the spell ...

What do you mean with that?

**Comment by Naxxramas-Server** [comment]
No because , you take damage by the spell , but not in the visual when the boss cast it.
When in P4 the boss use this ability , run around the room , you'll see you take damage out the visual

**Comment by Nefertumm** [comment]
I re-tested it, the first time i tested was normal, now i saw what you meant.

**Comment by Naxxramas-Server** [comment]
Yep i think it's that,  but don't know how to fix it , that's why i opened this issue :
^^

**Comment by Viste** [comment]
@Naxxramas-Server try:
https://github.com/Viste/Azeroth4you/tree/mimiron
https://github.com/Viste/Azeroth4you/commit/6d0f1d4e104188affbd2532c9b41d7536b40f8aa

**Comment by Pondaveia** [comment]
@Viste https://github.com/Viste/Outlandcore/blob/6d0f1d4e104188affbd2532c9b41d7536b40f8aa/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp#L1554

Did you try swapping with DoCast() ? Just a feeling 🤔

**Comment by solidmaxtor** [comment]
I confirm that the error persists in the last master, Spinning Up Mimiron only work in P2 and Not in P4
check for many players last weeks.

**Comment by WWOkaso** [comment]
So, nobody is having a go at this right now? I have a wack idea about what could be wrong,  but have no c++ skills to start looking at it, I can test stuff tho if anyone is working on it.

**Comment by FrancescoBorzi** [comment]
NOT RELATED WITH THIS ISSUE

@WWOkaso if you could help with testing, that would be great. We have plenty of PRs to test: https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+is%3Aopen+label%3A%22Waiting+to+be+tested%22

**Comment by Dreaxxx** [comment]
I'v added 30$ more
There is now 75$ bounty on this issue actually

**Comment by Yehonal** [comment]
I've an idea on how to fix it, however, I can't test it this week.
Meanwhile, could someone take a video of what happen right now and what happen when you uncomment that line? 

Otherwise, just wait ^_^

**Comment by Voxstrasza** [comment]
I've added $15 more to this bounty for a total of $90.

hope someone can figure this out, it's been a while.

**Comment by FALL1N1** [comment]
I'm on it, fixed it locally. I just have to do the PR tomorrow if someone doesn't do it yet.

**Comment by UltraNix** [comment]
Made a PR. Please, review it.
