### ISSUE TITLE
[Magtheridon's Lair] Infernals spawn too quickly and have wrong immunities

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#16119]
originally posted by NinesCC at: https://github.com/chromiecraft/chromiecraft/issues/5349

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

- Channelers summon a infernal all at the start of the encounter (confirmed)
- Infernals hit for 2.5k-3k damage on normal mode, but hit for 6k on Hard mode. <-hard mode scaling related. part of progression, not AC so irrelevant here
- As of the time of the testing, infernals were inmune to all kind of CC (not all necessarily confirmed. needs more sources)
https://youtu.be/ke3fLMKc6iw?t=6949

### Expected Blizzlike Behaviour

- Channelers should summon Infernals at a slow pace, not everyone at the same time.
- Infernal damage should scale accordingly instead of double damage.
- Infernals may be frost nova'd, banished, feared, stunned, or trapped.

### Source

First Infernal spawns 15 secs after the pull, the second appears 40 seconds after the first.
https://youtu.be/PVL-m0CvfI0?t=29

### Steps to reproduce the problem

1. .teleport magtheridon
2. clear the trash
3. hit a channeler to start the encounter
4. watch the speed in which they summon infernals

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/37f0b7095f949293c13f1d913f8917407ffe3b1b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
Spawn fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/16722
