### ISSUE TITLE
[Ulduar] Runemaster Molgeim - Rune of Summoning [$10]

### ISSUE THREAD

**Issue by Naxxramas-Server** [azerothcore/azerothcore-wotlk#1612]
[Ulduar] Runemaster Molgeim - Rune of Summoning

##### SMALL DESCRIPTION:
Spell Rune of summoning of Runemaster Molgeim doesn't work on 25 raid Mode

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When Runemaster Molgeim is the last alive boss in the encounter , he should use the spell Rune of summoning in 10 and 25 players raid mode

##### CURRENT BEHAVIOUR:
Actually , Runemaster Molgeim use this ability only in 10 players mode and not in 25 players mode.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Move to Ulduar
2. Start Assembly of iron encounter and kill the 2 other boss : Steelbreaker and Stormcaller Brundir
3. When only Molgeim is alive , he use the Rune of summoning in 10 players mode but not in 25 players mode.

##### BRANCH(ES):

master

**Comment by Motorheadx** [comment]
This will fix your problem
UPDATE `creature_template` SET `entry`='33051', `difficulty_entry_1`='0' WHERE (`entry`='33051');

**Comment by FrancescoBorzi** [comment]
@Motorheadx can you please open a PR with it? So you can claim the bounty and earn 10 dollars
