### ISSUE TITLE
Unit_Class Paladin HP at 66 is odd

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#16146]
### Current Behaviour

unit_class 2 (Paladin) has

level 65: 4731 hp
level 66: 6906 hp
level 67: 5060 hp

![image](https://user-images.githubusercontent.com/50233983/235376684-bca4167e-8be2-45e7-903f-87c97908dcb8.png)
![image](https://user-images.githubusercontent.com/50233983/235376640-d2786e1c-8b64-4b26-b0fd-5bc851804fd0.png)
![image](https://user-images.githubusercontent.com/50233983/235376630-1b55cccc-74ba-4114-b093-3f0391456ea0.png)

### Expected Blizzlike Behaviour

level 66 hp should lie in between 65 and 67

### Steps to reproduce the problem

.go c id 21809

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/26e79da8a8d33b3c8f53797ea359e45ef261fd4c

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
[Wyrmcult Poacher](https://wowgaming.altervista.org/aowow/?npc=21809) on 3.4.0 45704 (Paladin unit_class, level 66) has 4892 health.
Source: 👃
