### ISSUE TITLE
[server] World Crash - Recent Commit

### ISSUE THREAD

**Issue by jshplayer** [azerothcore/azerothcore-wotlk#16142]
### Current Behaviour

Suspect this one is caused by commit a238e5e27bfa7b0fd2f6aab19d0722c61eaf81c5

Debug
No symbol table info available.
  Id   Target Id                                     Frame 
* 1    Thread 0x7f0833524fc0 (LWP 825) "worldserver" 0x0000000000d17792 in Unit::DealDamage(Unit*, Unit*, unsigned int, CleanDamage const*, DamageEffectType, SpellSchoolMask, SpellInfo const*, bool, bool, Spell const*, bool) ()
  2    Thread 0x7f0832bff700 (LWP 831) "worldserver" futex_wait_cancelable (private=0, expected=0, futex_word=0x7f083308019c) at ../sysdeps/nptl/futex-internal.h:186
  3    Thread 0x7f08323fe700 (LWP 832) "worldserver" 0x00007f0835746d56 in epoll_wait (epfd=4, events=0x7f08323fbe70, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  4    Thread 0x7f0831bfd700 (LWP 833) "worldserver" futex_wait_cancelable (private=0, expected=0, futex_word=0x7f08330422e0) at ../sysdeps/nptl/futex-internal.h:186
  5    Thread 0x7f08313fc700 (LWP 836) "worldserver" futex_wait_cancelable (private=0, expected=0, futex_word=0x7f0833042224) at ../sysdeps/nptl/futex-internal.h:186
  6    Thread 0x7f0830bfb700 (LWP 840) "worldserver" futex_wait_cancelable (private=0, expected=0, futex_word=0x7f0833042164) at ../sysdeps/nptl/futex-internal.h:186
  7    Thread 0x7f07ef1ff700 (LWP 871) "worldserver" futex_wait_cancelable (private=0, expected=0, futex_word=0x1ba5ac0 <MapMgr::instance()::instance+376>) at ../sysdeps/nptl/futex-internal.h:186
  8    Thread 0x7f07de9fe700 (LWP 872) "worldserver" 0x00007f083573ce23 in __GI___select (nfds=19, readfds=0x7f07de9d4180, writefds=0x7f07de9d4200, exceptfds=0x7f07de9d4280, timeout=0x7f07de9d4170) at ../sysdeps/unix/sysv/linux/select.c:41
  9    Thread 0x7f07de1fd700 (LWP 873) "worldserver" 0x00007f0835746d56 in epoll_wait (epfd=21, events=0x7f07de1fadc0, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  10   Thread 0x7f07dd3ff700 (LWP 874) "worldserver" 0x00007f083573ce23 in __GI___select (nfds=1, readfds=0x7f07dd3fd450, writefds=0x0, exceptfds=0x7f07dd3fd4d0, timeout=0x7f07dd3fd440) at ../sysdeps/unix/sysv/linux/select.c:41
  11   Thread 0x7f07dc7ff700 (LWP 875) "worldserver" 0x00007f083570d1a1 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7f07dc7fd5b0, rem=0x7f07dc7fd5b0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48

Thread 11 (Thread 0x7f07dc7ff700 (LWP 875) "worldserver"):

### Expected Blizzlike Behaviour

Not crash

### Steps to reproduce the problem

Unknown

### AC rev. hash/commit

AzerothCore rev. 26e79da8a8d3 2023-04-30 00:20:39 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100519
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-22-cloud-amd64

### Operating system

Debian 10

**Comment by Fireevil** [comment]
confirm in https://github.com/azerothcore/azerothcore-wotlk/commit/26e79da8a8d33b3c8f53797ea359e45ef261fd4c
