### ISSUE TITLE
[server] world server crash 0430

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#16141]
### Current Behaviour

https://pastebin.com/Amf59KQS

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 26e79da8a8d3+ 2023-04-30 00:20:39 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.15.104-1-pve
Worldserver listening connections on port 54346
Realmlist (Realm Id: 2) configured in port 54346
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow2/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow2/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow2/bin/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autozc
- mod-eluna
- mod-zone-difficulty

### Operating system

debian 11 x64

**Comment by smellbee** [comment]
same crash 
see 
https://github.com/azerothcore/azerothcore-wotlk/issues/15228
and
https://github.com/azerothcore/azerothcore-wotlk/issues/15889

**Comment by Nefertumm** [comment]
It's not the same crash. And also, do you know how to reproduce it?

**Comment by kissingers** [comment]
It random crash for from minutes to hours, and both random kick player off from the server if not crash.
I roll back to  c2f6f5b8815395728994aa478dd06f29588a4e41  olny worldserver, the crash still happen.
Roll back the worldserver and the acore_world both to  c2f6f5b8815395728994aa478dd06f29588a4e41, the crash will never happen.

**Comment by kissingers** [comment]
> there are two type of crash logs, after #16166 the first type log not appear agein
> 
> but second type crash still happen https://pastebin.com/XgPExr1n

the second crash happen 4 times.
I temp roll back worldserver to https://github.com/azerothcore/azerothcore-wotlk/commit/c2f6f5b8815395728994aa478dd06f29588a4e41

**Comment by zxnhrdz** [comment]
Well, it's completely random disconnection now, but the frequency is very low, basically once or twice a day. The feeling it gave me started after updating # 16115. feat(Core/Unit): anticheat helper (#16115)

**Comment by Nefertumm** [comment]
Indeed. That's the commit that caused the crashes. In order to fix it, we need to use guids instead of pointers since we can't be sure the referenced memory still exists.
