### ISSUE TITLE
Server downtime

### ISSUE THREAD

**Issue by 127y** [azerothcore/azerothcore-wotlk#16171]
### Current Behaviour

Revision: AzerothCore rev. d7190451cf1d+ 2023-05-03 17:50:14 +0000 (master branch) (Win64, Release, Static)
Date 4:5:2023. Time 19:5 
//=====================================================
*** Hardware ***
Processor: Intel(R) Xeon(R) Platinum
Number Of Processors: 2
Physical Memory: 8239404 KB (Available: 6637180 KB)
Commit Charge Limit: 12168524 KB

*** Operation System ***
Windows Server 2016 Datacenter (Version 10.0, Build 20348)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF6BCAFE4F7 01:00000000005CD4F7 C:\Azeroth\core\worldserver.exe

Registers:
RAX:0000000000000570
RBX:0000000000000001
RCX:0000000000000000
RDX:000001DA7A6F1F60
RSI:000001DA705E0930
RDI:000000CAA79FD5B0
R8: 000000CAA79FD5B0
R9: 0000000000000000
R10:000000CAA6D0E640
R11:000001DA09FB6890
R12:0000000000000002
R13:000001DA7A6F1F60
R14:0000000000000000
R15:0000000000000001
CS:RIP:0033:00007FF6BCAFE4F7
SS:RSP:002B:00000000A6D0E3B0  RBP:00000000
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
00007FF6BCAFE4F7  000000CAA6D0E650  0001:00000000005CD4F7 C:\Azeroth\core\worldserver.exe
00007FF6BCA9B93C  000000CAA6D0EBE0  0001:000000000056A93C C:\Azeroth\core\worldserver.exe
00007FF6BC563900  000000CAA6D0EE90  0001:0000000000032900 C:\Azeroth\core\worldserver.exe
00007FF6BC5711BF  000000CAA6D0FB40  0001:00000000000401BF C:\Azeroth\core\worldserver.exe
00007FF6BD317D1C  000000CAA6D0FB80  argon2id_verify_ctx+2B3EC
00007FFC196E4DD0  000000CAA6D0FBB0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA6D0FC30  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A241344  000000CAA6D0BD80  ZwGetContextThread+14
0000000000000374  000000CAA6D0BD88  0000:0000000000000000 
0000000000000004  000000CAA6D0BD90  0000:0000000000000000 
000000CAA6D0CE10  000000CAA6D0BD98  0000:0000000000000000 
0000000000000001  000000CAA6D0BDA0  0000:0000000000000000 
00000000000003D4  000000CAA6D0BDA8  0000:0000000000000000 

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F594  000000CAA72FF760  NtRemoveIoCompletion+14
00007FFC17A47473  000000CAA72FF7C0  GetQueuedCompletionStatus+53
00007FF6BC567A20  000000CAA72FF910  0001:0000000000036A20 C:\Azeroth\core\worldserver.exe
00007FF6BC56D024  000000CAA72FF9F0  0001:000000000003C024 C:\Azeroth\core\worldserver.exe
00007FF6BC56CEB3  000000CAA72FFA50  0001:000000000003BEB3 C:\Azeroth\core\worldserver.exe
00007FF6BC550F7A  000000CAA72FFA80  0001:000000000001FF7A C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA72FFAB0  _recalloc+5C
00007FFC196E4DD0  000000CAA72FFAE0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA72FFB60  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F594  000000CAA73FF530  NtRemoveIoCompletion+14
00007FFC17A47473  000000CAA73FF590  GetQueuedCompletionStatus+53
00007FF6BC567A20  000000CAA73FF6E0  0001:0000000000036A20 C:\Azeroth\core\worldserver.exe
00007FF6BC56CFF2  000000CAA73FF7C0  0001:000000000003BFF2 C:\Azeroth\core\worldserver.exe
00007FF6BC56CEB3  000000CAA73FF820  0001:000000000003BEB3 C:\Azeroth\core\worldserver.exe
00007FF6BC550F7A  000000CAA73FF850  0001:000000000001FF7A C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA73FF880  _recalloc+5C
00007FFC196E4DD0  000000CAA73FF8B0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA73FF930  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA74FF620  NtWaitForAlertByThreadId+14
00007FFC1A20CE47  000000CAA74FF6A0  RtlSleepConditionVariableSRW+137
00007FFC17A5E319  000000CAA74FF6E0  SleepConditionVariableSRW+29
00007FFBF5842939  000000CAA74FF710  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFBF5842B7A  000000CAA74FF740  _Cnd_wait+3A
00007FF6BD287D48  000000CAA74FF770  0001:0000000000D56D48 C:\Azeroth\core\worldserver.exe
00007FF6BC5E4BBF  000000CAA74FF7A0  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA74FF7D0  _recalloc+5C
00007FFC196E4DD0  000000CAA74FF800  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA74FF880  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA75FFD40  NtWaitForAlertByThreadId+14
00007FFC1A20CE47  000000CAA75FFDC0  RtlSleepConditionVariableSRW+137
00007FFC17A5E319  000000CAA75FFE00  SleepConditionVariableSRW+29
00007FFBF5842939  000000CAA75FFE30  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFBF5842B7A  000000CAA75FFE60  _Cnd_wait+3A
00007FF6BD287D48  000000CAA75FFE90  0001:0000000000D56D48 C:\Azeroth\core\worldserver.exe
00007FF6BC5E4BBF  000000CAA75FFEC0  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA75FFEF0  _recalloc+5C
00007FFC196E4DD0  000000CAA75FFF20  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA75FFFA0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA76FF610  NtWaitForAlertByThreadId+14
00007FFC1A20CE47  000000CAA76FF690  RtlSleepConditionVariableSRW+137
00007FFC17A5E319  000000CAA76FF6D0  SleepConditionVariableSRW+29
00007FFBF5842939  000000CAA76FF700  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFBF5842B7A  000000CAA76FF730  _Cnd_wait+3A
00007FF6BD287D48  000000CAA76FF760  0001:0000000000D56D48 C:\Azeroth\core\worldserver.exe
00007FF6BC5E4BBF  000000CAA76FF790  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA76FF7C0  _recalloc+5C
00007FFC196E4DD0  000000CAA76FF7F0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA76FF870  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F4F4  000000CAA77FFDF0  ZwWaitForSingleObject+14
00007FFC17A1D52E  000000CAA77FFE90  WaitForSingleObjectEx+8E
00007FF6BC56CE53  000000CAA77FFEC0  0001:000000000003BE53 C:\Azeroth\core\worldserver.exe
00007FF6BC56EAD5  000000CAA77FFEF0  0001:000000000003DAD5 C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA77FFF20  _recalloc+5C
00007FFC196E4DD0  000000CAA77FFF50  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA77FFFD0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA78FF310  NtWaitForAlertByThreadId+14
00007FFC1A20CE47  000000CAA78FF390  RtlSleepConditionVariableSRW+137
00007FFC17A5E319  000000CAA78FF3D0  SleepConditionVariableSRW+29
00007FFBF5842939  000000CAA78FF400  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFBF5842B7A  000000CAA78FF430  _Cnd_wait+3A
00007FF6BC5EF484  000000CAA78FFB40  0001:00000000000BE484 C:\Azeroth\core\worldserver.exe
00007FF6BC5E4BBF  000000CAA78FFB70  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA78FFBA0  _recalloc+5C
00007FFC196E4DD0  000000CAA78FFBD0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA78FFC50  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA79FF770  NtWaitForAlertByThreadId+14
00007FFC1A20CE47  000000CAA79FF7F0  RtlSleepConditionVariableSRW+137
00007FFC17A5E319  000000CAA79FF830  SleepConditionVariableSRW+29
00007FFBF5842939  000000CAA79FF860  ?_Winerror_message@std@@YAKKPEADK@Z+139
00007FFBF5842B7A  000000CAA79FF890  _Cnd_wait+3A
00007FF6BD0F6E48  000000CAA79FF8C0  0001:0000000000BC5E48 C:\Azeroth\core\worldserver.exe
00007FF6BC5E4BBF  000000CAA79FF8F0  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA79FF920  _recalloc+5C
00007FFC196E4DD0  000000CAA79FF950  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA79FF9D0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F4F4  000000CAA7AFFDF0  ZwWaitForSingleObject+14
00007FFC17A1D52E  000000CAA7AFFE90  WaitForSingleObjectEx+8E
00007FF6BC56CE53  000000CAA7AFFEC0  0001:000000000003BE53 C:\Azeroth\core\worldserver.exe
00007FF6BC56EAD5  000000CAA7AFFEF0  0001:000000000003DAD5 C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA7AFFF20  _recalloc+5C
00007FFC196E4DD0  000000CAA7AFFF50  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA7AFFFD0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F594  000000CAA7BFF8A0  NtRemoveIoCompletion+14
00007FFC17A47473  000000CAA7BFF900  GetQueuedCompletionStatus+53
00007FF6BC567A20  000000CAA7BFFA50  0001:0000000000036A20 C:\Azeroth\core\worldserver.exe
00007FF6BC56D024  000000CAA7BFFB30  0001:000000000003C024 C:\Azeroth\core\worldserver.exe
00007FF6BCACDA8E  000000CAA7BFFC40  0001:000000000059CA8E C:\Azeroth\core\worldserver.exe
00007FF6BC5E4BBF  000000CAA7BFFC70  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA7BFFCA0  _recalloc+5C
00007FFC196E4DD0  000000CAA7BFFCD0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA7BFFD50  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F534  000000CAA7CFF130  ZwReadFile+14
00007FFC17A241FB  000000CAA7CFF1A0  ReadFile+7B
00007FFC17D57859  000000CAA7CFF240  _read+209
00007FFC17D576F2  000000CAA7CFF280  _read+A2
00007FFC17D57A2A  000000CAA7CFF2B0  _fgetc_nolock+AA
00007FFC17D57BFD  000000CAA7CFF2F0  _fgetwc_nolock+FD
00007FFC17D75211  000000CAA7CFF350  fgetws+81
00007FF6BC573FF8  000000CAA7CFF7B0  0001:0000000000042FF8 C:\Azeroth\core\worldserver.exe
00007FF6BC550F3B  000000CAA7CFF7E0  0001:000000000001FF3B C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA7CFF810  _recalloc+5C
00007FFC196E4DD0  000000CAA7CFF840  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA7CFF8C0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23FAF4  000000CAA7DFF3D0  NtDelayExecution+14
00007FFC1A1F7AAA  000000CAA7DFF410  RtlDelayExecution+2A
00007FFC179E7531  000000CAA7DFF490  SleepEx+71
00007FFBF5842E1C  000000CAA7DFF4E0  _Thrd_sleep+3C
00007FF6BC553AD3  000000CAA7DFF540  0001:0000000000022AD3 C:\Azeroth\core\worldserver.exe
00007FF6BC55DA6F  000000CAA7DFF720  0001:000000000002CA6F C:\Azeroth\core\worldserver.exe
00007FF6BC550F3B  000000CAA7DFF750  0001:000000000001FF3B C:\Azeroth\core\worldserver.exe
00007FFC17D76B4C  000000CAA7DFF780  _recalloc+5C
00007FFC196E4DD0  000000CAA7DFF7B0  BaseThreadInitThunk+10
00007FFC1A21E3DB  000000CAA7DFF830  RtlUserThreadStart+2B
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FF6BCAFE4F7  000000CAA6D0E650  0001:00000000005CD4F7 C:\Azeroth\core\worldserver.exe

00007FF6BCA9B93C  000000CAA6D0EBE0  0001:000000000056A93C C:\Azeroth\core\worldserver.exe

00007FF6BC563900  000000CAA6D0EE90  0001:0000000000032900 C:\Azeroth\core\worldserver.exe

00007FF6BC5711BF  000000CAA6D0FB40  0001:00000000000401BF C:\Azeroth\core\worldserver.exe

00007FF6BD317D1C  000000CAA6D0FB80  argon2id_verify_ctx+2B3EC

00007FFC196E4DD0  000000CAA6D0FBB0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA6D0FC30  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A241344  000000CAA6D0BD80  ZwGetContextThread+14

0000000000000374  000000CAA6D0BD88  0000:0000000000000000 

0000000000000004  000000CAA6D0BD90  0000:0000000000000000 

000000CAA6D0CE10  000000CAA6D0BD98  0000:0000000000000000 

0000000000000001  000000CAA6D0BDA0  0000:0000000000000000 

00000000000003F4  000000CAA6D0BDA8  0000:0000000000000000 

0000000000000001  000000CAA6D0BDB0  0000:0000000000000000 

00007FF6BC57CFDD  000000CAA6D0C2E0  0001:000000000004BFDD C:\Azeroth\core\worldserver.exe

00007FF6BC57B2F1  000000CAA6D0C970  0001:000000000004A2F1 C:\Azeroth\core\worldserver.exe

00007FF6BC57C494  000000CAA6D0CC70  0001:000000000004B494 C:\Azeroth\core\worldserver.exe

00007FFC17A8F84D  000000CAA6D0CD90  UnhandledExceptionFilter+1BD

00007FFC1A248585  000000CAA6D0CDD0  memset+2445

00007FFC1A22E726  000000CAA6D0CE40  __C_specific_handler+96

00007FFC1A2443AF  000000CAA6D0CE70  __chkstk+12F

00007FFC1A1D170E  000000CAA6D0D5B0  RtlVirtualUnwind2+35E

00007FFC1A2433BE  000000CAA6D0E3A0  KiUserExceptionDispatcher+2E

00007FF6BCAFE4F7  000000CAA6D0E650  0001:00000000005CD4F7 C:\Azeroth\core\worldserver.exe

00007FF6BCA9B93C  000000CAA6D0EBE0  0001:000000000056A93C C:\Azeroth\core\worldserver.exe

00007FF6BC563900  000000CAA6D0EE90  0001:0000000000032900 C:\Azeroth\core\worldserver.exe

00007FF6BC5711BF  000000CAA6D0FB40  0001:00000000000401BF C:\Azeroth\core\worldserver.exe

00007FF6BD317D1C  000000CAA6D0FB80  argon2id_verify_ctx+2B3EC

00007FFC196E4DD0  000000CAA6D0FBB0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA6D0FC30  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F594  000000CAA72FF760  NtRemoveIoCompletion+14

00007FFC17A47473  000000CAA72FF7C0  GetQueuedCompletionStatus+53

00007FF6BC567A20  000000CAA72FF910  0001:0000000000036A20 C:\Azeroth\core\worldserver.exe

00007FF6BC56D024  000000CAA72FF9F0  0001:000000000003C024 C:\Azeroth\core\worldserver.exe

00007FF6BC56CEB3  000000CAA72FFA50  0001:000000000003BEB3 C:\Azeroth\core\worldserver.exe

00007FF6BC550F7A  000000CAA72FFA80  0001:000000000001FF7A C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA72FFAB0  _recalloc+5C

00007FFC196E4DD0  000000CAA72FFAE0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA72FFB60  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F594  000000CAA73FF530  NtRemoveIoCompletion+14

00007FFC17A47473  000000CAA73FF590  GetQueuedCompletionStatus+53

00007FF6BC567A20  000000CAA73FF6E0  0001:0000000000036A20 C:\Azeroth\core\worldserver.exe

00007FF6BC56CFF2  000000CAA73FF7C0  0001:000000000003BFF2 C:\Azeroth\core\worldserver.exe

00007FF6BC56CEB3  000000CAA73FF820  0001:000000000003BEB3 C:\Azeroth\core\worldserver.exe

00007FF6BC550F7A  000000CAA73FF850  0001:000000000001FF7A C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA73FF880  _recalloc+5C

00007FFC196E4DD0  000000CAA73FF8B0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA73FF930  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA74FF620  NtWaitForAlertByThreadId+14

00007FFC1A20CE47  000000CAA74FF6A0  RtlSleepConditionVariableSRW+137

00007FFC17A5E319  000000CAA74FF6E0  SleepConditionVariableSRW+29

00007FFBF5842939  000000CAA74FF710  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFBF5842B7A  000000CAA74FF740  _Cnd_wait+3A

00007FF6BD287D48  000000CAA74FF770  0001:0000000000D56D48 C:\Azeroth\core\worldserver.exe

00007FF6BC5E4BBF  000000CAA74FF7A0  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA74FF7D0  _recalloc+5C

00007FFC196E4DD0  000000CAA74FF800  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA74FF880  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA75FFD40  NtWaitForAlertByThreadId+14

00007FFC1A20CE47  000000CAA75FFDC0  RtlSleepConditionVariableSRW+137

00007FFC17A5E319  000000CAA75FFE00  SleepConditionVariableSRW+29

00007FFBF5842939  000000CAA75FFE30  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFBF5842B7A  000000CAA75FFE60  _Cnd_wait+3A

00007FF6BD287D48  000000CAA75FFE90  0001:0000000000D56D48 C:\Azeroth\core\worldserver.exe

00007FF6BC5E4BBF  000000CAA75FFEC0  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA75FFEF0  _recalloc+5C

00007FFC196E4DD0  000000CAA75FFF20  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA75FFFA0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA76FF610  NtWaitForAlertByThreadId+14

00007FFC1A20CE47  000000CAA76FF690  RtlSleepConditionVariableSRW+137

00007FFC17A5E319  000000CAA76FF6D0  SleepConditionVariableSRW+29

00007FFBF5842939  000000CAA76FF700  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFBF5842B7A  000000CAA76FF730  _Cnd_wait+3A

00007FF6BD287D48  000000CAA76FF760  0001:0000000000D56D48 C:\Azeroth\core\worldserver.exe

00007FF6BC5E4BBF  000000CAA76FF790  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA76FF7C0  _recalloc+5C

00007FFC196E4DD0  000000CAA76FF7F0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA76FF870  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F4F4  000000CAA77FFDF0  ZwWaitForSingleObject+14

00007FFC17A1D52E  000000CAA77FFE90  WaitForSingleObjectEx+8E

00007FF6BC56CE53  000000CAA77FFEC0  0001:000000000003BE53 C:\Azeroth\core\worldserver.exe

00007FF6BC56EAD5  000000CAA77FFEF0  0001:000000000003DAD5 C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA77FFF20  _recalloc+5C

00007FFC196E4DD0  000000CAA77FFF50  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA77FFFD0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA78FF310  NtWaitForAlertByThreadId+14

00007FFC1A20CE47  000000CAA78FF390  RtlSleepConditionVariableSRW+137

00007FFC17A5E319  000000CAA78FF3D0  SleepConditionVariableSRW+29

00007FFBF5842939  000000CAA78FF400  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFBF5842B7A  000000CAA78FF430  _Cnd_wait+3A

00007FF6BC5EF484  000000CAA78FFB40  0001:00000000000BE484 C:\Azeroth\core\worldserver.exe

00007FF6BC5E4BBF  000000CAA78FFB70  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA78FFBA0  _recalloc+5C

00007FFC196E4DD0  000000CAA78FFBD0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA78FFC50  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A242F64  000000CAA79FF770  NtWaitForAlertByThreadId+14

00007FFC1A20CE47  000000CAA79FF7F0  RtlSleepConditionVariableSRW+137

00007FFC17A5E319  000000CAA79FF830  SleepConditionVariableSRW+29

00007FFBF5842939  000000CAA79FF860  ?_Winerror_message@std@@YAKKPEADK@Z+139

00007FFBF5842B7A  000000CAA79FF890  _Cnd_wait+3A

00007FF6BD0F6E48  000000CAA79FF8C0  0001:0000000000BC5E48 C:\Azeroth\core\worldserver.exe

00007FF6BC5E4BBF  000000CAA79FF8F0  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA79FF920  _recalloc+5C

00007FFC196E4DD0  000000CAA79FF950  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA79FF9D0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F4F4  000000CAA7AFFDF0  ZwWaitForSingleObject+14

00007FFC17A1D52E  000000CAA7AFFE90  WaitForSingleObjectEx+8E

00007FF6BC56CE53  000000CAA7AFFEC0  0001:000000000003BE53 C:\Azeroth\core\worldserver.exe

00007FF6BC56EAD5  000000CAA7AFFEF0  0001:000000000003DAD5 C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA7AFFF20  _recalloc+5C

00007FFC196E4DD0  000000CAA7AFFF50  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA7AFFFD0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F594  000000CAA7BFF8A0  NtRemoveIoCompletion+14

00007FFC17A47473  000000CAA7BFF900  GetQueuedCompletionStatus+53

00007FF6BC567A20  000000CAA7BFFA50  0001:0000000000036A20 C:\Azeroth\core\worldserver.exe

00007FF6BC56D024  000000CAA7BFFB30  0001:000000000003C024 C:\Azeroth\core\worldserver.exe

00007FF6BCACDA8E  000000CAA7BFFC40  0001:000000000059CA8E C:\Azeroth\core\worldserver.exe

00007FF6BC5E4BBF  000000CAA7BFFC70  0001:00000000000B3BBF C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA7BFFCA0  _recalloc+5C

00007FFC196E4DD0  000000CAA7BFFCD0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA7BFFD50  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23F534  000000CAA7CFF130  ZwReadFile+14

00007FFC17A241FB  000000CAA7CFF1A0  ReadFile+7B

00007FFC17D57859  000000CAA7CFF240  _read+209

00007FFC17D576F2  000000CAA7CFF280  _read+A2

00007FFC17D57A2A  000000CAA7CFF2B0  _fgetc_nolock+AA

00007FFC17D57BFD  000000CAA7CFF2F0  _fgetwc_nolock+FD

00007FFC17D75211  000000CAA7CFF350  fgetws+81

00007FF6BC573FF8  000000CAA7CFF7B0  0001:0000000000042FF8 C:\Azeroth\core\worldserver.exe

00007FF6BC550F3B  000000CAA7CFF7E0  0001:000000000001FF3B C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA7CFF810  _recalloc+5C

00007FFC196E4DD0  000000CAA7CFF840  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA7CFF8C0  RtlUserThreadStart+2B

Call stack:
Address   Frame     Function      SourceFile
00007FFC1A23FAF4  000000CAA7DFF3D0  NtDelayExecution+14

00007FFC1A1F7AAA  000000CAA7DFF410  RtlDelayExecution+2A

00007FFC179E7531  000000CAA7DFF490  SleepEx+71

00007FFBF5842E1C  000000CAA7DFF4E0  _Thrd_sleep+3C

00007FF6BC553AD3  000000CAA7DFF540  0001:0000000000022AD3 C:\Azeroth\core\worldserver.exe

00007FF6BC55DA6F  000000CAA7DFF720  0001:000000000002CA6F C:\Azeroth\core\worldserver.exe

00007FF6BC550F3B  000000CAA7DFF750  0001:000000000001FF3B C:\Azeroth\core\worldserver.exe

00007FFC17D76B4C  000000CAA7DFF780  _recalloc+5C

00007FFC196E4DD0  000000CAA7DFF7B0  BaseThreadInitThunk+10

00007FFC1A21E3DB  000000CAA7DFF830  RtlUserThreadStart+2B

### Expected Blizzlike Behaviour

Server downtime

### Steps to reproduce the problem

Server downtime

### AC rev. hash/commit

d7190451cf1d33e78fb55959b921c92a99f8d8e5

### Operating system

windows server2022 X64

### Custom changes or Modules

Anticheat
Eluna

**Comment by Kitzunu** [comment]
Dont paste crashlogs in the issue. Upload it to gist and post the link

Also release logs are useless, so can't do anything sith it
