### ISSUE TITLE
Every now and then all users disconnect from the server

### ISSUE THREAD

**Issue by nini-jjq** [azerothcore/azerothcore-wotlk#16177]
### Current Behaviour

From time to time, all users disconnect from the server, and the system log indicates that there is a kernel error.
The error message is as follows

kernel: [310657.037712] worldserver[122739]: segfault at 0 ip 00000000013b99bf sp 00007ffe12fede70 error 6 in worldserver[415000+1073000]
 kernel: [310657.037731] Code: 00 00 00 b9 0d 00 00 00 e8 ae eb 03 00 48 8b 3d 77 90 82 00 e8 52 be 05 ff 48 8b 7c 24 40 e8 28 b7 05 ff 48 89 05 e9 7f 86 00 <c7> 04 25 00 00 00 00 00 00 00 00 bf 01 00 00 00 e8 0c d7 05 ff 48

### Expected Blizzlike Behaviour

0632ff2   problem

### Steps to reproduce the problem

linux :ubuntu 20.04
syslog :

### AC rev. hash/commit

0632ff2   problem

### Operating system

ubuntu 20.04

### Custom changes or Modules

Eluna

**Comment by Kitzunu** [comment]
post a valid commit hash

also what you posted doesnt tell us anything
