### ISSUE TITLE
Illidan's bug

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#16197]
### Current Behaviour

Illidan lacks key skill cutting，And P2, it's a way of walking

### Expected Blizzlike Behaviour

Normal casting of shear reduces tank health，
P2 should be flying in the air and dropping an egg knife

### Steps to reproduce the problem

I don't know how to solve it

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/444793346de74d54a7b0b5cb9d9fc62be5772076+ 2023-05-05 22:39:36 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

WINDOWS2019

### Custom changes or Modules

mod-1v1-arena
mod-anticheat
mod-autobalance
mod-eluna

**Comment by yukijean** [comment]
Didn't anyone notice this problem

**Comment by GoMateoGo** [comment]
Can your Illidan end the battle from beginning to end?

I mean, can you pick up drops after the plot is completed?

**Comment by cavalierfly** [comment]
The same problem too, In phase 5 Illidan get out of combat, then can not be selected.

**Comment by leewheel** [comment]
Illidan does have a BUG in the P2 stage. If the player's group is destroyed in P2, then Illidan will become unselectable, and even if the player is resurrected, he still cannot select him to enter the battle again. He can only reset the dungeon and start again.

**Comment by heyitsbench** [comment]
This should be fixed with the recent rewrite.
