### ISSUE TITLE
[instances] disconnecting while solo in a raid instance with `Instance.IgnoreRaid = 1` leaves player character in a broken state

### ISSUE THREAD

**Issue by kjack9** [azerothcore/azerothcore-wotlk#16201]
### Current Behaviour

Enabling `Instance.IgnoreRaid = 1` allows you to enter raid instances solo without being in a raid OR a party. Once inside content works as normal unless you disconnect. Upon re-connection you are teleported outside the instance (entrance, graveyard, or default position) and the player's name shows as "Unknown" until logging out and back in again.

### Expected Blizzlike Behaviour

Reconnecting player should re-connect inside the dungeon with all player functionality and naming still correct.

### Steps to reproduce the problem

1. Start with a stock AC server with no modules, fresh deployment
2. Configure `Instance.IgnoreRaid = 1` in worldserver.conf
3. Level to 60 (method up to you, but I prefer `.levelup 59`).
4. Teleport to any raid instance (`.tel Zulgurub`) and enter
5. Logout successfully
6. Log back in and observe that you get two loading screens - one for the raid instance, followed by another for the zone you're being teleported to
7. Observe your new location outside the instance and that your name when targeting yourself is "Unknown"
8. Relog again to observe that your name is fixed

### Extra Notes
The exact location you end up in when relogging varies by raid instance. Zul'Gurub drops you right outside the entrance in Stranglethorn Vale. Molten Core, probably since it's "entrance" is in BRD, teleports you back to your racial starting position. I have also been teleported out to the graveyard, but I've yet to nail down exactly what causes that.

If the player is in a raid or a party (even if the other members are all offline) things work as expected.

### AC rev. hash/commit

Latest as of the time of this issue:
https://github.com/azerothcore/azerothcore-wotlk/commit/d282cce4af69110fa035954b3c81258a1e560b5e

### Operating system

Ubuntu 22.04 running Docker

### Custom changes or Modules

None

**Comment by kjack9** [comment]
Maybe related to #12969 ?

**Comment by zxnhrdz** [comment]
Yes, this problem has indeed existed for a long time.

**Comment by Kitzunu** [comment]
Here's your culprit

https://github.com/azerothcore/azerothcore-wotlk/blob/42a1650d3146e025d996ce5b9b5dfbd9bd8fbe88/src/server/game/Entities/Player/PlayerStorage.cpp#L6991-L6993

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/16306
