### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by langzaifei** [azerothcore/azerothcore-wotlk#16207]
### Current Behaviour

compile error: cant't link AddDelayedDamage when build 

### Expected Blizzlike Behaviour

solve this, 3Q!

### Steps to reproduce the problem

compile all

### AC rev. hash/commit

master

### Operating system

windows 10

**Comment by Nefertumm** [comment]
Update your core, it should be fine now. I've just compiled the whole core and no errors were shown.
