### ISSUE TITLE
[Karazhan] Ghostly Steward - Enrage

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#16212]
### Current Behaviour

1. Ghostly Steward use enrage between 0 and 30%
2. Ghostly Steward doesn't seem to wipe all threat.

### Expected Blizzlike Behaviour

https://www.wowhead.com/tbc/guide/trash-karazhan-strategy-burning-crusade-classic
>Enrage happens at 50%, increasing damage dealt and attack speed. When the Ghostly Steward Enrages, he wipes all threat.

https://www.wowhead.com/npc=16414/ghostly-steward#comments
>By 16438 (297 – 1·4) on 2007/02/23 (Patch 2.0.8)
At 50% they enrage and hit for 3k to 4k damage (against about 12.5k armor)

>By 27233 (566 – 1·5) on 2007/09/27 (Patch 2.1.3)		
Seem like they drop threat on 50% aswell

https://youtu.be/D8OZU8bg6lk?t=1896

### Source

https://www.wowhead.com/tbc/guide/trash-karazhan-strategy-burning-crusade-classic
https://www.wowhead.com/npc=16414/ghostly-steward#comments
https://youtu.be/D8OZU8bg6lk?t=1896

### Steps to reproduce the problem

.go cr 135301

### Extra Notes

Report from CC: https://github.com/chromiecraft/chromiecraft/issues/5578

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by elthehablo** [comment]
1 thing I don't really agree with is the line ('That was a 200 year old Pupellyverbos Port!') being said at frenzy. It makes more sense that, as it is now in the db already, it is being said when the creature hits you over the head with a bottle

**Comment by Santaria94** [comment]
> 1 thing I don't really agree with is the line ('That was a 200 year old Pupellyverbos Port!') being said at frenzy. It makes more sense that, as it is now in the db already, it is being said when the creature hits you over the head with a bottle

Yes, that comment appears to be incorrect. Looked at the video, they were saying "How dare you disturb the master's dinner!" and "That was wasted on the likes of you!" when getting enrage. For now I'm removing this from the report. Probably need to do more research on their text and the conditions when they say
