### ISSUE TITLE
[Hunter] Pet Disappear [$20]

### ISSUE THREAD

**Issue by Naxxramas-Server** [azerothcore/azerothcore-wotlk#1621]
[Hunter] Pet Disappear (Priority Hight)

##### SMALL DESCRIPTION:
Hunter pets disappear when the try to call stable pet or tame new beast with active dismissed pet.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When hunter have a dismissed pet and try to tame a beast or call stable pet with spell or stable master , message must appear and can't be possible to do this action

##### CURRENT BEHAVIOUR:
Actually , Hunter with dismissed pet can Tame a beast and call other pet in stable , and the dismissed pet equiped by the hunter disappear.
You can see more information in this post : 
https://github.com/WoWManiaUK/Redemption/issues/2853 (related to trinitycore)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make a Hunter with a pet equipped and dismiss the pet
2. Try to open stable or Tame a new beast
3. Your pet dismissed disappear after this actions.

**Comment by Deku** [comment]
Confirmed. When you dismiss your pet and pick one from the stable, your "current" pet disappears

**Comment by Ercules76** [comment]
I found the bug but have a question. If the pet is dismissed and i cast the spell 'Call Stabled Pet', it's right that i don't see the current pet at first slot?

**Comment by Pondaveia** [comment]
Just for notice, I'm looking at this issue 😉
