### ISSUE TITLE
[Silverpine Forest] Quest "The Dead Fields" - objective "Enter the Dead Fields"

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#16210]
### Current Behaviour

**By [asdff134242](https://github.com/asdff134242):**

[The Dead Fields][0] requires one to both enter the Dead Fields and to kill Nightlash to collect the Essence of Nightlash. However, the "enter the Dead Fields" objective never completes when entering the area, even after exiting and reentering it. This prevents completing the quest and turning it in.

[0]: https://wowgaming.altervista.org/aowow/?quest=437

### Expected Blizzlike Behaviour

**By [asdff134242](https://github.com/asdff134242):**

The "enter the Dead Fields" objective should be completed upon entering the Dead Fields area:
https://www.youtube.com/watch?v=XztwCwTeSME&t=135s

There are no comments about this part of the quest not completing properly on Wowhead:
https://www.wowhead.com/classic/quest=437/the-dead-fields

### Source

https://www.wowhead.com/classic/quest=437/the-dead-fields

### Steps to reproduce the problem

.quest add 437
.go zone 46.79 20.27 130

### Extra Notes

Report from CC: https://github.com/chromiecraft/chromiecraft/issues/5472

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Windows 10 build 19042.630

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by pangolp** [comment]
I will check it now and try to fix it.

**Comment by pangolp** [comment]
![WoWScrnShot_061523_212237](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/7e3542f6-49bd-4c10-af52-d9f9c7e6f64e)
![WoWScrnShot_061523_212300](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/928439a2-830f-48e9-af54-ecff784edc90)

On the downside, it's not a sniff, but it may work for now.
