### ISSUE TITLE
TBC enchants missing ICD

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#16233]
### Current Behaviour

Many tbc weapon enchants miss their internal cooldown and proc too often.

enchants affected are part of the list (not all affected!)
https://www.wowhead.com/wotlk/spells/professions/enchanting/name:weapon/min-skill-level:301/max-skill-level:375?filter=20;1;0

### Expected Blizzlike Behaviour

enchants should respect the ICD.

Deathfrost: 50% proc chance, 25 seconds ICD
Spellsurge: 15% proc chance, 50 seconds ICD
Battlemaster seems a bit more tricky: its 1PPM but has no explizit proc chance or ICD. But, it can proc only on auto-attack swings. not on ability usage

### Source

[https://www.wowhead.com/wotlk/spells/professions/enchanting/name:weapon/min-skill-level:301/max-skill-level:375?filter=20;1;0](https://www.wowhead.com/wotlk/spells/professions/enchanting/name:weapon/min-skill-level:301/max-skill-level:375?filter=20;1;0)

### Steps to reproduce the problem

.

### Extra Notes

Chromiecraft report

https://github.com/chromiecraft/chromiecraft/issues/5424

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Ubuntu

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by Samsequel** [comment]
Spellsurge is fixed already
Can't fix battlemaster myself, I don't know what the proc spell is for it.

**Comment by balleny** [comment]
https://wowgaming.altervista.org/aowow/?enchantment=2675
-> https://wowgaming.altervista.org/aowow/?spell=28005

https://www.wowhead.com/wotlk/spell=28004/enchant-weapon-battlemaster
-> https://www.wowhead.com/wotlk/spell=28005/battlemaster

**Comment by Samsequel** [comment]
yep its none of those

**Comment by Samsequel** [comment]
Nevermind, it just doesn't appear to use an aura to trigger it...
