### ISSUE TITLE
[PvP] Getting flagged through AoE abilities

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#16239]
### Current Behaviour

Using AOE abilities without being flagged for pvp, will flag you for pvp if the abilities hit an enemy player who is flagged for pvp.

### Expected Blizzlike Behaviour

without being flagged for pvp, aoe abilities shouldnt affect players of the opposite faction that are flagged, and not flag the player using the abilities.

### Source

https://wowwiki-archive.fandom.com/wiki/Bluewall?oldid=2089274

Also note it is not possible to become flagged through use of AOE attacks around players or NPCs, the attack will simply have no effect and will not flag you. Bear this in mind if you are fleeing from NPC guards and you try and AOE fear/snare/etc to escape as it will do nothing. This behaviour also prevents griefing attacks where flagged players could stalk a player using AOE to farm mobs.

### Steps to reproduce the problem

2 chars, opposite faction
flag char a for pvp
use aoe abilities like arcane explosion, volley, consecration, thunderclap, starfall, explosive trap in proximity on char b

same applies for "jumping" abilities like chain lightning, avengers shield, living bomb, seed of corruption

### Extra Notes

this is a critical bug IMHO, because it is on the one hand abused ingame, and also bannable.

not 100% sure about abilities like whirlwind, divine storm, swipe (bear). I would assume those should NOT have an effect except if the player is being targeted.

(additional source, use a translator tool of your choice: https://redmine.rising-gods.de/issues/12904)

Chromiecraft report:
https://github.com/chromiecraft/chromiecraft/issues/5253

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5e9b88a9a9ddf510ee2e7a95861988a1fb3e54ca

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/540eda2af9a21148a3d75a3db1964465de6064ad
