### ISSUE TITLE
(Spells): You can click off the Haunted aura from the Haunted Memento.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16248]
### Current Behaviour

The [Haunted Memento](https://wowgaming.altervista.org/aowow/?item=40110) gives a [Haunted](https://wowgaming.altervista.org/aowow/?spell=53768) aura. This aura can be right-clicked and removed.

### Expected Blizzlike Behaviour

The aura should only be removable by removing the Haunted Memento from your inventory (e.g. throwing to another player, placing in bank, etc).

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.additem 40110`
2. Right-click the aura.
3. Observe you can right-click the aura.

### AC rev. hash/commit

f2e01028cf4d3977b4e1c5a821f44097ec032975

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Kitzunu** [comment]
Is it supposed to be a positive aura?

**Comment by TimekillerTK** [comment]
Not sure if it was in WotLK, but that seems to be the case during Cataclysm. Some videos:
* https://www.youtube.com/watch?v=AWr5ZSvzk-I 
* https://www.youtube.com/watch?v=Rb7tY07neuI
* https://www.youtube.com/watch?v=iVIBMREHZiU

Posts on wowhead also seem to confirm it's a buff: 
* https://www.wowhead.com/wotlk/item=40110/haunted-memento#comments

**Comment by heyitsbench** [comment]
> Is it supposed to be a positive aura?

Yes.
