### ISSUE TITLE
Dustwallow Marsh large swamp frogs do not drop quest items

### ISSUE THREAD

**Issue by gaolei4408** [azerothcore/azerothcore-wotlk#16267]
### Current Behaviour

Dustwallow Marsh large swamp frogs do not drop quest items

### Expected Blizzlike Behaviour

Large swamp frogs cannot kill quest items

### Source

Large swamp frogs cannot kill quest items

### Steps to reproduce the problem

Large swamp frogs cannot kill quest items

### AC rev. hash/commit

Large swamp frogs cannot kill quest items

### Operating system

Windows11

**Comment by elthehablo** [comment]
This is a mess of an issue but I assume you mean this:

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/bb6dad7c-5438-4277-9cff-12df236b4978)

The database does have loot values for the mob called Giant Marsh Frog

**Comment by heyitsbench** [comment]
This issue has been reported on the CC repo [here](https://github.com/chromiecraft/chromiecraft/issues/4939) and [here](https://github.com/chromiecraft/chromiecraft/issues/5453). Seems the loot is not given when the creature is killed by an auto-attack.

**Comment by Marcelo20XX** [comment]
The problem is that the mob is a "critter", as soon as I changed its family to any other type I drops the quest loot...

**Comment by Kitzunu** [comment]
Add rev/hash
