### ISSUE TITLE
Quest "The Troll Cave" incorrect instructions

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#16262]
Original CC report https://github.com/chromiecraft/chromiecraft/issues/5593 confirmed.

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

[The Troll Cave](https://wowgaming.altervista.org/aowow/?quest=182) quest asks for 10 [Frostmane Troll Whelps](https://wowgaming.altervista.org/aowow/?npc=706) to be killed, but the actual objective is 14.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/8634df1e-99cd-4ac2-8924-1dd10e09c4db)

### Expected Blizzlike Behaviour

Both should be 14 in 3.3.5
in 4.03 the quest was changed to be 10

### Source
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/fc3bc688-57f0-4d93-90c0-7f26d0d07085)

https://wowpedia.fandom.com/wiki/The_Troll_Cave
https://wowpedia.fandom.com/wiki/The_Troll_Menace

### Steps to reproduce the problem

1. `.quest add 182`
2. Observe.

### Extra Notes

Spotted by `[EXDr] StunYo#7846` on the CC Discord.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Since the information was excluded in triage, I will point out that sniffs from Classic confirm both the objective/objective text say it should be 10 whelps.
