### ISSUE TITLE
[Karazhan] Spectral Performer Spotlight ability

### ISSUE THREAD

**Issue by v-mstrs** [azerothcore/azerothcore-wotlk#16274]
https://github.com/chromiecraft/chromiecraft/issues/5393

### Current Behaviour

Only works for mobs, it should also affect players. Range is too big, should be shown as debuff when standing in it

### Expected Blizzlike Behaviour

Spotlight will place a beam of light on the ground, increasing damage dealt for anyone inside, enemies or players. (aura as debuff)

### Source

https://www.wowhead.com/tbc/guide/trash-karazhan-strategy-burning-crusade-classic
https://youtu.be/Iv6zSyhmLGc?t=675

### Steps to reproduce the problem

1. .teleport Karazhan , enter
2. .go xyz -10917.5 -1745.3 90.4 532

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/00e42645b8b6

### Operating system

Linux Mint 21.1

**Comment by elthehablo** [comment]
Reported again at: https://github.com/chromiecraft/chromiecraft/issues/5618

**Comment by v-mstrs** [comment]
`INSERT INTO spell_linked_spell VALUES (29683, 32214, 0, "Spotilght should affect everyone");`
 from https://github.com/SunstriderEmu/BugTracker/commit/8c4235be673999ce424c911472d74d50cf7edf33
 You now do get the 20% dmg buff (shown as debuff) but it stacks still
 
 enemies get 50% that comes from [29683](https://www.wowhead.com/tbc/spell=29683/spotlight) ?? also stacks
![2023-06-19_15-36](https://github.com/azerothcore/azerothcore-wotlk/assets/104088833/308a91d4-77ff-4bf1-aa65-d2db54bfb2aa)
