### ISSUE TITLE
Some warnings in compilation

### ISSUE THREAD

**Issue by saliven1970** [azerothcore/azerothcore-wotlk#16280]
### Current Behaviour

Warning occurred during compilation.

/root/AzerothCore-335/src/server/game/Entities/Unit/Unit.cpp: ‘uint32 Unit::GetModelForForm(ShapeshiftForm, uint32) const’:

/root/AzerothCore-335/src/server/game/Entities/Unit/Unit.cpp:20680:59: Warning：‘enum TeamId’ and ‘enum Team’ [-Wenum-compare]
20680 |                 else if (Player::TeamIdForRace(GetRace()) == ALLIANCE)
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/AzerothCore-335/src/server/game/Entities/Unit/Unit.cpp:20759:59: Warning：‘enum TeamId’ and ‘enum Team’ [-Wenum-compare]
20759 |                 else if (Player::TeamIdForRace(GetRace()) == ALLIANCE)
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/AzerothCore-335/src/server/game/Entities/Unit/Unit.cpp:20764:54: Warning：‘enum TeamId’ and ‘enum Team’ [-Wenum-compare]
20764 |                 if (Player::TeamIdForRace(GetRace()) == ALLIANCE)
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/root/AzerothCore-335/src/server/game/Entities/Unit/Unit.cpp:20768:54: Warning：‘enum TeamId’ and ‘enum Team’ [-Wenum-compare]
20768 |                 if (Player::TeamIdForRace(GetRace()) == ALLIANCE)

### Expected Blizzlike Behaviour

Compilation warnings should not occur.

### Steps to reproduce the problem

1.cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/wow-335 -DCMAKE_BUILD_TYPE=Release -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
2.make -j4

### Extra Notes

Player::TeamIdForRace(GetRace()) == ALLIANCE
Does it need to be replaced by：
Player::TeamIdForRace(GetRace()) == TEAM_ALLIANCE

### AC rev. hash/commit

[a8bc892](https://github.com/azerothcore/azerothcore-wotlk/commit/a8bc892da3b4d4868cd7ebe3260c6927ec33b692)

### Operating system

OpenEuler22.03

**Comment by Kitzunu** [comment]
Not an issue per https://github.com/azerothcore/azerothcore-wotlk/commit/f6d11d526b9f54341075d92f62db7c543aba065d
