### ISSUE TITLE
(DB/Loot): Galak Windchaser drops mid-high level items.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16290]
### Current Behaviour

[Galak Windchasers](https://wowgaming.altervista.org/aowow/?npc=4096#drops:0-2-14+1) drops many items, many of which have a required level of 40.

### Expected Blizzlike Behaviour

Windchasers do not drop items with level requirements in excess of 30 at most.

### Source

[Wowhead](https://www.wowhead.com/wotlk/npc=4096#drops;0-2+16-20+1)

### Steps to reproduce the problem

1. Look at AoWoW/Keira loot entries for the creature (template ID of 4096) or kill him repeatedly.
2. Observe the items way above the expected levels.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/4131.

### AC rev. hash/commit

a8bc892da3b4d4868cd7ebe3260c6927ec33b692

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by sudlud** [comment]
#18796 / 65942555b51c0200fdf962bc968ec9002686417a
