### ISSUE TITLE
about ICC gunship rocket pack

### ISSUE THREAD

**Issue by ryoting** [azerothcore/azerothcore-wotlk#163]
**Description**:
use the rocket pack,jump to another gunship,then can't attack all creature,it's tip 'out of range,and can't use the rocket pack again.
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
Seems to work fine for me

**Comment by ShinDarth** [comment]
missing AC commit hash, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
