### ISSUE TITLE
(Crash) icecrown

### ISSUE THREAD

**Issue by WildBlizzard** [azerothcore/azerothcore-wotlk#16300]
### Current Behaviour

#----------------------------------------------------------------------#

>> ASSERTION FAILED

# Location '/root/Azerothcore/src/server/game/Maps/Map.h:682'
# Function 'getNGrid'
# Condition 'x < MAX_NUMBER_OF_GRIDS && y < MAX_NUMBER_OF_GRIDS'

# Debug info: 'Id: 631 InstanceId: 85 Difficulty: 0 HasPlayers: true
ScriptId: 728 ScriptName: instance_icecrown_citadel'

#----------------------------------------------------------------------#
/root/run_ser.sh: line 24:    19 Segmentation fault      (core dumped) ./worldserver

### Expected Blizzlike Behaviour

not crash

### Steps to reproduce the problem

Icecrown Fortress, Blood Prince Council, When Kresse release spell "Spark Spark".

### AC rev. hash/commit

f2e01028cf4d3977b4e1c5a821f44097ec032975

### Operating system

CentOS7.9

**Comment by heyitsbench** [comment]
Try to throw the crashlog in a [gist](https://gist.github.com/) next time, please.

**Comment by WildBlizzard** [comment]
> Try to throw the crashlog in a [gist](https://gist.github.com/) next time, please.

Sorry, its my fault...

**Comment by Kitzunu** [comment]
Post the crashlog. This doesnt help anyone
