### ISSUE TITLE
(DB): Name columns are accent-insensitive

### ISSUE THREAD

**Issue by r-o-b-o-t-o** [azerothcore/azerothcore-wotlk#16314]
### Current Behaviour

All tables and columns are created with `utf8mb4_unicode_ci`, which is accent insensitive. This means, among other things, that we cannot create characters that have the same name but with accents. For example, if there is a character named `Aa`, creating a character named `Äâ` will be impossible even though it does not exist yet.

*Note*: on MySQL, this could be fixed by using `utf8mb4_0900_as_ci`. For instance:
```sql
ALTER TABLE `characters` MODIFY `name` varchar(12) COLLATE utf8mb4_0900_as_ci NOT NULL;
```
However, this is not available on MariaDB and I am not aware of a character set that accomplishes this and exists on both MySQL and MariaDB ☹️

https://github.com/azerothcore/azerothcore-wotlk/assets/24357633/107bf15c-4f85-466e-906c-593e2b7fec9f

### Expected Blizzlike Behaviour

I believe players should be able to create characters with the same name as another but with accented letters.

### Steps to reproduce the problem

See video above

### AC rev. hash/commit

42a1650d3146e025d996ce5b9b5dfbd9bd8fbe88

### Operating system

Windows 11 x64, MySQL v8.0.31

**Comment by Kitzunu** [comment]
Fuck maria

**Comment by Tereneckla** [comment]
That's why Llègöläss was taken already

**Comment by Vyperhand** [comment]
This is a relatively new issue.  You can see in the armory that such characters do exist:
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/131016474/bfe1744e-a9f2-4b0b-8747-4ca6fca34b35)

And I was able to create Nícci on April 16th, despite Nicci already existing.  Then when I deleted and attempted to re-create her on May 12th, it no longer worked.

**Comment by r-o-b-o-t-o** [comment]
> This is a relatively new issue. You can see in the armory that such characters do exist:

My guess is it's related to https://github.com/azerothcore/azerothcore-wotlk/pull/15433
We probably had an accent insensitive charset on Chromie before, which was replaced by that PR probably

**Comment by Kitzunu** [comment]
https://github.com/TrinityCore/TrinityCore/commit/fb388298a0bf76402a6f1de35bdfcb33223d51bb

**Comment by Kitzunu** [comment]
That is supported by Maria too

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/16344
