### ISSUE TITLE
(Creature): Healing a Draenei Survivor puts the player into combat and flags the playerfor PvP.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16319]
### Current Behaviour

If the player heals a [Draenei Survivor](https://wowgaming.altervista.org/aowow/?npc=16483) as a part of the [Rescue the Survivors!](https://wowgaming.altervista.org/aowow/?quest=9283) quest, then they will both be put into combat and flagged for PvP.

### Expected Blizzlike Behaviour

The player should not be put into combat nor flagged for PvP.

### Source

Wrath Classic

### Steps to reproduce the problem

1. Create a draenei.
2. `.quest add 9283`
3. Use [Gift of the Naaru](https://wowgaming.altervista.org/aowow/?search=gift+of+the+naaru) on a survivor.
4. Observe your portrait.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/5503.

### AC rev. hash/commit

be48e3c2493b420c62c293897e321c0bf7c0483f

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
This likely has to do with the survivor having a `unit_flags` including 4096 (PVP), which it does not have in a 3.4.0 45435 sniff.

**Comment by v-mstrs** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/7308
