### ISSUE TITLE
(Crash) instance of icecrown 

### ISSUE THREAD

**Issue by WildBlizzard** [azerothcore/azerothcore-wotlk#16327]
### Current Behaviour

We were fighting in Icecrown Fortress, during Blood Prince Council, when Kresse released the spell 'Spark Spark', and the server crashed.
The crashlog is https://gist.github.com/WildBlizzard/fad354f663472a564e88b23073c966e5

### Expected Blizzlike Behaviour

not crash

### Steps to reproduce the problem

1. Go to Icecrown Fortress
2. Find Kresse
3. Fight with him when he release sepll "Spark Spark"

### AC rev. hash/commit

f2e01028cf4d3977b4e1c5a821f44097ec032975

### Operating system

CentOS7.9

**Comment by Kitzunu** [comment]
The crashlog is useless

**Comment by WildBlizzard** [comment]
> The crashlog is useless
What kind of crash log should I give you? The core.19 file is very large, about 3GB, and I only have this one

**Comment by r0m1ntik** [comment]
The error message "Segmentation fault" typically indicates an attempt to access unauthorized memory. This can occur when trying to access a null pointer, accessing unallocated memory, or dereferencing an invalid pointer.

From the given backtrace, it can be observed that the crash occurs during the call to the Map::EnsureGridCreated function and then to Map::GetHeight. This suggests that there may be an issue with accessing the grid or the map's height.

**Comment by sanctum32** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp#L119 in this line replace container ```c
ObjectData const creatureData[] =
{
    { NPC_SINDRAGOSA, DATA_SINDRAGOSA }
};```
to
```c
ObjectData const creatureData[] =
{
    { NPC_SINDRAGOSA, DATA_SINDRAGOSA },
    { 0, 0 } // END
};

**Comment by Kitzunu** [comment]
> > The crashlog is useless
> > What kind of crash log should I give you? The core.19 file is very large, about 3GB, and I only have this one

You need to build in RelWithDebInfo or Debug

**Comment by WildBlizzard** [comment]
I think it's my local map issue
