### ISSUE TITLE
Feature: Pre-Spawn / Event Spawn System

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#16323]
### Describe your feature request or suggestion in detail

There seems to be 2 types of summons in Blizz, through spells and without spells (CreatedbySpell: 0). In both cases creatures are spawned via CreateObject2

In short, what I've noticed is that creatures spawned via spells have simpler scripting, while those spawned via CreatedbySpell: 0 have more complex behaviours. Nearly all of these complex behaviours can be achieved via SAI and GUID scripting in a way that summon_groups cannot handle.

While I cannot prove all of it, I have a theory that creatures spawned with CreatedbySpell: 0 do not overlap. I.e. 2 cannot be spawned at the same time. I have examples of it in Additional Context section.

Note: Creatures with Invisibility auras appear by CreateObject1 when players can see them

### Describe a possible solution to your feature or suggestion in detail

This is what pre-spawns can do with guid scripting. All in DB: https://github.com/azerothcore/azerothcore-wotlk/pull/16254#issuecomment-1546803761

All this behaviour can be simulated via SmartAI, see the above link.

### Additional context

Example 1: The Mechanar Bridge event, which is triggered either by proximity to the pre-spawn or a serverside areatrigger. All creatures there. All spawned with CreateObject2 (real spawn) and not via spells

Example 2: The Shattered Halls Legionnaire Gauntlet event just before the barracks and sewers. Also spawned by CreateObject2 and not via spells.

Example 3: Naturalist Bite event in The Slave Pens. The 3 spawned adds have formations and waypoints

Example 4: The Deathforge Infernal Soul event. Every few minutes Summoner Skartax performs an event to "summon" an Infernal Soul, and this event plays every few minutes, regardless if the summoning is successful. But the kicker is that IT CANNOT BE "SUMMONED" IF IT'S ALREADY SPAWNED, or in other words, cannot overlap. If any of the 3  creatures spawned in the event are alive, the Infernal Soul refuses to spawn. 

Example 5: Mana-Forge questline in Netherstorm

Example 6: Kargath Bladefist in The Shattered Halls has adds that spawn via a creature (Warchief's Portal). The portal creature is spawned by (CreatedbySpell: 0) while the creatures it itself spawns are spawned via serverside spells. In contrast, Grandmaster Vorpil in Shadow Labyrinth has all his summons (even the dummy that handles half of the summons) done via spells.

Example 7: Brood of Anzu are spawned at 2 points in the encounter, however, **they cannot overlap**. If one group is already spawned, the second group will not spawn. Everything in the Anzu event, including summoning, is CreatedbySpell: 0

Example 8: Quest "Have You Ever Seen One of These?" in Zangarmarsh. The murlocs spawned cannot be spawned twice, i.e. only one set can be spawned at once. Using the item while they're already spawned consumes the item and does nothing, and does not complete the quest.

### Blizzard

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/b4916a07-c79c-4cdc-8322-675323d745de)

Blizzard handles many events through scripts as exemplified above. Creatures spawned by these are not created by spells (serverside or clientside), appear as CreateObject2 (not invisible beforehand), and generally have unique actions regardless of their entry.

**Comment by Gultask** [comment]
Another detail: TC's Dynamic Spawns does not support pre-spawns as it was considered a hack, from what I've heard.
Mangos seems to have pre-spawns to some extent which I've not looked much into (negative respawn timers)

**Comment by Grimdhex** [comment]
Seels to be resolve with the linked PR. I close this issue but reopen it if I'm wrong.
