### ISSUE TITLE
(Holidays): Holiday dates must be filled for the next however many years.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16325]
### Current Behaviour

We have run out of Darkmoon Faires.

### Expected Blizzlike Behaviour

We need more Darkmoon Faires.

### Source

Assumption based on the established eternal presence of the Darkmoon Faire.

### Steps to reproduce the problem

1. Open the calendar.
2. Observe the Darkmoon Faire is no more.

### Extra Notes

We just need to add more dates for events in `holiday_dates`. Shouldn't be too difficult.

### AC rev. hash/commit

be48e3c2493b420c62c293897e321c0bf7c0483f

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Kitzunu** [comment]
Is it just out of the calender? Because it shouldnt stop as the end time is 2030-01-01 06:00:00

**Comment by heyitsbench** [comment]
> Is it just out of the calender? Because it shouldnt stop as the end time is 2030-01-01 06:00:00

Yes, it only affects the in-game calendar, the events still play out in the world as expected.

**Comment by lemondsMs** [comment]
confirm

Darkmoon is displayed on the calendar

**Comment by kerricsson** [comment]
Good day, players at CC discovered this bug in game and started to talk about it in sever discord (because now it's time for DMF).

**Comment by Synful-Syn** [comment]
We should never have to manually feed by hand the upcoming recurrent world events such as Darkmoon Faire. It should have been automated in the first place. Otherwise, we'll just push the very same problem later.

**Comment by heyitsbench** [comment]
Whichever solution comes first should be acceptable.

**Comment by Gultask** [comment]
Could anyone see if this works?
https://gist.github.com/Gultask/c06f6dbb543594618164ffc2241c31ec

Uses the Classic schedule convention

**Comment by Nyeriah** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/47818697/a682602f-38db-471d-9ac1-075bf4e37058)

Doesn't seem to do anything

AFAIK that's one of AC's tables created with the idea of moving client data to the database, I am not sure if it's even implemented tbh

**Comment by Gultask** [comment]
I definitely managed to switch dates around for *existing* entries, but new ones don't appear for me

**Comment by heyitsbench** [comment]
> AFAIK that's one of AC's tables created with the idea of moving client data to the database, I am not sure if it's even implemented tbh

Doubt that, considering the table exists (and seems to work) on TC.

**Comment by Gultask** [comment]
Alright I figured it out after much fiddling...
It only accepts 25 entries. (???)

**Comment by Gultask** [comment]
I did, however, did not notice that the start date mentioned is for the building event and not DMF itself so it's starting every Tuesday 😩

**Comment by Gultask** [comment]
`#define MAX_HOLIDAY_DATES 26` ? why?

**Comment by heyitsbench** [comment]
> why?

Fun.

**Comment by Kitzunu** [comment]
It is due to client limitations
