### ISSUE TITLE
(Creature): Underground Orgrimmar Grunt.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16343]
### Current Behaviour

There is an [Orgrimmar Grunt](https://wowgaming.altervista.org/aowow/?npc=3296) (GUID: 10299) underground near the Nightsong Woods in Ashenvale.

### Expected Blizzlike Behaviour

There should not be an Orgrimmar Grunt underground anywhere, let alone Ashenvale.

### Source

Assumption.

### Steps to reproduce the problem

1. `.go xyz 3328.98 -1758.51 201.91`, `/tar Orgrimmar Grunt` / `.go c 10299`
2. Observe there is a grunt underground.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/5648.

### AC rev. hash/commit

0637170c3014d028784414400f4c92e4e9965bdf

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by elthehablo** [comment]
Any idea whether it's an extra, or missing somewhere and just in a wrong location?

**Comment by heyitsbench** [comment]
> Any idea whether it's an extra, or missing somewhere and just in a wrong location?

Quite frankly, if it's misplaced it doesn't really matter. In my opinion, if coordinates are *this* bad, something needs to be re-done from scratch. 😆
