### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ikkj** [azerothcore/azerothcore-wotlk#16349]
### Current Behaviour

crash
https://gist.github.com/ikkj/007091a3d85f3e9a160fded4aead8db1

### Expected Blizzlike Behaviour

1

### Steps to reproduce the problem

1

### AC rev. hash/commit

https://gist.github.com/ikkj/007091a3d85f3e9a160fded4aead8db1

### Operating system

Windows 2016

**Comment by Tony931023** [comment]
update your core first and check if it keeps crashing AzerothCore rev. d7e3dc01b546+ 2023-05-06 08:47:24 +0800

**Comment by Kitzunu** [comment]
Do you have a way to reproduce this? Because the instance map is null
