### ISSUE TITLE
Feature: I hope to extracting custom maps

### ISSUE THREAD

**Issue by Blandyoung** [azerothcore/azerothcore-wotlk#16348]
### Describe your feature request or suggestion in detail

I have found many maps online that can be read and used normally on the client, but the existing map extractor cannot extract the map, and I cannot use paths or pathfinding on the map.

The server will report an error:“Wrong area flag 0 in map data PLAYER_EXPLORED_ ZONES 1 +X( X must be< 128)”

**Comment by yuanf225** [comment]
Agreed. When using the extraction tool, you can select or extract all. mpq files on the client by default.

**Comment by Blandyoung** [comment]
> 同意。使用提取工具时，您可以选择或全部提取。默认情况下，客户端上的 MPQ 文件。

I imported the Panda Man map and extracted it, but the extractor displayed not such file

**Comment by Blandyoung** [comment]
![wow 2023-05-25 01-57-12](https://github.com/azerothcore/azerothcore-wotlk/assets/120236092/02bf696d-7877-408c-bedb-dfec53823cbd)
After I added zone music and environmental music, it was really amazing happy

**Comment by Blandyoung** [comment]
But NPC was unable to find its way and used random movement, which made me very disappointed

**Comment by Blandyoung** [comment]
Hope to have friends who enjoy studying maps to take action together.

**Comment by yuanf225** [comment]
How did you complete the selection?

**Comment by Kitzunu** [comment]
This works. See https://github.com/azerothcore/azerothcore-wotlk/issues/16740#issuecomment-1683351738
