### ISSUE TITLE
(DB/Text): Darnassus Sentinels have incorrect text for mage trainer directions.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16354]
### Current Behaviour

Currently [Darnassus Sentinels](https://wowgaming.altervista.org/aowow/?npc=4262) will say [the following text](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/21218dae-0878-4144-ae71-05d1aedd9e99) when asked for directions to the mage trainer.

### Expected Blizzlike Behaviour

They should instead say [the following text](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/49e5f460-d878-407c-a9e2-5ff0402716ab).

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.go c id 4262`
2. Interact with them.
3. Ask them for directions to the mage class trainer.
4. Observe their text.

### Extra Notes

Originally observed by @Vyperhand in the ChromieCraft Discord.

I obviously cannot verify 100% with sniffs (due to missing parser support for 3.4.1), but visually the POI flag for the trainer does seem to be in the same spot between Classic/AC.

### AC rev. hash/commit

8e91065412805f4674c54119bcd7a060d1f84e19

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by elthehablo** [comment]
Interestingly enough in `creature_text` at `ID` 15906 after some digging, it does seem to have the correct text in there

**Comment by heyitsbench** [comment]
`broadcast_text` is the Cata text, the `npc_text` entry is tied to it so it overrides with the broadcast (Cata) text.

**Comment by elthehablo** [comment]
> `broadcast_text` is the Cata text, the `npc_text` entry is tied to it so it overrides with the broadcast (Cata) text.

that shit is a mess. will give it another look tomorrow

**Comment by Kitzunu** [comment]
Remove the link to broadcast_text
