### ISSUE TITLE
Latest Commit not Compiling with Eluna Engine

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1635]
##### SMALL DESCRIPTION:
Latest Commit not Compiling with Eluna Engine

Throws these errors in VS2017 Community Edition:

10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1950): error C2065: 'BAN_ACCOUNT': undeclared identifier (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1959): error C2065: 'BAN_CHARACTER': undeclared identifier (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1963): error C2065: 'BAN_IP': undeclared identifier (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1974): error C2039: 'BanAccount': is not a member of 'World' (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>D:\AC\azerothcore\src\server\game\World\World.h(551): note: see declaration of 'World' (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1974): error C2065: 'BanMode': undeclared identifier (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1974): error C2146: syntax error: missing ')' before identifier 'banMode' (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1974): error C2146: syntax error: missing ';' before identifier 'banMode' (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1974): error C2059: syntax error: ')' (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1950): error C2051: case expression not constant (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1959): error C2051: case expression not constant (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1963): error C2051: case expression not constant (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)
10>d:\ac\azerothcore\modules\mod-eluna-lua-engine\luaengine\GlobalMethods.h(1969): warning C4065: switch statement contains 'default' but no 'case' labels (compiling source file D:\AC\azerothcore\modules\mod-eluna-lua-engine\LuaEngine\LuaFunctions.cpp)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should compile successfully like before the latest commit.

##### CURRENT BEHAVIOUR:

Not compiling successfully.

##### STEPS TO REPRODUCE THE PROBLEM:

Just try compile latest commit with Eluna module.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

30b0325

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

mod-eluna-engine (AzerothCore module)

**Comment by wizzymore** [comment]
This commit compiles eluna module but now the function Ban only works with BanMode in numbers (1 - Account, 2- Char, 3-IP). I made the fix so it compiles and bans the account if needed. The duration now must be like in game: "4s", "4d5m4s"
Example script:
```lua
local function OnLogin(event, player)
	Ban( 1, player:GetName(), "5s", "Test reason", player:GetName() )
	print("Banned")
end

RegisterPlayerEvent(3, OnLogin)
```

**Comment by gtao725** [comment]
Thx wizzymore! that worked! I do kinda wish AC could have their own fork of Lua Engine instead of depending on others, maybe they should just use yours haha!

**Comment by wizzymore** [comment]
@gtao725 keep in mind that this is not a fix, is just a temporary solution!

```cpp
enum BanMode
{
    BAN_ACCOUNT,
    BAN_CHARACTER,
    BAN_IP
};
```
```lua
Ban( banMode, nameOrIP, duration, reason, whoBanned )
```
banMode now works only as an integer ( 1 = BAN_ACCOUNT,  2 = BAN_CHAR, 3 = BAN_IP ) { i don't know how it was working before }
And note that BAN_CHARACTER is not working.

**Comment by gtao725** [comment]
noted! thx a a lot.

**Comment by wizzymore** [comment]
@gtao725 tell me if this commit works as it should with ban function please

https://github.com/wizzymore/Eluna/commit/3eaa54dc72f8f6ea7af7f692d99e07b5d1a60684

**Comment by wizzymore** [comment]
https://github.com/ElunaLuaEngine/Eluna/pull/286

**Comment by wizzymore** [comment]
This issue can now be closed

**Comment by gtao725** [comment]
> This issue can now be closed

@wizzymore thx so much, srry it was getting late, I didn't have time to try last nite. Just compiled and it worked like a charm! The BAN Commands also work flawlessly.
