### ISSUE TITLE
[server]Skill delay and increasing ‘Update time diff’ value.

### ISSUE THREAD

**Issue by zoo0074** [azerothcore/azerothcore-wotlk#16357]
### Current Behaviour

My server is configured with dual-socket Intel Xeon Gold 6148 processors, 40 cores, 128GB memory, and 100Mbps bandwidth. However, after running for about 2-3 hours, the ‘Update time diff’ value gradually increases, resulting in skill delay within the game.
`Line 1615: Update time diff: 169. Players online: 390.
Line 1626: Update time diff: 100. Players online: 389.
Line 1634: Update time diff: 106. Players online: 396.
Line 1646: Update time diff: 163. Players online: 392.
Line 1668: Update time diff: 123. Players online: 383.
Line 1678: Update time diff: 100. Players online: 385.
Line 1685: Update time diff: 52. Players online: 382.
Line 1691: Update time diff: 26. Players online: 385.
Line 1700: Update time diff: 91. Players online: 384.
Line 1706: Update time diff: 115. Players online: 391.`

### Expected Blizzlike Behaviour

After reviewing some previous submissions, I did not discover anyone else experiencing a similar issue. Could it be possible that the problem is due to mismatched configurations in the server’s worldserver.conf file? Below is some partial information from my worldserver.conf configuration.
`
LoginDatabase.WorkerThreads     = 16
WorldDatabase.WorkerThreads     = 16
CharacterDatabase.WorkerThreads = 16
LoginDatabase.SynchThreads     = 4
WorldDatabase.SynchThreads     = 4
CharacterDatabase.SynchThreads = 4
ThreadPool = 40
MapUpdate.Threads = 20
Network.Threads = 16
MapUpdateInterval = 100
Network.TcpNodelay = 1
SetAllCreaturesWithWaypointMovementActive = 0
PreloadAllNonInstancedMapGrids = 1
`

### Steps to reproduce the problem

After running for 2-3 hours, the CPU usage of the server significantly drops, and the ‘Update time diff’ value gradually increases until the server program is restarted, after which the problem is quickly resolved.

### AC rev. hash/commit

AzerothCore rev. fd6941de7c7e 2023-04-09 23:44:52 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.80.0
Using MySQL version: 80032
Using CMake version: 3.25.0
Compiled on: Windows 10.0.22000
Worldserver listening connections on port 35707
Realmlist (Realm Id: 1) configured in port 35707
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in Data/maps. Total size: 291014951 bytes
vmaps directory located in Data/vmaps. Total size: 658130721 bytes
mmaps directory located in Data/mmaps. Total size: 2192910844 bytes
Using zhCN DBC Locale as default. All available DBC locales: enUS zhCN zhTW
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-cfbg
- mod-eluna
- mod-learn-spells
- mod-transmog
- mod-weekend-xp

### Operating system

Windows sever2022

**Comment by Kitzunu** [comment]
Update your core. It is old.
A lot of fixes has been done to issues like this.
