### ISSUE TITLE
Good to start the authserver and worldserver, but the client crashed when I pressed the "create new character" button

### ISSUE THREAD

**Issue by GrissomWang** [azerothcore/azerothcore-wotlk#16362]
---------------------------
Wow
---------------------------
This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal Condition
Program:	F:\WOW_WOLK_PROGRAM\CLIENT\World of Warcraft\Wow.exe

Failed to read file item\objectcomponents\weapon\sword_2h_claymore_a_01.m2.

Press OK to terminate the application.

**Comment by AnchyDev** [comment]
Looks like an issue with your client and not the core.
