### ISSUE TITLE
can't learn scripted spells via command

### ISSUE THREAD

**Issue by ladiszlai** [azerothcore/azerothcore-wotlk#1636]
When you try to learn a spell from spell_script_names table, you got error "spell cannot be learned by using a command". If I remove its row from the table it will work what the hell ?

Hash: 4193898

**Comment by FrancescoBorzi** [comment]
@ladiszlai please add your AC version

**Comment by ladiszlai** [comment]
@FrancescoBorzi newest fresh compiled core

**Comment by FrancescoBorzi** [comment]
@ladiszlai ok but still please add the hash commit to keep track of when this issue was experienced

**Comment by Winfidonarleyan** [comment]
@ladiszlai,
```cpp
if (handler->GetSession()->GetSecurity() < SEC_CONSOLE && (bounds.first != bounds.second || spellDifficultyId))
{
    handler->PSendSysMessage("Spell %u cannot be learnt using a command!", spell);
    handler->SetSentErrorMessage(true);
    return false;
}
```

**Comment by ladiszlai** [comment]
@Winfidonarleyan Is there a fourth level ? I have level 3 GM acc and I could learn spells which was not using scripts.

**Comment by Winfidonarleyan** [comment]
@ladiszlai need change condition

**Comment by FrancescoBorzi** [comment]
ideally this should be configurable via DB to be consistent with other commands, but a quickfix is better than nothing so well done @poszer

**Comment by BarbzYHOOL** [comment]
i guess to have this fully done via DB is called "RBAC" :P

**Comment by ladiszlai** [comment]
Thank you for fixing this :)
