### ISSUE TITLE
Black Temple NPC Teleports Broken

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1639]
##### SMALL DESCRIPTION:

1. Spirit of Olum: https://wow.gamepedia.com/Spirit_of_Olum
https://wowgaming.altervista.org/aowow/?npc=23411

This NPC currently only teleports player to Sanctuary of Shadows after killing High Warlord Naj'entus and Supremus.

After killing the Illidari Council, the option to teleport players to Chamber of Command just before Illidan encounter is NOT WORKING.

2. Spirit of Udalo: https://wow.gamepedia.com/Spirit_of_Udalo
https://wowgaming.altervista.org/aowow/?npc=23410

This NPC DOESN'T OFFER ANY OPTION to teleport players to Chamber of Command just before Illidan encounter after killing the Illidari Council.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

See above.

##### CURRENT BEHAVIOUR:

See above.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Clear Black Temple up to Illidan, do not have to fight him.
2. Speak to Spirit of Olum near beginning of Black Temple and you see 2 options. Second option is supposed to take player directly to Chamber of Command, but it doesn't do anything.
3. Speak to Spirit of Udalo at Sanctuary of Shadows inside Black Temple, he offers no option to teleport players to Chamber of Command. Option is meant to appear after the Illidari Council has been cleared.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

4193898

##### OPERATING SYSTEM:

Win 7/Win 10/Win Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by grimgravy** [comment]
That's been fixed by trinitycore. In preview it will be available in PR

**Comment by FrancescoBorzi** [comment]
@grimgravy can you please import that fix or link the commit here so it can be imported?

**Comment by grimgravy** [comment]
Yes, I can
