### ISSUE TITLE
[TBC The Arcatraz] Warden Mellichar not being immune to priest MC can cause some bugging out

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#16399]
Originally reported on CC at: https://github.com/chromiecraft/chromiecraft/issues/5693
By: [TotallyNotMyAccount](https://github.com/TotallyNotMyAccount)

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

To start the Harbinger Skyriss encounter one has to aggro Warden Mellichar. If this is done with the priest spell "Mind Control" he spawns every miniboss twice. A second harbinger also spawns, but never aggros because the Warden is dead, since the first one killed him. Until his eventual demise the Warden also aggros the priest, following him, but not attacking him.

**elthehablo:**

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/7300cc3d-cb20-47b1-86d0-002ec0acef05)

**caption: Warden Mellichar out of his bubble, frolicking around, spawning multiple mobs**

### Expected Blizzlike Behaviour

Minibosses only spawn on their own instead of in packs of 2. The warden stays in his bubble.

### Source

Obviously a bug.

### Steps to reproduce the problem

1. Go to Arcatraz as a priest
2. Go to Harbinger Skyriss' room, clear all adds, don't touch the warden
3. Mind control the Warden
4. Watch the fireworks

### Extra Notes

Warden Mellichar is proooobably immune to MC (charm). But just to be sure this could use a test in retail

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
This is Blizzlike, lol.
We can (and should) add a countermeasure but in core it should remain as it's provable that the encounter can be broken from MC'ing Warden Mellichar

**Comment by elthehablo** [comment]
> This is Blizzlike, lol. We can (and should) add a countermeasure but in core it should remain as it's provable that the encounter can be broken from MC'ing Warden Mellichar

okidoki

**Comment by Gultask** [comment]
> kinda makes me wanna see it happen on live servers

It's anticlimactic. He just stays still forever and stares at the player
