### ISSUE TITLE
Feature: Ability to disable DungeonFinder in config file

### ISSUE THREAD

**Issue by Magissia** [azerothcore/azerothcore-wotlk#16397]
### Describe your feature request or suggestion in detail

I would like to DungeonFinder=0 to disable it in config file.

### Additional context

The example in the dist config file doesn't mention the possibility to disable it, it is assumed it is not possible.
If possible, it should be specified.

**Comment by Kitzunu** [comment]
use this
https://github.com/azerothcore/azerothcore-wotlk/blob/79d6f4e2334334822ecea16c06207b9701d1d81f/src/server/apps/worldserver/worldserver.conf.dist#L1300-L1310
