### ISSUE TITLE
Some importants NPC´s not doing their spells

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16421]
### Current Behaviour

Stormwind:
King Varyan https://wowclassicdb.com/wotlk/npc/29611 not doing his spells, only autoattack
Stormwind City Guard https://wowclassicdb.com/wotlk/npc/68 not doing spells, only autoattack
Officer Pomeroy https://wowclassicdb.com/wotlk/npc/14438 not doing spells, only autoattack
Officer Brady https://wowclassicdb.com/wotlk/npc/14439 not doing spells, only autoattack
Stormwind Royal Guard https://wowclassicdb.com/wotlk/npc/1756 not doing spells, only autoattack

Orgrimmar:
Orgrimmar Grunt https://wowclassicdb.com/wotlk/npc/3296 not doing their spells, only autoattack
Scout Tharr https://wowclassicdb.com/wotlk/npc/14377 not doing spells, only autoattack
Scout Manslayer https://wowclassicdb.com/wotlk/npc/14376 not doing spells, only autoattack
Scout Stronghand https://wowclassicdb.com/wotlk/npc/14375 not doing spells, only autoattack
Kor´kron Elite https://wowclassicdb.com/wotlk/npc/14304 not doing spells, only autoattack
Vol´Jin https://wowclassicdb.com/wotlk/npc/10540 not doing spells, only autoattack

### Expected Blizzlike Behaviour

These NPC´s must do their spells.

### Steps to reproduce the problem

1. Found them
2. Fight with them
3. Watch if they are using their spells

### AC rev. hash/commit

AzerothCore rev. 96a5224d927f+ 2023-04-22 07:25:31 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

x64

**Comment by Kitzunu** [comment]
Make one issue per npc.

**Comment by therelus** [comment]
Oh ok sorry xD i will make it, thanks you alot :)
