### ISSUE TITLE
Talents Inspecting from the same and opposit faction.

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#1642]
Inspecting has 2 variants: 
**1 (Enabled)** = **Everybody** can see Talents  of same and opposit faction.
**0 (Disabled)** = **No one** can see other people's talents.  Faction is no matter, only GM can see Talents.  But in this case player must to see tallents of players of his faction

**worldserver.conf**:
•    TalentsInspecting
•        Description: Allow inspecting characters from the opposing faction.
•                    Doesn't affect characters in gamemaster mode.
•        Default:     1 - (Enabled)
•                         0 - (Disabled)

**TalentsInspecting = 1**

**Comment by poszer** [comment]
Please fill the field hash commit ( Your AC version ) @Bogir

**Comment by poszer** [comment]
Oh, i understand now. Will post fix soon, thanks for report @Bogir

**Comment by BarbzYHOOL** [comment]
What's the issue??

**Comment by Deku** [comment]
This needs to follow the template for issues and add a proper explanation. Please fix it.

**Comment by poszer** [comment]
Like description said : 
**Allow inspecting characters from the opposing faction.**
Tested with configuration set to 1 and 0 .
They re both fine, i don't see any problem with this configs.
Images below:
![HordeinspectAlly](https://user-images.githubusercontent.com/41213210/55170318-9e93fc00-5176-11e9-881c-6e67020fc34b.jpg)
![Bothnormalplayersinspect](https://user-images.githubusercontent.com/41213210/55170319-9e93fc00-5176-11e9-86c8-e648b86ff3c1.jpg)
![hordeinspectallyconfig0](https://user-images.githubusercontent.com/41213210/55170320-9f2c9280-5176-11e9-9343-c3eefe11cf3e.jpg)

Closing this. Thanks for report anyway

**Comment by Bogir** [comment]
You tested it from GM account?  Very nice!

**Comment by BarbzYHOOL** [comment]
Your description and english was so bad that nobody understood

**Comment by poszer** [comment]
> You tested it from GM account? Very nice!
> 
> As i've said - only GM can see Talents. And you are start to testing by GM account. Where is the logic?

Tested with A/H players - GM also.
I ask you to fill template while reporting issue, you didnt.
Tou didnt even read the introduction there, where it clearly say this : 

IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE
