### ISSUE TITLE
(Creature) Orgrimmar Grunt not doing their spells

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16425]
### Current Behaviour

Orgrimmar Grunt https://wowclassicdb.com/wotlk/npc/3296 not doing their spells, only autoattack

### Expected Blizzlike Behaviour

This NPC must do spells

### Steps to reproduce the problem

1.Found them
2.Fight with them
3.Watch if they are using their spells

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/96a5224d927fde51860619abfe32e2fa5b3f14fa+ 2023-04-22 07:25:31 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

x64

**Comment by elthehablo** [comment]
Please provide source

**Comment by therelus** [comment]
Sorry for my no-know xD what you mean with source x.x , azerothcore? revision date of repack? :P

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/09081f9b-4641-4852-bfa9-c631e922470b)

**Comment by TheSCREWEDSoftware** [comment]
Copying and pasting as it is the same issue... Lack of source and information about this issue, searched for `Orgrimmar Grunt` in TBC and WOTLK of wowhead the only ablitlies is related to testing or dks. Closing this
