### ISSUE TITLE
(Creature) Defias Cutpurse not doing spells

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16433]
### Current Behaviour

Defias Cutpurse https://wowclassicdb.com/wotlk/npc/94 not doing spells, only auto attack

### Expected Blizzlike Behaviour

This NPC must do spells

### Steps to reproduce the problem

1.Found them
2.Fight with them
3.Watch if they are using their spells

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/96a5224d927fde51860619abfe32e2fa5b3f14fa+ 2023-04-22 07:25:31 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static) (worldserver-daemon)

### Operating system

x64

**Comment by elthehablo** [comment]
Spell is assigned in `smart_scripts`. If it's not working it might be a problem with the spell itself. Have you tried turning your back to the mob?

**Comment by elthehablo** [comment]
I assume the problem here lies in the fact that the ability requires energy. So changing the castflags should fix this

**Comment by therelus** [comment]
Yea i turned back but nothing, but I´m using a revision of AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/96a5224d927fde51860619abfe32e2fa5b3f14fa+ 2023-04-22, maybe they fixed it already :P

**Comment by elthehablo** [comment]
> Yea i turned back but nothing, but I´m using a revision of AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/96a5224d927fde51860619abfe32e2fa5b3f14fa+ 2023-04-22, maybe they fixed it already :P

Check referenced pull request

**Comment by elthehablo** [comment]
What is your source on this?

**Comment by elthehablo** [comment]
I will close this issue as the spell should not be present on wotlk. The report was correct that the spell was not working so I will close as completed and make a PR to remove the SAI from Defias Cutpurse
