### ISSUE TITLE
(Hunter) Spirit Beast too big.

### ISSUE THREAD

**Issue by ztyhw** [azerothcore/azerothcore-wotlk#16441]
### Current Behaviour

Hunter tamed Spirit Beast that are too big.
How to recovery to normal?
![a](https://github.com/azerothcore/azerothcore-wotlk/assets/22415068/9d4a7020-df05-49fd-9393-5fbb0f4c4b46)

![b](https://github.com/azerothcore/azerothcore-wotlk/assets/22415068/767e8cad-12bd-419f-8924-a0fa339ff26d)

![c](https://github.com/azerothcore/azerothcore-wotlk/assets/22415068/c96c8879-46d8-4c43-a8e9-52d1fbb9ccc3)

### Expected Blizzlike Behaviour

Blizzard's not so big.

### Steps to reproduce the problem

I don't know if anyone else's is that big.
I downloaded the latest version, debian 11 X64 compiled and ran it.
The data downloaded is (Full data (v16) - from 02/01/2023 to now).
I've changed many 3.3.5 clients all the same.

### AC rev. hash/commit

AzerothCore rev. 79d6f4e23343 2023-05-29 00:32:16 +0000 (master branch) (Unix, Debug, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100519
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-22-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Debian 11 x64

**Comment by pklloveyou** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/84bdcea0-7379-4b95-a84e-2a320d6583f7)
try this

**Comment by ztyhw** [comment]
@pklloveyou   Thank you very much, it has been fixed.
