### ISSUE TITLE
[WORLD] deposit

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1644]
##### SMALL DESCRIPTION:

Some deposits are in inaccessible areas and we cannot mine them. E.g like screenshot below
![WoWScrnShot_032719_173226](https://user-images.githubusercontent.com/31663279/55094597-fa974b80-50b6-11e9-8142-53f9e6648104.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

We should have access to the deposits 

##### CURRENT BEHAVIOUR:

Some deposits are in inaccessible areas and we cannot mine them

##### STEPS TO REPRODUCE THE PROBLEM:

1. go on Redridge Canyons
2. on screenshot you seen an exemple

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

W10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Deku** [comment]
Seems like this will be a loooong task 🤣

**Comment by BarbzYHOOL** [comment]
This can only be done manually for each node?

**Comment by poszer** [comment]
> This can only be done manually for each node?

Yep xD Need to find which are wrong positioned lol

**Comment by wizzymore** [comment]
So, we should create a PR that will be WIP and everyone can report bad spawns on deposits. Otherwise for only one man this would be a headache

**Comment by poszer** [comment]
> So, we should create a PR that will be WIP and everyone can report bad spawns on deposits. Otherwise for only one man this would be a headache

Yea, we can report them on this opened isuse :+1:

**Comment by BarbzYHOOL** [comment]
Members can edit the original issue and add a list.
