### ISSUE TITLE
Quest: ID: 11280 - Draconis Gastritis | have a bug

### ISSUE THREAD

**Issue by MrLanovskiy** [azerothcore/azerothcore-wotlk#16443]
### Discussed in https://github.com/azerothcore/azerothcore-wotlk/discussions/11522

<div type='discussions-op-text'>

<sup>Originally posted by **xp20035** April 25, 2022</sup>
Hi, 

I'm using your azerothcore server on a linux machine. I noticed that a quest in the game has a bug.
How can I fix this quest? 
The quest is: Draconis Gastritis id:11280

You can accept the quest from the NPC, but when you use the item, the dragon comes and just attacks and doesn't allow you to complete the quest. I've tested it several times.</div>

**Comment by Kitzunu** [comment]
Fill out the proper issue report. https://github.com/azerothcore/azerothcore-wotlk/issues/new?assignees=&labels=&projects=&template=bug_report.yml

**Comment by MrLanovskiy** [comment]
I need fix too
