### ISSUE TITLE
Elwynn Forest level 9 Riverpaw Outrunner sometimes attacks 3 times instead of once. Not through the thrashing mechanic

### ISSUE THREAD

**Issue by woodenfrog** [azerothcore/azerothcore-wotlk#16451]
### Current Behaviour

https://www.wowhead.com/classic/npc=478/riverpaw-outrunner

The Riverpaw `Outrunner`, and not the others like the `Runt`, attacks 3 times instead of once. The behavior happens every 3-4 hits, like he has gained 2 attacks for his next hit. Look at the timestamps: 3 attacks at 00:27:01
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/110529878/e62e9ad7-2769-4ac1-96c7-dc73821dbc17)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/110529878/ab808503-1a28-468d-bb56-f28c7286c715)

### Expected Blizzlike Behaviour

It should attack normally, hitting the player only once per attack.

### Source

-

### Steps to reproduce the problem

1. Find Riverpaw Outrunner in Elwynn Forest near Hogger
2. Aggro and watch the combat log

### Extra Notes

Sorry for this very clearly unprofessional bug report, it is my very first time using Github so I know absolutely nothing. 

### AC rev. hash/commit

5c3199857361+

### Operating system

Win 10

**Comment by Gultask** [comment]
> I honestly do not know what this is, sorry :((

you can get it from `.server info` :)

It actually is Thrash, it adds the aura on self after respawning, so it casts on around 25% of attacks iirc

**Comment by woodenfrog** [comment]
Oh, so I guess it is intended then. Sorry for bothering, at least now I know how github works!
