### ISSUE TITLE
Critical error causing server hang

### ISSUE THREAD

**Issue by wefgame** [azerothcore/azerothcore-wotlk#16457]
### Current Behaviour

The essence of reproduction:
A person who is not in a group with another person, hangs up any buff, for example, a paladin buff: id 48932, 25898 and enters a random dungeon search, there he re-enters the game world and the server freezes.

### Expected Blizzlike Behaviour

?

### Steps to reproduce the problem

The essence of reproduction:
A person who is not in a group with another person, hangs up any buff, for example, a paladin buff: id 48932, 25898 and enters a random dungeon search, there he re-enters the game world and the server freezes.

### AC rev. hash/commit

AzerothCore rev. cedd60cf485b+ 2023-06-01 10:52:39 +0500 (moonguard branch) (Win64, RelWithDebInfo, Static)
[20:09:46] Using SSL version: OpenSSL 1.1.1t  7 Feb 2023 (library: OpenSSL 1.1.1t  7 Feb 2023)

### Operating system

win 10

### Custom changes or Modules

no

**Comment by Kitzunu** [comment]
You are using custom changes. That rev doesnt exist

**Comment by Kitzunu** [comment]
Test it on a clean core before reporting issues
