### ISSUE TITLE
Feature: Change the minimum requirement for MariaDB version

### ISSUE THREAD

**Issue by The-GhostRider** [azerothcore/azerothcore-wotlk#16455]
### Describe your feature request or suggestion in detail

I will try to be short and concise.

The fact is this:
As for me, I use MariaDB/MySQL version:

**Lower than:** `MIN_MYSQL_SERVER_VERSION 100500u`
and
**Less than:** ```MIN_MYSQL_SERVER_VERSION 50700u```
**Less than:** ```MIN_MYSQL_CLIENT_VERSION 50700u```

I use this specific version, and not higher for personal reasons that are not related to this project, but the point is not to change the version to help me.
The point for which I open this suggestion is that: Since the Core works very well even with my version which is lower than the one currently used, why not make this project available also for those who for "X" reasons are forced to use a lower version?

And I can guarantee that with the settings set like this:
```
#if MARIADB_VERSION_ID >= 100600
#define MIN_MYSQL_SERVER_VERSION 100400u
#define MIN_MYSQL_CLIENT_VERSION 30203u
#else
#define MIN_MYSQL_SERVER_VERSION 50500u
#define MIN_MYSQL_CLIENT_VERSION 50500u
#endif
```

Everything works correctly without bugs or problems, plus you would solve a problem for me, because every time I update the Core I am forced to change these parameters every time.

### So the solution I suggest is:
**Change in File:** `src\server\database\Database\DatabaseWorkerPool.cpp`

**This:**
```
#if MARIADB_VERSION_ID >= 100600
#define MIN_MYSQL_SERVER_VERSION 100500u
#define MIN_MYSQL_CLIENT_VERSION 30203u
#else
#define MIN_MYSQL_SERVER_VERSION 50700u
#define MIN_MYSQL_CLIENT_VERSION 50700u
#endif
```

**Into this:**
```
#if MARIADB_VERSION_ID >= 100600
#define MIN_MYSQL_SERVER_VERSION 100400u
#define MIN_MYSQL_CLIENT_VERSION 30203u
#else
#define MIN_MYSQL_SERVER_VERSION 50500u
#define MIN_MYSQL_CLIENT_VERSION 50500u
#endif
```

**Comment by Kitzunu** [comment]
No. Need to stay 50700 because we dont support mysql 50500

**Comment by The-GhostRider** [comment]
Hi @Kitzunu, sorry but I don't understand what you mean with this statement:  **"because we dont support mysql 50500"**

- "We" = Who?
- "Don't Support" = Why?
- Is it a sort of "Version Racism" or something?

I just need to understand because I can't at moment.. I mean.. I can't see the point..

**Comment by Kitzunu** [comment]
Because MySQL 5.5 does not work with MySQL 8.0 support. Thats why it was deprecated nearly 3 years ago

**Comment by Kitzunu** [comment]
We always strive to, in the first part, support the most latest version of MySQL. And of that means deprecating old versions. Especiaally those who are EOL, then we do that.

I hopw this makes sense, otherwise tell me what is unclear and I can try to explain it better 👍

**Comment by The-GhostRider** [comment]
> Because MySQL 5.5/5.6 does not work alongside MySQL 8.0 support. Thats why it was deprecated nearly 3 years ago. And changing to 50500 would allow people to use 5.5 which isnt possible as the server can't boot with it
> 
> Base thing is that the older versions of MySQL cannot run Queries that newer versions can.

Ok, now that you've explained your point of view, your motivations, I understand why you oppose it, unfortunately, however, I still can't be on your side, and the reason is that this statement you made:

`And changing to 50500 would allow people to use 5.5 which isnt possible as the server can't boot with it`

 is wrong, and for "Wrong" I mean it doesn't reflect reality, **(if I understand what you meant).**
 This sentence does not reflect reality because I use MySQL version 50505 which corresponds to `mysql version Ver 15.1 Distrib 10.4.17-MariaDB, source revision 5fbfdae130950d0a5a07d4b909f3bf1ff0498d34` and the server works great, it has **NEVER** given me a problem, not even by chance.

`Because MySQL 5.5/5.6 does not work alongside MySQL 8.0 support. `
Then if you kindly explain this other statement to me because I'm not sure I have understood what you meant


> We always strive to, in the first part, support the most latest version of MySQL. And if that means deprecating old versions. Especiaally those who are EOL, then we do that.
> 
> I hope this makes sense, otherwise tell me what is unclear and I can try to explain it better 👍

I understand very well that the "EOL" versions **(by procedure**)  would be better avoided, because they no longer have support or updates, but these "rules" are only **Guidelines** they are not a **"Must"** to follow and this is because those **"Guidelines"** they don't really apply to everything.

Then, honestly talking to you, I can't tell you if there was a substantial difference between the **50500 version** and the version I use which is **50505** and maybe in the 50500 version the server doesn't work as you say..
But I can guarantee to you that in version 50505 everything works perfectly.

**Comment by Kitzunu** [comment]
If I understand you dont use MySQL, you use Maria?

**Comment by The-GhostRider** [comment]
> If I understand you dont use MySQL, you use Maria?

**I Use:**
```
XAMPP Version: 1.8.3
Control Panel Version: 3.2.1
```

**Comment by Kitzunu** [comment]
That did not really answer my question...

**Comment by The-GhostRider** [comment]
> That did not really answer my question...

Well, implicitly yes, because XAMPP doesn't use MySQL, but it does use MariaDB, so yes.. 😅

**Comment by Kitzunu** [comment]
Okay that will help me explain the situation. I will do that when I get home 👍

**Comment by The-GhostRider** [comment]
> Okay that will help me explain the situation. I will do that when I get home 👍

Thanks for your help. 🙂

**Comment by Kitzunu** [comment]
Okay I will do my best to explain this.

MySQL != MariaDB, I know you know that.

And AC primarily focus on supporting the most latest MySQL Version.
This means that while an earlier version of MariaDB may work, MariaDB minimum requirement is forced to increase when MySQL version is forced to increase as Maria is based on a MySQL fork.

What do I mean by this?
MySQL 8.0 cannot be supported alongside MySQL 5.5/5.6, therefore these versions had to be deprecated.
Maria versions that use it's library from MySQL 5.5/5.6 may however still work. But we cannot support that unless we open up these MySQL checks, which you proposed.

By opening up them, that would allow people to build with MySQL 5.5/5.6 which is not in anyway possible. As those versions cannot live alongside MySQL 8.0

So while I understand what you mean, MariaDB is unfortunately not prioritized over MySQL, and therefore it's minimum requirement needs to follow MySQL to not fuck up the MySQL support.

**Comment by The-GhostRider** [comment]
> Okay I will do my best to explain this.
> 
> MySQL != MariaDB, I know you know that.
> 
> And AC primarily focus on supporting the most latest MySQL Version, while maintaining MariaDB support where possible. This means that while an earlier version of MariaDB other than what is specifed as what we support may work, MariaDB minimum requirement is forced to increase when MySQL version is forced to increase as Maria is based on a MySQL fork.
> 
> What do I mean by this? MySQL 8.0 cannot be supported alongside stock MySQL 5.5/5.6, therefore these versions had to be deprecated. Maria versions that use it's library from MySQL 5.5/5.6 may however still work. But we cannot support that unless we open up these MySQL checks, which you proposed.
> 
> By opening up them, that would allow people to build with MySQL 5.5/5.6 which is not in anyway possible. As those versions cannot live alongside MySQL 8.0
> 
> So while I understand what you mean, MariaDB is unfortunately not prioritized over MySQL, and therefore it's minimum library requirement needs to follow MySQL to not fuck up the MySQL support.

Yes, now that you've explained it in detail, I understand what the difficulty is.
In practice the difficulty is to create a "Vulnerability" in the stability of the Core due to MySQL. Vulnerability which, however, does not appear in the "equivalent" of MariaDB, very clear.

But at this point, I'm thinking of something else.
I mean, people aren't stupid, or at least people who "Compile Core" have some background, and in AzerothCore we have miles and miles of "Guides" on how to do everything.
Does it cost so much to put a warning explaining that you don't have to compile with that version and it's at your own risk and that we don't take responsibility for any errors?
Sometimes a small warning, 2 well written words, are better than many debates.

Me, for example:
I compile with MySQL 8.0, and use Core with MySQL 5.5.5
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/1884642/90084be6-245d-4ade-a1f4-7cdb3c0f5334)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/1884642/74876fa3-0d4c-4c27-adc5-afc173c84204)

So as you see, the 2 things are not mutually exclusive..


.

**Comment by Kitzunu** [comment]
> I mean, people aren't stupid,

Yes they are x)

You should **never** run the core on different version Server DB from what you compiled with.
That *can* cause issues. That's also a reason why the checks are in place.

**Comment by The-GhostRider** [comment]
> > I mean, people aren't stupid,
> 
> Yes they are x)

Yes, even Shin tried to explain to me that the vision I had of people was too optimistic. 🤣
> 
> You should **never** run the core on different version Server DB from what you compiled with. That _can_ cause issues. That's also a reason why the checks are in place.

I'm not so sure about this statement of yours, since: since I've been here on AC, (since 2021), I've always done this and I've never encountered any problems. But I'll keep that in mind if something goes wrong.
> 
> But I am glad I could make myself clear enough. Hopefully it isnt too much of a hassle in your case. I have not encountered anyone, until now, which have had any issue updating their Maria version to one of the "Supported" ones by AC

Well, I made a suggestion, you replied, later explaining why my suggestion could not be implemented, and you were kind enough to explain it to me in detail.

Now I understand your point of view better, (which is not wrong), but I would have handled it differently, let's say..
Said this..

As for updating Maria's DB or using MySQL 8.0, the problem is not an "Update" problem, the fact is that I have a sort of "need" let's say in using this version, because if I use other more updated ones , some things I have go bad.

that's all my problem..
