### ISSUE TITLE
Quests "Big Bone Worm" and "Fumping", spawns disappear in 1 minute

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#16458]
Original CC report https://github.com/chromiecraft/chromiecraft/issues/5514 confirmed on my local

Related to https://github.com/azerothcore/azerothcore-wotlk/issues/13144

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

65-69

### Current Behaviour

Anything summoned by the Fumper- Big worms, small worms, sand gnomes- will despawn in one minute after summon, dead or alive, looted or not. This is more noticable during the big bone worm quest because it takes longer to kill.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/979cabf7-9dc2-4b26-a963-6bfaf4eaf737)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/9368ab69-6622-45da-b28b-6ef7210408e1)

### Expected Blizzlike Behaviour

It should behave like any other mob during combat and not despawn unless it goes out of combat and resets (player dies or runs out of range)

### Source

https://youtu.be/L6PdXZNUjpI?t=92 notice the time battle lasts over 1 minute and mob does not despawn

### Steps to reproduce the problem

1. `.go c 77628`
2. `.quest add 10930`
3. Kill a kodo use the fumper
4. Begin timer with whatever spawns
5. Auto attack for 1 minute
6. watch it vanish
7. `.go c 1977362`
8. `.quest add 10929`
9. Use fumper
10. Begin timer with whatever spawns
11. Auto attack for 1 minute
12. Watch it vanish.

### Extra Notes

SIde note: As many times as I tested this, I never once spawned sand gnomes during the big bone worm quest. Maybe it was just me?

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ce6ca597b54e64f328cacddae5f003cdc41a343d

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
This likely happens because on evade is called the moment the creatures appear. So we have to come up with a better event or some kind of script checking whether it is being "reset"

**Comment by elthehablo** [comment]
Maybe check with event type 25 instead of 7

**Comment by kerricsson** [comment]
I want also to add that this work has very weird (=bad) hitbox for melee players and it's very hard to find the right position to damage it properly.

**Comment by Samsequel** [comment]
> 

25 wont work, as it will trigger on spawn.
7 should work, but apparently it doesnt do what it says it does -> on creature EVADE attack.... unless it for some reason enters evade when spawning which is dumb

**Comment by elthehablo** [comment]
> > 
> 
> 25 wont work, as it will trigger on spawn.
> 7 should work, but apparently it doesnt do what it says it does -> on creature EVADE attack.... unless it for some reason enters evade when spawning which is dumb

I think it does enter evade upon spawning. I had this same issue trying to fix some stuff in the opera fight in kara

**Comment by elthehablo** [comment]
My hack-fix suggestion would be to let the evade mode check also check its health and only despawn when health is not at 100% and evading

**Comment by Samsequel** [comment]
I am trying something else

**Comment by Samsequel** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/20357406/53741c5a-c62e-42e6-9d0d-a0778eb60797)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/20357406/d091b51e-90e7-4d79-9345-18d6762da0ed)

**Comment by elthehablo** [comment]
I will beat you to it if I get out of this bed in time
