### ISSUE TITLE
i think i have a local ubuntu azerothcore server setup. Right now it is on localhost and i want to bind him to a static ip

### ISSUE THREAD

**Issue by Masoudahgl** [azerothcore/azerothcore-wotlk#16462]
### Discussed in https://github.com/azerothcore/azerothcore-wotlk/discussions/16460

<div type='discussions-op-text'>

<sup>Originally posted by **thermolab** June  4, 2023</sup>
i have no idea how to do that
i have tried a couple of things but did not work

any help would be appreciated</div>

**Comment by Kitzunu** [comment]
Issues are meant for bugs.

Keep questions to discussions, discord, stackoverflow and google.
