### ISSUE TITLE
problem npc [Kurzen Commando]

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#16467]
### Current Behaviour

They are invisible but they are seen
![WoWScrnShot_060423_133017](https://github.com/azerothcore/azerothcore-wotlk/assets/52524476/0c68318e-7295-4442-829b-f83aeb947682)

### Expected Blizzlike Behaviour

They should not be seen in invisible mode

### Steps to reproduce the problem

.go c 1627

### AC rev. hash/commit

rev. 79d6f4e23343

### Operating system

window server 2019 64bit

**Comment by v-mstrs** [comment]
You can see them because you are high level.
