### ISSUE TITLE
immune Druid Spell 

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#16468]
### Current Behaviour

https://github.com/azerothcore/azerothcore-wotlk/assets/52524476/53de04f3-5cd2-4648-84db-57ba2d92e591

### Expected Blizzlike Behaviour

None

### Source

spell_school_immune_mask = 0

https://github.com/azerothcore/azerothcore-wotlk/assets/52524476/09a2f0d9-b1dc-4cff-8baf-12d8e7be7320

### Steps to reproduce the problem

.go c 126974

### AC rev. hash/commit

rev. 79d6f4e23343

### Operating system

window server 2019 64bit

**Comment by Tereneckla** [comment]
https://www.wowhead.com/npc=28585/slag#comments:id=637235
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/50233983/49e99488-9c2e-4bbe-b652-40bef1409597)
