### ISSUE TITLE
Quest `Return to Brock` incorrect completion text

### ISSUE THREAD

**Issue by woodenfrog** [azerothcore/azerothcore-wotlk#16470]
### Current Behaviour

What client do you play on?
enUS

Faction
Alliance

Content Phase:
1-19

The quest mentions this part `I'm sure they're eager to use them on some fresh boar meat.`, which is from the modified version of the quest in Cataclysm patch 4.0.3. I have not checked the prior quests in this chain, I do not know if they happen to be the Cataclysm versions as well.

### Expected Blizzlike Behaviour

The correct quest text should be the one with `I'm sure they're eager to use them on the ore deposits of [Loch Modan]`.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/110529878/8928faa3-4dd0-4644-9feb-c31a808cb5f9)

### Source
I have already turned the quest in, so I can not attach a screenshot from in-game.

https://wowpedia.fandom.com/wiki/Return_to_Brock

Cataclysm version:
https://wowpedia.fandom.com/wiki/Return_to_Gremlock

### Steps to reproduce the problem

1. Read the quest text of `Return To Brock`

### AC rev. hash/commit

5c3199857361+

### Operating system

Windows 10

**Comment by elthehablo** [comment]
Yeah unfortunately there is a lot of creature texts that are overwritten from Cataclysm. Thanks for the report!
