### ISSUE TITLE
[Quest Item] - Miscellaneous quest item are not dropping

### ISSUE THREAD

**Issue by diluh** [azerothcore/azerothcore-wotlk#1647]
**Description:**

several quests are not dropping the [Quest Item]

**Current Behavior:**

after doing several quests I noticed that many of them do not drop the [Quest Item] some of them are:
https://wotlk.evowow.com/?quest=9420
https://wotlk.evowow.com/?quest=10450
There are many

I already changed the drop to 100% and still do not drop, if it is some configuration, please kindly help me.

**Expected behavior:** All quest items should drop.

**Steps to reproduce the problem:**

of the quest
Branch (s): Master

AC hash / commit: https://github.com/azerothcore/azerothcore-wotlk/commit/57a5f26eb1767325afcae1915e3054ff1105d3f3

**Operating system:** Ubuntu server 18.04 LTS

**Modules:** Are you using modules? if so, list them
Not
Other customizations: Are you using core / db patches or other customizations? If yes, please specify them here.
Not

**Comment by poszer** [comment]
Just tested, the drop rate is fine. Also the item can be obtained by killing mobs, i don't see any problem with these quests : 
Images below : 

![Screenshot_12](https://user-images.githubusercontent.com/41213210/55168522-460f2f80-5173-11e9-93dc-9d5d6851756d.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/41213210/55168524-460f2f80-5173-11e9-9663-c4265edc221c.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/41213210/55168526-46a7c600-5173-11e9-8217-82975bba23f0.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/41213210/55168527-46a7c600-5173-11e9-8a36-695616f728da.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/41213210/55168528-46a7c600-5173-11e9-92e5-aed9bb0e611d.jpg)
![Screenshot_9](https://user-images.githubusercontent.com/41213210/55168529-46a7c600-5173-11e9-974a-c08b9a270001.jpg)
![Screenshot_10](https://user-images.githubusercontent.com/41213210/55168531-47405c80-5173-11e9-92bb-0af8c78382d5.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/41213210/55168532-47405c80-5173-11e9-8b03-bfb2fe6a5d4c.jpg)

Closing this.
