### ISSUE TITLE
Explosive Shot Ranks

### ISSUE THREAD

**Issue by Manpower99** [azerothcore/azerothcore-wotlk#16480]
### Current Behaviour

Currently Explosive Shot if applied again by a lower rank of it it will reset the durations but that is not blizzlike.
the application of explosive shot (rank 3) will overlap the DoT of explosive shot (rank 4) previously used during LnL proc.

### Expected Blizzlike Behaviour

Spells such as Explosive Shot , Explosive Trap, Flamestrike of different ranks should apply different spell IDs that would not reset/overlap  them

### Source

https://www.wowhead.com/wotlk/spell=56344/lock-and-load#comments
to cite :
Just tested this with recount. When LnL procs you can cast explosive shot(rank 4) explosive shot(rank 3) explosive shot(rank 4) and it will get all 9 ticks and it does more damage than an explosive shot(rank 4) spam. Very handy when you need that big burst of damage and every second counts.

### Steps to reproduce the problem

Trigger Lock and Load 
1.Use Explosive shot rank 4
2.Use explosive shot rank 3 before the dot is over

### Extra Notes

Worth to note that the DoT from each explosive shot rank do not share a spell ID (they are different spell ID's) same goes for alot of spells such as flame strike and explosive trap

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

### Operating system

win10

**Comment by v-mstrs** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/8a01b194b12736b12da2a7180d74d0a221aeba73/src/server/game/Spells/Auras/SpellAuras.cpp#LL2035C1-L2035C115

**Comment by BugSquisher9000** [comment]
thats a nice code line there, feels like this guy did not like that mages could stack flamestrike and decided to just add it in.

**Comment by Tereneckla** [comment]
Except that flamestrike is a ground dot that is handled differently
Debuffs/Auras in fact generally do not stack

**Comment by BugSquisher9000** [comment]
Well I guess seed of corruption share the same fate as Explosive shot. Have anyone tested Living Bomb if two mages can use that on same target. I hope someone take their sweet time to fix this so I can go back and enjoy Survival
