### ISSUE TITLE
WaypointMovementGenerator::LoadPath: creature doesn't have waypoint path id: 0

### ISSUE THREAD

**Issue by whiskeytangofoxy** [azerothcore/azerothcore-wotlk#16485]
### Current Behaviour

After worldserver comes up, the console outputs errors related to various Dustbelcher NPCs:

`WaypointMovementGenerator::LoadPath: creature Dustbelcher Mauler (GUID Full: 0xf130000a9d0016b4 Type: Creature Entry: 2717  Low: 5812) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c0016b7 Type: Creature Entry: 2716  Low: 5815) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Shaman (GUID Full: 0xf130000a9e0016b8 Type: Creature Entry: 2718  Low: 5816) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c0016b9 Type: Creature Entry: 2716  Low: 5817) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Mystic (GUID Full: 0xf130000b5b0016ba Type: Creature Entry: 2907  Low: 5818) doesn't have waypoint path id: 0`

### Expected Blizzlike Behaviour

NPCs should have a waypoint path id.

### Steps to reproduce the problem

1. Clone from repo
2. Build according to documentation
3. Run worldserver

### AC rev. hash/commit

AzerothCore rev. 765b907b1688 2023-05-26 09:17:54 +0700

### Operating system

Ubuntu 22.04

**Comment by Riveir** [comment]
Also getting some of the same but different ```WaypointMovementGenerator::LoadPath: creature Dustbelcher Mauler (GUID Full: 0xf130000a9d00065f Type: Creature Entry: 2717  Low: 1631) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c000662 Type: Creature Entry: 2716  Low: 1634) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Shaman (GUID Full: 0xf130000a9e000663 Type: Creature Entry: 2718  Low: 1635) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c000664 Type: Creature Entry: 2716  Low: 1636) doesn't have waypoint path id: 0
WaypointMovementGenerator::LoadPath: creature Dustbelcher Mystic (GUID Full: 0xf130000b5b000665 Type: Creature Entry: 2907  Low: 1637) doesn't have waypoint path id: 0```
