### ISSUE TITLE
[Mage] Arcane Subtlety does not work

### ISSUE THREAD

**Issue by sassouiabd** [azerothcore/azerothcore-wotlk#16489]
### Current Behaviour

The talent Arcane Subtlety dispell resists component doesn't work.

https://youtu.be/a3F-mBaermY

### Expected Blizzlike Behaviour

"Reduces the chance your helpful spells and damage over time effects will be dispelled by 30%"

### Source

https://www.wowhead.com/wotlk/spell=12592/arcane-subtlety

### Steps to reproduce the problem

https://youtu.be/a3F-mBaermY

1. As a level 70 mage character, put any buff on you
2. Dispel it with a priest
You will notice that you are able to dispell almost 100% of the times.

The same behavior can happen with living bomb (damage over time)
if you try to dispel it as a priest you will be able to dispell it everytime.

### Extra Notes

The issue is pretty blocking for pvp for the 3 specs 
as frost mage you can have all your slows, ice nova,  ice barrier being dispelled immediatly.
As fire mage you have your living bomb (core talent) being dispelled instantly.
As arcane mage you have your slow (core talent) being dispelled instantly.

### AC rev. hash/commit
240d2928f1fde72f10e7cda84185011e33127156

### Operating system

Windows 10 x64

### Custom changes or Modules

This bug have been reproduced in chromie craft

**Comment by sassouiabd** [comment]
Can someones the flag invalid-missingHas. The SHA has been added in the description of the issue

**Comment by sassouiabd** [comment]
When investigating this issue, have in mind that the priest class has similair issue with the talent 
**Silent resolve** which is suppose also to reduce the chance your helpful spells and damage over time effects will be dispelled by 30%.
It maybe a general issue with this kind of talent or specifics  and different problems for each class.

**Comment by Nefertumm** [comment]
I took a look at the dispel chance with different spells, and it doesn't seem to be any issue. In fact, the dispel chance is being calculated just fine. 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19627365/6095c18c-0640-4471-bcfe-2db830333dac)
This is a log from console that I put as debug, where you can see the resistance of the aura that's going to be dispel. With that the core calculates the chance to dispel. From what I'm seeing, if you are using "Dispel Magic" from the priest, the description of the spell says that it removes 2 harmful or beneficial spells from you or your enemy, this means if you have just 1 beneficial spell on you, the dispel will roll 2 times on the same spell (and also the core calculates it that way).
I will investigate further more, but try with more than 2 auras on the mage and so

**Comment by Nefertumm** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19627365/ba94db82-664f-4039-bc15-6a42e485c024)
This is what happens usually, one roll fail and the other succeed or the other way around (although if it succeed on the first one, obviously it won't roll the second chance)

**Comment by sassouiabd** [comment]
I will try out with two aura on a mage or with two debuff on the priest at the same time and see what happens

**Comment by sassouiabd** [comment]
@Nefertumm 
I can confirm what you said after trying with 2 aura.
I have also tried with chaman and paladin dispells.
Everything seems working as expected.

We can close this issue.
Thank you for investigating <3

**Comment by sassouiabd** [comment]
@Nefertumm sorry to reopen this.
Unlike priest, paladin has one dispel and is able to dispell mage slow 
100% of the times.
Here is a video to showcase it : 
https://youtu.be/iy-TmP9xpYA

**Comment by laasker** [comment]
> 

As the tooltip says, helpful spells and damage over time effects, so Slow doesn't apply here

**Comment by sassouiabd** [comment]
what do you mean ? The dispell resistance works perfectly on frostbolt and its a slow.

**Comment by Tereneckla** [comment]
That would be the actual bug then

**Comment by sassouiabd** [comment]
i am going to verify this if frostbolt can't be dispell

**Comment by sassouiabd** [comment]
Ok frostbolt can be instant dispelled too with the talent ( i learn't something today).
@laasker was right 👌
