### ISSUE TITLE
Human Warlock Imp does not attack (except for Fireball)

### ISSUE THREAD

**Issue by jwh1981** [azerothcore/azerothcore-wotlk#16495]
### Current Behaviour

I created a new Human Warlock and found that the Imp pet does not Attack when Aggressive or Defensive. The Fireball attack does work but the Imp never leaves my side. Manually clicking Attack does not work either.

This may happen for other races with Warlock or other pets (after leveling up). I have not tested. I am going to level up this Warlock and see if I can recreate it with other pets.

### Expected Blizzlike Behaviour

When Aggressive, the Imp should attack a mob as soon as I attack. When Defensive, the Imp should attack when I am attacked.

### Steps to reproduce the problem

1. Create Human Warlock.
2. Acquire Summon Imp.
3. Cast Imp
4. Set to Aggressive or Defensive
5. Attack a mob

### AC rev. hash/commit

AzerothCore rev. 3fc0a5b4fde2 2023-06-07 11:42:56 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 12

### Custom changes or Modules

mod-ah-bot
mod-autobalance
mod-solo-lfg

**Comment by Gultask** [comment]
You mean melee attack?
Afaik the imp never melees targets, they only use Fireball

**Comment by heyitsbench** [comment]
Please provide a source. The imp does not have an auto-attack.

**Comment by jwh1981** [comment]
I stand corrected and was mistaken. I was not aware that it didn't have an auto-attack since its been ages since I've played a Warlock. Closing.
