### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#165]
**Description**:
Server crashes due to instance save manager

**Current behaviour**: Tell us what happens
When server tries to unbind all characters from save, server crashes

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Branch(es)**: master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:   Windows 10 x64

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Crash Log**:
[c0590a5cfc2e+_worldserver.exe_[23-9_21-41-42].txt](https://github.com/azerothcore/azerothcore-wotlk/files/505163/c0590a5cfc2e._worldserver.exe_.23-9_21-41-42.txt)
##

**Comment by ShinDarth** [comment]
Steps to reproduce the problem ?

**Comment by stryker09** [comment]
"When server tries to unbind all characters from save, server crashes"
^ @talamortis did you do a .instance unbind? or does this happen due to its daily reset? 
this would have been more widespread if its due to the daily reset though....
