### ISSUE TITLE
[server] Icecrown Gunship Crash

### ISSUE THREAD

**Issue by jshplayer** [azerothcore/azerothcore-wotlk#16511]
### Current Behaviour

Crash occurred during Icecrown Gunship battle, possibly relating to multiple alliance ship spawns out of place.

### Expected Blizzlike Behaviour

Not crash

### Source

https://gist.github.com/jshplayer/2abc5bfaccd654cfda35572ca7d82c01

### Steps to reproduce the problem

Random on Gunship event - does not occur every time.

### AC rev. hash/commit

AzerothCore rev. 4ce85d6d41f0+

### Operating system

Debian 10

**Comment by Kitzunu** [comment]
Dont upload random files, nobody want to download it. use gist.github.com

**Comment by jshplayer** [comment]
This looks to relate to a player DC'ing / logging off and the core being unable to place them back on the ship.

**Comment by jshplayer** [comment]
> Dont upload random files, nobody want to download it. use gist.github.com

done
