### ISSUE TITLE
[Beast Lord Armor] 4 piece set bonus does not work

### ISSUE THREAD

**Issue by v-mstrs** [azerothcore/azerothcore-wotlk#16512]
### Current Behaviour

Does not give the armor pen.

### Expected Blizzlike Behaviour

The Beast Lord 4 set bonus is supposed to give 85 armor penetration value after using Kill Command

### Source

Item description

### Steps to reproduce the problem

1. .learn 34026
2. .aura 37483 / or while wearing 4 pieces of Beast Lord Armor
3. use Kill Command
4. Hover over hit to see armor penetration / Attack target to notice no difference

### Extra Notes
https://www.wowhead.com/tbc/item-set=650/beast-lord-armor
https://github.com/chromiecraft/chromiecraft/issues/5448

### AC rev. hash/commit

0fb492828510

### Operating system

Linux Mint 21.1

**Comment by Gultask** [comment]
Hey, could you give us some more details?
Namely:

1. Easier steps to reproduce the issue. For example, commands .cast [SpellID] or .learn [SpellID] for Kill Command
2. Item set id or the ids of the armor set so we can quickly equip them
3. ID of the aura which the set gives, which can be looked up on a database like AoWoW or WoWHead

**Comment by Gultask** [comment]
awesome @v-mstrs, thank you very much!
