### ISSUE TITLE
Tcpnodelay/ delay

### ISSUE THREAD

**Issue by hebao22g** [azerothcore/azerothcore-wotlk#16529]
### Current Behaviour

AzerothCore rev. 30f475829a83 2023-05-23 22:39:55 -0300 (master branch) (Win64, Release, Static)
#    Network.Threads
#        Description: Number of threads for network.
#         Default:    1 - (Recommended 1 thread per 1000 connections)

Network.Threads = 10

#
#    Network.OutKBuff
#        Description: Amount of memory (in bytes) used for the output kernel buffer (see SO_SNDBUF
#                     socket option, TCP manual).
#        Default:     -1 - (Use system default setting)

Network.OutKBuff = -1

#
#    Network.OutUBuff
#        Description: Amount of memory (in bytes) reserved in the user space per connection for
#                     output buffering.
#         Default:    65536

Network.OutUBuff = 524288

#
#    Network.TcpNoDelay:
#        Description: TCP Nagle algorithm setting.
#         Default:    0 - (Enabled, Less traffic, More latency)
#                     1 - (Disabled, More traffic, Less latency, TCP_NO_DELAY)

Network.TcpNodelay = 1

#    MapUpdate.Threads
#        Description: Number of threads to update maps.
#        Default:     1

MapUpdate.Threads = 20
漫天过海 2023/6/13 13:57:45
#    ThreadPool
#        Description: Number of threads to be used for the global thread pool
#                     The thread pool is currently used for:
#                      - Signal handling
#                      - Remote access
#                      - Database keep-alive ping
#                      - Core freeze check
#                      - World socket networking
#        Default:     2

ThreadPool = 4

漫天过海 2023/6/13 13:57:52
#    LoginDatabase.WorkerThreads
#    WorldDatabase.WorkerThreads
#    CharacterDatabase.WorkerThreads
#        Description: The amount of worker threads spawned to handle asynchronous (delayed) MySQL
#                     statements. Each worker thread is mirrored with its own connection to the
#                     MySQL server and their own thread on the MySQL server.
#        Default:     1 - (LoginDatabase.WorkerThreads)
#                     1 - (WorldDatabase.WorkerThreads)
#                     1 - (CharacterDatabase.WorkerThreads)

LoginDatabase.WorkerThreads     = 8
WorldDatabase.WorkerThreads     = 8
CharacterDatabase.WorkerThreads = 8

#
#    LoginDatabase.SynchThreads
#    WorldDatabase.SynchThreads
#    CharacterDatabase.SynchThreads
#        Description: The amount of MySQL connections spawned to handle.
#        Default:     1 - (LoginDatabase.WorkerThreads)
#                     1 - (WorldDatabase.WorkerThreads)
#                     2 - (CharacterDatabase.WorkerThreads)

LoginDatabase.SynchThreads     = 16
WorldDatabase.SynchThreads     = 32
CharacterDatabase.SynchThreads = 32

### Expected Blizzlike Behaviour

The current server configuration should not experience such high latency
The server is 36 cores, 72 threads, and 64G
The bandwidth is 100Mb

### Source

#    Network.OutUBuff
#        Description: Amount of memory (in bytes) reserved in the user space per connection for
#                     output buffering.
#         Default:    65536

Network.OutUBuff = 524288

#
#    Network.TcpNoDelay:
#        Description: TCP Nagle algorithm setting.
#         Default:    0 - (Enabled, Less traffic, More latency)
#                     1 - (Disabled, More traffic, Less latency, TCP_NO_DELAY)

Network.TcpNodelay = 1

When the  Network.OutUBuff  setting here is less than this value （524288）, the delay will directly exceed 300ms（300 people online simultaneously）

### Steps to reproduce the problem

first：Set parameters like this
1000+ online
#    Network.OutUBuff
#        Description: Amount of memory (in bytes) reserved in the user space per connection for
#                     output buffering.
#         Default:    65536

Network.OutUBuff = 524288

#
#    Network.TcpNoDelay:
#        Description: TCP Nagle algorithm setting.
#         Default:    0 - (Enabled, Less traffic, More latency)
#                     1 - (Disabled, More traffic, Less latency, TCP_NO_DELAY)
Network.TcpNodelay = 1

Then start

Line 836: Update time diff: 25. Players online: 293.
	Line 845: Update time diff: 53. Players online: 336.
	Line 857: Update time diff: 65. Players online: 357.
	Line 865: Update time diff: 88. Players online: 378.
	Line 873: Update time diff: 92. Players online: 397.
	Line 885: Update time diff: 122. Players online: 416.
	Line 905: Update time diff: 100. Players online: 430.
	Line 911: Update time diff: 118. Players online: 442.
	Line 917: Update time diff: 114. Players online: 455.
	Line 927: Update time diff: 124. Players online: 467.
	Line 939: Update time diff: 185. Players online: 476.
	Line 948: Update time diff: 224. Players online: 489.
	Line 973: Update time diff: 144. Players online: 489.
	Line 986: Update time diff: 186. Players online: 505.

### Extra Notes

1000+ online
#    Network.OutUBuff
#        Description: Amount of memory (in bytes) reserved in the user space per connection for
#                     output buffering.
#         Default:    65536

Network.OutUBuff = 65536

#
#    Network.TcpNoDelay:
#        Description: TCP Nagle algorithm setting.
#         Default:    0 - (Enabled, Less traffic, More latency)
#                     1 - (Disabled, More traffic, Less latency, TCP_NO_DELAY)
Network.TcpNodelay = 1

When using these default settings, the program delay will directly exceed 1000+ms

### AC rev. hash/commit

AzerothCore rev. 30f475829a83 2023-05-23 22:39:55 -0300 (master branch) (Win64, Release, Static

### Operating system

windosserver2012

**Comment by pklloveyou** [comment]
The same issue exists in `WinServer 2019 X64`

**Comment by wzw1990** [comment]
You can try reducing the value of the Network.OutUBuff
Keeping it at the default value first all

**Comment by Kitzunu** [comment]
Dont just copy paste stuff into a report.
