### ISSUE TITLE
[PvP] Attacks through objects

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/azerothcore-wotlk#16528]
### Current Behaviour

It's releasing attacks from Houses through objects.

### Expected Blizzlike Behaviour

House attacks must not be released through objects.

### Source

![WoWScrnShot_061323_220658](https://github.com/azerothcore/azerothcore-wotlk/assets/19478417/f595f3dd-bee9-4cc2-8d98-623170f621bd)
![WoWScrnShot_061323_220648](https://github.com/azerothcore/azerothcore-wotlk/assets/19478417/2fa79053-b64b-40df-8497-50156c0c6fdc)
![WoWScrnShot_061323_220749](https://github.com/azerothcore/azerothcore-wotlk/assets/19478417/ea09266b-14a8-4692-a018-5d84e0d0f19d)
![WoWScrnShot_061323_220747](https://github.com/azerothcore/azerothcore-wotlk/assets/19478417/38fc0499-da6f-4fb0-80ab-47e53e8891dd)

### Steps to reproduce the problem

1. Join BG with a cast
2. Cast spell behind central warsong object or fence next to graveyard.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/79d6f4e2334334822ecea16c06207b9701d1d81f

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
Please use a valid source for issues. Screenshots of AC do not constitute valid sources.

There currently exists a [worldserver config option](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/apps/worldserver/worldserver.conf.dist#L410) to achieve the LoS you're expecting, but the way it currently is by default is blizzlike and correct.
