### ISSUE TITLE
[Item] Training sword 8178 with wrong random enchant suffix

### ISSUE THREAD

**Issue by gchekenny** [azerothcore/azerothcore-wotlk#16533]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/5745

What client do you play on?
deDE, enGB, enUS

Faction
Both

Content Phase:
1-19

Current Behaviour
Of Toughness, Of Beast Slaying and Of the Falcon should NOT be eligible enchantments for Training sword ID 8178

Expected Blizzlike Behaviour
Expected enchants for item 8178:
...of the Bear (12.9% chance)
+(1 - 2) Stamina , +(1 - 2) Strength
...of the Whale (11.3% chance)
+(1 - 2) Spirit , +(1 - 2) Stamina
...of the Eagle (11.2% chance)
+(1 - 2) Intellect , +(1 - 2) Stamina
...of the Tiger (10.9% chance)
+(1 - 2) Agility , +(1 - 2) Strength
...of the Boar (10.9% chance)
+(1 - 2) Spirit , +(1 - 2) Strength
...of the Monkey (10.8% chance)
+(1 - 2) Agility , +(1 - 2) Stamina
...of the Wolf (10.6% chance)
+(1 - 2) Agility , +(1 - 2) Spirit
...of Stamina (6.2% chance)
+(3 - 4) Stamina
...of Strength (6.2% chance)
+(3 - 4) Strength
...of Agility (5.9% chance)
+(3 - 4) Agility
...of Power (2.8% chance)
+(6 - 8) Attack Power

Source
https://www.wowhead.com/wotlk/item=8178/training-sword

Steps to reproduce the problem
.ad 8178

AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

Operating system
Ubuntu 20.04

Modules
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft

Tested. Issue confirmed, also found 2 additional wrong enchants: ...of beast slaying and ...of falcon
Sources https://www.wowhead.com/wotlk/item=8178/training-sword
https://www.wowhead.com/classic/item=8178/training-sword
https://wowpedia.fandom.com/wiki/Training_Sword

Of Toughness, Of Beast Slaying and Of the Falcon should NOT be eligible enchantments for Training sword ID 8178

![WoWScrnShot_061423_154919](https://github.com/chromiecraft/chromiecraft/assets/65800273/525063e6-48f4-4f46-8f42-4cc2c8c3f207)
![WoWScrnShot_061423_155633](https://github.com/chromiecraft/chromiecraft/assets/65800273/4dbbb01a-de76-4c75-b22e-a5fe13b65cd2)
![WoWScrnShot_061423_154916](https://github.com/chromiecraft/chromiecraft/assets/65800273/dcffe42c-c83e-4bfa-92ec-8303b01dcd8c)

**Comment by Kitzunu** [comment]
Here are all possible enchants that the swords can get

it is for `8178/training-sword` and `3192/short-bastard-sword` 

RandomProperty 5173 // item_enchantment_template entry 5173

<details><summary>Open/Hide</summary>

db_itemrandomproperties_12340
---
| id | NAME | name_lang_enus | 
| ---: | --- | --- | 
| 14 | of Agility | of Agility | 
| 17 | of Agility | of Agility | 
| 18 | of Agility | of Agility | 
| 22 | of Stamina | of Stamina | 
| 24 | of Strength | of Strength | 
| 29 | of Toughness | of Toughness | 
| 33 | of Quality | of Quality | 
| 91 | of Beast Slaying | of Beast Slaying | 
| 93 | of Agility | of Agility | 
| 96 | of Stamina | of Stamina | 
| 97 | of Strength | of Strength | 
| 197 |  | of Toughness | 
| 228 |  | of the Wolf | 
| 231 |  | of the Falcon | 
| 256 |  | of the Wolf | 
| 501 | of the Wolf | of the Wolf | 
| 502 | of the Wolf | of the Wolf | 
| 584 | of the Monkey | of the Monkey | 
| 585 | of the Monkey | of the Monkey | 
| 586 | of the Monkey | of the Monkey | 
| 587 | of the Monkey | of the Monkey | 
| 669 | of the Tiger | of the Tiger | 
| 670 | of the Tiger | of the Tiger | 
| 671 | of the Tiger | of the Tiger | 
| 672 | of the Tiger | of the Tiger | 
| 839 | of the Eagle | of the Eagle | 
| 840 | of the Eagle | of the Eagle | 
| 841 | of the Eagle | of the Eagle | 
| 842 | of the Eagle | of the Eagle | 
| 927 | of the Gorilla | of the Gorilla | 
| 1009 | of the Whale | of the Whale | 
| 1010 | of the Whale | of the Whale | 
| 1011 | of the Whale | of the Whale | 
| 1012 | of the Whale | of the Whale | 
| 1013 | of the Whale | of the Whale | 
| 1094 | of the Boar | of the Boar | 
| 1095 | of the Boar | of the Boar | 
| 1096 | of the Boar | of the Boar | 
| 1097 | of the Boar | of the Boar | 
| 1179 | of the Bear | of the Bear | 
| 1180 | of the Bear | of the Bear | 
| 1181 | of the Bear | of the Bear | 
| 1182 | of the Bear | of the Bear | 
| 1399 | of Fire Resistance | of Fire Resistance | 
| 1547 | of Power | of Power | 
| 1548 | of Power | of Power | 
| 1549 | of Power | of Power | 
| 1550 | of Power | of Power | 
| 1913 | of Holy Wrath | of Holy Wrath | 
| 1952 | of Frozen Wrath | of Frozen Wrath | 
| 2067 | of Concentration | of Concentration | 
| 2068 | of Concentration | of Concentration | 
| 2069 | of Concentration | of Concentration | 
</details>
