### ISSUE TITLE
2nd Boss in Serpent Shrine Cavern Not Spawning

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1653]
##### SMALL DESCRIPTION:
2nd Boss in Serpent Shrine Cavern does not spawn after fishing him up. The achievement pops but the fight just doesn't start.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://wow.gamepedia.com/The_Lurker_Below
https://www.youtube.com/watch?v=JhWuAKAwTaw

##### CURRENT BEHAVIOUR:

You fish, then when you successfully fish it up you see "enter combat", then immediately you see "out of combat", the lurker never spawns.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Enter Serpentshrine Cavern.
2.  Go to the Strange Pool. #2 from this map: http://mywow.wikidot.com/ssc. Stand anywhere on the circular enclosure around the Strange Pool (Glowing Light)
3.  Start fishing, you might get some random fish catches, that is fine. You know when you fished up boss when you see enter combat.
4. Then you will see yourself immediately out of combat without ever seeing the boss spawn.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

dfd0343

##### OPERATING SYSTEM:

Win 7/10/Server 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by comix1988** [comment]
issue already opened.
https://github.com/azerothcore/azerothcore-wotlk/issues/522
