### ISSUE TITLE
A crash problem caused by one character.

### ISSUE THREAD

**Issue by lemonmomomo** [azerothcore/azerothcore-wotlk#16536]
### Current Behaviour

One of my characters got stuck in the world interface, the world server crashed, but the other characters can play normally, I don't know what I did? I'm uploading my crash log. Can you take a look at it?
[c676a8283768+_worldserver.exe_[15-6_17-9-17].txt](https://github.com/azerothcore/azerothcore-wotlk/files/11756002/c676a8283768%2B_worldserver.exe_.15-6_17-9-17.txt)
[c676a8283768+_worldserver.exe_[15-6_16-57-34].txt](https://github.com/azerothcore/azerothcore-wotlk/files/11756004/c676a8283768%2B_worldserver.exe_.15-6_16-57-34.txt)

### Expected Blizzlike Behaviour

I want to know how the character caused the server crash? So I can avoid the next one.

### Steps to reproduce the problem

I don't know why

### AC rev. hash/commit

AzerothCore rev. c676a8283768+ 2023-06-13 08:10:35 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1t  7 Feb 2023 (library: OpenSSL 1.1.1t  7 Feb 2023)
Using Boost version: 1.81.0
Using MySQL version: 80031
Using CMake version: 3.26.3
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-autobalance
- mod-eluna
- mod-skip-dk-starting-area
- mod-transmog
- mod-weapon-visual

### Operating system

win10 x64

### Custom changes or Modules

- mod-ah-bot
- mod-autobalance
- mod-eluna
- mod-skip-dk-starting-area
- mod-transmog
- mod-weapon-visual
- npcbot

**Comment by heyitsbench** [comment]
In the future, please create a [gist](https://gist.github.com/) with your crash logs rather than upload the files here. [Here are the attached crash logs](https://gist.github.com/heyitsbench/3a175ff5d3de92c3fe60b1bfe4f0e48e).

**Comment by lemonmomomo** [comment]
@heyitsbench create a gist？This is a little difficult for me, but I can try to do it. If I can't do it right, I'll ask you again.

**Comment by heyitsbench** [comment]
> This is a little difficult for me, but I can try to do it.

You don't need to do it with this particular issue, as I've already done so for you. Just if you need to report any crashes going forward, please do use Gist.

> If I can't do it right, I'll ask you again.

Feel free to. If you'd prefer and are able, my Discord username is the same as here on Github (`heyitsbench`).

**Comment by lemonmomomo** [comment]
@heyitsbench 
Thank you very much for your patience.

**Comment by pklloveyou** [comment]
transmog_scripts.cpp line 42

**Comment by wzw1990** [comment]
From the crash logs, it should be that an error occurred when mod-transmog read the character settings. Check the data in the character_settings table?

**Comment by lemonmomomo** [comment]
Thank you for your patience. I only cleaned up the table content related to transmog, the character can enter the game normally, but the equipment they wear is gone, which is really strange. I felt I should address this issue to transmog's contributors.
