### ISSUE TITLE
Corrupted Ashbringer causes you to aggro neutral mobs and guard

### ISSUE THREAD

**Issue by GastonCK** [azerothcore/azerothcore-wotlk#16532]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/5776

hat client do you play on?
enUS, enGB

Faction
Both

Content Phase:
Generic

Current Behaviour
If you equip Corrupted Ashbringer, neutral/yellow mobs will aggro you as if they are hostile. Neutral Guards will also 'aggro' you but not attack, placing you in combat.

Expected Blizzlike Behaviour
No effect on regular yellow mobs or guards.

Source
PTR, equipping CA

Steps to reproduce the problem
Equip CA
Run to a yellow mob (like start zone mobs) and watch them aggro you like hostile mobs.
Teleport to Shattrath, and walk to city guard, watch them try to dismount and attack you, but reset instantly, keeping you in combat.

Extra Notes
No response

AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

Operating system
windows10, windows11

Modules
No response

Customizations
None

Server
ChromieCraft, PTR

Tested, Issue confirmed
Item: https://www.wowhead.com/wotlk/item=22691/corrupted-ashbringer#comments
Spell: https://www.wowhead.com/wotlk/spell=28282/ashbringer#comments

Being attacked by random neutral creatures: is INCORRECT behaviour
![WoWScrnShot_061423_125919](https://github.com/chromiecraft/chromiecraft/assets/65800273/44395b49-b7cf-46f7-aa8f-0e9a30ad8409)

Aggro and resetting neutral npcs: is INCORRECT behaviour
![WoWScrnShot_061423_133806](https://github.com/chromiecraft/chromiecraft/assets/65800273/94dd61e2-2bd5-4f71-a75d-928a1cd779a4)

Hostile to Argent Dawn: Works and is correct behaviour
![WoWScrnShot_061423_131701](https://github.com/chromiecraft/chromiecraft/assets/65800273/6ac31123-d887-45eb-b09a-ee7fd69b1300)

Friendly at Scarlet Monastery's Cathedral: Works and is correct behaviour
![WoWScrnShot_061423_132508](https://github.com/chromiecraft/chromiecraft/assets/65800273/83478aac-6626-46c0-8164-23ed450b427a)

**Comment by heyitsbench** [comment]
As obvious as the expected behavior might be, please *always* provide a valid source.

**Comment by gchekenny** [comment]
What would be a valid source for a case like this?

**Comment by heyitsbench** [comment]
> What would be a valid source for a case like this?

How about [a video from Classic](https://youtu.be/ka5iRCMhyVk?t=829)? The warrior wielding the Ashbringer charges past an [Alterac Ram](https://wowgaming.altervista.org/aowow/?npc=10990) without aggroing it from the Ashbringer. On AC, an act like this (since it involves getting close to the ram) *does* aggro, therefore AC's behavior is incorrect.
