### ISSUE TITLE
L70ETC Concert outside Shattrath issues.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16530]
### Current Behaviour

Currently there's a L70ETC performance in Terokkar Forest outside Shattrath City that occurs every Friday at one in the morning server time.

### Expected Blizzlike Behaviour

There should be pretty much four instances of these guys existing.
- [A permanent spawn in Silvermoon City](https://github.com/azerothcore/azerothcore-wotlk/issues/14911).
- [A performance in BRD every night at eight P.M.](https://github.com/azerothcore/azerothcore-wotlk/issues/8411) (drumset perma-spawned, as well as the crew).
- [A performance in World's End Tavern in Shattrath every four hours](https://github.com/azerothcore/azerothcore-wotlk/issues/14912) (no lingering spawns).
- A performance in Terokkar Forest outside Shattrath City that occurred every hour during August 3rd and 4th to celebrate Blizzcon 2007. **This is the event this issue refers to. It should only ever have happened August 3rd and 4th, 2007.** It should also have occurred every hour starting at midnight, supposedly for a total of ~48 performances.

### Source

[Bluepost of the era](https://web.archive.org/web/20080210151733/http://forums.worldofwarcraft.com/thread.html?topicId=676238677&pageNo=1&sid=1)

### Steps to reproduce the problem

1. Wait until one in the morning on a Friday.
2. Go southeast of Shattrath City.
3. Observe the band performing.

### Extra Notes

The performance at least seems to be pretty well scripted from what little I saw of it. 😛

### AC rev. hash/commit

c676a828376877e63da77fc1adc81ac2aa3daab0

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
I am inclined to believe the stage, bleachers, and bruisers were all lingering spawns during the time the band wasn't performing, but unsurprisingly it's hard to find evidence of this.

**Comment by heyitsbench** [comment]
It seems I misread the quoted bluepost. They state the performances would begin at midnight that night (the archive says the post was made July 31st, 2007 at 1:51:37 AM UTC, which would be July 30th, 2007 at 9:51 PM EST). At the latest, that means it started at midnight between July 31st and August 1st, meaning it lasted for ~4 days, though I suspect they more likely were using EST or thereabouts, which would start the event at midnight between July 30th and July 31st, lasting ~5 days. Still not every week, but at least twice the duration I thought it was.

**Comment by heyitsbench** [comment]
As can be seen in [this old recording](https://www.youtube.com/watch?v=ISA_nG5smy0), there are supposed to be torches surrounding the audience area. Given the DMF banners, it seems reasonable to me to assume that these are the same [Free Standing Torches 01](https://wowgaming.altervista.org/aowow/?object=180043) that can be seen in the [DMF event in Terokkar](https://wowgaming.altervista.org/aowow/?event=3), especially given the visual similarity. Obviously any placement would be speculative, but they should probably be placed at some point.

**Comment by Raz0r1337** [comment]
It seems that the concerts are broken again.

In the Worlds end Tavern I can hear the music, but I can't see the chars.

Outside of Shattrath the concert doesn't spawn and music is not played.
