### ISSUE TITLE
(Quest - Terokkar Forest) Taken in the Night

### ISSUE THREAD

**Issue by GastonCK** [azerothcore/azerothcore-wotlk#16541]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/5728#issue-1745571005

What client do you play on?
enGB, enUS

Faction
Horde

Content Phase:
61-64

Current Behaviour
Quest https://www.wowhead.com/wotlk/quest=10873/taken-in-the-night
If you cast a DoT spell on a "Netherweb Victim" (meaning that you don't kill it with one shot), you will enter into combat and the moob will chase you.

Expected Blizzlike Behaviour
The "Netherweb Victim" should remain in its position.

Source
https://www.youtube.com/watch?v=3B81h2C9g6I

Steps to reproduce the problem
Take quest from Scout Navrin at 31.4 75.6
Go to the quest zone and use a DoT spell on a Netherweb Victim, i.e. cast a "living bomb".
As you enter into combat, the Netherweb Victim will chase you moving form its original position until it dies and reveals the moob trapped inside.
Extra Notes
No response

AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

Operating system
Ubuntu 20.04

Modules
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft

Tested, issue confirmed. Netherweb victim chases you and attacks you.
![WoWScrnShot_061523_114108](https://github.com/chromiecraft/chromiecraft/assets/65800273/dd9e3ea1-f4c1-43e8-80ed-45269a1c27a0)
![WoWScrnShot_061523_114116](https://github.com/chromiecraft/chromiecraft/assets/65800273/a3dcb8af-8488-45c7-b894-baa7c90b4c76)

at 0:55 we can see that Netherweb victim should NOT chase you nor attack you. https://youtu.be/3B81h2C9g6I?t=55

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/14314
