### ISSUE TITLE
Running speed after charge

### ISSUE THREAD

**Issue by apostolov11** [azerothcore/azerothcore-wotlk#16540]
### Current Behaviour

I don't know if I make the right issue or if there is already knowing for this but here is what I mean. I play warrior and when I charge, intercept or intervene the first second after I charge I am slowed I don't know the exact speed that I am slowed but I am and in PvP is pretty crucial. The same thing is with flying mount when I am flying (280%) and land the first seconds I am slowed then I start running with normal speed. All this slowing is happening like 50% of the time not every time but most of the time. I try to see when this happens if there is something that i do or its the npc that i charge or some kind of buff but there is nothing 

### Expected Blizzlike Behaviour

I don't think that when i fly or charge (Intercept, intervene) i should be slowed unless i have some kind of slow from a player or a NPC. The right way to work is when i charge or lands i shoud run with normal speed.

### Steps to reproduce the problem

Charge an npc and the first second you are slowed. Land with mount and run on the ground with the mount and you are slowed

### AC rev. hash/commit

###USAGE: .server...
Possible subcommands:
|-server info
|-server motd

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
I've noticed this as well, happens with a wide variety of actions. Please attach a valid commit hash when you are able though, specifically copy the results of the `server debug` command on an account with sufficient GM level.

**Comment by heyitsbench** [comment]
@apostolov11 Did you experience this issue on your own local AzerothCore installation or on the ChromieCraft servers? I can reproduce it easily on CC, but not on my own server.

**Comment by apostolov11** [comment]
Hello, I experience it on ChromieCraft server

**Comment by heyitsbench** [comment]
> Hello, I experience it on ChromieCraft server

In that case, as has been pointed out to me by Nyeriah, this seems to be an issue with the Anticheat module CC uses, which should be reported on either the [Anticheat module repo](https://github.com/azerothcore/mod-anticheat/issues/new?assignees=&labels=&projects=&template=bug_report.yml) or the [ChromieCraft issue tracker](https://github.com/chromiecraft/chromiecraft/issues/new?assignees=&labels=&projects=&template=bug_report.yml) rather than the AC repo.

**Comment by apostolov11** [comment]
Thank you for the guidance, I will try to describe it as best as I can. I am not very familiar white those bug issues.
