### ISSUE TITLE
[NPC] Wounded Blood Elf Pilgrim (16993) - Incorrect behavior

### ISSUE THREAD

**Issue by GastonCK** [azerothcore/azerothcore-wotlk#16543]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/5727

What client do you play on?
enGB, enUS

Faction
Alliance

Content Phase:
61-64

Current Behaviour
At [24,76] in Hellfire Peninsula there's a npc called [Wounded Blood Elf Pilgrim](https://www.wowhead.com/tbc/npc=16993/wounded-blood-elf-pilgrim). This npc is Friendly to horde players and starts a quest that involves releasing her from her cage and escorting her to Falcon Watch.
As expected, she appears as unfriendly to Alliance players.
However, there is an incorrect behavior when approaching her as Alliance player.

While killing some Haal'eshi mobs, npc went through the bars of her prison and started attacking me. Damage and CCs on her worked properly, and Vanishing made her run back inside her cage.

Expected Blizzlike Behaviour
NPC should stay inside the cage where she is held prisoner and not be able to pull a T-1000 and go through the bars.

Source
https://www.wowhead.com/tbc/npc=16993/wounded-blood-elf-pilgrim
https://youtu.be/X6hhYPBU4Yc?t=61 here an alliance hunter and his pet passing by without being attacked (classic wow)

Steps to reproduce the problem
Have an alliance character
Go to Hellfire Peninsula in visible mode at around [24, 76]
Observe caged npc going out of her cage like her body was made of unbound atoms.

Extra Notes
No response

AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/5c31998573613c7564d4d5a9b050d2656b0e4c23

Operating system
Ubuntu 20.04

Modules
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft

Tested, Issue confirmed
Wounded blood elf pilgrim behaves as a non-caged hostile npc to alliance players and gets aggroed from afar.
![WoWScrnShot_061523_140507](https://github.com/chromiecraft/chromiecraft/assets/65800273/f603a7da-5809-4c81-8100-fc8d510cd374)
![WoWScrnShot_061523_140516](https://github.com/chromiecraft/chromiecraft/assets/65800273/e9e0ab42-eed8-4774-9960-9522e60019d1)

**Comment by Si1ker** [comment]
Blizzlike intended: Original TBC (2007) > TBC Classic

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/61223313/a4af4493-d52d-4b6e-8f84-f6a733fa2b69)

**Comment by heyitsbench** [comment]
> Blizzlike intended: Original TBC (2007) > TBC Classic

Is it not possible it was a bug fixed during TBC's original run? 2.0.12 is pretty dang early on.

**Comment by Si1ker** [comment]
> > Blizzlike intended: Original TBC (2007) > TBC Classic
> 
> Is it not possible it was a bug fixed during TBC's original run? 2.0.12 is pretty dang early on.

Only way to know if that's true would be with original tbc footage (vid).

**Comment by heyitsbench** [comment]
> Only way to know if that's true would be with original 2007 tbc footage (vid).

Or Wrath footage, but fair enough. But as so often comes up, isn't the general opinion of AC to fix blizzlike bugs (as this would likely be)?

**Comment by Si1ker** [comment]
I've seen both faces of the coin, meaning it applies or not depending on who looks into the PR.

By default, your statement is correct:

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/61223313/1996b802-4cb3-460c-a238-fb5e5468469f)

source: https://www.azerothcore.org/wiki/faq

**Comment by Si1ker** [comment]
> > Only way to know if that's true would be with original 2007 tbc footage (vid).
> 
> Or Wrath footage, but fair enough. But as so often comes up, isn't the general opinion of AC to fix blizzlike bugs (as this would likely be)?

I've seen both faces of the coin, meaning it applies or not depending on who looks into the PR.

By default, your statement is correct:

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/61223313/1996b802-4cb3-460c-a238-fb5e5468469f)

source: https://www.azerothcore.org/wiki/faq

**Comment by Si1ker** [comment]
@heyitsbench & @gchekenny , check https://github.com/azerothcore/azerothcore-wotlk/pull/16566 .
