### ISSUE TITLE
冰冠堡垒炮舰战斗，开船一会，整个azerothcore服务端就爆了 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by luchec** [azerothcore/azerothcore-wotlk#16554]
[http://file.wlk80.top/bg1.png](url)
[http://file.wlk80.top/bg2.png](url)

冰冠堡垒炮舰战斗，开船一会，整个azerothcore服务端就爆了 Segmentation fault (core dumped)，有哪位大神能解读一下吗

**Comment by heyitsbench** [comment]
You will need to upload your crash logs to a site like [gist](https://gist.github.com/) and post them here. You would also have to include your source's revision hash as well as any modules/modifications you have.
