### ISSUE TITLE
ICC difficulty error

### ISSUE THREAD

**Issue by GoMateoGo** [azerothcore/azerothcore-wotlk#16567]
### Current Behaviour

1. After killing the ICC10 Hero Lord, the cooldown time shows that 10 people are normal
2. After killing 10 normal difficulty lords, enter 10 hero mode again and discover that the 10 hero mode lord has also died

### Expected Blizzlike Behaviour

10 player normal difficulty and 10 player hero difficulty should be calculated as CD normally

And organisms should be distinguished. They do not affect each other

### Steps to reproduce the problem

1. Requires a character that passes the Heroic difficulty of 10 players

2. Enter 10 player difficulty and kill the first lord Check whether the cooling time of the replica is normal

3. Reenter into 10 player normal difficulty to check if the first lord is alive

### AC rev. hash/commit

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18229643/5ba51f03-047d-49bc-8f30-c8551b473478)

### Operating system

WIN11  22H2 (22621.1814)

### Custom changes or Modules

eluna
cfbg

#16571 b6088fb872e6d0d134840617e22c60d135568825 [b6088fb]

**Comment by pangolp** [comment]
For the report to be valid, you need to provide the compilation hash. If you did it via git, with it `.server info` you can get token information. Otherwise, if you downloaded the code, you should check what was the date you downloaded it. If you do not correct this, you will most likely be closed, so I suggest you look up the date as soon as possible and edit the issue, so that someone can modify the tag and it can be reviewed by someone else at some point.

**Comment by heyitsbench** [comment]
They did provide a revision hash, only issue is that it isn't valid for the typical AC repo.

**Comment by pangolp** [comment]
Right, I tried to search for it with that number, but I couldn't find it. You will have to run the command and check again, because with that value, it cannot be traced.

**Comment by GoMateoGo** [comment]
I obtained the latest information through git pull

b6088fb872e6d0d134840617e22c60d135568825 [b6088fb]

**Comment by Si1ker** [comment]
my pr got linked here xd

change it under "Custom changes or Modules" of your report to remove link.

**Comment by heyitsbench** [comment]
Even using that PR, the revision hash is still invalid.

**Comment by pklloveyou** [comment]
Instance.SharedNormalHeroicId = 1

**Comment by pklloveyou** [comment]
can close it now

**Comment by GoMateoGo** [comment]
The problem can be closed

Through debugging, it was found that it was due to the configuration file

The default value of Instance.SharedNormalHeroicId is 1 Normal after prohibition

I think this value should be disabled by default rather than enabled Or he should give us a hint

**Comment by GoMateoGo** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18229643/77fd44d7-23ff-4d69-a562-c9f60d746c20)
In the early days, the client would display hero mode, but now it is not.
This doesn't seem to be a normal phenomenon.
