### ISSUE TITLE
Mai'Zoth does not cast Frost Armor

### ISSUE THREAD

**Issue by GastonCK** [azerothcore/azerothcore-wotlk#16582]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/5556

What client do you play on?
enUS

Faction
Both

Content Phase:
40-49

Current Behaviour
Mai'Zoth does not cast Frost Armor according to his [AoWoW page](https://wowgaming.altervista.org/aowow/?npc=818).

Expected Blizzlike Behaviour
He should cast Frost Armor.

Source
Wrath Classic

https://www.wowhead.com/wotlk/spell=12544/frost-armor
https://www.wowhead.com/wotlk/npc=818/maizoth#abilities
https://youtu.be/_Ppcj-ZdT58?t=282

Steps to reproduce the problem
.go c id 818
Observe his lack of armor of frost.

Extra Notes
Tested, he does not use frost armor
![WoWScrnShot_061623_223931](https://github.com/chromiecraft/chromiecraft/assets/65800273/b2b57e00-1f03-4dae-9ec7-8a6cbfb76907)

you can use frost armor with mind control but he should be able to cast it without mindcontrol
![WoWScrnShot_061623_224549](https://github.com/chromiecraft/chromiecraft/assets/65800273/9aee1b2c-f70f-4093-b9ab-efe1e2b44b2b)

AC rev. hash/commit
https://github.com/chromiecraft/azerothcore-wotlk/commit/590dcca82b9c6e5d5f49fb5f954b084a88070f84

Operating system
Ubuntu 20.04

Modules
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft

**Comment by Gultask** [comment]
Easy to fix with Keira.

Add a row with event_type HAS_AURA, set repeat/cooldown to something like 3600ms or 5000ms.
