### ISSUE TITLE
[Serpentshrine Cavern] Greyheart Tidecaller don't cast Arcane Lightning and Virulent Poison

### ISSUE THREAD

**Issue by v-mstrs** [azerothcore/azerothcore-wotlk#16594]
### Current Behaviour

~~Greyheart Tidecaller don't cast Arcane Lightning or Virulent Poison~~ don't case Frostbrand weapon (proc)

### Expected Blizzlike Behaviour

~~Casting Arcane Lightning and Virulent Poison~~ casts Frostbrand weapon (proc)

### Source

https://www.icy-veins.com/tbc-classic/serpentshrine-cavern-raid-guides
https://wowpedia.fandom.com/wiki/Greyheart_Tidecaller
https://www.wowhead.com/tbc/npc=21229/greyheart-tidecaller#abilities;mode:n25

### Steps to reproduce the problem

1. Check creature's SAI / engage

### AC rev. hash/commit

2d8dd19e260c

### Operating system

Linux Mint 21.1

**Comment by ChrisCGalbraith** [comment]
- The Tidecallers cast a [Poison Shield](https://www.wowhead.com/tbc/spell=39027/poison-shield) which itself casts the [Virulent Poison](https://www.wowhead.com/tbc/spell=39029/virulent-poison#triggered-by). This appears to be working. However, I do not see the [Frostbrand Attack](https://www.wowhead.com/tbc/spell=38617/frostbrand-attack) triggered by [Frostbrand Proc](https://www.wowhead.com/tbc/spell=38620/frostbrand-proc) in the SAI

- These are not the NPCs that cast Arcane Lightning. [Greyheart Nether-Mage](https://www.wowhead.com/tbc/npc=21230/greyheart-nether-mage#abilities;mode:n25) does.
