### ISSUE TITLE
Crossfactionbg

### ISSUE THREAD

**Issue by ahuraa** [azerothcore/azerothcore-wotlk#166]
any body can't add crossfaction bg ?

i add crossfaction bg 

bot bg doors no't open and no start bgs
##

**Comment by ShinDarth** [comment]
@ahuraa you can open a PR, so other people can review your code and help you.. otherwise it's hard to help you

**Comment by ahuraa** [comment]
please help me

**Comment by cooler-SAI** [comment]
@ahuraa , post private 5.4.8 from wowsource and I can help you )))

**Comment by ahuraa** [comment]
why wowsource ?

help me here

**Comment by cooler-SAI** [comment]
@ahuraa  coz you have it)))

**Comment by ahuraa** [comment]
i no have wowsource i no have vip account in wowsource wtf?

can help me or not?

**Comment by HeartWell** [comment]
Not

**Comment by ahuraa** [comment]
why?

**Comment by cooler-SAI** [comment]
coz life is pain xD

**Comment by ahuraa** [comment]
no i not from spain 

please help me to fix it

**Comment by HeartWell** [comment]
Please help me to fix hunt pet)

**Comment by cooler-SAI** [comment]
Please help me make azerothcore better

**Comment by Obitus1** [comment]
@ahuraa Download this [https://www.mediafire.com/?xvb8qzbp7abbuxz](url)

**Comment by ahuraa** [comment]
@Obitus1  ty very very  its work?

**Comment by Obitus1** [comment]
This is working.
https://www.mediafire.com/?2m00xe09tae50ty
I've tested it on a fresh azerothcore source which I downloaded and compiled today.

**Comment by HeartWell** [comment]
@cooler-SAI All afraid of Azeroth because your system modules.

**Comment by ShinDarth** [comment]
why don't you guys create a [PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) or a [module](https://github.com/azerothcore/azerothcore-wotlk/wiki/Create-a-Module) for it?

**Comment by ahuraa** [comment]
compile error my friend

**Comment by HeartWell** [comment]
Correct the error or you can not it?

**Comment by Obitus1** [comment]
@ahuraa  In VS go to Solution Explorer > game > right click on Header Files > Add > Existing Item and search in your source for Cfbg.h file
After that right click on Source Files > Add > Existing Item and add Cfbg.cpp

**Comment by ahuraa** [comment]
can make new patch ?

**Comment by bigkoroush** [comment]
i got some error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: unsigned char __cdecl Unit::getRace(bool)const " (?getRace@Unit@@QEBAE_N@Z)	worldserver	I:\gameserver\source\azerothcore-patch\azerothcore-wotlg.git64\src\worldserver\scripts.lib(instance_culling_of_stratholme.obj)	1

**Comment by bigkoroush** [comment]
oh my wrong :) that fiix...

**Comment by ahuraa** [comment]
are you test it? working fin?

**Comment by ahuraa** [comment]
When two of the same faction enters the BG he is showing like even ally.
You can not really attack and dies when he needs to go to the cemetery of his faction not according to the crossfaction
for example two players enter the alliance BG, one goes to horde and another to ally ... when you will try to attack it is impossible because it is saying that you can not attack.
Because it is as if it were exactly the same faction!

So there is no gameplay the crossfaction is useless from that!

**Comment by bigkoroush** [comment]
yeah fine i test that

**Comment by ahuraa** [comment]
in game working fine?

**Comment by ahuraa** [comment]
i have problem to login

login in game and crash

**Comment by ShinDarth** [comment]
@ahuraa please provide the crash dumps, otherwise we don't know how to help you

**Comment by ahuraa** [comment]
http://uplod.ir/apjqhwml5s3e/unknown_worldserver.exe_[21-10__-10-48].txt.htm

this is crash dumps

**Comment by bigkoroush** [comment]
i try cfbg last day that work some times(not property) but today after a restart doset work or only balance some one for exam 1 aliyance 8 hord, My random bg set to 8 member to start in battleground_template

**Comment by ahuraa** [comment]
any news?

**Comment by bigkoroush** [comment]
also pets not working (walock,mage,hunter...) don't enter the combat

**Comment by ahuraa** [comment]
i have crash can't test it

**Comment by ahuraa** [comment]
i test it and not working 

no balance 

can't atack aliance - aliance {balanced}  or horde

pets not working in bgs

**Comment by ahuraa** [comment]
any news?

**Comment by HeartWell** [comment]
No

**Comment by ahuraa** [comment]
please help to fix it obitus

**Comment by ahuraa** [comment]
any body help me please

**Comment by ahuraa** [comment]
please help me to fix this fucking cfbg

**Comment by ShinDarth** [comment]
@ahuraa it looks like at the moment no one is working on the crossfaction. I have a small fix which should help with the loot system in case of crossfaction, and I will commit it soon.

What I suggest to you is start working on minore features so we can improve the core meanwhile and you can get more help and improve your skills. There are many more things that in my opinion are more urgent compared to the crossfaction that need to be done, you may pick some of them.

**Comment by rre-za** [comment]
which crossfaction BG patch u are using?
and please provide core hash + debug logs ( not release with debug info ) compile in debug mode

**Comment by ahuraa** [comment]
i fixed it and use this

**Comment by rre-za** [comment]
well done!
would u mind sharing the patch with community?

**Comment by HeartWell** [comment]
Ahaha he fixed it and closed the request and then help people.Share CFBG.

**Comment by bigkoroush** [comment]
well done , i need this

**Comment by ahuraa** [comment]
https://bitbucket.org/pak3935/sunwellcore/commits/c23b9751df230411334eb7ed27f59becb0f98eaa

check it

**Comment by lineagedr** [comment]
@ahuraa Does it work, since there's one comment that says it doesn't.

**Comment by ShinDarth** [comment]
@ahuraa can you please [open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) ?

so we have everything needed in the main repository, without the need of going to take things here and there...

**Comment by bigkoroush** [comment]
Doest it Work ! Alliance cant attack to aliance and hord cant attack to hord ! and crash after bg end
Plz fix

**Comment by ShinDarth** [comment]
@bigkoroush please provide your crash dumps so we can try to help you

**Comment by falzard** [comment]
I can try the code from here https://bitbucket.org/pak3935/sunwellcore/commits/c23b9751df230411334eb7ed27f59becb0f98eaa  on azerothcore (just applying the patch, I'm not C++ knowledgeable). Then I tell you if it works great and someone can turn this into a module for AzerothCore?

I don't know how to help more.

**Comment by lineagedr** [comment]
The bitbucket version is obviously not even completed yet.

**Comment by falzard** [comment]
Segmentation fault

**Comment by falzard** [comment]
Pak3935 seems to be working on this again and I suppose we need to test it but he's still based on sunwellcore.
https://bitbucket.org/pak3935/sunwellcore3/commits/branch/test

**Comment by Raz240** [comment]
Is there anything working at the moment?
