### ISSUE TITLE
Quest Incense for the Festival Scorchlings

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#16604]
### Current Behaviour

"The quest Incense for the Festival Scorchlings cannot be turned in. I picked up the quest in Orgrimmar and went to Razor Hill, Durotar to turn the quest in. The scorchling was not there."

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/58153179/e9b68e28-66a3-4e68-b596-4240fb10e9d0)

### Expected Blizzlike Behaviour

"The scorchlings should spawn in settlements in order to complete the quest."

### Steps to reproduce the problem

Go to Orgrimmar and accept the quest "Incense for the Festival Scorchlings"
Go to Razor Hill, where the scorchling should be there.
The scorchling was not there.

### Extra Notes

Edit: There is a scorchling to turn in the quest in Trisfall Glades

### AC rev. hash/commit

7ae4b85c43d7cc5909e3778f5f76833c960250e7

### Operating system

Windows 11

**Comment by Stump876** [comment]
Duplicate https://github.com/azerothcore/azerothcore-wotlk/issues/11789
