### ISSUE TITLE
[Raid]Ulduar Teleporter

### ISSUE THREAD

**Issue by xtrodinary12** [azerothcore/azerothcore-wotlk#1660]
Ulduar teleporter . After you kill first 4 boss  U can't go to other  . Ulduar teleporter is not usable .

**Comment by poszer** [comment]
Please while reporting issue fill template ( TITLE, DESCRIPTION, EXPECTED BLIZZLIKE BEHAVIOUR, CURRENT BEHAVIOUR, STEPS TO REPRODUCE THE PROBLEM, AC HASH/COMMIT )...

-- IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE! -
