### ISSUE TITLE
[QUEST] Head of Nefarian not spawned in Stormwind after quest turn-in

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1661]
##### SMALL DESCRIPTION:

Head of Nefarian not displayed in Stormwind after quest turn-in to Field Marshal Afrasiabi. He does correctly yell the event text and also gives the big buff.

https://wowgaming.altervista.org/aowow/?quest=7781
https://wowgaming.altervista.org/aowow/?quest=7782

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The head should show hanging near where the quest was turned in to Field Marshal Afrasiabi.
See below video:
https://www.youtube.com/watch?v=fbXETY0C44U

##### STEPS TO REPRODUCE THE PROBLEM:

1. additem 19003 to an alliance character lvl60+.
2. accept quest and follow it through.
3. event plays out, players get buff, but no dragon head hanging.

##### EXTRA NOTES:

Maybe it can be fixed like the horde counterpart: https://github.com/azerothcore/azerothcore-wotlk/issues/541

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

0f174ef

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by Pondaveia** [comment]
I can confirm that this isn't scripted in either factions. I will try to pick this up tonight.

**Comment by gtao725** [comment]
> I can confirm that this isn't scripted in either factions. I will try to pick this up tonight.

I can confirm it works for the Horde side. You turn the head in to Thrall, and then he directs you to the Overlord near entrance of Orgrimmar. Once turned in there, the Overload guy will mount the head on a pike, yell something, and give everybody a buff. The horde counterpart of this quest was fixed a long time ago in https://github.com/azerothcore/azerothcore-wotlk/issues/541.

**Comment by Pondaveia** [comment]
@gtao725 You're right, I remember this issue from December but didn't realize it was fixed in January.
