### ISSUE TITLE
Opening doors with cheat programs

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#16632]
### Current Behaviour

https://github.com/azerothcore/azerothcore-wotlk/assets/52524476/93de60e2-7cbd-4955-b357-dcdb7ad1450a

Opening doors dugeon, raid, arena, battlegruond

### Expected Blizzlike Behaviour

None

### Source

None

### Steps to reproduce the problem

![Untitled11](https://github.com/azerothcore/azerothcore-wotlk/assets/52524476/546547e8-498b-4b33-95d8-39f367fa7719)

unlock

### Extra Notes

None

### AC rev. hash/commit

rev. 79d6f4e23343

### Operating system

window server 2019 64bit

**Comment by Kitzunu** [comment]
Well without access to the program the report is useless

**Comment by poryagholami** [comment]
> Well without access to the program the report is useless

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-programs/501471-gagarin-advanced-multi-hack-wow-3-3-5a.html&ved=2ahUKEwiRpp-a3ub_AhUhBzQIHcfBBY0QFnoECBAQAQ&usg=AOvVaw2yW-0_YQ5LQbiwHVw_gSVo

**Comment by Ovahlord** [comment]
just disable the object report use   opcode handling when the gameobject has the not_selectable flag
