### ISSUE TITLE
[Entangling Roots] doesn't break if no melee target

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#16637]
### Current Behaviour

title

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/61223313/c98b8cba-b685-46c1-80c7-ade38c827cf8)

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/61223313/0bdd297f-cba1-4bcb-aab0-f94927c3e14a)

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/61223313/d0e87597-9512-4c07-ab7a-7ad1e49a5859)

### Expected Blizzlike Behaviour

break at certain (low) damage threshold

### Steps to reproduce the problem

get a druid
get roots on the target
spam cast the target
- if there's no other player in melee range of your target, root will not break

### AC rev. hash/commit

fb7164b

### Operating system

Ubuntu 20.04

**Comment by Si1ker** [comment]
You may want to take a look at this @Nyeriah @Gultask .
Specially used in heroics.

**Comment by Tereneckla** [comment]
It does break no matter if someone is in melee or not
The damage needed to break seems to be dependent on the hp of the target, which leads to this (you also always could spam it)

**Comment by Si1ker** [comment]
check the title again, I know what I'm reporting.

**Comment by Tereneckla** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/50233983/bb41a7cc-0221-482d-bf97-9b2047dbc41a)

And I know the actual behavior

**Comment by Kitzunu** [comment]
I can confirm it with low damage. Try using a level 1 Wrath and it will not interrupt the root. 718b0000b

**Comment by Nyeriah** [comment]
The chance to break is proportional to the damage it does, so yes, that's intended

**Comment by Kitzunu** [comment]
Ah okay, then we can close
