### ISSUE TITLE
[Wotlk Nexus] Unkillable Grand Magus Telestra

### ISSUE THREAD

**Issue by GastonCK** [azerothcore/azerothcore-wotlk#16638]
### Current Behaviour

The first boss of The Nexus https://www.wowhead.com/wotlk/npc=26928/grand-magus-telestra splits into 3 copies and when you kill those copies the boss does not return to the fight. This also makes the last boss inaccessible because the first boss is a requisite.
Issue Example : https://youtu.be/6Uuf0NuJ674

### Expected Blizzlike Behaviour

Once the copies are eliminated the boss must return to the fight.

### Source

Wotlk Classic https://youtu.be/_kF4vK1cON0?t=158

### Steps to reproduce the problem

.tele nexus
.engage combat with Grand Magus Telestra
.damage 10000
.kill the copies and nothing happens after
.type .combat and she'll appear.

### Extra Notes

Happens on both Normal and Heroic versions

### AC rev. hash/commit

9941f78396798031f791e08fedc730e72443e07d

### Operating system

Windows 11

### Custom changes or Modules

No

**Comment by GastonCK** [comment]
Now it works, closing.

**Comment by elthehablo** [comment]
> Now it works, closing.

What fixed it? Or was it never broken?

**Comment by GastonCK** [comment]
I have no clue, I updated the core and went to try her again and the fight worked properly.

**Comment by heyitsbench** [comment]
> I have no clue, I updated the core and went to try her again and the fight worked properly.

Might be an inconsistent issue. 🤷‍♀️
