### ISSUE TITLE
On kill reputation gains reduced while grouped.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16646]
### Current Behaviour

Currently it seems that reputation gains from creature kills while in a group are split for each player in the party. [Screenshot attached.](https://github.com/chromiecraft/chromiecraft/assets/38561765/c8139ccd-5c05-4892-9e66-6c1a34abfc62)

### Expected Blizzlike Behaviour

The reputation gains from creature kills should not be split across players.

### Source

[Wrath Classic](https://github.com/chromiecraft/chromiecraft/assets/38561765/43ade927-8706-4bf8-8df3-1625d1001637), no mention on any reputation guides elsewhere on the Internet

### Steps to reproduce the problem

1. `.go zonexy 33.4 75 33` on two characters.
2. Kill a Bloodsail enemy on one character.
3. Invite the other character to a party.
4. Kill a Bloodsail enemy again.
5. Observe the reputation split.

### Extra Notes

Tests performed on both AC/Classic with level 70 night elf warrior template characters on [Bloodsail Raiders](https://wowgaming.altervista.org/aowow/?npc=1561).

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/5848.

### AC rev. hash/commit

791add7f352b0e8ac0aa08d187b93ed72fedb134

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by elthehablo** [comment]
Whoa. Always wondered why this was made like this. Pretty big deal tbh

**Comment by elthehablo** [comment]
Maybe something that used to be in retail wotlk but got changed as a QOL feature with the classic versions?

**Comment by Tereneckla** [comment]
Not a classic change
https://youtu.be/RjlygZkYcS8

(Dead) char gains the full 20 rep per kill here

**Comment by elthehablo** [comment]
Leaves me to wonder why the rep split got implemented on AC. Probably already implemented on whatever came before

**Comment by Tereneckla** [comment]
Making a fix for it
it's the same place and code as the xp split
