### ISSUE TITLE
Festive decorations are missing from the "Bloody Monastery-Cathedral" in midsummer

### ISSUE THREAD

**Issue by fangshun2004** [azerothcore/azerothcore-wotlk#16658]
### Current Behaviour

There are no lotus flowers and candles in the pools in the Bloody Monastery ornaments
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/6b036669-32a0-4757-8be6-af646125b9cf)

### Expected Blizzlike Behaviour

There should be candles and lotus flowers in the pool of the cathedral
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/c1da5f50-caec-497c-99dc-adbbb09b5926)

### Steps to reproduce the problem

1. .go xyz 930.119080 1399.185425 18.341074 189

### AC rev. hash/commit

c843af3b77ce

### Operating system

.go xyz 930.119080 1399.185425 18.341074 189

**Comment by heyitsbench** [comment]
Can confirm, there are supposed to be Midsummer decorations throughout Scarlet Monastery during Midsummer. Source: Wrath Classic.

I do have a sniff of this particular instance with the decorations, but as per usual, parsing unavailable.
