### ISSUE TITLE
Cannot talk to Frost Giants in Dun Niffelem to turn in quests

### ISSUE THREAD

**Issue by AldebaraanMKII** [azerothcore/azerothcore-wotlk#16665]
### Current Behaviour

Whenever i try to talk to the Giants in Dun Niffelem i get the icon to attack them instead, even though they are seem as friendly in the UI and don`t attack the player. This happens with any frost giant no matter if they`re inside Dun Niffelem or not.

### Expected Blizzlike Behaviour

That you`re able to talk to them to complete the quest

### Steps to reproduce the problem

1. Get any quests from the frost giants in Dun Niffelem
2. Try to talk to them to complete the quest

### AC rev. hash/commit

c843af3

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
Disable “At War” in your reputation UI

**Comment by AldebaraanMKII** [comment]
> Disable “At War” in your reputation UI

Yes that worked. Thanks.
