### ISSUE TITLE
[Druid] Feral Spells are not gated at trainers

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1666]
SMALL DESCRIPTION:

Feral spells (Bear and Cat form) can be learned without obtaining the required forms. You should be able to only learn those spells if you have the associated form.

Can be seen here: https://youtu.be/DYTHaE2XyJ4?t=343 (you can see he is lvl 10 but no Demo Roar present, while on the server right now you can learn that spell at lvl 10 even tho you don't have Bear Form.)

In this video: https://youtu.be/XPCmIWXUQmY?t=303 you can see when he goes to learn Demo Roar, under the spell name it says: Requires: Level 10, Bear Form(Shapeshift). It's in white letters cause he just obtained Bear Form but if he didn't have it, the letters would be red and he would not be able to learn that spell.

Bear Spells:
-Demoralizing Roar spell=99
-Enrage - spell=5229
-Bash - spell=5211
-Swipe(Bear)  spell=779
-Challenging Roar  spell=5209
-Frenzied Regeneration =22842
-Savage Defense - spell=62600
-Lacerate - spell=33745

Cat Spells:
-Claw  spell=1082
-Prowl  spell=5215
-Rip  spell=1079
-Shred  spell=5221
-Rake  spell=1822
-Pounce  spell=9005
-Feline Grace spell=20719
-Tiger's Fury spell=5217
-Dash - spell=1850
-Cower spell=8998
-Ferocious Bite spell=22568
-Ravage spell=6785
-Track Humanoids spell=5225
-Maim spell=22570
-Swipe(Cat)  spell=62078
-Savage Roar spell=52610

EXTRA NOTES:

BRANCH(ES):
master

AC HASH/COMMIT:
AzerothCore rev. 0f174eff0142+ 2019-03-30 15:44:35 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Win10

MODULES:
transmog

**Comment by poszer** [comment]
Hm, anyway you can't use these abilities until you get required spec, right?

**Comment by Pondaveia** [comment]
@poszer It's not like what he said is wrong, even if players can't use them It's still a bug. I remember this on retail too. Gotta add a condition to this... not sure if this is db or core.

**Comment by poszer** [comment]
> t like what he said is wrong

Yes, you re right. I Already checked some old videos, that's why is tag '' Need Feedback '' there. Anyway thanks for confirm @Pondaveia

**Comment by BarbzYHOOL** [comment]
very minor bug though

**Comment by JamesGent** [comment]
Can confirm this is still a thing.

![Desktop 28-11-2020 16-55-55-29](https://user-images.githubusercontent.com/61194190/100521287-98032680-319a-11eb-9ede-45b4d5e53986.png)

**Comment by Kitzunu** [comment]
I suppose this is easily fixed with conditions
