### ISSUE TITLE
[QUEST] A Life Without Regret

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1667]
DESCRIPTION:

The mission "[A Life Without Regret](https://wowgaming.altervista.org/aowow/?quest=13266)" doesn't work properly

EXPECTED BLIZZLIKE BEHAVIOUR:

when you accept the mission, the undercity portal appears

CURRENT BEHAVIOUR:

the undercity portal doesn't appear

STEPS TO REPRODUCE THE PROBLEM:

- create a horde pg;
- .quest add 13266
- .go 1921.3 -4140.4 41.8 1

BRANCH(ES):
Master

AC HASH/COMMIT:
commit https://github.com/azerothcore/azerothcore-wotlk/commit/eae9affec99181cec14fa4fd0449bb9f8e02565f

OPERATING SYSTEM:
linux

**Comment by Stoabrogga** [comment]
You have to start the quest chain with "Herald of War" (13257) or otherwise the phasing will not work. Don't jump into the middle of the quest chain as GM.
