### ISSUE TITLE
Creature level scaling spells do not seem to scale damage properly.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16676]
### Current Behaviour

Spells with the [SPELL_ATTR0_SCALES_WITH_CREATURE_LEVEL](https://www.wowhead.com/wotlk/spells?filter=58;1;0) attribute do not seem to scale the damage value correctly based on caster level.

For this example, I will refer to the [Bristleback Shaman](https://wowgaming.altervista.org/aowow/?npc=2953) (level four in this particular example) and their [Lightning Bolt](https://wowgaming.altervista.org/aowow/?spell=9532) ability. Against a level one Tauren warrior (with `.cheat god` on), [this is what the combat log looks like](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/e36dcbe7-9df9-47f3-9050-b9fd3a642c63).

### Expected Blizzlike Behaviour

Unsure at this point.

As a part of the prior example, on Classic in the same conditions, [this is what the combat log looks like](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/04340de5-60d5-4e7b-94d8-2fc8fb42790e).

### Source

Wrath Classic

### Steps to reproduce the problem

1. Create a Tauren warrior.
2. `.go c id 2953`
3. Let it cast [Lightning Bolt](https://wowgaming.altervista.org/aowow/?spell=9532) at you.
4. Observe its damage.

### Extra Notes

There is currently a [VMaNGOS PR](https://github.com/vmangos/core/pull/2007) open targeting this same issue. Could possibly cherry-pick if we can verify on Wrath Classic that the formula is the same.

Unsurprisingly, this issue may have been reported on the CC issue tracker for various individual casters/spells. Those will have to be triaged later since there's probably a whole bundle bunch of em. As well, individual casters/spells could have been reported on the AC repo. Those will have to be identified as well.

### AC rev. hash/commit

893a9beeacc4554f9ac85755b40520a9b8e6d411

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Gultask** [comment]
https://github.com/chromiecraft/chromiecraft/issues/5818
https://github.com/chromiecraft/chromiecraft/issues/5820
