### ISSUE TITLE
Engineer's Explosive Extravaganza (Midsummer Fireworks Spectacular) event is unimplemented.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16677]
### Current Behaviour

Currently there is some [debris](https://github-production-user-asset-6210df.s3.amazonaws.com/38561765/248529029-727b26d3-7e81-4789-8644-700d4bbcce4d.png) in front of the Exodar's entrance as a part of the Midsummer event.

### Expected Blizzlike Behaviour

Timing is weird of course, but around the 4th of July (May have been a different date or nonexistent for non-US realms) a bunch of NPCs/gameobjects should spawn around various capitals. Many reveler NPCs, fireworks vendors, tables, kegs, goblets, and mugs. The NPCs should say various things depending on which area they're attending (and depending on the status of the fireworks show), and the goblets (I believe) should only be spawned for a bit, also dependent on the fireworks show. Every hour from the start of the event (Intuition says no fireworks at the start, every hour following including the last the event should take place) there should be a fireworks show at every capital city as well as Booty Bay in a specific spot. (Gates of Org, Exodar, SW, Ironforge, Silvermoon, UC; close to the flight post in TB, just off the coast of Rut'theran Village, above one of the small paths in Shattrath's upper city, and in the middle of the bay in Booty Bay) This show should go on for about ten minutes with the revelers in the area turning towards it at certain points, and (iirc) cheering at the end.

### Source

Wrath Classic, Wowhead run-downs

### Steps to reproduce the problem

1. Exist on the 4th of July.
2. Observe AzerothCore does not celebrate the United States of America's day of independence.

### Extra Notes

~~The Exodar debris section of this report was brought to you in part by: https://github.com/chromiecraft/chromiecraft/issues/5832.~~ fixed

I have a lot of this particular event sniffed, though very possibly not all. I was sniffing at the top of every hour at every location mentioned in the report as well as Ratchet and Dalaran, neither of which I saw any sort of fireworks display or commotion at, so I believe these two do not have anything of interest related to this event.

### AC rev. hash/commit

dc071dab4cc8edaafbbefd5f765b02d4dcb7613b

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by sudlud** [comment]
Holidays.dbc, ID 62
- duration 18 (hours)
---
HolidayNames.dbc, ID 12
```
Fireworks Spectacular
```

---

HolidayDescriptions.dbc, ID 11
```
After the sun sets, the end of Midsummer is celebrated, with an hourly firework extravaganza.

To watch the show, visit any capital city or Booty Bay.
```

just for future reference 👀

**Comment by heyitsbench** [comment]
For the record (since loosely related), the fireworks event for New Year's (as well as any other firework event, e.g. Peon Day in Europe, Chinese New Year) is a separate event, HolidayDescriptions/HolidayNames ID 2 (Fireworks Celebration rather than Fireworks Spectacular), missing the fireworks vendors, but that seems to be about the only difference.
