### ISSUE TITLE
(SAI): Gnarlpine Mystic cast the wrong Wrath spell.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#16678]
### Current Behaviour

Currently, [Gnarlpine Mystics](https://wowgaming.altervista.org/aowow/?npc=7235) are casting the wrong [Wrath](https://wowgaming.altervista.org/aowow/?spell=5177) spell, specifically the rank two Druid's Wrath spell.

### Expected Blizzlike Behaviour

The mystics should be casting the correct [Wrath](https://wowgaming.altervista.org/aowow/?spell=9739) spell.

### Source

(Wrath Classic) Wowhead, 2.5.2 sniff

### Steps to reproduce the problem

1. `.go c id 7235`
2. Observe their cast.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/5682.

The original SAI for this creature was added in [this commit](https://github.com/azerothcore/azerothcore-wotlk/commit/948bd0a24898e2fe2d17faeb7ce852343b0397ac).

### AC rev. hash/commit

bda9b404038e886f54d30a33bfce54a06c1f5004

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by elthehablo** [comment]
(I will make the PR tomorrow)

**Comment by heyitsbench** [comment]
> Hey man. This is a good first issue! Keep it up

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/717c7c71-1e61-4a16-87c1-aa3f75a89b83)

🙂

**Comment by elthehablo** [comment]
> > Hey man. This is a good first issue! Keep it up
> 
> ![image](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/717c7c71-1e61-4a16-87c1-aa3f75a89b83)
> 
> 🙂

The original linked issue was genuinely a really good and detailed issue report (I scrolled through it quite quickly but it looked good)
