### ISSUE TITLE
Quest: Wild Hearts (429) - bad quest markers on NPCs

### ISSUE THREAD

**Issue by wowquester** [azerothcore/azerothcore-wotlk#16699]
### Current Behaviour

When you hover your mouse over NPCs that should give you the Discolored Worg Heart as an quest item, the quest marker is missing. Should apply for: 

### Expected Blizzlike Behaviour

There should be...
![WoWScrnShot_070723_231355](https://github.com/azerothcore/azerothcore-wotlk/assets/138876396/9d9149be-0ebf-4330-beaf-aebc597a4ecc)

### Source

https://www.wowhead.com/wotlk/item=3164/discolored-worg-heart
https://www.youtube.com/watch?v=KjHzz6R_OCo

### Steps to reproduce the problem

.q add 429
.go xyz 943.951294 1447.872681 42.608425
Hover over Mottled Worg, Bloodsnout Worg, Worg or Gorefang. - nothing happens

### Extra Notes

Now, SQL mages help me, please... i thought that this would fix the problem, however it doesn´t work for every NPC listed... can you comment or PM me why? I'd love to learn to solve this. 

DELETE FROM `creature_questitem` WHERE `CreatureEntry` IN (1765, 1766, 1923, 12431);
INSERT INTO `creature_questitem` (`CreatureEntry`, `Idx`, `ItemId`, `VerifiedBuild`) VALUES
(1765, 0, 3164, 0),
(1766, 0, 3164, 0),
(1923, 0, 3164, 0),
(12431, 0, 3164, 0);

### AC rev. hash/commit

bda9b404038e

### Operating system

Win11 x64

### Custom changes or Modules

None

**Comment by heyitsbench** [comment]
> ### Source
> https://www.youtube.com/watch?v=KjHzz6R_OCo

The quest markers in this video I am almost certain are provided by an add-on (my assumption would be Questie, but the interface looks different) as opposed to in the base game.

**Comment by wowquester** [comment]
> > ### Source
> > https://www.youtube.com/watch?v=KjHzz6R_OCo
> 
> The quest markers in this video I am almost certain are provided by an add-on (my assumption would be Questie, but the interface looks different) as opposed to in the base game.

Ah yes, you're right... sorry about the false issue. Will do better research the next time.
