### ISSUE TITLE
Compile Failing - All Eluna Errors!

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1672]
##### SMALL DESCRIPTION:

Compiling using VS2017 Community Edition just failed on latest commit.
See below errors:
![image](https://user-images.githubusercontent.com/35093669/55486568-1d99a080-565f-11e9-9203-b4bb1f52847d.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should compile as before.

##### CURRENT BEHAVIOUR:

Compile failing with Eluna.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just compile it and see in Windows 7/10/Svr 2016 using VS2017 Community Edition.

##### EXTRA NOTES:

N/A
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

d56a41f

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by Winfidonarleyan** [comment]
Please test PR https://github.com/azerothcore/azerothcore-wotlk/pull/1668

**Comment by gtao725** [comment]
> Please test PR #1668

@Winfidonarleyan Works flawlessly, thank you!

**Comment by gtao725** [comment]
PR has being merged to master.
