### ISSUE TITLE
ICC 10 Normal - Sindragosa disapeared after RO

### ISSUE THREAD

**Issue by Revan2107** [azerothcore/azerothcore-wotlk#16728]
### Current Behaviour

Regarding to player. He with his guild had raid time some time before. He couldn't kill Sindragosa so desided to leave it until next raid time. Next time they came to Singragosa's boss room there wasn't any creatures there including Sindragosa. So apprently they lost a possibility kill the boss and pass ICC.

YouTube video from player side: https://www.youtube.com/watch?v=Abb76WrWYUg

### Expected Blizzlike Behaviour

Sindragosa stays on it's place until boss fight starts.

### Source

https://www.wowhead.com/wotlk/npc=36853/sindragosa

`This NPC can be found in [Icecrown Citadel].`

### Steps to reproduce the problem

1. With raid group try to kill Sindragosa;
1.1. Probably wipe;
2. Disband raid group;
2.1. Probably wait until daily processes will pass or trigger it by yourself;
3. Create raid group again with same players;
4. Come where Sindragosa supposed to be.

### Extra Notes

Fraction: Horde

### AC rev. hash/commit

AzerothCore rev. 9d7e47216078+ 2023-07-02 09:15:52 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80033
Using CMake version: 3.22.1
Compiled on: Linux 5.15.0-75-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azerothcore/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azerothcore/data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-duel-reset
- mod-globalchat
- mod-transmog

### Operating system

Ubuntu 22.04.2 LTS

### Custom changes or Modules

> List enable modules:
- mod-duel-reset
- mod-globalchat
- mod-transmog

**Comment by Nefertumm** [comment]
Closing. Dup #16751
