### ISSUE TITLE
Blade of Wizardry is missing an ICD

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#16747]
### Current Behaviour

No ICD

### Expected Blizzlike Behaviour

Has an ICD of possibly 50s

### Source

https://www.wowhead.com/wotlk/spell=38319/forgotten-knowledge
https://wago.io/Sk9LwGd76

### Steps to reproduce the problem

.add 31336
Cast spells

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=31336
https://wowgaming.altervista.org/aowow/?spell=38319

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5aa44033ab3d0b42561fd47bb22bcd59098a6ecd

### Operating system

Windows 10

**Comment by elthehablo** [comment]
:,(
