### ISSUE TITLE
Extract custom mmaps and vmaps

### ISSUE THREAD

**Issue by DykeRz** [azerothcore/azerothcore-wotlk#16740]
### Current Behaviour

Hello all, i using Trickerer source Azerothcore with npc bots and i try to extract mmaps for my custom map,i put all adt/wdl/wdt, m2,wmo that i have in my custom map to patch-3.mpq and replace my custom areatable.dbc and map.dbc to patch-enUS-3.mpq and trying to extract all, vmaps extracting for my custom map,but mmaps don't,any idea?
And for ICC, all dungeon is good, but at Lich King place no vmaps, server console says "vmap file 631 does not exist" but in folder its existing.

it seems that some files are being overwritten incorrectly

### Expected Blizzlike Behaviour

Custom geo must be extracted

### Steps to reproduce the problem

pull AC source
compile extractors
extract custom lands

### AC rev. hash/commit

37382dc

### Operating system

debian 11

**Comment by ilkashpilkerman** [comment]
Hello. Have you found a solution? I have the same problem.

**Comment by Kitzunu** [comment]
No, because then it wouldve been closed.

**Comment by ilkashpilkerman** [comment]
> No, because then it wouldve been closed.

Actually, I came here from TrinityCore, but I think everything works same here. The guys suggested that to read custom maps, maps, mmaps, you need to create a patch after original (patch-3) "patch-4(5).MPQ". I didn't read it before because I called it as patch-6, which is incorrect. But if that doesn't work, then make a backup of patch-3.MPQ and patch-enUS-3.MPQ and insert your cards there. My extractors found everything.

**Comment by Kitzunu** [comment]
So this can be closed?

**Comment by ilkashpilkerman** [comment]
Yes🥰

**Comment by syphex97** [comment]
For clarification here. adding ontop of Ilkashpilkerman's comment.
**You need two Patch files for the extractors to work.** 
**patch-4.MPQ** (Here you put all files like your custom map, textures etc, apart from DBFilesClient)
**patch-enUS-4.MPQ** (This is where you put your DBC files (The folder DBFilesClient)

patch-4.MPQ goes into Data folder
patch-enUS-4.MPQ goes into Data\enUS folder

**Explanation:**
Maps (base files) extract all patch files in Data folder (DBC files (DBFilesClient) and all other files)
However Vmaps and mmaps only load DBC files from the patch file in enUS. This means if the DBFilesClient folder is in the patch-4.mpq it won't load the DBC Files, and therefore won't find the entry for your custom map, which it gets from the map.dbc file.

Hope this clarifies it.
