### ISSUE TITLE
Deathbringer Saurfang doesn`t drop anything

### ISSUE THREAD

**Issue by AldebaraanMKII** [azerothcore/azerothcore-wotlk#16757]
### Current Behaviour

I killed him 3 times already on normal 10 player difficulty. No drops.

### Expected Blizzlike Behaviour

That he drops his loot.

### Steps to reproduce the problem

1. Kill Deathbringer Saurfang on normal 10 player difficulty.

### AC rev. hash/commit

c843af3b

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
He is not meant to drop anything. A chest spawns with his loot
