### ISSUE TITLE
[Icecrown Citadel Raid] No Sindragosa respawn

### ISSUE THREAD

**Issue by al99vin** [azerothcore/azerothcore-wotlk#16751]
### Current Behaviour

According to the player's report: after a failed attempt at a boss fight, they exited the game. There was supposed to be another attempt a few days later, but the boss was nowhere to be found - neither in the air nor on the ground. As proof, I am attaching a video from the [player's screen](https://youtu.be/qa66S5MHIrA)

### Expected Blizzlike Behaviour

I expect that when going back to raiding with the existing **InstanceID**, all unkilled bosses will be in place, including Sindragosa.

### Source

https://www.wowhead.com/wotlk/npc=36853/sindragosa

### Steps to reproduce the problem

1. Create a raid;
2. Beat all bosses to Sindragosa (Rebrad, Lady, Ships, Saurfang, Valitria);
3. Wipe on Syndragosa;
4. Disband the raid;
5. Wait a few days or run the daily processes manually;
6. Create a raid with the same people and see if Sindragosa exists;

### Extra Notes

Fraction: Alliance

### AC rev. hash/commit

AzerothCore rev. 9d7e472+ 2023-07-02 09:15:52 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80033
Using CMake version: 3.22.1
Compiled on: Linux 5.15.0-75-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azerothcore/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azerothcore/data/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

List enable modules:

mod-duel-reset
mod-globalchat
mod-transmog

### Operating system

Ubuntu 22.04.2 LTS

### Custom changes or Modules

List enable modules:

mod-duel-reset
mod-globalchat
mod-transmog

**Comment by Tony931023** [comment]
This is happening exactly since the commit https://github.com/azerothcore/azerothcore-wotlk/commit/f59ee4ef7cc455fc300ed0741ac635c8e1f03fe3 was made, as well as **Algalon the Observer** after dying the event does not appear again and you must wait for the next restart of id, after Sindragosa I fixed it @Nyeriah  more information in this issue #15557 , after this it was thought that it worked correctly but the fact is that if you reach Sindragosa and summon it and your raid dies, and Disband your raid to reassemble another day, and your server was restarted or crashed at some point, since Sindragosa does not appear again, you must enter with a gm account and execute _.resp all_ there and they must clean the room again and kill the two dragons with _.die_ since they stay bugg in the air, that's how Sindragosa reappears.

We would have to wait for these events to be fixed or CC to reach this patch so that it can be fixed.

or see if @Nyeriah and @UltraNix (sorry for the ping) could review and correct it

**Comment by noisiver** [comment]
> 

Sadly, this sounds like an issue that shouldn't be set to wait until CC reaches that point. It could be a long time before CC gets there. It's good of you to know more about it and give it the attention it requires.

**Comment by noisiver** [comment]
That code is a mess because you failed to properly use a codeblock.

**Comment by Nefertumm** [comment]
It might be because Sindragosa is treated as a TempSummon after failing it, so the method "DespawnOnEvade" will trigger this message:
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19627365/f0c162e9-67f8-443b-9ed0-bff014b1ca00)

I suspect that this is breaking it somewhere, but I couldn't look at it deeply.

**Comment by Nyeriah** [comment]
> It might be because Sindragosa is treated as a TempSummon after failing it, so the method "DespawnOnEvade" will trigger this message: ![image](https://user-images.githubusercontent.com/19627365/255156439-f0c162e9-67f8-443b-9ed0-bff014b1ca00.png)
> 
> I suspect that this is breaking it somewhere, but I couldn't look at it deeply.

This effectively does nothing, redundant warning

**Comment by Nyeriah** [comment]
There’s only an issue after the server restarts so there’s some issue with the instance save data

**Comment by Nefertumm** [comment]
I know it does nothing, but in effect there is something broken about the instance save data and despawning the bosses (as I far I understood, it happens in Algalon too)

**Comment by Nyeriah** [comment]
> I know it does nothing, but in effect there is something broken about the instance save data and despawning the bosses (as far as I understood, it happens in Algalon too)

Different issue, Algalon needs the respawn event scripted at all as it wasn’t. Sindragosa has a respawn script in place

**Comment by GastonCK** [comment]
Confirming, this just happened on our server
Original report https://github.com/andeswow/bugtracker/issues/5

**Comment by EricksOliveira** [comment]
bug confirmed. any hackfix?

**Comment by noisiver** [comment]
A hackfix is a band-aid and not a solution for this. It's best if someone who knows how to fix it would be kind enough to put the time in.

**Comment by Ligthsx** [comment]
Well I fixed it this way, it works perfectly in my case, and sorry if it is poorly structured, I'm just learning.
**src\server\scripts\Northrend\IcecrownCitadel**

`bool OnTrigger(Player* player, AreaTrigger const* /*areaTrigger*/) override
    {
        if (InstanceScript* instance = player->GetInstanceScript())
        {
            if (!instance->GetData(DATA_SPINESTALKER))
                if (Creature* spinestalker = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_SPINESTALKER)))
                    spinestalker->AI()->DoAction(ACTION_START_FROSTWYRM);
            if (!instance->GetData(DATA_RIMEFANG))
                if (Creature* rimefang = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_RIMEFANG)))
                    rimefang->AI()->DoAction(ACTION_START_FROSTWYRM);
        /***if (!instance->GetData(DATA_SINDRAGOSA_FROSTWYRMS) && !instance->GetGuidData(DATA_SINDRAGOSA) && instance->GetBossState(DATA_SINDRAGOSA) != DONE) ***/
            if (!instance->GetData(DATA_SINDRAGOSA_FROSTWYRMS) && instance->GetGuidData(DATA_SINDRAGOSA) && instance->GetBossState(DATA_SINDRAGOSA) != IN_PROGRESS)
            {
                if (instance->GetData(DATA_HAS_LIMITED_ATTEMPTS) && !instance->GetData(DATA_HEROIC_ATTEMPTS))
                    return true;
                player->GetMap()->LoadGrid(SindragosaSpawnPos.GetPositionX(), SindragosaSpawnPos.GetPositionY());
        /***    if (Creature* sindragosa = player->GetMap()->SummonCreature(NPC_SINDRAGOSA, SindragosaSpawnPos)) ***/
                if (Creature* sindragosa = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_SINDRAGOSA)))
                    sindragosa->AI()->DoAction(ACTION_START_FROSTWYRM);
            }
        }

        return true;
    }`
