### ISSUE TITLE
I wanna say Thanks You to all Devs and People who contribute with azeroth core to make the best playable server <3

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16762]
### Current Behaviour

Im enjoying a lot :) i can sense the hard working and amazing scripting of server

### Expected Blizzlike Behaviour

the best XD

### Steps to reproduce the problem

...

### AC rev. hash/commit

...

### Operating system

...

**Comment by noisiver** [comment]
This is not something that should be an issue report. It's better suited for Discord.

**Comment by 55Honey** [comment]
Thanks a lot for the kind words.
Like noisiver said, feel free to join our discord for a chat.

**Comment by therelus** [comment]
:D i know that not was the right zone but i wanna say that, i joined discord! :)

**Comment by therelus** [comment]
> Thanks a lot for the kind words. Like noisiver said, feel free to join our discord for a chat.

Hey 55Honey, i need ask you something for the LUA you created, ZoneDebuff Lua, i not understand it well and i only wanna sustituye it for solocraft module, because in solocraft module you can find a bug which you can stack a lot of stats and become too powerfull, i really excited a lot when i saw your LUA , im trying put my chars more powerfull but no work by the moment, to put the Debuff in all dungeon than exists, i need write all dungeons in config? or not need? thx i hope this can be the right zone to ask you that xd if not, tell me please where i can ask you
