### ISSUE TITLE
Hunter pets don't move smooth when following

### ISSUE THREAD

**Issue by wzw1990** [azerothcore/azerothcore-wotlk#16763]
### Current Behaviour

Hunter pets don't move smoothly when following the player after learning the Boar's Speed talent
[Prove Video](https://youtu.be/ijqUeb_r_Js)

### Expected Blizzlike Behaviour

It should be smooth. I don't have an account to verify right now, so if anyone is willing to help I'd greatly appreciate it!

### Steps to reproduce the problem

1. Create a blood elf hunter
2. .level 79
3. Selected a Springpaw Cub then using .pet create
4. Pets learn Boar's Speed talent

### AC rev. hash/commit

AzerothCore rev. 3a3dc6446bad 2023-07-12 08:04:39 -0300 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.81.0
Using MySQL version: 80021
Using CMake version: 3.26.3
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/workspace/azerothcore-wotlk/build/bin/Debug/maps. Total size: 291014951 bytes
vmaps directory located in E:/workspace/azerothcore-wotlk/build/bin/Debug/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/workspace/azerothcore-wotlk/build/bin/Debug/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows 11 x64

### Custom changes or Modules

None

**Comment by wzw1990** [comment]
I think it might be [TargetedMovementGenerator.cpp#L306](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L306C27-L306C27) that's causing the issue. when the pet follows the player, the base speed should be based on the player's speed.
If I'm right, I'd be happy to submit a PR after more testing!

**Comment by noisiver** [comment]
I can confirm this. They move as if their movement speed is slightly above yours and interrupt their movement animation halfway through every time to let you catch up. It's merely a way of explaining what it looks like for me, not what is actually happening (since I don't know the specifics).
