### ISSUE TITLE
AzerothCore consume a lot of CPU in Linux, can it be solved?May be some bad compilation?

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16760]
### Current Behaviour

Idk where post this "bug", we don´t know how solve it, we tought could be some incompatible thing with Linux, or maybe bad compilation, we used "Master" to compilate and we get hard consume of CPU, with 20 people it goes to 104%, with a VPS of 4 Cores and 24G RAM, we tested in Windows and the consume of CPU is really much lower , for that reason we think that is could be some Linux incompatibility. Thanks :)

### Expected Blizzlike Behaviour

...

### Steps to reproduce the problem

...

### AC rev. hash/commit

AzerothCore Rev 2023-06-09

### Operating system

Ubuntu 20.04

**Comment by v-mstrs** [comment]
Same here just idling its sitting at around 50~%

**Comment by noisiver** [comment]
Perhaps you're reading it wrong. The processes listed, i.e in htop, shows the percentage based on 100% = 1 full core. Mine is sitting at 30% but that's 30% out of 400% (with access limited to 4 cores). While the worldserver process itself sitting at roughly 30%, this is the total core usage
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/5157047/bc1a082f-cf19-460f-9203-cc039b87f0b2)

**Comment by noisiver** [comment]
For the record, with a lot happening on 1 core, you can increase `MapUpdate.Threads` from 1 to make use of more cores.

**Comment by wzw1990** [comment]
Windows and Linux have different algorithms for calculating CPU utilization. for example:
Hardware: 2 Core 4 Threads 
MapUpdate.Threads = 1
Windows: Cpu Utilization is about ~25%
Linux: Cpu Utilization is about ~100%
MapUpdate.Threads = 2
Windows: Cpu Utilization is about ~50%
Linux: Cpu Utilization is about ~200%

**Comment by ninjawow** [comment]
@noisiver At the time I thought the same thing, but then I stopped to see the process and it is very fluctuating, at times it consumes all the cores, but the amazing thing is that this happens with 4 colleagues online, I compiled a previous revision and it doesn't exist This consumes excessively, the cpu always remains at 10 with 4 colleagues online, this is a bug in the latest reviews of Azerothcore. I've been reviewing for several weeks on a machine with Linux Ubuntu 20.04 with 8 cores and 24 GB of ram, regardless of cores consumption is always high, something is happening and I record it in my 4-core vps that I use for testing.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/5303854/dd7b0fd6-91cc-4057-9692-672b40cafdbb)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/5303854/b9ec985b-1ab9-4d63-a6ad-339ce95db6db)

**Comment by noisiver** [comment]
> 

It is not like that for me. My server is up for 7 days at a time, sure only up to 25 of my characters are online at a time but I enable preloading maps and setting all creatures as active so load is as high as it's ever going to get. With 4 map threads it's sitting at about 50-75% cpu usage on each core and 6GB RAM usage (I changed the core to only load maps that are accessible to me in the current place in progression). If I disable preload/active it sits at <10% on each core. I'm running Ubuntu 22.04 on all my current servers.

**Comment by moncat2005** [comment]
The issue of high CPU usage in Worldserver allowed by LINUX compilation has been discovered for a long time.
After carefully checking and modifying world.conf and testing its effectiveness, I have found a method that can reduce CPU usage.

Modify the following configuration parameters in the worldserver.conf file.

//MinWorldUpdateTime
//Description: Minimum time (milliseconds) between world update ticks (for mostly idle servers).
//Default:     1 - (0.001 second)
MinWorldUpdateTime = 1 change to 10

//MapUpdateInterval
//Description: Time (milliseconds) for map update interval.
//Default:     10 - (0.01 second)
MapUpdateInterval = 10 change to 100

After adjusting the configuration parameters, the problem has been improved.
![249795572-c0e6d41f-e03a-4147-8f27-9cf41c763883](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/36e84913-4952-4ca5-83ac-5ca314eea9bd)

In addition, during the compilation and runtime of Worldserver programs on Linux systems before 2021， 
I confirmed that the CPU usage rate is usually between 15% and 20%.

**Comment by pangolp** [comment]
I wonder if poor memory management can cause CPU consumption to skyrocket... however, it's a touchy subject. Memory management is a problem that all projects have at some point. And you have to be careful in that aspect, but I don't know if it really has to do with this issue, or the problem could be another.

**Comment by ninjawow** [comment]
Thank you very much brother, that was it, now the cpu consumption is going great.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/5303854/c0a9e72e-323c-4e83-bb9c-cc1e835ae12f)

**Comment by moncat2005** [comment]
@ninjawow
What adjustments have you made to lower CPU usage?

**Comment by ninjawow** [comment]
the ones you said...

**Comment by moncat2005** [comment]
I found that modifying this configuration item can reduce CPU usage, but it is not clear which program functions will affect the execution performance.

**MinWorldUpdateTime** is approximately the minimum time slot unit during game execution. For an online game, it seems that the current default recommended 1ms is too harsh, so I switched to 10ms.

**MapUpdateInterval** should be based on the update interval of map change data. I remember before 2021, this parameter seemed to have been 100ms, but for some reason, the recommended default value has now been changed to 10ms.

These two configuration parameters have a significant impact on the resource usage during program operation, so adjustments have also shown an effect.

Anyway, if the same source code version and configuration result in a significantly lower CPU usage of the compiled worldserver program under WINDOWS compared to LINUX, I think we still haven't found the source of this problem.

**Comment by ninjawow** [comment]
For me it is working, the cpu consumption is going very well and the stability of the server is great, it has been online for 6 days without crashes, I don't know if these two parameters really affect something in particular, but the cpu consumption is going very well and with that I am glad.
