### ISSUE TITLE
`Roland Geardabbler` is missing his bubble

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#16773]
### Current Behaviour

[Roland Geardabbler](https://www.wowhead.com/wotlk/npc=8394/roland-geardabbler) is missing his bubble effect. I do not know what is the spell so we need a sniff.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/22718174/d1fd40ec-228d-426d-8efe-bb925b2380e0)

### Expected Blizzlike Behaviour

Wowhead screenshot bubble!

![image](https://wow.zamimg.com/uploads/screenshots/small/87716.jpg)

### Steps to reproduce the problem

`.go creature 160362`

### AC rev. hash/commit

AzerothCore rev. 54c0ff2912f4+ 2023-07-08 23:10:25 -0400 (merge-some-player-checks branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.82.0
Using MySQL version: 80027
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19044
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by heyitsbench** [comment]
50375 packet (truncated for anonymity):
```
ServerToClient: SMSG_AURA_UPDATE (0x2C1F) Length: 54
UpdateAll: True
AurasCount: 1
Slot: 0
HasAura: True
CastID: [Roland]
SpellID: 12508 (12508)
SpellXSpellVisualID: 244129
Flags: 259 (NoCaster, Positive, MawPower)
ActiveFlags: 1
CastLevel: 43
Applications: 0
ContentTuningID: 0
HasCastUnit: False
HasDuration: False
HasRemaining: False
HasTimeMod: False
PointsCount: 0
EstimatedPoints: 0
HasContentTuning: False
UnitGUID: [Roland]
```

**Comment by heyitsbench** [comment]
For the record, on Classic all four of the crew are not swimming, just standing, blades in hand and all. On AC, they do swim.

**Comment by heyitsbench** [comment]
Roland also has incorrect health/mana values.

|Source|Health|Mana|
|-|-|-|
|AC|1648|1432|
|Classic|1441|3575|
