### ISSUE TITLE
Solocraft Module stack infinite times stats of some classes and get crazy damage

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#16772]
### Current Behaviour

Characters can stack infinite stats and become too powerfull doing absurd damage

### Expected Blizzlike Behaviour

...

### Steps to reproduce the problem

1. I think you must enter and go out many times of a dungeon

### AC rev. hash/commit

...

### Operating system

Ubuntu 20.04

**Comment by heyitsbench** [comment]
Make a report on the solocraft module repo, not here.

**Comment by therelus** [comment]
Oh sorry, i don´t knew where report it, thx you :)
