### ISSUE TITLE
[TBC Karazhan] Arcane Protectors have not-working/wrong behaviour

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#16786]
Originally reported on CC at: https://github.com/chromiecraft/chromiecraft/issues/4887
By: [NinesCC](https://github.com/NinesCC)

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

- They aren't patrolling how they should
- Currently stunnable by warrior abilities
- Fist of Stone is not doing anything
https://youtu.be/px3WCMXzK_Q?t=6083

### Expected Blizzlike Behaviour

- They should be able to be pulled alone, but their patrol paths is not correct, so they stand with other packs
- They should be immune to stuns.
- Fist of stone should increase damage and attack speed.

### Source

_They are single pulls, but hit quite hard. They are immune to snares and stuns. When they activate Fist of Stone they hit quite hard but move slowly. Let the tank kite them for the duration._
https://wowpedia.fandom.com/wiki/Arcane_Protector

### Steps to reproduce the problem

1. Enter Karazhan by the backdoor
2. Go upstairs
3. Kill Curator
4. They are the robots after you kill curator.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by v-mstrs** [comment]
Fist of Stone works fine
