### ISSUE TITLE
[TBC Karazhan] Players are sacrificed in the wrong area in the Terestian Illhoof fight

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#16787]
Originally reported on CC at: https://github.com/chromiecraft/chromiecraft/issues/4889
By: [NinesCC](https://github.com/NinesCC)

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Sacrifice is casted on top of the boss:
https://youtu.be/px3WCMXzK_Q?t=6836

### Expected Blizzlike Behaviour

Sacrifice should teleport the afflicted person to the center of the room, inside the green ritual symbols.

### Source

2007 Footage
https://youtu.be/6TqCLSxDRqY?t=34

### Steps to reproduce the problem

1. Head into Karazhan backdoor
2. Go upstairs past Curator
3. Enter the secret door on the left, past the first imps you fight.
4. Go down the tunnel and fight Illhoof
5. Wait for him to cast Sacrifice

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by ChrisCGalbraith** [comment]
`Effect 1` of [Sacrifice](https://www.wowhead.com/wotlk/spell=30115/sacrifice) is `Teleport` which derives its coordinates from `TARGET_DEST_DB`. I'll try and investigate where the coordinates are actually found, I suspect DBCs?

**Comment by heyitsbench** [comment]
Just to point out, here is a sniff of this spell being cast from 3.4.2 50375:
```
ServerToClient: SMSG_SPELL_GO (0x2C36)
(Cast) CasterGUID: Full: [IllhoofGUID] Map: 532 Entry: 15688 Low:
(Cast) CasterUnit: Full: [IllhoofGUID] Map: 532 Entry: 15688 Low:
(Cast) CastID: Full: [ID] Map: 532 Low:
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: 30115 (30115)
(Cast) SpellXSpellVisualID: 314959
(Cast) CastFlags: 67109128
(Cast) CastFlagsEx: 2097152
(Cast) CastTime: 2236866802
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) DestLocSpellCastIndex: 4
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) HitTargetsCount: 1
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) HasAmmoDisplayId: False
(Cast) HasAmmoInventoryType: False
(Cast) (Target) Flags: 66 (Unit, DestinationLocation)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: True
(Cast) (Target) HasOrientation: True
(Cast) (Target) hasMapID : True
(Cast) (Target) Unit: Full: [TargetGUID] Map: 0 Low:
(Cast) (Target) Item: Full: 0x0
(DstLocation) Transport: Full: 0x0
(DstLocation) Location: X: -11234.2 Y: -1698.41 Z: 179.237
(Cast) (Target) Orientation: 0.558504998683929443
(Cast) (Target) MapID: 532
(Cast) (Target) Name: 
(Cast) [0] HitTarget: Full: [TargetGUID] Map: 0 Low:
```

**Comment by avarishd** [comment]
rev 7d6a578 no longer the case, probably was fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/17311
