### ISSUE TITLE
ByteBuffer byte order

### ISSUE THREAD

**Issue by rdcentermrzhi** [azerothcore/azerothcore-wotlk#1679]
##### SMALL DESCRIPTION:

in Big-Endian  mac no convert byte order 

 template<class T> void append(const T *src, size_t cnt)
        {
            return append((const uint8 *)src, cnt * sizeof(T));
        }

when read in  Big-Endian mac  can happend error 

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

**Comment by FrancescoBorzi** [comment]
Can you put your AC commit hash?
