### ISSUE TITLE
Clean Build Startup Errors

### ISSUE THREAD

**Issue by AXISIT** [azerothcore/azerothcore-wotlk#16802]
### Current Behaviour

Expected no errors on clean install of system, but instead have the following in my DBErrors.log 

Table 'reference_loot_template' Entry 43001 does not exist but it is used by Reference 43001
Table 'reference_loot_template' Entry 526791 isn't reference id and not referenced from loot, and thus useless.
Table 'reference_loot_template' Entry 526792 isn't reference id and not referenced from loot, and thus useless.
Script named 'npc_anzu_spirit' is not assigned in the database.
Script named 'npc_pet_darting_hatchling' is not assigned in the database.
Table 'reference_loot_template' Entry 43001 does not exist but it is used by Reference 43001
Table 'reference_loot_template' Entry 526791 isn't reference id and not referenced from loot, and thus useless.
Table 'reference_loot_template' Entry 526792 isn't reference id and not referenced from loot, and thus useless.
Script named 'npc_anzu_spirit' is not assigned in the database.
Script named 'npc_pet_darting_hatchling' is not assigned in the database.
Table 'reference_loot_template' Entry 43001 does not exist but it is used by Reference 43001
Table 'reference_loot_template' Entry 526791 isn't reference id and not referenced from loot, and thus useless.
Table 'reference_loot_template' Entry 526792 isn't reference id and not referenced from loot, and thus useless.
Script named 'npc_anzu_spirit' is not assigned in the database.
Script named 'npc_pet_darting_hatchling' is not assigned in the database.
Table 'reference_loot_template' Entry 43001 does not exist but it is used by Reference 43001
Table 'reference_loot_template' Entry 526791 isn't reference id and not referenced from loot, and thus useless.
Table 'reference_loot_template' Entry 526792 isn't reference id and not referenced from loot, and thus useless.
Script named 'npc_anzu_spirit' is not assigned in the database.
Script named 'npc_pet_darting_hatchling' is not assigned in the database.

### Expected Blizzlike Behaviour

Clean Startup No Errors

### Steps to reproduce the problem

launch Authserver with no errors
launch Worldserver with multiple errors

### AC rev. hash/commit

 AzerothCore rev. 30197f40d687 2023-07-19 05:57:13 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 15 minute(s) 23 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100519
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.10.0-23-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/wow/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/wow/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/wow/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_07_19_04.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Debian 11

**Comment by Kitzunu** [comment]
A clean build cant have any startup errors. If it did the CIs wouldnt pass, so you did something wrong.

Try again from scratch 👍

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/5595549218/job/15156314380
