### ISSUE TITLE
Unable to get to character select screen after login

### ISSUE THREAD

**Issue by wangsiw1** [azerothcore/azerothcore-wotlk#16814]
### Current Behaviour

After start the server, log in with username and password, game will say connected successfully and wait for a second, then, instead of get to character selection screen as usual, the realm select window pops up, with my only realm showing, with correct number of character in that realm and low server load. Choosing the realm will loop previous behavior.

### Expected Blizzlike Behaviour

After log in, go to character select screen directly.

### Steps to reproduce the problem

1. Start authserver, wait for startup finishes
2. Start worldserver, wait for startup finishes
3. Start game client
4. Log in with username and password

### Extra Notes

I git pulled latest commit on 2023-07-22, patched NPCBots, rebuild the core, then I was able to start the server and the game just fine as before. I played on both 07-22 and 07-23, with 07-23 I raided Gruul’s Lair, Magtheridon’s Lair, Serpentshrine Cavern, and Zul'Aman with bots. Nothing happened during the play, and I shutdown the worldserver with command "server shutdown 2" and then authserver as usual, then I am not able to join the server on 07-24.

### AC rev. hash/commit

AzerothCore rev. 9482836e3392+ 2023-07-21 19:16:11 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 1 minute(s) 4 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 100612
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.90.1-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /mnt/d/WoW/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /mnt/d/WoW/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /mnt/d/WoW/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_26_00_characters_npcbot_transmog.sql
Latest WorldDatabase update: 2023_07_19_04.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

WSL Ubuntu 22.04.2 LTS

### Custom changes or Modules

Applied NPCBots from https://github.com/trickerer/Trinity-Bots

**Comment by Samsequel** [comment]
We do not support npcbots ourself, please report your issue at the place where you got your fork.

**Comment by Kitzunu** [comment]
You have done something wrong in the setup.

Works without issues
