### ISSUE TITLE
Pets in Magical Menagerie (Dalaran) are shifted up, out of their cages and displays

### ISSUE THREAD

**Issue by ChibaPet** [azerothcore/azerothcore-wotlk#16839]
### Current Behaviour

Pets in Magical Menagerie (Dalaran) are shifted up, out of their cages and displays. Examples of some of them:

https://0x0.st/H2Xf.png

### Expected Blizzlike Behaviour

Pets are in their cages and displays, not above them.

### Steps to reproduce the problem

1. Enter Magical Menagerie
2. Observe.

### AC rev. hash/commit

AzerothCore rev. 5c132654cd2f 2023-07-27 23:44:47 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 2.
Server uptime: 29 minute(s) 32 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100519
Found MySQL Executable: /bin/mysql
Compiled on: Linux 5.10.0-23-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/acore/data/maps. Total size: 291014951 bytes
vmaps directory located in /opt/acore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/acore/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_07_27_05.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-transmog

### Operating system

Debian 11 amd64

### Custom changes or Modules

mod-transmog

**Comment by heyitsbench** [comment]
Seems these guys respawn possibly at 2am every day, that'd make grabbing their spawn points easy.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/3e75bd70-d3be-4c00-bcec-4be7dfb11f94)

**Comment by heyitsbench** [comment]
Can definitely confirm *most* of these guys respawn at 2am every day, got a good sniff of those. The ones that don't respawn don't seem to move though, thus those have also been sniffed.

**Comment by sudlud** [comment]
well, looks like the sniffed spawns are identical and the issue persists.

Also I wanted to update the Stable Hunter Pets with CO2 spawns, but then they stopped moving (?)
is wander_distance and MovementType reliable / relevant from sql parses (?) or should the current DB values be kept and just xyz, orientation, VerifiedBuild be updated from the sniff

**Comment by sudlud** [comment]
31730 Cosmetic Frog seems to be the only one correctly sitting in its box

**Comment by sudlud** [comment]
now it gets interesting, looks like the spawn coordinate itself is correct but the creature actually is spawned with an offset (?)

so we e.g. have this spawn here:
`(117622, 31714, 571, 1, 1, 0, 5851.6484375, 561.7413330078125, 653.24591064453125, 4.084070205688476562, 120, 0, 0, 0, 0, 0, "", 48632, 1, NULL),`

now we teleport to the xyz coordinate
.gm fly on
.go xyz 5851.6484375, 561.7413330078125, 653.24591064453125 571

standing at the correct position inside the glas box:
![WoWScrnShot_011024_221520_go_xyz](https://github.com/azerothcore/azerothcore-wotlk/assets/7723845/4b758209-0fd7-409d-8379-d6c54ad19f17)

now we teleport to the creature GUID of this spawn:
.go c 117622

and we're standing on top of the box in the same spot where the creature actually has been spawned:
![WoWScrnShot_011024_221600_go_c](https://github.com/azerothcore/azerothcore-wotlk/assets/7723845/57ae8380-f028-431f-9f2b-87cdc81b0139)

what's going on here? why is the creature not spawned at it's spawn location but somewhere else (?)
is there some kind of flag to prevent this maybe?

**Comment by sudlud** [comment]
Feels like creatures are being spawned with an additional z offset to prevent them getting stuck in the ground 👀

**Comment by heyitsbench** [comment]
Maybe the boxes aren't considered walkable spaces and are being shifted to the first Z coordinate that is?

**Comment by sudlud** [comment]
> Maybe the boxes aren't considered walkable spaces and the creatures are being shifted to the first Z coordinate that is?

Maybe, but some of them are actually spawned inside the cages, like those in the stack of cages. The bottom cage animal is sitting in the top cage

**Comment by sudlud** [comment]
Creature::LoadCreatureFromDB()

https://github.com/azerothcore/azerothcore-wotlk/blob/7ec2585cc80b08db87441ac374cefec14a42c56e/src/server/game/Entities/Creature/Creature.cpp#L1669-L1677

**Comment by sudlud** [comment]
> Creature::LoadCreatureFromDB()
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/7ec2585cc80b08db87441ac374cefec14a42c56e/src/server/game/Entities/Creature/Creature.cpp#L1669-L1677
> 

when I comment out these lines, all animals are correctly sitting in their cages.

![WoWScrnShot_011124_103701](https://github.com/azerothcore/azerothcore-wotlk/assets/7723845/bf8a7dfc-b4f3-4328-946b-fce9391a5077)
