### ISSUE TITLE
Core getting a malformed packet when trying to log in

### ISSUE THREAD

**Issue by Onixiya** [azerothcore/azerothcore-wotlk#1684]
Core getting a malformed packet when trying to log in

##### SMALL DESCRIPTION:

Getting a bad packet when i try to log in

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Logging in without a issue

##### CURRENT BEHAVIOUR:

WorldSocket::handle_input_header(): client (account: 0, char [GUID: 0, name: <none>]) sent malformed packet (size: 8, cmd: 1867972641)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Compile with all default options(Don't know how to disable debug mode)
2. Setup the databases and .conf files to connect to mysql server and also disable warden
3. Start the server and create a account with the username being 'nut' and password 'nut'(eating peanuts when writing this if your wondering about the name)
4. Try to log in on Wow client.
5. Fail
##### EXTRA NOTES:

I have mysql 5.7 x64 and openssl 1.1.1b x64. Compiling using visual studio 2015
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9eb6e9a7776025553dc9ce14a240713f5ccce94a

##### OPERATING SYSTEM:

Windows 10 x64

##### MODULES:

Nope

##### OTHER CUSTOMIZATIONS:

Every thing is default with the exception of warden being disabled and the mysql settings being changed

**Comment by Falstring** [comment]
I'm not certain about this, but I think it's your ssl version.

1.1.x is not compitable with mangos nor trinitycore. Isn't this the case with AC core aswell? I've only been using 1.0.x (non-light), so not sure.

But I think you need ssl 1.0.x

**Comment by Onixiya** [comment]
I'll try a earlier version

**Comment by Onixiya** [comment]
Getting the exact same problem, got the client by installing off the disc(physical cd) then applying updates.

**Comment by Falstring** [comment]
try re-installing using the ready-to-play clients from Warmane or alike.

**Comment by Nefertumm** [comment]
1.1.x is compatible with AC

**Comment by Onixiya** [comment]
It was a client problem. I have no clue whatsoever on how it was caused since i doubt debug versions of wow were released. That was a huge waste of time compiling the core over and over again with different openssl versions. At least i found the problem.

**Comment by Falstring** [comment]
Ah great. :D 

and 1.1.x is compitable. learned smth new too.

**Comment by Warglaive** [comment]
> 

It has been some time..But could you share how you fixed it? Thanks!
