### ISSUE TITLE
Minigob Manabonk (32838) broken

### ISSUE THREAD

**Issue by ChibaPet** [azerothcore/azerothcore-wotlk#16841]
### Current Behaviour

Previously, Minigob Manabonk (32838) would appear at random and sheep players. As of at least a couple months ago (not sure when this changed) he appears to spawn under the street level or somesuch, and the player being targeted hears what is evidently an interrupted cast bar from broken line of sight, as they are never sheeped. However, a targeted player will receive Minigob's mail with attached Mischief Maker soon thereafter, as if they had been successfully sheeped.

### Expected Blizzlike Behaviour

Minigob Manabonk (32838) sheeps players when he appears.

### Steps to reproduce the problem

1. Stand around in Dalaran.
2. Wait to hear Minigob Manabonk (32838) attempting unsuccesfully to sheep you.
3. Check your mail to see his letter and gift item.

### AC rev. hash/commit

AzerothCore rev. 5c132654cd2f 2023-07-27 23:44:47 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 2.
Server uptime: 29 minute(s) 32 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100519
Found MySQL Executable: /bin/mysql
Compiled on: Linux 5.10.0-23-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/acore/data/maps. Total size: 291014951 bytes
vmaps directory located in /opt/acore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/acore/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_07_27_05.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-transmog

### Operating system

Debian 11 amd64

### Custom changes or Modules

mod-transmog

**Comment by sudlud** [comment]
I can confirm this on latest AC.

I've had the mail appearing in my mailbox multiple times without ever actually being sheeped, always after a short visit to dalaran.

**Comment by pangolp** [comment]
Now that I think about it, that happened to me too, that I received the email without having seen the event, but I thought it had happened at some point when I was absent or distracted, but apparently it's general. Finally, someone took care of him... haha.
