### ISSUE TITLE
[QUEST]Magtheridon's Head Not on Display and No Buff (Horde & Alliance)

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1685]
##### SMALL DESCRIPTION:

When turning in the following quests:

[Alliance] The Fall of Magtheridon (https://wowgaming.altervista.org/aowow/?quest=11002)
[Horde] The Fall of Magtheridon (https://wowgaming.altervista.org/aowow/?quest=11003)

There are 2 things that doesn not happen by the end of the hand in:

1. Neither Alliance side nor Horde side gets the zone buff. (Trollbane's Command[https://wowgaming.altervista.org/aowow/?spell=39911] for Alliance or Nazgrel's Fervor[https://wowgaming.altervista.org/aowow/?spell=39913] for Horde)

2. Magtheridon's Head is not displayed on a spike at the entrance of either Thrallmar (Horde) or Honor Hold (Alliance)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://wow.gamepedia.com/Signs_of_victories    (See section on Magtheridon)
https://wow.gamepedia.com/Magtheridon%27s_Head

##### CURRENT BEHAVIOUR:

1. Quest can be completed by both Alliance or Horde players but neither side gets buff and the head on a spike is not displayed for either faction.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .additem 32385 (for alliance) or .additem 32386 (for horde)
2. .go creature id 16819 (for alliance) or .go creature id 3230 (for horde)
3. hand in the quest and choose your reward. Trollbane(alliance) or Nazgrel(horde) will say something about your feat of strength.
4. After that you will see you get no buff and outside near the entrance Magtheridon's Head on a spike is NOT SEEN anywhere... not for horde and not for alliance.

##### EXTRA NOTES:

Very similar mechanics to Nefarians Head on a spike in Orgrimmar and Stormwind.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9eb6e9a

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by poszer** [comment]
Will take a look on this

**Comment by Pondaveia** [comment]
@poszer Is really dedicated to show off heads everywhere xD

**Comment by JamesGent** [comment]
Can confirm no head after quest completion nor buff.

![Desktop 28-11-2020 16-48-39-879](https://user-images.githubusercontent.com/61194190/100521127-a735a480-3199-11eb-9d44-f0ad7fc19465.png)

**Comment by sogladev** [comment]
There are other multiple zone buffs that work incorrectly like this one

- Magtheridon's buff: Hellfire Peninsula and Hellfire dungeons
- Ada'ls Song of Battle: Shattrath and Tempest Keep dungeons, 
- Kiru Song of Victory: Isle of Quel'danas and Sunwell dungeons 

### CMangos for reference
Joining/leaving Zone adds/removes player GUID to a list 
```
void WorldState::HandlePlayerEnterZone(Player* player, uint32 zoneId)
```
https://github.com/cmangos/mangos-wotlk/blob/bd63be95ae8e084c748eb5129366a7533edc02c4/src/game/World/WorldState.cpp#L442

Added in: https://github.com/cmangos/mangos-wotlk/commit/0b87ca9d9edf2d4752a3c0f8e9cf85c6689ca861

Matheridon quest complete sets worldstate which loops through the vector and applies the spell https://github.com/cmangos/mangos-wotlk/blob/master/src/game/AI/ScriptDevAI/scripts/outland/hellfire_peninsula.cpp#L1586

### ACore
no global zone remove/add exists? A playerscript can be used like the midsummer event 

- https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Events/midsummer.cpp#L160 

Should a single playerscript be used with a vectorGUID that stores/removes players like cmangos? Or is there a need for more global OnLeaveZone or OnEnterZone functions
