### ISSUE TITLE
Quest: 1361 - Incorrect POI

### ISSUE THREAD

**Issue by wowquester** [azerothcore/azerothcore-wotlk#16857]
### Current Behaviour

Comp. POI is duplicated in Durotar, should't be. Its a bug, Barrens one is ok, but the POI is duplicated at the exact same place in Durotar - there is no NPC, nothing. 
![WoWScrnShot_072923_224913](https://github.com/azerothcore/azerothcore-wotlk/assets/138876396/65c3faaa-7162-46e8-841b-27b38acfa5c2)
![WoWScrnShot_072923_224919](https://github.com/azerothcore/azerothcore-wotlk/assets/138876396/bacffe8d-1aab-411a-9084-45270395b29c)

### Expected Blizzlike Behaviour

Deduplicate the POI in durotar. 

### Source

Regthar Deathgate (the cmpl. npc) is only in Barens, not Durotar. 

### Steps to reproduce the problem

.q add 1361 
.go tax 23
- check the map

### AC rev. hash/commit

bda9b404038e

### Operating system

win11

**Comment by avarishd** [comment]
rev. 05161a9
Could not reproduce

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/8a53be5d-3257-47c3-b876-e22cb4a47224)
