### ISSUE TITLE
[Feature Request] Config for Party EXP Penalty (Reduction)

### ISSUE THREAD

**Issue by cdenq** [azerothcore/azerothcore-wotlk#16860]
Would love for a way to edit (completely remove) party exp penalty! This seems to be hard-coded somewhere, but would be much more convenient to have it editable in SQL.

When I say party exp penalty, I am talking about the fact that if a mob gives 100 exp normally, in a party of 2, both teammates get 50 exp each. The removal of the penalty would mean that both teammates get 100 exp normally.

**Comment by Tereneckla** [comment]
I assume you mean the party xp split as there actually is an increase in total experience dependent on the party size

This line does the ratio of experience a player in a raid/party gets
https://github.com/azerothcore/azerothcore-wotlk/blob/177fc23f088f8223e81c07545fa7ec7078e37d7f/src/server/game/Entities/Player/KillRewarder.cpp#L210

**Comment by cdenq** [comment]
Thank you!
