### ISSUE TITLE
Glyph of Arcane Shot doesn't function & returns an error

### ISSUE THREAD

**Issue by Linear-Petra** [azerothcore/azerothcore-wotlk#16873]
### Current Behaviour

When casting Arcane Shot with the Glyph of Arcane Shot active, no mana is refunded and an error message appears saying that the player needs to be near a Lexicon of Power

### Expected Blizzlike Behaviour

When Arcane Shot is triggered with a sting active and the Glyph installed, it should refund 20% of the mana cost of Arcane Shot

### Steps to reproduce the problem

1. Log onto a hunter with Glyph of Arcane Shot as an active major glyph
2. Cast a sting (Serpent Sting and Scorpid Sting were both tested) on the target
3. Cast Arcane Shot on the same target
4. When the shot hits the target, check for returned mana and for the error message at the top-center of the screen that "Requires you to be near a Lexicon of Power"

### Extra Notes

TimeisTime and Reagent Bank are present, but not enabled

A fix was attempted with changing src/server/scripts/Spells/spell_hunter.cpp line 70 to point to spell 56841 instead of spell 61389; while this removed the error message, it still did not refund the mana.

### AC rev. hash/commit

.server debug
AzerothCore rev. 30ec58cca92b 2023-07-30 18:33:36 -0500 (AzCoreBotsUpdated branch) (Win64, Debug, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 3 minute(s) 18 second(s)
Update time diff: 2ms, average: 6ms.
Using SSL version: OpenSSL 3.1.1 30 May 2023 (library: OpenSSL 3.1.1 30 May 2023)
Using Boost version: 1.81.0
Using CMake version: 3.26.4
Using MySQL version: 80033
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/BotBuild/bin/Debug/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/BotBuild/bin/Debug/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/BotBuild/bin/Debug/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: zz_optional_aq_quest_nerf.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
>List enable modules:
- mod-TimeIsTime
- mod-individual-progression
- mod-reagent-bank

### Operating system

Windows 10 x64

### Custom changes or Modules

Compiled with commits from Trickerer's NPCbots - https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting this issue. This sounds like a bug in the Individual Progression module. I have opened a new issue on the module to track progress and get it fixed: https://github.com/ZhengPeiRu21/mod-individual-progression/issues/160

As this is not an AzerothCore bug, I will be closing the issue here.
