### ISSUE TITLE
Missing effects from The Stories Dead Men Tell (13643)

### ISSUE THREAD

**Issue by ChibaPet** [azerothcore/azerothcore-wotlk#16885]
### Current Behaviour

One can click on each grave and get question completion, but there's no graphical effect where we see the victims show how they died.

### Expected Blizzlike Behaviour

On clicking on each grave, an image of the victim appears, showing how each was killed.

### Source

https://www.youtube.com/watch?v=2375gMjLHOI

### Steps to reproduce the problem

1. Accept quest.
2. Click on each grave. See question completion text but no graphical component.

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/5c132654cd2fcaed457d426299f2d2b4ef91bf12 2023-07-27 23:44:47 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 2.
Server uptime: 29 minute(s) 32 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 1.1.1n 15 Mar 2022 (library: OpenSSL 1.1.1n 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100519
Found MySQL Executable: /bin/mysql
Compiled on: Linux 5.10.0-23-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/acore/data/maps. Total size: 291014951 bytes
vmaps directory located in /opt/acore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/acore/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_07_27_05.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

    List enable modules:

    mod-transmog

### Operating system

Debian 11 amd64

### Custom changes or Modules

mod-transmog

**Comment by Vanheden** [comment]
https://www.youtube.com/watch?v=GZKXSFzAhhs&ab_channel=Roddan

I managed to fix it here with some help.
