### ISSUE TITLE
[Bloodmyst Isle] Deathclaw not patrolling

### ISSUE THREAD

**Issue by wdraenor** [azerothcore/azerothcore-wotlk#16892]
### Current Behaviour

Deathclaw not patrolling

### Expected Blizzlike Behaviour

Deathclaw should patrol the area

### Source

Deathclaw map from Wowhead: https://www.wowhead.com/wotlk/npc=17661/deathclaw#map
Video of Deathclaw patrolling: https://www.youtube.com/watch?v=eoZPJFnfZpY&t=4511

### Steps to reproduce the problem

.go xyz -1383.488159 -11283.249023 7.790300 530 3.476966
observe

### Extra Notes

[Aowow](https://wowgaming.altervista.org/aowow/?npc=17661)
[Wowhead](https://www.wowhead.com/wotlk/npc=17661/deathclaw)

DB GUID: 63385, current GUID: 235
Current Entry: 17661

### AC rev. hash/commit

AC> AzerothCore rev. e6377c55a9c3 2023-08-04 15:03:52 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 54 minute(s) 32 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 100612
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/user/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/user/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/user/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_08_04_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Linux Mint 21.1

### Custom changes or Modules

None

**Comment by elthehablo** [comment]
according to my checks he seems to have the blizzard equivalent of our wander movement on current wotlk classic PTR
