### ISSUE TITLE
Feature: Support MySQL 8.1

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#16902]
### Describe your feature request or suggestion in detail

MySQL 8.1 has been released and we should support the most recent version when possible.

If the support of MySQL 8.1 requires deprecation of 5.7 that will be done as the official EOL of 5.7 is 31/10/2023. If it is possible without extensive work to keep all 3 versions alive, that will of course be the desired case.

**Comment by Kitzunu** [comment]
Works out of the box, so no changes needed :)

MySQL client library: 8.1.0
MySQL server ver: 8.1.0
Connected to MySQL database at 127.0.0.1
MySQL client library: 8.1.0
MySQL server ver: 8.1.0

AzerothCore rev. e6377c55a9c3 2023-08-04 15:03:52 +0000 (support-MySQL-81 branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 1 minute(s) 53 second(s)
Update time diff: 2ms, average: 1ms.
Using SSL version: OpenSSL 3.0.8 7 Feb 2023 (library: OpenSSL 3.0.8 7 Feb 2023)
Using Boost version: 1.81.0
Using CMake version: 3.25.2
Using MySQL version: 80100
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.1/bin/mysql.exe
Compiled on: Windows 10.0.22000
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_08_04_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

**Comment by heyitsbench** [comment]
> Works out of the box, so no changes needed :)

Yay, not a fourth DB version to explicitly support. 🥳
