### ISSUE TITLE
[QUEST] For the Horde! (No Buff After Quest Turn In)

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1690]
##### SMALL DESCRIPTION:

After turning in quest https://wowgaming.altervista.org/aowow/?quest=4974 at Thrall, he is supposed to do a buff on everyone in Orgrimmar, everyone at the Crossroads, everyone at Camp Taurajo and everyone at Razor Hill called "Warchief's Blessing". However, this does not happen. Also as soon as someone hands in the quest at Thrall, at the same time at the Crossroads, a NPC called Herald of Thrall also spawns which does a similar but slightly different yell to the one that Thrall does:

Thrall yells: Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!
Thrall yells: Be bathed in my power! Drink in my might! Battle for the glory of the Horde!

Herald of Thrall yells: Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!
Herald of Thrall yells: Be bathed in the power of the Warchief! Drink in his might! Battle for the glory of the Horde!

Herald of Thrall Spawn Location: [51.8, 30.4] or see the video included in the next section.

Buff/Yell mechanics: Everyone in Orgrimmar, Crossroads, Camp Taurajo and Razor Hill gets the buff and hears the yell. Everyone in Orgrimmar hears Thrall's yell while everyone in the other places hear the yell of the Herald of Thrall and gets the buff. NOTE: people in Barrens and Durotar other than Orgrimmar, Crossroads, Camp Taurajo and Razor Hill will hear the yell from Herald of Thrall but should NOT get the buff.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://www.youtube.com/playlist?list=PL6L9EYYlrCZwfsoRg2MPmHhBNMKbif3mz
https://wowgaming.altervista.org/aowow/?quest=4974
https://wowgaming.altervista.org/aowow/?spell=16609
https://wowwiki.fandom.com/wiki/Herald_of_Thrall
https://wow.gamepedia.com/Warchief%27s_Blessing
https://wow.gamepedia.com/For_The_Horde!_(quest)
https://wow.gamepedia.com/Signs_of_victories  (Read the section on Rend Blackhand)

##### CURRENT BEHAVIOUR:

Turn the quest in, no buff from Thrall for anyone at Orgrimmar, the Crossroads, Camp Taurajo and Razor Hill. No yell, No Herald of Thrall.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use a level 60 Horde character and .tele Kargath and talk to Warlord Goretooth which starts the chain https://wowgaming.altervista.org/aowow/?quest=4903
2. Follow it through until you turn in https://wowgaming.altervista.org/aowow/?quest=4974 at Thrall in Orgrimmar.
3. Thrall DOES NOT buff anyone in Orgrimmar, the Crossroads, Camp Taurajo, Razor Hill. He doesn't yell, nor does the Herald of Thrall spawn in Crossroads and yell.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9e39666

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by gtao725** [comment]
Will edit this again later today. Seems to be more to it than I thought for how the buff is applied...

**Comment by gtao725** [comment]
Updated with FULL DETAILS, videos will follow soon, uploading to Youtube at the moment. The videos are taken from my test characters using Light's Hope Mangos Build: https://github.com/vmangos/core and this DB: https://github.com/brotalnia/database. Although this is Vanilla 1.12, this quest never changed until Cataclysm.

**Comment by gtao725** [comment]
Check out this YouTube playlist: https://www.youtube.com/playlist?list=PL6L9EYYlrCZwfsoRg2MPmHhBNMKbif3mz for full quest mechanics.

**Comment by Pondaveia** [comment]
Good report :+1: will look into it eventually if no one elae does

**Comment by JamesGent** [comment]
Can confirm after completing the quest no buff or yell is to be had. Ghost/Deleted user said they were looking into it.

![Desktop 27-11-2020 17-28-46-664](https://user-images.githubusercontent.com/61194190/100473340-08943f80-30d6-11eb-9dd2-75617a603882.png)

**Comment by Shineslippers** [comment]
Still exist https://github.com/chromiecraft/chromiecraft/issues/2336
