### ISSUE TITLE
Feature: How to change the announcement content on the login page of the wow client？

### ISSUE THREAD

**Issue by yongguang2023** [azerothcore/azerothcore-wotlk#16924]
### Describe your feature request or suggestion in detail

How to change the announcement content on the login page of the wow client？
 thanks all；

**Comment by Kitzunu** [comment]
Not the place to ask questions.

but this could probably help you https://www.azerothcore.org/wiki/how-to-use-warden-payload-mgr

and probably this module assuming this is what you mean https://github.com/AnchyDev/BreakingNewsOverride/tree/wardenpr
