### ISSUE TITLE
Feature: Players can go through closed doors

### ISSUE THREAD

**Issue by ztyhw** [azerothcore/azerothcore-wotlk#16928]
### Describe your feature request or suggestion in detail

By modifying the MPG file, the player can pass through some closed gates. Can it be fixed?

### Describe a possible solution to your feature or suggestion in detail

Unzip to /data 
[through closed doors.zip](https://github.com/azerothcore/azerothcore-wotlk/files/12270197/through.closed.doors.zip)

### Additional context

Players can kill the last boss directly by this method, and can also simply complete some Heroic difficulty instances.

![a1](https://github.com/azerothcore/azerothcore-wotlk/assets/22415068/08d7c82a-0829-49af-a926-38fcc2a1f4da)
![a2](https://github.com/azerothcore/azerothcore-wotlk/assets/22415068/32a6f822-966c-41ac-83d8-0a0139566b3c)
![a3](https://github.com/azerothcore/azerothcore-wotlk/assets/22415068/da01a5aa-e4b2-41fb-b384-e0affb64a71f)

**Comment by Kitzunu** [comment]
Open as a bug report.

This is a feature request
