### ISSUE TITLE
Code review reports(performance, warnings, security, code style)

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#1693]
##### SMALL DESCRIPTION:

- [ ] Warnings:

https://app.codacy.com/app/FrancescoBorzi/azerothcore-wotlk/issues?bid=11973180&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJDUFAiXX0seyJpZCI6IkNhdGVnb3J5IiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJXYXJuaW5nIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d

- [ ] performance:

https://app.codacy.com/app/FrancescoBorzi/azerothcore-wotlk/issues?bid=11973180&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJDUFAiXX0seyJpZCI6IkNhdGVnb3J5IiwidmFsdWVzIjpbIlBlcmZvcm1hbmNlIl19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==

- [ ] security:

https://app.codacy.com/app/FrancescoBorzi/azerothcore-wotlk/issues?bid=11973180&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJDUFAiXX0seyJpZCI6IkNhdGVnb3J5IiwidmFsdWVzIjpbIlNlY3VyaXR5Il19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==

- [ ] code style:

https://app.codacy.com/app/FrancescoBorzi/azerothcore-wotlk/issues?bid=11973180&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJDUFAiXX0seyJpZCI6IkNhdGVnb3J5IiwidmFsdWVzIjpbIkNvZGVTdHlsZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfV0=
##### EXTRA NOTES:
look at links and Good luck!

**Comment by Viste** [comment]
Good luck!

**Comment by FrancescoBorzi** [comment]
@Viste good job, but why are you using my fork instead of the main repo ?

**Comment by Viste** [comment]
@FrancescoBorzi i get this link from random PR, so its not me )

**Comment by JamesGent** [comment]
Good reports based on Francesco's fork(?) but information is likely outdated at this point and new reports would need to be made. If you feel this is wrong feel free to reopen the issue.
