### ISSUE TITLE
Po tem, ko Illidan ni uspel pri prvem ubijanju, ni mogel napasti in ponovno izbrati!

### ISSUE THREAD

**Issue by songjunst** [azerothcore/azerothcore-wotlk#16952]
### Current Behaviour

Po tem, ko Illidan ni uspel pri prvem ubijanju, ni mogel napasti in ponovno izbrati!

### Expected Blizzlike Behaviour

Po tem, ko Illidan ni uspel pri prvem ubijanju, ni mogel napasti in ponovno izbrati!

### Steps to reproduce the problem

Po tem, ko Illidan ni uspel pri prvem ubijanju, ni mogel napasti in ponovno izbrati!

### AC rev. hash/commit

Po tem, ko Illidan ni uspel pri prvem ubijanju, ni mogel napasti in ponovno izbrati!

### Operating system

win10

**Comment by Maria-sequel** [comment]
Issues have to be in english
