### ISSUE TITLE
[Quest] Doing your duty

### ISSUE THREAD

**Issue by GastonCK** [azerothcore/azerothcore-wotlk#16968]
### Current Behaviour

When doing https://www.wowhead.com/wotlk/es/quest=12227/cumplir-con-tu-deber clicking "Use the outhouse" will instantly give you the seed. Also there's an Imp inside the outhouse.
![WoWScrnShot_080923_112327](https://github.com/andeswow/bugtracker/assets/65800273/d03c6665-f1e6-4f9c-936a-cced2e5c2bdb)
![WoWScrnShot_080923_112037](https://github.com/andeswow/bugtracker/assets/65800273/2ea871ea-f177-41ba-bc30-4dead3af8e9a)

### Expected Blizzlike Behaviour

When clicking "Use the outhouse" you should teleport into the outhouse and start to defecate and scream. You should get the debuff ["Indisposed" ](https://www.wowhead.com/wotlk/spell=53017/indisposed)and when it ends you should receive the [seed](https://www.wowhead.com/wotlk/item=37250/partially-processed-amberseeds)
Wrath Classic https://www.youtube.com/watch?v=_a5TgN7owJ4
Also there shouldn't be an Imp inside the outhouse.

### Source

Wrath Classic https://www.youtube.com/watch?v=_a5TgN7owJ4

### Steps to reproduce the problem

.char level 75
.tel amberpine
.q a 12227
.cick the outhouse (observe there's an Imp inside it)
.click use the outhouse
.receive the seed instantly, no event.

### Extra Notes
enUS client
Original report https://github.com/andeswow/bugtracker/issues/1

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/1cd181f9234d

### Operating system

Debian 11, Windows 11

### Custom changes or Modules

- [mod-aoe-loot](https://github.com/azerothcore/mod-aoe-loot)
- [mod-recruit-friend](https://github.com/pangolp/mod-recruit-friend)
- [mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
- [mod-npc-promotion](https://github.com/pangolp/mod-npc-promotion)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-quest-loot-party](https://github.com/pangolp/mod-quest-loot-party)

**Comment by Vanheden** [comment]
It was fixed 3 days ago.

https://github.com/azerothcore/azerothcore-wotlk/pull/16923

**Comment by pangolp** [comment]
> This was fixed 3 days ago.
> 
> #16923

A thousand apologies, we are using it, as a sample, for our community, so that they report it and then we try to fix / report the bugs here. Thanks for notifying.
