### ISSUE TITLE
Feature: I found that the ID of the user's spell table in the character database does not match the ID of the spell table in the world server?

### ISSUE THREAD

**Issue by yongguang2023** [azerothcore/azerothcore-wotlk#16965]
### Describe your feature request or suggestion in detail

I found that the ID of the user's spell table in the character database does not match the ID of the spell table in the world server?
SELECT * from character_spell WHERE spell = 67;  have data
SELECT * from spell_dbc WHERE id= 67;  have not  data
tks；

**Comment by avarishd** [comment]
The 2 tables have nothing to do with each another.

"[This table (spell_dbc)](https://www.azerothcore.org/wiki/spell_dbc) contains data regarding serverside spells which are not to be found in Client DBC files as well as overrides of the DBC that are meant to improve or fix any spell."

[character_spell  ](https://www.azerothcore.org/wiki/character_spell)

**Comment by yongguang2023** [comment]
@avarishd  tks, i see...
but if I want to fix the price of learning skills for each profession? Which table should I modify?
