### ISSUE TITLE
No NPC's in Razor Hill

### ISSUE THREAD

**Issue by Onixiya** [azerothcore/azerothcore-wotlk#1698]
##### SMALL DESCRIPTION:

Nothing is in Razor Hill

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC's spawned in Razor Hill

##### CURRENT BEHAVIOUR:

No NPC is spawned there. Just buildings and dirt.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Walk, ride or fly Razor Hill
2. Look around
3. Job done

##### EXTRA NOTES:
 None

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

e1d782d0de21e603a43fe30bde330a589baff1df

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

Eluna Lua engine
Transmogrification 

##### OTHER CUSTOMIZATIONS:

Nope

**Comment by poszer** [comment]
Can't reproduce
![razor](https://user-images.githubusercontent.com/41213210/55728529-85ac0600-5a14-11e9-96de-1d462fea3255.jpg)
![razor1](https://user-images.githubusercontent.com/41213210/55728531-85ac0600-5a14-11e9-8496-5687ba0d08e9.jpg)
![razor2](https://user-images.githubusercontent.com/41213210/55728533-86449c80-5a14-11e9-865d-1bb794534adc.jpg)
![razor3](https://user-images.githubusercontent.com/41213210/55728536-86449c80-5a14-11e9-8fed-b2648911781e.jpg)

**Comment by Onixiya** [comment]
Thats wierd then. I got nothing for me in there
