### ISSUE TITLE
Trying to compile Sunwell in Linux Ubuntu 16.04 error

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#17]
hello

Trying to compile Sunwell in Linux Ubuntu 16.04 LTS (64-bit)

When I run "make" I get this at 99 or 100%:

[ 99%] Linking CXX executable worldserver
../game/libgame.a(PathGenerator.cpp.o): In function PathGenerator::CalculatePath(float, float, float, bool)': /home/gabbe/Sunwell/core/src/server/game/Movement/MovementGenerators/PathGenerator.cpp:77: undefined reference toCell::Cell(float, float)'
/home/gabbe/Sunwell/core/src/server/game/Movement/MovementGenerators/PathGenerator.cpp:79: undefined reference to `Cell::Cell(float, float)'
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:292: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1201: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Should be how to solve? T.T

**Comment by Yehonal** [comment]
try to install the ace development libs.. Something like:

sudo apt-get install libace-dev

And please compile with gcc, not clang

Il 20/Lug/2016 03:50, "boom8866" <notifications@github.com> ha scritto:

**Comment by boom8866** [comment]
@Yehonal     Problems still exist

**Comment by mik1893** [comment]
in the file PathGenerator.cpp, add as include:

#include "CellImpl.h"
#include "Cell.h"

in the file Cell.h , remove the include 
#include <cmath>

**Comment by ShinDarth** [comment]
I'm unable to reproduce it, compiles for me on Ubuntu 16.04

**Comment by ShinDarth** [comment]
@boom8866 any news? did you try what mik1893 said?

**Comment by mynew4** [comment]
@mik1893  @ShinDarth https://github.com/azerothcore/azerothcore-wotlk/commit/b88e0fe9a8e87d9c2818b24f69cd10fc93fe63a8 already fixed

**Comment by mynew4** [comment]
@mik1893  @ShinDarth https://github.com/azerothcore/azerothcore-wotlk/commit/b88e0fe9a8e87d9c2818b24f69cd10fc93fe63a8 already fixed
