### ISSUE TITLE
Fix some quest and quests

### ISSUE THREAD

**Issue by Vtkachenko-Informa** [azerothcore/azerothcore-wotlk#17016]
### Current Behaviour

-- https://www.wowhead.com/wotlk/quest=9686/the-second-trial
-- .gobject set phase 23106 1
update gameobject set phaseMask=1 where id=182052;

-- https://www.wowhead.com/wotlk/quest=2359/klavens-tower
-- fix quest level
UPDATE  quest_template SET `QuestLevel` = '20' WHERE (`ID` = '2359');

-- https://www.wowhead.com/wotlk/quest=12214/fresh-remounts
-- remove  aura 48290 when cast 48297
INSERT INTO  `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES ('48297', '-48290', '0', 'For Fresh Remounts quest');

### Expected Blizzlike Behaviour

Quest not working correct

### Steps to reproduce the problem

Quest not working correct

### AC rev. hash/commit

master

### Operating system

debian

**Comment by heyitsbench** [comment]
First off, this isn't how fixes are submitted, secondly, form is improperly filled out, third, I can already tell you that this:

> UPDATE quest_template SET QuestLevel = '20' WHERE (ID = '2359');

is wrong.

**Comment by elthehablo** [comment]
Feel free to submit a working PR. We will run you through what is wrong and what works

**Comment by Kitzunu** [comment]
One issue per report. So one bugged quest per report filled out in the report form properly.

And a fix is submitted by a PR. Where you fix one Quest or onee Script or one Spell etc including related issues to the specific thing

**Comment by Vtkachenko-Informa** [comment]
> First off, this isn't how fixes are submitted, secondly, form is improperly filled out, third, I can already tell you that this:
> 
> > UPDATE quest_template SET QuestLevel = '20' WHERE (ID = '2359');
> 
> is wrong.
Can explain why this wrong ? I check on wowhead gain exp and quest level
