### ISSUE TITLE
(GameObject): Missing mailbox in Nighthaven.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17013]
### Current Behaviour

There is a missing mailbox in Nighthaven, Moonglade.

### Expected Blizzlike Behaviour

There should be a mailbox [here](https://user-images.githubusercontent.com/38561765/236371043-5238be71-b967-4a91-bcf3-721ca1d7bd76.png).

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.go xyz 7884.7 -2569 487`
2. Observe no mailbox.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/5557.

I almost definitely have a sniff of this thing somewhere, but I don't want to sift right now.

### AC rev. hash/commit

4f015d09678038be49e9d12114c3147e499d82ef

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Vanheden** [comment]
Can check tomorrow if I remember 😁
