### ISSUE TITLE
(Quest): Klaven's Tower has wrong RewardBonusMoney value.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17017]
### Current Behaviour

[Klaven's Tower](https://wowgaming.altervista.org/aowow/?quest=2359) has a RewardBonusMoney value of 132300.

### Expected Blizzlike Behaviour

It should have a value of 2340.

### Source

Wrath Classic sniff

### Steps to reproduce the problem

1. `.quest add 2359`
2. `.levelup 79`
3. `.quest reward 2359`
4. Observe gold reward.

### AC rev. hash/commit

4f015d09678038be49e9d12114c3147e499d82ef

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by ChrisCGalbraith** [comment]
For my own understanding [WotLK Classic](https://www.wowhead.com/wotlk/quest=2359/klavens-tower) indicates that you should receive 13g 23s 00c as a reward if completed at level 80. You say you have a sniff showing that this is in fact incorrect?

**Comment by heyitsbench** [comment]
> You say you have a sniff showing that this is in fact incorrect?

No, I have a sniff saying that I should receive 23s 40c as a reward if completed at level 38. This issue is invalid, I apologize.
