### ISSUE TITLE
Missed / wrong property in worldserver.conf

### ISSUE THREAD

**Issue by wampirr** [azerothcore/azerothcore-wotlk#1701]
Hello!

While configuring my hello world found this:

https://github.com/azerothcore/azerothcore-wotlk/blob/97e7e2228e9b66e15d307f97c1b05160dd612aaa/src/server/worldserver/worldserver.conf.dist#L2319-L2323

Seems to me like a mistake(talent param and mining description).

Thank you.

**Comment by Pondaveia** [comment]
What do you mean with mistake? What's wrong with this configuration?

**Comment by wampirr** [comment]
overall format:
```
# <same config property>
#       descr about it and values
<same config property> = value

```
in other words:
- 1 description for one config property
- 1 value assign for ANOTHER config property
- appropriate missed parts for both of them not found elsewhere in file

I hope that you just did not read my post.

**Comment by Pondaveia** [comment]
I think it's missing because its default value is set on code. If you change it then new alterations should happen. You should the next line and test it. See what's the behaviour 😃 

Rate.Mining.Amount = 2
