### ISSUE TITLE
Hanging Head of Nefarian in Stormwind Disappears after 1 Min

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1702]
##### SMALL DESCRIPTION:

The hanging head of Nefarian in Stormwind disappears after 1 min of player handing in the quest and getting the buff.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The head should display for 2 hours as agreed in https://github.com/azerothcore/azerothcore-wotlk/pull/1662.

##### CURRENT BEHAVIOUR:

The head only displays for about 60 seconds and then disappears.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .use an Alliance character and then .additem 19003
2.  start the quest from the item
3.  follow the quest through
4.  by the end you will see the head disappears after roughly 60 seconds of hanging.

##### EXTRA NOTES:

N/A
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

97e7e22

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by Falstring** [comment]
this should be updated: action_type 50 paramter 2 is measured in seconds.
(@ENTRY,9,3,0,0,0,100,0,3000,3000,0,0,50,179882,7200,0,0,0,0,8,0,0,0,-8925.57,496.042,103.767,2.42801,'Field Marshal Afrasiabi - On Script - Summon Gameobject The Severed Head of Nefarian and despawn after 2 hours'),

---
this should be removed: no point
(@ENTRY,9,6,0,1,0,100,0,30000,30000,0,0,41,7200000,0,0,0,0,0,14,0,179882,0,0,0,0,0,'Field Marshal Afrasiabi - Despawn In 10000 ms');

**Comment by Pondaveia** [comment]
@Falstring make a PR so it can be tested if you will 👍

**Comment by gtao725** [comment]
I can confirm it works properly now. Despawns after 2 hrs exactly. Can merge.
