### ISSUE TITLE
[TBC OHF] Ashbringer gem cleansing event unimplemented

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#17025]
### Current Behaviour

Relevant NPCs (Tirion, Mograine etc.) stand around and say nothing

### Expected Blizzlike Behaviour

They should have an event where they are shown cleansing the gem found near Blackrock Mountain into a gem that was used to craft Ashbringer. Event is supposed to trigger when a player enters the inn (areatrigger?). A pretty cool event imo.

### Source

https://wowpedia.fandom.com/wiki/Ashbringer/Old_Hillsbrad_Ashbringer_event for texts

### Steps to reproduce the problem

1. go to Escape from Durnholde Keep (OHF)
2. go to Southshore
3. enter the inn
4. observe there is no event

### Extra Notes

Maybe TC has it implemented so we can cherry-pick? Otherwise need sniffs

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/pull/17024/commits/27936da63dd888259157ff9c1e5e4d86c65eed2f

### Operating system

Windows 11

### Custom changes or Modules

None. not a clean DB but in this case that is not relevant.

**Comment by fangshun2004** [comment]
I tested the gem purification event and it worked fine and there is a corresponding event in smartai
![WoWScrnShot_082023_062046](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/b8983afe-f802-43a0-87a1-bd6a9c44603b)
![WoWScrnShot_082023_062142](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/6a4b21e6-bb2d-4a65-a596-87b4774b3f8c)
![WoWScrnShot_082023_062258](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/e68c4014-a9d0-4835-b1c3-b8ce27fd737e)
![WoWScrnShot_082023_062312](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/02d444ff-51e2-45cb-bc91-c67654c518ee)
![WoWScrnShot_082023_062314](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/8644988f-9add-43f6-aa60-67c4d46028ed)
![WoWScrnShot_082023_062326](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/466f886a-8cf3-4a24-b792-8074f5403db4)

**Comment by elthehablo** [comment]
Ye mb it was implemented. Oversight on my part
