### ISSUE TITLE
[NPC] Paelarin should discriminate against troll players

### ISSUE THREAD

**Issue by Salehyn** [azerothcore/azerothcore-wotlk#17036]
Original report: https://github.com/chromiecraft/chromiecraft/issues/6060
Reported by: https://github.com/heyitsbench

**What client do you play on?**

enUS

**Faction**

Horde

**Content Phase:**

1-19

**Current Behaviour**

[Paelarin](https://wowgaming.altervista.org/aowow/?npc=16263) is more than happy to act as a vendor regardless of his customer's race.

**Expected Blizzlike Behaviour**

[He should not be willing to do business with trolls.](https://github.com/chromiecraft/chromiecraft/assets/38561765/ce8d36ca-f46d-4ead-bf6c-92477ac2e29b)

**Source**

Wrath Classic

**Steps to reproduce the problem**

    .go c id 16263 as a troll. (or .go c 56974)
    Interact with Paelarin.

**Extra Notes**

From wowhead: "He hates trolls, because, if you noticed where he is, a Farstrider retreat, doesn't take too kindly on trolls. Farstriders have been fighting Amani for thousands of years, and recently in the Second War trolls also were part of the Horde that set fire to their beloved forests.
Nevertheless, the feeling is mutual I bet, elves and trolls have never gotten along."

No response
AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd
Operating system

Ubuntu 20.04
Modules

    [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

Customizations

None
Server

ChromieCraft

**Comment by Maria-sequel** [comment]
npc_text ID 8679
