### ISSUE TITLE
Spell `36298` Effect `Index: EFFECT_0 Name: 77` of script `spell_q10651_q10692_book_of_fel_names`

### ISSUE THREAD

**Issue by Wishmaster117** [azerothcore/azerothcore-wotlk#17045]
### Current Behaviour

Hi,
I pulled latest updates and compiled them.
Now when i start worldserver i have this error:
Spell `36298` Effect `Index: EFFECT_0 Name: 77` of script `spell_q10651_q10692_book_of_fel_names` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed

Can someone help whith this?

Best regards

### Expected Blizzlike Behaviour

Correct this error

### Steps to reproduce the problem

Start world server
Validating Spell Scripts...
Spell `36298` Effect `Index: EFFECT_0 Name: 77` of script `spell_q10651_q10692_book_of_fel_names` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed

### AC rev. hash/commit

Calendar deletion of old events.
.server debug
AzerothCore rev. 5367eb4b1dfb+ 2023-08-19 22:44:05 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 33 second(s)
Update time diff: 2ms, average: 3ms.
Using SSL version: OpenSSL 3.1.1 30 May 2023 (library: OpenSSL 3.1.1 30 May 2023)
Using Boost version: 1.82.0
Using CMake version: 3.27.0
Using MySQL version: 80034
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Build/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Build/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: account_bound_mounts.sql
Latest CharacterDatabase update: mod_individual_xp_IndividualXP.sql
Latest WorldDatabase update: mod_individual_xp_command.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-account-achievements
- mod-accountbound
- mod-autobalance
- mod-eluna
- mod-guildhouse
- mod-individual-xp
- mod-learn-spells
- mod-multi-vendor
- mod-npc-buffer
- mod-npc-services
- mod-pocket-portal
- mod-solo-lfg

### Operating system

Windows 10 pro

**Comment by Kitzunu** [comment]
Then you did something wrong, because Dry Run CI runs without errors https://github.com/azerothcore/azerothcore-wotlk/actions/runs/5918305472/job/16047494600

**Comment by Kitzunu** [comment]
Also spell_q10651_q10692_book_of_fel_names does not exist in azerothcore. So you are not running a clean AC

**Comment by Wishmaster117** [comment]
Thanks for your answer. 
It's strange because I cloned this azerothcore repository.
I'me a newbi so how can I solve this without looking all mods and players database, I don't have this error before pulled last updates. 
Where should I look to found this script ?
Thanks and regards.

**Comment by Kitzunu** [comment]
The script does not exist. So i cannot tell you

**Comment by Kitzunu** [comment]
Github is not for support. Join discord and ask for help there

**Comment by GastonCK** [comment]
Same Issue, clean compilation, can play but the red message is there
commit https://github.com/azerothcore/azerothcore-wotlk/commit/80a8f6d47a8a48869de197ed95c23b80c0999476
![AC ERROR](https://github.com/azerothcore/azerothcore-wotlk/assets/65800273/19f5b528-212d-4bcc-8f3e-b0bda44cbc5a)

**Comment by Wishmaster117** [comment]
Yes i juste cloned the official repository to see and founs this spell codes il file \azerothcore-wotlk\src\server\scripts\Spells\spell_quest.cpp

So this is a issue.

I don't use moded core.

enum book
{
    SPELL_METAMORPHOSIS   = 36298
};

class spell_q10651_q10692_book_of_fel_names : public SpellScript
{
    PrepareSpellScript(spell_q10651_q10692_book_of_fel_names);

    void HandleScript(SpellEffIndex /*effIndex*/)
    {
        GetHitUnit()->RemoveAurasDueToSpell(SPELL_METAMORPHOSIS);
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_q10651_q10692_book_of_fel_names::HandleScript, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};

**Comment by heyitsbench** [comment]
> Also spell_q10651_q10692_book_of_fel_names does not exist in azerothcore. So you are not running a clean AC

Added with edc92b42822cbb33cf283011588647cf36474585 I believe.

**Comment by Kitzunu** [comment]
Very odd CI does not fail

**Comment by heyitsbench** [comment]
> Very odd CI does not fail

[Happens in the CI](https://github.com/azerothcore/azerothcore-wotlk/actions/runs/5918305469/job/16047494664#step:9:1319), just doesn't fail it.

**Comment by Kitzunu** [comment]
Because it isnt recorded as a DBError, thats why
