### ISSUE TITLE
[Karazhan] if opera kill Dorothee very fast, the rest npc will not attackable, instance will always in combit.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#17067]
### Current Behaviour

if opera kill Dorothee very fast, the rest npc will not attackable, instance will always in combit.  thoes who out of the instance will never can go back to this instance and can not continuous.

I think maybe below code did not consider the Dorothee die before Schedule time.

    void ScheduleActivation()
    {
        _scheduler.Schedule(16670ms, [this](TaskContext)
        {
            if (Creature* roar = instance->GetCreature(DATA_ROAR))
            {
                roar->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                roar->SetImmuneToPC(false);
                roar->SetInCombatWithZone();
            }
        }).Schedule(26300ms, [this](TaskContext)
        {
            if (Creature* strawman = instance->GetCreature(DATA_STRAWMAN))
            {
                strawman->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                strawman->SetImmuneToPC(false);
                strawman->SetInCombatWithZone();
            }
        }).Schedule(34470ms, [this](TaskContext)
        {
            if (Creature* tinhead = instance->GetCreature(DATA_TINHEAD))
            {
                tinhead->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
                tinhead->SetImmuneToPC(false);
                tinhead->SetInCombatWithZone();
            }
        });
    }

there maybe some other boss has the same logical problem. and case instance will always in combit. 

### Expected Blizzlike Behaviour

Will continuous even if Dorothee died before other boss active

### Steps to reproduce the problem

just kill Dorothee very fast first , the other boss will not be attack and also will not attack player, and the instance will always in combit

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/3c2e73a6-5fa6-4d69-b92e-03b689660e05)

### AC rev. hash/commit

AzerothCore rev. 4c287e2873c3+ 2023-08-22 12:13:36 +0200 (HEAD branch) (Unix, RelWithDebInfo, Static)
Connected players: 63. Characters in world: 61.
Connection peak: 181.
服务器运行时间: 19 hour(s) 38 minute(s) 53 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 3.0.9 30 May 2023 (library: OpenSSL 3.0.9 30 May 2023)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101103
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.2.16-6-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
                         All available DBC locales: zhCN 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: zone_difficulty_instance_saves.sql
Latest WorldDatabase update: zone_difficulty_spelloverrides.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-reward-played-time
- mod-save-inventory
- mod-server-auto-shutdown
- mod-zone-difficulty
- mod_spec_reward

### Operating system

debian 12 x64

**Comment by danqu** [comment]
问题在于BOSS死亡之后，BOSS实例不存在了，延迟处理中断了，
我现在的修复方式是在BOSS死亡时，如果还没有加入战斗的，全部移除UNIT_FLAG_NON_ATTACKABLE状态

    void ActivateUnit(uint32 unitId)
    {
        if (Creature* unit = instance->GetCreature(unitId))
        {
            unit->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
            unit->SetImmuneToPC(false);
            unit->SetInCombatWithZone();
        }
    }

    void ScheduleActivation()
    {
        _scheduler.Schedule(16670ms, [this](TaskContext)
            {
               ActivateUnit(DATA_ROAR);
            }).Schedule(26300ms, [this](TaskContext)
            {
               ActivateUnit(DATA_STRAWMAN);
            }).Schedule(34470ms, [this](TaskContext)
            {
            ActivateUnit(DATA_TINHEAD);
            });
    }

**Comment by kissingers** [comment]
> 问题位于BOSS死亡之后，BOSS实例不存在了，延迟处理中断了， 我现在的修复方式是在BOSS死亡时，如果还没有加入战斗的，全部移除UNIT_FLAG_NON_ATTACKABLE状态
> 
> ```
> void ActivateUnit(uint32 unitId)
> {
>     if (Creature* unit = instance->GetCreature(unitId))
>     {
>         unit->RemoveUnitFlag(UNIT_FLAG_NON_ATTACKABLE);
>         unit->SetImmuneToPC(false);
>         unit->SetInCombatWithZone();
>     }
> }
> 
> void ScheduleActivation()
> {
>     _scheduler.Schedule(16670ms, [this](TaskContext)
>         {
>            ActivateUnit(DATA_ROAR);
>         }).Schedule(26300ms, [this](TaskContext)
>         {
>            ActivateUnit(DATA_STRAWMAN);
>         }).Schedule(34470ms, [this](TaskContext)
>         {
>         ActivateUnit(DATA_TINHEAD);
>         });
> }
> ```

看你这个修复,应该不全对吧? 在die地方也应用要引用一次  ActivateUnit ?  否则和原来代码没本质差别?

**Comment by danqu** [comment]
void JustDied(Unit* /*killer*/) override
    {
        Talk(SAY_DOROTHEE_DEATH);
        ActivateUnit(DATA_ROAR);
        ActivateUnit(DATA_STRAWMAN);
        ActivateUnit(DATA_TINHEAD);
        SummonCroneIfReady(instance, me);
        me->DespawnOrUnsummon();
    }
    
    那是肯定需要的啊

**Comment by elthehablo** [comment]
> ```
> void JustDied(Unit* /*killer*/) override
> {
>     Talk(SAY_DOROTHEE_DEATH);
>     ActivateUnit(DATA_ROAR);
>     ActivateUnit(DATA_STRAWMAN);
>     ActivateUnit(DATA_TINHEAD);
>     SummonCroneIfReady(instance, me);
>     me->DespawnOrUnsummon();
> }
> 
> 那是肯定需要的啊 
> ```

I don't think this is how blizzard does it, unless you have proof for that. But yes this was an oversight on my part on my last PR, likely not a problem during progression, but still possible.

**Comment by elthehablo** [comment]
So the best solutions is probably to move the clocks back to the original units

**Comment by danqu** [comment]
Of course, Blizzard doesn't operate this way, and this can only be a temporary solution

**Comment by elthehablo** [comment]
> Of course, Blizzard doesn't operate this way, and this can only be a temporary solution

Better to wait for the right solution to come with sniffs before we fix a hack-fix with a hack-fix imo. But feel free to make a PR ofc

**Comment by elthehablo** [comment]
Another solution would be to let the schedulers run in the last activated npc. That guy can ofc not die before the others die

**Comment by danqu** [comment]
Yes, scheduling it to the final NPC and executing the removal of UNIT_FLAG_NON_ATTACKABLE activation is the best solution

**Comment by kissingers** [comment]
thanks discuss about the solution, but the problem happen very offen,  because Dorothee HP very low, and died quickly, and total instance can continue. so if can fix this as a high Priority PR?

**Comment by elthehablo** [comment]
yes I will make a PR using your ideas rn. thanks

**Comment by elthehablo** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/17077 test?

**Comment by kissingers** [comment]
> [第17077章](https://github.com/azerothcore/azerothcore-wotlk/pull/17077)测试？

Tested , it seems all ok, thanks!
