### ISSUE TITLE
DBImport crashes without logging if config file doesn't exist

### ISSUE THREAD

**Issue by michaeldelago** [azerothcore/azerothcore-wotlk#17065]
### Current Behaviour

When starting `dbimport` without creating a config file, it crashes without any output (to either stderr or sdtout)

```console
$ /src/tools/dbimport
$ echo $?
1
$ ls /usr/local/etc/dbimport.conf
ls: cannot access '/usr/local/etc/dbimport.conf': No such file or directory
```

the `--help` option works fine

```console
$ src/tools/dbimport --help
Allowed options:
  -h [ --help ]                         print usage message
  -v [ --version ]                      print version build info
  -d [ --dry-run ]                      Dry run
  -c [ --config ] arg (="/usr/local/etc/dbimport.conf")
                                        use <arg> as configuration file
```

specifying a (valid) config allows the dbimport to run

```console
$ src/tools/dbimport -c ../src/tools/dbimport/dbimport.conf.dist
AzerothCore rev. 4c287e2873c3+ 2023-08-22 12:13:36 +0200 (master branch) (Unix, RelWithDebInfo, Static) (dbimport)
<Ctrl-C> to stop.

# startup continues, banner shows, etc ...
```

### Expected Blizzlike Behaviour

dbimport should

The worldserver logs an error:

```console
$ src/server/apps/worldserver
> Config::LoadFile: Failed open file '/usr/local/etc/worldserver.conf'
```

The authserver logs an error:

```console
$ src/server/apps/authserver
> Config::LoadFile: Failed open file '/usr/local/etc/authserver.conf'
```

### Steps to reproduce the problem

Build AzerothCore as you normal, dont create the configs

1. `mkdir build && cd build`
2. `cmake ../ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DWITH_WARNINGS
=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static`
3. `make -j$(nproc)`
4. observe failure without logging `./src/tools/dbimport`
5. Observer failure with logging `./src/server/apps/worldserver`

### AC rev. hash/commit

$ git rev-parse HEAD
4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Linux x64

### Custom changes or Modules

Stock repo with no changes.

**Comment by Kitzunu** [comment]
So we need to make sure a dbimport.conf is created at build

**Comment by michaeldelago** [comment]
The `dbimport.conf.dist` is created at build, it's only moved around with `make install` or `cmake --install` (link to src https://github.com/azerothcore/azerothcore-wotlk/tree/master/src/cmake/macros/ConfigInstall.cmake#L46-L72)

so we just need to make sure that whatever happens for the worldserver/authserver is also happening for the dbimport. I spent some time trying to poke at it to figure it out, but nothing obvious came up 🙃

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/c43f62f6a9617fe7f7bb3f1309c373aa2ba137a1
