### ISSUE TITLE
Creatures in Shadowmoon Valley

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#1707]
Creatures in Shadowmoon Valley

##### SMALL DESCRIPTION:

The creatures doesn't do damage.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should attack the players and do damage with their abilities
[NPC Dragonmaw Peon](https://www.wowhead.com/npc=22252/dragonmaw-peon#abilities)
1. [Sunder Armor](https://www.wowhead.com/spell=15572/sunder-armor)
2. [Kick](https://www.wowhead.com/spell=34802/kick)

##### CURRENT BEHAVIOUR:
 In Shadowmoon Valley, preciously in Netherwing Ledge, there are a lot NPC's Dragonmaw Poen. If you walk near them, they will enter in combat, but they just follow player, doesn't do any damage or something

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go creature 78000
2. Enter in combat
3. Check will they attack, use their abilities & damage you

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
 97e7e22

##### OPERATING SYSTEM:
 Windows

##### MODULES:
 NO

##### OTHER CUSTOMIZATIONS:
 NO

**Comment by Stoabrogga** [comment]
What has happened to #1678 and #1676?

**Comment by poszer** [comment]
> What has happened to #1678 and #1676?

Not tested by more people, to confirm that PR was correct, so we closed it. Waiting someone to create better one
