### ISSUE TITLE
[TBC Karazhan] Shade of Aran movement behaviour is wrong

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#17073]
Originally reported on CC at: https://github.com/chromiecraft/chromiecraft/issues/4891
By: [NinesCC](https://github.com/NinesCC)

Problem is related to the general caster AI. If you were to disallow combat movement he would be able to be cheesed out of melee.

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Shade of Aran will chase players around. https://youtu.be/kcHT_7cOTgE?t=10030

### Expected Blizzlike Behaviour

He should stay static in the center of the room.

### Source

2007 Footage
https://youtu.be/K9QzLjMSWcE

### Steps to reproduce the problem

1.   Enter Karazhan by the backdoor
2.   Go upstairs, past Curator
3.   Enter Aran's room and engage him
4.   Kite him around.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b3e37226745a6e6de308bb7b00f0d2f9c596938e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by v-mstrs** [comment]
> he would be able to be cheesed out of melee.

What do you mean by that ?

**Comment by elthehablo** [comment]
> > he would be able to be cheesed out of melee.
> 
> What do you mean by that ?

I mean for a brief period of time you would see him just standing still looking at you with his staff at the ready if you are not in his melee range. Imagine ragnaros but without his lava blast he does when nobody is in range

**Comment by shaszun** [comment]
Flame Wrath by the boss wasn't used at all in your video.

**Comment by Nyeriah** [comment]
He should relocate only if he's unable to land his spells

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/47818697/37bf9d77-30e5-433c-90b9-819d4765f7d9)

**Comment by Nyeriah** [comment]
This is a wrong/inaccurate report
