### ISSUE TITLE
Cannot swap bags unless old bag is empty 

### ISSUE THREAD

**Issue by Salehyn** [azerothcore/azerothcore-wotlk#17084]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/6070
Reported by: https://github.com/balleny

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

when you try to drag and drop an unused bag above a used bag, but the used bag contains items, you receive the error:
"you can only do this with empty bags"

right now, you have to empty the bag, exchange it, and then you  can refill it.

### Expected Blizzlike Behaviour

You should be able to exchange a bag in use with a different bag from your inventory if
1. the slots used/occupied in the bag are less or equal to the number of slots of the new bag
2. you dont have conflicting itemtypes (regular bag with ores and herbs, trying to replace it with a herb-only bag)

### Source

https://worldofwarcraft.fandom.com/et/wiki/Bag
Confirmed as per stated in the wiki. In vanilla you needed to empty bags before changing them but this was fixed sometime during BC. 
Here is another thread discussing to add it to classic ahead of its time:
https://www.reddit.com/r/classicwow/comments/9rqijf/swap_bags_without_emptyinghttps://worldofwarcraft.fandom.com/et/wiki/Bag

This is a consistent issue on cc.

### Steps to reproduce the problem

.additem 38082 for gigantique bags
equip a bag, put in 1 item.
drag and drop a different bag ontop of the filled bag

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
iirc this is blizzlike. Can you provide a source

**Comment by elthehablo** [comment]
We need the Benchman

**Comment by Nyeriah** [comment]
You can swap bags with items on retail yes done it all the time. Would make it virtually impossible to replace small bags early Dane otherwise without deleting a lot of items

**Comment by Gultask** [comment]
Don't know about **retail** retail but Classic I know for sure you can swap without removing items first

**Comment by elthehablo** [comment]
Might look into this. Seems tricky to solve. Especially since I know nothing about how bagspace is handled

**Comment by Salehyn** [comment]
Sorry I linked all the evidences into comment on cc GitHub. I'll copy them into the AC report too

**Comment by Kitzunu** [comment]
That quote does not exist on wowwiki https://wowpedia.fandom.com/wiki/Bag. Or it was poorly translated from the link you provided

There is also nothing on it from 2010 https://wowpedia.fandom.com/wiki/Bag?oldid=2158120

I am not saying this issue is wrong, because I do not know, but I believe I remember reading somewhere long ago that this is a client limitation. Which would make this issue invalid. But don't quote me on that

**Comment by heyitsbench** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/ab2c6cee-49a6-475a-869b-d9fedf1ff7d1)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/17086

**Comment by heyitsbench** [comment]
Even more evidence that this was added by 3.3.5a: [GameFAQs board article circa July '08](https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/44403056).

**Comment by Salehyn** [comment]
You linked a different wiki. I quoted from the one I put in the report.
And yeah there are a dozen forum discussions about it too.

**Comment by heyitsbench** [comment]
> I quoted from the one I put in the report.

The wiki linked in the report includes no source, no patch for the changes, and no mention of it changing between vanilla/retail. The edit history is all well past-Wrath and almost certainly copied verbatim from another site. Excuse us if we don't regard it with much trust.

**Comment by Salehyn** [comment]
It's actually a rather trustworthy wotlk wiki that devotes special attention to outline cataclysm changes. It's definitely no less reliable than random comments based on individual player experiences. You're right it should not be the sole source used. How fortunate I provided another.

**Comment by Kitzunu** [comment]
How awesome we established this already and I already fixed the issue. So no need to comment about it anymore :) 👍

**Comment by heyitsbench** [comment]
> So no need to comment about it anymore :) 👍

Proper sourcing is important.

**Comment by Salehyn** [comment]
> How awesome we established this already and I already fixed the issue. So no need to comment about it anymore :) 👍
> 
> > You linked a different wiki. I quoted from the one I put in the report.
> 
> Fair, I saw /et/ so I removed it from the link, as I obviously want an English website, and that automatically redirected me to wowpedia. I didn't see it was written in English because I went straight to see edit history, and that was definitely not in English. hence why I removed /et/ from the link

Don't worry it's just the game we play with Bench. He can't resist an opportunity to call my sources shit because I didn't sniff them with my own nose 😂

**Comment by heyitsbench** [comment]
> Don't worry it's just the game we play with Bench. He can't resist an opportunity to call my sources shit because I didn't sniff them with my own nose 😂

Play nice.
