### ISSUE TITLE
Mark of the Wild	has different values in spellbook and in buff

### ISSUE THREAD

**Issue by Vtkachenko-Informa** [azerothcore/azerothcore-wotlk#17089]
### Current Behaviour

When you cast  Mark of the Wild you have different values in spell book and in buff
<img width="334" alt="image" src="https://github.com/azerothcore/azerothcore-wotlk/assets/122799938/84bb90b7-3994-4a2f-9f89-7f9eed5b8481">
<img width="301" alt="image" src="https://github.com/azerothcore/azerothcore-wotlk/assets/122799938/0c547f06-8304-4439-be70-12c9c1f013de">

### Expected Blizzlike Behaviour

values need be same in spell book and in buff

### Steps to reproduce the problem

cast Mark of the Wild

### AC rev. hash/commit

 AzerothCore rev. 23c5e990b6b6+ 2023-08-25 22:02:21 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 34. Characters in world: 34.
Connection peak: 43.
Server uptime: 17 hour(s) 59 minute(s) 46 second(s)
Update time diff: 3ms, average: 91ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80034
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-78-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS ruRU
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-transmog

### Operating system

debian

**Comment by Salehyn** [comment]
This is a general behaviour for most buffs that are enhanced by talents. Spell tooltip updates, buff tooltip does not. Afaik this is working as intended
https://us.forums.blizzard.com/en/wow/t/dampen-magic-buff-tooltip-bug-classic-era/1654791

**Comment by Tereneckla** [comment]
Buffs changing tooltip according to talents and other things was added in cataclysm
