### ISSUE TITLE
 Yogg-Saron Phase 2 Portal Failure

### ISSUE THREAD

**Issue by sd3420625** [azerothcore/azerothcore-wotlk#17098]
### Current Behaviour

In the last two versions, the az server installed with docker, when fighting the final boss Yogg-Saron of Ulduar, clicking on the portal in the second stage has no effect and cannot enter the interior. After testing, it is found that the portal skill is invalid, whoever has the ability, please help to fix it, thank you very much!

### Expected Blizzlike Behaviour

unknown

### Steps to reproduce the problem

Enter Ulduar and fight Yogg-Saron

### AC rev. hash/commit

unknown

### Operating system

ubuntu20.04

**Comment by yi-Lee** [comment]
I also encountered this problem today. May I ask if there is any solution to this problem?

**Comment by yi-Lee** [comment]
> ### 当前行为
> 在最后两个版本中，安装了docker的az服务器，在与Ulduar的最终BOSS约格-萨隆战斗时，点击第二阶段的传送门没有效果，无法进入内部。经测试发现传送门技能无效，有本事者，请帮忙修复，非常感谢！
> 
> ### 预期的暴风雪行为
> 未知
> 
> ### 源
> _无响应_
> 
> ### 重现问题的步骤
> 进入乌尔杜尔，与约格-萨隆战斗
> 
> ### 额外说明
> _无响应_
> 
> ### AC 修订哈希/提交
> 未知
> 
> ### 操作系统
> 乌班图20.04
> 
> ### 自定义更改或模块
> _无响应_

Have you solved the problem?
