### ISSUE TITLE
Worldserver.exe crashed at connectig (ASSERTION FAILED - C0000420)

### ISSUE THREAD

**Issue by pagimu** [azerothcore/azerothcore-wotlk#17099]
### Current Behaviour

Worldserver.exe crashed after I have start wow.exe. 

### Expected Blizzlike Behaviour

Correct Connection 

### Steps to reproduce the problem

1. Compile the latest build (AzerothCore rev. 5d01b700fd01+)
2. Launch mysql, authserver and worldserver
3. start wow.exe

### Extra Notes

The last few Builds I was using runs also with all modules below. And they was working fine. I have also test a new compiled Build without any modules. The same problem. I have found https://github.com/azerothcore/azerothcore-wotlk/issues/15980. But that doesn't help.

### AC rev. hash/commit

[5d01b700fd01+_worldserver.exe_[28-8_14-12-10].txt](https://github.com/azerothcore/azerothcore-wotlk/files/12454307/5d01b700fd01%2B_worldserver.exe_.28-8_14-12-10.txt)

### Operating system

Win11 Pro

### Custom changes or Modules

> 1v1arena.conf
> mod_ahbot.conf
> AutoBalance.conf
> mod_charactertools.conf
> mod_LuaEngine.conf
> Individual-XP.conf
> mod_moneyforkills.conf
> reagent_bank.conf
> reward_system.conf
> reward_shop.conf
> SoloLfg.conf
> Solocraft.conf
> transmog.conf
> mod-weapon-visual.conf

**Comment by Kitzunu** [comment]
Upload your crashlog in gist. Without it there's nothing to be done

**Comment by Kitzunu** [comment]
Also try without any modules first

**Comment by Aaltan** [comment]
I am also experiencing the same issue. 
I just finished an installation on Ubuntu 22.04 with updated sources. 
This is the message the server outputs upon login: 

#----------------------------------------------------------------------#

>> ASSERTION FAILED

# Location '/home/lancer/azerothcore/src/common/Cryptography/ARC4.cpp:31'
# Function 'ARC4'
# Condition 'result == 1'

#----------------------------------------------------------------------#

The sources from a couple of weeks ago were working correctly.

**Comment by heyitsbench** [comment]
> I am also experiencing the same issue.

Then upload your crashlog through [gist](https://gist.github.com/).

**Comment by Aaltan** [comment]
Never done, please tell me how.

**Comment by heyitsbench** [comment]
> Never done, please tell me how.

Drag and drop the *.txt crashlog file into a new gist and hit create. Then paste the link to the gist here.

**Comment by Kitzunu** [comment]
You find the crashlog in the crashlog folder

**Comment by Aaltan** [comment]
Sorry guys, but I can't find any 'crashlog' folder, nor any '.txt' or '.log' files, 
except the usual ones (Auth.log, Errors.log and Server.log).
Where is it located, or do I need to enable some parameter in worldserver.conf, please ?

**Comment by Kitzunu** [comment]
/build/RelWithDebInfo/crash/ is the directory

**Comment by Aaltan** [comment]
Well, mine it's an Ubuntu installation

**Comment by Aaltan** [comment]
What a quick fix.
Thank you.

**Comment by heyitsbench** [comment]
> What a quick fix.

Can't be keeping crashes around. 😛
