### ISSUE TITLE
quest 12730  bugged 

### ISSUE THREAD

**Issue by cnmir2** [azerothcore/azerothcore-wotlk#171]
**Description**:
quest 12730 bugged 
**Current behaviour**: Tell us what happens
the item cant use to summon the npc 28996
**Expected behaviour**: Tell us what should happen instead
but you could use .learn spell 55884 to summon the npc !
the npc smart script is ok! 
**Steps to reproduce the problem**:

1. .quest add 12730
2. .go 6443.1 -4470.6 451 571 
3. use the quest item no response;  if you .learn spell 55884 and  click the spell the quest could finished 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
win7
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by HeartWell** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/34
