### ISSUE TITLE
[Hunter] Pets abilities,focus and gcd

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#17115]
Original issue: https://github.com/chromiecraft/chromiecraft/issues/4851

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

- Pets are not dumping focus when spells are available to be cast. The issue doesn't always happen, only works properly in the beginning phase when they initially dump focus but after it starts regening from 0 you can see this odd behaviour.

- Devilsaurs [Monstrous bite](https://wowgaming.altervista.org/aowow/?spell=55498) is not alwaying being prioritized over [Bite](https://wowgaming.altervista.org/aowow/?spell=27050) which leads to the buff falling off often.

- Wasps [Sting](https://wowgaming.altervista.org/aowow/?spell=56630) similar issue where special ability is not being recast when the debuff is up which is not blizzlike, debuff uptime won't be 100% because of this.

- Harder to track but pet gcd is wrongfully 1.5secs. 

### Expected Blizzlike Behaviour

- Pets shouldn't be pooling 40-50 energy before casting abilities.
- Monstrous bite or pet special abilities in general should be prioritized, they cost less focus than bite, claw, smack, etc.
- Pet gcd should be @ 1.25 secs. This was a known issue back in wotlk (not present in the current classic). Unsure if it was intended since there's no official changelog mention about this but was reported as such by players back then as well.

### Source

Shandara spreadsheet shows bite with a 1.25 gcd. **https://docs.google.com/spreadsheets/d/1OyAHQHFgyskXLMn60mGff9sd2DkXCuZcda3UDPLiu9E/edit#gid=1774281807**

https://www.wowhead.com/forums/topic/pet-combat-some-questions-157123 
`Pets have a GCD of 1.25 seconds on all abilities no matter what.
`

Also some discussions on classic hunter discord on how gcd used to be 1.25 but is 1.5 currently on classic, if you wanna search it up. **https://discord.gg/classichunter**

Video of wasp casting its ability on cd rather than waiting till the debuff falls off. **https://youtu.be/RsUu7nEvzr8?t=452**

### Steps to reproduce the problem

Test all the issues I'm describing with a pet on training dummies.

### AC rev. hash/commit

6cd3b2a32cd9

### Operating system

Ubuntu 20.04 - Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
One bug per issue. Here you are describing 3
