### ISSUE TITLE
[Azshara] Truesilver Vein spawned above ground

### ISSUE THREAD

**Issue by damnablebear** [azerothcore/azerothcore-wotlk#17111]
### Current Behaviour

Truesilver node in Azshara spawns slightly too high above the ground, showing more of the model than is normally standard for ore notes. (GUID 9329)
![264374669-d2139e66-c17f-465d-a266-adda16a45f55](https://github.com/azerothcore/azerothcore-wotlk/assets/127447064/d058e690-29c5-45c0-88d1-e817c3d847ce)

### Expected Blizzlike Behaviour

Node should be spawned lower so that less of the model is above-ground, like many other nodes in game.

### Steps to reproduce the problem

.tele azshara 
.go xyz 3276.414062 -5124.830078 87.242325
See node sticking out a bit high from the ground.

### Extra Notes

Originally reported here. https://github.com/chromiecraft/chromiecraft/issues/1247

Verified on my local AC install.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
Fixed with 34ff19309fde1c8a05881b5bc7714603f0455975.
