### ISSUE TITLE
[Molten Core] Majordomo Executus [$25]

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#1713]
##### SMALL DESCRIPTION:

1. He is missing the following text after defeat [Proof](https://wowwiki.fandom.com/wiki/Majordomo_Executus)

> Brashly, you have come to wrest the secrets of the Living Flame! You will soon regret the recklessnss of your quest.
> I go now to summon the lord whose house this is. Should you seek an audiance with him, your paltry lives will surely be forfeit! Nevertheless, seek out his lair, if you dare!

2. He teleports to the wrong location

3. Missing spell that summons ragnaros and text [Proof](https://www.youtube.com/watch?v=TflRQdFliVY&t=21s)

-------------------------------------------------------------------------------------------------
Research by @T1ti : 
- https://classic.wowhead.com/spell=21086/encouragement is missing, Majordomo should cast it whenever an add dies, it will buff all the adds. buff should reset on wipe
- healing mechanic is missing, whenever all adds except 1 dies, the last add should heal to full and become buffed
I believe it comes from this spell : https://classic.wowhead.com/spell=21090/champion
but it's missing in the 3.3.5 DBC
-when only 4 adds remain, he should cast https://classic.wowhead.com/spell=21087/immunity (also missing in dbc) which makes the remaining adds immune to fear and polymorph
-teleport's visual is missing 
https://classic.wowhead.com/spell=19484/majordomo-teleport-visual
-he is missing the separation anxiety mechanic, this is the standard anti abuse mechanic, when adds are too far, make them enrage and immune to cc
https://classic.wowhead.com/spell=21095/separation-anxiety
triggered by https://classic.wowhead.com/spell=21094/separation-anxiety

-he should use aegis of ragnaros on pull on himself and say text

-teleport isn't working at all atm(after after filling the missing spell_target_position data in db) and doesn't do anything.

-he has two teleport spells, one which teleport the tank, another which teleports a random player. he should cast one of the two, similar to gehennas' shadow bolt. His teleport should also reset the tank threat(only the tank tp ?)

-majordomo shouldn't sue the spell "blast wave", only the Elites use it

-his defeat event is pretty lame, he just despawns, he should use some teleport spells with visuals
https://classic.wowhead.com/spell=19484/majordomo-teleport-visual
--------------------------------------------------------------------------------------------------

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Check proof for details

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele moltencore
2. Kill all bosses until Majordomo Executus spawns
3. Fight him but don't kill
4. Check his dialogue with sound and notice missing texts
5. Check his position at Ragnaros'es chamber and talk to him to initiate encounter

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

57a5f26eb1767325afcae1915e3054ff1105d3f3

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

**Comment by poszer** [comment]
Just tested, but i can't confirm everything that you report in this issue:

_About text, He's missing next text on Summon_ : 
- [ ] Majordomo Executus says: Very well, <name>.

- [ ] Majordomo Executus yells: Imprudent whelps! You've rushed headlong to your own deaths! See now, the master stirs!

_And the text that you mention for Majordomo Executus on defeat:_

- [ ] Brashly, you have come to wrest the secrets of the Living Flame! You will soon regret the recklessnss of your quest.

- [ ] I go now to summon the lord whose house this is. Should you seek an audiance with him, your paltry lives will surely be forfeit! Nevertheless, seek out his lair, if you dare!

Now, about teleport. I can't confirm that he's teleporting to wrong location (For me, the location is fine, checked some old videos and looks correct).

**Comment by Pondaveia** [comment]
Did you watch the video I linked? His position is like 10 yards to his current position on Azerothcore. When you talk to him then he walks to his final position while casting a spell.
The defeat text is when you beat his fight, not when he gets killed by Ragnaros. You can hear the voice but not read the text.

**Comment by poszer** [comment]
> Did you watch the video I linked? His position is like 10 yards to his current position on Azerothcore. When you talk to him then he walks to his final position while casting a spell.
> The defeat text is when you beat his fight, not when he gets killed by Ragnaros. You can hear the voice but not read the text.

Yes, i watch and that's not correct from the video you posted. If you have account on bliz, check there correct position where this creature teleport, or check the official warcraft movies. 
It's the same like on this video, and same like on AC :  [Take a look](https://youtu.be/BYMGYNH2L_Y)
Also for the text, i have linked what's quotes missing for this Boss on defeat, not the corresponding voice-text .

Also, when you beat he's adds there and when he become as friendly target the voice-text should go in this way: 

- Impossible! Stay your attack, mortal... I submit! I submit!

- Brashly, you have come to wrest the secrets of the Living Flame! You will soon regret the recklessnss of your quest.

- I go now to summon the lord whose house this is. Should you seek an audiance with him, your paltry lives will surely be forfeit! Nevertheless, seek out his lair, if you dare!

- Than Teleport Animation.

When you gone there he continue : 

- Behold Ragnaros - the Firelord! He who was ancient when this world was young! Bow before him, mortals! Bow before your ending!

- Ragnaros yells: TOO SOON! YOU HAVE AWAKENED ME TOO SOON, EXECUTUS! WHAT IS THE MEANING OF THIS INTRUSION???

- Majordomo Executus yells: These mortal infidels, my lord! They have invaded your sanctum and seek to steal your secrets!

- Ragnaros yells: FOOL! YOU ALLOWED THESE INSECTS TO RUN RAMPANT THROUGH THE HALLOWED CORE? AND NOW YOU LEAD THEM TO MY VERY LAIR? YOU HAVE FAILED ME, EXECUTUS! JUSTICE SHALL BE MET, INDEED!

- Ragnaros kills Executus with Elemental Fire, instantly killing him and empowering himself.

- Majordomo Executus: My flame... Please, don't take away my flame...

- Ragnaros yells: NOW FOR YOU, INSECTS! BOLDLY, YOU SOUGHT THE POWER OF RAGNAROS. NOW YOU SHALL SEE IT FIRSTHAND!

Than the fight start :D

**Comment by Seebaby** [comment]
So I have to say that what's not true I only know that in Classic Majordomo Executus that you looked at him and said a few sentences and then teleported.

After that he didn't stand where he stands now but walked a little and cast a cast that had made a big flame aoe then Ragnaros appeared and the two spoke a little.

Video https://www.youtube.com/watch?v=nCX3HV4vlXA Classic Time

**Comment by T1ti** [comment]
I'm not able to summon majordomo at all, anyone else confirm ?
