### ISSUE TITLE
[PvP] Dispel magics (such as Purge, Tranquilizing shot and Dispel magic) remove all charges from a beneficial spell

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#17130]
Related issue: https://github.com/chromiecraft/chromiecraft/issues/4918

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

When you cast [Purge](https://www.wowhead.com/wotlk/spell=8012/purge), [Tranquilizing Shot](https://www.wowhead.com/wotlk/spell=19801/tranquilizing-shot), or [Dispel Magic](https://www.wowhead.com/wotlk/spell=988/dispel-magic) on a player that has a beneficial spell with charges (like [Nature's Grasp](https://www.wowhead.com/wotlk/spell=53312/natures-grasp), [Water Shield](https://www.wowhead.com/wotlk/spell=33736/water-shield), [Lightning Shield](https://www.wowhead.com/wotlk/spell=25469/lightning-shield), all charges were dispelled.

If you try to cast the same offensive spells on a shaman that has [Earth Shield](https://www.wowhead.com/wotlk/spell=32594/earth-shield), it removes only 2 charges (or 1 based on the rank's spell)

### Expected Blizzlike Behaviour

I don't know what the correct behavior is, but I imagine that the current one is incorrect because it doesn't follow a precise rule

### Source

I didn't find any source of the correct behavior, and right now I can't try to reproduce it on the PTR (but I guess it must be easy)

### Steps to reproduce the problem

Make a druid
Duel someone with an offensive dispel (priest, shaman, hunter)
Cast natures grasp
all 3 charges get purged

### AC rev. hash/commit

6cd3b2a32cd9

### Operating system

Ubuntu 20.04 - Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by laasker** [comment]
I belive its normal

Earth Shield have this spell attribute:
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/79991768/db3bbe64-f700-4534-bbf8-6783ffbbcf79)


While Nature's Grasp, Water Shield doesn't have it

**Comment by Pyromanihack** [comment]
Where do you take this source? It's an helpful tool to know 😁

**Comment by laasker** [comment]
it's the Spell-Editor tool https://github.com/stoneharry/WoW-Spell-Editor

You can also check on wotlk wowhead: (tho wotlk classic is a different client from the one we use"
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/79991768/4e748d6e-9a8b-448b-93ff-d7233826ac22)

**Comment by Pyromanihack** [comment]
Ok so clearly this is not a bug, I'm closing this

**Comment by avarishd** [comment]
Additional source https://youtu.be/R25q7IPDEDg?t=962 Priest dispels all stacks (can see GCD on nameplates) & PW:S
