### ISSUE TITLE
(Instance/Karazhan): Barnes text prior to killing Moroes is incorrect.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17149]
### Current Behaviour

Currently, if you haven't killed [Moroes](https://wowgaming.altervista.org/aowow/?npc=15687) yet, [Barnes](https://wowgaming.altervista.org/aowow/?npc=16812) will complain about how busy he is.

### Expected Blizzlike Behaviour

He should instead point out that Moroes forbade him from running any shows and that something must be done with him if he is to allow a performance.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.tele kara`
2. Make your way to Barnes without killing Moroes.
3. Interact with Barnes.
4. Observe his text.

### Extra Notes

Broadcast text ID: `14050`

### AC rev. hash/commit

6cd3b2a32cd97ed6824e8a20891b74e97fe34286

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
[This](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/6ea42a18-cf4a-4df2-9eef-0f811fbfc43c) is what the stage manager should say.

**Comment by elthehablo** [comment]
So this is the gossip before Moroes is dead? Okie :)
