### ISSUE TITLE
[server]world server carsh

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#17150]
### Current Behaviour

crash log:

https://gist.github.com/mpfans/c82dd789183887a9ab4c097903995047

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6cd3b2a32cd97ed6824e8a20891b74e97fe34286

### Operating system

Ubuntu20.04

**Comment by mpfans** [comment]
Just now, the same reason crashed again

**Comment by Winfidonarleyan** [comment]
```
Aentry = 0x0
```
