### ISSUE TITLE
(Instance/Karazhan): Chess Event can be skipped.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17168]
### Current Behaviour

The Gamesman's Hall Exit Door is unlocked.

### Expected Blizzlike Behaviour

It should not be unlocked until after the Chess match has been played and won.

### Source

Wrath Classic, assumption

### Steps to reproduce the problem

1. `.tele kara`
2. Make your way to the Chess event.
3. Open the door on the other side.

### AC rev. hash/commit

6ff5f3811eba62bade219dfa00e96a2eff86c7df

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
Correction from TBCC sniff: the door should not be interactable, only opening once the game is concluded.

**Comment by Gultask** [comment]
```sql
UPDATE `gameobject_template_addon` SET `faction` = 1375, `flags` = 32 WHERE (`entry` = 184277);
```
