### ISSUE TITLE
[Hunter] Marked for Death talent affects Stings and Volley too

### ISSUE THREAD

**Issue by Salehyn** [azerothcore/azerothcore-wotlk#17169]
Originally reported on CC: https://github.com/chromiecraft/chromiecraft/issues/6076
Reported by: [balleny ](https://github.com/balleny)

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

[Marked for Death](https://wowgaming.altervista.org/aowow/?spell=53246) talent increases damage done by [Serpent Sting](https://wowgaming.altervista.org/aowow/?spell=13554) and [Volley](https://wowgaming.altervista.org/aowow/?spell=58434) in addition to shots and pet special attacks.

### Expected Blizzlike Behaviour

It should affect only "shots" like Chimera Shot, Aimed Shot, Arcane Shot, Multi-Shot, Explosive Shot, Silencing Shot, Steady Shot among hunter abilities, and pet special attacks.

### Source

1. Wotlk classic:
https://imgur.com/a/BgvGp2v
((3943 + 650) * 0,2 + 1210) * 1,3 * 1,02 / 5 = 565

2. DrDamage

3. https://web.archive.org/web/20100807223434/http://elitistjerks.com/f74/t30710-wotlk_dps_spreadsheet/p5/
Marked for Death no longer increases Sting damage

4. https://www.youtube.com/watch?v=n9Jma4Q0vz8
At 1:21 you can see 4321 RAP. You can also see that there is no metagem on crit damage, so the standard crit damage without metagem is 2.3 for ranged attacks with the talent
https://wotlk.cavernoftime.com/spell=53338 + https://wotlk.cavernoftime.com/spell=19422
at 0:07 Serpent sting crits 1339
((4321 + 600) * 0,2 + 1210) * 1,3 * 1,02 * 2,3 / 5 = 1338.3 = 1339
at 0:08, the hunt gives Chimera Shot and refreshes the Serpent Sting already under the buff https://wowroad.info/?spell=64495, deals 600 damage, at this moment his RAP is 4673 (at 1:27 you can see how many RAP under this buff )
((4673 + 600) * 0,2 + 1210) * 1,3 * 1,02 / 5 = 600.5 = 600

5. https://www.warmane.com/bugtracker/report/115336

### Steps to reproduce the problem

compare sting damage with and without the talent on a marked target - should be equal

Create a hunter
.learn 13554 (serpent sting)
.learn 58434 (volley)
.learn 1130 (hunters mark rank1)
.go c 202964 (orgrimmar training dummy)

Test1: lvl 70 dummy, serpent sting, no mark, no talent (standard dmg)
Test2: lvl 70 dummy, serpent sting, mark, no talent (gonna be +1 dmg per tick with rank1 mark)
Test3: lvl 70 dummy, serpent sting, no mark, talent (standard dmg)
Test4: lvl 70 dummy, serpent sting, mark, talent (gonna be +1 dmg from rank1 mark + 5% dmg from talent)

Rinse repeat the same but swap 'serpent sting' for 'volley'

### Extra Notes

Combat log with and without talent on Chromie PTR

![WoWScrnShot_082723_092817](https://github.com/chromiecraft/chromiecraft/assets/12682004/08397bfc-3d6c-48ec-bab0-f73b6822800e)
![WoWScrnShot_082723_092750](https://github.com/chromiecraft/chromiecraft/assets/12682004/55cd8829-8b30-4698-af6d-7f407ebacc40)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4c287e2873c3464a64baafc8c93a47521bccfbc9

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Due to this:
https://github.com/azerothcore/azerothcore-wotlk/blame/f9b0eea0fd088dcc39b1e812201ff9aa812d6bd3/src/server/game/Spells/SpellInfoCorrections.cpp#L416-L420C8

0x00002000 Volley
0x00004000 Serpent Sting
