### ISSUE TITLE
Viscidus not die, it stand at 1 hp (NPC)

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#17179]
### Current Behaviour

If you wanna kill this boss you cannot because the boss stand at 1 hp

### Expected Blizzlike Behaviour

I think it must be killable xD

### Steps to reproduce the problem

1.Go An quiraj
2.Go to Viscidus
3.Try kill him

### AC rev. hash/commit

AzerothCore rev. 30197f40d687 2023-07-19 05:57:13 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon) ready...

### Operating system

x64

**Comment by Tereneckla** [comment]
To kill viscidius you to need to freeze him with frost attacks and then do enough physical attacks while he's frozen to shatter

**Comment by therelus** [comment]
Ohhh sorry i didn´t knew it >< thanks
