### ISSUE TITLE
Ground Scorpok Assaway not working correctly (ITEM)

### ISSUE THREAD

**Issue by therelus** [azerothcore/azerothcore-wotlk#17177]
### Current Behaviour

This item put you a Buff when you use it, but it not goes, if you click for use it you will be waiting for nothing

### Expected Blizzlike Behaviour

Must put you the Buff

### Steps to reproduce the problem

1. get the item
2. Use it
3. you will see it not work correctly

### AC rev. hash/commit

AzerothCore rev. 30197f40d687 2023-07-19 05:57:13 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon) ready...

### Operating system

x64

**Comment by Kitzunu** [comment]
This works on 9ac71a4e2a8c9252eed683a111922fc67890837d
