### ISSUE TITLE
AuthServer startup error

### ISSUE THREAD

**Issue by NUAAMETEOR** [azerothcore/azerothcore-wotlk#17189]
### Current Behaviour

 Using configuration file       /opt/wow/etc/authserver.conf
> Using SSL version:             OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
> Using Boost version:           1.74.0

Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 8.0.34
MySQL server ver: 8.1.0
Connected to MySQL database at 127.0.0.1
MySQL client library: 8.0.34
MySQL server ver: 8.1.0
Connected to MySQL database at 127.0.0.1
DatabasePool 'acore_auth' opened successfully. 2 total connections running.

Wrong format occurred (filesystem error: cannot make absolute path: Invalid argument []) at '/opt/software/azerothcore/src/server/database/Updater/DBUpdater.cpp:54'
Could not populate the Login database, see log for details.
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.

### Expected Blizzlike Behaviour

authserver startup normally

### Steps to reproduce the problem

tell me

### AC rev. hash/commit

auth.log

    /opt/wow/bin  cat Auth.log                                                                                                                    1 ↵  12:58:16    0.39    2.44G 
AzerothCore rev. 6ff5f3811eba 2023-09-02 18:51:28 -0300 (master branch) (Unix, RelWithDebInfo, Static) (authserver)
<Ctrl-C> to stop.

   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
                                 ██████╗ ██████╗ ██████╗ ███████╗
                                ██╔════╝██╔═══██╗██╔══██╗██╔════╝
                                ██║     ██║   ██║██████╔╝█████╗
                                ██║     ██║   ██║██╔══██╗██╔══╝
                                ╚██████╗╚██████╔╝██║  ██║███████╗
                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

     AzerothCore 3.3.5a  -  www.azerothcore.org

> Using configuration file       /opt/wow/etc/authserver.conf
> Using SSL version:             OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
> Using Boost version:           1.74.0

Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 8.0.34
MySQL server ver: 8.1.0
Connected to MySQL database at 127.0.0.1
MySQL client library: 8.0.34
MySQL server ver: 8.1.0
Connected to MySQL database at 127.0.0.1
DatabasePool 'acore_auth' opened successfully. 2 total connections running.

Wrong format occurred (filesystem error: cannot make absolute path: Invalid argument []) at '/opt/software/azerothcore/src/server/database/Updater/DBUpdater.cpp:54'
Could not populate the Login database, see log for details.
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.

### Operating system

RaspberryPi 4B+Ubuntu22.04

**Comment by Kitzunu** [comment]
Somewhere in config you have specified a path with `[]`

**Comment by aholeye** [comment]
I got the same error.

**Comment by aholeye** [comment]
<img width="897" alt="image" src="https://github.com/azerothcore/azerothcore-wotlk/assets/26758630/d2db89a9-6799-4c12-ac1a-ef719d5107bb">
Install mysql-client on you server, this mistake will disapper.

**Comment by apaxyx** [comment]
> <img alt="image" width="897" src="https://user-images.githubusercontent.com/26758630/268488612-d2db89a9-6799-4c12-ac1a-ef719d5107bb.png"> Install mysql-client on you server, this mistake will disappear.

It works! Thank you!
