### ISSUE TITLE
Dalaran NPCs address themselves when speaking

### ISSUE THREAD

**Issue by kel8458** [azerothcore/azerothcore-wotlk#1718]
##### SMALL DESCRIPTION:
Dalaran NPCs address themselves when speaking, instead of the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They should use the player's name instead of their own.

##### CURRENT BEHAVIOUR:
![image](https://user-images.githubusercontent.com/25411980/56004639-cb681780-5d0f-11e9-9e7a-bcc83d711254.png)
A list of the NPCs I've seen doing this:
- Disidra Stormglory `32718` (Wanders around Dalaran and the Commerce Exchange)
- Moon Priestess Nici `32714` (Commerce Exchange)
- Violetta `32720` (Near the South Bank)

##### STEPS TO REPRODUCE THE PROBLEM:
Wander around Dalaran near these NPCs to trigger their speech.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
b4a89be

##### OPERATING SYSTEM:
Debian 9

##### MODULES:
- AHBot
- New player perks
- Individual XP

##### OTHER CUSTOMIZATIONS:
No other modifications

**Comment by Pondaveia** [comment]
There must be an issue with their SAI when targeting the action invoker

**Comment by talamortis** [comment]
nothing wrong with 3rd person speaking. talamortis does it all the time 😆

**Comment by Bogir** [comment]
For me, it works every time without errors
![изображение](https://user-images.githubusercontent.com/25766571/56282432-97825d00-6128-11e9-8bc8-b83d6b870e83.png)

**Comment by poszer** [comment]
confirmed
![Screenshot_1](https://user-images.githubusercontent.com/41213210/56283052-ee7c3800-6110-11e9-9920-8b26dbcd2ec0.png)
