### ISSUE TITLE
[Bug] Bag swap with items makes items to disappear

### ISSUE THREAD

**Issue by shaszun** [azerothcore/azerothcore-wotlk#17199]
### Current Behaviour

Sometimes when you swap bags with items in them. In my case 14 slot to 16 slot. It made 2 items to disappear, relog didn't help and I had to switch the bags around again to get them back.

### Expected Blizzlike Behaviour

The items not to dissapear.

### Steps to reproduce the problem

1. Get 2 bags
2. Put some items in the equiped one
3. Switch them around

### AC rev. hash/commit

76d1d02dce2f

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
CC: @Kitzunu

**Comment by heyitsbench** [comment]
Would you be able to try to find the item(s) in `acore_characters.item_instance`? If so, are they anywhere in `acore_characters.character_inventory`?

**Comment by shaszun** [comment]
I tried to reproduce it while recording, but it didn't happen after 15 mins of bag switching and moving items around in the bags.

**Comment by Kitzunu** [comment]
I cant reproduce it.
