### ISSUE TITLE
(Instance/Magethridon'sLair): Magtheridon despawns as soon as the last Channeler dies.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17197]
### Current Behaviour

Currently in Magtheridon's Lair, if you kill all of the Hellfire Channelers, Magtheridon will despawn and the channelers will respawn immediately. The despawn happens right as the boss is supposed to become targetable by raid members.

### Expected Blizzlike Behaviour

The boss should become targetable by raid members and not despawn when the channelers are killed.

### Source

Assumption.

### Steps to reproduce the problem

1. `.tele magtheridon`
2. Kill all the trash. (Optional)
3. Engage in combat with the channelers.
4. Kill the channelers.
5. Observe Magtheridon's "exit game" strategy.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/6117.

Likely caused by 056b28ea21609ecf3ef31736d9231d6301653c51, dd647da913ef99ab3a0a86ac8f1ab2adb3acc621, or the combination of the two.

### AC rev. hash/commit

4147418a7ad7ef6d56cc6bfbad390933d2c646e2

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
Tested, caused by 056b28ea21609ecf3ef31736d9231d6301653c51.

**Comment by elthehablo** [comment]
Yup sorry not mentioned in the PR I just made. Was urgent fix. Will add now
