### ISSUE TITLE
[Druid] Wrong spirit coefficient used to calculate health regen ticks every 2seconds

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#17195]
Original report on CC: https://github.com/chromiecraft/chromiecraft/issues/6057
Reported by: [Apathyxia ](https://github.com/Apathyxia)

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour
Druids receive about 12-13% of their spirit as health regen to every tick / 2seconds (24 per tick with base 135 spirit at 70)

### Expected Blizzlike Behaviour

Here is some regeneration calculations based on spirit: https://wowwiki-archive.fandom.com/wiki/Health_regeneration

Using calculations from above link:
Level 70 druid with 135 spirit should have 135* 0.09 + 6.5 health per tick = 18.65 health per tick

This formula was confirmed on Wotlk classic by Kerrik https://www.youtube.com/watch?v=QMR0voa2G9o

Further calculations with higher values (421 spirit at lvl 80) show that the precise number is around 9,2% for the coefficient. (45-46 per tick)

### Source

https://wowwiki-archive.fandom.com/wiki/Health_regeneration

https://www.youtube.com/watch?v=QMR0voa2G9o
https://www.youtube.com/watch?v=vi0xzE7_kWU (geared test with 241 spirit)
https://www.youtube.com/watch?v=6Q4zhcsb-No (test at lvl 80 with 421 spirit)

### Steps to reproduce the problem

1. Make a druid .char level 70
2. Take some damage
3. Observe health regeneration every 2 seconds

### Extra Notes

Spirit coefficients are class-based. This report is only valid for druids, but there are likely mismatches in numbers for other classes too.
Spirit tooltips are broken. They say per second when they really mean per tick (every 2second). This is a blizzlike bug.
Spirit coefficients are supposed to be the same at every level. These tests were done at lvl 70 and 80 but there could be deviations at lower level brackets.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ovahlord** [comment]
The formula you have listed is wrong. The health regeneration ratio per spirit point is defined in the  gtRegenHPperSpt.dbc which at level 70 is 0.0625

So 135 spirit * 0.0625 = 8.4375 hp per second.

You can read up the ratio here:
https://wow.tools/dbc/?dbc=gtregenhpperspt&build=3.3.5.12340

the index within this table is determined by the following formula:   (unit_class - 1) * 100 + level -1.
Consequently a druid at level 70 has its ratio at row 1069.

**Comment by Salehyn** [comment]
> The formula you have listed is wrong. The health regeneration ratio per spirit point is defined in the gtRegenHPperSpt.dbc which at level 70 is 0.0625
> 
> So 135 spirit * 0.0625 = 8.4375 hp per second.
> 
> You can read up the ratio here: https://wow.tools/dbc/?dbc=gtregenhpperspt&build=3.3.5.12340
> 
> the index within this table is determined by the following formula: (unit_class - 1) * 100 + level -1. Consequently a druid at level 70 has its ratio at row 1069.


Those numbers simply don't match the data we collected from wotlk classic. The wiki formula does. There is of course a small margin of error (as to whether the coefficient is 9 or 9.2) but it's certainly not 6.25.
On top of that, the healing is calculated per-tick , not per second. Ticks happen every 2 seconds.

**Comment by Ovahlord** [comment]
There are more pieces which increase the health regen based on spirit. I've just gone over the code and (oh surprise), azerothcore is missing the whole gametable part entirely. There you have the root of your problem.

See Player::RegenerateHealth

Here's the correct implementation that needs to be ported over.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Player/Player.cpp#L5425

**Comment by Salehyn** [comment]
If the Devs choose to ignore the current retail numbers and leave it as-is to stick to some perceived correctness of what may or may not have existed thirteen thirteen years ago, that is their choice. 

As far as evidence goes, the above is the currently known 3.3.5a behavior. I doubt the 13 year old wiki would have the same formula if it was senseless.
