### ISSUE TITLE
Karazhan Boss Moroes Script Bug

### ISSUE THREAD

**Issue by mayaren888** [azerothcore/azerothcore-wotlk#172]
**Description**:
Script doesn't work properly
http://www.wowhead.com/npc=15687/moroes
**Current behaviour**: Tell us what happens
Boss skill  bug
**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Moroes disappear, releases the lock throat skills will appear again to the players.But, in the process of actual operation, this is not.
2. Coming of mo rose without any action, with players, into a stake.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
WIN7/X64
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

![20161009102312](https://cloud.githubusercontent.com/assets/6006653/19217343/f5d8013c-8e0a-11e6-8b0b-72ad6a1f7108.png)
##

**Comment by talamortis** [comment]
can confirm

**Comment by mayaren888** [comment]
vanish after There is no spell

`                    case EVENT_SPELL_VANISH:
                        events.DelayEvents(9000);
                        events.SetPhase(1);
                        me->CastSpell(me, SPELL_VANISH, false);
                        events.ScheduleEvent(EVENT_SPELL_VANISH, 30000);
                        events.ScheduleEvent(EVENT_SPELL_GARROTE, urand(5000, 7000));
                        return;
                    case EVENT_SPELL_GARROTE:
                        me->CastSpell(me, SPELL_VANISH_TELEPORT, false);
                        break;
                }

                // Xinef: not in vanish 
                if (events.GetPhaseMask() == 0)
                    DoMeleeAttackIfReady();
            }
`

Tc.code
`if (InVanish)
            {
                if (Wait_Timer <= diff)
                {
                    Talk(SAY_SPECIAL);

                    if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                        target->CastSpell(target, SPELL_GARROTE, true);

                    InVanish = false;
                } else Wait_Timer -= diff;
            }

            if (!InVanish)
                DoMeleeAttackIfReady();`

**Comment by ShinDarth** [comment]
@mayaren888  can you [open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) ?

@talamortis  please include your commit hash when you confirm issues, thanks

**Comment by talamortis** [comment]
Will do, and looking into fix :)

**Comment by talamortis** [comment]
Fixed. will do PR later

**Comment by ShinDarth** [comment]
There is an open PR by @talamortis https://github.com/azerothcore/azerothcore-wotlk/pull/179

it would be nice if someone can test it and give feedback, instructions here:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request
