### ISSUE TITLE
Adamantite Shell Machine has a 1.5 second GCD

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#17201]
Original issue: https://github.com/chromiecraft/chromiecraft/issues/5149

### What client do you play on?

enGB - enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

Currently, Adamantite Shell Maker boxes when used, (5 charges of 200 shells) cost a GCD. Adamantite Arrow Maker boxes work correctly and you can spam 200 arrows out of the 5 charge box with no GCD.

### Expected Blizzlike Behaviour

Both boxes should be spam click-able to receive the ammunition with no GCD.

### Source

From wowhead (GCD set to zero)
Spell ID 45171
![shell](https://github.com/azerothcore/azerothcore-wotlk/assets/82369562/4350630f-eb7b-4453-8dfb-eb60124f8c5e)

### Steps to reproduce the problem

1. `.additem 34504` Adamantite Shell Machine
2. `.additem 20475` Adamantite Arrow Maker 
3. Notice one takes a gcd and the other does not.

### AC rev. hash/commit

dd647da913ef

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
The spell has no GCD in DBC data, so that is correct. It is the item that has the cooldown so this proof is useless

**Comment by Kitzunu** [comment]
resolved in the PR as not correct
