### ISSUE TITLE
[Druid] Innervate threat generation

### ISSUE THREAD

**Issue by Salehyn** [azerothcore/azerothcore-wotlk#17218]
CC report: https://github.com/chromiecraft/chromiecraft/issues/6124

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Currently [Innervate ](https://www.wowhead.com/wotlk/spell=29166/innervate) uses the Power Gain (Rage) threat modifier of 5 points of threat per mana gained.
This is 10 times higher than the intended 0.5 threat for each point of mana that is the normal modifier for all Mana type of power gains.
A lvl 70 druid's innervate currently generates 5330 mana and 27k threat. It will easily pull aggro off any tank if cast early into the fight.

### Expected Blizzlike Behaviour

Power gains of mana generate 0.5 threat per mana gained. Always have, always will. This is working as intended for most mana gains, such as mana potions. Only innervate is screwed up because somebody misread a number in a druid spreadsheet.

### Source

https://www.wowhead.com/classic/guide/threat-overview-classic-wow
"Mana generates threat at a 1-to-0.5 ratio (100 mana gained = 50 threat generated), Rage generates threat at a 5-to-1 ratio (50 rage = 250 threat), and Energy generates threat at a 5-to-1 ratio as well. The threat generated by these resources is distributed equally to all of the mobs that are actively engaged by the party/raid. In addition, these threat values are static and cannot be altered by threat modifiers (talents, abilities, etc)."
https://wowwiki-archive.fandom.com/wiki/Threat
"Power Gain (Mana) | Base threat is 0.5x Mana gained (only certain effects)"

### Steps to reproduce the problem

Create a druid .char level 70
Burn your mana with healing touch until below 10%.
Engage a mob, cast [innervate](https://www.wowhead.com/wotlk/spell=29166/innervate), watch threat meter > each tick of 533 mana gained generates like 2.6k threat.

### Extra Notes

I see this came up a couple times both on AC and even sunwell github and everybody always shuts it down with "its working as intended".
Gotta say the people who have the audacity to say mana should give 5x threat have never played the actual game. They keep linking some threads about bears with their power gains at 5-1 ratio but that is for rage, not mana.
Sigh.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
Tested and confirmed on WOTLK classic as well:
https://www.youtube.com/watch?v=XOvSIL7y0fI
(courtesy of Kerrik)

**Comment by avarishd** [comment]
```sql
DELETE FROM `spell_threat` WHERE `entry`=29166;
```
This returns it to normal threat generation.
