### ISSUE TITLE
(Instance/HyjalSummit): Jaina/Thrall/Tyrande have incorrect text prior to scourge wave encounter.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17214]
### Current Behaviour

Currently, [Jaina Proudmoore](https://wowgaming.altervista.org/aowow/?npc=17772), [Thrall](https://wowgaming.altervista.org/aowow/?npc=17852), and [Tyrande Whisperwind](https://wowgaming.altervista.org/aowow/?npc=17948) all have a generic "what are you doing here" text.

### Expected Blizzlike Behaviour

They should have unique text telling you to either go help Jaina Proudmoore or help fend off the legion.

[Jaina](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/d2e846ec-0ced-4bfa-a074-2c7b9312df06), [Thrall](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/a51690af-426c-4a5f-964c-804a8440b5ec), [Tyrande](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/000a0755-0b02-4350-80a1-c72142b9d8fb)

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.tele cavernsoftime`
2. Run to and inside the Hyjal instance portal.
3. Walk into the Alliance encampment portal.
4. Make your way to Jaina/the Horde/Night Elf camps.
5. Interact with the leaders.
6. Observe their text.

### AC rev. hash/commit

76d1d02dce2f63348dccb8ac218ec0cc54e6ce8c

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Gultask** [comment]
Did you know there's also hidden menus that can't be seen because they lose npcflags and automatically close the gossip menu? 💀 
https://github.com/azerothcore/azerothcore-wotlk/pull/18460/files#diff-8f172ca5e360207bd2a2778bc4e26b15a1a2822a1bb0b57cf14d594ed7a0dcb6R605-R611
