### ISSUE TITLE
[Warlock] Drain Soul uses binary resistance mechanic instead of nonbinary

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#17235]
Original report on CC: https://github.com/chromiecraft/chromiecraft/issues/4815
Reported by: [immersionnn](https://github.com/immersionnn)

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Drain soul(https://wowgaming.altervista.org/aowow/?spell=11675) is getting fully resisted on the initial cast against targets with shadow resistance.

### Expected Blizzlike Behaviour

It should receive partial resists on each tick against targets with shadow resistance just like any other DOT (i.e. corruption, curse of agony)

### Source
Any log from classic https://classic.warcraftlogs.com/reports/ANtXrg6aQwpc897h#fight=8&type=damage-done&source=24 shows the spell should run on nonbinary (partial) resist mechanic.

### Steps to reproduce the problem

.char level 70 .learn 11675
Attack any target lvl 71 to 73. (or a player with shadow resistance aura/buff)
Spam drain soul until you get a full resist. Observe the ticks in combat log are not being part-resisted.

ps: when drain soul gets fully resisted it won't say it in the combat log like it does for curse of elements so you'll hate to enable your combat text target damage or get an addon like msbt(MiksScrollingBattleText)

### Extra Notes

Original report was for both Drain Soul and Curse of the Elements, however the latter is intended to run on binary resistance and as such works as intended. Only Drain soul requires fixing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/592a26cb8c46a9db92a70c275f1d8625f8949c1d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
Drain Soul is getting the custom binary resist attribute added with [this line](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellMgr.cpp#L3074). One of the spell's effects is probably getting stopped by the if statement on L3059, but the other two don't. Tempfix for this might be to remove the attribute in SpellInfoCorrections, at least until more research can be done to figure out what's going wrong with this spell (without breaking others).
