### ISSUE TITLE
Table "spell" or "spell_template" missing from database!

### ISSUE THREAD

**Issue by SouthMemory** [azerothcore/azerothcore-wotlk#17239]
### Current Behaviour

Table "spell" or "spell_template" missing from database acore_world
There's only a table called "spell.dbc", but only a few records is in it .
I can not find where spell id=23881 is.

### Expected Blizzlike Behaviour

there is a table called  "spell" or "spell_template"  in database acore_world.

### Steps to reproduce the problem

just open database and check

### AC rev. hash/commit

nothing

### Operating system

macos 12

**Comment by Kitzunu** [comment]
There is no table with such name
