### ISSUE TITLE
Feature: Adjust Kologarn fight - Right arm should not target Main Tank/Current threat target with Squeeze

### ISSUE THREAD

**Issue by jdmccathie** [azerothcore/azerothcore-wotlk#17245]
### Describe your feature request or suggestion in detail

I play on a server running Autobalance, which allows some raids to be completed solo. Ulduar has a hard barrier on solo completion due to Kologarn targetting any target at random (including the main tank) with Squeeze, creating an unmitigatable amount of damage leading to a wipe.

### Describe a possible solution to your feature or suggestion in detail

Prevent Kologarn's Right Arm from targetting the Main Tank/Current threat target with Squeeze

### Additional context

Thig should hypothetically not impact standard raid sizes in this fight, as the Squeeze ability will still be able to target all other raid members.

**Comment by heyitsbench** [comment]
Query: does this squeeze happen on retail if soloing Kologarn?

**Comment by heyitsbench** [comment]
Answering my own question here: [`Kologarn will not grip you if you are first on agro list AND if you are in melee range.`](https://www.wowhead.com/npc=32930#comments:id=1820757)

**Comment by heyitsbench** [comment]
According to [this engadget article](https://www.engadget.com/2009-03-11-ulduar-on-the-3-1-ptr-kologarn.html), this avoiding the torso tank mechanic has always been a thing. This may be a bug rather than a QoL suggestion.

**Comment by jdmccathie** [comment]
Thanks, ill redraft as a Bug
