### ISSUE TITLE
[Magtheridon] Debris targets player even after moving out of effect

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#17243]
https://github.com/chromiecraft/chromiecraft/issues/6051
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Magtheridon's Debris ability ([30631](https://wowgaming.altervista.org/aowow/?spell=30631)) that he casts frequently in Phase 3 (<30% hp) is causing damage at incorrect location, resulting in players dying while being far away from the visual cave-in effect [30632](https://wowgaming.altervista.org/aowow/?spell=30632).

According to my PTR testing, the Debris behaves in two different ways depending on whether it spawns on a player or not.

1. IF the Debris visual (30632) spawns on top of a player, the damage ability (30631) will target that player (after 5 seconds) regardless of how far the player runs away from the cave-in.
2. IF the Debris visual (30632) spawns anywhere else (i.e., not on top of any player), the damage ability (30631) will land _somewhere_ in the proximity of the visual effect - sometimes at least partially overlapping with the visual effect but other times not.

I am attaching some screenshots from my PTR testing that show both of those cases (floating combat text is enabled to determine if Debris hit me or not).

### Case 1
![WoWScrnShot_081623_222938](https://github.com/chromiecraft/chromiecraft/assets/120322864/c9454734-bf19-4f2f-a2a6-84572c421dfb)
![WoWScrnShot_081623_222638](https://github.com/chromiecraft/chromiecraft/assets/120322864/6b3e888f-7c6b-4e17-9dac-2e3e6ff7623c)

In both instances, the Debris visual originally appeard on top of me and even though I ran far away from the visual effect (seen to the right or left of my character), the damaging ability (that meteor visual) targeted me and landed on my character anyway.

### Case 2
![WoWScrnShot_081623_222859](https://github.com/chromiecraft/chromiecraft/assets/120322864/e1a07343-0492-4a2e-8bb8-e0b575d7f306)
![WoWScrnShot_081623_222803](https://github.com/chromiecraft/chromiecraft/assets/120322864/0cc82f8e-e6ae-485a-baff-b455b0c07934)
![WoWScrnShot_081623_222918](https://github.com/chromiecraft/chromiecraft/assets/120322864/63e4ede5-6f50-4d83-95e7-1abc923d5cee)
![WoWScrnShot_081623_222818](https://github.com/chromiecraft/chromiecraft/assets/120322864/495a1ca5-1945-4fd7-be4a-f6d93f77490d)

In all the screenshots, the Debris visual did not originally appear on top of me but rather at a random location. As the screenshots show, the damaging ability then (after 5 seconds) lands somewhere near the center of the visual effect. In the first two screenshots, it clearly lands far enough to not hit me even though I am standing right where the visual effect was, while the last two screenshots show that in some cases, the damaging ability will at least partially overlap with the visual effect.

### Expected Blizzlike Behaviour

The Debris damaging ability (30631) should always land precisely in the center of the visual effect (30632) location. Debris should be a simple "void zone" type mechanic, meaning: you stand in it = you die; you run away = you live. The Debris damage component should not "follow" affected players or land "somewhere near" the visual effect.

### Source

Timestamped _Dungeon Dives_ strategy video for TBC Classic:
https://youtu.be/NBP7T9QMad0?t=296

Strategy post on WoWhead: https://www.wowhead.com/wotlk/npc=17257/magtheridon#comments:id=2822532
> Cave In, will occur periodically. The Cave In deals 90,000-113,000 damage to anyone standing in the Cave In. Each Cave In is preceded by a Cave In animation (approx. 3 seconds), which gives players enough time to move out of the Cave In (which will result in instant death).

Classic TBC - Magtheridon's Lair - Nova vs. Magtheridon
[8:53](https://youtu.be/rb_m6T6fk9w?t=533): Debris visual spawning near one of the fire patches and the damage ability landing exactly at the location of the visual effect (hard to see because of the fire tho).
[9:22](https://youtu.be/rb_m6T6fk9w?t=562): Debris visual spawning near the player, the damage ability landing precisely in the center of the visual effect a few seconds later.

World Of Warcraft: The Burning Crusade Classic - Magtheridon Boss Fight
[7:31](https://youtu.be/bjj8gaqdRgI?t=451): Debris visual spawning in a fire patch, the damage ability landing again precisely in the center of the visual effect.

A blast from the past (vanilla TBC): Unknown Potential - Magtheridon TBC kill
[8:59](https://youtu.be/FQEzzZfG0R0?t=539): Debris spawning once again in/near the fire patch and the damage ability landing precisely where the visual effect is.

### Steps to reproduce the problem

.teleport Magtheridon
4. Start the encounter, kill all the Channelers and get Mag below 30% (.damage 4000000)
5. Wait for Mag to spawn Debris visual. If it spawns on top of you (Case 1), run as far away as you can and watch the damage ability (meteor) still target you and land at your new position. If it spawns somewhere else in the room (Case 2), get close to its location and watch where the damage ability lands.

### Extra Notes

There is another report for Magtheridon's Debris ability (#5904), yet that report is about the buff/debuff status of the Debris visual effect (30632) and for that reason I would not consider this issue duplicate.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/86bfef8874883a1726966326368918567c5531cd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
Potentially relevant info from UndoUreche in original post
> I'm not a contributor to the project, but I was annoyed enough by this to check, and spotted two suspect bits: ![image](https://user-images.githubusercontent.com/50205200/263453604-4bab0279-cfbb-404f-b7a0-a155b27977cc.png) ![image](https://user-images.githubusercontent.com/50205200/263453591-5e3fd821-bdd0-49db-b53d-ac4ec300ab7c.png)
> 
> Again, I'm not familiar with the api the folks have put together here, but what I'm reading is that in the context of mag picking a target, he will cast the visual effect on a player, followed by him then scheduling a debris damage event on said player. The event will then (after 5 seconds, as per the schedule) deal the debris damage to the affected player directly.
> 
> This seems to be the issue, but I would appreciate if somebody could confirm my suspicion

**Comment by Nyeriah** [comment]
I wasn't the one who worked on this but if I am not mistaken in the sniff research the target casts the spell on itself
cc @Nefertumm
