### ISSUE TITLE
Phrases on Wintergrasp battle ruRU

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#1725]
Wrong phrases in Wintergrasp's announces and Dalaran's NPC-registrators.

LOCALIZATION = ruRU !!!

1. 
Wrong phrases when players damages, breaks towers or defends a fortress.

NPCs Wizard Bredin 32169 (Alliance) and Magister Surdiel 32170 (Horde) show the wrong owner of Wintergrasp in the text above the gossip menu (npc_text id 14775, broadcast_text id 35922 - owner is Horde, but sometimes the real owner of Wintergrasp Lake is Alliance). 

With the victory of the the Alliance announcement is also not true: broadcast_text id is 30960 "The Battle for Lake Wintergrasp is about to begin!" but it's over... If Horde has successfully defended Wintergrasp Fortress - announce is "The Alliance has defended Wintergrasp Fortress!" (broadcast_text id 31403)

2.
If you are taking part in the battle - you are joining to raid. You can write to raid chat, but you can't write to group chat. In this chat you can only read messages of players which was in your group when you are joined to battle's raid and can not answer to him while in raid. To answer them, you must leave battle, leave from raid, then answer (group with those players is staying), then you must back to Wintergrasp Lake, join to battle raid and continue to fight. 
And you can'not write to your's group of this raid. Only to raid chat.

##### STEPS TO REPRODUCE THE PROBLEM:
take part in the battle

1. damage or destroy South towers
2.  damage or destroy Fortress walls
3. Defend or take fortress
4. After battle speak with registrator for next battle in Dalaran - He may says wrong owner of Wintergrasp Fortress and wrong time to next battle.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
 135b4470ce85+ 2019-04-11 23:48:46 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
mod-gmsecurity-master

##### OTHER CUSTOMIZATIONS:
ruRU client
![изображение](https://user-images.githubusercontent.com/25766571/56285576-fa77f200-6130-11e9-9da8-38e0574aa074.png)

![изображение](https://user-images.githubusercontent.com/25766571/56285657-314e0800-6131-11e9-9625-00dfdf3ed0e9.png)

Flags near the towers blue/red:
![изображение](https://user-images.githubusercontent.com/25766571/56286069-33fd2d00-6132-11e9-844b-5196287df648.png)

Alliance defended fortress:
![изображение](https://user-images.githubusercontent.com/25766571/56286339-e59c5e00-6132-11e9-8e23-107943acfd4c.png)

**Comment by poszer** [comment]
@Winfidonarleyan , Can you try this please?

**Comment by Winfidonarleyan** [comment]
I'll try tomorrow

**Comment by Viste** [comment]
confirm old bug

**Comment by Naxxramas-Server** [comment]
Yep i can confirm too

**Comment by Winfidonarleyan** [comment]
Hm, I don't think I need to check anymore

**Comment by spinzaku** [comment]
Confirmed.
Also lots of the flags are mixed horde/alliance together.

**Comment by poszer** [comment]
> Confirmed.
> Also lots of the flags are mixed horde/alliance together.

The texts are fixed for this, it correctly shows now
