### ISSUE TITLE
Charge pathing not working underwater

### ISSUE THREAD

**Issue by ajgration** [azerothcore/azerothcore-wotlk#17268]
### Current Behaviour

Since "AC Data v16" released, I've noticed that charge/intercept etc. is no longer functioning correctly underwater. In v15 it worked well, but you could potentially charge through terrain and fall through the world. While that issue seems to be fixed, it now seems to be unable to find pathing to monsters which are swimming in water around 90% of the time. You can spam the charge ability and nothing will happen. Currently it seems random as to when it's going to work and you often need to do a full circle around the mob to find the right angle to allow you to use the skill.

### Expected Blizzlike Behaviour

As a warrior, you should be able to charge mobs in and around water, especially so if there is nothing in the way of your pathing.

### Source

https://youtu.be/UMGPhfuD7pU?t=743

Here you can see a warrior charging a mob that is underwater in BFD.  For comparison, I just ran a BFD and could only successfully use charge once or twice the whole instance.

### Steps to reproduce the problem

Step 1: Be warrior
Step 2: Go out into a body of water where mobs are underwater
Step 3: Try and use Charge on a couple of different mobs
Step 4: You will most likely be unable to use the spell

### AC rev. hash/commit

AzerothCore rev. cacb32f4232f

### Operating system

Windows 10

### Custom changes or Modules

mod-1v1-arena
mod-ah-bot
mod-autobalance
mod-challenge-modes
mod-gain-honor-guard
mod-individual-progression
mod-npc-buffer
mod-reagent-bank
mod-solo-lfg
mod-transmog

**Comment by AGandrup** [comment]
This PR: https://github.com/azerothcore/azerothcore-wotlk/pull/13705 seems to have caused this issue.
I tried to revert the changes and found that charge now works in water again. I have not tried to generate new mmaps to see if that fixes the issue.

**Comment by MikaMauger** [comment]
It seems there is a bug with the Unit::CanSwim method. Player is not considered as a unit which "can swim". I'll create a fix for this.

PS: mmaps do not need to be regenerated.

**Comment by ajgration** [comment]
Awesome! Thanks heaps :)
