### ISSUE TITLE
WorldServer received a SMART error

### ISSUE THREAD

**Issue by fangshun2004** [azerothcore/azerothcore-wotlk#17271]
### Current Behaviour

When a character enters Dalaran from another map, the worldserver console receives an 
```
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28994 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 29494, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 29523 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 35500, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28989 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 29493, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28721 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 28701, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28725 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 28703, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28726 SourceType 0 EventType 10 TargetType 7 using non-existent Text id 0 for talker 28699, ignored.
```
 error

### Expected Blizzlike Behaviour

You will not receive an error

### Steps to reproduce the problem

1. Restart WorldServer
2. .go xyz 5813.370117 453.403015 658.755615 571

### AC rev. hash/commit

AzerothCore rev. acc1303c9430

### Operating system

winsows 11

**Comment by Kitzunu** [comment]
can you run `SELECT * FROM creature_text WHERE creatureid = 28994` and post the output?

Because the text does exist.

**Comment by fangshun2004** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/1532a3b4-b928-43e7-a7a4-a4859d823b7b)

**Comment by fangshun2004** [comment]
My guess is that this may have something to do with the event_param6 key value added before the smart data table

**Comment by Kitzunu** [comment]
@Gultask what did you break 😠 <3

**Comment by fangshun2004** [comment]
event_param5 Was it 1 before? Players only

**Comment by Gultask** [comment]
> event_param5 Was it 1 before? Players only

good catch, but I don't know why I'd have changed that. I don't remember modifying OOC_LOS

**Comment by Gultask** [comment]
```sql
UPDATE `smart_scripts` SET `event_param5` = 1, `action_param3` = 1 WHERE `source_type` = 0 AND `entryorguid` IN (28994,29523,28989,28721,28725,28726);
```
