### ISSUE TITLE
(Instance/MagistersTerrace): Kalecgos' landing position is incorrect.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17280]
### Current Behaviour

[Kalecgos](https://wowgaming.altervista.org/aowow/?npc=24844) lands very close to the scrying orb.

### Expected Blizzlike Behaviour

He should land a bit further away from it.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.tele magistersterrace`
2. Enter the instance.
3. Clear your way up to the scrying orb.
4. Observe Kalecgos' landing position.

### AC rev. hash/commit

b84596fcaba2b805723e30d291c570c09c091f94

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Nyeriah** [comment]
No longer floats, closing as per https://github.com/azerothcore/azerothcore-wotlk/pull/17286
