### ISSUE TITLE
Karazhan The opera house Script Bug

### ISSUE THREAD

**Issue by mayaren888** [azerothcore/azerothcore-wotlk#173]
**Description**:
The scene can't trigger
http://www.wowhead.com/npc=16812/barnes
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Click on the NPC after didn't open the option.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
WIN7/X64
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

![20161009104152](https://cloud.githubusercontent.com/assets/6006653/19217420/38b10c7c-8e0d-11e6-9e15-11eec0fe32ea.png)
##

**Comment by Krath** [comment]
I think I have found the problem :
In Karazhan.cpp, at line 364, the script checks if Moroes has been defeated : if (instance->GetData(TYPE_MOROES) == DONE && instance->GetData(TYPE_OPERA) != DONE)

In boss_moroes.cpp, in the JustDied function, the TYPE_MOROES does not get set to DONE and therefore the event can not start. 
Also, there are some lines that are commented in instance_karazhan.cpp. The file has to be checked since most of instance data and objects are not working properly.

**Comment by talamortis** [comment]
instance->SetBossState(TYPE_MOROES, DONE) thats script what you put in just died function, but still is not working.

**Comment by ShinDarth** [comment]
can this be of any help? https://github.com/HellFire-wow/first/commits/master

**Comment by Krath** [comment]
It probably can. I'm gonna try it

**Comment by talamortis** [comment]
they have not fixed the opera problem, just looked at the commits, i think i found the problem
![untitled](https://cloud.githubusercontent.com/assets/6143065/19222734/2a3103f6-8e57-11e6-8574-74cde4fb2592.png)

**Comment by xnova214** [comment]
In my repo (https://github.com/HellFire-wow/first/commits/master) opera event and nightbane works fine. But please do not swear much, if you find any problems ... I'm still new to programming :)

**Comment by ShinDarth** [comment]
@xnova214 do not worry, this is an educative project and it's meant also for those who are just starting (I started with this stuff at 15 years old with almost 0 knowledge in programming stuff).

I suggest you to open a PR, so your code can be reviewed by others and can be improved, then merged with the official code base. Here the guide: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request

**Comment by mayaren888** [comment]
@xnova214 Thank you very much for the link, I need to test, and then tell everyone.

**Comment by talamortis** [comment]
managed to get all the doors working, just need to get the opera working correctly.

**Comment by talamortis** [comment]
sorry ives not updated this issue, i am getting close to solving the problem, once i do i will do a PR  👍

**Comment by ShinDarth** [comment]
there is a PR to solve this issue:

https://github.com/azerothcore/azerothcore-wotlk/pull/200

please can you guys test it and give your feedback? so it can be merged to master
