### ISSUE TITLE
cant install updates error 1060

### ISSUE THREAD

**Issue by Griptor** [azerothcore/azerothcore-wotlk#17317]
### Current Behaviour

Im getting errors even with a fresh new empty db.

Files
2023_09_10_01
2023_09_15_00
2023_09_15_01

### Expected Blizzlike Behaviour

Updating World database...
>> Applying update "2023_09_10_01.sql" '850D546'...
ERROR 1060 (42S21) at line 3 in file: 'source\data\sql\updates\db_world\2023_09_10_01.sql': Duplicate column name 'CreateObject'♪◙

### Steps to reproduce the problem

Cloned repo
I have not had issues like this in the past.

im using a portable mysql 5.7.40

### AC rev. hash/commit

its the npcbot from trickerer
aef631e354b226f01393752990e0789b0616e14b

however it is only the 3 update files that are causing probs.

### Operating system

win 11

### Custom changes or Modules

autobalance
dungeonrespawn
mod_accountbound
mod_achivements
mod_ahbot
mod_learnspells
randomenchants
skipdkmodule
solocraft
sololfg
transmog

**Comment by Kitzunu** [comment]
Go to the trickerer repo. We dont support this and it works on a clean install

**Comment by Griptor** [comment]
Ooh ok ty
