### ISSUE TITLE
(Instance/Karazhan): Shade of Aran teleport shortcut gossip does not appear.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17318]
### Current Behaviour

After killing the [Shade of Aran](https://wowgaming.altervista.org/aowow/?npc=16524), [Berthold](https://wowgaming.altervista.org/aowow/?npc=16153) does not offer to teleport players up to the Guardian's Library.

### Expected Blizzlike Behaviour

Upon Aran's defeat, Berthold should offer to teleport players up to the Guardian's Library.

### Source

Wrath Classic, [Wowpedia](https://wowpedia.fandom.com/wiki/Berthold?oldid=2254791), [Wowhead comment](https://www.wowhead.com/wotlk/npc=16153/berthold#comments:id=95708)

### Steps to reproduce the problem

1. `.tele kara`
2. Clear your way to Aran.
3. Kill him.
4. `.tele kara`
5. Interact with Berthold.
6. Observe no teleport gossip option.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/6175.

Couple things on the sniff side of things: he's supposed to cast [39566](https://wowgaming.altervista.org/aowow/?spell=39566) which then triggers the player to cast [39567](https://wowgaming.altervista.org/aowow/?spell=39567) on themself (which is the one it seems he's trying to cast on the gossip currently). Also, the target position is just slightly wrong. Here's the sniff:
```
(DstLocation) Location: X: -11165.2 Y: -1911.95 Z: 232.009
(Cast) (Target) Orientation: 2.143526077270507812
(Cast) (Target) MapID: 532
```

### AC rev. hash/commit

f633eb8592b83a9dc38871a969a9cf39607897e5

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
Conditions do exist for this guy's gossip option, but it seems maybe in all the overhauling that's happened recently, it got left behind.

**Comment by kerricsson** [comment]
still valid at AzerothCore rev. 152429867b81+ 2023-09-20 00:39:52 +0000 (master branch) (Unix, RelWithDebInfo, Static) . Fix will be very appreciated since there are a lot of wiped during progression phase and around 1h is going for run to the upper part of the tower.
