### ISSUE TITLE
(Instance/Ulduar): Opening Algalon's chamber does not save you to the instance.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17321]
### Current Behaviour

No interaction with [Algalon](https://wowgaming.altervista.org/aowow/?npc=32871), either opening his chamber, starting his fight, or defeating him, will save you to the Ulduar instance ID.

### Expected Blizzlike Behaviour

Opening the door to his chamber should save you to the instance ID.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.tele ulduar`
2. Enter the instance.
3. `.go xyz 1631.1 -166.2 427.3`
4. [`.additem 45796`](https://wowgaming.altervista.org/aowow/?item=45796)
5. Open the chamber.
6. Observe you are not saved.

### Extra Notes

For the record, in a normal 100% 3.3.5a environment, this issue will literally never come up, as you have to kill at a minimum Flame Leviathan and XT-002 to get to Algalon's chamber, both of which I imagine *do* lock the player correctly to the instance. However, with Wrath Classic adding a skip straight to the Antechamber, it is possible there to have Algalon be the first (and only) boss encounter. If someone wished to emulate that behavior, it isn't unreasonable to assume that Algalon should lock them to the instance. Other bosses in the Antechamber do lock players to the instance, such as Kologarn, so it's not like it currently only is the optional bosses up to and including the first mandatory boss that lock a player to the instance.

### AC rev. hash/commit

fcd58da08c0b50383ff9f5d6b40cfc2054ef8e0b

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Tony931023** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/15379

https://github.com/azerothcore/azerothcore-wotlk/issues/15382

**Comment by heyitsbench** [comment]
> 15379 15382

Those are both unrelated issues.

**Comment by heyitsbench** [comment]
This seems to have been resolved with https://github.com/azerothcore/azerothcore-wotlk/commit/69418ab93616cd04d2a91060c12e110d675b6941.
