### ISSUE TITLE
(Instance/MagistersTerrace): selin_fireheart

### ISSUE THREAD

**Issue by fangshun2004** [azerothcore/azerothcore-wotlk#17325]
### Current Behaviour

selin_fireheart When drawing energy from nearby crystals, any spell skill that attacks the crystal will be interrupted selin_fireheart absorb energy, stay in place, will not use melee attacks, and if it reaches 100% energy, it will shout "Yes!!" multiple times!! I am a god!”

### Expected Blizzlike Behaviour

selin_fireheart When drawing energy from nearby crystals, attacking crystals will not affect selin_fireheart energy sucking behavior, and only by destroying the crystal or selin_fireheart energy reaches 100% can the energy absorption stop behavior. And when the energy reaches 100%, only once will shout "Yes!!" I am a god!”

### Source

https://clipchamp.com/watch/0HLNa6XTa4g

### Steps to reproduce the problem

1. .go xyz 267.809906 6.161789 1.237262 585
2. Enter the battle
3. Wait for selin_fireheart to go to the crystal to absorb the energy 
4. Attack the Crystal and leave the boss melee range 

### AC rev. hash/commit

fb1d356af98d

### Operating system

win11

**Comment by Rorschach91** [comment]
Confirmed by a recent beta-testing.
