### ISSUE TITLE
Could not find text for creature

### ISSUE THREAD

**Issue by qq462518439** [azerothcore/azerothcore-wotlk#17360]
### Current Behaviour

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/91646500/650547ca-f042-447c-87f9-93407ccc9f15)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. Use the latest source code
2. Log in to the game then teleport to Dalaran
3.check the console messages in about 1 minute
(If the console doesn't send an error message, add any creature near npcID 28997and repeat the above steps)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e67a0b1a82a0173c6100921b1bcf91b8834c9308

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
@Gultask leftover from your pr?
