### ISSUE TITLE
[Quest] Seeds of the Blacksouled Keepers [Fix included]

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1737]
Quest name: Seeds of the Blacksouled Keepers
Quest ID: 11319

Issue: Quest Poi showing wrong positions on the map.

How to test:
.tele HowlingFjord
 .quest add 11319

Check Poi locations

```sql
DELETE FROM `quest_poi` WHERE `QuestID`=11319 AND `id`=0;
INSERT INTO `quest_poi` (`QuestID`, `id`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `VerifiedBuild`) VALUES (11319, 0, 0, 571, 491, 0, 0, 1, 0);
DELETE FROM `quest_poi` WHERE `QuestID`=11319 AND `id`=1;
INSERT INTO `quest_poi` (`QuestID`, `id`, `ObjectiveIndex`, `MapID`, `WorldMapAreaId`, `Floor`, `Priority`, `Flags`, `VerifiedBuild`) VALUES (11319, 1, -1, 571, 491, 0, 0, 1, 0);
```

Apply SQL, abandon quest, reload quest_poi, take quest again and check positions now.

**Comment by Pondaveia** [comment]
You can open a pr with this fix :smile:

**Comment by poszer** [comment]
Knindza sharing his fixes in this way. Do not close this issue if the PR is not created and referenced

**Comment by Knindzagxg** [comment]
I hate Git Pondaveia :D

**Comment by poszer** [comment]
Hmm, doesn't change nothing for me. Can you check again your fix @Knindzagxg :smiley:

**Comment by Pondaveia** [comment]
@poszer it was missclick, close and comment instead of comment 😴

**Comment by poszer** [comment]
Knindza anything abt this ? :rofl:

**Comment by Helias** [comment]
This seems already fixed now.

![image](https://user-images.githubusercontent.com/519778/87864018-f3a6e300-c962-11ea-8222-e11f7a9c4682.png)

I also tested it in-game, it already works.
