### ISSUE TITLE
PreloadAllNonInstancedMapGrids bugs

### ISSUE THREAD

**Issue by zhangdiming** [azerothcore/azerothcore-wotlk#17378]
### Current Behaviour

Enabling the "PreloadAllNonInstancedMapGrids" setting will cause the game to not correctly load the Smoldering Scrap with NPC entry 30169. 

To reproduce this issue, follow these steps: 

set "PreloadAllNonInstancedMapGrids" to 1, 

set "SetAllCreaturesWithWaypointMovementActive" to 1, 

then restart the world server, enter the game, and use the commands "

.go c 1975965" and ".modify phase 8." 

You won't be able to see the Smoldering Scrap; instead, you will only see the model associated with that NPC.

### Expected Blizzlike Behaviour

as set "PreloadAllNonInstancedMapGrids" to 0.

### Steps to reproduce the problem

1.set "PreloadAllNonInstancedMapGrids" to 1
2.set "SetAllCreaturesWithWaypointMovementActive" to 1,
3.restart the world server,
4. a GM character uses ".go c 1975965" and ".modify phase 8." 

### AC rev. hash/commit

latest  rev.

### Operating system

Ubuntu 22.04

**Comment by Kitzunu** [comment]
Add your info from ".server debug"
