### ISSUE TITLE
(Event/Brewfest): Process for starting fight with Coren Direbrew is incorrect.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17382]
### Current Behaviour

Currently you have to be ported in via random dungeon finder for [Coren Direbrew](https://wowgaming.altervista.org/aowow/?npc=23872) to spawn at all. Once you're ported in, you interact with Direbrew and go through a few gossip options to start fighting him. Also, the fight starts immediately after hitting the last gossip option.

### Expected Blizzlike Behaviour

Not only should Coren himself be spawned at all times regardless of the manner of entry, but the [Brewfest Spy](https://wowgaming.altervista.org/aowow/?npc=26719) should also be spawned in the Grim Guzzler at all times. Direbrew should not be interactable (but targetable) on his own. The spy will offer a [daily quest to insult Direbrew](https://wowgaming.altervista.org/aowow/?quest=12062) to everyone in the instance which gets turned into Direbrew. Once it is turned in, Direbrew will do a small RP saying the class will pay for the insult, and then combat will begin. Once killed, he should also respawn not long after (~10s) so that the other members of the instance can turn in the quest and get another run of loot.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.event start 24`
2. `.debug lfg`
3. `.level 79`
4. Queue for Coren Direbrew through RDF. (May have to log out/in)
5. Engage Direbrew.
6. Observe his behavior.

### AC rev. hash/commit

29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
So it seems the process in Classic is accurate only to <2010, after that [all event bosses were tied into RDF to be summoned](https://web.archive.org/web/20100228042701/http://forums.worldofwarcraft.com/thread.html?topicId=23329143450&sid=1&pageNo=1). The antagonist posse is still perma-spawned if you walk in the instance which may be incorrect, and the RP should still happen before combat starts based on retail, but otherwise this issue is invalid for 3.3.5a.

**Comment by sudlud** [comment]
Good research

**Comment by heyitsbench** [comment]
> Good research

Can't all be winners.
