### ISSUE TITLE
Karazhan Boss nightbane Script Bug

### ISSUE THREAD

**Issue by mayaren888** [azerothcore/azerothcore-wotlk#174]
**Description**:
Lack of script
http://www.wowhead.com/npc=17225/nightbane
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Click on the items after nightbane is not appeared

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
WIN7/X64
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

![20161009105134](https://cloud.githubusercontent.com/assets/6006653/19217522/740c0dba-8e0f-11e6-8bc9-f1d93bf3710a.png)
##

**Comment by talamortis** [comment]
I am looking into this now @mayaren888
