### ISSUE TITLE
[NPC] Coilskar defender

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1740]
DESCRIPTION:
the npc coilskar defender doesn't attack and it isn't possible to attack it

CURRENT BEHAVIOUR:

the npc coilskar defender doesn't attack and it isn't possible to attack it

STEPS TO REPRODUCE THE PROBLEM:

.go creature 70696 and try to attack it

BRANCH(ES):
master

AC HASH/COMMIT:
commit 6021de887558a9fb4d93278a903d30ae6112e073

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by poszer** [comment]
Same problem, flags :D

**Comment by poszer** [comment]
@comix1988 when you can, try the referenced fixes :+1:
