### ISSUE TITLE
[NPC-QUEST] Escape from the staging grounds

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#1741]
DESCRIPTION:

the "escape from the staging grounds" quest (ID 10425) cannot be completed.

BLIZZLIKE BEHAVIOUR:

![questnether](https://user-images.githubusercontent.com/22867608/56489079-d0338500-64e0-11e9-9157-66a9f7e3c036.png)

CURRENT BEHAVIOUR:

we have more than one bug:
- the npc "captured protectorate vanguard" (ID 86833) is always visible;
- the npc "ethereum guardian" (ID 86834) is not attackable;(spawn time 26min)
- the quest can be obtained but cannot be completed because being unable to kill the npc "ethereum guardian", the npc "captured protectorate vanguard" dies.

STEPS TO REPRODUCE THE PROBLEM:

.go creature 86833 
wait 26min to spawn Ethereum guardian or .go creature 86834 (in gm on), target he e use .resp command

BRANCH(ES):
master

AC HASH/COMMIT:
commit 6021de887558a9fb4d93278a903d30ae6112e073

OPERATING SYSTEM:
linux

MODULES:
OTHER CUSTOMIZATIONS:

**Comment by poszer** [comment]
Hmm interesting. As i can see from this creature in db, it has wrong flags : 
So posible issue is that, you can't kill/enter in combat with this NPC to escort Quest Creature.
> Ethereum guardian
> 256 | 0x0000 0100 | UNIT_FLAG_IMMUNE_TO_PC | disables combat/assistance with PlayerCharacters . 
Posting fix in some secs

**Comment by poszer** [comment]
Also @comix1988 while doing this quest, please take the quest from Captured protectorate vanguard, than escort him. 

![QuestCaptuired](https://user-images.githubusercontent.com/41213210/56495186-3b875200-64f5-11e9-9704-64b25c1ca619.png)

**Comment by Knindzagxg** [comment]
Quest it self working and can be completed which u can see bellow in video.

Problem remain with Arena Event:
* Vanguard and Gladiator should spawn at the same time and fight each other until player get close to them and kill Gladiator. At that point, Vanguard should offer quest and proceed with escort.

https://youtu.be/XKwj0yFPoZ0
