### ISSUE TITLE
Raid buffs not ignoring LoS.

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#17425]
### Current Behaviour

AoE Buffs do not ignore LoS.

### Expected Blizzlike Behaviour

AoE Buffs should ignore LoS.

### Source

Thank you @heyitsbench for helping sniff this bug on classic. As you can see in the video, [Flash heal] cannot be cast when the target is out of LoS, but the Prayer of Fortitude applies.
https://www.youtube.com/watch?v=ito5CNpDe_0

### Steps to reproduce the problem

Char A
.go xyz 1383 -4359 27.3 1
Char B
.go xyz 1394 -4358 25.5 1 1.8

Join group with A & B.
Confirm that there is no LoS.
On either one do ".cast 21849 t"
Notice only the caster gets the buff.

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/6145

<details>
<summary> List of all spells that use TARGET_UNIT_CASTER_AREA_RAID as Target A</summary>

469	    Commanding Shout
2048	Battle Shout
2825	Bloodlust
5242	Battle Shout
6192	Battle Shout
6673	Battle Shout
11549	Battle Shout
11550	Battle Shout
11551	Battle Shout
19594	Plague Effect
21562	Prayer of Fortitude
21564	Prayer of Fortitude
21849	Gift of the Wild
21850	Gift of the Wild
23028	Arcane Brilliance
25289	Battle Shout
25392	Prayer of Fortitude
26557	Plague Effect
26991	Gift of the Wild
27127	Arcane Brilliance
27681	Prayer of Spirit
27683	Prayer of Shadow Protection
32182	Heroism
32999	Prayer of Spirit
33006	Nagrand Fort Buff Reward Raid
39374	Prayer of Shadow Protection
43002	Arcane Brilliance
47436	Battle Shout
47439	Commanding Shout
47440	Commanding Shout
48074	Prayer of Spirit
48090	Demonic Pact
48162	Prayer of Fortitude
48170	Prayer of Shadow Protection
48470	Gift of the Wild
52759	Ancestral Awakening
52910	Turn the Tables
52914	Turn the Tables
52915	Turn the Tables
53651	Light's Beacon
54171	Divine Storm
54180	Judgements of the Wise
57330	Horn of Winter
57623	Horn of Winter
57669	Replenishment
59725	Spell Reflection
61316	Dalaran Brilliance
61332	[DND] Dalaran Brilliance
61782	Infinite Replenishment + Wisdom
63944	Renewed Hope
69377	Fortitude
69378	Blessing of Forgotten Kings
69381	Gift of the Wild
69511	Lucky Charm
69749	Shiny Shard of the Scale Heal Targeter
69754	Purified Shard of the Scale Heal Targeter
69994	Brilliance

</details>

This also includes TARGET_UNIT_TARGET_AREA_RAID_CLASS (Paladin greater buffs)

**Edit: This also causes the targeted spell (the 40y) to be ignoring LoS as well, which would be wrong.**
Or add ignore LoS flag to all, similar to bloodlust.
https://github.com/azerothcore/azerothcore-wotlk/blob/05161a9ffe5cd69832305657f17e0eaafda0c363/src/server/game/Spells/SpellInfoCorrections.cpp#L996-L1001

### AC rev. hash/commit

de50ce3

### Operating system

Windows 10

**Comment by pangolp** [comment]
From what I can understand in the video, it allows you to add the buff to a teammate, even if they are out of reach (in this case, behind a wall). However, it does not allow you to cure it. So what should be done is to prevent the buff from being added as well?

**Comment by heyitsbench** [comment]
> So what should be done is to prevent the buff from being added as well?

Right now the buffs already respect LoS, as in they're already being prevented from being added to players behind walls. They should ignore LoS and players behind walls should still get the aura from the caster.

**Comment by pangolp** [comment]
> Right now on AC, the buffs already respect LoS, as in they're already being prevented from being added to players behind walls. They should ignore LoS and players behind walls should still get the aura from the caster.

I don't know if this is the best way to do it, but following the suggestions, create the pull request. We'll see what happens.

**Comment by pangolp** [comment]
It would have been simpler to group them and put them all together, but if in the future you want to add something more to any of them, you would have to separate them, so I directly separated them to avoid that work in the future. But I don't know if it's the best way to do it, I'm just guided by what they said here.

**Comment by heyitsbench** [comment]
I would honestly prefer a generic solution for the target type personally, but that's not my call, and I can't complain about it working when it didn't before. 😄

**Comment by pangolp** [comment]
If something needs to be corrected, it is done. The issue is knowing what and where.
