### ISSUE TITLE
Bug diff

### ISSUE THREAD

**Issue by valentime21** [azerothcore/azerothcore-wotlk#17434]
### Current Behaviour

The increase in diff occurs after 3 hours of server operation . Online 50+
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/666639eb-67f3-46d5-b253-2853ffc8a4da)

core i9 9900kf 
10 gb ram
NVME 60 
Debian 11

Standard config

### Expected Blizzlike Behaviour

No high diff :D

### Steps to reproduce the problem

1. Start server
2. Wait 3 hour
3. Diff  random high

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a2c6af4c568380c11c01ec6599e7e158725d3ded

### Operating system

debian 11 x64

### Custom changes or Modules

https://github.com/azerothcore/mod-autobalance
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-anticheat
https://github.com/azerothcore/mod-cfbg
https://github.com/azerothcore/mod-aoe-loot
https://github.com/azerothcore/mod-weapon-visual
https://github.com/azerothcore/mod-learn-spells
https://github.com/azerothcore/mod-weapon-visual

**Comment by valentime21** [comment]
@UltraNix  fix please

**Comment by valentime21** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/08a23e4e-555e-45ed-987b-b26f3db85906)

**Comment by valentime21** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/971f0ade-187a-4cec-a93e-cfb2cbeefd8b)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/fee1d224-bfab-4f42-97c7-ceb36f11f226)

**Comment by Kitzunu** [comment]
Do .server debug

And send the information

**Comment by valentime21** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/a275aef7-e465-4f1e-ae90-3740156e2e79)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/95bc7ef7-8d8c-41b6-94c4-e0749c4c29fb)
Sry edit modules

**Comment by heyitsbench** [comment]
> Sry edit modules

I'm more concerned about that revision hash.

**Comment by valentime21** [comment]
[[[Before that there was - https://github.com/azerothcore/azerothcore-wotlk/commit/de1f3a1cdc6e431d60a7701c81e284701d70a2da there was also an increased diff , updated to the last commit](https://github.com/azerothcore/azerothcore-wotlk/issues/17434#issuecomment-1751215783)]

**Comment by valentime21** [comment]
Before that there was - https://github.com/azerothcore/azerothcore-wotlk/commit/de1f3a1cdc6e431d60a7701c81e284701d70a2da there was also an increased diff , updated to the last commit

**Comment by valentime21** [comment]
And off anticheat and autobalance but it didn't help

**Comment by valentime21** [comment]
Off transmog and aoe loot no didn't help

**Comment by valentime21** [comment]
Reboot fixes the diff for 2-3 hours

**Comment by valentime21** [comment]
1 hour later 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/b15793f0-0a50-4a59-8859-96a591f94a55)

**Comment by valentime21** [comment]
1 hour later
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/2b8c605d-a28b-4c8f-842a-522830d4cefd)

**Comment by valentime21** [comment]
1 hour later 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/f9aaaba2-309a-458a-bac5-5ee341d7d756)

**Comment by valentime21** [comment]
1 hour later 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/147187451/3fd4b256-6bdc-4816-af24-dd3de0ec0d71)

**Comment by Nyeriah** [comment]
How much ram are you using? And fix your revision hash. The visibility PR increased resource usage considerably

**Comment by valentime21** [comment]
> How much ram are you using? And fix your revision hash. The visibility PR increased resource usage considerably

10 gb server, use 6-8 gb

**Comment by valentime21** [comment]
> How much ram are you using? And fix your revision hash. The visibility PR increased resource usage considerably

Revision - https://github.com/azerothcore/azerothcore-wotlk/commit/a2c6af4c568380c11c01ec6599e7e158725d3ded

**Comment by valentime21** [comment]
I used a server with 16 GB of RAM, it didn't help

**Comment by pklloveyou** [comment]
Is it possible that it is related to thishttps://github.com/TrinityCore/TrinityCore/issues/24356

**Comment by moncat2005** [comment]
This issue may still be related to the introduction of core/grids (commit 2779833). 
After this step, the CPU usage of the Worldserver process has almost tripled, 
and the TOP tool under Linux shows that the CPU usage of the process has skyrocketed from 30% to 105%. 
Even if the visual object distance parameters related to this grid function adjustment are reduced to the original data, the CPU usage of WorldServer remains very high. 
In this case, it is expected that an extremely large value of "uptimediff" will occur.
At present, as long as the source code is rolled back to September 28th and recompiled and run, the problem will disappear.

**Comment by deef32** [comment]
> This issue may still be related to the introduction of core/grids (commit 2779833). After this step, the CPU usage of the Worldserver process has almost tripled, and the TOP tool under Linux shows that the CPU usage of the process has skyrocketed from 30% to 105%. Even if the visual object distance parameters related to this grid function adjustment are reduced to the original data, the CPU usage of WorldServer remains very high. In this case, it is expected that an extremely large value of "uptimediff" will occur. At present, as long as the source code is rolled back to September 28th and recompiled and run, the problem will disappear.

I use https://github.com/azerothcore/azerothcore-wotlk/commit/de1f3a1cdc6e431d60a7701c81e284701d70a2da rev and high diff

**Comment by mpfans** [comment]
`git reset --hard 29af6cc88662ab2565bdcedcf60e12f0cc87cecf`

All the problems have disappeared

**Comment by AGandrup** [comment]
Hey! Can anyone test the latest changes done here: https://github.com/azerothcore/azerothcore-wotlk/pull/17480 and check if that fixes the issue? Thanks in advance 😬

**Comment by Kitzunu** [comment]
@mpfans @pklloveyou could you guys test the PR above?

**Comment by AGandrup** [comment]
Please see: https://github.com/azerothcore/azerothcore-wotlk/pull/17569#issuecomment-1781983068
Should be fixed now.

**Comment by Kitzunu** [comment]
@mpfans @valentime21 has this issue been resolved?

I will give it until the end of the weekend, then I close as fixed
