### ISSUE TITLE
(Death's Challenge) quest is okay NPC Wrong Gossip Id

### ISSUE THREAD

**Issue by Seebaby** [azerothcore/azerothcore-wotlk#1744]
SMALL DESCRIPTION:

If you accept the quest Death's Challenge you should have a duel against real players or against the NPC's.

This doesn't work because the gossip id is wrong in the script so you can't start the duell.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

start duell about gossip

##### CURRENT BEHAVIOUR:

Duell cannot be started because there is no gossip text available

##### STEPS TO REPRODUCE THE PROBLEM:

Create a Death Knight
give yourself the quest 12733
Go down to the npc and start the duell.

##### BRANCH(ES):
AzerothCore rev. 22d4cae1f1c4+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

####### MODULE:
mod-transmog
mod_world_chat

**I have already deleted the problem and would be happy to provide the solution.** 

<img width="1968" alt="Fixx quest" src="https://user-images.githubusercontent.com/179698/56508425-840a3400-6524-11e9-8620-72232dcc2eb6.png">

for the solution see pictures

**Comment by Pondaveia** [comment]
Thanks for the contribution @Seebaby , would you kindly open up a pull request with the changes please? If you need help don't hesitate contacting anyone in Azerothcore's discord channels.

**Comment by poszer** [comment]
Changed with this commit https://github.com/azerothcore/azerothcore-wotlk/commit/fe17a0ecccb99ef96b901cdb0b4e16088c32eff6 @Nefertumm

**Comment by Nefertumm** [comment]
Typo, feel free to open a pr with the fix.
