### ISSUE TITLE
K'iru's Song of Victory - Isle of Quel'Danas Zone Buff

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1746]
##### SMALL DESCRIPTION:

The buff K'iru's Song of Victory (https://wowgaming.altervista.org/aowow/?spell=46302) is NOT ACTIVE on the Isle of Quel'Danas. This buff should be active after K'iru spawns as a result of Isle of Quel'Danas being secured by Shattered Sun Offensive. In Wotlk K'iru is spawned by default without players having to complete the entire Isle of Quel'Danas story chain or having to turn in a set number of dailies. So the buff should be active at all times on the Isle of Quel'Danas including Magister's Terrace dungeon and Sunwell Plateau raid.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As soon as player sets foot onto Isle of Quel'Danas, the K'iru's Song of Victory Buff should activate and it should be carried into Magister's Terrace Dungeon as well as the Sunwell Plateau raid. The buff should only wear off if the player leaves Isle of Quel'Danas zone.
https://wowgaming.altervista.org/aowow/?spell=46302
https://wow.gamepedia.com/K%27iru%27s_Song_of_Victory
https://wow.gamepedia.com/K%27iru

##### CURRENT BEHAVIOUR:

No K'iru's Song of Victory buff at all on Isle of Quel'Danas.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele queldanas
2.  No buff in zone or inside Magisters's Terrace or inside Sunwell Plateau

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

22d4cae

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by JamesGent** [comment]
Wowwiki says

"This spell is cast by K'iru once all objectives as part of the Shattered Sun Offensive storyline are completed. This buff functions everywhere on the Isle of Quel'Danas and inside Magisters' Terrace. Unlike other zone buffs such as Rallying Cry of the Dragonslayer this is permanent as long as K'iru is active. "

Completion

Once all objectives on the Isle have been completed, and an unknown number of additional daily quests have been completed, K'iru spawns and buffs players zone-wide and inside the Magisters' Terrace with K'iru's Song of Victory, increasing Stamina by 79 and Intellect by 40. 

https://wowwiki.fandom.com/wiki/Shattered_Sun_Offensive#Reclaiming_Sun.27s_Reach

**Comment by JamesGent** [comment]
If someone wants to test this again after completing all the dailies (likely 10,000+) and finishing the entire questline feel free to create a new issue. We could also handwave the requirements if we want to step away from blizzlike(?)
