### ISSUE TITLE
Commands to shut down auth and world servers result in immediate restart of processes instead of shutting down

### ISSUE THREAD

**Issue by iipamonkey** [azerothcore/azerothcore-wotlk#17467]
### Current Behaviour

In the CLI console, issuing the commands ".server shutdown" and ".server exit" cause an immediate restart of the servers.

### Expected Blizzlike Behaviour

Issuing the commands ".server shutdown" and ".server exit" should result in the servers shutting down and not restarting.

### Steps to reproduce the problem

1. start server using "./acore.sh run-worldserver"
2. issue ".server shutdown" and/or ".server exit"
3. Observe servers immediately restart instead of shutting down

### Extra Notes

I just downloaded/built the core yesterday for the first time using the dashboard script method.

### AC rev. hash/commit

AC> AzerothCore rev. 999cdf7ee45c 2023-10-08 11:51:18 +0000 (master branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 14 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100519
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.10.0-22-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_09_16_00.sql
Latest WorldDatabase update: 2023_10_08_03.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Debian 11

**Comment by Nyeriah** [comment]
You’re running a restart script, all of the commands you mentioned (including server restart) will shutdown the executable permanently under normal circumstances

**Comment by iipamonkey** [comment]
> You’re running a restart script, all of the commands you mentioned (including server restart) will shutdown the executable permanently under normal circumstances

Thanks for replying. I did nothing but run the dashboard script installation exactly per the instructions. What part of that process creates a "restart script" and how do you disable it? I have done nothing on this server manually to enable such functionality.

**Comment by 55Honey** [comment]
> start server using "./acore.sh run-worldserver"
The score shell script includes a restarter. If you don't want it, start the worldserver binary manually instead.

**Comment by iipamonkey** [comment]
> > start server using "./acore.sh run-worldserver"
> 
> The acore shell script includes a restarter. If you don't want it, start the worldserver binary manually instead.

Thank you!
