### ISSUE TITLE
[Brewfest] Drunken Brewfest Reveler - wrong model

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#17491]
https://github.com/chromiecraft/chromiecraft/issues/6206
### Current Behaviour

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/e8cde636-04a8-471c-9a85-e6968fb9899e)

### Expected Blizzlike Behaviour
Correct model (probably morphed for Durotar, original modelID is a dwarf), [aura ](https://www.wowhead.com/wotlk/spell=43905/completely-hammered) missing for ironforge spawn

### Source

https://www.wowhead.com/wotlk/npc=23698/drunken-brewfest-reveler

### Steps to reproduce the problem

.go c 88896
.go c 88960

### Extra Notes

https://www.wowhead.com/wotlk/npc=23698
https://www.wowhead.com/wotlk/spell=43905/completely-hammered

Related https://github.com/azerothcore/azerothcore-wotlk/issues/17399

### AC rev. hash/commit

1753a8d

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
No, it is correct that only one reveler can exist at a time per camp at any given time. Wowhead is simply seeing their RP movement as separate spawns which is not correct.

**Comment by heyitsbench** [comment]
Sniffed this (50664). Goblin reveler had the following spells:
```
35777 - Bloodmaul Intoxication Visual (Dummy aura effect)
43905 - Completely Hammered (Dummy aura effect)
44096 - Brewfest Reveler - Drunk Goblin (Transform aura effect, NPC 24632)
```
Dwarf reveler had the following spells:
```
35777 - Bloodmaul Intoxication Visual (Dummy aura effect)
43905 - Completely Hammered (Dummy aura effect)
```
