### ISSUE TITLE
Update core rev Referenced commit(s): 7d6a578

### ISSUE THREAD

**Issue by kurigvin** [azerothcore/azerothcore-wotlk#17500]
### Current Behaviour

Error error compilation:

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:192: src/server/apps/worldserver] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:932: src/server/apps/CMakeFiles/worldserver.dir/all] Ошибка 2
make: *** [Makefile:136: all] Ошибка 2

### Expected Blizzlike Behaviour

100% compilation

### Steps to reproduce the problem

Without modules everything is fine

### AC rev. hash/commit

Didn't start the server

### Operating system

Debian  12

**Comment by Kitzunu** [comment]
CI passing so something wrong on your end
