### ISSUE TITLE
chat log write garbled code

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#17519]
### Current Behaviour

Before updating this commit (https://github.com/azerothcore/azerothcore-wotlk/commit/66066f508ba5d9fcaedb5f1a55f9e3c21aaa1dac),and set `worldserver.conf`

```
Appender.DB=3,5,0
Logger.chat.log=4,DB
Logger.chat.log.addon=4,DB
```
 the chat record is written to the database
Update to the latest commit (https://github.com/azerothcore/azerothcore-wotlk/commit/608f1c92fad0d418a0b70f90905ea93a14f70148)

 set `worldserver.conf`

```
Appender.DB=3,5,0
Logger.chat.log=4,DB
Logger.chat.log.addon=4,DB
```

`logs` table not any log

and set `worldserver.conf`
```
Logger.chat.say=4,DB Chat
Logger.chat.emote=4,Console Chat
Logger.chat.yell=4,DB Chat
Logger.chat.whisper=4,DB Chat
Logger.chat.party=4,DB Chat
Logger.chat.raid=4,DB Chat
Logger.chat.bg=4,DB Chat
Logger.chat.guild=4,DB Chat
Logger.chat.guild.officer=4,DB Chat
Logger.chat.channel=4,DB Chat
Logger.chat.addon.msg=4,DB Chat
Logger.chat.addon.emote=4,DB Chat
Logger.chat.addon.yell=4,DB Chat
Logger.chat.addon.whisper=4,DB Chat
Logger.chat.addon.party=4,DB Chat
Logger.chat.addon.raid=4,DB Chat
Logger.chat.addon.bg=4,DB Chat
Logger.chat.addon.guild=4,DB Chat
Logger.chat.addon.guild.officer=4,DB Chat
Logger.chat.addon.channel=4,DB Chat
```
The following garbled code appears

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18187177/962d5b64-68f4-4c29-987d-d5483e8081b6)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

608f1c92fad0d418a0b70f90905ea93a14f70148

### Operating system

Ubuntu20.04

**Comment by mpfans** [comment]
@Kitzunu maybe you can help with this issue.tyvm

**Comment by Kitzunu** [comment]
Weird

**Comment by Kitzunu** [comment]
Also, all of them are sent by player addons. You could just decide to not log addon messages

**Comment by mpfans** [comment]
> Also, all of them are sent by player addons. You could just decide to not log addon messages

Please try a language other than English. One of the images I am displaying was sent by the player to raid

**Comment by Kitzunu** [comment]
to me it all looks like messages from some addon.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/ffbb2ed3-0595-4047-aa91-60fbfceca820)


Can you instead send a picture from a player that said something in chat.say for example?

**Comment by mpfans** [comment]
> to me it all looks like messages from some addon. ![image](https://user-images.githubusercontent.com/24550914/276262731-ffbb2ed3-0595-4047-aa91-60fbfceca820.png)
> 
> Can you instead send a picture from a player that said something in chat.say for example?


sry, I removed the following content and it work



```
Logger.chat.addon.msg=4,DB Chat
Logger.chat.addon.emote=4,DB Chat
Logger.chat.addon.yell=4,DB Chat
Logger.chat.addon.whisper=4,DB Chat
Logger.chat.addon.party=4,DB Chat
Logger.chat.addon.raid=4,DB Chat
Logger.chat.addon.bg=4,DB Chat
Logger.chat.addon.guild=4,DB Chat
Logger.chat.addon.guild.officer=4,DB Chat
Logger.chat.addon.channel=4,DB Chat```

**Comment by Kitzunu** [comment]
well yea, because that is for logging addon messages... like I said

**Comment by mpfans** [comment]
> well yea, because that is for logging addon messages... like I said

only set
```
Logger.chat.yell=4,DB
Logger.chat.whisper=4,DB
Logger.chat.party=4,DB
Logger.chat.raid=4,DB
Logger.chat.bg=4,DB
Logger.chat.guild=4,DB
Logger.chat.guild.officer=4,DB
Logger.chat.channel=4,DB
```
There are still some addon logs available

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18187177/eaf8586e-8ddf-4bde-8e80-1eddcf61a31b)
