### ISSUE TITLE
Worldserver.exe closes right away

### ISSUE THREAD

**Issue by ForTheGreaterGood4** [azerothcore/azerothcore-wotlk#17527]
Hello, I am new to WoW private server repacks.
I have downloaded the AzerothCore Single Player Repack and its patches on wowsingleplayer.my.id.
But whenever I try launching the "Worldserver.exe" it simply shut down right away.

I extracted the repack, then the update and finally the hotfix, I have not extracted the 11k NPCbots addon yet.
I have the .conf files inside the main folder, inside "configs" and "config", while I had everything, it didn't work so I deleted them all and kept only the one in configs as it is supposedly the one it requires.
I have edit the file with the right locations.
But the Worldserver still refuses to launch, it gave me errors before editing it, now it simply says some things and at the end it says "Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1." and it closes itself. 
At some point, I was able to connect in-game with "admin" as both the username and password but not anymore.
And when I was able to do that, when I would try to join the server, it wouldn't work, probably because Worldserver isn't up.
MySQL and AuthServer seems to work properly but Worldserver refuses to launch and work properly.
If I understand well, I need Worldserver to be able to play on the "server", also need it to create an account with a different username and password.

Anyone has an idea on how to fix this? I have been looking for a fix for days now, I have check the help seciton but the reasons why the software closes over there seems to be different to mine.

Thanks to anybody who can help me.

**Comment by Kitzunu** [comment]
Dont use a repack. Compile the core yourself

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/installation
