### ISSUE TITLE
Can't start Headless Horseman fight

### ISSUE THREAD

**Issue by SmileyPlatypus** [azerothcore/azerothcore-wotlk#17538]
I can queue for the event fight, get in, talk to the pumpkin, and click the response, then nothing happens.

This only happens on my 80 mage and 80 warrior. I have 6 other 80s it works on.

They are both gnomes, but so is my dk. The only two things I can think of they have in common is they both have a Brewfest Kodo

**Comment by SmileyPlatypus** [comment]
Why was this closed?

**Comment by Kitzunu** [comment]
because you did not make a bug report

**Comment by SmileyPlatypus** [comment]
I'm confused where do I go to make a bug report then? I clicked to make a bug report then clicked new issue

**Comment by Nyeriah** [comment]
You deleted the bug report template you were supposed to fill
