### ISSUE TITLE
Can't summoned the headless horseman by pumpkin shrine in LFG Dungeon

### ISSUE THREAD

**Issue by pagimu** [azerothcore/azerothcore-wotlk#17539]
### Current Behaviour

If I click on the shrine then comes only a Text but nothing happen.  The Script "go_pumpkin_shrine" doesn't start.

### Expected Blizzlike Behaviour

Using the "Call the Headless Horseman" gossip menu on the Pumpkin Shrine summons the Headless Horseman.

### Steps to reproduce the problem

1. Join dungeon via the LFG tool.
1. Click on the Pumpkin Shrine to summon the headless horseman

### Extra Notes

I have use a new compiled core wihtout any changes on server and client side. But the problem still exist. 

### AC rev. hash/commit

AzerothCore rev. ed9f35932828 2023-10-18 16:04:42 +0200 (master branch) 

### Operating system

Windows 11 x64

### Custom changes or Modules

breakingnews.conf
dungeonrespawn.conf
1v1arena.conf
mod_ahbot.conf
AutoBalance.conf
mod_charactertools.conf
mod_LuaEngine.conf
Individual-XP.conf
mod_moneyforkills.conf
reagent_bank.conf
reward_system.conf
reward_shop.conf
SoloLfg.conf
transmog.conf
mod-weapon-visual.conf

**Comment by noisiver** [comment]
I can't confirm this as it works fine on my end. I took this screenshot 30 seconds ago after summoning him.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/5157047/a29d72d6-d094-4eca-8e7e-3068f35d7364)

This is also what I see when I right-click the pumpkin
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/5157047/2720a11d-880e-4263-8287-88ae2f430b2c)

**Comment by pagimu** [comment]
Thank you. That is what I see. What could be the problem at my side? Maybe somebody have an Idea?
![headlesshorseman](https://github.com/azerothcore/azerothcore-wotlk/assets/55284322/e77a9a75-6569-4f8b-83ad-dfd5cf70aca9)

**Comment by drozco** [comment]
I noticed if I enter the dungeon in GM mode, even if you turn it off before calling the horseman, it will not trigger.

**Comment by pagimu** [comment]
I found that the Gossip_Menu_Option (ID=8891) was lost in DB. I don't know why, but now it works again. Also in GM mode. :-) 

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/55284322/14d98743-00b3-4561-b124-6105b2eee076)
