### ISSUE TITLE
Can't summon Headless Horseman

### ISSUE THREAD

**Issue by SmileyPlatypus** [azerothcore/azerothcore-wotlk#17540]
### Current Behaviour

I can dungeon queue for the Headless Horseman fight, talk to the pumpkin, and hit the response, then nothing happens.

This is only on my level 80 mage and level 80 warrior. I have 6 other 80s it works fine on.

### Expected Blizzlike Behaviour

My character should start the script, and the Headless Horseman should be summoned.

### Source

It works fine for my other 6 80s

### Steps to reproduce the problem

Have a level 80 mage/warrior
Queue for dungeonfinder Headless Horseman
Try to activate the Headless Horseman through the pumpkin

### Extra Notes

The only thing I can think of these two characters have in common that none of my others do is they both have a brewfest kodo mount. At first I thought it was because they were gnomes but my DK works fine and hes also a gnome. Same hairstyle exactly too.

### AC rev. hash/commit

Idk

### Operating system

Windows 11

**Comment by SmileyPlatypus** [comment]
You can close it. Ty for help. After patching server I was able to do it. Took several attempts/relogs on each character(even after patch) but it eventually worked. Sorry the servers run by my cousin I don't have the hash/commit.

**Comment by kissingers** [comment]
It ok, you did not update nearly PR.
