### ISSUE TITLE
[Alterac Valley] worldserver crash after defeating the Alliance boss

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1756]
##### SMALL DESCRIPTION:
Defeating the Alliance boss ([Vanndar Stormpike](https://wowgaming.altervista.org/aowow/?npc=11948)) as the horde results in a server crash. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Battleground should end, server should not crash.

##### CURRENT BEHAVIOUR:
Server crashes. See: 
![56539028-f6c5e000-6521-11e9-8dd9-7efaa167274f](https://user-images.githubusercontent.com/43800467/56651109-962fc380-6645-11e9-9007-68a7358672da.PNG)

Maybe something to do with having less than minimum players when debugging?

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a horde character
2. Create an alliance character on separate account
3. Queue both for Alterac Valley
4. Type `.debug bg`
5. Enter battle on both
6. When the battle begins, go to the Alliance keep and slay Vanndar Stormpike
    (you can do this easily by using `.learn all gm`  and then using one of the dmg spells
7. Scoreboard will sometimes appear, but nothing will work, worldserver.exe will show error.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
b81c15762826b25d1aa269377ec3be29c1a2de9d

##### OPERATING SYSTEM:
Windows 10

**Comment by Falstring** [comment]
hey,

can you post entire crashlog for this

**Comment by poszer** [comment]
I was in bg with 2 players (Alliance and Horde) - .debug mode on checking some factions related to players. And while doing that, the server just crashed. So i can say the issue is not with related with killing Boss.
![crashAlterac](https://user-images.githubusercontent.com/41213210/56727237-8cdf4d80-6750-11e9-8d45-8228115edfac.png)

**Comment by Falstring** [comment]
Question is if this only occurs in debug mode

**Comment by poszer** [comment]
> Does this only occur while in debug mode?

Maybe, we should test this as in other mode

**Comment by Seebaby** [comment]
So I killed BG 4 times, killed Horde boss 2 times, killed Alli Boss 2 times and conquered everything in between. No crash

AzerothCore rev. f05fee7+ 2019-05-13 17:15:14 +0000 (master branch) (Win64, Release)

MODULE:
mod transmog
mod_world_chat

**Comment by FrancescoBorzi** [comment]
thanks @Seebaby for your feedback, could you please test the same with this PR too? 

https://github.com/azerothcore/azerothcore-wotlk/pull/1695

**Comment by shuradumau** [comment]
this error occurs when you enter from gm on bg and teleport or from .recal on some player that is within bg ... for error you happen to need to be with gm within bg and use the .tele or .recal command at some player inside the bg ..

example: log in to two accounts and enter any bg, check bg and enter, one has to be gm .. when you enter bg, turn off the gm so you can walk on bg, then switch on the gm and go to your other account, and a .tele in your other account. and the mistake will happen
