### ISSUE TITLE
[Alterac Valley] Trash mobs do not randomly wander within their spawn area

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1757]
##### SMALL DESCRIPTION:
The random mobs that exist in Alterac Valley should wander within a small radius of their spawn point. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Trash mobs in AV should wander within a small radius of their spawn point as seen at points in [this video](https://youtu.be/MBg7EPuGixw?t=5)

##### CURRENT BEHAVIOUR:
Trash mobs stay motionless in one place until engaged. 
See: [Wild Creatures section on wowwiki AV page for list of creatures](https://wowwiki.fandom.com/wiki/Alterac_Valley#Wild_creatures)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a character
2. Queue for Alterac Valley
3. Type `.debug bg`
4. Enter battle
5. Look at the previously mentioned mobs

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
b81c15762826b25d1aa269377ec3be29c1a2de9d

##### OPERATING SYSTEM:
Windows 10

**Comment by wetbrownsauce** [comment]
Upon further investigation, the guards around Graveyard flags should also wander a little bit. 
See [this video](https://youtu.be/MBg7EPuGixw?t=312)

**Comment by poszer** [comment]
Since this creature using SAI already, attaching the random move there in little radius should fix this problem. I'll take a look on this

**Comment by poszer** [comment]
@wetbrownsauce When you are able, try the referenced PR please :+1:
