### ISSUE TITLE
(Crash) WorldServer Icc npc_icc_gauntlet

### ISSUE THREAD

**Issue by Fireevil** [azerothcore/azerothcore-wotlk#17575]
### Current Behaviour

https://gist.github.com/Fireevil/604253a9646655d6f9e07f8fe950708b

every time they reach the icc spider anuba trap after of sindragosa the server crashes

Before it didn't happen, the only changes I made was updating the server and adding the autobalance module

### Expected Blizzlike Behaviour

there should be no crash

### Steps to reproduce the problem

cross the room of spiders before sindragosa crashes when activating the trap

### AC rev. hash/commit

last rev   d2a3683210a1c3242df2b582022375d95c65aba6

### Operating system

windows 10

### Custom changes or Modules

mod-autobalance last rev

**Comment by Fireevil** [comment]
with update it still appears

**Comment by gamabutara** [comment]
Confirm last rev 0025758fb8ae192166665ae0cf3cadfec2da8b9a   
I was on icc 10, we stepped on a trap https://www.wowhead.com/wotlk/es/npc=37503/sindragosas-ward  and the server crashed

**Comment by jshplayer** [comment]
Can also confirm this is occurring and have a stack trace if you'd like another

**Comment by qwe900** [comment]
iam using an old version of autobalance and have the same issue after merging to newest core, maybe its due the gridunload system ? also saw that the elevator to sindra has multiple platforms. Some ICC runs works, and some where u see multiple elevators crahes the worldserver

**Comment by qwe900** [comment]
disable gridunlaod throud worldserver conf then its works

**Comment by jshplayer** [comment]
can you mention the specific line i don't see it on latest conf.dist

**Comment by qwe900** [comment]
#
#    GridUnload
#        Description: Unload grids to save memory. Can be disabled if enough memory is available
#                     to speed up moving players to new grids.
#        Default:     1 - (enable, Unload grids)
#                     0 - (disable, Do not unload grids)

GridUnload = 0


my cf it is 439

**Comment by jshplayer** [comment]
thanks i was actually missing this conf i'll try that out but it sounds logical
