### ISSUE TITLE
worldserver crash when a player create a character with wrong race and class

### ISSUE THREAD

**Issue by Vitumoc** [azerothcore/azerothcore-wotlk#17577]
### Current Behaviour

I use a latest version of AzerothCore, here is my server info:
AzerothCore rev.  2217563fb1dc 2023-10-20 12:50:59 +0000 (master branch) (Unix, RelWithDebInfo, Static)

when a user use a modified client, and try to create a Orc Mage(Normally this is not possible), the worldserver will crash, an this is the end of the logfile.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/31403302/adeffb1d-04ed-4e77-b3fc-0eac1b660255)

### Expected Blizzlike Behaviour

Character creation failed
user be kick out

### Steps to reproduce the problem

1. downlaod the patch
link：https://pan.baidu.com/s/1SR559ws1YtXxHnrGI3qUNw 
code：l5kl

2. copy the path to client
3. login an create a orc mage

### AC rev. hash/commit

AzerothCore rev. 2217563fb1dc 2023-10-20 12:50:59 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 24. Characters in world: 22.
Connection peak: 33.
Server uptime: 1 day(s) 30 minute(s) 16 second(s)
Update time diff: 9ms, average: 8ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 100612
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-87-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/vc/azeroth-data/maps. Total size: 291014951 bytes
vmaps directory located in /home/vc/azeroth-data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/vc/azeroth-data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autobalance
- mod-eluna
- mod-progression-system
- mod-solo-lfg
- mod-transmog

### Operating system

Ubuntu 22.04.2 LTS

**Comment by Kitzunu** [comment]
Add a gdb crash log

**Comment by pklloveyou** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/db4c49aa-3aef-47c2-9b43-05276bdc2069)
no crash

**Comment by Vitumoc** [comment]
I can reproduce this problem stably
When I try to create a race/class combination that shouldn't exist

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/31403302/01382d2a-0a87-4f56-8293-1982d9d1cca3)

The steps to reproduce are as I described above. need to place the patch in the position shown in the picture below.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/31403302/3b89086e-a282-4b37-bf6c-835bf82e3474)

here is the crash info:

[2217563fb1dc_worldserver.exe_[26-10_18-11-57].txt](https://github.com/azerothcore/azerothcore-wotlk/files/13176003/2217563fb1dc_worldserver.exe_.26-10_18-11-57.txt)

[2217563fb1dc_worldserver.exe_[26-10_18-11-57].dmp](https://github.com/azerothcore/azerothcore-wotlk/files/13176004/2217563fb1dc_worldserver.exe_.26-10_18-11-57.dmp)

**Comment by Kitzunu** [comment]
Dont upload files. Put the crashlog in gist

**Comment by Vitumoc** [comment]
here is the crashlog in gist:

https://gist.github.com/Vitumoc/8b3a21ad981bc1c6f6ca1cda64a8f11f

**Comment by Kitzunu** [comment]
Can you remove all your modules and try again please.

**Comment by Vitumoc** [comment]
you are really a genius

I try a latest version with no mod, no problem occurred, here is server debug:

https://gist.github.com/Vitumoc/a7ae64d07ffee7bc2152a0bec005f327

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/31403302/433e7141-37f2-46e4-a6d1-578709d6eeaa)



then i try the version with only one mod "mod-autobalance", The crash occurs again

**Comment by Kitzunu** [comment]
Open an issue on the auto balance repo instead

**Comment by kjack9** [comment]
Hello all,

I'm not sure how to fix this issue from the AutoBalance side. I added some additional checks to the function that is failing:

https://github.com/kjack9/mod-autobalance/blob/1c22e9b87e7c475cfeb0d35b01067471e08dad9a/src/AutoBalance.cpp#L3657-L3664

And yet that `->GetMap()` call on line 3660 is what's causing the user's crash.

[Full Crash Log](https://gist.githubusercontent.com/Vitumoc/d181445fd06bbb9072b1b3829b4beddc/raw/1ac1a48700efe716fe2fdbca09802a5316b06a72/52d37a927dc9_worldserver.exe_%255B31-10_14-2-44%255D.txt)

I'm a fresh-faced newb at deciphering crash reports, but it looks to me like the call that's failing is here:
https://github.com/azerothcore/azerothcore-wotlk/blob/52d37a927dc921785fcac35bd8830221299495c7/src/server/game/Entities/Object/Object.h#L526

Is there another way I can be checking before running that `GetMap()`? Or is this something that needs to be fixed in AC?

**Comment by Vitumoc** [comment]
I'm a newbie to open source, and here's my analysis of the problem.

When the character(player) is created, an PlayerInfo object will be obtained based on race and class, which contains map information.

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L482

When the race and class are incorrect, this info is actually a null pointer.

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Globals/ObjectMgr.cpp#L9965

The console will report an error here.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/31403302/74a066ab-8dc0-486c-b322-6ea15077cc2b)


I think that in this process, the player's map is not initialized.

WorldSession will then delete this player, so CleanupsBeforeDelete will be called.
Normally this is not a problem.

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L463

But in the CleanupsBeforeDelete function, OnPlayerLeaveCombat in autoBalance will be called. GetMap will be used here.

Therefore, a crash occurs when autoBalance uses GetMap because m_currMap has not been initialized.

**Comment by Vitumoc** [comment]
Maybe executing SetMap before LOG_ERROR can solve this problem, but it doesn't look good.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/31403302/456caba5-3fe1-4938-94f6-8061d2925111)

**Comment by Vitumoc** [comment]
I have tried the modification method just mentioned, and it does not crash anymore.

**Comment by kjack9** [comment]
> I have tried the modification method just mentioned, and it does not crash anymore.

Awesome! I'd suggest you submit a PR from your fork to the main azerothcore-wotlk repo. Let's get it resolved permanently!

**Comment by Vitumoc** [comment]
Thank you for your encouragement.

I would like to further explore this issue.

When creating a character, the character should not have entered the world yet. So why is it necessary to clean it in WorldSession?

I will try to figure out the reason for this and then see if there are any modifications in this regard.

I believe that such a modification would be more reasonable than the modification I proposed before.
