### ISSUE TITLE
The chat log incorrectly recorded the addon log

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#17570]
### Current Behaviour

if install `Details` will record the addon log in the chat whispering record

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18187177/1ee28438-09ea-47a5-aded-6ff4207d43f0)

[Details.zip](https://github.com/azerothcore/azerothcore-wotlk/files/13090161/Details.zip)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. worldserve.conf set
```
Appender.DB=3,5,0
Logger.chat.whisper=4,DB
```

2.install `Details`
3.Create character A and B
4.`.level 80`
5.use any talent points at will
6.character A invite B to join the group
7.no need to do anything, you will see the approximate content of the image in the database

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/608f1c92fad0d418a0b70f90905ea93a14f70148

### Operating system

Ubuntu20.04

**Comment by Kitzunu** [comment]
Well no, because that would be what the addon is sending

**Comment by mpfans** [comment]
Annotated here
```
#Logger.chat.addon.whisper=4,DB
```

**Comment by mpfans** [comment]
Before updating the commit of the chat log, all records were normal and there were no spam messages sent by these addons

**Comment by Kitzunu** [comment]
This will fix it https://github.com/azerothcore/azerothcore-wotlk/pull/19441

I totally missed whispers lol
