### ISSUE TITLE
Dead loop during RemoveAllAurasOnDeath for spell 38067(Guard's Mark)

### ISSUE THREAD

**Issue by liyunfan1223** [azerothcore/azerothcore-wotlk#17580]
### Current Behaviour

When character has aura [Guard's Mark](https://www.wowhead.com/wotlk/spell=38067/guards-mark) and die, server will stuck since the dead loop of Unit::RemoveAllAurasOnDeath.

### Expected Blizzlike Behaviour

Remove the aura [Guard's Mark](https://www.wowhead.com/wotlk/spell=38067/guards-mark) correctly without dead loop.

### Steps to reproduce the problem

1. Create a new horde character.
2. Teleport to Honor Hold `.go xyz -683 2657 91 530`
3. Get the aura [Guard's Mark](https://www.wowhead.com/wotlk/spell=38067/guards-mark).
4. Killed by guards or `.die` to yourself.

### Extra Notes

Thread 1 "worldserver" received signal SIGINT, Interrupt.
0x000055555688192d in je_arena_dalloc_bin_junked_locked ()
(gdb) bt
#0  0x000055555688192d in je_arena_dalloc_bin_junked_locked ()
#1  0x000055555687cdf3 in je_tcache_bin_flush_small ()
#2  0x000055555686c044 in je_free_default ()
#3  0x0000555555d20e19 in std::_Hashtable<ObjectGuid, ObjectGuid, std::allocator<ObjectGuid>, std::__detail::_Identity, std::equal_to<ObjectGuid>, std::hash<ObjectGuid>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_M_erase(std::integral_constant<bool, true>, ObjectGuid const&) ()
#4  0x00005555561e468b in void VisitorHelper<Acore::VisibleNotifier, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > >(Acore::VisibleNotifier&, ContainerMapList<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >&) ()
#5  0x00005555561e154d in void Cell::Visit<Acore::VisibleNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >(CoordPair<512u> const&, TypeContainerVisitor<Acore::VisibleNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, Map&, float, float, float) const ()
#6  0x00005555561db6b5 in void Cell::VisitAllObjects<Acore::VisibleNotifier>(WorldObject const*, Acore::VisibleNotifier&, float, bool) ()
#7  0x00005555561da087 in Player::UpdateVisibilityForPlayer(bool) ()
#8  0x000055555665e438 in AuraEffect::HandleEffect(AuraApplication*, unsigned char, bool) ()
#9  0x0000555556669359 in AuraApplication::_HandleEffect(unsigned char, bool) ()
#10 0x00005555562110eb in Unit::_ApplyAura(AuraApplication*, unsigned char) ()
#11 0x000055555666d67e in Aura::_ApplyEffectForTargets(unsigned char) ()
#12 0x00005555565e24bb in Spell::HandleEffects(Unit*, Item*, GameObject*, unsigned int, SpellEffectHandleMode) ()
#13 0x00005555565e30f8 in Spell::DoSpellHitOnUnit(Unit*, unsigned int, bool) ()
#14 0x00005555565e16a1 in Spell::DoAllEffectOnTarget(TargetInfo*) ()
#15 0x00005555565eb63c in Spell::handle_immediate() ()
#16 0x00005555565e9070 in Spell::_cast(bool) ()
#17 0x00005555565e4d30 in Spell::prepare(SpellCastTargets const*, AuraEffect const*) ()
#18 0x00005555561fd4e8 in Unit::CastSpell(Unit*, unsigned int, TriggerCastFlags, Item*, AuraEffect const*, ObjectGuid)
    ()
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000555555f18ce4 in npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(Unit*) ()
#20 0x0000555555f1eec9 in CreatureAI::MoveInLineOfSight_Safe(Unit*) ()
#21 0x0000555556333aae in Acore::AIRelocationNotifier::Visit(GridRefMgr<Creature>&) ()
#22 0x0000555556250d7f in void Cell::Visit<Acore::AIRelocationNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >(CoordPair<512u> const&, TypeContainerVisitor<Acore::AIRelocationNotifier, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >&, Map&, float, float, float) const ()
#23 0x000055555624a225 in void Cell::VisitAllObjects<Acore::AIRelocationNotifier>(WorldObject const*, Acore::AIRelocationNotifier&, float, bool) ()
#24 0x00005555562404fe in Unit::UpdateObjectVisibility(bool) ()
#25 0x00005555561da1ac in Player::UpdateObjectVisibility(bool) ()
#26 0x000055555665e438 in AuraEffect::HandleEffect(AuraApplication*, unsigned char, bool) ()
#27 0x000055555666938c in AuraApplication::_HandleEffect(unsigned char, bool) ()
#28 0x0000555556211752 in Unit::_UnapplyAura(std::_Rb_tree_iterator<std::pair<unsigned int const, AuraApplication*> >&, AuraRemoveMode) ()
#29 0x0000555556214690 in Unit::RemoveAllAurasOnDeath() ()
#30 0x00005555562336a9 in Unit::setDeathState(DeathState, bool) ()
#31 0x00005555561387ca in Player::setDeathState(DeathState, bool) ()
#32 0x00005555561fb934 in Unit::Kill(Unit*, Unit*, bool, WeaponAttackType, SpellInfo const*, Spell const*) ()
#33 0x0000555555e07413 in misc_commandscript::HandleDieCommand(ChatHandler*) ()
#34 0x00005555559e1a11 in Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker<bool (ChatHandler*)>(bool (&)(ChatHandler*))::{lambda(void*, ChatHandler*, std::basic_string_view<char, std::char_traits<char> >)#1}::__invoke(void*, ChatHandler*, std::basic_string_view<char, std::char_traits<char> >) ()
#35 0x00005555560157f7 in Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand(ChatHandler&, std::basic_string_view<char, std::char_traits<char> >) ()
#36 0x000055555600d3d8 in ChatHandler::_ParseCommands(std::basic_string_view<char, std::char_traits<char> >) ()
#37 0x0000555556737c51 in WorldSession::HandleMessagechatOpcode(WorldPacket&) ()
#38 0x00005555564f99f6 in WorldSession::Update(unsigned int, PacketFilter&) ()
#39 0x00005555566ecd81 in World::UpdateSessions(unsigned int) ()
--Type <RET> for more, q to quit, c to continue without paging--
#40 0x00005555566e633d in World::Update(unsigned int) ()
#41 0x00005555559ab9c3 in WorldUpdateLoop() ()
#42 0x00005555559a6f05 in main ()

### AC rev. hash/commit

41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

Ubuntu 22.04

### Custom changes or Modules

None

**Comment by heyitsbench** [comment]
CC: @AGandrup
