### ISSUE TITLE
[Alterac Valley] Patrols do not patrol [$20]

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1758]
##### SMALL DESCRIPTION:
The patrol mobs for the factions currently stand still and do not move instead of patrolling their paths. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The patrol mobs should move along fixed waypoints.

[Example of Horde patrol pack (entering from left of screen)](https://youtu.be/MBg7EPuGixw?t=33)

Alliance patrols can be found near their end of the map, usually 2 dwarves and an owl. 

##### CURRENT BEHAVIOUR:
Patrol mobs stand still until engaged. 

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a character
2. Queue for Alterac Valley
3. Type `.debug bg`
4. Enter battle
5. Look at the previously mentioned mobs

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
b81c15762826b25d1aa269377ec3be29c1a2de9d

##### OPERATING SYSTEM:
Windows 10

**Comment by poszer** [comment]
Confirmed, need to add waypoints

**Comment by Helias** [comment]
I anyone knows the exact path of the NPCs we could easily add them

**Comment by FrancescoBorzi** [comment]
@Helias it would be hard to know the exact paths, you can check videos on YouTube to reverse-engineer it. Even if the paths are not 100% accurate, it's better than not patrolling at all.

**Comment by FALL1N1** [comment]
It's not just paths, the event is not scripted at all. I'm currently working on this and will post a commit for everyone to test here.
