### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by FireGolza1** [azerothcore/azerothcore-wotlk#17588]
### Current Behaviour

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/146747725/fabbc78f-351b-42c6-9318-ebcc8e7c4b51)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/146747725/84872069-b590-4930-a6f6-023f3d94e22d)

Not sure what is going wrong, but when I try to compile the Azerothcore (and Azerothcore-wotlk-with-NPCBots) code using boost 1.8.3 and the rest of the needed software on SQL 5.7, I get these errors. I have compiled it successfully a few months before. Are these caused by SQL 5.7 or something else?

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

1. Attempt to compile Azerothcore-wotlk-with-NPCBots (also failed on just Azerothcore) fresh on Windows 11 with Boost 1.8.3 and SQL 5.7

### Extra Notes

11>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\common\Threading\ProcessPriority.cpp(47,17): error C3861: 'LOG_ERROR': identifier not found
11>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\common\Threading\ProcessPriority.cpp(51,17): error C3861: 'LOG_INFO': identifier not found
11>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\common\Threading\ProcessPriority.cpp(55,17): error C3861: 'LOG_ERROR': identifier not found
11>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\common\Threading\ProcessPriority.cpp(64,13): error C3861: 'LOG_INFO': identifier not found
11>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\common\Threading\ProcessPriority.cpp(68,13): error C3861: 'LOG_ERROR': identifier not found
11>Tokenize.cpp
11>Util.cpp
11>Errors.cpp
11>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
11>- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
11>- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
11>Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).
11>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
11>- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
11>- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
11>Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).
11>Done building project "common.vcxproj" -- FAILED.

17>LINK : fatal error LNK1181: cannot open input file '..\..\common\RelWithDebInfo\common.lib'

16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.h(39,10): error C2039: 'optional': is not a member of 'std' (compiling source file C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp)
16>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\unordered_map(24,1): message : see declaration of 'std' (compiling source file C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp)
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.h(39,10): error C7568: argument list missing after assumed function template 'optional' (compiling source file C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp)
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.h(39,10): error C2062: type 'unknown-type' unexpected (compiling source file C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp)
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.h(39,37): error C2238: unexpected token(s) preceding ';' (compiling source file C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp)
16>AccountScript.cpp
16>AchievementCriteriaScript.cpp
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp(84,13): error C2039: 'orientation': is not a member of 'WaypointData'
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.h(35,8): message : see declaration of 'WaypointData'
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.cpp(147,13): error C2039: 'orientation': is not a member of 'WaypointData'
16>C:\Program Files\AzerothCore-wotlk-with-NPCBots\src\server\game\Movement\Waypoints\WaypointMgr.h(35,8): message : see declaration of 'WaypointData'

18>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
18>- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
18>- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
18>Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).

18>LINK : fatal error LNK1181: cannot open input file '..\game\RelWithDebInfo\game.lib'
18>Done building project "worldserver.vcxproj" -- FAILED.

========== Build: 15 succeeded, 4 failed, 0 up-to-date, 1 skipped ==========
========== Build started at 11:39 PM and took 04:17.268 minutes ==========

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/41dba1affbb5a24457a894bf3d503f4aa6303a1b

### Operating system

Windows 11 x64

**Comment by Kitzunu** [comment]
You are not using a clean AC. Turn to the author of npcbots

**Comment by Kitzunu** [comment]
Anyway it is not caused by eother boost or mysql. You have probably done something wrong with the setup.

Go back to the wiki and start over
