### ISSUE TITLE
[Alterac Valley] Stormpike Quartermaster's gossip options do nothing

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1759]
##### SMALL DESCRIPTION:
The gossip options for the Stormpike Quartermaster do nothing when clicked. (Excluding offered quests)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Gossip options should perform their functions.

##### CURRENT BEHAVIOUR:
Gossip options do nothing when clicked for [Stormpike Quartermaster](https://wowgaming.altervista.org/aowow/?npc=12096)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create an alliance character
2. Queue for Alterac Valley
3. Type `.debug bg`
4. Enter battle
5. Go to Dun Baldar
6. Speak to the Stormpike Quartermaster (under one of the tents)
7. Try gossip options

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
b81c15762826b25d1aa269377ec3be29c1a2de9d

##### OPERATING SYSTEM:
Windows 10

**Comment by poszer** [comment]
Confirmed. This also didn't work before
