### ISSUE TITLE
(Regression) Respawning creatures do not send location updates to the client

### ISSUE THREAD

**Issue by kjack9** [azerothcore/azerothcore-wotlk#17595]
### Current Behaviour

When creatures are respawned, they are returned to their correct starting positions. However, the client is not receiving a packet to inform them of this, making it appear as though they are still at the position where they died.

The example below makes use of `creature_formations` to trigger spawning but doing a `.respawn` on a dead creature will produce the same effect - all respawning seems to be affected.

I did a git bisect and found that this issue was introduced in commit 60e27511c530b0949fee361a89d3eb9d9f9125af (PR #17480)

### Expected Blizzlike Behaviour

Respawning creatures should immediately re-appear back at their starting position.

### Steps to reproduce the problem

- `.go xyz -11687.117188 -1968.376587 62.590042 309 4.137`
- `.gm off`
- pull the boss
- target both Zulian Tigers and do `.die`
- `.gm on`

Observe that the tigers appear to still be at the spots they died. Attempting to melee these creatures will result in a `You are too far away!` message.

- `.tel stormwind`
- `.go xyz -11687.117188 -1968.376587 62.590042 309 4.137`

Observe that the tigers are back in their cages.

### Extra Notes

This can be (badly, incorrectly) resolved for the reproduction case by adding:
```c++
            Position myHomePosition = pMember->GetHomePosition();
            pMember->NearTeleportTo(myHomePosition);
```
just after `pMember->Respawn();` in https://github.com/azerothcore/azerothcore-wotlk/blob/79b39f9655111088a741185c4dabd31dae7d85ea/src/server/game/Entities/Creature/CreatureGroups.cpp#L328-L330

That appears to generate the appropriate client update packet to have the tigers return to their starting positions.

### AC rev. hash/commit

Introduced in 60e27511c530b0949fee361a89d3eb9d9f9125af
Present in all commits after that.

### Operating system

Ubuntu 22.04

### Custom changes or Modules

None, fresh AC.

**Comment by heyitsbench** [comment]
CC: @AGandrup

**Comment by AGandrup** [comment]
> CC: @AGandrup

Yes, I'll fix it. God damn it.
Its the gift that keeps on giving. 🥴

**Comment by kjack9** [comment]
> > CC: @AGandrup
> 
> Yes, I'll fix it. God damn it. Its the gift that keeps on giving. 🥴

Sorry!

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/19712078/330470a3-80df-4e41-97d9-902ebf866edc)

**Comment by AGandrup** [comment]
> > > CC: @AGandrup
> > 
> > 
> > Yes, I'll fix it. God damn it. Its the gift that keeps on giving. 🥴
> 
> Sorry!
> 
> ![image](https://user-images.githubusercontent.com/19712078/278565757-330470a3-80df-4e41-97d9-902ebf866edc.png)
> 
> If it makes you feel any better, I _did_ try to fix it. Then I realized how out of my depth I was and created this Issue. =P
> 
> You mean throwing an extra teleport at the end of a respawn event isn't the right answer?!?

Haha, its fine. I broke it so I'll fix it too 😛 But ye, hopefully we're coming to an end with all these bugs soon.

**Comment by danqu** [comment]
I believe it's essential to retain the previous logic:

if (force)
{
    if (IsAlive())
        setDeathState(JUST_DIED);
    else if (getDeathState() != CORPSE)
        setDeathState(CORPSE);
}

if (getDeathState() == DEAD)
{
    ...
    setDeathState(JUST_RESPAWNED);
    ...
}
if (force)
{
    if (IsAlive())
        setDeathState(JUST_DIED);
    else if (getDeathState() != CORPSE)
        setDeathState(CORPSE);
}

if (getDeathState() == DEAD)
{
    ...
    setDeathState(JUST_RESPAWNED);
    ...
}
Both of these respawn methods should maintain the previous logic:

// xinef: relocate notifier, fixes npc appearing in corpse position after forced respawn (instead of spawn)
m_last_notify_position.Relocate(-5000.0f, -5000.0f, -5000.0f, 0.0f);

This ensures that NPCs always respawn at their initial positions.

**Comment by AGandrup** [comment]
This is an old hack, which should not be necessary anymore. The issue can also be fixed by calling creature->Relocate() outside of the if-else scope in Map::CreatureRelocation. But I am trying to figure if there is another way - i'm guessing it is something I missed.

**Comment by danqu** [comment]
I am currently unsure if there are other issues related to creature respawning. But, based on the issue mentioned here, I believe we can set the creature's position back to its initial location right before calling the  method. This way, when the  method is invoked, the creature will be reborn at its initial position.RespawnRespawn

void CreatureGroup::MemberEvaded(Creature* member)
{
    ...
    else
    {
        if (pMember->IsAlive())
        {
            continue;
        }

        if (itr.second.HasGroupFlag(std::underlying_type_t<GroupAIFlags>(GroupAIFlags::GROUP_AI_FLAG_DONT_RESPAWN_LEADER_ON_EVADE)) && pMember == m_leader)
        {
            continue;
        }

        // 设置生物回到初始化位置
        float initX, initY, initZ, initO;
        pMember->GetRespawnPosition(initX, initY, initZ, &initO);
        pMember->Relocate(initX, initY, initZ, initO);

        pMember->Respawn();
    }
    ...
}

**Comment by danqu** [comment]
"Perhaps it can be done this way:
Every time during the respawn, make sure it's always at the initial position.

void Creature::Respawn(bool force)
{
        //将生物的位置设置回其初始位置
    float initX, initY, initZ, initO;
    GetRespawnPosition(initX, initY, initZ, &initO);
    Relocate(initX, initY, initZ, initO);
    
    Of course, there might be better solutions, but this approach can temporarily address the current issue.

**Comment by AGandrup** [comment]
> "Perhaps it can be done this way: Every time during the respawn, make sure it's always at the initial position.
> 
> void Creature::Respawn(bool force) { //将生物的位置设置回其初始位置 float initX, initY, initZ, initO; GetRespawnPosition(initX, initY, initZ, &initO); Relocate(initX, initY, initZ, initO);
> 
> ```
> Of course, there might be better solutions, but this approach can temporarily address the current issue.
> ```

Yes, I was about to test the same thing. Probably the cleanest and most proper way right now

**Comment by danqu** [comment]
But we need to ensure that both  and  always return valid positions.GetRespawnPosition   Relocate

**Comment by kjack9** [comment]
> I am currently unsure if there are other issues related to creature respawning. But, based on the issue mentioned here, I believe we can set the creature's position back to its initial location right before calling the method. This way, when the method is invoked, the creature will be reborn at its initial position.

I think the solution needs to be wider than just CreatureFormation. I can trigger the same issue by doing a `.revive` on a dead creature that isn't in a formation.

Checking the position isn't going to work, I don't think. As far as the server is concerned the creature IS back at their starting position. It's the update to the client that isn't happening. So if I respawn a guy right in front of me he APPEARS to be within melee range, but trying to actually melee him gets an out-of-range message.

**Comment by AGandrup** [comment]
@kjack9 btw, when you discovered this, was it by doing force respawn or have you tried waiting for corpse to disappear and then the creature spawn as it normally would? The thing is, it looks like Creature::RemoveCorpse() takes care of calling CreatureRelocation with the respawn coordinates.

**Comment by kjack9** [comment]
> @kjack9 btw, when you discovered this, was it by doing force respawn or have you tried waiting for corpse to disappear and then the creature spawn as it normally would? The thing is, it looks like Creature::RemoveCorpse() takes care of calling CreatureRelocation with the respawn coordinates.

Happy to test that, let me get into an instance and find out for sure. I've always tested shortly after the creature died. Although with creature formation respawning that obviously never really happens - a reset boss instantly respawns linked creatures.

**Comment by AGandrup** [comment]
> > @kjack9 btw, when you discovered this, was it by doing force respawn or have you tried waiting for corpse to disappear and then the creature spawn as it normally would? The thing is, it looks like Creature::RemoveCorpse() takes care of calling CreatureRelocation with the respawn coordinates.
> 
> Happy to test that, let me get into an instance and find out for sure. I've always tested shortly after the creature died. Although with creature formation respawning that obviously never really happens - a reset boss instantly respawns linked creatures.

Ye true. The thing is, maybe the trick is just to move the logic from RemoveCorpse to Respawn method.

**Comment by danqu** [comment]
@kjack9 

You can try the following solution:
I believe it should address the issue you mentioned.

void Creature::Respawn(bool force)
{
        //将生物的位置设置回其初始位置
    float initX, initY, initZ, initO;
    GetRespawnPosition(initX, initY, initZ, &initO);
    Relocate(initX, initY, initZ, initO);
}

At least from my current testing, I've found that everything seems to be working correctly.

**Comment by kjack9** [comment]
> @kjack9
> 
> You can try the following solution: I believe it should address the issue you mentioned.
> 
> void Creature::Respawn(bool force) { //将生物的位置设置回其初始位置 float initX, initY, initZ, initO; GetRespawnPosition(initX, initY, initZ, &initO); Relocate(initX, initY, initZ, initO); }
> 
> At least from my current testing, I've found that everything seems to be working correctly.

So, correct me if I'm wrong, but isn't that just working around the issue? If the creature is being relocated correctly in the server, but not in the client, isn't this just covering up that issue by moving them again? Seems like the first move should be correctly updating the client rather than moving twice.

If I misunderstand, please let me know.

**Comment by AGandrup** [comment]
> @kjack9
> 
> You can try the following solution: I believe it should address the issue you mentioned.
> 
> void Creature::Respawn(bool force) { //将生物的位置设置回其初始位置 float initX, initY, initZ, initO; GetRespawnPosition(initX, initY, initZ, &initO); Relocate(initX, initY, initZ, initO); }
> 
> At least from my current testing, I've found that everything seems to be working correctly.

Yes it would work but still thinking if there is a better solution. The creature is already relocated server side, its just client side

**Comment by heyitsbench** [comment]
> You can try the following solution: I believe it should address the issue you mentioned.

In my humble opinion, that solution is very much a hackfix.

**Comment by kjack9** [comment]
Confirmed by at least one other tester on Discord:
https://discord.com/channels/217589275766685707/331552075278450690/1168075446559182918

**Comment by Day36512** [comment]
Can confirm issue as well, though it doesn't seem consistent.

**Comment by pklloveyou** [comment]
BOSS won't interact with little spiders
```.go xyz 529.64 574.32 777 601 ```
AND
At this coordinate for combat, the boss cannot complete the transmission correctly
```.go xyz 2714.5 -3492.2 263 533 ```

**Comment by AGandrup** [comment]
Feel free to test: https://github.com/azerothcore/azerothcore-wotlk/pull/17642

@pklloveyou teleport should be fixed. I am not sure what you mean with the spider boss - maybe you can elborate a bit more or provide a video?

**Comment by kjack9** [comment]
FYI - #17642 fixes the test case I provided in this issue. There is a short (500ms delay) between when I turn on GM mode and the tigers respawn in their cages, but it is well within acceptability IMO. Thanks for working on fixing this!
