### ISSUE TITLE
StartNetwork failed to bind socket acceptor

### ISSUE THREAD

**Issue by Sakuya-CN** [azerothcore/azerothcore-wotlk#17594]
![375ee5a73aa76aa329542cd0d664a86](https://github.com/azerothcore/azerothcore-wotlk/assets/56291932/6fc20499-5459-463f-88ac-354d0c8b5414)
When I start/ When acore. sh runs worldserver and authserver, the error 'StartNetwork failed to bind socket acceptor' will appear
Failed to initialize network "
What's going on

**Comment by heyitsbench** [comment]
The port it's using is already in use.

**Comment by Sakuya-CN** [comment]
ok this was a small mistake, I fixed it later, sorry
