### ISSUE TITLE
[Alterac Valley] Captain Galvangar is facing the wrong direction upon spawn

### ISSUE THREAD

**Issue by wetbrownsauce** [azerothcore/azerothcore-wotlk#1760]
##### EXPECTED BLIZZLIKE BEHAVIOUR:
Captain Galvangar should face the entrance of his keep, not the back wall.

##### CURRENT BEHAVIOUR:
[Captain Galvangar](https://wowgaming.altervista.org/aowow/?npc=11947) is facing the back wall of his keep when he initially spawns in. 

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a character
2. Queue for Alterac Valley
3. Type `.debug bg`
4. Enter battle
5. Go to Iceblood Garrison
6. Galvangar is facing the wrong way

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
b81c15762826b25d1aa269377ec3be29c1a2de9d

##### OPERATING SYSTEM:
Windows 10

**Comment by poszer** [comment]
@wetbrownsauce When you can also this one referenced, please :smiley:
