### ISSUE TITLE
worldcrash - unknown

### ISSUE THREAD

**Issue by jshplayer** [azerothcore/azerothcore-wotlk#17606]
### Current Behaviour

World server is crashing, this one is rare and we're unsure of trigger - we're just uploading it for viewing.

### Expected Blizzlike Behaviour

World server not to crash.

### Source

https://gist.github.com/jshplayer/fabaa16890adf985c7ca65b816684e12

### Steps to reproduce the problem

Unsure

### AC rev. hash/commit

23a620007b38c03368bac441e4fd91c585935c01

### Operating system

Debian 10

**Comment by heyitsbench** [comment]
Should be resolved with 79b39f9655111088a741185c4dabd31dae7d85ea. Please update your core.

**Comment by jshplayer** [comment]
Will do, we're only 1 commit behind but obviously she's an important one : )
