### ISSUE TITLE
worldcrash - brd

### ISSUE THREAD

**Issue by jshplayer** [azerothcore/azerothcore-wotlk#17605]
### Current Behaviour

Random world server crashes we believe are triggered during an Ironhand encounter.

### Expected Blizzlike Behaviour

World Server should not crash.

### Source

https://gist.github.com/jshplayer/6c8e7f16e01bdee50bd7e131c6f2e212

### Steps to reproduce the problem

1. Run a BRD instance, we're not yet seeing this consistently occur.

### AC rev. hash/commit

23a620007b38c03368bac441e4fd91c585935c01

### Operating system

Debian 10

### Custom changes or Modules

Autobalance and DungeonRespawn

**Comment by kissingers** [comment]
update this
79b39f9655111088a741185c4dabd31dae7d85ea

**Comment by jshplayer** [comment]
Have updated now just gauging whether this has resolved.
