### ISSUE TITLE
worldserver crash

### ISSUE THREAD

**Issue by slattyslattslatt** [azerothcore/azerothcore-wotlk#17619]
### Current Behaviour

https://gist.github.com/slattyslattslatt/8a557a7d8645b5c51f72a7219a5b4d46

### Expected Blizzlike Behaviour

-

### Steps to reproduce the problem

everything is fine but when i tried to add much more bots in the db as wanderingnpcbots around the world (over 300) the worldserver crashes sometimes

### AC rev. hash/commit

de00b639b3247098cf809ac038b227181443fa06

### Operating system

Windows 10

### Custom changes or Modules

ah-bot
1vs1 arena
npcbots
instance-reset
random enhancements
autobalance
soloLFG
transmog

**Comment by Nyeriah** [comment]
Open an issue in the module repository
