### ISSUE TITLE
[Auction] Items disapear after auction creation

### ISSUE THREAD

**Issue by Revan2107** [azerothcore/azerothcore-wotlk#17631]
### Current Behaviour

After creating an auction + relog items in bag disappear. Tried to reproduce few times, happened once for me.

**Bug recorded by some player**: https://www.dropbox.com/scl/fi/f89pwyw60o5c80xf67cs3/IMG_1123.mov?rlkey=ownpw1w2jgvjfsgwd51arvq3v&dl=0

**Bug reproduced and recorded by me**: https://youtu.be/ZAd-tAT6Vpc
**Tried to record a bug without noises during the recording and coudn't reproduce**: https://youtu.be/CGS7nC-bl7Q

### Expected Blizzlike Behaviour

If you create a batch of auctions (for example sell 5 Eternal Belt Buckle out of 7 you have in bags) items shouldn's disappear after relog.

### Steps to reproduce the problem

1. Exit the game and enter back.
2. Add 7 Eternal Belt Buckle to your inventory. Use `.additem 41611 7`.
3. Go to any auction house.
4. Create auction for 5 stacks of Eternal Belt Buckle (1 item per each stack) out of 7 you have in inventory. Set the same value for start price and buyout.
5. After you verify auctions were created go outside of auction house and relog the character.
6. Verify you don't have rest 2 Eternal Belt Buckle in your inventory.

### AC rev. hash/commit

AzerothCore rev. a099059cc793+ 2023-10-31 17:26:42 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 128. Characters in world: 120.
Connection peak: 133.
Server uptime: 3 hour(s) 34 minute(s) 45 second(s)
Update time diff: 28ms, average: 23ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80035
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-87-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azerothcore/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azerothcore/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS koKR zhCN zhTW
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-cfbg
- mod-congrats-on-level
- mod-duel-reset
- mod-globalchat
- mod-transmog

### Operating system

Ubuntu 22.04.2 LTS

### Custom changes or Modules

- mod-cfbg
- mod-congrats-on-level
- mod-duel-reset
- mod-globalchat
- mod-transmog

**Comment by Kitzunu** [comment]
Possibly resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/17644 ? 

Could you please test

**Comment by Kitzunu** [comment]
Test the PR I linked

**Comment by Revan2107** [comment]
Fixed
