### ISSUE TITLE
(Instance/IcecrownCitadel): Sindragosa's Unchained Magic has possibly incorrect proc behavior.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#17664]
### Current Behaviour

Currently, if you cast a spell with a cast time (such as Shadow Bolt) while afflicted with Unchained Magic, and cast an instant cast spell (such as Corruption) at the end of the cast of Shadow Bolt, you will get two stacks of Instability.

### Expected Blizzlike Behaviour

Casting an instant cast spell at the same time as a cast time spell finishes casting should only proc one stack of Instability.

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.learn 686`, `.learn 172`
2. Engage Sindragosa.
3. Wait until you are afflicted with Unchained Magic.
4. Cast Shadow Bolt.
5. As it finishes casting, cast Corruption.
6. Observe two stacks of Instability.

### Extra Notes

Hunted for retail Wrath videos of casters casting an instant cast after a cast time spell, but came up empty handed.

### AC rev. hash/commit

e80c23974d2a2ee63b3094e001a91ff4bee69a53

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Nyeriah** [comment]
Does the same happen with other spells? Corruption isn’t particularly an instant cast spell if I remember correctly

**Comment by heyitsbench** [comment]
> Does the same happen with other spells?

The behavior in my experience (both in AC/Classic behavior) seems to be global across any cast time/instant spell, Shadow Bolt/Corruption were just examples here.

**Comment by avarishd** [comment]
Side note, instability damage scales with the ICC buff.

**Comment by heyitsbench** [comment]
Forgot about it in the original report, channeled spells (such as Penance, Drain Soul, Drain Life, etc) in this situation behave the same way as instant cast spells, as their Instability proc is at the moment the channel starts.
