### ISSUE TITLE
[Alterac Valley] Creatures Frostwolf's and Alterac Ram's faction

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#1766]
Frostwolfs and Alterac Ram creatures faction

##### SMALL DESCRIPTION:

The previous report was wrong. Everything is updated now

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should have same factions like Guards in Alterac (For Horde/Alliance). So while the player for first time enter in bg they will see them as Neutral until he get reputation to friendly. Also, the creatures who are friendly with Alliance should attack Horde players on spot. Same for the creatures who are friendly with Horde, should attack Alliance players on spot. 

##### CURRENT BEHAVIOUR:

Creatures are all time Neutral for Both Factions. Also, if the Horde/Alliance walk near opossite creatures, the creatures doesn't attack players. Which is wrond. They should always attack opossite players.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create both faction characters
2. Enter in Alterac Valley Battleground
3. Walk near these Creatures (The wolfs should attack alliance / Rams should attack hordes)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
 80c2025cd9a250a215849f3c79a4ea037706cde3

**Comment by comix1988** [comment]
I have not found any information that confirms that these 2 mobs become friendly when we increase our reputation.
![ram](https://user-images.githubusercontent.com/22867608/56814790-2afe1100-6840-11e9-97c9-3e25460a06f9.png)

![ram2](https://user-images.githubusercontent.com/22867608/56814997-8defa800-6840-11e9-9427-8cef294f1295.png)


![wolf](https://user-images.githubusercontent.com/22867608/56814798-2df90180-6840-11e9-8424-60dec4ba4ddc.png)

can you link to me where I can find this information? @poszer

**Comment by poszer** [comment]
> I have not found any information that confirms that these 2 mobs become friendly when we increase our reputation.
> ![ram](https://user-images.githubusercontent.com/22867608/56814790-2afe1100-6840-11e9-97c9-3e25460a06f9.png)
> 
> ![ram2](https://user-images.githubusercontent.com/22867608/56814997-8defa800-6840-11e9-9427-8cef294f1295.png)
> 
> ![wolf](https://user-images.githubusercontent.com/22867608/56814798-2df90180-6840-11e9-8424-60dec4ba4ddc.png)
> 
> can you link to me where I can find this information? @poszer

https://github.com/azerothcore/azerothcore-wotlk/pull/1761#issuecomment-486478828

**Comment by poszer** [comment]
But yes, there was actually problem. @wetbrownsauce share wrong informations about these creatures. They should be both on faction 7 (Creature). 
@Knindzagxg tested it on blizz, and confirm that 7 is correct. The PR is updated. Thanks everyone :heart_eyes:
