### ISSUE TITLE
Feature: Use custom race by Naga,there has some wrong with tail skin.

### ISSUE THREAD

**Issue by Blandyoung** [azerothcore/azerothcore-wotlk#17679]
### Describe your feature request or suggestion in detail

When I treated Naga as a player race, its tail texture was incorrect. 

I have tried many solutions that cannot be fixed. 

But npc's racial skin can be displayed correctly.

**Comment by Kitzunu** [comment]
Not supported and likely something to do clientside

**Comment by Blandyoung** [comment]
I have resolved this issue and it is indeed related to the client。

Due to the fact that this race was not considered for player creation, the texture needs to be remade
