### ISSUE TITLE
CI: MacCI broken

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#17687]
### Current Behaviour

```
CMake Error at /usr/local/Cellar/cmake/3.27.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system filesystem
-- Configuring incomplete, errors occurred!
  program_options iostreams regex) (Required is at least version "1.67")
```
> https://github.com/azerothcore/azerothcore-wotlk/actions/runs/6837061159/job/18592632541

We install `boost@1.76` without issues

Maybe mac build is just broken?

### Expected Blizzlike Behaviour

Pass build

### Steps to reproduce the problem

See CI

### AC rev. hash/commit

649dc84feac60ae4f8d4051a9d86cf0f657a844b

### Operating system

macOS 11/12

**Comment by kam92** [comment]
I had some issues with boost path in macbook M1 chips. My old one (with intel) works just fine.
