### ISSUE TITLE
[Class/Death Knight]: Army of the Dead aggro

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#1768]
Death Knight: Army of the Dead aggro

##### SMALL DESCRIPTION:

These summoned pet's shouldn't take aggro in this way.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

While using this spell to summon Army of the Dead, once they are summoned and you are attacking someone, they instantly taking aggro. (It's posible sometimes, but player can easy to take aggro again)

##### CURRENT BEHAVIOUR:

When you fight some creature, and you summon this Army of the Dead, they re instantly taking aggro at self, and they attacking so fast (You can check it by watching in the creature who's attacked, he's looking like without head, he doesn't know where to attack :rofl: ). Also, the player are not able to return aggro even if you do abnormal damage (GM spells from commands), until they re despawned. Which is totally wrong! The Player should be able to get aggro back easy in fight. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create Death Knight (Get best gear and everything)
2. Go and fight any creature which is higher level
3. In the middle of the fight summon Army of the Dead (SPELL 42650)
4. They will instantly take aggro, and you can't get it back until they re despawned.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
80c2025cd9a250a215849f3c79a4ea037706cde3

##### OPERATING SYSTEM:

Windows 8

##### MODULES:
 No

##### OTHER CUSTOMIZATIONS:
 No

**Comment by sucofog** [comment]
Confirmed, ghouls just take aggro instantly when summoned by spell, this can be critical since if a player is tanking a 25 man raid and ghouls take aggro, whole raid can wipe due to this

**Comment by Razfury** [comment]
This is a blizzlike feature - The only time they don't "taunt" is in raids 10/25 doesn't matter.

**Comment by Razfury** [comment]
@poszer

**Comment by poszer** [comment]
> @poszer

Yeah, i checked day ago. Anyway thanks for info (But also it should be tested in the raids). Just to be sure, if this happens also on bosses, than it's incorrect

**Comment by poszer** [comment]
**Info** :  Need checks in raids / If they don't taunt in raids, this issue can be closed.

**Comment by poszer** [comment]
It's fine in raids. Closing this
