### ISSUE TITLE
CI: noPCH CI build don't actually fail when nopch is broken

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#17688]
### Current Behaviour

All our builds run a nopch setup

```
* Build core w/PCH                : No
* Build scripts w/PCH             : No
```

But even then sometimes we encounter that the nopch build is broken, whilst all CI's still pass. See https://github.com/azerothcore/azerothcore-wotlk/issues/17610 (Mentioned issue was fixed https://github.com/azerothcore/azerothcore-wotlk/commit/52d37a927dc921785fcac35bd8830221299495c7)

(Also we probably should have one CI running PCH 🤷 

### Expected Blizzlike Behaviour

CI should fail when nopch build fails.

### Steps to reproduce the problem

See previous issue where nopch build fails on personal PC's, but pass on CI

### AC rev. hash/commit

52d37a927dc921785fcac35bd8830221299495c7

### Operating system

All of the above

**Comment by sudlud** [comment]
I feel like this got fixed in the meantime? I'm quite sure that CI checks get marked as "failed" / red cross now, if any of the pch / nopch checks fails.

**Comment by Kitzunu** [comment]
Easily tested. Revert https://github.com/azerothcore/azerothcore-wotlk/commit/52d37a927dc921785fcac35bd8830221299495c7 in a PR and see if the CI fails :D

**Comment by sudlud** [comment]
revertet 52d37a9 in #19196 

nopch failed as expected:
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/9701355412/job/26774833093?pr=19196

**Comment by Kitzunu** [comment]
You sure? PCH fails at the same thing https://github.com/azerothcore/azerothcore-wotlk/actions/runs/9701355399/job/26774832609

and the original error was
```
/mnt/raid0/wow_server/azerothcore/src/server/game/Movement/Waypoints/WaypointMgr.h:39:10: fatal error: no template named 'optional' in namespace 'std'
  std::optional<float> orientation;
  ~~~~~^
  ```
