### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#177]
when compiling with cmake in 32 bits I get the following error:
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
Running cmake hook: AFTER_WORLDSERVER_CMAKE
No hooks registered for AFTER_WORLDSERVER_CMAKE
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD

programs:
*Openssl 1.02h x32 
*mysql 5.5.11 x32 + library 
*VS 14 (2015) 
## *cmake v3.6.2 32x

SO: Windows Server 2008 R2
##

**Comment by talamortis** [comment]
have you downloaded the required files from the Wiki?

**Comment by Sworken** [comment]
all my friend

**Comment by talamortis** [comment]
Did you manually add mysql path to the mysql developement files?

**Comment by Sworken** [comment]
yes

**Comment by Sworken** [comment]
I've tried everything, but I can not compile

**Comment by talamortis** [comment]
@Sworken do you have access to gitter? if so pm me and i will help compile.

**Comment by Dude100** [comment]
and how to slow this ?

**Comment by Rochet2** [comment]
Are these even errors? I mean, I get them too, but they look more like info messages than warnings or errors.

The cmake errors do not prevent from running cmake (configure & generate) and the sln is generated fine. Then compiling can also be done and succeeds for me.
