### ISSUE TITLE
Many Smart_scripts are missing in BRD 

### ISSUE THREAD

**Issue by Seebaby** [azerothcore/azerothcore-wotlk#1770]
SMALL DESCRIPTION:

In BRD almost no NPC casts what is missing many smart_Scripts

I found this link from trinitycore where many npc fixes are included if the 100% are correct I don't know 
https://github.com/TrinityCore/TrinityCore/issues/22104

BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

####### MODULE:
mod-transmog
mod_world_chat

**Comment by Knindzagxg** [comment]
Can cofirm.

Checked SQL, looks good as well.
Applied and no issues at all.

**Comment by poszer** [comment]
> Can cofirm.
> 
> Checked SQL, looks good as well.
> Applied and no issues at all.

Thank you @Seebaby for sharing and @Knindzagxg for testing. Will create PR with this query :+1:
