### ISSUE TITLE
BRD The seven minibosses don't work properly

### ISSUE THREAD

**Issue by Seebaby** [azerothcore/azerothcore-wotlk#1772]
###### SMALL DESCRIPTION:
The seven minibosses don't work properly miniboss doomrel should be the last to start the attack and also stop the event. and the chest spawns wrong too.

Loot Chest fix for Position

REPLACE INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES (67872, 169243, 230, 0, 0, 1, 1, 1266.18, -285.451, -78.2193, 3.93, 0, 0, 0.909298, 0.416147, -300, 100, 1, '', 0);

Offi Video https://youtu.be/GR_CQ-eC6ns?t=1380

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The order of the event is wrong.

Events start Boss Doomrel ID 9039

1 attacker is Anger'rel ID 9035
2 attacker is Seeth'rel ID 9038
3 Attacker is Dope'rel ID 9040
4 Attacker is Gloom'rel ID 9037
5 attacker is Vile'rel ID 9036
6 attacker is Hate'rel ID 9034
7 attacker is Doom'rel after his death spawnt the chest and the doors go back to ID 9039

the chest spawnt next to the door see video

##### CURRENT BEHAVIOUR:
1 attacker is Doom'rel ID 9039
2 Attacker is Dope'rel ID 9040
3 attacker is Hate'rel ID 9034
4 Attacker is Vile'rel ID 9036
5 attacker is Seeth'rel ID 9038
6 attacker is Gloom'rel ID 9037
7 attacker is Anger'rel D 9035

##### STEPS TO REPRODUCE THE PROBLEM:
.go creature 91020 and start the event.

##### BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
mod transmog
mod_world_chat

**Comment by Pondaveia** [comment]
Thanks for feedback 👍
