### ISSUE TITLE
Bug Report: Issue with Quest  Kaw the Mammoth Destroyer ( ID : 11879 )

### ISSUE THREAD

**Issue by Tilenozz** [azerothcore/azerothcore-wotlk#17746]
### Current Behaviour

Dear Development Team,

I've encountered a critical issue that prevents the successful completion of a particular quest involving the Bull Mammoth encounter. Specifically, there seems to be a bug in the sequence when mounting the Bull Mammoth and engaging Moria, leading to an unintended reset of Kaw's behavior.

When mounting one of the Bull Mammoths and subsequently defeating Moria, there's an unexpected behavior of Kaw, he reset. Instead of this sequence, it would be more fitting for Kaw to dismount and initiate an attack against the player. Upon Kaw's defeat, the quest item should then be lootable from their corpse.

Thanks

### Expected Blizzlike Behaviour

When mounting one of the Bull Mammoths and subsequently defeating Moria, there's an unexpected behavior of Kaw, he reset. Instead of this sequence, it would be more fitting for Kaw to dismount and initiate an attack against the player. Upon Kaw's defeat, the quest item should then be lootable from their corpse.

### Steps to reproduce the problem

1 - Get the quest 11879
2 - go to location : Map 571 , Zone 3537 , Area 3537  ZoneX 54.341919 , ZoneY: 29.053354 , GroundZ: 29.903205 , Floor Z: 29.903208
3 - Get a mammoth and start figth Moria

### AC rev. hash/commit

AC> AzerothCore rev. 76f4a0928df4 2023-11-09 22:02:14 +0100 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 3. Characters in world: 3.
Connection peak: 3.
Server uptime: 3 minute(s) 55 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80035
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-88-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/wowserver/azeroth-server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/wowserver/azeroth-server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/wowserver/azeroth-server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: recruit_info.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-congrats-on-level
- mod-recruit-friend
- mod-transmog

### Operating system

Ubuntu

**Comment by Dr-Arayashiki** [comment]
the quest item is looted from the ax he drops, not the corpse. Here is the solution for that if you want to try : https://github.com/azerothcore/azerothcore-wotlk/pull/17859
