### ISSUE TITLE
bug(Core/Quest): Having an item id of 0 in quest rewards breaks following rewards.

### ISSUE THREAD

**Issue by AnchyDev** [azerothcore/azerothcore-wotlk#17740]
### Current Behaviour

If you have a quest template with 3 rewards, but there is an empty reward between them; not all rewards are rewarded even though you can see it in the quest reward frame.

Example:
| RewardItem1 | RewardItem2 | RewardItem3 | RewardItem4 |
|- |-|-|-|
| 37711 | 37711| 0 | 37711|

Only the first 3 are iterated since there is 3 rewards counted in the core.

### Expected Blizzlike Behaviour

All items should be rewarded regardless whether there is an empty slot in between rewards.

### Source

Not really a blizzlike issue if your quests are made properly.

### Steps to reproduce the problem

1. Create or find a quest in `quest_template`.
2. Setup the 4 `rewardItemN` fields and set the 3rd one to a 0.
3. Complete the quest ingame and observe that only the first two items are rewarded.

### Extra Notes

The reason this happens is because when quests are loaded from the `quest_template` in the database these 4 fields are iterated and a counter is increased for every valid item. 

When the core rewards the player for completing the quest [it uses this counter](https://github.com/azerothcore/azerothcore-wotlk/blob/c8cfec6794effc7a96aaa64487c3d38310fffd0d/src/server/game/Entities/Player/PlayerQuest.cpp#L488) to count up from the first slot. So if you have 3 valid rewards (valid, valid, invalid, valid) you are rewarded as (iterated, iterated, iterated, not iterated).

This is fixable by changing [this line](https://github.com/azerothcore/azerothcore-wotlk/blob/c8cfec6794effc7a96aaa64487c3d38310fffd0d/src/server/game/Entities/Player/PlayerQuest.cpp#L488) to use `QUEST_REWARDS_COUNT` to iterate over all items instead of just the reward counter. The line above can stay the same as it just checks whether there is a reward available.

### AC rev. hash/commit

c8cfec6794effc7a96aaa64487c3d38310fffd0d

### Operating system

Windows 11 x64

### Custom changes or Modules

No changes.

**Comment by natrist** [comment]
I'm not familiar with quest design but what exactly is an empty reward? 🤔

**Comment by AnchyDev** [comment]
> I'm not familiar with quest design but what exactly is an empty reward? 🤔

When you setup a quest template you have the option to have 4 items as a reward (excluding the other rewards, ignore that for now). By default these fields are 0 so the core knows there is no rewards. If you populate these fields then the core will count each field that does not have a 0 and increase an internal counter for that quest which we will call `rewardCount`. This becomes a problem later because if you have your rewards in the database in this order: `rewardItem1: 37711, rewardItem2: 37711, rewardItem3: 0, rewardItem4: 37711` then the counter is increased to 3 (which makes sense right? there are 3 rewards) but when the RewardQuest co-routine is called it will use the `rewardCount` counter to reward the items which means it will only loop through each reward slot 3 times (rewardItem1-3) but the 3rd reward was actually on the fourth slot so it is skipped. This is not a problem if you have all your rewards in consecutive order like a normal person but this is an issue we noticed on our server that if you don't have it in consecutive order the core will still show the reward in the quest but it won't reward it.

**Comment by natrist** [comment]
Thank you, I will investigate this.
