### ISSUE TITLE
BRD Magmus fight doesn't go right

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1774]
SMALL DESCRIPTION:

After lighting the 2 shadowforge brazier in The Lyceum magmus should say a text it doesn't. If you go around you can already see the guards using their flamethrowers this should only be the case in Fight against Magmus and stop who this death is.

EXPECTED BLIZZLIKE BEHAVIOR:
After lighting the 2 shadowforge brazier in The Lyceum magmus should say a text.
If you attack Magmus, the guards become active and turn on the flamethrowers. When Magmus is dead, the guards go out again.

Video: https://youtu.be/GR_CQ-eC6ns?t=1824

CURRENT BEHAVIOUR:
There is no text from Magmus when you have lit the coal basins.
The guards shoot takes their flames but they don't do any harm and are directed upwards this should flood the room in front of them and not warm the ceiling.

STEPS TO REPRODUCE THE PROBLEM:
.go creature magmus
Open Fight 

BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by Pondaveia** [comment]
Can you check if the doors are already open before lighting the braziers?

**Comment by Seebaby** [comment]
No, the doors are closed only when both carbon pools are lit, the doors open without a problem.

**Comment by JamesGent** [comment]
Can confirm fire does no damage and Magmus is silent. Flames do flood the floor now but still no dmg.

![Desktop 28-11-2020 17-15-33-917](https://user-images.githubusercontent.com/61194190/100521750-56c04600-319d-11eb-95b0-12c68724cb3e.png)
