### ISSUE TITLE
Worldserver Segfault on "character check" command

### ISSUE THREAD

**Issue by moterpent** [azerothcore/azerothcore-wotlk#17771]
### Current Behaviour

When issuing the "character check bag" command worldserver segfaults.

### Expected Blizzlike Behaviour

Command should run and return character bank data.

### Steps to reproduce the problem

1. Start worldserver and wait for command prompt
2. Issue command "character check bank" command.

### Extra Notes

Rocky Linux 9.2.
OpenSSL 3.0.7
Boost 1.75.0
AzerothCore rev. b6cb8a572c69 2023-11-16 01:00:30 +0000 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

### AC rev. hash/commit

b6cb8a572c69

### Operating system

Rocky Linux 9.2

**Comment by heyitsbench** [comment]
Please attach a crash log.

**Comment by Kitzunu** [comment]
Cannot reproduce on d948a488c
