### ISSUE TITLE
Ulduar Salvaged Siege Engine vehicle problem

### ISSUE THREAD

**Issue by brussens** [azerothcore/azerothcore-wotlk#1778]
##### SMALL DESCRIPTION:

In the Ulduar, if the second player sit in the [Salvaged Siege Engine](https://www.wowhead.com/npc=33060/salvaged-siege-engine), the person does not display a vehicle, in consequence of the check can not get out of the machine.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Sit 1st player in Salvaged Siege Engine
2. Sit 2nd player in Salvaged Siege Engine
3. See vehicle of 2nd player

##### BRANCH(ES):

master

**Comment by comix1988** [comment]
already reported here https://github.com/azerothcore/azerothcore-wotlk/issues/1317
