### ISSUE TITLE
BRD Emperor Dagran Thaurissan does not say his texts there is only one text available

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1779]
SMALL DESCRIPTION:
Emperor Dagran Thaurissan does not say his texts there is only one text available

EXPECTED BLIZZLIKE BEHAVIOR:
The texts he should have said are mob dependent groups see video

Fighting senate
They were just getting in the way anyways.
Is that the best you can do? Do you really expect that you could defeat someone as awe inspiring as me?
Ha! You can't even begin to imagine the futility of your efforts.
Your efforts are utterly pointless, fools! You will never be able to defeat me!
After killing the Shadowforge Senate
Thank you for clearing out those foolish senators. Now prepare to meet your doom at the hands of Ragnaros' most powerful servant.
Aggro
I will crush you into little tiny pieces!
Aggro (Trash mobs alive)
Come to aid the Throne!
Killing a player
Hail to the king, baby!

Video: https://www.youtube.com/watch?v=GR_CQ-eC6ns&feature=youtu.be&t=1824
https://wow.gamepedia.com/Dagran_Thaurissan

CURRENT BEHAVIOUR:
When you pull denboss, he just says a text.

Come to aid the Throne!

STEPS TO REPRODUCE THE PROBLEM:
.go creature 47613
pull Boss

BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by Pondaveia** [comment]
Thanks for feedback again 👍

**Comment by Pondaveia** [comment]
Did you test if the boss pulls adds on aggro?

**Comment by Seebaby** [comment]
I have made a video of how it is currently running in the instance and what is said that can be compared with the video as it should actually be.

https://www.youtube.com/watch?v=pczkvwng5nc AC Core 

https://www.youtube.com/watch?v=GR_CQ-eC6ns&feature=youtu.be&t=1824 Original

**Comment by Voxstrasza** [comment]
Confirmed, still a problem as of `221f33b5b7af`
