### ISSUE TITLE
Crash# Strand of Ancients

### ISSUE THREAD

**Issue by franklampardahar** [azerothcore/azerothcore-wotlk#178]
when win the strand of ancient bg worldserver crashed and stop working. 
i test it only when i get Bg quests on dalaran and join strand bg . after crash i join without quest and when start Server get crash. 

this is my crash log on crashes folder of server release :
[unknown_worldserver.exe_[16-10_23-48-42].txt](https://github.com/azerothcore/azerothcore-wotlk/files/532101/unknown_worldserver.exe_.16-10_23-48-42.txt)

**Comment by talamortis** [comment]
crash log is useless, please compile as debug mode, are u using any moduals?

**Comment by franklampardahar** [comment]
@talamortis  i compile as debug mode and server not crashed . tnx

**Comment by talamortis** [comment]
np but if it crashes again please submit the debug crash log :)

**Comment by franklampardahar** [comment]
@talamortis okay dear :)
