### ISSUE TITLE
Kologarn in Ulduar Casts Petrifying Breath too early

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1781]
Kologarn in Ulduar Casts Petrifying Breath too early

##### SMALL DESCRIPTION:

Kologarn in Ulduar Casts Petrifying Breath as soon as he is pulled, this needs a delay else it causes a raid wipe.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Kologarn in Ulduar has a small delay before casting Petrifying Breath as soon as he is pulled

##### CURRENT BEHAVIOUR:

Kologarn in Ulduar Casts Petrifying Breath as soon as he is pulled, this needs a delay else it causes a raid wipe.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Attack kologarn in ulduar

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

15ffcc65aa1e5f59df3839203f190e55f78b8bd2

##### OPERATING SYSTEM:

ubuntu 16.04

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Pondaveia** [comment]
https://wowwiki.fandom.com/wiki/Kologarn

> - NOTE: This is cast when the aggro target is not in melee range, and typically means a raid wipe.

Did you test this with a meele character?

**Comment by disclosurez** [comment]
> https://wowwiki.fandom.com/wiki/Kologarn
> 
> > * NOTE: This is cast when the aggro target is not in melee range, and typically means a raid wipe.
> 
> Did you test this with a meele character?

Yes, same issue occured it seems that his pull range is too wide for petryfying breath

**Comment by Naxxramas-Server** [comment]
Yes i confirm the bug , Kologarn shouldn't use this ability on pull

**Comment by Pondaveia** [comment]
@disclosurez we should add a check if the encounter started 5 seconds ago not to cast [this spell](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp#L477)

Something like
``` C++
events.ScheduleEvent(EVENT_BREATH_READY, 5000);

case EVENT_BREATH_READY:
    breathReady = true;
    break;

if (breathReady)
    me->CastSpell(me->GetVictim(), SPELL_PETRIFYING_BREATH, false);
```

I can commit this later when I get home, should be a quick fix. Even though It would be nice to check how many seconds it takes for it to become valid.
