### ISSUE TITLE
ObjectGridUnloader  crash

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#17816]
### Current Behaviour

https://gist.github.com/boom8866/337dab3fab7cb4ce82ea020df850d3b9

 Creature::~Creature (this=0x7f9737021000) at /home/ubuntu/SSDdisk/azerothcore2023-10/src/server/game/Entities/Creature/Creature.cpp:249
 ObjectGridUnloader::Visit<Creature> (this=<optimized out>, m=...) at /home/ubuntu/SSDdisk/azerothcore2023-10/src/server/game/Grids/ObjectGridLoader.cpp:228
 VisitorHelper<ObjectGridUnloader, Creature> (v=..., c=...) at /home/ubuntu/SSDdisk/azerothcore2023-10/src/common/Dynamic/TypeContainerVisitor.h:44
r<ObjectGridUnloader, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (v=..., c=...) at /home/ubuntu/SSDdisk/azerothcore2023-10/src/common/Dynamic/TypeContainerVisitor.h:50

### Expected Blizzlike Behaviour

Unknown issue

### Source

Unknown issue

### Steps to reproduce the problem

Unknown issue

### Extra Notes

Unknown issue

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a286bc55bdbade2b7c5f126685b0349ca4caff08

### Operating system

debian 11

### Custom changes or Modules

hardmode
Anticheat
breakingnews
mod-zone-difficulty

**Comment by Nyeriah** [comment]
The revision you posted in your issue isn’t the revision your core is using, so, please update your core
