### ISSUE TITLE
Finishing Random Heroic Does not always reward emblems, sometimes gives deserter also

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1782]
Finishing Random Heroic Does not always reward emblems, sometimes gives deserter also

##### SMALL DESCRIPTION:

Finishing Random Heroic Does not always reward emblems, sometimes gives deserter also

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Finishing Random Heroic Does gives emblems everytime a random rhc is completed

##### CURRENT BEHAVIOUR:

Finishing Random Heroic Does not always reward emblems, sometimes gives deserter also

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start random heroic with 5 members
2. 1 Person leaves group from that 5 members
3. New person join group
4. Complete RHC
5. All members get deserter buff after RHC is completed and no emblems are awarded

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

15ffcc65aa1e5f59df3839203f190e55f78b8bd2

##### OPERATING SYSTEM:

Ubuntu 16.04 LTS

##### MODULES:

no

##### OTHER CUSTOMIZATIONS:

no

**Comment by nerows** [comment]
lfg not working good.

**Comment by poszer** [comment]
> lfg not working good.

How you mean, can you explain?

**Comment by disclosurez** [comment]
So I think I figured why you dont get the emblem for finishing the dungeon. What ever causes you to get deserter is not flagging the dungeon done so you get the debuff and no emblem.

**Comment by BarbzYHOOL** [comment]
> > lfg not working good.
> 
> How you mean, can you explain?

it's clear "not working good", now fix it.

**Comment by Voxstrasza** [comment]
@FrancescoBorzi I don't have the means to test this as I don't have a public server anymore, but back in Feburary-March 2020 this did happen a few times.

**Comment by Kitzunu** [comment]
I will close this as there has not been another report for this in 3 years
