### ISSUE TITLE
Fix Crossfaction Battleground & Arena Bug [$20 awarded]

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1783]
Fix Crossfaction Battleground Module and the Associated Horde Arena Bug

##### SMALL DESCRIPTION:

Take the following commits and produce crossfaction BG.diff or module based into Azerothcore:

https://github.com/Viste/Outlandcore/commit/e83c10bd5eb38bb050d748a3c3616e7498e3a9e7
https://github.com/Viste/Outlandcore/commit/1710d998b644a14f36681f77b2de9c24b318c942
https://github.com/Viste/Outlandcore/commit/b860c934f677fe417538729be426babff21dce39
https://github.com/Viste/Outlandcore/commit/5ccc2aa2f113c32f326a04f6976cd4258939f93e
https://github.com/Viste/Outlandcore/commit/a81ea50852edde6e4e297635ca48ba5bfe521d0a
https://github.com/Viste/Outlandcore/commit/05557152e54bd30471a872fb679f9490d8d8bb77
https://github.com/Viste/Outlandcore/commit/5c359107b5074757348cee2baaecda9cc7db9331

Also fix this issue with Arena
https://github.com/Viste/Outlandcore/issues/1

##### CURRENT BEHAVIOUR:
Crossfaction needs to be released as a proper .diff or a module in Azerothcore
This issue also needs fixing:
https://github.com/Viste/Outlandcore/issues/1

**Comment by Winfidonarleyan** [comment]
Done

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan which commit fixed the issue?

**Comment by disclosurez** [comment]
> 
> 
> @Winfidonarleyan which commit fixed the issue?

Private release

**Comment by poszer** [comment]
> > @Winfidonarleyan which commit fixed the issue?
> 
> Private release

If it's private than you should ask private, not posting it on AC issues.

**Comment by FrancescoBorzi** [comment]
@disclosurez @Winfidonarleyan 

I cannot force people to share their custom modules. However Bountysource is meant to sponsor **open source** software and it can **not** be used as a public market where to buy/sell private code like it just happened here.
