### ISSUE TITLE
worldserver crash - assertion failed

### ISSUE THREAD

**Issue by sudlud** [azerothcore/azerothcore-wotlk#17835]
### Current Behaviour

I was teleporting around the world using ".go xyz" command

https://gist.github.com/sudlud/cb1a7c27e2996f061c4e4e303d7106b8

### Expected Blizzlike Behaviour

no crash

### Steps to reproduce the problem

somehow related to ".go xyz"

### Extra Notes

last compiled on e940305cffd1
currently checked out 1850c974a, so DB is at this commit.
(maybe this caused the issue)

### AC rev. hash/commit

AzerothCore rev. e940305cffd1+ 2023-11-20 18:38:41 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 21 second(s)
Update time diff: 1ms, average: 2ms.
Using SSL version: OpenSSL 3.1.2 1 Aug 2023 (library: OpenSSL 3.1.2 1 Aug 2023)
Using Boost version: 1.81.0
Using CMake version: 3.27.3
Using MySQL version: 80034
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_09_16_00.sql
Latest WorldDatabase update: rev_1700752157974887500.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows

**Comment by sudlud** [comment]
crashes when running this command in-game

`.go xyz -6102.31, -1140.57, -184.87, -1.18682`

**Comment by elthehablo** [comment]
> crashes when running this command in-game
> 
> `.go xyz -6102.31, -1140.57, -184.87, -1.18682`

That makes sense, because with the new REGEX pr for .go the . and the , would both be parsed so the coordinates won't make sense

**Comment by Nyeriah** [comment]
If you have chat story press arrow up and check the location you tried to teleport to. Check command logs too to see if it shows the location you tried going to. Will help understand what happened here

**Comment by elthehablo** [comment]
Probably related to https://github.com/azerothcore/azerothcore-wotlk/pull/17772

**Comment by elthehablo** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/425d1be9-0e55-42e2-9595-64ca6d0ebae3)
probably breaks on this boolean

**Comment by sudlud** [comment]
alright this reproduces it
the coordinates were meant for map 1 but i ran the command on map 0

```
.tele stormwind
.go xyz -6102.31, -1140.57, -184.87, -1.18682
```

**Comment by sudlud** [comment]
ah how stupid i copied the orientation as a 4th parameter from my sql gile which should be the map, so its trying to use "-1.18682" as the map

**Comment by sudlud** [comment]
so all you have to do is provide a negativ value for the map in command .go xyz

`.go xyz 1630 -4375 32 -1`

**Comment by elthehablo** [comment]
Yeah I am stupid too. It shouldn't break on the REGEX of the coordinates. So yeah still nice you found this

**Comment by elthehablo** [comment]
I am working on something

**Comment by Kitzunu** [comment]
if map < 0
    DoSomethingThatIsntAssert()

**Comment by elthehablo** [comment]
> if map < 0 DoSomethingThatIsntAssert()

yeah except it isn't zero, but a big int. You can check this in an if statement with MAPID_INVALID. PR coming

**Comment by elthehablo** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/f3d5e0d4-3731-4603-afc8-c21f1a49bd31)
this is what it tries to parse. because it is uint

**Comment by elthehablo** [comment]
> ![image](https://user-images.githubusercontent.com/83884799/285313137-f3d5e0d4-3731-4603-afc8-c21f1a49bd31.png) this is what it tries to parse. because it is uint

this is with the linked PR, just to show the MapId it thinks it wants to go to
