### ISSUE TITLE
Auction emails sent from incorrect Character.GUID

### ISSUE THREAD

**Issue by Akaitatsu** [azerothcore/azerothcore-wotlk#17882]
### Current Behaviour

When an auction ends and the mail is sent to the winner, the sender of the email is usually incorrect. The sender's field appears to be set to ID of the auction house faction instead of the seller's character.guid. I noticed this when I created the **6th** character on my server and all the auction house mails started showing that character as the sender. All the characters on my server so far are Horde which is faction **ID 6**, matching the new character's GUID.

### Expected Blizzlike Behaviour

The sender of the mail should match the seller of the auction.

### Source

I don't have a source, but it only makes sense for the sender of the mail to be the auction seller.

### Steps to reproduce the problem

1. Create an auction with one character (make sure the character's guid isn't the same as the faction of the auction house)
2. Bid/buyout the auction with another character
3. Query the mail table and you'll see that the sender matches the faction's ID instead of the character's

### Extra Notes

I believe the offending code is at **line 67 of Mail.cpp** (linked below), but I don't really know C++.
https://github.com/azerothcore/azerothcore-wotlk/blob/9da76571478521caf05cff10349e74ec3f871c1e/src/server/game/Mails/Mail.cpp#L67C27-L67C27
It looks like `sender->GetHouseId()` should be `sender->owner`.

### AC rev. hash/commit

```
AzerothCore rev. 03612e8bffe7+ 2023-11-15 14:17:29 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 3 hour(s) 27 minute(s) 5 second(s)
Update time diff: 2ms, average: 2ms.
Using SSL version: OpenSSL 3.0.12 24 Oct 2023 (library: OpenSSL 3.0.12 24 Oct 2023)
Using Boost version: 1.81.0
Using CMake version: 3.27.7
Using MySQL version: 101103
Found MySQL Executable: C:/Program Files/MariaDB 10.11/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
                         All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-aoe-loot
- mod-autobalance
- mod-npc-enchanter
- mod-npc-services
- mod-solo-lfg
- mod-transmog
```

### Operating system

Windows Server 2022

### Custom changes or Modules

See debug output.

**Comment by pklloveyou** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/cefa9dd8-7352-4006-8588-f1984c03393d)
It seems to be correct

**Comment by Akaitatsu** [comment]
That's getting the House ID (Alliance/Horde) for the character and not the character's GUID. So if the seller is a Horde character, the auction mail is sent from the _character_ with GUID of 6 (Horde is house 6). Basically, all mails for Alliance auctions are sent from character GUID 2 and all Horde auctions use character GUID 6.

I believe that `sender->GetHouseId()` is wrong and that it should be `sender->owner`.

**Comment by Kitzunu** [comment]
Wrong. When winning a bid in the auctionhouse, the AH is sending you the item, not a player.

**Comment by Akaitatsu** [comment]
@Kitzunu, thanks for your time on this. I think I understand the **mail** table better now. The description of the _sender_ column could use some more detail, but the rest of the auction-related information is good.
