### ISSUE TITLE
[Ogri'la] Quest Wrangle Some Aether Rays! Instantly completable

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#17895]
https://github.com/chromiecraft/chromiecraft/issues/6364
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Quest [Wrangle Some Aether Rays](https://wowgaming.altervista.org/aowow/?quest=11065) is instantly completable upon pick up. So is the daily version of the quest [Wrangle More Aether Rays](https://wowgaming.altervista.org/aowow/?quest=11066)

### Expected Blizzlike Behaviour

Quests should not be instantly completable.

### Source

https://wowgaming.altervista.org/aowow/?quest=11066
https://www.wowhead.com/tbc/quest=11065/wrangle-some-aether-rays

### Steps to reproduce the problem

.go c id 23335
accept quest
instantly turn in even if ? doesnt appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e663505b41ef3639138d793b14f6896acfad07d8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
I cannot reproduce this https://github.com/azerothcore/azerothcore-wotlk/commit/4552e89bfd809c6d00cb1ffc6d891ebf03b2998f

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/ef1b5645-bc3d-4e09-ba0d-6bd3770a2187)
