### ISSUE TITLE
[Ogri'la] Quests do not follow the intended quest progression

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#17899]
https://github.com/chromiecraft/chromiecraft/issues/6368
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Quests in Ogri'la are all available at once instead of following the chain they are supposed to be in.

### Expected Blizzlike Behaviour

There are quests that unlock upon completing certain quests instead of being all available at once.

### Source

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/11332559/29ca0605-61d2-4da1-88ef-dca873d26d9c)

https://www.wowhead.com/tbc/guide/ogrila-reputation-burning-crusade-classic#neutral-to-friendly
https://wowgaming.altervista.org/aowow/?quest=11009

### Steps to reproduce the problem

.quest add11009
.go c id 23233
hand in and notice all quests are available

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e663505b41ef3639138d793b14f6896acfad07d8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tereneckla** [comment]
Working correctly on stock AC https://github.com/azerothcore/azerothcore-wotlk/commit/4552e89bfd809c6d00cb1ffc6d891ebf03b2998f
