### ISSUE TITLE
[Ogri'la] Bombing Run instantly completable.

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#17894]
https://github.com/chromiecraft/chromiecraft/issues/6363
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

70

### Current Behaviour

Quest [Bombing Run](https://wowgaming.altervista.org/aowow/?quest=11010) as well as the daily [Bomb Them Again!](https://wowgaming.altervista.org/aowow/?quest=11023) are instantly completable upon pick up. 

Also, the daily version can picked up at the same time as the normal version of the quest.

### Expected Blizzlike Behaviour

Quests should not be instantly completable. Daily quest should unlock after completing the normal version.

### Source

https://wowgaming.altervista.org/aowow/?quest=11010
https://www.wowhead.com/tbc/quest=11010/bombing-run

### Steps to reproduce the problem

.go c id 23120
pick up quest
hand in quest even if ? doesnt appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e663505b41ef3639138d793b14f6896acfad07d8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
Can't reproduce https://github.com/azerothcore/azerothcore-wotlk/commit/4552e89bfd809c6d00cb1ffc6d891ebf03b2998f

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/3fd2a5fe-340a-4bbb-9eef-9d9deffa5942)
