### ISSUE TITLE
character customization doesn't accept name as arg

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#17942]
### Current Behaviour

When using the `character customize` GM command, there's no way to type the name of the recipient in the command.
`.character customize [$name]`
The [wiki](https://www.azerothcore.org/wiki/gm-commands) suggests that a name should be accepted, but only a target works.

### Expected Blizzlike Behaviour

`.character customize coolgoat` should allow for a character customization for the player with the name `Coolgoat` at the next login.

### Source

Just reading the [wiki](https://www.azerothcore.org/wiki/gm-commands).

### Steps to reproduce the problem

- Do not target anything.
- Type `character customize $name`
- Relog the character with the name $name
- No customization is offered

### AC rev. hash/commit

AzerothCore rev. 28591caaf83b 2023-12-03 18:04:25 -0300 (master branch) (Unix, Release, Static)

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/4e7877e0-211d-474c-a44b-80be5297139d)
jokes on you. I can't reproduce this

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/06ae09c1-b5f6-4def-993c-5866b4e913b0)
Same in-game

**Comment by 55Honey** [comment]
Thanks for checking, case solved!
