### ISSUE TITLE
Hanging on make -j `nproc` on MacOS Silicon

### ISSUE THREAD

**Issue by rwzdoorn** [azerothcore/azerothcore-wotlk#17948]
### Current Behaviour

Everything was build correctly with brew. When I follow the instructions to use:

make -j `nproc` ; at 98% my memory is being filled up (28GB) and looks like hanging on the line _Building CXX object src/server/scripts/CMakeFiles/scripts.dir/World/npcs_special.cpp.o_

### Expected Blizzlike Behaviour

The process keeps working towards 100%

### Steps to reproduce the problem

Step 1)
```
cd azerothcore
mkdir build
cd build
```

Step 2)
```
export OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)
cmake ../ \
-DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/  \
-DTOOLS_BUILD=all \
-DSCRIPTS=static \
-DMYSQL_ADD_INCLUDE_PATH=/opt/homebrew/include/mysql \
-DMYSQL_LIBRARY=/opt/homebrew/lib/libmysqlclient.dylib \
-DREADLINE_INCLUDE_DIR=/opt/homebrew/opt/readline/include \
-DREADLINE_LIBRARY=/opt/homebrew/opt/readline/lib/libreadline.dylib \
-DOPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR/include" \
-DOPENSSL_SSL_LIBRARIES="$OPENSSL_ROOT_DIR/lib/libssl.dylib" \
-DOPENSSL_CRYPTO_LIBRARIES="$OPENSSL_ROOT_DIR/lib/libcrypto.dylib"
```
(correct folder)

Step 3) `make -j `nproc``

### AC rev. hash/commit

I don't have any

### Operating system

MacOS 14.0

**Comment by Kitzunu** [comment]
Highest suppoeted is MacOS 12

**Comment by Kitzunu** [comment]
Or rather I should say, highest tested is mos12

**Comment by eyeofstorm** [comment]
The latest source code compiles successfully on my iMac M1 macOS sonoma 14.1.2 without any issues.

**Comment by Kitzunu** [comment]
Closing as Mac CI passes and no hash was provided
