### ISSUE TITLE
The "Amped for Revolt!  quest=13374 " mission: After the vehicle is summoned, the player is not automatically summoned onto the vehicle, preventing the mission from starting.

### ISSUE THREAD

**Issue by dongkui555** [azerothcore/azerothcore-wotlk#17967]
### Current Behaviour

The "Amped for Revolt!  quest=13374 " mission: After the vehicle is summoned, the player is not automatically summoned onto the vehicle, preventing the mission from starting.

### Expected Blizzlike Behaviour

After the vehicle is summoned, the player is automatically summoned onto the vehicle, and then the mission begins.

### Steps to reproduce the problem

Talk to NPC Rizzy Ratchwiggle to summon the bomber.

### AC rev. hash/commit

.server debug

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
add the output of .server debug
