### ISSUE TITLE
Crash on additem in the world console window

### ISSUE THREAD

**Issue by lanhai** [azerothcore/azerothcore-wotlk#18015]
### Current Behaviour

commands/additem

### Expected Blizzlike Behaviour

when i type additem command in world console window or soap service ,the world server will be crash in few seconds

### Steps to reproduce the problem

just crashed

### AC rev. hash/commit

none

### Operating system

Windows 11 x64

**Comment by Kitzunu** [comment]
Add hash and a way to properly reproduce it. I.e the enite command input which causes the crash
