### ISSUE TITLE
[MSVC] Azerothcore-wotlk failed to build with msvc due to error C2440, error C3861 on Windows

### ISSUE THREAD

**Issue by charmian-ch** [azerothcore/azerothcore-wotlk#18017]
### Current Behaviour

Azerothcore-wotlk failed to build with msvc:
```
src\test\common\Configuration\Config.cpp(39,5): error C2440: 'return': cannot convert from 'const boost::filesystem::path::string_type' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
src\test\common\Configuration\Config.cpp(39,5): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
src\test\common\Configuration\Config.cpp(68,5): error C3861: 'setenv': identifier not found
src\test\common\Configuration\Config.cpp(76,5): error C3861: 'setenv': identifier not found
src\test\common\Configuration\Config.cpp(84,5): error C3861: 'setenv': identifier not found
src\test\common\Configuration\Config.cpp(92,5): error C3861: 'setenv': identifier not found
src\test\common\Configuration\Config.cpp(100,5): error C3861: 'setenv': identifier not found
src\test\common\Configuration\Config.cpp(107,5): error C3861: 'setenv': identifier not found
src\test\common\Configuration\Config.cpp(113,5): error C3861: 'setenv': identifier not found
```

### Expected Blizzlike Behaviour

No error.

### Source

[src/test/common/Configuration/Config.cpp](https://github.com/azerothcore/azerothcore-wotlk/tree/06525cdc1e79cc041583af40b9f923adb7996d64/src/test/common/Configuration/Config.cpp)

### Steps to reproduce the problem

1. Clone the https://github.com/azerothcore/azerothcore-wotlk.git code to S:\azerothcore-wotlk folder
2. git -C "S:\azerothcore-wotlk" reset --hard 06525cd
3. Open a x86 Native Tools Command Prompt for VS 2022
4. mkdir S:\azerothcore-wotlk\build_x86
5. cd /d S:\azerothcore-wotlk\build_x86
6. set BOOST_ROOT=S:\boost-binaries\boost_1_83_0-msvc-14.3-32
7. set MYSQL_ROOT=S:\mysql_5_7_36\mysql-5.7.36-win32
8. set OPENSSL_ROOT=S:\OpenSSL\32
9. cmake -G "Visual Studio 17 2022" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DTOOLS=ON -DBUILD_TESTING=ON .. 2>&1
10. set _CL_=/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR /D_HAS_DEPRECATED_RESULT_OF=1 /D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING
11. msbuild /m /p:Platform=Win32 /p:Configuration=Release AzerothCore.sln /t:Rebuild 2>&1

**Here are the build files and cl.exe parameter file can reproduce easily:**
1. Download [azerothcore-wotlk-repro.zip](https://github.com/azerothcore/azerothcore-wotlk/files/13682255/azerothcore-wotlk-repro.zip)
2. Open a x86 Native Tools Command Prompt for VS 2022
3. Cd to azerothcore-wotlk-repro folder,  run: `cl.exe @cl.rsp`

### Extra Notes

Visual Studio 2022 17.8.3

### AC rev. hash/commit

[06525cd](https://github.com/azerothcore/azerothcore-wotlk/commit/06525cdc1e79cc041583af40b9f923adb7996d64)

### Operating system

Windows 10 x64, 22H2

**Comment by Kitzunu** [comment]
32bit is not supported. Go 64bit.

========== Build: 19 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========
