### ISSUE TITLE
Worldserver Red Warnings

### ISSUE THREAD

**Issue by ForevergloryXXI** [azerothcore/azerothcore-wotlk#18016]
### Current Behaviour

- Hei i just set up the Azerothcore and install 5 modules:
Anticheat, Autobalance, Challenge_modes, Individualprogression, istance-reset
Mod_boss_announcer, mod_luaengine, solofg.

Photo: https://imgur.com/a/Fh5jVcE

- The problems are every time when i start the world server
- I get this huge red list what say "Is not assigned in the database"
- And i get another error, "unknown spell 89505 by caster guid full" 
- The unknown spell error, i receive it approximately every time
- When my character use one of his spell 

- How can i fix these problems, did someone know how to fix it 
- Or can give me a link with an old topic what fix this problem please help <

Trying to do some research but as a newbie in this world is a little bite harder
After some research, i didn't find any fix

### Expected Blizzlike Behaviour

-----

### Steps to reproduce the problem

1. I start the worldserver

### AC rev. hash/commit

===

### Operating system

Win 11

**Comment by Kitzunu** [comment]
It is because of module SQL files not being run in the database. You need to run them or follow the installation steps given by each module
