### ISSUE TITLE
create_module.sh has error on requesting setup_git_commit_template.sh, file is not existent

### ISSUE THREAD

**Issue by Verizane** [azerothcore/azerothcore-wotlk#18022]
### Current Behaviour

Starting create_module.sh. On end it says
--- Configure git for nice commit messages
./create_module.sh: line 34: setup_git_commit_template.sh: No such file or directory
bash: setup_git_commit_template.sh: No such file or directory

### Expected Blizzlike Behaviour

Either it should not be calling the file or the file should be existent.

### Steps to reproduce the problem

Execute create_module.sh inside module directory.

### AC rev. hash/commit

no hash

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
That tool is outdated. Use https://github.com/azerothcore/skeleton-module as a base
