### ISSUE TITLE
Eclipsion Dragonhawk's fire breath hitting harder than it should

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#18042]
Original Cromiecraft report https://github.com/chromiecraft/chromiecraft/issues/6391 Confirmed on my local 

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour
The [Eclipsion Dragonhawk](https://wowgaming.altervista.org/aowow/?npc=20502), located in Eclipse Point, Shadowmoon Valley, is dealing an extreme amount of damage with their [Fire Breath](https://wowgaming.altervista.org/aowow/?spell=38309) spell.
Witnessed in person on two separate characters. Two images of the combat log are included.
![eclipsiondragonhawkbugreportexample1](https://github.com/chromiecraft/chromiecraft/assets/153065400/155f9eda-f0c0-426f-aa88-e2b3e1131d6f)
![eclipsiondragonhawkbugreportexample2](https://github.com/chromiecraft/chromiecraft/assets/153065400/e2212d71-a312-4083-b970-038fe126ee90)

**Tester notes:** Current spell used is 38309 tooltip is stated as below.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/fe931c57-2dab-499d-b0a9-9f159b61d09a)
I don't believe this is the correct spell. The tooltip also looks to be unfinished, and there is no referance to this spell being used by anything
https://www.wowhead.com/spell=38309/fire-breath
https://wowgaming.altervista.org/aowow/?spell=38309

### Expected Blizzlike Behaviour

Several sources have spell 37985 listed as the ability used by this mob
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/94dddd5e-96bf-4a5e-b1ff-f142bceced6d)

### Source
https://www.wowhead.com/npc=20502/eclipsion-dragonhawk#abilities
https://wowgaming.altervista.org/aowow/?spell=37985#used-by-npc

### Steps to reproduce the problem

1. .go c 72587
2. engage in combat
3. Wait until it casts Fire Breath
4. Pull out marshmallows
5. Check combat logs for the spell used

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
![37985 is in use.](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/fd04475e-7a46-4cbf-a52b-703a74b1bcb8)

**Comment by heyitsbench** [comment]
I am very confident this is due mostly to the dragonhawk's auto-attacks doing higher damage than they should.

**Comment by jamjar1233** [comment]
From what I was able to gather from the symbols within the project. I believe that the smart AI is missing for the Eclipsion Dragonhawk, thus it is pulling the wrong spell. Cross-referencing with similar projects, I believe the loading of the entity along with its smart AI is incorrect as you mentioned. I believe it should look something similar to this: 

`
SET @ENTRY := 20502;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,2500,2500,15000,30000,11,37985,0,0,0,0,0,2,0,0,0,0,0,0,0,"Eclipsion Dragonhawk - In Combat - Cast 37985");`

**Comment by heyitsbench** [comment]
> From what I was able to gather from the symbols within the project. I believe that the smart AI is missing for the Eclipsion Dragonhawk, thus it is pulling the wrong spell.

The correct spell is being used, it just has too high damage. Again, I believe this is due to an issue with the Dragonhawk's damage overall, as it melees for too much as well.

**Comment by heyitsbench** [comment]
I think I've figured out the underlying issue here. Both the spell being cast by the Dragonhawk (which is the correct one) and the spell triggered by that spell have the scaling damage based on caster level attribute. This causes the trigger spell to scale the value to give to the next spell, and then that next spell scaling the final damage value *again*.
