### ISSUE TITLE
Scholomance Item healthy-dragon-scale droppt permanent 

### ISSUE THREAD

**Issue by Seebaby** [azerothcore/azerothcore-wotlk#1805]
SMALL DESCRIPTION:

The item healthy-dragon-scale ID 13920 should not drop until you have completed the quest Plagued Hatchlings 5529.

But it always drops on the mobs Plagued Hatchling 10678.

EXPECTED BLIZZLIKE BEHAVIOR:

Item should only drop after the quest Plagued Hatchlings ID 5529 has been completed

the dropprate should also be 6% and not 100 

https://www.wowhead.com/quest=5582/healthy-dragon-scale

CURRENT BEHAVIOUR:

Item Drops Even Without Closing Plagued Hatchlings 

STEPS TO REPRODUCE THE PROBLEM:
.go creature 48929
Kill the dragons and loote them

BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by poszer** [comment]
Will add condition for it. Thanks for reporting @Seebaby

**Comment by poszer** [comment]
What's loot for this, can't be 100% for sure :laughing:

**Comment by poszer** [comment]
Instead of changing titles, you can answer me nvm :angry:

**Comment by Seebaby** [comment]
Sry what would you like to know exactly my english is not the best

**Comment by poszer** [comment]
> y what would you like to kn

It's okay. There is fix referenced, if you can, test it :+1:

**Comment by Seebaby** [comment]
Ah okay man today I'm all messed up
I'll test him right now.
