### ISSUE TITLE
Orgimmar grunts giving improper gossip for barber shop

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#18059]
Original Chromicraft report https://github.com/chromiecraft/chromiecraft/issues/6259 Confirmed

### What client do you play on?

enGB

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

SO when you ask an Orgrimmar Grunt about the barber, it will mention that it moved out of the cleftshadows, just to relocate into the valley of strength, where the "fruit" vendor used to be.

If you go ingame, the barber is in the cleft of shadows, and the grunts mark your map correct. But what the Grunt's gossip is saying, is absolutely wrong.

### Expected Blizzlike Behaviour
Thanks @heyitsbench for the check!
![3.4.3 52237](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/210b5a21-882d-409b-a503-9a62ac32813a)

### Source

![Barber](https://github.com/chromiecraft/chromiecraft/assets/96357766/db870d61-bbab-427e-8489-0c074b67eec0)
![Barber 2](https://github.com/chromiecraft/chromiecraft/assets/96357766/57761202-443f-45a2-8000-4daafca75472)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/68164076/f25c800e-7333-409c-84e4-591bd4f95fee)
https://wowwiki-archive.fandom.com/wiki/Barbershop_(Org)#:~:text=of%20Orgrimmar%20is%20located%20between,shop%20used%20to%20be%20located.

### Steps to reproduce the problem

1. .go c 10350
2. Ask for the barber
3. Read incorrect directions (but marks map correct)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/29af6cc88662ab2565bdcedcf60e12f0cc87cecf

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
![3.4.3 52237](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/210b5a21-882d-409b-a503-9a62ac32813a)

**Comment by elthehablo** [comment]
Cata broadcast texts 😩

**Comment by sudlud** [comment]
soi I tried this

```
-- Update Orgrimmar Grunt directions for barber Shop
-- these had VerifiedBuild 18019 (Mists of Pandoria) before and were therefore incorrect for 3.3.5a
UPDATE `broadcast_text` SET `MaleText` = 'The barber is in the Cleft of Shadow.', `FemaleText` = 'The barber is in the Cleft of Shadow.', `VerifiedBuild` = 52237 WHERE `ID` = 31559;
```

but I'm getting this error

`ERROR 1264 (22003) at line 3 in file: 'C:\Azerothcore\data\sql\updates\db_world\rev_1704434117493300100.sql': Out of range value for column 'VerifiedBuild' at row 1`

VerifiedBuild is smallint in broadcast_text but e.g. int in gameobject table (?)

@Nyeriah

**Comment by heyitsbench** [comment]
That's because `broadcast_text` did not have VerifiedBuild's datatype adjusted to match newer client version numbers when I did that because `broadcast_text` entries are not to be edited.

**Comment by sudlud** [comment]
Well but if they have VerifiedBuild 18019 (MoP) and are wrong for 3.3.5a, the time for editing broadcast_text might have come

**Comment by Kitzunu** [comment]
No. Broadcast_text is all bruteforced data. That is why it is not to be edited. If something is wrong you just dont specify broadcast_text id in creature_text or wherever you may use it

**Comment by sudlud** [comment]
> No. Broadcast_text is all bruteforced data. That is why it is not to be edited. If something is wrong you just dont specify broadcast_text id in creature_text or wherever you may use it and just use the correct text in the respective table

So it's more like a fixed 'catalogue' that can be used or not

**Comment by Kitzunu** [comment]
Sure
