### ISSUE TITLE
(Event): Commoners talk too often.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#18050]
### Current Behaviour

Event commoners talk at an interval of 45s-60s.

### Expected Blizzlike Behaviour

They should talk at an interval of 300s. (5m)

### Source

Wrath Classic

### Steps to reproduce the problem

1. `.event start 2`
2. `.go c id 20102`
3. Observe their speech.

### Extra Notes

Originally reported at https://github.com/chromiecraft/chromiecraft/issues/6295.

### AC rev. hash/commit

79a2bb84e932a23de84b0d1f2bbe3b5d86947527

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by sudlud** [comment]
for creature 20102 the interval is currently set to 45-90s.

@heyitsbench what range would you propose? or should this actually be fixed to 300s?

**Comment by sudlud** [comment]
> > [...] should this actually be fixed to 300s?
> 
> This is what I would propose, the commoners on Classic stick to this timer very rigidly, if there is a range it's within the span of a second, definitely not forty-five.

alright - should there be some random initial offset after spawning? or will each pair of commoners always talk at the exact same time to each other

**Comment by heyitsbench** [comment]
> alright - should there be some random initial offset after spawning? or will each pair of commoners always talk at the exact same time to each other

Basically impossible to tell what offset there is if it is intentional (since most aren't killable or anything), oftentimes they do talk at the same time as each other.
