### ISSUE TITLE
Quest "Ending Their World" prerequisite quest incorrect

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#18055]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/6305 confirmed on my local. OP confirmed on classic.

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Quest "Ending Their World" does not unlock after completing quest "What We Don't Know". It seems that Clearing the Way (9761) is currently a pre-req, but the 2 quests should be able to be to be done at the same time.

### Expected Blizzlike Behaviour

"Ending Their World" should unlock after completing "What we don't know"

### Source

https://www.wowhead.com/wotlk/quest=9759/ending-their-world#comments:id=54917
https://wowwiki-archive.fandom.com/wiki/Quest:Ending_Their_World

### Steps to reproduce the problem

1. Be a draenei at least level 18
2. `.quest add 9753`
3. `.go c 63779`
4. Turn in and accept the chain quest "What we don't know" 
5. `.quest complete 9756` and turn in
6. accept "Vindicators Rest" chain quest
7. `.go c 63688` turn in 
8. Quest "Ending Their World" not available (It should be available at this point)
9. `.quest add 9761`
10. `.quest complete 9761` turn in 
11. Demolitionist Legoso now has "Ending Their World" avaliable

### Extra Notes

Leveled a Draenei on classic to check and Ending Their World unlocks after What We Don't Know..., and is available when going to turn in Vindicator's Rest.

After turning in What We Know, the quest is not there.
![ShareX_7Qycue96b1](https://github.com/chromiecraft/chromiecraft/assets/7994405/8c3bb187-079e-4b55-b821-5ddfef2a9dac)

After turning in What We Don't Know, it is.
![WowClassic_moQfFXz1ax](https://github.com/chromiecraft/chromiecraft/assets/7994405/7eb2fe02-b7d4-4e1b-bd73-07c79fd20e86)

Both quests in the log together
![WowClassic_FHD8vfeaSc](https://github.com/chromiecraft/chromiecraft/assets/7994405/eb4fdf58-c77e-49cf-806b-571e8ebf2e3b)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Win10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sudlud** [comment]
step 3 should be
'.go c 63379'

my draenei just got killed when going to the other creature 😝
