### ISSUE TITLE
Scholomance Darkmaster Gandling does not run quite correctly 

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1806]
SMALL DESCRIPTION:

The bossfight go Darkmaster Gandling does not run quite correctly 

EXPECTED BLIZZLIKE BEHAVIOR:

The boss fight against Darkmaster Gandling should take place in such a way that after some time the player portet into one of the 6 rooms.

There should be 3 guards in every room that you have to kill to open the door.

the tank can also be ported then the aggro should be transferred to a group member because the tank is not there 

The 3 guards should only leave the room when the group member dies in the room then the guards should attack the group and open the door after their kill.

https://youtu.be/tkt5Bgtozrw?t=727

CURRENT BEHAVIOUR:

you attack the boss and he casts what he should only should the tank be ported into one of the 6 rooms the boss runs into one of the 6 rooms afterwards and does not attack another group member.

In the room of miniboss Lord Alexei Barov spawning when you enter, there will be no guards to reopen the door to the boss.

The awake spawners in the room of The Ravenian and there are only 2 awake that are not enough to open the door of Lord Alexei Barov.

STEPS TO REPRODUCE THE PROBLEM:
.go creature 247104
Kill the 6 minibosses and fight against the boss min 2-5 player goes also solo takes only to see everything

BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by Voxstrasza** [comment]
Confirmed, still an issue as of `9facd81e54ac`

**Comment by patou01** [comment]
I understand it doesn't work, but do we have a proper video of what it should do? The mobs are clearly running through a locked door for what does seem to be no reason at all https://youtu.be/tkt5Bgtozrw?t=815

**Comment by Azcobu** [comment]
Upgraded priority as this is the final fight for one of the two major dungeons for this bracket, and it doesn't work correctly.
