### ISSUE TITLE
Cannot compile the code due to missing a cpp file

### ISSUE THREAD

**Issue by yiminyuan** [azerothcore/azerothcore-wotlk#18074]
### Current Behaviour

Cannot compile the code due to the following error:
```
clang: fatal error: no such file or directory: '/home/azerothcore/azerothcore/src/server/scripts/EasternKingdoms/zone_alterac_mountains.cpp'
```

Probably caused by the recent commit: https://github.com/azerothcore/azerothcore-wotlk/commit/0ad882338cc1eb7a63aa8942d8c37ba5ad0f2c9d

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

Try to compile the code after this commit: https://github.com/azerothcore/azerothcore-wotlk/commit/0ad882338cc1eb7a63aa8942d8c37ba5ad0f2c9d

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0ad882338cc1eb7a63aa8942d8c37ba5ad0f2c9d

### Operating system

Ubuntu 22.04

**Comment by Nyeriah** [comment]
Rerun cmake. It needs to be done whenever new files are added or removed
