### ISSUE TITLE
Caribou Trap doesn't use all provided templates

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#18078]
### Current Behaviour

One of the 15 gameobject_templates is used for every spawn of Caribou Traps

### Expected Blizzlike Behaviour

Each Caribou Trap has it's own template (go ask the blizzard intern why)

### Source

sniffs
there exist 15 templates and 15 spawns

### Steps to reproduce the problem

DB

### Extra Notes

The one template used is 187982
```SELECT * FROM `gameobject_template` WHERE `name` = 'Caribou Trap';```
https://wowgaming.altervista.org/aowow/?search=caribou+trap

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6a6cefb512e89350850e9fae5325f35ec25d8290

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
Okok but if you have the sniffs you can provide the correct position corresponding to the different entries 👍👍

**Comment by Tereneckla** [comment]
The sniff is deleted...
It's from my stupid phase where I did stuff for another pserver

**Comment by Kitzunu** [comment]
Ahh Bench got sniffs of everything. He surely got it

**Comment by heyitsbench** [comment]
> Ahh Bench got sniffs of everything.

I explicitly do not.

> He surely got it

I might.
