### ISSUE TITLE
Heirloom Weapons are Dealing more damage than they should

### ISSUE THREAD

**Issue by Dracko42** [azerothcore/azerothcore-wotlk#18083]
### Current Behaviour

I first noticed issue when I hit lvl 80 and crafted a Titansteel Destroyer to replace my Bloodied Arcanite Reaper. This was standard behavior in retail as when you hit 80 the BOAs stop being useful. However...Upon equipping the Destroyer my damage on the character screen and testing on the boss dummy dropped by about half? (exact percent is hard to determine looking at random white numbers but it would be 'around' 50%). I was concerned some mods (like the solo dungeon mod) might be causing an issue even though I was no longer in a dungeon so I spun up a fresh install of azerothcore and proceeded testing. Below are my results:

Setup:
- I set my account to permission level 3 which I believe is the highest.
- I created a paladin (all my testing has been on paladin).
- I leveled the paladin to 80 and set all weapon skills to 400 (max)
- I create some BoAs the majority of testing I did with the Bloodied Arcanite Reaper.
- I created a Bryntroll, the Bone Arbiter (ilvl 264).
- With no buffs or other gear (other than the weapons) I proceeded to bash the boss target in Silvermoon City.

The character screen damage was similar between the 2 (sorry I don't remember the exact figures but they were 'close'). The white damage on the dummy seemed to average slightly higher on the Bone Arbiter.

I did also notice in other testing that this is not limited to the Bloodied Arcanite Reaper. I also used a Venerable Dal'Rend's Sacred Charge which was also considerably overperforming.

I did do an initial dive into the DB but I got stuck when I realized that the scaling tables in the world DB were blank.

### Expected Blizzlike Behaviour

BOA weapons should not perform better than ilvl 200 lvl 80 weapons. Historically they slightly underperformed the first lvl 80 purples you can get at lvl 80

### Steps to reproduce the problem

From above:

Setup:
- I set my account to permission level 3 which I believe is the highest.
- I created a paladin (all my testing has been on paladin).
- I leveled the paladin to 80 and set all weapon skills to 400 (max)
- I create some BoAs the majority of testing I did with the Bloodied Arcanite Reaper.
- I created a Bryntroll, the Bone Arbiter (ilvl 264).
- With no buffs or other gear (other than the weapons) I proceeded to bash the boss target in Silvermoon City.

I did not create another titansteel destroyer for my fresh test but if you also wanted to use that it should slightly outperform the bloodied arcanite reaper.

### Extra Notes

This 'feels' like a scaling issue with at least 2 of the BoA weapons. Thinking back to when I was leveling...When I switched from a blue weapon to the reaper (around lvl 30) I immediately noticed an improvement. Thinking back that should have been a signal there was an issue as I was killing mobs very quickly.

### AC rev. hash/commit

AzerothCore rev. b6cb8a572c69 2023-11-16 01:00:30 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 12

### Custom changes or Modules

Was running the following mods when noticed:

AH bot mod
Solocraft mod
SoloLFG mod
Transmog mod

I did the majority of testing off a fresh install (from backup) without any mods

**Comment by smellbee** [comment]
confirmed!  this is a long existed bug, totally make melee weopon under lvl 264 useless
 hope devs could look into this

**Comment by elthehablo** [comment]
The scaling is likely done by script. Probably some base number divided by 80 and increased to x/80 of the full number every step. Problem is to fix this accurately we have to check how it is done on wotlk classic.

I'm sorry if I skimmed the report too fast and this was answered, but are the stats themselves on the item also too high or is it the hidden stats that make it do too much damage?

**Comment by Dracko42** [comment]
I can confirm that the stats on both the Bloodied Arcanite Reaper and the Venerable Dal'Rend's Sacred Charge are showing the right stats at lvl 80

Bloodied Arcanite Reaper:
In game:
63 Str, 103 stam, improve crit by 68
Couple different wotlk item DBs:
63 Str, 103 stam, improve crit by 68

Venerable Dal'Rend's Sacred Charge:
In game:
44 stam, atk pwr +58, crit + 29
Couple different wotlk item DBs:
44 stam, atk pwr +58, crit + 29

Going to make an assumption the rest of the weapons will similarly show the right stats. This would indicate it is the hidden stats that are scaling too high.

**Comment by stgaozhong** [comment]
传家宝武器伤害翻倍了，源码计算的时候算了两次？？

**Comment by Dracko42** [comment]
You are all rock stars. Much appreciated.
