### ISSUE TITLE
The mage's flash will fall into the void

### ISSUE THREAD

**Issue by zhwblm** [azerothcore/azerothcore-wotlk#18081]
### Current Behaviour

Mage flashes will fall into the void. In models with stairs, flashes will fall into the void. Occasionally, they will flash in place, warriors will charge, and they will also fall into the void

### Expected Blizzlike Behaviour

正常法师闪现不会掉进虚空

### Steps to reproduce the problem

Flashing at the staircase position

### AC rev. hash/commit

Flashing at the staircase position

### Operating system

win10

**Comment by Kitzunu** [comment]
Provide hash and the entire output of .server debug
