### ISSUE TITLE
Gearing Redridge

### ISSUE THREAD

**Issue by kamenitxan** [azerothcore/azerothcore-wotlk#18097]
### Current Behaviour

When you complete quest, I dont think that soulbound items 2857 and 6214 should be removed from your inventory.

### Expected Blizzlike Behaviour

Equiped items 2857 and 6214 are not removed.

### Steps to reproduce the problem

.additem 2857 4
.additem 6214 4
Equip item 2857 and 6214 
.quest add 1618
.go creature id 415
Complete quest
Observe that items  2857 and 6214  are not equiped

### Extra Notes

![WoWScrnShot_010124_232639](https://github.com/azerothcore/azerothcore-wotlk/assets/935684/acd6c046-bc7a-446e-a65e-24d92b9015ec)
![WoWScrnShot_010124_232750](https://github.com/azerothcore/azerothcore-wotlk/assets/935684/643a7759-e07a-406e-a4e9-3a02e936c036)

### AC rev. hash/commit

AzerothCore rev. f9f71fff36de

### Operating system

Ubuntu 22.04.3

### Custom changes or Modules

mod-account-achievements

**Comment by elthehablo** [comment]
Any sort of proof for this?

**Comment by kamenitxan** [comment]
I couldn't find any proof. Feel free to close this, if you think that current behavior is correct.

**Comment by Foereaper** [comment]
Tested in Classic, behavior is the same
