### ISSUE TITLE
[Karazhan] Aran's trigger visibility is reversed.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18107]
### Current Behaviour

In GM mode, you can't see the triggers in a circle in the small room, but in normal user mode, you can see many triggers instead.

### Expected Blizzlike Behaviour

the visibility should reversed，gm mode can see and normal mode can not see.

### Steps to reproduce the problem

.go c 135692
and see on gm mode and normal use mode around

### AC rev. hash/commit

AzerothCore rev. ce8a7fd8802c 2024-01-03 00:56:15 +0800 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 20. Characters in world: 18.
Connection peak: 113.
服务器运行时间: 20 hour(s) 3 minute(s) 21 second(s)
Update time diff: 10ms, average: 10ms.
Using SSL version: OpenSSL 3.0.11 19 Sep 2023 (library: OpenSSL 3.0.11 19 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101104
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.2.16-19-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
                         All available DBC locales: zhCN 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: zone_difficulty_instance_saves.sql
Latest WorldDatabase update: zone_difficulty_spelloverrides.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-reward-played-time
- mod-save-inventory
- mod-server-auto-shutdown
- mod-zone-difficulty
- mod_spec_reward

### Operating system

debian12 x64

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/15932
