### ISSUE TITLE
ConditionMgr will log errors when CONFIG_EXPANSION is not set to 3 

### ISSUE THREAD

**Issue by ben-of-codecraft** [azerothcore/azerothcore-wotlk#18118]
### Current Behavior

Logs many errors into logs or console that look like this: 

ERROR Skill condition specifies invalid skill value (300), skipped

### Expected Blizzlike Behavior

Should ignore conditions that are greater than max skill level for each expansion and not log error.

### Source

I would recommend this change
```
--- a/src/server/game/Conditions/ConditionMgr.cpp
+++ b/src/server/game/Conditions/ConditionMgr.cpp
@@ -2004,8 +2004,21 @@ bool ConditionMgr::isConditionTypeValid(Condition* cond)
 
         if (cond->ConditionValue2 < 1 || cond->ConditionValue2 > sWorld->GetConfigMaxSkillValue())
         {
-            LOG_ERROR("sql.sql", "Skill condition specifies invalid skill value ({}), skipped", cond->ConditionValue2);
-            return false;
+            // Handle cases where the user has set an expansion lower than the existing conditions. 
+            bool isError = true; 
+            int8 expansion = uint8(sWorld->getIntConfig(CONFIG_EXPANSION)); 
+            if(expansion == 1 && cond->ConditionValue2 > 300) {
+                isError = false; 
+            }
+
+            if(expansion == 2 && cond->ConditionValue2 > 375) {
+                isError = false; 
+            }
+
+            if(isError) {
+                LOG_ERROR("sql.sql", "Skill condition specifies invalid skill value ({}), skipped", cond->ConditionValue2);
+                return false;
+            }            
         }
```

### Steps to reproduce the problem

1. Set World config expansion lower than 3
2. Start server 

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/859b6594a59ac5c0aecd65be787951dd93380892

### Operating system

Ubuntu 18

### Custom changes or Modules

I have eluna and NPC Bots appled, but validated this is in main branch of azerothcore also

**Comment by Kitzunu** [comment]
Set expansion to 0 with no errors in the console

**Comment by Kitzunu** [comment]
It errors when you change MaxPlayerLevel which is correct as the condition require higher level skill than the player can acquire. So there is no reason to change this. If you plan to lower max level you can change these conditions yourself
