### ISSUE TITLE
Warlock Pets Bugged

### ISSUE THREAD

**Issue by htc16** [azerothcore/azerothcore-wotlk#18115]
### Current Behaviour

Since level 40 I have noticed my summoned demons do not work properly. I am currently level 42 affliction warlock. When I summon a Succubus or Felhunter it works properly, however, if I teleport somewhere, use hearthstone, use flightmaster or sometimes even just use my mount, it occasionally (not every time) disappears. When I dismount or appear, the Felhunter/Succubus is either just gone (no summoned demon), or it is suddenly a different one. Aka, I had a Succubus summoned, then I mount up, go somewhere, I dismount, and I have an Imp as a summoned pet. Or I had a Felhunter summoned, I use my hearthstone and I either have no summoned demon, or I have a Succubus.
I have NOT noticed this problem with Imp or Voidwalker, or on my (horde) demonology warlock's Felguard.

### Expected Blizzlike Behaviour

A summoned demon should always stay the same through any travelling and also stay summoned (unless killed or dismissed).

### Steps to reproduce the problem

1. Summon Succubus/Felhunter.
2. Mount up and travel or use a flightmaster.
3. Check if you still have a demon pet, and if it is the same one.

### AC rev. hash/commit

ccf92f481d0d

### Operating system

Windows 11

**Comment by Nyeriah** [comment]
Unable to reproduce using succubus + fly path/mount

**Comment by Alethrion** [comment]
Playing destruction with imp I've never gotten the wrong summon from teleports (as is to be expected), but I have noticed there is something odd about summons in general. Most of my summons will have 1 of 2 random names each time they come out when the intended behavior is for them to always have the same random name

**Comment by Alethrion** [comment]
It seems this can occur frequently when you swap pets often (as is done in pvp) or swap specs often and mount up
