### ISSUE TITLE
SQL Update causes conflicts db_import for gameobject

### ISSUE THREAD

**Issue by ben-of-codecraft** [azerothcore/azerothcore-wotlk#18119]
### Current Behaviour

When running db import updates for 11_12_07 the file creates gameobject that will conflict with servers that have used sql modules from the azerothcore modules site. 

Error message im DBImport logs

```
Updating World database...
>> Applying update "2023_11_12_07.sql" '96ED637'...
ERROR 1062 (23000) at line 40 in file: '/azerothcore/data/sql/updates/db_world/2023_11_12_07.sql': Duplicate entry '2135505' for key 'gameobject.PRIMARY'
```

The gameobject table is using an unsigned auto-increment so explicitly setting the guid is not necessary and by removing the set guid when adding the inserts into the gameobject table it will not create conflicts for servers that may have custom content installed in those guids. 

### Expected Blizzlike Behaviour

The new spawn points for the location of the gameobjects should not create an import conflict if there are existing guids in the table for that id.  The 

### Steps to reproduce the problem

1. Run sql  - will set up the database to have an existing entry at 2135505
```
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`)  VALUES
(2135505, 500000, 530, 0, 0, 1, 1, -3550.81, 5709.02, 0.112858, 1.5979, 0, 0, -0.716625, -0.697459, 181, 100, 1, '', 0);
```
2.  run dbimport for file 2023_11_07.sql
3.  View log in DBImport.log

### Extra Notes

This would add the spawn locations of the objects without creating conflicts, allowing the auto-increment to create the primary key.  
```
DELETE FROM `gameobject` WHERE (`id` = 185211);
INSERT INTO `gameobject` (`id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(185211, 530, 3519, 3686, 1, 1, -3660.15, 5811.12, 0.02822, 1.98968, 0, 0, 0.838671, 0.544639, 181, 100, 1, '', 0),
(185211, 530, 3519, 3686, 1, 1, -3678.81, 5733.74, -1.00285, 0.733038, 0, 0, 0.358368, 0.93358, 181, 100, 1, '', 0),
(185211, 530, 3519, 3686, 1, 1, -3639.31, 5831.26, 0.07337, -2.44346, 0, 0, 0.939693, -0.34202, 181, 100, 1, '', 0),
(185211, 530, 0, 0, 1, 1, -3579.06, 5817.54, -3.24684, 3.7348, 0, 0, -0.956334, 0.292275, 181, 100, 1, '', 0),
(185211, 530, 0, 0, 1, 1, -3674.35, 5709.55, -0.758734, 1.02344, 0, 0, -0.489679, -0.871903, 181, 100, 1, '', 0);

DELETE FROM `gameobject` WHERE (`id` = 185210);
INSERT INTO `gameobject` (`id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(185210, 530, 3519, 3686, 1, 1, -3568.34, 5772.01, -2.86157, 2.72271, 0, 0, 0.978148, 0.207912, 181, 100, 1, '', 0),
(185210, 530, 3519, 3686, 1, 1, -3560.05, 5771.58, -3.12615, -0.506145, 0, 0, 0.25038, -0.968148, 181, 100, 1, '', 0),
(185210, 530, 0, 0, 1, 1, -3550.81, 5709.02, 0.112858, 1.5979, 0, 0, -0.716625, -0.697459, 181, 100, 1, '', 0),
(185210, 530, 0, 0, 1, 1, -3687.46, 5732.52, -0.673687, 0.680559, 0, 0, -0.333751, -0.942661, 181, 100, 1, '', 0),
(185210, 530, 0, 0, 1, 1, -3620.8, 5760.07, 1.91674, 5.29837, 0, 0, -0.472748, 0.881198, 181, 100, 1, '', 0);
```

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/1d3d3bebb8c855c760c74a40edf294904428b52c

### Operating system

Unbuntu 20

### Custom changes or Modules

SQL Script for Town Portals from Azerothcore modules site.

**Comment by Kitzunu** [comment]
Yup this is my bad. We should obviously delete GUID too

**Comment by ben-of-codecraft** [comment]
I wouldn't think you want to delete the guid that is in place, that could break custom content on upgrade.  I was thinking just leaving guid out of the query, so SQL creates it automatically on insert at the next available id.

**Comment by Nyeriah** [comment]
No because that would make it impossible to update those objects later on seeing how every user could have different guids

**Comment by Kitzunu** [comment]
The core works like this

The Core takes first place and priority everywhere. Custom content and modules are designed and to be adjusted to work with the Core. Not the other way around.

If a core change breaks a module or custom content, the author of these needs to fix it within their space

**Comment by ben-of-codecraft** [comment]
Yeah I was thinking more about what you said Nyeriah I am not as familiar with the tables to know if there is a foreign key for that guid so don't know if it's possible. I see the pattern on db migrations for this project seem to be id based deletes.  

When I have generally had to work with this problem in the past I just generate the delete statement similar to the insert statement: 

DELETE FROM `gameobject` WHERE (`id` = 185210) AND (`map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`)
IN (
    (530, 3519, 3686, 1, 1, -3568.34, 5772.01, -2.86157, 2.72271, 0, 0, 0.978148, 0.207912, 181, 100, 1, '', 0),
    (530, 3519, 3686, 1, 1, -3560.05, 5771.58, -3.12615, -0.506145, 0, 0, 0.25038, -0.968148, 181, 100, 1, '', 0),
    (530, 0, 0, 1, 1, -3550.81, 5709.02, 0.112858, 1.5979, 0, 0, -0.716625, -0.697459, 181, 100, 1, '', 0),
    (530, 0, 0, 1, 1, -3687.46, 5732.52, -0.673687, 0.680559, 0, 0, -0.333751, -0.942661, 181, 100, 1, '', 0),
    (530, 0, 0, 1, 1, -3620.8, 5760.07, 1.91674, 5.29837, 0, 0, -0.472748, 0.881198, 181, 100, 1, '', 0)
);

Well thanks for fast fix guys, I will stop pestering ya. I was doing upgrades today and found some issues but can just fix em as I go.  I am going to have to use more the approach I laid out since I do have custom content.

**Comment by Kitzunu** [comment]
GUID is the pri key. Why we also delete the ID (should always be guid + id) is to make sure we don't accidentally delete wrong guid's

**Comment by Kitzunu** [comment]
What you can do for custom content is to use unreasonably high GUIDs as we try to fill empty as low as possible spots first when creating new gob/creature spawns.
