### ISSUE TITLE
(Instance/Karazhan): Nightbane is killable during air phase.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#18120]
### Current Behaviour

Currently Nightbane is killable during air phase. He will also skip air phases if enough damage is taken.

### Expected Blizzlike Behaviour

He should cast the full durations of each rain of bones for each air phase skipped, and stay at one health point until landing back on the terrace.

### Source

[Wrath pre-patch combat log](https://classic.warcraftlogs.com/reports/7nrz98TtXqRkdAj1#view=replay&fight=21)

### Steps to reproduce the problem

1. `.tele kara`
2. Go to Nightbane.
3. Summon him.
4. Damage him in whatever way you'd like once he lands.
5. Trigger his air phase.
6. Do enough damage to make him skip the next phase(s).
7. Observe he can die while airborne.

### AC rev. hash/commit

859b6594a59ac5c0aecd65be787951dd93380892

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by kissingers** [comment]
Yes, and when it dies in the air phase, there is a chance that it will fall out of the wall and not be able to pick up its items.
