### ISSUE TITLE
Warning for compiling source code.

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#1814]
The following warnings appear with the latest source code:
Previous source code did not have such a prompt.
Does he affect core communications? If so, fix it.
Thank you for your contribution. Thank you!

e:\azerothcore-wotlk\src\server\game\server\worldsocket.cpp(727): warning C4715: “WorldSocket::ProcessIncoming”: Not all control paths return values

AzerothCore rev. 60bbe8f0eacd 2019-05-06 10:46:17 

windwos7  64bit

**Comment by poszer** [comment]
You don't need to open same issues: 

Already exist https://github.com/azerothcore/azerothcore-wotlk/issues/1793
Closing this.

**Comment by forever2019** [comment]
> 您不需要打开相同的问题：
> 
> 已经存在[＃1793](https://github.com/azerothcore/azerothcore-wotlk/issues/1793)
> 关闭这个。


I'm just asking if this question has any impact.
Thank you.
