### ISSUE TITLE
(DeathKnight): Unholy Gargoyle scaling spells unimplemented.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#18148]
### Current Behaviour

Currently there is a [hunter pet scaling spell](https://wowgaming.altervista.org/aowow/?spell=61017) enumerated in the DK pet script under the name `SPELL_DK_PET_SCALING`, but it goes unused in the script itself.

### Expected Blizzlike Behaviour

Gargoyle (and other pets) should have a few auras on them that affect quite a few things. For the gargoyle, that includes the following: [Death Knight Pet Scaling 01](https://wowgaming.altervista.org/aowow/?spell=54566), [Death Knight Pet Scaling 02](https://wowgaming.altervista.org/aowow/?spell=51996), and [Death Knight Pet Scaling 03](https://wowgaming.altervista.org/aowow/?spell=61697).

### Source

Sniffs, both Wrath Classic/Wrath retail

### Steps to reproduce the problem

1. Create a Death Knight.
2. `.levelup 25`
3. Accrue the talents required to engage in gargoylery.
4. Summon the gargoyle you worked so hard for.
5. `.list auras` on said gargoyle.
6. Observe none of the aforementioned.

### Extra Notes

These types of auras extend beyond the gargoyle and even beyond just the Death Knight, a lot of information on these can be found in these two TC issues: https://github.com/TrinityCore/TrinityCore/issues/874, https://github.com/TrinityCore/TrinityCore/issues/5136. Reason I'm reporting the gargoyle in particular (first, at least) is because it is apparently one of the ones people complain about most for not having well scaling with the summoner's haste, which seems to be handled through these spells.

### AC rev. hash/commit

fdbde0b866300f5647a0df0211b7cfda2e6d66b5

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Kitzunu** [comment]
what about 

https://github.com/azerothcore/azerothcore-wotlk/blob/a1891d8d8f8acd42dc1bd0c55ef4be3a8763cac9/src/server/game/Entities/Pet/Pet.cpp#L1343-L1356

**Comment by Joshmash** [comment]
so when will these changes be applied?

**Comment by Kitzunu** [comment]
They already exist

**Comment by heyitsbench** [comment]
> what about [Pet.cpp]
> Handled here [spell_dk.cpp]

My mistake, I believe I was checking the `pet_dk` script file for it. Either way, I don't believe `Hunter Pet Scaling 04` should be applied to Gargoyles. Based on discussions I've had with players on CC, the formula for some of these scaling spells may also be incorrect, hence why I opened this issue, but this issue itself is invalid. Thanks for checking.
