### ISSUE TITLE
Build error - my_bool is undefined

### ISSUE THREAD

**Issue by lwang665** [azerothcore/azerothcore-wotlk#1815]
![AC error](https://user-images.githubusercontent.com/49755364/57334584-1101df80-7118-11e9-8899-d8c186e1c7c5.png)

SMALL DESCRIPTION:
Build error for code

##### EXPECTED BLIZZLIKE BEHAVIOUR:
VC should let me build to proceed with installation

##### CURRENT BEHAVIOUR:
VC does not let me build

##### STEPS TO REPRODUCE THE PROBLEM:
1. Pull from git commit 
commit a68c13488e59c715c3ab355e0aa5f5b4423b703c (HEAD -> master, origin/master,                                                                                                                                                                                                origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Tue May 7 17:42:35 2019 +0000

    Import pending SQL update file...

    Referenced commit(s): 5b4cd25e5a0b5c2d3c840c204091eaa6c8957896

2. Perform cmake
3. open AzerothCore.sln, and attempt to build solution

##### EXTRA NOTES:
None

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
commit a68c13488e59c715c3ab355e0aa5f5b4423b703c (HEAD -> master, origin/master,                                                                                                                                                                                                origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Tue May 7 17:42:35 2019 +0000

    Import pending SQL update file...

    Referenced commit(s): 5b4cd25e5a0b5c2d3c840c204091eaa6c8957896

##### OPERATING SYSTEM:
Windows 10 Home

##### MODULES:

I'm am not sure what they are. 

##### OTHER CUSTOMIZATIONS:

No, I have not been able to install the game yet

**Comment by poszer** [comment]
https://discord.gg/fnYSwt Join here

**Comment by poszer** [comment]
Join here https://discord.gg/f9553v

**Comment by poszer** [comment]
Fixed

**Comment by bogdanian** [comment]
I am also having this issue, how can I fix it?

**Comment by poszer** [comment]
> I am also having this issue, how can I fix it?

On what OS? And what is your version of mysql ?

**Comment by bogdanian** [comment]
> On what OS? And what is your version of mysql ?

Windows 10
MySQL Ver 8.0.16 for Win64 on x86_64 (MySQL Community Server - GPL)

**Comment by poszer** [comment]
> > On what OS? And what is your version of mysql ?
> 
> Windows 10
> MySQL Ver 8.0.16 for Win64 on x86_64 (MySQL Community Server - GPL)

This will fix your issue, download this mysql
[MySql 5.6](http://dev.mysql.com/downloads/mysql/5.6.html)
