### ISSUE TITLE
Request more animations

### ISSUE THREAD

**Issue by Blandyoung** [azerothcore/azerothcore-wotlk#18167]
### Describe your feature request or suggestion in detail

I am trying to import other versions of skills, such as the monk's roll.

But what I got was an animation of smoke and dust.

This rolling animation should be built-in to the model and called by the client.

I added action numbers to the dbc file, but the added file did not respond on the client.

So my brothers told me what to do on the client side？

### Describe a possible solution to your feature or suggestion in detail

More casting actions and effects

**Comment by Kitzunu** [comment]
This is not a place for modding repated questions. Go seek up the modding community
