### ISSUE TITLE
Invincible's Reins is 60% mount

### ISSUE THREAD

**Issue by blinkysc** [azerothcore/azerothcore-wotlk#18178]
### Current Behaviour

Seems Invincible's Reins is 60% mount

### Expected Blizzlike Behaviour

Should be flying mount as well as fast ground mount

### Steps to reproduce the problem

.levelup 79
Learn all riding skills
.additem 50818

### Extra Notes

Tried going to all different locations with same behavior

### AC rev. hash/commit

a5cd23fa5b4b

### Operating system

Debian 12

**Comment by Nyeriah** [comment]
It scales with your riding skill

**Comment by blinkysc** [comment]
Tried learning all riding skills. Other mounts work as intended it seems (though didn’t test every mount). Put in steps to reproduce to learn riding skills
