### ISSUE TITLE
(Quest\11879) kaw the mammoth destroyer not work again

### ISSUE THREAD

**Issue by skelUA** [azerothcore/azerothcore-wotlk#18181]
### Current Behaviour

https://youtu.be/0x_AXQWNicw

### Expected Blizzlike Behaviour

Work as expected 

### Steps to reproduce the problem

1. Get quest kaw-the-mammoth-destroyer and try to start event

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/707df272332383f8f2008f236675ec5e6d4af173 2024-01-14 17:01:56 +0000 (master branch) (Unix, Debug, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 13 hour(s) 57 minute(s) 23 second(s)
Update time diff: 1ms, average: 5ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80034
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-79-generic
Worldserver listening connections on port 8087
Realmlist (Realm Id: 2) configured in port 8087
VMAPs status: Enabled. LineOfSight: 1, getHeight: 0, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 557561268 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 1910788784 bytes
Default DBC locale: enUS.
All available DBC locales: enUS ruRU
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: 2024_01_14_14.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

debian

**Comment by sudlud** [comment]
#17859

**Comment by gaolei4408** [comment]
![Uploading bed3f706b6727ed30eeed9f77346123a.png…]()

**Comment by sudlud** [comment]
@gaolei4408 looks like your upload was not done yet when you sent the comment

**Comment by elthehablo** [comment]
> Revert #18026 then it works good

Yes let's revert a core fix to fix a specific quest issue

**Comment by sudlud** [comment]
> > Revert #18026 then it works good
> 
> Yes let's revert a core fix to fix a specific quest issue 

I think it was just meant  informational that the PR has a causal relation, not as a suggestion to fix the issue.

**Comment by elthehablo** [comment]
It would have been very hard to test that PR completely. If you make issues for every broken quest encountered we can fix them

**Comment by elthehablo** [comment]
If the number goes up in the tens, twenties, etc. we can consider taking actions in the core
