### ISSUE TITLE
Quest 11705 (Foolish Endeavors) is uncompleteable

### ISSUE THREAD

**Issue by Nocty1501** [azerothcore/azerothcore-wotlk#18194]
### Current Behaviour

Varidus the Flenser, Saurfang, Getry  will all disappear before Saurfang can kill Varidus.

### Expected Blizzlike Behaviour

Saurfang should defeat Varidus and the quest should be marked as complete in your quest log.

### Steps to reproduce the problem

1. Start quest.
2. Watch Saurfang and Varidus fight it out.
3. Observe everyone despawning before the fight is over.

### AC rev. hash/commit

AzerothCore rev. 91c075896acd+ 2023-12-06 15:30:30 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04.3 LTS

**Comment by Kitzunu** [comment]
Closing as you have not provided a valid hash. Test on latest master without your custom changes
