### ISSUE TITLE
Visible Triggers - DK Start Area 

### ISSUE THREAD

**Issue by may-ruz** [azerothcore/azerothcore-wotlk#18191]
### Current Behaviour

+ Visible triggers appearing as Infernals are seen on the some of the Unworthy Initiates' wall locks. 
These visible triggers are named Unworthy Anchor Initiate.

+ A visible trigger is seen under a farm silo in Havenshire Farms. 
This visible trigger is oddly named The Lich King.

These did not appear in a 2023/11 version, but I notice them in 2024/01 (AzerothCore 3.3.5a).
I am using Warmane's Ultimate WotLK HD models, if that matters.

### Expected Blizzlike Behaviour

Triggers appearing as Infernals are supposed to be invisible to normal players.

### Steps to reproduce the problem

Create a Death Knight character using a non-GM account,  view initial areas.

### AC rev. hash/commit

Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: mod_auctionhousebot.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-ah-bot
- mod-solo-lfg
- mod-solocraft

### Operating system

Ubuntu Server 22.04.3 LTS

**Comment by Kitzunu** [comment]
Provide the entire server debug output and dont shorten it.
