### ISSUE TITLE
Feature: Fix license conflict this year

### ISSUE THREAD

**Issue by CraftedRO** [azerothcore/azerothcore-wotlk#18193]
### Describe your feature request or suggestion in detail

Hi, will you manage the License conflict this year, maybe ?

(two years passed and I see no solution implemented yet)

It is not possible in open source world to just grab some project source and relicense as you wish preventing development of the main project !!! (kek)

### Describe a possible solution to your feature or suggestion in detail

just put the "root project license" back please aka GPLv2.

### Additional context

Have a good day !

**Comment by Nyeriah** [comment]
This discussion has already taken place elsewhere, there's no need for another source of license drama.

Closing
