### ISSUE TITLE
Unable to import `item_dbc` on MariaDB 10.6

### ISSUE THREAD

**Issue by michaeldelago** [azerothcore/azerothcore-wotlk#18202]
### Current Behaviour

When running AzerothCore against MariaDB 10.6, the dbimporter fails with error message:

```
ERROR 1146 (42S02) at line 2 in file: '/azerothcore/data/sql/updates/db_world/2024_01_20_05.sql': Table 'acore_world.version' doesn't exist

Applying of file '/azerothcore/data/sql/updates/db_world/2024_01_20_05.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.
```

### Expected Blizzlike Behaviour

It should import in the same way as it does with MySQL - without an issue.

### Source

```console
$ grep --no-filename -roE "COLLATE=\S+" data/sql/base | cut -f2 -d\= | cut -f
1 -d\; | sort | uniq -c
      2 utf8mb4_0900_ai_ci
    404 utf8mb4_unicode_ci
```

it seems like the collation should be uniform throughout, as there's only 2 outliers

### Steps to reproduce the problem

(note that I have [this PR ](https://github.com/azerothcore/azerothcore-wotlk/pull/18201)checked out due to issues with MariaDB version checking)
1. Deploy with MariaDB instead of MySQL
2. Importing `db_world` should fail for the item_dbc.sql table

### Extra Notes

pretty sure we can just change the collation on [this line](https://github.com/azerothcore/azerothcore-wotlk/blob/7f7f18e48906959460171e05733baa736a730048/data/sql/base/db_world/item_dbc.sql#L29), though i dont know enough about the DB change process

### AC rev. hash/commit

7ad5c7e8d1734d64c813e9d66021abdb5915a5dd

### Operating system

Linux x64

### Custom changes or Modules

[This PR](https://github.com/azerothcore/azerothcore-wotlk/pull/18201), which is based off of `7f7f18e48906959460171e05733baa736a730048`

**Comment by Kitzunu** [comment]
Yea let me check. That collation looks wrong
