### ISSUE TITLE
Solved bug: A Spirit Ally? id 9847

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#1822]
Quest: "A Spirit Ally?" id 9847
Questitem: "Feralfen Totem" id 24498

Error: The mission item has no cd and infinite snakes can be invoked.

Simple solved: 
```sql
UPDATE `item_template` SET `spellcharges_1` = 1 WHERE `entry` = 24498;
```

**Comment by Pondaveia** [comment]
@solidmaxtor Can you please open a PR with this fix if you will?

If you don't know how you can do it by following these [guidelines](http://www.azerothcore.org/wiki/Dealing-with-SQL-files#how-to-create-an-sql-update-file).
Note: Make sure you sync your fork, create a new branch from master and then follow the guidelines above.

**Comment by Seebaby** [comment]
Fix is good and tested

**Comment by Seebaby** [comment]
So I made a PR request and hope that I did everything correctly. 

Is my first PR

**Comment by solidmaxtor** [comment]
Thanks Selyria the fix is aproved, it's my first contribution T_T

**Comment by Selyria** [comment]
> Thanks Selyria the fix is aproved, it's my first contribution T_T

Yes is fixed has been accepted and will soon be put together good fix.
