### ISSUE TITLE
worldserver process to crash for World::ProcessDelayedDamages()

### ISSUE THREAD

**Issue by amwmqj** [azerothcore/azerothcore-wotlk#18229]
### Current Behaviour

I encountered an issue that causes the worldserver to crash, which only happens when MapUpdate.Threads > 1. Here are the details:

crash on world.cpp:
World::ProcessDelayedDamages()
{
    //other code
    _delayedDamages.clear(); <- crash
}

minidump stack log:

Call stack:
Address   Frame     Function      SourceFile
000000007782F1FF  000000000013EB30  RtlUnhandledExceptionFilter+29F
000000007782F806  000000000013EB60  EtwEnumerateProcessRegGuids+1C6
0000000077830422  000000000013EB90  RtlQueryProcessLockInformation+342
0000000077832534  000000000013EBC0  RtlLogStackBackTrace+284
000000007779A232  000000000013EC40  RtlFreeHeap+72
000007FEF3DEF02B  000000000013EC70  _free_base+1B
#crash on "list::clear()"
0000000140295FBD  000000000013ED00  World::ProcessDelayedDamages+10D  F:\azerothcore-wotlk-BT\src\server\game\World\World.cpp line 3423
00000001402A5D84  000000000013EE90  World::Update+2F4  F:\azerothcore-wotlk-BT\src\server\game\World\World.cpp line 2361
000000013FBB83EA  000000000013F140  WorldUpdateLoop+69A  F:\azerothcore-wotlk-BT\src\server\apps\worldserver\Main.cpp line 599
000000013FBC58D0  000000000013F7C0  main+2CF0  F:\azerothcore-wotlk-BT\src\server\apps\worldserver\Main.cpp line 416
0000000140CAC810  000000000013F800  __scrt_common_main_seh+10C  D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
000000007766556D  000000000013F830  BaseThreadInitThunk+D
00000000777C372D  000000000013F880  RtlUserThreadStart+1D

### Expected Blizzlike Behaviour

None

### Source

world.cpp :

void World::ProcessDelayedDamages()
{
    for (auto& damage : _delayedDamages)
    {
        // Get map first
        Map* map = sMapMgr->FindMap(damage.mapId, damage.instanceId);
        if (!map)
            continue;

        // Now we get both, attacker and victim, but attacker can be null (although attacker is always a player).
        Unit* attacker = ObjectAccessor::GetUnit(map, damage.attacker);
        Unit* victim = ObjectAccessor::GetUnit(map, damage.victim);
        if (!victim)
            continue;

        Unit::DealDamage(attacker, victim, damage.damage, damage.cleanDamage, damage.damagetype, damage.damageSchoolMask, damage.spellProto, damage.durabilityLoss);
    }
    _delayedDamages.clear(); //crash
}

### Steps to reproduce the problem

1.online player > 350
2.worldserver.conf set MapUpdate.Threads > 1(2 - 33)

### AC rev. hash/commit

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1q  5 Jul 2022)
Using Boost version: 1.74.0
Using MySQL version: 80031
Using CMake version: 3.25.0
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in data/maps. Total size: 291014951 bytes
vmaps directory located in data/vmaps. Total size: 658130553 bytes
mmaps directory located in data/mmaps. Total size: 2192911264 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.10-dev

### Operating system

windows server 2008 r2 Enterprise

### Custom changes or Modules

- mod-anticheat
- mod-better-item-reloading
- mod-eluna
- mod-transmog

**Comment by Kitzunu** [comment]
1. 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/544db8cb-1726-4b3a-bc42-e466829785ec)

2. Fix your hash
3. Update your core
