### ISSUE TITLE
Setting any _triggeredCastFlags results in no indication of spell casting on client

### ISSUE THREAD

**Issue by 3ster** [azerothcore/azerothcore-wotlk#18226]
### Current Behaviour

Calling `Unit::CastSpell` with `_triggeredCastFlags` set to, for example, `TRIGGERED_IGNORE_POWER_AND_REAGENT_COST` causes no indication on the client that a spell is being cast.

### Expected Blizzlike Behaviour

The cast should proceed as normal, just without consuming power and/or reagents.

### Source

n/a

### Steps to reproduce the problem

1. Call `player->CastSpell(player, 3561, TRIGGERED_IGNORE_POWER_AND_REAGENT_COST)` (or use the Eluna script below to cast `Teleport: Stormwind`)
2. Observe no cast bar or `UNIT_SPELLCAST_START` event showing up on the client, and the player teleporting after the ten seconds cast time have elapsed

### Extra Notes

I'm not sure how this behaves on actual blizzard servers, but the behavior *feels* incorrect.  
I've also found an [issue in TrinityCore](https://github.com/TrinityCore/TrinityCore/issues/16687) from 2016 about this behavior, which was closed due to age.
It seems like this behavior is caused by `Spell::SendSpellStart()`  checking if *any* flags are set in `_triggeredCastFlags`, and setting `CAST_FLAG_PENDING` if so. Patching `Spell::SendSpellStart()` to *not* set `CAST_FLAG_PENDING`, in this case if `_triggeredCastFlags` is set to `TRIGGERED_IGNORE_POWER_AND_REAGENT_COST`, results in the, in my opinion, "correct" behavior:
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index e35decd..7adadb6 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4701,6 +4701,9 @@ void Spell::SendSpellStart()
 
     if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell()) || m_triggeredByAuraSpell) && !m_cast_count && !m_spellInfo->IsChanneled())
         castFlags |= CAST_FLAG_PENDING;
+    
+    if (this->_triggeredCastFlags == TRIGGERED_IGNORE_POWER_AND_REAGENT_COST)
+        castFlags ^= CAST_FLAG_PENDING;
 
     if (m_spellInfo->HasAttribute(SPELL_ATTR0_USES_RANGED_SLOT) || m_spellInfo->HasAttribute(SPELL_ATTR0_CU_NEEDS_AMMO_DATA))
         castFlags |= CAST_FLAG_PROJECTILE;
```

### AC rev. hash/commit

AzerothCore rev. c18bd641369e+ 2024-01-23 21:38:32 +0100 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 3 minute(s) 48 second(s)
Update time diff: 100ms, average: 100ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80035
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/app/data/maps. Total size: 291014951 bytes
vmaps directory located in /azerothcore/app/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/app/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_01_20_00.sql
Latest WorldDatabase update: 2024_01_23_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna

### Operating system

Ubuntu 22.04

### Custom changes or Modules

Single Eluna script used to test this behavior with a patched Eluna module:  
Script:
```lua
local PLAYER_EVENT_ON_COMMAND = 42
local command = "cc"

local function OnCommand(_, player, full_cmd, _)
    local cmd, arg = string.match(full_cmd, "^(%a*)%s*(%d*)%s*$")
    if cmd ~= command then
        return true
    end
    player:CastSpell(player, arg, nil, 4)
    return false
end

RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, OnCommand)
```  
Patch:  
```diff
diff --git a/src/LuaEngine/UnitMethods.h b/src/LuaEngine/UnitMethods.h
index 50e467b..4e06c03 100644
--- a/src/LuaEngine/UnitMethods.h
+++ b/src/LuaEngine/UnitMethods.h
@@ -7,6 +7,8 @@
 #ifndef UNITMETHODS_H
 #define UNITMETHODS_H
 
+#include <SpellDefines.h>
+
 /***
  * Inherits all methods from: [Object], [WorldObject]
  */
@@ -2199,11 +2201,12 @@ namespace LuaUnit
         Unit* target = Eluna::CHECKOBJ<Unit>(L, 2, false);
         uint32 spell = Eluna::CHECKVAL<uint32>(L, 3);
         bool triggered = Eluna::CHECKVAL<bool>(L, 4, false);
+        TriggerCastFlags triggerFlags = (TriggerCastFlags)Eluna::CHECKVAL<uint32>(L, 5, triggered ? TRIGGERED_FULL_MASK : TRIGGERED_NONE);
         SpellInfo const* spellEntry = sSpellMgr->GetSpellInfo(spell);
         if (!spellEntry)
             return 0;
-
-        unit->CastSpell(target, spell, triggered);
+        
+        unit->CastSpell(target, spell, triggerFlags);
         return 0;
     }
```

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/c18bd641369e1df670226654f65dbc174de093da/src/server/game/Spells/Spell.cpp#L4702

Not really. As you can see it only returns true if the spell is triggered and is not a channeled spell.

!m_spellInfo->IsChanneled()

The reason you are experiencing this is because spell 3561 is missing these spell attributes SPELL_ATTR1_IS_CHANNELED | SPELL_ATTR1_IS_SELF_CHANNELED and that is why the if statement above returns true

**Comment by Kitzunu** [comment]
So to correctly fix this I would propose to add something like
```cpp
.... && !m_spellInfo->CastTimeEntry(Whatever ID here for no cast time and unlimited casttime))

**Comment by Kitzunu** [comment]
Test this https://github.com/azerothcore/azerothcore-wotlk/pull/18228

**Comment by 3ster** [comment]
Doesn't seem to work for me - there's no cast bar showing up on the client. I've tested a similar patch, which seems to work (tested with `Teleport: Stormwind` for spell with cast time, and `Power Word: Shield` for an instant cast:
```diff
diff --git a/src/server/game/Spells/Spell.cpp b/src/server/game/Spells/Spell.cpp
index e35decd..e38ec55 100644
--- a/src/server/game/Spells/Spell.cpp
+++ b/src/server/game/Spells/Spell.cpp
@@ -4699,9 +4699,8 @@ void Spell::SendSpellStart()
 
     uint32 castFlags = CAST_FLAG_HAS_TRAJECTORY;
 
-    if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell()) || m_triggeredByAuraSpell) && !m_cast_count && !m_spellInfo->IsChanneled())
+    if (((IsTriggered() && !m_spellInfo->IsAutoRepeatRangedSpell()) || m_triggeredByAuraSpell) && !m_cast_count && !m_spellInfo->IsChanneled() && !(m_spellInfo->CastTimeEntry->CastTime > 0))
         castFlags |= CAST_FLAG_PENDING;

     if (m_spellInfo->HasAttribute(SPELL_ATTR0_USES_RANGED_SLOT) || m_spellInfo->HasAttribute(SPELL_ATTR0_CU_NEEDS_AMMO_DATA))
         castFlags |= CAST_FLAG_PROJECTILE;
 ```

**Comment by Kitzunu** [comment]
Yea true that makes more sense

**Comment by Kitzunu** [comment]
I updated it again, can you please also test that Eye of Acherus doesn't crash

**Comment by 3ster** [comment]
Correct me if I'm wrong, but I think there might be a logic issue in your PR, as far as I can tell the check should be
```c++
if (((IsTriggered() && [...] && !(m_spellInfo->IsChanneled() || (m_spellInfo->CastTimeEntry->CastTime > 0)))
```
and not
```c++
if (((IsTriggered() && [...] && (!m_spellInfo->IsChanneled() || !(m_spellInfo->CastTimeEntry->CastTime > 0)))
```
The former works fine with Eye of Acherus, the latter doesn't show a cast bar for my usual test spells.

**Comment by Kitzunu** [comment]
Yea you are right my bad
