### ISSUE TITLE
[Lunar fesival] Dalaran [Giant Spotlight] and [Greater Moonlight Spell Focus] spawn positioning problem

### ISSUE THREAD

**Issue by chaosua** [azerothcore/azerothcore-wotlk#18224]
### Current Behaviour

Lunar fesival **Giant Spotlight** (NPC id 15897 guid 61993) and **Greater Moonlight Spell Focus** (Go 180867 guid 241007) have diffrent spawn locations.  Greater Moonlight Spell Focus spawned, de facto, in the oposite corner
When I try to use item **Lunar Festival Invitation**  (21711) in visual Greater Moonlight it says I must be in Greater Moonlight. 

### Expected Blizzlike Behaviour

I must be able to use Lunar Festival Invitation in place where I see  **Moonlight** in Dalaran

### Steps to reproduce the problem

.additem 21711
.go creature 61993
try to use Lunar Festival Invitation => nothing happens)
.go gameobject 241007
try to use Lunar Festival Invitation => casting spell

### AC rev. hash/commit

d0eae390b61377c569af4bcf2ac647a23a21800b

### Operating system

Windows 10 x64

**Comment by sudlud** [comment]
gameobject `180867` does not show in sniffs, still it's required for the current implementation of the spotlight mechanics so I'll update the spawns accordingly
