### ISSUE TITLE
Pets spin uncontrollably on top of npcs that are casting targeted spells at them

### ISSUE THREAD

**Issue by GoonBoiBarry** [azerothcore/azerothcore-wotlk#18237]
### Current Behaviour

Pets that attack npcs casting spells at them move directly on top of the npcs position and spin around each other uncontrollably.

### Expected Blizzlike Behaviour

They should just attack and act like normal.

### Steps to reproduce the problem
1. Create a horde toon .gm on
2. go creature 19193
3. levelup 10
4. .npc tame a nearby bear
6. Send bear to attack dalaran apprentice 
7. Watch them spin like crazy

Alternate method with different pet type:
1. Create a horde toon .gm on
2. go creature 19193
3. Levelup 10
4. .learn 33831
5. cast force of nature on a dalaran apprentice 
6. Watch them spin like crazy

### AC rev. hash/commit

AzerothCore rev. a5cd23fa5b4b+ 2024-01-15 00:17:05 +0000 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win 10

**Comment by Tntdruid** [comment]
I have seen that a lot too using AzerothCore rev a5cd23f.

**Comment by Tntdruid** [comment]
Looks like this https://youtu.be/iRdqSLxljog

**Comment by GoonBoiBarry** [comment]
Your video is private fyi

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/assets/47818697/ce3d9f6e-5706-47f9-bf58-7e632b715779

**Comment by GoonBoiBarry** [comment]
I've worked out that this is unrelated to pets. It affects all npcs, but only certain spells cause it. For example Dalaran Apprentices cause will cause this affect on any mob targeting attacking them that they are casting at.

**Comment by GoonBoiBarry** [comment]
Okay so the source of the issue was in PetAI.cpp in the DoAttack function. On line 617, the pet is told to chase. If you replace this code with line 30 from UnitAI.cpp, the issue no longer occurs and the pet appears to function normally. I don't know how to do pull request and just sort of stumbled across this solution through trial and error, but if anyone experienced wants to officially fix this hopefully this helps.
