### ISSUE TITLE
 [Karazhan] The Mana Warp will not die if cast knockout skill before  HP 10% and hit to 0% during the stun period

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18234]
### Current Behaviour

if knockout the creature high than 10%, will not die.
if knockout the creature below to 10%, will kill self normaly.

### Expected Blizzlike Behaviour

The creature will always kill itself

### Steps to reproduce the problem

.go c 135720
.gm off
.gm vi on
target the Mana Warp and cast spell such as 10308 and then cast spell 27255 try kill it immediately.
the creature will not cast SAI link 2 and 3, and can not chage to Phasemask 1 and will never die.

### Extra Notes

I fixd it, so can always die if knockout high 10% HP, but I dont know if it same as blizzard.

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 16530);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(16530, 0, 0, 0, 25, 0, 100, 512, 0, 0, 0, 0, 0, 0, 42, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mana Warp - On Reset - Set HP Invincibility'),
(16530, 0, 1, 2, 2, 0, 100, 513, 0, 10, 0, 0, 0, 0, 11, 37079, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mana Warp - Between Health 0-10% - Cast Warp Breach'),
(16530, 0, 2, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 0, 11, 29919, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mana Warp - Between Health 0-10% - Cast Warp Breach'),
(16530, 0, 3, 0, 2, 0, 100, 512, 0, 10, 0, 0, 0, 0, 22, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mana Warp - Between Health 0-10% - Set Event Phase'),
(16530, 0, 4, 0, 0, 1, 100, 512, 2500, 2500, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Mana Warp - In Combat - Die');

### AC rev. hash/commit

Because I fixed some problem but dont know how to pull request to the master, so I fork the master and hash might not same as master version

https://github.com/kissingers/acore-wow

AzerothCore rev. 310bb4d60ac7 2024-01-21 22:18:47 +0800 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 15. Characters in world: 15.
Connection peak: 93.
服务器运行时间: 8 hour(s) 47 minute(s) 44 second(s)
Update time diff: 10ms, average: 10ms.
Using SSL version: OpenSSL 3.0.11 19 Sep 2023 (library: OpenSSL 3.0.11 19 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101104
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.5.11-7-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 34345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
                         All available DBC locales: zhCN 
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: zone_difficulty_instance_saves.sql
Latest WorldDatabase update: zone_difficulty_spelloverrides.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-anticheat
- mod-bg-reward
- mod-cfbg
- mod-eluna
- mod-multi-client-check
- mod-npc-beastmaster
- mod-pvp-titles
- mod-reward-played-time
- mod-save-inventory
- mod-server-auto-shutdown
- mod-zone-difficulty
- mod_spec_reward

### Operating system

debian12 x64

**Comment by kissingers** [comment]
just change ID 2 not link to ID 3, and ID 3 separate change Health 0-10% set Event Phase 1, so always can run ID 4

**Comment by kissingers** [comment]
But nobody said the problem a few months ago, and I compared the old SAI with the master SAI, no difference, so suspect that some Core/SAI PR has caused a problem, case the the original SAI ID 2 if break by some spell, it will not action, so can not continue link to 3.

**Comment by sudlud** [comment]
Yes I also think that there's a general core issue with SAI casting / creature targeting right now, see e.g. #18225.
Also other related issues start showing up.

**Comment by sudlud** [comment]
Was this fixed with a recent PR?

**Comment by elthehablo** [comment]
Ye https://github.com/azerothcore/azerothcore-wotlk/pull/18255

**Comment by kissingers** [comment]
Just fixed the SAI, not change the SAI source code, so might some SAI logic creature have same problem, but can fix just like https://github.com/azerothcore/azerothcore-wotlk/pull/18255

**Comment by elthehablo** [comment]
> Just fixed the SAI, not change the SAI source code, so might some SAI logic creature have same problem, but can fix just like https://github.com/azerothcore/azerothcore-wotlk/pull/18255

The problem here was the spell wasn't properly firing. So that is the issue. Otherwise the link would have worked
