### ISSUE TITLE
Sartharion 10/25 bug area event [$10]

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#1826]
Sartharion 10/25 bug area event

Description:
When the event starts players can leave the central area and move to any place in the sanctuary with the boss behind them.
The lava does not affect the event and the 3 drakes arrive in the central zone without participating in the event.

This checked in:
 last master branch + full history
 latsmaster branch + no previous history
 last master all branches and all history

Not modules
Latest commit dd4d892
Ubuntu 16.04

**Comment by FrancescoBorzi** [comment]
@solidmaxtor can you please include your AC version (commit hash) ?

**Comment by solidmaxtor** [comment]
i think so Latest commit dd4d892 the last show, i am compile and testing 12 hours ago aprox.

**Comment by Seebaby** [comment]
Yes I can confirm it is possible to refuel Sartharion at the entrance the 3 kites come but to a flown.

Video https://youtu.be/kTnuJ47lvSE

AzerothCore rev. f05fee74365a+ 2019-05-13 17:15:14 +0000 (master branch) (Win64, Release)

**Comment by Pondaveia** [comment]
These videos are really helpful @Seebaby thank you. Another boss bug to take care of :joy:

**Comment by Knindzagxg** [comment]
No please.

When you test Raid boss or anything, u can't have Divine up which will mitigate everything.
Sartharion works perfectly, and yes, you can move him out of central area.

Problem u have is cause divine shield and you cant be affected by Pyrobuffet, which is cast on you every now and then once you move Sartharion away from lava.

https://www.wowhead.com/spell=57557/pyrobuffet

**Comment by Selyria** [comment]
> Nein, bitte.
> 
> Wenn du den Raid-Boss oder irgendetwas testest, kannst du Divine nicht haben, was alles mildert. 
> Sartharion funktioniert perfekt, und ja, Sie können ihn aus dem zentralen Bereich bewegen.
> 
> Das Problem, das du hast, ist der göttliche Schild, und du kannst nicht von Pyrobuffet betroffen sein, das von Zeit zu Zeit auf dich gewirkt wird, sobald du Sartharion von der Lava entfernst.
> 
> https://www.wowhead.com/spell=57557/pyrobuffet

Okay, the video was just to show that the dragons are still coming.

The boss is putting a pyro buffet on the player if you pull him out of the zone.

So he is deadly if you pull him out of the zone.
