### ISSUE TITLE
Build errors on Windows 11 with OpenSSL 3.0.x

### ISSUE THREAD

**Issue by stoudtlr** [azerothcore/azerothcore-wotlk#18281]
### Current Behaviour

Wiki states to use OpenSSL 3.0.x
<img width="258" alt="image" src="https://github.com/azerothcore/azerothcore-wotlk/assets/36058236/86600b2e-476a-4c38-9be2-162d13e27611">
Wiki states to download from here:
https://slproweb.com/products/Win32OpenSSL.html
Only SSL version available at link provided by wiki that works is 1.1.1w.  Using OpenSSL 3.0.13 or 3.1.5 both result in cmake errors.
<img width="380" alt="image" src="https://github.com/azerothcore/azerothcore-wotlk/assets/36058236/c7648625-a15a-4387-b3db-f433669d7ff7">

### Expected Blizzlike Behaviour

compile without errors

### Steps to reproduce the problem

Follow Windows instructions and try using OpenSSL 3.0.13 or 3.1.5 from https://slproweb.com/products/Win32OpenSSL.html

### Extra Notes

Build completes without errors if using 1.1.1w which is available at the link from the Wiki.  Also tried version 3.1.2 as suggested in AzerothCore discord and that version works as well.  Available from https://www.filehorse.com/download-openssl-64/81965/download/

Search discord and there are a few recent comments about OpenSSL errors in cmake

### AC rev. hash/commit
Commit = e2f1648
<img width="295" alt="image" src="https://github.com/azerothcore/azerothcore-wotlk/assets/36058236/1f15a065-2cc8-4e7c-b1a9-6232c6ad36c2">

### Operating system

Windows 11 x64

### Custom changes or Modules

none

**Comment by pangolp** [comment]
When hashing, just use the URL
Because if not, the invalid label will appear.
