### ISSUE TITLE
Minigob Manabonk - Incorrect Event Timers

### ISSUE THREAD

**Issue by Cinnamohn** [azerothcore/azerothcore-wotlk#18286]
### Current Behaviour

Minigob Manabonk's event timers were converted incorrectly awhile back. He spawns in and despawns immediately because they are set to 3ms instead of 3000ms.

### Expected Blizzlike Behaviour

3-second delay on despawn

### Steps to reproduce the problem

Sit in Dalaran.

### Extra Notes

zone_dalaran.cpp -> CreatureScript("npc_minigob_manabonk")
EVENT_BLINK - 3 sec
EVENT_DESPAWN - 3 sec
EVENT_DESPAWN_VISUAL - 2.5 sec

### AC rev. hash/commit

a1891d8

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
add output of .server debug

the proveided hash is invalid

**Comment by Cinnamohn** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/a1891d8d8f8acd42dc1bd0c55ef4be3a8763cac9
