### ISSUE TITLE
[Quest] Marsh Frog Legs 

### ISSUE THREAD

**Issue by Tolkinz** [azerothcore/azerothcore-wotlk#18291]
### Current Behaviour

- Giant Marsh Frog(Lv1 critter) does not drop anything while it is supposed to drop Marsh Frog Leg 100%
![Marsh_Frog_02](https://github.com/azerothcore/azerothcore-wotlk/assets/105026618/739ae53e-1ca8-4762-a901-4f4fd384b5ee)

Quest ID : 1218 Marsh Frog Legs
Creature ID : 23979 Giant Marsh Frog
Drop ID : 33202 Marsh Frog Legs

![Marsh_Frog_01](https://github.com/azerothcore/azerothcore-wotlk/assets/105026618/9cde4b02-ee39-4a11-a08e-aa84283e6d61)

* I do not see any weird numbers within creature_loot_template, it looks like 100% drop, but still it drops nothing.

### Expected Blizzlike Behaviour

Giant Marsh Frog should drop quest objects.

### Steps to reproduce the problem

.quest add 1218
.tele SwamplightManor
/target Giant Marsh Frog
/attack

### AC rev. hash/commit

AzerothCore rev. 901d58cdc476 2024-02-01 16:06:31 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 21 minute(s) 14 second(s)
Update time diff: 3ms, average: 7ms.
Using SSL version: OpenSSL 3.0.12 24 Oct 2023 (library: OpenSSL 3.0.12 24 Oct 2023)
Using Boost version: 1.81.0
Using CMake version: 3.25.2
Using MySQL version: 80036
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in D:/WorldofWarcraft/Server Builds/3.3.5a/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in D:/WorldofWarcraft/Server Builds/3.3.5a/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in D:/WorldofWarcraft/Server Builds/3.3.5a/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_01_20_00.sql
Latest WorldDatabase update: 2024_02_01_01.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Win11 x64

**Comment by chaosua** [comment]
relraleted to https://github.com/azerothcore/azerothcore-wotlk/issues/16374

**Comment by Tolkinz** [comment]
upon your tip, I tried below methods as a 40 lock

rain of fire, hellfire, shadow bolt, wand/shoot = yield loot
curse of agony, corruption, melee auto attack, drain soul, drain life = no loot

Probably wand would be the most convenient way to do this of all, only if I knew there resides such an issue.

**Comment by Tolkinz** [comment]
ahh okay.
All I can see is that fix would not be simple and quick.
Thanks for your attention.

**Comment by Kitzunu** [comment]
Duplicate`
