### ISSUE TITLE
PvPToken.enable doesn't work

### ISSUE THREAD

**Issue by bigkoroush** [azerothcore/azerothcore-wotlk#183]
**Description**:
in config server PvPToken.enable=1 but that doesn't work !
**Current behaviour**: Tell us what happens
dosent receive Reward for killers
**Expected behaviour**: Tell us what should happen instead
must receive reward an item in config file item id 
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
##

**Comment by talamortis** [comment]
when its enabled does it give you any sort of item? defult is 29434 (Badge of Justice)

**Comment by bigkoroush** [comment]
no , not happend !and i set emblem of heroism (40752) but not change
and i set PvPToken.MapAllowType = 4 and any other type has not diffrent

**Comment by bigkoroush** [comment]
i found this >http://emudevs.com/showthread.php/919-Two-questions< but can't test

**Comment by talamortis** [comment]
can you try getting the server type to ffa type 16, & test please just a hinch 👍

**Comment by bigkoroush** [comment]
i test all type ,nothing

**Comment by sucofog** [comment]
I,ll test this out, but i think it was working

**Comment by ShinDarth** [comment]
any news?

**Comment by bigkoroush** [comment]
Dont Work For Me :(( I Test all Method but not work

**Comment by boom8866** [comment]
With IP does not have a role

**Comment by bigkoroush** [comment]
@boom8866  exactly i most what to do ? for enable this

**Comment by boom8866** [comment]
Function module has been removed, this is a missing feature

**Comment by Franklampardst** [comment]
confirm , not working PvP Token
