### ISSUE TITLE
build error on raspberry pi 4b after #18295

### ISSUE THREAD

**Issue by sandbox404** [azerothcore/azerothcore-wotlk#18307]
### Current Behaviour

[ 15%] Building CXX object src/server/database/CMakeFiles/database.dir/Database/MySQLConnection.cpp.o
/home/pi/azerothcore/src/server/database/Database/MySQLConnection.cpp:231:9: fatal error: use of undeclared identifier 'mysql_stmt_bind_named_param'
    if (mysql_stmt_bind_named_param(msql_STMT, msql_BIND, m_mStmt->GetParameterCount(), nullptr))
        ^
[ 15%] Linking CXX executable map_extractor
1 error generated.
make[2]: *** [src/server/database/CMakeFiles/database.dir/build.make:189: src/server/database/CMakeFiles/database.dir/Database/MySQLConnection.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1052: src/server/database/CMakeFiles/database.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 15%] Built target map_extractor
[ 15%] Linking CXX executable mmaps_generator
[ 15%] Built target mmaps_generator
make: *** [Makefile:136: all] Error 2

### Expected Blizzlike Behaviour

build success

### Steps to reproduce the problem

1. sudo apt update && sudo apt-get install git cmake clang default-libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mariadb-server libboost-all-dev
2. git clone https://github.com/azerothcore/azerothcore-wotlk.git --branch master --single-branch azerothcore
3. mkdir azerothcore/build
4. cd azerothcore/build
5. cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static -DCMAKE_BUILD_TYPE=Release
6. make -j3

### AC rev. hash/commit

6b1dd7e19ef52c2760d65849a31a29af70ad9795

### Operating system

Debian 12 arm64

**Comment by 0xCiBeR** [comment]
Same error on latest pull 1d8c4056b3b8671fef2e356d940cef493de5f6d5 for ubuntu 22.04

**Comment by pangolp** [comment]
Are you using MariaDB? Surely I made the mistake there since when I made the pull request to correct the problems on Mac, it did not cause any problems in the compilation, however, the if talks about the MySQL version, it does not say anything about MariaDB. I'll have to modify the conditional.

**Comment by pangolp** [comment]
Initially, the pull request was not intended to replace the method, based on the version of MySQL, but rather, based on the version of the operating system. But obviously, and despite passing all the tests, this error now appeared, so the condition will have to be modified.

**Comment by pangolp** [comment]
```
#ifdef _CUSTOMCONFIG_
#include <custom_conf.h>
#else
#define PROTOCOL_VERSION                10
#define MARIADB_CLIENT_VERSION_STR      "10.11.4"
#define MARIADB_BASE_VERSION            "mariadb-10.11"
#define MARIADB_VERSION_ID              101104
#define MARIADB_PORT                    3306
#define MARIADB_UNIX_ADDR               "/run/mysqld/mysqld.sock"
#ifndef MYSQL_UNIX_ADDR
#define MYSQL_UNIX_ADDR MARIADB_UNIX_ADDR
#endif
#ifndef MYSQL_PORT
#define MYSQL_PORT MARIADB_PORT
#endif

#define MYSQL_CONFIG_NAME               "my"
#define MYSQL_VERSION_ID                101104
#define MYSQL_SERVER_VERSION            "10.11.4-MariaDB"
```

That's the problem, they keep using the same variable.

**Comment by pangolp** [comment]
I made a mistake when setting the condition.

`#if !defined(MARIADB_VERSION_ID) && MYSQL_VERSION_ID >= 80300`

Now I replace it and the problem should be solved.
I didn't know that both of them were still using the same constants after so much time.
