### ISSUE TITLE
Feature: Any way to see SQL changes when GM uses commands such as ".npc add", ."npc move", ."npc del"?

### ISSUE THREAD

**Issue by PadreWoW** [azerothcore/azerothcore-wotlk#18317]
### Describe your feature request or suggestion in detail

When GM uses commands such as ".npc(.gobj) add", ".npc(.gobj) move", ".npc(.gobj) del", there are SQL changes: adding new npc(go) to DB, changes "xyz" coords for the npc(go), deleting npc(go) from DB
But nothing can be seen in server console
Any way to see that changes in server console or in *.log file?

**Comment by Kitzunu** [comment]
Enable the GM appender and you will get a log of all gm commands used

**Comment by PadreWoW** [comment]
Not GM commands
SQL changes
You use command (.npc move for example) and can see only gm log in console, but not sql change!

For example on Oregon in logSQL.log file you can see this:

2024-01-21 14:03:39 UPDATE `world`.`creature` SET `position_x` = '-2843.992676', `position_y` = '3986.055420', `position_z` = '1.306372', `orientation` = '0.158082' WHERE `guid` = '68308';

**Comment by pangolp** [comment]
At this moment, I don't know if the emulator has a mechanic like the one you describe.

**Comment by PadreWoW** [comment]
Old OregonCore has such mechanic
Maybe anyone can look there and port it here?
Unfortunately I don't have enough experience

**Comment by PadreWoW** [comment]
Easy way to add such logs:

diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index e71ef8759..f6995bf08 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -1790,6 +1790,11 @@ void Creature::DeleteFromDB()
 
     WorldDatabaseTransaction trans = WorldDatabase.BeginTransaction();
 
+    LOG_WARN("sql", "DELETE FROM `creature` WHERE `guid` = '{}';", m_spawnId);
+    LOG_WARN("sql", "DELETE FROM `creature_addon` WHERE `guid` = '{}';", m_spawnId);
+    LOG_WARN("sql", "DELETE FROM `game_event_creature` WHERE `guid` = '{}';", m_spawnId);
+    LOG_WARN("sql", "DELETE FROM `game_event_model_equip` WHERE `guid` = '{}';", m_spawnId); // any other tables to delete creature?
+
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_CREATURE);
     stmt->SetData(0, m_spawnId);
     trans->Append(stmt);

**Comment by PadreWoW** [comment]
I don't know how to add DB name here (not manually!) -> "DELETE FROM <DB NAME>.creature

**Comment by PadreWoW** [comment]
Ok I found the way, but i'm not shure that the way is correct

diff --git a/src/server/database/Database/DatabaseWorkerPool.h b/src/server/database/Database/DatabaseWorkerPool.h
index 4cf6a2e92..b717c0ace 100644
--- a/src/server/database/Database/DatabaseWorkerPool.h
+++ b/src/server/database/Database/DatabaseWorkerPool.h
@@ -229,7 +229,7 @@ public:
 
     [[nodiscard]] size_t QueueSize() const;
 
-private:
+public:
     uint32 OpenConnections(InternalIndex type, uint8 numConnections);
 
     unsigned long EscapeString(char* to, char const* from, unsigned long length);

diff --git a/src/server/game/Entities/Creature/Creature.cpp b/src/server/game/Entities/Creature/Creature.cpp
index e71ef8759..a943842af 100644
--- a/src/server/game/Entities/Creature/Creature.cpp
+++ b/src/server/game/Entities/Creature/Creature.cpp
@@ -15,6 +15,7 @@
  * with this program. If not, see <http://www.gnu.org/licenses/>.
  */
 
+#include "DatabaseWorkerPool.h"
 #include "Creature.h"
 #include "BattlegroundMgr.h"
 #include "CellImpl.h"
@@ -1790,6 +1791,11 @@ void Creature::DeleteFromDB()
 
     WorldDatabaseTransaction trans = WorldDatabase.BeginTransaction();
 
+    LOG_WARN("sql", "DELETE FROM `{}`.`creature` WHERE `guid` = '{}';", WorldDatabase.GetDatabaseName(), m_spawnId);
+    LOG_WARN("sql", "DELETE FROM `{}`.`creature_addon` WHERE `guid` = '{}';", WorldDatabase.GetDatabaseName(), m_spawnId);
+    LOG_WARN("sql", "DELETE FROM `{}`.`game_event_creature` WHERE `guid` = '{}';", WorldDatabase.GetDatabaseName(), m_spawnId);
+    LOG_WARN("sql", "DELETE FROM `{}`.`game_event_model_equip` WHERE `guid` = '{}';", WorldDatabase.GetDatabaseName(), m_spawnId);
+
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_CREATURE);
     stmt->SetData(0, m_spawnId);
     trans->Append(stmt);

**Comment by PadreWoW** [comment]
Can anyone test it please?
Is 
-private:
+public:
critical?

**Comment by blazery** [comment]
Im willing to test this later if you can create a PR or branch with patch files. Im not feeling copying these changes manually into the correct files.

**Comment by PadreWoW** [comment]
`
diff --git a/src/server/database/Database/DatabaseWorkerPool.h b/src/server/database/Database/DatabaseWorkerPool.h
index 4cf6a2e92..b717c0ace 100644
--- a/src/server/database/Database/DatabaseWorkerPool.h
+++ b/src/server/database/Database/DatabaseWorkerPool.h
@@ -229,7 +229,7 @@ public:
 
     [[nodiscard]] size_t QueueSize() const;
 
-private:
+public:
     uint32 OpenConnections(InternalIndex type, uint8 numConnections);
 
     unsigned long EscapeString(char* to, char const* from, unsigned long length);
`

**Comment by PadreWoW** [comment]
Patch file for .npc command in attach
[0001-Core-Log-SQL-Changes-When-Using-.npc-Commands.patch](https://github.com/azerothcore/azerothcore-wotlk/files/14279334/0001-Core-Log-SQL-Changes-When-Using-.npc-Commands.patch)
