### ISSUE TITLE
Not able to create custom Trainers

### ISSUE THREAD

**Issue by New-HavenWotLK** [azerothcore/azerothcore-wotlk#18321]
### Current Behaviour

Wanted to create some custom Trainers... all Flags are properly setted... still there does not pop up a trainer window.

Even tried it with a copied version of an already existing trainer... same result... the original trainer works fine, the custom npc with the very same trainer data setted does not work.

### Expected Blizzlike Behaviour

It should pop up the training window of that NPC when creating a custom trainer NPC with proper trainer flags and npc_trainer entries 

### Steps to reproduce the problem

1: Create a fresh NPC and give him trainer flags or copy an already existing trainer to a fresh entry
2: Give the NPC proper values within npc_trainer
3: The original NPC will work as a trainer, the fresh made with kinda the same values besides the ID does not work.

### Extra Notes

I checked btw: 
this happened also already on the revision from 31.01.2024 and the revision from 09.04.2023, as well as on an even earlier revision from april 2022!

so yeah... something doesn't get pushed properly it seems or idk =/

### AC rev. hash/commit

b6ee4f49cfbf

### Operating system

Win Server 2019

### Custom changes or Modules

none

**Comment by Elmsroth** [comment]
@New-HavenWotLK we cannot reproduce since you do not give the SQL code of your custom trainer.
We should test in teh same conditions (same flags etc.. same values...)

**Comment by New-HavenWotLK** [comment]
> @New-HavenWotLK we cannot reproduce since you do not give the SQL code of your custom trainer. We should test in teh same conditions (same flags etc.. same values...)

Here the SQL code of the npc entry as well as of the trainer entry... it is planned in regular to handle him then later via lua to be a trainer and multivendor... multivendor itself works great... just that damn trainer does not push somehow the trainer window, even when rn like here only setted with trainerflags. =/

-- npc_trainer table:
INSERT INTO `npc_trainer`(`ID`, `SpellID`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqLevel`, `ReqSpell`) VALUES (500048, -202011, 0, 0, 0, 0, 0);
INSERT INTO `npc_trainer`(`ID`, `SpellID`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqLevel`, `ReqSpell`) VALUES (500048, -202010, 0, 0, 0, 0, 0);

-- creature_template table:
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(500048, 0, 0, 0, 0, 0, 23477, 0, 0, 0, 'Krerel Morningspirit', 'Multi Trainer and Vendor', 'Buy', 0, 80, 80, 0, 35, 113, 1, 1.14286, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2048, 0, 0, 1, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, '', 0);

**Comment by Grimfeather** [comment]
Have you maybe been able to solve this? I ran into the same issue today.

Created new npc with exactly the same data as the trainer I copied. Training window won't open.

**Comment by New-HavenWotLK** [comment]
> Have you maybe been able to solve this? I ran into the same issue today.
> 
> Created new npc with exactly the same data as the trainer I copied. Training window won't open.

actually yes...

atm i used a NPC ID below 200k it worked xD

**Comment by Nyeriah** [comment]
Overflow, use lower ids

**Comment by New-HavenWotLK** [comment]
> Overflow, use lower ids

yeah thought so, that's when i used a lower entry and checked till which entry it is working ^^

just would be dope actually, when there would be at least an info message console sided about the overflow.

**Comment by AnVenDev** [comment]
I'm facing the same problem right now. Does anyone have a valid solution?
