### ISSUE TITLE
In worldserver.com

### ISSUE THREAD

**Issue by Dutty-yh** [azerothcore/azerothcore-wotlk#18320]
### Current Behaviour

In worldserver.conf

#AllowTwoSide Accounts=0

Camp restrictions not in effect

### Expected Blizzlike Behaviour

no

### Steps to reproduce the problem

It is not related to whether the account is level 3 or not

### AC rev. hash/commit

PLAYER INTERACTION

### Operating system

 Windows 10 x64

**Comment by pangolp** [comment]
For the report to be valid, please add the URL of the commit used in the build and also change the title, so that it is representative of the problem or topic that is being discussed here in this issue. Thank you.
