### ISSUE TITLE
ICC 10/25 switching normal to heroic

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#1833]
##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you enter a raid in 10 man normal and kill a boss, you can't get out the dungeon and re-do the same dungeon in 10 man heroic because the 10 modes share the same ID. For example:

Kill Lich King in 10 man normal do get atunement with Icecrown Citatel. When the Raids reset, you can't re-do 10 man normal, finish the raid and then do it in 10 man heroic because you are saved. The same happens with 25 man modes.

##### STEPS TO REPRODUCE THE PROBLEM:

1. You need to kill 10 man normal Lich King in Icecrown Citatel to have eligibility for 10 man heroic 
2. Reset your raid id
3. Choose 10 man normal raid mode and re-do Icecrown Citatel
4. Switch to 10 man heroic mode

Still unsure if this behavior happens with other Normal/Heroic raids that require atunement.

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Debian 8

**Comment by Pondaveia** [comment]
Sorry I'm didn't understand this issue, maybe use a traducer? Or if you tell us your mother tongue someone in the team might be able to understand what's the problem.

**Comment by mpfans** [comment]
Chinese

**Comment by mpfans** [comment]
> Sorry I'm didn't understand this issue, maybe use a traducer? Or if you tell us your mother tongue someone in the team might be able to understand what's the problem.

sorry,my English is very poor,I am a Chinese

**Comment by Pondaveia** [comment]
@mpfans We appreciate your report. Maybe try using this translator to see if we understand what's the problem. 

https://translate.yandex.com/?lang=en-zh

Or you can always try to find someone Chinese in our discord channels:
https://discord.gg/rGpc9V

**Comment by mpfans** [comment]
> @mpfans We appreciate your report. Maybe try using this translator to see if we understand what's the problem.
> 
> https://translate.yandex.com/?lang=en-zh
> 
> Or you can always try to find someone Chinese in our discord channels:
> https://discord.gg/rGpc9V

ICC 10   OR 10 hero , you know?

**Comment by Pondaveia** [comment]
Talked to @mpfans to understand the issue and updated description for him. This needs further research.

**Comment by Maurowin** [comment]
No in the end of WOTLK, you don't need finish ICC normal mode to do it heroic mode.

**Comment by mpfans** [comment]
> ## Raids in 10 and 25 man Normal/Heroic
> ##### EXPECTED BLIZZLIKE BEHAVIOUR:
> When you enter a raid in 10 man normal and kill a boss, you can't get out the dungeon and re-do the same dungeon in 10 man heroic because the 10 modes share the same ID. For example:
> 
> Kill Lich King in 10 man normal do get atunement with Icecrown Citatel. When the Raids reset, you can't re-do 10 man normal, finish the raid and then do it in 10 man heroic because you are saved. The same happens with 25 man modes.
> 
> ##### STEPS TO REPRODUCE THE PROBLEM:
> 1. You need to kill 10 man normal Lich King in Icecrown Citatel to have eligibility for 10 man heroic
> 2. Reset your raid id
> 3. Choose 10 man normal raid mode and re-do Icecrown Citatel
> 4. Switch to 10 man heroic mode
> 
> Still unsure if this behavior happens with other Normal/Heroic raids that require atunement.
> 
> ##### BRANCH(ES):
> master
> 
> ##### OPERATING SYSTEM:
> Debian 8
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74108435-icc-10-25-switching-normal-to-heroic?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).

if killed 10 man normal Lich King in Icecrown Citatel, and then next week..you can't in any 10 man raid,at will switch 10 man normal/heroic mode.

**Comment by Pondaveia** [comment]
What do you mean with can't in any 10 man raid? You can't join 10 man's after the weekly reset?

**Comment by mpfans** [comment]
> What do you mean with can't in any 10 man raid? You can't join 10 man's after the weekly reset?

sry,I mean "in any 10 man raid,can't switch 10 man normal/heroic mode."

**Comment by Pondaveia** [comment]
Is that what's supposed to happen or is that the current behavior on azerothcore?

**Comment by mpfans** [comment]
this is  supposed to happen 
"in any 10 man raid,can't switch 10 man normal/heroic mode."

**Comment by pklloveyou** [comment]
#
#    Instance.SharedNormalHeroicId
#        共享正常与英雄副本进度
#        默认：    0 - （禁用）
#                      1 - （启用）

Instance.SharedNormalHeroicId = 0

**Comment by mpfans** [comment]
> # Instance.SharedNormalHeroicId
> # 默认： 0 - （禁用）
> # 1 - （启用）
> Instance.SharedNormalHeroicId = 0

国服原来是可以在副本内切难度的...这个开启后是不是可以切换了?

**Comment by mpfans** [comment]
Instance.SharedNormalHeroicId = 1   

 issue resolved
