### ISSUE TITLE
[TBC Shattrath] Kirembri Silvermane

### ISSUE THREAD

**Issue by Grimfeather** [azerothcore/azerothcore-wotlk#18358]
### Current Behaviour

https://www.wowhead.com/npc=33637/kirembri-silvermane

She seems to be missing. Can someone confirm this please?
She is the jewelcrafting trainer in Shattrath in the Scryers area.
I checked the database and I can find her in 'creature_template', but she's missing in the 'creature' database
So as far as I can tell, she hasn't been placed in the world yet.

I'm using the Individual progression module, so I first checked if that module maybe disabled her, but I don't think it does.
I checked because she was added in patch 3.1 and she doesn't show up in wowhead TBC.

### Expected Blizzlike Behaviour

well, for her to be in the world of course.

### Steps to reproduce the problem

1. check the database
2. check her location in Shattrath

### Extra Notes

for anyone finding her missing like me.
you can add her with a GM account.
stand on the location you want her to be at and type:
.npc add 33637

### AC rev. hash/commit

AzerothCore rev. 4ef3ff79c204 2024-02-10 14:58:59 +0700 (npcbots_3.3.5 branch)

### Operating system

Windows 10

### Custom changes or Modules

Individual progression, reagent bank, lua engine

**Comment by sudlud** [comment]
just checked this on 86bff2761

she's right in the spot that wowhead shows, GUID 88267.

It's also in the base creature.sql files:

https://github.com/azerothcore/azerothcore-wotlk/blob/86bff276112226cd8768930fd37b918f8a372f27/data/sql/base/db_world/creature.sql#L85218

so this issue is invalid on a clean AC install.
