### ISSUE TITLE
[SAI] Weird issue

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1835]
Hey,

Few players on my server found really weird issue in Borean Tundra at Fizcrank Airstrip.

There's mini event, when Robot drags plane, Fighter come from house, get inside and start flying around zone -> Works really nice.

Script wise, everything is perfect, there's no errors when checked and everything should work as supposed.

But problem is next:

* If there's no player in zone and around Airport, event keep spawning more and more.
Due to script, fighters should be despawned and they are, same as planes, but for some weird reason plane remain in air.

* If there's player to follow plane, it will despawn, but once out of sight, it will just stand in one position until more and more catch up.

He took picture with phone, cause FPS droped like CRAZY.
I went to check and even with latest PC configuration, my FPS droped to 10.
When checked DB, there was over 120 guides for plane after 2 hours of server working.

This can be huge memory issue for someone who don't have resources.
I disabled SAI for all 3 NPCS at once, and world working with much less memory now.

NPC ID's: 26817, 25765, 25766
SAI is from official TC, long time ago

How to test:

1. Go to Borean Tundra, or teleport to Airport
2. Find planes and try to follow them to proc despawn
3. Wait for new to summon and mark with Raid marker
4. .tele to Stormwind or etc
5. Wait there 5 minutes and then recall
6. Plane will be in same position when u left

Latest Master commit tho, always up to date.

![image1](https://user-images.githubusercontent.com/27079035/57788728-e3c8b900-7737-11e9-8bd1-2769af6183b2.jpg)

**Comment by Selyria** [comment]
Yes I can confirm as soon as you are out of range the plane stops and stops. 

Airplanes start when players are at the airport when you drag it out for a few days some 100-1000 airplanes can come together depending on the number of players.

**Comment by poszer** [comment]
Big issue, and need to be tracked as high priority
