### ISSUE TITLE
Server crash when returning the quest "The Boon of Remulos"

### ISSUE THREAD

**Issue by lach3v** [azerothcore/azerothcore-wotlk#18353]
### Current Behaviour

The server crashes when someone returns the quest "the boon of remulos" (quest id 13075) to Crusader Bridenbrad (creature id 30562) in Icecrown.

This was also tested and confirmed by another person.

### Expected Blizzlike Behaviour

The player should return the quest and get a quest reward.

### Steps to reproduce the problem

.quest add 13075
.quest complete 13075
.go creature id 30562
Return the quest

### AC rev. hash/commit

AC> AzerothCore rev. f72174c6221b 2024-02-04 14:12:06 +0000 (master branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 20 minute(s) 40 second(s)
Update time diff: 1ms, average: 3ms.
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using CMake version: 3.16.3
Using MySQL version: 80036
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.4.0-153-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-1v1-arena
- mod-ah-bot
- mod-anticheat
- mod-aoe-loot
- mod-autobalance
- mod-cfbg
- mod-chat-login
- mod-eluna
- mod-individual-xp
- mod-multi-client-check
- mod-pvp-titles
- mod-server-auto-shutdown
- mod-solo-lfg
- mod-transmog
- mod-world-chat

### Operating system

Ubuntu 20.04.5 LTS

**Comment by heyitsbench** [comment]
Please attach the crashlog.

**Comment by lach3v** [comment]
My GDB isn't enabled currently, but I will do it and eventually post

**Comment by Tilenozz** [comment]
Hi, same trouble. Gdb file in attach
[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/14351715/gdb.txt)

**Comment by Elmsroth** [comment]
Bug related to CastTimeEntry wich is nullptr :
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/1208311/c5843a6f-6320-4bf6-a0ec-726cc4c4e7d9)

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/18379
