### ISSUE TITLE
 The items in the chests multiply

### ISSUE THREAD

**Issue by mchang10** [azerothcore/azerothcore-wotlk#18363]
### Current Behaviour

Chests containing loot increase in number after each server restart

### Expected Blizzlike Behaviour

The amount should not increase

### Steps to reproduce the problem

1. Get a lootable chest

2. Check the chest without removing anything

3. Restart server.

4. Look again at the items inside the chest.

### AC rev. hash/commit

.Server restart

### Operating system

Window 10

**Comment by sudlud** [comment]
Thanks for the report.
Can you please add the output of
.server debug

Also can you please specify the steps to reproduce the issue.
- go to chest xyz
- ...

Thanks.
