### ISSUE TITLE
Quest : Bury Those Cockroaches!

### ISSUE THREAD

**Issue by Tilenozz** [azerothcore/azerothcore-wotlk#18396]
### Current Behaviour

On this quest is require to set a bomb on a determinated place.
The bomb is corretly placed , but when exploded do not count as execeuted.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/54805850/54cd30bd-3266-4e26-a810-91f4b3f059b9)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/54805850/56842ff8-791e-4f20-a2f9-eb9c4aebce00)

### Expected Blizzlike Behaviour

count the place as done

### Steps to reproduce the problem

.quest add 11608
.tele warsong

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/e311bacfe580046a333e88f43f7c1dc251b60a9a 2024-02-21 06:41:57 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04

**Comment by avarishd** [comment]
Was able to complete the quest without any issues, bunch of times.
