### ISSUE TITLE
Spiritual Attunement Doesn't work

### ISSUE THREAD

**Issue by Motorheadx** [azerothcore/azerothcore-wotlk#184]
Description :

A passive ability that gives the Paladin mana when healed by other friendly targets' spells. The amount of mana gained is equal to a percentage of the amount healed.

Link :

http://old.wowhead.com/spell=31786

Bug :

When the paladin is healed, he receives no mana.

Hope my english is understandable

**Comment by HeartWell** [comment]
Все прекрасно работает, талант вот http://merlin.org.ua/wowhead2/?spell=33776.

**Comment by Motorheadx** [comment]
а почему же тогда в комбат лог у меня не пишется то что действует этот талант или он скрытый ?)

**Comment by HeartWell** [comment]
Пал должен быть в комбате и с маленьким хп, после чего хилер должен захилить и увидишь в логе)

**Comment by Motorheadx** [comment]
Спасибо сейчас попробую =)

**Comment by Motorheadx** [comment]
да действительно работает я просто думал что и на фул хп тоже должно =))
