### ISSUE TITLE
Kurken exotic pet too small

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#18412]
https://github.com/chromiecraft/chromiecraft/issues/6309
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Kurken exotic pet is very small no matter the level
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/11332559/1104ca9a-2212-40b9-b5d9-16f75b3e2ac6)

### Expected Blizzlike Behaviour

Pet should be taller. see source that shows it as being larger than a male orc
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/11332559/292b6052-38e2-438b-9403-a3b5fb8de4a7)

### Source

(not the clearest due to it being 480p from 2010, but its larger than the kurken is at max level on AC)
https://www.youtube.com/watch?v=gXnD0MV5s5I&t=111s

### Steps to reproduce the problem

.learn 1515
.learn 53270
.go c id 17447

tame the kurken

### Extra Notes
seemingly not fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/14511
other exotic pets are normal size

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/11c88cb30e1122fcd59aa72e04783231424cb174

### Operating system

Windows 11 Home 64-bit (10.0, Build 22621)

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by laasker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/1f878f7000d51fe5f14bafbb2cbb3806fb1c547e/src/server/game/Entities/Pet/Pet.cpp#L2503

I think adding || ctFamily == CREATURE_FAMILY_CORE_HOUND there fix this problem.
Also rhino and crocolisk are small too but i don't know if their sizes are correct or not
