### ISSUE TITLE
Paladin Seal of Vengeance  bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#1841]
all the Seal class spells(Seal of Command\Seal of Righteousness\Seal of Vengeance\Seal of Justice\Seal of Light\Seal of Wisdom)  should be triggered by the following spells:

Protection
 Judgement of Light (id=20271) 
Shield of Righteousness (id=61411)
Hammer of the Righteous(id=53595)

Retribution
 Judgement of Light (id=20271) 
Crusader Strike (id=35395)
Divine Storm(id=53385)

##### SMALL DESCRIPTION:
At present only melee swing hits  trigger Seal of Vengeance(id=31801)

##### STEPS TO REPRODUCE THE PROBLEM:
1. cast Seal of Vengeance
2. cast Judgement of Light
3. should additional Holy Damage

##### BRANCH(ES):
master

##### OPERATING SYSTEM:
Debian 8

Judgement of Light trigger Seal of Command 
![1](https://user-images.githubusercontent.com/18187177/57840034-65811b00-77fa-11e9-9961-75d4e1f12d11.png)

Judgement of Light No trigger Seal of Vengeance
![2](https://user-images.githubusercontent.com/18187177/57840109-91040580-77fa-11e9-82ea-075303cb767c.png)

**Comment by poszer** [comment]
Only melee attacks will apply the proc
![Screenshot_1](https://user-images.githubusercontent.com/41213210/57850365-0dd4b680-77de-11e9-922e-c1eed8331c1d.png)
![Screenshot_3](https://user-images.githubusercontent.com/41213210/57850421-2e047580-77de-11e9-8fa9-43c2f7de6120.png)

**Comment by Pondaveia** [comment]
Correct behavior. Thanks for validation @poszer 👍
