### ISSUE TITLE
First AID   DK

### ISSUE THREAD

**Issue by kamila231993** [azerothcore/azerothcore-wotlk#18424]
### Current Behaviour

https://private-user-images.githubusercontent.com/79054852/307984494-7c6b4463-8ebb-4454-9d25-5842c0d5e447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTAzODcsIm5iZiI6MTcwODk5MDA4NywicGF0aCI6Ii83OTA1NDg1Mi8zMDc5ODQ0OTQtN2M2YjQ0NjMtOGViYi00NDU0LTlkMjUtNTg0MmMwZDVlNDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIzMjgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDA2NDI5ZDcwZmUzYWFkMjVlZjFhMDAyMDY3MjgxOGMxYmY0YTM0NzE1ODk2MzQzMjJmN2RlOTY4MDc2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6uthR-WUvcOz_1sdEQvMzoDAAcWsYlahXuKj-5XXlo

https://private-user-images.githubusercontent.com/79054852/307984499-83b023f2-2d0c-4af7-b65a-665afd983ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTA0MjEsIm5iZiI6MTcwODk5MDEyMSwicGF0aCI6Ii83OTA1NDg1Mi8zMDc5ODQ0OTktODNiMDIzZjItMmQwYy00YWY3LWI2NWEtNjY1YWZkOTgzZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIzMjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTA4ZmVhZWVlNzBmMmVlYWUzNDc5YjE3ZDU1MDMyMTdjYWJlNDc1N2FlZjQ5ZDUyNTFlMmJiYjJhMWIxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_vVvfc3WZuYopVLfH0tV1shbJSV-VKu6u2a8AXkLbc

### Expected Blizzlike Behaviour

Being able to continue the trainer here does not work

### Steps to reproduce the problem

https://private-user-images.githubusercontent.com/79054852/307984499-83b023f2-2d0c-4af7-b65a-665afd983ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTA0MjEsIm5iZiI6MTcwODk5MDEyMSwicGF0aCI6Ii83OTA1NDg1Mi8zMDc5ODQ0OTktODNiMDIzZjItMmQwYy00YWY3LWI2NWEtNjY1YWZkOTgzZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIzMjg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMTA4ZmVhZWVlNzBmMmVlYWUzNDc5YjE3ZDU1MDMyMTdjYWJlNDc1N2FlZjQ5ZDUyNTFlMmJiYjJhMWIxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_vVvfc3WZuYopVLfH0tV1shbJSV-VKu6u2a8AXkLbc

https://private-user-images.githubusercontent.com/79054852/307984494-7c6b4463-8ebb-4454-9d25-5842c0d5e447.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTAzODcsIm5iZiI6MTcwODk5MDA4NywicGF0aCI6Ii83OTA1NDg1Mi8zMDc5ODQ0OTQtN2M2YjQ0NjMtOGViYi00NDU0LTlkMjUtNTg0MmMwZDVlNDQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDIzMjgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDA2NDI5ZDcwZmUzYWFkMjVlZjFhMDAyMDY3MjgxOGMxYmY0YTM0NzE1ODk2MzQzMjJmN2RlOTY4MDc2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6uthR-WUvcOz_1sdEQvMzoDAAcWsYlahXuKj-5XXlo

### Extra Notes

nici unul

### AC rev. hash/commit

nici unul

### Operating system

Ubuntu 20.04

### Custom changes or Modules

nici unul

**Comment by Nyeriah** [comment]
Please fill the template properly
