### ISSUE TITLE
Time-Lost Skettis High Priests are visible and friendly without Elixir of Shadows.

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#18421]
https://github.com/chromiecraft/chromiecraft/issues/6544
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Currently, the [Time-Lost Skettis High Priest](https://wowgaming.altervista.org/aowow/?npc=21787)s are visible and friendly without being under the effects of the [Elixir of Shadows](https://wowgaming.altervista.org/aowow/?item=32446).

### Expected Blizzlike Behaviour

They should never be seen as friendly (even if secretly they love you very much) and should only be seen while under the effects of the aforementioned elixir.

### Source

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/11332559/37db637e-0f73-4c0b-9758-57259fbb6613)
https://www.wowhead.com/wotlk/npc=21787/time-lost-skettis-high-priest#comments
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/11332559/0e631dd4-1320-4bf2-a559-f286c6e357f5)

### Steps to reproduce the problem

.go c id 21787

### Extra Notes

Related to Sha'tari Skyguard.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
Open a new issue for the bosses that are summoned by the skull piles.
