### ISSUE TITLE
Chaman Reincarnation does not consume ankh [$10]

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#1843]
This is low priority but i am report this.
Chaman Reincarnation does not consume ankh

When a shaman dies and uses reincarnation the ANKH are not consumed.
test without having the reincarnation glyph and orcs, trolls, dranei.

Testet last banch
No modules
ubuntu 16.04

**Comment by poszer** [comment]
Confirmed

**Comment by Shard-MW** [comment]
According to Player::GetResurrectionSpellId(), spell used for shaman reincarnation is 21169. 
When you manually `.cast 21169` Ankh is consumed. If you've the Glyph of Renewed Life, reincarnation spell (21169) doesn't consume Ankh (and that's what's intended).
But when you don't have the reincarn glyph, and you `.cast 21169 triggered`, the Ankh isn't consumed. 

So I think, the reincarnation spell 21169 is casted like it's triggered.
