### ISSUE TITLE
Illidan Stormrage Black Temple small mistakes in the text and wrong spells

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1845]
SMALL DESCRIPTION:

Illidan should be a little confused by the sentences he says and Akama once checked out seems to be.

Wrong spells work magic 

The shadow spirits like to stay with the same goal and don't run over to another one.

EXPECTED BLIZZLIKE BEHAVIOR:

The Zauber and Phasen on the side. 

https://wow.gamepedia.com/Illidan_Stormrage_(tactics)

text that Illidan, Akama and Maiev should say far down on the page

Parasitic Shadowfiend Important — A parasitic shadowfiend burrows its way through the target, dealing 5400 Shadow damage every 2 sec for 10 sec. When the shadowfiend is finished, it leaves the target and seeks new prey.

CURRENT BEHAVIOUR:

The shadow spirits like to stay with the same goal and don't run over to another one.

Illidan sturmgrimm, Akama are a little confused by the text. Should be checked.

Illidan stormgrimm should work Shear Id 41032 haven't even seen it in the combat log. 

Illidan stormgrimm affects himself Spell 40685 which I couldn't find seemed to be a false spell.

STEPS TO REPRODUCE THE PROBLEM:
Go to the black temple, defeat all the bosses and start the event at akama.

BRANCH(ES):
AzerothCore rev. f1def5ec323e+ 2019-05-10 10:13:42 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod transmog
mod_world_chat

**Comment by spinzaku** [comment]
confirmed

**Comment by steenburgh** [comment]
> The shadow spirits like to stay with the same goal and don't run over to another one.

**Comment by steenburgh** [comment]
> The shadow spirits like to stay with the same goal and don't run over to another one.

What do you mean by 'the same goal'? We've been doing the Illidan fight and the shadowfiends always seem to spawn directly on top of the player with the debuff, and then randomly aggro a player. We're not sure if this is how it's supposed to work. Thoughts?

**Comment by UltraNix** [comment]
I don't understand that report...

**Comment by Selyria** [comment]
I have to check it again myself it was a long time ago

**Comment by Selyria** [comment]
Okay these problems do not exist anymore or are described in other reports.
