### ISSUE TITLE
Nightbane Air Phase Movement

### ISSUE THREAD

**Issue by Alethrion** [azerothcore/azerothcore-wotlk#18451]
### Current Behaviour

After Nightbane flies up to his location in the sky and his threat resets, he proceeds to walk back down into melee range and spends the whole air phase there. It's worth noting that he isn't meleeing or casting ground phase spells while in this melee air phase.

### Expected Blizzlike Behaviour

He is meant to remain in the air casting his spells as normal.

### Source

Air Phase: https://wowwiki-archive.fandom.com/wiki/Nightbane_(boss)

### Steps to reproduce the problem

1. .tele kara
2. .additem 24140
3. Summon Nightbane
4. Deal 25% of his health in damage to push into phase 2
5. Observe Behavior

### Extra Notes

This used to only occur when threat target changed, but now that threat resets are correctly applied, it occurs every fight.
Originally reported at https://github.com/chromiecraft/chromiecraft/issues/6567

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Windows 10 x64

**Comment by Johaine** [comment]
I cannot reproduce this (with one or two chars in the fight). Nightbane flys in the air and stays in position until he resumes the ground phase. Can you post a video of it?

There are some visual glitches (Nightbane standing in the air) but that doesn't make him attackable by melees.

**Comment by Alethrion** [comment]
https://youtu.be/PgwuuvRqpmo?t=1064
Courtesy of Bench. Every air phase he comes over to the melee. At some point during this fight Nightbane is in both air and ground phase, and that is also unintended.

**Comment by Johaine** [comment]
Thanks for the video.

I tried fixing the messy movement today but wasn't successful. Meanwhile, I saw this behaviour maybe once or twice but still have no idea, what is causing this.

Maybe I'll try digging deeper next weekend, but it really seems convoluted ( e.g. #18551 )

**Comment by heyitsbench** [comment]
Maybe set Nightbane to rooted once he reaches the final point in air phase and unroot when it's time for ground phase?

**Comment by Johaine** [comment]
Yes, this is probably what I'll do. But I'll post a patch this weekend, fixing the other movement as well as some other fixes for the fight.

**Comment by kissingers** [comment]
this not only Nightbane problem, it seems any boss in sky if cast spell, it will dorp to ground, so the spell cast destroy the disableGravity(true)
temporary fix can use this way
https://github.com/azerothcore/azerothcore-wotlk/commit/46ba1ba6a327db712a219cef8f09d2c24ae7bc5a

**Comment by heyitsbench** [comment]
This seems to have been fixed.
