### ISSUE TITLE
[ZulAman] When kill the first 3 boss, the QuestMinute alread reset to 0 and disappear

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18466]
### Current Behaviour

When kill the first 3 boss, the QuestMinute alread reset to 0 and disappear, also the winner npc and box will not appear

### Expected Blizzlike Behaviour

after kill the first 4 boss, the time disappear, can get the 4 boxes.

### Steps to reproduce the problem

just fight and test

### Extra Notes

problem can from here, the enum form 0 start

enum DataTypes
{
    DATA_GONGEVENT                      = 0,
    DATA_NALORAKKEVENT                  = 1,
    DATA_AKILZONEVENT                   = 2,
    DATA_JANALAIEVENT                   = 3,
    DATA_HALAZZIEVENT                   = 4,
    DATA_HEXLORDEVENT                   = 5,
    DATA_ZULJINEVENT                    = 6,
    DATA_SPIRIT_LYNX                    = 7,
    DATA_CHESTLOOTED                    = 8,
    TYPE_RAND_VENDOR_1                  = 9,
    TYPE_RAND_VENDOR_2                  = 10

and when  the open door npc die,  the BossKilled already is 1 not 0. so the flow if will true when kill any 3 boss (BossKilled is 4 and DATA_HALAZZIEVENT also is 4 ), the 4 boss will no time and no box

                case DATA_GONGEVENT:
                    m_auiEncounter[DATA_GONGEVENT] = data;
                    if (data == IN_PROGRESS)
                        SaveToDB();
                    else if (data == DONE)
                        QuestMinute = 21;
                    break;
........................................................
            if (data == DONE)
            {
                ++BossKilled;
                if (QuestMinute && BossKilled >= DATA_HALAZZIEVENT)

the easy fix is change
                if (QuestMinute && BossKilled > DATA_HALAZZIEVENT)
the hard fix is change enum DataTypes +1 each event, or  ++BossKilled add to right boss but not 0 boss.

### AC rev. hash/commit

I use self fix fork so the hash not same as the master
https://github.com/kissingers/acore-wow/tree/master
AzerothCore rev. 00ec58511324 2024-03-01 21:36:22 +0800 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.

### Operating system

debian12 x64

**Comment by Tereneckla** [comment]
The 4th chest has been removed in 3.0.2. There is no way to get the mount in wotlk

**Comment by kissingers** [comment]
> 第 4 个宝箱已在 3.0.2 中移除。wotlk中没有办法获得坐骑

why I remember the fourth box is still there,  just no the bear? We fight at 3.13 for 2 years...

**Comment by kissingers** [comment]
The fourth box has been changed to give ring and so on, so you can get 2 rings at one instance.
