### ISSUE TITLE
Core Crash Caused by Odur Monster

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#1846]
When I attack the monster below the view, the core will collapse immediately.
![image](https://user-images.githubusercontent.com/49540243/57968332-4ff72700-799b-11e9-978a-2ad891bb41b0.png)
![image](https://user-images.githubusercontent.com/49540243/57968334-56859e80-799b-11e9-98de-bf76ba295bd8.png)

Restart the core and prompt the character to go online.
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111826) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111836) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111851) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112131) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112156) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112287) doesn't have waypoint path id: 0

core:
2019-05-18 18:25:43 AzerothCore rev. 78b897f852a0+ 2019-05-16 02:49:11 +0200 (master branch) (Win64, Release) (worldserver-daemon) ready...

modules:
![image](https://user-images.githubusercontent.com/49540243/57968377-4cb06b00-799c-11e9-85c9-14c9e0e58177.png)

Please test and repair. Thank you.

**Comment by poszer** [comment]
What is the creature name, entry from picture? Also, these Db errors are for other creatures, not related to this one from image

**Comment by forever2019** [comment]
> What is the creature name, entry from picture? Also, these Db errors are for other creatures, not related to this one from image

creature_template entry  Below 

32882
32883
32886
32907

**Comment by poszer** [comment]
> 32882

Tested, can't reproduce. Killed him without problem (Maybe you have issue with Module VAS-Autobalance, or even if you have module  boss announcer, someone already reported while killing boss, the server crash)

![Screenshot_4](https://user-images.githubusercontent.com/41213210/57969577-dea67c80-7978-11e9-91c2-35eb14dcca8d.png)
![Screenshot_3](https://user-images.githubusercontent.com/41213210/57969578-dea67c80-7978-11e9-9f6e-9d7fab10c348.png)

**Comment by forever2019** [comment]
> > 32882
> 
> Tested, can't reproduce. Killed him without problem (Maybe you have issue with Module VAS-Autobalance, or even if you have module boss announcer, someone already reported while killing boss, the server crash)
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/41213210/57969577-dea67c80-7978-11e9-91c2-35eb14dcca8d.png)
> ![Screenshot_3](https://user-images.githubusercontent.com/41213210/57969578-dea67c80-7978-11e9-9f6e-9d7fab10c348.png)

Thank you
I'll remove the module and reconfirm it.

**Comment by poszer** [comment]
> > > 32882
> > 
> > 
> > Tested, can't reproduce. Killed him without problem (Maybe you have issue with Module VAS-Autobalance, or even if you have module boss announcer, someone already reported while killing boss, the server crash)
> > ![Screenshot_4](https://user-images.githubusercontent.com/41213210/57969577-dea67c80-7978-11e9-91c2-35eb14dcca8d.png)
> > ![Screenshot_3](https://user-images.githubusercontent.com/41213210/57969578-dea67c80-7978-11e9-9f6e-9d7fab10c348.png)
> 
> Thank you
> I'll remove the module and reconfirm it.

Ok, i'll repopen issue, since there is PR related to it. For these waypoints errors in DB log. It will closed with it automatically. Also, tell us when you remove module, what's happening. Would like to help you. But as you can see, i don't have crash after killing this creature

**Comment by forever2019** [comment]
> > 32882
> 
> Tested, can't reproduce. Killed him without problem (Maybe you have issue with Module VAS-Autobalance, or even if you have module boss announcer, someone already reported while killing boss, the server crash)
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/41213210/57969577-dea67c80-7978-11e9-91c2-35eb14dcca8d.png)
> ![Screenshot_3](https://user-images.githubusercontent.com/41213210/57969578-dea67c80-7978-11e9-9f6e-9d7fab10c348.png)


Hello!
After I deleted the mod-vas-autobalance module, everything is fine now.

**Comment by poszer** [comment]
> > > 32882
> > 
> > 
> > Tested, can't reproduce. Killed him without problem (Maybe you have issue with Module VAS-Autobalance, or even if you have module boss announcer, someone already reported while killing boss, the server crash)
> > ![Screenshot_4](https://user-images.githubusercontent.com/41213210/57969577-dea67c80-7978-11e9-91c2-35eb14dcca8d.png)
> > ![Screenshot_3](https://user-images.githubusercontent.com/41213210/57969578-dea67c80-7978-11e9-9f6e-9d7fab10c348.png)
> 
> Hello!
> After I deleted the mod-vas-autobalance module, everything is fine now.

Great. If you want, you can report issue at this link:
https://github.com/azerothcore/mod-vas-autobalance
Also, if you are able to test this :
https://github.com/azerothcore/azerothcore-wotlk/pull/1847
Just check your DB log, and will you get these errors anymore included in your issue : 

> 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111826) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111836) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111851) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112131) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112156) doesn't have waypoint path id: 0
2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112287) doesn't have waypoint path id: 0

**Comment by forever2019** [comment]
> > > > 32882
> > > 
> > > 
> > > Tested, can't reproduce. Killed him without problem (Maybe you have issue with Module VAS-Autobalance, or even if you have module boss announcer, someone already reported while killing boss, the server crash)
> > > ![Screenshot_4](https://user-images.githubusercontent.com/41213210/57969577-dea67c80-7978-11e9-91c2-35eb14dcca8d.png)
> > > ![Screenshot_3](https://user-images.githubusercontent.com/41213210/57969578-dea67c80-7978-11e9-9f6e-9d7fab10c348.png)
> > 
> > 
> > Hello!
> > After I deleted the mod-vas-autobalance module, everything is fine now.
> 
> Great. If you want, you can report issue at this link:
> https://github.com/azerothcore/mod-vas-autobalance
> Also, if you are able to test this :
> #1847
> Just check your DB log, and will you get these errors anymore included in your issue :
> 
> > 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111826) doesn't have waypoint path id: 0
> > 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111836) doesn't have waypoint path id: 0
> > 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Winter Revenant (Entry: 34134 GUID: 3111851) doesn't have waypoint path id: 0
> > 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112131) doesn't have waypoint path id: 0
> > 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112156) doesn't have waypoint path id: 0
> > 2019-05-18 18:26:07 ERROR: WaypointMovementGenerator::LoadPath: creature Guardian Lasher (Entry: 33430 GUID: 3112287) doesn't have waypoint path id: 0

Hello!
After testing, it was found that all the problems caused by the module conflict were normal after the module was removed.
Thank you.
This problem can be closed.
