### ISSUE TITLE
Twilight of the Dawn Runner - Quest

### ISSUE THREAD

**Issue by ShenTraX** [azerothcore/azerothcore-wotlk#18485]
### Current Behaviour

Can activate the quest and can rescue the NPC. This is a two part quest, with the second part being crates at the top of the tower - which dont allow the player to interact with. You can however wait some time and the NPC will respawn at the base of the tower and "rescue" them a second time and it will complete the quest.

### Expected Blizzlike Behaviour

Speaking with the NPC completes part 1/2 of the quest. Collecting the crates at the top of the tower adds items to your inventory to allow 2/2 of quest completion.

### Steps to reproduce the problem

start quest
speak with NPC to get part 1 of 2.
traverse to the top of the tower and no crates are available to "activate"

### AC rev. hash/commit

current as of 3/1/2024

### Operating system

Windows 11

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/893a50df-31e7-424a-953d-d0d071acf652)
