### ISSUE TITLE
A Dip in the Moonwell - Quest

### ISSUE THREAD

**Issue by ShenTraX** [azerothcore/azerothcore-wotlk#18484]
### Current Behaviour

Able to remote the drone into the well and able to click the collect water action. It performs the animation, but doesn't "collect" for the quest to continue.

### Expected Blizzlike Behaviour

It should add the collected water to inventory and mark quest part complete.

### Steps to reproduce the problem

Start Quest
proceed to remote control site
activate drone
move into the well
attempt to collect the water - either using keyboard key or clicking on action-bar item.

### AC rev. hash/commit

current as of 3/1/2024

### Operating system

Windows 10

### Custom changes or Modules

modules AHBOT

**Comment by Kitzunu** [comment]
> current as of 3/1/2024
not a valid hash

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/5b9e4114-a11c-485a-bcfa-526406376563)
