### ISSUE TITLE
The Eye Bosses do not reset when leaving the room. 

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#18497]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/6522 Confirmed on my local  48873da974dd

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Void Reaver, and High Astromancer Solarian, leave their respective rooms to give chase and do not reset the fight.

~~Additionally, the doors to Kael'thas' room does not shut during combat. (They also chase, but you should not be allowed to leave the room.)~~  EDIT: Looks like this is already reported

### Expected Blizzlike Behaviour

Fights should reset once pulled from the room they are in.

### Source

https://youtu.be/xdnRDY9Atyk - cc ptr 4/1/24
https://wowwiki-archive.fandom.com/wiki/Void_Reaver 
https://wowwiki-archive.fandom.com/wiki/High_Astromancer_Solarian

### Steps to reproduce the problem

.tele theeye
Clear trash if so desired
Go to Void Reaver `.go c 158092`
Try to pull it out of the room
Go to High astromancer Solarian `.go c 158179`
Try to pull her out of the room
Go to Kael'thas `.go c 158218`
Begin the fight.
Observe doors. 

### Extra Notes

Door objects `.go ga 29829` `.go ga 29830`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e2ecbf44cc19450109bee1ef7ce6aaa7621c5af4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by kissingers** [comment]
It's similar to this one
https://github.com/azerothcore/azerothcore-wotlk/issues/18350

**Comment by elthehablo** [comment]
How about Al'ar?

**Comment by kissingers** [comment]
Al'ar is ok,  so I just do a fix as Al'ar and add the PR

**Comment by kissingers** [comment]
> Al'ar is ok, so I just do a fix as Al'ar and add the PR, and tested in real server it seems do well. #18373

sorry I make a mistake with aran...

**Comment by elthehablo** [comment]
> > Al'ar is ok, so I just do a fix as Al'ar and add the PR, and tested in real server it seems do well. #18373
> 
> sorry I make a mistake with aran...
> just like Shade of Aran

You can use boss boundaries just like I did in the referenced PR

**Comment by elthehablo** [comment]
And I meant whether Al'ar needs reset on pulling him out of the room in p2. I assume so

**Comment by kissingers** [comment]
> > > Al'ar is ok, so I just do a fix as Al'ar and add the PR, and tested in real server it seems do well. #18373
> > 
> > 
> > sorry I make a mistake with aran...
> > just like Shade of Aran
> 
> You can use boss boundaries just like I did in the referenced PR

It seem hard for me to fix like https://github.com/azerothcore/azerothcore-wotlk/commit/3f700645bd1579a4538a009cc4ea7d766656e62f 
So could you fix kalazhan Malchezaar? and I close the PR as fix way seems not beautiful.
also Aran same as my way, maybe use the same fix way.

**Comment by Nyeriah** [comment]
> And I meant whether Al'ar needs reset on pulling him out of the room in p2. I assume so

P2 alar resets when leaving room, just p1 doesnt

**Comment by elthehablo** [comment]
Okay good then we got it right
