### ISSUE TITLE
[Quest] Roll the bones id 3882

### ISSUE THREAD

**Issue by Thurin93** [azerothcore/azerothcore-wotlk#185]
**Description**: You can receive this quest from Spark Nilminer in Un'goro Crater. During this quest, you need to loot 8 Dinosaur bones from Diametradon, Elder diametradon Or Stegodon. You can loot these bones even from some skeletons on the ground.

**Current behaviour**: Diametradon, Elder Diametradon, Stegodon, Thunderstomp Stegodons seems to have low drop rate on this item. I killed 50 of them with no one of this items dropped.

**Expected behaviour**: The drop rate should be near 30% as shown here. This is the only source I could find: http://www.wowhead.com/item=11114/dinosaur-bone

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/8eb135e5456acebf44108f01bbee67fb07a4a317

**Operating system**:  Windows 8, 8.1, 10

**Modules**: Duel reset

**Other Customizations**: Crossfaction

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
Ill check the issue later, see what % chance of drop it currently set as

**Comment by Blumfield** [comment]
I had a fix for that on my old DB try it

`INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (6501, 11114, 30);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (6502, 11114, 30);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (6503, 11114, 30);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (6504, 11114, 30);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (9162, 11114, 30);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (9163, 11114, 30);
INSERT INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (9164, 11114, 30);`

**Comment by ShinDarth** [comment]
@Blumfield thanks a lot for your fix, please:
- open a [Pull request](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) to submit your fix
- read [Dealing with SQL files](https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files) so you can write a cleaner SQL code ;)

**Comment by talamortis** [comment]
INSERT INTO creature_loot_template (entry, item, ChanceOrQuestChance) VALUES
(6501, 11114, 30),
(6502, 11114, 30),
(6503, 11114, 30),
(6504, 11114, 30),
(9162, 11114, 30),
(9163, 11114, 30),
(9164, 11114, 30);

@Blumfield  please use the SQL above for a PR 👍
