### ISSUE TITLE
[Quest] [DB] The Gearmaster

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1850]
Quest The Gearmaster

Potential Memory Leak -> Once you spawn NPC, gobject should phase away, but it remain visible and you can spawn NPC as much as you want.

Tried with Force despawn and respawn (Despawn works, but never respawn after kill) and visibility but no luck so far.

.quest add 11798
.tele Borean Tundra

Spawn one NPC for quest and keep clicking on object to spawn more.

Commit: Latest, always up to date.

**Comment by deadmanevil** [comment]
fix tested 
DELETE FROM `event_scripts` WHERE `id`=17209 AND `command`=8;
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
(17209, 1, 8, 27995, 1, 0, 0, 0, 0, 0);

**Comment by poszer** [comment]
> fix tested
> DELETE FROM `event_scripts` WHERE `id`=17209 AND `command`=8;
> INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`) VALUES
> (17209, 1, 8, 27995, 1, 0, 0, 0, 0, 0);

What is tested here? With this, they will be spawned like before, the players are able to click on the book XXXX times, and summon XXXX of these creatures
