### ISSUE TITLE
[Quest] Going Bearback

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1853]
Event to ride bear and etc for Going Bearback working nice.

But, NPC's that are required for quest are friendly (35)
Tried to change Faction ID towards them, but for some reason they always remain friendly.

Also, when i tried to modify their factions towards Sons of Hodir, faction is not found in DBC.
Setting it to faction 190 or 7 will make them neutral and quest will be available, but after restart they will go back to friendly again, even if they are set to diff ID DB wise.

.quest add 12851
.tele k3

**Comment by Meltie2013** [comment]
This possibly would be core side if I am not mistaken.
