### ISSUE TITLE
Refactor Profanity and Reserved names functionality

### ISSUE THREAD

**Issue by walkline** [azerothcore/azerothcore-wotlk#18556]
### Describe your feature request or suggestion in detail

At the moment these two functions are heavily unoptimized:
https://github.com/azerothcore/azerothcore-wotlk/blob/77bbcb39250835dde1a5738f58be9128ba616786/src/server/game/Globals/ObjectMgr.cpp#L212
https://github.com/azerothcore/azerothcore-wotlk/blob/77bbcb39250835dde1a5738f58be9128ba616786/src/server/game/Globals/ObjectMgr.cpp#L240

The thing is that we iterating over 25 000 strings, then we are making some replacements in every of them and finally we are making comparison.
We are calling it on every login and character creation, which can be resulted in diff spikes.

During my load testing with 1 000 characters login the diff spike was 22k ms (22 seconds).
![Screenshot 2024-03-15 at 13 27 59](https://github.com/azerothcore/azerothcore-wotlk/assets/444158/c5a2d39b-87e6-47eb-a2e8-17e11f39a81a)

When I disabled `StrictNames.Reserved` & `StrictNames.Profanity`, the same test - the spike is 2k ms (2 seconds).
![Screenshot 2024-03-15 at 13 32 35](https://github.com/azerothcore/azerothcore-wotlk/assets/444158/e07eac8d-f908-433b-9d95-7f2fda2b7b16)

### Describe a possible solution to your feature or suggestion in detail

We should move this logic to the server loading stage. At this stage, we would build a search tree (e.g., std::set) from normalized strings. During "runtime", we can simply search for the word in this tree (which would take O(log n) time instead O(n)+string normalization on every iteration).

**Comment by Elmsroth** [comment]
Agree 100%

**Comment by pklloveyou** [comment]
I DON'T KNOW WHY, SUNWELLCORE IS BETTER THAN THE CURRENT CORE PERFORMANCE

**Comment by Nyeriah** [comment]
Because it was a little more than a collection of hacks with barely anything working as it should?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19259
