### ISSUE TITLE
[Quest] Lightning Infused Relics

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1855]
Report came from player, and was able to confirm myself.

```
While doing the quests Lightning Infused Relics and The Delicate Sound of Thunder, I walked into the cave system in Baelgun's Excavation Site. I then got teleported upwards and got stuck in the air, then WoW crashed. After logging my vehicle is stuck walking in front of me and I can't move or hearth. I logged out again and when I logged back in I fell and can move again.

Just noticed after logging back on all the Iron Rune Workers are now friendly towards me.
```

There should be something like instant injection. I tried to fix, but no luck so far.

.quest add 11494
.tele HowlingFjord

Commit: Up to date.

![quest1](https://user-images.githubusercontent.com/27079035/57980564-58983d80-7a2d-11e9-89a1-565eb409ff33.jpg)

**Comment by poszer** [comment]
Can you record video of this issue @Knindzagxg , please :stuck_out_tongue:

**Comment by deadmanevil** [comment]
can this fix be serious check it
UPDATE smart_scripts SET action_param1 = 6000 WHERE entryorguid = 24824;

**Comment by FrancescoBorzi** [comment]
@deadmanevil please wrap any sql code on github using:

![image](https://user-images.githubusercontent.com/75517/58385332-13f14100-7fef-11e9-8342-ef0c3f68e71d.png)

**Comment by Voxstrasza** [comment]
@Knindzagxg Can you provide more info?  I'm not sure how to reproduce this bug.

**Comment by Knindzagxg** [comment]
Sadly i can't.

Report came long time ago from player.
It might be fixed with some PR's we had and i can't re-test it cause i modified core for some crazy Kara sorting xP

**Comment by Voxstrasza** [comment]
im going to close this issue then; i'm not sure how to reproduce the bug (i haven't done this quest in a long time so i'm not even sure where to go)
