### ISSUE TITLE
[Icecrown Citadel]Lord Marrowgar bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#18572]
### Current Behaviour

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18187177/d0551a38-4865-4b17-9c2c-d2dd9594e7e0)
As shown in the figure, this position will not be damaged by Coldflame

https://youtu.be/yctUGCeAJ3w

### Expected Blizzlike Behaviour

All areas will be damaged by Coldflame

### Steps to reproduce the problem

1. `.go xyz -343.038116 2210.850830 42.550510 631`
2. Start the battle
3.Run to the position of the image and observe if there is any damage from Coldflame

### AC rev. hash/commit

e0bc7d7

### Operating system

Ubuntu 20.04

**Comment by Joshmash** [comment]
I thouht this was about bone storm phase when he charges to random player instead of the farthest one

**Comment by Joshmash** [comment]
Tried and it's got fixed
24df7a9f465d+ 2024-06-19 07:59:40 +0300 (TS branch) (Unix, RelWithDebInfo, Static)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/153951964/4d213408-0cf2-4f8b-b1de-8a541ed3a8c5)

**Comment by mpfans** [comment]
confirmed
