### ISSUE TITLE
Pit Commander/Minions in Outland Bug

### ISSUE THREAD

**Issue by Sochyo** [azerothcore/azerothcore-wotlk#18573]
### Current Behaviour

I noticed the "Pit Commander" in Outland spawn but not his minions and they dont use their path. [I have preload map grid and set waypoint active.]

### Expected Blizzlike Behaviour

He's suppose to spawn with some minions and they are supposed to walk to the stairs infront off the outland big portal to fight the guards.

### Steps to reproduce the problem

Step.1 create gm account
Step.2 login and use tele cmd> .Tele Outland
Step.3 go straight and notice he's not on the way or fighting the guards

### Extra Notes

(The guards at the bottom of the stairs are also a bit bugged. They are stacked one on each other)

### AC rev. hash/commit

![20240318_011405](https://github.com/azerothcore/azerothcore-wotlk/assets/163804950/e240a197-d613-4c0f-8248-ed06a1b38774)

### Operating system

Windows 10 x64

### Custom changes or Modules

Preload map grid = enable
Creature with waypoint active = enable

**Comment by heyitsbench** [comment]
Closing in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/18619, as that has a revision attached.

**Comment by dewmguy** [comment]
confused why this ticket is closed. having the same problem

**Comment by heyitsbench** [comment]
> confused why this ticket is closed. having the same problem

A) Because this issue didn't have a revision attached, but more importantly B) a different issue was opened with more information and a revision.
