### ISSUE TITLE
[Warrior/Mage] "DoT Munching"  Deep Wounds/Ignite 

### ISSUE THREAD

**Issue by Wheemix** [azerothcore/azerothcore-wotlk#18593]
https://github.com/chromiecraft/chromiecraft/issues/5669

### Current Behaviour

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/88062402/a80e1507-50ca-4c64-94ab-20d21a8cff56)

Currently when you land 2 critical strikes at the same time frame, deep wounds is only registering 1 application. 

### Expected Blizzlike Behaviour

Each critical strike from the warrior should proc 1 application of deep wounds.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/88062402/5c549a83-851d-4008-93af-21e2a228daed)
By description of the spell itself, each and every crit should apply 1 deep wound.

### Source

Quote from official Blizzard Wotlk Classic patch notes (https://www.wowhead.com/wotlk/news/patch-notes-version-3-4-2-wotlk-classic-333579) confirming this as a bug and not intended 3.3.5 behaviour:
"Fixed an issue that caused stacking damage over time effects to not properly stack when two effects that increase the magnitude of the DoT land simultaneously.
Developers’ note: This resolves the so-called “DoT Munching” behavior seen predominately with spells like Ignite and Deep Wounds."

### Steps to reproduce the problem

1. Create warrior, and spec into deep wounds
2. Get some gear and wep, and make a slam /startattack macro
3. Get double crit from the auto+slam and check logs

### Extra Notes

original Chromiecraft report by Cooties on May 26th, 2023: 
https://github.com/chromiecraft/chromiecraft/issues/5669

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/bc0ddaa3c2af2e7b0e92986741485d04c1a90a35

### Operating system

Ubuntu 20.04

**Comment by heyitsbench** [comment]
This issue is invalid per original Wrath. IMO, munching should be made into a config or made adjustable/removable by a module, but in terms of default behavior this issue is, again, invalid.
