### ISSUE TITLE
[Black Temple] the NPC second akama does not at right position and the illidan dont call the fire at second phase

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18591]
### Current Behaviour

the NPC second akama does not appear after kill 4 bosses. and I find it at top of the hill. player can not diag with it so can not continue  open the door to illidan.
also when I fix the position , try fight with illidan, it dont call the fire at second phase.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### Extra Notes

UPDATE acore_world.creature SET position_x = 652.413, position_y = 305.68, position_z = 271.69, orientation = 0 WHERE guid = 148735;

use the sql can temp fix akama position

### AC rev. hash/commit

I am fix something by my fork so hash not same as the master PR
https://github.com/kissingers/acore-wow

### Operating system

debian12 x64

**Comment by kissingers** [comment]
after this pr
https://github.com/azerothcore/azerothcore-wotlk/pull/18569

**Comment by pklloveyou** [comment]
```
DELETE FROM `creature` WHERE `guid` = 148734;
DELETE FROM `creature` WHERE `guid` = 148733;
INSERT INTO `creature` VALUES (148734, 23448, 0, 0, 564, 0, 0, 1, 3, 0, 678.06, 285.22, 354.325, 3.29867, 604800, 0, 0, 1, 0, 0, 0, 0, 0, '', 46741, 1, NULL);
INSERT INTO `creature` VALUES (148733, 23448, 0, 0, 564, 0, 0, 1, 5, 0, 676.226, 325.231, 354.319, 3.12414, 604800, 0, 0, 1, 0, 0, 0, 0, 0, '', 46741, 1, NULL);
```

**Comment by kissingers** [comment]
excelent! thanks...
UPDATE acore_world.creature SET `phaseMask` = 3, WHERE guid = 148734;
UPDATE acore_world.creature SET `phaseMask` = 5, WHERE guid = 148733;

**Comment by kissingers** [comment]
excelent! thanks...
UPDATE acore_world.creature SET `phaseMask` = 3, WHERE guid = 148734;
UPDATE acore_world.creature SET `phaseMask` = 5, WHERE guid = 148733;

**Comment by Gultask** [comment]
hehe, sowwy.
I'm rewriting the Shade of Akama and Illidari Council fights so I can fix them asap. I'd recommend not updating the core yet if you're doing BT progression, although I believe not all fights worked correctly.
