### ISSUE TITLE
[TBC Hyjal] Flying creatures in the horde base can get stuck

### ISSUE THREAD

**Issue by elthehablo** [azerothcore/azerothcore-wotlk#18595]
### Current Behaviour

Some waves will just have 2 ghouls running, which likely means there should be some gargoyles as well, but they never end up making it.

### Expected Blizzlike Behaviour

To be frank, I haven't played Hyjal in TBC, but 2 ghouls is likely not the intended behaviour. So likely there would be some flying mobs flying in (I can remember this from testing Hyjal before the last PR)

### Source

Logic

### Steps to reproduce the problem

1. kill the first 2 bosses
2. talk to thrall
3. see that on wave 2, only 2 ghouls walk in (are waves randomized? not entirely sure)

### Extra Notes

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/dcd07c70-1562-4add-89c6-77ff93df89b9)
they can spawn, however sometimes they are getting stuck likely

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/83884799/c7434294-a9f6-48be-b95d-8f2245dc5708)
update: found them. them getting stuck may not be intentional?

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/ec1b2f7a28e0acba50ad991bb12f42851dc2015b

### Operating system

Windows 10

### Custom changes or Modules

mod-prog, mod-zone-difficulty and some changes on Archimonde that shouldn't matter here

**Comment by Gultask** [comment]
.ins setbossstate 1 3
.ins setbossstate 2 3
.go c id 17852

Gargoyles can spawn either behind the Troll Camp or the Entrance but it's not random. After they path I made them move in a large radius.

They're also set to be active on spawn so they can't get stuck from not moving, hopefully. The waves are described in creature_summon_groups for map 534

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/db3bbe22-8c40-48c5-baab-2d64e3d3308f)

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/7ce34979-3ae5-49ee-860c-794bf7d8820a)

**Comment by elthehablo** [comment]
okay then this is likely the correct behaviour as is
