### ISSUE TITLE
[Hyjal] The boss 3 and 4 have 8 lots of creatures, they work seems not normal.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18590]
### Current Behaviour

they just pass throw the Thrall, not go to Thrall attack him.
and the creature seems go much more slowly. and the 8th lot still not be killed, the boss already come out but go  also very slowly  

### Expected Blizzlike Behaviour

they go to Thrall and try attack him

### Steps to reproduce the problem

n/a

### AC rev. hash/commit

I am fix something by my fork so hash not same as the master PR
https://github.com/kissingers/acore-wow

### Operating system

debian12 x64

**Comment by kissingers** [comment]
after this PR
https://github.com/azerothcore/azerothcore-wotlk/pull/18512

**Comment by Gultask** [comment]
What are the creatures?
In all cases creatures don't go directly to the boss (Thrall or Jaina), instead, they patrol around the base using 3 different patrol paths, killing what they can, that's also in Retail.

**Comment by kissingers** [comment]
> Which creatures? In all cases creatures don't go directly to the boss (Thrall or Jaina), instead, they patrol around the base using 3 different patrol paths, killing what they can, that's also in Retail.

Sorry, before PR the 8 tiems creature will go to Thrall ,if meet any body or npc will fight with then first. if kill the Thrall will reset the Boss. 
I wander If all players die when fight with the creatures in retail, how to reset the boss?

**Comment by kissingers** [comment]
> Which creatures? In all cases creatures don't go directly to the boss (Thrall or Jaina), instead, they patrol around the base using 3 different patrol paths, killing what they can, that's also in Retail.

Sorry, before PR the 8 tiems creature will go to Thrall ,if meet any body or npc will fight with then first. if kill the Thrall will reset the Boss. 
I wander If all players die when fight with the creatures in retail, how to reset the boss?

**Comment by Gultask** [comment]
> I wander If all players die when fight with the creatures in retail, how to reset the boss?

As they move around they should fight and easily kill Horde NPCs around the camp. Once enough NPCs are killed the instance resets and everyone is despawned.
I haven't added that yet because I didn't figure out the correct number and I don't want to undershoot and make the instance too frustrating.

**Comment by Kitzunu** [comment]
Closing as no hash was provided
