### ISSUE TITLE
[AQ40/Bug Trio] Vem does not enrage when he is the last one alive (?)

### ISSUE THREAD

**Issue by SuzumiK** [azerothcore/azerothcore-wotlk#18618]
### Current Behaviour

When Vem is left alive as the last bug, he is supposed to enrage.

This appears to have been implemented before (old rev!):
https://github.com/azerothcore/azerothcore-wotlk/blob/1f472bddd395073bf2a2d146ecb66489b36015fb/src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp#L360

However, I'm not sure if this was ever triggered, because the counter was only ever set to 1, but not incremented.
https://github.com/azerothcore/azerothcore-wotlk/blob/1f472bddd395073bf2a2d146ecb66489b36015fb/src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp#L279

This seems to still be the case:
https://github.com/azerothcore/azerothcore-wotlk/blob/3ff8de2086a2f32316ec0041963968c6eccf8958/src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp#L307

### Expected Blizzlike Behaviour

When Vem is the last bug alive, he should enrage - or should he?

### Source

https://www.wowhead.com/classic/de/guide/bug-trio-temple-of-ahnqiraj-strategy#vem-abilities

However, this refers to "Classic", not "Vanilla" and I can't actually find a source old enough to back this up definitively.

### Steps to reproduce the problem

1. Kill Yauj and Kri
2. Vem does not enrage

### AC rev. hash/commit

63a00515eccd5af35c7601d1b5042ab810935498

### Operating system

Win11

**Comment by Johaine** [comment]
Confirmed, will post a PR to fix it tomorrow.
