### ISSUE TITLE
Low level repeatable quest exclamation marks appearing as yellow instead of blue

### ISSUE THREAD

**Issue by sluggor** [azerothcore/azerothcore-wotlk#1862]
Low level repeatable quests appear as yellow exclamation marks instead of blue

##### SMALL DESCRIPTION:

When using the "Low Level Quests" tracker on the mini map, repeatable quests will appear as yellow exclamation marks over the heads of questgivers and on the minimap. They should appear as blue. If the quest is not low-level, it will appear properly as blue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Repeatable low-level quests should appear as blue exclamation marks.

##### CURRENT BEHAVIOUR:

Repeatable low-level quests are appearing as yellow exclamation marks.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a repeatable, low-level quest where the exclamation mark is hidden.
2. Turn on "Low Level Quests" tracking on the mini map.
3. Exclamation mark will be yellow.

##### EXTRA NOTES:

The code handling this is below:

Link: [Player.cpp](https://github.com/azerothcore/azerothcore-wotlk/blob/0b9a0d8ea63cec42df9e19d013ca37cd08cc9613/src/server/game/Entities/Player/Player.cpp#L16805)

```
QuestStatus status = GetQuestStatus(questId);

if (status == QUEST_STATUS_NONE)
{
	if (CanSeeStartQuest(quest))
	{
		if (SatisfyQuestLevel(quest, false))
		{
			if (quest->IsAutoComplete())
				result2 = DIALOG_STATUS_REWARD_REP;
			else if (getLevel() <= (GetQuestLevel(quest) + sWorld->getIntConfig(CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF)))
			{
				if (quest->IsDaily())
					result2 = DIALOG_STATUS_AVAILABLE_REP;
				else
					result2 = DIALOG_STATUS_AVAILABLE;
			}
			else
				result2 = DIALOG_STATUS_LOW_LEVEL_AVAILABLE;
		}
		else
			result2 = DIALOG_STATUS_UNAVAILABLE;
	}
}
```

The issue is that the code checks to see if it's a daily *after* the low-level check, so low-level quests never get recognized as repeatable. One possible fix (that works for me) would be:

```
        QuestStatus status = GetQuestStatus(questId);
        if (status == QUEST_STATUS_NONE)
        {
            if (CanSeeStartQuest(quest))
            {
                if (SatisfyQuestLevel(quest, false))
                {
                    if (quest->IsAutoComplete())
                        result2 = DIALOG_STATUS_REWARD_REP;
                    else {
                        bool bLowLevel = (getLevel() > (GetQuestLevel(quest) + sWorld->getIntConfig(CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF)));

                        if (quest->IsDaily()) {
                            if (bLowLevel)
                                result2 = DIALOG_STATUS_LOW_LEVEL_AVAILABLE_REP;
                            else
                                result2 = DIALOG_STATUS_AVAILABLE_REP;
                        }
                        else {
                            if (bLowLevel)
                                result2 = DIALOG_STATUS_LOW_LEVEL_AVAILABLE;
                            else
                                result2 = DIALOG_STATUS_AVAILABLE;
                        }
                    }
                }
                else
                    result2 = DIALOG_STATUS_UNAVAILABLE;
            }
        }
```

This code checks first to see if it's a daily (repeatable), *then* checks for a low-level quest in either case. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

24daecddfa413040f7562b78298b605cb25d0809

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

No

##### NOTE:

I am new to GitHub and using this system. If I got anything wrong in this report template, please let me know so I can do it better next time, thanks.

**Comment by poszer** [comment]
Hmm, interesting. Thanks for report, will be great if you can write us some quests which showing incorrect color (!,?)
![questtype](https://user-images.githubusercontent.com/41213210/58118941-30ae0300-7c02-11e9-8fbf-6ec8021e8072.png)

**Comment by sluggor** [comment]
The quest I noticed it on was "Drake Hunt" (acore_world.quest_template.ID = 11940). This is repeatable version, acore_world.quest_template.Flags = 4224 (QUEST_FLAGS_DAILY|QUEST_FLAGS_TBC).

The quest giver is Raelorasz at Transitus Shield in Borean Tundra. After you finish the first "Drake Hunt" quest (11919), you unlock the daily quest of the same name.

It was low-level, so didn't appear until I enabled low-level quest tracking. It appeared yellow.

After making the noted changes, it was blue.

Additionally, if you you set "Quests.LowLevelHideDiff = -1" in worldserver.conf, you don't need to use low level quest tracking from the mini map, and it will be blue. It's only yellow if you're using "Low Level Quests" tracking when low level applies.

In fact (sorry, thinking as I type), here's the best way to see the issue.

Edit worldserver.conf and set `Quests.LowLevelHideDiff = -1`, then restart the world server.

Go to Isle of Quel'Danas on a level 80 character, where pretty much everything is a daily. With `LowLevelHideDiff` set to `-1`, nearly all the exclamation points will be blue.

Now edit worldserver.conf again, and set `Quests.LowLevelHideDiff = 4` (the default), and restart the world server.

Now, on a level 80 character, there will be no exclamation marks (quests too low). Turn on "Low Level Quests" tracking, and they'll all appear yellow.

**Comment by poszer** [comment]
Ok, tested i see change. Your fix is okay, but what about these quests like in Orgrimar, the repeatable, they should be blue too, right ? @sluggor 
![Hf7P246jTxqaeaxzhfN-oQ](https://user-images.githubusercontent.com/41213210/58125390-c0f34480-7c10-11e9-898d-995aacf3c829.png)

**Comment by sluggor** [comment]
These quests are all listed without any flags (acore_world.quest_template.Flags = 0): QUEST_FLAGS_NONE.

They are the following quests, and are not defined in the database as repeatable:
`7833` `A Donation of Wool` Flags are set to 0
`7834` `A Donation of Silk` Flags are set to 0
`7835` `A Donation of Mageweave` Flags are set to 0
`7836` `A Donation of Runecloth` Flags are set to 0

They'd need flags of at least 4096 (QUEST_FLAGS_DAILY) to be repeatable, I think.

I don't remember if these were originally dailies or not in retail. Based on the way that they're defined in acore.world.quest_template, though, they are not repeatable and should be yellow.

**Comment by poszer** [comment]
Hmm, will check it. Also thanks for the fix with others quests. Can you open pr with your changes?

**Comment by sluggor** [comment]
I am new to GitHub, so I'm still trying to understand all of the parts and procedures, but I'll read through the docs and try to figure it all out. Thanks!

**Comment by poszer** [comment]
> I am new to GitHub, so I'm still trying to understand all of the parts and procedures, but I'll read through the docs and try to figure it all out. Thanks!

Okay, good. If you need any help, PM me on discord.  https://discord.gg/j3tjZy
