### ISSUE TITLE
Problems encountered in compiling a clean core in vs2017

### ISSUE THREAD

**Issue by forazeroth147** [azerothcore/azerothcore-wotlk#1863]
Hello guys,I have some trouble when i compile in vs2017.
hopes guys can help me to solve it!

##### SMALL DESCRIPTION:

made in a clean verison in vs2017 and a clean azerothcore.

##### CURRENT BEHAVIOUR:

it has some trouble in the same point.Forgive me that im a new person to learn c++
the bug description:
Error C2065 "bool_tmp": undeclared identifier common C: Users tbc Desktop azerothcore-wotlk src common Database PreparedStatement.cpp 206

Error C2065 "bool_tmp": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database PreparedStatement. CPP 207

Error C2541 "delete": cannot delete objects that are not pointers. Common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 52

Error C2541 "delete": cannot delete objects that are not pointers. Common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 82

Error C2065 "my_bool": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database PredStatement. CPP 206

Error C2065 "my_bool": undeclared identifier common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult.cpp 43

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 40

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 43

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 52

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 69

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult.cpp 82

Error C2614 "Prepared ResultSet": Illegal member initialization: "m_isNull" is not a base or member of common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult. 27

Error: LNK1181 could not open the input file ". \\\\\\\\\\\ common. lib" authserver C: Users tbc Desktop ac src server authserver LINK 1

Error: LNK1181 could not open the input file ".. common Release common. lib" worldserver C: Users TBC Desktop AC SRC server world server LINK

Error C2061 Syntax Error: Identifier "my_bool" common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 40

Error C2146 Syntax Error: Lack of ";" (in front of identifier "bool_tmp") Common C: Users tbc Desktop azerothcore-wotlk src Common Database PreparedStatement. CPP 206

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

windows 7

##### MODULES:

clean core

**Comment by poszer** [comment]
What version of OpenSSL you have installed? Also, what MySQL version you use?

**Comment by forazeroth147** [comment]
> 您安装了哪个版本的OpenSSL？另外，你使用的MySQL版本是什么？

thanks for your reply.
Im use the Win64openssl 1_0_2o,and Installation-free version of MySQL for 8.0.13
Mabe the verison have trouble?

**Comment by poszer** [comment]
> > 您安装了哪个版本的OpenSSL？另外，你使用的MySQL版本是什么？
> 
> thanks for your reply.
> Im use the Win64openssl 1_0_2o,and Installation-free version of MySQL for 8.0.13
> Maybe the verison have trouble?

Np. Yeah, posible problem is your MySQL version. Download this, and let me know did it fix issue:
http://dev.mysql.com/downloads/mysql/5.6.html

**Comment by forazeroth147** [comment]
thanks a lot！😊

**Comment by poszer** [comment]
> thanks a lot！

Fixed?

**Comment by forazeroth147** [comment]
> > thanks a lot！
> 
> Fixed?

emm..I have tried in the next day,Seem have solved some problem,but also have 8 problem.
the problem description:
Error C2541 "delete": cannot delete objects that are not pointers. Common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 52

Error C2541 "delete": cannot delete objects that are not pointers. Common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 82

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 40

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 43

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 52

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 69

Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult.cpp 82

Error C2614 "Prepared ResultSet": Illegal member initialization: "m_isNull" is not a base or member of common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult. 27

how can i solve the problem?
Thanks!

**Comment by poszer** [comment]
> > > thanks a lot！
> > 
> > 
> > Fixed?
> 
> emm..I have tried in the next day,Seem have solved some problem,but also have 8 problem.
> the problem description:
> Error C2541 "delete": cannot delete objects that are not pointers. Common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 52
> 
> Error C2541 "delete": cannot delete objects that are not pointers. Common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 82
> 
> Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 40
> 
> Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 43
> 
> Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 52
> 
> Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore - wotlk src common Database QueryResult. CPP 69
> 
> Error C2065 "m_isNull": undeclared identifier common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult.cpp 82
> 
> Error C2614 "Prepared ResultSet": Illegal member initialization: "m_isNull" is not a base or member of common C: Users tbc Desktop azerothcore-wotlk src common Database QueryResult. 27
> 
> how can i solve the problem?
> Thanks!

Follow this guide please and try. 
http://www.azerothcore.org/wiki/Requirements#windows
