### ISSUE TITLE
Feature: Combined achivements across all characters

### ISSUE THREAD

**Issue by SimonMakwarth** [azerothcore/azerothcore-wotlk#18645]
### Describe your feature request or suggestion in detail

A combined list of achivements for chromiecraft. This entails that if a player have completed one achivement on one toon, all other toons will also have that achivement completed. 

### Describe a possible solution to your feature or suggestion in detail

Achivements are bound to user and not to a character.

### Additional context

I this way achivement-hunters will have a reason the level new alt thus being able to spot and report new issues.

**Comment by Nyeriah** [comment]
This looks like a suggestion for the Chromiecraft forums.
As for azerothcore I believe there already is such module

**Comment by avarishd** [comment]
Discord poll? Not a bad idea to add it to CC.

https://github.com/azerothcore/mod-account-achievements
https://github.com/azerothcore/mod-account-mounts
