### ISSUE TITLE
[crash] world server crash 20240402

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#18649]
### Current Behaviour

crash log :https://gist.github.com/mpfans/104573b076a8e2f32ef18d02e5d3a493

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

e0bc7d73ddaae154dc113bbfa83390ffbb3040fb

### Operating system

Ubuntu 20.04

**Comment by Nyeriah** [comment]
Crash in kaelthas
