### ISSUE TITLE
Monsters do not disengage from combat when the player is flying.

### ISSUE THREAD

**Issue by icedcolor** [azerothcore/azerothcore-wotlk#18658]
### Current Behaviour

Monsters do not disengage from combat when the player is flying. 
Monsters in Blizzard disengage from combat when the player flies with a flying mount.
In Cmangos this is as official as it gets.

### Expected Blizzlike Behaviour

Monsters in Blizzard disengage from combat when the player flies with a flying mount.

### Steps to reproduce the problem

1 Go to the Outlands or Northrend。
2 Riding on a Flying Mount。
3 Fly up to a certain height, but the monster will keep watching yet, and will not disengage from the fight.

### AC rev. hash/commit

none

### Operating system

windows 10 x64

**Comment by balleny** [comment]
see also
https://github.com/chromiecraft/chromiecraft/issues/6552
(https://github.com/chromiecraft/chromiecraft/issues/6944)

**Comment by heyitsbench** [comment]
Evade logic in general on AC needs a bit of a rework from what I've observed.

**Comment by Nyeriah** [comment]
They used to, this is something that got broken in the movement update we had last year

**Comment by icedcolor** [comment]
https://github.com/azerothcore/azerothcore-wotlk/assets/19793341/6980b5a4-1317-4a8e-9637-59cd1398c534

This video was compiled last April after everything was fine. Also, this paragraph is the configuration at that time.
#    ThreatRadius
#        Description: Distance for creatures to evade after being pulled away from the combat
#                     starting point. If ThreatRadius is less than creature aggro radius then aggro
#                     radius will be used.
#        Default:     60

ThreatRadius = 60

But now there is no such configuration.

**Comment by heyitsbench** [comment]
> But now there is no such configuration.

When it was removed it wasn't used in the core at all, chances are it wasn't when the video was recorded either.

**Comment by icedcolor** [comment]
Maybe so, but the source code for this video is from last April, and it's all just fine, and now Fly Up Monster will be watching you, always!

**Comment by icedcolor** [comment]
#17557
I restored this update and everything is fine.

**Comment by icedcolor** [comment]
@heyitsbench @Nyeriah   
You can try resuming this update and everything works fine, it seems that this update still has some work to do.

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/50d6cdcd-7c49-463f-8260-48050879b556)
