### ISSUE TITLE
worldserver crash - .go xyz 

### ISSUE THREAD

**Issue by sudlud** [azerothcore/azerothcore-wotlk#18662]
### Current Behaviour

https://gist.github.com/sudlud/4e92e9604b94d54bb9811e0ce9dfa196

### Expected Blizzlike Behaviour

no crash

### Steps to reproduce the problem

```
.tele durotar
.go xyz 90000 0
```

### AC rev. hash/commit

40bbba64d

### Operating system

Windows 10 x64

**Comment by ashleyhh** [comment]
tested crashed my server also

**Comment by pklloveyou** [comment]
I'm in the "Outland" and the server crashes as well

**Comment by qq462518439** [comment]
Using .go xyz 90000 0 on any map will result in a crash
