### ISSUE TITLE
[BlackTemple] Illidan problems

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18667]
### Current Behaviour

At EVENT_PHASE_2_START, the boss only fly one time and drop to ground, then run in ground but not fly'.
the problem like this bug report:
https://github.com/azerothcore/azerothcore-wotlk/issues/18551
It sees some spell action destroy the disableGravity, any spell will let the creature drop to ground, so must before use GetMotionMaster do these again, 
                    me->SetDisableGravity(true);
                    me->SendMovementFlagUpdate();
just like https://github.com/azerothcore/azerothcore-wotlk/commit/46ba1ba6a327db712a219cef8f09d2c24ae7bc5a at line 345-346
I think might find and fix the problem destroy the DisableGravity at any spell in script AI. So all these problem will automatic fixed

At EVENT_PHASE_5_START, when me->CastSpell(me, SPELL_SHADOW_PRISON, true) sometimes the boss will outcombit
might need set me->SetReactState(REACT_PASSIVE) before or after SPELL_SHADOW_PRISON immediately. or change  SPELL_SHADOW_PRISON spell will not let boss outcombit

At EVENT_PHASE_5_SCENE5 , if boss's Victim died with SPELL_SHADOW_PRISON and in fire. The Server Crash, might need like this:
https://github.com/azerothcore/azerothcore-wotlk/pull/18653/commits/15ef5fc57f8405d91fb9377e7889463d987953c5
or like this
                    if (me->GetVictim())
                        me->SetTarget(me->GetVictim()->GetGUID());
                    else
                        DoMeleeAttackIfReady();

And if outcombit after EVENT_PHASE_5_START,  and restart fight with the boss, the boss will not selectable, might add 
these at  BossAI::Reset()
            me->SetReactState(REACT_AGGRESSIVE);
            me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. e863873d4c80 2024-04-03 19:36:53 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 29 second(s)
Update time diff: 10ms. Last 500 diffs summary:
- Mean: 10ms
- Median: 10ms
- Percentiles (95, 99, max): 11ms, 11ms, 11ms
Using SSL version: OpenSSL 3.0.11 19 Sep 2023 (library: OpenSSL 3.0.11 19 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101106
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.5.13-1-pve
Worldserver listening connections on port 54346
Realmlist (Realm Id: 2) configured in port 54346
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow2/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow2/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow2/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: enUS koKR frFR deDE zhCN zhTW esES 
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: zone_difficulty_instance_saves.sql
Latest WorldDatabase update: mod-spawn-zone-diff.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna
- mod-playerclass-damage
- mod-real-area-diff
- mod-real-map-diff
- mod-real-zone-diff
- mod-spawn-area-diff
- mod-spawn-map-diff
- mod-spawn-zone-diff

### Operating system

debian12 x64

**Comment by icedcolor** [comment]
@kissingers  The TrinityCore  of the Illidan fight is perfect
