### ISSUE TITLE
ICC The Battle Problem of No.3 BOSS

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#1868]
**describe**
When I changed all the biological attributes in the configuration file, ICC No. 3 BOSS fought, the battle attack damage of both sides was unbalanced and could not defeat each other.

**testing procedure**
1)The configuration modifications are as follows

Rate.Creature.Normal.Damage          = 0.05
Rate.Creature.Elite.Elite.Damage     = 0.05
Rate.Creature.Elite.RARE.Damage      = 0.05
Rate.Creature.Elite.RAREELITE.Damage = 0.05
Rate.Creature.Elite.WORLDBOSS.Damage = 0.05

Rate.Creature.Normal.SpellDamage          = 0.05
Rate.Creature.Elite.Elite.SpellDamage     = 0.05
Rate.Creature.Elite.RARE.SpellDamage      = 0.05
Rate.Creature.Elite.RAREELITE.SpellDamage = 0.05
Rate.Creature.Elite.WORLDBOSS.SpellDamage = 0.05

Rate.Creature.Normal.HP          = 0.05
Rate.Creature.Elite.Elite.HP     = 0.05
Rate.Creature.Elite.RARE.HP      = 0.05
Rate.Creature.Elite.RAREELITE.HP = 0.05
Rate.Creature.Elite.WORLDBOSS.HP = 0.05

2)To ICC No.3 Boss to start fighting, and participate in the fight, the battle process to observe the damage of both sides, the gap is very obvious, unable to defeat the other side.

**Proposed change**
After modifying the overall configuration, both sides of the enemy's life and attack damage will be the same. Otherwise, the damage is different and the BOSS can't be passed.

**core**
AzerothCore rev. 0b9a0d8ea63c+ 2019-05-21 17:07:52 +0200 (master branch) (Win64, Release) (worldserver-daemon)

You've been working hard
Thank you

**Comment by Krath** [comment]
Who is the third boss of ICC? Are you talking about the Gunship Battle?

**Comment by forever2019** [comment]
> Who is the third boss of ICC? Are you talking about the Gunship Battle encounter?

Gunboat warfare
The gunboats of the two sides were inconsistent in injuries and could not defeat each other.
