### ISSUE TITLE
Wintergrasp -  flood message %faction take fortress [$50]

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#1869]
Zone: Wintergrasp
When: during each conquest event

Each few minuts this message is spamed in chat and middle screen
The message is 3 times or 2 or 1 time consecutive. but this is all conquest event.

The horde is taken wintergrasp fortress
The horde is taken wintergrasp fortress
The horde is taken wintergrasp fortress

or in case the alliance has the fortress.

The aliance is taken wintergrasp fortress
The aliance is taken wintergrasp fortress
The aliance is taken wintergrasp fortress

Corret funtion:
This message should only be displayed when the horde/aliance wins the battle for Wintergrasp

Check in 2 weeks ago masters and de last master
no modules
run in ubuntu 16

![spam conquista 1](https://user-images.githubusercontent.com/50475454/58193976-e7a19180-7c89-11e9-9cd1-06bc276a22d2.jpg)

**Comment by Knindzagxg** [comment]
I can confirm this as well.
Few players on server asked about this tho.

**Comment by spinzaku** [comment]
Confirmed, happened on my server.

**Comment by spinzaku** [comment]
Bounty fix? $5 maybe? hehe

**Comment by Winfidonarleyan** [comment]
Ah, sorry, miss click

**Comment by heyaapl** [comment]
Tested this - flood messages are working as expected
