### ISSUE TITLE
[Death Knight] (Quest) Where Kings Walk

### ISSUE THREAD

**Issue by DarthSidious666** [azerothcore/azerothcore-wotlk#18691]
### Current Behaviour

When beginning the quest "Where Kings Walk" travelling through the portal to Stormwind after breaking free of the Lich King's influence there should be an event or trigger that plays the sounds of boos from the crowd and the throwing of rotten fruit from the guards as well as them spitting at you. 

A debuff called 'Rotten Fruit' with flies buzzing around the player until they hand the letter to the King it should also set the player's reputation to unfriendly.

### Expected Blizzlike Behaviour

As described above, the event or trigger should happen.

### Source

https://us.forums.blizzard.com/en/wow/t/npcs-in-org-will-spit-and-throw-rotten-fruit-at-death-knights/1641166

### Steps to reproduce the problem

Enter the portal to Stormwind or Ogrimmar in the quest given by Mograine.
Travel through the City to where the King or Leader is

### AC rev. hash/commit

#18681 

### Operating system

Windows 11 x64

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/f7451657-4486-4640-91c3-fb63b4394287)
