### ISSUE TITLE
nohup run worldserver with cpu 180% usage

### ISSUE THREAD

**Issue by anyway2019** [azerothcore/azerothcore-wotlk#18696]
### Current Behaviour

run worldserver with nohup command in ubuntu cpu usage 180% ,but only 50% cpu usage in ./worldserver.

### Expected Blizzlike Behaviour

run worldserver with nohup should be equal to run ./worldserver.

### Source

it seems same issue https://github.com/TrinityCore/TrinityCore/issues/9998.

### Steps to reproduce the problem

```
nohup ./worldserver &
top
```
0player cpu usage 180%

```
./worldserver
top
``
0player cpu usage 52%

### Extra Notes

_No response_

### AC rev. hash/commit

branch master

### Operating system

ubuntu22.04

### Custom changes or Modules

none module installed

**Comment by kissingers** [comment]
use gdb and pm2 run as service
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/a34d27b1-9cd2-4736-a9e1-7a281f010fdd)

**Comment by anyway2019** [comment]
> use gdb and pm2 run as service ![image](https://private-user-images.githubusercontent.com/33601959/321661369-a34d27b1-9cd2-4736-a9e1-7a281f010fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODUzNDIsIm5iZiI6MTcxMjg4NTA0MiwicGF0aCI6Ii8zMzYwMTk1OS8zMjE2NjEzNjktYTM0ZDI3YjEtOWNkMi00NzM2LWE5ZTEtN2EyODFmMDEwZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzRiMDk3YjQ1NzRjZjE4NTEzNGNhOGFhYzEyZmRkZWRlNjcxNzg1YjBiNmNiNDYyN2JmZjkyM2M1OTZkMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PBdK11byZRDx8TK1wCGwWZetoOYifWZJYVYFSCscCM)

it works for me,thanks.
