### ISSUE TITLE
[Server] Crash 2024-04-12

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#18717]
### Current Behaviour

https://pastebin.com/5Ks9usCB

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

on Start Crash
til now pr

### Operating system

debian12 x64

**Comment by sudlud** [comment]
#18699 maybe related

**Comment by sudlud** [comment]
@kissingers Can you please add your revision hash?

**Comment by kissingers** [comment]
f05200fcca36a69060384df5e91a7c15aef27b19
to this pr

**Comment by kissingers** [comment]
fixed
