### ISSUE TITLE
(Creature): Broken-down Shredder has incorrect order of controlled spells.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#18729]
### Current Behaviour

Currently the [Broken-down Shredders](https://wowgaming.altervista.org/aowow/?npc=27354) in Grizzly Hills have a spell order of [Backfire](https://wowgaming.altervista.org/aowow/?spell=48558), [Overclock](https://wowgaming.altervista.org/aowow/?spell=48604), [Short Circuit](https://wowgaming.altervista.org/aowow/?spell=48548), (empty), and [Shredder Delivery](https://wowgaming.altervista.org/aowow/?spell=48610)

### Expected Blizzlike Behaviour

They should have an order of Short Circuit, Backfire, Overlock, (space), and Shredder Delivery.

### Source

Wrath Classic, [Wrath retail](https://youtu.be/7aVWto_rhGQ?si=X1Wsccj8cl95GSYl&t=47)

### Steps to reproduce the problem

1. `.go c id 27354`
2. `.quest add 12244`
3. Board the Shredder.
4. Observe its spells.

### AC rev. hash/commit

ec10eb841cd223c2c2b04a5b55fb9d9b23076687

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by heyitsbench** [comment]
The Shredder also can't seem to melee on AC, but it can on Classic.

**Comment by xubpwg** [comment]
@heyitsbench hello, it looks like that separate issue is needed for no shredder melee attack
