### ISSUE TITLE
Crash when sending items by collect mail

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#18741]
### Current Behaviour

When sending a collect email to a player who is then deleted, the server crashes.

![WoWScrnShot_041324_163516](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/3ff31308-9bdb-4182-9431-c9f142a3170e)

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/fe7d0512-3947-4ccb-b0e2-165dd7a1ffca)

### Expected Blizzlike Behaviour

Basically, we should corroborate that the player to be deleted has no pending mails. That way, the failure would possibly not occur. 

### Source

None

### Steps to reproduce the problem

Currently, the emulator has a bug, which consists of the following:
1. With one character, send a collect item to another character.
2. Delete the character that should receive the mail.
3. The emulator does not check before deleting the character that the character has pending mails.
4. Crashes the server.

### Extra Notes

None

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/723596c6734a

### Operating system

Windows 10

### Custom changes or Modules

None

**Comment by Nyeriah** [comment]
Can't reproduce following the steps provided on https://github.com/azerothcore/azerothcore-wotlk/commit/cdc72216c8b9282906fdd3634364a29c56973fd0

**Comment by pangolp** [comment]
> Can't reproduce following the steps provided on [cdc7221](https://github.com/azerothcore/azerothcore-wotlk/commit/cdc72216c8b9282906fdd3634364a29c56973fd0)

I am testing with the latest version. Mine was 3 days old.

**Comment by sudlud** [comment]
So the crash should happen when you try to login with the sender of the mail, after the recipient was deleted?

**Comment by pangolp** [comment]
Tested on the latest version of the emulator.

https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/417375c5-4ca3-4a15-b46b-f85bda2ff2b6

**Comment by pangolp** [comment]
> So the crash should happen when you try to login with the sender of the mail, after the recipient was deleted?

For me, the emulator should not let you delete the character if it has a pending mail. The same thing it does when you change faction. You can't change until you delete the email. Although it could be another reason. I mention that, but I'm not 100% sure if it would be the way.

**Comment by MarioJvPz98** [comment]
It seems very good to me that this error is finally known, they have been knocking down projects for many months with the aim of damaging their reputation in order to demand payment for the "fix" and in the end they seek their own benefit and not help the community, how unfortunate.

**Comment by pangolp** [comment]
> It seems very good to me that this error is finally known, they have been knocking down projects for many months with the aim of damaging their reputation in order to demand payment for the "fix" and in the end they seek their own benefit and not help the community, how unfortunate.

What they did is done. Now let's look forward and see how we fix this.

**Comment by MarioJvPz98** [comment]
Of course, I will try to read the entire file and analyze the error in the console.

**Comment by MarioJvPz98** [comment]
Of course, I will try to read the entire file and analyze the error in the console.

**Comment by PkllonG** [comment]
Maybe we can discuss this and feel free to close the PR if you don't agree
https://github.com/azerothcore/azerothcore-wotlk/pull/18744

**Comment by pangolp** [comment]
> Maybe we can discuss this and feel free to close the PR if you don't agree
> https://github.com/azerothcore/azerothcore-wotlk/pull/18744

I don't care which solution is chosen. What matters to me is that the problem is solved. It doesn't matter if it's your PR or mine. As long as it gets fixed, I really don't care.

**Comment by walkline** [comment]
I can't reproduce the crash. Maybe there is some dependency on config option?

**Comment by pangolp** [comment]
> I can't reproduce the crash. Maybe there is some dependency on config option?

As far as I remember, I'm using the default values. Check to see if you sent the item collect. Because if you send the item and the gold, the error is not generated. The problem is that the second player, upon being eliminated, will never receive the email and will not be able to reply to it. I attach a video with the steps. Since you test the translator, you may misspell some word.

**Comment by walkline** [comment]
> Check to see if you sent the item collect. Because if you send the item and the gold, the error is not generated. 
I tried to send a stack of 5 items, and choose Cash On Delivery (C. O. D.) - no crash.

**Comment by pangolp** [comment]
> > Check to see if you sent the item collect. Because if you send the item and the gold, the error is not generated. 
> 
> I tried to send a stack of 5 items, and choose Cash On Delivery (C. O. D.) - no crash.

I really do not know what to say. I updated the kernel to day 13, and I don't remember making any modifications to the worldserver. Used the default values for most, or at least 99% of the options. I am not using any module. The tests were carried out on Windows. Maybe in another operating system it won't cause problems (although it should).

**Comment by PkllonG** [comment]
All I can say is that I also broke down

**Comment by pangolp** [comment]
> All I can say is, my server crash

My local version of Windows 10 too. Maybe in Linux it doesn't fail. It would be strange, but it wouldn't surprise me, because in other cases, I have also had different behaviors. Like when we put the authserver in Firelands. On Windows we got a nullptr, but on Mac we could enter the realm.

**Comment by walkline** [comment]
@pangolp are you running server on windows as well? I’m testing on MacOS.

**Comment by pangolp** [comment]
I made the video, because sometimes the translator can express my words wrong or I can make a mistake when expressing them. But in the video, you can see the exact steps to reproduce the error (at least on Windows)

**Comment by PkllonG** [comment]
I'm windows too

**Comment by pangolp** [comment]
> @pangolp are you running server on windows as well? I’m testing on MacOS.

It is the local, development environment. I don't have a server. But possibly in Unix the error does not exist. This has already happened to us on other occasions.

**Comment by sudlud** [comment]
@Nyeriah I was able to reproduce this on Windows at cdc72216c8b9

this is what I did:

```
create orc hunter
.level 79
.tele orgrimmar
empty mailbox completely
logout

create troll hunter
.level 79
.tele orgrimmar
.modify money 1000000000
empty mailbox completely (there should be a mail with a gift from Ronin)
unpack gift
open mailbox
new mail to orc hunter
add 5x runic healing potion
add 10g 0s 0c
select C.O.D.
send
logout

delete orc hunter in selection screen
crash
```

I think the important step here (maybe) is to send the items AND gold, I've almost missed this in the video by @pangolp.

crashlog:
https://gist.github.com/sudlud/fd23cbb3d57fe570ac93de41ad3f1428

**Comment by Nyeriah** [comment]
Yes, thanks for testing. It was an issue with COD mails specifically that wasn't clear to me at first

**Comment by sudlud** [comment]
thanks for the fix! character deletion in the character selection screen now fails as expected with:
`Character deletion failed`

BUT

I can still crash the server at 564192f88 when deleting the character by command in the server console:
`.character erase ...`

crashlog:
https://gist.github.com/sudlud/b9e03016f170df0d7db03a5af0c8c3f2

😃

**Comment by pangolp** [comment]
> thanks for the fix! character deletion in the character selection screen now fails as expected with: `Character deletion failed`
> 
> BUT
> 
> I can still crash the server at [564192f](https://github.com/azerothcore/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03) when deleting the character by command in the server console: `.character erase ...`
> 
> crashlog:

What you mention is true, but it would no longer be a product of a third party, it would be a mutilation by the server administrator hahaha. Here the problem, is that any player, with a simple email, in Windows, could bring down the kingdom of some people. 90% use Linux, so they could not reproduce the error. In fact, I use Windows only locally. If I had a server, I would use Debian or Ubuntu. But anyway, it had to be corrected, to avoid that the crooks that are going around, charge people who don't know about this, and try to make money by extorting them.

I think what you say about the console is basic, and it also happens to me with another report, about the `character level` or `level up` command. But as you say, the failure can only occur, if the command is executed. You can add a validation to the command, to avoid that the character is deleted in this case. But that would be negligence hahaha.

**Comment by pangolp** [comment]
That problem you mention, happened to me with this... https://github.com/azerothcore/azerothcore-wotlk/issues/16516. I was thinking whether to close it, or add validation to the command. But... there is no way a player can reproduce it, it would be the fault of the administrator, or the person who has access to the command. Through the console, or inside the game.

**Comment by heyitsbench** [comment]
> What you mention is true, but it would no longer be a product of a third party, it would be a mutilation by the server administrator hahaha.

Even still, the server should never have a condition in which it would crash IMO, regardless of circumstance surrounding it.

> But... there is no way a player can reproduce it, it would be the fault of the administrator, or the person who has access to the command.

Multiple players on CC have had the issue happen to them.

**Comment by sudlud** [comment]
Yes - no input in any "normal" interface of the server should ever lead to a crash, so also any command input should be secured imo.

**Comment by pangolp** [comment]
Correct, it should be corrected.

**Comment by MarioJvPz98** [comment]
I agree with the error presented here, since we tested it several times yesterday with @pangolp  and the error was the one shown in the video posted at the top of the thread.

The temporary fix I was able to give on my local server was this.
 
 
    if (CharacterCacheEntry const* playerData = sCharacterCache->GetCharacterCacheByGuid(guid))
    {

        // check mailbox before deleting the character and not causing a crash !!
        if (playerData->MailCount)
        {
            SendCharDelete(CHAR_DELETE_FAILED);
            std::shared_ptr<CharacterFactionChangeInfo> factionChangeInfo = std::make_shared<CharacterFactionChangeInfo>();
            SendCharFactionChange(CHAR_DELETE_FAILED, factionChangeInfo.get());
            return;
        }

**Comment by MarioJvPz98** [comment]
Although the message displayed on the screen when trying to delete the character is not correct, it is a minor problem compared to the worldserver crashing by sending mail

**Comment by pangolp** [comment]
> Although the message displayed on the screen when trying to delete the character is not correct, it is a minor problem compared to the worldserver crashing by sending mail.

In this case, you have 2 error messages. The one in the email and the other one we put. Anyway, the branch has already been merged, if you update the core, you will get the change.

```c++
if (CharacterCacheEntry const* playerData = sCharacterCache->GetCharacterCacheByGuid(guid))
{
    // check mailbox before deleting the character and not causing a crash !!
    if (playerData->MailCount)
    {
        std::shared_ptr<CharacterFactionChangeInfo> factionChangeInfo = std::make_shared<CharacterFactionChangeInfo>();
        SendCharFactionChange(CHAR_DELETE_FAILED, factionChangeInfo.get());
        return;
    }
}
```

**Comment by MarioJvPz98** [comment]
@pangolp Yes you're right. I did it today around 4 AM so there I was also with my head a little confused, I hadn't realized that I used the 2 messages. In any case, it is a "stable" fix for the moment and a great basis for the final fix, I think. Good job. :D

**Comment by pangolp** [comment]
Now we only need to add that they cannot use the command and that's it. I will see if I can make that modification now.

**Comment by MarioJvPz98** [comment]
> Now we only need to add that they cannot use the command and that's it. I will see if I can make that modification now.

The permission level for its execution from the database can be raised to level 4 (admin) for the command and thus, if this problem were to occur, it would be an error on the part of the administration, although it is not the definitive fix, it could be a solution. temporary and thus avoid rollbacks due to falls or crashes. If you need a hand, I'd like to help and learn more too. ❤️

**Comment by pangolp** [comment]
> > Now we only need to add that they cannot use the command and that's it. I will see if I can make that modification now.
> 
> The permission level for its execution from the database can be raised to level 4 (admin) for the command and thus, if this problem were to occur, it would be an error on the part of the administration, although it is not the definitive fix, it could be a solution. temporary and thus avoid rollbacks due to falls or crashes. If you need a hand, I'd like to help and learn more too. ❤️

Apparently, they have made another contribution, which seems to correct everything, but well, it will be a matter of testing it. I already mentioned it, but I'll say it again. The solution, really for me, is indistinct. As long as the failure is corrected, let it be solved in any way (obviously, not breaking other mechanics). In this case, we are preventing the character from being eliminated, although the message was not clear. We will see what the change would be with the other fix.
