### ISSUE TITLE
LBRS Small buggs and missing movements

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1874]
SMALL DESCRIPTION:

When I tested a pull I found something else that doesn't work correctly.

EXPECTED BLIZZLIKE BEHAVIOR:
Spire Spider ID 10374 and Spire Spiderling 10375 should also move a little see video.

If you go to the Boss Mother Smolderweb Id 10596 there should be some Spire Spider there and some small Spire Spiderling there.

Spire Spider ID 10374 should cast after some time the spell summon Spire Spiderling, Spire Spiderling do that too and there will be 4 Spire Spiderling Spire. 

If the group dies, the spire should despawn Spiderling after 10 seconds. Also fails have a death warrant after 10 seconds.

after 10 seconds die the spiders created by Spire Spider.

CURRENT BEHAVIOUR:

- [x] Spire Spider ID 10374 and Spire Spiderling 10375 should also move a little see video.

- [x] If you go to the Boss Mother Smolderweb Id 10596 there should be some Spire Spider there and some small Spire Spiderling there.
But are these also dead because they are all dead after 10 seconds after entering the instance

- [X] Spire Spider ID 10374 should cast after some time the spell summon Spire Spiderling, Spire Spiderling do that too and there will be 4 Spire Spiderling Spire. 

- [X] If the group dies, the spire should despawn Spiderling after 10 seconds. Also fails have a death warrant after 10 seconds.

- [X] after 10 seconds die the spiders created by Spire Spider.

AC Video https://www.youtube.com/watch?v=QB-BoDceess

As you can see here, there is something mighty that would have to be spawned from the offi, but it seems well known to me.

https://youtu.be/65Fd2AzjYkc?t=144

STEPS TO REPRODUCE THE PROBLEM:
Take the order and wait 10 seconds.
.go xyz -139.523 -525.879 6.36398 229

BRANCH(ES):
AzerothCore rev. b67ea15d1651+ 2019-05-23 15:26:51 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: NO

**Comment by poszer** [comment]
So, what's left to fix, just movement of these big spiders , right?

**Comment by Selyria** [comment]
jepp also sees everything crawling well

**Comment by Voxstrasza** [comment]
If I understand the issue, the issue has been fixed.  The spider boss summons Spiderlings, the spider mobs summon more Spiderlings, and the room is populated.  

Closing this issue.
