### ISSUE TITLE
Race 1 Class 6 Does Not Have Initial Stats Data

### ISSUE THREAD

**Issue by StraysFromPath** [azerothcore/azerothcore-wotlk#18769]
### Current Behaviour

Editing the max level of a server in config files causes worldserver to crash on launch.

Not every time but most of the time.

What annoys me most is eventually it gives up and works, but I have run worldserver like 14-20 times for it to work.

### Expected Blizzlike Behaviour

Resolutions:

A) Bundle azerothcore with "example" data for DKs below 55. Costs 5kb to solve 100 head aches. This is still blizzlike as it's impossible with base acore to have a DK below 55.

B) Have a line of working code that actually checks for the DK stats, because they are in my DB using the above link, but it still crashes 75% of the time on launch with that error code.

This started to break when Acore moved away from the combined class AND level stats into two tables, class stats and race stats. I think there's an old line of code looking for a nonexistent table.

### Steps to reproduce the problem

Edit worldserver config to edit max player level to below 55.

Use SQL to insert DK stats for below 55. (https://gist.github.com/heyitsbench/21fa68994f0f20563148c164ee3dcc67)

Watch it bug out.

### Extra Notes

Over 85 users on discord have reported this issue.

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/53864433888c2b827399b4db8b27ebb9b82c26f3 2024-04-17 03:53:43 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

win10 server

### Custom changes or Modules

none

**Comment by StraysFromPath** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/119371540/114579f1-8538-46c8-ad23-b24cd10dd51b)

https://github.com/azerothcore/azerothcore-wotlk/issues/14808#issuecomment-1409779172

**Comment by Kitzunu** [comment]
this is correct as a DK could never start below 55 therefore there are no "real" values for it. If you wanna run it below you do it yourself

**Comment by StraysFromPath** [comment]
> this is correct as a DK could never start below 55 therefore there are no "real" values for it. If you wanna run it below you do it yourself

I have personally added the DK levels 1-55 and the worldserver still crashes.

If you read the issue, the issue is that the crash happens regardless of if data exists or not.

The issue is still open/active/live on latest.
