### ISSUE TITLE
WorldSocket::ReadHeaderHandler(): client IPHERE sent malformed packet (size: 16672, cmd: 544498019)

### ISSUE THREAD

**Issue by brunolopes1996** [azerothcore/azerothcore-wotlk#18778]
### Current Behaviour

We are currently running a small wow private server now a repack, compiled source, compiled/cloned like  2 months ago, and some how sometimes we that that worldsocket warning spam in the worldserver.exe and dont know what to do about it...

### Expected Blizzlike Behaviour

Not have that red mensage spam?

### Steps to reproduce the problem

No idea how to reproduce the issue sorry

### AC rev. hash/commit

AzerothCore rev. 9616433b6609+ 2024-03-10 16:52:03 -0300 (master branch) (Win64, Release, Static)

### Operating system

windows 10

### Custom changes or Modules

> List enable modules:
- mod-aoe-loot
- mod-autobalance
- mod-eluna
- mod-individual-xp
- mod-instance-reset
- mod-learn-spells
- mod-skip-dk-starting-area
- mod-solo-lfg
- mod-transmog
- mod-world-chat

**Comment by PkllonG** [comment]
I have that here, too

**Comment by brunolopes1996** [comment]
Yea the major problem about it is that some times it causes lag spikes

**Comment by Kitzunu** [comment]
Most likely some port scanning services

**Comment by brunolopes1996** [comment]
Not really, It is a way of DDOS, i understand that some bots also ping the IP but thats once in a while, now in the other hand people with malicious intent ping the worldserver port like crazy and the server enventually crashes, my solution to this was buy aditional DDOS protection for TCP protocols, but i have used other emulators and this doesnt happen, just tought you should know

**Comment by manstfu** [comment]
https://i.hizliresim.com/NDnNZL.jpg

Hello, thats a DOS method i saw 10 years ago, it can be done using a custom wow client or a WPE script as i remember, had same problem with a confirmed 'hater', ip was also attached to his account in-game, ip ban solve this issue, but he can also change his ip and create new account.

```
3000+ lines
WorldSocket::ReadHeaderHandler(): client 86.** sent malformed packet (size: 16672, cmd: 544498019)
WorldSocket::ReadHeaderHandler(): client 86.** sent malformed packet (size: 16672, cmd: 544498019) 
```

https://github.com/TrinityCore/TrinityCore/issues/22765
https://community.trinitycore.org/topic/14087-error-client-sent-malformed-packet/

**Comment by CheckYourFax** [comment]
> Not really, It is a way of DDOS, i understand that some bots also ping the IP but thats once in a while, now in the other hand people with malicious intent ping the worldserver port like crazy and the server enventually crashes, my solution to this was buy aditional DDOS protection for TCP protocols, but i have used other emulators and this doesnt happen, just tought you should know

I have checked all IP's that were sending malformed packets on a family-only AzerothCore server and 90% are from valid port scanning services that are trying to warn people who have exposed services with old versions of software with known security vulnerabilities. They are not dangerous and can be safely ignored.

If you only play with a few people, the best way to stop it is to change port forward rules in your NAT router to only allow specific external IP's to forward traffic to your AC server.  This will make the NAT router drop packets that are not from specific legit IP addresses.
