### ISSUE TITLE
UBRS The Beast Small bug Event

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1878]
SMALL DESCRIPTION:

So if you go into the room where the boss is The Beast, the boss should slowly approach you when you are halfway into the room.

If you killed the boss, and he's a furrier, you should appear to the Npc Finkle unicorn and give him a quest.

EXPECTED BLIZZLIKE BEHAVIOR:
https://wow.gamepedia.com/The_Beast
https://www.youtube.com/watch?v=J426t8ameoQ

So if you go into the room where the boss is The Beast, the boss should slowly approach you when you are halfway into the room.

If you killed the boss, and he's a furrier, you should appear to the Npc Finkle unicorn and give him a quest.

According to the story, Finkle Unicorn is eaten by the Beast as he swam around in the lava and was then in the stomach of the Beast. He was freed when the Beast furriers were found.

CURRENT BEHAVIOUR:

- [ ] The boss should be coming at you when you're halfway through the room.

- [X] Spells The Boss Has FLAMEBREAK = 16785, IMMOLATE = 20294, TERRIFYINGROAR = 14100,
FLAMEBREAK and TERRIFYINGROAR think the range is too small

- [ ] Spells that the boss lacks Berserker Charge, Fire Blast, Fireball,

- [ ]   Finkle Einhorn stands behind the beast that shouldn't be so he should only appear when you have the beast furriers.

- [X] Finkle Unicorn appears when you squeeze the beast.

AC Video https://youtu.be/xMM0rDFLjgg

STEPS TO REPRODUCE THE PROBLEM:
.go 13.18 -536.23 110.93 229

BRANCH(ES):
AzerothCore rev. b67ea15+ 2019-05-23 15:26:51 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: NO

**Comment by Voxstrasza** [comment]
Still an issue as of `221f33b5b7af`
