### ISSUE TITLE
Cannon type mobs are moving and porting

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#18789]
### Current Behaviour

cannons are moving - they port to close a range gap for their cast

### Expected Blizzlike Behaviour

be stationary

### Source

common sense

### Steps to reproduce the problem

.

### Extra Notes

https://www.wowhead.com/wotlk/npc=21233/legion-fel-cannon
https://www.wowhead.com/wotlk/zone=3483/hellfire-peninsula#npcs;q=cannon
https://www.wowhead.com/wotlk/zone=3518/nagrand#npcs;q=cannon

and many more

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

ubuntu

### Custom changes or Modules

chromiecraft

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/20504
