### ISSUE TITLE
[Regression] Mote of Shadow drop chance

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#18788]
### Current Behaviour

https://github.com/azerothcore/azerothcore-wotlk/pull/15590
https://github.com/chromiecraft/chromiecraft/issues/4732

reduced the drop chance of motes to

1.0615% on Unstable Voidwraith
1.0194% on Voidshrieker

### Expected Blizzlike Behaviour

going by wowhead and the other chances in the PR, a higher drop rate seems expected (all other rates are between 15-60%)
https://www.wowhead.com/wotlk/npc=18869/unstable-voidwraith
https://www.wowhead.com/wotlk/npc=18870/voidshrieker

### Steps to reproduce the problem

https://github.com/azerothcore/azerothcore-wotlk/pull/15590/files

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

ubuntu

### Custom changes or Modules

chromiecraft

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19088
