### ISSUE TITLE
Crashlog

### ISSUE THREAD

**Issue by borisov99** [azerothcore/azerothcore-wotlk#18792]
### Current Behaviour

Hello, I sometimes have a server crash. I can't figure out for what reason. I'm applying a crash log : 
https://gist.github.com/borisov99/f134d52c68e0f4ffcc708f9e87832182

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

Ubuntu

**Comment by sudlud** [comment]
Can you please update this issue with the output of:

.server debug

So we can see the revision beeing used on your server.

Also are you using any modules?

**Comment by borisov99** [comment]
Of course, thank you!
![Smv5hNfPaaA](https://github.com/azerothcore/azerothcore-wotlk/assets/34372128/acfc9bce-3ac6-4bff-a4d5-1cf7691e8c19)
![saqvGG91uZs](https://github.com/azerothcore/azerothcore-wotlk/assets/34372128/ec83ebad-5d51-40a6-99fc-2d6c9caba1da)

**Comment by walkline** [comment]
It's seems that you are using custom code. Can you test on clear core?
