### ISSUE TITLE
Custom npc trainer doesn't work

### ISSUE THREAD

**Issue by huchao-github** [azerothcore/azerothcore-wotlk#18794]
### Current Behaviour

When i create some npc for trainer, and set the npcflag to 16|64, then i found it doesn't work. I check the source code for the function ObjectMgr::AddSpellToTrainer in ObjectMgr.cpp.

void ObjectMgr::AddSpellToTrainer(uint32 entry, ... )
{
    if (entry >= ACORE_TRAINER_START_REF)
        return;
    ...
}

I got the reasons. ACORE_TRAINER_START_REF is define 200000. and my npc's entry is > 200000, so it doesn't work. and i remove this condition, my custom npc trainer is worked. 

But i don't understand why need entry < 200000. Is there any special reason needs to add this condition?

### Expected Blizzlike Behaviour

.

### Steps to reproduce the problem

.

### AC rev. hash/commit

.

### Operating system

Windows 10 x64

**Comment by Cinnamohn** [comment]
The spell lists used by trainers start with an ID of 200001. They are then assigned to creature_template IDs as a negative value like loot_template references. You can find everything in the npc_trainer table.
