### ISSUE TITLE
WorldServer Lag

### ISSUE THREAD

**Issue by franklampardahar** [azerothcore/azerothcore-wotlk#188]
Hi to all users who see this post . i compile server as debug mode to show me crash logs but now i cant start server and play with my personal computer because worldserver is full lag when i type .help from worldserver console this give me answer after 5 min and when i playing 4-10 min take to retrieve my characters and loading game after this game is lag cant type or cast spell . Thanks to reading how i can fix it?
my computer hardware system : 2gb ram - 2core cpu i know it's low but i think this can support 1 player :D

**Comment by ShinDarth** [comment]
that sounds very weird... what is the output of .server info ?

**Comment by franklampardahar** [comment]
@ShinDarth i test it on 4GB ram working good but not perfect 3.4GB of my memory is working all time for debug mode but fix lag thanks
