### ISSUE TITLE
[Arcatraz] Arcatraz Warders dont try to establish distance after Wing Clip

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#18815]
### Current Behaviour

https://wowgaming.altervista.org/aowow/?npc=20859 cast Wing Clip to root their target

### Expected Blizzlike Behaviour

should cast Wing Clip and if it hits successfully, they should try to get 12 yards range

### Source

https://youtu.be/pmviK7IVpLQ?t=65

### Steps to reproduce the problem

engage mob

### Extra Notes

**this is a big generic AI issue: when a mob roots a player (frostnova, etc. and does so from melee range, it should establish some range (leaving melee range) to the targets - this is applicable literally to all mobs that have a root effect and at least 1 ranged ability**

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d030260dd4b7e0aae88f609222877bd2aabdafe0

### Operating system

ubuntu

### Custom changes or Modules

chromiecraft

**Comment by balleny** [comment]
https://github.com/chromiecraft/chromiecraft/issues/5301

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/18026

https://github.com/chromiecraft/chromiecraft/assets/46330494/bb0a6d00-6a25-4d77-9ae6-105a3595f097
