### ISSUE TITLE
Shirrak often applies multiple stacks of the bleed effect

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#18823]
### Current Behaviour

Boss often applies multiple stacks within the same second onto players

### Expected Blizzlike Behaviour

no double stacks within a second

### Steps to reproduce the problem

https://wowgaming.altervista.org/aowow/?npc=18371

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

ubuntu

### Custom changes or Modules

chromiecraft

**Comment by balleny** [comment]
https://github.com/chromiecraft/chromiecraft/issues/6575

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/02104ca89b27211b89aa699616edd408ac6adccd
