### ISSUE TITLE
[SSC] Priestess Spirit not spawning

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#18824]
### Current Behaviour

https://www.wowhead.com/tbc/npc=21220/coilfang-priestess just dies

### Expected Blizzlike Behaviour

Priestess Spirit will spawn when the Coilfang Priestess dies. As a Spirit, she will spam cast [Holy Nova](https://www.wowhead.com/tbc/spell=38589/holy-nova), dealing Holy damage and healing nearby enemies.
https://www.wowhead.com/tbc/npc=22210/priestess-spirit

### Source

https://www.wowhead.com/tbc/guide/trash-mobs-serpentshrine-cavern-ssc-strategy-burning-crusade-classic

### Steps to reproduce the problem

kill npc

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

ubuntu

### Custom changes or Modules

chromiecraft

**Comment by balleny** [comment]
https://github.com/chromiecraft/chromiecraft/issues/6590

**Comment by Gultask** [comment]
https://www.wowhead.com/tbc/npc=21220/coilfang-priestess#comments:id=192172

scrapped mechanic? Might add to mod-progression.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/2c5d4aaf-f48f-45cc-9107-93972bbc85b9)
