### ISSUE TITLE
item_template wrong confusing values in maxcount & stackable

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1882]
##### SMALL DESCRIPTION:

Wrong confusing values in the database

##### ISSUE:

These wrong values do not harm but if you have another app reading them, it can be stupid. Example: you display an item's caracteristic as Unique(X) where X = `maxcount`.
Then you end up with `Unique (2147483647)` instead of nothing. Ingame it's fine though. But then you realize it's stupid and you waste precious minutes of your time.

As written in the wiki, if the item should be available in infinite quantity, put a 0 instead (default value).

##### STEPS TO REPRODUCE THE PROBLEM:

```sql
SELECT entry, name, maxcount, stackable, description FROM item_template
WHERE maxcount > 1000
or stackable > 1000
;
```
Check the ridiculous values, some don't even make sense. 

##### EXTRA NOTES:

Imo, it should be changed, what do you think?

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

ded199dd7e7bb03813e8c84d3bbe6a9b37429169

**Comment by BarbzYHOOL** [comment]
note: it's a small cleanup of confusing data in the db, i have other things like that in mind (like obsolete entries etc)

**Comment by Kitzunu** [comment]
These are sniffed values
