### ISSUE TITLE
Command .mailbox doesn't work & never worked

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1883]
##### SMALL DESCRIPTION:

Command .mailbox never worked

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should work when you're a GM on/off GM mode

##### CURRENT BEHAVIOUR:

In console, I get this `Barbz attempt open mailbox in cheating way.` *notice the perfect english*

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a GM character
2. `.send mail your_character "hello" "butch"`
1. Log out and log back in
3. Put GM mode on (or off, same thing)
1. Type `.mailbox` = doesn't work (and check the console error)
1. Open the mail box manually, like a normal player and you will see your mail.

##### EXTRA NOTES:

Bug always present since the beginning.
I'm on an OLD core though.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

e8aff9feac0fdcce5591b9c6e5e1eb1f77d57bc7

##### OPERATING SYSTEM:

Ubuntu

**Comment by Selyria** [comment]
Yes I can confirm that you are not going to be completely blocked even if you go to a mailbox afterwards you can no longer send anything.

only after a relogg everything goes again except for command .mailbox

**Comment by lineagedr** [comment]
I guess a fix would be to check the gmlevel of the player:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Handlers/MailHandler.cpp#L23


`if (_player->GetSession()->GetSecurity() < SEC_MODERATOR)
		{
			sLog->outError("%s attempt open mailbox in cheating way.", _player->GetName().c_str());
			return false;
		}`

**Comment by BarbzYHOOL** [comment]
Hmm, maybe @lineagedr however I think to check the GM level there are other methods if I recall.

Like this `if (m_player->IsGameMaster())`

**Comment by lineagedr** [comment]
> Hmm, maybe @lineagedr however I think to check the GM level there are other methods if I recall.
> 
> Like this `if (m_player->IsGameMaster())`
> 
> ```c++
> if (guid == _player->GetGUID() && ! m_player->IsGameMaster())
> {
>   sLog->outError("%s attempts to open the mailbox by cheating.", _player->GetName().c_str());
>   return false;
> }
> ```
> 
> maybe this?

You've said that
> It should work when you're a GM on/off GM mode

IsGameMaster checks for .gm on

**Comment by BarbzYHOOL** [comment]
oh ok thank you

**Comment by wizzymore** [comment]
@lineagedr way is correct, can someone test it? Did you test it @lineagedr ?

**Comment by BarbzYHOOL** [comment]
and this `guid == _player->GetGUID()` ?

**Comment by BarbzYHOOL** [comment]
Note: If you didn't check your mailbox before, then it will be empty. If you checked it before, it will have what you already saw last time.
