### ISSUE TITLE
[TK] Bloodwarder Marshals cast WW twice

### ISSUE THREAD

**Issue by balleny** [azerothcore/azerothcore-wotlk#18834]
### Current Behaviour

https://www.wowhead.com/tbc/npc=20035/bloodwarder-marshal casts whirlwind twice

### Expected Blizzlike Behaviour

cast it once and then later again

### Source

.

### Steps to reproduce the problem

engage and see him cast it twice directly in a row

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

ubuntu

### Custom changes or Modules

chromiecraft

**Comment by balleny** [comment]
https://github.com/chromiecraft/chromiecraft/issues/7007

**Comment by Rorschach91** [comment]
It seems that Bloodwarder Marshals doesn't cast Whirlwind twice anymore.
I close this report.
