### ISSUE TITLE
[TBC Vendors] Wrong vendor inventories: Not selling "Wicked Arrow" and "Impact Shot"

### ISSUE THREAD

**Issue by Arcitec** [azerothcore/azerothcore-wotlk#18845]
### Current Behaviour

The TBC ammo vendors in AzerothCore are not selling the correct ammo. I saw this at the first two vendors I have checked and I guess it applies to every ammo vendor.

They only sell level 45 and 65 ammo. They don't sell the level 55 ammos ("Wicked Arrow" and "Impact Shot").

Other items are missing too, for example Floyd Pinkus is supposed to sell things like Soothing Spices, but he doesn't sell that either on AzerothCore.

I am guessing that many/most TBC vendors have some small issues like these.

### Expected Blizzlike Behaviour

The official inventory contains Wicked Arrow and Impact Shot, and other items. But ammo is the most important oversight since it means having to go back to Azeroth constantly to get ammo refills until you reach level 65 to buy the Outlands ammo.

### Source

https://www.wowhead.com/wotlk/npc=16602/floyd-pinkus
https://www.wowhead.com/wotlk/item=28053/wicked-arrow#sold-by;0+3+12
https://www.wowhead.com/wotlk/item=28060/impact-shot#sold-by;0+3+12

### Steps to reproduce the problem

1. Visit vendor.

### AC rev. hash/commit

AzerothCore rev. dadd75953bfe 2024-04-24 07:34:32 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Linux

**Comment by heyitsbench** [comment]
> They don't sell the level 55 ammos ("Wicked Arrow" and "Impact Shot").

Please provide creature examples, the vendors I've checked are selling these items.

> [...] for example Floyd Pinkus is supposed to sell things like Soothing Spices [...]

No he isn't, this is a failure on Wowhead's side (which I have emailed them about in the past), it is a remnant of them selling both Flint and Tinder and Soothing Spices back in TBC but these items were removed from vendors when they were made useless in Wrath.

**Comment by Arcitec** [comment]
> Please provide creature examples, the vendors I've checked are selling these items.

I just arrived in Outlands with my Hunter. So I saw the Horde <Supply something> vendor at the right side of the dark portal, and then Floyd Pinkus at Thrallmar. I have not checked any other vendors. These two did not carry any of the level 55 ammos but they carry lower level ones.

I am on ChromieCraft.

> No he isn't, this is a failure on Wowhead's side (which I have emailed them about in the past), it is a remnant of them selling both Flint and Tinder and Soothing Spices back in TBC but these items were removed from vendors when they were made useless in Wrath.

Ah that's great to hear about the other items. :)

**Comment by heyitsbench** [comment]
> I am on ChromieCraft.

This is a ChromieCraft issue then, and should be reported there in the future. This particular issue has [already been reported there](https://github.com/chromiecraft/chromiecraft/issues/5896), but it is not an issue with AC itself.

**Comment by Arcitec** [comment]
@heyitsbench Oh okay. Since ChromieCraft is the official AzerothCore mass test realm, I thought it would be up to date regarding things like this so I thought it was a core issue. Sorry for the issue report. :)

**Comment by heyitsbench** [comment]
> Sorry for the issue report.

Don't worry about it, I don't blame you for the confusion. 😛
