### ISSUE TITLE
Problems encountered during compilation.

### ISSUE THREAD

**Issue by lemonmomomo** [azerothcore/azerothcore-wotlk#18854]
### Current Behaviour

At compile time
E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (119,26): warning C4834: Abandon the return value of a function with the [nodiscard]] attribute (compile source file "../../../../AzerothCorewotlk/src/server/apps/authserver/Server/AuthSession. cpp")

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (119,26): Template instantiation context (earliest instantiation context) is E: \ ac335 \ AzerothCore wotlk \ src \ server \ apps \ authserver \ Server \ AuthSession. h (64,28): View references to instantiating 'Socket' on the compiled class template

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (114,10): When compiling the class template member function "void Socket:: QueuePacket (Message&)", E: \ ac335 \ AzerothCore wotlk \ src \ server \ apps \ authserver \ Server \ AuthSession. cpp (280,20): Please refer to the first reference to "Socket: QueuePacket" in "AuthSession:: SendPacket"

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (202,34): warning C4834: Abandon the return value of a function with the [nodiscard]] attribute (compile source file "../../../../AzerothCore wotlk/src/server/apps/authserver/Server/AuthSession. cpp")

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (202,34): The template instantiation context (earliest instantiation context) is E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (191,10): When compiling the class template member function "void Socket: WriteHandle (boost:: system: errorCode, size_t)", E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (158,33): Please refer to the first reference to "Socket:: WriteHandler" in "Socket:: AsyncProcessQueue"

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (119,26): Please refer to the first reference to "Socket:: AsyncProcessQueue" in "Socket:: QueuePacket"

E: \ ac335 \ AzerothCore wotlk \ src \ server \ apps \ authserver \ Server \ AuthSession. cpp (280,20): Please refer to the first reference to 'Socket:: QueuePacket' in 'AuthSession: SendPacket'

### Expected Blizzlike Behaviour

May I ask if you have any similar situations? What should be done if there is this problem? Thank you!

### Steps to reproduce the problem

I didn't notice it before, but I suddenly saw it during compilation.

### AC rev. hash/commit

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (119,26): warning C4834: Abandon the return value of a function with the [nodiscard]] attribute (compile source file "../../../../AzerothCorewotlk/src/server/apps/authserver/Server/AuthSession. cpp")

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (119,26): Template instantiation context (earliest instantiation context) is E: \ ac335 \ AzerothCore wotlk \ src \ server \ apps \ authserver \ Server \ AuthSession. h (64,28): View references to instantiating 'Socket' on the compiled class template

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (114,10): When compiling the class template member function "void Socket:: QueuePacket (Message&)", E: \ ac335 \ AzerothCore wotlk \ src \ server \ apps \ authserver \ Server \ AuthSession. cpp (280,20): Please refer to the first reference to "Socket: QueuePacket" in "AuthSession:: SendPacket"

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (202,34): warning C4834: Abandon the return value of a function with the [nodiscard]] attribute (compile source file "../../../../AzerothCore wotlk/src/server/apps/authserver/Server/AuthSession. cpp")

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (202,34): The template instantiation context (earliest instantiation context) is E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (191,10): When compiling the class template member function "void Socket: WriteHandle (boost:: system: errorCode, size_t)", E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (158,33): Please refer to the first reference to "Socket:: WriteHandler" in "Socket:: AsyncProcessQueue"

E: \ ac335 \ AzerothCore wotlk \ src \ server \ shared \ Network \ Socket. h (119,26): Please refer to the first reference to "Socket:: AsyncProcessQueue" in "Socket:: QueuePacket"

E: \ ac335 \ AzerothCore wotlk \ src \ server \ apps \ authserver \ Server \ AuthSession. cpp (280,20): Please refer to the first reference to 'Socket:: QueuePacket' in 'AuthSession: SendPacket'

### Operating system

win10

### Custom changes or Modules

 mod_ahbot
 AutoBalance
 mod_LuaEngine
Solocraft.conf
 transmog.conf
 mod-weapon-visual
SkipDKModule
npcbot

**Comment by lemonmomomo** [comment]
Is the warning above normal?

**Comment by Nyeriah** [comment]
Could you please translate/post them in English?

**Comment by lemonmomomo** [comment]
@Nyeriah Your suggestion is correct, thank you!

**Comment by Kitzunu** [comment]
as they are only warnings I will close this issue
