### ISSUE TITLE
BC Instance The Slave Pens + The Steamvault Npc Chat Spam

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1888]
SMALL DESCRIPTION:

In the instance The Steamvault also the Coilfang Slavemaster Chat make spam ID 17805.

Also these guards beat the slaves and spam the chat full with it.
+
Instance The Slave Pens

The Mob Coilfang Slavehandler 17959 says far too often what the whole chat is full of spam.

I found out that he who he beats the slaves with the spell 6754 he should say a text is also okay.
Problem is only that he also says the text he should say at aggro at the same time.

EXPECTED BLIZZLIKE BEHAVIOR:

The Mob Coilfang slave handler should say a text when beating the slaves.

The Mob Coilfang Slavehandler should say a different text when aggro on player.

CURRENT BEHAVIOUR:

In the instance The Steamvault also the Coilfang Slavemaster Chat make spam ID 17805.

The Mob Coilfang Slavehandler ID 17959 spammt a text and the text it should say at aggro when slapping the slaves.
Creature Wastewalker Captive ID18206 Spam also well with me on the server I have adjusted it he stands on 30% chance. In AC DB it is set to 100% normal.

The texts in the database are also sometimes duplicated

Spam Video ^^ https://youtu.be/swBDUb2SVUI

STEPS TO REPRODUCE THE PROBLEM:
Go to the The Slave Pens and look at your chat.
.go c 79359 Instance The Slave Pens
.go c 12591 Instance The Steamvault

BRANCH(ES):
AzerothCore rev. b67ea15+ 2019-05-23 15:26:51 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: NO

**Comment by Voxstrasza** [comment]
Still an issue as of  `221f33b5b7af`
