### ISSUE TITLE
ICC Lich King summoned minions issue

### ISSUE THREAD

**Issue by Joshmash** [azerothcore/azerothcore-wotlk#18882]
### Current Behaviour

[Drudge Ghoul](https://www.wowhead.com/wotlk/npc=37695/drudge-ghoul), [Shambling Horror](https://www.wowhead.com/wotlk/npc=37698/shambling-horror) [Vile Spirit](https://www.wowhead.com/wotlk/npc=37799/vile-spirit) spawns and target closest pet/totem to attack
We can see it on this [video](https://www.youtube.com/watch?v=b7POiVKbwwI&ab_channel=Morningstars) 
Timeline:
First phase:
0:09 - Shambling Horror attacks totem and stops
0:36 - Drudge Ghouls attacks hunter pet
1:09 - Shambling Horror spawn with no pet/totem near him
Third phase:
8:25 - Vile Spirits went down to attack pets/totems

### Expected Blizzlike Behaviour

[Drudge Ghoul](https://www.wowhead.com/wotlk/npc=37695/drudge-ghoul), [Shambling Horror](https://www.wowhead.com/wotlk/npc=37698/shambling-horror) [Vile Spirit](https://www.wowhead.com/wotlk/npc=37799/vile-spirit) should not attack nearest pets/totems when spawns

### Source

[Video](https://www.youtube.com/watch?v=_QcuB8zCpu4&ab_channel=TheAscardia) of the first lich king kill in 2010
Timeline with blizzlike behaviour:
2:08 - Drudge Ghoul spawn and stays still
2:16 - Shambling Horror spawn and stays still
12:33 - Vile Spirits spawns and stays in the air

### Steps to reproduce the problem

1. Go to lich king battle
2. Have pet/totem 
3. Wait for Drudge Ghoul, Shambling Horror or Vile Spirits to spawn
4. See the result

### AC rev. hash/commit

AzerothCore rev. 15323bb9fbe4+ 2024-05-01 07:55:44 +0300 (TS branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80036
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-97-generic
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/azerothcore/data/maps. Total size: 291014951 bytes
vmaps directory located in /root/azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /root/azerothcore/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Ubuntu 22.04.4 LTS

### Custom changes or Modules

List enable modules:
- mod-cfbg
- mod-congrats-on-level
- mod-duel-reset
- mod-globalchat
- mod-individual-xp
- mod-transmog

**Comment by boom8866** [comment]
confirm

**Comment by qwe900** [comment]
seems to be an initialaggro problem

**Comment by qwe900** [comment]
The Summons arent intrested in the unitstarce react passive,  they just spawns and selecting a target which are seems to be first pets, and after that the LichKingStartMovementEvent runs and selecting a random nontankselector .


While Pets and Totems in near of spawn already attacked an down:
=========================================
StartMovementEvent: Executing for summon Drudge Ghoul. Threat list empty: false
-----------------------------------------
StartMovementEvent: Summoner The Lich King has a threat list with 3 entries.
StartMovementEvent: Summoner The Lich King has threat entry for Devgnom with 1000000 threat.
StartMovementEvent: Summoner The Lich King has threat entry for Dasdasd with 3214.3333 threat.
StartMovementEvent: Summoner The Lich King has threat entry for Astralea with 95.48718 threat.
StartMovementEvent: Threat list is not empty for summon Drudge Ghoul.
-----------------------------------------
StartMovementEvent: Summon Drudge Ghoul has a threat list with 3 entries.
StartMovementEvent: Summon Drudge Ghoul has threat entry for Dasdasd with 0 threat.
StartMovementEvent: Summon Drudge Ghoul has threat entry for Astralea with 0 threat.
StartMovementEvent: Summon Drudge Ghoul has threat entry for Devgnom with 0 threat.
StartMovementEvent: Summon Drudge Ghoul selects target Dasdasd from threat list.
StartMovementEvent: Summon Drudge Ghoul is entering zone combat.
=========================================

**Comment by tabooo** [comment]
confirm. still bug

**Comment by tabooo** [comment]
confirm

**Comment by tabooo** [comment]
Also they are too fast.

**Comment by Joshmash** [comment]
> Also they are too fast.

wdym

**Comment by tabooo** [comment]
Still bugged

**Comment by oxbar** [comment]
Is that fixed ? Any video of 2025
