### ISSUE TITLE
[Quest] Bones and Arrows - required item 'Quiver of Dragonbone Arrows ' doesn't drop

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1889]
[Quest] Bones and Arrows - required item 'Quiver of Dragonbone Arrows ' doesn't drop

##### SMALL DESCRIPTION:

Quiver of Dragonbone Arrows ' doesn't drop from the monsters -> Wandering Shadow  &  Shadow Revenant

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quiver of Dragonbone Arrow should drop from 2 mobs -> Wandering Shadow  &  Shadow Revenant

In blizzard servers some actually have loot problems: https://www.wowhead.com/quest=13154/bones-and-arrows#comments

##### CURRENT BEHAVIOUR:

Required item not dropping

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Wintergrasp.
2. get quest Bones and Arrows
3.  Kill Wandering Shadow  &  Shadow Revenant
4. no drop

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Azerothcore rev. ded199d

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Selyria** [comment]
Works for me without any problems have met quest.

You can do the quest only if your faction has conquered Wintergrasp.

If the Horde conquered the city you can't get the questitems as an ally. 

If the Alliance has conquered the city, the Horde cannot receive these questitems.

**Comment by BarbzYHOOL** [comment]
@spinzaku what do you think of the answer above (with proof)?
