### ISSUE TITLE
[Quest] The Ring of Blood

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1890]
**_Problem_**

- _Once you start any quest, NPC's appear as supposed._
- _But, if you decide to abandon quest and take it again, new set will be spawned, and this can be used as much as you wanna which can, at the end, crash server due to number of them._
- _**Problem is with every quest that you can take in Arena.**_

**_Expetations_**

- _Once player leave combat or arena it self, NPC's should despawn._
- _If quest is abandoned, NPC's should despawn as well._

**_How to_**

- _Create character and level up your self to 80._
- _Modify your health cause NPC's hit hard._
- _.tele Nagrand (Move to Arena)_
- _Talk with Gurgthock and start quest._
- _Abandon once they spawn and take quest again._

**_Commit: Up to date / Latest._**

![WoWScrnShot_052619_175336](https://user-images.githubusercontent.com/27079035/58384288-58c1ab80-7fe0-11e9-91a7-5eda9168de98.jpg)

**Comment by FrancescoBorzi** [comment]
@Knindzagxg as I mentioned, can you please include the AC version (commit hash) in **all** your reports ?

**Comment by Knindzagxg** [comment]
It's always up to date mate, latest.
I typed at the end :P

**Comment by Meltie2013** [comment]
@Knindzagxg It's best to put it anyways, easier to track down issues that way. I also doubt its up-to-date every second of the day.

**Comment by BarbzYHOOL** [comment]
yes just in case an issue stay a very long time open

**Comment by Meltie2013** [comment]
Tested on this revision https://github.com/azerothcore/azerothcore-wotlk/commit/68a998c79e9c19de973a9551fecdff2f711e299a. Your welcome @Knindzagxg.

More then likely broken since https://github.com/azerothcore/azerothcore-wotlk/commit/f9bdf86c6d0392ad1d6c91ae1dcf17e4939d252c. Relation https://github.com/azerothcore/azerothcore-wotlk/issues/1056
