### ISSUE TITLE
A Curse Upon Both of Your Clans!

### ISSUE THREAD

**Issue by SenorBozz** [azerothcore/azerothcore-wotlk#18908]
### Current Behaviour

Fetish item works while standing in doorways of the buildings - but if someone else has used the building, the spirit animation remains.  These buildings do not count when you use the fetish, and there's not enough buildings for more than one person to have completed.

### Expected Blizzlike Behaviour

Spirits should clear after use

### Steps to reproduce the problem

1. Stand in doorway of house with a spirit animation already there
2. Use Fetish
3. Observe that it doesn't count

### AC rev. hash/commit

AzerothCore rev. eaa6487fc23a+ 2023-08-27 22:25:22 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 11

**Comment by Kitzunu** [comment]
your core is like 10 months old. try on latest
