### ISSUE TITLE
Ulduar flame_leviathan BUG

### ISSUE THREAD

**Issue by yukijean** [azerothcore/azerothcore-wotlk#18916]
### Current Behaviour

When entering the dungeon, the dialogue Brian Bronze Whisker (33579) should activate the 1st BOSS normal mode instead of the difficult mode, while the dialogue Noganon Gatekeeper (33686) should activate the 1st BOSS difficult mode

### Expected Blizzlike Behaviour

Dialogue Brian Bronze Whisker (33579) should activate the normal mode of Boss 1, while Dialogue Noganon Gatekeeper (33686) should activate the difficult mode of Boss 1

### Steps to reproduce the problem

Dialogue copper whiskers activate difficult mode

### AC rev. hash/commit

AzerothCore rev. 3988e9581d73+ 2024-05-18 10:02:57 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 7 minute(s) 29 second(s)
Update time diff: 1ms. Last 500 diffs summary:
- Mean: 3ms
- Median: 2ms
- Percentiles (95, 99, max): 8ms, 10ms, 18ms
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.78.0
Using CMake version: 3.29.2
Using MySQL version: 80032
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.20348
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Bulid/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Bulid/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Bulid/bin/RelWithDebInfo/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: Skip_DK_Script.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

WINDOWS SEVER 2022

### Custom changes or Modules

AzerothCore rev. 3988e9581d73+ 2024-05-18 10:02:57 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 7 minute(s) 29 second(s)
Update time diff: 1ms. Last 500 diffs summary:
- Mean: 3ms
- Median: 2ms
- Percentiles (95, 99, max): 8ms, 10ms, 18ms
Using SSL version: OpenSSL 1.1.1s  1 Nov 2022 (library: OpenSSL 1.1.1s  1 Nov 2022)
Using Boost version: 1.78.0
Using CMake version: 3.29.2
Using MySQL version: 80032
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.20348
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Bulid/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Bulid/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Bulid/bin/RelWithDebInfo/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: Skip_DK_Script.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

**Comment by sogladev** [comment]
My observation in 10man Ulduar:

Talking to Bran: 2 towers visuals (Thorim/Mimiron) active. FL has 2.3m hp with no tower buffs. All towers are alive. Starting the fight FL gains no auras and does not cast Mimiron's beam that spawns Fire or Thorim yellow beam (Thunder damage)

Talking to the other guy: 
4 towers visuals are active. All towers are alive. Starting the fight FL gains 4 buffs from the towers boosting his hp to 83m. He activates wards aka hardmode abilities 

Conclusion:
talking to Bran activates normal mode correctly but the crystal visuals are wrong 

Mimiron's targetting Crystal
Thorim's targetting Crystal

should not be active after talking to Bran

![talk_to_bran_2_towers_active_4_alive](https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/51850193-d3ab-4478-a687-3cae2293aec0)
