### ISSUE TITLE
A TOO BIG BUG：服务端提供的DBC有问题，中国和台湾的客户端显示任何物品和NPC全部乱码！

### ISSUE THREAD

**Issue by vskllee** [azerothcore/azerothcore-wotlk#1891]
A TOO BIG BUG：服务端提供的DBC有问题，中国和台湾的客户端显示任何物品和NPC全部乱码！

Google Translate：There is a problem with the DBC provided by the server. The clients in China and Taiwan show that all items and NPCs are garbled!

**Comment by FrancescoBorzi** [comment]
@vskllee can you please include your AC version (commit hash) in the report ?

**Comment by vskllee** [comment]
> @vskllee你可以在报告中包含你的AC版本（提交哈希）吗？

最新的版本！昨天刚下载的！

我测试了中国客户端，以及台湾客户端，发现所有的武器衣服药品全部乱码，npc名字也全部乱码。其他界面没问题。我用同样的客户端登录marmane是不会乱码的，但是登录这个会，所以问题出在dbc文件内。如果简体中文和繁体中文乱码，那么日文以及韩语肯定也乱码，也就是只有英文不乱码……这是个巨大的bug
希望能修复下dbc、maps、vmaps、mmaps！非常感谢。

https://mega.nz/#F!Am4DBKCR!o9Qj_xFLfsg4sczqg0xq2A
git clone https://github.com/azerothcore/azerothcore-wotlk.git

Google Translate：The latest version! Just downloaded yesterday!
I tested the Chinese client and the Taiwan client and found that all the weapons and medicines were garbled, and the npc names were all garbled. Other interfaces are fine. I am not garbled to log in to marmane with the same client, but logging in will be, so the problem is in the dbc file. If Simplified Chinese and Traditional Chinese are garbled, then Japanese and Korean must be garbled, that is, only English is not garbled... This is a huge bug.
I hope to fix the next dbc, maps, vmaps, mmaps! thank you very much

The language is unreasonable, the translation may be distorted, forgive me

**Comment by FrancescoBorzi** [comment]
@vskllee "latest version" will make no sense anymore after a while, so please include the exact version that you're using

**Comment by poszer** [comment]
Generate DBC from your Client maybe? @vskllee

**Comment by vskllee** [comment]
> @vskllee “最新版本”将在一段时间后不再有意义，所以请包括您正在使用的确切版本

AzerothCore 2.0.0 released!

**Comment by FrancescoBorzi** [comment]
@vskllee we need the commit hash, for example:

https://github.com/azerothcore/azerothcore-wotlk/commit/68a998c79e9c19de973a9551fecdff2f711e299a

**Comment by vskllee** [comment]
> 可能从您的客户端生成DBC？@vskllee

我尝试自己生成了dbc，但是都是这样的

I tried to generate dbc myself, but it is like this

<img width="682" alt="屏幕快照 2019-05-27 02 03 07" src="https://user-images.githubusercontent.com/23329808/58385482-c216de00-8023-11e9-9c94-3c5467bd98e7.png">

**Comment by poszer** [comment]
I didn't mean to generate database. DBC dude, generate your dbc (data) from your game client

**Comment by vskllee** [comment]
> I didn't mean to generate database. DBC dude, generate your dbc (data) from your game client

我今天从Windows那里提取里dbc，但是进去后还是乱码。这个问题不在数据上。azerothcore-wotlk的编码是不是缺少中文字库

I extracted the dbc from Windows today, but it was still garbled after entering. This problem is not on the data. Is the encoding of azerothcore-wotlk missing the Chinese font library?

**Comment by poszer** [comment]
> > I didn't mean to generate database. DBC dude, generate your dbc (data) from your game client
> 
> 我今天从Windows那里提取里dbc，但是进去后还是乱码。这个问题不在数据上。azerothcore-wotlk的编码是不是缺少中文字库
> 
> I extracted the dbc from Windows today, but it was still garbled after entering. This problem is not on the data. Is the encoding of azerothcore-wotlk missing the Chinese font library?

From your Game dude, put extractor where is your game. And run script to generate your DBC files from client >.<
@pklloveyou Can you help him and explain ?

**Comment by vskllee** [comment]
> > > I didn't mean to generate database. DBC dude, generate your dbc (data) from your game client
> > 
> > 
> > 我今天从Windows那里提取里dbc，但是进去后还是乱码。这个问题不在数据上。azerothcore-wotlk的编码是不是缺少中文字库
> > I extracted the dbc from Windows today, but it was still garbled after entering. This problem is not on the data. Is the encoding of azerothcore-wotlk missing the Chinese font library?
> 
> From your Game dude, put extractor where is your game. And run script to generate your DBC files from client >.<
> @pklloveyou Can you help him and explain ?

我想我找到问题的根源了！参考这个链接：https://www.cnblogs.com/z-belief/p/6148463.html
docker的编码问题！你谷歌翻译下上面的链接就明白了。
现在我要试着去解决

I think I found the root of the problem! Refer to this link: https://www.cnblogs.com/z-belief/p/6148463.html
Docker coding problem! You can understand the link above in Google Translate.
Now I have to try to solve

**Comment by BarbzYHOOL** [comment]
@a4501150 can you give him some advice?

Or maybe it's only a docker issue

**Comment by vskllee** [comment]
I can't fix this problem and ask for help! How can I modify Docker's MYSQL encoding to UTF-8? Mac version Docker

**Comment by a4501150** [comment]
Hi, you need to extract your own DBC from Chinese Version of WoW Client using tools available in AC.

**Comment by a4501150** [comment]
Ok, after reading up, if it not because of DBC extracting issue, it may because of docker. But why not try to compile and run it without docker? @vskllee

**Comment by vskllee** [comment]
> Ok, after reading up, if it not because of DBC extracting issue, it may because of docker. But why not try to compile and run it without docker? @vskllee

I need to run on mac, so I have to use docker

**Comment by a4501150** [comment]
> > Ok, after reading up, if it not because of DBC extracting issue, it may because of docker. But why not try to compile and run it without docker? @vskllee
> 
> I need to run on mac, so I have to use docker

I remember you can compile on mac without docker, using Cmake

**Comment by icecatbing** [comment]
Debian 8 & 9 没有问题。Mac没有试过，如果不使用Docker应该和Debian一样，非常容易部署。

**Comment by yolinlin** [comment]
活捉国人

**Comment by vskllee** [comment]
> 活捉国人

别活捉，看看mac能解决不。。。

**Comment by jsRuner** [comment]
me too.  how to fix @vskllee
