### ISSUE TITLE
BC Instance The Underbog Many Creatures Missing and Waypoints

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1892]
SMALL DESCRIPTION:

The Underbog is missing a massive amount of mobs and 
Movements (waypoints) there are wrong mob groups put together or are not even there.

Swamplord Musel'ek does not work properly

EXPECTED BLIZZLIKE BEHAVIOR:

It's a cata video, but the instance never changed.
https://www.youtube.com/watch?v=i2sHhYo8TlU 

Well described here under Strategy 
https://wowwiki.fandom.com/wiki/Swamplord_Musel%27ek

**Swamplord Musel'ek**

Clear the Underbog Lord that patrols near Musel'ek before engaging the boss. He can crit for in excess of 9.5k on mail armour. He will aggro when you attack the boss, and you will wipe unless spectacularly geared.

This fight is similar to the Illyanna Ravenoak encounter in Dire Maul and can be completed with a single tank. The tank first attacks Claw for a few seconds to build up threat before switching to Musel'ek. Once the tank has built up enough threat, the rest of the party can attack and down him quite quickly. Musel'ek will occasionally freeze the whole group and take some distance so he can shoot. It is important for the tank to get back into the hunter's melee range immediately. Once the hunter is dead the group can focus on Claw, who will turn friendly at 20% health and expose himself as Windcaller Claw. Alternatively, the bear can be burned to 20% first, removing it from the fight, and then the boss engaged. The primary concern appears to be healing interruption and proper double-tanking.
CURRENT BEHAVIOUR:
**Swamplord Musel'ek**

Boss Swamplord Musel'ek is doing his thing pretty well. But if you would knock the bear down first he should withdraw from the fight he doesn't spawn again.

**Instanze mob groups and waypoints** 

Many mob groups are missing the best video times look falls then so into your face ^^

A lot of waypoints are missing a lot of mobs just standing around.

Mob groups are wrongly arranged 1-2 groups

Youtube AC https://youtu.be/6q3FTwhhE3Y Not my best video at best myself also make an insight

STEPS TO REPRODUCE THE PROBLEM:
Go to the instance of the Underbog.

.tele Underbog

Watch the video and look at the instance 

BRANCH(ES):

AzerothCore rev. b67ea15+ 2019-05-23 15:26:51 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: NO

**Comment by Voxstrasza** [comment]
Still an issue as of `9facd81e54ac`
