### ISSUE TITLE
After multiple Arenas are completed, the server's CPU usage increases by a factor of two to three

### ISSUE THREAD

**Issue by PkllonG** [azerothcore/azerothcore-wotlk#18921]
### Current Behaviour

After multiple Arenas are completed, the server's CPU usage increases by a factor of two to three

### Expected Blizzlike Behaviour

After the arena is completed, the CPU usage should not increase

### Steps to reproduce the problem

Take part in the arena and observe the CPU usage

### AC rev. hash/commit

440cea3

### Operating system

Windows Server 2019 x64

**Comment by PkllonG** [comment]
The server didn't uninstall them after the arena was done?

**Comment by sudlud** [comment]
can you please provide reproduction steps, preferrebly using gm commands?
thanks.

**Comment by sudlud** [comment]
alright i'm no trying it this way
```
lvl 80 char
.debug arena
.go c id 102693
join 2v2 skirmish
```

**Comment by sudlud** [comment]
I can't reproduce this on c13c1b28e

i ran 3 arenas as described above with 2 players and couldn't notice any difference in cpu usage.

Can you please provide exact steps on how to reproduce this on a clean AC install?

Thanks.

**Comment by PkllonG** [comment]
Today in my server, players have played more than 100 arenas, and there are no players in the arena at the moment, and the CPU usage has been 2~3 times that of usual. 
There have been anomalies like this a long time ago, and it wasn't until today that I confirmed that it was a bug in the arena.

**Comment by sudlud** [comment]
Alright, then I need to figure out how I can run 100 arenas easily after server start. I'll try to reproduce this again later today

**Comment by PkllonG** [comment]
Start recording
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/a67d8b03-875e-45c0-a2b0-6cc8cdd59c90)

**Comment by PkllonG** [comment]
I used it for testing convenience https://github.com/azerothcore/mod-1v1-arena

**Comment by sudlud** [comment]
> I used it for testing convenience https://github.com/azerothcore/mod-1v1-arena

alright, `.debug arena` should have the same effect for testing

**Comment by PkllonG** [comment]
I played 60 games and probably it didn't have anything to do with it, I'll close it first. I'll turn it on again if there's any progress

**Comment by sudlud** [comment]
Thanks for checking, maybe it's Battlegrounds instead?

**Comment by PkllonG** [comment]
My idea is to reboot the server and see what happens to the CPU tomorrow
