### ISSUE TITLE
(quest) Magic Carpet Ride - Blank Quest

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1893]
(quest) Magic Carpet Ride - Blank Quest
Related

##### SMALL DESCRIPTION:

Quest is blank or incomplete

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should let me accept quest

##### CURRENT BEHAVIOUR:

Can't accept quest. already tried abandoning and relog.
Check screenshot
![received_431383187700917](https://user-images.githubusercontent.com/18629476/58398902-02f50e00-8089-11e9-82b0-855012f89ed1.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go and talk to Gorge NPC
2. Try to accept quest

##### EXTRA NOTES:

Tried with 3 people. only one got to get the quest after going to another zone and relogging in

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Azerothcore rev. ded199d+

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
It's not blank quest dude. You have to complete it first - Read what Quest said: **_''Talk to Yanni at Warsong Hold to arrange safe travel to the coast. Speak to Gorge the Corpsegrinder once you arrive at Garrosh's Landing.''_** :roll_eyes: 

![complete it](https://user-images.githubusercontent.com/41213210/58517781-ebaf4100-81ac-11e9-98c0-7913b399b978.png)

![completedone](https://user-images.githubusercontent.com/41213210/58517796-f8cc3000-81ac-11e9-9f73-0fc07d585a57.png)

Closing this issue
