### ISSUE TITLE
Whose problem is this

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/azerothcore-wotlk#18942]
### Current Behaviour

 I used the PLAYERBOT mod to create 4000 NPCs. The server's latency is very high and it's very laggy. I noticed that the worldserver process only utilizes one CPU, while the others remain idle. Why is this? Below is my configuration.
Network.Threads = 4
ThreadPool = 4
UseProcessors = 4
MapUpdate.Threads = 8

### Expected Blizzlike Behaviour

not delay

### Steps to reproduce the problem

1.install playerbot mod 
2.create 4000 npc

### AC rev. hash/commit

last

### Operating system

ubuntu22.04.4

### Custom changes or Modules

playerbot mod

**Comment by trickerer** [comment]
> UseProcessors = 4

You make worldserver use a single core with your own hands.
Open worldserver.conf, scroll down to `UseProcessors` and carefully read its description.
