### ISSUE TITLE
authserver.exe and worldserver.exe is not run

### ISSUE THREAD

**Issue by zhaoweizw2000** [azerothcore/azerothcore-wotlk#18955]
i Compiled AzerothCore by windows10 system. In the windows10 system, 
authserver.exe and worldserver.exe is ok. but ,copy the application to windows11 system,authserver.exe and worldserver.exe is not run, and no logs putout.
authserver.exe run of image.
<img width="1072" alt="222222" src="https://github.com/azerothcore/azerothcore-wotlk/assets/9583090/d14fcbf7-c6ad-49f8-a281-4ff0d2a31b81">
worldserver.exe run of image.
<img width="1069" alt="111111111" src="https://github.com/azerothcore/azerothcore-wotlk/assets/9583090/6fa6ffbc-e7c5-41c2-ba71-98d0261d830e">

**Comment by Nyeriah** [comment]
Could be anything to do with your system, not a core issue therefore closing this

**Comment by zhaoweizw2000** [comment]
it not have logs.
what does it have command to create logs?

**Comment by zhaoweizw2000** [comment]
this question is over. my windows11 system is bad.
