### ISSUE TITLE
Issue when training faster riding and being mounted at same time

### ISSUE THREAD

**Issue by rasm685p** [azerothcore/azerothcore-wotlk#1896]
_Issue when training faster riding and being mounted at same time_

**SMALL DESCRIPTION:**
I was mounted on the blizzbear and wanted to train to a faster riding speed but when I trained, i got default walking speed. Everytime I mount the blizzbear it's stuck at the same speed I walk at. When mounting another mount it works fine. I think I just bugged the mount but this issue should happen for every mount (Only blizzbear is tested)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
It should give me 100% speed not less

**CURRENT BEHAVIOUR:**
Gives me walking speed when training faster riding. I tried relog etc.

**STEPS TO REPRODUCE THE PROBLEM:**
Go to Thrallmar outland and go to mount trainer. Go on your mount (I was using blizzbear) and learn all of the other riding/flying skills. (I only had the 60% speed at the time.)
EXTRA NOTES:
Tried with multiple accounts and got the same bug twice.

**BRANCH(ES):**
master

**COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/0b18d4c3d902647a06a79b6c643d5de307c9cc5a

**OPERATING SYSTEM:**
Ubuntu 16.04

**MODULES:**
Mod-vas-autobalance

**Comment by poszer** [comment]
100% is max speed allowed for this mount? @rasm685p

**Comment by rasm685p** [comment]
@poszer I don't know. I don't play wow that much but I know that it isn't supposed to go from 60% to walking speed.
