### ISSUE TITLE
Program crash .in windows11 , report error  code: 0xc0000005，error modle name: MSVCP140.dll when authserver.exe is running

### ISSUE THREAD

**Issue by zhaoweizw2000** [azerothcore/azerothcore-wotlk#18961]
authserver.exe Program crash

Version Windows 11 Professional 23H2 
Operating system version 22631.2861
not installed vs2022

error description:
Wrong application name: authserverexe, version: 0.0.0.0, timestamp: 0x66505217 
Error module name: MSVCP140.DLL, version: 14.36.32532.0, timestamp: 0x04a30cf0 
Exception code: 0xc000005 
Error offset: 0x000000000012f58 
Error process ID: 0x0x2EAC 
Error application startup time: 0x0x1DAB0AADDC368E7 
Error application path: D: \ wowServer playerbots \ core \ authserverexe 
Error module path: C: \ Windows \ System32 \ MSVCP140.DLL 
Report ID: 1d0246c1-4be4-4aaf-acad-3f10db814544 
Error package full name: 
Error package relative to application ID: 

I compile AzerothCore in windows 10 system,  the version of MSVCP140.dll is 14.40, with installed vs 2022, running authserverexe is ok.
but I have another windows11 compute, the version of MSVCP140.dll is 14.38,with installed vs 2022, running authserverexe is ok.

How to handle this issue？！！！！

**Comment by PkllonG** [comment]
``` wowServer playerbots ``` ???

**Comment by zhaoweizw2000** [comment]
yse, azerothcore playerbots.



















在 2024-05-28 12:54:10，"天鹿" ***@***.***> 写道：

wowServer playerbots ???
