### ISSUE TITLE
(quest) Mending Fences 

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1897]
(quest) Mending Fences 

##### SMALL DESCRIPTION:

Can't target Fjorn with rock

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Can target Fjorn with rock just like other giants

##### CURRENT BEHAVIOUR:

Can't target Fjorn with rock

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get Mending Quest Npc
2. Try to use rock on fjorn

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Azerothcore rev. ded199d+

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by wizzymore** [comment]
"STEPS TO REPRODUCE THE PROBLEM:"
I suggect you to use
.quest add QUEST_ID
And a .tele near the quest giver or the entry of the Fjorn NPC
It will be easyer for testers to check if the problem exists

**Comment by poszer** [comment]
Like the infos said: You are able to throw it just on Stormforged Iron Giant not on Fjorn

_Info:_
https://wotlk.evowow.com/?item=41505
_Use: Hurls a Granite Boulder at a targeted **Stormforged Iron Giant**, summoning a group of Earthen Ironbane dwarves to assist you in combat. (10 seconds cooldown)_

Closing this issue

**Comment by spinzaku** [comment]
Official Retail wow you can target Fjorn. look at video: https://youtu.be/Yvp-imxsS7c?t=256

**Comment by poszer** [comment]
> Official Retail wow you can target Fjorn. look at video: https://youtu.be/Yvp-imxsS7c?t=256

I already write you, why it's closed. Read my comment

**Comment by spinzaku** [comment]
but retail wow even have video showing u can target fjorn. https://youtu.be/Yvp-imxsS7c?t=256 

.. but ok

**Comment by Stoabrogga** [comment]
@poszer 
I think @spinzaku is right here:
https://www.wowhead.com/quest=12915/mending-fences#comments:id=748604

I also remember using it against Fjorn himself at the time.

**Comment by Selyria** [comment]
Yes I agree I've looked a little bit so the one with the stone is right the one who summoned a helper the one that helps

Good to read here

https://wowwiki.fandom.com/wiki/Quest:Mending_Fences
