### ISSUE TITLE
Feature: Can the default call to the worldserver.conf.dist configuration file be made during core startup?

### ISSUE THREAD

**Issue by 1825679767** [azerothcore/azerothcore-wotlk#18987]
### Describe your feature request or suggestion in detail

It is hoped that the settings can be modified to allow default reading of the dist parameters, and only the modified parameters need to be filled in the conf. If there are parameters in the conf, take the conf as the standard, and if there are no parameters in the conf, read the parameters of the dist file.
In this way, the conf file will be filled with the parameters you need to modify, and it will be very convenient to continue adjusting next time.

### Describe a possible solution to your feature or suggestion in detail

It is hoped that the settings can be modified to allow default reading of the dist parameters, and only the modified parameters need to be filled in the conf. If there are parameters in the conf, take the conf as the standard, and if there are no parameters in the conf, read the parameters of the dist file.
In this way, the conf file will be filled with the parameters you need to modify, and it will be very convenient to continue adjusting next time.

### Additional context

Before the core starts now, it is necessary to copy the dist file and change the suffix to conf, and the conf file must contain all the same parameters as the dist file to start normally; otherwise, the core will report an error.
However, there are many parameters, and after modification, you may forget what you have changed next time, which is very inconvenient.

**Comment by sudlud** [comment]
as far as I can tell the `.dist` holds the default values and acts as a template for the `.conf`.

some settings must be present in the `.conf` file, but for many settings if they are not present in the `.conf`, the core will load their default values that are defined in the source code (!), which should usually be equal to the default value present in the `.dist`

**Comment by 1825679767** [comment]
> 据我所知，它保留了默认值并充当 .`.dist``.conf`
> 
> 某些设置必须存在于文件中，但对于许多设置，如果它们不存在，则内核将加载其在源代码 （！） 中定义的默认值，该值通常应等于`.conf``.conf``.dist`

Yes, but if the conf file is missing parameters, the core will report an error upon startup. Therefore, I hope to adjust to prioritize reading parameters from the conf file. If a parameter is not present in the conf, then reading the parameters from dist will suffice. This way, conf only needs to contain the parameters one wishes to modify, which will make it appear less bloated.

**Comment by 1825679767** [comment]
> as far as I can tell the holds the default values and acts as a template for the .`.dist``.conf`
> 
> some settings must be present in the file, but for many settings if they are not present in the , the core will load their default values that are defined in the source code (!), which should usually be equal to the default value present in the `.conf``.conf``.dist`

Yes, but if the conf file is missing parameters, the core will report an error upon startup. Therefore, I hope to adjust to prioritize reading parameters from the conf file. If a parameter is not present in the conf, then reading the parameters from dist will suffice. This way, conf only needs to contain the parameters one wishes to modify, which will make it appear less bloated.

**Comment by Kitzunu** [comment]
It will just throw a warning that there is no value in conf file. You don't need to have them all in the conf file (Just a few mandatory like database credentials). Rest is read from the core

**Comment by Kitzunu** [comment]
the .dist is just a distribution file and not intended to be read

**Comment by 1825679767** [comment]
> the .dist is just a distribution file and not intended to be read
> 
> Here's some reading on how config files work https://www.azerothcore.org/wiki/how-to-work-with-conf-files https://www.azerothcore.org/wiki/config-overrides-with-env-var

But if the conf file is missing any parameter, the core will report an error in red when it starts up. How can I cancel these prompts?

**Comment by 1825679767** [comment]
![Uploading f77648fc-70d5-4369-8321-3966c942557e.png…]()

After I filled in the following parameters in the conf configuration file, it was impossible to start.
[worldserver]
LoginDatabaseInfo     = "127.0.0.1;3306;root;root;azerothcore_test_auth"
WorldDatabaseInfo     = "127.0.0.1;3306;root;root;azerothcore_test_world"
CharacterDatabaseInfo = "127.0.0.1;3306;root;root;azerothcore_test_chars"

**Comment by Kitzunu** [comment]
> But if the conf file is missing any parameter, the core will report an error in red when it starts up.

Correct, it is just telling you that the configs are missing. They are moreso warnings over errors, because an error would halt the server.

> After I filled in the following parameters in the conf configuration file, it was impossible to start.

Because there are more mandatory settings....

To make it easy I would say most settings, not all, in `SERVER SYSTEM SETTINGS` should be present in the conf file. At least `DATABASE & CONNECTIONS` `DIRECTORIES` `AUTOUPDATER`

 while `GAME SETTINGS` don't.

**Comment by 1825679767** [comment]
> > But if the conf file is missing any parameter, the core will report an error in red when it starts up.
> 
> Correct, it is just telling you that the configs are missing. They are moreso warnings over errors, because an error would halt the server.
> 
> > After I filled in the following parameters in the conf configuration file, it was impossible to start.
> 
> Because there are more mandatory settings....
> 
> To make it easy I would say most settings, not all, in should be present in the conf file. At least `SERVER SYSTEM SETTINGS``DATABASE & CONNECTIONS` `DIRECTORIES` `AUTOUPDATER`
> 
> while don't.`GAME SETTINGS`

Excuse me, how should I modify the code if I want to cancel the red alert due to the lack of the GAME SETTINGS section?
