### ISSUE TITLE
Quest_template [RewardXPMultiplier]

### ISSUE THREAD

**Issue by Drazroz** [azerothcore/azerothcore-wotlk#1898]
I don't know if there is a option that do it, but i was looking for a field like that at db, and don't have by now [AzerothCore rev. 2bcedc2859e7], it would be greatful if enable that field at the table of quest_template or set it somewhere visible

**Comment by wizzymore** [comment]
As you can see even in TC, https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130261/quest+template#quest_template-RewardXPMultiplier
The RewardXPMultiplier is there but is not documented and from what i know with my experience with trinity, in 3.3.5 there was no xpmultiplier if i am not wrong, maybe this thing comes from newer expansions. Why don't you just modify the reward dificulty?

**Comment by Drazroz** [comment]
Because for what i wan't to do isn't enougth, i need A LARGE AMOUNT of Xp (With a specify quest you can up 10 levels +/-), and the limit of dificulty is low so... But ok, thanks btw

**Comment by Voxstrasza** [comment]
You can modify quest experience from here in worldserver.conf:

```
#
#    Rate.XP.Kill
#    Rate.XP.Quest
#    Rate.XP.Explore
#        Description: Experience rates (outside battleground)
#        Default:     1 - (Rate.XP.Kill)
#                     1 - (Rate.XP.Quest)
#                     1 - (Rate.XP.Explore)

Rate.XP.Kill    = 2
Rate.XP.Quest   = 2
Rate.XP.Explore = 2

```

If you want to increase experience for an individual quest, Keira3 has an option in quest_template for easy access.

Since this has been open since May 2019 and no replies since, I will be closing it - if the above options don't help you feel free to open a new suggestion.

**Comment by Helias** [comment]
FYI: we have a field `RewardXPDifficulty` in quest_template which change the Quest XP based on the related level.
