### ISSUE TITLE
Delete AzerothCore motd

### ISSUE THREAD

**Issue by fallen26** [azerothcore/azerothcore-wotlk#1899]
How to delete This server runs on azerothcore?

https://ibb.co/Wkjyx5R

**Comment by Helias** [comment]
Why would you do that?
We work for free to make this server what it is, you can't leave the credits?

**Comment by Viste** [comment]
it's at least not pretty. Well and under license it is desirable to leave copyright of the author
keep calm and play.
or you can write your own core )) or use Trinity they copy easy to remove )))) but its not pretty to.

**Comment by BarbzYHOOL** [comment]
bastard

**Comment by fmrmx** [comment]
is an easy work, figure it our yoursdelf, if you cant delete a small piece of code, then you do not deserve to have a game server.
