### ISSUE TITLE
Reinforced Fel Iron Chest Contains No Loot

### ISSUE THREAD

**Issue by justurn** [azerothcore/azerothcore-wotlk#18999]
### Current Behaviour

Reinforced Fel Iron Chest Contains No Loot, checked in Keira and there is no loot table associated with the chest.

GOBJECT 185168

Correct reference loot table exists but is not assigned to the chest.

REFERENCE LOOT 12003

### Expected Blizzlike Behaviour

Reinforced Fel Iron Chest should contain loot, correct reference loot table exists and assigned to the chest.

REFERENCE LOOT 12003

### Source

https://www.wowhead.com/tbc/object=185168/reinforced-fel-iron-chest

### Steps to reproduce the problem

1.  Teleport to Hellfire Ramparts
2. Slay Nazan and Vazruden the Herald
3. Open Chest

### Extra Notes

This query solves the problem.

DELETE FROM `gameobject_loot_template` WHERE (`Entry` = 21762) AND (`Item` IN (0));
INSERT INTO `gameobject_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(21762, 0, 12003, 100, 0, 1, 0, 1, 1, '');

### AC rev. hash/commit

766ce24367e7

### Operating system

Windows

**Comment by avarishd** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/9ff4bcf3-8803-4d1c-8f36-e6304b2d38a0)

Also that query is wrong.
