### ISSUE TITLE
The server has a startup problem

### ISSUE THREAD

**Issue by snowcpu** [azerothcore/azerothcore-wotlk#18993]
### Current Behaviour

![ac 2024-06-02_12-35-57](https://github.com/azerothcore/azerothcore-wotlk/assets/171467655/dcc04651-86fc-4b4c-8596-e73b7c172e67)

### Expected Blizzlike Behaviour

please repair problems.

### Steps to reproduce the problem

startup server.

### AC rev. hash/commit

35de41b45f425759efdeb97af1731490882109f1

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
A clean core cant have startup errors, you did something to the table
