### ISSUE TITLE
Help needed：clients often freeze

### ISSUE THREAD

**Issue by zbhcn** [azerothcore/azerothcore-wotlk#19013]
### Current Behaviour

Help needed: During raids or when a large number of players are on the same map, most of the team members' clients often freeze. After forcibly closing the client, if players try to log in again within approximately 3 minutes, the client still freezes. It is only after waiting for 3 minutes that they can log in normally. Does anyone know what might be causing this issue?

### Expected Blizzlike Behaviour

It is only after waiting for 3 minutes that they can log in normally

### Source

official source no change ,Just adding some models

### Steps to reproduce the problem

Appears irregularly and becomes more frequent as the server runs for a longer period of time

### AC rev. hash/commit

Using SSL version: OpenSSL 3.0.0 7 sep 2021 (library: OpenSSL 3.0.12 24 Oct 2023)
Using Boost version: 1.83.0
Using CMake version: 3.24.3
Using MySQL version: 80036
Found MySQL Executable: F:/MYSQL/bin/mysqld.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014339 bytes
vmaps directory located in ./data/vmaps. Total size: 658130553 bytes
mmaps directory located in ./data/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-1v1-arena
- mod-anticheat
- mod-autobalance
- mod-cdkey
- mod-cfbg
- mod-eluna

### Operating system

windows 2019 standard

### Custom changes or Modules

- mod-1v1-arena
- mod-anticheat
- mod-autobalance
- mod-cdkey
- mod-cfbg
- mod-eluna

**Comment by sudlud** [comment]
Please provide the output of

.server debug

**Comment by zbhcn** [comment]
> Please provide the output of
> 
> .server debug

Using SSL version: OpenSSL 3.0.0 7 sep 2021 (library: OpenSSL 3.0.12 24 Oct 2023)
Using Boost version: 1.83.0
Using CMake version: 3.24.3
Using MySQL version: 80036
Found MySQL Executable: F:/MYSQL/bin/mysqld.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014339 bytes
vmaps directory located in ./data/vmaps. Total size: 658130553 bytes
mmaps directory located in ./data/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-1v1-arena
- mod-anticheat
- mod-autobalance
- mod-cdkey
- mod-cfbg
- mod-eluna

**Comment by heyitsbench** [comment]
Provide the parts above the SSL line.

**Comment by zbhcn** [comment]
> Provide the parts above the SSL line.

AC> .server debug
AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static)
Connected players: 115. Characters in world: 112.
Connection peak: 187.
服务器运行时间: 13 hour(s) 45 minute(s) 55 second(s)
Update time diff: 8ms. Last 500 diffs summary:
- Mean: 11ms
- Median: 9ms
- Percentiles (95, 99, max): 24ms, 27ms, 32ms

**Comment by sudlud** [comment]
Your revision hash is wrong, can you please retry on clean AC on latest master. Thanks!
