### ISSUE TITLE
Caliph Scorpidsting is nowhere to be found for many updates now

### ISSUE THREAD

**Issue by PerryCS** [azerothcore/azerothcore-wotlk#19029]
### Current Behaviour

Can't find him!  Hours killing everything in Tanaris.  Rebooting.  Trying again after an update... been a few months now.  I even updated.  Still unable to find him.

### Expected Blizzlike Behaviour

He can be found :)  I've done this quest approx 40 times over the years :)

### Steps to reproduce the problem

Get Quest WANTED: Caliph Scorpidsting
Try and find him.  Never anywhere.

### AC rev. hash/commit

 AzerothCore rev. e4b46863e807 2024-05-12 21:53:41 +0000 (HEAD branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04.3 LTS

### Custom changes or Modules

None

**Comment by Nyeriah** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/47818697/9f7417e1-10c3-47a5-be06-e741202a7496)

Gotta look harder, he is just fine, he wanders

**Comment by PerryCS** [comment]
I just ran around as a GM for 5 min and found him wandering... sorry to waste your time... :(  I turned off GM and he's still there.  Weird I couldn't find him after hours of wandering around killing everything in sight on more than 1 occasion...
