### ISSUE TITLE
Crash due to Guild Bank Delete

### ISSUE THREAD

**Issue by jacatinelord** [azerothcore/azerothcore-wotlk#19023]
### Current Behaviour

I hosted a server with approx 10-15 ppl, and didnt know how this occured. but it seems the crash was caused by some Guild Bank Deletion?
the crashlog: https://gist.github.com/jacatinelord/3a097125eae8b28ee9e763a517f95300

### Expected Blizzlike Behaviour

-

### Steps to reproduce the problem

-

### AC rev. hash/commit

AzerothCore rev. ef61b95c28bc 2024-06-06 01:22:06 +0800

### Operating system

Win Server 2016

### Custom changes or Modules

i am currently on AzerothCore with npcbot

**Comment by Kitzunu** [comment]
Post the output of .server debug

and try on a clean version of AC. ef61b95c28bc is not a rev that exists

**Comment by jacatinelord** [comment]
Sorry, the .server debug its here:
AzerothCore rev. ef61b95c28bc 2024-06-06 01:22:06 +0800 (Win64, RelWithDebInfo, Static)
Connected players: 13. Characters in world: 12.
Connection peak: 14.
Server uptime: 43 minute(s) 44 second(s)
Update time diff: 3ms. Last 500 diffs summary:
- Mean: 22ms
- Median: 3ms
- Percentiles (95, 99, max): 72ms, 80ms, 165ms
Using SSL version: OpenSSL 3.3.0 9 Apr 2024 (library: OpenSSL 3.2.1 30 Jan 2024)
Using Boost version: 1.81.0
Using CMake version: 3.29.2
Using MySQL version: 80034
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in data/maps. Total size: 291014951 bytes
vmaps directory located in data/vmaps. Total size: 658130721 bytes
mmaps directory located in data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS frFR deDE esES ruRU
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: 2024_05_29_00_command.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- BreakingNewsOverride
- mod-1v1-arena
- mod-ah-bot
- mod-anticheat
- mod-autobalance
- mod-better-item-reloading
- mod-eluna
- mod-guildhouse
- mod-individual-xp
- mod-npc-all-mounts
- mod-npc-buffer
- mod-npc-free-professions
- mod-npc-gambler
- mod-npc-services
- mod-premium
- mod-pvp-titles
- mod-rdf-expansion
- mod-reagent-bank
- mod-solo-lfg
- mod-transmog
- mod-weekendbonus

and i used the azerothcore with npc bot one, i tried to make a report there once about some crash but it redirect me to the main repo, so i try to post it here.

**Comment by Kitzunu** [comment]
and how do I reproduce the issue?
