### ISSUE TITLE
Failed to start worldserver.service: Unit worldserver.service not found.

### ISSUE THREAD

**Issue by rkhale01** [azerothcore/azerothcore-wotlk#19033]
I thought i had followed all the directions on this page (https://www.azerothcore.org/wiki/linux-core-installation), however when i try to start the service with sudo service worldserver start per the instructions i get the title message "Failed to start worldserver.service: Unit worldserver.service not found." Which is odd because i can SEE it as a file within the system i am running to hopefully start a server for some buddies. This is as far as i've gotten. I tried to follow each step and have done each of them multiple times. The system is up to date, all of the lines in the instructions have been run twice where i can to insure that each was done properly per the instructions. All of the files up to that point seem to be there. I am connected via SSH & Remote Desktop to a debian system. What have i missed? I am /somewhat/ new to linux, but i've used it off and on again throughout the years for various purposes. 

-I get this error even if i point the terminal to the file folder CONTAINING worldserver.service. i searched to see if anyone else has had this issue but i have not seen anything - if i have missed it please link me and i will search from there. 

My primary computer is Linux Mint most recent stable build
"Server"/computer with the azerothcore files is debian(most recent stable)

any help is appreciated, please be kind - been really busy with work and school but a lot of my freetime has been spent with this issue recently.

**Comment by Kitzunu** [comment]
Not the place to ask questions. Go to discord
