### ISSUE TITLE
Zulaman instance incorrect door and creature alarm.

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#19048]
### Current Behaviour

The database is automatically generated after compiling with the current source code, checking the zulaman door, and found that the doors 186303 186306, etc. are missing.
and that the definition of the   GO_GATE_ZULJIN = 186304  It should be wrong, it's 186306, also the front door of boss 4 is missing, I didn't find the right door id.
In addition, even if you fix GO_GATE_ZULJIN , the order of the door is not correct, because the additional definition of DATA_GONGEVENT = 0, so the actual the boss count is one more, in most of instance_zulaman.cpp, >= should be changed to > to be correct, for example, the following code can be changed to > to be executed correctly.

        void CheckInstanceStatus()
      {
         if (BossKilled > DATA_HALAZZIEVENT)      //chang >= to > because first door gate is an ext boss
                HandleGameObject(HexLordGateGUID, true);
         if (BossKilled > DATA_HEXLORDEVENT)
                HandleGameObject(ZulJinGateGUID, true); 
        }

Similarly, there are a lot of creature will go and bang on the drum to warn when player come near, and the current behaviour is just to bang the air and then fight the player directly without summoning other creature.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

I use myself fork from AZ and NPCbots.
https://github.com/kissingers/acore-wow/commits/mynpcbots/

AzerothCore rev. bd56f90d4c13 2024-06-08 13:31:59 +0800 (mynpcbots branch) (Unix, RelWithDebInfo, Static)
Connected players: 68. Characters in world: 67.
Connection peak: 68.
服务器运行时间: 9 hour(s) 49 minute(s) 23 second(s)
Update time diff: 10ms. Last 500 diffs summary:
- Mean: 11ms
- Median: 10ms
- Percentiles (95, 99, max): 18ms, 18ms, 23ms

### Operating system

debian12 x64

**Comment by kissingers** [comment]
https://github.com/kissingers/acore-wow/commit/bd56f90d4c13fe1ee5e9c5e1dc3c576e6eb82414

Here is myself fix, just fix some of the door problem, with flow add door object.

INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES (2135586, 186303, 568, 0, 0, 1, 1, 305.908, 1112.09, 9.9566, 3.14159, 0, 0, -1, 0, 180, 255, 1, '', 0, NULL);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`, `Comment`) VALUES (2135587, 186306, 568, 0, 0, 1, 1, 123.256, 914.421, 34.1441, -1.57952, 0, 0, -0.710185, 0.704015, 180, 255, 1, '', 0, NULL);

**Comment by kissingers** [comment]
186304 it seem might the front door of boss 4

**Comment by kissingers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19010

**Comment by kissingers** [comment]
Also sometimes the BossKilled not work right, because the if (data == DONE)  and BossKilled++ will do every call. 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/a61643d7-751c-4c4d-9f01-2a6b1f42f6ac)

So change to the right 4 boss if (data == DONE), other call will not do BossKilled++
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/6f11088a-54cf-4e80-bbee-a8ef7ab84191)

this is my way fix
https://github.com/kissingers/acore-wow/commit/7099d6a28202f4178ead35abd19e2007755b3094

**Comment by Nyeriah** [comment]
Doors were fixed already, added and scripted
