### ISSUE TITLE
When using the module, compiling it into a dynamic link library version failed.

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/azerothcore-wotlk#19053]
### Current Behaviour

According to the compilation documentation, I configured the environment and compiled. When there is no module, the dynamic library compilation passes normally, but when a module is used, it fails. The modules are the latest cloned from the AzerothCore organization.

### Expected Blizzlike Behaviour

build pass with module 

### Steps to reproduce the problem

cmake configure 
cmake generator 
cmake open project
relwithdebuginfo and x64 
vs2022 

### AC rev. hash/commit

[da8d42c](https://github.com/azerothcore/azerothcore-wotlk/commit/da8d42c72cf819f8baeda5cd0450023e7f1d066a)[da8d42c](https://github.com/azerothcore/azerothcore-wotlk/commit/da8d42c72cf819f8baeda5cd0450023e7f1d066a)[da8d42c](https://github.com/azerothcore/azerothcore-wotlk/commit/da8d42c72cf819f8baeda5cd0450023e7f1d066a)

### Operating system

win11 x64

### Custom changes or Modules

* Modules config list:
  |
  +- mod-arena-3v3-solo-queue
  |  * arena_3v3_solo_queue.conf.dist
  +- mod-boss-announcer
  |  * mod_boss_announcer.conf.dist
  +- mod-breaking-news-override
  |  * breakingnews.conf.dist
  +- mod-eluna
  |  * mod_LuaEngine.conf.dist
  +- mod-guildhouse
  |  * mod_guildhouse.conf.dist
  +- mod-learn-spells
  |  * mod_learnspells.conf.dist
  +- mod-money-for-kills
  |  * mod_moneyforkills.conf.dist
  +- mod-npc-all-mounts
  |  * npc_allmounts.conf.dist
  +- mod-npc-gambler
  |  * npc_gambler.conf.dist
  +- mod-progression-system
  |  * progression_system.conf.dist
  +- mod-top-arena
  |  * modarenatop.conf.dist
  +- mod-transmog
  |  * transmog.conf.dist
  +- mod-weekend-xp
  |  * mod-double-xp-weekend.conf.dist
  +- mod-world-chat
  |  * WorldChat.conf.dist

**Comment by Nyeriah** [comment]
What error it gives? You are not really providing any information so it’s impossible to tell what your issue is

**Comment by xengine-qyt** [comment]
There were many warnings and errors, with the warnings mainly related to symbol import linking. The errors were primarily linking errors and some precompiled header (PCH) errors. There were too many errors, and I don't know why they occurred. I'm sorry, I deleted them. Using static library linking, the compilation passed.
