### ISSUE TITLE
Nagrand Arena Mogor the Ogre doesn't revive himself

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1907]
SMALL DESCRIPTION:

Mogor doesn't revive after he's been killed for the first time.

EXPECTED BLIZZLIKE BEHAVIOR:

https://www.youtube.com/watch?v=i-atkvdLsNA Quotes look chat

Video Bossfight https://youtu.be/wCjLu8Q1pM0?t=241

https://wowwiki.fandom.com/wiki/Mogor_the_Ogre

In the Burning Crusade expansion, Mogor leads the Warmaul Ogres in the Laughing Skull Ruins in northern Nagrand in Outland. He watches, while shouting insults at you, during the series of battles in the Ring of Blood. After you finish pummeling (or getting pummeled by) the 5 elites, Mogor himself comes down to fight you personally. He has a slight heal, (but has a ton of health, making it a very annoying ability) When he is first killed he will resurrect himself (He will have less health this time around) and will enrage, hitting for over 1000 damage on plate armor.

CURRENT BEHAVIOUR:

Man goes to do the arena quest in Nagrand after killing the 5 bosses before comes Mogor.

Mogor doesn't do much except go into the ring and say 1 sentence and then start the fight he heals himself a little and castet follow spells.

Spells that work

Mogor - In Combat - Cast 'Chain Lightning' (No Repeat) ID 16033
Mogor - In Combat - Cast 'Flame Shock' (No Repeat) ID 39529
Mogor - Between 0-60% Health - Cast 'Healing Wave' (No Repeat) 15982
Mogor - Between 0-30% Health - Cast 'Frenzy' (No Repeat) ID 28747

When he dies, he completes the quest.

AC Video https://youtu.be/hBb-2u2fmrw

Offi Video Bossfight https://youtu.be/wCjLu8Q1pM0?t=241

STEPS TO REPRODUCE THE PROBLEM:

.quest remove 9962
.quest remove 9967
.quest remove 9970
.quest remove 9972
.quest remove 9973
.quest remove 9977

.go -727.81 7929.77 58.001 530 

Start the quest series and defeat the 5 bosses and then start the quest with mogor name of quest The Ring of Blood: The Final Challenge.

BRANCH(ES):

AzerothCore rev. 0e08350b69fe+ 2019-05-28 14:29:31 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: 
Transmog
Worldchat

**Comment by Stoabrogga** [comment]
I'll look into this.
