### ISSUE TITLE
Feature (CI): add `ready_for_review` to pull request types filter

### ISSUE THREAD

**Issue by sogladev** [azerothcore/azerothcore-wotlk#19085]
### Describe your feature request or suggestion in detail

Setting PR status from `draft` to `ready for review` does not trigger builds.  closing/opening or adding a useless commit is /can be used as a workaround.

official docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

### Describe a possible solution to your feature or suggestion in detail

Add `ready_for_review` to pull request types filter like below to the files listed below

```
pull_request:
    branches: [my_branch]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
```

https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/core-build-nopch.yml
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/core-build-pch.yml
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/core_modules_build.yml
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/docker_build.yml
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/macos_build.yml
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/windows_build.yml

**Comment by Kitzunu** [comment]
this is fixed
