### ISSUE TITLE
bug priest count kill 2 times

### ISSUE THREAD

**Issue by shuradumau** [azerothcore/azerothcore-wotlk#1908]
http://prntscr.com/nv4rhd
when the priest has this talent activated, when he dies he becomes an angel, until normal, but when he turns an angel and you kill the angel, it counts as if it were 2 kills or even 5 .. the normal should be counting only one kill,

AzerothCore rev. 68a998c79e9c+ 2019-05-26 13:09:40 +0000 (master branch) (Win, Release)

**Comment by poszer** [comment]
Please fill issue template as described

**_IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE!_** 








##### SMALL DESCRIPTION:




##### EXPECTED BLIZZLIKE BEHAVIOUR:




##### CURRENT BEHAVIOUR:




##### **_STEPS TO REPRODUCE THE PROBLEM_**:


1. 
2. 
3. 

##### EXTRA NOTES:


##### BRANCH(ES):


master


##### **_AC HASH/COMMIT_**:




##### OPERATING SYSTEM:




##### MODULES:




##### OTHER CUSTOMIZATIONS:
