### ISSUE TITLE
(Event/Midsummer)Server Crash by npc_midsummer_ribbon_pole_target

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#19107]
### Current Behaviour

Thread 15 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9abff640 (LWP 608330)]
std::_Rb_tree<unsigned int, std::pair<unsigned int const, AuraApplication*>, std::_Select1st<std::pair<unsigned int const, AuraApplication*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, AuraApplication*> > >::equal_range (this=0x7fff79759278, __k=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_tree.h:2005
2005		  if (_M_impl._M_key_compare(_S_key(__x), __k))
#0  std::_Rb_tree<unsigned int, std::pair<unsigned int const, AuraApplication*>, std::_Select1st<std::pair<unsigned int const, AuraApplication*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, AuraApplication*> > >::equal_range (this=0x7fff79759278, __k=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_tree.h:2005
#1  std::multimap<unsigned int, AuraApplication*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, AuraApplication*> > >::equal_range (this=0x7fff79759278, __x=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_multimap.h:1048
#2  Unit::GetAuraApplication (this=0x7fff79758c80, spellId=45406, casterGUID=..., itemCasterGUID=..., reqEffMask=0 '\000', except=except@entry=0x0) at /root/azerothcore/src/server/game/Entities/Unit/Unit.cpp:5506
#3  0x0000555556392b39 in Unit::HasAura (this=0x7fff79758c80, spellId=45406, casterGUID=..., itemCasterGUID=..., reqEffMask=0 '\000') at /root/azerothcore/src/server/game/Entities/Unit/Unit.cpp:5642
#4  0x0000555555c75d96 in npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}::operator()(Player*) const (dancer=0x7fff79758c80, this=<optimized out>) at /root/azerothcore/src/server/scripts/Events/midsummer.cpp:712
#5  __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}>::operator()<__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > > >(__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >) (__it=0x7fff79758c80, this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/predefined_ops.h:318
#6  std::__find_if<__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}> >(__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}>, std::random_access_iterator_tag) (__first=0x7fff79758c80, __last=__last@entry=0xf1f1690000c05621, __pred=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_algobase.h:2099
#7  0x0000555555c75b7b in std::__find_if<__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}> >(__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}>) (__first=0x7fff71721160, __last=0xf1f1690000c05621, __pred=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_algobase.h:2114
#8  std::__remove_if<__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}> >(__gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__normal_iterator<Player**, std::vector<Player*, std::allocator<Player*> > >, __gnu_cxx::__ops::_Iter_pred<npc_midsummer_ribbon_pole_target::DoCleanupChecks()::{lambda(Player*)#1}>) (__first=0x7fff71721160, __last=0xf1f1690000c05621, __pred=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_algo.h:816

### Expected Blizzlike Behaviour

No crash

### Source

npc_midsummer_ribbon_pole_target::DoCleanupChecks()
/src/server/scripts/Events/midsummer.cpp:712

### Steps to reproduce the problem

None

### AC rev. hash/commit

48c141895adf3f38d7d33fac55b8bada4a75b303

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
Please upload crashlogs to a [gist](https://gist.github.com/) and post them rather than uploading contents into an issue body.

**Comment by Nyeriah** [comment]
nullptr/dereference crash, worldobjects (players, creatures, objects) shouldn't be stored in scripts but instead be assessed through their GUID
