### ISSUE TITLE
Durotar there are no mines and herbs

### ISSUE THREAD

**Issue by PkllonG** [azerothcore/azerothcore-wotlk#19100]
### Current Behaviour

https://github.com/azerothcore/azerothcore-wotlk/pull/18982
After that in Dulongtal there are no mines and herbs

### Expected Blizzlike Behaviour

There should be herbs and minerals here

### Steps to reproduce the problem

.go -611 -4263 40 1
.go 9592 1037 1270 1
Check it out there

### AC rev. hash/commit

3872c39aabe37791b31c9ce6384e30a50a8afc84

### Operating system

Win Server 2019 x64

**Comment by PkllonG** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/d1cf8d9d-7c39-462d-83bb-bc98bdab28c5)
There are no mines and herbs in these two areas

**Comment by sudlud** [comment]
@Gultask

**Comment by Gultask** [comment]
Wtf I thought I never touched those 2 and I remember checking, even.

I'll fix this, it's easy, Neifion had rebuilt those from scratch so we just need to re-run the queries.

**Comment by Gultask** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/15f2aace-d455-46c1-b5a7-d5945aea7cfe)

I'll rebuild my DB and re-compile just in case but it should be working.
Remember that the level 1-5 zones like Valley of Trials and Shadowglen should have no nodes, while the level 6-10 like Durotar proper and Teldrassil should. Teldrassil also has no mines, since it's technically a giant tree.

**Comment by Gultask** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/fc225f15-6964-4731-841b-319e3c3c19b7)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/a6d5a098-4429-4821-8f90-87ddc459e8ef)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/d0b7a186-d341-4a79-9a3f-e3143b038ed1)

Could you check again on your end? If it's something missing on your end only I'll make you a query for it.

**Comment by PkllonG** [comment]
I'm reinstalling the core, wait a minute

**Comment by PkllonG** [comment]
@Gultask  @sudlud  @Nyeriah Thank you all for paying attention to my problem, the error disappeared after a clean install of the core.

**Comment by PkllonG** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/e3742141-d07b-4438-afbc-df7afa71215e)
It should have something to do with it

**Comment by Gultask** [comment]
yeah the last commit of that PR had that added so it would exclude Teldrassil and Durotar. And no worries, I don't mind checking :)
