### ISSUE TITLE
(Instance/Azjol-Nerub): Anub'Arak should remove debuffs on submerging

### ISSUE THREAD

**Issue by YggdrasilWotLK** [azerothcore/azerothcore-wotlk#19113]
### Current Behaviour

Currently, he's not dropping his debuffs when he starts to cast submerge. Consequences of this includes that if he dies while submerged (due to DOTs), he becomes unlootable.

### Expected Blizzlike Behaviour

He should drop his debuffs on starting to cast submerge. 

### Source

https://www.youtube.com/watch?v=mTlJn8oGTJ0 re 06:40

### Steps to reproduce the problem

1. Go to Anub'Arak in Azjol-Nerub
2. DOT him up
3. Get him to 75% and watch him submerge with DOTs active

### Extra Notes

I'm not too familiar with how PRs and such work but I imagine the fix could be changing this part in boss_anubarak.cpp (https://github.com/metallinos2/azerothcore-wotlk/commit/64802191a93c8a8eb113025b96a42d85a27751c8)

                        if (me->HealthBelowPct(eventId*25))
                        {
                            Talk(SAY_SUBMERGE);
                            me->RemoveAllAuras(); *new line to remove auras 
                            me->CastSpell(me, SPELL_IMPALE_PERIODIC, true);
                            me->CastSpell(me, SPELL_SUBMERGE, false);

### AC rev. hash/commit

20ff8df91ca7

### Operating system

Ubuntu 20.04

### Custom changes or Modules

ELUNA module

**Comment by sogladev** [comment]
On wrath classic he did remove all dots at the start of his burrow. He remained targettable for ~1 second, so you could re apply a dot. 

burrow in TOGC for reference does remove auras 

- https://github.com/azerothcore/azerothcore-wotlk/blob/b055faf8eec50c6cdf39a2144df902992528e7d4/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp#L316

unkillable can be done with bossAI
```
void DamageTaken(Unit* attacker, uint32& damage, DamageEffectType damageEffectType, SpellSchoolMask spellSchoolMask) override
    {
        if (me->HasAuras(SPELL_SUBMERGE);)
        {
            if (damage >= me->GetHealth())
            {
                damage = me->GetHealth() - 1;
            }
        }
        BossAI::DamageTaken(attacker, damage, damageEffectType, spellSchoolMask);
    }
```

**Comment by heyitsbench** [comment]
Anub'Arak uses [this spell](https://wowgaming.altervista.org/aowow/?spell=34098) to clear his debuffs on submerge.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/4e6d433dd2d8a7b9aa2ae6813cdfb3758ab3c1b3
