### ISSUE TITLE
[worldserver] crash20240621

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#19112]
### Current Behaviour

crash log:

https://gist.github.com/mpfans/c2582f2bc29c5d97ba12246ba81345e4

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e69f642dfeb7f5fe1999863e1443d2f5242e2597

### Operating system

Ubuntu 20.04

**Comment by heyitsbench** [comment]
Should get resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/19109.
