### ISSUE TITLE
Dk starting level bugged

### ISSUE THREAD

**Issue by DeewaTT91** [azerothcore/azerothcore-wotlk#19124]
### Current Behaviour

Setting "StartHeroicPlayerLevel" to a value below 55 prevents the server from starting.

### Expected Blizzlike Behaviour

You should just be able to spawn as dk, but be level 35.

### Steps to reproduce the problem

1. Go to your server config
2. change the value for StartHeroicPlayerLevel to something below 55
3. try to start your server

### AC rev. hash/commit

Loading Player Create Level Stats Data...
Race 1 class 6 initial level does not have stats data!
exit code: 1
worldserver terminated, restarting...
worldserver Terminated after 9 seconds, termination count: : 2
Running without GDB

### Operating system

Debian 10 x64

### Custom changes or Modules

Playerbots

**Comment by Kitzunu** [comment]
You need to fill player stat data in the db for DKs below 55 https://www.azerothcore.org/wiki/player_class_stats
