### ISSUE TITLE
(Instance/TrialoftheCrusader): Anub'Arak does not use the proper spell to clear his debuffs on submerge.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19136]
### Current Behaviour

Just uses the RemoveAllAuras method.

### Expected Blizzlike Behaviour

Should cast [ClearAllDebuffs](https://wowgaming.altervista.org/aowow/?spell=34098).

### Source

Wrath Classic sniff (50172)

### Steps to reproduce the problem

1. Do Trial of the Crusader.
2. Get to Anub'Arak.
3. Let him submerge.
4. Observe no debuff clear spell cast.

### AC rev. hash/commit

b055faf8eec50c6cdf39a2144df902992528e7d4

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19140
