### ISSUE TITLE
Feature: Changing the meaning of the create_template table

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/azerothcore-wotlk#19137]
### Describe your feature request or suggestion in detail

Personally, I don't see the need to change it at all, is it just to make it easier to individually modify the size of different appearances of the same creature? The create_template table associates some of the modules with the lua.

### Describe a possible solution to your feature or suggestion in detail

It is highly recommended to revert to the previous structure.

### Additional context

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/110412571/cf29268d-5a8c-47c9-b19d-32d77cf630a3)

**Comment by heyitsbench** [comment]
> is it just to make it easier to individually modify the size of different appearances of the same creature?

To make it possible to individually modify the size and probabilities of different displays for creatures.

**Comment by Kitzunu** [comment]
Because of blizzlike purposes. Adding 8 new columns to C_T is just not it.

**Comment by Kitzunu** [comment]
I also want to make it very clear that AC is developed by itself and any module or custom extension, such as ELUNA, should adapt after what AC does. Not the other way around.

The development of AzerothCore does not stop just because it makes it an inconvenient for a user to update
