### ISSUE TITLE
Feature: Instance difficulty condition.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19147]
### Describe your feature request or suggestion in detail

`ConditionTypeOrReference` column in `conditions` table has no ID for instance difficulty.

### Describe a possible solution to your feature or suggestion in detail

Implement a new condition ID for getting instance difficulty.

### Additional context

TrinityCore apparently has an ID for instance difficulty implemented.

**Comment by Kitzunu** [comment]
we do CONDITION_DIFFICULTY_ID
