### ISSUE TITLE
Hunter: Pets disappearing when interacting with stable or on BM -> MM/SV specialization change.

### ISSUE THREAD

**Issue by Andrei-UPB** [azerothcore/azerothcore-wotlk#1914]
Hunter: Pets disappearing when interacting with stable or on BM -> MM/SV specialization change.

##### SMALL DESCRIPTION:

When changing the current pet with another from the stable via Call Stabled Pet or by changing specializations with a dismissed pet, you permanently lose the pet that's in your "Current Pet" stable slot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should under no circumstance lose any stabled pets whenever performing permutations with the Call Stabled Pet spell ( https://wotlk.evowow.com/?spell=62757 ) or interacting with a Stable Master NPC.

The "Current Pet" slot should still be filled by the  "current pet" you were using even after dismissing it, as there is a difference between dismissing your pet (un-summoning it) and abandoning it (PERMANENTLY deleting it).

##### CURRENT BEHAVIOUR:

Dismissing the pet (1), being mounted while using the Stable Master NPC (2) or switching specializations (3) removes said pet from the current pet stable slot (the slot appears empty), you can drag another pet from your stable roster into your current pet slot and lose the first one in the process instead of the pet swap going through, replacing the initial pet with one of your choosing from your four stable slots.

To be able to reproduce I recommend a fully decked pet roster, let's consider C as the current pet, S1 , S2, S3 and S4 as our stabled pets.

1. Have your current pet active (IE: not dismissed, not mounted) and accessing the stables in one of the two ways described above yields the following result:
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      C                            S1              S2                 S3            S4

``` 
2. Attempt to swap some pets around, let's say we want to take S4 out. We drag S4 into the Current Pet slot, thus Stable Slot 4 will be taken by C.
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      S4                            S1              S2                 S3            C

``` 
This is the INTENDED BEHAVIOUR and how it should ALWAYS work.

##### STEPS TO REPRODUCE THE PROBLEM:

The screenshots below will answer most of the questions, but i'll describe it with a little graphic as well.

In the current behaviour section i've typed (1), (2), and (3) in parentheses , I'll post a how-to-reproduce for each of them.

(1). Dismissing the pet and swapping with another from the stable via Call Stabled Pet ( https://wotlk.evowow.com/?spell=62757 ) or interacting with a Stable Master NPC ( I used NPC entry 10050 , but you can use any stable master).

1. Dismiss Pet ( https://wotlk.evowow.com/?spell=2641 ) your current pet and accessing the stables in one of the two ways described above yields the following result:
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
   <empty>                         S1              S2                 S3            S4

``` 
2. Attempt to swap S4 to the Current Pet position. We drag S4 into the Current Pet slot, thus Stable Slot 4 SHOULD be taken by C.
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      S4                            S1              S2                 S3        <empty>

``` 
3. Stable Slot 4 is not occupied by the current (dismissed) pet C because the game interprets that as no pet existing, therefore stable slot 4 will be empty, and you will lose pet C forever.
4. You can repeat these steps until you've lost all but one of your five pets.

(2). The same way to reproduce as (1), except you don't have to dismiss your pet but be mounted (tested with a  regular ground mount) and interact with a Stable Master NPC (tested with https://wotlk.evowow.com/?npc=10050 ) , mounting has no effect over swapping pets via Call Stabled Pet because using the spell dismounts you, therefore i considered this a second way to replicate the bug.

1. Mount up and access the stables by talking to the Stable Master and choosing the "I'd like to stable my pet here." gossip, you will be greeted by this menu:
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
   <empty>                         S1              S2                 S3           <empty>

``` 
2. Attempt to swap S3 to the Current Pet position. We drag S3 into the Current Pet slot, thus Stable Slot 3 SHOULD be taken by S4, who became our current pet in the last reproduction cycle for (1). The result can be seen below:

```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      S3                            S1              S2                <empty>        <empty>

``` 
3. Stable Slot 3 is not occupied by the current pet S4 because you are mounted and the game interprets that as you not having a pet active, therefore stable slot 3 will be empty, and you will lose pet S4 forever.

(3). This issue is related to swapping specializations from Beast Mastery to Marksmanship or Survival and losing your exotic pet in the process.

1. Have an exotic beast as your current pet ( I tamed Skoll https://wotlk.evowow.com/?npc=35189 for this purpose ).
2. Swap specializations from Beast Mastery to Marksmanship or Survival.
3. Open your stables by using Call Stabled Pet or talking with a Stable Master NPC.
4. Your current pet slot is now empty and upon taking another pet from the stable you lose your exotic beast forever akin to (1) and (2). How this should work is you should be able to see your exotic pet in your current slot, but redded-out (unusable) and be able to move it in an empty stable slot or swap with an existing non-exotic pet usable in Marksmanship or Survival specializations
##### SCREENSHOTS:
I've added three imgur albums describing each of the issues mentioned above (1), (2), (3).
(1). https://imgur.com/a/rmh5CN0
(2). https://imgur.com/a/w7SxgdM
(3). https://imgur.com/a/1XCAvRF
##### EXTRA NOTES:

There's an earlier issue pertaining this but I found out after I already wrote and documented all of this :( , The earlier issue  can be found here : https://github.com/azerothcore/azerothcore-wotlk/issues/1621 

**If there is a way to merge both issues that would be fantastic as I would not want this to go to waste.**

I believe the fix might be related to a way to store the dismissed pet in the current pet slot  even post dismissal or when you are mounted instead of it becoming empty upon dismissal / mounting up.

I have no means of testing this on any other server application at the current time. I'll try to download a clean TC and test there.
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

b67ea15
##### OPERATING SYSTEM:

Ubuntu 18

##### MODULES:

Transmogrification module, but I doubt there's anything related to that.

##### OTHER CUSTOMIZATIONS:

Yes, I did modify some database entries to fix other various bugs, however they should be unrelated.

Thank you in advance for looking over this, the issue seems daunting at first but I am sure that if there's a possibility to somehow store the current pet in it's slot even when dismissed or the player character is mounted, this bug will be resolved and no pets will ever be lost again.

**Comment by poszer** [comment]
Yeah, same issue like https://github.com/azerothcore/azerothcore-wotlk/issues/1621

**Comment by solidmaxtor** [comment]
I also confirmed it 1 month ago.
In bountysource is more reward now.
https://www.bountysource.com/issues/71835162-hunter-pet-disappear

**Comment by Helias** [comment]
If this is a duplicate we can close this, @poszer

**Comment by Andrei-UPB** [comment]
I would close it myself but I do feel like this post is bringing more evidence to the table and I would like the possibility to merge / crosspost this to the other opened issue #1621 , as stated previously, I found it out after already writing the entirety of the post and uploading the screenshots.

**Comment by BarbzYHOOL** [comment]
yeah close the smallest one

Eventually can merge the texts

**Comment by Andrei-UPB** [comment]
@GMKyle As promised, I tested PR#2100 , and i bring both good and bad news.

This fix solves the issue but only in part. You can move your current dismissed pet into the stable and it works as intended. The problem (I believe it's an oversight and easily fixable) is if instead of moving the dismissed pet into the stables, you move one of the stabled pets into the current pet slot, and it gets overwritten.

To clarify:
The pet C is your current pet, but is dismissed for case (1) and (3) or considered dismissed because the player is mounted for (2).
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      C                                    S1               S2                      S3                    S4
```
If you swap over C with  S1, it works as it should and you get the following result:
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      S1                                   C               S2                      S3                    S4
```
But if you swap over S1 with C, you get the following result:
```
|Current Pet|                |Stable Slot 1| |Stable Slot 2| |Stable Slot 3| |Stable Slot 4|
      S1                                 S2                      S3                    S4          <empty>

```

C -> S1 is working fine,
S1 -> C is not and still leads to the current pet being lost after the transfer.
The current pet is also listed as level 0 if dismissed (minor, shouldn't matter much).

**Comment by FrancescoBorzi** [comment]
@Andrei-UPB thanks a lot for testing, but please post the feedback of the PR in the PR discussion and not in the issue :)

**Comment by Andrei-UPB** [comment]
I did that as well.
