### ISSUE TITLE
shaman totems bugs / disappear buff after 3

### ISSUE THREAD

**Issue by Zydrax** [azerothcore/azerothcore-wotlk#1916]
##### SMALL DESCRIPTION:

shaman totems bugs / disappear buff after 3 seconds to lighting sheald and to water sheald the same

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make a Shaman character 
2. Activate Totem 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/490fd16bf56db23a15e16b62513419ba43036811

##### OPERATING SYSTEM:

Ubuntu 18

##### MODULES:

Antichat 
Weekend XP
Solocraft

**Comment by poszer** [comment]
Can you please write us more informations

**Comment by Viste** [comment]
https://github.com/Viste/trinity/commit/5dd7da0a74eb4f2aa0a563290b40a20bb36b298e ?

**Comment by Voxstrasza** [comment]
I created a Shaman, activated Lightning Shield, dropped some totems and the buff persisted.  Same with Water Shield.  Cannot reproduce.
