### ISSUE TITLE
Dalaran Visitors

### ISSUE THREAD

**Issue by Andyk10** [azerothcore/azerothcore-wotlk#19174]
### Current Behaviour

Dalaran visitor, will not disappear even if they don't dismount.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/125536059/44c0ab6a-87df-4ffd-a8e8-95688f468406)

### Expected Blizzlike Behaviour

Dismount, run into Dalaran, disappear.

### Steps to reproduce the problem

.go xyz 5819 453 659

### AC rev. hash/commit

bb0a04e

### Operating system

windows 10 x64

**Comment by Andyk10** [comment]
BTW, it was correct before e69f642.

**Comment by Andyk10** [comment]
It did not fix this issue. @PkllonG

**Comment by heyitsbench** [comment]
> It did not fix this issue.

You will need to drop your world database and have your worldserver reconstruct it. Back up any changes you may have made before doing so.

**Comment by Andyk10** [comment]
reconstruct？OMG！ T.T

**Comment by Andyk10** [comment]
![ab9eefbd610d8eb4ff6ee682beed033a](https://github.com/azerothcore/azerothcore-wotlk/assets/125536059/a4bddb76-4423-4ffc-afea-01111cbc9edb)
Isn't updating possible?

**Comment by Andyk10** [comment]
I resolved it. Luckily, I had a backup from the 20th. That was scary.

**Comment by avarishd** [comment]
https://www.azerothcore.org/wiki/sql-directory#custom-files
