### ISSUE TITLE
Line of sight its bugged, i cannot los mobs

### ISSUE THREAD

**Issue by Zydrax** [azerothcore/azerothcore-wotlk#1917]
##### SMALL DESCRIPTION:

Line of sight its bugged, i cannot los mobs...for example if i pull a mob caster and i hide behinde a wall he still hits me with spells. The proper way was that he comes after me and couldnt cast thru walls.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/490fd16bf56db23a15e16b62513419ba43036811

##### OPERATING SYSTEM:

Ubuntu 18

##### MODULES:

Antichat
Weekend XP
Solocraft

**Comment by Shard-MW** [comment]
Cannot reproduce, it works for me. Npc's are following me when I'm hidden behind a pillar and casts when I'm in their los.
Where did you had this issue ? Did you enabled vmaps and mmaps ?

**Comment by BarbzYHOOL** [comment]
I retried exactly the issue and it's not happening.
