### ISSUE TITLE
SAI MOVE_TO_POS incorrect behavior when target is closest object(and maybe creature).

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#19171]
### Current Behaviour

When using a combination of MOVE_TO_POS and target for closest/all objects (and probably creatures) and no target is found within the given distance (no matter if reaching the hardcap at 100y or not) the creature starts moving to [Destination Unknown](https://www.youtube.com/watch?v=7RmOiiMB-jM).

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/058bee14-16f6-4155-bf7e-961c6d2a3ab4)

When object is within specified distance. (correct)

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/b840da32-d122-45e9-8afe-8cd8ee0eea53

When object is OUTSIDE of specified distance (incorrect)

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/68545077-26ef-438e-aa02-3a39f0b6ef96

### Expected Blizzlike Behaviour

To either stop the entire SAI action/actionlist as it fails to find the target.

### Steps to reproduce the problem

After https://github.com/azerothcore/azerothcore-wotlk/pull/19169
.go c 71065
Drop to under 20% and he goes on an adventure

### Extra Notes

Most likely closest creature and all creatures/objects in range causes the same issue.

### AC rev. hash/commit

b2457ef67e4e0a3cde875ef2a1c00b4624cacd48

### Operating system

Windows 10

**Comment by PkllonG** [comment]
quest id 12673 This error also exists
