### ISSUE TITLE
Quest markers disappearing

### ISSUE THREAD

**Issue by OtavioProfeta** [azerothcore/azerothcore-wotlk#19173]
### Current Behaviour

I noticed that some quest NPCs do not carry the exclamation and question marks signaling the quest. It happened several times with the first NPC with the tutorial mission where sometimes the marker appeared and sometimes it didn't. But one NPC that ALWAYS crashes is the blood elves' Well Watcher Solanian. He offers us two missions and when he returns to complete them he is always without the mission marker.

### Expected Blizzlike Behaviour

Show all quest markers and quest completions.

### Steps to reproduce the problem

1 - Create a Blood Elf
2- Do the first tutorial mission
3 - Do the two Well Watcher Solanian's missions
4- Return to Well Watcher Solanian's to complete the mission

### Extra Notes

None

### AC rev. hash/commit

None

### Operating system

Windows 10

### Custom changes or Modules

None

**Comment by PkllonG** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/18535853/9b4dacc7-3616-48ff-83ab-ff7a5ac70f7b)
Try this

**Comment by OtavioProfeta** [comment]
It worked, the bug was fixed!

**Comment by Kitzunu** [comment]
Closing as no hash was provided
