### ISSUE TITLE
[ChatLevelReq] !

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#1918]
DESCRIPTION: On The Worldserver.cfg Not Found LevelReq For "Guild and Party" Chats!

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L1956

AC HASH/COMMIT:https://github.com/azerothcore/azerothcore-wotlk/commit/490fd16bf56db23a15e16b62513419ba43036811

Os: Windows 2016 Server

Modules:
Antichat
Weekend XP
Solocraft

**Comment by poszer** [comment]
Bcoz we don't have it ^^
