### ISSUE TITLE
[QUEST] Cleansing Drak'Tharon

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#192]
**Description**: The NPC Image of Drakuru (26787) appear when i use Drakuru's Elixir

**Current behaviour**: The NPC don't give any quest
**Expected behaviour**: The NPC give me the quest Cleansing Drak'Tharon (http://wotlk.openwow.com/quest=12238)

**Steps to reproduce the problem**:
1. Use Drakuru's Elixir [http://www.wowhead.com/item=35797/drakurus-elixir] in grizzy hills at and talk with Image of Drakuru
##

**Comment by talamortis** [comment]
@ghost1988 is he surposed to give you a quest? or are you surpoed to be able to complete a quest?

**Comment by ghost1988** [comment]
Start "image of drakuru" grizzly hills and complete "drakuru" into draktaron.

**Comment by talamortis** [comment]
@ghost1988 please test the PR and let me know if it works or not

**Comment by ShinDarth** [comment]
@talamortis thanks for the fix, can you please check my review?
