### ISSUE TITLE
Nagrand Kristen Dipswitch Event does not exist

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1920]
SMALL DESCRIPTION:

The little gnome should survive to get a quest Quest is called I'm Saved! Id 9897

I have found a sql file on the internet I think you can do a good job with it
https://git.fastblit.com/rowanxt/tbc-db/blob/3facfa05913376e627092412ca2f97bfe155276f/Updates/386_nesingwary_safari.sql

Offi https://www.youtube.com/watch?v=Hk5J2RU0NlE

https://www.youtube.com/watch?v=FCk3BqD8YmU There are 2 events in the Sql in the same place.

EXPECTED BLIZZLIKE BEHAVIOR:

It is about a small event with the Gnom Kristen Dipswitch Id 18294

The little gnome rides all the way to Nesingwary Safari Station

she's talking to Hemet Nesingwary Id 18180.

A scoundrel ID 18297 comes and sneaks up on her. 

the two fight who you help her get you a quest.

CURRENT BEHAVIOUR:

All the creatures are there and spawned but the whole event is missing.

STEPS TO REPRODUCE THE PROBLEM:
.go c 65624  Kristen Dipswitch
.go c 86752 Gankly Rottenfist

BRANCH(ES):

AzerothCore rev. 0e08350+ 2019-05-28 14:29:31 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
Transmog
Worldchat

**Comment by Voxstrasza** [comment]
Confirmed as of `9facd81e54ac`

The fix in the OP might work but it's not catered to the AC database structure
