### ISSUE TITLE
Majordomo Executus guards respawning when fight is supposed to end

### ISSUE THREAD

**Issue by ThoorAdam** [azerothcore/azerothcore-wotlk#19212]
### Current Behaviour

When you kill all the guards Majordomo becomes friendly as supposed. But his guards respawn and if you continue to kill them they keep respawning. This prevent Ragnaros from spawning. 

This started occuring when we updated our core yesterday. We were behind a few weeks of updates.

### Expected Blizzlike Behaviour

The guards should not respawn.

### Steps to reproduce the problem

1. Kill Majordomos guards.

### AC rev. hash/commit

AzerothCore rev. 407c10bdf0cf+ 2024-06-26 12:30:13 +0200 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)
Connected players: 7. Characters in world: 7.
Connection peak: 7.
Server uptime: 1 hour(s) 6 minute(s) 56 second(s)
Update time diff: 12ms. Last 500 diffs summary:
- Mean: 14ms
- Median: 12ms
- Percentiles (95, 99, max): 20ms, 21ms, 23ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80037
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.5.0-1023-oracle
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/ubuntu/wow/Data/maps. Total size: 291014951 bytes
vmaps directory located in /home/ubuntu/wow/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/ubuntu/wow/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-eluna
- mod-instance-reset
- mod-transmog

### Operating system

Ubuntu 22.04

### Custom changes or Modules

mod-eluna
mod-transmog
mod-instance-reset
trickerer TrinityBots

**Comment by 2uah** [comment]
Happens also to me 2nd week in a row. First week we tought we killed the boss what caused this bug, but today it happened again

Here is video proof: https://youtu.be/WlqX1i73uLI

**Comment by dbennett33** [comment]
Also experiencing this issue - spun up a fresh instance of acore and same problem still

**Comment by Nyeriah** [comment]
Can`t reproduce at https://github.com/azerothcore/azerothcore-wotlk/commit/77be5bb19d82a12dc27928c52c4204f37b8bf327

Update your core / playerbots branch

**Comment by webtectonics** [comment]
Also having this issue.

**Comment by ThoorAdam** [comment]
> Also having this issue.

This is fixed. Update your core.

**Comment by webtectonics** [comment]
You are absolutely correct.  Thank you.  It's working now.
