### ISSUE TITLE
Error en CMAKE

### ISSUE THREAD

**Issue by SNetWoW** [azerothcore/azerothcore-wotlk#19228]
### Current Behaviour

Hola quiero compilar azeroth core pero el cmake me da dos errores.
ERROR 1:

CMake Warning (dev) at deps/boost/CMakeLists.txt:35 (find_package):
Policy CMP0167 is not set: The FindBoost module is removed. Run "cmake
--help-policy CMP0167" for policy details. Use the cmake_policy command to
set the policy and suppress this warning.

This warning is for project developers. Use -Wno-dev to suppress it.

ERROR 2:

Running cmake hook: BEFORE_GAME_LIBRARY

No hooks registered for BEFORE_GAME_LIBRARY

Running cmake hook: AFTER_GAME_LIBRARY

No hooks registered for AFTER_GAME_LIBRARY

Running cmake hook: BEFORE_SCRIPTS_LIBRARY

No hooks registered for BEFORE_SCRIPTS_LIBRARY

Y AL FINAL:

Running cmake hook: AFTER_SRC_LOAD

No hooks registered for AFTER_SRC_LOAD

Configuring done (39.1s)

### Expected Blizzlike Behaviour

1. Necesito solucionar el problema 

### Steps to reproduce the problem

Esto sucede al configurar el proyecto en cmake

### AC rev. hash/commit

La última 

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
This is not a help forum. go to discord
