### ISSUE TITLE
Worldserver.exe Mysql Error

### ISSUE THREAD

**Issue by Snickers213** [azerothcore/azerothcore-wotlk#1923]
##### SMALL DESCRIPTION:
I run Worldserver.exe and I receive a error about Mysql "mysql_stmt_prepare"
and that the table 'acore_world.graveyard_zone' doesn't exist.
I tried to run both SQL Updater and reinstalled mysql database, but I can seem to update the mysql database.

[Logs](https://gist.github.com/Snickers213/ec7a018d404be81a53c24d65686ab261)

When I try to use updates>db_world and the latest version I get unnamed warning. 

##### AC HASH/COMMIT:
e9013454a61b8d7fefdcaca58746a0f7b02bd3b1

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
None

**Comment by Winfidonarleyan** [comment]
Update DB to last :/
