### ISSUE TITLE
SpellAttribute1 - SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT - Not Yet Implemented 

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#19248]
### Current Behaviour

SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT spell attribute1 does nothing

### Expected Blizzlike Behaviour

Should probably behave like SPELL_ATTR0_CU_IGNORE_EVADE
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp

### Steps to reproduce the problem

go to any  hostile creature
.aura 59208
enter combat and then .gm on - aura is removed

### Extra Notes

```sql
-- [stoneharry/WoW-Spell-Editor](https://github.com/stoneharry/WoW-Spell-Editor)
SELECT SpellName0,ID,AttributesEx FROM spell WHERE AttributesEx = AttributesEX|0x02000000
```
<details>
<summary> Spells with that attribute (0x02000000) </summary>

| SpellName0 | ID | AttributesEx | 
| --- | ---: | ---: | 
| You're a ...! (Effects1) | 43945 | 301989889 | 
| You're Infected! | 43958 | 33556480 | 
| You're a ...! (Effects2) | 44305 | 301989888 | 
| Juking | 44752 | 33554432 | 
| You're a ...! (Effects3) | 48050 | 301989888 | 
| Obsidian Essence | 48616 | 33556484 | 
| ZP - Retch! (Bunny Aura) | 51241 | 301989888 | 
| Corpse Exploded | 51270 | 33554464 | 
| Mosswalker Chains | 52140 | 302646276 | 
| Crystalline Essence | 53058 | 33554432 | 
| Death and Decay | 53721 | 33554568 | 
| Anti-Magic Shell | 53766 | 33554432 | 
| You're a ...! (Effects4) | 54059 | 301991936 | 
| You're a ...! (Effects5) | 54145 | 301989888 | 
| You're a ...! (Effects6) | 54147 | 301989888 | 
| You're a ...! (Effects7) | 54162 | 301989888 | 
| Enrage | 54287 | 33554432 | 
| End Fight, Garrosh | 55844 | 301989888 | 
| End Fight, Thrall is wounded | 56115 | 301989888 | 
| End Fight, Thrall | 56117 | 301989888 | 
| End Fight, Thrall recovers | 56253 | 33554432 | 
| Hover (Anim Override) | 57764 | 302254080 | 
| Geist Chain | 58103 | 302646276 | 
| Force Reaction: Scourge | 58117 | 301992960 | 
| Corrupted Rejuvenation | 58624 | 33554432 | 
| Enraged | 59208 | 33554432 | 
| Death and Decay | 60160 | 33554568 | 
| Death and Decay | 60953 | 33554568 | 
| Death and Decay | 61112 | 33554568 | 
| Wear Christmas Hat, Green (DND) | 61398 | 301989888 | 
| Wear Christmas Hat, Red (DND) | 61399 | 301989888 | 
| Wear Christmas Hat, Red, Self (DND) | 61400 | 301989888 | 
| Wear Christmas Hat, Green, Self (DND) | 61401 | 301989888 | 
| Saurfang Slow Down (DND) | 61458 | 301989888 | 
| Death and Decay | 61603 | 33554568 | 
| Death and Decay | 71001 | 33554568 | 
| Unsated Craving | 71168 | 33554432 | 
| Death and Decay | 72108 | 33554568 | 
| Death and Decay | 72109 | 33554568 | 
| Death and Decay | 72110 | 33554568 | 
| Well of Corruption | 72362 | 33554568 | 
| Grow | 74996 | 301990944 | 
| Zalazane's Fool | 75018 | 33555488 | 

</details>

### AC rev. hash/commit

688d7e2fdf4d0e9e2a5297ed03127a4f49b631be

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19254
