### ISSUE TITLE
Feature: improve curl command for docker app ac-client-data-init

### ISSUE THREAD

**Issue by slavanorm** [azerothcore/azerothcore-wotlk#19253]
### Describe your feature request or suggestion in detail

Hello thank you all for your work.
I have bad internet and after couple minutes googling turns out that this command could better utilize curl while downloading client data.

### Describe a possible solution to your feature or suggestion in detail

file: apps/installer/includes/functions.sh:249
AS IS:
```
    echo "Downloading client data in: $zipPath ..."
    curl -L https://github.com/wowgaming/client-data/releases/download/$VERSION/data.zip > "$zipPath" \
```
TO BE:
```
    echo "Downloading client data in: $zipPath ..."
    curl -C - -Z -o "$zipPath" \
        -L https://github.com/wowgaming/client-data/releases/download/$VERSION/data.zip \

```

### Additional context

reasoning:
using "-o filename" and "-C -" allows to continue download on network fail
using "-Z" allows multiple connections possibly speeding the download up

i'm not sure if -o filename works at all with docker volume, would be glad if someone clarified this.

best regards

**Comment by Kitzunu** [comment]
Feel free to open a PR
