### ISSUE TITLE
The CPU usage of the worldserver process is increasing again.

### ISSUE THREAD

**Issue by moncat2005** [azerothcore/azerothcore-wotlk#19268]
### Current Behaviour

After compiling using the [0c747bc](https://github.com/azerothcore/azerothcore-wotlk/commit/0c747bc92537e80fe21093a3d95af5187223f7d5) version on June 28th, it was found that the CPU usage of the Worldserver process had once again increased.
Under normal circumstances, when there were 5 online users, the CPU usage rate of WorldServer was around 30%, but it has now risen to over 80%.
![cpu-2024-07-04-02](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/0b360597-3ad0-4bd5-80e5-399780257ece)

At the same time, the last 500 diffs summary value displayed on the console has also significantly increased.
![cpu-2024-07-04-01](https://github.com/azerothcore/azerothcore-wotlk/assets/34859687/7c1dc6ec-60db-4b4a-af2d-28d9cc1c9435)

When normal the last 500 diffs summary value 
mean:12-15
median:11-12
percentiles:18,24,131

### Expected Blizzlike Behaviour

Restore normal CPU usage

### Steps to reproduce the problem

1. Run Worldserver compiled on June 10th and June 28th, respectively,
2. Launch the game and observe the last 500 diffs summary value on the console
3. Run TOP to check the CPU usage difference of the world server process.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0c747bc92537e80fe21093a3d95af5187223f7d5

### Operating system

ubuntu 18.04

**Comment by Kitzunu** [comment]
Send the output of .server debug

**Comment by PkllonG** [comment]
Today I also had an abnormal increase in CPU usage on my server, it was 3%~8%, today it was 21%~30%, I restarted the worldcore and am observing....

**Comment by Zerkenn** [comment]
I just noticed the same thing today on my server when checking my grafana for my virtual machines. No one has been online the last week and my server auto restarts everyday at 3am.

Server Info:
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/88915224/3bd7cfec-686b-47b5-ae94-92fb074e6342)
VM Total CPU for last 7 days:
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/88915224/4e94d42e-d5a4-46bc-bd98-c8af0361c6dd)
HTOP:
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/88915224/25ea1bad-4ac0-4434-a1b1-a992f922615e)

The main thread usually runs around 15-20% usage. This debian 12 vm is only running azerothcore.

Something is definitely wrong...

I can provide more information if needed.

**Comment by Nyeriah** [comment]
Please check tomorrow if its still the same. It might be related to the fireworks event...

**Comment by Zerkenn** [comment]
> Please check tomorrow if its still the same. It might be related to the fireworks event...

That would make sense that there is a issue with the code for fireworks / midsummer fire festival.

**Comment by kissingers** [comment]
when finished fireworks / midsummer fire lastday(yesterday), the Shattas city are unusually stuck.

**Comment by sudlud** [comment]
The firework gameobjects (for each explosion) are despawned but probably stay in world, so it get more with each shownthat has been running.
I will update it to use the new SAI feature to remove them from world after despawn, then this should be alright for next year.

**Comment by moncat2005** [comment]
I have been following and using a version based on the combination of azerothcore and npcbots functionality. 
The latest is（ https://github.com/azerothcore/azerothcore-wotlk/commit/0c747bc92537e80fe21093a3d95af5187223f7d5 )+( https://github.com/trickerer/Trinity-Bots/commit/ab7c42d4d5caaf7638faf33d7815f92cf642be6a ）Compiled on July 1st.

After merging NPCbots and some mod functions, the CPU usage of WorldServer increased by about 5% -10% compared to native Azerothcore.
On a daily basis, the normal CPU usage of my version is around 30%, and the last 500 diffs summary value displayed on the console is as described in my post.
mean:12-15
median:11-12
percentiles:18-25,24-35,130-400

On July 3rd, some gamers reported that there has been a prolonged lag in conversations with NPCs in the game these past few days,
At this point, I checked the console and found that the last 500 diffs summary value was abnormal.
mean:**45**
median:12
percentiles:**102-120**,**105-135**,130-450

I have very few gaming friends here, so the service can only be restarted once a week.
I am unable to confirm the impact of resource costs caused by the Mid Summer Festival fireworks incident.
If it is a fireworks event triggered every midnight starting from June 22nd, which affects the CPU usage of the WorldServer service,
So last week, I should have noticed an anomaly in the last 500 diffs summary value.
However, I did not notice.

Today, I rolled back the Worldserver program and World database from June 28th to June 18th, and the abnormal phenomena of CPU usage and lag disappeared.

In addition, I also have a WorldServer corresponding to the realmd region, which I will keep running on the version of the WorldServer program and database compiled on July 1st.
I have already restarted today. 
When I have free time, I will go online and observe again.

**Comment by PkllonG** [comment]
> I have been following and using a version based on the combination of azerothcore and npcbots functionality. The latest is（ [0c747bc](https://github.com/azerothcore/azerothcore-wotlk/commit/0c747bc92537e80fe21093a3d95af5187223f7d5) )+( [trickerer/Trinity-Bots@ab7c42d](https://github.com/trickerer/Trinity-Bots/commit/ab7c42d4d5caaf7638faf33d7815f92cf642be6a) ）Compiled on July 1st.
> 
> After merging NPCbots and some mod functions, the CPU usage of WorldServer increased by about 5% -10% compared to native Azerothcore. On a daily basis, the normal CPU usage of my version is around 30%, and the last 500 diffs summary value displayed on the console is as described in my post. mean:12-15 median:11-12 percentiles:18-25,24-35,130-400
> 
> On July 3rd, some gamers reported that there has been a prolonged lag in conversations with NPCs in the game these past few days, At this point, I checked the console and found that the last 500 diffs summary value was abnormal. mean:**45** median:12 percentiles:**102-120**,**105-135**,130-450
> 
> I have very few gaming friends here, so the service can only be restarted once a week. I am unable to confirm the impact of resource costs caused by the Mid Summer Festival fireworks incident. If it is a fireworks event triggered every midnight starting from June 22nd, which affects the CPU usage of the WorldServer service, So last week, I should have noticed an anomaly in the last 500 diffs summary value. However, I did not notice.
> 
> Today, I rolled back the Worldserver program and World database from June 28th to June 18th, and the abnormal phenomena of CPU usage and lag disappeared.
> 
> In addition, I also have a WorldServer corresponding to the realmd region, which I will keep running on the version of the WorldServer program and database compiled on July 1st. I have already restarted today. When I have free time, I will go online and observe again.

你现在就是用最新的提交，它也不卡，现在说的是，昨天有一个游戏事件造成的卡，事件ID 72，持续18个小时

**Comment by moncat2005** [comment]
@PkllonG 多谢，我找到这个7/4的烟花事件了，我误以为谈论的是6/22开始的仲夏火焰节的事件。
如果真是这个事件引发，那么在这个事件结束之前，即使服务重启应该也是无效的。
我昨天下午5点重启后一开始看资源似乎恢复正常了，但晚上9点就有玩友反馈出现严重卡顿了。
我7/5上午查看控制台依然是严重卡顿的数值，说明这个事件触发后的资源占用不会自动收敛。

我这边开了二个区域，保留了7/1编译的版本，还有一个回滚到6/18了，跑一个晚上明天就知道罪魁祸首是不是这个事件了。

**Comment by Zerkenn** [comment]
Next day update: The issue resolved after my daily 3am restart. It appears fore sure to be related to the firework spectacular / fire festival.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/88915224/bac291f9-3c0a-4499-9980-a62c1d887106)

**Comment by moncat2005** [comment]
Confirmed.
The increase in CPU usage of the Worldserver process this time is caused by game_event. eventEntry=72 (Fireworks Spectacular).
The CPU usage and lag caused by this event will not automatically converge and release with the expiration of the event, and must be restarted to recover.

Thank you all for your support and analysis!

**Comment by sudlud** [comment]
Thanks for conforming this, I will provide a fix before this event goes live again next year.

**Comment by Kitzunu** [comment]
I love this community, you guys are awesome. Good job
