### ISSUE TITLE
User-defined SQL functions/procedure in SQL updates

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1927]
We have a problem with defining sql FUNCTIONs or PROCEDUREs inside our sql updates.

The main issues are the following:

- it will cause a failure, becase all SQL update are currently being wrapped inside a PROCEDURE and sql does not allow to define nested FUNCTIONS/PROCEDURES and fails with the following:

```
ERROR 1357 (HY000) at line 10204: Can't drop or alter a FUNCTION from within another stored routine
```
- our travis pipeline will **NOT** detect this issue in the PR, but it will fail only after it's merged on master
-----------------
So we need a way to solve this issue, either

A) ( Ideal solution ) Find a way to make sql functions work, but I currently don't know how.

B) Find a way to make travis fail the PR pipeline when sql functions/procedures are present

C) ( What we should do until we implement A or B ) Just do not allow contributors to use sql functions/procedures inside the sql updates. However this solution is not the best because we have to manually check it. Most of PRs will not have sql functions anyway, but it can always happen.

CC: @Yehonal @sluggor

**Comment by BarbzYHOOL** [comment]
@Rochet2 @Deku :pray:

**Comment by Deku** [comment]
For B you could use a regex to try the contents of the SQL files

**Comment by Yehonal** [comment]
B can be done running the script that converts the pending sql in normal updates before running the database setup in travis

I think that B & C together can be a good workaround. 

There's no way to use nested procedures/function, the alternative to allow users to use mysql functions should be to rewrite our migration system using another language instead of mysql itself

**Comment by sluggor** [comment]
If understand this correctly, the SQL that gets pushed out from contributors is eventually run from within a SQL function, so if contributors use functions, they are nested and therefore illegal?

That being the case, it's completely fair just to say no functions allowed. In my own case, I can rewrite my SQL without functions, just need a little time to get it all refactored.

**Comment by FrancescoBorzi** [comment]
@sluggor yes, you understood correctly. Your old commit is fine because I've fixed it, but we should keep in mind this for future.

**Comment by sluggor** [comment]
Oh, cool. Thanks.

**Comment by FrancescoBorzi** [comment]
this issue has been resolved by @locus313  and can now be closed 🎉
