### ISSUE TITLE
Life Tap Tooltip Inaccuracy

### ISSUE THREAD

**Issue by Trus3683** [azerothcore/azerothcore-wotlk#19289]
### Current Behaviour

Life Tap tooltip incorrectly describes health:mana ratio (taking into account spell power/shadow power scaling). Shows to take more health and give less mana, but appears to function correctly.

Noticed this behavior on both local server and ChromieCraft

### Expected Blizzlike Behaviour

Tooltip should describe exact amount of health taken and exact amount of mana given after spell power/shadow power scaling. Spell appears to function correctly, but tooltip description is inaccurate.

### Steps to reproduce the problem

1. Log into a warlock.
2. Look at Life Tap tooltip.
3. Cast Life Tap, and compare tooltip to reality.

### AC rev. hash/commit

Using MySQL version: 101106
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.1.0-22-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
PlayerbotsDatabase queue size: 0
> List enable modules:
- mod-account-mounts
- mod-ah-bot
- mod-no-hearthstone-cooldown
- mod-playerbots

### Operating system

Debian

### Custom changes or Modules

- mod-account-mounts
- mod-ah-bot
- mod-no-hearthstone-cooldown
- mod-playerbots

**Comment by Tereneckla** [comment]
The tooltip of lifetap is entirely client side
