### ISSUE TITLE
[Quest] Memories of Stormhoof

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1928]
Memories of Stormhoof

##### SMALL DESCRIPTION:

No roleplay after talking to Stormhoof when you select 'I am sorry to disturb your rest, chieftan....'

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Stormhoof should be having roleplay/convo with you like in this video: https://www.youtube.com/watch?v=RP4TyCvCxos

##### CURRENT BEHAVIOUR:

No roleplay after talking to Stormhoof when you select 'I am sorry to disturb your rest, chieftan....'
Wowhead: https://www.wowhead.com/quest=13037/memories-of-stormhoof
How the quest should work: https://www.youtube.com/watch?v=RP4TyCvCxos

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fly to frostloe deep
2. Talk to Stormhoof
3. Choose 'I am sorry to disturb your rest, chieftan....'

##### EXTRA NOTES:

This quest was bugged in TrinityCore but fixed.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5bfbb9f

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Thanks for report. Already updated, can you try referenced PR @spinzaku
