### ISSUE TITLE
[Quest] In Memoriam

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1929]
In Memoriam

##### SMALL DESCRIPTION:

Horn Fragment not spawning

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Horn Fragment should spawn like in this video:  https://www.youtube.com/watch?v=jnXWpniDw1I

##### CURRENT BEHAVIOUR:

Horn Fragment not spawning.
Wowhead: https://www.wowhead.com/quest=12975/in-memoriam
How the quest should work: https://www.youtube.com/watch?v=jnXWpniDw1I

##### STEPS TO REPRODUCE THE PROBLEM:

1. Talk and get quest from King Jokkum
2. Go to 72,47 to find Horn Fragment

##### EXTRA NOTES:

Also tested with two players, haven't both same problem.
![unknown](https://user-images.githubusercontent.com/18629476/58763556-a913ad00-858e-11e9-9202-2f456cb02fe7.png)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5bfbb9f

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Also, updated. Could you please try the fix? Thanks
