### ISSUE TITLE
[Quest] EVIL DRAWS NEAR - Terokkar Forest [Ally]

### ISSUE THREAD

**Issue by Thurin93** [azerothcore/azerothcore-wotlk#193]
**Description**:The quest is descrived here -> http://www.wowhead.com/quest=10923/evil-draws-near#comments <- You have to loot 20 Doom Skulls, then you have to go inside a circle 
![cerchio](https://cloud.githubusercontent.com/assets/16744874/19626956/25e89dea-993d-11e6-9d0a-48df0068f4d7.PNG) The one in the screenshot, then use the Dread Relic provided and summon the drake     Teribus the Cursed  and slay it.

**Current behaviour**: Once you kill the npc, you can't reward the quest  from Oakun even if it appears to be complete.

**Expected behaviour**: It should be possible to reward the quest.

**Steps to reproduce the problem**:
1. Just follow the quest as it is.

**Branch(es)**: master 

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/8eb135e5456acebf44108f01bbee67fb07a4a317

**Operating system**:  

**Modules**: duel reset

**Other Customizations**: Crossfaction
##

**Comment by talamortis** [comment]
so do they drop the doom skulls or is that the bug?

**Comment by Thurin93** [comment]
I Think I explained bad. The doom skulls has been looted correctly. the problem is that when you kill Teribus, the quest sounds to be completed, but Oakun (the npc whom starts and ends the quest) has a Grey "?" on his head so the quest cannot be consigned. The only things you have to do are loot these 20 doom skulls (who drops correctly) and kill Teridus.

**Comment by talamortis** [comment]
ok thanks i think i found the problem, just testing now

**Comment by talamortis** [comment]
Fixed, will be doing PR in a second :)

**Comment by talamortis** [comment]
@Thurin93 could you please test and let me know if it works? thanks

**Comment by Thurin93** [comment]
@talamortis Sorry for the time. I just tested your fix and now Teribus stays in the air, so it is impossible to hit him, even with spells like Fireball.

**Comment by talamortis** [comment]
@Thurin93 hmm strange seems to work on my core, that is with my fix can anyone else please test?
![untitled](https://cloud.githubusercontent.com/assets/6143065/19663023/e6262db2-9a31-11e6-9374-17d264042e24.png)

**Comment by Blumfield** [comment]
@talamortis your fix works fine for me, althought I suspect the mob sometime doesn't land(needs to be confirmed)

**Comment by talamortis** [comment]
I will check the smartai script tomorrow afternoon after i finish work

**Comment by ShinDarth** [comment]
@talamortis are you running azerothcore with both VMAPS/MMAPS enabled?

**Comment by talamortis** [comment]
@shin yes im using both + mmaps

**Comment by Blumfield** [comment]
mmaps? I haven't seen an option to enable it in the configuration file

**Comment by talamortis** [comment]
@Blumfield oh yeah xD ive just saw, some reason i have mmaps in my data folder lol

**Comment by talamortis** [comment]
recompiled my core and Database retested with my fix, works fine NPC still has not errored on me.
