### ISSUE TITLE
[Quest] At The Enemy's Gates

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1932]
At The Enemy's Gates

##### SMALL DESCRIPTION:

Cannot mount Argent Horses

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once the argent lance is equipped the argent horses should be mountable

##### CURRENT BEHAVIOUR:

Wowhead: https://www.wowhead.com/quest=13855/at-the-enemys-gates
Argent Lance already equipped but can't mount any of the Argent Horses
Video of the bug: https://youtu.be/bCkC2N-ITiE

##### STEPS TO REPRODUCE THE PROBLEM:

1. Talk to Airae Starseeker and get At The Enemy's Gates quest
2. Equip Argent Lance
3. Try to mount Argent Horses

##### EXTRA NOTES:

A couple of my players tested having the same bug on my live server. One of them was able to record a video of the bug: https://youtu.be/bCkC2N-ITiE

Current solution: kill the mobs with your character - (very hard) not doable

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5bfbb9f

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
We already closed same issue like that 
https://github.com/azerothcore/azerothcore-wotlk/issues/1877
Actually i can't reproduce it. I'm able to mount up when having equiped lance. Will leave this open until confirmation from someone else

**Comment by spinzaku** [comment]
Well it's a real bug. Please check the video if you haven't seen. Maybe there's something causing this bug. Module perhaps?

**Comment by Stoabrogga** [comment]
I can confirm this issue. If you enter the Court of Bones _without_ a lance equipped you cannot mount the Stabled Campaign Warhorses, even if you equip a lance while being in the Court of Bones. If you enter the area with a lance already equipped you will be able to mount the horses.

**Comment by BarbzYHOOL** [comment]
ty for clearing this out stoabrogga, issue authors should be more precise

**Comment by spinzaku** [comment]
> ty for clearing this out stoabrogga, issue authors should be more precise

What the heck is your problem? you should be glad people like me are helping and posting current bugs and issues of this emulator. I even provided a video on the bug. You don't even help people who are new to the emulator. Not everyone has instant knowledge in everything.

**Comment by spinzaku** [comment]
If you can't even appreciate authors issuing bugs. Then no wonder why we have so few people people contributing or posting issues

**Comment by spinzaku** [comment]
> I can confirm this issue. If you enter the Court of Bones _without_ a lance equipped you cannot mount the Stabled Campaign Warhorses, even if you equip a lance while being in the Court of Bones. If you enter the area with a lance already equipped you will be able to mount the horses, even if you then switch to another weapon, which is also not correct.
> 
> I think this has to be related to the area phasing in and out.

Thank you. makes sort of sense now

**Comment by Stoabrogga** [comment]
There's a very old issue that's still open on TC describing exactly the same problem:
https://github.com/TrinityCore/TrinityCore/issues/20935

**Comment by Stoabrogga** [comment]
I think I've found a way to fix this via PR #1936.

**Comment by BarbzYHOOL** [comment]
@spinzaku i saw your shitty comments, last warning
