### ISSUE TITLE
Connection Issue Report for AzerothCore

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#19330]
### Current Behaviour

Problem Description:
I am currently experiencing difficulties when trying to connect to the AzerothCore server. The problem frequently occurs when the server reaches between 75 and 80 users online. Below are the symptoms and actions taken so far:
Symptoms:

Possible Cause:
We believe there might be an issue with the database connection since we do not see any problems with the internet connection. We also do not observe high resource consumption, with network usage at 5%. We have increased the number of connections to the database and similar adjustments seem to improve the situation, but we do not understand what the exact error could be.

    After entering the password, the client remains in the "connecting" state for an extended period.
    Occasionally, the client shows "connection accepted" but still takes a significant amount of time to load the character selection screen.

Steps Taken:

    I originally experienced this issue on Windows. To try to resolve it, I switched to Linux.
    However, the problem persists on the new platform, suggesting that the issue is not specific to the operating system.

### Expected Blizzlike Behaviour

The client should quickly move past the "connecting" state and load the character selection screen without significant delay, regardless of the number of users online.

### Steps to reproduce the problem

I originally experienced this issue on Windows. To try to resolve it, I switched to Linux.
However, the problem persists on the new platform, suggesting that the issue is not specific to the operating system.

### AC rev. hash/commit

Update time diff: 1ms. Last 500 diffs summary:
- Mean: 3ms
- Median: 2ms
- Percentiles (95, 99, max): 9ms, 9ms, 10ms
Using SSL version: OpenSSL 3.0.13 30 Jan 2024 (library: OpenSSL 3.0.13 30 Jan 2024)
Using Boost version: 1.83.0
Using CMake version: 3.28.3
Using MySQL version: 80037
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.0-36-generic
Worldserver listening connections on port 8086
Realmlist (Realm Id: 2) configured in port 8086
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_texts.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 38
WorldDatabase queue size: 0
> List enable modules:

### Operating system

ubuntu 24

### Custom changes or Modules

mod-anticheat, mod-breaking-news-override, mod-cfbg, mod-learn-spells, mod-transmog

**Comment by PkllonG** [comment]
CharacterDatabase queue size: 38

**Comment by kambire** [comment]
> `CharacterDatabase queue size: 38` The error is here. Never had so many queues on my server

Sorry, I don't understand where the error is, in the database or in a CPP file. I can't click on what you sent me
