### ISSUE TITLE
item_level under table access_requirement does not work

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1934]
item_level under table access_requirement does not work

##### SMALL DESCRIPTION:

item_level under table access_requirement does not work

##### EXPECTED BLIZZLIKE BEHAVIOUR:

when setting an item level, if the player does not have that item level he cannot enter instance

##### CURRENT BEHAVIOUR:

item_level under table access_requirement does not work, players can enter naked with no gear in bags etc

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Set item level of instance (ulduar for example) to 200
2.  Enter raid on naked character
3.  No message displays, characters can enter naked with no issues

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

6480f99ca2f4+

##### OPERATING SYSTEM:

UBUNTU LINUX 16.04

**Comment by disclosurez** [comment]
example sql to reproduce:

REPLACE INTO `access_requirement` VALUES (603, 0, 80, 0, 220, 0, 0, 0, 0, 0, NULL, 'Ulduar Raid entrance');

**Comment by FrancescoBorzi** [comment]
@disclosurez FYI:

![image](https://user-images.githubusercontent.com/75517/58767491-399cbe00-858c-11e9-9561-729f6781dbb5.png)

**Comment by disclosurez** [comment]
@Viste does not fix, can still enter instance without ilvl

**Comment by Viste** [comment]
OK i split PRs tonight or later

**Comment by disclosurez** [comment]
Bump

**Comment by mirlol** [comment]
Bump. Get the same problem. Even nexus has default 180ilvl on 5hc and still can enter naked.

**Comment by Kitzunu** [comment]
This is wrong.

"ilvl" in this table ONLY alters the requirement you need to queue with the Dungeon Finder Tool.
Entering dungeons via the portal under-geared is totally intended.

**Comment by BarbzYHOOL** [comment]
haha nice finding kitzunu, i effectively discovered this yesterday and I might push an update to allow it to work with the instance portals

Note: It's intended because it's blizzlike, but in terms of documentation, coding and customization (one of the concepts behind AC), it's not logical
