### ISSUE TITLE
[Quest] The Hunter and the Prince

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1937]
Quest ID: 13400

https://www.wowhead.com/quest=13400/the-hunter-and-the-prince

At the moment, once you take quest, there's no object "Bloodstained Stone" spawned near.
I tried with adding manually and object works, quest and AI works pretty good as well.

Problem i have with fix is that i'm unable to add condition for some weird reason, and object is visible to everyone, so players can just get there and click to trigger event.

How to check:

1. Create Alliance character
2. Level up your self to level 75+
3. .quest add 13400
4. .tele Icecrown

There's also horde version, Quest ID 13361

Video how object is supposed to be spawned:

https://www.youtube.com/watch?v=jM-shMM8L2A

Hash: f8167d4

**Comment by GMKyle** [comment]
@Knindzagxg 
Tested with ali player, as soon as you take in the quest from de npc the Bloodstained Stone are spawn in .go xyz 6331.72 2360.05 477.274 don't use .quest add

**Comment by Naxxramas-Server** [comment]
Confirmed and with the manually add , after that when you kill the pnj with illidan , the quest isn't validate.

**Comment by Knindzagxg** [comment]
That's weird Kyle, cause i checked whole zone for object and doesn't appear at all.

**Comment by GMKyle** [comment]
check mouse pointer, also be aware that will despawn in a few seconds (less than a minute)

![Bloodstained Stone](https://user-images.githubusercontent.com/25353073/58896968-322d0000-86c5-11e9-9f0d-1cf39ee82324.png)

**Comment by Knindzagxg** [comment]
I will re-check again, just posting really weird issue again.
