### ISSUE TITLE
(Creature): Vhel'kur is visible to any player.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19384]
### Current Behaviour

Vhel'kur at the Netherwing Ledge in Shadowmoon Valley is permanently visible.

### Expected Blizzlike Behaviour

He should only be visible with the Spectrecles.

### Source

Wowhead comments

### Steps to reproduce the problem

1. `.go c id 21801`
2. Observe that you can see him.

### AC rev. hash/commit

70eb920b108786020dd6a63a6b5f2b43a1b0d893

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by avarishd** [comment]
https://github.com/user-attachments/assets/f159018c-31e9-4f17-9de3-46b02851e269

**Comment by heyitsbench** [comment]
CC exclusive issue then, I guess.

**Comment by avarishd** [comment]
Can move the SAI to tempalte_addon if you want. That usually fixes it, on CC.
