### ISSUE TITLE
boss_hodir.cpp Script is bugged, SPELL_ICE_SHARDS_SMALL: is casting too much [$50]

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1938]
boss_hodir.cpp Script is bugged, SPELL_ICE_SHARDS_SMALL: is casting too much

##### SMALL DESCRIPTION:

boss_hodir.cpp Script is bugged, SPELL_ICE_SHARDS_SMALL: is casting too much

##### EXPECTED BLIZZLIKE BEHAVIOUR:

    SPELL_ICE_SHARDS_SMALL              = 62457,
Should not be casting as much as it currently is, this is unplayable for raids as they get raped by continual falling ice.

##### CURRENT BEHAVIOUR:

    SPELL_ICE_SHARDS_SMALL              = 62457,

is casting too much, this should be casting a lot less than it is.
I would suggest adding a delay to this cast / script:

switch( spell->Id )
            {
                case SPELL_ICE_SHARDS_SMALL:
                case SPELL_ICE_SHARDS_BIG:
                    DoAction(1);
                    break;
}

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Run Hodir In Ulduar
2.  Profit

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

latest

##### OPERATING SYSTEM:

ubuntu 16.04

##### MODULES:

none

**Comment by FrancescoBorzi** [comment]
Please do NOT just put "latest" as with time it will no make sense and we won't have trace about when the bug was actually found. Please put your actual commit hash value.

**Comment by Viste** [comment]
`
is casting too much, this should be casting a lot less than it is.
I would suggest adding a delay to this cast / script `
Some proofs ? Or its just in your view?

**Comment by Selyria** [comment]
So it's hard to tell if it's going too fast with the ice blocks falling from the ceiling.

Because in the 10 man raid it always hits another player.


AzerothCore Video https://youtu.be/5EgVepiPtnA

Offi Video https://www.youtube.com/watch?v=Hcl4tz-XQFo

AzerothCore rev. f47c2d2+ 2019-06-03 05:30:11 +0000 (master branch) (Win64, Release)

**Comment by disclosurez** [comment]
> 
> 
> So it's hard to tell if it's going too fast with the ice blocks falling from the ceiling.
> 
> Because in the 10 man raid it always hits another player.
> 
> I'd say it's faster on AC than offi
> 
> AzerothCore Video https://youtu.be/5EgVepiPtnA
> 
> Offi Video https://www.youtube.com/watch?v=Hcl4tz-XQFo
> Offi Video https://www.youtube.com/watch?v=d8Wqg5eP6V8 From the point of view of a distance fighter.
> 
> AzerothCore rev. [f47c2d2](https://github.com/azerothcore/azerothcore-wotlk/commit/f47c2d2f8c232aee115ceeaae167591dca92ba2c)+ 2019-06-03 05:30:11 +0000 (master branch) (Win64, Release)

vid is 25man

**Comment by disclosurez** [comment]
sorry guys forgot to mention, this bug only affects 10 man, 25 man is fine

**Comment by Selyria** [comment]
> sorry guys forgot to mention, this bug only affects 10 man, 25 man is fine

okay, i was in the 25-man raid now, too.

The icicles are falling as fast as in 10 man

**Comment by disclosurez** [comment]
> The icicles are falling as fast as in 10 man

yes needs to fall slower in 10 man that is the problem

**Comment by Selyria** [comment]
> > The icicles are falling as fast as in 10 man
> 
> yes needs to fall slower in 10 man that is the problem

Okay, so it seems like there's gonna be a countdown in between to stop the ice.

In the 10 Man Raid Here good to see https://www.youtube.com/watch?v=VZoAha-2Elc

**Comment by Viste** [comment]
@Selyria thx for proofs

**Comment by Shard-MW** [comment]
It should have 4sec delay, according the videos you sent

**Comment by solidmaxtor** [comment]
In my server players no report any problems with this shards, raids inside everyday in Ulduar.

**Comment by Darkon47** [comment]
Since the fix was merged in, could we mark this as fixed?

**Comment by disclosurez** [comment]
> 
> 
> Since the fix was merged in, could we mark this as fixed?

yes fixed

**Comment by poszer** [comment]
Where is fix merged? I can't see it on master. There is just your PR opened @Darkon47 https://github.com/azerothcore/azerothcore-wotlk/pull/2050
