### ISSUE TITLE
Issue with ticket response

### ISSUE THREAD

**Issue by patphoenix** [azerothcore/azerothcore-wotlk#19390]
### Current Behaviour

It displays a random, garbled response that is not what is typed in as the ticket response

![ticketresponse](https://github.com/user-attachments/assets/042b3c92-55f2-40ae-8961-3044709ba364)

The above is just random text that appears and is not what was typed

### Expected Blizzlike Behaviour

It should display the text that was inputted in the "ticket response" command rather than some random text

### Steps to reproduce the problem

1. Create a ticket
2. Issue the command ticket response appendln ticketid ticketresponsehere
3. Issue command ticket complete ticketid
4. See the response is garbled

### AC rev. hash/commit

Connection peak: 2.
Server uptime: 1 hour(s) 11 minute(s) 36 second(s)
Update time diff: 4ms. Last 500 diffs summary:
|- Mean: 9ms
|- Median: 7ms
|- Percentiles (95, 99, max): 20ms, 23ms, 38ms
Using SSL version: OpenSSL 1.1.1w  11 Sep 2023 (library: OpenSSL 1.1.1w  11 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100523
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.10.0-11-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-playerbots

### Operating system

Debian 11

**Comment by patphoenix** [comment]
hey there, I have pulled the latest version and built it, but this issue still exists on my end, it does not appear to be fixed.

sorry I'm new to this and maybe I'm missing something, but just wanted to let you know in case anything further needs to be done on it

**Comment by Kitzunu** [comment]
please send the output of .server debug and the entire command you are trying to send ex. `.ticker response appendln some text`

**Comment by patphoenix** [comment]
Entire command: `.ticket response appendln 8 This is a test response` (8 is the ID of the test ticket)

Here is my server debug:

```
Server uptime: 27 second(s)
Update time diff: 10ms. Last 361 diffs summary:
|- Mean: 39ms
|- Median: 11ms
|- Percentiles (95, 99, max): 47ms, 138ms, 5825ms
Using SSL version: OpenSSL 1.1.1w  11 Sep 2023 (library: OpenSSL 1.1.1w  11 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100523
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.10.0-30-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-playerbots
```

**Comment by Kitzunu** [comment]
you are missing the first lines of the server debug output

**Comment by patphoenix** [comment]
Hi, apologies for that, is this better?

AzerothCore rev. 05c9a96ba99c 2024-07-11 12:32:13 +0800 (Playerbot branch) (Unix, Release, Static)
Connected players: 1. Characters in world: 468.
Connection peak: 1.
Server uptime: 1 minute(s) 18 second(s)
Update time diff: 6ms. Last 500 diffs summary:
|- Mean: 16ms
|- Median: 11ms
|- Percentiles (95, 99, max): 36ms, 39ms, 53ms
Using SSL version: OpenSSL 1.1.1w  11 Sep 2023 (library: OpenSSL 1.1.1w  11 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100523
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.10.0-30-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-playerbots

**Comment by Kitzunu** [comment]
2024-07-11 your core is 7 days old and the fix was merged 3 days ago
