### ISSUE TITLE
stack size

### ISSUE THREAD

**Issue by Tntdruid** [azerothcore/azerothcore-wotlk#1940]
##### SMALL DESCRIPTION:

Hello,

Any way to change the trade gods stack size?

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

**Comment by FrancescoBorzi** [comment]
this is not a bug and does not belong here, please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
