### ISSUE TITLE
NPC Issue (Prolly core wise) Potential memory leak

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1941]
Hey,

Was checking quest The Fate of Bloodbane for phases (13164) and once i finally reached it there is really really weird issue.

There were a lot of NPC's -> Multi spawns.
They are used for event to fight other friendly NPC's (Not working currently tho)

Tried to delete some of them cause there would be no chance to complete quest sadly, but really weird thing happen which you can see on video -> Once i deleted one, it respawn after few seconds, and it's same for every multi spawned NPC.

Check video bellow.

https://www.youtube.com/watch?v=c78DPAFWhCU&feature=youtu.be

Hash: 61f3e6a

**Comment by poszer** [comment]
:thinking:

**Comment by Knindzagxg** [comment]
It's prolly cpp cause they don't even have SAI or DB GUID

![WoWScrnShot_060419_191304](https://user-images.githubusercontent.com/27079035/58899309-e72edf00-86fc-11e9-8f2c-f1b588cc4ab8.jpg)

**Comment by Motorheadx** [comment]
try this UPDATE `smart_scripts` SET `entryorguid`='31316', `source_type`='0', `id`='0', `link`='0', `event_type`='0', `event_phase_mask`='0', `event_chance`='100', `event_flags`='0', `event_param1`='0', `event_param2`='15000', `event_param3`='15000', `event_param4`='30000', `event_param5`='0', `action_type`='11', `action_param1`='58962', `action_param2`='0', `action_param3`='0', `action_param4`='0', `action_param5`='0', `action_param6`='0', `target_type`='1', `target_param1`='0', `target_param2`='0', `target_param3`='0', `target_param4`='0', `target_x`='0', `target_y`='0', `target_z`='0', `target_o`='0', `comment`='Ebon Blade Reaper - OOC - Cast Summon Death Knight Adept' WHERE (`entryorguid`='31316') AND (`source_type`='0') AND (`id`='0') AND (`link`='0');

**Comment by FrancescoBorzi** [comment]
@Motorheadx FYI I've edited your comment, for better readability

![image](https://user-images.githubusercontent.com/75517/58909206-d12c1900-8712-11e9-8614-1d0722d652cb.png)

**Comment by Knindzagxg** [comment]
Just added SAI, forgot before.

Will see tomz about it after weekly restart of my serv.

**Comment by Knindzagxg** [comment]
Yeah, fix is fine, issues is gone.

Only need to work on that small event in future.

**Comment by Stoabrogga** [comment]
I'll look into this. The Death Knight Adepts and the Ebon Blade Reapers should battle each other, right?

**Comment by Stoabrogga** [comment]
Nevermind, I think I've found a solution: #1962
