### ISSUE TITLE
The Test of Righteousness (Paladin)

### ISSUE THREAD

**Issue by Trus3683** [azerothcore/azerothcore-wotlk#19437]
### Current Behaviour

Jordan Stilwell freezes after turning in The Test of Righteousness. NPC RP begins to craft the hammer, but does not allow the player to interact to receive it. 

### Expected Blizzlike Behaviour

Quest turnin will pop up to receive the hammer as a reward.

### Steps to reproduce the problem

Turn in The Test of Righteousness, wait. 

### Extra Notes

Final quest was still available immediately after a server restart. 

### AC rev. hash/commit

Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: zz_optional_aq_quest_nerf.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-individual-progression
|- mod-no-hearthstone-cooldown
|- mod-playerbots
|- mod-solocraft

### Operating system

Debian

### Custom changes or Modules

List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-individual-progression
|- mod-no-hearthstone-cooldown
|- mod-playerbots
|- mod-solocraft

**Comment by Kitzunu** [comment]
you are missing several lines of the server debug output. Add them
