### ISSUE TITLE
ArmorDamageModifier column in item_template

### ISSUE THREAD

**Issue by dewmguy** [azerothcore/azerothcore-wotlk#19456]
Could someone please describe how this column works, exactly?

I understand that if you add a positive integer on an armor (class 4) item, it will add "bonusarmor" stat to the item.

I believe that if you subtract a negative integer on a weapon (class 2) item, it will add either feral attack power or spell power to the item.

Is this true? is there more? if there is more, please provide details.

additionally, please provide equations or their locations for how this integer affects various stats.

I'm creating an item level calculator and having the most precise information and equations will help ensure the most accuracy possible.

**Comment by Kitzunu** [comment]
Not the place to ask questions. Use discord

**Comment by dewmguy** [comment]
Could I please get unbanned from the discord?
