### ISSUE TITLE
Feature: AccountID creation check for existing accountID's instead of AUTO_INCREMENT

### ISSUE THREAD

**Issue by Williamhb** [azerothcore/azerothcore-wotlk#19465]
### Describe your feature request or suggestion in detail

AccountID creation check for existing accountID's, instead of AUTO_INCREMENT.
Lets say i deleted 600 accounts, and still 1 remain. 
The AUTO_INCREMENT would start on accountid 602 for the next account id number, even though i deleted the 600 account's
i should start on accountID nr 2 for the new account or?

### Describe a possible solution to your feature or suggestion in detail

rewrite AUTO_INCREMENT code to check for existing accountID

**Comment by Kitzunu** [comment]
This acts as a kind of "safety" in case not everything was deleted across all tables etc. It is also a much safer way of handling new entries into the table as it can't cause any unexpected issues

If you really want to reset yours locally you could do 
```sql
ALTER TABLE tbl AUTO_INCREMENT = x;
```
