### ISSUE TITLE
[Hyjal] Incorrect Trash Wave remaining enemy counter behavior

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#19468]
https://github.com/chromiecraft/chromiecraft/issues/7224
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Been reported in Chromiecraft discord but no report created here I believe
1. The trash wave remaining character is counting mobs kills other than the intended mobs for each wave
2. This results in early termination of current wave and starting the next wave (even when there are mobs still alive and the timer for current wave has not ended yet)
3. This also leads to the counter able to reach negative numbers
4. Mobs remaining from previous wave, when killed also affect the current wave
![image](https://github.com/user-attachments/assets/562dbb28-bd3b-4c75-8df9-1581d92dbb30)

### Expected Blizzlike Behaviour

counter should only count down when mobs that compose the wave die, and the next wave/boss should only spawn when the entire previous wave is killed 

### Source

Chromiecraft discord reports from other raid groups and on two separate Hyjal raids that was participated in
An example is shown here:
https://discord.com/channels/788063059926712341/1245416476089778256/1263184913126129826

### Steps to reproduce the problem

.tele hyjalsummit
start trash waves
kill trash waves slowly allowing Shadowy Necromancer to summon minions

### Extra Notes

wasnt happening prior to these fixes being loaded onto chromiecraft https://github.com/chromiecraft/azerothcore-wotlk/compare/793f87fd61e1...42e003e54d6d

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/441fdc324f5c28c7859cb670103d93b771f80438

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by kasvati** [comment]
So currently there are two issues.
1. Counter doesn't count kills correctly (multiple subtractions)
2. Counter shouldn't carry over its state between waves.

Issue 1:
I have tried replicating the bug on my local AC installation and I wasn't successful. I asked around and none else was able to replicate it outside live raid. So probably it would be best to enable logging for the instance_hyjal.cpp so we can see what and how is manipulating the trash counter. (ie. mobs that are not supposed to be counted or multiple triggering of OnUnitDead() handler)

Issue 2:
I'm not sure if that is correct way it should behave. It would be best to have someone look at retail to see how the counter behaves. If its confirmed that its wrong then a of the counter might be in order.

**Comment by amed80** [comment]
It's related to Seed of Corruption after this PR https://github.com/azerothcore/azerothcore-wotlk/pull/19322


https://github.com/user-attachments/assets/c94ab82e-b452-4c18-b4d6-8eb8a4050a3e

**Comment by sogladev** [comment]
found what's causing, reproduced with
```
+++ b/src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
@@ -340,4 +340,4 @@ class spell_cannibalize_heal : public SpellScript
         {
-            uint32 heal = caster->CountPctFromMaxHealth(7);
-            SetHitHeal(heal);
+            // uint32 heal = caster->CountPctFromMaxHealth(7);
+            SetHitHeal(0);
```
`.go c id 17772` jaina, damage a ghoul to <300hp, put seed, rewards rep twice

dying to dot calls `Unit::Kill` https://github.com/azerothcore/azerothcore-wotlk/blob/02a05fbd4c640b33b1e03075681f169db2fb6ab2/src/server/game/Entities/Unit/Unit.cpp#L18088

`RemoveAllAurasOnDeath();` which pocs the AoE. The auras are removed before death state is updated, so the creature is alive when doing the AoE and does a second kill https://github.com/azerothcore/azerothcore-wotlk/blob/02a05fbd4c640b33b1e03075681f169db2fb6ab2/src/server/game/Entities/Unit/Unit.cpp#L14490  

zonescript is also called while the unit is still alive ?
