### ISSUE TITLE
Getting error during building

### ISSUE THREAD

**Issue by ralver** [azerothcore/azerothcore-wotlk#19474]
### Current Behaviour

I pulled fresh for git and ran './acore.sh compiler build'
During building and compiling I get the next error:

[ 93%] Building CXX object modules/CMakeFiles/modules.dir/mod-eluna/src/LuaEngine/CreatureHooks.cpp.o
/apps/azerothcore-wotlk/modules/mod-ah-bot/src/cs_ah_bot.cpp:43:41: fatal error: no matching constructor for initialization of 'std::vector<ChatCommand>' (aka 'vector<Acore::ChatCommands::ChatCommandBuilder>')
        static std::vector<ChatCommand> commandTable =
                                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:497:7: note: candidate constructor not viable: cannot convert initializer list argument to 'const std::vector<Acore::ChatCommands::ChatCommandBuilder, std::allocator<Acore::ChatCommands::ChatCommandBuilder>>::allocator_type' (aka 'const std::allocator<Acore::ChatCommands::ChatCommandBuilder>')
      vector(const allocator_type& __a) _GLIBCXX_NOEXCEPT
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:510:7: note: candidate constructor not viable: cannot convert initializer list argument to 'std::vector::size_type' (aka 'unsigned long')
      vector(size_type __n, const allocator_type& __a = allocator_type())
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:553:7: note: candidate constructor not viable: cannot convert initializer list argument to 'const std::vector<Acore::ChatCommands::ChatCommandBuilder, std::allocator<Acore::ChatCommands::ChatCommandBuilder>>'
      vector(const vector& __x)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:572:7: note: candidate constructor not viable: cannot convert initializer list argument to 'std::vector<Acore::ChatCommands::ChatCommandBuilder, std::allocator<Acore::ChatCommands::ChatCommandBuilder>>'
      vector(vector&&) noexcept = default;
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:625:7: note: candidate constructor not viable: no known conversion from 'const char [13]' to 'Acore::ChatCommands::ChatCommandBuilder' for 1st argument
      vector(initializer_list<value_type> __l,
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:487:7: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
      vector() = default;
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:575:7: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
      vector(const vector& __x, const allocator_type& __a)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:607:7: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
      vector(vector&& __rv, const allocator_type& __m)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:522:7: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
      vector(size_type __n, const value_type& __value,
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:585:7: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
      vector(vector&& __rv, const allocator_type& __m, true_type) noexcept
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:589:7: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
      vector(vector&& __rv, const allocator_type& __m, false_type)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_vector.h:653:2: note: candidate constructor template not viable: requires at least 2 arguments, but 1 was provided
        vector(_InputIterator __first, _InputIterator __last,
        ^
1 error generated.
gmake[2]: *** [modules/CMakeFiles/modules.dir/build.make:134: modules/CMakeFiles/modules.dir/mod-ah-bot/src/cs_ah_bot.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:1216: modules/CMakeFiles/modules.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2

real    0m34.808s
user    1m50.010s
sys     0m9.402s

### Expected Blizzlike Behaviour

It should be compiling

### Steps to reproduce the problem

1. git pull
2. ./acore.sh compiler build

### AC rev. hash/commit

From https://github.com/azerothcore/azerothcore-wotlk
   47ad691c9..be256e7a7  master     -> origin/master

### Operating system

Linux ...  5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

### Custom changes or Modules

root@wow-wotlk:/apps/azerothcore-wotlk/modules# ll
total 64
-rw-r--r-- 1 root root 13344 Sep 16  2022 CMakeLists.txt
-rw-r--r-- 1 root root  3066 Sep 16  2022 create_module.sh
-rw-r--r-- 1 root root  1003 Sep 16  2022 how_to_make_a_module.md
drwxr-xr-x 7 root root  4096 Apr 16  2023 mod-ah-bot
drwxr-xr-x 7 root root  4096 Apr 27 13:15 mod-aoe-loot
drwxr-xr-x 6 root root  4096 Sep 19  2022 mod-custom-login
drwxr-xr-x 7 root root  4096 Oct 25  2023 mod-eluna
drwxr-xr-x 7 root root  4096 Apr  9 00:40 mod-guildhouse
drwxr-xr-x 7 root root  4096 Oct  6  2023 mod-solocraft
drwxr-xr-x 6 root root  4096 Jul  4  2023 mod-solo-lfg
-rw-r--r-- 1 root root  1919 Sep 16  2022 ModulesLoader.cpp.in.cmake
-rw-r--r-- 1 root root   938 Sep 16  2022 ModulesPCH.h
-rw-r--r-- 1 root root   864 Sep 16  2022 ModulesScriptLoader.h

**Comment by Kitzunu** [comment]
Update your mod-ah-bot
