### ISSUE TITLE
mod-duel-reset DC in all players

### ISSUE THREAD

**Issue by shuradumau** [azerothcore/azerothcore-wotlk#1947]
I am reporting a problem that is occurring when you have the cd reset module on the server.

the problem is this, when it resets the DC server several times in all logged in accounts, there players need to log in again, this only occurs when you have multiple accounts logged in.

module: https://github.com/azerothcore/mod-duel-reset

Azerothcore rev. fa9638a1b1f+ 2019-05-29 Master (branch )  (win64, Release)

**Comment by FrancescoBorzi** [comment]
@shuradumau thanks for your report, however issues about modules should be reported in their own repository, in this case: https://github.com/azerothcore/mod-duel-reset/issues/new

also I don't understand what you mean by:

> the problem is this, when it resets the DC server several times in all logged in accounts, there players need to log in again, this only occurs when you have multiple accounts logged in.

but let's discuss it in the appropriate repo, not here.
