### ISSUE TITLE
Lord Marrowgar Bone Storm Phase

### ISSUE THREAD

**Issue by Joshmash** [azerothcore/azerothcore-wotlk#19476]
### Current Behaviour

While in Bone Storm Phase he's targeting random player and charges to him

### Expected Blizzlike Behaviour

While in Bone Storm Phase he must target player that farthest and charge him

### Source

https://wowpedia.fandom.com/wiki/Lord_Marrowgar this site says that he always charges random player but we can find videos that Lord Marrowgar charges only farthest players:
https://youtu.be/eUeHJwI4JKc?si=1bwxZ5WhYEuPOA6w 10hm
https://youtu.be/ppmCtJhsK4Y?si=kS-f8zzSiJ06Uwyb 25hm
Sometimes he just stops mid charge but i guess it was a bug

### Steps to reproduce the problem

1. Group with 3+ people 
2. Start fight with Lord Marrowgar
3. See the result

### AC rev. hash/commit

AzerothCore rev. 2f49d77a0bc 2024-07-22 16:28:57 +0300 (TS branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 22.04.4 LTS

### Custom changes or Modules

- mod-cfbg
- mod-congrats-on-level
- mod-duel-reset
- mod-globalchat
- mod-individual-xp
- mod-transmog

**Comment by heyitsbench** [comment]
> While in Bone Storm Phase he must target player that farthest and charge him

No, based on Wrath Classic testing he does a coin flip and targets one of the two farthest players away and charges, not always the farthest.

**Comment by Joshmash** [comment]
Does he gonna get changed from random to farthest?

**Comment by heyitsbench** [comment]
> Does he gonna get changed from random to farthest?

🤷‍♀️
