### ISSUE TITLE
Announcements in Alterac Valley isn't showing the names properly

### ISSUE THREAD

**Issue by noisiver** [azerothcore/azerothcore-wotlk#19483]
### Current Behaviour

The announcer in Alterac Valley uses `{}` instead of names in the yells.

### Expected Blizzlike Behaviour

It should say the names of points, towers, alliance, horde etc

### Steps to reproduce the problem

1. Enter Alterac Valley
2. Capture a tower or graveyard
3. Watch the announcements

### Extra Notes

![bild](https://github.com/user-attachments/assets/52cbe7bf-bc16-4461-aa4d-216f3380a675)

### AC rev. hash/commit

339506cbedab8608f97eeb985f326a14260fbc0d

### Operating system

Ubuntu 22.04

### Custom changes or Modules

Tested without any

**Comment by Kitzunu** [comment]
I will check it. Probably uses worldpacket to send the message which doesnt work with fmt format.

**Comment by Kitzunu** [comment]
Though, it's strange that it's not using creature_text
