### ISSUE TITLE
[Item in Dungeon] If use Saronite Bomb in Malygos  the platform is destroy - Video

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#1948]
If use Saronite Bomb in Malygos the platform is destroy

Item: Saronite Bomb
https://www.wowhead.com/item=41119
Where:
Eye of Eternity - Malygos Raid 10/25

Possible gameobject related entry 193958 and 193960 
"The Focusing Iris"
tipe 10 GAMEOBJECT_TYPE_GOOBER
data0: open (LockId from Lock.dbc)
data2: eventID (event_script id)
data3: Time in ms before the initial state is restored
ScriptName: go_the_focusing_iris

STEPS TO REPRODUCE THE PROBLEM:
CHeck video

Test in last master
with and without modules
Ubuntu 16.04

Video
https://www.youtube.com/watch?v=1n7MmaWs2O8

**Comment by Selyria** [comment]
Okay, the bug is really mega.

Good thing you found him.

**Comment by talamortis** [comment]
Will assign myself but will look into this when I get a little more time.
