### ISSUE TITLE
[boss] zul gurub

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#195]
Description: After a wipe, Bloodlord Mandokir (ID:11382) is supposed to position himself where the Vilebranch Speaker (ID:11391) was prior to killing him to trigger the encounter. The boss has to reset and place himself below the stairs.
Also, a minor bug with him yelling "I'm keeping my eye on you, player!" when casting Threatening Gaze (ID:24314) but he is supposed to yell "player! I'm watching you!".

Current behaviour: When a wipe occur, Bloodlord Mandokir starts to run away from his platform and goes outside his "room" and starts running around the next zone only to come back again to despawn.
He is also yelling the wrong thing when casting Threatening Gaze.

Expected behaviour: Upon a wipe he should reset the encounter and run to the bottom of the stairs. Meaning he should reset his health back to full and respawn his mount, Ohgan (ID:14988), which he then mounts and the fight can start again when attacked.

Steps to reproduce the problem:

Kill the Vilebranch Speaker at the bottom of the stairs.
Attack Bloodlord Mandokir.
Die.
Wait to see him run around and eventually despawn or release and run back inside and he has despawned.
##

**Comment by talamortis** [comment]
Looking into it now :)

**Comment by talamortis** [comment]
![Text Fix](https://cloud.githubusercontent.com/assets/6143065/19628724/1801ac16-995c-11e6-9a3b-b2671114cf56.png)

Ok so text is now fixed just working on the movement
