### ISSUE TITLE
Fields inconsistency and Safe Deposit achievement

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#19510]
### Current Behaviour

The bankSlots field in the characters table should always match the criteria 752 in the character_achievement_progress table. Inconsistency between these two fields leads to the impossibility of acquiring the achievement https://www.wowhead.com/wotlk/achievement=546/safe-deposit

### Expected Blizzlike Behaviour

/

### Steps to reproduce the problem

1. Set `bankSlots` to 7 in `characters`
2. Set criteria `752` to any other value ex. 3 in `character_achievement_progress`
3. You'll have 7 bank slots unlocked, but your achievement criteria is 3, if you want to acquire `Safe deposit` achievement you can't because you can't buy any other slots because your `bankSlots` its already 7

**This problem should not appear on a fresh server, but when `bankSlots` was added, i think all characters on old servers got all of their items from bank by in-game mail system, and `Safe deposit` achievement locked untill player reacquire bank slots back which fix the inconsistency and from there this bug will never appear again, that makes me think thats not a real bug, and it can be fixed with a simple query**

Quick query fix
`
UPDATE characters c
JOIN character_achievement_progress cap
 ON c.guid = cap.guid
SET c.bankSlots = cap.counter
WHERE cap.criteria = 752;
`

### Other fix ideas

If criteria `752`  value exists and is more than > 0 update character value `bankSlots` at login
If bankSlots is more than 0, and criteria doesnt exists create criteria `752` with that value 

### AC rev. hash/commit

AzerothCore rev. 17d6166+ 2024-07-25 23:52:41 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 12

**Comment by TheSCREWEDSoftware** [comment]
The achievement exists there when you acquire the 7th slot by buying, if it you already have the 7th slot or change the char to have the 7th slot, the only way to get that achievement by manually adding it. I will be closing this with the tag on top.
