### ISSUE TITLE
The Binding (Warlock Felhunter Pet Quest): broken

### ISSUE THREAD

**Issue by gruberchris** [azerothcore/azerothcore-wotlk#19533]
### Current Behaviour

See this previous issue for more context about this quest chain:

https://github.com/azerothcore/azerothcore-wotlk/issues/6137

When I do this quest, the npc quest giver does seem to do his actions but the Felhunter create never spawns and all I can do is abandon the quest.

I see in my server logs that when this happens it makes a SmartScript error log that says "Action target Creature(entry: 1860) is not using SmartAI, action skipped to prevent crash."

### Expected Blizzlike Behaviour

The Felhunter pet creature should span and aggro on to my warlock and then I fight it to win the quest rewards.

### Source

See this prior issue as it accurately linked how this quest should work.

https://github.com/azerothcore/azerothcore-wotlk/issues/6137

### Steps to reproduce the problem

1. Turn in quest requirements to quest giver.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/0e1afaa76

### Operating system

Linux docker container using the provided docker compose script.

**Comment by kasvati** [comment]
I couldn't confirm, on my installation quest works properly altho you need to start it manually for RP to happen.

02a05fb

**Comment by gruberchris** [comment]
Interesting. The commit I referenced is from this repository but it was from the merge mod-playerbots uses. I wonder if it's a DB issue from that project somehow.

**Comment by gruberchris** [comment]
Actually, this quest is working fine. I simply wasn't doing what the quest said. I expected the felhunter creature would spawn automatically. Of course, I had to click the tome used by this quest. I will close this issue.
