### ISSUE TITLE
Kael'thas's final phase transition still allows him to be attacked.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19548]
### Current Behaviour

Currently, when Kael'thas enters his final phase, he removes his attackable unit flag. However, if players were attacking him before the flag was removed, they'll continue to attack him during the transition.

### Expected Blizzlike Behaviour

The attackable unit flag being removed from a unit should mean the any units attacking that unit should have their attacks be halted.

### Source

Assumption

### Steps to reproduce the problem

1. Enter Tempest Keep.
2. Make your way to Kael'thas.
3. Get to his final phase transition.
4. Observe you can attack him despite not being able to attack him.

### Extra Notes

This is likely a generic issue with any instance of the attackable unit flag being removed, Kael'thas is just a good example of it.

### AC rev. hash/commit

ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Grimdhex** [comment]
I couldn't assign, but I'm on the issue (maybe other because I've see several issue in the script and I've sniff some stuff on live server).
