### ISSUE TITLE
Akama wrong text when fighting minions

### ISSUE THREAD

**Issue by ASBaj** [azerothcore/azerothcore-wotlk#19550]
### Current Behaviour

During the Illidan fight, Akama says "Be wary, friends. The Betrayer meditates in the court just beyond" when going to fight the minions.

### Expected Blizzlike Behaviour

Akama should say "I will deal with these mongrels! Strike now, friends! Strike at the Betrayer!".

### Source

https://www.youtube.com/watch?v=9PweqV5BU4k

### Steps to reproduce the problem

1. Engage Illidan.
2. Fight him until he summons minions.
3. Observe Akama text.

### AC rev. hash/commit

fcdc50306ff8734f6f56d22db54862c173879f10

### Operating system

Windows Server 2022

**Comment by heyitsbench** [comment]
This should be fixed with the recent rewrite.
