### ISSUE TITLE
Trigging invulnerability during the Illidan fight phase 2 when soloing him resets the encounter

### ISSUE THREAD

**Issue by ASBaj** [azerothcore/azerothcore-wotlk#19552]
### Current Behaviour

Casting Divine Shield, or presumably any invulnerability spell, during Phase 2 of the Illidan fight when soloing him causes the encounter to reset, except Akama does not appear to respawn.

### Expected Blizzlike Behaviour

Presumably the fight should still continue regardless.

### Steps to reproduce the problem

1. Engage Illidan solo.
2. Fight him to Phase 2.
3. Cast Divine Shield. Encounter will reset.

### AC rev. hash/commit

fcdc50306ff8734f6f56d22db54862c173879f10

### Operating system

Windows Server 2022

**Comment by ASBaj** [comment]
Following the call stack:

 	worldserver.exe!boss_illidan_stormrage::boss_illidan_stormrageAI::EnterEvadeMode(CreatureAI::EvadeReason why) Line 249	C++

>	worldserver.exe!Creature::SelectVictim() Line 14759	C++

 	worldserver.exe!CreatureAI::UpdateVictim() Line 276	C++

 	worldserver.exe!boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(unsigned int diff) Line 476	C++

So basically, UpdateAI calls UpdateVictim and UpdateVictim calls SelectVictim. Because the player is immune and there are no other players, SelectVictim calls EnterEvadeMode.

Not sure the best way to fix. Changing the behavior of SelectVictim might have wide-ranging effects. Perhaps it would be best to change UpdateAI on Illidan himself, and add an exception for invulnerability?

**Comment by heyitsbench** [comment]
This should be fixed with the recent rewrite.
