### ISSUE TITLE
The world_updates.sql import was unsuccessful!

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#1955]
Using the world_updates.sql generated by appsdb_assembler.sh,
Importing data with source was unsuccessful.

![QQ截图20190609174249](https://user-images.githubusercontent.com/49540243/59157539-f1772180-8ade-11e9-9343-97497030dcc3.jpg)

![QQ截图20190609174648](https://user-images.githubusercontent.com/49540243/59157540-f50aa880-8ade-11e9-9a8f-9b5e30ac799d.jpg)

AzerothCore rev. 204160b121a4+ 2019-06-07 23:39:09 +0200 (master branch) (Win64, Release)

**Comment by FrancescoBorzi** [comment]
@forever2019 why don't you just use the db assembler to import the updates?

**Comment by forever2019** [comment]
@FrancescoBorzi  Sorry, I don't know any other way.
Please repair it. Thank you.

**Comment by FrancescoBorzi** [comment]
@forever2019 can you try the following?

![image](https://user-images.githubusercontent.com/75517/59160821-b5da5880-8ada-11e9-9f7a-6883126ae3f6.png)

**Comment by forever2019** [comment]
Thank you.
I'll try. Thank you for your reply.

**Comment by forever2019** [comment]
@FrancescoBorzi 
![image](https://user-images.githubusercontent.com/49540243/59161368-6f095480-8b14-11e9-990e-c5d6de94ee34.png)

It has been tested.
It is still impossible to import successfully.
This problem needs to be fixed.
Otherwise, I can't update the database later.
It's hard. Thank you.

**Comment by FrancescoBorzi** [comment]
@forever2019 can you please post the error that you get after trying the way I suggested?

**Comment by BarbzYHOOL** [comment]
if you don't post the error how can we help you? Do you think we are magicians??

**Comment by forever2019** [comment]
Thank you for settling it.

**Comment by forever2019** [comment]
@FrancescoBorzi @BarbzYHOOL  
After many tests, it is now confirmed that the problem is 2019_06_01.sql.
Failure to import data will also cause the MySQL database to hang and fail to start mysql.
Steps for Navicat for MySQL testing:
1. Import world_base.sql
2. World_updates integration to 2019_06_01_00.sql
3. Import 2019_06_01.sql
Please test and repair. Thank you!

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi i thought you fixed it in https://github.com/azerothcore/azerothcore-wotlk/pull/1922

**Comment by FrancescoBorzi** [comment]
As I mentioned:

> @forever2019 can you please post the error that you get after trying the way I suggested?

I cannot fix anything if I don't know what the error is.

Also please make sure you're using the **latest** version of AC.
