### ISSUE TITLE
Feature: Add option to disable "Dungeon Deserter" in worldserver.conf

### ISSUE THREAD

**Issue by Blitzritze** [azerothcore/azerothcore-wotlk#19569]
### Describe your feature request or suggestion in detail

Addition of a configuration option in the worldserver.conf file that allows to disable the "Dungeon Deserter" debuff.

### Describe a possible solution to your feature or suggestion in detail

- Introduce a new parameter in the worldserver.conf file named `Dungeon.CastDeserter`.
- This parameter should be a int value (1 or 0).
- Default value should be 1 to maintain current behavior unless explicitly changed.

### Additional context

You can already deactivate the debuff for leaving the BG, couldn't that be set up for dungeons as well?

**Comment by avarishd** [comment]
https://www.azerothcore.org/wiki/spell_dbc

But yes, an option should exist for rdf too.
