### ISSUE TITLE
Command display error

### ISSUE THREAD

**Issue by jimteck** [azerothcore/azerothcore-wotlk#19566]
### Current Behaviour

After updating the CORE, all commands stopped displaying data correctly.

### Expected Blizzlike Behaviour

Before the update, all commands and announcements of events and other game events were displayed correctly.

### Steps to reproduce the problem

I type any commands and as a result it displays through %; it also does not display announcements and event announcements (everything is written through %) there is no text display.

### AC rev. hash/commit

AzerothCore rev. 26f70894ed48+ 2024-08-06 00:41:54 +0000 (master branch) (Win64, Release, Static)	26f70894ed48+	ACDB 335.10-dev	10
![Безымянный](https://github.com/user-attachments/assets/9765bd22-6226-4af7-bb91-6ca8f208d5fe)
![Безымянный1](https://github.com/user-attachments/assets/5ad4eaf1-6635-4976-acfc-c5a60d58c1db)
![Безымянный2](https://github.com/user-attachments/assets/5c18fb8b-6710-404f-b452-e6a187bb6105)
![Безымянный3](https://github.com/user-attachments/assets/371fbca5-6548-4f4e-950e-8e658f74e0a7)

### Operating system

Windows 11

**Comment by Kitzunu** [comment]
Update your DB. This isnt an issue
