### ISSUE TITLE
Command display error

### ISSUE THREAD

**Issue by jimteck** [azerothcore/azerothcore-wotlk#19565]
![изображение_2024-08-06_165914865](https://github.com/user-attachments/assets/23bef69f-3942-4bf6-a7e2-99dd4aee5f62)
### Current Behaviour

After updating the CORE, all commands stopped displaying data correctly.

### Expected Blizzlike Behaviour

Before the update, all commands and announcements of events and other game events were displayed correctly.

### Steps to reproduce the problem

I type any commands and as a result it displays through %; it also does not display announcements and event announcements (everything is written through %) there is no text display.

### AC rev. hash/commit

AzerothCore rev. 88bb14dc9a0b+ 2024-07-20 09:18:06 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static)	88bb14dc9a0b+	ACDB 335.12-dev	12

### Operating system

Windows 11

**Comment by Nyeriah** [comment]
Compile your core, not just update repo

**Comment by jimteck** [comment]
I already compile to last rev.

**Comment by Tereneckla** [comment]
Your rev says 3 weeks ago (and npcbots)
