### ISSUE TITLE
(DB/Quest) Deeprun Rat Roundup

### ISSUE THREAD

**Issue by Blackbird102** [azerothcore/azerothcore-wotlk#19572]
### Current Behaviour

* Accept the quest and get the provided item 'Rat Catcher's Flute'
* Kill the 5 rats and the quest is completed
* Turn in the quest

### Expected Blizzlike Behaviour

* Accept the quest and receive the quest item "Rat Catcher's Flute"
* Use the flute on the rats
  * The rats get friendly and following you
  * The rats gets counted as quest objective
* If you catched 5 rats the quest is complete
* Turn in the quest,  "Rat Catcher's Flute" is removed from inventory and the rats despawn.

### Source

https://www.youtube.com/watch?v=4Phvjninx_s

### Steps to reproduce the problem

Be level 10 or higher a do the quest as described above

### AC rev. hash/commit

AzerothCore rev. f5e44cd8a65a+ 2024-08-01 15:41:23 +0800 (Playerbot branch) (Win64, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 0.
Connection peak: 1.
Server uptime: 6 minute(s) 17 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 3ms, 4ms, 4ms
Using SSL version: OpenSSL 3.3.1 4 Jun 2024 (library: OpenSSL 3.3.1 4 Jun 2024)
Using Boost version: 1.85.0
Using CMake version: 3.30.1
Using MySQL version: 80039
Found MySQL Executable: D:/Programme/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in D:/WoW/AzerothCorePlayerBotsBuild/bin/RelWithDebInfo/Data/maps. Total size: 291014951 bytes
vmaps directory located in D:/WoW/AzerothCorePlayerBotsBuild/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in D:/WoW/AzerothCorePlayerBotsBuild/bin/RelWithDebInfo/Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: zz_optional_aq_quest_nerf.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-individual-progression
|- mod-playerbots

### Operating system

Windows 11 x64

**Comment by Ceikry** [comment]
Can't seem to reproduce, killing the rats does nothing and they only respond to the flute.

**Comment by F-Lambda** [comment]
I've noticed this happening in my own setup. I suspect it's a common module doing it, possibly the Individual Progression Module.
