### ISSUE TITLE
[Dungeon][Wotlk] The Oculus (Heroic) - 3rd Boss Mage-Lord Urom sometimes does not spawn [$50]

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1957]
The Oculus (Heroic) - 3rd Boss Mage-Lord Urom sometimes does not spawn

##### SMALL DESCRIPTION:

The Oculus (Heroic) - 3rd Boss Mage-Lord Urom sometimes does not spawn after killing the three pack of mobs. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should work like this: https://youtu.be/f6KLV6P9LlY?t=190

##### CURRENT BEHAVIOUR:

Dungeon: The Oculus (Heroic) 
Boss: (3rd) Boss Mage-Lord Urom sometimes does not spaw after killing the three pack of mobs. 
He should spawn somewhere in the center. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start a group, or gm mode and kill 1st and 2nd boss in The Oculus (Heroic)
2. Start the 3rd boss encounter - Mage-Lord Urom
3. Kill the group of mobs ( Animals, Elements, Monsters)
4. Mage-Lord Urom has 50 percent chance to spawn after killing the 3 group of mobs.
5. Try another clean Oculus run and repeat

##### EXTRA NOTES:
 
Trinitycore had the same problem before.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 97e65bd

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Naxxramas-Server** [comment]
I can confirm it , but this bug not appear all time , approximately 1/5 time

**Comment by shuradumau** [comment]
I can confirm too, the bug appears 3/5 here

**Comment by solidmaxtor** [comment]
Yeah I confirm this 3/5 aprox

**Comment by spinzaku** [comment]
I retested like 10 times. 6/10. Yeah theres a bug somewhere

**Comment by BarbzYHOOL** [comment]
Can this be related to the order in which mobs die? (just spitting an idea)

**Comment by spinzaku** [comment]
> Can this be related to the order in which mobs die? (just spitting an idea)

maybe. but in retail servers it didn't matter what order the mobs die, boss will still spawn in the end

**Comment by BarbzYHOOL** [comment]
well if some of you can try to find out how to 100% reproduce the issue, it would help

**Comment by spinzaku** [comment]
@poszer  can you please put labels? Dungeon bug?

**Comment by spinzaku** [comment]
@Stoabrogga please help :)

**Comment by spinzaku** [comment]
Added  $5 bounty

**Comment by FrancescoBorzi** [comment]
it's currently $50 : https://www.bountysource.com/issues/75283788-dungeon-wotlk-the-oculus-heroic-3rd-boss-mage-lord-urom-sometimes-does-not-spawn?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github

thanks to our backers @spinzaku @heyaapl and @solidmaxtor
