### ISSUE TITLE
Missing Scripted Objects For quest (Into the Draenethyst Mine)

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19580]
Bug Triager Notes:

Original CC Issue: https://github.com/chromiecraft/chromiecraft/issues/5248#issue-1637290980

You can see crystals number and positions on the mini-map, in the video linked.

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

There are currently 4 items only....

### Expected Blizzlike Behaviour

There are more than that in the mine (TBC classic, WOTLK classic)

### Source
https://www.youtube.com/watch?v=bPdyEJQT5Bk

### Steps to reproduce the problem

Take quest and go to Draenethyst Mine 
Check if you can complete the quest in 1 go - if u have to wait -then its little spawns the mine should have more than enough for 1 player. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/989584b199ee5e4dcc57c30796123275f58aa096

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sudlud** [comment]
`.quest add 10510`

**Comment by sudlud** [comment]
gameobject `Draenethyst Mine Crystal (184689)`
