### ISSUE TITLE
[Silithus] Twilight Prophet bug.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19595]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/6578#issue-2092774580

Video: [Youtube](https://youtu.be/eVmBvOB1vaQ)

This bug type is new even for me.
I don't think I need to add anything else.

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

The NPC Twilight Prophet doesn't stop when I attack it, just keep walking doing the pat always do.
![WoWScrnShot_012124_180934](https://github.com/chromiecraft/chromiecraft/assets/74470790/d5b6142e-1ac9-41b5-b89b-46c145c87675)
![WoWScrnShot_012124_180910](https://github.com/chromiecraft/chromiecraft/assets/74470790/6335be95-4e21-4e7e-a624-d29b7e8d640b)

### Expected Blizzlike Behaviour

-

### Source

-

### Steps to reproduce the problem

-

### Extra Notes

-

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None
-

### Server

ChromieCraft

**Comment by icemansparks** [comment]
I have happened this to me as well, but its not specific to this NPC, but rather happening sometimes especially to NPCs that are "en route". Could not pinpoint or manually reproduce so far.
