### ISSUE TITLE
GM Commands via CLI not working properly

### ISSUE THREAD

**Issue by V-Cyberpunk** [azerothcore/azerothcore-wotlk#19592]
### Current Behaviour

type in e.g. help in AC CLI. no list of commands appears or e.g. server info doesn't work. ingame all is correct via gm char.
![image](https://github.com/user-attachments/assets/1dda24cd-e78c-4abb-a6d8-5371249cf918)
![image](https://github.com/user-attachments/assets/c5d915fd-ad45-4c41-9e7e-ddd5257d55f2)

### Expected Blizzlike Behaviour

commands should work in CLI like ingame

### Steps to reproduce the problem

type in "help" or "server info" in AC CLI

### AC rev. hash/commit

b81bcfbfea07

### Operating system

Debian 12 x64

### Custom changes or Modules

BreakingNewsOverride
ExtendedXP
mod-account-achievements
mod-account-mounts
mod-ah-bot
mod-anticheat
mod-autobalance
mod-boss-announcer
mod-duel-reset
mod-dynamic-xp
mod-eluna
mod-gain-honor-guard
mod-instance-reset
mod-learn-spells
mod-npc-beastmaster
mod-npc-buffer
mod-pvp-titles
mod-rdf-expansion
mod-reagent-bank
mod-solocraft
mod-solo-lfg
mod-starter-guild
mod-transmog
mod-weekend-xp
ReusablePotion

**Comment by V-Cyberpunk** [comment]
corrected the hash

**Comment by Kitzunu** [comment]
Yeah my bad. They work they just don't show
