### ISSUE TITLE
[Quest]Escape from Durnholde (Thrall not giving option for escort)

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1959]
[Quest]Escape from Durnholde (Thrall not giving option for escort)

##### SMALL DESCRIPTION:

Thrall not giving option for escort when doing the last part of Escape from Durnholde quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should be like this: https://youtu.be/jiTHFKo4CKU

##### CURRENT BEHAVIOUR:

No options to escort thrall, already tried abandoning, re-doing quest.
![thrallbug](https://user-images.githubusercontent.com/18629476/59246028-9879cb80-8c4d-11e9-831b-8e66de9f1f30.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get Old Hillsbrad Quest and go to Escape from Durnholde Keep 
2. Do Taretha's Diversion (Burn the Lodges)
3. Complete quest and Talk to thrall for the last part of Escape from Durnholde 'Thrall's Destiny Fulfilled'

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 97e65bd

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Andrei-UPB** [comment]
Hey there. I could not reproduce the issue, works totally fine on my test server running Azerothcore rev. 6d3eabc , I was able to both accept the quest and free Thrall from the Prison, leading to the completion of the dungeon.
![WoWScrnShot_061119_151202](https://user-images.githubusercontent.com/6130699/59271074-bea66800-8c5b-11e9-8437-7c5a70aa51a7.jpg)

**Comment by Selyria** [comment]
I have to agree with @Andrei-UPB because there is no problem was just tested yesterday with 5 man group.

They put the charges in the houses and beat the first boss.

If the first boss isn't dead, thrall doesn't work.

**Comment by spinzaku** [comment]
I am gonna retest again when i get home. thank you guys

**Comment by spinzaku** [comment]
@Selyria Did you test horde side?
@Andrei-UPB  thanks

I will retest when i get home. i am stuck at work

**Comment by Selyria** [comment]
> @Selyria Did you test horde side?
> @Andrei-UPB thanks
> 
> I will retest when i get home. i am stuck at work

Yes, I tried it as Draenei Alliance and as Undead Horde did both.


Remember that you must have killed the first boss.

**Comment by spinzaku** [comment]
@

> > @Selyria Did you test horde side?
> > @Andrei-UPB thanks
> > I will retest when i get home. i am stuck at work
> 
> Yes, I tried it as Draenei Alliance and as Undead Horde did both.
> 
> Remember that you must have killed the first boss.

Ok finally got to test again. it was the first boss. 
going to close this

Thank you all
