### ISSUE TITLE
[Loot table] Witchwing harpies - Dropping incorrect items

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19606]
Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7273#issue-2462503159

I can confirm wrong loots in Witchwing Arpies loots.
Dalaran Wizard's Robe is only an example.

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

The [different harpies](https://www.wowhead.com/wotlk/en/item=5064/witchwing-talon) at the north area in The Barrens, objective of several quests, have an incorrect loot table. Although the items needed for quests are correct, there are some other items that they shouldn't drop. For example, they should not drop "[Dalaran Wizard's Robe](https://www.wowhead.com/wotlk/item=5110/dalaran-wizards-robe)", which comes from npcs in Silverpine Forest.
![ 2024-08-13 a las 1 18 30](https://github.com/user-attachments/assets/e3e99037-2db1-43b9-a1b5-1e9b7b99ef1d)

### Expected Blizzlike Behaviour

Mobs in the Barrens should not drop [Dalaran Wizard's Robe](https://www.wowhead.com/wotlk/item=5110/dalaran-wizards-robe).

### Source

[This](https://www.wowhead.com/wotlk/en/item=5064/witchwing-talon) is the list of harpies in the area, you can check their loot tables.

### Steps to reproduce the problem

1. Kill harpies at The Barrens and obtain items you shouldn't.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by zergov** [comment]
Hi 👋, I'm on a fresh instance running d4aca0bca18124557fb6bf0a9b42abd56783c36b. 
I ran some queries on `acore_world` to check the `creature_loot_templates` for these harpies, and I don't see the `Dalaran Wizard's Robe` in the loot table.

```sql
-- creature_loot_templates for the different Harpies:
-- https://www.wowhead.com/wotlk/npc=3276/witchwing-harpy
-- https://www.wowhead.com/wotlk/npc=3277/witchwing-roguefeather
-- https://www.wowhead.com/wotlk/npc=3280/witchwing-windcaller
-- https://www.wowhead.com/wotlk/npc=3278/witchwing-slayer
-- https://www.wowhead.com/wotlk/npc=3279/witchwing-ambusher
-- https://www.wowhead.com/wotlk/npc=3452/serena-bloodfeather
select ct.entry as creature_id, ct.name as creature_name, it.entry as item_entry, it.name, clt.Chance 
from acore_world.creature_template ct 
inner join acore_world.creature_loot_template clt on clt.Entry = ct.entry 
inner join acore_world.item_template it on it.entry = clt.Item 
where ct.entry in (3276, 3277, 3280, 3278, 3279, 3452)
```

I get this result: 
|creature_id|creature_name|item_entry|name|Chance|
|-----------|-------------|----------|----|------|
|3276|Witchwing Harpy|1179|Ice Cold Milk|2.507|
|3276|Witchwing Harpy|2287|Haunch of Meat|4.5197|
|3276|Witchwing Harpy|2589|Linen Cloth|37.9915|
|3276|Witchwing Harpy|4776|Ruffled Feather|7.4923|
|3276|Witchwing Harpy|5064|Witchwing Talon|80.0|
|3276|Witchwing Harpy|5114|Severed Talon|22.262|
|3276|Witchwing Harpy|5635|Sharp Claw|1.0028|
|3276|Witchwing Harpy|6661|Recipe: Savory Deviate Delight|0.08|
|3276|Witchwing Harpy|17056|Light Feather|28.2573|
|3277|Witchwing Roguefeather|1179|Ice Cold Milk|2.452|
|3277|Witchwing Roguefeather|2287|Haunch of Meat|4.3406|
|3277|Witchwing Roguefeather|2589|Linen Cloth|38.7399|
|3277|Witchwing Roguefeather|4776|Ruffled Feather|7.2131|
|3277|Witchwing Roguefeather|5064|Witchwing Talon|80.0|
|3277|Witchwing Roguefeather|5114|Severed Talon|23.1947|
|3277|Witchwing Roguefeather|5635|Sharp Claw|1.9917|
|3277|Witchwing Roguefeather|6661|Recipe: Savory Deviate Delight|0.14|
|3277|Witchwing Roguefeather|17056|Light Feather|28.7494|
|3278|Witchwing Slayer|414|Dalaran Sharp|0.02|
|3278|Witchwing Slayer|1179|Ice Cold Milk|2.3505|
|3278|Witchwing Slayer|2287|Haunch of Meat|4.4128|
|3278|Witchwing Slayer|2589|Linen Cloth|17.8134|
|3278|Witchwing Slayer|2592|Wool Cloth|19.3669|
|3278|Witchwing Slayer|4537|Tel'Abim Banana|0.02|
|3278|Witchwing Slayer|4541|Freshly Baked Bread|0.02|
|3278|Witchwing Slayer|4605|Red-speckled Mushroom|0.02|
|3278|Witchwing Slayer|5064|Witchwing Talon|80.0|
|3278|Witchwing Slayer|5065|Harpy Lieutenant Ring|80.0|
|3278|Witchwing Slayer|5114|Severed Talon|7.1416|
|3278|Witchwing Slayer|5115|Broken Wishbone|22.6225|
|3278|Witchwing Slayer|5635|Sharp Claw|2.0713|
|3278|Witchwing Slayer|6661|Recipe: Savory Deviate Delight|0.06|
|3278|Witchwing Slayer|17056|Light Feather|28.6608|
|3279|Witchwing Ambusher|1179|Ice Cold Milk|1.8727|
|3279|Witchwing Ambusher|2287|Haunch of Meat|4.2135|
|3279|Witchwing Ambusher|2589|Linen Cloth|18.7734|
|3279|Witchwing Ambusher|2592|Wool Cloth|17.8371|
|3279|Witchwing Ambusher|4605|Red-speckled Mushroom|0.02|
|3279|Witchwing Ambusher|5064|Witchwing Talon|80.0|
|3279|Witchwing Ambusher|5114|Severed Talon|6.882|
|3279|Witchwing Ambusher|5115|Broken Wishbone|23.2678|
|3279|Witchwing Ambusher|5635|Sharp Claw|1.8727|
|3279|Witchwing Ambusher|6661|Recipe: Savory Deviate Delight|0.08|
|3279|Witchwing Ambusher|17056|Light Feather|29.6348|
|3280|Witchwing Windcaller|414|Dalaran Sharp|0.02|
|3280|Witchwing Windcaller|1179|Ice Cold Milk|2.9087|
|3280|Witchwing Windcaller|2287|Haunch of Meat|4.6311|
|3280|Witchwing Windcaller|2589|Linen Cloth|16.7046|
|3280|Witchwing Windcaller|2592|Wool Cloth|18.7358|
|3280|Witchwing Windcaller|4537|Tel'Abim Banana|0.013|
|3280|Witchwing Windcaller|4541|Freshly Baked Bread|0.02|
|3280|Witchwing Windcaller|4605|Red-speckled Mushroom|0.02|
|3280|Witchwing Windcaller|5064|Witchwing Talon|80.0|
|3280|Witchwing Windcaller|5075|Blood Shard|0.0162|
|3280|Witchwing Windcaller|5114|Severed Talon|7.4911|
|3280|Witchwing Windcaller|5115|Broken Wishbone|22.4732|
|3280|Witchwing Windcaller|5498|Small Lustrous Pearl|0.02|
|3280|Witchwing Windcaller|5635|Sharp Claw|1.8687|
|3280|Witchwing Windcaller|6661|Recipe: Savory Deviate Delight|0.026|
|3280|Witchwing Windcaller|17056|Light Feather|29.2818|
|3452|Serena Bloodfeather|1179|Ice Cold Milk|2.1948|
|3452|Serena Bloodfeather|2287|Haunch of Meat|4.9383|
|3452|Serena Bloodfeather|2589|Linen Cloth|17.0096|
|3452|Serena Bloodfeather|2592|Wool Cloth|17.8326|
|3452|Serena Bloodfeather|5064|Witchwing Talon|80.0|
|3452|Serena Bloodfeather|5067|Serena's Head|100.0|
|3452|Serena Bloodfeather|5114|Severed Talon|6.7215|
|3452|Serena Bloodfeather|5115|Broken Wishbone|22.4966|
|3452|Serena Bloodfeather|5635|Sharp Claw|3.155|
|3452|Serena Bloodfeather|17056|Light Feather|25.6516|

---

I then tried to look for `creature_loot_template` rows for `Dalaran Wizard's Robe` and I couldn't find any🤔.  

```sql
-- creature_loot_templates for 'Dalaran Wizard's Robe' (id 5110)
-- https://www.wowhead.com/wotlk/item=5110/dalaran-wizards-robe
select it.name, loot.Entry, loot.Item 
from acore_world.item_template it 
left join acore_world.creature_loot_template loot on loot.Item = it.entry 
where it.entry = 5110
```

---

I'm new to the project (found the repo yesterday), so I might not be looking at the right spot.

**Comment by Kitzunu** [comment]
you can find it in reference_loot_template (entries 1011415, 1011515, 1011516, 1011616)
```sql
SELECT * FROM reference_loot_template WHERE item = 5110
```

Which is tied into creature_loot_template here
```sql
SELECT * FROM creature_loot_template WHERE reference IN (SELECT entry FROM reference_loot_template WHERE item = 5110);
```

more info here https://www.azerothcore.org/wiki/loot_template

**Comment by zergov** [comment]
Thanks for the quick answer! This should unblock me <3
