### ISSUE TITLE
mod-gain-honor-guard crashed

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/azerothcore-wotlk#19644]
### Current Behaviour

run worldserver

![image](https://github.com/user-attachments/assets/d697bbf9-8b4e-420e-9a65-3e778260b62e)

### Expected Blizzlike Behaviour

no crash

### Steps to reproduce the problem

open terminate
./worldserver
crashed

### AC rev. hash/commit

last commit 
azerothcore is playerbot branch last version 

### Operating system

ubuntu22.04.4

### Custom changes or Modules

-- * Modules config list:
  |
--   +- mod-ah-bot
--   |  * mod_ahbot.conf.dist
--   +- mod-boss-announcer
--   |  * mod_boss_announcer.conf.dist
--   +- mod-eluna
--   |  * mod_LuaEngine.conf.dist
--   +- mod-guildhouse
--   |  * mod_guildhouse.conf.dist
--   +- mod-learn-spells
--   |  * mod_learnspells.conf.dist
--   +- mod-npc-all-mounts
--   |  * npc_allmounts.conf.dist
--   +- mod-npc-gambler
--   |  * npc_gambler.conf.dist
--   +- mod-playerbots
--   |  * playerbots.conf.dist
--   +- mod-transmog
--   |  * transmog.conf.dist

**Comment by xengine-qyt** [comment]
sorry.mod-gain-honor-guard cant comment issuse

**Comment by Grimdhex** [comment]
could you provide a full crashlog ? you can share them here : https://gist.github.com/
