### ISSUE TITLE
Shaman Totem elementals are always hostile to opposite faction

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#19658]
https://github.com/chromiecraft/chromiecraft/issues/7284
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Shaman Fire elemental and Earth elemental totems are hostile and attackable by the opposite faction to the Shaman that summoned the totem. This includes non PvP flagged players and those in a crossfaction Raid/Party. It can also attack non targetable enemy faction NPC's like the  PvP call to arms ones in shattrath

### Expected Blizzlike Behaviour

They should not automatically be hostile

### Steps to reproduce the problem

.learn 2894 or 2062
test with character of opposite faction

### Extra Notes

possibly related to https://github.com/azerothcore/azerothcore-wotlk/pull/19599

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee8c103d3d9b0473e8014f11bba910f2e8ee84ec

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by BeefSteaker** [comment]
![image](https://github.com/user-attachments/assets/b95c99d1-9c1c-45f2-9409-d4f50cec35df)

**Comment by heyitsbench** [comment]
Would need to refer to sniffs to be sure, but maybe a fix could be setting elemental faction to faction of the totem creator.

**Comment by heyitsbench** [comment]
Checked a sniff, totem and elemental faction template ID was 2 (Player, Orc) which matches default AC behavior. Can confirm that the elemental(s) attack the creatures mentioned on AC.
