### ISSUE TITLE
Weekly Dungeon Resets Occurring Daily

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#19657]
### Current Behaviour

I have encountered a critical issue with the weekly dungeons. The reset timers for these dungeons are incorrectly set to reset daily instead of weekly. This issue has been observed in most of the weekly dungeons, although Onyxia has not yet been tested. However, all other tested dungeons are resetting every day.
![Imagen de WhatsApp 2024-08-17 a las 13 12 47_b7fe1202](https://github.com/user-attachments/assets/d98ed9fe-e888-413a-af94-7bc4c3a5cb7a)

### Expected Blizzlike Behaviour

Weekly dungeons should only reset once per week, not daily. Players should be able to complete these dungeons once a week and have the lockout period last for the entire week.

### Steps to reproduce the problem

1.- Enter any weekly dungeon.
2.- Complete the dungeon.
3.- Wait until the next daily reset.
4.- Observe that the dungeon has reset, allowing re-entry.

### Extra Notes

According to Blizzard's official documentation and community knowledge, weekly dungeons should reset once every 7 days.

### AC rev. hash/commit

AC> AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/3c4086a5a069fa73452e74801c8ed4faf6caeb05 2024-08-16 05:07:41 -0300 (master branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 1 minute(s) 3 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 3ms, 4ms, 4ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-118-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: npc_gambler.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg

### Operating system

Ubuntu 24.04 LTS

### Custom changes or Modules

mod-anticheat, mod-breaking-news-override, mod-cfbg

**Comment by Kitzunu** [comment]
![image](https://github.com/user-attachments/assets/bae885bd-bb40-4da7-b2ab-4dfbebf520e4)

I cannot confirm. Are you sure you didnt change a config option

**Comment by Kitzunu** [comment]
or that you tested on a Wednesday because reset time is by default 04.00 Thursday
