### ISSUE TITLE
Quest greeting crash

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#19659]
### Current Behaviour

https://gist.github.com/Nyeriah/11c0553ed968884cfe96b3277c9dbb80

### Expected Blizzlike Behaviour

No crash

### Steps to reproduce the problem

Unsure

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3c4086a5a069fa73452e74801c8ed4faf6caeb05

### Operating system

Ubuntu 22

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by Nyeriah** [comment]
I suspect https://github.com/azerothcore/azerothcore-wotlk/pull/19615

**Comment by Nyeriah** [comment]
![image](https://github.com/user-attachments/assets/ea10c29c-112f-486b-9799-8c8f256ddef8)

**Comment by heyitsbench** [comment]
Reproduction steps:
1. `.go c id 23572`
2. `.quest add 11208`
3. `.quest add 11211`
4. Talk to Drazzit.
5. Crash.

**Comment by Kitzunu** [comment]
I look

**Comment by Kitzunu** [comment]
Got bench looking at a sniff to determine how I should fix it.
