### ISSUE TITLE
[Worldserver/Crash] ACCESS_VIOLATION Crash

### ISSUE THREAD

**Issue by LannyE** [azerothcore/azerothcore-wotlk#19663]
### Current Behaviour

I updated my installation and it now crashes not too long after starting the worldserver.   The last update I did was on 8-8-24 using commit:
https://github.com/azerothcore/azerothcore-wotlk/tree/ebc62182754e21515d4cd53d42c9fe6634fdf2ae

That commit worked fine.  Updated yesterday and constant crashes about 15 minutes after starting the worldserver.  

Crashlog from my test server. 
https://gist.github.com/LannyE/3e4b76ba5a4e883095a6ccfe99328546

Anyone else seeing this?  I have tried it without modules but the outcome and crashlog are the same.  

### Expected Blizzlike Behaviour

Not Crash after starting the worldserver

### Steps to reproduce the problem

Compile new commit
Start Worldserver
About 15 minutes later it crashes.  

### AC rev. hash/commit

AzerothCore rev. a691ad3f4ddb+ 2024-08-17 20:27:36 +0200 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-gain-honor-guard](https://github.com/azerothcore/mod-gain-honor-guard)
[mod-individual-xp](https://github.com/azerothcore/mod-individual-xp)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-solo-lfg](https://github.com/azerothcore/mod-solo-lfg)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/ad411b49b772b40e870fd5079f3328807631facd possibly caused this

**Comment by kambire** [comment]
https://gist.github.com/kambire/b3bcfda0a30015c6c99ae2746150b6c7

**Comment by kambire** [comment]
I've also been experiencing multiple worldserver crashes for several days. Hopefully, this can be resolved soon.

**Comment by LannyE** [comment]
@Nyeriah Thanks for pointing me to that commit.  I removed that code on my test server and it has so far stayed running for over an hour which is much more than I was getting before.  I will continue watching it for a while longer and report back on what happens.
