### ISSUE TITLE
Quest 12705 Will of the titans

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#19673]
### Current Behaviour

![image](https://github.com/user-attachments/assets/e5be34e5-f705-460c-ae36-3d06d93d5b11)

Error `Requires Great Lightning Stone` when using item quest `Tainted Crystal` near the Great Lightning Stone

### Expected Blizzlike Behaviour

It should transform you in a panther and kill 50 Frenzyheart using panther

### Source

Quest Description

### Steps to reproduce the problem

.quest add 12705
.itemadd 39266
search for the stone near The Mosslight Pillar in Sholazar Basin

### AC rev. hash/commit

AzerothCore rev. 3c4086a5a069 2024-08-16

### Operating system

Debian 12

**Comment by Kitzunu** [comment]
Paste the result of `.server debug` in `AC rev. hash/commit` "last" does not mean anything

**Comment by manstfu** [comment]
AzerothCore rev. 3c4086a5a069 2024-08-16

**Comment by TheSCREWEDSoftware** [comment]
![image](https://github.com/user-attachments/assets/b7743b36-fca7-4dc2-8201-77f5d4977757)

You're at the wrong place.
