### ISSUE TITLE
Locales

### ISSUE THREAD

**Issue by cooler-SAI** [azerothcore/azerothcore-wotlk#197]
**Description**: Can you show me how I can change locales into Russian lang? (DBC.Locale = 8)

**Current behaviour**: I changed DBC locales in configs and set RealmZone to 12 and nothing happened. I have fully completed locales tables fpt loc 8
**Expected behaviour**: Lang in the game must changes

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
##

**Comment by HeartWell** [comment]
All localization cut. We need to build upon and add Broadcast. 

Там все вырезали, пришлось попотеть над  броаткастом)

**Comment by alexkulya** [comment]
Решение для локализации вещей.
Solution for item localization.
https://github.com/alexkulya/SunwellCore/commit/e92388d0a8e650d12f01eeb6edfa94492fe78f6a

SunwellCore

**Comment by HeartWell** [comment]
Ты серьезно? А где все остальное?

**Comment by sucofog** [comment]
Yeah, i looked into the code and there are parts left that you correctly added @HeartWell 
better commit of @HeartWell including Achievement + Cs, etc...

**Comment by alexkulya** [comment]
HeartWell. Не знаю кому адресовано ваше сообщение, если мне то:
Коммит добавляет только локализацию для вещей и не более.

**Comment by HeartWell** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/223
Вот как должно быть.

**Comment by alexkulya** [comment]
Я не работаю на AzerothCore и не собираюсь. Хотите составлять отдельный баг-репорт, ради бога. Я указал лишь решение. И не надо меня тыкать пальцем.

**Comment by HeartWell** [comment]
Если не работаешь, то и не надо.

**Comment by alexkulya** [comment]
Как хотите, делайте все сами.

**Comment by SergeyBliznec** [comment]
https://github.com/SergeyBliznec/azerothcore-rudb мой порт из YTDB
