### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by patphoenix** [azerothcore/azerothcore-wotlk#19711]
### Current Behaviour

Getting following error when compiling:

```
[  7%] Building CXX object src/common/CMakeFiles/common.dir/Cryptography/OpenSSLCrypto.cpp.o
/root/azerothcore-wotlk/src/common/Cryptography/OpenSSLCrypto.cpp:20:10: fatal error: 'openssl/provider.h' file not found
#include <openssl/provider.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [src/common/CMakeFiles/common.dir/build.make:413: src/common/CMakeFiles/common.dir/Cryptography/OpenSSLCrypto.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/root/azerothcore-wotlk/src/common/Cryptography/ARC4.cpp:23:15: fatal error: use of undeclared identifier 'EVP_CIPHER_fetch'
    _cipher = EVP_CIPHER_fetch(nullptr, "RC4", nullptr);
              ^
1 error generated.
[  7%] Built target revision.h
gmake[2]: *** [src/common/CMakeFiles/common.dir/build.make:353: src/common/CMakeFiles/common.dir/Cryptography/ARC4.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:940: src/common/CMakeFiles/common.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2

real    0m0.730s
user    0m1.210s
sys     0m0.283s
```

### Expected Blizzlike Behaviour

Error should not occur and should compile

### Steps to reproduce the problem

1) Pull latest git repositories
2) build and get the above error

### Extra Notes

N/A

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/05c9a96ba99c9884d070326238c8c3f2587bbb4b 2024-07-11 12:32:13 +0800 (Playerbot branch) (Unix, Release, Static)
Connected players: 1. Characters in world: 468.
Connection peak: 1.
Server uptime: 1 minute(s) 18 second(s)
Update time diff: 6ms. Last 500 diffs summary:
|- Mean: 16ms
|- Median: 11ms
|- Percentiles (95, 99, max): 36ms, 39ms, 53ms
Using SSL version: OpenSSL 1.1.1w 11 Sep 2023 (library: OpenSSL 1.1.1w 11 Sep 2023)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100523
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.10.0-30-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-playerbots

### Operating system

Debian 11 x64

### Custom changes or Modules

N/A

**Comment by Nyeriah** [comment]
OpenSSL 1.x not supported. Upgrade to 3.x
