### ISSUE TITLE
Feathermoon Headdress has the wrong stats

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#19721]
https://github.com/chromiecraft/chromiecraft/issues/7025
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

Feathermoon Headdress (id: 13113) in game is currently giving +20 Intellect. 
 it should give +20 Intellect , +13 Stamina, and surprisingly "Equip: Increases damage done by magical spells and effects by up to 25"

### Expected Blizzlike Behaviour

According to wowhead and comments from patch 3.x the correct stats are: +20 Intellect, +13 Stamina and +25 spell power.

### Source

![image](https://github.com/user-attachments/assets/c0c52c4d-8d5b-434d-98fa-3853508bb84d)

https://www.wowhead.com/wotlk/item=13113/feathermoon-headdress
![image](https://github.com/user-attachments/assets/1a006a2e-899b-4335-a9d3-1fc7504f8118)

### Steps to reproduce the problem

1. Log in PTR
2. Use the command ".additem 13113"
3. Check the item stats and character stats

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/564192f8810b32823925c9c1644a0abfa84d9d03

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by alecsci** [comment]
✅ Tested, looks good now.
The trick here was to remove the Cache folder, if the item with the wrong stats was added before.
