### ISSUE TITLE
[Black Temple] High Nethermancer Zerevor doesn't use Dampen Magic out of combat

### ISSUE THREAD

**Issue by M4th3m4tic4l** [azerothcore/azerothcore-wotlk#19729]
Original: https://github.com/chromiecraft/chromiecraft/issues/7305

### Current Behaviour

[High Nethermancer Zerevor](https://wowgaming.altervista.org/aowow/?npc=22950) doesn't use [Dampen Magic](https://wowgaming.altervista.org/aowow/?spell=41478) out of combat

### Expected Blizzlike Behaviour

[High Nethermancer Zerevor](https://wowgaming.altervista.org/aowow/?npc=22950) should be using [Dampen Magic](https://wowgaming.altervista.org/aowow/?spell=41478) even out of combat

### Source

[Pre Wotlk Classic](https://youtu.be/TRPy6G0UhcA?t=5449) at 1:30:49 as soon the warrior enter Illidari Council room he target Zerevor and he already have the buff on him
[TBC Classic](https://youtu.be/MAjuy89WIbY) you can see the buff already exist before starting the fight.
[TBC Classic](https://youtu.be/LiQcM_Y3lR4) another video shows that Zeveros have the buff on him before the fight.

### Steps to reproduce the problem

1. .tele bt
2. go to Illidari Council room
3. before engaging in the combat with them ,you can see that [High Nethermancer Zerevor](https://wowgaming.altervista.org/aowow/?npc=22950) doesn't have [Dampen Magic](https://wowgaming.altervista.org/aowow/?spell=41478)

### Extra Notes

It seems that the Zeveros have ~1mn CD before using [Dampen Magic](https://wowgaming.altervista.org/aowow/?spell=41478) again with some conditions?

* Out of combat , you can see in the first source from [Pre Wotlk classic](https://youtu.be/TRPy6G0UhcA?t=6284) at 1:44:44 that Zeveros always wait until the buff runs out then buff himself again with it.

* If you start the fight with Zeveros and 1mn already have passed from the previous cast of the buff , then Zeveros will immediately cast the buff again as soon the fight starts which can be seen in the second source from [TBC classic](https://youtu.be/MAjuy89WIbY) as there was ~3mn left on the buff and Zeveros buffed himself again with it as the fight started.

* Before starting the fight , if you waited for the buff to run out and for Zeveros to cast it again then you steal it , Zeveros will not cast his buff again unless ~1mn has passed from his previous cast , as it can be seen from this video from [TBC classic](https://youtu.be/LiQcM_Y3lR4?t=12) as his second cast of [Dampen Magic](https://wowgaming.altervista.org/aowow/?spell=41478) was ~1mn later , at 1:12 , 2:14 , 3:17 , 4:22 , 5:23 , 6:31

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 20.04

### Custom changes or Modules

* [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
 * [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
 * [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
 * [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
 * [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
 * [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
 * [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
 * [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
 * [mod-eluna](https://github.com/azerothcore/mod-eluna)
 * [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
 * [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
 * [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
 * [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
 * [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
 * [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
 * [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
 * [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
 * [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
 * [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
 * [mod-transmog](https://github.com/azerothcore/mod-transmog)
 * [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
 * [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
 * [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
 * [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
 * [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
 * [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
 * [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
 * [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
 * [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
 * [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by Blandyoung** [comment]
REPLACE INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES (22950, 0, 0, 0, 4097, 0, 3, '41341 41478');

**Comment by M4th3m4tic4l** [comment]
> REPLACE INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES (22950, 0, 0, 0, 4097, 0, 3, '41341 41478');

Could you make a pull request for this? thanks

**Comment by heyitsbench** [comment]
I suspect it'd be an incorrect fix, I would believe he's supposed to cast it on spawn and repeat thereafter.

**Comment by M4th3m4tic4l** [comment]
I see, you are right

**Comment by Nyeriah** [comment]
> I suspect it'd be an incorrect fix, I would believe he's supposed to cast it on spawn and repeat thereafter.

Yes, I've confirmed that behaviour while checking it on retail
