### ISSUE TITLE
[Dungeon Wotlk] Halls of Stone - Brann Bronzebeard sometimes does not respawn after wiping [$15]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#1974]
[Dungeon Wotlk] Halls of Stone - Brann Bronzebeard sometimes does not respawn after wiping

##### SMALL DESCRIPTION:

Halls of Stone - Brann Bronzebeard sometimes does not respawn when an entire party wipes, can't restart escort/event.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Brann Bronzebeard should respawn after running backin/wipe or restarting escort.

##### CURRENT BEHAVIOUR:

Halls of Stone - Brann Bronzebeard sometimes does not respawn when an entire party wipes. Once you release and run back to restart the escort/event. Brann is not there anymore.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run Hall of Stones dungeon
2. Talk to Brann Bronzebeard to start escort/event
3. Halfway to the event/escort suicide/wipe/die party.
4. Run back in to dungeon, he doesn't spawn

##### EXTRA NOTES:

This bug also happens in retail version.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 97e65bd

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Andrei-UPB** [comment]
Check the respawn timer and modify it accordingly, it might be set to one hour.

**Comment by Bogir** [comment]
> 
> 
> Check the respawn timer and modify it accordingly, it might be set to one hour.

This bug is happens from every begining of TC and not depends of SQL. Brann spawned by instance script, and respawns in 65 minutes after death with all instance trash

**Comment by disclosurez** [comment]
can confirm this needs to change due to players wiping

**Comment by Stoabrogga** [comment]
Already fixed via PR #2063, merged in commit bad8390dee2fba50a711a26e6537fbdbb0d8863d
