### ISSUE TITLE
[SSC] Greyhound Spellbinder miss Banish ability #6412

### ISSUE THREAD

**Issue by alecsci** [azerothcore/azerothcore-wotlk#19765]
### Current Behaviour

Reported by: https://github.com/chromiecraft/chromiecraft/issues/6412
> https://wowgaming.altervista.org/aowow/?npc=21806#abilities dont use Banish

### Expected Blizzlike Behaviour

they should also banish raid members

### Source

https://www.wowhead.com/tbc/npc=21806/greyheart-spellbinder#abilities;mode:n25

### Steps to reproduce the problem

1. Check Keira
2. (or) .go c id 21806 and battle for yourself

### AC rev. hash/commit

4ed1815de64e97a373bacf075073b7e2cde46dc5

### Operating system

Windows 11 x64

**Comment by Carriola-wotlk** [comment]
should they banish a random raid member?

**Comment by alecsci** [comment]
Yes @Carriola-wotlk
