### ISSUE TITLE
Core/Misc: change license

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#1976]
##### SMALL DESCRIPTION:
- Need to add or change the license in all files in a project

#### Example
- https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/cmake/compiler/clang/settings.cmake
- https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Miscellaneous/Language.h

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan do you mean, to make it consistent with majority of our files?

**Comment by Winfidonarleyan** [comment]
Yes, if I understand you correctly
