### ISSUE TITLE
Paladin Classmounts not correct

### ISSUE THREAD

**Issue by cptcl** [azerothcore/azerothcore-wotlk#19773]
### Current Behaviour

Most of the paladin class horses are wrong. i.e. "Warhorse" is in fact "Highlord's Vengeful Charger". "Thalassian Warhorse" is also something else.

### Expected Blizzlike Behaviour

Cast correct mount

### Steps to reproduce the problem

Have a Paladin and learn "warhorse"
Use it
Sit on a wrong mount

### Extra Notes

Tryed every spell that has "warhorse" inside and cant get the right mount . 

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/1d56e84fb9d8554d9c6448b18b7f688aa2d42ee0

### Operating system

Server Debian 12 latest

**Comment by Nyeriah** [comment]
Are you using HD client patches or other client patches ?
