### ISSUE TITLE
Failing workflow due to duplicate entry in query.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19771]
### Current Behaviour

Workflow is failing due to a duplicate entry in [this SQL query](https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/updates/db_world/2024_08_28_03.sql) introduced in [this commit](https://github.com/azerothcore/azerothcore-wotlk/commit/8852f0c74c212d50c7bc767864f8f9fe925691bb).

### Expected Blizzlike Behaviour

No duplicate entry, no failing workflow.

### Source

Assumption.

### Steps to reproduce the problem

1. Look at the [commit history](https://github.com/azerothcore/azerothcore-wotlk/commits/master/).
2. Observe the ❌'s.

### AC rev. hash/commit

558e430349e716b8585efcb66399d9475a45d0d1

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Gultask** [comment]
![image](https://github.com/user-attachments/assets/7a36152e-9547-4f1f-adf0-52fa78a86773)
