### ISSUE TITLE
Warlock's Infernal behavior

### ISSUE THREAD

**Issue by Saqra1** [azerothcore/azerothcore-wotlk#19783]
### Current Behaviour

- On summon the infernal react state is always "passive"
- On dismiss the infernal doesn't go away, it can't be controlled but it just stands in place until it expires or another pet is summoned
  - It only loses it's Enslave Demon aura
- It gets Enslave Demon aura applied automatically

### Expected Blizzlike Behaviour

- Initial react state should be "aggressive"
- It should disappear on dismiss
- It shouldn't need Enslave Demon aura
  - During Vanilla it was required to be enslaved (and re-enslaved) but not on Wrath
  - It starts under warlock's command
  - The infernal is not hostile 
  - It can't get loose, it only disappears

### Source

Wotlk Classic:

https://www.youtube.com/watch?v=LOeJNC6XDdU

### Steps to reproduce the problem

1. `.learn 1122` (Inferno) and `.additem 5564` (Infernal Stone)
2. Summon infernal
3. Check react state on pet
4. Check auras on pet 
5. Try to dismiss it

### AC rev. hash/commit

c8c7362

### Operating system

Windows 11

**Comment by heyitsbench** [comment]
> YouTube video

Wasn't expecting that to be mine. 😆

**Comment by Saqra1** [comment]
I was investigating past Infernal issues and got the video from this issue: https://github.com/chromiecraft/chromiecraft/issues/5823

**Comment by Saqra1** [comment]
Initially I was trying to reproduce this issue https://github.com/chromiecraft/chromiecraft/issues/7202 (I've seen it happen many times on Chromie). The only way I could get the infernal to be in the same uncontrollable state was by not casting Enslave Demon on it.

I suspect there is an scenario that prevents the infernal from being enslaved. Maybe the aura is getting resisted, or dispelled, or expires sooner, it could be any number of issues. But in any case it shouldn't be getting that aura and we shouldn't depend on it to control the unit.

This might address it too.

**Comment by heyitsbench** [comment]
For the record, I checked a 3.4.3 51943 sniff and found the following auras on an infernal summoned by a raid member (number denoting aura slot):
- 0: 34947 - Warlock Pet Scaling 01
- 1: 34956 - Warlock Pet Scaling 02
- 2: 19432 - (doesn't exist lol)
- 3: 19483 - Immolation
- 4: 65220 - Avoidance
- 5: 61679 - Pet Health Scaling
- 6: 67557 - Pet Scaling - Master Spell 03 - Intellect, Spirit, Resilience
- 7: 34957 - Warlock Pet Scaling 03
- 8: 34958 - Warlock Pet Scaling 04
- 9: 61013 - Warlock Pet Scaling 05
