### ISSUE TITLE
Shattrath Flasks are not persisted when leaving mentioned zones

### ISSUE THREAD

**Issue by alecsci** [azerothcore/azerothcore-wotlk#19786]
### Current Behaviour

Reported by: https://github.com/chromiecraft/chromiecraft/issues/6482

Initially only 1 type of flasks was reported, but I tested and all are affected.
> We wiped on Vashj and after "release spirit" the shattrath flask buff was gone.
The "remove" can be seen in this recent Video
[https://www.twitch.tv/heringv/clip/SucculentSincereJuiceArgieB8-M3QLSu8K4k5wMKr6](https://github.com/chromiecraft/chromiecraft/issues/url)

### Expected Blizzlike Behaviour

The flask buff should be still there even if not in the instance, only the effect shouldn't work outside.

### Source

I can also confirm due to my playing on other servers.

### Steps to reproduce the problem

1. .tele ssc
2. .additem 32899
3. .additem 35716
4. .go c id 18538
5. .die and release

### Extra Notes

It's worth testing the fix against other instances too: BT, SSC, Hyjall.
Solution hint: https://github.com/chromiecraft/chromiecraft/issues/6482#issuecomment-1879817985

### AC rev. hash/commit

37d601b6c8a466414228d71986beb0689725bfb9

### Operating system

Windows 11 x64

**Comment by heyitsbench** [comment]
Possibly related to https://github.com/azerothcore/azerothcore-wotlk/issues/16360?

**Comment by alecsci** [comment]
@heyitsbench not sure. Your referenced ticket mentions stacking the buffs, my report mentions the buff gets removed when getting out of instance.
