### ISSUE TITLE
Wintergrasp Catapult Siege Vehicle is buggy [$25]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#1978]
Wintergrasp Catapult Siege Vehicle is buggy

##### SMALL DESCRIPTION:

Wintergrasp Catapult Siege Vehicle has a visual bug when using Plague Barrel and Flame Breath's range is too wide.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://youtu.be/5ZfYp2Xvbvc?t=58

Correct the trajectory of the "Plague Barrel"
Reduce the range for "Flame Breath" skill

##### CURRENT BEHAVIOUR:

1. Catapult Siege Vehicle Skill "Plague Barrel" visual bug for driver. When used the barrel flies behind but still lands on your target.
2. Catapult Siege Vehicle Skill "Flame Breath" range of flame breath is so wide it can hit you if your within around 50 yards.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Join Wintergrasp Battle
2. Ride the Catapult Siege Vehicle
3. Use Plague Barrel and Flame Breath

Video of actual bug: https://youtu.be/KvZ63ptfdbg

##### EXTRA NOTES:

Maybe related due to insane catapult range/damage: https://github.com/TrinityCore/TrinityCore/issues/7622

Wintergrasp is basically impossible to play especially if one faction controls and rides all the catapults and spams flame breath. You will still get damaged when you spawn basically one shot

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 97e65bd

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Naxxramas-Server** [comment]
I can confirm

**Comment by Selyria** [comment]
I can confirm

**Comment by Hir0shi** [comment]
Yes and me, Confirm

**Comment by BarbzYHOOL** [comment]
@Hir0shi because you don't help us

**Comment by FrancescoBorzi** [comment]
@Hir0shi this is a community-driven project. It's not a project where people is paid to work on it. So we do what we can do, hoping that the other users will help too.

**Comment by spinzaku** [comment]
More testing: 

Wintergrasp is basically impossible to play especially if one faction controls and rides all the catapults and spams flame breath. You will still get damaged when you spawn basically one shot

**Comment by poszer** [comment]
Caused by this PR https://github.com/azerothcore/azerothcore-wotlk/commit/e9770dbb33bcf0838418de7fc03f50d9f89d6213

As the temp fix for that flame breath you can try this query:

```sql
UPDATE creature_template SET spell2='50990' WHERE entry=27881;
```

**Comment by spinzaku** [comment]
Thank you for this fix @poszer

**Comment by wowmane** [comment]
@spinzaku

Worked

**Comment by spinzaku** [comment]
I tried this temp fix in my live server. The same bug for fire breath happens. Long range damage from very far away

**Comment by poszer** [comment]
> I tried this temp fix in my live server. The same bug for fire breath happens. Long range damage from very far away

Hm. I think the problem is caused by this commit https://github.com/azerothcore/azerothcore-wotlk/commit/e9770dbb33bcf0838418de7fc03f50d9f89d6213 . Even if i say before on previous PR opened for this, these values are incorrect https://github.com/azerothcore/azerothcore-wotlk/pull/1327#issuecomment-460389193

**Comment by spinzaku** [comment]
$25 bounty!!

**Comment by poszer** [comment]
Just to say info about Wintergrasp Catapult Siege Vehicle visual bug when using Plague Barrel.
This is client side problem. If you are in vehicle and using that spell, other player see your spell correctly casted, i mean the spell will be casted in your targeted direction.
But the player who is casting it, sometimes seing that spell going in the other direction.
