### ISSUE TITLE
quest = 10804 / kindness bug

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#1980]
After eating up and down from the sky, the spiritual pterygium did not return to the air, resulting in the task could not be completed normally.

Correctly, after eating, he will fly back into the air.

![QQ截图20190618144757](https://user-images.githubusercontent.com/49540243/59659452-cd9b9600-91d8-11e9-9f05-0e45b8a34350.jpg)

Normal Video
https://www.wowhead.com/quest=10804/kindness#videos:id=85556

**Comment by FrancescoBorzi** [comment]
@forever2019 please include your AC version (commit hash)

**Comment by forever2019** [comment]
> @ forever2019请包含您的AC版本（提交哈希）

AzerothCore rev. 3fe56680c965+ 2019-06-14 05:53:21 +0000 (master branch) (Win64, Release)

**Comment by Selyria** [comment]
Yes, I can confirm that.

The kites don't climb up again 

sometimes it doesn't work at all that a dragon lands 

AzerothCore rev. 7d13c66e5c8d+ 2019-06-17 11:14:29 +0200 (master branch) (Win64, Release)

**Comment by poszer** [comment]
@forever2019 Could you please try with referenced PR ? Thanks

**Comment by forever2019** [comment]
@poszer   ＃1987 
It's normal after testing. Thank you.

**Comment by BarbzYHOOL** [comment]
@forever2019 say it in the PR page please https://github.com/azerothcore/azerothcore-wotlk/pull/1987
