### ISSUE TITLE
[Black Temple - Teron Gorefiend] Shadowy Constructs are too fast and they move to boss instantly. 

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19815]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7322#issue-2498601589

I said various gameplays and I can confirm the issue.
In gameplays it is also noticeable that constructs remain stationary one or two seconds when they appear.

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

70

### Current Behaviour

The Shadowy constructs (https://www.wowhead.com/wotlk/npc=23111/shadowy-construct#comments).
They move towards the raid like they are supposed to, and get affected by the spells correctly, but their base speed is too high,

### Expected Blizzlike Behaviour

Their base speed should match retail as shown in the videos.

### Source

https://www.youtube.com/watch?v=FzrOGTCsRwQ
https://www.youtube.com/watch?v=ty6Vbr2YWn0

### Steps to reproduce the problem

1. Get a group with at least 2 people.
2. Start the Teron Gorefiend Fight
3. Wait for the Shadow of Death debuff to appear on a person
4. Turn into a ghost in the corner of the room

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> In gameplays it is also noticeable that constructs remain stationary one or two seconds when they appear.

https://github.com/azerothcore/azerothcore-wotlk/issues/19062
