### ISSUE TITLE
Fatal crash

### ISSUE THREAD

**Issue by Lamulius** [azerothcore/azerothcore-wotlk#19818]
### Current Behaviour

Fatal crash w/o visible reasons and patterns
[gdb.txt](https://github.com/user-attachments/files/16825026/gdb.txt)

### Expected Blizzlike Behaviour

The server shouldn't crash without a reason))))

### Steps to reproduce the problem

Fatal crash w/o visible reasons and patterns

### Extra Notes

Fatal crash w/o visible reasons and patterns

### AC rev. hash/commit

AzerothCore rev. 1b4ef98bf01a+ 2024-08-31 13:55:32 +0500 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 6. Characters in world: 5.
Connection peak: 6.
Server uptime: 16 minute(s) 1 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 3ms
|- Median: 1ms
|- Percentiles (95, 99, max): 8ms, 8ms, 9ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-119-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /home/maliken/gemcraft/actual_core/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/maliken/gemcraft/actual_core/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/maliken/gemcraft/actual_core/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev

Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: mod_npc_free_professions_01.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-1v1-arena
|- mod-duel-reset
|- mod-instance-reset
|- mod-npc-free-professions
|- mod-reward-played-time

### Operating system

Ubuntu 22.04 LTS

### Custom changes or Modules

1v1arena
duelreset
instance-reset
reward_system

**Comment by heyitsbench** [comment]
Please test on a clean AC and upload the crashlogs to a [gist](https://gist.github.com/).

**Comment by Kitzunu** [comment]
I wont download random files. Upload the text to gist or pastebin

**Comment by walkline** [comment]
But you haven't answered the question. Do you have a custom changes in the core? This commit is not part of AC - https://github.com/azerothcore/azerothcore-wotlk/commit/1b4ef98bf01adb2116216b57202fe134060d765f

**Comment by perocustos41** [comment]
No confirm use last ac, 210+ online good uptime 14hour + 

Check you custom code
