### ISSUE TITLE
[PvP] Dying during Battleground prep time bugs your character 

### ISSUE THREAD

**Issue by alecsci** [azerothcore/azerothcore-wotlk#19827]
### Current Behaviour
Reported by: https://github.com/chromiecraft/chromiecraft/issues/6213
> Dying during battleground preparation time automatically ressurects the character but leaves you unable to move or use abilities, with the error message being something to the tune of "You are unable to do this while dead." The only workaround I found once stuck this way, was deserting the battleground.

I get insta revived and get the message: "You are dead!"

### Expected Blizzlike Behaviour

Be able to revive

### Source

:upside_down_face:

### Steps to reproduce the problem

1. .debug bg
2. join bg (AB/WSG)
3. before joining make sure gm is off
4. .die
5. after insta revive try to use any spell or move

### Extra Notes

I reproduced it in all bgs (AV, EOTS, AB, WSG)

### AC rev. hash/commit

5331a299621a5e10f9d6067bc7d77994dcd1cddf

### Operating system

Windows 11 x64

**Comment by laasker** [comment]
Maybe same issue of https://github.com/azerothcore/azerothcore-wotlk/issues/16516
