### ISSUE TITLE
GMs don't trigger Archivements

### ISSUE THREAD

**Issue by Raz0r1337** [azerothcore/azerothcore-wotlk#19854]
### Describe your feature request or suggestion in detail

It would be great if GM chars don't trigger achievements. I set up admin chars at the start of my server and modify the level to 255. This triggers a row of achievements like first lvl 70,80 on realm and so. I remove this from the DB, but it could be better than I don't have to do this. These achievements should only get by my friends and me normal characters.

### Describe a possible solution to your feature or suggestion in detail

Maybe a new config in the config file witch let the admin chose that GM's get achievements or not.

### Additional context

I think TrinityCore have this feature already but I'm not sure. I remember before I came to azerothcore that admins don't geht achievements.

**Comment by sudlud** [comment]
If you have .gm on, achievements should not trigger as of now.

**Comment by vanilla20002** [comment]
will not affect the achievements of non GM characters. Even if GM is the first to reach level 80, non GM characters can still achieve this achievement

**Comment by vanilla20002** [comment]
GM will not affect the achievements of non GM characters. Even if GM is the first to reach level 80, non GM characters can still achieve this achievement

**Comment by Raz0r1337** [comment]
ok, my fault. I thought I had GM on.
