### ISSUE TITLE
Monsters will ignore the path and come straight at you.

### ISSUE THREAD

**Issue by icedcolor** [azerothcore/azerothcore-wotlk#19865]
### Current Behaviour

Monsters will ignore the path and come straight to the attack, even if you attack the monster remotely from the rooftop, it will just as easily ignore the path and come straight to the attack.

### Expected Blizzlike Behaviour

Finds paths when there are no paths or when it is necessary to go over an obstacle.

### Steps to reproduce the problem

1 . Standing on a roof to attack monsters。
2 . Stand in a place that is covered by an obstacle and has a path to attack the monster.

### AC rev. hash/commit

mmaps and vmaps: enabled

### Operating system

Windows 11 x64,

**Comment by avarishd** [comment]
@heyitsbench Probably related to the leashing pr?
Running bf18b9b

https://github.com/user-attachments/assets/f7f21d9c-0ec6-4294-ad0f-eabe5259e516

**Comment by icedcolor** [comment]
It's very strange that monsters are suddenly ignoring obstacles and paths. Two days ago it was normal.

**Comment by PkllonG** [comment]
Try removing this
[de2bcbdabf19cb05682b2087b42726ee2325fe8e](https://github.com/azerothcore/azerothcore-wotlk/commit/de2bcbdabf19cb05682b2087b42726ee2325fe8e)

**Comment by PkllonG** [comment]
![image](https://github.com/user-attachments/assets/23857d8b-028f-4d85-ad67-08f00d5e37e4)
It may have something to do with this

**Comment by PkllonG** [comment]
Try this
https://github.com/azerothcore/azerothcore-wotlk/pull/19867

**Comment by Mrming1994** [comment]
@PkllonG Hello, I modified the code based on Fix (Core/Misc): Acore:: StringFormat to fmt format # 19867 and compiled it without any errors, but it did not take effect. What is the problem! 

https://github.com/user-attachments/assets/3e588b59-51e7-47ad-a6b5-c532fa9d2971
