### ISSUE TITLE
(Instance/BlackTemple): Illidan is casting Shear.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19879]
### Current Behaviour

Currently Illidan casts Shear in a couple phases of his fight.

### Expected Blizzlike Behaviour

Illidan should not cast Shear as of ~Wrath pre-patch.

### Source

Cata solo videos, [warlock](https://www.youtube.com/watch?v=qrA3OZyy7VU) and [rogue](https://www.youtube.com/watch?v=C5k-wr3fkkY)

### Steps to reproduce the problem

1. Engage Illidan.
2. Observe his Shearing.
3. What a hooligan.

### AC rev. hash/commit

9dae87595dc2f0f14d06ce7984250535630f54df

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Nyeriah** [comment]
I'm not sure about this, tried finding anything in the patch notes/web but found nothing. I know at some point in time abilities were changed so abilities targeted to tanks would only hit tanks etc. to make encounters soloable, gonna tag this for further research

**Comment by heyitsbench** [comment]
https://web.archive.org/web/20081104084554/http://blue.mmo-champion.com/12/10532281654-existing-raid-content-changes.html

> To coincide with the upcoming new talents and mechanic changes for classes in the next patch, we are making some adjustments in existing raid content to provide a smooth transition when the upcoming patch is released.
> [...]
> On top of this Illidan is also doing his part and will stop casting Shear on players.

**Comment by Nyeriah** [comment]
Okay
