### ISSUE TITLE
[Black Temple] Illidari Assassin: some abilities are missing.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19876]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7334#issue-2503156619

I tested the issue and I can confirm that the mob doesn't use [Paralyzing Poison](https://www.wowhead.com/tbc/it/spell=3609/paralyzing-poison) and [Vanish](https://www.wowhead.com/tbc/it/spell=39667/vanish) abilities.

Source: [WoWHead](https://www.wowhead.com/tbc/it/guide/trash-mobs-black-temple-strategy-burning-crusade-classic)
![guide](https://github.com/user-attachments/assets/a975ba22-a0a3-481d-ad9f-04cd836ecdc1)

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

70

### Current Behaviour

Illidari Assassins don't do -Vanish- and -Paralyzing Poison- spells.
wacth this Vanish cast from Illidari Assassin at 1:26:45 https://www.youtube.com/watch?v=F-UhkX0DMQM&t=5555s

### Expected Blizzlike Behaviour

Illidari Assassins must do the vanish and paralyzing poison spells.

### Source

missing spell 1: https://www.wowhead.com/tbc/it/spell=39667/vanish
missing spell 2: https://www.wowhead.com/tbc/it/spell=3609/paralyzing-poison

### Steps to reproduce the problem

1. type .tele bt
2. going to Illidari Assassin trash mob located after Mother Shazrah and before Illidari Council
3. pull it and waiting for Vanish and Paralyzing cast/debuff.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/30a790117be921ed0eff513322af1793995b2b4d

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by elthehablo** [comment]
Are we sure about the spell id for paralyzing poison?

**Comment by elthehablo** [comment]
It's probably right, but would like to see it backed up with a sniff

**Comment by elthehablo** [comment]
Would also be nice to get that to be able to determine timers on that

**Comment by Carriola-wotlk** [comment]
Actually, the bug is a bit different from how it was described in this ticket. The first spawned Assassin only casts Paralyzing Poison and Vanish abilities (and doesn't cast Riposte). The other 3 spawns don't cast anything, they only perform melee attacks

**Comment by Rorschach91** [comment]
> Actually, the bug is a bit different from how it was described in this ticket. The first spawned Assassin only casts Paralyzing Poison and Vanish abilities (and doesn't cast Riposte). The other 3 spawns don't cast anything, they only perform melee attacks

Right, I only said that to you. I'm sorry guys but in these last days I was focused on another report and I forgot to edit this isssue.
