### ISSUE TITLE
[BUG] CHAT SETTINGS

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#1988]
Description: Level requirement for characters to be able to write in chat channels , don't work ! ! !

ChatLevelReq.Channel = 1

BRANCH(ES): Master
AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/e71d70cec486c80002ff6cabc80358edc0be1507
OS: windows server 2016

**Comment by poszer** [comment]
It's not working for GM, Admin ranks. It's working for players.
![chatSEtting](https://user-images.githubusercontent.com/41213210/59886431-35133a80-93bf-11e9-8bd0-088793973939.png)
Closing this
