### ISSUE TITLE
[BUG] Motd

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#1989]
Description: Message of the Day, displayed at login.
Motd = "Welcome to an AzerothCore server."

Don't Work!

BRANCH(ES): Master
AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/e71d70cec486c80002ff6cabc80358edc0be1507
OS: windows server 2016

**Comment by FrancescoBorzi** [comment]
O_o weird, it worked for me last time I've tried.

**Comment by poszer** [comment]
Can someone confirm this ?

**Comment by Hir0shi** [comment]
Does not Show ! Motd 

Last version AZ.

**Comment by poszer** [comment]
I didn't ask you!

**Comment by Stoabrogga** [comment]
Cannot confirm. Tested with commit 5d3cd9a0b4f99515e1d9f84124ae89ae17b2dc54 , MotD is shown at login.

**Comment by poszer** [comment]
Closing this. MotD is shown
![acText](https://user-images.githubusercontent.com/41213210/59883482-8ae2e500-93b5-11e9-937e-6b0f43716564.png)

**Comment by Hir0shi** [comment]
how to changed moted !
this server runs

**Comment by poszer** [comment]
> how to changed moted !
> this server runs ....

Maybe to ban you from here?

**Comment by FrancescoBorzi** [comment]
Just to make it clear:

- It is allowed to change "Welcome to an AzerothCore server"
- IT IS **NOT** ALLOWED TO CHANGE "This server runs on AzerothCore www.azerothcore.org"

**Comment by poszer** [comment]
> Just to make it clear:
> 
> * It is allowed to change "Welcome to an AzerothCore server"
> * IT IS **NOT** ALLOWED TO CHANGE "This server runs on AzerothCore [www.azerothcore.org](http://www.azerothcore.org)"

Great. Here we go, change your MOTD!!!! This is excatly what you want :rofl: :rocket:   @Hir0shi  ^.^
https://github.com/azerothcore/azerothcore-wotlk/blob/00338506abd1084076ba0cf9c03a12a5ae8e99e7/src/server/worldserver/worldserver.conf.dist#L1435

**Comment by BarbzYHOOL** [comment]
Tired of his bullshit, and wasting contributors' precious time, he's banned for 30 days.
