### ISSUE TITLE
Feature: Add more git ignore path to suit for Visual studio

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#19896]
### Describe your feature request or suggestion in detail

I'm a beginner for C++, most of the modification of the source code is through Visual studio 2022, not familiar with the command to commit git. vs 2022 will produce a .vs directory and an out directory, each time you need to commit to ignore, and then back to ignore, very inconvenient, so is it possible to ignore these two folders within the .gitignore, and then I'm not familiar with it, but I'm not familiar with it, so I'm not familiar with it. So is it possible to ignore these two folders in .gitignore, to make it easier for many people who use VS to modify source code?

/.vs
/out

**Comment by Kitzunu** [comment]
Never had this issue
