### ISSUE TITLE
[Ulduar] Algalon the door is not activated

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#199]
**Description**:
you can not start the meeting with Algalon the Observer.
**Current behaviour**: Tell us what happens
When attempting to activate [Access to the celestial planetarium] ObjectID: 194752
not open the door to the final boss.
**Expected behaviour**: Tell us what should happen instead
The door should be unlocked after defeat Yogg-Saron
activating the following object: [Access to the celestial planetarium] ObjectID: 194752

**Branch(es)**: / 1.x /

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/47d1ee4f559fc3e98f708ad32717dcd39d032ba7

**Operating system**:  Windows Server 2008 R2

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

-passive anticheat
-transmogrifer
##

**Comment by Motorheadx** [comment]
that would open the door to boss need to go up the chain of quests with Muradin

**Comment by franklampardahar** [comment]
it work perfect . before you must need complete quest to receive key . Close this issue
