### ISSUE TITLE
High Overlord Saurfang db errors

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#1990]
High Overlord Saurfang

##### SMALL DESCRIPTION:

While in ICC fighting with these mobs arround, pull them close to the place where is High Overlord Saurfang. When he attack the mobs, check your DB log. 
![overlord](https://user-images.githubusercontent.com/41213210/59883289-cfba4c00-93b4-11e9-9ca7-dd74f120e221.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be without DB errors ^^

##### CURRENT BEHAVIOUR:

When High Overlord Saurfang attack the mobs, there are DB errors showing logs, missing creature text.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go in Icecrown
2. Attack the mobs and pull them close to High Overlord Saurfang
3. Check DB Log

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/a16ff7363ec9f6831dd0ec2fa84c2f5976d7c724

**Comment by poszer** [comment]
Info : Looks like wrong creature spawned in Icecrown (Entrance)

**Comment by Stoabrogga** [comment]
Yes, seems like the correct creature ID is 37187 instead of 32315. 32315 is used for the "Battle for the Undercity" event and should only be used there. But as we discussed recently it seems that 37187 has currently only the Saurfang outro event scripted, not the intro.
