### ISSUE TITLE
(BlackTemple): Illidan stage 2 after cast line of fire will drop to ground  and run to next station but not by fly

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#19925]
### Current Behaviour

Illidan stage 2 after cast line of fire will drop to ground and run to next station but not fly to next station.
the new PR for Illidan still have the problem reference to this issue.
 https://github.com/azerothcore/azerothcore-wotlk/issues/18551

### Expected Blizzlike Behaviour

Will keep fly to next station, it always fly in sky at stage 2.

### Steps to reproduce the problem

.go c 148736
fight with Illidan and to stage 2

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/cf95c1dfbdb252cfd18e32f8bdfef0da8ff01092 2024-09-07 15:39:31 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 24 second(s)
Update time diff: 100ms. Last 176 diffs summary:
|- Mean: 100ms
|- Median: 100ms
|- Percentiles (95, 99, max): 101ms, 101ms, 151ms
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80402
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-1-pve
Worldserver listening connections on port %u
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_03_00.sql
Latest WorldDatabase update: 2024_09_09_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-eluna

### Operating system

Debian 12 PVE

**Comment by Rorschach91** [comment]
This issue has been fixed.
