### ISSUE TITLE
Custom Items DBC Display didnt work and .look spell ingame failed

### ISSUE THREAD

**Issue by Effect90** [azerothcore/azerothcore-wotlk#1993]
Custom Items DBC Display didnt work and .look spell ingame failed

If i create custom items with normally wotlk displays, i cant see the
weapon/item display in my bag ingame. "Only Red ?" We Hv tryed to pack the new dbc
in Install Folder Data, and as Patch.mpq But it didnt work ...

If i type .look spell ... in chat to search for spells, server says only "Spell not found"
Tryed english and german dbc's but it doesnt work ... 

It makes the work very hard, canno find spells to testing for custom npc/bosses

Do y can help me guys? please

Have a nice day!

**Comment by solidmaxtor** [comment]
This is not an issue, you want to customize things but here the core is developed as the original.
Maybe you can look for help in the Discord for other people who customize things.

**Comment by poszer** [comment]
@Effect90 It's best for you to open question here about this : 
https://stackoverflow.com/search?q=azerothcore

**Comment by Effect90** [comment]
thanks
