### ISSUE TITLE
(Instance/BlackTemple): No message for opening the door to the Den of Mortal Delights.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#19941]
### Current Behaviour

When the door is opened to the Den of Mortal Delights, nothing happens.

### Expected Blizzlike Behaviour

[Black Temple Trigger](https://wowgaming.altervista.org/aowow/?npc=22984) should emote that the door has been opened.

### Source

[Retail TBC](https://www.youtube.com/watch?v=9kTY4qbebAk&t=436s)

### Steps to reproduce the problem

1. `.tele bt`
2. Clear all of the bosses prior to Mother Shahraz.
3. Observe no message when the door is opened.

### AC rev. hash/commit

321ac4a8c23ba5e006239fceb89eb8409135bed4

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

**Comment by Nyeriah** [comment]
No message for opening the door after najentus either

**Comment by heyitsbench** [comment]
> No message for opening the door after najentus either

Thank you for pointing that out, I noticed the extra quote on the creature's AoWoW page, but I wasn't sure when it was supposed to occur.
