### ISSUE TITLE
[Black Temple] Mother Shahraz Fatal Attraction bugs

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19940]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7348#issue-2513144012

Report Edited: 09/13/24

1)  ̶W̶h̶e̶n̶ ̶a̶ ̶p̶l̶a̶y̶e̶r̶ ̶l̶i̶n̶k̶e̶d̶ ̶b̶y̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶g̶o̶ ̶f̶a̶r̶ ̶e̶n̶o̶u̶g̶h̶ ̶t̶o̶ ̶m̶a̶k̶e̶ ̶t̶h̶e̶ ̶"̶c̶h̶a̶i̶n̶s̶"̶ ̶d̶i̶s̶a̶p̶p̶e̶a̶r̶,̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶d̶e̶b̶u̶f̶f̶ ̶s̶h̶o̶u̶l̶d̶ ̶v̶a̶n̶i̶s̶h̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶p̶l̶a̶y̶e̶r̶.̶

2) Regarding a possible white list, I watched some videos and I noticed that players are never been teleported in too closed areas or where they cannot move away as fast as possible. 
In addition I can confirm that players are teleported in places when they shouldn't be teleported.
Evidence: [Youtube](https://youtu.be/SwzVduzhcy8)

3̶)̶ ̶W̶h̶e̶n̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶a̶r̶e̶ ̶a̶f̶f̶l̶i̶c̶t̶e̶d̶ ̶b̶y̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶s̶h̶o̶u̶l̶d̶n̶'̶t̶ ̶b̶e̶ ̶t̶a̶r̶g̶e̶t̶t̶e̶d̶ ̶b̶y̶ ̶[̶S̶i̶n̶i̶s̶t̶e̶r̶ ̶B̶e̶a̶m̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶w̶o̶w̶h̶e̶a̶d̶.̶c̶o̶m̶/̶t̶b̶c̶/̶s̶p̶e̶l̶l̶=̶4̶0̶8̶5̶9̶/̶s̶i̶n̶i̶s̶t̶e̶r̶-̶b̶e̶a̶m̶)̶ ̶a̶b̶i̶l̶i̶t̶y̶.̶
̶E̶v̶i̶d̶e̶n̶c̶e̶:̶ ̶[̶Y̶o̶u̶t̶u̶b̶e̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶y̶o̶u̶t̶u̶.̶b̶e̶/̶g̶d̶O̶u̶Z̶C̶1̶K̶d̶5̶8̶)̶
4)  ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶s̶o̶m̶e̶t̶i̶m̶e̶s̶ ̶a̶f̶f̶l̶i̶c̶t̶s̶ ̶o̶n̶e̶ ̶t̶a̶r̶g̶e̶t̶ ̶o̶n̶l̶y̶.̶ ̶I̶t̶ ̶s̶h̶o̶u̶l̶d̶ ̶a̶f̶f̶l̶i̶c̶t̶ ̶2̶ ̶o̶r̶ ̶3̶ ̶t̶a̶r̶g̶e̶t̶s̶.̶

5) D̶a̶m̶a̶g̶e̶ ̶m̶e̶c̶h̶a̶n̶i̶c̶s̶ ̶m̶u̶s̶t̶ ̶b̶e̶ ̶a̶n̶a̶l̶y̶z̶e̶d̶ ̶b̶e̶t̶t̶e̶r̶,̶ ̶b̶u̶t̶ ̶a̶c̶t̶u̶a̶l̶l̶y̶ ̶I̶ ̶c̶a̶n̶ ̶c̶o̶n̶f̶i̶r̶m̶ ̶t̶h̶a̶t̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶d̶a̶m̶a̶g̶e̶ ̶i̶s̶ ̶a̶b̶s̶u̶r̶d̶,̶ ̶a̶n̶d̶ ̶I̶'̶v̶e̶ ̶t̶h̶e̶ ̶s̶u̶s̶p̶e̶c̶t̶ ̶t̶h̶a̶t̶ ̶t̶h̶e̶r̶e̶ ̶a̶r̶e̶ ̶t̶o̶o̶ ̶m̶u̶c̶h̶ ̶d̶a̶m̶a̶g̶e̶ ̶o̶u̶t̶p̶u̶t̶s̶ ̶i̶n̶ ̶a̶ ̶s̶i̶n̶g̶l̶e̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶

 ̶R̶e̶g̶a̶r̶d̶i̶n̶g̶ ̶P̶o̶i̶n̶t̶ ̶1̶:̶

̶W̶a̶t̶c̶h̶i̶n̶g̶ ̶t̶h̶i̶s̶ ̶[̶v̶i̶d̶e̶o̶ ̶c̶l̶i̶p̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶y̶o̶u̶t̶u̶b̶e̶.̶c̶o̶m̶/̶w̶a̶t̶c̶h̶?̶v̶=̶N̶2̶Q̶E̶G̶m̶S̶q̶g̶Z̶E̶)̶ ̶y̶o̶u̶ ̶w̶i̶l̶l̶ ̶n̶o̶t̶i̶c̶e̶ ̶t̶h̶a̶t̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶D̶e̶b̶u̶f̶f̶ ̶v̶a̶n̶i̶s̶h̶ ̶i̶f̶ ̶t̶h̶e̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶m̶o̶v̶e̶ ̶f̶a̶r̶ ̶e̶n̶o̶u̶g̶h̶ ̶a̶p̶a̶r̶t̶ ̶t̶o̶ ̶b̶r̶e̶a̶k̶ ̶t̶h̶e̶ ̶c̶h̶a̶i̶n̶s̶.̶
̶O̶n̶ ̶A̶C̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶d̶e̶b̶u̶f̶f̶ ̶s̶t̶i̶l̶l̶ ̶p̶e̶r̶s̶i̶s̶t̶ ̶i̶f̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶m̶o̶v̶e̶ ̶a̶w̶a̶y̶,̶ ̶c̶a̶u̶s̶i̶n̶g̶ ̶a̶ ̶c̶h̶a̶i̶n̶ ̶r̶e̶t̶u̶r̶n̶ ̶(̶a̶n̶d̶ ̶o̶b̶v̶i̶o̶u̶s̶l̶y̶ ̶d̶a̶m̶a̶g̶e̶)̶ ̶i̶f̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶l̶i̶n̶k̶e̶d̶ ̶g̶e̶t̶ ̶c̶l̶o̶s̶e̶ ̶a̶g̶a̶i̶n̶.̶

 ̶E̶v̶i̶d̶e̶n̶c̶e̶:̶ ̶[̶V̶i̶d̶e̶o̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶y̶o̶u̶t̶u̶.̶b̶e̶/̶S̶w̶z̶V̶d̶u̶z̶h̶c̶y̶8̶)̶ ̶f̶r̶o̶m̶ ̶m̶i̶n̶u̶t̶e̶ ̶0̶:̶1̶4̶
 
̶R̶e̶g̶a̶r̶d̶i̶n̶g̶ ̶P̶o̶i̶n̶t̶ ̶3̶:̶

W̶a̶t̶c̶h̶i̶n̶g̶ ̶t̶h̶i̶s̶ ̶[̶v̶i̶d̶e̶o̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶y̶o̶u̶t̶u̶.̶b̶e̶/̶g̶d̶O̶u̶Z̶C̶1̶K̶d̶5̶8̶)̶ ̶y̶o̶u̶ ̶w̶i̶l̶l̶ ̶n̶o̶t̶i̶c̶e̶ ̶t̶h̶a̶t̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶a̶f̶f̶l̶i̶c̶t̶e̶d̶ ̶b̶y̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶c̶o̶u̶l̶d̶ ̶b̶e̶ ̶a̶t̶t̶a̶c̶k̶e̶d̶ ̶b̶y̶ ̶[̶S̶i̶n̶i̶s̶t̶e̶r̶ ̶B̶e̶a̶m̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶w̶w̶w̶.̶w̶o̶w̶h̶e̶a̶d̶.̶c̶o̶m̶/̶t̶b̶c̶/̶s̶p̶e̶l̶l̶=̶4̶0̶8̶5̶9̶/̶s̶i̶n̶i̶s̶t̶e̶r̶-̶b̶e̶a̶m̶)̶.̶ ̶I̶'̶v̶e̶ ̶t̶h̶e̶ ̶s̶u̶s̶p̶e̶c̶t̶ ̶t̶h̶a̶t̶ ̶t̶h̶e̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶a̶f̶f̶l̶i̶c̶t̶e̶d̶ ̶b̶y̶ ̶F̶a̶t̶a̶l̶ ̶A̶t̶t̶r̶a̶c̶t̶i̶o̶n̶ ̶a̶r̶e̶ ̶t̶e̶m̶p̶o̶r̶a̶r̶i̶l̶y̶ ̶i̶m̶m̶u̶n̶e̶ ̶t̶o̶ ̶S̶i̶n̶i̶s̶t̶e̶r̶ ̶B̶e̶a̶m̶,̶ ̶b̶u̶t̶ ̶I̶ ̶c̶a̶n̶n̶o̶t̶ ̶b̶e̶ ̶s̶u̶r̶e̶.̶
̶I̶t̶ ̶m̶a̶y̶ ̶a̶l̶s̶o̶ ̶b̶e̶ ̶a̶ ̶p̶r̶o̶b̶l̶e̶m̶ ̶c̶a̶u̶s̶e̶d̶ ̶b̶y̶ ̶t̶h̶e̶ ̶f̶a̶c̶t̶ ̶t̶h̶a̶t̶ ̶I̶ ̶t̶r̶i̶e̶d̶ ̶t̶h̶i̶s̶ ̶b̶o̶s̶s̶ ̶w̶i̶t̶h̶ ̶o̶n̶l̶y̶ ̶5̶ ̶p̶l̶a̶y̶e̶r̶s̶.̶ ̶I̶ ̶n̶e̶e̶d̶ ̶t̶o̶ ̶t̶r̶y̶ ̶t̶h̶i̶s̶ ̶b̶o̶s̶s̶ ̶a̶g̶a̶i̶n̶ ̶w̶i̶t̶h̶ ̶m̶o̶r̶e̶ ̶p̶e̶o̶p̶l̶e̶.̶ ̶
̶

----------------------------------------------------------------------------------------------------------------------------------------

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Fatal attraction teleport now works, however sometimes people get teleported into a corner, making separating fast enough impossible. I know the tooltip of the mechanic says the teleport location is random but in all my years doing TBC raiding we never had an issue with people jammed into a corner and us dying/wiping because of that. There must be whitelist of acceptable teleport locations somewhere.

Fatal attraction does its 3k dmg multiple times in the same tick - does over 50k dmg in a single second. 

Fatal attraction chains appear again and start doing dmg if players get close to each other after initially breaking them.

### Expected Blizzlike Behaviour

The teleport location is in the middle of an open space in the room.

The shadow dmg is done once every second.

Once broken the chains should not reappear if players get closer that 25 yards to each other.

### Source

https://www.wowhead.com/npc=22947/mother-shahraz

14:23 in https://www.youtube.com/watch?v=cvMTW85NQJU

### Steps to reproduce the problem

Engage Mother Shahraz with more than 4 people.
Wait for Fatal Attraction to be cast on 3 of them.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/dccec8764408a58eb01ba85827f8686b196d370c

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Rorschach91** [comment]
Report updated.

**Comment by Nyeriah** [comment]
Tip. You can enable timestamps in combat log. 

I can’t find the source of the “absurd” damage. If 3 players are stacked, it will tick and damage all of them every second. I did mention however that the damage should be exempt from the tuning spell list (so this part might be a chromiecraft issue if it wasn’t)

**Comment by Rorschach91** [comment]
The problem is the number of hits per explosion.

As I saw reading guides and watching gameplays, if players linked by Fatal Attraction stay stacked, they should cause damage in this way:

First Explosion:
Player one: 1k damage to itself (1 hit) and 1k damage to other players linked with it (1 hit player 2 - 1 hit player 3).
Player two: 1k damage to itself (1 hit) and 1k damage to other players linked with it (1 hit player 1 - 1 hit player 2).
Player three: 1k damage to itself (1 hit) and 1k damage to other players linked with it (1 hit player 1 - 1 hit player 2).

In conclusion: 3k damage per player.

Second Explosion:
Player one: 2k damage to itself (1 hit) and 2k damage to other players linked with it (1 hit player 2 - 1 hit player 3).
Player two: 2k damage to itself (1 hit) and 2k damage to other players linked with it (1 hit player 1 - 1 hit player 2).
Player three: 2k damage to itself (1 hit) and 2k damage to other players linked with it (1 hit player 1 - 1 hit player 2).

In conclusion: 6k damage per player.

Third Explosion:
Player one: 3k damage to itself (1 hit) and 3k damage to other players linked with it (1 hit player 2 - 1 hit player 3).
Player two: 3k damage to itself (1 hit) and 3k damage to other players linked with it (1 hit player 1 - 1 hit player 2).
Player three: 3k damage to itself (1 hit) and 3k damage to other players linked with it (1 hit player 1 - 1 hit player 2).

In conclusion: 9k damage per player.

Etc.......

This is how it currently works on AC (unless something has changed during this week):

First Explosion:
Player one: 1k + 1k damage to itself (2 hit)  and 1k + 1k damage to other players linked with it (2 hit player 2 - 2 hit player 3).
Player two: 1k + 1k damage to itself (2 hit) and 1k + 1k damage to other players linked with it (2 hit player 2 - 2 hit player 2).
Player three: 1k + 1k damage to itself (2 hit) and 1k + 1k damage to other players linked with it (2 hitplayer 2 - 2 hit player 2).

In conclusion: 9k damage per player.


Second Explosion:
Player one: 2k + 2k damage to itself (2 hit)  and 2k + 2k damage to other players linked with it (2 hit player 2 - 2 hit player 3).
Player two: 2k + 2k damage to itself (2 hit) and 2k + 2k damage to other players linked with it (2 hit player 2 - 2 hit player 2).
Player three: 2k + 2k damage to itself (2 hit) and 2k + 2k damage to other players linked with it (2 hit player 2 - 2 hit player 2).

In conclusion: 18k damage per player.

Third Explosion:
Player one: 3k + 3k damage to itself (2 hit)  and 3k + 3k damage to other players linked with it (2 hit player 2 - 2 hit player 3).
Player two: 3k + 3k damage to itself (2 hit) and 2k + 2k damage to other players linked with it (2 hit player 2 - 2 hit player 2).
Player three: 3k + 3k damage to itself (2 hit) and 2k + 2k damage to other players linked with it (2 hit player 2 - 2 hit player 2).

In conclusion: 27k damage per player.

With this damage players die with the second explosion. They have no time to run away (they lose 85% of their hp with the first explosion).

At least this is what I understood during these days that i've passed watching gameplays and reading guides.
It could be wrong, but I found no other sources.

**Comment by Nyeriah** [comment]
Conclusion: the explosion is hitting the player itself and shouldnt?

**Comment by Nyeriah** [comment]
spell is procing once for every player around, so if there are 2 players, it procs twice

**Comment by Nyeriah** [comment]
@Rorschach91 thanks for looking into this

**Comment by Rorschach91** [comment]
One less problem. Anyway I updated the report.
