### ISSUE TITLE
[Black Temple - Illidan] Flames of Azinoth issues.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#19954]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7351#issue-2513928203

1. Blades of Azzinoth are 40 yards apart from each other and this is right. 

![cattura](https://github.com/user-attachments/assets/8a36c510-6ee0-4cf5-a2a9-be3cafa49b03)

2. If a Flame of Azzinoth goes too far from its glaive (beyond 40 yards), it goes in enrage (It seems that this feature works well on AC).

3. Watching some videos from TBC classic (an [example](https://www.youtube.com/watch?v=tWw8eF-8zgE)), you can see that if a player move more than 40 yard from a Glaive of Azzinoth, the Flame of Azzinoth linked to that glaive charge them (naturally, if during this charge Flame of Azzinoth goes over 40 yards it goes in enrage).
On AC this mechanic is clearly bugged.
Evidence: [Youtube](https://youtu.be/wrFCSDGLvsw) (consider that in this video Avelle is exactly upon the Glaive of Azzinoth).

Note: It seems that the players that have Flames of Azzinoth in aggro, are not charged (they are excluded from charge mechanic).

4. Looking at guides and some videos I can say that [Flame Blast](https://www.wowhead.com/tbc/spell=40631/flame-blast) and [Blaze](https://www.wowhead.com/tbc/spell=40611/blaze) abilities are missing from Flames of Azzinoth.

Source: Always [this](https://youtu.be/tWw8eF-8zgE).
![evidence 2](https://github.com/user-attachments/assets/14a49d78-e683-4488-9228-db556b77815f)

5. Flames of Azzinoth should have AI delay.

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[The Phase 2](https://www.wowhead.com/npc=112831/flame-of-azzinoth) adds spawn already enraged, doing 1 shot dmg to tanks and moving lightning fast.

### Expected Blizzlike Behaviour

1 Flame of Azinoth should spawn on each of his twinblades. They should only [enrage](https://www.wowhead.com/spell=39869/uncaged-wrath?dd=33) and get the extra 500% dmg and 200% speed if taken outside the required range (I couldnt find a reliable source of how many yards we are talking about sadly).

### Source

https://www.wowhead.com/npc=22917/illidan-stormrage

### Steps to reproduce the problem

Pull boss
Get to phase 2

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fafd351e44b4556b9ceda4bfaa72c6e5f22c3f78

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Grimdhex** [comment]
I'm not sure of the rest issues:

- Blades of Azzinoth position are right or not ? Otherwise, I will need sniffs.

For: "If a Flame of Azzinoth goes too far from its glaive (beyond 40 yards), it goes in enrage (It seems that this feature works well on AC).". Is it an issue or not finally ?

**Comment by Rorschach91** [comment]
> Blades of Azzinoth position are right or not ? Otherwise, I will need sniffs.

Yes, they are right. It wasn't an issue, but a constatation.

> For: "If a Flame of Azzinoth goes too far from its glaive (beyond 40 yards), it goes in enrage (It seems that this feature works well on AC).". Is it an issue or not finally ?

It is another constatation, not a bug.

> "Flames of Azzinoth should have AI delay." Could you specify ?

Simply, when they spawn, they should stay immobile without attacking for 1.5 - 2 seconds.

In a few words, Flames of Azzinoth have an issue with charge mechanics, AI delay is not present (they insta-attack when they spawn), and [Flame Blast](https://www.wowhead.com/tbc/spell=40631/flame-blast) and [Blaze](https://www.wowhead.com/tbc/spell=40611/blaze) abilities are missing.

This report looks strange for the discussion that we had under the original CC issue.
