### ISSUE TITLE
Feature: Changed Flight Master Behaviour (TBC - Dark Portal)

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#19953]
### Describe your feature request or suggestion in detail

For the times where Insta Fllight Path or Other Flight paths have been discovered in TBC, the Flight Masters in the Dark Portal (in outland) should allow you to flight to whaterver Flight Path  is avaiaible, if no Flight Path is avaiable should required the quest as is intended in TBC. 

Also if there's no avaiiable flight path, it should say so instead of (in my case of testing) toggle the Insta Flight path. 
![image (1)](https://github.com/user-attachments/assets/4768fd9e-89da-4e88-8b7d-de445739c887)

Horde Flight Master "Vlagga Freyfeather" ID: 18930
Alliance Flight Master "Amish Wildhammer" ID: 18931

**Comment by Kitzunu** [comment]
this looks more like a bug if anything. Use the proper template
