### ISSUE TITLE
Enemies are evading and retreating after 10 seconds if they are not hit by something other than a dot.

### ISSUE THREAD

**Issue by OojahSagirin** [azerothcore/azerothcore-wotlk#19952]
### Current Behaviour

If mobs are not 'hit' by spells such as mind flay or warlock pets they are evading after 10 seconds of combat.

### Expected Blizzlike Behaviour

Mobs should not evade and retreat because they are not hit for 10 seconds

### Steps to reproduce the problem

cast any combination of dots on a mob and wait 10 seconds. I've tried this on a warlock and a priest. 

### AC rev. hash/commit

maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-playerbots
AC> Update time diff: 198ms with 0 players online
Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 5ms, 198ms

### Operating system

Windows 11 x64

### Custom changes or Modules

Playerbots and AHbot

**Comment by heyitsbench** [comment]
Feel free to provide a source and a revision hash.

**Comment by OojahSagirin** [comment]
Ah. silly me. My putty wasn't showing that many lines scrolling up.

AC> server debug
AC> AzerothCore rev. 6f5b504e4cfa 2024-09-07 14:27:11 +0800 (Playerbot branch) (Unix, Release, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 15 minute(s) 5 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 5ms, 5ms
Using SSL version: OpenSSL 3.0.13 30 Jan 2024 (library: OpenSSL 3.0.13 30 Jan 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 101106
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.1.0-22-amd64
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: world_playerbots_rpg_races.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-playerbots

**Comment by heyitsbench** [comment]
You might have missed the part where I asked for a source as well. According to this issue: https://github.com/azerothcore/azerothcore-wotlk/issues/5116 as well as lots of testing on Classic and some older pictures of WowEdit, it very much appears that creatures are supposed to evade after a set time without being actively attacked.

**Comment by OojahSagirin** [comment]
I see. It's just a feeling I have. I'm not moving the mobs more than a few yards starting combat this morning and i'm experiencing this leashing that seems unintended. It just seems unintended as I don't remember having this much trouble when I dot farmed on wotlk classic.

**Comment by OojahSagirin** [comment]
https://youtu.be/3OQHycwQ49U?si=zkJgGH0CAqksJRuP

starting around 2:40 you can see a lot of mobs being active in combat for more than 10 seconds without leashing. Granted I’m only in my low 20s and I haven’t tested this area it gives an example of “dots only” being sufficient to keep these mobs from evading after 10 seconds.

I will do more testing in this specific area that is in the YouTube video but my findings this morning I wasn’t moving at all and maybe pulling the mob a yard or two.

**Comment by Nyeriah** [comment]
You’re using an outdated source (player bots).

**Comment by OojahSagirin** [comment]
I see now. I'm submitting this issue in the wrong repository. I'm still learning. I'll get there someday. Thanks for the help
