### ISSUE TITLE
Crash! (Some Kind of Memory Leak)

### ISSUE THREAD

**Issue by PadreWoW** [azerothcore/azerothcore-wotlk#19960]
### Current Behaviour

Just go to 
https://www.wowhead.com/wotlk/quest=12416/heated-battle
Start attack Frigid Abomination Attacker (https://www.wowhead.com/wotlk/npc=27531/frigid-abomination-attacker) or any mob there
After some time the server will go down
The problem is intermittent and does not always reproduce.
MaxCoreStuckTime = 10

I think, the problem is here:
https://github.com/azerothcore/azerothcore-wotlk/commit/c929b95172c88d5257077dbbdebb9ca8fabbad26

![изображение](https://github.com/user-attachments/assets/015fc128-fe9f-4a9b-bffa-3a4831b0ba74)

![изображение](https://github.com/user-attachments/assets/768fb766-14e7-4d83-a7a5-fbeb5033a086)

![изображение](https://github.com/user-attachments/assets/35f326c7-6f9e-4fcc-bc33-655460f7034d)

[fa1f49be1a2d_worldserver.exe_[13-9_14-11-37].dmp](https://github.com/user-attachments/files/16992958/fa1f49be1a2d_worldserver.exe_.13-9_14-11-37.dmp)

### Expected Blizzlike Behaviour

Should not crash

### Steps to reproduce the problem

MaxCoreStuckTime = 10

1) Just go to https://www.wowhead.com/wotlk/quest=12416/heated-battle
2) Start attack Frigid Abomination Attacker (https://www.wowhead.com/wotlk/npc=27531/frigid-abomination-attacker)
3) After some time the server will go down

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5263b0aee18b825ff7f46fb861094ff1836693e

### Operating system

WinServ 2019

### Custom changes or Modules

mod_transmog
mod_learnspell
mod_anticheat

**Comment by heyitsbench** [comment]
Cannot reproduce. Please provide the actual crashlog instead of the dump file (.txt, not .dmp).

**Comment by heyitsbench** [comment]
No memory leak, result of https://github.com/azerothcore/azerothcore-wotlk/commit/edd7e10dfc7651ed2657a09d5411771831c8ec1e.

**Comment by PadreWoW** [comment]
CharacterDatabase.SynchThreads = 1 - CRASH
CharacterDatabase.SynchThreads = 2 - NO CRASH

**Comment by PadreWoW** [comment]
How about log?

**Comment by PadreWoW** [comment]
> No memory leak, result of [edd7e10](https://github.com/azerothcore/azerothcore-wotlk/commit/edd7e10dfc7651ed2657a09d5411771831c8ec1e).

You found problem?

**Comment by hermensbas** [comment]
> No memory leak, result of [edd7e10](https://github.com/azerothcore/azerothcore-wotlk/commit/edd7e10dfc7651ed2657a09d5411771831c8ec1e).

Not sure thats the cause of the above problem, but we had to revert that commit is caused nonstop crashes during init.
[Reference bug](https://github.com/liyunfan1223/mod-playerbots/issues/526)

**Comment by PadreWoW** [comment]
Problem was really here [edd7e10](https://github.com/azerothcore/azerothcore-wotlk/commit/edd7e10dfc7651ed2657a09d5411771831c8ec1e).

No crash after revert this commit
Many thanks

**Comment by Nyeriah** [comment]
That you found the solution to your problem doesn't mean its fixed

**Comment by heyitsbench** [comment]
I am unable to reproduce this crash/hang on a clean AC. If anyone is able to do so, please provide steps.

**Comment by PadreWoW** [comment]
> I am unable to reproduce this crash/hang on a clean AC. If anyone is able to do so, please provide steps.

I am able to catch this crash only on Warrior (Fury-Arms) - gear on screenshot above

**Comment by heyitsbench** [comment]
Yes, I can see from the crashlog that the spell causing the issue is Deep Wounds, but I've tested with Deep Wounds and it's causing no issues for me.

**Comment by PadreWoW** [comment]
> Yes, I can see from the crashlog that the spell causing the issue is Deep Wounds, but I've tested with Deep Wounds and it's causing no issues for me.

Just use this build: https://www.wowhead.com/wotlk/ru/talent-calc/warrior/0502030123-305050130525010250120501351
And my gear
Do not use only deep wounds - use all abilities
And the probability of getting a crash increases if you hit many mobs at once

**Comment by heyitsbench** [comment]
Tested as you said, still no crash.

**Comment by hermensbas** [comment]
I wasnt able to reproduce neither on the AC branch, other then that specific commit created issue on the synced branch of playerbots.

> The crashlog provided is not using a valid AC revision. Please retest with a clean AC.

Tried wasnt able too

**Comment by PkllonG** [comment]
> Problem was really here [edd7e10](https://github.com/azerothcore/azerothcore-wotlk/commit/edd7e10dfc7651ed2657a09d5411771831c8ec1e).
> 
> No crash after revert this commit Many thanks

me too

**Comment by kissingers** [comment]
https://pastebin.com/Vt6fNUrH
Me too Crash. and after revert this no problem. my branch is npcbots

**Comment by kissingers** [comment]
0x0000555556386fce in Unit::CastCustomSpell (this=this@entry=0x7fff7af21000, spellId=spellId@entry=12654, value=..., victim=victim@entry=0x7fff7a6c0000, triggerFlags=triggerFlags@entry=TRIGGERED_FULL_MASK, castItem=castItem@entry=0x0, triggeredByAura=<optimized out>, originalCaster=...) 

before triggeredByAura always triggeredByAura@entry=0x0
and now 
triggeredByAura=<optimized out> 

then crash. 

might  aurEff here direct change to nullptr to keep same as before?
caster->CastCustomSpell(spellId, SPELLVALUE_BASE_POINT0, addAmount, this, TriggerCastFlags(TRIGGERED_FULL_MASK & ~TRIGGERED_NO_PERIODIC_RESET), nullptr, aurEff, caster->GetGUID());

**Comment by walkline** [comment]
I bet that aura effect lifetime is less than AuraMunchingQueue.

**Comment by heyitsbench** [comment]
For those experiencing the crash, please give https://github.com/azerothcore/azerothcore-wotlk/pull/19977 a try.
