### ISSUE TITLE
[GM COMMAND] Level up

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#19966]
### Current Behaviour

`.levelup $character 79` and `.char level $character 80` doesn't add level achievement to character if he is offline, it works for online character!

### Expected Blizzlike Behaviour

Add level achievement even if character is offline

### Source

My own mind

### Steps to reproduce the problem

.char level $name 80 while character is offline

### AC rev. hash/commit

rev. af776520dbd5+

### Operating system

Debian 12

**Comment by manstfu** [comment]
Playerbot related!

**Comment by manstfu** [comment]
Seems not playerbot related, can someone confirm this?

**Comment by Nyeriah** [comment]
Yeah, it's not granting achievements.

**Comment by manstfu** [comment]
Any possibility to be related to https://github.com/azerothcore/azerothcore-wotlk/blob/4fc60bbbdfb6e40b4e174333065c8365f639dfef/data/sql/updates/db_characters/2024_09_03_00.sql#L4 ?
