### ISSUE TITLE
[AZ] Usage Much Memory !

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#1997]
DESCRIPTION: azerothcore so much use memory and cpu , tested by RAM 15 G!
0 online players!

usage of : RAM 52%
usage of CPU: 50%

IMAGE:
https://pasteboard.co/IkDFROZ.png

BRANCH(ES): master

AC HASH/COMMIT:https://github.com/azerothcore/azerothcore-wotlk/commit/54ddf1950147d49053f1dc70a5d20fbfeb3488de

OPERATING SYSTEM: Debian

MODULES:
mod-eluna-lua-engine
TRANSMOG

**Comment by FrancescoBorzi** [comment]
@Hir0shi please be more specific when reporting issues.

Where is the problem? Is it in the commit you linked? Have you tested both with and without that commit? Does the RAM increase endlessly?

Because "AC uses 50% of my 15 GB" is not a bug report.

**Comment by Hir0shi** [comment]
@FrancescoBorzi 

over time, it will increase "RAM"

**Comment by FrancescoBorzi** [comment]
@Hir0shi can you please answer the other questions too?

**Comment by Hir0shi** [comment]
I can only explain that:

1.start worldserver
2.After a few hours
3.check of ram usage by Azcore 50% to 59%
4.CPU 400

Just see image

https://pasteboard.co/IkMu03W.png

OMG.

**Comment by FrancescoBorzi** [comment]
>  Have you tested both with and without that commit? Does the RAM increase endlessly?

**Comment by Hir0shi** [comment]
Yes, RAM and CPU ! ! !

**Comment by Hir0shi** [comment]
@FrancescoBorzi 
See again the photos:

BEFORE:
https://pasteboard.co/IkMu03W.png

AFTER:
https://pasteboard.co/IkMP5K4.png

**Comment by poszer** [comment]
> @FrancescoBorzi
> See again the photos:
> 
> BEFORE:
> https://pasteboard.co/IkMu03W.png
> 
> AFTER:
> https://pasteboard.co/IkMP5K4.png
> 
> First start Azcore: 21% will to .39% .. 49%.... 59% ... 61%.. and..
> RAM & CPU!
> 
> good information?

It must grow on starting server ofc. Check after some hours, it will decrease

**Comment by Hir0shi** [comment]
SEE TIME +10 hours past!
