### ISSUE TITLE
Love is in the Air event missing Love Boat vehicles 

### ISSUE THREAD

**Issue by sogladev** [azerothcore/azerothcore-wotlk#19986]
### Current Behaviour

"Love Boat" vehicles are not spawned in Darnassus, Undercity, Stormwind

e.g. https://www.wowhead.com/wotlk/npc=37980/darnassus-love-boat

### Expected Blizzlike Behaviour

1. boats that spawn in Darnassus, Undercity, Stormwind
2. right-click to board
3. passengers receive love buff when 2 characters are boarded
4. boats follow waypoints
5. at the end of the waypoint, passengers are ejected and exit on land 

### Source

fixed on TC335 

relevant TC issue

- https://github.com/TrinityCore/TrinityCore/issues/14027

### Steps to reproduce the problem

1. `.event start 8`
2.  go to lake/river/canal in Darnassus, Undercity, Stormwind

tp to boat summoners
```
.go c id 36817
.go c id 37964
.go c id 37981
```

### Extra Notes

missing a `vehicle_seat_addon` ([introduced in TC335 here](https://github.com/TrinityCore/TrinityCore/commit/98d6c501d7c1a7a632c6ff8b1d46c7d0d4ae5b37)) table to specify vehicle exit positions. ACore has some hard-coded exit positions instead

### AC rev. hash/commit

4254827b2cad

### Operating system

Ubuntu 24.04

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/19360

**Comment by sogladev** [comment]
duplicate, closing
