### ISSUE TITLE
Nethermine Flayer Hide not dropping

### ISSUE THREAD

**Issue by Loyaldk** [azerothcore/azerothcore-wotlk#19989]
### Current Behaviour

Killed dozens of Nethermine mobs including the Overmine Flayer, Nethermine Flayers, Ravagers, or Crust-Busters and none drop the Nethermine Flayer Hide when skinned. Did this for about 30 minutes with zero drops.

### Expected Blizzlike Behaviour

A chance to drop the Nethermine Flayer Hide from the Overmine Flayer, Nethermine Flayers, Nethermine Ravagers, or Nethermine Crust-Busters. 

### Source

https://www.wowhead.com/tbc/item=32470/nethermine-flayer-hide

### Steps to reproduce the problem

1. Kill the mob in question.
2. Skin the mob.
3. Loot and doesn't drop.

### Extra Notes

I am currently 2600/3000 reputation and Neutral reputation.

### AC rev. hash/commit

AzerothCore rev. 00e35a201e04 2024-09-11 03:25:32 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
![Nethermine Flayer Hide drops.](https://github.com/user-attachments/assets/2572fabb-d2db-4a8b-932c-ff7b516470d2)

**Comment by Loyaldk** [comment]
https://youtu.be/3ddFrgAWEBM
Issue was reproduced with 10 minutes of video.
