### ISSUE TITLE
Netherwing Crystals not dropping

### ISSUE THREAD

**Issue by Loyaldk** [azerothcore/azerothcore-wotlk#19988]
### Current Behaviour

Killed and looted dozens of mobs as explained below and never dropped a single one after 30 minutes of slaying.

### Expected Blizzlike Behaviour

A chance to drop the Netherwing Crystal from Crazed Murkblood Miner, Crazed Murkblood Foreman, Netherwing Ray, Nethermine Flayer, Black Blood of Draenor, Nethermine Burster, Overmine Flayer, and Nethermine Ravager.

### Source

https://www.wowhead.com/tbc/item=32427/netherwing-crystal

### Steps to reproduce the problem

1. Kill the mob in question.
2. Loot and doesn't drop.

### Extra Notes

I am currently 2600/3000 reputation and Neutral reputation.

### AC rev. hash/commit

AzerothCore rev. 00e35a201e04 2024-09-11 03:25:32 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
![Netherwing Crystals drop.](https://github.com/user-attachments/assets/09f25b32-2a39-44da-8c1f-a4cf99a83a08)

**Comment by Loyaldk** [comment]
https://youtu.be/3ddFrgAWEBM
Issue was reproduced with 10 minutes of video.

**Comment by heyitsbench** [comment]
> Issue was reproduced with 10 minutes of video.

Your issue has already been reported on the ChromieCraft issue tracker, both for [crystals](https://github.com/chromiecraft/chromiecraft/issues/7119) and [hides](https://github.com/chromiecraft/chromiecraft/issues/7093). This is not an issue with AzerothCore itself, as the issue can't be reproduced on stock AzerothCore, not even on the revision reported.
