### ISSUE TITLE
[Black Temple] Illidan cross the 4 and 5 stage case logic problem

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#19990]
### Current Behaviour

If Illidan enters the Shadow phase and then blood hits from above 30% to below 30%, it will trigger the Cage phase directly, but the phase is incomplete and Marvel won't come out, resulting in a phase bug.
And if you perish in the Shadow Phase, the next time you restart the fight Illidan has a certain probability of not being able to move, it will only turn with the tank's position and not follow the tank's movement.

### Expected Blizzlike Behaviour

Not sure if it switches from the Shadow phase to the Cage phase if the blood level is around 30%, but once it does, it must be possible to summon Marvel correctly
Boss fight reset should allow bosses to move at next fight

### Steps to reproduce the problem

1 .go c 148736 and fight with the boss
2. let the boss HP big than 30% a little and wait he to the Shadow phase
3. at Shadow phase let HP less than 29%

### AC rev. hash/commit

AzerothCore rev. a35f0c4ef61f 2024-09-16 15:13:36 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 10 minute(s) 16 second(s)
Update time diff: 100ms. Last 97 diffs summary:
|- Mean: 100ms
|- Median: 100ms
|- Percentiles (95, 99, max): 100ms, 102ms, 142ms
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80402
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 
Worldserver listening connections on port %u
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_03_00.sql
Latest WorldDatabase update: 2024_09_16_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-eluna

### Operating system

Debian 12 PVE

**Comment by kissingers** [comment]
https://github.com/user-attachments/assets/a1397a65-7971-49b0-912c-6ffb99e9b09b

Here is vedio :
first few seconds, the tank far away form the boss, the boss will not flow tank to attack (the problem from start fight to now except phase 2 all can not move)

then the boss to phase 5 try call Marvel,  then the boss find HP< 30% , and turn to phase 4 cast Shadow Phase. so all palyer die.

**Comment by kissingers** [comment]
the boss can not move because reset before fight not reset some of the movement flags, and all other fight with the boss will not move even if reset the boss, and will never change to normal without reset the instance.

**Comment by Rorschach91** [comment]
I can confirm the issue. 

This is what happen if Illidan starts demon form when he reachs 30% HP: [Youtube](https://youtu.be/tattbu787-w).

And this is how it should work when boss reachs 30% hp when demon form is starting: [Youtube](https://www.youtube.com/watch?v=1Ea_imv1zpM) from minute 5:05.
