### ISSUE TITLE
Warlock Imps are not named

### ISSUE THREAD

**Issue by Trus3683** [azerothcore/azerothcore-wotlk#19994]
### Current Behaviour

Warlock imps do not have generated names upon creation. Minion name is always "Imp".

### Expected Blizzlike Behaviour

Warlock imps should have permanent names generated upon creation. 

### Steps to reproduce the problem

- Create warlock
- Summon Imp

### AC rev. hash/commit

AzerothCore rev. af776520dbd5 2024-09-13 17:45:21 +0800 (Playerbot branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 1246.
Connection peak: 1.
Server uptime: 3 hour(s) 57 minute(s) 20 second(s)
Update time diff: 27ms. Last 500 diffs summary:
|- Mean: 16ms
|- Median: 12ms
|- Percentiles (95, 99, max): 36ms, 44ms, 54ms
Using SSL version: OpenSSL 3.3.2 3 Sep 2024 (library: OpenSSL 3.3.2 3 Sep 2024)
Using Boost version: 1.81.0
Using CMake version: 3.30.3
Using MySQL version: 80039
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in D:/WoW PSERVs/3.3.5a Local/AzerothCore/Build/bin/RelWithDebInfo/data/maps. Total size: 291014951 bytes
vmaps directory located in D:/WoW PSERVs/3.3.5a Local/AzerothCore/Build/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in D:/WoW PSERVs/3.3.5a Local/AzerothCore/Build/bin/RelWithDebInfo/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Using Playerbots DB Revision:
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: playerbots_names.sql
Latest WorldDatabase update: zz_optional_aq_quest_nerf.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
PlayerbotsDatabase queue size: 0
List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-autobalance
|- mod-individual-progression
|- mod-instance-reset
|- mod-junk-to-gold
|- mod-no-hearthstone-cooldown
|- mod-npc-enchanter
|- mod-playerbots
|- mod-quest-loot-party

### Operating system

Win 11 x64

### Custom changes or Modules

List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-autobalance
|- mod-individual-progression
|- mod-instance-reset
|- mod-junk-to-gold
|- mod-no-hearthstone-cooldown
|- mod-npc-enchanter
|- mod-playerbots
|- mod-quest-loot-party

**Comment by Tereneckla** [comment]
![image](https://github.com/user-attachments/assets/8c652445-1bc0-4b0f-a9ea-18093aec732c)
It works on base Azerothcore, you should bring it up to the playerbot branch
