### ISSUE TITLE
Instanze The Black Morass Small Bug

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#1999]
**SMALL DESCRIPTION:**

In the instance The Black Morass
Npc Medivh Text
Texts are correct but in wrong order

If you want to use the dragon with the item
Id 24289 summoned 
he stands around until you move the boss.
Id creature 17918

**EXPECTED BLIZZLIKE BEHAVIOR:**

The dragon should attack immediately.

https://wow.gamepedia.com/Medivh

**CURRENT BEHAVIOUR:**

The dragon is standing around.
until you move the boss.

Texts are correct but in wrong order

**STEPS TO REPRODUCE THE PROBLEM:**
.go c 31754

**BRANCH(ES):**
AzerothCore rev. 4a483aa3fd6e+ 2019-06-22 10:56:47 +0200 (master branch) (Win64, Release)
MODULES:
NO

**Comment by poszer** [comment]
Could you write correct text order

**Comment by Selyria** [comment]
> Could you write correct text order

Caverns of Time

Medivh in the Caverns of Time.
Event Begins
The time has come! Gul'dan, order your warlocks to double their efforts! Moments from now the gateway will open and your Horde will be unleashed on this ripe, unsuspecting world.

Shield at 75%
Champions! My shield grows weak!

Shield at 50%
My powers must be concentrated on the portal! I do not have time to hold the shield!

Shield at 25%
The shield is nearly gone! All that I have worked for is in danger!

Death
No! Damn this feeble, mortal coil!

Dark Portal Opened
What is this? Champions, coming to my aid? I sense the hand of the Dark One in this. Truly this sacred event bears his blessing.
I am grateful for your aid, champions. Now, Gul'dan's Horde will sweep across this world like a locust swarm, and all my designs, all my carefully-laid plans will at last fall into place.
A small army of orc warriors with the Shadow Council comes through.

Orcs of the Horde! This portal is the gateway to your new destiny! Azeroth lies before you, ripe for the taking!
The leader turns to the others.

Shadow Council Enforcer yells: Gul'dan speaks the truth! We should return at once to tell our brothers of the news! Retreat back through the portal!

**Comment by Voxstrasza** [comment]
Confirmed as of `9facd81e54ac`
