### ISSUE TITLE
Feature: Double the Ghost Movement Speed in AzerothCore

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#19996]
### Describe your feature request or suggestion in detail

Hey AzerothCore community! 👋

I’d like to recommend a small but impactful improvement for our WoW 3.3.5a servers: doubling the ghost movement speed. This change greatly enhances the player experience, as the current ghost speed, while faster than normal characters, still feels a bit slow and tedious—especially when players are far from their corpse.

Why should we make this change?

    Improves player experience: It reduces the wait time for players who need to run back to their body after dying.
    Similar to Retail WoW: This change was implemented in WoW Retail to streamline gameplay without disrupting balance.
    Easy to implement: I don’t think it’s difficult to apply, nor should it affect other aspects of the game.

By making this adjustment, we preserve the core essence of the classic WoW experience while offering a quality-of-life improvement that many players will appreciate. It’s a small tweak that adds more fluidity and enjoyment to the game.

### Describe a possible solution to your feature or suggestion in detail

When a player dies in WoW, their ghost often needs to travel long distances or navigate through complicated areas to find their body. This process can sometimes feel unnecessarily slow and frustrating, especially in larger zones or dungeons where paths are less direct. By doubling the current ghost movement speed, we can make this experience less tedious and more dynamic, without making it too easy or unrealistic.

It’s important that the increased speed is balanced—not an absurdly fast pace—but just enough to keep the flow of the game smooth. A doubling of the current speed would be more than enough to improve the gameplay without compromising the challenge. This would help reduce player frustration and keep the focus on engaging gameplay rather than long, slow recovery after death.

**Comment by heyitsbench** [comment]
Definitely best suited for a config or, preferably, a module.

**Comment by avarishd** [comment]
I would LOVE to see that as a config, as having CUSTOM things in the CONFIG is AMAZING. +1 from me

**Comment by Ceikry** [comment]
+1 for module, custom content is irrelevant to the main AzerothCore and only serves to pollute the already dense config with options most users won't care about.

**Comment by sogladev** [comment]
ghost speed is set by aura 8326

example of usage in the core 
- https://github.com/azerothcore/azerothcore-wotlk/blob/a196f7f28aa263dc7f9c532e15839f3b409fb68f/src/server/game/Handlers/CharacterHandler.cpp#L957

modifying the bp set by this aura with an AuraScript sets a custom speed

in a module:

https://github.com/sogladev/mod-ghost-speed/blob/master/src/mod_ghost_speed.cpp

50 default
200 fast
500 zoom

**Comment by kambire** [comment]
> ghost speed is set by aura 8326
> 
> example of usage in the core
> 
>     * https://github.com/azerothcore/azerothcore-wotlk/blob/a196f7f28aa263dc7f9c532e15839f3b409fb68f/src/server/game/Handlers/CharacterHandler.cpp#L957
> 
> 
> modifying the bp set by this aura with an AuraScript sets a custom speed
> 
> in a module:
> 
> https://github.com/sogladev/mod-ghost-speed/blob/master/src/mod_ghost_speed.cpp
> 
> 50 default 200 fast 500 zoom

you developed a module in less than an hour, you're a pro!

**Comment by heyitsbench** [comment]
Gonna call this issue resolved.
