### ISSUE TITLE
Need help increasing maximum group size for dungeons.

### ISSUE THREAD

**Issue by Beatlebattle** [azerothcore/azerothcore-wotlk#20008]
I am trying to get my dungeon group size up on my private server. I have checked another topic about this (https://github.com/azerothcore/azerothcore-wotlk/issues/5105) but I'm not able to change it. I don't think I quite understand the guides. I have the server running on a debian linux VM and I'm not very good navigating this so I wasn't able to extract the dbc file manually so I opened the database with HeidiSQL.

I have opened the database and I do see maxplayer variables in map.dbc and mapdifficulty.dbc. However I do not know how to fill them in. Just changing the (0) value to 40 for example did not work.

Can anybody please help me with this? (Sorry if I posted this in the wrong section).

![image](https://github.com/user-attachments/assets/2d04fae9-8070-406d-9145-2efed183e019)

**Comment by Nyeriah** [comment]
Please open a thread on Discord, the issue tracker is not a discussion board
