### ISSUE TITLE
[SSC - Vashj] Striders not rooted by Netherweave Nets

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20000]
Bug Triager Notes:

Original CC Reports: https://github.com/chromiecraft/chromiecraft/issues/6475#issue-2043792570

Currently, [Coilfang Striders](https://www.wowhead.com/tbc/npc=22056/coilfang-strider#comments) are immune to [Netherweave Net](https://www.wowhead.com/tbc/item=24268/netherweave-net#comments).
They shouldn't be immune to the nets.

![ev](https://github.com/user-attachments/assets/832aa80f-5acd-4d43-a146-014869c65449)

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Striders in the fight against Vashj (p2) are being rooted by Netherweave Nets

### Expected Blizzlike Behaviour

Nets should root the striders

### Source

https://wowwiki-archive.fandom.com/wiki/Lady_Vashj_(tactics)

### Steps to reproduce the problem

.

### Extra Notes

https://wowgaming.altervista.org/aowow/?item=24268
https://wowgaming.altervista.org/aowow/?npc=22056

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4d40b036440069fcfa964eac36eebda9d60140cb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sogladev** [comment]
mobs that are immune to stun are immune to net 

net 31367 has Mechanic = 12 (MECHANIC_STUN) 

comment 2.0.10 mentions stun, maybe it used to stun in early TBC? Now, there's no stun effect, yet it is labelled as a stun mechanic. https://www.wowhead.com/tbc/item=24268/netherweave-net#comments



[Reading wowhead Striders should not be immune to stuns](https://www.wowhead.com/tbc/npc=22056/coilfang-strider#comments)? 
![image](https://github.com/user-attachments/assets/05727c6c-ff9f-4a79-957f-b3790e25c2d0)

hammer of justice
`.cast 853`
immune

remove stun immunity
```
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` & ~2048 WHERE (`entry` = 22056);
```
