### ISSUE TITLE
[NPC DROP] Runes of the yrkvinn

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20011]
### Current Behaviour

this item
https://www.wowhead.com/wotlk/item=40690/runes-of-the-yrkvinn#dropped-by
should drop from
https://www.wowhead.com/wotlk/npc=29518/overseer-syra

### Expected Blizzlike Behaviour

Drop the item

### Source

Sons of Hodir Quest Chain

### Steps to reproduce the problem

.go c name overseer syra
kill

### AC rev. hash/commit

rev. 2e17b3250897

### Operating system

Debian 12

**Comment by heyitsbench** [comment]
![Runes drop.](https://github.com/user-attachments/assets/0ace194e-48bd-4623-a190-0a04ad5bfca9)

Need to have accepted [The Crone's Bargain](https://wowgaming.altervista.org/aowow/?quest=12841) for them to drop.
