### ISSUE TITLE
The server runs for a while and then reports the error: Thread 15 'worldserver' received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by springcell** [azerothcore/azerothcore-wotlk#20019]
### Current Behaviour

[Segmentation fault.txt](https://github.com/user-attachments/files/17095149/Segmentation.fault.txt)

### Expected Blizzlike Behaviour

I don't know how it happens; it occurs after running for a period of time.

### Steps to reproduce the problem

I don't know how it happens; it occurs after running for a period of time.

### AC rev. hash/commit

AzerothCore rev. 7fad987e0095+ 2024-09-13 11:13:00 +0800 (Playerbot branch) (Unix, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
                                 ██████╗ ██████╗ ██████╗ ███████╗
                                ██╔════╝██╔═══██╗██╔══██╗██╔════╝
                                ██║     ██║   ██║██████╔╝█████╗
                                ██║     ██║   ██║██╔══██╗██╔══╝
                                ╚██████╗╚██████╔╝██║  ██║███████╗
                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

     AzerothCore 3.3.5a  -  www.azerothcore.org

> Using configuration file       ./etc/worldserver.conf
> Using SSL version:             OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.9 30 May 2023)
> Using Boost version:           1.84.0
 
 
Loading Modules Configuration...
 
Using modules configuration:
> 1v1arena.conf.dist
> mod_ahbot.conf.dist
> Anticheat.conf.dist
> mod_boss_announcer.conf.dist
> mod_LuaEngine.conf.dist
> playerbots.conf.dist
> transmog.conf.dist
 
Initializing Scripts...
> Loading C++ scripts
 
Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool 'acore_auth' opened successfully. 2 total connections running.
 
Opening DatabasePool 'acore_characters'. Asynchronous connections: 1, synchronous connections: 2.
DatabasePool 'acore_characters' opened successfully. 3 total connections running.
 
Opening DatabasePool 'acore_world'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool 'acore_world' opened successfully. 2 total connections running.
 
Updating Auth database...
>> Auth database is up-to-date! Containing 2 new and 0 archived updates.
 
Updating Character database...
>> Character database is up-to-date! Containing 8 new and 6 archived updates.
 
Updating World database...
>> World database is up-to-date! Containing 1071 new and 3 archived updates.
 
Opening DatabasePool 'acore_playerbots'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool 'acore_playerbots' opened successfully. 2 total connections running.
 
Updating Playerbots database...
>> Playerbots database is up-to-date! Containing 1 new and 0 archived updates.
 
Loading World Information...
> RealmID:              1
> Version DB world:     ACDB 335.12-dev
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir data/
WORLD: VMap support included. LineOfSight:true, getHeight:true, indoorCheck:true PetLOS:true
AnticheatModule Loaded.
Loading transmog appearance collection cache....
Loaded 35425 collected appearances into cache
 
Loading Acore Strings...
>> Loaded 1169 Acore Strings in 2 ms
 
Loading Module Strings...
>> Loaded 6 Module Strings in 1 ms
 
Loading Module Strings Locale...
>> Loaded 12 Module Strings Locales in 0 ms
 
Initialize Data Stores...
>> Initialized 112 Data Stores in 359 ms
 
Using zhCN DBC Locale As Default. All Available DBC locales: zhCN enUS 
 
>> Loading Cinematic Camera files
>> Loaded 14 Cinematic Waypoint Sets in 0 ms
 
Loading IP Location Database...
 
Loading Game Graveyard...
>> Loaded 685 Graveyard in 2 ms
 
Initializing PlayerDump Tables...
>> Initialized Tables For PlayerDump in 15 ms.
 
Loading SpellInfo Store...
>> Loaded Spell Custom Attributes in 38 ms
 
Loading Spell Cooldown Overrides...
>> Loaded 11 Spell Cooldown Overrides entries in 0 ms
 
Loading SpellInfo Data Corrections...
>> Loading spell dbc data corrections  in 5 ms
 
Loading Spell Rank Data...
>> Loaded 3502 spell rank records in 2 ms
 
Loading Spell Specific And Aura State...
>> Loaded Spell Specific And Aura State in 6 ms
 
Loading SkillLineAbilityMultiMap Data...
>> Loaded 10219 SkillLineAbility MultiMap Data in 2 ms
 
Loading SpellInfo Custom Attributes...
>> Loaded 316 spell custom attributes from DB in 0 ms
>> Loaded SpellInfo Custom Attributes in 16 ms
 
Loading GameObject Models...
>> Loaded 2323 GameObject Models in 1 ms
 
Loading Script Names...
>> Loaded 2942 ScriptNames in 215 ms
 
Loading Instance Template...
>> Loaded 85 Instance Templates in 1 ms
 
Loading Character Cache...
>> Loaded Character Infos For 3008 Characters in 5 ms
 
Loading Instances...
>> Loaded Instances And Binds in 12 ms
 
Loading Broadcast Texts...
>> Loaded 73039 Broadcast Texts in 162 ms
>> Loaded 583570 Broadcast Text Locales in 873 ms
 
Loading Localization Strings...
>> Loaded 27293 Creature Locale Strings in 254 ms
>> Loaded 21503 Gameobject Locale Strings in 181 ms
>> Loaded 46110 Item Locale Strings in 373 ms
>> Loaded 2481 Item Set Name Locale Strings in 17 ms
>> Loaded 9461 Quest Locale Strings in 191 ms
>> Loaded 14739 Quest Offer Reward Locale Strings in 70 ms
>> Loaded 14739 Quest Request Items Locale Strings in 48 ms
>> Loaded 8368 Npc Text Locale Strings in 53 ms
>> Loaded 1974 Page Text Locale Strings in 21 ms
>> Loaded 309 Gossip Menu Option Locale Strings in 3 ms
>> Loaded 453 Points Of Interest Locale Strings in 3 ms
>> Loaded 106 Pet Name Locales Parts in 0 ms
 
>> Localization Strings loaded in 1214 ms
 
Loading Page Texts...
>> Loaded 1946 Page Texts in 4 ms
 
Loading Game Object Templates...
>> Loaded 21580 Game Object Templates in 80 ms
 
Loading Game Object Template Addons...
>> Loaded 21493 Game Object Template Addons in 26 ms
 
Loading Transport Templates...
>> Loaded 30 Transport Templates in 7 ms
 
Loading Spell Required Data...
>> Loaded 50 Spell Required Records in 1 ms
 
Loading Spell Group Types...
>> Loaded 362 Spell Group Definitions in 0 ms
 
Loading Spell Learn Skills...
>> Loaded 103 Spell Learn Skills From DBC in 4 ms
 
Loading Spell Proc Event Conditions...
>> Loaded 832 Extra Spell Proc Event Conditions in 2 ms
 
Loading Spell Proc Conditions and Data...
>> Loaded 0 Spell Proc Conditions And Data. DB table `spell_proc` Is Empty.
 
Loading Spell Bonus Data...
>> Loaded 1270 Extra Spell Bonus Data in 1 ms
 
Loading Aggro Spells Definitions...
>> Loaded 106 SpellThreatEntries in 1 ms
 
Loading Mixology Bonuses...
>> Loaded 21 Mixology Bonuses in 0 ms
 
Loading Spell Group Stack Rules...
>> Loaded 37 Spell Group Stack Rules in 0 ms
 
Loading NPC Texts...
>> Loaded 8355 Npc Texts in 84 ms
 
Loading Enchant Spells Proc Datas...
>> Loaded 42 Enchant Proc Data Definitions in 0 ms
 
Loading Item Random Enchantments Table...
>> Loaded 28594 Item Enchantment Definitions in 21 ms
 
Loading Disables
>> Loaded 910 Disables in 1 ms
 
Loading Items...
>> Loaded 46096 Item Templates in 871 ms
 
Loading Item Set Names...
>> Loaded 2489 Item Set Names in 3 ms
 
Loading Creature Model Based Info Data...
>> Loaded 24143 Creature Model Based Info in 28 ms
 
Loading Creature Custom IDs Config...
Loading Creature Templates...
>> Loaded 40206 creature template models in 43 ms
>> Loaded 2209 Creature Template Resistances in 2 ms
 
>> Loaded 9555 Creature Template Spells in 5 ms
 
>> Loaded 29958 Creature Definitions in 453 ms
 
Loading Equipment Templates...
>> Loaded 10851 Equipment Templates in 10 ms
 
Loading Creature Template Addons...
>> Loaded 11942 Creature Template Addons in 15 ms
 
Loading Reputation Reward Rates...
>> Loaded 14 Reputation Reward Rate in 1 ms
 
Loading Creature Reputation OnKill Data...
>> Loaded 2035 Creature Award Reputation Definitions in 3 ms
 
Loading Reputation Spillover Data...
>> Loaded 26 Reputation Spillover Template in 0 ms
 
Loading Points Of Interest Data...
>> Loaded 463 Points of Interest Definitions in 1 ms
 
Loading Creature Base Stats...
>> Loaded 400 Creature Base Stats in 3 ms
 
Loading Creature Data...
>> Loaded 149467 Creatures in 1156 ms
 
Loading Temporary Summon Data...
>> Loaded 1208 Temporary Summons in 3 ms
 
Loading Pet Levelup Spells...
>> Loaded 993 Pet Levelup And Default Spells For 39 Families in 0 ms
 
Loading Pet default Spells additional to Levelup Spells...
>> Loaded Addition Spells For 112 Pet Spell Data Entries in 1 ms
 
Loading Summonable Creature Templates...
>> Loaded 471 Summonable Creature emplates in 4 ms
 
Loading Creature Addon Data...
>> Loaded 35235 Creature Addons in 51 ms
 
Loading Creature Movement Overrides...
>> Loaded 9 Movement Overrides in 0 ms
 
Loading Gameobject Data...
>> Loaded 85099 Gameobjects in 677 ms
 
Loading GameObject Addon Data...
>> Loaded 32 Gameobject Addons in 0 ms
 
Loading GameObject Quest Items...
>> Loaded 862 Gameobject Quest Items in 1 ms
 
Loading Creature Quest Items...
>> Loaded 4416 Creature Quest Items in 3 ms
 
Loading Creature Linked Respawn...
>> Loaded 4345 Linked Respawns In 3 ms
 
Loading Weather Data...
>> Loaded 35 Weather Definitions in 1 ms
 
Loading Quests...
>> Loaded 9464 Quests Definitions in 214 ms
 
Checking Quest Disables
>> Checked 693 Quest Disables in 0 ms
 
Loading Quest POI
>> Loaded 18771 Quest POI definitions in 69 ms
 
Loading Quests Starters and Enders...
Loading GO Start Quest Data...
>> Loaded 455 Quest Relations From gameobject_queststarter in 1 ms
 
Loading GO End Quest Data...
>> Loaded 457 Quest Relations From gameobject_questender in 1 ms
 
Loading Creature Start Quest Data...
>> Loaded 7497 Quest Relations From creature_queststarter in 12 ms
 
Loading Creature End Quest Data...
>> Loaded 7899 Quest Relations From creature_questender in 12 ms
 
Loading Quest Greetings...
>> Loaded 206 quest_greeting in 0 ms
 
Loading Quest Greeting Locales...
>> Loaded 5 quest greeting Locale Strings in 0 ms
 
Loading Quest Money Rewards...
>> Loaded 800 Quest Money Rewards in 1 ms
 
Loading Objects Pooling Data...
>> Loaded 7329 Objects Pools In 3 ms
 
Loading Creatures Pooling Data...
>> Loaded 1496 Creatures In Pools in 1 ms
 
Loading Gameobjects Pooling Data...
>> Loaded 28731 Gameobjects In Pools in 25 ms
 
Loading Mother Pooling Data...
>> Loaded 5001 Pools In Mother Pools in 4 ms
 
Loading Quest Pooling Data...
>> Loaded 162 Quests In Pools in 0 ms
 
Starting Objects Pooling System...
 
Loading Game Event Data...
>> Loaded 153 Holiday Dates in 0 ms
>> Loaded 88 Game Events in 1 ms
 
Loading Game Event Saves Data...
>> Loaded 0 Game Event Saves In Game Events. DB Table `game_event_save` Is Empty.
 
Loading Game Event Prerequisite Data...
>> Loaded 0 Game Rvent Prerequisites in Game Events. DB Table `game_event_prerequisite` Is Empty.
 
Loading Game Event Creature Data...
>> Loaded 10133 Creatures In Game Events in 4 ms
 
Loading Game Event GO Data...
>> Loaded 24937 Gameobjects In Game Events in 11 ms
 
Loading Game Event Model/Equipment Change Data...
>> Loaded 0 Model/Equipment Changes In Game Events. DB Table `game_event_model_equip` Is Empty.
 
Loading Game Event Quest Data...
>> Loaded 215 Quests Additions In Game Events in 0 ms
 
Loading Game Event GO Quest Data...
>> Loaded 78 Quests Additions In Game Events in 0 ms
 
Loading Game Event Quest Condition Data...
>> Loaded 0 quest event Conditions In Game Events. DB Table `game_event_quest_condition` Is Empty.
 
Loading Game Event Condition Data...
>> Loaded 0 Conditions In Game Events. DB table `game_event_condition` Is Empty.
 
Loading Game Event Condition Save Data...
>> Loaded 0 Condition Saves In Game Events. DB Table `game_event_condition_save` Is Empty.
 
Loading Game Event NPCflag Data...
>> Loaded 5 Npcflags In Game Events In 0 ms
 
Loading Game Event Seasonal Quest Relations...
>> Loaded 690 Quests Additions In Game Events in 0 ms
 
Loading Game Event Vendor Additions Data...
>> Loaded 14 Vendor Additions In Game Events in 1 ms
 
Loading Game Event Battleground Data...
>> Loaded 6 Battleground Holidays In Game Events in 0 ms
 
Loading Game Event Pool Data...
>> Loaded 8 Pools For Game Events in 0 ms
 
Loading UNIT_NPC_FLAG_SPELLCLICK Data...
>> Loaded 330 Spellclick Definitions in 2 ms
 
Loading Vehicle Template Accessories...
>> Loaded 193 Vehicle Template Accessories in 0 ms
 
Loading Vehicle Accessories...
>> Loaded 0 Vehicle Accessories in 0 ms
 
Loading SpellArea Data...
>> Using ICC Buff Horde: 73822
>> Using ICC Buff Alliance: 73828
>> Loaded 700 Spell Area Requirements in 1 ms
 
Loading Area Trigger Definitions
>> Loaded 1217 Area Trigger Definitions in 4 ms
 
Loading Area Trigger Teleport Definitions...
>> Loaded 274 Area Trigger Teleport Definitions in 0 ms
 
Loading Access Requirements...
>> Loaded 121 Rows From dungeon_access_template And 35 Rows From dungeon_access_requirements in 12 ms
 
Loading Quest Area Triggers...
>> Loaded 57 Quest Trigger Points in 0 ms
 
Loading Tavern Area Triggers...
>> Loaded 113 Tavern Triggers in 0 ms
 
Loading AreaTrigger Script Names...
>> Loaded 149 Areatrigger Scripts in 1 ms
 
Loading LFG Entrance Positions...
>> Loaded 22 LFG Entrance Positions in 0 ms
 
Loading Dungeon Boss Data...
>> Loaded 612 Instance Encounters in 0 ms
 
Loading LFG Rewards...
>> Loaded 15 LFG Dungeon Rewards in 0 ms
 
Loading Graveyard-Zone Links...
>> Loaded 704 Graveyard-Zone Links in 0 ms
 
Loading Spell Pet Auras...
>> Loaded 49 Spell Pet Auras in 1 ms
 
Loading Spell Target Coordinates...
>> Loaded 676 Spell Teleport Coordinates in 1 ms
 
Loading Enchant Custom Attributes...
>> Loaded 47 Custom Enchant Attributes in 3 ms
 
Loading linked Spells...
>> Loaded 582 Linked Spells in 0 ms
 
Loading Player Create Data...
>> Loaded 62 Player Create Definitions in 1 ms
 
Loading Player Create Items Data...
>> Loaded 1 Custom Player Create Items in 0 ms
 
Loading Player Create Skill Data...
>> Loaded 1103 Player Create Skills in 0 ms
 
Loading Player Create Spell Data...
>> Loaded 0 player create spells. DB table `playercreateinfo_spell_custom` is empty.
Loading Player Create Cast Spell Data...
>> Loaded 19 Player Create Cast Spells in 0 ms
 
Loading Player Create Action Data...
>> Loaded 283 Player Create Actions in 0 ms
 
Loading Player Create Level Stats Data...
>> Loaded 746 Level Stats Definitions in 2 ms
 
Loading Player Create XP Data...
>> Loaded 79 XP For Level Definitions in 0 ms
 
Loading Exploration BaseXP Data...
>> Loaded 80 BaseXP Definitions in 0 ms
 
Loading Pet Name Parts...
>> Loaded 313 Pet Name Parts in 1 ms
 
Loading The Max Pet Number...
>> Loaded The Max Pet Number: 9717 in 0 ms
 
Loading Pet Level Stats...
>> Loaded 2800 Level Pet Stats Definitions in 4 ms
 
Loading Player Level Dependent Mail Rewards...
>> Loaded 24 Level Dependent Mail Rewards in 0 ms
 
Load Mail Server Template...
 
Loading Creature Loot Templates...
>> Loaded 248919 Creature Loot Templates in 350 ms
 
Loading Fishing Loot Templates...
>> Loaded 254 Fishing Loot Templates in 1 ms
 
Loading Gameobject Loot Templates...
>> Loaded 17959 Gameobject Loot Templates in 25 ms
 
Loading Item Loot Templates...
>> Loaded 4988 item loot templates in 9 ms
 
Loading Mail Loot Templates...
>> Loaded 105 mail loot templates in 0 ms
 
Loading Milling Loot Templates...
>> Loaded 45 milling loot templates in 2 ms
 
Loading Pickpocketing Loot Templates...
>> Loaded 10995 pickpocketing loot templates in 18 ms
 
Loading Skinning Loot Templates...
>> Loaded 1875 skinning loot templates in 4 ms
 
Loading Disenchanting Loot Templates...
>> Loaded 124 disenchanting loot templates in 3 ms
 
Loading Prospecting Loot Templates...
>> Loaded 37 prospecting loot templates in 2 ms
 
Loading Spell Loot Templates...
>> Loaded 163 spell loot templates in 10 ms
 
Loading Reference Loot Templates...
>> Loaded reference loot templates in 69 ms
 
Loading Player Loot Templates...
>> Loaded 20 player loot templates in 0 ms
 
Loading Skill Discovery Table...
>> Loaded 347 skill discovery definitions in 9 ms
 
Loading Skill Extra Item Table...
>> Loaded 226 spell specialization definitions in 0 ms
 
Loading Skill Perfection Data Table...
>> Loaded 72 spell perfection definitions in 1 ms
 
Loading Skill Fishing Base Level Requirements...
>> Loaded 94 areas for fishing base skill level in 0 ms
 
Loading Achievements...
>> Loaded 43 achievement references in 0 ms
 
Loading Achievement Criteria Lists...
>> Loaded 7494 achievement criteria in 1 ms
 
Loading Achievement Criteria Data...
>> Loaded 2815 additional achievement criteria data in 3 ms
 
Loading Achievement Rewards...
>> Loaded 104 achievement rewards in 1 ms
 
Loading Achievement Reward Locales...
>> Loaded 103 Achievement Reward Locale Strings in 0 ms
 
Loading Completed Achievements...
>> Loaded 43 completed achievements in 2 ms
 
Loading Item Auctions...
>> Loaded 251 auction items in 1 ms
 
Loading Auctions...
>> Loaded 251 auctions in 1 ms
 
Loading Guilds Definitions...
>> Loaded 1 guild definitions in 1 ms
 
Loading Guild Ranks...
>> Loaded 5 guild ranks in 0 ms
 
Loading Guild Members...
>> Loaded 45 guild members int 1 ms
 
Loading Bank Tab Rights...
>> Loaded 0 guild bank tab rights. DB table `guild_bank_right` is empty.
 
Loading Guild Event Logs...
>> Loaded 100 guild event logs in 0 ms
 
Loading Guild Bank Event Logs...
>> Loaded 0 guild bank event logs. DB table `guild_bank_eventlog` is empty.
 
Loading Guild Bank Tabs...
>> Loaded 0 guild bank tabs. DB table `guild_bank_tab` is empty.
 
Filling bank tabs with items...
>> Loaded 0 guild bank tab items. DB table `guild_bank_item` or `item_instance` is empty.
 
Validating data of loaded guilds...
>> Validated data of loaded guilds in 0 ms
 
Loading ArenaTeams...
>> Loaded 25 arena teams in 1 ms
 
Loading Groups...
>> Loaded 2 group definitions in 0 ms
 
Loading Group Members...
>> Loaded 22 group members in 1 ms
 
Loading Reserved Names...
>> Loaded 0 reserved names. DB table `reserved_name` is empty!
>> Loaded 16330 reserved names from DBC in 8 ms
 
Loading Profanity Names...
>> Loaded 0 profanity names. DB table `profanity_name` is empty!
>> Loaded 8267 profanity names from DBC in 5 ms
 
Loading GameObjects for Quests...
>> Loaded 1820 GameObjects for quests in 1 ms
 
Loading BattleMasters...
>> Loaded 147 battlemaster entries in 2 ms
 
Loading GameTeleports...
>> Loaded 1491 GameTeleports in 4 ms
 
Loading Gossip Menu...
>> Loaded 5995 gossip_menu entries in 4 ms
 
Loading Gossip Menu Options...
>> Loaded 4544 gossip_menu_option entries in 10 ms
 
Loading Vendors...
>> Loaded 37762 Vendors in 42 ms
 
Loading Trainers...
>> Loaded 79302 Trainers in 133 ms
 
Loading Waypoints...
>> Loaded 141778 waypoints in 273 ms
 
Loading SmartAI Waypoints...
>> Loaded 828 SmartAI waypoint paths (total 14138 waypoints) in 12 ms
 
Loading Creature Formations...
>> Loaded 5494 Creatures In Formations in 8 ms
 
Loading World States...
>> Loaded 144 World States in 1 ms
 
Loading Conditions...
>> Loaded 15404 conditions in 31 ms
 
Loading Faction Change Achievement Pairs...
>> Loaded 124 faction change achievement pairs in 1 ms
 
Loading Faction Change Spell Pairs...
>> Loaded 113 faction change spell pairs in 0 ms
 
Loading Faction Change Item Pairs...
>> Loaded 1395 faction change item pairs in 1 ms
 
Loading Faction Change Reputation Pairs...
>> Loaded 15 faction change reputation pairs in 0 ms
 
Loading Faction Change Title Pairs...
>> Loaded 22 faction change title pairs in 0 ms
 
Loading Faction Change Quest Pairs...
>> Loaded 293 faction change quest pairs in 0 ms
 
Loading GM Tickets...
>> Loaded 0 GM tickets. DB table `gm_ticket` is empty!
Loading GM Surveys...
>> Loaded GM Survey count from database in 0 ms
 
Loading Client Addons...
>> Loaded 23 known addons in 1 ms
 
Deleting Invalid Mail Items...
 
Returning Old Mails...
 
Loading Autobroadcasts...
Loading Motd...
>> Loaded Motd Definitions in 0 ms
 
Loading spell_scripts...
>> Loaded 131 script definitions in 0 ms
 
Loading event_scripts...
>> Loaded 434 script definitions in 1 ms
 
Loading waypoint_scripts...
>> Loaded 573 script definitions in 2 ms
 
Loading Spell Script Names...
>> Loaded 2204 spell script names in 3 ms
 
Loading Creature Texts...
>> Loaded 18282 Creature Texts For 4116 Creatures in 41 ms
 
Loading Creature Text Locales...
>> Loaded 14027 Creature Text Locale in 23 ms
 
Loading Scripts...
Loading Script Waypoints For 62 Creature(s)...
>> Loaded 2305 Script Waypoint nodes in 5 ms
>> Loaded 3042 C++ scripts in 90 ms
 
Validating Spell Scripts...
>> Validated 2581 scripts in 2 ms
 
Loading SmartAI Scripts...
>> Loaded 13298 SmartAI scripts in 173 ms
 
Loading Calendar Data...
>> Loaded 0 calendar events
>> Loaded 0 calendar invites
 
Initializing SpellInfo Precomputed Data...
 
Initialize Commands...
Initialize Game Time and Timers
 
Starting Map System
 
Starting Game Event system...
 
Player::DeleteOldChars: Deleting all characters which have been deleted 30 days before...
 
Initializing Opcodes...
Starting Arena Season...
 
Arena Season 8 started...
 
Starting Battleground System
>> Loaded 13 battlegrounds in 1 ms
 
Starting Outdoor PvP System
>> Loaded 7 outdoor PvP definitions in 0 ms
 
Starting Battlefield System
Battlefield: Wintergrasp successfully initiated.
 
Loading Transports...
>> Spawned 20 continent motion transports in 111 ms
Loading Warden Checks...
>> Loaded 793 warden checks.
 
Loading Warden Action Overrides...
>> Loaded 1 warden action overrides.
 
Deleting Expired Bans...
Calculate Next Daily Quest Reset Time...
Calculate Next Weekly Quest Reset Time...
Calculate Next Monthly Quest Reset Time...
Calculate Random Battleground Reset Time...
Calculate Deletion Of Old Calendar Events Time...
Calculate Guild Cap Reset Time...
 
Load Petitions...
>> Loaded 0 Petitions!
 
Load Petition Signs...
>> Loaded 0 Petition signs!
 
Load Stored Loot Items...
>> Loaded 0 stored items!
 
Load Channel Rights...
>> Loaded 0 Channel Rights!
 
Load Channels...
>> Loaded 209 channels in 17ms
 
 
Load Playerbots Config...
Initializing AI Playerbots by ike3, based on the original Playerbots by blueboy
---------------------------------------
          Loading TalentSpecs          
---------------------------------------
250 random bot accounts with 2504 characters available
Building ammo cache for 80 levels
Cached 160 types of ammo
Building potion cache for 80 levels
Cached 18 types of potions
Building food cache for 80 levels
Cached 18 types of food
Building trade cache for 80 levels
Cached 9 trade items
Loading random item cache
Equipment cache loaded from 12752 records
Loading playerbots dungeon suggestions...
88 playerbots dungeon suggestions loaded in 0 ms
---------------------------------------
        AI Playerbots initialized       
---------------------------------------
>> Loaded playerbots config in 2027 ms
 
 
WORLD: World Initialized In 0 Minutes 15 Seconds
 
AzerothCore rev. 7fad987e0095+ 2024-09-13 11:13:00 +0800 (Playerbot branch) (Unix, Release, Static) (worldserver-daemon) ready...
Initialize AuctionHouseBot...
AHBot: Configuration for ah 2
AHBot: 12234 disabled items
AHBot: loaded 5 grey   trade goods
AHBot: loaded 213 white  trade goods
AHBot: loaded 22 green  trade goods
AHBot: loaded 4 blue   trade goods
AHBot: loaded 0 purple trade goods
AHBot: loaded 0 orange trade goods
AHBot: loaded 0 yellow trade goods
AHBot: loaded 1099 grey   items
AHBot: loaded 540 white  items
AHBot: loaded 4420 green  items
AHBot: loaded 971 blue   items
AHBot: loaded 343 purple items
AHBot: loaded 0 orange items
AHBot: loaded 0 yellow items
AHBot: Configuration for ah 6
AHBot: 12234 disabled items
AHBot: loaded 5 grey   trade goods
AHBot: loaded 213 white  trade goods
AHBot: loaded 22 green  trade goods
AHBot: loaded 4 blue   trade goods
AHBot: loaded 0 purple trade goods
AHBot: loaded 0 orange trade goods
AHBot: loaded 0 yellow trade goods
AHBot: loaded 1099 grey   items
AHBot: loaded 540 white  items
AHBot: loaded 4420 green  items
AHBot: loaded 971 blue   items
AHBot: loaded 343 purple items
AHBot: loaded 0 orange items
AHBot: loaded 0 yellow items
AHBot: Configuration for ah 7
AHBot: 12234 disabled items
AHBot: loaded 5 grey   trade goods
AHBot: loaded 213 white  trade goods
AHBot: loaded 22 green  trade goods
AHBot: loaded 4 blue   trade goods
AHBot: loaded 0 purple trade goods
AHBot: loaded 0 orange trade goods
AHBot: loaded 0 yellow trade goods
AHBot: loaded 1099 grey   items
AHBot: loaded 540 white  items
AHBot: loaded 4420 green  items
AHBot: loaded 971 blue   items
AHBot: loaded 343 purple items
AHBot: loaded 0 orange items
AHBot: loaded 0 yellow items
AHBot [2112]: initialization complete
Starting up Auction House Listing thread...
Calendar deletion of old events.
Anticheat: Resetting daily report states.
Anticheat: Next daily report reset: Tue Sep 24 2024 06:00:00
Saving reports for 60 players.
Saving reports for 120 players.
Saving reports for 131 players.
Saving reports for 132 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Saving reports for 135 players.
Update time diff: 486ms with 1 players online
Last 500 diffs summary:
|- Mean: 2ms
|- Median: 1ms
|- Percentiles (95, 99, max): 2ms, 17ms, 486ms
Saving reports for 154 players.
Saving reports for 154 players.
Saving reports for 154 players.
Saving reports for 154 players.

### Operating system

Linux version 4.4.302+ (root@build6) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:01:14 CST 2024

**Comment by heyitsbench** [comment]
Your server was compiled in release mode which makes your crashlog useless, and you are not running a clean AC build.
