### ISSUE TITLE
Codacy sometimes doesn't work right

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#2001]
Codacy sometimes fails with strange error messages while checking PRs. Example:
#1998
![codacy](https://user-images.githubusercontent.com/38475780/59972619-b969e700-9592-11e9-994f-21c513916d99.png)

The first run, which failed, has this URL (seems to be associated with talamortis):
https://app.codacy.com/app/talamortis/azerothcore-wotlk/pullRequest?prid=3756112

The second one, which was successful, has this URL (associated with shin):
https://app.codacy.com/app/FrancescoBorzi/azerothcore-wotlk/pullRequest?prid=3756078

**Comment by talamortis** [comment]
Codacy is 💩

**Comment by FrancescoBorzi** [comment]
@Viste any suggestions here?

**Comment by Viste** [comment]
yes you can add own standarts in admin panel :)

**Comment by Kitzunu** [comment]
not used anymore
