### ISSUE TITLE
Feature: (Core/Vehicles) specify vehicle exit position and orientation with a vehicle seat addon table

### ISSUE THREAD

**Issue by sogladev** [azerothcore/azerothcore-wotlk#20029]
### Describe your feature request or suggestion in detail

implement `vehicle_seat_addon` table to specify a unit's exit position and orientation

this behavior is currently hard-coded and has an additional hack for flame leviathan

- https://github.com/azerothcore/azerothcore-wotlk/blob/62509abd1d55ceaa7f7451d19d90ee06620a2056/src/server/game/Entities/Unit/Unit.cpp#L19749

this feature is present in other 335 cores and can fix issues like:
- part of https://github.com/azerothcore/azerothcore-wotlk/issues/15831 "NPCs should jump off the mount, turn to face you"
- TODO of https://github.com/azerothcore/azerothcore-wotlk/pull/19987 "exit positions"

### Describe a possible solution to your feature or suggestion in detail

tc335 https://github.com/TrinityCore/TrinityCore/commit/98d6c501d7c1a7a632c6ff8b1d46c7d0d4ae5b37
same structure can be found in cmangos https://github.com/cmangos/mangos-wotlk/commit/aa6e3b93156a85eddc1edd603405bee9973b339b

### Additional context

fixes provided by current hacks should be preserved which makes this challenging

`Vehicle.dbc` lists the vehicle and its corresponding vehicle_seats. e.g. AT mount `vechicle id 349 -> 1 seat 3129 `

part of investigating vehicle related issues, very much WIP https://github.com/sogladev/azerothcore-wotlk/tree/fix(Core/Vehicle)SetRootWhenAddingPassenger, vehicle_seat_addon https://github.com/azerothcore/azerothcore-wotlk/commit/332a5791f9a9c21158682d957ffd231aca505c01

**Comment by Kitzunu** [comment]
> fixes provided by current hacks should be preserved which makes this challenging

It isn't wrong to break something if it provides the right tools to fix it.
