### ISSUE TITLE
[Quest] The Fel and the Furious 10612 & 10613

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20022]
### Current Behaviour

deathforged infernal cannot be attacked using sentinel, also [Fel Reaver Controller](https://www.wowhead.com/wotlk/spell=38123/fel-reaver-controller) not working, it should work 50.000 yards

Quest ID: 10612 & 10613

### Expected Blizzlike Behaviour

Quest description

### Steps to reproduce the problem

.quest add 10612 (ally) | 10613 (horde)

### AC rev. hash/commit

rev. 2e17b3250897

### Operating system

Debian 12

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3605
https://github.com/azerothcore/azerothcore-wotlk/issues/15035
https://github.com/azerothcore/azerothcore-wotlk/issues/19993

**Comment by manstfu** [comment]
Ok sorry i didnt check, closed.
