### ISSUE TITLE
[Quest] Fires over Skettis does not work

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#20041]
### Current Behaviour

No eggs spawned
Bomb not usable

### Expected Blizzlike Behaviour

Eggs spawned
Bomb usable

### Source

...

### Steps to reproduce the problem

.tele skettis
.quest add 11008
Try to use the added bomb
Fly around to see no eggs

### Extra Notes

probably related to https://github.com/azerothcore/azerothcore-wotlk/pull/19567

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/da3109809463ff4223038d2fc9d48610d67c9238

### Operating system

Ubuntu 24.04

**Comment by sudlud** [comment]
`.tele lowerveil`

there's eggs that can be destroyed with the bombs. can't tell why there are no eggs at `.tele skettis`.

both areas are marked blue for the quest in the map

**Comment by sudlud** [comment]
i've opened a PR to add the missing spawns for eggs.

@Tereneckla are you getting the quest credit when destroying the eggs?

somehow for my testing i'm not getting it - the latest skettis PR changed the targets of the bomb spell.
the quest credit and gameobject respawing is beeing handled by the trigger creature's smartAI.

so this could probably be the issue why it's not in a working state as of now, if the bomb spell is not targetting the trigger creatures anymore.

**Comment by sudlud** [comment]
besides the missing spawns that will be added in #20063, I can't reproduce the issue on b07670f130a0e27747f27fa54502825c04db8a3b

using a lvl 70 druid, i can add the quest, throw the bombs at the targets and get the quest credit. also the eggs respawn after some time.

**Comment by Mervin31** [comment]
Not sure if it is implemented or not. If it is implemented on chromiecraft then the bad news is that
1) bomb is still unusable
2) eggs still do not spawn

**Comment by sun4crash** [comment]
Are there any updates on this? As far as I know, the issue is still ongoing — the eggs still aren’t spawning. When using the “Bombs” I get the error message: “You can’t do that yet.”
