### ISSUE TITLE
[Bug] Problem with items when in cat/bear form

### ISSUE THREAD

**Issue by konatox** [azerothcore/azerothcore-wotlk#20045]
### Current Behaviour

You can't use consumables when in cat/bear form. When you right click them from the bag, or use them from the bars appears an error message

![image1](https://github.com/user-attachments/assets/72ccd579-2b53-4972-a443-7ce9ab4c8d59)

If you disconnect from the server while in cat/bear form, when you reconnect, all your items are sent to the mail (only the main bag remains equipped). The worldserver console shows errors related to that.

![image2](https://github.com/user-attachments/assets/cab354cb-095d-47d5-b64f-1fedce94a912)

### Expected Blizzlike Behaviour

You should be able to use items in cat/bear form and won't lose your inventory when you logout in any form

### Steps to reproduce the problem

1. Use cat/bear form
2. Try to use any consumable

or

1. Use cat/bear form
2. Logout and login
3. Check your inventory

### AC rev. hash/commit

AC> AzerothCore rev. c2be39898609+ 2024-09-25 18:03:41 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 1.
Server uptime: 22 minute(s) 15 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 1ms
|- Median: 1ms
|- Percentiles (95, 99, max): 5ms, 5ms, 6ms
Using SSL version: OpenSSL 3.0.13 30 Jan 2024 (library: OpenSSL 3.0.13 30 Jan 2024)
Using Boost version: 1.83.0
Using CMake version: 3.28.3
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.0-40-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 291014951 bytes
vmaps directory located in ../data/vmaps. Total size: 658130721 bytes
mmaps directory located in ../data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: skeleton_module_acore_string.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-eluna
|- mod-fireworks-on-level
|- mod-learn-spells

### Operating system

Ubuntu 24.04

### Custom changes or Modules

- mod-eluna
- mod-fireworks-on-level
- mod-learn-spells

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/6e4a9bbb145620938e7d39bafaad9e6f0b34c279  is the culprit
