### ISSUE TITLE
PQR,EWT Scripts block

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#2004]
PQR,Ewt, Scripts block

##### SMALL DESCRIPTION:

I don't need a lot to say. It's simple, we need it (It's totally sh1ty to play vs players who's using it).
Also i'm opening this issue, so we can track it. If someone is experienced and already give a try to try block this, share infos with us. Thanks

##### CURRENT BEHAVIOUR:

Players are able to run these things in the background.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get scripts, PQR profile and play
2. It's undetected by core
3. This software is destroying the game.

##### BRANCH(ES):

master

**Comment by poszer** [comment]
Will be great to PIN this issue if posible @FrancescoBorzi

**Comment by vhiperdev** [comment]
Some time ago I was trying to make this block, but it is complex to understand how Warden works to make these scripting blocks that come from the client.

Reference Link: https://community.trinitycore.org/topic/14569-ant-pqr-script/

**PQR and EWT**

And also forbidden macros example:

**#showtooltip Mind Freeze
/ run if GetSpellCooldown ("Mind Freeze") == 0 and IsSpellInRange ("Mind Freeze", "target") and (UnitCastingInfo ("target") or UnitChannelInfo ("target")) then CastSpellByName ("Mind Freeze") end**

**Comment by FrancescoBorzi** [comment]
@poszer pinned

**Comment by BarbzYHOOL** [comment]
I have already compiled a lot of info in a private repo on gitlab for a big anticheat (PQR included) because I felt like discussing anticheat in public wasn't the best idea. Hit me up if one of you wants to start working on this.

**Comment by Viste** [comment]
its even can be added to security(new github future).

**Comment by poszer** [comment]
> its even can be added to security(new github future).

Yeah, you re right

**Comment by lineagedr** [comment]
It's actually really simple, I've already done it on my Sunwell Core. All you need to do is a few modifications to your warden to be able to send LUA to players clients.

Example:

warden_checks table
![warden_checks](https://user-images.githubusercontent.com/12139798/60099431-4615d000-9760-11e9-9496-26fb5b0e209e.png)

In-Game:
![ingame](https://user-images.githubusercontent.com/12139798/60099485-65acf880-9760-11e9-9c0d-997ff69e58df.png)

And then you'll have to make your custom lua detection code or use one from: https://pastebin.com/BZJ2QNAM which is sniffed warden data from warmane

Like this: 
```
_=(function() if ChatFrame1 == nil then return nil end c=ChatFrame1:GetNumMessages() for i=1,c do t=ChatFrame1:GetMessageInfo(i) if string.find(t,\"\\124cffff7d0a<\\124r\\124cffffd200PQR\\124r\\124cffff7d0a>\\124r\") ~= nil then return \"PQRFOUND\" end end end)()"
```

It scans the players chat for the PQR string and if it finds it returns PQRFOUND

**Comment by Riztazz** [comment]
@lineagedr
Any chance you could tell how exactly you're sending LUA with Warden, any hint whatsoever so we can actually start working on the solution?:P

**Comment by CosmeF** [comment]
Any news on this issue? I'm getting complaints on pvp's fairness, specially with PQR. So if any of you have like a temporal solution, please give us a hand. If you are worried about the temporal fix being spread out and reverse engineered, feel free to contact me privately. I'll be discrete for the good of the fix.

**Comment by frankygat123** [comment]
@lineagedr How do you configure your warden to send that? When I have attempted to change the function for GetText it fails the checks and I never have it send the lua. I know the address for DoString over GetText, but I'm not having luck making my warden send lua

**Comment by frytik** [comment]
https://github.com/TrinityCore/TrinityCore/commit/0531463a3c02d98ed77e9c7689ad7237ecaddc09

**Comment by Helias** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/3875

**Comment by mehdikhody** [comment]
People still using PQR with 'Show message in chat' off, and Warden is not able to detect it.
