### ISSUE TITLE
[Docker] Error with the default PAGESIZE of Raspberry Pi 5

### ISSUE THREAD

**Issue by Varoso** [azerothcore/azerothcore-wotlk#20057]
### Current Behaviour

When performing a clean clone from the repository and starting it with Docker Compose, the ac-db-import container fails with the following error message:

<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
terminate called without an active exception

The default page size on the Raspberry Pi can be obtained with the command getconf PAGESIZE, which returns a value of 16384.

After researching further, I found that this can be resolved by modifying the /boot/firmware/config.txt file and adding the line kernel=kernel8.img.

Now, after restarting and running the command getconf PAGESIZE, the value 4096 is obtained, allowing the container to function correctly.

Is it possible to adapt the container to work with the Raspberry Pi's default value instead of having to make this modification?

### Expected Blizzlike Behaviour

Works with the default PAGESIZE of the Raspberry Pi

### Steps to reproduce the problem

Step 1: Perform a clean clone of the repository on a Raspberry Pi with a freshly installed Raspberry Pi OS
Step 2: Run the command docker compose build
Step 3: Run the command docker compose up -d

### AC rev. hash/commit

<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
terminate called without an active exception

### Operating system

Raspberry Pi OS Lite bassed on Debian 12

**Comment by kambire** [comment]
> ### Current Behaviour
> 
> When performing a clean clone from the repository and starting it with Docker Compose, the ac-db-import container fails with the following error message:
> 
> : Unsupported system page size : Unsupported system page size : Unsupported system page size terminate called without an active exception
> 
> The default page size on the Raspberry Pi can be obtained with the command getconf PAGESIZE, which returns a value of 16384.
> 
> After researching further, I found that this can be resolved by modifying the /boot/firmware/config.txt file and adding the line kernel=kernel8.img.
> 
> Now, after restarting and running the command getconf PAGESIZE, the value 4096 is obtained, allowing the container to function correctly.
> 
> Is it possible to adapt the container to work with the Raspberry Pi's default value instead of having to make this modification?
> ### Expected Blizzlike Behaviour
> 
> Works with the default PAGESIZE of the Raspberry Pi
> ### Source
> 
> _No response_
> ### Steps to reproduce the problem
> 
> Step 1: Perform a clean clone of the repository on a Raspberry Pi with a freshly installed Raspberry Pi OS Step 2: Run the command docker compose build Step 3: Run the command docker compose up -d
> ### Extra Notes
> 
> _No response_
> ### AC rev. hash/commit
> 
> : Unsupported system page size : Unsupported system page size : Unsupported system page size terminate called without an active exception
> ### Operating system
> 
> Raspberry Pi OS Lite bassed on Debian 12
> ### Custom changes or Modules
> 
> _No response_

To resolve this issue, you found that you can modify the /boot/firmware/config.txt file on the Raspberry Pi and add the line kernel=kernel8.img. This changes the default page size to 4096 bytes after restarting the system. Doing so allows the container to run correctly.
