### ISSUE TITLE
[The Barrens - Cavern of Mists] Boahn incorrectly dualwielding & missing ability.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20051]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7380#issue-2551185637

I can confirm the issue. He use dual wielding animation and doesn't use [Serpent Form](https://www.wowhead.com/classic/spell=8041/serpent-form) ability.

Edit: He doesn't use DW anymore.

### What client do you play on?

enGB

### Faction

Both

### Content Phase:

1-19

### Current Behaviour

~~Boahn, a rare NPC in Barrens, Wailing Caverns is attacking with both hands, despite using a 2handed weapon. This was introduced with newest update.~~

Boahn is only casting Lightning Bolt and Healing Touch.

### Expected Blizzlike Behaviour

Should not dualwield, NPC is using 2handed weapon.

NPC should also cast Snake Form (spell id 8041 ?) at around 50% HP

### Source

https://www.youtube.com/watch?v=3ZsHPkdnUvA see timestamp: 3:00 and 3:09
https://www.wowhead.com/classic/de/npc=3672/boahn#abilities

### Steps to reproduce the problem

Go to Wailing Caverns in front of dungeon entrance and fight him

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sogladev** [comment]
I can confirm he's using dual-wield with 2her; will fix this part soon

**Comment by elthehablo** [comment]
Why re-opened?

**Comment by heyitsbench** [comment]
Dual-wield issue resolved, still missing ability.

**Comment by Rorschach91** [comment]
> Dual-wield issue resolved, still missing ability.

Yup :)

**Comment by elthehablo** [comment]
I see ty

**Comment by elthehablo** [comment]
According to wowhead he shouldn't even heal. Kinda makes sense to me as it would be weird if he healed at 40% if he also transforms at 50%

**Comment by elthehablo** [comment]
Then again, it could be fine as it only lasts temporarily anyway. Eh.
