### ISSUE TITLE
bug:[Arcane Rune]After the task is completed, the NPC is not there and the task cannot be submitted.

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/azerothcore-wotlk#20066]
### Current Behaviour

last 

### Expected Blizzlike Behaviour

npc is here

### Steps to reproduce the problem

completed task.not found the npc .npc not here.

### AC rev. hash/commit

last 

### Operating system

ubuntu22.04.4

**Comment by heyitsbench** [comment]
This report has nothing of substance.
