### ISSUE TITLE
Dreamwalker in ICC 10 Heroic - When starting the battle the npc looses slowly his HP and DIES

### ISSUE THREAD

**Issue by cyberpro98** [azerothcore/azerothcore-wotlk#20065]
### Current Behaviour

Dreamwalker in ICC 10 Heroic - When starting the battle the npc looses slowly his HP and DIES.. Idk if this is normal

### Expected Blizzlike Behaviour

Dreamwalker should be healed and not loosing HP

### Steps to reproduce the problem

Start the battle in 10Heroic and you will see  that the dragon stats loosing its hp without letting the mobs attacking him.

### AC rev. hash/commit

AzerothCore rev. 94ea10985817+ 2024-04-03 21:30:41 +0200 (master branch) (Win64,
 RelWithDebInfo, Static)
Connected players: 2. Characters in world: 2.
Connection peak: 2.
Server uptime: 12 minute(s) 19 second(s)
Update time diff: 2ms. Last 500 diffs summary:
- Mean: 2ms
- Median: 2ms
- Percentiles (95, 99, max): 6ms, 6ms, 7ms
Using SSL version: OpenSSL 1.1.1w  11 Sep 2023 (library: OpenSSL 1.1.1w  11 Sep
2023)
Using Boost version: 1.81.0
Using CMake version: 3.28.1
Using MySQL version: 80035
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 6.3.9600
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.11-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: vip_command.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- HardMode
- KillStreak-Module
- boss_podling
- item_leveler
- mod-1v1-arena
- mod-ah-bot
- mod-anticheat
- mod-autobalance
- mod-cfbg
- mod-eluna
- mod-item-upgrade
- mod-npc-free-professions
- mod-premium
- mod-pvp-titles
- mod-sell-items
- mod-solo-lfg
- mod-solocraft
- mod-transmog
- mod_TwilightEvent
- mod_world_chat
- vipCommands

### Operating system

Windows 2012 

### Custom changes or Modules

Just the configs modified as i need them.

**Comment by Nyeriah** [comment]
![image](https://github.com/user-attachments/assets/78d3fa1b-c33d-44be-adba-3a588440897f)

**Comment by cyberpro98** [comment]
So is it normal that the Health goes down in 10Man Heroic Mode?
