### ISSUE TITLE
Feature: Auto Updater - change path for Base files and update files in .conf files

### ISSUE THREAD

**Issue by Badgermilk0** [azerothcore/azerothcore-wotlk#20070]
### Describe your feature request or suggestion in detail

Ability to modify all PATHS for all type of SQL imports, including the BASE import files, in .conf files.

Currently updates, custom and archive can be configured in the DB table updates_include for each DB.

### Describe a possible solution to your feature or suggestion in detail

Add parameters to worldserver.conf and authserver.conf for all types of SQL imports.
Base, updates, custom

**Comment by kambire** [comment]
I solved all my problems with updates on Linux, and it works perfectly. You can manage all the updates automatically using the acore.sh tool. If you need help using it, I can assist you.

**Comment by Badgermilk0** [comment]
Might be outside of my current competence but I will look in to it, thanks for guidance. =)
I also noticed that the the .conf files already have parameters to change the SOURCE path, so I guess I can already do what I want by keeping the sourcefolder close to the installation.
