### ISSUE TITLE
[Issues Druid Equipment and Form] Missing Gear and Trinket Activation Errors in Cat/Bear Form after Logout

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#20085]
### Current Behaviour

Upon logging back in after being logged out in cat form, the character was missing all equipped items and bags. The missing items were found in the mailbox, sent from the account "Customer Support" with the subject "This item(s) have problems with equipping." I received all the items and bags, but couldn't equip the bags while in cat form. The message displayed was "You can't do that while disarmed." After shifting out of cat form, I was able to equip the bags and retrieve all other items.

Attempting to equip items using the Equipment Manager while in cat form resulted in multiple "You can't do that while disarmed" messages. Upon shifting out of cat form, the items equipped correctly. When trying to use trinkets like "Medallion of the Horde" in cat form, the message "The item was not found" appeared multiple times, despite the game playing the activation sound. Shifting out of cat form showed the character animation attempting to activate the trinket. The trinket worked properly when activated outside of cat form.

### Expected Blizzlike Behaviour

Equipped Items and Bags: Upon logging back in, the character should retain all equipped items and bags, regardless of the form the druid was logged out in (cat, bear, or any other form). Items and bags should not be automatically sent to the mailbox due to any equipping issues.

Equipment Manager: The Equipment Manager should allow items to be equipped in any form, including cat and bear forms, without displaying "You can't do that while disarmed" messages. The form of the druid should not restrict the ability to equip or swap gear.

Trinket Activation: Trinkets, such as the "Medallion of the Horde", should activate correctly while in cat or bear form without showing the "The item was not found" message. The activation should work seamlessly, regardless of the druid's form.

### Steps to reproduce the problem

1.- Log out as a druid in cat or bear form.
2.- Log back in; the character appears without any items or bags equipped.
3.- Retrieve items from the mailbox and attempt to equip bags while in cat form.
4.- Attempt to equip items using Equipment Manager while in cat or bear form.
5.- Try activating a trinket while in cat form.

### AC rev. hash/commit

AC> AzerothCore rev. c2be39898609+ 2024-09-25 18:03:41 +0000 (HEAD branch) (Unix, Release, Static)
Connected players: 16. Characters in world: 16.
Connection peak: 65.
Server uptime: 1 day(s) 8 hour(s) 51 minute(s) 21 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 7ms
|- Median: 2ms
|- Percentiles (95, 99, max): 19ms, 20ms, 21ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-122-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: ghost_speed.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg
|- mod-ghost-speed
|- mod-learn-spells

### Operating system

Ubuntu 22

### Custom changes or Modules

mod-anticheat
mod-breaking-news-override
mod-cfbg
mod-ghost-speed
mod-learn-spells

**Comment by TheSCREWEDSoftware** [comment]
On: AzerothCore rev. bb0d292e1c2b 2024-09-22 07:38:46 +0000 (master branch) (Win64, RelWithDebInfo, Static)

Couldn't replicate the said above.

My druid kept his items and bags and I was able to equip my bags with any shapeshift form (bear, cat, dire bear and travel form).

The only issue i had with the equipement manager was just when the inventory was full you couldnt change sets.

> [!NOTE]  
> For those whom want to test. To enable "Equipment Manager" go to Optins => Interface => Features and check it, from there your characther sheet should have a on the top right Equipment Manager

**Comment by Nyeriah** [comment]
Update your core before reporting new issues

**Comment by kambire** [comment]
> Update your core before reporting new issues

I usually perform the database and core updates on Wednesdays at 2:00 PM. Doing daily core updates and restarts can be a bit disruptive for the players, so I limit it to once a week and keep track of any feedback from users during that time. I apologize if I report something that has already been fixed—I'm only trying to help the community and make sure any issues are known, just in case they haven’t been addressed yet

**Comment by Nyeriah** [comment]
I understand it’s much appreciated that you’re providing reports. But this has indeed already been fixed

**Comment by Nyeriah** [comment]
For reference https://github.com/azerothcore/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3
