### ISSUE TITLE
[Quest] Bang a Gong! (ID: 8743) - Scarab Lord questline not completing

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#20103]
### Current Behaviour

Description: There is an issue with the final quest of the Scarab Lord questline, "Bang a Gong!" **(Quest ID: 8743)**. The NPC that should provide the quest does not offer it, preventing players from completing the questline.

### Expected Blizzlike Behaviour

Upon reaching the final step of the questline and having the required item, the NPC should offer the quest "Bang a Gong!" so players can finish the chain.

### Steps to reproduce the problem

1.- Complete all the prerequisite quests in the Scarab Lord chain.
2.- Obtain the item necessary to strike the gong.
3.- Interact with the NPC to receive the final quest.
4.- Observe that the quest is not offered.

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. c2be39898609+ 2024-09-25 18:03:41 +0000 (HEAD branch) (Unix, Release, Static)
Connected players: 50. Characters in world: 49.
Connection peak: 65.
Server uptime: 1 day(s) 22 hour(s) 39 minute(s) 50 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 8ms
|- Median: 3ms
|- Percentiles (95, 99, max): 23ms, 24ms, 25ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-122-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: ghost_speed.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg
|- mod-ghost-speed
|- mod-learn-spells

### Operating system

Ubuntu 22

### Custom changes or Modules

mod-anticheat, mod-breaking-news-override, mod-cfbg, mod-ghost-speed, mod-learn-spells

**Comment by Tereneckla** [comment]
The Temple of Ahn'Qiraj is open by default on wotlk servers. The quest Bang a Gong! only is available when it is closed/12h after the first turn in
