### ISSUE TITLE
Missing NPC - Flynn Firebrew (ID: 24364)  is missing from the database

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#20101]
### Current Behaviour

 The NPC Flynn Firebrew, ID 24364, is missing from the database in my AzerothCore setup. This NPC is critical for the Brewfest event and is supposed to spawn in the event zone. When attempting to add it manually, the entry does not exist in the database.

### Expected Blizzlike Behaviour

Flynn Firebrew should be present in the Brewfest event, offering his services related to the festivities. The NPC must give a task that involves delivering beers for a return delivery.

### Steps to reproduce the problem

1.- Log in during the Brewfest event.
2.- Go to the event area and search for the NPC Flynn Firebrew (ID: 24364).
3.- Attempt to spawn the NPC using .npc add 24364 or search for the NPC in the database.

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. c2be39898609+ 2024-09-25 18:03:41 +0000 (HEAD branch) (Unix, Release, Static)
Connected players: 44. Characters in world: 43.
Connection peak: 65.
Server uptime: 1 day(s) 21 hour(s) 51 minute(s) 58 second(s)
Update time diff: 6ms. Last 500 diffs summary:
|- Mean: 9ms
|- Median: 2ms
|- Percentiles (95, 99, max): 25ms, 25ms, 26ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80039
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-122-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: charactersdb_anticheat.sql
Latest WorldDatabase update: ghost_speed.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-anticheat
|- mod-breaking-news-override
|- mod-cfbg
|- mod-ghost-speed
|- mod-learn-spells

### Operating system

Ubuntu 22

### Custom changes or Modules

mod-anticheat, mod-breaking-news-override, mod-cfbg, mod-ghost-speed, mod-learn-spells

**Comment by sudlud** [comment]
he has a spawn
`.go c 240002`

but when going there, he's not visible / at that location as it seems

**Comment by sudlud** [comment]
also there's seems to be a condition to be able to see him

**Comment by kambire** [comment]
> also there's seems to be a condition to be able to see him

You're right, it’s there, but it’s not visible. When you’re on the mission mount, it becomes visible. Now, he’s supposed to hand out some barrels of beer, but the NPC has nothing—he doesn’t give the barrel.
