### ISSUE TITLE
[DK Starter Chain Quest] A Special Surprise. Some issues.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20111]
### Current Behaviour

Quest can be completed, but:
All npcs in the room can be killed by the player.
Player's race npc can be instantly killed.
All Npcs have a chance to dodge, parry or miss your attack.

Evidence: [Youtube](https://youtu.be/VvS0Nq_GOtA)

### Expected Blizzlike Behaviour

You can only kill your race's npc.
You can be able to kill your race's npc only when it finishes its dialogue line.
Npcs shouldn't be able to parry, dodge or miss your attack, they are basically dummies.

How it should work: [Youtube](https://www.youtube.com/watch?v=9lzb-Gz5bD4&t)

### Steps to reproduce the problem

1. Start the quest.
2. Go into the house

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/784e80668d5b57640a4c7a4d6e2c7b898e4f804d

### Operating system

Windows 11

**Comment by TheSCREWEDSoftware** [comment]
Also to add to your video, not happening to the same race as but to the gnome, double checking (whenever this get fixed) making sure that none of the NPCs can actually parry or block your attack (like the gnome did).

**Comment by Rorschach91** [comment]
> Also to add to your video, not happening to the same race as but to the gnome, double checking (whenever this get fixed) making sure that none of the NPCs can actually parry or block your attack (like the gnome did).

I checked again and I can confirm that all npcs have a chance to parry, dodge or miss an attack.
