### ISSUE TITLE
[Grizzly Hills] Escape from Silverbrook

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20127]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7388#issue-2558230786

Watch this comment: https://github.com/chromiecraft/chromiecraft/issues/7388#issuecomment-2385667264

### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

75-79

### Current Behaviour

On the Escape from Silverbrook quest in Grizzly Hills, the cage does not open to let out the caged prisoner for the escape to initiate. 

![image](https://github.com/user-attachments/assets/43cb74a0-bca8-494a-b02e-4b48fadb035e)
![image](https://github.com/user-attachments/assets/3efa34f1-1d2a-4f98-ba5e-b7c1d8ad9629)

### Expected Blizzlike Behaviour

After accepting the quest, the cage should open and the prisoner should escape from the cage and run around the back of the houses to the horses. This should trigger an event where the player should hop onto the prisoner's horse and you will both escape together while Worgen case you. 

### Source

https://www.wowhead.com/wotlk/quest=12308/escape-from-silverbrook
https://www.wowhead.com/wotlk/quest=12308/escape-from-silverbrook#videos:id=241064

### Steps to reproduce the problem

1. Complete these quests:

[[73] The Hills Have Us](https://www.wowhead.com/wotlk/quest=12511) (Ride a gryphon from Dragonblight to Amberpine Lodge in Grizzly Hills)
[[74] Local Support](https://www.wowhead.com/wotlk/quest=12292) (Collect [Cedar Chest](https://www.wowhead.com/wotlk/object=189298) (in a house guarded by 3 hordes))
[[74] Close the Deal](https://www.wowhead.com/wotlk/quest=12293) (Simply go to [Ivan](https://www.wowhead.com/wotlk/npc=27469))
[[74] A Tentative Pact](https://www.wowhead.com/wotlk/quest=12294) (Simply go back to [Lieutenant Dumont](https://www.wowhead.com/wotlk/npc=26875))
[[74] An Exercise in Diplomacy](https://www.wowhead.com/wotlk/quest=12295) (Yet another go-to quest. Go to [Envoy Ducal](https://www.wowhead.com/wotlk/npc=26821))

Part 2 (Helping the northern locals)
Finishing part 1 unlocks 2 independent quests
[[74] Wolfsbane Root](https://www.wowhead.com/wotlk/quest=12307) (Collect 8 [Wolfsbane Roots](https://www.wowhead.com/wotlk/object=189313) around [28.5, 38.5](https://www.wowhead.com/wotlk/maps=394:285385))
[[74] Northern Hospitality](https://www.wowhead.com/wotlk/quest=12299) (Kill 8 [Conquest Hold Marauders](https://www.wowhead.com/wotlk/npc=27424))

Part 3 (Is there something suspicious?)
Finishing part 2 unlocks this chain
[[74] Test of Mettle](https://www.wowhead.com/wotlk/quest=12300) (Kill [Sergeant Bonesnap](https://www.wowhead.com/wotlk/npc=27493) and a guard next to him. Ignore the provided quest item)
[[74] Words of Warning](https://www.wowhead.com/wotlk/quest=12302) (Go to [Caged Prisoner](https://www.wowhead.com/wotlk/npc=27499))

3. Teleport to "Caged Prisoner" in Grizzly Hills (26.5, 32.0)
4. Start Quest
5. Observe that the cage does not open and the quest does not continue after accepting the quest.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8a0604479af820c5b0cfdb3fdb02985d240d79d3

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
> ### Content Phase:
> 70

I know it doesn't ultimately matter very much, but this is just not true.

**Comment by Rorschach91** [comment]
> > ### Content Phase:
> > 70
> 
> I know it doesn't ultimately matter very much, but this is just not true.

What?

**Comment by elthehablo** [comment]
That's because we don't really expect people to post wotlk issues there

**Comment by mwk102** [comment]
Oops! That's my bad, is there another spot for WoTLK issues?

**Comment by elthehablo** [comment]
> Oops! That's my bad, is there another spot for WoTLK issues? 
> 
> Edit: nevermind, its here :D My fault for submitting in the wrong repo! I'll bookmark this one.

Where you are now :)

**Comment by TheSCREWEDSoftware** [comment]
I've been able to make the door open. 

And probably make the NPC dissepear also. Been having issues with It casting the spell that summons the NPC on the imp.

**Comment by TheSCREWEDSoftware** [comment]
I was able to go around from casting the spell to summon the entity as it contains all the logic there.

The video of my fix on youtube [here](https://www.youtube.com/watch?v=Q0ayxICRNUI)

The order of logical / SAI:
1 - When the player accepts the quest, the Cage opens.
2 - Quest giver becomes invisible (still alive).
3 - Spawn the NPC that the quest giver should cast (as the cast it's a self cast and targeting doesnt work) on top of the generic trigger imp that there.
4 - Despawns after half a second. (which i pressume when it "dies" while GM is part of it).

Issues that came after being able to do the questline properly. I'm not at my PC so I dont have 100GB space for WoW. to test and sniff the questline.

But the horse will part away without you after a time. And I dont think it dispawns if he goes away too far.

Don't think you can "fail" the quest even if you lose the horse npc.

I could add to the SAI an another condition to dispawn if it was failed or abandoned (this im not sure).

If you feel like taking testing it to see i can go foward with a PR with this.

```SQL
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 27499;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 27499);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(27499, 0, 0, 1, 19, 0, 100, 0, 12308, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 20, 188706, 10, 0, 0, 0, 0, 0, 0, 'Caged Prisoner - On Quest \'Escape from Silverbrook\' Taken - Activate Gameobject'),
(27499, 0, 1, 2, 61, 0, 100, 0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Caged Prisoner - On Quest \'Escape from Silverbrook\' Taken - Set Visibility Off'),
(27499, 0, 2, 3, 61, 0, 100, 0, 0, 0, 0, 0, 0, 0, 12, 27411, 6, 1200000, 0, 0, 0, 19, 24042, 10, 0, 0, 0, 0, 0, 0, 'Caged Prisoner - On Quest \'Escape from Silverbrook\' Taken - Summon Creature \'Freed Alliance Scout\''),
(27499, 0, 3, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 0, 41, 500, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Caged Prisoner - On Quest \'Escape from Silverbrook\' Taken - Despawn In 500 ms');

```
