### ISSUE TITLE
[World] Crash 20241005

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#20138]
### Current Behaviour

https://pastebin.com/fNSuREM5

When fight with IIidan and after the vedio ranfance the BUG report , one of fight with the IIidan case the server crash.
https://github.com/azerothcore/azerothcore-wotlk/issues/19990

might becasue the "check" is null?

![image](https://github.com/user-attachments/assets/bc6ce64d-0d18-4e98-821e-e2fbad15481b)

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 01b86ec7a6c9 2024-10-04 11:01:36 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 5 minute(s) 10 second(s)
Update time diff: 100ms. Last 500 diffs summary:
|- Mean: 100ms
|- Median: 100ms
|- Percentiles (95, 99, max): 101ms, 101ms, 101ms
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80402
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-1-pve
Worldserver listening connections on port %u
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: mod-zone-difficult.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-difficult
|- mod-eluna

### Operating system

Debian 12 with PVE

**Comment by sudlud** [comment]
@Nyeriah probably fixed with #20163?

**Comment by Nyeriah** [comment]
yes, reopen if it happens again

**Comment by kissingers** [comment]
OK, if crash I will open another issue, close it first.
