### ISSUE TITLE
[DK Starting Area] Horses don't run from Stables to New Avalon.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20146]
### Current Behaviour

On AC, there is an immobile Horses Pack near New Avalon. 

![Running Horses](https://github.com/user-attachments/assets/414050a7-a04c-4220-a382-1461b19c2f9a)

### Expected Blizzlike Behaviour

This pack should periodically spawn at the Havenshire Stables and then running until New Avalon.

Evidence: [Youtube ](https://www.youtube.com/watch?v=4teUyejpjjw)from minute 3:00

### Source

Official Server

### Steps to reproduce the problem

1. You can see this issue by exploring the map.

### Extra Notes

Before fixing this issue, look at this [report](https://github.com/azerothcore/azerothcore-wotlk/issues/20142).

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/538b8a45fa0855d5e34e08bad377fde02227c58f

### Operating system

Windows 11

**Comment by TheSCREWEDSoftware** [comment]
Do they have waypoints or these also require some sniffing?

**Comment by Rorschach91** [comment]
> Do they have waypoints or these also require some sniffing?

They use a waypoint in the official servers. If you want to sniff it, you can use TWW waypoints (they are not been changed between the various expansions).
The guid smartai should be something like this:

On Respawn-Start Waypoint "waypoint id" (waypoint must be setted to "run").
Waypoint ended-Force Despawn- despawn timer 2000 ms, respawn timer XX seconds (I don't know what seconds/minutes are after the despawn).

Havenshire Stallion probably spawn 1-2 seconds before Havenshire Mare and Havenshire Colts.

**Comment by TheSCREWEDSoftware** [comment]
I will see if i get some sniffing done on these then (in the weekend) if you're not in a rush.

**Comment by Rorschach91** [comment]
> I will see if i get some sniffing done on these then (in the weekend) if you're not in a rush.

No rush dude, take your time.
