### ISSUE TITLE
[Class - Shaman] Mana Spring Totem doesn't refresh mana.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20140]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7393#issue-2562907475

It seems that Mana Spring Totem Aura doesn't refresh player's mana. 

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Shaman class mana spring totem is not refreshing my mana.  The mana increase while thee totem is active is the same as sitting

### Expected Blizzlike Behaviour

Each totem has a specified mana increase amount, the different mana totems are not increasing mana while active for the specified amount

### Source

https://wowpedia.fandom.com/wiki/Mana_Spring_Totem

### Steps to reproduce the problem

1.  as a shaman open a mana spring totem
2. the shaman mana is not increasing more than if the shaman was sitting.
3. The expected result would be the man is increasing by the specified amount while the totem is active

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/529e9140323edeef916bd6a1b6c97e13aa38db08

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cgrahamseven** [comment]
I can’t repro this in AC. I created a shaman, added all skills and tested MP5 with no totem and confirmed it matched my base value of 44. I then used mana spring totem and observed the buff activate and my mana regen went from 44 to 153 for a rank 8 totem and I could visibly watch my total mana increasing faster than before I had cast the totem.

**Comment by Rorschach91** [comment]
Uhm...That's strange. When I have reported this issue was present. Maybe it was a temporary bug.
It can be closed. Thank you for the warning.
