### ISSUE TITLE
Shaman - Dual Wield Specialization not adding hit chance

### ISSUE THREAD

**Issue by oblivion-hymns** [azerothcore/azerothcore-wotlk#20158]
### Current Behaviour

Currently, the Enhancement Shaman talent "Dual Wield Specialization" (SpellIDs 30816, 30818, 30819) does not seem to apply the hit chance (2%, 4%, and 6%, respectively).

### Expected Blizzlike Behaviour

The Enhancement Shaman talent should apply an additional 2%, 4%, and 6% hit chance at each talent point level, respectively.

### Steps to reproduce the problem

1. Add 1, 2, and 3 talent points to Dual Wield Specialization
2. Notice that the hit chance does not update

### AC rev. hash/commit

```
AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 5 minute(s) 36 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 4ms, 5ms
Using SSL version: OpenSSL 3.3.2 3 Sep 2024 (library: OpenSSL 3.3.2 3 Sep 2024)
Using Boost version: 1.81.0
Using CMake version: 3.30.3
Using MySQL version: 80402
Found MySQL Executable: C:/xampp/mysql/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_03_00.sql
Latest WorldDatabase update: z_filter_disabled_and_trash.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-aoe-loot
|- mod-autobalance
|- mod-solo-lfg
```

### Operating system

Windows 10 x64

### Custom changes or Modules

Enabled: AH Bot, Autobalance, Solo LFG
Disabled: AOE Loot

**Comment by heyitsbench** [comment]
Might just be a visual issue, possible discrepancy between the combat rating (what gets shown in the character sheet) and `m_modMeleeHitChance` (what the spell is actually affecting). If it is just a visual issue, need confirmation as to whether it's Blizzlike or not.

**Comment by oblivion-hymns** [comment]
Yeah, I just read that in WoTLK these talents don't show on your character sheet. So it's Blizzlike the way it is (although it's a bit of an odd design decision). Sorry about that.

**Comment by Kitzunu** [comment]
fix your hash
