### ISSUE TITLE
Zeppelin to Borean Tundra disappear and players fall off to their deaths

### ISSUE THREAD

**Issue by AldebaraanMKII** [azerothcore/azerothcore-wotlk#20162]
### Current Behaviour

See title

### Expected Blizzlike Behaviour

That the players are teleported to Warsong Hold.

### Steps to reproduce the problem

1. Enter the zeppelin to Borean Tundra in Durotar
2. Wait for it to get to the end
3. Fall off to your death

### AC rev. hash/commit

AzerothCore rev. af776520dbd5 2024-09-13 17:45:21 +0800 (Playerbot branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by manstfu** [comment]
Hello, this is related to playerbot branch, not confirmed on stock AC

**Comment by AldebaraanMKII** [comment]
Yes. And it was caused by me not setting EnablePlayerSettings to 1 when using Individual Progression module. Sorry about that.
