### ISSUE TITLE
Zul Aman: Nalorakk misses instance->SetData(DATA_NALORAKKEVENT,xxx)

### ISSUE THREAD

**Issue by Boxhead78** [azerothcore/azerothcore-wotlk#20171]
### Current Behaviour

I noticed since https://github.com/azerothcore/azerothcore-wotlk/commit/b959d5cc87e262efdebf1fc079a3637b41af3df2 Nalorakk misses following lines:
- instance->SetData(DATA_NALORAKKEVENT, NOT_STARTED);
- instance->SetData(DATA_NALORAKKEVENT, IN_PROGRESS);
- instance->SetData(DATA_NALORAKKEVENT, DONE);

I don't know why these got removed or if it was intended but now the questtimer won't get additional 15 minutes by defeating nalorakk and also GO_GATE_HEXLORD won't open after 4 bosses are killed since SetData() isn't run after nalorakk dies.

### Expected Blizzlike Behaviour

1. Questtimer increased by 15 minutes after nalorakk dies.
2. GO_GATE_HEXLORD should open after 4 bosses are killed.

### Steps to reproduce the problem

1. Go into raid Zul Aman kill Nalorakk => See timer isn't increased by 15 minutes.
2. Go into raid Zul Aman kill 4 bosses => Door to Hexlord won't open even though it should.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/31cb7579e0f2240a4e68d8d8d499dc4160f82988

### Operating system

Win 11

**Comment by kissingers** [comment]
Already fixed but not merge for a long time 

https://github.com/azerothcore/azerothcore-wotlk/pull/19895

**Comment by Nefertumm** [comment]
They were removed because SetData is handled generically by the BossAI class. It's odd though that it doesn't work without kissinger's PR, as it should set the data to done automatically on kill.

**Comment by kissingers** [comment]
I know will fix in BossAI, But it's been 3 months since the boss script was changed, and the problems caused by it haven't been fixed yet, so I think we should make the instance works first, and then fix by BossAI.

**Comment by kissingers** [comment]
Now it's obvious that half of the changes were made and then ignored the instance normal work.

**Comment by kissingers** [comment]
Obviously, the PR of AZ now prefers to fix some features, but very little attention is paid to fixing the instance, in fact the instance experience is the most important part of the simulator, and should be prioritized over the fixing of other features besides the crash!

**Comment by Nyeriah** [comment]
> They were removed because SetData is handled generically by the BossAI class. It's odd though that it doesn't work without kissinger's PR, as it should set the data to done automatically on kill.

SetBossState is, not SetData. SetData is the deprecated handling of boss states

**Comment by kissingers** [comment]
Thanks, I try find how use SetBossState  and use this to modify all ZulAman boss and test it.


> > They were removed because SetData is handled generically by the BossAI class. It's odd though that it doesn't work without kissinger's PR, as it should set the data to done automatically on kill.
> 
> SetBossState is, not SetData. SetData is the deprecated handling of boss states

**Comment by Nefertumm** [comment]
> > They were removed because SetData is handled generically by the BossAI class. It's odd though that it doesn't work without kissinger's PR, as it should set the data to done automatically on kill.
> 
> SetBossState is, not SetData. SetData is the deprecated handling of boss states 

Indeed, that's what I meant to say. 😵‍💫

**Comment by kissingers** [comment]
It sees still can not use SetBossState replace SetData because only 2 boss use BossAI, others still use CreatureScript, so temp fix all BossAI will still need add SetData, till all boss change to BossAI then can replace to SetBossState. So it need two step change otherwise will destory the instance normal work

class boss_akilzon : public CreatureScript
struct boss_halazzi : public BossAI
class boss_hexlord_malacrass : public CreatureScript
class boss_janalai : public CreatureScript
struct boss_nalorakk : public BossAI
class boss_zuljin : public CreatureScript
class npc_zulaman_hostage : public CreatureScript
class npc_harrison_jones : public CreatureScript

**Comment by Nyeriah** [comment]
Don't worry about it, instance will be updated in the following weeks

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/0cb6081bc72f6d1a20e06f3eee598671e1ee49b8
