### ISSUE TITLE
[Spell] Shield Slam

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#2019]
DESCRIPTION: Warrior spell [Shield Slam] can to dispels 1 magic effect on the target, but spell will to remove more of spells and buffs.. 

STEPS TO REPRODUCE THE PROBLEM:
Paladin use spell [Avenging Wrath] Warrior will to Dis by [Shield Slam]

:grin:
https://wotlk-twinhead.twinstar.cz/?spell=30356

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/e15a0c218942f602d55584b7235eb69254c3a35b

OPERATING SYSTEM:Windows Server 2016

MODULES:
mod-npc-beastmaster
mod-vas-autobalance

**Comment by WarCrafte** [comment]
Fix Cod

`
                // Remove cooldown on Shield Slam
                if (Player* player = GetTarget()->ToPlayer())
                    player->GetSpellHistory()->ResetCooldown(SPELL_WARRIOR_SHIELD_SLAM, true);
            }
`

**Comment by poszer** [comment]
Shield Slam - Dispels 1 magic effect on the target, e.g. Paladin Wings, Warlock Sacrifice, Shaman's Heroism or Blood lust...
What's actually problem, it dispel more than 1 magic effect?

**Comment by Shard-MW** [comment]
It works fine for me

**Comment by poszer** [comment]
Can't reproduce. Closing this issue
https://github.com/azerothcore/azerothcore-wotlk/issues/2019#issuecomment-506996116
