### ISSUE TITLE
[Aura bug] The weapon's spell damage lost after some enchanting buffs be canceled

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#20203]
### Current Behaviour

After enchanting a shaman's firetongue weapon or a warlock's flamestrike, if the enchantment is removed, the weapon's spell damage effect is also removed.
This does not happen with heirlooms.

before
![image](https://github.com/user-attachments/assets/5db36a20-f5cf-448d-802e-e660a90fc26b)

after
![image](https://github.com/user-attachments/assets/06f12951-8a8e-4609-9146-991bf0e6a7a6)

cancel(both weapon power effect remove)
![image](https://github.com/user-attachments/assets/65dd5348-1afb-4388-b00e-b2a18731abaf)

remove the weapon(power no change same as cancel) and equip again(back to before)
![image](https://github.com/user-attachments/assets/4fc14fa6-5754-47d7-ade8-6252a457ce52)

### Expected Blizzlike Behaviour

Will only remove aura enchanting

### Steps to reproduce the problem

1. lookup power of mana
2. click spell 25489 and lookup
3. cancel aura 25489 and lookup
4. remove weapon lookup
5. equip and lookup

### AC rev. hash/commit

AzerothCore rev. 7afaaaedee77 2024-10-12 11:07:00 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 30 second(s)
Update time diff: 100ms. Last 223 diffs summary:
|- Mean: 101ms
|- Median: 100ms
|- Percentiles (95, 99, max): 101ms, 101ms, 352ms
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80402
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-1-pve
Worldserver listening connections on port %u
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: mod-zone-difficult.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-difficult
|- mod-eluna

### Operating system

Debian 12 with PVE

**Comment by kissingers** [comment]
spell 25489
item 40773 41194

**Comment by kissingers** [comment]
git checkout 97aaf8490cdde12d194558c4ee5acf037b5cd1b5   will not happen

**Comment by heyitsbench** [comment]
Likely caused by 9f58d55a1d97d681114964fec540b7c728b17b52.

CC: @walkline

**Comment by kissingers** [comment]
git checkout 7690c35208429fcca48ab1b7ed7e2b35d060b888  will not happen

**Comment by kissingers** [comment]
git checkout ee870ff3b37bc092654ae19b37db732bd83ae068   will not happen

**Comment by kissingers** [comment]
git checkout cc37941ef550e1465a112e1400325d5b1716fca1 will not happen

**Comment by kissingers** [comment]
git check 9f58d55a1d97d681114964fec540b7c728b17b52 happen

**Comment by kissingers** [comment]
sure is this problem
https://github.com/azerothcore/azerothcore-wotlk/pull/20128

and seems this fix will case cpu 100%
https://github.com/openwow-org/azerothcore-wotlk/commit/3790d3ccdf264543e981892bdc9c50cd54566ea2

**Comment by walkline** [comment]
I didn't understand your issue. What is the expected outcome from the steps to reproduce?


https://github.com/user-attachments/assets/7bb403fe-ef10-4510-93a2-bd352a9e90b8


Everything looks correct for me. Can you explain the issue more clearly?

**Comment by kissingers** [comment]
first need a weapon have power such as item 34336 ,it have power 292,  the equip it, and use spell 25489 enchat it. then clear the spell aura effect 25489, the power will reduce the spell 25489 effect about 70 and also remove weapon power 292, total about 360. then if tack off the weapon, the player power will not change. and then tack on the weapon, the power come back.
the weapon must not heirlooms. and not the no power weapon

**Comment by kissingers** [comment]
https://github.com/user-attachments/assets/6589220f-6bc0-44a9-a8b8-9f85cbe9eeee

and when the buff timeout ,the weapon will lost power 292 till remove and reequip the weapon

**Comment by kissingers** [comment]
I rebulid the server and all the sql, still same.

**Comment by kissingers** [comment]
it seem not all weapon will act this bug, if I use 45612 will not, but most 70 level weapon will action
