### ISSUE TITLE
[Black Temple - Illidan] Players inside Shadow Prison are not immune to damage.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20215]
Bug Triaging Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7425#issue-2586512509

I can confirm the issue for the players. They take damage from Flame Crash and Parasitic Shadowfiend debuff.

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Currently, if you stand on top of a Flame Crash going into the phase five transition, you will die.

### Expected Blizzlike Behaviour

You should be immune to all damage while under the effects of Shadow Prison.

### Source

[Wowhead comment](https://www.wowhead.com/spell=40647#comments:id=338959), [Cataclysm solo video](https://www.youtube.com/watch?v=1yE_NQ_QWOA&t=246s) (can see Felguard taking no damage from Flame Crash)

### Steps to reproduce the problem

1. Illidan.
2. Phase three.
3. Flame Crash.
4. Stand in it.
5. Phase five.
6. Die to Flame Crash.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0fa770d56788196bda608343dde4ceb452848f89

### Operating system

Ubuntu 22.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
spell data is fine

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L4293

is broken and only applies melee immunity
