### ISSUE TITLE
[SOAP PDUMP] Runeforge

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20230]
### Current Behaviour

Using SOAP pdump load on Death Knight characters, [Runeforging ](https://www.wowhead.com/wotlk/spell=53428/runeforging) does not open up, **_until full server restart._**

It is visible in spellbook, character has skill and quest chain completed, but it doesn't open!

For me it looks like Runeforging spell has an additional check that runs on cached version of the server.

https://github.com/user-attachments/assets/22d82da1-9da8-488b-9842-fbca083a7c49

Similar issue: https://github.com/azerothcore/azerothcore-wotlk/issues/18391

### Expected Blizzlike Behaviour

Open runeforging

### Steps to reproduce the problem

Very complicated.

### AC rev. hash/commit

rev. 9182e970d4ba

### Operating system

Debian 12

**Comment by TheSCREWEDSoftware** [comment]
See if this pr fixes it https://github.com/azerothcore/azerothcore-wotlk/pull/20232

**Comment by manstfu** [comment]
No it doesn't

**Comment by TheSCREWEDSoftware** [comment]
`.pdump write` on a fresh DK and `.pdump load`. 

Wouldn't allow me to use the runeforge. As I pressume i'm in the Death Knight Starting Area (instance) without being in the Instance itself. 

When I use the ebon portal, I was able to runeforge my weapon.

I never had an issue with the menu not opening. Just couldn't runeforge.

Also images about the different maps you're part of. (didn't check what is the correct gameboject runeforge).

My video [here](https://www.youtube.com/watch?v=5YE_zMLBHfE&ab_channel=TheSCREWEDSoftware)

Tested on rev: AzerothCore rev. e58c9cba422d 2024-09-23 10:31:03 +0000 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

<details>
<summary>Images of the "Map"</summary>

Start DK (Map 609, Ebon) Phase 1
![Screenshot_27](https://github.com/user-attachments/assets/3f0c7358-f9a3-404a-9e03-239fa0914b62)

After you pdump a new DK (Map 609, Ebon) Phase 1
![image](https://github.com/user-attachments/assets/68ab3e50-0ebb-47ef-bf0a-2f8f0e4c3569)


After you use the gate (Map 0, East. Kingdoms) PHase 1
![Screenshot_28](https://github.com/user-attachments/assets/866aae4a-7c65-48ba-b6c4-ccde1523dffd)


</details>

**Comment by TheSCREWEDSoftware** [comment]
If you want testing closer to your issue, give me the exact steps you did, level, zone, and progression with the chracther or just give me the pdump file so i can try it on my end with the same variables, otherwise i can't replicate your issue.
