### ISSUE TITLE
localized acore_string values need update for fmt

### ISSUE THREAD

**Issue by Onjiary** [azerothcore/azerothcore-wotlk#20233]
### Current Behaviour

![WoWScrnShot_101724_193516](https://github.com/user-attachments/assets/62ff720d-af83-4fad-88c0-1450f7324e66)

this happens when you use a command in the game

### Expected Blizzlike Behaviour

that the localized acore_string variables output the texts properly for the respective language

### Steps to reproduce the problem

go plz ingame for the german-language and write in the chat  .gps  all gm commands not localized for the language 

### AC rev. hash/commit

.server debug
AzerothCore rev. 46c9f8234b09 2024-10-15 19:09:12 +0000 (master branch) (Win64, Debug, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Laufzeit des Servers: %s
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 6ms
|- Median: 2ms
|- Percentiles (95, 99, max): 16ms, 20ms, 37ms
Using SSL version: OpenSSL 3.1.2 1 Aug 2023 (library: OpenSSL 3.0.9 30 May 2023)
Using Boost version: 1.78.0
Using CMake version: 3.27.5
Using MySQL version: 80039
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in C:/Users/Onjiary/Desktop/Azerothcore/build/bin/Debug/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Users/Onjiary/Desktop/Azerothcore/build/bin/Debug/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Users/Onjiary/Desktop/Azerothcore/build/bin/Debug/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: deDE.
All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: 2024_10_15_32.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules are enabled

### Operating system

Windows 10

**Comment by sudlud** [comment]
@Kitzunu

**Comment by Kitzunu** [comment]
![image](https://github.com/user-attachments/assets/98e8d6af-64b0-4e24-a871-e4e99376e6ae)

Your DB is wrong

AzerothCore rev. fd52e6160bfa 2024-10-19 09:57:28 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
Server uptime: 2 minute(s) 30 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 5ms, 6ms, 9ms
Using SSL version: OpenSSL 3.3.1 4 Jun 2024 (library: OpenSSL 3.3.1 4 Jun 2024)
Using Boost version: 1.85.0
Using CMake version: 3.27.4
Using MySQL version: 80401
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.4/bin/mysql.exe
Compiled on: Windows 10.0.22631
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./data/maps. Total size: 291014951 bytes
vmaps directory located in ./data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: 2024_10_19_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules are enabled
AC>
