### ISSUE TITLE
[BUG] Memory Leak !?

### ISSUE THREAD

**Issue by WarCrafte** [azerothcore/azerothcore-wotlk#2025]
SMALL DESCRIPTION: Total Ram is 8G and after 6 or 10 hours High consumption by server, 10x online player start server wait 6-10 hours,  server will to lag and closed "Crash Memory" !

Result:
Server uses a lot of memory, Per hour

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/9f3c0267bcb738a274e5f9eed90ce4bd568a3489

MODULES:
mod-npc-beastmaster
mod-vas-autobalance

In the new updates This problem has come about.

**Comment by poszer** [comment]
Include your crash log Hiroshi

**Comment by WarCrafte** [comment]
@poszer I did not catch, you mean

Similar: 
https://github.com/azerothcore/azerothcore-wotlk/issues/1887

https://github.com/azerothcore/azerothcore-wotlk/issues/1525

https://github.com/azerothcore/azerothcore-wotlk/issues/784

https://github.com/azerothcore/azerothcore-wotlk/issues/508

https://github.com/azerothcore/azerothcore-wotlk/issues/782

https://github.com/azerothcore/azerothcore-wotlk/issues/665


Does not exist "crash log" just memory error and locked, the system needs to be restarted!

**Comment by poszer** [comment]
If it's like you said a memory leak, then it will run out of memory and it will crash server (Also there must be crash log). Also reporting it without any informations is kinda weird. What i can see from this post ? Nothing dude. I can't reporoduce nothing, i don't know how you recognize that ''memory leak''. 
When you decide to setup server, you have option to build it on debug. Every owner should do that, and take a look on the memory usage. Maybe to try research from where it comes, what's causing too much usage. I'm sorry, but i can't reproduce it without any information, where to check ? What to do ? Tell me, and i'll do. 
Also, read this http://www.azerothcore.org/wiki/FAQ

**Comment by WarCrafte** [comment]
Crash log does not give, but memory locked Due to usage High consumption by memory and system needs to be restarted!

**Comment by poszer** [comment]
> Crash log does not give, but memory locked Due to usage High consumption by memory and system needs to be restarted!

> **where to check ? What to do ? Tell me, and i'll do.**

**Comment by WarCrafte** [comment]
I think this bug is for character moves in the maps, but I'm not "member" or "Contributor" for fix the problem!

Dear, This problem is not in version https://github.com/azerothcore/azerothcore-wotlk/releases/tag/v1.0.4 !

The problem has been created the version https://github.com/azerothcore/azerothcore-wotlk/releases/tag/v2.0.0 and after that.......

I think sabotage done in the project

**Comment by poszer** [comment]
> I think this bug is for character moves in the maps, but I'm not "member" or "Contributor" for fix the problem!
> 
> Dear, This problem is not in version https://github.com/azerothcore/azerothcore-wotlk/releases/tag/v1.0.4 !
> 
> The problem has been created the version https://github.com/azerothcore/azerothcore-wotlk/releases/tag/v2.0.0 and after that.......
> 
> I think sabotage done in the project

You are user and you should report it correctly. There is XXXX fixed issues who are correctly reported, explained, included a lot informations and it was easy for us to reproduce it. For this issue, there is some issues opened, but none of you didn't give a try to give us a one little tip where we should check about it, hoooooow to reproduce, right? Right. 
So tell me now, how we can fix something when there is no informations about it?
No details, informations, no crash log... Nothing, just text (Memory leak). 
Be realistic, and set yourself in our position and i'll ask you now a one simple question. 
How something can be fixed if we can't reproduce it?

**Comment by WarCrafte** [comment]
Now everyone has this problem and report and more reports will be sent, the problem is very complicated.

I may be back to this version:
https://github.com/azerothcore/azerothcore-wotlk/releases/tag/v1.0.4

I just know that this malicious problem has been created the in version v2.0.0 and later...
I understand you !

**Comment by Winfidonarleyan** [comment]
Да сука, сколько можно плодить это, одно и тоже, без единого сука пруфа, пиздец бесит

**Comment by Viste** [comment]
В голове твоей меморилик долбаеб сука

**Comment by fmrmx** [comment]
> Да сука, сколько можно плодить это, одно и тоже, без единого сука пруфа, пиздец бесит.

это все что ты хочешь сказать? nice devs

**Comment by WarCrafte** [comment]
That's why the problem is added....
This is normal, Because you are russian, dev!

This is all the problem and you will not attempt to fix it

I'm sorry for you, Smile now!

@Winfidonarleyan
@Viste

**Comment by milestorme** [comment]
Id10t user error

**Comment by poszer** [comment]
Will be checked tonight

**Comment by Stoabrogga** [comment]
see https://github.com/azerothcore/azerothcore-wotlk/issues/508#issuecomment-507162871
