### ISSUE TITLE
`.tele` parsing 

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20269]
### Current Behaviour

The parsing of `.tele` doesn't take in count any special characthers.

### Expected Blizzlike Behaviour

I would pressume that it would read both of them. `Pot'ato` and `Potato` as valid options.

### Source

None

### Steps to reproduce the problem

- `.tele zuldrak`
- "Teleport location 'zuldrak' doesn't exist."
- `.tele zul'drak`
- Works fine.

This applies for `Zul'Drak`, `Taunka'leVillage` and `Unu'pe`

### Extra Notes

Note: Do not use this PR otherwise this issue doesn't happen as I've fixed it here. https://github.com/azerothcore/azerothcore-wotlk/pull/20265

### AC rev. hash/commit

AzerothCore rev. faea1c0735f1 2024-10-15 11:15:31 +0100 (master branch) (Win64, RelWithDebInfo, Static)
```
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 5 hour(s) 47 minute(s) 17 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 5ms, 5ms
Using SSL version: OpenSSL 3.1.5 30 Jan 2024 (library: OpenSSL 3.1.5 30 Jan 2024)
Using Boost version: 1.81.0
Using CMake version: 3.29.3
Using MySQL version: 80036
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: 2024_10_21_03.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules are enabled
```

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by TheSCREWEDSoftware** [comment]
Video [here](https://www.youtube.com/watch?v=Gy0tuSSCh1Q&feature=youtu.be)

**Comment by Kitzunu** [comment]
Well because there isn't a teleport named `ZulDrak` in the database, hence why it fails. 
![image](https://github.com/user-attachments/assets/b798aea4-1eba-4266-9954-d1e399550009)

**Comment by TheSCREWEDSoftware** [comment]
> I would pressume that it would read both of them. Pot'ato and Potato as valid options.

Therefor i made it issue

**Comment by Kitzunu** [comment]
We shouldnt make it ambiguous. It should respect how it is entered in the db

**Comment by TheSCREWEDSoftware** [comment]
I made both this issues I was working in adding the missing teles for wotlk and fixing the names to have a standard written. 

https://github.com/azerothcore/azerothcore-wotlk/pull/20265/files
