### ISSUE TITLE
[Class - Warrior] - Character Locked in Berserker Stance

### ISSUE THREAD

**Issue by Badgermilk0** [azerothcore/azerothcore-wotlk#20266]
### Current Behaviour

Warrior locked in Berserker Stance.

All buttons highlighted, nothing happens when clicking on any stances.

Tried to;
restart server, kill character, offline over night, joining BG / Instance, chaning talent spec.
Cleared client Cache, removed addons etc.

Don't know how it happened other then it occurred after joining a dungeon through the dungeon finder. 

![image](https://github.com/user-attachments/assets/0a30b4b5-5b45-4c3c-8c2d-858346fce77e)

### Expected Blizzlike Behaviour

Not being locked in a warrior stance.

### Steps to reproduce the problem

Don't know how this happend, cannot reliably reproduce..

### AC rev. hash/commit

AzerothCore rev. 5d129e6dc43a 2024-10-19 11:40:13 +0700 (npcbots_3.3.5 branch) (Win64, RelWithDebInfo, Static)

### Operating system

Win11

### Custom changes or Modules

List of enabled modules:
|- mod-ah-bot
|- mod-autobalance
|- mod-challenge-modes
|- mod-individual-progression
|- mod-individual-xp
|- mod-pvp-titles
|- mod-reagent-bank
|- mod-transmog

**Comment by heyitsbench** [comment]
Resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/034ebb3cdd34e86764d66570f2da3194f080ad61, update your core.
