### ISSUE TITLE
`.tele add` - "Already Exists"

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20268]
### Current Behaviour

When trying to create a new teleport (that doesn't exist) but if the word during parsing finds a partial match it will tell you that already exists.

### Expected Blizzlike Behaviour

That are you're expect to create any new teleport that doesn't have an exact match.

### Source

None

### Steps to reproduce the problem

- `.tele add Garm`
- _"Teleport location already exist!"_
- `.tele Garm`
- You will be taken to `Zangarmarsh`

This also happens with others that now in my head I can't think off.

### Extra Notes

The workaround from my side was to temporarly change in the DB`Zangarmarsh` to something else like `ZangaTADrmarsh` and `.reload all` and now you will be able to add `Garm` and go back to DB and change it back to `Zangarmarsh`. And if i - `.tele Garm` it takes to me `Garm`

Note: Do not use this PR otherwise this issue doesn't happen as I've fixed it here. https://github.com/azerothcore/azerothcore-wotlk/pull/20265

### AC rev. hash/commit

AzerothCore rev. faea1c0735f1 2024-10-15 11:15:31 +0100 (master branch) (Win64, RelWithDebInfo, Static)
```
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 5 hour(s) 47 minute(s) 17 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 5ms, 5ms
Using SSL version: OpenSSL 3.1.5 30 Jan 2024 (library: OpenSSL 3.1.5 30 Jan 2024)
Using Boost version: 1.81.0
Using CMake version: 3.29.3
Using MySQL version: 80036
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: 2024_10_21_03.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules are enabled
```

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by TheSCREWEDSoftware** [comment]
Video [here](https://www.youtube.com/watch?v=5DTKI-BH7E4&feature=youtu.be)

Note: I added a another tp called "tsg" just so i could go back.

**Comment by Kitzunu** [comment]
![image](https://github.com/user-attachments/assets/4054e55f-2426-4a2f-a51b-a3ead67ed74b)
![image](https://github.com/user-attachments/assets/fa399d01-0322-4383-81e4-72d6cbe5b4cd)

Can't reproduce. Get teleported to garm with it

**Comment by TheSCREWEDSoftware** [comment]
>Note: Do not use this PR otherwise this issue doesn't happen as I've fixed it here. https://github.com/azerothcore/azerothcore-wotlk/pull/20265

While is not reprodusable now since i've added the teleporters to wotlk and to add "Garm" as example I had to temporarly change the name of Zangarmash to something else, otherwise wouldn't let me create the teleport in the first place

**Comment by Kitzunu** [comment]
You make no sense man. The issue doesnt exist because you presumably fixed it, hence why we cant reproduce it. So what is the issue? Why do we have an open issue for a fixed problem?

**Comment by TheSCREWEDSoftware** [comment]
Do this.

- Go to your database in world `SELECT * FROM game_tele WHERE ID = 1659`
- Change `Garm` to `GaDAKrm`
- Go in-game `.reload all` if the server is running.
- `.tele add Garm`
- It already exists! (because not of Garm but because of `Zangarmarsh`)
- `.tele garm`
- You've achieve the original issue mentioned here.
Is about the command parsing not the game_tele command name

**Comment by Kitzunu** [comment]
aight, now I understand. thank
