### ISSUE TITLE
[Black Temple - Illidan] Boss doesn't respawn in his position.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20260]
### Current Behaviour

Sometimes, after a reset, Illidan doesn't respawn at his usual spawn point.
It seems that he respawn at the same point when he lands at the end of Flames of Azzinoth phase.

### Expected Blizzlike Behaviour

Illidan should always respawn at his spawn point.

### Source

Official Servers.

### Steps to reproduce the problem

1. Fight Illidan and die.
2. Restart the fight.
3. Repeat point 1 and 2 until Illidan respawn in the wrong place.

### AC rev. hash/commit

[860b881](https://github.com/azerothcore/azerothcore-wotlk/commit/860b881ca0844ec9d56430cd6027d118c8bea7ca)

### Operating system

Windows 11

**Comment by Nyeriah** [comment]
Is there more to this? Like do we know about a specific phase or something? This was supposed to have been fixed

**Comment by Rorschach91** [comment]
Maybe if the raid wipe during the Flames of Azzinoth phase.

![Desktop Screenshot 2024 10 22 - 10 27 39 35](https://github.com/user-attachments/assets/e64ccd8f-b1c0-469a-aba7-49b00e2d428c)
