### ISSUE TITLE
[MAP] Gnome & Mechanostrider

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20275]
### Current Behaviour

Gnomes get dismount in certain zones in Stormwind while on Mechanostrider mount, looks like ground is not detected

https://github.com/user-attachments/assets/0840ab7c-2e14-4868-9e9d-b980aa6524e9

### Expected Blizzlike Behaviour

Don't blame gnomes

### Steps to reproduce the problem

Walk around stormwind with gnome on mechanostrider

### AC rev. hash/commit

rev. bb40bf772701

### Operating system

Debian 12

**Comment by heyitsbench** [comment]
Cannot reproduce this on 87aeaf10fdcc74caf1b5986bc988ee21a966ac41.

**Comment by manstfu** [comment]
Yea can't reproduce it also, maybe client related..
