### ISSUE TITLE
[Black Temple] Illidan does not repeat demon phase

### ISSUE THREAD

**Issue by Tereneckla** [azerothcore/azerothcore-wotlk#20284]
### Current Behaviour

Illidan only performs the first demon phase. Next occurrence merely is a threat reset

Transition from demon phase:
https://www.twitch.tv/videos/2283095282?t=00h15m30s

Threat reset
https://www.twitch.tv/videos/2283095282?t=00h16m30s

### Expected Blizzlike Behaviour

Demon Phases happen

### Steps to reproduce the problem

Fight Illidan until you hit p3
Wait for phase changes

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8852c38cd465edc9bc92d8f78436a53304b2fdf0

### Operating system

Ubuntu 24.04

**Comment by Rorschach91** [comment]
Yes I can confirm it. I noticed the issue half an hour ago while I was testing a PR.

**Comment by Nyeriah** [comment]
the event that returns him to normal form after demon phase keeps repeating itself so whenever it happens it resets his timers, this keeps on repeating so at some point it gets delayed indefinitely

![image](https://github.com/user-attachments/assets/dfe0769f-b1fa-4a06-b70b-b4d15cf8e90f)
