### ISSUE TITLE
[QUEST] Torture the Torturer

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#203]
**Description**: In this quest i have to hit a prisoner 5 times with High Executor's Branding Iron
http://www.wowhead.com/npc=27209/torturer-lecraft
http://www.wowhead.com/quest=12252/torture-the-torturer
http://www.wowhead.com/item=37314/high-executors-branding-iron

**Current behaviour**: I hit 5 times the NPC but nothing happen. Then if i press anythings key the game crash

**Expected behaviour**: Description of the item: Brand Torturer LeCraft at least 5 times to extract all of the information from him.

**Steps to reproduce the problem**: Hit 5 times the prisoner

**Comment by starrheld** [comment]
> It's fully functional for me.

![IMG1](http://i.imgur.com/j7vzh73.jpg)
