### ISSUE TITLE
[NPC Trainer] [Core/DB] Weaponsmithing Trainer Imindril not opens gossip

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#20303]
### Current Behaviour

 Imindril does not respond to hovering and right-clicking
 
![изображение](https://github.com/user-attachments/assets/41cac317-2297-432a-8e48-f94b537e4a24)

### Expected Blizzlike Behaviour

Expected list of spells for learning:
![изображение](https://github.com/user-attachments/assets/c8eaffb8-8929-4555-8839-e1e6229878d1)
![изображение](https://github.com/user-attachments/assets/b5327a40-5bac-4508-b33b-1712368d4a5f)

### Source

wowcircle.net

### Steps to reproduce the problem

.go xyz 5905 676  643.5 571

place mouse over Imindril, right-click.

### AC rev. hash/commit

AzerothCore rev. 2ebbd5648857 2024-10-22 19:57:35 +0000

### Operating system

Windows

### Custom changes or Modules

none

**Comment by TheSCREWEDSoftware** [comment]
![image](https://github.com/user-attachments/assets/356b1ab2-c0b5-4f9b-8c04-a6f183d1ef1b)

Confirmed from Cata classic.
