### ISSUE TITLE
[ZulAman]: Boss Jan'alai use wrong timesheet hatch all eggs, also will be interrupted when just run next ScheduleTimedEvent

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#20314]
### Current Behaviour

now will after 25% even, then hatch all eggs even. 
normal will do 35% even hatch all eggs first, then do 25% even.
might need change ScheduleHealthCheckEvent by descending order HP% just link this. 
        ScheduleHealthCheckEvent(35, [&]{
            Talk(SAY_ALL_EGGS);
            me->AttackStop();
            me->GetMotionMaster()->Clear();
            me->SetPosition(janalainPos);
            me->StopMovingOnCurrentPos();
            DoCastSelf(SPELL_HATCH_ALL);
            HatchAllEggs(HATCH_ALL);
        });

        ScheduleHealthCheckEvent(25, [&]{
            DoCastSelf(SPELL_ENRAGE, true);
        });

and also all eggs even will do some active and cast spell, but when time to every next ScheduleTimedEvent, if ScheduleHealthCheckEvent(35)  not finished at all,  will stop the eggs hatch, all 30s, 10s, and 8s even will stop this 35% action. might  need pause other timeschedule first at even 35% and resume at end.

### Expected Blizzlike Behaviour

Will do as normal work.

### Steps to reproduce the problem

.go c 89322
see if:

fight below 35% will not hatch all eggs. till 25% the boss angry then will hatch all eggs. but if just at do a timeschedule or when hatching all eggs then to do another timeschedule, the hatching eggs will stoped.

replace order script 35% first and 25% after. will fix need first to 25%. but interrupt by timeschedule will still active.

### AC rev. hash/commit

AzerothCore rev. d9e277351989 2024-10-26 00:44:25 +0200 (HEAD branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 18 second(s)
Update time diff: 100ms. Last 112 diffs summary:
|- Mean: 100ms
|- Median: 100ms
|- Percentiles (95, 99, max): 101ms, 101ms, 149ms
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80403
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-2-pve
Worldserver listening connections on port %u
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: mod-zone-difficult.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-difficult
|- mod-eluna

### Operating system

Debian 12 with PVE

**Comment by kissingers** [comment]
test base on this pr
https://github.com/azerothcore/azerothcore-wotlk/pull/20195

**Comment by Nyeriah** [comment]
Rested after the latest PRs are merged.

**Comment by kissingers** [comment]
> Rested after the latest PRs are merged.

After PSs if HP% match just cast fire bomb, the the hit eggs will take later. but if match other event, still will stop hit eggs.
It seems hit eggs requires a duration, during which cast any other spelll actions will stop this action.

Also 35% do hit eggs not right, need change 35% event move up to the 25% event. otherwise the two event will action at almost same time.

**Comment by kissingers** [comment]
So is it possible to change to customspell mode and let the eggs hatch directly, or use other triggers to execute hatching eggs?

**Comment by Nyeriah** [comment]
I don’t understand what you are saying but bear in mind the PR that affects this has not been merged yet.

**Comment by kissingers** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/20496
I means after this PR, If boss do cast spell  a little good than before.
