### ISSUE TITLE
[Black Temple - Gurtogg Bloodboil] SPELL_BLOODBOIL 42005 should not appear in Phase 2

### ISSUE THREAD

**Issue by bluegene-ai** [azerothcore/azerothcore-wotlk#20327]
### Current Behaviour

Gurtogg Bloodboil casts the SPELL_FEL_RAGE to mark the battle to enter phase 2, and according to Blizzard's settings, phase 2 should not appear SPELL_BLOODBOIL. However, in the current version, Gurtogg Bloodboil will still cast SPELL_BLOODBOIL.

### Expected Blizzlike Behaviour

Gurtogg Bloodboil should not be cast SPELL_BLOODBOIL in Phase 2

### Source

![Uploading 20241028102531.png…]()
As you can see from the code, Gurtogg has been casting SPELL_BLOODBOIL for the entire duration of the battle, and the correct situation should be to determine if Skill 2 exists, then Skill 1 should not continue to be cast.

### Steps to reproduce the problem

1.Teleport to Gurtogg Bloodboil .
2. Start the battle and continue until Phase 2, then Gurtogg cast SPELL_FEL_RAGE.
3. He will continue to cast SPELL_BLOODBOIL(42005) in Phase 2.

### AC rev. hash/commit

30a790117be9+ 2024-08-23 06:38:00 +0200

### Operating system

Windows Server 2022 21H2

### Custom changes or Modules

mod-eluna
mod-transmog

**Comment by bluegene-ai** [comment]
[
![20241028102531](https://github.com/user-attachments/assets/f2e36ef0-6bfe-48d0-8c5f-4e057f070d38)
](url)

**Comment by heyitsbench** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp#L86

It checks if Gurtogg has the Fel Rage aura, marking phase 2. Update your core.
