### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by blinkysc** [azerothcore/azerothcore-wotlk#20322]
### Current Behaviour

Clients crash as well as server crashes while playing with segmentation fault and no additional errors in error.log

### Expected Blizzlike Behaviour

No crashes

### Steps to reproduce the problem

Step 1. Pull many mobs at once in client
Step 2. It might crash all clients connected or server segmentation fault and server shuts down

### AC rev. hash/commit

2ce2c8cf3a8a

### Operating system

Debien 12.7

**Comment by blinkysc** [comment]
Tested on another fresh server, still segmentation fault happens. Set characters to level 15 and ran a dungeon with 2 players, after pulling many mobs clients crashed. Was able to get back in but then full segmentation fault with server crash

**Comment by Grimdhex** [comment]
Play in debug mode and send us the craslogs. We can't do anything without.

**Comment by TheSCREWEDSoftware** [comment]
Aside from having the debug information. Can you tell us how to reproduce this issue?

Where you've done this, I understand while you pulling as many mobs, but I dont understand where. Than you mentioned a dungeon run.

Be more specific so we can look at it and attempt to reproduce your issue.

**Comment by blinkysc** [comment]
Been trying to run it all morning to reproduce it myself in debug mode, but couldn't get it to do it again. It was at level 16 for each player, 2 druids, 1 heal 1 tank in The Deadmines. It seemed to happen when pulling 10+ mobs at once with mod-autobalance and when spamming swipe while jumping and constant turning. Feel it is maybe limited to this dungeon because initially I was able to reproduce it between two seperate systems (one being a fresh built server). Both systems set for 2 cores and 4GB ram so don't think some sort of resource issue.

**Comment by TheSCREWEDSoftware** [comment]
Have you been able to reproduce this issue?

**Comment by blinkysc** [comment]
No I haven’t, I have since removed the mod-autobalance though; perhaps it had to do with that?

**Comment by TheSCREWEDSoftware** [comment]
I will be closing this, but i would suggest you to make an issue, where you can mentioned this or give your insight of the crash in the module's page.
