### ISSUE TITLE
[Quest]For Great Honor - can't complete quest

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2032]
[Quest]For Great Honor - Can't turn in

##### SMALL DESCRIPTION:

I have completed requirements needed for '[Quest]For Great Honor' It won't let me complete quest

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should let me complete the quest

##### CURRENT BEHAVIOUR:

[Quest]For Great Honor - Can't complete the quest
![greathonor](https://user-images.githubusercontent.com/18629476/60416286-05123580-9c10-11e9-8857-79090c534c6a.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do some battlegrounds and get the needed items for [Quest]For Great Honor
2.  Talk to NPC and try to turn in the quest

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

031e0ae

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Done, when you are available please test the referenced PR. Thanks :+1: @spinzaku
