### ISSUE TITLE
[Hellfire Peninsula] Fel Canon MKI move from their spawn point.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20326]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7445#issue-2610206014

If players are targetted from Fel Canons MKI and they go away from their line of sight, Cannons teleport them near the player position.

Evidence: [Youtube](https://youtu.be/OHsWnUX8vB4)

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

61-64

### Current Behaviour

Fel Canon MKI in the areas around Thrallmar will teleport to you if you line of sight them.

### Expected Blizzlike Behaviour

Presumably, the canons should be unable to move from their position. At the very least, I do not recall them ever doing so.

### Source

![2024-10-23_18-43-40](https://github.com/user-attachments/assets/88fec3da-6aab-483e-b801-50d4c9d196d5)

### Steps to reproduce the problem

1. Aggro one of the Fel Canons in the area closest to Thrallmar
2. Move behind the structure in the center

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/572be7d69f8b9a0100d95ecaa045247e574c38a4

### Operating system

Gentoo

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by cgrahamseven** [comment]
Here is a potential fix for this issue that doesn't involve changing the unit flags. It involves adding a new CastFlags value for the smart ai. If you apply the fix in the core and then modify the Fel Cannon entry in the smart_scripts table for 'In Combat - Cast Fel Cannon Blast' by ORing the current CastFlags with the new value, it will prevent the AI from being set to move after the failed cast from LOS or range. 

```
--- a/src/server/game/AI/SmartScripts/SmartScript.cpp
+++ b/src/server/game/AI/SmartScripts/SmartScript.cpp
@@ -691,6 +691,8 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
                     // To prevent running back and forth when OOM, we must have more than 10% mana.
                     bool canCastSpell = me->GetPowerPct(POWER_MANA) > 10.0f && spellInfo->CalcPowerCost(me, spellInfo->GetSchoolMask()) < (int32)me->GetPower(POWER_MANA) && !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED);
                     bool isSpellIgnoreLOS = spellInfo->HasAttribute(SPELL_ATTR2_IGNORE_LINE_OF_SIGHT);
+                    // If caster must remain stationary and shouldn't chase target
+                    bool canMove = (e.action.cast.castFlags & SMARTCAST_COMBAT_CANNOT_MOVE) != SMARTCAST_COMBAT_CANNOT_MOVE;

                     // If target is rooted we move out of melee range before casting, but not further than spell max range.
                     if (isWithinLOSInMap && isWithinMeleeRange && isRangedAttack && isTargetRooted && canCastSpell && !me->IsVehicle())
@@ -705,13 +707,15 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
                     if (distanceToTarget > spellMaxRange && isWithinLOSInMap)
                     {
                         failedSpellCast = true;
-                        CAST_AI(SmartAI, me->AI())->SetCombatMove(true, std::max(spellMaxRange - NOMINAL_MELEE_RANGE, 0.0f));
+                        if(canMove)
+                            CAST_AI(SmartAI, me->AI())->SetCombatMove(true, std::max(spellMaxRange - NOMINAL_MELEE_RANGE, 0.0f));
                         continue;
                     }
                     else if (distanceToTarget < spellMinRange || !(isWithinLOSInMap || isSpellIgnoreLOS))
                     {
                         failedSpellCast = true;
-                        CAST_AI(SmartAI, me->AI())->SetCombatMove(true);
+                        if(canMove)
+                            CAST_AI(SmartAI, me->AI())->SetCombatMove(true);
                         continue;
                     }
```
```
--- a/src/server/game/AI/SmartScripts/SmartScriptMgr.h
+++ b/src/server/game/AI/SmartScripts/SmartScriptMgr.h
@@ -1916,7 +1916,8 @@ enum SmartCastFlags
     SMARTCAST_AURA_NOT_PRESENT       = 0x020,                     // Only casts the spell if the target does not have an aura from the spell
     SMARTCAST_COMBAT_MOVE            = 0x040,                     // Prevents combat movement if cast successful. Allows movement on range, OOM, LOS
     SMARTCAST_THREATLIST_NOT_SINGLE  = 0x080,                     // Only cast if the source's threatlist is higher than one. This includes pets (see Skeram's True Fulfillment)
-    SMARTCAST_TARGET_POWER_MANA      = 0x100                      // Only cast if the target has power type mana (e.g. Mana Drain)
+    SMARTCAST_TARGET_POWER_MANA      = 0x100,                      // Only cast if the target has power type mana (e.g. Mana Drain)
+    SMARTCAST_COMBAT_CANNOT_MOVE     = 0x200                        // Caster can only cast and cannot move at all in combat. No movement on range, OOM, LOS
 };

 enum SmartFollowType

```

I only tested this with the Fel Cannon MKI, not with other mobs that should cast and then follow if out of range or LOS. So need full testing to ensure that it doesn't cause any issues.
