### ISSUE TITLE
[Quel'Danas Isle] Abyssal Flamewalkers don't use Immolation ability.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20345]
### Current Behaviour

Abyssal Flamewalkers don't use Immolation ability.

### Expected Blizzlike Behaviour

Abyssal Flamewalkers should cast Immolation on theirselves, causing aoe damage to all players near them.

### Source

Official Servers

### Steps to reproduce the problem

1. Go to Quel'Danas Isle
2. Fight Abyssal Flamewalkers

### AC rev. hash/commit

[07a6327](https://github.com/azerothcore/azerothcore-wotlk/commit/07a6327c8c2d08d44710ec00931d0a8420621465)

### Operating system

Windows 11

**Comment by IntelligentQuantum** [comment]
@Rorschach91 https://www.wowhead.com/wotlk/npc=25001/abyssal-flamewalker#abilities it does not have Immolation

**Comment by Rorschach91** [comment]
> @Rorschach91 https://www.wowhead.com/wotlk/npc=25001/abyssal-flamewalker#abilities it does not have Immolation

I've checked this mob in wow cata classic ptr and it have this ability. 
Maybe blizzard added immolation during cataclysm expansion, but it looks strange.

**Comment by IntelligentQuantum** [comment]
> > @Rorschach91 https://www.wowhead.com/wotlk/npc=25001/abyssal-flamewalker#abilities it does not have Immolation
> 
> I've checked this mob in wow cata classic ptr and it have this ability. Maybe blizzard added immolation during cataclysm expansion, but it looks strange.

do you have correct spell id

**Comment by avarishd** [comment]
spell 12743 does not exist in wotlk dbc

**Comment by Rorschach91** [comment]
Cata Classic PTR servers are off-line. I can only check it on TWW PTR right now. 
I'm going to check.
