### ISSUE TITLE
[Quel'Danas Isle] Dawnblabe Summoners fight at melee range.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20342]
### Current Behaviour

Dawnblabe Summoners fight at melee range when they enter in combat.

### Expected Blizzlike Behaviour

They are casters, so they should fight from the distance until they finish the mana.

### Source

Official Servers

### Steps to reproduce the problem

1. Go to Quel'Danas Isle
2. Fight Dawnblabe Summoners

### AC rev. hash/commit

[07a6327](https://github.com/azerothcore/azerothcore-wotlk/commit/07a6327c8c2d08d44710ec00931d0a8420621465)

### Operating system

Windows 11

**Comment by IntelligentQuantum** [comment]
@Rorschach91 https://www.wowhead.com/wotlk/npc=24978/dawnblade-summoner#abilities;mode:n25

it does not have 'Incinerate' or Summon Imp
So should she only cast Immolate? And when her mana runs out, should he attack up close?

**Comment by Rorschach91** [comment]
> @Rorschach91 https://www.wowhead.com/wotlk/npc=24978/dawnblade-summoner#abilities;mode:n25
> 
> it does not have 'Incinerate' or Summon Imp So should she only cast Immolate? And when her mana runs out, should he attack up close?


Be carefull when you use WoWHead, because it is not 100% reliable.

As far as I remember (when I tried two weeks ago on official server) Dawnblabe Summoners on AC use correct abilities (offy-like).

The only problem is that they go in melee range.

**Comment by IntelligentQuantum** [comment]
> > @Rorschach91 https://www.wowhead.com/wotlk/npc=24978/dawnblade-summoner#abilities;mode:n25
> > it does not have 'Incinerate' or Summon Imp So should she only cast Immolate? And when her mana runs out, should he attack up close?
> 
> Be carefull when you use WoWHead, because it is not 100% reliable.
> 
> As far as I remember (when I tried two weeks ago on official server) Dawnblabe Summoners on AC use correct abilities (offy-like).
> 
> The only problem is that they go in melee range.

Is there any source?

**Comment by Rorschach91** [comment]
The only source that I have is how this npc works when I checked on the official servers (cata ptr).
Unfortunally Cata PTR servers are off-line now, so I cannot create a video that shows it.
