### ISSUE TITLE
[HUNTER] Ghost Wolf

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20346]
### Current Behaviour

These NPC should not be tamable, not sure if they can be found in world, or can be only spawned by GM, but they should not be tamable!

https://www.wowhead.com/wotlk/npc=24133
https://www.wowhead.com/wotlk/npc=5596

![image](https://github.com/user-attachments/assets/d99cd6bf-45a2-4ff5-aeda-c4ec6374c68b)

### Expected Blizzlike Behaviour

Not tamable

### Steps to reproduce the problem

.npc add temp 24133
.npc add temp 5596
.pet create

### Extra Notes

Possible fix:
```
UPDATE creature_template SET type_flag = 1024 WHERE entry = 24133;
UPDATE creature_template SET type_flag = 0 WHERE entry = 5596;
```

### AC rev. hash/commit

rev. bed3e1d407d9+

### Operating system

Debian 12

**Comment by TheSCREWEDSoftware** [comment]
In AC: AzerothCore rev. faea1c0735f1 2024-10-15 11:15:31 +0100 (master branch) (Win64, RelWithDebInfo, Static)

I can't tame either `Ancient Grimtotem Spirit Guide` (24133) and `Grimtotem Spirit Wolf` (26111).

<details>
<summary>Post and Screenshot of wowhead</summary>

[Post](https://www.wowhead.com/tbc/npc=24133/ancient-grimtotem-spirit-guide#comments)


![image](https://github.com/user-attachments/assets/228682a2-7abd-4d24-a5ed-005f5fab9c5f)

</details>

If I spawn 26111 via the spell 43110 `Summon Spirit Wolf` it will dispawn after a while, don't know the criteria, has to do with the Grimtotem npc probably. But even here that one can't be spawned.

<details>
<summary>Post and Screenshot of wowhead</summary>

[Post](https://www.wowhead.com/wotlk/npc=26111/grimtotem-spirit-wolf#comment)

![image](https://github.com/user-attachments/assets/48ddb9ed-2c0e-4b64-95d1-846278c5985c)

</details>

If both spawn temp, they stay both and none can be tamed. Only the 26111 gives a message of not tamable the other just casts and doesn't let you channel. So adding the change to Spirit Guide to not tamable should just prevent someone somehow taming it.

**Comment by TheSCREWEDSoftware** [comment]
I wouldn't change the NPC 5596 `Twain Test Prop` as it a test npc. 

```sql
UPDATE `creature_template` SET `type_flags` = 1024 WHERE `entry` = 24133 AND `type_flags` = 1025;
```

Tested and you can make a PR or I can do it is indifferent

**Comment by manstfu** [comment]
Thats the problem [24133](https://www.wowhead.com/wotlk/npc=24133) cannot be found in world, so should we consider it as test npc?

**Comment by heyitsbench** [comment]
Change the Spirit Guide, not the Test Prop. There's no evidence that the Test Prop *isn't* tamable, whereas there is for the Spirit Guide.

**Comment by manstfu** [comment]
Flags get sent in sniffs, turns out this is not correct. Looks like the Wowhead posts/comments may have been referring to the creature swap resulting in the creature becoming untamable, not this creature itself having its tamability removed.

**Comment by manstfu** [comment]
Flags get sent in sniffs, turns out this is not correct. Looks like the Wowhead posts/comments may have been referring to the creature swap resulting in the creature becoming untamable, not this creature itself having its tamability removed.
