### ISSUE TITLE
[Raid]Ulduar - Razorscale Boss Encounter - Razorscale Devouring Flame Stalker(Infernal-trigger) not hidden

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2035]
[Raid]Ulduar - Razorscale Boss Encounter - Razorscale Devouring Flame Stalker(Infernal-trigger) not hidden

##### SMALL DESCRIPTION:

Players can see Razorscale Devouring Flame Stalker Trigger (should be hidden) When they encounter Razorscale

##### EXPECTED BLIZZLIKE BEHAVIOUR:

 Razorscale Devouring Flame Stalker (Infernal) shouldn't been seen by players

##### CURRENT BEHAVIOUR:

Players can see Razorscale Devouring Flame Stalker Trigger (should be hidden) When they encounter Razorscale

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Do ulduar raid
2.  Start Razorscale encounter
![hidden](https://user-images.githubusercontent.com/18629476/60437911-f04e9580-9c41-11e9-902d-1f75dc698fac.png)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

031e0ae

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Also i just checked on master, Razorscale Devouring Flame Stalker (Entry: 34188) already using correct flags_extra set to 130 (Invisible to players). Tested with player account, i can't see it without .gm on option.
But other creature, near him Razorscale Harpoon Fire State used incorrect flags_extra. It's updated now, and ready for test @spinzaku
