### ISSUE TITLE
[Quel'Danas Isle] Some Shattered Sun Marksman attack the player also if they aren't in combat. 

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20354]
### Current Behaviour

Shattered Sun Marksman that do target practice hit the players who get too close to them without entering combat.

Evidence: [Youtube](https://youtu.be/KlizSnnQ64Y)

### Expected Blizzlike Behaviour

They should hit players in that way.

### Source

Official Servers

### Steps to reproduce the problem

1. Go to Quel'Danas Isle
2. Go near Shattered Sun Marksman that do target practice

### Extra Notes

Issue probably related to the smartai:
![smartai](https://github.com/user-attachments/assets/9ef1c110-6ffe-4d51-af60-25162ff49a26)

### AC rev. hash/commit

[752c687](https://github.com/azerothcore/azerothcore-wotlk/commit/752c6875b5240e7ac31d752806c00b3e54a96ad0)

### Operating system

Windows 11

**Comment by heyitsbench** [comment]
[Dawnblade Marksman](https://wowgaming.altervista.org/aowow/?npc=24979)* for the record.
