### ISSUE TITLE
[Sunwell Plateau] First Blood Elf packs are not linked properly.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20361]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7465#issue-2621443008

Both packs are not linked properly.

![Desktop Screenshot 2024 10 30 - 17 59 36 71](https://github.com/user-attachments/assets/47451df0-3c42-482f-b6ac-3c8d27e26107)

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Only half of the pack pulls

https://github.com/user-attachments/assets/d25d15de-e6da-456a-9f86-91ec324a3a04

### Expected Blizzlike Behaviour

The whole pack should be linked

### Source

https://youtu.be/-jbuSxeXYzQ?t=65

### Steps to reproduce the problem

1. Pull the rightern most mob of the pack

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/4b59c867e141cf210c654b05fdddb3c12f7e7ea2

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
I was trying to look into this and made my questions and what have 'figured out' so far. in Discord [here](https://discord.com/channels/217589275766685707/689803159086170250/1301373873303851009)

But when i compare all the existing GUIDs to Formation GUIDS (leader or member) in the map 580 (sunwell) I dont find any. So i pressume this aggro happening is social aggro between the mobs. I just need some more inside into to this to confirm what i've been trying to figure out. If there is indeed no formations made for sunwell, Which if is the case I think from there i can orient myself to create the said formations.
