### ISSUE TITLE
fatal error during install; "mysql_ssl_mode; did you mean mysql_ssl_set?"

### ISSUE THREAD

**Issue by spacefox-platforms** [azerothcore/azerothcore-wotlk#20373]
### Current Behaviour

when attempting to update the server per the [wiki](https://www.azerothcore.org/wiki/linux-keeping-the-server-up-to-date), i run into this [error](https://gist.github.com/spacefox-platforms/e380595073880c4f6a4775c435320242)

i'm assuming this might have to do with the version of mariadb i'm using?
[mariadb installed on server](https://gist.github.com/spacefox-platforms/6aab7034bf01aa718d01546f2c6edaf4)

### Expected Blizzlike Behaviour

update/install should succeed

### Steps to reproduce the problem

attempt to update server per the wiki

### AC rev. hash/commit

unable to, server is out of date and won't run

### Operating system

debian 12

### Custom changes or Modules

mod-ah-bot

**Comment by Nyeriah** [comment]
MariaDB is not supported

**Comment by spacefox-platforms** [comment]
> MariaDB is not supported. You can’t compile with MariaDB.

ahhh, i didnt notice the banner on the wiki. that explains a lot. thanks!
will go ahead and close this
