### ISSUE TITLE
[Quest] [A Suitable Disguise]

### ISSUE THREAD

**Issue by DARKENE** [azerothcore/azerothcore-wotlk#2038]
SMALL DESCRIPTION: Quest Buged, these sunfury or summoners, the azaloth attacking you to which is wrong!

1. Quest 10688 and quest 10637!
2. Try to attack summoners sunfury!
3. The azaloth will attack you too when you get near him which is wrong!
4. Also the visaul on on him is wrong while banished!
5. After using the scoll on him, the look is same which is wrong!

If can't to compelete this quest, other quest not done! (Important)

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/ea2ecdbcc8eb2c47d420d0fb29dcb04897228d84

OPERATING SYSTEM:
Windows Server 2016 Server

MODULES:
mod-npc-beastmaster
mod-vas-autobalance

**Comment by poszer** [comment]
A Suitable Disguise is quest with id : 24556 https://www.wowhead.com/quest=24556/a-suitable-disguise
Also your reports are related to the quest A Necessary Distraction which is already opened.
https://github.com/azerothcore/azerothcore-wotlk/issues/1159
You just copy paste my text from reported issue. Closing this issue, it's duplicate.
