### ISSUE TITLE
[Quest] The Battle for Undercity [$15]

### ISSUE THREAD

**Issue by Gargarensis** [azerothcore/azerothcore-wotlk#204]
**Description**: Quest completely missing since there are no sniffs because the quest has been removed from retail.

**Current behaviour**: Simply, the script is missing

**Expected behaviour**: There are actually 2 quests, one for Alliance and one for Horde players.
Since describing the quests would take too long, I suggest to see this videos (one Alliance, one Horde)
https://www.youtube.com/watch?v=thvM9fd-pJA
https://www.youtube.com/watch?v=PxvQKCJagoI

**AC hash/commit**:  
3f25872719f7d81c3b8387a5e371a7944280af

**Operating system**:  Any

This quest is unfixable on Trinity Core, because there are no sniffs; we can start working on it together here anyway since this core accepts no-sniffs fixes.
##

**Comment by HeartWell** [comment]
https://github.com/TrinityCore/TrinityCore/pull/17954

**Comment by Gargarensis** [comment]
I've found this one too: https://github.com/TrinityCore/TrinityCore/commit/3002839bfec1c69e00a191d82e569b647cd4fdb8

**Comment by HeartWell** [comment]
Nice) I addthis)

**Comment by ShinDarth** [comment]
please open PR so it can be tested and then merged

**Comment by Gargarensis** [comment]
I think we need to adapt it, since it is for TrinityCore

**Comment by ShinDarth** [comment]
that's also what I meant with opening a PR 💃

**Comment by Krath** [comment]
https://github.com/TrinityCore/TrinityCore/commit/3002839bfec1c69e00a191d82e569b647cd4fdb8
That's not the Battle for Undercity script

**Comment by HeartWell** [comment]
You now.
[3.3.5] Core/Quest: A life without regret (#16067)

**Comment by Krath** [comment]
This is the script for the Battle for the Undercity quest : https://github.com/TrinityCore/TrinityCore/pull/17954

**Comment by sucofog** [comment]
Is this intended to work here in azerothcore or is it working right now?

**Comment by boom8866** [comment]
This is not in the 335 version of the content

**Comment by Irome** [comment]
Is there no one who wants to finish this?

**Comment by sucofog** [comment]
@Irome If we set a bounty maybe someone wants to

**Comment by pondaveia** [comment]
I'm currently working on a quest. After fixing it I'll pick this one up.

**Comment by BarbzYHOOL** [comment]
Related https://github.com/azerothcore/azerothcore-wotlk/issues/131

**Comment by gtao725** [comment]
I know this is an old existing issue but it seems people at dalaranwow(trinitycore based i think) has fixed this quest: https://github.com/dalaranwow/dalaran-wow/issues/2404
Any chance this will be fixed for AzerothCore? I mean this is an epic quest for wotlk which people created new chars just to repeatedly see the event.

**Comment by FrancescoBorzi** [comment]
@gtao725 

Yes there is a chance, we should import it from https://github.com/Falstring/Dalaran-Core

**Comment by poszer** [comment]
> I know this is an old existing issue but it seems people at dalaranwow(trinitycore based i think) has fixed this quest: [dalaranwow/dalaran-wow#2404](https://github.com/dalaranwow/dalaran-wow/issues/2404)
> Any chance this will be fixed for AzerothCore? I mean this is an epic quest for wotlk which people created new chars just to repeatedly see the event.

It will be fixed on AC soon

**Comment by gtao725** [comment]
Thx guys, this is awesome! Can't wait. Bless you all for all the hard work!

**Comment by BarbzYHOOL** [comment]
haha nice I had mentioned it too to two devs but i'm not alone

**Comment by Naxxramas-Server** [comment]
I'v add 15$ bounty on this

**Comment by BarbzYHOOL** [comment]
how to display the bounty automatically @FrancescoBorzi @Yehonal (offtopic but we will hide the messages afterwards)

**Comment by Yehonal** [comment]
should be fixed now

**Comment by Yehonal** [comment]
> how to display the bounty automatically @FrancescoBorzi @Yehonal (offtopic but we will hide the messages afterwards)

solved the bounty issue

**Comment by Rushor** [comment]
thanks for stealing lol

**Comment by FrancescoBorzi** [comment]
@Rushor stealing what exactly?

**Comment by Viste** [comment]
script base from Dalaran-WoW source code who posted on github under GPL 2.0 
https://github.com/Falstring/Dalaran-Core

**Comment by FrancescoBorzi** [comment]
Actually the real "stealing" is when you take a project like mangos/TC/AC and create your own **private** fork, violating the GPL license.

People are more than welcome to copy code from any GPL project and add them to their own, as long as they keep them open source.
