### ISSUE TITLE
TypeContainer.h include err 1696

### ISSUE THREAD

**Issue by leewheel** [azerothcore/azerothcore-wotlk#20402]
### Current Behaviour

![image](https://github.com/user-attachments/assets/f2e550af-aae3-4218-b2b1-2b017d6f38fa)

### Expected Blizzlike Behaviour

No

### Source

#include "Dynamic/TypeList.h"
#include "GridRefMgr.h"                    (X)
#include <unordered_map>

### Steps to reproduce the problem

just open TypeContainer.h

### AC rev. hash/commit

It does not affect compilation, but it looks uncomfortable

### Operating system

Windows 10

**Comment by Grimdhex** [comment]
Related to your custom change. We can't provide support for it.

**Comment by TheSCREWEDSoftware** [comment]
@leewheel you've to be more specific about the issues you report. 

I understand that you get compiler warnings. on `#include "GridRefMgr.h"` it's a suggestion you're attempt to provide here? so it gets removed or fix?

**Comment by Grimdhex** [comment]
I close this issue also (if not fixed, to be post on NPCbots repos)
