### ISSUE TITLE
RealmList.cpp 

### ISSUE THREAD

**Issue by leewheel** [azerothcore/azerothcore-wotlk#20425]
### Current Behaviour

Deleting the reference #include "IoContext.h" causes compilation failure 

### Expected Blizzlike Behaviour

None

### Source

#include "RealmList.h"
#include "DatabaseEnv.h"
#include "DeadlineTimer.h"
#include "IoContext.h"     //Must not delete it
#include "Log.h"
#include "Resolver.h"
#include "Util.h"
#include <boost/asio/ip/tcp.hpp>
#include <memory>

### Steps to reproduce the problem

Just compilation

### AC rev. hash/commit

No

### Operating system

Windows 10

**Comment by Grimdhex** [comment]
We will need more informations. What config do you use on Windows to get these fails ? Because I've no build issues on windows

**Comment by TheSCREWEDSoftware** [comment]
@leewheel are you able to provide the rev. that you're using?

**Comment by Grimdhex** [comment]
I close this issue also (if not fixed, to be post on NPCbots repos)
