### ISSUE TITLE
Aspect of the Viper does not work on General Vezax in Ulduar

### ISSUE THREAD

**Issue by Fot3k** [azerothcore/azerothcore-wotlk#2042]
**Aspect of the Viper does not work on General Vezax in Ulduar.**

##### SMALL DESCRIPTION:
Aspect of the Viper should restore mana while doing General Vezax in Ulduar but it does not. Trying to do hard mode is made extremely difficult with this bug.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Aspect of the Viper should restore mana against General Vezax.

##### CURRENT BEHAVIOUR:
Aspect of the viper does not restore mana against General Vezax.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Ulduar.
2. Fight General Vezax.
3. Run out of mana and switch to Aspect of the Viper.
4. Always out of mana with no way to restore it as a hunter.

##### EXTRA NOTES:
Shadow crashes don't seem to reduce mana cost. 

##### BRANCH(ES):
Master.

##### AC HASH/COMMIT:
[c82a422](https://github.com/azerothcore/azerothcore-wotlk/tree/c82a422c2cd20de1617332f2c04aef70aa80a300)

##### OPERATING SYSTEM:
Debian.

**Comment by solidmaxtor** [comment]
Mechanics is like that. No skill or potions are used to regenerate mana.
You only have to attack on the shadow areas that reduces the consumption of mana and increases your cele and sp.
Also break a saronita and stand on the saronite area, this regenerate mana but cause damage on players.

**Comment by Dreaxxx** [comment]
No solidmaxtor , i can confirm it , see https://www.wowhead.com/spell=62692/aura-of-despair#changelog

Aspect of the viper should world.

**Comment by Ka0tik** [comment]
It should work as suggested also by @Dreaxxx 

On Hard Mode you can't use the Saronite Vapor and from doing multiple runs on this boss the shadow crashes that generate the black pools for the buff don't seem to reduce mana cost either but not 100% on that.

**Comment by disclosurez** [comment]
can confirm here, players on my server also crying about it

**Comment by solidmaxtor** [comment]
On hard mode is not complicated kill this boss, Only players no casting out  shadow areas.
In Wowhead log i can read "its partialmente efective", how partial? 10% maybe, i not have idea really.
Work fine for me but i am not opousse for any ajustement if not use this skils to 100%

**Comment by disclosurez** [comment]
bump

**Comment by Ka0tik** [comment]
Still broken.
