### ISSUE TITLE
Script named 'spell_item_luffa' is not assigned in the database

### ISSUE THREAD

**Issue by Denza755** [azerothcore/azerothcore-wotlk#20454]
### Current Behaviour

Script named 'spell_item_luffa' is not assigned in the database

### Expected Blizzlike Behaviour

Script named 'spell_item_luffa' is not assigned in the database

### Source

Script named 'spell_item_luffa' is not assigned in the database

### Steps to reproduce the problem

Script named 'spell_item_luffa' is not assigned in the database

### Extra Notes

Script named 'spell_item_luffa' is not assigned in the database

### AC rev. hash/commit

Script named 'spell_item_luffa' is not assigned in the database

### Operating system

Windows 10

### Custom changes or Modules

Script named 'spell_item_luffa' is not assigned in the database

**Comment by Nyeriah** [comment]
Update your core

**Comment by Denza755** [comment]
hi
i already update core today
but these errors stil appear
what is the reason for these errors?

ср, 6 нояб. 2024 г. в 00:17, Andrew ***@***.***>:

**Comment by Nyeriah** [comment]
Type .server debug and post everything that shows here.
