### ISSUE TITLE
[DB/reference_loot_template] Loot error

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2045]
reference_loot_template entry 34215 refiere to Emalon in "Vault to Archavon" raid instance
This loot items 219/226 but one item 251is in reference (https://es.wowhead.com/item=40811)

Fix
```sql
DELETE FROM `reference_loot_template` WHERE  `Entry`=34215 AND `Item`=40811;
```

How reproduce
Tele Vault to Archavon
kill emalon
well loot its random for many items check id in DB its more fast  =)

BRANCH(ES):
master

AC HASH/COMMIT:
d8f14c9 and older

OPERATING SYSTEM:
ubuntu 16.04

MODULES:
No

**Comment by FrancescoBorzi** [comment]
@solidmaxtor please open a PR with the fix
