### ISSUE TITLE
cmake 编译错误

### ISSUE THREAD

**Issue by YangSimon** [azerothcore/azerothcore-wotlk#20476]
### Current Behaviour

严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY Crypto
  SSL) (found version "3.0.15")		C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake	230		

![image](https://github.com/user-attachments/assets/7b0bde1d-71cb-43d5-8fc7-61bb72bdf9ae)

当我在使用windows 11 系统下，去进行cmake编译的时候报 openssl未找到，但是openssl已经正确安装

![image](https://github.com/user-attachments/assets/22a3c8c7-3373-45bd-89a1-447444d53426)

### Expected Blizzlike Behaviour

同上

### Steps to reproduce the problem

同上

### AC rev. hash/commit

同上

### Operating system

windows 11 x64

**Comment by Nyeriah** [comment]
We can't offer support in languages other than English. Please post your issues in English.

**Comment by TheSCREWEDSoftware** [comment]
I think he has to define the OpenSSL path in cmake from that error

**Comment by leewheel** [comment]
It seems that this is a problem with your computer compilation environment.

**Comment by TheSCREWEDSoftware** [comment]
Closing this, no more was said from the author, you're free to re-open this in the future or another one if you provide the issue in english and including the explanation of the issue.
