### ISSUE TITLE
Help to Fix Memory Leak!

### ISSUE THREAD

**Issue by DARKENE** [azerothcore/azerothcore-wotlk#2048]
DESCRIPTION: I have the same problem, in the last version Azerothcore
huge memory leak 12 hours = 2.401 -> 5.910gb

So0o bad bug, server uptime 12 or 24 hours = memory usage full!

@spinzaku please help , give information!

#Confirm https://github.com/azerothcore/azerothcore-wotlk/issues/1887

version: https://github.com/azerothcore/azerothcore-wotlk/commit/ea2ecdbcc8eb2c47d420d0fb29dcb04897228d84

OPERATING SYSTEM: debian

MODULES:
NO

**Comment by Winfidonarleyan** [comment]
Ah...

**Comment by DARKENE** [comment]
Why @Winfidonarleyan  !

**Comment by Stoabrogga** [comment]
Quoting myself from here: https://github.com/azerothcore/azerothcore-wotlk/issues/508#issuecomment-507162871
> Closing this, as there's no prove about memory leaks. Enough people tried to reproduce this behaviour, checked their own server and commented on the issue that everything is ok, even after days of server uptime, e.g.:
> [#1887 (comment)](https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-495946651)
> [#1887 (comment)](https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-506558222)
> [#1887 (comment)](https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-506649011)
> 
> I also use AC for many months now without any issues.

**Comment by poszer** [comment]
**Ban everyone from now who open issue without crash log, without more informations!
This isn't problem on AC, there isn't memory leak, and for those people who are trying to f**ck project and team, I can say one big words: " We will work more and even get better from day to day ".**
