### ISSUE TITLE
What closed All Memory Leak Reports?!

### ISSUE THREAD

**Issue by DARKENE** [azerothcore/azerothcore-wotlk#2049]
@Stoabrogga

what closed my post? it is bug, 100x report of Memory Leak in the last versions
You only see this command? https://github.com/azerothcore/azerothcore-wotlk/issues/1887#issuecomment-495946651

You may not be able to fix the problem, You should not ignore our report!

What should we do?

We trusted this project, this is not right!
Reduced project azerothcore popularity, Everyone left?

**Comment by Stoabrogga** [comment]
You provide no prove. The issue can not be reproduced. As I see it you use this account you created yesterday to post spam on the project. Closing.
