### ISSUE TITLE
[QUEST] Into the World of Spirits

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#205]
**Description**: You have to search for Reagent Pouch on the deck of sunken ship
http://www.wowhead.com/item=33635/reagent-pouch

**Current behaviour**: The item don't exist

**Expected behaviour**: The item is on the deck

**Steps to reproduce the problem**: Go to the sunken ship

Quest: http://www.wowhead.com/quest=11333
##

**Comment by HeartWell** [comment]
```sql
-- Fix Game Object Position
-- Quest: 11333 Into the World of Spirits
UPDATE `gameobject` SET `position_x`=724.7922, `position_y`=-5170.241, `position_z`=-73.79707, `orientation`=-1.937316, `rotation2`=-0.8241262, `rotation3`=0.5664061, `animprogress`=100 WHERE `guid`=56732; -- Reagent Pouch

**Comment by HeartWell** [comment]
Does not need a fix! It is further specified quest, the search area is large. 

<a target="_blank" href="http://radikal.ru"><img src="http://s019.radikal.ru/i604/1610/eb/2a8bc6429616.jpg" /></a>

**Comment by HeartWell** [comment]
Maybe close?
