### ISSUE TITLE
Winterhoof Cleansing Quest 754 cannot complete

### ISSUE THREAD

**Issue by blinkysc** [azerothcore/azerothcore-wotlk#20500]
### Current Behaviour

Using item 5411 winterhoof-cleansing-totem at 42,14 well doesn't "cleanse" the well

### Expected Blizzlike Behaviour

Totem should cleanse the well so that quest can proceed
![image](https://github.com/user-attachments/assets/7777e7b9-0466-4b5a-9220-67907d44a8aa)

### Steps to reproduce the problem

Accept quest 754 got to well 42,14 and try to use the totem to cleanse

### AC rev. hash/commit

Chromie Craft

### Operating system

Windows 11

**Comment by TheSCREWEDSoftware** [comment]
You're at the wrong well.

**Comment by blinkysc** [comment]
Oh thought for sure all wells were “game” I’ll just close this lmao

**Comment by TheSCREWEDSoftware** [comment]
For that area they are two well quests if not mistaken, south which is the first "something of will" and the other one up north is "Thundershock or something". If you check this quest in Wowhead probably peole have marked it the comments where it is

**Comment by heyitsbench** [comment]
For the record, in the future if you find bugs on the ChromieCraft server, you should report them on the ChromieCraft specific repository [here](https://github.com/chromiecraft/chromiecraft/issues/new/choose).
