### ISSUE TITLE
Quest Bug: "Behind the Moonstone" [Quest ID: 10994]

### ISSUE THREAD

**Issue by kambire** [azerothcore/azerothcore-wotlk#20522]
### Current Behaviour

Current Behaviour
The quest "Behind the Moonstone" (Part 5 of 6) is not completing as expected. Players are required to bring a Southfury Moonstone to Morthis Whisperwing at Cenarion Refuge, but upon gathering the Southfury Moonstone and reaching Morthis, the quest does not progress or complete. This bug prevents players from moving forward in the quest chain necessary to access the "Anzu" encounter, which is critical for farming the Raven Lord mount.

Affected:

    Quest: [Behind the Moonstone (ID 10994)](https://www.wowhead.com/wotlk/es/quest=10994/tras-la-piedra-lunar)
    Required Item: Southfury Moonstone

### Expected Blizzlike Behaviour

After obtaining the Southfury Moonstone from near the river in Azshara (around the mounds near the river source) and bringing it to Morthis Whisperwing at Cenarion Refuge, the quest should update and complete, allowing players to continue and eventually face Anzu.

### Source

You can check the expected behavior on WoWHead: [Behind the Moonstone (Quest ID: 10994)](https://www.wowhead.com/wotlk/es/quest=10994/tras-la-piedra-lunar)

### Steps to reproduce the problem

Steps to reproduce the problem

1.-     Accept the quest "Behind the Moonstone" (ID: 10994).
2.-     Go to Azshara and obtain the Southfury Moonstone from the mounds near the source of the river.
3.-     Take the Southfury Moonstone to Morthis Whisperwing at Cenarion Refuge.
5.-     Observe that the quest does not complete as expected.

### AC rev. hash/commit

.server debug
AC> AzerothCore rev. d12de19e5b5b+ 2024-11-06 15:14:23 +0000 (HEAD branch) (Unix, Release, Static)
Connected players: 15. Characters in world: 14.
Connection peak: 20.
Server uptime: 2 hour(s) 46 minute(s) 54 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 5ms
|- Median: 1ms
|- Percentiles (95, 99, max): 15ms, 16ms, 16ms
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80040
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-124-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 2) configured in port 9086
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: z_filter_disabled_and_trash.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-account-mounts
|- mod-ah-bot
|- mod-anticheat
|- mod-arena-replay
|- mod-bg-reward
|- mod-breaking-news-override
|- mod-cfbg
|- mod-ghost-speed
|- mod-learn-spells
|- mod-transmog

### Operating system

Ubuntu 22

**Comment by TheSCREWEDSoftware** [comment]
Looking at your issue now. Refer in the future using the English sources. And the quest in english its called `Chasing the Moonstone` while a literal translation is Behind, it's refer to the chasing of it and behind.
