### ISSUE TITLE
(Player Spell Interaction) - Lay on Hands heals through Cyclone 

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20527]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7497

Triage Notes: To my testing the abilities go through but the healing shouldn't. when casting Lay on hands on the cyclone target i got "Immune" but i got the full heal out of it.

<details>

<summary>Image of the combat log while testing</summary>

![image](https://github.com/user-attachments/assets/aa9e9fb7-ae3b-4cd4-9242-4cdb16a7b6d7)

</details>

Original Post Below: 

---

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

spell https://wowgaming.altervista.org/aowow/?spell=633 can heal through https://wowgaming.altervista.org/aowow/?spell=33786 

### Expected Blizzlike Behaviour

this should not happen, you cannot heal through cyclone under any circumstances

### Source

https://www.wowhead.com/spell=33786/cyclone#comments
"This not only makes your target unable to do anything and immune to damage, but it also makes it immune to heals."

### Steps to reproduce the problem

cast cyclone
cast Lay on Hands
notice it heals through

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/88db984e52b2c0daf533c6a1ef769a3d50d7347c

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
To my knowledge the healing abilities go through cyclone just they do not heal. while cyclone is active on the target, you shouldn't be forbidden from casting tho

@IntelligentQuantum

**Comment by Nyeriah** [comment]
> @TheSCREWEDSoftware is it correct? ![image](https://private-user-images.githubusercontent.com/14080516/385179348-a5ee934f-ff11-4560-b09a-85aa60bb6453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTIzNTQsIm5iZiI6MTczMTQxMjA1NCwicGF0aCI6Ii8xNDA4MDUxNi8zODUxNzkzNDgtYTVlZTkzNGYtZmYxMS00NTYwLWIwOWEtODVhYTYwYmI2NDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDExNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNjNiYWNhMDZkNmIyYjUxN2I0ODkxMGZlMjdlOTE1YTAwMTI4YmI3ZjU3OGJmMjcyMGVmZWFhN2YwMDI4YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lknlx_F6YgwOikRsfHsJT1N-4kTW6oTogVvuTvqRIBs)

Looks completely custom

> To my knowledge the healing abilities go through cyclone just they do not heal. while cyclone is active on the target, you shouldn't be forbidden from casting tho

This

**Comment by TheSCREWEDSoftware** [comment]
I dont understand the question

**Comment by Nyeriah** [comment]
> I dont understand the question

There is no question. It’s a quote.

**Comment by TheSCREWEDSoftware** [comment]
Were acknowelding my response to [IntelligentQuantum](https://github.com/IntelligentQuantum)? If that was my miss-understading of your message

**Comment by IntelligentQuantum** [comment]
> To my knowledge the healing abilities go through cyclone just they do not heal. while cyclone is active on the target, you shouldn't be forbidden from casting tho
> 
> @IntelligentQuantum

ow tnx
