### ISSUE TITLE
[CRASH] .npc set faction original

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20535]
### Current Behaviour

World crash after using .npc set faction original without a target (if that matter)
https://gist.github.com/manstfu/79dcc7338f80e47164e3600c06c8e3da

### Expected Blizzlike Behaviour

Don't crash

### Steps to reproduce the problem

.npc set faction original

### AC rev. hash/commit

rev. 752c6875b524+

### Operating system

Debian 12

**Comment by TheSCREWEDSoftware** [comment]
Can confirm the issue above. If `.npc set faction original` with target it' crashes, I think has to do with the command parsing not being set correctly.

**Comment by TheSCREWEDSoftware** [comment]
PR for the issue has been created and test. Just a matter of waiting for it to get merged.
