### ISSUE TITLE
Feature: Rewrite Auction House search

### ISSUE THREAD

**Issue by walkline** [azerothcore/azerothcore-wotlk#20538]
### Describe your feature request or suggestion in detail

Currently, the auction search implementation has race conditions that lead to crashes (like [this one](https://gist.github.com/Nyeriah/d331e335c0c99427755712cc482ff295)).
The race conditions happens in this thread - https://github.com/azerothcore/azerothcore-wotlk/blob/f8d53d4cd87a887237986e4a2619b54c701f1dc0/src/server/apps/worldserver/Main.cpp#L713
In this thread, we interact with auction listings and players/sessions without proper synchronization.

### Describe a possible solution to your feature or suggestion in detail

I see several solutions here:

1. Move search requests back to the world thread. This isn't the best option, as searches would affect the world update tick (diff).
2. Use an appropriate threading model for search requests. I outlined my ideas in this scheme, but it's not the only way to achieve this.  
![AH drawio](https://github.com/user-attachments/assets/cecaa172-ec79-42cc-8663-27bdce5fb11a)
I believe the suggested solution is scalable and would require minimal locking. Since each worker maintains its own cache, it has a space (RAM) complexity of NxM, where N is the number of workers and M is the number of listings in the auction.
3. Delegate Auction House functionality to a new service (process). I have long-term plans to implement this as part of [TC9](https://github.com/walkline/ToCloud9) project, but I think we need a solution now.

**Comment by Grimdhex** [comment]
I don't think there's much discussion to be had here. The first option is not preferable from a performance point of view, and even if the third option is interesting, it's not ready yet. So that leaves option two, which seems structurally correct to me (but I don't know much about multhi-threading).

**Comment by Takenbacon** [comment]
I am working on putting something together for this.

**Comment by Takenbacon** [comment]
I have not forgot about this, ended up getting a little busy. I've made a couple changes based on @walkline feedback

WIP can be found here https://github.com/Takenbacon/azerothcore-wotlk/commits/ah_threading/
Note: while it compiles as of posting this comment it is currently completely untested and missing a few things (configs, SMSG_AUCTION_BIDDER_LIST_RESULT, SMSG_AUCTION_OWNER_LIST_RESULT, etc)

**Comment by walkline** [comment]
@Takenbacon Nice! Thanks for the update!
Maybe you could create PR where we can request help with testing? You can still mark the PR as WIP if needed.

**Comment by Takenbacon** [comment]
I wanted to get it feature complete before bothering, which it "SHOULD" be as of now. I'd like to do some testing locally before making a PR as I'm sure there is probably a couple silly mistakes with this large of a change set. I'm hoping I can get my local setup tonight or tomorrow and do some initial testing then make the PR soon.
