### ISSUE TITLE
[Raid-WotLK] Naxxramax - Ender event not over on kill Loatheb

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2053]
When you kill Loatheb the event takes approx. 30 min in finishing.
Door of the room does not open and when leaving the dungeon you can not enter it gives you the message that the event is still running.

How reproduce

Tele naxx
advance in the dungeon and kill loatheb
look the magic =)

(This bug its not present in olders branch back 27/06/2019)

BRANCH(ES):
master

AC HASH/COMMIT:
d8f14c9

OPERATING SYSTEM:
ubuntu 16.04

MODULES:
No

**Comment by ArashGorge** [comment]
it was no problem
tested
IMG: https://ibb.co/dpHqvzm

**Comment by solidmaxtor** [comment]
I test compiling fresh days  29, 30,31 juny and 1,2, july all days test and problem persist. 
All the scripts in Naxxramas were rewritten. Look at the scripts of day 26 and they are very different from the later ones.
It is where this problem originates.

![Uploading WoWScrnShot_070319_015935.jpg…]()
![WoWScrnShot_070319_020206](https://user-images.githubusercontent.com/50475454/60690690-ea99bf80-9e8e-11e9-8b76-2f8df6cf7981.jpg)

This file is /src/server/scripts/Northrend/Naxxramas/Loatheb.cpp
2 files in zip  day26 and actual cpp
[loatheb.zip](https://github.com/azerothcore/azerothcore-wotlk/files/3360702/loatheb.zip)

**Comment by Selyria** [comment]
https://youtu.be/XDZQKLJLU9c

Yes, I can confirm that the door no longer opens and that the portal is also missing. And you are trapped.

**Comment by spinzaku** [comment]
confirmed bug

**Comment by disclosurez** [comment]
confirmed bug

**Comment by disclosurez** [comment]
confirmed bug, use this script until it's fixed.

https://pastebin.com/wnSPW08x

**Comment by solidmaxtor** [comment]
11/07/19
Bug persist, Only work fine if copy old 26/06/19 script

**Comment by GMKyle** [comment]
@solidmaxtor Override Justdied funtion:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Naxxramas/boss_loatheb.cpp#L106
```c++
        void JustDied(Unit* killer) override
        {
            BossAI::JustDied(killer);
            if (pInstance)
                pInstance->SetData(BOSS_LOATHEB, DONE);
            summons.DespawnAll();
        }
```
enjoy!!

**Comment by FrancescoBorzi** [comment]
@GMKyle can you please open PR with that?

**Comment by GMKyle** [comment]
@FrancescoBorzi i can't until monday :(

**Comment by FrancescoBorzi** [comment]
@GMKyle it's fine, there is no rush :)

**Comment by Stoabrogga** [comment]
Closing this issue as #2098 has been merged.
