### ISSUE TITLE
[Midsummer] Ribbon Pole Dance Missing NPC Spawns [$30]

### ISSUE THREAD

**Issue by heyaapl** [azerothcore/azerothcore-wotlk#2054]
##### SMALL DESCRIPTION:
The Ribbon Pole [GOB 181605] has many guid's which are missing a corresponding NPC spawn [17066] on top of the pole to enable the buff, ribbon line effect, and ground effects to work.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Click on the Ribbon Pole, spin around with a blue spell effect coming from the top of the pole to the player. Apply the 10% exp buff to the player in +3 min increments for every couple of seconds of spinning. Occasionally blue circular flames are cast on the ground below the pole.

##### CURRENT BEHAVIOUR:
Some Poles work, others do nothing. You spin around a few times but stop. No buff, no blue line, no ground effect.

##### STEPS TO REPRODUCE THE PROBLEM:
1. See GOB GUID 150707 (Razor Hill) during Midsummer event. Click on the pole, it doesn't work.
2. See GOB GUID 51040 (Goldshire) during Midsummer event. Click on the pole, and it works as intended.

##### EXTRA NOTES:
The NPC 17066 should be spawned on top of the Ribbon Pole GOB so that the spell effects target the correct place on the Pole.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
5086af8190e82cf134ed6eed2d15406bb6daf64d

##### OPERATING SYSTEM:
Debian 9

##### MODULES:
No

##### OTHER CUSTOMIZATIONS:
No

**Comment by poszer** [comment]
Confirmed

**Comment by poszer** [comment]
Test my PR when u can @heyaapl
