### ISSUE TITLE
[The Eye] - Boss: Al'ar keeps doing Rebirth after casting Dive Bomb

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20569]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/6752

Triage Notes: Not mine, visual example of the issue: https://github.com/chromiecraft/chromiecraft/issues/6752#issuecomment-1974899616

Original Post Below: 

---

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

Al'ar does Rebirth after every Dive Bomb

### Expected Blizzlike Behaviour

Rebirth is his revival after death in P1, should only be used to transition to P2

### Source

https://www.wowhead.com/tbc/guide/alar-the-eye-tempest-keep-strategy-burning-crusade-classic
https://www.icy-veins.com/tbc-classic/al-ar-guide-strategy-abilities-loot

>>Phase 2 - Rebirth will trigger at the start of the Phase, dealing fire damage and knocking back all nearby players.
>>[Rebirth] Starts the second phase of the fight, once again knocking back everyone near the boss and dealing Fire damage.

### Steps to reproduce the problem

1. Al'ar P2

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9c1dc95dd8f150a77673d9f23235b235dd700e4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Issue description and comments on the original report are contradictory

**Comment by heyitsbench** [comment]
> it's sniff data enough prove this issue vs comment (of the issue)?

Sniffs only show one cast of 34342 throughout the encounter, but multiple casts of 35369.

**Comment by TheSCREWEDSoftware** [comment]
@heyitsbench can you confirm me if 35369 gets casted alongside 35181 or vice-versa?

**Comment by heyitsbench** [comment]
> can you confirm me if 35369 gets casted alongside 35181 or vice-versa?

```
35181 casts

18:02:44.202
18:03:40.890
18:04:37.579
18:05:32.688
18:06:29.380
18:07:24.545
18:08:18.092
18:09:14.890

35369 casts

18:02:47.438
18:03:44.134
18:04:40.814
18:05:35.931
18:06:32.618
18:07:27.792
18:08:21.332
18:09:18.134
```

**Comment by TheSCREWEDSoftware** [comment]
Thanks for confirming bench, i will be closign this issue and the cc one.
