### ISSUE TITLE
(Minor) Wrong placement of pumpkin object? Midsummer Fire Festival

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2056]
(Minor) Wrong placement of pumpkin object? Midsummer Fire Festival

##### SMALL DESCRIPTION:

Wrong placement of pumpkin object? Midsummer Fire Festival

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No pumpkin on live server

##### CURRENT BEHAVIOUR:

No pumpkins at all on midsummer fire festival
![pumpkin](https://user-images.githubusercontent.com/18629476/60638447-08483400-9e51-11e9-86f8-9caf36245ba0.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Tele Silvermoon City
2.  Find pumpkin!

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8190e82cf134ed6eed2d15406bb6daf64d

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Yea it's wrongly spawned there. Thanks for report
