### ISSUE TITLE
map.h and map.cpp Some code causes crash

### ISSUE THREAD

**Issue by leewheel** [azerothcore/azerothcore-wotlk#20574]
### Current Behaviour

00007FF6B9C008B5  0000005927CFDF00  Map::getNGrid+35  C:\WoWServer\335Source\azerothcore\azerothcore-wotlk\src\server\game\Maps\Map.h line 687
00007FF6BA5E60BB  0000005927CFDF30  Map::IsGridLoaded+1B  C:\WoWServer\335Source\azerothcore\azerothcore-wotlk\src\server\game\Maps\Map.cpp line 667

### Expected Blizzlike Behaviour

No

### Source

`    [[nodiscard]] NGridType* getNGrid(uint32 x, uint32 y) const
    {
        ASSERT(x < MAX_NUMBER_OF_GRIDS && y < MAX_NUMBER_OF_GRIDS);
        return i_grids[x][y];
    }`

`void Map::VisitNearbyCellsOfPlayer(Player* player, TypeContainerVisitor<Acore::ObjectUpdater, GridTypeMapContainer>& gridVisitor,
                                   TypeContainerVisitor<Acore::ObjectUpdater, WorldTypeMapContainer>& worldVisitor,
                                   TypeContainerVisitor<Acore::ObjectUpdater, GridTypeMapContainer>& largeGridVisitor,
                                   TypeContainerVisitor<Acore::ObjectUpdater, WorldTypeMapContainer>& largeWorldVisitor)`

### Steps to reproduce the problem

Most of the time it appears when the character exits, both logout and exit will appear, but not 100%

### AC rev. hash/commit

AzerothCore rev. 21d2ca7ff321+ 2024-11-15 11:50:27 +0800 (NpcBotsLFG branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.1.2 1 Aug 2023)
Using Boost version: 1.81.0
Using CMake version: 3.29.5
Using MySQL version: 80037
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8098
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in Data/maps. Total size: 467378196 bytes
vmaps directory located in Data/vmaps. Total size: 1190145877 bytes
mmaps directory located in Data/mmaps. Total size: 3397173168 bytes
Default DBC locale: enUS.
All available DBC locales: enUS koKR frFR deDE zhCN zhTW esES esMX
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: No updates found!
Latest CharacterDatabase update: No updates found!
Latest WorldDatabase update: 2024_07_17_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- DungeonRespawn
|- ReusablePotion
|- StatBooster
|- StatBoosterReroller
|- mod-absorb
|- mod-anticheat
|- mod-appreciation
|- mod-auctionator
|- mod-autobalance
|- mod-breaking-news-override
|- mod-eluna
|- mod-emblem-transfer
|- mod-guildfunds
|- mod-individual-progression
|- mod-keep-out
|- mod-npc-beastmaster
|- mod-random-enchants
|- mod-reagent-bank-account
|- mod-reward-played-time
|- mod-starting-pet
|- mod-transmog
|- mod-war-effort
|- mod-world-chat

### Operating system

Windows 10

**Comment by Grimdhex** [comment]
Samething that all your issue provide complete crash logs and check on clean AC... Almost sure that cause by your repack or custom changes...

**Comment by leewheel** [comment]
I found it, it was caused by the behavior of some NPC Bots, thank you

**Comment by Grimdhex** [comment]
> I found it, it was caused by the behavior of some NPC Bots, thank you

If you use NPCBots all your issues should be post on their repos. We can't provide support for this fork. (except if it's something related to Gameplay as Quest, or Raid/Dungeons... and not related to bots behaviours).
