### ISSUE TITLE
[Dustwallow Marsh] Darkfang Venomspitter underneath terrain.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20594]
Bug Triager Notes:

Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7506#issue-2664561187

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

30-39

### Current Behaviour

[Darkfang Venomspitter](https://wowgaming.altervista.org/aowow/?npc=4414), id=4414, guid=7887 is hanging around underneath terrain in Dustwallow Marsh

### Expected Blizzlike Behaviour

not needed

### Source

not needed

### Steps to reproduce the problem

.gm fly on
.go creature 7887

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6fd034c8b3038a967e17136ece47df13009e1d68

### Operating system

Windows 11

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
> * [ ]  `.go xyz -2572.63 -3742.22 23.0639 1 2.47837` // GUID: 7887
> * [x]  `.go xyz -2568.83 -3653.23 51.1729 1 0.03025`
> * [x]  `.go xyz -3103.18 -3603.2 65.412 1 0.086061`
> * [ ]  `.go xyz -3215.17 -3649.05 43.9613 1 4.08407` // GUID: 18622
> * [x]  `.go xyz -2551.34 -2848.82 65.2243 1 6.06282`
> * [x]  `.go xyz -2465.57 -2918.18 39.8907 1 0.09834`
> * [x]  `.go xyz -2712.31 -3934.22 75.349 1 1.36309`
> * [x]  `.go xyz -3319.99 -4204.49 42.4945 1 5.03846`
> * [x]  `.go xyz -3360.47 -4235.41 23.5935 1 1.12638`
> * [x]  `.go xyz -3076.78 -4137.48 24.142 1 3.22765`
> * [x]  `.go xyz -3176.96 -3703.58 51.0437 1 5.03661`
> * [x]  `.go xyz -3254.27 -3720.83 43.4415 1 5.56083`
> * [x]  `.go xyz -3412.88 -3956.42 27.9814 1 0.265643`
> * [x]  `.go xyz -2769.73 -4053.95 57.5352 1 3.51775`
> * [x]  `.go xyz -2838.79 -4125.88 48.9155 1 5.8136`
> * [x]  `.go xyz -2968.12 -3576.43 39.42 1 2.35847`
> * [x]  `.go xyz -3407.39 -4275.99 28.6751 1 4.46741`
> * [x]  `.go xyz -2946.58 -3145.52 34.3377 1 0.979004`
> * [x]  `.go xyz -3360.04 -4045.12 25.9036 1 4.92623`
> * [x]  `.go xyz -2943.94 -3007.72 40.2233 1 4.8634`
> * [x]  `.go xyz -2853.99 -3579.29 37.5432 1 3.17021`
> * [x]  `.go xyz -3012.98 -2778 57.1159 1 5.01807`
> * [x]  `.go xyz -3002.28 -2956.01 33.3417 1 2.44186`

These are the TWO Guids that get spawn under the ground

**Comment by TheSCREWEDSoftware** [comment]
After fixing their Z axis. They do not have pathing/patrol
