### ISSUE TITLE
[Pet hunter non tamable]

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#206]
**Description**: The NPC Wild Sparrowhawk (beast) in Outland>Nagrand is not tamable
http://www.wowhead.com/npc=22979/wild-sparrowhawk

**Current behaviour**: When i use the spell tame beast the error is "Invalid target"

**Expected behaviour**: The spell work and the Npc (beast) became my new pet

**Steps to reproduce the problem**: Go to outland and try to tame this NPC

**Comment by HeartWell** [comment]
Maybe costs flags exotic npc?

**Comment by ghost1988** [comment]
I don't know i can only test in game

**Comment by talamortis** [comment]
** Comment on WoW Head **

These birds are tameable as of a hotfix today in patch 5.0.4. They are quite a tricky tame as they immediately drop threat and flee (thus interrupting the tame). One way to maintain threat is to (ironically, given the above problem) use Scare Beast on them. They don't drop threat while they're feared. You just have to hope they don't fly out of range.

Of course there are plenty of other grey owls in the game so there's no real reason to do this other than the minor challenge :)

Patch 3.3.5 They was not tameable.

**Comment by ShinDarth** [comment]
@talamortis so it this report invalid ?

**Comment by talamortis** [comment]
by the sounds of it, they was tameable in 5.0.4 patch we are 3.3.5 so yes it will be invalid 👍
