### ISSUE TITLE
[CRASH] MotionMaster (maybe)

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#2061]
##### SMALL DESCRIPTION: 
- I have crash
- https://gist.github.com/Winfidonarleyan/181026c216ce788f06263d3c2f3839c5

##### STEPS TO REPRODUCE THE PROBLEM:
- Unknown

**Comment by wowmane** [comment]
soap is enable?

this crash is for soap !

same as static member of an already seen type

**Comment by solidmaxtor** [comment]
That happens to me when I mount a test server and the soap / ra ports are used by the main server.

 check if those ports are being used, if so change them for others at ease.

**Comment by poszer** [comment]
@Winfidonarleyan  did you try with disabling soap, what's happening?

**Comment by Winfidonarleyan** [comment]
I'm not sure, but maybe it helped.

**Comment by milestorme** [comment]
If you try run 2 servers on the same host using the same soap port it crash’s can confirm that , disabling soap on extra realms stops this crash, shouldn’t we be able to use soap on the same port for multiple realms?

**Comment by mik1893** [comment]
You can't run two soap servers on the same port, like any other service if a port is already used it will fail. Soap access is per single core running so if you run two realms on the same server, you'll need to specify different ports

**Comment by wowmane** [comment]
@Winfidonarleyan 

I said , disable soap and test...

**Comment by poszer** [comment]
> @Winfidonarleyan
> 
> I said , disable soap and test

Will you stop with that stupid edits?

**Comment by poszer** [comment]
Closing this
https://github.com/azerothcore/azerothcore-wotlk/issues/2061#issuecomment-514510371
