### ISSUE TITLE
[Zul'Aman-Halazzi] Boss life issue.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20634]
### Current Behaviour

During the Lynx phase, if the Spirit Lynx or Halazzi's HP drops too quickly, the boss returns to its normal phase with a low percentage of HP, causing the mechanics to break down.

Evidence 1 (Lynx): [Youtube](https://youtu.be/1VwnRnSD4CI)
Evidence 2 (Boss): [Youtube](https://www.youtube.com/watch?v=0E42q8CX6Ok)

### Expected Blizzlike Behaviour

Not needed

### Source

Not needed

### Steps to reproduce the problem

1. Fight Halazzi.
2. Use massive damage when Hallazzi or the Lynx are near to 20% of their HP.

### Extra Notes

Probably this issue happen only with the first Lynx phase, but I'm not sure.

### AC rev. hash/commit

[8c763f6](https://github.com/azerothcore/azerothcore-wotlk/commit/8c763f66123686183371edc996e099c11aeb3bf0)

### Operating system

Windows 11

**Comment by Nyeriah** [comment]
i think it might be an issue with cc tuning

**Comment by Rorschach91** [comment]
I Will try to replicate It on my AC server

**Comment by Rorschach91** [comment]
@Nyeriah You are right, it is a tuning issue.
