### ISSUE TITLE
[Zul'Aman] Halazzi doesn't use Earth Shock ability.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20636]
### Current Behaviour

During the fight, Halazzi doesn't use Earth Shock ability.

### Expected Blizzlike Behaviour

He should use it.

### Source

[WoWHead ](https://www.wowhead.com/tbc/guide/janalai-zulaman-za-strategy-burning-crusade-classic)guide
[Icy Veins](https://www.icy-veins.com/tbc-classic/halazzi-guide-strategy-abilities-loot) guide

### Steps to reproduce the problem

1. Fight the boss

### AC rev. hash/commit

[8c763f6](https://github.com/azerothcore/azerothcore-wotlk/commit/8c763f66123686183371edc996e099c11aeb3bf0)

### Operating system

Windows 11

**Comment by Nyeriah** [comment]
He selects a random target and **if** they are casting, he casts earth shock, else, he casts flame shock. So to test this you must be casting spells. Seems working to me (granted that is the expected behaviour)

**Comment by Rorschach91** [comment]
> He selects a random target and **if** they are casting, he casts earth shock, else, he casts flame shock. So to test this you must be casting spells. Seems working to me (granted that is the expected behaviour)

Yes, I read the script after the report.

All I know is that all the casters in my group have never been afflicted by that spell. 
I can try more tests. If the result is a false positive, I will close the report.
