### ISSUE TITLE
Unable to compile code - fatal error: use of undeclared identifier 'mysql_ssl_mode'; did you mean 'mysql_ssl_set'?

### ISSUE THREAD

**Issue by hysel** [azerothcore/azerothcore-wotlk#20656]
### Current Behaviour

Hi

I am using the core version on Linux. When trying to compile the code in Linux, I am getting the following error:

```
/home/wow/azerothcore/src/server/database/Database/MySQLConnection.cpp:132:9: fatal error: use of undeclared identifier 'mysql_ssl_mode'; did you mean 'mysql_ssl_set'?
  132 |         mysql_ssl_mode opt_use_ssl = SSL_MODE_DISABLED;
      |         ^~~~~~~~~~~~~~
      |         mysql_ssl_set
/usr/include/mariadb/mysql.h:539:14: note: 'mysql_ssl_set' declared here
  539 | int             STDCALL mysql_ssl_set(MYSQL *mysql, const char *key,
      |                         ^
1 error generated.
make[2]: *** [src/server/database/CMakeFiles/database.dir/build.make:189: src/server/database/CMakeFiles/database.dir/Database/MySQLConnection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Here is my setup:

OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

DB:
mysqld  Ver 10.11.8-MariaDB-0ubuntu0.24.04.1 for debian-linux-gnu on x86_64 (Ubuntu 24.04)

I tried pulling the source report again and starting from scratch, but it didn't help. 

### Expected Blizzlike Behaviour

I am able to compile the code

### Steps to reproduce the problem

Used the instruction here: https://www.azerothcore.org/wiki/linux-core-installation

### AC rev. hash/commit

N/A

### Operating system

Ubuntu 24.04.1 LTS

**Comment by heyitsbench** [comment]
MariaDB is no longer supported.

**Comment by hysel** [comment]
oh wow, ok than, I will migrate, thank you very much
