### ISSUE TITLE
[Zul'Aman] First 4 bosses are dropping one extra gear item

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20655]
Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7512#issue-2665159353

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

First 4 bosses ([Akil'zon](https://wowgaming.altervista.org/aowow/?npc=23574), [Nalorakk](https://wowgaming.altervista.org/aowow/?npc=23576), [Jan'alai](https://wowgaming.altervista.org/aowow/?npc=23578) and [Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577)) are dropping 2 gear items each

### Expected Blizzlike Behaviour

First 4 bosses ([Akil'zon](https://wowgaming.altervista.org/aowow/?npc=23574), [Nalorakk](https://wowgaming.altervista.org/aowow/?npc=23576), [Jan'alai](https://wowgaming.altervista.org/aowow/?npc=23578) and [Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577)) should only drop 1 random gear item each

### Source

[TBC Classic1](https://youtu.be/XDGZM7GQNoo?t=605) Akil'zon kill at 10:05 , Nalorakk at 17:40 , Jan'alai at 23:50 and Halazzi at 37:03 all of them dropped one gear item
[TBC Classic2](https://youtu.be/P5ycvN09UiY?t=754) Akil'zon kill at 12:30 , Nalorakk at 22:20 , Jan'alai at 30:15 and Halazzi at 41:35 all of them dropped one gear item
[Wotlk PrePatch](https://youtu.be/0CtPGmyOOlY?t=88) Akil'zon kill at 1:29 , Nalorakk at 3:12 , Jan'alai at 4:06 and Halazzi at 5:32 all of them dropped one gear item
[Wotlk PrePatch](https://youtu.be/7b-OtoM5Xpw?t=86) Akil'zon kill at 1:27 , Nalorakk at 6:57 , Jan'alai at 11:18 and Halazzi at 21:18 all of them dropped one gear item

### Steps to reproduce the problem

1. .go c id 23574
2. .go c id 23576 
3. .go c id 23578
4. .go c id 23577

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6fd034c8b3038a967e17136ece47df13009e1d68

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by heyitsbench** [comment]
These bosses also dropped only one item during Wrath Classic, specifically 3.4.3 53788. (Malacrass/Zul'jin did drop two items, plus Blood of Zul'jin)
