### ISSUE TITLE
WSG Flag while mounted

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2065]
Description:

Warsong flags can be picked up while mounted, to reproduce it needs to be done super fast.
If you click on the Flag millisecond before your Mount Cast Bar expires and boom! you are mounted and with a flag on your back!

Expected behavior: Players are not supposed to achieve this, cannot pick up flag while mounted

Steps to reproduce the problem:

Pick up a flag and walk outside,
Drop the Flag
Cast any mount spell (I tried over 20 mounts, all work)
Millisecond before your Mount Cast Bar expires click on the flag
Sometimes it won't work the first time cause you have to try it few times before you get a hang of it.

https://user-images.githubusercontent.com/6587064/54854899-b5f56400-4cf4-11e9-859a-b9d798215141.png

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/6db0a438d9dff3d1fab5f904657ed281f5dee6c7

OS: Linux; Debian

MODULES:
Anticheat

**Comment by ArashGorge** [comment]
Fixed Please test it
https://github.com/azerothcore/azerothcore-wotlk/pull/2067

**Comment by wowmane** [comment]
No, this is fixed
<cod>
            if (!m_goInfo->IsUsableMounted())
            playerUser->RemoveAurasByType(SPELL_AURA_MOUNTED);
</cod>

Test: build and in game.

**Comment by ArashGorge** [comment]
> No, this is fixed
> 
> if (!m_goInfo->IsUsableMounted())
> playerUser->RemoveAurasByType(SPELL_AURA_MOUNTED);
> Test: build and in game.

what is m_goInfo ? its not working, if u want to use (IF), try this

        if (player->IsMounted())
        {
         player->Dismount();
         player->RemoveAurasByType(SPELL_AURA_MOUNTED);
        }

**Comment by FrancescoBorzi** [comment]
@ArashGorge @wowmane 

please discuss about the test results in the [PR page (#2067)](https://github.com/azerothcore/azerothcore-wotlk/pull/2067), not here.

**Comment by wowmane** [comment]
@FrancescoBorzi 

I tested just this: worked!

if (!m_goInfo->IsUsableMounted())
playerUser->RemoveAurasByType(SPELL_AURA_MOUNTED);

**Comment by wowmane** [comment]
@ArashGorge 
If you want to join contribution staff

First, fix this commit:
https://github.com/azerothcore/azerothcore-wotlk/pull/2014

just need to fix build!

**Comment by FrancescoBorzi** [comment]
@wowmane what exactly have you tested?

**Comment by wowmane** [comment]
build and test on the bg, use mount and flag. 

if casted mount flag drop.

if (!m_goInfo->IsUsableMounted())
playerUser->RemoveAurasByType(SPELL_AURA_MOUNTED);

**Comment by FrancescoBorzi** [comment]
@wowmane it looks this other PR has been already approved for this bug resolution: https://github.com/azerothcore/azerothcore-wotlk/pull/2067

More in general: when you have a fix just open a PR ;)
