### ISSUE TITLE
[Quest] Goblin Invaders should not require "The Spirits of Stonetalon" as a prerequiste.

### ISSUE THREAD

**Issue by GroodeeshPanj** [azerothcore/azerothcore-wotlk#20669]
### Current Behaviour

Unable to start the quest "Goblin Invaders" without first getting the quest "The Spirits of Stonetalon" from Zor Lonetree in Grommash Hold.

### Expected Blizzlike Behaviour

Be able to obtain the quest "Goblin Invaders" without needing the quest "The Spirits of Stonetalon"

### Source

https://www.wowhead.com/wotlk/quest=1061/the-spirits-of-stonetalon 
https://www.wowhead.com/wotlk/quest=1062/goblin-invaders

Several comments state that you don't need to complete "The Spirits of Stonetalon" first. Do note however, if you accept "Goblin Invaders" then you can not go back and accept "The Spirits of Stonetalon" quest.

### Steps to reproduce the problem

1. .go c id 4049
2. unable to accept quest "Goblin Invaders"
3. .go c id 4047 
4. Accept "The Spirits of Stonetalon"
5. .go c id 4049 
6. Turn in "The Spirits of Stonetalon"
7. Now able to accept "Goblin Invaders"

### Extra Notes

My guess is the same treatment needs to be done as was done to these quests already commited: https://github.com/azerothcore/azerothcore-wotlk/commit/cdade8dcd65737875434bdb779ebe7cbcfe7103c but I am far from an expert. Thank you.

### AC rev. hash/commit

AzerothCore rev. e2369986ef3c 2024-11-21 13:50:51 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 24.04 (Linux acore 6.8.12-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-3 (2024-10-23T11:41Z) x86_64 x86_64 x86_64 GNU/Linux)

### Custom changes or Modules

> Latest LoginDatabase update: 2024_11_15_00.sql
Latest CharacterDatabase update: mod_individual_xp_IndividualXP.sql
Latest WorldDatabase update: npc_services_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants

**Comment by TheSCREWEDSoftware** [comment]
Will look at this to confirm it along another two from CC. If i confirm them i will do a PR for the 3.

Image Source refering to no needing for the quest: 
![image](https://github.com/user-attachments/assets/d5635287-6b6a-4ec2-acd7-ca422356203b)
Wowhead comments [here](https://www.wowhead.com/wotlk/quest=1062/goblin-invaders) easier to find if you filter for the patch 2.2.3
