### ISSUE TITLE
Chains of ice while shaman is in Ghost Wolf form

### ISSUE THREAD

**Issue by tabooo** [azerothcore/azerothcore-wotlk#20676]
### Current Behaviour

Shaman is not slowed by 95% when in Ghost wolf and DK uses chains of ice spell on him.

### Expected Blizzlike Behaviour

chains of ice must apply 95% freeze for 1 sec and then reduce 10% for each second.

### Steps to reproduce the problem

1. use Ghost wolf spell with shaman
2. use chains of ice spell with DK on shaman

### AC rev. hash/commit

AzerothCore rev. e15ca6ff51d1+ 2024-11-21 07:23:01 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 29. Characters in world: 29.
Connection peak: 30.
Server uptime: 37 minute(s) 7 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 4ms
|- Median: 2ms
|- Percentiles (95, 99, max): 13ms, 14ms, 23ms
Using SSL version: OpenSSL 3.3.2 3 Sep 2024 (library: OpenSSL 3.3.2 3 Sep 2024)
Using Boost version: 1.81.0
Using CMake version: 3.31.0-rc2
Using MySQL version: 80403
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.4/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in C:/Azerothcore/server/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Azerothcore/server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Azerothcore/server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: zone_difficulty_completion_logs.sql
Latest WorldDatabase update: zone_difficulty_spelloverrides.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-anticheat
|- mod-autobalance
|- mod-bg-reward
|- mod-cfbg
|- mod-duel-reset
|- mod-guildfunds
|- mod-pvp-titles
|- mod-reset-raid-cooldowns
|- mod-transmog
|- mod-weekendbonus

### Operating system

Windows 11

**Comment by Tereneckla** [comment]
Are you saying the debuff is not applied?

Because in ghost wolf shamans can't be slowed below base speed

**Comment by tabooo** [comment]
Debuff not works properly. Debuff applied but not slowed by 95%

**Comment by Tereneckla** [comment]
Then it is working correctly as ghost wolf cannot be slowed
![image](https://github.com/user-attachments/assets/9e339d10-42c5-4255-a4c9-918ce41e32b2)

**Comment by tabooo** [comment]
Ok I will close this issue
