### ISSUE TITLE
Boss Lady Deathwhisped - Vengeful Shade unroot timer

### ISSUE THREAD

**Issue by tabooo** [azerothcore/azerothcore-wotlk#20677]
### Current Behaviour

when npc Vengeful Shade is summoned by deathwhisper it imediatally runs to target.

### Expected Blizzlike Behaviour

when npc Vengeful Shade is summoned by deathwhisper it must wait for 2 sec and then run to target.

### Source

I changed this 500 to 2000 and worked:

boss_lady_deathwhisper.cpp on Line 915

           me->SetControlled(true, UNIT_STATE_ROOT);
           unroot_timer = 500; // <--- must be 2000
           targetGUID.Clear();

### Steps to reproduce the problem

1. go to ICC
2. Fight with Deathwhisper (2nd boss)
3. remove shield and wait to summon vengeful spirit

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/e15ca6ff51d1d7a420b6a75f0b1c5295eafa647a+ 2024-11-21 07:23:01 +0100 (master branch) (Win64, RelWithDebInfo, Static)
Connected players: 29. Characters in world: 29.
Connection peak: 30.
Server uptime: 37 minute(s) 7 second(s)
Update time diff: 1ms. Last 500 diffs summary:
|- Mean: 4ms
|- Median: 2ms
|- Percentiles (95, 99, max): 13ms, 14ms, 23ms
Using SSL version: OpenSSL 3.3.2 3 Sep 2024 (library: OpenSSL 3.3.2 3 Sep 2024)
Using Boost version: 1.81.0
Using CMake version: 3.31.0-rc2
Using MySQL version: 80403
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.4/bin/mysql.exe
Compiled on: Windows 10.0.19045
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in C:/Azerothcore/server/data/maps. Total size: 291014951 bytes
vmaps directory located in C:/Azerothcore/server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Azerothcore/server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: zone_difficulty_completion_logs.sql
Latest WorldDatabase update: zone_difficulty_spelloverrides.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-ah-bot
|- mod-anticheat
|- mod-autobalance
|- mod-bg-reward
|- mod-cfbg
|- mod-duel-reset
|- mod-guildfunds
|- mod-pvp-titles
|- mod-reset-raid-cooldowns
|- mod-transmog
|- mod-weekendbonus

### Operating system

Windows 11

**Comment by TheSCREWEDSoftware** [comment]
I would recommend you to submit a PR with the changes, but keep in mind this being part of AC that hasn't be touched to the point of functionality and polish, the PR may taken sometimes (if approved) to be approved.

As it's prefered, as it has been done for the last bosses in TBC moving what it can be moved from the Boss Script to SAI. 
A way to modernize the code to suit blizzard-like behaviour and reducing errors or crash by the human error (in code)
