### ISSUE TITLE
[Pilgrim's Bounty] Wild Turkey should only spawn in Tirisfal Glades or Elywnn Forest

### ISSUE THREAD

**Issue by GroodeeshPanj** [azerothcore/azerothcore-wotlk#20683]
### Current Behaviour

Wild Turkey mobs are found outside of intended areas, such as Silverpine Forest and inside Undercity. These turkeys are needed for the achievement: https://www.wowhead.com/wotlk/achievement=3578 "The Turkinator" I have not yet checked the Alliance side.

![image](https://github.com/user-attachments/assets/7cb6614e-cce0-4312-a24e-3070d53183db)

### Expected Blizzlike Behaviour

During Pilgrim's Bounty, Wild Turkey mobs should only spawn in Tirisfal Glades or Elywnn Forest.

### Source

https://www.wowhead.com/wotlk/npc=32820/wild-turkey#comments
https://www.wowhead.com/wotlk/achievement=3578#comments

![image](https://github.com/user-attachments/assets/b922e3bb-5532-4146-839a-875a8081eb13)

### Steps to reproduce the problem

1. .tele sepulcher
2. view happy turkey roaming free
3. run around silverpine to see more

### AC rev. hash/commit

AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/e2369986ef3c95f83af37e0620c246719cd0443a 2024-11-21 13:50:51 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 24.04

### Custom changes or Modules

List of enabled modules:
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants

**Comment by TheSCREWEDSoftware** [comment]
Comparing to the aowow https://wowgaming.altervista.org/aowow/?npc=32820 for the spawn locations and the query in the databse with `3'723` entries, I do think this issue is valid

**Comment by TheSCREWEDSoftware** [comment]
Will be doing a PR soon to remove the turkeys out of the other zones. About TOO MANY in the expected zones we need more sniff data.
