### ISSUE TITLE
[Zul'Aman] - Boss: Halazzi's Corrupted Lightning Totem doesn't do anything

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20698]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7544

Triage Notes: This a week ago https://github.com/azerothcore/azerothcore-wotlk/commit/905cc7b537de9967aadd8ac8aae782fa1616f50c the totems worked. (haven't looked at the code changes, probably being moved from Script to SAI?)

Original Post Below: 

---

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577)'s [Corrupted Lightning Totem](https://wowgaming.altervista.org/aowow/?npc=24224) doesn't do anything

### Expected Blizzlike Behaviour

[Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577)'s [Corrupted Lightning Totem](https://wowgaming.altervista.org/aowow/?npc=24224) should cast [Lightning](https://wowgaming.altervista.org/aowow/?spell=43301)

### Source

[Wotlk Classic](https://youtu.be/6XQW9eIQ68c?t=3134) at 52:16 , [Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577) summons [Corrupted Lightning Totem](https://wowgaming.altervista.org/aowow/?npc=24224) and it start casting [Lightning](https://wowgaming.altervista.org/aowow/?spell=43301)

### Steps to reproduce the problem

1. .go c id 23577
2. Deal damage to [Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577) until he reaches phase 2
3. Wait for [Halazzi](https://wowgaming.altervista.org/aowow/?npc=23577) in his human form to summon [Corrupted Lightning Totem](https://wowgaming.altervista.org/aowow/?npc=24224)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
Hmm

![image](https://github.com/user-attachments/assets/91c93760-cc30-4892-9298-9801f2c841b3)

**Comment by TheSCREWEDSoftware** [comment]
What rev you're testing it on? @IntelligentQuantum

**Comment by IntelligentQuantum** [comment]
> What rev you're testing it on? @IntelligentQuantum

https://github.com/azerothcore/azerothcore-wotlk/tree/0b771cbc922f06ecf159c43db9102a4716cc25a3

**Comment by TheSCREWEDSoftware** [comment]
Was asking because in a week the boss changed - https://github.com/chromiecraft/chromiecraft/issues/7544#issuecomment-2495523247
