### ISSUE TITLE
locales_ translations in database dont work properly with core? esES Client

### ISSUE THREAD

**Issue by sucofog** [azerothcore/azerothcore-wotlk#207]
**Description**: Locales translations don't work properly (for me)

**Current behaviour**: I have a database of the same exact estructure than the one using with azerothcore-wotlk, i translated everything as it is in the other database i use with an old Trinitycore compilation,, but in this case with azerothcore-wotlk.. quests dont detect the translations on locales_ tables on world database,, items dont translate, npc texts dont translate,, they still remain in english, i used locales 6 as in my old database that worked properly, this is maybe a think i should set-up in worldserver.conf file? I did something wrong?
Its problem of the core not reconizing the locales?
Should i help with a fix to this?

**Expected behaviour**: Using translation locales_ system should translate for clients texts to language according to his client, in my case esES.

**Operating system**:  Windows 10 Pro

**Modules**:  Should i use any module to solve this? Don't really know...

**Other Customizations**: Clean compile, everything works fine except for translations to Spanish.

If you can explain me detaile

If you need screenshots i can attach them.
Thanks and sorry for my english.
Keep this great work.
##

**Comment by sucofog** [comment]
Also sorry if i have duplicated an issue!

**Comment by cooler-SAI** [comment]
ok! what left here? Quests ?

**Comment by UGCMcKay** [comment]
Yes, Quests are still in englisch even with translations in the database
