### ISSUE TITLE
Shoot 'Em Up (Quest) - Stuck in combat bug [$5]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2071]
Shoot 'Em Up (Quest) - Combat Bug

##### SMALL DESCRIPTION:

After the drake dies near a harpoon, you will get stuck in combat bug. Even logging out won't help.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You shouldn't be stuck in combat after drake dies near harpoon

##### CURRENT BEHAVIOUR:

After the drake dies near a harpoon, you will get stuck in combat bug. Even logging out won't help.

![combatbug](https://user-images.githubusercontent.com/18629476/60768928-56349480-a0fc-11e9-828c-1f017bba87d4.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do Shoot 'Em Up quest
2. Kill drake near harpoon

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8

##### OPERATING SYSTEM:

 Ubuntu 16/18

**Comment by Naxxramas-Server** [comment]
Confirmed

**Comment by wowmane** [comment]
Confirmed

**Comment by grimgravy** [comment]
I am checking. Wait for correction.

**Comment by Kitzunu** [comment]
I cannot reproduce this

**Comment by Si1ker** [comment]
Confirmed on last rev 9d0ebcd

**Comment by Kitzunu** [comment]
What did you do to reproduce @Si1ker ?

**Comment by Si1ker** [comment]
@Kitzunu Go do the quest, mount in the vehicle, shoot drakes, get out you'll end up in combat state.
This won't happen at 10% of the time but most of the cases.

Another thing you can do, get into the cannon, shot a drake 1 time, wait until the drake comes close to you, left the cannon, kill it, then you should be stuck in combat until you die

**Comment by Kitzunu** [comment]
Ok I will try later, because last time I did that I couldn't reproduce. Thank you!

**Comment by Si1ker** [comment]
In addition to this issue, when you shoot form the cannon, most of the time it does not count for damage when you hit a drake. It takes several shots until it finally starts getting damage.

**Comment by merdlin** [comment]
Confirmed

**Comment by Kitzunu** [comment]
I believe two things:
1. Dragons should never aggro the player
2. The quest credit distance needs to be upped. How, I dont know yet
