### ISSUE TITLE
[NPC/World] - Certain NPC (if not all). Do not move after being interacted with

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20721]
### Current Behaviour

If you talk to any npc that has an interaction, like a gossip, they will stop and stay there until a server restart.

### Expected Blizzlike Behaviour

After the interaction is done, for them to eventually move.

### Source

N/A

### Steps to reproduce the problem

For alliance, at the start of the server / loading the area. 
- `.go c 208110` // Isle of Conquest Emissary
- Interact with any of the `Isle of Conquest Emissaries`
- Oberseve them not moving

For horde, at the start of the server / loading the area. 
- `.go c i 23713` // Kraxx
- Interact with Kraxx
- Oberseve him not moving.

### Extra Notes

Reported by `atlas` ( iatlas |155066684774940674 ) in Discord

![image](https://github.com/user-attachments/assets/89c1e631-421c-449b-b9af-4cde121c0411)

### AC rev. hash/commit

AzerothCore rev. f14edcbdc90c

```
Connected players: 2. Characters in world: 2.
Connection peak: 2.
Server uptime: 48 minute(s) 22 second(s)
Update time diff: 2ms. Last 500 diffs summary:
|- Mean: 2ms
|- Median: 2ms
|- Percentiles (95, 99, max): 4ms, 4ms, 4ms
Using SSL version: OpenSSL 3.1.5 30 Jan 2024 (library: OpenSSL 3.1.5 30 Jan 2024)
Using Boost version: 1.81.0
Using CMake version: 3.29.3
Using MySQL version: 80036
Found MySQL Executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Compiled on: Windows
Worldserver listening connections on port %hu
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in ./Data/maps. Total size: 291014951 bytes
vmaps directory located in ./Data/vmaps. Total size: 658130721 bytes
mmaps directory located in ./Data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_11_15_00.sql
Latest CharacterDatabase update: 2024_11_15_00.sql
Latest WorldDatabase update: 2024_11_22_03.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules are enabled
```

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by Grimdhex** [comment]
Need to take care because some behaviour are voluntary. It look strange but for example guards of stormwind or others npcs in Elwyn have the same behaviour. I was checked on retail and classic, all is correct.

Need to check for box reported.

**Comment by TheSCREWEDSoftware** [comment]
Having patrols creatures that stop until restart doesn't sound something normal, I can go check same behaviour in retail or either cata classic or vanilla classic and make a video comparing. Sometimes npcs do stop for a bit, which is fine

**Comment by xeonatlas** [comment]
> Having patrols creatures that stop until restart doesn't sound something normal, I can go check same behaviour in retail or either cata classic or vanilla classic and make a video comparing. Sometimes npcs do stop for a bit, which is fine

Yes, it seems random, no adjustment of the and no adjustment of the `Creature.MovingStopTimeForPlayer` or `WaypointMovementStopTimeForPlayer` options makes any difference either.

But if this is actually intentional, it's such a strange decision.

**Comment by Grimdhex** [comment]
During my tests, I waited 5min without restart. It's maybe more longer. So need to investigate on it's really work.

**Comment by TheSCREWEDSoftware** [comment]
Sorry @Grimdhex i'm having a hard time understanding your comment. Did you encounter the issue?

**Comment by xeonatlas** [comment]
Thanks for confirming this, hopefully on the path to fix, I tried running my build in debug mode but no so sure this is actually going to throw errors of any kind.

**Comment by Grimdhex** [comment]
> Thanks for confirming this, hopefully on the path to fix, I tried running my build in debug mode but no so sure this is actually going to throw errors of any kind.

There are no errors or bugs. It's just that interacting with an NPC interrupt and finish their path. Need to implement a pause instead.

**Comment by LannyE** [comment]
I have been wrestling with this for Moon Priestess Amara for a few days.  Talk to her for her quests and she stops and never resumes her waypoint until server restart.  Funny thing I noticed is Trinitycore claims to have fixed this back in 2021, and we have the same code implemented in AZ that they implemented to fix theirs, but apparently it doesn't work.  Also, I tried setting the `InteractionPauseTimer` in the `creature_template_movement` table for her and it has no effect.  I tried messing around with the settings `Creature.MovingStopTimeForPlayer` and `WaypointMovementStopTimeForPlayer` in the `worldserver.conf `but they also seem to have no effect.  Anyways, just what I have noticed so far.

**Comment by Grimdhex** [comment]
> I have been wrestling with this for Moon Priestess Amara for a few days.  Talk to her for her quests and she stops and never resumes her waypoint until server restart.  Funny thing I noticed is Trinitycore claims to have fixed this back in 2021, and we have the same code implemented in AZ that they implemented to fix theirs, but apparently it doesn't work.  Also, I tried setting the `InteractionPauseTimer` in the `creature_template_movement` table for her and it has no effect.  I tried messing around with the settings `Creature.MovingStopTimeForPlayer` and `WaypointMovementStopTimeForPlayer` in the `worldserver.conf `but they also seem to have no effect.  Anyways, just what I have noticed so far.  

Do you have the link of this "fix" ? And yes, TC have the same issue.

**Comment by LannyE** [comment]
Here are the links to closed issues and PRs in Trinitycore that I was able to find.   I haven't spun up my old Trinitycore server but these links allude to them fixing the issue.  
https://github.com/TrinityCore/TrinityCore/issues/25647
https://github.com/TrinityCore/TrinityCore/pull/25880

This one also makes you think that it was working fine, and they had to fix/adjust it for escort quests: 
https://github.com/TrinityCore/TrinityCore/pull/24005

Hopefully some of these can help with the issue.  I just can't get Amara to move again after talking with her.  I wonder if it has to do with her using the `waypoint_data` table for her movement, don't know.  Like I said I have only been working on it for a few days which only amounts to about 1 hour in actual research and testing.   Thanks for looking at it.
