### ISSUE TITLE
[Zul'Aman] - Boss: Hex Lord Malacrass spell mechanics need to be adjusted.

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20740]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7553

Triage Notes: Read from my comment and below: https://github.com/chromiecraft/chromiecraft/issues/7553#issuecomment-2497970941

Original Post Below: 

---

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) schedule previous class's abilities from his [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) and cast them immediately after [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383).

https://github.com/user-attachments/assets/f843fa7f-d442-405d-bac1-4289eb8d1020

### Expected Blizzlike Behaviour

[Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) shouldn't use any abilities from the previous class after the timer for [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) is over

### Source

[TBC Classic](https://youtu.be/wPc2NNXfHNk?t=82) at 1:25 , [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) finishing channeling [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383) and cast [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) without using any of the previous class abilities (rogue) , and same at 2:05 and 2:45

### Steps to reproduce the problem

1. .go c id 24239
2. Fight [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) with 2 characters
3. Wait for [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) to use his first [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383) then Siphon Soul
4. Wait for [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) to use his second [Spirit Bolts](https://wowgaming.altervista.org/aowow/?spell=43383).
5. [Hex Lord Malacrass](https://wowgaming.altervista.org/aowow/?npc=24239) will use an abilities from the previous class before casting [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by TheSCREWEDSoftware** [comment]
- [Siphon Soul](https://wowgaming.altervista.org/aowow/?spell=43501) needs to have their animation adjusted. Should be attached to the Boss always (and not the point where it was casted from) to the player)

![image](https://github.com/user-attachments/assets/9b11b8c8-c9f4-4dc0-973d-1fb960e27b77)

Here's a video https://youtu.be/4At1FNloaRA?si=po6lzEJvw5Nlmkfw&t=1592 (26:32) from the current recording player you can see that the link stays attached at the boss and not the casting point

**Comment by TheSCREWEDSoftware** [comment]
While the Drain Power debuff and stack has been fixed it requires some more attention.

Mentioned here: https://github.com/azerothcore/azerothcore-wotlk/pull/20749#issuecomment-2500785153

---

It's working as intended, the only thing now is the timer of it needs to be fixed (not this issue) im pretty sure the player is not supposed to lose the debuff. He should cast it before ending. Example right now he has 14 stacks.

14 stacks / 2 people = 7 each (we have 6 each) because the player which gets the latest update on the stack has a change to lose (it's at 0 seconds remaing) of the debuff.

![image](https://github.com/user-attachments/assets/df1f687c-9900-4d14-84d8-c53bec0aff9c)

@amed80 do you any more insight on this?

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/20754
