### ISSUE TITLE
Feature: Configurable rest bones max experience

### ISSUE THREAD

**Issue by rudylhm** [azerothcore/azerothcore-wotlk#20759]
### Describe your feature request or suggestion in detail

My friends have unstable online times, and they want to accumulate more rest bonus XP while offline.

### Describe a possible solution to your feature or suggestion in detail

The code is in src/server/game/Entities/Player/Player.cpp, line 10229.
Could you make "rest_bonus_max" configurable?

**Comment by TheSCREWEDSoftware** [comment]
I wouldn't see a reason why this couldn't be implemented. Assuming isn't a blizzard limit client side. AzerothCore is always up for Pull Request than they get reviewed.

**Comment by Exitare** [comment]
I disagree. 
There should be an agreement whether this feature is acceptable before someone puts in the work in order to open a PR. 
No one likes to waste time.

**Comment by TheSCREWEDSoftware** [comment]
I wouldn't say it would go to waste their time. If wouldn't get approved they could turn in into a module :)

**Comment by Exitare** [comment]
Again strong disagreement.
It shouldn't be a problem or a big deal to agree whether something is acceptable to be merged into the main before someone works on it.

**Comment by Nyeriah** [comment]
If there's an objection to any given suggestion, the suggestions get closed with one of the maintainers justifying why it wouldn't be a good idea to accept it. Otherwise, it's implicit that every suggestion is valid and acceptable, being the actual implementation subject to review as every other PR is

**Comment by Kitzunu** [comment]
make a pr and @ me in discord and I'll review it for yah @Exitare

**Comment by Kitzunu** [comment]
It's a harmless implementation

**Comment by Exitare** [comment]
Thanks!
