### ISSUE TITLE
[Dungeon Heroic]  Pit of Saron sometimes monsters are double/triple stacking [$15]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2075]
[Dungeon Heroic]  Pit of Saron sometimes have double/triple stacked mobs

##### SMALL DESCRIPTION:

Heroic Pit of Saron sometimes monsters are double/triple stacking

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The monsters inside the dungeon does not double/triple stack

##### CURRENT BEHAVIOUR:

Sometimes running heroic Pit of Staron - Monsters double or triple stack
![pitsaron](https://user-images.githubusercontent.com/18629476/60795010-7c5e4100-a19d-11e9-837f-5be883aa1360.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a group to do Heroic Pit of Saron
2. Go inside

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by ArashGorge** [comment]
![WoWScrnShot_070819_144807](https://user-images.githubusercontent.com/52334511/60803672-0522b000-a191-11e9-82aa-81889dd6e145.jpg)

Tested , did not seen problem

**Comment by Selyria** [comment]
Was very simple the group just has to be too fast. And already it happened

https://youtu.be/T4OB2Usgn0I

**Comment by ArashGorge** [comment]
you should update your database and scripts, its ok ,i tested it so much times and didn't see problem

**Comment by Selyria** [comment]
> you should update your database and scripts, its ok ,i tested it so much times and didn't see problem

then they do something wrong the database and core are always up to date. Max 2 days old

**Comment by poszer** [comment]
> you should update your database and scripts, its ok ,i tested it so much times and didn't see problem

Nah, this issue exist

**Comment by ArashGorge** [comment]
Yes, Confirmed, if you are very fast and go ahead before enemy spawn it's going stuck
i'll fix it soon

**Comment by FALL1N1** [comment]
I couldn't reproduce it on latest with 5-6 attempts. Can anyone re-check?

**Comment by UltraNix** [comment]
This is okay - there should be two same groups of mobs there. No bug here.
