### ISSUE TITLE
[Achievements] dual talent

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2076]
Description: bug learn dual talent achievement.

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/6db0a438d9dff3d1fab5f904657ed281f5dee6c7

OS: windows 2017

MODULES:
Anticheat

@Winfidonarleyan 

https://github.com/azerothcore/azerothcore-wotlk/pull/1218

**Comment by FrancescoBorzi** [comment]
Can you please be more descriptive? It is not clear to me what the problem is

**Comment by wowmane** [comment]
if give dual talent, dont give achievement!

**Comment by Selyria** [comment]
So I just tested it and didn't have any problems. 
![Duall Spell](https://user-images.githubusercontent.com/179698/60866684-49618f00-a229-11e9-8deb-11a0d2b94910.jpg)

**Comment by poszer** [comment]
Thank you @Selyria . Closing this issue

**Comment by wowmane** [comment]
@Selyria 

WTF? 

What is your version :))?

**Comment by Selyria** [comment]
AzerothCore rev. ac8b20922bea+ 2019-07-08 11:27:52 +0200 (master branch) (Win64, Release)
