### ISSUE TITLE
[Zul'Aman] Boss: Zul'jin keeps targeting players and hitting (auto-attack) them during Eagle form 

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20773]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7570

Triage Notes: https://github.com/chromiecraft/chromiecraft/issues/7570#issuecomment-2508921236

Original Post Below: 

---

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Zul'jin](https://wowgaming.altervista.org/aowow/?npc=23863) keep targeting players and hitting them during Eagle form/phase 3

### Expected Blizzlike Behaviour

[Zul'jin](https://wowgaming.altervista.org/aowow/?npc=23863) should not target players during his Eagle form/phase 3 and shouldn't use auto attack for the whole phase

### Source

[Wotlk Classic Solo](https://youtu.be/lKlDl13T1O4?t=3112) Starting from 51:51 , [Zul'jin](https://wowgaming.altervista.org/aowow/?npc=23863) never target the paladin and never change his direction towards him or attacking him for the whole phase.

[TBC Classic](https://youtu.be/po_7Cn9vhqs?t=3001) Starting from 50:04 , [Zul'jin](https://wowgaming.altervista.org/aowow/?npc=23863) never target any player for the whole phase and doesn't deal any damage himself

### Steps to reproduce the problem

1. .go c id 23863
2. Fight and deal damage to [Zul'jin](https://wowgaming.altervista.org/aowow/?npc=23863) until he switch to eagle form at 60%
3. get into [Zul'jin](https://wowgaming.altervista.org/aowow/?npc=23863) melee range.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Auto attack issue fixed here: https://github.com/azerothcore/azerothcore-wotlk/pull/20805
