### ISSUE TITLE
Unable to cast (some?) spells "Invalid target"

### ISSUE THREAD

**Issue by GroodeeshPanj** [azerothcore/azerothcore-wotlk#20798]
### Current Behaviour

Targeting a mob and casting a spell, or trying to cast as spell on myself results in "invalid target" error message. I checked to make sure it wasn't an auto self cast issue and it wasn't.

I did a clean client test and it fails too. Verified on two different servers.

Spells tested: Fireball, Shadow Word: Pain, Lesser Heal, Power Word: Fortitude

### Expected Blizzlike Behaviour

Cast spells, do damage or healing

### Steps to reproduce the problem

1. Updated to latest rev
2. Target mob or yourself
3. Try to cast spell or heal yourself
4. "Invalid target"

### AC rev. hash/commit

AC> server debug
AC> AzerothCore rev. a4a278a0e7fc 2024-11-30 20:25:27 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 12 minute(s) 24 second(s)
Update time diff: 12ms. Last 500 diffs summary:
|- Mean: 12ms
|- Median: 12ms
|- Percentiles (95, 99, max): 13ms, 13ms, 13ms
Using SSL version: OpenSSL 3.0.13 30 Jan 2024 (library: OpenSSL 3.0.13 30 Jan 2024)
Using Boost version: 1.83.0
Using CMake version: 3.28.3
Using MySQL version: 80403
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.0-49-generic
Worldserver listening connections on port %u
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /home/mx/server/data/maps. Total size: 291014951 bytes
vmaps directory located in /home/mx/server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/mx/server/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_11_15_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: npc_services_00.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-eluna
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants
|- mod-solocraft

### Operating system

Ubuntu 24.04

### Custom changes or Modules

List of enabled modules:
|- mod-eluna
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants
|- mod-solocraft

**Comment by reactmay** [comment]
same problem
