### ISSUE TITLE
SQL Update issue

### ISSUE THREAD

**Issue by leewheel** [azerothcore/azerothcore-wotlk#20799]
### Current Behaviour

![image](https://github.com/user-attachments/assets/3cc5709b-ede3-4edc-b712-b6f524530e7a)

### Expected Blizzlike Behaviour

`UPDATE `acore_world`.`creature_loot_template` SET `MinCount` = 2, `MaxCount` = 3 WHERE `Entry` = 21212 AND `Item` = 34062 AND `Reference` = 34062 AND `GroupId` = 3;
UPDATE `acore_world`.`creature_loot_template` SET `MinCount` = 2, `MaxCount` = 3 WHERE `Entry` = 21215 AND `Item` = 34059 AND `Reference` = 34059 AND `GroupId` = 0;
UPDATE `acore_world`.`creature_loot_template` SET `MinCount` = 2, `MaxCount` = 3 WHERE `Entry` = 21214 AND `Item` = 34060 AND `Reference` = 34060 AND `GroupId` = 0;`

### Source

UPDATE `acore_world`.`creature_loot_template` SET `MinCount` = 2, `MaxCount` = 3 WHERE `Entry` = 21212 AND `Item` = 34062 AND `Reference` = 34062 AND `GroupId` = 3;
UPDATE `acore_world`.`creature_loot_template` SET `MinCount` = 2, `MaxCount` = 3 WHERE `Entry` = 21215 AND `Item` = 34059 AND `Reference` = 34059 AND `GroupId` = 0;
UPDATE `acore_world`.`creature_loot_template` SET `MinCount` = 2, `MaxCount` = 3 WHERE `Entry` = 21214 AND `Item` = 34060 AND `Reference` = 34060 AND `GroupId` = 0;

### Steps to reproduce the problem

Run the worldserver.exe, just read the log

### AC rev. hash/commit

Sory, Server crashed,so no hash can gei, but i imported This two days update

### Operating system

Windows 10

**Comment by sudlud** [comment]
can't reproduce on fc9e7309742c86de6aba3791d2cb2ff1ce910080

**Comment by sudlud** [comment]
also the commit hash is the firt message when starting the worldserver, can you please provide yours

**Comment by Kitzunu** [comment]
Can't reproduce
