### ISSUE TITLE
[chainquest] shadwomoon valley

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#208]
**Description**: durin the chain quest of shadowmoon valley The Altar of Damnation the npc Spirit of Ar'tor is invisble for the player (in gm on i see).
The "problem" start after the quest Demonic Crystal Prisons

Chainquest: http://wowwiki.wikia.com/wiki/Shadowmoon_Valley_quests
Npc http://www.wowhead.com/npc=21318/spirit-of-artor

**Current behaviour**: i can't see the npc and i can't take the quest

**Expected behaviour**: i see the npc that give me the quest to continue the chain

**Steps to reproduce the problem**: complete all quest to (or add complete and reward) Demonic Crystal Prisons and the npc don't appear or is visible for the next quest

**Comment by starrheld** [comment]
#382
