### ISSUE TITLE
[DK Starting Area] Missing random npcs spawn in phase 4.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20803]
### Current Behaviour

In dk starting area (phase 4) npcs with waypoints or Random in radius, when killed respawn as they were (same npc id/Guid).

### Expected Blizzlike Behaviour

When an npc with a waypoint is killed, in many cases there is a 50% chance that another npc will spawn in its place, following the same path.
The npcs in this case are either Scarlet Captains or Scarlet Preachers.

Examples:
![Evidence 1](https://github.com/user-attachments/assets/2b7620c9-1b49-442b-a5ca-20c5bb0585af)
![Evidence 2](https://github.com/user-attachments/assets/c32facc6-ba0f-4323-aaaf-bfaec30547d6)
![Evidence 3](https://github.com/user-attachments/assets/c8c83281-93a3-4436-a4c7-5c6a89bbe8d3)
![Evidence 4](https://github.com/user-attachments/assets/790248dc-ffcd-45ea-8052-c29837f965f1)
![Evidence 5](https://github.com/user-attachments/assets/7f644818-5e49-41d2-bea6-75a961cd7459)
![Evidence 6](https://github.com/user-attachments/assets/bdb23e4a-6e0b-4a1f-b449-42109ba76381)
![Evidence 7](https://github.com/user-attachments/assets/a3707045-e705-4df1-93b2-e412b294a44c)
![Evidence 8](https://github.com/user-attachments/assets/8a1253c2-04a1-4e07-8a62-613f94972d9e)
![evidence 9](https://github.com/user-attachments/assets/4993b9c0-d1f1-4bad-9456-39eb969ddaa5)

The Npcs with Movement Type = 1 (Random in radius) have the same mechanics, but in this case they can respawn as a Scarlet Preacher, a Scarlet Crusader or a Scarlet Marksman.

### Source

WoW Cata Classic Live

### Steps to reproduce the problem

1. You must have an active account on WoW Cata Classic Live (Cata ptr servers are currently off-line).
2. Make a dk.
3. Do the chain quest until The Crypt of Remembrance quest.
4. Kill npcs with waypoint and random in radius inside New Avalon.

### Extra Notes

Probably Scarlet Peasant have a similar mechanics (phase 1). 
Related [issue](https://github.com/azerothcore/azerothcore-wotlk/issues/20744).

### AC rev. hash/commit

[10a7944](https://github.com/azerothcore/azerothcore-wotlk/commit/10a79441b6c0cb41d8a6237083f8c59866195a42)

### Operating system

Windows 11

**Comment by TheSCREWEDSoftware** [comment]
Took me a while to see the text you had in the screenshots, used in the screenshot (at least in the phone)

**Comment by Rorschach91** [comment]
> Took me a while to see the text you had in the screenshots, used in the screenshot (at least in the phone)

Lol, you can see it better on PC.
