### ISSUE TITLE
swiftmane cant attack players?

### ISSUE THREAD

**Issue by Doc-Huang** [azerothcore/azerothcore-wotlk#20816]
### Current Behaviour

The swiftmane with ID 5831 in The Barrens will not counterattack the players after be attacked, but will continue to run along the predetermined path. I guess there is a problem with the second encoding, please modify it.
![image](https://github.com/user-attachments/assets/b84d3615-e498-425b-809d-3e0d45851b9f)
![image](https://github.com/user-attachments/assets/8bc78f86-07b1-4b0a-8c2c-7e5d3bdb43e4)

### Expected Blizzlike Behaviour

All the AZ server have this bug,please fix it and make it normal.

### Steps to reproduce the problem

NONE

### AC rev. hash/commit

b45a3fcac97b

### Operating system

win11 x64

**Comment by TheSCREWEDSoftware** [comment]
Please provide your Revision of AC.

![image](https://github.com/user-attachments/assets/d13a9c36-8c03-41b5-bbe7-0d00637d9932)

**Comment by Doc-Huang** [comment]
> Please provide your Revision of AC
I realy dont know,I just find BUG,cant package game。(─.─|||

**Comment by TheSCREWEDSoftware** [comment]
Update your core than attempt to replicate the issue. If you able to replicate the issue be free to re-open this or make a new one refering this.

**Comment by Doc-Huang** [comment]
> Update your core than attempt to replicate the issue. If you able to replicate the issue be free to re-open this or make a new one refering this.

Okay, this issue persists regardless of the new or old versions
