### ISSUE TITLE
 Raid Alternate Difficulties for SharedNormalHeroicId

### ISSUE THREAD

**Issue by manstfu** [azerothcore/azerothcore-wotlk#20826]
### Current Behaviour

Changing the raid difficulty from directly from inside the instance is not possible; the entire raid must leave the instance, switch the difficulty to Heroic, and then re-enter.

### Expected Blizzlike Behaviour

**Only IF `Instance.SharedNormalHeroicId = 1`**

They can mix difficulties within the same raid. For example, they might defeat some bosses on Normal and others on Heroic. This is possible if:

- All players in the raid have already defeated the Lich King on Normal difficulty.
- There’s no shared cooldown between Normal and Heroic modes, meaning you can switch freely between them.

**Changing Difficulty**: Adjusting the difficulty setting during the raid doesn’t affect the entire instance—only the boss fights. Trash mobs remain the same regardless of mode.

### Source

https://web.archive.org/web/20091107192305/http://forums.worldofwarcraft.com/thread.html?topicId=20677335705&sid=1

https://wowpedia.fandom.com/wiki/Dungeon_difficulty
![image](https://github.com/user-attachments/assets/4e6f958a-7f4c-48e7-9d23-05a011441b19)

### Steps to reproduce the problem

Create a raid group
Go to Lord Marrowgar
Change Raid Difficulty Mode

### AC rev. hash/commit

rev. 10a79441b6c0+

### Operating system

Debian 12

**Comment by manstfu** [comment]
Works as excepted now, all players must have achievement [4530](https://www.wowhead.com/achievement=4530/the-frozen-throne-10-player) unlocked!

**Comment by TheSCREWEDSoftware** [comment]
> Works as excepted now, all players must have achievement [4530](https://www.wowhead.com/achievement=4530/the-frozen-throne-10-player) unlocked!

Is this with our without running the `/script SetRaidDifficulty(2)` manually?

![image](https://github.com/user-attachments/assets/7b52157d-0101-4633-9fac-524dada8991e)

**Comment by manstfu** [comment]
> > Works as excepted now, all players must have achievement [4530](https://www.wowhead.com/achievement=4530/the-frozen-throne-10-player) unlocked!
> 
> Is this with our without running the `/script SetRaidDifficulty(2)` manually?
> 
> ![image](https://private-user-images.githubusercontent.com/16946913/393504859-7b52157d-0101-4633-9fac-524dada8991e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzAyMTUsIm5iZiI6MTczMzU2OTkxNSwicGF0aCI6Ii8xNjk0NjkxMy8zOTM1MDQ4NTktN2I1MjE1N2QtMDEwMS00NjMzLTlmYWMtNTI0ZGFkYTg5OTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDExMTE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYWJjNTNjZTY3YWYwMjY5MDkxMGExYzUzNGIyNTZiMWUwYTYzYWE4YjJkZmU3YTI5ZjI3OWMzYTM3NDk3ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gciSlJiPL4I9BPuj8JNzcZqL_rsO0-VY0A5G3JG3owk)

yes, it works on different realms, it is fixed now!
