### ISSUE TITLE
Heroic Reset not working?

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2082]
Heroic Reset not working?

##### SMALL DESCRIPTION:

Heroic Reset not working even thou calendar shows the time.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Heroics should reset, what calendar says

##### CURRENT BEHAVIOUR:

Heroics not resetting for some reason:
![resetbug](https://user-images.githubusercontent.com/18629476/61023131-3098db00-a3db-11e9-9b76-a77ee542143d.jpg)

Edit: i restarted server and now it all changed:
![afterreset](https://user-images.githubusercontent.com/18629476/61023671-7191ef00-a3dd-11e9-9038-fed2603e8e61.jpg)

Server/Realm time is GMT+8

Didn't touch the worldserver.conf setting:
//Instance.ResetTimeHour
Instance.ResetTimeHour = 4

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do heroics
2. Wait for it to reset (check calendar)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by spinzaku** [comment]
Reset finally on 4:00pm.

I will close this and re-open in the future if it happens again.

**Comment by milestorme** [comment]
Yeah I have mine set to 2 am but it says 11:59 not sure why
