### ISSUE TITLE
[Zul'Aman]  No any item can loot when click summon objects

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#20847]
### Current Behaviour

    the 4 object will be give, where diag with the summon NPC, but nothing in the packet object.
    GO_HARKORS_SATCHEL                  = 187021,
    GO_TANZARS_TRUNK                    = 186648,
    GO_ASHLIS_BAG                       = 186672,
    GO_KRAZS_PACKAGE                    = 186667,

### Expected Blizzlike Behaviour

will give a item for loot

### Steps to reproduce the problem

go to Zul'Aman and kill the boss in time, and try get the item form summon npc.

### AC rev. hash/commit

AzerothCore rev. 6cd9f953c0c4 2024-12-02 23:05:43 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 13 second(s)
Update time diff: 100ms. Last 70 diffs summary:
|- Mean: 100ms
|- Median: 100ms
|- Percentiles (95, 99, max): 100ms, 114ms, 143ms
Using SSL version: OpenSSL 3.0.15 3 Sep 2024 (library: OpenSSL 3.0.15 3 Sep 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80403
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-4-pve
Worldserver listening connections on port 54347
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_11_15_00.sql
Latest CharacterDatabase update: 2024_11_15_00.sql
Latest WorldDatabase update: mod-zone-difficult.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-difficult
|- mod-eluna

### Operating system

Debian 12 with PVE

**Comment by sudlud** [comment]
#20529
