### ISSUE TITLE
[QUEST] Defending Wyrmrest Temple

### ISSUE THREAD

**Issue by PadreWoW** [azerothcore/azerothcore-wotlk#20865]
### Current Behaviour

wymrest defenders can't fly up and down

### Expected Blizzlike Behaviour

When you fly on a defender, it should be controlled like an air mount - it should fly not only forward-backward-right-left but also up and down

### Steps to reproduce the problem

1) Take quest Defending Wyrmrest Temple
2) Take one of the wymrest defenders on the second floor - same floor that you picked up the quest.
3) Try to go up and down

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/85d8c99b494a90823fe50974cf0cd297d3ae2e14

### Operating system

win 10

### Custom changes or Modules

mod_anticheat
mod_transmog
mod_learnspells

**Comment by TheSCREWEDSoftware** [comment]
Are you able to provide a video of the quest as source?

**Comment by PadreWoW** [comment]
How can i show on video that dragon can't fly up or down?

**Comment by Nyeriah** [comment]
https://github.com/user-attachments/assets/d2ae7f04-c144-477b-a745-2a6c6e606fde

works fine
