### ISSUE TITLE
[Tempest Keep] Boss: Kael'thas Sunstrider Phase 2 to Phase 3 timer is wrong

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20877]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7592

Triage Notes: Not mine, https://github.com/chromiecraft/chromiecraft/issues/7592#issuecomment-2525116410

Original Post Below: 

---

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

Generic

### Current Behaviour

1. The damage from Grand Astromancer Capernian is doing much higher than it should be if this is the "nerfed" version. She is now doing 7,000 damage fireballs
2. The transition from phase 2 (weapon phase) to phase 3 (four advisor stage) is about 1m30s longer than it should be
3. The health of advisors in phase 3 is doubled from what it should be.

### Expected Blizzlike Behaviour

1. The damage should be significantly lower if this is the nerfed version
2. The transition from phase 2 to phase 3 should be 2 minutes after weapon spawn
3. The health of the four advisors should be the same in phase 1

### Source

1. I do not have actual source as I am not sure how the tuning should be, but 7k fireball is abnormally high for a nerfed version
2. This TBC guide references a 2 minute phase timer between weapon spawn to advisor resurrection https://www.wowhead.com/tbc/guide/kaelthas-sunstrider-the-eye-tempest-keep-strategy-burning-crusade-classic
3. Many video PoV shows advisor health in P1 and P3 is the same: example: https://www.youtube.com/watch?v=3e19JC9nJ9A

### Steps to reproduce the problem

1. Engage Kael'thas sunstrider in Tempest Keep
2. Go through phase 1, 2 and 3
3. Observe damage from Capernian
4. Observe health of four advisors in phase 1 and then compare in phase 3
![image](https://github.com/user-attachments/assets/9d796ac0-ab84-4f5b-a830-433ca820653c)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sogladev** [comment]
1. Astromancer is using ID - 36971 Fireball, is this not the correct spell?
```
Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 5524 to 7475 Bonus = 1.00
Targets (6, 0) (TARGET_UNIT_TARGET_ENEMY, NO_TARGET)
```
damage on a 70 character without talents, looks ok to me 
![astromancer_fireball_nomods](https://github.com/user-attachments/assets/a6416667-9ab4-4a6a-a25c-c7c3df6142c6)

2. fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/20914
3. hp values look correct to me:
phase 3 doubles advisors' hp. Resurrection applies a %hp modifier. https://wowgaming.altervista.org/aowow/?spell=36450
```
Astromancer 
pre-resurrection: 134k
post-resurrection: 268k (x2)
```
