### ISSUE TITLE
[Zul'Aman] Amani'shi Warrior missing abilities.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20886]
Original CC Report: https://github.com/chromiecraft/chromiecraft/issues/7606#issue-2724988836

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

[Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225) missing abilities

### Expected Blizzlike Behaviour

[Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225) should use [Charge](https://wowgaming.altervista.org/aowow/?spell=43519)

### Source

Wowhead [Amani'shi Warrior](https://www.wowhead.com/wotlk/npc=24225/amanishi-warrior#abilities;mode:n10)

Wowpedia [Amani'shi Warrior](https://wowpedia.fandom.com/wiki/Amani'shi_Warrior#Abilities)
![image](https://github.com/user-attachments/assets/734e4908-f66d-4d42-803f-26ef6ff5ada7)

[TBC Classic](https://youtu.be/4_QRZ8lx7H8?t=7445) at 2:04:07 , [Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225) uses [Charge](https://wowgaming.altervista.org/aowow/?spell=43519) on the shaman

### Steps to reproduce the problem

1. .go c id 24175
2. start the gauntlet event
3. wait for [Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225) to spawn
4. .mod speed 2 and start running away from [Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225)

### Extra Notes

Many sources have [Kick](https://wowgaming.altervista.org/aowow/?spell=43518) as an ability listed for [Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225) but hard to look for it on videos other than [Amani'shi Warrior](https://wowgaming.altervista.org/aowow/?npc=24225) doing the kick animation like in this video [Wotlk Classic Prepatch](https://youtu.be/KyPDiYevouU?t=292) at 4:54 and this video [TBC Classic](https://youtu.be/2QjPyAmgWsU?t=731) at 12:12

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Grimdhex** [comment]
Do we have an idea of timers from videos ? Because for now it's impossible to "estimate" it as they are no longer TBC/Woltk server. Or need to wait one/two years before that tbc anniversary server open and reach ZA.

**Comment by Rorschach91** [comment]
> Do we have an idea of timers from videos ? Because for now it's impossible to "estimate" it as they are no longer TBC/Woltk server. Or need to wait one/two years before that tbc anniversary server open and reach ZA.

No fucking idea. There are two ways:
1) Someone has the sniffs from TBC Classic.
2) We can see which npcs have these abilties in their smartAI, and then correct them a bit by watching gameplay videos.

**Comment by Nyeriah** [comment]
It's fine if the timers are reasonable, as this is something we hardly will ever be able to confirm, and timers are almost impossible to get 100% accurately anyway
