### ISSUE TITLE
[Quest] Report to Steeljaw's Caravan - Can't turn in quest

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2089]
[Quest] Report to Steeljaw's Caravan - Can't turn in quest

##### SMALL DESCRIPTION:

Report to Steeljaw's Caravan - Can't turn in quest

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to turn in the quest:  https://www.youtube.com/watch?v=Wsk6p3OwbJk

##### CURRENT BEHAVIOUR:

Grunt Ragefist just ignores and can't turn in quest
![report](https://user-images.githubusercontent.com/18629476/61167037-e9d9eb00-a56a-11e9-91c1-50c5a2505de3.png)

Edit:
I killed Grunt Ragefist and respawned her and now i can turn in:
![respawn](https://user-images.githubusercontent.com/18629476/61167092-cfecd800-a56b-11e9-8cd5-504b3528e2d1.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get quest https://www.wowhead.com/quest=11591/report-to-steeljaws-caravan
1. or .quest add 11591
2. Fly/go to Grunt Ragefist
3. Try to turn in quest

##### EXTRA NOTES:

Maybe related to this? -> https://github.com/dalaranwow/dalaran-wow/issues/2601#issuecomment-118666743 

> The quest itself works, the problem is that the npcs near the Caravan gets stuck after someone already completed the quest We Strike Back (I think its called). There are a few solutions to this problem at the moment:
> 
> Get a GM to reset the NPCs
> Have a member of the Alliance (If you know any) kill the NPCs and wait for them to respawn
> Try pulling a few mobs near the NPCs and they get in combat, keep chainpulling till they all die and wait for the respawn

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Try this please:

```sql
-- Generated by Event Horizon - SAI Editor (http://devsource-eventhorizon.tk/)

-- Grunt Ragefist
SET @ENTRY := 25336;
SET @SOURCETYPE := 0;

DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=@SOURCETYPE;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY LIMIT 1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES 
(@ENTRY,@SOURCETYPE,0,0,38,0,100,0,1,1,0,0,80,2533600,2,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Grunt Ragefist - On Data Set 1 1 - Run Script"),
(@ENTRY,@SOURCETYPE,1,2,38,0,100,0,2,2,0,0,59,1,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Grunt Ragefist - On Data Set 2 2 - Set Run on"),
(@ENTRY,@SOURCETYPE,2,0,61,0,100,0,0,0,0,0,29,2,3,0,0,0,0,19,25335,0,0,0.0,0.0,0.0,0.0,"Grunt Ragefist - On Data Set 2 2 - Follow Longrunner Proudhoof"),
(@ENTRY,@SOURCETYPE,3,0,38,0,100,0,3,3,0,0,41,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Grunt Ragefist - On Data Set 3 3 - Despawn"),
(@ENTRY,@SOURCETYPE,4,0,38,0,100,0,4,4,0,0,101,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Grunt Ragefist - On Data Set 4 4 - Set Home Position"),
(@ENTRY,@SOURCETYPE,5,0,1,0,100,0,0,0,2000,2000,101,0,0,0,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,"Grunt Ragefist - OOC - Set Home Position");
```

**Comment by Helias** [comment]
Can't reproduce the bug, I tested it consecutively with 2 horde characters in GM Off.
