### ISSUE TITLE
[QUEST] Convocation at Zol'Heb

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#209]
**Description**: In this quest you have to use a item in a portal summon
QUEST: http://www.wowhead.com/quest=12730/convocation-at-zolheb
ITEM: http://www.wowhead.com/item=39566/prophet-of-akali-convocation
NPC to summon: http://www.wowhead.com/npc=29028/prophet-of-akali

**Current behaviour**: In the right place the game tell "you can't use now"

**Expected behaviour**: The quest item work and you can kill the NPC of the quest

**Steps to reproduce the problem**: Go in te correct place, use the item and it doesn't work

**Comment by HeartWell** [comment]
dublicate https://github.com/azerothcore/azerothcore-wotlk/issues/34

**Comment by HeartWell** [comment]
Maybe close?
