### ISSUE TITLE
Can someone please tell me where the spellpower modifier is stored for Mana Shield???

### ISSUE THREAD

**Issue by joshjoshajosh** [azerothcore/azerothcore-wotlk#20904]
### Describe your feature request or suggestion in detail

I've literally looked everywhere. Every table, every DBC, please tell me what I've missed, I know I'm looking for a number around ~80-81 but I cannot find it anywhere.

**Comment by joshjoshajosh** [comment]
Places where it's supposed to be but isn't:

spell.dbc
column 98 (EffectAmplitude1): 0
column 229 (EffectBonusMultiplier1): 0

acore_world.spell_bonus_data
no entries for any rank of the spell.

overridespelldata_dbc
empty table

spell_dbc
no mana shield entry

**Comment by blinkysc** [comment]
Think maybe azerothcore-wotlk/src/server/scripts/Spells/spell_mage.cpp

```class spell_mage_mana_shield : public spell_mage_incanters_absorbtion_base_AuraScript
{
    PrepareAuraScript(spell_mage_mana_shield);

    void CalculateAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
    {
        canBeRecalculated = false;
        if (Unit* caster = GetCaster())
        {
            // +80.53% from sp bonus
            float bonus = 0.8053f;

            bonus *= caster->SpellBaseDamageBonusDone(GetSpellInfo()->GetSchoolMask());
            bonus *= caster->CalculateLevelPenalty(GetSpellInfo());

            amount += int32(bonus);
        }
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mage_mana_shield::CalculateAmount, EFFECT_0, SPELL_AURA_MANA_SHIELD);
        AfterEffectManaShield += AuraEffectManaShieldFn(spell_mage_mana_shield::Trigger, EFFECT_0);
    }
};```

Also might be better to ask questions using the discord channel https://discord.com/invite/A3skHCGw?utm_source=Discord%20Widget&utm_medium=Connect

**Comment by joshjoshajosh** [comment]
Thanks for the reply and the invite. Dam that sucks, does this mean I can't change it without recompiling the server? Or can I add an override entry somewhere for it?

**Comment by blinkysc** [comment]
You'll have to recompile

**Comment by TheSCREWEDSoftware** [comment]
This is not the proper channel to make questions. Use the Link provided by Blinky or the one below, and use either the quick-questions or support-forum. 

Discord Perma Link: https://discord.com/invite/gkt4y2x

**Comment by joshjoshajosh** [comment]
The disadvantage of discord is that if someone has the same question, they find it on google.

**Comment by TheSCREWEDSoftware** [comment]
Stackoverflow is the proper place if you want ask and keep your question publicly without needing to be in discord

https://stackoverflow.com/questions/tagged/azerothcore

**Comment by joshjoshajosh** [comment]
Thank you
