### ISSUE TITLE
ACE00046: Used MySQL library version (8.0.39 id 800xx does not match the version id used to compile AzerothCore (id 800xx)

### ISSUE THREAD

**Issue by icelament** [azerothcore/azerothcore-wotlk#20924]
### Current Behaviour

The current docker-compose.yml has the outdated tag value: image: mysql:8.3

the latest image: acore/ac-wotlk-worldserver:${DOCKER_IMAGE_TAG:-master} uses mysql 8.4.
 
This causes issue when starting WorldServer with docker compose up -d --build

(https://github.com/azerothcore/azerothcore-wotlk/blob/35f316b1a6cd63cde9c0ee65aaaf89b5543d1f63/docker-compose.yml#L11C5-L11C18)

### Expected Blizzlike Behaviour

libmysql.dll version should match.

### Steps to reproduce the problem

1) Follow the guide: https://www.azerothcore.org/wiki/install-with-docker
2) Run: docker compose up -d --build
3) Run: docker attach ac-worldserver to view the error message.

### Extra Notes

Update mysql:8.3 to mysql:8.4 should fix the issue.

### AC rev. hash/commit

[35f316b](https://github.com/azerothcore/azerothcore-wotlk/commit/35f316b1a6cd63cde9c0ee65aaaf89b5543d1f63)

### Operating system

debian12

**Comment by sudlud** [comment]
@michaeldelago
