### ISSUE TITLE
authserver

### ISSUE THREAD

**Issue by Neovinger** [azerothcore/azerothcore-wotlk#2092]
Got a problem with the authserver!! 

When starting the authserver it hangs up and can't find the error. 

Hope you can help me with it 

Sry if it should be in the wrong range since I post for the first time such a contribution here

[https://www.bilder-upload.eu/bild-76b748-1563014730.png.html](url)

**Comment by FrancescoBorzi** [comment]
@Neovinger please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
