### ISSUE TITLE
Quest Ending Their World an event should start [$30]

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#2094]
##### SMALL DESCRIPTION:
After you have completed the quest Ending Their World an event should start

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After you have completed the quest Ending Their World an event should start

https://youtu.be/EJWnyEpUTms?t=590

After submitting Ending Their World, the quest should be 	
Start The Unwritten Prophecy and you only need it when Velender almost stands behind you

##### CURRENT BEHAVIOUR:

When you give Ending Their World away, nothing happens after that.

##### STEPS TO REPRODUCE THE PROBLEM:
Give yourself the Quest 9759
.Quest Complet 9759
.go c 63379
Submit quest

##### BRANCH(ES):
Master

##### AC HASH/COMMIT:
AzerothCore rev. c47391bc94a1+ 2019-07-13 06:08:10 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
mod-transmog
mod-world-chat

**Comment by w5860363** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18642 
https://github.com/TrinityCore/TrinityCore/pull/14149/files
