### ISSUE TITLE
[TBC - NPC] Aether Rays are not stunned while being wrangled.

### ISSUE THREAD

**Issue by Cythisiax** [azerothcore/azerothcore-wotlk#20949]
What client do you play on?
enUS

Faction
Both

Content Phase:
70

Current Behaviour
Currently while using the rope on Aether Rays, they will still attack you.

Expected Blizzlike Behaviour
They should stop doing actions while being wrangled.

Source
Wrath Classic

Steps to reproduce the problem
Do the Wrangle Aether Rays quest.
Observe their attacking you while you wrangle them.
Extra Notes

https://streamable.com/24gg5i - replication
https://www.youtube.com/watch?v=f-qlxpSFyn8 - source

AC rev. hash/commit
https://github.com/azerothcore/azerothcore-wotlk/commit/2923a4aa43d0afdee369dc5c1638f309c343de01

Operating system
Ubuntu 20.04 / Windows

Modules
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
[lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
[lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft
https://github.com/chromiecraft/chromiecraft/issues/6399

**Comment by Rorschach91** [comment]
@Cythisiax are you able to add the labels on AC repositary?

**Comment by Cythisiax** [comment]
> @Cythisiax are you able to add the labels on AC repositary?

Yes, but not sure which labels are to be applied with AC repo with ones linked from CC

**Comment by Rorschach91** [comment]
> > @Cythisiax are you able to add the labels on AC repositary?
> 
> Yes, but not sure which labels are to be applied with AC repo with ones linked from CC

In this case you can use label "70" and "Confirmed".

**Comment by Nyeriah** [comment]
Please keep the issue link from CC on the top of the report, so we don't have to search for it when linking on the PR later, thanks!
