### ISSUE TITLE
Orb of Translocation (Undercity to Silvermoon) not working

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2096]
Orb of Translocation (Undercity to Silvermoon) not working

##### SMALL DESCRIPTION:

Nothing happens when i click on Orb of Translocation (Undercity to Silvermoon)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Clickign on Orb of translocation in Undercity should teleport you to Silvermoon

##### CURRENT BEHAVIOUR:

![WoWScrnShot_071519_180445](https://user-images.githubusercontent.com/18629476/61209320-fd807f80-a72b-11e9-89d0-6309686402c7.jpg)
Nothing happens when i click on Orb of Translocation (Undercity to Silvermoon)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to undercity
2. Find Orb of Translocation on the West Side
3. Try right click

##### EXTRA NOTES:

maybe related to
https://github.com/TrinityCore/TrinityCore/issues/5935

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5aa9266cf3cc49e8dc0852c19ec161b4c6df71d8

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by wowmane** [comment]
Confirm

**Comment by Stoabrogga** [comment]
Cannot confirm. Translocation from Undercity to Silvermoon is working as well as from Silvermoon to Undercity. Used a fresh compilation of commit 7b105b75dd2afda008c6a0b6f0fa42e806be1fd8 and a fresh DB.

**Comment by poszer** [comment]
Can't confirm. Both Translocation's working fine for me. Closing this issue

**Comment by FrancescoBorzi** [comment]
@wowmane please do not confirm issues or fixes without actually testing them, otherwise you will be banned.

**Comment by spinzaku** [comment]
Silvermoon City -> Undercity works for me
Undercity -> Silvermoon City doesn't work for me.

But i will be updating my server later, i also run untouched core btw.
