### ISSUE TITLE
Mob Loot Tables - Heavy Stone

### ISSUE THREAD

**Issue by Cythisiax** [azerothcore/azerothcore-wotlk#20967]
What client do you play on?
enUS

Faction
Alliance

Content Phase:
30-39

Current Behaviour
Heavy Stone is not dropping from any of the mobs that you'd normally kill to farm heavy stone
https://www.wowhead.com/wotlk/item=2838/heavy-stone#dropped-by;0-11-3-10+1
https://wowgaming.altervista.org/aowow/?item=2838#dropped-by:0-8+1

Expected Blizzlike Behaviour
https://wowgaming.altervista.org/aowow/?npc=2359
https://wowgaming.altervista.org/aowow/?npc=4120
https://wowgaming.altervista.org/aowow/?npc=6073
should all have a ~25% chance to drop Heavy Stone

Source
https://www.wowhead.com/wotlk/item=2838/heavy-stone#dropped-by;0-11-3-10+1

Steps to reproduce the problem
attempt killing:
.go creature id 2359
.go creature id 4120
.go creature id 6073

Extra Notes

https://wowgaming.altervista.org/aowow/?npc=2359#drops - Does not have "Heavy Stone" in drop tables from source. But according to https://www.wowhead.com/wotlk/npc=2359/elemental-slave#drops tables and comments it does.

DB does not have Heavy Stone 2838 in loot table.

https://www.wowhead.com/wotlk/npc=4120/thundering-boulderkin - per wowhead also has Heavy Stone.
https://www.wowhead.com/wotlk/npc=6073/searing-infernal - Should have Heavy Stone per Wowhead as well.

DB does not show Heavy Stone in either of their loot tables.

AC rev. hash/commit
https://github.com/azerothcore/azerothcore-wotlk/commit/a23b13defea47fa806b85074d108eaf19561ee50

Operating system
Ubuntu 22.04

Modules
[mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
[mod-anticheat](https://github.com/azerothcore/mod-anticheat)
[mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
[mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
[mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
[mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
[mod-cfbg](https://github.com/azerothcore/mod-cfbg)
[mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
[mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
[mod-costumes](https://github.com/azerothcore/mod-costumes)
[mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
[mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
[mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
[mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
[mod-eluna](https://github.com/azerothcore/mod-eluna)
[mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
[mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
[mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
[mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
[mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
[mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
[mod-progression-system](https://github.com/azerothcore/mod-progression-system)
[mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
[mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
[mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
[mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
[mod-transmog](https://github.com/azerothcore/mod-transmog)
[mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
[mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
[lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
[lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
[lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
[lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
[lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
[lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
[lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
[lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
Customizations
None

Server
ChromieCraft
https://github.com/chromiecraft/chromiecraft/issues/7575

**Comment by Exitare** [comment]
I can confirm this, for the 3 examples provided
