### ISSUE TITLE
Horde and Alliance can talk to each other using /e command [$25]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2099]
Horde and Alliance can talk to each other using /e command

##### SMALL DESCRIPTION:

Horde and Alliance can talk to each other using /e command

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You shouldn't be able to understand each other, even using /e command

##### CURRENT BEHAVIOUR:

![duel](https://user-images.githubusercontent.com/18629476/61245953-48c47d80-a780-11e9-8bb5-5685f64f7a1d.png)
They had a duel
after duel Assok and Seran could completely understand each other using
/e gg hahah (good game)
/e wg sami (going to wintergrasp)
/e wp (well played)
/e sige2 (ok)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Talk to any opposite faction
2. use /e messagehere

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5aa9266

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by solidmaxtor** [comment]
confirm here use everytime... it will be sad to remove it HAHAHA
do it please.

**Comment by spinzaku** [comment]
with @poszer Emote was using this:

>     std::string _text(text);
>     sScriptMgr->OnPlayerChat(this, CHAT_MSG_EMOTE, LANG_UNIVERSAL, _text);
> #ifdef ELUNA
>     if (!sEluna->OnChat(this, CHAT_MSG_EMOTE, LANG_UNIVERSAL, _text))
>         return;

We tried changing LANG_UNIVERSAL to LANG_COMMON still didn't fix this

**Comment by FrancescoBorzi** [comment]
Maybe we should make this configurable. Some RPG servers might want to keep this feature for role playing game.

**Comment by poszer** [comment]
> Maybe we should make this configurable. Some RPG servers might want to keep this feature for role playing game.

Nah. Doesnt needed. This should work for normal emotes (/laugh/welcome/cry) and things like that. But using it for in game communication/e Hello shin how are you its totally incorrect

**Comment by FrancescoBorzi** [comment]
@poszer Of course, I did not mean to use it for normal communication like `Hello shin how are you` but for the real purpose of the `/e` function:

`/e shakes his hands`
`/e looks in the sky`

It is supposed to describe actions of your own character. Of course this can easily be abused so most of server will want to disabled it, but servers that do [role-playing game](https://en.wikipedia.org/wiki/Role-playing_game) would probably want to keep it.

**Comment by talamortis** [comment]
me & @poszer  have solved this. He will do PR with fixes.

**Comment by Ali-Khazaee** [comment]
@andoys Can you test this https://github.com/Ali-Khazaee/azerothcore-wotlk/commit/fefec5e5ddc23124684813fb69dbb4d9a1713bc3 ?

**Comment by andoys** [comment]
Confirmed fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/2117

**Comment by FrancescoBorzi** [comment]
I have claimed the bounty on behalf of @Stoabrogga  who wants to re-invest this money on AC.
