### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by ShinDarth** [azerothcore/azerothcore-wotlk#21]
The license of this project should be set to GNU GPL, as MaNGOS and TrinityCore were.

Also we should restore the credits to MaNGOS and TrinityCore in source file headers:

https://github.com/AzerothCore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L2

**Comment by Yehonal** [comment]
I would avoid to use old style header to licensing files. I think we just
need to add a LICENSE file for root folder, mostly related to src
directory, and dedicated LICENSE files for each module/ in this way we can
differentiate 3rd party /external modules from main project

Il 20/Lug/2016 18:38, "Francesco Borzì" <notifications@github.com> ha
scritto:

**Comment by Yehonal** [comment]
Suggesting new AGPL for new modules

Il 20/Lug/2016 19:32, ha scritto:

**Comment by ShinDarth** [comment]
Agree with AGPL for new modules

**Comment by temzky** [comment]
File licensed as AGPLv3:
https://github.com/AzerothCore/azerothcore-wotlk/blob/master/src/server/scripts/Kalimdor/RazorfenKraul/instance_razorfen_kraul.cpp

File licensed as GPLv2 (**not** 'GPLv2 or later' as in TrinityCore):
https://github.com/AzerothCore/azerothcore-wotlk/blob/master/src/server/scripts/Kalimdor/zone_thousand_needles.cpp

I believe those files are linked together in one executable, thus counting as "combined work".

AGPLv3 is not compatible with GPLv2 ([source](https://www.gnu.org/licenses/license-list.en.html#AGPL)).
This could be solved by relicensing 'GPLv2 or later' files to GPLv3.
But GPLv2 files are stripped of "or later" phrase.

**Comment by FrancescoBorzi** [comment]
> But GPLv2 files are stripped of "or later" phrase.

this was a mistake that we should fix

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4762

**Comment by temzky** [comment]
The issue still exists, i.e. one program is built from GPLv2 and AGPLv3 source files. These licenses are not compatible. Now those GPLv2 files can be relicensed to GPLv3 thanks to 'or later' phrase (GPLv3 can be mixed with AGPLv3 so it fixes the problem), but as it stands they are GPLv2.
IANAL so I may be wrong on this.

**Comment by FrancescoBorzi** [comment]
@temzky thanks for your feedback, can you please open a PR to fix the issue?

**Comment by temzky** [comment]
I was wrong.
It is OK to keep 'GPLv2 or later' and AGPLv3 files in the same project. When they are combined together during the build process, 'GPLv2 or later' files are interpreted as GPLv3 and there is no incompatibility - they don't need to be relicensed. Sorry for the confusion.

**Comment by FrancescoBorzi** [comment]
no worries and thanks for trying to help!
