### ISSUE TITLE
Acore string entry xxxxx not found in DB.

### ISSUE THREAD

**Issue by GroodeeshPanj** [azerothcore/azerothcore-wotlk#21017]
### Current Behaviour

I'm not sure if this is a bug, hoping someone could help.

Sometime after startup, the following string entries are reported as not found. I can't pin point when this first happened because I don't often check the console or logs. I just happed to notice it during a weekly git pull / core update.

```WORLD: World Initialized In 0 Minutes 25 Seconds

Starting up anti-freeze thread (300 seconds max stuck time)...
AzerothCore rev. cbdab03623b8 2024-12-22 11:48:36 +0100 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
AC> Calendar deletion of old events.
Acore string entry 35411 not found in DB.
Acore string entry 35414 not found in DB.
Acore string entry 35415 not found in DB.
```

I poked around in the little bit of time I had and didn't see entries for those three numbers in the github repo.

### Expected Blizzlike Behaviour

Doesn't apply (other than no missing string entries I suppose)

### Steps to reproduce the problem

1. start up my core
2. wait random amount of time. no players logged in required.

### Extra Notes

enUS client. I searched 35415 in data/sql folders on github and didn't find anything noteworthy.

### AC rev. hash/commit

```
ll available DBC locales: enUS
Using World DB: ACDB 335.13-dev
Latest LoginDatabase update: acore_cms_subscriptions.sql
Latest CharacterDatabase update: trasmorg.sql
Latest WorldDatabase update: trasm_world_VendorItems.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-better-item-reloading
|- mod-eluna
|- mod-individual-xp
|- mod-npc-buffer
|- mod-npc-enchanter
|- mod-npc-services
|- mod-random-enchants
|- mod-solocraft
|- mod-transmog
```

### Operating system

Ununtu 24.04

**Comment by Kitzunu** [comment]
This is related to some module you got.

I cannot find these entries neither in the core nor in any old DB updates.

Make sure all the SQLs for the modules are executed properly

**Comment by GroodeeshPanj** [comment]
Thanks for the tip. It turned out to be an update to mod_individual_xp that added entries to acore_strings.

**Comment by Clauimb** [comment]
ghost , how did you fix the string errors ?
