### ISSUE TITLE
Bug spell blue-and-white cube

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#2101]
SMALL DESCRIPTION:
the spells are displayed as blue white cubes
These spells are a protracted problem.
These links I found on trinitycore

.spell 42772,59685,55348,55521,55550, I found that are affected by it

https://github.com/TrinityCore/TrinityCore/issues/20502
https://github.com/TrinityCore/TrinityCore/issues/14966

EXPECTED BLIZZLIKE BEHAVIOUR:
A texture should be present

CURRENT BEHAVIOUR:
![WoWScrnShot_071619_102633](https://user-images.githubusercontent.com/179698/61279129-d2427280-a7b5-11e9-855d-c30aa976bf0a.jpg)

STEPS TO REPRODUCE THE PROBLEM:
.go c 126027

BRANCH(ES):
Master

AC HASH/COMMIT:
AzerothCore rev. c47391b+ 2019-07-13 06:08:10 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
mod-transmog
mod-world-chat

**Comment by Stoabrogga** [comment]
Will be fixed after PR #2060 is merged.

**Comment by Selyria** [comment]
> Will be fixed after PR #2060 is merged.

fix your also these mistakes 55348,55521,55550,

**Comment by Stoabrogga** [comment]
The fix is for spell IDs 42772 and 59685 only. Could you please provide instructions to test the other spells you mentioned? Which creatures are using them? This has to be addressed in another PR.

**Comment by poszer** [comment]
55348 used by Drakkari Battle Rider
55521 used by Drakkari Battle Rider
55550 - Jagged Knife

Throw effects.

**Comment by poszer** [comment]
creature_equip_template ID:29836 (Drakkari Battle Rider) using  ItemId1 =5870 ItemId2 =5870 (They re wrong)

**Comment by Stoabrogga** [comment]
Great, thanks. Will look into this later.
