### ISSUE TITLE
Ogron missing in Dustwallow Marsh

### ISSUE THREAD

**Issue by blinkysc** [azerothcore/azerothcore-wotlk#21016]
### Current Behaviour

Ogron is missing from location he should be. /target Ogron not working either; not sure if under map. 

### Expected Blizzlike Behaviour

Ogron should be at proper location and give quest 

### Source

https://www.wowhead.com/wotlk/npc=4983/ogron
https://www.youtube.com/watch?v=aoECH-l4R5s
https://www.wowhead.com/wotlk/quest=1273/questioning-reethe

### Steps to reproduce the problem

1. level 45+ horde char
2. .teleport brackenwall
3. Move to 41,36

### Extra Notes

Am on playerbot

### AC rev. hash/commit

5b37bc520542

### Operating system

Debian 12.8 x64

**Comment by GroodeeshPanj** [comment]
Clear your cache? He's showing up for me and has been for awhile. Screenshots on a L80 GM (off) character. also commit# 5b37bc5

![WoWScrnShot_122224_153544](https://github.com/user-attachments/assets/2206e121-3212-44fe-a37f-74e6d30f575f)
![WoWScrnShot_122224_153624](https://github.com/user-attachments/assets/5631e3c5-7b39-4995-9b52-9d87354e26d5)

**Comment by TheSCREWEDSoftware** [comment]
https://wowgaming.altervista.org/aowow/?quest=1273

https://wowgaming.altervista.org/aowow/?npc=4983

![image](https://github.com/user-attachments/assets/685e84e5-4bfe-4188-9078-14e43d0e344a)

![image](https://github.com/user-attachments/assets/5d6edc02-debf-4d00-9bd6-151ab76b55dd)

@blinkysc 

I can't reproduce the issue. 

In-game you can use `.go creature id 4983` if it doesn't work.

Check your database in the `creature`, you can run the following query:

```sql
SELECT * FROM creature WHERE ID1 = 4983
```

If you get a result, he doesn't exist / no results appears. Either drop your world and fill it again or report this issue to playerbots.

**Comment by blinkysc** [comment]
.go creature id 4983 did work, but going to it manually or naturally hasn't worked. Not too sure whats up. I'll ```DROP acore_world``` and see if that helps

**Comment by TheSCREWEDSoftware** [comment]
`.go creature id 4983` worked means you got to the creature's spawn.

If you restart the server and run the command you should be able to see him (i dont know if he patrols)

**Comment by blinkysc** [comment]
Ran into this issue again this morning. Interesting problem. Just restarted server and was back again

**Comment by blinkysc** [comment]
I think I see what the issue is now... Ogron doesn't reset his position. Bots auto quest and must do his quest making him stuck in this state
