### ISSUE TITLE
Can't prepare the core using Cmake after 866c304d85e917b0330f4a7f2956538f0befe3c7 commit

### ISSUE THREAD

**Issue by PadreWoW** [azerothcore/azerothcore-wotlk#21014]
### Current Behaviour

Can't prepare the core using Cmake after 866c304d85e917b0330f4a7f2956538f0befe3c7 commit

Error:
CMake Error at src/cmake/macros/FindMySQL.cmake:130 (cmake_host_system_information):
cmake_host_system_information does not recognize WINDOWS_REGISTRY
Call Stack (most recent call first):
CMakeLists.txt:106 (find_package)

### Expected Blizzlike Behaviour

Not ingame problem

### Steps to reproduce the problem

1) Just update the core to 866c304d85e917b0330f4a7f2956538f0befe3c7 commit
2) Try to prepare the core with CMAKE 3.23.1

### Extra Notes

I'm using WampServer 3.3.6 (MySQL 8.0.39 + Apache 2.4.58 + PHP 5.6.40)

### AC rev. hash/commit

866c304d85e917b0330f4a7f2956538f0befe3c7

### Operating system

Win 10

### Custom changes or Modules

no

**Comment by Kitzunu** [comment]
Sounds to me like a WampServer issue

**Comment by PadreWoW** [comment]
Before this commit there was no issue

**Comment by PadreWoW** [comment]
There is no such registry key:
"HKEY_LOCAL_MACHINE\\SOFTWARE\\MySQL AB"

**Comment by Takenbacon** [comment]
Definitely not WampServer issue, I just ran into this as well with a direct MySQL install.

**Comment by Kitzunu** [comment]
I can't reproduce on W11, MySQL 8.4 CMake 3.27.4

**Comment by Takenbacon** [comment]
Appears to be older CMake related, no longer an issue after updating.

**Comment by PadreWoW** [comment]
> Definitely not WampServer issue, I just ran into this as well with a direct MySQL install.

What do you mean "direct MySQL install"?
Do you have registry key "HKEY_LOCAL_MACHINE\SOFTWARE\MySQL AB"?

**Comment by Kitzunu** [comment]
Update your CMake

**Comment by PadreWoW** [comment]
> Update your CMake

Updated to 3.31

Error:
CMake Error in src/server/database/CMakeLists.txt:
  Imported target "mysql" includes non-existent path

    "MYSQL_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by Kitzunu** [comment]
Have you added mysql to your system variables?

**Comment by PadreWoW** [comment]
Yes

![изображение](https://github.com/user-attachments/assets/53c1b5db-2fb7-47c7-8e47-f73fea6cabff)

**Comment by Kitzunu** [comment]
And that is the right path for the mysql server? Usually the path is ...\MySQL\MySQL Server 8.0.39\bin

**Comment by PadreWoW** [comment]
I use WampServer installed to D:\Wamp

The problem disappeared when I also entered the path to the include folder
But this is not in the installation instructions and it still turns out to be a hardcode

![изображение](https://github.com/user-attachments/assets/b124526d-36e3-4bb1-93fa-a238e58d04c2)
