### ISSUE TITLE
Saedelin Whitedawn - NPC (Dalaran) sometimes floats and goes underground instead of walking

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2103]
Saedelin Whitedawn - NPC (Dalaran) sometimes floats and goes underground instead of walking

##### SMALL DESCRIPTION:

Saedelin Whitedawn - NPC (Dalaran) sometimes floats and goes underground instead of walking

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Saedelin Whitedawn - NPC should be working normally

##### CURRENT BEHAVIOUR:

![WoWScrnShot_071619_204719](https://user-images.githubusercontent.com/18629476/61295732-4d824380-a80b-11e9-90a8-89ddafba5566.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Dalaran
2. Find Saedelin Whitedawn

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

53b74a6c073764c6b305bffd57b1043d23d3716b

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
This NPC is only spawned in Dalaran, right ?

**Comment by poszer** [comment]
Ok, we can try like this, adding one more waypoint there. When you can, please try this @spinzaku - And let me know if issue is solved  : 
```sql
DELETE FROM `waypoint_data` WHERE `id`=1142920 AND `point` IN (33,34);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES
(1142920, 33, 5761.59, 597.858, 649.707, 0, 0, 0, 0, 100, 0),
(1142920, 34, 5722.22, 624.876, 646.633, 0, 0, 0, 0, 100, 0);
```

**Comment by Selyria** [comment]
I tested it before and after I had no problems with both. 20 runs were made.

But I think an additional waypoint can't hurt after the fix I didn't have any problems either.

**Comment by spinzaku** [comment]
Tested i don't see her floating anymore.
