### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DevJoestar** [azerothcore/azerothcore-wotlk#21041]
### Current Behaviour

**/src/common/Cryptography/ARC4.cpp:23:15: fatal error: use of undeclared identifier 'EVP_CIPHER_fetch'
    _cipher = EVP_CIPHER_fetch(nullptr, "RC4", nullptr);
              ^
1 error generated**.

**_Compiled at 12% for the first time, the error appears and I don't understand why it is, I have been out of date, my guess is that because a dependency is not updated, nothing appears in the wiki. I await your response, thank you_**

**cmake version 3.21.2
libboost version 1.81 all dev
gcc 9.4.0
clang 10.0.0**

### Expected Blizzlike Behaviour

Compilar hasta 100% 

### Steps to reproduce the problem

1, Iniciar cmake
2, Llegar a 12%

### AC rev. hash/commit

https://github.com/DevJoestar/rhaegals

### Operating system

Ubuntu 20.04

**Comment by sudlud** [comment]
You're using ancient compiler and tools.

**Comment by sudlud** [comment]
https://github.com/azerothcore/azerothcore-wotlk/security

https://www.azerothcore.org/wiki/linux-requirements

**Comment by Kitzunu** [comment]
1. Update clang and GCC. That is way too old.
2. Update openssl
