### ISSUE TITLE
Scourgelord Tyrannus died mid-air. Body got stuck mid-air and can't be looted

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2106]
Scourgelord Tyrannus died mid-air. Body got stuck mid-air and can't be looted

##### SMALL DESCRIPTION:

Scourgelord Tyrannus died mid-air. Body got stuck mid-air and can't be looted

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Scourgelord Tyrannus body should drop down to the floor, so he can be looted

##### CURRENT BEHAVIOUR:

Sometimes you can kill Scourgelord Tyrannus mid-air. Making his body stuck mid-air and can't loot

![midair](https://user-images.githubusercontent.com/18629476/61439873-ec767f00-a974-11e9-9433-7bde11b1704f.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Kill Scourgelord Tyrannus mid-air
2. Stuck body mid-air
3. Can't loot

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

69c7fefad60a75cb2047d336287c5c55bec4d7fa

##### OPERATING SYSTEM:

 Ubuntu 16/18

**Comment by solidmaxtor** [comment]
@ArashGorge  Maybe this need you script =)

**Comment by ArashGorge** [comment]
> @ArashGorge Maybe this need you script =)

https://github.com/ArashGorge/azerothcore-wotlk/pull/7/files

just i forget to make rp at AC :X
