### ISSUE TITLE
Spell proc 0.00 attack speed fix

### ISSUE THREAD

**Issue by AzazelxD** [azerothcore/azerothcore-wotlk#2107]
Spell proc 0.00 attack speed fix

##### SMALL DESCRIPTION:

Which cpp and codes need edit in cpp for fix spell proc 0.00 attack speed fix,someone can tell me please?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When got 0.01 attack speed spell proc work,but when i got 0.00 spell proc not work

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Windows 7

**Comment by poszer** [comment]
Is this a question, or issue?

**Comment by AzazelxD** [comment]
Is issue,i need help.

**Comment by poszer** [comment]
> Is issue,i need help.

Fill this **AC HASH/COMMIT:**

**Comment by AzazelxD** [comment]
AC HASH/COMMIT what u mean ?

**Comment by poszer** [comment]
> AC HASH/COMMIT what u mean ?I have use azerothcore source, and i dont know how fix proc spell 0.00 chance

It's your version of AC

**Comment by AzazelxD** [comment]
I have AC version Latest commit 66aa629 Master

**Comment by Shard-MW** [comment]
Nothing is explained in the "issue"... Can you please give us more info ?
