### ISSUE TITLE
[Eluna] SendAreaTriggerMessage will only send %s but no message

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#21071]
### Current Behaviour

if send a message by  SendAreaTriggerMessage will only send %s, but SendBroadcastMessage OK.
        player:SendAreaTriggerMessage("This is test message")   error
        player:SendBroadcastMessage(("This is test message")  good

and I not see any change about SendAreaTriggerMessage at mod-eluna, so this must azerothcore change case this problem.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

N/A

### AC rev. hash/commit

AzerothCore rev. 35bc0a78cedb 2024-12-30 22:24:48 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 0.
服务器运行时间: 26 second(s)
Update time diff: 100ms. Last 202 diffs summary:
|- Mean: 100ms
|- Median: 100ms
|- Percentiles (95, 99, max): 101ms, 101ms, 167ms
Using SSL version: OpenSSL 3.0.15 3 Sep 2024 (library: OpenSSL 3.0.15 3 Sep 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80403
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 
Worldserver listening connections on port 54347
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.13-dev
Latest LoginDatabase update: 2024_12_15_00.sql
Latest CharacterDatabase update: 2024_11_15_00.sql
Latest WorldDatabase update: mod-zone-difficult.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-difficult
|- mod-eluna

### Operating system

Debian 12

**Comment by Kitzunu** [comment]
Open an issue in eluna
