### ISSUE TITLE
Gameobjects - Weird GUID behaviour?

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#2111]
Wierd guid behaviour with gameobjects

##### SMALL DESCRIPTION:
When you spawn a gameobject (for example id 32), it generates a guid (let's say it's 1000)
When I use .gob del 1000, it wrotes "Game Object (GUID : 1001) removed"
Then when I add a new gameobject, the next guid is 1002.

![image](https://user-images.githubusercontent.com/75517/61561122-6dfe0800-aa6e-11e9-8e9c-99b0c37a7610.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I think it shouldn't increase the guid when a guid is removed.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Spawn a gameobject and observe its guid
2. Remove it, observe the message
3. Respawn a new gameobject and observe its guid

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
Commit : 8f12eb031165bcfcb2036423c4b91289cb00de99

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
None

#### Extra : 
[https://imgur.com/nOI8s1M](url)

**Comment by locus313** [comment]
confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/37d1f2be4729e4f9465a0591d451af4b8a945418

**Comment by Kitzunu** [comment]
Cannot Reproduce https://github.com/azerothcore/azerothcore-wotlk/commit/af28aeebde8f8d9dec96259a594af595e1308d33

![image](https://user-images.githubusercontent.com/24550914/119250222-dc4a0f00-bb9e-11eb-96ad-f46b33bfdd1a.png)
