### ISSUE TITLE
Quest Event missing complete A Lost Master & How Big a Threat & Npc Sentinel Selarin [$25]

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#2118]
##### SMALL DESCRIPTION:

To make it a little easier here are all my sources and scripts I found

https://github.com/Anonymous2/trinityone/commit/65aa7cd57bda49ab7f9ea3f0efefc81d5d0a8f3b

https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/8edb6e77abff1a9b20df226f14b7a81b9e1acefc

https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/05b55109710ef0d20a7b8e41d405c066e0d432be

https://github.com/TrinityCore/TrinityCore/issues?utf8=%E2%9C%93&q=Terenthis

**Here is a description of how the quest should work** 

How Big a Threat
https://vanilla-twinhead.twinstar.cz/?issue=10624

https://github.com/TrinityCore/TrinityCore/issues/14364

**After the Quest How Big a Threat**

A Lost Master

https://vanilla-twinhead.twinstar.cz/?issue=10623
https://vanilla-twinhead.twinstar.cz/?issue=3419

After the Quest A Lost **Master**

**Escape Through Force**

If you do the quest Escape Through Force and you have completed the escort, the master should hold a small talk with his bear and then despawn both. 

Escape Through Stealth or Escape Through Force

The order of the quest would be

1 Quest 984 How Big a Threat Part 1
2 Quest 985 How Big a Threat Part 2
3 Quest 986 A Lost Master Part 1
4 Quest 993 A Lost Master Part 2
5 Quest 994 or 995 Escape Through Stealth or Escape Through Force

After delivering the quest to Terenthis, the Sentinel Selarin should run down the path in house and keep with Terenthis Small-talk then it should stand for 3 minutes and give a quest.

After the 3 minutes it goes again and despawnt in the woods

##### EXPECTED BLIZZLIKE BEHAVIOUR:

**So here are the videos from Offi and from Ac Core**

https://youtu.be/hXFftFeQvb4?t=617 Quest How Big a Threat Part 1 Offi

https://youtu.be/dLmm15NnYLk Quest How Big a Threat Part 1 Ac Core

https://youtu.be/hXFftFeQvb4?t=1152 Quest How Big a Threat Part 2 Offi

https://youtu.be/-262Z3tsjVk Quest How Big a Threat Part 2 Ac Core

https://youtu.be/hXFftFeQvb4?t=1188 Quest A Lost Master Part 1 Offi

https://youtu.be/vZZp8Hr3y8M Quest A Lost Master Part 1 Ac Core

https://youtu.be/hXFftFeQvb4?t=11347 Quest A Lost Master Part 2 Offi

https://youtu.be/LvtcwRzESGg Quest A Lost Master Part 2 Ac Core

https://youtu.be/hXFftFeQvb4?t=13262 Magic of the cape Quest A Lost Master Offi

https://youtu.be/LvtcwRzESGg?t=22 Magic of the cape Quest A Lost Master Ac Core

https://youtu.be/hXFftFeQvb4?t=13286 Quest Escape Through Force Offi

https://youtu.be/y1vwYhbqaiA Quest Escape Through Force Ac Core

https://youtu.be/hXFftFeQvb4?t=13685 Npc Sentinel Selarin run Offi

https://youtu.be/-JbQaZ2TzUs  Npc Sentinel Selarin run Ac Core

to find the quest order here well

https://vanilla-twinhead.twinstar.cz/?quest=985

##### CURRENT BEHAVIOUR:

It doesn't happen after the quest's submissions no Event.

##### STEPS TO REPRODUCE THE PROBLEM:
.go c 37097
accept the quest here
and then give the quest back.

there are 5 quests in total
1 Quest How Big a Threat Part 1
2 Quest How Big a Threat Part 2
3 Quest A Lost Master Part 1
4 Quest A Lost Master Part 2
5 Quest Escape Through Force

##### BRANCH(ES):
Master

##### AC HASH/COMMIT:
AzerothCore rev. 7b105b75dd2a+ 2019-07-15 06:08:55 +0000 (master branch) (Win64, Release)
##### OPERATING SYSTEM:
Windows 10

##### MODULES:
mod-transmog
mod-world-chat

**Comment by Azcobu** [comment]
Another summary of the various issues for these quests is here: https://github.com/chromiecraft/chromiecraft/issues/452

**Comment by vtihomirov** [comment]
Here another video source from TBC Classic: https://www.youtube.com/watch?v=ZeQXq3F6IeY
