### ISSUE TITLE
Compiling tools errors on mmap generator

### ISSUE THREAD

**Issue by Rochet2** [azerothcore/azerothcore-wotlk#212]
**Description**:
Compiling tools on windows causes mmap generator project to error.

You can see the output log, errors and warnings here:
https://gist.github.com/Rochet2/64afb7b65ee38df79d5698b9ce52e9ab

It also contains a recompile output so it is easier to see just the errors.

**Current behaviour**: There are errors when compiling with tools checked
**Expected behaviour**: There are no errors when compiling with tools checked
**Steps to reproduce the problem**:
1. Set up windows
2. Follow the installation guide https://github.com/AzerothCore/azerothcore-wotlk/wiki/Installation but in cmake tick to build "tools"
3. compile normally
4. behold the errors

**Branch(es)**: master
**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/8667c3b607e5572e202ac12c62805c5e738436e8
**Tools and Deps**:  windows 10 64 bit, cmake 3.6.1, VS 2015 enterprise version 14.0.25431.01 Update 3, building as 32 bit, OpenSSL 1.0.2g, mysql  Ver 14.14 Distrib 5.6.26, for Win32 (x86)
**Modules**:  none
**Other Customizations**: none
##

**Comment by Blumfield** [comment]
https://mega.nz/#F!9dYjjaJD!cmFzgTEnM-9AZ6pfNf2yLQ!BQwihAYA you can download the data here in the meantime, i'll try to fix it but I have others plan for now

**Comment by sucofog** [comment]
@Blumfield But do mmaps work? I don't see the enable option on the worldserver.conf and in the console it doesn't show the mmaps as loaded or localized.

**Comment by Blumfield** [comment]
It should be working yes, they are set to enabled by default if my memory serves me right

**Comment by stryker09** [comment]
not sure if only the extractors themselves need to be updated or do the core code which uses the resulting files need to be updated as well

**Comment by rre-za** [comment]
@Rochet2 
found this on bitbucket , see if that helps 
https://bitbucket.org/pak3935/sunwellcore/commits/0cf1eacb988bdbcad77208b9dfbf8800ec34e1c4

but im curious anyway there is no enable option in config files nor core loads mmaps , how we can know core is using mmaps ?

**Comment by ShinDarth** [comment]
can anyone try https://github.com/azerothcore/azerothcore-wotlk/pull/312 and give feedback please?
