### ISSUE TITLE
[Raid-WotLK] The Obsidian Sanctum - Is possible inside when the boss event is run on

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2120]
Error 1: When the battle against Satarion starts, if you die it is possible to release and re-enter the event.
Error 2: If you attack another one of the dragons it is possible to move it to the center, lower it a lot the HP, Pull Sartharion and kill blue dragon. This to obtain the achievement of 3 live drakes
How reproduce

EXPECTED BLIZZLIKE BEHAVIOUR:
for 1:  Any player NOT enter in the Sanctum if other players are in combat with a boss.
for 2: If other mini boss move X yards, boss is restart or If Pull Sartharion others 3 dragons Live is restar in espedific locations.

BRANCH(ES):
master

AC HASH/COMMIT:
3b09bd7  - but test others old

OPERATING SYSTEM:
ubuntu 16.04

MODULES:
No

**Comment by ArashGorge** [comment]
Fixed 
https://github.com/azerothcore/azerothcore-wotlk/pull/2130

**Comment by solidmaxtor** [comment]
Excellent service .jpg
Nice ArashGorge  work fine first test
