### ISSUE TITLE
Pit of Saron Normal/Heroic Dungeon - Ymirjar Deathbringer witches sometimes are stuck underground. [$5]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2124]
Pit of Saron Normal/Heroic Dungeon - Ymirjar Deathbringer witches sometimes are stuck underground.

##### SMALL DESCRIPTION:

Pit of Saron Normal/Heroic Dungeon - Ymirjar Deathbringer witches sometimes are stuck underground. If they aren't underground and when you pull them they will move and go underground. (check minimap below for exact spot)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Ymirjar Deathbringer witches shouldn't be stuck underground.

##### CURRENT BEHAVIOUR:

80% of the runs. Two Ymirjar Deathbringer witches are always underground on this spot. If they aren't underground and when you pull them they will move and go underground. So players have to to shoot them through the ground. (check minimap)

![minimap2](https://user-images.githubusercontent.com/18629476/61605303-6fe6e780-ac77-11e9-8df5-dd97ee8b3f0d.jpg)
![minimap](https://user-images.githubusercontent.com/18629476/61605305-74130500-ac77-11e9-9fbc-68eae081d0b9.png)

A couple more withes here, precise location minimap:
![minimap](https://user-images.githubusercontent.com/18629476/61637901-ee20a980-acca-11e9-8bfd-c30398684b3a.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do a dungeon run of Pit of Saron Normal/Heroic
2. And find the Two Ymirjar Deathbringer witches (minimap check above)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

3b09bd7 

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Related
https://github.com/azerothcore/azerothcore-wotlk/issues/862

**Comment by LichKing255** [comment]
Confirm.

I think altitude calculations are not true.
In some places like orgrimmar , dalaran , stormwind some npc have problem movement.
for example : Great Hexer Ohodo on Dalaran or some guard on front entrance stormwind.
They seem to be flying in some places, but that's not the case. they are in ground but have state fly.

And also in position mentioned in first issue when players cast one spell Throws npcs , they go to underground.

**Comment by LichKing255** [comment]
Confirm.

I think altitude calculations are not true.
In some places like orgrimmar , dalaran , stormwind some npc have problem movement.
for example : Great Hexer Ohodo on Dalaran or some guard on front entrance stormwind.
They seem to be falling in some places, but that's not the case. they are in ground but have state fall down.

And also in position mentioned in first issue when players cast one spell Throws npcs , they go to underground.
