### ISSUE TITLE
[quest] bug

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2126]
Description: can't speak to npc start event of quest
quest: [The Black Knight's Fall]

https://www.wowhead.com/quest=13664/the-black-knights-fall

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/6db0a438d9dff3d1fab5f904657ed281f5dee6c7

OS: windows 2017
MODULES:
Anticheat

**Comment by andoys** [comment]
Steps on how to do this quest:

1.) You need to be a **Champion** to pick up this Quest
While not all of the daily quests here involve mounted combat, it is the focus of the tournament. All participants will begin as an Aspirant and be given quests to let you practice the basic mechanics of mounted combat against target dummies.

Each of the daily quests you complete will reward you with an Aspirant’s Seal. After a couple days of practicing your skills you will be able to gather enough of these seals to challenge an NPC and should you succeed, you will attain the rank of valiant of your race’s respective home city.

As a valiant you will be given a similar set of daily quests to continue your training, each of these daily quests will reward you with a Valiant’s Seal and after enough days of practicing you will be ready for another challenge, if you complete this challenge you will become a champion of your city!
2.) Equip the lance
3.) Mount Stabled Argent Warhorse (Required if not Calvin won't talk to u)
4.) Talk to the squire calvin on the rafts by the entrance of the big arena
5.) He summons the Black Knight.
6.) As soon as he appears, dismount. and kill him.
