### ISSUE TITLE
Hunter's Tranquilizing Shot cannot dispell Enrage(Spell ID 19451)

### ISSUE THREAD

**Issue by soniczhang11** [azerothcore/azerothcore-wotlk#2129]
##### SMALL DESCRIPTION:
Players on my server found this issue when they trying to down Magmadar in Molten Core.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Tranquilizing Shot should be able to dispell Enrage from Magmadar.

##### CURRENT BEHAVIOUR:
I tried to use GM account with another guy to test both Tranquilizing Shot and Enrage from Magmadar. Tranquilizing Shot can dispell buffs like Berserker Rage from Warrior, but it cannot dispell Enrage from Magmadar. (GM account learned 19451 and test it with a hunter.)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c id 11982
2. aggro the boss
3. try Tranquilizing Shot when boss enraged.
4. .learn 19451
5. test it with a hunter using Tranquilizing Shot.

##### EXTRA NOTES:

It seems nothing wrong with Spell.dbc, since there is no such issue with TC using the same dbc files, maybe a bug in scripts?
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 15bd8f544097 2019-07-20 14:36:14 +0200 (master branch) (Unix, Release) (worldserver-daemon)

##### OPERATING SYSTEM:

CentOS 7

##### MODULES:

no.

##### OTHER CUSTOMIZATIONS:

no.

**Comment by Naxxramas-Server** [comment]
This problem is not in the spell but in the boss flags.

**Comment by soniczhang11** [comment]
> This problem is not in the spell but in the boss flags.

I try to learn this spell with GM account, and use another hunter trying to dispell it. But also failed.

**Comment by poszer** [comment]
Can you try to change Boss Flags?

**Comment by soniczhang11** [comment]
> Can you try to change Boss Flags?

you mean npc_flags? I compared unit_flags, npc_flags, flags_extra and mechanic_immune_mask with DB of trinitycore, they are all the same. I can confirm Tranquilizing Shot has no such issue with trinitycore.  Maybe a core/spell issue?

**Comment by Shard-MW** [comment]
So, I did some trys.
There is nothing to do with creature flags.
The issue come from that the Magmadar's Enrage spell
```
https://www.wowhead.com/spell=19451/enrage
```
is considered as a debuff on AC, and a buff on TC. That's why hunt's can't cast Tranquilizing Shot on him. It should be considered as a buff, and I think the issue is coming from the way that how AC reads spells, and not specially this spell.
