### ISSUE TITLE
Dalaran Guards Teleport Bug

### ISSUE THREAD

**Issue by Tixlenra** [azerothcore/azerothcore-wotlk#213]
**Description**:

The Guards in Dalaran should eradicate any opposite faction from their area.

**Current behaviour**: Tell us what happens

When entering the Alliance area of Dalaran as a Horde player, sometimes the guards do not remove you from the area. Sometimes when they DO remove you, it does not stun.

**Expected behaviour**: Tell us what should happen instead

The Guards in Dalaran should eradicate any opposite faction from their area.

**Steps to reproduce the problem**:
1. Walk into the Alliance side of Dalaran as a horde player.
2.  Walk into the Horde side of Dalaran as an alliance player
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  commit 7e4328b588c44d916a530a629d282b5c6a5ab0c8

**Operating system**:  Windows

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
##

**Comment by ShinDarth** [comment]
@Tixlenra AC hash/commit ?

**Comment by Tixlenra** [comment]
@ShinDarth Hi, sorry, I'm trying to find that out, will post soon

**Comment by Tixlenra** [comment]
@ShinDarth  **AC hash/commit**:  commit 7e4328b588c44d916a530a629d282b5c6a5ab0c8

**Operating system**:  Windows

**Comment by ShinDarth** [comment]
thanks

**Comment by sucofog** [comment]
I did not got that problem, checked and no bug apparently

**Comment by rre-za** [comment]
yep they are skippy sometimes 

hash : 7128d14b09dde8facc183a26aba168bfb6fa87fd

**Comment by talamortis** [comment]
yeah i can confirm, the horde side worked 100% for me, its only the alliance side that had the error's
