### ISSUE TITLE
Warlock's Backdraft cannot be consumed by AOE spell of Destruction

### ISSUE THREAD

**Issue by soniczhang11** [azerothcore/azerothcore-wotlk#2132]
##### SMALL DESCRIPTION:

Backdraft cannot active its effect for Destructions AOE like Rain of fire, Hellfire, Shadowfury etc.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After using Conflagrate with talents Backdraft, Warlock can get 3 Backdraft buffs, which can reduce spelltime and gcd of Destructions spells and will be consumed by those spells, e.g. if warlock get Backdraft buffs, the spelltime of Rain of fire and Hellfire should be reduced, and the gcd after spelling shoud also be reduced. Once spelling, 1 of 3 Backdraft buffs will be consumed. 

##### CURRENT BEHAVIOUR:

Backdraft can only reduce spelltime and gcd for Directional spells of Destructions, like Shadow Bolt, Immolate, Searing Pain. But it does not work with AOE spells of Destructions like Rain of fire, Hellfire and Shadowfury. AOE spell cannot even consume them.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create a Warlock
2.  learn all my class and active the talent "Backdraft"
3.  using Immolate and Conflagrate to get the "Backdraft" buffs
4. try Directional and AOE spells of Destructions, then you will see the issue.

##### EXTRA NOTES:

There is no such issue with latest TC.
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 763f546d2ae8 2019-07-23 17:50:58 +0000 (master branch) (Unix, Release) (worldserver-daemon)

##### OPERATING SYSTEM:

CentOS 7

##### MODULES:

nope

##### OTHER CUSTOMIZATIONS:

nope

**Comment by andoys** [comment]
Bug confirmed! A couple of my warlock players also reported this

**Comment by lineagedr** [comment]
Invalid. 
https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire?p=6039937&viewfull=1#post6039937

**Comment by poszer** [comment]
> Invalid.
> https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire?p=6039937&viewfull=1#post6039937

Thank you for info. Closing this issue

**Comment by soniczhang11** [comment]
> > Invalid.
> > https://www.mmo-champion.com/threads/634921-Backdraft-amp-Rain-of-Fire?p=6039937&viewfull=1#post6039937
> 
> Thank you for info. Closing this issue

I am sure it affect Shadowfury, Hellfire and Rain of fire in 3.3.5a 12340, cuz the description in dbc shows that. 
Spell Tooltip: Reduced cast time and global cooldown for your Destruction spells by $s1%.
Spell Description: Cast time and global cooldown of your next three Destruction spell reduced by $s1%.

**Comment by wowmane** [comment]
Confirm
