### ISSUE TITLE
[Druid][Swipe(cat)/(bear)] Swipe does not proc Omen of Clarity clearcasting [$5]

### ISSUE THREAD

**Issue by deadmage** [azerothcore/azerothcore-wotlk#2133]
##### SMALL DESCRIPTION:
Swipe (Cat) and Swipe (Bear) do not proc Omen of Clarity clearcasting.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Swipe should proc Omen of Clarity Clearcasting

##### CURRENT BEHAVIOUR:
Swipe does not proc Omen of Clarity clearcasting

##### STEPS TO REPRODUCE THE PROBLEM:

1. Pull 5 to 10 mobs.
2. Spam Swipe(cat)/(bear)
3. Notice that Swipe does not proc clearcasting from Omen of Clarity

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

4b1436175a3b

**Comment by andoys** [comment]
Bug confirmed!

**Comment by poszer** [comment]
What i can see the proc works fine. Could you check your combat log
![CatSwpie](https://user-images.githubusercontent.com/41213210/61854179-d52c1a00-aebd-11e9-94fb-ddc4d1408b58.png)

**Comment by andoys** [comment]
HMMM i have to recheck, maybe i am using another version

**Comment by deadmage** [comment]
I swiped 10 times 20+ adds and it did not proc at all, i get procs from my AA only.

**Comment by deadmage** [comment]
Also i'm talking about the spell Swipe, not just swiping (AA) the target

**Comment by poszer** [comment]
> Pull 5 to 10 mobs.
> Spam Swipe(cat)/(bear)

Just tested, The proc works fine.
Also include your AC HASH/COMMIT:

**Comment by deadmage** [comment]
I noticed that during ulduar yesterday when i aoe'd the worms before Hodir.

**Comment by Ali-Khazaee** [comment]
Working on it, i will commit it

**Comment by Ali-Khazaee** [comment]
After some research, I've found out this talent should proc just at these points

1 Successful melee attack
2 Successful cast positive magic spell
3 Successful damage from harmful magic spell cast

So, feral's abilities are not **MAGIC SPELL** or **HARMFUL MAGIC** so this issue is blizlike behavior

anyway if you want to feral's abilities proc Omen try this:

https://github.com/Ali-Khazaee/azerothcore-wotlk/commit/a4d448dd59a74bb13cd1b9815370b86efe781604

**Comment by Ali-Khazaee** [comment]
@poszer Look at the screen you sent, Your character have done melee attack

**Comment by deadmage** [comment]
@Ali-Khazaee So I'm mistaking than, are u sure tho, cuz the spell says Each of the druids Damage, healing and auto attacks........

**Comment by Ali-Khazaee** [comment]
What i said was what i extracted from spell work. So that must be blizlike behavior. If not then Ali-Khazaee@a4d448d is correct fix

**Comment by andoys** [comment]
@FrancescoBorzi  @poszer  can we put @Ali-Khazaee fix on pull?

**Comment by FrancescoBorzi** [comment]
@andoys yes he can open PR

**Comment by Ali-Khazaee** [comment]
Guys, I could create PR, But this isn't BlizLike! choice is yours

**Comment by andoys** [comment]
Wait i thought you said its Blizzlike?
Ahh i think i have read your message wrong. my apologies

**Comment by Ali-Khazaee** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2148

**Comment by talamortis** [comment]
> Guys, I could create PR, But this isn't BlizLike! choice is yours

If this is not blizzlike then please close the PR as i am aware that azerothcore focus's on blizzlike content.

**Comment by Ali-Khazaee** [comment]
@talamortis You did it :D
