### ISSUE TITLE
"./worldserver" returns that one of map files doesn't exist.

### ISSUE THREAD

**Issue by Crowfunder** [azerothcore/azerothcore-wotlk#2134]
"./worldserver" returns that one of map files doesn't exist.

##### SMALL DESCRIPTION:

`"Map file './maps/0004331.map': does not exist!"` authserver works normally.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Configured everything exactly as written in `http://www.azerothcore.org/wiki/Installation`

While in `/home/user/azeroth-server/bin`:
2. Terminal Command `./authserver` working normally without issues.
3. Terminal Command `./worldserver` returned error code.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

03864eea587f61cff66968aeee8b294247842ce1

##### OPERATING SYSTEM:

Ubuntu

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

None

**Comment by poszer** [comment]
Set Data folder in world server.conf

**Comment by FrancescoBorzi** [comment]
this is not a bug report but rather a support request, please read:

https://www.azerothcore.org/wiki/How-to-ask-for-help
