### ISSUE TITLE
[Player/Exp] Any character level can gain experience of high-level creatures

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2135]
SMALL DESCRIPTION:
Low level player can gain exp for  high level creatures

EXPECTED BLIZZLIKE BEHAVIOUR:
Characters not gain exp for creatures with +10 levels

CURRENT BEHAVIOUR:
any char level 1 for example kill level 80 creatures and gain exp

STEPS TO REPRODUCE THE PROBLEM:
-create character go any mayor level zone (thundra boreal example)
-kill any creature, use commandos or use other high level char for assist.

EXTRA NOTES:
BRANCH(ES):
all in last month test

OPERATING SYSTEM: ubuntu
MODULES: no
OTHER CUSTOMIZATIONS: no

**Comment by ArashGorge** [comment]
And whats problem ? Its RPG , 
But low level players cant kill Ex: lvl80 Mob, if low-lvl player killed high level mob its a reall kill :D and No problems i thinks
If him group member helps he or he was in group exp gained is low then solo

**Comment by poszer** [comment]
This is fine, closing issue
