### ISSUE TITLE
[Druid][Tier 8][Feral] The tier 8 2/5 set bonus does not proc clearcasting

### ISSUE THREAD

**Issue by deadmage** [azerothcore/azerothcore-wotlk#2136]
##### SMALL DESCRIPTION:

The 4/5 set bonus of the feral set does not proc clearcasting on periodic damage done by Rake, Rip and Lacerate.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Clearcasting should proc when Rake, Rip or Lacerate does periodic damage on the target.

##### CURRENT BEHAVIOUR:

1. Cast Lacerate, Rip and Rake on the target.
2.  Observe the buff bars for clearcasting proc.
3. 

##### BRANCH(ES):

master

**Comment by andoys** [comment]
Confirmed!

**Comment by Shard-MW** [comment]
You're speaking about this right ?
https://wotlk.evowow.com/?spell=64752

**Comment by deadmage** [comment]
yes

**Comment by w5860363** [comment]
https://github.com/TrinityCore/TrinityCore/pull/7278/files

**Comment by disclosurez** [comment]
> 
> 
> https://github.com/TrinityCore/TrinityCore/pull/7278/files

testing...

**Comment by disclosurez** [comment]
> 
> 
> > https://github.com/TrinityCore/TrinityCore/pull/7278/files
> 
> testing...

confirmed fixed

**Comment by FrancescoBorzi** [comment]
@disclosurez can you please open a PR with that?

**Comment by Nefertumm** [comment]
Can't confirm eadcb1a78208f1b777bbd847048f495128c84372
It's already fixed.
