### ISSUE TITLE
Feature Request: Allow people to AFK/Away in City without getting disconnected to character selection screen.  [$10]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2139]
Feature Request: Allow people to AFK/Away in City without getting disconnected to character selection screen.

Can be Module 
or
Core Edit (maybe configurable by worldserver.conf to enable/disable)
if this is clientside then no problem if someone can do it also

Currently there's no option for this.

This config is for people who are away/afk in character selection screen:
```
#    SocketTimeOutTime
#        Description: Time (in milliseconds) after which a connection being idle on the character
#                     selection screen is disconnected.
#        Default:     900000 - (15 minutes)
SocketTimeOutTime = 900000
```

**Comment by andoys** [comment]
Added $10 bounty

**Comment by Malow** [comment]
Isn't this something that is done by the client?

**Comment by IceNet** [comment]
Yes, AFK Kick is clientside, not serverside.

**Comment by andoys** [comment]
I talked with two devs here, they said its likely serverside. but i wont mind if its clientside.

**Comment by lineagedr** [comment]
I did some tests and found out that: 
After an X amount of time of being away the client will send ```CMSG_LOGOUT_REQUEST``` to the server.

And we can add code to:
```void WorldSession::HandleLogoutRequestOpcode(WorldPacket & /*recv_data*/)``` 

Maybe:
```
if (GetPlayer()->isAFK())
{
   LogoutRequest(0);
   WorldPacket data(SMSG_LOGOUT_CANCEL_ACK, 0);
   SendPacket(&data);
   return;
}
```
This will prevent players that have the afk tag to logout which isn't as optimal and also the client doesn't will not stop spamming the CMSG_LOGOUT_REQUEST opcode untill logged out or untill the client is no longer away.

Any ideas?

**Comment by andoys** [comment]
Oh so it can be done server side! great work @lineagedr  But is it possible to detect if player is in a City like Dalaran?  I still want people to get disconnected if they AFK in battlegrounds or outside cities thou

**Comment by lineagedr** [comment]
> Oh so it can be done server side! great work @lineagedr But is it possible to detect if player is in a City like Dalaran? I still want people to get disconnected if they AFK in battlegrounds or outside cities thou

If players afk in a bg they'll be automatically kicked from the BGs.

It is possible to detect if a player is in a city but I'm not sure why would you want that? Is there a special exception you want? Because the code above works anywhere in-game.

**Comment by andoys** [comment]
@lineagedr i just want players to be allowed to afk without getting kicked in safe zones. If it's too hard then maybe allowing Dalaran to be safe to afk without getting kicked? or all major cities.

**Comment by lineagedr** [comment]
@andoys So, only in safe zones. Got it.

**Comment by lineagedr** [comment]
@andoys This will check if the player has a AFK tag and if he's in a safe zone and if so he won't be kicked if HandleLogoutRequestOpcode is called

```
if (GetPlayer()->isAFK())
{
   if (AreaTableEntry const* zoneEntry = GetAreaEntryByAreaID(GetPlayer()->GetZoneId()))
   {
      if (zoneEntry->IsSanctuary()) // Sanctuary - No PvP
      {
         LogoutRequest(0);
         WorldPacket data(SMSG_LOGOUT_CANCEL_ACK, 0);
         SendPacket(&data);
         return;
      }
   }
}
```

**Comment by andoys** [comment]
> @andoys This will check if the player has a AFK tag and if he's in a safe zone and if so he won't be kicked if HandleLogoutRequestOpcode is called
> 
> ```
> if (GetPlayer()->isAFK())
> {
>    if (AreaTableEntry const* zoneEntry = GetAreaEntryByAreaID(GetPlayer()->GetZoneId()))
>    {
>       if (zoneEntry->IsSanctuary()) // Sanctuary - No PvP
>       {
>          LogoutRequest(0);
>          WorldPacket data(SMSG_LOGOUT_CANCEL_ACK, 0);
>          SendPacket(&data);
>          return;
>       }
>    }
> }
> ```

Wow great work! Which file did you add/edit this in src?
How hard is it to make it a configurable via worldserver.conf ?

**Comment by lineagedr** [comment]
> > @andoys This will check if the player has a AFK tag and if he's in a safe zone and if so he won't be kicked if HandleLogoutRequestOpcode is called
> > ```
> > if (GetPlayer()->isAFK())
> > {
> >    if (AreaTableEntry const* zoneEntry = GetAreaEntryByAreaID(GetPlayer()->GetZoneId()))
> >    {
> >       if (zoneEntry->IsSanctuary()) // Sanctuary - No PvP
> >       {
> >          LogoutRequest(0);
> >          WorldPacket data(SMSG_LOGOUT_CANCEL_ACK, 0);
> >          SendPacket(&data);
> >          return;
> >       }
> >    }
> > }
> > ```
> 
> Wow great work! Which file did you add/edit this in src?
> How hard is it to make it a configurable via worldserver.conf ?

Change the code to:
```
if (sWorld->getBoolConfig(CONFIG_ALLOW_GM_GROUP))
{
   if (GetPlayer()->isAFK())
   {
      if (AreaTableEntry const* zoneEntry = GetAreaEntryByAreaID(GetPlayer()->GetZoneId()))
      {
         if (zoneEntry->IsSanctuary()) // Sanctuary - No PvP
         {
	    LogoutRequest(0);
	    WorldPacket data(SMSG_LOGOUT_CANCEL_ACK, 0);
	    SendPacket(&data);
	    return;
	}
      }
   }
}
```

In MiscHandler.cpp
```void WorldSession::HandleLogoutRequestOpcode(WorldPacket & /*recv_data*/)```

Above the 
```//instant logout in taverns/cities or on taxi or for admins, gm's, mod's if its enabled in worldserver.conf``` Comment

Making it configurable via worldserver.conf:

Edit World.h

Add:
```
CONFIG_DENY_KICKING_AFK_PLAYERS,
```
Below:
```
CONFIG_LFG_LOCATION_ALL, // Player can join LFG anywhere
```

Then edit World.cpp

Add:
```
// Deny kicking afk players in safe zones
m_bool_configs[CONFIG_DENY_KICKING_AFK_PLAYERS] = sConfigMgr->GetBoolDefault("Misc.DenyKickingAFKers", false);
```
Below:

```
m_bool_configs[CONFIG_LFG_LOCATION_ALL] = sConfigMgr->GetBoolDefault("LFG.Location.All", false);
```

And lastly add it to your worldserver.conf:

Misc.DenyKickingAFKers = 1

**Comment by andoys** [comment]
@lineagedr  great work! were you able to test this on your server? 
Please claim bounty if it works 100%

**Comment by lineagedr** [comment]
> @lineagedr great work! were you able to test this on your server?
> Please claim bounty if it works 100%

It does work but like I've mentioned above it's not optimal
```
But it isn't optimal and also the client will not stop spamming the CMSG_LOGOUT_REQUEST opcode untill logged out or if the client is no longer away.
```

**Comment by andoys** [comment]
> > @lineagedr great work! were you able to test this on your server?
> > Please claim bounty if it works 100%
> 
> It does work but like I've mentioned above it's not optimal
> 
> ```
> But it isn't optimal and also the client will not stop spamming the CMSG_LOGOUT_REQUEST opcode untill logged out or if the client is no longer away.
> ```

@lineagedr What happens if 20 clients does the logout request? every minute?
if its no hassle can u make a pull ?

**Comment by andoys** [comment]
@lineagedr 
Thank you. 

What happens if lets say if 20 clients does the logout request? is it every second? or? What would be the worst that could happen? Also is there a way to contact you? Are you in Azerothcore Discord? 

Hmm your right maybe we should wait for something more optimal

**Comment by lineagedr** [comment]
@andoys It may cause server lag if there's a lot of players that have been afk long enough to trigger the clients inactivity kick. It's best to wait for a better way.

My discord is: Alistar#2047

**Comment by mik1893** [comment]
please check #2205 . From what i can see from logs, if i send back a reason for denying logout it won't spam it again immediatly after.
Please test and let me know.

**Comment by pklloveyou** [comment]
![TIM截图20190814184435](https://user-images.githubusercontent.com/18535853/63015472-9a694080-bec3-11e9-9933-059f63b8952b.png)
Waiting.。。

**Comment by FrancescoBorzi** [comment]
@pklloveyou please give your test feedback in the PR page (not here). Thank you
