### ISSUE TITLE
Hunter Pets Dash movement speed buff not applying after activation.  It's applied only after first attack.

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2140]
Hunter Pets Dash movement speed buff not applying after activation.  It's applied only after first attack.

##### SMALL DESCRIPTION:

Hunter Pets Dash movement speed buff not applying after activation.  It's applied only after first attack.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Upon Pet Dash activation, movement speed buff should be applied right away.

##### CURRENT BEHAVIOUR:

Hunter Pets Dash movement speed buff not applying after activation.  It's applied only after first attack.
Check Video: https://youtu.be/_TdUXXgYI78

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a pet
2. Use Pet Dash
3. It's movement is not increased.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

7d44bf25c741573d9ee54a129b19e5b1876ed16c

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by soniczhang11** [comment]
confirmed

**Comment by mik1893** [comment]
are you clicking on dash before entering combat with an enemy?

**Comment by diluh** [comment]
does anyone know how to fix this? it's an old mistake
@Viste @Winfidonarleyan @masterking32 @Yehonal @Helias

**Comment by avatar789** [comment]
there really is such a problem.

**Comment by mnclaras** [comment]
Any news with this bug? It's really weird

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers

**Comment by mnclaras** [comment]
I think it can be fixed with something like "Furious Howl" spell. I tried to add Dash spell in the same switch case (SpellMgr -> Find "Furious Howl"). 
The result was that pet took the effect on spell activation, but it was also applied to the hunter.

**Comment by syssneck** [comment]
Is this still an issue? There were some reworks for pets recently.

**Comment by FrancescoBorzi** [comment]
@syssneck feel free to close issues like this if none confirms it
