### ISSUE TITLE
Battleground system, cross-faction

### ISSUE THREAD

**Issue by poszer** [azerothcore/azerothcore-wotlk#2141]
CFbg reworks

##### SMALL DESCRIPTION:

After applying https://github.com/azerothcore/azerothcore-wotlk/pull/2064/files + module, we have a lot bugs now in battlegrounds

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After applying https://github.com/azerothcore/azerothcore-wotlk/pull/2064/files and module, there is a lot problems in battlegrounds.

I'm still for this option:
Expected behaviour is to revert these commit's and leave it, since our Bg system was excellent, without any problem reported ever. Cross Faction system is custom (and we should keep it under new branch , or atleast priovide it as patch + module, so the people who are interested about this and want to use it, check other branch, or patch their core, and use this feature (module) whatever.

##### CURRENT BEHAVIOUR:

After merging this PR we have a lot problems in Bg's. Didn't tested all issues, but will write some, that's for sure caused by this Pr : https://github.com/azerothcore/azerothcore-wotlk/pull/2064/

These are fine:
https://github.com/azerothcore/azerothcore-wotlk/pull/2008
https://github.com/azerothcore/azerothcore-wotlk/pull/2009
https://github.com/azerothcore/azerothcore-wotlk/pull/2010

Issues at this moment, keep im mind that everything is not tested, so the list will be updated when i confirm new issue:

1. Random Spam Chat in Raid and Guild (If you write something in Raid chat, all of these messages will be shown also in guild, but in other structure, like numbers, symbols, etc etc - Too much spam.) https://github.com/azerothcore/azerothcore-wotlk/pull/2064
2.  If you queue bg as a group there's chance you cannot attack each other bcoz you are friendly with the opssite factions.
3. When the Finishing Battleground, players are staying in their fake morphs provided for CFBG, leaving it doesn't restore Morph players (need to relog always)
4.  BG Chat not working properly (Same like first)

- Everything caused by module and this PR : https://github.com/azerothcore/azerothcore-wotlk/pull/2064 and module https://github.com/Winfidonarleyan/mod-cfbg

##### STEPS TO REPRODUCE THE PROBLEM:

1. Apply https://github.com/azerothcore/azerothcore-wotlk/pull/2064 and https://github.com/Winfidonarleyan/mod-cfbg, and play some bg's
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/763f546d2ae8d9b37fde9f924784120f4e643731

##### OPERATING SYSTEM:

Windows

##### MODULES:
 https://github.com/Winfidonarleyan/mod-cfbg

**Comment by FrancescoBorzi** [comment]
I don't see how https://github.com/azerothcore/azerothcore-wotlk/pull/2008/files or https://github.com/azerothcore/azerothcore-wotlk/pull/2009/files can have caused this issue. So probably the issue is caused by:

https://github.com/azerothcore/azerothcore-wotlk/pull/2010

@poszer can you please try to use latest master and then:

```git revert c7c4bd1ffd0c43d123963b8fe91872cc710da21b```

and see if this is the cause of the bugs?

**Comment by poszer** [comment]
Ok, edited infos. All caused by PR + Module
