### ISSUE TITLE
Isle of Conquest (BG) If you use Portal to get out of gate it always removes warlock pet.

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2143]
Isle of Conquest (BG) If you use Portal to get out of gate it always removes warlock pet.

##### SMALL DESCRIPTION:

Isle of Conquest (BG) If you use Portal to get out of gate it always removes warlock pet.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Portal should not remove warlock pet.

##### CURRENT BEHAVIOUR:

Using portal to get out of gate it always removes warlock pet.

##### STEPS TO REPRODUCE THE PROBLEM:

1. queue Isle of Conquest  BG / .debug bg
2. Warlock w/ pet out, use  Portal
3. Pet gone. need to re-summon

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

178315f  

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by LichKing255** [comment]
not confirm, Pet goes through closed door.

**Comment by FrancescoBorzi** [comment]
@LichKing255 thank you
