### ISSUE TITLE
[Core] Creatures in combat do not chain-aggro other similar creatures when walking close to them

### ISSUE THREAD

**Issue by Malow** [azerothcore/azerothcore-wotlk#2144]
#### SMALL DESCRIPTION:
As title.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Creatures that are in combat that walks close by other similar creatures should chain-aggro these other creatures. For example if you're doing a dungeon and use Fear as a form of crowd-control then if the feared creature runs into another pack that pack should aggro. 

##### CURRENT BEHAVIOUR:
Creatures do not chain-aggro as they're supposed to:
https://www.youtube.com/watch?v=L-CvD-Zuz2w
https://www.youtube.com/watch?v=ElQJyaGLcoY

##### STEPS TO REPRODUCE THE PROBLEM:
Aggro a creature and make it run through other similar mobs, using for example Fear.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
178315f8e263394063a602cda17d6eca1bd294da

##### OPERATING SYSTEM:
Windows 10

No modules and no customization.

**Comment by Nefertumm** [comment]
Fixed by 2ae84e2faf6b3884ce949299c1914e2d3e438a9d
