### ISSUE TITLE
SpellInfo - Possible errors with positive/negative effects

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#2147]
##### SMALL DESCRIPTION:
After working on fixing issue #2129, I noticed that there is **maybe** some wrong calculations about SpellInfo. 
I compared TC - SpellInfo.cpp (SpellInfo::_isPositiveEffectImpl)
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellInfo.cpp#L3376
with AC - SpellInfo.cpp (SpellInfo::_IsPositiveEffect)
https://github.com/azerothcore/azerothcore-wotlk/blob/d8d0bed3508c69f735ae73bc199598068252560c/src/server/game/Spells/SpellInfo.cpp#L2545
I think that if Magmadar's Enrage spell (https://wowgaming.altervista.org/aowow/?spell=19451) was shown as negative instead of positive, there should be some other spells that have the same error.
My PR (#2146) doesn't fix the error for all spells, but only for Magmadar's Enrage. 

##### EXTRA NOTES:
I think porting the SpellInfo::_isPositiveEffectImpl from TC could fix it since they didn't had Magmadar's Enrage issue. 

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
Commit : 8d4a694e82b0a6f4e26eba44dfec9837b226b598

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
None

**Comment by Yehonal** [comment]
Have you noticed that this spell triggers the 19272 spell (https://wowgaming.altervista.org/aowow/?spell=19272)?

According to the spell_editor it's a SCHOOL_DAMAGE therefore it's negative

![image](https://user-images.githubusercontent.com/147092/85346404-8f286d80-b4f5-11ea-9abd-52e73b157f43.png)


Moreover here: https://github.com/azerothcore/azerothcore-wotlk/blob/d8d0bed3508c69f735ae73bc199598068252560c/src/server/game/Spells/SpellInfo.cpp#L2740 

we can clearly read that if a positive spell casts a non-positive spell, then the the spell aura of the "main cast" will be considered a "debuff".

I'm not saying that's correct but that's what happen. We can rubber-ducking the trinitycore code to understand if they are using a different approach and why

**Comment by Yehonal** [comment]
Another strange thing is that TARGET_UNIT_CONE_ENEMY_54 (the Target used by lava burst) is not considered in both AC and TC _isPositiveTarget() method:

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2858

https://github.com/TrinityCore/TrinityCore/blob/c3dcbe04dcea04ce3f453f99d44ebebb542bcda7/src/server/game/Spells/SpellInfo.cpp#L4461

But if we add TARGET_UNIT_CONE_ENEMY_54 to the switch then the if condition here: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2740

could return true and the "Enrage" spell can be considered positive instead

**Comment by Yehonal** [comment]
check the PR please
