### ISSUE TITLE
Naxxramas - Anub'Rekhan 10 Man has a Crypt Guard

### ISSUE THREAD

**Issue by Tixlenra** [azerothcore/azerothcore-wotlk#215]
**Description**:

Anub'Rekhan is the first boss of the Arachnid Quarter in Naxxramas.
http://wowwiki.wikia.com/wiki/Anub'Rekhan

**Current behaviour**: Tell us what happens

Anub'Rekhan is standing with a Crypt Guard but he should not have any Crypt Guards with him in 10 man before the fight starts. 

**Expected behaviour**: Tell us what should happen instead

One of these adds spawns after every Locust Swarm. In addition, one spawns approximately 20 seconds after Anub'Rekhan is pulled. They have around 234,000 health. They have a cleave, a stacking acid spit DoT that ticks for 500 a stack, and a low-hp frenzy that increases damage by 50% and attack speed by 60%. 

The only time Crypt Guards should accompany Anub'Rekhan before the fight starts is in 25 man, and there should be two adds, one on his left side and one on his right side. On 10 man, there should be no adds accompanying him before the fight, he should be alone.

**Steps to reproduce the problem**:
1. Enter Naxxramas 10 Man.
2. Proceed to Anub'Rekhan.
3. You'll see he has a Crypt Guard by his side on 10 Man which should not be there.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  commit 7e4328b588c44d916a530a629d282b5c6a5ab0c8

**Operating system**:  Windows

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
##

**Comment by talamortis** [comment]
can confirm this issue, in 10 man he has 0 guards but on heroic he has 2, 1 at each side of him
