### ISSUE TITLE
[Quest] BUG

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2151]
DESCRIPTION: This quest [Garments of the Light] is buged.

https://www.wowhead.com/quest=5625/garments-of-the-light

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/3b09bd79ca0c83a8d99d36c73f8977c6fb00c678

OPERATING SYSTEM: Windows Server 2017

MODULES: Anticheat

**Comment by poszer** [comment]
> IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE!

- [ ]  SMALL DESCRIPTION:

- [ ]  EXPECTED BLIZZLIKE BEHAVIOUR:
- [ ]  CURRENT BEHAVIOUR:
- [ ]  STEPS TO REPRODUCE THE PROBLEM:

**Comment by wowmane** [comment]
@poszer ..................
