### ISSUE TITLE
Crash ACE_Message_Block::total_size_and_length

### ISSUE THREAD

**Issue by blackdev01** [azerothcore/azerothcore-wotlk#2152]
more than 15 crashes happend in a day

i don't know why this crash is happening exactly , but suddenly  server is going to crash and this like appear in database .
Max allowed socket connections 65536

i compiled my core in the debug mode and this is the log 
https://gist.github.com/blackdev01/91f6487040696c4d78b614fe580e073f
https://gist.github.com/blackdev01/755d8264d33edcfb84318b9d0d1de1ec
https://gist.github.com/blackdev01/38f232722a42cb6c06746c5faab607fe

OS : Linux Debian 7
ACE : lib 6.2.8

commit hash : https://github.com/azerothcore/azerothcore-wotlk/commit/a9b981d619c220d7459a963cac4e989215b638b1

**Comment by wowmane** [comment]
your server core version , is not for AC !

Mythcore ?

**Comment by blackdev01** [comment]
please don't spam here , if you don't have information about this problem
 if you pay attention ,you can see this  ACORE::Thread::Sleep    -->>> ACORE
ACORE = Azeroth Core

**Comment by wowmane** [comment]
You changed name, iknow this is for Mythcore Project :)

I can read well crash logs ... !

**Comment by FrancescoBorzi** [comment]
>  IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE!

@blackdev01 please fill the required information. Most importantly, the AC version (commit hash), if you use modules, etc...

**Comment by blackdev01** [comment]
rev : https://github.com/azerothcore/azerothcore-wotlk/commit/a9b981d619c220d7459a963cac4e989215b638b1
in module folder  i have : 
acore
hw-core
mod-anticheat-master
uwd
and worldengine

**Comment by poszer** [comment]
Too old rev

**Comment by wowmane** [comment]
@blackdev01

TrinityCore -> Mythcore -> Sunwell -> Azerothcore.

Your Core Mythcore, I'm sure.

**Comment by blackdev01** [comment]
that's an abuse. i think core update can not fix this problem.
i read the ac updates. there are nothing related to this crash

**Comment by poszer** [comment]
> that's an abuse. i think core update can not fix this problem.
> i read the ac updates. there are nothing related to this crash

Maybe bcoz we didn't have this issue, that's why you don't see nothing related to that? And to be clear about updates, every update is there to fix problem. So, instead of talking, try to update your core to latest rev of AC, and check will you get crash :D

**Comment by FrancescoBorzi** [comment]
@blackdev01 using an old version is never recommended. Please update to the latest version and try to reproduce the crash.

Closing this until it can be reproduced on a recent version.
