### ISSUE TITLE
[DB/Quest] Hellfire Fortifications

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2153]
IDs:
http://wotlk.openwow.com/quest=10110
http://wotlk.openwow.com/quest=10106

DESCRIPTION::
These two quests are marked as repeatable. But if you run towards the questgiver, the questmark is not updated to the BLUE questmark.

(and yes i didn't looked at the nonrepeatablequests like quest=13408/quest=13409, only the repeatable quests aren't working)

REV: https://github.com/azerothcore/azerothcore-wotlk/commit/c7156c787fe8156f094090cb87a575151b31561d

SYSTEM: Windows 2017
Moudels: Anticheat

**Comment by wizzymore** [comment]
Hi, the blue flag is okay, the quest is a daily quest ( both of them, horde and alliance and yes 10110 and 10106 )

What was not set-up correctly tho is the PVP Flag which i will update

Thanks for this
