### ISSUE TITLE
[Quest/DB] Quest "The Summoning"

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2157]
Description:
In the Quest "The Summoning" ( whose entry is 1713) the Bath'rah the Windwatcher cannot summon Cyclonian.

Current behaviour:
I try to use their fixed SQL query, but it makes errors.

REV: https://github.com/azerothcore/azerothcore-wotlk/commit/c7156c787fe8156f094090cb87a575151b31561d

SYSTEM: Windows 2017
Moudels: Anticheat

**Comment by Stoabrogga** [comment]
The issue text was copied from this TC issue:
https://github.com/TrinityCore/TrinityCore/issues/23318

Seems this is valid for AC, the event after turning in the quest is not played.

**Comment by Stoabrogga** [comment]
I was mistaken, the quest is working correctly, tested it successfully with commit 2f74802d03d52d735f8f2b06dee0151f2dde47c1:
```
.q rem 1712
.q rem 1713
.q a 1712
.q c 1712
.go 252.881 -1459.12 52.1 0
```
