### ISSUE TITLE
Core/Pools: Objects in the pool stop spawning

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2158]
Description: Creatures (probably GameObjects too) that belong to a pool, will stop to respawn after some time. this happens with Webbed Crusaders(30268 30273) and Serfex the Reaver(28083), for example.
I only monitored it for a few hours, but I think they won't respawn again until a server restart.

Current behaviour: After some number os respawns, the creature no longer spawn.

Expected behaviour: Creatures should keep respawning within the right time.

Steps to reproduce the problem:
To force it happen:

1.quest add 13008
2.go xyz 6394 229 395 571
3.cast 44659
4.Repeat step 3 a few times, usally after the second/third time the Webbed Crusaders won't spawn anymore.

REV: https://github.com/azerothcore/azerothcore-wotlk/commit/c7156c787fe8156f094090cb87a575151b31561d
SYSTEM: Windows 2017
Moudels: Anticheat

**Comment by Stoabrogga** [comment]
The issue text was copied from this TC issue:
https://github.com/TrinityCore/TrinityCore/issues/21331

I tested this and cannot confirm this to be true for AC. Tested the Webbed Crusaders and Serfex the Reaver.
