### ISSUE TITLE
Please delete need more information

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2161]
please delete need more information

**Comment by lineagedr** [comment]
I don't think this was possible pre Wotlk. Got any video or better proof? Because this:

```
- "Combo points added to a target should not be reset until you add a combo point to a different target."
```

Doesn't seem related to slice and dice it looks like a bugfix where the combo points might have reset randomly.

You still need combo points on your target in order to use spells that require combo points.

**Comment by FrancescoBorzi** [comment]
closing, as requested by author
