### ISSUE TITLE
Quest: Emergency Protocol: Section 8.2, Paragraph D

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2168]
Quest: Emergency Protocol: Section 8.2, Paragraph D

##### SMALL DESCRIPTION:

Scuttle a Southern Wreck not working after using torch on Crashed Flying Machine

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After using torch on Crashed Flying Machine.  I should get quest completion for Southern Wreck

##### CURRENT BEHAVIOUR:

![crashedflying](https://user-images.githubusercontent.com/18629476/62406228-00f48180-b5db-11e9-926e-65d49870b34e.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get Emergency Protocol: Section 8.2, Paragraph D quest ( .quest add 11796 )
2. Go to southern wreck
3. Use torch on Crashed Flying Machine

##### EXTRA NOTES:

Maybe fixes it: https://github.com/Aokromes/TrinityCore/commit/190a7ade6f90e408c73446bce723b2d4b35f0990

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

a35725712e0443d8002afa59f74c1f4ae4177c43

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Hacaw** [comment]
I **can not** reproduce this issue.

![image](https://user-images.githubusercontent.com/6963500/101519644-1bd3c480-398c-11eb-86d8-8e4dd274f2e6.png)
![image](https://user-images.githubusercontent.com/6963500/101519758-3c9c1a00-398c-11eb-888c-cc182e06b1f9.png)


TESTING
---
Used testing steps mentioned by author.
@andoys it would be nice if you can provide some teleport gm command to get there faster.

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None
