### ISSUE TITLE
Naxxramas - Maexxna's Naxxramas Portal

### ISSUE THREAD

**Issue by Tixlenra** [azerothcore/azerothcore-wotlk#217]
Screenshot: https://gyazo.com/d9fc5a258444a8a8bede96780af60d67

**Description**:

After killing Maexxna, a 'portal' appears which funnily enough doesn't look like a portal, so I guess we could just call it a transporter. 

**Current behaviour**: Tell us what happens

After killing Maexxna, it spawns, but in the wrong position.

**Expected behaviour**: Tell us what should happen instead

After killing Maexxna, it should spawn near the wall. Here's a video where you can see the correct positioning: https://youtu.be/-709sus1gIg?t=6m59s

**Steps to reproduce the problem**:

1. Kill all of Arachnid Quarter
2. Observe

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  commit 7e4328b588c44d916a530a629d282b5c6a5ab0c8

**Operating system**:  Windows

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Selectah** [comment]
This is actually not possible due to not included three dimensional rotation values (Quaternion) 

Mangos has it done and TC is on the work -> [https://github.com/TrinityCore/TrinityCore/pull/14146](TC)

**Comment by ShinDarth** [comment]
this is the correct commit link: https://github.com/TrinityCore/TrinityCore/commit/2967bf59b4a47837b85c995b732a6761c9c35f7e

**Comment by Selectah** [comment]
Thanks @ShinDarth Updated my Link aswell. There are all Pullrequest referals and comments. But this Commit is not finished atm.

**Comment by JunkyBulgaria** [comment]
It is already implemented in sunwell, you just need to update the angle in the database.

**Comment by ShinDarth** [comment]
@JunkyBulgaria it would be nice if you could open a PR for taht
