### ISSUE TITLE
Totem of Wrath

### ISSUE THREAD

**Issue by Shiftingwind** [azerothcore/azerothcore-wotlk#2173]
Totem of Wrath debuff disappearance

##### SMALL DESCRIPTION:

Once totem of wrath is placed, it's supposed to give the enemy mob/player the debuff that increases the critical strike chance of all attacks by 3% against all enemies within 40 yards.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

increases the critical strike chance of all attacks by 3% against all enemies within 40 yards.

##### CURRENT BEHAVIOUR:
 
gives the enemy debuff increases the critical strike chance of all attacks by 3% against all but the debuff disappears after a while and the debuff does only apply to one target if not 2-3 at most.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

**Comment by Hacaw** [comment]
@FrancescoBorzi maybe we should close or update the issues that have no commit-id.

I can not reproduce this issue.

TESTING
---
Created a party of 4 characters, 1 being a shaman.
On shaman I ran the followings:
.character level 80
.learn 3738 
.additem 5178
Cast totem of wrath. 
Wait 5 minutes, and check permanently the party status. 
Everyone kept their Totem of wrath buff.


SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by FrancescoBorzi** [comment]
@Hacaw thank you!
