### ISSUE TITLE
Nexus Instanze Grand Magus Telestra Should Make A Text Output

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#2182]
**SMALL DESCRIPTION:**

Grand Magus Telestra Should Make A Text Output

**EXPECTED BLIZZLIKE BEHAVIOR:**

https://youtu.be/pySQvQey1f8?t=184

**CURRENT BEHAVIOUR:**

Some texts are missing although they are available in DB

<img width="2048" alt="Nexus Say" src="https://user-images.githubusercontent.com/179698/62478641-dad20b80-b7ab-11e9-8a30-21693c6a41cd.png">

![Instanze Übersetzung](https://user-images.githubusercontent.com/179698/62537917-e0822c80-b851-11e9-94cf-401451fe6f63.jpg)

**STEPS TO REPRODUCE THE PROBLEM:**
.go c 126480

**BRANCH(ES):**
AzerothCore rev. 0228c1ea03c4+ 2019-08-05 13:36:05 +0200 (master branch) (Win64, Release)

**Comment by talamortis** [comment]
Maybe it works as intended but it does not show because of your client language?

**Comment by Selyria** [comment]
I also tried it with Englisch client
