### ISSUE TITLE
AoWoW for azerothcore [$10]

### ISSUE THREAD

**Issue by IceNet** [azerothcore/azerothcore-wotlk#2184]
##### SMALL DESCRIPTION:
make aowow compatible with azerothcore

##### EXPECTED BLIZZLIKE BEHAVIOUR:
the web database should show all datas

##### CURRENT BEHAVIOUR:
currently the aowow version here: https://github.com/azerothcore/www-aowow is not fully compatible with the currect AC
It doesn't generate datas for:
achievements
currencies
items
npc's
quests
titles
spells
some icons

##### STEPS TO REPRODUCE THE PROBLEM:

1. set up the web database
2. look for npc, items and quests etc

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
9ea1b0e6be843955d135ed801f29d93eb1cb1d9e

##### OPERATING SYSTEM:
debian 9

##### MODULES:
none

##### OTHER CUSTOMIZATIONS:
none

<!-- ------------------------- THE END ------------------------------

**Comment by Viste** [comment]
current aowow version works fine

**Comment by milestorme** [comment]
@Viste will this do https://github.com/azerothcore/www-aowow/pull/1

**Comment by solidmaxtor** [comment]
i am recomend extrac all data in local, upload if all is corected extracted.

**Comment by IceNet** [comment]
Update:

It's working now for all except NPC's and Quests

Any ideas?

**Comment by Wokwer** [comment]
> It's working now for all except NPC's and Quests

there's another problem: the character's talents aren't displayed

**Comment by Helias** [comment]
https://github.com/azerothcore/www-aowow 

I updated this fork of AoWoW to make it works with AzerothCore, check it and report any bugs there.
I know that there are something that maybe does not work properly but just report them one by one and we will improve it.

Anyway I don't know if this issue can be closed, because AoWoW works with AzerothCore.
@IceNet

**Comment by FrancescoBorzi** [comment]
I guess @Helias should claim the bounty

**Comment by BarbzYHOOL** [comment]
already told him

**Comment by Helias** [comment]
Claim requested.

Anyway, what I did so far is:

update www-aowow
fix some compatible issues with AC and updated the README to improve them
added a sql file in the setup (view README.md) to fit better AC with AoWoW
some tests
May, can miss something but I think that the 80-90% at least, is compatible with AzertohCore

**Comment by IceNet** [comment]
Done, Thx!
