### ISSUE TITLE
Wintergrasp queue not working with CFBG Module enabled

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2185]
Wintergrasp queue not working with CFBG Module enabled

##### SMALL DESCRIPTION:

Wintergrasp queue not working with CFBG Module enabled. Talking to NPC doesn't give option to QUEUE or pressing H.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Wintergrasp queue not working with CFBG Module enabled. Talking to NPC doesn't give option to QUEUE or pressing H.

##### CURRENT BEHAVIOUR:

Even npc announced battle gonna start soon:
![WoWScrnShot_080719_035520](https://user-images.githubusercontent.com/18629476/62573365-81abca00-b8c8-11e9-85ef-9de85b54042e.jpg)

We tried to QUEUE up via H or talking to NPC but eventually it became 0:00
![WoWScrnShot_080719_013012](https://user-images.githubusercontent.com/18629476/62574376-ee27c880-b8ca-11e9-871b-3164f93d1cb1.jpg)

Queue up failed to no avail. And just showed this:
![WoWScrnShot_080719_040249](https://user-images.githubusercontent.com/18629476/62573461-ae5fe180-b8c8-11e9-8d49-f63a6d63d5c0.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Updated to latest commit: ef377b9 
2. Added CFBG Module and Enabled
3. compiled server is up
4. Try queuing up before Wintergrasp starts if it works

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

ef377b9

##### OPERATING SYSTEM:

Ubuntu 16/18 

##### MODULES:

CFBG Module

**Comment by IceNet** [comment]
It works for the faction who control WG i guess

**Comment by andoys** [comment]
> It works for the faction who control WG i guess

no it should still work even if u don't control faction

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can you please have a look here?

**Comment by Winfidonarleyan** [comment]
![image](https://user-images.githubusercontent.com/18329778/62590051-5d1a1700-b8f5-11e9-8ae1-4049e7e49248.png)

![image](https://user-images.githubusercontent.com/18329778/62589989-2d6b0f00-b8f5-11e9-9e20-90c69acb1f6c.png)

**Comment by andoys** [comment]
Mine doesn't work. and my version:
![azerothcoreversion](https://user-images.githubusercontent.com/18629476/62590348-930fc900-b8fe-11e9-8404-64490fd349ec.png)

**Comment by Winfidonarleyan** [comment]
![image](https://user-images.githubusercontent.com/18329778/62590494-c3536980-b8f6-11e9-9d4a-418e267b2615.png)

**Comment by andoys** [comment]
Well no clue. i will do clean git clone.
