### ISSUE TITLE
ICC 30% Buff cross-faction, other faction doesn't get buff

### ISSUE THREAD

**Issue by IceNet** [azerothcore/azerothcore-wotlk#2186]
##### SMALL DESCRIPTION:
When crossfaction is enabled for raid, only the faction who has the phase get the 30% buff

##### EXPECTED BLIZZLIKE BEHAVIOUR:
crossfaction raid is not blizzlike

##### CURRENT BEHAVIOUR:

When crossfaction is enabled for raid, only the faction who has the phase, get the 30% buff
Phase Horde definition: 56618
Phase Ally definition: 56617
Horde buff: 73822
Ally buff: 73828
(i hope the spellIds will help)

##### STEPS TO REPRODUCE THE PROBLEM:
1. enable crossfaction raid in worldconfig
2. make a raid with an ally/horde char
3. enter ICC

##### EXTRA NOTES:
-

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
9ea1b0e6be843955d135ed801f29d93eb1cb1d9e

##### OPERATING SYSTEM:
windows server 2016

##### MODULES:
transmog, anticheat, 1vs1, better item reload, autolearnspells, arena commands, duel-reset, individual XP, guildhouse, pvptitles

##### OTHER CUSTOMIZATIONS:
-

**Comment by IceNet** [comment]
false report, the other faction has the buff, but other icon -faceplam- my fault, sry!

**Comment by FrancescoBorzi** [comment]
@IceNet no problem, and thanks anyway for the prompt report! ;)
