### ISSUE TITLE
 [Quest] The Cipher of Damnation - Borak's Charge - Ruul the Darkener not spawning

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2188]
[Quest] The Cipher of Damnation - Borak's Charge - Ruul the Darkener not spawning

##### SMALL DESCRIPTION:

 [Quest] The Cipher of Damnation - Borak's Charge - Ruul the Darkener not spawning

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should spawn just like this video:  https://youtu.be/5DYheqZ2KYg?t=40

##### CURRENT BEHAVIOUR:

Quest: https://www.wowhead.com/quest=10578/the-cipher-of-damnation-boraks-charge
Ruul the Darkener not spawning: https://www.wowhead.com/npc=21315/ruul-the-darkener

![WoWScrnShot_080719_200528](https://user-images.githubusercontent.com/18629476/62621721-338dd980-b94f-11e9-85ff-1f9d89b8c0aa.jpg)
![WoWScrnShot_080719_200654](https://user-images.githubusercontent.com/18629476/62621725-35579d00-b94f-11e9-93e4-49ff4bbb85cb.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .questadd 10578
2. .tele shadowmoon valley and go to spawn location

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

ef377b9d9f2be3a17c4d1ed5a49b24c4daea4ff6

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Stoabrogga** [comment]
He does not spawn for the quest, he is always there, patrolling between the Warden's Cage and the Dragonmaw Fortress. He starts above the Warden's Cage, then flies down to the Netherwing Fields, walks towards the Dragonmaw Fortress and finally moves all the way back to the Warden's Cage.
