### ISSUE TITLE
Worldserver.exe error instantcrash with error log

### ISSUE THREAD

**Issue by crotin1111** [azerothcore/azerothcore-wotlk#2197]
Opening DatabasePool 'acore_world'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.5.38
MySQL server ver: 8.0.16
[ERROR]: In mysql_stmt_prepare() id: 8, sql: "INSERT INTO graveyard_zone (ID, GhostZone, Faction) VALUES (?, ?, ?)"
[ERROR]: Table 'acore_world.graveyard_zone' doesn't exist
[ERROR]: In mysql_stmt_prepare() id: 9, sql: "DELETE FROM graveyard_zone WHERE ID = ? AND GhostZone = ? AND Faction = ?"
[ERROR]: Table 'acore_world.graveyard_zone' doesn't exist
MySQL client library: 5.5.38
MySQL server ver: 8.0.16
[ERROR]: In mysql_stmt_prepare() id: 54, sql: "SELECT difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2, modelid1, modelid2, modelid3, modelid4, name, subname, IconName, gossip_menu_id, minlevel, maxlevel, exp, faction, npcflag, speed_walk, speed_run, scale, rank, mindmg, maxdmg, dmgschool, attackpower, DamageModifier, BaseAttackTime, RangeAttackTime, unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race, minrangedmg, maxrangedmg, rangedattackpower, type, type_flags, lootid, pickpocketloot, skinloot, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType, InhabitType, HoverHeight, HealthModifier, ManaModifier, ArmorModifier, RacialLeader, movementId, RegenHealth, mechanic_immune_mask, flags_extra, ScriptName FROM creature_template WHERE entry = ?"
[ERROR]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', mindmg, maxdmg, dmgschool, attackpower, DamageModifier, BaseAttackTime, RangeA' at line 1

Worldserver error

##### SMALL DESCRIPTION:

So i want to make this work. i have updated everything, but i still get an error, please help 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

WorldServer to work loading all databases

##### CURRENT BEHAVIOUR:

It does not load all the supposed database

##### STEPS TO REPRODUCE THE PROBLEM:

1. I do not know honestly because i have been trying for an entire day with no results..
2. 
3. 

##### EXTRA NOTES:
 It works in a repack

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

I cannot find it

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:
 None

**Comment by poszer** [comment]
Configure and Use dbassembler to import DB

**Comment by crotin1111** [comment]
I cannot configure, i have tried and it says access denied but im administrator. i do not get or understand it. could you help me through teamviewer maybe? see what i am doing wrong

**Comment by crotin1111** [comment]
also, which version should i use for git bash, i have the latest but i assume i need lower for it to work? but permissions are all messed up apparently even after allowing and putting permissions

**Comment by crotin1111** [comment]
okay so i set permission for git. but now a new error appears when assembling 

common.sh: line 18: [: /c/Users/Sheldon: binary operator expected
cat: /c/Users/Sheldon: Is a directory
EXPECTED value GOT EOF
1) all: Assemble all
2) bases: Assemble only bases
3) updates: Assemble only updates
4) customs: Assemble only customs
5) import-all: Assemble & Import all
6) import-bases: Assemble & Import only bases
7) import-updates: Assemble & Import only updates
8) import-customs:  Assemble & Import only customs
9) quit: Exit from this menu
[Please enter your choice]: 5
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
/c/Users/Sheldon Gelinas/Desktop/AzerothCore/azerothcore-wotlk/apps/db_assembler/includes/functions.sh: line 144: $OUTPUT_FOLDER$database$suffix_base".sql": ambiguous redirect

**Comment by poszer** [comment]
> okay so i set permission for git. but now a new error appears when assembling
> 
> common.sh: line 18: [: /c/Users/Sheldon: binary operator expected
> cat: /c/Users/Sheldon: Is a directory
> EXPECTED value GOT EOF
> 
> 1. all: Assemble all
> 2. bases: Assemble only bases
> 3. updates: Assemble only updates
> 4. customs: Assemble only customs
> 5. import-all: Assemble & Import all
> 6. import-bases: Assemble & Import only bases
> 7. import-updates: Assemble & Import only updates
> 8. import-customs:  Assemble & Import only customs
> 9. quit: Exit from this menu
>    [Please enter your choice]: 5
>    =====     DB ASSEMBLER MENU     =====
>    ===== STARTING ASSEMBLY PROCESS =====
>    /c/Users/Sheldon Gelinas/Desktop/AzerothCore/azerothcore-wotlk/apps/db_assembler/includes/functions.sh: line 144: $OUTPUT_FOLDER$database$suffix_base".sql": ambiguous redirect

Contact me on discord. I'll help you

**Comment by crotin1111** [comment]
okay will do right now

**Comment by crotin1111** [comment]
whats your discord @poszer

**Comment by FrancescoBorzi** [comment]
https://discordapp.com/channels/217589275766685707/284406375495368704

**Comment by poszer** [comment]
> whats your discord @poszer

★彡[Poszer]彡★#8448

**Comment by crotin1111** [comment]
ok Thank you added
