### ISSUE TITLE
[Class, Rogue] offhand attack buged.

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2200]
DESCRIPTION: Rouge class, most of attacks by off hand weapon missed !

Tested by class/rouge:
Gs: 4300
hit rating: 380

How to tested:

1. Creat class rouge
2. Added need items
3. On the waepons Just be off hand
4. Attacked to dummy or characters on the duel.

Missed attacks by off hand weapon...

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/ef377b9d9f2be3a17c4d1ed5a49b24c4daea4ff6
OPERATING SYSTEM: Windows server 2016
MODULES:
OTHER CUSTOMIZATIONS:

**Comment by FrancescoBorzi** [comment]
"most of attacks by off hand weapon missed" is not a proper bug report.

You should mention how it currently works and how it is supposed to work, with numbers.

For example: "on X hits, it missed Y times and it is instead expected to miss between Z-N and Z+N times"

also, show proof about what you are saying.

**Comment by wowmane** [comment]
@andoys

Can u help to this : test ?
