### ISSUE TITLE
[Boss ICC 25] Sindragosa - Ice Tomb and Frost Imbued Blade buff Issue

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2201]
[Boss ICC 25] Sindragosa - Ice Tomb and Frost Imbued Blade buff Issue

##### SMALL DESCRIPTION:

If player has Frost Imbued Blade buff and he is hit by Ice Tomb he is immune. Player with Frost Imbued shouldn't be targeted by Ice Tomb it should pick other players. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If you have Frost Imbued Blade buff you can't be targeted with Ice Tomb. So other players always get targeted
But if you do Solo run, Ice Tomb always miss/immune/no effect because no other player? or because you have Frost Imbued blade buff

##### CURRENT BEHAVIOUR:

Watch video: https://youtu.be/9OJCylVHcqk

5 characters targeted by Sindragosa for Ice Tombs
Look at raid marker X he has Frost Imbued Blade Buff but once he is targeted by Ice Tomb and gets hit by it. He is immune. No Ice Tomb appears. All 4 other players got Ice Tomb.

Ice tomb is important to reset the Mystic Buffet buff
No Mystic Buffet = Wipe

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get Shadowmourne quest -> https://www.wowhead.com/quest=24757/frost-infusion
2. Start raid 25 man Sindragosa
3. Equip Shadow's Edge
4. Get hit by frost breath 4 times by Sindragosa
5. You now have 4 stacks https://www.wowhead.com/spell=72292/frost-infusion
6. You now have https://www.wowhead.com/spell=72290/frost-imbued-blade
7. Wait and get hit by Ice Tomb

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

ef377b9d9f2be3a17c4d1ed5a49b24c4daea4ff6

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by Ali-Khazaee** [comment]
1. Open boss_sindragosa.cpp
2. Find this word class SindragosaIceTombCheck
3. Replace it's code body to this
```
class SindragosaIceTombCheck
{
    public:
        bool operator()(Unit* unit) const
        {
            return !unit->HasAura(SPELL_FROST_IMBUED_BLADE) && unit->IsImmunedToDamageOrSchool(SPELL_SCHOOL_MASK_ALL);
        }

        bool operator()(WorldObject* object) const
        {
            return object->ToUnit() && !object->ToUnit()->HasAura(SPELL_FROST_IMBUED_BLADE) && object->ToUnit()->IsImmunedToDamageOrSchool(SPELL_SCHOOL_MASK_ALL);
        }
};
```
After this change if player has Imbued_blade buff will not be targeted by sindragosa ice tomb

**Comment by andoys** [comment]
Thank you @Ali-Khazaee  life saver

**Comment by Ali-Khazaee** [comment]
https://github.com/Ali-Khazaee/azerothcore-wotlk/commit/41c44304f17311bb4fe55ab34b5bb3d9d038fffe

**Comment by andoys** [comment]
Great work @Ali-Khazaee :D best fix

**Comment by FrancescoBorzi** [comment]
@Ali-Khazaee can you please open a PR with it?

**Comment by Ali-Khazaee** [comment]
@FrancescoBorzi Done
