### ISSUE TITLE
Help!?

### ISSUE THREAD

**Issue by HevdavDEV** [azerothcore/azerothcore-wotlk#2204]
Hy! Help my!?

<a href="https://kepkuldes.com/image/WowO1c"><img src="https://kepkuldes.com/images/2211963faad4d9dfc002b03e92aebd5c.th.jpg" alt="2211963faad4d9dfc002b03e92aebd5c.jpg" border="0" /></a>

**Comment by FrancescoBorzi** [comment]
@mik1893
