### ISSUE TITLE
Tauren camera height

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#2206]
I'm not sure, but in my opinion the tauren’s camera height should be higher. I ask you to study this issue. This is very inconvenient when playing for tauren.

https://i2.imageban.ru/out/2019/08/14/8a2861dfa28a26d73ebc2a77170ad1f5.jpg
https://i6.imageban.ru/out/2019/08/14/071ab33e97e95eb4aea161b4e7178f30.jpg

MaloWС from Discord say what this maybe in .dbc files.

**Comment by Kitzunu** [comment]
If .dbc then we cannot do anything

**Comment by BarbzYHOOL** [comment]
it's very probably client side

**Comment by Mitradis** [comment]
not client
https://www.youtube.com/watch?v=1UaVSN0wz1A
https://www.youtube.com/watch?v=3K9kFgI4FqY
