### ISSUE TITLE
Camera height jumping

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#2207]
When traveling, you can notice how in some places the height of the camera (center) “jumps” (reset). These places can be found anywhere, the most obvious:
https://i3.imageban.ru/out/2019/08/14/407103541519b835f708bf1ee808da4b.jpg
https://i4.imageban.ru/out/2019/08/14/33b3e55fe66f0105e7eee67043ffd335.jpg
https://i5.imageban.ru/out/2019/08/14/6489043a0f2de23eafb0de9cd552bc62.jpg
https://i3.imageban.ru/out/2019/08/14/b6c88910e6d90f4885d3da8d2cea618d.jpg
https://i2.imageban.ru/out/2019/08/14/2a685b391eb07a3d724ffb6de06d93e8.jpg
https://i1.imageban.ru/out/2019/08/14/6ef529e62dfdcc3ba9c596fa9c38995f.jpg
https://i3.imageban.ru/out/2019/08/14/1d16079371b63125344743f68ae05b50.jpg
https://i2.imageban.ru/out/2019/08/14/ff64da38ddb09b73e9edccdda49d4806.jpg
https://i3.imageban.ru/out/2019/08/14/02b02ffce724d915e6d4e8d7b3ff57c1.jpg
https://i1.imageban.ru/out/2019/08/14/32b0ecb9334241f9ac6a1d660bf53328.jpg

**Comment by degenesis** [comment]
I'm also noticing this. Jumpy camera height adjustment while moving on slopes.

**Comment by Mitradis** [comment]
i think its in .dbc files.

**Comment by Mitradis** [comment]
@UltraNix @Kitzunu you do a lot of collisions and make different fixes for them. Perhaps you know the reason for this camera behavior? Such a gap is present on absolutely all servers on the Internet and no one has solved it.

**Comment by UltraNix** [comment]
It's clientside.

**Comment by Mitradis** [comment]
but there is no such thing in the original

**Comment by Mitradis** [comment]
https://github.com/chromiecraft/chromiecraft/issues/1428
a very similar problem, I'm sure this is a server problem,

**Comment by UltraNix** [comment]
The one you linked might be indeed related to server, because there should be `SMSG_COLLISION_HEIGHT `packet send.
There are only three cases when this packet is sent: mounting up, changing scale and shapeshifts. The rest are clientside.

**Comment by Mitradis** [comment]
official servers. it wasn’t like that when I played there.

you can fix https://github.com/chromiecraft/chromiecraft/issues/1428 I do not think that adding this request (updating the height) will take a long time. Or do I need to dry separate report?

**Comment by UltraNix** [comment]
Maybe they changed that on retail.

**Comment by Mitradis** [comment]
https://www.youtube.com/watch?v=UcfE82kCTSY
@UltraNix  I played this game in the period 2007-2016 I know what I say. If you have not played this game then why argue otherwise. Here you can clearly see that this was not the case.
https://www.youtube.com/watch?v=RfKnS4uKV2E

**Comment by UltraNix** [comment]
Because I'm telling you - it's not serverside thing. There is no packet that controls camera (besided the cases I wrote above) from the server.

**Comment by Mitradis** [comment]
I have (like everyone else) the original original 2009. ORIGINAL! Do you want to say that having the same client in 2009, there is no such thing on the official server, but on the pirated one? bullshit.

**Comment by UltraNix** [comment]
I don't know why are you rude? I'm just telling you what I know and I'm not infallible. I am not the only developer here, so I don't know why you closed that ticket. If somebody have a clue to handle this - go on.

**Comment by FrancescoBorzi** [comment]
> bullshit. then you don't know enough

@Mitradis You've been warned before. One more comment like this and you're permabanned by all AC platforms. Last warning.

**Comment by Mitradis** [comment]
I know that this is due to incorrect docking (connection) of the cells of the grids (meshes) of the maps. I can't prove it, but I know it.

**Comment by heyitsbench** [comment]
All related issues to this are closed as being a blizzlike, client-sided issue. Without a source for this (aside from memory), I see no reason for this to remain open.
