### ISSUE TITLE
Mounts and water Breath [$25]

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#2208]
if going in water on mount when posible see timer "Breath", but visual character on mount not in underwarer. But if unmount can see what character in fact underwater. 
https://i2.imageban.ru/out/2019/08/14/9effe0656d3c63ea72fe2b54c3749110.jpg
https://i4.imageban.ru/out/2019/08/14/7d092f329d4a0240f35856278de97b22.jpg
https://i6.imageban.ru/out/2019/08/14/23f87772e95eb131d68bf80e2b9f71c6.jpg

in addition, need dive deep for activate "Breath":
https://i6.imageban.ru/out/2019/08/14/0f4e9a37f95cf395d3a7f547bbe594fe.jpg
https://i1.imageban.ru/out/2019/08/14/af907c2c7b8d85eeb0a92a0c2821f1e9.jpg

**Comment by poszer** [comment]
Same is if you flying

**Comment by Skovisen** [comment]
Without having looked at the code, this might seem like the "breath" event does not account for the mount offset, thinking that the character is at the center of the object, while it is in fact at some positive y offset to the center. As can be seen in picture 2, the mount's face is partially under water, likely triggering the event. 

@Mitradis as for pictures 4 and 5, did this happen after being mounted in the water and then swimming downwards, or did it happen after swimming out from the shore and then diving?

**Comment by Mitradis** [comment]
@Skovisen 4 and 5 pics another situation, unrelated to the Mounts and water Breath. This is just additional remark. Just depth activation "Breath" very deeper.

sorry my english...

**Comment by Kitzunu** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b9e9ccf93c63c3b27d7a6f9eced0beb4e14af40e

**Comment by Mitradis** [comment]
some one can transfer this fix to AC?

**Comment by Kitzunu** [comment]
Is this touched in your PR? @Yehonal

**Comment by UltraNix** [comment]
> in addition, need dive deep for activate "Breath":
> https://i6.imageban.ru/out/2019/08/14/0f4e9a37f95cf395d3a7f547bbe594fe.jpg
> https://i1.imageban.ru/out/2019/08/14/af907c2c7b8d85eeb0a92a0c2821f1e9.jpg

This is because of performance check - breath timer is updated every 3 yards. of movement.  I won't change that, because this is here for some reason (vmap calls are quite expensive).
The first problem solved in PR.
