### ISSUE TITLE
[Feature Request] Cross-Faction Dungeon Finder [$30]

### ISSUE THREAD

**Issue by andoys** [azerothcore/azerothcore-wotlk#2212]
Feature Request: Cross-Faction Dungeon Finder
Must work with [CFBG Module](https://github.com/azerothcore/mod-cfbg) Enabled

- Can be Module 
- Core Edit 

Configurable by Worldserver.conf to enable/disable

**Comment by andoys** [comment]
Hmm can't seem to add bounty? will just manually add reward

**Comment by Ali-Khazaee** [comment]
I've find a way to implement this feature in ac without hardcore edits, After testing it i'll make a PR

**Comment by FrancescoBorzi** [comment]
This feature should be an addition to the CFBG

**Comment by Ali-Khazaee** [comment]
https://github.com/Ali-Khazaee/azerothcore-wotlk/tree/CFD

**Comment by FrancescoBorzi** [comment]
@Ali-Khazaee can you make it as an addition to the CFBG module?

we should avoid patching the core directly

**Comment by Winfidonarleyan** [comment]
I never understood why need to do cfbg and cfd together. 
It's not the same thing, it's 2 different systems (bgs and dungeons) it really annoys me when say it's the same

**Comment by Winfidonarleyan** [comment]
@Ali-Khazaee, please move all code in the core to module

**Comment by Ali-Khazaee** [comment]
@FrancescoBorzi Alright, I'll make it as a separate module

**Comment by Ali-Khazaee** [comment]
I've just realized making this as module, Requires to add new hooks to the core

**Comment by FrancescoBorzi** [comment]
@Ali-Khazaee that's fine, you can add the hooks to the core when needed

**Comment by BarbzYHOOL** [comment]
A module for crossfaction dungeon finder, a module for crossfaction battlegrounds, a module for crossfaction ICC, what else??

THAT MAKES NO SENSE

When we enable crossfaction, we want all these things in ONE. All in one. Imo it should be in the core or all in one big module. In the core there is already crossfaction chat, grouping etc...........................

**Comment by FrancescoBorzi** [comment]
> A module for crossfaction dungeon finder, a module for crossfaction battlegrounds, a module for crossfaction ICC, what else??

> When we enable crossfaction, we want all these things in ONE. All in one. Imo it should be in the core or all in one big module. In the core there is already crossfaction chat, grouping etc...........................

you got a point, what I don't want is to break/complicate/alter the current behaviour when introducing such extra features

@Ali-Khazaee @BarbzYHOOL I don't mind if it's in the core, as long as when:

```
AllowTwoSide.DungeonFinder = 0
```

it has NO side effects at all

**Comment by BarbzYHOOL** [comment]
yes, it must be properly coded, if the author (most likely ali-khazaee) can't, then well a module will do the trick but in the end it should all be in the core OR we take all the crossfaction system OUT of the core and put all into a big module

**Comment by Ali-Khazaee** [comment]
https://github.com/Ali-Khazaee/azerothcore-wotlk/commit/b31b26c1dd98c27f16987f8f4ebd55113da28109

Could someone test & approve this commit ?

**Comment by Ali-Khazaee** [comment]
I've tried to keep this feature simple and not too much hardcore code

**Comment by Malow** [comment]
Isn't cross-faction dungeon finder already working by default in AC? At least on my server with the cross-faction battle ground module installed and all cross-faction flags enabled in the config I can queue with 2 Hordes and 3 Alliance to Random Dungeon and they all get matched together as a group.
