### ISSUE TITLE
[Request] Fix Quest chain "Scarab Lord" Title [$25]

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2213]
Thi chain its broken and autocomplete to end chain in few quest complete.

QUEST INFO:

1st Mission What the future holds: http://old.wowhead.com/quest=8286 Collection of the npc http://old.wowhead.com/npc=15180
2nd Mission Only one can get up: http://old.wowhead.com/quest=8288 Collection of the npc http://old.wowhead.com/npc=15180
3rd Mission The path of the honest http://old.wowhead.com/quest=8301 Collection of the npc http://old.wowhead.com/npc=15180
4th Anachronos Mission http://old.wowhead.com/quest=8303 Collection of the npc http://old.wowhead.com/npc=15180
5th Mission Forgotten Memories http://old.wowhead.com/quest=8305 Collection of the npc http://old.wowhead.com/npc=15192
6th Mission A pawn in life chess http://old.wowhead.com/quest=8519 Collected from http://old.wowhead.com/object=180633
7th Mission Entrust to Flights http://old.wowhead.com/quest=8555 Collection of the npc http://old.wowhead.com/npc=15192

--> HERE IS AUTOCOMPLETE AND END CHAIN FOR 2 QUEST MORE <--

--> CHECK AND FIX HERE ON FORWARD <--
Part of the green fragment.

You have to go to the submerged temple and go to the Shadow of Eranikus http://old.wowhead.com/npc=5709, then Malfurion will appear and give you the mission Eranikus, the tyrant of the dream.
2nd Mission Tyrande and Remulos http://old.wowhead.com/quest=8734 Collection of the npc http://old.wowhead.com/npc=15624
3rd Mission The Nightmare Corruption Collection of the npc http://old.wowhead.com/npc=11832
4th Mission The Nightmare manifests Pickup of the npc http://old.wowhead.com/npc=11832
5th Mission The Champion Returns Collection of the npc http://old.wowhead.com/npc=11832

Part of the red fragment.
You have to go to Black Wing Den and talk to Vaelastrasz http://old.wowhead.com/npc=10538 she will give you the mission Nefarius Corruption http://old.wowhead.com/quest=8730

Part of the blue fragment.
You have to go to the npc Spirit of Azuregos http://old.wowhead.com/npc=15481 and talk to him and he will give you an item that starts a mission.
1st Mission The Azuregos Magic Accounting Book http://old.wowhead.com/quest=8575
2nd Mission The translation of the accounting book http://old.wowhead.com/quest=8576 Collection of the npc http://old.wowhead.com/npc=11811
3rd Mission Guisón, former best friend http://old.wowhead.com/quest=8577/ Collection of the npc http://old.wowhead.com/npc=11811
4th Mission A pair of glasses? No problem! http://old.wowhead.com/quest=8578 Npc Collection http://old.wowhead.com/npc=11811
5th Mission Never ask me about my business! http://old.wowhead.com/quest=8584 Collection of the npc http://old.wowhead.com/npc=11811
6th Mission The Island of Terror http://en.wowhead.com/quest=8585 Collection of the npc http://old.wowhead.com/npc=8125
7th Mission Fabulous quimerok chops from Dirge http://old.wowhead.com/quest=8586 NPC Collection http://old.wowhead.com/npc=8125
8th Mission Go back to Narain http://old.wowhead.com/quest=8587 Pick up the npc http://old.wowhead.com/npc=8125
9th Draconic for clumsy http://old.wowhead.com/quest=8597 Npc collection http://old.wowhead.com/npc=11811
10th ReScaTe http://old.wowhead.com/quest=8598 http://old.wowhead.com/object=180652
11th Decoy! http://old.wowhead.com/quest=8606 NPC Collection http://old.wowhead.com/npc=11811
12th The only recipe http://old.wowhead.com/quest=8620 Collection of the npc http://old.wowhead.com/npc=11811
13th Mission Good and bad news http://old.wowhead.com/quest=8728 Collection of the npc http://old.wowhead.com/npc=11811
14th Mission The anger of Neptulon http://old.wowhead.com/quest=8729 Collection of the npc http://old.wowhead.com/npc=11811

Thanks for read

**Comment by FrancescoBorzi** [comment]
@solidmaxtor how did this get fixed?
