### ISSUE TITLE
Shaodowmourne Questline not working properly.

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#2218]
Shadowmourne Questline not working properly.

##### SMALL DESCRIPTION:

- Mobs in Plagueworks Quarter doesn't count as "Souls" towards Shadowmourne Questline. 

Source: https://www.wowhead.com/quest=24547/a-feast-of-souls#comments
You must have Shadow's Edge equipped to gather souls.
You can only gather souls in ICC 10 or 25.
You don't need to get a killing blow.
A single full clear of The Plagueworks 10-man yields about 190 souls if you one-shot most bosses.
You need to be alive to gather souls. 

Yes, Shadow's Edge was equipped at all times.
Didn't get killing blows, but as said, doesn't matter.
Did full clear, our guy barely got 40 Souls from the quarter.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs (even from Traps in Plaguework Quarters) - Should count as Souls towards the weapon-quest, but didn't. This was from 3.3.0 Patch.

##### CURRENT BEHAVIOUR:

Multiple of the mobs who should count towards the Questline for Shadowmourne  -  (Feast of Souls quest) doesn't count, even with weapon equipped and doing it as it should be done. Specificly mobs in Plagueworks Quarter, as this was the place ppl mainly would aim to go for to recieve a bunch of souls.

##### STEPS TO REPRODUCE THE PROBLEM:

Equip Shadow's Edge - Kill mobs, see which mobs counts as Souls towards Feast of Souls quest, and which doesn't - Normally the whole Plagueworks Quarter should count towards it. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 79f13e5075ca+

##### OPERATING SYSTEM:
Linux Ubuntu 16

##### MODULES:

none

**Comment by andoys** [comment]
This quest is working on my server. One of my players already in https://www.wowhead.com/quest=24548/the-splintered-throne 4 steps ahead

**Comment by disclosurez** [comment]
> 
> 
> This quest is working on my server. One of my players already in https://www.wowhead.com/quest=24548/the-splintered-throne 4 steps ahead
> 
> Commit: [84be529](https://github.com/azerothcore/azerothcore-wotlk/commit/84be529c76e268510a89e42f7adea361b2475ccd)

Nothing to do with it not working, Souls should be easier to obtain, mobs supposed to count towards quest doesn't count.

**Comment by Kitzunu** [comment]
Works. 

Everything in plague quarter that should give souls does.
