### ISSUE TITLE
Bugs Ahn'kahet: The Old Kingdom + Languages translations not possible because written in script

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#2219]
SMALL DESCRIPTION:

At the first Boss all texts are not in my language although they are available.

Reason for this is that all texts in the script are inside would be good if you can avoid that and do it via the database so that all languages are translated.

Boss Script boss_elder_nadox

<img width="1253" alt="Yell Boss" src="https://user-images.githubusercontent.com/179698/63193706-7433d400-c06e-11e9-9bd6-b86681de89d0.png">

The mob Ahn'kahar Spell Flinger ID 30278

Casts the spells Shadow Blast Spell Id 56698 this should cause 65% damage it causes about 45 damage.

[Hurls a bolt of dark magic at an enemy, inflicting Shadow damage equal to 65% of the target's maximum health.]

Shadow Sickle Spell ID 56702 
Flings circular shadow blades at random enemies for 6 sec. Channeled.

The npc casts but nothing happens

EXPECTED BLIZZLIKE BEHAVIOR:

https://www.wowhead.com/spell=56698/shadow-blast
https://www.wowhead.com/spell=56702/shadow-sickle

CURRENT BEHAVIOUR:

The spell Shadow Blast does about 45 damage
Shadow Sickle is casted, but nothing happens.

BRANCH(ES):

AzerothCore rev. 0228c1ea03c4+ 2019-08-05 13:36:05 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
Transmog
Worldchat

**Comment by grimgravy** [comment]
Using the Talk function you can add the speech to the database. MosterYell function very old outdated yet.
