### ISSUE TITLE
Elwynn Forest and Durotar is neutral zones

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#2225]
Elwynn Forest and Durotar must be frendly zones. Now they neutral zones for fractions.

https://i5.imageban.ru/out/2019/08/19/f32df548770e0bd5de8ff6a56db7d172.jpg
https://i4.imageban.ru/out/2019/08/19/f6c568819519b8838498c75173ca3920.jpg
https://i2.imageban.ru/out/2019/08/19/85a72f1e60fb7696463e01531bd0f27c.jpg
https://i2.imageban.ru/out/2019/08/19/ceeade3b575e72d7e4550fdfa0ab4f0f.jpg

Must be:
https://i5.imageban.ru/out/2019/08/19/81feb53d239c56ee806a23e0c556fd89.jpg

**Comment by Mitradis** [comment]
with other friendly zones same problem.

**Comment by Ramys** [comment]
did you look at that?
# SERVER SETTINGS
#
#    GameType
#        Description: Server realm type.
#        Default:     0  - (NORMAL)
#                     1  - (PVP)
#                     4  - (NORMAL)
#                     6  - (RP)
#                     8  - (RPPVP)
#                     16 - (FFA_PVP, Free for all PvP mode like arena PvP in all zones except rest
#                          activated places and sanctuaries)

GameType = 0

**Comment by Ramys** [comment]
Did you look at that?

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L827

**Comment by Mitradis** [comment]
understand, delete.
