### ISSUE TITLE
Error message when the worldserver is initialized

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#2228]
The world server always writes an error message after the initialization is finished, e.g.:
```
ERROR: WORLD: World initialized in 0 minutes 19 seconds
```
In the code:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/World/World.cpp#L1961

As this is clearly not an error, could someone please tell me why it is treated as such?

**Comment by Meltie2013** [comment]
It existed on the Sunwell Core was well. So more then likely a typo during that time.

**Comment by Viste** [comment]
`sLog->outError`

**Comment by Viste** [comment]
must be 
`sLog->outString`

**Comment by BarbzYHOOL** [comment]
It's written like that to be in RED. I know that's not the smartest thing but there are only 4 colors in debug (and yes it's not something we added ourselves on AC).

Maybe with winfi's PR for improved logging, we can use something semantically correct and with a different color than white

**Comment by Kitzunu** [comment]
I think this can be closed
![image](https://user-images.githubusercontent.com/24550914/79193594-379dbf80-7e2b-11ea-9ef6-b951e8073b53.png)

**Comment by LukasVolgger** [comment]
Check log file. In console it's always fine @Kitzunu

**Comment by LukasVolgger** [comment]
Why closing this guys?

**Comment by FrancescoBorzi** [comment]
@LukasVolgger this was done on purpose I guess. I don't know the original reason, maybe to emit a sound?

So it's not really a "bug", but I'm not against changing it

**Comment by LukasVolgger** [comment]
Okily Dokily :ok_hand:
