### ISSUE TITLE
NPC's in Garm's Bane doesn't move [$15]

### ISSUE THREAD

**Issue by IceNet** [azerothcore/azerothcore-wotlk#2237]
##### SMALL DESCRIPTION:
The NPC's doesn't move (mini Event?)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The NPCs should run towards K3

##### CURRENT BEHAVIOUR:
https://www.wowhead.com/npc=29618/snowblind-follower
https://www.wowhead.com/npc=29619/garm-invader
Video: https://www.wowhead.com/quest=12820/a-delicate-touch#videos:id=75355

##### STEPS TO REPRODUCE THE PROBLEM:
1. Fly to Garm's Bane
2. Look at the NPC's (Snowblind Follower and Garm Invader)

##### EXTRA NOTES:
idk

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
0264d952e78ee0eba4d8f4e1b4bff8d8aad3b9ea

##### OPERATING SYSTEM:
Windows Server 2016

##### MODULES:
1v1 arena
better item reloading
bg reward
CF BG
CF Instances/Raids
invdividual XP
NPC CodeBox
NPC Gambler
PvPTitles
Teleporter
Weekend XP

##### OTHER CUSTOMIZATIONS:
none

**Comment by IceNet** [comment]
Reference/Possible fix:
https://pastebin.com/YzMFHfgT
https://pastebin.com/fpg6dwkt

Fixes are from leaked rising-gods core
maybe someone can use it as a template

**Comment by Stoabrogga** [comment]
I tested the quests "A Delicate Touch", "Overstock" and "Gormok Wants His Snobolds" and they work quite well. So all that is missing here is the waypoint movement. I'll try to figure something out.
