### ISSUE TITLE
warlock imp bug

### ISSUE THREAD

**Issue by daromero2** [azerothcore/azerothcore-wotlk#2242]
warlock imp bug

##### SMALL DESCRIPTION:
When you send the IMP out without the active fireball, it goes around the target

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When you send the IMP out without the active fireball, should not take any action

##### CURRENT BEHAVIOUR:
When you send the IMP out without the active fireball, it goes around the target

##### STEPS TO REPRODUCE THE PROBLEM:
1. Crete a warlock 
2.  Summon imp pet
3.  send it to atack

##### EXTRA NOTES:
AzerothCore rev. a35725712e04+ 2019-08-02 09:05:33 +0000 

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
51e54da6379f42eef504531a298e654278527311

##### OPERATING SYSTEM:
Windows 10 64bit

##### MODULES:
anticheat

##### OTHER CUSTOMIZATIONS:

sorry about my english

**Comment by LichKing255** [comment]
Confirm.

**Comment by d3athbl0w** [comment]
Pets: DK, WARLOCK, HUNTER, MAGUE Same problem

**Comment by Stoabrogga** [comment]
This only affects pets which have no melee attack: The warlock imp and the mage water elemental. Other pets are not affected. The reason for this is the AI logic of those two pets which tries to get a distance to the victim because both pets use ranged spells and must not attack otherwise. This is not easy to fix and to be honest is also not a big problem in my opinion.

If someone wants to fix this, this would be a good point to start:
https://github.com/azerothcore/azerothcore-wotlk/blob/9f593eb64e541eca05a857bec292a53e85cecfa8/src/server/game/AI/CoreAI/PetAI.cpp#L566

This sets a 20 yard distance for pets who have no melee attack.

**Comment by LichKing255** [comment]
> This only affects pets which have no melee attack: The warlock imp and the mage water elemental. Other pets are not affected. The reason for this is the AI logic of those two pets which tries to get a distance to the victim because both pets use ranged spells and must not attack otherwise. This is not easy to fix and to be honest is also not a big problem in my opinion.
> 
> If someone wants to fix this, this would be a good point to start:
> https://github.com/azerothcore/azerothcore-wotlk/blob/9f593eb64e541eca05a857bec292a53e85cecfa8/src/server/game/AI/CoreAI/PetAI.cpp#L566
> 
> This sets a 20 yard distance for pets who have no melee attack.

@Nightprince Fixed this for me. i send diff for you . i can't pull request . test and pull request this.

Ty @Nightprince


[0001-Core-PetAI-Fix-aggro-and-movement-IMP-Warlock-and-Wa.zip](https://github.com/azerothcore/azerothcore-wotlk/files/3771750/0001-Core-PetAI-Fix-aggro-and-movement-IMP-Warlock-and-Wa.zip)

**Comment by Stoabrogga** [comment]
I presume this was taken over from TC 3.3.5. Sorry, but this contains too many changes, I don't have the time to sort this out or test this thoroughly to prevent side effects or regression, and I won't take over such changes blindly.

**Comment by Nightprince** [comment]
> I presume this was taken over from TC 3.3.5. Sorry, but this contains too many changes, I don't have the time to sort this out or test this thoroughly to prevent side effects or regression, and I won't take over such changes blindly.

if you don't want to update PetAI to last version of TC , just change this line:

https://github.com/azerothcore/azerothcore-wotlk/blob/9f593eb64e541eca05a857bec292a53e85cecfa8/src/server/game/AI/CoreAI/PetAI.cpp#L566

to :

> if(_canMeleeAttack())
>    me->GetMotionMaster()->MoveChase(target, 20.0f, float(M_PI));

**Comment by FrancescoBorzi** [comment]
@Nightprince thanks, can you please open a PR with that?

http://www.azerothcore.org/wiki/How-to-create-a-PR
