### ISSUE TITLE
Exceptional drop-off of client

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#2245]
Several friends and I set up servers on the LAN. When we were playing normal games, all of them suddenly dropped.

Core tips are as follows:
2019-08-29 10:09:45 ERROR: WorldSocket:: HandlePing: Player (account: 13, GUID: 0, name: <none>) kicked for over-speed pings (address: 192.168.123.192)

There is no characte with guid 0 in the database

Azeroth Core rev. 0ee3f8373a04 + 2019-08-27 23:07:31 + 0000

server System: win7 64bit

![image](https://user-images.githubusercontent.com/49540243/63905620-6192a500-ca47-11e9-919c-fb4f1529afe6.png)

**Comment by Viste** [comment]
`            if (max_count && m_OverSpeedPings > max_count)
            {
                ACE_GUARD_RETURN(LockType, Guard, m_SessionLock, -1);

                if (m_Session && AccountMgr::IsPlayerAccount(m_Session->GetSecurity()))
                {
                    Player* _player = m_Session->GetPlayer();
                    sLog->outError("WorldSocket::HandlePing: Player (account: %u, GUID: %u, name: %s) kicked for over-speed pings (address: %s)",
                        m_Session->GetAccountId(),
                        _player ? _player->GetGUIDLow() : 0,
                        _player ? _player->GetName().c_str() : "<none>",
                        GetRemoteAddress().c_str());

                    return -1;
                }
            }
        }`
