### ISSUE TITLE
All long-range spell creatures walk incorrectly and do not use spell attacks

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#2258]
I compiled the latest core and found that all remote law creatures did not walk the right path, and they would not use magic to attack players.

I compiled the test on May 31 and the results were all right.

22b360ee0d7c86d0315ac46a0bc56f151b194570

**Comment by FrancescoBorzi** [comment]
can anyone reproduce this? it looks fine for me

**Comment by forever2019** [comment]
I tested in Bloody Monastery and Zulfarack that the Family's remote monsters had incorrect paths and did not use magic attacks.
Always run out for a long distance, then stand still, and don't use magic attacks.

**Comment by FrancescoBorzi** [comment]
@forever2019 while we wait for someone that can reproduce the issue, it would be nice if you can find the commit that actually broke this

**Comment by boom8866** [comment]
Determine the existence of this problem
The path of legal organisms is very strange.

**Comment by pklloveyou** [comment]
![TIM截图20190904205941](https://user-images.githubusercontent.com/18535853/64256915-f2411780-cf56-11e9-8932-5ce2da45dabf.png)

**Comment by forever2019** [comment]
@pklloveyou Is compiled today's latest submission core?

**Comment by pklloveyou** [comment]
yes

**Comment by Stoabrogga** [comment]
Cannot confirm this. Tested Zul'Farrak and Scarlet Monastery on two commits:
2f74802
a15c824
On both commits the Sandfury Shadowcasters in Zul'Farrak were correctly using their spell "Shadow Bolt" and the Scarlet Adepts in Scarlet Monastery were correctly using their spell "Holy Smite" (although they just stand at a distance until they're out of mana).
