### ISSUE TITLE
Bandwidth consumption ( Instance Vault of Archavon )

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/azerothcore-wotlk#2260]
Hi, sorry native language spanish, so i will try to explain
In the instance Vault of Archavon
with 25 players the servers go from 1mb of upload bandwidth to more than 10mb, so the server lags.
It happen in the moment the boss has agro and go to attack

all the server get lag
cpu remain in 10% and memory is ok

Branch installed: Commits on Aug 31, 2019
I can't say in what commit it start i think 2 o 3 commits before i thought it was only an internet issue at first. but i tested it, and the server in that moments go from 1mb of upload to more than 10mb

Also take note upload price in my country is expensive, i will understand if it is a normal behavior but i don't think so becouse the server only had at this moment 30 players. and it only happen with the instance.

In case im wrong please excuse me.

![99](https://user-images.githubusercontent.com/29511376/64254583-b02fbb80-ceed-11e9-871d-bccb23de46ae.png)

**Comment by boom8866** [comment]
Confirm that the problem exists
1500 players need 130M bandwidth
1800 players need 200M bandwidth
confirm

**Comment by pklloveyou** [comment]
Which BOSS?

**Comment by Nemepy** [comment]
> Which BOSS?
Archavon The Stone Watcher

**Comment by pklloveyou** [comment]
I guess it has to do with"spell_archavon_rock_shards"There's a problem.
