### ISSUE TITLE
Problems encountered in world database import.

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#2262]
Compile the latest core, test #2258 .
Then edit conf/config.sh, use appsdb_assemblerdb_assembler.sh, and select 5 to import into the database.

When importing the world database, wait 20 minutes, it is not complete.

View the information in the version_db_world table of the world database as follows:

![QQ截图20190905003038](https://user-images.githubusercontent.com/49540243/64305765-f4d95680-cfc2-11e9-9251-c7d20c245076.jpg)

roce : a15c824abe870db9eb24b153b30efb40fab9c92b
OS:win10 home x64
Modular:no

#1922 This does not solve the problem.

It is recommended that a world database integrating updatas be published every three or six months.

**Comment by Viste** [comment]
lol look at your console ACCESS DENIED FOR USER:))))

**Comment by forever2019** [comment]
The console error does not affect the import.
Auh and character have been imported normally.
World database can be imported after 2019-02-17, but it cannot be imported by 2019-06-01-01.
And waiting for 20 minutes is still not complete.
So I suspect that it's the updating problem of 2019-06-01-01.

**Comment by jwh1981** [comment]
I had a similar issue (kinda). See if #2270 helps ya.

**Comment by forever2019** [comment]
@jwh1981 No, it still hasn't solved the problem.
Still stay in the submission of June 2019-01-01, unable to import.

![QQ截图20190908084714](https://user-images.githubusercontent.com/49540243/64481747-49741000-d215-11e9-9540-cf4ff1c9a766.jpg)


Please repair it.
[2019_06_01_01.zip](https://github.com/azerothcore/azerothcore-wotlk/files/3587196/2019_06_01_01.zip)

**Comment by locus313** [comment]
tested this on commit https://github.com/azerothcore/azerothcore-wotlk/commit/f62693021fa83b270eb82ce624a611ab6337917e
not able to reproduce the issue

**Comment by jwh1981** [comment]
I’m gonna try it again when I get a few.
