### ISSUE TITLE
quest=10804/kindness  bug

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#2267]
When the spiritual pterygium flew down to eat and then flew into the air again, there was a probability that it would not disappear, which led to the failure to continue the task.

core:  a15c824abe870db9eb24b153b30efb40fab9c92b

os:  win7 64bit

![QQ截图20190906010520](https://user-images.githubusercontent.com/49540243/64389400-185cd980-d075-11e9-840d-dc5b41211b33.jpg)

**Comment by Stoabrogga** [comment]
The drakes should not disappear. Instead they get an aura "Has Eaten Recently" which prevents them from being fed again for 1 minute. But I have to admit that they should not just hover in the air after being fed, but continue their waypoint movement. This seems to be something which has been forgotten in PR #1987, I'll try to figure out a fix for this.

**Comment by Stoabrogga** [comment]
Please test PR #2272.
