### ISSUE TITLE
What is mesh_extractor ?

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2269]
What is the use of mesh_extractor?
It's not used anywhere, so why is it added to Tools?
Why not delete it?

**Comment by FrancescoBorzi** [comment]
Hello. Thanks for your question.

Generic questions are always welcome, but shouldn't be reported as issue here. Please use either the forum or Stackoverflow.

Read: https://www.azerothcore.org/wiki/How-to-ask-for-help
