### ISSUE TITLE
ERROR 1118 (42000) at line 2293216: Row size too large (> 8126)

### ISSUE THREAD

**Issue by jwh1981** [azerothcore/azerothcore-wotlk#2270]
Issue: ERROR 1118 (42000) at line 2293216: Row size too large (> 8126) on Debian 10 / Mariadb 10.3

Expected result:
The database is expected to import correctly.

Current behavior:
jhendricks@monster:~/azerothcore/apps/db_assembler$ ./db_assembler.sh
1) all: Assemble all
2) bases: Assemble only bases
3) updates: Assemble only updates
4) customs: Assemble only customs
5) import-all: Assemble & Import all
6) import-bases: Assemble & Import only bases
7) import-updates: Assemble & Import only updates
8) import-customs:  Assemble & Import only customs
9) quit: Exit from this menu
[Please enter your choice]: 5
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
Generating /home/jhendricks/azerothcore/env/dist/sql/auth_base ...
Searching on /home/jhendricks/azerothcore/data/sql/base/db_auth/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/auth_updates ...
Searching on /home/jhendricks/azerothcore/data/sql/updates/db_auth/ ...
Searching on /home/jhendricks/azerothcore/data/sql/updates/pending_db_auth/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/auth_custom ...
Searching on /home/jhendricks/azerothcore/data/sql/custom/db_auth/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/characters_base ...
Searching on /home/jhendricks/azerothcore/data/sql/base/db_characters ...
Generating /home/jhendricks/azerothcore/env/dist/sql/characters_updates ...
Searching on /home/jhendricks/azerothcore/data/sql/updates/db_characters/ ...
Searching on /home/jhendricks/azerothcore/data/sql/updates/pending_db_characters/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/characters_custom ...
Searching on /home/jhendricks/azerothcore/data/sql/custom/db_characters/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/world_base ...
Searching on /home/jhendricks/azerothcore/data/sql/base/db_world/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/world_updates ...
Searching on /home/jhendricks/azerothcore/data/sql/updates/db_world/ ...
Searching on /home/jhendricks/azerothcore/data/sql/updates/pending_db_world/ ...
Generating /home/jhendricks/azerothcore/env/dist/sql/world_custom ...
Searching on /home/jhendricks/azerothcore/data/sql/custom/db_world/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
auth database exists
characters database exists
world database exists
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
auth seems empty
importing AUTH - base ...
characters seems empty
importing CHARACTERS - base ...
world seems empty
importing WORLD - base ...
ERROR 1118 (42000) at line 2293216: Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Install Debian 10 and dependencies as shown on: http://www.azerothcore.org/wiki/Requirements 
2. Follow steps on: http://www.azerothcore.org/wiki/Database-Setup
3. The issue will occur.

##### EXTRA NOTES:
I also ran the db_assembler.sh and only assembled the sql files. I manually imported the sql files (base then updates) in env/dist/sql and ran into the same issue while trying to import world_base.sql

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
43629790efa1bcb03fc91a5b240de389f0c60088

##### OPERATING SYSTEM:
Debian 10 x86_64 with all updates with dependencies listed on: http://www.azerothcore.org/wiki/Requirements installed and using Mariadb 10.3 (as installed with the dependencies.)

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by IceNet** [comment]
Add the this to your my.cnf and restart the mysql server

[mysqld]
innodb_strict_mode = 0

**Comment by jwh1981** [comment]
Thank you for the quick response. I’ll test when I get home.

**Comment by jwh1981** [comment]
That fixed it!. Might be helpful if this was listed on the normal site instructions as others with my OS/DB combo might have this issue.

**Comment by Stoabrogga** [comment]
I recently tried to import the AC DB into MariaDB and got a similar error. Setting `innodb_strict_mode = 0` just prevents warnings from getting handled as errors, but we probably should fix the actual cause of the issue.

**Comment by Viste** [comment]
Научитесь блять настраивать MySQL, тогда у вас не будет проблем.... 
Сделали дамп на 5.5 вот и мучаетесь...
https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-20.html

**Comment by gengarshadowball** [comment]
"Learn to fuck configure MySQL, then you will not have problems ....
Dumped to 5.5 here and suffer ..."

What a polite person :)

**Comment by Viste** [comment]
@gengarshadowball as i say already suck my dick dog.

**Comment by Viste** [comment]
@gengarshadowball S U C K M Y D I C K DOG!

**Comment by Tooldev94** [comment]
> "Learn to fuck configure MySQL, then you will not have problems ....
> Dumped to 5.5 here and suffer ..."
> 
> What a polite person :)

ты лох ты падла ты школьник ты сосешь ты червяк я таких в армии  пиздил иди качай сборки сва и юзай трайс  я твои примеум акки залил полная хуета у меня сервер сломался блять падла блять верни деньги за сервер сука у меня дифф 1000 теперь после твоего пула гад

**Comment by BarbzYHOOL** [comment]
Alright, insulting people have been blocked from our organization (temporarily or permanently).
