### ISSUE TITLE
New Crash again..

### ISSUE THREAD

**Issue by Undead02** [azerothcore/azerothcore-wotlk#2277]
New crash 
https://pastebin.com/6chxwpKC

**Comment by wowmane** [comment]
What is your version of  Ac ?

**Comment by Viste** [comment]
Закинь пожалуйста backtrace на https://paste2.org например, вырвиглазно выглядит тут, читать крайне трудно :)

**Comment by Undead02** [comment]
https://pastebin.com/6chxwpKC

Да на аве горшок)

**Comment by Winfidonarleyan** [comment]
Добавь больше информации об ос, напиши коммит ядра

**Comment by Undead02** [comment]
debian 8 ядро к сожалению еще чистый санвел, не как не могу перейти но в целом ядро одно и тоже

**Comment by Viste** [comment]
нет санвел, далеко не то же самое, что азерот.

**Comment by BarbzYHOOL** [comment]
stop the russian guys lol

**Comment by Ramys** [comment]
Slutty in Russian.
Lol

**Comment by Nefertumm** [comment]
Is this confirmed or something?

**Comment by FrancescoBorzi** [comment]
Can anyone explain how to reproduce this crash?

**Comment by Viste** [comment]
No, all we get is back trace

**Comment by BarbzYHOOL** [comment]
close or not to close?

**Comment by Viste** [comment]
backtrace looks like ACE issue and not according to as i recommend use ACE 6.3 or high
