### ISSUE TITLE
Quest [Bang a Gong!]

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2284]
DESCRIPTION: 
Add item 21175, go zone The Sacrab Dais , Gobject don't give Quest!

I, tested Previous quests and all work, just this gobject quest giver buged.

![Untitled](https://user-images.githubusercontent.com/52528361/64827459-85bebc00-d5d9-11e9-89c4-332ce19fd6e7.png)

https://classicdb.ch/?item=21175
https://classic.wowhead.com/quest=8743/bang-a-gong

OPERATING SYSTEM: Debian
MODULES: No
AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/8853302da9353b25c1fc534296ef8286e3851041

**Comment by Stoabrogga** [comment]
The quest was removed in patch 3.2.0:
https://wow.gamepedia.com/Bang_a_Gong!#Patch_changes

**Comment by wowmane** [comment]
@Stoabrogga 

all quests is work just this buged.

I need to this quest , can you give update?

**Comment by Stoabrogga** [comment]
AC is on patch 3.3.5a, and the quest "Bang a Gong" was removed in 3.2.0, so it is correct that it is not available.

**Comment by wowmane** [comment]
Iknow, how to fixed, gobject give quest by item=21175.

**Comment by wowtbconline** [comment]
> AC находится на патче 3.3.5a, а квест "Bang a Gong" был удален в 3.2.0, поэтому правильно, что он недоступен.

Interesting assumption. And if I want correct quest on 2.4.3. You also answer me that it is only the kernel 3.3.5 ?

**Comment by FrancescoBorzi** [comment]
@wowtbconline most of 2.4.3 content is also available in 3.3.5a

**Comment by wowmane** [comment]
@FrancescoBorzi 

Can added update for this? for needers
