### ISSUE TITLE
[Quest]  [Pink Elekks On Parade]

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2287]
DESCRIPTION: Player Can't see Npc or Gobjects , but npc and gobjects worked by gm on.

![Untitled](https://user-images.githubusercontent.com/52528361/64908397-00402680-d715-11e9-9a08-9c6ecdd5ee7c.png)

![2](https://user-images.githubusercontent.com/52528361/64908402-0fbf6f80-d715-11e9-844e-092ca791711b.png)

https://www.wowhead.com/quest=11118/pink-elekks-on-parade

OPERATING SYSTEM: Debian
MODULES: No
AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/8853302da9353b25c1fc534296ef8286e3851041

**Comment by Stoabrogga** [comment]
You have to get drunk to see the Pink Elekks. Tested this and it is working as intended.
