### ISSUE TITLE
CORE/instance TrialOfTheCrusader/Map texture

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#2289]
TrialOfTheCrusader

##### SMALL DESCRIPTION:
As shown in the picture
![TIM截图20190915164531](https://user-images.githubusercontent.com/18535853/64919220-bfaae080-d7da-11e9-815f-33a7f82aa715.jpg)
![TIM截图20190915164610](https://user-images.githubusercontent.com/18535853/64919223-c20d3a80-d7da-11e9-9bd0-c466870ffaf9.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
BOSS should not fall under the floor

##### CURRENT BEHAVIOUR:
As shown in the picture

##### STEPS TO REPRODUCE THE PROBLEM:
1.  .go c 202957
2.  .modify speed  6
3.  Start fighting, then move left and right.

**Comment by pklloveyou** [comment]
![TIM截图20190915172108](https://user-images.githubusercontent.com/18535853/64919438-3fd24580-d7dd-11e9-997b-ce9503641218.jpg)

**Comment by pklloveyou** [comment]
![TIM截图20190915172404](https://user-images.githubusercontent.com/18535853/64919468-a6576380-d7dd-11e9-9b56-4a06461f1ab1.jpg)

**Comment by pklloveyou** [comment]
All BOSS ground will fall on the floor

**Comment by pklloveyou** [comment]
![TIM截图20190915172614](https://user-images.githubusercontent.com/18535853/64919489-f33b3a00-d7dd-11e9-8d30-48ef7d2e2655.jpg)

**Comment by pklloveyou** [comment]
![TIM截图20190915172857](https://user-images.githubusercontent.com/18535853/64919516-53ca7700-d7de-11e9-9cca-1ecacd216347.jpg)

**Comment by wowmane** [comment]
OH MAN!

**Comment by pklloveyou** [comment]
LOL

**Comment by pklloveyou** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19865
https://github.com/TrinityCore/TrinityCore/commit/a07ed72a9bb3be753a065e161ea8fb7aefa76d59
https://github.com/TrinityCore/TrinityCore/commit/9614f9d8cf295d4135346d59e67fa47b51d2ed88
https://github.com/TrinityCore/TrinityCore/commit/cfb0f9fb19c03677b127f09407a6bd00bfefbe55

**Comment by pklloveyou** [comment]
Solved after downloading the latest MAP

**Comment by pklloveyou** [comment]
Solved after downloading the latest MAP
