### ISSUE TITLE
Warlock Spell [Conflagrate]

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2302]
DESCRIPTION:
Cannot active its effect for Destructions aoe like Rain of fire!

1. creat character class warlock
2. train spell and talent
3. use immolate & shadowflame
4. and finally Conflagrate 
. It doesn't work well, Used late Conflagrate!

https://wotlk.cavernoftime.com/spell=17962

AC HASH/COMMIT:
AzerothCore rev: https://github.com/azerothcore/azerothcore-wotlk/commit/ae7f128b964e23413c1599b509e3d13e3a088a80

OPERATING SYSTEM: CentOS

MODULES: No

**Comment by wizzymore** [comment]
What exactly is the problem?
Conflagrate doesn't consume immolate or shadowflame?
It doesn't deal the bonus dmg?
You have Glyph of Conflagrate and immolate or shadowflame still gets consumed?

**Comment by vhiperdev** [comment]
https://www.youtube.com/watch?v=yq3N1fP3a24&feature=youtu.be&t=194 Intended

That's an intended behaviour for the spell to be "blizzlike"

**Comment by Stoabrogga** [comment]
Closing this as the issue description is not sufficient.
