### ISSUE TITLE
Cotire Compilation Error

### ISSUE THREAD

**Issue by SeluneArkadia** [azerothcore/azerothcore-wotlk#2306]
Cotire Compilation Error

##### SMALL DESCRIPTION:

CMake Error at compilation

##### CURRENT BEHAVIOUR:

azeroth@belisama:~/azerothcore/build$ cmake ../ -DCMAKE_INSTALL_PREFIX=/var/games/wow/server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=0 -DSCRIPTS=1

[ 13%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/UprightFrame.cpp.o
[ 13%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector2.cpp.o
[ 13%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector3.cpp.o
[ 13%] Building CXX object deps/g3dlite/CMakeFiles/g3dlib.dir/source/Vector4.cpp.o
[ 13%] Linking CXX static library libg3dlib.a
[ 13%] Built target g3dlib
[ 13%] Generating CXX prefix source src/common/cotire/common_CXX_prefix.cxx
CMake Warning (dev) at src/common/common_CXX_cotire.cmake:17:
  Syntax Warning in cmake code at column 99

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:3596 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

[ 13%] Generating CXX prefix header src/common/cotire/common_CXX_prefix.hxx
CMake Warning (dev) at src/common/common_CXX_cotire.cmake:17:
  Syntax Warning in cmake code at column 99

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:3596 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

[ 13%] Building CXX precompiled header src/common/cotire/common_CXX_prefix.hxx.pch
CMake Warning (dev) at /var/games/wow/azerothcore/build/src/common/common_CXX_cotire.cmake:17:
  Syntax Warning in cmake code at column 99

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:3596 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

In file included from <built-in>:407:
<command line>:5:19: warning: missing terminating '"' character [-Winvalid-pp-token]
#define _CONF_DIR "
                  ^
<command line>:6:9: error: macro name must be an identifier
#define /var/games/wow/server/etc"" 1
        ^
<command line>:13:15: warning: missing terminating '"' character [-Winvalid-pp-token]
#define NDEBUG" 1
              ^
<command line>:13:15: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
3 warnings and 1 error generated.
CMake Error at /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:1990 (message):
  cotire: error 1 precompiling
  /var/games/wow/azerothcore/build/src/common/cotire/common_CXX_prefix.hxx.
Call Stack (most recent call first):
  /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:3694 (cotire_precompile_prefix_header)

make[2]: *** [src/common/CMakeFiles/common.dir/build.make:64: src/common/cotire/common_CXX_prefix.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:890: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
--------------------------

##### STEPS TO REPRODUCE THE PROBLEM:

1. cd azerothcore/build
2. make clean
3. cmake ../ -DCMAKE_INSTALL_PREFIX=/var/games/wow/server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=0 -DSCRIPTS=1
4. make -j 8

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit 8061351128463cb41e3a208b733f9a91691adb93

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

mod-ah-bot  mod-eluna-lua-engine  mod-guildhouse  mod-npc-beastmaster  mod-reward-played-time  mod-weekend-xp  mod-who-logged

##### OTHER CUSTOMIZATIONS:

Database minor changes to fit to the modules requirements

**Comment by FrancescoBorzi** [comment]
@SeluneArkadia can you please test this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/2305

and let us know if that solves the issue for you? (please comment in the PR the result of your test, not here)

**Comment by SeluneArkadia** [comment]
Still the same issue : 

`<command line>:13:15: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
3 warnings and 1 error generated.
CMake Error at /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:1990 (message):
  cotire: error 1 precompiling
  /var/games/wow/azerothcore/build/src/common/cotire/common_CXX_prefix.hxx.
Call Stack (most recent call first):
  /var/games/wow/azerothcore/deps/cotire/CMake/cotire.cmake:3694 (cotire_precompile_prefix_header)


make[2]: *** [src/common/CMakeFiles/common.dir/build.make:64: src/common/cotire/common_CXX_prefix.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:890: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by Stoabrogga** [comment]
@SeluneArkadia 
Could you please try PR #2307?
