### ISSUE TITLE
quest bug  [The Drakkensryd]

### ISSUE THREAD

**Issue by wowmane** [azerothcore/azerothcore-wotlk#2308]
DESCRIPTION: The quest in the last version AC is have been buged.

Use the hyldnir harpoon to defeat 10 hyldsmeet darkeriders at the template of stroms, use the yldnir hrpoon on a column ornament to exit the darkkendsryd and speak to thorim when youive succeeded.

<b> BUG:  Can not to target npcs "Proto-darkes" for use Hyldnir Harpoon</b>

https://www.wowhead.com/quest=12886/the-drakkensryd

AzerothCore rev: https://github.com/azerothcore/azerothcore-wotlk/commit/ae7f128b964e23413c1599b509e3d13e3a088a80

OPERATING SYSTEM: CentOS

MODULES: No

**Comment by Stoabrogga** [comment]
I tested the quest and it is working as intended. Sorry, but I've got enough of your pointless issues and will ignore them in the future because they are just wasting my time.
