### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by 3majed** [azerothcore/azerothcore-wotlk#231]
**Description**:
World update sql error
**Current behaviour**: Tell us what happens
`-- -------------------------------------------------------- 
-- 2016_11_05_02.sql 
-- -------------------------------------------------------- 
-- DB update 2016_11_05_01 -> 2016_11_05_02
DROP PROCEDURE IF EXISTS `updateDb`;
CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2 */
SHOW DATABASES;
/* Entering session "Unnamed" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='world';
SHOW TABLE STATUS FROM `world`;
SHOW FUNCTION STATUS WHERE `Db`='world';
SHOW PROCEDURE STATUS WHERE `Db`='world';
SHOW TRIGGERS FROM `world`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='world';
SHOW CREATE TABLE `world`.`version_db_world`;`

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
Master
**AC hash/commit**:  

**Operating system**:  
windows server 8r2
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by ShinDarth** [comment]
I've just tested again the script ``2016_11_05_02.sql`` and it imports fine for me, it doesn't give me any error.

What is the line that is causing the error to you?

**Comment by 3majed** [comment]
`-- DB update 2016_11_05_01 -> 2016_11_05_02
DROP PROCEDURE IF EXISTS `updateDb`;
CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2 */`

**Comment by 3majed** [comment]
Ok it may be only me who got this issue, however if you got the same issue try to use Navicat for MySQL to import the sqls :)

and big thanks to ShinDarth

**Comment by dd667** [comment]
got same issue, even when using navicat doesn't work.

**Comment by d3tr0l** [comment]
same issue here, it is not working, does not matter if i use Navicat or HeidiSQL or anything else...

**Comment by justdothings** [comment]
![capture](https://user-images.githubusercontent.com/17615911/32699240-cdff1ec4-c7cb-11e7-96a9-e69875cd1ce4.PNG)

**Comment by justdothings** [comment]
@ShinDarth tried with navicat 12 and navicat 11 also updated mysql server version but getting same error
