### ISSUE TITLE
CFBG Stats List

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2310]
##### SMALL DESCRIPTION:

when use cross bg and player go in bg and change faction, if change (Horde to Alliance) or (Alliance to Horde) , when open stats you can see colors not change.

![WoWScrnShot_092719_014801](https://user-images.githubusercontent.com/54138710/65728994-94bd6800-e0c9-11e9-910b-0e5e49cf2e5c.jpg)

![WoWScrnShot_092719_014806](https://user-images.githubusercontent.com/54138710/65728999-9850ef00-e0c9-11e9-8525-f1213470ab3e.jpg)

![WoWScrnShot_092719_014811](https://user-images.githubusercontent.com/54138710/65729010-9d15a300-e0c9-11e9-8895-197e11fe93f4.jpg)

must change color to blue when horde changed to alliance and alliance too change to red color.

##### STEPS TO REPRODUCE THE PROBLEM:

1. enable cross bg
2. command : .debug bg
3. join 2 horde hero , or 2 alliance hero in bg.

##### BRANCH(ES):

master

##### MODULES:

cfbg

**Comment by wowmane** [comment]
What is this motd, welcome to TrinityCore :d

**Comment by LichKing255** [comment]
This is azeroth , just changed motd 😒😒

**Comment by FrancescoBorzi** [comment]
@LichKing255 please read:

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L1447

**Comment by LichKing255** [comment]
> @LichKing255 please read:
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L1447

So why you added config for Motd? :)
I had not seen this text. reopen issue.

**Comment by Winfidonarleyan** [comment]
Don't support if you delete standard motd

**Comment by LichKing255** [comment]
> Don't support if you delete standard motd

You can not fix it, So it was closed.

**Comment by Zausender** [comment]
Why you closing issue when issue exist on AzerothCore with CFBG module?

**Comment by LichKing255** [comment]
Reopn this, if @Winfidonarleyan can not fix it someone else might be able to fix it.

**Comment by FrancescoBorzi** [comment]
@LichKing255 @Zausender it should be opened here:

https://github.com/azerothcore/mod-cfbg/issues

**Comment by LichKing255** [comment]
> @LichKing255 @Zausender it should be opened here:
> 
> https://github.com/azerothcore/mod-cfbg/issues

must edit source, can not fix on module.

**Comment by Shard-MW** [comment]
I can't confirm it. I don't have this issue 
[https://imgur.com/zWd6gTd](url)
I'm using two horde characters and cfbg module on commit https://github.com/azerothcore/azerothcore-wotlk/commit/69ebb5081bab5abfd5e9cc1fb86a955493ba2215

I know that, when you JUST join with 2 horde players, the table shows "2 Horde players" but you have to wait 2-3 sec and reopen it to get it refreshed and you will see "1 Horde player - 1 Alliance player"

**Comment by LichKing255** [comment]
> I can't confirm it. I don't have this issue
> https://imgur.com/zWd6gTd
> I'm using two horde characters and cfbg module on commit [69ebb50](https://github.com/azerothcore/azerothcore-wotlk/commit/69ebb5081bab5abfd5e9cc1fb86a955493ba2215)
> 
> I know that, when you JUST join with 2 horde players, the table shows "2 Horde players" but you have to wait 2-3 sec and reopen it to get it refreshed and you will see "1 Horde player - 1 Alliance player"
> 
> I don't know if you joined the battleground with _.GM ON_ but the truth is, that if you join as _.GM ON_ and then do _.GM OFF_, your real faction is restored.
> So if you join with 2 horde players with _.GM ON_ and do _.GM OFF_ inside the battleground, the two players will be in different sides but will have the same faction. Doing _.GM ON_ and _.GM OFF_ inside the battleground will result the same

not change for me after 2-3 sec or 2-3 min , without .gm on i join battleground.

**Comment by Nefertumm** [comment]
Closing, if this is happening, open an issue on the module's github.
