### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by remamakiller** [azerothcore/azerothcore-wotlk#2313]
##### SMALL DESCRIPTION:

Trying to compile gives me an error and closes the compilation
Attached image

##### STEPS TO REPRODUCE THE PROBLEM:

1. Trying to compile gives me an error and closes the compilation
Attached image
2. [url=https://postimg.cc/9wwsFNdK][img]https://i.postimg.cc/Y0d7R5hr/error.png[/img][/url]
3. 

##### BRANCH(ES):

master

**Comment by wizzymore** [comment]
Either:
- reinstall visual studio
- Right click the project, go to Properties. Under Configuration Properties, go to General. Change your Platform Toolset to one of the available ones.
