### ISSUE TITLE
CFBG

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#2314]
Im not saying what has happened to this core this is more of a statement, but since the CFBG has been implemented it has caused a lot off issues with the core its self. i no longer contribute to this core but in my personal opinion cfbg should be reverted, it shouldn't of been pushed or commited to the core until fully tested which it has not been.

**Comment by talamortis** [comment]
Revert all changes and ill try work on a CFBG patch for azerothcore. - I will only do if changes get reverted.

**Comment by Stoabrogga** [comment]
What issues? Perhaps name a few ones if there are lots of them.

**Comment by FrancescoBorzi** [comment]
"lot of issues" doesn't help, we need to know what issues are there and how to reproduce them so we can either try to fix them or revert whatever caused them.

So please mention a few of them

**Comment by Stoabrogga** [comment]
Closing this as there is no information to work with.
