### ISSUE TITLE
Item random enchantments (stats) not generated on player buy/.send items

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#2316]
##### SMALL DESCRIPTION:
Item random enchantments (stats) not generated when player buys the item, but they're when we use .add/drop the item
Same for .send items 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When you buy an item with random enchantments (stats) from a vendor, stats should be generated
Items sent by mail (that were not looted) are supposed to get their random properties generated

##### CURRENT BEHAVIOUR:
Currently, the stats generation works only when a player loot the item from a mob or from .additem
When we try to buy an item with random stats from a vendor or using .send items, players get the item without stats.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Add an item with random stats to a vendor (.npc add it 727)
2. Buy it
3. Observe that the item has no random stats.

1. Use .send items
2. Look at your mailbox and observe that sent items don't have random properties

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
commit : 72faaf643d461ca5cf2798e019c62682b57f155d

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
None

**Comment by Stoabrogga** [comment]
Is there a "blizzlike" vendor who sells items with random stats? I thought those items only drop from mobs.

**Comment by Shard-MW** [comment]
I don't know if there was some on retail, but currently there is no vendor that sells those items on AC.
(According to :
`SELECT DISTINCT entry FROM npc_vendor WHERE item IN (SELECT entry FROM item_template WHERE (RandomProperty != 0 OR RandomSuffix != 0));`)

**Comment by Shard-MW** [comment]
Just noticed that sending items by using .send items don't generate Random Properties too.
