### ISSUE TITLE
BWL/Razorgore the Untamed BUG

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#2322]
My partner and I had problems experiencing BWL copies.
Razorgore the Untamed cannot be killed correctly.

The problems encountered are consistent with the submission below. Please repair and improve them.

Thank you

#785

72faaf643d461ca5cf2798e019c62682b57f155d

**Comment by FrancescoBorzi** [comment]
> The problems encountered are consistent with the submission below.

so why opening a new issue instead of confirming the existing one?

If you are reporting something that has not been reported before, please add more details in your report. Otherwise just comment the existing issue.
