### ISSUE TITLE
Item random properties not generated in many cases

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#2324]
_I decided to open a new issue to be more clear and close the old one_ #2316 

##### SMALL DESCRIPTION:
Item random properties are not generated in many cases.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
An item with random properties should have it random stats generated on creation.

##### CURRENT BEHAVIOUR:
Random stats are generated only on .add or item loot.
They're not generated when :
- The player buys the item from a vendor
- The player directly equip the item from a vendor (drag and drop to equip slot)
- Sending item through command (.send items)

##### STEPS TO REPRODUCE THE PROBLEM:
ItemID : 727 
1. Add the item to a vendor (.npc add it 727) and buy it.
2. Drag and drop the sold item to your slot directly from the vendor
3. Send mail to yourself thourgh .send mail command

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
commit : 72faaf6

##### OPERATING SYSTEM:
Windows 10

**Comment by wizzymore** [comment]
@Shard-MW please help me out by checking my PR
