### ISSUE TITLE
[Crash][No log][Fix]HandleMovementOpcodes

### ISSUE THREAD

**Issue by wlasser** [azerothcore/azerothcore-wotlk#2327]
**This affect current master branch, with latest updates.
AC hash: 9e2bd353d2de485593b384a137cd1f3c9dc9f91a**

Path: src/server/game/Handlers/MovementHandler.cpp

There is possible to crash server.
Who know how to reproduce - can do it, without my instruction. No solution for haxxors.
Ok, building client movement packet wiht forward/backward/strafe left/right without adding guid to packet - crash server.
This can be fast overlooked in MovementHadler.cpp, on HandleMovementOpcodes:
there is no check incomming guid.

Well, just make advanced check, and log it:
```
recvData.readPackGUID(guid);
ASSERT(!guid);
```
or:
```
if (!guid)
return;
```

Sorry for "not templated" post, but no care.

**Comment by FrancescoBorzi** [comment]
@wlasser please add your AC version (commit hash)

**Comment by wlasser** [comment]
> @wlasser please add your AC version (commit hash)

done

**Comment by wowmane** [comment]
I can, Confirm, this crash.

**Comment by Mestremagos** [comment]
How do you reproduce this error?
Log: 
https://pastebin.com/bJidXUwC

**Comment by wlasser** [comment]
well, affter look over code - there is just need check with objectAccessor or something, to find realy object. if this is failed - you must finish reading packet.

**Comment by AndrewColl90** [comment]
@wlasser.

Could you help me to understand how I can reproduce this error to improve my server defenses? Cause I got a guy what are doing this bug on my server and I am a bit lost about it.

I need understand what him are using to reproduce that and stop him.

If you know how to solve this problem, may we can negociate.

**Comment by Helias** [comment]
Hope this could help: https://github.com/azerothcore/azerothcore-wotlk/pull/2410
I added some checks, I added also a check `!guid` as this issue suggested.

**Comment by wlasser** [comment]
> if you can provide me more details I'll try it.
any "prove" in this topic just make haxxorz more happy. i am look over commit, you are done for check mover. but crash, is going some first. anyway you must check valid guid for world in context, with trinity::objectaccessor or something.

**Comment by Helias** [comment]
If you mean `ObjectAccessor::FindPlayer(guid)`, it only checks if `player` exists and if `IsInWorld`, but I already do this using `if (!mover || !(mover->IsInWorld()) || ...`.

Anyway, I didn't get if your server still crashes or not with the PR, did you test it?

**Comment by wlasser** [comment]
> Anyway, I didn't get if your server still crashes or not with the PR, did you test it?

i'll check it latter.
