### ISSUE TITLE
[Quest] Hotter than Hell

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#2335]
##### SMALL DESCRIPTION:
Related quest item(Unfired Key Mold) can be used everywhere

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Unfired Key Mold can be used only in area of Fel Reaver's corpse.

##### CURRENT BEHAVIOUR:
Unfired Key Mold can be used/casted everywhere, you don't need to meet the criteria for the quest to use this item. The casted spell is -> [Heat Mold](https://wowgaming.altervista.org/aowow/?spell=38202). Link to the item -> [Unfired Key Mold](https://wowgaming.altervista.org/aowow/?item=31251)

##### STEPS TO REPRODUCE THE PROBLEM:

1. There are 2 ways. You can complete all previous quests for the Shattered Halls Key, or you can .qu add 10764(Alliance)/10758(Horde)
2. Use quest related item

##### EXTRA NOTES:

An item called [Medivh's Journal](https://wowgaming.altervista.org/aowow/?item=23934) for quest [The Master's Terrace](https://wowgaming.altervista.org/aowow/?quest=9645) have an identical issue. I understand, that those are disabled and kinda irrelevant quests for WoTLK, but still.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
a8a27c2

##### OPERATING SYSTEM:
Win 10 x64 LTSC 1903

##### MODULES:
No, i'm not, it's a clean build

##### OTHER CUSTOMIZATIONS:
Same as modules.

**Comment by wizzymore** [comment]
Please test the PR and provide feedback
