### ISSUE TITLE
Missing deDE Quest Locales (Offer Reward & Request Items)

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2346]
##### SMALL DESCRIPTION:

Nearly all quest texts of the request items and the offer rewards are not translated in german.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Wow deDE Client should be able to use all german quest texts. 

##### CURRENT BEHAVIOUR:

Missing deDE Locales in the following db tables:

- quest_request_items_locale
- quest_offer_reward_locale. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Add any quest
2. get the required stuff (Requested items)
3. End the quest (Offer rewards)

##### EXTRA NOTES:

Using Azerothcore Solo Repack from Brookstech

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
d2b409e77ed0+ 2019-06-15 11:51:37 -0500

##### OPERATING SYSTEM:
Windows 10 Home Premium

##### MODULES:

- Auctionhouse Bot
- npc_beastmaster
- npc_enchanter
- BuffMaster
- VASAutoBalance 
- Transmogrifier

##### OTHER CUSTOMIZATIONS:

- AutoRevive on death
- NPC Instance, LFG, Dungeon cooldowns reset
- Individual-XP

**Comment by quilumipe** [comment]
the same happens with the other locales like spanish and french

**Comment by Endeffect93** [comment]
@BarbzYHOOL 
 I found a translated DB and wan't to edit the tables to our DB Structure an then test to import.

What does the first column with an int in the table 'quest_offer_reward_locale' mean?

**Comment by Helias** [comment]
![immagine](https://user-images.githubusercontent.com/519778/67212282-6c9cfc80-f41c-11e9-8593-14f1e075201c.png)

If you mean `ID` for first column, it's just the ID of the Quest.
Locale is the local language.

Anyway I just checked the DB, there are 1700 deDE quests and 44 esES quests, so several quests language are missing.

**Comment by Endeffect93** [comment]
Ah Sry i meant the 'VerifiedBuild' @Helias. 
The ID is clear what it does :D

**Comment by Endeffect93** [comment]
@Helias

I found some sql files from the GTDB project on Github https://github.com/gpn39f/GTDB where a lot of quests where i noticed they are not translated are stored. 

Could you have a look at it?

**Comment by Helias** [comment]
Sure.

**Comment by Helias** [comment]
There are several contents in GTDB, but it is for a old TrinityCore version, so we need to convert the sql structure into our and than import the sql.

**Comment by Endeffect93** [comment]
Exactly, i already worked a little bit on the structure of the sql so that i fit's to our db but i can't get further wirh my SQL knowledge 😓

Definitely the request item and offer reward texts are needed, some objectives too but i will check this later...

If you could prepare it then i would test them 👍🏻

**Comment by Endeffect93** [comment]
Thx 👍🏻😁

**Comment by Helias** [comment]
The GTDB is still incomplete, like "Work in progress", the project probably stopped 6 years ago.

I imported the followings table and related data, I removed the duplicates data:
- creature_text_locale (452)
- creature_template_locale (only 40, the others 22k are already imported)
- gossip_menu_option_locale (2924)
- item_template_locale (165)
- npc_text_locale (5395)
- page_text_locale(28)
- points_of_interest_locale (0) -> AC has already all data
- trinity_string (904)

I don't know the correspond table in AC for:
- creature_ai_texts
- db_script_string

TODO: quest_template_locale

I'm working on it, I will finish this last table and make the PR.

**Comment by Helias** [comment]
locales_quest done.

Imported the data and distributed into the following tables:
- quest_template_locale (1), these quests are already translated for deDE client.
- quest_request_items_locale (3082)
- quest_offer_reward_locale (5680)

**Comment by Endeffect-AT** [comment]
Nice, you saved my Weekend✌🏻 I will check it out in a few hours, i noticed every non-translated quest i ever made 😅🙈

**Comment by Helias** [comment]
PR opened, feel free to check the SQL file :wink:
