### ISSUE TITLE
Cape of the Black Baron is missing

### ISSUE THREAD

**Issue by katz1** [azerothcore/azerothcore-wotlk#2349]
##### EXPECTED BLIZZLIKE BEHAVIOUR:
Cape of the Black Baron (13340) should be dropped by Baron Rivendale (10440);

##### CURRENT BEHAVIOUR:
Cape of the Black Baron (13340) is not dropped by anything according to creature_loot_template.

##### AC HASH/COMMIT:
43629790efa1bcb03fc91a5b240de389f0c60088

**Comment by Helias** [comment]
Thanks for the issues, test the fix https://github.com/azerothcore/azerothcore-wotlk/pull/2350
