### ISSUE TITLE
Some Gossips not load on Debug mode

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2352]
##### SMALL DESCRIPTION:
some text gossip for example teleporters icc not load from DB on Debug Mode (Just Debug mode, Work on RelWithDBInfo and Release)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

must load :|

##### CURRENT BEHAVIOUR:
![WoWScrnShot_101419_144603](https://user-images.githubusercontent.com/54138710/66747523-a22c6d80-ee91-11e9-8b38-6184fb668032.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. compile on debug
2. go to icc and kill lord marrow
3. go to near teleporter and right click for see gossips

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/4e7e98b542baacb2e0d68c80778e22f6637102d3

##### OPERATING SYSTEM:
Win 10 , MySQL 5.7

##### MODULES:
CFBG

**Comment by LichKing255** [comment]
@Stoabrogga @FrancescoBorzi 

Can check this ? this is very important.

**Comment by Stoabrogga** [comment]
Cannot confirm, the texts where clearly visible. Would also not make sense, as the debug mode doesn't change the code in the "icecrown_citadel_teleport" GameObjectScript. I tested on Ubuntu 16.04 using debug (-DCMAKE_BUILD_TYPE=Debug), cmake 3.15.4, clang 7.1.0 and using commit 7d09a260e8a8fde8074a4af89ab636d026384617.

Could it be that you disabled compiling the scripts? (-DSCRIPTS=0)

**Comment by LichKing255** [comment]
> Cannot confirm, the texts where clearly visible. Would also not make sense, as the debug mode doesn't change the code in the "icecrown_citadel_teleport" GameObjectScript. I tested on Ubuntu 16.04 using debug (-DCMAKE_BUILD_TYPE=Debug), cmake 3.15.4, clang 7.1.0 and using commit [7d09a26](https://github.com/azerothcore/azerothcore-wotlk/commit/7d09a260e8a8fde8074a4af89ab636d026384617).
> 
> Could it be that you disabled compiling the scripts? (-DSCRIPTS=0)

no , i don't disable scripts.

**Comment by Stoabrogga** [comment]
Sorry, but then I have no idea. Perhaps someone else could test this on Windows?

**Comment by LichKing255** [comment]
> Sorry, but then I have no idea. Perhaps someone else could test this on Windows?

Code does not change, only the text is not loaded. Gossips are added, but their text is not visible.

**Comment by Stoabrogga** [comment]
Like I said, no idea. For me everything's working like expected. I also used a fresh DB for my test.

**Comment by LichKing255** [comment]
I don't know what problem , but again recompile and fixed . closed
