### ISSUE TITLE
Achievements Statistics

### ISSUE THREAD

**Issue by Zausender** [azerothcore/azerothcore-wotlk#2356]
Achievements Statistics doesn't work correctly

##### SMALL DESCRIPTION:

Doesn't need small description, there is current behaviour where i can write what's happening.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The stats should be saved there.

##### CURRENT BEHAVIOUR:

If you do 10 duels, win 5 and losse 5 duels, the statistics in the "Compare Achievements" aren't show correctly there.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get two players, and click on Compare Achievements => Player vs Player => World. There will be Duels Won, Duels Lost. The stats isn't correct.
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/003e8fa4598bcbbc28367b752c1183fed84a72f8

##### OPERATING SYSTEM:

Debian 9

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Endeffect-AT** [comment]
Didn't test the Issue above, but yes there are more errors in the statistics. 
Example the Quest statistics rewarded daily:

![WoWScrnShot_111019_150830](https://user-images.githubusercontent.com/55922592/68950460-808a1300-07bc-11ea-84ad-2b389ec9f110.jpg)

Would be nice if i can do so much quest in one day :D

**Comment by Kitzunu** [comment]
I believe this to be a client bug, I have done research into it but cannot find anything validating to why it should not work.

What I have tested is why Gunship battle 10/25/nm/hc stores correctly, but for example, marrowgar stats goes through everything. I have yet to find the issue though
