### ISSUE TITLE
Deathbringer's Will proc

### ISSUE THREAD

**Issue by Zausender** [azerothcore/azerothcore-wotlk#2363]
The item proc incorrect

##### SMALL DESCRIPTION:

When it activate it change gender

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should return character orginal gender

##### CURRENT BEHAVIOUR:

When item procs the character gender sholdn't be changed.

##### STEPS TO REPRODUCE THE PROBLEM:

Equip item https://wotlk.evowow.com/?item=50362 , go on dummy and attack it. When you are transformed, log out and login again. Wait until buff gone, if you re female, you become MALE and this is totally incorrect
1. 
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/003e8fa4598bcbbc28367b752c1183fed84a72f8

##### OPERATING SYSTEM:

Debian 9

##### MODULES:

no

**Comment by Stoabrogga** [comment]
Cannot reproduce this. Tested with different characters and after the transformation ends the original state of the character is restored (also tested logout / login while transformed).
Tested with commit 6b395e9b70f63eb80656ee41904898adbf412752.

**Comment by Zausender** [comment]
you are right @Stoabrogga it is issue from module i downloaded, crossfactions. Disabling it, the bug dissapear thanks

**Comment by talamortis** [comment]
This issue is produced with a previous commit that got placed.

**Comment by Stoabrogga** [comment]
@Zausender 
I tested again using commit 2cb28e5f5342e92934b5d7d3acd771a7785be82d and the module https://github.com/azerothcore/mod-cfbg but still cannot reproduce the issue 🤔.
