### ISSUE TITLE
Crash server by wow client.

### ISSUE THREAD

**Issue by FrozenTT** [azerothcore/azerothcore-wotlk#2366]
I know the bug.

**Comment by Helias** [comment]
What do you mean with "special characters"? Give me an example, I would try it

**Comment by FrozenTT** [comment]
> What do you mean with "special characters"? Give me an example, I would try it

😥😥😥 like this

**Comment by Helias** [comment]
I can't copy that, my PC convert them into: `disappointed_relieveddisappointed_relieveddisappointed_relieved`.

I tried with ⚽️🏋 and WoW convert it on `??`.


![immagine](https://user-images.githubusercontent.com/519778/67157637-05554e80-f32f-11e9-9e71-09fed98a8841.png)


I'm using Linux - Ubuntu 18.04.3 LTS, what are you using?

**Comment by FrozenTT** [comment]
> I can't copy that, my PC convert them into: `disappointed_relieveddisappointed_relieveddisappointed_relieved`.
> 
> I tried with ⚽️🏋 and WoW convert it on `??`.
> 
> ![immagine](https://user-images.githubusercontent.com/519778/67157637-05554e80-f32f-11e9-9e71-09fed98a8841.png)
> 
> I'm using Linux - Ubuntu 18.04.3 LTS, what are you using?

you must use tool send pactek

**Comment by Helias** [comment]
@FrozenTT which tool? could you show me an example, I want to test it ;-)

**Comment by Helias** [comment]
with the following PR the problem persist? https://github.com/azerothcore/azerothcore-wotlk/pull/2407
