### ISSUE TITLE
Seek help! I installed according to wiki, but it was always compilation failure. What did I do wrong? I hope you can help me. Thank

### ISSUE THREAD

**Issue by Orangeat** [azerothcore/azerothcore-wotlk#2369]
```23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (121): error c2001: line break in constant

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (122): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (122): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (122): error c2001: line break in constant

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (123): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (123): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (123): error c2001: line break in constant

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (124): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (124): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (129): error c2001: line break in constant

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (130): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (130): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (130): error c2001: line break in constant

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (131): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (131): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (131): error c2001: line break in constant

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (132): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ worldserver \ master.cpp (132): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

23 > D: \ stygiancore \ source \ SRC \ server \ game \ Battlegrounds \ battleground. H (423): warning c4267: "return": converting from "size" to "uint32", possibly losing data (compiling source file D: \ stygiancore \ source \ SRC \ server \ worldserver \ commandline \ clirunnable. CPP)

23 > D: \ stygiancore \ source \ SRC \ server \ game \ Battlegrounds \ battleground. H (433): warning c4267: "return": converting from "size_t" to "uint32", possibly losing data (compiling source file D: \ stygiancore \ source \ SRC \ server \ worldserver \ commandline \ clirunnable. CPP)

23 > D: \ stygiancore \ source \ SRC \ server \ game \ Battlegrounds \ battleground. H (435): warning c4267: "return": converting from "size" to "uint32", possibly losing data (compiling source file D: \ stygiancore \ source \ SRC \ server \ worldserver \ commandline \ clirunnable. CPP)

23 > D: \ stygiancore \ source \ SRC \ server \ game \ spells \ spellmgr. H (684): warning c4267: "return": converting from "size" to "uint32", possibly losing data (compiling source file D: \ stygiancore \ source \ SRC \ server \ worldserver \ worldthread \ worldrunnable. CPP)

23 > D: \ stygiancore \ source \ SRC \ server \ game \ entities \ player \ player. H (1627): warning c4267: "return": convert from "size" to "uint32", possibly losing data (compile source file to translate source file to D: \ stygiancore \ source \ SRC \ server \ worldserver \ worldthread \ worldrunnable. CPP)

23 > finished building project "worldserver. Vcxproj" - failed.

24 > ------ rebuild all started: Project: all build, configuration: debug x64------

24 > building custom rule D: / stygiancore / source / cmakelists.txt

==========Rebuild all: 19 succeeded, 5 failed, 0 skipped==========
```

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

**Comment by Helias** [comment]
"stygiancore"?
did you try the original azerothcore? take the source from the repository

**Comment by FrancescoBorzi** [comment]
sorry but we don't support other cores

**Comment by Orangeat** [comment]
Thank you for answering my question in such a hurry. But I'm on the verge of collapse, and I 've never compiled the azerothcore, and this is my first attempt. After Wikipedia introduced the cloned source code, it went through four days and nights and continuously downloaded the source code. It had suspected that the source code download process was incomplete. So there's a repeat download process. However, the compilation failed, suggesting many grammatical errors. Forgive me for my poor English. Uninstall and reinstall Microsoft Visual Studio 2017 compilation from Microsoft Visual Studio 2019 still failed. I'm really going to crash right now, because the repair from the azerothcore is really good, and now it's very clear that compilation requires complex operations, and I hope you can help me and let me feel the joy of this azerothcore, thank you very much! Hey! I'm using Windows 10 64bit Pro.

**Comment by Orangeat** [comment]
How long ago was the original core azerothcore?

**Comment by Orangeat** [comment]
I'm sorry. I used the standard core azerothcore, and I copied it as a branch source that has been published in other branches. I think the ready-made source code should be compiled very smoothly, but the idea is wrong, simply pasted this, but the content is basically the same.

**Comment by FrancescoBorzi** [comment]
@Orangeat you can try either the traditional setup or the docker setup:

- http://www.azerothcore.org/wiki/Installation

- http://www.azerothcore.org/wiki/Install-with-Docker

the Docker setup should be easier

**Comment by Orangeat** [comment]
Thank you for your help. I'll try your way. Thank you.

**Comment by Orangeat** [comment]
Hello, this is not very clear. Can you introduce it to me further? Can it run on Windows 10?

**Comment by Helias** [comment]
Hey, of course you can install it on Windows.
If you want to follow the traditional setup:

Install the requirements, follow this: http://www.azerothcore.org/wiki/Requirements#windows
then, use git to download the source and install everything following this: http://www.azerothcore.org/wiki/Installation

What do you need exactly? Follow the guide, if you got any trouble feel free to ask on Discord in the  #support channel, we'll support better you there :wink:

**Comment by Orangeat** [comment]
Thank you for your help! I need a complete and effective environment to install wiki. The only thing I don't have is MySQL development file. It's not clear what this is. I compiled according to the tradition and ended up failing. Most of the grammatical errors, I was suffering with joy until I was about to give up, because it was too difficult. I still don't understand four days and nights, because I have no basis for C language.

> @

**Comment by Orangeat** [comment]
您输入的可能是: 意大利语

15 > D: \ azerothcore WotLK \ SRC \ server \ game \ entities \ creation \ creationgroups.cpp: warning c4819: this file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss

15 > D: \ azerothcore WotLK \ SRC \ server \ game \ server \ worldsocket.cpp (727): warning c4715: "worldsocket:: processincoming": not all control paths return values

15 > game.vcxproj - > D: \ build \ SRC \ server \ game \ release \ game.lib

15 > finished generating project "game. Vcxproj".

22 > ------ rebuild all started: Project: worldserver, configuration: release x64------

22 > generating cxx prefix header D: \ build \ SRC \ server \ worldserver \ release \ cotire \ worldserver? Cxx? Prefix.hxx

22 > warn about uninitialized values.

22 > -- D: / xerothcore WotLK / DEPs / composite / cmake / composite. Cmake composite D: / build / SRC / server / worldserver / worldserver ﹣ cxx ﹣ release ﹣ composite. Cmake D: / build / SRC / server / worldserver / release / composite / worldserver ﹣ cxx ﹣ prefix. Hxx D: / xerothcore WotLK / SRC / server / worldserver / precompiledheaders / worldpch. H

22 > ifdef > cplusplus

22 > "include" D: \ azerothcore WotLK \ SRC \ server \ worldserver \ precompiledheaders \ worldpch. H "

22>#endif

22>

22 > -- / * cotire.cmake 1.8.0 generated file*/

22 > / * D: / build / SRC / server / worldserver / release / cotire / worldserver? Cxx? Prefix.hxx*/

22 > ifdef > cplusplus

22 > "include" D: \ azerothcore WotLK \ SRC \ server \ worldserver \ precompiledheaders \ worldpch. H "

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp: warning c4819: this file contains characters that cannot be represented in the current code page (936). Please save the file in Unicode format to prevent data loss

22 > rasocket.cpp

22 > tcsoap.cpp

22 > worldrunnable.cpp

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (121): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (122): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (122): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (122): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (123): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (123): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (125): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (126): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (126): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (126): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (127): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (127): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (129): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (130): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (130): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (130): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (131): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (131): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (131): error c2001: line break in constant

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (132): error c2143: syntax error: missing ")" (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > D: \ azerothcore WotLK \ SRC \ server \ worldserver \ master.cpp (132): error c2143: syntax error: missing ';' (before "ace_singleton < log, ace_thread_mutex >:: instance")

22 > finished generating project "worldserver. Vcxproj" - failed.

23 > ------ rebuild all started: Project: all build, configuration: release x64------

23 > building custom rule D: / azerothcore-wotlk/cmakelists.txt

==========Rebuild all: 16 succeeded, 7 failed, 0 skipped==========

**Comment by FrancescoBorzi** [comment]
> if you got any trouble feel free to ask on Discord in the #support channel, we'll support better you there
