### ISSUE TITLE
Stealth VS aoe spells

### ISSUE THREAD

**Issue by Undead02** [azerothcore/azerothcore-wotlk#2371]
Spells like pestilence,  killing spree etc break rogue stealth

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Use pestilence
2. rogue need to stay near
3. https://i.imgur.com/yizOjQz.jpg
https://i.imgur.com/xrtFnuH.jpg
https://i.imgur.com/fL7JMZs.jpg

and another item break stealth https://wowroad.info/?item=33866
https://i.imgur.com/cMUkGWm.jpg

master

##### OPERATING SYSTEM:

Debian 8

**Comment by FrancescoBorzi** [comment]
hostile spells are supposed to remove you from stealth, please be more specific. Also the issue lacks of information (e.g. AC version)

**Comment by Undead02** [comment]
[6b395e9](https://github.com/azerothcore/azerothcore-wotlk/commit/6b395e9b70f63eb80656ee41904898adbf412752)

spells like pestilence death knight shouldnt break any stealth 
also killling spree rogue break stealth if player stay in range spell

**Comment by Shard-MW** [comment]
Confirmed.

Killing Spree shouldn't hit invisible targets, but it does.

About Pestilence I'm not sure, so I checked Wowhead and found this comment : 
https://www.wowhead.com/spell=50842/blood-boil#comments:id=948983
But I think we need to investigate more there :)

**Comment by Undead02** [comment]
i agree, olso https://www.wowdb.com/items/33866-stormchops break stealth

**Comment by ErnestoGonzalezC** [comment]
I agree with @Shard-MW (Killing Spree shouldn't hit invisible targets) , I could not find information on pestilence.
