### ISSUE TITLE
NPC 29095 No Gossip

### ISSUE THREAD

**Issue by necromancers-dev** [azerothcore/azerothcore-wotlk#2375]
NPC 29095 have no gossip

Soluce : 
UPDATE creature_template SET npcflag = 1 where entry = 29095;

https://tenor.com/view/waouh-waow-woaw-wahou-whaou-gif-5361193

**Comment by Helias** [comment]
Good, you can open a PR with this sql update.

http://www.azerothcore.org/wiki/Dealing-with-SQL-files

**Comment by FrancescoBorzi** [comment]
http://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by Stoabrogga** [comment]
The only use of this character was to redeem Tyrael's Hilt for the 2008 Worldwide Invitational:
https://wow.gamepedia.com/Edward_Cairn
So I don't think this gossip is needed anymore.
