### ISSUE TITLE
Quest "What Is Goind On?" ID 3982 broken

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2376]
SMALL DESCRIPTION:

After accepting the Quest nothing happens. 

EXPECTED BLIZZLIKE BEHAVIOUR:

6 lv 55 elite guardsman and one executioner should  spawn when you accept this quest right inside the cell. 
Source: https://de.classic.wowhead.com/quest=3982/was-ist-los#english-comments

CURRENT BEHAVIOUR:

6 of NPC ID 8891 and 1 NPC ID 8898 or 8903 (Could'nt find a executioneer?)
 List of BRFS NPC's: https://classic.wowhead.com/blackrock-depths#npcs:0+1

STEPS TO REPRODUCE THE PROBLEM:

1. Go to Instance BRFS NPC ID 9020
2. Add Quest ID 3981 and end it
3. Accept the following Quest ID 3982
3. It should spawn the mobs like the description above but nothing happens. 

EXTRA NOTES:

BRANCH(ES):

master

AC HASH/COMMIT:

d2b409e+ 2019-06-15 11:51:37 -0500

OPERATING SYSTEM:

Win 10 Pro 64 bit

MODULES:

- Auctionhouse Bot
- npc_beastmaster
- npc_enchanter
- BuffMaster
- VASAutoBalance
- Transmogrifier
- OTHER CUSTOMIZATIONS:
- AutoRevive on death
- NPC Instance, LFG, Dungeon cooldowns reset
- Individual-XP

**Comment by Stoabrogga** [comment]
This is already fixed in commit efaa4586e64fd8ca1a6012b994d72a401b207e8b, please update your AC version (and please actually use AC and no repacks, the commit you mentioned looks strange to me).

**Comment by Endeffect-AT** [comment]
Oh, so it works in recent compile?

**Comment by Stoabrogga** [comment]
Yes, the quest should work now.
