### ISSUE TITLE
Core/Worldstates: daily calendar deletion old events time

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#2383]
We could add the worldstate WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME and a related config to set the deletion of old events.

I get this missing worldstate comparing our worldstates to TC.

Related code: https://github.com/TrinityCore/TrinityCore/commit/fb059722fdb18a94d47b3f44a5b2d7f183bf5a29#diff-69f0ea4bf362615d6993f2a38027d31a

**Comment by Kitzunu** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/2799 , right?

**Comment by Helias** [comment]
Yes, thanks @Kitzunu
