### ISSUE TITLE
[World] Bugged creature movement/engaging in combat

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#2390]
##### SMALL DESCRIPTION:

When mobs are engaging in combat, NPC or NPCs getting stuck and you can't normally fight them.
Can't properly describe it, so i made a video.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC movement and combat engaging should work properly

##### CURRENT BEHAVIOUR:

[Video link](https://youtu.be/JqUSK9Sg33g)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Watch the [video](https://youtu.be/JqUSK9Sg33g) :)

P.S. I CAN'T REPRODUCE THIS BUG at 100% of the times, and mostly where it happens is an Outland, so, maybe this bug is related to MMaps or VMaps

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

d9986c0

##### OPERATING SYSTEM:

Win 10 LTSC 1903

##### MODULES:

AutoBalance

##### OTHER CUSTOMIZATIONS:

No.

**Comment by Stoabrogga** [comment]
Cannot confirm. Tested this with different characters on commit 2cb28e5f5342e92934b5d7d3acd771a7785be82d with a fresh DB and the fish are attacking normally. Swam around Serpent Lake for a while and did not see any strange behaviour.

**Comment by markvetwow** [comment]
In my case, this bug affects not only those fishes, but absolutely random NPCs in Zangarmarsh for example. It can be a nagas, broken draenei, no matter. Same bug.

**Comment by diluh** [comment]
I confirm this, on my server sometimes this happens exactly with these paladin spells

**Comment by markvetwow** [comment]
Just an addition, as you may see in my video, there is 2 more dudes are playing with, sometimes they can "catch" this issue too. So, shaman and mage as well, may be it's not class related.

**Comment by diluh** [comment]
I think in fact the mistake is in the creatures, because some pets stop attacking certain creatures.  Test with pets from Hunter, Shaman, Warlock, Mage.

@markvetwow

**Comment by Stoabrogga** [comment]
Hmm, so does this happen if using specific spells? Or pets? Or if playing in a party? In order to analyze and fix this we need a reliable way of reproducing the issue.

**Comment by Viste** [comment]
Only in water? or outside the water this happens to?

**Comment by markvetwow** [comment]
It doesn't matter if you are pulling mobs in a party or solo, same for spells, and the same for ground/underwater. I tried with a different gm levels, just to be sure, same issue.  Unfortunately, I don't know, how to precisely reproduce this bug, but it can occur from time to time.

**Comment by Stoabrogga** [comment]
I'm playing on my own AC server since December 2017 and never saw the behaviour you described, not even once (played with several characters until level 80 and a few others until 30-40).

Do you use any custom modifications? Or any special configuration changes?

**Comment by markvetwow** [comment]
I'm using only an AutoBalance module, and increased uncommon items rate to 1.5, that's it

**Comment by Stoabrogga** [comment]
Hmm, ok. Sorry, but I have no idea what's wrong here and I cannot reproduce the issue on my own server. Perhaps someone else has an idea about this.

One thing though: Did you try downloading the data files from here and use those instead of extracting them on your own?
http://www.azerothcore.org/wiki/Installation#5-download-the-data-files

**Comment by markvetwow** [comment]
I used them at the first place. Then re-converted, and used one from my client

**Comment by solidmaxtor** [comment]
Compiled fresh core 27/10/19 and players report probems with pet follow and many npc no move o reset combat. I will be collecting more specific information today

**Comment by smansesdottk** [comment]
I got this problem too
sometimes you must hit that bugged mop on other place, not when it stand
I try to extract my own data files, but still same

**Comment by pklloveyou** [comment]
I have not found this error

**Comment by solidmaxtor** [comment]
I am use this files @Stoabrogga but this problem is report for many players DK and hunter beast mainly. Pets suddenly stop or do not attack:

https://www.youtube.com/watch?v=f99eAkzGFsw
https://www.youtube.com/watch?v=O5EntIALUzc

**Comment by Stoabrogga** [comment]
Are you using normal player accounts or game masters? I only tested normal player accounts.

**Comment by solidmaxtor** [comment]
These video reports are made by the players.

**Comment by Stoabrogga** [comment]
Did you change any default values in the worldserver configuration? Aside from DB, Port, DataDir etc.

**Comment by solidmaxtor** [comment]
No changes check again line per line but all normal no changes and download new copy maps.
i continue test today.

**Comment by Stoabrogga** [comment]
Which OS are you using for your server? My server is running on Ubuntu 16.04.

**Comment by solidmaxtor** [comment]
Same OS ubuntu 16.04 transmorg module but test without modules.

**Comment by diluh** [comment]
@solidmaxtor @Stoabrogga 
How did you decide tell me which manager you used to add the databases to.  (NaviCat)? (HeidSql) ?(SqlYog). ? I realized that they do not perform the updates I have to put manual.

**Comment by solidmaxtor** [comment]
The problem is not completely resolved.
Many creatures of the world do not work properly.
Visually it seems that they remain still but leave the range of attack mele or range.
Apparently these are falling, same problem with pets.
Its very critical problem.

**Comment by Shard-MW** [comment]
@Knindzagxg 
Please can you try to use Blink spell in the area where Concetration does not stick to ground ?
I think this issue can come from maps/vmaps/mmaps

**Comment by pklloveyou** [comment]
The problem has not been found on the server......................

**Comment by solidmaxtor** [comment]
Confirm this problem, i am use 31/10 fresh compile all clear no modules, new maps download but problem persist, this is really critical en new compile cores:
https://www.youtube.com/watch?v=iNc_9AjyhEU

**Comment by FrancescoBorzi** [comment]
it would be nice if we can have the commit that was causing this issue

**Comment by FrancescoBorzi** [comment]
@solidmaxtor also we need help to reproduce this issue, since several contributors cannot reproduce it and then it's not possible to fix

**Comment by Stoabrogga** [comment]
Ok, I did set up a complete new server using commit 52cd73e1560aa9a7fc17e5233df148594d933b29:
- OS: Ubuntu 16.04
- MySQL 5.7
- Compiled using cmake 3.15.4 and clang 7.1.0
- Fresh DB
- Data files from here: https://github.com/wowgaming/client-data/releases/tag/v7
- no modules or any other customizations
- cleared client cache

Played a while with a warlock (felguard) and a hunter, both 80. I did not see any issues so far, neither the ones mentioned here or in #2399.

**Comment by diluh** [comment]
I can only reproduce the bug with people active on the server alone it seems to have no errors.

**Comment by BarbzYHOOL** [comment]
maxtor, update your compiling tool (clang 6.0 needed)

**Comment by Stoabrogga** [comment]
The root cause is the same as for #2399. I'm currently working on a PR to solve this.

**Comment by Stoabrogga** [comment]
Could you please test PR #2457 and provide feedback?
