### ISSUE TITLE
Warlock's life drain spell seems to be invalid to Training dummy

### ISSUE THREAD

**Issue by wang5150753** [azerothcore/azerothcore-wotlk#2391]
##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

**Comment by Shard-MW** [comment]
Please can you give us more infos ? We can't do anything with empty issue lol
@wang5150753

**Comment by lineagedr** [comment]
Drain life drains % hp from target. Target dummy happens to have 1 hp I wouldn't call it invalid.

**Comment by Helias** [comment]
I think, we can close this issue.
