### ISSUE TITLE
Update g3dlite

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2392]
Please update depens g3dlite to last version.

**Comment by diluh** [comment]
my google machine updated by itself, and is giving error in the vice build uses G cloud too?  Leave your discord

**Comment by LichKing255** [comment]
> my google machine updated by itself, and is giving error in the vice build uses G cloud too? Leave your discord

what you say ? :|

**Comment by Kitzunu** [comment]
Still valid?

**Comment by Helias** [comment]
I think so, we still have g3dlite in our repo
I am not sure if any PR will rmeove it, but I don't think so

**Comment by Kitzunu** [comment]
Closing as outdated. I cannot find that we would not use a recent version
