### ISSUE TITLE
The fire will not produce fire damage

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#2396]
SMALL DESCRIPTION:
![image](https://user-images.githubusercontent.com/18535853/67938080-c4501a80-fc09-11e9-9d57-16f630b21f05.png)
Bonfires should produce damage
Change "gameboject entry 94183" displayID to 197 to generate damage correctly
Bonfire material blocking the damage of the game player
```c++
.go o 23
```

EXPECTED BLIZZLIKE BEHAVIOUR:
Bonfires should produce damage

CURRENT BEHAVIOUR:
The fire did not hurt, 
but moved to the fire internal damage “.go o 23”, 
remove the fire GUID23, GUID24 damage properly，
Object 24 impenetrable object 23 deals damage to the player

STEPS TO REPRODUCE THE PROBLEM:
```c++
.go o 23
```
As shown in
![image](https://user-images.githubusercontent.com/18535853/67938080-c4501a80-fc09-11e9-9d57-16f630b21f05.png)

BRANCH(ES): master
AC HASH/COMMIT: d9986c0
OPERATING SYSTEM: Win 10 x64
MODULES: NO

**Comment by Stoabrogga** [comment]
There's also another problem concerning some other bonfires: Their radius for the fire effect is too large, e.g. if you run to Thrall in Orgrimmar (`.go 1923.89 -4198.55 42.1597 1`) or in the Valley of Trials (`.go -605.034 -4172.43 41.0001 1`).
