### ISSUE TITLE
[Quest]: The Halls Of Reflection

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#2400]
![WoWScrnShot_110119_173232](https://user-images.githubusercontent.com/52524476/68082569-bbdb2800-fe33-11e9-8ac2-303d6a834292.jpg)
![WoWScrnShot_110119_173329](https://user-images.githubusercontent.com/52524476/68082570-bed61880-fe33-11e9-8a14-acafd779dcf1.jpg)
![WoWScrnShot_110119_173405](https://user-images.githubusercontent.com/52524476/68082572-c09fdc00-fe33-11e9-8aa5-c7dce404b49a.jpg)
![WoWScrnShot_110119_173436](https://user-images.githubusercontent.com/52524476/68082574-c3023600-fe33-11e9-91d7-7a605198ace4.jpg)

Hi sorry this bug question is going to be solved.
But it can't be solved like the sword that is needed and this is defined in the database but inside the mob there is no sword and the mob shape must be a sword that is invisible and when I hover my mouse on the mob no sword form is available Fix this.
Quest : [The Halls Of Reflection]
Entry : 37158
Guid : 3120855
Native : 30547

**Comment by FrancescoBorzi** [comment]
@poryagholami please include your AC version

**Comment by poryagholami** [comment]
Acdb 3.3.5.3 
A.c 3.0.0

**Comment by FrancescoBorzi** [comment]
@poryagholami not this, the AC commit version.

For example: https://github.com/azerothcore/azerothcore-wotlk/commit/52cd73e1560aa9a7fc17e5233df148594d933b29

**Comment by poryagholami** [comment]
3b67466d9c08

**Comment by poryagholami** [comment]
There was no answer

**Comment by LichKing255** [comment]
Not confirm. Your DB have problem.

**Comment by LichKing255** [comment]
Not confirm. Your DB have problem.

**Comment by GMKyle** [comment]
Quest works fine, the problem is the npc's  model(30547). A lot of players complains about it.
Just for drop some light on this issue,  Quel'Delar (37158) is a transparent/invisible npc with a sword  when it's is dead it's difficult to loot.
Confirm

**Comment by LichKing255** [comment]
@GMKyle 
I can't confirm. Tell me how difficult it is to loot? Players can see sword.
Picture :

![Capture](https://user-images.githubusercontent.com/54138710/68490332-07d80380-025e-11ea-8b96-8c24e8f27df1.PNG)

**Comment by GMKyle** [comment]
@LichKing255 
I don't know why but sometimes sword isn't visible. Just look the pictures and in my local server happens to . Perhaps it's a maps issue, i'm just guessing

**Comment by LukasVolgger** [comment]
Cannot reproduce on commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4

![image](https://user-images.githubusercontent.com/55922592/100499395-a2f19300-3169-11eb-894a-63721975f46b.png)
![image](https://user-images.githubusercontent.com/55922592/100499407-b8ff5380-3169-11eb-81b1-94a7d06295a7.png)
