### ISSUE TITLE
"The Prophet Tharon'ja" in Drak'Tharon Keep can be pulled down too early

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#2401]
![WoWScrnShot_110319_123208](https://user-images.githubusercontent.com/52524476/68082870-3d808500-fe37-11e9-986b-2571d7963434.jpg)
![WoWScrnShot_110319_123228](https://user-images.githubusercontent.com/52524476/68082873-3fe2df00-fe37-11e9-9b96-d54fec1b5b4f.jpg)
![WoWScrnShot_110319_123237](https://user-images.githubusercontent.com/52524476/68082874-42453900-fe37-11e9-8084-7a682a74a722.jpg)
![WoWScrnShot_110319_123250](https://user-images.githubusercontent.com/52524476/68082876-440efc80-fe37-11e9-8e02-259fc3e6cf76.jpg)
![WoWScrnShot_110319_123258](https://user-images.githubusercontent.com/52524476/68082879-4709ed00-fe37-11e9-91a9-5bfac4a3595e.jpg)
![WoWScrnShot_110319_123306](https://user-images.githubusercontent.com/52524476/68082880-48d3b080-fe37-11e9-9f84-5aca7d089b8d.jpg)
![WoWScrnShot_110319_123335](https://user-images.githubusercontent.com/52524476/68082881-4a9d7400-fe37-11e9-9d1b-f47da1563b4d.jpg)
![WoWScrnShot_110319_123354](https://user-images.githubusercontent.com/52524476/68082885-4c673780-fe37-11e9-9bce-ce8cd09ac0df.jpg)
![WoWScrnShot_110319_123431](https://user-images.githubusercontent.com/52524476/68082887-4e30fb00-fe37-11e9-908a-1bf7bc51086a.jpg)
![WoWScrnShot_110319_123445](https://user-images.githubusercontent.com/52524476/68082889-52f5af00-fe37-11e9-818f-914ebb6e826a.jpg)

Hello from bass can bring the bass to the end with shaman totem This bug has to make the pet that 
the pat on the bass can't go to set a range for him.

/target The Prophet Tharon'ja
instance : Dark'Tharon Keep

**Comment by FrancescoBorzi** [comment]
@poryagholami please include your AC version (commit hash)

**Comment by poryagholami** [comment]
Acdb 3.3.5.3 
A.c 3.0.0

**Comment by FrancescoBorzi** [comment]
@poryagholami not this, the AC commit version.

For example: https://github.com/azerothcore/azerothcore-wotlk/commit/52cd73e1560aa9a7fc17e5233df148594d933b29

**Comment by poryagholami** [comment]
3b67466d9c08

**Comment by poryagholami** [comment]
There was no answer

**Comment by FrancescoBorzi** [comment]
what answer?

**Comment by Stoabrogga** [comment]
I can reproduce the issue using a Shaman:
- `.go -246.954 -666.484 26.5445 600` (teleports into Drak'Tharon Keep, just behind Trollgore)
- `/target the prophet`
- summon Fire Elemental Totem
- the Greater Fire Elemental will start to float up through the ceiling, attacking the boss and ultimately pulling down the boss to the player

It does not seem to work with other pets or summons (tested with hunter / warlock pets and mage water elemental).

**Comment by Stoabrogga** [comment]
@pklloveyou
I tested the issue you mentioned [here](https://github.com/azerothcore/azerothcore-wotlk/pull/2694#issuecomment-589983545) but it seems to only affect the Shaman's Fire Elemental, not all pets.

**Comment by pklloveyou** [comment]
I am looking for a way to reproduce this error

**Comment by Ragelezz** [comment]
My Fire Elemental is not going for Tharon'Ja at all. Which spell are you using ?

**Comment by steenburgh** [comment]
It could be fixed. I'm using the spell you get at the trainer as far as I know

**Comment by steenburgh** [comment]
I have not retested
