### ISSUE TITLE
Game Event "Stranglethorn Fishing Vale Competition" Event NPC  "Riggle Bassbait" Missing

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2404]
##### SMALL DESCRIPTION:

During the stranglethorn fishing extravaganza event every sunday from 02:00 pm 04:00 pm the NPC which is needed to complete the fishing contest is not spawning. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC "Riggle Bassbait" ID 15077 should spawn during the event every sunday at 02:00 pm and disappear at 04:00 pm server time.  

See:

https://classic.wowhead.com/npc=15077/riggle-bassbait

https://wowwiki.fandom.com/wiki/Riggle_Bassbait

Position of NPC should be:

https://www.gamingcfg.com/img/6338/Riggle-Bassbait.jpg
http://www.vanion.eu/uploads/media/article/0001/22/thumb_21672_article_big.jpeg

##### CURRENT BEHAVIOUR:

The game_event ID 15 the fishing pools spawn correctly, but he NPC ID 15077 does not appear during the given time. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele booty bay
2. Start the event using the command .event start 15
3. See the Screenshots above, the NPCs and Gobject is not spawned. 

##### BRANCH(ES):

AzerothCore rev. c69b05fb1c7c 2019-11-03 20:42:34 +0100 (pr-2381 branch)

##### AC HASH/COMMIT:

c69b05fb1c7c

##### OPERATING SYSTEM:

Windows 10 Pro 64 Bit

**Comment by pklloveyou** [comment]
Event 16 in the absence of the player in the map, the box is not generated, there is no activation of biological ID14508, the player is often unable to get the items in the box

**Comment by pklloveyou** [comment]
ID 14508

**Comment by pklloveyou** [comment]
```sql
INSERT INTO `game_event_creature` VALUES (15, 203521);
INSERT INTO `game_event_creature` VALUES (62, 203521);
```

**Comment by solidmaxtor** [comment]
Confirm, event not can complete the npc not spam correctly

**Comment by Endeffect-AT** [comment]
Working on a fix - rebuild from the positions of the npc's from screenshots:

![WoWScrnShot_112119_161652](https://user-images.githubusercontent.com/55922592/69350888-a7dc5680-0c7a-11ea-988f-a28e6293e053.jpg)

![WoWScrnShot_112119_161655](https://user-images.githubusercontent.com/55922592/69350898-aca10a80-0c7a-11ea-8165-70bd5e06e765.jpg)
