### ISSUE TITLE
worldserver error - segmentation fault

### ISSUE THREAD

**Issue by Beater901** [azerothcore/azerothcore-wotlk#2408]
Some help me with this error. worldserver

Linux - Debian 9

`2019-10-31 21:03:48 [Eluna]: Eluna is disabled in config 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.ForcedID40'. The default value is used () 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.ForcedID25'. The default value is used () 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.ForcedID10'. The default value is used () 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.ForcedID5'. The default value is used () 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.ForcedID2'. The default value is used () 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.DisabledID'. The default value is used () 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.enable'. The default value is used (1) 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.announce'. The default value is used (1) 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.LevelEndGameBoost'. The default value is used (1) 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.DungeonsOnly'. The default value is used (1) 2019-10-31 21:03:48 ERROR: -> Not found option 'VASAutoBalance.PlayerChangeNotify'. The default value is used (1) 2019-10-31 21:03:48 ERROR: -> Not found option . `

**Comment by BarbzYHOOL** [comment]
seems related to vasautobalance, post in the right repository and also try to remove your vasautobalance.conf and use the default .conf.dist first
