### ISSUE TITLE
Error Displaying Mage Water Elemental Companion User Interface

### ISSUE THREAD

**Issue by Volgger** [azerothcore/azerothcore-wotlk#2414]
##### SMALL DESCRIPTION:

The representation of the water elemental in the character window below the companion point is incorrect.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The companion should scale normally for the window size and should be displayed without problems.

##### CURRENT BEHAVIOUR:

See the following Screenshots what's the error:

**https://1drv.ms/f/s!AiO9s9C6ULPRnw-HCWR6V4jmyooj**

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Mage Character
2. Level and skill Frost until u are able to summon the Water Elemental ~ lvl 40+
3. Use the Glyph 'Glyph of Eternal Water' ID 50045 to permanently control the elemental
4. Open the character windows (c) and see the companion

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3142b1+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max Skill on levelup

**Comment by Zausender** [comment]
Actually the mage pet tab  shouldn't been there
![image](https://user-images.githubusercontent.com/56157973/69008905-1f934400-0950-11ea-8d2b-6cc46b94e24c.png)

**Comment by Endeffect-AT** [comment]
@Zausender 

Are you using the Glyph of Eternal Water?
