### ISSUE TITLE
Quest "Blueleaf Tubers" cannot be completed

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2415]
##### SMALL DESCRIPTION:

The Snufflenose Gopher should go and look for Blueleaf Tubers after using the Snuffelnose Command Stick on him. In fact the Gopher run around and kills mobs - he shouldn't...

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Look this Video and check the comments of wowhead how the Quest should work:

https://www.youtube.com/watch?v=S9lrdq0AeoM
https://classic.wowhead.com/quest=1221/blueleaf-tubers#comments

##### CURRENT BEHAVIOUR:

After i follow the description and the comments of wowhead how it should work and stand on a vine to release the Gopher with the 'Crate with holes' ID 5880, he spawns correctly. Now after using the 'Snuffelnose Command Stick' ID 6684 ONCE he should go and search for the Blueleaf Tubers. He just runs around and kills mobs - very funny, but not correct :D

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 1221 and get the items in Ratschet
2. Go to Razorfen Kraul and follow the left path on the vine until u can use the 'Crate with holes'
3. Select the Gopher and use 'Snuffelnose Command Stick' ID 6684 Once on him

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

Max skill on levelup

**Comment by wizzymore** [comment]
Hi, can anyone reproduce this?

After this: https://github.com/azerothcore/azerothcore-wotlk/pull/1633 i didn't meet any problems with this quest

**Comment by GMKyle** [comment]
I confirm, gophers are aggressive and attacks all mobs in their way; they even go very far away from players

**Comment by Endeffect-AT** [comment]
Label confirmed pls :)

**Comment by Stoabrogga** [comment]
I also tested this and the gopher indeed pulls half the dungeon if used. It cannot attack, though, but it runs to the enemies. If I have time the next few days I can try to fix this behaviour.

**Comment by Endeffect-AT** [comment]
Thx, but i will miss it because the actual behavior is very funny :smile:

Will test it when ready :+1:

**Comment by Stoabrogga** [comment]
> Thx, but i will miss it because the actual behavior is very funny 😄

Yeah, reminds me of this:
https://www.youtube.com/watch?v=tgj3nZWtOfA&t=120
🤣

**Comment by Endeffect-AT** [comment]
Haha 🤣
Monty Python movies are the best!  Great humor!  👍🏻🤣
