### ISSUE TITLE
[Locale] Translation issues, need help

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#2423]
##### SMALL DESCRIPTION:

It looks like there is a text translation problems on core side.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All texts should be translated properly.

##### CURRENT BEHAVIOUR:

Tested in 2 different locales, deDE and ruRU. There is a translations in database for those locales, but texts still shows in English lang. Yes, i cleared the cache.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Run client with any different from enUS or enGB locale.

2.  I tested on this 2 particular cases, some places everything is okay, some not. First mob is Ishanah in Shattrath(its gossip options), and aggro texts from Auchenai Soulpriests and Vindicators in Auchenai Crypts.

3. Some screens:

![image](https://user-images.githubusercontent.com/24928567/68550914-837db000-0418-11ea-9986-9a799792742e.png)
![image](https://user-images.githubusercontent.com/24928567/68550921-89739100-0418-11ea-9f5e-6a7b2837c691.png)
![image](https://user-images.githubusercontent.com/24928567/68550925-93958f80-0418-11ea-930d-da6bb4773b97.png)
![image](https://user-images.githubusercontent.com/24928567/68550928-97c1ad00-0418-11ea-8406-8ca7b25edc79.png)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

0fd565d

##### OPERATING SYSTEM:

Win 10 LTSC 1809 x64

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by brussens** [comment]
I'll send the locale fix today. However, the problem with many gossip is that they are hard-code within scripts. To do this, we need to rewrite all the scripts that override the default behavior of all gossip.

**Comment by markvetwow** [comment]
It didn't help in my case. It's still an English in both clues. One little detail that i mentioned. Let's take this NPC for example(id 19232). Just an inkeeper with a default hearthstone bind/vendor gossip options.  Just in case i decided to change it's gossip_menu to another one, from Inkeeper Allison in Stormwind(which translated correctly by the way), and still it stays in English.

**Comment by markvetwow** [comment]
Okay, re-checked the db. And yes, there is a missing broadcast texts in creature_text for those mobs in Auchenai Crypts, so they are just missing broadcast_text id.

**Comment by BarbzYHOOL** [comment]
@markvetwow can you post on the PR the conclusion of your tests?
