### ISSUE TITLE
Disable Authserver compilation

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2429]
I tried to do this: add a cmake option to disable authserver from compilation

It's on this branch:
https://github.com/BarbzYHOOL/azerothcore-wotlk/commits/separate_authserver_worldserver

it doesn't work, it requires at least 2 headers from the authserver (one being Authsocket.h which seems to be removable, the other being Realmsocket.h and it's not removable)

If anyone wants to fix and improve this, feel free to make a new PR or hit me here or on discord

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2416
