### ISSUE TITLE
Crash server and "ChatStrictLinkChecking.Severity"

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#2433]
This following script allows to make crash the server when `ChatStrictLinkChecking.Severity = 3` in `worldserver.conf`.

Script:
```
/run function CrashServer() SendChatMessage("\124cffffd000\124Henchant:59387\124h[Inscription]\124h\124r", "SAY") end CrashServer()
```

Thanks  @avatar789 (ZIC on discord) to discover this critical issue.
Issue related to https://github.com/azerothcore/azerothcore-wotlk/issues/2409  

---  

##### STEPS TO REPRODUCE THE PROBLEM:
1.  put `ChatStrictLinkChecking.Severity = 3` in `worldserver.conf`
2.  login and write this in chat:
```
/run function CrashServer() SendChatMessage("\124cffffd000\124Henchant:59387\124h[Inscription]\124h\124r", "SAY") end CrashServer()
```
3.  the server will crash

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
1914571cbac9206a71e0601c19345ced190d7d52

##### OPERATING SYSTEM:
Tested on Ubuntu 18.04.3 LTS

##### MODULES:
no modules

**Comment by pklloveyou** [comment]
Why doesn't my server crash....

**Comment by pklloveyou** [comment]
1. ChatStrictLinkChecking.Severity = 0
![image](https://user-images.githubusercontent.com/18535853/68832176-38e78680-06eb-11ea-89bc-8efc017aad4d.png)
2. ChatStrictLinkChecking.Severity = 3
![image](https://user-images.githubusercontent.com/18535853/68832215-53216480-06eb-11ea-9d8b-c676f82411e3.png)
No display after sending

**Comment by Helias** [comment]
I don't know, my server crash, be sure that your server is loading the right worldserver.conf with severity = 3
```
/run function CrashServer() SendChatMessage("\124cffffd000\124Henchant:59387\124h[Inscription]\124h\124r", "SAY") end CrashServer()
```

**Comment by Stoabrogga** [comment]
Tested and my Server crashed after executing the script with a level 1 player character (commit: fae7ae9).

**Comment by LichKing255** [comment]
> Why doesn't my server crash....



> 1. ChatStrictLinkChecking

change ChatFakeMessagePreventing from 0 to 1.

**Comment by Helias** [comment]
I have ChatFakeMessagePreventing = 0 and the server still crashes when I put severity=3.

**Comment by Helias** [comment]
Fixed, you can test the PR :wink:
