### ISSUE TITLE
[Bug] Underwater Maps Error Maraudon Entry

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#2437]
##### SMALL DESCRIPTION:

When you go to the instance maraudon (yellow entrance), a few yards before you are underwater - but there should be no water. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

In the given location sould be a normal surface without any underwater breathing.

##### CURRENT BEHAVIOUR:

See the Screenshots:

https://1drv.ms/f/s!AiO9s9C6ULPRnxhSHJ7UOM7ewYwa

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go -1460.429443 2685.802734 77.320488 1
2. See that the mobs swim in this area and you got undewater breathing

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max Skill on levelup

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/68937122-d075d380-07d6-11ea-9397-29d93ff1d5d3.png)

**Comment by Stoabrogga** [comment]
There's also a similar issue on TC:
https://github.com/TrinityCore/TrinityCore/issues/20221#issuecomment-328080013

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/68992787-477c9c00-08ab-11ea-9ad6-163d60f418c4.png)

**Comment by Endeffect-AT** [comment]
@pklloveyou 
Confirm. The Mobs are flying as you can see on the screens

**Comment by Endeffect-AT** [comment]
another error found related to the maps, in Western Plaguelands in Herdweiler you sometimes fall through the map. During the Quest 'Scarlet Subterfuge' ID 5862.

![WoWScrnShot_101919_181627](https://user-images.githubusercontent.com/55922592/68992966-87735d00-0872-11ea-9d6f-0f80f3791a49.jpg)

**Comment by Shard-MW** [comment]
@Endeffect-AT 
Please open up another issue for the undermap bug 😌

**Comment by Endeffect-AT** [comment]
@Shard-MW 
Now i cannot reproduce Herdweiler the issue by myself. I updated the core and it seems to be working fine!

**Comment by Nyeriah** [comment]
This needs to be retested with the new maps

**Comment by Gultask** [comment]
I set up a local AC a few hours ago (re-downloaded the client data too) and this still happens.

swimming
![WoWScrnShot_043022_000331](https://user-images.githubusercontent.com/100873791/166088224-0929ee94-335c-4904-ba96-6d8a0735100a.jpg)

floating
![WoWScrnShot_043022_000641](https://user-images.githubusercontent.com/100873791/166088234-d41b7113-deca-45ec-aead-4c35db833000.jpg)

**Comment by acidmanifesto** [comment]
This is flaggined the anticheat detection AntiSwim. https://github.com/azerothcore/mod-anticheat/issues/71

**Comment by Kitzunu** [comment]
there are some places like this, another is `.go xyz 3289.781 6604.514 -2.32 571`

**Comment by acidmanifesto** [comment]
> there are some places like this, another is `.go xyz 3289.781 6604.514 -2.32 571`

if there was any breath bar there before it isnt present currently 
![image](https://user-images.githubusercontent.com/16887899/167265986-548a558c-8bb3-4959-89d0-99135cbf1600.png)

**Comment by Kitzunu** [comment]
Maybe bad coords. But it would be around that area
