### ISSUE TITLE
Mysql error in creature_template

### ISSUE THREAD

**Issue by wang5150753** [azerothcore/azerothcore-wotlk#2438]
I got a err when I use mysql8.0
'''
[ERROR]: In mysql_stmt_prepare() id: 54, sql: "SELECT difficulty_entry_1, difficulty_entry_2, difficulty_entry_3, KillCredit1, KillCredit2, modelid1, modelid2, modelid3, modelid4, name, subname, IconName, gossip_menu_id, minlevel, maxlevel, exp, faction, npcflag, speed_walk, speed_run, scale, rank, mindmg, maxdmg, dmgschool, attackpower, DamageModifier, BaseAttackTime, RangeAttackTime, unit_class, unit_flags, unit_flags2, dynamicflags, family, trainer_type, trainer_spell, trainer_class, trainer_race, minrangedmg, maxrangedmg, rangedattackpower, type, type_flags, lootid, pickpocketloot, skinloot, resistance1, resistance2, resistance3, resistance4, resistance5, resistance6, spell1, spell2, spell3, spell4, spell5, spell6, spell7, spell8, PetSpellDataId, VehicleId, mingold, maxgold, AIName, MovementType, InhabitType, HoverHeight, HealthModifier, ManaModifier, ArmorModifier, RacialLeader, movementId, RegenHealth, mechanic_immune_mask, flags_extra, ScriptName FROM creature_template WHERE entry = ?"
[ERROR]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', mindmg, maxdmg, dmgschool, attackpower, DamageModifier, BaseAttackTime, RangeA' at line 1
'''

I have check 'rank' is a reserved field of mysql !!!!!【mariadb10 dont have this issue But it can't use because it's below 5.7!!!! wtf???】
so can anyone help to fix this bug?

The following sql can reproduce this bug：
select  rank from creature_template where entry=1;
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from creature_template where entry=1' at line 1

**Comment by FrancescoBorzi** [comment]
> I got a err when I use mysql8.0

mysql 8 is not supported, please use mysql 5.7

**Comment by Winfidonarleyan** [comment]
We support `MySQL 5.6, 5.7` `MariaDB 10.1 - 10.4`
