### ISSUE TITLE
Quest "Azsharite" Felhound works not correctly

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2439]
##### SMALL DESCRIPTION:

The Felhound which you get when accepting the Quest 'Azsharite' does nothing after you target him and type emote /roar.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If you target the felhound and type the emote /roar it should do the emote 'Felhound Tracker searches for a source of arcane energy.' and go around to the next Azsharite in the near. After he found it, the Felhound should do the second emote 'Felhound Tracker growls.'

Look this Video: https://youtu.be/xZ595B7iENg

##### CURRENT BEHAVIOUR:

Nothing happens when typing the /roar emote in the chat ingame while selected the Felhound. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 3602
2. .go 2660.236572 -5852.825684 94.152527 1
3. Release the Felhound with the item 10831
4. Target the Felhound and type the emote /roar in chat

##### EXTRA NOTES:

Seems to be similar to Isse #2415 
You can complete the quest without the felhound by finding the Azsharite yourself. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max Skill on levelup

**Comment by Stoabrogga** [comment]
The Felhound Tracker has no script, so it won't do anything. I'll take a look at this.
