### ISSUE TITLE
[Spell] Victory Rush

### ISSUE THREAD

**Issue by HeartWell** [azerothcore/azerothcore-wotlk#244]
**Description**: The problem with Victory Rush.

**Current behaviour**: After the killing of a mob with VR, VR is not updated, despite the fact that in the description of the skill killing the enemy gives honor/exp, VR should be updated.

**Expected behaviour**: Killing an enemy with VR, VR should appear as ready to use.

**Steps to reproduce the problem**:

1. To kill a mob with VR and to see how the VR behaves.

**Branch(es)**: 1.x

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/d53b5522f92398ed5dc785c3c84a325593d20747

**Operating system**:  Windows 10

**OpenWoW:**
- http://wotlk.openwow.com/spell=34428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Yehonal** [comment]
@HeartWell why you closed it?
