### ISSUE TITLE
[Core / Pet] Pets on passive/defensive don't use direct spells (melee range) when commanded to attack

### ISSUE THREAD

**Issue by EpicDR** [azerothcore/azerothcore-wotlk#2440]
[Core / Pet] Pets on passive/defensive don't use direct spells (melee range) when commanded to attack

Bug:

When a pet on passive/defensive is commanded to attack it will only use melee attack at any distance. If it is sent to attack with a spell or special attack (melee range), it does not reach its destination.

Example: Claw from DK's.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Even if the pet is passive or defensive when using a spell or special attack (melee range), it should attack its target.

##### CURRENT BEHAVIOUR:
Details:

To activate special attacks, the Hunter has to manually send the pet to attack with melee damage so that the pet can use its spells. Using the spell or special attacks directly in passive/defensive mode on the target, the pet does not reach its destination target and stops a few yards before.

##### STEPS TO REPRODUCE THE PROBLEM:

With DK

1. Take a prudent distance with your target
2. With UH talents put yor ghoul in pasive/defensive stance
3. Use the "claw" spell from your ghoul, and your ghoul, goes towards the target but stop a few yards before attack the target.

##### OPERATING SYSTEM:
ubuntu, debian.

##### MODULES:
clean.

##### OTHER CUSTOMIZATIONS:
clean

**Comment by FrancescoBorzi** [comment]
@EpicDR please include your AC version (commit hash)

**Comment by EpicDR** [comment]
commit 1914571cbac9206a71e0601c19345ced190d7d52

(12 nov 2019)

**Comment by V3nomAnc3r** [comment]
confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/7e0fba81b7b54376c32f7d915322a86834569a0a

**Comment by Stoabrogga** [comment]
I can reproduce the behaviour on commit dd81c21. Sadly, don't have an idea how to fix this.

**Comment by Yehonal** [comment]
Could someone test on an old version of AC? I think the best way to fix it is to understand what broke it.

**Comment by Stoabrogga** [comment]
@Yehonal 
Which commit do you propose to test this with? I have a bit more time next week and could try this.

**Comment by Yehonal** [comment]
Is this confirmed on hunter pets too? or just DK

**Comment by Stoabrogga** [comment]
I tested it with both, hunter pets and ghoul. If you disable pet autocast and give the attack command directly the pet attacks normally, but if you use a spell which needs melee range the pet stops before getting in range. If you activate autocast for the melee ranged pet spell and then give the attack command everything works well.

**Comment by Yehonal** [comment]
Could be related: https://github.com/azerothcore/azerothcore-wotlk/blob/dd81c219680db16172bfdfe4684f64a58a23eeb1/src/server/game/Entities/Creature/Creature.cpp#L1519

**Comment by Stoabrogga** [comment]
Tested using the first commit of AC v2.0.0: 1fc22a7
Behavior was the same, so this bug seems to be _very_ old.

**Comment by V3nomAnc3r** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/fea7cc7775e4bce5aa9a6e304a0b18bad381916a Still bug

**Comment by Tooldev94** [comment]
confirmed

**Comment by Stoabrogga** [comment]
> [fea7cc7](https://github.com/azerothcore/azerothcore-wotlk/commit/fea7cc7775e4bce5aa9a6e304a0b18bad381916a) Still bug

Thanks for testing this. Seems to be this is an ancient bug. I did take a look at different parts of the code handling pet movement but sadly still don't know what causes this.
