### ISSUE TITLE
Unfortunately new crash attack

### ISSUE THREAD

**Issue by Mestremagos** [azerothcore/azerothcore-wotlk#2446]
I hope noble friends help me
[https://www.mediafire.com/file/b6is7y7je4actm4/erro.txt/file](url) - Full archive here

Call stack:
Address   Frame     Function      SourceFile
00007FF6B31AAD6E  0000000A4A3FF120  Trinity::Assert+6E  e:\server\game_versao_estavel\src\server\shared\debugging\errors.cpp line 33
00007FF6B2E2A162  0000000A4A3FF150  Player::GetCollisionHeight+1E2  e:\server\game_versao_estavel\src\server\game\entities\player\player.h line 2622
00007FF6B2F9EAD6  0000000A4A3FF200  Unit::Mount+276  e:\server\game_versao_estavel\src\server\game\entities\unit\unit.cpp line 12329
00007FF6B3100D6D  0000000A4A3FF240  AuraEffect::HandleAuraMounted+18D  e:\server\game_versao_estavel\src\server\game\spells\auras\spellauraeffects.cpp line 2794
00007FF6B3105E8F  0000000A4A3FF270  AuraEffect::HandleEffect+EF  e:\server\game_versao_estavel\src\server\game\spells\auras\spellauraeffects.cpp line 764
00007FF6B30F8D87  0000000A4A3FF2E0  AuraApplication::_HandleEffect+A7  e:\server\game_versao_estavel\src\server\game\spells\auras\spellauras.cpp line 167
00007FF6B2FB3430  0000000A4A3FF320  Unit::_ApplyAura+C0  e:\server\game_versao_estavel\src\server\game\entities\unit\unit.cpp line 3882
00007FF6B30F8579  0000000A4A3FF3A0  Aura::_ApplyEffectForTargets+239  e:\server\game_versao_estavel\src\server\game\spells\auras\spellauras.cpp line 709
00007FF6B30DB7C0  0000000A4A3FF3E0  Spell::HandleEffects+C0  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 4979
00007FF6B30DA666  0000000A4A3FF4B0  Spell::DoSpellHitOnUnit+966  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 2846
00007FF6B30D94DD  0000000A4A3FF5B0  Spell::DoAllEffectOnTarget+2DD  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 2377
00007FF6B30E77EC  0000000A4A3FF5F0  Spell::handle_immediate+13C  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 3588
00007FF6B30E5DC2  0000000A4A3FF660  Spell::_cast+592  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 3524
00007FF6B30E6936  0000000A4A3FF690  Spell::cast+56  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 3326
00007FF6B30E87AB  0000000A4A3FF6C0  Spell::update+19B  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 3827
00007FF6B30DAB05  0000000A4A3FF6F0  SpellEvent::Execute+25  e:\server\game_versao_estavel\src\server\game\spells\spell.cpp line 7281
00007FF6B31BC833  0000000A4A3FF720  EventProcessor::Update+63  e:\server\game_versao_estavel\src\server\shared\utilities\eventprocessor.cpp line 47
00007FF6B2FB124B  0000000A4A3FF760  Unit::Update+1B  e:\server\game_versao_estavel\src\server\game\entities\unit\unit.cpp line 356
00007FF6B2E5A514  0000000A4A3FF870  Player::Update+94  e:\server\game_versao_estavel\src\server\game\entities\player\player.cpp line 1612
00007FF6B2FD3F6F  0000000A4A3FF940  Map::Update+16F  e:\server\game_versao_estavel\src\server\game\maps\map.cpp line 667
00007FF6B303086D  0000000A4A3FF970  MapUpdateRequest::call+1D  e:\server\game_versao_estavel\src\server\game\maps\mapupdater.cpp line 58
00007FF6B31BDBD9  0000000A4A3FF9A0  DelayExecutor::svc+49  e:\server\game_versao_estavel\src\server\shared\threading\delayexecutor.cpp line 54
00007FF9BCF67E4C  0000000A4A3FF9D0  ACE_Task_Base::svc_run+3C  e:\server\game_versao_estavel\dep\acelite\ace\task.cpp line 273
00007FF9BCF684E9  0000000A4A3FFA10  ACE_Thread_Adapter::invoke_i+69  e:\server\game_versao_estavel\dep\acelite\ace\thread_adapter.cpp line 159
00007FF9BCF68441  0000000A4A3FFA50  ACE_Thread_Adapter::invoke+71  e:\server\game_versao_estavel\dep\acelite\ace\thread_adapter.cpp line 94
00007FF9BBC84F7F  0000000A4A3FFA80  _beginthreadex+107
00007FF9BBC85126  0000000A4A3FFAB0  _endthreadex+192
00007FF9D33284D4  0000000A4A3FFAE0  BaseThreadInitThunk+14
00007FF9D565E8B1  0000000A4A3FFB30  RtlUserThreadStart+21

**Comment by Helias** [comment]
We need to resolve, but if I can't reproduce the crash it's hard to fix.

**Comment by Helias** [comment]
I think that you are using SunwellWoW not AzerothCore, anyway try to update your core with the last 2 commits pushed in master and let me know if you got this crash attack again

**Comment by FrancescoBorzi** [comment]
@Mestremagos which version of AC are you using?

**Comment by Mestremagos** [comment]
SunwellWoW yes I use this version.
I'm sorry if I'm not following the model, I don't have much practice on this platform

**Comment by FrancescoBorzi** [comment]
@Mestremagos sorry but we can't offer support for other cores. Please use latest AC version. You can follow the instructions here:

http://www.azerothcore.org/wiki/Installation
