### ISSUE TITLE
[Fix included] Missing creature_queststarter entry 'Duke Hydraxis'

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2447]
##### SMALL DESCRIPTION:

Duke Hydraxis should start the quest 6804 - he didn't.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC 'Duke Hydraxis' should give the quest 6804. 

##### CURRENT BEHAVIOUR:

Source: 
https://classic.wowhead.com/quest=6804/poisoned-water
https://classic.wowhead.com/npc=13278/duke-hydraxis#starts

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### EXTRA NOTES:

FIX: 

`DELETE FROM `creature_queststarter` WHERE `id` = 13278 AND `quest` = 6804;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (13278, 6804);`

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

-  Max Skill on levelup

**Comment by Endeffect-AT** [comment]
`


`

**Comment by Underminus** [comment]
This quest was removed in patch 3.0.8. 
 - Patch 3.0.8 (2009-01-20): He no longer gives the quest Neutral 15 [56] Poisoned Water

https://wowwiki.fandom.com/wiki/Duke_Hydraxis
