### ISSUE TITLE
All Daily Profession Quest stopped working

### ISSUE THREAD

**Issue by wowpide** [azerothcore/azerothcore-wotlk#2448]
All Daily Profession Quest stopped working

##### SMALL DESCRIPTION:
Daily Profession Quest stopped working go to cooking trainer or fishing trainer and try to get daily quest in dalaran

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Fishing trainer https://wotlk.evowow.com/?npc=28742#starts should give one of 5 quests

##### CURRENT BEHAVIOUR:
giving no dailies at all for fishing , same for cooking and other professions 

##### STEPS TO REPRODUCE THE PROBLEM:
max fishing skill and try to get daily from https://wotlk.evowow.com/?npc=28742#starts

##### EXTRA NOTES:
same with cooking , max cooking skill and try to get daily from npc 29631 Awilo Lon'gomba

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
AzerothCore rev. f9a8de9be767+ 2019-11-15 16:31:54 +0700 (master branch) (Unix, Release)

##### OPERATING SYSTEM:
Debian /10

##### MODULES:
mod-cfbg
mod-indivdual-xp
mod-1v1-arena

##### OTHER CUSTOMIZATIONS:
no

**Comment by FrancescoBorzi** [comment]
@wowpide after which commit did they stop working?

**Comment by Zausender** [comment]
Confirmed. Before merging PR's you need the testers there. Not the people who will merge on their core your PR and just say "TESTED, Builded without errors no problems" What's tested actually so they can confirm it's really tested, the errors won't show alone instantly on build. And that sucks. I just checked some last PR's merged on master, they re merged with confirmation on the comments that i mention already "TESTED, Builded without errors no problems".
We can't know which commit break it, you should ask the people who Merged latest commits

**Comment by FrancescoBorzi** [comment]
@Zausender I agree with you, we should test things more deeply as our application is quite complex and it doesn't have any kind of automated tests in place. I hope more people can help with it.

About this issue specifically, can you please let us know which commit is causing the issue? so we can fix or revert it.

**Comment by sluggor** [comment]
This NPC (28742 - Marcia Chase / Grand Master Fishing Trainer & Supplies) is the quest starter for the Dalaran fishing quests 13830, 13832, 13833, 13834, and 13836. These quests are in pool 5676.

There was a change to the pool manager code a few months ago (#2027) that may be worth a look.

If your last pull was more than a few months ago, you could try reverting that code and see what happens.

Other than #2027, I don't remember seeing any recent issues that dealt with Dalaran NPCs or daily quests.

**Comment by Stoabrogga** [comment]
Tested with commit b1e5943e0aa8a23fea7ed9a3d763830adb778e61 and a fresh DB and I cannot confirm this issue. Could get a new daily fishing quest from Marcia Balzer and a new daily cooking quest from Awilo Lon'gomba.

**Comment by FrancescoBorzi** [comment]
@wowpide @Zausender please help us reproduce the issue on a clean (latest) AC, otherwise we are not able to fix it

**Comment by pklloveyou** [comment]
The players in my server did not report this error and the server ran for two months

**Comment by milestorme** [comment]
It started after this commit https://github.com/azerothcore/azerothcore-wotlk/commit/e83169d715904d4cd79bb8ee12db11018ec3c726 if I go back here it’s working , Also there’s an sql error on setting game_event to 1970 on sql import , MariadB

**Comment by wowpide** [comment]
@pkiloveyou this started in the last week so you can’t if tested tgat this doesn’t work in the last 2 months

**Comment by wowpide** [comment]
@Zausender  you have Linux too and Maria ? This started they are working here https://github.com/azerothcore/azerothcore-wotlk/commit/c294dd3142b10ab822982cda02728818c11f72da on this commit if I go back but I loose the crash fix’s

**Comment by Stoabrogga** [comment]
I'm using Ubuntu 16.04 x64, cmake 3.15.5, clang 7.1.0, MySQL 5.7. And @wowpide this is a hobby project, you don't pay for it and we don't get paid, so instead of just complaining you could also contribute by helping to nail down the errors. We can only fix errors that we can reproduce.

**Comment by wowpide** [comment]
@Zausender did reproduce

**Comment by wowpide** [comment]
I guess only help me if I’m rich and have money to buy fix

**Comment by Stoabrogga** [comment]
Even money cannot help you here as there's too few information to work with.

**Comment by Yehonal** [comment]
I remember a similar issue happened suddenly on a live server, but I don't remember what caused it, fixed with a simple restart if I remember well. Could be an edge case but ofc we should investigate more next time

**Comment by wowpide** [comment]
Thank you @Yehonal

**Comment by manstfu** [comment]
happened for me today solved with server restart, ac rev. 2e17b3250897

Table `character_queststatus_daily` get cleared correctly, but new quest are not assigned to npc's


Modules.
mod-1v1-arena
mod-ah-bot
mod-anticheat
mod-breaking-news-override
mod-cfbg
mod-congrats-on-level
mod-duel-reset
mod-eluna
