### ISSUE TITLE
 Talent Paladin tank [Ardent Defender] not works

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#245]
**Current Behavior**: The talent of paladin [Ardent Defender] does not activate when you have less than 1% health

**Expected behavior**: The talent [Ardent Defender] should be activated, heal up to 30% health and leave you a debuff of 2 minutes so that the talent does not return activating.

**Link**: http://www.wowhead.com/spell=31850/ardent-defender

**Branch(es)**: 1.x

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/cd6209cdb10234201682fd4c15b01964c0fa60ed

**Operating system**:  Windows 2008 R2

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: 
- Transmogrif
- Crossfaction

**Comment by boom8866** [comment]
Normal spell

**Comment by Sworken** [comment]
Test using paladins level 40, 50, 60 and 70. does not work

**Comment by talamortis** [comment]
Think i have fixed this issue, just compiling and testing now

**Comment by falzard** [comment]
Other Customizations:

    Transmogrif
    Crossfaction

Where is that crossfaction module from?

**Comment by HeartWell** [comment]
Everything works fine for me, but it is very difficult to detect under-damage at> 35% health. Just when killing blow vostanavivaet dependent health defense.

**Comment by Sworken** [comment]
The custom modules do not affect this, because I did a clean compilation as well and don't works. 
NOTE: Levels equal to or less than 70

**Comment by talamortis** [comment]
@Sworken  please test the PR #287
