### ISSUE TITLE
Thief lost off-hand weapon  during the attack.

### ISSUE THREAD

**Issue by wang5150753** [azerothcore/azerothcore-wotlk#2458]
commit id：
ded3bd8900e1b3b422c8baec88f82a38b9308115

Thief lost off-hand weapon  during the attack.

##### STEPS TO REPRODUCE THE PROBLEM:

1. start attack
![image](https://user-images.githubusercontent.com/20810531/69138037-e77b3500-0af8-11ea-9cf9-84a79e1b5568.png)

2. eat a 【Delicious wind snake】during attacking.

3. you will see off-hand weapon is missing。
![image](https://user-images.githubusercontent.com/20810531/69138135-1396b600-0af9-11ea-9284-f6cefab9dae4.png)

4.Same issue with item [Deathbringer's Will]‘s effect

**Comment by lineagedr** [comment]
This is known visual CLIENT bug even on retail.

https://youtu.be/R48XiVuLl3E?t=190

**Comment by Helias** [comment]
If this is a client bug I think that we can close this issue.
