### ISSUE TITLE
All branches have this problem

### ISSUE THREAD

**Issue by dust514** [azerothcore/azerothcore-wotlk#2461]
DESCRIPTION
**Killed leader infinitely regenerated**
All branches have this problem，Condition error, Repeat trigger

STEPS TO REPRODUCE THE PROBLEM:
Step video：https://www.mediafire.com/file/5ftytapksd4wdgx/2019-11-20_13-10-34-257.mp4/file

BRANCH(ES): 
master

MODULES:
No

OTHER CUSTOMIZATIONS:
No

AC HASH/COMMIT:
Author:		Nightprince <keramatjokar8855@gmail.com>
Date:		1 day ago (2019/11/18 23:05:25)
Committer:	Francesco Borzì <borzifrancesco@gmail.com>
Commit hash:	ded3bd8900e1b3b422c8baec88f82a38b9308115
Parent(s):	616b8d9fb1

AzerothCore rev. ded3bd8900e1+ 2019-11-18 16:05:25 +0100 (master branch) (Win64, Debug) (authserver)
AzerothCore rev. ded3bd8900e1+ 2019-11-18 16:05:25 +0100 (master branch) (Win64, Debug) (worldserver-daemon)

**Comment by FrancescoBorzi** [comment]
@dust514 can you please add a proper title and a (text) description of the issue?

**Comment by dust514** [comment]
@FrancescoBorzi Added description：Killed leader infinitely regenerated
