### ISSUE TITLE
HELP DB!

### ISSUE THREAD

**Issue by admkiller** [azerothcore/azerothcore-wotlk#2467]
How to apply all DB-updates at once?

**Comment by Helias** [comment]
Use the tool in `apps/db_assembler`

**Comment by admkiller** [comment]
![image](https://user-images.githubusercontent.com/57419173/69567384-06b21080-0f98-11ea-9e4f-8ec214eb3487.png) Which one should I choose?

**Comment by Helias** [comment]
should be the option 7) to apply only the updates

**Comment by admkiller** [comment]
Just choose option 7, which it already updates in the database automatically? or you have to do something else.

**Comment by Helias** [comment]
Before, you should configure the database parameters in the `conf` directory.
Copy `config.sh.dist` into `config.sh` and configure the parameters, at the bottom you will find the mysql credentials and the databases name.

After that, run db_assembler.sh type `7` and `ENTER`, than you should have your database updated.

**Comment by FrancescoBorzi** [comment]
This is not the right place for support, please read:

http://www.azerothcore.org/wiki/How-to-ask-for-help
