### ISSUE TITLE
Kurzen Commando

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#247]
**Description**:
Kurzen commando's in the Kurzen Compound are not stealthed

**Current behaviour**: Tell us what happens
They are visible 100% of the time.

**Expected behaviour**: Tell us what should happen instead
They should be stealthed on spawn or reset.

**Steps to reproduce the problem**:

1.  .go -11523.224609 -677.670410 34.234581 0
2. 
3. 

**Branch(es)**: Master

**AC hash/commit**:  

**Operating system**:  
Windows 10

**Modules**:  Are you using modules? if yes, list them
Transmog

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by cooler-SAI** [comment]
```sql
-- Kurzen Commando
SET @ENTRY := 938;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `source_type`=0 AND `entryorguid`=@ENTRY;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,11,0,100,1,0,0,0,0,11,22766,0,0,0,0,0,1,0,0,0,0,0,0,0,'Cast Sneak on Spawn'),
(@ENTRY,0,1,0,7,0,100,1,0,0,0,0,11,22766,0,0,0,0,0,1,0,0,0,0,0,0,0,'Cast Sneak on Evade'),
(@ENTRY,0,2,0,2,0,100,0,0,60,18000,22000,11,7964,2,0,0,0,0,1,0,0,0,0,0,0,0,'Cast Smoke Bomb at 60% HP');
```

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/246/commits/7f4e075003071da2b7ea388da7e18a3945a1243e

**Comment by ShinDarth** [comment]
@cooler-SAI please can you open a PR ?

@talamortis it's not a good idea to mix things in one PR :D
