### ISSUE TITLE
[Stacking/Auras] Wrecking Crew and Enrage  [Warrior] 

### ISSUE THREAD

**Issue by diluh** [azerothcore/azerothcore-wotlk#2473]
**SMALL DESCRIPTION:**

Wrecking Crew [Arms warrior] and Enrage [Fury Warrior] cant stack, but in this rev
they can. When both stack, its increased 18% or 20% increased dmg for warrior. This shouldn't happens.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

can't stack together

**STEPS TO REPRODUCE THE PROBLEM:**

![image](https://user-images.githubusercontent.com/46387591/69804659-d64bbb80-11bd-11ea-868b-85d91cd3d507.png)

Create a build like this from the 1 duel test image and you'll see that the two spells will stack

Stacked ID Spells [14204] [57521]

**BRANCH(ES):**

Master

**AC HASH/COMMIT:**

e1ee77e

**OPERATING SYSTEM:**

Ubuntu 18.04.3 LTS

MODULES:
None

OTHER CUSTOMIZATIONS:
None

**Comment by Bogir** [comment]
Is it your wish or truth?

**Comment by diluh** [comment]
https://wotlk.evowow.com/?spell=56613
https://wotlk.evowow.com/?spell=13048

Read the description of the spells.

When one of them is activated the other should not activate
What is happening is that if you put talent points to release them on the two arms of talent [Arms and Fury] they are coming together and it can't happen.
@Bogir

**Comment by Stoabrogga** [comment]
According to the patch notes this seems to have been introduced with 3.1.0:
https://wow.gamepedia.com/Patch_3.1.0#General_2
```
[Hysteria], [Tricks of the Trade], Enrage, [Wrecking Crew], [Death Wish], 
[Arcane Power], [Owlkin Frenzy], Beast Within, and [Avenging Wrath] 
damage bonuses no longer stack together.
```

**Comment by GMKyle** [comment]
This is perhaps a visual issue, (i don't know how this spells behave  on retail visually speaking) anyways both spells can be active simultaneously BUT players only benefits from 1 because  they are in the same stack group with (SPELL_GROUP_STACK_FLAG_EFFECT_EXCLUSIVE - Same effects of spells will not stack, yet auras will remain on a target) flag.

**Comment by lineagedr** [comment]
Add
```
switch (Id)
{
case 12880: // Enrage (Enrage)
case 14201:
case 14202:
case 14203:
case 14204:
case 57518: // Enrage (Wrecking Crew)
case 57519:
case 57520:
case 57521:
case 57522:
case 57514: // Enrage (Imp. Defensive Stance)
case 57516:
	return SPELL_SPECIFIC_WARRIOR_ENRAGE;
default:
	break;
}
```

After
https://github.com/azerothcore/azerothcore-wotlk/blob/82d53bf316b82c4ba0aef2162ef097979fd6f506/src/server/game/Spells/SpellInfo.cpp#L2126
```

**Comment by Andrei-UPB** [comment]
Went ahead and did a bit of testing, @GMKyle is correct, it is just a visual bug with both auras being present.

My way of testing was using a constant damage effect (Rend) on a Training Dummy. Talents like Trauma or Blood Frenzy were not picked in order not to influence the rend damage over time.

Without any of the enrages my Rend  hits for 292, with the Wrecking Crew Enrage ( aura 57521 ), my Rend ability hits for 313 which is indeed a ~8% increase. With the other enrage ( aura 14204 ), my Rend hits for 321 which is a ~10% increase.

Now with both buffs active ( 57521 and 14204) Rend hits for 321, therefore proving that the greater effect (14204) takes priority and the two auras stack ONLY visually.

**Comment by Kitzunu** [comment]
The question kind of lands in, is it a bug or not?
In retail did these two auras show at the same time, or did one remove the other?

**Comment by vhiperdev** [comment]
@Kitzunu 
That's just visual the two activated buffs don't stack up  although no benefit is granted in terms of damage output, because damage increases are not accumulating.

In my opinion this can be closed, if you do not want to appear the 2 icons together need to make a condition in add a condition on spell_linked_spell.

**Comment by Kitzunu** [comment]
Yea that was what I was asking if it was a bug that the two auras are shown or if we should change to SPELL_GROUP_STACK_RULE_EXCLUSIVE_HIGHEST

**Comment by vhiperdev** [comment]
I think these spells are currently in SPELL_GROUP_STACK_FLAG_EFFECT_EXCLUSIVE
i agree with you maybe if you change to SPELL_GROUP_STACK_RULE_EXCLUSIVE_HIGHEST could solve.

**Comment by Kitzunu** [comment]
Well actually the stack_rule = 16, which makes 0 sense since there is no rule that high

**Comment by UltraNix** [comment]
That's right - both auras are on the player, but only one works - some auras got additional effects that must be applied as well.
