### ISSUE TITLE
Dire Maul North & West Doors Open-Sound Bug

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2479]
##### SMALL DESCRIPTION:

The Opening-Sound doesn't stop after opening the Doors.  

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After opening the Doors, the Sound should appear one time. 

##### CURRENT BEHAVIOUR:

After opening the Doors at the given locations in Dire Maul North & West the Opening-Sound is bugged and don't stops.  

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the Keys .additem 18249 & 18266
2. Dire Maul North .go 386.414764 373.675995 -1.131539 429 open the Door and listen
3. Dire Maul West .go 51.071949 499.721527 -23.300320 429 open the Door and listen

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 1977336+ 2019-11-22 22:42:00 +0700 (master branch) (Win64, Release) (worldserver-daemon)

##### OPERATING SYSTEM:

Windows 10 Pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

Max Skill on Levelup

**Comment by Stoabrogga** [comment]
I think this is a client bug, at least I don't see how the server can cause this. There's also a very old bug report about this behaviour from 21st November 2010:
https://us.battle.net/forums/en/wow/topic/1083319801

**Comment by Endeffect-AT** [comment]
Alright, thx for checking it!  So as it's a client bug i close this issue.
