### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by elementalwow** [azerothcore/azerothcore-wotlk#2486]
I need to know if there is how to put c ++ Script in the core Azerothcore, because I tried always gives errors.

**Comment by Viste** [comment]
Yes you can! but you don't help you self! A good tone and good help to yourself would be to provide additional information:
What script?
Where you put script?
How you do it ?
What error you get?

**Comment by FrancescoBorzi** [comment]
Please read: http://www.azerothcore.org/wiki/How-to-ask-for-help
