### ISSUE TITLE
Yogg-Saron: Immortal Guardians arent changing the name when they are marked by Empowering Shadows

### ISSUE THREAD

**Issue by jmaguero94** [azerothcore/azerothcore-wotlk#2488]
##### SMALL DESCRIPTION:

Immortal Guardians are not changing the name when they are marked by Empowering Shadows

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When an Immortal Guardian is marked by the spell Empowering Shadows the name of this npc will change to "Marked Immortal Guardian"

##### CURRENT BEHAVIOUR:

When Empowering Shadows: https://wowgaming.altervista.org/aowow/?spell=64467 affects an Immortal Guardian: https://wowgaming.altervista.org/aowow/?npc=33988 the npc arent changing his name to: "Marked Immortal Guardian": https://wowgaming.altervista.org/aowow/?npc=36064

Link to the patch: https://wowwiki.fandom.com/wiki/Patch_3.2.0
Link to the changes in the npc: https://wowwiki.fandom.com/wiki/Immortal_Guardian#toc 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Starts battle with Yogg-Saron
2. Start the P3
3. Wait for a Guardian to be affected by the buff Empowering Shadows

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5f2191337868da233fc6d72c0bf17e204e61d932

##### OPERATING SYSTEM:

Windows 7

**Comment by steenburgh** [comment]
This looks like it was fixed in #5046, can anyone confirm?

**Comment by Si1ker** [comment]
Yes @steenburgh , I already fixed this in #5046
Thanks for the note, closing!
