### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by elementalwow** [azerothcore/azerothcore-wotlk#2489]
I have tried several times to compile this core, but always give the same error. Would you help me?
![image](https://user-images.githubusercontent.com/57023516/70189251-94e17180-16d1-11ea-8d47-6245d1ffae9a.png)

unable to open input file game.lib

**Comment by lineagedr** [comment]
Is worlserver.exe running in the background?

**Comment by elementalwow** [comment]
no

**Comment by lineagedr** [comment]
Copy the compile output and upload it to pastebin.

**Comment by wowpide** [comment]
this is an error from trying to compile Stygiancore not azerothcore

**Comment by FrancescoBorzi** [comment]
missing AC version (commit hash)
