### ISSUE TITLE
[BUG] Taste for Blood / Rend / Warrior 

### ISSUE THREAD

**Issue by RandomReportForYou** [azerothcore/azerothcore-wotlk#2491]
##### SMALL DESCRIPTION:
Taste for Blood doesn't always renew on rend tick, so it reaches 0 seconds.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The tick from Rend should proc the Taste for Blood talent on the warrior at the first tick, and renew it after every 6 seconds because it has a 6 seconds cooldown, so, at 3 seconds (going to 2 seconds) or so remaining it should be renewed to its full duration. 

##### CURRENT BEHAVIOUR:
Against one target, the first tick of rend will always proc Taste for Blood (3/3), the next tick shouldn't and won't proc it, because it's on cooldown, however, the next tick of Rend should always proc Taste for Blood, and sometimes it will, sometimes it won't, it's not consistent, which makes the talent proc reach 0 seconds without being renewed when it should, wasting 1 tick from Rend.
Taste for Blood https://wowgaming.altervista.org/aowow/?spell=56638
Rend https://wowgaming.altervista.org/aowow/?spell=47465
Glyph of Rending (+6s) https://wowgaming.altervista.org/aowow/?spell=58385

##### STEPS TO REPRODUCE THE PROBLEM:
1) Use Rend on a single target or dummy (tested on both a dummy and player druid)
2) Wait for it to deal damage so it procs Taste for Blood (no problem here)
3) Taste for blood should always be renewing itself when it has 3 seconds or so left on its duration (unless rend doesn't deal damage, like on shields)
4) Sometimes (not always) the duration of Taste for blood will reach 0 seconds, because it skipped one Rend tick (but never the first tick)
5)

##### EXTRA NOTES:
Tested using level 80 characters, the warrior had 3/3 on the talent, also improved rend and the rend glyph for the extra 6s, though on a short test, without the glyph, the problem is still present.

Some blizzard evidence of how it should renew itself:
https://youtu.be/nD2stcm4W8M?t=126
https://youtu.be/nD2stcm4W8M?t=267
https://youtu.be/nD2stcm4W8M?t=366
https://youtu.be/nD2stcm4W8M?t=431
https://youtu.be/nD2stcm4W8M?t=468

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
3d34d799a6a9cd76044bbe5e9c895c43bf6119f7

##### OPERATING SYSTEM:
Ubuntu 18.04.2 LTS

##### MODULES:
none

##### OTHER CUSTOMIZATIONS:
none

**Comment by gengarshadowball** [comment]
I can confirm the bug in this (video)[https://www.youtube.com/watch?v=YL2E2sLWIfw]. I'll look into into!

**Comment by UltraNix** [comment]
Already fixed.
