### ISSUE TITLE
build warning on windows 

### ISSUE THREAD

**Issue by Ashland** [azerothcore/azerothcore-wotlk#2494]
not all control paths return a value latest commits 0d2999a can cause crash

##### SMALL DESCRIPTION:
11>  WorldSocketMgr.cpp
11>c:\azerothcore-wotlk\src\server\game\server\worldsocket.cpp(727): warning C4715: 'WorldSocket::ProcessIncoming': not all control paths return a value

##### STEPS TO REPRODUCE THE PROBLEM:
git pull origin and cmake and compile visual studio 15 or 17 warning is on both.

**Comment by milestorme** [comment]
can confirm this
