### ISSUE TITLE
SQL error (duplicate entry)

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2498]
I've noticed at server's console SQL error (4 times for today). It seems - reason is Hunter's pet.
![изображение](https://user-images.githubusercontent.com/25766571/70461841-a0b2a680-1aca-11ea-96b8-fafb66ec93b8.png)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

dda507aaca33

##### OPERATING SYSTEM:

Windows 7

I don't know how to reproduce this error

**Comment by milestorme** [comment]
cannot reproduce

**Comment by Stoabrogga** [comment]
Closing this in favor of #2589.
