### ISSUE TITLE
bwl boss bug

### ISSUE THREAD

**Issue by cnmir2** [azerothcore/azerothcore-wotlk#25]
well done azerothcore team !  in blackwing lair the second boss bugged ! boss_vaelastrasz she should a dialog you could trigger a battle with she by click this dialog! kill the boss_vaelastrasz the second floor door open and you could enter into and go on next boss!

and the last boss also bug i use gm character and go to the last boss but the boss have no dialog to trigger the last battle ! not script

**Comment by ghost1988** [comment]
Work

**Comment by ShinDarth** [comment]
@cnmir2 if you still get this issue, please tell us how to reproduce it.

Read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
