### ISSUE TITLE
MMAPS problem exists

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#250]
**This may be the MMAPS problem**:

**Current behaviour**: The battle is on the hillside.
![5cfs mh 54 xjdbd_uwx](https://cloud.githubusercontent.com/assets/16046064/20513269/d74f9d4c-b0bf-11e6-8ad6-6620f79eec92.png)

More than 50 yards in the release of the master after the release of the magic will be moved to build up

**Expected behaviour**: Specific please test

**Steps to reproduce the problem**:

**Description**:

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by lineagedr** [comment]
https://bitbucket.org/maczuga/sunwellcore/commits/1749037808d1de4f963b65aef117decacf78a8aa

This guy rewrote sunwell vmaps and mmaps should help.

**Comment by boom8866** [comment]
Test the same problem exists

**Comment by Maczuga** [comment]
@lineagedr I'd rather avoid those mmap fixes, weren't that stable. This is most likely a waypoint issue if it does not occur in many places.

**Comment by boom8866** [comment]
Test https://bitbucket.org/maczuga/sunwellcore found that the MMAPS problem is still there

**Comment by mynew3** [comment]
@Maczuga I think this is the TargetedMovementGenerator.cpp core issue  falling underground. But TC core no problem。

**Comment by ShinDarth** [comment]
@Maczuga  I invited you to join our gitter channel:  https://gitter.im/azerothcore/azerothcore

it would be nice if you can join us and work together!

**Comment by Maczuga** [comment]
@ShinDarth Sorry, but I'm not really interested in developing any projects like this. I don't have time for that. That's why I stopped to develop the core I've published. If you want to port changes from my repo - feel free to do that, but I'm not taking a part in anything related to wow development for a long time.

**Comment by lineagedr** [comment]
@Maczuga Thank you for all the hard work and fixes you've provided on your repo, I really appreciate your work. Take care.

**Comment by ShinDarth** [comment]
@Maczuga got it, thanks for having shared the source. See you around!

**Comment by boom8866** [comment]
@Maczuga  Thank you for your sharing
