### ISSUE TITLE
Error "trinity_string' doesn't exist" DB import world_custom.sql

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2500]
Error ""trinity_string' doesn't exist"" DB import world_custom.sql

This error appear for update DB
ERROR 1146 (42S02) at line 18: Table 'world.trinity_string' doesn't exist

STEPS TO REPRODUCE THE PROBLEM:
-Download Acore
-Use DB asembler
-import or update world DB

Comand return this error:
ERROR 1146 (42S02) at line 18: Table 'world.trinity_string' doesn't exist

BRANCH:
master
Laster commit 333dab2

Ubuntu18 no modules

**Comment by Viste** [comment]
its acore_string now, but if you add updates 1 by 1 all should be ok >_<

**Comment by FrancescoBorzi** [comment]
@solidmaxtor do you have any custom scripts?

**Comment by solidmaxtor** [comment]
No custom scripts, problem persist today, if import new DB show error msg. 
All DB charge fine but show this error:
![trinity string](https://user-images.githubusercontent.com/50475454/70688948-e74a0180-1c80-11ea-980c-84fa895aea09.jpg)

**Comment by Stoabrogga** [comment]
@solidmaxtor 
Are you using any modules? Because on the screenshot you are importing "world_custom.sql" which should be empty if you use no modules.

**Comment by solidmaxtor** [comment]
This error no more show in lasted builds, i close this issue, thanks guys.
