### ISSUE TITLE
Glyph of Eternal Water

### ISSUE THREAD

**Issue by Cinnamohn** [azerothcore/azerothcore-wotlk#2503]
##### SMALL DESCRIPTION:

Your Water Elemental persists upon removing or overriding Glyph of Eternal Water in your book.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Your Water Elemental should despawn upon removing or overriding the glyph in your book.

##### CURRENT BEHAVIOUR:

Your Water Elemental persists upon removing or overriding Glyph of Eternal Water in your book.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Insert Glyph of Eternal Water into your book.
2. Spec into the Summon Water Elemental talent in the Mage's Frost tree.
3. Cast Summon Water Elemental.
4. Remove or override the glyph in your book.
5. Continue on your merry way with a permanent Water Elemental.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5e2ac17

##### OPERATING SYSTEM:

Windows 10

**Comment by Endeffect-AT** [comment]
I am already working on the bug because the glyph also learns the Spell id 70908, which does not appear anywhere in the database. 
This is also the reason why the name of the elementary is only displayed on enUS, no matter which locale one uses.

However, I need help to find out where the spell can be found and why it is used.

**Comment by Stoabrogga** [comment]
> Spell id 70908, which does not appear anywhere in the database.

The spell is read from DBC. I think you have to implement an AuraScript which unsummons the Water Elemental if aura 70937 ("Glyph of Eternal Water") is removed. The summoning of the Water Elemental itself is handled here:
https://github.com/azerothcore/azerothcore-wotlk/blob/5e2ac178887ffe8cf322cdd4036acfeab2db4990/src/server/scripts/Spells/spell_mage.cpp#L1052-L1056

**Comment by Endeffect-AT** [comment]
Okay, theres someone with further c++ skills needed...

And what could be the reason why no locales are used?

**Comment by Stoabrogga** [comment]
> And what could be the reason why no locales are used?

Could you please describe in detail what's the actual problem? I don't think I understood that yet.

**Comment by Endeffect-AT** [comment]
The name of the water elemental conjured by spell 70908, learned after using the glyph "Eternal Water", is only in English:
![image](https://user-images.githubusercontent.com/55922592/70849251-14163880-1e7c-11ea-9980-6af0b4b2abc9.png)

I use deDE client.

**Comment by Stoabrogga** [comment]
Ok, understood, but I don't think it's related to this issue. Sadly, I cannot help here, as I'm only using the English client, perhaps something is wrong with your client? Do you have the chance to test further languages?

Concerning the AuraScript to fix the glyph issue I can probably create a PR, just need the time to accomplish this, perhaps in a few days.

**Comment by Endeffect-AT** [comment]
And I could swear it was the spell that caused the problem ... Ok, for the name I have to see what the real problem is
