### ISSUE TITLE
Error compile debian 8

### ISSUE THREAD

**Issue by Darkensand** [azerothcore/azerothcore-wotlk#2512]
![Безымянный](https://user-images.githubusercontent.com/569097/71073441-12ed5000-2189-11ea-82e9-239f0b3c40b9.png)
![Безымянный](https://user-images.githubusercontent.com/569097/71072706-b63d6580-2187-11ea-85e3-2166c5729c1f.png)

**Comment by Helias** [comment]
what is your gcc and g++ version?
try to update them.

**Comment by Darkensand** [comment]
my version is 4.9 how to install the right version ???

**Comment by Helias** [comment]
My version is 7.4.0 try to update it using this guide:

![immagine](https://user-images.githubusercontent.com/519778/71107237-0258cc00-21c1-11ea-9f6f-b29716502426.png)

reference: https://stackoverflow.com/questions/43151627/installing-g-7-0-1-on-debian-8-7

Just look around on the web.

**Comment by Darkensand** [comment]
add
deb http://deb.debian.org/debian experimental main

ok?

**Comment by FrancescoBorzi** [comment]
@Darkensand sorry but this is not the right place to ask for help. Please read:

https://www.azerothcore.org/wiki/How-to-ask-for-help

Open a question on Stackoverflow and we will be happy to help you there, please include as many details as possible (also include your errors as text, not only images, please).
