### ISSUE TITLE
Error compile debian 8 dont closed

### ISSUE THREAD

**Issue by Darkensand** [azerothcore/azerothcore-wotlk#2513]
https://user-images.githubusercontent.com/569097/71072706-b63d6580-2187-11ea-85e3-2166c5729c1f.png
https://user-images.githubusercontent.com/569097/71073441-12ed5000-2189-11ea-82e9-239f0b3c40b9.png
manual https://stackoverflow.com/questions/43151627/installing-g-7-0-1-on-debian-8-7

~# apt-get -t experimental install gcc-7
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gcc-7

**Comment by Darkensand** [comment]
source list 

# deb http://mirror.yandex.ru/debian jessie main

deb http://mirror.yandex.ru/debian jessie main contrib
deb-src http://mirror.yandex.ru/debian jessie main contrib

deb http://security.debian.org/ jessie/updates main contrib
deb-src http://security.debian.org/ jessie/updates main contrib

#deb https://wiki.debian.org/DebianExperimental jessie/updates main contrib
#deb-src https://wiki.debian.org/DebianExperimental jessie/updates main contrib
deb http://deb.debian.org/debian experimental main

deb http://httpredir.debian.org/debian experimental main

**Comment by Darkensand** [comment]
closed

**Comment by BarbzYHOOL** [comment]
you should use debian 9, and that comes from a guy that was using debian 8 when it was already OBSOLETE FOR 1 YEAR lol
