### ISSUE TITLE
Windows 10 x64 - AC Compiles successfully, except for mmaps_generator

### ISSUE THREAD

**Issue by FiftyTifty** [azerothcore/azerothcore-wotlk#2514]
AC Compiles successfully, except for mmaps_generator.

**##### SMALL DESCRIPTION:**

Latest AzerothCore from Github, compiled on fresh Windows 10 LTSC 2019 (Windows build 1809) x64, successfully compiles everything except the mmaps_generator tool.

**##### EXPECTED BLIZZLIKE BEHAVIOUR:**

The executable for the mmaps_generator code should compile like every other part of the solution. Unfortunately, it's the only part that doesn't compile.

**##### CURRENT BEHAVIOUR:**

Here is the log: https://pastebin.com/raw/ZYq6BGff

In particular, here are the relevant error lines:
```
19>C:\servers\azerothcore\src\common\Utilities\Util.h(401): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\IntermediateValues.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(402): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\IntermediateValues.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(401): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(402): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(401): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\MapBuilder.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(402): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\MapBuilder.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(401): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\PathGenerator.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(402): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\PathGenerator.cpp)
16>spell_shaman.cpp
19>C:\servers\azerothcore\src\common\Utilities\Util.h(401): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
19>C:\servers\azerothcore\src\common\Utilities\Util.h(402): error C3861: 'UINT64_C': identifier not found (compiling source file C:\servers\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
```
`19>Done building project "mmaps_generator.vcxproj" -- FAILED.`

**##### STEPS TO REPRODUCE THE PROBLEM:**
1. Follow the instructions here: http://www.azerothcore.org/wiki/Installation
2. The following dependencies were installed: **Win64OpenSSL-1_0_2t** , **vs_Community.exe** , **Git-2.24.1.2-64-bit.exe** , **cmake-3.16.1-win64-x64.msi** , **mysql-5.7.28-winx64** , and **mysql_lib**.
3. When installing Visual Studio Community, the version available was 15.9.18. Here is a screenshot showing the installed components: https://i.imgur.com/E5DN91t.png

**##### EXTRA NOTES:**

I've only ever compiled TrinityCore before, and that was on Ubuntu. The mmaps_generator executable generated just fine, and worked without issue.

**##### BRANCH(ES):**
I've only tried to compile the master branch, which happens to show this behaviour, as per the guide, with the following git command: **git clone https://github.com/azerothcore/azerothcore-wotlk.git --branch master --single-branch C:\servers\azerothcore**

So the branch is master, as of 18/12/2019

**##### AC HASH/COMMIT:**
Running **git log** showed the following in the command line (more than one hash):

$ git log
commit f1f553b5094594beb090ff934eba7bdd1bafd97a (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Wed Dec 18 06:47:54 2019 +0000

    Import pending SQL update file...

    Referenced commit(s): f3b742549bcaa4d73d6e366f36d8d1726888d797

commit f3b742549bcaa4d73d6e366f36d8d1726888d797
Author: Lukas V <55922592+Endeffect-AT@users.noreply.github.com>
Date:   Wed Dec 18 07:45:31 2019 +0100

    fix(DB/Locales): Various names & title fixes in locales (#2482)

commit da91e4a372a41d07e27b5a8ec4f56a82b6950a1e
Author: Shard <30301841+Shard-MW@users.noreply.github.com>
Date:   Tue Dec 17 07:48:22 2019 +0100

    fix(Core/Guild): Crash during money deposit / withdrawal (#2506)

commit 54e93a0ddf976e392cfc8b1bcc381b5394949978
Author: AzerothCoreBot <azerothcorebot@gmail.com>

**##### OPERATING SYSTEM:**
Windows 10 LTSC 2019 (Windows build 1809) x64

**##### MODULES:**
None, only the code downloaded via git as per the instructions is present.

**##### OTHER CUSTOMIZATIONS:**
Nothing extra, everything was done manually by following the guide.

**Comment by Shard-MW** [comment]
I had the same, I reverted this commit to make it compile : 
https://github.com/azerothcore/azerothcore-wotlk/commit/1977336050955f40d6eb33b8c601435e8559a50a

**Comment by FrancescoBorzi** [comment]
@Viste

**Comment by Viste** [comment]
@FrancescoBorzi tomorrow i look on it and maybe fix
today i can\t

**Comment by Viste** [comment]
#2529

**Comment by FiftyTifty** [comment]
It's not been merged into master, so the change isn't applied after calling `git pull`. I'll test, but I need to know how to get that change applied to the downloaded repository.

**Comment by milestorme** [comment]
http://www.azerothcore.org/wiki/How-to-test-a-PR
