### ISSUE TITLE
Nagrand Arena - Weird gameobject spawned

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#2517]
### SMALL DESCRIPTION:
Weird gameobject spawned when the doors opens.
It's spawned on both sides

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Shouldn't be there

##### CURRENT BEHAVIOUR:
![nagrandarenaweird](https://user-images.githubusercontent.com/30301841/71256002-d14ad980-232f-11ea-87e8-e3e4fd176f67.PNG)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Queue into Nagrand Arena

##### EXTRA NOTES:
This isn't beautiful :(

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
4e8c3fd3440e6f773c1f8aadd70d8b86a7b20e55

##### OPERATING SYSTEM:
Windows 10 x64

##### MODULES:
None

**Comment by Shard-MW** [comment]
Confirmed by @Helias @milestorme on Discord btw

**Comment by milestorme** [comment]
Confirmed

**Comment by Helias** [comment]
TC, SkyFire, FirestormWOD have the same coords of ours, I didn't test in game but probably the bug is only in our core (?).
TC use Quaternion to spawn gameobject, this is the difference with AC.

Anyway, I'm trying to fix it using a different coord Z to spawn the gamoebjcts.

**Comment by Helias** [comment]
on TOP the doors break the ceiling, so the coords are definitely wrong.

![immagine](https://user-images.githubusercontent.com/519778/71321870-303f5880-24c0-11ea-9164-9c689688e1a6.png)

**Comment by Helias** [comment]
I think that this is a better way, but probably the size of the gameobject is a little bit bigger than the size of the place where it is spawned.
![immagine](https://user-images.githubusercontent.com/519778/71322836-64207b00-24cc-11ea-9f9f-abc4c7d958c4.png)
