### ISSUE TITLE
Issues with gameobjects visibility

### ISSUE THREAD

**Issue by Shard-MW** [azerothcore/azerothcore-wotlk#2518]
##### SMALL DESCRIPTION:
Sometimes a player can't see gameobject in battleground (or maybe not only in battlegrounds?)
Happened in :
**[BG]** Warsong Gulch - With it's own flag (impact : low)
**[BG]** Arathi Bassin - With the nearest cap (impact : medium -> some ppl can't cap)
**[Arena]** Ring of Valor - With the first pillars (impact : critical -> can go inside the pillar zone and get stuck)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Players should see every gameobject 24/7.

##### CURRENT BEHAVIOUR:
**SOMETIMES** (it doesn't occur everytime) players can't see a specific gameobject.
They have to alt+f4 and relog to see it.

![bggameobjectvisibility](https://user-images.githubusercontent.com/30301841/71256522-4965cf00-2331-11ea-9d20-85348a23ffa3.png)
![arenavisibility](https://user-images.githubusercontent.com/30301841/71256543-54b8fa80-2331-11ea-8c80-582806999a04.png)

##### STEPS TO REPRODUCE THE PROBLEM:
Simply enter in Warsong Gulch/Arathi Bassin or Ring of Valor. Remember that it doesn't occur everytime.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
4e8c3fd3440e6f773c1f8aadd70d8b86a7b20e55

##### OPERATING SYSTEM:
Windows 10 x64

##### MODULES:
None

**Comment by FrancescoBorzi** [comment]
Ancient TC bug. It happened to me from time to time, when it does usually clearing the client's cache and restarting the game solves the issue.

**Comment by Shard-MW** [comment]
I think it's related to our guids system

**Comment by milestorme** [comment]
Can confirm this too , but’s it’s not everytime and it seems different for some players which is weird

**Comment by FrancescoBorzi** [comment]
it would be nice if we could find the steps to reproduce the problem because so far it looks random to me, unfortunately

**Comment by milestorme** [comment]
try using the core before CFBG im getting reports this error does not occur before that commit

**Comment by Shard-MW** [comment]
> try using the core before CFBG im getting reports this error does not occur before that commit

Before which commit ?

**Comment by FrancescoBorzi** [comment]
to be honest it happened to me since a long time (before that module was even created)

but I can't know if that module makes it worse or not

**Comment by milestorme** [comment]
> > try using the core before CFBG im getting reports this error does not occur before that commit
> 
> Before which commit ?

https://github.com/azerothcore/azerothcore-wotlk/tree/34184d4afe6bdc8949e4ba2eb9450ce80d074c0a

**Comment by pklloveyou** [comment]
This error does not occur randomly，Mistakes happen all the time.，For example, in one example, after the death of BOSS, the server sends the data to the client the door has been opened, two players facing the door and the other back to the door, the door facing the player will see the door open, and the back to the door of the player after a certain time turned around, but he also。
I am not sure whether this error belongs to the client or the server.

**Comment by pklloveyou** [comment]
The translation may not be correct, I explain it with screenshots.

**Comment by pklloveyou** [comment]
![1](https://user-images.githubusercontent.com/18535853/75298719-3b22ba80-586e-11ea-977c-0d792db1b9b3.png)
One player faces the door and the other player is in the opposite direction。
![2](https://user-images.githubusercontent.com/18535853/75298767-58578900-586e-11ea-838b-7f9ec44fb212.png)
Kill the BOSS，The player facing the door will see the door open.
![3](https://user-images.githubusercontent.com/18535853/75298806-7329fd80-586e-11ea-8e04-652aa0eef4c4.png)
Another player turns to the gate.You will find that the door is opening.

**Comment by pklloveyou** [comment]
This is just one example.This error occurs in the“object in action”and does not produce too many errors.For example Gates, skill effects, creatures, etc.But if the object is no action, such as "Battlefield flag", it may not see the error occurs

**Comment by pklloveyou** [comment]
![1](https://user-images.githubusercontent.com/18535853/75299734-cd2bc280-5870-11ea-9e56-db3671f6b7b9.png)
![2](https://user-images.githubusercontent.com/18535853/75299736-d026b300-5870-11ea-923e-951235147289.png)
![3](https://user-images.githubusercontent.com/18535853/75299741-d2890d00-5870-11ea-88f5-e701035d74a9.png)

**Comment by pklloveyou** [comment]
![TIM截图20200226082400](https://user-images.githubusercontent.com/18535853/75299936-5b07ad80-5871-11ea-91d4-5b6ada627261.png)

**Comment by pklloveyou** [comment]
This issue could be a client-side“delayed display " issue, and how should we fix it, like Blizzard.

**Comment by Kitzunu** [comment]
Maybe https://github.com/TrinityCore/TrinityCore/commit/b0db728c49f0b70d2c4f18270c389e4445161b7f fixes this issue?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/de6af87bd37ce063e08633eca28bf7d644d83bd2
