### ISSUE TITLE
How Can I change the language of quests etc.?

### ISSUE THREAD

**Issue by Salexes** [azerothcore/azerothcore-wotlk#252]
**Description**: How Can I change the language of quests etc.?

**Comment by boom8866** [comment]
Need other database translation

**Comment by Salexes** [comment]
I found this db for 3.3.5a https://github.com/WoW-Studio/TrinityCore/tree/master/sql/wow-studio/GTDB
but I think TrinityCore also got german localizazions.

I am not sure which one is more complete.

**Comment by ShinDarth** [comment]
Check the ``locales_*`` tables, for example: https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/base/db_world/locales_gossip_menu_option.sql

the locale ID for German is 3, according to https://trinitycore.atlassian.net/wiki/display/tc/Localization+lang

**Comment by Salexes** [comment]
So I just can import the Trinity/GTDB locales and everything should work?

**Comment by HeartWell** [comment]
The database will not help, no localization in the core.

**Comment by Salexes** [comment]
So what does that mean (Sorry I am new to world of warcraft emulation) ?

**Comment by HeartWell** [comment]
This means that the localization of the tasks of the core was cut and its need to add again.

**Comment by Salexes** [comment]
So that means that I need to wait till/if localization is added again, correct?
How long would that probably take?

**Comment by HeartWell** [comment]
Yes, this question to ask the developers of the core.

**Comment by Salexes** [comment]
Will they read this here, or do I need to create a pull request ?

**Comment by HeartWell** [comment]
This here.

**Comment by ShinDarth** [comment]
@Salexes you can open PR and just import from TrinityCore whatever you need from localisations, we are open

**Comment by Salexes** [comment]
So I have the full DB of trinitys 3.3.5 branch, how do I now just import the locales part, so I can import it ?
Sorry I am very new to wow emulators, so sorry for my dumb questions 😄

**Comment by gelsas** [comment]
I imported everything needed from localizations now.
I have a german wow client.
I logged in to the server, created a new char and still everything is completly in english, even with the german locales added to the db.
What should I do now ? How can I fix this ?
