### ISSUE TITLE
[Quest] Gormok Wants His Snobolds

### ISSUE THREAD

**Issue by csgomvs** [azerothcore/azerothcore-wotlk#2520]
Gormok Wants His Snobolds (Quest ID 14090) doesnt work

##### SMALL DESCRIPTION:
When an item is used(ITEM ID 46885) on a creature, it counts nothing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When an item is used on a creature, it must count
https://www.youtube.com/watch?v=RsF8cC2m35k

##### OPERATING SYSTEM:
Ubuntu 18.04.3 LTS

##### MODULES:
AntiCheat
eluna-engine
duelreset
transmog
individual-xp

##### OTHER CUSTOMIZATIONS:
Clear core

**Comment by Stoabrogga** [comment]
Could you please add the commit hash of your AC version? This issue was fixed in PR #2468 which was merged in commit 87bcf2a.

**Comment by csgomvs** [comment]
Thanks. Complete
