### ISSUE TITLE
ice shackles (olo)

### ISSUE THREAD

**Issue by Darkensand** [azerothcore/azerothcore-wotlk#2527]
![WoWScrnShot_122319_225356](https://user-images.githubusercontent.com/569097/71439972-5e14df00-2704-11ea-9add-47bb1dfc9c62.jpg)
![WoWScrnShot_122319_231332](https://user-images.githubusercontent.com/569097/71439973-5e14df00-2704-11ea-863d-1e246311b1d9.jpg)
![WoWScrnShot_122319_225348](https://user-images.githubusercontent.com/569097/71439974-5e14df00-2704-11ea-8134-346377ac9d20.jpg)
There are no walls and mobs on the ice icy lake on the screen, everything is visible

**Comment by FrancescoBorzi** [comment]
@Darkensand you have to include your AC version (commit hash) when opening new issues.

**Comment by milestorme** [comment]
i have this issue too commit AzerothCore rev. f9a8de9be767+

**Comment by FrancescoBorzi** [comment]
@milestorme thanks for confirming

**Comment by Stoabrogga** [comment]
I think you should update your core, at least I don't see this error on commit 0d2999a. This could be a side effect of a bug which was fixed in commit a8ee996.

**Comment by Viste** [comment]
> This could be a side effect of a bug which was fixed in commit [a8ee996](https://github.com/azerothcore/azerothcore-wotlk/commit/a8ee99643119322679235724d40567357fd7fc52).
true

**Comment by Darkensand** [comment]
ty

**Comment by Darkensand** [comment]
Now I will test and unsubscribe to you

**Comment by Viste** [comment]
слово unsubscribe не применимо в данном контексте :) просто write, если ты хотел отписаться :) 
никогда не переводи жаргонизмы.
