### ISSUE TITLE
ice shackles (olo)

### ISSUE THREAD

**Issue by Darkensand** [azerothcore/azerothcore-wotlk#2532]
![WoWScrnShot_122319_225356](https://user-images.githubusercontent.com/569097/71439972-5e14df00-2704-11ea-9add-47bb1dfc9c62.jpg)
![WoWScrnShot_122319_231332](https://user-images.githubusercontent.com/569097/71439973-5e14df00-2704-11ea-863d-1e246311b1d9.jpg)
![WoWScrnShot_122319_225348](https://user-images.githubusercontent.com/569097/71439974-5e14df00-2704-11ea-8134-346377ac9d20.jpg)
There are no walls and mobs on the ice icy lake on the screen, everything is visible

update to https://github.com/azerothcore/azerothcore-wotlk/commit/b776e68665def38af797b02e6a4ed68651bd0f7e

**Comment by Viste** [comment]
Да только скришоты те же чувак :))) в чате то же самое написано ты смешной.

**Comment by Viste** [comment]
Let's take screenshots that have both a bug and a .server info output.

**Comment by Stoabrogga** [comment]
It would also be interesting to know the OS and if any customizations or modules are used. That's what the issue template is all about, don't know why people always delete it.

**Comment by Darkensand** [comment]
![WoWScrnShot_122719_150720](https://user-images.githubusercontent.com/569097/71541145-f3121500-295c-11ea-9b56-b7428cd7914d.jpg)
What are the screenshots? sense of new if the bug remains! So I took the same screenshots, here's a new one for you!
os debian 9

**Comment by Bogir** [comment]
I bet, He is using mod Guildhouse and not applyed .patch correctly.
