### ISSUE TITLE
Suggestion to add new command for developers

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2539]
Can we add a new command for **console** "**.ver**" which will give all info about server for using it as Copy-Past or Screenshot then Admin want to make a new issue here?

Cmake prints many useful things.
Can we use it?
![изображение](https://user-images.githubusercontent.com/25766571/71583553-06b9a900-2b20-11ea-9247-f9da43ee3385.png)

If so, the questions “What mods do you use?”, “What core revision?”,"What OS?" etc. will disappear

**Comment by Nefertumm** [comment]
Mmm i don't know about a whole new command, it can be done inside the .server info command i think :)

**Comment by Kitzunu** [comment]
I don't think this is possible without editing the actual module?

**Comment by IntelligentQuantum** [comment]
@Winfidonarleyan We have it?

**Comment by Winfidonarleyan** [comment]
`.ser debug`
