### ISSUE TITLE
Spell "Chain Lightning" of Elemental Shaman have bug

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2543]
##### SMALL DESCRIPTION:

Skill of Elemental Shaman "Chain Lightning" strikes to 3 target, but makes damage only to first of them.

**/!\ PROBABLY AFFECTS ONLY PEOPLE USING PREMIUM BG MODULES FROM HELIAS**

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Hurls a lightning bolt at the enemy, dealing (180% of spell power) Nature damage **and then jumping to additional nearby enemies. Affects 3 total targets**.

Description here
https://wow.gamepedia.com/Chain_Lightning
##### CURRENT BEHAVIOUR:
Affects only 1 target

##### STEPS TO REPRODUCE THE PROBLEM:
Create Elemental Shaman
Learn spell 421 "Chain Lightning"
Find 3 or more mobs near each other
Select one of them
use Chain Lightning 

Only the selected mob will take damage

##### EXTRA NOTES:

You can switch to revision 4cf20f5c720c0f926d0bbead92843201a2492d5d - everything is ok with this spells

##### BRANCH(ES):

master, last revision 

##### AC HASH/COMMIT:

0f590d03974a+

##### OPERATING SYSTEM:

Windows 7

##### MODULES:

No modules. Clear cloned core

##### OTHER CUSTOMIZATIONS:

![Screenshot_10](https://user-images.githubusercontent.com/25766571/71694039-0d198080-2dbf-11ea-92fb-19687a24faca.jpg)

**Comment by Bogir** [comment]
tested rev. 84be529c76e2 - bug the same.
![изображение](https://user-images.githubusercontent.com/25766571/71771908-4c78d600-2f53-11ea-864b-bfedc66b1920.png)

Additional: spell "**Chain heal**" id 1064 also affects only selected character, but it must also affects 3 targets
![изображение](https://user-images.githubusercontent.com/25766571/71772048-62879600-2f55-11ea-93cc-b7b82243bc7a.png)

**Comment by Bogir** [comment]
Bug have come from revision **10105cab01487cbef761f253725b224f9847e8fb** 
"fix(Core/Deps): Update recastnavigation to last version  (#2189)

Note: you need to re-extract the client data files, or download them from: https://github.com/wowgaming/client-data/releases/tag/v7"

In revision **4cf20f5c720c0f926d0bbead92843201a2492d5d**  everything is ok with this spells
![изображение](https://user-images.githubusercontent.com/25766571/71772703-90bea300-2f60-11ea-8c18-8b97a9fe7f58.png)

How to fix? :D

**Comment by Bogir** [comment]
it works on last rev with reverted 10105cab01487cbef761f253725b224f9847e8fb
![изображение](https://user-images.githubusercontent.com/25766571/71786457-819d2b00-301c-11ea-8ff4-e4aa1f31465e.png)

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/71803017-91f3eb00-309a-11ea-9a29-e3d06b3aa847.png)
10105ca There is no error

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/71803704-7f7ab100-309c-11ea-9f00-ade56ffcf544.png)

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/71803945-10518c80-309d-11ea-8df9-9728f8b8e41c.png)

**Comment by BarbzYHOOL** [comment]
so confusing :(, need more testers

**Comment by solidmaxtor** [comment]
work fine for me, I am test in last master and 1 month ago compiled run server, no problems and no players reports.

**Comment by Bogir** [comment]
Everything is fine in last revision with lastest data-files without data-files from BG-mods (BFG, SalveryValley, TweenPeaks).

**Comment by BarbzYHOOL** [comment]
@Helias @Shard-MW can you guys test? it's related to the premium modules

**Comment by Endeffect-AT** [comment]
Can't confirm on commit 0f590d03974a. Spell is working as expected. 

![WoWScrnShot_010720_201044](https://user-images.githubusercontent.com/55922592/71921919-25581980-318a-11ea-8c74-9df47afeb14a.jpg)

**Comment by Bogir** [comment]
> Can't confirm on commit
Of course!
If I'm not mistaken, you are haven't  premium BG-modules?

**Comment by BarbzYHOOL** [comment]
It's an issue ONLY with the premium contributors BG modules (dbc, maps, etc) @Helias

**Comment by Endeffect-AT** [comment]
So if I read the description above correctly and misunderstood something, I'm sorry.  Didn't suspect a mod bug here

**Comment by solidmaxtor** [comment]
For me work fine but confirm i not use: BG-mods (BFG, SalveryValley, TweenPeaks).

**Comment by skxawng-cu** [comment]
I test it right now with a clean build of rev Master: cf33698040e62ebe2c49d785ea526c114c9d271c
Without any premium bg mods. And Everything is OK.

**Comment by BarbzYHOOL** [comment]
> I have tested it right now with a clean build of rev Master: [cf33698](https://github.com/azerothcore/azerothcore-wotlk/commit/cf33698040e62ebe2c49d785ea526c114c9d271c)
> Without any premium bg mods. And Everything is OK.
> If it is a bug of a premium BG module (PBGM) you must post the issue in its repo. Try to build with only one PBGM by time to detect what have the problem. I'm sorry for my english because I speak spanish.

yes, exactly

**Comment by Helias** [comment]
@Bogir try to test it without replacing Spell.dbc in server-data

**Comment by Nefertumm** [comment]
Can't confirm eadcb1a78208f1b777bbd847048f495128c84372
If it's a bug with the module, open an issue in its repository.
I'm closing this.
