### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pa-ra-dox** [azerothcore/azerothcore-wotlk#2545]
Segmentation fault (core dumped)

##### SMALL DESCRIPTION:
Good morning,

I'll contact you after my last compilation.
Once the DBs are set up, there is no possibility to turn on the server.

MAPS, DBC, VMAPS, MMAPS set up

I have this message
![image](https://user-images.githubusercontent.com/58987080/71745990-16145b80-2e6c-11ea-8224-c814f1e55ee8.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. I don't Know..
2. 
3. 

master

##### AC HASH/COMMIT:
The version I use is this one : https://github.com/azerothcore/azerothcore-wotlk/commit/0f590d03974a3356b324d1eabef4cbc14c176095

##### OPERATING SYSTEM:
Linux Mint 19.3

##### MODULES:
Eluna

**Comment by Winfidonarleyan** [comment]
http://www.azerothcore.org/wiki/Memory-Usage

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/71763053-63361300-2ee8-11ea-9136-3d85e02dd04f.png)

**Comment by pa-ra-dox** [comment]
@Winfidonarleyan i have 32GB of ram ;)
