### ISSUE TITLE
[event] Crown Chemical Co. Hummel not working

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/azerothcore-wotlk#2546]
Crown Chemical Co. Apothecary Hummel not working

##### SMALL DESCRIPTION:
Unable to start event Apothecary Hummel.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When in gossip menu click "Start battle" event will be started

##### CURRENT BEHAVIOUR:
When in  gossip menu click "Start battle" hothing happens

##### STEPS TO REPRODUCE THE PROBLEM:
1. .ev st 8
2. .go cr id 36296
3. Click to Hummel
4. Click "Start battle"

##### BRANCH(ES):
master

##### OPERATING SYSTEM:
ubuntu 18

##### MODULES:
eluna engine
duelreset
transmog
ahbot

##### OTHER CUSTOMIZATIONS:
nothing

**Comment by Bogir** [comment]
First of all, you need to take the quest
No ned to "**.ev st 8**"  (event 8 - "Love is in the Air")
![Screenshot_11](https://user-images.githubusercontent.com/25766571/71765055-ccc21b80-2f00-11ea-964c-beec625544da.jpg)
Acept it
![Screenshot_1](https://user-images.githubusercontent.com/25766571/71765041-a0a69a80-2f00-11ea-89cd-417d1a357618.jpg)

Open item Serving kit - you'll receive Court Subpoena
![Screenshot_4](https://user-images.githubusercontent.com/25766571/71765045-a8663f00-2f00-11ea-89af-44d422e94f4c.jpg)

Finish Quest 
![Screenshot_2](https://user-images.githubusercontent.com/25766571/71765043-a3a18b00-2f00-11ea-9047-d2448d6fe445.jpg)

![Screenshot_5](https://user-images.githubusercontent.com/25766571/71765046-aac89900-2f00-11ea-9361-78d20d39177d.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/25766571/71765048-ad2af300-2f00-11ea-90ee-308f2bfe148a.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/25766571/71765049-ae5c2000-2f00-11ea-8c76-e4fb1161a670.jpg)

**Comment by dev-master21** [comment]
thanks

**Comment by BarbzYHOOL** [comment]
so it's invalid? (and thank you @Bogir )
