### ISSUE TITLE
Extraction Tools for AzerothCore?

### ISSUE THREAD

**Issue by gelsas** [azerothcore/azerothcore-wotlk#255]
Where can I find the extraction tools for mmaps, vmaps etc.? 

A download link to the latest one would be awesome! 

Thanks

**Comment by ShinDarth** [comment]
https://github.com/azerothcore/azerothcore-wotlk/wiki/Installation#5-download-the-data-files

**Comment by gelsas** [comment]
I specifically asked for the extraction tools because I need to extract them from the German client.

**Comment by gelsas** [comment]
Ah there are no working ones, right now. Thanks

**Comment by ShinDarth** [comment]
You can have a look at the current status of dbc/maps extractors, I haven't even tried them
