### ISSUE TITLE
[Quest] DK ID: 12701 (Massacre At Light's Point) Bug

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#2557]
[Quest] DK ID: 12701 (Massacre At Light's Point) Bug

##### SMALL DESCRIPTION:

In this quest you must enter a mining trailer and a miner drags you through the enemy lines to one of the two ships on the beach. When he takes you to the ship on the left, everything is fine; but when it takes you to the ship on the right, the mining trailer stays in the air.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The miner should take you to the ship.

##### CURRENT BEHAVIOUR:

Quest: [Massacre At Light's Point] https://wowgaming.altervista.org/aowow/?quest=12701
Class: Death Knight.
Details: When the miner arbitrarily takes you to the ship on the right, the cart stays in the air and does not reach the ship.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Death Knight.
2. Command: .q a 12701
3. Command: .go xyz 2396.51 -5895.32 110.473
4. Enter in mining cart.
5. Wait for it to arrive on the ship (The error is only when it leaves you on the ship on the right, otherwise: leave the mission (.q r 12701) and repeat from step 2).

Screenshot:

![WoWScrnShot_010820_151900](https://user-images.githubusercontent.com/59569407/72014159-5b9aa500-322d-11ea-831d-96cb88cc722c.jpg)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

cf33698040e62ebe2c49d785ea526c114c9d271c

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

mod-anticheat
mod-bossannouncer
mod-cfbg
mod-transmog
mod-duelreset

**Comment by Bogir** [comment]
https://translate.google.com/

**Comment by skxawng-cu** [comment]
> 
> 
> https://translate.google.com/

I already translated it into English

**Comment by skxawng-cu** [comment]
@BarbzYHOOL, @Endeffect-AT, @Helias: can you test this issue. I am learning CPP right now, but I program in other languages and understand a lot about it. If someone could tell me where the quest scripts are, I could try to fix it myself. I don't know much about the directory structure of AzerothCore. Thanks.

**Comment by skxawng-cu** [comment]
@BarbzYHOOL : I already fix it in PR #2559

**Comment by BarbzYHOOL** [comment]
use deepl.com for translation if needed, I can't test the issue/PR but thank you for the PR
