### ISSUE TITLE
Where is log go to?

### ISSUE THREAD

**Issue by wplatform** [azerothcore/azerothcore-wotlk#2558]
Where is log go to?

##### SMALL DESCRIPTION:

Start the worldserver and authserver with docker.

sudo docker run -d --name ac-authserver \
    --mount type=bind,source="$(pwd)"/docker/authserver/bin/,target=/azeroth-server/bin \
    --mount type=bind,source="$(pwd)"/docker/authserver/etc/,target=/azeroth-server/etc \
    --mount type=bind,source="$(pwd)"/docker/authserver/logs/,target=/azeroth-server/logs \
    -p 127.0.0.1:3724:3724 \
    --network ac-network \
    -it azerothcore/authserver
sudo docker run -d --name ac-worldserver \
    --mount type=bind,source="$(pwd)"/docker/worldserver/data/,target=/azeroth-server/data \
    --mount type=bind,source="$(pwd)"/docker/worldserver/bin/,target=/azeroth-server/bin \
    --mount type=bind,source="$(pwd)"/docker/worldserver/etc/,target=/azeroth-server/etc \
    --mount type=bind,source="$(pwd)"/docker/worldserver/logs/,target=/azeroth-server/logs \
    -p 127.0.0.1:8085:8085 \
    --network ac-network \
    -it azerothcore/worldserver

##### CURRENT BEHAVIOUR:

No log file found in 
/docker/worldserver/logs and /docker/authserver/logs

**Comment by FrancescoBorzi** [comment]
Please follow: https://www.azerothcore.org/wiki/Install-with-Docker#setup

If you have more questions, please open them in StackOverflow under the tag `azerothcore` as explained in: https://www.azerothcore.org/wiki/How-to-ask-for-help

this repository issue tracker is only for reporting bugs
