### ISSUE TITLE
Flight master doesnt work in alliance maps

### ISSUE THREAD

**Issue by rre-za** [azerothcore/azerothcore-wotlk#256]
**Description**:
Flight master menu doesn't show up in alliance bases ( tested in stormwind , ironforge etc... )
it works fine on horde maps , or neutral maps like shattrath... 

but its a one way flight from shattrath to alliance bases , u can go from shattrath to alliance bases but again flight master in alliance map doesnt work so u cant go back

**Steps to reproduce the problem**:

1. taxi cheat on
2. go to stormwind flight master ( or any other alliance base )
3. flight master menu doesn't show up

**AC hash/commit**:  
98b7ce9ea7623547c82ae36b2d63ccd709cd26ac

**Modules**:  transmog - duelreset

**Comment by sucofog** [comment]
https://files.gitter.im/azerothcore/azerothcore/gbUl/blob

https://files.gitter.im/azerothcore/azerothcore/NOo6/blob

https://files.gitter.im/azerothcore/azerothcore/gz8F/blob

Working properly, its not bugged.
