### ISSUE TITLE
Buffs stack

### ISSUE THREAD

**Issue by Zausender** [azerothcore/azerothcore-wotlk#2561]
Stacking buffs

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[This buff does not stack with the paladin buffs [Blessing of Kings] or [Greater Blessing of Kings].](https://wowwiki.fandom.com/wiki/Drums_of_Forgotten_Kings)

##### CURRENT BEHAVIOUR:

Using paladin buff Blessing of the Kings with Drums of forgotten kings apply both buffs. on player.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create paladin, buff self with Kings
2. .add item 49633 ( Drums of F.Kings) and use it
3.  Result, you have Kings 10% buff and 8% Drums buff

##### BRANCH(ES):

master

**Comment by Ashland** [comment]
Yes this buffs stack for me too

**Comment by BarbzYHOOL** [comment]
hmm isn't this behaviour defined in the dbc normally ? or maybe it's a special spell

**Comment by GMKyle** [comment]
"Visual" issue (i don't know how this spells behave on retail visually speaking), same as https://github.com/azerothcore/azerothcore-wotlk/issues/2473

**Comment by Zausender** [comment]
> "Visual" issue (i don't know how this spells behave on retail visually speaking), same as #2473

How its visual, when stats get increased from both buffs? (You should test first). Also, I did tc setup,  their core doesn't  have this issue.

**Comment by GMKyle** [comment]
I tested and i can't reproduce, players only benefits from Blessing of Kings  if  the 2 buffs are present (10 % better than 8%). Perhaps some else should test this.

**Comment by Stoabrogga** [comment]
I also cannot reproduce this issue. If both buffs are present only the greater one is applied to the stats (10%).

**Comment by Zausender** [comment]
To be honest, you tested it just with Greater Blessing of Kings, in combination with drums. That's incorrect, and there stats isn't increased when both are applied.
Like i said, test with Blessing of Kings (Not Greater) and you'll see problem.
Will show now with images behaviour:

**Drums in combination of Blessing of Forgotten Kings:**

1. **Without buffs**
![nokings](https://user-images.githubusercontent.com/56157973/72339860-63dc5f80-36c7-11ea-88bf-d60ace173e0d.png)

2. **With Drums applied (Stats increased)**
![8kings](https://user-images.githubusercontent.com/56157973/72339872-68087d00-36c7-11ea-8656-212685b1c209.png)

3. **With Drums and Kings (Paladin buff) - Stats increased from both.**
![10%](https://user-images.githubusercontent.com/56157973/72339893-70f94e80-36c7-11ea-99bd-b36309463ab4.png)

**Now images when Greater Blessing of Kings applied with Drums**

1. **Greater Blessing of Kings applied (Stats increased)**
![greater10](https://user-images.githubusercontent.com/56157973/72340883-44decd00-36c9-11ea-87d4-ab52065fe9a3.png)

2. **Greater Blessing of Kings + Drums (Stats not increased for both, as you can see we have same stats now like on first image, which mean it's correct only with Greater Blessing of Kings)**
![greateranddrums](https://user-images.githubusercontent.com/56157973/72340957-6b046d00-36c9-11ea-9d40-2648bbbff0fe.png)



I'm on the https://github.com/azerothcore/azerothcore-wotlk/commit/d769d0e62c5ae7b29f28ad55138120e360f60019 version, and this problem exist there.
Just downloaded latest ac, clean, without any modules or edits, problem is same.

**Comment by Stoabrogga** [comment]
I tested it with "Blessing of Kings", not with "Greater Blessing of Kings".

**Comment by Zausender** [comment]
> I tested it with "Blessing of Kings", not with "Greater Blessing of Kings".

Stoabrogga commented 4 hours ago
I also cannot reproduce this issue. If both buffs are present **only the greater one** is applied to the stats (10%).

**Comment by Stoabrogga** [comment]
Yes, 10% is greater than 8%, that's what I meant.

**Comment by Zausender** [comment]
> Yes, 10% is greater than 8%, that's what I meant.

You should have written it a little more precisely. Because we already have that name clearly declared Greater Blessing of Kings -> Blessing of Kings (Not same) / Both of them give benefit 10% impStats, so it's not 10% is greater than 8%. But nevermind, i understand what you mean.
So, let's leave this issue opened until someone else confirm this as the valid issue. And as the comparison on the trinity core, they doesn't have this problem (Actually they fixed it, any of the Greater buffs from Paladin replace drums, that's also blizzlike behaviour) and that is how the spell should work here too.

**Comment by Stoabrogga** [comment]
If I meant "Greater Blessing of Kings" I would have written so. And 10% from the Blessing of Kings is greater than 8% from the Drums, and in my tests only the 10% were applied to the stats.

**Comment by Zausender** [comment]
Just checked a bit more, and something is wrong here with core and DB spell_group / stack_rules

**Comment by pangolp** [comment]
Perform the following tests.

**First:**
- Use 10-minute kings and then the drums.
The results were that when I applied the kings, my statistics increased, but then when I used the drums they didn't change.

**Next:**
- Use the drums first and then the kings.
The result was that the drums increased my statistics by 8%, but when I used the kings, they were replaced by the 10% buffo, obtaining the same result.

**In conclusion**
As much as you have both buffos, your stats are always 10%.
We should only prevent the use of drums, in case there are kings I think, if I'm not wrong, the issue is so.

<a href="https://subefotos.com/ver/?25dbdbefc165c2575cf378d73e5ddd0ao.png" target="_blank"><img src="http://thumbs.subefotos.com/25dbdbefc165c2575cf378d73e5ddd0ao.jpg" /></a>
<a href="https://subefotos.com/ver/?e23dd0ee42562643e4812251bd4933d4o.png" target="_blank"><img src="http://thumbs.subefotos.com/e23dd0ee42562643e4812251bd4933d4o.jpg" /></a>
<a href="https://subefotos.com/ver/?31c4771d7dce31e89accba9a9bbe85bdo.png" target="_blank"><img src="http://thumbs.subefotos.com/31c4771d7dce31e89accba9a9bbe85bdo.jpg" /></a>
<a href="https://subefotos.com/ver/?ac2d7eeb23c4c2396effcac939bb311co.png" target="_blank"><img src="http://thumbs.subefotos.com/ac2d7eeb23c4c2396effcac939bb311co.jpg" /></a>
<a href="https://subefotos.com/ver/?cb51d9ef3be8a1a4cde8fff015a5f636o.png" target="_blank"><img src="http://thumbs.subefotos.com/cb51d9ef3be8a1a4cde8fff015a5f636o.jpg" /></a>

**Comment by Stoabrogga** [comment]
@Zausender 

> The steps to reproduce it:
> 
>     1. First, do Drums buff
> 
>     2. Check your character stats (They're increased)
> 
>     3. Now apply paladin kings (Stats increased more)

Of course the stats increase if you apply the Blessing of Kings **after** the Drums: Blessing of Kings has a 10% buff which overwrites the 8% buff of the Drums. But they don't stack, you are not getting 18% increased stats or something like that.

**Comment by pangolp** [comment]
No, neither way you get 18%. The maximum number is always 10% regardless of the way they are applied. You should only perhaps prevent one from being used if the other is present. I think that's officially the way it is. But I could be wrong.

**Comment by Stoabrogga** [comment]
Yeah, that's what @GMKyle meant with "visual" issue above, you have both icons in the buff list. But technically it's correct, because only the biggest buff is applied to the stats.

**Comment by pangolp** [comment]
I mean, wouldn't it be a problem to have both of them in the picture? It can be confusing for people. Anyway, if you check the statistics, you'll notice that you don't get any benefit.

**Comment by Zausender** [comment]
> @Zausender
> 
> The steps to reproduce it:
> 1. First, do Drums buff
> 
> 2. Check your character stats (They're increased)
> 
> 3. Now apply paladin kings (Stats increased more)
> 
> 
> Of course the stats increase if you apply the Blessing of Kings after the Drums: Blessing of Kings has a 10% buff which overwrites the 8% buff of the Drums. But they don't stack, you are not getting 18% increased stats or something like that.

To be clear about this, it's not visual bug, it's mistake somewhere in the core or the db cuz when you check character current auras, the character has both auras which means one aura isn't removed. Also, you can check for example druid Marks of Wild with Drums of the Wild which work same like that Kings buff. Even both of them are created by LW (We have correct way with the Drums of Wild, druid buff replacing Drums always and one aura stick on character).
Same, how that spell work, this Kings should work also. I tried to check core in the spells, but can't find nothing related to this calculations, only one which i find is the Hack fix for the GBOS (Greater blessing of Sanctuary).

**Comment by Stoabrogga** [comment]
I think it is wrong to remove the aura with the smaller buff, because after all it's a valid aura. If the bigger buff aura is removed the lower one still exists and then applies it's increase to the stats. Sorry, but I don't see any error here, everything's working as intended.

**Comment by Stoabrogga** [comment]
There's also a comment on wowhead:
https://www.wowhead.com/item=49633/drums-of-forgotten-kings#comments:id=908904:reply=140475
`It does not stack. You can have both buffs on you, but you won't be getting 18% to all stats, only 10%, from the stronger spell.`

**Comment by NixAJ** [comment]
You may all refer to

"https://wowwiki.fandom.com/wiki/Buff"

Which document generally speaking which buffs are overriden in what order.

**Comment by Zausender** [comment]
> There's also a comment on wowhead:
> https://www.wowhead.com/item=49633/drums-of-forgotten-kings#comments:id=908904:reply=140475
> It does not stack. You can have both buffs on you, but you won't be getting 18% to all stats, only 10%, from the stronger spell.

**Is this enough? :)**

![rec](https://user-images.githubusercontent.com/56157973/72395800-f36f2600-373a-11ea-975d-b7e1890d8ada.gif)

**Comment by Stoabrogga** [comment]
They already do not stack, so nothing to fix here in my opinion. And as the wowhead comment from 2010-01-01 (patch 3.3.0) states you can have both buffs on a player character, but only the stronger one counts. Sorry, but I said everything I have to, I'm out of this discussion.

**Comment by Zausender** [comment]
> They already do not stack, so nothing to fix here in my opinion. And as the wowhead comment from 2010-01-01 (patch 3.3.0) states you can have both buffs on a player character, but only the stronger one counts. Sorry, but I said everything I have to, I'm out of this discussion.

Go and play retail, try buff up both of them, maybe you understand, and accept it. Even stats are not stacked, the only one icon (from higher spell eff) can be there (writing and trying to provide infos like its visual bug only, its unprofessional and in one hand sad). I didnt except a lot from you, to be honest, related to your way of commenting and providing some comments of course you re out of discussion,  because you cant provide better info, except random person comment. Everyone can put comment there, so it doesnt help a lot and doesn't give any proofs at all. 
I would like to hear the explanation about same item spell "Drums of the wild" which work in same way like "Drums of forgotten kings" why that Drums of the wild doesnt provide buff (icon) near Druids buff Mark of The Wild (Why we dont have icons from both buffs? And why higher buff override lower, in this situation Druid buffs stay at buffed character, and the buff from drums of wild is removed. Isn't that interesting, no?
I think it's very simple to understand this, but you have your own way. So keep it, I'll keep mine.

P.S I found what causing it.

**Comment by BarbzYHOOL** [comment]
I agree with stoabrogga and I trust GmKyle, Stevej and Stoabrogga tests as they proved us they are serious in the past.

**Comment by Nefertumm** [comment]
For who want to avoid having both icons instead of 1, just add a condition on spell_linked_spell.
