### ISSUE TITLE
ICC: Putricide Trap [Heroic]

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#2568]
Description: Once you kill Rootface / Festergut and open pipes for gas / slime you have to do mini gauntlet to open doors towards Putricide. Everything works perfect on Normal, but Heroic ... It's not possible to do it.

Current behaviour: On normal (Both 10 and 25) it works perfect, but when you switch to Heroic there is 1shoot mechanic. I'm not sure why it's happening. It's melee attack players for over 300k.

Expected behaviour: It shouldn't one shoot players.

Check pictures from Heroic testing (First i thouth there is problem cause i had few extra buffs on me)

https://i.imgur.com/jW1U5Hc.jpg
https://i.imgur.com/8zsBDW5.jpg

Branch(es): Master.
Modules: Auto Balance
AC hash/commit: Latest, up to date.
Operating system: Linux, Debian 9

**Comment by pangolp** [comment]
Good day and thanks for the report. I went to the instance and cannot reproduce the error in difficulty of 10 heroic at least. I mean, it worked fine for me.

**Comment by Knindzagxg** [comment]
Must be something from Autobalance, will check more about this.

**Comment by Ashland** [comment]
It’s not auto balance it’s a spell being cast by the trap in the hallway,     SPELL_GIANT_INSECT_SWARM            = 70475,

Hits for over 4 million damage , not sure if this is blizzlike or not but it kills whoever sets it off there’s 2 traps in there tgat are unavoidable

**Comment by Nefertumm** [comment]
This is about autobalance. If I'm not mistaken, that spell does percentage damage, so you can work around that. I would recommend to disable the event while the error is getting fixed.
However, I think this issue has to be opened in the module's issue section.
