### ISSUE TITLE
[BUG][SPELL][PALADIN] Judgement of Justice

### ISSUE THREAD

**Issue by V3nomAnc3r** [azerothcore/azerothcore-wotlk#2569]
##### CURRENT BEHAVIOUR:

https://wowgaming.altervista.org/aowow/?spell=53407

preventing them from fleeing and limiting their movement speed.  << this part not working
##### STEPS TO REPRODUCE THE PROBLEM:

1. Create Paladin
2. .npc add 26327 << Paladin Trainer
3.  [Judgement of Justice] Use this spell

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d769d0e62c5ae7b29f28ad55138120e360f60019

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

NO

##### OTHER CUSTOMIZATIONS:

NO

**Comment by Alireza-mz** [comment]
confirm

**Comment by Zausender** [comment]
Confirmed, The movement is the same with/without Judgement of Justice

**Comment by Stoabrogga** [comment]
Cannot confirm this issue. As Druid in Travel Form you are reduced to normal speed when Judgement of Justice is applied, so working correctly. This is not a slow effect, it is only limiting speed to normal speed:
https://wow.gamepedia.com/Judgement_of_Justice
```
Judgement of Justice
Cannot flee or move faster
than your normal movement
speed. This is not considered a
movement impairing effect.
Duration: 20 seconds 
```

**Comment by V3nomAnc3r** [comment]
@Stoabrogga Thank you, I didn't know.
