### ISSUE TITLE
[Quest] Shoot Em Up FIX

### ISSUE THREAD

**Issue by Chinoske** [azerothcore/azerothcore-wotlk#257]
**Description**: Fix for quest

**Steps to reproduce the problem**:

1. Does not mark the mission of killing the dragons (bug)
 SQL: (FIX) World

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=56578 AND `ElseGroup`=1;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13, 3, 56578, 0, 1, 31, 0, 3, 30330, 0, 0, 0, 0, '', 'Spell Rapid-Fire Harpoon targets only Jotunheim Proto-Drake');

DELETE FROM `smart_scripts` WHERE `entryorguid` = 30330;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(30330, 0, 0, 0, 25, 0, 100, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Jotunheim Proto-Drake - On Reset - Set Active'),
(30330, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 33, 30330, 0, 0, 0, 0, 0, 18, 40, 0, 0, 0, 0, 0, 0, 'On Death - Kill Credit');

**Comment by ShinDarth** [comment]
thanks @Chinoske , can you please [open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request) ?

**Comment by Yehonal** [comment]
Any update about this issue?

**Comment by Rushor** [comment]
better fix: https://github.com/TrinityCore/TrinityCore/commit/0df7d22a89c09e3a15711211dec77fed8613cd1a

**Comment by ShinDarth** [comment]
@Rushor can you open a PR please?

**Comment by Rushor** [comment]
no need to pr, just cherry-pick it from trinitycore :)

**Comment by ShinDarth** [comment]
there is a different format to deal with SQL files, in a way that devs will not have duplication issues in testing a PR with SQL inside after that PR got merged:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files

**Comment by starrheld** [comment]
Fix:

``` SQL
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=13 AND `SourceEntry`=56578 AND `ElseGroup`=1;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13, 3, 56578, 0, 1, 31, 0, 3, 30330, 0, 0, 0, 0, '', 'Spell Rapid-Fire Harpoon targets only Jotunheim Proto-Drake');


UPDATE `creature_template` SET `AIName`='SmartAI', `flags_extra`=`flags_extra`|64 WHERE `entry`=30330;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 30330 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(30330, 0, 0, 0, 25, 0, 100, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Jotunheim Proto-Drake - On Reset - Set Active');

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=18 AND `SourceGroup`=30337 AND `SourceEntry`=43671;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES 
(18, 30337, 43671, 0, 0, 9, 0, 13069, 0, 0, 0, 0, 0, '', "Spellclick requires Active (taken) quest Shoot 'Em Up.");
```

**Comment by talamortis** [comment]
could you please do a PR
