### ISSUE TITLE
[BUG] Hunter pet stay Bug

### ISSUE THREAD

**Issue by V3nomAnc3r** [azerothcore/azerothcore-wotlk#2570]
##### STEPS TO REPRODUCE THE PROBLEM:

1. https://streamable.com/93dsq

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d769d0e62c5ae7b29f28ad55138120e360f60019

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

NO

##### OTHER CUSTOMIZATIONS:

NO

**Comment by Zausender** [comment]
Confirmed (broken). This problem didn't exist before.
Now to attack someone with pet, you have to spam first attack button, and then use pet abilities

**Comment by Stoabrogga** [comment]
I think this is the same issue as described here:
#2440

**Comment by V3nomAnc3r** [comment]
So! Please add label Priority - High, because hunter can't play pvp with this bug.

**Comment by FrancescoBorzi** [comment]
then I'm closing this in favour of https://github.com/azerothcore/azerothcore-wotlk/issues/2440, which I'll mark as high priority

please search among the existing issues before creating a new one, and leave a comment in the existing issue with "confirmed on rev XXXX" replacing XXXX with your AC commit hash
