### ISSUE TITLE
ACore players conections limitation

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2573]
recibe this text ever have exactly population namber.

![unknown](https://user-images.githubusercontent.com/50475454/72227149-22cd3980-3567-11ea-990e-4fbd6827c0db.png)

```Out of file descriptors, suspendig income conections for 10 seconds```

Discard completly dedicate resources
64 gb ram
1gbps Bandwhit
xeon2165 6c/12t 3500mhrz
ssd 480gb

Discart changes and improvements in mysql and sysctl.conf

Exactly player number for ocurrence is 950 check this image
ADD: Discard world config max players for 0 or 1k+ 2k+ ect its same message same namber 950 , login is very slow for more conections.

![950](https://user-images.githubusercontent.com/50475454/72227252-55c3fd00-3568-11ea-85da-2934fd565aa2.jpg)

##### BRANCH(ES):
AzerothCore rev. 6a14c29e25e3+ 2020-01-07 11:18:36 +0100 (master branch) (Unix, Release)

##### OPERATING SYSTEM:
Ubuntu 18

##### MODULES:
mod-anticheat
mod-boss-announcer
mod-duel-reset
mod-transmog
mod-individual-xp
mod-weekend-xp
mod-congrats-on-level
mod-cfbg (no active)

**Comment by Stoabrogga** [comment]
You can list all open file descriptors using the following command, perhaps this shows something strange:
`ls -al /proc/*/fd/* 2>/dev/null`
Open sockets and open files share the same file descriptor table. The maximum number of entries in this table is specified here:
`/proc/sys/fs/file-max`

**Comment by solidmaxtor** [comment]
@Stoabrogga send file for discord pm
Discard now: "CloseIdleConnections = 0"

**Comment by Stoabrogga** [comment]
I'd never use `CloseIdleConnections = 0` as this would cause sockets to remain open. I don't even know why we have such a parameter, doesn't make sense.

**Comment by solidmaxtor** [comment]
CloseIdleConnections its for this Merged:
https://github.com/azerothcore/azerothcore-wotlk/pull/1550

This is optional for no disconect players afk
I test this active and inactive for same problem with limit 950

**Comment by Stoabrogga** [comment]
Ok, then I have no idea, sorry. I also see nothing strange in the file you sent. The error should only occur if you are reaching the limit specified in ` /proc/sys/fs/file-max`, but you are far below this limit, as you can see if counting the open file descriptors:
`ls -al /proc/*/fd/* 2>/dev/null | wc -l`

**Comment by Stoabrogga** [comment]
It could also be that you hit the maximum open files per process. You can check the limits of the worldserver process using this command:
```
# cat /proc/$(pgrep worldserver)/limits | fgrep 'Max open files'
Max open files            1024                 1048576              files
```
In this example the maximum allowed number of open files is 1024. You can change this (see https://linux.die.net/man/5/limits.conf):
`vi /etc/security/limits.conf`
Add this for the appropriate user (here: root):
```
root      soft    nofile      100000
root      hard    nofile      100000
```
It will increase the allowed limit to 100000. I don't know if a reboot is necessary after changing this.

**Comment by Viste** [comment]
i read this few times but still dont understand whats happen? and why if you get OoFD where is the system variables to make sure it's a core bug? 
No useful information, just a screenshot with an error and some speculation.

**Comment by solidmaxtor** [comment]
Yeah i will test this in few hours. Its important share again this tips for Yehonal in this zip:

[yehonaltips.zip](https://github.com/azerothcore/azerothcore-wotlk/files/4055172/yehonaltips.zip)

This lost when close old forun in azerothcore.org

**Comment by BarbzYHOOL** [comment]
I think this is a very old issue and is normally listed in the zip above (my zip xD) because I remember reading that you must increase that number in your linux settings. If it's that, it's not that worrying Maxtor ;)

**Comment by solidmaxtor** [comment]
Solved guys, thanks for all help =)

**Comment by FrancescoBorzi** [comment]
@solidmaxtor it would be nice if you could document the issue you had and how you solved it opening a question (for the issue) and answer (for the solution) on stackoverflow

**Comment by BarbzYHOOL** [comment]
so your players no longer have to wait 3 seconds to log in ?

**Comment by skxawng-cu** [comment]
Hi. I am the admin of https://www.sking.nat.cu, I have more than 700 online users every day. I change the file descriptors limit but when worldserver start It log: Max number of sockets connections 1024. And after 24 hours uptime launch the same message: Out of file descriptors... Someone can help me.

**Comment by Helias** [comment]
@solidmaxtor

**Comment by skxawng-cu** [comment]
I have found the source of the error. When I run the server directly it works fine, the problem is when I start it as a daemon service.

**Comment by Yehonal** [comment]
Simple recipe

Add to /etc/security/limits.conf

Follow this: https://forum.proxmox.com/threads/proxmox-ulimit-hell-how-to-really-increase-open-files.81073/#post-358160

* soft core unlimited
* hard core unlimited
* soft data unlimited
* hard data unlimited
* soft fsize unlimited
* hard fsize unlimited
* soft memlock unlimited
* hard memlock unlimited
* soft nofile 1048576
* hard nofile 1048576
* soft rss unlimited
* hard rss unlimited
* soft stack unlimited
* hard stack unlimited
* soft cpu unlimited
* hard cpu unlimited
* soft nproc unlimited
* hard nproc unlimited
* soft as unlimited
* hard as unlimited
* soft maxlogins unlimited
* hard maxlogins unlimited
* soft maxsyslogins unlimited
* hard maxsyslogins unlimited
* soft locks unlimited
* hard locks unlimited
* soft sigpending unlimited
* hard sigpending unlimited
* soft msgqueue unlimited
* hard msgqueue unlimited

root soft core unlimited
root hard core unlimited
root soft data unlimited
root hard data unlimited
root soft fsize unlimited
root hard fsize unlimited
root soft memlock unlimited
root hard memlock unlimited
root soft nofile 1048576
root hard nofile 1048576
root soft rss unlimited
root hard rss unlimited
root soft stack unlimited
root hard stack unlimited
root soft cpu unlimited
root hard cpu unlimited
root soft nproc unlimited
root hard nproc unlimited
root soft as unlimited
root hard as unlimited
root soft maxlogins unlimited
root hard maxlogins unlimited
root soft maxsyslogins unlimited
root hard maxsyslogins unlimited
root soft locks unlimited
root hard locks unlimited
root soft sigpending unlimited
root hard sigpending unlimited
root soft msgqueue unlimited
root hard msgqueue unlimited
