### ISSUE TITLE
Help Motd

### ISSUE THREAD

**Issue by elementalwow** [azerothcore/azerothcore-wotlk#2575]
Hello I would like some help, I installed the core of azerothcore. I was wondering how to remove this message "This server runs on AzerothCore www.azerothcore.org"
![image](https://user-images.githubusercontent.com/57023516/72285791-a39d3b80-3622-11ea-87bf-ff83c82300de.png)

**Comment by BarbzYHOOL** [comment]
maybe we can pay you to use azerothcore too, what do you think?

**Comment by elementalwow** [comment]
I don't wanna get paid, thanks. I only wish for help!

**Comment by Bogir** [comment]
change the server to Mangos

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L1453
