### ISSUE TITLE
BG Disbalance

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/azerothcore-wotlk#2578]
##### SMALL DESCRIPTION:
BattleGround Balance

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The difference between the number of players is not more than 2

##### CURRENT BEHAVIOUR:
10 players from horde and 1-2 players from alliance (And vice versa)

##### STEPS TO REPRODUCE THE PROBLEM:
idk

##### EXTRA NOTES:
How to establish the difference in the number of players?
I need maximum 1 players diff
```

#
#    Battleground.InvitationType
#        Description: Set Battleground invitation type.
#        Default:     0 - (Normal, Invite as much players to battlegrounds as queued,
#                          Don't bother with balance)
#                     1 - (Experimental, Don't allow to invite much more players
#                          of one faction)
#                     2 - (Experimental, Try to have even teams)

Battleground.InvitationType = 1

#

```
config settings (InvitationType = 1 doesn't working)
##### BRANCH(ES):
master

##### OPERATING SYSTEM:
Ubuntu

##### MODULES:
none

**Comment by MakUCI** [comment]
Battleground.InvitationType = 2

**Comment by solidmaxtor** [comment]
I am use ```Battleground.InvitationType = 2```
Never have problems for disbalance.

**Comment by dev-master21** [comment]
changed Battleground.InvitationType = 1 to Battleground.InvitationType = 2
the difference between the players remained
(2vs5). Need maximum 1 player difference...

**Comment by MakUCI** [comment]
weird there isn't BG who call with 7 players, minimun is 10 WSG-random bg, 15 AB-EotS, 40 AV

**Comment by Voidx** [comment]
This is still happening. In some cases, if a player leaves the battleground (not sure how), the battleground ends up 10v8 or 10v9.
