### ISSUE TITLE
We have a too large file of 72MB for Github

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2582]
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File data/sql/base/db_world/broadcast_text_locale.sql is 72.88 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remot
```

Max size is 100MB  I think, should we worry ?

**Comment by FrancescoBorzi** [comment]
we should not worry, however we should at least remove big files from the git history

**Comment by Bogir** [comment]
Let's divide his queries by languages (each lang into a separate file)

**Comment by Kitzunu** [comment]
Personally I have issues when trying to import broadcast_text_locale.sql from base to DB, could that be due to it being too big?
https://gist.github.com/Kitzunu/d146b76e4104ba3120cafa4e3208c0a5

Some other guy (don't remember) also confirmed that.

**Comment by LukasVolgger** [comment]
The "some other guy" confirms again.

**Comment by Kitzunu** [comment]
My memory is short sometimes haha, sorry and thanks Lukas 🗡️

**Comment by Bogir** [comment]
I suggest to divide *_locale.sql to 8 different tables:
*_enUS_locale.sql
*_deDE_locale.sql
*_frFR_locale.sql
*_ruRU_locale.sql
and so on.
500 000+ records in broadcast_text_locale is too much ((
![изображение](https://user-images.githubusercontent.com/25766571/80138006-d6a18480-85ac-11ea-8459-7b55606d3092.png)

**Comment by Kitzunu** [comment]
I agree that could be a good option

**Comment by Goatform** [comment]
How about you divide (split) source code and database into 2 separate repositories.
This way you will not only make it more readable and easier to track changes but generally better for downloading etc.

**Comment by FrancescoBorzi** [comment]
> How about you divide (split) source code and database into 2 separate repositories.
> This way you will not only make it more readable and easier to track changes but generally better for downloading etc.

Originally it was like this in MaNGOS. The problem is that there are often changes involving **both** the C++ and the DB, that's also why TrinityCore/CMaNGOS went for the monorepo approach, which we inherited.

Currently only the table `broadcast_text_locale.sql` exceeds the limit of 72mb, being it 76mb.

**Comment by Hacaw** [comment]
My proposal for this issue is to make the localization as a module and support in the core only the English version.

**Comment by LukasVolgger** [comment]
I'm not happy with this @Hacaw and i think others will agree with me. Also i use deDE Client and the Blizzlike Core should work with different languages so there should be no mod with localisation tables.

**Comment by FrancescoBorzi** [comment]
> My proposal for this issue is to make the localization as a module and support in the core only the English version.

Usually, I'd say the more things can go into modules the better. But in this case, I agree with @LukasVolgger as a server should support any language. You can have different clients with different localisations connecting together.

**Comment by Kitzunu** [comment]
Will close, not really an issue
