### ISSUE TITLE
[Collaborative] List all the important patrolling creatures

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2586]
#### SMALL DESCRIPTION: 

Please, everybody with WOW knowledge contribute to this list of creatures that must patrol constantly.

#### EXPECTED BLIZZLIKE BEHAVIOUR:

Some important creatures should patrol all the time, even if no player is near them. They must have a unique role like being a vendor, a quest giver, a quest creature to kill/talk to or a world boss.

#### THE LIST

**Any staff member can edit this list to update it**

**Template:**
```
- [ ] Creature name - creature_template ID - Extra information
```

###### Important creatures 

- [ ] Lethlas - 39394 - https://wow.gamepedia.com/Lethlas 
- [ ] Somnus - 12900 - https://wow.gamepedia.com/Somnus
- [ ] Axtroz - 12899 - https://wow.gamepedia.com/Axtroz
- [ ] Scryer - 10664 - https://wow.gamepedia.com/Scryer
- [ ] Chronalis
- [ ] The alliance outrunners - https://wow.gamepedia.com/Alliance_Outrunners
- [ ] There is an equivalent of 3 horde mobs in Loch Modan or something like that, can't find their name
- [ ] Crimson Courrier - 12337 - https://wow.gamepedia.com/Crimson_Courier
- [ ] Goblin caravan https://classic.wowhead.com/npc=11626/rigger-gizelton

###### Less important creatures

Creatures that are low level, or not very important.

- [ ] The goblin vendor going from the barrens to ratchet (can't find the name)
- [ ] Maybe old Rexxar creature_template if still in DB, for those who want to reenable it (lol)

**Comment by Stoabrogga** [comment]
Perhaps add the Crimson Courier in Eastern Plaguelands:
https://wow.gamepedia.com/Crimson_Courier

**Comment by BarbzYHOOL** [comment]
Added it, anybody from staff can edit the issue though.

Also I think there is another patrol like that in eastern plaguelands, but it only pops up on a quest,  but it should not stop moving when player is out of sight.

**Comment by Stoabrogga** [comment]
I think it's the same:
https://wow.gamepedia.com/The_Crimson_Courier_(original)

**Comment by BarbzYHOOL** [comment]
No, I really think there was another, but maybe a group with no boss inside, but can't be sure.

There is also a big worm in the zone https://classic.wowhead.com/npc=11896/borelgore dunno if we add it (probably?)

**Comment by Stoabrogga** [comment]
No, Borelgore was great when it was still elite, now it's just another mob.

**Comment by BarbzYHOOL** [comment]
> No, Borelgore was great when it was still elite, now it's just another mob.

:rofl: didn't know

**Comment by Stoabrogga** [comment]
But we could set Borelgore to "large" in order to enable seeing it from far away (appropriate for such a large creature).

**Comment by Kitzunu** [comment]
Better to create one issue per creature
