### ISSUE TITLE
Deadmines aggro too big?

### ISSUE THREAD

**Issue by Selyria** [azerothcore/azerothcore-wotlk#2588]
SMALL DESCRIPTION:

Somehow the aggro here is too big it should only be the two mobs below + the boss,
not half the boat

EXPECTED BLIZZLIKE BEHAVIOR:

Normally the 2 mobs come in shadow form and the boss

CURRENT BEHAVIOUR:

There are too many mobs when you pull the two mobs down

Video https://youtu.be/p4TyiYzO39k

BRANCH(ES):

AzerothCore rev. 70170f0bbd76+ 2020-01-16 08:24:10 +0100 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES:
Transmog
Worldchat

**Comment by solidmaxtor** [comment]
Don Mamporro =P  i love this fight event. 
I know exactly if adds namber is good, but this no problem for players, kill adds before Mamporro.
Noob players only hit mamporro, he (2 or 3 times) stun all players for 10 sec when he go change weapons and back.
If not kill adds they kill player in stun phase.

**Comment by Ashland** [comment]
@solidmaxtor Is he meant to pull the adds off the boat behind him ? Not the boss adds he spawns which should be focused first (adds over boss) 
@Selyria You can adjust agro range in worldserver.conf see if that helps and the call for help range

**Comment by Selyria** [comment]
I have the Config on standard so everything should fit but it is somehow extremely high now.

When I play with the settings this applies to the whole server which would not be in my sense.

**Comment by Ashland** [comment]
Yeah aggro at default seems really off , lots of players complained about it so I reduced it too 40 yards and call for help to 15 seems to be much better that’s why I say set the worldserver.conf radius to 40 and call for help to half what it is so it’s playable in the mean time , cause the issue might take a while to get fixed that’s all

**Comment by Selyria** [comment]
Which values do I have to change exactly in the Config

**Comment by Ashland** [comment]
Go to CREATURE SETTINGS. Then the first option is threat radius default set to 60 change to 40 and the second option just under that is , call for help , default 30 change to 15 this is not a proper fix for the los but it makes it way more playable

**Comment by Branel** [comment]
@FrancescoBorzi @Kitzunu can we add some tags to this so that someone might look into it at some point.

**Comment by Si1ker** [comment]
I have done some runs on Deadmines, no error found, at some point, it got fixed.

**Comment by T1ti** [comment]
> I have done some runs on Deadmines, no error was found, it just pulled the two mobs at the beginning of the bridge.
> At some point, it got fixed.

yeah aggro radius was recently fixed
