### ISSUE TITLE
SQL Pet Aura error [$15]

### ISSUE THREAD

**Issue by Ashland** [azerothcore/azerothcore-wotlk#2589]
sql error logs for Insert Pet Aura

```
2020-01-18 04:18:54 SQL(p): INSERT INTO pet_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges) VALUES (13, 17379391235810214797, 21787, 1, 1, 1, 46, 0, 0, 2, 0, 0, 120000, 91750, 0)
 [ERROR]: [1062] Duplicate entry '13-21787-1' for key 'PRIMARY'
2020-01-18 04:18:54 [Warning] Transaction aborted. 5 queries not executed.
2020-01-18 05:56:15 SQL(p): INSERT INTO pet_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount1, base_amount2, maxDuration, remainTime, remainCharges) VALUES (13, 17379391235810214869, 21787, 1, 1, 1, 46, 0, 0, 2, 0, 0, 120000, 98564, 0)
 [ERROR]: [1062] Duplicate entry '13-21787-1' for key 'PRIMARY'
2020-01-18 05:56:15 [Warning] Transaction aborted. 4 queries not executed.

```

##### EXPECTED BLIZZLIKE BEHAVIOUR:
no error

##### CURRENT BEHAVIOUR:
error

##### STEPS TO REPRODUCE THE PROBLEM:
not actually sure

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
AzerothCore rev. 70170f0bbd76 2020-01-16 08:24:10 +0100 (master branch)

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
CFBG
Chat
Dynamic XP

##### OTHER CUSTOMIZATIONS:
none

**Comment by Bogir** [comment]
confirm
https://github.com/azerothcore/azerothcore-wotlk/issues/2498

**Comment by Ashland** [comment]
@Bogir sorry I didn’t see your issue I looked for an issue already and didn’t see yours

**Comment by solidmaxtor** [comment]
I see this error all time in log worldserver, but no have payers report for error or problems.
Error in log exist for me same, i confirm.

**Comment by Stoabrogga** [comment]
The spell seems to be related to these creatures:
- Gretheer (uses 21787 directly through SAI)
- Nerubis Centurion (uses 21787 directly through SAI)
- Thessala Hydra (21787 triggered by aura 21788)

**Comment by Bogir** [comment]
Still something weird with assigning a value in a key field
![изображение](https://user-images.githubusercontent.com/25766571/74854746-cbce3780-5350-11ea-9ffa-19ec50595b04.png)

**Comment by Kitzunu** [comment]
How do to reproduce it?

**Comment by Bogir** [comment]
> 
> 
> How do to reproduce it?

perhaps it happens then pet get buffs what must be stored to DB
I am using npc_buffer and pet have 6 buffs when this error happened

**Comment by BarbzYHOOL** [comment]
I also have this error (everybody has it)

```sql
SQL(p): INSERT INTO pet_aura (guid, casterGuid, spell, effectMask, recalculateMask, stackCount, amount0, amount1, amount2, base_amount0, base_amount
1, base_amount2, maxDuration, remainTime, remainCharges) VALUES (775, 17379391158936972621, 5416, 1, 1, 1, 15, 0, 0, 1, 0, 0, 45000, 26143, 0)
 [ERROR]: [1062] Duplicate entry '775-5416-1' for key 'PRIMARY'                                                                                     [Warning] Transaction aborted. 7 queries not executed. 
```

Maybe related but no solution linked :( https://github.com/TrinityCore/TrinityCore/issues/1464

**Comment by BarbzYHOOL** [comment]
So this insert only happens in the function:
```cpp
void Pet::_SaveAuras(SQLTransaction& trans, bool logout)
```
which is only called (unless i made a mistake) in the same file, aka Pet.cpp, in the function:
```cpp
void Pet::SavePetToDB(PetSaveMode mode, bool logout)
```

Here are where this function is called:
```
server/game/Spells/SpellEffects.cpp:3124:        pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/game/Spells/SpellEffects.cpp:3239:    pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/game/Spells/SpellEffects.cpp:5242:    pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/game/Spells/SpellEffects.cpp:5845:        pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/game/Entities/Player/Player.cpp:19729:        pet->SavePetToDB(PET_SAVE_AS_CURRENT, logout);
server/game/Entities/Player/Player.cpp:20842:    pet->SavePetToDB(mode, true);
server/game/Entities/Pet/Pet.h:69:        void SavePetToDB(PetSaveMode mode, bool logout);
server/game/Entities/Pet/Pet.cpp:206:void Pet::SavePetToDB(PetSaveMode mode, bool logout)
server/game/Entities/Pet/Pet.cpp:2103:            SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/game/Entities/Pet/Pet.cpp:2227:            pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/game/Entities/Pet/Pet.cpp:2289:            pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/scripts/Commands/cs_npc.cpp:1407:        pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
server/scripts/Commands/cs_misc.cpp:2902:        pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
```
From this, we can try to reproduce the issue

**Comment by BarbzYHOOL** [comment]
What i can see is that each time, it's related to a nature POISON SPELL cast by an enemy onto your pet.
21787
5416
35201

So I can't reproduce it but I think if you are a hunter, you go fight one of these mobs https://db.frostgram.eu/?spell=5416#used-by-npc and then your pet keeps getting poisoned and at some point it should error

**Comment by FrancescoBorzi** [comment]
I can confirm this is still an issue on https://github.com/chromiecraft/azerothcore-wotlk/commit/51342ef9b5008ac9fd4cbd0710c9cc924a35aad6

**Comment by Bogir** [comment]
UltraNix thanks!
