### ISSUE TITLE
[Quest] Convocation at Zol'Heb (Part 2 of 2)

### ISSUE THREAD

**Issue by Deteroch** [azerothcore/azerothcore-wotlk#259]
**Description**: The quest is descrived here-->http://www.wowhead.com/quest=12730/convocation-at-zolheb.

**Current behaviour**: When the player reaches the summoning circle and tries to use the quest item appears the message: you can't do that yet. 
![wowscrnshot_112616_164143](https://cloud.githubusercontent.com/assets/22517711/20641403/479c87c4-b3f7-11e6-9e2f-d52b0887e32a.jpg)

**Expected behaviour**: after the player has used the item should start the ritual to summon Akali and then kill him

**Steps to reproduce the problem**:

1. Go to summoning circle in Zol'Heb temple
2. Use the quest item 
3. 

**Branch(es)**: master 

**AC hash/commit**:  

**Operating system**: 

 **Modules**:  Duel Reset

**Other Customizations**: Crossfaction

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Chinoske** [comment]
Fix SQL for [Quest] Convocation at Zol'Heb

[Convocation at Zol'Heb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/614388/Convocation.at.Zol.Heb.txt)

**Comment by sucofog** [comment]
@Chinoske 

Thanks but SQL is not updated to Azerothcore tables, also the:

SmartAIMgr::LoadSmartAIFromDB: GameObject entry (300221) does not exist, skipped loading.
SmartAIMgr::LoadSmartAIFromDB: GameObject entry (300221) does not exist, skipped loading.

Gameobject_template 300221 not implemented.

**Comment by sucofog** [comment]
Gameobject_template ID 300221 should be 191124 which is the current ID.

**Comment by sucofog** [comment]
Also WHY DELETE creature_text entry's when they are handled by database already, and BroadcastTextID is not supported?

**Comment by sucofog** [comment]
[Convocation at Zol'Heb_FIXED.txt](https://github.com/azerothcore/azerothcore-wotlk/files/614430/Convocation.at.Zol.Heb_FIXED.txt)

**Comment by Chinoske** [comment]
its works for me in azerothcore

**Comment by sucofog** [comment]
Imposible @Chinoske
