### ISSUE TITLE
mmaps_generator compile failed

### ISSUE THREAD

**Issue by LichKing255** [azerothcore/azerothcore-wotlk#2590]
##### SMALL DESCRIPTION:
Cannot compile mmaps_generator on VS 2019 16.3.10

> 1>------ Build started: Project: revision.h, Configuration: RelWithDebInfo x64 ------
> 2>------ Build started: Project: mmaps_generator, Configuration: RelWithDebInfo x64 ------
> 2>TerrainBuilder.cpp
> 2>VMapExtensions.cpp
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(52,32): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(53): message : see reference to class template instantiation 'std::_Safe_add<_Ax,_Bx>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(25,39): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(111): message : see reference to class template instantiation 'std::_Ratio_add<_R1,_R2>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(78,20): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(135): message : see reference to class template instantiation 'std::ratio<100,1>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621): message : see reference to class template instantiation 'std::_Ratio_multiply<std::ratio<100,1>,std::nano>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621): message : see reference to alias template instantiation 'std::ratio_multiply<std::ratio<100,1>,std::nano>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(79,20): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(149,19): error C2338: integer arithmetic overflow (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621): message : see reference to class template instantiation 'std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(160,74): error C2794: 'type': is not a member of any direct or indirect base class of 'std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621,76): error C2938: 'std::ratio_multiply' : Failed to specialize alias template (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(172,47): error C3203: 'duration': unspecialized class template can't be used as a template argument for template parameter '_Duration', expected a real type (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(177,1): error C2825: '_Duration': must be a class or namespace when followed by '::' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(627): message : see reference to class template instantiation 'std::chrono::time_point<std::chrono::system_clock,int>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(177,46): error C2510: '_Duration': left of '::' must be a class/struct/union (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(177,1): error C2061: syntax error: identifier 'rep' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(178,1): error C2825: '_Duration': must be a class or namespace when followed by '::' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(178,46): error C2510: '_Duration': left of '::' must be a class/struct/union (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(178,1): error C2061: syntax error: identifier 'period' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(180,1): error C2338: duration must be an instance of std::duration (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,39): error C2641: cannot deduce template arguments for 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2783: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const _Rep2 &) noexcept(<expr>)': could not deduce template argument for '_Rep' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(76): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2440: '<function-style-cast>': cannot convert from '__int64' to 'std::chrono::system_clock::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194,65): error C2065: 'rep': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194,65): error C2923: 'std::is_arithmetic_v': 'rep' is not a valid template type argument for parameter '_Ty' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194): error C2144: syntax error: 'unknown-type' should be preceded by ')' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194,1): error C2057: expected constant expression (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,39): error C2641: cannot deduce template arguments for 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2783: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const _Rep2 &) noexcept(<expr>)': could not deduce template argument for '_Rep' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(76): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2440: '<function-style-cast>': cannot convert from '__int64' to 'std::chrono::system_clock::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\VMapExtensions.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(52,32): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(53): message : see reference to class template instantiation 'std::_Safe_add<_Ax,_Bx>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(25,39): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(111): message : see reference to class template instantiation 'std::_Ratio_add<_R1,_R2>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(78,20): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(135): message : see reference to class template instantiation 'std::ratio<100,1>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621): message : see reference to class template instantiation 'std::_Ratio_multiply<std::ratio<100,1>,std::nano>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621): message : see reference to alias template instantiation 'std::ratio_multiply<std::ratio<100,1>,std::nano>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(79,20): error C2065: 'INTMAX_MAX': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(149,19): error C2338: integer arithmetic overflow (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621): message : see reference to class template instantiation 'std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\ratio(160,74): error C2794: 'type': is not a member of any direct or indirect base class of 'std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(621,76): error C2938: 'std::ratio_multiply' : Failed to specialize alias template (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(172,47): error C3203: 'duration': unspecialized class template can't be used as a template argument for template parameter '_Duration', expected a real type (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(177,1): error C2825: '_Duration': must be a class or namespace when followed by '::' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(627): message : see reference to class template instantiation 'std::chrono::time_point<std::chrono::system_clock,int>' being compiled (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(177,46): error C2510: '_Duration': left of '::' must be a class/struct/union (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(177,1): error C2061: syntax error: identifier 'rep' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(178,1): error C2825: '_Duration': must be a class or namespace when followed by '::' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(178,46): error C2510: '_Duration': left of '::' must be a class/struct/union (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(178,1): error C2061: syntax error: identifier 'period' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(180,1): error C2338: duration must be an instance of std::duration (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,39): error C2641: cannot deduce template arguments for 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2783: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const _Rep2 &) noexcept(<expr>)': could not deduce template argument for '_Rep' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(76): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): error C2440: '<function-style-cast>': cannot convert from '__int64' to 'std::chrono::system_clock::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(628,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194,65): error C2065: 'rep': undeclared identifier (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194,65): error C2923: 'std::is_arithmetic_v': 'rep' is not a valid template type argument for parameter '_Ty' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194): error C2144: syntax error: 'unknown-type' should be preceded by ')' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(194,1): error C2057: expected constant expression (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,39): error C2641: cannot deduce template arguments for 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2783: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const _Rep2 &) noexcept(<expr>)': could not deduce template argument for '_Rep' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(76): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2784: 'std::chrono::duration<_Rep,_Period> std::chrono::duration(const std::chrono::duration<_Rep2,_Period2> &) noexcept(<expr>)': could not deduce template argument for 'const std::chrono::duration<_Rep2,_Period2> &' from '__int64' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(84): message : see declaration of 'std::chrono::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): error C2440: '<function-style-cast>': cannot convert from '__int64' to 'std::chrono::system_clock::duration' (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\include\chrono(636,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous (compiling source file F:\Git\azerothcore\src\tools\mmaps_generator\TerrainBuilder.cpp)
> 2>Done building project "mmaps_generator.vcxproj" -- FAILED.
> ========== Build: 1 succeeded, 1 failed, 20 up-to-date, 0 skipped ==========

`

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/70170f0bbd767c7d4656b9a3e33b7e21429f00ab

##### OPERATING SYSTEM:
Windows 10 Enterprise 1909

**Comment by solidmaxtor** [comment]
Run fine for me in linux - ubuntu 18 (core 12 days ago)
rev. cf33698040e6+ 2020-01-05 21:06:41 +0100 (master branch)

**Comment by Viste** [comment]
plz put log to paste or haste

**Comment by LichKing255** [comment]
> plz put log to paste or haste

https://hastebin.com/jolalohuqa.shell

**Comment by gengarshadowball** [comment]
Can you try to update your fork and re-compile?

**Comment by Viste** [comment]
@LichKing255 update your for its error fixed about month ago )

**Comment by Helias** [comment]
@Viste are you sure? can we close this issue?

**Comment by Viste** [comment]
yes this commit( https://github.com/azerothcore/azerothcore-wotlk/commit/435190979eee00e6e227a387021daeb4a36a81ab ) must fix this

**Comment by LichKing255** [comment]
> yes this commit( [4351909](https://github.com/azerothcore/azerothcore-wotlk/commit/435190979eee00e6e227a387021daeb4a36a81ab) ) must fix this

no , it's not work for me , i have this commit .

**Comment by dunjeon** [comment]
No build errors on Windows 10

**Comment by Viste** [comment]
@dunjeon Never mind he use own fork not official AC its his problem. He even don't say PCH or non-PCH build he used :)
