### ISSUE TITLE
db_assembler should find SQL automatically in modules

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2592]
Same idea as https://github.com/azerothcore/azerothcore-wotlk/issues/2571

The db_assembler.sh should not require a file `include.sh` in **modules** which itself requires a  `conf/config.sh.dist`, it should automatically check for SQL files in `sql/` if that directory exists following this directory structure https://github.com/azerothcore/skeleton-module/tree/master/sql

That way, developers will waste less time on updating these small files, and when we change something we don't have to update all the 80+ modules... Also it normalizes the modules structure which is very needed to avoid wasting people's time and to avoid inconsistency

**Comment by Kitzunu** [comment]
Not supported anymore
