### ISSUE TITLE
Isle of Conquest Scoreboard Error

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2593]
##### SMALL DESCRIPTION:

Joined BG Isle of Conquest with one pleayer each faction, 2 Horde are shown. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Scoreboard should work like all other scorebnoards and show the players each faction correctly. 
Example: 

![image](https://user-images.githubusercontent.com/55922592/72669739-da65be00-3a35-11ea-84bd-f785d08d8831.png)

##### CURRENT BEHAVIOUR:

The error appears only on Random Queue, not Specific Queue! 

**Scoreboard from Random Queue:** 

![image](https://user-images.githubusercontent.com/55922592/72669672-37ad3f80-3a35-11ea-89e9-9a2b0b7dc876.png)

**Scoreboard from Specific Queue:**

![image](https://user-images.githubusercontent.com/55922592/72669698-7e9b3500-3a35-11ea-9421-df45c0f19179.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. create 1 H/A char on different accounts
2. .debug bg
3. Join via Random Queue the BG Isle of Conquest and open Scoreboard

> You can remove the "Deserteur" aura with .unaura 26013 

##### EXTRA NOTES:

[Server.log](https://github.com/azerothcore/azerothcore-wotlk/files/4081695/Server.log)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

bb42c7c5eb03+

##### OPERATING SYSTEM:

Windows 10 pro 64 bit

##### MODULES:

- Auctionhouse Bot
- SoloLFG
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max skill on levelup

**Comment by diluh** [comment]
I confirm

**Comment by Viste** [comment]
try https://github.com/Viste/az-core/commit/46b5edebf4471ece1b86dde0d68c91060ae2c24a
