### ISSUE TITLE
ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS is not handled by the core

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#260]
**Description**:

This config is read but never used since pussywizard disabled it

https://github.com/azerothcore/azerothcore-wotlk/blob/81b195099be42dcaab50d54ef5212fa40b5ab522/src/game/World/World.cpp#L1058

**Current behaviour**: 

You cannot change the AP distribution interval

**Expected behaviour**: 

You should be able to change the interval

**Branch(es)**: all branches

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/81b195099be42dcaab50d54ef5212fa40b5ab522

**Operating system**:  Ubuntu linux

**Modules**:  No

**Other Customizations**: No

**Comment by sucofog** [comment]
Pussywizard disabled a lot of good things for no reason like this, .save command, bg announce player self, and many other things dont know why
