### ISSUE TITLE
Command .mailbox doesn't refresh the mailbox content

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2601]
##### SMALL DESCRIPTION:

Command .mailbox doesn't refresh the mailbox content

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If you open the mailbox with the command, it should be EXACTLY like opening it by clicking on a mailbox

##### CURRENT BEHAVIOUR:

If you didn't check your mailbox before, then it will be empty. If you checked it before, it will have what you already saw last time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Type `.mailbox`

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

eadcb1a

**Comment by Zausender** [comment]
Duplicate. Check before posting
https://github.com/azerothcore/azerothcore-wotlk/issues/1883
