### ISSUE TITLE
[DK Starting Area] Stable Master Kitrik has no path.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#2610]
[DK-Quest #12680] - Grand Theft Palomino

SMALL DESCRIPTION:

* NPC "Stable Master Kitrik" (id=28683) does not perform his usual round and does not move from his spawn point.

EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.youtube.com/watch?v=xq23deehfKU

https://www.wowhead.com/quest=12680/grand-theft-palomino
https://wowgaming.altervista.org/aowow/?quest=12680

BRANCH(ES):
master

AC HASH/COMMIT:
9f690a3

OPERATING SYSTEM:
Ubuntu 18.04

MODULES:
mod_eluna
mod_transmo

OTHER CUSTOMIZATIONS:
No custom

**Comment by Kitzunu** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d5f565f42992d5142b30c7fbd694f8a5b1245f4c

**Comment by aradep** [comment]
Confirmed on 2a17125.

**Comment by Rorschach91** [comment]
Issue has not been fixed yet.
