### ISSUE TITLE
[DK-Quest #12687] - Into the Realm of Shadows

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#2611]
[DK-Quest #12687] - Into the Realm of Shadows

SMALL DESCRIPTION:
*There's an unmounted horse in the area, making the quest feasible without facing a rider.
*The NPCs "Black Rider of Acherus" (id=28768) ride an elite horse that is aggressive towards the player and makes the fight unwinnable for the player.

EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.youtube.com/watch?v=ha_A2b79lTU

https://www.wowhead.com/quest=12687/into-the-realm-of-shadows
https://wowgaming.altervista.org/aowow/?quest=12687

BRANCH(ES):
master

AC HASH/COMMIT:
9f690a3

OPERATING SYSTEM:
Ubuntu 18.04

MODULES:
mod_eluna
mod_transmo

OTHER CUSTOMIZATIONS:
No custom

**Comment by aradep** [comment]
>There's an unmounted horse in the area, making the quest feasible without facing a rider.

Unable to reproduce on 2a17125

___

> The NPCs "Black Rider of Acherus" (id=28768) ride an elite horse that is aggressive towards the player

Seems to be blizzlike https://youtu.be/tVjXhFmzeho?t=142
___
> ...and makes the fight unwinnable for the player.

Confirmed. The damage is a bit high compared to videos of retail, but not unwinnable.

**Comment by Rorschach91** [comment]
> *There's an unmounted horse in the area, making the quest feasible without facing a rider.

The unmounted horse is not present anymore.

> *The NPCs "Black Rider of Acherus" (id=28768) ride an elite horse that is aggressive towards the player and makes the fight unwinnable for the player.

This issue is still present, in fact I have reported it: https://github.com/azerothcore/azerothcore-wotlk/issues/20107
There is a PR "Ready to be Reviewed" which should solve the problem.
