### ISSUE TITLE
[DK-Quest #12725] - Brothers In Death

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#2613]
[DK-Quest #12725] - Brothers In Death

SMALL DESCRIPTION:
*When you accept the quest, the dialogue between NPCs "Orbaz Bloodbane" (id=28914) and "Thassarian" (id=28913) does not start.
*NPC "Koltira Deathweaver" (id=28912) is not in the location, he attacks NPCs in the fort and it is not possible to talk to him to continue the quest, killing the NPCs that attack him makes him disappear, he then respawn in the location.

EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.youtube.com/watch?v=Qk3HRbg5CGo

https://www.wowhead.com/quest=12725/brothers-in-death
https://wowgaming.altervista.org/aowow/?quest=12725

BRANCH(ES):
master

AC HASH/COMMIT:
9f690a3

OPERATING SYSTEM:
Ubuntu 18.04

MODULES:
mod_eluna
mod_transmo

OTHER CUSTOMIZATIONS:
No custom

**Comment by zqgmzq** [comment]
on the latest build
i have the same issue

**Comment by FrancescoBorzi** [comment]
can anyone reproduce this on latest master?

**Comment by aradep** [comment]
Unable to reproduce on 2a17125.  #2788 did indeed fix it.
