### ISSUE TITLE
ARAC

### ISSUE THREAD

**Issue by darkmoi31** [azerothcore/azerothcore-wotlk#2616]
##### SMALL DESCRIPTION:

Hello,
I am contacting you because I am looking for an All Race All Class sql patch.
Can you help me please ?
thanks

EXTRA NOTES:
BRANCH(ES):

##### BRANCH(ES): 

master

##### AC HASH/COMMIT:

b66ec5712ed27f165b8f79b5b50203590698cb8c

##### OPERATING SYSTEM:
Debian 9

**Comment by wlasser** [comment]
as i remember - you must hack something in code and make few changes in ChrRaces.dbc - the second is not supported by devs.

**Comment by darkmoi31** [comment]
My dbc is ready for this but not my playercreateinfo tables... i have trouble with playercreateinfo_spell ans playercreateinfo_option...

**Comment by Helias** [comment]
I tried a sql patch taken from ac-web once, I will try it again and let you know soon

**Comment by darkmoi31** [comment]
my problem is mainly with the table: playercreateinfo_spell, on azerothcore the columns are racemask and classmask, on trinity it's playercreateinfo_skills and they don't use masks but just the ids of the races / classes. I don't know how to convert them. I managed to convert these tables:

-playercreateinfo_action
-player_levelstats
-player_classlevelstats
-player_factionchange_achievement

I therefore miss the following tables:

-playercreateinfo_item
-playercreateinfo_spell
-player_factionchange_items
-player_factionchange_quests
-player_factionchange_reputations
-player_factionchange_spells
-player_factionchange_titles

if you can help me, it would be very nice.

**Comment by Helias** [comment]
try this one https://mega.nz/#!RkYFha7D!FHkncE8AfFlOiti-mgLpErFqO4EZQgO4E5MFYluVnTM

**Comment by darkmoi31** [comment]
hi, 
this not work...

screen : https://image.noelshack.com/fichiers/2020/04/5/1579892289-screen.jpg

**Comment by iThorgrim-hub** [comment]
I've updated all the sql and I've restructured it as well ^^
Everything works perfectly :D

![image](https://user-images.githubusercontent.com/58987080/73135976-00e4b400-4049-11ea-9cf9-d4d04e831ccf.png)

![image](https://user-images.githubusercontent.com/58987080/73135978-03470e00-4049-11ea-8798-83998a443286.png)


[ARAC_AzerothCore.zip](https://github.com/azerothcore/azerothcore-wotlk/files/4113503/ARAC_AzerothCore.zip)

**Comment by darkmoi31** [comment]
omg thanks you !!!
