### ISSUE TITLE
DB/Warden: Hacks not detected

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#262]
These two hacks are not detected by warden:

https://mega.nz/#!BcwDxTII!DDjcb8zvJzadv5_6RFxpabs3f5QZW0ruGQSdWYpG2Sk

https://mega.nz/#!KNdBQB4T!JYu5HH1Ellt9EtTvskhujJEMSeWwuYKFoUkh7EzI8gw

If someone could make the warden detect them.

Thanks !

**Comment by falzard** [comment]
Which hacks are they? I'm on linux, I suppose it's some windows program.

Is it teleport hack and fly hack?

**Comment by Dragnell87** [comment]
Pretty sure warden does not detect many of these [hack ](http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-programs/531659-wow-admin-panel-2-0-7-all-private-servers-patches.html), including fly and teleport.

**Comment by falzard** [comment]
@3ndos worked on this https://github.com/3ndos/AnticheatModule but it can be greatly improved

**Comment by Sworken** [comment]
I am using the module now and it is better than before;)

**Comment by falzard** [comment]
Why closed? there is no issue opened about cheats while it's a big concern that is not resolved :(

**Comment by Kitzunu** [comment]
Is this still valid??

**Comment by Dragnell87** [comment]
Probably yes.

**Comment by Dragnell87** [comment]
> Is this still valid??

Probably yes.

**Comment by BarbzYHOOL** [comment]
yeah but we can't fix it with warden i think

**Comment by Kitzunu** [comment]
I am going to close this as we had no reports or activity in this post about this topic since 2016.

If anyone has this issue in the future, please open a new report.
