### ISSUE TITLE
Quest items not being removed from inventory upon completion of quest

### ISSUE THREAD

**Issue by jwh1981** [azerothcore/azerothcore-wotlk#2620]
##### SMALL DESCRIPTION:
Quest items are not removed after completing a quest (at least in the human starting zone)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When completing Millie's harvest (human), the grapes should be removed.

##### CURRENT BEHAVIOUR:
The current behavior is that any quest items are not removed from inventory upon completing a quest. For instance, diseased wolf hides are not removed when completing Wolves Across the Border (given by Eagan Peltskinner) nor are the grapes removed when completing Millie's Harvest quest.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Accept Millie's Harvest quest in human starting zone (Northshire)
2. Retrieve grape harvest
3. Turn in quest to Millie
4. Grapes remain inventory (clearing showing as being quest items and not normal items)

##### EXTRA NOTES:
This is running on a Windows 8.1 x64 Pro desktop with MySQL 5.7 and compiled with Visual Studio 2017 community (as x64) and release (not debug)

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
999d588c37ef0e56d9043f1aa33ad5e9796f74ca

##### OPERATING SYSTEM:
Windows 8.1 x64 Pro with all updates

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Ashland** [comment]
Can confirm on latest commit , quest items not deleting

**Comment by FrancescoBorzi** [comment]
@Kaev

**Comment by Kaev** [comment]
My bad, had a brainfart in the following PR: https://github.com/azerothcore/azerothcore-wotlk/pull/2617
This will be fixed with: https://github.com/azerothcore/azerothcore-wotlk/pull/2626

**Comment by FrancescoBorzi** [comment]
thanks @Kaev for quickly fixing this!
