### ISSUE TITLE
Possible bug in guardian combat system

### ISSUE THREAD

**Issue by Kaev** [azerothcore/azerothcore-wotlk#2624]
##### SMALL DESCRIPTION:
There might be a bug in the combat system of guardians, see extra notes.

##### EXTRA NOTES:
StatSystem.cpp line 1236
At the top there is this expression: if (attType > BASE_ATTACK) return;
We should recheck if the > was put there accidently.
If this is no accident, we can remove code in line 1264 because it never gets reached (which is how i found this)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

35b6bed

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

None

**Comment by Viste** [comment]
i thniks its something from old mangos days... https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/StatSystem.cpp#L1439
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Entities/StatSystem.cpp#L900
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Entities/StatSystem.cpp#L1144
