### ISSUE TITLE
Arena 3v3/5v5 token reward

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#2625]
Author: @IntelligentQuantum 
Unfortunately, in IRAN the people can't access Github (and internet) easily, so I am posting this issue for the reporter.

##### SMALL DESCRIPTION:
> When I join 3v3 arena it doesn't give me 3v3 token instead it gives me 2v2 token
> 2v2 token = 1000000
> 3v3 token = 1000001

Responsible piece of code of this:
https://github.com/IntelligentQuantum/AzerothCore/blob/master/modules/IntelligentQuantum/BGScripts/BattlegroundsReward.cpp#L52

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Get 3v3 token after a game.

##### CURRENT BEHAVIOUR:
After a 3v3-arena the players receive 2v2 token instead of 3v3.

##### STEPS TO REPRODUCE THE PROBLEM:
- join arena 3v3 in team
- win the arena
- check the reward token

Note: be sure to have `Arena.Reward.Enable` config enable in worldserver.conf.

**Comment by MakUCI** [comment]
reading the code reward is item 29434 for 2v2,3v3,5v5

line 61 and 64 maybe wrong about item reward code.

PD: this is a module, maybe you should write issue to the author

**Comment by Kaev** [comment]
> 
> 
> reading the code reward is item 29434 for 2v2,3v3,5v5
> 
> line 61 and 64 maybe wrong about item reward code.
> 
> PD: this is a module, maybe you should write issue to the author

29434 is the default value. You get that item on every queue, if you don't have Arena.Reward.Enable configured. Are we sure that the reporter has configured the correct item IDs?

**Comment by Bogir** [comment]
> Are we sure that the reporter has configured the correct item IDs?

Do you see at least one config in his repository?

**Comment by Helias** [comment]
Some config was wrong in his local server

**Comment by Mamaro89** [comment]
Why i cannot find this option on my worldserver.conf?  Is it a Module?
