### ISSUE TITLE
Fail with request sql

### ISSUE THREAD

**Issue by darkmoi31** [azerothcore/azerothcore-wotlk#2627]
##### SMALL DESCRIPTION:

i have make this request : UPDATE item_template SET RequiredReputationFaction = 1161, RequiredReputationRank = 7 IN (entry = 34989, 34996, 34997, 35014, 35015);
but it's have change all my table, what is wrong on my request please ...

##### EXPECTED BLIZZLIKE BEHAVIOUR:

it should have just changed the entries I put in the request

##### BRANCH(ES):

master

##### OPERATING SYSTEM:
Debian 9

**Comment by Bogir** [comment]
try to change
WHERE entry IN (34989, 34996, ...

**Comment by darkmoi31** [comment]
ohhh good !!!! thank you verry much !

**Comment by darkmoi31** [comment]
but it's have change 4 not 5 entry why ?

**Comment by Bogir** [comment]
Maybe 35015 does not exists? =)

**Comment by FrancescoBorzi** [comment]
- GitHub should be used for bug reports only
- for support request, StackOverflow should be used instead

> Do you have questions about C++ or SQL code that is related with AzerothCore or other AC custom modules?
this kind of questions are considered support questions, and are handled via StackOverflow. Read below

Please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
