### ISSUE TITLE
Totem Shaman not work

### ISSUE THREAD

**Issue by darkmoi31** [azerothcore/azerothcore-wotlk#2633]
##### SMALL DESCRIPTION:

the totems appear but do nothing

##### STEPS TO REPRODUCE THE PROBLEM:

1. create shaman
2. use totem

##### BRANCH(ES):

master

##### OPERATING SYSTEM:
Debian 9

**Comment by Darkon47** [comment]
I could not reproduce this issue, needs more information, fire resistance, nature resistance, strength of earth, and flametongue totem all work as expected.

**Comment by Rochet2** [comment]
What modules do you use?

**Comment by solidmaxtor** [comment]
Test in:
commit 08796ec (31/01/2020)
commit 9f690a3 (23/01/2020)

No problems, no reports for players for me.

**Comment by Viste** [comment]
all is ok for me on last master

**Comment by Rochet2** [comment]
Possibly related https://github.com/azerothcore/azerothcore-wotlk/pull/2636

**Comment by BarbzYHOOL** [comment]
test this plz @darkmoi31 (I bet you use Eluna cause you're friend with Ithorgrim :P)

**Comment by darkmoi31** [comment]
yes i use eluna, why it's make bug ? test what  ^^"

**Comment by BarbzYHOOL** [comment]
> Possibly related #2636

Click the link !!

**Comment by darkmoi31** [comment]
serveur@debian:~/azerothcore$ git pull origin pull/2636/head
Depuis https://github.com/azerothcore/azerothcore-wotlk
 * branch              refs/pull/2636/head -> FETCH_HEAD
Mise à jour b66ec571..5c8896d6
error: Vos modifications locales aux fichiers suivants seraient écrasées par la fusion :
        src/server/game/Entities/Unit/Unit.cpp
Veuillez valider ou remiser vos modifications avant la fusion.
Abandon

**Comment by darkmoi31** [comment]
i have add mod_spellregulator, i have problem befor add this

**Comment by darkmoi31** [comment]
i go reinstall all my server with new clean core and new clean database ....

**Comment by darkmoi31** [comment]
when compile with eluna i have this error ; 

src/server/game/Spells/Auras/SpellAuraEffects.cpp:6034:28: error: invalid argument type
      'void' to unary expression
        if (c && caster && !sEluna->OnDummyEffect(caster, GetId(), SpellEffIndex(GetEffIndex()), target->ToCreature()))
                         

Why ?

**Comment by Rochet2** [comment]
Latest Eluna requires the change from the pull request that was linked.
https://github.com/azerothcore/azerothcore-wotlk/issues/2633#issuecomment-581190142

**Comment by darkmoi31** [comment]
i have solved, it's my database corrupt.
