### ISSUE TITLE
[Object] Deadmines door lever

### ISSUE THREAD

**Issue by devovh** [azerothcore/azerothcore-wotlk#264]
**Description**:
[Object] Deadmines door lever, first boss door(door open), now use door lever and no open door.
Video: https://youtu.be/xJ5eGddCLI8
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead
Use door leaver and close door. Use 2x door leaver open door.
**Steps to reproduce the problem**:

1. Go Deadmines
2. Go and kill First boss
3. Use door lever object x2

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  
dc8f05ec93e3f69fc0eecda7f4695ffa767bca5c
**Operating system**:  
Linux debian 8
**Modules**:  Are you using modules? if yes, list them
no modules
**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.
no customizations

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by rizlaq** [comment]
i killed that boss today , i did not have this isue

**Comment by devovh** [comment]
look video: https://youtu.be/xJ5eGddCLI8

**Comment by ShinDarth** [comment]
@rizlaq that's why it is better to post the commit hash when confirming issue, can you do it please?

**Comment by devovh** [comment]
https://github.com/devovh/SunwellCore-1/commit/4ffa08e29ae4a4dea200c090a5dcd344ba96d51a

* Fix Deadmines door lever not opening doors. Where is fix ?

**Comment by devovh** [comment]
FIX: src/server/game/AI/SmartScripts/SmartScript.cpp

@@ -630,7 +630,7 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
                  {
                      // Activate
  					// xinef: wtf is this shit?
 -					//(*itr)->ToGameObject()->SetLootState(GO_READY);
 +					(*itr)->ToGameObject()->SetLootState(GO_READY);
  					(*itr)->ToGameObject()->UseDoorOrButton(0, e.action.activateObject.alternative ? true : false, unit);
                      ;//sLog->outDebug(LOG_FILTER_DATABASE_AI, "SmartScript::ProcessAction:: SMART_ACTION_ACTIVATE_GOBJECT. Gameobject %u (entry: %u) activated",
                      //    (*itr)->GetGUIDLow(), (*itr)->GetEntry());

**Comment by devovh** [comment]
`@@ -630,7 +630,7 @@ void SmartScript::ProcessAction(SmartScriptHolder& e, Unit* unit, uint32 var0, u
                  {
                      // Activate
  					// xinef: wtf is this shit?
 -					//(*itr)->ToGameObject()->SetLootState(GO_READY);
 +					(*itr)->ToGameObject()->SetLootState(GO_READY);
  					(*itr)->ToGameObject()->UseDoorOrButton(0, e.action.activateObject.alternative ? true : false, unit);
                      ;//sLog->outDebug(LOG_FILTER_DATABASE_AI, "SmartScript::ProcessAction:: SMART_ACTION_ACTIVATE_GOBJECT. Gameobject %u (entry: %u) activated",
                      //    (*itr)->GetGUIDLow(), (*itr)->GetEntry());`

**Comment by devovh** [comment]
FIX: src/server/game/AI/SmartScripts/SmartScript.cpp

 //(*itr)->ToGameObject()->SetLootState(GO_READY);
+(*itr)->ToGameObject()->SetLootState(GO_READY);

**Comment by devovh** [comment]
Fix: https://github.com/devovh/azerothcore-wotlk/commit/bf9664217f1a36b0e0f4071a94395b50f6921cc5

**Comment by ShinDarth** [comment]
@devovh please [create a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request)

**Comment by devovh** [comment]
How to identify the appropriate commit a pull request ? Because he wants to select me, I can not commit to create a pull request.

**Comment by devovh** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/269
