### ISSUE TITLE
[Instance] Ruby Stratum dark phase

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/azerothcore-wotlk#2647]
##### SMALL DESCRIPTION:
Halion attacks the player instantly after entering the portal

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Halion attacks the player after the player hits the Halion

##### CURRENT BEHAVIOUR:
Halion attacks the player instantly after entering the portal

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go trigger 5869
2. Call Halion (kill other 3 boss)
3. Deal damage before dark phase 
4. Enter to the portal

##### BRANCH(ES):
master

##### OPERATING SYSTEM:
ubuntu 18.04

##### MODULES:
eluna

**Comment by solidmaxtor** [comment]
I thought that was the blizzlike mode.
the offtank must be the first player to enter the "dark phase" for take agroo.

**please correct me if I'm wrong

**Comment by Bogir** [comment]
Usually, on step 4 if the first person who entered to dark phase, was not tank - RL kicked them for such mistake =)
It is not bug, it is normal
