### ISSUE TITLE
Windows 10: Server crash

### ISSUE THREAD

**Issue by gengarshadowball** [azerothcore/azerothcore-wotlk#2649]
Server crash running on debug mode

##### SMALL DESCRIPTION:

When you run the worldserver on debug mode in windows 10 there's a crash involving some object and tempsummon.

##### STEPS TO REPRODUCE THE PROBLEM:

On Windows 10 run the worldserver on debug 

##### EXTRA NOTES:

[Crash file](https://drive.google.com/open?id=1faPJPHdAtPYaqYvNuEh9VnB7z12sQbaK)
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

3f0739f1c9a5+

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

Added 2 more tables:
- characters.premium_character
- auth.premium_account

**Comment by Stoabrogga** [comment]
Sorry, I think this was my fault. I did not check if "owner" is null concerning the PlayerScript hook in TempSummon. Could you please test #2650 and check if the crash still occurs?

**Comment by gengarshadowball** [comment]
Tested and fix working like a charm! Thanks Stoa 🙏
