### ISSUE TITLE
Portal Maligos -> Dalaran bug

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2652]
##### SMALL DESCRIPTION:
This portal summoned after killing Maligos boss
Creature ID 30118 "Portal (Malygos)"
All Players mounted on drakes. They can't interact with portal while mounted. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Players can interact with portal while mounted on drakes

##### CURRENT BEHAVIOUR:

Players must dismount to interact with portal. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go instance Eye of eternity (Nexus zone, upper level)
2. Kill maligos
3. Fly to portal 
4. Click on it - nothing happens while you mounted

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

166967fe8642+

**Comment by solidmaxtor** [comment]
Confirm.
Players need unmount and take portal in the air, if fail the fall is long XD
