### ISSUE TITLE
Quest "A Pawn on the Eternal Board" is buggy and can not be completed

### ISSUE THREAD

**Issue by Endeffect-AT** [azerothcore/azerothcore-wotlk#2656]
##### SMALL DESCRIPTION:

See the screenshots below. Quet can not be finished sometimes.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The battle of the scarabs and the Anubisath Conqueror should look more pleasant, some npc's are missing. The waypoints of the dragons are horrible.

Look this video: **https://www.youtube.com/watch?v=V_wU8PhIIWU**

##### CURRENT BEHAVIOUR:

- Position of the dragons & waypoints

![WoWScrnShot_020820_131555](https://user-images.githubusercontent.com/55922592/74085560-427a5380-4a7a-11ea-9758-1688f76288e1.jpg)

- Some NPCs 15424 Anubisath Conqueror are missing

![WoWScrnShot_020820_135240](https://user-images.githubusercontent.com/55922592/74085581-9d13af80-4a7a-11ea-9b21-6e6dfadebaca.jpg)

- Mouseover gate bug: 

![2020-02-08 13_48_31-Window](https://user-images.githubusercontent.com/55922592/74085537-13fc7880-4a7a-11ea-9c16-022b5e947db3.png)

- I had the problem that with my main non-gm char the quest didn't finished (Tried 3 times). I also tried the same quest using the steps above and it finished as expected. I don't know why but this is strange.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Preparation: .q rem 8305, .q a 8305, .q c 8305
2. .go -8025.437500 1539.031250 2.609403 1
3. Accept the following quest 8519 and look at the event

##### EXTRA NOTES:

Quest id 8519
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

eadbd40d5e82+

##### OPERATING SYSTEM:

Windows 10 pro x64

##### MODULES:

- Auction House Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:

- Max skill on  levelup

**Comment by Stoabrogga** [comment]
There's a very old PR which tried to fix this, but it was never completed: #1493

**Comment by Endeffect-AT** [comment]
Damn didn't noticed the already open issue. Sry

**Comment by Endeffect-AT** [comment]
Integrated in #543 & close this.
