### ISSUE TITLE
Server became unstable 

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2657]
Server became unstable after applying updates #2618, #2622, #2639, #2650
It crashes from time to time without a reason.
Server can work from 1-2 minutes to 2-3 hours

##### BRANCH(ES):

master

##### OPERATING SYSTEM:
Windows 7

**Comment by diluh** [comment]
I confirm - server gets stuck and doesn't fail after

See in the video
[https://streamable.com/qm0f3]

**Comment by BarbzYHOOL** [comment]
does it happen even if you launch the worldserver and do nothing? (no login, no playing)

If so, can you reproduce it at the same time or not?

**Comment by Bogir** [comment]
> 
> 
> does it happen even if you launch the worldserver and do nothing? (no login, no playing)
> 
> If so, can you reproduce it at the same time or not?

For me - ti is so. No matter if there is players or not. Today server crashed in 13 hours

**Comment by pklloveyou** [comment]
I did not use ＃2639，＃2650 and did not crash

**Comment by BarbzYHOOL** [comment]
> > does it happen even if you launch the worldserver and do nothing? (no login, no playing)
> > If so, can you reproduce it at the same time or not?
> 
> For me - ti is so. No matter if there is players or not. Today server crashed in 7 hours
> ![изображение](https://user-images.githubusercontent.com/25766571/74090849-72007e80-4ac1-11ea-921b-dd90531ca5ff.png)

this shows 1 player online, also I have never seen this "X sessions" thing lol

**Comment by diluh** [comment]
I removed the pr #2622 #2639  and apparently is normal

![image](https://user-images.githubusercontent.com/46387591/74093089-fa742480-4aab-11ea-8208-008939bbab27.png)

**Comment by Bogir** [comment]
> I have never seen this

Also, if you noticed,  I removed 
![изображение](https://user-images.githubusercontent.com/25766571/74093160-38d70700-4adf-11ea-8f8c-4ab7b249aef0.png)
if it no more 10 ms.

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2622 is huge, seems more likely to be related

can you retry without this one only?

PS: what are players sessions @Bogir ?

**Comment by Bogir** [comment]
It is how many players loged in and stayin on character choose scren (don't know how to correctly describe it in English)

**Comment by diluh** [comment]
@BarbzYHOOL @Kaev I think it's related to this PR that you mentioned.

**Comment by Bogir** [comment]
@BarbzYHOOL In any case, at this time we have only 1confirmation of server crash. It is very little.
So I start to think that reason is in custom modules, not in the our core

**Comment by BarbzYHOOL** [comment]
- Just revert that big PR and retest
- List your modules, please (but you are not working together on the same server Diluh and Bogir?)

offtopic:
> It is shows how many players loged in and staying on character selecting screen (don't know how to correctly describe it in English)

ok but how can 1 player be connected TWICE on the character selection screen ?? 2 sessions

**Comment by Bogir** [comment]
No, I have mine test server))

Offtopic: 2 players connected to Login server (Auth server: 2 sessions) and 1 of them is staying on character selection screen (AFK-character disconnected from Game server or player still not decide which character hi wants to play)

**Comment by BarbzYHOOL** [comment]
**list your modules guys!**


offtopic: ah ok nice Bogir, I would make the clear distinction personally (authserver/worldserver) but it's cool

**Comment by Bogir** [comment]
mod-autobalance-master
mod-solo-lfg-master
They are combined together to 1 module, and I think the reason is somewhere here. Perhaps I have some conflict with #2622

**Comment by Bogir** [comment]
@BarbzYHOOL Could you add label "Need confirm" for this issue? If nobody confirm it I'll close it soon

**Comment by diluh** [comment]
I don't have any of these modules mentioned, and I confirm this error, don't do the same thing they did with the Pets error, all saying that there was no error and in the end @vhiperdev  showed the faulty commit and it was corrected.

**Comment by Bogir** [comment]
And why the others not confirm this crash? Maybe they have no errors/conflicts and we must test it on a clear cloned core? Simply run clear server and wait =)

**Comment by Bogir** [comment]
So, now I cloned clear core lastest revision, compilled, started server and went to sleep =) 
Tomorrow will se result

**Comment by solidmaxtor** [comment]
i am use commit b1bcd21 (30/01/2020) full modules.
No problems for me, check lasts changes 1-9 feb

**Comment by Viste** [comment]
![image](https://user-images.githubusercontent.com/281977/74099188-f854a900-4b31-11ea-82d9-f3b2f19afc6e.png)

**Comment by BarbzYHOOL** [comment]
> I don't have any of these modules mentioned, and I confirm this error, don't do the same thing they did with the Pets error, all saying that there was no error and in the end @vhiperdev showed the faulty commit and it was corrected.

instead of complaining, you should help finding the bug like vhiper did, it's your role here, not just say "bug plz help slaves"

note: that I talked with vhiper many times during that bug

**Comment by Bogir** [comment]
> 
> I don't have any of these modules mentioned, and I confirm this error, 

![изображение](https://user-images.githubusercontent.com/25766571/74205680-7081b280-4c89-11ea-8ef8-e3e7a97b3612.png)

I had conflict with my customization and pr #2622 and fixed it. 
To find where is your problem you can clone clear core, add 1-2 of your modules or customizations and test how server will be work.
