### ISSUE TITLE
Romantic Picnic Basket disappears ahead of time

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#2658]
##### SMALL DESCRIPTION:

**Romantic Picnic Basket** disappears ahead of time after it was used by owner

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It mustt staying for 3 minutes and everybody can use it too with you for getting an achievenment

##### CURRENT BEHAVIOUR:

After using Romantic Picnic Basket it disappears momentarely

##### STEPS TO REPRODUCE THE PROBLEM:

1. if event "Love is in the Air" not started yet: .event start  8
2. .add 34480
3. use item, then use Basket
4. You can add 34480 to other player, which will use it near you and will use the Bucked. You and him gets love auras, but not achievement.

##### EXTRA NOTES:

![изображение](https://user-images.githubusercontent.com/25766571/74090204-c6076500-4ab9-11ea-8c02-a16506ddb824.png)

##### BRANCH(ES):

master lastest

##### OPERATING SYSTEM:

Win 7

**Comment by Volgger** [comment]
I will try to fix that soon

**Comment by Volgger** [comment]
I found some older TC issues where this is mentioned:

https://github.com/TrinityCore/TrinityCore/issues/5116
https://github.com/TrinityCore/TrinityCore/issues/5257

Seems that we have the same problem and it needs to be scripted. Cannot solve this in that case, sry.

**Comment by Kitzunu** [comment]
This should fix the despawn issue if it is compatible with AC https://github.com/TrinityCore/TrinityCore/commit/2b1e8d135bd3f3a3ddf7f29471cf6116da223175 + https://github.com/TrinityCore/TrinityCore/commit/50c5d30d13fe12af2a2028baf845fb6eab329a57

**Comment by pklloveyou** [comment]
Because you are missing an item, entry 22236

**Comment by pklloveyou** [comment]
Food disappearing early is another mistake

**Comment by pklloveyou** [comment]
love_in_air.app
```
-                //if ((*itr) != target && (*itr)->HasAura(GetId())) //&& (*itr)->getStandState() == UNIT_STAND_STATE_SIT)
+                if ((*itr) != target && (*itr)->HasAura(GetId()) && (*itr)->getStandState() == UNIT_STAND_STATE_SIT)
                {
                    if (caster)
                    {
                        caster->CastSpell(*itr, SPELL_ROMANTIC_PICNIC_ACHIEV, true);
                        caster->CastSpell(target, SPELL_ROMANTIC_PICNIC_ACHIEV, true);
                    }
                    foundSomeone = true;
                    break;
                }
```

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/76587976-b3e96e00-6520-11ea-8307-3385bd79144f.png)
