### ISSUE TITLE
[Config] Crossfaction trading doesn't work (and never worked)

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#266]
**Description**: In worldserver.conf:
`AllowTwoSide.Trade = 1`

Doesn't work entirely.
This affects all the emulators for atleast 3 years (trinitycore, mangos etc), so fixing it on AzerothCore would be quite nice.

**Current behaviour**: When you enable this parameter (gametype doesn't affect it), you can't trade with the opposite faction's player unless you are grouped with him. **It displays "Target is unfriendly."**

**Expected behaviour**: We should be able to trade with the opposite faction even if not in a group.

**Steps to reproduce the problem**:

1. Set AllowTwoSide.Trade = 1 in worldserver.conf
2. Create 1 alliance character on an account, and 1 horde character on another account
3. Meet together and you can't trade (type /trade) unless you're in a group.

**Branch(es)**: All

**Operating system**:  Debian 8 jessie / windows 7 (useless info)

**Modules**:  No.

**Other Customizations**: None

**Comment by boom8866** [comment]
There is no problem Please re confirm the team

**Comment by falzard** [comment]
what?

**Comment by boom8866** [comment]
AllowTwoSide.Interaction.Chat = 1
AllowTwoSide.Interaction.Group = 1
AllowTwoSide.Trade = 1

Set the above and then try to test

**Comment by falzard** [comment]
It's already set to this (I enabled all AllowTwoSide) and it doesn't make sense anyway, you should try the issue before suggesting this!

**Comment by sucofog** [comment]
![image](https://cloud.githubusercontent.com/assets/734950/20649870/25c885a8-b4c9-11e6-9dd3-ccd52e167c25.png)

![image](https://cloud.githubusercontent.com/assets/734950/20649880/46df4d1c-b4c9-11e6-9b08-8dc82f539d13.png)

Yes, its bugged, confirmed.

**Comment by falzard** [comment]
Thanks Sucofog.
I tried to check if there was something related to this in TradeHandler.cpp but there was not, it was missing  (there are 2 lines of code but it's not about this particular issue).

**Comment by sucofog** [comment]
I don't think there's related to TradeHandler.cpp, its more related to config:

World.cpp
World.h

Let me check, missing config

**Comment by sucofog** [comment]
![image](https://cloud.githubusercontent.com/assets/734950/20650495/02609cde-b4d0-11e6-9ebd-529d91e8cf2e.png)

Change AllowTwoSide.Trade = 1 for AllowTwoSide.trade = 1

**Comment by falzard** [comment]
Did you try it? Because I just tried by changing the conf line to AllowTwoSide.trade = 1 and it didn't change anything.
Update: I just have another bug, my worldserver.conf modifications are not taken into account (database settings are but things like player starting level are not, what the hell)

**Comment by falzard** [comment]
`if (!sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_TRADE) && pOther->GetTeamId() != _player->GetTeamId())
    {
        SendTradeStatus(TRADE_STATUS_WRONG_FACTION);
        return;
    }`

The only part about this is that.

_Bonus: Found this
`void LFGMgr::SetTeam(uint64 guid, TeamId teamId)
{
    if (sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP))
        teamId = TEAM_ALLIANCE; // @Not Sure About That TeamId is supposed to be uint8 Team = 0(@TrinityCore)

    PlayersStore[guid].SetTeam(teamId);
}`

So everybody is considered alliance?_

**Comment by boom8866** [comment]
![f m no 6wkqhl1f a3eg](https://cloud.githubusercontent.com/assets/16046064/20657085/21f9a8f8-b56e-11e6-9dff-cd9075569d93.png)
![j5inrsh4 3h2ux kc zs8r](https://cloud.githubusercontent.com/assets/16046064/20657094/2aedef96-b56e-11e6-9f9c-84a471b07536.png)

Why?

I will be opposed?

**Comment by boom8866** [comment]
###################################################################################################
# PLAYER INTERACTION
#
#    AllowTwoSide.Accounts
#        Description: Allow creating characters of both factions on the same account.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

AllowTwoSide.Accounts = 1

#
#    AllowTwoSide.Interaction.Chat
#        Description: Allow say chat between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Chat = 1

#
#    AllowTwoSide.Interaction.Channel
#        Description: Allow channel chat between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Channel = 1

#
#    AllowTwoSide.Interaction.Group
#        Description: Allow group joining between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Group = 1

#
#    AllowTwoSide.Interaction.Guild
#        Description: Allow guild joining between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Guild = 0

#
#    AllowTwoSide.Interaction.Auction
#        Description: Allow auctions between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Auction = 1

#
#    AllowTwoSide.Interaction.Mail
#        Description: Allow sending mails between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Mail = 1

#
#    AllowTwoSide.AddFriend
#        Description: Allow adding friends from other faction the friends list.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.AddFriend = 1

#
#    AllowTwoSide.Trade
#        Description: Allow trading between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Trade = 1

#
#    TalentsInspecting
#        Description: Allow inspecting characters from the opposing faction.
#                     Doesn't affect characters in gamemaster mode.
#        Default:     1 - (Enabled)
#                     0 - (Disabled)

TalentsInspecting = 1

#
###################################################################################################

**Comment by falzard** [comment]
Ok boom8866, thank you for trying to help us but I already stated this in the issue. Try it WITHOUT A GROUP, or just wait for someone with real knowledge to answer, please.

**Comment by Blumfield** [comment]
I think I had this fixed, i'll see when I get internet and post the fix

**Comment by sucofog** [comment]
It would be nice @Blumfield ! :)

**Comment by falzard** [comment]
@Blumfield did you get internet back? :P

**Comment by Viste** [comment]
![wowscrnshot_031017_133109](https://cloud.githubusercontent.com/assets/281977/23792498/2c8c46ca-0598-11e7-92e5-c3cd7c516c15.jpg)
![wowscrnshot_031017_133112](https://cloud.githubusercontent.com/assets/281977/23792500/2e41ab7c-0598-11e7-8315-546f1feb6b2e.jpg)
All is ok man i don't know why it not work for you

**Comment by sucofog** [comment]
@Viste Try that without being in a group, that is what should be right, trading with opposite faction without being in a group/band

**Comment by Viste** [comment]
@sucofog ok i try later

**Comment by Viste** [comment]
without party don't work

**Comment by Viste** [comment]
Its corret i think, party make faction 3 and make other factions in one

**Comment by lineagedr** [comment]
Looked alot through the source code didn't find anything, most likely client bug?

**Comment by Yehonal** [comment]
It's probably a client limitation since the client is able to check
factions before server (improving performances)

Il 22 Ott 2017 5:02 AM, "lineagedr" <notifications@github.com> ha scritto:

**Comment by STARRHELD** [comment]
Yeah I think we can close down this issue as this is the same on TC - you need to be in a party to see the invite selection.
