### ISSUE TITLE
mod-eluna-lua-engine give some compilation errors

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#2661]
Compiling mod-eluna-lua-engine with the latest version of AzerothCore and LuaEngine I get the followings errors, I am reporting here, I will try to fix them, in the meanwhile any suggestions is well accepted :sweat_smile: 

> [ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Spells/Auras/SpellAuraEffects.cpp.o
> [ 76%] Built target scripts
> /home/helias/Documenti/sources/azerothcore-wotlk/src/server/game/Spells/Auras/SpellAuraEffects.cpp: In member function ‘void AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick(Unit*, Unit*) const’:
> /home/helias/Documenti/sources/azerothcore-wotlk/src/server/game/Spells/Auras/SpellAuraEffects.cpp:6030:50: error: could not convert ‘Eluna::GEluna->Eluna::OnDummyEffect(((WorldObject*)caster), ((const AuraEffect*)this)->AuraEffect::GetId(), ((SpellEffIndex)((const AuraEffect*)this)->AuraEffect::GetEffIndex()), target->Unit::<anonymous>.WorldObject::<anonymous>.Object::ToCreature())’ from ‘void’ to ‘bool’
>          if (c && caster && !sEluna->OnDummyEffect(caster, GetId(), SpellEffIndex(GetEffIndex()), target->ToCreature()))
> /home/helias/Documenti/sources/azerothcore-wotlk/src/server/game/Spells/Auras/SpellAuraEffects.cpp:6030:118: error: in argument to unary !
>          if (c && caster && !sEluna->OnDummyEffect(caster, GetId(), SpellEffIndex(GetEffIndex()), target->ToCreature()))
>                                                                                                                       ^
> src/server/game/CMakeFiles/game.dir/build.make:4577: recipe for target 'src/server/game/CMakeFiles/game.dir/Spells/Auras/SpellAuraEffects.cpp.o' failed
> make[2]: *** [src/server/game/CMakeFiles/game.dir/Spells/Auras/SpellAuraEffects.cpp.o] Error 1
> CMakeFiles/Makefile2:1072: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
> make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> 

modules: mod-eluna-lua-engine

**Comment by Rochet2** [comment]
Waiting to merge: https://github.com/azerothcore/azerothcore-wotlk/pull/2636

**Comment by Rochet2** [comment]
Try now
