### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/azerothcore-wotlk#2666]
Server crashes

##### SMALL DESCRIPTION:
after 5-20min server just crashes
Previously, this did not happen and there was an uptime of 4 days. Today there are problems

##### EXTRA NOTES:
```
terminate called after throwing an instance of 'ByteBufferPositionException'
  what():  Attempted to get value with size: 4 in ByteBuffer (pos: 0 size: 8)
Aborted

```
##### BRANCH(ES):
master

##### OPERATING SYSTEM:
ubuntu

**Comment by dev-master21** [comment]
I found out that the player comes in and sends some packets, because of which the server crashes.

**Comment by lineagedr** [comment]
@dev-master21 It would be helpful if you can list those packets.

**Comment by dev-master21** [comment]
> @dev-master21 It would be helpful if you can list those opcodes.

I have no extra logs. The player went to the server and did something, after which the server turned off. I could not understand what the problem was until I noticed in the log files that a 1st-level character comes in and immediately the server shuts down. I solved the problem by ban IP, but I think that the player will bypass the ban

**Comment by pklloveyou** [comment]
#1506

**Comment by gengarshadowball** [comment]
I was also getting malformed packets the other day

**Comment by dev-master21** [comment]
Due to this error please, attackers break the all servers on AzerothCore

**Comment by FrancescoBorzi** [comment]
@dev-master21 do you know how to reproduce the crash? does it happen only in latest revision or also in older versions of AC?

please provide us more information so we can solve the problem, if we don't know how to reproduce it, we can't do anything

**Comment by dev-master21** [comment]
> @dev-master21 do you know how to reproduce the crash? does it happen only in latest revision or also in older versions of AC?
> 
> please provide us more information so we can solve the problem, if we don't know how to reproduce it, we can't do anything

I do not know how to reproduce the error. But I think this is due to the fact that small packets are sent to the server. Such a problem is possible and it was before.

I found something that maybe might help in solving the problem.
https://github.com/TrinityCore/TrinityCore/commit/ce947814c6fa2c32c0908f1e7088ce971f74d365

**Comment by Laintime** [comment]
nead size return 
https://github.com/azerothcore/azerothcore-wotlk/blob/1952b2fbfbb3792319f320eb5d2bf22aa9a7dd4f/src/common/Packets/ByteBuffer.cpp#L15

**Comment by BarbzYHOOL** [comment]
what laintime?

**Comment by dev-master21** [comment]
Using the program, I will try to find the name of the package that the player sends to the server.

If someone can help me with the log file, so that I can more accurately track it, then please write about it here.

**Comment by BarbzYHOOL** [comment]
@dev-master21 try this PR https://github.com/azerothcore/azerothcore-wotlk/pull/2669/files (check our wiki if you don't know how)

**Comment by FrancescoBorzi** [comment]
@dev-master21  we have a fix, can you please test it and let us know?

https://github.com/azerothcore/azerothcore-wotlk/pull/2669

**Comment by dev-master21** [comment]
> @dev-master21 we have a fix, can you please test it and let us know?
> 
> #2669

I applied the changes. The server did not crash, but it seems to me that this person who crashed the server did not join go server in the last days.

Give 2-3 days for testing, I will answer here if the problem is resolved. Now I can not reproduce the error, so I need to wait for the hackers.

**Comment by CosmeF** [comment]
I've been experiencing the same issue, and the changes did not solve it. I'm still geting the same error.

**Comment by Viste** [comment]
@CosmeF crushdump, server.log can you give something?

**Comment by EpicDR** [comment]
> terminate called after throwing an instance of 'ByteBufferPositionException'
  what():  Attempted to get value with size: 4 in ByteBuffer (pos: 0 size: 8)
Aborted

**Comment by Helias** [comment]
Maybe this can help https://github.com/azerothcore/azerothcore-wotlk/pull/2684

**Comment by dev-master21** [comment]
> Maybe this can help #2684

Can I use this with a ah-bot?

**Comment by Helias** [comment]
@dev-master21 what do you mean? I think so, it should not break anything about the common use (play in-game, auction house bot etc.)
Just try it and see if your server still crash or not.

**Comment by dev-master21** [comment]
> @dev-master21 what do you mean? I think so, it should not break anything about the common use (play in-game, auction house bot etc.)
> Just try it and see if your server still crash or not.
The last time the server crashed 6 days ago. After that, the person who was breaking my server did not join to server. I can’t check now.

**Comment by Helias** [comment]
log the OPCODE which the user use to make crash your server and may we can work on it

**Comment by BarbzYHOOL** [comment]
@CosmeF @EpicDR test the fixes proposed (two pull requests), please

**Comment by CosmeF** [comment]
> 
> 
> @CosmeF @EpicDR test the proposed fixes (two pull requests), please

So far, so good. Working with both PR. We even try to drop it ourselves, and it holds nicely. Still waiting for the funny guy tho.

**Comment by Helias** [comment]
Ok, but please, next time you have a similar issue, please report it here with a log or the last OPCODE of the packet receive before the crash, so we can work on it asap.
