### ISSUE TITLE
[Core/Scripts] Battle for Mount Hyjal.

### ISSUE THREAD

**Issue by soniczhang11** [azerothcore/azerothcore-wotlk#2667]
##### SMALL DESCRIPTION:

Players can talk to NPCs after down the Boss(after 24h) to respawn the events. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When one event and boss are already finished, there should be no more gossip for players to aktive them again.

##### CURRENT BEHAVIOUR:

There seems to be something wrong with the scripts in core.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Just talk to NPCs to aktive and finish the events and bosses.
2. Wait for 24h.
3. Go in the RAID again and you will find you can aktive the events again, and all bosses can be respawned. They are also lootable after dead.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 30fa1ae3b4ed 2020-02-13 08:12:52 +0100 (master branch) (Unix, Rel     ease) (worldserver-daemon)

##### MODULES:

Nothing to do with Modules

**Comment by aradep** [comment]
Unable to reproduce on 2a17125
