### ISSUE TITLE
The transmogrification data is not saved to DB

### ISSUE THREAD

**Issue by retrydev** [azerothcore/azerothcore-wotlk#267]
**Description**: An item's appearance is reset on logout. The transmogrification data is not saved to DB.

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
using

+typedef std::unordered_map<uint64, uint32> TransmogMapType;
+
+#ifdef PRESETS
+typedef std::map<uint8, uint32> PresetslotMapType;
+struct PresetData
 {
+std::string name;
+PresetslotMapType slotMap; // slotMap[slotId] = entry
 };
+typedef std::map<uint8, PresetData> PresetMapType;
+#endif

+TransmogMapType transmogMap; // transmogMap[iGUID] = entry
+#ifdef PRESETS
+PresetMapType presetMap; // presetMap[presetId] = presetData
+#endif

compile without error, transmogrification data is not saved to DB
2.  
using

+uint32 Player::_customDataId = 0;

+class PlayerData
+{
+public:
+virtual ~PlayerData() {};
+};

+static uint32 GenCustomDataId() { return ++_customDataId; }
+bool HasCustomData(uint32 id) const { return _customData.find(id) != _customData.end(); }
+PlayerData& GetCustomData(uint32 id) { return _customData[id]; }
+PlayerData& SetCustomData(uint32 id, const PlayerData& data) { _customData[id] = data; return _customData[id]; }
+void DeleteCustomData(uint32 id) { _customData.erase(id); }

+static uint32 _customDataId;
+std::map<uint32, PlayerData> _customData;

compile without error, character create crash
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**: 

**Operating system**:  Win7 x64, Win7 x32 on Virtual Machine

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Yehonal** [comment]
Are you using transmog module? If yes you must post this issue in that
repository. They are separated projects

Il 28/Nov/2016 22:25, "Shukhrat" <notifications@github.com> ha scritto:

**Comment by retrydev** [comment]
I am not using transmog module, using transmog patch rochet2. ok, how to add TransmogDisplayVendor?

**Comment by Yehonal** [comment]
We don't support any 3rd party patch here. I close it

**Comment by retrydev** [comment]
о обиделся то шо его модуль не использую видишь ли, да поше

**Comment by ShinDarth** [comment]
@retrydev I don't know what you said but I suggest just use the Transmog module

**Comment by retrydev** [comment]
https://gist.github.com/retrydev/fd3de4c06993797a13a50c20072bd657
https://gist.github.com/retrydev/b313ba92b4de8ca536a8c6c60932bab7
https://gist.github.com/retrydev/43ebf46651013dd7cf2a81874ad6b664
https://gist.github.com/retrydev/57de53198dd95eb5d259b8cb94a9f29c
https://gist.github.com/retrydev/0dd2eeecc2db75e87207e1a5c44a1cdf
https://gist.github.com/retrydev/3aa1860bb319b4548389ac3aa825f6ac

full working transmog and transmogdisplayvendor ;) save and delete on DB :D

**Comment by ShinDarth** [comment]
@retrydev thanks a lot for sharing, but this way it is not really helping, can you open a PR to our [module transmog](https://github.com/azerothcore/mod-transmog) please ?
