### ISSUE TITLE
RangeHack

### ISSUE THREAD

**Issue by V3nomAnc3r** [azerothcore/azerothcore-wotlk#2673]
More info, With Fix >> https://github.com/TrinityCore/TrinityCore/issues/17060

**Comment by Viste** [comment]
#310

**Comment by V3nomAnc3r** [comment]
@Viste but still bug

**Comment by Viste** [comment]
@V3nomAnc3r #2675

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2686 another fix
