### ISSUE TITLE
[QUEST OBJECT] Fel Spirits

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2682]
##### SMALL DESCRIPTION:

The quest object becomes invisible after a few seconds or after capturing a spirit.  The laser is offset as well.
The object remains for a very long time as well. I logged off for 20min and it was still there, invisible of course.

![WoWScrnShot_021920_192207](https://user-images.githubusercontent.com/31663279/74863415-24e89c00-534e-11ea-909f-8c982bdf53c9.jpg)

![WoWScrnShot_021920_192259](https://user-images.githubusercontent.com/31663279/74863418-2619c900-534e-11ea-9ea9-faae7804e512.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The laser should start from the object like this link https://wow.zamimg.com/uploads/screenshots/normal/177893-fel-spirits.jpg Should not become invisible and should last less time.

##### CURRENT BEHAVIOUR:

The quest object becomes invisible after a few seconds or after capturing a spirit.  The laser is offset as well.
The object remains for a very long time as well. I logged off for 20min and it was still there, invisible of course.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do the quest id 10909
2. 
3. 

##### BRANCH(ES):

Master

##### OPERATING SYSTEM:

Ubuntu server 18.04

##### MODULES:

No one

**Comment by Endeffect-AT** [comment]
I confirm, noticed the same yesterday.
