### ISSUE TITLE
Grounded NPC flying over gap and crossing boundaries (mmap issue) [$75]

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2688]
##### SMALL DESCRIPTION:

Mobs can fly over a gap, or climb up/down a wall while it's impossible normally.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPCs should follow the laws of nature, like the player characters do.

##### CURRENT BEHAVIOUR:

Mobs can fly over a gap, climb up/down a mountain or a wall etc... it's gamebreaking and visually horrible and screams "BUG" to the players' ears.

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.cheat god`
2. `.go cr 90632` (inside BRD)
3. Attack this mob but do not kill it, at around 20% he will flee and join  the other side on the right and will pull all the mobs which is normally impossible and will wipe your group. This is kinda gamebreaking (and ugly to see).
4. You can also jump below and they will all follow you.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

8760a9f5c9739726cda09a96c44c11d4a6813e72

##### OPERATING SYSTEM:

Deb 9

**Comment by Maurowin** [comment]
Confirm!

**Comment by BarbzYHOOL** [comment]
I almost want to put priority critical for this

**Comment by FALL1N1** [comment]
https://github.com/OregonCore/OregonCore/commit/55d9bdc525e70a468bc7fe5e1ab974efdda0a845 should be backported as it improves the pathfinding in general a lot, here is an example http://prntscr.com/vc4fct, without it (the stock values) the path would be like this: http://prntscr.com/vc4ga8

**Comment by FALL1N1** [comment]
yeah, that fixes the issue, http://prntscr.com/vc4mk7 - they will stop at the edge and not going to fall underground...

In addition, I have added this for testing purposes, not sure if it's related and fixes it, but it's still worth the try - https://gist.github.com/FALL1N1/5d6ec1874303587ab61abbf68ab782d1

**Comment by Goatform** [comment]
That commit is quite an old one so I can't fully recall what it does when I committed it back in days. And @FALL1N1 , regard changing `i_nextCheckTime `from 0.5s down to 0.1s ... is a little bit scary. I suggest checking how expensive are those movement checks for `i_nextCheckTime`. Technically, it may improve some scenarios but at what cost?

**Comment by FALL1N1** [comment]
I'll benchmark it later and see how it performs, they are already .1s/.2s at Trinity, so it shouldn't have that heavy impact. @Goatform

**Comment by Goatform** [comment]
That would be quite helpful. But the thing that makes me wonder is logic. Example:

FleeingMovementGenerator has a  random reposition timer like this.
`i_nextCheckTime.Reset(urand(500, 1000));`
(Random timer between 500ms and 1000ms)

Wouldn't it also make sense to synchronize those timers together with `i_nextCheckTime` because FleeingMovementGenerator should already perform certain movement checks?

Either having 1 value or if it's a random value, perhaps to store it in variable and use that given value for checking `i_nextCheckTime `

**Comment by FALL1N1** [comment]
RAM remained the same, cpu as well, I did not see any performance drops as well as the VS debugger, so it's fine to be tested.
