### ISSUE TITLE
Mobs using "bitter blast" can one shot you

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2693]
##### SMALL DESCRIPTION:

One NPC uses the wrong spell
Another NPC is not using the spell while it should

##### CURRENT BEHAVIOUR:

This mob https://wotlk.evowow.com/?npc=32767 probably has the wrong spell, this is certainly the right spell https://wotlk.evowow.com/?spell=46406

This second mob ( https://wow.gamepedia.com/Ahunite_Coldwave ) should also have "bitter blast" , but he is missing the smart_scripts I guess 
EDIT: he has this spell instead 46887 which can only be cast at long range, I don't know if it's the right spell, probably yes

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.npc add 25756`
2. See the damage output, bitter blast should be around this number (1k) but he doesn't cast "bitter blast" since it's missing
3. `.npc add 32767`
1. This NPC has "bitter blast" and will one shot you :D makes no sense

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

d387bdc

**Comment by Degenesis** [comment]
I think this is intended. The mobs are fought using vehicles as part of daily quests.
https://wotlk.evowow.com/?quest=13374
https://wotlk.evowow.com/?quest=13376

**Comment by BarbzYHOOL** [comment]
Can you verify the other mobs, how much damage they do etc??

Because you just fly, pass nearby and get two shot (they hit more than the last boss of utgarde keep biggest spell), that's really unfair

**Comment by aradep** [comment]
- [x] Frostbrood Sentry's Bitter Blast is [blizzlike](https://youtu.be/Ijpg8a2X-gc?t=201)

- [x] Ahunite Coldwave casts Bitter Blast and damage is accurate.
