### ISSUE TITLE
[NPC] Moon Priestess Amara

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2700]
##### SMALL DESCRIPTION:

NPCs are not linked 
![InkedWoWScrnShot_022320_180012_LI](https://user-images.githubusercontent.com/31663279/75116297-245e4700-5667-11ea-801d-85477289c606.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They have to walk together, the one in the white frame always in the middle. If we talk to one of them, they all stop. As in this video, unfortunately, I couldn't find any video from the WOTLK era but nothing has changed since then.
https://youtu.be/gAFeMHS9b-8?t=135

##### CURRENT BEHAVIOUR:

NPCs are not linked 
https://wowgaming.altervista.org/aowow/?npc=2151

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go cr 2151
2. 
3. 

##### BRANCH(ES):

master

**Comment by Endeffect-AT** [comment]
I will check this soon!

**Comment by Stoabrogga** [comment]
Should be easy to fix using [creature formations](http://www.azerothcore.org/wiki/creature_formations). Here's an example I wrote a long time ago for the Kodos in the Barrens:
https://github.com/azerothcore/azerothcore-wotlk/blob/a42f16363fe2b5bb0a7d0c368b4f8568391a1202/data/sql/updates/pending_db_world/rev_1528460337456239208.sql#L13-L18
Moon Priestess Amara would be the leader with the other two NPCs being members of the formation. The waypoint movement of the members has to be removed in this case (creature_addon / waypoint_data).

**Comment by Endeffect-AT** [comment]
Thx a lot, that will be very useful!

**Comment by Endeffect-AT** [comment]
Cannot confirm this - Waypoints look good. 

Please convince me if i'm wrong or tell me how it should look like. 

![WoWScrnShot_022520_175632](https://user-images.githubusercontent.com/55922592/75269010-8c906280-57f8-11ea-81c3-2dbd863c817a.jpg)

![WoWScrnShot_022520_175646](https://user-images.githubusercontent.com/55922592/75269019-90bc8000-57f8-11ea-9072-8e662a4d5110.jpg)

![WoWScrnShot_022520_175733](https://user-images.githubusercontent.com/55922592/75269035-94500700-57f8-11ea-8253-e49d275ff75f.jpg)

**Comment by Stoabrogga** [comment]
As each of the NPCs is using it's own waypoint movement I could imagine that they get out of sync after a while, so a formation would be better in this case.

**Comment by Endeffect-AT** [comment]
I tried to delete the waypoint of the 2 other npcs and set a new creature_formation but the don't follow the leader. What  i did wrong?
