### ISSUE TITLE
[NPC] Zenn Foulhoof

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2701]
##### SMALL DESCRIPTION:

This NPC is turned the wrong way.
![WoWScrnShot_022320_175906](https://user-images.githubusercontent.com/31663279/75116448-cfbbcb80-5668-11ea-8b80-5b41d232fe69.jpg)
https://wowgaming.altervista.org/aowow/?npc=2150

##### EXPECTED BLIZZLIKE BEHAVIOUR:

 a 180° and you'll be fine.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go cr 2150
2. 
3. 

##### BRANCH(ES):

master

**Comment by Endeffect-AT** [comment]
Invalid - check this article: https://wowwiki.fandom.com/wiki/Zenn_Foulhoof
Position is as expected, but i agree it looks weird.

**Comment by Maurowin** [comment]
I had a doubt, thank you. I'll close this issue.

**Comment by Endeffect-AT** [comment]
No problem! :) At the beginning it helped me a lot to research here: https://wowwiki.fandom.com/wiki

Basically you can find almost everything here!
