### ISSUE TITLE
dont build with ENABLE_EXTRA_LOGS

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#2706]
/home/wow/code/GGCORE/src/server/game/Handlers/AuctionHouseHandler.cpp:682:163: fatal error: use of undeclared identifier 'guid'

#if defined(ENABLE_EXTRAS) && defined(ENABLE_EXTRA_LOGS)
        sLog->outDebug(LOG_FILTER_NETWORKIO, "WORLD: HandleAuctionHelloOpcode - Unit (GUID: %u) not found or you can't interact with him.", uint32(GUID_LOPART(guid)));
#endif

**Comment by Helias** [comment]
my fault, I will fix it asap
