### ISSUE TITLE
NPCs with waypoints take too long to restart.

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2712]
##### SMALL DESCRIPTION:

NPC with a waypoint take too long (minutes) to get back on track after interacting with them.
https://youtu.be/5Km03F75EJY

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They have to leave much faster. They may even interrupt the interaction with them if we take too long. I don't know how long, but probably no more than 30 seconds.

##### CURRENT BEHAVIOUR:

https://youtu.be/5Km03F75EJY

##### STEPS TO REPRODUCE THE PROBLEM:

1. speak with an NPC with waypoint like my video
2. 
3. 

##### BRANCH(ES):

master

**Comment by Stoabrogga** [comment]
Stop time is 2 minutes:
https://github.com/azerothcore/azerothcore-wotlk/blob/e22d78ecd6997bc11f8620b759364f119dac431a/src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.h#L22
(we should change the comment there)

I think 2 minutes is a good value, especially if reading through longer dialogues. No need to reduce it in my opinion.

**Comment by Maurowin** [comment]
it's handy for slow readers, but it's not blizzlike at all.

**Comment by Stoabrogga** [comment]
We could add an option in the worldserver configuration, so you can use the time you want. Should be easy to implement.
