### ISSUE TITLE
Stun spell stops moving creatures in mid-air

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#2713]
Stun spell stops moving creatures in mid-air

##### SMALL DESCRIPTION:
![image](https://user-images.githubusercontent.com/18535853/75301501-ebe08800-5875-11ea-8b80-7e7638f71376.png)
![image](https://user-images.githubusercontent.com/18535853/75301714-7f19bd80-5876-11ea-9e78-8fe3ebe2809d.png)
![image](https://user-images.githubusercontent.com/18535853/75301865-fd765f80-5876-11ea-8c9a-0360fbb2264e.png)
![image](https://user-images.githubusercontent.com/18535853/75301873-023b1380-5877-11ea-8c3b-66a4ed0392d1.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Shouldn't be off the ground.

##### CURRENT BEHAVIOUR:
spell 1776 8643 61685
This problem exists with all stun spells

##### STEPS TO REPRODUCE THE PROBLEM:
Cast spells on moving creatures

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
6869848
##### OPERATING SYSTEM:
w10x64

**Comment by humanana** [comment]
also too me when warrior charge to the target sometimes the target float on ground

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/75769314-ed7fe380-5d80-11ea-9aae-4e27a10b2c84.png)

**Comment by pklloveyou** [comment]
MoveMaps.Enable = 0  If set to close, there is no such error，But the game picture, you can imagine.

**Comment by pklloveyou** [comment]
The fish will walk on the water.

**Comment by BarbzYHOOL** [comment]
> The fish will walk on the water.

Sounds like a secret code for spies
:rofl:

**Comment by dcombat** [comment]
![](https://i.imgur.com/jOCT3fm.jpg)
![](https://i.imgur.com/6kUUf6f.jpg)
Seems to work fine for me

**Comment by pklloveyou** [comment]
As the fish swim through the water, they will chase you if they go too far, they will swim to the surface and move.

**Comment by pklloveyou** [comment]
This problem should be MMAP moving path generation problem,
![image](https://user-images.githubusercontent.com/18535853/77044445-6b3b2480-69fa-11ea-8349-d3361b94638b.png)
Green is the currently generated path, vertigo will cause NPCS to stop in the air,
The correct path should be blue

**Comment by Kitzunu** [comment]
@Yehonal is this touched in your PR?

**Comment by temperrr** [comment]
This has been resolved between reporting and now.
