### ISSUE TITLE
[Dungeon] Deadmine is buguy

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2718]
##### SMALL DESCRIPTION:

Deadmine is buguy

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- [ ] Aggro must be less wide, but it seems to be a general problem all over Azeroth.
- [ ] Spawning of patrols for each section after killing the boss corresponding to his section. 
- [ ] I don't know how many more monsters must come after blowing up the door, but not only two. 
- [ ] They must not stack up but spread out in an arc.
- [ ] When the NPC die, corpse must stay in the same place where he is dead and not a spawn place. (leave dungeon and back again)

##### CURRENT BEHAVIOUR:

- There is an aggro much too wide (we see it has several times in the video, we aggro even Vancleef too much too far)
- No patrols after killing bosses.
- When we destroy the door with the cannon we have two unfortunate NPCs stacking up...
- Kill all NPC and wait a few minutes, their corpses will move on their original spawn.

https://youtu.be/yClHUqIdLog

![WoWScrnShot_022620_150206](https://user-images.githubusercontent.com/31663279/75351811-054ef780-58a9-11ea-8807-ccd1397c806a.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. go into deadmin en clean it
2. 
3. 

##### BRANCH(ES):

master

**Comment by ChromieCraftServer** [comment]
some issues are still valid, others are duplicated, other have been fixed already. It's better to close this and open/confirm 1 ticket per bug

thanks for your report @Maurowin
