### ISSUE TITLE
[Dungeon] Hellfire Ramparts

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2719]
##### SMALL DESCRIPTION:

Some NPC are not linked and 2 wolves are stacked.
https://youtu.be/LyDLbuHtXuM.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Some NPC shall be linked
2 Wolves doesnot to be stacked.

##### CURRENT BEHAVIOUR:

Some NPC are not linked and 2 wolves are stacked.

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to hellfire ramparts
2. 
3. 

##### BRANCH(ES):

master

**Comment by aradep** [comment]
Pack linking issue confirmed on 2a17125. Couldn't find any stacked worgs, unless @Maurowin is refering to the lack of mob fanning.

**Comment by UltraNix** [comment]
Already fixed.
