### ISSUE TITLE
Diseased wolves are linked mobs but shouldn't

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#273]
**Description**: Attacking level 1-2 neutral wolves pull other wolves. Very minor bug

**Current behaviour**: In Northshire, diseased young/timber wolves are linked, if you attack one, one or two additional wolves will come.

Creature id: 69, 299

**Expected behaviour**: From http://wowwiki.wikia.com/wiki/Mangy_Wolf and from wowhead, only mangy wolves should trigger this behaviour.

**Steps to reproduce the problem**:

1. Go to northshire
2. Attack a wolf near other wolves

**Branch(es)**: master 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by HeartWell** [comment]
```diff
diff --git a/src/server/game/AI/CreatureAI.cpp b/src/server/game/AI/CreatureAI.cpp
index 226fd70..2d9c131 100644
--- a/src/server/game/AI/CreatureAI.cpp
+++ b/src/server/game/AI/CreatureAI.cpp
@@ -128,14 +128,20 @@ void CreatureAI::MoveInLineOfSight(Unit* who)
     if (me->GetVictim())
         return;
 
+    if (me->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET) // non-combat pets should just stand there and look good;)
+        return;
+
+        // Northshire Abbey - wolves fix. They can call assistance only outside the starting zone.
+        if (me->ToUnit()->getLevel() < 5 && me->GetAreaId() == 9)
+            return;
+
 	// pussywizard: civilian, non-combat pet or any other NOT HOSTILE TO ANYONE (!)
 	if (me->IsMoveInLineOfSightDisabled())
-		if (me->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET ||      // nothing more to do, return
-			!who->IsInCombat() ||                                         // if not in combat, nothing more to do
+        if (!who->IsInCombat() ||                                         // if not in combat, nothing more to do
 			!me->IsWithinDist(who, ATTACK_DISTANCE))                      // if in combat and in dist - neutral to all can actually assist other creatures
 			return;
 
-    if (me->CanStartAttack(who))
+    if (me->HasReactState(REACT_AGGRESSIVE) && me->CanStartAttack(who))
         AttackStart(who);
 }

**Comment by falzard** [comment]
I'll test it when I got time (not urgent), did you make it specifically or you had it fixed already? because that's very nice of you!

**Comment by falzard** [comment]
It's half working. Now they don't aggro when you attack one of them but if you run near one while another wolf is attacking you, then he will aggro you and you can pull all the mobs in the zone if you run to them all.
https://bitbucket.org/maczuga/sunwellcore/commits/fffefd59fa278b52a1a427479ba0a83024678356

**Comment by Ikfes** [comment]
Still not working.

**Comment by falzard** [comment]
From xinef:

> If someone wants to get rid off this (neutral npc aggros on someone attacking his 'friend') -> Creature.ccp:2040 change to if (targetVictim && IsHostileTo(target) && IsFriendlyTo(targetVictim). Instead of this you can remove our if from function FactionTemplateEntry::IsFriendlyTo, but plenty of the npc in instances will stop helping each other (buffs, healing, aggro etc.).
> btw. sorry for no response had internet problems
> How is it fixed on the current sunwell: hackfix, in northshire abbey no npc beneath level 5 won't be aggroed, even a hostile one. What about other neutral npc? Code from repo: if (me->ToUnit()->getLevel() < 5 && me->GetAreaId() == 9) return;

**Comment by talamortis** [comment]
try this sql and if it works ill do a PR
UPDATE 'creature_template' SET 'flags_extra' = '2' WHERE 'entry' = 69;

**Comment by falzard** [comment]
No, it doesn't change anything.

**Comment by STARRHELD** [comment]
Hackfix above.
