### ISSUE TITLE
[ITEM] [Flask of the North]

### ISSUE THREAD

**Issue by merdlin** [azerothcore/azerothcore-wotlk#2732]
item could be in trouble.

SHORT DESCRIPTION:
it is a random potion or it activates the spell or the power or force attack, in which case it is only activating the spell and the force, but the power attack it is not activated.

CURRENT BEHAVIOR:
https://wotlk.evowow.com/?item=47499

STEPS TO REPRODUCE THE PROBLEM:
just drink the potion
OPERATING SYSTEM:
Windows server 2016

MODULS:
MOD-CFBG / ARENA 1V1

OTHER CUSTOMIZATIONS:
no
-->

**Comment by BarbzYHOOL** [comment]
Please, use https://www.deepl.com/translator to improve your description

**Comment by BarbzYHOOL** [comment]
item: https://wotlk.evowow.com/?item=47499

**Comment by GMKyle** [comment]
flask of the north triggers a class dependent buff, according to:
TC old 2012 issue
https://github.com/TrinityCore/TrinityCore/issues/5287
wowhead
https://es.wowhead.com/item=47499/flask-of-the-north#english-comments
Ex:
https://wowwiki.fandom.com/wiki/Flask_of_the_North 
```
As of 3.3 this flask gives either a Spellpower or Strength buff to druids, meaning 
you have to click it twice and/or mouse over the buff to make sure you got the one 
you want. There is currently no widely known way to always get one or the other 
with either an addon or a macro. 
```
Extract of azerothcore Flask of the North spellscript :
```c++
switch (caster->getClass())
{
    case CLASS_WARLOCK:
    case CLASS_MAGE:
    case CLASS_PRIEST:
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_SP);
        break;
    case CLASS_DEATH_KNIGHT:
    case CLASS_WARRIOR:
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_STR);
        break;
    case CLASS_ROGUE:
    case CLASS_HUNTER:
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_AP);
        break;
    case CLASS_DRUID:
    case CLASS_PALADIN:
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_SP);
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_STR);
        break;
    case CLASS_SHAMAN:
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_SP);
        possibleSpells.push_back(SPELL_FLASK_OF_THE_NORTH_AP);
        break;
}
```


which class have you tested?

**Comment by BarbzYHOOL** [comment]
So it seems like it's working fine, but how does it work for druid? it's just random but then you have to wait for the cooldown? how long is that cooldown??

(thank you @GMKyle for info)

**Comment by GMKyle** [comment]
@BarbzYHOOL  hasn't cooldown, normally only takes a few "sips" to get desired buff :P

**Comment by merdlin** [comment]
no problems then?

**Comment by BarbzYHOOL** [comment]
i see one problem lol why does it give a strength buff instead of attack power for druid??

or it should give one of all 3 buffs instead of 2 only (i know it's apparently what blizzard did but that was stupid on their part of course)

**Comment by merdlin** [comment]
the problem reported was in the Druid class.

**Comment by GMKyle** [comment]
Str grants 2 Attack Power for each point as feral so.....

**Comment by BarbzYHOOL** [comment]
> Str grants 2 Attack Power for each point as feral so.....

even as cat?? if so, then yes, no need and it's working fine :D

**Comment by BarbzYHOOL** [comment]
ok i mixed up strength and agi, well so all seems fine, and IT IS blizzlike

so gonna close this

@merdlin the druid does not trigger Attack Power, but he still has +80 attack power in bear form and cat form, so it's the same result
