### ISSUE TITLE
[DB] char_trade_logs doesn't work

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/azerothcore-wotlk#2741]
##### SMALL DESCRIPTION:
No entries to the database char_trade_logs

##### STEPS TO REPRODUCE THE PROBLEM:

1. login and make 2 characters, exchange items with another character
2. check table char_trade_logs

##### BRANCH(ES):
master

##### OPERATING SYSTEM:
linux 18.04

**Comment by BarbzYHOOL** [comment]
doesn't require a worldserver conf option enabled??

**Comment by Bogir** [comment]
I have no such table **char_trade_logs** at by Characters DB
Who stoled it?

**Comment by Bogir** [comment]
Which server it come from?
