### ISSUE TITLE
Implementation of a c++ linter integrated with IDE and CI

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#2745]
##### SMALL DESCRIPTION:
I'm opening this issue to collect information on the "epic" job to integrate a linter system to format the code using the IDE (with visual studio [code] extensions) and check the formatting via CI (such as eslint for javascript/typescript) 

To do it we can study and integrate the clang-tidy system

##### EXPECTED BLIZZLIKE BEHAVIOUR:
blizzwhat? 🌩 

##### CURRENT BEHAVIOUR:

At the moment all code is messed up with formatting, there's not homogeneous code style and even worse the indentation varies from 4 spaces to tabs everywhere, making the code unreadable sometime.

##### STEPS TO REPRODUCE THE PROBLEM:

open your ide and make a search of this character between the double quotes: "	"

##### BRANCH(ES):

master

**Comment by Kitzunu** [comment]
I am going to close this in the belief that this already exists

- CI checks for codestyle as far as tabs and trailing spaces goes
- Most IDE's defaults to 4 spaces
- I believe we do not have tabs anywhere in the project.

Feel free to reopen it if I'm wrong

**Comment by Yehonal** [comment]
linter is way more than that, clang-tidy should be the linter for cpp but we are not using it entirely I guess
