### ISSUE TITLE
Core/Command: npc info

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#2749]
This is just a personal opinion and a personal preference that I would like to put as a suggestion.

Currently if you do `.npc info` on an NPC you will get this for the flags:
![image](https://user-images.githubusercontent.com/24550914/76568675-a0eb8500-64b1-11ea-82c0-baf4055fcca7.png)

My suggestion would be to show the actual flag names (+ the total value) so you quickly can see if an NPC has a flag that is causing a bug without you having to look it up with some tool or wiki etc.

Also having the spacing between them is unnecessary imo, as I dont see the point for it other than it is rather confusing ^^

**Comment by FrancescoBorzi** [comment]
it's a theoretically a good idea, however there are so many values per every single flags-field so I'm not sure if displaying them in the client's chat might be a good idea at the end.

Just FYI, using [Keira3](https://github.com/azerothcore/Keira3/releases) you can have a good overview of each flags-field, e.g.:

![image](https://user-images.githubusercontent.com/75517/76574967-2aa14f80-64be-11ea-91ab-ba63934c896c.png)

**Comment by BarbzYHOOL** [comment]
the spacing is confusing for sure

btw for the immunity flags, they are shown at the end

**Comment by Kitzunu** [comment]
yea that I saw also after ^^

**Comment by Kitzunu** [comment]
I fixed this already and forgot about this issue =)
