### ISSUE TITLE
The "(low level)" unknown quest (bug)

### ISSUE THREAD

**Issue by sucofog** [azerothcore/azerothcore-wotlk#275]
**Description**: The "(low level)" unknown quest

**Current behaviour**: In some cases, some NPC's give a "(low level)" quest, it's untargetable, cannot be accepted, it disappears when you complete the quest above.
If you click the "(low level)" quest first, you cannot take the above quest, you have to walk backwards and then speak again with the NPC.

This happened in different NPC's, 4-5 different cases at different locations and zones.

**Expected behaviour**: The "(low level)" unknown quest should not appear in any NPC.

**Steps to reproduce the problem**:

1. It happens randomly, go, take a quest, complete it..
2. Then, talk to other npc that is questgiver,
3. It will show a "(low level)" quest untargetable, and the quest that the npc should give, then you complete the quest, and the "(low level)" quest dissapears.

NPC's reproducing the bug:

NPC = 381
NPC = 415
NPC = 341

Screenshots attached:

![blob 1](https://cloud.githubusercontent.com/assets/734950/20938466/85202d3e-bbeb-11e6-9913-78c81b8f2b01.png)

![blob](https://cloud.githubusercontent.com/assets/734950/20938472/8acf05ac-bbeb-11e6-863e-52b9a409a52b.png)

**Branch(es)**: 0.x / 1.x / master

**AC hash/commit**:  Reproducing this on latest commit:

https://github.com/azerothcore/azerothcore-wotlk/commit/440b7e731fa4747036398dcf9411fb3dfb013570

**Operating system**:  Windows 10 Pro.

**Modules**:  None.

**Other Customizations**: None.

**Comment by sucofog** [comment]
@ShinDarth Can you confirm this?

**Comment by ShinDarth** [comment]
I can't try it now but so far I haven't heard such issue from players

**Comment by Blumfield** [comment]
Could be a locales problems

**Comment by 3ndos** [comment]
@Blumfield I'm thinking so also

**Comment by sucofog** [comment]
The problem was solved, i got bad locales on my database, really sorry for wasting your time guys.

**Comment by ShinDarth** [comment]
no problem, I'm glad that you've solved!
