### ISSUE TITLE
Passive spell "thorns" can MISS

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2754]
##### SMALL DESCRIPTION:

Druid's passive spell "thorns" can miss https://wotlk.evowow.com/?search=thorns#abilities

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should never miss

##### CURRENT BEHAVIOUR:

There is a low chance that instead of dealing damage, it misses, as if user was directly casting a spell.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .cast 9910
2. Fight a melee mob with few levels higher than you, and check the combat log for the miss to happen

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

2eeab4c72b0383d4611a17bbb925a1f2c412082d

**Comment by frytik** [comment]
Any proof ?

**Comment by BarbzYHOOL** [comment]
proof of what? that it should NOT miss? :rofl:

**Comment by Viste** [comment]
@frytik 
![Снимок экрана от 2020-03-17 00-31-35](https://user-images.githubusercontent.com/281977/76801421-b41a8f80-67e6-11ea-9b97-b03f81245f96.png)

**Comment by BarbzYHOOL** [comment]
the PR above fixes it for druids which is the most important

however some NPC/item spells are still missing, here are some that may be bugged (some are fixed in the DBC already):
https://webdb.fusion-host.eu/?search=thorns#npc-abilities (ex: 31271)
https://webdb.fusion-host.eu/?search=thorns#spells

also some shaman/priest/paladin spells might have the same minor issue
