### ISSUE TITLE
Timed Actionlists having event_type different than 0

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#2761]
I run the following query to check what kind of `event_type` our Timed Actionlists have:

```
SELECT  event_type, COUNT(*) FROM smart_scripts WHERE source_type = 9 GROUP BY event_type;
```

The result is:

![image](https://user-images.githubusercontent.com/75517/76681705-1a8c8b80-65f6-11ea-9880-617ce82905d2.png)

while majority of them have `event_type` set to `0` there are some execptions.

I'm wondering, are all those non-0 timed actionslists a mistake or there is something that I'm missing here?

**Comment by malcrom** [comment]
Those are errors
