### ISSUE TITLE
build[compilation FAIL] anyone? 1668b76

### ISSUE THREAD

**Issue by humanana** [azerothcore/azerothcore-wotlk#2775]
does anyone Fail on compilation on 1668b76 ?

not only the world socket warning still happen but the compilation have fatal error and fail to finish compilation [from #2735]

I have no idea what affect to the core currently ,or is it only me??? TT[]TT

![e1](https://user-images.githubusercontent.com/51247678/76957715-e512d580-6948-11ea-9f80-76c1dc23188a.JPG)

**Comment by Viste** [comment]
all is ok on linux on last master

**Comment by Viste** [comment]
do you add some changes to SOAP?

**Comment by humanana** [comment]
> do you add some changes to SOAP?

nope,I just only fresh pull from git I'm on windows x64 8.1

**Comment by dunjeon** [comment]
Windows 10 builds without any problems: 8d6bf1f

**Comment by humanana** [comment]
right... I go back to test the old clone link from here 

I used 2. choice the first time, then clone and pull the update to latest but I dont know what happen perhaps from my mistake I got error from above with SOAP

now I test again clone from choice 1 and recompile again now the error gone but world socket still warning [from issues/2735]

sorry if it was my mistake for wrong error OTL

![e2](https://user-images.githubusercontent.com/51247678/76992545-00e49e80-697e-11ea-8870-4afe52cc9d53.JPG)

![e3](https://user-images.githubusercontent.com/51247678/76992974-adbf1b80-697e-11ea-943e-dbf32b572c7d.JPG)

**Comment by Mitradis** [comment]
Compiler just crashed on latest VS2019...

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can you please help with this?

**Comment by Mitradis** [comment]
https://i.ibb.co/gttg9P7/image.png

**Comment by Mitradis** [comment]
https://i.ibb.co/RDj3qxH/image.png

**Comment by dunjeon** [comment]
I can confirm a build error with the latest Visual 2019 version 16.5.0 (updated on 03-18-202). But it is not the same error as this issue ticket. This should have it's own issue, yes?

**Comment by Viste** [comment]
Никому твои окна не нужны, все адекватные люди сидят на линуксе(даже microsoft признает что linux лучше), если мозгов не хватает страдай.

**Comment by Viste** [comment]
@dunjeon plz open issue with a normal description of the problem, screenshots or a paste log.

**Comment by IntelligentQuantum** [comment]
Fix - Visual studio 16.3.0

Ace Error - Visual studio 16.5.0

**Comment by Mitradis** [comment]
**IntelligentQuantum**
ty. i will try today

**Viste**
я не задрот этого проекта и не прогер на плюсах. Я просто собираю время от времени чисто для ностальгии. Извини если чем то обидел, я понимаю, что это непростая работа и ты очень много вложил в этот проект и твой вклад действительно существенный.

**Comment by BarbzYHOOL** [comment]
> Compiler just crashed on latest VS2019... when compile ACE.
> 
> Заебали со своим докером, в жопу себе его запихните и наладьте нормальный компиль для винды. Каждый раз сука одно и тоже, месяц проходит и нихуя не компилится.

what the hell is that retard on

**Comment by asfo** [comment]
My compilation fails also, but with a different error:

QueryResult.h(87): error C2143: 

```
private:
        MYSQL_BIND* m_rBind;
        MYSQL_STMT* m_stmt;
        MYSQL_RES* m_res;

        my_bool* m_isNull;
        unsigned long* m_length;

        void FreeBindBuffer();
        void CleanUp();
        bool _NextRow();
```

It says that I need to add a `;` after `my_bool*`.

I know that this requires MySQL 5.7 but I'm wondering if there is a fix to make it works with MySQL 8 instead.

**Comment by Kitzunu** [comment]
@asfo yes, there is a fix for MySQL 8.0 for Windows 10.
See the changes here https://github.com/azerothcore/azerothcore-wotlk/pull/2896

I personally run MySQL 8.0

**Comment by Kitzunu** [comment]
The actual issue of this topic:
Usually you get that error if you try to compile while Worldserver.exe/authserver.exe is still running.

**Comment by Kitzunu** [comment]
Okay, the build will fail if you use VS over this version:
VS 19 16.2

**Comment by Winfidonarleyan** [comment]
Hah, normal build at vs 19 16.4.2

**Comment by Winfidonarleyan** [comment]
Sucesfull build at VS 19 `16.4.6`
![image](https://user-images.githubusercontent.com/18329778/80276486-5ba6ae00-8713-11ea-80d5-2616351021c6.png)

**Comment by Kitzunu** [comment]
Ok 16.5 dont work at least, I tested it yesterday

**Comment by Winfidonarleyan** [comment]
> Ok 16.5 dont work at least, I tested it yesterday

Haha, okay, I'm already rocking the latest version.
![image](https://user-images.githubusercontent.com/18329778/80280759-49873880-8730-11ea-8d4e-69b479d38f02.png)

**Comment by Winfidonarleyan** [comment]
Well played, aaaah. Failed build at `VS 16.5.4`

Failed build-in library `ace` in file `Process_Manager.cpp(142,1)`
```
D:\Git\azerothcore-wotlk\deps\acelite\ace\Process_Manager.cpp(142,1): fatal error C1001: 
```

Full log
```
1>------ Сборка начата: проект: ZERO_CHECK, Конфигурация: Release x64 ------
1>Checking Build System
2>------ Сборка начата: проект: ace, Конфигурация: Release x64 ------
2>Dynamic_Service_Base.cpp
2>Log_Msg_NT_Event_Log.cpp
2>Name_Space.cpp
2>Process_Manager.cpp
2>D:\Git\azerothcore-wotlk\deps\acelite\ace\Process_Manager.cpp(142,1): fatal error C1001: Внутренняя ошибка компилятора.
2>(Файл компилятора "msc1.cpp", строка 1532.)
2> Чтобы обойти эту проблему, попытайтесь упростить или изменить программу в строках около указанной позиции.
2>Если это возможно, предоставьте шаги, которые привели к возникновению проблемы, на следующей странице: https://developercommunity.visualstudio.com.
2>Для получения дополнительных сведений выберите команду "Техническая поддержка"
2>в меню "Справка" Visual C++ или откройте файл справки технической поддержки.
2>ВНУТРЕННЯЯ ОШИБКА КОМПИЛЯТОРА в "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\CL.exe"
2>    Выберите команду "Техническая поддержка" в меню "Справка" Visual C++ или
2>    откройте справочный файл технической поддержки для получения доп. сведений
2>cl : командная строка error D8040: ошибка при создании или взаимодействии с дочерним процессом
2>Сборка проекта "ace.vcxproj" завершена с ошибкой.
========== Сборка: успешно: 1, с ошибками: 1, без изменений: 0, пропущено: 0 ==========
```

**Comment by Winfidonarleyan** [comment]
Okay okay, I solved this problem. Need download `16.6.0 Preview 4.0` (last)

![image](https://user-images.githubusercontent.com/18329778/80346468-fd093d80-8894-11ea-8cd4-2ff76ed41756.png)

**Comment by Viste** [comment]
or update acelite
