### ISSUE TITLE
[refundable item]Items purchased from a merchant cannot be returned within two hours

### ISSUE THREAD

**Issue by kuramajssken001** [azerothcore/azerothcore-wotlk#2778]
**SMALL DESCRIPTION:**

Items purchased from a merchant cannot be returned within two hours.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Items purchased within 2 hours can be returned in full.

**CURRENT BEHAVIOUR:**

Non-refundable after purchase.

**BRANCH(ES):**
master

**AC HASH/COMMIT:**
ef5d6eae9b2d8a6a594dd98c73faf9d52412f7fa

**Comment by Viste** [comment]
plz edit issue to correct format. http://www.azerothcore.org/wiki/Contribute#how-to-open-an-issue

**Comment by pklloveyou** [comment]
Just disable the plug-in.PR can be turned off：）

**Comment by kuramajssken001** [comment]
> plz edit issue to correct format. http://www.azerothcore.org/wiki/Contribute#how-to-open-an-issue

Ok,I have reedited it.

**Comment by pklloveyou** [comment]
你把插件禁用了不就能退了？

**Comment by boom8866** [comment]
This problem occurs in China. The closure problem is not caused by the core.

**Comment by pklloveyou** [comment]
Related to the version of wow.exe,V13930 wow.exe does not have this problem，My personal feeling is that it should have something to do with custom plug-ins

**Comment by kuramajssken001** [comment]
@pklloveyou 是插件的引起的？没往这方面想。。。好的我去试一下，谢谢你

**Comment by kuramajssken001** [comment]
经过测试，问题确实是因插件引起的。那么我将这个问题关闭.
