### ISSUE TITLE
erorr compiler 

### ISSUE THREAD

**Issue by behnam3000** [azerothcore/azerothcore-wotlk#278]
hi 
Please guide me the following error when compiling.
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int EVP_EncryptInit_ex(EVP_CIPHER_CTX *,const EVP_CIPHER *,ENGINE *,const unsigned char *,const unsigned char *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	shared	C:\Users\...\source\modules\worldengine\nucleus\src\Cryptography\ARC4.cpp	13	
.........................................................................................................................................................................
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'INTMAX_MAX': undeclared identifier (compiling source file C:\Users\raged_000\Downloads\Compressed\azerothcore-wotlk-master\source\modules\acore\extractors\mmaps_generator\TerrainBuilder.cpp)	mmaps_generator	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio	113

**Comment by ShinDarth** [comment]
which compiler are you using?

**Comment by behnam3000** [comment]
visual studio community 2015 update 3
Cmake = visual studio 14 2015

**Comment by behnam3000** [comment]
What is this error when capturing build.
1) ARC4::m_ctx' uses undefined struct 'evp_cipher_ctx_init'
2)'HmacHash::m_ctx' uses undefined struct 'hmac_ctx_st'
3)'HMAC_CTX_init': identifier not found
4)'int HMAC_Init_ex(HMAC_CTX *,const void *,int,const EVP_MD *,ENGINE *)': cannot convert argument 1 from 'int *' to 'HMAC_CTX *
5)annot open input file '..\..\modules\worldengine\nucleus\src\Release\shared.lib
Please help release when I got the above error.
The two screenshots of the build of Visual Studio errors later.
![1](https://cloud.githubusercontent.com/assets/9869505/21103793/20cac314-c099-11e6-81fe-5c27c7303879.jpg)
![2](https://cloud.githubusercontent.com/assets/9869505/21103794/2102ce6c-c099-11e6-9523-383bdde97781.jpg)

**Comment by behnam3000** [comment]
No one to help me

**Comment by ShinDarth** [comment]
unfortunately I'm not able to reproduce the issue on my system

**Comment by sucofog** [comment]
Im not able also, compiling is just fine on Linux/Windows

**Comment by HeartWell** [comment]
Reinstall all soft(MySQL,openSLL, git, Cmake only you operation 64 or 32).

**Comment by sucofog** [comment]
I don' think this is a valid bug, why still open?

**Comment by adan830** [comment]
visual studio community 2015 update 3
Cmake = visual studio 14 2015
I have the same error:
1>  IntermediateValues.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(111): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(123): note: 参见对正在编译的类 模板 实例化“std::ratio<_Nx,_Dx>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(113): error C2065: “INTMAX_MAX”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(26): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(165): note: 参见对正在编译的类 模板 实例化“std::_Ratio_add<_R1,_R2>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(216): error C2338: integer arithmetic overflow
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): note: 参见对正在编译的类 模板 实例化“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2794: “type”: 不是“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的任何直接或间接基类的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2938: “ratio_multiply<std::ratio<100,1>,std::nano>”: 未能使别名模板专用化
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2062: 意外的类型“unknown-type”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2238: 意外的标记位于“;”之前
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2065: “period”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2923: “std::chrono::duration”: 对于参数“_Period”，“period”不是有效的 模板 类型变量
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(969): error C3203: “duration”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Duration”，应为 real 类型
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(973): note: 参见对正在编译的类 模板 实例化“std::chrono::time_point<std::chrono::system_clock,int>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C3646: “rep”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C3646: “period”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(235): error C2338: duration must be an instance of std::duration
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): error C2228: “.count”的左边必须有类/结构/联合
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): note: 类型是“int”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>  MapBuilder.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(111): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(123): note: 参见对正在编译的类 模板 实例化“std::ratio<_Nx,_Dx>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(113): error C2065: “INTMAX_MAX”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(26): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(165): note: 参见对正在编译的类 模板 实例化“std::_Ratio_add<_R1,_R2>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(216): error C2338: integer arithmetic overflow
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): note: 参见对正在编译的类 模板 实例化“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2794: “type”: 不是“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的任何直接或间接基类的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2938: “ratio_multiply<std::ratio<100,1>,std::nano>”: 未能使别名模板专用化
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2062: 意外的类型“unknown-type”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2238: 意外的标记位于“;”之前
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2065: “period”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2923: “std::chrono::duration”: 对于参数“_Period”，“period”不是有效的 模板 类型变量
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(969): error C3203: “duration”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Duration”，应为 real 类型
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(973): note: 参见对正在编译的类 模板 实例化“std::chrono::time_point<std::chrono::system_clock,int>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C3646: “rep”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C3646: “period”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(235): error C2338: duration must be an instance of std::duration
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): error C2228: “.count”的左边必须有类/结构/联合
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): note: 类型是“int”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>  PathGenerator.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(111): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(123): note: 参见对正在编译的类 模板 实例化“std::ratio<_Nx,_Dx>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(113): error C2065: “INTMAX_MAX”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(26): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(165): note: 参见对正在编译的类 模板 实例化“std::_Ratio_add<_R1,_R2>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(216): error C2338: integer arithmetic overflow
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): note: 参见对正在编译的类 模板 实例化“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2794: “type”: 不是“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的任何直接或间接基类的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2938: “ratio_multiply<std::ratio<100,1>,std::nano>”: 未能使别名模板专用化
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2062: 意外的类型“unknown-type”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2238: 意外的标记位于“;”之前
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2065: “period”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2923: “std::chrono::duration”: 对于参数“_Period”，“period”不是有效的 模板 类型变量
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(969): error C3203: “duration”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Duration”，应为 real 类型
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(973): note: 参见对正在编译的类 模板 实例化“std::chrono::time_point<std::chrono::system_clock,int>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C3646: “rep”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C3646: “period”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(235): error C2338: duration must be an instance of std::duration
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): error C2228: “.count”的左边必须有类/结构/联合
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): note: 类型是“int”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>  TerrainBuilder.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(111): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(123): note: 参见对正在编译的类 模板 实例化“std::ratio<_Nx,_Dx>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(113): error C2065: “INTMAX_MAX”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(26): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(165): note: 参见对正在编译的类 模板 实例化“std::_Ratio_add<_R1,_R2>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(216): error C2338: integer arithmetic overflow
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): note: 参见对正在编译的类 模板 实例化“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2794: “type”: 不是“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的任何直接或间接基类的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2938: “ratio_multiply<std::ratio<100,1>,std::nano>”: 未能使别名模板专用化
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2062: 意外的类型“unknown-type”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2238: 意外的标记位于“;”之前
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2065: “period”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2923: “std::chrono::duration”: 对于参数“_Period”，“period”不是有效的 模板 类型变量
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(969): error C3203: “duration”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Duration”，应为 real 类型
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(973): note: 参见对正在编译的类 模板 实例化“std::chrono::time_point<std::chrono::system_clock,int>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C3646: “rep”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C3646: “period”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(235): error C2338: duration must be an instance of std::duration
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): error C2228: “.count”的左边必须有类/结构/联合
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): note: 类型是“int”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>  VMapExtensions.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(111): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(123): note: 参见对正在编译的类 模板 实例化“std::ratio<_Nx,_Dx>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(113): error C2065: “INTMAX_MAX”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(26): error C2065: “INTMAX_MAX”: 未声明的标识符
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(165): note: 参见对正在编译的类 模板 实例化“std::_Ratio_add<_R1,_R2>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ratio(216): error C2338: integer arithmetic overflow
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): note: 参见对正在编译的类 模板 实例化“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2794: “type”: 不是“std::_Ratio_multiply_sfinae<std::ratio<100,1>,std::nano,false,void>”的任何直接或间接基类的成员
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2938: “ratio_multiply<std::ratio<100,1>,std::nano>”: 未能使别名模板专用化
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2062: 意外的类型“unknown-type”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(966): error C2238: 意外的标记位于“;”之前
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2065: “period”: 未声明的标识符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(968): error C2923: “std::chrono::duration”: 对于参数“_Period”，“period”不是有效的 模板 类型变量
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(969): error C3203: “duration”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Duration”，应为 real 类型
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(973): note: 参见对正在编译的类 模板 实例化“std::chrono::time_point<std::chrono::system_clock,int>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C3646: “rep”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(231): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2825: '_Duration': 当后面跟“::”时必须为类或命名空间
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C2510: “_Duration”:“::”的左边必须是类/结构/联合
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C3646: “period”: 未知重写说明符
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(232): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(235): error C2338: duration must be an instance of std::duration
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(974): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): error C2228: “.count”的左边必须有类/结构/联合
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(979): note: 类型是“int”
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): error C2440: “<function-style-cast>”: 无法从“__int64”转换为“std::chrono::system_clock::duration”
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\chrono(985): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
