### ISSUE TITLE
Beacon of Light wrong proc 

### ISSUE THREAD

**Issue by junker1609** [azerothcore/azerothcore-wotlk#2782]
**Beacon of Light wrong proc** 

##### SMALL DESCRIPTION:
The spell Beacon of Light is wrong proc when its used with Judgement of Light and the glyph of Holy light sometimes, paladin raises his arms in the air every time a group member hits an enemy under judgment 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Paladin should not initiate proc or heal if any member attacks an enemy under judgment

##### CURRENT BEHAVIOUR:
If you make a light judgment on an enemy, and you put the Beacon on you, you will raise your arms every time your friend hits the enemy under judgment

##### STEPS TO REPRODUCE THE PROBLEM:

1. Put a paladin and other character in party.
2. Use Glyph of Holy light 
3. Use Beacon of Light on you, and use Judgement of Light in some dummy.
4. Make other character attack by melee on dummy

##### EXTRA NOTES:

master branch Unix release

##### AC HASH/COMMIT:

AzerothCore rev.d131840f34a8+ 

##### OPERATING SYSTEM:
Ubuntu 18.64

##### MODULES:
Crossfaction BG
PREMIUM MOD
Guild house
Mod-XP
Transmog

**Comment by MakUCI** [comment]
also:
- player with beacon takes longer to get out of combat (instances, bg,wintergrasp, idk if arena).
- player with beacon receive extra heals from judgement of light proc. (bug???)
- with proc explained in the issue also paladin do melee extra attack even at long range(more than 8 yards)

**Comment by Andrei-UPB** [comment]
Confirmed, the Beacon of Light target gets indirect heals transferred over such as Judgement of Light procs, Seal of Light procs, procs from Glyph of Holy light, which are not a "heal you cast on party or raid member", as per the tooltip: 

"The target becomes a Beacon of Light to all members of your party or raid within a 60 yard radius. Any heals you cast on party or raid members will also heal the Beacon for 100% of the amount healed. Only one target can be the Beacon of Light at a time. Lasts 1 min."

In my azerothcore db the table spell_proc is empty and trying to filter out the extra procs here by using masks breaks the spell entirely. I am willing to work on a solution if anyone can give me a pointer in the right direction.

**Comment by Malow** [comment]
Same issue as reported here on TrinityCore: https://github.com/TrinityCore/TrinityCore/issues/20337

This issue seems pretty severe to me, I think a Holy Paladin can basically get double the HPS compared to what he should have with both Judgement of Light and the Holy Light Glyph combined.

**Comment by Yehonal** [comment]
Maybe we can ask the sunwell-bastards to share their fix to the open-source community: SunwellTracker/issues#2454

PS Could be it related? https://github.com/TrinityCore/TrinityCore/pull/21260

**Comment by GMKyle** [comment]
No recent update on this issue.... anyway, i have been working in a solution, Looking for information about which spells should proc beacon, i found this:
[warmane holy paladin guide] (http://forum.warmane.com/showthread.php?t=325569)
```
Beacon of Light
This is the spell that we were given to help us deal with being able to heal multiple targets at the same time. It can be much better, or it can be worse, than other healer's AoE healing depending on the situation. The Beacon takes into account all healing, so it is very useful. It only works on Paladin healing abilities (ignoring Glyph of HL and trinkets)........
```
Wowhead comment
[wowhead](https://es.wowhead.com/spell=53563/se%C3%B1al-de-la-luz)
```
......Healing trinket from heroic magisters terrace does not proc it because you are not casting....
```
Then i assume that beacon of light only procs when paladin cast:
- Holy/Flash of light
- Lay on Hands
- Holy Shock

So far this are my results
- Move beacon code from Unit.cpp to a spell script (spell_paladin)
- Insert a "valid" spell proc in DB (spell_proc_event)

Can some1 pls give me a feedback @Andrei-UPB @Yehonal

Best regards guys

**Comment by Algorak** [comment]
The error still persists -.-
