### ISSUE TITLE
Malformed Packets

### ISSUE THREAD

**Issue by merdlin** [azerothcore/azerothcore-wotlk#2784]
Malformed Packets

##### SMALL DESCRIPTION:
Hi, I'm getting malformed packages at WorldSocket :: handle_input_header <>: I was wondering if anyone else has this?

##### CURRENT BEHAVIOUR:
WorldSocket

##### EXTRA NOTES:
No line of code has been changed, I have the latest version of Azerothcore.

##### OPERATING SYSTEM:
Windows Server 2016

##### MODULES:
Arena 1v1, Transmog

##### OTHER CUSTOMIZATIONS:
none

**Comment by Helias** [comment]
Probably someone is sending you some malformed packet and the server just ignores them notifying you this.

**Comment by merdlin** [comment]
thanks
