### ISSUE TITLE
Missing .reload battleground_template

### ISSUE THREAD

**Issue by ShinDarth** [azerothcore/azerothcore-wotlk#28]
The following command is missing:

`.reload battleground_template`

it would be nice to import it from TC

**Comment by Bodeguero** [comment]
@ShinDarth This command was implemented in TrinityCore in TDB335.11.55 version when it was implementing RBAC system - ideally we add this RBAC system as well. . . What about that?

**Comment by ShinDarth** [comment]
yes, it would be nice, can you help with that?

**Comment by HeartWell** [comment]
https://gist.github.com/HeartWell/64e87b6bd2b5f6509d9aa0558c47c5d4

**Comment by ShinDarth** [comment]
@HeartWell thanks, can you open PR please ?

**Comment by HeartWell** [comment]
@ShinDarth sorry, i dont use azeroth( plz can you open pr?

**Comment by Bodeguero** [comment]
@ShinDarth The team will implement RBAC system too?

**Comment by ShinDarth** [comment]
@Bodeguero yes I would like to implement it, but it is not really urgent so first I would like to focus to more urgent stuff. But you can start working on it and I can help you

**Comment by ShinDarth** [comment]
@HeartWell ok I will

**Comment by HeartWell** [comment]
@ShinDarth thanks)

**Comment by Bodeguero** [comment]
@ShinDarth Well I'll see what I can do, I was in the team JadeCore - more unfortunately out for reasons of being disorganized and set up my own team! One question this source of AzerothCore is better than the current TrinityCore?

**Comment by HeartWell** [comment]
@Bodeguero much better, but a little outdated in terms of standards.

**Comment by Bodeguero** [comment]
@HeartWell Well what I realized is that it has corrected some things and fixed the TrinityCore does not have such as Wintergrasp!

**Comment by ShinDarth** [comment]
One of the main goals of this project is to clean the code and update the core structure (partially already done comparing with the old sc sources).

About the @Bodeguero 's question "if this is better of TrinityCore", well I think there are pros and cons on both. First of all I wouldn't consider this project as totally separated from TrinityCore. This project is based on TrinityCore and it is my will to collaborate with both when possible. Another important goal of this project is to make the code as updated as possible with TrinityCore: the more they are similar, and the easier is to share useful things across the 2 projects (and that does not involve the cores only, but also any other external tool for them).

TrinityCore is much more popular and has a stronger community, cleaner code and also very experienced developers. Also I believe that TrintiyCore is a bit more stable than AzerothCore.
On the other hand, it's a matter of fact that AzerothCore is much more appreciated by the players, especially for all the contents inherited from SunwellCore (that's why more and more private servers are switching to sunwellcore/azerothcore).

We are basically trying to fill the gap between the original SunwellCore and TrinityCore ( making it cross-platform and adding the clang support was one of the first reached goals ), and as well as adding useful features for development ( like the modular system ideated by @Yehonal ). The more contributors we'll have, the sooner we can accomplish our goals reaching a great server applications under all points of view.

**Comment by Bodeguero** [comment]
@ShinDarth I understand - I will look at the structure and try to update the same to the new revision of trinitycore without losing anything of what was done in this source! I have managed to update old sources as the UnforgivenWoW it was in TC 48 version to the new review - it took me a few months to make it more able - try to see what I can do with this source!

**Comment by Blumfield** [comment]
@Bodeguero wow you sure have lots of hope hehe, good luck my friend

**Comment by Bodeguero** [comment]
@Blumfield 🤓 :neckbeard:

**Comment by ShinDarth** [comment]
@HeartWell can you send me your email? so I can set you as author of the commit
