### ISSUE TITLE
Melee Range is Bug 

### ISSUE THREAD

**Issue by Shahin-Diseases** [azerothcore/azerothcore-wotlk#2800]
according to this issue : https://github.com/azerothcore/azerothcore-wotlk/pull/2686

download this video file : https://www.mediafire.com/file/pevmky41sf311nf/wow_2020-03-24_19-51-58-558.avi/file

you will see anything you need in that video 

Rev: b868f0a

**Comment by Viste** [comment]
can you follow this: http://www.azerothcore.org/wiki/Contribute#how-to-open-an-issue and make issue more readable

**Comment by aradep** [comment]
This is related to the changes made in #2686. According to the feedback in the PR, as well as [my own testing](https://www.youtube.com/watch?v=yNbTu4CVXNY) and the fact that no other issues have been made about it since, I'm going to say it's in an acceptable state and close this.
