### ISSUE TITLE
Warlock Conflagrate Delay

### ISSUE THREAD

**Issue by Shahin-Diseases** [azerothcore/azerothcore-wotlk#2801]
found a bug on warlock's Conflagrate 
it has a delay after immolate 
check this Video : https://www.mediafire.com/file/qe9ekg6z9el33vi/wow_2020-03-24_20-52-45-407.avi/file

last Rev : http://github.com/azerothcore/azerothcore-wotlk/commit/b868f0ad04e78b180c721cf6b1c3820c513573e3

**Comment by lineagedr** [comment]
It's has an intended blizzlike delay: https://www.youtube.com/watch?v=KUizH_eVcuA&feature=youtu.be&t=209

**Comment by Shahin-Diseases** [comment]
Solved
