### ISSUE TITLE
gm rank 1 is enemy with players

### ISSUE THREAD

**Issue by V3nomAnc3r** [azerothcore/azerothcore-wotlk#2806]
##### SMALL DESCRIPTION:
gm rank 1 is enemy with players.
create new character horde rank 1, create new character alliance rank 0

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should not be an enemy

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/19144d8bff39b77f2618904c64bb75b56ae5e4c2

##### OPERATING SYSTEM:

windows 10

##### MODULES:

No

**Comment by IntelligentQuantum** [comment]
Try this https://paste.ubuntu.com/p/syqWpX5r8b/

**Comment by V3nomAnc3r** [comment]
tnx works perfect

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum @V3nomAnc3r the fix should be on master before closing the issue.

Can you open PR with it?
