### ISSUE TITLE
Command .debug send chatmmessage doesn't exist

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2808]
##### SMALL DESCRIPTION:

debug send chatmmessage doesn't exist (and it even looks like it has a typo lol)

##### CURRENT BEHAVIOUR:

It's in the DB, but it doesn't exist
It's also in the wiki.

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.debug send chatmmessage`
2. `.debug` it's in the list

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

fcc81ed

**Comment by BarbzYHOOL** [comment]
Ok, my issue is wrong, apparently it exists but there is 0 help for this command

When I type `.debug send chatmmessage "loool"` I get this in chat "testtest" wtff??

**Comment by AsunaFrostwyrm** [comment]
- you misunderstood how the command works
- thats exactly what the response of the command should be

How to use the command is exactly whats written in the wiki: 

> Syntax: .debug send chatmmessage #msgtype. Send a message “testtest” of type #msgtype.

The only thing you can change is the type of the message, not the content of the message.


The different types of the message can be looked up [here](https://github.com/azerothcore/azerothcore-wotlk/blob/e22d78ecd6997bc11f8620b759364f119dac431a/src/server/game/Miscellaneous/SharedDefines.h#L2996).

**Comment by BarbzYHOOL** [comment]
ok, i was more reading the ingame help than the wiki (and there is no help)

I got confused at "testtest" because it's something I write all the time, so I was like "maybe it's me who wrote testtest somewhere?"


Any practical example as to when this command is useful?

**Comment by AsunaFrostwyrm** [comment]
Well, you can test out how the different messagetypes look like ingame.

Try using the command with an integer from 1 - 53, for example:

`.debug send chatmmessage 6`

Then you get a preview of how the message looks like with the type "6" which is specified as "yelling".

**Comment by BarbzYHOOL** [comment]
interesting ty, we should add better description in DB and wiki tho
