### ISSUE TITLE
General channels' names are in lower case

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#282]
**Description**: General Channels' names are in lower case, it may also affect custom channels and more things related to chat

Happened to me (on enUS client) and to Sucofog (esES)

**Current behaviour**: Look at this screen shot:
https://cloud.githubusercontent.com/assets/734950/20062803/547595ea-a505-11e6-952f-fcd01c16d0f3.png -----> Azerothcore

**Expected behaviour**: It should be like this:
https://cloud.githubusercontent.com/assets/734950/20063857/f5aed6da-a508-11e6-83eb-6ec6727c0cfa.png ------> Trinitycore

**Branch(es)**: 1.x / master

**Modules**:  DuelReset - Anticheat by 3ndos

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by falzard** [comment]
Possible workaround in this commit  https://github.com/Exodius/MistCore/commit/864f923ddea822807f3e47834365c76758fd328b

**Comment by sucofog** [comment]
Thanks for opening issue @falzard im quite busy these days with work also with live server translating, :)

**Comment by falzard** [comment]
I tested sunwell.pl (which is mostly maczuga's repo) and the same bug happens there. I wonder if it happens with a polish client

**Comment by sucofog** [comment]
The workaround of MistCore it's useful becouse now we can load the channels server-side and not from DBC's, becouse now we're loading them from DBC's and we got this ugly bug.

**Comment by Yehonal** [comment]
If we don't have issues with channels localizations and it's just an issue with lowercase, i think we don't need MistCore workaround.

Even if i'm a fun of dbc porting to sql , i think that the solution is quite simple here ( i didn't tried it )


You can notice that on trinitycore they just differentiate custom channels ( that must be in lower case to avoid conflicts ) , between builtin. In fact builtin channels can have upper case letters.

Take a look at screenshots

TrinityCore
![image](https://cloud.githubusercontent.com/assets/147092/21311480/a84b4e14-c5e7-11e6-985c-f30f0ff686cc.png)

AzerothCore

![image](https://cloud.githubusercontent.com/assets/147092/21311515/e3593548-c5e7-11e6-9d99-1fce8f3a0665.png)

**Comment by falzard** [comment]
Thanks I'll check it out soon (didn't update for months)
