### ISSUE TITLE
[ToC Raid] Incorrect roleplay

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#2820]
##### SMALL DESCRIPTION:
After defeating the Twin Val'kyr in Trial of the Crusader, the following incorrect conversation takes place between the Lich King and Tirion Fordring:

Highlord Tirion Fordring yells: A mighty blow has been dealt to the Lich King! You have proven yourselves as able bodied champions of the Argent Crusade. Together we will strike against Icecrown Citadel and destroy what remains of the Scourge! There is no challenge that we cannot face united!
**_The Lich King yells: The Nerubians built an empire beneath the frozen wastes of Northrend. An empire that you so foolishly built your structures upon. MY EMPIRE._**
Highlord Tirion Fordring yells: Arthas! You are hopelessly outnumbered! Lay down Frostmourne and I will grant you a just death.
_**The Lich King yells: The Nerubians built an empire beneath the frozen wastes of Northrend. An empire that you so foolishly built your structures upon. MY EMPIRE.**_
The Lich King yells: The souls of your fallen champions will be mine, Fordring.

https://i.imgur.com/LMe9pmN.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The correct conversation/dialogue is this:

Highlord Tirion Fordring yells: A mighty blow has been dealt to the Lich King! You have proven yourselves as able bodied champions of the Argent Crusade. Together we will strike against Icecrown Citadel and destroy what remains of the Scourge! There is no challenge that we cannot face united!
**_The Lich King yells: You will have your challenge, Fordring._**
Highlord Tirion Fordring yells: Arthas! You are hopelessly outnumbered! Lay down Frostmourne and I will grant you a just death.
The Lich King yells: The Nerubians built an empire beneath the frozen wastes of Northrend. An empire that you so foolishly built your structures upon. MY EMPIRE.
The Lich King yells: The souls of your fallen champions will be mine, Fordring.

Video from Retail: https://www.youtube.com/watch?v=UW7VjpglECc

##### CURRENT BEHAVIOUR:

The Lich King repeats the following line twice:

**The Lich King yells: The Nerubians built an empire beneath the frozen wastes of Northrend. An empire that you so foolishly built your structures upon. MY EMPIRE.**

Small, but noticeable.  The correct line is present in the database but I believe the code is triggering the same line twice.

https://i.imgur.com/aL7xRfx.png

##### STEPS TO REPRODUCE THE PROBLEM:
1. Enter ToC on either normal/heroic 10 or 25 man
2. Clear the raid up to and including Twin Val'kyr
3. Wait for roleplay event and listen to boss audio/read chat log.

##### EXTRA NOTES:
N/A

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

1411336dcbbc

##### OPERATING SYSTEM:
Win10

##### MODULES:
N/A

##### OTHER CUSTOMIZATIONS:
Health increases on bosses, nothing else.

**Comment by AsunaFrostwyrm** [comment]
I also tested this and can confirm, that the LK is saying this line twice in the roleplay after the two valks are dead. Even the sound of the text is said twice. I will make a PR which fixes this.

**Comment by NizeGuy** [comment]
> 
> 
> I also tested this and can confirm, that the LK is saying this line twice in the roleplay after the two valks are dead. Even the sound of the text is said twice. I will make a PR which fixes this.
> 
> #Edit -> Forgot to say, that you were looking for the wrong creatureID in the creature_text table. The entry which is used in ToC isn't 16980, it is 35877.
> 
> For this CreatureID there are three rows in the creature_text table and two of them are similiar, GroupID 0 and GroupID 2.

I tested your fix.  It works.

**Comment by Helias** [comment]
@Voxstrasza, next time you test a PR comment it there not only in the issue ;-)
