### ISSUE TITLE
Vault of Archavon Bosses - Incorrect Scripts/Visuals/etc [$15]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#2823]
##### SMALL DESCRIPTION:
Emalon the Storm Watcher:  Adds do not respawn when they explode, but do respawn when killed via damage.  Video: https://youtu.be/OWqc-ayUNis

**FIXED BY #2868**  --  Toravon the Ice Watcher:  On 25-man, only one Frozen Orb spawns, and Whiteout is tied to the Frozen Orb death.  Ex: Kill a Frozen Orb, and Whiteout will be cast.  When multiple Frozen Orbs are killed, multiple Whiteout's will be casted on the raid.  Additionally, the visual for Whiteout is missing.  Video: https://youtu.be/R15BH1zM84M

Koralon the Flame Watcher:  When he casts Burning Breath, he faces one direction.  Video: https://youtu.be/Bdz3eYpeLJI

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Emalon the Storm Watcher:  Adds should respawn, regardless how they die - whether it is because they explode or because they are killed.

Toravon the Ice Watcher:  On 25-man difficulty, three Frozen Orbs should spawn.  The first Whiteout should be cast **24 seconds** after the initial pull, and then every **38 seconds** after that, and it should accompany a visual effect.  Retail video: https://youtu.be/VMsP_8F6BvQ

Koralon the Flame Watcher:  Burning Breath is an AoE ability, and Koralon should spin in place when he channels this.  Retail video: https://www.youtube.com/watch?v=Vgrw5_zPoOE

##### CURRENT BEHAVIOUR:
Emalon the Storm Watcher:  Currently, when adds explode, they will not respawn.  They will respawn if they are killed via damage.

Toravon the Ice Watcher:  Only one Frozen Orb spawns on 25-man difficulty.  Whiteout does not have a visual when it is used, and it is tied to a Frozen Orb dying.

Koralon the Flame Watcher:  When he uses Burning Breath, he faces a random direction and remains facing that way for the entire duration.

##### STEPS TO REPRODUCE THE PROBLEM:
1.   Enter Vault of Archavon on 25 man difficulty
2.   Pull Emalon the Storm Watcher
3.   Wait until he overcharges a Tempest Minion, and wait until it has 10 stacks of the debuff.  It will explode and not spawn again, leaving you with 3.  Kill the other 3, and the 3 will respawn.  There should be 4 throughout the entire encounter.
4.   Pull Koralon the Flame Watcher
5.  Wait until Burning Breath, notice he faces one direction.
6.  Pull Toravon the Ice Watcher.
7.  Wait until Frozen Orbs spawn, and kill them.  Toravon will then cast Whiteout multiple times, depending on how many Frozen Orbs you kill.  There will be no visual effect.

##### EXTRA NOTES:
N/A

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
1411336dcbbc

##### OPERATING SYSTEM:
Win 10

##### MODULES:
N/A

##### OTHER CUSTOMIZATIONS:
Modified health on bosses

**Comment by NizeGuy** [comment]
Upon further review and testing, it appears that killing a Frozen Orb also clears the Whiteout debuff.  This shouldn't reset, it should continuously stack per Whiteout cast until a wipe or the boss death.

**Comment by arthaswow** [comment]
Same problem, if anyone wants to test just ask-me a account
http://arthaswow.servegame.com

**Comment by Helias** [comment]
@arthaswow pm me on Discord or give me your discord username

**Comment by Voxstrasza** [comment]
#2868 fixes 1 out of 3 issues in this post

**Comment by UltraNix** [comment]
Made a PR. Please, review it.
