### ISSUE TITLE
[$15] Icecrown Citadel Raid - Lich King Incorrect Scripting + Weird Snapping [$15]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#2826]
##### SMALL DESCRIPTION:

Shadow Traps do not consider the Lich King tank a target.  Additionally, Lich King has a weird snapping motion to his North during phase transitions.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The tanks should be a viable target for Shadow Trap in Phase 1 Lich King Heroic.  The Lich King should _face_ (aka his target for Pain & Suffering) the raid during transitions while he's using Pain and Suffering.   

I could not find a video of the Lich King casting Shadow Trap on his target from 2010, but I don't believe it's changed from 2010 to 2013, see video of solo here: https://youtu.be/UcFY90Cs6Vw?t=45

Retail Transition (notice he is facing the raid): https://youtu.be/vMKPdq3on1k?t=139

##### CURRENT BEHAVIOUR:
The Lich King does not consider his target a candidate for Shadow Traps, and he does a weird snapping movement to the North after he casts Pain and Suffering:  https://youtu.be/LYPjzt-dW3Q

##### STEPS TO REPRODUCE THE PROBLEM:
1.  (It helps to have boss mod timers here)  Start the RP for Lich King, and wait for Shadow Trap timer.
2.  Phase Lich King to his first transition, and watch him while he casts Pain & Suffering.  He will snap to the North and only face you when he's casting Pain and Suffering on you.

##### EXTRA NOTES:
N/A

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
1411336dcbbc

##### OPERATING SYSTEM:
Win10

##### MODULES:
N/A

##### OTHER CUSTOMIZATIONS:
Increased health modifiers on bosses

**Comment by Voxstrasza** [comment]
In regards to the Lich King issue, the problem lies in the script:

```
  switch (pointId)
                {
                    case POINT_CENTER_1:
                        me->SetFacingTo(0.0f);
                        Talk(SAY_LK_REMORSELESS_WINTER);
                        me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                        me->CastSpell(me, SPELL_REMORSELESS_WINTER_1, false);
                        //events.DelayEvents(62500, EVENT_GROUP_BERSERK); // delay berserk timer, its not ticking during phase transitions, bullshit, 15mins on movies
                        events.ScheduleEvent(EVENT_QUAKE, 62500);
                        events.ScheduleEvent(EVENT_PAIN_AND_SUFFERING, 3500, EVENT_GROUP_ABILITIES);
                        events.ScheduleEvent(EVENT_SUMMON_ICE_SPHERE, 8000, EVENT_GROUP_ABILITIES);
                        events.ScheduleEvent(EVENT_SUMMON_RAGING_SPIRIT, 4000, EVENT_GROUP_ABILITIES);
                        break;
                    case POINT_CENTER_2:
                        me->SetFacingTo(0.0f);
                        Talk(SAY_LK_REMORSELESS_WINTER);
                        me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_SPECIAL);
                        me->CastSpell(me, SPELL_REMORSELESS_WINTER_2, false);
                        summons.DespawnEntry(NPC_VALKYR_SHADOWGUARD);
                        //events.DelayEvents(62500, EVENT_GROUP_BERSERK); // delay berserk timer, its not ticking during phase transitions, bullshit, 15 mins on movies
                        events.ScheduleEvent(EVENT_QUAKE_2, 62500);
                        events.ScheduleEvent(EVENT_PAIN_AND_SUFFERING, 3500, EVENT_GROUP_ABILITIES);
                        events.ScheduleEvent(EVENT_SUMMON_ICE_SPHERE, 8000, EVENT_GROUP_ABILITIES);
                        events.ScheduleEvent(EVENT_SUMMON_RAGING_SPIRIT, 4000, EVENT_GROUP_ABILITIES);
                        break;
                    default:
                        break;
                }
            }
```

I'm not exactly sure how to modify `me->SetFacingTo(0.0f);` so that he is facing his Pain & Suffering target

**Comment by Voxstrasza** [comment]
[bounty](https://www.bountysource.com/issues/90892586-icecrown-citadel-raid-intro-error-saurfang-rp-lich-king-incorrect-scripting-weird-snapping-dalaran-fountain)

**Comment by Voxstrasza** [comment]
bump

**Comment by Voxstrasza** [comment]
bump

**Comment by Kitzunu** [comment]
It's not likely to be worked on by anyone since it has multiple bugs in one issue

**Comment by Voxstrasza** [comment]
> 
> 
> It's not likely to be worked on by anyone since it has multiple bugs in one issue

Okay, I'll repost as individual.

**Comment by Voxstrasza** [comment]
sfdfd

**Comment by Voxstrasza** [comment]
Bump, edited issue to reflect just one - bounty will remain on the above.
