### ISSUE TITLE
[core/loot]loot BUG

### ISSUE THREAD

**Issue by kuramajssken001** [azerothcore/azerothcore-wotlk#2828]
**SMALL DESCRIPTION**:
Players who are not in combat should not have access to loot.
Also, the player will be able to acquire equipment without infecting the dungeon CD.
My English is very poor. I'm sorry.
If you don't get what I'm saying, check out the video below.

**BRANCH(ES):**
master

**AC HASH/COMMIT:**
633ef83b47851c5d78176f16525c623879f0dd39
**DEMO:**
https://youtu.be/002JF2gUgYw

**Comment by Kitzunu** [comment]
Dup of https://github.com/azerothcore/azerothcore-wotlk/issues/2104

**Comment by pklloveyou** [comment]
As long as the loot before entering the instance,you can ROLL, this is wrong.

**Comment by Si1ker** [comment]
@kuramajssken001 Thanks for your report, however, I am closing this issue due to is duplicity with the issue #2104 

Thanks, @Kitzunu for pointing it out.
