### ISSUE TITLE
[Quest] "The Assassination of Harold Lane" Bugged

### ISSUE THREAD

**Issue by Axaxxax** [azerothcore/azerothcore-wotlk#2831]
##### SMALL DESCRIPTION:
Character killing does not count

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After killing a character, the quest must be considered completed.

##### CURRENT BEHAVIOUR:
During the quest you must kill a character
Harold Lane, then get the reward. 
https://www.wowhead.com/quest=11892/the-assassination-of-harold-lane

##### STEPS TO REPRODUCE THE PROBLEM:

1. GUID NPC 115091
2. .go 3301.399902 5694.100098 60.090698
3. add quest 11892 and kill npc, see what happen

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
19c3a70

##### OPERATING SYSTEM:
Windows 10 x64

##### MODULES:

- Auctionhouse Bot

- 1v1 Arena

- transmog

- cfbg

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/79036001-fce61e00-7bc3-11ea-8c70-71858ae9fa65.png)
I cannot reproduce this

**Comment by LukasVolgger** [comment]
Cannot reproduce this issue on commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4

![image](https://user-images.githubusercontent.com/55922592/100499570-e6003600-316a-11eb-818b-971157824ed9.png)
