### ISSUE TITLE
New feature: GM Commands aliases

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2834]
This is a new feature for all gm commands.
A new table "command_aliases" where we can create aliases for each command. We can then fix common typos, can add different language for commands, and we can even use this instead of renaming existing commands when they have horrible names.

Tables:

```
command                                 (why is it singular form -__-)
-----------------------
id    | name      | ...
-----------------------
145 | account | ....
```
```
command_aliases
-----------------------
id    | alias
---------------
145 | acount
145 | test

id = smallint
alias = varchar 255
primary/unique key = id + alias  (or use a guid column as primary key)
```

Result: these 3 commands do the same thing:
```
.account
.acount
.test
```

**Comment by P-Kito** [comment]
https://github.com/P-Kito/azerothcore-wotlk/commit/58a4cb0f5d1df69cecfb660236d52e06c04d45b5

I started doing some stuff, it translates some of the aliases, but I have no clue why it crashes on certain others...

maybe it has been a too long day for me xD

(My assumption is the size_t pos, size_t len part, where it should replace the alias with the "real" command)

**Comment by P-Kito** [comment]
im dump, because .find() return nothing
Yes it has been late. I will maybe correct that tomorrow xD

**Comment by BarbzYHOOL** [comment]
ok

**Comment by Kitzunu** [comment]
Don't see the purpose of this

**Comment by BarbzYHOOL** [comment]
"We can then fix common typos, can add different language for commands, and we can even use this instead of renaming existing commands when they have horrible names."
