### ISSUE TITLE
Pet/PVP - just attacking with pet causes the target to be in combat

### ISSUE THREAD

**Issue by arenacraftwow** [azerothcore/azerothcore-wotlk#2838]
Just attacking with pet causes the target to be in combat

##### SMALL DESCRIPTION:

In PVP if a player sends his pet to attack you, you will get combat, instantly. However you should only get combat once the pet hits you. This is a game breaking issue for stealth classes becasue it means that they can never restealth vs a pet class. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If a player sends his pet after you, you should not get combat. Only after you get hit by the pet (melee, or the pets spell).

##### CURRENT BEHAVIOUR:

Currently if a player sends his pet after you, you will get combat instantly. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make 2 characters, I've tested with  a rogue and a frost mage
2. Duel each other
3. optional: Make the pet go LoS (this bugs out even thru LoS, making it doubly bad for PvP).
4. optional: have a combat identicator addon  (or get other means of determining combat)
5. make the mage's pet attack the rogue
6.  notice the rogue has combat as soon as you make the pet chase the rogue, no matter if the pet is behind the LoS or far away. 

![image](https://user-images.githubusercontent.com/61932925/78357690-2e525e80-75b2-11ea-9463-57a5404a0042.png)
 

##### EXTRA NOTES:

I only know about PVP, but I suspect this issue applies to PVE as well. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

d85f2aa6ffb572123edc613c3ed4124721ae75e2

##### OPERATING SYSTEM:

Arch linux

##### MODULES:

```
mod-duel-reset
mod-learn-spells 
mod-npc-talent-template
mod-learn-highest-talent 
mod-npc-services
```

##### OTHER CUSTOMIZATIONS:

https://github.com/arenacraftwow/azerothcore-wotlk some customizations but I don't think its related.

**Comment by arenacraftwow** [comment]
Actaully this appears to be working properly in PVE.

**Comment by Viste** [comment]
try revert https://github.com/azerothcore/azerothcore-wotlk/commit/3cf3f69e135f6751c4a5910528dfefaf7ba9fff2

**Comment by arenacraftwow** [comment]
@Viste It's not an issue with melee stuff in particular. Casting waterbolt also insta triggers combat.

**Comment by Viste** [comment]
ok thanks

**Comment by arenacraftwow** [comment]
Ok Im still looking into it, its weird. I can't reproduce this issue with a warlock pet.

**Comment by arenacraftwow** [comment]
Ok after looking into this issue deeper I've noticed that the issue goes away if you use the eternal water glyph (making water elem perma). 

Additionally I've tested shadow fiend and it has the same issue. 

This means that there is a problem with Pets that are temporary but controlled.

**Comment by Si1ker** [comment]
@arenacraftwow 

Please, try with ghoul of a dk without talent point and using a controlled demon with a warlock.
Let me know.

**Comment by arenacraftwow** [comment]
@Si1ker 

>Please, try with ghoul of a dk without talent point

I know what you are getting at. I've tried it already but a uncontrolled ghoul can't get bugged, why? Well becasue in order to get it attacking I have to attack myself (which will make the target in combat already).

>Ghoul from a dk WITH talent point to make it permanent

Then it works properly. 

As for the rest I will let u know soon, since I'm testing it at this moment.

**Comment by arenacraftwow** [comment]
@Si1ker
 Enslaved demon = bugs 
 Summoned demon = fine

**Comment by arenacraftwow** [comment]
I think I've figured it out. The issue is due to a branch of code that checks for `IsPet()`. With working pets it returns true however with temporary pets it returns false.

**Comment by arenacraftwow** [comment]
Alrigt actually I guess that branch of code should just use `IsSummon()` instead of `IsPet()`. Will make a PR soon.

**Comment by laasker** [comment]
i think this can be closed, was fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/8877 and https://github.com/azerothcore/azerothcore-wotlk/pull/7315
