### ISSUE TITLE
Checkbox on the DK spell book

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2843]
##### SMALL DESCRIPTION:

We have the checkbox in the DK spell book to display the ranks

##### EXPECTED BLIZZLIKE BEHAVIOUR:

we mustn't have a checkbox in the DK's book of spells. Like warriors, thieves or any other class to whom spells do not change the amount of resource to be used.

##### CURRENT BEHAVIOUR:

We have the checkbox in the DK spell book to display the ranks

##### STEPS TO REPRODUCE THE PROBLEM:

1. create DK
2. look your spells book
3. 

##### BRANCH(ES): 

master

##### OPERATING SYSTEM:

Ubuntu server 18.04

**Comment by Maurowin** [comment]
I think we doen't need feedback for that, is not game breaker and logical with respect to other classes that do not have a change in the amount of resource to use an ability.

**Comment by Whistl3r** [comment]
Hello, unfortunately it can break DK I suppose, because then Death Strike (45470) is visible and I can click it and it instantly heals without global cooldown as many times as I want.

It may be caused by me customising server to my requirements but I am not touching the core at all. I have looked already to my scripts which autolearn spells on insta 80lvl and I am not making mistake there by learning it accidentally.

![image](https://user-images.githubusercontent.com/29665551/100251319-e916de80-2f3e-11eb-8d1b-76dd3998fe87.png)

**Comment by Whistl3r** [comment]
Could someone point me into direction where I can find data/settings regarding spell book ? Or should I have a look into class specific settings? I already tried to find it but without luck.

**Comment by Maurowin** [comment]
Do u see, u havent rank on it.

**Comment by Whistl3r** [comment]
ah thanks, I'm new into this stuff :) will have a look at it today

**Comment by Anhedonie-Shanrai** [comment]
Can't confirm. 
Neither on newly created Death Knights, nor on lvl 80 Death Knights does this appear when clicking the option "Show all spell ranks" - tested for enUS & deDE. 
Running AC from 30.03.21. 
![DS](https://user-images.githubusercontent.com/82074951/114250252-6ba7b400-999d-11eb-8486-4c2413b2905e.PNG)

**Comment by Maurowin** [comment]
That is why this checkbox must be removed.
There is no rank to display like all energy, rage etc.. classes

**Comment by Maurowin** [comment]
> 
> 
> Hello, unfortunately it can break DK I suppose, because then Death Strike (45470) is visible and I can click it and it instantly heals without global cooldown as many times as I want.
> 
> It may be caused by me customising server to my requirements but I am not touching the core at all. I have looked already to my scripts which autolearn spells on insta 80lvl and I am not making mistake there by learning it accidentally.
> 
> ![image](https://user-images.githubusercontent.com/29665551/100251319-e916de80-2f3e-11eb-8d1b-76dd3998fe87.png)

If you can click forever without consuming any resource and without GCD, it's cheating, it's a spell that should not be available to players.

**Comment by Anhedonie-Shanrai** [comment]
> If you can click forever without consuming any resource and without GCD, it's cheating, it's a spell that should not be available to players.
But that's the point: It isn't available - see my screenshot. Are you sure there is no custom modification you made caused this? Have you tried this on a "clean" AC, without any custom mods (mods in the AC repo should be ok).

**Comment by Maurowin** [comment]
maybe u right, which means it's either an oversight by blizzard or they're stupid

**Comment by claudiodfc** [comment]
## Feedback: Not a bug

I created a Death knight and they don't learn Death Strike until level 56. Went to the trainer, raised a level and modified money to learn the spell and this is my spell book afterwards:

![image](https://user-images.githubusercontent.com/54484196/122679729-e71ab280-d1e3-11eb-92af-712b50ea5edb.png)


The only way you've got access to spells like this is using the **Gamemaster command** ```.learn all my spells``` which players don't have access to.
