### ISSUE TITLE
Bug Dungeon

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#2846]
![WoWScrnShot_040420_234412](https://user-images.githubusercontent.com/52524476/78459668-f3dee380-76cf-11ea-8367-b89a7c5b0758.jpg)
![WoWScrnShot_040420_234415](https://user-images.githubusercontent.com/52524476/78459678-fe00e200-76cf-11ea-9566-7868229916b4.jpg)
![WoWScrnShot_040420_234509](https://user-images.githubusercontent.com/52524476/78459687-02c59600-76d0-11ea-8967-7597b060993b.jpg)
![WoWScrnShot_040420_234523](https://user-images.githubusercontent.com/52524476/78459692-078a4a00-76d0-11ea-8ccc-4fddcd841c1b.jpg)
![WoWScrnShot_040420_234655](https://user-images.githubusercontent.com/52524476/78459696-0ce79480-76d0-11ea-84bc-c37905507282.jpg)
![WoWScrnShot_040420_234714](https://user-images.githubusercontent.com/52524476/78459700-12dd7580-76d0-11ea-8f5c-759ae416b02e.jpg)
![WoWScrnShot_040420_234402](https://user-images.githubusercontent.com/52524476/78459707-183ac000-76d0-11ea-89f7-4274d90808e1.jpg)
Hi, first of all, we are entering this Drak'Tharon Keep
The first bass that we kill, then the last bass of Target, which we do with Pat Shaman, brings it to him.
This is from the bug ins

**Comment by LukasVolgger** [comment]
Hello there, please use the issue template and complete all data, especially the commit hash.

**Comment by meisam3505** [comment]
duplicate issue

**Comment by LukasVolgger** [comment]
Thx @meisam3505! 

@poryagholami  you already opened the issue here #2401 
Closing this
