### ISSUE TITLE
[Bug][Fix included][Core]

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#2848]
![WoWScrnShot_040520_000710](https://user-images.githubusercontent.com/52524476/78459956-27227200-76d2-11ea-8fad-6e39b1f81025.jpg)
![WoWScrnShot_040520_000722](https://user-images.githubusercontent.com/52524476/78459957-2c7fbc80-76d2-11ea-8f22-4ffd3aefd52d.jpg)
![WoWScrnShot_040520_000741](https://user-images.githubusercontent.com/52524476/78459958-31447080-76d2-11ea-9dfb-2f7c78a555e4.jpg)
![WoWScrnShot_040520_001050](https://user-images.githubusercontent.com/52524476/78459963-34d7f780-76d2-11ea-9037-bf834b8936af.jpg)
![WoWScrnShot_040520_001103](https://user-images.githubusercontent.com/52524476/78459967-39041500-76d2-11ea-8136-89e3596bc04d.jpg)
Hi, there is a problem, we are entering this and we are throwing these skeletons or any other creature into the wall or the ground with this lull of Shaman or Druid that we throw away.

**Comment by LukasVolgger** [comment]
Same as #2847.
Please add commit hash and further informations to your issues in future. 

Closing this
