### ISSUE TITLE
fix(DB/characters/mail) Mail 'id' duplicate entry

### ISSUE THREAD

**Issue by Axaxxax** [azerothcore/azerothcore-wotlk#2849]
fix(DB/characters/mail) Mail 'id' duplicate entry

##### SMALL DESCRIPTION:

The item store on my site creates an id for the letter in the game so that the player receives his things, but the server does not see the id of the letter created by the site and tries to enter a new mail in its place.

2020-04-04 23:19:11 SQL(p): INSERT INTO mail(id, messageType, stationery, mailTemplateId, sender, receiver, subject, body, has_items, expire_time, deliver_time, money, cod, checked) VALUES (260, 2, 62, 0, 1, 120, '873:0:1:6:1', '              76:4486920:4486920:0:0', 1, 1593800351, 1586024351, 0, 0, 4)
 [ERROR]: [1062] Duplicate entry '260' for key 'PRIMARY'
2020-04-04 23:19:11 [Warning] Transaction aborted. 5 queries not executed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If id 1,2,3,4,5 where is 4 id of the letter created by the site, and the letter sent by the player or auction will be id 5

##### CURRENT BEHAVIOUR:

Letters to DB character-mail are formed with the correct id (1,2,3,4,5,6) if from my site there is a request to add a letter at the time of purchase, the server will try to overwrite it. As a result, the item purchased by the player will disappear from his letter \ inventory when re-entering on character

##### STEPS TO REPRODUCE THE PROBLEM:

1. Through a request, add a letter to DB/characters/mail("INSERT INTO mail SET id = ?,messageType = ?,stationery = ?,mailTemplateId = ?,receiver = ?,subject = ?,body = ?,has_items = ?,expire_time = ?,deliver_time = ?,money = ?")
2. send a letter to another character so that it is added to the DB and see an error in the server console: [ERROR]: [1062] Duplicate entry '260' for key 'PRIMARY'
3. After attachment 1 letters will disappear or change

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Windows 10 x64

##### MODULES:

ah mod
1v1 arena
cfbg
transmog

**Comment by Axaxxax** [comment]
no one knows how to fix this problem?

**Comment by Helias** [comment]
There is a conflict of ID, you should delegate the server to create the new ID of the mail using SOAP (probably).
You should not create new IDs by 3rd tools but manage it from the server.

@Bogir met a similar issues, may he can helps.

**Comment by Axaxxax** [comment]
@Helias  thanks for your advice, I tried to execute the command to send things via acSOAP, but when I try to bind my ip host SOAP, the server says that it can’t use my ip for SOAP, when installing 0.0.0.0, as I understand it, it sets 127.0.0.1. I would be very grateful if ever someone created detailed instructions for setting up soap for the server

**Comment by Helias** [comment]
What is the matter exactly?
if you run a local server you can test SOAP with this guide:
https://stackoverflow.com/questions/59382665/how-to-send-commands-using-soap-to-azerothcore-worldserver-console

**Comment by Bogir** [comment]
This problem can be solved if we will disable to manage mail's IDs in server's memory. Server MUST make new mail ID after checking highest mail ID in db and assign +1 to new mail created by server
