### ISSUE TITLE
worldserver crashed

### ISSUE THREAD

**Issue by retrydev** [azerothcore/azerothcore-wotlk#285]
**Description**: worldserver crashed

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1.

--- DEBUG: --- START

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff47ff700 (LWP 9455)]
[Thread 0x7ffff47ff700 (LWP 9455) exited]
[New Thread 0x7ffff47ff700 (LWP 9456)]
[New Thread 0x7ffff37ff700 (LWP 9457)]
[New Thread 0x7ffff1fff700 (LWP 9458)]
[New Thread 0x7fffbffff700 (LWP 9463)]
[New Thread 0x7fffab3ff700 (LWP 9464)]
[New Thread 0x7fffaa3ff700 (LWP 9465)]
[New Thread 0x7fffa93ff700 (LWP 9466)]
[Thread 0x7fffaa3ff700 (LWP 9465) exited]
[New Thread 0x7fffa83ff700 (LWP 9467)]
[New Thread 0x7fffa73ff700 (LWP 9468)]
[New Thread 0x7fffa6bfe700 (LWP 9469)]

Program received signal SIGCONT, Continued.
[Switching to Thread 0x7ffff47ff700 (LWP 9456)]
pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185	../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: Нет такого файла или каталога.

--- DEBUG: BACKTRACE FULL

#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00007ffff746ca0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.2.8.so
No symbol table info available.
#2  0x00000000009fab2f in wait_not_empty_cond (timeout=<optimized out>, this=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1778
No locals.
#3  ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4823140, first_item=@0x7ffff47fede8: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1970
        ace_mon = {lock_ = 0x7ffff4823190, owner_ = <optimized out>}
#4  0x00007ffff7453e65 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
No symbol table info available.
#5  0x0000000000ff4ccb in DatabaseWorker::svc (this=0x7ffff48710c0) at /home/retry/azeroth/modules/worldengine/nucleus/src/Database/DatabaseWorker.cpp:30
        request = 0x7ffff4817eb0
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
No symbol table info available.
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
No symbol table info available.
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
No symbol table info available.
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7ffff47ff700) at pthread_create.c:309
        __res = <optimized out>
        pd = 0x7ffff47ff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737295415040, 5320941640694351243, 1, 140737295562592, 17, 140737295415040, -5320966930030672501, -5320963089876531829}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

--- DEBUG: INFO REGISTERS

rax            0xfffffffffffffe00	-512
rbx            0x0	0
rcx            0xffffffffffffffff	-1
rdx            0x3	3
rsi            0x80	128
rdi            0x7ffff48231cc	140737295561164
rbp            0x0	0x0
rsp            0x7ffff47fed50	0x7ffff47fed50
r8             0x7ffff4823100	140737295560960
r9             0x1	1
r10            0x0	0
r11            0x246	582
r12            0x7ffff48231c8	140737295561160
r13            0x7ffff4823190	140737295561104
r14            0x7ffff47fede8	140737295412712
r15            0x7ffff47ff700	140737295415040
rip            0x7ffff63d308f	0x7ffff63d308f <pthread_cond_wait@@GLIBC_2.3.2+191>
eflags         0x246	[ PF ZF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

--- DEBUG: CALLS (x/32i $pc)

=> 0x7ffff63d308f <pthread_cond_wait@@GLIBC_2.3.2+191>:	mov    (%rsp),%edi
   0x7ffff63d3092 <pthread_cond_wait@@GLIBC_2.3.2+194>:	callq  0x7ffff63d5750 <__pthread_disable_asynccancel>
   0x7ffff63d3097 <pthread_cond_wait@@GLIBC_2.3.2+199>:	mov    0x8(%rsp),%rdi
   0x7ffff63d309c <pthread_cond_wait@@GLIBC_2.3.2+204>:	mov    $0x1,%esi
   0x7ffff63d30a1 <pthread_cond_wait@@GLIBC_2.3.2+209>:	xor    %eax,%eax
   0x7ffff63d30a3 <pthread_cond_wait@@GLIBC_2.3.2+211>:	lock cmpxchg %esi,(%rdi)
   0x7ffff63d30a7 <pthread_cond_wait@@GLIBC_2.3.2+215>:	jne    0x7ffff63d318d <pthread_cond_wait@@GLIBC_2.3.2+445>
   0x7ffff63d30ad <pthread_cond_wait@@GLIBC_2.3.2+221>:	mov    0x2c(%rdi),%edx
   0x7ffff63d30b0 <pthread_cond_wait@@GLIBC_2.3.2+224>:	mov    0x18(%rdi),%rax
   0x7ffff63d30b4 <pthread_cond_wait@@GLIBC_2.3.2+228>:	mov    0x10(%rdi),%r9
   0x7ffff63d30b8 <pthread_cond_wait@@GLIBC_2.3.2+232>:	cmp    0x4(%rsp),%edx
   0x7ffff63d30bc <pthread_cond_wait@@GLIBC_2.3.2+236>:	jne    0x7ffff63d30ce <pthread_cond_wait@@GLIBC_2.3.2+254>
   0x7ffff63d30be <pthread_cond_wait@@GLIBC_2.3.2+238>:	cmp    0x18(%rsp),%r9
   0x7ffff63d30c3 <pthread_cond_wait@@GLIBC_2.3.2+243>:	jbe    0x7ffff63d312e <pthread_cond_wait@@GLIBC_2.3.2+350>
   0x7ffff63d30c5 <pthread_cond_wait@@GLIBC_2.3.2+245>:	cmp    %rax,%r9
   0x7ffff63d30c8 <pthread_cond_wait@@GLIBC_2.3.2+248>:	jbe    0x7ffff63d312e <pthread_cond_wait@@GLIBC_2.3.2+350>
   0x7ffff63d30ca <pthread_cond_wait@@GLIBC_2.3.2+250>:	incq   0x18(%rdi)
   0x7ffff63d30ce <pthread_cond_wait@@GLIBC_2.3.2+254>:	subl   $0x2,0x28(%rdi)
   0x7ffff63d30d2 <pthread_cond_wait@@GLIBC_2.3.2+258>:	cmpq   $0xffffffffffffffff,0x8(%rdi)
   0x7ffff63d30d7 <pthread_cond_wait@@GLIBC_2.3.2+263>:	jne    0x7ffff63d3107 <pthread_cond_wait@@GLIBC_2.3.2+311>
   0x7ffff63d30d9 <pthread_cond_wait@@GLIBC_2.3.2+265>:	mov    0x28(%rdi),%eax
   0x7ffff63d30dc <pthread_cond_wait@@GLIBC_2.3.2+268>:	and    $0xfffffffe,%eax
   0x7ffff63d30df <pthread_cond_wait@@GLIBC_2.3.2+271>:	jne    0x7ffff63d3107 <pthread_cond_wait@@GLIBC_2.3.2+311>
   0x7ffff63d30e1 <pthread_cond_wait@@GLIBC_2.3.2+273>:	add    $0x28,%rdi
   0x7ffff63d30e5 <pthread_cond_wait@@GLIBC_2.3.2+277>:	cmpq   $0xffffffffffffffff,-0x8(%rdi)
   0x7ffff63d30ea <pthread_cond_wait@@GLIBC_2.3.2+282>:	mov    $0x1,%edx
   0x7ffff63d30ef <pthread_cond_wait@@GLIBC_2.3.2+287>:	mov    $0x1,%eax
   0x7ffff63d30f4 <pthread_cond_wait@@GLIBC_2.3.2+292>:	mov    $0x81,%esi
   0x7ffff63d30f9 <pthread_cond_wait@@GLIBC_2.3.2+297>:	cmove  %eax,%esi
   0x7ffff63d30fc <pthread_cond_wait@@GLIBC_2.3.2+300>:	mov    $0xca,%eax
   0x7ffff63d3101 <pthread_cond_wait@@GLIBC_2.3.2+305>:	syscall 
   0x7ffff63d3103 <pthread_cond_wait@@GLIBC_2.3.2+307>:	sub    $0x28,%rdi

--- DEBUG: THREAD APPLY ALL BACKTRACE

Thread 12 (Thread 0x7fffa6bfe700 (LWP 9469)):
#0  0x00007ffff58e2623 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff747b762 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#2  0x00007ffff747cb9c in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.2.8.so
#3  0x00007ffff747e1bb in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#4  0x00007ffff74bc5e2 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.2.8.so
#5  0x0000000000d7c64e in ReactorRunnable::svc (this=0x7fffab64a6b8) at /home/retry/azeroth/src/game/Server/WorldSocketMgr.cpp:158
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7fffa6bfe700) at pthread_create.c:309
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 11 (Thread 0x7fffa73ff700 (LWP 9468)):
#0  0x00007ffff58e2623 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff747b762 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#2  0x00007ffff747cb9c in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.2.8.so
#3  0x00007ffff747e1bb in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#4  0x00007ffff74bc5e2 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.2.8.so
#5  0x0000000000d7c64e in ReactorRunnable::svc (this=0x7fffab64a588) at /home/retry/azeroth/src/game/Server/WorldSocketMgr.cpp:158
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7fffa73ff700) at pthread_create.c:309
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 10 (Thread 0x7fffa83ff700 (LWP 9467)):
#0  0x00007ffff63d618d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000ffb846 in sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/4.9/thread:282
#2  ACORE::Thread::Sleep (msecs=msecs@entry=1000) at /home/retry/azeroth/modules/worldengine/nucleus/src/Threading/Threading.cpp:104
#3  0x0000000000a02e60 in FreezeDetectorRunnable::run (this=0x7fffab6f56e0) at /home/retry/azeroth/src/worldserver/Master.cpp:104
#4  0x00007ffff6172970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff63cf0a4 in start_thread (arg=0x7fffa83ff700) at pthread_create.c:309
#6  0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 9 (Thread 0x7fffa93ff700 (LWP 9466)):
#0  0x00007ffff63d618d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000ffb846 in sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/4.9/thread:282
#2  ACORE::Thread::Sleep (msecs=msecs@entry=1) at /home/retry/azeroth/modules/worldengine/nucleus/src/Threading/Threading.cpp:104
#3  0x00000000009fd2d8 in AuctionListingRunnable::run (this=<optimized out>) at /home/retry/azeroth/src/worldserver/WorldThread/WorldRunnable.cpp:121
#4  0x00007ffff6172970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff63cf0a4 in start_thread (arg=0x7fffa93ff700) at pthread_create.c:309
#6  0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 7 (Thread 0x7fffab3ff700 (LWP 9464)):
#0  0x00007ffff63d618d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000ffb846 in sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/include/c++/4.9/thread:282
#2  ACORE::Thread::Sleep (msecs=<optimized out>) at /home/retry/azeroth/modules/worldengine/nucleus/src/Threading/Threading.cpp:104
#3  0x00000000009fd88e in WorldRunnable::run (this=<optimized out>) at /home/retry/azeroth/src/worldserver/WorldThread/WorldRunnable.cpp:54
#4  0x00007ffff6172970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff63cf0a4 in start_thread (arg=0x7fffab3ff700) at pthread_create.c:309
#6  0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 6 (Thread 0x7fffbffff700 (LWP 9463)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746ca0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.2.8.so
#2  0x00000000009fab2f in wait_not_empty_cond (timeout=<optimized out>, this=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1778
#3  ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff2114600, first_item=@0x7fffbfffede8: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1970
#4  0x00007ffff7453e65 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#5  0x0000000000ffac77 in DelayExecutor::svc (this=0x7ffff2114570) at /home/retry/azeroth/modules/worldengine/nucleus/src/Threading/DelayExecutor.cpp:48
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7fffbffff700) at pthread_create.c:309
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 5 (Thread 0x7ffff1fff700 (LWP 9458)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746ca0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.2.8.so
#2  0x00000000009fab2f in wait_not_empty_cond (timeout=<optimized out>, this=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1778
#3  ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff48233c0, first_item=@0x7ffff1ffede8: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1970
#4  0x00007ffff7453e65 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#5  0x0000000000ff4ccb in DatabaseWorker::svc (this=0x7ffff27fe660) at /home/retry/azeroth/modules/worldengine/nucleus/src/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7ffff1fff700) at pthread_create.c:309
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7ffff37ff700 (LWP 9457)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746ca0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.2.8.so
#2  0x00000000009fab2f in wait_not_empty_cond (timeout=<optimized out>, this=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1778
#3  ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4823280, first_item=@0x7ffff37fede8: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1970
#4  0x00007ffff7453e65 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#5  0x0000000000ff4ccb in DatabaseWorker::svc (this=0x7ffff48717a0) at /home/retry/azeroth/modules/worldengine/nucleus/src/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7ffff37ff700) at pthread_create.c:309
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7ffff47ff700 (LWP 9456)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746ca0d in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.2.8.so
#2  0x00000000009fab2f in wait_not_empty_cond (timeout=<optimized out>, this=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1778
#3  ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4823140, first_item=@0x7ffff47fede8: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1970
#4  0x00007ffff7453e65 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.2.8.so
#5  0x0000000000ff4ccb in DatabaseWorker::svc (this=0x7ffff48710c0) at /home/retry/azeroth/modules/worldengine/nucleus/src/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cd01d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.2.8.so
#7  0x00007ffff74ce4f6 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.2.8.so
#8  0x00007ffff74ce41d in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.2.8.so
#9  0x00007ffff63cf0a4 in start_thread (arg=0x7ffff47ff700) at pthread_create.c:309
#10 0x00007ffff58e204d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7ffff7fe6780 (LWP 9451)):
#0  0x00007ffff63d04db in pthread_join (threadid=140736066483968, thread_return=0x0) at pthread_join.c:92
#1  0x00007ffff6172837 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000ffb77a in ACORE::Thread::wait (this=this@entry=0x7fffffffe9e0) at /home/retry/azeroth/modules/worldengine/nucleus/src/Threading/Threading.cpp:46
#3  0x0000000000a02625 in Master::Run (this=0x7ffff4818208) at /home/retry/azeroth/src/worldserver/Master.cpp:281
#4  0x00000000009e5efa in main (argc=<optimized out>, argv=<optimized out>) at /home/retry/azeroth/src/worldserver/Main.cpp:149

--- DEBUG: --- STOP

2. 
3. 

**Branch(es)**:  1.0.2

**AC hash/commit**: 

**Operating system**:  Debian 8.5 amd64

**Modules**:  Are you using modules? if yes, list them 

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
No offence but isn't it quite obvious that those fields need to be replaced and filled ?

```
Branch(es): 0.x / 1.x / master (Specify the branch(es) affected by this issue)

AC hash/commit:

Operating system:

Modules: Are you using modules? if yes, list them

Other Customizations: Are you use core/db patches or other customizations? If yes please specify them here.
```

**Comment by Yehonal** [comment]
Sorry i can't reproduce it. 

Could you test in another environment?
