### ISSUE TITLE
All NPCs are ground and wall bugs

### ISSUE THREAD

**Issue by poryagholami** [azerothcore/azerothcore-wotlk#2854]
![WoWScrnShot_040520_000722](https://user-images.githubusercontent.com/52524476/78459957-2c7fbc80-76d2-11ea-8f22-4ffd3aefd52d.jpg)
![WoWScrnShot_040520_000741](https://user-images.githubusercontent.com/52524476/78459958-31447080-76d2-11ea-9dfb-2f7c78a555e4.jpg)
![WoWScrnShot_040520_001050](https://user-images.githubusercontent.com/52524476/78459963-34d7f780-76d2-11ea-9037-bf834b8936af.jpg)
![WoWScrnShot_040520_001103](https://user-images.githubusercontent.com/52524476/78459967-39041500-76d2-11ea-8136-89e3596bc04d.jpg)

##### EXTRA NOTES:

master

##### OTHER CUSTOMIZATIONS:

<!-- ------------------------- THE END ------------------------------
Thank you for your contribution.

**Comment by Si1ker** [comment]
Thanks for your report to AzerothCore

However, this issue will be closed for the following reasons:
1- The issue template was not used or it was deleted during the creation.
2- This has been reported in the past, reference #2847 

Regards,
