### ISSUE TITLE
Improve storing IP address

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2855]
Just found out this https://www.z-car.com/blog/mysql/how-do-i-store-an-ip-address-in-mysql-inet_aton

We should store the IP as an integer instead of a string, it's proper, and faster. Should not be too hard to do, store with `INET_ATON()` and select it with `INET_NTOA()` to convert it back.

(this is for IPv4. I don't know for IPv6, never used)

Try with these:
```sql
SELECT INET_ATON("127.0.0.1") as IP;
SELECT INET_NTOA("2130706433") as R_IP;
SELECT INET_NTOA(INET_ATON("127.0.0.1")) as R_IP;
```

Concerned tables (might be missing some though and didn't check the modules) in the `auth` DB:

- logs_ip_actions
- ip_banned
- ip2nation
- realmlist
- account

**Comment by IceNet** [comment]
Idk, but, will this break all CMS' which uses/show IP's in account info?

**Comment by BarbzYHOOL** [comment]
yes, on FusionCMS IP is not used at all if I recall.

They would only need to update the SELECT query to `SELECT INET_NTOA("2130706433")` though, so a very easy fix. They can also do it in pure PHP

**Comment by Kitzunu** [comment]
Storing as string is a fine way of doing it and I doubt there will be any notable change in performance.
