### ISSUE TITLE
[Suggestion] MOTD and ANNOUNCE

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2856]
Just an idear :
I think it would be great to have the MOTD in the database instead of the conf file.
That way we could have a MOTD based on the language of the client.

We can also extend this idea to the announce that are already in the database but don't have a local column.

**Comment by Kitzunu** [comment]
This could also mean if done as the announces, we could have different MOTD depending on the realms

I like this suggestion :)

**Comment by solidmaxtor** [comment]
Yeah like suggestion, this can work same cast autobroadcast custom lines for diferent msg and realms.

**Comment by Maurowin** [comment]
Yeah, when I said ad, I meant this. Then as for the quests, if the translation is not available it uses English by default.

**Comment by Kitzunu** [comment]
Well, then we would also need to add a locale table so we manually can add the translations

**Comment by Maurowin** [comment]
Exactly !

**Comment by Maurowin** [comment]
@FrancescoBorzi just to up this suggestion :) 
the idea being if the players connect with different languages, that the server displays the MOTD related to the language of the client as for the quests etc... and if we could extend also for the server announcements that it is for :
- Autobroadcast 
- Server restarts 
- etc...

**Comment by Maurowin** [comment]
Is this PR only for autobroadcasts or does it also take into account MOTD?
