### ISSUE TITLE
[Core/Spell]  - Warlock Spell Soulshatter remove Invisibility [rogue/druid]

### ISSUE THREAD

**Issue by aqquarium** [azerothcore/azerothcore-wotlk#2857]
**SMALL DESCRIPTION:**
Warlock Spell Soulshatter  **ID** = 29858 
Remove Invisibility [Stealth] Rogue.
Remove Invisibility [Prowl] Druid feral.
Near or Far

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Warlock Spell Soulshatter  **ID** = 29858 não deve remover a invisibilidade como exemplo no video abaixo Stealth de rogue ou Prowl de Druid feral.

**CURRENT BEHAVIOUR:**
When a player of the warlock class casts the Soulshatter spell near or away from players who are invisible these players are appear because the spell has an effect on invisibility

**STEPS TO REPRODUCE THE PROBLEM:**
Enter the game with two accounts, like Warlock, and enter another Rogue or Druid class
test in the duel or pvp zone, stay invisible with rogue or ferocious druids and use the Soulshatter spell with an assistant watch the demo video
https://streamable.com/bv4k7z

BRANCH(ES):
master

**AC HASH/COMMIT:**
71f98ab

**OPERATING SYSTEM:**
Ubuntu 18 / Windows 10

**MODULES:**
No modules. Clean rev

**Comment by wizzymore** [comment]
I can confirm this,

The problem is not with the spell itself is with the rogue's stealth.
"Soulshatter is a core warlock ability learned at level 66. It reduces aggro on all targets within 90 yards by 50%."
The aggro is reduced on all targets i can't find any source saying that invisible or stealth targets don't get affected

**Comment by Maurowin** [comment]
I don't test to confirm if this issue exist, but in retail, this spell doesn't break Stealth.

**Comment by wizzymore** [comment]
I tested and can confirm that this doesn't work as intended.

Regards,

**Comment by BarbzYHOOL** [comment]
Does it inflict damage to the rogue too? (bug)

**Comment by FrancescoBorzi** [comment]
@wizzymore you can apply the `Confirmed` label

**Comment by BarbzYHOOL** [comment]
@aqquarium can you test this https://github.com/azerothcore/azerothcore-wotlk/pull/3056 and tell us if it's fine?
