### ISSUE TITLE
[RAID] AQ40 - Twin Emperors in Anhqiraj are buggy

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2863]
##### SMALL DESCRIPTION:

Teleportation doesn't work as expected, there is animation but without teleportation or rare times one joins the other.
an NPC is in the room when it shouldn't be there.

![WoWScrnShot_041020_093821](https://user-images.githubusercontent.com/31663279/78973889-137f6d00-7b11-11ea-9d99-604e65b5d094.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Teleportation should work, the twins should switch places via teleportation.
the NPC shouldn't be there.

https://youtu.be/B6vV64dmzwg?t=3097

##### CURRENT BEHAVIOUR:

Teleportation doesn't work as expected, there is animation but without teleportation or rare times one joins the other.

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to aQ40
2. use icons mark on them
2. pull Twin Emperors
3. and wait teleportation

##### BRANCH(ES):

master

**Comment by ChrisCGalbraith** [comment]
Unable to replicate the teleporting issue. I logged two characters and had one twin on each. They teleported fine across the entire room.

**Comment by Kitzunu** [comment]
Closing as it wasnt reproduced
