### ISSUE TITLE
Data Maps Error Start

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2865]
Hi guys, i'm use this manual -> http://www.azerothcore.org/wiki/digital-ocean-video-tutorial for compile AC on Debian 9, but when i'm starting ./worldserver i got the error 

`Map file '/home/azcore/azeroth-server/data/maps/0004331.map': does not exist!`

Where i can find this maps? Other i have

**Comment by wowissues** [comment]
i solved this problem, sry wrong directory path.

**Comment by Kitzunu** [comment]
Thst happened to me too, I just re-ran the tool and it fixed for me.

Happy to see you also managed to fix it :)
