### ISSUE TITLE
[$15] [ToC Raid] [Repost] - Floor needs to be re-broken by Arthas to get to Anub'arak after wipes [$15]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#2869]
##### SMALL DESCRIPTION:
You need to keep speaking to the NPC to get Arthas to come out and break the floor so you can get to Anub'arak after a wipe, and Anub'arak doesn't respawn unless you talk to that NPC.

This is a repost of issue #1143 which was posted last year.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After you kill Twin Val'kyr, the roleplay event should be a one-time thing - unless you soft-reset the instance (i.e., wait the number of hours it takes to soft-reset, can't be done manually).

Once the roleplay is over with, you get blown off downstairs and walk up to Anub'arak.  Once you're close enough, he'll pop out of the ground and say this:

> Anub'arak yells: Ahhh, our guests have arrived, just as the master promised.

Again, this is a one-time thing.  After a wipe, he should be waiting above ground to be pulled again.  There is no more roleplay after the first.

##### CURRENT BEHAVIOUR:
The floor needs to be re-broken after a wipe on Anub'arak and Anub doesn't respawn unless you talk to the NPC. Tested on 10, 10H, 25, 25H.

Anub'arak is being forced to do his intro each time, when it should be once, and then re-spawn in full view of players when a wipe occurs.

https://youtu.be/EqZoOt6VFl8

##### STEPS TO REPRODUCE THE PROBLEM:
Go into any difficulty of the ToC raid
Do the first 4 bosses and go down to Anub'arak
Wipe and attempt to zone back in. You will need to re-initiate the RP to get to Anub'arak and get him to spawn.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
44c3bef14ea7

##### OPERATING SYSTEM:
Win10

##### MODULES:
N/A

##### OTHER CUSTOMIZATIONS:
Increased boss HP

**Comment by Voxstrasza** [comment]
[bounty](https://www.bountysource.com/issues/90893599-toc-raid-repost-floor-needs-to-be-re-broken-by-arthas-to-get-to-anub-arak-after-wipes)

**Comment by wlasser** [comment]
You can hack this with next lines:
first, define some global var for instance in scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/trial_of_the_crusader.h
for example: bool tryBefore = false;

in scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
update this:
```
 void KilledUnit(Unit* who)
        {
            if( who->GetTypeId() == TYPEID_PLAYER )
               {
                  Talk(SAY_KILL_PLAYER);
                  tryBefore =true;
               }
        }

```
and scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp

```
case INSTANCE_PROGRESS_VALKYR_DEAD:
if (tryBefore)
{
 if( GameObject* floor = instance->GetGameObject(GO_FloorGUID) )
   floor->SetDestructibleState(GO_DESTRUCTIBLE_DAMAGED);
// i don't know about spawned staff, but here you can remove/spawn anything what do you need
}
else
events.RescheduleEvent(EVENT_SCENE_401, 0);
break;
```
this not is true way, because i am do not code long time. and this is just hak.
Sure, you can do it better.

**Comment by Helias** [comment]
@wlasser if you open a PR with a fix of this you can get the bounty, if there is anything we can improve to convert this "hackfix" into a proper fix, we'll see in the review of the PR, but I recommend you to open the PR first :wink:

**Comment by Helias** [comment]
@lineagedr using bountysource you can claim the 15$ :moneybag: 
Do it, you deserve them :+1:

**Comment by Helias** [comment]
I am opening the issue just to solve a problem with bountysource
