### ISSUE TITLE
[Dungeon] Nexus minors bugs

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2874]
##### SMALL DESCRIPTION:

In this topic I will address several problems related to this dungeon

- [ ] Book for the quest
- [ ] positioning mobs
- [ ] missing mobs
- [ ] superfluous mobs
- [ ] doesn't give money

I found some bad quality video from the original server, unfortunately. However, I found a 2013 video still from the original server of better quality.

2009 vidéos : 
part 1 of 3 https://www.youtube.com/watch?v=mYXT-zDwiQI
part 2 of 3 https://www.youtube.com/watch?v=zfGC6KxxTrw
part 3 of 3 https://www.youtube.com/watch?v=MYUjITBF3R4

2013 vidéo : 
https://www.youtube.com/watch?v=pySQvQey1f8

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The book must not despawn after you pick it up.
![WoWScrnShot_041120_124802](https://user-images.githubusercontent.com/31663279/79042500-afd06f00-7bf8-11ea-856e-21b2d4a99d8d.jpg)

That monster needs to be on the ground, not levitating.
![WoWScrnShot_041120_125237](https://user-images.githubusercontent.com/31663279/79042522-d7273c00-7bf8-11ea-94b2-265e81a33fef.jpg)

The purple monsters shouldn't be here.
![WoWScrnShot_041120_125348](https://user-images.githubusercontent.com/31663279/79042744-6da82d00-7bfa-11ea-8f45-395b66679e46.jpg)

These one, they mustn't be present because they're being killed by the mobs next them
![WoWScrnShot_041120_130212](https://user-images.githubusercontent.com/31663279/79042605-75b39d00-7bf9-11ea-959e-6a1aa47e2f23.jpg)

There are too many of them here!
![WoWScrnShot_041120_130147](https://user-images.githubusercontent.com/31663279/79042619-94b22f00-7bf9-11ea-9b91-fedaf39c9741.jpg)

Here, there should be a few 
![WoWScrnShot_041120_124802](https://user-images.githubusercontent.com/31663279/79042920-f83d5c00-7bfb-11ea-92aa-df77cf4cab66.jpg)
![WoWScrnShot_041120_130157](https://user-images.githubusercontent.com/31663279/79042644-c88d5480-7bf9-11ea-8f8d-c6825400c222.jpg)
![WoWScrnShot_041120_130207](https://user-images.githubusercontent.com/31663279/79042645-c88d5480-7bf9-11ea-9a50-9bfae89dccf9.jpg)

Bosses don't give money when they should.
![WoWScrnShot_041120_125459](https://user-images.githubusercontent.com/31663279/79042660-e490f600-7bf9-11ea-9243-7b571d5e9543.jpg)
![WoWScrnShot_041120_130517](https://user-images.githubusercontent.com/31663279/79042661-e5298c80-7bf9-11ea-80dd-6d15a49fc851.jpg)
![WoWScrnShot_041120_130704](https://user-images.githubusercontent.com/31663279/79042662-e5298c80-7bf9-11ea-84ed-16dac63a070b.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT: 

384fab39f909+

##### OPERATING SYSTEM:

ubuntu server 18.04

**Comment by Kitzunu** [comment]
I will look into this!

**Comment by Maurowin** [comment]
Dont run with mod spe xx because u will not give to some bug like first screenshot of "There are too many of them here!" chapter

**Comment by Kitzunu** [comment]
Ok thanks for letting me know!

Will probably get around to this during the upcoming week

**Comment by Kitzunu** [comment]
I decided to not study for my Ny'Alotha raid that I have tonight and rescript this because it seemed more fun xD
