### ISSUE TITLE
(DB/NPC): Heb'Drakkar Striker

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#2876]
##### SMALL DESCRIPTION:

He gets off his bat in midair and starts swimming towards us...
![WoWScrnShot_041120_143558](https://user-images.githubusercontent.com/31663279/79043867-4e150280-7c02-11ea-9fa1-469acf661fba.jpg)
![WoWScrnShot_041120_143646](https://user-images.githubusercontent.com/31663279/79043868-4ead9900-7c02-11ea-883b-5cd7acf3c0ea.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He mustn't swim, but stay on his horse and attack us while he's on it.

##### CURRENT BEHAVIOUR:

He gets off his bat in midair and starts swimming towards us...

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

384fab3+

##### OPERATING SYSTEM:

ubuntu server 18.04

**Comment by Kitzunu** [comment]
This is actually a retail bug that exists to this day.

I just tried it, and they dismount on aggro and does not fly to you.

**Comment by Maurowin** [comment]
Okay, maybe it's retail, but do we have to keep all the bugs in the game because it's retail?

**Comment by Kitzunu** [comment]
I think it might be impossible to fix, i sat 3 hrs trying different sai methods but could not improve it

**Comment by Maurowin** [comment]
Thank you so much for your efforts!
It must still be possible, there are a lot of mobs riding around and attacking us, for example in Gundrak. And that works perfectly on AC.

Do you think it's possible to get inspiration from their SAI?

It seems to me that I saw on Warmane that this problem has been corrected.

**Comment by Kitzunu** [comment]
I think the issue is that this mount is not a spellID mount, infact, it is mounted on another creature using action: 
SMART_ACTION_MOUNT_TO_ENTRY_OR_MODEL (creature_template.entry, creature_template.modelidx).

Most other mounts uses an actually spell to mount

**Comment by Maurowin** [comment]
Do you think we can modify it to be a spell mount?

**Comment by Kitzunu** [comment]
I am 99% sure that would require updates in client files, which would not be optimal
