### ISSUE TITLE
 How to update AC?

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2882]
Hello everyone, please tell me please how to update AzerothCore correctly?
After installation transmog i got an error and created issue here: https://github.com/azerothcore/mod-transmog/issues/37 worldserver is done

`SQL: DELETE FROM custom_transmogrification WHERE NOT EXISTS (SELECT 1 FROM item_instance WHERE item_instance.guid = custom_transmogrification.GUID) ERROR: [1146] Table 'acore_characters.custom_transmogrification' doesn't exist 
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders..`

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
AzerothCore rev. 9c8c5ea+ 2020-04-08 23:45:58 +0000

##### OPERATING SYSTEM:
Debian 9

##### MODULES:
Anticheat, ResetDuel, CFBG, Transmog

**Comment by DJBoxer** [comment]
Looks like you forgot to execute the SQL from the module folder.

> acore_characters.custom_transmogrification' doesn't exist Your database structure

https://github.com/azerothcore/mod-transmog/tree/master/data/sql

**Comment by wowissues** [comment]
i fixed this, idk why but transmorg.sql don't execute into my db

Thank you, others sql i need to execute? But anyway how to update AzerothCore correctly?

**Comment by FrancescoBorzi** [comment]
@wowissues 

http://www.azerothcore.org/wiki/Update

also, if you have more questions please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
