### ISSUE TITLE
(DB/Gameobject): Dalaran Forges

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2885]
https://www.youtube.com/watch?v=kmBmz9r3YxQ
horns don't work

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 9c8c5ea+ 2020-04-08 23:45:58 +0000

**OPERATING SYSTEM**: Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog

**Comment by wlasser** [comment]
`.gob near 20`
near this object, and same command at working object.
what it's guid/entry?
well, next you can download Keira editor, which link is on azerothcore page.
And just compare each other.
Don't be a lazy, this is realy easy.

**Comment by Kitzunu** [comment]
It is not a game object. But there is spellfocus missing.

I am fixing this atm

**Comment by Kitzunu** [comment]
But the report could be more pretty, i.e including proof

**Comment by Kitzunu** [comment]
Feel free to test this PR https://github.com/azerothcore/azerothcore-wotlk/pull/2886 which will fix your issue :)

**Comment by wowissues** [comment]
> But the report could be more pretty, i.e including proof

sorry but video is not my)

**Comment by wowissues** [comment]
Fixed https://github.com/azerothcore/azerothcore-wotlk/issues/2885

**Comment by Kitzunu** [comment]
Dont close it before the PR is merged

**Comment by wowissues** [comment]
> Dont close it before the PR is merged

ok, i'm sorry about this.
