### ISSUE TITLE
(Core/Spell Script): Obsidian Sanctum Sartharion Flame Tsunami

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2891]
**SMALL DESCRIPTION**:
I don't know how to get ID of this object or what is that, i'm talking about the Flame Tsunami. (I tried to find it on the wowhead but did not find it)

**EXPECTED BLIZZLIKE BEHAVIOUR**:
They must impose a debuff  https://www.wowhead.com/spell=57491/flame-tsunami and knockback https://wowhead.com/spell=60241/ 

**CURRENT BEHAVIOUR**:
They must impose a debuff  https://www.wowhead.com/spell=57491/flame-tsunami (it's working fine), but also they should knockback https://wowhead.com/spell=60241/ (it didn't works)

**STEPS TO REPRODUCE THE PROBLEM**: 

1. Start fight with Sartharion (https://www.wowhead.com/npc=28860/sartharion). 
2. Wait for it to launch Flame Tsunami

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. f7562f8d961d+ 2020-04-12 21:59:00 +0000

**OPERATING SYSTEM:** Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, RewardPlayedTime

**Comment by Si1ker** [comment]
Hello @wowissues , thanks for your report.

However, this is not an issue, there is no attribute for "knockback" into the behavior of the spell/wall so it won't push away but damage, apply periodic damage and slow down.


![2020-04-14 10_51_27-Flame Tsunami - Spell - World of Warcraft](https://user-images.githubusercontent.com/61223313/79251829-f1059080-7e3d-11ea-8a03-9a35bc5c44ab.png)
source: https://www.wowhead.com/spell=57491/flame-tsunami

**Comment by wowissues** [comment]
> Hello @wowissues , thanks for your report.
> 
> However, this is not an issue, there is no attribute for "knockback" into the behavior of the spell/wall so it won't push away but damage, apply periodic damage and slow down.
> 
> ![2020-04-14 10_51_27-Flame Tsunami - Spell - World of Warcraft](https://user-images.githubusercontent.com/61223313/79251829-f1059080-7e3d-11ea-8a03-9a35bc5c44ab.png)
> source: https://www.wowhead.com/spell=57491/flame-tsunami

I didn't understand anything, sorry English is not my native language. That is, it should work like that? Without knockback?

**Comment by wowissues** [comment]
yes, i'm rechecked it doesn't work

**Comment by Si1ker** [comment]
@wowissues Ok now confirm me where 60241 is used.
(Spoiler: it is not used in the boss script, instance script neither header)

**Comment by wowissues** [comment]
> @wowissues Ok now confirm me where 60241 is used.
> (Spoiler: it is not used in the boss script, instance script neither header)

I attached the screenshot above. These fiery tsunamis are released when you attack Sartarion

**Comment by Si1ker** [comment]
The screenshot above, are from spell 60241 which is not used anywhere into the sartharion events, you can post here any other core using 60241into the sartharion events, after that I will be happy to confirm this, until that, this will remain invalid and ina couple fo days not confirmed.

Also if it knockbacks players, that would help people from getting hurt by the periodic damage of the fie walls, which would not make sense.

Once again, you can search for that spell being used into any other core as a proof, then this will be confirmed.

Thanks.

**Comment by wowissues** [comment]
I don’t know how to recognize ID(((. But Blizzlike behavior should knockback

**Comment by LukasVolgger** [comment]
This is a valid issue. Read this article from 2009 https://www.eurogamer.net/articles/world-of-warcraft-dragons-raid-guide-article

Also i saw a bunch of videos on YT where you can see the knockback.

On top myself did this raid a couple of time on retail and iirc the fire wall gives indeed knockback.

**Comment by Si1ker** [comment]
@LukasVolgger Do you have any video from YT where we can check it?

**Comment by LukasVolgger** [comment]
@Si1ker 
At 7:30
https://youtu.be/iJJ4hhL9DU0

**Comment by wowissues** [comment]
> This is a valid issue. Read this article from 2009 https://www.eurogamer.net/articles/world-of-warcraft-dragons-raid-guide-article
> 
> Also i saw a bunch of videos on YT from retail where you can see the knockback.
> 
> On top myself did this raid a couple of time on retail and iirc the fire wall gives indeed knockback.
> 
> Edit: Didn't test the behaviour ingame.

i love you, thanks to help me in this issue

**Comment by LukasVolgger** [comment]
No problem! 

Also well done issue reports in last time @wowissues! Thx for reporting and  contributing to the project!

**Comment by wowissues** [comment]
> contributing

I want to write issues better. English is just not my native language. And I have not really figured out the coordinates of xyz. To make it more convenient for everyone to test.

**Comment by PivanDepolo** [comment]
yep, i have this problem too
