### ISSUE TITLE
(Core/spell) Assertion failed

### ISSUE THREAD

**Issue by merdlin** [azerothcore/azerothcore-wotlk#2892]
(Core/spell) Assertion failed

##### SMALL DESCRIPTION:
the error happens at the dungeon pit farm

##### EXPECTED BLIZZLIKE BEHAVIOUR:
the last mistake was after killing the boss garfrost and using the return stone.

##### CURRENT BEHAVIOUR:
SPELLS INVALID

##### STEPS TO REPRODUCE THE PROBLEM:
Dungeon PIT FARM 

1. die garfrost
2. return stone
3. SPELL INVALID

##### EXTRA NOTES:

BRANCH(ES): master

AC HASH/COMMIT: AzerothCore rev. [[f7562f8](https://github.com/azerothcore/azerothcore-wotlk/commit/f7562f8d961de02e8b56fd112b7ca0a5b9c8c5a6)]+ 2020-04-12 21:59:00 +0000

##### OPERATING SYSTEM:
Windows server 2016

##### MODULES:
Crossfaction / mod-npc-buffer-master

##### OTHER CUSTOMIZATIONS:
NO
![image](https://user-images.githubusercontent.com/60373652/79250134-a2afbc00-7e54-11ea-8455-c9ec30320455.png)

**Comment by merdlin** [comment]
**I just discovered the problem, the npc Buffer is giving Invalid spells.**

**Comment by Kitzunu** [comment]
Which NPC?

**Comment by merdlin** [comment]
> Which NPC?

http://www.azerothcore.org/catalogue/details.html?id=123951698

**Comment by Kitzunu** [comment]
If it is a bug with the module I suggest you raise a ticket there https://github.com/azerothcore/mod-npc-buffer

**Comment by merdlin** [comment]
I'm closing the ticket because the bug is not in the core, but in the module.
