### ISSUE TITLE
MySQL 8 Upgrade

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#2895]
##### SMALL DESCRIPTION:

I propose that we upgrade to MySQL 8.0, to stay in phase with Trinitycore.

This probably means that we have to stop support for MySQL 5.6, but can keep 5.7. (I cannot test this as I have upgraded my system to 8.0)

I have made it work locally with this:
https://github.com/Kitzunu/azerothcore-wotlk/commit/489275d34e1b7a6e39e6c697e1e797c59dad5441
https://github.com/Kitzunu/azerothcore-wotlk/commit/f55cea6a1780c944599e1ec55cedfc866551c371
https://github.com/Kitzunu/azerothcore-wotlk/commit/9972a4bc20c7e0af0e08c0ea800eeb738376cd57

Works like a charm, I have not found any issues with it so far :)

##### TODO
I am 99% sure that the db assembler gets broken by MySQL 8.0 because I got this error when trying to run it:
```
/e/azerothcore-wotlk/apps/db_assembler/includes/functions.sh: line 24: mysql: command not found
```
```sh
    retval=$("$DB_MYSQL_EXEC"  -h "$MYSQL_HOST" -u "$MYSQL_USER" $options -e "$command")
```
which I did not manage to fix myself, so I imported everything manually to DB.

**Comment by Viste** [comment]
https://www.mysql.com/ -- dead project
https://mariadb.org/ -- The future 
just my opinion

**Comment by wizzymore** [comment]
Off-topic:
```/e/azerothcore-wotlk/apps/db_assembler/includes/functions.sh: line 24: mysql: command not found``` - to make this work be sure the folder containing mysql.exe is added in the environment path.
