### ISSUE TITLE
(Core/NPC/Spell Script): Naxxramas Death Knight Understudy and Mind Control

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2899]
**EXPECTED BLIZZLIKE BEHAVIOUR**:
When you are use https://www.wowhead.com/npc=29912/obedience-crystal, you control https://www.wowhead.com/npc=16803/death-knight-understudy and you can leave his mind.

**CURRENT BEHAVIOUR**:
All work nice, but you cannot leave his mind

**STEPS TO REPRODUCE THE PROBLEM**:

1. Use https://www.wowhead.com/npc=29912/obedience-crystal
2. Try to get out from mind of https://www.wowhead.com/npc=16803/death-knight-understudy

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. f7562f8+ 2020-04-12 21:59:00 +0000

**OPERATING SYSTEM**: Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, RewardPlayedTime, PvPTitles

**Comment by PivanDepolo** [comment]
i can confirm this too!

**Comment by Kitzunu** [comment]
cc @Si1ker

**Comment by Si1ker** [comment]
What do you mean about "leave mind" ??

https://www.youtube.com/watch?v=8elL14VTND8
![image](https://user-images.githubusercontent.com/61223313/104833742-a7c8ee00-5860-11eb-8f0f-5a68fb3c881c.png)

**Comment by Kitzunu** [comment]
I understand it that this is not a bug, as Silker also removed the confirmed label.

Reopen if I'm wrong

**Comment by Si1ker** [comment]
> I understand it that this is not a bug, as Silker also removed the confirmed label.
> 
> Reopen if I'm wrong

@Kitzunu closing is ok, not because is invalid, but because is a duplicate of #4198
(The issue is real & confirmed, I don't remember why I removed the label, maybe misclick lol

**Comment by T1ti** [comment]
maybe he is talking about the "exit" button on the bar 
![image](https://user-images.githubusercontent.com/40864460/131589804-8b9352d9-d611-48c6-a720-bcdea15eff87.png)

**Comment by T1ti** [comment]
re open this issue, yes right click pet and dismissing currently work, but the pet is missing the cancel button as u can see above 
![image](https://user-images.githubusercontent.com/40864460/131769498-9424b708-afce-4eba-be37-f6174fcf59a2.png)
