### ISSUE TITLE
ZulAman RAID Bug Please come in and see.

### ISSUE THREAD

**Issue by mayaren888** [azerothcore/azerothcore-wotlk#290]
**Description**: Have some boss, After the entire team fails, you will be prompted: in combat, unable to enter.
**Current behaviour**: “in combat, unable to enter.”

**Expected behaviour**: When the team fails, outside players should be able to enter RAID

**Steps to reproduce the problem**:

1. A certain Boss,Team failure, players Resurrection.
2. When entering RAID, dialog prompt:in combat, unable to enter.
3. All players will not be able to continue the game.
4.Restart worldserver or clear player game instance(Character.instance table), problem solving.

**Branch(es)**: Master
**AC hash/commit**:  068ac593cb2894a16f3bfa78867fd901fc3122ed
**Operating system**:  Windows 7

Which kind of people can help solve this problem. God will thank you.

**Comment by talamortis** [comment]
@mayaren888 Im sure when you are in a boss fight it put all players in combat and u cant ever a raid if any other player is alive

**Comment by mayaren888** [comment]
@talamortis Even if all players die, become soul state still can not enter RAID

**Comment by mayaren888** [comment]
@talamortis Even if all players die, become soul state still can not enter.

**Comment by talamortis** [comment]
can you tell me what boss?

**Comment by mayaren888** [comment]
@talamortis  NPC id:23576    name:Nalorakk   
Other Boss also have a chance to generate this problem.

**Comment by panpan6494** [comment]
hi,did you solve this problem?

**Comment by panpan6494** [comment]
i want to know how to solve it,too.

**Comment by panpan6494** [comment]
i think i have solve this problem. in boss-akilzon.cpp. the function justdie,add code
instance->setdata(data-akilzonevent,done);
and add this code into function killedunit, too.

**Comment by talamortis** [comment]
@panpan6494, so if player is dead the boss is complete this code will be incorrect. sorry

**Comment by panpan6494** [comment]
function justdie（）;
function killunit（）;
all of them added？

**Comment by talamortis** [comment]
The Reason this error happened was because when the creature/boss got in combat it set the instance to inprogress while the instance is in progress state no player can not enter, there for this didnt have the function in the reset which is as shown as above. the Justdie is for when the boss dies, the killUnit is when the boss kills a player you was setting both to done, so if this was a tribute run for the mount and that was the last boss players probly can kill them self just to gain the item.

**Comment by panpan6494** [comment]
Got your mean. 你可以直接删了有setdata的代码，好多人都这样做。

**Comment by AnonXS** [comment]
This Line https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp#L141 , adjusted to Akil'Zon, is missing from his void Reset().

**Comment by ShinDarth** [comment]
@AnonXS PRs are welcome
