### ISSUE TITLE
Skybreaker questline

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#2902]
##### SMALL DESCRIPTION:

Currently the Skybreaker has no quest chaining at all as seen in the image below
![image](https://user-images.githubusercontent.com/24550914/79516352-6abe9980-804b-11ea-8cb5-729cea8b4a61.png)

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

https://github.com/azerothcore/azerothcore-wotlk/commit/6a410efa3622ee522cacfb68a26c3d56d1604605

**Comment by merdlin** [comment]
#2903 Fix.
