### ISSUE TITLE
(DB/Creature): King Magni Bronzebeard <Lord of Ironforge>

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2905]
**EXPECTED BLIZZLIKE BEHAVIOUR**:
He must use abilities https://wowhead.com/spell=20685/storm-bolt I don’t know about others

**CURRENT BEHAVIOUR**:
He is like a mannequin, just beats, but does not use abilities.

**STEPS TO REPRODUCE THE PROBLEM**:
1. .go xyz -4851.801270 -1038.111084 502.189911 0.5.421868
2. Start fight with https://wowhead.com/npc=2784/king-magni-bronzebeard

**AC HASH/COMMIT**: AzerothCore rev. f7562f8+ 2020-04-12 21:59:00 +0000

**OPERATING SYSTEM**: Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, RewardPlayedTime, PvPTitles

**Comment by Voxstrasza** [comment]
According to https://wowwiki.fandom.com/wiki/Magni_Bronzebeard, he has several other abilities in his arsenal in addition to Storm Bolt:

Avatar (https://www.wowhead.com/spell=19135/avatar)
Thunderclap 
Charge
Knock Away (https://www.wowhead.com/spell=20686)
Summon Guards
Self Heal

I'm not sure what Thunderclap, Charge, Summon or Self Heal spell IDs he uses.

**Comment by Kitzunu** [comment]
In tc this is the script related to combat

smart_scripts
---
```sql
SELECT * FROM smart_scripts WHERE entryorguid = 2784
```
| entryorguid | source_type | id | link | event_type | event_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | action_type | action_param1 | action_param2 | action_param3 | action_param4 | action_param5 | action_param6 | target_type | target_param1 | target_param2 | target_param3 | target_param4 | target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 2784 | 0 | 0 | 0 | 20 | 0 | 100 | 0 | 683 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | King Magni Bronzebeard - On Quest 'Sara Balloo's Plea' Finished - Say Line 0 | 
| 2784 | 0 | 1 | 0 | 4 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 4 | 5896 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | King Magni Bronzebeard - On Aggro - Play Sound 5896 | 
| 2784 | 0 | 2 | 0 | 0 | 0 | 100 | 0 | 5000 | 7000 | 25000 | 30000 | 0 | 11 | 19135 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | King Magni Bronzebeard - In Combat - Cast Avatar | 
| 2784 | 0 | 3 | 0 | 0 | 0 | 100 | 0 | 8000 | 10000 | 20000 | 30000 | 0 | 11 | 20686 | 0 | 0 | 0 | 0 | 0 | 2 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | King Magni Bronzebeard - In Combat - Cast Knock Away | 
| 2784 | 0 | 4 | 0 | 0 | 0 | 100 | 0 | 12000 | 15000 | 15000 | 20000 | 0 | 11 | 20685 | 0 | 0 | 0 | 0 | 0 | 5 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | King Magni Bronzebeard - In Combat - Cast Storm Bolt |
