### ISSUE TITLE
DB/Quest: Into the World of Spirits

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#2907]
##### SMALL DESCRIPTION:

Currently there is no Reagent Pouch in the correct location for the quest.
Reported by Barbz

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Reagent Pouch should be in the broken ship

##### STEPS TO REPRODUCE THE PROBLEM:

1. .q add 11333
2. .go xyz 797 -5148 -83 571

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/2514f8fc9a3b8f24b89ba5ef402bec3f8f36fee0

##### OPERATING SYSTEM:

W10

**Comment by wowissues** [comment]
Works, thx
