### ISSUE TITLE
Creatures and not only dropping underground after i use spells like Typhoon, Blink (Mage) or Thunderstorm (Sham)

### ISSUE THREAD

**Issue by redbaron99** [azerothcore/azerothcore-wotlk#2912]
Creatures and not only dropping underground after i use spells like Typhoon, Blink (Mage) or Thunderstorm (Sham)

##### SMALL DESCRIPTION:

Hello everyone, there is such a strange problem , creatures and not only dropping underground after i use spells like Typhoon, Blink (Mage) or Thunderstorm (Sham), also sometimes some aoe spells like Starfall pulling creature from another room and another floor. im looking for help about this sotuation. here is example in icecrown citadel using Typhoon
https://youtu.be/76yqrXYTXPs

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

50287c05f0e3ac4d8f006543eb916d53efa15f5f

##### OPERATING SYSTEM:

Debian 9

**Comment by arthaswow** [comment]
maps, vmaps and mmaps were extracted and installed correctly?

**Comment by redbaron99** [comment]
im using this one https://github.com/wowgaming/client-data/releases/tag/v7

**Comment by redbaron99** [comment]
Github links:

Full data (v8) - from 13/08/19 to now (Used in the automatic downloader script in /apps/)

**Comment by Kitzunu** [comment]
Extract the maps from the client using the tools provided when you build the source.

Perhaps those maps are outdated

**Comment by redbaron99** [comment]
@Kitzunu same with extracted new maps

**Comment by arthaswow** [comment]
this world configs are set ?
```
vmap.enableIndoorCheck = 1
DetectPosCollision = 1
CheckGameObjectLoS = 1
```

**Comment by redbaron99** [comment]
> this world configs are set ?
> 
> ```
> vmap.enableIndoorCheck = 1
> DetectPosCollision = 1
> CheckGameObjectLoS = 1
> ```

yes

**Comment by redbaron99** [comment]
any ideas whats wrong with it?

**Comment by arthaswow** [comment]
i think is something with core, need to debug and trace

**Comment by Shard-MW** [comment]
Does this happen only on some maps or on all maps ?

**Comment by Kitzunu** [comment]
I just want to add as a side not to this, that it also happens for players using Killing Spree (Taken from Discord)

**Comment by pklloveyou** [comment]
Confirm, I also have this problem

**Comment by BarbzYHOOL** [comment]
this is probably again because of our faulty mmap/vmap :'(

**Comment by FALL1N1** [comment]
Can someone try this:

i_nextCheckTime.Reset(500);
to
i_nextCheckTime.Reset(100);

in FleeingMovementGenerator.cpp @ L45
