### ISSUE TITLE
Valkyr animation bug

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2916]
##### SMALL DESCRIPTION:
The Valkyr do not use the appropriate animations for moving, standing or casting.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The Valkyr use their special animations while casting or on the ground.

##### CURRENT BEHAVIOUR:
Valkyr, when on ground level or doing animations go to their standing animations, where they stand up straight, instead of their flying ones.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Die in the Ebon Hold

##### EXTRA NOTES:
Video: https://youtu.be/b863yUtcCzM?t=953

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Viste** [comment]
send this to repack author. We don't manage this repack
