### ISSUE TITLE
Deaths Challenge DK quest bug

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2917]
##### SMALL DESCRIPTION:
The Death Knights do not do their animation when defeated in a duel

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The Death Knights emote

##### CURRENT BEHAVIOUR:
They just go back to their positions

##### STEPS TO REPRODUCE THE PROBLEM:

1. Defeat a Death Knight in a duel on quest 12733

##### EXTRA NOTES:
Video: https://youtu.be/b863yUtcCzM?t=933

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Viste** [comment]
send this to repack author. We don't manage this repack
