### ISSUE TITLE
Scourge Gryphon bug

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2919]
##### SMALL DESCRIPTION:
Scourge Gryphons in phase 2 of the Scarlet Enclave/Death Knight quest Chain do not go anywhere, leading to them stacking up instead of going to fight

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They go towards the Scarlet instead of standing still until despawn and stacking up

##### CURRENT BEHAVIOUR:
They just stand

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to phase 2 of Havenshire and follow Gothik the Harvester

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Viste** [comment]
send this to repack author. We don't manage this repack

**Comment by BarbzYHOOL** [comment]
I wouldn't be surprised if we had this bug on AC too
