### ISSUE TITLE
Charged Leap animation desync

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2920]
##### SMALL DESCRIPTION:
Ulduar Trash mobs ability, Charged Leap, 64779, doesnt do the shockwave (impact) animation at the same time that the user hits ground after using it

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It is in sync

##### CURRENT BEHAVIOUR:
90% of the time its delayed

##### STEPS TO REPRODUCE THE PROBLEM:

1. Add the spell to your character and use it.

##### EXTRA NOTES:
♩ ♪ ♫ ♬

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Kitzunu** [comment]
I am 90% sure repacks are not supported.
However, these issues might be in our current core anyways.

If I have time tomorrow, I may check

**Comment by Viste** [comment]
send this to repack author. We don't manage this repack
