### ISSUE TITLE
Spellbook inconsistency

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2921]
##### SMALL DESCRIPTION:
Learning different spellbook skills and abilities will sometimes give you an extra category in your spellbook (such as Death Knights Frost skill), and other times not, causing the spells to go to the general tab. This is fairly frustrating for testing lots of ability, causing clutter

##### EXPECTED BLIZZLIKE BEHAVIOUR:
None

##### CURRENT BEHAVIOUR:
Inconsistent and unnecessary

##### STEPS TO REPRODUCE THE PROBLEM:

0. Make a Rogue character
1. Add DK Frost skill and ability to your character, and the Mage Fire skill and ability. 
2. Learn Frost Strike and Mages Fireball
3. Open Spellbook

##### EXTRA NOTES:
♩ ♪ ♫ ♬

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Viste** [comment]
send this to repack author.

**Comment by Helias** [comment]
We provide support for the main repo azerothcore/azerothcore-wotlk, so the repo where you opened the issue, as @Viste said, we do not support repack.

**Comment by BarbzYHOOL** [comment]
yes because this is not a blizzlike behaviour anyway, so it's up to the repack author to fix it
