### ISSUE TITLE
Koltira/Bloody Breakout Timing inconsistency

### ISSUE THREAD

**Issue by Bassaled** [azerothcore/azerothcore-wotlk#2922]
##### SMALL DESCRIPTION:
The quest Bloody Breakout seems to work in two parts, a trigger and a timer. If Koltira aggros a Scarlet NPC, he will not propperly loot the chest or obtain his armor, and will stand there and use Anti Magic zone in the corner of the room.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The quest doesnt rely on timers, and Koltira gets his armor, stands in the center of the room and then uses anti magic zone.

##### CURRENT BEHAVIOUR:
Timers can cause inconsistency in the quest scripting.
##### STEPS TO REPRODUCE THE PROBLEM:

1. Before breaking Koltira Free, aggro a scarlet mob
2. Turn in the quest
3. Watch Koltira aggro him and punch him and fail the rest of his actions
##### EXTRA NOTES:
I think its better if the scripts relied less on timers and more on propper sequences.

##### AC HASH/COMMIT:
Azeroth Core solo repack 1.3.10

##### OPERATING SYSTEM:
Windows 7

##### MODULES:
Azeroth Core solo repack 1.3.10

##### OTHER CUSTOMIZATIONS:
No

**Comment by Viste** [comment]
send this to repack author. We don't manage this repack
