### ISSUE TITLE
[Core/Pet] Missing Action Bar when Shaman summoned fire/earth elemental

### ISSUE THREAD

**Issue by soniczhang11** [azerothcore/azerothcore-wotlk#2923]
##### SMALL DESCRIPTION:

there is no action bars for Shamans' earth&fire elemental. So players cannot control the summoned pets. btw, action bar works for shaman's feral spirit.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

fire and earth elemental should have action bar and can be controlled just like other summoned pets, e.g. water elemental.

##### CURRENT BEHAVIOUR:

fire elemental
Spell: 2894 Creature(totem):15439 Creature(great fire elemental): 15438 

##### STEPS TO REPRODUCE THE PROBLEM:

1. use a shaman and summon the elemental.
2. action bar missed.
3. 

##### EXTRA NOTES:

already checked the Pet.cpp, Pet.h and PetDefines.h and seems like nothing wrong. Shaman's elemental are littel different from other temopral summoned pets, since its logic is spell -> totem ->pets. Maybe here is the problem?
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 30dceb3fa652+ 2020-04-22 00:26:47 +0200 (master branch) (Unix, Release) (worldserver-daemon) ready...

##### OPERATING SYSTEM:

CentOS 7

##### MODULES:

nope

##### OTHER CUSTOMIZATIONS:

nope

**Comment by lineagedr** [comment]
Got any proof?
So far I've seen this https://www.youtube.com/watch?v=pQ7dPZtMX3o and it shows no bar.

**Comment by soniczhang11** [comment]
> Got any proof?
> So far I've seen this https://youtu.be/pQ7dPZtMX3o?t=7 and it shows no bar.

sry for that, blizzlike should no action bar, you are right.
