### ISSUE TITLE
Clang 10 build

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#2927]
##### SMALL DESCRIPTION:
Clang 10 build broken
##### EXPECTED BLIZZLIKE BEHAVIOUR:
build must be ok
##### CURRENT BEHAVIOUR:
Clang 10 build  log https://paste2.org/h3efZ8VX
##### STEPS TO REPRODUCE THE PROBLEM:
1. update clang to 10
2. run cmake
3. run make and upset 

##### EXTRA NOTES:
part of this errors related to G3Dlib and can be fixed with https://github.com/azerothcore/azerothcore-wotlk/pull/2904 no its help only for gcc

##### BRANCH(ES):
master
##### OPERATING SYSTEM:
```
 ~/d/a/build   master   lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.0
Codename:	Lysia

```
##### MODULES:
no clean master

**Comment by Viste** [comment]
![Снимок экрана от 2020-04-23 01-14-30](https://user-images.githubusercontent.com/281977/80039226-0050a200-8500-11ea-9248-b4a98ed5facd.png)
fix for ngrid error

**Comment by mishaparem** [comment]
I see the same behaviour
[https://paste2.org/CaDsB1Ub](https://paste2.org/CaDsB1Ub)

**Comment by FrancescoBorzi** [comment]
@Viste  it's not fixed yet so why closing?

**Comment by Viste** [comment]
is not relevant to me.

**Comment by mishaparem** [comment]
@FrancescoBorzi I'm still working on this.. slowly, when time permits. Not sure it's specifically related to Clang10, seems more like a bunch of C++11 stuff so far.

**Comment by Viste** [comment]
@mishaparem just remove from cmake -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"
and apply 
![image](https://user-images.githubusercontent.com/281977/81502986-dfeb5a80-92e9-11ea-9707-3e6285bb13a4.png)

**Comment by mishaparem** [comment]
@Viste some of the "just warnings" point to potential bugs

**Comment by Viste** [comment]
@mishaparem this shit works ok for few years with this potential bugs

**Comment by mishaparem** [comment]
@Viste umm, not sure why that's an argument to ignore potential bugs

**Comment by FrancescoBorzi** [comment]
@mishaparem I agree that warnings should be fixed, can you please report them in a new issue?

thanks
