### ISSUE TITLE
Bug  [Berserker Stance] and  [Defensive Stance]

### ISSUE THREAD

**Issue by Ramys** [azerothcore/azerothcore-wotlk#293]
**Description**:

Spells do not appear to train 

**Current behaviour**: Tell us what happens

Only .learn to add a spell

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Class Warrior
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  AzerothCore rev. 068ac593cb28

**Operating system**:  Win 10

**Modules**:  Are you using modules? if yes, list them
transmog

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
@Ramys  did you try the quest before opening the issue?
