### ISSUE TITLE
(DB/Quest): The Deathstalkers

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2931]
**SMALL DESCRIPTION**:
https://wowhead.com/quest=1886/the-deathstalkers
On the way, you need to find a Astor Hadren (https://www.wowhead.com/npc=6497/astor-hadren) , you need to talk to him and then kill him. A quest item falls from him. This item starts a chain of quests. The problem is that when you talk to him he disappears and you leave the field of view he appears but he cannot be attacked, the target writes too far, although he stood close to him.

**STEPS TO REPRODUCE THE PROBLEM**:

    1. .q add 1886
    2. .tele silverpineforest

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 30dceb3fa652+ 2020-04-22 +0200

**OPERATING SYSTEM**: Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, RewardPlayedTime, PvPTitles

**Comment by BarbzYHOOL** [comment]
test this please @wowissues https://github.com/azerothcore/azerothcore-wotlk/pull/2935/files
