### ISSUE TITLE
Quest Repurposed Technology

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#2932]
https://www.wowhead.com/quest=12035/repurposed-technology

##### SMALL DESCRIPTION:

You can reuse multiple times the same corpse

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The corpse should disappear after used

#### CURRENT BEHAVIOUR:

The corpse does not disappear after use, so players can abuse it using it multiple times

##### AC VERSION

https://github.com/azerothcore/azerothcore-wotlk/commit/5f2f68c500ea435348cd269d23da3a906eb0c388

**Comment by FrancescoBorzi** [comment]
TC issue: https://github.com/TrinityCore/TrinityCore/issues/16158

TC fix (not tested yet on AC): https://github.com/TrinityCore/TrinityCore/commit/2668258fe227252fd337cb2d668a27b6a4a02eb8

**Comment by merdlin** [comment]
#2936 I just posted the tested fix and it works.
