### ISSUE TITLE
[Improvement] Blizzlike Pet Movement

### ISSUE THREAD

**Issue by lineagedr** [azerothcore/azerothcore-wotlk#2941]
This is how it's going to look:

Prototype 2 (new):
https://www.youtube.com/watch?v=TMRt6CYaEmQ

MaNGOS Commits:
1. https://github.com/cmangos/mangos-wotlk/commit/6f2bb4d2f7a58cdce1ad483d65d15ca6824b37d5#diff-f3507a9230dee6c1c0e3df9e898810df
2. https://github.com/cmangos/mangos-wotlk/commit/e0770c55a64235f6f4a67f4a0c819c3f8efde502#diff-f3507a9230dee6c1c0e3df9e898810df
3. https://github.com/cmangos/mangos-wotlk/commit/1fe23b116841c8c1ff530b916a0309eb4934c744#diff-f3507a9230dee6c1c0e3df9e898810df
4. https://github.com/cmangos/mangos-wotlk/commit/ec2ff4496aeceab7b5d0151589e0254f307961ee#diff-f3507a9230dee6c1c0e3df9e898810df
5. https://github.com/cmangos/mangos-wotlk/commit/ee9bdaf7e9fdca5d92ed3bee2d29cbfa9e67af60#diff-f3507a9230dee6c1c0e3df9e898810df
6. https://github.com/cmangos/mangos-wotlk/commit/e5346a070a5010c676cec8c008d6c149dc30af57#diff-f3507a9230dee6c1c0e3df9e898810df
7. https://github.com/cmangos/mangos-wotlk/commit/b87d01461638ff8cccce631c01bc91f572ef05ed#diff-f3507a9230dee6c1c0e3df9e898810df
8. https://github.com/cmangos/mangos-wotlk/commit/b6a579d57a2eee5cd915701dd8297bded2dcc36b#diff-f3507a9230dee6c1c0e3df9e898810df
9. https://github.com/cmangos/mangos-wotlk/commit/3283560886a9dd1aba63d8db49d0fa4fc30dd67a#diff-f3507a9230dee6c1c0e3df9e898810df
10. https://github.com/cmangos/mangos-wotlk/commit/fb2b5b2845e545df0d253948588f265c25827f76#diff-f3507a9230dee6c1c0e3df9e898810df
11. https://github.com/cmangos/mangos-wotlk/commit/b61c3135e65299833e0a444fe8496d917493b583#diff-f3507a9230dee6c1c0e3df9e898810df
12. https://github.com/cmangos/mangos-wotlk/commit/b64e54fc2ed70ef13d8a5a1f327e483864105161#diff-f3507a9230dee6c1c0e3df9e898810df
13. https://github.com/cmangos/mangos-wotlk/commit/768187afbcdb3659943f054430283d2e46b3da62#diff-f3507a9230dee6c1c0e3df9e898810df
14. https://github.com/cmangos/mangos-wotlk/commit/4fcb56d13c919c6afac784717ef056015bee12f3#diff-f3507a9230dee6c1c0e3df9e898810df
15. https://github.com/cmangos/mangos-wotlk/commit/f5c3634231edebac47cd3dc1ea6a43350cf6c9e6#diff-f3507a9230dee6c1c0e3df9e898810df
16. https://github.com/cmangos/mangos-wotlk/commit/3ce215e947984b2018ba69d2aada85c487a8c428#diff-f3507a9230dee6c1c0e3df9e898810df
17. https://github.com/cmangos/mangos-wotlk/commit/6b5cda5d0cf6c28101d643b0f856619e1ebdd189#diff-f3507a9230dee6c1c0e3df9e898810df
18. https://github.com/cmangos/mangos-wotlk/commit/75eabbe1baa352ee908825436701b7265756b008#diff-f3507a9230dee6c1c0e3df9e898810df 
19. https://github.com/cmangos/mangos-wotlk/commit/3dee47aed4472256d5e624d7515256110c560409#diff-f3507a9230dee6c1c0e3df9e898810df
20. https://github.com/cmangos/mangos-wotlk/commit/05611a211f54dbf90d620506c21146dfd0d255c8#diff-f3507a9230dee6c1c0e3df9e898810df

Most of these commits are improvements and fixes of the previous commits.

##### EXTRA NOTES:

I know that MaNGOS structure is not the same as AC but that doesn't mean we can't use their logic for the pet movement.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/fc3fec3deb55cf144d89fc1ae288183e7f5b36ba

**Comment by Viste** [comment]
> I know that MaNGOS structure is not the same as AC but that doesn't mean we can't use their logic for the pet movement.
MaNGOS is grandpa of AC so its ok to use it :D

**Comment by BarbzYHOOL** [comment]
I don't remember it being like that on blizzard servers but it's certainly better.

By the way, there are also small pets, guardians, npcs that follow you (escort quests) or when a player /follow, what about them?

And should I put this in https://github.com/azerothcore/azerothcore-wotlk/issues/1141 as well?

**Comment by Maurowin** [comment]
The new movement on this video is most blizzlike than today.

**Comment by Kitzunu** [comment]
cc @Yehonal

**Comment by lineagedr** [comment]
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/c9961e6a94b021d2c7bfef086ba9b694a4c2609a
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/0cf82dc50b2d0bff5cd54211e4b39249fe38b0b5
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/84931537fce20799c361bd404a336ad9a19a7abe
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/1bac4289d7fa6de3911c3ffde7056cc32a048fea
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/f2ee7412bc83b799640afcd184d90f055fb7a618
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/05bdaf47fb1ef9b3b1cd258aed0a573cd1b7e369
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/c2a676b774e16c2cb716679fdc576b42ac472169
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/a2b5c104469cea489f7f7514cf5e3204d59e4a41
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/479437f8d6b5efb30fa33c1c5a437e060b9a773c
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/1f93a67e041ff4a4c1c38ddda8fd24a5db2d0c36
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/26e58239138e9a9a48ddf8654b5c1a5ed99023ea
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/b8802ccaa29a992282a28835db7df572d7b2b9f1
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/0ea220087919154be5462588daf6abb4c9bc83d4
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/749fdc06d16c1fc57d0cb4c0c8cc97d08f4fd6c8
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/dbe365844ba6312c2f74eeed4b071c77aff08b96
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/724121fbb9051ad2e68713fb4c139c17f3b8c995
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/1646f2a53da77ef7de7be301155b0d9f5608bad9
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/d49579395ef38d8ba4009846da0ff4009fe69504
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/416b0edd51665c3d1e330c76dde8884d3670fca7
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/7b62f5ac56ad6f6de68f9e103e6c1b78b213d34d
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/pull/124

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/1becd73f09764e9e6ae27f35efdb514e860b12bf
