### ISSUE TITLE
(Death Knight) Pet "Risen Ghoul" has no name

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#2942]
**(Death Knight) Pet "Risen Ghoul" has no name**

##### SMALL DESCRIPTION:
The pet ghoul for death knights has no individual name and is just called "Risen Ghoul" by the game.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Every time the ghoul is summoned, they should receive a random name (e.g. like Tombmuncher).

##### CURRENT BEHAVIOUR:
When using the spell "Raise Dead" the pet ghoul will spawn and everything works fine, but it will always only be called "Risen Ghoul". However, I noticed that sometimes NPC will address my ghoul by its name (e.g. Tombmuncher).
https://wowgaming.altervista.org/aowow/?spell=46584

##### STEPS TO REPRODUCE THE PROBLEM:
1. Play death knight
2. Use the spell "Raise Dead"
3. (I'm playing an unholy death knight and have the talent "Master of Ghouls", which makes the summoned pet permanent. Nevertheless, a temporary ghoul has this bug too)
https://wowgaming.altervista.org/aowow/?spell=52143

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
c839ce5

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
No modules

##### OTHER CUSTOMIZATIONS:
No customizations

**Comment by Kitzunu** [comment]
I am 99% sure that in WotLK it was always called Risen Ghoul

**Comment by CosmeF** [comment]
This changed with PR #2637. Ghoul names works fine without that PR, as I've tested this too.

**Comment by Kitzunu** [comment]
I would love to see some proof of this, I am uncertain atm of how it worked in WotLK

**Comment by TheWatchingI** [comment]
@CosmeF: Thank you. With this information I was able to revert the changes. My ghoul now has an unique name.

@Kitzunu: After some googling it seems that the beta server for wotlk hadn't unique names for ghouls, but the live version had. https://www.engadget.com/2008-09-10-death-knight-ghouls-baby-name-book.html

For example see this video of wotlk 3.3.5 https://youtu.be/Cp3nIhf2tfk?t=210

Which brings me to the question, why that feature was removed in the first place?

**Comment by Viste** [comment]
haha  testing system fail again.

**Comment by Helias** [comment]
the testing system can't cover everything, but it's better than nothing :sweat_smile:
probably we should test more the PRs or implement unit-tests in someway

**Comment by Viste** [comment]
> implement unit-tests in someway

i think lot about that and i don't see any way

**Comment by Helias** [comment]
@Viste, me too, but what about end-to-end test? I have an idea about this, may in future I will do something.

Anyway we are going too much off-topic.

**Comment by Kitzunu** [comment]
Please don't close before the PR is merged
