### ISSUE TITLE
DB/spell_group_stack_rules: Some groups have stack_rule > 4

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#2948]
##### SMALL DESCRIPTION:

Currently 22 groups have a stack_rule > 4 even though there are only rules 1,2,3,4
Is there anyone that knows why this is, a simple mistake or does it serve some undocumented purpose?

##### STEPS TO REPRODUCE THE PROBLEM:

```sql
SELECT * FROM spell_group_stack_rules WHERE stack_rule > 4; 
```

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/cdf518aba1d16e6a45d363859aa073e0c0170edf

##### OPERATING SYSTEM:

W10

**Comment by frytik** [comment]
If you were looking at wiki then yes. AC wiki is bad in that case. Its like copy from TC wiki where TC have just 4 stack rules, and AC have a lot of more. Just take a look in core. Sunwell did custom stack rule system.

**Comment by BarbzYHOOL** [comment]
can you plz improve the wiki frytik??

**Comment by Kitzunu** [comment]
Where do I check it in the core?

**Comment by frytik** [comment]
`enum SpellGroupSpecialFlags
{
    SPELL_GROUP_SPECIAL_FLAG_NONE               = 0x000,
    SPELL_GROUP_SPECIAL_FLAG_ELIXIR_BATTLE      = 0x001,
    SPELL_GROUP_SPECIAL_FLAG_ELIXIR_GUARDIAN    = 0x002,
    SPELL_GROUP_SPECIAL_FLAG_ELIXIR_UNSTABLE    = 0x004,
    SPELL_GROUP_SPECIAL_FLAG_ELIXIR_SHATTRATH   = 0x008,
    SPELL_GROUP_SPECIAL_FLAG_STACK_EXCLUSIVE_MAX= 0x00F,
    SPELL_GROUP_SPECIAL_FLAG_FORCED_STRONGEST   = 0x010, // xinef: specially helpful flag if some spells have different auras, but only one should be present
    SPELL_GROUP_SPECIAL_FLAG_SKIP_STRONGER_CHECK= 0x020,
    SPELL_GROUP_SPECIAL_FLAG_BASE_AMOUNT_CHECK  = 0x040,
    SPELL_GROUP_SPECIAL_FLAG_PRIORITY1          = 0x100,
    SPELL_GROUP_SPECIAL_FLAG_PRIORITY2          = 0x200,
    SPELL_GROUP_SPECIAL_FLAG_PRIORITY3          = 0x400,
    SPELL_GROUP_SPECIAL_FLAG_PRIORITY4          = 0x800,
    SPELL_GROUP_SPECIAL_FLAG_MAX                = 0x1000,
};

enum SpellGroupStackFlags
{
    SPELL_GROUP_STACK_FLAG_NONE                 = 0x00,
    SPELL_GROUP_STACK_FLAG_EXCLUSIVE            = 0x01,
    SPELL_GROUP_STACK_FLAG_NOT_SAME_CASTER      = 0x02,
    SPELL_GROUP_STACK_FLAG_FLAGGED              = 0x04, // xinef: just a marker
    SPELL_GROUP_STACK_FLAG_NEVER_STACK          = 0x08,
    SPELL_GROUP_STACK_FLAG_EFFECT_EXCLUSIVE     = 0x10,
    SPELL_GROUP_STACK_FLAG_MAX                  = 0x20,

    // Internal use
    SPELL_GROUP_STACK_FLAG_FORCED_STRONGEST     = 0x100,
    SPELL_GROUP_STACK_FLAG_FORCED_WEAKEST       = 0x200,
};`

**Comment by Kitzunu** [comment]
hm... and I suppose you are able to stack these rules? i.e Rule 1+8+20?

**Comment by frytik** [comment]
Yes you can

**Comment by Kitzunu** [comment]
Okay... interesting.
Thank you for your help :)
