### ISSUE TITLE
(DB/Quest): Rescue OOX-09/HL!

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#2949]
https://wowhead.com/quest=836/rescue-oox-09-hl
**SMALL DESCRIPTION**:

After you pass the egg, the quest appears to accompany the chicken to the end of the path before protecting the quest 3 attackers attack you kill you will walk a couple of meters the quest is protected. The problem is this: as soon as you kill these 3 owls there are new 3 you kill them and 3 more in a circle the quest is unable to defend itself due to recurrence and the chickens cannot fight the quest forever in battle

**STEPS TO REPRODUCE THE PROBLEM**:

    1. .q add 836
    2. .tele thehinterlands

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 30dceb3+ 2020-04-22 +0200

**OPERATING SYSTEM**: Debian 9

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, RewardPlayedTime, PvPTitles

**Comment by Knindzagxg** [comment]
I can confirm this.
Started writing fix long time ago but never finished.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg you can add the `Confirmed` label in cases like this :)

**Comment by Geekena** [comment]
tried aswell and bug is there

**Comment by PivanDepolo** [comment]
As I understand it, this NPC is not even in the database?
