### ISSUE TITLE
Server Crash.

### ISSUE THREAD

**Issue by Ramys** [azerothcore/azerothcore-wotlk#295]
**Description**:

Server crashing after a few hours
**Current behaviour**: Tell us what happens
I have to reinstall the databases to fly to normal
**Expected behaviour**: Tell us what should happen instead
master

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  AzerothCore rev. 068ac593cb28

**Operating system**:  
win 10
**Modules**:  Are you using modules? if yes, list them
transmogrifier
**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
please provide crash log

**Comment by Ramys** [comment]
[crash.txt](https://github.com/azerothcore/azerothcore-wotlk/files/673076/crash.txt)
 this is

**Comment by talamortis** [comment]
please try in debug mode, as this is release.

**Comment by Ramys** [comment]
ok
