### ISSUE TITLE
(DB/Quest): wrong Spanish translation

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#2953]
##### SMALL DESCRIPTION:
The quest [5261](https://es.wowhead.com/quest=5261/deprecated-eagan-desollapelambres) has the wrong title `Eagan Desollapieles` in the Spanish translation, it should be ~~`Eagan Desollapieles`~~ `Eagan Desollapelambre`

Moreover, looking around in the web I found this: https://github.com/smaitch/Grail
We could take several translations from this.

##### STEPS TO REPRODUCE THE PROBLEM:
- use a esES  client
- `.q add 5261`
- compare the translation with [wowhead](https://es.wowhead.com/quest=5261/deprecated-eagan-desollapelambres)

##### BRANCH(ES):

master

**Comment by Kitzunu** [comment]
Actually it should be `Eagan Desollapelambres` according to Spanish WoWHead https://es.wowhead.com/quest=5261/deprecated-eagan-desollapelambres

**Comment by Helias** [comment]
3.3.5a should be correct, indeed, I wrote `Eagan Desollapieles` should be `Eagan Desollapieles` I would mean `Eagan Desollapelambres` xD.

**Comment by Kitzunu** [comment]
Cool :D

**Comment by Kitzunu** [comment]
in 
```sql
SELECT * FROM quest_template_locale WHERE id = 5261
```
for esES it is correct

**Comment by Kitzunu** [comment]
Was fixed in some PR, dont know, but is right in DB
