### ISSUE TITLE
Release spirit while in combat inside instances/raids

### ISSUE THREAD

**Issue by chamorrorenzo** [azerothcore/azerothcore-wotlk#2954]
##### SMALL DESCRIPTION:
you can release spirit while in combat inside instances/raids

##### EXPECTED BLIZZLIKE BEHAVIOUR:
you shouldnt be able to release your spirit while fighthing  a boss in instances or raids

##### CURRENT BEHAVIOUR:
After entering combat in raid or instance with a boss, you can release your spirit and get back to the instance while your party is fighthing the boss, in raids you cant enter but you still can release your spirit

##### STEPS TO REPRODUCE THE PROBLEM:

1. enter an instance with more than 2 people
2. fight the boss and one of you die
3. release spirit and try to enter the raid/instance

##### EXTRA NOTES:

maybe im beeing dumb, and there is some config I just need to disable ( I checked and there isnt) but this shouldnt be happening right?
##### BRANCH(ES):

master

##### OPERATING SYSTEM:

w7

##### MODULES:

no modules use

##### OTHER CUSTOMIZATIONS:

its a clean compile I just did

**Comment by Kitzunu** [comment]
Have you tested more than one instance?

If yes, then there is something fishy about it, but if you only tested one instance and one boss there may perhaps be a flag from that boss that is missing

**Comment by Si1ker** [comment]
"EXPECTED BLIZZLIKE BEHAVIOUR:
you shouldnt be able to release your spirit while fighthing a boss in instances or raids"

that's a lie.. lol  instance will be locked during encounter, you can **always** release spirit at any point int he game.
