### ISSUE TITLE
"unk" columns in broadcast_text

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2959]
http://www.azerothcore.org/wiki/broadcast_text

In our DB we have "unk1" and "unk2", i guess we need to port the commit that changed these from TC or just rename them damnit

**Comment by Kitzunu** [comment]
EmoteID, Flags are the two missing

**Comment by BarbzYHOOL** [comment]
on the wiki it says emoteID and type

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/2ff4e85578ec8aca11b7696e8b88f7319b27b2f6
