### ISSUE TITLE
Spell.cpp potential bug in logic

### ISSUE THREAD

**Issue by mishaparem** [azerothcore/azerothcore-wotlk#2961]
Spell.cpp potential bug in logic

##### SMALL DESCRIPTION:

Potential bug in bitwise logic at azerothcore/src/server/game/Spells/Spell.cpp:2836
// first dive into AC source, and haven't progged in C++ in a while, so second set of eyes won't hurt.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Bitwise logic at Spell.cpp:2836 should evaluate to true only if spell hit or spell critical hit.
`(procEx & ( PROC_EX_NORMAL_HIT|PROC_EX_CRITICAL_HIT))`

##### CURRENT BEHAVIOUR:

Bitwise logic evaluates to true regardless.
`((procEx & PROC_EX_NORMAL_HIT) | PROC_EX_CRITICAL_HIT)`

##### STEPS TO REPRODUCE THE PROBLEM:

1. open azerothcore/src/server/game/Spells/Spell.cpp
2. goto line 2836
3. read source

##### EXTRA NOTES:

Justification:
(some_var | some_non_zero_const) // always evaluates true
current:
( procEx & PROC_EX_NORMAL_HIT ) // evaluates true if normal hit
( ) | PROC_EX_CRITICAL_HIT // always evaluates true, because PROC_EX_CRITICAL_HIT is non-zero const

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit 03a7becfb133c4178ad705c55056b84b14df9e24

##### OPERATING SYSTEM: 

OpenSuse Tumbleweed

##### MODULES: 

no

##### OTHER CUSTOMIZATIONS: 

C++11 build fixes
-  [Rule of Three](https://en.cppreference.com/w/cpp/language/rule_of_three) applied so as to build successfully
- Misleading indentations (potential bugs here as well, will create separate issues for review and add links)

**Comment by BarbzYHOOL** [comment]
explain why the spell should work like that too please

**Comment by mishaparem** [comment]
> explain why the spell should work like that too please

line 2835:
// Xinef: ofc count only spells that HIT the target, little hack used to fool the system

Comment on the line before says action should be performed only on successful hit.
Successful hit includes normal hit (PROC_EX_NORMAL_HIT) and critical hit (PROC_EX_CRITICAL_HIT). So successful hit counts if procEx matches one of the two values.

**Comment by solidmaxtor** [comment]
What spell is? 2835 or 2836 ?
spell 2835 not exist, or you refer for line ?

**Comment by mishaparem** [comment]
> What spell is? 2835 or 2836 ?
> spell 2835 not exist, or you refer for line ?

Referring to line number in Spell.cpp file

**Comment by mishaparem** [comment]
I thought I would invest a little time into testing this out. Conclusion:
- There's definitely a bug in the code as it is in the master branch.
- Bitwise logic might not be applicable here at all. See below:
**Code:**
```
 int main()
{
    int PROC_EX_NORMAL_HIT = 5;
    int PROC_EX_CRITICAL_HIT = 7;
    int procEx_zero = 0;
    int procEx_norm = 5;
    int procEx_crit = 7;
    int procEx_bad = 2;
    printf("PROC_EX_NORMAL_HIT:%d | PROC_EX_CRITICAL_HIT:%d | procEx_zero:%d | procEx_norm:%d | procEx_crit:%d | procEx_bad:%d\n",PROC_EX_NORMAL_HIT,PROC_EX_CRITICAL_HIT,procEx_bad,procEx_zero,procEx_norm,procEx_crit);
    // current behaviour
    printf("procEx_zero:%d | procEx_norm:%d | procEx_crit:%d | procEx_bad:%d\n",
    ((procEx_zero & PROC_EX_NORMAL_HIT) | PROC_EX_CRITICAL_HIT),
    ((procEx_norm & PROC_EX_NORMAL_HIT) | PROC_EX_CRITICAL_HIT),
    ((procEx_crit & PROC_EX_NORMAL_HIT) | PROC_EX_CRITICAL_HIT),
    ((procEx_bad & PROC_EX_NORMAL_HIT) | PROC_EX_CRITICAL_HIT));
    //proposed:
    printf("procEx_zero:%d | procEx_norm:%d | procEx_crit:%d | procEx_bad:%d\n",
    (procEx_zero & (PROC_EX_NORMAL_HIT | PROC_EX_CRITICAL_HIT)),
    (procEx_norm & (PROC_EX_NORMAL_HIT | PROC_EX_CRITICAL_HIT)),
    (procEx_crit & (PROC_EX_NORMAL_HIT | PROC_EX_CRITICAL_HIT)),
    (procEx_bad & (PROC_EX_NORMAL_HIT | PROC_EX_CRITICAL_HIT)));
    //proposed:
    printf("procEx_zero:%d | procEx_norm:%d | procEx_crit:%d | procEx_bad:%d\n",
    ((procEx_zero & PROC_EX_NORMAL_HIT) | (procEx_zero & PROC_EX_CRITICAL_HIT)),
    ((procEx_norm & PROC_EX_NORMAL_HIT) | (procEx_norm & PROC_EX_CRITICAL_HIT)),
    ((procEx_crit & PROC_EX_NORMAL_HIT) | (procEx_crit & PROC_EX_CRITICAL_HIT)),
    ((procEx_bad & PROC_EX_NORMAL_HIT) | (procEx_bad & PROC_EX_CRITICAL_HIT)));
    return 0;
}
```
**Output:**

> PROC_EX_NORMAL_HIT:5 | PROC_EX_CRITICAL_HIT:7 | procEx_zero:2 | procEx_norm:0 | procEx_crit:5 | procEx_bad:7
> procEx_zero:7 | procEx_norm:7 | procEx_crit:7 | procEx_bad:7 // always true
> procEx_zero:0 | procEx_norm:5 | procEx_crit:7 | procEx_bad:2 // procEx_bad - wrong behavior
> procEx_zero:0 | procEx_norm:5 | procEx_crit:7 | procEx_bad:2 // procEx_bad - wrong behavior

Can't seem to find how to write the logic properly so that the expression would evaluate true only on normal hit or critical hit. As we can see - when the value of procEx is neither PROC_EX_NORMAL_HIT nor PROC_EX_CRITICAL_HIT, it will evaluate as whatever value procEx is. If procEx > 0, then it will evaluate as true.

**Comment by UltraNix** [comment]
Logic already corrected.
