### ISSUE TITLE
(DB/Quest): Tomb of the Lightbringer

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#2967]
##### SMALL DESCRIPTION:
The npc one is supposed to escort, doesn't engage in battle.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The player is supposed to escort Anchorite Truuen through a ghoul infested graveyard. At some points in the graveyard a bigger number of ghouls spawn, which are supposed to attack the player AND the npc.

##### CURRENT BEHAVIOUR:
Anchorite Truuen ignores all ghouls and is ignored by them. He isn't attacked, doesn't engage in battle, if the player is attacked, or reacts in any way. Anchorite Truuen has a pretty high walking speed (he is running the whole time) and since he doesn't stop for battle, he will run out of range while the player is fighting and immediately despawn. This makes the quest basically impossible, at least if one isn't a much higher level to one-hit the ghouls or ignore them too.
https://wotlk.evowow.com/?quest=9446

##### STEPS TO REPRODUCE THE PROBLEM:
1. Finish the prerequisite https://wotlk.evowow.com/?quest=9474, given by Anchorite Truuen in the western plaguelands.
2. Start the quest "Tomb of the Lightbringer", given by Anchorite Truuen.
3. Follow him through the graveyard.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
autobalance
morphsummon
solocraft
solo-lfg

##### OTHER CUSTOMIZATIONS:
none

**Comment by Hacaw** [comment]
CONCLUSION
---
I can reproduce this issue.

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Helias** [comment]
Thank you @Hacaw for all the tests that you are doing, good job :rocket:
