### ISSUE TITLE
(DB/Quest): A Dire Situation

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#2968]
##### SMALL DESCRIPTION:
A shrunken wolf still attacks you and you can use the shrinking powder again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You engage a wolf, use the quest item on him, he gets a debuff, shrinks and stops attacking you.

##### CURRENT BEHAVIOUR:
Shrinking a wolf counts twice for the quest (should only count once), the shrunken wolf keeps attacking you and you can use the shrinking powder again on the same wolf while he still has the debuff from the powder. https://wotlk.evowow.com/?quest=10506

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to Rina Moonspring https://wotlk.evowow.com/?npc=21066 
2. Start the quest "The Encroaching Wilderness" https://wotlk.evowow.com/?quest=10455 and follow the questline until you geht "A Dire Situation" (the fourth and last quest in the questline)
3. Use the quest item "Rina's Diminution Powder" https://wotlk.evowow.com/?item=30251 on the quest mobs.

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
autobalance
morphsummon
solocraft
solo-lfg

##### OTHER CUSTOMIZATIONS:
none

**Comment by Helias** [comment]
@TheWatchingI there is a fix for this, you can test it https://github.com/azerothcore/azerothcore-wotlk/pull/2974 :wink:
