### ISSUE TITLE
Warsong Champion and Valiance Expedition Champion in Wintergrasp

### ISSUE THREAD

**Issue by Irome** [azerothcore/azerothcore-wotlk#297]
**Description**: There are not NPCs Warsong Champion and Valiance Expedition Champion in their corresponding locations within the map of Wintergrasp, namely in the 3 bridges, the streets of WG and in the workshop. They are not present both before and after the battle.

**Expected behaviour**:

Warsong Champion:
http://www.wowhead.com/npc=30739/warsong-champion

Valiance Expedition Champion:
http://www.wowhead.com/npc=30740/valiance-expedition-champion

**AC hash/commit**:  068ac593cb2894a16f3bfa78867fd901fc3122ed

**Comment by Azzaleo** [comment]
Principally on Workshop's the problem is the same ( need 10 guards for a Workshop )

**Comment by gengarshadowball** [comment]
Wowhead is updated for the latest expansions so without proof is going to be hard to accurately add more defenders and attackers, however I'll try my best to reproduce this as much as I can. Feel free to give information via sniff about their positions.
