### ISSUE TITLE
Warlock destruction: BUG "Conflagrate"

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#298]
**Description**:
To conflagrate is not instantaneous
**Current behaviour**: Tell us what happens
When you use http://wotlk.evowow.com/?spell=61290 / http://wotlk.evowow.com/?spell=47811
Does not activate immediately  http://wotlk.evowow.com/?spell=1796, has a delay of 1 second or 2
**Expected behaviour**: Tell us what should happen instead
When you use: Immolate or Shadowflame, Conflagrate  Should be activated immediately
**Steps to reproduce the problem**:

1. With the active talent to conflagrate, make the following rotation
2. Use "Immolate" or "Shadowflame"
3. And finally "Conflagrate"

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/068ac593cb2894a16f3bfa78867fd901fc3122ed

**Modules**:  Are you using modules? if yes, list them
Transf
anticheat

**Comment by Irome** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/296

**Comment by talamortis** [comment]
this spell should have a global cooldown like all spells.

**Comment by Sworken** [comment]
I know, but even so after the load it takes a little longer to activate

**Comment by talamortis** [comment]
Fixed. will push later

**Comment by lineagedr** [comment]
WRONG it's actually blizzlike props to the Sunwell team for finding the delay and adding it to Conflagrate https://youtu.be/KUizH_eVcuA?t=209 so it's working as intended.
