### ISSUE TITLE
Allow to override spells in spell_dbc

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2994]
```
Index 69683 already exists in dbc:'spell_dbc'                                                                                                       
Some required *.dbc files (1 from 101) not found or not compatible:
/worldserver_1/data/dbc/Spell.dbc exists, and has 234 field(s) (expected 234). Extracted file might be from wrong client version or a database-update has been forgotten.
```

We cannot override a spell by creating a spell with similar ID in `spell_dbc` table and it's kinda annoying. If we do, the worldserver doesn't even start.

We should be able to override spells one by one if we wanted. This way we don't have to edit the DBC

**Comment by Yehonal** [comment]
I've put this issue inside the related project board: https://github.com/azerothcore/azerothcore-wotlk/projects/13

We will work on it while refactoring the system

**Comment by Kitzunu** [comment]
Wouldn't we still need to edit the DBC if we want to display the changes on the Client?

**Comment by Shard-MW** [comment]
> Wouldn't we still need to edit the DBC if we want to display the changes on the Client?

Yes

**Comment by Yehonal** [comment]
> Wouldn't we still need to edit the DBC if we want to display the changes on the Client?

If you're using the official wow client then you need to do it for the 60% of the DBCs, yes.

PS We should create the list of the DBCs that can be changed server side without modify the client, is someone interested doing it?

**Comment by FrancescoBorzi** [comment]
> PS We should create the list of the DBCs that can be changed server side without modify the client, is someone interested in doing it?

I guess many people would be interested in having such a feature. Not sure who might be available to actually work on it though.

**Comment by Shadowfiende** [comment]
https://user-images.githubusercontent.com/63067250/89230748-2efb1000-d5f9-11ea-8691-6595c0fd5809.png
