### ISSUE TITLE
(DB/Creature): Timmy the Cruel

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#2998]
##### SMALL DESCRIPTION:
The stratholme boss Timmy the Cruel endlessly respawns.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Some time after clearing the square in front of the monastery and entering the building Timmy the Cruel spawns in the square. There one can engange him and kill him like every other boss in the dungeon.

##### CURRENT BEHAVIOUR:
All of the above  happens, only that Timmy respawns multiple times - at least until you have cleared the monastery completely. This way one can kill him more than once.
https://wotlk.evowow.com/?npc=10808

##### STEPS TO REPRODUCE THE PROBLEM:
1. Enter Stratholme
2. Clear the square of the scarlet monastery in Stratholme 
3. Enter the building and wait some time.
4. Timmy spawns outisde in the square -> you can kill him.
5. Repeat steps 3 & 4

##### EXTRA NOTES:
I'm not sure, if the process stops after killing Balnazzar.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
c839ce5

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
autobalance
solocraft
solo-lfg

##### OTHER CUSTOMIZATIONS:
None

**Comment by Hacaw** [comment]
CONCLUSION
---
For me Timmy didn't spawn at all.
So instead I tried to do .npc add 10808 and I saw nothing was spawned, so I switch to gm and observed that Timmy is available only when gm is on, probably this means he is a phase.

The boss in the back is the original one, the 2 from the front are the one spawned by me, all are visible with gm-on.
![image](https://user-images.githubusercontent.com/6963500/102016981-99247e00-3d6c-11eb-92db-2fbd28dacf08.png)



TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Kitzunu** [comment]
Test this https://github.com/TrinityCore/TrinityCore/commit/c69825d96d6c7ff847c196c908e1040cb7a8d5db

**Comment by avarishd** [comment]
@Kitzunu This has been fixed some time ago with the condition table

He's spawned with the instance, but set to friendly faction and with visibility OFF, then when all NPCs (10418/10419/10424) within 40yards are killed, SAI ID 5 is ran, which sets his faction to 21 (Undead, Scourge) and that is the link for SAI ID 6, which set visibility ON.
He does not yell on "spawn", can maybe mock up a quick pr, but this is not part of this issue. Also, he doesn't respawn.


conditions
---
| SourceTypeOrReferenceId | SourceGroup | SourceEntry | SourceId | ElseGroup | ConditionTypeOrReference | ConditionTarget | ConditionValue1 | ConditionValue2 | ConditionValue3 | NegativeCondition | ErrorType | ErrorTextId | ScriptName | Comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | 
| 22 | 6 | 10808 | 0 | 0 | 29 | 1 | 10418 | 40 | 0 | 1 | 0 | 0 |  | Run action if no npcs in range | 
| 22 | 6 | 10808 | 0 | 0 | 29 | 1 | 10419 | 40 | 0 | 1 | 0 | 0 |  | Run action if no npcs in range | 
| 22 | 6 | 10808 | 0 | 0 | 29 | 1 | 10424 | 40 | 0 | 1 | 0 | 0 |  | Run action if no npcs in range |
