### ISSUE TITLE
[Core/Spells] Hunter spell does not work correctly

### ISSUE THREAD

**Issue by Axaxxax** [azerothcore/azerothcore-wotlk#3000]
##### SMALL DESCRIPTION:

there is a problem when the hunter uses the spirit of a viper and a spell https://classic.wowhead.com/spell=14295/volley  mana does not regenerate from this spell

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The ability https://classic.wowhead.com/spell=14295/volley under the spell (Spirit of the Viper) should regenerate the hunter's mana from each shot

##### STEPS TO REPRODUCE THE PROBLEM:

1. Take a character class hunter
2. Use "Viper Spirit" (restores mana from a shot)
3. Use spell https://classic.wowhead.com/spell=14295/volley on any hostile creature

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c9b7c75

##### OPERATING SYSTEM:

Windows 10 x64

**Comment by Kitzunu** [comment]
This is wrong
>Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, **but not including the ticks of Serpent Sting or the damage of Volley**) to generate a percentage of the Hunter's maximum mana.

Source: [WoWWiki October 4th 2009](https://wowwiki.fandom.com/wiki/Aspect_of_the_Viper?oldid=2065531)

**Comment by Axaxxax** [comment]
@Kitzunu 
To find the amount of mana each shot will return the following formula should be used:
Mana Return = Base Mana * 0.03075
For example; If your base mana is 10,000 then you will be regenerating 307.5 mana per shot, rounded up to 308 for some shots and rounded down to 307 for others.

Source: [WoWWiki October 4th 2009](https://wowwiki.fandom.com/wiki/Aspect_of_the_Viper?oldid=2065531)

how it works on [AC](https://youtu.be/Djs8Uuh4f5M) (my video)
EXPECTED [BLIZZLIKE](https://youtu.be/BXAHW5ihwE4) BEHAVIOUR  (I found this video)

**Comment by Kitzunu** [comment]
we got two issues here:
1. We got a clear source that says Volley does not affect Aspect of the Viper to generate mana
2. Your video is not from retail.
