### ISSUE TITLE
(DB/Quest): Whispers of the Raven God

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3007]
##### SMALL DESCRIPTION:
The fourth prophecy doesn't count toward the quest goal, which makes the quest not completable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Collecting the fourth prophecy should count toward the quest goal.

##### CURRENT BEHAVIOUR:
The quest works basically like it should, it just doesn't progress the quest goal upon receiving the fourth prophecy. https://www.wowhead.com/quest=10607/whispers-of-the-raven-god

##### STEPS TO REPRODUCE THE PROBLEM:
1. Start the quest https://www.wowhead.com/quest=10607/whispers-of-the-raven-god
2. Go to (40, 23) - the totem for the fourth prophecy is on the camp ground.
3. Kill the Harbringer in the hut on the right side of the totem. You will receive a buff, which allows you to interact with the totem.
4. Use the totem

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by Kitzunu** [comment]
I can't even get Prophesy 1-3 to work

**Comment by buddiman** [comment]
I could finish the quest without a problem.
![grafik](https://user-images.githubusercontent.com/10009755/123793845-7a3da180-d8e2-11eb-9801-bf2ed0538471.png)

It is normal that you may need to kill more than one Arakkoa to get the buff for interacting with the totems.

Tested on https://github.com/azerothcore/azerothcore-wotlk/commit/f1727b79d251ec28775796a45cfb669b1c346b66

**Comment by IntelligentQuantum** [comment]
It works fine for me.
