### ISSUE TITLE
(DB/Quest): Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3008]
##### SMALL DESCRIPTION:
The enemy attacks not the quest vehicle, but the player directly and basically two-hits them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You take control over Teron Gorefiend and use his abilities to fight against Karsius the Ancient Watcher. Karsius on the other hand attacks Teron together with a few spirits, which shoot lightning at him.

##### CURRENT BEHAVIOUR:
Karsius the Ancient Watcher is a very strong elite mob and instead of attacking Teron Gorefiend, which the player controls, he directly attacks the player and kills them in record time. This makes it impossible to win the fight.

##### STEPS TO REPRODUCE THE PROBLEM:
1. You start the questline with "A Ghost in the Machine" https://www.wowhead.com/quest=10642/a-ghost-in-the-machine
2. You continue the questline until you're send to the Ancient Shadowmoon Spirit https://www.wowhead.com/npc=21797/ancient-shadowmoon-spirit
3. You follow his questline until you get "Teron Gorefiend, I am..." https://www.wowhead.com/quest=10645/teron-gorefiend-i-am
4. You will need to equip "Spectrecles" from "A Ghost in the Machine" to be able to see Karsius https://www.wowhead.com/item=30719/spectrecles

##### EXTRA NOTES:
The quest exists two times: One for the Alliance and one for the Horde. I only tested the Alliance one.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by Kitzunu** [comment]
Could this be related to some threat bug?

I even added an SAI so that he should in combat should attack Teron Gorfiend GUID 86139 and Entry 21867 yet he still runs to the player.

My guess is that somehow threat gets redirected towards the player instead of the creature itself. I tried this by attacking another mob with Teron Gorfiend in possession.

**Comment by TheWatchingI** [comment]
I had the feeling too that it was somehow connected with the threat level of the player. Furthermore I was surprised that it was possible for Karsius to attack the player in the first place.

**Comment by Kitzunu** [comment]
it is because the player is still there, just as a "spirit"

**Comment by Gultask** [comment]
Can't reproduce anymore unless I specifically .damage Karsius
