### ISSUE TITLE
(DB/Quest): The Fel and the Furious

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3011]
##### SMALL DESCRIPTION:
The range of the controlled mob only covers half ot the quest area.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
One uses a control console to take over a Fel Reaver and uses their abilities to kill the quest mobs.

##### CURRENT BEHAVIOUR:
Only half of the area with the quest mobs is in range of the control console. If the Fel Reaver steps out of it, one loses the connection. This makes half of the quest mobs unavailable, which makes it necessary to wait for respawn. This makes the quest rather difficult, since it is timed and has to be done in 5 minutes. 
Additionally, after losing control of a Fel Reaver, the Reaver doesn't walk back to its starting position but to the player, because they're in combat with each other (even though the Reaver doesn't actually attack).

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Start the quest and try it out https://www.wowhead.com/quest=10612/the-fel-and-the-furious

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by LukasVolgger** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3605
