### ISSUE TITLE
[GENERAL] Build fails with unknown type name 'my_bool'

### ISSUE THREAD

**Issue by Statscowski** [azerothcore/azerothcore-wotlk#3012]
I am on Ubuntu Server 20 LTS and following the classic installation guide.

Any insight would be greatly appreciated. 

The step jmake -4 fails with:

> root@kris ~/git/azerothcore-wotlk/build # make -j 4
[  0%] Built target fmt
[  0%] Built target Detour
[  3%] Built target lualib
[  7%] Built target g3dlib
[  9%] Built target Recast
[ 10%] Built target gsoap
[ 13%] Built target jemalloc
[ 13%] Building CXX precompiled header src/common/cotire/common_CXX_prefix.hxx.pch
[ 13%] Built target revision.h
In file included from /root/git/azerothcore-wotlk/build/src/common/cotire/common_CXX_prefix.hxx:4:
In file included from /root/git/azerothcore-wotlk/build/src/common/cotire/common_CXX_prefix.cxx:4:
In file included from /root/git/azerothcore-wotlk/src/common/PrecompiledHeaders/commonPCH.h:6:
In file included from /root/git/azerothcore-wotlk/src/common/Database/SQLOperation.h:13:
/root/git/azerothcore-wotlk/src/common/Database/QueryResult.h:87:9: fatal error: unknown type name 'my_bool'
        my_bool* m_isNull;
        ^
1 error generated.
CMake Error at /root/git/azerothcore-wotlk/deps/cotire/CMake/cotire.cmake:1990 (message):
  cotire: error 1 precompiling
  /root/git/azerothcore-wotlk/build/src/common/cotire/common_CXX_prefix.hxx.
Call Stack (most recent call first):
  /root/git/azerothcore-wotlk/deps/cotire/CMake/cotire.cmake:3694 (cotire_precompile_prefix_header)

>make[2]: *** [src/common/CMakeFiles/common.dir/build.make:64: src/common/cotire/common_CXX_prefix.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:981: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by FrancescoBorzi** [comment]
@Statscowski can you please tell us what your clang version is?

also include details about the AC version you're using

**Comment by Statscowski** [comment]
Sure!.

clang --version output:

>clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

AC version should be master? I literally cloned https://github.com/azerothcore/azerothcore-wotlk about an hour ago.

Should I try cloning a specific release instead of master?

**Comment by Kitzunu** [comment]
This is an error you only get on MySQL 8.0 which is not supported

**Comment by Kitzunu** [comment]
Why? MySQL stopped supporting my_bool in 8.0

**Comment by Statscowski** [comment]
> Why? MySQL stopped supporting my_bool in 8.0

Oh, all righty! 

Good to know thank you. Ubuntu 20 might be just too new then.

**Comment by Kitzunu** [comment]
If you really want to use MySQL 8.0 you can pull this PR https://github.com/azerothcore/azerothcore-wotlk/pull/2896 it will allow support for it, but it is not officially supported
