### ISSUE TITLE
Shadowmourne: Soul Fragment Proc

### ISSUE THREAD

**Issue by Irome** [azerothcore/azerothcore-wotlk#302]
**Description**:

1. The effect Soul Fragment (http://www.wowhead.com/spell=71905/soul-fragment) of Shadowmourne (http://www.wowhead.com/spell=71903/item-shadowmourne-legendary) not it's correct. The aura of the spell proc chance is 100%.
2. If you try to use the Shadowmourne in any BG, the Soul Fragment no procs, it does not work.

**Current behaviour**:

1. The proc of the Soul Fragment increases with each melee ability.
2. The proc of the Soul Fragment does not work in BG.

**Expected behaviour**:

1. It is a touchy subject. There are many theories about it. However, the issue was discussed and solved on TC: https://github.com/TrinityCore/TrinityCore/issues/1619
2. The proc of the Soul Fragment should work in BG.

I quote here the proper functioning of Shadowmourne:
http://www.wowpedia.org/Shadowmourne

THE PROBLEM HAS BEEN SOLVED ON TC, SUFFICIENT TO IMPLEMENT THE COMMENTS: https://github.com/TrinityCore/TrinityCore/commit/2ff855054f52bf2dcf81aa7a7da7bab7f8a99686

**Branch(es)**: Master

**AC hash/commit**: 7025bad000e31ed1bd058e4f94b19fe832f9d28a

**Comment by justdothings** [comment]
![img_1060](https://cloud.githubusercontent.com/assets/17615911/21545308/220bafea-cdf0-11e6-8e0d-b69ae95fd27e.PNG)
Its disabled by xnief you can comment this lines,

**Comment by ShinDarth** [comment]
@justdothings feel free to open a PR for whatever you think that needs to be changed :+1:

**Comment by Yehonal** [comment]
Well this is fixed at half, because the proc bug is still there i think.
Dunno if it's better to open a new issue with only proc  bug or keep it
open modifying the issue itself

Il 01/Gen/2017 15:39, "Francesco Borzì" <notifications@github.com> ha
scritto:

**Comment by ShinDarth** [comment]
I guess it's better to open a new one

**Comment by falzard** [comment]
I can't help but think "Why Xinef did that?" (in fact I think "Xinef = retard" but I can't say this)
