### ISSUE TITLE
C++11 Rule of three/five/zero warning fixes

### ISSUE THREAD

**Issue by mishaparem** [azerothcore/azerothcore-wotlk#3021]
C++ 11 Rule of 3 requirement

##### SMALL DESCRIPTION:

C++11 issues warning if Rule of 3 not met:

> If a class requires a user-defined destructor, a user-defined copy constructor, or a user-defined copy assignment operator, it almost certainly requires all three.
https://en.cppreference.com/w/cpp/language/rule_of_three

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No warnings issued while building.

##### CURRENT BEHAVIOUR:

Warnings issued during build.
https://paste2.org/xEUhbXXj

##### STEPS TO REPRODUCE THE PROBLEM:

1. Build using C++11 standards

##### EXTRA NOTES:

```
> gcc --version
gcc (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]
```
proposed changes: (from git diff)
https://paste2.org/UM2y8zt7

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit 03a7becfb133c4178ad705c55056b84b14df9e24

##### OPERATING SYSTEM:

<details>
<summary>OpenSuse Tumbleweed</summary>
> cat /etc/os-release<br>
NAME="openSUSE Tumbleweed"<br>
# VERSION="20200425"<br>
ID="opensuse-tumbleweed"<br>
ID_LIKE="opensuse suse"<br>
VERSION_ID="20200425"<br>
PRETTY_NAME="openSUSE Tumbleweed"<br>
ANSI_COLOR="0;32"<br>
CPE_NAME="cpe:/o:opensuse:tumbleweed:20200425"<br>
BUG_REPORT_URL="https://bugs.opensuse.org"<br>
HOME_URL="https://www.opensuse.org/"<br>
LOGO="distributor-logo"<br>
</details>

##### MODULES:

none

##### OTHER CUSTOMIZATIONS:

none

**Comment by Yehonal** [comment]
Can you paste the warnings here please?

**Comment by mishaparem** [comment]
> Can you paste the warnings here please?

updated

**Comment by Yehonal** [comment]
thanks!
