### ISSUE TITLE
World Crash (SIGSEGV, Segmentation fault)

### ISSUE THREAD

**Issue by CosmeF** [azerothcore/azerothcore-wotlk#3028]
Crash log:

https://gist.github.com/CosmeF/c8b4427be4eb5b105723ee8b2d01425a

##### SMALL DESCRIPTION:
Server crash, gdb generated the log above.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Not a clue, sorry

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
f97d494ffc90c3b3dde041564d6b2ca20ec22905

##### OPERATING SYSTEM:
Ubuntu 18.04

##### MODULES:
mod-anticheat-master
mod-boss-announcer
mod-eluna-lua-engine-master
mod-emblem-transfer
mod-premium
mod-reward-played-time-master
mod-transmog-master

##### OTHER CUSTOMIZATIONS:
I've lowered conflarate delay to 0 on https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp#L3928

**Comment by Meltie2013** [comment]
@CosmeF Looks like its related to SAI but its a useless crash log without symbols being loaded, cause the server is compiled in release.

Need a log in Debug or RelWithDebInfo.

**Comment by CosmeF** [comment]
@Meltie2013 Thanks a lot. I've checked the flag for aditional debug code, so hopefuly I'll catch some extra info next time, so I can share it on this issue.

**Comment by hlainin** [comment]
This server error appears periodically. Is there a solution? How to output the error log, my logs are empty. in the logs this error "Segmentation fault"

**Comment by Kitzunu** [comment]
@hlainin You need to build in Debug if you want a useful log

**Comment by Helias** [comment]
@CosmeF, did you solve? is there any progress?

**Comment by CosmeF** [comment]
Server did crash but haven't been able to register a more detailed crash log. Now i'm still waiting for it to crash again and check if the crash log works with some extra flags enabled.

**Comment by Kitzunu** [comment]
Did you build in RelWithDebInfo or Debug this time?

**Comment by CosmeF** [comment]
Yes, the build is now running whith coredebug flag. Still waiting for the crash though.

**Comment by CosmeF** [comment]
Crashed again, segmentation fault. Log appears to be the same than last time. Am I doing something wrong here? I use "-WITH_COREDEBUG=1" option on cmake, using GDB. The modules are the same since last time.

https://gist.github.com/CosmeF/4566730670e4170e42efe167a195f86d

**Comment by Kitzunu** [comment]
I have no idea what system you use, but could you paste the entire line of the Worldserver please?

**Comment by tatense** [comment]
SmartScriptHolder

SMART_EVENT

Map::VisitNearbyCellsOf(WorldObject*

**Comment by CosmeF** [comment]
@Kitzunu Sure, here it is. Sorry for not pointing out the current commit the system is running on.
`AzerothCore rev. 34077115a5de+ 2020-06-18 12:04:56 +0200 (master branch) (Unix, Release) (worldserver-daemon) ready...`

**Comment by Kitzunu** [comment]
You have compiled in **Release** that is why you dont get info from the crash log

I suggest you compile in **RelWithDebInfo**

**Comment by CosmeF** [comment]
Thanks. Now it shows (Unix, RelWithDebInfo). I'll post the log as soon as I can, when the crash shows up again.

**Comment by CosmeF** [comment]
Sorry for the previous logs. Hopefully this helps now.

https://gist.github.com/CosmeF/436a0f273c3c56a967fc64dd79ccf597

Aparently is linked to game object id 124371 (Uldaman "Keystone"?)

**Comment by Kitzunu** [comment]
@P-Kito 
smart_scripts
---
```sql
SELECT * FROM smart_scripts WHERE entryorguid = 124371

```
| entryorguid | source_type | id | link | event_type | event_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | action_type | action_param1 | action_param2 | action_param3 | action_param4 | action_param5 | action_param6 | target_type | target_param1 | target_param2 | target_param3 | target_param4 | target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 124371 | 1 | 4 | 0 | 61 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 38 | 0 | 0 | 0 | 0 | 0 | 0 | 19 | 7228 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | Keystone - On Gossip Hello - Set In Combat With Zone | 

Could this crash have to do with your changes of Combat with zone?

**Comment by Kitzunu** [comment]
@CosmeF Try reverting this commit and come back in a day or two to see if you got a new crash https://github.com/azerothcore/azerothcore-wotlk/commit/f381bd47cb1a1b5c0f4a1e2acab4327e86193e90

**Comment by CosmeF** [comment]
@Kitzunu I've conducted a small test on the test realm. With f381bd4, on AzerothCore rev. 435de8a1355b, the activation of the Keystone on Uldaman started the door unlock sequence, and just after the door shows a blue glow, the server crashes, whith the same error log showed before.

On the same server, but doing a revert to commit f381bd4, the same test showed no crash at all. So I think you were right on pointing this commit as troublesome for this crash.

**Comment by P-Kito** [comment]
since when action 38 is allowed for gameobjects?

**Comment by P-Kito** [comment]
Is this custom SAI? Or blizzlike?

**Comment by Kitzunu** [comment]
It is in the Main repo, so it is nothing custom that he's done

**Comment by P-Kito** [comment]
But I think gameobjects cannot be SetInCombatWithZone O_o

We should limit this action to creatures only, right?

**Comment by P-Kito** [comment]
Is this SAI executed in a dungeon? 
If it is, then it had nothing to do with my changes, since I only touched it when
`IsDungeon()` is true ;-)

**Comment by P-Kito** [comment]
Anyways.
Possible crash fix:
```
        if (!me->GetMap()->IsDungeon())
        {
``` 
change to:

```
        if (me && me->FindMap() && !me->GetMap()->IsDungeon())
        {
``` 

But I dont think that this smart action should actually work for gameobjects ???? 

We can restrict it from loading on gameobjects like the other actions that are limited creatures.

**Comment by Kitzunu** [comment]
Yea sure we could restrict it @P-Kito 


smart_scripts
---
```sql
SELECT * FROM smart_scripts WHERE source_type = 1 AND action_type = 38
```
| entryorguid | source_type | id | link | event_type | event_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | action_type | action_param1 | action_param2 | action_param3 | action_param4 | action_param5 | action_param6 | target_type | target_param1 | target_param2 | target_param3 | target_param4 | target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 124371 | 1 | 4 | 0 | 61 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 38 | 0 | 0 | 0 | 0 | 0 | 0 | 19 | 7228 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | Keystone - On Gossip Hello - Set In Combat With Zone | 

Only that gameobject uses it, but then we'd need to find a workaround (Maybe this is not even blizzlike and not needed?)

**Comment by P-Kito** [comment]
Can a gameobejct be in combat with something?
If no, than this sai can be deleted.

**Comment by Kitzunu** [comment]
If I crossreference to TC, they have no SAI with this Action for Gobs.

**Comment by P-Kito** [comment]
There you have your answer...

**Comment by CosmeF** [comment]
I've got a different segmentation fault crash. Here is the log. If is not related to the previous one, please ignore and I'll post this on another issue. Running: Worldserver crash AzerothCore rev. 34077115a5de+ (master branch) (Unix, RelWithDebInfo)

https://gist.github.com/CosmeF/35b7e8a6697cf44bd96e9dcc6c4930c7

**Comment by Kitzunu** [comment]
not related

**Comment by hlainin** [comment]
Hi, everybody. I have a "Segmentation fault" error. I made a RelWithDebInfo build, but I don't get a report file when the server crashes. Please can you tell me how to get the report file. Debian 9

**Comment by FrancescoBorzi** [comment]
@hlainin https://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by hlainin** [comment]
I didn't ask how to create a theme. I can't get a crash log file

**Comment by CosmeF** [comment]
> 
> 
> Can a gameobejct be in combat with something?
> If no, than this sai can be deleted.

Since I've deleted the conflicting SAI entry, no more crashes have ocurred. I've conducted tests on Uldaman using the keystone, and it shows no problems. So thank you guys.

**Comment by Kitzunu** [comment]
This never got resolved on the core @Helias

**Comment by Helias** [comment]
@CosmeF could you open a PR about this?

**Comment by P-Kito** [comment]
See, just a false SAI... Gameobjects shouldnt "SetInCombatWithZone" :P
