### ISSUE TITLE
Quests: [The Black Knight's Orders] and [At The Enemy's Gates]

### ISSUE THREAD

**Issue by Irome** [azerothcore/azerothcore-wotlk#303]
**Description**: Quests Chain Argent Tournament:
1. [The Black Knight's Orders] http://wotlk.openwow.com/quest=13663
2. [At The Enemy's Gates] http://wotlk.openwow.com/quest=13855

**Current behaviour**:

1.The Black Knight's Orders: After taking the Gryphon, when going to land hangs in the air and disappears.
2. At The Enemy's Gates: In the village there should be a mount for use of the Argent Tournament, it is necessary for the purposes of the quest. In fact the mobs to kill have much life, and have shields which reduce damage :: why the spell of the mounts of 'Argent Tournament are necessary. You can not take the mounts, can not be used, even after wearing the spear.

**Expected behaviour**:

1. In this video you can see how it should work the quest: https://youtu.be/RJrwFyvhNbY?t=120
2. In this video you can see how it should work the quest to 1:04 minutes:
https://youtu.be/Z6uSqv7aOX8?t=62

**Steps to reproduce the problem**:

1. Take the quest [The Black Knight's Orders] and try to do it.
2. Take the quest [At The Enemy's Gates] r try to climb the mount.

**Branch(es)**: Master

**AC hash/commit**:  7025bad000e31ed1bd058e4f94b19fe832f9d28a

**Comment by talamortis** [comment]
@Irome with the quest [The Black Knight's Orders] does the giffen stop in the middle of the sea and dismount? as i thought i fixed this a while back.

**Comment by Rushor** [comment]
maybe it wasn't applied on live realm

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/3356a712c3e0d8346ab76bca5ccf57406c0b8216

**Comment by talamortis** [comment]
@Irome  did u test the fix from before?
