### ISSUE TITLE
(DB/Dungeon/Quest): Missing quest items in Shadow Labyrinth Heroic

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3032]
##### SMALL DESCRIPTION:
Quest items are missing in the heroic mode of the Shadow Labyrinth.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The codex of blood (https://tbcdb.com/?quest=10094) and the soul devices (https://tbcdb.com/?quest=10091) should be available in the Shadow Labyrinth in heroic mode.

##### CURRENT BEHAVIOUR:
The quest items are missing, but only on heroic. In the normal version of the dungeon they are available.

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Add the quests "The Codex of Blood" and "The Soul Devices"
2. Walk through the Shadow Labyrinth in heroic mode

##### EXTRA NOTES:
Like I said: The quests work on normal difficulty.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by wizzymore** [comment]
Hi,

This can be fixed easily, but i can't find proof of the game object being present in the heroic dungeon

**Comment by Racknar0** [comment]
Tested 

![image](https://user-images.githubusercontent.com/38267074/98484959-f4e56f80-21e0-11eb-993c-d32240a35f10.png)


I doubt that the Gobject was in the air but check and your position is correct


![image](https://user-images.githubusercontent.com/38267074/98484974-2827fe80-21e1-11eb-91cc-5e4c55f7c2c3.png)
