### ISSUE TITLE
(DB/Dungeon/Quest): Entry into Karazhan

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3033]
##### SMALL DESCRIPTION:
The mob, which drops the first key fragment for the quest, doesn't spawn.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
There is a container besides Murmur in the Shadow Labyrinth. With the quest Entry into Karazhan (https://tbcdb.com/?quest=9831) you are able to interact with it. Once you do a "First Fragment Guardian" (https://tbcdb.com/?npc=22890) spawns, which drops the quest item. 

##### CURRENT BEHAVIOUR:
The quest mob doesn't spawn when interacting with the container (neither in normal nor heroic mode of the Shadow Labyrinth)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Start the quest Entry into Karazhan
2. Interact with the container beside Murmur in the Shadow Labyrinth

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by Rotzbold** [comment]
He spawns for me. Just not directly at the container like he should but somewhere else in the room.
