### ISSUE TITLE
(DB/Dungeon/Quest): Missing quest mob Lakka in Sethekk Halls Heroic

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3034]
##### SMALL DESCRIPTION:
Lakka, the mob in a cage behind the first boss, is missing in heroic mode.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Lakka should sit in her cage beside the first boss and wait for her rescue. The quest for that is called "Brother Against Brother" (https://www.wowhead.com/quest=29605/brother-against-brother)

##### CURRENT BEHAVIOUR:
In the heroic mode of Sethekk Halls Lakka isn't there.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to the first boss in the Sethekk Halls in heroic and look for a cage.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by r0m1ntik94** [comment]
Try this
```sql
-- Set phase for spawn in heroic too
UPDATE `creature` SET `spawnMask` = 3 WHERE `id` = 18956; -- Olirea
UPDATE `gameobject` SET `spawnMask` = 3 WHERE `id` = 183051; -- Sethekk Cage
```

**Comment by Helias** [comment]
@r0m1ntik94 you can open a PR for the fix, a tester and developers will test and review your code to improve it.

**Comment by Helias** [comment]
@r0m1ntik94 checking the database the `spawnMask` is already 3 for both (creature and gameobject).

May this has been fixed from May to today..?
@TheWatchingI did you test the Quest recently?
