### ISSUE TITLE
Arena.QueueAnnouncer does not work

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#304]
**Description**:

**Current behaviour**: Tell us what happens

Sand announcer does not work when activated
worldserver.conf and worldserver.conf.dist
Arena.QueueAnnouncer.Enable = 1

**Expected behaviour**: Tell us what should happen instead

should announce the sand equipments

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/1eb07581fed648a5791ca48fbb300f35798633de

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

NO

**Comment by Blumfield** [comment]
I think this was also disabled by xinef i'll look tonight
