### ISSUE TITLE
Atal'ai Priest unattackable

### ISSUE THREAD

**Issue by wackinwallaby** [azerothcore/azerothcore-wotlk#3041]
Atal'ai Priest creature unattackabe

##### SMALL DESCRIPTION:

Atal'ai Priest creature in the entrance to Sunken Temple is not able to be attacked and does not attack players.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This creature should be hostile and attack players in range

##### CURRENT BEHAVIOUR:

Creature does not attack players and is not able to be attacked, even with aoe attacks.
![WoWScrnShot_051520_145242](https://user-images.githubusercontent.com/65240021/82106834-8754fc80-96f1-11ea-9923-1b87d0f6438a.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to the entrance of Sunken Temple
2.  Notice the Atal'ai Priest creature is not attackable
3. 

##### EXTRA NOTES:

None
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. f301d817e7d5 2020-05-12 06:08:54 +0000 (master branch) (Unix, Release)

##### OPERATING SYSTEM:

Ubuntu 18.04

##### MODULES:

AHbot
Autobalance

##### OTHER CUSTOMIZATIONS:

None

**Comment by r0m1ntik94** [comment]
Try this
```sql
UPDATE `creature_template` SET `unit_flags` = 32768 WHERE `entry` = 5269; -- Atal'ai Priest
```

**Comment by wackinwallaby** [comment]
That worked nicely! thank you for the help..

**Comment by FrancescoBorzi** [comment]
@r0m1ntik94 can you please [create a PR](http://www.azerothcore.org/wiki/How-to-create-a-PR) with it?
