### ISSUE TITLE
Blackwing Lair Issues [$45]

### ISSUE THREAD

**Issue by cts17** [azerothcore/azerothcore-wotlk#3042]
##### SMALL DESCRIPTION: 
A report on issues inside Blackwing Lair

**Razoregore the Untamed** (12435)
a) should destroy (19873) the eggs (177807) when mind controlled using the Orb of Domination (177808)
b) should aggro raid after last egg has been destroyed, using Fireball Volley (22425)
c) adds should have abilities, like the Blackwing Mage (12420) should cast Fireball (17290), and use Arcane Explosion (22271) if engaged by melee)

There's an existing issue for this boss from a year ago #785 . I think for now we should just enable the portcullis to remain open and bypass this boss until a proper fix is implemented.

**Vaelastrasz the Corrupt** (13020)
a) should have a dialogue with Nefarian upon entering his room. Maybe it's scripted already and didn't trigger because previous boss is bugged?
b) should cast Burning Adrenaline (18173) every 15 seconds (1 mana user, 1 mana user, MT; 1 mana user, 1 mana user, MT; etc.)

**Broodlord Lashlayer** (12017)
a) Suppression Room should have workable Suppression Devices (179784) casting Suppression Aura (22247) if not disarmed by rogues

**Firemaw** (11983)
a) should be patrolling from Alchemy room to stairs
b) Death Talon Overseers (12461) should also be patrolling back and forth
c) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

**Ebonroc** (14601)
a) should be patrolling around the platform he's on
b) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

**Flamegor** (11981)
a) should be patrolling around the platform he's on
b) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

**Chromaggus** (14020)
a) the lever should open the portcullis, you shouldn't interact with the portcullis directly

**Nefarian**
a) Only in here by myself, so hard to test properly
b) Nefarian should be walking randomly amid the raid, rather than targeting the tank and running up to him (easy fix is to just have him follow a set path around the pillar)
c) Class calls should be benefiting Nefarian, not the player (paladins should not receive Improved Blessing of Protection (23415) on themselves, but onto Nefarian)
d) at 20% mobs should respawn as Bone Constructs (14605)
e) Shadowflame should apply a DoT (22682) if you're not wearing Onyxia Scale Cloak (15138)

##### BRANCH(ES):
I'm not sure what this means. I presume it's master? It's a vanilla raid.
master

##### AC HASH/COMMIT:
Not 100% sure what this means either. Most recent commit is from Kitzunu on Fri May 15 10:56:54 2020 commit f0cb99746642e8dc93f215d0742cbc362e611d04

##### OPERATING SYSTEM:
Windows 10 Pro

##### MODULES:
No other modules

##### OTHER CUSTOMIZATIONS:
No other customizations

**Comment by h0lysp4nk** [comment]
@cts17 

I can confirm Blackwing Lair is a mess and in need of a rework. I was reviewing the code a couple of weeks ago and decided it will probably need to be mostly re written as I don't think anything actually works from my testing.

I'm working on the Temple of Ahn'Qiraj at the moment, once that's done I'll take a look at Blackwing Lair unless someone else wants to.

**Comment by cts17** [comment]
With h0lysp4nk tied up in AQ40, there anyone else willing to take a look or two?

**Comment by FALL1N1** [comment]
follow https://github.com/azerothcore/azerothcore-wotlk/pull/3673 this for progress
