### ISSUE TITLE
 Low damage Gargoyle dk

### ISSUE THREAD

**Issue by deadmanevil** [azerothcore/azerothcore-wotlk#3053]
dk Gargoyle
Little description:
There is a problem that I want to confirm with you if the Gargoyle of the dk is ok or not, so it hits from 140 damage to maximum 200, so they say that it hits very little, I leave the ids of the ebony gargoyle, it is npc 27829, they indicate that must give between 900 to 1.5k
EXPECTED BEHAVIOR BLIZZLLIKE:
it should stick a little more since it is very low damage
CURRENT BEHAVIOR:
hits very low the gargoyle of the dk
STEPS TO REPRODUCE THE PROBLEM:
when you invoke the gargoyle
Atacapero in damage is low both in the npc as players and also in the wooden trainers
his spell does little
EXTRA NOTES:
None

BRANCH (ES):
master

AC HASH / COMMIT:
8b7530b96f0386e0bdc3d66332fd08af513b47e9

OPERATING SYSTEM:
debian 10

MODULES:
Self balancing

OTHER CUSTOMIZATIONS:
None

**Comment by Knindzagxg** [comment]
Currently, it working well.

Hes minimum damage is around 400 / maximum 600.
It scales with DK attack power, which means later on pet itself will do more damage.

Also, i noticed that you have balance module, which can lower stats of all creatures, that include pets.
Can you remove that and test damage without?

You can try with switching specs as well, which should also increase (Just a little) damage output.

**Comment by BarbzYHOOL** [comment]
I confirm this from my tests.

With or without T10, the gargoyle did 168 spell damage which is RIDICULOUS. Someone told she should be doing 3000 dmg per hit (it's the ultimate spell of the unholy DK)

**Comment by BarbzYHOOL** [comment]
Maybe this spell is not working correctly: https://db.frostgram.eu/?spell=51963
It says "+100.00% of spell power to direct component" but the ingame description says it should scale with ATTACK power, not spell power.
Imo, this spell is the right spell after reading the wowhead comments. But it's not coded right
Read more here https://www.wowhead.com/spell=49206/summon-gargoyle#comments someone says it could do 3300 dmg

When I cast the spell as a DK, it also does 168 damage (approximatively). If I increase my spell power, it increases the damage of the spell

Some info about the damage:

```
This thing does absolutely beastly damage. At level 68 with about 1025 AP, it hits for 650~ every 2 seconds on a single target. Take that to 80 with the vast AP increase, and you're hitting for a TON. It does drain your Runic Power very fast, though, but it's almost a good thing in that it encourages you to go on a killing spree to keep your RP up. You cannot skip this if you're going into the Unholy tree.
```
```
Current status of gargoyle:
-scales with all physical haste benefits at the same rate as the player
-attack power coefficient is 0.4
-base damage per strike is 120
-does not inherit any crit from the player
-does not inherit any +damage % modifiers from the player, such as bone shield, desecration, or blood presence
-player stats are taken as a snapshot when the gargoyle is launched; that is, when you cast this spell, however much attack power and haste is the amount your gargoyle strikes will be basing themselves off of.
```

**Comment by BarbzYHOOL** [comment]
So, here is the code for that spell:

```
                    // Gargoyle Strike
                    case 51963:
                    {
                        // about +4 base spell dmg per level
                        damage = (m_caster->getLevel() - 60) * 4 + 60;
                        break;
                    }
``` 
in SpellEffects.cpp

We probably need to add the attack power formula, but I don't know how to do it

**Comment by BarbzYHOOL** [comment]
This second spell that is triggered on summoning the gargoyle isn't doing anything too:
https://db.frostgram.eu/?spell=61777


## Trinitycore

The trinitycore file for the dk pet is different than on AC https://raw.githubusercontent.com/TrinityCore/TrinityCore/3.3.5/src/server/scripts/Pet/pet_dk.cpp with no reference to the spell, while our file has a ref to it (maybe hackfix?)

Here is the issue fixed but probably hard to apply for us https://github.com/TrinityCore/TrinityCore/issues/21435 they seem to have also moved the code from spellEffects when they fixed some core spell system :(

**Comment by BarbzYHOOL** [comment]
but knindza's comment is interesting because I also use the mod-autobalance, maybe related, will test tomorrow without it!

**Comment by BarbzYHOOL** [comment]
ok so it's not related to the mod-autobalance at all

**Comment by Knindzagxg** [comment]
Tested again cause Barbz asked xP

So, with 0 modules, i'm unable to find issue.
I did very simple and quick test.

1st pic - Only weapon and ull see damage from pet 3+566 overkill (3 is cause dummy have 3hp only)
2nd pick - Only tier set (5 items) and damage scale up 3 + 1149.

Pretty please, disable all modules, recompile and tell me results.

![1](https://user-images.githubusercontent.com/27079035/89334031-3290a480-d696-11ea-8531-a9af35cd5d17.jpg)
![2](https://user-images.githubusercontent.com/27079035/89334035-345a6800-d696-11ea-9075-951489eb82df.jpg)

**Comment by BarbzYHOOL** [comment]
Alright, I finally identified the issue...........

It's the module mod-npc-beastmaster... and its author is gone forever

Because mod-npc-beastmaster can't be disabled in the conf, and I had forgotten that, it took me hours to identify the faulty module.... https://github.com/azerothcore/mod-npc-beastmaster/blob/master/conf/npc_beastmaster.conf.dist

**Comment by Felcaster** [comment]
Hello
Gargoyle still have not enough dmg. I create full pvp DK 6651 gears score with Shadowmourne and two best trinkets.
Dr.Damage shows that strike must be ~2684 and total lifetime dmg ~38525 (with all procs around 80000).
But recount shows 1595-1614 strike dmg and 36071 total dmg (gargoyle called with all procs). So it miss ~ 50%dmg.
![WoWScrnShot_080823_155109](https://github.com/azerothcore/azerothcore-wotlk/assets/141717213/c14b258f-1145-4fef-b8a8-436ec66a8f66)
