### ISSUE TITLE
deadmines captain greenskin creatures

### ISSUE THREAD

**Issue by wackinwallaby** [azerothcore/azerothcore-wotlk#3055]
deadmines captain greenskin creatures

##### SMALL DESCRIPTION:

there are 2 defias pirates at the top of the ship in deadmines that are not patrolling correctly

##### EXPECTED BLIZZLIKE BEHAVIOUR:

the 2 defias creatures at the top of the ship are supposed to be patrolling with captain greenskin around the boat.  Note captain greenskin is correct, but the additional creatures are not

##### CURRENT BEHAVIOUR:

the 2 defias creatures are just standing on the ship without patrolling

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to the deadmines
2. go to the top of the ship right before the last boss (van cleef)
3. see the 2 defias creatures not patrolling
![WoWScrnShot_052020_115958](https://user-images.githubusercontent.com/65240021/82565137-e7abca00-9b47-11ea-83dc-c44e0a418c65.jpg)

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

f2892764cd38

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

AhBot
Autobalance

##### OTHER CUSTOMIZATIONS:

none

**Comment by Maurowin** [comment]
I think this PR fix this issue : https://github.com/azerothcore/azerothcore-wotlk/pull/2970

**Comment by Knindzagxg** [comment]
It's not included mate.
That one is just damage fix.

I'm working on patrols and other DB errors from pathing, but not even close to finish those yet, cause a lot of other zones are priority first.
