### ISSUE TITLE
Release 22/05 - Help me please.

### ISSUE THREAD

**Issue by leonardodiasalves** [azerothcore/azerothcore-wotlk#3057]
Image: https://i.imgur.com/Wq5MWcG.png
Image2: https://i.imgur.com/SKWWjXD.png

Mysql: 5.7 OK

worldserver.conf e authserver.conf configured
DataDir = "C:\Users\suap\Downloads\WoW Brasil"

**Comment by Kitzunu** [comment]
Check so your .DLL files matches the actual version you have on your MySQL

AKA Extract them from your MySQL install

**Comment by Kitzunu** [comment]
For OpenSSL 1.0.x: 

* (C:\OpenSSL-Win32\ or C:\OpenSSL-Win64\)
  * `libeay32.dll`
  * `ssleay32.dll`

For OpenSSL 1.1.x: 

* Win32 (C:\OpenSSL-Win32\bin)
  * `libcrypto-1_1.dll` 
  * `libssl-1_1.dll`
