### ISSUE TITLE
Disable battleground random 

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#306]
**Description**:

**Current behaviour**: Tell us what happens
When you disable some BG from the database, it still works in random BG mode.
**Expected behaviour**: Tell us what should happen instead
Should be disabled also in BG random
**Steps to reproduce the problem**:
Example:
Run the following query in the database "world"
```
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('3', '1', '0', '', '', '');
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('3', '30', '0', '', '', '');
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('2', '628', '0', '', '', '');
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('2', '30', '0', '', '', '');
```

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/858955b68c70b98e0c05b737cad5ee7310033308

**Modules**:  Are you using modules? if yes, list them
NO
**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

no

**Comment by rre-za** [comment]
confirmed ,

currently random BG , doesn't check if the battleground is disables in DB.

**Comment by Viste** [comment]
сconfrim and look when have free time

**Comment by Viste** [comment]
@Sworken @rre-za try my PR
