### ISSUE TITLE
SPELL_FAILED_AURA_BOUNCED (not stacking auras) is not working

### ISSUE THREAD

**Issue by fragcamp** [azerothcore/azerothcore-wotlk#3062]
##### SMALL DESCRIPTION:

When you cast for example the first Polymorph (that lasts 10 seconds) and then, before it gets to 5 seconds duration, you cast Polymorph again, the second polymorph shouldn't cast correctly because the enemy already has Polymorph aura "stronger" than the newest one you are trying to apply.

SPELL_FAILED_AURA_BOUNCED sends a message with "A more powerful spell is already active".

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### EXTRA NOTES:

This was fixed on TrinityCore https://github.com/TrinityCore/TrinityCore/commit/5e2c5a52cd8a4ce12e189034df66b42d0d0b2c01?diff=unified

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/6c7184b29d1ec15c2fec3d6d088fcb6f9899879f

##### OPERATING SYSTEM:

Win 7

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Kitzunu** [comment]
Feel free to open a PR :D
