### ISSUE TITLE
Move github template files inside .github folder:

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#3076]
github related files, such as template for PR and commits, can be moved under .github directory to keep everything more clean and focused on project sources

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/3074

**Comment by BarbzYHOOL** [comment]
i wanted to do this for years but never found the time lol

**Comment by FrancescoBorzi** [comment]
this was already done, thanks @Kitzunu 

closing
