### ISSUE TITLE
Dungeon: Blackrock Depths; Golem and Constructs should attack

### ISSUE THREAD

**Issue by wackinwallaby** [azerothcore/azerothcore-wotlk#3077]
Dungeon: Blackrock Depths; Golem and Constructs should attack

##### SMALL DESCRIPTION:

In Blackrock depths, near the boss Golem Lord Argelmach, there are some Wrath Hammer Constructs and Ragereaver Golems.  These creatures are supposed to be hostile and attack players.  The current behavior is that the creatures are not attackable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Golems are supposed to be hostile towards players

##### CURRENT BEHAVIOUR:

The Golems in this area are not hostile to the players and players cannot interact with the creatures.
![WoWScrnShot_052220_222357](https://user-images.githubusercontent.com/65240021/83087259-d0487180-a05e-11ea-8c0e-0095df89e25f.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to BRD near the boss Golem Lord Argelmach
2.  Notice the Golems in the area are not attackable
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

f2892764cd38

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

AHbot
Autobalance

##### OTHER CUSTOMIZATIONS:

None

**Comment by r0m1ntik94** [comment]
@wackinwallaby sorry can't create PR, try this:
```sql
UPDATE `creature_template_addon` SET `auras` = '' WHERE `entry` = 8906; -- Ragereaver Golem
UPDATE `creature_addon` SET `auras` = '' WHERE `guid` = 45933; -- entry 8907 Wrath Hammer Construct
```

**Comment by FrancescoBorzi** [comment]
@r0m1ntik94 why can't you [create a PR](http://www.azerothcore.org/wiki/How-to-create-a-PR)?

we can help if needed

**Comment by Kitzunu** [comment]
Well this would be a hack fix anyways...

We need to understand why it exists and when it should be removed, or if the spell script is wrong.
https://github.com/azerothcore/azerothcore-wotlk/blob/d1e83f6e3d6255802e123845f3377685d9b78695/src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp#L161-L200

This was probably added by Sunwell devs, so honestly, I don't know the reasoning to it, nor how it is supposed to work...

**Comment by gengarshadowball** [comment]
> 
> 
> Well this would be a hack fix anyways...
> 
> We need to understand why it exists and when it should be removed, or if the spell script is wrong.
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/d1e83f6e3d6255802e123845f3377685d9b78695/src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp#L161-L200
> 
> This was probably added by Sunwell devs, so honestly, I don't know the reasoning to it, nor how it is supposed to work...

Why check the instance_uldaman when the golem is from blackrock depths? What did i miss 😄

**Comment by Kitzunu** [comment]
Because the spell is scripted there xD

Anyhow, the spell is a dummy spell so this script makes 0 sense

**Comment by Azcobu** [comment]
Getting reports from CC regarding this - see https://github.com/chromiecraft/chromiecraft/issues/1355, which has more sources on expected golem behaviour.

Also, as the minimum required level to get into BRD is 42, changing labels/project accordingly.

**Comment by T1ti** [comment]
I'm pretty sure when you engage the boss he just wakes up the golems, gonan try to find a calssic source

**Comment by T1ti** [comment]
So this aura is also used by those golems in Uldaman 
![image](https://user-images.githubusercontent.com/40864460/128643245-07f6716d-9934-4099-b7cb-f392e1dc3a37.png)

I can confirm in sniff that both the golems in uldaman and BRD have it

https://youtu.be/hnRIUMTjygU?t=8420
From video, it looks like they are attackable even before engaging the boss but they have the freeze as a dark visual effect, you can see that when engaging the boss their dark aura is removed
Looks like it's purely a visual thing, from what I've seen vmangos deosn't bother with it and doesn't use that aura at all

**Comment by T1ti** [comment]
NVM, they do use it ! 
![image](https://user-images.githubusercontent.com/40864460/128643453-f7374757-098c-4d96-a541-425ac696c401.png)

This is in blackrodepht.cpp

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/128643464-abb1b2e1-5430-47e6-a429-713b056ca9a1.png)
This is how they handle the aura script, it's a generic spell in spellauras.cpp for vmangos, it's not in uldaman

**Comment by syssneck** [comment]
I'm putting this to "high priority" now, as I think it is an important fix for the current and also for the next bracket on Chromiecraft.
Here is a Classic video of the fight: https://youtu.be/QoEwUz7Bdq8?t=645

What should happen when the fight starts, is this:
Golem Lord Argelmach runs a few meters towards The Manufactory and says: "Intruders in the Manufactory? My constructs will destroy you!" He will then draw all the mobs in the Manufactory to aid them, if they haven't been cleared before. As this happens, the two golems behind him already start to fight.

Source: <https://classic.wowhead.com/npc=8983/golem-lord-argelmach#comments:id=3172945>

> Clear out the non-elite gnomes in the other area first, we got some adds when he ran into the work area.

> ...  he does run out of the room to rally the troops but only if you don't clear the those rooms first. If you clear the room before him he stays and fights when you pull ...

> Prior to pulling him make sure you have clears the halls before him. Once you aggro him he will run out into the halls to rally the troops. If you don't kill them all they will come to his aid.
