### ISSUE TITLE
Dungeon: Blackrock Depths: Pathing issues.

### ISSUE THREAD

**Issue by wackinwallaby** [azerothcore/azerothcore-wotlk#3079]
Dungeon: Blackrock Depths: Pathing issues.

##### SMALL DESCRIPTION:

Just outside the domicile in BRD if you try to pull creatures from the room, they hover in mid air and attack you.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Creatures should follow the path like player characters would and attack.

##### CURRENT BEHAVIOUR:

Creatures in the area run out in mid air and attack you hovering.  Some will even run through the walls.

##### STEPS TO REPRODUCE THE PROBLEM:

![WoWScrnShot_052220_213443](https://user-images.githubusercontent.com/65240021/83088096-d17a9e00-a060-11ea-9ced-f47d214715d1.jpg)

1. Go to BRD in the domicile area(see screenshot) and engage enemies in the room
2. Walk out of the room to pull a group back and watch the chaos
3. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

f2892764cd38

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

AHbot
Autobalance

##### OTHER CUSTOMIZATIONS:

None

**Comment by pangolp** [comment]
@wackinwallaby Hello, good afternoon. Thanks for the report. Apologies in advance for the delay. I'm trying to find the area you mentioned, but I can't find it. Could you please provide me with the coordinates? So that I can check if the error persists or if it has already been repaired.

**Comment by Stump876** [comment]
This has been repaired. I can't say exatly when, but I just ran this and they do not defy gravity anymore.
