### ISSUE TITLE
Hunter Pet ability: Ravage

### ISSUE THREAD

**Issue by Irome** [azerothcore/azerothcore-wotlk#308]
**Description**:

The spell Ravage (http://wotlk.openwow.com/spell=53562) of Pet Ravange does not work.

**Current behaviour**:

When you cast the spell Ravage, the target isn't stunned.

**Expected behaviour**:

The Ravage spell should stun the target for 2 seconds.

This video shows exactly what happens: http://tinypic.com/player.php?v=o5w4yc%3E&s=9#.WGf3QTVjZ0x

**Steps to reproduce the problem**:

1. Launch with the Hunter pet Ravange, the spell Ravage, while the target is stationary.
2. Launch with the Hunter pet Ravange, the spell Ravage, while the target is moving.

**Branch(es)**: Master

**AC hash/commit**: 858955b68c70b98e0c05b737cad5ee7310033308

**Comment by falzard** [comment]
Just a hint, be careful when you write issues.

I had to read three times what you said and look on google to understand what was the problem because the "Current behaviour" was not proper english.

I suggest you to edit this:

> The Ravage spell the pet of the hunter when there is activated stuns the target

By this:
**The Ravage spell of a hunter's pet does NOT stun a target.**

**Comment by Irome** [comment]
Thank you falzard for advising me. I can't write well in english, I hope that now you understand what I wrote.

**Comment by falzard** [comment]
No problem Irome.
I forgot to copy paste a line in my message, sorry it doesn't make sense.

What I wanted to say is this: remove the wowwiki.wikia.com link too because it doesn't say a word about the 2 seconds stun (because it has been modified since WOTLK) and it's confusing.

**Comment by Inifield** [comment]
I can't reproduce it 
https://vid.me/8TpO

**Comment by talamortis** [comment]
tested on my server aswell, cant reproduce mine also stuns the target
