### ISSUE TITLE
Erro Compile - QueryResult.h

### ISSUE THREAD

**Issue by MagnusDevs** [azerothcore/azerothcore-wotlk#3080]
I already tried to do with the repository clean and had the same problem
I commented on the change and it worked

https://media.discordapp.net/attachments/284406375495368704/715425421990297610/unknown.png?width=793&height=395

System: Debian 9

Fix
commented from line 21 to 25

https://media.discordapp.net/attachments/284406375495368704/715427789293092905/unknown.png?width=265&height=67

**Comment by Kitzunu** [comment]
@FrancescoBorzi

**Comment by Kitzunu** [comment]
Which MySQL Version do you use?

**Comment by FrancescoBorzi** [comment]
@MagnusDevs please indicate details about your system. MySQL version, AC commit hash, etc...

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3083

**Comment by FrancescoBorzi** [comment]
@MagnusDevs please test this and let me know if it solves your issue: 

#3084
