### ISSUE TITLE
Fatal error: typedef redefinition with different types ('bool' vs 'char') typedef bool my_bool

### ISSUE THREAD

**Issue by hlainin** [azerothcore/azerothcore-wotlk#3083]
Fatal error: typedef redefinition with different types ('bool' vs 'char')
typedef bool my_bool

##### SMALL DESCRIPTION:
When compiling the AZEROTHCORE build, an error occurs.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The build must compile successfully

##### CURRENT BEHAVIOUR:
Trying to install the latest build "https://github.com/azerothcore/azerothcore-wotlk/commit/d1e83f6e3d6255802e123845f3377685d9b78695". Error occurs: Fatal error: typedef redefinition with different types ('bool' vs 'char').
```
`/opt/server/wow/azerotcore/azerothcore-wotlk/src/common/Database/QueryResult.h:22:14: fatal error: typedef redefinition with different types ('bool' vs 'char')
typedef bool my_bool;
             ^
/usr/include/mariadb/mysql.h:39:14: note: previous definition is here
typedef char my_bool;
             ^
1 error generated.
CMake Error at /opt/server/wow/azerotcore/azerothcore-wotlk/deps/cotire/CMake/cotire.cmake:1990 (message):
  cotire: error 1 precompiling
  /opt/server/wow/azerotcore/azerothcore-wotlk/build/src/common/cotire/common_CXX_prefix.hxx.
Call Stack (most recent call first):
  /opt/server/wow/azerotcore/azerothcore-wotlk/deps/cotire/CMake/cotire.cmake:3694 (cotire_precompile_prefix_header)


make[2]: *** [src/common/CMakeFiles/common.dir/build.make:64: src/common/cotire/common_CXX_prefix.hxx.pch] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:914: src/common/CMakeFiles/common.dir/all] Ошибка 2
make: *** [Makefile:130: all] Ошибка 2`
```

##### OPERATING SYSTEM:
```
Debian 10
Mariadb - 10.3
/////////////////////
clang version 7.0.1-8 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
/////////////////////
cmake version 3.13.4
```
##### MODULES:
none

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3080

**Comment by FrancescoBorzi** [comment]
I know the other issue has been reported first, however I'd actually prefer to keep @hlainin since he put more information

**Comment by FrancescoBorzi** [comment]
@hlainin please test this and let me know if it solves your issue: https://github.com/azerothcore/azerothcore-wotlk/pull/3084

**Comment by hlainin** [comment]
> @hlainin, пожалуйста, проверьте это и дайте мне знать, если это решит вашу проблему: [# 3084](https://github.com/azerothcore/azerothcore-wotlk/pull/3084)

With this fix, the bug is gone. Thanks!
