### ISSUE TITLE
problems with custom race polymorph

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#3092]
problems with custom race polymorph

SMALL DESCRIPTION:
When using polymorph on custom races, the character breaks the model, this problem is not in trinitycore

EXPECTED BLIZZLIKE BEHAVIOUR:
When using polymorph, the model should return to its original state

CURRENT BEHAVIOUR:
When using polymorph on custom races, the character breaks the model

STEPS TO REPRODUCE THE PROBLEM:
1. It is necessary to make changes to sharedefines.h diff is in the archive
2.Add dbc
3.install the patch in the client
4.shed files sql
5.Create worgen warrior and create human mage
6. use polymorph (spell id 12826)

video problems
https://youtu.be/LSje1qjOkmk

patch archive
https://drive.google.com/file/d/1h6U9YAtjqflSkpamZXW6BEQnsi5ACaBz/view?usp=sharing

i'm sorry my bad english

**Comment by iThorgrim-Hub** [comment]
I have same problem with my Worgen :
![image](https://user-images.githubusercontent.com/58987080/83349775-af6e6d80-a337-11ea-8c9e-a43bc9977b6a.png)

![image](https://user-images.githubusercontent.com/58987080/83349801-d5940d80-a337-11ea-8b2e-d2e8ef129687.png)

Only with AzerothCore

**Comment by avatar789** [comment]
The problem is relevant not only for worgens, but also for other races, for example zandalari and voidelf
the same problems are possible from the appearance of the druids.
Actually only for Azerotkor on trinity everything works correctly
![WoWScrnShot_053020_234152](https://user-images.githubusercontent.com/5444058/83350951-13118e80-a36a-11ea-8fe0-0b39960e2da5.jpg)
![WoWScrnShot_052920_000136](https://user-images.githubusercontent.com/5444058/83350953-1442bb80-a36a-11ea-8b5b-f496eb2f691c.jpg)

**Comment by Helias** [comment]
@avatar789 did you solve?

**Comment by heyitsbench** [comment]
I don't believe this issue has been solved. The issue can be seen in [this commit](https://github.com/heyitsbench/mod-worgoblin/commit/d2da3d4d7d5cecbfa83de92481ae0b937b05c2ce) of my Worgoblin module. ACHERAX#0001 on the modding Discord had a similar issue and noted his solution:
```
I had removed troll from my enums since I was removing the race, but I guess TC does something odd involving the ordering of races when it comes to de-morphing.
I added RACE_TROLL back in and explicitly defined the playable horde races (excluding trolls from it), and that solved the issue for me.
```

**Comment by Furioz420** [comment]
Pretty sure this issue is because of not having the right (opposite) gender model in the database.

After a morph it reverts to that to change player back to its "default" look.
We had this some time ago aswell with our custom races.

Its either that , or you have conflicting data in you chrSections.dbc
