### ISSUE TITLE
RangeHack

### ISSUE THREAD

**Issue by retrydev** [azerothcore/azerothcore-wotlk#310]
**Description**: RangeHack

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. https://github.com/TrinityCore/TrinityCore/issues/17060
2.
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**: 

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
@retrydev please read [how to open an issue](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue) and fill the requested texts

**Comment by falzard** [comment]
At least you can read what it is about in the link

**Comment by Helias** [comment]
It's only a visual bug, I think that it depends only from the client, so from the patch.

**Comment by falzard** [comment]
You sure? they say that there is no server side check and so you can attack from higher range with all spells if you use a modified client (patch)

**Comment by Helias** [comment]
I tested it and my character says "Out of range" all the time, is a visual bug you don't see your spells "red" but you can't use it.

**Comment by ShinDarth** [comment]
@falzard I've read it, I'm only asking to open a proper report

**Comment by lineagedr** [comment]
It's not visual I've tested it here's a fix from TC that I've applied succesfully on my sunwell core

https://github.com/Aokromes/TrinityCore/commit/fa7026cee30743fb7b51dc5b5ca5ebe136de715b

**Comment by falzard** [comment]
Received this msg:

It's not visual I've tested it here's a fix from TC that I've applied succesfully on my sunwell core

Aokromes/TrinityCore@fa7026c
