### ISSUE TITLE
Codacy Error

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#3100]
Every PR from 2 days ago (29/05) has had Codacy issues that it won't even run the code tests.

**Codacy/PR Quality Review — Codacy was unable to analyse your pull request.**

**Comment by FrancescoBorzi** [comment]
@Kitzunu I'm not sure what I can do about it

**Comment by Kitzunu** [comment]
I just assigned you since it is running on your fork or smt

**Comment by FrancescoBorzi** [comment]
o_O my fork? what?

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/83401008-3a1c9e80-a404-11ea-955c-75fe67a19301.png)

**Comment by FrancescoBorzi** [comment]
It looks like the url is correct, pointing to the main AC repo, not to my fork:

![image](https://user-images.githubusercontent.com/75517/83402904-f166e480-a407-11ea-925d-391a8aa72ef4.png)

**Comment by FrancescoBorzi** [comment]
I made Codacy non-required until the issue is solved

**Comment by Kitzunu** [comment]
Seems to be working now
