### ISSUE TITLE
clang 10 build has warnings

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#3108]
##### SMALL DESCRIPTION:

In prior Clang versions we managed to fix all warnings and prevent new warnings to be added thanks to the `-Werror` flag.

This is not critical as you can still compile using clang-10. However, this prevents us to use `-Werror` (fail on warning) in our CI clang-10 build. **So basically if new warnings will be added by a PR for the clang-10 build, we will not catch that.**

##### EXPECTED BEHAVIOUR:

There shouldn't be any warning

##### CURRENT BEHAVIOUR:

If you compile with clang-10, you get some warning such as:

> /home/runner/work/azerothcore-wotlk/azerothcore-wotlk/deps/g3dlite/include/G3D/Vector3.h:118:25: warning: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);

##### STEPS TO REPRODUCE THE PROBLEM:
1. Install clang-10 and use
2. Set your CMake flags to use clang-10 **AND** enable warnings and `-Werror`, example:

```
-DCMAKE_C_COMPILER=/usr/bin/clang-10 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DWITH_WARNINGS=1 -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"
```

3. Try to compile the core, you will see some warnings. We should fix them.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/3d9d51977d0df3c7f8e5b896fb34f1b47292b53b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

No modules

##### OTHER CUSTOMIZATIONS:

None.

**Comment by Yehonal** [comment]
Maybe we can disable those warnings for g3dlite https://stackoverflow.com/questions/15133332/ignore-only-show-errors-warnings-from-certain-directory-using-cmake

We could also try to fix G3D directly. We have the version 9 (2013), the last version is the 10 (2014). I don't think they have that fix inside the last version, so we could patch it by ourself eventually

**Comment by tatense** [comment]
Confirm
