### ISSUE TITLE
Buggy moderator (gmlvl1) visibility commands

### ISSUE THREAD

**Issue by MetalRuller** [azerothcore/azerothcore-wotlk#3109]
Buggy moderator (gmlvl1) visibility commands

##### SMALL DESCRIPTION:

Moderators are currently able to use .gm visible off and .gm visible on to permanently turn on gm mode

##### STEPS TO REPRODUCE THE PROBLEM:

1. account set gmlevel account 1 -1
2. login to a char on the account (after privileges are reloaded)
3. .gm visible off
4. .gm visible on
5. if worldserver.GM.LoginState is > 1, that moderator char is now permanently in GM mode and cannot exit it. 

##### EXTRA NOTES:

It seems to me that moderator (lvl1) accounts aren't meant to be able to use **.gm on** and visibility commands according to command definitions in https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_gm.cpp#L36

I assume the goal here with the Moderator visibility system, if it was intended, was to have "invisible-only" GMs, but this only works with worldserver.GM.LoginState = 0 and having the moderator chars log off whenever they want to turn GM off.

I'm new to this server software stuff, but I don't understand why, given the table definitions, that they are able to use **.gm visible** to begin with.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c92d9b9291c9f5b848ed3dfeed793e89def2774e

##### OPERATING SYSTEM:

Ubuntu 20

##### MODULES:

No.

##### OTHER CUSTOMIZATIONS:

No.

**Comment by Kitzunu** [comment]
You override it in `command`

command
---
```sql
SELECT * FROM command WHERE NAME LIKE '%visible%'
```
| name | security | help | 
| --- | ---: | --- | 
| gm visible | 1 | Syntax: .gm visible on/off Output current visibility state or make GM visible(on) and invisible(off) for other players. | 

No issue here

**Comment by BarbzYHOOL** [comment]
Yes, I think it depends on the server's owner preference, really dunno what the best default setting would be
