### ISSUE TITLE
How Can I change the language of quests etc.?

### ISSUE THREAD

**Issue by Seebaby** [azerothcore/azerothcore-wotlk#311]
Will it be possible at any time to add the localization? Would like the server in German

**Comment by luozhazha** [comment]
TrinityCore  hasn't this problem. But AzerothCore has.

**Comment by pak3935** [comment]
https://bitbucket.org/pak3935/sunwellcore3/commits/93316c509194c56e31812ca30431b57a1e9ab113

**Comment by NRJ955** [comment]
en español , A guide to put it in Spanish please

**Comment by starrheld** [comment]
@NRJ955 - For questions please join our Spanish room in Discord.

https://discord.gg/nNH3GvT
