### ISSUE TITLE
[Class][Warlock] - Immolation Debuff

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#3112]
##### SMALL DESCRIPTION:

A delay of almost 1 second elapses between the moment when the "Immolation" spell is used on the target and the moment when the debuff appears. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When the player uses the spell "Immolation (Rank 11); ID: 47811" on an enemy target, a debuff is cast on the target. 
"Immolation: Inflicts 157 Fire damage every 3 seconds. 

As a result, the latter allows the use of the spell "Conflagration; ID: 17962".
The use of the conflagration spell, without cooldown time, is possible when the debuff "Immolation (Rank 11); ID: 47811" is applied to the enemy target.

##### CURRENT BEHAVIOUR:
A delay of almost 1 second elapses between the moment when the "Immolation" spell is used on the target and the moment when the debuff appears. 

Therefore the "Conflagration; ID: 17962" spell, which should be usable instantly after the use of "Immolation (Rank 11); ID: 47811", not possible without waiting that one second of delay.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Start your server
2. Create a Destruction Warlock
3. Fight!

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/64e0867c281cf2d812159a2ae4d15423394149d1

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
- Eluna
- 1v1
- CFBG

##### OTHER CUSTOMIZATIONS:
- Community Bonus (Lua_Script)
- Account-Mount-Wide (Lua_Script)

**Comment by lineagedr** [comment]
It has an intended blizzlike delay: https://www.youtube.com/watch?v=KUizH_eVcuA&feature=youtu.be&t=209

**Comment by iThorgrim-Hub** [comment]
I've just checked frame by frame and apparently you're right, there are a few milliseconds during which the spell doesn't appear.

I was mistaken.

![image](https://user-images.githubusercontent.com/58987080/83949251-ec000480-a822-11ea-9ece-269482af7dfd.png)
![image](https://user-images.githubusercontent.com/58987080/83949256-ef938b80-a822-11ea-943c-ffe2dc216e03.png)
