### ISSUE TITLE
.reload page_text only works if you delete your client cache

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3114]
##### SMALL DESCRIPTION:

.reload page_text doesn't refresh cache

##### STEPS TO REPRODUCE THE PROBLEM:

Read a book with a page_text in it, edit that page_text, reload, and it's still the same page_text unless you remove the client cache

##### EXTRA NOTES:

Can be really annoying, especially when testing

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

441c02a

**Comment by Kitzunu** [comment]
I honestly don't know if we could force that... any example of something that forces the cache to reload or smt?

**Comment by BarbzYHOOL** [comment]
the module better reload items does, dunno how though

https://github.com/azerothcore/mod-better-item-reloading/

**Comment by BarbzYHOOL** [comment]
the module makes it possible for item reloading

also if we can't do it, then we should have a message that tells the developer "you need to delete your client cache to see changes" because most table reloads don't require that at all

**Comment by Kitzunu** [comment]
Maybe it has something to do with this :shrug:
https://github.com/azerothcore/mod-better-item-reloading/blob/master/src/BetterItemReloading.cpp#L48-L59

But I will make a fix for a text to say it needs client cache deletd

**Comment by Shard-MW** [comment]
We can resend cache to client 
That's what's done here : 
https://github.com/azerothcore/mod-better-item-reloading/blob/master/src/BetterItemReloading.cpp#L632

I just don't know if it'll have the same behaviour as items

**Comment by pangolp** [comment]
Is it possible to just delete the cache of the developer, or rather, who uses the command? Because it is true that it would be annoying, if you are updating a lot of text, to have to exit, delete cache and re-enter every time you make 1 or more changes. Anyway, the idea of the message, I do not think bad. I think there are other commands, which delete the cache, but only from whoever executes the command.

**Comment by BarbzYHOOL** [comment]
Pangolp's idea is good, there would need to send an output message to the command user to reboot the server if he wants players to have the new changes
