### ISSUE TITLE
Boss in Temple of Atal'hakkar has no path (error console)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3118]
##### SMALL DESCRIPTION:

`WaypointMovementGenerator::LoadPath: creature Weaver (Entry: 5720 GUID: 3603138) doesn't have waypoint path id: 0`

Mob is: https://wow.gamepedia.com/Weaver

##### STEPS TO REPRODUCE THE PROBLEM:

1. No idea, I suppose just type `lookup creature jammal'an` and you go to this boss.
2. You kill that boss and then you find the 4 other drake bosses, one is called `Weaver` and it's him. He probably displays this error in console as soon as he pops or moves.

**Comment by Kitzunu** [comment]
The only problem with this is that GUID 3603138 does not exist in the DB 

creature
---
```sql
SELECT * FROM creature WHERE id = 5720
```
| guid | id | map | zoneId | areaId | spawnMask | phaseMask | modelid | equipment_id | position_x | position_y | position_z | orientation | spawntimesecs | wander_distance | currentwaypoint | curhealth | curmana | MovementType | npcflag | unit_flags | dynamicflags | ScriptName | VerifiedBuild | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | 
| 239021 | 5720 | 109 | 0 | 0 | 1 | 2 | 0 | 0 | -458,84 | 127,7 | -91,57 | 5,77 | 86400 | 0 | 0 | 11075 | 0 | 2 | 0 | 0 | 0 |  | 0 |

**Comment by BarbzYHOOL** [comment]
it's spawned dynamically...

**Comment by Kitzunu** [comment]
From where? I cannot find any reference in SAI or Core that would reference 5720 as creature to spawn

**Comment by BarbzYHOOL** [comment]
Read the how to test.

I just tried what I said and it spawned Weaver (kill jammal'an first). Then, you teleport near him, in GM mode (so he doesn't attack you). And then he will start moving with his friend and the error displays in console

**Comment by merdlin** [comment]
Confirmed

**Comment by FrancescoBorzi** [comment]
@merdlin feel free to add the `Confirmed` badge whenever you can confirm the issue

**Comment by merdlin** [comment]
#https://github.com/TrinityCore/TrinityCore/issues/6614

**Comment by merdlin** [comment]
https://github.com/TrinityCore/TrinityCore/commit/87a44450b56eadfbf693071174fcb0132b893934
