### ISSUE TITLE
playercreateinfo_item amount is limited to 127 wtf

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3119]
##### SMALL DESCRIPTION:

If we want to put 200 items on player creation (ex: 200 arrows for hunters) we can't.

##### CURRENT BEHAVIOUR:

The datatype is wrong and totally useless (like most tables, proper SQL is not so easy).
We can have -127 to 127 (or 128).
What we need is 0-255 (unsigned tinyint) or more (unsigned smallint).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Put an item in that table with amount = 250. You can't

##### EXTRA NOTES:

**How to fix suggestion:**

SQL
```SQL
ALTER TABLE `playercreateinfo_item` CHANGE `amount` `amount` tinyint(3) unsigned NOT NULL DEFAULT 1 AFTER `itemid`; 
```

CPP, in ObjectMgr.cpp:
```CPP
// change this to the corresponding GetIntX() amount
uint8 amount   = fields[3].GetInt8();
```

*Note: I would post the fix myself if my working environment wasn't so dirty, I have to clean my core/repo before being able to do that, that's why i post it in an issue, sorry*

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

bf74a3a

**Comment by Kitzunu** [comment]
Well, then we should make it smallint? Because some arrows (maybe all?) stack in 1000

**Comment by BarbzYHOOL** [comment]
yes probably, i had the arrows example come to my mind while writing it ^^
