### ISSUE TITLE
Simple errors "Creature not found in creature_addon"

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3120]
##### SMALL DESCRIPTION:

Errors in console:
```
Creature (GUID: 85227) does not exist but has a record in `creature_addon`                
Creature (GUID: 88108) does not exist but has a record in `creature_addon`
```

**Fix:**

```SQL
DELETE FROM `creature_addon` WHERE `guid` IN (85227,88108);
```

The bug originates in: sql/base/db_world/creature_addon.sql:20710:(85227,0,0,0,1,0,NULL),

Note: I would post the fix myself if my working environment wasn't so dirty, I have to clean my core/repo before being able to do that, that's why i post it in an issue, sorry

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

19c3a70d

**Comment by Kitzunu** [comment]
Well... these creatures actually do exist in the Database, and are spawned under those GUID's

creature
---
```sql
SELECT * FROM creature WHERE guid IN  (85227,88108)
```
| guid | id | map | zoneId | areaId | spawnMask | phaseMask | modelid | equipment_id | position_x | position_y | position_z | orientation | spawntimesecs | wander_distance | currentwaypoint | curhealth | curmana | MovementType | npcflag | unit_flags | dynamicflags | ScriptName | VerifiedBuild | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | 
| 85227 | 35507 | 571 | 0 | 0 | 1 | 1 | 29830 | 1 | 5758,4 | 745,385 | 653,748 | 4,27606 | 180 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |  | 0 | 
| 88108 | 35508 | 571 | 0 | 0 | 1 | 1 | 29829 | 1 | 5946,12 | 512,111 | 650,263 | 2,93215 | 180 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 |  | 0 |

**Comment by BarbzYHOOL** [comment]
not for me lol wtf

**Comment by BarbzYHOOL** [comment]
you're right, my bad!
