### ISSUE TITLE
Deprecated item on player creation needs to be removed

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3121]
##### SMALL DESCRIPTION:

We have an useless grey item for death knight on player creation. This item was only added during test server and readded in cataclysm (i verified on wowhead, wowpedia etc)

Here is the fix:
```sql
DELETE FROM `playercreateinfo_item` WHERE `itemid` = 40582 AND `class` = 6 AND `amount` = -1;
```
The fix is very specific in case someone edited the item itself so it is identified exactly, **do not change it, please.**

*Note: I would post the fix myself if my working environment wasn't so dirty, I have to clean my core/repo before being able to do that, that's why i post it in an issue, sorry*

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nothing, it's blizzlike to have no hearthstone for DK until cataclysm. (it was temporarily added in beta realms for 3.0 but removed after). So we just need to remove that from our DB

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

19c3a70

**Comment by lineagedr** [comment]
```sql
`amount` = -1;
```

The -1 means it will remove the item not add it. I downloaded a fresh AC today and I was wondering why my DK had the 
"[TDB PH] - unsused Scourgestone" item. This https://github.com/azerothcore/azerothcore-wotlk/pull/3122 commit broke removing items with the playercreateinfo_item table.

**Comment by FrancescoBorzi** [comment]
@lineagedr could you please open a new report with this information? cc @Kitzunu
