### ISSUE TITLE
[Quest] The Plains of Nasam

### ISSUE THREAD

**Issue by Phoenix-Game** [azerothcore/azerothcore-wotlk#3125]
SMALL DESCRIPTION:

Can't use Tank
EXPECTED BLIZZLIKE BEHAVIOUR:

You must use Tank and destroy 100 Scourge Soldiers and rescue 3 Injured Warsong Soldiers on the Plains of Nasam.
( https://www.wowhead.com/quest=11652/the-plains-of-nasam )
CURRENT BEHAVIOUR:

When you use Tank it dropping you down.
STEPS TO REPRODUCE THE PROBLEM:

- Start quest: The Plains of Nasam (questid:11652)
-Try to use Tank
EXTRA NOTES:

I think is related to this issue, the same behavior: https://github.com/azerothcore/azerothcore-wotlk/issues/3124
BRANCH(ES):

master
AC HASH/COMMIT:

7424718
OPERATING SYSTEM:

Ubuntu 18
MODULES:
1vs1arena, anticheat, duelreset, ahbo, pvptitle, double xp.

**Comment by vhiperdev** [comment]
![image](https://user-images.githubusercontent.com/39068627/84600631-22f09e80-ae51-11ea-9cec-0b7502a738b7.png)

I can't reproduce this error, update your updated database and map core.

**Comment by Phoenix-Game** [comment]
The issues was in database or maps, after update everything working
