### ISSUE TITLE
import sql updates have error!

### ISSUE THREAD

**Issue by tatense** [azerothcore/azerothcore-wotlk#3128]
I use last version AC , all  sql/updates have error for import in to databases;

ERROR 1558 (HY000) at line 2: Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaD       B 100108, now running 100411. Please use mysql_upgrade to fix this error

Ithins bugs is for this import up linS: (updateDb)

<details>
DROP PROCEDURE IF EXISTS updateDb;
DELIMITER //
CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
SELECT COUNT(*) INTO @COLEXISTS
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'version_db_auth' AND COLUMN_NAME = '2019_04_13_00';
IF @COLEXISTS = 0 THEN LEAVE proc; END IF;
START TRANSACTION;
ALTER TABLE version_db_auth CHANGE COLUMN 2019_04_13_00 2020_02_07_00 bit;
SELECT sql_rev INTO OK FROM version_db_auth WHERE sql_rev = '1579213352894781043'; IF OK <> 'FALSE' THEN LEAVE proc; END IF;
</details>

https://github.com/azerothcore/azerothcore-wotlk/commit/cccdb0a692dca5b51b1c1cd5458f3753484f397e

mysql: xampp last version

**Comment by FrancescoBorzi** [comment]
@tatense do you use this while using the db assembler? can you describe what you are exactly doing?

**Comment by tatense** [comment]
Hi

i use this:
merge_updates_unix.sh

**Comment by Yehonal** [comment]
Maybe it's related: https://stackoverflow.com/questions/16177465/column-count-of-mysql-proc-is-wrong-expected-20-found-16-the-table-is-probabl

**Comment by tatense** [comment]
I tested not work.

and i use xampp last version

Includes: Apache 2.4.43, MariaDB 10.4.11, PHP 7.4.6 + SQLite 2.8.17/3.31.1 + multibyte (mbstring) support, Perl 5.16.3, ProFTPD 1.3.6, phpMyAdmin 5.0.2, OpenSSL 1.1.1g, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.8-dev, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4

**Comment by Yehonal** [comment]
should not be any \r character inside config.sh

try to use the tool dos2unix to convert that file in UNIX LF

**Comment by Yehonal** [comment]
However, you should not remove that line, it's needed to keep your DB versioned

Can you test it with mysql instead of mariadb? (or a previous version of mariadb)

**Comment by tatense** [comment]
This problem did not exist in the past.

I tested everything I could,These lines give an error and does not allow the file to be imported !

example:
`
-- DB update 2019_03_03_00 -> 2019_03_07_00
DROP PROCEDURE IF EXISTS `updateDb`;
DELIMITER //
CREATE PROCEDURE updateDb ()
proc:BEGIN DECLARE OK VARCHAR(100) DEFAULT 'FALSE';
SELECT COUNT(*) INTO @COLEXISTS
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'version_db_world' AND COLUMN_NAME = '2019_03_03_00';
IF @COLEXISTS = 0 THEN LEAVE proc; END IF;
START TRANSACTION;
ALTER TABLE version_db_world CHANGE COLUMN 2019_03_03_00 2019_03_07_00 bit;
SELECT sql_rev INTO OK FROM version_db_world WHERE sql_rev = '1551539925032805900'; IF OK <> 'FALSE' THEN LEAVE proc; END IF;
--
-- START UPDATING QUERIES
--
`

**Comment by tatense** [comment]
@Yehonal 

When will it be new Releases AC

**Comment by Kitzunu** [comment]
@tatense AC has updates everyday. See it as a release x)

@Yehonal I have the same issue, that it can't import due to a line like that.

**Comment by Winfidonarleyan** [comment]
Normal work at MariaDB `10.4.8`
at `my.ini`
```ini
[mysqld]
datadir=C:/Program Files/MariaDB 10.4/data
port=3306
innodb-page-size=65536
innodb_buffer_pool_size=1024M
character-set-server=utf8
[client]
port=3306
plugin-dir=C:/Program Files/MariaDB 10.4/lib/plugin
```

**Comment by tatense** [comment]
@Winfidonarleyan

Can u share last AC world full DB by all updates?

w can't import updates!
