### ISSUE TITLE
Lich King evading.

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#313]
The Lich King is evading after fininshing a first part of script with Tirion.

There were 2 players in raid,without administrator rights(for testing).

After throwing an ice block thing into Tirion,Arthas climbs upstairs to his throne,and script is resetting by itself.

**Comment by ShinDarth** [comment]
This report is invalid. Please read https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
