### ISSUE TITLE
How to update database when using docker to deploy the server?

### ISSUE THREAD

**Issue by CalsRanna** [azerothcore/azerothcore-wotlk#3133]
I use db_assembler.sh seems has some problem ,and it didn't wok well. So i wondering if where was a way more smooth than manuly import every update sql.

**Comment by tatense** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3128

**Comment by FrancescoBorzi** [comment]
@CalsRanna if you have issues please open a **detailed** bug report (if you think it's a bug) or a StackOverflow question if you need generic help:

https://www.azerothcore.org/wiki/How-to-ask-for-help
