### ISSUE TITLE
[MYSQL] azerothcore don't supported version 5.6!

### ISSUE THREAD

**Issue by tatense** [azerothcore/azerothcore-wotlk#3146]
Hi

AC last version don't supported mysql of xampp.

I usage last version xampp but have error:

![Untitled](https://user-images.githubusercontent.com/47708113/85209061-29e44900-b34a-11ea-988a-00fb2e59dd1e.png)

I testing mysql-server and full worked!
but if we want usage xampp! can't

https://www.apachefriends.org/download.html
XAMPP for Linux version  7.4.7

Please fixed.
OS: ubuntu 20.04
version: https://github.com/azerothcore/azerothcore-wotlk/commit/139743004bd28fb046d5637bd0dac98b3caa73c6

**Comment by Kitzunu** [comment]
You get this error if you use **DIFFERENT VERSION OF YOUR .DLL** compared to the **MYSQL VERSION YOU USE** (Or if you use MySQL under 5.6)

**Comment by tatense** [comment]
@Kitzunu 
Iknow but xampp supported mysql v 5.6.

please added mysql supports by versions: 5.6  5.7 and 8.0

**Comment by Kitzunu** [comment]
We support them and they all work

**Comment by tatense** [comment]
Testing

https://www.apachefriends.org/xampp-files/7.4.7/xampp-linux-x64-7.4.7-0-installer.run

don't work!

**Comment by Kitzunu** [comment]
As I said, your MySQL.dll in the folder of your worldserver.exe is not the same version as the MySQL Server you use. 

if they are not the exact same (5.6.4851 for example) it will not work

**Comment by tatense** [comment]
Dear
my os is linux not windows

**Comment by Kitzunu** [comment]
Well then I can't help you more other than that I know for a fact that all MySQL versions do work because I have used them myself

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/85209281-e16f6000-b336-11ea-95b4-48a582529910.png)
You are using MySQL Version 5.5.5 in your MariaDB.

It is not supported

**Comment by FrancescoBorzi** [comment]
@Viste what version of MySQL should be normally included inside MariaDB ?

**Comment by Viste** [comment]
they forked from 5.5 but 10.1+ its like 5.6 i use 10.4 and all ok, also dont have reference about 5.5-5 in console
![Снимок экрана от 2020-06-22 02-13-26](https://user-images.githubusercontent.com/281977/85237248-04c90680-b42e-11ea-88f8-dc7c0b30c51f.png)
![Снимок экрана от 2020-06-22 02-12-07](https://user-images.githubusercontent.com/281977/85237249-05fa3380-b42e-11ea-871a-e8c9489646ce.png)
@tatense try to install MariaDB 10.4 from starch you have very strange version

**Comment by tatense** [comment]
@Viste   Iknow.

AC don't supported mysql and mariadb from xampp...

install last version xampp and check....

https://www.apachefriends.org/download.html

linux: 7.4.7 version

**Comment by Viste** [comment]
address this to xampp they use "shitty" version of MariaDB(dont know about mysql... dont use this shit)
if they want use 10.4 maria they must install 10.4 but they do shit... mysql 5.5 dont supported by AZ because of security issue and its stupid to support this old shit.

**Comment by tatense** [comment]
Can you creat and give A patch for some if want usage xampp mysql and mariadb.

**Comment by Viste** [comment]
@tatense you don't post what error you have with xampp so idk what need to do and also don't want install this mad tool on my laptop

**Comment by tatense** [comment]
@Viste 

This is last version XAMPP and you can testing visit all infos..

https://www.apachefriends.org/xampp-files/7.4.7/xampp-linux-x64-7.4.7-0-installer.run

**Comment by Viste** [comment]
No thanks, I don't want to install this garbage software, or you show a mistake or wait for help from the AZ team .

**Comment by tatense** [comment]
Ok.
But xampp has a lot of fans.

**Comment by Viste** [comment]
> Ok.
> But xampp has a lot of fans.

ok but its not my problem :D i even not a contributor of this project anymore, only in past :D
also i think you need revert to many good commits to get it work on 5.5-5.6 mysql, because of DB struct changes.

> Includes: Apache 2.4.43, MariaDB 10.4.13, PHP 7.4.7 + SQLite 2.8.17/3.32.2 + multibyte (mbstring) support, Perl 5.30.3, ProFTPD 1.3.6, phpMyAdmin 5.0.2, OpenSSL 1.1.1g, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4

all of this can be installed without xampp :D i don't see any reason to use this pre-build by someone(What if there's a backdoor somewhere?)

**Comment by tatense** [comment]
xampp It has many services.

and you can will to easy disables, service.

secuirty xampp is power full !

**Comment by Viste** [comment]
> and you can will to easy disables, service.
![Снимок экрана от 2020-06-22 03-18-41](https://user-images.githubusercontent.com/281977/85238519-1cf15380-b437-11ea-9d0e-8dcd9f313241.png)
really i also can easy disable what i want :DD

**Comment by tatense** [comment]
xampp command:

stop mysql
stop apache
stop mariadb

**Comment by Viste** [comment]
> xampp command:
> 
> stop mysql
> stop apache
> stop mariadb

Ok they just have symlink or script to do what i do in screen :DD 
But if they so cool and perfect why they lie about they MariaDB version??? I use 10.4.13-MariaDB and can use AzerothCore.... and you with latest xampp where they SAY Includes: Apache 2.4.43, MariaDB 10.4.13 YOU GET Troubles??? funny

**Comment by Kitzunu** [comment]
So the problem with this is that your XAMPP is using MySQL 5.5 which has (never?) been supported by Azerothcore or any other core in a very long time.

At this current moment Azerothcore supports
MySQL 5.6, 5.7 and 8.0
(5.6 will be deprecated in the future)

As Viste said it is due to security things.
If you really want to use Xampp then you have to allow MySQL 5.5 yourself.
If you check the commit history you will find when we allowed support for 8.0, do what I did but allow 5.5 instead.

But it is nothing you will get official support for as we do not support any MySQL versions *below* MySQL 5.6

**Comment by Viste** [comment]
> If you check the commit history you will find when we allowed support for 8.0, do what I did but allow 5.5 instead.

some other commits breaks compatibility with 5.5 https://github.com/azerothcore/azerothcore-wotlk/commit/31bce00b2a2dd5ee1ee2606be8445b024e1265b2 this for example so its a hard task to make 5.5 works
also xampp lies about they Maria version this is general issue :D they say WE USE MariaDB 10.4 but in fact 5.5. lol

**Comment by Kitzunu** [comment]
Solution:
Dump Xampp and use an actual database server; i.e MySQL Server xD

**Comment by Viste** [comment]
@Kitzunu I think you should close the discussion, it won't lead to anything anyway. The more that the problem is not on the AzerothCore side.

**Comment by Kitzunu** [comment]
Thank you for the help @Viste 
It is always appreciated :)
