### ISSUE TITLE
[Battleground] Produces a crash with gm

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#315]
**Description**:

** Current Behavior **: Tell Us What Happens
The problem occurs when a Game Master enters a battlefield. I have been testing internally and still don't understand exactly what causes this problem. I only know that it occurs if a GM enters the battlefield And it is randomly, I do not have a pattern, but if I can say that at the time when more is produced is when a battlefield culminates

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/a655ddcbc02f90d08683c834e0d0e3b95ea216d2

**Modules**:  Are you using modules? if yes, list them
Transfiguration
AnticheatSystem
**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by talamortis** [comment]
@Sworken please try with anticheat disabled.

**Comment by falzard** [comment]
@HeartWell ??

**Comment by HeartWell** [comment]
Not confirm for clean AC.
