### ISSUE TITLE
[Suggestion] New command

### ISSUE THREAD

**Issue by furywow** [azerothcore/azerothcore-wotlk#3158]
Hello AC community

# I wanted to suggest two commands

- Check player bag
- Check player work

```sh
$ .bag You can see what items are inside the player's bag
$ .work You can see which job the player has
```

**Comment by Kitzunu** [comment]
> .work You can see which job the player has

What?

**Comment by FrancescoBorzi** [comment]
> .work You can see which job the player has

maybe you mean profession?

**Comment by Kitzunu** [comment]
If so there is no use because you can see that by looking up their spells
ie. .lo spell Jewelcrafting

**Comment by furywow** [comment]
> > .work You can see which job the player has
> 
> maybe you mean profession?

Yes, i mean profession

**Comment by IntelligentQuantum** [comment]
https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/dadfccb7be9f4b8aa391f681e51b1294f90efeca

**Comment by Helias** [comment]
@IntelligentQuantum what about to open a PR from your wonderful fork? :grin: ?

**Comment by furywow** [comment]
> [IntelligentQuantum@dadfccb](https://github.com/IntelligentQuantum/azerothcore-wotlk/commit/dadfccb7be9f4b8aa391f681e51b1294f90efeca)

Thank you! Could you open a pr?

**Comment by Helias** [comment]
@furywow, the PR has been opened, just test it and comment your feedback in the PR
