### ISSUE TITLE
[BUG] Ahune Boss [solstice event], can't be spawned on RDF

### ISSUE THREAD

**Issue by chamorrorenzo** [azerothcore/azerothcore-wotlk#3159]
##### CURRENT BEHAVIOUR:

If you join a group RDF to kill the boss, any of the players cant get access to talk to the icepillar, unless any of us on the party have this item :https://wotlk.evowow.com/?item=34953 wich if Im not misstaking its from the quest to invoke him, but if you want to solo him

##### EXPECTED BLIZZLIKE BEHAVIOUR:

People need to be able to summon him, if they use RDF option  to kill ahune, with out the need to have the quest item https://wotlk.evowow.com/?item=34953 

##### STEPS TO REPRODUCE THE PROBLEM:

1. group 5 people, and join RDF ahune event
2. try to spawn him, by talking to the ice pillar
3. You can't, but if you give yourself this item https://wotlk.evowow.com/?item=34953, the gossip will appear and you will be abble to summon ahune

##### OPERATING SYSTEM:

w10

##### MODULES:

boss_announcer
npc_services
mod_transmog
npc_weapon_visual
ah_bot
cfbg_master
npc-talent-template-master
world_chat

**Comment by Kitzunu** [comment]
Please state the rev you are using

**Comment by Kitzunu** [comment]
The reason is that Luma Skymother does not offer the quest she is supposed to, and unfortunately, I cannot figure out why she doesn't

**Comment by FrancescoBorzi** [comment]
@Kitzunu have you checked the DB ?

**Comment by chamorrorenzo** [comment]
Sorry im not on pc atm, rev im using its just 2 weeks old

**Comment by Kitzunu** [comment]
@FrancescoBorzi ofc,

**Comment by 0xCiBeR** [comment]
Posted a $10 bounty on this one, seems its still an issue.
