### ISSUE TITLE
CMake Compilation ERROR

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3160]
Hello guys,  I follow this instruction https://www.azerothcore.org/wiki/digital-ocean-video-tutorial, but i'm get an error:

> azcore@login:~/azerothcore/build$ make -j
> [  0%] Built target Detour
> [  0%] Built target fmt
> [  1%] Built target gsoap
> [  3%] Built target Recast
> [  8%] Built target g3dlib
> [ 11%] Built target jemalloc
> [ 11%] Building CXX precompiled header src/common/cotire/common_CXX_prefix.hxx.pch
> [ 11%] Built target revision.h
> In file included from /home/azcore/azerothcore/build/src/common/cotire/common_CXX_prefix.hxx:4:
> In file included from /home/azcore/azerothcore/build/src/common/cotire/common_CXX_prefix.cxx:4:
> In file included from /home/azcore/azerothcore/src/common/PrecompiledHeaders/commonPCH.h:6:
> In file included from /home/azcore/azerothcore/src/common/Database/SQLOperation.h:13:
> /home/azcore/azerothcore/src/common/Database/QueryResult.h:22:14: error: typedef redefinition with different types ('bool' vs 'char')
> typedef bool my_bool;
>              ^
> /usr/include/mysql/mysql.h:53:14: note: previous definition is here
> typedef char my_bool;
>              ^
> 1 error generated.
> CMake Error at /home/azcore/azerothcore/deps/cotire/CMake/cotire.cmake:1990 (message):
>   cotire: error 1 precompiling
>   /home/azcore/azerothcore/build/src/common/cotire/common_CXX_prefix.hxx.
> Call Stack (most recent call first):
>   /home/azcore/azerothcore/deps/cotire/CMake/cotire.cmake:3694 (cotire_precompile_prefix_header)
> 
> 
> src/common/CMakeFiles/common.dir/build.make:63: recipe for target 'src/common/cotire/common_CXX_prefix.hxx.pch' failed
> make[2]: *** [src/common/cotire/common_CXX_prefix.hxx.pch] Error 1
> CMakeFiles/Makefile2:785: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
> make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

Previously, I compiled without problems on this instruction. Could this be because I only have 2 cores per processor?

**OPERATION SYSTEM**: Debian 9

**Comment by Kitzunu** [comment]
Which Rev are you on?`
Please do not delete the template.
```
<!-- IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE! -->

<!-- This template is for problem reports, for feature suggestion etc... feel free to edit it.
 If this is a crash report, upload the crashlog on https://gist.github.com/
 For issues containing a fix, please create a Pull Request following this tutorial: http://www.azerothcore.org/wiki/Contribute#how-to-create-a-pull-request -->


<!-- WRITE A RELEVANT TITLE -->


##### CURRENT BEHAVIOUR:
<!-- Describe the bug in detail. Database to link spells, NPCs, quests etc https://wowgaming.altervista.org/aowow/ -->




##### EXPECTED BLIZZLIKE BEHAVIOUR:
<!-- Describe how it should be working without the bug. -->




##### STEPS TO REPRODUCE THE PROBLEM:
<!-- Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
 - Which commands to use? Which NPC to teleport to?
 - Do we need to have debug flags on Cmake?
 - Do we need to look at the console while the bug happens?
 - Other steps
-->

1. 
2. 
3. 

##### EXTRA NOTES:
<!--
Any information that can help the developers to identify and fix the issue should be put here.
Examples:
- was this bug always present in AzerothCore? if it was introduced after a change, please mention it
- the code line(s) that cause the issue
- does this feature work in other server appplications (e.g. CMaNGOS, TrinityCore, etc...) ?
-->






##### AC HASH/COMMIT:
<!-- IF YOU DO NOT FILL THIS OUT, WE WILL CLOSE YOUR ISSUE! NEVER WRITE "LATEST", ALWAYS PUT THE ACTUAL VALUE INSTEAD.
Find the commit hash (unique identifier) by running "git log" on your own clone of AzerothCore or by looking at here https://github.com/azerothcore/azerothcore-wotlk/commits/master -->



##### OPERATING SYSTEM:
<!-- Windows 7/10, Debian 8/9/10, Ubuntu 16/18 etc... -->



##### MODULES:
<!-- Are you using modules? If yes, list them (note them down in a .txt for opening future issues) -->



##### OTHER CUSTOMIZATIONS:
<!-- Are you using any extra script?
 - Did you apply any core patch/diff?
 - Did you modify your database?
 - Or do you have other customizations? If yes please specify them here.
-->




<!-- ------------------------- THE END ------------------------------
Thank you for your contribution.
If you use AzerothCore regularly, we really NEED your help to:
 - TEST our fixes ( http://www.azerothcore.org/wiki/Contribute#how-to-test-a-pull-request )
 - Report issues
 - Improve the documentation/wiki
With your help the project can evolve much quicker!
-->


<!-- NOTE: If you intend to contribute more than once, you should really join us on our discord channel! We set cosmetic ranks for our contributors and may give access to special resources/knowledge to them! The link is on our site http://azerothcore.org/
-->
```

**Comment by wowissues** [comment]
> Which Rev are you on?`
> Please do not delete the template.
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> 
> ##### CURRENT BEHAVIOUR:
> 
> 
> 
> 
> 
> ##### EXPECTED BLIZZLIKE BEHAVIOUR:
> 
> 
> 
> 
> 
> ##### STEPS TO REPRODUCE THE PROBLEM:
> 
> 
> 1. 
> 2. 
> 3. 
> 
> ##### EXTRA NOTES:
> 
> 
> 
> 
> 
> 
> 
> ##### AC HASH/COMMIT:
> 
> 
> 
> 
> ##### OPERATING SYSTEM:
> 
> 
> 
> 
> ##### MODULES:
> 
> 
> 
> 
> ##### OTHER CUSTOMIZATIONS:
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ```

At the very last one it’s obvious. I install from 0

**Comment by Kitzunu** [comment]
Which MySQL / Maria Version do you use?

**Comment by wowissues** [comment]
> Which MySQL / Maria Version do you use?

root@login:~# mysql --version
mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

root@login~# mysql -v
Server version: 10.1.44-MariaDB-0+deb9u1 Debian 9.11

**Comment by Kitzunu** [comment]
Try using a Maria version > 10.1 especially since it uses MySQL 5.6
Any version above should use 5.7 too, could be interesting to see if it works

**Comment by FrancescoBorzi** [comment]
@Kitzunu would be nice if we could create a wiki page with all supported/unsupported versions of mysql and mariadb

**Comment by Kitzunu** [comment]
@FrancescoBorzi 
We support these versions of MySQL:

| MySQL Version | Supported          |
| ------------- | ------------------ |
| 5.6           | :white_check_mark: |
| 5.7           | :white_check_mark: |
| 8.0           | :white_check_mark: |

We support these versions of MariaDB:

| MariaDB Version | Supported          |
| --------------- | ------------------ |
| 10.1            | :white_check_mark: |
| 10.2            | :white_check_mark: |
| 10.3            | :white_check_mark: |
| 10.4            | :white_check_mark: |

I wonder why it don't want to work in CMake...

**Comment by wowissues** [comment]
me need time to update db, since I don’t know how to do it

**Comment by FrancescoBorzi** [comment]
@Kitzunu I don't think MariaDB 10.1 works fine. Check the comments in: https://stackoverflow.com/questions/62503653/error-on-compilation-my-bool-droplet-on-digitalocean-debian-9-12

**Comment by wowissues** [comment]
Since I did not have the mind to update the mariadb. I reinstalled Debian 9 to Debian 10 (which defaults to Mariadb 10.3). And it worked, the core compiled.
Since I saw other people’s questions regarding 5.6 / Mariadb 10.1, I think the problem is this.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/3085#issuecomment-635726926
