### ISSUE TITLE
ERROR: Unit::HandleDummyAuraProc: Spell 58642

### ISSUE THREAD

**Issue by merdlin** [azerothcore/azerothcore-wotlk#3166]
ERROR: Unit::HandleDummyAuraProc: Spell 58642

##### CURRENT BEHAVIOUR:
ERROR: Unit::HandleDummyAuraProc: Spell 58642 has non-existing triggered spell 4294967295
After this failure the worldserver stops working.
The players informed me that they were in the wintergrasp the problem may come from there.

##### EXTRA NOTES:
After these errors are reported, the worldserver crash.

AC HASH/COMMIT:
[master](https://github.com/azerothcore/azerothcore-wotlk/commit/7725dfe8b85e16a0b95811e8e0801ff342b1ac6f)

##### OPERATING SYSTEM:
Windows server 2016

##### MODULES:
Arena 1v1, npc transmog, duelreset, weapon visual.

##### OTHER CUSTOMIZATIONS:
no

![image](https://user-images.githubusercontent.com/60373652/85955822-ccf31f00-b957-11ea-870e-f7c93a3341ed.png)

**Comment by Kitzunu** [comment]
Please attach a crashlog

**Comment by merdlin** [comment]
[unknown_worldserver.exe_[28-6_15-44-43].txt](https://github.com/azerothcore/azerothcore-wotlk/files/4842855/unknown_worldserver.exe_.28-6_15-44-43.txt)

**Comment by Kitzunu** [comment]
In a pastbin or gist... I dont want to download stuff

**Comment by merdlin** [comment]
https://pastebin.com/cY0W628s

**Comment by Kitzunu** [comment]
And now to the fun stuff.

Your crash logs give us 0 because you have built your core in **Release**
You need to build in **RelWithDebInfo** or **Debug** for the crashlog to be useful :)
