### ISSUE TITLE
Creature Murkdeep is visible with GM Mode ON only.

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#3167]
Creature Murkdeep is visible with GM Mode ON only

##### CURRENT BEHAVIOUR:

NPC: Murkdeep
Entry in creature_template: 10323
GUID in creature: 1976190
Zone: Darkshore
Note: This creature is needed for quest "WANTED: Murkdeep" (ID: 4740) but it is only visible as GM.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Players need to kill this creature.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create new alliance character with level 20 min.
2. Teleport to creature: .go creature 1976190
3. Add Quest: .q a 4740
4. Test visibility of creature when .gm on and .gm off

##### AC HASH/COMMIT:

df637282c2fddb585614e50efd8ed54984e39a23

##### OPERATING SYSTEM:

Windows 10 version 2004

**Comment by FrancescoBorzi** [comment]
all creatures are visible when GM on

**Comment by skxawng-cu** [comment]
> 
> 
> all creatures are visible when GM on

Yes, I know that. But this creature must be visible without GM mode activated because it must be visible to players in order to complete the mission.

**Comment by xDevICCI** [comment]
I tested this issue:

Add Quest , In Mode player ( gm off)
![error](https://user-images.githubusercontent.com/44324742/86496917-61d98c00-bd4d-11ea-9dd3-b70083fd4e9a.png)


Others:

![first](https://user-images.githubusercontent.com/44324742/86496939-787fe300-bd4d-11ea-85bb-675891676318.png)


![seco](https://user-images.githubusercontent.com/44324742/86496941-7c136a00-bd4d-11ea-9255-b24c0134e36b.png)

**Comment by FrancescoBorzi** [comment]
sounds like a phasing issue

**Comment by skxawng-cu** [comment]
Sorry, I make more test to quest and Murkdep appears when you kill all Murloks in the camp.
I will close the issue.
