### ISSUE TITLE
Authserver and Worldserver won't start

### ISSUE THREAD

**Issue by CyberMist2** [azerothcore/azerothcore-wotlk#3169]
### **Description**
I just compiled **Azerothcore** on **Wndows 10 64bit**, setup **database**, **configuration** files and **data files** (dbc, maps, vmaps, etc).
When I tried to start **authserver.exe** or **worldserver.exe** they just closed suddenly without any error or any log file created.

### **What was my issue?**
I renamed authserver.conf.dist and worldserver.conf.dist to no .dist extension which caused the issue.

### **How to avoid this issue?**
Do **NOT** just rename the **.dist** configuration files!
Copy/paste **.dist** authserver and worldserver configuration files then rename them and leave **.dist** configuration files untouched.

**Comment by CyberMist2** [comment]
### Fixed:

Do NOT just rename the .dist configuration files!
Copy/paste .dist authserver and worldserver configuration files then rename them and leave .dist configuration files untouched.

**Comment by FrancescoBorzi** [comment]
@CyberMist2 sorry if it was not clear enough, however, as explained in: https://www.azerothcore.org/wiki/How-to-ask-for-help support requests should be placed on Stackoverflow, while this GitHub repo is used for bug reports.
