### ISSUE TITLE
Worldserver problem

### ISSUE THREAD

**Issue by IZM38** [azerothcore/azerothcore-wotlk#317]
**Description**:
Hello. I have a problem with the worldserver.
**Current behaviour**: Tell us what happens
When I apply the update for the world table (world_update_2017_01_09_16_10_00.sql) it gives the error in the picture
and when I don't apply it, it can't connect to the mysql server.

![worldserver error](https://cloud.githubusercontent.com/assets/25008014/21768004/7737a45c-d68c-11e6-8048-ecfa15603d81.jpg)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
Master
**AC hash/commit**:  a655ddc

**Operating system**:  Windows 8.164-bit

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
what error are u getting when trying to input the sql file?

**Comment by talamortis** [comment]
also make sure u input these sql files

https://github.com/azerothcore/azerothcore-wotlk/tree/master/data/sql/updates/pending_db_world

**Comment by IZM38** [comment]
I'm not getting any error when I input it it's after that when I applied it and run the worldserver that get the error.

**Comment by talamortis** [comment]
did u input the sql files from the link?

**Comment by Rushor** [comment]
hello ali

**Comment by IZM38** [comment]
Applied the files and it works!
Thank you.
