### ISSUE TITLE
Command .mute when player is offline does not work (read inside)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3174]
##### CURRENT BEHAVIOUR:

if you .mute a player who is offline but WHO is still logged in (= at the character selection panel), then he won't be muted. But it will still say ingame that the player is muted while he's not.

If the guy is totally logged out however, it works fine.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Take two accounts. Log in with both but stay at the character selection screen (before entering the game) for account 2
2. With account 1 use `.mute` to mute the other account's character
3. Log in with account 2's muted character. and he can speak.......

##### EXTRA NOTES:

This might also affect other commands working similarly. Note that it looks like that these commands have not been touched for years, even on trinitycore, and are full of small bugs/inconvenience

##### AC HASH/COMMIT:

6d460c54a03510d69502e5683846f685e00cda59

**Comment by wizzymore** [comment]
Seems like this happens only when the character is in character select screen.
When the account connects to the server, only then it is checked for the offline mute.

What we need to do is to implement a check at the login of the character as well.

**Comment by Winfidonarleyan** [comment]
try https://github.com/WarheadCore/WarheadCore/commit/097df4e7b85c8b7ad026c34fe41adf7f83f33379

**Comment by lineagedr** [comment]
@FrancescoBorzi I believe this can be closed.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/f538eacebaeb5428c85e0aae96a23346ed8dc5be
