### ISSUE TITLE
Command ".unstuck" does not work when stuck player is offline -__-

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3177]
##### CURRENT BEHAVIOUR:

You can't use `.unstuck barbz` if character Barbz is offline. This is extremely inconvenient as a GM can receive a ticket "please i'm stuck, can you unstuck me" and the player logs out. Then you can't unstuck him easily until he logs back in. You have to go into the DB for that, or use other hacky techniques.

The command also doesn't return anything when you successfully unstuck someone. It should say something in chat AND console to warn the GM that it worked. It could also warn the player with a red notification "You have been unstuck by a GM.".

##### STEPS TO REPRODUCE THE PROBLEM:

1. Take two accounts. Log in with both but stay at the character selection screen (before entering the game) for account 2
2. With account 1 use `.unstuck` to unstuck (teleport to his $home inn) the other account's character
3. Doesn't work when offline

##### EXTRA NOTES:

This might also affect other commands working similarly. Note that it looks like that these commands have not been touched for years, even on trinitycore, and are full of small bugs/inconvenience

Also, the command doesn't return useful output . It says "Player not found!", it should say player offline. That's the case for tons of commands, it's shit (can lead to a lot of time wasted).

##### AC HASH/COMMIT:

6d460c54a03510d69502e5683846f685e00cda59

**Comment by natrist** [comment]
The GM tool I intend to develop soon™ will feature an option to teleport offline players via a SQL query. 

Also if you're going to be implementing custom behaviour, that is behaviour that does not reflect the original behaviour of the game and its servers, you should be careful and put it under a module or Lua script. The codebase is already riddled with custom implementations and bad code.

**Comment by pangolp** [comment]
I'll check this command later, however, to unlock a character, in case it gets caught and requires help, you can also use the `.summon` command. Anyway, I'll try to check what happens with this command.

**Comment by sudlud** [comment]
I thought this already got fixed on the meantime, but thanks @pangolp roe checking

**Comment by pangolp** [comment]
Previously, I don't remember the year, we had assigned some issues. That's why I'm assigned this one and three more. But the truth is, I had completely forgotten about this.

**Comment by pangolp** [comment]
Maybe it can be improved later, but maybe this way, for now it will be fine.

https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/61687966-6d6e-43ac-a347-f6099dfafd03
