### ISSUE TITLE
(DB/Quest): Plagued Lands

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3178]
https://wowhead.com/quest=2118/plagued-lands

**SMALL DESCRIPTION:**:
Does not give out new traps if the old one was used

**STEPS TO REPRODUCE THE PROBLEM**:

`1 .q add 2118`
`2. .tele darkshore`

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506fbfe5+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Knindzagxg** [comment]
Confirmed.

If you abandon quest and take again, you will give item.
Will try to sort during weekend.

**Comment by Shineslippers** [comment]
f62664c9874bda6a49c67872c2e951eeabff56ce Working as intended

https://user-images.githubusercontent.com/85256266/142876709-64c9f6cc-2dd1-4aca-ac5c-a6d7544460e8.mp4
