### ISSUE TITLE
(Ulduar Heroic Mode 25): Faceless Horror

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3182]
https://www.wowhead.com/npc=33772/faceless-horror

**CURRENT BEHAVIOUR**:
This NPC uses only 2 abilities https://www.wowhead.com/spell=63722/shadow-crash and https://www.wowhead.com/spell=63703/void-wave

**EXPECTED BLIZZLIKE BEHAVIOUR**:
This NPC should be used 5 abilities https://www.wowhead.com/npc=33772/faceless-horror#abilities

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Helias** [comment]
The NPC seems to have implemented in SAI **Death Grip, Shadow Crash, Void Wave**, but only the normal mode, @Knindzagxg the heroic mode inherit the normal mode SAI? because it seems that it is not implemented.

I am considering this
- entry 33772 normal mode
- entry 33773 heroic mode

**Comment by Knindzagxg** [comment]
Damn, just saw mate.
I will check it tomorrow.

Think i saw difference between 2, not sure atm.

**Comment by Knindzagxg** [comment]
Yeah, its not added to Heroic version.
I'm gonna quickly import from normal mode towards heroic, since it's same AI.
