### ISSUE TITLE
(DB/Creature): Frostbrood Sentry and Gargoyle Ambusher too much damage

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3184]
https://www.wowhead.com/npc=32767/frostbrood-sentry
https://www.wowhead.com/npc=32769/gargoyle-ambusher

**SMALL DESCRIPTION**:
These NPCs do too much damage. Frostbrood Sentry 10 thousand, Gargoyle Ambusher 7500 dmg

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Knindzagxg** [comment]
Don't see any problem in DB at the moment.

```REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (32769, 0, 0, 0, 33192, 32188, 25753, 0, 0, 0, 'Gargoyle Ambusher', '', '', 0, 80, 80, 2, 21, 0, 1, 1.71429, 1, 0, 417, 582, 0, 608, 1, 2000, 2000, 2, 32768, 2048, 0, 0, 0, 0, 0, 0, 341, 506, 80, 6, 0, 32769, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 0, 4, 1, 1, 1, 1, 0, 164, 1, 8388624, 0, '', 12340);
```

```REPLACE INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (32769, 0, 0, 0, 33192, 32188, 25753, 0, 0, 0, 'Gargoyle Ambusher', '', '', 0, 80, 80, 2, 21, 0, 1, 1.71429, 1, 0, 417, 582, 0, 608, 1, 2000, 2000, 2, 32768, 2048, 0, 0, 0, 0, 0, 0, 341, 506, 80, 6, 0, 32769, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 0, 4, 1, 1, 1, 1, 0, 164, 1, 8388624, 0, '', 12340);
```

Those are default and they are fine.
Make sure you haven't changed or modified those (Feel free to use this to fix)
