### ISSUE TITLE
Feature Request - Show All Characters on Account command

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#3185]
Hey Guys,

It would be nice if we could develop a command that shows all characters on a selected account.

example syntax:

`.account characters (acc name)`

then would produce a list of characters on that account like so:

`Showing characters for account "Test":`
`Test1`
`Test2`
`Test3`
`Test4`
`Test5`

Thoughts?

**Comment by IntelligentQuantum** [comment]
.look player acc test

**Comment by disclosurez** [comment]
i love you.

> 
> 
> .look player acc test
