### ISSUE TITLE
Can't compile with the MariaDB 10.4

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3189]
**SMALL DESCRIPTION**:

Hi guys, I updated the mariadb to 10.4.13, but during compilation I got this error:
`CMake Error at src/cmake/macros/FindMySQL.cmake:235 (message):
  Could not find MySQL headers! Please install the development libraries and
  headers
Call Stack (most recent call first):
  CMakeLists.txt:101 (find_package)

-- Configuring incomplete, errors occurred!`

How i can fix this? 

**OPERATING SYSTEM**: Debian 9

**Comment by FrancescoBorzi** [comment]
as explained in: https://www.azerothcore.org/wiki/How-to-ask-for-help

github issues should be used to report bugs, for support requests you should use Stackoverflow instead. Please read that page carefully.
