### ISSUE TITLE
Core/DB Death Knight Quest Line Unable to Progress

### ISSUE THREAD

**Issue by Tyrelis** [azerothcore/azerothcore-wotlk#3192]
##### CURRENT BEHAVIOUR:

The 8th mission in the Death knight quest line is you to talk to Highlord Darion Mograine too accept the quest "Report to Scourge Commander Thalanor". When you go to him, and turn in the quest he doesn't give you the quest "The Power of Blood, Frost And Unholy" so you can't continue the quest line to progress there.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

On the 8th mission in the Death knight quest line is you to talk to Highlord Darion Mograine too accept the quest "Report to Scourge Commander Thalanor". When you go to him, and turn in the quest he gives you the quest "The Power of Blood, Frost And Unholy" so you can continue the quest line to progress there.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a deathknight
2. Do main quest line until 8th mission.
3. You will be unable to progress past that point.

##### AC HASH/COMMIT:

a2a4416

##### OPERATING SYSTEM:

Ubuntu 18.04

**Comment by Knindzagxg** [comment]
What's your XP rates mate?

Year (Or even more) ago, there was issue if you had higher rate that made some issue with phasing and quests.
Kinda same like we had for Sons of Hodir.

**Comment by Tyrelis** [comment]
@Knindzagxg My rates are xp rates are 8x

**Comment by Knindzagxg** [comment]
Try with 1x and tell me what happen.
You can use quest command till that part.

**Comment by Tyrelis** [comment]
After setting the rates to x1 that fixed the issue I can confirm this is cause of bug.

**Comment by Knindzagxg** [comment]
Thouth so.

Also, you can try with 8x rates for xp but 1x rep, which is temp fix as well.
Last thing you can do is to increase xp requirements between level 55-60 (Multiply default by 8) to get kinda blizzlike way of doing those so DK's can get their Talents and etc.

But hopefully, we will sort this as soon as possible.

**Comment by Tyrelis** [comment]
> Thouth so.
> 
> Also, you can try with 8x rates for xp but 1x rep, which is temp fix as well.
> Last thing you can do is to increase xp requirements between level 55-60 (Multiply default by 8) to get kinda blizzlike way of doing those so DK's can get their Talents and etc.
> 
> But hopefully, we will sort this as soon as possible.

Thanks for temp fix.

**Comment by omghixd** [comment]
tested on 64778f8decf8 with x5 XP Rates

This is from start to reported quest.

Quest 1: Working Perfectly

Quest 2: Working Perfectly

Quest 3: Working Perfectly

Quest 4: Working Perfectly

Quest 5: Working Perfectly

Quest 6: Working Perfectly 

Quest 7: It is working, But the eye is VERY SLOW when going towards the objective. From the acherus to the town that is (The uncontrollable part) And the eye in general has a veeery slow movement speed. Are we sure this is blizzlike value?
And the spell to return on the hotbar does not work. you've got to use the one on the MiniActionBar.
- Overall works, but could use some fine-tuning.

Quest 8: Working Perfectly. Gives the reward, area effect spell and the followup quest.

Quest 9: Also works perfectly.
Wanted to do a test of this one, even tho it wasnt within the report. Considering it has transport involved.

**Comment by wowissues** [comment]
> tested on 64778f8decf8 with x5 XP Rates
> 
> This is from start to reported quest.
> 
> Quest 1: Working Perfectly
> 
> Quest 2: Working Perfectly
> 
> Quest 3: Working Perfectly
> 
> Quest 4: Working Perfectly
> 
> Quest 5: Working Perfectly
> 
> Quest 6: Working Perfectly
> 
> Quest 7: It is working, But the eye is VERY SLOW when going towards the objective. From the acherus to the town that is (The uncontrollable part) And the eye in general has a veeery slow movement speed. Are we sure this is blizzlike value?
> And the spell to return on the hotbar does not work. you've got to use the one on the MiniActionBar.
> 
> * Overall works, but could use some fine-tuning.
> 
> Quest 8: Working Perfectly. Gives the reward, area effect spell and the followup quest.
> 
> Quest 9: Also works perfectly.
> Wanted to do a test of this one, even tho it wasnt within the report. Considering it has transport involved.

7) https://github.com/azerothcore/azerothcore-wotlk/pull/2939 this pr fix eye for me, i tested and it's works fine

**Comment by Tyrelis** [comment]
> tested on 64778f8decf8 with x5 XP Rates
> 
> This is from start to reported quest.
> 
> Quest 1: Working Perfectly
> 
> Quest 2: Working Perfectly
> 
> Quest 3: Working Perfectly
> 
> Quest 4: Working Perfectly
> 
> Quest 5: Working Perfectly
> 
> Quest 6: Working Perfectly
> 
> Quest 7: It is working, But the eye is VERY SLOW when going towards the objective. From the acherus to the town that is (The uncontrollable part) And the eye in general has a veeery slow movement speed. Are we sure this is blizzlike value?
> And the spell to return on the hotbar does not work. you've got to use the one on the MiniActionBar.
> 
> * Overall works, but could use some fine-tuning.
> 
> Quest 8: Working Perfectly. Gives the reward, area effect spell and the followup quest.
> 
> Quest 9: Also works perfectly.
> Wanted to do a test of this one, even tho it wasnt within the report. Considering it has transport involved.

Try up to quest 12 I may have been wrong on quest count.

**Comment by omghixd** [comment]
> > tested on 64778f8decf8 with x5 XP Rates
> > This is from start to reported quest.
> > Quest 1: Working Perfectly
> > Quest 2: Working Perfectly
> > Quest 3: Working Perfectly
> > Quest 4: Working Perfectly
> > Quest 5: Working Perfectly
> > Quest 6: Working Perfectly
> > Quest 7: It is working, But the eye is VERY SLOW when going towards the objective. From the acherus to the town that is (The uncontrollable part) And the eye in general has a veeery slow movement speed. Are we sure this is blizzlike value?
> > And the spell to return on the hotbar does not work. you've got to use the one on the MiniActionBar.
> > 
> > * Overall works, but could use some fine-tuning.
> > 
> > Quest 8: Working Perfectly. Gives the reward, area effect spell and the followup quest.
> > Quest 9: Also works perfectly.
> > Wanted to do a test of this one, even tho it wasnt within the report. Considering it has transport involved.
> 
> Odd, what is your reputation rates set at?

1x. Blizzlike

**Comment by Tyrelis** [comment]
> > > tested on 64778f8decf8 with x5 XP Rates
> > > This is from start to reported quest.
> > > Quest 1: Working Perfectly
> > > Quest 2: Working Perfectly
> > > Quest 3: Working Perfectly
> > > Quest 4: Working Perfectly
> > > Quest 5: Working Perfectly
> > > Quest 6: Working Perfectly
> > > Quest 7: It is working, But the eye is VERY SLOW when going towards the objective. From the acherus to the town that is (The uncontrollable part) And the eye in general has a veeery slow movement speed. Are we sure this is blizzlike value?
> > > And the spell to return on the hotbar does not work. you've got to use the one on the MiniActionBar.
> > > 
> > > * Overall works, but could use some fine-tuning.
> > > 
> > > Quest 8: Working Perfectly. Gives the reward, area effect spell and the followup quest.
> > > Quest 9: Also works perfectly.
> > > Wanted to do a test of this one, even tho it wasnt within the report. Considering it has transport involved.
> > 
> > 
> > Odd, what is your reputation rates set at?
> 
> 1x. Blizzlike

Try setting your rates to 5x for reputation and test again.

**Comment by pangolp** [comment]
Is this report still valid?

**Comment by heyitsbench** [comment]
Tested on 244dca66609beaba1fbcf66fc607e53572fe8d52 with both 1x rep/xp rates, as well as 8x, quest chain worked fine both times. I'd say report is invalid.

**Comment by acidmanifesto** [comment]
I just finished this quest yester day. No issues.

**Comment by pangolp** [comment]
Thanks.
