### ISSUE TITLE
(DB/Creature): Vorakem Doomspeaker

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3194]
https://www.wowhead.com/npc=18679/vorakem-doomspeaker 
For some reason, it seems to me that all the RARE NPC are so broken.

**SMALL DESCRIPTION**:
This NPC stands still and does not run after the hero. He only uses spells when you approach him.

**STEPS TO REPRODUCE PROBLEM**:
`.npc add 18679`

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Knindzagxg** [comment]
This one got some weird movement ID, will sort in next few.
Tho which other?
I tested every TBC rare for achie and only this one have move problem.

**Comment by wowissues** [comment]
> This one got some weird movement ID, will sort in next few.
> Tho which other?
> I tested every TBC rare for achie and only this one have move problem.

I don't know, he just stand still and do not move.

**Comment by Knindzagxg** [comment]
What about other?

You said all rares have problems?

**Comment by wowissues** [comment]
> What about other?
> 
> You said all rares have problems?

I haven't checked it yet, it only seems to me that way. How to check I will say

**Comment by Knindzagxg** [comment]
Nice, feel free to post and just make sure to always do more then one check.

Cheers mate.

**Comment by wowissues** [comment]
> Nice, feel free to post and just make sure to always do more then one check.
> 
> Cheers mate.

Thanks! I always test several times!
