### ISSUE TITLE
AzerothCore can't find configuration Files Windows Fresh Build

### ISSUE THREAD

**Issue by FSKiller** [azerothcore/azerothcore-wotlk#3197]
### CURRENT BEHAVIOUR:
Server closes with Error: "Load config error. Invalid or missing dist configuration file: worldserver.conf.dist
Verify that the file exists and has '[worldserver]' written in the top of the file!"

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Server start normally

##### STEPS TO REPRODUCE THE PROBLEM:
1. Fresh compile AzerothCore Master Branch
2. Open WorldServer.exe instant crash with the error

##### AC HASH/COMMIT:
047d630c7d96bdcfcbf76a1f9bc6f301115154bb

##### OPERATING SYSTEM:
Windows 10

##### OTHER CUSTOMIZATIONS:
No modifications

![AzerothServer](https://user-images.githubusercontent.com/4363770/87793895-c9a7d080-c83d-11ea-9e74-3c929dcec14e.png)

**Comment by Kitzunu** [comment]
I think you need to copy them too so you have .conf and .conf.dist

**Comment by FSKiller** [comment]
in the screenshot you can see i have both .conf and .dist files cant seem to find the problem here though

**Comment by Kitzunu** [comment]
hm weird...

**Comment by BarbzYHOOL** [comment]
@Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
You're running the program from the wrong path. Need run from `E:\AzerothServer` only
