### ISSUE TITLE
Convertion

### ISSUE THREAD

**Issue by TW1NKLET** [azerothcore/azerothcore-wotlk#320]
Does anyone have any experience in migrating a DB from Trinitycore to Azerothcore? Everything is working, but no spells are learned from old characters nor any mounts/skills.

i know that under character_talent and character_spells talentGroup is specMask

**Comment by ShinDarth** [comment]
@starrheld if you wrote a converter, can you share it?

**Comment by Yehonal** [comment]
Which migration tool are you using starrheld? if you want i can help you to fix specMask and talentGroup, but we must share this tool on a public repository

**Comment by starrheld** [comment]
Did not use any tool other then HeidiSQL and my own hands :+1:

**Comment by Yehonal** [comment]
this means that the db sync works of @Helias and @ShinDarth is working :)

well about specMask and talentGroup maybe i've some sql, i'll create a repo with such sql so you can test it

**Comment by ShinDarth** [comment]
it will be even easier once we complete https://github.com/azerothcore/azerothcore-wotlk/issues/236

**Comment by Yehonal** [comment]
https://github.com/azerothcore/tool-tc-migration

Here you can find 2 sql to convert the TC spell system to AC

there are also old sql to convert TC to 0.x, but i do not suggest them

**Comment by starrheld** [comment]
Used it, all spels were there when I logged on, when I logged off and in again everything was gone
