### ISSUE TITLE
[QUEST] The Ravaged Caravan

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#321]
Quest: http://www.wowhead.com/quest=749/the-ravaged-caravan
Object: http://www.wowhead.com/object=2908/sealed-supply-crate    X: -1922.880005 Y: -712.921997 >: 691720

**Description**: The object that should complete the quest is clickable but not complete the quest

**Current behaviour**: Don't work object

**Expected behaviour**: Click the object and complete the quest

**Steps to reproduce the problem**:

1. go to the object and try click

**Comment by talamortis** [comment]
please provide item id, quest id .go points to each
