### ISSUE TITLE
for 20200722 code build error:    No template named 'auto_ptr' in namespace 'std'

### ISSUE THREAD

**Issue by wokaoak** [azerothcore/azerothcore-wotlk#3213]
explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )

**Comment by wokaoak** [comment]
system：Mac OS    Xcode

**Comment by wokaoak** [comment]
[](url)
![image](https://user-images.githubusercontent.com/6096192/88127959-836cbb80-cc07-11ea-97d4-11dc1c6628eb.png)

**Comment by FrancescoBorzi** [comment]
please open a proper issue by filling ALL the required fields:

![image](https://user-images.githubusercontent.com/75517/88155636-a055be80-cc08-11ea-9273-1f3c0d5ebf6d.png)
