### ISSUE TITLE
Core/Script: Playing music from GameObjects

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#3215]
##### CURRENT BEHAVIOUR:

Currently, we are not able to play music from game objects which cause issues such as music for Holiday zones (i.e. Brewfest) won't be heard

##### EXPECTED BLIZZLIKE BEHAVIOUR:

We'd need to implement the possibility to play music from Gameobjects.

##### STEPS TO REPRODUCE THE PROBLEM:

None as it is not implemented

##### EXTRA NOTES:

TC has it implemented and I have tried to implement it several times but run into build errors that I cannot solve.
https://github.com/TrinityCore/TrinityCore/commit/002b0a7a65167d15969d98b41af7f91d222df664
https://github.com/TrinityCore/TrinityCore/commit/963278459a1d9df5aa3c2e1c8b5f5f112f6a370c
https://github.com/TrinityCore/TrinityCore/commit/e3560f3f518ee8a76921b4922292805c03871d4a
https://github.com/TrinityCore/TrinityCore/commit/19f8acdb616909758391d1c1459fe61196531f3b

**Comment by FrancescoBorzi** [comment]
> I have tried to implement it several times but run into build errors that I cannot solve

you can open a WIP PR and ask for help there

**Comment by Kitzunu** [comment]
yh will do in the future, maybe tomorrow
