### ISSUE TITLE
Core/Spell: Ravenous Dead

### ISSUE THREAD

**Issue by Wowkasu** [azerothcore/azerothcore-wotlk#3217]
##### CURRENT BEHAVIOUR:

Talent https://wotlkdb.com/?spell=49572
![2020-07-22_22-42-31](https://user-images.githubusercontent.com/68443208/88197420-abdad100-cc6c-11ea-84de-f4e631df7ce8.png)
does not increase the parameters of the army of the dead

![2020-07-22_17-02-29](https://user-images.githubusercontent.com/68443208/88197506-c7de7280-cc6c-11ea-86c5-b3deed7615b1.png)
in this picture. It's a stripped character with no talent. https://wotlkdb.com/?spell=49572
https://wotlkdb.com/?npc=24207 are in standard health

![2020-07-22_22-38-04](https://user-images.githubusercontent.com/68443208/88197827-34597180-cc6d-11ea-864b-92815af8f7b7.png)
in this picture in this picture, the character dressed in clothes and took the talent, but the army of the dead doesn't increase in life.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When the knight of death uses the call of the army of the dead, the number of life of the ghouls must be increased from the number of the master.
as in this picture
![2020-07-22_22-48-55](https://user-images.githubusercontent.com/68443208/88198307-c6fa1080-cc6d-11ea-8087-19c6bb7c52a8.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. create a Level 80 Knight of Death, without clothes and without learning talent https://wotlkdb.com/?spell=49572.
2. Call the army of the dead https://wotlkdb.com/?spell=42650.
3. Watch the helpers' life expectancy is (3795).
4. Dress the character in good outfit that gives strength and life. Explore the talent https://wotlkdb.com/?spell=49572
5. Call the army of the dead https://wotlkdb.com/?spell=42650.
6. Look at the parameters of ghoulish helpers 3795 !!! has not changed!

##### EXTRA NOTES:

An audit of my server a week ago. -There's a problem.

We've created a clean version of this day, no modules, - there's a problem.

Checked on the server, with the version of February of the month - there is a pomel.

means it's been in there for a long time.

**Comment by Wowkasu** [comment]
I corrected the time, the working version, I don't know if it's available.

**Comment by Hacaw** [comment]
CONCLUSION
---
I can reproduce this issue.

Ghoul's HP = 3795 (Player with no stamina items + no talent)
![image](https://user-images.githubusercontent.com/6963500/102016449-c1f74400-3d69-11eb-940b-4f3d185712dd.png)


Ghoul's HP = 3795 (Player with stamina items + 3/3 talent)
![image](https://user-images.githubusercontent.com/6963500/102016455-ccb1d900-3d69-11eb-9c14-8bf106618765.png)


TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: adf436c9
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None
