### ISSUE TITLE
Ahn'kahet: The Old Kingdom - Jedoga Shadowseeker - freeze

### ISSUE THREAD

**Issue by hlainin** [azerothcore/azerothcore-wotlk#3218]
Ahn'kahet: The Old Kingdom - Jedoga Shadowseeker - freeze

##### CURRENT BEHAVIOUR:
The jedoga Shadowseeker Boss script in the Ahn'kahet: the Old Kingdom instance stops during combat in a random period. When the boss flies up and has to call one of the acolytes, not one of the acolytes goes. At this point, the script freezes and the jedoga Shadowseeker boss remains on top, it can not be killed. I attached a video of the bug.

Video bug
https://vk.com/video603739362_456239017

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The jedoga Shadowseeker boss in Ahn'kahet: the Old Kingdom instance flies up during the battle and summons one of the minions, one of them must come up and give his life to the boss. After that, the boss goes down and the fight continues.

##### STEPS TO REPRODUCE THE PROBLEM:
1. go inside the instance (normal/heroic) Ahn'kahet: The Old Kingdom
2. Start to fight the boss Jedoga Shadowseeker

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/e428f0d6f16160b4596e5a93d1cab8cc4729b6c7

##### OPERATING SYSTEM:
Debian 10

##### MODULES:
none

##### OTHER CUSTOMIZATIONS:
none

Discord nick - hlainin

**Comment by Conscript01** [comment]
confirmed e3a81ad180a8

**Comment by Si1ker** [comment]
after the rewrite of this instance has working good.
