### ISSUE TITLE
(DB/Quest): Betrayal

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3224]
https://www.wowhead.com/quest=12713/betrayal

**SMALL DESCRIPTION**:
https://www.wowhead.com/item=43059/drakurus-last-wish It is impossible to loot this item, it just does not rise

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by r0m1ntik94** [comment]
```
**QuestRequired**
 Informs the core that the item should be shown only to characters having appropriate quest. This means that even if item is dropped, in order to see it in the loot the player must have at least one quest that has the item ID in its RequiredItemId fields or in its RequiredSourceItemId fields. The player must also have less copies of the item than RequiredItemCount or RequiredSourceItemCount.
```
```sql
UPDATE `gameobject_loot_template` SET `QuestRequired` = 0 WHERE `item` = 43059;
```

And fix spell 57553 (don't work in AzerothCore) fixed.

```sql
INSERT INTO `spell_target_position` VALUES
(57553, 0, 571, 5875.43, -1981.37, 234.671, 0, 0); -- Escape Voltarus
```

**Comment by FrancescoBorzi** [comment]
@r0m1ntik94 can you please [create a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with that fix?
