### ISSUE TITLE
(DB/Quest): Gluttonous Lurkers

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3227]
https://www.wowhead.com/quest=12527/gluttonous-lurkers

**SMALL DESCRIPTION**:
The essence of the quest is to collect rats and feed them to basilisks and loot crystals from them
The bug is that if you sit on the mount, you can endlessly loot one rat 
![download](https://user-images.githubusercontent.com/64589699/88473819-ef159800-cf29-11ea-8c7f-69e95c737589.png)

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by r0m1ntik94** [comment]
```sql
DELETE FROM `smart_scripts`WHERE `entryorguid`= 28202;
INSERT INTO `smart_scripts` VALUES
	(28202, 0, 0, 0, 8, 0, 100, 1, 50926, 0, 0, 0, 0, 11, 50927, 3, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Zul\'Drak Rat - On Spellhit \'Gluttonous Lurkers: Create Zul\'Drak Rat Cover\' - Cast `Create Zul\'Drak Rat`'),
	(28202, 0, 1, 0, 31, 0, 100, 1, 50927, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Zul\'Drak Rat - On Spellhit target \'Create Zul\'Drak Rat\' - Despawn Instant');
```

**Comment by Helias** [comment]
hey @r0m1ntik94, thank you for the fix, could you open a PR for it?

**Comment by r0m1ntik94** [comment]
@Helias sorry can't, if u can create please :)

**Comment by BarbzYHOOL** [comment]
why you can't? we can teach you

**Comment by Helias** [comment]
@r0m1ntik94 after you do the first PR, you will do all in a quick way, really :P

**Comment by r0m1ntik94** [comment]
@Helias @BarbzYHOOL If it's not difficult to explain, I didn't understand the nut.

**Comment by Helias** [comment]
@r0m1ntik94 if you have some problems to do the PRs contact me on Discord I will be glad to help you to make a PR ;-)

my username is Helias#9347

**Comment by Kitzunu** [comment]
If you use Windows, use Github Desktop.
SUPER EASY to create PRs and branches and all of that stuff with it :)
