### ISSUE TITLE
The Lich King is evading on any difficulty.

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#323]
**Description**: So,The Lich King is evading on any difficulty.

**Current behaviour**: After Tirion and Arthas dialogue fight is interrupting and boss is evading. There is a link to ShadowPlay record of this issue - [Click](https://www.youtube.com/watch?v=wNGUj2Je6Sg)

**Expected behaviour**: After intro dialogue, a combat with Lich King must start.

**Branch(es)**: master

**AC hash/commit**:  b9e68be

**Operating system**:  Windows 8.1 x64 with last updates

**Modules**:  Core is without any modules.

**Comment by talamortis** [comment]
I will take a look into this tonight

**Comment by talamortis** [comment]
by the look of the script it checks for the boss data have you killed all bosses in the instance?

**Comment by talamortis** [comment]
![image](https://cloud.githubusercontent.com/assets/6143065/21901152/81324b56-d8ee-11e6-8a62-54837bfd3388.png)

ok so i got him working

**Comment by talamortis** [comment]
this issue is invalid, all bosses need to be killed before lichking is attackable.

**Comment by talamortis** [comment]
but if u want him to work delete the lines  

highlighted.
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L638-L643
