### ISSUE TITLE
(DB/Quest): Yulda's Folly

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3232]
https://www.wowhead.com/quest=12968/yuldas-folly

**SMALL DESCRIPTION**:
https://www.wowhead.com/npc=30046/yulda-the-stormspeaker - There are two of these NPCs, but there should be 1
https://www.youtube.com/watch?v=7FLxca_HV9c

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by pangolp** [comment]
Thanks for the input. From what I see you are using the emulator dated 03/07, you don't know if after that date the fix was made? Because it's 28. In 25 days they could have made several repairs.

**Comment by wowissues** [comment]
> Thanks for the input. From what I see you are using the emulator dated 03/07, you don't know if after that date the fix was made? Because it's 28. In 25 days they could have made several repairs.

no i just checked commits

**Comment by pangolp** [comment]
You were right, there are currently 2 npc. I just checked.

![WoWScrnShot_072820_155528](https://user-images.githubusercontent.com/2810187/88708938-cc7ead00-d0ea-11ea-8708-e69aca4a1be8.jpg)

You should find out which one is left over, usually when it is a mistake, the guid is usually a very big value, but in this case they are consecutive. Anyway, you have to remove 1.

![30046](https://user-images.githubusercontent.com/2810187/88709071-fe900f00-d0ea-11ea-9cf8-2cb440a1f017.png)

**Comment by pangolp** [comment]
I now perform the corresponding pull request. Thank you.
