### ISSUE TITLE
Mana does not regenerate

### ISSUE THREAD

**Issue by jwh1981** [azerothcore/azerothcore-wotlk#3237]
I am on commit: https://github.com/azerothcore/azerothcore-wotlk/commit/91bbbf08eb73837f50469ad5dac7a106cecadb8f and I found that mana is not regenerating. My Setup is Debian 10 x86_64 with MySQL 5.7.  I tested with a human mage and ran my mana down to near 0. I waited about 5 min and my mana is still only 5 (it never increased). I confirmed that Rate.Mana in worldserver.conf is 1.

I also tested with an Undead Mage also and the mana failed to regenerate.

**Comment by Lulzcritic** [comment]
I am on commit b9ff7eb and same problem on mana regen, my setup is Windows 10 with MySQL 5.7. It only happen at level 1 on new characters, as soon as I reach level 2, the mana regen works fine.

**Comment by imxari** [comment]
Commit: `b9adeba`

I can confirm that this issue isn't present on the above commit from the 7th of July.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/88837235-933d5e80-d20a-11ea-824d-edaf6dac5790.png)
![image](https://user-images.githubusercontent.com/18535853/88837257-9a646c80-d20a-11ea-93d9-512d194bb52a.png)
It can't be reproduced

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/88837721-1494f100-d20b-11ea-9d1b-7c8e4aa212f1.png)
![image](https://user-images.githubusercontent.com/18535853/88837737-1e1e5900-d20b-11ea-81c3-6db2d3a0b5ee.png)
It can't be reproduced

**Comment by jwh1981** [comment]
Maybe its a locale thing. Its possible that its only for latin-based character sets.

**Comment by TheSkorpiox** [comment]
@pklloveyou Which build where you running ?

**Comment by pklloveyou** [comment]
Current latest submission，win10x64 MariaDB10.5

**Comment by jwh1981** [comment]
> 
> 
> I am on commit [b9ff7eb](https://github.com/azerothcore/azerothcore-wotlk/commit/b9ff7eb0c1570fe75187d466ad4a73b400001120) and same problem on mana regen, my setup is Windows 10 with MySQL 5.7. It only happen at level 1 on new characters, as soon as I reach level 2, the mana regen works fine.

I just confirmed this as well. As soon as I leveled up past level 1, mana regeneration works.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/88879784-b5ac9780-d25d-11ea-9214-4fa42e12f513.png)
![image](https://user-images.githubusercontent.com/18535853/88879770-afb6b680-d25d-11ea-91e7-43ee5dcbdf76.png)
![image](https://user-images.githubusercontent.com/18535853/88879893-f73d4280-d25d-11ea-803b-04d11ce18bb1.png)
![image](https://user-images.githubusercontent.com/18535853/88879912-ff957d80-d25d-11ea-923b-8e901ca6f7b9.png)

**Comment by Tyrelis** [comment]
@FrancescoBorzi I have just tested this issue and also can confirm that you do not regenerate mana when the player is level one. I am using latest comment 91bbbf0 and tested this on a human mage. Once I hit level 2 the issue with not regenerating mana tends to fix itself. The not confirm tag in invalid.

**Comment by jwh1981** [comment]
I agree with @Tyrelis, this is still a bug and should be marked as Confirmed as a few of us confirmed the issue.

**Comment by ninjaskija** [comment]
I've seen this also. Using the latest commit also [91bbbf0](https://github.com/azerothcore/azerothcore-wotlk/commit/91bbbf08eb73837f50469ad5dac7a106cecadb8f)

**Comment by merdlin** [comment]
am on commit [fcaf91b](https://github.com/azerothcore/azerothcore-wotlk/commit/fcaf91b8b2af5ca34f63cad66f0184997b827c61) and same problem on mana regen

**Comment by Conscript01** [comment]
e3a81ad180a8 confirmed

**Comment by BarbzYHOOL** [comment]
plz test https://github.com/azerothcore/azerothcore-wotlk/pull/3216 guys
