### ISSUE TITLE
(DB/Quest): Kyle's Gone Missing!

### ISSUE THREAD

**Issue by bmilescu** [azerothcore/azerothcore-wotlk#3239]
Quest description:
https://wotlkdb.com/?quest=11129

##### CURRENT BEHAVIOUR:
[Tender Strider Meat](https://wotlkdb.com/?item=33009) does not seem to drop.
I've dropped the quest and retook it, but I still didn't see it drop.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Should drop in order to be able to complete the quest

##### STEPS TO REPRODUCE THE PROBLEM:
Kill [Adult Plainstrider](https://wotlkdb.com/?npc=2956) and [Elder Plainstrider](https://wotlkdb.com/?npc=2957)

##### AC HASH/COMMIT:
Branch: master
Commit: [fcaf91b](https://github.com/azerothcore/azerothcore-wotlk/commit/fcaf91b8b2af5ca34f63cad66f0184997b827c61)

##### OPERATING SYSTEM:
Docker

##### MODULES:
https://www.azerothcore.org/catalogue/details.html?id=76854669

**Comment by ninjaskija** [comment]
My bad, it finally dropped, but I was expecting by looking at the drop rate to be rather sooner than later. 
I killed like 20-30 of them before it dropped.
I guess it can be closed if this is normal behavior.

**Comment by pangolp** [comment]
Thanks for the report, the pull request has been made and I have just tested it. Indeed the item had a too low drop. I had to kill about 10 npc to receive it, but now it has a 50% chance to drop.
