### ISSUE TITLE
[DB/Creature] Palemane Skinner/Tanner/Poacher not using abilities

### ISSUE THREAD

**Issue by ninjaskija** [azerothcore/azerothcore-wotlk#3240]
##### CURRENT BEHAVIOUR:
The mentioned mobs are only attacking melee, they don't use any ability.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They should use the described abilities:

https://wotlkdb.com/?npc=2949
https://wotlkdb.com/?npc=2950
https://wotlkdb.com/?npc=2951

##### STEPS TO REPRODUCE THE PROBLEM:
Engage the mobs and observe.

##### AC HASH/COMMIT:

[f56ef23](https://github.com/azerothcore/azerothcore-wotlk/commit/f56ef239de2e8c0dba48eed8c6a6c20664c5952e)

##### OPERATING SYSTEM:
Docker under Ubuntu 20.04

##### MODULES:
AutoBalance

**Comment by r0m1ntik94** [comment]
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 2949;
INSERT INTO `smart_scripts` VALUES
	(2949, 0, 0, 0, 4, 0, 30, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Palemane Tanner - On Aggro - Say Line 0'),
	(2949, 0, 1, 0, 0, 0, 100, 0, 0, 0, 2400, 3800, 0, 11, 9739, 64, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Palemane Tanner - In Combat - Cast \'Wrath\''),
	(2949, 0, 2, 0, 2, 0, 100, 1, 0, 15, 0, 0, 0, 25, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Palemane Tanner - Between 0-15% Health - Flee For Assist');
```
Profit :) sorry can't create PR, if someone can create.

**Comment by ninjaskija** [comment]
So basically the all the skills that a NPC uses are described in the database? Can we see other missing skills for the rest of the NPSs? Maybe comparing with TC?

**Comment by r0m1ntik94** [comment]
@ninjaskija These mobs were simply not scripted on AzerothCore. I pulled this script out with TC, work perfectly.

**Comment by BarbzYHOOL** [comment]
apply this to the DB and test @ninjaskija and tell us if it works plz

@r0m1ntik94 why you say you can't make a PR?

**Comment by Knindzagxg** [comment]
All of these are sorted, just not Merged yet.

https://github.com/azerothcore/azerothcore-wotlk/pull/3144

**Comment by Knindzagxg** [comment]
Yeah, guess we can.
Its merged week or something ago, lazy to search via phone xP
