### ISSUE TITLE
[DB/Creature] Prairie Wolf/Stalker/Wolf Alpha not using abilities

### ISSUE THREAD

**Issue by ninjaskija** [azerothcore/azerothcore-wotlk#3241]
##### CURRENT BEHAVIOUR:
The mentioned mobs are only attacking melee, they don't use any ability.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They should use the described abilities:

https://wotlkdb.com/?npc=2958
https://wotlkdb.com/?npc=2959
https://wotlkdb.com/?npc=2960

##### STEPS TO REPRODUCE THE PROBLEM:
Engage the mobs and observe.

##### AC HASH/COMMIT:

[f56ef23](https://github.com/azerothcore/azerothcore-wotlk/commit/f56ef239de2e8c0dba48eed8c6a6c20664c5952e)

##### OPERATING SYSTEM:
Docker under Ubuntu 20.04

##### MODULES:
AutoBalance

**Comment by r0m1ntik94** [comment]
```sql

UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` IN (2958, 2959, 2960);

INSERT INTO `smart_scripts` VALUES
	(2958, 0, 0, 1, 1, 0, 100, 0, 30000, 600000, 120000, 600000, 0, 4, 1018, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Wolf - Out of Combat - Play Sound 1018'),
	(2958, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 5, 393, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Wolf - Out of Combat - Play Emote 393'),
	(2958, 0, 2, 0, 0, 0, 100, 0, 6000, 10000, 35000, 45000, 0, 11, 5781, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Wolf - In Combat - Cast Threatening Growl');

INSERT INTO `smart_scripts` VALUES
	(2959, 0, 0, 1, 1, 0, 100, 0, 30000, 600000, 120000, 600000, 0, 4, 1018, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Stalker - Out of Combat - Play Sound 1018'),
	(2959, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 5, 393, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Stalker - Out of Combat - Play Emote 393');

INSERT INTO `smart_scripts` VALUES
	(2960, 0, 0, 1, 1, 0, 100, 0, 30000, 600000, 120000, 600000, 0, 4, 1018, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Wolf Alpha - Out of Combat - Play Sound 1018'),
	(2960, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 5, 393, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Wolf Alpha - Out of Combat - Play Emote 393'),
	(2960, 0, 2, 0, 0, 0, 100, 0, 6000, 10000, 35000, 45000, 0, 11, 5781, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Prairie Wolf Alpha - In Combat - Cast Threatening Growl');

```

**Comment by ninjaskija** [comment]
@r0m1ntik94 @FrancescoBorzi @Kitzunu  Tested and seems to work fine! There are a lot more of NPC's that present the same behavior. Is there any way to fix them all? Maybe extract those values from an established database like the one from TrinityCore?

**Comment by r0m1ntik94** [comment]
@ninjaskija TC have 9075 creature scripted SmartAI and AzerothCore have 7927. Need extract this 👍

**Comment by Knindzagxg** [comment]
Whole Mulgore zone is fixed, but not merged yet.

You can check https://github.com/azerothcore/azerothcore-wotlk/pull/3144

**Comment by r0m1ntik94** [comment]
Yesterday I transferred more than 2k scripts from trinity, testers are checking, I did not do it by zone.

**Comment by Knindzagxg** [comment]
Most of them have to be fixed, cause they are made long time ago.
I'm 80% done with all zones and classic/tbc dungeons so all of them should be up in 2-3 weeks.

**Comment by BarbzYHOOL** [comment]
but yes, shouldn't we import the SQL for creatures that are not scripted? because there is no risk of overwriting our work if these creatures are NOT scripted at all
