### ISSUE TITLE
Icecrown Citadel Raid - Saurfang Intro Roleplay

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#3246]
EXPECTED BLIZZLIKE BEHAVIOUR:

After the introduction roleplay (Tirion + Saurfang/Muradin talk) after the two bone warriors die), Saurfang/Muradin and their entourage (their generals) should walk to the instance portal, but they should also despawn. He is also using the wrong model in this area of ICC. He should be using his red Warrior gear here. https://wow.zamimg.com/uploads/screenshots/normal/150141-high-overlord-saurfang.jpg (photo from ICC entrance)

CURRENT BEHAVIOUR:

Intro: After the intro roleplay to the instance, Saurfang and Muradin walk to the instance portal and.. just stay there - forever. He is also using the wrong model in this area of ICC: https://i.imgur.com/O1tE6b5.jpg - However, he does use the correct model for the Gunship battle and Saurfang arenas.

STEPS TO REPRODUCE THE PROBLEM:

1.  Go into ICC on 10/25 Normal/Heroic
2.  Defeat the two bone warriors to initiate the roleplay
3. Watch Saurfang or Muradin, and follow them when they start walking towards the entrance.

EXTRA NOTES:

N/A
BRANCH(ES):

master
AC HASH/COMMIT:

1411336
OPERATING SYSTEM:

Win10
MODULES:

N/A
OTHER CUSTOMIZATIONS:

Increased health modifiers on bosses

**Comment by r0m1ntik94** [comment]
![Capture d’écran 2020-08-03 à 21 10 27](https://user-images.githubusercontent.com/12685486/89218136-cb0f2200-d5cd-11ea-8757-b03d425b1dcc.png)
Comfirme

**Comment by r0m1ntik94** [comment]
@Voxstrasza 
```sql
UPDATE `creature` SET `id` = 37187 WHERE `id` = 32315;
```

![Capture d’écran 2020-08-03 à 21 41 56](https://user-images.githubusercontent.com/12685486/89220614-2e02b800-d5d2-11ea-9ff9-a9830c01cf6b.png)

**Comment by BarbzYHOOL** [comment]
@voxstrasza can you test?

**Comment by Voxstrasza** [comment]
Tested the fix, it's good and gives Saurfang the correct model.

**Comment by BarbzYHOOL** [comment]
ok but event must stil be fixed

**Comment by Voxstrasza** [comment]
> 
> 
> ok but event must stil be fixed, right?

Depends on what you mean by fixed, the event works perfectly, but the NPCs don't despawn as they should once they reach the instance portal (roleplay/event --> walk to instance portal --> stay there forever)

**Comment by FrancescoBorzi** [comment]
@r0m1ntik94 same here: can you please open a PR with your fix? I can help you with it.

All you need is explained here: https://www.azerothcore.org/wiki/How-to-create-a-PR 

However, I'm available for further clarification if needed.

**Comment by Remberance** [comment]
if you changed 32315 to 37187, muradin and saurfang will have gossip in light hammer.

Found the problem: if you change 32315 to 37187(front of ICC 4TH BOSS), they will have gossip menu, i searched the database, i found 36969, but in 'creature' database 36969 in map 673, and this map isn't exists, when i changed 32315 to 36969 in 'creature', when i come into icc game client will crash. so i think the problem is 36969!!!

im sorry my bad english, anyone understand what i said?
