### ISSUE TITLE
".cheat power" should give full power or require 0 power to work

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3257]
##### CURRENT BEHAVIOUR:

Currently, `.cheat power` requires you to have some "power" first.
This mostly affects warriors and death knights, they start at 0 rage or runic power, so they can't use their high cost spells until they get enough power. It's very annoying when testing, especially because it decreases with time.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Imo, it should give 100 (max) power in these cases. It could also refill rogue's energy and mana.

**Comment by Kitzunu** [comment]
A work around is to use .mod rage 1000000

**Comment by BarbzYHOOL** [comment]
yes, just found out, still kinda confusing when you don't know the commands, and forces u to go extra steps (so it's bad)
