### ISSUE TITLE
Can't boot worldserver since yesterday

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#326]
Pretty much updated and got a handful of errors, now the Database should be fine however my maps/vmaps are incompatible. I got the maps part working however when extracting the VMAPS all I get is...

http://i.imgur.com/o41yDSc.png

So I don't know what to do right now :(

Edit: extracting on Windows

**Comment by Inifield** [comment]
yeah the last error on your screen is normal don't worry
