### ISSUE TITLE
Config global function to extract values from a comma separated list

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3267]
### Concept

We need a function in the config manager to easily extract values from a string list.
Ex: "1,2,3,4" or "1, 2, 3, 4"

In the module conf:
MyModule.List = "1, 2, 3, 4"

In the module cpp:
```cpp
sConfigMgr->GetUint32ListDefault("MyModule.List", "")
```

Actually, everytime we want to make a list, we have to recreate a similar function in our modules. This is very bad
Maybe we can also have an argument to choose the delimiter and by default it's a comma `,`.

### This is what I tried unsuccessfully:

On a suggestion by Malow:

common/Configuration/Config.cpp
```cpp
// Wrapper around GetStringDefault to get values from a comma separated list from a string
std::vector<uint32> ConfigMgr::GetUint32ListDefault(const char* name, const std::string &def, bool logUnused /*= true*/)
{
    string input = GetStringDefault(name, def, logUnused);

    vector<uint32> list;

    while (input.find(", ") != std::string::npos)
    {
        list.push_back(stoi(input.substr(0, s.find(", "))));
        input = input.substr(2);
    }

    // sLog->outError("============= %u", list);
    return list;
}
```

common/Configuration/Config.h
```cpp
    std::vector<uint32> GetUint32ListDefault(const char* name, const std::string& def, bool logUnused = true);
```
The Config.h fails at compilation but I don't know how all this works so I can't fix it.

Also, I don't know if vector is the right data type to use as in the module I wanted that for, the list is in that form:
```cpp
std::unordered_set<uint32> m_ignoreSpells = { 64380, 23885, 23880 };
```
unordered_set and not vector

The idea was to put this in the config, but also add a secondary list of optional spells and then merge them together. cf: https://github.com/azerothcore/mod-learn-spells/issues/17

### Conclusion 

Once done, it could also be used in mod-autobalance and replace the function created there `LoadForcedCreatureIdsFromString()`

**Comment by Riztazz** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/4a8f1de5381d1cf53cdcc4c5bb7d9ef7c99a8a8f/src/server/game/Chat/Channels/ChannelMgr.cpp#L155

like this?;p

**Comment by BarbzYHOOL** [comment]
there is another function to tokenize too, if I recall right, but anyway need to add it to the core and test it, which I didn't manage to do, needs someone who knows cpp

**Comment by FrancescoBorzi** [comment]
yooo @Riztazz

**Comment by Riztazz** [comment]
But you already have a function for it, what do you need another one?
In theory you could make a wrapper for it that deduces data types but use-cases are so very low that i don't think it's worth investing time into, just tokenize it on startup/reload and you're good to go.

```
Tokenizer toks(LoadConfigString, ',');
for (auto&& token : toks)
{
    DataType value = do your cast to type;
    container.insert/push_back/whatever
}
```

Hello Shin <3

**Comment by Kitzunu** [comment]
already possible see https://github.com/azerothcore/azerothcore-wotlk/blob/b84596fcaba2b805723e30d291c570c09c091f94/src/server/apps/worldserver/worldserver.conf.dist#L1856
