### ISSUE TITLE
[Core] Critical Bug in Character Stats

### ISSUE THREAD

**Issue by XpiroClass** [azerothcore/azerothcore-wotlk#3268]
**Last updates have a critical bug in base stats for character**

CURRENT BEHAVIOUR:
All characters have bug  stats about critical mele and spell base

STEPS TO REPRODUCE THE PROBLEM:
 - Compile and start server using lasted masters repos
 - Create chararctes (its more notory in druid)
 - Check critical for new char level 1  (mele = 34%, Spell = 20% ) Really crasy O.o
 - Other class like warrior are negatively affected check level 80 with 20% minor critic mele aprox.

PICS

![WoWScrnShot_080820_113413](https://user-images.githubusercontent.com/69396219/89715542-dc5c8380-d96b-11ea-890a-6d2a1e3d02d8.jpg)
![WoWScrnShot_080820_113420](https://user-images.githubusercontent.com/69396219/89715543-dd8db080-d96b-11ea-9c6b-3af4aacc1893.jpg)

AC HASH/COMMIT:
Test for last time in cdb4999

##### OPERATING SYSTEM:
Linux

##### MODULES:
No modules

**Comment by Winfidonarleyan** [comment]
#3216

**Comment by BarbzYHOOL** [comment]
@winfidonarleyan please be clear to new people :) "Please, test this pull request #3216 for a solution"

**Comment by r0m1ntik94** [comment]
@XpiroClass after #3216
![Capture d’écran 2020-08-08 à 19 57 11](https://user-images.githubusercontent.com/12685486/89716912-63801a80-d9b1-11ea-8adc-a26f1eb43b52.png)
