### ISSUE TITLE
Scalding Mornbrew Delivery

### ISSUE THREAD

**Issue by Flerex** [azerothcore/azerothcore-wotlk#327]
**Description**: Mission _Scalding Mornbrew Delivery_ from the initial Dwarf/Gnome zone gets completed even when the timer runs out of time.

**Current behaviour**: It gets auto-completed when the timer runs out of time

**Expected behaviour**: It should mark it as failed.

**Branch(es)**: master

**AC hash/commit**:  e30ae1d4c329b8a203ed0d75b6eccccef30cba66

**Operating system**:  MacOS

**Modules**:  Nope

**Other Customizations**: Nope

**Comment by ShinDarth** [comment]
missing revision commit hash, please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

and update your report adding the hash

**Comment by Flerex** [comment]
Fixed

**Comment by starrheld** [comment]
**Can someone confirm?**
-----------------------------
From **WOWHEAD**

> By Dregothalom (135 – 1) on 2009/12/24 (Patch 3.3.0)		
No longer timed as of patch 3.3.

Source: http://www.wowhead.com/quest=3364/scalding-mornbrew-delivery

If so
- Fix:

```SQL
UPDATE `quest_template` SET `LimitTime` = 0 WHERE `id` IN(3364);
```
