### ISSUE TITLE
(DB/Creature): Uhk'loc/Rak'shiri and others vanilla rares

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3270]
**SMALL DESCRIPTION**:
https://wowhead.com/npc=6585/uhkloc
https://wowhead.com/npc=10200/rakshiri
And others vanilla rares have empty loot.

**AC HASH/COMMIT**:
AzerothCore rev. cdb4999

**OPERATING SYSTEM**:
Debian 10

**MODULES**:
CFBG, Anticheat, learnallspells, duelreset, transmog, pvptitles

**Comment by r0m1ntik94** [comment]
can't confirm for
```
https://wowhead.com/npc=6585/uhkloc
https://wowhead.com/npc=10200/rakshiri
```
![Capture d’écran 2020-08-09 à 15 56 56](https://user-images.githubusercontent.com/12685486/89733902-fc1da580-da58-11ea-9e2e-7bc828156645.png)

**Comment by PivanDepolo** [comment]
> can't confirm for
> 
> ```
> https://wowhead.com/npc=6585/uhkloc
> https://wowhead.com/npc=10200/rakshiri
> ```
> 
> ![Capture d’écran 2020-08-09 à 15 56 56](https://user-images.githubusercontent.com/12685486/89733902-fc1da580-da58-11ea-9e2e-7bc828156645.png)

try in game
попробуй в игре бро, да и можно твои контакты узнать? За денежки фиксы делаешь?

**Comment by r0m1ntik94** [comment]
@PivanDepolo в игре тоже работает проверил только что.
дискорд: r0m1ntik#2435
вк: https://vk.com/romanfrance94

**Comment by Kitzunu** [comment]
Please translate into English whenever you write in a foreign language.

**Comment by BarbzYHOOL** [comment]
there is one in the southern barrens too

**Comment by alexkulya** [comment]
This situation can occur here with any rare NPC in the locations EK, Kalimdor, Outland (in some loot is not present at all). In the loot of each rare mob, there must be at least one ref loot build with a 100 percent chance of falling out. to correct the situation, you need to check and correct absolutely all the loot of rare mobs in the above locations.

**Comment by LukasVolgger** [comment]
Cannot reproduce for this 2 creatures on commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4. Sometimes creatures just drop 0 items - just respawn them and try again. 

TaDa 
![image](https://user-images.githubusercontent.com/55922592/100499630-6cb51300-316b-11eb-8cad-8721ed2cfd31.png)

![image](https://user-images.githubusercontent.com/55922592/100500133-953d0d00-316b-11eb-8891-9242a92ee369.png)
