### ISSUE TITLE
The Nexus - Anomalus boss

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3274]
##### CURRENT BEHAVIOUR:

1. Keeps his rift shield up even after the rift is destroyed
2. Is able to charge rifts way off the platform 

![image](https://user-images.githubusercontent.com/4015312/89740325-8b689000-da3c-11ea-9b27-82af948ecf42.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. When the rift on the platform is destroyed, Anomalus shield should go away.
2. Anomalus should only be able to charge rifts on the platform. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go into The Nexus 
2. leave rifts off the platform un-touched
2. Attack Anomalus until he spawns a rift 
3. Destroy the rift and check if his shield is still present.
4. Monitor rifts off platform and see that he charges them

##### AC HASH/COMMIT:

https://github.com/locus313/azerothcore-wotlk/commit/e3a81ad180a83805a1b0226d62aaee00be9d17c8

##### OPERATING SYSTEM:

Centos 7

##### MODULES:

AutoBalance (tested with and without it enabled)
Individual-XP
AHbot
Customlogin
Transmog

**Comment by pangolp** [comment]
First of all, thanks for the report. I went to the dungeon, I started the fight, but even though I used the faults that are outside the platform, when the casting is done, the boss can be eliminated without any problem, the truth is that I don't have enough information, to really say that this is a mistake or not.

**Comment by locus313** [comment]
Thanks @pangolp. I was also able to finish the boss after the casting was done. I am pretty sure the range of the spell is not blizzlike.

**Comment by Kitzunu** [comment]
I am pretty sure the script of this is quite off anyway so needs looking ove
