### ISSUE TITLE
DK Blood

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#328]
Can anyone please check out the threat of BLOOD DKS? Can't hold aggro, whole party is getting aggro... doens't even matter what I do... <3

**Comment by ShinDarth** [comment]
this is not a chat, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

if you just want to chat, please use our official chat:  https://gitter.im/azerothcore/azerothcore
