### ISSUE TITLE
(DB/Quest): Anguish of Nifflevar

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3281]
https://www.wowhead.com/quest=11344/anguish-of-nifflevar
**SMALL DESCRIPTION:**
you listen to all the dialogue, but the quest does not count

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. cdb4999+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by r0m1ntik94** [comment]
can't confirm, quest work. u need just use /bow or /поклон (Russian) for this quest.
![Capture d’écran 2020-08-12 à 19 08 08](https://user-images.githubusercontent.com/12685486/90045569-84a57b80-dccf-11ea-94a7-ff52fab95e6f.png)
