### ISSUE TITLE
(DB/Quest): The Alchemist's Apprentice

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3282]
https://www.wowhead.com/quest=12602/the-alchemists-apprentice
**SMALL DESCRIPTION**:
does not throw ingredients into the container

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. cdb4999+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by r0m1ntik94** [comment]
Wrong quest id, maybe: 
```c++
QUEST_ALCHEMIST_APPRENTICE      = 12541
```
On quest accept, use gossip and can complete quest.
![Capture d’écran 2020-08-12 à 19 48 56](https://user-images.githubusercontent.com/12685486/90049286-e1effb80-dcd4-11ea-9628-3dbaafb00582.png)

**Comment by LukasVolgger** [comment]
Working very well on commit 2788d49

Closing this one as there is no bug.
