### ISSUE TITLE
(DB/Quest): Judgment Day Comes!

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3283]
https://www.wowhead.com/quest=13226/judgment-day-comes
**SMALL DESCRIPTION**:
There is no character or a problem with phasing, or I screwed up myself because I made another chain with this character

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. cdb4999+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Hacaw** [comment]
I can't reproduce any issue with this specific quest.
@PivanDepolo I don't understand the description.

TESTING
---
1. .go c id 28179
2. .q add 13226
3. it completes without issues

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None
