### ISSUE TITLE
(DB/Quest): Shadow Vault Decree

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3284]
https://www.wowhead.com/quest=12943/shadow-vault-decree
**SMALL DESCRIPTION**:
When entering the cave, where the quest is being completed, the battalion commander is hung up, which does not allow the use of the item https://www.wowhead.com/item=41776/shadow-vault-decree, thereby the quest becomes impossible.

In addition, the battalion commander no longer falls off the player, even after exiting the game, which can only be resolved by the Hearthstone

Quite a nasty and critical error

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. cdb4999+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by felwyn** [comment]
Confirmed. Quest not working.
![WoWScrnShot_083020_131046](https://user-images.githubusercontent.com/70294869/91657566-44613e00-eac2-11ea-9ea1-20f392642238.jpg)

**Comment by wizzymore** [comment]
Seems like it worked here:
https://github.com/azerothcore/azerothcore-wotlk/issues/258

**Comment by wizzymore** [comment]
I think i found the sweet spot:

![image](https://user-images.githubusercontent.com/25827787/103182855-48a63800-48b7-11eb-9369-fea22a39e707.png)
It works from here
