### ISSUE TITLE
(DB/Quest): Post-partum Aggression

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3285]
https://www.wowhead.com/quest=12614/post-partum-aggression
**SMALL DESCRIPTION**:
Killed the https://www.wowhead.com/npc=28467/broodmother-slivina while riding a Mammoth (according to the quest), as a result, they did not count. I had to kill a second time "with my own hands" without a mammoth and it works.

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. cdb4999+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by felwyn** [comment]
Can confirm. Will only count as kill when not riding the mammoth.

![WoWScrnShot_083020_120959](https://user-images.githubusercontent.com/70294869/91656541-bda86300-eab9-11ea-8e2a-869e6b7de6a7.jpg)

**Comment by Shadofiend** [comment]
confirm

**Comment by Helias** [comment]
https://github.com/TrinityCore/TrinityCore/issues/18079
