### ISSUE TITLE
(DB/Quest): Spirits Watch Over Us

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3286]
https://www.wowhead.com/quest=11961/spirits-watch-over-us
**SMALL DESCRIPTION**:
Totem cannot be picked up with NPC https://www.wowhead.com/npc=26219/iruk

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. cdb4999+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by r0m1ntik94** [comment]
can't confirm.

 .go xyz 2963 4671 -29.98 571

![Capture d’écran 2020-08-12 à 20 19 17](https://user-images.githubusercontent.com/12685486/90052303-40b77400-dcd9-11ea-8b4b-2d381382e215.png)

![Capture d’écran 2020-08-12 à 20 19 22](https://user-images.githubusercontent.com/12685486/90052313-41e8a100-dcd9-11ea-8a5a-199d525785e9.png)

**Comment by felwyn** [comment]
Yes quest is  doable!
