### ISSUE TITLE
New dbc, maps, etc..?

### ISSUE THREAD

**Issue by Cubansephiroth** [azerothcore/azerothcore-wotlk#329]
**Description**:

After update today with    e30ae1d4c329b8a203ed0d75b6eccccef30cba66    
worldserver cant start due to outdated maps.
/maps/0004331.map' is from an incompatible clientversion. Please recreate using the mapextractor.

Anyone can upload updated data? i am running a server in linux and is not an option for me to upload the game to the server and use extractors in linux.

**Current behaviour**: Worldserver cant load maps

**Expected behaviour**: Worldserver should start fine.

**Steps to reproduce the problem**:

1.  just start worldserver ./worldserver
2. 
3. 

**Branch(es)**: Master

**AC hash/commit**: e30ae1d4c329b8a203ed0d75b6eccccef30cba66

**Operating system**:  Ubuntu 16.04

**Modules**:  Are you using modules? if yes, list them
Anticheat - Duelreset - Transmog

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
redo your maps they have been updated.

**Comment by ShinDarth** [comment]
in past I've always used the extractor under linux: actually you can either compile them and use the native extractor or run the windows version using wine

**Comment by Cubansephiroth** [comment]
@talamortis  from the mega link in Wiki?

**Comment by talamortis** [comment]
no mate do the tools in git and run map_exteacter

**Comment by Cubansephiroth** [comment]
@talamortis tools?

**Comment by talamortis** [comment]
http://frostmourne.servebeer.com/downloads/mapextractor.exe 

click the link it will give u the new extractor run that in ur wow directory and place the maps folder into ur server directory.

**Comment by Cubansephiroth** [comment]
@talamortis works like a charm. Thanks to you and @ShinDarth  for your support.

**Comment by ArthasCore** [comment]
Пиздец вы мудаки сука самаучки не могут сделаить нормально экстракторы )))))
