### ISSUE TITLE
(Core/guild) guild leader left his guild inexplicably.

### ISSUE THREAD

**Issue by kuramajssken001** [azerothcore/azerothcore-wotlk#3290]
SMALL DESCRIPTION:
Guild President loses guild management when he goes offline and goes online. He is no longer guild President.
This is not a common problem.

BRANCH(ES): master

AC HASH/COMMIT: AzerothCore rev. 96fc9fc

OPERATING SYSTEM: Debian9

**Comment by CosmeF** [comment]
may be related with #3291

**Comment by FrancescoBorzi** [comment]
@kuramajssken001 the fix should now be on master. Please update your core to the latest version and let us know if the bug persists.

**Comment by kuramajssken001** [comment]
> @kuramajssken001 the fix should now be on master. Please update your core to the latest version and let us know if the bug persists.

@FrancescoBorzi Okay now last commit,but problem remains.

**Comment by kuramajssken001** [comment]
> may be related with #3291

yeah, i try. thank u.

**Comment by hlainin** [comment]
> > @kuramajssken001 the fix should now be on master. Please update your core to the latest version and let us know if the bug persists.
> 
> @FrancescoBorzi Okay now last commit,but problem remains.

Please tell us in detail how to repeat this problem?

**Comment by kuramajssken001** [comment]
@hlainin this is not a common problem.

**Comment by Si1ker** [comment]
@FrancescoBorzi remember viola and its arena team? this happened in BF with arena teams and guilds as well as you may remember, there is no way to reproduce it, it just happens from time to time.

**Comment by FrancescoBorzi** [comment]
@Si1ker yes I do remember. @CosmeF found a way to reproduce the issue and has a solution for it: https://github.com/azerothcore/azerothcore-wotlk/pull/3291

So this issue is probably solved. I'd say better close it and if anyone still has it on a new AC then we can reopen it.
