### ISSUE TITLE
(DB/Quest): Sorlof's Booty [$30]

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3298]
##### CURRENT BEHAVIOUR:

You have to click very quick to be able to kill him with the cannon. If you only fire a few shots at a time he will regen his health right away. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to fire shots at a much slower rate and sorlof's health should not regen right away.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 11529
2. .tele howling fjord

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d2cc3fcbc2d7bf0b185eb03d169afc9783870568

##### OPERATING SYSTEM:

Centos 7

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

**Comment by Kitzunu** [comment]
This is due to the NPC not going in combat

**Comment by felwyn** [comment]
Confirmed

**Comment by steenburgh** [comment]
Confirmed. Just encountered this while questing. I'm running Azeroth Core commit 27ed629ff5d49dee5e12e7564b52f232dda947b9

**Comment by mpfans** [comment]
Confirm. If the level 80 rapid firing shell can be completed, if the level 70 will not be completed
