### ISSUE TITLE
Crossfaction bg bug

### ISSUE THREAD

**Issue by franklampardahar** [azerothcore/azerothcore-wotlk#330]
**Description**: Crossfaction bg Druid
 
**Current behaviour**: when config crossfaction bg Druids all the time when change into shapeshift remove his/him shapeshift morphs .

**Expected behaviour**: Make Druid / Go in bg after bg finished go out from bg or in bg change into cat/bear/etc

**Operating system**:  win 7 64bit

**Modules**:  anticheat - transmog - duelreset

i think if we don't change druids morph and send to players a message like you are ally/horde and after bg dont remove druids morph it get to fix .

**Comment by ShinDarth** [comment]
where is the revision? (commit hash) :D

**Comment by franklampardahar** [comment]
Sorry for commit :) ee6f152

**Comment by Raz240** [comment]
Which module are you using? @Franklampardst
