### ISSUE TITLE
(DB/Quest): Adding injury to insult

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3303]
##### CURRENT BEHAVIOUR:

After insulting him when you try to walk him over he will reset before you reach the ambush.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to reach the ambush without him resetting.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 12481
2. .tele howling fjord
3. 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d2cc3fcbc2d7bf0b185eb03d169afc9783870568

##### OPERATING SYSTEM:

Centos 7

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

**Comment by peti446** [comment]
It can be a bit difficult to get him to the Ambush, but it is possible, I agrroed him using the Vrykul Insult , then immediately I started running to the ambush.
Once I got over the water the debuff was about to go out, but when he started crossing the water I attacked him and he continued to follow me.

I would also like to add I agroed him from the furthest away possible with the vrykul insult.

![image](https://user-images.githubusercontent.com/4162295/91221760-0953b900-e716-11ea-8918-a1692adc64e0.png)

**Comment by locus313** [comment]
@peti446 Thanks for checking this out. i did some more testing and i found that if i just attack him before the water he will continue to follow. I saw the time for the buff is at 25 seconds. Which looks to be correct.
https://wowgaming.altervista.org/aowow/?spell=43315#used-by-item
ill go ahead and close this out.
