### ISSUE TITLE
Heroic Dungeon - Ahn'Kahet, The Old Kingdom - Amanitar encounter 

### ISSUE THREAD

**Issue by NexusWoW** [azerothcore/azerothcore-wotlk#331]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
You engage Amanitar in H-OK and he casts mini and mushrooms spawn about the area. The mushrooms are not targetable or damageable by aoe.

Expected behaviour: Tell us what should happen instead
You engage Amanitar in H-OK and he casts mini and mushrooms spawn about the area the healthy mushrooms should be targetable and killable and remove the debuff mini.

Steps to reproduce the problem:

In H-OK, clear trash around Amanitar and then engage him.

Attempt to kill healthy mushrooms.

Include proofs for this behaviour
Wowwiki article: http://wowwiki.wikia.com/wiki/Amanitar
"Killing a healthy mushroom when you are "mini" and close to it removes the debuff and appears to be the key to the encounter. Healing through crit chains is very difficult depending on your tank type - dodge-based druids fare better than defense-based prot warriors."

**Comment by talamortis** [comment]
should the healthy mushrooms be attackable or just the posion ones?

**Comment by NexusWoW** [comment]
I am under the impression both are attackable, since you are supposed to be able to clear the tanking area.
