### ISSUE TITLE
Quest [Basic Chemistry]

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#332]
**Description**: Not working properly...

**Current behaviour**: You can use [Pustulant Spinal Fluid] as many times as you want, same mobs spawns all the time.

**Expected behaviour**: New mobs should spawn, like the small slimes

**Steps to reproduce the problem**:

1. Take quest [Basic Chemistry]
2. Use [Pustulant Spinal Fluid] on the Cauldron 
3. Stay there for a year

Check video how it should work out,
https://www.youtube.com/watch?v=sloYKs_sJpg

**Branch(es)**: Master

**AC hash/commit**:  e30ae1d4c329

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
tested and can confirm

**Comment by ghost1988** [comment]
Cooldown of Pustulant Spinal Fluid is too long then cauldron (or viceversa) and the cauldron reset

**Comment by starrheld** [comment]
Fix:
```SQL
UPDATE `item_template` SET `spellcooldown_1` = 30000 WHERE `entry` IN (44010);
```
