### ISSUE TITLE
(Windows 10) MeshExtractor Fails to build when compiled via Visual Studio 2019

### ISSUE THREAD

**Issue by FiftyTifty** [azerothcore/azerothcore-wotlk#3329]
**##### TITLE:**

MeshExtractor Fails to build when the **TOOLS** and **WITH_MESHEXTRACTOR** flags are enabled in CMake, when building on Windows 10.

**##### CURRENT BEHAVIOUR:**

When following the instructions on the AC wiki, as the tools are not provided, you are required to build them from AC's source after enabling the option in CMake. The compiler used is Visual Studio Community Edition 2017.

All the tools, except MeshExtractor, compile successfully.

**##### STEPS TO REPRODUCE THE PROBLEM:**

1. Download the latest AC repo via git
2. Follow the instructions on the Wiki posted here: https://www.azerothcore.org/wiki/Installation
3. When it comes to "Compiling on Windows", when configuring CMake, enable two flags: **TOOLS** and **WITH_MESHEXTRACTOR**.
4. After the build files have been generated, open **AzerothCore.sln**.
5. Building the solution via Visual Studio's menu **Build** -> **Build Solution** will only fail for **MeshExtractor.vcxproj**.

**##### EXTRA NOTES:**

27/09/20: The latest commit resolved the ACE errors, but now there are a multitude of new errors: https://pastebin.com/LZndMMjM

<details>
<summary>OLD</summary>
Here are the relevant lines from the build log: https://pastebin.com/KWCvwjhN
</details>

**##### AC HASH/COMMIT:**

<details>
<summary>As of 27/09/2020 the issue remains, but with different errors (no ACE errors now), with the following **git log** output:</summary>
The command **git log** outputs the following:
commit 91f4671d07b40a5316268bb4b2096dcd2bdf20d9 (HEAD -> master, origin/master, origin/HEAD)
Author: Stefano Borzì <stefanoborzi32@gmail.com>
Date:   Sun Sep 27 16:31:41 2020 +0200

    fix(Core/Spells): prevent client crash on use spell Neural Needle + ESC (#3383)

commit 1910b4ab35bf6ecc65f02df3e06cba4b6805318d
Author: Stefano Borzì <stefanoborzi32@gmail.com>
Date:   Sat Sep 26 14:46:27 2020 +0200

    chore(Core/Player): remove useless SendQuestComplete (#3380)

commit 8b3a1c1fe58488912f3d3b1a244664e7385b46a1
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Fri Sep 25 08:07:55 2020 +0000

    chore(DB): import pending SQL update file

    Referenced commit(s): fa29890a61717d70827a493ebde6ba7c3534cf5a

commit fa29890a61717d70827a493ebde6ba7c3534cf5a

</details>

<details>
<summary>As of 23/08/2020, **git log** outputs the following:</summary>
commit 27ed629ff5d49dee5e12e7564b52f232dda947b9 (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Sun Aug 16 11:26:33 2020 +0000

    Import pending SQL update file...

    Referenced commit(s): 8b9cec620d005db264baca9abb68c49167bdfabb

commit 8b9cec620d005db264baca9abb68c49167bdfabb
Author: Kitzunu <24550914+Kitzunu@users.noreply.github.com>
Date:   Sun Aug 16 13:25:26 2020 +0200

    refactor(Core/SpellInfo): Positive/Negative spells from SpellFamilyName into DB (#3149)

    * Implement SPELL_ATTR0_CU_POSITIVE_EFF0

    * Implement SPELL_ATTR0_CU_POSITIVE_EFF1

    * Implement SPELL_ATTR0_CU_POSITIVE_EFF2

    * Move SpellFamilyName spells into DB to define if they are POSITIVE or NEGA:
</details>

**##### OPERATING SYSTEM:**

Windows 10 LTSC 2019 x64 (Windows build 1809)

**##### MODULES:**

None

**##### OTHER CUSTOMIZATIONS:**

None

**Comment by Kitzunu** [comment]
I can confirm this on 78a02c8fd1f3d5a84e64787b9d46505541c6c3b2

**Comment by Kitzunu** [comment]
With these errors
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\MPQ.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\DoodadHandler.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\ChunkedData.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\ContinentBuilder.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ABORT': identifier not found	MeshExtractor	E:\azerothcore-wotlk\src\tools\mesh_extractor\MPQManager.cpp	67	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\Model.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\MeshExtractor.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\TileBuilder.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Error	C3861	 'ACELIB_ERROR': identifier not found (compiling source file E:\azerothcore-wotlk\src\tools\mesh_extractor\WorldModelHandler.cpp)	MeshExtractor	E:\azerothcore-wotlk\deps\acelite\ace\Event.h	60	
Warning	C4477	 'printf' : format string '%u' requires an argument of type 'unsigned int', but variadic argument 1 has type 'unsigned __int64'	MeshExtractor	E:\azerothcore-wotlk\src\tools\mesh_extractor\MeshExtractor.cpp	29	
```

**Comment by Viste** [comment]
try https://github.com/Viste/az-core/tree/rafex

**Comment by FiftyTifty** [comment]
> 
> 
> try #3351
> for linux works ok

That version outputs a large number of errors, warnings, and fails to build MeshExtractor. Whereas the original branch just fails to build MeshExtractor.

Error list log: https://pastebin.com/wr5qEYyG
Output log: https://pastebin.com/tp0dnyr2

**Comment by Viste** [comment]
> > try #3351
> > for linux works ok
> 
> That version outputs a large number of errors, warnings, and fails to build MeshExtractor. Whereas the original branch just fails to build MeshExtractor.
> 
> Error list log: https://pastebin.com/wr5qEYyG
> Output log: https://pastebin.com/tp0dnyr2

do you clean build folder? because there in no reference to ACElib in meshextractor but you have them in log ><

**Comment by FiftyTifty** [comment]
> 
> 
> do you clean build folder? because there in no reference to ACElib in meshextractor but you have them in log ><

Ah yeah, that was my bad. That removes the errors and warnings, but MeshExtractor still fails. Here's the Output log: https://pastebin.com/WRUgmPYA

**Comment by Viste** [comment]
oh that ace :/ its some headers or cmake insanity

**Comment by FiftyTifty** [comment]
> 
> 
> oh that ace :/ its some headers or cmake insanity

Been a few days, just wanted to say if there is any testing that would help, I'm up for doing it. Been itching to get AC all set up so I can start modding it.

**Comment by FiftyTifty** [comment]
Despite this being closed, the issue is still present in the latest master repository. The output log is the same, with MeshExtractor failing to build: https://pastebin.com/Cxjc5B4V

**Comment by Viste** [comment]
@FiftyTifty try https://github.com/azerothcore/azerothcore-wotlk/pull/3450 if this not help you need update VS to more fresh or w8 for full ACE remove.

**Comment by FiftyTifty** [comment]
> 
> 
> @FiftyTifty try #3450 if this not help you need update VS to more fresh or w8 for full ACE remove.

@Viste Did a fresh install of AC, and downloaded that PR by following the instructions here: https://www.azerothcore.org/wiki/How-to-test-a-PR

Unfortunately, that PR causes not just **MeshExtractor** to fail, but also **mmaps_generator**, **vmap4assembler**, **authserver**, and **worldserver**. CMake's log: https://pastebin.com/ZpExbQzf

The same happens when using VS 2019 as the CMake compiler and then compiling with VS 2019, instead of 2017.

**Comment by FrancescoBorzi** [comment]
According to @FiftyTifty , the faulty commit is https://github.com/azerothcore/azerothcore-wotlk/commit/8b9cec6

**Comment by FiftyTifty** [comment]
> 
> 
> According to @FiftyTifty , the faulty commit is [8b9cec6](https://github.com/azerothcore/azerothcore-wotlk/commit/8b9cec6) and it's still a bug

I'm going through all the past commits right now, and it's been a bug for a long time. I've checked the following commits so far:

<details>
Jul 25 2020 049299caf57cc9531c602f497b3705f0b3ed5c98

Jun 18 2020 34077115a5de7d640517caf8136f8648f8f195e3

May 25 2020 c50131faee1aebd7d05453f43203008e5f02f860

April 25 2020 fe1815d48b1ba899560b0715aa159752cdc95bac

Mar 25 2020 5ef98b95c932e6117b42e966677701b5543de757

Feb 25 2020 68698483647082aa0f0771ece3a7ff9d2def8203
</details>

**Comment by FrancescoBorzi** [comment]
@FiftyTifty what's important here is to find which commit broke it. So if at `N-1` it worked fine and at `N` it didn't, then `N` is the faulty commit.

**Comment by FiftyTifty** [comment]
> 
> 
> @FiftyTifty what's important here is to find which commit broke it. So if at `N-1` it worked fine and at `N` it didn't, then `N` is the faulty commit.

Yup, that's why I'm going back through all the commits. Just finished compiling (Jan 25 2019) 8c49cec40a50186bf90663676283867a829e1965, which also fails to compile MeshExtractor.

**Comment by FiftyTifty** [comment]
Update: The issue persists all the way through to **Dec 17 2018 (SSL Fix for Windows) 4a52df637574c24cc056e08a739c4001e56199eb**. Can't test any older commits due to a error with OpenSSL on Windows and AzerothCore, as CMake refuses to build with that error.

**Comment by shamage** [comment]
@FiftyTifty :

I did a basic compilation via Cmake - and here is the result:   [Pastebin](https://pastebin.com/t34sJtyk) . The compilation went well .

I compiled via Microsoft Visual Studio 2019 , everything went without errors. - and here is the result : [Pastebin2](https://pastebin.com/cD5Ax94z)

I compiled via VS with the listed MeshExtractor - and here is the result : [Pastebin3](https://pastebin.com/hERmVAKT)
All the compilations I did went well and without errors. It looks like you will have a problem with the settings or incorrect compilation.

**Comment by shamage** [comment]
AzerothCore revision            : 6ef28a8c4744 2020-09-28 12:15:51 +0000 (master branch)

**Comment by FiftyTifty** [comment]
@shamage That is really strange. Seeing that you have Boost installed, while the installation requirements don't mention it at all, I wonder if there are missing dependencies?

Just downloaded the latest master branch to double check, and it fails to build MeshExtractor as expected.

AzerothCore Revision: 6ef28a8
OpenSSL 1.1.1g  21 Apr 2020
MySQL 5.7.31.0
CMake 3.18.1
Windows 10 17763.1339

I'll try installing boost, see if that fixes it.

**Comment by Kitzunu** [comment]
We dont use Boost

**Comment by FiftyTifty** [comment]
Damn, thought we had something to go off there. I took another look at the log, and since the ACE stuff was revolved, there are a bunch of different errors being thrown. Too big to put in a spoiler, so here's the Pastebin: https://pastebin.com/LZndMMjM

I'll update the OP as well.

**Comment by Viste** [comment]
> Too big to put in a spoiler, so here's the Pastebin: https://pastebin.com/LZndMMjM

looks like bullshit in VS because for example
```
18>c:\servers\azerothcore\azerothcore\src\tools\mesh_extractor\Cache.h(36): error C3861: 'RETURN_GUAD': identifier not found (compiling source file C:\Servers\azerothcore\azerothcore\src\tools\mesh_extractor\DoodadHandler.cpp)
```
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/tools/mesh_extractor/Cache.h#L12
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/common/Threading/PolicyLock.h#L12
next
```
18>C:\Servers\azerothcore\azerothcore\src\tools\mesh_extractor\ContinentBuilder.cpp(183): error C2039: 'activate': is not a member of 'BuilderThread'
```
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/tools/mesh_extractor/ContinentBuilder.cpp#L13
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/tools/mesh_extractor/ContinentBuilder.cpp#L173-L183
you do something wrong man

**Comment by FiftyTifty** [comment]
I've also tried compiling AzerothCore, which has the same issue compiling MeshExtractor on Windows. Seeing how Shamage was able to successfully compile it, there must be something missing from the wiki's requirements section. As for what I've done, I've only followed the installation instructions to the letter.

**Comment by Viste** [comment]
> I've also tried compiling AzerothCore, which has the same issue compiling MeshExtractor on Windows. Seeing how Shamage was able to successfully compile it, there must be something missing from the wiki's requirements section. As for what I've done, I've only followed the installation instructions to the letter.
> 
> Edit: Literally posted right before you made that edit. I'll try that PR now and see if it compiles.
PR not complited.
MeshExtractor as i see fully broken because sunwell dont use it(on linux you even cant build mesh)

**Comment by Kitzunu** [comment]
I am renaming and confirming this VS 2019 as 2017 is not supported anymore
