### ISSUE TITLE
Normal/Heroic Dungeon - Ahn'Kahet, The Old Kingdom - Jedoga Shadowseeker encounter

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#333]
**Description**: Encounter not working properly

**Current behaviour**: Sometimes Twilight Volunteers will not spawn during her "in the air" phase

**Expected behaviour**: The mob Twilight Volunteers should spawn and walk slowly towards the boss, not be running like now...

**Steps to reproduce the problem**:

1. Start the encounter
2. Wait for the 2nd phase
3. The mob will bug, not sure if it's while in a group ONLY, when I tested it alone it worked fine

**Branch(es)**: Master

**AC hash/commit**:  e30ae1d4c329

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
@starrheld  does this happen all the time?

**Comment by starrheld** [comment]
Like I said, I tried it alone and nothing happened... but however when I did it in group with my friend it has happened two times, out of two tried. So 100 %

**Comment by talamortis** [comment]
![image](https://cloud.githubusercontent.com/assets/6143065/22183582/851b5c26-e0b9-11e6-98b0-3ec2113aa3f1.png)

Got it working, i think but need to to set speed of the creature

**Comment by starrheld** [comment]
Try it a few times, please try with friends if you are able to legit without any gm/dev tag

**Comment by starrheld** [comment]
Because alone it worked fine, but the speed is insane like you said

**Comment by talamortis** [comment]
@starrheld maybe i can send u the script and then u test with people?

**Comment by starrheld** [comment]
Yes you can if you want make a PR

**Comment by talamortis** [comment]
will do once i fixed the speed of the creatures, the boss is now making them go to her and not just being stunned.

**Comment by starrheld** [comment]
Tell me when!

**Comment by talamortis** [comment]
https://github.com/talamortis/azerothcore-wotlk/commit/89b0b7436b3c78e3cfb1975c8d04f4d603131d09 try that branch mate on my fork to change the speed on the NPC's just alter his speed_run in the database

**Comment by AgencyDev** [comment]
Also the Twilight Volunteers should come running in when you start the encounter.
They shouldn't just appear out of nowhere.

https://www.youtube.com/watch?v=PJm9t0uMqRM

**Comment by starrheld** [comment]
@talamortis Does anyone know how to grab your commit 89b0b7436b3c78e3cfb1975c8d04f4d603131d09 to my own fork? I'm such a git noob...

**Comment by talamortis** [comment]
just copy the whole code mate in raw

**Comment by starrheld** [comment]
@talamortis Alright, now the mobs run in to the boss and dies instantly without attacking it, also they still run too fast!

**Comment by starrheld** [comment]
@talamortis And as mentioned, the mobs should run towards the boss not just spawn there upon Pulling the boss, however that is not a major thing...

**Comment by talamortis** [comment]
i know they should run at the boss and not just spawn, try this SQL script and then test 

UPDATE `creature_template` SET `speed_walk` = "0.2", `speed_run` = "0.3" WHERE `entry` = "30114";

**Comment by starrheld** [comment]
Well, now the mobs before the boss runs really slow, and one human male still random pretty fast towards boss!

**Comment by talamortis** [comment]
i will check in the morning, it was justa  guess, maybe there are 2 types of creatures with the same name just different ID's

**Comment by starrheld** [comment]
Cool, tell me and I'll test it immediately so that we can commit.

**Comment by talamortis** [comment]
think i have fixed the speed problem just compiling and testing now
