### ISSUE TITLE
SKILL - SAP - ROGUE

### ISSUE THREAD

**Issue by merdlin** [azerothcore/azerothcore-wotlk#3332]
TITLE: SKILL - SAP - ROGUE 

CURRENT BEHAVIOUR: 
The bug of the rogue's skill has to be very close to the character to give SAP, if it is far it does not work.
https://wotlk.evowow.com/?spell=51724

EXPECTED BLIZZLIKE BEHAVIOUR:
The right thing would be for Skill to work from afar, in RANGE 5.

STEPS TO REPRODUCE THE PROBLEM:
1. Go stealth
2. Target a mob
3. Go to the furthest range you can sap
4. Use the command .dist when you target the mob to get the exact distance between you and the mob. In yards

##### AC HASH/COMMIT:
[master](https://github.com/azerothcore/azerothcore-wotlk/pull/3203)

OPERATING SYSTEM:
Windows Server 2016

MODULES:
mod-starter-guild, mod-cfbg

OTHER CUSTOMIZATIONS:
NO

**Comment by merdlin** [comment]
<!-- This template is for problem reports, for feature suggestion etc... feel free to edit it.
##### CURRENT BEHAVIOUR:
The bug of the rogue's skill has to be very close to the character to give SAP, if it is far it does not work.
https://wotlk.evowow.com/?spell=51724




##### EXPECTED BLIZZLIKE BEHAVIOUR:
The right thing would be for Skill to work from afar, in RANGE 5.



##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a character with the Rogue class.
2. Try to use the skill on a Mob from afar.

##### AC HASH/COMMIT:
[master](https://github.com/azerothcore/azerothcore-wotlk/pull/3203)



##### OPERATING SYSTEM:
Windows Server 2016



##### MODULES:
mod-starter-guild, mod-cfbg



##### OTHER CUSTOMIZATIONS:
NO

**Comment by merdlin** [comment]
WHY IS THIS BUG HAPPENING ??

I can not write.

**Comment by Kitzunu** [comment]
I will test this tomorrow.

How to test properly.

1. Go stealth
2. Target a mob
3. Go to the furthest range you can sap
4. Use the command .dist when you target the mob to get the exact distance between you and the mob. In yards

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/91067314-0b911700-e633-11ea-9301-8aac57ee18c8.png)

Works, it is at melee range aka 5 yards

**Comment by merdlin** [comment]
Wrong, right is by far. I tested it at blizzard and trinitycore has to be by far.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/91069124-57dd5680-e635-11ea-9244-fd68dd0f08fe.png)

**Comment by merdlin** [comment]
Where can I find the configuration for this skill? (.cpp)

**Comment by Kitzunu** [comment]
Don't reopen it. This is not a bug.
SpellWork (DBC) and in-game distance clearly shows that this spell has the correct distance.

And there is no such thing as "configuration" for spells, some are scripted, some are used right out of the dbc and this is one of them.
it works.

**Comment by merdlin** [comment]
If you think you are correct, no problem. But on my server I will correct it.

**Comment by merdlin** [comment]
The skill returned to work, azerothcore has some bugs an hour it works and nothing stops working.

**Comment by merdlin** [comment]
![image](https://user-images.githubusercontent.com/60373652/91075653-ccec6400-e614-11ea-89d1-322a9beb6112.png)

**Comment by Kitzunu** [comment]
Exactly, you are 6.9 yards away (More than 5yards) == You cannot use Sap
