### ISSUE TITLE
WoW Error Crash - Mirror Image - WOD Client 

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#3334]
WoW Error Crash - Mirror Image - WOD Client 

##### CURRENT BEHAVIOUR:

If you have the warmane client / a wotlk client with the WOD updated models you will crash when a mage does the following:

steps to reproduce:

1. mage use noggen fogger elixir (spell id 16591)
2. mage use mirror image
3. everyone around him with certain clients will crash

##### EXPECTED BLIZZLIKE BEHAVIOUR:

no crash.

##### STEPS TO REPRODUCE THE PROBLEM:

steps to reproduce:

1. mage use noggen fogger elixir (spell id 16591)
2. mage use mirror image
3. everyone around him with certain clients will crash

**Comment by Kitzunu** [comment]
If it is strictly due to custom clients and WOD models then this is not a core issue.

What you have to do is fix the client bug or use a clean client
