### ISSUE TITLE
Why azerothcore can not create Blood Elf and Draenei

### ISSUE THREAD

**Issue by yun000** [azerothcore/azerothcore-wotlk#334]
Why azerothcore can not create Blood Elf and Draenei?

It will prompt me to need the Burning Crusade

**Comment by talamortis** [comment]
Well update ur account info to wotlk

**Comment by talamortis** [comment]
in ur auth database go to account in there select what account u want, and then make exspansion to 2

**Comment by yun000** [comment]
yes my exspansion is 2 but can not create Blood Elf and Draenei

**Comment by talamortis** [comment]
try making a new account via console, then testing it

.account create (username) (password)

**Comment by yun000** [comment]
OK I have tested it and it is fine. But I found a new problem, Tauren can not create Paladin career

**Comment by talamortis** [comment]
that is correct, in 3.3.5 they was not able to be paladin

**Comment by yun000** [comment]
Thank you for my idiot question
