### ISSUE TITLE
An unknown crash occurred

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#3342]
I'm using the "azerothcore-wotlk" core, but I didn't completely follow all submissions

https://gist.github.com/boom8866/ec7068443cad07efc3895963eb81c4af

If you can help me, please contact me to leave a message

##### CURRENT BEHAVIOUR:

This collapse never happened until these two days

My core has been used for two years and has also followed some latest submissions 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It has been stable before

##### STEPS TO REPRODUCE THE PROBLEM:
Unknown

##### EXTRA NOTES:
no

##### AC HASH/COMMIT:
ubuntu 14.04
commit [987095e]
##### OPERATING SYSTEM:
ubuntu 14.04

**Comment by Kitzunu** [comment]
Use the latest master, v2.0.0 is not stable

**Comment by boom8866** [comment]
Just asking for some help, I added a lot of functions, and updating again requires a lot of follow-up.
