### ISSUE TITLE
(DB/Quest): Leave No One Behind

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3343]
https://www.wowhead.com/quest=11961/spirits-watch-over-us

**SMALL DESCRIPTION**:
the task is to bring in 2 minutes, otherwise it will die, I bring it in 45 seconds, it does not count after the expiration of time, the saved ones are running after you anyway trying to revive their other clones, so to speak, where they are lying around, so after that the army of these clones runs after you cancel the quest they will run away to random rooms plots and do not react even when their mobs hit

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 4f04af6+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by felwyn** [comment]
I dont quite understand the problem right here. But something is not right with this quest. You can save the first 2 Crusaders but when you try to save the last one you it wont recognize the event.

**Comment by LukasVolgger** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3656
