### ISSUE TITLE
(DB/Creature): Amanitar

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3344]
https://www.wowhead.com/npc=30258/amanitar

**SMALL DESCRIPTION**:
The problem is his ability https://www.wowhead.com/spell=57055/mini
When the battle begins, he grows mushrooms (poisonous and healthy) around and only then after a while he must throw the "mini" debuff, but he casts a debuff on everyone at once. The debuff cannot be removed by killing a healthy mushroom.

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 4f04af6+

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by peti446** [comment]
Can confirm this issue.

**Comment by peti446** [comment]
Found the issue doing a PR for it, it also seems that he does not cast the mini spell as much as he is required (every 30 seconds)

**Comment by sanctum32** [comment]
if interested, i'm doing some sort of AhnKahet rewrite, you may will find some useful stuff https://github.com/sanctum32/azerothcore-wotlk/tree/ahnkahet_revamp, currently improving Teldaram encounter
