### ISSUE TITLE
Visual bug in Warlock's Infernal

### ISSUE THREAD

**Issue by Flerex** [azerothcore/azerothcore-wotlk#335]
**Description**: When casting the Warlock spell _Infernal_, a ball of felfire should fall from the sky and then a Infernal should appear just in the middle of the area.

**Current behaviour**: The infernal is summoned just next to you at cast time.

**Expected behaviour**: The infernal should appear once the felball reaches the floor AND in the center of the area.

**Steps to reproduce the problem**:

1. Cast _Infernal_

**Branch(es)**: master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/e30ae1d4c329b8a203ed0d75b6eccccef30cba66

**Operating system**:  MacOS

**Modules**:  Nope

**Other Customizations**: Nope

**Comment by talamortis** [comment]
the problem is not the visual bug, its as the pet is summoned its react state is passive, so its going to come straight to the player.
