### ISSUE TITLE
Security Vulnerability (Fix included) [$200]

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#3352]
https://github.com/cmangos/issues/issues/1826
https://github.com/TrinityCore/TrinityCore/issues/25157
https://github.com/TrinityCore/TrinityCore/issues/22913
same shit here boys

**Comment by Si1ker** [comment]
https://www.youtube.com/watch?v=JAVDuzq3Jg0

**Comment by Viste** [comment]
@Si1ker its not only DB issue core also related :)

**Comment by asfo** [comment]
Fixed in TC:

**Comment by Viste** [comment]
> Fixed in TC:
> [TrinityCore/TrinityCore@bcdbdd6](https://github.com/TrinityCore/TrinityCore/commit/bcdbdd6f23ce65cc0e381e61d2840140dce79311)
@Helias  this is just remove sha not the fix in general lol, so no fix included. 
there must be more commits from TC :D for that lable

**Comment by Helias** [comment]
I know, but I see that TC has a EPIC issue about this, and we could follow it.

https://github.com/TrinityCore/TrinityCore/issues/25157

**Comment by asfo** [comment]
> > Fixed in TC:
> > [TrinityCore/TrinityCore@bcdbdd6](https://github.com/TrinityCore/TrinityCore/commit/bcdbdd6f23ce65cc0e381e61d2840140dce79311)
> 
> @Helias this is just remove sha not the fix in general lol, so no fix included.
> there must be more commits from TC :D for that lable
> also mangos fix this to :D

Its supposed that the issue came from the SRP6 which had a wrong implementation, removing the "sha_pass_hash" as the main issue said and deprecated it and using the proper SRP6 mitigates this issue.

Maybe I'm wrong. And if I'm, please, let me know how this is supposed to be fixed (just learning)

**Comment by Viste** [comment]
> > > Fixed in TC:
> > > [TrinityCore/TrinityCore@bcdbdd6](https://github.com/TrinityCore/TrinityCore/commit/bcdbdd6f23ce65cc0e381e61d2840140dce79311)
> > 
> > 
> > @Helias this is just remove sha not the fix in general lol, so no fix included.
> > there must be more commits from TC :D for that lable
> > also mangos fix this to :D
> 
> Its supposed that the issue came from the SRP6 which had a wrong implementation, removing the "sha_pass_hash" as the main issue said and deprecated it and using the proper SRP6 mitigates this issue.
> 
> Maybe I'm wrong. And if I'm, please, let me know how this is supposed to be fixed (just learning)

you right about spr6 and sha, but they do many commits for this and also cleanup they authserver so you must link more commits not just that :D

**Comment by Meltie2013** [comment]
@Viste @Helias 
Here's the full list of the PRs for the SRP6 methods.

https://github.com/TrinityCore/TrinityCore/pull/25093
https://github.com/TrinityCore/TrinityCore/pull/25131
https://github.com/TrinityCore/TrinityCore/pull/25135
https://github.com/TrinityCore/TrinityCore/pull/25138
https://github.com/TrinityCore/TrinityCore/pull/25156

**Comment by Winfidonarleyan** [comment]
Good, just good

**Comment by UltraNix** [comment]
Created PR with ported changes. Please, review it.
