### ISSUE TITLE
Location shows when new char is created

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3354]
##### CURRENT BEHAVIOUR:

When you create a new character it shows the location on the character select screen which isnt the normal behaviour. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If shouldnt show any location at all

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create a new character
2.  See the location

##### EXTRA NOTES:

The location doesnt show on TrinityCore. So it works there.

##### AC HASH/COMMIT:

d8ad0c520060280fe48fb9d73e2284cad241794d

##### OPERATING SYSTEM:

Windows 10 Enterprise (real activated version)

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Helias** [comment]
Confirmed.

Looking at the code responsible for this, I think that we need to change the way to create the `data` of the WorldPacket to fix this.
Like TC does using WriteBits() FlushBits() functions

**Comment by Helias** [comment]
nevermind, I've just found a way to fix it, let's test it https://github.com/azerothcore/azerothcore-wotlk/pull/3358

**Comment by felwyn** [comment]
Can be closed. Fix is working.

**Comment by Helias** [comment]
the issue will be closed when the PR will be merged
