### ISSUE TITLE
Quest #12849 bugged

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3356]
Quest "The Power of Blood, Forst And Unholy" is minorly bugged

##### CURRENT BEHAVIOUR:

It shows up as a ? when you have finished "Report To Scourge Commander Thalanor" (ID: 12850). In the text field it shows a gray ? icon instead of golden/yellow one.

You can complete the quest but the ? will stay above his head until you complete another quest or logout and login again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should show a ! in the first place and not a ? and that should go away after completing the quest.
A video link how it should be: https://www.youtube.com/watch?v=enJwUm1bOR4

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create a death knight
2.  Go through the Starting Zone until you completed the quest "The Might of the Scourge" and have received the quest "Report to Scourge Commander Thalanor"
3. Go to Lord Thorval and you will see him offering the quest with ? instead of a !
4. Finish the quest and the ? will stay

##### EXTRA NOTES:

I have no idea if this is working properly on TrinityCore.

##### AC HASH/COMMIT:

d8ad0c520060280fe48fb9d73e2284cad241794d

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Kitzunu** [comment]
If I remember I will check this when I get home today.
I've got my doubts, but I will check :)

**Comment by felwyn** [comment]
@Kitzunu Any news on this?

**Comment by Kitzunu** [comment]
I couldnt reproduce
