### ISSUE TITLE
Mobs stacking up

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3357]
Mobs stacking up.

##### CURRENT BEHAVIOUR:

2+ Mobs stacking up at one position. They are not spreading around the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should spread around the player and combat you from one angle only

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Pull 2+ Mobs at one time.
2.  Run away from them and let them form one unity.
3.  Fight!

##### EXTRA NOTES:

Works on Warmane but I guess that doesnt help at all.

Doesnt work on TrinityCore either.

##### AC HASH/COMMIT:

d8ad0c520060280fe48fb9d73e2284cad241794d

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by felwyn** [comment]
Works fine on CMaNGOS-WOTLK.

**Comment by felwyn** [comment]
It feels a bit to me there is an additional check going on on CMaNGOS. Like when the mob detects there is already 1 mob in front of the player, it will go a bit to the side and combat from there.

**Comment by FrancescoBorzi** [comment]
@felwyn can you please link the interested code on cmangos?

**Comment by felwyn** [comment]
No I have no idea about coding sadly :/ it was only an assumption.

**Comment by felwyn** [comment]
@FrancescoBorzi Hmm this could be interesting?
https://gist.github.com/Langerz82/1dbe4acec7fb6bbedf61fb4a44aeece3

**Comment by felwyn** [comment]
This fix is probably also helpful to fix combat position of your character. Because you can literally stand in the mob and attack him which is not very blizzlike. Mob should re-position at your position.

https://i.imgur.com/iMcNBPA.jpg
