### ISSUE TITLE
No suitable start date found for holiday XXX

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3360]
No suitable start date found for holiday XXX

##### CURRENT BEHAVIOUR:

When starting up worldserver.exe there are 6 Errors (? check if they are real errors by definition) talking about "no suitable start dates found for holidays XXX. 

Those holidays are the 6 from the Call to Arms events.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I guess there shouldnt be any error message.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Well just start-up worldserver.exe
2.  Scroll up until you see the errors.

##### EXTRA NOTES:

Works on every other platform I Have used (CMaNGOS, TC and Warmane and such)

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d8ad0c520060280fe48fb9d73e2284cad241794d

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Kitzunu** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5b4287e6832da32539a49e68f6a5ab0ee55854b3
