### ISSUE TITLE
IF Mountaineer half-glitching

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3363]
IF Mountaineer half-glitching through wall

##### CURRENT BEHAVIOUR:

Female IF Mountaineer patrolling around Anvilmar is half-glitching through the wall when she walk towards the exit of Anvilmar.

https://i.imgur.com/KxZsWq7.jpg https://i.imgur.com/z0JXJEa.jpg https://i.imgur.com/R4Oeqrt.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Well she shouldnt half-glitch through the wall

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Create a dwarf 
2. Walk to Anvilmar and then left entrance and wait for "her" to pass by
3.  You will see that she glitches through the wall but continues walking

##### EXTRA NOTES:

No

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/041a508a50e366ac7a826aa46b96107719e23944

##### OPERATING SYSTEM:

Windows 100

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Helias** [comment]
can you provide the guid of the NPC?

**Comment by felwyn** [comment]
GUID of the NPC is 1021
