### ISSUE TITLE
Quest Bug: Reconnaissance Flight

### ISSUE THREAD

**Issue by Mamaro89** [azerothcore/azerothcore-wotlk#3367]
Bug on Quest: Reconnaissance Flight

##### CURRENT BEHAVIOUR:
It just doesnt work.  It does not summon any plain as suposed

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This is how it should work:
https://www.youtube.com/watch?v=aw-Eugwg7eI
When you accept the quest, it does not bring the airplane, it does nothing.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Sholazar Basin, on NPC Pilot Vic and get the quest An Embarrassing Incident
2. Once completed you get this quest Reconnaissance Flight.
3. It was suposed to sumon and aircraft, but ir does not.

##### AC HASH/COMMIT:

commit f4953cc13b3c986b703e9ebc95fd82aaf385ef24

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

individual-xp
mod_boss_announcer
mod_congratsonlevel
mod_gmisland
mod_leadspells
mod_LuaEngine
modarenatop
transmog

##### OTHER CUSTOMIZATIONS:

nothing.

**Comment by felwyn** [comment]
I am sorry cant confirm. Quest works like a charm.

https://i.imgur.com/AVjW5c5.jpg

**Comment by FrancescoBorzi** [comment]
thanks @felwyn 

if anyone can reproduce this, we will reopen
