### ISSUE TITLE
HELP! compile error

### ISSUE THREAD

**Issue by heijing-iw7** [azerothcore/azerothcore-wotlk#3370]
I am newbie to azerothcore, have followed the instructions in traditional way. I got cmake configure/generation right, but I got compile errors in vs. I post the cmake log and compile errors below. PLS help me, I have searched in web to get more answers, I have tried 3 versions of openssl. did not work.

CMAKE log:
The C compiler identification is MSVC 19.16.27041.0
The CXX compiler identification is MSVC 19.16.27041.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++17 support
Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
cotire 1.8.0 loaded.
Found MySQL library: E:/sw/mysql-5.7.31-winx64/lib/libmysql.lib
Found MySQL headers: E:/sw/mysql-5.7.31-winx64/include
Found git binary : C:/Program Files/Git/cmd/git.exe

* AzerothCore revision            : 8c144458e5bf+ 2020-08-28 14:10:15 +0000 (master branch)

* Install core to                 : C:/Program Files (x86)/AzerothCore
* Install configs to              : C:/Program Files (x86)/AzerothCore

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (default)
* Build map/vmap tools            : No  (default)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable extra features           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Enable extra logging functions  : No (default)
* Show source tree                : Yes - "hierarchical"

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
C CXX target ace cotired without unity build excluding Atomic_Op_Sparc.c, Rtems_init.c.
Looking for open
Looking for open - found
Looking for _strtod_l
Looking for _strtod_l - found
begin detect openssl
Found OpenSSL: optimized;E:/sw/OpenSSL-Win64-1_0_2q/lib/VC/ssleay32MD.lib;E:/sw/OpenSSL-Win64-1_0_2q/lib/VC/libeay32MD.lib;debug;E:/sw/OpenSSL-Win64-1_0_2q/lib/VC/ssleay32MDd.lib;E:/sw/OpenSSL-Win64-1_0_2q/lib/VC/libeay32MDd.lib  
CXX target common cotired without unity build.
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
CXX target game cotired without unity build.
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
CXX RC target authserver cotired without unity build.
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE

CXX target scripts cotired without unity build.
CXX RC target worldserver cotired without unity build.
Running cmake hook: AFTER_WORLDSERVER_CMAKE
No hooks registered for AFTER_WORLDSERVER_CMAKE
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done

Below is compile erros in vs:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4819	The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	1	
Error (active)	E1866	attribute does not apply to any entity	fmt	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\deps\fmt\fmt\core.h	477	
Error (active)	E1866	attribute does not apply to any entity	fmt	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\deps\fmt\fmt\core.h	478	
Error (active)	E1866	attribute does not apply to any entity	fmt	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\deps\fmt\fmt\format.h	2592	
Error (active)	E1866	attribute does not apply to any entity	fmt	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\deps\fmt\fmt\format.h	2593	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	103	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	104	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	104	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	104	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	105	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	105	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	107	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	108	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	108	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	108	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	109	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	109	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	111	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	112	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	112	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	112	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	113	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	113	
Error	C2001	newline in constant	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	113	
Error	C2143	syntax error: missing ')' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	114	
Error	C2143	syntax error: missing ';' before 'Log::instance'	authserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\authserver\Main.cpp	114	
Warning	C4819	The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss	game	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\game\Entities\Creature\CreatureGroups.cpp	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	scripts	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-build\src\server\scripts\zone_alterac_mountains.obj	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	scripts	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-build\src\server\scripts\zone_burning_steppes.obj	1	
Warning	C4819	The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	1	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	124	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	125	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	125	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	125	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	126	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	126	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	128	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	129	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	129	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	129	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	130	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	130	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	132	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	133	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	133	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	133	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	134	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	134	
Error	C2001	newline in constant	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	134	
Error	C2143	syntax error: missing ')' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	135	
Error	C2143	syntax error: missing ';' before 'Log::instance'	worldserver	E:\iw7.private.svn\worlds\wow\AzerothCore\azerothcore-wotlk-git.working\src\server\worldserver\Master.cpp	135

**Comment by FrancescoBorzi** [comment]
hi, welcome to AzerothCore. Please read: https://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by heijing-iw7** [comment]
> hi, welcome to AzerothCore. Please read: https://www.azerothcore.org/wiki/How-to-ask-for-help

so basicly I should report this in stackoverlow, that's ok, but I am wonderring how my post there can get enough attention especially from offical support like from you guys..
Anyway I will post there soon

**Comment by FrancescoBorzi** [comment]
@heijing-iw7 because this is the bugtracker and we get bug reports here. We don't want to mix bugs and support requests, otherwise it becomes too messy :)

I hope you understand

**Comment by heijing-iw7** [comment]
> @heijing-iw7 because this is the bugtracker and we get bug reports here. We don't want to mix bugs and support requests, otherwise it becomes too messy :)
> 
> I hope you understand

I have posted in stackoverflow:https://stackoverflow.com/questions/63649642/compile-errors-in-azerothcore-on-windows-10
after one day long there's 0 reply.. Could you pls help me there?

**Comment by Kitzunu** [comment]
If I should be honest I have no idea what your issue could be.

Windows build works fine for me

**Comment by wsw0108** [comment]
BOM things!

https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom
