### ISSUE TITLE
Mana-Tombs: Hidden Ethereal Priest

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3371]
##### CURRENT BEHAVIOUR:

After killing Ethereal Priest, near by mobs are still getting Power Word: shield

![image](https://user-images.githubusercontent.com/4015312/91628894-06a4ce00-e979-11ea-81dd-dd4650135807.png)
![image](https://user-images.githubusercontent.com/4015312/91628900-14f2ea00-e979-11ea-8990-34d38e449674.png)
![image](https://user-images.githubusercontent.com/4015312/91628904-1c19f800-e979-11ea-8cd9-5574d06146d7.png)
![image](https://user-images.githubusercontent.com/4015312/91628908-2805ba00-e979-11ea-9b5e-3e25db03eb70.png)
![image](https://user-images.githubusercontent.com/4015312/91628909-305df500-e979-11ea-80a7-8b444170954a.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

mobs should not get Power Word: shield after the near by Ethereal Priest is killed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. run mana-tombs and see if mobs still get Power Word: shield after killing the near by Ethereal Priest. (see gps info in screenshot)

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/a6a7cbf887915b7441de19db38dfceff2a9bb182

##### OPERATING SYSTEM:

Centos 7

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

**Comment by Hacaw** [comment]
I cannot reproduce this issue.
I let the mobs attacking me for 5 minutes and they didn't get another buff.

TESTING
---
1. .go c id 18317
2. .die on the Etheral Priest
3. observe the near mobs

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by locus313** [comment]
Thanks @Hacaw. I will recheck this  on the latest commit to confirm I no longer see this issue.

**Comment by locus313** [comment]
Retested I am still able to reproduce this issue:
![image](https://user-images.githubusercontent.com/4015312/101542064-1d36ca00-3957-11eb-83b8-b0d6409cbbb6.png)

This was tested with commit https://github.com/azerothcore/azerothcore-wotlk/commit/1b156ef7ebb77b60f630f3951884ec2c07009c29

It seems in the hallway between two of the rooms is where I see it mainly happening. Try using .go c 91239

**Comment by wizzymore** [comment]
Confirming this.

What happens is that the nearby priests that are not in combat are casting the shields.
