### ISSUE TITLE
Weird rhino placement

### ISSUE THREAD

**Issue by felwyn** [azerothcore/azerothcore-wotlk#3372]
Weird rhino placement

##### CURRENT BEHAVIOUR:

Rhino are placed too crowded. I dont know if this was blizzlike behaviour back in the original days but it seems weird to me.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Probably make their place a bit less crowded.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .tel StormPeaks
2.  The Rhinos should be very near where you have teleported
3. 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/33613254351f7715afbd5adc5186a1e45853083a

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Helias** [comment]
How they should be?
I don't think is so bad.
![image](https://user-images.githubusercontent.com/519778/91640527-7c16aa00-ea1e-11ea-80d6-004b5c0d424c.png)


I think we can close this

**Comment by felwyn** [comment]
True. Can it be true that those rhinos are being held kept by those giants? When you enable gm mode you can see them surrounding those rhinos.

**Comment by Helias** [comment]
no giant, the giants are in another phase, to get the phase of the giant, click on it and use `.npc info` and read the phasemask, same for the rhinos.

I am closing this issue ;-)
