### ISSUE TITLE
Berserker Stance - Critical hit chance stacks one more time after reload

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#3386]
##### CURRENT BEHAVIOUR:
When a warrior uses Berserker Stance, critical chance is increased 3% as usual, but after reload, it seems to be increased twice.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
IT should not stack twice times.

##### STEPS TO REPRODUCE THE PROBLEM:

Before casting Berserker Stance
![image](https://user-images.githubusercontent.com/15328758/91672940-b2911980-eb31-11ea-9ccd-a5d1c21a1e60.png)
After casting Berserker Stance
![image](https://user-images.githubusercontent.com/15328758/91672979-f3892e00-eb31-11ea-87b0-c7223e00d8af.png)
After logout and login
![image](https://user-images.githubusercontent.com/15328758/91672992-026fe080-eb32-11ea-8a36-d5a4701a8bbd.png)

##### OPERATING SYSTEM:
Ubuntu 16

##### AC/HASH COMMIT
[a1a726f](https://github.com/azerothcore/azerothcore-wotlk/commit/a6a7cbf887915b7441de19db38dfceff2a9bb182)

**Comment by FrancescoBorzi** [comment]
missing AC commit hash

**Comment by mnclaras** [comment]
> missing AC commit hash

Done!

**Comment by r0m1ntik94** [comment]
@mnclaras can't confirm on [8b3a1c1](https://github.com/azerothcore/azerothcore-wotlk/commit/8b3a1c1fe58488912f3d3b1a244664e7385b46a1)

**Comment by FrancescoBorzi** [comment]
@mnclaras can you please update your server to the latest AC version and try again?

**Comment by mnclaras** [comment]
> @mnclaras can you please update your server to the latest AC version and try again?

I did it but the bug continues. I'm on [1910b4a ](https://github.com/azerothcore/azerothcore-wotlk/commit/91f4671d07b40a5316268bb4b2096dcd2bdf20d9).

Also updated dbc/maps/mmaps/vmaps to [latest version](https://github.com/wowgaming/client-data/releases), which is from 13 August 2019.

¿Can it be related to database events/scripts? Just do this rotation:
Battle Stance (view % Critical Strike) -> Berserker Stance (it applies +5% Critical Strike) -> Logout -> Login -> It applies (+5% Critical Strike) -> Battle Stance (Critical Strike is reduced by 10%).
