### ISSUE TITLE
[Spell/Glyph] Glyph of Molten Armor losing bonus on relog

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#3387]
##### CURRENT BEHAVIOUR:
Fire Mage.
[Glyph of Molten Armor](https://www.wow-mania.com/armory/?item=42751) is losing its effect on relog.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should not lose effect on relog.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Without glyph and Molten Armor buff
![image](https://user-images.githubusercontent.com/15328758/91673219-5b8c4400-eb33-11ea-8509-46f06c68e950.png)
2. Put Glyph and cast Molten Armor (BEFORE LOGOUT)
![image](https://user-images.githubusercontent.com/15328758/91673245-79f23f80-eb33-11ea-89f1-df2fd6fdc6ec.png)
3. Do a relog and check
![image](https://user-images.githubusercontent.com/15328758/91673250-86769800-eb33-11ea-92d9-cdcd341c22bf.png)

##### AC/HASH COMMIT
[a1a726f](https://github.com/azerothcore/azerothcore-wotlk/commit/a6a7cbf887915b7441de19db38dfceff2a9bb182)

**Comment by FrancescoBorzi** [comment]
missing AC commit hash

**Comment by mnclaras** [comment]
> missing AC commit hash

Done!

**Comment by Remberance** [comment]
its after cast molten armor with glyph, 29.xx%, relog, 27.xx%

**Comment by r0m1ntik94** [comment]
Confirm for all symbols that give bonuses to buffs, for example:
Paladin [Glyph of Seal of Vengeance](https://wowroad.info/?item=43869)

**Comment by lineagedr** [comment]
Moving this https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L18356
Above:
_LoadAuras(holder->GetPreparedResult(PLAYER_LOGIN_QUERY_LOAD_AURAS), time_diff);

Solves the issue

**Comment by FrancescoBorzi** [comment]
@lineagedr thanks for your solution, could you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it?

**Comment by mnclaras** [comment]
@lineagedr There is another bug, where if you change the talent tree, the bonus is applied until you renew it. I'll open a bug.
