### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by XevL** [azerothcore/azerothcore-wotlk#339]
**Description**:
Hi, i don't know what i did wrong but i'm getting an error when trying to compile on windows.
I did check advance on cmake i have:
OpenSSL_INCLUDE_DIR: C:/OpenSSL-Win64/include
OPENSSL_ROOT_DIR: C:/OpenSSL-Win64
All requirements installed
Visual Studio 14 ( 2015 update 3 Desktop Community )
Cmake 3.6.3
Git 2.11.0.3 64-bit
Mysql 5.5.54 64-bit
Win64 OpenSSL v1.1.0c

Can someone help me please.

**Current behaviour**: Tell us what happens
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  modules/worldengine/nucleus/src/cmake/macros/FindOpenSSL.cmake:175 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
Win 7 64-bit
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by XevL** [comment]
fixed with older version of OpenSSL.

**Comment by kasumiru** [comment]
I have same problem. 
Then I press configure button, I see:
Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES)
FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
cmake/macros/FindOpenSSL.cmake:175 (find_package_handle_standard_args)

Variables:
Win 7, Openssl 1.1.1 ver, 
%PATH%=C:\CMake\bin;C:\Windows\system32;C:\Windows;C:\CMake\bin;C:\openssl-win64\bin
OPENSSL_FOUND=C:\openssl-win64
OPENSSL_INCLUDE_DIR=C:\openssl-win64\include
OPENSSL_LIBRARIES=C:\openssl-win64\lib
OPENSSL_ROOT_DIR=C:\openssl-win64
cmake 3.13-rc2 ver.

**Comment by poszer** [comment]
@kasumiru  Check this please [OpenSSL 1.1 on windows](https://github.com/azerothcore/azerothcore-wotlk/pull/1065)

**Comment by BarbzYHOOL** [comment]
@kasumiru and once you have tested, please tell us if it works or not!

**Comment by kasumiru** [comment]
Thank you! After this patch [https://github.com/azerothcore/azerothcore-wotlk/pull/1065](url) I can "configure" and "generate" azerothcore.
But after that, in other program MVS 15, I see many another errors: 
```
    AuthSocket.obj : error LNK2019: unresolved external symbol;
    Done building project "worldserver.vcxproj" -- FAILED;
    shared.lib(HMACSHA1.obj) : error LNK2019: unresolved external symbol _HMAC_CTX_cleanup;
    shared.lib(QueryResult.obj) : error LNK2019: unresolved external symbol 
```
and many similar errors.
