### ISSUE TITLE
Unknown column QuestInfoID in field list

### ISSUE THREAD

**Issue by oneohthree** [azerothcore/azerothcore-wotlk#340]
**Description**: 

This was a fresh install, both OS and AzerothCore. I followed **all steps** described in [Installation](https://github.com/AzerothCore/azerothcore-wotlk/wiki/Installation), then  when I run worldserver the system throws this error:

```
ERROR: [1054] Unknown column 'QuestInfoID' in 'field list'
Your Database structure is not up to date. Please make sure you've executed all queries in the sql/update folders.
Aborted
```

I used .sql files generated by `db_assembler`.

If I execute the queries `azerothcore/data/sql/updates/pending_db_world` the server runs without issues.

**Steps to reproduce the problem**:

1. Run ./worldserver from /bin directory

**Branch(es)**: master 

**Operating system**:  Debian 8.7 64bits

**Comment by Inifield** [comment]
Apply SQL in pending_world

**Comment by oneohthree** [comment]
I did what you suggest before reporting this. But I think this should be reflected on the Wiki.

**Comment by talamortis** [comment]
did the sql files work in the pending folder?

**Comment by oneohthree** [comment]
Yes, they did. As I said before, I ran grep to find out related files and I realized the pendind folder has this updates, so I use just two of them (the ones which have ''QuestInfoID" and "TimeAllow"). This: `rev_1482952611662394924.sql` and this: `rev_1482409122200235830.sql`.
