### ISSUE TITLE
[NPC][WOTLK] Brittle Revenant - Missing Random MovementType + Low Droprate

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#342]
**Description**: Wrong MovementType

**Current behaviour**: Standing still 

**Expected behaviour**: MovementType 1 like Seething Revenant

**Steps to reproduce the problem**:

1. Go to Frostfield Lake
2. Check them out and check out Seething Revenant
3. Can be seen here that they should move 

https://www.youtube.com/watch?v=Kgf0tslmPWM

**Branch(es)**: Master

**AC hash/commit**:  b2c3330095bf

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by starrheld** [comment]
Possible fix:

```sql
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976006";
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976007";
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976008";
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976009";
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976010";
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976011";
UPDATE `creature` SET `MovementType` = "1" WHERE `guid` = "1976012";
```

**Comment by ShinDarth** [comment]
@starrheld 

better code format:

``UPDATE `creature` SET `MovementType` = "1" WHERE `guid` IN (1976006, 1976007, ........ );``

**Comment by starrheld** [comment]
@ShinDarth Thanks for the tip, not very savy in this world ;)

**Comment by Rushor** [comment]
you need to set `spawndist` too

better:  
```sql
UPDATE `creature` SET `spawndist`=10, `MovementType`=1 WHERE  `id`=30160;
```

**Comment by talamortis** [comment]
please open a PR, thanks.
