### ISSUE TITLE
ICC Intro Event - Saurfang/Muradin

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#3422]
##### CURRENT BEHAVIOUR:
Saurfang and Muradin show dialog to start Deathbringer Saurfang event.  Tirion doesn't initiate intro event after killing the two The Damned at the beginning of the instance.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When you kill the two The Damned at the door, the intro event should start.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Enter ICC (any difficulty, on alliance or horde characters)
2. Kill the two The Damned
3.  No intro event.

##### EXTRA NOTES:
I believe this broke when #3294 was merged - original bug report was to de-spawn the NPCs after the event, but instead the event does not start at all.

#3261 was also merged to correct Saurfangs model.  Unsure if related.

##### AC HASH/COMMIT:
2632cd6fcd8b

##### OPERATING SYSTEM:
Win10

##### MODULES:
N/A

##### OTHER CUSTOMIZATIONS:
N/A

**Comment by Winfidonarleyan** [comment]
need fix
```
NPC_HIGH_OVERLORD_SAURFANG_DUMMY            = 32315,
``

**Comment by Shadofiend** [comment]
confirm

**Comment by Akimboss** [comment]
I called this error, but no one listened :D, this error caused by the query you added here Core/DB fix Icecrown Citadel Raid - Saurfang Intro Roleplay (#3261) ( this query UPDATE `creature` SET `id` = 37187 WHERE `id` = 32315; ) how can you replace the ID with another ID ? with all my respect that's just dumb ... the ID should be ModelID not ID of NPC, in general without talking too much revert the query and the event will work fine and for the model, just update the model to 30583 which is the modelID of Saurfang ... you can either do this by database or ingame by going to npc and use ! .Npc set model 30583, and it's fixed forever for event and model, please test before future merge ...

**Comment by Voxstrasza** [comment]
> 
> 
> I called this error, but no one listened :D, this error caused by the query you added here Core/DB fix Icecrown Citadel Raid - Saurfang Intro Roleplay (#3261) ( this query UPDATE `creature` SET `id` = 37187 WHERE `id` = 32315; ) how can you replace the ID with another ID ? with all my respect that's just dumb ... the ID should be ModelID not ID of NPC, in general without talking too much revert the query and the event will work fine and for the model, just update the model to 30583 which is the modelID of Saurfang ... you can either do this by database or ingame by going to npc and use ! .Npc set model 30583, and it's fixed forever for event and model, please test before future merge ...

I have no idea what you just said.

**Comment by peti446** [comment]
This is correct with @Akimboss changes it triggers as expected. The model should be changed not the ID as the script is dependend on it.
`UPDATE `acore_world`.`creature` SET `id` = '32315', `modelid` = '30583' WHERE (`guid` = '200984');`

**Comment by Akimboss** [comment]
> > I called this error, but no one listened :D, this error caused by the query you added here Core/DB fix Icecrown Citadel Raid - Saurfang Intro Roleplay (#3261) ( this query UPDATE `creature` SET `id` = 37187 WHERE `id` = 32315; ) how can you replace the ID with another ID ? with all my respect that's just dumb ... the ID should be ModelID not ID of NPC, in general without talking too much revert the query and the event will work fine and for the model, just update the model to 30583 which is the modelID of Saurfang ... you can either do this by database or ingame by going to npc and use ! .Npc set model 30583, and it's fixed forever for event and model, please test before future merge ...
> 
> I have no idea what you just said.

Well, i explained the reason for this bug, and the solution inside what i said or just copy peti query

**Comment by Voxstrasza** [comment]
> 
> 
> This is correct with @Akimboss changes it triggers as expected. The model should be changed not the ID as the script is dependend on it.
> `UPDATE 'creature' SET 'id' = '32315', 'modelid' = '30583' WHERE ('guid' = '200984');`

Oh, I see - it was #3261 that broke the script.  I'll test this query out.

**Comment by peti446** [comment]
@Akimboss Are you working on a PR for this, if not I could quickly create one for this.

**Comment by Voxstrasza** [comment]
Not really sure how to create a PR, but here is what I just did to fix everything

` UPDATE `creature` SET `id` = 32315 WHERE `id` = 37187;

INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES
(32315, 0, 0, 0, 0, 0, 30583, 0, 0, 0, 'High Overlord Saurfang', '', '', 0, 80, 80, 2, 1735, 0, 1, 1.14286, 1, 3, 2, 2, 0, 24, 7.5, 2000, 2000, 1, 0, 2048, 0, 0, 0, 0, 0, 0, 1, 1, 0, 7, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 200, 1, 1, 0, 199, 1, 0, 0, '', 12340);`

Also, I fixed Tirion's text when the two The Damned die:

`UPDATE `acore_world`.`broadcast_text` SET `MaleText`='This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people.' WHERE  `ID`=36923;
SELECT `ID`, `Language`, `MaleText`, `FemaleText`, `EmoteID0`, `EmoteID1`, `EmoteID2`, `EmoteDelay0`, `EmoteDelay1`, `EmoteDelay2`, `SoundId`, `Unk1`, `Unk2`, `VerifiedBuild` FROM `acore_world`.`broadcast_text` WHERE  `ID`=36923;`

**Comment by peti446** [comment]
> Not really sure how to create a PR, but here is what I just did to fix everything
> 
> `UPDATE`creature`SET`id`= 32315 WHERE`id` = 37187;`
> `
@Voxstrasza  I would not update all to 32315 as Saurfang after the ship battle needs to use 37187 I think to be able to start the fight. Not really sure if we really need a creature_template for the specific caracter tbh but I am not a db expert :)

Here is some info to create PR in the mean time: https://www.azerothcore.org/wiki/How-to-create-a-PR
If not, I will be able to open a PR tomorrow late evening and test you proposed changes.

**Comment by Voxstrasza** [comment]
This does not interfere with Gunship.

**Comment by Akimboss** [comment]
> @Akimboss Are you working on a PR for this, if not I could quickly create one for this.

Well you can use the query or command INGAME, it's up to you, for IG command NPC set model 30583 and that's it without messy people head

**Comment by Akimboss** [comment]
> > Not really sure how to create a PR, but here is what I just did to fix everything
> > `UPDATE`creature`SET`id`= 32315 WHERE`id` = 37187;`
> 
> @Voxstrasza I would not update all to 32315 as Saurfang after the ship battle needs to use 37187 I think to be able to start the fight. Not really sure if we really need a creature_template for the specific caracter tbh but I am not a db expert :)
> 
> Here is some info to create PR in the mean time: https://www.azerothcore.org/wiki/How-to-create-a-PR
> If not, I will be able to open a PR tomorrow late evening and test you proposed changes.

i'll create PR for you tomorrow

**Comment by Remberance** [comment]
UPDATE `creature_template` SET `modelid1`='30583' WHERE (`entry`='32315');
when i used this SQL, the model is right, and the intro event worked!

**Comment by Voxstrasza** [comment]
Closing as it was fixed by a few PRs
