### ISSUE TITLE
Help Compile

### ISSUE THREAD

**Issue by kekstm98** [azerothcore/azerothcore-wotlk#3424]
When compiling the source code, an error occurs(in the photo)
[https://d.radikal.ru/d17/2009/f1/15f3d81b7975.jpg
](url)How do I fix it and where do I set the value?
![bandicam 2020-08-31 22-31-58-830](https://user-images.githubusercontent.com/63323520/91998772-518d5f80-ed44-11ea-9b8a-a99a8a0a34a1.jpg)

**Comment by FrancescoBorzi** [comment]
Hello, this is the bugtracker and should not be used for support requests.

Please read this and we'll be glad to help you:

https://www.azerothcore.org/wiki/How-to-ask-for-help
