### ISSUE TITLE
[NPC][WotlK] Heldgarr Steelbeard - Unable to cast shoot

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#343]
Thanks to @Rushor!
----------------------

http://www.wowhead.com/npc=25281/heldgarr-steelbeard

should be able to cast shoot (see wowhead screenshot rev.)
http://www.wowhead.com/spell=45425/shoot (Effect: Dummy, Server-side script)

http://www.wowhead.com/npc=25281/heldgarr-steelbeard#screenshots:id=282675

![Image of Heldgarr](https://cloud.githubusercontent.com/assets/4903600/22222928/3a3c2554-e1b9-11e6-93b7-5f7760aebfc8.jpg)

**Comment by starrheld** [comment]
Fix:

```sql
DELETE FROM `disables` WHERE `entry`= 45425;
INSERT INTO `disables` (`sourceType`,`entry`,`flags`,`params_0`,`params_1`,`comment`) VALUES
(0, 45425, 64, '', '', 'Ignore LOS for Shoot (Dummy)');
```

**Comment by ShinDarth** [comment]
@starrheld 

please [open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) to submit fixes

**Comment by Rushor** [comment]
my fix lol https://github.com/TrinityCore/TrinityCore/issues/18937

**Comment by starrheld** [comment]
@Rushor Sorry forgot, edited :dagger:
