### ISSUE TITLE
Target not in line of sight bug

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3431]
^
Target not in line of sight bug

##### CURRENT BEHAVIOUR:

When I try to attack a target which is not in line of sight with a ranged weapon. I get this incredible annoying "Aim sound" multiple times. It only goes away when I get in line of sight with the target.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You shouldnt be able to get in gun target mode at all when you are not in side.

This behaviour doesnt happen on Warmane.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Take a gun 
2.  Target a mob which is not in line of sight.
3.  Et voila.

##### EXTRA NOTES:

No

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/03bd4fafe65d7662b0b1fd3e1614b32b20da40ca

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by craftorix** [comment]
UPDATE:

This only applies when using ranged weapons. When using ranged mage spells or equally it works fine.
