### ISSUE TITLE
Drink and Eat Animations are no consistent/continuous

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3434]
Drink and Eat Animations are not consistent or continued

##### CURRENT BEHAVIOUR:

When eating or drinking stuff. It will only play the initial drink/eat animations when you sit down but it wont play the other continued animations.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The character should have the eat and drink animations for the time the item is consumed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get yourself something to drink or eat.
2. Drink/Eat it.
3. You will see that the character will only do the first animation and then do nothing just sitting.

##### EXTRA NOTES:

Cant tell but works on Warmane.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/8908df6b8040cb849731a68d71bc8fcfbaaf3b0a

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Meltie2013** [comment]
The source is missing some code to make it work correctly.

Reference Pull Request: https://github.com/TrinityCore/TrinityCore/pull/21280/files

**Comment by FrancescoBorzi** [comment]
@Meltie2013 thanks for that link. You can also [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it. Don't forget to mention the original author.

**Comment by Helias** [comment]
@Meltie2013, can yuo make a PR? so the people can test it easily and comment with their feedback there?

Anyways, thank you :+1:

**Comment by FrancescoBorzi** [comment]
@Meltie2013 thanks for your fix, you can check this to know how to open a PR: https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by Meltie2013** [comment]
I would love to open a PR for you guys but currently on the road, so internet isn't good for downloading and uploading.
I'll see when I can make that PR.

**Comment by Viste** [comment]
Congratulations, you finally found Easter egg from me, which proves that the current test system has shit itself again.
and sorry for this )

**Comment by Viste** [comment]
funny but https://github.com/azerothcore/azerothcore-wotlk/commit/03bfbf4f7e43f6b8064e6846e0bf2503958c17bc#diff-4522eeffcbc961602e86620011a2d579R17511 when this make false again is magic i look all history from that commit to now and don't see any commints that make this to false :D

**Comment by Kitzunu** [comment]
Becasue it is
https://github.com/azerothcore/azerothcore-wotlk/blob/03bfbf4f7e43f6b8064e6846e0bf2503958c17bc/src/server/game/Entities/Unit/Unit.cpp#L17498-L17504
