### ISSUE TITLE
Patrolling Horde Elites are in a wrong position

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3438]
Patrolling Horse Elites are in a wrong position

##### CURRENT BEHAVIOUR:

These 3 patrolling Horde Elites are in a wrong position (too close with each other)
Creature GUIDs are 9204, 9203 and 9205 (from left to right on the attached image)

![WoWScrnShot_090620_182026](https://user-images.githubusercontent.com/70746948/92330308-2f5e4f00-f06e-11ea-811d-2ca34732fdbd.jpg)
![WoWScrnShot_090620_182535](https://user-images.githubusercontent.com/70746948/92330348-6b91af80-f06e-11ea-9947-d9cfee844f4b.jpg)
![WoWScrnShot_090620_182529](https://user-images.githubusercontent.com/70746948/92330349-6c2a4600-f06e-11ea-89b2-f262f8435956.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They shouldnt be so near with each other while patrolling.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .gm on
2. .go creature 9204/9203/9205

##### EXTRA NOTES:

-/-

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d6646f8a81c10f5c1a83d1c04c3f5f579c282674

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by craftorix** [comment]
DELETE FROM `creature_formations` WHERE `leaderGUID`=9203;
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES 
(9203, 9203, 0, 0, 2, 0, 0),
(9203, 9204, 3, 45, 2, 0, 0),
(9203, 9205, 3, 315, 2, 0, 0);

DELETE FROM `creature_addon` WHERE guid IN (9204,9205);
DELETE FROM `waypoint_data` WHERE id IN (92040,92050);
UPDATE `creature` SET `MovementType`=0, `SpawnDist`=0 WHERE `id` IN (2477,7170);
UPDATE `creature_template` SET `MovementType`=0 WHERE `entry` IN (2477,7170);
UPDATE `creature_template` SET `Speed_Walk`=1.47, `Speed_Run`=1.14286 WHERE `entry` IN (2478);
UPDATE `creature_template` SET `Speed_Walk`=1.48, `Speed_Run`=1.14286 WHERE `entry` IN (2477,7170);

These lines of code fixed them.

**Comment by Helias** [comment]
@craftorix thank you for the fix, could you open a PR to allows the dev to make a proper code review and the testers to test it :P?

https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by FrancescoBorzi** [comment]
@craftorix just FYI, I've edited your post for better code readability:

![image](https://user-images.githubusercontent.com/75517/92978759-00424600-f491-11ea-893e-604b006dac9a.png)
