### ISSUE TITLE
Creature Waypoint

### ISSUE THREAD

**Issue by craftorix** [azerothcore/azerothcore-wotlk#3440]
Creature Waypoint

##### CURRENT BEHAVIOUR:

This Creature ID: 9464 has waypoints

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This Creature ID: 9464 has no waypoints and should only be standing there like in Image 2
![WoWScrnShot_090620_212513](https://user-images.githubusercontent.com/70746948/92333699-dc919100-f087-11ea-8b8d-c43967df7188.jpg)
![WoWScrnShot_090620_212538](https://user-images.githubusercontent.com/70746948/92333700-df8c8180-f087-11ea-8469-46a1cdf6edcd.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3.

**Comment by Helias** [comment]
Are you sure? because it's strange that someone added the waypoint randomly

**Comment by craftorix** [comment]
Yes I am 1000% sure. When I played WoW Classic this character was just standing there like in image 2.
