### ISSUE TITLE
(DB/Quest): The Hunt is on [$15]

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3443]
##### CURRENT BEHAVIOUR:

- [ ] Quest giver gives you the "Oculus of the Exorcist" which allows you to "detect recent users of cultist necromancy" When using the item the following NPCs should have the spell "Shroud of the Death Cultist" cast on them:

NPC_TOM_HEGGER                              = 25827,
NPC_SALTY_JOHN_THORPE                       = 25248,
NPC_GUARD_MITCHELLS                         = 25828,

Even though they do not have "Shroud of the Death Cultist" look to them. You are able to complete the quest. 

- [ ] I also noticed that the NPC Tom Hegger display's the $c in the aggro text "You don't know who you're messing with, $c! Death beckons!"

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After using the "Oculus of the Exorcist" you should see the 3 NPC listed above with the "Shroud of the Death Cultist" look to them. 

For the aggro text of Tom Hegger, the $c should be replaced with the players class.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele Borean
2. .quest add 11794
3. use the Oculus of the Exorcist while standing in front of the npc's listed above

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/3934678b07603bb44189f16bebb32a25b19bc23f

##### OPERATING SYSTEM:

Centos 7

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

**Comment by locus313** [comment]
i did find this pr that looks to fix the aggro text. Ill submit in a pr later:
https://github.com/TrinityCore/TrinityCore/pull/17395

**Comment by locus313** [comment]
Also see mentioned here: 
https://github.com/TrinityCore/TrinityCore/issues/16133
about the spell 46077 not working. but see it mentions it was fixed by some changes on spells by ariel.
Did some digging through the commits and think this might be the pr with the mentioned fixes:
https://github.com/TrinityCore/TrinityCore/pull/21395

**Comment by Helias** [comment]
@locus313  any updates about this?

**Comment by locus313** [comment]
No yet, I haven't tried to look into this further yet.

**Comment by UltraNix** [comment]
Made a PR. Please, review it.
