### ISSUE TITLE
[Warlock] Conflagrate Spell with Delay

### ISSUE THREAD

**Issue by Mamaro89** [azerothcore/azerothcore-wotlk#3458]
[Warlock] Conflagrate Spell with Delay

##### CURRENT BEHAVIOUR:
When you cast a Immolate Spell, you need to wait almost a second to be able to use conflagrate

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should be instant, once you use immolate, you should be able to use Conflagrate instantly.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a warlock
2. Put a Destruction Build with CONFLAGRATE on it
3.  Train your spells
4. Go to a Dummy and test using Immolate > Conflagrate spells (u'll notice a delay)

##### AC HASH/COMMIT:

68b111282149283cfd231e980ff53f2dfb5e981b

##### OPERATING SYSTEM:
Debian10

##### MODULES:
bg_reward
eluna

##### OTHER CUSTOMIZATIONS:

None.

**Comment by Mamaro89** [comment]
At least someone to tell me how to configure it with no delay, any DB table i can adjust?

**Comment by Goatform** [comment]
I personally can't recall if there should be some delay to aura state update or perhaps for it to be instant:
Here are patches that you may try:

Result: Should be instantly enabled

``` diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 0b78373..d8d330a 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -3917,19 +3917,11 @@ void Unit::_ApplyAura(AuraApplication * aurApp, uint8 effMask)
     const SpellInfo* spellInfo = aura->GetSpellInfo();
     if (AuraStateType aState = spellInfo->GetAuraState())
     {
-        if (aState != AURA_STATE_CONFLAGRATE)
-        {
-            // Sting (hunter's pet ability), Faerie Fire (druid versions)
-            if (aState == AURA_STATE_FAERIE_FIRE)
-                aurApp->GetTarget()->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);
+        // Sting (hunter's pet ability), Faerie Fire (druid versions)
+        if (aState == AURA_STATE_FAERIE_FIRE)
+            aurApp->GetTarget()->RemoveAurasByType(SPELL_AURA_MOD_STEALTH);
 
-            ModifyAuraState(aState, true);
-        }
-        else if (caster)
-        {
-            ConflagrateAuraStateDelayEvent *pEvent = new ConflagrateAuraStateDelayEvent(GetGUID(), caster->GetGUID());
-            m_Events.AddEvent(pEvent, m_Events.CalculateTime(700)); // intended 700ms delay before allowing to cast conflagrate
-        }
+        ModifyAuraState(aState, true);
     }
 
     if (aurApp->GetRemoveMode())
```

Or if there should be some delay to it, then perhaps decreasing value will do the work?
Example:

``` diff
diff --git a/src/server/game/Entities/Unit/Unit.cpp b/src/server/game/Entities/Unit/Unit.cpp
index 0b78373..87f6d01 100644
--- a/src/server/game/Entities/Unit/Unit.cpp
+++ b/src/server/game/Entities/Unit/Unit.cpp
@@ -3928,7 +3928,7 @@ void Unit::_ApplyAura(AuraApplication * aurApp, uint8 effMask)
         else if (caster)
         {
             ConflagrateAuraStateDelayEvent *pEvent = new ConflagrateAuraStateDelayEvent(GetGUID(), caster->GetGUID());
-            m_Events.AddEvent(pEvent, m_Events.CalculateTime(700)); // intended 700ms delay before allowing to cast conflagrate
+            m_Events.AddEvent(pEvent, m_Events.CalculateTime(300)); // intended 300ms delay before allowing to cast conflagrate
         }
     }
```


NOTE: Patches that I submitted aren't tested but I think they should work around the issue you reported.
I'll mention @FrancescoBorzi here to take a look since he should know who could confirm if this is the issue in a first place.

**Comment by FrancescoBorzi** [comment]
> It should be instant, once you use immolate, you should be able to use Conflagrate instantly.

can you please provide evidence of this?

**Comment by Goatform** [comment]
Here are some reports about the same issue and looks like it may be invalid.

https://github.com/azerothcore/azerothcore-wotlk/issues/298
https://github.com/SunwellTracker/issues/issues/1254

So I guess there should be some delay however to me it doesn't look like it's 700 ms delay (Probably should be tweaked a little bit ... perhaps down to 400-500 ms instead)

**Comment by Mamaro89** [comment]
> > It should be instant, once you use immolate, you should be able to use Conflagrate instantly.
> 
> can you please provide evidence of this?

Well you just need to follow the steps i created

Cast Immolate
Then try to use your conflagrate instantly, it wont work... it has a delay of something aroung 700 ms

**Comment by FrancescoBorzi** [comment]
> > > It should be instant, once you use immolate, you should be able to use Conflagrate instantly.
> > 
> > 
> > can you please provide evidence of this?
> 
> Well you just need to follow the steps i created
> 
> Cast Immolate
> Then try to use your conflagrate instantly, it wont work... it has a delay of something aroung 700 ms
> 
> Invalid - Missing Information? wich information is missing ??

What is missing is the proof that the 700ms delay should NOT be there. Can you please provide some evidence about it?

**Comment by merdlin** [comment]
I have the same problem on my server. Many players complained

**Comment by FrancescoBorzi** [comment]
> I have the same problem on my server. Many players complained

It's not a problem, as far as I know it's the blizzlike behaviour, unless you can prove it's not :)
