### ISSUE TITLE
Retrieving item information 

### ISSUE THREAD

**Issue by DomeSs97** [azerothcore/azerothcore-wotlk#3475]
Hi, i have Azerothcore 2019 

Im using custom items.. 
And i have problem with Item retrieving info 
Vendors and Loot loading around 30sec..
Can some one help to fix it? 

![JPEG_20200909_224956](https://user-images.githubusercontent.com/20913037/92992471-7d9aa480-f4eb-11ea-8149-85267011fd69.jpg)
![JPEG_20200909_225155](https://user-images.githubusercontent.com/20913037/92992477-85f2df80-f4eb-11ea-8479-a47e4e2b0ac6.jpg)

![JPEG_20200909_224651](https://user-images.githubusercontent.com/20913037/92992481-8c815700-f4eb-11ea-8071-5285df1dd9a9.jpg)

![JPEG_20200909_224613](https://user-images.githubusercontent.com/20913037/92992489-9a36dc80-f4eb-11ea-849f-b0549154070d.jpg)

**Comment by Kitzunu** [comment]
This is just the client taking the time to fetch information.

**Comment by Kitzunu** [comment]
I dont think we can do anything about it

**Comment by Meltie2013** [comment]
@DomeSs97 Could you check and see if the server itself has a high delay by running `.server info`?

**Comment by DomeSs97** [comment]
![ping](https://user-images.githubusercontent.com/20913037/93014491-c9178600-f5b1-11ea-86de-d1850f2b1264.png)

**Comment by DomeSs97** [comment]
> This is just the client taking the time to fetch information.

Its more then 30sec for every vendor or loot pick.. 
Is any way to loand cache Faster?

**Comment by DomeSs97** [comment]
https://youtu.be/z16sm4RwNIY
Its more then 30sec for every vendor or loot pick..
Is any way to loand cache Faster?

**Comment by DomeSs97** [comment]
No way to fix?

**Comment by Kitzunu** [comment]
Nope, is client that is slow to respond to server

**Comment by BarbzYHOOL** [comment]
yes, happened to me too, can be internet issue too

**Comment by DomeSs97** [comment]
> yes, happened to me too, can be internet issue too

![FB_IMG_1600269666882](https://user-images.githubusercontent.com/20913037/95047224-002b1400-06e6-11eb-8078-bac3cfa97e88.jpg)

**Comment by Si1ker** [comment]
#WeirdFlexButStillFlex

**Comment by BarbzYHOOL** [comment]
Someone else has this issue, it's weird

@domess97 ever fixed it??

**Comment by DomeSs97** [comment]
@BarbzYHOOL No..
