### ISSUE TITLE
Brewfest event started a week early

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3479]
##### CURRENT BEHAVIOUR:

I noticed that the brewfest event started today(September 13th):

![image](https://user-images.githubusercontent.com/4015312/93036261-406e0980-f5f4-11ea-91ed-d9a995b7970d.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Brewfest should not start until September 20th

##### STEPS TO REPRODUCE THE PROBLEM:

1. .event activelist
2. check to see if brewfest is showing as active (before September 20th)

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/92d2c4c60268733da1e7a0d35b8acecddba71864

##### OPERATING SYSTEM:

Centos 7 

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

**Comment by Kitzunu** [comment]
```sql
DELETE FROM `game_event` WHERE `eventEntry` = 24;
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `holidayStage`, `description`, `world_event`, `announce`) VALUES 
(24, '2017-09-20 01:01:00', '2030-12-31 07:00:00', 525600, 21600, 372, 2, 'Brewfest', 0, 2);
```
Do the maths on that and see if it will begin on Sunday instead

**Comment by locus313** [comment]
@Kitzunu Think that is about right
![image](https://user-images.githubusercontent.com/4015312/93153379-f8afb680-f6b5-11ea-85d7-28f8fea29980.png)

**Comment by locus313** [comment]
@Kitzunu Here is after applying your sql from above:
![image](https://user-images.githubusercontent.com/4015312/93157430-12093080-f6bf-11ea-944b-936ad689c752.png)
