### ISSUE TITLE
[Dungeon] Wailing Caverns - Druids of the Fang wrong shape-shifting sound

### ISSUE THREAD

**Issue by ninjaskija** [azerothcore/azerothcore-wotlk#3483]
CURRENT BEHAVIOUR:
When Druids of the Fang are shapeshifting into snakes they make a druid bear sound instead of a snake sound.

EXPECTED BLIZZLIKE BEHAVIOUR:
They should make a snake-like sound.

STEPS TO REPRODUCE THE PROBLEM:
Engage the Druids of the Fang and observe.

AC HASH/COMMIT:
`854dbef`

OPERATING SYSTEM:
Docker under Ubuntu 20.04

MODULES:
```
mod-autobalance/
mod-random-enchants/
mod-solocraft/
mod-solo-lfg/
```

**Comment by r0m1ntik94** [comment]
@ninjaskija confirm for sound.
How to find out what the sound should be? spell bear icon.
For dev spellId: [8041](https://www.wowhead.com/spell=8041/serpent-form)

**Comment by wizzymore** [comment]
Hi, i never fixed spells but i tried to find this one and it is not in the core neither in the database, it might me an error from the .dbc

**Comment by vtihomirov** [comment]
Hi guys I also wondered about this issue and I searched youtube a bit for a valid source and fortunately I think I've found one https://youtu.be/WR6cJkIOwL0?t=1235. I think that we can close the issue for now as it looks like it is the bear sound in classic as well. We should however reopen it again if a more reliable video source is found.
