### ISSUE TITLE
[Dungeon] Wailing Caverns - Disciple of Naralex stops casting

### ISSUE THREAD

**Issue by ninjaskija** [azerothcore/azerothcore-wotlk#3484]
CURRENT BEHAVIOUR:
In the last phase when Naralex should be saved, if the Disciple of Naralex gets attacked it will stop casting.

EXPECTED BLIZZLIKE BEHAVIOUR:
He should cast until the phase is finished

STEPS TO REPRODUCE THE PROBLEM:
Get to the last boss and observe

AC HASH/COMMIT:
`854dbef`

OPERATING SYSTEM:
Docker under Ubuntu 20.04

MODULES:
```
mod-autobalance/
mod-random-enchants/
mod-solocraft/
mod-solo-lfg/
```

**Comment by Hacaw** [comment]
CONCLUSION
---
Pretty hard to test this.
I tried to add the quest for the disciples but is not found.
I went to Naralex who sleeps 
.go c id 3679

@ninjaskija can you please provide more gm-commands and test steps so I can easily reproduce it ?

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None
