### ISSUE TITLE
[Raid-ToC] Nerubian Burrower can be cc-able from all sources

### ISSUE THREAD

**Issue by ARDYS25** [azerothcore/azerothcore-wotlk#3486]
good
 **REPORT CRUSADER TEST:**

1. **Npc  https://es.wowhead.com/npc=34607/perforador-nerubiano**

 **Raid Boss anub'arak, either normal or heroic, the skills that I will mention can be used with the following skills, which remains to be fixed:**

**https://es.classic.wowhead.com/spell=9484/chain-not-dead (Chain Undead)**

https://en.wowhead.com/spell=3355/freezing-trap (Freezing Trap)

https://es.classic.wowhead.com/spell=20066/repentimiento (Repentance)

https://es.wowhead.com/spell=57546/ahuyentar-el-mal-superior (Drive away evil)

https://db.wowlatinoamerica.com/?spell=60192 (Freezing Arrow)

https://es.classic.wowhead.com/spell=339/enwrapping-roots (Entangling roots)

**TTest the video malfunction demonstrated in this RAID Facebook server azeroth project**
https://www.facebook.com/WoW-Azeroth-Project-335-Camino-a-la-Luz-del-Alba-108019180728305/videos/toc-25h-raid-1-y-2/534619004070804/    error report Video of the last minutes since they put CC since this server has an emulator  **azeroth core** server _  **Azeroht project_**

Test the video
[https://youtu.be/uaXSPY6oAKc?t=4553](url)
 
### **¿HOW IT SHOULD WORK?**

TankSpot's Guide to Heroic Anub'arak (25 Hard)
OFFICIAL  https://www.youtube.com/watch?v=zDmdb9RYecY

_In the tankspot video they explain that only stun are used to cut the cast of the adds, other cc's are never mentioned this video is from 2009_
https://www.youtube.com/watch?v=PlMtNG8D2x0

**Comment by ARDYS25** [comment]
when they can reviewN, since TOC is one of the bands of patch 3.2 Important

**Comment by Si1ker** [comment]
@ARDYS25 Re-do your issue (English) using the issue template or it will be close it.

**Comment by Si1ker** [comment]
The issue was opened with invalid information but it is confirmed.
Reopening and changing the title to English.
I have created a Pull request to fix this issue after further research has been done.
