### ISSUE TITLE
Brewfest - horde -  Low level hostile mobs are wandering the camp

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#3496]
##### CURRENT BEHAVIOUR:

When you go to the brewfest camp just outside of orgrimmar. You will see there is low level hostile mobs wandering the camp

![image](https://user-images.githubusercontent.com/4015312/93822495-285e4180-fc15-11ea-9f6a-3e2496bdf3bb.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

During the Brewfest event the low level mobs should not be wandering in the camp.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the brewfest camp right outside orgrimmar
2. 
3. 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/4406830e36fc16e2fd79354a70f7650756bf6257

##### OPERATING SYSTEM:

centos7

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

**Comment by Kitzunu** [comment]
That one probably shouldnt even have a spawn there ever

**Comment by locus313** [comment]
@Kitzunu do think the non hostile's should be removed as well? ill try to collect all the guid's.

**Comment by locus313** [comment]
Here is the sql I Tested:
```
--- hostile mobs ---
DELETE FROM `creature` WHERE `guid` IN (7370, 22181, 22188, 22473);
--- non-hostile mobs ---
DELETE FROM `creature` WHERE `guid` IN (12369, 21020, 21022, 21026);
```
Here is a screenshot from my test:
![image](https://user-images.githubusercontent.com/4015312/93837116-d7147900-fc39-11ea-8860-73c145175b51.png)

ill submit a pr with the changes.

**Comment by genion18** [comment]
is this are not better when you makes this creatures in an Event?

Then the event start are the Creature Hidden and then not creature unhidden.
