### ISSUE TITLE
Slide on Gunnery outside ICC

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#3498]
##### CURRENT BEHAVIOUR:

When a player arrives on the gunnery outside ICC, and that it leaves it starts to slide on the ground with the same trajectory as the gunnery .

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once it comes out of the Gunnery it is not supposed to slide.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Juste climb aboard the Gunnery and leave it afterwards.

##### EXTRA NOTES:
A video of bug : 
 - https://www.youtube.com/watch?v=r-SrN37Q27Q

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/3815e0df4f6a8ef2e82739bd60c428f801d26f9e

##### OPERATING SYSTEM:

Debian 10 on server / Windows 10 on client

##### MODULES:

- mod-1v1-arena
- mod-arena-tiger
- mod-arena-tolviron
- mod-autobalance
- mod-better-item-reloading
- mod-bg-battle-for-gilneas
- mod-bg-reward
- mod-bg-twinpeaks
- mod-cfbg
- mod-eluna-lua-engine
- mod-instance-reset
- mod-learn-spells
- mod-pvp-titles
- mod-random-enchants
- mod-spell-regulator
- mod-transmog

##### OTHER CUSTOMIZATIONS:

Yes mine Parangon System & Exp_Modifier

**Comment by Si1ker** [comment]
Cannot repro.
last commit #3016

**Comment by iThorgrim-Hub** [comment]
I have test without all my module i have the same bugs on Gunnery.
These are not the Gunnary inside ICC but outside

![WoWScrnShot_092420_123339](https://user-images.githubusercontent.com/58987080/94134475-57b5be00-fe62-11ea-9185-dce09027fd43.jpg)

**Comment by FrancescoBorzi** [comment]
> Cannot repro.
> last commit #3016
@Si1ker what is exactly your AC version (commit hash)? Also, please make sure you are upgrading your server properly, i.e. not manually cherry-picking things (otherwise your server version is different than a clean AC).

**Comment by iThorgrim-Hub** [comment]
The bug comes from one of the patches of the modules Custom BG or Custom Arena.
