### ISSUE TITLE
Brewfest isnt UP, while it counts as running on callendar

### ISSUE THREAD

**Issue by Mamaro89** [azerothcore/azerothcore-wotlk#3499]
Brewfest not working ?

##### CURRENT BEHAVIOUR:
There is nothing on where the event should be
<a href="https://ibb.co/zft71Tt"><img src="https://i.ibb.co/2Kpsw1p/Wo-WScrn-Shot-092220-215217.jpg" alt="Wo-WScrn-Shot-092220-215217" border="0"></a>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should be crowded
<a href="https://imgbb.com/"><img src="https://i.ibb.co/sjgTH3c/download-1.jpg" alt="download-1" border="0"></a>

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Log in
2.  Go to where the event should be happening right now
3.  Note that there is nothing in place

##### EXTRA NOTES:
Just updated my core recently

##### AC HASH/COMMIT:
commit 68b111282149283cfd231e980ff53f2dfb5e981b 

##### OPERATING SYSTEM:
Debian 10

##### MODULES:
Yes:
BGReward
CFBG
duelreset
individual-xp
Eluna
mod_arena_top
transmog

##### OTHER CUSTOMIZATIONS:
No

<!-- ------------------------- THE END ------------------------------

**Comment by locus313** [comment]
Brewfest is working for me:
![image](https://user-images.githubusercontent.com/4015312/93965579-54fa8200-fd17-11ea-948d-9389fa090b63.png)
![image](https://user-images.githubusercontent.com/4015312/93965609-66438e80-fd17-11ea-92e1-5fb66141f043.png)

**Comment by Kitzunu** [comment]
Update your core.

**Comment by Mamaro89** [comment]
THanks @Kitzunu
