### ISSUE TITLE
PP 10HC dropping only Vanquisher's Mark of Santification, not another type

### ISSUE THREAD

**Issue by Mamaro89** [azerothcore/azerothcore-wotlk#3500]
PP on 10hc only drops Vanquisher's Mark as the Marks Items, the rest is OK

##### CURRENT BEHAVIOUR:
It only drop 1 type of Mark.
It drops 2 marks, both the same, vanquisher's
Here's the DB:
<a href="https://ibb.co/y5nx3X8"><img src="https://i.ibb.co/Y87Vr3t/PHOTO-2020-09-22-22-03-56.jpg" alt="PHOTO-2020-09-22-22-03-56" border="0"></a>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should not drop the same Mark twice, same boss fight.
It should be one Vanquisher and another Conqueror's, example

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Enter ICC 10 man Heroic Mode
2.  Kill PP
3.  Check the loot

##### EXTRA NOTES:
I'll fix it myself by creating another reference_loot table, but i think it should be fixed in core

##### AC HASH/COMMIT:
commit 68b111282149283cfd231e980ff53f2dfb5e981b 

##### OPERATING SYSTEM:
Debian 10

##### MODULES:
BGReward
CFBG
duelreset
individual-xp
Eluna
mod_arena_top
transmog

##### OTHER CUSTOMIZATIONS:
No

<!-- ------------------------- THE END ------------------------------

**Comment by Mamaro89** [comment]
Idk why.. when i go with my GM it works.. but in raids it is only dropping vanquisher
i'll investigate more

**Comment by FallenDev** [comment]
I've tested this and can confirm this is still an issue. Another issue with Marks is it's dropping the normal marks instead of the Heroic versions in Heroic mode. This issue should be reopened. 
ICC 10 HC & ICC 25 HC
![image](https://user-images.githubusercontent.com/12104989/211177376-01ad7b02-3ed6-4eed-8ff3-6205ef125cd2.png)
