### ISSUE TITLE
Professor Putricide 25 man Normal, loot not working

### ISSUE THREAD

**Issue by Mamaro89** [azerothcore/azerothcore-wotlk#3501]
Professor Putricide 25 man Normal, loot not working

##### CURRENT BEHAVIOUR:
When you kill PP on ICC 25, it does not drop the items, just one
Drop:
<a href="https://ibb.co/Wv90YZ3"><img src="https://i.ibb.co/JjLqMVd/Wo-WScrn-Shot-092220-223410.jpg" alt="Wo-WScrn-Shot-092220-223410" border="0"></a>
<a href="https://ibb.co/B3ZJmj8"><img src="https://i.ibb.co/MSVHbpq/Wo-WScrn-Shot-092220-223412.jpg" alt="Wo-WScrn-Shot-092220-223412" border="0"></a>

See the DB:
<a href="https://ibb.co/y5nx3X8"><img src="https://i.ibb.co/Y87Vr3t/PHOTO-2020-09-22-22-03-56.jpg" alt="PHOTO-2020-09-22-22-03-56" border="0"></a>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should drop more then 1 normal item.
Besides, should not it be on reference_loot table? to work with the multiplier on worldserver.conf ?

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to ICC 25 man Normal
2.  Kill Professor Putricide
3.  Take a look at the loot

##### EXTRA NOTES:

AC HASH/COMMIT:
commit 68b1112

OPERATING SYSTEM:
Debian 10

MODULES:
Yes:
BGReward
CFBG
duelreset
individual-xp
Eluna
mod_arena_top
transmog

OTHER CUSTOMIZATIONS:
No

**Comment by Mamaro89** [comment]
Here the fix i made:
<a href="https://ibb.co/q0Spkx7"><img src="https://i.ibb.co/f8gH4Qq/tit.png" alt="tit" border="0"></a>

**Comment by Helias** [comment]
@Mamaro89 could you open a PR with the SQL code?

**Comment by Mamaro89** [comment]
> @Mamaro89 could you open a PR with the SQL code?

I rly dont know how to make it.. @Helias but i would love to

**Comment by Helias** [comment]
if you have the SQL code, it's easy, just follow https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by Si1ker** [comment]
Just waiting for any validated source (retail) of information which indicates your suggested loot is the correct one 🐱

**Comment by Voxstrasza** [comment]
I am pretty certain that ICC heroic end bosses should drop 1x piece of loot, 2x normal tokens and 1x heroic token, as well as 2x frost emblems and a possibility of a primordial saronite and shadowmourne shard, and normal should be 1x loot, 2x normal tokens, 2 frost emblems and chance for primordial saronite/shard
