### ISSUE TITLE
Quests.IgnoreAutoAccept=1 client cannot receive the quest manually

### ISSUE THREAD

**Issue by amydomi** [azerothcore/azerothcore-wotlk#3503]
**Describe the bug**
worldserver.conf
Quests.IgnoreAutoAccept=1
client cannot receive the quest manually

**To reproduce**
1. configuration server worldserver.conf Quests.IgnoreAutoAccept=1
2. There is no response when the client clicks NPC to accept the quest manually

**Expected behavior**
Allows the user client to accept quest manually

**Comment by Helias** [comment]
It's a problem of the core not of the documentation/wiki.
So I am moving this to the repo azerothcore-wotlk.

**Comment by dusksoft** [comment]
The problem has not been solved.

**Comment by Kitzunu** [comment]
Could you provide a screenshot? I dont have the time to test this right now, but I do have a theory

**Comment by dusksoft** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by dusksoft** [comment]
worldserver.conf
Quests.IgnoreAutoAccept=1
![1](https://user-images.githubusercontent.com/2236995/94602679-c910c900-02c7-11eb-9017-803e25efc887.png)
![2](https://user-images.githubusercontent.com/2236995/94602722-d62db800-02c7-11eb-8447-6d1bacb93b5f.png)
