### ISSUE TITLE
Does not send mail from the site to the game or between players in the game

### ISSUE THREAD

**Issue by NiganNi** [azerothcore/azerothcore-wotlk#3504]
SMALL DESCRIPTION:
Does not send mail from the site, players can not exchange things among themselves. But the amazing thing is that money is sent by mail. SOAP is enabled, but the player cannot receive mail when using SOAP to send items, but not money.
I made the transfer from trinitycore to azerothcore all according to the instructions. The server is working well, but there is a problem with SOAP. I have tried with a clean database acore_auth acore_character acore_world. All the same, I think that the problem is in the worldserver itself. When you switch to trinitycore, everything works.
No errors were found during compilation.

CURRENT BEHAVIOUR:
Players don't receive mail

STEPS TO REPRODUCE THE PROBLEM:
SOAP.Enabled = 1
SOAP.IP = "0.0.0.0"
SOAP.Port = 7878

EXPECTED BLIZZLIKE BEHAVIOUR:
Players exchange items via in-game mail

BRANCH(ES):
master
AzerothCore rev. 3815e0df4f6a+ 2020-09-22 11:33:15 +0200 (master branch) (Win64, Release) (worldserver-daemon)

OPERATING SYSTEM:
Win х64

**Comment by Ramys** [comment]
You have to activate your machine's Telnet.

**Comment by Ramys** [comment]
Close this.
