### ISSUE TITLE
Feature: Automatically speak when entering NPC area

### ISSUE THREAD

**Issue by amydomi** [azerothcore/azerothcore-wotlk#3506]
**Describe your feature request or suggestion in detail**
In the area where an Npc is located, an Npc can speak automatically. Blizzard official has this, TrinityCore also has it. Why don't we have it here?

**Describe a possible solution to your Feature or Suggestion in detail**
See trinityCore for the latest source code

**Additional context**

**Comment by dusksoft** [comment]
This is a screenshot of TrinityCore server

![3](https://user-images.githubusercontent.com/2236995/94603651-1f323c00-02c9-11eb-81cc-cb45dbb74d31.png)

**Comment by IceNet** [comment]
AzerothCore has it...

Many NPC speaks when you are in the near.

**Comment by Nyeriah** [comment]
Each NPC script needs to be fixed individually so the lines are said when a player moves in line of sight, or on a timer if that is the case. Closing this as it doesn't have enough information for us to go around.
