### ISSUE TITLE
10 Man Raid - Ulduar - Flame Leviathan Shutdown [$20]

### ISSUE THREAD

**Issue by NexusWoW** [azerothcore/azerothcore-wotlk#351]
Description:
Flame Leviathan doesn't go into Shutdown when turrets are destroyed.

Current behaviour: Tell us what happens
If a player is launched onto FL he/she can target and destroy the turrets on FL as expected. However, destorying these turrets currently causes no effect,

Expected behaviour: Tell us what should happen instead
Destroying the turrets should cause FL to become stunned, increase its damage taken by 50% and reset its gather speed buff.

Steps to reproduce the problem:

Engage FL.
Launch player onto FL.
Player destroys turrets.
http://wowwiki.wikia.com/wiki/Flame_Leviathan

Branch(es): 0.x / 1.x / master (Specify the branch(es) affected by this issue)

AC hash/commit:
a0ade8571fbc16f9d8452966e89faefd76fab07e
Operating system:
server 2008

Modules: Are you using modules? if yes, list them
none

Other Customizations: Are you use core/db patches or other customizations? If yes please specify them here.
none

**Comment by ShinDarth** [comment]
please fill ``AC hash/commit:``

**Comment by NexusWoW** [comment]
done

**Comment by markvetwow** [comment]
Confirm this issue. Tested Levi encounter in 5 modes. Normal/+1,2,3,and all towers. Same issue is happening. Shutdown doesn't remove MS stacks. :(

**Comment by Naxxramas-Server** [comment]
I confirm the problem , not only in 10 players , 25 too

**Comment by poszer** [comment]
Hmm, how i can see the problem is in function definitions for some scripts.

**Comment by Naxxramas-Server** [comment]
I think the problem is here : 

class boss_flame_leviathan_overload_device : public CreatureScript
{
    public:
        boss_flame_leviathan_overload_device() : CreatureScript("boss_flame_leviathan_overload_device") { }

        struct boss_flame_leviathan_overload_deviceAI : public NullCreatureAI
        {
            boss_flame_leviathan_overload_deviceAI(Creature* creature) : NullCreatureAI(creature)
            {
            }

            void OnSpellClick(Unit* /*clicker*/, bool& result)
            {
                if (!result)
                    return;

                if (me->GetVehicle())
                {
                    me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
                    me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);

                    if (Unit* player = me->GetVehicle()->GetPassenger(SEAT_PLAYER))
                    {
                        me->GetVehicleBase()->CastSpell(player, SPELL_SMOKE_TRAIL, true);
                        player->ExitVehicle();
                    }
                }
            }
        };

        CreatureAI* GetAI(Creature* creature) const
        {
            return new boss_flame_leviathan_overload_deviceAI(creature);
        }
};

In expedcted behaviour , player doesn't need to activate overload device after turret death for overload circuit.
Players just have to kill all the turret and the overload is automatically not a spellClick.
But i don't know how to do this , i don't know c++

**Comment by Naxxramas-Server** [comment]
I'v add 20$ bounty on this issue
