### ISSUE TITLE
[Dungeon /The Oculus] Dragon keepers don't come out

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#3519]
[Dungeon / Occulus] No dragons ?

##### CURRENT BEHAVIOUR:

When Drakos dies, the NPCs in the cages do not come forward.
They do not summon any dragons.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://youtu.be/GpCe2As30IY?t=110

When the Drakos die, the cages are supposed to open, the NPCs appear and we can choose the dragon we want for the rest of the dungeon.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to occulus
2. Kill Drakos
3. Nothing else

##### EXTRA NOTES:
Nothing sorry :-/

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/8b3a1c1fe58488912f3d3b1a244664e7385b46a1

##### OPERATING SYSTEM:

Debian 10

##### MODULES:
Nothing

##### OTHER CUSTOMIZATIONS:
Nop, nothing

**Comment by Si1ker** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/61223313/94776573-36336580-037f-11eb-9a0a-f76ba5db0cb7.png)
