### ISSUE TITLE
Paladin - Greater Blessings on pets

### ISSUE THREAD

**Issue by NexusWoW** [azerothcore/azerothcore-wotlk#352]
Description:
If you cast a Greater Blessing on a pet, it applies to the Paladin as well and vice versa.

Current behaviour: Tell us what happens
When a Paladin casts a Greater Blessing (Eg. Greater Blessing of Sanctuary) upon himself, he gets the buff, but so do any pets of other raid members, eg. warlock imp, hunter pet.
If a paladin casts a Greater Blessing upon a pet in the raid group the buff is applied to the Paladin class as well.
This is annoying because often a paladin will want to cast a different buff on pets to the one for the paladin class.

Expected behaviour: Tell us what should happen instead
A paladin casting a Greater Blessing upon himself should apply that blessing only to the paladin class, not pets of raid members.
A paladin casting a Greater Blessing upon a pet in the group should apply that blessing only to pets in the group, not paladins and himself.

Steps to reproduce the problem:

Group a paladin with a warlock/hunter with their pet out.
Cast Greater blessing of might on paladin, it will go on pet and paladin.
Cast Greater blessing of wisdom on pet and it will go on pet and paladin,
Branch(es): 0.x / 1.x / master (Specify the branch(es) affected by this issue)

AC hash/commit:
a0ade8571fbc16f9d8452966e89faefd76fab07e
Operating system:
server 2008

Modules: Are you using modules? if yes, list them
none

Other Customizations: Are you use core/db patches or other customizations? If yes please specify them here.
none

**Comment by ShinDarth** [comment]
please fill ``AC hash/commit:``
