### ISSUE TITLE
[Dungeon / Trial of Champion] - Dismount

### ISSUE THREAD

**Issue by iThorgrim-Hub** [azerothcore/azerothcore-wotlk#3520]
[Dungeon / Trial of Champion] - Dismount

##### CURRENT BEHAVIOUR:

When we climb on a mount, it makes us come down directly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
We are supposed to be able to ride on a proposed mount to launch the dungeon.
https://youtu.be/mdPDYjFYLkU?t=57

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to "Trial of Champion"
2. Try to ride mount 
3. nothing else

##### EXTRA NOTES:
I think the problem comes from here: https://github.com/azerothcore/azerothcore-wotlk/blob/1f89282b225147675073c11cbcc996419df4a15b/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp#L188
I have no skills in Cpp 😢

##### AC HASH/COMMIT:
8b3a1c1

##### OPERATING SYSTEM:
Debian 10

**Comment by r0m1ntik94** [comment]
@iThorgrim-Hub can't confirm on [6ef28a8
](https://github.com/azerothcore/azerothcore-wotlk/commit/6ef28a8c4744db3781f9636d738c9f9164856c88)

You forgot to put this item [Argent Lance](https://www.wowhead.com/item=46106/argent-lance) before getting on the mount.

![Capture d’écran 2020-09-28 à 21 53 21](https://user-images.githubusercontent.com/12685486/94479798-9be3ee00-01d5-11eb-91b1-5e2fc35d548c.png)
![Capture d’écran 2020-09-28 à 21 53 31](https://user-images.githubusercontent.com/12685486/94479809-9edede80-01d5-11eb-8991-ee5355092912.png)

**Comment by iThorgrim-Hub** [comment]
Thanks for the information, I searched a little bit everywhere but I hadn't found anything!
Thanks a lot !!
