### ISSUE TITLE
[Defender of Timbermaw] Doesn't heal

### ISSUE THREAD

**Issue by CyberFoxHax** [azerothcore/azerothcore-wotlk#3521]
##### CURRENT BEHAVIOUR:
Use of the trinket [[Defender of Timbermaw]](https://classic.wowhead.com/item=21326) will summon a helper that will assist in melee combat. It does not heal, I've tried going to 1% hp in hopes it would trigger the healing. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I never had this on retail. But the description says "Use: Calls forth a Timbermaw Ancestor to fight at your side and heal you. (10 Min Cooldown)"

##### STEPS TO REPRODUCE THE PROBLEM:
.additem 21326

##### EXTRA NOTES:
Same issue when i got the trinket on Warmane.

Commit: e1bf18374124ff05ab41f8014f001d27af1ab865
Server OS: Debian 10
Modules: None
Other customizations: None

**Comment by Knindzagxg** [comment]
Try with fix i made.
Should be sorted.

https://github.com/azerothcore/azerothcore-wotlk/pull/3523

**Comment by FrancescoBorzi** [comment]
https://www.azerothcore.org/wiki/How-to-test-a-PR
