### ISSUE TITLE
[Ulduar] Kologarn Focused Eyebeam

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#3524]
##### CURRENT BEHAVIOUR:

At Ulduar (10/25) at the moment Kologarn executes event EVENT_FOCUSED_EYEBEAM he stops attacking or using abilities.
He resumes using melee attacks and abilities until the event is finished

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When he has active his SPELL_FOCUSED_EYEBEAM and following a player, he doesn't attack or use any other abilities until the event finishes to do attacks and spells once again

https://www.youtube.com/watch?v=4fmcDjlVfto
At 0:28: He uses SPELL_FOCUSED_EYEBEAM..  AND ! doing attacks and using other spells/abilities

https://www.youtube.com/watch?v=SeK4SqoRwLA
At 2:28: Same, he is using SPELL_FOCUSED_EYEBEAM and using abilities/attacks

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go xyz 1763.09 -23.60 448.80 603 0.00
2. Fight Kologarn
3. Wait until he uses his Focused Eyebeam, you will notice he stops using attacks/abilities

##### EXTRA NOTES:

I have tried commenting at line 389 but there is a minor difference and does not resolve the problem
```cpp
if (me->HasUnitState(UNIT_STATE_CASTING))
```

Also I've tried to remove this conditional at line 483, it ended up in the Boss attacking every 0.1 seconds  xD
```cpp
//Make sure our attack is ready and we aren't currently casting before checking distance
            if (me->isAttackReady() && me->GetVictim()) // victim could die by a spell (IMPORTANT!!!) and kologarn entered evade mode
```

##### AC HASH/COMMIT:

8b3a1c1

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

None  : )

##### OTHER CUSTOMIZATIONS:
 Hardest custom Naxxramas ever  < 3

**Comment by wizzymore** [comment]
Hi, i can confirm this is true, once he gets the specific event he stops everything else. After 12 seconds the script gets resumed

**Comment by wizzymore** [comment]
@Si1ker please review this: https://github.com/azerothcore/azerothcore-wotlk/pull/3529
