### ISSUE TITLE
Docker .env MySQL-Password not working

### ISSUE THREAD

**Issue by D3B453R** [azerothcore/azerothcore-wotlk#3527]
##### CURRENT BEHAVIOUR:

When copying the ./.env.dist file to ./.env and changing the password for the DB the pw is still set to "password" after the containers are up and running.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Copied the ./.env.dist file to ./.env
2. Changed the pw to something else like 123456
3. Password is still set to "password" after starting the containers with "docker-compose up --build"

##### OPERATING SYSTEM:

Ubuntu Server 20.04

**Comment by FrancescoBorzi** [comment]
> Password is still set to "password" after starting the containers with "docker-compose up --build"

have you destroyed and recreated your containers?

you can try to destroy EVERYTHING using `docker reset -a` and try again

**Comment by D3B453R** [comment]
> > Password is still set to "password" after starting the containers with "docker-compose up --build"
> 
> have you destroyed and recreated your containers?
> 
> you can try to destroy EVERYTHING using `docker reset -a` and try again

I get 'reset' is not a docker command so i ran instead:

docker rm $(docker ps -aq)

docker rmi $(docker images -q)

docker system prune

but still no luck. I've tried it with an older version of the repo from my backup and there it is working.

**Comment by locus313** [comment]
There is a persistent volume for the ac-database docker. here is what I would try:
```
docker-compose stop
docker-compose down
docker system prune
docker system prune --volumes
```

**Comment by D3B453R** [comment]
> docker system prune --volumes
> ```
That solved my problem, thank you. 🥇

**Comment by FrancescoBorzi** [comment]
@D3B453R @locus313 it would be nice to open a Q&A on StackOverflow with this problem/solution

**Comment by locus313** [comment]
@FrancescoBorzi added to StackOverflow:
https://stackoverflow.com/questions/64459085/azerothcore-docker-env-mysql-password-not-working/64459087#64459087
