### ISSUE TITLE
Ulduar Base Camp - Mage channel beam

### ISSUE THREAD

**Issue by aradep** [azerothcore/azerothcore-wotlk#3528]
##### CURRENT BEHAVIOUR:
In the Expedition Base Camp in Ulduar, the two Kirin Tor Battle-Mages nearest the shield are not channeling any spells.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The Kirin Tor Battle-Mages nearest the shield should be channeling a purple energy beam at the shield while it is up, connecting to the two spots visible above. 
https://www.youtube.com/watch?v=_79ba-tIGF8 Video shows blizzlike behavior

##### STEPS TO REPRODUCE THE PROBLEM:
Enter a fresh lockout of Ulduar and look at the shield.

##### EXTRA NOTES:
The channel target NPCs appear to be present, but they are on the ground instead of hovering in place.

##### AC HASH/COMMIT:
e9bce8a

##### OPERATING SYSTEM:
Win 10

**Comment by Si1ker** [comment]
@aradep test #3548 , you opened the issue so I guess you want to have it resolved as soon as possible, this can be done by testing in. 🐱

**Comment by aradep** [comment]
@Si1ker will do, thanks!

**Comment by Hacaw** [comment]
@FrancescoBorzi please update it with the correct labels, since a fix was already provided :D

**Comment by FrancescoBorzi** [comment]
@Hacaw you should already have the permissions to change labels, haven't you?
