### ISSUE TITLE
[NPC][WOTLK] Snowblind Digger(s) Wrong Location

### ISSUE THREAD

**Issue by STARRHELD** [azerothcore/azerothcore-wotlk#353]
Missing spawn locations/wrong spawn location(s)-
They are doing their emote in the air with their pick(s)...

![IMG1](http://i.imgur.com/GQB90lZ.jpg)
![IMG2](http://i.imgur.com/twVLE34.jpg)
![IMG3](http://i.imgur.com/jfVD0Bw.jpg)

From retail: 
![IMG4](https://scontent-arn2-1.xx.fbcdn.net/v/t35.0-12/16357744_10155675871038881_1862760481_o.jpg?oh=8fee01b1ca92a9e65c0ad9a07bcc7ef2&oe=588D505D)
![IMG5](http://i.imgur.com/BEeMawp.jpg)

**Comment by starrheld** [comment]
@Rushor present at current TC rev?

**Comment by STARRHELD** [comment]
Closing down this issue since there's not been any progress or discussion going on.
We might re-open this issue once there's been a breakthrough in progress.
