### ISSUE TITLE
Rogue Vanish + Mage Mirror Image

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#3532]
##### CURRENT BEHAVIOUR:
When a Mague uses [Mirror Image](https://www.wowhead.com/spell=55342/mirror-image) and they start to attack a rogue, he uses Vanish and the copies still have them on target. If you get far from them, they follow you.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Copies should lose rogue target and they have not to follow him.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Enter in duel with a Rogue and a Mage
2. Cast Mirror Image with the mage and start to attack the rogue
3. Use Vanish with the rogue and get far from the copies
4. Copies follow the rogue and they does not lose his target.

##### AC/HASH COMMIT
[e19a217](https://github.com/azerothcore/azerothcore-wotlk/commit/e9bce8a0f4544c87a6ce00d7123a634802f12800)

**Comment by Maurowin** [comment]
Someone can confirm that ?

**Comment by Kitzunu** [comment]
Works on b2861be1cd623182fd9e900c9ccfe8e063f28d8e
