### ISSUE TITLE
Naxx - Noth the Plaguebringer visual bug.

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#354]
**Description**:

**Current behaviour**: So,after entering the Balcony phase(casting teleport), he is coming back to last tank position(before he casts teleport)

**Expected behaviour**: After casting a teleport,he must stand still on the balcony.

**Steps to reproduce the problem**:

1. Pull Noth
2. Wait around 90-110 seconds

**Branch(es)**: master

**AC hash/commit**:  ad0d548

**Operating system**:  Windows 8.1 x64 with last updates

**Modules**:  No

**Other Customizations**: No.

**Some video proof is here**:  [Link!](https://www.youtube.com/watch?v=_rC5_9v8DJQ)

**Comment by talamortis** [comment]
thanks for proof, i will look into this with remote desktop as im on holiday 👍
