### ISSUE TITLE
[QUEST][WOTLK] A COLD FRONT APPROACHES

### ISSUE THREAD

**Issue by STARRHELD** [azerothcore/azerothcore-wotlk#355]
This quest displays as un-completed

![IMG1](http://i.imgur.com/og2m5OP.jpg)

Should be yellow (completed on pickup):
https://www.youtube.com/watch?v=yuaaxlBYN0g

**Comment by starrheld** [comment]
Possible fix:

```sql
UPDATE `quest_template` SET `QuestType`=2 WHERE `Id`=13070;
```

This will only partially fix it however, the quest should be completed on pickup not when you speak to the NPC.

**Comment by STARRHELD** [comment]
Closing down this issue since there's not been any progress or discussion going on.
We might re-open this issue once there's been a breakthrough in progress.
