### ISSUE TITLE
(Raid-Ulduar) Wrong damage in bosses

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#3552]
##### CURRENT BEHAVIOUR:

The current damage of Ulduar bosses they are very superior to those of blizzard.
Here are some examples.
![ignis 25](https://user-images.githubusercontent.com/37153212/95269476-11b40f00-07ff-11eb-82e4-b643f1d2c46a.jpg)
![hodir 25](https://user-images.githubusercontent.com/37153212/95281295-67e37b00-081c-11eb-8c12-44aa2dd4da4d.jpg)
![thorim 25](https://user-images.githubusercontent.com/37153212/95273290-4e383880-0808-11eb-954e-d53e4e14a57a.jpg)
![freya 25](https://user-images.githubusercontent.com/37153212/95269510-255f7580-07ff-11eb-91b8-fffd76b815f7.jpg)
![mimiron 25](https://user-images.githubusercontent.com/37153212/95269793-cf3f0200-07ff-11eb-8e84-04dccafa8853.jpg)
![vezax 25](https://user-images.githubusercontent.com/37153212/95273324-6445f900-0808-11eb-876a-0a9ec93ebeb9.jpg)
![vezax 10](https://user-images.githubusercontent.com/37153212/95273599-17165700-0809-11eb-87ed-d17b14a377ee.jpg)

Almost all bosses have the wrong damage and this happens in mode 10 and 25 but at the moment I could only find this.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The damage inflicted by the bosses is shown in the following videos:
Ignis 10
https://www.youtube.com/watch?v=dXVOTCBbTgM
https://www.youtube.com/watch?v=vVZ-df9kfTk
Ignis 25
https://www.youtube.com/watch?v=Plxi6jaBcJ0
https://www.youtube.com/watch?v=2pNvPmaS3-w
https://www.youtube.com/watch?v=q5hQ6xgBTfc
Hodir 10
https://www.youtube.com/watch?v=wmJz7OkYiFo
hodir 25
https://www.youtube.com/watch?v=e1LRW0YaKyg
https://www.youtube.com/watch?v=auxb6AGzuqM
https://www.youtube.com/watch?v=D-Xg6sALfA8
https://www.youtube.com/watch?v=bvhACGHhdGw
https://www.youtube.com/watch?v=k0lORzSHDp4
Thorim 25  (seems to have the correct damage)
https://www.youtube.com/watch?v=6Lvk8XReW1I  
https://www.youtube.com/watch?v=PNT9tSxFDeg  
https://www.youtube.com/watch?v=JLYZykH8eQs  
https://www.youtube.com/watch?v=qk7naVKc3kU 
Freya 10
https://www.youtube.com/watch?v=qTpDaZWOYeU
https://www.youtube.com/watch?v=S9cBUWnXn9I
https://www.youtube.com/watch?v=1leHv611P5g
Freya 25
https://www.youtube.com/watch?v=7wxv88pA3Ew   (Min 3:05)
https://www.youtube.com/watch?v=RRrnn2W871k
Mimiron 10
https://www.youtube.com/watch?v=VtkouIxacBI
https://www.youtube.com/watch?v=37U7-gBwpFs
https://www.youtube.com/watch?v=Vcqe4JBcQDo
https://www.youtube.com/watch?v=MHqySgIKWTY
Mimiron 25
https://www.youtube.com/watch?v=yePAlisR3Pk
https://www.youtube.com/watch?v=A3lUI3vCzbA
https://www.youtube.com/watch?v=W640JPmABjk
Vezax 10
https://www.youtube.com/watch?v=I_ss8HpM_X4
https://www.youtube.com/watch?v=LKRTgGI4bBI
https://www.youtube.com/watch?v=Gq2LVApE8zM
https://www.youtube.com/watch?v=TckFS3KtLFc
vezax 25
https://www.youtube.com/watch?v=ACDRJuARk2k
https://www.youtube.com/watch?v=lKm4g6pT15U
https://www.youtube.com/watch?v=nBVc6U6YRoM

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a character that can tank
2. .learn 25899  .learn 48470  .learn 16237  .learn 58753  .learn 48942  .modify hp 500000  .learn 62892 (Heal)
3. Get tank gear and reach a minimum of 24k armor without buff
4. Learn tank talents.
5. Go to Ulduar.
6. buff on me and spam ancestral fortitude (16237).
##### EXTRA NOTES:

It is very important to take damage with all the buffs on ... and this is because in raid these buffs are always active.
The buffs mentioned above reduce damage taken.
I recommend doing damage tests with 65% physical damage reduction
Don't forget the paladin's aura.
Spam Ancestral Fortitude.
![image](https://user-images.githubusercontent.com/37153212/95280443-9c563780-081a-11eb-8f9f-e31be22c9689.png)

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No

**Comment by Si1ker** [comment]
@Kitzunu @Knindzagxg

**Comment by Knindzagxg** [comment]
I will check and sort it later today mate.
Tho, damage on every boss is broken sadly.

**Comment by Si1ker** [comment]
@Knindzagxg  can you confirm the issue?

**Comment by Knindzagxg** [comment]
Just came home mate, not sure ill be able to check tonight.
But deffo tomorrow.

I'm pretty sure damage is weird, looks like its not updated towards 3.3.5

**Comment by Knindzagxg** [comment]
Should be fixed now.

Damage was ... Totally weird.
Some of them had 20ish k with 13 multiply which is just mad.

Check #3555
