### ISSUE TITLE
(Raid-Ulduar) Error with Iron Construct in the fight against ignis 25 players

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#3553]
##### CURRENT BEHAVIOUR:

In combat with Ignis in mode 25, the NPC Iron Construct ID: (33121)
When this NPC is set on fire, he gains a buff that currently stacks 20 times and causes the NPC to turn red.
https://www.wowhead.com/spell=65667/heat
https://www.wowhead.com/spell=62373/molten
##### EXPECTED BLIZZLIKE BEHAVIOUR:

It happens that the buff "Heat" should only accumulate 10 times for the other buff "Molten" to activate 
https://www.youtube.com/watch?v=nDzq__yQen0  (Min 1:10 ---   1:25)
https://www.youtube.com/watch?v=VtjYIM61B68   (Min 2:25  ---  2:40)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Change raid difficulty to 25 and enter Ulduar
2. .modify hp 500000  and .learn 62892
3. Find Ignis and start combat
4. Wait for Iron Construct and take it to the flames

##### EXTRA NOTES:

The bug only happens in the 25 version of Ulduar as in 10 player mode it works correctly.

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No

**Comment by Si1ker** [comment]
https://wow.gamepedia.com/Ignis_the_Furnace_Master_(tactics)

![image](https://user-images.githubusercontent.com/61223313/95337166-d05b4800-086e-11eb-84bb-eada096a9199.png)

**Comment by BarbzYHOOL** [comment]
why did it ever get set to 20 o_0

**Comment by Si1ker** [comment]
@BarbzYHOOL https://github.com/azerothcore/azerothcore-wotlk/pull/3554#issuecomment-704960236
