### ISSUE TITLE
[NPC][WOTLK] Argent Cannon

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#356]
This NPC should have 0 mana, not 1000.

Proof: https://www.youtube.com/watch?v=GyGhEKb7g9U&t=47s
![IMG3](http://i.imgur.com/14X7qrB.png)

Also you look like a muppet standing on the Vehicle so I believe the VehicleId is wrong at 246 -- 244 looks better but movement is odd (should be 360 degrees), anyone that can correct me? Also when you are at 1000 mana the text, "Reckoning Bomb READY! Purge the evil from this land!" should appear on your screen.

Before:
![IMG1](http://i.imgur.com/vVAq6pM.jpg)

after fix:
![IMG4](http://i.imgur.com/BZRxF0o.jpg)

![IMG2](http://i.imgur.com/BugUWZs.png)

**Comment by starrheld** [comment]
Fix for mana:

```sql
UPDATE `creature` SET `curmana`=0 WHERE `id`=30236;
```

**Comment by Helias** [comment]
Open PR and in the PR quote this issue.

Anyway, I so that you are importing fixes from rushor fixes, good job

**Comment by starrheld** [comment]
Any feedback on this @talamortis

**Comment by talamortis** [comment]
im on holiday maate so i cant test
