### ISSUE TITLE
(Raid-Ulduar) Stone Nova does not stack.

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#3564]
##### CURRENT BEHAVIOUR:

In the combat against Kologarn in its 25 player mode, when one of his arms is destroyed, the npc Rubble ID: 33768 appears.
The problem is when these NPCs cast their Stone Nova ID: 63978 ability the debuff is not stacking if another Rubble applies the debuff.
![WoWScrnShot_101020_184359](https://user-images.githubusercontent.com/37153212/95667236-b187da80-0b28-11eb-9415-549db14b8b22.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Stone Nova has to stack despite another Rubble casting the ability.
https://www.youtube.com/watch?v=9bFX0kIarM0  (Min 1:55 -- 2:07) 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Ulduar 25.
2. .npc add 33768 (create at least 2)
3. Start combat and observe.

##### EXTRA NOTES:

In 10-player mode, Rubble NPCs do not cast this ability.
https://www.youtube.com/watch?v=RytKo-x9xNU

https://wotlkdb.com/?spell=63978
https://www.wowhead.com/spell=63978/stone-nova
https://www.wowhead.com/npc=33768/rubble
https://wotlkdb.com/?npc=33768

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No.

**Comment by Si1ker** [comment]
Same behavior as in #3513  under "KNOWN ISSUES AND TODO LIST:"
