### ISSUE TITLE
(Raid-Ulduar) bug in iron assembly

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#3565]
##### CURRENT BEHAVIOUR:

In the combat against the iron assembly when defeating one of the 3 bosses, the defeated boss grants a buff to his companions but when you defeat 2 of the 3 bosses the buff supercharge ID: 61920 is being applied incorrectly accumulating 2 times the same buff.
This issue occurs in the 10 and 25 player version of Ulduar
![WoWScrnShot_101020_190508](https://user-images.githubusercontent.com/37153212/95667553-5ad0cf80-0b2d-11eb-9636-d17f4807b257.jpg)
![WoWScrnShot_101020_190558](https://user-images.githubusercontent.com/37153212/95667557-615f4700-0b2d-11eb-8a02-dfc8d01e7eff.jpg)
![WoWScrnShot_101020_190643](https://user-images.githubusercontent.com/37153212/95667559-6623fb00-0b2d-11eb-9692-63c9c23e3e4f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Supercharge should accumulate a maximum of 2 times.
https://www.youtube.com/watch?v=7J0tTzbN70k  (Min 3:40)     
https://www.youtube.com/watch?v=7oMMK2KLhhg (Min 4:15)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .cheat god
2. .go c 136421
3. Defeat 2 of the 3 bosses.

##### EXTRA NOTES:

https://www.wowhead.com/spell=61920/supercharge

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No.

**Comment by aradep** [comment]
I think this is caused because the auras come from different NPCs.  Functionally the same, but yea it should stack to 2.
