### ISSUE TITLE
[BUG/QUEST] First quest of Lv1 start zones cannot be accepted

### ISSUE THREAD

**Issue by awedy01** [azerothcore/azerothcore-wotlk#3566]
CURRENT BEHAVIOUR:
The first quest of Lv1 start zones such as Dwarven Outfitters quest at Dwarf start zone, (also tested human start zone) cannot be accepted IF the following setting is enabled:
Quests.IgnoreAutoAccept
I am not sure about all quests, but i know death knight starter quest work if its enabled.

EXPECTED BLIZZLIKE BEHAVIOUR:
The reason of turning auto-accept off is the bug what cause the quest window to dont close upon accepting/completing quest.
Expectation to be able to accept all quests by myself instead of auto accept.

STEPS TO REPRODUCE THE PROBLEM:
 - Which commands to use? Which NPC to teleport to?
No commands, just create a new character (100% sure at human & dwarf zone)

 - Do we need to have debug flags on Cmake?
Not sure about this one
 - Do we need to look at the console while the bug happens?
No
 - Other steps
1. Edit worldserver.conf
2. Add "Quests.IgnoreAutoAccept = 1"
3. Create a new dwarf OR human character(probably the others bugged aswell)

AC HASH/COMMIT:
#Not sure which u need so here is the whole git log
commit 4e9e915a1d7c0f79ffcbd365aa3af6aa36d4f085 (HEAD -> master, origin/master, origin/HEAD)
Author: Andrius Peleckas <32540208+sanctum32@users.noreply.github.com>
Date:   Sun Oct 4 11:13:06 2020 +0200

    fix(Core/Misc): fixed NOPCH build (#3448)

commit b67c30e26306ce82cae1919c3058ce59a70311af
Author: Patrick Lewis <pat@lo5t.com>
Date:   Sat Oct 3 07:25:54 2020 -0700

    fix(Core/Script) npc Tom Hegger target player for aggro text (#3444)

commit 4290a129caa380359c8c672f1c637844448eafa2
Author: Kitzunu <24550914+Kitzunu@users.noreply.github.com>
Date:   Fri Oct 2 12:13:15 2020 +0200

    fix(Issue/Config): correct links (#3423)

commit e9bce8a0f4544c87a6ce00d7123a634802f12800
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Thu Oct 1 09:43:52 2020 +0000

OPERATING SYSTEM:
Ubuntu 20.04 LTS

**Comment by aradep** [comment]
Starting quests being auto-accept is blizzlike.
https://wowwiki.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)#Quests

However, you can remove the auto-accept flags yourself with this query
`UPDATE `quest_template` SET `flags` = (`flags`-524288) WHERE `flags` >= 524288 AND `ID` IN (6,7,8,15,18,21,33,54,179,363,364,376,380,381,382,383,456,458,783,788,789,790,792,794,804,805,1516,1517,1518,2158,2160,2161,3082,3084,3085,3086,3102,3901,3902,3903,3904,3905,4402,4495,4641,5441,6394,6395,8325,9279,9280,9283,9287,9289,9293,9294,9303,9305,9309,9311,9312,9313,9314,9409,9798,9799,10302,10303);`
