### ISSUE TITLE
Spell: Holy Nova (priest)

### ISSUE THREAD

**Issue by NiganNi** [azerothcore/azerothcore-wotlk#3567]
Description:
Does not work. When used, there is no graphic design, no mana spent, can be used indefinitely.

Current behaviour:
![Holy Nova](https://user-images.githubusercontent.com/61392055/95677816-ddf73180-0bd0-11eb-8edb-275e428a8e11.jpg)

2020-10-06 15:23:45 AzerothCore rev. 1910b4ab35bf+ 2020-09-26 14:46:27 +0200 (master branch) (Win64, Release) (worldserver-daemon)
Operating system: win х64

**Comment by aradep** [comment]
It appears you are using the wrong spell (https://wotlkdb.com/?spell=23455)
The correct rank 1 Holy Nova spell is https://wotlkdb.com/?spell=15237

**Comment by NiganNi** [comment]
**aradep** thank you for your answer, but I already solved the problem yesterday. You said it right! This was due to the mod-learn-spells mod.
