### ISSUE TITLE
is from an incompatible clientversion. Please recreate using the mapextractor. Map file '/home/game-server/tools/data/maps/0004331.map' Че за дичь вы пилите это ядро и такая хуйня пиздец

### ISSUE THREAD

**Issue by ArthasCore** [azerothcore/azerothcore-wotlk#357]
**Description**:

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ArthasCore** [comment]
/usr/bin/ld: ../../../worldengine/nucleus/src/libshared.a(Util.cpp.o): неопределённая ссылка на символ «pthread_getspecific@@GLIBC_2.0»
//lib/i386-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_generator.dir/build.make:197: ошибка выполнения рецепта для цели «modules/acore/extractors/mmaps_generator/mmaps_generator»
make[2]: *** [modules/acore/extractors/mmaps_generator/mmaps_generator] Ошибка 1
make[2]: Цель «modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_generator.dir/build» не была пересобрана из-за ошибок.
CMakeFiles/Makefile2:1034: ошибка выполнения рецепта для цели «modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_generator.dir/all»
make[1]: *** [modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_generator.dir/all] Ошибка 2

**Comment by ArthasCore** [comment]
В пизду ваше ядро целый день потратил на сбор этого говна !

**Comment by talamortis** [comment]
template not filled out correctly.
