### ISSUE TITLE
(Raid-Onyxia Lair) bug in Onyxia's Lair

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#3570]
##### CURRENT BEHAVIOUR:

When you are in the fight against Onyxia in the 25 player mode, upon reaching phase 2 Onyxia summons Onyxian Whelp
 ID: 11262 // 36566.
Onyxia in 25 player mode summons the Onyxian Whelp that belongs to 10 player mode.
![WoWScrnShot_101220_150756](https://user-images.githubusercontent.com/37153212/95787544-588e8280-0c9f-11eb-8042-4a29ef8ce04b.jpg)

The same thing happens if someone falls into the onyxia eggs in 25 player mode, summons the Onyxian Whelp that belong to 10 player mode.
![WoWScrnShot_101220_151054](https://user-images.githubusercontent.com/37153212/95787505-43b1ef00-0c9f-11eb-9224-47610a59328b.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Onyxian Whelp ID 36566 should be summoned from 25 player mode

##### STEPS TO REPRODUCE THE PROBLEM:

1. .modify hp 500000 and .learn 62892
2. Switch to 25 player mode and type .go c onyxia
3. reach phase 2 and when the Onyxian Whelp are summoned write .npc info or go to the onyxia eggs invoke the Onyxian Whelp and write .npc info

##### EXTRA NOTES:

--

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No.

**Comment by Si1ker** [comment]
Read how the IDs work at https://www.azerothcore.org/wiki/creature_template#difficulty_entry_x
Under the category "difficulty_entry_x"

The NPC 11262 pulls the data from the ID 36566 when in 25-man mode, it is working as planned.


10 mode:
![image](https://user-images.githubusercontent.com/61223313/95850870-aee6da00-0d0e-11eb-9e5e-1a7cfacdb758.png)


25 mode:
![image](https://user-images.githubusercontent.com/61223313/95850878-b60de800-0d0e-11eb-8846-19eb6aa52805.png)
