### ISSUE TITLE
Gems in [Eternal Belt Bucket] socket not counting towards meta gem requirements.

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3598]
##### CURRENT BEHAVIOUR:
While the prerequesites show as fulfilled for a meta gem, the gems in a prismatic slot, which was created by an [Eternal Belt Buckle](https://wowgaming.altervista.org/aowow/?item=41611), still do not count towards the activation. Tested with Austere [Earthsiege Diamond](https://wowgaming.altervista.org/aowow/?item=41380).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
All gems in all slots should count towards the activation for real, instead of only showing as fulfilling the requirement but not providing the meta gems stats.

##### STEPS TO REPRODUCE THE PROBLEM:
1.) Create a paladin, make it level 80, teach it plate and have it wear [Thane's Tainted Greathelm](https://wowgaming.altervista.org/aowow/?item=39395). Attach an [Austere Earthsiege Diamond](https://wowgaming.altervista.org/aowow/?item=41380)
.level 80
.learn 750
.additem 39395
.additem 41380

2.) Wear another item with 2 sockets to cover one part of the Meta gems requirements, like [Chestguard of the Exhausted](https://wowgaming.altervista.org/aowow/?item=40279) and fill it with 2 blue gems like [Lustrous Chalcedony](https://wowgaming.altervista.org/aowow/?item=39927)
.additem 40279
.additem 39927 2

3.) Wear a Belt like [Ancient Aligned Girdle](https://wowgaming.altervista.org/aowow/?item=37241) and attach an [Eternal belt Buckle](https://wowgaming.altervista.org/aowow/?item=41611) creating a Prismatic Socket.
.additem 37241
.additem 41611

4.) Check the Meta gems requirements with only the above items equipped which should be unfulfilled. Also remember the armor value and stamina value. Then attach a gem like [Regal Twilight Opal](https://wowgaming.altervista.org/aowow/?item=40031), which counts as a red one to the belt. 
.additem 40031

5.) Again look at the Meta gems requirements. They show up as fulfilled. Also look at the armor and stamina. Even though the meta shows as activated, the bonusses do not apply.

##### EXTRA NOTES:
A blacksmiths "Socket Bracer" / "Socket Gloves" prismatic sockets are not affected by this.

##### AC HASH/COMMIT:
c208a1219b54fa52501d86446a4a30edb51d0d2d
from June 3rd

##### OPERATING SYSTEM:
OS: Ubuntu Server 20.04

##### MODULES:
none

##### OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by BarbzYHOOL** [comment]
very good issue reported, plz test and thank the dev here :) https://github.com/azerothcore/azerothcore-wotlk/pull/3643
