### ISSUE TITLE
Command .character level - Server Crash

### ISSUE THREAD

**Issue by Koschull** [azerothcore/azerothcore-wotlk#3603]
Hi, when i try to use gm (console) command on the server console (character level Test 20) server instantly crash.
Newly created character named Test level 1 after cinematic waiting in-game and type command to the server console and crash.

AzerothCore rev. 90a10a9b88fe+ 2020-10-22 08:19:12 +0000 (master branch) (Win64, Release) (worldserver-daemon)
Using modules: (solo-lfg, solocraft, ah-bot)

On the older version this command works like a charm. Compile with  same machine, same tools and same process, but i use all version history git repo, so i can't tell you what is that version (older) .

AzerothCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release) (worldserver-daemon)

**Comment by iThorgrim-Hub** [comment]
Crash with the same command with AC https://github.com/azerothcore/azerothcore-wotlk/commit/90a10a9b88febbd0cab9809f9772833293ddec16

**Comment by Ramys** [comment]
confirmed. besides the accident, i had a roolback.

**Comment by iThorgrim-Hub** [comment]
This commit made crash : https://github.com/azerothcore/azerothcore-wotlk/commit/d5bb6ba1c46141f0fba5b130f9360d4df6ff712a

I tested the commit before him and it works perfectly.

The commit https://github.com/azerothcore/azerothcore-wotlk/commit/d5bb6ba1c46141f0fba5b130f9360d4df6ff712a modify send mail system and the crash server appaear when the server send a mail to the player.

**Comment by Koschull** [comment]
It is true. When i set level below 20 (not sent mail about riding) works well otherwise level 20+ crash.

**Comment by arielcami** [comment]
Confirmed, crash+rollback.
I'm using an old build I had in backup

**Comment by BarbzYHOOL** [comment]
please, everyone here test this as soon as possible: https://github.com/azerothcore/azerothcore-wotlk/pull/3604

**Comment by Ramys** [comment]
I will test and post the result.

**Comment by Ramys** [comment]
@BarbzYHOOL  
Thanks for the support, This fix mentioned works perfectly
I recompiled it and it doesn't fall anymore!

**Comment by Koschull** [comment]
Well done! Great job all and also thanks.

**Comment by BarbzYHOOL** [comment]
No, we close it (automatically) when it's merged and please, leave a comment on the Pull Request I linked to thank the developer! ;)

**Comment by Koschull** [comment]
OK. Sorry about that. I remember now. :)
