### ISSUE TITLE
[Quest] Battle of the Crimson Watch

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#3606]
##### CURRENT BEHAVIOUR:

After accepting the quest ID 10781, the mobs appear. After you kill them, nothing happens and the quest cannot be completed. 

- All  texts are missing
- Wave 2, 3 and 4 is missing

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Watch https://www.youtube.com/watch?v=tiwpKqlLGaM&ab_channel=WilliamPritchard

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go -4616.399902 1391.324707 139.923584 530
2. .q a 10781
3. Fight against the 1st wave. After they died, nothing happens

##### AC HASH/COMMIT:

AzerothCore rev. ab5933e 2020-10-17 14:59:22 +0200 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro x64

##### MODULES:

- Ah-Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max Skill on levelup

**Comment by Voxstrasza** [comment]
confirmed

**Comment by Quickson** [comment]
I cannot reproduce this on rev. 0bee5af962c0 2020-11-16 15:21:58 +0000 (master branch) (Win64, RelWithDebInfo)
All waves is spawned.

Quest i start from Crystal Prison, not by command

**Comment by LukasVolgger** [comment]
@Quickson ty for your test. I didn't use the command in first place, just to reproduce. Can you test if it's working too with the command or you already did?

**Comment by Quickson** [comment]
@LukasVolgger when to accept the quest through ".q a 10781" nothing happens. Even the first wave does not spawn. 

I looked at the code and found that the script for this quest starts in the [go_crystal_prison :: OnQuestAccept](https://github.com/azerothcore/azerothcore-wotlk/blob/42abbc9e4aa6f462596b88ea79232eff46d26b4c/src/server/scripts/Outland/zone_shadowmoon_valley.cpp#L1577) handler. 
If start through a command, then we don't get into this handler

**Comment by LukasVolgger** [comment]
@Quickson thank you for your efforts and research! In this case the issue can be closed as the quest is working without any gm commands
