### ISSUE TITLE
[Quest] Cohlien Frostweaver

### ISSUE THREAD

**Issue by Gierlappen** [azerothcore/azerothcore-wotlk#3609]
##### CURRENT BEHAVIOUR:

The quest Id 10307 cannot be completed after the task is done correctly. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After placing the hat in the footlocker the quest should be completed. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go 2203.750000 2409.765137 108.537361 530
2. .additem 29236 and start quest 10307
3. place the item and see that the quest is not completed

##### AC HASH/COMMIT:

AzerothCore rev. ab5933e 2020-10-17 14:59:22 +0200 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro x64

##### MODULES:

- Ah-Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max Skill on levelup

**Comment by mamartel** [comment]
You have to use (right-click) the hat to do the objective of the quest.
Not bugged.

**Comment by mamartel** [comment]
![Cohlien Frostweaver (1)](https://user-images.githubusercontent.com/1738891/97787678-24193280-1b8a-11eb-8468-d3bd13898ae0.png)
![Cohlien Frostweaver (2)](https://user-images.githubusercontent.com/1738891/97787679-24b1c900-1b8a-11eb-9bba-e1a3176ab64b.png)
![Cohlien Frostweaver (3)](https://user-images.githubusercontent.com/1738891/97787680-254a5f80-1b8a-11eb-8ebb-9a57386100b0.png)
![Cohlien Frostweaver (4)](https://user-images.githubusercontent.com/1738891/97787681-25e2f600-1b8a-11eb-9c36-9635ade26866.png)
![Cohlien Frostweaver (5)](https://user-images.githubusercontent.com/1738891/97787683-267b8c80-1b8a-11eb-96ae-463dfdfe254b.png)
![Cohlien Frostweaver (6)](https://user-images.githubusercontent.com/1738891/97787685-27acb980-1b8a-11eb-8e4e-a3ba2d45817d.png)
![Cohlien Frostweaver (7)](https://user-images.githubusercontent.com/1738891/97787687-28455000-1b8a-11eb-9045-5b375a6d054c.png)

**Comment by Gierlappen** [comment]
Then it hast to be an other Problem.

Closed.

**Comment by BarbzYHOOL** [comment]
yep, it works fine however i could attack the gnome after he puts his hat, weird
