### ISSUE TITLE
[DUNGEON][WOTLK] Halls of Stone

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#361]
@Talamortis 
-
Issues in **Halls of Stone**

- [ [BOSS] Maiden of Greef - Casts her Black Area of Effect below the surface/ground.] 

Currently:
![MAIDEN1](http://i.imgur.com/7D1LIhj.jpg)

How it should look **(sorry for the bad quality)**:
![MAIDEN2](http://i.imgur.com/FD0tZWe.png)

- [NPC] Brann Bronzebeard - Missing his gossip before last boss at the door, he should stop and you are supposed to talk to him and ask him to open the door. Now he's just running towards last boss and the door is opened automatically.

How it should look:
![BRANN](http://i.imgur.com/vd5qumD.png)

**Comment by ShinDarth** [comment]
good job @talamortis , that was very fast :D

**Comment by talamortis** [comment]
Yeah that thanks getting used to this coding now



Sent from my Samsung Galaxy S7 - powered by Three

-------- Original message --------
