### ISSUE TITLE
Created items without creatorGuid in DB

### ISSUE THREAD

**Issue by arielcami** [azerothcore/azerothcore-wotlk#3631]
**Created items without creatorGuid in DB**

**CURRENT BEHAVIOUR:**
Created Glyphs and Trade Goods in general (Smelted bars, Leather, Engineering parts, etc), 
are created with the in-game 'created by x' label missing.

Created items show '0' in column 'creatorGuid' in 'item_instance' DB and every player =/= 0.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Every created item must show its creator label.

**STEPS TO REPRODUCE THE PROBLEM:**
-Learn mining skill and smelt copper ores. Copper bars must show the creator label.
-Learn Engineering and create any Part.
-Learn Inscription and create any glyph.

**Important**: It is NOT the case with created Armor and Weapons.

AzerothCore rev. 7a9a0892db33 2020-10-25 09:12:33 +0000 (master branch) (Win64, Release) (worldserver-daemon)

**Operating System**
Windows 10 Professional (Version 10.0, Build 19041)

**MODULES:**
AH-Bot
Transmog
Eluna Engine

//

**Comment by BarbzYHOOL** [comment]
@arielcani can u write the commands to reproduce the issue please? looks like a serious issue though

**Comment by arielcami** [comment]
@BarbzYHOOL 

.learn 2575
.gobject add 1685
.additem 2770

Proceed to create a Copper bar.
The copper bar you just created doesn't show your name on it.

It happens with trade goods, but it does not with Amor - Weapons - Gems.

**Comment by placemolle** [comment]
This is not a bug. Those kind of items don't have a signature on official servers.
This is from a [video on Youtube](https://www.youtube.com/watch?v=zr5FPHLErFQ) of someone crafting a steel bar, and you can see it doesn't have a signature:
![image](https://user-images.githubusercontent.com/73811101/98332678-1f5edf00-1fcd-11eb-8ccd-9522a0581520.png)
