### ISSUE TITLE
Sartharion OS10 / 25 Not Pull Dragons

### ISSUE THREAD

**Issue by Racknar0** [azerothcore/azerothcore-wotlk#3633]
Sartharion OS10 / 25 Not Pull Dragons

SMALL DESCRIPTION:

When you pull sartharion https://www.wowhead.com/npc=28860/sartharion without killing the 3 dragons they should come down and attack, but at no time does.

 EXPECTED BLIZZLIKE BEHAVIOUR:

the dragons must come down to fight

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Go to Sartharion OS 
2.  the battle begins
3.  Slowly come to life at no time the dragons come down. 

BRANCH(ES):
master

AC HASH/COMMIT:
OPERATING SYSTEM:
Ubuntu

MODULES:
None

OTHER CUSTOMIZATIONS:
None

**Comment by Si1ker** [comment]
@racknarox  add hash/commit, there is a template for a reason and is not decoration.


Confirmed, #3426 caused.
Sartharion is useless, only event taking place are lava waves. Moreover, after a reset, drakes around die for 5 seconds and then go back to life.
cc @sanctum32

**Comment by sanctum32** [comment]
will open pr soon to correct behavior, anyways code of Sartharion is crap anyways but sure sure...

**Comment by sanctum32** [comment]
https://github.com/sanctum32/azerothcore-wotlk/tree/sartharion_revamp work is in progress, whole original script is horrible...

**Comment by FrancescoBorzi** [comment]
thanks @sanctum32 !

**Comment by BarbzYHOOL** [comment]
test this guys https://github.com/azerothcore/azerothcore-wotlk/pull/3634
