### ISSUE TITLE
Server can not started if player death.

### ISSUE THREAD

**Issue by wplatform** [azerothcore/azerothcore-wotlk#3640]
##### CURRENT BEHAVIOUR:

The world server can not be started.

Loading pet level stats...
>> Loaded 2720 level pet stats definitions in 4 ms

Loading Player Corpses...

/opt/azerothcore/src/server/game/Entities/Object/Object.cpp:2117 in GetBaseMap ASSERTION FAILED:
  m_currMap

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The world server can be started.

##### STEPS TO REPRODUCE THE PROBLEM:

I do not know how to reproduce the problem.

##### EXTRA NOTES:

/opt/azerothcore/src/server/game/Entities/Object/Object.cpp:2117 in GetBaseMap ASSERTION FAILED:
  m_currMap

+------------+------+---------+---------+---------+-------------+-------+-----------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+---------+-------+----------+------------+------------+------------+
| corpseGuid | guid | posX    | posY    | posZ    | orientation | mapId | phaseMask | displayId | itemCache                                                                                                                                                                 | bytes1    | bytes2   | guildId | flags | dynFlags | time       | corpseType | instanceId |
+------------+------+---------+---------+---------+-------------+-------+-----------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+---------+-------+----------+------------+------------+------------+
|         33 |    3 | 736.883 | 28.3288 | 430.697 |     6.09419 |   658 |         1 |     15475 | 16828423 33564284 50381121 67139469 83942585 100720226 117497476 134268997 151046843 167829043 184581282 184598605 201383378 201383106 268466587 285277412 0 0 318821279  | 100731392 | 50331652 |       1 |    12 |        0 | 1604243624 |          1 |          0 |
+------------+------+---------+---------+---------+-------------+-------+-----------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+---------+-------+----------+------------+------------+------------+

##### AC HASH/COMMIT:

commit 85e0a3a71edf38c295120985fe13fd5be627a20b (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Sun Nov 1 16:41:56 2020 +0000

    chore(DB): import pending SQL update file

    Referenced commit(s): f5445a9385cc6cd8c7a229fbe9e40ebbc2286227

commit f5445a9385cc6cd8c7a229fbe9e40ebbc2286227
Author: Kitzunu <24550914+Kitzunu@users.noreply.github.com>
Date:   Sun Nov 1 17:40:51 2020 +0100

    fix(DB/Quest): Rifle the Bodies (#3574)

commit ec150e16805df5531557079c72861c49a9b9a0b3
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Sun Nov 1 10:02:10 2020 +0000

    chore(DB): import pending SQL update file

    Referenced commit(s): 155e634b93276cf967e15127c1833b5b5906942c

##### OPERATING SYSTEM:

 Ubuntu 18

##### MODULES:

no

**Comment by Goatform** [comment]
@wplatform , could you test something like this: https://github.com/Goatform/azerothcore-wotlk/commit/efb550251589a1167bbe658d649444f4c5619037

**Comment by wplatform** [comment]
It is obviously.

/opt/azerothcore/src/server/game/Entities/Object/Object.cpp:2117 in GetBaseMap ASSERTION FAILED:

assert m_currMap.

so the m_currMap is null.

**Comment by Kitzunu** [comment]
I could not reproduce this on a 70 commit old core, I will try with the current core later today

**Comment by Goatform** [comment]
That does not help at all. If you post a crash log then it would make some sense because then we could know a place where it occurred. You may have custom changes on top of that.

**Comment by Kitzunu** [comment]
I cannot reproduce this on https://github.com/azerothcore/azerothcore-wotlk/commit/2e298e7fc900

**Comment by Si1ker** [comment]
cannot repro on c32283f and never provided info requested nor crash log.
