### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by blacknightt1** [azerothcore/azerothcore-wotlk#3642]
Hi,
    I'm going to command players
    Players can come to my target area and do it themselves
    With command .home

    And all players can come to that area, wherever they are
    With command .home

    View my area:

    Map: 1 (Kalimdor) Zone: 331 (Ashenvale) Area: 414 (The Zoram Strand) Phase: 4294967295
    X: 2975.360107 Y: 2566.550049 Z: 150.917999 Orientation: 4.055010
    grid[37,36]cell[4,6] InstanceID: 0
    ZoneX: -15.026882 ZoneY: 44.164070
    GroundZ: 134.480469 FloorZ: 150.917725 Have height data (Map: 1 VMap: 1 MMap: 1110484994)

    I use azerothcore

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/How-to-ask-for-help
