### ISSUE TITLE
Stats Limits is missing

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#3648]
Current behaviour: Stats Limits
Expected behaviour: players stat limit 75%
Steps to reproduce the problem:
1.update item 10000 stat
.additem
Players Dodge <100%
Also, I found a trinitycore commit that was deleted. Is that intentional? https://github.com/TrinityCore/TrinityCore/commit/e18571346400281861490b36c4d35a381bc80dd8
Branch: Master.
AC hash/commit: https://github.com/azerothcore/azerothcore-wotlk/commit/2e809055a07e5965f832a989839d4758d734a5a4
Operating system: Linux, Ubuntu 14.04 and Windows 7.
Modules: No.
Other Customizations: No.

**Comment by Kitzunu** [comment]
That commit would have been for Mop

**Comment by placemolle** [comment]
I imported the referenced commit [here](https://github.com/placemolle/azerothcore-wotlk/tree/fix-3648).
But before creating a pull request, i'm wondering if this is the correct Blizz-like behavior.
Right now, dodge/parry/block/crit are capped at 95%, but the caps are disabled by default.
If this is the right behavior for WOTLK, why disabled by default?

**Comment by Helias** [comment]
@placemolle, unfortunately, I don't know the answer, but I think that you can open the PR and may create a discussion there ;-)
