### ISSUE TITLE
[Install] Worldserver.exe and Authserver.exe missing

### ISSUE THREAD

**Issue by t0mmy86** [azerothcore/azerothcore-wotlk#365]
Hello,

I got a big problem. Visual Studio doesn't create the worldserver.exe/.conf and authserver.exe/.conf in \bin\release\ folder.

I followed the official installation guide and already tried the installation in two different folders, one with 'debug' and one with 'release'. The result is the same.

Used software:

- CMake 3.7.2
- VS Community 2015 Update 3
- Git

**Current behaviour**: Got the files via Git ("git clone https://github.com/azerothcore/azerothcore-wotlk.git azerothcore") and set up CMake like the installation guide describes. I checked SCRIPTS, SERVERS, TOOLS, USE_COREPCH, USE_MYSQL_SOURCES, USE_SCRIPTCH. It' was generated with Visual Studio 14 2015 Win64. I got the OpenSSL error but corrected the folders in the advanced options.

After that I started the AzerothCore.sln, chose "release" and built the ALL_BUILD. At the end of the build VS tells me, that 19 were successfull and 4 got errors. These errors are in connection with the missing file "..\..\modules\worldengine\deps\mysqllite\Release\libmysql.lib". But I think that's okay, because it needs to be added manually if you follow the installation guide!?

**The result is that i only got 4 files in the release folder:**

1. ace.dll
2. mapextractor.exe
3. vmap4assembler.exe
4. vmap4extractor.exe

I couldn't find a single solution via google. It seems everyone got the files except of me :/
Anyone can help me? 

Thanks in advance. If you need further information please tell me.

**Comment by talamortis** [comment]
can you please send a screen shot on what files it created after debug?

**Comment by t0mmy86** [comment]
Wow, that was a fast reply. Thank you. 

The debug folder contains the following files:

![grafik](https://cloud.githubusercontent.com/assets/25536071/22606081/bd6fa6a2-ea52-11e6-87f6-c0c4e09c6553.png)

**Comment by talamortis** [comment]
strange, is it possible for you to PM me on gitter and i can try help you with it

**Comment by talamortis** [comment]
problem fixed 👍
