### ISSUE TITLE
[Quest] The Storm King's Vengeance

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#3654]
##### CURRENT BEHAVIOUR:

Quest ID 12919 is totally bugged. After accepting it the following issues are there:

- You cannot use any spells of the vehicle
- You cannot leave the vehicle
- You have to ALT+F4 and release the vehicle to continue with gameplay because your'e in a phase

##### EXPECTED BLIZZLIKE BEHAVIOUR:

YouTube Video from 2008: https://www.youtube.com/watch?v=Vjy4V6nBo44&ab_channel=wtbblue

- You should be able to use the spells from the vehicle
- You should be able to leave the vehicle 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go 5791.343750 -1583.743774 234.912033 571
2. .q rem 12919 & .q a 12919
3. talk to "Gymer" to mount him and see the issues

##### AC HASH/COMMIT:

AzerothCore rev. 9a9308afd16a+ 2020-11-04 16:30:40 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro x64

##### MODULES:

- Auctionhouse Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:

None

**Comment by Hacaw** [comment]
CONCLUSION
---
I can not reproduce this issue.
I can use all his abilities and it look like all of them do damage.
I can unmount without trouble.

@LukasVolgger can you please, recheck ?

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Just rechecked and everything is fine. Thx @Hacaw !
