### ISSUE TITLE
Resistances in Pve and Pvp too high?!

### ISSUE THREAD

**Issue by Algorak** [azerothcore/azerothcore-wotlk#3659]
![InkedWoWScrnShot_103120_214456_LI](https://user-images.githubusercontent.com/73311832/98449541-bf834800-2134-11eb-8e30-f6049e159e89.jpg)
![WoWScrnShot_110520_122652](https://user-images.githubusercontent.com/73311832/98449550-c90cb000-2134-11eb-90f6-ab0e5d1b60da.jpg)
Here the weapon enchantment was resisted by the death knight

Resistance in Pve and Pvp too high or wrong!

##### CURRENT BEHAVIOUR:

Resistance in Pve and Pvp too high Spells are sometimes 100% resisted as a player or Npc (Bosses)

I actually play all magic classes and also melee classes and I noticed the magic being resisted, whether in raids, instances or open world (Pvp).

I have 135-140 spell penetration as a warlock and players without Pvp equipment resist my spells, even though they are low level or are in the same level, it makes no difference whether they are wearing Pvp or Pve equipment. The general values ​​are just completely wrong in my opinion and that cannot be completely resisted by Npcs in raids spells, even though I have 18% hit. We have all the raids support with us.
As a tank, I also partially resist spells from bosses like Sindragosa, Lichking, and many other bosses.

I hope you can find something there or prove the opposite to me, but I haven't encountered such problems on any server

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I've played a lot of wow and haven't seen any server that you can resist in PvE. And I also believe that spells can only be weakened but never 100% resisted.
https://wowwiki.fandom.com/wiki/Resistance?oldid=2142719 <-----------

##### STEPS TO REPRODUCE THE PROBLEM:

1. There are no processes is simply Rnd. Spells are resisted and randomly.

##### EXTRA NOTES:

Only on this core on many others have never had the problem.

I noticed it when I played my Tank DK and then it was resisted several times IT death grip and icy chains. I have 9% Hit Max Raid Support and have looked in the process - many spells are completely resisted.

I've been looking at this for a long time, our DEV thinks it's normal! But I'm sure the magic in Pve can never be completely resisted! Unless the boss did, resist these spells! But in Wotlk hardly any boss has this resistance. Let alone Npc's in the same level, I would be really grateful if you could have a look over it.

##### AC HASH/COMMIT:

90a10a9b88febbd0cab9809f9772833293ddec16

##### OPERATING SYSTEM:

Win 10

##### MODULES:

no

##### OTHER CUSTOMIZATIONS:

no

**Comment by Visionre** [comment]
Screen is from frostmourne-wow, which has custom modifications.
Do you really want to allow issues from servers that have no clean core?
How are we supposed to reproduce this? The error can be caused by their changes.

**Comment by Si1ker** [comment]
@Algorak now people have to guess how to repro? it's a new challenge or something?

![image](https://user-images.githubusercontent.com/61223313/98449830-dc038e00-20fc-11eb-85ca-43e5731861f7.png)

**Comment by Algorak** [comment]
> @Algorak jetzt müssen die Leute raten, wie man Repro macht? Es ist eine neue Herausforderung oder so?
> 
> ![Bild](https://user-images.githubusercontent.com/61223313/98449830-dc038e00-20fc-11eb-85ca-43e5731861f7.png)

sorry but there are no processes it just happens when casting on whatever Npcs

**Comment by Algorak** [comment]
> Der Bildschirm stammt von frostmourne-wow und verfügt über benutzerdefinierte Modifikationen.
> Möchten Sie wirklich Probleme von Servern zulassen, die keinen sauberen Kern haben?
> Wie sollen wir das reproduzieren? Der Fehler kann durch ihre Änderungen verursacht werden.
