### ISSUE TITLE
People Request Mall

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#366]
I know this is a blizzlike thing but i have had a few people ask me to create a mall for them: i am willing to do that so if anyone wants to request a vendor please let me know, i am going to use this as a tracking.

Mall Vendors:

- [ ] Tier 10 - Cloth
- [ ] Tier 10 - Leather
- [ ] Tier 10 - Mail
- [ ] Tier 10 - Plate
- [ ] Tier 9 - Cloth
- [ ] Tier 9 - Leather
- [ ] Tier 9 - Mail
- [ ] Tier 9 - Plate

**Comment by Mowhok** [comment]
Yes please :D

**Comment by Mowhok** [comment]
i have some suggestions xD

**Comment by STARRHELD** [comment]
As long as it’s not implemented in the core it’s all good. Since it’s not Blizzlike.
