### ISSUE TITLE
[Quest] Rampage

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#3660]
##### CURRENT BEHAVIOUR:

During the quest ID 12721 you have to free "Akali" from his chains. 

- After you unlocked all 4 chains the objective isn't completed 

 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

YouTube Video from 2008: https://www.youtube.com/watch?v=po3h51bcuao&ab_channel=wtbblue

- The objective should be completed after you unlocked all 4 chains

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go 6881.901367 -4571.919434 442.405487 571
2. .q rem 12721 & .q a 12721
3. unlock all 4 chains
4. the quest objective doesn't count

##### AC HASH/COMMIT:

AzerothCore rev. 9a9308afd16a+ 2020-11-04 16:30:40 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro x64

##### MODULES:

- Auctionhouse Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:

None

**Comment by Hacaw** [comment]
CONCLUSION
---
I can not reproduce this issue.
After breaking 4 chains & a couple of seconds, some phase or event is starting he gets bigger and is attacked by lots of drakkari, until it's killed by the prophet. (similar to the video)

Could it be that I have the Warmane client or it doesn't matter?

![image](https://user-images.githubusercontent.com/6963500/101671416-24480000-3a5d-11eb-99a2-7bd075857bfd.png)


TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Same here, tested again and it's working. Thx again @Hacaw !
