### ISSUE TITLE
[Spell] non-existing spell 39805

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#3664]
##### CURRENT BEHAVIOUR:
- Spell info correction specified for non-existing spell 39805

https://github.com/azerothcore/azerothcore-wotlk/blob/6e7fac81cf1dfc71d3ed0dcf93c303ce2ef8d646/src/server/game/Spells/SpellMgr.cpp#L3411

**Comment by Kitzunu** [comment]
I believe this should be spell = 30675 instead

**Comment by Hacaw** [comment]
@Winfidonarleyan , @Kitzunu was this fixed ? 
 I see none at line 3411 on my version.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Kitzunu** [comment]
Yes.
It is refactored the whole thing so you wont be able to look for that line

Anyhow, it will throw DB error if it try to correct spell that doesnt exist. And I did remove this :)
