### ISSUE TITLE
[Spells] Incorrect/Invalid spells

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#3665]
##### CURRENT BEHAVIOUR:
```
19:28:46 Loading SpellInfo store...
19:28:46 TOTAL_AURAS must be at least 397, spellIndex 78142
19:28:46 TOTAL_AURAS must be at least 375, spellIndex 78142
19:28:46 TOTAL_AURAS must be at least 376, spellIndex 78142
19:28:46 TOTAL_SPELL_EFFECTS must be at least 168, spellIndex 78951
19:28:46 TOTAL_AURAS must be at least 332, spellIndex 79342
19:28:46 TOTAL_SPELL_TARGETS must be at least 119, spellIndex 79579
```

**Comment by Hacaw** [comment]
@Winfidonarleyan, is there a way I can test this ? 
I suppose this is the log message when you startup the worldserver, what I am getting is only this:

`
ac-worldserver_1  | Loading SpellInfo store...`
`ac-worldserver_1  | >> Loaded spell custom attributes in 49 ms
`

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None
