### ISSUE TITLE
Feature: Adding IP address in the log of malformed packets [$15]

### ISSUE THREAD

**Issue by Racknar0** [azerothcore/azerothcore-wotlk#3670]
Feature: Adding IP address in the log of malformed packets

Yesterday something happened in the server was all normal and from one moment to another began to generate lag throughout the world, expelled many people went to check the Server.Log and came out this message:

![image](https://user-images.githubusercontent.com/38267074/98488024-cd989d80-21f4-11eb-967c-31fa41247547.png)

You can see that it does not give any information, is there any possibility to add the IP address in that LOG?
in the mangos page i think they talked about it

https://www.getmangos.eu/forums/topic/3828-worldsockethandle_input_header-client-sent-malformed-packet-size/

They give some information but the structure is different.

![image](https://user-images.githubusercontent.com/38267074/98488099-3849d900-21f5-11eb-9166-1f9a99b1ea30.png)

We would appreciate it very much if you could detect the IP through the log.

**Comment by Goatform** [comment]
@Racknar0  I'm working on it with a few additional improvements, have a look here:
https://github.com/azerothcore/azerothcore-wotlk/compare/master...Goatform:handle_input_header_error

**Comment by Racknar0** [comment]
> @Racknar0 I'm working on it with a few additional improvements have a look here:
> [master...Goatform:handle_input_header_error](https://github.com/azerothcore/azerothcore-wotlk/compare/master...Goatform:handle_input_header_error)
> (I'm planning to do a few more changes before making PR)

we will wait for you soon 👀👀😃

**Comment by Racknar0** [comment]
again today 

![image](https://user-images.githubusercontent.com/38267074/98587253-df7f4c80-2297-11eb-9e56-d503ae86fd33.png)

How can I detect the fault? Or is it an attack?

**Comment by Goatform** [comment]
Usually, I mostly experienced that error when attempting to log-in with the client and somehow login would fail. Now, the core I work on is totally another expansion / patch but I mean the error is pretty much the same. However, I never managed to reproduce the issue 100%

**Comment by Racknar0** [comment]
apply your patch and the IP does not come out

![image](https://user-images.githubusercontent.com/38267074/98601936-b5d12000-22ad-11eb-9cf7-cc48f1ae1f71.png)

**Comment by Goatform** [comment]
This means that somehow the client has no session data at all. Either some possible (failed) attack or perhaps session never get to be created in the first place. I'll try to think of something.

**Comment by Racknar0** [comment]
> Esto significa que de alguna manera el cliente no tiene ningún dato de sesión (puede ver que cada información es 0 / nula, lo que lo confirma). O algún ataque (fallido) o quizás la sesión nunca se crea en primer lugar para ese caso específico. Intentaré pensar en algo.
> 
> ACTUALIZACIÓN: aplique un nuevo compromiso e intente capturarlo nuevamente.

I will wait for the failure to reproduce again, if it happens again I will notify you about the result

**Comment by Kitzunu** [comment]
Any updates?

**Comment by Goatform** [comment]
@Kitzunu I have no idea. The guy hasn't responded after as you can see. Also, I completely forgot about this PR that I was preparing. I can continue if someone can help me out to reproduce this report.
