### ISSUE TITLE
[NPC] Big Roy

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#3676]
##### CURRENT BEHAVIOUR:

- Big Roy (creature GUID 203496) is spawned twice with the same DB GUID

![image](https://user-images.githubusercontent.com/55922592/98727121-ba720300-2397-11eb-9863-284551268728.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- Big Roy should be spawned only once

https://wowwiki.fandom.com/wiki/Big_Roy 
##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 203496
2. see that this beatiful creature is there twice

##### EXTRA NOTES:

You don't need to do a quest to see this creature

##### AC HASH/COMMIT:

AzerothCore rev. 9a9308afd16a+ 2020-11-04 16:30:40 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro x64

##### MODULES:

- Auctionhouse Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:

None

**Comment by BarbzYHOOL** [comment]
how can there be twice the same guid? did u mean same id?

**Comment by LukasVolgger** [comment]
No, guid.

**Comment by BarbzYHOOL** [comment]
So i typed `SELECT * FROM `creature` WHERE `guid` = '203496'` and i got as a result only 1 row...

i'm not convinced about this issue

**Comment by BarbzYHOOL** [comment]
However ```SELECT * FROM `creature` WHERE `id` = '24785'``` yelds two rows, so i was right, it's not guid but id...

plz verify that the PR is really good

**Comment by locus313** [comment]
I see what your saying here, its not really that the DB GUID is the same, but that there is two entry's for Big Roy ( id 24785). Here is the two rows I saw in the creature DB for this id. 
```sql
(`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES 
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0),
(203496, 24785, 571, 0, 0, 1, 1, 0, 0, -25.5455, -3302.97, -1.54832, 5.95897, 300, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0);
```
Converting the sql from the pr to a select. Here is the data that would get removed:
```sql
(`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`, `guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `isLarge`, `auras`, `id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`, `move_type`, `action`, `action_chance`, `wpguid`) VALUES 
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 1, -69.856, -3276.64, -3.3955, 0, 0, 0, 0, 100, 0),
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 2, -31.814, -3275.34, -3.3955, 0, 0, 0, 0, 100, 0),
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 3, -23.1854, -3287.08, -3.20106, 0, 0, 0, 0, 100, 0),
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 4, -27.8761, -3306.28, -3.86772, 0, 0, 0, 0, 100, 0),
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 5, -41.3687, -3311.33, -4.00661, 0, 0, 0, 0, 100, 0),
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 6, -68.5023, -3304.22, -3.78439, 0, 0, 0, 0, 100, 0),
(203340, 24785, 571, 0, 0, 1, 1, 0, 0, -75.7733, -3292.35, -3.92591, -3.50661, 120, 0, 0, 9291, 0, 2, 0, 0, 0, '', 0, 203340, 2033400, 0, 0, 0, 0, 0, NULL, 2033400, 7, -75.7733, -3292.35, -3.50661, 0, 0, 0, 0, 100, 0);
```
So only the data related to the creature guid 203340 gets removed without having to have delete statements for each database. And creature guid 203496 will remain as the only entry for creature id 24785. So I think sql in the pr is just fine.

**Comment by BarbzYHOOL** [comment]
> So I think sql in the pr is just fine.
i also think so but didn't check in details

just was like "guid" can't be used twice, it's not possible

**Comment by LukasVolgger** [comment]
@BarbzYHOOL check ingame before PR with  .npc info on both creatures

**Comment by BarbzYHOOL** [comment]
> @BarbzYHOOL check ingame before PR with .npc info on both creatures

ingame it's two different guid ^^ but maybe you missclicked one of the big roy and you selected twice the same NPC, hence the confusion

it doesn't change anything though, the issue is valid and the fix too, i was just curious

**Comment by LukasVolgger** [comment]
okay then it must be like this, I should go to sleep earlier o.o
