### ISSUE TITLE
Feature: New player rank "tester"

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#3677]
**Describe your feature request or suggestion in detail**

A new rank in the core, and in the tables `realmlist` and `account_access`.
The rank would be number 1 and then we'd have to move all the other ranks by 1 up.

Current common.h:

```cpp
enum AccountTypes
{
    SEC_PLAYER         = 0,
    SEC_MODERATOR      = 1,
    SEC_GAMEMASTER     = 2,
    SEC_ADMINISTRATOR  = 3,
    SEC_CONSOLE        = 4                                  // must be always last in list, accounts must have less security level always also
};
```
New:
```cpp
enum AccountTypes
{
    SEC_PLAYER                 = 0,
    SEC_TESTER                 = 1,
    SEC_MODERATOR         = 2,
    SEC_GAMEMASTER      = 3,
    SEC_ADMINISTRATOR   = 4,
    SEC_CONSOLE              = 5
};
```

So why?

Well when you have a dev realm, you might want to allow only certain accounts on that server. Actually we have to block ALL players from entering, meaning we can't even test with normal player accounts unless we edit the `realmlist` table and reboot authserver and worldserver (annoying and rank 0 players can now enter, which is unwanted).

Also we could simply set a tester rank for players of our choice to test on our dev realm (or dedicated test realm).

Note: never really understand the rank "moderator" but i guess it's like a new GM.

**Additional context**

To convert current ranks in the DB, it can probably be handled smoothly with queries.
Also, MAYBE, need to update the default accounts and set "test9" and "test10" to rank 1 probably (and move all the other ranks by one up?)

**Comment by Si1ker** [comment]
❌

**Comment by Racknar0** [comment]
❌

**Comment by BarbzYHOOL** [comment]
In fact, i don't think it will break fusioncms cause if we keep the previous account_access to rank "console" then it will be fine as in fusioncms it uses the account name

**Comment by FALL1N1** [comment]
That's really unnecessary in my opinion, if someone wants it - they will simply add it.

**Comment by BarbzYHOOL** [comment]
> That's really unnecessary in my opinion, if someone wants it - they will simply add it.

Like every feature, nothing is necessary and can be custom added. Less work for users is better, and it also avoids git conflicts when updating. What about the current subjective ranks we have? They lay the path for server owners, and it's fine (though one could argue that these should be configurable in DB directly instead and I agree with that)

This would allow for premium testers or people who would register to a beta test (or a PTR) through a special form on their website. It only gives more flexibility, more possibilities for little cost. I feel like I didn't explain it well in the first place :(

**Comment by FALL1N1** [comment]
Maybe backporting RBAC would be a better idea rather than playing with those values? In my opinion it is, also it's much better than the current implementation of security levels.

**Comment by BarbzYHOOL** [comment]
ah maybe too (though slightly different subject), I really dunno how good RBAC is but it's prob a lot of work to port (meanwhile this could be added lol)

I think Deku had started the work on his fork long ago (he wanted to make it a module though, not sure why, maybe to avoid breaking changes)
no one else tried

**Comment by Kitzunu** [comment]
Gonna close this in favor of RBAC https://github.com/azerothcore/azerothcore-wotlk/issues/5704
