### ISSUE TITLE
server is frozen [$150]

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#3679]
logs:
```
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 2450 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 4527 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 4267 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 2450 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6976 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 499 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 499 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): DELETE FROM character_pet WHERE id = 133
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 5219 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 5219 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 208 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
```

 version:AzerothCore rev. c32283fab782+ 2020-11-06 18:05:03 +0000 (master branch) (Unix, Release) 
OS:ubuntu 18.04.4

**Comment by Kitzunu** [comment]
Crashlog please

**Comment by mpfans** [comment]
> Crashlog please

not crash log... only frozen ... can see the following logs on the console.

[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 2450 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 4527 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 4267 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 2450 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6976 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 499 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 499 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): DELETE FROM character_pet WHERE id = 133
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 5219 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 5219 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 208 AND slot = 0
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.

**Comment by FrancescoBorzi** [comment]
@mpfans do you use any modules or any other kind of customisations?

**Comment by mpfans** [comment]
> @mpfans do you use any modules or any other kind of customisations?

use mod-multi-client-check modules..  https://github.com/azerothcore/mod-multi-client-check

not any customisations...

**Comment by FrancescoBorzi** [comment]
@mpfans can you please provide the instructions to reproduce the issue? also, can you try to reproduce the issue without any module?

**Comment by mpfans** [comment]
I can't reproduce the issue, it happens twice in a week. Disabled modules also appear.

**Comment by FrancescoBorzi** [comment]
@mpfans I understand, but unfortunately we can't do much without reproduction steps :(

**Comment by mpfans** [comment]
Ok, Tyvm

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/102979867-a4806200-4541-11eb-86fa-c198a4694ebd.png)

**Comment by mpfans** [comment]
I use AC core, there is no other custom code

**Comment by mpfans** [comment]
module:mod-anticheat

**Comment by Kitzunu** [comment]
Add rev and a crashlog pls

**Comment by mpfans** [comment]
> Add rev and a crashlog pls
rev https://github.com/azerothcore/azerothcore-wotlk/commit/672057316a516f6126ee07f53006546eb238b7de
not carsh log...

**Comment by Kitzunu** [comment]
Without a crashlog we can't figure out the issue

**Comment by Viste** [comment]
@mpfans dont listen this stupid boys who say about crash logs :D just w8 some time we with winfi try to slove this
@Kitzunu try to learn how to read what people write.... or if you need "crashlog" when server is running explain how to run server with gdb and trace of an initiated process.... or don't dishonour yourself...

**Comment by FrancescoBorzi** [comment]
be careful @Kitzunu , the bear will not tolerate any technical incorrectness 😆

**Comment by Viste** [comment]
> be careful @Kitzunu , the bear will not tolerate any technical incorrectness laughing

It's hard to resist when someone asks for crashlog when there was no crash.

**Comment by skxawng-cu** [comment]
I have the same problem actually, in my case it happen one time every day.

**Comment by skxawng-cu** [comment]
I found the information about the Deadlock executing this query to mysql: SHOW ENGINE INNODB STATUS \G

------------------------
LATEST DETECTED DEADLOCK
------------------------
2021-04-26 12:56:30 0x7f6cbe4bc700
*** (1) TRANSACTION:
TRANSACTION 9431837, ACTIVE 0 sec starting index read
mysql tables in use 2, locked 2
LOCK WAIT 6 lock struct(s), heap size 1136, 5 row lock(s), undo log entries 1
MySQL thread id 31849, OS thread handle 140101631866624, query id 8884203 localhost 127.0.0.1 acore Searching rows for update
UPDATE character_pet SET slot = 100 WHERE owner = 10538 AND slot = 0

*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 48 page no 24 n bits 1616 index idx_slot of table `acore_characters`.`character_pet` trx id 9431837 lock_mode X locks rec but not gap
Record lock, heap no 744 PHYSICAL RECORD: n_fields 2; compact format; info bits 32
 0: len 1; hex 00; asc  ;;
 1: len 4; hex 000023b9; asc   # ;;
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 48 page no 24 n bits 1616 index idx_slot of table `acore_characters`.`character_pet` trx id 9431837 lock_mode X waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len 1; hex 00; asc  ;;
 1: len 4; hex 00000007; asc     ;;


*** (2) TRANSACTION:
TRANSACTION 9431834, ACTIVE 0 sec fetching rows
mysql tables in use 2, locked 2
LOCK WAIT 30 lock struct(s), heap size 3520, 1658 row lock(s), undo log entries 1
MySQL thread id 31851, OS thread handle 140098291095296, query id 8884195 localhost 127.0.0.1 acore Searching rows for update
UPDATE character_pet SET slot = 100 WHERE owner = 16783 AND slot = 0

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 48 page no 24 n bits 1616 index idx_slot of table `acore_characters`.`character_pet` trx id 9431834 lock_mode X
Record lock, heap no 2 PHYSICAL RECORD: 
n_fields 2; compact format; info bits 0
 0: len 1; hex 00; asc  ;;
 1: len 4; hex 00000007; asc     ;;

**Comment by skxawng-cu** [comment]
The character related here was a warlock

**Comment by ChromieCraftServer** [comment]
added a 20$ bounty here, I hope this helps.

**Comment by UltraNix** [comment]
Comes from `Pet::SavePetToDB`
```
// prevent duplicate using slot (except PET_SAVE_NOT_IN_SLOT)
      if (mode <= PET_SAVE_LAST_STABLE_SLOT)
      {
          stmt = CharacterDatabase.GetPreparedStatement(CHAR_UDP_CHAR_PET_SLOT_BY_SLOT);
          stmt->setUInt8(0, uint8(PET_SAVE_NOT_IN_SLOT));
          stmt->setUInt32(1, ownerLowGUID);
          stmt->setUInt8(2, uint8(mode));
          trans->Append(stmt);
      }
```

**Comment by mpfans** [comment]
The server has been running for 3 days. Then it freezes and can't log in

**Comment by Viste** [comment]
@mpfans  plz connect to your mysql-server and use world DB the run this 2 query and show results:
`desc character_pet;
show create table character_pet\G`

**Comment by mpfans** [comment]
> `explain delete from character_pet where id=%some id from server cli error%;`

![image](https://user-images.githubusercontent.com/18187177/119265856-ead60c00-bc1a-11eb-84f6-8be27841f42e.png)

**Comment by mpfans** [comment]
> @mpfans plz connect to your mysql-server and use world DB the run this 2 query and show results:
> `desc character_pet;`
> `show create table character_pet\G`

![image](https://user-images.githubusercontent.com/18187177/119265890-0b9e6180-bc1b-11eb-8db5-4ed0da780135.png)

**Comment by Viste** [comment]
> > `explain delete from character_pet where id=%some id from server cli error%;`
> 
> ![image](https://user-images.githubusercontent.com/18187177/119265856-ead60c00-bc1a-11eb-84f6-8be27841f42e.png)

man you......  need CHANGE `%some id from server cli error%;` replace WITH REAL ID FROM YOUR LOG LIKE ON THIS SCREEN

> ![20210521080936](https://user-images.githubusercontent.com/18187177/119069851-7b44fe80-ba19-11eb-97ea-71c3bd7ecf8a.jpg)

**Comment by mpfans** [comment]
> > > `explain delete from character_pet where id=%some id from server cli error%;`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/18187177/119265856-ead60c00-bc1a-11eb-84f6-8be27841f42e.png)
> 
> man you...... need CHANGE `%some id from server cli error%;` replace WITH REAL ID FROM YOUR LOG LIKE ON THIS SCREEN
> 
> > ![20210521080936](https://user-images.githubusercontent.com/18187177/119069851-7b44fe80-ba19-11eb-97ea-71c3bd7ecf8a.jpg)

Ok... Wait for the next time or can I execute this query at any time?

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/119282880-ceaf8a80-bc6d-11eb-9f6e-ab31dce3146b.png)

**Comment by T1ti** [comment]
does pressing enter in the world console unfreeze it ? that happens to me a lot

**Comment by mpfans** [comment]
> does pressing enter in the world console unfreeze it ? that happens to me a lot

not .  No matter how to operate, it can not be unfreeze !
I have to use the kill command to end the process

**Comment by UltraNix** [comment]
@mpfans Look at your `worldserver.conf` and show me your values of these two: `CharacterDatabase.WorkerThreads` and `CharacterDatabase.SynchThreads`

**Comment by Viste** [comment]
you just need revert some shit commits related to pet system from stoabragga and another one person dont remember nickname

**Comment by Viste** [comment]
or another way you can drop current pet system and take it from cMaNGOS

**Comment by Viste** [comment]
@UltraNix @FrancescoBorzi @Winfidonarleyan

**Comment by FrancescoBorzi** [comment]
@Viste PRs are welcome :)

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/120455282-3630ad00-c3c7-11eb-88b9-d24f11c1ce8c.png)

**Comment by Viste** [comment]
@mpfans try revert this shit PR https://github.com/azerothcore/azerothcore-wotlk/pull/2100

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/126998872-14fbfd86-f2a2-4029-8e20-68027328733d.png)

**Comment by Viste** [comment]
> @mpfans try revert this shit PR #2100

@mpfans

**Comment by mpfans** [comment]
> > @mpfans try revert this shit PR #2100
> 
> @mpfans

Will this PR affect pet work?

**Comment by Viste** [comment]
> > > @mpfans try revert this shit PR #2100
> > 
> > 
> > @mpfans
> 
> Will this PR affect pet work?

only stables

**Comment by mpfans** [comment]
This problem still exists

**Comment by FrancescoBorzi** [comment]
@mpfans

**Comment by mpfans** [comment]
> @mpfans you check @Viste PR?

no,his PR is draft
