### ISSUE TITLE
Feature: Server Reboot System

### ISSUE THREAD

**Issue by Racknar0** [azerothcore/azerothcore-wotlk#3684]
Server Reboot System

Good afternoon, as you know the server's ram consumption is gradually increasing I tried to perform a reboot CRONTAB but when you close the service of one the server has a rollback

It would be interesting to be able to implement a server reboot system within the kernel in the config file in which you can specify how often and at what times
example
Restart server frequency: 2 Days
Restart Server Hour: 23:15

That the command .server restart will be executed with a warning could be 10 minutes of anticipation to warn the players in advance of the reboot

Would this option be viable?

Translated with www.DeepL.com/Translator (free version)

**Comment by IceNet** [comment]
You need a restarter for a reboot system anyway.

I just solved it with a python script and cronjob.
The python script sends the command ".server restart 900", so there is no rollback

**Comment by FrancescoBorzi** [comment]
>  as you know the server's ram consumption is gradually increasing

that's because of all the items that are being kept cached, such as the maps. But at some point, it should stabilise

**Comment by Racknar0** [comment]
> You need a restarter for a reboot system anyway.
> 
> I just solved it with a python script and cronjob.
> The python script sends the command ".server restart 900", so there is no rollback

Could you show me how the script goes?

**Comment by FALL1N1** [comment]
There was an auto restarter in a leaked mop/cata source if that's what you need, I can backport it if there are more requests.

**Comment by FrancescoBorzi** [comment]
> There was an auto restarter in a leaked mop/cata source if that's what you need, I can backport it if there are more requests.

why not!

**Comment by IceNet** [comment]
you still need a restarter, unless you run a "monitoring thread", which would be more time consuming

**Comment by BarbzYHOOL** [comment]
there is a restarter in our repo too but never tried it and might have some bugs

but yeah, in fact, it's made to work with an external restarter than can do anything u want with it (i even fixed the exit codes long ago so you can know if it's a reboot or a shutdown etc)

I think it should be closed and labeled "intended"

**Comment by Racknar0** [comment]
When the process is killed via crontab there is always rollback! because it is forced to close
it would be much better to send the command .server subtart XXX
at a certain configurable time

example
Restart server frequency: 2 Days
Restart Server Hour: 23:15

**Comment by FALL1N1** [comment]
@Racknar0 that's because you have to send "saveall" first.

**Comment by Racknar0** [comment]
> @ Racknar0 eso se debe a que primero debe enviar "saveall".

but the idea is to make it automatic XD

**Comment by Racknar0** [comment]
but the idea is to make it automatic XD...

**Comment by IceNet** [comment]
But the effort is quite large for the benefit

The installation and testing for the cronjob and perl script takes about 10 minutes

**Comment by Kitzunu** [comment]
Was not the intention for an automatic restarter to be apart of the core. It was meant to be an external script.

f.ex if you run windows you can use https://github.com/azerothcore/azerothcore-exitcode-script
