### ISSUE TITLE
Feature: Pet XP rate

### ISSUE THREAD

**Issue by IceNet** [azerothcore/azerothcore-wotlk#3687]
**Describe your feature request or suggestion in detail**
the possibility to define the EXP rate of pets

**Additional context**
At the moment there is only the definition "#define PET_XP_FACTOR 0.05f" in "src/server/game/Entities/Pet/Pet.cpp" line 26.
Would be a nice feature on highrate servers
The problem is that you level yourself quickly, but the pet doesn't

**Comment by gabrielfoo** [comment]
I've checked and the pet already receives the same exp as the player.

If the exp received is 100, and the rate is set to 5x, both hunter and pet will receive 500 exp. 

At level 24, you will get something like this in the xp bar:
Pet: _500 / 1360_
Player: _500 / 27200_

I have to point out that the pet's exp-to-next-level "1360" is 0.05x of the player's "27200" at level 24. I think that was what the PET_XP_FACTOR is for. Therefore, the pet will level faster than the player for sure.

**Comment by gabrielfoo** [comment]
Whether the above behaviour is blizzlike or not, I'm not sure.

**Comment by gabrielfoo** [comment]
I've checked and the pet already receives the same exp as the player.

If the exp received is 100, and the rate is set to 5x, both hunter and pet will receive 500 exp.

Also, the total experience for the pet to level is merely 5% (PET_XP_FACTOR) of the character of the same level as the pet. For eg, the character at level 24 needs 27200 exp to get to lvl 25. The pet only needs 1360 exp to level 25.

The pet will definitely level quickly, so there isn't a problem at all.

**Comment by Helias** [comment]
Check these modules, may they can help
```
mod-weekend-xp
mod-individual-xp
mod-dynamic-xp
```

**Comment by BarbzYHOOL** [comment]
test the PR !!!!!!!!

**Comment by IceNet** [comment]
> test the PR !!!!!!!!

Tested!
Works!
