### ISSUE TITLE
[Request] Update mythic+ system to latest AC

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/azerothcore-wotlk#3693]
Request: Update mythic+ system so that it works with lastest AC

Fork with mythic+ system: https://github.com/Visionre/azerothcore-wotlk/tree/mythic_plus_335
after this commit it's broken: https://github.com/azerothcore/azerothcore-wotlk/commit/833611f1c5e43bb9c13c579962eedbf3b4ab87aa

**Comment by Kitzunu** [comment]
@P-Kito

**Comment by Kitzunu** [comment]
Closing this issue as it doesn't have any relation to the core, but tagged the original author so he hopefully can look at it :)

**Comment by Si1ker** [comment]
@Err0r1 Err0r1 edited 4 minutes ago
❌  Request: Update mythic+ system so that it works with lastest AC

❌  Fork with mythic+ system: https://github.com/Visionre/azerothcore-wotlk/tree/mythic_plus_335
❌ after this commit it's broken: azerothcore/azerothcore-wotlk@833611f

✔️ Nvm.

🤔 ?
