### ISSUE TITLE
How To Modify directory mysql lib

### ISSUE THREAD

**Issue by vituchito125** [azerothcore/azerothcore-wotlk#3697]
Excuse me but the mysql where I install the emulator belongs to bitnami and is modified, how do I change the directory because I get an error
![update](https://user-images.githubusercontent.com/53723504/99162704-86b41780-26ce-11eb-85c2-2b5360cb90cf.jpg)
/opt/bitnami/mysql/
donde lo modifico ?

**Comment by FrancescoBorzi** [comment]
hi @vituchito125 welcome to AzerothCore. Support requests should be sent via stackoverflow and not in the bugtracker (that is only to report bugs). Please read: https://www.azerothcore.org/wiki/How-to-ask-for-help
