### ISSUE TITLE
Valiance Keep recruiting event not scripted/Quest Dialogue [$30]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#3699]
##### CURRENT BEHAVIOUR:

Recruitment Officer Carven and the Civilian Recruits are simply static and do not perform their continuous event.  The Civilian Recruits do not say anything when you accept the quest Enlistment Day (ID: 11672)

No dialogue between the 3 NPCs when you turn in the quest Enlistment Day (ID: 11672)

It's not scripted but most of it is found in the database, maybe a wrong trigger?

https://i.imgur.com/j3Kxm3T.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There is an event that happens with the recruitment line, the transcript of which is found here: https://wow.gamepedia.com/Civilian_Recruit

At random, Recruitment Officer Carven will say one of these:

```
    Recruitment Officer Carven says: Yes, then. What is your trade?
    Recruitment Officer Carven says: State your profession.
    Recruitment Officer Carven says: Your profession?
    Recruitment Officer Carven says: Your previous line of work, recruit?
    Recruitment Officer Carven says: What did you do before you came to Northrend, then?
```

A civilian recruit will randomly respond with one of these:

```
    Civilian Recruit says: Cook.
    Civilian Recruit says: Farmhand.
    Civilian Recruit says: Farmhand, sir.
    Civilian Recruit says: Farmhand, m'lord.
    Civilian Recruit says: Miner.
    Civilian Recruit says: Miner, sir.
    Civilian Recruit says: Shipwright.
    Civilian Recruit says: Shipwright, sir.
    Civilian Recruit says: Mason, sir.
    Civilian Recruit says: Blacksmith.
    Civilian Recruit says: Blacksmith, sir.
    Civilian Recruit says: Carpenter.
    Civilian Recruit says: Carpenter, sir.
    Civilian Recruit says: Seamstress, m'lord.
    Civilian Recruit says: Tailor.

```

Recruitment Officer Carven will randomly respond with one of these:

```
    Recruitment Officer Carven says: Yeah. We could use some more of you. Report to the civilian liaison.
    Recruitment Officer Carven says: Looks like we have room for one more... no, my mistake. That's a seven not a one. Hope you're good with a sword - report to the barracks.
    Recruitment Officer Carven says: I thought we had enough in your line of work, but it looks like we have some openings. Report to the civilian liaison.
    Recruitment Officer Carven says: Yeah. We could use some more of you. Report to the civilian liaison for work assignment.
    Recruitment Officer Carven says: Afraid not, friend. Here's your sword and shield. Report to the barracks for duty.
    Recruitment Officer Carven says: Not anymore! Here's your sword. Report to the barracks for duty!
    Recruitment Officer Carven says: With a sword arm like that? I'm afraid we need you in the front lines, my friend. Report to the barracks.
    Recruitment Officer Carven says: I do have some openings in your line of work. Report to the civilian liaison.
    Recruitment Officer Carven says: You're breaking my heart - I've quotas to fill, you know? Can you wield a sword? Off to the barracks.
    Recruitment Officer Carven says: Yes, you're well seasoned in your field of work. Report to the civilian liaison at once, we need more like you!
```

When a Civilian Recruit leaves the recruitment line, one of these are said:
```

    Recruitment Officer Carven says: Keep it moving, people.
    Recruitment Officer Carven says: Next, please!
    Recruitment Officer Carven says: Next!
```

The Civilian Recruit will then leave the line, and the line moves up - a new Civilian Recruit spawns near the docks and gets in the back of the line.

When you accept the quest Enlistment Day (ID: 11672), a Civilian Recruit should say this:
`What's the matter, <class>? Think you're too good to stand in line with the rest of us?`

When you complete Enlistment Day, the following should be said:

```
    Harbinger Vurenn says: Give the word, general. I will have two regiments at your disposal in a month's time.
    Counselor Talbot says: Our troops, general, consist mostly of villagers and peasants. Good men, but not quite rid of the prejudices and superstitions of their upbringing. They're not ready to fight alongside our more exotic allies.
    General Arlos says: Your offer will be carefully considered, harbinger. In the meantime we will make use of your delegation in an advisory role.
    Harbinger Vurenn says: Very well, general. Should you change your mind, my people will be more than willing to provide military assistance.
```

https://wow.gamepedia.com/Enlistment_Day

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create character, level doesn't matter
2. .tele valiancekeep
3. Walk to the recruitment line, there is no scripted event
4. Add the quest Enlistment Day with .quest add 11672 and turn it in to General Arlos in the barracks, there is no dialogue

##### AC HASH/COMMIT:

543753b641bc

##### OPERATING SYSTEM:

Win10

**Comment by Voxstrasza** [comment]
Not all Civilian Recruit dialogue present in database: https://i.imgur.com/fhQa3KN.png

Carven dialogue is in database

**Comment by Voxstrasza** [comment]
[$15 Bounty](https://www.bountysource.com/issues/94324987-valiance-keep-recruiting-event-not-scripted?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)

**Comment by Voxstrasza** [comment]
here is a video on how it works on retail https://www.youtube.com/watch?v=GRhIrNAGBdc

i've learned that it's all random, and a civilian recruit can walk to either the barracks and despawn or the civilian liason and despawn - no matter what recruiting officer carven says

**Comment by Voxstrasza** [comment]
added $15 for a total of $30

**Comment by Winfidonarleyan** [comment]
Hmm

**Comment by FALL1N1** [comment]
try https://raw.githubusercontent.com/TrinityCore/TrinityCore/f7283d97660be93921fdabb58a9fc3a245ece6e2/sql/old/6.x/world/03_2016_04_11/2016_04_09_17_world_2016_04_01_00_world.sql

**Comment by Voxstrasza** [comment]
> 
> 
> try https://raw.githubusercontent.com/TrinityCore/TrinityCore/f7283d97660be93921fdabb58a9fc3a245ece6e2/sql/old/6.x/world/03_2016_04_11/2016_04_09_17_world_2016_04_01_00_world.sql
> 
> fixed for ac:
> https://gist.githubusercontent.com/FALL1N1/8a7e9b5466d8c9de1582fa1f61fa55c8/raw/ce0420c9ee5db8a2451db7ed2b5c4a558292f9a7/asd.sql
> 
> http://prntscr.com/vlzfnw

You are a god, I'll try it out, why not make PR and get your money? :D

does this cover the dialogue on completing the quest as well?

**Comment by FALL1N1** [comment]
I haven't tested the questchain, I just saw them moving and talking, let me know if the quest completion works and I'll make the pr, otherwise I'll include the other fix as well.

**Comment by Maurowin** [comment]
Do u will put all language of dial ?
I seen on the screenshot first mob climp the table.
