### ISSUE TITLE
Noth the Plaguebringer 10 ppl / Curse bug

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#370]
**Current behaviour**: After entering the second and third ground phase,he stops using his Curse on players.

**Expected behaviour**: After entering second and third ground phase,he must using his Curse spell,as needed.

**Steps to reproduce the problem**:

1. Pull Noth.
2. Wait his first returning from balcony.
3. Check yours debuff frame.

**Branch(es)**: master

**AC hash/commit**:  e25a499

**Operating system**:  Windows 8.1 x64, with all current updates.

**Modules**:  No.

**Other Customizations**: No, I don't.

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/scripts/Northrend/Naxxramas/boss_noth.cpp#L89 -- the function is called here. after returning from the balcony it should cast it within 15 seconds.

**Comment by markvetwow** [comment]
I uploaded the video with this issue. You can check it [here.](https://www.youtube.com/watch?v=Hc-vVYMqpHc). As you can see,he using his curse on first ground phase as intended. But after first balcony phase,he is returning,and stops using the curse spell at all.

**Comment by talamortis** [comment]
thank you im  checking this now :)
