### ISSUE TITLE
When summoning/teleporting in GM mode, target player gets all phases

### ISSUE THREAD

**Issue by steenburgh** [azerothcore/azerothcore-wotlk#3702]
##### CURRENT BEHAVIOUR:
When I turn on GM mode and summon a player, their phase mask becomes 0xFFFF_FFFF (all phases).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This is a GM command, so I'm not sure what blizzlike behavior is, or if there's any public info about that. That said, I personally would not expect a GM summon to modify the player's phase. Perhaps I'm wrong + if I am, let's just close this, and I'll make a PR to add documentation about this behavior to the AzerothCore wiki instead.

##### STEPS TO REPRODUCE THE PROBLEM:
1. On a gm character, turn on gm mode, `.gm on`
2. Run `.pinfo anotherchar` on some other character that's online (and also not in gm mode). Note their phase. Usually it's `1`
2. Summon that character `.summon anotherchar`.
3. Run `.pinfo anotherchar` again.

*Expected*: Their phase has not changed
*Actual*: Their phase is set to `MAX_UNSIGNED_INT`, `4294967295`

A great way to test this is by summoning a player to the bank at undercity. Before you summon them, they'll see the city like normal. If you summon them while you're in GM mode, they'll see the city on fire. I suspect this is because GMs can see all phases, and the summon command is just using the GM's current phase mask.

Before summon
![image](https://user-images.githubusercontent.com/9411156/99182245-6d749080-26f9-11eb-8720-3cd42e762632.png)
![image](https://user-images.githubusercontent.com/9411156/99182249-7a917f80-26f9-11eb-914d-354e50310364.png)

After summon
![image](https://user-images.githubusercontent.com/9411156/99182593-63539180-26fb-11eb-9f02-6ad19a3dff62.png)
![image](https://user-images.githubusercontent.com/9411156/99182269-9ac13e80-26f9-11eb-8df4-dd01e4211234.png)

##### EXTRA NOTES:
* ~~The `.teleport name` command also exhibits this behavior~~ Looks like I was mistaken. The `.teleport name` command does not affect player phase.
* The screenshots above show me summoning a character who happens to be on an account with GM level 3. This also happens for characters on regular accounts

##### Workaround
* Reset the player's phase to 1 via `.modify phase 1`.
* Turn off GM mode and summon the player to a *different location*. If you teleport the player to the exact same coordinates, it will not set their phase. I assume this is because of an optimization in the teleport command

*Neither of these workarounds restore the player's phase to what it was before they were summoned, which will be a problem for players like death knights who rely heavily on phasing for their starting quest line.*

##### AC HASH/COMMIT:
27ed629ff5d49dee5e12e7564b52f232dda947b9

##### OPERATING SYSTEM:
Windows 10.0.19041

##### MODULES:
* mod-ah-bot (custom build from https://github.com/steenburgh/mod-ah-bot/pull/1)
* mod-autobalance

##### OTHER CUSTOMIZATIONS:
* I have applied the Brewfest Start Time fix from https://github.com/azerothcore/azerothcore-wotlk/pull/3487

**Comment by Si1ker** [comment]
Yeah, I noticed it quite  along time but I just felt it like "that's the way it works" and then just did .mod phase 1, which restores phase 1 for the player, at least that way worked for me, so not sure if this behavior is an issue, tagging @Kitzunu @FrancescoBorzi  for their feedback on this and decide if is whether an "issue" or expected.

**Comment by Kitzunu** [comment]
Personally I think we should force the player to the "normal" phase

**Comment by steenburgh** [comment]
IDK what the intent of the `summon`/`teleport name` commands are, but I've always thought it was for when GMs needed to respond to tickets + move players around for one reason or another. On my server, we use it much more frequently during normal gameplay just to make traveling more convenient. In either case, you almost never would want to change their phase to 'all phases'. Now the obvious response to that is "well don't use gm mode then" and I get that, but it just doesn't seem intuitive that that would affect it at all.

**Comment by Si1ker** [comment]
Note: The .teleport name command also exhibits this behavior
This statement is **false**, a player teleported in this way:

- Click player
- `.tele name tirisfal`

The player will be teleported to "default" phase, not the gm one.

**Comment by steenburgh** [comment]
Just tested on my server and yep, I was mistaken - the `.tele name` command does not modify the player's phase. I've updated the description to reflect this.
