### ISSUE TITLE
Add logs database [$50]

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#3719]
The logs of AC core cannot be written to the database correctly

modify worldserver.conf

EnableLogDB = 1
LogDB.Char = 1
LogDB.GM = 1
LogDB.RA = 1
LogDB.World = 1
LogDB.Chat = 1

No transaction log, no cod log, no ah log
Vmangos logs is perfect
https://github.com/vmangos/core/blob/development/sql/logs.sql
You can refer to the logs of vmangos

**Comment by FrancescoBorzi** [comment]
Marking as "Fix included" as the source code of vMaNGOS is open source.

Also, everything must be configurable, disabled by default.

**Comment by Visionre** [comment]
> The logs of AC core cannot be written to the database correctly

What do you mean by that? Which error?

I use DBLog without any problems

**Comment by mpfans** [comment]
> > The logs of AC core cannot be written to the database correctly
> 
> What do you mean by that? Which error?
> 
> I use DBLog without any problems

![image](https://user-images.githubusercontent.com/18187177/99466857-16302380-2978-11eb-8576-cb352b2d1204.png)

The logs table can not meet the requirements of storing char, chat, BG, trade, drop, etc

**Comment by Visionre** [comment]
Please search for the error 1366.
Its not an AC issue.

![screenshot 1961](https://user-images.githubusercontent.com/74114448/99468800-bcad0200-2941-11eb-803e-c48e0d476ebd.png)

Latest AC with DB Logs enabled. Working fine.

**Comment by mpfans** [comment]
> Please search for the error 1366.
> Its not an AC issue.
> 
> ![screenshot 1961](https://user-images.githubusercontent.com/74114448/99468800-bcad0200-2941-11eb-803e-c48e0d476ebd.png)
> 
> Latest AC with DB Logs enabled. Working fine.
> E: AC doesn't log drop/BG/trade/etc in auth->logs table.

No problem with English,What about Chinese chat?And the logs are messy.So I want a vmangos like logging system
I can query various logs according to the guid, and query the data I want to query according to various conditions

**Comment by Visionre** [comment]
The logs are not read out in the db but read with e.g. php and are deleted every 14 days by default anyway

Unfortunately I don't have a chinese client to test it, maybe you can send me a link in Disocrd? Vision#0940

If you use Fusion, I can send you a module for chat + gm

**Comment by mpfans** [comment]
> The logs are not read out in the db but read with e.g. php and are deleted every 14 days by default anyway
> 
> Unfortunately I don't have a chinese client to test it, maybe you can send me a link in Disocrd? Vision#0940
> 
> If you use Fusion, I can send you a module for chat + gm

So I hope to have a vmangos logs system

**Comment by mpfans** [comment]
Would anyone like to work for logs? I'd like to increase the reward again

**Comment by Winfidonarleyan** [comment]
Maybe i'm

**Comment by Kitzunu** [comment]
cc @Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
Now no

**Comment by Winfidonarleyan** [comment]
@mpfans Can recheck this?
