### ISSUE TITLE
[Ulduar] [Assembly of Iron] Stormshield granting immunity to spell interrupt

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3728]
##### CURRENT BEHAVIOUR:
During the Assembly of Iron (25) encounter [Stormshield](https://wotlkdb.com/?spell=64187), gained from 2 dead, incorrectly gives Brundir immunity to kick in addition to stun. Tested with a warriors [Shield Bash](https://wotlkdb.com/?spell=72).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Interrupting spells should still be possible, even with [Stormshield](https://wotlkdb.com/?spell=64187) up.

##### STEPS TO REPRODUCE THE PROBLEM:
1.) Take a warrior in GM mode to Ulduar
2.) Start the Assembly of Iron encounter
3.) Take 2 down and leave Brundir alive. He should be buffed with "Stormshield". Try to interrupt one of his casts of [Lightning Whirl](https://wotlkdb.com/?spell=52943) with a [Shield Bash](https://wotlkdb.com/?spell=72).

##### EXTRA NOTES:
On the same topic, even before Stormshield is active it seems like Brundir cant be kicked right away after he starts casting. If you wait for him to get a few bolts off, kicks with [Shield Bash](https://wotlkdb.com/?spell=72) seem to work.

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by aradep** [comment]
Managed to reproduce this under very specific circumstances. The problem is with this part of the script
![image](https://user-images.githubusercontent.com/61268368/99899001-619a4880-2c7c-11eb-9a83-da46fcfad0e3.png)
If Brundir casts a spell _immediately_ after an Overload cast finishes, that spell will be uninterruptible because the event to set interrupt flag didn't fire in time.

**Comment by Si1ker** [comment]
@55Honey get changes from #3765 and try to repro the issue 🐱

**Comment by 55Honey** [comment]
Unfortunately i can not compile and test myself.
