### ISSUE TITLE
After the update(2017_02_03_47), Paladin skills invalid

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#373]
**Description**:
After the update(2017_02_03_47), Paladin skills invalid.
Skills name:
Greater Blessing of Might
Greater Blessing of Wisdom
Greater Blessing of Kings
Greater Blessing of Sanctuary
(All teams buff, no revenue, there is no icon in the upper right corner).
@Ercules76 @Helias @polaretto @ShinDarth @talamortis @Yehonal

**Comment by DarkmoonRabbit** [comment]
I guess it is associated with this change
https://github.com/azerothcore/azerothcore-wotlk/commit/8da076247d9b48ebb10228f6ccaf43d3e01c2260

**Comment by talamortis** [comment]
I'll take a look on my fork if need be ill revert it back 👍
