### ISSUE TITLE
Feature: Automatic DB updates via worldserver [$50]

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#3739]
**Describe your feature request or suggestion in detail**

Basically, the way TC handles DB updates but more progressive instead of having our external tool.

So when worldserver.exe is started it checks the latest SQL file in the src to see if the same revision is in the current DB or if any other file is missing (incase they have been imported manually in weird orders) - if not we automatically import the missing updates.

This would simplify keeping the DB up-to-date and first startup of the core instead of using a *in my opinion* confusing external tool.

Obviously this needs to have an option in config to disable auto updates

**Comment by FrancescoBorzi** [comment]
we can import @Naios' implementation from TC: https://github.com/TrinityCore/TrinityCore/tree/3.3.5

**Comment by Winfidonarleyan** [comment]
For this need to support `boost`
For example implementation in AC core https://github.com/WarheadCore/WarheadCore/commit/9a46794a2f3ad1f5040814e1321b2f9c74369cc9

**Comment by FrancescoBorzi** [comment]
> For this need to support `boost`
> For example implementation in AC core [WarheadCore/WarheadCore@9a46794](https://github.com/WarheadCore/WarheadCore/commit/9a46794a2f3ad1f5040814e1321b2f9c74369cc9)

@Winfidonarleyan it's ok to use Boost if needed but.. why do we need it? In that commit I see it's used for the Filesystem, but...  since C++17 the Filesystem is supported natively... so why not just using native C++ instead?

**Comment by FALL1N1** [comment]
You don't need boost if you know the new cpp17 syntax and functions.

**Comment by yuanf225** [comment]
Oregon core is also automatically updated, it seems that I didn’t find the need for boost?
