### ISSUE TITLE
[NPC] Incorrect casters behaviour

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#3740]
##### CURRENT BEHAVIOUR:

There is a bug with caster NPCs behaviour. If caster NPC was interrupted or was LoS'ed, they continue to move out from current aggro or trying to move to the point, where they can cast on current aggro again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

A vast majority of caster NPCs MUST go in melee to current aggro, if they were interrupted or if current aggro breaking its LoS.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a character with interrupt ability/spell (rogue, shaman etc.)
2. Learn it, of course
3. .tele brackwell
4. Pull Surena Caledon from the inside
5. Try to avoid her LoS or interrupt her casts

##### EXTRA NOTES:

I'm applying a link to the video [here](https://youtu.be/B9Mfh1gtOQ8)

##### AC HASH/COMMIT:

17afcaf

##### OPERATING SYSTEM:

Windows 10 x64

##### MODULES:

It's a clean build

**Comment by Quickson** [comment]
Can reproduce AzerothCore rev. 0bee5af962c0

**Comment by markvetwow** [comment]
Any guesses what might cause this? :(

**Comment by markvetwow** [comment]
Any guesses on what might cause this? :( It's kinda gamebreaking. You can basically kite the casters all around the building etc. without even being touched.

**Comment by Hacaw** [comment]
How should we handle this ? Let them cast through walls, or make them move faster to get out of LOS ?

**Comment by aradep** [comment]
Can also confirm, something is odd with ranged mobs and LoS.  
[Example of blizzlike behavior in Classic](https://youtu.be/pKCr1DY12XE?t=17740)

**Comment by markvetx** [comment]
This issue is still present even after #4894

**Comment by esanhueza** [comment]
Yeah, it seems casters must change to melee if the target is out of sight and only try to cast again after successfully reaching the target. Right now they try to cast constantly (even when moving) without accounting for their last action.
About the delay, it seems that there is some kind of delay between actions, so if you stop (interrupt, silecence, LoS, etc) one action, they wait for their "next turn" to decide what to do.
I will try to fix this issue during the week. But it would be great if someone can digest the behavior of casters or at least compile some videos of how they should behave.

**Comment by markvetx** [comment]
Could this be related to SAI?

**Comment by aradep** [comment]
NPC repositioning when LoS is broken just needs to be tweaked. Current code is selecting a location that is in line-of-sight but still far away from the player, while blizzlike behavior is to run straight into melee range. [See this video as an example.](https://youtu.be/pKCr1DY12XE?t=17740)

I think this should be given a high priority, as it affects most caster mobs and is frequently encountered in normal gameplay. Fixing this will make NPC behavior pretty much perfect.

**Comment by heyitsbench** [comment]
I believe this has been resolved by 8f127f9e2135a70cdb5573d052f50304d1b3875c.

**Comment by elthehablo** [comment]
> I believe this has been resolved by [8f127f9](https://github.com/azerothcore/azerothcore-wotlk/commit/8f127f9e2135a70cdb5573d052f50304d1b3875c).

Correct, although might not work correctly if 64 cast flag is missing or init timers are too high.
