### ISSUE TITLE
Quest "The Family and the Fishing Pole" Crashes World Server Upon Completion in Aberdine

### ISSUE THREAD

**Issue by PerryCS** [azerothcore/azerothcore-wotlk#3741]
Quest "The Family and the Fishing Pole" Crashes World Server Upon Completion in Aberdine.

##### CURRENT BEHAVIOUR:

I created a Hunter Female in Darnasses.  Did every single quest available.  Did the Gryphon Quest to take me to Adberdine.  He is right near the dock by the water.    The quest "The Family and the Fishing Pole" once turned in... crashes the world server.  Logging back in, it crashes instantly over and over.  If I restore a VM snapshot before I do this quest.. and continue questing... the game does not crash.  If I go back anytime to do the quest it crashes the server instantly again.

https://wow.gamepedia.com/The_Family_and_the_Fishing_Pole

https://www.wowhead.com/npc=10216/gubber-blump#screenshots

##### EXPECTED BLIZZLIKE BEHAVIOUR:

World server doesn't crash.  :)

##### STEPS TO REPRODUCE THE PROBLEM:

1. I did all quests in Darnassus (creating a female hunter).
2. Went to Aberdine.
3. Went around gathering every ! I could see.
4. I did the fishing quest first.  Upon completion it crashes the world server and kicks you out.  And then crashes over and over as soon as you log back in.

##### EXTRA NOTES:

I can't remember if this bug was in the TrinityCore I played years ago.  Been too long.  (sorry).
Also, I have it snapshotted after the crash.  So, I can technically submit a crash dump, but, I don't know where that crash dump is in Ubuntu 20 running the worldserver...

I remember reading in the comments this quest upon completion mails you something.  Maybe that is broken??!?!  Here is what someone posted...

**Once you turn in his quests (I don't know if it's related to one, or the other, or both), he sends you a mail the following day. Attached to it is one shiny bauble. One. It is rather terrifically funny. Here is a transcript:**

##### AC HASH/COMMIT:

commit d07a34c1d5f883167db0aedaff618429dfb8f532 (grafted, HEAD -> master, origin/master, origin/HEAD)

##### OPERATING SYSTEM:

GUI Ubuntu 20.04 LTS running in QEMU 12GB of ram in VM. Ryzen 1700 16gb of ram main machine.  Geforce 1660Ti.

##### MODULES:

no

##### OTHER CUSTOMIZATIONS:

no, very clean install, only had a few hours on it before getting to Aberdine.

**Comment by Kitzunu** [comment]
I cannot reproduce on 17afcaf5cc8b

**Comment by FrancescoBorzi** [comment]
@Kitzunu you can add "Not confirmed" in such cases ;)

**Comment by Kitzunu** [comment]
Ah yes, been awake for too long too tired hehe

**Comment by PerryCS** [comment]
I'll try updating my core and DB... never done that before... always fresh installed... and see if the problem goes away...  the one you linked to 17afcaf is newer than my Oct d07a34c.

I'll snapshot the VM first and that way if I mess things up trying to update the server I can always restore back.

Will update once I do that!   Thank you for testing that.  Unsure why it does it on mine but, hopefully the new version will fix that.  👍

**Comment by PerryCS** [comment]
OK, I snapshotted the VM...  went into the azerothcore folder... ran

git pull (as the docs say to do)

and it pulled in a bunch of stuff.

I then typed

make -j 16 

and I get...

[ 12%] Built target shared
make[2]: *** No rule to make target '../src/common/AutoPtr.h', needed by 'src/common/cotire/common_CXX_prefix.hxx.pch'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:867: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2


So, I went to the main docs and did the CMAKE command from there to see if that would fix the compile problem.. and ran make again... I get the same error...

So, I have no idea what I am doing in this.  I was able to compile it before with no errors...  but, after the git pull... now it gives this error?

Any ideas?  (sorry if it's obvious to someone who is familiar with git, pulling, merging, cloning, etc...).  I have programmed quite a bit, but as for Linux, I am barely out of the novice category... 👍

**Comment by BarbzYHOOL** [comment]
follow the normal steps again is all i can say

**Comment by LukasVolgger** [comment]
Cannot reproduce the issue on commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4

If the crash still persists we can reopen the issue.

**Comment by PerryCS** [comment]
I finally had time to update and test the newer changes.  The problem has been fixed.  BTW - I had to delete my entire azerothcore directory and start from scratch to get around those build errors I was experiencing.  I updated the database (option 7) so this is the first time I have ever updated and not reinstalled from scratch ... not as easy as it could be I'm sure, but, at least it worked, and thankfully someone fixed the bug!   Works great now!  Only minor thing is the 2 clickable items on the NPC don't do anything (the speak to him and the other one).  But, who cares about that.  lol.

**Comment by Helias** [comment]
Everything you will do or report will be appreciated, this is a learning project so take this occasion to learn more about Ubuntu and AzerothCore, don't worry :wink:
Join our community on Discord if you didn't yet. https://discord.gg/wAYXfcmb
