### ISSUE TITLE
[Quest] Cold Hearted

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#3747]
##### CURRENT BEHAVIOUR:

During the quest ID 12856 you have to mount captive proto-drakes to finish the quest. After you try to mount them, you get instantly a Parachute and you can't go further with the quest.

![image](https://user-images.githubusercontent.com/55922592/99914851-7a4c4200-2d00-11eb-8108-c8803f79251a.png)

![image](https://user-images.githubusercontent.com/55922592/99914863-833d1380-2d00-11eb-90ae-319678738b50.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to ride the captive proto-drakes and go on with the quest.

YouTube Video from 2008: https://www.youtube.com/watch?v=L_JXPyfUFYI&ab_channel=wtbblue

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go 7142.458984 -2651.866211 813.410034 571
2. .q rem 12856 & .q a 12856
3. Try to mount the captive proto-drakes

##### AC HASH/COMMIT:

AzerothCore rev. 2788d495f9e8+ 2020-11-14 06:08:00 +0100 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:

None

**Comment by Hacaw** [comment]
CONCLUSION
---
I can not reproduce this issue.
I can mount the captive drakes without issue and I didn't get unmounted or parachuted.
The only issue that I found is that when you free prisoners the quest is not updated, so should we update the description ?

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Please open a new one and thx for testing @Hacaw !
