### ISSUE TITLE
Cmake Issuse

### ISSUE THREAD

**Issue by MarcusPOL** [azerothcore/azerothcore-wotlk#375]
Hello,

I did everything according to the instructions and gives me a problem when cmake.

> 
> "CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>   Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
> Call Stack (most recent call first):"

Even a little confused and maybe someone hovers me what I have to do to solve the problem?

**Comment by talamortis** [comment]
install openssl

**Comment by talamortis** [comment]
don't use the /bin in the installation

**Comment by MarcusPOL** [comment]
ohh my bad... i must use Visual Studio 14 2015 Win64.

But now have other problems with solution :P 


> 4>LINK : fatal error LNK1181: cannot open input file '..\..\modules\worldengine\deps\mysqllite\Release\libmysql.lib'

with all cores...

thanks for fast replay!

**Comment by talamortis** [comment]
k i see the problem try these .. manually locate to them in ur cmake 
[mysql_lib.zip](https://github.com/azerothcore/azerothcore-wotlk/files/762207/mysql_lib.zip)

**Comment by MarcusPOL** [comment]
i cant find modules\worldengine\deps\mysqllite\Release\libmysql.lib grrrr

**Comment by MarcusPOL** [comment]
I do not know, yesterday I erased everything and installed from scratch according to the guide, and unfortunately for 10 64bit win nothing works.


detriment.

Apparently I have to buy a vps on Linux.

**Comment by Refuge89** [comment]
I test it.

Only works in visual studio 2015 enterprise. (community not work)

So i think can closed issue.

**Comment by electricmessiah** [comment]
Cmake 3.9, OpenSSL 64 1.01f - Cmake cannot find OpenSSL. I've installed OpenSSL a few different times in different locations and using the /bin option. No dice.

`CMake Error at C:/Games/Tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES)
Call Stack (most recent call first):
  C:/Games/Tools/cmake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  modules/worldengine/nucleus/src/cmake/macros/FindOpenSSL.cmake:175 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)`

**Comment by StygianTheBest** [comment]
This is wrong. It works fine in VS Community 2015. 99% of these CMAKE issues are due to using the wrong versions of Boost or OpenSSL. This should be closed.

**Comment by STARRHELD** [comment]
I deem this issue non-valid, if you seek any assistance in the future please join our Discord and talk to us immediately in the support channels. Thank you.
