### ISSUE TITLE
[Quest] "When cows come home" wrong text.

### ISSUE THREAD

**Issue by CyberFoxHax** [azerothcore/azerothcore-wotlk#3770]
[[When cows come home]](https://www.wowhead.com/quest=10337)

##### CURRENT BEHAVIOUR:
I don't know what the real text is supposed to be but right now it looks like this:

> Bessy says: Thank you for bringing back my Bessy, $N. I couldn't live without her!

the cow says this 2 times during the escort.

##### OPERATING SYSTEM:
Server: Debian 10
Client: Windows 10

##### AC HASH/COMMIT:
e1bf18374124ff05ab41f8014f001d27af1ab865

**Comment by Voxstrasza** [comment]
well, it seems that Bessy is supposed to say this:

```
    Mooooo...
    Moooooooooo!
```

**Comment by Hacaw** [comment]
Tested and reproduced on commit: https://github.com/azerothcore/azerothcore-wotlk/commit/885f45c63c10c96d8a955cf5c659e91acf325a92

@CyberFoxHax I think there is also the issue that Bessy is using the text used by the farmer even when you finish the quest.

We need to update the text used by the farmer and the cow in the database. I will take a closer look on the solution and will try to provide a pull-request. 

Check the image below:
![image](https://user-images.githubusercontent.com/6963500/100639830-5a3f0300-333e-11eb-8f23-d8943ec90053.png)
