### ISSUE TITLE
[Naxxramas] Slime debuff persistent through death

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3776]
##### CURRENT BEHAVIOUR:
If a toon dies from [Slime](https://wotlkdb.com/?spell=28801) in Thaddius' room in Naxxramas, there is a chance that the debuff is not properly removed after releasing spirit. I could'nt find any relation to classes and/or specs.
Its probably related to the Thaddius encounter itself, since thats the only situation when some toons of my raid die from it. 3-5 out of 20 toons who died from slime kept the debuff after releasing each wipe. Every time it happened, the raid was running Thaddius phase 2. 

Intentionally killing the whole raid out of combat from the [Slime](https://wotlkdb.com/?spell=28801) debuff does NOT make any toons keep it after releasing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I could'nt find any prove that [Slime](https://wotlkdb.com/?spell=28801) is removed 100% on death. But it feels too wrong to assume it could be blizzlike the way it is.

##### STEPS TO REPRODUCE THE PROBLEM:
- Take a raid to Thaddius
- .kill his adds
- let the raid die from slime while thaddius hunts them

##### EXTRA NOTES:
[Footage](https://cdn.discordapp.com/attachments/717079289392267315/772238804445560832/unknown.png)

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by Si1ker** [comment]
How even people get or "die" that?  : S

**Comment by Voxstrasza** [comment]
> 
> 
> How even people get or "die" from that? : S

knuckle draggers

**Comment by Si1ker** [comment]
I mean dying in Naxx is nearly impossible unless you afk , that spell is caused by that green-slime thing (water) in the environment that does not move, does not attack, does not attack you.

So just trying to understand this report, your players afk in the slime water, they died, they come back to the keyboard and when they released they still have the debuff??

**Comment by 55Honey** [comment]
Im a multiboxer and my movement wasnt good enough to make the jump from the platforms down to Thaddius at the start ;-)

**Comment by Voxstrasza** [comment]
> 
> 
> I mean dying in Naxx is... weird.
> 
> That spell is caused by that green-slime thing (water) in the environment that does not move, does not attack, does not attack you.
> 
> So just trying to understand this report, your players afk in the slime water, they died, they come back to the keyboard and when they released they still have the debuff??

on thaddius this could actually be an issue; if a raid leader calls a wipe everyone will jump off into the slime, and if you're not in range of thaddius he'll start aoe blasting the room.

also, if someone misses the jump, they could potentially die en route to the platform to try again and be stuck with the debuff

but if you die in naxxramas you should probably throw your computer away

**Comment by Si1ker** [comment]
"but if you die in naxxramas you should probably throw your computer away"
G O L D  🤣

**Comment by 55Honey** [comment]
> but if you die in naxxramas you should probably throw your computer away

I won't do that. I'm happy to entertain though :-P

**Comment by Voxstrasza** [comment]
> 
> 
> "but if you die in naxxramas you should probably throw your computer away"
> G O L D 🤣
> 
> Ok, will try to repro the issue later 🐱

I'll take a look too

I'm sure a lot of us have been in raids with keyboard drooling idiots that for some reason can't make that thaddius jump and somehow end up wiping the raid, there's always one person

**Comment by 55Honey** [comment]
> I'm sure a lot of us have been in raids with keyboard drooling idiots that for some reason can't make that thaddius jump and somehow end up wiping the raid, there's always one person

And now imagine that person plays all 25 toons ;-)
