### ISSUE TITLE
Equipping [fishing pole] staff possible without enough bag space

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3779]
##### CURRENT BEHAVIOUR:
When ones inventory is full and the toon wears a main hand + offhand item, it is currently possible to equip a [fishing pole] staff, even though the toon has no bag space to store both items. This results in the player being forced to delete the shield/offhand.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Since it's not possible to check a 3.3.5 live realm and theres no footage from back then to be found, I had a few people try official Classic realms. The game does not allow the fishing pole to be equipped on these servers. A try results in "Inventory full" so there seems to be a check, if both items can be stored before the equip process is induced.

##### STEPS TO REPRODUCE THE PROBLEM:
- Fill all your bag slots. have the toon yield a mainhand weapon and a shield.
- Right click a [fishing pole] staff in your inventory. The formerly worn main hand will go to the slot where the [fishing pole] staff was while the shield is stuck at the mouse and can't go anywhere.

##### EXTRA NOTES:
The automatic mail system will return the item without an enchant.

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by r0m1ntik** [comment]
![Снимок экрана 2020-11-26 в 22 03 26](https://user-images.githubusercontent.com/40755539/100391330-5b68eb00-3033-11eb-87d5-cf0f5aa5f225.png)

"This item cannot be exchanged" no bag space

**Comment by 55Honey** [comment]
I must admit that i can not reproduce it with a fishing pole either.  But it works with a staff. Editing initial post.

**Comment by 55Honey** [comment]
https://cdn.discordapp.com/attachments/717079797280538695/784127805293068298/2020-12-03_19-40-56.mkv

Tested it with a staff again. Still works. Sorry for confusing it with a fishing pole, its been a while :-)

**Comment by r0m1ntik** [comment]
Confirm with a staff
[350f18106826f61d6c6cb76faffcc09bc6975dbb](https://github.com/azerothcore/azerothcore-wotlk/commit/350f18106826f61d6c6cb76faffcc09bc6975dbb)

**Comment by heyitsbench** [comment]
Still an issue as of https://github.com/chromiecraft/azerothcore-wotlk/commit/ce27bbbc86b73279c771a819073c2a5f96487519.
