### ISSUE TITLE
DK chain quest bug

### ISSUE THREAD

**Issue by jubel02** [azerothcore/azerothcore-wotlk#378]
Hi i was testing DK starting zone and found this bug

There are many invisible **creatures** during the quest The Scarlet Apocalypse.

I am not sure it is right to remove them or change spawn phase.

So here is the GUIDs of all of them.
130793
130574
130815
130792
130733
130722
130721
130658
130602
130570
130743
130608
130567

**Branch master**

**AC hash/commit 7408b67629386759fe36b05b6d2d43899f5a278d**:  

**Win 10 64 bit**:  

**Modules**:  No.

**Other Customizations**: Are you using any core/db patches or other customizations? No.

**Comment by Franklampardst** [comment]
Not confirm! all thing working good . i think you get quest complete with GM / on and teleport on that side of map . And your phase get Another phase.

**Comment by Viste** [comment]
Not confirm! all thing working good
