### ISSUE TITLE
[raid] Minor bugs ulduar

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#3782]
##### CURRENT BEHAVIOUR:

For starters, at Ulduar to the first boss, Brann is invisible when he talks
![WoWScrnShot_112620_145034](https://user-images.githubusercontent.com/31663279/100434865-6f493700-309d-11eb-8b1a-019c5cfe2cda.jpg)

A lot of anima in first boss too, maybe some replicate.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- Bronzebeard Radio's weapon and dial bubles should not apear, because it's a radio transmission.
- In the ulduar we have to much flying anima. i think we have a lot of duplicate things

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to the first boss ulduar
2. 
3.

**Comment by Si1ker** [comment]
"For starters, at Ulduar to the first boss, Brann is invisible when he talks"

- Because he says he will speak through the radio, pay attention to the dialogues when the vehicles are summoned.
