### ISSUE TITLE
(DB/Quest): Guardian of the Monument

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3788]
https://www.wowhead.com/quest=11059/guardian-of-the-monument
**SMALL DESCRIPTION**:
You need to call the guard for 35 apexis crystals, kill him and bring the quest item "head". However, the quest item never fell from two of these monsters.
Based on the characteristics of this mob (~ 140k HP) and the fact that the quest is in the location for ~ 70 level, I assume that the quest item should fall with 100% probability.

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 37d1f2b

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by LukasVolgger** [comment]
Hello @PivanDepolo and ty for your issue report. As i can see on Wowhead the drop chance is 61,17% https://www.wowhead.com/item=32697/apexis-guardians-head

![image](https://user-images.githubusercontent.com/55922592/100513799-2b733200-3170-11eb-812c-e24de2ee1d3b.png)


It may seem hard that based on the characteristics of the mob it does not drop 100% but as long as there is no blizzlike proof that it is not this issue is invalid.

Closing this.

**Comment by FrancescoBorzi** [comment]
I'm not sure about this. Wowhead is not always accurate so we can't rely on it.

Given the current circumstances, I'd set that to 100% drop chance. It's quite reasonable that you kill an NPC and you drop his head for a quest like it usually happens.

Waiting for a second opinion.

**Comment by Knindzagxg** [comment]
Drop chance for it is 100%.

Problem why it's showing 61% is due progressive dynamic system which we sadly don't have and no core have it atm.
In other words, a second you start quest, chance for that drop item is 61% and during game (Shard game), until Guardian appears it will go to 100%. It's also a party drop -> Everyone in group is able to get quest item after killing it.

**Comment by JamesGent** [comment]
I played retail at the TBC/Wotlk era and I did this quest 5-10 times. The head never failed to drop for me.

I can vouch that it should be a 100% party drop.

**Comment by FrancescoBorzi** [comment]
thanks @Knindzagxg @JamesGent for your feedback.

@PivanDepolo please test my fix: https://github.com/azerothcore/azerothcore-wotlk/pull/3796

**Comment by Voxstrasza** [comment]
as @JamesGent says, this is in fact an 100% drop.  I spent a lot of time farming that reputation.
