### ISSUE TITLE
 crash Often occur

### ISSUE THREAD

**Issue by gaosheng136** [azerothcore/azerothcore-wotlk#379]
**Description**:  crash Often occur

**Current behaviour**: I dont konw
**Expected behaviour**: I dont konw

**Steps to reproduce the problem**:

[1b379027c63+_worldserver.exe_[17-2_22-37-38].txt](https://github.com/azerothcore/azerothcore-wotlk/files/783547/1b379027c63._worldserver.exe_.17-2_22-37-38.txt)

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  1b379027c63d79717247e79c3aa8d9b67b1af399

**Operating system**:  win2008 r2

**Modules**:  no

**Other Customizations**: no

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by jubel02** [comment]
What exactly were you doing when the server crash?

**Comment by gaosheng136** [comment]
I sorry,I dont know ,myserver have 30 online player

**Comment by td1tfx** [comment]
The same problem, when i improve the memory up to 8G, the problem solved.

**Comment by starrheld** [comment]
Yes please monitor your PC/Servers usage, like CPU/RAM. Please provide with your specs, not able to read txt on me phone. :)

**Comment by gaosheng136** [comment]
my server memory is 32G

**Comment by Deku** [comment]
Closing because of the date of the report. If this still happens, please comment here.
