### ISSUE TITLE
Leave from the dungeon search.

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#3791]
**SMALL DESCRIPTION**:
When leaving the dungeon, by exiting the party, teleports to the cemetery in Durotar. Both the alliance and the horde.

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. 37d1f2b

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by LukasVolgger** [comment]
Cannot reproduce this issue on commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4. If i leave the group while i'm in the dungeon it teleports me exactly to the location i was before. 

Please add more detailed informations to your issue reports.
