### ISSUE TITLE
Transmog - Eluna

### ISSUE THREAD

**Issue by iMerdjaoui** [azerothcore/azerothcore-wotlk#38]
Hello,
Are those scripts compatible with azerothcore? I tried transmog
`error: patch failed: src/server/game/DataStores/DBCStores.cpp:122
error: src/server/game/DataStores/DBCStores.cpp: patch does not apply
error: patch failed: src/server/game/DataStores/DBCStores.h:134
error: src/server/game/DataStores/DBCStores.h: patch does not apply
error: patch failed: src/server/game/DataStores/DBCStructure.h:1171
error: src/server/game/DataStores/DBCStructure.h: patch does not apply
error: patch failed: src/server/game/DataStores/DBCfmt.h:75
error: src/server/game/DataStores/DBCfmt.h: patch does not apply
error: patch failed: src/server/game/Entities/Player/Player.cpp:12074
error: src/server/game/Entities/Player/Player.cpp: patch does not apply
error: patch failed: src/server/game/Entities/Player/Player.h:29
error: src/server/game/Entities/Player/Player.h: patch does not apply
error: patch failed: src/server/game/Handlers/SpellHandler.cpp:26
error: src/server/game/Handlers/SpellHandler.cpp: patch does not apply
error: src/server/scripts/Custom/custom_script_loader.cpp: No such file or directory
error: patch failed: src/server/scripts/Spells/spell_generic.cpp:38
error: src/server/scripts/Spells/spell_generic.cpp: patch does not apply
error: patch failed: src/server/worldserver/worldserver.conf.dist:3719
error: src/server/worldserver/worldserver.conf.dist: patch does not apply
`

**Comment by mik1893** [comment]
you have to rework patches to make those work with this core - you cannot simply hope to apply a patch for trinitycore on a completely different rev.

Transmog can be implemented (i've personally done it myself)

**Comment by Draztal** [comment]
mik1893 can send the patch or diff for Transmog
