### ISSUE TITLE
[NPC][TBC] Spirit of Ar'tor

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#382]
** Description **:

** Current Behavior **: Tell Us What Happens
Wowhead.com/npc=21318 is invisible

** Expected Behavior **: Tell us what should happen instead
At the end of the mission
Wowhead.com/quest=10528
Npc = 21318 does not appear, it is in invisible mode, therefore we can not continue with the chain of missions.

** AC hash / commit **:

Https://github.com/azerothcore/azerothcore-wotlk/commit/7408b67629386759fe36b05b6d2d43899f5a278d

**Comment by starrheld** [comment]
Fix:
```SQL
DELETE FROM `spell_area` WHERE `spell`=60197 AND `area`=3752;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES
(60197, 3752, 10528, 0, 0, 0, 2, 1, 64, 0);

DELETE FROM `spell_area` WHERE `spell`=60194 AND `area`=3752;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES
(60194, 3752, 0, 10528, 0, 0, 2, 1, 0, 11);
```

**Comment by talamortis** [comment]
open a PR @starrheld  :D
