### ISSUE TITLE
[Ulduar] [Hodir] Spells incorrectly ignoring resist

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3831]
CURRENT BEHAVIOUR:
During the Hodir encounter in Ulduar it is not possible to resist any incoming Frost damage from falling Icicles and Freeze.
(Not sure about spell ids for both)

EXPECTED BLIZZLIKE BEHAVIOUR:
Frost resistance should allow for both spells to be (partly)resisted.

STEPS TO REPRODUCE THE PROBLEM:
- Take a toon to Ulduar in GM mode
- Wear frost resistance:
.additem 43583
.additem 43584
.additem 43585
- Start the Hodir encounter
- Stand in Icicles when they fall down and watch incoming damage/resistance

EXTRA NOTES:
[Footage](https://cdn.discordapp.com/attachments/768525612180570143/783418602266558494/unknown.png)
[Youtube](https://youtu.be/d8Wqg5eP6V8?t=108)  (Icicle resisting 5600 at 1:52)
[Youtube](https://youtu.be/d8Wqg5eP6V8?t=199)  (Icicle resisting 5600 at 3:18)
[Youtube](https://youtu.be/d8Wqg5eP6V8?t=210)  (Freeze resisting 1745 at 3:34)
[Youtube](https://youtu.be/d8Wqg5eP6V8?t=210)  (Freeze resisting 2416 at 4:58)

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by 55Honey** [comment]
I assume the relevant file for this encounter is src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
According to it, there are [Icicle (small)](https://wotlkdb.com/?spell=62457) and [Icicle (larg)](https://wotlkdb.com/?spell=65370) for the damage/knockback part of Icicle. 
Also, ive found [Freeze](https://wotlkdb.com/?spell=62469) in that file.

**Comment by gengarshadowball** [comment]
A spellfix needs to be applied to each spell just like [this mimiron spell](https://github.com/azerothcore/azerothcore-wotlk/blob/224a3308e693fe10f86aff20e9ec8760ec39638f/src/server/game/Spells/SpellMgr.cpp#L5192). We must remove the bits that make the spell ignore resistances like that mimiron spell fix.

**Comment by gengarshadowball** [comment]
I confirm the issue on AzerothCore rev. 6872a3424489
![image](https://user-images.githubusercontent.com/60325009/101262437-ad49f900-3736-11eb-9f04-f6ff73a008ed.png)

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/e2d7dc9bd7fc636469e46b82587a92f43e7825d9

this commit no bug.
