### ISSUE TITLE
Feature: Create a script (db_assembler.bat or db_assembler.exe) for windows systems.

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#3846]
**Describe your feature request or suggestion in detail**

Create a script to assemble the AzerothCore database in windows builds.

**Describe a possible solution to your Feature or Suggestion in detail**

The script may be a batch file .bat or a binary file .exe that scan the data/ folder and assemble the specific .sql files.

**Additional context**

**Comment by FrancescoBorzi** [comment]
@skxawng-cu the DB assembler already supports Windows, you just have to use it with [git bash](https://gitforwindows.org/).

https://www.azerothcore.org/wiki/Database-Setup

**Comment by skxawng-cu** [comment]
@FrancescoBorzi thanks, I tested and works fine with git bash.
