### ISSUE TITLE
Battered Hilt Questline: Thalorien Dawnseeker

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#3851]
##### CURRENT BEHAVIOUR:

Not only the body was missing, but after quest complete there's no text.

![image](https://user-images.githubusercontent.com/60325009/101269038-f19ebe80-3761-11eb-8fd2-ab83f64b3a6a.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

> I confess that I did not expect Thalorien's spirit to recognize you as the heir to Quel'Delar, but I defer to his judgment. You may enter the Sunwell, but I remind you that you are a guest in our most sacred of precincts, and you should act accordingly.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .q a 24535 (Alliance)
2. .tele sunwell
3. .Try to find the body in the dead scar
4. You didn't find the body so repeat step 2
5. .q c 24535
6. Talk to the NPC in the entrance and see that the quest has no text.

##### EXTRA NOTES:

Check for information:
https://www.wowhead.com/quest=24535/thalorien-dawnseeker

##### AC HASH/COMMIT:

d4b71dc70d3f

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

None

**Comment by LukasVolgger** [comment]
Working on it 👍🏻

**Comment by wizzymore** [comment]
Expect of the missing quest text, there is no issue here, could complete the quest based on this video:
https://www.youtube.com/watch?v=_YlPOW1IU0U

https://prnt.sc/wamarv
https://prnt.sc/wambb8

**Comment by Raelorasz** [comment]
I think this one can be closed, the issue was addressed in https://github.com/azerothcore/azerothcore-wotlk/pull/3852

**Comment by Sedatyf** [comment]
Indeed! Thank you @Raelorasz!
