### ISSUE TITLE
[Raid] [BattleForMountHyjal] Boss's spell should not be interrupt 

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#3854]
[Raid] [BattleForMountHyjal] Boss's spell should not be interrupt 

##### CURRENT BEHAVIOUR:
All Boss of BattleForMountHyjal can be interrupt while cast spell! 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
boss should immue with interrupt

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### EXTRA NOTES:

cause the record of creature_template field mechanic_immune_mask was unflaged with MECHANIC_INTERRUPT

just modify the value with MECHANIC_INTERRUPT flag enable. 

they are blizzard liked after these modify

**Comment by Maurowin** [comment]
Please provide Hash commit pls

btw i confirm

**Comment by LukasVolgger** [comment]
@Maurowin you could to that do :P

**Comment by betayi** [comment]
> Please provide Hash commit pls
> 
> btw i confirm

i thought the hash commit is "commit c563b3a6ad48cb6c1445d244ade52417d63698f9" ? the last line of git log
or the result after typed server info : "01c830ed4691+" ?

**Comment by betayi** [comment]
> Please provide Hash commit pls
> 
> btw i confirm

or

commit 01c830ed46918fae2cbaa8b48a6b8cf690ba909e

the first line of git log 

sorry, i am not good at this

**Comment by LukasVolgger** [comment]
You can easylie find it in your server log/console after starting the worldserver :)

**Comment by Maurowin** [comment]
> 
> 
> @Maurowin you could do that too :P

No i cant because i'am talking about mechanic. You can't in BattleForMountHyjal interrupt spell.
