### ISSUE TITLE
[Summoning Portal] [Spell] Using a summoning portal costs mana

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3856]
##### CURRENT BEHAVIOUR:
Using a summoning portal created by [Ritual of Summoning](https://wotlkdb.com/?spell=698) often costs mana. A level 80 warlock with less than ~460 mana can not use the Summoning Portal to summon another player.
![image](https://user-images.githubusercontent.com/71938210/101286845-168c4380-37ed-11eb-9a94-81a7fbca721f.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The creation of the portal done by a warlock does cost mana. The summoning itself should not.

##### STEPS TO REPRODUCE THE PROBLEM:
- Create a warlock, a priest and a warrior on 3 different accounts
- for the Warlock:
.level 79
.learn 698
.additem 6265 10
- Let the Warlock perform a ritual of summoning, priest and warrior should help
- Let the Warlock spam spells, e.g. Demon Skin until oom / below 400 mana
- The Warlock can not rightclick the Portal to summon another player while below ~460mana

##### EXTRA NOTES:
The fresh created lvl 1 priest and a warrior (no matter if lvl 1 or 80) can both use the Summoning Portal just fine, even though they do not meet the ~460mana condition. Leveling the priest to 80 results in the same behavior as the warlock. No usage of the Summoning Portal possible below ~460 mana.

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by aradep** [comment]
<details><summary>Found this, for anyone looking into it. Maybe related</summary>

```src/server/game/Entities/GameObject.cpp```
![image](https://user-images.githubusercontent.com/61268368/101297471-928f8700-37ff-11eb-8bb3-823495e2c463.png)
</details>
Spell 61993 has a 12% base mana cost, which explains why the warrior and lvl 1 priest aren't affected.

**Comment by Kitzunu** [comment]
It must be some other trigger spell... Because I flopped this into DBC Data corrections 
```cpp
    ApplySpellFix({ 61993, 62330, 698 }, [](SpellEntry* spellInfo)
    {
        spellInfo->powerType = POWER_HEALTH;
    });
```
And it still says "Not enough mana".
and I know nothing is wrong with the spellInfo->powerType change because when I did this spell 698 (Ritual of Summoning) now cost health instead of mana

**Comment by Kitzunu** [comment]
Got the fix for ya :D https://github.com/azerothcore/azerothcore-wotlk/pull/4013
