### ISSUE TITLE
[Shaman] [Talent] Elemental Focus

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3859]
CURRENT BEHAVIOUR:
[Elemental Focus](https://wotlkdb.com/?spell=16164) can proc from healing spells like [Riptide](https://wotlkdb.com/?spell=16246) and [Lesser Healing Wave](https://wotlkdb.com/?spell=49276).

EXPECTED BLIZZLIKE BEHAVIOUR:
The talent description of [Elemental Focus](https://wotlkdb.com/?spell=16164) clearly states that it is meant to be procced from Fire-, Frost- or Nature **damage** spells. 

STEPS TO REPRODUCE THE PROBLEM:
Create a shaman
.level 79
Spec [Elemental Focus](https://wotlkdb.com/?spell=16164) (Elemental Tier 3)
.learn all my spells
cast [Lower Healing Wave](https://wotlkdb.com/?spell=49276) on yourself. It will proc clearcasting on a crit.

EXTRA NOTES:
Especially when combined with Tidal Waves, this can be seriously abused to gain lots of procs.
![image](https://user-images.githubusercontent.com/71938210/101401909-4d3c8980-38d3-11eb-95fd-1eef0e7bf0c5.png)

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by Hacaw** [comment]
CONCLUSION
---
I can reproduce this issue.

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: adf436c9
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Kitzunu** [comment]
Here's the fix, please test it =) https://github.com/azerothcore/azerothcore-wotlk/pull/4014

**Comment by Shineslippers** [comment]
Still exist or comeback idk. https://github.com/chromiecraft/chromiecraft/issues/2301 `.aura 16164` `.cast 331`
![WoWScrnShot_112321_100119](https://user-images.githubusercontent.com/85256266/142982590-8dcc717c-dace-4520-874f-55bf5dcb3a9f.jpg)

**Comment by UltraNix** [comment]
https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2#Shaman
`https://wowwiki-archive.fandom.com/wiki/Patch_3.0.2#Shaman`
