### ISSUE TITLE
[Paladin] [Talent] Divinity does not stack with Heal-increasing buffs

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3860]
CURRENT BEHAVIOUR:
[Divinity](https://wotlkdb.com/?spell=63650) does not stack with [Improved Devotion Aura](https://wotlkdb.com/?spell=20140) as well as [Tree of Life](https://wotlkdb.com/?spell=33891)-aura.

EXPECTED BLIZZLIKE BEHAVIOUR:
Divinity should not share stacks with these two.

STEPS TO REPRODUCE THE PROBLEM:
Create a new paladin.
.level 79
.learn all my spells
Spec 5/5 divinity and spam Flash of Light(Rank 1) on yourself. Note the min/max amount.
Spec 3/3 Improved Devotion Aura. Again spam Flash of Light(Rank 1) on yourself and note the min/max amount.
There is no difference in healing gained for the paly itself.

EXTRA NOTES:
Casting Flash of Light(Rank 1) on yourself, results in 94-108 heals with 5/5 [Divinity](https://wotlkdb.com/?spell=63650) Talent.
With 5/5 [Divinity](https://wotlkdb.com/?spell=63650) AND Improved Devotion Aura, which should provide 6% healing taken on top,  it still does the exact same amount.

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by lineagedr** [comment]
https://www.mmo-champion.com/threads/694988-Improved-Devotion-Aura/page2?p=7308815&viewfull=1#post7308815

**Comment by Voxstrasza** [comment]
> 
> 
> https://www.mmo-champion.com/threads/694988-Improved-Devotion-Aura/page2?p=7308815&viewfull=1#post7308815

Good find

**Comment by UltraNix** [comment]
So it's not a bug?

**Comment by UltraNix** [comment]
@lineagedr @55Honey So it's not a bug?

**Comment by UltraNix** [comment]
I believe it's okay. I think comments are misleading. Divinity is "2in1" buff: increases healing done to you and done by you. Tree of Life/Improved Devotion aura overrides only the "increases healing done to you", so the 2nd bonus is still here.

**Comment by UltraNix** [comment]
@55Honey

**Comment by 55Honey** [comment]
Sorry, what's the ping for? I didn't follow this thread.

**Comment by UltraNix** [comment]
You wrote that Divinity should stack with Improved Devotion Aura and Tree of Life. And I've read in many places that it should not.

**Comment by 55Honey** [comment]
If the initial issue isn't valid, let's close it.
