### ISSUE TITLE
[Shaman] [Talent] Blessing of the Eternals

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3865]
CURRENT BEHAVIOUR:
[Blessing of the Eternals](https://wotlkdb.com/?spell=51555) does not award the 80% increase in chance to apply Earthliving on targets below 35%hp. It feels like it was 20% total still.

EXPECTED BLIZZLIKE BEHAVIOUR:
With 20% baseline chance and an 80% increase it should be a 100% proc.

STEPS TO REPRODUCE THE PROBLEM:
- Create a Shaman and a second toon.
- both toons: .level 79
- shaman: .learn all my spells
- shaman: spec [Blessing of the Eternals](https://wotlkdb.com/?spell=51555)
- apply [Earthliving weapon](https://wotlkdb.com/?spell=51994)
- damage the second toon below 35% hp, e.g. with a duel and spam [Healing Wave (Rank 1)](https://wotlkdb.com/?spell=331) on it after.
- Note how Earthliving will not proc 100%

EXTRA NOTES:
none

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by Kitzunu** [comment]
I can confirm this.

**Comment by Kitzunu** [comment]
Please test the fix :) https://github.com/azerothcore/azerothcore-wotlk/pull/4015
