### ISSUE TITLE
[Pit of Saron] Fix needed: Scourgelord Tyrannus breaks before Ice Cave.

### ISSUE THREAD

**Issue by arielcami** [azerothcore/azerothcore-wotlk#3876]
Tyrannus isn't spawning the mobs in front of the cave, encounter broken.

##### CURRENT BEHAVIOUR:
As you make your way to the end of Dungeon, Tyrannus [36794] should spawn a little army of undead
to protect the cave entrance, but this never happens.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Tyrannus must spawn those mobs so the cave encounter can happen, and afterwards,
make the dungeon beatable.

##### STEPS TO REPRODUCE THE PROBLEM:
1- [.go 5594.524 2012.229 798.041 571 3.854] and enter the dungeon.
2- Kill Gargelus and Agh.
3- Keep Killing mobs heading to the Cave.
4- At [.go 929.464 78.263 562.19 658 5.08] Tyrannus should spawn the army of undead.

*Please take a quick look at this vid, it shows exactly what should happen.
https://www.youtube.com/watch?v=G-sK8OaoQa8
Advance to 8:37

rev. 1b156ef7ebb7+

Win 10 pro
No Modules
![WoWScrnShot_121020_093215](https://user-images.githubusercontent.com/71854140/101963286-53d14680-3bdc-11eb-9571-f575ec6ffc37.jpg)

**Comment by Bogir** [comment]
Why do you closed this issue? Is it fixed? I think - no. 
So, let it stay opened

**Comment by loolpes** [comment]
I have this problem
I installed Azerothcore and the dungeon boss is not starting the event at the cave entrance
if this event does not start, it will not be possible to fight with the final boss of the dungeon

OBS: sorry for the mistakes, I'm Brazilian and I'm not a fan of this language
![Screenshot_1](https://user-images.githubusercontent.com/62625958/158267236-d83a5373-04d5-4b98-904f-82621de8d7a1.png)

**Comment by SilentCLD** [comment]
> I have this problem I installed Azerothcore and the dungeon boss is not starting the event at the cave entrance if this event does not start, it will not be possible to fight with the final boss of the dungeon
> 
> OBS: sorry for the mistakes, I'm Brazilian and I'm not a fan of this language ![Screenshot_1](https://user-images.githubusercontent.com/62625958/158267236-d83a5373-04d5-4b98-904f-82621de8d7a1.png)

See https://github.com/azerothcore/azerothcore-wotlk/pull/10819
