### ISSUE TITLE
[Quest] The Mark of the Nexus-King. Quest item wont drop.

### ISSUE THREAD

**Issue by CyberFoxHax** [azerothcore/azerothcore-wotlk#3877]
I tried and failed to complete this quest [[The Mark of the Nexus-King]](https://www.wowhead.com/quest=10976)
You have to run around and interact some purple spheres, which will spawn an elite mob that has a  chance to drop [[Mark of the Nexus-King]](https://www.wowhead.com/item=31941). The item should have 24% chance to drop. I killed around 30 bosses and no mark dropped. 

The item does appear in the loot table (assuming this IS the loot table):
![image](https://user-images.githubusercontent.com/7734690/101875958-87a17180-3bc6-11eb-8ceb-6ca23903a23b.png)

##### STEPS TO REPRODUCE THE PROBLEM:
This is not a "quest item" so it should be possible to do this without doing the quest chain.

you still need the key.
`.additem 29750`

##### OPERATING SYSTEM:
Server: Debian 10
Client: Windows 10

##### AC HASH/COMMIT:
e1bf18374124ff05ab41f8014f001d27af1ab865

**Comment by Kitzunu** [comment]
check if it has QuestRequired in creature loot template or if it has any conditions to it

**Comment by CyberFoxHax** [comment]
![image](https://user-images.githubusercontent.com/7734690/101897111-ff7e9480-3be4-11eb-8578-dfa5f2555e35.png)

**Comment by Kitzunu** [comment]
Could also be extremely unlucky, usually, if there are no conditions attached to it that is the reason

**Comment by Si1ker** [comment]
@CyberFoxHax change prop to 100% and test if you can get it, if you can then you are unlucky.
If still cannot get it, there's something else to change a requirement or condition probably.

**Comment by CyberFoxHax** [comment]
`UPDATE creature_loot_template
	SET Chance=100
	WHERE Item = 31941`

At first nothing changed but i restarted the server and now it drops every time. So i guess that's that.

**Comment by Kitzunu** [comment]
Dont trust wowhead :)

It is based from Player info through their addon which can be used in private servers ^^
