### ISSUE TITLE
Walk through a portal can't teleport to dungeon in City

### ISSUE THREAD

**Issue by Whyy0416** [azerothcore/azerothcore-wotlk#3879]
After commit af53598fa2d7d63021f54a4a2bd37449f31e97cf fix(Core/Game): Rest & Inn Improvements (#3780). You can't teleport to dungeon rage fire cave or jail when walk through a portal. Maybe dungeons in Dalaran affected by this commit too, but I didn't test it yet.

##### CURRENT BEHAVIOUR:
Can't teleport to dungeon rage fire cave or jail by walk through portal.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Teleport to dungeon rage fire cave or jail by walk through portal.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to Stormwind city or Orgrimmar city
2. Go to portal to rage fire cave or jail
3. Can't teleport to dungeon and no alert or warning message in both game or server side.

##### EXTRA NOTES:
I roll back to aff02b0599b29a3dd777fe5c09e89634bd84b3f8 then it works well.  

##### AC HASH/COMMIT:
48f418e7e223266e02bdd8d9f63f5d218fca89d2

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by FrancescoBorzi** [comment]
@Meltie2013 @Maurowin @BarbzYHOOL @Si1ker

**Comment by BarbzYHOOL** [comment]
can you test in another dungeon/raid to make sure?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3983

**Comment by vituchito125** [comment]
en mi servidor no deja entra a la masmorra despues que utilizaron el ojo para encontra la masmorrar seria igual a este caso ?.
modulos
mod-1v1-arena
mod-anticheat
mod-cfbg
mod-learn-spells
mod-npc-promotion
mod-top-arena
mod-transmog-master
mod-world-chat
mod_npc_enchanter
mod-npc-free profesiones

**Comment by FrancescoBorzi** [comment]
PR that fixes the issue: https://github.com/azerothcore/azerothcore-wotlk/pull/3984

**Comment by Meltie2013** [comment]
@FrancescoBorzi I have the fix for the issue that was caused. Typo in the code.

**Comment by FrancescoBorzi** [comment]
@Meltie2013 please send a PR with it asap

**Comment by Meltie2013** [comment]
Making sure its not effecting anything else.

**Comment by FrancescoBorzi** [comment]
thanks @Meltie2013 for the quickfix

@Whyy0416 @vituchito125 can you please update to latest AC version and let us know if the bug is fixed for you?

**Comment by Whyy0416** [comment]
> thanks @Meltie2013 for the quickfix
> 
> @Whyy0416 @vituchito125 can you please update to latest AC version and let us know if the bug is fixed for you?

fixed confirm.

**Comment by FrancescoBorzi** [comment]
good job @Meltie2013 and thanks @Whyy0416 for reporting the bug and confirming the solution
