### ISSUE TITLE
the karazhan raid bug: 

### ISSUE THREAD

**Issue by cnmir2** [azerothcore/azerothcore-wotlk#39]
the karazhan raid bug: 
1 the Sebastian have no script the dialog to trigger the battle of opera hall !
2 the echo of medivh could not trigger the battle of gamesman's hall 
3 the quest=9644 Nightbane is bugged in karaazhan you klick the blacked urn nothing happen !

and  could you close the bwl i submit to your repo issue the bwl boss 2 and last boss can give dialogue to trigger battle! i test another once !! my fault!
##

**Comment by Bodeguero** [comment]
Its project SunWellCore its return:

http://sunwell.pl/
