### ISSUE TITLE
DB errors when execute world

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#394]
**Description**:
When execute world db sql make with db_assembler you have errors http://paste2.org/4yjWCYVD
**Current behaviour**: Tell us what happens
db errors and sad face
**Expected behaviour**: Tell us what should happen instead
All ok and happy face
**Steps to reproduce the problem**:

1. Use db_assembler
2. Execute world db file
3. sad face

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
Debian 8
**Modules**:  Are you using modules? if yes, list them
no
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
no

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Inifield** [comment]
MySQL server has gone away, alllow more packets

**Comment by Viste** [comment]
No i try to add lines in console and
[Err] 1231 - Variable 'character_set_client' can't be set to the value of 'NULL'
and others....
