### ISSUE TITLE
[CORE][SPELL] Mirror Image

### ISSUE THREAD

**Issue by TW1NKLET** [azerothcore/azerothcore-wotlk#395]
**Description**: Visual Bug

**Current behaviour**: When **[Iron Boot Flask]** is active, and you activate **[Mirror Image]** the Dwarf is mirrored and not your "self image".

**Expected behaviour**: I can't confirm if your self image should appear or just the Dwarf, but the Dwarf model is bugged regardless.

**Steps to reproduce the problem**:

1. .additem 43499 and use it
2. /cast Mirror Image
3. Look 

![IMG1](http://i.imgur.com/zyCktKh.png)
![IMG2](http://i.imgur.com/rVxXLwl.png)

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  b2b365b2096f

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
is this still the issue? can anyone confirm?

**Comment by talamortis** [comment]
@starrheld  can you test :D?

**Comment by talamortis** [comment]
fixed with commit on #396

**Comment by talamortis** [comment]
fixed with https://github.com/azerothcore/azerothcore-wotlk/commit/bd799ecd5b064300cc198d3a7aa982a82c34e175
