### ISSUE TITLE
[CORE][ITEM] Iron Boot Flask / Orb of the Sin'dorei

### ISSUE THREAD

**Issue by TW1NKLET** [azerothcore/azerothcore-wotlk#396]
**Description**: Visual Bug

**Current behaviour**: Does not change your modelid in relation to gender

**Expected behaviour**: When you are a blood elf female, you use [Iron Boot Flask], you turn into a male dwarf, and then if you use the [Orb of the Sin'dorei] it should turn you into a blood elf male. This is the correct behavior like retail.

**Steps to reproduce the problem**:

1. .additem 43499 and use it
2. .additem 35275 and use it
3. Look 

![IMG1](http://i.imgur.com/3z1T1nA.png)
![IMG2](http://i.imgur.com/a5cr5Cx.png)

**Branch(es)**: Master

**AC hash/commit**:  b2b365b2096f

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by starrheld** [comment]
Possible fix:
https://github.com/TrinityCore/TrinityCore/commit/24bad7fd20e4673ca9b5a0996d877a70dbd6588e

**Comment by talamortis** [comment]
Fixed nice find @starrheld

**Comment by starrheld** [comment]
@talamortis Did you check that the gender is actually removed when aura of the item is removed? If you use Iron Boot Flask and then Savory? I usually got stuck with a male character ;)

**Comment by talamortis** [comment]
I

**Comment by talamortis** [comment]
fucking phone and yeah I did :)
