### ISSUE TITLE
[CORE][SPELL] Sunder Armor / Expose Armor

### ISSUE THREAD

**Issue by STARRHELD** [azerothcore/azerothcore-wotlk#397]
**Description**: Stacking Bug

**Current behaviour**: **Sunder Armor** stacks with other armor reduction debuffs.

**Expected behaviour**: **Sunder Armor** should not stack with other armor reduction debuffs, in this case **Expose Armor**

**Steps to reproduce the problem**:

1. Cast **Sunder Armor** (Warrior)
2. Cast **Expose Armor** (Rogue) 

![IMG1](http://i.imgur.com/EfPZiez.jpg)
![IMG2](http://i.imgur.com/q3J3vwf.jpg)

_Same for_
**Armor Reduction (Minor) -> Curse of Weakness, Faerie Fire and Sting**
**Spell Hit debuff -> Improved Faerie Fire and Misery**
**Armor Reduction (Major) -> Acid Spit, Expose Armor and Sunder Armor**

**Branch(es)**: Master

**AC hash/commit**:  b2b365b2096f

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by STARRHELD** [comment]
Closing down this issue since there's not been any progress or discussion going on.
We might re-open this issue once there's been a breakthrough in progress.

**Comment by lineagedr** [comment]
Check spell_group for spells 58567 - Sunder Armor and 8647 - Expose Armor they're already in there. They may stack but their effect doesn't. 

![wowscrnshot_101517_154342](https://user-images.githubusercontent.com/12139798/31584875-d4b8ee60-b1bf-11e7-8625-67cf887eb69c.jpg)


![wowscrnshot_101517_154358](https://user-images.githubusercontent.com/12139798/31584876-d7e70694-b1bf-11e7-88b7-7c1cbdae8f25.jpg)



![wowscrnshot_101517_154419](https://user-images.githubusercontent.com/12139798/31584877-dce82038-b1bf-11e7-862a-743c9141337b.jpg)
