### ISSUE TITLE
you cannot enter the instances

### ISSUE THREAD

**Issue by vituchito125** [azerothcore/azerothcore-wotlk#3983]
I do not know how the problem happened but a band put together a masmorra and used the eye but from there they could not go through the portal
![image](https://user-images.githubusercontent.com/53723504/101992741-66528b00-3c83-11eb-820f-a4c5f28fb7c0.png)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3879
