### ISSUE TITLE
Can't learn some npc spells via command

### ISSUE THREAD

**Issue by mikey4901** [azerothcore/azerothcore-wotlk#400]
I've just found out thati can't use some npc spells,and it's not just the ".learn" command that's not working,i can't use the ".aura" or ".cast" commands with these spells either 
When i try to learn one of these spells by command,the chatbox just says: "Spell "xxx" cannot be learned/casted by using a command.Keep in mind that these spells exist in the game.
http://i65.tinypic.com/2w7odg2.jpg

**Comment by talamortis** [comment]
some of the spells you are trying to use onyourself only creatures can cast, if you make a creature script and put the spells in, they work correctly.
