### ISSUE TITLE
quest can be repeated

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4000]
‘Treats for Great-father Winter ’（id= 6962）quest can be repeated 
This quest not be repeated. If it can be repeated, all players can use this quest get a huge sum gold

AzerothCore revision : 4cb0c9f+ 2020-12-10 05:57:54 +0000 (master branch)
OS:ubuntu 18.04
Module:mod-anticheat

**Comment by Helias** [comment]
There is a flag which make a quest repeatable or not, should be easy to fix this through Keira3

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4004
