### ISSUE TITLE
Feature: improve our Docker structure [$50]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4006]
## Current setup

We currently have a [Docker setup](https://www.azerothcore.org/wiki/Install-with-Docker) that allows the user to install AC easily with a simplified procedure.

The building blocks of the current Docker setup are:

- everything inside the [docker/](https://github.com/azerothcore/azerothcore-wotlk/tree/master/docker) directory
- [docker-compose.yml](https://github.com/azerothcore/azerothcore-wotlk/blob/master/docker-compose.yml)
- [.env.dist](https://github.com/azerothcore/azerothcore-wotlk/blob/master/.env.dist)

It currently allows the user to:

- build locally an image of AzerothCore on the current user's branch and version
- run the locally-built image

There are 4 docker containers:

- the [database container](https://github.com/azerothcore/azerothcore-wotlk/tree/master/docker/database), quite self-contained and independent from the others. It can also be run as standalone.
- the [build container](https://github.com/azerothcore/azerothcore-wotlk/tree/master/docker/build) which executes the compilation, generating the `worldserver` and `authserver` binaries and places them respectively under `docker/worldserver/bin` and `docker/authserver/bin`
- the [authserver container](https://github.com/azerothcore/azerothcore-wotlk/tree/master/docker/authserver) which runs the `authserver` binary (generated by the Build) 
- the [worldserver container](https://github.com/azerothcore/azerothcore-wotlk/tree/master/docker/worldserver) which runs the `worldserver` binary (generated by the Build) as well as reading the client data placed in `docker/worldserver/data` **placed there manually by the user**.

Also, the docker images are built in our CI, the `build container` is also executed to check that the build does not fail.

## Ideal setup

In addition to the current features, our docker setup should also:

- publish the images of containers on docker hub, allowing the user to pull  and use them without necessarily building them locally (but still giving the possibility to do so)
- have an extra container for the data files, allowing the `worldserver container` to simply read those data files instead of requiring the user to place them manually inside `docker/worldserver/data` (however it would be nice to still keep the possibility of adding the data files manually)

**Comment by chrisg-carleton** [comment]
Is anyone working on this? I'd like to take a crack at it.

**Comment by FrancescoBorzi** [comment]
> Is anyone working on this? I'd like to take a crack at it.

@chrisg-carleton not that I'm aware of, please go ahead :)

**Comment by Yehonal** [comment]
I've completed this with the latest docker system, I'm going to fix the latest bug of this system these days and improving small stuff.

But the requirements of this issue has been satisfied. I'll claim the bounty and reinvest it into the AC project

**Comment by Yehonal** [comment]
![image](https://user-images.githubusercontent.com/147092/115964517-2949af80-a525-11eb-997c-6a6e84851c31.png)
