### ISSUE TITLE
Quest: They're Alive! Maybe... 

### ISSUE THREAD

**Issue by Okuluss** [azerothcore/azerothcore-wotlk#4009]
Quest: They're Alive! Maybe... is bugged as no researcher is spawning. Quest can still be completed, though.

##### CURRENT BEHAVIOUR:
By destroying "webbed creature" a random mob will spawn in it's place but none of the missing researchers for the actual quest. Even if it counts for quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Researcher has to spawn and flee with various text as e.g. "We're free! We're free!" or others.
please also see here: https://www.youtube.com/watch?v=RP3a8ENPKQY

##### STEPS TO REPRODUCE THE PROBLEM:
go to Bloodmyst Isle and accept quest at Researcher Cornelius.
start to destroy "webbed creature" in the vicinity.

##### EXTRA NOTES:
I am no programmer at all but I checked the corresponding script (npc_webbed_creature) and I noticed that perhaps there is a missing line as in case 0 there is no spawn of a creature. I added the line in bold. The npc has the correct ID. Dont knwo how to make them flee and say something.
...
case 0:
    if (Player* player = killer->ToPlayer())
       player->KilledMonsterCredit(NPC_EXPEDITION_RESEARCHER);
    **spawnCreatureID = NPC_EXPEDITION_RESEARCHER;**
    break;
...

##### AC HASH/COMMIT:
AzerothCore rev. f1be5f940540+
(not sure if thats the required number)

##### OPERATING SYSTEM:
Docker installation

##### MODULES:
SoloLFG, 1v1Arena, AhBot, AutoBalance

**Comment by r0m1ntik** [comment]
[TrinityCore/commit/d59f111](https://github.com/TrinityCore/TrinityCore/commit/d59f111cabb0bb6e2709026f03657826f8c96ecb)

**Comment by Helias** [comment]
Fixed! let's test it!
https://github.com/azerothcore/azerothcore-wotlk/pull/4035
