### ISSUE TITLE
[FIXED can be added] Creature (GUID: 6432 Entry: 3197) has wrong spell 0 defined in `auras` field.

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#401]
**Description**: 
Creature (GUID: 6432 Entry: 3197) has wrong spell 0 defined in `auras` field.

**Current behaviour**: After launching the server, it printed this error:
Creature (GUID: 6432 Entry: 3197) has wrong spell 0 defined in `auras` field.

**Expected behaviour**: There shouldn't be any error

**Steps to reproduce the problem**:

1. Launch the server
2. Wait
3. Error (there are many more though)

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
Master (lastest)

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/54e25518c3348e62f0f490f720c342950102f772

**Operating system**:  Linux

**Other Customizations**: Bare core

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by falzard** [comment]
This will fix it.

```
UPDATE `creature_addon` SET
`guid` = '6432',
`path_id` = '643200',
`mount` = '0',
`bytes1` = '0',
`bytes2` = '0',
`emote` = '0',
`auras` = ''
WHERE `guid` = '6432';
```

**Comment by ShinDarth** [comment]
@falzard please open a PR to submit fixes

**Comment by talamortis** [comment]
why dont you just do 

UPDATE `creature_addon` SET `auras`='' WHERE `guid` = 6432;

since its only the aura that is causing the problem?

**Comment by falzard** [comment]
Because I was lazy so I exported the result of my GUI modification.
