### ISSUE TITLE
[PROJECT] Complaint: My contribution efforts are undermined

### ISSUE THREAD

**Issue by abebeos** [azerothcore/azerothcore-wotlk#4016]
# IF YOU DO NOT FILL THIS TEMPLATE OUT, WE WILL CLOSE YOUR ISSUE! -->

Remove this, it's nonsense.

## CURRENT BEHAVIOUR:

PR's are not merged, e.g.:

* #3874 (this related to bounty work, so, you place a bounty, then block the efforts to solve the problem)
* #3867, #3863 - super-trivial documentation changes not merged, despite beeign approved.

@FrancescoBorzi cites a "process", but then, looking at other PR's, they get merged immediately, even if they affect core/code logic:

https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+is%3Aclosed

So, something is very wrong with this.

## EXPECTED BEHAVIOUR:

* Trivial PRs are merged immediately upon approval (no "to be merged" label, which is completely redundant).
* One project member should never undermine the contributions of a newcoming developer (here: me)

If you don't want my contributions, just say it, instead of being friendly whilst in the same time blocking my efforts.

I'm an 3 decades xp dev with hw-design background, and wanted to contribute here mostly to relax a bit from heavier projects.

Do you really have the luxury to send away people like me with you no-sense "processes" and arrogant behavior of one project member?

**Comment by Voxstrasza** [comment]
cry more

**Comment by abebeos** [comment]
Oh, it's your users crying, because you alienate contributors despite this:

356 open issues, 96 open PR's

**Comment by aradep** [comment]
So... you want your PRs to be merged faster? Can't you just work in a fork?

**Comment by abebeos** [comment]
A fork? for this: #3867, #3863

it's not enough that you cannot write decent (normal) captions, you "rebel" (4th person now) to not commit them immediately.

This is called "insanity" (resisting to become better).

**Comment by Voxstrasza** [comment]
why not send shin a DM over discord and bring up your concerns like an adult, rather than make a spectacle over a public forum?

**Comment by abebeos** [comment]
> 
> 
> why not send shin a DM over discord

discord? I see.

> and bring up your concerns like an adult, rather than make a spectacle over a public forum?

Where is the public forum? This here is an issue-tracker, the perfectly valid medium for what I filed.

You go continue playing - obviously you've even lower knowledge than this @FrancescoBorzi .

Go, go!

**Comment by aradep** [comment]
"3 decades" of experience, and you haven't managed to learn professionalism 😄

**Comment by abebeos** [comment]
You're right, quite unprofessional of me to waste my time here replying to "contributors", instead of waiting what the "members" have to say.

Now go away, open some fork to play with...

**Comment by abebeos** [comment]
> azerothcore deleted a comment from Voxstrasza 11 hours ago 

you should really not delete comments of others.
