### ISSUE TITLE
problemas para entra a la icc

### ISSUE THREAD

**Issue by vituchito125** [azerothcore/azerothcore-wotlk#4019]
Buenas hay un problema la cual es dificil de entra caminando defrente para poder ingresa a la instancia de la icc en light king

foto 1 la forma de que no se puede ingresar
![1](https://user-images.githubusercontent.com/53723504/102722099-d8068680-42cc-11eb-9f21-5ae9d1b4c470.jpg)
fot 2 : en esta forma se puede ingresar
![tiene que ](https://user-images.githubusercontent.com/53723504/102722108-e48adf00-42cc-11eb-8671-6b6f900a6af4.jpg)

video explicando

https://user-images.githubusercontent.com/53723504/102722112-ebb1ed00-42cc-11eb-80ca-2b93d8d901c9.mp4
OPERATING SYSTEM
linux-debian10
modulos instalados
mod-1v1-arena
mod-anticheat
mod-boss-announcer
mod-cfbg
mod-duel-reset
mod-instance-reset
mod-learn-spells
mod-npc-services
mod-top-arena
mod-transmog
mod-enchanter
mod-npc_freeprofesion

**Comment by Yehonal** [comment]
Only english here and please, follow the istructions to open a proper issue
