### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#402]
download you dbc maps mmaps and vmaps from here https://mega.nz/#F!FMYzASKA!M-RY7OgXUR0nhWpnPKwusg and when run worldserver i got 
Map file '/opt/server/test/dataf/maps/0004331.map' is from an incompatible clientversion. Please recreate using the mapextractor.
where i can fine extractors for win64/86 or build files...

**Comment by Inifield** [comment]
extract them

**Comment by starrheld** [comment]
@Viste 
http://www.azerothcore.co.uk/downloads/maps.zip
http://www.azerothcore.co.uk/downloads/dcb.zip
http://www.azerothcore.co.uk/downloads/vmaps.zip
http://www.azerothcore.co.uk/downloads/mmaps.zip

**Comment by Viste** [comment]
thx
