### ISSUE TITLE
Brewfest Banner outside Exodar on 21st of Dec

### ISSUE THREAD

**Issue by Okuluss** [azerothcore/azerothcore-wotlk#4025]
Noticed brewfest banner at entrace of Exodar during feast of winter veil (21st of Dec)

##### CURRENT BEHAVIOUR:
2 x brewfest banner at entrance of Exodar during feast of winter veil. Obviously dont belong there during that time of the year.
see pic below:
![WoWScrnShot_121920_151216](https://user-images.githubusercontent.com/76229969/102823640-90baeb80-43db-11eb-86ad-03a00650ca45.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Remove brewfest banners during feast of winter veil.

##### STEPS TO REPRODUCE THE PROBLEM:
Go to entrance of Exodar.

##### AC HASH/COMMIT:
AzerothCore rev. f1be5f940540+

##### OPERATING SYSTEM:
Docker installation.

##### MODULES:
SoloLFG, 1v1Arena, AhBot, AutoBalance

**Comment by Kitzunu** [comment]
Feel free to test https://github.com/azerothcore/azerothcore-wotlk/pull/4026
