### ISSUE TITLE
Bug Spell Charge IceHowl

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#403]
**Description**: Icehowl charge bug

**Current behaviour**: when he charge on a target and in path stop and  he's go into Enrage!!!

**Expected behaviour**: He's must enrage when hit on player when charged! 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) master

**AC hash/commit**:  latest AC

**Operating system**:  se7en 64 bit

**Modules**:  Are you using modules? no

**Comment by franklampardahar** [comment]
it get bug only same times !

**Comment by gengarshadowball** [comment]
This is not a bug:
https://wow.gamepedia.com/Icehowl
"If Massive Crash doesn't hit anyone, then Icehowl crashes on Coliseum's wall, and gets a debuff that stuns him for 15 secs, increasing damage taken by 100%. If it does hit someone, a hunter should use  [Tranquilizing Shot] immediately to remove the rage effect."

**Comment by BarbzYHOOL** [comment]
Bogir also confirmed it's not a bug
