### ISSUE TITLE
[AreaTrigger] ICC Entrance not working always

### ISSUE THREAD

**Issue by morpheux** [azerothcore/azerothcore-wotlk#4048]
##### CURRENT BEHAVIOUR:
Sometimes we are unable to enter ICC and it is necessary to try more often or to enter from the side. (no error just portal not working)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
ICC Portal should always put you in or warn about quest or other difficulty kills missing.

##### STEPS TO REPRODUCE THE PROBLEM:
1 - Go to Icecrown Citadel Entrance
2 - Try to enter

##### EXTRA NOTES:
Reverted this change 
https://github.com/azerothcore/azerothcore-wotlk/pull/3780/commits/7beaadf08037299b4b5788d8939dbdd14d4b9b19
Entrance works again.

##### AC HASH/COMMIT:
[96c7d42](https://github.com/azerothcore/azerothcore-wotlk/commit/96c7d423806c3fd8c7390bbcd373ece62f438ac1)

##### OPERATING SYSTEM:
Ubuntu 20.04

##### MODULES:
CFBG
Transmog

##### OTHER CUSTOMIZATIONS:
N/A

**Comment by r0m1ntik** [comment]
Confirm [96c7d42](https://github.com/azerothcore/azerothcore-wotlk/commit/96c7d423806c3fd8c7390bbcd373ece62f438ac1)

**Comment by Kitzunu** [comment]
@Meltie2013 might have a clue? =)

**Comment by Kitzunu** [comment]
@morpheux @r0m1ntik Could you please try this fix
```diff
diff --git a/src/server/game/Entities/Object/Object.cpp b/src/server/game/Entities/Object/Object.cpp
index 2a4ca7de40..d417a8278f 100644
--- a/src/server/game/Entities/Object/Object.cpp
+++ b/src/server/game/Entities/Object/Object.cpp
@@ -1335,7 +1335,7 @@ bool Position::IsWithinBox(const Position& center, float xradius, float yradius,
     // is-in-cube check and we have to calculate only one point instead of 4
 
     // 2PI = 360*, keep in mind that ingame orientation is counter-clockwise
-    double rotation = 2 * M_PI - GetOrientation();
+    double rotation = 2 * M_PI - center.GetOrientation();
     double sinVal = std::sin(rotation);
     double cosVal = std::cos(rotation);
 
@@ -1347,14 +1347,13 @@ bool Position::IsWithinBox(const Position& center, float xradius, float yradius,
 
     // box edges are parallel to coordiante axis, so we can treat every dimension independently :D
     float dz = GetPositionZ() - center.GetPositionZ();
-    float dx = rotX - GetPositionX();
-    float dy = rotY - GetPositionY();
+    float dx = rotX - center.GetPositionX();
+    float dy = rotY - center.GetPositionY();
     if ((std::fabs(dx) > xradius) ||
         (std::fabs(dy) > yradius) ||
         (std::fabs(dz) > zradius))
-    {
         return false;
-    }
+
     return true;
 }
 ```
 From Meltie https://github.com/Meltie2013/azerothcore-wotlk/commit/550fede1671613a844545f8810b986a31892fe5d
 If it works I can PR it when I have time

**Comment by r0m1ntik** [comment]
@Kitzunu it's work ! ThankU

**Comment by Helias** [comment]
@Kitzunu if you create the PR for me, you can put as To Be Merged if the build pass

**Comment by Kitzunu** [comment]
@Helias okok =)
