### ISSUE TITLE
Smokywood supplies has an outdated year in description

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4051]
Accepting the quest https://www.wowhead.com/quest=8861/new-year-celebrations will give the item https://www.wowhead.com/item=21545/smokywood-supplies witch is supposed to be used before the next year.
The box actually says "Use before 2010", should be "Use before 2021" and this need to be updated every year.

![imagen](https://user-images.githubusercontent.com/4155059/103144187-1e604900-4704-11eb-876e-44af3d4ada72.png)

**Comment by Kitzunu** [comment]
As a personal opinion I dont want to change this

**Comment by Si1ker** [comment]
@Kitzunu reason? If you want to block blizzlike behavior, there should be a good reason, right? 🐱

**Comment by Kitzunu** [comment]
Pure nostalga for a cosmetic thing.
Also DBC data

**Comment by Si1ker** [comment]
I just did some investigation, this won't be changed:

On wowhead "Live" (meaning Shadowlands) it will display 2012: https://www.wowhead.com/item=21545/smokywood-supplies
![image](https://user-images.githubusercontent.com/61223313/103144387-36c56900-46ee-11eb-8dad-c66e0b88467b.png)


On wowhead "Classic" it will display 2010: https://classic.wowhead.com/item=21545/smokywood-supplies
![image](https://user-images.githubusercontent.com/61223313/103144390-42b12b00-46ee-11eb-8288-f2db9bd3f07a.png)


Other sources:
https://db.rising-gods.de/?item=21545/smokywood-supplies
https://wotlkdb.com/?item=21545
http://wotlk.cavernoftime.com/item=21545
![image](https://user-images.githubusercontent.com/61223313/103144394-49d83900-46ee-11eb-88cd-1286ca76cd55.png)

So the year was updated after woltk expansion, which means it won't happen here, the 2010 will stay, also there is no proof that it should be updated every year.

Is like watching your calendar and you say:    " hey.. it cannot be 2020 if I'm playing a woltk expansion  D ;  "
Time stuff. 🐱
