### ISSUE TITLE
[Wintergrasp] Object visibility distance

### ISSUE THREAD

**Issue by Wowhungarian** [azerothcore/azerothcore-wotlk#4057]
##### CURRENT BEHAVIOUR:
The problem is that, the destroyable game objects like Towers and Walls have low visibility distance at WG. Therefore [Wintergrasp Cannons](https://wowgaming.altervista.org/aowow/?npc=28366), which have greater visibility distance, than  the WG Towers, loads and falls down to the ground. Because of that, the Cannons on the Towers are usually unusable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Cannons stays at their position.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go away from WG Tower Cannons until, they disappeare.
2. Approach the Towers.
3. Check Cannons.

##### AC HASH/COMMIT:
d3aff86c32334ad86d93aa37f09221c162049cf7

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
mod-anticheat

##### OTHER CUSTOMIZATIONS:
nope

##### SCREENSHOT:
![cannon](https://user-images.githubusercontent.com/36567380/103166841-624b6f00-4826-11eb-98d0-66fd49979693.jpg)

It can also fall under the tower texture.

![cannon2](https://user-images.githubusercontent.com/36567380/103172999-187b7c80-4858-11eb-9d52-0bb53e077ff7.jpg)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/2779833768bbe9967006d6d16888dace05b4bcb6
