### ISSUE TITLE
(DB/CORE) Fel Reaver

### ISSUE THREAD

**Issue by imxari** [azerothcore/azerothcore-wotlk#4059]
##### CURRENT BEHAVIOUR:

The Fel Reaver roaming around Helfire in Outlands glitches through the floor and cuts across the map to return to it's original spawn point/waypoint.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC is meant to circle Helfire and eventually make it back to it's waypoint without cutting across the map.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Helfire and watch the Fel Reaver.

Screenshots:
- https://linx.xarihosted.org/i01t7l8f.jpg
- https://linx.xarihosted.org/ak53dmj7.jpg

##### AC HASH/COMMIT:

d3aff86

##### OPERATING SYSTEM:

Ubuntu 20.04 with Docker.

##### MODULES:

mod-ah-bot
mod-autobalance
mod-individual-xp
mod-transmog

##### OTHER CUSTOMIZATIONS:

- Legion High Resolution Models for creatures and items.
- Custom Heirloom Items.

**Comment by LukasVolgger** [comment]
You are using a modified client. Please retry with an clean WotLK client.

**Comment by imxari** [comment]
> You are using a modified client. Please retry with an clean WotLK client.

Tried without a modded client, issue is still present. I think it's a waypoints issue as he reaches Honor Hold and cuts across the middle of the map.

**Comment by heyitsbench** [comment]
This has likely been fixed with 17d56cb18c1e6b51fd90ebd7ffacf49ca4885420.
