### ISSUE TITLE
DB/Quest: Soaket Pages

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4060]
##### SMALL DESCRIPTION:
When you loot the quest item for this quest, it disappears and the other party members cannot loot it until respawn. 

https://www.wowhead.com/quest=9062/soaked-pages

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Typically when doing quests that require to loot only 1 item, all the party members all allowed to loot it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a group of 2 or more members
2. Take the "Soaket Pages" quest with each party member 
3. Collect the item from under the water

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/672057316a51

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Yehonal** [comment]
Probably we should use 2 seconds instead of 0 that can also cause some concurrency issue in core

Check this related issue: https://github.com/TrinityCore/TrinityCore/issues/20162

You could also get fixes for other similar objects

**Comment by FrancescoBorzi** [comment]
> Probably we should use 2 seconds instead of 0 that can also cause some concurrency issue in core
> 
> Check this related issue: [TrinityCore/TrinityCore#20162](https://github.com/TrinityCore/TrinityCore/issues/20162)
> 
> You could also get fixes for other similar objects

are you sure about this? because if that is true, then we have a problem:

![image](https://user-images.githubusercontent.com/75517/103156972-c29eca00-47ae-11eb-8f9e-60967e58d65a.png)

**Comment by Yehonal** [comment]
Not all objects are interactive. That's why they might not have respawntime
probably.
Anyway, it's very unlikely that you have a problem with 0 sec respawntime,
but should be safer to set 1 or 2 secs. Just test the result in game.

Il sab 26 dic 2020, 19:16 Francesco Borzì <notifications@github.com> ha
scritto:
