### ISSUE TITLE
Low population of Ghostclaw Lynx 

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4065]
Original report from @NicoAravena

I was doing the quest https://www.wowhead.com/quest=9158/bearers-of-the-plague and searching for Ghostclaw lynx was hard, because of the low population of them.
![imagen](https://user-images.githubusercontent.com/4155059/103162483-eaeaf080-47cf-11eb-84ce-394df44a7249.png)
On the image, the left blue area, was empty of any kind of mobs and near of the Farstrider Enclave, there was 5 or 6 of them, so you need to wait a moment for the respawn.

Fun fact, I thought that I was disconnected of the server because of the lac of mobs 😆 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/672057316a51

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by wizzymore** [comment]
I saw this on discord some days ago,

Based on the new wowhead, there are 125 spawn:
![image](https://user-images.githubusercontent.com/25827787/103175907-60a99780-4876-11eb-9bff-a258bbab5286.png)

Based on our current database, there are only 19 spawns, 2 are on the left side, 17 on the right side.

> Fun fact, I thought that I was disconnected of the server because of the lac of mobs 😆
I feel you about this, on the left zone, i only encountered 3 mobs, the 2 Lynx spawns and one Mistbat, i don't know if the zone should feel this empty and i will look into this a bit more, but, there are so few spawns in this big zone that after a passed those npcs it took me 5 minutes to find another npc, which was the same Mistbat that moved around a bit, so the area is really really empty.
