### ISSUE TITLE
(DB/Quest) Taken by the Scourge

### ISSUE THREAD

**Issue by imxari** [azerothcore/azerothcore-wotlk#4077]
##### CURRENT BEHAVIOUR:

- When you free a Warsong Peon they take too long to despawn. And they don't say anything.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- In retail when you free a Warsong Peon they say one of many different lines and then despawn a few seconds later.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Warsong Hold in Borean Tundra.
2. Obtain the quest "Taken by the Scourge" (.quest add 11611)
3. Kill Nerub'ar Victim's (id: 25284)

##### EXTRA NOTES:

- Quest ID: 11611
- Nerub'ar Victim ID: 25284
- Warsong Peon ID: 25270

##### AC HASH/COMMIT:

e7dc6df

##### OPERATING SYSTEM:

Ubuntu 20.04 with Docker

##### MODULES:

mod-transmog
mod-autobalance
mod-ah-bot
mod-individual-xp

##### OTHER CUSTOMIZATIONS:

- Custom Heirlooms
- High Res Models from Legion

**Comment by Kitzunu** [comment]
Gonna open a PR

**Comment by Kitzunu** [comment]
Please test it =) https://github.com/azerothcore/azerothcore-wotlk/pull/4079

**Comment by imxari** [comment]
> Please test it =) #4079

Tested, works perfectly. Amazing work :D
