### ISSUE TITLE
[Quest] Galaen's fate missing text on quest accept

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4078]
##### SMALL DESCRIPTION:

Missing npc texts after taking quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

On accept:

The ghost of Galaen appears.
_Galaen says: Morae... Is that you?
Galaen says: No... you're not Morae, but I sense that you have met. When you see her, tell her that I survived the crash, only to be done in by the infiltrators.
Galaen says: Let her know... my last thought was of her..._
The spirit fades away.

##### CURRENT BEHAVIOUR:

No texts appear when accepting quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. go c id 17426
2. q a 9578
3. q c 9578
4. take next quest from npc 

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/c3b32302987c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:
ChromieCraft

**Comment by wizzymore** [comment]
Confirm, i will create a PR soon for this

**Comment by wizzymore** [comment]
I don’t think Waiting to be tested label in needed
