### ISSUE TITLE
Rin'ji is normally a male and is not attackable by alliance players and can't get out of his cage

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#408]
**Description**: Rin'ji is normally a male and is not attackable by alliance players and can't get out of his cage

**Current behaviour**: Alliance players can attack Rin'Ji and if he is attacked, he escapes from the cage while the cage is still locked and is attacked by other mobs around him and dies.
Also he's using a female model (or he is randomly cycling through his male and female modelid).

**Expected behaviour**: He must stay in his cage and must be unattackable/invincible while staying in his cage but becomes attackable when out of the cage. http://wowwiki.wikia.com/wiki/Rin'ji

**Steps to reproduce the problem**:

1. make an alliance character
2. .tele queldanil
3. find rin'ji

**Comment by falzard** [comment]
Maybe alliance players can attack rin'ji but not when he's in the cage.

**Comment by ShinDarth** [comment]
@talamortis  please do not close the issue until the fix is actually in master branch

**Comment by HeartWell** [comment]
Omg this quest only horde.

**Comment by falzard** [comment]
I don't think you understood.

**Comment by talamortis** [comment]
@falzard me or @HeartWell ?

**Comment by falzard** [comment]
Heartwell
