### ISSUE TITLE
Feature: SmartAI makes player to do an action on a specific target

### ISSUE THREAD

**Issue by wizzymore** [azerothcore/azerothcore-wotlk#4084]
**Describe your feature request or suggestion in detail**

Add a specific option in SAI to as an example make a player cast a spell on a specific target.
This could help us move scrips from c++ to SAI and create more specific scripts that use spells.

**Describe a possible solution to your Feature or Suggestion in detail**

A good example is this script here which cannot be move to SAI because of this missing feature:

https://github.com/azerothcore/azerothcore-wotlk/pull/4079

The spell that summons the guardians needs to be casted by the player so he owns the guardian, but, the target of the spell should be the cocoom ( Victim ) as they need to spawn as if they we’re inside the cocoon, so we have a spell that the player needs to cast on the creature that has the smart script.

If this is achievable already but i just don’t know how to do this, let me know and i can close this issue.

**Comment by Kitzunu** [comment]
I dont know, but if you cast the spell on a target, is it yours or the targets npc's then?


Thinking of SMART_ACTION_CAST and SMART_TARGET_ACTION_INVOKER

**Comment by wizzymore** [comment]
The casting is still done by the creature or GOB.

**Comment by Kitzunu** [comment]
then there's probably not a way to force player cast through sai, since the sai is assigned to a creature or gob

**Comment by wizzymore** [comment]
This is possible to be done, as an example, this is how AreaTrigger is done:
![image](https://user-images.githubusercontent.com/25827787/103246625-da23b180-496c-11eb-8b31-7c101573546b.png)
The caster becomes a summoned unit and then casts the spell on the target, the problem is not if this can be done, is if people want to see this thing.

**Comment by wizzymore** [comment]
Actually, after looking a bit in the script, i think this is what i was looking for:
SMART_ACTION_CROSS_CAST 
I will test this and close the issue if i am right

**Comment by Kitzunu** [comment]
Nice

**Comment by Kitzunu** [comment]
Yea should in theory work with SMART_TARGET_ACTION_INVOKER

**Comment by wizzymore** [comment]
Yep, this works:
![image](https://user-images.githubusercontent.com/25827787/103247591-0db40b00-4970-11eb-8652-90ea5ad895c9.png)

The set-up in DB.
![image](https://user-images.githubusercontent.com/25827787/103247598-14428280-4970-11eb-97d0-e060cf7f6adb.png)

I will close this issue, also, i recommend switching that c++ script to SAI, i will send you the script if you are interesed

**Comment by Kitzunu** [comment]
Better change it in another PR imho since it is already tested and approved
