### ISSUE TITLE
[Quest] Show-Gnomercy missing text and scripts

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4086]
##### CURRENT BEHAVIOUR:

Engineer "Spark" Overgrind spawns and attack the player with no texts and then walks weirdly.

There are multiple but little issue with this quest.

- [ ] Missing text when you use the option when talking with him.

Engineer "Spark" Overgrind laughs.
Engineer "Spark" Overgrind says: Does it frighten you to know that there are those would serve the Legion with such devotion as to remain unwavering citizens of your pointless civilizations until called upon?
Engineer "Spark" Overgrind says: Live in fear, die by the will of Kael'thas... It's all the same.
Engineer "Spark" Overgrind says: And now, I cut you!
Engineer "Spark" Overgrind says: DIE!

- [ ] Weird behavior

After attacking in melee-mode the player for 5 times the npc starts slowly walking to range-mode to throw dynamites and keep doing so, he should be able to throw dynamites from melee to. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
[For text reference]
https://www.wowhead.com/quest=9537/show-gnomercy#videos:id=90511
https://wow.gamepedia.com/Show_Gnomercy

[For combat abilities - throwing dynamites]
https://youtu.be/Jr2Ne2yaAZM

##### STEPS TO REPRODUCE THE PROBLEM:

1. go c id 17240
2. q a 9537 
3. talk with the gnome and watch

**Comment by Kitzunu** [comment]
> After attacking in melee-mode the player for 5 times the npc starts slowly walking to range-mode to throw dynamites and keep doing so, he should be able to throw dynamites from melee to.

I believe this is a generic issue for the core

**Comment by wizzymore** [comment]
Can confirm both, working on a PR

**Comment by wizzymore** [comment]
Also, while wondering on the bitch there is no script going on.

"Wandering around the beach

While Engineer "Spark" Overgrind wanders around the beach, collecting seashells, he says 1 out of 6 random quotes, followed by 1 out of 3 random emotes, when he finds a shell:

    Engineer "Spark" Overgrind says: A-ha! Found one!
    Engineer "Spark" Overgrind says: Another one!
    Engineer "Spark" Overgrind says: Oh that's a big one!
    Engineer "Spark" Overgrind says: It's ironic, I hate the ocean but I love the beach.
    Engineer "Spark" Overgrind says: I wonder if you can really hear the ocean in these things.
    Engineer "Spark" Overgrind says: Yes Master, all goes along as planned.

    Engineer "Spark" Overgrind places the shell in his pack.
    Engineer "Spark" Overgrind examines the shell.
    Engineer "Spark" Overgrind holds the shell up to his ear."
