### ISSUE TITLE
[Quest] What We Know display bug

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4087]
##### CURRENT BEHAVIOUR:
Quest is marked as a group-quest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Quest should be a normal one.
https://wotlk.evowow.com/?quest=9753

##### STEPS TO REPRODUCE THE PROBLEM:

1. q a 9753

**Comment by Kitzunu** [comment]
No.
https://wowwiki.fandom.com/wiki/Quest:What_We_Know...?oldid=1485483 Rev from 2008
> Type
Group

**Comment by Hacaw** [comment]
@Kitzunu it's just a speak to a npc quest which is near the quest giver.  
I don't think it was intended by Blizzard and that's why it was fixed, but nevertheless, thanks for checking out.

**Comment by Kitzunu** [comment]
Yea I am closing it since it is blizzlike, so we should keep it like that

**Comment by wizzymore** [comment]
All of this chain except the last questions are meant for group, also from wowhead comments i think the chain should be draenei only as well, will need to look into this more
