### ISSUE TITLE
NPCs in revantusk village keep moaning and yelling while playing drums

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#409]
**Description**: 3 troll NPCs in revantusk village keep moaning and yelling while playing drums

**Current behaviour**: Some trolls in the second floor of the Revantusk village play the drums but they also play the sound of attacking.

**Expected behaviour**: I doubt they should moan permanently because it's very annoying, we should only hear the drum sounds.

**Steps to reproduce the problem**:

1. .tele revantusk
2. listen
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
this is something to do with the emote system, as they attack they (moan) this is what its like on most cores.

**Comment by falzard** [comment]
You could just label it to "very low priority" instead of closing it :P

**Comment by talamortis** [comment]
there is no emote for "attacking" without sound

http://rpheaven.org/forum/index.php?/topic/2029-repostthe-emote-id-list/

**Comment by falzard** [comment]
On retail there wasn't this bug.
