### ISSUE TITLE
[NPC] Demolitionist Legoso has a weird behavior 

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4092]
##### CURRENT BEHAVIOUR:
Demolitionist Legoso spam cast Lightning Shield when he detects aggros.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Not sure about this one, I searched WoWPedia, WoWHead, WoWWiki but couldn't find what should he actually do, since some guards are attacking mobs outside of city should he also attack creatures that are approaching ?

##### STEPS TO REPRODUCE THE PROBLEM:
1. go c id 17986
2. aggro an Enraged Ravager 
3. bring it to the Demolitionist
4. the more you walk the more he casts lightning shields

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
First encountered on ChromieCraft Server + Client

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Kitzunu** [comment]
smart_scripts
---
```sql
SELECT * FROM smart_scripts WHERE entryorguid = 17982
```
| entryorguid | source_type | id | link | event_type | event_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | action_type | action_param1 | action_param2 | action_param3 | action_param4 | action_param5 | action_param6 | target_type | target_param1 | target_param2 | target_param3 | target_param4 | target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 17982 | 0 | 4 | 0 | 0 | 0 | 100 | 0 | 0 | 0 | 15000 | 15000 | 0 | 11 | 325 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | IC Update - Cast Spell Lightning Shield |

**Comment by Kitzunu** [comment]
I wonder if he even should, in TC script he doesn't use the spell

**Comment by wizzymore** [comment]
Seems like he casts some kind of Frost Shock everytime he enters combat ( only when he aggros from OOC, not by switching targets IC ).
https://www.youtube.com/watch?v=lARzK9CLu24
Other than that i couldn't find anything else.

**Comment by Hacaw** [comment]
@wizzymore I haven't done any quests related to him. 
I just aggroed a monster and bring it near him and he seems he want to attack the creature, but is pinned in the place and perma casts lightning orbs.

**Comment by FrancescoBorzi** [comment]
I think the problem might be that he tries to aggro the creature but fails, and there is no initial delay for `IC Update - Cast Spell Lightning Shield`:

![image](https://user-images.githubusercontent.com/75517/103590644-ae657600-4eee-11eb-9b45-9337e052b680.png)

giving an initial delay of half a second seems to solve the issue for me:

![image](https://user-images.githubusercontent.com/75517/103590714-da80f700-4eee-11eb-8291-db2923506ebc.png)

@Hacaw please test this: https://github.com/azerothcore/azerothcore-wotlk/pull/4211
