### ISSUE TITLE
[Spell] Polymorph on creatures is overpowered [$15]

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4093]
##### CURRENT BEHAVIOUR:
The creature waits 3-4 seconds after the effect is finished.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The creature should attack you right away after the effect is finished.

##### STEPS TO REPRODUCE THE PROBLEM:
1. create mage character
2. learn all my spells
2. go c id 17348 (melee creature) / go c id 17606 (range creature)
3. get a bit of distance and cast Polymorph Rank 1
4. wait 20 sec for the spell to finish 
5. after the effect is gone you'll notice the creature will wait 3-4 seconds before it attacks you 

##### AC HASH/COMMIT: 
e7dc6df31e0eff050103eb5ded28c419a2e748fc

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
First encountered on ChromieCraft Server + Client

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by r0m1ntik** [comment]
confirm [d513d80
](https://github.com/azerothcore/azerothcore-wotlk/commit/d513d8064a31cdde183ebabfcab171e369b30a23)

**Comment by FrancescoBorzi** [comment]
does it happen with all creatures or only some specific ones?

**Comment by r0m1ntik** [comment]
> does it happen with all creatures or only some specific ones?

All creatures, I tested in game

**Comment by Hacaw** [comment]
All creatures that can be polymorphed.

**Comment by lineagedr** [comment]
More like they don't start chasing you untill you start moving.

Poly creature and don't move
.damage 1 on creature
watch how it just stays there untill you move.

**Comment by lineagedr** [comment]
This issue is fixed after https://github.com/azerothcore/azerothcore-wotlk/pull/4220

**Comment by FrancescoBorzi** [comment]
@Hacaw can you please double-check this one on latest master?

**Comment by Hacaw** [comment]
@FrancescoBorzi TL;DR **It works.**

##### SCENARIOS:
- [x] Polymorph a melee creature, after the effect is gone the creature instantly comes chasing you.
- [x] Tested @lineagedr scenario with + without moving, after the effect is gone the creature instantly comes chasing you.

##### AC HASH/COMMIT: 
adcf3f7a

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None
