### ISSUE TITLE
[Quest][Client] The Sun Gate missing animation

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4094]
##### CURRENT BEHAVIOUR:
1. The laser beams are missing
![image](https://user-images.githubusercontent.com/6963500/103276330-e80a1e80-49ce-11eb-943b-620806b169cc.png)

2. After taking the quest 9740 https://www.wowhead.com/quest=9740/the-sun-gate#videos:id=33955 and disable Sunhawk Portal Controller it should disable the animation of the associated laser beam.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
 [2016 video](https://youtu.be/hgKvI2_juGg)
 [2008 video](https://youtu.be/ZMO56xG2yYo?t=189)

##### STEPS TO REPRODUCE THE PROBLEM:
1. go c id 17887
2. watch the laser beams are missing
3. q a 9740

##### AC HASH/COMMIT: 
e7dc6df31e0eff050103eb5ded28c419a2e748fc

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
First encountered on ChromieCraft Server + Client
Tested with Warmane Client + Chromie Client.

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by r0m1ntik** [comment]
confirm

**Comment by r0m1ntik** [comment]
[TrinityCore/sql/old/3.3.5a/world/64_2019_03_19/2019_01_22_04_world.sql](https://github.com/DeltaIN/TrinityCore/blob/0567b3245a04f3957f20db7791cbb7fcd77bfabd/sql/old/3.3.5a/world/64_2019_03_19/2019_01_22_04_world.sql) 
![Снимок экрана 2020-12-29 в 18 51 03](https://user-images.githubusercontent.com/40755539/103305828-7355d500-4a0c-11eb-9dc0-1060d5b18438.png)
