### ISSUE TITLE
NPC AI: Minions dont enter flight

### ISSUE THREAD

**Issue by Okuluss** [azerothcore/azerothcore-wotlk#4098]
I noticed that some NPC minions dont enter combat like Succubus minion from IIkrud Magthrull (GUID 32439).  Please also see pic below. Might be the only one as e.g his summuned minions at 50% hp immediatly support him. If you start to fight succubus while Magthrull is still alive, it uses melee attack and lash of pain.

CURRENT BEHAVIOUR:
Minion dont enter fight.

STEPS TO REPRODUCE THE PROBLEM:
Go to coordinates provided in screenshot below and fight Magthrull in Ashenvale (GUID 32439). Minion (GUID  3120722) wont enter fight.

![Capture_1](https://user-images.githubusercontent.com/76229969/103310576-3abbf880-4a18-11eb-8c9c-4bcd03c9b5fb.JPG)

AC HASH/COMMIT:
AzerothCore rev. f1be5f9+

OPERATING SYSTEM:
Docker Installation

MODULES:
SoloLFG, 1v1Arena, AhBot, AutoBalance

OTHER CUSTOMIZATIONS:
Graphics: HD Creatures/Characters

**Comment by r0m1ntik** [comment]
@Okuluss this demon don't attack ?
![Снимок экрана 2020-12-30 в 16 31 27](https://user-images.githubusercontent.com/40755539/103363891-8f18b400-4abc-11eb-8647-6706c0eef52e.png)

**Comment by Okuluss** [comment]
Hi r0m1ntik! The succubus doesnt attack. Shes already around before the fight (on the right hand side in my pic). The summoned viodwalkers during fight work as intended.
