### ISSUE TITLE
[Quest] Gyromasts Revenge

### ISSUE THREAD

**Issue by Okuluss** [azerothcore/azerothcore-wotlk#4099]
Wrong gossip for quest. Threshwackonator doesnt attack player when approaching Gelkak Gyromast to turn in quest.
Quest ID: 2078

##### CURRENT BEHAVIOUR:
As described above.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Please also see video below:
https://classic.wowhead.com/quest=2078/gyromasts-revenge#videos:id=170980
with gossip:
![image](https://user-images.githubusercontent.com/76229969/103312463-6ab9ca80-4a1d-11eb-9c7a-f9adea8d7b66.png)

##### STEPS TO REPRODUCE THE PROBLEM:
Go to northernmost coast of Darkshore. Corrdinates as in pic below. Accept quest "Gyromasts Revenge" (ID 2078). You need the key inside your bags (ID 7442). Escort Threshwackonator north back to Gelkak.
![image](https://user-images.githubusercontent.com/76229969/103312408-3940ff00-4a1d-11eb-9db5-baf34a8304b5.png)

##### EXTRA NOTES:
Trinitycore was converting CPP to SAI and corrected gossip. Please see link below:
https://github.com/TrinityCore/TrinityCore/issues/24034

##### AC HASH/COMMIT:
AzerothCore rev. f1be5f9+

##### OPERATING SYSTEM:
Docker Installation

MODULES:
SoloLFG, 1v1Arena, AhBot, AutoBalance

OTHER CUSTOMIZATIONS:
Graphics: HD Creatures/Characters

**Comment by Kitzunu** [comment]
I dont really understand. Do you mean that he is not starting to attack if you press the gossip?

**Comment by Okuluss** [comment]
No, sorry. Threshwackonator just gets hostile when you apporach Gelkak but doesnt attack player. Before is friendly as it should be.

**Comment by Kitzunu** [comment]
ah

**Comment by wizzymore** [comment]
Hi, i will create a PR for this soon.

Thanks for the report 😄
