### ISSUE TITLE
[VANILLA][ITEM] Corrupted Ashbringer

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#410]
**Description**: Corrupted ashbringer doesn't turn you friendly to scarlet crusade or enemy to argent dawn

**Expected behaviour**: The opposite. Spells involved are 28282 and/or 28414

**Steps to reproduce the problem**:

1. create a level 60 warrior
2. .add 22691
3. equip it and go to scarlet monastery

**Comment by falzard** [comment]
I heard voices from the ashbringer without adding that thing.

**Comment by starrheld** [comment]
Pushed https://github.com/azerothcore/azerothcore-wotlk/commit/e7582c9ac7de9da6919c2e1607322251a62d7d99
