### ISSUE TITLE
[Quest] Urgent Delivery! + Botanist Taerix

### ISSUE THREAD

**Issue by wizzymore** [azerothcore/azerothcore-wotlk#4101]
##### CURRENT BEHAVIOUR:

"Urgent Delivery!" currently has the Prev Required quest to be "Botanist Taerix" but it should be this:
https://wowwiki.fandom.com/wiki/Quest:Urgent_Delivery!#Quest_progression
![image](https://user-images.githubusercontent.com/25827787/103321634-4bce2f00-4a43-11eb-8d70-a3e25c92f388.png)

![image](https://user-images.githubusercontent.com/25827787/103321767-df076480-4a43-11eb-9006-1eb7cfe9f2b0.png)

Also,  "Botanist Taerix" has no Prev Required quest, but it should be "Urgent Delivery!"

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After "You Survived!" (first Draenei quest) you should receive "Replenishing the Healing Crystals"
After "Replenishing the Healing Crystals" you should receive "Urgent Delivery!"
"Urgent Delivery!" should unlock two quests:
1. "Rescue the Survivors!"
2. Botanist Taerix

Also it can be seen here:
https://www.youtube.com/watch?v=Hjy_9buBkbM
No quest appears on the map as available, currently "Urgent Delivery!" appears on AC as specified above.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Dranei
2. Take the first quests and see which are available

##### EXTRA NOTES:

Help me confirm this is correct and if so i can come with a PR to solve the issue, thanks.

**Comment by Kitzunu** [comment]
But shouldnt they be accessed all at the same time? Due to the [1]

**Comment by wizzymore** [comment]
That is the level of the quest

**Comment by Kitzunu** [comment]
Makes very much sense

**Comment by Kitzunu** [comment]
however, isnt that quest supposed to be able to be done by all races? That means it would clash if we changed it, no?

**Comment by Kitzunu** [comment]
I might be wrong, it is too late to use the brain

**Comment by Kitzunu** [comment]
anyhow https://github.com/TrinityCore/TrinityCore/issues/16391 is where it was added

**Comment by wizzymore** [comment]
@Kitzunu actually the rest of the classes have the correct order:
9369 ( Replenishing the Healing Crystals for the other classes, not for Draenei ) continues with Urgent Delivery! as it should.
![image](https://user-images.githubusercontent.com/25827787/103322814-753d8980-4a48-11eb-8284-bf4043ff225d.png)

**Comment by wizzymore** [comment]
Please add this to 1-19 for correct project tracking.
