### ISSUE TITLE
quest 9575 &9572 wrong location

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4102]
1. quest a 9575 or 9572
2. Look at the location of the quest
As shown in the figure, it is shown in the position of 3. In fact, it should be in the position of 1

![20201230082036](https://user-images.githubusercontent.com/18187177/103322153-024c0700-4a78-11eb-8408-07059a809d49.jpg)

AzerothCore revision : 96c7d42+ 2020-12-24 02:48:51 +0000 (master branch)
OS:ubuntu 18.04

**Comment by r0m1ntik** [comment]
Idk if existe in DBC WorldMapAreaId for Hellfire Peninsula, but MapID in DB is wrong,
```sql
UPDATE `quest_poi` SET `MapID` = 543, `WorldMapAreaId` = 0 WHERE `QuestID` IN (9572, 9575) AND `id` IN (0, 1, 2);
```

**Comment by wizzymore** [comment]
> Idk if existe in DBC WorldMapAreaId for Hellfire Peninsula, but MapID in DB is wrong,
> 
> ```sql
> UPDATE `quest_poi` SET `MapID` = 543, `WorldMapAreaId` = 0 WHERE `QuestID` IN (9572, 9575) AND `id` IN (0, 1, 2);
> ```

@r0m1ntik Does this fix the issue completely?

**Comment by r0m1ntik** [comment]
@wizzymore the coordinates of the points are correct, but there the problem in the ID of the map was simple, it does not show where to be in the game, since the quest is performed in the insta and this insta is not in WorldMapAreaId.dbc

**Comment by mpfans** [comment]
tested... There is no location for quests now
![20201231152330](https://user-images.githubusercontent.com/18187177/103399472-40caea00-4b7c-11eb-860b-ca85810336b9.png)

Because it is an instance quest, the location will not appear on the map

**Comment by mpfans** [comment]
Confirm that it has been fixed
