### ISSUE TITLE
error buff

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4103]
1..go -4620.14209 -1243.340332 -53.041912 1
2.View buffs

![20201230082917](https://user-images.githubusercontent.com/18187177/103322511-1fcda080-4a79-11eb-81ba-bb92a256e84e.jpg)

AzerothCore revision : 96c7d42+ 2020-12-24 02:48:51 +0000 (master branch)
OS:ubuntu 18.04

**Comment by mpfans** [comment]
The second bug
change worldserver.conf
Wintergrasp.Enable = 1 to Wintergrasp.Enable = 0
A party to a Alliance or Horde , still get 'Essence of Wintergrasp' buff

**Comment by FrancescoBorzi** [comment]
@mpfans please open a separate error for each bug

**Comment by mpfans** [comment]
> @mpfans please open a separate error for each bug

ok

**Comment by r0m1ntik** [comment]
```sql
DELETE FROM `spell_area` WHERE `area` = 480 AND `spell` = 57940;
```

**Comment by FrancescoBorzi** [comment]
@r0m1ntik can you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it?

**Comment by mpfans** [comment]
![20201231163603](https://user-images.githubusercontent.com/18187177/103402035-4c231300-4b86-11eb-9146-19dca5516565.jpg)

tested.
Confirmed it's fixed

**Comment by lineagedr** [comment]
```sql
DELETE FROM `spell_area` WHERE `spell` = '57940' AND `area` IN (65, 66, 67, 206, 210, 394, 395, 480);
```

These are the non northrend areas linked to that spell. Looking now there are some dungeon area ids with that spell.
