### ISSUE TITLE
GetAverageItemLevel 2 functions for 1 usage? Remove one function?

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#4104]
##### CURRENT BEHAVIOUR:

I wrote this a few months ago (and I don't remember the details) and posted in discord, I post it here and if you guys don't agree or explain to me why these two functions are needed, then just close it::

Why twice a similar function? Shouldn't we only use one? here is my (attempt) analysis of the code:
```cpp
float Player::GetAverageItemLevel()
{
    float sum = 0;
    uint32 count = 0;
    uint8 level = getLevel();

    for (uint8 i = EQUIPMENT_SLOT_START; i < EQUIPMENT_SLOT_END; ++i)
    {
        // don't check tabard, ranged, offhand or shirt
        if (i == EQUIPMENT_SLOT_TABARD || i == EQUIPMENT_SLOT_RANGED || i == EQUIPMENT_SLOT_OFFHAND || i == EQUIPMENT_SLOT_BODY)
            continue;

        if (m_items[i] && m_items[i]->GetTemplate())
            sum += m_items[i]->GetTemplate()->GetItemLevelIncludingQuality(level);

        ++count;
    }

    return std::max<float>(0.0f, sum/(float)count);
}

float Player::GetAverageItemLevelForDF()
{
    float sum = 0;
    uint32 count = 0;
    uint8 level = getLevel();

    for (int i = EQUIPMENT_SLOT_START; i < EQUIPMENT_SLOT_END; ++i)
    {
        // don't check tabard, ranged, offhand or shirt
        if (i == EQUIPMENT_SLOT_TABARD || i == EQUIPMENT_SLOT_RANGED || i == EQUIPMENT_SLOT_OFFHAND || i == EQUIPMENT_SLOT_BODY)
            continue;

        if (m_items[i] && m_items[i]->GetTemplate())
        {
            if (m_items[i]->GetTemplate()->Quality == ITEM_QUALITY_HEIRLOOM)
                sum += level*2.33f;
            else
                sum += m_items[i]->GetTemplate()->ItemLevel;
        }

        ++count;
    }

    return std::max(0.0f, sum / (float)count);
}
```
GetItemLevelIncludingQuality() already does that part `sum += level*2.33f;`. So the only diff is that for DungeonFinder, it does not take into account the quality of the item.

GetAverageItemLevel() seems to be used in the raid browser

```cpp

    float GetItemLevelIncludingQuality(uint8 pLevel) const
    {
        auto itemLevel = (float)ItemLevel;
        switch (Quality)
        {
            case ITEM_QUALITY_POOR:
            case ITEM_QUALITY_NORMAL:
            case ITEM_QUALITY_UNCOMMON:
                itemLevel -= 26.0f;
                break;
            case ITEM_QUALITY_RARE:
                itemLevel -= 13.0f;
                break;
            case ITEM_QUALITY_HEIRLOOM:
                itemLevel = pLevel*2.33f;
                break;
            case ITEM_QUALITY_ARTIFACT:
            case ITEM_QUALITY_EPIC:
            case ITEM_QUALITY_LEGENDARY:
            default:
                break;
        }
        return std::max<float>(0.f, itemLevel);
    }
```

ilvl 200 blue is in fact absolute ilvl of 187. I don't know where this is from but it kinda makes sense to have reduced ilvl depending on the quality.
That's why I think this function should be used for the DungeonFinder too and that `GetAverageItemLevelForDF()` be totally removed for `GetAverageItemLevel()`

Otherwise, we could reverse the calc from here https://wowwiki.fandom.com/wiki/Item_level to calculate the absolute stats of an item:

Uncommon: ilvl = ItemSlotValue * 2.0 + 8.00
Rare:           ilvl = ItemSlotValue * 1.8 + 0.75
Epic:            ilvl = ItemSlotValue * 1.2 + 26

Rare: 

ilvl = ItemSlotValue * 1.8 + 0.75
200 = ItemSlotValue * 1.8 + 0.75
200 - 0.75 = ItemSlotValue * 1.8
ItemSlotValue = 199.25 / 1.8 = 110,694444444
ItemSlotValue = (ilvl - 0.75) / 1.8

Epic: ItemSlotValue = 200 / 1.2 + 26 = 78
ItemSlotValue = (ilvl - 26) / 1.2 = 145

With this we can see that the highest epic items from TBC are almost equivalent to same ilvl blue items in terms of stats. However, at ilvl 200, there seems to be a huge gap between blue and epic (and there is no blue above 200)

**Comment by wizzymore** [comment]
Hi Barbz, this is because one is used for dungeon finder where heirlooms are given bonuses for easier queues, while to the other situations ( like Raid Browser ) you don't want this kind of behaviour.

**Comment by BarbzYHOOL** [comment]
> where heirlooms are given bonuses for easier queues

What do you mean? it's to allow heirloom wearing players to pass the ilvl check?

**Comment by Kitzunu** [comment]
@T1ti do you know?

**Comment by UltraNix** [comment]
Both are calculated differently, so both should stay.
