### ISSUE TITLE
Feature: Calculate ilevel from owned equipment in bag/bank

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#4105]
**Describe your feature request or suggestion in detail**

On this page is written "Officially, average item level is calculated from the best item you own for that slot, not what you have equipped" which would be very practical for players and an improvement with 0 drawback.
Some players equip lower ilvl items on specific occasions, if it instead checked what is inside the bag + bank, it would save time to the players and maybe avoid useless GM tickets :D

https://www.mmo-champion.com/threads/803352-Macro-to-quot-accurately-quot-calculate-average-item-level

**Describe a possible solution to your Feature or Suggestion in detail**

Could also make this configurable.

**Additional context**

There are 2 functions to get avg ilvl, i'm not really sure why, cf https://github.com/azerothcore/azerothcore-wotlk/issues/4104

**Comment by wizzymore** [comment]
Hi,

iLvL even if it is present, is not used in gear comparations.
Gearscore should be used as a default system by everyone, something that was created by the community for the community.

**Comment by BarbzYHOOL** [comment]
it is used for the LFG so it would be better this way, but it's trivial
