### ISSUE TITLE
Weird interaction with maps in Ghostlands

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4106]
##### SMALL DESCRIPTION:
In Amani camps near Zul'Aman, some pet Lynx have a weird behaviour whe moving near houses (watch the video https://youtu.be/v9gHYshNNrM).

##### EXPECTED BLIZZLIKE BEHAVIOUR:
No dancing lynx

##### CURRENT BEHAVIOUR:
Pet lynx start moving weird near house entrance from amani's camps.

##### STEPS TO REPRODUCE THE PROBLEM:
 
1. Go to Ghostlands
2. Go Amani camps near Zul'Aman searching for a dancing lynx near the entrance of any house

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/c3b32302987c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Never report several unrelated bugs in one issue.

**Comment by nicoaravena** [comment]
@Kitzunu Just updated the issue, will create new ones for others.

**Comment by Kitzunu** [comment]
Also add rev

**Comment by nicoaravena** [comment]
Updatated again  @Kitzunu

**Comment by nicoaravena** [comment]
@Kitzunu can you add the label 1-19 to this please, it still happening even after #4274

**Comment by Kitzunu** [comment]
done

**Comment by Helias** [comment]
I don't think it's a proper "issue".
This is related to the "random movements radius", the problem is that sometimes the NPC can be a bit stuck in some object, but I don't think on retail it is so different.
We should see in retail what happens to understand if this is a real bug or not

**Comment by nicoaravena** [comment]
I will try to find other problems, but I think it is related to the houses in that map.

**Comment by ChromieCraftServer** [comment]
is this still valid?
