### ISSUE TITLE
Escape from the Catacombs weird npc behaviour

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4108]
In my trip arround Ghostlands on ChromieCraft leveling my char and found little weird things.

I found weird is doing the rescue mission in the Amani Catacombs (https://www.wowhead.com/quest=9212/escape-from-the-catacombs), when killing the mobs in the ambush, Ranger Lilatha stay in combat and follow the path attacking first mob in sight, in this case were 2 bats, she went to them running faster than usual.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Do not run with hyper speed to closest monster

##### CURRENT BEHAVIOUR:
After an amani troll ambush, Ranger Lilatha runs fast and attackas first monster she encounters.

##### STEPS TO REPRODUCE THE PROBLEM:
 
1. Go to Amani Catacombs in Ghostlands
2. Search for Ranger Lilatha in a rounded room and start the quest.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/c3b32302987c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@nicoaravena thanks for the report. A little tip: you can just copy paste [this](https://raw.githubusercontent.com/chromiecraft/chromiecraft/main/issue_template.md) template when reporting issues that you find on ChromieCraft.

**Comment by nicoaravena** [comment]
@FrancescoBorzi just uptade the issue to match with given template.

**Comment by FrancescoBorzi** [comment]
@nicoaravena yeah it's ok, I mean for the future so it's easier for you ;)
