### ISSUE TITLE
[CORE] Glyph(s) learnage

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#411]
**Description**: Glyph Learn is Bug

**Current behaviour**: When You use a Glyph from first spec and learn Dual spec you can not use that glyph each used in first spec you must remove first spec glyph.

**Expected behaviour**: you must learn a glyph in 2 spec . first spec & dual spec too

**Steps to reproduce the problem**:

1. use a glyph
2. learn dual spec
3. use that glyph each used from first spec in second spec . you can't

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) Master

**AC hash/commit**:  latest AC

**Operating system**:  Se7en 64bit

**Modules**:  Are you using modules? yes . anticheat - transmog

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by lif3st3al3r** [comment]
Confirm

**Comment by Franklampardst** [comment]
@kvipka @ShinDarth  not have any idea?

**Comment by ShinDarth** [comment]
unfortunately Idk, never investigated on this issue

**Comment by pklloveyou** [comment]
Confirm

**Comment by pklloveyou** [comment]
Quit a game into the game can learn Glyph

**Comment by pklloveyou** [comment]
@Yehonal 
Is it a mechanism that should be added?
Save all glyphs and reload glyph status while switching second genres

**Comment by lineagedr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/dd300003e27ea6b5e8060d9f2adb8bf4cd7e913d/src/server/game/Entities/Player/Player.cpp#L26639
```C++
for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)
        if (uint32 glyphId = m_Glyphs[GetActiveSpec()][slot])
            if (GlyphPropertiesEntry const* glyphEntry = sGlyphPropertiesStore.LookupEntry(glyphId))
                CastSpell(this, glyphEntry->SpellId, TriggerCastFlags(TRIGGERED_FULL_MASK&~(TRIGGERED_IGNORE_SHAPESHIFT|TRIGGERED_IGNORE_CASTER_AURASTATE)));
```

Repalce with:

```C++
for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)
{
	uint32 glyphId = m_Glyphs[GetActiveSpec()][slot];

	if (glyphId)
		if (GlyphPropertiesEntry const* glyphEntry = sGlyphPropertiesStore.LookupEntry(glyphId))
			CastSpell(this, glyphEntry->SpellId, TriggerCastFlags(TRIGGERED_FULL_MASK&~(TRIGGERED_IGNORE_SHAPESHIFT | TRIGGERED_IGNORE_CASTER_AURASTATE)));

		SetGlyph(slot, glyphId, true);
}
```

Can someone test?

**Comment by Deku** [comment]
Is this still an issue?

**Comment by BarbzYHOOL** [comment]
@FALL1N1 didn't you talk about this issue previously?

**Comment by BarbzYHOOL** [comment]
> add a check if it's a glyph 

this is the solution (the error is quite useful to some degree with instant servers)

**Comment by fragcamp** [comment]
tested with @FALL1N1 fix and it's still the same however @lineagedr fix seems to resolve the issue

**Comment by BarbzYHOOL** [comment]
ok nice, @fragcamp 

Would you like to try to open a pull request? It only requires to follow a tutorial https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request
