### ISSUE TITLE
(DB/Creature): Mottled Worg location in tree

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#4116]
##### CURRENT BEHAVIOUR:

Mottled Worg is located inside a tree
![image](https://user-images.githubusercontent.com/4015312/103387883-0a796600-4abb-11eb-9518-1f9b84a1ec28.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mottled Worg should not be in the tree

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 17952 
2. walk forward (it will look like your not in the tree)
3. turn around and see the Mottled Worg in the tree

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/c3b32302987c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### SERVER:

ChromieCraft

##### CONFIRMED ON:
also confirmed this on my local server running on:
https://github.com/azerothcore/azerothcore-wotlk/commit/aec0dbb747791683338c8d45aad5936ab165b2d8

**Comment by Helias** [comment]
this was a easy one https://github.com/azerothcore/azerothcore-wotlk/pull/4117
