### ISSUE TITLE
Shadowglen Webwood Spiders Population

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4127]
Shadowglen Webwood Spiders Population

##### CURRENT BEHAVIOUR:

Currently there are 5-6 spiders grouped closely in the entrance, and the spiders are paired in twos all over the cave. It feels like there's 2x too many spawns in this interior.

Go ingame and compare the current level of spiders (over 50 in the cave, 5 in the entrance, moslty in pairs) to this video from 2008 of them mostly alone and maybe 2-3 in the entrance.

https://www.youtube.com/watch?v=W4wCYxRsxEU

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mostly alone and maybe 2-3 in the entrance.

https://www.youtube.com/watch?v=W4wCYxRsxEU

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to shadowglen
2. Go to webwood cave north of map
3. Look at spiders

##### EXTRA NOTES:

EXTRA NOTE:

Every other starting zone only has yellows. The night elves are the only ones to have reds. Despite this being weird I think it's correct behaviour.

wowhead comments from 3.0.2 talk about them being hostile

https://wotlk.evowow.com/?npc=1986

https://www.wowhead.com/npc=1986

##### AC HASH/COMMIT:

2020-12-31
6414b40518da (chromiecraft)

##### OPERATING SYSTEM:

Whatever Chromiecraft is on.

##### MODULES:

Whatever Chromiecraft is on.

##### OTHER CUSTOMIZATIONS:

Whatever Chromiecraft is on.

**Comment by r0m1ntik** [comment]
SELECT COUNT(1) FROM `creature` WHERE `id` = 1986;
TrinityCore DB: 45
AzerothCore DB: 62
