### ISSUE TITLE
IceHowl & Anub Loot

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#413]
**Description**: icehowl and anub loot 

**Current behaviour**: icehowl and anub in toc 10nm & hc almost not give loot 

**Expected behaviour**: Must give loot after killed boss
**Steps to reproduce the problem**:

1. need party members.
2. change group loot
3. kill Boss IceHowl

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) master

**AC hash/commit**:  latest AC

**Operating system**:  se7en 64bit

**Modules**:  Are you using modules?no
**Other Customizations**: Are you using any core/db patches or other customizations? NO!

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by starrheld** [comment]
What do you mean? Just a few pieces or nothing at all?
- " almost not give loot"

**Comment by Franklampardst** [comment]
@starrheld only give eot on my server not giving items a lot time.
