### ISSUE TITLE
[Portal] Instance portal not working 

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4132]
#CURRENT BEHAVIOUR:
While testing my fixes for Gruul i entered and left Gruuls lair quite a few times. Each and every time i wanted to left the dungeon, walking straight through the middle of the portal did not work. Entering the lair has never been a problem.
[Portal fail](https://streamable.com/bpsqrj)
[Portal success](https://streamable.com/cg6rlh)

EXPECTED BLIZZLIKE BEHAVIOUR:
Players should be able to leave the raid no matter at what angle the player walks.

STEPS TO REPRODUCE THE PROBLEM:
Form a raidgroup
.tele Gruulslair
Enter the dungeon and try to walk back out through the portal.

EXTRA NOTES:
c208a12 with OS: Ubuntu Server 20.04 from June 3rd does NOT have this problem

AC HASH/COMMIT:
https://github.com/55Honey/azerothcore-wotlk/commit/1ed80e95969ce672cdb8bd6d17de58cfb0785f6d

OPERATING SYSTEM:
Windows 10 64-bit

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by r0m1ntik** [comment]
fixed [#4050](https://github.com/azerothcore/azerothcore-wotlk/commit/d3aff86c32334ad86d93aa37f09221c162049cf7)

**Comment by 55Honey** [comment]
Im going to update my server and test it again then.

**Comment by Helias** [comment]
@55Honey if the bug persists reopen or comment this issue
