### ISSUE TITLE
Laris Geardawdle (9616) missing text

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4133]
Laris Geardawdle (9616) missing text

##### CURRENT BEHAVIOUR:

His first text works but if you ask him the his dialogue options it says "Greetings %N."

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should have more text on his dialogues. I don't know what the text is but not Greetings X.

https://classic.wowhead.com/npc=9616/laris-geardawdle

https://wow.gamepedia.com/Laris_Geardawdle

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to NPC in Ironfroge Explorer's league.
2. Talk to him.
3. Observe "greetings X".

##### AC HASH/COMMIT:

ChromieCraft 02-01-2020
6414b40 (chromiecraft)

##### OPERATING SYSTEM:

ChromieCraft

##### MODULES:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@JamesGent thanks for the report, please add the [1-19] label too when reporting bugs about this part of content :)
