### ISSUE TITLE
Siltfin Murloc Population too high on Siltfin Shore (Azuremyst)

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#4136]
Siltfin Murloc Population too high on Siltfin Shore (Azuremyst)

##### CURRENT BEHAVIOUR:

There are almost 100 Siltfins on the small beach which made doing the lvl 8 quest extremely hard for a group of two (Priest/Shaman) players. I couldn't imagine doing it alone as every pull pulls 2-5 murlocs.

https://www.wowhead.com/quest=9562/murlocs-why-here-why-now

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Half the murlocs give or take.

https://www.youtube.com/watch?v=VCCVWUaPl2I

Video is from 2015 and people have been clearing the area but the difference is extreme.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to siltfin shore.
2. Observe the amount of murlocs
3. Cry

##### AC HASH/COMMIT:

ChromieCraft
2020-12-31
6414b40 (chromiecraft)

##### OPERATING SYSTEM:

ChromieCraft

##### MODULES:

ChromieCraft

##### OTHER CUSTOMIZATIONS:

ChromieCraft

**Comment by r0m1ntik** [comment]
confirm
![Снимок экрана 2021-01-02 в 19 04 34](https://user-images.githubusercontent.com/40755539/103463542-66e3bc00-4d2d-11eb-8e8a-86a6e57cecb5.png)

**Comment by r0m1ntik** [comment]
```sql
SELECT COUNT(1) FROM `creature` WHERE `id` IN(17190, 17191, 17192);
```
TrinityCore: 90
Azerothcore: 99

**Comment by JamesGent** [comment]
Lmao that I guess there's 100 murlocs and there's 99 Siltfins and 1 Murgurgula equalling exactly 100 murlocs.

**Comment by r0m1ntik** [comment]
I do not know how much should be in fact, maybe someone has more information, or implement 9 less as in TrinityCore ? @JamesGent

**Comment by FrancescoBorzi** [comment]
@JamesGent would you be able to identify which ones needs to be removed? you can `.npc info` on them to get the GUID of the ones that need to go

**Comment by vtihomirov** [comment]
Here a TBC Classic recording of the Murlocs in this area: https://youtu.be/ClODO5uPMAE

**Comment by claudiodfc** [comment]
The difference between classic and azerothcore is the lack of pooling on our side. 100 possible spawns isn't that much for such a contested area. The problem is the amount of the spawned ones not using dynamic spawn.
