### ISSUE TITLE
Core/Creature: hardcoded text in boss_skadi

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4153]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp#L85

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by avarishd** [comment]
@Kitzunu

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/ac8a6b432805593eeb33ccacab94838808d7f50c
