### ISSUE TITLE
Core/Creature: hardcoded text in boss_hodir

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4157]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp#L133-L140

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by buddiman** [comment]
This is already fixed on https://github.com/azerothcore/azerothcore-wotlk/commit/a43ccdd7c676ca5bb3c888c47de5c2b4783aa907
