### ISSUE TITLE
Core/Creature: hardcoded text in boss_general_vezax

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4158]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp#L89-L95

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by buddiman** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp#L285-L291

There is also this emote which should be used by the saronite vapor when the creature spawns instead of general Vezax.
