### ISSUE TITLE
Core/Creature: hardcoded gossips in oculus

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4160]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp#L60-L66

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by wizzymore** [comment]
This was removed in this:
https://github.com/azerothcore/azerothcore-wotlk/pull/3531

**Comment by Kitzunu** [comment]
Nice
