### ISSUE TITLE
Core/Creature: hardcoded text in zone_sholazar_basin

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4165]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L268-L279
https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L549-L550
https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L611-L613
https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L1045-L1047

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/3255e1cdf7b2d2ff4b69dfcf4a5f5f256c0112a3/src/server/scripts/Northrend/zone_sholazar_basin.cpp#L831
```
constexpr auto SAY_OFFER = "Care to try Grimbooze Thunderbrew's new jungle punch?";
```

**Comment by ZhengPeiRu21** [comment]
Resolved in https://github.com/azerothcore/azerothcore-wotlk/pull/11829.
