### ISSUE TITLE
[QUEST][WOTLK] Jormuttar is Soo Fat...

### ISSUE THREAD

**Issue by sucofog** [azerothcore/azerothcore-wotlk#417]
**Description**:  The quest Jormuttar is Soo Fat... is bugged, you can't use the skinning knive on the dead bears.

**Current behaviour**: You should be able to skin dead bears  with item http://www.wowhead.com/item=42732/everfrost-razor

**Expected behaviour**: You should be able to skin dead bears.

FACT: With .gm on you can see dead bears and you can use knive to skin them, but they are invisible to players (phasemasked)

![image](https://cloud.githubusercontent.com/assets/734950/23662165/f3af8ccc-034e-11e7-9752-1cf080b2c6c4.png)

**Steps to reproduce the problem**:

1. .quest add 13011
2. .go xyz 7202.350098 -2113.439941 768.617981
3. Kill a bear and try to skin it

**Branch(es)**: master

**Operating system**:  Ubuntu 16.04

**Modules**:  Mod-anticheat | Mod-transmog | Mod-duelreset

**Other Customizations**: None.

**Comment by starrheld** [comment]
Can you try with:

.aura 55012
.aura 72914

Seen a few videos where this aura is applied in the Cave.

**Comment by sucofog** [comment]
Okay gonna test

**Comment by sucofog** [comment]
That are the costumes, both auras applied do not fix the bug :/

**Comment by sucofog** [comment]
Phases are bugged with this chain

**Comment by spinzaku** [comment]
i have encountered this issue now with a player.
.GM can see the dead bears and slimes
but player could not. so its a phasing bug.
