### ISSUE TITLE
Core/Creature: hardcoded gossip in zone_feralas

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4181]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Kalimdor/zone_feralas.cpp#L26
Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by buddiman** [comment]
This was remove in https://github.com/azerothcore/azerothcore-wotlk/commit/07861d0548111aa7d5ca9bb826370b4db40f0d62
