### ISSUE TITLE
Core/Creature: hardcoded gossip in zone_darkshore

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4184]
##### CURRENT BEHAVIOUR:

https://github.com/azerothcore/azerothcore-wotlk/blob/79aa5606547d898542557a01a2150f76e477e9e9/src/server/scripts/Kalimdor/zone_darkshore.cpp#L431

Need to convert to DB so locales can make use of it

AC HASH/COMMIT: 79aa560
OPERATING SYSTEM: w10

**Comment by buddiman** [comment]
This was already resolved in 42244612ff2409c59ac9e3505fb81aad5fc8c052
