### ISSUE TITLE
[Suggestion] Use TrinityCore auth database structure

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#419]
**Description**: There are useful rows in the TC auth database, for several years already.
It could be updated to look like this (with the corresponding core modifs of course):
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/sql/base/auth_database.sql

I don't know if it's the best idea but it doesn't seem to hurt to use this structure instead, tell me if I'm wrong. I put it there so developers looking for something to do can stumble upon this idea.

**Comment by Nefertumm** [comment]
There is a TODO list that is related with the DB structure. #236
