### ISSUE TITLE
[Raid][BattleForMountHyjal]Instance Reset After Retreat From Thrall  

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#4193]
##### CURRENT BEHAVIOUR:
After Killed Bosses Except Archimonde In Anytime，And click Retreat talk with Thrall,
Just leave this instance for a while(relative with unload instance map interval) , or just restart the worldserver;
enter the instance from any entry, then all instance npc was reset as beginning of new instance;
and
I moniter that The Instance record's Data Field will be reset to null after click the retreat from Thrall.
It Should Be "3 3 3 3 0 1 1 700000"
That's why the raid is reset as new instance , just  after leave the map for a while (unload the instance map) ,and back again(reload data from database).

I can not find the reason why the data was reset to null but not "3 3 3 3 0 1 1 700000"

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC Should Reset After Every Week Maintaince

##### STEPS TO REPRODUCE THE PROBLEM:

1. update acore_characters.instance with mapid 534, Set Field "data" with "3 3 3 3 0 1 0 700000"  to simulate boss 4 killed
2. .go 5449 -2723 1485 534
3. talk with thrall and click retreat
4. review the record just upated, the data field with show you NULL but not "3 3 3 3 0 1 1 700000" it should be.
5. leave instance for a while or restart worldserver, force worldserver reload data from database
6. enter instance , All NPC are ready for battle ! again!

##### AC HASH/COMMIT:

01c830ed4691

##### OPERATING SYSTEM:

Ubuntu 20 (Docker build)

**Comment by betayi** [comment]
i make a lot of try to find this regulation，and i confirmed it only repear at this condition. 
it's ugly for a raid group battle times a day for those euippments , like a normal dungen instance can reset as much as will!

**Comment by betayi** [comment]
leave the instance for a while is 30 minutes as default arg defined in conf (Instance.Unloadmap)

**Comment by betayi** [comment]
@Kitzunu @Yehonal  I’m sorry for Get your mention, but it's really a critical problem needs to be fixed

**Comment by Kitzunu** [comment]
I suck at remembering things, but if I manage to remember this tomorrow I will look at it. Currently 1.30AM

**Comment by betayi** [comment]
> I suck at remembering things, but if I manage to remember this tomorrow I will look at it. Currently 1.30AM

i wanna help you guys, but i am chicken at coding, i will collect datas as much as i can, good job, for the azeroth!
