### ISSUE TITLE
Quest: Missing Event on "Fallen Sky Lake"

### ISSUE THREAD

**Issue by Okuluss** [azerothcore/azerothcore-wotlk#4197]
After turning in quest "fallen sky lake" in Astranaar, an event should start according to:
https://www.youtube.com/watch?v=eL2s52LexhI

##### CURRENT BEHAVIOUR:
No event after turning in quest.

##### STEPS TO REPRODUCE THE PROBLEM:
accept quest "fallen sky lake" (ID 1035) in Astranaar
turn in and no event starts

##### EXTRA NOTES:
Solution found for TrinityCore:
https://github.com/TrinityCore/TrinityCore/issues/20344

##### AC HASH/COMMIT:
AzerothCore rev. f1be5f9+

##### OPERATING SYSTEM:
Docker Installation

##### MODULES:
SoloLFG, 1v1Arena, AhBot, AutoBalance

##### OTHER CUSTOMIZATIONS:
Graphics: HD Creatures/Characters

**Comment by Si1ker** [comment]
SQL passed but fix from TC did not work for me.
