### ISSUE TITLE
DB/creature: Death Knight Understudy can disappear on "Dismiss" action

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#4198]
NPC = [Death Knight Understudy](https://www.wowhead.com/npc=16803/death-knight-understudy)
Location: Naxxramas (Map 533) at Military Quarter

##### CURRENT BEHAVIOUR:
If you use right-click a controlled Death Knight Understudy and click on "Dismiss", the NPC disappears.  o.o !

![image](https://user-images.githubusercontent.com/61223313/103497582-9cf56e80-4e07-11eb-9331-882f0f3d6d3d.png)

![image](https://user-images.githubusercontent.com/61223313/103497663-d29a5780-4e07-11eb-8a86-c43f8d41d7bc.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC should not disappear after you click on "dismiss", it is not a summoned pet, sometimes you will get the bug and sometimes not, the chance to get the bug is 50/50.

https://www.youtube.com/watch?v=8elL14VTND8

![image](https://user-images.githubusercontent.com/61223313/103497795-34f35800-4e08-11eb-9551-f300b9e5ed63.png)

![image](https://user-images.githubusercontent.com/61223313/103497842-5fddac00-4e08-11eb-86ee-e0a9cba68cc9.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Adjust raid difficulty to 10man
2. .go xyz 2812.673 -3089.319 272.425 533 3.300
3. Use an [Obedience Crystal](https://www.wowhead.com/npc=29912/obedience-crystal) to control a Death Knight Understudy
4. Right-click on the controlled Death Knight Understudy picture and click on "Dismiss" as shown above then....
If it remains => try again
If it disappears => You have reproduced the bug 

##### EXTRA NOTES:

N/A

##### AC HASH/COMMIT:

79aa560

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

HD textures
Legion models

**Comment by Gultask** [comment]
https://github.com/chromiecraft/chromiecraft/issues/6968
https://github.com/chromiecraft/chromiecraft/issues/6932

Likely caused because they're TempSummons

**Comment by heyitsbench** [comment]
They're being despawned by [this PetHandler line](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Handlers/PetHandler.cpp#L291). Maybe needs a check to see if pet owner matches charm unit?

**Comment by heyitsbench** [comment]
Could also be that they're supposed to use the ([unimplemented](https://github.com/azerothcore/azerothcore-wotlk/issues/12641)) `Cannot Dismiss Pet` summon property flag.

**Comment by Nyeriah** [comment]
> Could also be that they're supposed to use the ([unimplemented](https://github.com/azerothcore/azerothcore-wotlk/issues/12641)) `Cannot Dismiss Pet` summon property flag.

They are not summons though, they're mind controlled npcs

**Comment by heyitsbench** [comment]
> They are not summons though, they're mind controlled npcs

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Naxxramas/boss_razuvious.cpp#L77-L82
I'm just spitballing here.

**Comment by sogladev** [comment]
Allowing to "unsummon" charmed NPCs  `pet->ToTempSummon()->UnSummon()` when not the owner feels wrong.

Comparing to TC 335 https://github.com/TrinityCore/TrinityCore/blob/14501c0d7af9ae06e3febcb7567407191249d821/src/server/game/Handlers/PetHandler.cpp#L238  only stopping the charm is present here

Desummoning pets that are owned are handled here https://github.com/azerothcore/azerothcore-wotlk/blob/8e9e134924efc5da5f50d3dd197f613cabadaa33/src/server/game/Handlers/PetHandler.cpp#L308 

Not sure for what special case there's a clause in AC to allow it when player is not the owner https://github.com/azerothcore/azerothcore-wotlk/blob/8e9e134924efc5da5f50d3dd197f613cabadaa33/src/server/game/Handlers/PetHandler.cpp#L290
