### ISSUE TITLE
Quest: 

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#42]
This quest: http://it.wowhead.com/quest=8519/a-pawn-on-the-eternal-board

It works perfectly but after all the animations the game doesn't complete the quest.

**Comment by DantestyleXD** [comment]
Completed without errors.
There is an invisible trigger at the center of action that will complete your quest.

----------------------------
Server: Local (Repo AzerothCore)
Last commit hash tested: 0ba91d7c3ee994607a6e0437ab47c2c79ba1ab0a
O.S.: Windows 10
Compiler: MS Visual Studio 2013
