### ISSUE TITLE
Updated: 2017_03_04_20.sql, Part of the quest can not accept.

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#420]
@fr4z3n @ShinDarth @Draztal @Viste 

**Added_1:** After testing, found that when the NPC also provides two (or more than two) quest, it will trigger the "Bug".
**Added_2:** I guess, perhaps because: in reading the second quest, read the locales_quest in the title? (My locales_quest database does not exist in Chinese).
**Added_3:** In more tasks shown here, can the code be written as: If locales_quest is empty, then call quest_template, I guess...help me.
**Added_4_over:** I added Chinese for locales_quest, still this error.

Yesterday update progress: 2017_03_04_20.
After the update, found some Npc and some quest can not accept accept.
I do not know if it is because https://github.com/azerothcore/azerothcore-wotlk/commit/4a6350dc83d58806195eafd3f8559c7494765299 this update.
I opened a free server, but I was not able to deal with the problem, hoping to get your help!
I will upload the "Bug" picture and my database description.

![1](https://cloud.githubusercontent.com/assets/21149808/23686643/b3fc0a82-03e5-11e7-952f-8bb9069883f5.png)

**Comment by Viste** [comment]
@DarkmoonRabbit give me plz npc id where have 2 quests i chek on my realm

**Comment by DarkmoonRabbit** [comment]
@Viste Thousand Needles - Shimmering Flats

**Comment by Viste** [comment]
oh ok i try to find >_<

**Comment by DarkmoonRabbit** [comment]
@Viste You too? this error.

**Comment by Viste** [comment]
@DarkmoonRabbit i don't know need find that npc and look you don't post npc ENTRY only location and name and it make all harder

**Comment by DarkmoonRabbit** [comment]
@Viste autodrome.
![20170308171602](https://cloud.githubusercontent.com/assets/21149808/23697535/17dedf60-0423-11e7-8f9d-b6d2c16771ac.png)

**Comment by Viste** [comment]
![wowscrnshot_030817_122425](https://cloud.githubusercontent.com/assets/281977/23697798
when i put on npc i have quest text so it tell 1 quest 
/369b5114-03fa-11e7-9398-be8a8c178192.jpg)
![wowscrnshot_030817_122422](https://cloud.githubusercontent.com/assets/281977/23697799/36a1474a-03fa-11e7-89a4-320c9a844ef5.jpg)
but with him i have that shit 
![wowscrnshot_030817_122612](https://cloud.githubusercontent.com/assets/281977/23697875/82e42366-03fa-11e7-85af-652451eb8142.jpg)

**Comment by DarkmoonRabbit** [comment]
@Viste At first, I think it is a database error! Now, it should be C ++ code ...

**Comment by Viste** [comment]
maeby i miss some i look when have free time

**Comment by DarkmoonRabbit** [comment]
@Viste Thank you very much, look forward to your fix.

**Comment by DarkmoonRabbit** [comment]
@Viste Very strange, some NPC can show multiple Quest, which is a separate problem?

**Comment by Viste** [comment]
@DarkmoonRabbit try PR #426

**Comment by DarkmoonRabbit** [comment]
@Viste How to download PR? the first time...

**Comment by ShinDarth** [comment]
@DarkmoonRabbit https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request
