### ISSUE TITLE
[NPC] Walkpoints underneath the map

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4203]
##### CURRENT BEHAVIOUR:
Image from ChromieCraft:
![image](https://user-images.githubusercontent.com/6963500/103545359-1e054200-4eaa-11eb-8553-e64cd2b07c98.png)

On my local server it didn't walk like that, maybe he has multiple paths defined in the db. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
[NPC](https://www.wowhead.com/npc=10880/warcaller-gorlach) should walk above the street.

##### STEPS TO REPRODUCE THE PROBLEM:
1. go to the Drag
2. follow this [NPC](https://www.wowhead.com/npc=10880/warcaller-gorlach)

##### AC HASH/COMMIT: 
e7dc6df3

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
First encountered on ChromieCraft Server + Client

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by nicoaravena** [comment]
Maybe this is related with the one I created #4205. Didn't saw this one before.

**Comment by Hacaw** [comment]
@nicoaravena thanks for pointing that out, I don't think there are the same root-causes. In your issue the npc looks like it's flying, in my issue it seems he is walking through the ground without changing his rotation on z axis.

**Comment by FrancescoBorzi** [comment]
@Yehonal

**Comment by Yehonal** [comment]
Should be fixed in:  https://github.com/azerothcore/azerothcore-wotlk/pull/4220

**Comment by FrancescoBorzi** [comment]
@hacaw  please help testing the PR linked by Yehonal

**Comment by Hacaw** [comment]
@FrancescoBorzi TL;DR It works.
@Yehonal good job, the path walking looks perfect with no z-axis clipping.

##### SCENARIOS:
Just walked with the npc an entire Oggrimar tour.

##### AC HASH/COMMIT: 
adcf3f7a

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None
