### ISSUE TITLE
[NPC] Multiple NPCs that walks arround a map start to fly for a while

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4205]
##### SMALL DESCRIPTION:
Some NPCs with specific paths, starts to fly at some point.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPC should not fly at any moment.

##### HOW TO TEST

One way is follow one of the following NPCs from far, without pulling them in Ghostlands:
- Luzran
- Knucklerot

Other way is doing [Unexpected Results](https://www.wowhead.com/quest=8488/unexpected-results) in Eversong Woods] and wait for enemies to start the attack.

##### Related images
![image](https://user-images.githubusercontent.com/4155059/103554102-29964000-4e8d-11eb-9c94-d9317b975ac7.png)

This was given by Gizmoh on Discord
![image](https://user-images.githubusercontent.com/4155059/103554148-374bc580-4e8d-11eb-8fd0-b3bf42b9f007.png)

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/79aa5606547d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Found that some weird moves from some mobs, like floating while going up or down in a path (also noticed doing https://www.wowhead.com/quest=8488/unexpected-results). And the weirdest thing was dancing Lynx (watch the video https://youtu.be/v9gHYshNNrM), this happens at server level, because we saw it with a friend and no once, but three times in different mobs.

**Comment by Yehonal** [comment]
Could you please add an "how to test"? 

You can link some NPCs to check or more info to help us testing it

**Comment by nicoaravena** [comment]
@Yehonal Added 2 ways to find this problem, one just following some elites, other with quest NPCs.

**Comment by Yehonal** [comment]
Fixed in  https://github.com/azerothcore/azerothcore-wotlk/pull/4220

**Comment by FrancescoBorzi** [comment]
@nicoaravena  please help testing the PR linked by Yehonal

**Comment by nicoaravena** [comment]
Sure, I have considered already, as soon as I have some time I will do it.

**Comment by malcrom** [comment]
I repathed Luzran and Knucklerot. After following them I find no issue.
