### ISSUE TITLE
[Weapon][Val'anyr] It is not activating with periodic healings (HOTS)

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#4207]
##### CURRENT BEHAVIOUR:
[Val'anyr, Hammer of Ancient Kings](https://wowwiki.fandom.com/wiki/Val%27anyr,_Hammer_of_Ancient_Kings) does not proc with healing hots, only with direct spell heals.

[Proof 1 - Youtube](https://www.youtube.com/watch?v=-PZdIObmtVc&ab): With healing casts, the effect works. After waiting the CD (Inactivity), hots does not activate it.

[Proof 2  - Youtube](https://www.youtube.com/watch?v=eXdYmo_HXas): Any of the HOTS apply the debuff. At minute 1:00 start to cast Nourish, who activate it. After the effect dissapear, and wait the 45 CD seconds, any HOT apply the debuff.

More proofs and description about how it should work in the weapon link.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The effect reads “Your healing spells have a chance to cause Blessing of Ancient Kings for 15 seconds allowing your heals to shield the target absorbing damage equal to 15% of the amount healed.”

The way this works is that when the proc happens (**which is a 10% chance whenever a hot or direct spell heals, with a 45 sec internal cooldown**) you gain a buff (the Blessing) on yourself. Now all of your heals for the next 15 sec cause an 8 sec damage shield. The shield stacks with itself. It includes healing done by subsequent ticks of existing hots on the target. **Note that the spell has to actually heal, so hots ticking on a fully-healed target cannot cause the proc**. However the shield is based on the size of the heal itself, not the amount healed – i.e. **100% overhealing will not proc the Blessing on the healer, but the shield itself includes overhealing once the Blessing is active**. The shield can grow to a maximum size of 20,000 damage absorbed.

**Example:** A druid casts Rejuvenation on the tank, healing her. The Blessing procs on the druid on the second tick. A shield is applied to the tank which absorbs 15% of the amount healed by that tick and each remaining tick of the Rejuv. If the druid also gets Lifebloom and Regrowth on the tank while the Blessing is up, then those ticks also contribute to the shield. If the shield goes down because the 8 sec duration expires or it absorbs that much damage, it can go up again as long as the Blessing lasts, which is 15 sec.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a druid.
2. Go level 80.
3. Add and equip Val'anyr to the character. _.add 46017_
4. Create a second character, level up to level 80 and make him some _.damage_ (he should be below 100% health).
5. Cast Rejuvenation to the second character. You will notice that proc does not activate.

##### AC/HASH COMMIT
[90526df](https://github.com/azerothcore/azerothcore-wotlk/commit/64c686c40c54f638a1cc3baeffcbbacc966a4a3d)

**Comment by mnclaras** [comment]
I think this should be done rewriting this line:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_item.cpp#L1677
Replacing `if (!spellInfo || !spellInfo->HasEffect(SPELL_EFFECT_HEAL))`
By `if (!spellInfo || (!spellInfo->HasEffect(SPELL_EFFECT_HEAL) && !spellInfo->HasAura(SPELL_AURA_PERIODIC_HEAL)))`

So it have periodic healings into account.

**Comment by Kitzunu** [comment]
With the "new" proc system you could do it in DB.

But it hasn't been fully ported unfortunatly
