### ISSUE TITLE
.reload smart_scripts not working

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4210]
##### CURRENT BEHAVIOUR:

`.reload smart_scripts` doesn't reload the table (at least not fully), I made some changes and tried to reload but it didn't work. I had to restart the server to see my changes effectively.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should correctly reload.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Edit some SAI
2. Try `.reload smart_scripts`
3. Check if your changes have been reloaded
4. Now try to restart the server and you'll see the changes

##### AC HASH/COMMIT:

672057316a51

**Comment by Kitzunu** [comment]
This worked without any problems for me when I made the fix for https://github.com/azerothcore/azerothcore-wotlk/pull/4079
