### ISSUE TITLE
Bugs after using #3369

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#4214]
##### CURRENT BEHAVIOUR:

Bugs after https://github.com/azerothcore/azerothcore-wotlk/pull/3369

```
.go c 65394
```
 When you swim to the center of the lake, the creatures will behave strangely.
Creatures will try to walk close to the bottom of the lake instead of swimming to attack you
![image](https://user-images.githubusercontent.com/18535853/103640485-0ce03200-4f8b-11eb-9927-d92730f0c901.png)

Sometimes it's there and it's spinning all the time
![image](https://user-images.githubusercontent.com/18535853/103640819-aa3b6600-4f8b-11eb-922a-e5f0e36f2426.png)

##### STEPS TO REPRODUCE THE PROBLEM:
```
.go c 65394
```
 When you swim to the center of the lake, the creatures will behave strangely.
Creatures will try to walk close to the bottom of the lake instead of swimming to attack you
##### AC HASH/COMMIT:
6ce5280

**Comment by Kitzunu** [comment]
@Helias
@Yehonal
@lucaAngrisani

**Comment by Helias** [comment]
Thanks for the test, we will take care of it!

**Comment by Yehonal** [comment]
Can you check this one please? https://github.com/azerothcore/azerothcore-wotlk/pull/4220

**Comment by pklloveyou** [comment]
OK, I'll try it
