### ISSUE TITLE
[eye of eternal]  Malygos spoil rotating

### ISSUE THREAD

**Issue by lwqlwq60** [azerothcore/azerothcore-wotlk#422]
**Description**: Malygos spoil rotating 

**Current behaviour**: Malygos move to land and attack the same player after cast VORTEX.  Malygos will spoil his attack rotating.

**Expected behaviour**: fix attack rotating

**Steps to reproduce the problem**:

1. go to eye of eternal alone and start the boss
2. wait malygos cast VORTEX
3.  Malygos move to land and attack you

**Branch(es)**: master

**AC hash/commit**:  e04409e

**Operating system**:  win7 64

**Modules**:  no

**Other Customizations**: no

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Viste** [comment]
eye of eternal not for 1 person most of instance don't work for one person

**Comment by lwqlwq60** [comment]
Okay .I know .I will try for many persons

**Comment by sucofog** [comment]
Delete this, it's not bug, invalid.
