### ISSUE TITLE
Tear in the Universe at North Gate Pass

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4221]
Tear in the Universe at North Gate Pass

##### CURRENT BEHAVIOUR:

A blue line between two object textures.

![image](https://user-images.githubusercontent.com/61194190/103762813-d816be00-5010-11eb-81ef-30dbd01c33df.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No line.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to North Gate Pass
2. Run from Loch Modan's side to Dun Morogh's side.
3. About halfway in (minimap guide) observe tear in universe.

##### EXTRA NOTES:

I use a custom texture pack but textures shouldn't change an object placement issue I don't think. I will mark as unconfirmed regardless.

##### AC HASH/COMMIT:

Chromiecraft 06-01-2021.
79aa56065427d

**Comment by FrancescoBorzi** [comment]
seems like a client glitch, probably nothing we can do about it

**Comment by JamesGent** [comment]
We could spawn a large boulder GOBJECT underneath the tear in the universe so it appears grey rather than blue and prevents people from falling through it?

**Comment by FrancescoBorzi** [comment]
not sure about that, would be worth to check on retail or other emus how it is

**Comment by aradep** [comment]
This is an issue with the 3d model itself. Not really fixable without a custom patch.

<details><summary>Same on TC.</summary>

![image](https://user-images.githubusercontent.com/61268368/104867676-cf2ec200-5917-11eb-864b-52fe53ef064c.png)

</details>

**Comment by Voxstrasza** [comment]
I can't for the life of me find this bluespace area in the tunnel.  I think this all depends on what client you use to rip data files from, because I don't have this issue at all
