### ISSUE TITLE
In Defense of the King's Land (263) Not Enough NPC Mobs to Complete(?)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4222]
In Defense of the King's Land (263) Not Enough NPC Mobs to Complete(?)

##### CURRENT BEHAVIOUR:

I went to complete in Defense of the Kings Lands (263) at South Loch Modan but could only find 3-4 quest NPCs in the entire trogg encampment. I'm putting it as not confirmed as I'm not 100% sure if I am dumb or not.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should be fully completable in both locations. More NPCs perhaps?

https://classic.wowhead.com/quest=263/in-defense-of-the-kings-lands

RELEVANT NPCS

Stonesplinter Shaman (1197)
Stonesplinter Bonesnapper (1164)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Pickup quest "In Defense of the King's Lands"
2. Go to South Loch Modan trogg camps.
3. Try to find the required NPCs.

##### AC HASH/COMMIT:

Chromiecraft 06-01-2021
79aa56065427d

**Comment by r0m1ntik** [comment]
![Снимок экрана 2021-01-06 в 23 52 52](https://user-images.githubusercontent.com/40755539/103827937-58253e00-507a-11eb-91fe-46b5177cb064.png)
