### ISSUE TITLE
Object Fade Distance on Barrel in Lakeshire Too Short 

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4228]
Object Fade Distance on Barrel in Lakeshire Too Short 

##### CURRENT BEHAVIOUR:

These object barrels fade unless you are within 10-15 yards or so. It's far too close. The boat looks like it is floating to anyone not extremely close to the boat.

One barrel has the correct fading, other 2 do not.

![image](https://user-images.githubusercontent.com/61194190/103926054-51e1a100-5110-11eb-9272-34172728b074.png)

![image](https://user-images.githubusercontent.com/61194190/103926075-57d78200-5110-11eb-891b-77ada8d6db58.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Barrels should fade the same distance as other barrels/boat.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Lakeshire
2. Look at boat
3. Get close/go far

##### AC HASH/COMMIT:

Chromiecraft 07-01-2021.
79aa560

**Comment by r0m1ntik** [comment]
![Снимок экрана 2021-01-07 в 19 27 31](https://user-images.githubusercontent.com/40755539/103930032-6b89e500-511e-11eb-859f-66cefd8b2fa5.png)
![Снимок экрана 2021-01-07 в 19 27 34](https://user-images.githubusercontent.com/40755539/103930037-6cbb1200-511e-11eb-8107-5f94483859c4.png)

**Comment by Helias** [comment]
I think it's a client-side issue too.

**Comment by Kitzunu** [comment]
Well, the question is, are these gameobjects or part of the map? It Will be easily understood what issue it is if we know that

**Comment by Helias** [comment]
I can't get any gob ID using .gob info/target so they are probably part of the map

**Comment by Kitzunu** [comment]
Then I think we can close
