### ISSUE TITLE
[NPC][WOTLK] Gothik the Harvester encounter minions(They are not scripted).

### ISSUE THREAD

**Issue by markvetwow** [azerothcore/azerothcore-wotlk#424]
**Description**: So,on Gothik's encounter,minions don't use any spells at all. Both on the living side, and on the undead side

**Current behaviour**: Descripted higher.

**Expected behaviour**: All minions on Gothik encounter must use their spells,like Shadow Mark from Death Knight on living side,and Arcane Explosion from Spectral Trainee on undead side.

**Steps to reproduce the problem**:

1.  Pull Gothik(start encounter)
2.  Wait around 1:30 to pack different NPCs
3.  You'll see,they don't use any spells.

**Branch(es)**: master

**AC hash/commit**:  e0d951c

**Operating system**:  WIndows 8.1 with all current system updates.

**Modules**: No, i don't

**Comment by starrheld** [comment]
I can confirm and also the door opens very quickly? Am I right?

**Comment by talamortis** [comment]
CreatureID?
