### ISSUE TITLE
[NPC] NPC does not patrol as it should

### ISSUE THREAD

**Issue by Gizmoh** [azerothcore/azerothcore-wotlk#4242]
##### CURRENT BEHAVIOUR:
Hezrul Bloocmark, NPC for this quest [Hezrul Bloodmark](https://classic.wowhead.com/quest=852/hezrul-bloodmark) is just standing there with his homies
![image](https://user-images.githubusercontent.com/4155081/104090083-efdd8480-5252-11eb-8f66-d4cf3f310285.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPC should patrol around the oasis as described in the link

##### AC HASH/COMMIT:
96a549c

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
    mod-cfbg
    mod-duel-reset

##### OTHER CUSTOMIZATIONS:
None

#### SERVER
ChromieCraft

**Comment by Helias** [comment]
fixed but... probably we should add the movement of his "homies"?

**Comment by FrancescoBorzi** [comment]
@Gizmoh please test this solution: https://github.com/azerothcore/azerothcore-wotlk/pull/4245

**Comment by Helias** [comment]
I fixed even the two NPCs near Hezrul ;-)
