### ISSUE TITLE
Level 255 stat issue.

### ISSUE THREAD

**Issue by FatGrandpa007** [azerothcore/azerothcore-wotlk#4243]
So I've recompiled with core edits that allow level 255, but there's a stat cap in player_levelstats, and also it goes completely bonkers ingame if items have too high stats.
Is there anyway to increase the amount a certain stat gives? Make 1 stamina give more than 10 health for example.

I cannot find anything that would fix it, I know you can change the 8bit to 16 or 32 in core inside player.h and player.cpp but I haven't been able to figure out what parts to change without build failures.
I also know its possible to have a higher stat attribute without the 8bit core changes but I have no idea how or where. 
I'm completely dead in tracks here.
Any help would be deeply appreciated. 
If this is the wrong place to post or if I'm posting it wrong I apologise. 

Best regards, Milo. 

Rev: bf089f47c11e+ 2021-01-07 00:38:51 +0000 (master branch) (Win64, Release)

**Comment by Kitzunu** [comment]
add rev and dont ignore template

**Comment by FatGrandpa007** [comment]
Template didn't show up on phone, I'll do it immediately from PC

**Comment by Kitzunu** [comment]
weird :D But add rev at least when possible

**Comment by BarbzYHOOL** [comment]
this is for custom and no idea if we can improve this without altering blizzlike AND without a specific config option

**Comment by Kitzunu** [comment]
I believe it is possible, just dont know how

**Comment by FatGrandpa007** [comment]
I mean I've seen it done, it was on my old server i just got no idea how it was done, I have the source and everything I just wasn't the developer making the changes. A lot of servers level 255 have crazy stats at the moment even Azerothcore based. So someone out there most know how, it can't be such a big deal

**Comment by BarbzYHOOL** [comment]
if you find the solution (you can ask on stackoverflow, ac web, forum, dunno) and it's not interfering, we can add it to AC
