### ISSUE TITLE
Eye of the Storm Emissary constantly falling in Darnassus

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#4247]
##### CURRENT BEHAVIOUR:
One EotS Emissary in Darnassus is constantly falling while pathing in Darnassus while the partner paths normally.  Pathing coords issue?

https://i.imgur.com/zgeZHua.jpg
https://i.imgur.com/Aic7Lu7.jpg
https://i.imgur.com/eHrPurE.jpg (has npc info in it)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPC is supposed to path normally like the counterpart seen in the SS.

##### STEPS TO REPRODUCE THE PROBLEM:
1. .tele darnassus
2. look for EotS emissary pathing near entrance
3. wait for them to path towards the entrance, the one on the right (if behind) will constantly fall

##### AC HASH/COMMIT:

7cf097eab2fc

##### OPERATING SYSTEM:
Win10

**Comment by Yehonal** [comment]
Fixed in:  https://github.com/azerothcore/azerothcore-wotlk/pull/4220

**Comment by Voxstrasza** [comment]
closing this then

**Comment by FrancescoBorzi** [comment]
@Voxstrasza no, let's not close issues until the fix is on `master` branch. Also please help testing the PR linked by Yehonal
