### ISSUE TITLE
Class/Weapon Trainers incorrect Mouse Icons [$15]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#4249]
##### CURRENT BEHAVIOUR:
Class trainers offer the same icon for every class, even if they're the incorrect class for that trainer.

In this image, I am a rogue hovering over the warrior trainer - it should just offer a generic gossip icon.

![](https://i.imgur.com/gov0vzG.jpg)

This behavior is present on **every single class trainer in the game.**  This might be in the core and not just the DB - if you re-flag the NPC, you'll end up with the generic gossip icon for same-class trainers.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Example:

![](https://i.imgur.com/nvVv0xf.png) - This icon should show if you're a hunter talking to the hunter trainer

![](https://i.imgur.com/kHfFML8.png) - This icon should show if you're a hunter talking to the warrior trainer

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create any class and zone into any starting zone, there are trainers in every starting zone
2. Go to a trainer that isn't for your class
3. Hover your mouse over the NPC and look at the icon

##### AC HASH/COMMIT:
f3f300a1defb

##### OPERATING SYSTEM:
Win10

**Comment by Voxstrasza** [comment]
[15 dollar bounty](https://www.bountysource.com/issues/95868725-class-trainers-incorrect-mouse-icons?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)

**Comment by lineagedr** [comment]
@Voxstrasza I'll PR https://github.com/lineagedr/azerothcore-wotlk/pull/1/commits/7553572640386be43fde2f818a0dd8f7f77a2a3c as soon as I figure out how to do two PRs from the same fork without them being together

**Comment by Voxstrasza** [comment]
Update; I've also found that some Weapon Trainers should have a generic gossip icon as well from this classic video: https://www.youtube.com/watch?v=hZsF4z-rw8Y&ab_channel=Exehn

when he goes to darnassus to train bows, there's a generic gossip icon and not the trainer book icon.

**Comment by UltraNix** [comment]
Made a PR - please, review it.
