### ISSUE TITLE
Casting spells from X distance no affecting some NPCs

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4252]
Attacking some NPCs on Tirifal Glades with spells not working and enters on cooldown.

https://youtu.be/BVKhV7dikKA

##### EXPECTED BLIZZLIKE BEHAVIOUR:
If NPC is on sight, spells will work as spected.

##### CURRENT BEHAVIOUR:
In some cases attacking an enemy on sight will do nothing and not pulling them.

##### STEPS TO REPRODUCE THE PROBLEM:
 
1. Go to Tirifal Glades to the tower near Scarlet Monastery
2. Cast a spell to a [Scarlet Bodyguard](https://classic.wowhead.com/npc=1660/scarlet-bodyguard#map) or the captain between them from the outside of the tower (tested with Mind blast at max range).
3. Nothing happens and spell enters in cooldown.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/20afed08c9570

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Voxstrasza** [comment]
Confirmed, this was happening to me on AC rev f3f300a1defb with a mage in Northshire (human start area)

**Comment by Kitzunu** [comment]
closed by https://github.com/azerothcore/azerothcore-wotlk/pull/4274
