### ISSUE TITLE
Balance module has no effect on ICC gunboat battle damage

### ISSUE THREAD

**Issue by forever2019** [azerothcore/azerothcore-wotlk#4255]
This module has no effect on adjusting the damage of ICC gunboat combat. The damage gap between us and the enemy is too big. We were defeated at the beginning of the battle

Enable the balance module and log in to the game
Enter. Go - 606.3696 2216.8457 199.9909 631
Find the gunboat, talk to NPC and start fighting
Request repair

The problem has been confirmed, please fix it
thank you
https://github.com/azerothcore/mod-autobalance/issues/75

**Comment by Kitzunu** [comment]
Not valid for the main repo
