### ISSUE TITLE
Ironforge Mystic Ward not Fishable

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4256]
Ironforge Mystic Ward not Fishable

##### CURRENT BEHAVIOUR:

Says water too shallow.

![WoWScrnShot_011121_133648](https://user-images.githubusercontent.com/61194190/104189313-683e7400-5412-11eb-9fa8-add12041bb01.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fishable water.

https://wow.gamepedia.com/Old_Ironjaw

"The waters in the Forlorn Cavern and the pool in the Mystic Ward have both been cited as sources for obtaining this elusive trophy. "

Source from 2008 claiming the same;

http://www.tentaclehaven.com/fish/old_ironjaw.html

##### STEPS TO REPRODUCE THE PROBLEM:

1. Learn fishing
2. Go to mystic ward water
3. Observe "too shallow" text.

##### EXTRA NOTES:

Chromiecraft 11-01-2021
20afed08c957

**Comment by Kitzunu** [comment]
@Yehonal

**Comment by Helias** [comment]
does it work before the pathfinding / movements commit?

**Comment by Kitzunu** [comment]
Is this even the pool you should fish in?
![image](https://user-images.githubusercontent.com/24550914/104225108-3c3ce600-5446-11eb-9c0f-636bcac1baeb.png)
I believe this is the correct one because the reported pool looks shallow af. Very sceptical

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/104225227-6abac100-5446-11eb-9077-69e19979b6c7.png)
yea I was correct

**Comment by JamesGent** [comment]
I've linked five sources, including two from 2008 that claim you can fish in the Mystic Ward in Vanilla.

https://wowwiki.fandom.com/wiki/Fishing_locations

Ironforge | Forlorn Cavern, Pool in Mystic Ward, Lava | 1 | 25 | [Raw Brilliant Smallfish],  [Raw Longjaw Mud Snapper],  [Raw Bristle Whisker Catfish]
-- | -- | -- | -- | --

https://wow.gamepedia.com/Old_Ironjaw

"The waters in the Forlorn Cavern and the pool in the Mystic Ward have both been cited as sources for obtaining this elusive trophy. "

http://www.tentaclehaven.com/fish/old_ironjaw.html

https://www.warcrafttavern.com/tbc/guides/fishing-1-375/

"On the Alliance side, Darnassus has a massive body of water surrounding The Temple Gardens, and Ironforge has pools in the Forlorn Cavern and the Mystic Ward."


There are hundreds of comments talking about fishing in the Mystic Ward dated 2006-2009 here;

https://www.wowhead.com/item=34484/old-ironjaw#comments;40


By 275712 (647 –  6)  on 2008/12/16 (Patch 3.0.3) |   |  
-- | -- | --
I decided to start fishing a few weeks ago because I want to try to get as many achievements as possible, and I knew fishing would take the most dedication and patience.

I went from 1-314 skill all in Ironforge, but finally found Ironjaw after about 1150 casts.

I did about 900 in the Forlorn Cavern, 50 near the Great Forge, and 100 near the Mystic Ward before finally catching him. 




Here is a comment from 2009 citing the possible removal of being able to fish in the mystic ward.

By threninduil (5,173 –  1·18·24)  on 2009/05/10 (Patch 3.1.1) |   |  
-- | -- | --
You can no longer fish in the Mystic Ward or the Great Forge. Waste of time.

**Comment by Kitzunu** [comment]
interesting ok

**Comment by JamesGent** [comment]
By threninduil (5,173 –  1·18·24)  on 2009/05/10 (Patch 3.1.1) |   |  
-- | -- | --

"You can no longer fish in the Mystic Ward or the Great Forge. Waste of time.

But I did catch old Ironjaw yesterday on my 324th cast!

No too shabby."

Did some DEEP DIGGING;

Fishing in Mystic Ward was an undocumented change and the ability to fish there was removed in 3.1.0.

Given this I'm happy to close.
