### ISSUE TITLE
NPC Flag Issue [$15]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#4261]
##### CURRENT BEHAVIOUR:
NPCs in starting areas that are involved in quests where a player would need to heal them have blue portraits (blue = player/player pets) despite being flagged for PvP in the database.  From the ones I've personally scouted out, these NPCs are:

Draenei Survivor (Draenei)
Sentinel Shaya (Night Elf)
Guard Thomas (Human)
Mountaineer Dolf (Dwarf)
Deathguard Kel (Undead)
Grunt Kor'ja (Orc & Troll)

This might also be an issue with Tavara (objective of Draenei Priest quest) and Eversong Rangers (objective of Blood Elf Priest quest).

I believe that something was created as a workaround - TC issues will be linked below that are related to this issue.

Out of these, it's probably worth to note that Draenei Survivor is the only NPC in the Draenei starting zone (Ammen Vale) that **can be attacked and killed** by Horde players (NPCs in starting zones: Shadowglen, Northshire Valley, Ammen Vale, Valley of Trials, etc are **usually flagged as civilians and cannot be attacked by opposing faction players**).  I am not sure if this rule applies to others, but Draenei Survivor is actually **inside** of Ammen Vale, and the other NPCs are near the secondary starting zone(ex: Goldshire, Razor Hill, etc).  See for more info:  https://wow.gamepedia.com/Draenei_Survivor

Additionally, Draenei Survivor is the only one **not involved** with a Priest quest, but it's similar in that the NPC needs to be healed (draenei racial).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These NPCs should all have a green portrait, be flagged for PvP for their respective faction and **still be able to** be healed to complete their respective quests.

##### EXTRA NOTES:

See below for similar/same issues:

https://github.com/TrinityCore/TrinityCore/issues/19963
https://github.com/TrinityCore/TrinityCore/issues/17075
https://github.com/TrinityCore/TrinityCore/issues/13676

##### AC HASH/COMMIT:
f3f300a1defb

##### OPERATING SYSTEM:

Win10

**Comment by Voxstrasza** [comment]
[$15 dollar bounty](https://www.bountysource.com/issues/95865788-npc-flag-issue)

**Comment by lineagedr** [comment]
@Voxstrasza  Let me know after https://github.com/azerothcore/azerothcore-wotlk/pull/4270
