### ISSUE TITLE
Pets should attack from behind the target

### ISSUE THREAD

**Issue by Footman** [azerothcore/azerothcore-wotlk#4262]
##### CURRENT BEHAVIOUR:

Character Pets start to attack NPCs from movement direction but should place themselfs behind NPC automatically all the time and avoid to be parried.
This Issue was fixed and works on Trinitycore [https://github.com/TrinityCore/TrinityCore/issues/19925](url)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The movement generator for pets should try to position them behind NPC targets when attacking (except player Pets)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Summon a hunter or warlock pet
2. Send it to attack a creature

##### AC HASH/COMMIT:

fd35054

##### OPERATING SYSTEM:

Ubuntu 20

##### MODULES:

CFBG
Transmog

**Comment by Kitzunu** [comment]
@Yehonal

**Comment by Footman** [comment]
closed by #aab4f41

**Comment by Kitzunu** [comment]
Nice just to wait for master merge 👍

**Comment by Algorak** [comment]
It's nice, I reported the same thing with pictures etc and didn't get an answer haha ​​... and months ago.

**Comment by FrancescoBorzi** [comment]
> It's nice, I reported the same thing with pictures etc and didn't get an answer haha ​​... and months ago.

I hope you realise that all people who work on this project are volunteers and not being paid for what they do.
You can place a bounty on your report to support the open-source development.
