### ISSUE TITLE
Weird Mob Behaviour in Darkshore (Pathing/Obstacle Finding?)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4268]
Weird Mob Behaviour in Darkshore

##### CURRENT BEHAVIOUR:

The murlocs stutter step very weirdly all the time.

https://youtu.be/CDQMCF6D2Z4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal mob behaviour.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Darkshore, COORDS 36,76ish
2. Observe Murlocs

Greymist Warrior NPC ID 2205

##### AC HASH/COMMIT:

Chromiecraft 12-01-2021
20afed08c957

**Comment by nicoaravena** [comment]
Found this bug also with some mobs in Coldridge Valley, but it does not happens with #4274, also went to darkshore to see this and is not present there.
