### ISSUE TITLE
Onu Quest Chain Out of Order

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4269]
##### CURRENT BEHAVIOUR:

You can complete "Onu is Meditating" before you begin the quest chain that leads to what it refers to/requires.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Onu is Meditating is a backup to help you finish https://classic.wowhead.com/npc=3616/onu which is the 3rd part of a 5 part chain.

You should not be able to complete Onu is Meditating before beginning the chain or it will brick your character.

https://classic.wowhead.com/npc=3616/onu

https://classic.wowhead.com/quest=960/onu-is-meditating

https://classic.wowhead.com/quest=961/onu-is-meditating

For added confusion there are 2 identical Onu is Meditating quests in the game.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Onu
2. Complete part 3 of the chain before beginning part 1
3. Crash and burn

##### EXTRA NOTES:

Chromiecraft 12-01-2021
20afed0

I have put the priorit as high because doing this chain out of order has bricked one of my characters to always crash on login. I'm still investigating to what extent this breaks things.

**Comment by Helias** [comment]
I can confirm, I will fix it asap
