### ISSUE TITLE
[CORE][INSTALLATION] Linux

### ISSUE THREAD

**Issue by lif3st3al3r** [azerothcore/azerothcore-wotlk#427]
**Description**: Compile Error

**Steps to reproduce the problem**:

1. cmake ../ -DCMAKE_INSTALL_PREFIX=/home/azeroth/azerothcore-wotlk-master/build -DCONF_DIR=/home/azeroth/azerothcore-wotlk-master/build -DLIBSDIR=/home/azeroth/azerothcore-wotlk-master/build -DCMAKE_BUILD_TYPE=RelWithDebInfo

2. make -j 4
3. http://imgur.com/QeTUoJ7

**Branch(es)**:Master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/fbe5e8c0dc01e3fae4a1c500225a55bb2c5c93dc

**Operating system**:  Kali Linux x64

**Modules**:  Are you using modules? NO

**Other Customizations**: NO

**Comment by Viste** [comment]
i use cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/server/ -DWITH_COREDEBUG=1 -DCMAKE_C_FLAGS="-march=k8 -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -pipe -pipe -msse3 -fomit-frame-pointer -ffast-math -fno-strength-reduce -fno-strict-aliasing -frename-registers" && make -j 5 and all ok

**Comment by lif3st3al3r** [comment]
http://imgur.com/a/r4qMX

Openssl 1.0.2k

**Comment by Viste** [comment]
don't have that on OpenSSL 1.0.1k 8 Jan 2015

**Comment by lif3st3al3r** [comment]
http://imgur.com/a/nvHIy

**Comment by Viste** [comment]
Something you do wrong

**Comment by starrheld** [comment]
Greetings!
For all support inquiries please join our Discord server at the following address **https://discord.gg/nNH3GvT**. Wish to hear from you there.

Best regards,
**AZEROTHCORE COMMUNITY**

**Comment by falzard** [comment]
And use the support channel!
