### ISSUE TITLE
Old Ironjaw / Old Crafty may not be fishable.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4272]
Old Ironjaw / Old Crafty may not be fishable.

I am tagging this as not confirmed because there's no way to be sure, but this is statistically extremely unlikely behaviour.

##### CURRENT BEHAVIOUR:

I have fished 5000 times in Ironforge Forlorn Caverns.

Old Ironjaw is a 0.1% rate.

0.1% x 1000 = 100%.

You'd expect to get it after a thousand fishes, give or take.

The chances of no Ironjaw after 5000 fishes is less than 0.5%.

![Desktop 13-01-2021 15-43-19-732](https://user-images.githubusercontent.com/61194190/104474871-5bf31c00-55b6-11eb-902d-1446422ec602.png)

![Desktop 13-01-2021 15-43-41-170](https://user-images.githubusercontent.com/61194190/104474876-5d244900-55b6-11eb-80c4-b7b5b938378b.png)

Am I the 0.5% unlucky, or is it not working? I will keep fishing but the longer I fish the more likely it is that something is broken than I am unlucky.

For context, the 1-Ring has a 0.02% droprate and I have 4 of those so far.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be fishable in Forlorn Cavern.

https://classic.wowhead.com/item=8350/the-1-ring

https://www.wowhead.com/item=34484/old-ironjaw

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do not attempt to reproduce this if you have a life.
2. Fish 5000 times.
3. Observe the statistically improbable.

##### EXTRA NOTES:

Chromiecraft 13-01-2021
20afed08c957

**Comment by Kitzunu** [comment]
0.1% x 1000 = 100%.

does not work like this. It is 0.1% chance per fishing, so you will never be guaranteed one after 1000 fishes.

HOWEVER, you can easily test this by increasing the dropchance in DB to 100% to see if it drops =)

**Comment by JamesGent** [comment]
> 
> 
> 0.1% x 1000 = 100%.
> 
> does not work like this. It is 0.1% chance per fishing, so you will never be guaranteed one after 1000 fishes.

I understand that 1000 x 0.1 is not guaranteed. 

However, it is the statistical expected value of the result. You would usually expect to find one within a few standard deviations of this number.

Not getting it after 5300+ fishes when you would statistically expect it after 1000 is statistically extremely unlikely, shown by the screenshot of the website calculator.

As shown in the source above, the chance that it does not occur after 5000 attempts is less than 0.6%.

I'm at 5300 now which puts it at less than 0.5% chance of occuring.

I think it is is more likely that Ironjaw is not working like other fishing problems don't, than I am 0.5% unlucky. For example, the STV event does not work, and other water in Ironforge is not flagged as fishable at all (I have opened issues for both of these).

The chance something is not working in AzerothCore is higher than 0.5%. Maybe the droprate isn't flagged to Ironforge water, maybe Ironforge's water isn't flagged as water, maybe the Forlorn cavern water is not set to match the loot-table that contains Ironjaw, maybe Ironjaw is not in the loot table it should be?

I'll never be able to know for sure, so I tagged it as "not confirmed", but it is looking increasingly likely that it is broken.

What's more likely? Is there a possibile 0.5% chance AzerothCore doesn't have this working?

> HOWEVER, you can easily test this by increasing the dropchance in DB to 100% to see if it drops =)

I don't have acore myself atm I can only test on Chromiecraft. Let me know what this experiment does for you.

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/104484088-2277dc00-55c9-11eb-95af-325c81233827.png)
![image](https://user-images.githubusercontent.com/24550914/104484144-36234280-55c9-11eb-8fce-800c0a369f21.png)

Set to 100%, works.

**Comment by JamesGent** [comment]
Reee. Then I am just the unluckiest dude to live. Gonna close it now.

**Comment by Kitzunu** [comment]
ouch

**Comment by Voxstrasza** [comment]
@JamesGent one of the dudes on chromiecraft just fished it @ 0.1% droprate in 271 attempts

xd
