### ISSUE TITLE
Misplaced item drop, Bad Clams on Sorrow Wing

### ISSUE THREAD

**Issue by Gizmoh** [azerothcore/azerothcore-wotlk#4282]
##### CURRENT BEHAVIOUR:
I got this item https://wotlkdb.com/?item=43491 out of this mob https://wotlkdb.com/?npc=5928
![imagen](https://user-images.githubusercontent.com/4155081/104664697-abb50e80-56ae-11eb-9dbe-ea84ceb60413.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This is a TBC item, it shouldn't drop in classic content

##### STEPS TO REPRODUCE THE PROBLEM:
Kill Sorrow Wing, cross your fingers?

##### AC HASH/COMMIT:
df600f9

OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

**Comment by Voxstrasza** [comment]
it's actually a wotlk item

https://wow.gamepedia.com/Recipe:_Bad_Clams
