### ISSUE TITLE
Changing spec only remove auras of the talent that are rank 1.

### ISSUE THREAD

**Issue by lineagedr** [azerothcore/azerothcore-wotlk#4284]
##### CURRENT BEHAVIOUR:

After changing specs you don't lose all auras of the talent you have learned.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After changing specs you should lose all auras that you have learned from the previous spec.

##### STEPS TO REPRODUCE THE PROBLEM:

Example: Have two specs :
1. Frost 
2. Arcane

While in spec 1 cast Ice Barrier any rank that's not rank 1.
Change to Arcane spec
Watch how Ice barrier stays on your character.

##### EXTRA NOTES:

This is where they're removed https://github.com/azerothcore/azerothcore-wotlk/blob/d237274a66aa0a379f7ae45922aed22f382cce3d/src/server/game/Entities/Player/Player.cpp#L26900

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/d237274a66aa0a379f7ae45922aed22f382cce3d

##### OPERATING SYSTEM:

Windows 10

**Comment by Kitzunu** [comment]
Good catch!

**Comment by Kitzunu** [comment]
This is what TC does if I am not mistaken
```cpp
        for (int8 rank = MAX_TALENT_RANK-1; rank >= 0; --rank)
        {
            // skip non-existing talent ranks
            if (talentInfo->RankID[rank] == 0)
                continue;
            RemoveSpell(talentInfo->RankID[rank], true); // removes the talent, and all dependant, learned, and chained spells..
            if (SpellInfo const* _spellEntry = sSpellMgr->GetSpellInfo(talentInfo->RankID[rank]))
                for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)                  // search through the SpellInfo for valid trigger spells
                    if (_spellEntry->Effects[i].TriggerSpell > 0 && _spellEntry->Effects[i].Effect == SPELL_EFFECT_LEARN_SPELL)
                        RemoveSpell(_spellEntry->Effects[i].TriggerSpell, true); // and remove any spells that the talent teaches
```

**Comment by Footman** [comment]
> This is what TC does if I am not mistaken
> 
> ```c++
>         for (int8 rank = MAX_TALENT_RANK-1; rank >= 0; --rank)
>         {
>             // skip non-existing talent ranks
>             if (talentInfo->RankID[rank] == 0)
>                 continue;
>             RemoveSpell(talentInfo->RankID[rank], true); // removes the talent, and all dependant, learned, and chained spells..
>             if (SpellInfo const* _spellEntry = sSpellMgr->GetSpellInfo(talentInfo->RankID[rank]))
>                 for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)                  // search through the SpellInfo for valid trigger spells
>                     if (_spellEntry->Effects[i].TriggerSpell > 0 && _spellEntry->Effects[i].Effect == SPELL_EFFECT_LEARN_SPELL)
>                         RemoveSpell(_spellEntry->Effects[i].TriggerSpell, true); // and remove any spells that the talent teaches
> ```

I tested with this code before. It has same effect.

**Comment by pklloveyou** [comment]
tested
