### ISSUE TITLE
[Warlock] Demonic Knowledge wrong calculation.

### ISSUE THREAD

**Issue by lineagedr** [azerothcore/azerothcore-wotlk#4287]
##### CURRENT BEHAVIOUR:

Getting wrong spell power from demonic knowledge talent.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

We should get the correct spell power.

##### STEPS TO REPRODUCE THE PROBLEM:

3/3 Talent Info:
Increases your spell damage by an amount equal to 
12% of the total of your active demon's Stamina plus Intellect.
--

Example Player:
Player Spell Power: 726
Imp stamina: 756
Imp Intellect: 657
Imp sta + Imp Int = 1413
12% of 1413 = 169.56
726 + 169.56 = 895.56 <- which is correct however we only get 881

##### EXTRA NOTES:

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_warlock.cpp#L293

https://github.com/azerothcore/azerothcore-wotlk/blob/8e0a48d43d12c5d2637885e62c5de3a88e845219/src/server/game/Entities/Unit/Unit.cpp#L16280

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/8e0a48d43d12c5d2637885e62c5de3a88e845219

##### OPERATING SYSTEM:

Win10

**Comment by GMKyle** [comment]
I'm not sure this is an issue, the one who coded Demonic Knowledge used 12%(STA + INT) not 12%(STA)+INT, if i read the talent desc the current behavior appears to be correct, but hey!! i'm not english specialist (Spanish talker) :P
Trinity use the same formula than us (may be wrong too)

https://github.com/TrinityCore/TrinityCore/blob/0b7b7f10f90eb5ef25c47749455572bcaa662d98/src/server/game/Entities/Pet/Pet.cpp#L1932
```c++
args.AddSpellMod(SPELLVALUE_BASE_POINT0, CalculatePct(aura->GetDamage(), GetStat(STAT_STAMINA) + GetStat(STAT_INTELLECT)));
```
