### ISSUE TITLE
[CORE][MODULE] Anticheat

### ISSUE THREAD

**Issue by iraj0711** [azerothcore/azerothcore-wotlk#429]
hi
compile core has error
can not copy file Anticheat.conf.dist in module to file bin

**Comment by Viste** [comment]
this module is bullshit and not work

**Comment by iraj0711** [comment]
help me.
the best anticheat for azerothcore???

**Comment by ShinDarth** [comment]
it would be nice to wrap it into a module

**Comment by sucofog** [comment]
But AC2 breaks transports, spells LoS related and a lot of things, is not stable, tested on live realm with AC.

**Comment by DarkmoonRabbit** [comment]
I think that the Anticheat module can continue to improve the development, it is a good module.

**Comment by Yehonal** [comment]
i've actually fixed compilation with arbitrary module name and opened the issue tracker for this module:

https://github.com/azerothcore/mod-anticheat/issues

please post any issue there

**Comment by Yehonal** [comment]
https://github.com/azerothcore/mod-anticheat/commit/1ba93ff80ce82e5fc4e954e99148287e8f2b3294
