### ISSUE TITLE
Apps/db_assambler: Mysql: command not found

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4291]
##### CURRENT BEHAVIOUR:

Currently, I get the error `bash: mysql: command not found` when I use any of the options 5 through 8 as shown in the image below

![image](https://user-images.githubusercontent.com/24550914/104794485-30378800-57a8-11eb-9cf2-e346f392dc72.png)
 
I think that perhaps this is only an issue on Windows?

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The command shall be found

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run the assembler and use any of the options 5 - 8

**Comment by locus313** [comment]
@Kitzunu Are you using git bash or wsl? The db_assambler script expects that you already have mysql installed. Your getting that error because its ether not installed or not in the path.

**Comment by Kitzunu** [comment]
git bash

**Comment by Kitzunu** [comment]
Going to close this, thanks to locus I could google the issue and this was the solution

https://dev.mysql.com/doc/mysql-windows-excerpt/8.0/en/mysql-installation-windows-path.html
