### ISSUE TITLE
"Chest of The Seven" from Blackrock Depths should spawn in a different position

### ISSUE THREAD

**Issue by Zoidwaffle** [azerothcore/azerothcore-wotlk#4293]
##### CURRENT BEHAVIOUR:

Currently the chest spawns halfway over a ledge and in the middle of the room.

![old_chest](https://user-images.githubusercontent.com/541438/104807267-09944400-57de-11eb-9f74-1e57ec7d2d92.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The chest should spawn next to the door - this is from a video on [YouTube](https://youtu.be/QoEwUz7Bdq8?t=1664)

and for your convenience, I took a screenshot:

![screenshot_youtube](https://user-images.githubusercontent.com/541438/104807283-216bc800-57de-11eb-8ed3-6e894893cc08.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele brd
2. .go c id 9039
3. As a GM you can see the chest not being by the door.

##### EXTRA NOTES:

I tried to fix this - if you apply this query:

```
-- "Chest of The Seven" from Blackrock Depths should spawn in a different position

UPDATE gameobject SET position_x="1265.55", position_y="-284.421", position_z="-78.2193", orientation="0.786698", rotation2="-0.383284", rotation3="-0.923631" WHERE guid=67872;
```

Then it will look like this:

![new_chest](https://user-images.githubusercontent.com/541438/104807323-78719d00-57de-11eb-8a9b-852cef3c231e.png)

And I think it looks pretty close to what it should.

##### AC HASH/COMMIT:

[37cb9f524218](https://github.com/azerothcore/azerothcore-wotlk/commit/37cb9f524218)

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

mod-account-achievements
mod-ah-bot
mod-arac
mod-autobalance
mod-congrats-on-level
mod-morph-all-players
mod-morphsummon
mod-npc-buffer
mod-transmog
mod-weapon-visual

**Comment by Voxstrasza** [comment]
make a PR homie

**Comment by Zoidwaffle** [comment]
OK, so I tried to make a PR - I can see I don't have the part with:

```
DROP PROCEDURE IF EXISTS `updateDb`;
etc.
```

that can be seen in the **./data/sql/updates/db_world/** folder files, but should I add that as well?

**Comment by Kitzunu** [comment]
that should not exist, it is added by a bot when merged

**Comment by Kitzunu** [comment]
You have done correctly apart from my remarks in the PR

**Comment by Zoidwaffle** [comment]
Thanks, I should have fixed it now :+1:

**Comment by BarbzYHOOL** [comment]
Nice work!

btw to make a PR there is a lengthy guide on the wiki
