### ISSUE TITLE
[ZONE][WOTLK] Wintergrasp

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#430]
**Description**:
Wintergrasp bugs all in one

**Current behaviour**: 
First don't work buff When there are more players in the team than in yours.
Second If all the workshops were in the allience control and wintergrasp to, when won the horde capturing for example 2 workshops, then on the next wintergrasp all the workshops will become in the possession of the alliance 
Anotherone when win horde wintergrasp say "allience bla bla" its not critical but funny :D 
**Expected behaviour**: hard to translate >_< 

**Steps to reproduce the problem**:

1. Go to WG Fight! and you see all bugs from behaviour

**Branch(es)**: master

**AC hash/commit**:  c4ed0375d4f091d2cdc0efbb8ca84bef2d846109

**Operating system**:  Debian 8

**Modules**:  yes transmog by rochet2, arena points announce 

**Other Customizations**: no

**Comment by Viste** [comment]
If there is time and I understand how to correct, I will correct and open PR.
If not, I will wait for help from God or one of you

**Comment by sucofog** [comment]
1st bug tenacity its true, it does not give sometimes the buff, but it applies sometimes.
2nd bug its verified, yes
3rd bug, its not valid, a problem of your locales probably

**Comment by Viste** [comment]
I fix buff by changing battlefieldWG to original sunwell core

**Comment by ShinDarth** [comment]
@Viste if you managed to get something working, please open a PR

**Comment by Viste** [comment]
@ShinDarth as you can see i alway do that, need some test before open PR. As i know some of members of AC merege fix to that buff but it fix break buff only :D  so i first test then open PR

**Comment by Viste** [comment]
@ShinDarth as i say i open PR when test it in some cases for me all is ok  need community feedback
