### ISSUE TITLE
NPC audio banter heard from afar 

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4303]
This issue has been originally reported by @a-man-of-culture to the ChromieCraft bugtracker (https://github.com/chromiecraft/chromiecraft/issues/17).

I'm not sure myself whether it's just the way the client behaves or if we should do something on the server-side, so any feedback is welcome.

##### SMALL DESCRIPTION:

You can hear lazy peons from a fairly big range, even underground.
https://vimeo.com/501255732

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC sounds should fade out with distance.

##### CURRENT BEHAVIOUR:

When Lazy Peon NPCs say their classic WC3 "Work-work!", you can hear them from half a valley away, even in the cave.
The volume is like they are standing right next to you.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Valley of Trials.
2. Find a Lazy Peon.
3. Get some distance.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
I think it's more a client issue, considering the same position of the video and the related NPCs they are not so far.
There are exactly two lazy peon near the cave

![image](https://user-images.githubusercontent.com/519778/105217034-a3981b80-5b53-11eb-9687-f03c92f10803.png)

![image](https://user-images.githubusercontent.com/519778/105217070-b01c7400-5b53-11eb-84d9-f9d84eadf5ad.png)

**Comment by Kitzunu** [comment]
Have you checked TC?

**Comment by Helias** [comment]
Personally I don't

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9525
PR is put in, took a bit of research. But this issue is valid. Thank you @FrancescoBorzi for reopening it.
Comments and sniff referenced is at the PR link.
