### ISSUE TITLE
Core/Chat: Players can ignore GM's

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4309]
##### CURRENT BEHAVIOUR:

Currently you, as a player, can ignore a GM via the friend tab / the /ignore command and thereby the GM cannot whisper the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

A player should not be able to ignore a GM

##### STEPS TO REPRODUCE THE PROBLEM:

1. two accounts, one user one gm
2. /ignore GMchar
3. Try to whisper the user from GM

**Comment by Voxstrasza** [comment]
is this even with .gm on?  if .gm isn't on, it should be flagged differently iirc and being ignored is possible - if it's on, the opposite

**Comment by Kitzunu** [comment]
I actually cant remember what I tested with ngl

**Comment by wizzymore** [comment]
Hi,

To talk as a GM player, you don't need to have .gm on, you have to have .gm chat on.
Because you can be a .gm on but the chat features are appearing only when your badge is on and this overrides any ignore or any other stuff.

**Comment by wizzymore** [comment]
Proof:

- Ignoring Admin
![image](https://user-images.githubusercontent.com/25827787/105112596-0d6ce280-5acc-11eb-87c6-1d64a040e72a.png)

- Testing the ignore as a normal player ( .gm off and .gm chat off )
![image](https://user-images.githubusercontent.com/25827787/105112612-165db400-5acc-11eb-9551-229d97eb0eda.png)

- Setting only .gm chat on ( with .gm off )
![image](https://user-images.githubusercontent.com/25827787/105112625-1d84c200-5acc-11eb-9c98-a8edde319dc4.png)

- Whispering now the player
![image](https://user-images.githubusercontent.com/25827787/105112644-24abd000-5acc-11eb-9952-34311c28c1ec.png)

- What the player sees
![image](https://user-images.githubusercontent.com/25827787/105112655-29708400-5acc-11eb-8aa7-298be8d167ff.png)

**Comment by Kitzunu** [comment]
I could've sworn I did the same.

Anyways, Thanks!
