### ISSUE TITLE
[TOOLS] Incompatible with Trinitycore generators?

### ISSUE THREAD

**Issue by knuxyl** [azerothcore/azerothcore-wotlk#431]
**Description**:
I got vmaps, dbc, maps, and mmaps from using the generators in TrinityCore source and worldserver was giving an "incompatible version" error.

**Current behaviour**: Tell us what happens
The tools build fine on Linux from AzerothCore but I couldn't find the build (found them later) so I built from TrinityCore source and those files won't work with current build.

**Expected behaviour**: Tell us what should happen instead
I don't know if this is expected or not.

**Steps to reproduce the problem**:

1.  Build AzerothCore
2.  Build TrinityCore Tools
3.  Use Tools from TrinityCore to get maps, mmaps, dbc, and vmaps
4.  Try to use them with AzerothCore

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master

**AC hash/commit**:  

**Operating system**:  
Xubuntu 16.04.2 LTS x86_64

**Modules**:  Are you using modules? if yes, list them
no

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
no

**Comment by Rushor** [comment]
tools from tc and sunwellcore are completely different

**Comment by knuxyl** [comment]
Thank you
