### ISSUE TITLE
dbc data overriding from sql [30$]

### ISSUE THREAD

**Issue by Romain-P** [azerothcore/azerothcore-wotlk#4312]
##### DETAILS

3 tables can't get loaded for overriding dbc data
```
spellitemenchantmentcondition_dbc
skilllineability_dbc
charstartoutfit_dbc
```

- charstartoutfit_dbc error (assertion fails at https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/shared/DataStores/DBCDatabaseLoader.cpp#L101)
```
ac-worldserver_1  | /azerothcore/src/server/shared/DataStores/DBCDatabaseLoader.cpp:101 in Load ASSERTION FAILED:
ac-worldserver_1  |   false
ac-worldserver_1  | Unsupported data type 'X' in table 'charstartoutfit_dbc'
```

- skilllineability_dbc error (assertion fails at https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/shared/DataStores/DBCDatabaseLoader.cpp#L108)
```
ac-worldserver_1  | /azerothcore/src/server/shared/DataStores/DBCDatabaseLoader.cpp:108 in Load ASSERTION FAILED:
ac-worldserver_1  |   sqlColumnNumber == result->GetFieldCount()
ac-worldserver_1  | SQL format string does not match database for table: 'skilllineability_dbc'
```

- spellitemenchantmentcondition_dbc (same assertion fail)

##### STEPS TO REPRODUCE THE PROBLEM:
- Download this patch: https://github.com/wowgaming/client-data/releases/download/dbc_sql_v1/AzerothcoreDBCToSQL.zip
- It contains all dbc as sql
- Start azeroth-core

##### OPERATING SYSTEM:
- Docker Ubuntu

**Comment by kaytotes** [comment]
@Yehonal I've added a $15 bounty to this: https://www.bountysource.com/issues/96019265-dbc-data-overriding-from-sql

**Comment by Winfidonarleyan** [comment]
:/

**Comment by ChromieCraftServer** [comment]
Added 15$ more

**Comment by heyitsbench** [comment]
Can confirm `skilllineability_dbc` at least is still an issue as of 1a043114689514a09d3fdedec5d52c0648fca43a.
