### ISSUE TITLE
Feature: override data

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#4313]
**Describe your feature request or suggestion in detail**
I would like to have a `custom_data` directory that overrides the `data` content to have the official data in `server/data` and my custom ones in `custom_data/` just to keep the two contents separate.

**Additional context**
This can be helpful for those who work with custom client data.

**Comment by BarbzYHOOL** [comment]
what about sql in data/ ?

**Comment by Helias** [comment]
You can import the SQL, it is not necessary to keep them in data I think

**Comment by BarbzYHOOL** [comment]
i just meant need to move the sql directory maybe

**Comment by Kitzunu** [comment]
_dbc tables overrides existing dbc files
