### ISSUE TITLE
[RAID][ZAM] Hex Lord Malacrass Wrong Positon and Wrong Spawntime

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#4314]
##### CURRENT BEHAVIOUR:

Hex Lord Malacrass Stand at wrong positon ,
and it will respawn after almost 5mintus later

##### EXPECTED BLIZZLIKE BEHAVIOUR:

should at the center of other 4 boss 
and respawn time is 72 hours

##### STEPS TO REPRODUCE THE PROBLEM:

1. go zam map
2. go the boss Hex Lord Malacrass 
3. find it was at right side - the wrong place
4. kill it
5. wait 5-6 minuts

##### AC HASH/COMMIT:

01c830ed4691

##### OPERATING SYSTEM:

Ubuntu 20

##### OTHER CUSTOMIZATIONS:

FIXed:
```sql
DELETE FROM `creature` WHERE (`id` = 24239) AND (`guid` IN (3110431));
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(3110431, 24239, 568, 0, 0, 1, 1, 0, 1, 117.26, 920.861, 33.8893, 1.59275, 259200, 0, 0, 401530, 67740, 0, 0, 0, 0, '', 0);
```

**Comment by FrancescoBorzi** [comment]
thanks for the provided fix @betayi , can you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it? thank you!

**Comment by betayi** [comment]
> thanks for the provided fix @betayi , can you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it? thank you!

i never created PR, but i'll have a try tomorrow,
and by the way ,the  boss looks like  missed some file of his weapon , it was a  masaic image！

**Comment by mpfans** [comment]
Above is a bug fixed
The original create guid is 89357,if the above SQL is executed, two boss will appear
The correct repair is as follows:
```sql
UPDATE `creature` SET `position_x` = '117.26',`position_y` = '920.861',`position_z` = '33.8893',`orientation` = '1.59275',`curmana` = '67740' WHERE `guid` = '89357' AND id =24239;

**Comment by betayi** [comment]
> Above is a bug fixed
> The original create guid is 89357,if the above SQL is executed, two boss will appear
> The correct repair is as follows:
> 
> ```sql
> UPDATE `creature` SET `position_x` = '117.26',`position_y` = '920.861',`position_z` = '33.8893',`orientation` = '1.59275',`curmana` = '67740' WHERE `guid` = '89357' AND id =24239; 
> ```

Thanks a lot ! you are right!
