### ISSUE TITLE
Failed to Build using Installation Guide

### ISSUE THREAD

**Issue by btaylor-ihr** [azerothcore/azerothcore-wotlk#432]
Hi, terribly sorry if this is not in the right place, but my VS (Community 2017) failed to build a few files...

libeay32.dll
libmySQL.dll 
ssleay32.dll 
worldserver.conf.dist
worldserver.exe

When using CMAKE, MySQL did originally appear in the "Not found" errors, but I just copied the mysql files into C:/MySQL as noted in the requirements page. I didn't need to edit PATH variables for that. I did not use the Mysql Development Files that were provided in another link. Those files did already exist, and I was a bit dubious about using three year old files.

I'm a web developer so don't be afraid to throw technical stuff at me :)

This is the full output of VS during the build - http://paste2.org/zyP9XI6M

**Comment by Viste** [comment]
Delete plz this long shit and put only errors on paste2.org

**Comment by btaylor-ihr** [comment]
Thanks for the tip

**Comment by Viste** [comment]
@btaylor-ihr In your VS you have "errors" button plz put info from that inset of you VS  your output is not full its only successed >_<

**Comment by btaylor-ihr** [comment]
I'm new to VS sorry. I didn't notice that tab. I'll get it for you when I'm finished at work. Thanks for being patient :)

**Comment by Erotes** [comment]
You should be using VS15 Update 3 for a successful build, follow the installation instructions throughly before opening an issue AND install the MySQL Community Edition 5.6 OR 5.7, both work confirmed.

**Comment by btaylor-ihr** [comment]
Ah, that could be the cause. I'll give it a try tonight. I'll be sure to make the time. It said `Install Visual Studio >= 14`, so I thought that any future versions would be fine. I could still select the `Visual Studio 14 2015 Win64` compiler.

I did look for the "errors" button that was mentioned earlier, but I couldn't see it. I'll give the VS15 suggestion a go tonight :)

**Comment by btaylor-ihr** [comment]
I got it to build! I had to jump through a few hoops to get VS15u3, but I got there. Wound back CMAKE to 3.6 as well.

Thanks for you help guys :)
