### ISSUE TITLE
Core/Talents:m_extraBonusTalentCount Only in CLASS_DEATH_KNIGHT

### ISSUE THREAD

**Issue by yangyitzzg** [azerothcore/azerothcore-wotlk#4327]
CURRENT BEHAVIOUR:
I'm a novice and I don't know much about GitHub, so I'll feed back the questions here. When I tested it, I found that only death knight can take effect when calculating additional talent points. The specific code involved is: \src\server\game\Entities\Player\Player.cpp Player::CalculateTalentsPoints()

Fix Code:
```
uint32 Player::CalculateTalentsPoints() const
{
    uint32 talentPointsForLevel = 0;
    uint32 base_talent = getLevel() < 10 ? 0 : getLevel() - 9;

    if (getClass() != CLASS_DEATH_KNIGHT || GetMapId() != 609)
    {
        talentPointsForLevel = base_talent;
    }
    else
    {
        talentPointsForLevel = getLevel() < 56 ? 0 : getLevel() - 55;
        talentPointsForLevel += m_questRewardTalentCount;
        if (talentPointsForLevel > base_talent)
            talentPointsForLevel = base_talent;
    }

    talentPointsForLevel += m_extraBonusTalentCount;
    return uint32(talentPointsForLevel * sWorld->getRate(RATE_TALENT));
}
```

AC HASH/COMMIT:
[ab8967c](https://github.com/azerothcore/azerothcore-wotlk/commit/ab8967c6388684db95f1ea26a8c0692d1e8db941)

OPERATING SYSTEM:
Windows 10 20H2

MODULES:
NO MODULES

**Comment by FrancescoBorzi** [comment]
hi, thanks for your contribution! please read this: https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by BarbzYHOOL** [comment]
that's because it's only used in the death knight case i think, and so the original devs never bothered to make the function/feature work for other cases which is a shame (and prob ugly code)

does ur code allow to get extra bonus talents with an ingame feature, with smart_scripts or smthg like that? or is it just for the function itself?

**Comment by yangyitzzg** [comment]
> that's because it's only used in the death knight case i think, and so the original devs never bothered to make the function/feature work for other cases which is a shame (and prob ugly code)
> 
> does ur code allow to get extra bonus talents with an ingame feature, with smart_scripts or smthg like that? or is it just for the function itself?

I think that only using death knights may lead to a partial imbalance in the game, so I made a small change to the code so that it can be applied to all class. At present, only module can call Player->RewardExtraBonusTalentPoints() to add talent points

**Comment by yangyitzzg** [comment]
> hi, thanks for your contribution! please read this: https://www.azerothcore.org/wiki/How-to-create-a-PR

Due to the problem of my network, it is very difficult for me to clone the code base, so I hope you can help me complete this modification. Thank you very much.

**Comment by BarbzYHOOL** [comment]
Ok, it can be useful for sure.

Does it affect `Rate.Talent = 1` too?

**Comment by BarbzYHOOL** [comment]
@yangyitzzg

**Comment by yangyitzzg** [comment]
> Ok, it can be useful for sure.
> 
> Does it affect `Rate.Talent = 1` too?

Yes, the default is this setting

**Comment by pklloveyou** [comment]
confirm
