### ISSUE TITLE
Double Spawned Goblin Commoner in Booty Bay during Festival [$10]

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#4330]
Double Spawned Goblin Commoner in Booty Bay during Festival

##### CURRENT BEHAVIOUR:

2x NPCs

![WoWScrnShot_012321_014755](https://user-images.githubusercontent.com/61194190/105565122-17d1eb00-5d1d-11eb-8e54-307a89e1e512.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1x NPCs

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Booty Bay during Lunar Festival
2. GO to Alliance Flight Master
3. Observe 2x NPCs spawned inside eachother.

##### AC HASH/COMMIT:

ChromieCraft current.
AzerothCore rev. eb9819991e77 2021-01-22 10:25:07 +0100 (master branch) (Unix, RelWithDebugInfo)

**Comment by Helias** [comment]
This issue happen during the midsummer festival too.

**Comment by Helias** [comment]
P.S. = actually the NPCs are 4 to fix, there are even other 2 near the horde gryphon

**Comment by BarbzYHOOL** [comment]
several issues with commoners depending on the events, some are not even spawned

**Comment by Kitzunu** [comment]
We probably need to rewrite all DB spawns for commoners... Or borrow TC's spawns :D

**Comment by Helias** [comment]
I ported the TC spawns at the end

**Comment by ChromieCraftServer** [comment]
is this still an issue?

**Comment by Helias** [comment]
yes, it is https://github.com/chromiecraft/chromiecraft/issues/640

**Comment by Helias** [comment]
I think so, I did not have the time to work on it unfortunately
