### ISSUE TITLE
Goblin Commoner at Midsummer festival 

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#4335]
##### CURRENT BEHAVIOUR:
The NPC 20102 has a wrong modelid probably it is a human during the midsummer festival, it should be a goblin.

![image](https://user-images.githubusercontent.com/519778/105614906-c5e89e00-5dcc-11eb-9e47-ca9585aba799.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
On wowhead classic it does not exists, on wowhead it is a goblin https://www.wowhead.com/npc=20102/goblin-commoner

##### STEPS TO REPRODUCE THE PROBLEM:
1. `.event start 1`
2. `.go cr 93734` OR  `.go cr id 20102`
3. you sill see a human called "Goblin commoner" instead of a goblin

##### AC HASH/COMMIT:
6e682da3870210c02a2110b6eef585339be28fc0

##### OPERATING SYSTEM:
Ubuntu 20.04

##### MODULES:
mod-cfbg

**Comment by BarbzYHOOL** [comment]
i think in all cities, the concept of a "commoner" is to be a (racial) citizen of the city, so imo it should rather be a goblin

same thing in all other cities, orc commoners in orgri etc...

**Comment by Helias** [comment]
related to https://github.com/chromiecraft/chromiecraft/issues/640
