### ISSUE TITLE
[Script] [Npcs] No zeppelin info from Kraxx

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4337]
### CURRENT BEHAVIOUR:
The NPC Kraxx in Undercity has no gossip options to tell the player where the zeppelins currently are.

### EXPECTED BLIZZLIKE BEHAVIOUR:
Kraxx should tell about the current location and progress.

### STEPS TO REPRODUCE THE PROBLEM:
.go cr 32035
talk to Kraxx and notice how there are no gossip options and no information about the zeppelins locations and flight progress.

### EXTRA NOTES:
The issue is known on TC. There might be a [potential fix](https://github.com/TrinityCore/TrinityCore/issues/24354).

Possibly other zeppelin trackers have the same issue.

### AC HASH/COMMIT:
c208a12 from June 3rd 2020
and
79aa560 from Jan 2nd 2021

### OPERATING SYSTEM:
OS:
Ubuntu Server 20.04 for the old one
Windows 10 pro 64bit for the recent

### MODULES:
none for the old one
ElunaLua and Individual xp for the recent

### OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by maluramichael** [comment]
Is there an easy way to find the Texts that would appear? Because then it would be easy to fix.

**Comment by 55Honey** [comment]
@maluramichael The texts are included in the PR from TC.

**Comment by Kitzunu** [comment]
This is an issue with all Zeppelin masters iirc

**Comment by heyitsbench** [comment]
Applies to:
```
Orgrimmar <-> Grom'gol  (The Iron Eagle)
Orgrimmar <-> Undercity (The Thundercaller)
Undercity <-> Grom'gol  (The Purple Princess)
```
zeppelins on Classic. The zeppelin masters for:
```
Orgrimmar <-> Warsong Hold      (The Mighty Wind)
Orgrimmar <-> Thunder Bluff     (The Zephyr)
Undercity <-> Vengeance Landing (Cloudkisser)
```
did not have any gossips of interest.
Kraxx inside the Undercity has gossips for both the Purple Princess and the Thundercaller.
