### ISSUE TITLE
Feature: Allow to only update world

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4344]
**Describe your feature request or suggestion in detail**

Currently you can only assemble and import all base/updates/custom but for some times you only want to update the world database to prevent losing character/auth databases

**Comment by FrancescoBorzi** [comment]
> **Describe your feature request or suggestion in detail**
> 
> Currently you can only assemble and import all base/updates/custom but for some times you only want to update the world database to prevent losing character/auth databases

I don't get your point, you should have daily backups of your chars/auth DBs anyway in a production environment

**Comment by Kitzunu** [comment]
yea sure, but now when I updated after the release with bases it also updates Auth and Characters, and in a non-production environment I won't back up those databases. Therefore I think it would be good to have an option to only update the world database. 

It could also limit some mistakes that can be made

**Comment by Kitzunu** [comment]
@FrancescoBorzi could you check discord quickly, unrelated to this but related to the squash

**Comment by FrancescoBorzi** [comment]
> yea sure, but now when I updated after the release with bases it also updates Auth and Characters, and in a non-production environment I won't back up those databases. Therefore I think it would be good to have an option to only update the world database.
> 
> It could also limit some mistakes that can be made

but you HAVE to update chars and auth as well, or you might have issues. All DBs MUST be in sync with the core version.

**Comment by Kitzunu** [comment]
Sure, but very rearely there are updates to them, so there should be an option. creating new characters everytime I use the updater is very annoying

**Comment by yuanf225** [comment]
So we need an automatic update program, just like TC, we only need to import the base three base DB for the first time, all the subsequent update SQL should have the automatic import update SQL when the core is started

**Comment by FrancescoBorzi** [comment]
> Sure, but very rearely there are updates to them, so there should be an option. creating new characters everytime I use the updater is very annoying

hold on.... whaaat ? there is something wrong with your setup then, because this is NOT the way it's supposed to be.. our DB updater already takes care of importing only the necessary updates (for all DBs).

We can further investigate your issue and help you to solve it, of course you shouldn't recreate chars everytime. But I'm going to close this because updating only one DB wouldn't be something good to do.
