### ISSUE TITLE
Lunar Festival Invitation will not teleport back to capitol cities - Says Requires Greater Moonlight

### ISSUE THREAD

**Issue by LannyE** [azerothcore/azerothcore-wotlk#4348]
While standing inside the Greater moonlight for the capitol city you want to return to and using the Lunar Festival Invitation you get a message saying Requires Greater Moonlight.  None of them work.  Anyone else with this issue? 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After the 10 minute cooldown you should be able to teleport back to your factions capitol city using the Lunar Festival Inivitation while standing inside that Faction's Greater Moonlight circle.  

##### STEPS TO REPRODUCE THE PROBLEM:
1. Use you Lunar Festival Invitation to teleport to Moonglade from a capitol city during the Lunar Festival Event
2.  Wait 10 minutes for the cooldown
3.  Try to use the Lunar festival Invitation while standing inside one of your faction's greater moonlight circle 
4.  See Error saying,  "Requires Greater Moonlight"

##### AC HASH/COMMIT:
AzerothCore rev. 3d60ce8e6e3f+ 2021-01-24 21:21:48 -0500 (master branch) (Win64, Debug) (worldserver-daemon)

##### OPERATING SYSTEM:
Windows 7/10

##### MODULES:
Transmogrification
AHBot
CFBG
OldPVPTitles
Solocraft
SoloDungeonFinder

![image](https://user-images.githubusercontent.com/65646022/105800105-42a58480-5f53-11eb-965e-754f621615e5.png)
![image](https://user-images.githubusercontent.com/65646022/105800161-59e47200-5f53-11eb-943a-414d9c712927.png)

**Comment by Helias** [comment]
Confirmed even in ChromieCraft https://github.com/chromiecraft/chromiecraft/issues/19

**Comment by Helias** [comment]
May these commits can help:
vmangos
https://github.com/cmangos/tbc-db/commit/9e50619a88b17f35799e5af10c20bca462db55d1

TC
https://github.com/TrinityCore/TrinityCore/commit/82f6d482732e621882fa536ee04368034f78e00a

**Comment by Helias** [comment]
fixed! test it if you can
https://github.com/azerothcore/azerothcore-wotlk/pull/4354
