### ISSUE TITLE
[Horde] Box in fatigue zone for quest Trial of the Sea Lion

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4352]
##### SMALL DESCRIPTION:
When you try to find [Half Pendant of Aquatic Endurance](https://classic.wowhead.com/item=15882/half-pendant-of-aquatic-endurance), it should be located at Silverpine Forest (30, 29) near to a bubble area. Bubbles spot is missing and the box is forward, after the fatigue limit.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
A bubble area and a loot box containing the item [Half Pendant of Aquatic Endurance](https://classic.wowhead.com/item=15882/half-pendant-of-aquatic-endurance) [Retail video](https://www.youtube.com/watch?v=ahnJOD3NsUE)
No fatigue, bubble spot near the box with coordinates [30, 30])
![imagen](https://user-images.githubusercontent.com/4155059/105913020-07668c80-600b-11eb-90dc-603efd2e30d2.png)

##### CURRENT BEHAVIOUR:
Fatigue, no bubble spot and box is in coordinates [26, 30])
![imagen](https://user-images.githubusercontent.com/4155059/105912909-e30ab000-600a-11eb-8d54-51b104f2fa85.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a druid and take the quest [Trial of the sea lion](https://classic.wowhead.com/quest=30/trial-of-the-sea-lion)
2. Go to Silverpine Forest, at coordinates [30, 29], near the great sea.
3. No box to be looted, just the under sea.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/9d307c71a6

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
I tested the quest for the Alliance.

For the item Half Pendant of Aquatic Endurance, the object is here

![image](https://user-images.githubusercontent.com/519778/105895546-eeafa400-6015-11eb-9dff-0eb47243e4ce.png)

you can use `.go object 27812` to reach it

For the item Half Pendant of Aquatic Agility the object is here:

![image](https://user-images.githubusercontent.com/519778/105896211-cd9b8300-6016-11eb-859a-82bd31e59626.png)

you can use `.go object 48785` to reach it.

Later near the creature queststarter you have to use the agility item to combine the two quest items and get the final quest item.

So, not confirmed, it works on master :wink:

**Comment by nicoaravena** [comment]
Yes, that is why the problem is just for the horde.

**Comment by Helias** [comment]
Sorry, I see only now the "horde" title.

Here the screenshot and commands for horde.
`.go object 27813`
![image](https://user-images.githubusercontent.com/519778/105896759-85c92b80-6017-11eb-9294-4b243892ba43.png)


.go object 13525
![image](https://user-images.githubusercontent.com/519778/105896874-b27d4300-6017-11eb-9ceb-342414933760.png)

**Comment by nicoaravena** [comment]
The object is there, but the buble spot no, also it is in the fatigue zone, also the box should appear on the coordinates 29, 30.
![imagen](https://user-images.githubusercontent.com/4155059/105897926-97024000-5ff7-11eb-827f-adc921707ff6.png)

The position should be on the image. See this video https://www.youtube.com/watch?v=ahnJOD3NsUE too please.

**Comment by Helias** [comment]
I found the gameobject and completed the quest, are you sure?

**Comment by nicoaravena** [comment]
I found the objecet, the problem is the position is in the fatigue zone, and should be que i'm standing in the picture, also what it is needed is the buble spot to recover oxigen or the player will probably die. also as a normal player you can't reach the item and go back without being damaged by the run out of the fatigue.

**Comment by nicoaravena** [comment]
#### Actual behavior:
Fatigue, no bubble spot and box is in coordinates [26, 30])
![imagen](https://user-images.githubusercontent.com/4155059/105912909-e30ab000-600a-11eb-8d54-51b104f2fa85.png)

#### Expected blizzard behavior:
No fatigue, bubble spot near the box with coordinates [30, 30])
![imagen](https://user-images.githubusercontent.com/4155059/105913020-07668c80-600b-11eb-90dc-603efd2e30d2.png)

**Comment by nicoaravena** [comment]
@Helias just updated all the issue to improve the issue quality.

**Comment by Helias** [comment]
Ok :+1:

**Comment by BarbzYHOOL** [comment]
are you sure fatigue is not intended? it's reachable even with fatigue if i recall
logically it should not be in the fatigue zone though, as it's confusing for low level characters

**Comment by Kitzunu** [comment]
Youtube :D
