### ISSUE TITLE
DB/Creature: Enchanted Elemental trying to delete its updating MG

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#4357]
To reproduce the issue  `Unit (Entry 21958) is trying to delete its updating MG (Type 14)!`:

- `.go cr 93814`
- `damage 300000` multiple times until she summons enchained elementals
- when the elementals suicide on lady vashj, the console error occurs

@francescoborzi @Hacaw 

Do you have it?

_Originally posted by @BarbzYHOOL in https://github.com/azerothcore/azerothcore-wotlk/issues/2536#issuecomment-768451200_

**Comment by Kitzunu** [comment]
Thanks! Gonna check it asap

**Comment by Kitzunu** [comment]
Yea I can confirm this on 6ecaca2d95e7

**Comment by BarbzYHOOL** [comment]
the issue had been reported 3 times with different creature_template, so once we find how to fix it here, we can verify the others closed incomplete issues

**Comment by Kitzunu** [comment]
Yea, now we at least have a clean report :)

**Comment by BarbzYHOOL** [comment]
For that general issue, the most reported one was NPC https://webdb.fusion-host.eu/?npc=36551
If you read the smart_scripts it despawns after 4sec, so seems like the issue is when a NPC deletes itself (maybe only if it deletes itself with smart_scripts actions)

Maybe the issue is global

**Comment by elthehablo** [comment]
This should be fixed afaik. Especially now that I put her in script https://github.com/azerothcore/azerothcore-wotlk/pull/18276
