### ISSUE TITLE
Feature: Core/Creature: Implement creature_template_movement (c_t_m) & creature_movement_override (c_m_o)

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#4361]
**Describe your feature request or suggestion in detail**

Cherry-pick from TC to move inhabittype to c_t_m and c_m_o

**Describe a possible solution to your Feature or Suggestion in detail**

This is the commit that introduces it. However it does also require a lot of other work for example implementing void Creature::UpdateMovementFlags() amongst other stuff https://github.com/TrinityCore/TrinityCore/commit/592516ae69d89da3bcb0ede144644a3d2e0186e0 & https://github.com/TrinityCore/TrinityCore/commit/a22bc236ebc038c723774e5b38cd93e814ccc43d & https://github.com/TrinityCore/TrinityCore/commit/e78465ccb4abefba1131f1490db2ea7c2944ed7c

**Comment by acidmanifesto** [comment]
we need to find the tc commit referencing the chase and random, seems to be a missing commit between  TrinityCore/TrinityCore@592516a & TrinityCore/TrinityCore@a22bc2. pretty much we are mising step 2 and i am having a issue locating it via git blame.

**Comment by acidmanifesto** [comment]
https://github.com/TrinityCore/TrinityCore/commit/dbadb6369cf0b6d394fffaa1dedc612dfb5cbe2a
https://github.com/TrinityCore/TrinityCore/commit/34cfa69efd1857540f1f44b118086bb02334c100
