### ISSUE TITLE
Core/Gameobject: Range check from caster

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4370]
### CURRENT BEHAVIOUR:
When using [Acherus Shackle Key](https://wotlkdb.com/?item=40732#unlocks-object) on Acherus Soul Prison during the quest The Endless Hunger during the initial stage of the DK quests, there is no range check.
![WoWScrnShot_012921_095744](https://user-images.githubusercontent.com/71938210/106254566-263a6e00-6219-11eb-82d8-5aab0de00f0e.jpg)
Just right clicking the Soul Prison without the key wielded checks for range.

The same applies for Titanium Skeleton Key when trying to open a locked door.
![WoWScrnShot_012921_123706](https://user-images.githubusercontent.com/71938210/106270916-f8f8ba80-622e-11eb-8a9b-5421548c985a.jpg)

It seems there is a range check missing in general for keys.

### EXPECTED BLIZZLIKE BEHAVIOUR:
There should be a range check.

### STEPS TO REPRODUCE THE PROBLEM:
- Create a DK, finish the initial sword engraving quest.
- Accept The Endless Hunger
- Right click the [Acherus Shackle Key](https://wotlkdb.com/?item=40732#unlocks-object) in your inventory then click the Soul Prison at high range.

### AC HASH/COMMIT:
879468506f8e 2021-01-25 20:50:53 +0100

### OPERATING SYSTEM:
OS:
Windows 10 pro 64

### MODULES:
none

### OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by Kitzunu** [comment]
Should be melee range... I will look at this during lunch

**Comment by Kitzunu** [comment]
I can confirm this, the spell has the correct range yet you can still use it... I don't know how to fix this.
But whoever tries, I can assure you 
```cpp
    ApplySpellFix({
        54669   // Unlocking Soul Prison
        }, [](SpellEntry* spellInfo)
    {
        spellInfo->rangeIndex = 2; // Melee Range
    });
```
Does not work

**Comment by 55Honey** [comment]
See edits. It seems there is a range check missing in general for keys.

**Comment by Kitzunu** [comment]
I think I have found a solution

**Comment by Viste** [comment]
It's because of that fix I told you about, but you didn't listen to me. All in all, it's nothing new.

**Comment by Kitzunu** [comment]
https://github.com/TrinityCore/TrinityCore/commit/76cc94f325ab68f66a4fa7b5d30316508e27c0ce
https://github.com/TrinityCore/TrinityCore/commit/32e1de39a26628dcb64bc21ad415afb2ad938925
https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7
https://github.com/TrinityCore/TrinityCore/commit/f01e53f3f3a8bf77859b4956da56a91809607dfb

**Comment by Helias** [comment]
may this can help https://github.com/azerothcore/azerothcore-wotlk/pull/3384/
could you check this bug with this PR

**Comment by lineagedr** [comment]
After
https://github.com/TrinityCore/TrinityCore/commit/32e1de39a26628dcb64bc21ad415afb2ad938925
https://github.com/TrinityCore/TrinityCore/commit/78070163dc6b9bb34ab2d006e9cc218548e861b7
https://github.com/TrinityCore/TrinityCore/commit/f01e53f3f3a8bf77859b4956da56a91809607dfb


https://user-images.githubusercontent.com/12139798/106302597-d8962380-6261-11eb-8557-691667161084.mp4

**Comment by Kitzunu** [comment]
Could you pr it?

**Comment by lineagedr** [comment]
@Kitzunu nah my copy of AC was downloaded manually not through git

**Comment by 55Honey** [comment]
I tried adding these commits to a fork of the latest master but it's beyond my skills.
Can you provide the changed files based on a recent master branch @lineagedr ?
