### ISSUE TITLE
Feature: recruit-a-friend (RAF) config to prevent same IP abuse

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#4375]
How to abuse the current unrestricted system? Players can make multiple accounts and use them to increase their XP gain, grant free levels to lower characters and can also place some characters in specific places to teleport to with the special teleport spell (example: to bypass the scarlet monastery locked door lol, or hellfire citadel)

**Describe a possible solution to your Feature or Suggestion in detail**

A new config option for the RAF system that allows to set a number defining if your recruited friends accounts can be running on the same IP as you, and how many of them are allowed. Typically, you'd want to set this to 1, 2 or 3 to prevent players from abusing it.

`RecruitAFriend.MaxSameIP = 3`

**Additional context**

No need for dynamic IP check in this case, it will already be enough imo

**Comment by Tr1v1an** [comment]
This issue has been resolved, it's currently no longer possible to use RAF for more than 1 character on the same IP.
