### ISSUE TITLE
why i cant use modules to build server?

### ISSUE THREAD

**Issue by Remberance** [azerothcore/azerothcore-wotlk#4377]
##### CURRENT BEHAVIOUR:
use modules to build, successed.
but when i start worldserver.exe, restart!!!

without modules, OK

##### EXPECTED BLIZZLIKE BEHAVIOUR:
no BLIZZLIKE BEHAVIOUR

##### STEPS TO REPRODUCE THE PROBLEM:
1.  use some modules to build, successed.
2.  start authserver, worldserver.exe crashed!
3. move modules, cmake, rebuild
4. restart OK.

##### EXTRA NOTES:
no

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/dce3c9f8cb28aa5225afcef949cc81127caa578e

##### OPERATING SYSTEM:
WIN 10 64bit

##### MODULES:

![image](https://user-images.githubusercontent.com/4078506/106340276-2fd4dc00-62d4-11eb-80d7-e9a3ab5c356e.png)

**Comment by Kitzunu** [comment]
What does the Worldserver tell you?

**Comment by Remberance** [comment]
when display 'installing C++ scripts', crashed.

**Comment by Kitzunu** [comment]
Show me the file or we eill never know

**Comment by BarbzYHOOL** [comment]
show the error

**Comment by dunjeon** [comment]
I wonder if he placed Eluna in the LuaEngine directory of the module...

**Comment by Remberance** [comment]
in logs/server:
2021-01-31 08:26:18 
2021-01-31 08:26:18 Initializing Scripts...
2021-01-31 08:26:18 Loading C++ scripts
2021-01-31 08:26:18 Initialize Eluna Lua Engine...
2021-01-31 08:26:18 [Eluna]: Searching scripts from `lua_scripts`

in Crashes
[540aaabca805_worldserver.exe_[31-1_8-26-18].txt](https://github.com/azerothcore/azerothcore-wotlk/files/5899005/540aaabca805_worldserver.exe_.31-1_8-26-18.txt)
![image](https://user-images.githubusercontent.com/4078506/106371339-4c3d4b00-639e-11eb-8773-075f27d5b0c5.png)

**Comment by Kitzunu** [comment]
well the crashlog is useless because you have built in `Release`

As for anything else, I am not module expert. But try redownloading Eluna and LuaEngine, maybe something got missplaced along the way :shrug:

**Comment by Remberance** [comment]
> well the crashlog is useless because you have built in `Release`
> 
> As for anything else, I am not module expert. But try redownloading Eluna and LuaEngine, maybe something got missplaced along the way 🤷

OK, i will built it in Debug later.

and i built it without Eluna mod, failed also.

**Comment by Kitzunu** [comment]
check the file "WorldServer.txt" what does it say when you built without ELuna?
