### ISSUE TITLE
Cannot get WotLK client to try and connect to localhost

### ISSUE THREAD

**Issue by btaylor-ihr** [azerothcore/azerothcore-wotlk#439]
After digging around the db and google, I figured out that you can sign in with test1:a...

---

Updated

I have a 3.3.5 client downlaoded from another website. It appears that realmlist.wtf isn't used in this build, so I can't get it to try to connect to localhost.

---

Old post

- The first time I do this, I immediately get disconnected.
- I log in again, I get to pick the realm type, but then get disconnected when I try to continue. 
- I log in a third time, and I get presented with a list of servers, but "Azeroth Core 3.3.5" is offline.

There's nothing really of interest in the worldserver terminal, other than `Creature (GUID: 6432 Entry: 3197) has wrong spell 0 defined in `auras` field.`

**Comment by Erotes** [comment]
Please post the text document named "DBErrors" and if you have any addons installed, compile a list of them and post it here.

**Comment by falzard** [comment]
It looks like a misconfiguration of your DB. Maybe related to the table realmlist from the auth database

**Comment by btaylor-ihr** [comment]
![image](https://cloud.githubusercontent.com/assets/13723023/24228947/d2057c1e-0fc2-11e7-8c34-945cd1b9396d.png)

I don't know much about the info stored in here. The addresses are what I'm connecting to. I don't know about the port or game build

**Comment by btaylor-ihr** [comment]
@Erotes I was listing the addons I had in my interface folder when I realised I had pointed a TBC client at my server :/ Of course that wasn't going to work. I do have a 3.3.5 client on hand, but it appears that the realmlist.wtf file isn't used. So I cannot currently get it to try and connect to me. I'll see if I need to play with the hosts file

**Comment by btaylor-ihr** [comment]
Ah, I had to move it into enUS. Awesome. I'm in!
