### ISSUE TITLE
Gathering Quest While in Party bug

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#4399]
### SMALL DESCRIPTION:
When in a party with a quest with drops shows it is lootable (see picture below) even if the corpse has nothing.

### EXPECTED BLIZZLIKE BEHAVIOUR:
Once the corpse is looted it should no longer be interactable and the cursor should be a gauntlet instead of bag.

### CURRENT BEHAVIOUR:
The body has no sparkles but you can "loot" it which does nothing and hovering over it shows a bag instead of a gauntlet. When you loot it in this state you bend over to pick something up but nothing happens and no loot window appears.

![105868962-5933f600-5fbc-11eb-8df6-c103aaefeb15](https://user-images.githubusercontent.com/2810187/106400220-e5e71580-63fb-11eb-804d-a244294e7af1.png)

### STEPS TO REPRODUCE THE PROBLEM:
I had my wife who was playing with me confirm the issue existed on her end. She is not using a UI mod. I did two quests in the BE starting area that had quest drops and they worked like above. I created a new character and the same thing happened. Seems to only happen while in a party.

### AC HASH/COMMIT:
- chromiecraft/azerothcore-wotlk@df600f9

### OPERATING SYSTEM:
- Ubuntu 20.04

### MODULES:
1. mod-cfbg
2. mod-duel-reset

### OTHER CUSTOMIZATIONS:
- None.

### SERVER:
- ChromieCraft

**Comment by pangolp** [comment]
The original report can be found here:
https://github.com/chromiecraft/chromiecraft/issues/20

**Comment by lineagedr** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a49544cc187d3a156b4615907d6b82057364fcc4

**Comment by pangolp** [comment]
Excellent contribution @lineagedr. I will see if I can replicate the arrangement.

**Comment by pangolp** [comment]
I am currently compiling, testing the changes, and creating the pull request.

**Comment by pangolp** [comment]
It works like a charm. Only 1 of the 2 can get the item, and the bag disappears.
![WoWScrnShot_020121_120224](https://user-images.githubusercontent.com/2810187/106476130-7b7ab780-6485-11eb-9d30-31b197c7ec59.jpg)

**Comment by pangolp** [comment]
@lineagedr thanks again for the information.
