### ISSUE TITLE
[CONF] CD reset does not work

### ISSUE THREAD

**Issue by Devalenok** [azerothcore/azerothcore-wotlk#440]
**Description**:If you change the value to Rate.InstanceResetTime = 0.01
KD reset remains the same 6 days.
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Open worldserver.conf
2. We replace: Rate.InstanceResetTime = 0.01
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
Debian 8
**Modules**:  Are you using modules? if yes, list them
no
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Viste** [comment]
No float here i guess works fine with int

**Comment by Viste** [comment]
Done must work, but minimum time is 1 day if you want hours need change code.
Теперь будет работать, но минимально все равно будет 1 день, если хочешь несколько часов, то напиши мне в скайп(visteevans) или в дискорд(зайдя на канал азерота найдешь меня) я скажу тебе что на что поменять.

**Comment by Devalenok** [comment]
Спасибо большое за помощь !
