### ISSUE TITLE
Storm Peaks Quest Chain: 'A Spark of Hope' should not require 'Mending Fences' to be turned in

### ISSUE THREAD

**Issue by steenburgh** [azerothcore/azerothcore-wotlk#4402]
##### CURRENT BEHAVIOUR:
When the player completes the quest: ['The Refiner's Fire'](https://wotlkdb.com/?quest=12922), they are not able to pick up the follow-up quest, ['A Spark of Hope'](https://wotlkdb.com/?quest=12956). *Edit: Unless they have also completed the quest: ['Mending Fences'](https://wotlkdb.com/?quest=12915), which the player will usually not have turned in yet if they complete the quest line as blizzard intended.* This bug breaks a huge Storm Peaks quest chain as 'A Spark of Hope' is a prerequisite for a pretty big quest chain: https://wotlkdb.com/?quest=12924

This is the anvil in question:
![image](https://user-images.githubusercontent.com/9411156/106403868-39566500-63f6-11eb-81c3-c9af2000c8a4.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The player should be able to pick up 'A Spark of Hope' after completing 'The Refiner's Fire', regardless of whether or not they have completed 'Mending Fences'. See [this video at 7:20 for proof](https://www.youtube.com/watch?v=CnTDHjrrpCc&t=7m20s)

Here's the sequence a normal player would follow on this questline, as shown in [this YouTube video](https://www.youtube.com/watch?v=CnTDHjrrpCc).
1. Receive 'Mending Fences' from Thorim. Travel to the area where the mobs you have to kill are
2. While killing these mobs, notice that an item has dropped that starts 'The Refiner's Fire'. Since the mobs you have to kill for 'The Refiner's Fire' are in the same area, complete this quest while you're over there.
3. The anvil you have to use to complete 'The Refiner's Fire' is guarded by Fjorn, who you have to kill for 'Mending Fences'. Kill Fjorn to complete mending fences
4. Once you've killed Fjorn, complete 'The Refiner's Fire' at Fjorn's Anvil. 
5. The anvil will give you a new quest: 'A Spark of Hope
6. Return to Thorim and turn in both 'A Spark of Hope' and 'Mending Fences'. 'A Spark of Hope' opens a new quest chain.

##### STEPS TO REPRODUCE THE PROBLEM:
1. `.character level 77` - Make sure you fix the requirements for the quest
2. `.additem 41556` - Start the quest from the item you just added
3. `.additem 41558 10` - This should complete the quest
4. `.go zonexy 77.234 62.731 67` and complete the quest
    * You may want to turn on .cheat god so you don't get killed by the mobs in the area

*Expected:* The anvil gives you the next quest in the series, 'A Spark of Hope' from the anvil.
*Actual:* No follow-up quest is available.

##### EXTRA NOTES:
~~I believe this issue occurs because the quest: 'A Spark of Hope' (ID: 12956) has no next or previous quest ID in the DB. I set its previous quest ID to 'The Refiner's Fire' (ID: 12922) and was able to continue the quest chain successfully. I will probably create a PR for this, but I still need to take the time to figure out how to make DB changes to AC as I've never done that before.~~

My initial assumption was incorrect. It turns out the problem was that there's an entry in the in the `conditions` table that says that 'Mending Fences' must be completed before 'A Spark of Hope' becomes available:
![image](https://user-images.githubusercontent.com/9411156/106406264-5a22b880-63fe-11eb-9ff6-580c3e0da49f.png)
According to the [docs for the conditions table](https://www.azerothcore.org/wiki/conditions), this means that... 
Line 1 says: 'CONDITION_SOURCE_TYPE_QUEST_AVAILABLE 12956 REQUIRES_QUEST_REWARDED 12915 ('Mending Fences')'
Line 2 says: 'CONDITION_SOURCE_TYPE_QUEST_AVAILABLE 12956 REQUIRES_QUEST_REWARDED 12922 ('The Refiner's Fire')'

I tried removing line 1 and this fixed the issue for me.

##### AC HASH/COMMIT:
2e6f78bdddbc84a1950aaec0865a689efa9fcde4

##### OPERATING SYSTEM:
Windows 10.0.19041

##### MODULES:
* mod-ah-bot (custom build from https://github.com/steenburgh/mod-ah-bot/pull/1)
* mod-autobalance
* mod-individual-xp

##### OTHER CUSTOMIZATIONS:
None

**Comment by Kitzunu** [comment]
Looks good to me

**Comment by Kitzunu** [comment]
Run the script from data/sql/uodates/pending_world/ bash script.

Path is something like that, edit the SQL and PR it :)

**Comment by steenburgh** [comment]
I just tested my fix on a fresh character and it did not seem to work. I'm not really sure why - perhaps there's another hidden prerequisite for this quest that the character I was leveling needed?

**Comment by steenburgh** [comment]
Looks like there's a second prerequisite in the DB, this quest: https://wotlkdb.com/?quest=12915, which kind of makes sense. Gotta do some more research on this. Perhaps this is a blizzard annoyance and not a bug at all.

**Comment by steenburgh** [comment]
After some digging, I found a video of someone turning in 'The Refiner's Fire' before 'Mending Fences' https://www.youtube.com/watch?v=CnTDHjrrpCc&t=7m20s, so this is definitely a bug on our end. However, I believe the fix is going to be a bit different than I'd initially thought.

**Comment by steenburgh** [comment]
Ok, so I found the quest ID referenced in another place: The `conditions` table. It turns out the quest will not appear unless you've completed both 'Mending Fences' *and* 'The Refiner's Fire'. The fix will be modifying the 'conditions' table instead. As a side question, do you know why the conditions table was used instead of `quest_template_addon`? Is using `conditions` the preferred method of defining quest dependencies?

![image](https://user-images.githubusercontent.com/9411156/106406264-5a22b880-63fe-11eb-9ff6-580c3e0da49f.png)
According to the [docs for the conditions table](https://www.azerothcore.org/wiki/conditions), this means that... 
Line 1 says: 'CONDITION_SOURCE_TYPE_QUEST_AVAILABLE 12956 REQUIRES_QUEST_REWARDED 12915 ('Mending Fences')'
Line 2 says: 'CONDITION_SOURCE_TYPE_QUEST_AVAILABLE 12956 REQUIRES_QUEST_REWARDED 12922 ('The Refiner's Fire')'

**Comment by Kitzunu** [comment]
Because some things are not possible to donin q_t_a

Anyhow, a tip. Try to find a quest map for the entire chain on Wowhead comments.
Usually, well sometimes, there have been users there that have made an entire map with prerequisites and breadcrumbs

**Comment by Kitzunu** [comment]
Btw ElseGroup there is the same for both, which indicates AND

**Comment by steenburgh** [comment]
> Because some things are not possible to donin q_t_a

Fair enough.

> Anyhow, a tip. Try to find a quest map for the entire chain on Wowhead comments.

I did try that actually - but I didn't spot anything in there indicating that there was a prerequisite

> Btw ElseGroup there is the same for both, which indicates AND

Right, that makes sense.

**Comment by Kitzunu** [comment]
This is the Hodir quest chain right?

I had a friend research the entire chain to piece it together correctly. I can see if I find the map later and we can look at it

**Comment by steenburgh** [comment]
I removed the entry from the conditions table, restarted my server, and the quest still does not appear for my character 🤔

**Comment by steenburgh** [comment]
> I had a friend research the entire chain to piece it together correctly. I can see if I find the map later and we can look at it

I did see a closed issue mentioning this same quest - was it this one? https://github.com/azerothcore/azerothcore-wotlk/issues/4402

**Comment by Kitzunu** [comment]
No.

I didnt find the tree, but I found something... I will do some digging with it later during the day and see if I can make sense of this questline

**Comment by Kitzunu** [comment]
N [80] Sibling Rivalry
N [80] Mending Fences (+28,600 The Sons of Hodir)
Note: The chain continues from a dropped item: Slag Covered Metal (dropped by Stormforged Iron Giants). You should complete this quest before returning to Thorim.
N [80] The Refiner's Fire
N [80] A Spark of Hope (+28,600 The Sons of Hodir)

**Comment by steenburgh** [comment]
Sounds like that confirms what the YouTube video I linked said. Now I just have to figure out why removing the condition from the conditions table doesn't seem to be having an effect. I reached out in the #dev-database channel to see if someone has any ideas. Perhaps there's another table in the DB somewhere that I need to modify as well.

**Comment by steenburgh** [comment]
Ok, turns out I removed the condition for the "The Refiner's Fire" quest instead of the condition requiring the "Mending Fences" quest. Fixed that and everything works now. I'll get a PR up later tonight.
