### ISSUE TITLE
Quest 'Alas, Andorhal' is a group quest but not group friendly

### ISSUE THREAD

**Issue by Zoidwaffle** [azerothcore/azerothcore-wotlk#4403]
##### CURRENT BEHAVIOUR:

Link to the quest: https://classic.wowhead.com/quest=211/alas-andorhal (Alliance)
And also https://classic.wowhead.com/quest=105/alas-andorhal (Horde)

This is a group/elite quest where players need to kill Araj the Summoner - he drops a chest-like "Araj's Phylactery" that contains a shard you need for the quest.

However, it will despawn once looted by a single player.

This makes it a huge pain to do as you need to wait quite some time for a respawn.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The phylactery should be lootable by all on the quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c id 1852
2. .quest add 105 (Horde - or 211 for Alliance)
3. /tar araj
4. .die
5. Loot the phylactery... it despawns right after looting and it shouldn't.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/tree/1774a322c8f54ee5a59a8dfb2cf4fd8a00c3b55d

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

mod-account-achievements
mod-ah-bot
mod-arac
mod-autobalance
mod-congrats-on-level
mod-morph-all-players
mod-morphsummon
mod-npc-buffer
mod-transmog
mod-weapon-visual

**Comment by Zoidwaffle** [comment]
... and I see it's the same issue for https://classic.wowhead.com/quest=5803/arajs-scarab as well... But whatever can fix the first issue here, can probably trivially fix this one as well.

**Comment by Helias** [comment]
I don't remember if Keira3 provides any field to specific that the quest item need to be shared between players, but I think so, check Keira3 and explore the quest and the item, may it's easy to figure out how to fix.
I suggest to compare a generic quest item and quest that works as you expect and compare it with this

**Comment by Zoidwaffle** [comment]
What makes this special is the thing that you don't kill some NPC and then loot... You kill the NPC that spawns a chest that you then loot.

So the chest is lootable by all and you get the 1 or 2 items you need (depending if you have 1 or 2 quests), but then the chest despawns so no others can finish their quests. I have poked around in the DB with and without Keira3, but I haven't found a way to fix it yet.

**Comment by Kitzunu** [comment]
Fixed

**Comment by Zoidwaffle** [comment]
The fix mentioned above, didn't work. Unfortunately. So a bit more info:

The chest is spawned by a script upon the death of Araj:

```
> SELECT * FROM `smart_scripts` WHERE `entryorguid`=1852 AND `id`=3\G
*************************** 1. row ***************************
     entryorguid: 1852
              id: 3
      event_type: 6
    event_chance: 100
     event_flags: 1
     action_type: 11
   action_param1: 18661
   action_param2: 7
     target_type: 1
         comment: Araj the Summoner - On Just Died - Cast 'Araj's Phylactery' (No Repeat)
```

The item inside the chest can be looted by anyone on the quest - but it will despawn after the first person loots the chest, making it impossible for the others.

So the spell https://www.wowhead.com/spell=18661/arajs-phylactery is the one - it's said to last for 5 minutes... Which seems perfectly fine, except the chest should remain for the full duration  no matter how many times it's looted (as long as it's only looted by anyone credited with the kill that is).

**Comment by Zoidwaffle** [comment]
OK, so recompiling... I will test if it solved the issue(s) afterwards...

**Comment by Zoidwaffle** [comment]
So before looting, there are stars and whatnot:

![Screenshot from 2021-02-01 23-19-39](https://user-images.githubusercontent.com/541438/106525303-11452f80-64e4-11eb-9997-01ffe4c06342.png)

And once looted:
![Screenshot from 2021-02-01 23-19-27](https://user-images.githubusercontent.com/541438/106525386-3174ee80-64e4-11eb-8252-613ff8a69bf1.png)

All the stars are gone and the phylactery remains.

Furthermore, you cannot loot this if you pass by as a different person.

I will test with a full group tomorrow - and if all is good, make a PR.
