### ISSUE TITLE
Shaman/Druid form appearance model infinite stuck bug [$15]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4410]
Shaman/Druid form appearance model infinite stuck bug

##### CURRENT BEHAVIOUR:

Currently if you enter a battleground or RDF dungeon whilst in a Druid or Shaman form (e.g bear form/spirit wolf) you will retain the model of the form. This means you can attack, cast spells, and move as a "Travel Form" druid model whilst your character is not actually in travel form causing confusion for players on the opposing faction.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As soon as you join a RDF/BG your form should be reset to yourself.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Queue BG or RDF
2. Be a shaman or druid in a model changing form
3. Click accept and observe

##### AC HASH/COMMIT:

Chromiecraft latest. 

rev. b905ce8c354b 2021-01-2

**Comment by FrancescoBorzi** [comment]
@JamesGent just a side note:

when reporting bugs found on ChromieCraft, you can just copy the following:

https://raw.githubusercontent.com/chromiecraft/chromiecraft/main/issue_template.md

so the template will be ready for you (rev, OS, modules, etc..)

**Comment by Kitzunu** [comment]
I cannot reproduce this.

Works as intended, if you enter as ghostwolf, it is removed once you get in.
Same for travel form.
And for bear-form you leave the form if you cast anything not bear related

**Comment by JamesGent** [comment]
https://cdn.discordapp.com/attachments/788063060430290948/814286879910133790/unknown.png

Ender has found ou

**Comment by Kitzunu** [comment]
And how do I do that?

**Comment by UltraNix** [comment]
Any info here how to reproduce it?

**Comment by bronzato** [comment]
some update in azerothcore fixed this, i cant reproduce it.

**Comment by UltraNix** [comment]
No confirmation - closed.
