### ISSUE TITLE
WorldServer Startup: Validate Spell Script 22539 Error

### ISSUE THREAD

**Issue by LannyE** [azerothcore/azerothcore-wotlk#4412]
##### CURRENT BEHAVIOUR:

I updated my core to 3.0 (merged database updates)  and then to AzerothCore rev. 0d52b4ca4a7e+ 2021-02-01 18:57:25 +0100 (master branch) and merged its database updates.
On worldserver startup the console window now shows this error under the "Validating spell scripts..." section:
```
ERROR: TSCR: Spell `22539` Effect `Index: EFFECT_0 Name: 77` of script `spell_bwl_shadowflame` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
```

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All spellscripts should pass validation on server startup.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Apply at least commit AzerothCore rev. 0d52b4c+ 2021-02-01 18:57:25 +0100 (master branch) and its database updates to your core. 
2. Startup worldserver
3. Look in section "Validating spell scripts..." for this error.  

##### EXTRA NOTES:
 May be related to #3673.  This was the BWL overhaul.  

##### AC HASH/COMMIT:
AzerothCore rev. 0d52b4c+ 2021-02-01 18:57:25 +0100 (master branch) 

##### MODULES:

Solocraft
SoloLFG
AHbot
CFBG
Transmog
OldPVPTitles

**Comment by locus313** [comment]
confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/0d52b4ca4a7ec2d8219c606b581f874186f171f9

**Comment by Kitzunu** [comment]
This should have failed on CI imo

**Comment by locus313** [comment]
> This should have failed on CI imo

already working on an improvement for this

**Comment by Kitzunu** [comment]
I have fixed the actual issue, but I am assuming you're talking about CI

**Comment by locus313** [comment]
> I have fixed the actual issue, but I am assuming you're talking about CI

yep for the ci :)
