### ISSUE TITLE
Module strange thing 

### ISSUE THREAD

**Issue by Viste** [azerothcore/azerothcore-wotlk#442]
**Description**:
I want to use random.h from modules\worldengine\deps\g3dlite\include\G3D  but it say  go away no file exist
**Current behaviour**: in custom module i want use #include "Random.h" but it fuck me in ass and say no exist random.h 

**Expected behaviour**: i can use #include "Random.h" in module or custom script

**Steps to reproduce the problem**:

1.  include header to you custom script or custom module and get a pain in the ass

**Branch(es)**: master
**AC hash/commit**:  last  b32a9b2

**Operating system**:  Debian 8

**Modules**:  yes custom for arenaannounce and want create event and need include random.h but it fuck me in ass 

**Other Customizations**: pussywizard transmog script in npc_special

**Comment by Yehonal** [comment]
you should use include_directories in your cmake

**Comment by Yehonal** [comment]
then, remember to include g3dlib in your target_link_libraries

**Comment by falzard** [comment]
> but is fuck me in ass 

:rofl:

**Comment by Viste** [comment]
@Yehonal so in modules\mod-customsmodulename\ CMakeLists.txt i need add include of g3ddlib?

**Comment by Yehonal** [comment]
yes but it depends how you're developing it. I've no idea. You can even try to put the full relative path

**Comment by Viste** [comment]
thanks very big
