### ISSUE TITLE
WorldServer Freeze

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#443]
**Description**: WorldServer Freeze
**Current behaviour**: same time worldserver freeze and characters login stay on connecting show realm but cant join into character list. when i check server.log see this line of error : 

ERROR : WorldSocket::HandleAuthSession: Authentication failed for account : example Address : xxxxxx

who can help? tnx
**Branch(es)**: master

**AC hash/commit**:  latest AC

**Operating system**:  se7en 64 bit

**Modules**:  Are you using modules? anticheat - transmog

**Other Customizations**: No!

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Viste** [comment]
not confrim try to disable anticheat and transmog module if need i can share my transmog without custom scritps and module using

**Comment by Viste** [comment]
and another one try without anticheat first then with anticheat without transmog and then without both

**Comment by Franklampardst** [comment]
okay i close it . fixed by update source
