### ISSUE TITLE
[raid]Archimonde Can't be killed

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4436]
##### CURRENT BEHAVIOUR:
Archimonde health reduced to 10% will enter the plot, and then the elf will go over and explode, Archimonde health reduced to 7%, out of combat. Archimonde health restored

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Archimonde health reduced to 10% will enter the plot, and then the elf will go and explode until Archimonde dies

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67
2. .go c 39927
3. Attack Archimonde health to 10%
4. Then watch the story

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

**Comment by betayi** [comment]
nice job, and does this #4193 a problem repeatable yet?
