### ISSUE TITLE
The wrong movement in the water

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4441]
##### CURRENT BEHAVIOUR:
The monster kept moving up and down in the water

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should be close to the target. Unless the target is moving up and down, the monster will not move

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67
2.Attack a monster in the water and watch it move

##### EXTRA NOTES:
I think this commit caused the bug
https://github.com/azerothcore/azerothcore-wotlk/commit/c8f43d85849c40e08d0da38913489426a0c35388

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

https://user-images.githubusercontent.com/18187177/106883557-193ae480-671b-11eb-8f90-69001e0f75d4.mp4

**Comment by Kitzunu** [comment]
@Yehonal
