### ISSUE TITLE
Crash worldserver

### ISSUE THREAD

**Issue by espargon** [azerothcore/azerothcore-wotlk#4446]
Hi, I'm trying to launch the latest Azeroth Core revision in Windows 10 64-bit but when I get to the point 2021-02-04 23:38:40 Loading Quest Pooling Data ... Crashea, can someone help me?

**Comment by Kitzunu** [comment]
1. Never copy paste into an issue. Use Gist or PasteBin
2. A crashlog in Release will be of no use as it gives no info. Build in RelWithDebInfo
3. Are you able to reproduce this issue?

Btw if it crashes in Worldserver startup it is 90% of the time due to that your database is Out-Of-Date...

**Comment by FrancescoBorzi** [comment]
also please read: https://www.azerothcore.org/wiki/How-to-ask-for-help

open a question including all your error log
