### ISSUE TITLE
[creatureAI]'Dragonmaw Transporter' wrong movement

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4447]
##### CURRENT BEHAVIOUR:
'Dragonmaw Transporter' wrong movement
https://youtu.be/QhnPDHe7_8Y
##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should fly away

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67
2..go -4334 213 180 530

##### EXTRA NOTES:
I think this commit caused the bug
https://github.com/azerothcore/azerothcore-wotlk/commit/c8f43d85849c40e08d0da38913489426a0c35388

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

**Comment by Footman** [comment]
I dont have this issue after latest pull requests
