### ISSUE TITLE
[SQL] Several mailboxes spawned upon each other

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#445]
**Description**:

**Current behaviour**: Seems like there are 4 mailboxes on top of each other

**Expected behaviour**: Only one mailbox? I'm not sure, I don't know if it's in an instance or part of a quest or a phase

**Steps to reproduce the problem**:

1. .go object 66358
2. .gob near
3. see, there are many mailboxes

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  c92d0403a7047414fcb5901f08da7dd652ca382c

**Comment by talamortis** [comment]
in what zone is the mailboxes in as like you said, could be zoned.

**Comment by starrheld** [comment]
DK starting area, could just be layered

**Comment by falzard** [comment]
It's havenshire. If you put your gm mode off, you can click on one mailbox, but if you put it on, you can click on two mailboxes on top of each other.

Well, sorry if it's not a valid issue, I don't know, I just reported it.

**Comment by ghost1988** [comment]
Dk zone, with gm of it's only one box. It's not a bug

**Comment by falzard** [comment]
if you type .gob near there are 4 mailboxes...
seems like it's badly done

**Comment by starrheld** [comment]
However, when you remove one gob, you can see that it's layered. There's one mailbox gob that looks awful.
