### ISSUE TITLE
[raid]'Illidan Stormrage' can't be killed

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4455]
##### CURRENT BEHAVIOUR:
Illidan Stormrage will be out of combat when its health value is only 300000

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Illidan Stormrage at P4 turn phase in the shadow cage out, and then fight with the players

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67
2. killed all the 'Black Temple ' boss
3. .go c 52484
3. Talk to Akama and fight
4. Illidan Stormrage Enter P4 stage

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

It should be the same bug:
https://github.com/azerothcore/azerothcore-wotlk/issues/4436

**Comment by hahalmtdhl** [comment]
@mpfans Has the problem been solved? I still can't work properly

**Comment by frizar** [comment]
not fixed
