### ISSUE TITLE
Level 1-2 Duskbats in Deathknell are skinnable

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4457]
##### SMALL DESCRIPTION:
Level 1-2 [Duskbats](https://www.wowhead.com/npc=1512/duskbat) in Deathknell are skinnable with huge drop chances.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
These should **not** be skinnable. Checked with wowhead and other woltk databases.

##### CURRENT BEHAVIOUR:
![image](https://user-images.githubusercontent.com/6963500/107050438-e6085c00-67d3-11eb-9128-b0401471b450.png)

##### STEPS TO REPRODUCE THE PROBLEM:
1. go c id 1512
2. itemadd 7005
3. learn 8613
4. kill & skin

##### AC HASH/COMMIT: 
[adcf3f7a](https://github.com/azerothcore/azerothcore-wotlk/commit/adcf3f7a)

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Hacaw** [comment]
Related to: https://github.com/chromiecraft/chromiecraft/issues/38

**Comment by LightDestory** [comment]
I guys, I will try to fix this. I am a newcomer, I am still learning but I will try my best :)

**Comment by OMGhixD-OG** [comment]
I've checked unit_flags and they do not have 

67108864 | 0x04000000 | UNIT_FLAG_SKINNABLE | Skinnable
-- | -- | -- | --

In table Creature_Template or Creature. So it is not unit_flags related.

The only thing that would make sense to do is remove the skinloot (to clear that data, since they arent suppose to be skinnable in the first place). Perhaps by just removing the skinnloot(id) this resolves itself? Will test and report back with a query if this works out fine.

**Comment by OMGhixD-OG** [comment]
`UPDATE `creature_template` SET skinloot = 0 WHERE entry = 1512;`

This resolves this issue. Removing the Skinnloot(ID) Definitely removed the ability to skin it.

**Comment by LightDestory** [comment]
Sure go on, thanks for this amazing explanation :D

**Comment by OMGhixD-OG** [comment]
> Sure go on, thanks for this amazing explanation :D

I apologize for just jumping in like that :P I just felt like checking myself to why it was skinnable in the first place as i was pretty sure a flag would cause this to be possible. But little to my surprise it wasn't a flag so i got motivated to keep digging.

**Comment by LightDestory** [comment]
No worries, I am still learning, a friend of mine already told me some tips but I wanted to learn on the field. But learning other's solution is also a way to learn 👍

**Comment by OMGhixD-OG** [comment]
> No worries, I am still learning, a friend of mine already told me some tips but I wanted to learn on the field. Reading other's solution is also a way to learn 👍

Glad to hear. I hope my documentation is of good learning practice :)

**Comment by Voxstrasza** [comment]
> 
> 
> ```sql
> UPDATE `creature_template` SET skinloot = 0 WHERE entry = 1512;
> ```
> 
> This resolves this issue. Removing the Skinnloot(ID) Definitely removed the ability to skin it.
> Not sure if a PR is gonna be required for such a tiny little change.
> 
> ![Image of creature not being skinnable.](https://camo.githubusercontent.com/aa010235d0e7eaecbde788f7ce1057ea13fce312b346c630844464f66e2e56ae/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3830363938383034373737373236373731332f3830373330333239333731373833393837322f756e6b6e6f776e2e706e673f77696474683d31323134266865696768743d363833)

make a pr boi

**Comment by Kitzunu** [comment]
Fixed, alongside other creatures that should not have skinning
