### ISSUE TITLE
Doctor Gregory Victor has wrong gossip text  [$5]

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4458]
##### SMALL DESCRIPTION:
Horde First-Aid Trainer, [Doctor Gregory Victor](https://wotlk.evowow.com/?npc=12920) has the [Alliance trainer](https://wotlk.evowow.com/?npc=12939) dialogue counterpart.

##### CURRENT BEHAVIOUR:
https://cdn.discordapp.com/attachments/806916563810385970/806918959382396968/Wow_JVNhb9gWuz.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:
https://wow.gamepedia.com/Doctor_Gregory_Victor

##### STEPS TO REPRODUCE THE PROBLEM:
1. go c id 12920
2. right-click on the npc
3. notice the wrong text

##### AC HASH/COMMIT: 
[adcf3f7a](https://github.com/azerothcore/azerothcore-wotlk/commit/adcf3f7a)

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Hacaw** [comment]
Related to: https://github.com/chromiecraft/chromiecraft/issues/36

**Comment by Kitzunu** [comment]
5381 is the right gossip_menu

**Comment by Stifler82** [comment]
@Voxstrasza
Just to catch me up, Is the fix finished or is it still W.I.P.?

**Comment by Voxstrasza** [comment]
WIP

**Comment by Helias** [comment]
any updates? @Voxstrasza

**Comment by Zoidwaffle** [comment]
I also looked at this... it's not as simple as replacing gossip_menu 5382 with 5381 that has the right sayings (I found the issue in Chromiecraft, didn't look here until later... So also found this looking in the DB).

I guess there's some stuff happening in src/server/scripts/World/npcs_special.cpp as well - I have been unable to find out how what he says is decided based upon your current first aid level... Anyone here smart enough to know how the logic is connected? :eyes:

**Comment by ChromieCraftServer** [comment]
> WIP

@Voxstrasza any news ?

**Comment by Voxstrasza** [comment]
> 
> 
> > WIP
> 
> @Voxstrasza any news ?

no idea how to fix the issue and make it work correctly.
