### ISSUE TITLE
[Bash Dashboard] install-deps fails on Debian 10

### ISSUE THREAD

**Issue by LightDestory** [azerothcore/azerothcore-wotlk#4459]
##### CURRENT BEHAVIOUR:
Running "install-deps" on acore.sh fails due to repository issues. Apt can't retrieve libmysql, mysql-server, libssl1.0, ect...

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Running "install-deps" on acore.sh should install all the necessary deps on the system.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Follow the guide on "https://www.azerothcore.org/wiki/Install-with-AC-Dashboard"
##### EXTRA NOTES:
Following the deps listen inside the "debian.sh" that is runned by inst_configureOS:
sudo apt-get install -y git cmake make gcc g++ clang libmysqlclient-dev libssl1.0-dev libbz2-dev libreadline-dev libncurses-dev mysql-server libace-6.* libace-dev curl unzip

Following the deps listed on the "Requirements" section of the wiki regarding Debian 10:
sudo apt-get install git cmake make gcc g++ clang default-libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mariadb-server libace-6.* libace-dev

##### AC HASH/COMMIT:
None

##### OPERATING SYSTEM:
Debian 10 under WSL 2 on Windows 10 20H2

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Kitzunu** [comment]
Sounds very strange if it would install MySQL and OpenSSL ngl.

But I guess @Helias would know more

**Comment by Helias** [comment]
I think we should change the debian.sh content based on the version 8-9-10 of debian, as the wiki already does.
