### ISSUE TITLE
[NPC] id=10216 Gubber Blump missing gossip

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4463]
![WoWScrnShot_020421_223059](https://user-images.githubusercontent.com/58756521/107109959-f6d7c280-6811-11eb-87c3-eeca48222ae4.jpg)
 
### SMALL DESCRIPTION:
Selecting the dialogue option doesn't do anything.
 
### EXPECTED BLIZZLIKE BEHAVIOUR:
https://classic.wowhead.com/quest=1141/the-family-and-the-fishing-pole#comments

What I assume is supposed to happen is that he's supposed to lend you a wishing pole should you not have one

### CURRENT BEHAVIOUR:
No gossip happening.

### STEPS TO REPRODUCE THE PROBLEM:
.go c 39062
Talk to the npc and click the gossip option.
 
### AC HASH/COMMIT:
[chromiecraft/azerothcore-wotlk@b905ce8](https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2)

### OPERATING SYSTEM:
Ubuntu 20.04

### MODULES:
* [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
* [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

### OTHER CUSTOMIZATIONS:
None.

### SERVER:
ChromieCraft
https://github.com/chromiecraft/chromiecraft/issues/48

**Comment by Helias** [comment]
Maybe this can help
https://github.com/TrinityCore/TrinityCore/commit/f6e709cde30f4485bcf2cd3739b8c82641b50b79
https://github.com/TrinityCore/TrinityCore/issues?q=Gubber+Blump
