### ISSUE TITLE
Sparkling loot animation is enabled for quest item objective that is already finished

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4465]
##### SMALL DESCRIPTION:
Sparkling loot animation is enabled for quest item objective that is already finished.

##### CURRENT BEHAVIOUR:
![image](https://user-images.githubusercontent.com/6963500/107118936-d8fb7380-688c-11eb-838c-93de9842b1f6.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Sparkling animation should not be present, see the other item required for the quest https://wotlk.evowow.com/?item=10639, where the animation is disabled.

##### STEPS TO REPRODUCE THE PROBLEM:
1. q a 3521
2. additem 10641 3 
3. go xyz 10565.937500 817.015686 1309.181763 1
4. loot one more to have 4/4 and completed objective
5. notice the sparkling animation is still present

##### AC HASH/COMMIT: 
[adcf3f7a](https://github.com/azerothcore/azerothcore-wotlk/commit/adcf3f7a)

##### DATABASE VERSION: 
WORLD: 2021_02_01_00
AUTH: 2021_01_25_00
CHARACTERS: 2021_01_25_00

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
Chromie-Client (Downloaded from 10-01-2021)
DBC & Maps - v9 - 1-12-2020

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Hacaw** [comment]
Related to: https://github.com/chromiecraft/chromiecraft/issues/51

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/107119764-f713a480-6889-11eb-8186-d9475daa1e40.png)
Can't confirm.

Also you need 4 of them for the quest, not 3.
And you can improve the go command like this
```
.go xyz 10565.937500 817.015686 1309.181763 1
```
The "1" is mapID, so you can cast the command anywhere and TP right

**Comment by Kitzunu** [comment]
Nvm I actually can confirm it when I did it manually.

```
.go xyz 10565.937500 817.015686 1309.181763 1
```

The "1" is mapID, so you can cast the command anywhere and TP right

**Comment by Hacaw** [comment]
Sorry @Kitzunu forgot one step, updated now the description.
Thanks for the suggestion, didn't know about that trick with `1`

**Comment by Stifler82** [comment]
@Kitzunu @Hacaw 
have somebody fix this?

**Comment by Stifler82** [comment]
It doesn't seem to me that GameObjects are buggy, to me it looks more like someone who has the **shitty enGB Client**...

**Video Test:** [Sparkling loot animation](https://youtu.be/4NQzRJdHPZw)
