### ISSUE TITLE
[raid]Icecrown Citadel any difficulty Nerub'ar Broodkeeper evading combat

### ISSUE THREAD

**Issue by WotlkCasually** [azerothcore/azerothcore-wotlk#4466]
##### CURRENT BEHAVIOUR:
NPC [Nerub'ar Broodkeeper](https://wotlkdb.com/?npc=36725) Evades combat constantly.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Not evade combat.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Clone [990e494](https://github.com/azerothcore/azerothcore-wotlk/commit/990e4943bad54c5c64e7f6bf0b71c44b43c05211)
2. Follow installation instructions on [AzerothCore bash dashboard](https://www.azerothcore.org/wiki/Install-with-AC-Dashboard)
3. Log in as any character or gm char with .gm off 
4. Go into Icecrown Citadel Raid
5. Try to kill [Nerub'ar Broodkeeper](https://wotlkdb.com/?npc=36725)

##### EXTRA NOTES:
[video demonstration](https://youtu.be/Ws6VQzYgiTc)

##### OPERATING SYSTEM:
Ubuntu 20.04 LTS

##### MODULES:
No modules

##### OTHER CUSTOMIZATIONS:
No customization

**Comment by morpheux** [comment]
Confirmed!
