### ISSUE TITLE
Feature: automated client data download in Docker

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4469]
It would be nice to have a simple bash script that the user can just execute which will:

- download the client data files from wowgaming and extract them (similar to what the `inst_download_client_data` function from [functions.h](https://github.com/azerothcore/azerothcore-wotlk/blob/master/apps/installer/includes/functions.sh#L221) does)
- place them in `docker/worldserver/data/` because Docker needs them there

**Comment by FrancescoBorzi** [comment]
@Yehonal would you like to have a look at this? as you were working on Docker recently

**Comment by locus313** [comment]
@FrancescoBorzi as part of the work I did in the docker-ci restructure:
https://github.com/azerothcore/azerothcore-wotlk/pull/4369 
I did add something that might work for this. The way its currently in the pr to use it from the command line you could do this:
`CI_DOCKER=true ./acore.sh client-data`

**Comment by locus313** [comment]
@FrancescoBorzi I updated the pr to add the additional option. now you can just run `./acore.sh client-data-docker`

**Comment by Yehonal** [comment]
> @FrancescoBorzi I updated the pr to add the additional option. now you can just run `./acore.sh client-data-docker`

I wouldn't create another command like that, but instead configuring correctly the paths in docker and possibly create a subcommand in acore dashboard with which you can handle all the docker-compose operations.

I'm doing that in my PR

**Comment by FrancescoBorzi** [comment]
ok, thanks guys!

**Comment by Yehonal** [comment]
this issue has been completed with the new docker system

the command is: `./acore.sh docker client-data`  that uses the `./acore.sh client-data` inside the container
