### ISSUE TITLE
Cat and bear form - rooting shaman

### ISSUE THREAD

**Issue by MagnusDevs** [azerothcore/azerothcore-wotlk#4471]
Cat and bear form - rooting shaman

Bear and cat-shaped spell is not removing movements rooted by shaman https://wow.gamepedia.com/Druid_shapeshift_forms

When the druid is in the battle against the shaman and shaman uses rooting, the druid does not leave rooting after changing form to bear or cat.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Druid vs. shaman duel
2. Spell Earthbind Totem (Shaman)
3. Cat form or Bear Form (Druid)

rev. d902411

**Comment by Kitzunu** [comment]
I confirm this issue. However, it is bizarre.

This is the code that is called on apply
https://github.com/azerothcore/azerothcore-wotlk/blob/d902411171fef250f842b304bc6c3eeaecab9463/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L1854-L1879

Which calls RemoveAurasByShapeShift that looks like this
https://github.com/azerothcore/azerothcore-wotlk/blob/d902411171fef250f842b304bc6c3eeaecab9463/src/server/game/Entities/Unit/Unit.cpp#L4764-L4778

In that method, it is looking if the spell has MECHANIC_SNARE which Earthbind (3600) actually has... So why it isn't removed I don't know

```
ID - 3600 Earthbind
=================================================
Description: Reduces the movement speed of all nearby enemies by $s1%.
ToolTip: Movement speed reduced by $s1%.
Category = 0, SpellIconID = 686, activeIconID = 0, SpellVisual = (68,0), SpellPriority = 0
Family SPELLFAMILY_SHAMAN, flag [0] 0x00000000 [1] 0x00000001 [2] 0x00000000

SpellSchoolMask = 8 (SPELL_SCHOOL_MASK_NATURE)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
=================================================
AttributesEx1: 0x00000088 (SPELL_ATTR1_CANT_BE_REDIRECTED, SPELL_ATTR1_CANT_BE_REFLECTED)
AttributesEx2: 0x10000000 (SPELL_ATTR2_UNK28)
AttributesEx3: 0x00000001 (SPELL_ATTR3_UNK0)
=================================================
Spell Level = 6, base 6, max 0, maxTarget 0

Category = 0
DispelType = 1 (DISPEL_MAGIC)
Mechanic = 11 (MECHANIC_SNARE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00
Duration: ID (28)  5000, 0, 5000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = -50
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 33 (SPELL_AURA_MOD_DECREASE_SPEED), value = -50, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 13) 10,00

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT
```

**Comment by Kitzunu** [comment]
I know the issue, it is due to some bad changes in https://github.com/azerothcore/azerothcore-wotlk/commit/0b35a24053f4d118b119fe792f187f816acbadfb

I will fix this

**Comment by Kitzunu** [comment]
Feel free to test the PR

**Comment by MagnusDevs** [comment]
Confirmed, now it works!
