### ISSUE TITLE
[Raid] [AQ40] C'Thun Dark Glare Improper Targeting Area

### ISSUE THREAD

**Issue by valens14** [azerothcore/azerothcore-wotlk#4478]
C'Thun Dark Glare hits a conal area instead of a line

CURRENT BEHAVIOUR:
Dark Glare(Spell ID - 26029) hits what appears to be roughly a 60-90 degree cone in front of C'thun.
https://youtu.be/XmM3wqqoo3g - video clip showing it hitting well outside of the line area.

EXPECTED BLIZZLIKE BEHAVIOUR:
Dark Glare should hit targets in a line in front of C'thun.

STEPS TO REPRODUCE THE PROBLEM:
1.  Engage C'thun with .cheat god on command used to prevent Death to the 1st tick of Dark Glare 
2.  Wait until red beam phase begins
3.  While C'thun is in red beam phase, move to various locations in a cone in front of him to see exactly how large the conal area the Dark Glare is doing damage to players in

EXTRA NOTES:
The script for the Dark Glare ability looks to be good.  He selects a target, turns to them, glows red, casts dark glare after a delay, and properly rotates while continuing to cast it.  I think the issue is with the spell itself but I have not been able to find a fix to make it target a line instead of a cone.

AC HASH/COMMIT:
46330ae

OPERATING SYSTEM:
Windows 10

MODULES:
Autobalance
Individual XP
Instance Reset
NPC Buffer
NPC Free Proffessions
NPC Services
PVP Titles
Solo LFG
Transmog

OTHER CUSTOMIZATIONS:
I have changed other portions of the C'thun Script as follows:
- No longer spawns the small eye tentacles or giant claw tentacles in phase 2
- Giant eye tentacles spawn progressively faster the longer phase 2 goes on
- When spawning small eye tentacles in phase 1, only 4 will spawn instead of 8
- Duration of the delay from when C'thun glows red until Dark Glare is cast the 1st time increased to 10 seconds (To allow players to dodge since the area Dark Glare hits is much larger than it should be)
- Small claw tentacles no longer use hamstring

Database/SQL editing:
Health values changed for all mobs
Melee damage reduced to 1 for Flesh Tentacles
Eye Beam damage adjusted
Mind Flay damage adjusted
Rupture damage adjusted

**Comment by UltraNix** [comment]
@azerothcore/testers Can anyone test if it's still valid?

**Comment by Nefertumm** [comment]
@UltraNix confirmed
