### ISSUE TITLE
When Hit and fly by a creature, it has a certain chance to stop combat

### ISSUE THREAD

**Issue by yangyitzzg** [azerothcore/azerothcore-wotlk#4481]
CURRENT BEHAVIOUR:
When Hit and fly by a creature, it has a certain chance to stop combat

STEPS TO REPRODUCE THE PROBLEM:
1. .go -1266.90 1655.86 68.74 543
2. Waiting to be Hit and fly by the soldiers
3. combat stop

EXTRA NOTES:
This problem is probably caused by an update in October 2020

AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/8851152815b23f3d5468f0f92f17437a22b6b8f7

OPERATING SYSTEM:
Windows 10

MODULES:
NO

**Comment by yangyitzzg** [comment]
I'm sorry, The latest update has resolved this issue

**Comment by FrancescoBorzi** [comment]
@yangyitzzg no problem and thanks for letting us know that the issue has been solved.
