### ISSUE TITLE
Amani Berserker Inside of Tree

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4483]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/39

##### SMALL DESCRIPTION:

Troll NPC (Amani Berserker) moving through a large tree.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC's shouldn't spawn or be able to go inside of objects like this. 

##### CURRENT BEHAVIOUR:

Below is a picture of the NPC, he will walk around the tree and sort of phase out of it though he doesn't leave the "tree."
You could melee him but ranged attacks generate LOS errors.

![image](https://user-images.githubusercontent.com/24766235/106949863-2e9c1880-66f3-11eb-95f8-6ca8283e82d7.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to this location (see Current Behavior for location)
2. Wait for this NPC to spawn to see if he is spawning inside of the tree or somehow going inside of it.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Shouldn't this have something to do with the coalition to maps?

**Comment by Kitzunu** [comment]
cc @Yehonal

**Comment by Stifler82** [comment]
> Shouldn't this have something to do with the collision to maps?

@Kitzunu 
No, **because this NPC have been spawned inside the Tree**, and **the Collision System is working good**,(in fact) The Npc in question **isn't able to get out from the Tree "Space" cause Collision**, it gets its **"Random Moving"** **inside the Tree's "Area".**

**Comment by Kitzunu** [comment]
Oh, I thought he walked into it. I didn't understand it had it's spawn inside of it.

Then it is an easy fix :)
Thanks for the clarificatoins

**Comment by Stifler82** [comment]
> Oh, I thought he walked into it. I didn't understand it had it's spawn inside of it.
> 
> Then it is an easy fix :)
> Thanks for the clarifications

@Kitzunu 
It need to be spawned just some meters more far from the Tree
