### ISSUE TITLE
Rogue skills failing

### ISSUE THREAD

**Issue by MagnusDevs** [azerothcore/azerothcore-wotlk#4489]
Rogue skills are failing

1° Stealth is not getting invisible -
2° Vanish is not becoming invisible
3º racial Shadowmeld Night elf is not becoming invisible
4° Sprint is taking rogue out of the invisible

https://wotlk.evowow.com/?spell=1784
https://wotlk.evowow.com/?spell=26889
https://wotlk.evowow.com/?spell=62196
https://wotlk.evowow.com/?spell=11305

rev. 2741a3e

##### OPERATING SYSTEM:
<! - Windows 10 ->

MODULES:
mod-auto-eluna-moon-engine-master

**Comment by Voxstrasza** [comment]
confirmed - shadowmeld doesn't work on any night elf classes, stealth works but sprint removes it and vanish doesn't apply stealth.

thinking 4472 has something to do with this

**Comment by Kitzunu** [comment]
We're looking at it, I think I know the cause

**Comment by MagnusDevs** [comment]
Hello, I was sleeping. test and it's working!
Thank you!
