### ISSUE TITLE
NPC - Lunar Festival Harbinger

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4490]
Double dialogue in some Lunar event NPCs.

![WoWScrnShot_013121_001804](https://user-images.githubusercontent.com/58756521/107110229-56cf6880-6814-11eb-9269-932ece2518f4.jpg)

##### SMALL DESCRIPTION:

Double dialogue.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should have 1 gossip dialogue.

##### CURRENT BEHAVIOUR:

NPC shows two of the same set of dialogue.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to [Lunar Festival Harbringer](https://wowgaming.altervista.org/aowow/?npc=15895)
2. Talk to her.
3. Double gossip option with the same behaviour.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Invalid, was fixed here https://github.com/azerothcore/azerothcore-wotlk/commit/c628cd776e43390421f6f355a57a99c38bccf41b
