### ISSUE TITLE
Burning Blade Apprentice's voidwalker does not enter combat properly

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4493]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Summoned voidwalker by Burning Blade Apprentice is aggro-ed only when close range, pulling the apprentice with ranged attack/spell will not trigger the voidwalker and he will just stay near the NPC even tho I'm in combat with the Apprentice.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Pet (voidwalker in this case) should start attacking the player together with the NPC owning the pet.

##### CURRENT BEHAVIOUR:

Apprentice: https://wowgaming.altervista.org/aowow/?npc=3198
Voidwalker: https://wowgaming.altervista.org/aowow/?spell=12746

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast the spell on the NPC at max range
2. See how the voidwalker just stays idle
3. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
refers to https://github.com/chromiecraft/chromiecraft/issues/55

**Comment by Foosiq** [comment]
Btw this applies basically to any pet summoned by NPC

**Comment by nicoaravena** [comment]
I can confirm what @Foosiq said, but I think it is better to create a new issue related (or edit this and improve the description)

**Comment by Stifler82** [comment]
Fixed, but...

https://user-images.githubusercontent.com/1884642/108665115-11759100-74cc-11eb-8c94-7c641cd4eb62.mp4
