### ISSUE TITLE
Mail visual bug

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4494]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/46

##### SMALL DESCRIPTION:

Items in mail do not display enchants

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Item should display enchant

##### CURRENT BEHAVIOUR:

When displayed in inbox item does not display enchant. When taken out of mail item does have enchant displayed. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enchant an item 
2. Sent to alt
3. View before and after taking item out of mail. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
As of today it is shown in retail shadowlands as well as classic:
https://cdn.discordapp.com/attachments/354347338191339536/808065387446272000/unknown.png
https://cdn.discordapp.com/attachments/354347338191339536/808069582631206972/unknown.png

**Comment by Stifler82** [comment]
I made the update today, morning..
https://user-images.githubusercontent.com/1884642/107158563-eb57d900-6982-11eb-81cf-24eca717be49.mp4

**Comment by Kitzunu** [comment]
This works on TC

**Comment by FrancescoBorzi** [comment]
@Kitzunu if you saw where the code is, we can find the PR fixing it with annotatate

**Comment by Kitzunu** [comment]
Probably this 
https://github.com/TrinityCore/TrinityCore/blob/06c1f728baca8e584fee8a10cb9e793abc5475bf/src/server/game/Server/Packets/MailPackets.cpp#L24-L44
https://github.com/TrinityCore/TrinityCore/blob/06c1f728baca8e584fee8a10cb9e793abc5475bf/src/server/game/Server/Packets/MailPackets.h#L31-L54

**Comment by FrancescoBorzi** [comment]
should be fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/4872

feel free to reopen if that's not the case
