### ISSUE TITLE
Loot chests spawning issue

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4496]
Original issue chromiecraft/chromiecraft#33

##### SMALL DESCRIPTION:

During leveling in Elwynn Forest I have found issue with spawning of Battered chest, the world object. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be present only one chest per sub-location at a same time. 
For example: Elwynn Forest/Forest's Edge - there are given 3 coordinates where chest could spawn according to database. Game algorithm should decide which location select to spawn a chest. 

##### CURRENT BEHAVIOUR:

Coordinates
Actually, I have found 3 Battered chests present at same time in Elwynn forest/Forest's Edge at those coordinates:
24.4, 93.5
26.0, 92.1
27.8, 88.3

Coordinates corresponds with database: https://wotlk.evowow.com/?object=106318#contains
Coordinates of Battered chests for Elwynn's starting location: https://wotlk.evowow.com/?object=2843

##### STEPS TO REPRODUCE THE PROBLEM:

1. I have noticed same issue for every sub-location Elwynn Forest. Deducing from it, this issue applies overall for every location. So you could find root cause probably in this world's object code rather than in location's code section.
2. You can always teleport to coords I have stated or to different coords found in attached links to decide if my theory is true.
3. Bonus invention: In current Blizz version of wow, there is an additional rule - "Opening a chest without looting it will make it disappear after 5 minutes." This rule is made due to players with low bag space, that looted only valuable things from chests and in result they left half-empty chests with only junk containing for other players. Players finding only junk instead of treasure have been disapointed about developer's reward system before this invention.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/2741a3ea1c6bf4b8af1defcf4e31246cfc475466

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

None.

**Comment by Zoidwaffle** [comment]
I just looked a bit into this.

First of all, TC and AC have the same data... Not saying it's correct. 15 chests id 2843 in total both of them... with respawn times set to 15m/1h/2h. So if you are on a low population server, I guess they can all be spawned at the same time.

I have sorted the 15 chests in the current DB by location here:

```
-- Dwarf/gnome
.go xyz -6507.27 688.761 387.274 0 #guid 85816 Coldridge
.go xyz -6524.63 362.427 388.329 0 #guid 85817 Coldridge
.go xyz -6490.65 512.377 387.494 0 #guid 1397 Coldridge
.go xyz -6484.93 294.773 372.653 0 #guid 1454 Coldridge

-- Human
.go xyz -8556.58 -199.101 85.8751 0 #guid 26749 Echo Ridge Mine / Elwyn Forest
.go xyz -9140.58 -282.026 71.8892 0 #guid 26756 Elwyn Forest
.go xyz -8593.03 -169.743 87.1218 0 #guid 34797 Echo Ridge Mine / Elwyn Forest
.go xyz -9038.98 -303.642 74.3616 0 #guid 34798 Northshire Vineyards / Elwyn Forest
.go xyz -9060.95 -463.424 72.5782 0 #guid 85653 Northshire Vineyards / Elwyn Forest

-- Undead
.go xyz 1900.49 1487.23 93.9514 0 #guid 45106 Deathknell / Tirisfall
.go xyz 2081.69 1967.03 101.193 0 #guid 45110 Night Webs Hollow / Tirisfall
.go xyz 1965.06 1617.98 88.2024 0 #guid 85818 Deathknell
.go xyz 1963.66 1383.45 64.1756 0 #guid 85832 Deathknell

-- Night elf
.go xyz 10911.3 848.826 1329.36 1 #guid 49528 Shadowthread Cave
.go xyz 10328 1033.01 1339.31 1 #guid 49529 Shadowglen
```

I don't know about any official rules to the spawning of these - but I think I would prefer we go for pooling them. So all in 1 area are pooled so just 1 is spawned at any point in time... and perhaps a way lower respawn timer as well - like 5 minutes, before a new chest pops up. Well, I'm working on a PR for this just for testing... If you have any info regarding if this seems right or wrong, it would be appreciated.
