### ISSUE TITLE
Patroling Deathguards (mounted) chain aggro range

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4499]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/59

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

**|======MODERATION EDIT Strart======|**
NPC: [Deathguard Abraham](https://wotlkdb.com/?npc=1735)
**|======MODERATION EDIT End======|**
Huge aggro range

##### EXPECTED BLIZZLIKE BEHAVIOUR:

not killing off their path so far away

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a patroling Deathguard in Tirisfal Glades
2. Watch him until he fights something
3. Watch how far he will stray from his point of origin if he chain kills

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Verified. NPC [Deathguard Abraham](https://wotlkdb.com/?npc=1735)
Quest Evidence, Video: [Deathguard Abraham](https://youtu.be/8gXTm78Q4Gw)

**Comment by Zoidwaffle** [comment]
It does look kinda fun how the guards start murdering that far away... But yes, it's not supposed to work like that.

Currently I don't know how to solve something like that - but I would assume some sort of AI scripting is needed. Perhaps fight within a close distance to the waypoint(s) and unless attacked, he should get back to his position after combat has ended no matter if more NPC's are close.

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers any hints?

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Patroling Deathguards chain aggro range](https://youtu.be/GAgINSUQdac)
