### ISSUE TITLE
first quests auto accepted

### ISSUE THREAD

**Issue by rynnokung** [azerothcore/azerothcore-wotlk#45]
When starting at level 1, all quests untill a certain point are set to autocomplete when returning it in. Is not blizzlike.

**Comment by rynnokung** [comment]
Has todo with quest_template : specialFlag, in 3.3.5a we only need to set it to 4 in starting zones, but when we do then something goes wrong, its accepted before the player presses accepted on the dialogue. So to fix this we can remove specialFlag 4 from the database or we need to modify the questhandler to not autoaccept when special flags = 4

Query could be something like : UPDATE  `quest_template` SET `SpecialFlags` = "0" where `SpecialFlags` = "4";

**Comment by ShinDarth** [comment]
once removed the autocomplete, are all those quest working properly?

**Comment by rynnokung** [comment]
There are about +\- 170 quests impacted. Will test them all to be sure.

**Comment by ShinDarth** [comment]
as you mentioned, probably there is a criteria in the database to filter them

**Comment by DantestyleXD** [comment]
Starter zone's quests auto complete or auto accept?
If you mean "auto complete": I haven't found quests with an auto complete;
If you mean "auto accept": All starter zone's quest are auto accept
