### ISSUE TITLE
[QUEST] An unusual patron

### ISSUE THREAD

**Issue by ghost1988** [azerothcore/azerothcore-wotlk#450]
**Description**:
In this quest the player summon a mob with an item and kill to complete the quest

**Current behaviour**: I use the item quest in front of the altair of Nais, the spell work with animation but nothing happen.

**Expected behaviour**: I use the item quest in front of the altair of Nais, spawn Nais

**Steps to reproduce the problem**:

1. Go to Altiar of Nais go object 11089
2. use item quest in front of altair
3. Nothing happen (and you can't try re-use item)

Quest: http://www.wowhead.com/quest=9457/an-unusual-patron
Item quest: http://www.wowhead.com/item=23680/gift-of-naias

**Comment by starrheld** [comment]
Works, but spawns behind you, which is not blizzlike.

![IMG1](http://i.imgur.com/fnSUPMR.jpg)

It's also missing creature_text:

> Who challenges Naias? Puny troll, you are little better than those mindless trolls I have played against each other like so many pieces on a game board!


-- https://youtu.be/KGeiXafHPZY?t=1m57s

**Comment by ghost1988** [comment]
my fault thanks
