### ISSUE TITLE
[Core-GM Commands] Some GM commands do not work

### ISSUE THREAD

**Issue by LightDestory** [azerothcore/azerothcore-wotlk#4505]
##### CURRENT BEHAVIOUR:
Playing as a GM level 3 the following commands do not work:

- .bank
- .explorecheat

The game responds with "There is not such command"

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The excepted behaviour is:

- .bank, show player's bank
- .explorecheat, set as explored or not all the zones

##### STEPS TO REPRODUCE THE PROBLEM:
1. Use the commands listed above

##### EXTRA NOTES:
None

##### AC HASH/COMMIT:
3671da6

##### OPERATING SYSTEM:
Debian 10 under WSL 2 on W10 20H2

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Voxstrasza** [comment]
wiki is outdated, the correct commands for what you want are as follows

```
.explore cheat 1 (on) 0 (off)
.character check bank
```

**Comment by Kitzunu** [comment]
Wiki is wrong. it is:
```
.char check bank
.cheat explore 1
```
