### ISSUE TITLE
Carbonite Map detect invisible MJs outside rest zones

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#4508]
Carbonite Map detect invisible MJs outside rest zones
##### CURRENT BEHAVIOUR:

When you are spying players with .gm visible off the client addon Carbonite Map detect you.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

May be this is not an AzerothCore bug but may be anyone can help me to fix that editing  server config.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create an GM account and connect to the server.
2. Turn off visibility.
3. Create a normal account and connect too with Carbonite Map client addon.
4. Go to non resting zone with normal account.
5. .ap to the normal char with gm.
6. Look the carbonite map in normal account an you will see the gm char.

##### AC HASH/COMMIT:

71b40ed8bc75

**Comment by avarishd** [comment]
If I recall correctly carbonite creates randomly named hidden chat channels to communicate with other carbonite users in the area/map. Nothing to do with GM visibility, since all the info comes from the chat.
