### ISSUE TITLE
A few Stratholme issues

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4513]
##### CURRENT BEHAVIOUR:
- magistrate Barthilas doesn't run away
- The gate in  slaughter square doesn't close.
- ramstein comes out way to fast and walks through the door

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- When entering from the service entrance, the magistrate should run away when he says his yell https://youtu.be/RMdgfp2x95c?t=225 . He then goes there https://youtu.be/W9GI5f-vTq0?t=2038
- The gate should close whenever an abomination is pulled and re open when party wipes or Rivendare is beaten
- ramstein should come out much more slowly, and after the door is opened. he should also walk slowly to the middle of the room https://youtu.be/W9GI5f-vTq0?t=2524 .But during his walk he can be attacked anytime,

##### AC HASH/COMMIT:
c5400b301259e048cfb89d3e591bef565d51cec3

##### OPERATING SYSTEM:
Windows 10

**Comment by Zoidwaffle** [comment]
Barthilas is also an issue for TC: https://github.com/TrinityCore/TrinityCore/issues/19383 (just putting it as an reference here)
