### ISSUE TITLE
Most vanilla dungeon bosses, and raid creatures are not correctly immune to Crowd Control

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4514]
##### CURRENT BEHAVIOUR:
- I have not tested that extensively on every dungeon bosses. But I can say that from what I have tested, you can CC all bosses in stratholme, scholomance, dire maul north... pretty much fears, roots, stuns etc all work. It makes all of them stupidly easy
It's ridiculous, you can even cc raid mobs 
![image](https://user-images.githubusercontent.com/40864460/107321870-a2e40c80-6aa3-11eb-9789-6b749da12156.png) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Most of those high level dungeons bosses should be immune to CC. I can't say precisely which ones aren't but anything medium/high level supposed to be strong is usualy immune, especially if they are bigger sized.

Making a list would take super long, I suggest just copying the data from a core that got it right, vmangos is the most accurate for vanilla content.

##### STEPS TO REPRODUCE THE PROBLEM:

1. test CC abilities against creatures that are supposed to be immune.

##### AC HASH/COMMIT:
c5400b301259e048cfb89d3e591bef565d51cec3

##### OPERATING SYSTEM:
Windows 10

**Comment by BarbzYHOOL** [comment]
yeah, we noted this when reworking bosses, if u want to fix it, hit me up on discord i'll give u a procedure and then you can make a PR out of it, what do you think?

**Comment by Zoidwaffle** [comment]
Hey, I basically did what @T1ti suggested - that is, I looked in the vmangos DB and compared creature_template entry+name with AC.

Then I took the changes to mechanic_immune_mask, if any, and assumed vmangos being right.

It's a fairly long and boring list to check...
