### ISSUE TITLE
Various Scholomance issues

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4520]
##### CURRENT BEHAVIOUR:

~~1.  Kirtonos The Herald is flying in human form, it's extremly weird.~~ fixed
~~2.  Unstable corses don't explode on death~~ fixed
~~3.   Occultists don't turn into shades~~ fixed
~~4.  Instructor malicia goes oom super fast, her corruptions cost 1k mana.(out of 7k)~~ fixed
~~5.  Splintered skeletons all aggro together~~ fixed
~~6.  bottom middle room of darkmaster Gandling encounter isn't working correctly: the gate isn't an interactive gobject(can't even click it in gm mode like the others). No spawns in the room and the gate never opens, You can't escape it.~~ fixed
~~7. Adds spawned during Darkmaster's Gandling encounter have loot and give XP.~~ fixed

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. He should stop flying in human form
2. They do 750 aoe magic dmg around them  when they die  https://youtu.be/s-2GXud7CJI?t=1120
3. https://youtu.be/s-2GXud7CJI?t=1496 Occultists turn into dark shades when they drop to low health. Those shades are immune to physical damages. TC got that working properly if you wanna copy it. 
4. https://youtu.be/s-2GXud7CJI?t=1592 her mana barely moves after she casts corruption
5. https://youtu.be/s-2GXud7CJI?t=1748 They are more spread out and roam, you can pull them separately
6. It should work like the other rooms, some adds spawn and gate opens when they are defeated
7. They should have no loot and XP like all temporary summons.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Test those issues in scholomance

##### AC HASH/COMMIT:
639d49509da0d931a1886290fd706e681682e171

##### OPERATING SYSTEM:
Windows 10

**Comment by Helias** [comment]
This can be related to https://github.com/azerothcore/azerothcore-wotlk/pull/4509/files
@Footman @Yehonal

**Comment by vtihomirov** [comment]
@T1ti 
> 1. Kirtonos The Herald is flying in human form, it's extremly weird.

Can you please re-test with the latest changes as I think https://github.com/azerothcore/azerothcore-wotlk/pull/5097/files PR addressed the issue.

> 7. Adds spawned during Darkmaster's Gandling encounter have loot and give XP.

According to https://youtu.be/vRFfCtpNpcY?t=122 they should provide loot. But not reputation.
Also I wasn't able to find a valid source about the XP. If you can share a source of proof.

**Comment by vtihomirov** [comment]
I tried to resolve
> 3. Occultists don't turn into shades

with UPDATE_TEMPLATE to dark shades like what they did in TC but there are two main issues with this.
1. For some reason when I update the template I'm unable to loot the mob on death.(No Loot)
2. When the mob resets by either Feign Death or Vanish it retains its updated template to Dark Shade instead of resetting to Scholomance Occultists.

I didn't find an option to reset the template and to make the looting work so, I decided to drop my changes towards this issue and I'm looking for suggestions.
Cheers

**Comment by T1ti** [comment]
> @T1ti
> 
> > 1. Kirtonos The Herald is flying in human form, it's extremly weird.
> 
> Can you please re-test with the latest changes as I think https://github.com/azerothcore/azerothcore-wotlk/pull/5097/files PR addressed the issue.
> 
> > 1. Adds spawned during Darkmaster's Gandling encounter have loot and give XP.
> 
> According to https://youtu.be/vRFfCtpNpcY?t=122 they should provide loot. But not reputation.
> Also I wasn't able to find a valid source about the XP. If you can share a source of proof.

he doesn't ahve the fly bug but now he has an even weirder bug where he just stands still and doesn't move at all 
![image](https://user-images.githubusercontent.com/40864460/114314386-b12dc380-9afa-11eb-9c00-8aa0c097948f.png)
