### ISSUE TITLE
Seed of Corruption's explosion ignores LOS

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4521]
##### CURRENT BEHAVIOUR:
The warlock spell Seed of Corruption ignores LOS and can damages ennemies trhough walls, this is especially bad in dungeons as you can aggro some creatures in another room.
![image](https://user-images.githubusercontent.com/40864460/107406936-4f0c0e80-6b09-11eb-806c-ca7c45d35d62.png)
 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Seed of corruption's explosion should not damages enemies behind walls.
![image](https://user-images.githubusercontent.com/40864460/107407079-7d89e980-6b09-11eb-96a5-ce1c9ee16f25.png)

##### STEPS TO REPRODUCE THE PROBLEM:
1.  I recommand testing this in the second room of scholomance where all the warlocks are, there is a room of skeletons under it.
Just cast seed on one of the warlocks, make it explode and see what happens.

##### EXTRA NOTES:
Trinity Core recently fixed this issue, it seems like this spell still has the ignore LOS flag in the DBC. they had to fix it through core changes, this flag might be important to make sure it can still explode when the player is out of sight ?
Here was the issue https://github.com/TrinityCore/TrinityCore/issues/26010 
And the fix : https://github.com/TrinityCore/TrinityCore/pull/26019 

##### AC HASH/COMMIT:
639d49509da0d931a1886290fd706e681682e171

##### OPERATING SYSTEM:
Windows 10

**Comment by Helias** [comment]
May this can be related to https://github.com/azerothcore/azerothcore-wotlk/pull/4509/files
@Footman, @Yehonal what do you think?

**Comment by T1ti** [comment]
From what I've read, it's only related to a flag on that spell

**Comment by Kitzunu** [comment]
Yes

**Comment by T1ti** [comment]
bump if anyone is interested in fixing this
