### ISSUE TITLE
Incorrect attack speed values for vanilla creatures(and movement speeds)

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4524]
##### CURRENT BEHAVIOUR:
So TC had that same issue, I reported it about a week ago and they "partially" resolved it by restoring all unsniffed values to the default value blizz uses 95% of the time (2000). (which is MUCH better than the current non sense)
Here's an example of completely wrong attack speed data for dire maul north creatures 
![image](https://user-images.githubusercontent.com/40864460/107469559-3ed84b80-6b6a-11eb-94b4-4fb39f73b3de.png)
(screenshot from TC db, exactly the same values in AC)
Link to my issue to TCwith some proofs, their explaination to why the valeus are so wrong, and their fix : 
https://github.com/TrinityCore/TrinityCore/issues/26012
Basically they said that all attack speeds have been generated from a random number generator years ago which is why they are so...random and make no sense.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
![image](https://user-images.githubusercontent.com/40864460/107469868-d342ae00-6b6a-11eb-82c7-49f385f9dcce.png)
For Dire Maul north creatures specifically, this is how they should look like from vmangos.

 **But globally, thousands of creature have completely wrong attack speed data**
An easy quick fix is so set everything that is not from sniffs to default like TC

Vmangos also sniffed the speed of thousands of vanilla creatures, all values in those updates are from sniffs : 
https://github.com/vmangos/core/commit/f0a1fbfc87d97d8a876bf569ca9eb09729714cdd
https://github.com/vmangos/core/commit/4a1083821eecdd77129e053e9c77b966c15f6924

##### AC HASH/COMMIT:
97b8394f97d8505284ded67c48541230ed12b3a1

**Comment by FrancescoBorzi** [comment]
@Knindzagxg

**Comment by Knindzagxg** [comment]
Thats true.

There is pretty low number of NPCs that have lower then 2.
Think there was error long time ago from sniffs cause lots of mobs have some attack speed modifier (buff or etc).

Sadly i didnt have time to even check those values when we were fixing classic zones / dungeons.

I should have more time in a week or two and can add to TBC fixes im working on.
Wish i had more time atm.

**Comment by BarbzYHOOL** [comment]
I think this is related https://github.com/vmangos/core/issues/997 
after discussing with titi, we should probably get rid of mindmg/maxdmg and only use a dmgmodifier (while i suggested the other way around to knindza etc for boss dmg), apparently that's how TC and some other emulators do and it makes more sense

From what I've seen, on AC we currently make use of mindmg/maxdmg, but we don't have hardcoded HP or Armor value, so it looks like we have the modifiers right, except for damage... why??

**Comment by FrancescoBorzi** [comment]
@T1ti thanks for reporting this, would you be able to provide a PR importing the fixes from TC/vmangos?

**Comment by T1ti** [comment]
I'm not a programmer, I definitely won't be able to port core changes, but I can help for the database and values stuff

**Comment by FrancescoBorzi** [comment]
> I'm not a programmer, I definitely won't be able to port core changes, but I can help for the database and values stuff

where are the core changes? I only see SQL changes from the TC/vmangos links you've mentioned

**Comment by T1ti** [comment]
> I think this is related [vmangos/core#997](https://github.com/vmangos/core/issues/997)
> after discussing with titi, we should probably get rid of mindmg/maxdmg and only use a dmgmodifier (while i suggested the other way around to knindza etc for boss dmg), apparently that's how TC and some other emulators do and it makes more sense considering it's how it works for health and armor
> [TrinityCore/TrinityCore@3018ff4](https://github.com/TrinityCore/TrinityCore/commit/3018ff4e6cbed7e3270df7727d1a04e28a901954) (found by Titi)
> 
> From what I've seen, on AC we currently make use of mindmg/maxdmg, but we don't have hardcoded HP or Armor value, so it looks like we have the modifiers right, except for damage... why??
> 
> Additional information here (with a player collected DB): [TrinityCore/TrinityCore@f188b0d](https://github.com/TrinityCore/TrinityCore/commit/f188b0d647c19820ce1e36923f0c72082b8512c5)

(https://github.com/TrinityCore/TrinityCore/commit/cd76d3290719161db1c10b4c82de191db1cef7e8 follow up commit to that)



> > I'm not a programmer, I definitely won't be able to port core changes, but I can help for the database and values stuff
> 
> where are the core changes? I only see SQL changes from the TC/vmangos links you've mentioned

Sorry I tought you were talking about that previous message about the classlevelstast system change. Sure I can make a PR ofr all the database speeds, how would you want me to do that ? Just have a massive file with the thousands of lines ?

What I think the best would be : 
-First apply that TC commit that changes wrong data to default (2000).
-Then apply vmangos sniffed data

**Comment by Zoidwaffle** [comment]
@T1ti : I'm looking into comparing the BaseAttackTime and RangeAttackTime values from the creature_template.

If there are differences, then take the vmangos one as the valid one... Does that sound like a plan?

**Comment by T1ti** [comment]
yes, first maybe also look at the TC fix that reverted all the random values to default (2000)

**Comment by Zoidwaffle** [comment]
@T1ti - I combined the TC "default" commit with the vmangos DB values.

Hopefully this is for the better!
