### ISSUE TITLE
All hp is reduced! (raid)

### ISSUE THREAD

**Issue by blakcnightt** [azerothcore/azerothcore-wotlk#4526]
hp All bosses are correct
But when a few
People go to instance
All hp is reduced! (raid)
But I think with the addition of a player to inctance
Like the Icecrown Citadel
The hp of each boss should not be reduced!   And I even see that with the arrival of raid players
Hp mobs within the instance are also reduced
And I do not think so
The same thing happens
Everything must remain the same

> 

![WoWScrnShot_020921_191254](https://user-images.githubusercontent.com/75519955/107500789-d742f000-6bab-11eb-8b47-a62cf91f4a14.jpg)
![WoWScrnShot_020921_191328](https://user-images.githubusercontent.com/75519955/107500799-da3de080-6bab-11eb-98a5-a4bd3d0ce173.jpg)

**Comment by Kitzunu** [comment]
follow the issue template

**Comment by blakcnightt** [comment]
I am a novice
And please
Explain it to me more clearly

**Comment by FrancescoBorzi** [comment]
@blakcnightt when you open a new issue there is a template with categories you need to fill with information, you deleted it :D

![image](https://user-images.githubusercontent.com/75517/107492897-3e04e100-6b8d-11eb-887f-973bcfa755b8.png)

**Comment by blakcnightt** [comment]
The problem is not just hp bosses
When we enter the advice of people, hp mobs also decrease
In summary
By entering several instance
The whole instance goes down

- [ ] https://3x3x5.ir/dl/2021/02/sshot-1.jpg
- [ ] https://3x3x5.ir/dl/2021/02/sshot-2.jpg

And the next thing is that
I am from https://github.com/azerothcore/azerothcore-wotlk
2 days ago azerothcore
I installed
And I did not make any adjustments!

**Comment by blakcnightt** [comment]
![4](https://user-images.githubusercontent.com/75519955/107500550-859a6580-6bab-11eb-8d6c-5d7956387583.jpg)

**Comment by Kitzunu** [comment]
You are still not following the template.

You sre missing Rev, Blizzlike behavior and steps to reproduce the issue

**Comment by Voxstrasza** [comment]
this dood is using the autobalance module
