### ISSUE TITLE
DB/Gameobject: Tristanfall Pumpkin

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4528]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/63

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
GameObject: [Tirisfal Pumpkin](https://wotlkdb.com/?object=375) at **Solliden Farmstead** in [Tirisfal Glades](https://wotlkdb.com/?zone=85) I think it has a wrong respawn time for 3.3.5a, because their respawn time is after 10+ minutes currently and I suppose it should be less than 10 minutes.

This GameObject in question is used to complete:
Quest: [Fields of Grief](https://wotlkdb.com/?quest=365)
The Quest requires you to loot 10 [Pumpkins ](https://wotlkdb.com/?item=2846) from [Tirisfal Pumpkin](https://wotlkdb.com/?object=375)
The Quest can be taken and delivered by:
**NPC_Start:** [Deathguard Simmer](https://wotlkdb.com/?npc=1519)
**NPC_End:** [Apothecary Johaan](https://wotlkdb.com/?npc=1518)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
I assume (because I don't know for sure), that the Respawn Time of this Game Object should be around 5 minutes.

##### CURRENT BEHAVIOUR:
10+ minute spawn, too long.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to [Tirisfal Glades](https://wotlkdb.com/?zone=85) **Solliden Farmstead** Area
2. Take the Quest: [Fields of Grief](https://wotlkdb.com/?quest=365) From: **NPC_Start:** [Deathguard Simmer](https://wotlkdb.com/?npc=1519)
3. Loot some pumpkins 
4. And wait for its respawn.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/63#issuecomment-776614338

**Comment by Zoidwaffle** [comment]
The respawntime is 700s and there are 10 spawns in total.

If you look at TC, they have 32 spawns and they respawn after 120s.

If no others look into this, I can probably do it a little later today.

I haven't found any "official" numbers to support one or the other, but it sounds to me like the spawning time should at least be decreased and possibly get more spawns as well.

**Comment by Stifler82** [comment]
> The respawntime is 700s and there are 10 spawns in total.
> 
> If you look at TC, they have 32 spawns and they respawn after 120s.
> 
> If no others look into this, I can probably do it a little later today.
> 
> I haven't found any "official" numbers to support one or the other, but it sounds to me like the spawning time should at least be decreased and possibly get more spawns as well.

I agree with you.

**Comment by Kitzunu** [comment]
Port the spawns from TC, look if they are pooled or just permanently spawned. And reduce respawn time :)

**Comment by Zoidwaffle** [comment]
yeah, I'm actually working on it right now :grin:

**Comment by Zoidwaffle** [comment]
There you go - please test and report back if it works as intended!
