### ISSUE TITLE
Deleted Restore command

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#453]
**Description**: AC Not Have Restore commands for restore deleted characters like trinitycore

**Current behaviour**: not work .character deleted restore

**Expected behaviour**: work on trinitycore

**Branch(es)**: 0.x / 1.x / master (Master)

**AC hash/commit**:  Latest AC

**Operating system**:  7

**Modules**:  Are you using modules? if yes, list them Transmog - anticheat

**Other Customizations**: NO

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
there is a PR to implement that but unfortunately the author doesn't have time to finish it, maybe you can help us and start testing it?

https://github.com/azerothcore/azerothcore-wotlk/pull/164

**Comment by falzard** [comment]
Test what, it's incomplete, and it has been reported "not working". We need to wait until a developer completes it before testing it.

**Comment by ShinDarth** [comment]
maybe test to try to understand what's wrong and how to fix it?

no one borns as a developer, I started learning things by trying to figure out what was wrong or missing in the code.

I would remind that this is an educative project, after all :D

**Comment by Viste** [comment]
how add commits to PR who created not by you

**Comment by ShinDarth** [comment]
@Viste  add as a remote the fork where the PR is opened from:

https://help.github.com/articles/adding-a-remote/

then you are able to access the branches of that fork in your local clone, so you can create a local copy of that branch and do whatever you want with it (work with it, push it to your github fork, etc...).

Feel free to poke me if you need any help.

**Comment by falzard** [comment]
> I would remind that this is an educative project, after all :D

For me, it's not. I have no passion for Cpp

**Comment by Franklampardst** [comment]
@ShinDarth Tested and Working Perfectly without problem for me "old" command working too for me Tnx

**Comment by ShinDarth** [comment]
@Franklampardst if you meant that you tested that PR, please leave your feedback in the PR page:

#164 

thank you!

**Comment by starrheld** [comment]
Like mentioned in the previous comment, all feedback and discussion is to be held in the active PR. https://github.com/azerothcore/azerothcore-wotlk/pull/164
