### ISSUE TITLE
Tormek Stoneriver incorrectly spawned

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#4531]
##### CURRENT BEHAVIOUR:
Tormek Stoneriver (GUID 244510 / NPC ID 16009) is spawned in Ironforge and offers the quest "Dearest Colara," for the Love is in the Air event.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This NPC and the quest were removed in 3.3.

Patch 3.3.0 (2009-12-08): Removed. 
Patch 3.3.0 (2009-12-08): Patch changed achievements for the event, and can be presumed to have removed this quest.

##### AC HASH/COMMIT:
1a137da

**Comment by Zoidwaffle** [comment]
@Voxstrasza would you recommend removing the NPC and quest from the database entirely? 

Or should they remain as a reference, only removing the spawn location?

**Comment by Voxstrasza** [comment]
> 
> 
> @Voxstrasza would you recommend removing the NPC and quest from the database entirely?
> 
> Or should they remain as a reference, only removing the spawn location?

I think they can stay in the DB for reference, deleting the spawn and deprecating the quest should work.

**Comment by Zoidwaffle** [comment]
Check, done!
