### ISSUE TITLE
creature_text, npc_text clean-up project

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#4536]
Our database is infested with text, NPC emotes, scripted events, etc for later expansions.  There is gossip text for the Dragon Soul raid in Cataclysm, for example, and many others for Cataclysm and even some Mists of Pandaria text.

There is literally over 10 thousand lines of code here; I encourage those who care enough to skim through it, and if something doesn't seem like it should be here (i.e. references to Aggra, thrall's wife who isn't in-game until Cataclysm) copy and paste the entire line of text and throw it into google.  There's a 99% chance you'll find a wowpedia page and it will tell you what patch that text was implemented, what event, etc.

If you find this text, simply make a PR and delete it and free up some space in the database, because there are some texts that are still not in-game yet that should be there

**Comment by Kitzunu** [comment]
I will close this, it is not really what we track due to the magnitude of texts in the database.
