### ISSUE TITLE
Pala retri talent Heart of the Cruzader not working

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#4551]
Pala retri talent Heart of the Cruzader not working

##### CURRENT BEHAVIOUR:

The Crusader Heart Suppression Paladin talent (Rank IDs: 20335, 20336, 20337) that should cause a debuff when casting a judgment on the enemy (Debuff IDs: 21183, 54498, 54499) is not working.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you have the retri talent Heart of the Cruzader and cast a judgment to an enemy it shoult apply a debuff that increase your critical hit from 1 to 3 %.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create and levelup a Paladin and set the talent Heart of the Cruzader.
2. Cast a judgment to an enemy.
3. Look at debuffs apply.

##### AC HASH/COMMIT:

e75961756df5

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

Anticheat
Transmog
Duel Reset

**Comment by r0m1ntik** [comment]
Confirm

**Comment by apav** [comment]
This is still not working for me, the debuff isn't applied when I cast a Judgement on the live server.
