### ISSUE TITLE
[Core] Spellscript 22539 won't be executed

### ISSUE THREAD

**Issue by LightDestory** [azerothcore/azerothcore-wotlk#4555]
##### CURRENT BEHAVIOUR:
During the launch of worldserver I receive the following warning:
`TSCR: Spell `22539` Effect `Index: EFFECT_0 Name: 77` of script `spell_bwl_shadowflame` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed`

##### EXPECTED BLIZZLIKE BEHAVIOUR:
No warnings

##### STEPS TO REPRODUCE THE PROBLEM:
1. Run the worldserver
2. Read the logs on the terminal

##### EXTRA NOTES:
None

##### AC HASH/COMMIT:
c5400b301259

##### OPERATING SYSTEM:
Debian 10 under WSL2

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Voxstrasza** [comment]
This was fixed in #4474
