### ISSUE TITLE
Unable to log out when AFK [$10]

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4557]
##### CONTENT PHASE:

1-19
Issue probably not dependant on levelrange.

##### SMALL DESCRIPTION:

Unable to log out log out / exit game via the games respective buttons when standing on another toon. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The positioning of a character inside another should not affect the ability to log out.

##### CURRENT BEHAVIOUR:

When following with multiple toons and hereby standing inside another, the "Logout" and "Exit Game" button **rarely** return  "You can not log out now".

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Log multiple toons and have them all follow the same main.
Step 2 Play a while. 
Step 3 Try to log out inside an Inn with all followers standing inside of each other. 

Moving the slightest bit, lets that toon log out just fine. The phenomenon does only appear when they are perfectly stacked.

I myself have been unable to reproduce the problem reliably. It seems to be mandatory to be logged in for a while. However, it did appear multiple times.
I will try to remember to record a video of the issue when i have a longer playsession and the error appears the next time.

Related: https://github.com/chromiecraft/chromiecraft/issues/77

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
I can confirm this never happended in dozens of days /played and hundreds of logouts with c208a12 from June 3rd.

**Comment by FrancescoBorzi** [comment]
I can confirm

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers any ideas about what could be the cause of this?

**Comment by Kaev** [comment]
> @azerothcore/developers any ideas about what could be the cause of this?

Maybe it's not position related but the infight bug that we all know and hate

**Comment by 55Honey** [comment]
> Maybe it's not position related but the infight bug that we all know and hate

Moving the slightest bit, lets that toon log out just fine. << this solves it 100%

**Comment by 55Honey** [comment]
https://streamable.com/mkxi97
Footage of the bug happening. IF it happens, it is 100% solved by the slightest bit of movement.

**Comment by FrancescoBorzi** [comment]
> You get the same error if you are /afk which is perhaps why...
> Actually, I think afk is the issue, in the streamable video above, you can just make out the blurry "you are now afk" in the chat windows.

https://github.com/chromiecraft/chromiecraft/issues/77#issuecomment-780297445

**Comment by UltraNix** [comment]
Cannot reproduce it.

**Comment by Yehonal** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/HEAD/src/server/game/Handlers/MiscHandler.cpp#L427

@FrancescoBorzi is it your conf? **PreventAFKLogout**

**Comment by Yehonal** [comment]
setting PreventAFKLogout to 0 will fix your issue, I think that the logout after a timeout is handled exactly in the same way of the manual logout, hence when you are AFK and you click on the button manually that opcode will be called and the PreventAFKLogout won't let you log out. 

I think this config is also a little bit dangerous to use with the WoW client since it expects to be logged out normally when you are AFK, and I have noticed that the character keeps the AFK flag after you start move.

Other clients should handle it correctly

**Comment by UltraNix** [comment]
It's already set to 0 - it's default setting.

**Comment by 55Honey** [comment]
It wasn't 0 on ChromieCraft apparently.

**Comment by FrancescoBorzi** [comment]
it has been set `PreventAFKLogout = 2` on ChromieCraft
