### ISSUE TITLE
[Locales]locales_gossip_menu_option

### ISSUE THREAD

**Issue by Devalenok** [azerothcore/azerothcore-wotlk#456]
The script on locales_gossip_menu_options if anyone needs it!
https://github.com/Devalenok/azerothcore-wotlk/commit/a95aa88b1ad46279cf4380e152ce20c8f21d98c0
![cdd185162a4f](https://cloud.githubusercontent.com/assets/11627014/24744850/776fb3ca-1ac4-11e7-9e5b-b5f57156ab01.jpg)

**Comment by OlegVintage88** [comment]
Nice! Thx

**Comment by ShinDarth** [comment]
thanks for your contribution, however if you think this is something that the master branch should have then [open a pull request](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) please, otherwise post it in our [forum](http://azerothcore.altervista.org/forum/).

**Comment by pak3935** [comment]
Source: https://wowjp.net/forum/121-305912-4252939-16-1483967260

**Comment by Viste** [comment]
@pak3935 i think source is old TC :D if you wish i can found a hash when it changed, so wowjp is not a source 
давай будем честны три икса просто выдрал из старой тринити кусок кода, из-за этого он не может считаться автором ) если хочешь могу даже найти оригинального

**Comment by HeartWell** [comment]
Ты что, он же у нас гуру разраб) Небось все правки с ТС и АС выдаёт как за свои, со словами да я целый день потратил на фикс))

**Comment by Devalenok** [comment]
pak3935, мне без разницы откуда этот скрип или будет другой этого же рода, дело в том что он бы не помешал бы в AC, PS Вы слишком тщеславны !

**Comment by Viste** [comment]
@Devalenok нет, просто мне не нравиться когда какого-то бомжа с wowjp, который просто выдрал кусок кода с тринити выставляют как автора чего-то там и как источник, даже если ты взял это там источник все равно trinity, а не какая-то тупая тема на вовжопе.

**Comment by pak3935** [comment]
@HeartWell а я смотрю что вы до сих пор беспокоитесь за авторские права ваших "уникальных" разработок.

**Comment by pak3935** [comment]
@Viste я написал там автор ?

**Comment by pak3935** [comment]
@Devalenok а вы вообще что тут забыли? Ядро же говно как вы писали
https://github.com/azerothcore/azerothcore-wotlk/issues/357

**Comment by Devalenok** [comment]
# @pak3935, я не знаю этот акка, на вовжп я не бываю редко, мой ник там Macabra
![jp](https://cloud.githubusercontent.com/assets/11627014/24814632/731608b8-1be3-11e7-9638-1f8b4968da04.png)
Но я со словами и скинами выше полностью солидарен, ибо по вашим постам видно кто вы есть !

**Comment by Viste** [comment]
@pak3935 мужик соурс переводиться как исход, источник итп, **то есть источник по твоим словам вовжопа**, _но ты признаешь что тринити_, **но источником пишешь вовжопу**, не вижу логики мужик, без обид. Мне кажется откуда он взял не особо важно в данном случае главное, что взял и помог ребятам, а не отсекся.

**Comment by HeartWell** [comment]
@pak3935 особо умный человек, объясняю для тупых и убогих. В АС указаны ссылки на ТС и Мангос с их копирайтами и даже в ReadMe. Так что сиди на своё вовжопе.
