### ISSUE TITLE
Skill Polearms can be learned before level 20

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4562]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC [Woo Ping](https://wotlkdb.com/?npc=11867) teaches Pole Arms before the player has reached level 20.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Level 20 should be mandatory for Polearms to become available.

##### CURRENT BEHAVIOUR:

NPC [Woo Ping](https://wotlkdb.com/?npc=11867) teaches Pole Arms before the player has reached level 20.
Archibald in UC does not teach it to a player below level 20.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Have an alliance character below level 20.
Step 2 Talk to [Woo Ping](https://wotlkdb.com/?npc=11867) in Stormwind Trade District.
Step 3 Learn Polearms before level 20.

Related Issue: https://github.com/chromiecraft/chromiecraft/issues/78

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/107863143-011d4080-6e52-11eb-94ea-a12fd0d3044b.png)
Simple fix : 
UPDATE `npc_trainer` SET `ReqLevel`='20' WHERE  `ID`=11867 AND `SpellID`=200;

**Comment by FrancescoBorzi** [comment]
hi @T1ti , thanks for your fix. Two tips for you:

1) you can use 3 times ` to better format your code when posting on github (as I edited in your comment):

![image](https://user-images.githubusercontent.com/75517/107865189-4ea2a900-6e64-11eb-9fa0-c1fc54420bb6.png)

2) you can submit it by [creating a new PR](https://www.azerothcore.org/wiki/How-to-create-a-PR). Would you do that, please?
