### ISSUE TITLE
Mage: Amplify magic bug

### ISSUE THREAD

**Issue by ErnestoGonzalezC** [azerothcore/azerothcore-wotlk#4565]
##### CURRENT BEHAVIOUR:

- The spell is applied as a debuff.  -> https://wowgaming.altervista.org/aowow/?spell=43017

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- It should be a benefit

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast the spell

##### EXTRA NOTES:

- The spell works correctly until rank 4, since then it becomes a debuff.

##### OPERATING SYSTEM:

- Windows 10

##### MODULES:

- none

##### OTHER CUSTOMIZATIONS:

- none

**Comment by ErnestoGonzalezC** [comment]
<img src="https://raw.githubusercontent.com/ErnestoGonzalezC/test/main/WoWScrnShot_021321_123718.jpg"></img>

**Comment by Voxstrasza** [comment]
@ErnestoGonzalezC please test this and see if it fixes the issue.

```
DELETE FROM `spell_custom_attr` WHERE  `spell_id`=10170;
```

**Comment by Voxstrasza** [comment]
@ErnestoGonzalezC please test #4567.
