### ISSUE TITLE
Update the creature damage system to CLS, too many issues currently. [$50]

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4570]
##### CURRENT BEHAVIOUR:
After days of looking at damages I was able to pinpoint what was wrong. Note : This is mostly for vanilla, as it's what I work on, I don't know the state of the BC/Wrath content.
So this issue is fairly complex and large and many different issues tie together, it all comes to this, currently many creatures damages are completely wrong.
Because there was a damage column in creature_classlevelstats, I tought the CLS(classlevelstats) system was implemented for damages, **but it's not**. It's currently implemented for armor and health but not for damages.
- Currently the core loads hardcoded min and max dmg values from the database unlike trinitycore which has moved to the CLS system for damages in 2013/2014.  https://github.com/TrinityCore/TrinityCore/commit/3018ff4e6cbed7e3270df7727d1a04e28a901954

- This in addition to the current broken attack speeds values, completely changes the dps creatures should have, see https://github.com/azerothcore/azerothcore-wotlk/issues/4524 .Because with this older system attack speed changes the dps of creatures and this was never considered when updating creature damages values. It simply multiplies flat values by attack speed.

- The DamageModifier has some unknown effect or isn't even implemented at all, I talked about some AC devs about it and they don't know how it works, and if it even works, just that it should be avoided and not touch it.
In this CLS system this column would just be used to multiply the base template value instead.

- Some PRs have been done(and closed) to update damages to blizzlike but were rejected because people had no clue how this modifier works and tought values were too high (sometimes also caused by wrong speed)
See : 
https://github.com/azerothcore/azerothcore-wotlk/pull/2742 (this one is interesting, long covnersation)
https://github.com/azerothcore/azerothcore-wotlk/pull/2773
https://github.com/azerothcore/azerothcore-wotlk/pull/2766

- **Another issue with the pre CLS system and hardcoded min/max values is that they don't scale based off level**, a lvl 37 and 38 of the same creature will have the same dmg, while it should be different based on level like the other stats.
Example with beast lore, screenshot from AC, notice that lvl 57 and 59 creatures have the same dmg : 
![image](https://user-images.githubusercontent.com/40864460/107868251-2bd3bd00-6e83-11eb-9fe7-7f5195958994.png)

- Finally: Too many creature damages are just completely wrong currently. Blizzard uses generic default damage value for most of their mobs and usualy elites have a simple multiplier like *3, it should be standardized.
- +having to manually fill dmg is just awful for modders and custom content :( 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Update to the new CLS system like trinitycore and cmangos, it should fix most of the ongoing issues with creature damages and heavily modernize it.
Here are some commits for it for TC : https://github.com/TrinityCore/TrinityCore/commit/3018ff4e6cbed7e3270df7727d1a04e28a901954
https://github.com/TrinityCore/TrinityCore/commit/cd76d3290719161db1c10b4c82de191db1cef7e8#diff-52a101f6175cb16c8a3879c92fcad3f9f4a263435ead333466a0f0f9428f00ce

##### AC HASH/COMMIT:
03e77ce66f2ccf55a4958faa4f36991ac4e95e2d

**Comment by DanielHackmann95** [comment]
Hello! I wanted to take a look at this but just wanted to make sure I understand the problem/mechanic right:

My understanding of a fix would look like this:

- Load the Min/Max DMG from the creature_classless table instead of all the custom values from creature_template table.
- Remove min/max dmg from the creature_template table and modify the code the table.
- Calculate min/max dmg with the damage_modifier (mulitply it, my understanding is atleast that thats how TC does it)

In Addition, the PRs you linked tried to circumvent the problem by simply modifying all the custom values instead of going by the classless stats, this is not wanted as this just dances around the issue right? 

Do we know if the min/max values in the classless table are correct?

One last thing, the Attack Speed Problem is a different issue right? If I understand it correctly, we calculate the damage right but the values are just off.

**Comment by T1ti** [comment]
> One last thing, the Attack Speed Problem is a different issue right? If I understand it correctly, we calculate the damage right but the values are just off.

It's a different problem with the CLS system, but with the current system it's not because it directly modifies DPS with the min/max dmg.

> Load the Min/Max DMG from the creature_classless table instead of all the custom values from creature_template table.

exactly

> Remove min/max dmg from the creature_template table and modify the code that loads the table.

yes

> Calculate min/max dmg with the damage_modifier (mulitply it, my understanding is atleast that thats how TC does it).

Yep, you can find the calculations in other cores, it's usualy somethnig like max = min *1.5

> In Addition, the PRs you linked tried to circumvent the problem by simply modifying all the custom values instead of going by the classless stats, this is not wanted as this just dances around the issue right?

I haven't really looked into the PRs too much, I think they just implement loading dmg from the CLS ? 

> Do we know if the min/max values in the classless table are correct?

They are 100% correct, Blizz are lazy and use default alues for msot of their creatures(they use the same system)

**Comment by T1ti** [comment]
AttackPowerValue(attType)/ 14.0f * att_speed

Simple overview of the two systems for clarity 
Creature used for the example : 

Creature name | minlevel | maxlevel | attack time
-- | -- | -- | --
Saltwater crocilisk | 35 | 36 | 2000

In game stats with tame beast 
![image](https://user-images.githubusercontent.com/40864460/110220780-37396780-7ec8-11eb-83c0-cba42789a96e.png)




### 1.  Current system(hardcoded values) : 
In creature_template (current db values) : 

mindmg | maxdmg | attackpower
-- | -- | --
50 | 66 | 120

-Level 35 and 36 will always have the same damages.
MINDAMAGE = mindmg * damagemod);
MAXDAMAGE =maxdmg * damagemod);

### 1.  Current system(hardcoded values) : 
Class Level Stat system : 
(creature_classlevelstats table)
level | class | attackpower | damage_base
-- | -- | -- | --
36 | 1 | 120 | 16.2984

The CLS formulas are: 
MINDAMAGE =  (basedamage + (AttackPower / 14)) * dmg_multiplier) * (baseattacktime / 1000);
MAXDAMAGE =  ((basedamage * 1.5) + (AttackPower / 14)) * dmg_multiplier) * (baseattacktime / 1000);

So min damage = (16.2974 +(120 / 14) * (2000 / 1000) = 49.739, so pretty much the same as the old value (50)
max damage is the same but you multiply base_damage by *1.5
((16.2974*1.5) +(120 / 14) * (2000 / 1000) = 66.03 Again, exactly the same

Note : I have no idea how attack power works in the current formula, I'm not even sure if attack power is dynamically calculated at all. I'm guessing the hardcoded values account for the attack power ? That probably means attack power reductions are not working properly currently and use some ahck fix to reduce dmg by a %

**Comment by claudiodfc** [comment]
Why do you divide AP by 14 and why do you multiply basedmg by 1.5?

**Comment by claudiodfc** [comment]
Can you message on discord @T1ti ? Drop a message on dev-core
