### ISSUE TITLE
Mobs casting daze when fighting face to face

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4571]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/61

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

When fighting a mob, specifically I was in tirisfal glades and anything I fought was doing it, I am getting dazed cast on me.
https://ibb.co/Rg1gXT5 combat log of it happening

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dazed shouldn't be cast during a fight face to face...should be cast when running away with your back exposed

##### CURRENT BEHAVIOUR:

I cast a spell on a mob to make it run to me while I stand still. It gets within melee range and combat begins face to face with the mob. Within 5 seconds the mob will cast daze on me https://bit.ly/3oXdRXv (dazed spell) and I am still just face to face with the mob, not moving, and yet it will cast daze on me which is used when running away from a mob and having your back exposed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Engage a mob in Tirisfal Glades (this bug could be server wide but I'm new and don't know)
2. Have the mob come to you so you know nothing else is happening (cast a spell on it to make it approach you)
3. Don't move at all and just fight the mob, it will cast daze on you for no reason.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by JamesGent** [comment]
https://classic.wowhead.com/npc=1934/tirisfal-farmer#abilities

Tirisfal Farmers have an ability called "daze". Is it all mobs or just this mob?

**Comment by Stifler82** [comment]
> https://classic.wowhead.com/npc=1934/tirisfal-farmer#abilities
> 
> Tirisfal Farmers have an ability called "daze". Is it all mobs or just this mob?

I'm no sure about it(if all NPCs have that spell), but [Tirisfal Farmers](https://classic.wowhead.com/npc=1934/tirisfal-farmer#abilities) have that spell/ability, that then, it will change in Cataclysm patch 4.0.3 with spell [Dirt Toss](https://www.wowhead.com/spell=80382/dirt-toss)
what i'm sure is that in the patch notes: [World of Warcraft Client Patch 3.3.0: Fall of the Lich King](https://www.toxicgaming.us/wow/wrath-patch-notes/)
there's wrote:
`Dazed: Creatures attacking a player from behind can no longer cause players level 1-5 to be dazed, and have a reduced chance to cause players level 6-10 to be dazed.`

And that NPCs are in that **"Range Level"**

So something definitely needs to be **"fixed"**.

**Comment by Stifler82** [comment]
Fixed!
-
- **Video Test:** [Mobs casting daze](https://youtu.be/feU1B9hq_-o)

**Comment by T1ti** [comment]
Daze should be a global mechanic. Or are those creature specific daze spells ?
https://vanilla-wow-archive.fandom.com/wiki/Daze 
https://wow.gamepedia.com/Daze
"All mob creatures have a chance to daze on each melee hit, ranging from 0% to a maximum 40%. Chance to daze is a function of player level, creature weapon skill and player base defense skill."

I think the daze spells shown on wowhead are just bugs, they use some tool to detect creature casts and some daze pells are displayed, or those mobs have it in addition to the global daze to have like a guarenteed daze ?

I did some testing in game and I couldn't get a single mob to daze me, is the global daze mechanic not implemented ?

**Comment by Stifler82** [comment]
> Daze should be a global mechanic. Or are those creature specific daze spells ?
> https://vanilla-wow-archive.fandom.com/wiki/Daze
> https://wow.gamepedia.com/Daze
> "All mob creatures have a chance to daze on each melee hit, ranging from 0% to a maximum 40%. Chance to daze is a function of player level, creature weapon skill and player base defense skill."
> 
> I think the daze spells shown on wowhead are just bugs, they use some tool to detect creature casts and some daze pells are displayed, or those mobs have it in addition to the global daze to have like a guarenteed daze ?
> 
> I did some testing in game and I couldn't get a single mob to daze me, is the global daze mechanic not implemented ?

@T1ti 
I will answer you in order of your questions:
- You're probably getting a little confused.
   the "Daze" you are talking about is a "Global Mechanics" with a duration of time of 5sec,
   instead the "Daze" of these mobs, is a "Daze"(Different) and has a duration of time of 9sec,
   so to answer to your question, yes, it is an (additional) Daze.

Instead, to answer your second question:
- I have no idea if the Daze (Global) is implemented, you should ask @FrancescoBorzi or @Helias.

**Comment by necropola** [comment]
After doing some further investigation in https://github.com/chromiecraft/chromiecraft/issues/223#issuecomment-802645816 I'd say that spell=13496 (10s daze from anywhere) should be removed from creature SAI entirely and not only restricted to application from behind. All creatures already have access to spell=1604 (3s daze from behind) via core functionality.

It's simply not reasonable that some random low level creatures (many are in the 5-8 level range) have access to another daze (10s as opposed to the core daze of 3s) which is lacking the noob protection of the core daze and applies the spell (aura) of the [Mug O' Hurt](https://wotlkdb.com/?item=4090) proc.
