### ISSUE TITLE
Feature: Import more smart_scripts event_type from TC to make them more compatible

### ISSUE THREAD

**Issue by Zoidwaffle** [azerothcore/azerothcore-wotlk#4572]
**Describe your feature request or suggestion in detail**

Certain smart_script events exist in TC branch 3.3.5 while not on AC.

While there are differences between the projects, a similarity to some extend, makes it easier to port SmartAI fixes between the projects.

At the time of writing, the only thing needed should be `SMART_EVENT_SUMMONED_UNIT_DIES  = 82` (types 78-81 are not there either, but they are just placeholders - they should be imported as well).

Of course, this is only relevant if the TC types are not already covered in the AC specific event types with numbers 100+ (and this is not the case here).

If type 82 is implemented, it should be possible to port some TC SAI over that fixes at least 1 quest and cleans up the code in zone_silverpine_forest.cpp (and hopefully more, this event is used in 6 places).

[TC documentation for event_type](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130108/smart+scripts) vs [AC documentaion for event_type](https://www.azerothcore.org/wiki/smart_scripts) (Numbers 78-81 are the relevant ones)

**Describe a possible solution to your Feature or Suggestion in detail**

Please see TC branch 3.3.5 and then the relevant files are probably all in ./src/server/game/AI/SmartScripts/.

**Additional context**

Edit: Just for the record, I looked into this myself. But I'm not a C++ developer and I'm not sure how this should be done properly.

**Comment by Voxstrasza** [comment]
I think https://github.com/azerothcore/azerothcore-wotlk/issues/4485 falls into this category as well.  The TC fix is not compatible with our core as of now

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/002e62d689b67c593c57a3c8595a0c8b27ad7a76
