### ISSUE TITLE
Gossip menu not localized

### ISSUE THREAD

**Issue by grabthar** [azerothcore/azerothcore-wotlk#4573]
Gossip menu not localized

##### CURRENT BEHAVIOUR:

Npc with no OptionbroadcastTextId are not localized however they should receive the locale.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All gossip menu options localized

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a npc (sql)
2. Create a gossip menu / gossip menu option / and the locale.  Do not create broadcastText/box
3. test -> not localized menu option / box

##### EXTRA NOTES:

The bug is in Player.cpp Player::PrepareGossipMenu()
Replace for both optionBroadcastText, boxBroadcastText
sObjectMgr->GetGossipMenuItemsLocale(MAKE_PAIR32(menuId, menuId))
To:
sObjectMgr->GetGossipMenuItemsLocale(MAKE_PAIR32(itr->second.MenuID, itr->second.OptionID))
With this npc are correctly translated

##### OPERATING SYSTEM:

Windows 10

**Comment by LukasVolgger** [comment]
Confirm.
