### ISSUE TITLE
[DB] Wrong position for Copper Ore

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4574]
##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

GameObject: [Copper Ore](https://wotlkdb.com/?item=2770) at 47.86 19.55 in Durotar spawns inside a rock and thus can not be looted.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Placement ~6m to the North would make it lootable.

##### CURRENT BEHAVIOUR:

GameObject: [Copper Ore](https://wotlkdb.com/?item=2770) at 47.86 19.55 in Durotar spawns inside a rock and thus can not be looted.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
```
SELECT * FROM `acore_world`.`gameobject` WHERE `guid`=4788;
SHOW TABLE STATUS LIKE 'gameobject';
```

![image](https://user-images.githubusercontent.com/71938210/107888882-86b2f600-6f0f-11eb-80f2-76d00371ac34.png)
![image](https://user-images.githubusercontent.com/71938210/107888925-dc879e00-6f0f-11eb-9f65-8dbc17aeab32.png)

Related: https://github.com/chromiecraft/chromiecraft/issues/80

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f4e317f518fdc96b964ecd9b2f65cca9619577a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Voxstrasza** [comment]
ok, i will move it
