### ISSUE TITLE
Escort Quest NPCs wipe/clear all buffs at the end of combat.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#4581]
Escort Quest NPCs wipe/clear all buffs at the end of combat.

##### CURRENT BEHAVIOUR:

Quest NPCs are pretty weak so I like to buff them during escorts.

If an escort NPC gets into a fight, as soon as combat ends they lose all buffs (including self-buffs).

![WoWScrnShot_021521_164706](https://user-images.githubusercontent.com/61194190/107975158-92ee9000-6faf-11eb-8c26-c8c873caaaff.jpg)

![WoWScrnShot_021521_164702](https://user-images.githubusercontent.com/61194190/107975164-9550ea00-6faf-11eb-9c75-a55bfdbc733b.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Escort quest NPCs should maintain buffs until they expire (I think, not 100% sure).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start any escort quest. (Recommended test same time as issue #4580)
2. Buff the escort NPC.
3. Get into combat.
4. End combat.
5. Check buffs.

##### AC HASH/COMMIT:

ChromieCraft latest.

AzerothCore rev. 21f828847f42 2021-02-14

**Comment by Kitzunu** [comment]
void EscortAI::EnterEvadeMode(EvadeReason /*why*/)
{
    me->RemoveAllAuras();

**Comment by Kitzunu** [comment]
The question is, as you mentioned, is this intentional or not

**Comment by ChromieCraftServer** [comment]
what's the status of this?
