### ISSUE TITLE
Rocklance is hiding below the world.

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4582]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/37
Related to this https://github.com/chromiecraft/chromiecraft/issues/39, with the same issue 

##### SMALL DESCRIPTION:
Level 17 silver elite centaur, Rocklance, is hiding under the ground and clips through when you get too close.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Rocklance should be visible above ground before engaging.

##### CURRENT BEHAVIOUR:
From a distance the oasis looks clear, but when I approach suddenly Rocklance comes up out of the ground and aggros me.

From a distance: 
![No mob in sight](https://user-images.githubusercontent.com/78349628/106941692-c7796680-66e8-11eb-91fa-fb13637334d1.png)

As I enter the oasis:
![Rocklance appears through the earth](https://user-images.githubusercontent.com/78349628/106941715-d06a3800-66e8-11eb-8689-ffff2d377920.png)

##### STEPS TO REPRODUCE THE PROBLEM:
1. I suppose you could either teleport to Rocklance himself, or to the Stagnant Oasis and then run southeast.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b905ce8c354b7cfac899ac3ab67209d2995b4de2

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by r0m1ntik** [comment]
Confirm 
![Снимок экрана 2021-02-17 в 0 13 14](https://user-images.githubusercontent.com/40755539/108133512-fd3d2880-70b4-11eb-85d0-3882e3142e8a.png)
