### ISSUE TITLE
Instant Statue Pedestal doesn't pose you

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4583]
##### CURRENT BEHAVIOUR:

No pose.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should be in a pose.

https://www.wowhead.com/item=54212/instant-statue-pedestal#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Add item 54212
2. Use it
3. Observe lack of flexing

##### AC HASH/COMMIT:

ChromieCraft latest
AzerothCore rev. 21f828847f42 2021-02-14 19:27:49

**Comment by r0m1ntik** [comment]
For first use can confirm, but second use work fine.
![Снимок экрана 2021-02-16 в 21 05 07](https://user-images.githubusercontent.com/40755539/108115728-d2de7180-709a-11eb-910f-b1ebbcba9b97.png)

**Comment by Kitzunu** [comment]
That's very weird, but I can confirm r0mntik's conclusion as well.

**Comment by JamesGent** [comment]
Once again I am cursed. I've used it 25 times and haven't posed yet. I'm happy to close it though as it seems like it's working (I'm just cursed).
