### ISSUE TITLE
[Log] Logging apparently not working

### ISSUE THREAD

**Issue by chakuze** [azerothcore/azerothcore-wotlk#459]
**Description**:
Debug logs not written to console window nor log file.

**Current behaviour**:
Worldserver.conf file edited the correct way:
LogLevel=3
LogFile="Server.log"
LogFileLevel=3
DebugLogMask=1048576
CharLogFile="Char.log"

**Expected behaviour**:
Worldserver console should display many infos (debug log level) and additionally information concerning the loot (see debug mask).

**Steps to reproduce the problem**:
Set settings like written above.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue)
3.3.5 (azerothcore-wotlk)

**Operating system**:  
MacOS

**Modules**:  Are you using modules?
No, I do not.

**Other Customizations**: Are you using any core/db patches or other customizations?
No, everything standard.

**Comment by Yehonal** [comment]
Shoud be fixed starting from: https://github.com/azerothcore/azerothcore-wotlk/commit/c1586e0d995de5dd278b0acfe410acf66f6c2c6d
