### ISSUE TITLE
'Chemical Wagon'  zhCN translation error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4598]
CURRENT BEHAVIOUR:
'Chemical Wagon'  zhCN translation error

AC HASH/COMMIT:
b905ce8

OPERATING SYSTEM:
ubuntu 18.04

This is a fixed SQL:
```SQL
UPDATE` `world`.`gameobject_template_locale` SET `name` = '药剂车' WHERE `entry` = '201716' AND `locale` = 'zhCN';

**Comment by r0m1ntik** [comment]
药剂车 confirm
![Снимок экрана 2021-02-18 в 13 19 16](https://user-images.githubusercontent.com/40755539/108356072-ee0cc680-71eb-11eb-92e7-415ec3648910.png)
