### ISSUE TITLE
[raid]Archimonde's BUG

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4599]
##### CURRENT BEHAVIOUR:
BUG1:Archimonde health reduced to 10% will enter the plot, and then the elf will go over and explode, If the surviving player leads Archimonde to move, Archimonde will recover health
BUG2:When Archimonde health reaches 10%, only the current target of Archimonde will get 'protection of Elune' buff (id = 38528)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When Archimonde's health value reaches 10%, all the living players will get a 'protection of Elune' buff (id = 38528). One minute later, either the players kill him or the ELF's explosion will kill Archimonde

##### STEPS TO REPRODUCE THE PROBLEM:
1. update to https://github.com/azerothcore/azerothcore-wotlk/commit/d7acacfac01383899ff36c69bde016d51851260b
2. .go c 39927(We need to kill other bosses)
3. Attack Archimonde health to 10%
4. Then watch the story

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/d7acacfac01383899ff36c69bde016d51851260b

##### OPERATING SYSTEM:
ubuntu 18.04
##### MODULES:
none

**Comment by Voxstrasza** [comment]
update your core, https://github.com/azerothcore/azerothcore-wotlk/pull/4509 should have fixed it

**Comment by mpfans** [comment]
> update your core, #4509 should have fixed it

d7acacfac01383899ff36c69bde016d51851260b After #4509

**Comment by Voxstrasza** [comment]
@Footman @Yehonal

**Comment by mpfans** [comment]
> update your core, #4509 should have fixed it

d7acacfac01383899ff36c69bde016d51851260b after #4509

**Comment by w5860363** [comment]
@Voxstrasza Confirmation of problem recurrence
