### ISSUE TITLE
[Request] Transmog

### ISSUE THREAD

**Issue by rynnokung** [azerothcore/azerothcore-wotlk#46]
[Request] Transmog
##

**Comment by Draztal** [comment]
I also need the Transmog

**Comment by xnova214** [comment]
me too :)

**Comment by DevRival** [comment]
Here successful completion, remained a bit and can will do PR)

[One](http://i042.radikal.ru/1608/f7/13f9a7398571.jpg)
[Two](http://s019.radikal.ru/i633/1608/4c/c7bf649b03a4.jpg)
[Three](http://s019.radikal.ru/i624/1608/d1/5bba579430e5.jpg)
[Four](http://i053.radikal.ru/1608/dc/cf4a761973a6.jpg)
[Five](http://s018.radikal.ru/i503/1608/00/44fa8489688c.jpg)

**Comment by ShinDarth** [comment]
@DevRival that's great, can you make a [module](https://github.com/azerothcore/azerothcore-wotlk/wiki/Create-a-Module) instead ?

**Comment by DevRival** [comment]
@ShinDarth i try)

**Comment by Draztal** [comment]
DevRival help me to put Transmog

**Comment by Yehonal** [comment]
I've a working transmog, but i won't publish it as a patch, we've to create a module ...and to do it we need some more ScriptMgr functions that we can add asap

**Comment by DevRival** [comment]
Horror more modules ..

**Comment by Yehonal** [comment]
Do you prefere conflicts with horror patched core? What are you talking
about?

Il 29/Ago/2016 12:38, "Rival" <notifications@github.com> ha scritto:

**Comment by DevRival** [comment]
You go on difficult paths , why module transmogrification if you can get a folder custom?))

**Comment by ShinDarth** [comment]
On the contrary: modularity makes the software better, easier to maintain and understood.

https://en.wikipedia.org/wiki/Modular_programming

Also AzerothCore modules are very easy to install.

**Comment by Yehonal** [comment]
Rival modules can contain script, moreover you can:

Create sql that will be assembled by our script automatically

Create .conf file that can be used for custom conf

All this things are required by transm system

Il 29/Ago/2016 14:53, "Shin" <notifications@github.com> ha scritto:

**Comment by DevRival** [comment]
It is your right, just when people use your core and end up losing out scripts for new modules or reconstruction of the core, it will hurt. I used your kernel , and I can say that a lot of problems in terms of custom. Do not you judge me, you're doing a great job,  good luck to you in this. Sorry my bad ENGLISH.

**Comment by Yehonal** [comment]
@DevRival you're out of topic here, i've created a topic to reply you, please continue this discussion here: http://azerothcore.altervista.org/forum/viewtopic.php?f=6&t=11

**Comment by talamortis** [comment]
Any news on this?

**Comment by xnova214** [comment]
Any news?

**Comment by cshaaa** [comment]
Any  news?😊

**Comment by DevRival** [comment]
No news)

**Comment by tea91** [comment]
https://bitbucket.org/pak3935/sunwellcore/commits/b05c129500b026ab8b63fe66ac61a9a9c5b1e27f

Is it not work?

**Comment by talamortis** [comment]
@tea91 i have a working transmogrifaction but its not a modual.

**Comment by Yehonal** [comment]
Transmog module is now available here:

https://github.com/azerothcore/module-transmog   

just install under modules/  folder , re-run cmake and recompile ( don't forget to import sql files of the module )

This is only compatible with latest AC/master revision
