### ISSUE TITLE
Maghar hunter (58673) is lvl 62 and summons a mob lvl 23

### ISSUE THREAD

**Issue by b4rib2z99** [azerothcore/azerothcore-wotlk#460]
**Description**: maghar hunter (creature_template entry = 58673) is lvl 62 and summons a mob lvl 23

**Expected behaviour**: I suppose he should summon a lvl62 mob since it's in outland.

**Steps to reproduce the problem**:

1. go to the mag'har hunter (.tele maghar)
2. look at the mob he has

**Branch(es)**: master

**AC hash/commit**:  c92d040

**Operating system**:  linux

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by starrheld** [comment]
Name of the summoned mob?

**Comment by b4rib2z99** [comment]
Tamed ravager

Apparently Starrheld doesn't have this bug, anybody has it? If nobody has it, I'll close the issue. Not like a big deal anyway (just requires one line of sql) but I wonder why I got this bug.
