### ISSUE TITLE
Quest - Blackfathom Villainy has wrong required level

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4602]
Original Issue chromiecraft/chromiecraft#85

##### SMALL DESCRIPTION:
Argent Guard Thaelrid from Blackfathom Deeps dungeon does not have the quest available for alliance players (didn't checked for horde)

Quest: [Blackfathom Villainy](https://web.archive.org/web/20100802000856/https://wowhead.com/quest=1200/blackfathom-villainy) 
NPC_Start: [Name Argent Guard Thaelrid](https://classic.wowhead.com/npc=4787/argent-guard-thaelrid#starts) 
NPC_End: [Name Dawnwatcher Selgorm](https://classic.wowhead.com/npc=4783/dawnwatcher-selgorm) 

[Blackfathom Deeps](https://classic.wowhead.com/blackfathom-deeps)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Level required for quest should be 18 and be given by Argent Guard Thaelrid

##### CURRENT BEHAVIOUR:
Not having any quest available when you approach him 

Quest: [Blackfathom Villainy](https://classic.wowhead.com/quest=1200/blackfathom-villainy) 
NPC_Start: [Name Argent Guard Thaelrid](https://classic.wowhead.com/npc=4787/argent-guard-thaelrid#starts) 
NPC_End: [Name Dawnwatcher Selgorm](https://classic.wowhead.com/npc=4783/dawnwatcher-selgorm) 

[Blackfathom Deeps](https://classic.wowhead.com/blackfathom-deeps)

##### STEPS TO REPRODUCE THE PROBLEM:
Enter Blackfathom Deeps (original issue used RDF)
Reach Argent Guard Thaelrid location - underwater cave after the first boss
There isn't any quest available from the NPC

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f4e317f518fdc96b964ecd9b2f65cca9619577a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by r0m1ntik** [comment]
For **Alliance**:
You need complete [In Search of Thaelrid](https://classic.wowhead.com/quest=1198/in-search-of-thaelrid) and after u can get [Blackfathom Villainy](https://classic.wowhead.com/quest=1200/blackfathom-villainy)
![Снимок экрана 2021-02-18 в 17 07 45](https://user-images.githubusercontent.com/40755539/108385328-d8a79480-720b-11eb-852a-68507c311c3a.png)
For **Horde**:
Only 1 quest [Blackfathom Villainy](https://classic.wowhead.com/quest=6561/blackfathom-villainy)

Can't confirm this isssue

**Comment by FrancescoBorzi** [comment]
@nicoaravena

**Comment by Zoidwaffle** [comment]
If you are Horde, you can pick up the quest instantly.

`.go c id 4787`

And talk to the nelf on the ground.

**Comment by nicoaravena** [comment]
My bad, miss understood an answer.
