### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#461]
CLOSE MY WRONG!!

**AC hash/commit**:  Latest AC

**Operating system**:  se7en

**Modules**:  Are you using modules? anticheat - transmog

**Other Customizations**: Are you using any core/db patches or other customizations?NO!

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by starrheld** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5bf90b33388bfabb3f7a434980021083d9911a36

**Comment by Franklampardst** [comment]
@starrheld  Yea i found that but we not have authsession to fix this problem need change codes . if we know which line make this problem can help to fix it . but i really don't know which line make this flood!

**Comment by starrheld** [comment]
@Franklampardst True. 
AuthSocket.cpp (AC) / AuthSession.cpp (TC)

**Comment by JunkyBulgaria** [comment]
https://gist.github.com/JunkyBulgaria/eb38f794f3af2e7795a3c71f4dc5a25b

**Comment by Franklampardst** [comment]
@JunkyBulgaria Tnx but Not Working :(

**Comment by JunkyBulgaria** [comment]
what opcode do they spam, if it's tcp flood you can't protect your self without a firewall

**Comment by Franklampardst** [comment]
@JunkyBulgaria i set firewall such as hardware or software but we must update source codes from https://github.com/TrinityCore/TrinityCore/commit/5bf90b33388bfabb3f7a434980021083d9911a36 and update source to fix this problem latest trinitycore resolved this issue

**Comment by Franklampardst** [comment]
this really simple with ignore in firewall . my fault
