### ISSUE TITLE
Divine Protection does not reduce fall damage as it should

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#4610]
Divine Protection does not reduce fall damage as it should

##### CURRENT BEHAVIOUR:

Divine Protection does not reduce fall damage as it should

https://shadowlands.wowhead.com/forums&topic=48087/divine-protection-and-falling

https://vanilla-wow-archive.fandom.com/wiki/Divine_Shield

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Divine Shield prevents all damage, including (unlike most other bubbles of other classes) falling damage, and even drowning damage. It is not uncommon for a Paladin to leap off a high cliff or despawn their flying mount in the air and bubble before landing, preventing damage or death. Hand of Protection does exactly the same thing for falling damage, and a Paladin with good timing may bubble himself and a party member."

##### STEPS TO REPRODUCE THE PROBLEM:

1. Jump from very high without divine protection.
2. Observe damage.
2. Cast Divine Protection
2. Jump from very high.
3. Observe damage.

##### EXTRA NOTES:

I just tried to get the "Going Down" fall achievement and I took 90% of my health (180% if Divine Shield was working) without getting the achievement.

![WoWScrnShot_021921_140252](https://user-images.githubusercontent.com/61194190/108514251-92117300-72bb-11eb-94b9-7df0f6b144c7.jpg)

##### AC HASH/COMMIT:

ChromieCraft latest.
AzerothCore rev. 21f828847f42 2021-02-14 19:27:49 +0000 (master branch) (Unix, RelWithDebInfo)

**Comment by r0m1ntik** [comment]
Confirm
[75813d7](https://github.com/azerothcore/azerothcore-wotlk/commit/75813d7a23223b9dee07c7b7df9469be05fedfb9)

**Comment by Helias** [comment]
it seems a hack, but it can be valid if we have no alternative

**Comment by FrancescoBorzi** [comment]
@r0m1ntik can you please send a PR with it?
