### ISSUE TITLE
Milling a stack of 5 herbs crashes the server

### ISSUE THREAD

**Issue by Cinnamohn** [azerothcore/azerothcore-wotlk#4611]
##### CURRENT BEHAVIOUR:

When you mill a stack of 5 herbs, the server will crash.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The server should not crash.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .learn 45357
2. .additem 765 5
3. Cast Milling on the Silverleaf.

##### EXTRA NOTES:

Any stack larger than 5 works just fine. Attempting to mill a stack smaller than 5 outputs the correct error. Prospecting is also fine.

I believe it broke sometime in the last 4 months, as I remember it working before I updated my core a couple weeks ago.

##### AC HASH/COMMIT:

576f358

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by r0m1ntik** [comment]
Can't confirm on [e843425c4ac30ffd7f02845efbd80ddf1dc7100b](https://github.com/azerothcore/azerothcore-wotlk/commit/e843425c4ac30ffd7f02845efbd80ddf1dc7100b)

**Comment by Helias** [comment]
@Cinnamohn are you using any custom script, patches or modules?

**Comment by Cinnamohn** [comment]
Updated to the most recent commit and it's still happening, although i didn't expect anything within the last few days to change it. I have both a heavily modded core/client and a fresh core/client with no additions. Occurs on both setups.

I did some more testing, and it's actually not related to herbs and milling exclusively. I can replicate it with ore and prospecting as well.

If I start with a clean inventory and then either use the .additem command, purchase from a vendor, or gather from nodes out in the world to obtain a fresh stack of an herb or ore (any amount), and then add to it and mill/prospect that stack until it's removed from my inventory (pretend the stack is a multiple of 5), it's removal crashes the server and remains upon restart. If I attempt to mill/prospect that same stack after a crash, it'll crash again.

However, if I logout after obtaining the first bit of that "corrupted" stack, the stack is then "cleansed" and I can freely add to it and mill/prospect it until it's gone. I can also take the corrupted stack and trade it to another character to cleanse it. If I receive a fresh stack in the mail, it's safe to add to and use.

I can't replicate this with the standard enchanting, but I imagine I could if I created a stacking disenchantable item.

**Comment by Cinnamohn** [comment]
I think I've narrowed it down even more. If I wait for the stack to be saved to the \characters\item_instance database, I can safely mill/prospect it away. If I do it before then, it crashes. Adding, purchasing, and gathering don't immediately update it, however logging out, trading, and grabbing from the mailbox do, which would explain the so called "cleansing."

**Comment by FrancescoBorzi** [comment]
@Cinnamohn are you on a 100% clean AzerothCore without any modules or other kinds of customisations?

**Comment by Cinnamohn** [comment]
It is a brand new, fresh core with the default client. Set it up on the 7th, updated it to the most recent commit today. All it has is 2 accounts and 2 characters that have done nothing other than test this bug.

**Comment by T1ti** [comment]
Works fine for me

**Comment by Cinnamohn** [comment]
Since I can take a backup of my core from a year ago and replicate it, I'm going to assume I somehow broke something when I reinstalled some stuff to update the core this month, as I've tried every obvious solution imaginable. Going to close this and figure it out when I have more time.
