### ISSUE TITLE
Westfall woodworker out of place

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4613]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/90

##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE: 

1-19

##### SMALL DESCRIPTION:

The worker out of place in Westfall - Sentinel Hill 

NPC: [Westfall Woodworker](https://wowgaming.altervista.org/aowow/?npc=6670)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC shouldn't be there.

##### CURRENT BEHAVIOUR:

![sentinel hill](https://user-images.githubusercontent.com/79286559/108433089-7627b600-7256-11eb-8673-3a2924fd36b0.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
i posted it, but i already fixed it, now i will commit it.

**Comment by Stifler82** [comment]
https://user-images.githubusercontent.com/1884642/108538967-4bca0d00-72d7-11eb-80ab-2051a5500ede.mp4

**Comment by FrancescoBorzi** [comment]
@Stifler82 good job! Just one note: do not close the issue until the PR that fixes it has been merged to the master branch.

When you open a PR that fixes an issue, just add `- Closes link-to-the-bug-report` so github will automatically close the bug once the fix is merged ;)
