### ISSUE TITLE
Line of Sight casting [$25]

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4620]
Original issue: chromiecraft/chromiecraft#97
Related to: azerothcore/azerothcore-wotlk#4220

##### SMALL DESCRIPTION:

  In certain cases (like a slightly uneven ground) targeted spells can be cast without the "Target not in line of sight" error.
https://www.youtube.com/watch?v=wshUR8yYYYk&feature=youtu.be

_(The same issue as https://github.com/chromiecraft/chromiecraft/issues/16
Creating a new thread since the old one has been flagged as fixed and closed)_

##### EXPECTED BLIZZLIKE BEHAVIOUR:

  Targeted spells should either succeed to cast or be cancelled with a "Target not in line of sight" message. 

##### CURRENT BEHAVIOUR:
   In certain places targeted spells can be considered as casted despite not being in the line of sight.
Such spell still drains mana, but has no effect on the enemy.
##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 - Go to the Shadowthread Cave in Shadowglen (Teldrassil)
Step 2 - Stand on the lower ground near entrance
Step 3 - Cast a spell on the spider that is slightly above

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
I tested again on latest commit of AC and is happening, tested other places that I knew this happened before but is only here.

**Comment by Stifler82** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by Stifler82** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by Stifler82** [comment]
@FrancescoBorzi @Yehonal @Helias 

The problem has not been solved yet

**Video Test:** [Line of Sight](https://youtu.be/sq5tPhLb3c4)

**Comment by Helias** [comment]
comment the related PR and tag @UltraNix

**Comment by UltraNix** [comment]
Tested on local - still works okay.
