### ISSUE TITLE
[Rogue] Spell 'Premeditation' removes eating (sit and aura)

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#4623]
##### CURRENT BEHAVIOUR:

If your opponent is sitting, you can knock his food down.
![Снимок экрана 2021-02-21 в 23 46 01](https://user-images.githubusercontent.com/40755539/108641408-56cf9980-749f-11eb-8dce-f518eae73782.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Shouldn't cancel food

##### STEPS TO REPRODUCE THE PROBLEM:

1. Log to 2 sessions (1 rogue and any class)
2. Put duel (for example)
3. Eating and rogue use '[Premeditation](https://wotlkdb.com/?spell=14183)'

##### AC HASH/COMMIT:

[8dbdffa](https://github.com/azerothcore/azerothcore-wotlk/commit/8dbdffab9282e34b1bcf5e1d670fa5743f81f720)

##### OPERATING SYSTEM:

Ubuntu 18

**Comment by claudiodfc** [comment]
**Tested on AzerothCore rev. 5d1f644552db**

Test executed:

1. Character 1 started eating food "4592" - Longjaw Mud Snapper
2. Character 2 Cast Premeditation while in Stealth
3. Character 1 stops eating

Status report: **Bug confirmed**
---
![WoWScrnShot_030321_182421](https://user-images.githubusercontent.com/54484196/109854004-72c8fd00-7c4e-11eb-99f4-f27fdcf4916d.jpg)
![WoWScrnShot_030321_182429](https://user-images.githubusercontent.com/54484196/109854012-73619380-7c4e-11eb-8061-0ff59507d9ea.jpg)
