### ISSUE TITLE
[Warrior] Can't use shield on disarm

### ISSUE THREAD

**Issue by r0m1ntik** [azerothcore/azerothcore-wotlk#4638]
##### CURRENT BEHAVIOUR:

When a warrior receives disarm, he cannot put on a shield to knock down a cast or use a reflex. You need to wait for the disarm to sleep. It should not be.

Video: [not work](https://streamable.com/2r0j39)
Video [Work](https://streamable.com/ahuf59)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create war, add shield
2. Use disarm on warm
3. Try to use reflect or just equip shield

##### AC HASH/COMMIT:

[a411586](https://github.com/azerothcore/azerothcore-wotlk/commit/a4115862de1cd6f37b70969c87df79f327457dd1)

##### OPERATING SYSTEM:

Ubuntu 18.04

**Comment by lineagedr** [comment]
```
EXPECTED BLIZZLIKE BEHAVIOUR:
```
Shows a clip from some random pserver -_-

**Comment by r0m1ntik** [comment]
> ```
> EXPECTED BLIZZLIKE BEHAVIOUR:
> ```
> 
> 
> Shows a clip from some random pserver -_-

yes you need to find a video on the internet

**Comment by lineagedr** [comment]
@r0m1ntik https://www.youtube.com/watch?t=247&v=rNVoMGRg4QE&feature=youtu.be
