### ISSUE TITLE
Misplaced Plaque in Stormwind (Archbishop Alonsus Faol)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4642]
Misplaced Plaque in Stormwind (Archbishop Alonsus Faol)

##### CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/61194190/109009875-02970600-76a7-11eb-8554-bf955e7df630.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not floating plaque (as it is invisible from the back).

https://classic.wowhead.com/object=177199/archbishop-alonsus-faol

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stormwind Cathedral District
2. Look at fountain
3. 

##### AC HASH/COMMIT:

AzerothCore rev. a4115862de1c 2021-02-21 22:12:25 +0100 (master branch) (Unix, RelWithDebInfo)

**Comment by Si1ker** [comment]
Don't know how it should be placed.. 😕 

![image](https://user-images.githubusercontent.com/61223313/110198678-d4899280-7e19-11eb-8d5f-4c4183649ad0.png)


The only picture available is not so clear:
![image](https://user-images.githubusercontent.com/61223313/110198686-e66b3580-7e19-11eb-938f-0c4434690223.png)
source: https://classic.wowhead.com/object=177199/archbishop-alonsus-faol#same-model-as
