### ISSUE TITLE
(Young) Moonkin don't have Moonfire

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4646]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/106

##### ISSUE: FACTION SIDE:
![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
[Moonkin](https://wotlkdb.com/?npc=10158) and [Young Moonkin](https://wotlkdb.com/?npc=10159) should not be able to cast [Moonfire](https://wotlkdb.com/?spell=8921). They don't even have a Mana bar but they spam this ability from range and in melee.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
They only should have melee attacks.

##### CURRENT BEHAVIOUR:
See **Small Decsription**

##### STEPS TO REPRODUCE THE PROBLEM:
Visit the Moonkin cave near Auberdine, e. g. as part of the Night Elf Druid Bear Form quest, and fight them.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7ec204943a3080071e0f1d7b7d18e10cbc4d1918

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
Normal moonkins don't have this issue, only youngs do.
Too lazy to make a PR : 
DELETE FROM smart_scripts WHERE entryOrGuid = 10159 AND source_type = 0;
UPDATE `creature_template` SET `AIName`='' WHERE  `entry`=10159 ;

**Comment by Zoidwaffle** [comment]
@T1ti - I made a PR for you :+1:
