### ISSUE TITLE
Hunters shouldn't be able to auto while channeling abilities

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4652]
##### CURRENT BEHAVIOUR:
you can just right click or cast auto attack while channeling and it will auto attack while channeling an ability when engaging combat.
If combat was already engaged, auto attacks will still be turned on and it will just keep auto shooting while casting abilities
https://i.gyazo.com/4f486c4b5bae17a43adfdd853981a81e.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You shouldn't be able to auto attack while casting abilities

##### STEPS TO REPRODUCE THE PROBLEM:
- cast an hunter ability with a cast time like Steady Shot, see if you can auto during the channel. By either turning on attack during the channel, or having turned it on before

##### AC HASH/COMMIT:
b9e132a9416197a78d72e08780c4cead2d039219

**Comment by Mitradis** [comment]
probably we are wrong https://youtu.be/h1x9MErf5NA?t=78

**Comment by T1ti** [comment]
https://youtu.be/h1x9MErf5NA?t=113
Can see it again here
Looks like it is currently blizzlike
