### ISSUE TITLE
Brewfest npcs in Exodar

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4654]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/94

##### ISSUE: FACTION SIDE:

![image](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![image](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### SMALL DESCRIPTION: 

Two brewfest npcs (Draenei commoners) in Exodar. Near Exodar bank. Also 2 brewfest npcs near Exodar hippogryph master.  Brewfest npcs with their masks on should not be around in February.

##### EXPECTED BLIZZLIKE BEHAVIOUR: 

No brewfest npcs around until Brewfest festival

##### CURRENT BEHAVIOUR:  

Two brewfest npcs (Draenei commoners) in Exodar. Near Exodar bank. Also 2 brewfest npcs near Exodar hippogryph master.  Brewfest npcs with their masks on should not be around in February.

![image](https://user-images.githubusercontent.com/78349628/109370496-31a7a600-7866-11eb-986b-8fca7827b584.png)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/21f828847f42083f7fad32b18828d254c208baba

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER: 

ChromieCraft

**Comment by LannyE** [comment]
These and many others are being fixed in this pull request #4336

**Comment by FrancescoBorzi** [comment]
@Helias
