### ISSUE TITLE
Stormwind Guard directs you to wrong place in chat when asking for a shaman trainer

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4656]
Original report: https://github.com/chromiecraft/chromiecraft/issues/105

##### SMALL DESCRIPTION:

 this response from [Stormwind City Patrollers](https://wotlkdb.com/?npc=1976) or [Stormwind City Guards](https://wotlkdb.com/?npc=68) when asked for a **Shaman Class Trainer** which smells a lot like it's from Cataclysm.
![image](https://user-images.githubusercontent.com/7461137/109325063-c81f9b80-7855-11eb-8f96-cec5493103a9.png)
Though the flag that is placed on your map marks the correct location in Valley of Heroes.
![image](https://user-images.githubusercontent.com/7461137/109325915-cb675700-7856-11eb-9217-42fe3f063a27.png)
 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should point to the right trainer

##### CURRENT BEHAVIOUR:

Guard directs you to see Shaman trainer not available until after Cataclysm launch. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Ask Stormwind Guard for Shaman trainer
Step 2 Read reply
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a4115862de1cd6f37b70969c87df79f327457dd1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by JamesGent** [comment]
![image](https://user-images.githubusercontent.com/61194190/109386926-f9e83f00-78f5-11eb-9a06-4a78c2a41d91.png)

TrinityCore has the same issue with the same text.

I can't find what the text used to be anywhere.

We could input a placeholder text like "I hear there's a Draenei Farseer lounging about the Valley of Heroes. I'd speak to her myself but I don't see a way to get to her without swimming." which is better that catacalysm misinformation but not correct until we find out what it should be.

**Comment by aradep** [comment]
Pretty sure there shouldn't be an option for shaman trainer if there isn't one in the city.

**Comment by markvetx** [comment]
@aradep Yes, of course. There is a trainer for shamans. [Link](https://wotlkdb.com/?npc=20407)
