### ISSUE TITLE
WorldServer Freeze

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#466]
**Description**: Worldserver freeze without crash

**Current behaviour**: worldserver.exe freeze without crash and disconnect all players and when try to connecting players stay on connecting after enter username and password. You must Close worldserver and Start it again to connect players correctly . it only 1 time seen by me!

**Branch(es)**: Master

**AC hash/commit**:  latest AC

**Operating system**:  se7en 64 bit

**Modules**:  Are you using modules? anticheat - transmog

**Other Customizations**: No!

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by devovh** [comment]
compile without anticheat

**Comment by ShinDarth** [comment]
unfortunately there is no much we can do to locate the problem, unless you are able to reproduce it

**Comment by Franklampardst** [comment]
@devovh @ShinDarth freeze only once after 2 month.

**Comment by ShinDarth** [comment]
I'm closing this, please feel free to reopen it if you find a way to reproduce the problem
