### ISSUE TITLE
Very important missing mob leash behavior [$20]

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4660]
##### CURRENT BEHAVIOUR:
You can aggro multiple creatures with a ranged attack or spell and they will reset separatly if you don't hit them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
In official Classic, creatures pulled at the same time will stay linked and won't reset separately. This is a big difference for the leveling and general world, it makes clearing groups of creatures a lot harder and makes mistakes less forgiving
This only happens with the "call for help" mechanic, when you aggro ONE mob and he calls for helps around him.
If you face pull multiple mobs, the mechanic will not trigger, because they haven't aggroed from the call for help "aoe aggro", they aggroed from the facepull.

This the the detailed description of the issue for the vanilla Vmangos core and the fix
vmangos/core#793
Commits : 
1. https://github.com/vmangos/core/commit/7d2f1e2923734ea1b983eeaa0208cfd158d4af02
2. https://github.com/vmangos/core/commit/c8510cbbd4dccbdac9900cc507910ef3ae0e6c43
3. https://github.com/vmangos/core/commit/3666b1d85bfdd6de8dec23726119485dde566d04 (?)
4. https://github.com/vmangos/core/commit/183203611d796a4958bbd64a394728f325257cbd (I think this one is a bug fix from moving to that system)

##### EXTRA NOTES:
I'm not 100% sure if this mechanic was still in Wrath, but I don't see a reason it wouldn't be. Some people even said it's still on retail

##### AC HASH/COMMIT:
3d0a4288e0ce9579d90b86437a49c648eee16e87

**Comment by UltraNix** [comment]
@T1ti Please, test it.
