### ISSUE TITLE
ICC Bosses stuck in the floor after flying [$15]

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#4661]
Bosses with inhibit type 5 in the floor and not looking correct

##### CURRENT BEHAVIOUR:

currently affecting:

Blood Queen Lanathel
Rimefang
Spinestalker
Sindragosa

https://i.imgur.com/0GOhoTH.jpg
https://cdn.discordapp.com/attachments/813104786043699220/814572752617996348/unknown.png

Not this, they should be ont he ground not half way the flying flag is not being removed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not this, they should be ont he ground not half way the flying flag is not being removed.

##### STEPS TO REPRODUCE THE PROBLEM:

clone latest ac:
https://github.com/azerothcore/azerothcore-wotlk/commit/695a7402ad809410f74cef08af5f184ecff84d9c

**Comment by FrancescoBorzi** [comment]
@Yehonal

**Comment by r0m1ntik** [comment]
Confirm

**Comment by bronzato** [comment]
Confirmed, same issue here (maybe a problem with hover mode ?

**Comment by disclosurez** [comment]
bump.

**Comment by ChromieCraftServer** [comment]
added 15$ bounty on this

**Comment by ChromieCraftServer** [comment]
@disclosurez you can add more: https://www.bountysource.com/issues/96796144-icc-bosses-stuck-in-the-floor-after-flying?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github

**Comment by ChromieCraftServer** [comment]
added a 15$ bounty here.

@disclosurez @bronzato  you can add more: https://www.bountysource.com/issues/96796144-icc-bosses-stuck-in-the-floor-after-flying?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github

**Comment by Si1ker** [comment]
Same behavior as reported at #4900

**Comment by disclosurez** [comment]
#5097 has fixed some of these bugs yet lanathel is still broken

**Comment by speedrunz** [comment]
yo @FrancescoBorzi why is this closed? this bug is confirmed existing.

**Comment by FrancescoBorzi** [comment]
> yo @FrancescoBorzi why is this closed? this bug is confirmed existing.

it was closed automatically when merging the PR. Reopened.

**Comment by speedrunz** [comment]
thank you @FrancescoBorzi .

**Comment by bronzato** [comment]
@FrancescoBorzi i made a fresh install of azerothcore and the problem persistis, but i fixed this on my server just changing the InhabitType to 1 for Blood-Queen Lana'thel, Sindragosa, even the Nerubians that came from the roof, the creature script make then fly, so you dont need this on ground creatures. if you want i can upload the sql files to change the ICC creatures InhabitType.

**Comment by FrancescoBorzi** [comment]
@bronzato nice, can you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) ?

**Comment by bronzato** [comment]
Sorry, i made the PR wrong, can you delete? i'll make it again

**Comment by FrancescoBorzi** [comment]
> Sorry, i made the PR wrong, can you delete? i'll make it again

no worries, I don't think I can delete PRs but closing it should be enough
