### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4664]
##### CURRENT BEHAVIOUR:
update to https://github.com/azerothcore/azerothcore-wotlk/commit/dbefa17a534500522a174e9906d8923445c16e79, compilation failed

##### AC HASH/COMMIT:
AzerothCore revision            : dbefa17a5345+ 2021-02-28 14:37:03 +0100 (master branch)

##### OPERATING SYSTEM:
ubuntu 18.04.1

##### MODULES:
none

-- CMake version: 3.19.2
-- The CXX compiler identification is Clang 10.0.0
-- The C compiler identification is Clang 10.0.0

Using compile commands:
cmake ../ -DCMAKE_INSTALL_PREFIX=/home/azerothcore/run/ -DCMAKE_C_COMPILER=/usr/bin/clang-10 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -DTOOLS=0 -DSCRIPTS=1 -DWITH_WARNINGS=1 -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"

error log
```
[ 15%] Building CXX object src/common/CMakeFiles/common.dir/Database/QueryResult.cpp.o
[ 15%] Building CXX object src/common/CMakeFiles/common.dir/Database/Transaction.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Database/Implementation/LoginDatabase.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Database/Implementation/CharacterDatabase.cpp.o
In file included from /home/azerothcore/azerothcore/src/common/Configuration/Config.cpp:8:
/home/azerothcore/azerothcore/src/common/Utilities/StringConvert.h:14:10: fatal error: 'charconv' file not found
#include <charconv>
         ^~~~~~~~~~
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Database/Implementation/WorldDatabase.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Navigation/DetourExtended.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Logging/Log.cpp.o
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Packets/ByteBuffer.cpp.o
1 error generated.
src/common/CMakeFiles/common.dir/build.make:278: recipe for target 'src/common/CMakeFiles/common.dir/Configuration/Config.cpp.o' failed
make[2]: *** [src/common/CMakeFiles/common.dir/Configuration/Config.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:828: recipe for target 'src/common/CMakeFiles/common.dir/all' failed
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Helias** [comment]
could you try using g++/gcc 9?

**Comment by FrancescoBorzi** [comment]
> could you try using g++/gcc 9?

might be worth trying, but it should work with clang as well

**Comment by mpfans** [comment]
> could you try using g++/gcc 9 or later? instead of clang

yes... @FrancescoBorzi  told me a solution
My issue is solved,use the following command 
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt install gcc-10 g++-10`
