### ISSUE TITLE
Razorfen Kraul Boss Summons TINY Pigs (Needs Confirm)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4665]
Razorfen Kraul Boss Summons TINY Pigs

##### CURRENT BEHAVIOUR:

Teeny tiny itty bitty boar spirits.

![WoWScrnShot_030121_142543](https://user-images.githubusercontent.com/61194190/109519745-6f454280-7aa3-11eb-9d7c-d48ce2a71332.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal sized spirits.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Razorfen Kraul
2. Aggro this boss (Aggem Thorncurse, left side)
3. Observe tiny bacon

##### EXTRA NOTES:

Might be related to my patch in client, haven't tested without, pls confirm.

##### AC HASH/COMMIT:

AzerothCore rev. c2f274e06dcf 2021-02-28 13:31:49 +0000 (master branch) (Unix, RelWithDebInfo)

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/111890635-9086b800-89eb-11eb-9c58-d6a0b32f5dc1.png)
can't reproduce

**Comment by JamesGent** [comment]
Issue stemmed from a custom patch I used for WoD models.
