### ISSUE TITLE
Razorfen Kraul Archers like to climb to the ceiling (possibly Wailing Caverns related too) Mob Pathing [$50]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4666]
Razorfen Kraul Archers like to climb to the ceiling (possibly Wailing Caverns related too) Mob Pathing

##### CURRENT BEHAVIOUR:

If you taunt a razorfen archer, he will try to reposition to hit you, this can involve climbing to the ceiling and becoming unreachable for melee.

![WoWScrnShot_030121_141905](https://user-images.githubusercontent.com/61194190/109520257-f0043e80-7aa3-11eb-8b07-f585b9cd0b07.jpg)

![WoWScrnShot_030121_141823](https://user-images.githubusercontent.com/61194190/109520264-f1ce0200-7aa3-11eb-84bd-20c538e11da8.jpg)

This is not RFK specific. Sometimes the snakes in Wailing Caverns will climb higher and higher until they hit the roof.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should reposition on ground only, not float.

##### STEPS TO REPRODUCE THE PROBLEM:

RFK:
1. GO to Razorfen Krauk
2. Find ranged unit like Hunter or Animal Tamer
3. Taunt it and break line of sight, see how it behaves.

Wailing Caverns:
An easy reproduction step is to enter Wailing Caverns, and go the "left way" towards Lord Cobrahn. The non-elite snakes love to climb low walls, pillars, and low ceilings if you break LOS or make them move.

Tag a couple of snakes and start running in circles around pillars, or towards the lower ceilings.

##### AC HASH/COMMIT:

AzerothCore rev. c2f274e06dcf 2021-02-28 13:31:49 +0000 (master branch) (Unix, RelWithDebInfo)

**Comment by FrancescoBorzi** [comment]
@Yehonal

**Comment by UltraNix** [comment]
Yep - another one with recent pathinder changes.

**Comment by UltraNix** [comment]
I cannot reproduce it :(

**Comment by UltraNix** [comment]
@JamesGent Please, test it with https://github.com/azerothcore/azerothcore-wotlk/pull/4879

**Comment by JamesGent** [comment]
@UltraNix I tested today and I can confirm your PR (#4879) does not close this issue #4666 in Wailing Caverns or Razorfen Kraul. 

An easy reproduction step is to enter Wailing Caverns, and go the "left way" towards Lord Cobrahn. The non-elite snakes love to climb low walls, pillars, and low ceilings if you break LOS or make them move.

Tag a couple of snakes and start running in circles around pillars, or towards the lower ceilings.

Thank you for trying though!

I can make a video if needed.

**Comment by UltraNix** [comment]
Thanks for testing. I will try to fix it if reproduce it.

**Comment by Yehonal** [comment]
This should not happen after your fix @UltraNix since the "CanReach" method is intended to check the slopes too.

**Comment by UltraNix** [comment]
@Yehonal @JamesGent tested it and he says it's not fixed.

**Comment by UltraNix** [comment]
@JamesGent Test it again with #4909.
