### ISSUE TITLE
Issues Refunding Honour Items During 2 Hour Refund Window

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4667]
Issues Refunding Honour Items

##### CURRENT BEHAVIOUR:

If you buy an item with honour it says it can be refunded for the next 2 hours but trying to right click to sell it to the merchant I bought it from does nothing.

https://youtu.be/eqhPv6mD6N8

##### EXPECTED BLIZZLIKE BEHAVIOUR:

2 hour refund window.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Refugee Point
2. Buy some honour items
3. Try to refund them

##### EXTRA NOTES:

Could be related to these specific items, this NPC, or just my character. Hard to know. When testing try other PVP vendors too.

Could be because I equipped them? But that isn't Blizzlike behaviour.

##### AC HASH/COMMIT:

AzerothCore rev. c2f274e06dcf 2021-02-28 13:31:49 +0000 (master branch) (Unix, RelWithDebInfo)

**Comment by FrancescoBorzi** [comment]
Weird. The time I tried it worked, but it was months ago.

**Comment by LautaroJMolina** [comment]
I was able to refund leather boots on the Arathi horde vendor like 2 days ago. I don't remember if I did equipe them beforehand.

**Comment by ChromieCraftServer** [comment]
is this still an issue?

**Comment by FrancescoBorzi** [comment]
closing unless someone can reproduce this again
