### ISSUE TITLE
Razorfen Stalkers don't have nameplates [$5]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4668]
Razorfen Stalkers don't have nameplates

##### CURRENT BEHAVIOUR:

This NPC doesn't have nameplates during combat (press V).

https://classic.wowhead.com/npc=6035/razorfen-stalker

![WoWScrnShot_030121_143844](https://user-images.githubusercontent.com/61194190/109528660-d61b2980-7aac-11eb-9eb1-af17335be59d.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I'd guess they're meant to have nameplates? It could be related to their "Prowl"/Stealth skill they have?

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Razorfen Kraul
2. Enable Nameplates (usuall V or Control-V)
3. Find and fight a Razorfen Stalker

##### AC HASH/COMMIT:

AzerothCore rev. c2f274e06dcf 2021-02-28 13:31:49 +0000 (master branch) (Unix, RelWithDebInfo)

**Comment by Si1ker** [comment]
Same behavior with this NPC = missing nameplate

Name: Riding Ram
ID: 8881
[wowhead info](https://classic.wowhead.com/npc=8881/riding-ram)

![image](https://user-images.githubusercontent.com/61223313/109598732-78ec9b80-7adf-11eb-9330-bd729d6fe023.png)
