### ISSUE TITLE
DB/Creature: Kolkar Drudge and Kolkar Outrunner extreme Fire Resistance

### ISSUE THREAD

**Issue by illfated** [azerothcore/azerothcore-wotlk#4670]
##### ISSUE: FACTION SIDE:
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

Original report: https://github.com/chromiecraft/chromiecraft/issues/107

This ticket content is based on comments written by @necropola in the linked issue ticket.

##### CURRENT BEHAVIOUR:

- https://wotlkdb.com/?npc=3119/kolkar-drudge
- https://wotlkdb.com/?npc=3120/kolkar-outrunner

The NPC mobs Kolkar Drudge and Kolkar Outrunner resist more than 50% of any Fire Damage thrown at them. Frost Damage works as expected, though.

This is from the combat log of my level 11 Blood Elf Mage (Fireball and Frostbolt are both Rank 2):

![image](https://user-images.githubusercontent.com/38162891/109538972-010f7880-7ac1-11eb-8a80-8ef52b996a75.png)

Fireballs work fine on other NPCs in the area, e. g. Scorpids.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should not have any elemental resistance at all …
… but I cannot find any information/source about elemental resistance on NPCs in any database, although I know that there are certain NPCs in game (usually elementals) that are supposed to have high resistance against a particular school of magic.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Kolkar Crag in Southern Durotar near Sen'jin Village.
2. Fight a few of the Kolkar as a Mage.
3. Watch the difference in damage between Frost and Fire spells.
4. Check your Combat Log.

##### EXTRA NOTES:

Based on the discussion in https://github.com/chromiecraft/chromiecraft/issues/107, we have discovered that the issue is currently present in TrinityCore 3.3.5 as well.

I have both a current AC-3.3.5 and a current TC-3.3.5 running locally on my Linux Host and both show the same **funny** fire resistance. The following screenshot is from hitting a Kolkar Drduge with a Fireball Rank 16 from my level 80 Fire Mage on a current TC-3.3.5 server.

![image](https://user-images.githubusercontent.com/7461137/109433417-82f39900-7a10-11eb-9ed7-cbdeb1ee4ed1.png)

Though I don't think just because it is also present in TC makes it correct.

See also the other comments in the linked issue ticket for related information.

##### SERVER:

ChromieCraft

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7ec204943a3080071e0f1d7b7d18e10cbc4d1918

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

* [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
* [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
* [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)

##### OTHER CUSTOMIZATIONS:

None.

**Comment by Kitzunu** [comment]
|| *name* || *resistance2* ||
|| Kolkar Drudge || 70 ||
|| Kolkar Outrunner || 70 ||

**Comment by necropola** [comment]
Does someone have a classic account and could try some of the 23 creatures (< level 20, at least one resistance > 50) I have listed in the ChromieCraft ticket? Just so we get an estimate on how blizz-like  AC's /TC's current resistance values are.

**Comment by T1ti** [comment]
Just look up th bestiary book

**Comment by T1ti** [comment]
When a creature has bonus resist it should show like that in the book
![image](https://user-images.githubusercontent.com/40864460/109696558-7ba5ca00-7b8d-11eb-95d5-5d10f3634eff.png) 
![image](https://user-images.githubusercontent.com/40864460/109696771-b3ad0d00-7b8d-11eb-8c87-651aad0da7e0.png)


![image](https://user-images.githubusercontent.com/40864460/109696637-8eb89a00-7b8d-11eb-864f-b4f17fe62ffb.png)

None of them seem to have any, but I'm not entirely sure this boss shows all resistances

**Comment by necropola** [comment]
Hmm, the book isn't actually available for free unless it's from a rather dubious source ...

**Comment by T1ti** [comment]
the book actually doesn't show any resistance for non boss creatures so it's not a reliable source here

**Comment by Zoidwaffle** [comment]
In vmangos they have 0 resistances.

In AC 70 fire and 30 shadow, same as TC.

I made a PR that aligns AC with vmangos. All this resistance for a starting-zone-creature seems weird.

**Comment by illfated** [comment]
The PR #4746 looks good. I just commented about a redundant blank line, but the content itself looks promising.

**Comment by necropola** [comment]
> In vmangos they have 0 resistances.
> 
> In AC 70 fire and 30 shadow, same as TC.
> 
> I made a PR that aligns AC with vmangos. All this resistance for a starting-zone-creature seems weird.
If you check my original report on ChromieCraft's issue tarcker, you'll see that there are a lot more low level creatures with significant ( > 50) resistances in AC (~~23~~ 21 below level 20).

**Comment by illfated** [comment]
Looks like you have got some good material for a new PR. 😉

**Comment by Zoidwaffle** [comment]
@necropola, I just looked at the original page now.

I could make a PR targeting the differences with vmangos unless any of you want to.

**Comment by illfated** [comment]
> I could make a PR targeting the differences with vmangos unless any of you want to.

Sounds good to me, I have not yet set up any local configuration for easy access to AC/CC data to make the necessary queries.

**Comment by necropola** [comment]
> I could make a PR targeting the differences with vmangos unless any of you want to.

Fire away!

**Comment by Zoidwaffle** [comment]
@necropola and @illfated - have a look at this: https://github.com/azerothcore/azerothcore-wotlk/pull/4753.

**Comment by illfated** [comment]
Thank you, that looks very good. Now, knowing that I tend to be an OCD perfectionist, I would like to post a completely cosmetic update to that SQL, just to illustrate my tendency to prefer order and ease of readability (please note, this is just cosmetic and should in no way be seen as a requirement or request for change).

```sql
-- Align resistances with vmangos for creatures level 1-20
UPDATE `creature_template` SET `resistance3`=  0 WHERE `entry`=   832; -- 'Dust Devil' level 19, resistance3 was 40 (Nature)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  1892; -- 'Moonrage Watcher' level 14, resistance5 was 5 (Shadow)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  1893; -- 'Moonrage Sentry' level 15, resistance5 was 5 (Shadow)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  1896; -- 'Moonrage Elder' level 15, resistance5 was 5 (Shadow)
UPDATE `creature_template` SET `resistance1`=  0 WHERE `entry`=  2166; -- 'Oakenscowl' level 9, resistance1 was 18 (Holy)
UPDATE `creature_template` SET `resistance2`=  0 WHERE `entry`=  3273; -- 'Kolkar Stormer' level 14, resistance2 was 70 (Fire)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3273; -- 'Kolkar Stormer' level 14, resistance5 was 30 (Shadow)
UPDATE `creature_template` SET `resistance2`=  0 WHERE `entry`=  3274; -- 'Kolkar Pack Runner' level 15, resistance2 was 70 (Fire)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3274; -- 'Kolkar Pack Runner' level 15, resistance5 was 30 (Shadow)
UPDATE `creature_template` SET `resistance2`=  0 WHERE `entry`=  3275; -- 'Kolkar Marauder' level 16, resistance2 was 70 (Fire)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3275; -- 'Kolkar Marauder' level 16, resistance5 was 30 (Shadow)
UPDATE `creature_template` SET `resistance2`=  0 WHERE `entry`=  3397; -- 'Kolkar Bloodcharger' level 15, resistance2 was 70 (Fire)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3397; -- 'Kolkar Bloodcharger' level 15, resistance5 was 30 (Shadow)
UPDATE `creature_template` SET `resistance5`= 30 WHERE `entry`=  3417; -- 'Living Flame' level 17, resistance5 was 0 (Shadow)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3529; -- 'Moonrage Armorer' level 15, resistance5 was 5 (Shadow)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3531; -- 'Moonrage Tailor' level 15, resistance5 was 5 (Shadow)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  3533; -- 'Moonrage Leatherworker' level 15, resistance5 was 5 (Shadow)
UPDATE `creature_template` SET `resistance2`=  5 WHERE `entry`=  3569; -- 'Bogling' level 5, resistance2 was 0 (Fire)
UPDATE `creature_template` SET `resistance3`=  5 WHERE `entry`=  3569; -- 'Bogling' level 5, resistance3 was 0 (Nature)
UPDATE `creature_template` SET `resistance4`=  5 WHERE `entry`=  3569; -- 'Bogling' level 5, resistance4 was 0 (Frost)
UPDATE `creature_template` SET `resistance5`= 10 WHERE `entry`=  3569; -- 'Bogling' level 5, resistance5 was 0 (Shadow)
UPDATE `creature_template` SET `resistance6`=  5 WHERE `entry`=  3569; -- 'Bogling' level 5, resistance6 was 0 (Arcane)
UPDATE `creature_template` SET `resistance3`= 15 WHERE `entry`=  5891; -- 'Minor Manifestation of Earth' level 15, resistance3 was 0 (Nature)
UPDATE `creature_template` SET `resistance2`= 19 WHERE `entry`=  6748; -- 'Water Spirit' level 18, resistance2 was 0 (Fire)
UPDATE `creature_template` SET `resistance3`= 38 WHERE `entry`=  6748; -- 'Water Spirit' level 18, resistance3 was 0 (Nature)
UPDATE `creature_template` SET `resistance5`= 38 WHERE `entry`=  6748; -- 'Water Spirit' level 18, resistance5 was 0 (Shadow)
UPDATE `creature_template` SET `resistance6`= 19 WHERE `entry`=  6748; -- 'Water Spirit' level 18, resistance6 was 0 (Arcane)
UPDATE `creature_template` SET `resistance2`=  0 WHERE `entry`=  9523; -- 'Kolkar Stormseer' level 16, resistance2 was 70 (Fire)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  9523; -- 'Kolkar Stormseer' level 16, resistance5 was 30 (Shadow)
UPDATE `creature_template` SET `resistance2`=  0 WHERE `entry`=  9524; -- 'Kolkar Invader' level 17, resistance2 was 70 (Fire)
UPDATE `creature_template` SET `resistance5`=  0 WHERE `entry`=  9524; -- 'Kolkar Invader' level 17, resistance5 was 30 (Shadow)
UPDATE `creature_template` SET `resistance6`= 76 WHERE `entry`= 10373; -- 'Xabraxxis' level 19, resistance6 was 0 (Arcane)
UPDATE `creature_template` SET `resistance3`= 15 WHERE `entry`= 11321; -- 'Molten Elemental' level 13, resistance3 was 22 (Nature)
UPDATE `creature_template` SET `resistance1`=  0 WHERE `entry`= 12431; -- 'Gorefang' level 13, resistance1 was 70 (Holy)
```
Changes from the original SQL:
- Added spacing to keep the query columns aligned.
- Added missing apostrophe (single quote) after some of the names.
- Removed comma after the names, since they are encapsulated in apostrophes anyway.

Feel free to use as much or as little as you like from my edited version. 🙂

**Comment by Zoidwaffle** [comment]
@illfated - no worries, the missing ' was an error on my behalf... the rest, well, I guess that's mostly for preference. But it looks nicer and I upgraded the PR and added you in there (then you can take half the blame as well)

**Comment by illfated** [comment]
> (then you can take half the blame as well)

Hahah, thank you for making me laugh just a little. I really needed that after a hard day at work today. Very well. It is not much of a change, but I like to share whatever I find more useful, just in case someone else would find it useful too.

**Comment by illfated** [comment]
(ref. https://github.com/azerothcore/azerothcore-wotlk/pull/4746)
