### ISSUE TITLE
[CORE] Looking For Group

### ISSUE THREAD

**Issue by Franklampardst** [azerothcore/azerothcore-wotlk#468]
**Description**: Group Not remove for Last Player on LFG

**Current behaviour**: after LFG last player always on party and not remove

**Expected behaviour**: need to disband party.

i open PR but can't work with that . really looool

You need go file on  src\game\DungeonFinding\LFGMgr.cpp and after `player->TeleportToEntryPoint();` add this lines : 

        // we need disband group for last player (i know this is not blizzlike)
        if (group->GetMembersCount() == 1)
        {
            group->Disband();
	        sLog->outDebug( LOG_FILTER_LFG, "Player %s is last in lfggroup so we disband the group.", player->GetName().c_str());
        }

this is not blizzlike but if you have another way we can improve it :)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by sucofog** [comment]
Where did you found this?

**Comment by Franklampardst** [comment]
@sucofog Added by trinitycore edited by me for AC

**Comment by Inifield** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/game/DungeonFinding/LFGScripts.cpp#L121

**Comment by Franklampardst** [comment]
@Inifield always my players ticket for we are solo but saying on party so that's not working

**Comment by starrheld** [comment]
For reference:
https://github.com/TrinityCore/TrinityCore/commit/e743f4a479ce7ddd3f13d51ca1c19a591c803fc0

One more thing that would be nice to get resolved and confirmed is whenever you finish a dungeon with a group, you need to re-group in order to be able to re-queue.

**Comment by sucofog** [comment]
This fix by trinitycore does not work under AC

**Comment by starrheld** [comment]
@sucofog That's my conclusion as well, tried it a while back and didn't work.

**Comment by sucofog** [comment]
Someone did a hack fix at discord chat, don't remember actually, i use it and its working, but i have to check commit log on my repo

**Comment by starrheld** [comment]
@sucofog Maybe Yehonal? In general chat on Discord?

**Comment by sucofog** [comment]
Yes, i think too @starrheld

**Comment by starrheld** [comment]
I summon you @Yehonal

**Comment by talamortis** [comment]
can someone test the below code to check see if it works?

`        if (group->GetMembersCount() == 1)
        {
            LeaveLfg(player->GetGUID());
            group->Disband(true);
        }
        return;`

**Comment by sucofog** [comment]
![image](https://user-images.githubusercontent.com/734950/28779965-583fa04a-7605-11e7-9267-050b5dc3d8ff.png)

The unique fix worked perfect for me

**Comment by Yehonal** [comment]
@sucofog where's this piece of code you've pasted? 

i'll add it in staging-master branch that is compiled by our demo server, so we can test it eventually

**Comment by sucofog** [comment]
@Yehonal You did this code as far as i remember, at discord, long ago

**Comment by Yehonal** [comment]
Yes but maybe we never imported it, so if you can send me that piece of code in this way i will re-test 

This is an high priority long bug so we've to fix as soon as possible (even if there's an in-game workaround for player)
