### ISSUE TITLE
Text missing in legacy of the aspects item (page 11)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4683]
Text missing in legacy of the aspects item (page 11)

##### CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/61194190/109718267-0511c800-7b9f-11eb-8c91-37855be41ece.png)

page 11 reads for half a line

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://classic.wowhead.com/item=5860/legacy-of-the-aspects

page 11 reads

The black dragon underwent a complete transformation; and in the end, Neltharion no longer existed. He became Deathwing, a creature of malice and hatred. No longer the Earth-Warder in the eyes of races like the high elves, he was renamed the Death Aspect and Xaxas in place of his titan-given name. Deathwing is the embodiment of chaos and evil, and is always hungry for destruction. He is arguably the first evil of Azeroth that appeared after the banishment of the Old Gods.

##### STEPS TO REPRODUCE THE PROBLEM:

1. add item Legacy of the Aspects (5860)
2. read and compare to link above
3.

**Comment by Helias** [comment]
fixed, will add the PR soon
![image](https://user-images.githubusercontent.com/519778/109720881-f16c5e80-7baa-11eb-8f72-c5b09912b0b8.png)
