### ISSUE TITLE
CMake can't succeed

### ISSUE THREAD

**Issue by diguo520** [azerothcore/azerothcore-wotlk#469]
CMake can't succeed

![1](https://cloud.githubusercontent.com/assets/20224521/25307721/6ef700a6-27d8-11e7-894a-c7c3be719812.PNG)

Do you have a .Sln  project file？

**Comment by starrheld** [comment]
Greetings!
For all support inquiries please join our Discord server at the following address https://discord.gg/nNH3GvT. Wish to hear from you there.

Best regards,
AZEROTHCORE COMMUNITY
