### ISSUE TITLE
Feature: Group and improve world drops loots

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4699]
**Describe your feature request or suggestion in detail**
I saw that cmangos has a really nice way of organizing and handling loot, which is for sure very similar to how Blizz did/does it.
Instead of having tons of entries or random reference tables for, they group world drops by levles and categories and assign them to NPCs logically.
This is how a creature loot looks like in AC : 
![image](https://user-images.githubusercontent.com/40864460/109912750-fca7b300-7cac-11eb-8e78-02f180fb403a.png)

And how it looks in cmangos[1.12 database] : 
![image](https://user-images.githubusercontent.com/40864460/109912783-0b8e6580-7cad-11eb-83bf-1a17cc2fc965.png)

Note that current drop rates in AC are very inconsistent, world drops of the same rarity+lvl have difference drop rates, that's because all of the loot data for private server has been massively copied from thottbot/wowhead databases. For creatures with low samples like some rares this is especially bad, like if a creature reported 50 times on wowhead dropped an epic or a bag once, the database will make the mob have 2% chance to drop an epic.
This system allows to standardize drop rates for world drops(blue = 0.05%, white = 5% etc...)

They have a table where they grouped all their world drops : 
 
![image](https://user-images.githubusercontent.com/40864460/109912929-54461e80-7cad-11eb-8c6f-a4aac818e676.png)

**Describe a possible solution to your Feature or Suggestion in detail**
Some commits from cmangos for that system : 
https://github.com/cmangos/classic-db/commit/f1de2da787a9ef2b829f6afe920db6c123de3a78
This is how their initial commit when moving to that new system (october 2018)
https://github.com/cmangos/classic-db/commit/4705c9e46a0fa635fd19b12d4b4500526a707f08 massive clean up here
https://github.com/cmangos/classic-db/commit/187c2f6f88c3aa8c73b33cdf7a89075b2cf216fa  adjust reference tables to NPCs level

**Comment by FrancescoBorzi** [comment]
hey @T1ti , is your suggestion about the table structure or table contents?

My 2 cents about the table structure: what I can see is vMaNGOS still using the old MaNGOS structure, which basically expresses the same things but it's a bit cumbersome. For example, the field `minCountOrRef` has been split in `MinCount` and `Reference` many years ago in TrinityCore. So when it comes to the table structure I like the TC/AC structure better, which is basically the same as MaNGOS but slightly improved.

**Comment by T1ti** [comment]
> hey @T1ti , is your suggestion about the table structure or table contents?
> 
> My 2 cents about the table structure: what I can see is vMaNGOS still using the old MaNGOS structure, which basically expresses the same things but it's a bit cumbersome. For example, the field `minCountOrRef` has been split in `MinCount` and `Reference` many years ago in TrinityCore. So when it comes to the table structure I like the TC/AC structure better, which is basically the same as MaNGOS but slightly improved.

it's Cmangos, not Vmangos
And I'm only talking aobut the improved reference groups

**Comment by Si1ker** [comment]
reference_loot_template

**Comment by JamesGent** [comment]
I like this idea a lot and would vouch for its value in decreasing the frequency of rare/epic drops. It would make the task of adjusting loot to match blizzlike rates a lot less time consuming.

**Comment by neifion-00000000** [comment]
as an additional comment toward the loot system, I investigated loot and found that each continent has separate drop tables similar to how some instance zones do, in regards to which sets drop in each location, in addition to the world drop table, if you want to accommodate a system that will not need later detail repair

**Comment by Gultask** [comment]
Yeah my PR actually ports Mangos' system. It's exactly what it's defined here.
