### ISSUE TITLE
[Request] Character Migrate compatibel

### ISSUE THREAD

**Issue by rynnokung** [azerothcore/azerothcore-wotlk#47]
Is it possible to make this compatibel with Azerothcore? Please consider this.
https://github.com/ahuraa/Character-Migration 
Yehonal also contributed to that repo. 

I know this is not urgent, but maybe its not that hard to fix. I tried it myself, error i'm getting is : "﻿Column count doesn't match value count at row 1", but since there is no refference as to wich tabel provides the error, i'm a bit stuck :(

**Comment by Yehonal** [comment]
We won't support this kind of tools for AzerothCore project. Is nothing that regards us.  

I've contributed to that repo but for personal reasons.
