### ISSUE TITLE
[Quest][Outland] Deathblow to the Legion | 10409

### ISSUE THREAD

**Issue by sucofog** [azerothcore/azerothcore-wotlk#470]
**Description**:

This quest is bugged due to no script support

Deathblow to the Legion
http://www.wowhead.com/quest=10409 

**Current behaviour**: 

You can kill http://www.wowhead.com/npc=20132/socrethar, but it won't credit the quest, just will credit his death, but, as there is no script, and no dialogue or event, the quest won't be completed.

![image](https://cloud.githubusercontent.com/assets/734950/25397277/0d3b0a76-29e8-11e7-8aa9-040246db4b0c.png)

**Expected behaviour**: 

Event should happen, i attach link to youtube video where you can see the quest on live realm.

https://www.youtube.com/watch?v=Ncfb5hyiy9E

**Steps to reproduce the problem**:

1. .quest add 10409
2. Go coordinates and use item provided by quest: http://www.wowhead.com/item=29796
.go xyz coordinates on image
![image](https://cloud.githubusercontent.com/assets/734950/25397468/a6f28748-29e8-11e7-98b1-b0f5992140a5.png)

3. .go xyz coordinates on 2nd image:
![image](https://cloud.githubusercontent.com/assets/734950/25397562/ee679474-29e8-11e7-86e5-6a2d82607156.png)

4. Kill Sorcrethar

5. Quest is not completed 🔪 

**Branch(es)**: master

**AC hash/commit**:  604fa387b53d3d298840026b83caebc891275849

**Operating system**:  Debian

**Modules**:  Mod-Transmog, Mod-Anticheat

**Other Customizations**: No.

**Additional data: 

There is a script at OregonCore repo, probably working, but no SQL data provided, and also needs to be adapted:

https://github.com/OregonCore/OregonCore/blob/0f4d552fce1242f49f625d9ac54f7f3aa0c349a9/src/scripts/Outland/netherstorm.cpp#L2468

**Comment by sucofog** [comment]
@Rushor Can you provide us some info? Not asking for fixes just to know if this is right, and if its broken at TC right now.

**Comment by STARRHELD** [comment]
We are missing quest credit, hence why the quest is not working properly.
```SQL
(20132, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 11, 35762, 2, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 'Socrethar - On Death - Quest Credit')
```
