### ISSUE TITLE
Paladin aura serious error

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#4707]
Paladin aura serious error

##### CURRENT BEHAVIOUR:
spell error
![image](https://user-images.githubusercontent.com/18535853/110001455-5e205e00-7d4f-11eb-8dd6-546357cf6fe8.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
![image](https://user-images.githubusercontent.com/18535853/110002645-94121200-7d50-11eb-944f-6a920dd6a74f.png)

##### STEPS TO REPRODUCE THE PROBLEM:
Choose yourself
1. .unaura all
2. .cast 44335 （Reuse 10 times）
3. .cast 54043
4. Wait for 44335 to disappear
5. Try to let the monster attack you and see the bounce damage
6. 
![image](https://user-images.githubusercontent.com/18535853/110002783-be63cf80-7d50-11eb-88ee-612c33a63a72.png)
This error damage will continue until the player is offline
If in a team, all team members have high rebound damage

##### AC HASH/COMMIT:
d7cef10

##### OPERATING SYSTEM:
Windows 10

**Comment by claudiodfc** [comment]
Casting this spell as a gamemaster stacks because you're casting a spell modifier to all type of damage:

_Apply Aura: Mod Damage Done - % (Physical, Holy, Fire, Nature, Frost, Shadow, Arcane)
Value: 50_
 
If you cast retribution before this aura wears off, it will increase the damage probably until you recast redemption.

In any case, where is this spell even present in the game? Because if players aren't able to cast this, there is really nothing to be fixed here.

**Comment by pklloveyou** [comment]
> Casting this spell as a gamemaster stacks because you're casting a spell modifier to all type of damage:
> 
> _Apply Aura: Mod Damage Done - % (Physical, Holy, Fire, Nature, Frost, Shadow, Arcane) Value: 50_
> 
> If you cast retribution before this aura wears off, it will increase the damage probably until you recast redemption.
> 
> In any case, where is this spell even present in the game? Because if players aren't able to cast this, there is really nothing to be fixed here.

```.go c id 24744```

**Comment by pklloveyou** [comment]
![Uploading image.png…]()

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/110012884-fa506200-7d5b-11eb-8cd0-7f1c11875ca8.png)
Players can easily stack dozens of times

**Comment by pklloveyou** [comment]
And this method applies to all auras that can increase damage

**Comment by claudiodfc** [comment]
Ok, so I can think of 2 possible problems.
1. Auras not reverting to normal modifiers after the modifier expires, such as this spell.
2. This Aura stacking indefinitely.

**Comment by pklloveyou** [comment]
YES

**Comment by pklloveyou** [comment]
There is no upper limit to this superposition

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/110019382-5965a500-7d63-11eb-929e-460a77fa9c23.png)

**Comment by pklloveyou** [comment]
No one's paying attention to this?

**Comment by r0m1ntik** [comment]
Confirm

**Comment by pklloveyou** [comment]
SpellAuraEffects.cpp
```
        case SPELL_AURA_DAMAGE_SHIELD:
+            if (GetId() == 7294 || GetId() == 10298 || GetId() == 10299 || GetId() == 10300 || GetId() == 10301 || GetId() == 27150 || GetId() == 54043)
+                break;
            if (GetBase()->GetType() == UNIT_AURA_TYPE)
                amount = caster->SpellDamageBonusDone(GetBase()->GetUnitOwner(), GetSpellInfo(), amount, SPELL_DIRECT_DAMAGE, 0.0f, 1);
            break;
```
Is that right? It solves the problem

**Comment by pklloveyou** [comment]
I made a mistake
