### ISSUE TITLE
Mage freeze effects can cause enemies to stop moving indefinitely [$25]

### ISSUE THREAD

**Issue by necropola** [azerothcore/azerothcore-wotlk#4708]
Original report: https://github.com/chromiecraft/chromiecraft/issues/125 by @CameronWoof

I could reproduce on current AC but not on current TC. See also the other comments in the linked issue ticket especially the precise trigger conditions for the bug;
- **your damage needs to be the cause of breaking the Frost Nova**
- you must not move nor turn nor turn the camera since the Frost Nova was applied
- you must not be hit by the frozen target

##### CONTENT PHASE:
[20-29]

##### SMALL DESCRIPTION:
Enemies frozen by Frost Nova or the Frostbite talent become unresponsive in certain situations.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Once the freeze effect wears off, the enemy should continue moving towards the player to attack them.

##### CURRENT BEHAVIOUR:
Under the right (easily repeatable) circumstances, the enemies instead stand still long after the freeze effect is removed, allowing you to kill them without them ever attempting to close the distance again. If they are an enemy type that flees at low health, they will do so as normal when reduced to the proper threshold.

##### STEPS TO REPRODUCE THE PROBLEM:
Step 1: Stand still. Do not rotate your character or move from your starting position.
Step 2: Get into combat with an enemy. They must be running towards you--beginning combat by freezing them will not work.
Step 3: Freeze the enemy before they close into melee range with you.

If you've done the above correctly, they should remain motionless even after the freeze effect ends or is removed. You can cast spells, attack with your wand, or do pretty much anything as long as you do not move or rotate your character. I'm able to reproduce this consistently, and it seems to apply to all mobs--animals, humanoids, constructs, you name it.

##### AC HASH/COMMIT:
chromiecraft/azerothcore-wotlk@c2f274e

##### OPERATING SYSTEM:
Ubuntu 20.04

##### MODULES:
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:
None.

##### SERVER:
ChromieCraft

**Comment by claudiodfc** [comment]
This bug is probably related to the same AI bug on neutral zones such as Tanaris, Ratchet, Booty Bay etc...
If you don't move, under certain conditions the AI will not attack you.

**Comment by CameronWoof** [comment]
I have personally tested that this also works with Druids' Entangling Roots. The common link, of course, is that these are snares that are removed by damage--the cause might be there?
