### ISSUE TITLE
Ashenvale Outrunners should be stealthed

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#4709]
related to https://github.com/chromiecraft/chromiecraft/issues/123

##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

NPC: [Ashenvale Outrunner](https://classic.wowhead.com/npc=12856/ashenvale-outrunner)

Zone: [Ashenvale](https://classic.wowhead.com/ashenvale)

These mobs should be in stealth until they attack or are dealt damage.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These mobs should be in stealth until they attack or are dealt damage.

##### CURRENT BEHAVIOUR:

They are walking around in the open despite doing the stealth walking animation.
![Ashenvale Outrunner](https://user-images.githubusercontent.com/78349628/109894282-cb9a9480-7c52-11eb-9b96-8969bdb1c43e.png)

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Teleport to Splintertree Post.
Step 2. Run south til you see the Ashenvale Outrunners. None of them are in stealth in the area they spawn at, but all of them move as though they were.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Helias don't forget to add the project
@Helias don't forget to add the project
@Helias don't forget to add the project
@Helias don't forget to add the project
@Helias don't forget to add the project
