### ISSUE TITLE
[C++] Player dump command should overwrite savefile (.pdump write)

### ISSUE THREAD

**Issue by falzard** [azerothcore/azerothcore-wotlk#471]
**Description**: Pdump allows us to save to a savefile (.txt) and restore a character from that same file. It also allows to copy character easily.

**Current behaviour**: If you save a character once, it creates a file, but if you use the same command again, with the same filename, it won't overwrite it and it will print an error that the action can't be done.

**Expected behaviour**: It should overwrite the file and update it.

**Steps to reproduce the problem**:

1. Login to a character
2. Save: .pdump  write  character_save_file  $playerNameOrGUID
3. Repeat: .pdump  write  character_save_file  $playerNameOrGUID
It should give you an error ingame and in the console.

**Operating system**:  Debian 8

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by KP580BM1** [comment]
Look PlayerDump.DisallowOwerwrite in the end of worldserver.conf

**Comment by falzard** [comment]
Omfg, I thought I had looked at each "Dump" entry but maybe I looked at "pdump" instead. So I never saw that config option.

I look like an idiot.

Thanks a lot!
