### ISSUE TITLE
Demetria is alone

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4715]
##### CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/40864460/110059248-253eb400-7d64-11eb-8749-d8d2fcfd7cc6.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
![image](https://user-images.githubusercontent.com/40864460/110059257-2a036800-7d64-11eb-8096-149b4c93260f.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### EXTRA NOTES:

she also should be in shadow form

##### AC HASH/COMMIT:
e59041ddb1fcbcfaec57cc0d24baf13b7e29efb1

**Comment by axzn** [comment]
Hi, I would like to have a go at this issue, if no one minds and it's not already grabbed 😄

**Comment by Zoidwaffle** [comment]
Oh, this is a good excuse to learn about creature_formations I believe? The knowledge could also be used here: https://github.com/azerothcore/azerothcore-wotlk/issues/4398.

@axzn - give it a go, I'm curious about seeing your solution as I'm interested in the concept myself :smiley:

**Comment by axzn** [comment]
Hey guys, unfortunately I think this is still beyond my knowledge a bit. Somebody who knows more with what they're doing should take this issue, or at least point me in the right direction on where to look for a fix.

At the moment, I know that Dimetria's id is **12339**, and that she starts walking along her `waypoint_data` points when a player accepts a quest with id **6148** (The Scarlet Oracle, Demetria). I can see that she has some SAI rows defined, but from the looks of it those rows just describe what spells she should use at certain HP levels. And that's where is all falls apart from me. I'm stumped at trying to find out exactly how taking this quest starts her walking route... Is it somewhere in C++ scripts, or SAI? I looked everywhere for anything related to this quest id and her entity id, but found nothing...

**Comment by Knindzagxg** [comment]
Not easy one to sort tbh.
Never tried to work with creature_formations my self and when had something where we need to spawn / move multiple adds i did it with spawns, masks and waypoints.

You can try to spawn them around Demetria like preposition and make them invisible.
On quest take, you can remove invisible mask and make them move with her trough waypoints.

Waypoints are not that hard to make: In-game and DB part
1. .npc info
2. .wp add current GUID + 0 (Example if current GUID is 55555+0 - make sure to add 0 at the end)
3. .npc add move GUID (Once you move in-game to position where you want add to move you type this - You can check this as well by following Dementia movement and check her Waypoints to see where she stop / move.)

Now let's go to DB -> creature_addon
1. Guide - creature GUID
2. Path - creature GUID + 0

It will take some times to get used to this, but once you do it few times, it's pretty easy after.

You can check this old video as well - Pretty nice tutorial.
https://www.youtube.com/watch?v=-1KfUHtl32c

**Comment by T1ti** [comment]
In vmangos, this is hardcoded but seems to work properly

This what what is responsible for the formation : 

```
uint64 guidScarletTrooper[9];

    void MovementInform(uint32 movementType, uint32 moveId) override
    {
        if (movementType != WAYPOINT_MOTION_TYPE)
            return;

        if (moveId == 0)
        {
            if (m_creature->FindNearestCreature(NPC_SCARLET_TROOPER, 60.0f, true)) //if another demetria is around, despawn.
                m_creature->ForcedDespawn();
            else
            {
                m_creature->JoinCreatureGroup(m_creature, 0, 0, (OPTION_FORMATION_MOVE | OPTION_AGGRO_TOGETHER | OPTION_EVADE_TOGETHER));
                for (int i = 1; i <= 9; i++)
                {
                    float angle = i * 2 * M_PI / 9;
                    float x, y, z;
                    m_creature->GetPosition(x, y, z);
                    x += 3.0f * cos(angle);
                    y += 3.0f * sin(angle);
                    if (Creature* c = m_creature->SummonCreature(NPC_SCARLET_TROOPER, x, y, z, m_creature->GetOrientation(), TEMPSUMMON_MANUAL_DESPAWN, 0))
                    {
                        c->JoinCreatureGroup(m_creature, 3.0f, angle - m_creature->GetOrientation(), (OPTION_FORMATION_MOVE | OPTION_AGGRO_TOGETHER | OPTION_EVADE_TOGETHER));
                        guidScarletTrooper[i - 1] = c->GetGUID();
                    }
                }
            }
        }

        if (moveId == 99)
        {
            DespawnTroopers();
            m_creature->ForcedDespawn();
        }
    }
```
 See : 
https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/eastern_plaguelands/eastern_plaguelands.cpp#L828

**Comment by T1ti** [comment]
video of vmangos : https://i.gyazo.com/30900a5748b7dd7d82645f4b682e6d1e.mp4

**Comment by LannyE** [comment]
I think I got this.  This is a Stitches 2.0 situation.  I should have a PR coming soon been working on this for a few weeks (Formations, Combat Rez, waypoint adjustments, smart scripts workarounds, bug testing, etc.).  Smart scripts is an extreme finiky beast, have very little hair left.  All I have left is to attempt to optimize the scripts.
