### ISSUE TITLE
Shaman Flurry talent on consecutive crits [$10]

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4720]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/122

##### ISSUE: FACTION SIDE:

 ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
 ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Spell: [Flurry](https://wowgaming.altervista.org/aowow/?spell=16284)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After dealing a melee critical hit, this talent should give 3 charges which buff you with 30% increased attack speed and are each expended by the following 3 melee swings.
When charges from a previous crit remain and a new critical hit is dealt, the new crit should set the charges to three, they don't stack.
https://www.youtube.com/watch?v=jvTAzjotu60 at 5:54
Gets a crit on the hunter, swings once at the druid expending one charge, next swing on the druid is a crit and the stacks go from 2 to 3.
I could not find documented changes to how the stacks work between vanilla final patch and last patch of wotlk.

##### CURRENT BEHAVIOUR:

Works normally on the first critical hit.
When having 1 or more charges of a previous critical remaining, if another critical hit is dealt, the buff duration gets reset but the charges will be set to only 2.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Spec the flurry talent in the Enhancement shaman tree
Step 2 Hit a creature until getting a critical
Step 3 Get a crit with one of the three swings following the proc from the previous step

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
I believe the next occurring critical hits are proccing as one of the three flurry hits after flurry is refreshed instead of before

**Comment by UltraNix** [comment]
Cannot confirm.
Cast 16280 on self, do 2 melee swings - 1 stack is left.
Again, cast 16280 on self - the buff duration is refreshed and got 3 stacks again.

**Comment by Stifler82** [comment]
> Cannot confirm.
> Cast 16280 on self, do 2 melee swings - 1 stack is left.
> Again, cast 16280 on self - the buff duration is refreshed and got 3 stacks again.

@UltraNix 
https://github.com/azerothcore/azerothcore-wotlk/issues/4723

**Comment by Stifler82** [comment]
> Okay, I think I got it.
> Got 3 stacks -> melee swing -> consume 1 proc (2 stacks left) -> this melee swing is critical , so it should refresh flurry, but still got 2 stacks?

@UltraNix 
Exacly
