### ISSUE TITLE
DISCUSSION: Investigation of a potential Bug and extension of it to other Characters

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4723]
Brief Summary
-
While doing triaging, I came across a Bug reported by a Player regarding a Shaman Enhancement talent.
**Link Player's Report:** https://github.com/chromiecraft/chromiecraft/issues/122

In short: the player reported that the talent **Flurry** **should always have 3 stacks at each refresh**, instead the talent does 3 Stacks **only on the first proc**, but if it procs **while the talent is active**, the aura **only gets 2 Stacks** instead.

I'm pretty sure the Player is right, but for the sake of scruple I did some research on the WOTLK Patch Notes, and I discovered this:

World of Warcraft Client Patch 3.0.2: Echoes of Doom (2008-10-15)
-
> **Shaman**
> 
> - **Flurry now increases attack speed by 15/20/25/30/35% for your next 3 swings after dealing a critical strike**

.
.
.

World of Warcraft Patch 3.0.3
-

> **Shaman**
> 
> - **Flurry: Now grants the proper number of charges when it triggers.**

**Probably the fix made by Blizzard in 3.0.3 was related to the Player's report.**

.
.
.

Then in the next Patch..

.
.
.

World of Warcraft Client Patch 3.1.0 - (2009-04-14)
-
> **Shaman**
> 
> - **Flurry: Now provides 5/10/15/20/25% haste instead of 10/15/20/25/30%.**

.
.
.

**From this point of the Patch on, there are no more references to the Flurry talent.**

Personal Questions and Considerations:
-
Since there are no other changes notified in the Patch Notes, everything suggests to me that this is the last change released for this talent...

So at this point the questions I ask myself are essentially two:

- **Do we have the wrong talent?**
and if so...
- **Is it the only talent that is affected by this problem?**
Or even worse..
- **Can the other Characters also be affected by the same error?**

Link Patch Notes: [WOTLK Patch Notes](https://www.toxicgaming.us/wow/wrath-patch-notes/)

**Comment by Stifler82** [comment]
@FrancescoBorzi

**Comment by FrancescoBorzi** [comment]
>  I wanted to add, I ignored the difference in haste because from my experience I thought it was 30%, but I actually realised now that shaman talents in Rawr 2.3.23 also display 25% at rank 5. Considering the app was made the 23rd of August 2010 I personally find it reliable.

from @LautaroJMolina
