### ISSUE TITLE
The Missing Diplomat - A specific part does not trigger the Npc RP Event

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#4725]
related to https://github.com/chromiecraft/chromiecraft/issues/132
possible fix https://github.com/TrinityCore/TrinityCore/commit/49e40f48c9326ce55f2f1f0b7e9ed2768d055b47

 ISSUE: FACTION SIDE: Alliance

________________________________________________________________________________________________________________________________________
________________________________________________________________________________________________________________________________________

Alliance

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:
The Missing Diplomat quest - Theramore phase does not trigger the RP event (https://wowgaming.altervista.org/aowow/?quest=1324)
________________________________________________________________________________________________________________________________________

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once you subdue Private Hendel, an RP event should start with Archmage Tervosh and Lady Jaina Proudmoore at the location of Private Hendel that allows you to advance / complete the quest.

##### CURRENT BEHAVIOUR:

The RP event does not start. 

Workaround for completing the quest -> move to the Theramore Magic tower and interact with the NPC there

##### STEPS TO REPRODUCE THE PROBLEM:

1. Advance with the quest line up to https://wowgaming.altervista.org/aowow/?quest=1324 
2. Subdue the NPC (note that during the time i performed the steps the NPC guards assisted me with lowering the target HP)
3. Once Private Hendel is subdued - the NPC RP event should start

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
Looking at the possible fix, probably is better to make a deep investigation on all "The Missing Diplomat" series and porting everything to SAI when it's possible. (On TC it seems fixed)

**Comment by LannyE** [comment]
I just put in a PR for Part 11 through Part 16 including the End event.  #4719

**Comment by Helias** [comment]
so your PR will fix this? if so, add in your PR description
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4725 
- Closes https://github.com/chromiecraft/chromiecraft/issues/132
