### ISSUE TITLE
Quest: Denalan's Earth - Missing walking event

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4735]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/141

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Denalan doesn't walk up to the pottery.

Quest: [Denalan's Earth](https://wotlkdb.com/?quest=997)
NPC_Start: [Syral Bladeleaf](https://wotlkdb.com/?npc=2083)
NPC_End: [Denalan](https://wotlkdb.com/?npc=2080)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The video shows how Denalan walks up and plants the gameobject from the quest.
[Youtube video](https://www.youtube.com/watch?v=N5ETR0eBlak)

##### CURRENT BEHAVIOUR:

He kneels without walking up, staying on his spawn position. Maybe missing waypoint.

##### STEPS TO REPRODUCE THE PROBLEM:

Get quest Denalan's Earth
Talk to Denalan and deliver quest
Watch his script

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
https://github.com/TrinityCore/TrinityCore/blob/1d04d5859a59caf286d71f78a18ec4ed05feb7c2/sql/old/7/world/01_2018_02_19/2017_09_05_00_world_2016_10_07_03_world_335.sql
