### ISSUE TITLE
Long Crawler Claw Drop Table

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4736]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/144

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC: [Ghostclaw Lynx](https://wotlkdb.com/?npc=16348)

Item: [Long Crawler Limb](https://wotlkdb.com/?item=2088)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This item should only drop from Sea Crawlers (https://wotlkdb.com/?npc=831) in Westfall

##### CURRENT BEHAVIOUR:

This item dropped from a Ghostclaw Lynx in the Ghostlands. It was on their drop table so I imagine it will be difficult to reproduce

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Kill and loot a Ghostclaw Lynx
Step 2 It is possible this item may drop

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Is there any proof video/evidence the item dropped from that NPC (Ghostclaw Lynx)?

Looking at the DB is almost impossible, in fact, I think it is, the item has no linked-way to that NPC.

**Comment by Zoidwaffle** [comment]
This is not pretty SQL, but @Stifler82 is right, it can drop from the lynx. 
```
select Reference from creature_loot_template where entry=16348 and Reference!=0;
+-----------+
| Reference |
+-----------+
|     24074 |
|     24075 |
|     24076 |
|     24077 |
|     24078 |
+-----------+

-- and then look at those references...

select * from reference_loot_template WHERE entry>=24074 and entry<=24078 and Item=2088;
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+-------------------+
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment           |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+-------------------+
| 24076 | 2088 |         0 |      0 |             0 |        1 |       1 |        1 |        1 | Long Crawler Limb |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+-------------------
```

It has 1% chance to enter the loot template with the claw... and in that pool it has a 1/53 chance of being a claw. So you where pretty damned lucky to get that claw! :grin:
