### ISSUE TITLE
Creatures can fall/stop behind walls

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#4742]
##### CURRENT BEHAVIOUR:

Currently, you can step into a creature so it will go back. You can use this behavior to get a creature/boss behind a wall and break mechanics without leaving (combat / boss reset)

This photo is an example of the Anub'Rehkhan encounter where I pushed him back throughout the wall by moving into its position.

![image](https://user-images.githubusercontent.com/61223313/110223902-cb8dd500-7e9c-11eb-93c2-8c6b6c0550c1.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

At retail, this should not be possible in order to avoid breaking mechanics.

##### STEPS TO REPRODUCE THE PROBLEM:

You can try it with any boss, just keep going to its position until it moves back and you get it behind a wall

##### EXTRA NOTES:

1- Using the latest vmaps
2- Related to #4220 

##### AC HASH/COMMIT:

f9b7e45

##### OPERATING SYSTEM:

Windows 7
&
Debian 10

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by Footman** [comment]
This issues should have need fixed by #4879

**Comment by Si1ker** [comment]
> This issues should have been fixed by #4879

Yep, this was resolved. Cannot repro
![image](https://user-images.githubusercontent.com/61223313/132052158-31ff6525-1fe9-48b5-9300-eeb95d994fe6.png)
