### ISSUE TITLE
Trolls in Drawen start Zone are NOT Aggresive

### ISSUE THREAD

**Issue by xaer-cromiecraft** [azerothcore/azerothcore-wotlk#4747]
##### CURRENT BEHAVIOUR:
https://youtu.be/KHtozWfm6G0?t=1061
The Trolls in Drawen start district should be Aggresive (RED) currently they are not aggresive and not social (yellow)
https://www.wowhead.com/npc=706/frostmane-troll-whelp

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Trolls are agressive and attack player on sight. "Boss" griknir-the-cold (https://www.wowhead.com/npc=808/griknir-the-cold) should attack with his two buddies.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Visit Cavern 
2. Place low level char within attack range.
3. the npc should attack the player.

##### OTHER CUSTOMIZATIONS:

**Comment by D3thw0lf** [comment]
Mobs, in starting zones, were changed to neutral in Patch 3.3.0
Source: https://wow.gamepedia.com/Patch_3.3.0_(undocumented_changes)

Your Video shows the "real" Classic 1.x experience and yes they were aggressive in BC, too. LK changed that to get players faster into the game and out of the "tutorial". :)

**Comment by Si1ker** [comment]
Check sources before posting.

![image](https://user-images.githubusercontent.com/61223313/110252377-b2436200-7f4a-11eb-8e27-e77e8ef51033.png)
