### ISSUE TITLE
(Quest issue): Unexpected Results - Protect Apprentice Mirveda (IA or script error?)

### ISSUE THREAD

**Issue by LordFers** [azerothcore/azerothcore-wotlk#4752]
The mission Unexpected Results: Protect Apprentice Mirveda (on EAST SANCTUM), has several issues.

**1)** NPCs spawn at speed > 15.0 .
**2)** They attack a little faster than normal.
**3)** If you lose the mission, that is, if Mirveda dies, it takes at least 10 minutes for the NPC to "respawn" to any other user within all server.
**4)** If you lose, after 10 minutes, you must abandon the quest to do it again.

**I'm using the actual master branch (I compiled it less than 12 hours ago.)**.

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

There's a reason why the template you deleted was there.
This will be closed if no appropriate changes are performed.
