### ISSUE TITLE
Debian 10 World database not specified in configuration file

### ISSUE THREAD

**Issue by dingweijie** [azerothcore/azerothcore-wotlk#4756]
##### CURRENT BEHAVIOUR:

"git pull" to check for new updates  #4608 
Fresh compile
error log:
Config: Missing name PidFile in config, add "PidFile = "
Config: Missing name WorldDatabaseInfo in config, add "WorldDatabaseInfo = "
World database not specified in configuration file

![image](https://user-images.githubusercontent.com/5669013/110262645-45ce6e80-7fef-11eb-8a4d-f63817be11e0.png)

![image](https://user-images.githubusercontent.com/5669013/110262678-5e3e8900-7fef-11eb-9aa4-1fbf0b19ad74.png)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fresh compile

##### OPERATING SYSTEM:

Debian 10

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
Hmm, interesting
`Ununtu 20.04` okay
![image](https://user-images.githubusercontent.com/18329778/110440030-c8882400-80ea-11eb-8a28-1a160f392fd4.png)

**Comment by Winfidonarleyan** [comment]
And
![image](https://user-images.githubusercontent.com/18329778/110443609-b0b29f00-80ee-11eb-85d9-be1f5cd73e1e.png)

**Comment by PatheticNeatness** [comment]
@dingweijie you definitely have a '#' in your db info, remove it and that will work

**Comment by PatheticNeatness** [comment]
@Winfidonarleyan 
add this
` src/common/Configuration/Config.cpp | 11 +++++------
 1 file changed, 5 insertions(+), 6 deletions(-)

diff --git a/src/common/Configuration/Config.cpp b/src/common/Configuration/Config.cpp
index 205ea26c..6372634f 100644
--- a/src/common/Configuration/Config.cpp
+++ b/src/common/Configuration/Config.cpp
@@ -45,7 +45,6 @@ namespace
             throw ConfigException(acore::StringFormat("Config::LoadFile: Failed open file '%s'", file.c_str()));
 
         uint32 count = 0;
-
         while (in.good())
         {
             std::string line;
@@ -60,15 +59,15 @@ namespace
             if (line[0] == '#' || line[0] == '[')
                 continue;
 
-            size_t found = line.find_first_of('#');
-            if (found != std::string::npos)
-                line = line.substr(0, found);
-
             auto const equal_pos = line.find('=');
-
             if (equal_pos == std::string::npos || equal_pos == line.length())
                 return;
 
+            size_t found = line.find_first_of('#');
+            size_t quote = line.find_last_of('"');
+            if ((quote == std::string::npos || found > quote) && found != std::string::npos)
+                line = line.substr(0, found);
+
             auto entry = acore::String::Trim(line.substr(0, equal_pos), in.getloc());
             auto value = acore::String::Trim(line.substr(equal_pos + 1), in.getloc());
 
`

will fix database info with '#' in them
