### ISSUE TITLE
Gathering Leather should be a skinning quest

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#4766]
Original issue: chromiecraft/chromiecraft#173

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Gathering Leather](https://classic.wowhead.com/quest=768/gathering-leather)
NPC_Start: [Veren Tallstrider](https://classic.wowhead.com/npc=3050/veren-tallstrider)
NPC_Start: [Veren Tallstrider](https://classic.wowhead.com/npc=3050/veren-tallstrider)
This quest shouldn't be offered to non-skinners.
![Gathering Leather](https://user-images.githubusercontent.com/78349628/110269922-56003280-7f8a-11eb-9aee-6b414a70e5b2.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be required to have the skinning skill to pick up this quest.

##### CURRENT BEHAVIOUR:

This quest is offered to anyone as far as I can tell (or at the very least, to my tauren druid who is herbalist / alchemy).

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Teleport to Veren Tallstrider.
Step 2. See if he offers the quest to you.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
I made a PR to fix it. Seems working, but please verify if possible.

It's a Horde only quest, but being in Thunderbluff that part was probably pretty obvious :grin:
