### ISSUE TITLE
Fear can send you right through walls into out of bounds [$50]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4769]
Fear can send you right through walls into out of bounds

##### CURRENT BEHAVIOUR:

Any sort of fear (Warlock Fear, Priest Psychic Scream, Warrior Intimidating Shout, Hunter's Shrapnel Shot, etc).

If you are feared you can and will walk through walls, under floors, and into spots that can get you stuck or leveraged out of bounds in battlegrounds and the overworld.

https://cdn.discordapp.com/attachments/801844176416276500/813924005156225024/WoWScrnShot_022321_220255.jpg

![WoWScrnShot_030821_230328](https://user-images.githubusercontent.com/61194190/110463698-26f0da80-80ca-11eb-85c0-1aa585636944.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Fears/controlled movements should not have you phase through solid objects and die.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter a BG or Gurubashi Arena or anywhere with walls. The huts in WSG that contain chests are good for this test.
2. Cast any source of fear.
3. Watch as sometimes you will phase through solid objects during the fear.

##### AC HASH/COMMIT:

AzerothCore rev. 6a7155eb7e82 2021-03-07 12:37:07 +0000 (master branch)

**Comment by JamesGent** [comment]
I put confirmed because there's my screenshot of it happening to me and Ixtab's screenshot of fearing Endermer into a wall trapping him under Gurubashi Arena.

**Comment by Hellucard** [comment]
This Bug is common as for NPCS going through walls/trees/stones etc

**Comment by Hacki95** [comment]
Could this have anything to do with the mmaps rewrite? If so @Yehonal should probably take a look at this.

**Comment by UltraNix** [comment]
Without mmaps, it works okay. So the problem lays within the pathfinder and recent changes to it.
