### ISSUE TITLE
Pets are slowed if master is slowed

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#4772]
##### CURRENT BEHAVIOUR:
Some pets are getting slowed if the pet owner is slowed, tested with a few classes:
Warlock, Hunter and Mage (water elemental without glyph) pets are getting slowed

Druid balance Treants, Priest Shadowfiend and Shaman Enhancement Feral Spirit are not getting slowed
Only class i didn't test was DK

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pets should only get slowed if the pet itself get a movement speed debuff.

As can be seen in these retail videos:

At 2:04 you can see warlock in party have deadly throw debuff (50% slow) and pet voidwalker walks normaly
https://www.youtube.com/watch?v=buLNkD4uw0o 

at 11:11, enemy warlock receives frostbolt slow and felhunter walks normal
https://www.youtube.com/watch?v=AVQ4G9gkXls

##### STEPS TO REPRODUCE THE PROBLEM:

1. Log to 2 sessions or have someone to help you 
2. Create a warlock or hunter and another class that can apply slow
3. Summon or call your pet
4. Put the pet in stay and get some distance from it
4. Apply slow to the warlock or hunter with the other class
5. Call your pet back to you with pet follow or send it to attack someone

##### EXTRA NOTES:

If you apply the same slow to the pet and pet owner, the pet gets even slower (lets say a warlock have -50% move speed, the pet gets -70%+ move speed)

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/51342ef9b500

##### OPERATING SYSTEM:
Windows 10

**Comment by FrancescoBorzi** [comment]
not sure if this is related to other pet issues recently reported. CC @Yehonal

**Comment by AbraKabastard** [comment]
Linking issue #4975

**Comment by UltraNix** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/1becd73f09764e9e6ae27f35efdb514e860b12bf
