### ISSUE TITLE
Greymist Murlocs don't drop any Loot

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#4775]
##### CURRENT BEHAVIOUR:
- Different Greymist Murlocs dont drop any Loot. (ID 2201 - 2208)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- They should drop some Loot

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go c 37961
2. Kill some Murlocs around here, on the beach, in the water.
3. They won't drop any Loot.

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/60d684282b602addfcb666cc970f01f700732b37

##### OPERATING SYSTEM:
Ubuntu 18

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Helias** [comment]
This issue is invalid, I cannot reproduce.

![image](https://user-images.githubusercontent.com/519778/110542200-0d32b000-8129-11eb-93c4-4740cd9b39b3.png)

![image](https://user-images.githubusercontent.com/519778/110542242-19b70880-8129-11eb-9458-a2aff27c06a7.png)
