### ISSUE TITLE
[Quest] The Absent Minded Prospector (ID=731) isn't scripted

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#4776]
##### CURRENT BEHAVIOUR:
- After you accept the quest from Prospector Remtravel he doesn't begin to move.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- Prospector should walk towards the golems and do his thing
- https://www.youtube.com/watch?v=UeNbdd8UBMA

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go c 37085
2. .quest add 731
3. Nothing happens

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/60d684282b602addfcb666cc970f01f700732b37

##### OPERATING SYSTEM:
Ubuntu 18.04

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Hacki95** [comment]
This one seems to be on my DB aswell. It works now... Sorry again.

**Comment by Yehonal** [comment]
Does anyone faced a bug with him again? apparently he seems not scripted. Can you confirm?

**Comment by Gultask** [comment]
If I recall correctly there may be some related bugs but the quest is doable.
![image](https://user-images.githubusercontent.com/100873791/219796687-70e0a26e-af26-4ff9-8337-5f3e1cce4380.png)

**Comment by Yehonal** [comment]
So eventually the problem was that I had to abandon the quest and take it again. I do not know if it was an occasional bug or simply the script doesn't put the quest on "failed". I should do more testing, but the quest and the script works for the rest
