### ISSUE TITLE
Murkdeep doesnt drop any Loot and doesn't have Waypoints

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#4777]
##### CURRENT BEHAVIOUR:
- When killed he doesn't drop any Loot.
- Spawns in the Water and doesn't move around

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- He should drop Loot.
- He also walks around normally

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go c 1976190
2. .die
3. Check Loot

##### EXTRA NOTES:
None

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/60d684282b602addfcb666cc970f01f700732b37

##### OPERATING SYSTEM:
Ubuntu 18.04

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Helias** [comment]
Cannot reproduce. It has the loot.

![image](https://user-images.githubusercontent.com/519778/110541872-a0b7b100-8128-11eb-81df-a91affc96009.png)
