### ISSUE TITLE
Professions learn

### ISSUE THREAD

**Issue by Rassd** [azerothcore/azerothcore-wotlk#478]
**Description**:
works unlearn when im logged on but gets back after reloge so i can learn all works from npc

**Steps to reproduce the problem**:

1. Create Hero 80
2. .learn All rec Jew And .Learn all rec Al
3. Unlearn Jewelcrafting
4. .learn all rec eng
5. Relog
6. Login
7. You Have 3 work:|

**Branch(es)**: Master

**AC hash/commit**:  Last Rev

**Operating system**:  Windows 64

**Modules**: Transmog Anticheat

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Viste** [comment]
Confrim!

**Comment by Yehonal** [comment]
Could you test it with normal procedure (from trainers) instead of .learn commands please?

**Comment by Viste** [comment]
@Yehonal i test it in few days when have free time

**Comment by Viste** [comment]
@Yehonal i check and it only .learn command bug

**Comment by Viste** [comment]
need help when i can find place where professions handle(all places)

**Comment by Viste** [comment]
This bug also can be repeat when you use character migration web tool

**Comment by poszer** [comment]
It's just an issue with learn commands. As the player in normal way, you can't reproduce this issue. I'm closing this

**Comment by vhiperdev** [comment]
This problem has been closed, but the error still exists it would be good to reopen it, I tried to check more I have not found a solution.

**Comment by V3nomAnc3r** [comment]
can someone fix this problem please!

**Comment by V3nomAnc3r** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/2330

**Comment by Kitzunu** [comment]
I will close this in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/2330 as it is the same issue, but more detailed.

Thank you for your report :)
