### ISSUE TITLE
Ethereal Liquor allows you to phase through BG walls (possibly related to fear bug) [$50]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4782]
Ethereal Liquor allows you to phase through BG walls (possibly related to fear bug)

##### CURRENT BEHAVIOUR:

Drink Ethereal Liquor. It turns you into a feared monster. The feared monster will run through walls in BGs.

https://www.wowhead.com/item=38294/ethereal-liqueur

Possibly related;

This might be a fear issue not an ethereal liquor issue, but I don't know.

https://github.com/azerothcore/azerothcore-wotlk/issues/4769

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not phase through walls.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Warsong Gulch
2. Go inside a hut/building
3. Drink and watch

##### AC HASH/COMMIT:

AzerothCore rev. 6a7155eb7e82 2021-03-07 12:37:07

**Comment by JamesGent** [comment]
https://cdn.discordapp.com/attachments/801844176416276500/821906902119612416/World_Of_Warcraft_2021.03.17_-_19.27.49.08_Trim.mp4

@UltraNix The specific walls (and windows) inside the WSG Flagrooms and the WSG Huts/Houses seem to be the issue. They also do not block Line of Sight for casting.

The video was recorded with your 4879 fix running, so this specific issue (phasing through walls) still persists.

**Comment by UltraNix** [comment]
As I said in PR - this is problem with generated VMaps and is out of scope of that PR. This is different from issues with fear. Must be be fixed (if it is not blizzlike) by another PR/issue ticket.

**Comment by FrancescoBorzi** [comment]
thanks @JamesGent and @UltraNix please update your PR list of "Closes #xxxx" accordingly to which issues are really closed by it.

**Comment by UltraNix** [comment]
@FrancescoBorzi Already did it - still those 2 + need test on #4666.

**Comment by JamesGent** [comment]
@UltraNix This issue is about phasing through walls. This is not about out of bounds but about phasing through walls whilst remaining in bounds.

The other issue (#4769) is about fear causing people to die out of bounds. You seem to have fixed that (great work!).

If people are still phasing through walls then this issue needs to remain open.

This video is a test performed with your PR;

https://cdn.discordapp.com/attachments/801844176416276500/821906902119612416/World_Of_Warcraft_2021.03.17_-_19.27.49.08_Trim.mp4

**Comment by UltraNix** [comment]
I will try to fix this problem with LoS.

**Comment by UltraNix** [comment]
This is how core see this place:
![mmap](https://user-images.githubusercontent.com/80540499/111746808-d2e6b280-888e-11eb-8da7-1b5106c69728.png)

**Comment by UltraNix** [comment]
@JamesGent Please, test it with #4922 and #4879.
