### ISSUE TITLE
Shadowfang Door Keep Lever is One-Time Use (Stuck bug) [$15]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4784]
Shadowfang Door Keep Lever is One-Time Use (Stuck bug)

##### CURRENT BEHAVIOUR:

On the final boss room in Shadowfang Keep next to Archmage Arugal there is a door.

The lever to the door is one time use.

This means if any player clicks the lever, anyone not in the room is trapped outside, and anyone inside the room is trapped inside forever.

The only way out is either hearthstone or dungeonfinder exit tool.

![WoWScrnShot_030821_123507](https://user-images.githubusercontent.com/61194190/110710562-01f98600-81f6-11eb-8b64-80d90ccb7a32.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Door can be opened/closed at will after the boss.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to NPC Archmage Arugal
2. Activate door lever after fight
3. Observe you are trapped

##### AC HASH/COMMIT:

AzerothCore rev. b6bcb0b2b01d 2021-03-10 21:28:56 +0000 (master branch) (Unix, RelWithDebInfo)

**Comment by kanwest5478** [comment]
I believe the lever object entry is: 18899
