### ISSUE TITLE
Hole in the world in Stormwind Trade District (clip through terrain to underworld) BLIZZLIKE

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4787]
Hole in the world in Stormwind Trade District (clip through terrain to underworld)

##### CURRENT BEHAVIOUR:

Whatever the fuck this is;

https://youtu.be/9EbFnJgZ2pk

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This is blizzlike lmao.

https://www.youtube.com/watch?v=oLWFrfo9jE8

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3.

**Comment by JamesGent** [comment]
This also works.

https://www.youtube.com/watch?v=NkdtVlkgOL0

![WoWScrnShot_031121_014618](https://user-images.githubusercontent.com/61194190/110723203-97ebdb80-820b-11eb-8ecc-00c20bcf3956.jpg)

**Comment by Hacki95** [comment]
Both of these glitches where possible to do in WOTLK so I would say its working as intended.

**Comment by Helias** [comment]
I don't think it's server-side related.
Because the buildings that you see in Stormwind like where you are in the last screenshot are client-side related

**Comment by Si1ker** [comment]
> I don't think it's server-side related.
> Because the buildings that you see in Stormwind like where you are in the last screenshot are client-side related

This was completely normal in retail back then, idk why even open an issue if know that it blizzlike, makes no sense.
