### ISSUE TITLE
Feral Charge - Cat travel speed should be faster

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#4791]
##### CURRENT BEHAVIOUR:
Druid spell https://wowgaming.altervista.org/aowow/?spell=49376 (Feral Charge - Cat) have its animation/travel time slower than intended

Right now its like that:

https://www.youtube.com/watch?v=KrWjRh578vM

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Should have a faster animation like that:   (retail videos btw)

https://www.youtube.com/watch?v=lLe3KJG2teQ&ab_channel=ZybakTV at 0:20 and at 0:37 

https://www.youtube.com/watch?v=XcQdFJjL4SQ&ab_channel=ZybakTV at 1:12

https://www.youtube.com/watch?v=-vt1gim7obQ&t=102s&ab_channel=wowmoviesandvideos at 4:08 and 9:20

##### STEPS TO REPRODUCE THE PROBLEM:
1. 
2. 
3. 

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/51342ef9b500

##### OPERATING SYSTEM:
Windows 10

**Comment by Helias** [comment]
I did a PR, test it if you can and read also the section test performed pls
