### ISSUE TITLE
Quest: Bounty on Murlocs has an incorrect prerequisite

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4800]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/161

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Quest: [Bounty on Murlocs](https://classic.wowhead.com/quest=46/bounty-on-murlocs)
NPC_Start: [Guard Thomas](https://classic.wowhead.com/npc=261/guard-thomas)
NPC_End: [Guard Thomas](https://classic.wowhead.com/npc=261/guard-thomas)

This quest should not have any prerequisites, except for its level requirement. However, it is currently flagged as having [Deliver Thomas' Report](https://wotlkdb.com/?quest=39) as a prerequisite. This means the quest cannot be completed at the same time as [Find the Lost Guards](https://wotlkdb.com/?quest=37), as originally intended.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Guard Thomas should offer [Find the Lost Guards](https://wotlkdb.com/?quest=37), [Protect the Frontier](https://wotlkdb.com/?quest=52), and [Bounty on Murlocs](https://wotlkdb.com/?quest=46) at the same time when you first speak to them at level 7.

##### CURRENT BEHAVIOUR:

He only offers the first two quests, but not Bounty on Murlocs.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Talk to Guard Thomas at level 7, and he does not offer the quest.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
@Stifler82 - you assigned a lot of issues to yourself (9 right now), I guess by mistake? So I took the liberty of fixing this one.

**Comment by Stifler82** [comment]
> @Stifler82 - you assigned a lot of issues to yourself (9 right now), I guess by mistake? So I took the liberty of fixing this one.

No, I did it on purpose, not by mistake, but if you want to get some, go ahead. 😉

**Comment by Zoidwaffle** [comment]
Ah, I only had time to fix one simple issue this morning so took this one.
