### ISSUE TITLE
Quilboars and other mobs sometimes are stucked

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4810]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/181

##### ISSUE: FACTION SIDE:
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)
![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:
1-19 20-29

##### SMALL DESCRIPTION:
Some mobs in Durotar (like Quilboars) and also in some dungeons, sometimes when are in combat with a player, are stucked into their position and do not move even if player go out from them and they are melee. All animations are stopped and it seems that they remain in Idle, without attaccking till you kill them or go out from their aggro range.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The mobs should not be stucked, but continuing their behaviours.

##### CURRENT BEHAVIOUR:
Sometimes the mobs are stucked into a position during combat with a player.

##### STEPS TO REPRODUCE THE PROBLEM:
Just engage some mobs in Durotar or in some dungeons, normally this happened to me with Quilboars.
Not really often, but like in 30 fights this happened 1-2 times.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Yehonal

**Comment by Stifler82** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303
