### ISSUE TITLE
Practice Lockboxes provide no Lockpicking skill after skill 101, but are green. [$15]

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4812]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/186

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

Practice Lockboxes in Redridge Mountains don't give skill ups after level 101, but are green and appear as if they would. 
https://wotlkdb.com/?object=178244

GameObject: [Practice Lockbox](https://wowgaming.altervista.org/aowow/?object=178244)
Zone: [Redridge Mountains](https://wowgaming.altervista.org/aowow/?zone=44)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These boxes should turn grey at skill 100.

##### CURRENT BEHAVIOUR:  

Class: Rogue. Chests stay green once skill of 100 is reached, but no longer provide skill ups. It should turn gray once it no longer provides skill ups. 

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Make a rogue character, train pick lock
Step 2: goto Redridge Mountains Zone
Step 3 Unlock the Practice Lockboxes at Alther's MIll until level 101.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by esanhueza** [comment]
According to a comment in https://classic.wowhead.com/object=178244/practice-lockbox, it turns gray at 105, I confirmed this using AC #394ae6fd00e42a120a1a97cb8f533767fa792fa7
 
Also, I made ~ 230 attempts with my skill at 101 but was unsuccessful so I think the problem is in the way the probability of success is calculated.

**Comment by UltraNix** [comment]
https://classic.wowhead.com/object=178244/practice-lockbox#comments:id=3151097:reply=1362023
There are green until 104. At 105 they are grey. No bug.
