### ISSUE TITLE
Feegly the Exiled doesn't mutate or die when you turn in The Tear of the Moons

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4814]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/193

##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Quest: [The Tear of the Moons](https://classic.wowhead.com/quest=857/the-tear-of-the-moons)
NPC_Start: [Feegly the Exiled](https://classic.wowhead.com/npc=3421/feegly-the-exiled)
NPC_End: [Feegly the Exiled](https://classic.wowhead.com/npc=3421/feegly-the-exiled)
When you turn in the completed quest, the quest giver should say some lines, turn into a trogg, and die. The scripting for this doesn't seem to be working.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you turn in the completed quest, the quest giver should say some lines, turn into a trogg, and die. 
[Wow Classic Video of Quest Turn in](https://youtu.be/4IMqLWg3eW4?t=165)

##### CURRENT BEHAVIOUR:

When you turn in the quest you just get the quest rewards.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Teleport to Feegly the Exiled. 
Step 2. Turn in the completed quest "The Tear of the Moons".
Step 3. See if he performs the scripting.

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
@Stifler82 : If you don't mind, I'd like to have a look at this one?

**Comment by Stifler82** [comment]
> @Stifler82 : If you don't mind, I'd like to have a look at this one?
> 
> I started looking into it based on chromiecraft, and you where not assigned there, only here.

@Zoidwaffle 
you can do what you desire Dude, I just put my self there just because i'm able to do it.
but if you wish make it, an help will be always welcome.
