### ISSUE TITLE
Players not being alerted when friends / guildmates log in or out

### ISSUE THREAD

**Issue by Jimmysmom** [azerothcore/azerothcore-wotlk#4822]
##### CURRENT BEHAVIOUR:

Players are not receiving the "[Friend] has logged in" or "[Friend] has logged out" notifications when friends/guildmates log in or log out.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Players should be receiving the "[Friend] has logged in/out" notification.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Log in as two characters.
2. Add each other as friends.
3. Have one of the characters log out / in

##### AC HASH/COMMIT:

7891207 (Mar 7)

##### OPERATING SYSTEM:

Windows 10

##### OTHER CUSTOMIZATIONS:

My Characters database was imported from TrinityCore using [this tool](https://www.azerothcore.org/wiki/TrinityCore-to-AzerothCore-characters-migration). Initially my thought was that my imported database was causing the problem, but I am not seeing any db errors in my SQLDriver log files, and this issue is present with newly created accounts and characters.

**Comment by kanwest5478** [comment]
Hey! Curious, did you verify the setting was on for you in WoW options? Maybe I'm going crazy, but I believe there is a setting that controls this notification. If I'm wrong let me know!

**Comment by Jimmysmom** [comment]
When troubleshooting this I found a setting for notifying when a guildmate logs in or out, but even with that toggled on the issue persists. Also, all of my players are seeing this issue.

**Comment by r0m1ntik** [comment]
@Jimmysmom
In src/server/game/Handlers/CharacterHandler.cpp for FRIEND_ONLINE
```diff
    // friend status
-    if (AccountMgr::IsGMAccount(GetSecurity())) // pussywizard: only for non-gms
-       sSocialMgr->SendFriendStatus(pCurrChar, FRIEND_ONLINE, pCurrChar->GetGUIDLow(), true);
+    sSocialMgr->SendFriendStatus(pCurrChar, FRIEND_ONLINE, pCurrChar->GetGUIDLow(), true);
```
And for FRIEND_OFFLINE
In src/server/game/Server/WorldSession.cpp
```patch
-    if (AccountMgr::IsGMAccount(GetSecurity())) // pussywizard: only for non-gms
-       sSocialMgr->SendFriendStatus(_player, FRIEND_OFFLINE, _player->GetGUIDLow(), true);
+    sSocialMgr->SendFriendStatus(_player, FRIEND_OFFLINE, _player->GetGUIDLow(), true);
```

**Comment by FrancescoBorzi** [comment]
@r0m1ntik can you please provide a PR with it?
