### ISSUE TITLE
Fix display of item enchantments in mailbox

### ISSUE THREAD

**Issue by Eureka26** [azerothcore/azerothcore-wotlk#4831]
##### CURRENT BEHAVIOUR:
there is a little mistake (easy to fix) that doesn't let see item enchantments on Mailbox Window) this issue was already fixed on trinitycore.

##### STEPS TO REPRODUCE THE PROBLEM:
send item with enchantments on it through mall

##### EXTRA NOTES:
here is the fix to the issue from Trinity-core
https://github.com/TrinityCore/TrinityCore/commit/f56d65dc2a1bdc1910a19c4352602db1ee675632

AC HASH/COMMIT: https://github.com/azerothcore/azerothcore-wotlk/commit/b24ee3fc1043df1fc7021f79c2959cb76a4ea76e

**Comment by FrancescoBorzi** [comment]
@Eureka26 missing your AC version (commit hash)

**Comment by Eureka26** [comment]
done, already added commit hash.

**Comment by Hemingway1970** [comment]
Same issue? : https://github.com/azerothcore/azerothcore-wotlk/issues/4494

**Comment by Eureka26** [comment]
> Same issue? : #4494

 yep is the same issue ^^ was a mistake of TC Devs from the past
will be fixed in this commit https://github.com/azerothcore/azerothcore-wotlk/pull/4872
