### ISSUE TITLE
Loot/Skinning issue, Black Dragon Whelps Lev 17

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4839]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/199

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC: Black Dragon Whelp https://wowgaming.altervista.org/aowow/?npc=441

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dead lev 17 whelp should be lootable to enable skinning.

##### CURRENT BEHAVIOUR:

Dead whelp only has skinning action enabled, which is not possible with loot on the body.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Kill whelp
Step 2 Attempt to loot
Step 3 Only skinning action shown.  Unable to loot.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Relative to:
-
https://github.com/chromiecraft/chromiecraft/issues/86
https://github.com/chromiecraft/chromiecraft/issues/180
https://github.com/chromiecraft/chromiecraft/issues/172

Video Test: [Loot Skinning issue](https://youtu.be/b6GM0hZtFf8)

**Comment by AbraKabastard** [comment]
It appears to me that the creature is on occasion only dropping some copper and isLooted is returning false because the gold remains but you cannot remove it from the creature because his 'unlootedCount' stays at 0
