### ISSUE TITLE
Core/Spell: Pets and LoS, spell cast fail 

### ISSUE THREAD

**Issue by Rassd** [azerothcore/azerothcore-wotlk#484]
**Description**:
Description: Pets dont use spells on target outside of line of sight.
Current behaviour: After using spells at targets outside the pet's line of sight, the spell fails.
Expected behaviour: The correct is that the pet chase the target until he can use the spell.
Little Vid : https://www.youtube.com/watch?v=IIxiusAehl0 (Video provided by @Goatform )
https://youtu.be/fgqmpbg8Cds (On Retail)

**Steps to reproduce the problem**:

1. Create one Warlock Pet (succubus ou any other)
2. Put warlock on circle of blood (.go xyz 2825 5911 3 530 )
3. Put another character out of LoS (.go xyz 2831 5920 3 530)
4. Try use any spell of warlock pet on another character

**Branch(es)**: master

**AC hash/commit**:  Last

**Operating system**:  win 64

**Modules**:  Are you using modules? if no

**Orginal Post**:https://github.com/TrinityCore/TrinityCore/issues/16647

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by lineagedr** [comment]
Wierd on sunwell core it was fixed.

**Comment by ShinDarth** [comment]
is anyone else having this issue?

**Comment by HamedMohsenavi** [comment]
Sunwellcore Work

AzerothCore Bug

**Comment by talamortis** [comment]
i cant reproduce this issue tried with succubus aswell as imp, the only issue im getting is when the success cast has been done its not returning back to the owner

**Comment by ShinDarth** [comment]
we'll reopen this issue if anyone else can confirm it on latest revision
