### ISSUE TITLE
Values of Items in guild tab being changed incorrectly - Visual bug [$25]

### ISSUE THREAD

**Issue by IvanBanic** [azerothcore/azerothcore-wotlk#4843]
When moving items in the guild bank the preview of the items below become incorrect.
This is the first screen before any actions were taken:
![Guild_Bank_Item_Bug_1](https://user-images.githubusercontent.com/28731701/111083166-64ab9400-850c-11eb-9093-f0fb5d18eae1.png)
After the gloves have switched places the item below one of the gloves receives an incorrect value and new incorrect stats:
![Guild_Bank_Item_Bug_2](https://user-images.githubusercontent.com/28731701/111083199-9290d880-850c-11eb-8c07-cc45c1c017a3.png)
The same happens under the first item when we change places again, the item which changes seems to be random. sometimes it's the item under the first one, sometimes it's the item under the second one:
![Guild_Bank_Item_Bug_3](https://user-images.githubusercontent.com/28731701/111083254-e69bbd00-850c-11eb-8848-f0c250a133b0.png)
if the Log is clicked and then we go back to the inventory screen, the values return to normal. the also go back to normal when they are moved to the characters inventory.
this seems to be only a visual bug and happens only when there is a larger stack of items below.

**Comment by r0m1ntik** [comment]
Confirm

**Comment by FrancescoBorzi** [comment]
@IvanBanic please add the AC version (commit hash) to your report.

Don't ignore the issue report template, it's there for a reason.

**Comment by mdawx** [comment]
I think it is the same issue as described here https://github.com/chromiecraft/chromiecraft/issues/387
