### ISSUE TITLE
Error when changing display of an npc

### ISSUE THREAD

**Issue by CrazyXDv** [azerothcore/azerothcore-wotlk#4845]
Supposedly when a display ID is invalid.
However, there was no crash on the server, just did not see the display and could change to another one without any problems!

Screen
https://media.discordapp.net/attachments/284406375495368704/820777348009164800/unknown.png

1. Change ID - Using TrinityAdmin Or with the command .npc set model 30355
2. Server error and closes
3. Using spell at the end I also got a crash (Spellid 71350)

Rev. d20a153

**Comment by AbraKabastard** [comment]
I can confirm that this causes a core freeze.

**Comment by r0m1ntik** [comment]
Confirm too
