### ISSUE TITLE
Missing event after turning in Helcular's Revenge (Quest)

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4847]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/202

##### ISSUE: FACTION SIDE:

![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Quest: [Helcular's Revenge](https://classic.wowhead.com/quest=553/helculars-revenge)
NPC_Start: [Novice Thaivand](https://classic.wowhead.com/npc=2429/novice-thaivand)
NPC_End: [Helcular's Grave](https://classic.wowhead.com/object=1767/helculars-grave)

Additional information: the Southshore are neutral towards Horde meaning we don't get attacked, which doesn't seem correct. But that might call for another issue thread.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be a small roleplay event of the NPC rising from the grave and attacking the Southshore guards and alliance players.

##### CURRENT BEHAVIOUR:

Nothing happens after turn in.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1: Pick up the quest at the Novice Thaivand in Tarren Mill.
Step 2: Complete the objective.
Step 3: Turn in the quest at Southshore graveyard,

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
Fix southshore guards's faction to "Stormwind" from "Southshore Mayor" (from classic sniffs)
`UPDATE `creature_template` SET `faction`='11' WHERE  `entry`=2386;`
If someone can make  a PR

**Comment by Stifler82** [comment]
@T1ti 

https://user-images.githubusercontent.com/1884642/113083402-0bae5200-91d4-11eb-9745-6c942c5e437b.mp4

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Helcular's Revenge](https://youtu.be/uTFaIo2bw50)
