### ISSUE TITLE
[Quest]-The-Manor-Ravenholdt Bugged (premature completion)

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4849]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/203

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

Likely 30-39 but also all

##### SMALL DESCRIPTION:

Quest: [The Manor, Ravenholdt](https://www.wowhead.com/quest=6681/the-manor-ravenholdt) 
Quest gets complete ahead of time

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The quest should only be completed upon NPC death.

##### CURRENT BEHAVIOUR:

Quest gets complete as soon as you enter the cave.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Enter cave to Ravenholdt
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
may this can help https://github.com/TrinityCore/TrinityCore/issues/3720

**Comment by Hemingway1970** [comment]
So I just revisited this. The NPC was not up. Maybe another rogue spawned him and he did not despawn? Anyway how is it premature ending? You are not supposed to touch the chest. You are supposed to bypass it as your detect traps reveals that it is trapped. Getting to the end of the tunnel without spawning the elite completes the quest. See: https://youtu.be/mLIaYauUCOk
Unless the fix is done already this seems to be working as intended.

**Comment by Stifler82** [comment]
> ‎Quindi ho appena rivisitato questo. L'NPC non era in piedi. Forse un altro ladro l'ha generato e non si è spogliato? Comunque, com'è prematuro finire? Non dovresti toccare il petto. Dovresti aggirarlo mentre le tue trappole di rilevamento rivelano che è intrappolato. Arrivare alla fine del tunnel senza generare l'élite completa la missione. Vedi: ‎[‎https://youtu.be/mLIaYauUCOk‎](https://youtu.be/mLIaYauUCOk)‎ ‎
> ‎ a meno che la correzione non sia già stata eseguita, questo sembra funzionare come previsto.‎

@Hemingway1970 
Okay, so you suggest that the quest is as correct as the video you linked to me suggests?

But you don't know if that video was made on Retail, however, (beyond the legitimate question), I also think the video is correct, but in our Server the quest is completed at the beginning of the tunnel, while in the video shows that the Quest gets complete where the jewel is.

**Comment by Hemingway1970** [comment]
I did this quest yesterday on my rogue and it appeared to complete appropriately. In your video you seem to start the quest on the wrong side of the cave. You appear to start it already at the Ravenholdt Manor. It would make sense to complete as you enter the cave from that end if it is triggered at the end of the cave (from entrance in Hillsbrad point of view).  Id suggest testing again from the Hillsbrad side.

**Comment by Stifler82** [comment]
**Faction:** [Wowhead Link - Ravenholdt](https://classic.wowhead.com/faction=349/ravenholdt)
**Video Test:** [Manor Ravenholdt, from the right path](https://youtu.be/-rEpn_VKlUE)

![image](https://user-images.githubusercontent.com/1884642/111607321-09112d00-87d0-11eb-8443-85854e2ed91a.png)
