### ISSUE TITLE
Strand of the Ancients Envoy pathing is bugged/weird in Thunderbluff

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4851]
Strand of the Ancients Emmisary pathing is bugged/weird in Thunderbluff

##### CURRENT BEHAVIOUR:

watch this

https://youtu.be/jRwz6A-eivA

##### EXPECTED BLIZZLIKE BEHAVIOUR:

no the above, normal walking speeds, not phasing through walls, etc

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Thunder Bluff Central Rise near the inn
2. Find the Strand of the Ancients Emmisary shown in the video
3. Witness the improbable

##### EXTRA NOTES:

https://wow.gamepedia.com/Thunder_Bluff_NPCs

##### AC HASH/COMMIT:

AzerothCore rev. 19642d915999+ 2021-03-14 10:35:19 +0000 (master branch) (Unix, RelWithDebInfo)
C

**Comment by FrancescoBorzi** [comment]
@JamesGent please help

**Comment by JamesGent** [comment]
> 
> 
> I can't find that NPC.

I think different "Envoy" NPCs spawn based on what random battleground is featured.

**Comment by JamesGent** [comment]
https://wotlk.evowow.com/?npc=34949

Here's the NPC link. 6 in Thunder Bluff.
