### ISSUE TITLE
All classes can roll need on Shields [$10]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4858]
All classes can roll need on Shields

##### CURRENT BEHAVIOUR:

All classes can roll need on Shields

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only Paladins, Warriors, and Shamans should be able to roll Need on shields. They are the only classes which can equip shields.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter group
2. Party loot or need before greed
3. Shield drops
4. Roll need on a shield as a Mage.

##### EXTRA NOTES:

https://wow.gamepedia.com/Shield

**Comment by necropola** [comment]
See also https://github.com/chromiecraft/chromiecraft/issues/190

**Comment by necropola** [comment]
I will close https://github.com/chromiecraft/chromiecraft/issues/190 when the fix is merged, too.

**Comment by Stifler82** [comment]
**Related to:** https://github.com/chromiecraft/chromiecraft/issues/190
