### ISSUE TITLE
"Ending Their World" quest bugged - despawning NPC, incorrect aggro, incorrect dialogues

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4860]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/205

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

Phase 1-19, Bloodmyst Isle

##### SMALL DESCRIPTION:

Quest: [Ending Their World](https://wotlkdb.com/?quest=9759)
NPC_Start: [Demolitionist Legoso](https://wotlkdb.com/?npc=17982)
NPC_End: [Exarch Admetius](https://wotlkdb.com/?npc=17658)

Zone: [Bloodmyst Isle](https://wotlkdb.com/?zone=3525)

There are three bugs I've noted while doing this quest:
1) ~The escort NPC Demolitionist Legoso is DESPAWNING if he gets too far from you, approximately around 40-50 yards away from the player. This is game breaking, as you can't finish the quest without the NPC and you have to abandon the quest, wait \~5-10 minutes for the NPC to respawn and retake the quest. This also makes the quest very difficult to finish, as you cannot stop to heal/cast a spell because of fear of Legoso getting too far away and disappearing.~ https://github.com/azerothcore/azerothcore-wotlk/commit/5a770d294500f74d4eb0d46224e3b314cdeb7fb2
2) Sironas is getting aggro'd before the explosion and somehow is able to attack the NPC Legoso from far distance, even though being a melee mob. This also makes quest additionally difficult to finish, because during my attempt there was four adjacent Sunhawk mobs suddenly getting aggrom which isn't blizzlike behavior.
3) Legoso's dialogue during the quest is all over the place, being out of sync with what is actually happening, i.e. bomb explodes before he finishes counting to 3, encouraging the player for the fight after you already killed the boss and so on and so forth. Below you can find examples attached: first picture is Legoso asking for more time to get the bomb ready, when in reality he's already set it up like 25 seconds ago. Second picture is mentioned previously Legoso saying to get ready when the quest has already been finished, as well as forgetting player's name.
![Screen Shot 03-14-21 at 03 11 PM](https://user-images.githubusercontent.com/80629696/111079769-ba2b7500-84fb-11eb-80b0-5b8f5706abd1.JPG)
![Screen Shot 03-14-21 at 03 11 PM 001](https://user-images.githubusercontent.com/80629696/111079775-c1eb1980-84fb-11eb-9848-752e725b2c3a.JPG)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Escort NPC should not despawn/disappear unless killed by mobs. Sironas shouldn't be preempitvely aggro'd by the NPC before the last explosion, also should not be able to deal damage from distance. Dialogue should match the actions on the screen.
A video presenting the entire quest in its proper form can be found here: https://www.youtube.com/watch?v=lARzK9CLu24

##### CURRENT BEHAVIOUR:

Please see the description presented above for current behaviour. 

##### STEPS TO REPRODUCE THE PROBLEM:

For first bug: take the quest, then let escort NPC run away from you. He will despawn after certain distance.

For other two: take the quest and let it progress normally.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4980 should fix your first issue, I upped the range to 100yards (cp from TC)
I don't know if it will fix the second issue, but I added some more checks for how the NPC can get into combat
