### ISSUE TITLE
Quest-Deviate-Hides-From-Nalpak-in-Wailing-Caverns-not-available-to-alliance

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4863]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/209

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE: 

_1-19_

##### SMALL DESCRIPTION: 

_The quest is not available to Alliance players, atleast not to night elves. I am not sure about horde._

 **Quest:** [Deviate Hides](https://wowgaming.altervista.org/aowow/?quest=1486)
 **NPC_Start:** [Nalpak](https://wowgaming.altervista.org/aowow/?npc=5767)
 **NPC_End:** [Nalpak](https://wowgaming.altervista.org/aowow/?npc=5767)

**Zone:** [Wailing Caverns](https://wowgaming.altervista.org/aowow/?zone=718)

##### EXPECTED BLIZZLIKE BEHAVIOUR: 

_Quest available._

##### CURRENT BEHAVIOUR: 

_Quest not avalable._

##### STEPS TO REPRODUCE THE PROBLEM: 

**Step 1** _Get to the barrens as an alliance character,_
**Step 2** _walk up to Nalpak in the Wailing Caverns (Near the entrance),_
**Step 3** _he will not have the quest available for you._

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
```SQL
UPDATE quest_template SET AllowableRaces = 0 WHERE id = 1486;
```
I see other quests have AllowableRaces = 0 instead of a bitmask of 1791. So I put what matches with the rest of the core. There are some quests though with 1791 (all ally and horde races combined)

**Comment by Stifler82** [comment]
It's the same thing, either put 0 or 1791, it means the same thing.

```
UPDATE `quest_template` SET `AllowableRaces` = 1791 WHERE (`ID` = 1486);
```
