### ISSUE TITLE
updates/db_world/2017_05_01_00.sql Error!

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#487]
**Description**: https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/updates/db_world/2017_05_01_00.sql

01. Line:165 ";--", Causes the source command to fail.
02. "UPDATE `creature_template` SET `ScriptName`='npc_scarlet_commander_mograine' WHERE `entry`=3976;" unfinished...
![qq 20170516163310](https://cloud.githubusercontent.com/assets/21149808/26096916/5b0e5dd4-3a55-11e7-8f8d-8024cc8a51cf.png)

**Comment by DarkmoonRabbit** [comment]
This item seems to have stopped ... AzerothCore team, are you still there?
I love this project!
@ShinDarth @Yehonal @Helias @polaretto

**Comment by ShinDarth** [comment]
what database server are you using?

**Comment by DarkmoonRabbit** [comment]
@ShinDarth mysql-5.6.35-winx64
that's not important! I do not know how to fix 'npc_scarlet_commander_mograine' this CPP script, only deleted after the return to normal.

**Comment by ShinDarth** [comment]
should be fixed  in https://github.com/azerothcore/azerothcore-wotlk/commit/c5b8d94dacb9c252912a0737670375bfc74e4d1c

thanks for reporting the issue!
