### ISSUE TITLE
[Quest]-The-Missing-Diplomat 11/16 (cannot be completed)

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#4871]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Quest: [The Missing Diplomat](https://classic.wowhead.com/quest=1249/the-missing-diplomat)
NPC_Start: [Mikhail](https://classic.wowhead.com/npc=4963/mikhail)
NPC_End: [Mikhail](https://classic.wowhead.com/npc=4963/mikhail)
Zone: [Wetlands](https://classic.wowhead.com/wetlands)
Quest ID: 1249

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Retake the quest when its failed and abandoned.

##### CURRENT BEHAVIOUR:

If quest is failed and later abandoned, cant retake it from _Mikhail_. Reset state of NPC not occurs after a while only after worldserver restart.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Go to Mikhail in Wetlands.
Step 2  Fail the quest and abandon
Step 3 No reset state after few mins.

Chromie Issue: https://github.com/chromiecraft/chromiecraft/issues/208

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
http://prntscr.com/10mvvhq
This is the state which isn't reset properly by a timer.

**Comment by nolt** [comment]
@[Repcan](https://github.com/Repcan)
> C++ -> SAI TrinityCore/TrinityCore#22240
> Last part problems too? TrinityCore/TrinityCore#25244
