### ISSUE TITLE
[spell] Berserk

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#488]
**Description**:
Berserk for cat druids is not working correctly with reducing energy cost.
It's aura effect is being applied before other passive talent auras that also reduce energy cost.

**Current behaviour**:
The energy cost of Shred with Shredding Attacks and Berserk is 12 (60 * 0.5 - 18) when it should be 21 ((60-18) * 0.5).
The energy cost of Mangle is 11.5 (45 * 0.5 - 5 - 6) when it should be 17 ((45-5-6) * 0.5)
and so on for the other spells.

This is not an issue on Trinity Core, but I haven't found the difference yet.

**Steps to reproduce the problem**:

1. make an 80 druid with talents in Shredding Attacks and Berserk
2. Use Berserk and Shred on a dummy.
3. Observe energy meter not going down to 79.

**Branch(es)**: master

**AC hash/commit**: cfd2d7e

**Comment by ShinDarth** [comment]
Missing commit hash, please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by HeartWell** [comment]
Shred cost 60 energy, learn two tal Shredding Attacks - 18 energy 60-18 = 42 if you have aura berserk -50% energy in for cat. 60-18:2= 21 right? Where bag?

**Comment by PolarCookie** [comment]
The tooltip will say 21, but if you use shred and watch the energy bar it's 12.
Very noticable when testing AC and TC next to eachother.

**Comment by HeartWell** [comment]
At the bar, I have 79 energy 100 - 21, with after using spells with aura. where you see 12 I don't know.

**Comment by PolarCookie** [comment]
Here's me testing on AC
https://webmshare.com/EBBwx

Here's me testing on TC
https://webmshare.com/wKKox

Reason I even made this ticket is because someone noticed this on Northcraft.
https://northcraft.org/bugtracker/view.php?id=693

**Comment by talamortis** [comment]
if this issue is invalid can we close?

**Comment by Viste** [comment]
we can close it all as @HeartWell  say

**Comment by lineagedr** [comment]
Confirm. After testing on https://github.com/azerothcore/azerothcore-wotlk/commit/7cf097eab2fc1425638557903f06a8922ee74ec1 

It does in fact consume 12 energy instead of 21.

There's something wrong in: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.h#L2966

No idea why this was closed.

**Comment by FrancescoBorzi** [comment]
thanks @lineagedr for your feedback

**Comment by Kitzunu** [comment]
I cannot reproduce this on a75b84ab2e4a47de8152ef9627ed3ea2ca00901a
