### ISSUE TITLE
[Mobs]Elder/Highland Razormaw in Raptor Ridge Cave in Wetlands

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#4881]
##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png) ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CHROMIE ISSUE:
https://github.com/chromiecraft/chromiecraft/issues/215

##### CONTENT PHASE:

20-29

##### SMALL DESCRIPTION:

Highland Razormaw and Elder Razormaw mobs in Raptor Ridge Cave in Wetlands(coordinates 70, 30) that are spawned in the shallow water do not move and are unable to attack unless the player is in melee range.

Zone: Wetlands

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs that are located in the shallow water should be able to move around freely and attack players when they aggro.

##### CURRENT BEHAVIOUR:

When player gets near the mobs that are standing in the shallow water in the cave they aggro and turn towards player 
but are unable to move from their spawning point so they are unable to attack players unless player comes in their melee range.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Go to Raptor Ridge Cave in Wetlands (70.6, 29.7)
Step 2 Go near Highland Razormaw or Elder Razormaw spawned in the shallow water and get their aggro
Step 3 Attack the mob in melee range and move out of it again
![WoWScrnShot_031621_155108](https://user-images.githubusercontent.com/80769357/111334174-9f7c0c00-8673-11eb-8119-ff37280bd273.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
Looks like spawn issue in DB

**Comment by nolt** [comment]
Nope its something wrong with this area, I spawned mob not in the water and they acts normal. But they cant chase me to the water, simply they stop at the edge and lost aggro in a while.

**Comment by T1ti** [comment]
personal guess : the server map consider this area underwater and those mobs can't move underwater

**Comment by Stifler82** [comment]
@nolt 
I confirm the bug, and add that it is a problem related to Vmaps
**Video Test:** [Raptor Ridge Cave](https://youtu.be/2fraaaUjavw)

**Comment by T1ti** [comment]
Water height requirement for an area with water should be increased for it to be considered underwater

Also I'm not sure how it work but what makes a creature swim might also be related to its own model size/bounding box(seems normal that a smaller creature would be consiered udnerwater in lwoer water), maybe there's an issue with that

**Comment by Stifler82** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303
