### ISSUE TITLE
learn all recipes (Learnspell) issue

### ISSUE THREAD

**Issue by Eureka26** [azerothcore/azerothcore-wotlk#4882]
##### CURRENT BEHAVIOUR:
when using  .learn all crafts,  it learn twice  [Basic Campfire]
and  [Disenchant]

<a href="https://imgur.com/H14KK2h"><img src="https://i.imgur.com/H14KK2h.png" title="source: imgur.com" /></a>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
it should learn only 1 of each one

##### STEPS TO REPRODUCE THE PROBLEM:
make a char, use .learn all recipes ) see spellbook

##### EXTRA NOTES:
pretty sure the problem is in void Player::learnSpell(uint32 spellId) 
because this also was affecting Template_Npc Module and also my own Learn_All_Talents Script, as it add twice spells. there should be a check or something  to evade the issue. but not only for recipes but  modules/scripts.

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/cdc6ce23bc3b00e9e4366265bb195a09fe27b06d

##### OPERATING SYSTEM:
window 10

##### MODULES:
Template_npc

**Comment by esanhueza** [comment]
I think you mean .learn all crafts.
I was able to reproduce this problem in rev b7aa1f301a99f5c0e12bf82654e458182d1812e0 
![error_wow](https://user-images.githubusercontent.com/5624399/111658469-230c3900-87eb-11eb-8220-4bd59126a6ef.png)

But the problem disappeared when I logged in again.

**Comment by Eureka26** [comment]
> I think you mean .learn all crafts.
> I was able to reproduce this problem in rev [b7aa1f3](https://github.com/azerothcore/azerothcore-wotlk/commit/b7aa1f301a99f5c0e12bf82654e458182d1812e0)
> ![error_wow](https://user-images.githubusercontent.com/5624399/111658469-230c3900-87eb-11eb-8220-4bd59126a6ef.png)
> 
> But the problem disappeared when I logged in again.

lol yep was .learn crafts but anyway the issue is something that involve modules/scripts and more things so it should be fixed

**Comment by UltraNix** [comment]
Fixed by 30e9ce350c11
