### ISSUE TITLE
Feature: by worldserver.conf Add a setting to allow the transaction time to loot items [$20]

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4883]
**Describe your feature request or suggestion in detail**
Blizzard has set a default time of 2 hours for trading items looted by the boss

**Describe a possible solution to your Feature or Suggestion in detail**
Blizzard has set a default time of 2 hours for trading items looted by the boss,I  hope we can add a setting to enable or disable it,Set 0 to disabled. If it is set to be greater than 0, the number of hours allowed to trade is 2. Via `worldserver.conf`

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by FrancescoBorzi** [comment]
@UltraNix you can claim: https://www.bountysource.com/issues/97181928-feature-by-worldserver-conf-add-a-setting-to-allow-the-transaction-time-to-loot-items
