### ISSUE TITLE
Update issues 486

### ISSUE THREAD

**Issue by mygithome002** [azerothcore/azerothcore-wotlk#489]
https://github.com/azerothcore/azerothcore-wotlk/issues/486

**Comment by ShinDarth** [comment]
what?

**Comment by mygithome002** [comment]
BLACK WING LAIR’ No.1 BOSS BUG

I tested ,this bug is existing too:
core:X64 (Without-Maps) 3.3.5a (With-Modules) (64-bit) MySQL 5.6 - No-Maps.rar[April-27-2017 [NEW] Release:]
http://www.ac-web.org/forums/showthread.php?224282-(3-3-5a)-AzerothCore-Repack-32x-64x-(With-Transmog)

cast no.3 spell:destory egg:
http://i2.muimg.com/577587/65e3dfd576fe3392.jpg

after spell action,egg still exist:
http://i2.muimg.com/577587/cb2229a3ee5e3d29.jpg
