### ISSUE TITLE
3 minutes respawnable wreckages

### ISSUE THREAD

**Issue by Zoidwaffle** [azerothcore/azerothcore-wotlk#4890]
From: https://github.com/chromiecraft/chromiecraft/issues/214

##### STEPS TO REPRODUCE THE PROBLEM:With a wreckage in water,fish it,wait for respawn.

Step 1 
Step 2 
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacki95** [comment]
> EXPECTED BLIZZLIKE BEHAVIOUR:Some wreckages spawn every 3 minutes after you fish them.
> CURRENT BEHAVIOUR:Some wreckages spawn every 3 minutes after you fish them

huh?

**Comment by Zoidwaffle** [comment]
Yeah, that doesn't make sense... But if you read the rest, you can see the issue is too fast respawns of the same fishing pools. I didn't change the original text, just copied it over as-is.
