### ISSUE TITLE
Feature: ServerAutoShutdown config in worldserver.conf [$25]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#4898]
```
#
#    ServerAutoShutdownEnabled
#        Description: Enable to automatically shut down the server, so it can be restarted on a daily basis
#        Default:     0 - Disabled
#                     1 - Enabled

ServerAutoShutdownEnabled = 0

#
#    ServerAutoShutdownTime
#        Description: Time (in HH:MM:SS) - 24 hours format 
#        Default:     04:00:00

ServerAutoShutdownTime = 04:00:00

#
#    ServerAutoShutdownDelay
#        Description: Seconds of delay, so the players will be informed about the server restart
#        Default:     3600 (1 hour)

ServerAutoShutdownDelay = 3600

#
#    ServerAutoShutdownAnnounce
#        Description: An announcement to be broadcasted in-game
#        Default:     "Automated (quick) server restart"

ServerAutoShutdownAnnounce = "Automated (quick) server restart"
```

**Comment by Winfidonarleyan** [comment]
I start

**Comment by Winfidonarleyan** [comment]
https://github.com/WarheadCore/mod-server-auto-shutdown

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan thanks! can you please add it to `azerothcore/` organisation and to the mod catalogue as well

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-server-auto-shutdown

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan nice, can you please make the credit headers to follow the AC format?

**Comment by Winfidonarleyan** [comment]
Okay

**Comment by FrancescoBorzi** [comment]
@azerothcore/modules @azerothcore/testers @azerothcore/developers 

I need a volunteer to test this module and its config on a non-Windows system (or on Windows using Docker because it's linux):

https://github.com/azerothcore/mod-server-auto-shutdown

**Comment by locus313** [comment]
@FrancescoBorzi i will give this a test

**Comment by locus313** [comment]
this looks pretty good. Worked on ubuntu 20.04. 

![image](https://user-images.githubusercontent.com/4015312/112214628-a60f0400-8bdc-11eb-8bdc-cb20712d8527.png)

tested making a change to the config and using `.reload conf`. Like how it displayed this:
![image](https://user-images.githubusercontent.com/4015312/112214697-bc1cc480-8bdc-11eb-8a0e-c549cd321344.png)

**Comment by FrancescoBorzi** [comment]
thank you very much @locus313 for testing this!

@Winfidonarleyan the bounty is yours!
