### ISSUE TITLE
BLACK WING LAIR’ No.1 BOSS BUG

### ISSUE THREAD

**Issue by mygithome002** [azerothcore/azerothcore-wotlk#490]
**Description**:BLACK WING LAIR’ No.1 BOSS BUG

**Current behaviour**:

cast no.3 spell:destory egg:
http://i2.muimg.com/577587/65e3dfd576fe3392.jpg

after spell action,egg still exist:
http://i2.muimg.com/577587/cb2229a3ee5e3d29.jpg

**Expected behaviour**: 
cast no.3 spell:destory egg,the egg should be disappearing.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 15.05.2017 master branch

**AC hash/commit**:https://github.com/azerothcore/azerothcore-wotlk/commit/3972a1da631144a83aff7fe76961fdac5dd1c28a

class spell_egg_event : public SpellScriptLoader
{
    public:
        spell_egg_event() : SpellScriptLoader("spell_egg_event") { }

        class spell_egg_eventSpellScript : public SpellScript
        {
            PrepareSpellScript(spell_egg_eventSpellScript);

            void HandleOnHit()
            {
                if (InstanceScript* instance = GetCaster()->GetInstanceScript())
                    instance->SetData(DATA_EGG_EVENT, SPECIAL);
            }

            void Register()
            {
                OnHit += SpellHitFn(spell_egg_eventSpellScript::HandleOnHit);
            }
        };

        SpellScript* GetSpellScript() const
        {
            return new spell_egg_eventSpellScript();
        }
};

**Operating system**:  win8.1

**Modules**:  i use modules:mod-anticheat-master;mod-duelreset-master;mod-random-enchants-master;mod-transmog-master;mod-vas-autobalance-master

**Other Customizations**: no.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by mygithome002** [comment]
I have tried to explain the situation ofthe BUG, if you still close this issue and not to deal with, then it was。。。

**Comment by ShinDarth** [comment]
I closed the issue that was not reported properly. Why didn't you fill the ``AC hash/commit:`` part?

**Comment by mygithome002** [comment]
sorry,i really don't know how to fill this  AC hash/commit:...
