### ISSUE TITLE
Pendant of the Agate Shield incorrect vendor price (ID 20950)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4902]
Pendant of the Agate Shield incorrect vendor price (ID 20950)

##### CURRENT BEHAVIOUR:

Pendant of the Agate Shield vendors for 1 copper.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should vendor for 15 silver and 35 copper.

https://wotlk.evowow.com/?item=20950

##### STEPS TO REPRODUCE THE PROBLEM:

1. Additem 20950
2. Observe sell price
3.

**Comment by r0m1ntik** [comment]
Really wtf :D
![Снимок экрана 2021-03-19 в 2 08 36](https://user-images.githubusercontent.com/40755539/111717302-12de7300-8858-11eb-97bb-3135a175c8ab.png)
![Снимок экрана 2021-03-19 в 2 08 28](https://user-images.githubusercontent.com/40755539/111717309-15d96380-8858-11eb-9a63-4859b44a9ad8.png)

**Comment by JamesGent** [comment]
https://user-images.githubusercontent.com/61194190/111833535-38b45800-88ea-11eb-9e61-d148dab6f4f2.mp4

It vendors for the correct amount, it just SHOWS the wrong amount.

It can only be fixed by a client side patch.

I'm using enUS. Madness.

**Comment by Helias** [comment]
Confirmed, I think it's more a client issue.
![image](https://user-images.githubusercontent.com/519778/111852686-379a1f80-8918-11eb-81f6-d1c7e5a817bb.png)
