### ISSUE TITLE
Line of Sight in Warsong Gulch (Graveyard Cliffs) allows attacking graveyard.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#4911]
Line of Sight in Warsong Gulch (Graveyard Cliffs) is abysmal.

##### CURRENT BEHAVIOUR:

You can attack through LOS cliffs. I died standing in the graveyard to a hunter on the lowground who was blatantly not within line of sight.

![WoWScrnShot_031921_234309](https://user-images.githubusercontent.com/61194190/111851923-0d8f3000-890d-11eb-87ff-5ed6eb467445.jpg)

![WoWScrnShot_031921_234302](https://user-images.githubusercontent.com/61194190/111851928-1122b700-890d-11eb-9f06-2cc274715ab9.jpg)

![WoWScrnShot_031921_234253](https://user-images.githubusercontent.com/61194190/111851933-13851100-890d-11eb-8f17-34a92e334b5e.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You shouldn't be able to attack through walls/cliffs.

This is especially bad because it means that a team of warlocks/hunters/ranged classes can farm people through the graveyard.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter WSG
2. 1 char low, 1 char high
3. Break LOS extremely hard
4. Attack anyway

##### EXTRA NOTES:

I'm putting not confirmed as the hunter claimed this is how it is on ClassicWoW but I don't think so given other LOS issues with Warsong Gulch such as issue #4782 

##### AC HASH/COMMIT:

AzerothCore rev. 68fab5c9cb5f+ 2021-03-16

**Comment by UltraNix** [comment]
It's blizzlike. Terrain does not block LoS.
Walls/cliffs/trees/rocks/buildings/etc do it.

**Comment by FrancescoBorzi** [comment]
thanks @JamesGent for your efforts and @UltraNix for your feedback, closing this.
