### ISSUE TITLE
Escortee despawn

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#492]
**Description**:
During escort quest, the escortee will despawn if you travel away such that the escortee is outside your view distance.
ex 1: When saving Corporal Keeshan for Missing in Action; if you feel like clearing the path ahead of him and go a bit to far, he'll be gone when you meet up with him.
ex 2: When escorting Homing Robot OOX-22/FE for Rescue OOX-22/FE!, the second ambush wave is 3 Groddoc Ape that spawn so far ahead they're outside the view distance, and they don't even charge at you (https://github.com/azerothcore/azerothcore-wotlk/issues/493). If you're impatient and feel like charging ahead towards them, the chicken will despawn.

I don't remember this happening ever on retail, never heard warnings of this behaviour, and it's highly unreasonable for a server to ruin a quest like this.

**Branch(es)**: master

**AC hash/commit**:  cfd2d7e

**Comment by talamortis** [comment]
This is blizzlike once u get out of sight or a bit to far away from the npc it should fail the quest and then despawn.
