### ISSUE TITLE
(DB/creature_text): Missing sound file for Kel'Thuzad

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#4926]
##### CURRENT BEHAVIOUR:

Sound file ID not specified in DB = No voice for that line

SQL select:
```sql
SELECT * FROM creature_text WHERE BroadcastTextId=12993;
```
![image](https://user-images.githubusercontent.com/61223313/111878144-85407780-896c-11eb-8dad-b5b7d4df5813.png)

Line: "Come, heroes... By the will of the Lich King, you shall be destroyed."

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When Sapphiron dies the whole conversation between Kel'Thuzad and The Lich King should be heard, meaning all the lines have sound files.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c sapphiron
2. Get into combat and kill it
3. Go to the Kel'thuzad door and hear each line & sound
4. The last one should be "Come, heroes... By the will of the Lich King, you shall be destroyed." linked with is sound/voice but you will not hear Kel'Thuzad's voice saying the line

##### EXTRA NOTES:

Also, TrinityCore does not have the file:
https://github.com/TrinityCore/TrinityCore/blob/1d04d5859a59caf286d71f78a18ec4ed05feb7c2/sql/old/6.x/world/00_2014_10_19/2014_12_17_00_world.sql#L7

##### AC HASH/COMMIT:

4949d3a

##### OPERATING SYSTEM:

Win 10

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

HD textures

**Comment by Voxstrasza** [comment]
This is because it does not exist.

https://www.youtube.com/watch?v=bzYx3RZ5O7E

**Comment by Si1ker** [comment]
> This is because it does not exist. There is no voice line.
> 
> https://www.youtube.com/watch?v=bzYx3RZ5O7E

u right, wtf
