### ISSUE TITLE
[quest] Rescue OOX-22/FE!

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#493]
**Description**:
For the second ambush wave of this escort event, the 3 Groddoc Apes spawn far ahead outside the view distance, and don't charge towards the chicken.
This almost guarantees everyone will fail this quest because of https://github.com/azerothcore/azerothcore-wotlk/issues/492.

**Branch(es)**: master

**AC hash/commit**:  cfd2d7e

**Comment by talamortis** [comment]
does this issue happen on the 3rd wave? aswell
