### ISSUE TITLE
[DB/Spawn] Mining Nodes: Multiple mining vein

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#4935]
##### CHROMIE ISSUE:
https://github.com/chromiecraft/chromiecraft/issues/242
https://github.com/chromiecraft/chromiecraft/issues/243
https://github.com/chromiecraft/chromiecraft/issues/247
https://github.com/chromiecraft/chromiecraft/issues/252
https://github.com/chromiecraft/chromiecraft/issues/258
https://github.com/chromiecraft/chromiecraft/issues/268

##### CURRENT BEHAVIOUR:

Swamp of Sorrows:
6629, 30348, 32291 - Iron Deposit, Iron Deposit & Silver Vein
~~6056, 32756 - Iron Deposit~~ - fix in https://github.com/azerothcore/azerothcore-wotlk/issues/4935#issuecomment-803662629

Arathi Highlands - underwater spawn locations:
63511, 63520, 65233 - Silver Vein, Gold Vein & Iron Deposit
65226, 70262, 70263, 70264, 70265, 70266, 70267 - Gold Vein, Iron Deposit, Mithril Deposit, Tin Vein, Silver Vein, Gold Vein, Truesilver Deposit

Western Plaguelands:
45561, 64098 - Small Thorium Vein, Truesilver Deposit
45502, 64001, 5816 - Gold Vein, Mithril Deposit, Gold Vein
7193, 63518 - Mithril Deposit, Gold Vein
~~7115, 45552 - Mithril Deposit~~ - fix in https://github.com/azerothcore/azerothcore-wotlk/issues/4935#issuecomment-803664934
63519, 63994 - Gold Vein, Mithril Deposit
7219, 9641 - Mithril Deposit, Truesilver Deposit
45553, 5770 - Truesilver Deposit, Gold Vein
5944, 7316 - Gold Vein, Mithril Deposit

Ashenvale - totally messedup spawn section:
~~5708, 5709, 5710, 5711, 5712, 5713 - Silver Vein~~ - fix in https://github.com/azerothcore/azerothcore-wotlk/issues/4935#issuecomment-803661856

Barrens - wrong spawn point:
~~5649 - Tin Vein~~ - fix in https://github.com/azerothcore/azerothcore-wotlk/issues/4935#issuecomment-803659384

Searing Gorge:
GUID 13216 + 13220 (Gold and Mithril)
GUID 34904 + 64839 (Mithril and Dark Iron)
GUID 29289 + 56790 (Small Thorium and Dark iron)
GUID 32285 + 64843 + 65291 (triple spawn: Truesilver, Dark Iron, Mithril)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only 1 vein should spawn at a time and in some cases wrong spawn location

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to there object
2. 
3.

**Comment by nolt** [comment]
I'm preparing DB update for bugged spawned points.

Need some one help to decide what we will do with multiple spawn points in case where we have two different mining veins. Maybe I should move and make more distance to each other? or leave only one vein but which one.

**Comment by nolt** [comment]
Barrens update:
```
UPDATE `gameobject` set `position_z`=94.7714 where (`id` = 3764 and `guid` = 5649)
```

**Comment by 55Honey** [comment]
> UPDATE `gameobject` set `position_z`=94.7714 where (`id` = 3764 and `guid` = 5649)

The guid should be unique. U don't need to check for the id here.

**Comment by 55Honey** [comment]
> I'm preparing DB update for bugged spawned points.
> 
> Need some one help to decide what we will do with multiple spawn points in case where we have two different mining veins. Maybe I should move and make more distance to each other? or leave only one vein but which one.

There should be no same spawns of minerals / herbs inside of each other or overlapping each other. We will not be able to track the perfect original data, but i am fairly sure, that all nodes -except Gravemoss- which spawn in a 10y radius, are double tracked from gathered live data in merged data sets.
This should pass as a "improvement to become more blizzlike".
I suggest multiple PRs for these. Maybe per zone or per same id of nodes.

**Comment by nolt** [comment]
> > UPDATE `gameobject` set `position_z`=94.7714 where (`id` = 3764 and `guid` = 5649)
> 
> The guid should be unique. U don't need to check for the id here.

So you say it's better to delete existing ID and spawn new one?

**Comment by nolt** [comment]
Ashenvale fix:

```
-- Delete wrong spam Silver Vein in Ashenvale
DELETE FROM `gameobject` WHERE (`id`= 1733) and `guid` in (5708, 5710, 5711, 5712, 5713);
```

**Comment by nolt** [comment]
Swamp of sorrows partial → 6056, 32756 - Iron Deposit:
```
DELETE FROM `gameobject` WHERE (`id`=1735 and `guid`=32756);
```

**Comment by nolt** [comment]
Western Plaguelands → partial for 7115, 45552 - Mithril Deposit
```
DELETE FROM `gameobject` WHERE `guid`=45552;
```

**Comment by 55Honey** [comment]
You do not need to gather all changes in the issue. Your best bet, is to fork the main repo and create an SQL patch according to [this guide](https://www.azerothcore.org/wiki/How-to-create-a-PR). Mind step 5!
Then make a Pull Request with it, when you're done coding.  List the proposed changes there and link this issue :>

**Comment by nolt** [comment]
Yea I know :) but I paste here for mine history :) I know what I have fixed and what is left.
About PR i know how to do it, thanks.

**Comment by nolt** [comment]
Arathi Highlands:
```
DELETE FROM `gameobject` WHERE `guid` in (70262, 70263, 70264, 70265, 70266, 70267);
```

**Comment by 55Honey** [comment]
You will create lots of pings with this to anyone watching the repo, i would rather save my progress e.g. in the PR.

**Comment by nolt** [comment]
Oh :) ok then :D

**Comment by nolt** [comment]
Multiple veins and decision what to leave based on veins object map at https://classic.wowhead.com/
