### ISSUE TITLE
Docker: acore-docker-build - Building with Modules fails

### ISSUE THREAD

**Issue by jpaechnatz** [azerothcore/azerothcore-wotlk#4940]
Docker: Building with Modules fails

##### CURRENT BEHAVIOUR:
If I place any module code in the modules directory, the acore-docker-build fails.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
building runs thru and everything is fine... ;-)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Place any module source in modules directory.
2. start rebuild with acore-docker-build

##### EXTRA NOTES:
Error message
100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o
fatal error: definition of macro 'CONFIG_FILE_LIST' differs between the precompiled header ('""') and the command line ('"mod_congratsonlevel.conf.dist,"')
1 error generated.
fatal error: definition of macro 'CONFIG_FILE_LIST' differs between the precompiled header ('""') and the command line ('"mod_congratsonlevel.conf.dist,"')
fatal error: definition of macro 'CONFIG_FILE_LIST' differs between the precompiled header ('""') and the command line ('"mod_congratsonlevel.conf.dist,"')
fatal error: definition of macro 'CONFIG_FILE_LIST' differs between the precompiled header ('""') and the command line ('"mod_congratsonlevel.conf.dist,"')
1 error generated.
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:106: src/server/worldserver/CMakeFiles/worldserver.dir/ACSoap/ACSoap.cpp.o] Error 1
1 error generated.
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:120: src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o] Error 1
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:78: src/server/worldserver/CMakeFiles/worldserver.dir/Main.cpp.o] Error 1
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:92: src/server/worldserver/CMakeFiles/worldserver.dir/Master.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1185: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

##### AC HASH/COMMIT:
 git log
commit 6f72d409df7a886034d9fba2a3497397b1b42528 (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Mon Mar 22 04:27:57 2021 +0000

##### OPERATING SYSTEM:
Ubuntu 18.04

##### MODULES:
For first try:
mod-congrats-on-level

##### OTHER CUSTOMIZATIONS:
None.

**Comment by FrancescoBorzi** [comment]
@jpaechnatz have you tried a clean build?

https://stackoverflow.com/questions/58202062/docker-building-deleted-modules-from-cache

**Comment by jpaechnatz** [comment]
That worked.

**Comment by Winfidonarleyan** [comment]
Need clean build for update pch files
