### ISSUE TITLE
NPC Nancy Vishas not responding to combat.

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4942]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/222

##### CURRENT BEHAVIOUR:

NPC doesn't respond to combat.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should aggro and engage in combat when hit.

Additionally, according to [a wowhead comment from 2006](https://classic.wowhead.com/npc=3984/nancy-vishas#comments:id=2801423), she should be in the house talking to herself with her father, another elite monster, triggering her dialogs, and at some point she should walk alone outside where the player can safely engage with her. I found her alone standing in the peer just like in the beginning of the video, but maybe she already followed her scenario.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to [Nancy Vishas](https://wowgaming.altervista.org/aowow/?npc=3984) and attack her.
2. No need to have debug flags on Cmake.
3. No need to look at the console while the bug happens.
4. No need for other steps.

##### EXTRA NOTES:

[Link to NPC](https://wowgaming.altervista.org/aowow/?npc=3984).

I recorded [a video](https://medal.tv/clips/46729069/d1337b2ffa6x) which is clearly showing that the NPC is not responding. The crucial part is that this NPC is part of the `Vorrel's Wedding Ring` quest. She successfully drops the quest item.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by pklloveyou** [comment]
Tested
