### ISSUE TITLE
[Quest]Going, Going, Guano! has wrong quest tracker marker

### ISSUE THREAD

**Issue by nolt** [azerothcore/azerothcore-wotlk#4944]
##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The Questlocation is according to the Text: Razorfen Kraul in Zone Durotar (south), instead the Tracker points to some weird location of a Spidernest in western Tirisfall Glades, or even further West. Since I am a total WOW newb, I was searching the Web for wtf I should do. It is totally confusing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. I picked up Quest in Zone The Barrens at Crossroads from the Apothecary guy. after I was sent there, probably for another quest.
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
I think it's releaded to this but I totally dunno how to fix it. MapID should be 47 according to https://www.azerothcore.org/wiki/Map

```
mysql> select * from quest_poi where QuestID=1109;
+---------+----+----------------+-------+----------------+-------+----------+-------+---------------+
| QuestID | id | ObjectiveIndex | MapID | WorldMapAreaId | Floor | Priority | Flags | VerifiedBuild |
+---------+----+----------------+-------+----------------+-------+----------+-------+---------------+
|    1109 |  0 |              4 |     0 |             20 |     0 |        0 |     1 |             0 |
|    1109 |  1 |             -1 |     0 |             20 |     0 |        0 |     1 |             0 |
+---------+----+----------------+-------+----------------+-------+----------+-------+---------------+
2 rows in set (0.01 sec)

mysql> select * from quest_poi_points where QuestID=1109;
+---------+------+------+------+------+---------------+
| QuestID | Idx1 | Idx2 | X    | Y    | VerifiedBuild |
+---------+------+------+------+------+---------------+
|    1109 |    0 |    0 | 2094 | 1909 |             0 |
|    1109 |    0 |    1 | 2201 | 1978 |             0 |
|    1109 |    0 |    2 | 2146 | 2012 |             0 |
|    1109 |    0 |    3 | 2132 | 2008 |             0 |
|    1109 |    0 |    4 | 2096 | 1990 |             0 |
|    1109 |    0 |    5 | 2076 | 1964 |             0 |
|    1109 |    0 |    6 | 2063 | 1937 |             0 |
|    1109 |    0 |    7 | 2059 | 1919 |             0 |
|    1109 |    1 |    0 | 1434 |  405 |             0 |
+---------+------+------+------+------+---------------+
9 rows in set (0.00 sec)
```

**Comment by FrancescoBorzi** [comment]
@nolt what is the minimum level required for this quest? so we can put either [1-19] or [20-29] accordingly

**Comment by nolt** [comment]
According to https://classic.wowhead.com/quest=1109/going-going-guano its 30lvl but we can assign it to 20-29 because its Dungeon Quest.

**Comment by eTzmNcbkrng** [comment]
https://wowwiki-archive.fandom.com/wiki/Quest:Going,_Going,_Guano!?oldid=2316406
The last update to this page prior to Cataclysm pre-patch was 8/July/2010 (a month after 3.3.5a release) which states the quest required L23 to acquire.

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you going to work on this?

**Comment by Stifler82** [comment]
@FrancescoBorzi soon..

**Comment by Stifler82** [comment]
Fixed!
-
https://user-images.githubusercontent.com/1884642/119477488-e73fa380-bd46-11eb-9270-9f50bad6ec14.mp4
