### ISSUE TITLE
Deadmines - Mr.Smite

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4945]
##### CURRENT BEHAVIOUR:
-Mr. Smite always uses his stun (Smite Slam)
-Mr Smite will aggro other nearby creatures when pulled by aggroing the blackguards ![image](https://user-images.githubusercontent.com/40864460/112096791-41818400-8b9f-11eb-9b77-494b5ed8c347.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
-He should only use his stun(Smite Slam) in hammer stance (below 33%) https://classic.wowhead.com/guides/deadmines-classic-dungeon#mr-smite. _At 33%, Smite will stun the group once again and run towards the chest. This time, he will pull out his famous 2-handed mace, granting him the  Smite Slam_
-Only Mr Smite should aggro when the blackguards are pulled.  https://youtu.be/j01MfraN6b0?t=2279 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go c id 646 and test

##### AC HASH/COMMIT:
b8c2c2311d08b2b6332ce013ecc69d4ce7e33500

**Comment by T1ti** [comment]
add this issue to 1-19

**Comment by eTzmNcbkrng** [comment]
This could more easily be fixed with #5045.

**Comment by T1ti** [comment]
Has the aggro issue been fixed too ?

**Comment by T1ti** [comment]
> The additional adds part of this issue could more easily be fixed with #5045.

I don't see how, I think it would be related to https://github.com/azerothcore/azerothcore-wotlk/issues/5455 , reduce his call for help range to 0 with a new column to set this
Perhaps there's already a way to reduce the call for help range but i'm not sure

**Comment by Branel** [comment]
The aggro issue is a issue seperate from Mr.Smite. #2588
