### ISSUE TITLE
Deadmines - Van Cleef summons adds twice

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4946]
##### CURRENT BEHAVIOUR:
Van cleef will call for help and summon blackguards at both 50% and 25% 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should only summon guards at 50%, not at 25%.
https://youtu.be/j01MfraN6b0?t=3251

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go c id 639
2. damage him and see when he summons adds

##### AC HASH/COMMIT:
b8c2c2311d08b2b6332ce013ecc69d4ce7e33500

**Comment by Kitzunu** [comment]
smart_scripts
---
```sql
SELECT * FROM smart_scripts WHERE entryorguid = 639
```
| entryorguid | source_type | id | link | event_type | event_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | action_type | action_param1 | action_param2 | action_param3 | action_param4 | action_param5 | action_param6 | target_type | target_param1 | target_param2 | target_param3 | target_param4 | target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 639 | 0 | 0 | 0 | 1 | 0 | 100 | 257 | 1000 | 1000 | 0 | 0 | 0 | 11 | 674 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Out of Combat - Cast Dual Wield | 
| 639 | 0 | 1 | 0 | 4 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - On Aggro - Say Line 0 | 
| 639 | 0 | 3 | 0 | 2 | 0 | 100 | 1 | 34 | 66 | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Between 34-66% Health - Say Line 1 | 
| 639 | 0 | 4 | 5 | 2 | 0 | 100 | 1 | 26 | 50 | 0 | 0 | 0 | 11 | 5200 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Between 26-50% Health - Cast VanCleef's Allies | 
| 639 | 0 | 5 | 0 | 61 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 2 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Between 26-50% Health - Say Line 2 | 
| 639 | 0 | 6 | 0 | 2 | 0 | 100 | 1 | 0 | 33 | 0 | 0 | 0 | 1 | 3 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Between 0-33% Health - Say Line 3 | 
| 639 | 0 | 7 | 8 | 2 | 0 | 100 | 1 | 0 | 25 | 0 | 0 | 0 | 11 | 5200 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Between 0-25% Health - Cast VanCleef's Allies | 
| 639 | 0 | 8 | 0 | 61 | 0 | 100 | 0 | 0 | 25 | 0 | 0 | 0 | 1 | 2 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - Between 0-25% Health - Say Line 2 | 
| 639 | 0 | 9 | 0 | 5 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 4 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - On Killed Unit - Say Line 4 | 
| 639 | 0 | 10 | 0 | 6 | 0 | 100 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 5 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Edwin VanCleef - On Just Died - Say Line 5 | 

```SQL
DELETE FROM `smart_scripts` WHERE `entryorguid` = 639 AND `id` IN (7,8);
UPDATE `smart_scritps` SET `id` = 7 WHERE `id` = 9 AND `entryorguid` = 639;
UPDATE `smart_scritps` SET `id` = 8 WHERE `id` = 10 AND `entryorguid` = 639;
```

**Comment by Pensukdeath** [comment]
We need a test. Can someone check on the official server?! The video is not clear.

**Comment by Pensukdeath** [comment]
![image](https://user-images.githubusercontent.com/1245535/112137498-64cd2300-8be1-11eb-8fec-6a88e6a3a10b.png)
wowhead

**Comment by markvetx** [comment]
According to [this](https://youtu.be/f1vwX_F_yqU?t=39), he is summoning 2 extra adds when VanCleef is below 25%
But.. According to [this](https://www.youtube.com/watch?v=MYh73HIPROY) he isn't.

**Comment by markvetx** [comment]
According to [this](https://youtu.be/8FZd0hdYsiU?t=938) and [this](https://www.youtube.com/watch?v=MYh73HIPROY) the boss shouldn't spawn any extra adds when below 25% of HP. Both videos are from current Classic game.

**Comment by Pensukdeath** [comment]
> According to [this](https://youtu.be/8FZd0hdYsiU?t=938) and [this](https://www.youtube.com/watch?v=MYh73HIPROY) the boss shouldn't spawn any extra adds when below 25% of HP. Both videos are from current Classic game.

OK. Thank. I'm calm)

**Comment by T1ti** [comment]
> ![image](https://user-images.githubusercontent.com/1245535/112137498-64cd2300-8be1-11eb-8fec-6a88e6a3a10b.png)
> wowhead

I have no idea where this comes from but I've never seen him summon adds twice on official

**Comment by Zoidwaffle** [comment]
I don't remember the encounter that well TBH, but the top comment here https://classic.wowhead.com/npc=639/edwin-vancleef#comments mentions summoning at 50 and 25%. So maybe that's the source? It's mentioned again near the end of the page.

**Comment by thenewblock** [comment]
https://youtu.be/xYezcS_e9tg?t=363

Looks like he only spawns adds once at 75%?

**Comment by Kitzunu** [comment]
Feel free to test the fix above

**Comment by T1ti** [comment]
> https://youtu.be/xYezcS_e9tg?t=363
> 
> Looks like he only spawns adds once at 75%?

he is super over leveled, and the reason why the NPCs appear later is because the original NPCs didn't aggro on pull because of the level difference imo

**Comment by Pensukdeath** [comment]
> Feel free to test the fix above

Above, they have already thrown off a video proof, that Van Cleef not summon, if his health is less than 25%.

**Comment by Zoidwaffle** [comment]
https://youtu.be/j01MfraN6b0?t=3232

so he starts out with 2 guards. 2 more appear around 50% health.

That's it.

So @T1ti is right.

I can't test the suggested fix as my server is fubar because of testing PR's :grin:

**Comment by T1ti** [comment]
Basically it was just one retard in Wowhead comments saying Van cleef summons adds at 25%(could have been because he got stunned, or the starting guards weren't aggroed on pull) and private servers did it :P

**Comment by T1ti** [comment]
Another suggestion, change his ability from "between 25% and 50% to like 1% and 50%", becasue I believe that currently if you sturn him and burn him below 25% during the CC duration, he will never summon the adds.
it should be "below 50%" rather than a specific range

**Comment by Zoidwaffle** [comment]
Yep, good idea. If no others decide to give it a go, I can take a look later.
