### ISSUE TITLE
Attacking NPCs does not aggro their pets

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4952]
##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

As a Druid after casting Wrath on [Razormane Hunter](https://wotlkdb.com/?npc=3265) it will initiate fight with the mob, however, it's companion wolf wont attack until it is harmed or in threat distance

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It is expected for hunters pet to attack when it's owner is threatened

##### STEPS TO REPRODUCE THE PROBLEM:

1. Approach Razormane Huner
2. Use Wrath to attack it. (I assume any ranged attack will work)

If you are not close to the Wolf, only the Razormane Hunter will attack you. 

Chromiecraft issue: https://github.com/chromiecraft/chromiecraft/issues/277
related to: azerothcore/azerothcore-wotlk#4493

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
I've started work on porting 
https://github.com/TrinityCore/TrinityCore/commit/f7a7d02a7f50400cdc2be3c4722afeefe7efce80 and other related changes. What I've ported so far fixes this particular issue but for the sake of it, all needs to be done. I attach a patch file because I no longer am working on this. If someone wishes to continue, feel free...
https://textuploader.com/ts5c1

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Razormane Wolf](https://youtu.be/mEaCcBQUlQ8)
