### ISSUE TITLE
[Wailing Caverns] [Script] Disciple of Naralex doesn't stop in fights [$15]

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#4953]
##### FACTION
Horde

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:
1-19

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Disciple of Naralex doesn't stop in fights to help and keeps going,giving you not enough time to kill all the mobs and get overwhelmed at the end.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Disciple of Naralex should stop in fights and help you kill the mobs but all the times.

Additional info: Didn't find proof that the Disciple helps or stops in fights between his 1st stop and outside the boss chamber, but I found[ this video](https://www.youtube.com/watch?v=1yAUsI88lWc) from 2011 that clearly shows that he helps in the 1st spawns and that the adds in boss chamber don't spawn all together but one by one, looks like a timer between each spawn.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Wailing Caverns
2. Kill all bosses
3. Go to disciple of Naralex
4.Tell him you're ready

##### EXTRA NOTES:

Please fix.
After last boss,the adds spawn almost all at once making it impossible to clear them all in time.

Chromiecraft issue: https://github.com/chromiecraft/chromiecraft/issues/281

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacki95** [comment]
Could the video be from a private server? The second text says "... I must cast the Spel to banish..." if I read that correctly.

**Comment by Hacki95** [comment]
Found another issue, if you fail to keep him alive and wipe he doesn't reset. I am pretty sure he should though when the group wipes because else its impossible to complete the random dungeon.

**Comment by Hacki95** [comment]
https://youtu.be/xeW3Nl9akYA?t=1830 You can see here in which frequency the adds spawn.

Also a bit before that we can see that he does indeed helps fighting the adds while he walks to cleanse the cavern.

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Disciple of Naralax](https://youtu.be/3wcq2qeFucE)
