### ISSUE TITLE
Missing SAI Feature: There is no method to select targets based on their power type

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4955]
##### CURRENT BEHAVIOUR:

- [X] The only way to have a spell casting player as a target is to use "when victim is casting any spell"

- [ ] there is no way to target only players/creatures that use mana, creatures that use mana burn/drain spells use it vs mana less players. Currently creatures that use mana drain/burn spells will cast it on any class regardless of if victim has mana or not

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- [X] A lot of mobs use a mechanic of being able to use their interrupt on any target that is casting in melee range around them, not just the victim.

See here : look at the boss using shield bash on the mage and interrupting him
https://youtu.be/vVupB139VcU?t=149
And from my experience, most mobs that have interrupts should work this way and interrupt any spellcasting in melee range

- [ ] only targeting enemies that have mana is a pretty common behavior for blizzlike npcs, a lot of them target some spells only at mana users. https://youtu.be/uDnixLCpQyo?t=217 the fight is short but that's all the footage I could find from classic, he will not use mana burn vs a warrior

##### STEPS TO REPRODUCE THE PROBLEM:

1. test a mana burn creature with a manaless class : .go c 35647 (he will cast mana burn below 80% health)
2. 
3. 

##### AC HASH/COMMIT:
ba9a09dd0cc5ed8148ea2833c665c221f2debea5

**Comment by FrancescoBorzi** [comment]
are these SAI features available in TC ?

**Comment by T1ti** [comment]
> are these SAI features available in TC ?

I don't think so.

**Comment by Gultask** [comment]
First one fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/16720

**Comment by Gultask** [comment]
I was wondering whether there should be a condition ID for ALL targeting methods, or if there should be a few more target_types (2 or 3) or if we should make it into a cast_flag.

I'm tempted to try castFlags
