### ISSUE TITLE
[quest] Wandering Shay issues

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#496]
**Description**:
This happened while doing the quest Wandering Shay in Feralas.
https://webmshare.com/KDDqr
When she started to "wander", she ran straight across the boundary and I could continue.
There was also some pathing issues around the big tree on the right side of the video.

Also, the quest did not complete when I reached Rockbiter.

Using the data files from the mega link from the installation page.
https://github.com/AzerothCore/azerothcore-wotlk/wiki/Installation

**Current behaviour**: Tell us what happens
Weird pathing issue some places.
Quest doesn't complete when reaching Rockbiter.

**Branch(es)**: master

**AC hash/commit**:   cfd2d7e

**Comment by talamortis** [comment]
i cant reproduce this issue :/ can anyone else?
