### ISSUE TITLE
Retribution "Heart of Crusader" talent isn't working properly

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4960]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/232
CURRENT BEHAVIOUR:
Heart of Crusader can't be seen on target's debuff when it's victim of a judgement [no matter if yellow, blue or red]
I can't say if does apply, but i think not.

EXPECTED BLIZZLIKE BEHAVIOUR:

This talent applies a "debuff" on target, indicating that the talent is active

STEPS TO REPRODUCE THE PROBLEM:

Just cast any judgement

EXTRA NOTES:

Links: Talent  [Heart of the Crusader](https://wowgaming.altervista.org/aowow/?spell=20337)
Video of debuff: [TUTORIAL PALADIN RETRIBUTION PVE 3.3.5](https://www.youtube.com/watch?v=27Nfx30zPpQ)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by r0m1ntik** [comment]
@Stifler82 [4585](https://github.com/azerothcore/azerothcore-wotlk/pull/4585)
