### ISSUE TITLE
Execute sometimes does no Damage

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4961]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/235

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

A week ago someone opened a ticket for execute but did not have enough information. I was recording while farming but most times this happens - it is hard to see because if Execute does no damage - the next autohit will kill the mob and its hard to see.
Today i had several times the problem that Execute does not do anything even after using it 2-3 times. 
Here is one video where you can see it very good
https://youtu.be/b3iOR69rcHA
So the Satyr drops under 20% and i keep pressing execute but nothing happens. This happens very often and even in BG - where maybe you hope to kill someone before he gets a heal of or out of range.

If I can any provide any further details here - please let me know

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Execute is meant a being a finisher so it should do damage to kill the target fast after reaching 20%
I am not sure if this is also happening in Blizzlike but definitly should not happen that often.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a Mob preferably with higher HP Pool
2. Bring it to 20% and use Execute
3. If Execute does damage - repeat the steps
    If Execute does no damage - there is the issue

Maybe you can create a dummy with <20% hp to test this

##### EXTRA NOTES:

https://youtu.be/b3iOR69rcHA

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Cinnamohn** [comment]
It's not reporting when it fails to connect with the target. I believe it can only miss, but you'll never see it in the combat log.

Take a random low-level character and a geared 80 with the caps met, turn on .cheat power/cooldown, and then spam it on a custom Lv83 dummy or something with each one.

**Comment by Algorak** [comment]
This also happens sometimes with other classes like my death knight. I spam my spells and there are no numbers or there is no miss because nothing happens. Apparently this only affects Melees.

I couldn't explain why that is, I have my hit rating and my weapons knowledge. But still this happens very often with some melee magic.
