### ISSUE TITLE
Deviate Pythons spawn in the ceiling in Wailing Caverns

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4965]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/251

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Two of the [Deviate Pythons](https://classic.wowhead.com/npc=8886/deviate-python) in [Wailing Caverns](https://classic.wowhead.com/wailing-caverns) spawn in the ceiling.

![Deviate Pythons spawn in the ceiling](https://user-images.githubusercontent.com/78349628/111847605-27158500-88d7-11eb-8cf7-35a4f7454758.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They'd be spawned on the ground beside the Druid of the Fang in that part of the cave.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go into Wailing Caverns and head for the area marked on the below image.
2. Look for the pythons in the ceiling.

![Wailing Caverns](https://user-images.githubusercontent.com/78349628/111848059-2df0c780-88d8-11eb-8be2-942cb61e3a6e.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacki95** [comment]
Don't know where it got fixed but they don't spawn in the air anymore.
