### ISSUE TITLE
Druid can perma root mobs

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4966]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/255

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

In Mulgore, as a Tauren Druid, if you cast wrath against any mob and immediately cast entangling roots followed by another wrath the mob will stand in place, then you can keep casting any spell and the move will not move, but if you jump, change you camera direction or move towards any direction(forward, backwards, left or right) then mob will approach and attack.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I expected the mob to approach me after breaking entangling roots by damaging it with wrath, this makes leveling a druid even easier

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Cast Wrath on a mob
2.  IMMEDIATELY (it will not work if you don't cast it IMMEDIATELY after wrath) cast entangling roots
3.  IMMEDIATELY (same as 2.)cast wrath
4. profit from a perma root
![WoWScrnShot_031921_215925](https://user-images.githubusercontent.com/39318044/111857325-ae2a2380-88fe-11eb-81c0-fb7984b19880.jpg)

##### EXTRA NOTES:

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Confirmed!
-
**Video Test:** [Druid can perma root mobs](https://youtu.be/vT_DhWfsWUg)

**Comment by Stifler82** [comment]
It is probably an issue related to this problem as well.
https://github.com/chromiecraft/chromiecraft/issues/125

**Comment by T1ti** [comment]
This sounds like it is related to this https://github.com/azerothcore/azerothcore-wotlk/issues/5039#issuecomment-808933825
