### ISSUE TITLE
Lack of herb and mining nodes in Eversong Woods and Ghostlands

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4967]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/262

##### FACTION

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Few herb and mining nodes in Eversong Woods. The only rich area in herbs is East from Silvermoon City.
Especially very few mining nodes in Ghostlands, there are only some around the Gnoll area to the West from Tranquillien.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Eversong Woods should be probably rich in low level nodes,
For Ghostlands there should be more mining nodes.

##### EXTRA NOTES:

This report is made both on my personal feeling as when I leveled up a character with mining throughout the Ghostlands being at the times the only person in the zone, as well as with the concern of the world chat being in doubt of so only few herb/mining nodes there.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
Eversong Woods should be OK for mining nodes?

https://github.com/azerothcore/azerothcore-wotlk/pull/4634

Just checked and found 26 minerals (the pool says 30, but those numbers seem to be slightly off often).

![eversong_minerals](https://user-images.githubusercontent.com/541438/112315219-35ceb400-8caa-11eb-9883-8d5867c55520.png)

I have not investigated missing herbs.

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers can anyone have a look at this?

**Comment by Hacki95** [comment]
Is on my extended list
