### ISSUE TITLE
[quest] Tooga's Quest

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#497]
Description:
This happened while doing the quest Tooga's Quest in Tanaris.
https://webmshare.com/zNNbK
Notice the line in the ground, I tried going south a bit, but no luck getting him over it so I gave up.

Using the data files from the mega link from the installation page.
https://github.com/AzerothCore/azerothcore-wotlk/wiki/Installation

This route is the best since you avoid walking through the Wastewander territory, this quest might be practically impossible to complete.

Branch(es): master

AC hash/commit: cfd2d7e

**Comment by talamortis** [comment]
cant reproduce this issue can anyone else?

**Comment by BarbzYHOOL** [comment]
Needs different waypoints maybe?

**Comment by poszer** [comment]
False report. Quest tested, everything work fine.  **Can Close**
Images included at the way on quest / finish
http://prntscr.com/ls0p0t
http://prntscr.com/ls0v1y
http://prntscr.com/ls0viz
http://prntscr.com/ls0vv4

**Comment by BarbzYHOOL** [comment]
either it's because the maps improved or because it's a very special place to be at

but let's close for now, thanks guys
