### ISSUE TITLE
Specific Bandage item [Warsong Gulch Silk Bandage] does not apply Recently Bandaged Debuff

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4970]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/269

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Specific Bandage item [Warsong Gulch Silk Bandage] does not apply Recently Bandaged Debuff 

![ads](https://user-images.githubusercontent.com/47978220/111910379-c9657200-8a69-11eb-8c41-6927997bcb1c.JPG)

[Warsong Gulch Silk Bandage] obtainable from the WSG Honor vendor

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Any bandage used should apply the Recently Bandaged debuff 

![3215](https://user-images.githubusercontent.com/47978220/111910365-c10d3700-8a69-11eb-9204-6f4518f83745.JPG)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Buy [Warsong Gulch Silk Bandage] from the Wsg honor vendor (from Stormwind in my case)
2. Join Warsong Gluch
3. Use the Bandages
4. Notice that there is no debuff applied 

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by AbraKabastard** [comment]
```sql
UPDATE item_template SET ScriptName='spell_gen_bandage' WHERE entry = 19068;
```
This should work

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [PvP Bandages](https://youtu.be/JOtWVW9YndM)
