### ISSUE TITLE
Redridge zone Peacebloom spawn inside of a tree

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4971]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/270
Related: https://github.com/chromiecraft/chromiecraft/issues/261

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

![Wow_JVIWAIvV8j](https://user-images.githubusercontent.com/24726811/111921289-75eb2800-8a59-11eb-9177-b848cd938969.png)
This peacebloom spawn is currently inside of a tree

View around the tree:
![Wow_OAgEnXF3l7](https://user-images.githubusercontent.com/24726811/111921303-80a5bd00-8a59-11eb-8dcc-6b871d8de2da.png)
![Wow_a2r8kQ3DWt](https://user-images.githubusercontent.com/24726811/111921304-826f8080-8a59-11eb-85c2-7cce09126c9e.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herb spawns should not be inside other objects, making them inaccessible

The peacebloom spawn should be accessible

##### STEPS TO REPRODUCE THE PROBLEM:

1. Visit Redridge at -9746, 1772, 52.665
2. Observe that peacebloom spawn 1374 (entry 1618) is not accessible by player

##### EXTRA NOTES:

![Wow_JVIWAIvV8j](https://user-images.githubusercontent.com/24726811/111921361-c4002b80-8a59-11eb-9eea-d4afd56005b0.png)

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
Thanks for the link but I have more than one issue with the same problem... and didnt checked all of them while in other hand im preparing PR for it...

**Comment by nolt** [comment]
This issue releated to the same map: https://github.com/chromiecraft/chromiecraft/issues/261

PR is almost done
