### ISSUE TITLE
Stonelaton mountains unreachable herb

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4972]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/273

##### FACTION
Alliance

- [ ] Alliance
- [ ] Horde

##### CONTENT PHASE:
Generic

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Found a wild steelbloom herb that is unreachable without a flying mount.
Coordinates 37.6 40,5

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herb supposed to be reachable to be gathered.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stonelatons Mountains
2. Coordinates 37.6 40.5
3. Look at the wild steelbloom
4.Unable to reach it

##### EXTRA NOTES:

For more info the coordinates are on the road entering Charred vale

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by nolt** [comment]
Thanks for the link but I have more than one issue with the same problem... and didnt checked all of them while in other hand im preparing PR for it...

**Comment by Si1ker** [comment]
Fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/4985
