### ISSUE TITLE
Install path is bugged

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4974]
##### CURRENT BEHAVIOUR:
-When doing a fresh install of AC, the server will build executables in build/Bin/release-debug regardless of the install path you chose in Cmake.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Clone a fresh install and choose an install path in cmake
2. 2. see where it builds and test that install path

##### EXTRA NOTES:
I have that issue happen to several members of my project, they all struggled with the install paths

##### AC HASH/COMMIT:
7dced8456f67862abee23fe88085fd1e27f993ec

##### OPERATING SYSTEM:
Windows 10

**Comment by Kitzunu** [comment]
I believe it will always create the folders bin and debug/relwithdebinfo/release so the question is, in your CMake, did you specify the path to the "Build" folder?

**Comment by Zoidwaffle** [comment]
I checkout the code, the create a "build" folder, from within that:

`cmake ../ -DCMAKE_INSTALL_PREFIX="/your/path/here" <other parameters>` and then `make -j $(nproc) && make install`.

I just rebuild master earlier today, worked fine. Or maybe I misunderstood the issue?

**Comment by T1ti** [comment]
well for me cmake install prefix just gets ignored on windows 
Though I rememer that it worked on my debian VPS

**Comment by Si1ker** [comment]
Hi, just to check, if not related just tell me  x)

Has this anything to do with this PR https://github.com/azerothcore/azerothcore-wotlk/pull/3196
or this issue? https://github.com/azerothcore/azerothcore-wotlk/issues/1064

It just sounds familiar, but idk.

**Comment by Hacki95** [comment]
I think this has something to do you have writing rights to the chosen directory without admin.

If you choose C:/Program Files(x86)/AzerothCore it sometimes cant make the folder, but if you use something like D:/AzerothCore it works (atleast for me).

**Comment by Hacki95** [comment]
> 
> 
> I think this has something to do you have writing rights to the chosen directory without executing Visual Studio as admin.
> 
> If you choose C:/Program Files(x86)/AzerothCore it sometimes cant make the folder, but if you use something like D:/AzerothCore it works (atleast for me).

**Comment by Hacki95** [comment]
> 
> 
> I think this has something to do with if you have writing rights to the chosen directory without executing Visual Studio as admin.
> 
> If you choose C:/Program Files(x86)/AzerothCore it sometimes cant make the folder, but if you use something like D:/AzerothCore it works (atleast for me).

**Comment by T1ti** [comment]
No I chose my E drive and I run VS as admin.
It also happened to all my project members.
I should speciy that we use a fork so that may be the reason, but we didn't modify any of that

**Comment by Hacki95** [comment]
I just compiled it today under windows and it worked for me.

Let me delete my folder and try again.

**Comment by T1ti** [comment]
The issues Si1ker posted are related to branch/upstream so that could very well be an issue only for forks

**Comment by Hacki95** [comment]
![grafik](https://user-images.githubusercontent.com/62942638/112394579-45c3b380-8cfd-11eb-93c4-efd8a6bbd925.png)
No problem here.


I just realised something though, did you rightclick on the "INSTALL" and hit "Build"? You need to do it manually after you compiled your core.

**Comment by thenewblock** [comment]
> ![grafik](https://user-images.githubusercontent.com/62942638/112394579-45c3b380-8cfd-11eb-93c4-efd8a6bbd925.png)
> No problem here.
> 
> I just realised something though, did you rightclick on the "INSTALL" and hit "Build"? You need to do it manually after you compiled your core.
> 
> ![grafik](https://user-images.githubusercontent.com/62942638/112394801-95a27a80-8cfd-11eb-8a14-d621092b238e.png)

This worked

**Comment by T1ti** [comment]
> ![grafik](https://user-images.githubusercontent.com/62942638/112394579-45c3b380-8cfd-11eb-93c4-efd8a6bbd925.png)
> No problem here.
> 
> I just realised something though, did you rightclick on the "INSTALL" and hit "Build"? You need to do it manually after you compiled your core.
> 
> ![grafik](https://user-images.githubusercontent.com/62942638/112394801-95a27a80-8cfd-11eb-8a14-d621092b238e.png)

maybe that should be added to the wiki....
