### ISSUE TITLE
Battered Junkboxes no loot

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4979]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/284

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Battered Junkboxes are empty,opened about 10 and none had any loot.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Battered Junkboxes should have loot.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a Battered Junkbox
2. Open it
3. See there is no loot
4.Do it again

##### EXTRA NOTES:

Type here.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
it has loot, just very low chanses
item_loot_template
---
```sql
SELECT * from item_loot_template WHERE entry = 16882
```
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 16882 | 422 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Dwarven Mild | 
| 16882 | 929 | 0 | 10,1 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Healing Potion | 
| 16882 | 1206 | 0 | 1,3 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Moss Agate | 
| 16882 | 1529 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Jade | 
| 16882 | 1705 | 0 | 1,7 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Lesser Moonstone | 
| 16882 | 1710 | 0 | 0,1 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Greater Healing Potion | 
| 16882 | 2836 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Coarse Stone | 
| 16882 | 2883 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Plans: Deadly Bronze Poniard | 
| 16882 | 3013 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Scroll of Protection | 
| 16882 | 3357 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Liferoot | 
| 16882 | 3393 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Recipe: Minor Magic Resistance Potion | 
| 16882 | 3608 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Plans: Mighty Iron Hammer | 
| 16882 | 3864 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Citrine | 
| 16882 | 3874 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Plans: Polished Steel Boots | 
| 16882 | 4348 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Pattern: Phoenix Gloves | 
| 16882 | 4350 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Pattern: Spider Silk Slippers | 
| 16882 | 4410 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Schematic: Shadow Goggles | 
| 16882 | 4412 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Schematic: Moonsight Rifle | 
| 16882 | 4999 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Azora's Will | 
| 16882 | 5374 | 0 | 10,8 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Small Pocket Watch | 
| 16882 | 5498 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Small Lustrous Pearl | 
| 16882 | 5500 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Iridescent Pearl | 
| 16882 | 5503 | 0 | 0,1 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Clam Meat | 
| 16882 | 5504 | 0 | 0,6 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Tangy Clam Meat | 
| 16882 | 5568 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Smooth Pebble | 
| 16882 | 5578 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Plans: Silvered Bronze Breastplate | 
| 16882 | 6046 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Plans: Steel Weapon Chain | 
| 16882 | 6391 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Pattern: Stylish Green Shirt | 
| 16882 | 6409 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Insignia Belt | 
| 16882 | 6613 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Sage's Bracers | 
| 16882 | 7363 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Pattern: Pilferer's Gloves | 
| 16882 | 11098 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Formula: Enchant Cloak - Lesser Shadow Resistance | 
| 16882 | 11967 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Zircon Band | 
| 16882 | 11983 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Chrome Ring | 
| 16882 | 11984 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Cobalt Ring | 
| 16882 | 11994 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Coral Band | 
| 16882 | 12006 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Meadow Ring | 
| 16882 | 12007 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Prairie Ring | 
| 16882 | 12008 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Savannah Ring | 
| 16882 | 12052 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Ring of the Moon | 
| 16882 | 12053 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Volcanic Rock Ring | 
| 16882 | 12054 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Demon Band | 
| 16882 | 16746 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Warsong Report | 
| 16882 | 16882 | 0 | 0,2 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Battered Junkbox | 
| 16882 | 17124 | 0 | 0,05 | 0 | 1 | 0 | 1 | 1 | Battered Junkbox - Syndicate Emblem |
