### ISSUE TITLE
How-to make salt hash using PHP to register new account from web?

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#4982]
What is the PHP-algorythm to make salt and verifier data after UltraNix removed Sha_pass_hash ?

commit 485f7e76391a5bbf1af6b3219d27db721af38440

We used before:` $sha_pass_hash = getPasswordHash($account_name, $password);`

And how to make salt and verifier to register new account now?

May be wee ned to place somewhere detailed instruction with examples ?

**Comment by FrancescoBorzi** [comment]
hi @Bogir this is indeed valid question but please use stackoverflow (github is for bug reports or core feature requests):

https://www.azerothcore.org/wiki/How-to-ask-for-help
