### ISSUE TITLE
NPC "Fenros" not dropping [Tribal Worg Helm] / Loot Table bug

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4986]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/285

##### FACTION

- [x ] Alliance
- [x ] Horde

##### CONTENT PHASE:

- [x ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The Rare NPC [Fenros](https://wowgaming.altervista.org/aowow/?npc=507#drops) is not dropping Item [[Tribal Worg Helm]](https://wowgaming.altervista.org/aowow/?item=6204). It is supposed to have around a 32% dropchance. I have personally killed it 5 times and everytime it just drops [[Ravenwood Bow]](https://wowgaming.altervista.org/aowow/?item=4474).

After getting frustrated, I went and checked the database file noticed that it has a whooping 0% chance to drop. This item is also not found in any reference loot table, so it's virtually impossible to obtain right now.

![0%](https://user-images.githubusercontent.com/32701428/112361086-67934b00-8ca9-11eb-8406-f6a4165fac15.PNG)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Item drops from Fenros 32% of the time.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill Fenros many times.
2. Notice it never drops Tribal Worg Helm.
3. Go check or download the creature_loot_template.sql at chromiecraft azerothcore database.
4. Notice it has a 0 on the entry for drop chance.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
MangOS use 25% in their DB
(65009,6204,25,1,1,1,0,'Tribal Worg Helm'),
from this commit https://github.com/cmangos/classic-db/commit/eb37cbe0f660d950f7766ed2e1e253d2c8d6bd48

**Comment by Zoidwaffle** [comment]
I believe the drop rate is set to 32% already.

You are just very unlucky.

There is a `GroupId=2` for some of the loot. This is the entire table:
```
+-------+-------+-----------+--------+---------------+----------+---------+----------+----------+-------------------------------------------------------+
| Entry | Item  | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment                                               |
+-------+-------+-----------+--------+---------------+----------+---------+----------+----------+-------------------------------------------------------+
|   507 |   929 |         0 |      2 |             0 |        1 |       0 |        1 |        1 | Fenros - Healing Potion                               |
|   507 |  1205 |         0 |      6 |             0 |        1 |       0 |        1 |        1 | Fenros - Melon Juice                                  |
|   507 |  1529 |         0 |    0.2 |             0 |        1 |       0 |        1 |        1 | Fenros - Jade                                         |
|   507 |  1712 |         0 |    0.2 |             0 |        1 |       0 |        1 |        1 | Fenros - Scroll of Spirit II                          |
|   507 |  2290 |         0 |    0.4 |             0 |        1 |       0 |        1 |        1 | Fenros - Scroll of Intellect II                       |
|   507 |  3385 |         0 | 0.9852 |             0 |        1 |       0 |        1 |        1 | Fenros - Lesser Mana Potion                           |
|   507 |  3832 |         0 |    0.2 |             0 |        1 |       0 |        1 |        1 | Fenros - Recipe: Elixir of Detect Lesser Invisibility |
|   507 |  4474 |         0 |     68 |             0 |        1 |       2 |        1 |        1 | Fenros - Ravenwood Bow                                |
|   507 |  4606 |         0 |      6 |             0 |        1 |       0 |        1 |        1 | Fenros - Spongy Morel                                 |
|   507 |  4634 |         0 |    0.2 |             0 |        1 |       0 |        1 |        1 | Fenros - Iron Lockbox                                 |
|   507 |  5637 |         0 |      6 |             0 |        1 |       0 |        1 |        1 | Fenros - Large Fang                                   |
|   507 |  6204 |         0 |      0 |             0 |        1 |       2 |        1 |        1 | Fenros - Tribal Worg Helm                             |
|   507 | 24047 |     24047 |      5 |             0 |        1 |       1 |        1 |        1 | Fenros - (ReferenceTable)                             |
|   507 | 24048 |     24048 |      1 |             0 |        1 |       1 |        1 |        1 | Fenros - (ReferenceTable)                             |
|   507 | 24050 |     24050 |      1 |             0 |        1 |       1 |        1 |        1 | Fenros - (ReferenceTable)                             |
|   507 | 24052 |     24052 |      1 |             0 |        1 |       1 |        1 |        1 | Fenros - (ReferenceTable)                             |
|   507 | 24058 |     24058 |      5 |             0 |        1 |       1 |        1 |        1 | Fenros - (ReferenceTable)                             |
+-------+-------+-----------+--------+---------------+----------+---------+----------+----------+--------------------------------------------------
```
He should always drop the MinCount from any GroupId not being 0.

So he will drop Ravenwood Bow 68% of the time. The number "0" for Tribal Worg Helm is not "0%" but "it has an equal chance with all other loot having 0". Since it's the only piece of loot besides the bow, it's 32%.

I went and killed him 6 times. He also dropped the bow 4 times and the head-gear 2 times.

It would be nice if someone could confirm my understanding of the loot-table, but I think it works as intended in this case.

**Comment by Zoidwaffle** [comment]
I added a "not confirmed" for now as I believe it works.

**Comment by Stifler82** [comment]
Hi @Zoidwaffle, has a PR been done on this drop already?

**Comment by Stifler82** [comment]
It seems to works to me..
So for me the report is Invalid..
As I believe you can also notice from my video:
**Video Test:** [Tribal Worg Helm](https://youtu.be/gpXNzH219EE)

**Comment by Zoidwaffle** [comment]
@Stifler82 yeah, no PR needed, it works as intended. The reporter just had bad luck.
