### ISSUE TITLE
Issue with Reload commands [$20]

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4991]
##### CURRENT BEHAVIOUR:
-When using the reload creature_template command, server will close.
-.reload smart_scripts doesn't seem to do anything

##### EXPECTED BLIZZLIKE BEHAVIOUR:
-don't crash
-smart script should update

##### STEPS TO REPRODUCE THE PROBLEM:
1. find a creature, get his entry ID, do the command, see if it crashes
2. change a creature's SAI, use the sai reload command and see if it updates

##### EXTRA NOTES:
Seems like a lot of .reload commands are broken

##### AC HASH/COMMIT:
83e430f28a25b33175569749a0aec46ccc92c9b6

##### OPERATING SYSTEM:
windows 10

**Comment by AbraKabastard** [comment]
Did you kill ans respawn the npc after smartai reload?

**Comment by r0m1ntik** [comment]
Confirm, conflit after[2031e55]( https://github.com/azerothcore/azerothcore-wotlk/commit/2031e55ec7025c25ac0d9ebba6f2e3efba809fec#diff-59e59afabb9e07b951f9cd43dc7ef08e8c894b2aa889ae394fc4ace2eef09242)

**Comment by thenewblock** [comment]
Can confirm also. Tried killing and respawning.

**Comment by Si1ker** [comment]
> Can confirm also. Tried killing and respawning.

![image](https://user-images.githubusercontent.com/61223313/112520539-2494ae80-8d61-11eb-9dd3-f96d39f0145a.png)
![image](https://user-images.githubusercontent.com/61223313/112520544-265e7200-8d61-11eb-9a0b-55ec5e1035af.png)
![image](https://user-images.githubusercontent.com/61223313/112520551-28c0cc00-8d61-11eb-9535-effefbc0ba3c.png)


???

**Comment by Si1ker** [comment]
-> .reload creature_template `id of the npc`
-> crash

![image](https://user-images.githubusercontent.com/61223313/112523330-480d2880-8d64-11eb-9bc2-6f2439d0d12f.png)

AC hash/commit = b093380

**Comment by T1ti** [comment]
for creature_template, it's probably because the command isn't updated for the new creature_template structure after the dmg changes

**Comment by thenewblock** [comment]
@Winfidonarleyan Does #5020 also fix the smart_script issue?

**Comment by Winfidonarleyan** [comment]
Try

**Comment by thenewblock** [comment]
Issue should be reopened as .reload smart_scripts still does not work.

**Comment by Winfidonarleyan** [comment]
How to repeat problem?

**Comment by thenewblock** [comment]
Change a smart script and reload it in game.

**Comment by Winfidonarleyan** [comment]
Need example

**Comment by thenewblock** [comment]
Ok, so Hamhock in Stockades for example.

If you change his spell Chain Lightning (421) to Fireball (133) and then .reload smart_scripts you _should_ be able to go ingame and do .reload smart_scripts, kill and respawn him and he will cast fireball instead of chain lightning. 

Right now doing the command and respawning him does nothing, you have to restart the world server.

**Comment by Winfidonarleyan** [comment]
Sql please

**Comment by thenewblock** [comment]
`SET @ENTRY := 1717;
DELETE FROM smart_scripts WHERE entryOrGuid = 1717 AND source_type = 0;
UPDATE creature_template SET AIName="SmartAI" WHERE entry= @ENTRY;
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) VALUES
(@ENTRY, 0, 0, 0, 0, 0, 100, 0, 1000, 1000, 4000, 7000, 11, 133, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, "Every 4 - 7 seconds (1 - 1s initially)  - Self: Cast spell Fireball (133) on Victim"),
(@ENTRY, 0, 1, 0, 0, 0, 100, 1, 5000, 5000, 0, 0, 11, 6742, 32, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Time = 5 seconds  - Self: Cast spell Bloodlust (6742) on Self (flags: aura not present)"),
(@ENTRY, 0, 2, 0, 16, 0, 100, 0, 6742, 30, 10000, 10000, 11, 6742, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, "When friendly unit in range 30 yards has not got aura Bloodlust (6742) (check every 10000 - 10000) - Self: Cast spell Bloodlust (6742) on Friendly unit"),
(@ENTRY, 0, 3, 0, 4, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "On aggro - Self: Talk 0 to invoker");
DELETE FROM conditions WHERE SourceTypeOrReferenceId = 22 AND SourceEntry = 1717 AND SourceId = 0;`

**Comment by Winfidonarleyan** [comment]
Need readd npc in world or unbind instance after `.reload sm`

**Comment by Winfidonarleyan** [comment]
Any other questions?

**Comment by FrancescoBorzi** [comment]
> Need readd npc in world or unbind instance after `.reload sm`
> Commnd `.reload smart_scripts` don't work differently
> @thenewblock try check this command in older revision, result will be the same as now

@T1ti @thenewblock please try this and let us know

**Comment by Kitzunu** [comment]
the weird thing is that this worked a couple of months back when I last worked with sai

**Comment by Pholoween** [comment]
My client doesn't crash but set HP to 1 and make mob fly
![WoWScrnShot_040621_105345](https://user-images.githubusercontent.com/76223768/113685435-8bea2100-96c6-11eb-9234-00e985ea4f66.jpg)

**Comment by Winfidonarleyan** [comment]
Any news?

**Comment by Pholoween** [comment]
Hi, no issue remaining :)

**Comment by Winfidonarleyan** [comment]
@T1ti
