### ISSUE TITLE
Warlock's imp doesn't auto cast Blood Pact [$10]

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4992]
##### CURRENT BEHAVIOUR:
-With auto cast on, the imp won't auto cast Blood Pact even if it's not activated

##### EXPECTED BLIZZLIKE BEHAVIOUR:
If blood pact is not activated and auto cast is on, always activate it

##### SOURCE:
83e430f28a25b33175569749a0aec46ccc92c9b6

##### STEPS TO REPRODUCE THE PROBLEM:
1. Play warlock, summon an imp
2. Toggle auto cast (right click the ability)
3. try many different things to try to get him to auto cast the buff, like dying, resummoning etc

##### EXTRA NOTES:
Seems like he will auto cast it only if he gets atatcked, just like his other ability Fire shield, probably a bug related to that.

##### AC HASH/COMMIT:
83e430f28a25b33175569749a0aec46ccc92c9b6

**Comment by r0m1ntik** [comment]
Confirm

**Comment by Bloodelf94** [comment]
for me it seems Imps rank 1 for blood elf warlocks can't shoot fireballs, only if  i click fire all the time? same in rank 2 of same imp fireballs disapear as a spell for it and adds health bonus for party and raid members. now imp can't even auto attack, not that it could before either.

**Comment by T1ti** [comment]
Imp can't auto attack on retail/classic, it's normal

**Comment by Bloodelf94** [comment]
> Imp can't auto attack on retail/classic, it's normal

oh alright, never played Warlock before now. but though it worked as a hunter pet in functions. 
Seems to me there wont be any reason to summon them if you got to control their attack while you use your own attack. But thank you very much for the reply :-) 

I dont know how to update DB / server. but tried follow a tutorial where i made a git pull. if my server is updated i really dont know, but tried making a warlock now and now it got 5 spells and react a little bit better when i click fire. got to play around with it a little bit more. Thank you again. :-)

**Comment by T1ti** [comment]
> > Imp can't auto attack on retail/classic, it's normal
> 
> oh alright, never played Warlock before now. but though it worked as a hunter pet in functions.
> Seems to me there wont be any reason to summon them if you got to control their attack while you use your own attack. But thank you very much for the reply :-)
> 
> I dont know how to update DB / server. but tried follow a tutorial where i made a git pull. if my server is updated i really dont know, but tried making a warlock now and now it got 5 spells and react a little bit better when i click fire. got to play around with it a little bit more. Thank you again. :-)

What I meant by auto attack is physical attacks(melee hits)
Imps are unable to melee hit, but they can still auto cast firebolt which is their main ability

**Comment by Bloodelf94** [comment]
> > > Imp can't auto attack on retail/classic, it's normal
> > 
> > 
> > oh alright, never played Warlock before now. but though it worked as a hunter pet in functions.
> > Seems to me there wont be any reason to summon them if you got to control their attack while you use your own attack. But thank you very much for the reply :-)
> > I dont know how to update DB / server. but tried follow a tutorial where i made a git pull. if my server is updated i really dont know, but tried making a warlock now and now it got 5 spells and react a little bit better when i click fire. got to play around with it a little bit more. Thank you again. :-)
> 
> What I meant by auto attack is physical attacks(melee hits)
> Imps are unable to melee hit, but they can still auto cast firebolt which is their main ability

No problem. didn't know that regarding melee. But they can't seem to auto fire spells. Tried making set to auto and activate it's buff. But it just stands and takes the damage. i got to click the manual fire button. But i think you guys are handling it now. it is just me that needs to know how to update the DB. will probely make a thread later today :-)
