### ISSUE TITLE
Error prompt fatal error C1001: an internal error occurred in the compiler，All structure errors come from "password verification aspect submission"

### ISSUE THREAD

**Issue by hahalmtdhl** [azerothcore/azerothcore-wotlk#4994]
CURRENT BEHAVIOUR:

Compilation errors after git pull
All structure errors come from "password verification aspect submission"
Error prompt fatal error C1001: an internal error occurred in the structure
![qq222](https://user-images.githubusercontent.com/18229643/112419388-50666300-8d66-11eb-9e51-ef4a597842a1.png)

STEPS TO REPRODUCE THE PROBLEM:

Debug or release will not succeed

EXTRA NOTES:

The code is the latest clone

AC HASH/COMMIT:
#https://github.com/azerothcore/azerothcore-wotlk/commit/7dced8456f67862abee23fe88085fd1e27f993ec

OPERATING SYSTEM:

Windows 10

**Comment by hahalmtdhl** [comment]
It has been solved. It can be solved by replacing the previous vs2017 version with the 2019 version

**Comment by Kitzunu** [comment]
VS17 not supported, use 19
