### ISSUE TITLE
(scripts/Patchwerk): Hateful Strike does not hit third target [25-mode]

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#5003]
## CURRENT BEHAVIOUR:

On the 25 mode of Naxxramas, the boss Patchwerk does not cast Hateful Strike on the third possible target.

## EXPECTED BLIZZLIKE BEHAVIOUR:

On the 25 mode of [Naxxramas](https://wowpedia.fandom.com/wiki/Naxxramas), the boss [Patchwerk](https://www.wowhead.com/npc=16028) should cast a secondary Hateful Strike sequence on the third available target within the melee range with the highest health.

## SOURCE:

![image](https://user-images.githubusercontent.com/61223313/112539960-3ed98700-8d77-11eb-98a9-00d011154622.png)
Link: https://wowwiki-archive.fandom.com/wiki/Patchwerk 

## STEPS TO REPRODUCE THE PROBLEM:

1. You will need to have 3 characters & adjust the raid mode to 25
2. .go c id 16028    (with your 3 characters)
3. Enter in combat and separate the 3 characters:
FIRST- Is gonna receive normal melee hits
SECOND- Will receive Hateful Strike
THIRD- nothing

## EXTRA NOTES:
TC has it fixed but I'm not able to recreate it for AC:
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Northrend/Naxxramas/boss_patchwerk.cpp#L120

## AC HASH/COMMIT:
983a9ed

## OPERATING SYSTEM:

Win 10

## MODULES:

N/A

## CUSTOMIZATIONS:

N/A

**Comment by GMKyle** [comment]
I think the  issue is in Hateful Strike's target selection in 25 mode, we apply the same target selection (10m mode) no matter instance mode(10/25) 
Reading the code's comments 
```US : // Cast Hateful strike on the player with the highest amount of HP within melee distance, and second threat amount```
```TC:  // Hateful Strike targets the highest non-MT threat in melee range on 10man
// and the higher HP target out of the two highest non-MT threats in melee range on 25man```
```c++
pHatefulTarget = (secondThreat->GetVictim()->GetHealth() < thirdThreat->GetVictim()->GetHealth()) ? thirdThreat->GetVictim() : secondThreat->GetVictim();
```
Hateful Strike hit only 1 target , the 2 off-tanks are needed to fully protect melee as wiki notes says.

**Comment by Nefertumm** [comment]
The good old issue again... I will try to solve this.

**Comment by francovilla** [comment]
Close this :), the explanation is simple:

What is cast to 2 melee targets apart from the tank is Threat, not Hateful ...

The wiki recommends 2 tanks because one can die from Hateful and another would remain...

I was looking at the code in TC and Hateful only casts once in the melee with more life (tank):

   `DoCast (pHatefulTarget, SPELL_HATEFUL_STRIKE, true);`
