### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5008]
![image](https://user-images.githubusercontent.com/18187177/112615672-beda1c80-8e5d-11eb-9461-45331ade579f.png)

## AC HASH/COMMIT:

877e394e04e13662554f8cce663bea1c646a98d2

## OPERATING SYSTEM:
ubuntu 18.04

## MODULES:
https://github.com/azerothcore/mod-world-chat

**Comment by Zoidwaffle** [comment]
Hehe, was about to comment when you closed it. Happy to know you resolved it yourself :+1:

**Comment by mpfans** [comment]
> Hehe, was about to comment when you closed it. Happy to know you resolved it yourself 👍

I didn't solve it. It was the module that caused the compilation failure

You can't use any module now, otherwise it will fail to compile

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/112619391-4033ae00-8e62-11eb-9541-a8a4057fa804.png)

https://github.com/azerothcore/mod-multi-client-check

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/112620333-58f09380-8e63-11eb-9b30-6f6fff8aa065.png)

https://github.com/azerothcore/mod-anticheat

**Comment by Zoidwaffle** [comment]
OK, last I recompiled was yesterday - I will do it again now with my normal modules. I do not have the 2 you mention above though. If I don't see any errors, I can try with the modules you mention as well.

**Comment by Zoidwaffle** [comment]
I'm using Debian Testing. I used to use Debian 10, but it stopped working for the map extraction tools recently so I was forced into using Testing as not enough was available in backports. Just to say our systems aren't the exact same.

I see you are using Ubuntu 18.04, perhaps it would be worth it to upgrade to 20.04?

What I use here:
cmake version 3.18.4
Debian clang version 11.0.1-2
build-essential 12.9

And modules:
```
mod-account-achievements
mod-ah-bot
mod-arac
mod-autobalance
mod-bg-slaveryvalley
mod-congrats-on-level
mod-morphsummon
mod-npc-buffer
mod-transmog
mod-weapon-visual
```

I just recompiled everything using commit 877e394e04e13662554f8cce663bea1c646a98d2 (the latest one right now).

It works just fine, trying again with the 2 modules you mentioned.

**Comment by Zoidwaffle** [comment]
I just compiled it, no errors.

**Comment by r0m1ntik** [comment]
@mpfans re run your cmake

**Comment by mpfans** [comment]
> I just compiled it, no errors.

ubuntu 18.04    
cmake version 3.19.2
clang version 10

no any module
![image](https://user-images.githubusercontent.com/18187177/112636716-6cf2c000-8e78-11eb-8b86-0279f457ea12.png)
Compilation complete

**Comment by mpfans** [comment]
I'm very sorry for the compilation failure caused by my module code changed to 0 bytes
