### ISSUE TITLE
DB/Quest: Kill 'Em With Sleep Deprivation & Look at the Size of It! script

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#501]
**Description**:
These quests were added in 3.3, so I never saw them during retail and neither have I seen it work on any server.

http://www.wowhead.com/quest=7702/kill-em-with-sleep-deprivation
http://www.wowhead.com/quest=7704/look-at-the-size-of-it

http://www.wowhead.com/npc=14635/sleepy-dark-iron-worker
http://www.wowhead.com/npc=14636/chambermaid-pillaclencher

https://www.youtube.com/watch?v=Gu29CrLxFN0

These quests and the associated event is not working.

**Current behaviour**:
Nothing happens.

**Expected behaviour**:
http://www.wowhead.com/npc=14636/chambermaid-pillaclencher#comments:id=1780621
This comment is a good summary, it's from WoD but after reading all the other comments it doesn't seem like the event was ever changed.

*    Enter the sleeping quarters and loot ONE pillow.
*    Sit and wait - after 1 minute the first pack of sleepy Dark Iron Dwarves spawns (kill them).
*    Sit and wait - after around 3 minutes the second pack of sleepy Dark Iron Dwarves spawns (kill them).
*    Sit and wait - after another 5 minutes Chambermaid Pillaclencher spawns.

http://www.wowhead.com/npc=14636/chambermaid-pillaclencher#comments:id=924124
She stays for 20 minutes.

http://www.wowhead.com/npc=14636/chambermaid-pillaclencher#comments:id=928550
She dual wields pillows! Hitting fast but for 40 damage main-hand on hunter pet.

http://wow.gamepedia.com/index.php?title=Chambermaid_Pillaclencher&oldid=2148320
3.3.0 version of this page, for reference for her Smother ability.

http://wow.gamepedia.com/Quest:Kill_%27em_With_Sleep_Deprivation
I couldn't find any pre-cata version of this quest on the wiki, but this page has the emote text on spawn at least.

**Branch(es)**: master

**AC hash/commit**:  cfd2d7e

**Comment by Si1ker** [comment]
![image](https://user-images.githubusercontent.com/61223313/113659051-793c0180-965e-11eb-8026-c1a01d994dff.png)

![image](https://user-images.githubusercontent.com/61223313/113659063-7fca7900-965e-11eb-9e16-df332c251a6d.png)

![image](https://user-images.githubusercontent.com/61223313/113659073-835e0000-965e-11eb-8bcd-527a9657950b.png)


Completed both quests today..  c0cb2ea

http://www.wowhead.com/quest=7702/kill-em-with-sleep-deprivation
http://www.wowhead.com/quest=7704/look-at-the-size-of-it
