### ISSUE TITLE
Wailing Caverns Disciple of Naralex moves too fast

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5011]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/297

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Disciple of Naralex in Wailing Caverns moves too fast.
Using the macro `/run print(GetUnitSpeed("target"))` his walking speed is observed to be slightly above 3.5

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Disciple of Naralex' movement speed should be slightly slower than a player's walking speed.
Citation:
>This guy might be the slowest walking escort in the game. He's the only one I've noticed that you can actually pass at walking speed.
https://www.wowhead.com/npc=3678/muyoh#comments:id=657945

His movement speed should be less than 2.5, which is what a player's walking speed is.

##### STEPS TO REPRODUCE THE PROBLEM:
In order to start the event which makes Disciple of Naralex start walking, you must kill the 4 Leaders of the Fang
They can be found here:
`.go creature 27380`
`.go creature 27366`
`.go creature 87107`
`.go creature 38148`

Once they are dead go to the Disciple of Naralex:
`.go creature 18675`

Talk to him and select the gossip option "Let the event begin!"
He will begin to walk away.
Observe his movement speed with `/run print(GetUnitSpeed("target"))` is about ~3.5

##### EXTRA NOTES:

This is NOT a duplicate of #281 which addresses the NPC not stopping to help with combat and mentions nothing about movement speed.
The video on that ticket is post-cata when Disciple of Naralex received a MASSIVE increase to his movement speed.

Thank you for your report. Please click submit new issue below.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
You can fix it with a simple:
```
UPDATE `creature_template` SET `speed_walk`=1 WHERE `entry`=3678;
```
This aligns the data with TC as well. Not sure why he had a walking speed of 1.4 before.

**Comment by Hacki95** [comment]
> 
> 
> You can fix it with a simple:
> 
> ```
> UPDATE `creature_template` SET `speed_walk`=1 WHERE `entry`=3678;
> ```
> 
> This aligns the data with TC as well. Not sure why he had a walking speed of 1.4 before.

Could it be that he walks even slower than 1? https://youtu.be/xeW3Nl9akYA?t=1721 I found this video.

**Comment by eTzmNcbkrng** [comment]
He does walk slower than 1, I mentioned this in the original ticket, citing a Wowhead comment, I hesitate to say your video confirms it as it's from Classic, but it certainly lends credence.

**Comment by Hacki95** [comment]
> 
> 
> @Hacki95
> He does walk slower than 1, I mentioned this in the original ticket, citing a Wowhead comment, I hesitate to say your video confirms it as it's from Classic, but it certainly lends credence.

Yeah I just used this video as it is the highest quality one I could find. I spend a while checking if WC was changed in TBC or WOTLK though, so in my opinion it can be used as a source to fix this encounter (atleast the movement part, not damage values etc).
