### ISSUE TITLE
Pull request # 4933 is breaking some area auras

### ISSUE THREAD

**Issue by Footman** [azerothcore/azerothcore-wotlk#5013]
## CURRENT BEHAVIOUR:

pull request #4933 broke some area auras like https://www.wowhead.com/spell=58600/restricted-flight-area
now players dont get this buff anymore when fly above dalaran and are falling to the ground.
also i think this is connected to some new issues in ICC but cant provide more info yet.

**Comment by FrancescoBorzi** [comment]
@Kitzunu @pklloveyou

this is what I mean by: testing that a PR does not bring regression.

In general:  when testing a PR, we should NOT (only) test that the PR works as intended, but that ANYTHING that is **related** to that change is still working fine.

@Kitzunu can you please check this? quite urgent

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/112657890-25a60880-8e53-11eb-8436-c361a5bc0284.png)
works 9c80fd344b50

**Comment by Kitzunu** [comment]
on it
