### ISSUE TITLE
Pull request #4909 is breaking scripts / spells

### ISSUE THREAD

**Issue by Footman** [azerothcore/azerothcore-wotlk#5014]
## CURRENT BEHAVIOUR:

#4909

Spell and Scripts now trace for ground Z starting from creatures feet + 0.5 units and will fail if creature is just a bit inside ground.
Before they started to search from feet + creatures collision and did not fail.

This causes a lot of bugs related to ground Z finding like creatures falling throw earth. Some spells failing etc.

**Comment by FrancescoBorzi** [comment]
@pklloveyou please be more careful when testing PRs

@WojtekNosal can you please have a look? otherwise we need to revert it :(

**Comment by Err0r1** [comment]
Maybe BWL orb issue related?

**Comment by FrancescoBorzi** [comment]
@Footman please give some examples of what has been broken by that PR so we can check and fix.

**Comment by AbraKabastard** [comment]
Are you sure this issue is caused by the PR https://github.com/azerothcore/azerothcore-wotlk/pull/4893 and not something that actually messes with positional information like..
https://github.com/azerothcore/azerothcore-wotlk/commit/b4242735749ca6ff4d7e370cc0d41105f5856f60

I don't think this is related to @WojtekNosal's work at all

**Comment by claudiodfc** [comment]
@Footman Can you show a specific test case so I can try to replicate it without some commits?

**Comment by FrancescoBorzi** [comment]
yes, it was a mistake. The PR is:

https://github.com/azerothcore/azerothcore-wotlk/pull/4909

created by @UltraNix , not  @WojtekNosal (apologies for the confusion).

**Comment by Footman** [comment]
It is hard to reproduce those bugs. Also not only this commit is causing this but also some other connected to LOS. There are a lot of new bugs happening on live server now. After I reverted al commits that are connected to Z height / LOS everything got fine.

There are bugs like: 
- bosses evading randomly
- sindragosa not launching air phase
- lichking ghouls falling throw earth
- event with spiders before sindragosa is not completing
- ghost in frostmourne lk room is falling throw earth

**Comment by FrancescoBorzi** [comment]
thansk @Footman ,  @UltraNix  can you please have a look at these?

**Comment by UltraNix** [comment]
@Footman Could you add 1yard more  and see the results?

**Comment by claudiodfc** [comment]
What about setting up a check in case there are units with an invalid z coordinate and set them at the height of terrain?

**Comment by claudiodfc** [comment]
What makes them go into the ground in the 1st place though? When they calculate a path they should take terrain into consideration, right?

**Comment by UltraNix** [comment]
I see problems with falling mobs do exist in Lich king room? There is a huge gameobejct instead of terrain.

**Comment by claudiodfc** [comment]
ToGC should be checked aswell

**Comment by UltraNix** [comment]
@Footman Give me more specific examples of problems with z offset calculations.

**Comment by UltraNix** [comment]
I think most problems with evading/not attacking caused by #4893.

**Comment by claudiodfc** [comment]
@UltraNix any chance this PR could break some spell target SRC entry?

**Comment by UltraNix** [comment]
Not really sure, but I guess not.
