### ISSUE TITLE
Issue with Warden

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#5017]
## CURRENT BEHAVIOUR:

The client gets kicked after a certain amount of time. For me, this appears to occur after 60 to 80 minutes of being in-game. The server does not crash, and the client can log back in again instantly. I can be in the middle of fighting when I'm suddenly kicked out of the game

## EXPECTED BLIZZLIKE BEHAVIOUR:

The client should not get kicked for no real reason

## SOURCE:

N/A

## STEPS TO REPRODUCE THE PROBLEM:

1. Compile the source, import the databases etc
2. Leave all configs as default, make sure warden is enabled, and set LogDebugMask to 75497537 to get some extra info in the console
3. Start the server and log in using the client
4. Run around and do stuff or be semi-idle, just make sure not to let yourself go AFK
5. After a certain amount of time you will be kicked out of the game

## EXTRA NOTES:

I have unfortunately not tested older versions of the core as I only started using it a couple of days ago and was told off on Discord when even mentioning trying older versions
The first break point I get is "_session->KickPlayer("Warden: clientResponseTimer > maxClientResponseDelay (Warden::Update)");" from Warden.cpp
After several days of research and testing, I can finally say that I believe this to be the fault of Warden. Disabling Warden in the worldconfig seems to fix the issue
The "Unable to read memory" I really have no idea what that's about

![kickplayer1](https://user-images.githubusercontent.com/5157047/112700895-76d3ed80-8e8f-11eb-9685-f438abc84b77.png)
![kickplayer2](https://user-images.githubusercontent.com/5157047/112700908-7dfafb80-8e8f-11eb-9b11-cbc52692fa55.png)

## AC HASH/COMMIT:

7067696f83c6ccb8c4f9ecc316ccf9be70693c03

## OPERATING SYSTEM:

Windows 10, Ubuntu 20.04, Ubuntu 20.10

## MODULES:

None

## CUSTOMIZATIONS:

Nothing

**Comment by FrancescoBorzi** [comment]
@UltraNix can you please have a look at this? It looks like several people are experiencing this when testing with players (even though it's not easy to reproduce on a local server without players).

**Comment by UltraNix** [comment]
I won't be able to fix it if I won't get any futher info.
I will try to reproduce it on my local.

**Comment by mpfans** [comment]
if `set Warden.Enabled = 1` and `Warden.ClientCheckFailAction = 2`
Many players will be banned for the reason of `login state - (may be false positive)`

From 22 o'clock yesterday to now, 18 players have been ban for this reason
![image](https://user-images.githubusercontent.com/18187177/112721706-6def2480-8f40-11eb-96ae-24c621c14246.png)

**Comment by UltraNix** [comment]
https://github.com/TrinityCore/TrinityCore/issues/5767
It looks like this specific warden check is false positive.

**Comment by UltraNix** [comment]
@tkn963 Check #5027

**Comment by disclosurez** [comment]
confirm same issue here

**Comment by UltraNix** [comment]
@disclosurez Have you tested provided fix from here: #5027?

**Comment by disclosurez** [comment]
> 
> 
> @disclosurez Have you tested provided fix from here: #5027?

jsut did, will let u know outcome.
