### ISSUE TITLE
Invisible Wall/Barrier in Stormwind causes issues with running + camera movement.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5018]
Invisible Wall/Barrier in Stormwind causes issues with running + camera movement.

## CURRENT BEHAVIOUR:

As you can see in my video, tall races/tall mounts cannot run down the mage tower.

https://youtu.be/DxrFw0GMIKo

In addition to this, the hidden wall provides camera jumps/stutters/issues when the camera hits it.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Not entirely sure.

The wall/issue is related to these videos;

https://youtu.be/K9MpxU03vmk

https://youtu.be/8jQWfquESZk?t=353

However, I don't recall ever getting stuck due to mount size on open air on retail.

I will mark it as "not confirmed" as I'm not 100% sure.

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Stormwind Mage Tower
2. As a large race (Draenei) mount a large mount (Mammoth or Elekk)
3. Try to run down the ramp

## AC HASH/COMMIT:

AzerothCore rev. 8bacb39d5334 2021-03-20 

## MODULES:

CFBG

**Comment by UltraNix** [comment]
It's problem with Blizz textures.
Definetely not a serverside bug.
