### ISSUE TITLE
Charge distance errors after #3384

### ISSUE THREAD

**Issue by markvetx** [azerothcore/azerothcore-wotlk#5021]
## CURRENT BEHAVIOUR:

If you try to charge, you will get an error that "Target is too close". This error is identical on druid and warrior.

After #3384

## EXPECTED BLIZZLIKE BEHAVIOUR:

It shouldn't be working like that, obviously.

## STEPS TO REPRODUCE THE PROBLEM:

1. Create druid or a warrior.
2. Learn "Charge" spells for those classes respectively.
3. Try to use it on neutral/hostile NPC's.

## AC HASH/COMMIT:

3e29ce2

## OPERATING SYSTEM:

Arch Linux 5.11.8

## MODULES:

[mod_autobalance](https://github.com/azerothcore/mod-autobalance)
[mod_ahbot](https://github.com/azerothcore/mod-ah-bot)
[mod_transmog](https://github.com/azerothcore/mod-transmog)

**Comment by FrancescoBorzi** [comment]
@markvetx thanks for reporting 

@Helias please have a look at this

**Comment by icecatbing** [comment]
same problem here.

**Comment by zqgmzq** [comment]
+1

**Comment by Helias** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5052
