### ISSUE TITLE
Rayne Missing Dialogues/texts

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5026]
Rayne Missing Dialogues/texts

## CURRENT BEHAVIOUR:

"Greetings %N" for all dialogue.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Gossip

Eastern Plaguelands

Hello, <class>. Please excuse me as I am having a conversation with Rimblat. He believes that even this land is not beyond saving.

    Gossip Hello, Rayne. What brings the Cenarion Circle to the Plaguelands?

    We are all drawn here for different reasons, <class>.

    <Rayne smiles.>

    I am here to meet with Rimblat of the Earthen Ring. He has some interesting theories on cleansing these lands.

        Gossip Are these lands not beyond healing? They look pretty beat up.

        I think not. Rimblat has already proven that new life can grow from the sundered earth. Now we must find a way to reproduce and, more importantly, sustain the growth.

        While I am here, I am also offering my services to adventurers entering Naxxramas.

            Gossip What kind of services?

            I am a crafter of some renown, <class>. With the proper materials, I am able to craft an armor known as Dreamwalker. Druids - and even some shaman - are drawn to this armor due to its magical properties. Are you interested?

    Gossip Rayne, where should I look for savage fronds?

    If you are one that prefers to hunt in the outdoor world, both Felwood's treants and Un'Goro's lashers are an excellent source of fronds.

    If you are more of a risk-taker, the eastern and western wings of Dire Maul will provide you with a near limitless supply of savage fronds.

## SOURCE:

https://wowpedia.fandom.com/wiki/Rayne

https://classic.wowhead.com/npc=16135/rayne

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Light's Hope Chapel
2. Speak to Rayne
3. 

## AC HASH/COMMIT:

AzerothCore rev. 8bacb39d5334 2021-03-20

**Comment by markvetx** [comment]
Can be closed. #5035 is merged.
