### ISSUE TITLE
Rohan the Assassin missing dialogue/texts

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5028]
Rohan the Assassin missing dialogue/texts

## CURRENT BEHAVIOUR:

"Greetings %N" for all replies.

## EXPECTED BLIZZLIKE BEHAVIOUR:

The title is misleading. I'm really a very nice person once you get to know me.

    Gossip What is it that you do exactly, Rohan?

    Ah, as the title states I am an assassin for the Scarlet Crusade. I spend my days exterminating high priority targets and nights at the Gadgetzan discotheque. Dancing is my true calling. Assassination just pays the bills.

        Gossip So what brings you to Light's Hope?

        Good question, <race>. In my younger days I was footloose and fancy free without a care in the world. In those days I would sing in a barber shop quartet out of Stormwind known as the Four Dons. That's where I learned how to craft the Bonescythe digs.

            Gossip What? Bonescythe?

            Yes, Bonescythe. You see, it was our tenor, an ornery fellow known as Don Julio, who got me started on the whole thing. In his travels throughout Lordaeron, Don Julio picked up many interesting skills, one of them being the ability to take the bones of fallen Scourge and fashion them into a lethal set of leather armor - perfectly suited for an assassin.

                    Gossip Wow, you're insane, aren't you?

                    I'm as sane as the next guy, fella. Believe what you will, but I AM capable of fashioning this armor. If you're interested, maybe we can make a deal. The sooner I can get out of the assassination business, the better.

                        Gossip Hey, wait, Gadgetzan has a disco?

                        Members only, scrub!

    Gossip Where can I find bone fragments?

    Are you daft? Did you miss the BONY SKELETAL CREATURES littering the landscape on your way over here?

    <Rohan sighs.>

    If you're the outdoor type, you'll find skeletal creatures all over both the Western and Eastern Plaguelands. Trust me, you can't miss 'em - they certainly won't miss you if they get the chance.

    If you're a dungeon type, Stratholme and Scholomance are definitely the place to be for bone fragments.

## SOURCE:

https://wowpedia.fandom.com/wiki/Rohan_the_Assassin

https://classic.wowhead.com/npc=16131

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Light's Hope Chapel
2. Speak to Rohan inside the church
3. 

## AC HASH/COMMIT:

AzerothCore rev. 8bacb39 2021-03-20

**Comment by FrancescoBorzi** [comment]
as a general rule: if a content is available for 50-59, no need to add label 60

**Comment by markvetx** [comment]
Can be closed. #5035 is merged.
