### ISSUE TITLE
Huntsman Leopold Missing dialogue/texts

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5029]
Huntsman Leopold Missing dialogue/texts

## CURRENT BEHAVIOUR:

"Greetings %N" for most dialogue.

## EXPECTED BLIZZLIKE BEHAVIOUR:

They almost sent my brother, Loksey, to this gathering. He cannot even take care of his hounds, let alone represent the Scarlet Crusade in a competent manner.

    Gossip What is Cryptstalker armor?

    The preternatural ability of the crypt fiend to hunt and kill its foe is one studied and vaunted by men in my profession. I, myself, have slain thousands of the beasts in my crusade to rid this world of Scourge.

    While I loathe the crypt fiend for its merciless nature, its abilities must be admired. It has a job and it does it - very well.

        Gossip Continue please.

        I have discovered a use for the carapace of the crypt fiend and its various body parts. I am able to fashion an extremely light and very deadly set of armor by combining the fragments with some of the desecrated magical armors lost in Naxxramas.

    Gossip Where can I find crypt fiend parts, Leopold?

    Those filthy beasts are all over the place.

    If you prefer hunting outdoors, you'll find most of them around Plaguewood and Terrordale, with a good concentration of them in the Terrorweb tunnel. They are also likely to appear at almost any Scourge encampment in the Eastern Plaguelands.

    If you're a hearty dungeon crawler, you'll find a good lot of them in Stratholme and a few of the necrofiend variety in Scholomance.

## SOURCE:

https://wowpedia.fandom.com/wiki/Huntsman_Leopold

https://classic.wowhead.com/npc=16132

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Light's Hope Chapel
2. Speak to Leopold
3. 

## AC HASH/COMMIT:

AzerothCore rev. 8bacb39d5334 2021-03-20 18:26:35 +0100 (master branch) (Unix, RelWithDebInfo)

**Comment by markvetx** [comment]
Can be closed. #5035 is merged.
