### ISSUE TITLE
Lichking resets after dialogue when he can't find player (LoS?)

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/azerothcore-wotlk#5030]
## CURRENT BEHAVIOUR:
the Lich King resets when the player is not in LoS. 

## EXPECTED BLIZZLIKE BEHAVIOUR:
the Lich King should run to the player and attack him

## STEPS TO REPRODUCE THE PROBLEM:

1. go to lichking (ICC last boss)
2. start dialogue 
3. hide (like in video)

## EXTRA NOTES:
video issue: https://vid.dragonwrath.net/v/J98Sxd
maybe related to:
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/azerothcore/azerothcore-wotlk/issues/5021
https://github.com/azerothcore/azerothcore-wotlk/issues/5014

## AC HASH/COMMIT:
3e29ce2e50e969d7d4ca1cd8a86745e74301f3b7

## OPERATING SYSTEM:
debian 10

## MODULES:
mod-cfbg
mod-transmog
mod-pvp-titles
mod-1v1

**Comment by FrancescoBorzi** [comment]
@Err0r1 do you know which commit broke this?

**Comment by Err0r1** [comment]
unfortunately i'm not sure :/

**Comment by disclosurez** [comment]
can confirm same issue here

**Comment by disclosurez** [comment]
maybe https://github.com/azerothcore/azerothcore-wotlk/pull/4893 causing the problem

**Comment by FrancescoBorzi** [comment]
cc @UltraNix

**Comment by UltraNix** [comment]
Cannot reproduce it.

**Comment by disclosurez** [comment]
confirmed #4893 was causing this issue, please revert

**Comment by UltraNix** [comment]
`m_respawnedTime` is not initialized - it's the only problem with that commit.

**Comment by FrancescoBorzi** [comment]
@UltraNix can you please provide a PR with this?

> `m_respawnedTime` is not initialized - it's the only problem with that commit.

**Comment by UltraNix** [comment]
No problemo.

**Comment by Err0r1** [comment]
> Cannot reproduce it.
> @Err0r1 Are you able to reproduce it every single time?

Yes.
