### ISSUE TITLE
Players log in and start timing. It is estimated that they will be forced to log out in about 1 hour and 10 minutes.

### ISSUE THREAD

**Issue by hahalmtdhl** [azerothcore/azerothcore-wotlk#5031]
**CURRENT BEHAVIOUR:**

Every time players log in, they will start to time, and they will be forced to log out in about 1 hour and 10 minutes.

**SOURCE:**

Through debugging, it is found that the execution of worldsession destructor will result in the forced logout of players.

Debug the breakpoint to the following code.

if (_ player)
   LogoutPlayer(true);

**STEPS TO REPRODUCE THE PROBLEM:**

Players log in and start counting. It will appear about 1 hour and 10 minutes later

**EXTRA NOTES:**

The world server console only displays player logout without any other prompts (debug mode will also be executed).

AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/3e29ce2e50e969d7d4ca1cd8a86745e74301f3b7

**OPERATING SYSTEM:**

WIN10

**Comment by disclosurez** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5027

fix maybe here

**Comment by hahalmtdhl** [comment]
Has this problem been incorporated into the project?

**Comment by Hacki95** [comment]
@hahalmtdhl This issue can be closed right?

**Comment by xclid** [comment]
its all good here
after #5027

**Comment by hahalmtdhl** [comment]
Yes, it has been solved.

**Comment by FrancescoBorzi** [comment]
thanks all for your feedback
