### ISSUE TITLE
NPCs don't attack the player if he is in water

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#5036]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

While fighting Venture Co. NPCs in Barrens, noticed if I attack them from Water, either by Taunting or Casting spells NPC get triggered but instantly return to passive state. [Video evidence](https://imgur.com/P8vLRV1)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After taunting or attacking NPC enemy they should engage in fight

##### STEPS TO REPRODUCE THE PROBLEM:

1. Swim in water
2. Taunt or cast ranged ability
3. Enemy will not attack and Evade

##### Extra Info:
Linked Issue: https://github.com/chromiecraft/chromiecraft/issues/306

Might be related to: https://github.com/azerothcore/azerothcore-wotlk/issues/5022

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Hacki95 don't forget **1-19** ;)

**Comment by Hacki95** [comment]
Not done yet ;)

**Comment by UltraNix** [comment]
These specific mobs do not have inhabit type INHABIT_WATER.

**Comment by Hacki95** [comment]
> 
> 
> It's not problem with maps/vmaps (as many such marked).
> These specific mobs do not have inhabit type INHABIT_WATER.

Thanks for the tip! So those mobs need this added?

**Comment by UltraNix** [comment]
Just set in DB inhabit type to 3 (ground + water).

**Comment by Hacki95** [comment]
> 
> 
> Just set in DB inhabit type to 3 (ground + water).

Thanks for your help. Will open a PR later.
