### ISSUE TITLE
3 minutes spawn timer for Black Lotus in Burning Steppes

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#5037]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

This black lotus can be repeatably gathered every 3 minutes. Tested for ~ 10 times.

Note by Hacki: It's also a double spawn, so you get atleast 2x Black Lotus every few minutes.

![WoWScrnShot_032721_230406](https://user-images.githubusercontent.com/81451494/112741254-1bb6ff00-8f52-11eb-9cc7-1126eb717a1f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Black Lotus to be hard to find.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Burning Steppes - Altar of Storms location 
2. Gather black lotus (see screenshot)
3. Wait 3 minutes
4. Black lotus respawns

##### EXTRA NOTES:

Linked issue: https://github.com/chromiecraft/chromiecraft/issues/309

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Zoidwaffle** [comment]
I recall reading about this a long time ago in Classic... From what I recall it's something like 1 spawn per zone with 1 hour respawn rate... So 2 every 3 minutes in the same location is a bit much. Maybe I can find time to fix it tomorrow, but others are welcome to fix it as well.

**Comment by T1ti** [comment]
> I recall reading about this a long time ago in Classic... From what I recall it's something like 1 spawn per zone with 1 hour respawn rate... So 2 every 3 minutes in the same location is a bit much. Maybe I can find time to fix it tomorrow, but others are welcome to fix it as well.

yes that's how it works, there can only be 1 black lotus per zone and they have 1 hour respawn

**Comment by Hacki95** [comment]
> 
> 
> I recall reading about this a long time ago in Classic... From what I recall it's something like 1 spawn per zone with 1 hour respawn rate... So 2 every 3 minutes in the same location is a bit much. Maybe I can find time to fix it tomorrow, but others are welcome to fix it as well.

I was kinda hoping you would do this one :P This screamed Zoidwaffle to me.

**Comment by Zoidwaffle** [comment]
Hehe, yeah, let me see if I can find the time tomorrow 😁

**Comment by Zoidwaffle** [comment]
Done. This should be better - and much easier to tweak later if needed. A bit crazy I could literally pick 20 Black Lotus in a zone easily...

**Comment by Footman** [comment]
Problem that it happens with nearly all burning crusade / classic herbs. for example https://wowhead.com/object=181276/flammenkappe
