### ISSUE TITLE
Feature: New creature grouping system [$55]

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#5045]
**Describe your feature request or suggestion in detail**
Create a new table to group creatures together. This is really required to fix linked aggro in instances, a lot of packs are meant to be aggro together but currently it only checks for distance, and sometimes that distance isn't enough. It's a very widespread issue that makes some packs too easy and scuffed in almost every instance.

Example : This hyena pack in Dire Maul north which is spread out
![image](https://user-images.githubusercontent.com/40864460/112769393-0b218a00-9021-11eb-9fda-237de506ae7e.png)
You can pull only a few creatures separatly 
![image](https://user-images.githubusercontent.com/40864460/112769439-415f0980-9021-11eb-939e-ae05ff27b218.png)
On classic, the whole pack will aggro together, whatever mob you hit 
https://youtu.be/tkuaQMURTRo?t=1393
Or there an  insect pack https://youtu.be/tkuaQMURTRo?t=495 Notice how all creatures aggro from far away
This is currently impossible to do in AC unless you increase mob radius to 100, and then it might aggro other creatures(based on faction..)

Expected behavior : If you pull any creature that is set in a  group, all other creatures in that group will also aggro regardless of distance

**Describe a possible solution to your Feature or Suggestion in detail**
Make a new table similar to creature_formation but with only a group ID and the GUID of all creatures in that group.
A new command to quickly add creatures to groups would be nice too.

I previously tried to use the creature_formation table with GroupAI 3 for this, but it didn't work out, the way it's coded is that it's all based around the leader and it will create weird bugs on packs that are spread out(resetting to leader etc). Creature_formation only works for formations.

This could be expended into SAI later, with new commands like "if group dies" do X, or group X does X... This would allow to move a lot of instance C++ code to SAI.

**Additional context**

**Comment by T1ti** [comment]
This could also be used to easily make groups of creature respawn if the whole group hasn't been beaten, which is something usualy done in C++ (like respawn boss' adds if players wiped nd boss didn't die, this is a big issue and missing on a lot of bosses currently)

**Comment by T1ti** [comment]
It's actually far worse than that, you can currently even pull boss adds separately if they're far enough
Example with Golemagg adds 
![image](https://user-images.githubusercontent.com/40864460/112771582-cac80900-902c-11eb-8c47-084698bfd47e.png)

**Comment by AbraKabastard** [comment]
Please see table creature_formations. If AC doesnt have a wiki see also https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129997/creature+formations and you could use https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130218/linked+respawn for something with the molten core hounds

**Comment by T1ti** [comment]
Did you even read ?

**Comment by AbraKabastard** [comment]
What part did I miss?

**Comment by T1ti** [comment]
Some more suggestions, those are some options vmangos use in their group table

{
    OPTION_FORMATION_MOVE               = 0x001,
    OPTION_AGGRO_TOGETHER               = 0x002,
    OPTION_EVADE_TOGETHER               = 0x004,
    OPTION_RESPAWN_TOGETHER             = 0x008,
    OPTION_RESPAWN_ALL_ON_MASTER_EVADE  = 0x010,
    OPTION_RESPAWN_ALL_ON_ANY_EVADE     = 0x020,
    OPTION_INFORM_LEADER_ON_MEMBER_DIED = 0x040,
    OPTION_INFORM_MEMBERS_ON_ANY_DIED   = 0x080,
};

**Comment by ChromieCraftServer** [comment]
added 25$ bounty

![image](https://user-images.githubusercontent.com/48177002/117422816-51bbab80-af20-11eb-889b-b6b0e1bb21ba.png)

**Comment by UltraNix** [comment]
But it's already doable by `creature_formation` table. Why do we need another table?

**Comment by T1ti** [comment]
closing since creature_formation has been fixed and seems to be able to do the job correctly now.
