### ISSUE TITLE
Compile error with DENABLE_EXTRA_LOGS - it should be added in the CI

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#5048]
## CURRENT BEHAVIOUR:
An error occurred while compiling the core. The compilation could not be completed

system：Ubuntu18.04
 compilation commands ：cmake ../ -DCMAKE_INSTALL_PREFIX=/www/game/server/ -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DWITH_WARNINGS=1 -DTOOLS=1 -DSCRIPTS=1 -DENABLE_EXTRAS=1 -DENABLE_EXTRA_LOGS=1

error messages：
[ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/zone_teldrassil.cpp.o
/www/game/azerothcore-wotlk/src/server/game/Warden/WardenMac.cpp:51:55: fatal error: too few arguments to function call, expected at least 2, have
      1; did you mean '::ByteArrayToHexStr'?
    sLog->outDebug(LOG_FILTER_WARDEN, "C->S Key: %s", acore::Impl::ByteArrayToHexStr(_inputKey).c_str());
                                                      ^~~~~
                                                      ::ByteArrayToHexStr
/www/game/azerothcore-wotlk/src/common/Utilities/Util.h:356:13: note: '::ByteArrayToHexStr' declared here
std::string ByteArrayToHexStr(Container const& c, bool reverse = false)
            ^
1 error generated.
src/server/game/CMakeFiles/game.dir/build.make:4802: recipe for target 'src/server/game/CMakeFiles/game.dir/Warden/WardenMac.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/Warden/WardenMac.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/OnyxiasLair/boss_onyxia.cpp.o
[ 69%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp.o
CMakeFiles/Makefile2:1765: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

## SOURCE:
cd450c2

[err-log.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6220794/err-log.txt)

**Comment by pklloveyou** [comment]
It's like this
```c++
acore::Impl::ByteArrayToHexStr(_inputKey, false).c_str()
```

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/112826045-12977080-90bf-11eb-91a6-7b6ff1a8b9fd.png)

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/112826616-d0226380-90bf-11eb-8b5f-30ad31f5f1a7.png)
Thank you. I'll test it right away

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/112829465-c13db000-90c3-11eb-92b2-f83f5a188657.png)
I revised the new error report

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/112829973-7a03ef00-90c4-11eb-9092-8957cc622a5d.png)
I added false on the second line as well, so let me try that

**Comment by pklloveyou** [comment]
Every line needs to be added

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/112834899-23e67a00-90cb-11eb-9594-a7ab22bef2a0.png)
I wonder if these two lines need to be added?

**Comment by FrancescoBorzi** [comment]
we should probably add `DENABLE_EXTRAS` to our CI in order to prevent bugs like this from happening

**Comment by yuanf225** [comment]
> we should probably add `DENABLE_EXTRAS` to our CI in order to prevent bugs like this from happening

look forward to

**Comment by yuanf225** [comment]
WardenMac.cpp and WardenWin.cpp This error needs to be handled

**Comment by wine-la** [comment]
remove DENABLE_EXTRA_LOGS=1, and try it again.

**Comment by yuanf225** [comment]
> remove DENABLE_EXTRA_LOGS=1, and try it again.

Why can't I use DENABLE_EXTRA_LOGS

**Comment by locus313** [comment]
@FrancescoBorzi sure,ill look at adding this.
