### ISSUE TITLE
[quest] City of Light

### ISSUE THREAD

**Issue by PolarCookie** [azerothcore/azerothcore-wotlk#505]
**Description**:
The scripted tour for this quest isn't working, Khadgar's servant follows you around as a pet.
Speedrunning from 1 to 68, this was the only roadblock I found.

**Branch(es)**: master

**AC hash/commit**:  d397d8c

**Comment by KwazarFr** [comment]
Tested and it works great, no bug at all.

Please confirm and close

Branch(es): master

AC hash/commit: [445b885](https://github.com/azerothcore/azerothcore-wotlk/commit/445b88563f07393134836e9d9840ed0649ea11ba)
