### ISSUE TITLE
During Curing the Sick, killing the deer after curing it counts towards quest completion [$10]

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#5055]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/312

related to #312

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

During the quest [Curing the Sick](https://wotlkdb.com/?quest=6124), you use a [quest item](https://wotlkdb.com/?item=15826) on [Sickly Deer](https://wotlkdb.com/?npc=12298), which awards one completion point per deer cured. However, if you kill them after they are cured, that will reward an additional point. 

![Curing the Sick](https://user-images.githubusercontent.com/8137930/112764711-e81eb800-8fd7-11eb-86f9-d0fde501c48c.png)

Note that this doesn't work if you kill the deer before you cure them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Killing the deer after you cure it should not reward a point towards quest completion. 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  While on the quest, find a Sickly Deer in Darkshore and use the Curative Animal Salve on it. This will reward one point towards the quest.
2.  Kill the Cured Deer immediately after, this will reward a second point.

##### EXTRA NOTES:

I don't have a Horde Druid to test it on, but the same bug might occur on the [Horde equivalent quest](https://wotlkdb.com/?quest=6129).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jordigil** [comment]
I can confirm same bug for Tauren (horde side)

**Comment by eTzmNcbkrng** [comment]
There is Blizzard original bug that caused this to happen but only with Entanglling Roots.
Blizzard never fixed this and it was still present in 3.3.5 only becoming obsolete when the quest was removed in 4.0.
Does AzerothCore want to reproduce Blizzard original bugs?
I think it should with an option to “fix” the bug.

>A little disturbing, but you can do this to finish the quest faster:
>- Cast entangling roots on the sickly animal
>- Use the Curative Animal Salve before the damage from the roots kills it
>- Wait for the animal to die, you'll get double credit
>
>This way, you only have to look for 5 of them!

 \- https://www.wowhead.com/quest=6129/curing-the-sick#comments:id=24320

**Comment by Helias** [comment]
No, AzerothCore will not keep the known bugs of Blizzard 😅

**Comment by Stifler82** [comment]
@Helias Have you fixed this Bug?
And
Are you took this Case in load?
If yes assign it to yourself pls..

**Comment by Helias** [comment]
For missing time at the end no, I made some try with SAI but without success :(
If you do it, remember to remove the spell_quest.cpp part of this quest.

Anyways if SPELL HIT + creature credit id 12299 works we can surely replace the C++ part.

**Comment by eTzmNcbkrng** [comment]
> 
> 
> No, AzerothCore will not keep the known bugs of Blizzard 😅

![image](https://user-images.githubusercontent.com/26512802/114476533-7f2d7600-9c4e-11eb-844c-03a7f36e2b0e.png)
https://github.com/chromiecraft/chromiecraft/issues/354#issuecomment-814108937

**Comment by Stifler82** [comment]
@eTzmNcbkrng 
Hi, can you unblock me on Discord please, I sent you a message you should read, thanks.

**Comment by Helias** [comment]
No, AzerothCore will not keep the known bugs of Blizzard ✅

The feature of the text color should be blizzlike and considering that TC has fixed it I was thinking that even Blizzard did, but later I didn't find the source where blizzard removed it.

It does not hurt so I think we can keep it, because it is not a "known bug" it's probably a feature of the client

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Stifler82** [comment]
@FrancescoBorzi soon

**Comment by Stifler82** [comment]
Fixed!
-
https://user-images.githubusercontent.com/1884642/119499781-f6cae680-bd5e-11eb-9441-40def2e910c2.mp4
