### ISSUE TITLE
Loot that is being rolled for disappears from existence if all 5 people enter an instance at the same time. [$5]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5056]
Loot that is being rolled for disappears from existence if all 5 people enter an instance at the same time.

## CURRENT BEHAVIOUR:

Loot that is being rolled for disappears from existence if all 5 people enter an instance at the same time.

https://cdn.discordapp.com/attachments/806142311120633907/826152060826550282/unknown.png

This chatlog contains 4 people rolling greed and then "everyone passed" on it.

![image](https://user-images.githubusercontent.com/61194190/112879296-dcf38700-90c0-11eb-9f04-47c37ad726c4.png)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Loot should still be rolled for and handed out even if people enter an instance.

## SOURCE:

https://wowpedia.fandom.com/wiki/Loot

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Scarlet Monastary as 5.
2. Kill mobs outside the instance to enter and a blue item "Watchman's Pauldrons" drop.
3. Whilst it is still being rolled for, enter the instance as 5.
4. The item and its roll disappears from existence and nobody gets it even if 4 players clicked green and 1 had not clicked yet.

## AC HASH/COMMIT:

AzerothCore rev. 8bacb39d5334 2021-03-20 18:26:35 +0100 (master branch) (Unix, RelWithDebInfo)

## MODULES:

CFBG

**Comment by UltraNix** [comment]
I don't think it's a bug. You have been teleported to instance and looted object in on different map - that's why you missed the loot. Can somebody check this on retail?

**Comment by FrancescoBorzi** [comment]
@azerothcore/bug-triaging please help

**Comment by mpfans** [comment]
> I don't think it's a bug. You have been teleported to instance and looted object in on different map - that's why you missed the loot. Can somebody check this on retail?


I agree.If you switch maps, you can't get items
