### ISSUE TITLE
worldserver instantly closing

### ISSUE THREAD

**Issue by IZM38** [azerothcore/azerothcore-wotlk#506]
**Description**: sorry to bother you with this (again) but the problem is the worldserver is instantly closing every time I try to open it and I've run every file and update sqls still nothing.
![world error](https://cloud.githubusercontent.com/assets/25008014/26558780/9ab9c7dc-44c0-11e7-9469-5460213ac539.jpg)
 

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: Master

**AC hash/commit**:   d397d8c

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Inifield** [comment]
you didin't apply sql files, else you would have it, it's right here https://raw.githubusercontent.com/azerothcore/azerothcore-wotlk/master/data/sql/updates/db_world/2016_12_02_00.sql

**Comment by talamortis** [comment]
make a bat file and put the following this will tell you what ur error is:

worldserver.exe 
pause

**Comment by ShinDarth** [comment]
in addition, when the worldserver closes instantly on Windows, open it with cmd so you can see what the problem actually is.

closing this, feel free to ask in [our discord chat server](https://discord.gg/gkt4y2x) if you need further help

**Comment by ShinDarth** [comment]
@talamortis if opened in the command line it shouldn't be needed to add the pause
