### ISSUE TITLE
Quest The fargodeep mine doesn't complete

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#5066]
## CURRENT BEHAVIOUR:
Exploring the whole cave never completes the quest

## EXPECTED BLIZZLIKE BEHAVIOUR:
It should complete when you reach the area trigger

## STEPS TO REPRODUCE THE PROBLEM:

1. take the quest in goldshire and explore the mine
2. see if it completes
3. 

## EXTRA NOTES:
I tried it on chromiecraft, a bunch of other dudes I met in that mine said it didn't work for them either, 1 guy said it worked after abandoning and taking it again

## AC HASH/COMMIT:
d4b8defcd8e6971bdd558b1c360de9dcca9767b3

**Comment by T1ti** [comment]
Content 1-19 category

**Comment by Hacki95** [comment]
I completed this quest just a few days ago on several characters. Its a bit tricky to find the correct area but it definitely works.
