### ISSUE TITLE
Feature: Auction House getAll scan

### ISSUE THREAD

**Issue by eTzmNcbkrng** [azerothcore/azerothcore-wotlk#5068]
**Describe your feature request or suggestion in detail**
Add the Auction House feature to run a getAll scan which was added to WoW in 2.3

**Describe a possible solution to your Feature or Suggestion in detail**
https://github.com/TrinityCore/TrinityCore/commit/3aaeb574050668e5a240078f6e40337c3975d110

**Additional context**

**getAll**
- Download the ENTIRE auction house as one single page. Only allowed when CanSendAuctionQuery() returns true as its second return (~every 15 minutes). May disconnect people with low bandwidth. Also see notes on client-to-server traffic in GetAuctionItemInfo() (Added in 2.3, though initially disabled. Appears to be enabled as of 2.4)

 \- https://wowpedia.fandom.com/wiki/API_QueryAuctionItems

**Comment by necropola** [comment]
I'd really like to have **AuctionHouse Search with GetAll** working on AC and the commit from TC would apply with very little modifications, if there weren't these weird **pussywizard** modifications:
https://github.com/azerothcore/azerothcore-wotlk/blob/5906222fd6910beec4b5d6c07f4c69f69bb094a4/src/server/game/AuctionHouse/AuctionHouseMgr.cpp#L550-L585
* A special *optimization for a simplified case* (Which case and why handle it differently?)
* A special/additional thread AsyncAuctionListing (Why can't BuildListAuctionItems just be directly called from AuctionHouseHandler like all the other stuff that writes to world packets?)

It looks like the initial import into github already had these special modifications (which are spread over various parts of the code including **worldserver/Master**), but so far nobody touched it, not even to fix obvious typos.  
https://github.com/azerothcore/azerothcore-wotlk/blob/5906222fd6910beec4b5d6c07f4c69f69bb094a4/src/server/worldserver/Master.cpp#L192-L194

Does any of the veteran devs know/remember, why this sepcial code is needed in AC?

**Comment by tstuver2000** [comment]
Just wanted to chime in and add my support for this feature. Here's what I wrote on #Suggestions on discord:

AH API Suggestion: Have AzerothCore support the "GetAll" one-click AH scan. This is a type of all-in-one auction house scan / API dump (sorry if I'm not using the best terms for this) that blizzard implemented to allow faster scanning of the AH and lesser load on the servers.

**Problem**: Right now, ChromieCraft generally averages around 100 AH pages. AH addons like TSM, Auctioneer, etc can scan the Auction House page by page, but this currently takes about 5 minutes to complete a full scan. In addition, I'm sure it increases the server load as each page has to be pulled individually. 

**Benefits:** My past experience with the "GetAll" scan on blizzard live servers is that it typically takes less than 30 seconds in one large information dump, also lessening server load.

**Comment by Razorce** [comment]
I have something to add, as stated in the Issues I posted...
When I first started chromie, I did my first 3-4 scans no problem, then later it stopped working.
But as I understand, it wasn't supposed to work at all?
I started on this same bracket, so nothing really should have changed

**Comment by Azcobu** [comment]
A great deal more detailed information from @VFaleiro on this here: https://github.com/chromiecraft/chromiecraft/issues/1393

**Comment by alchem1ster** [comment]
@Azcobu any updates? Still doesn't fixed. Tested today on ChromieCraft.

**Comment by Azcobu** [comment]
I haven't worked on the project for some time, so have no other information regarding the status of this issue beyond what is linked here.

**Comment by Grimdhex** [comment]
Close with https://github.com/azerothcore/azerothcore-wotlk/pull/20830
