### ISSUE TITLE
Vmaps4assembler Crash

### ISSUE THREAD

**Issue by Poisonleaf** [azerothcore/azerothcore-wotlk#507]
**Description**: While using Vmaps assembler it crashes @Abandonedorcbarracks.wmo

**Expected behaviour**: Continue and not crashing.

**Steps to reproduce the problem**:

1.  Run "vmaps4extractor.exe -l -d Data"
2. Run "vmaps4assembler.exe"
3. ????
4. Profit. 

**Operating system**:  Windows 7

** Can provide the wmo if needed.

Side note: I've been having trouble starting up both the auth & world server.
It crashes as vmaps so I toke this step.

Poison.

**Comment by ShinDarth** [comment]
your report is missing of the  **core revision** (commit hash), please read [how to open an issue](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue) and edit your report
