### ISSUE TITLE
Auth/World server Crash.

### ISSUE THREAD

**Issue by Poisonleaf** [azerothcore/azerothcore-wotlk#509]
**Description**:
Hiya,

This is the first time reporting an issue so hopefully I have provided the correct information,
Should something to be missing I will try and add it as soon as possible.
For a while i've been struggling to get Azerothcore to start up on my computer. I have re-compiled it multible times and had help from an a highly experienced developer.

MySQL starts up normally but these two will not.
It should be able to start up normally but sadly is it not.

The folders DBC/Maps/vmaps/mmaps are present within the core folder and the database is setup ( and loading) correctly.
They are all launched as administrator.

**Current behaviour**: Both Auth and worldserver refuse to launch.

**Expected behaviour**: Both should normally launch.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
?

**AC hash/commit**:  SHA-1: 1a0a3e05782711afac61db1d298b6d423f3ef3d5

**Operating system**:  Windows 7

**Crash reports**:

Authserver: https://gist.github.com/Poisonleaf/b92e3af5cedafccec53dc38d9e3c7363
WorldServer: https://gist.github.com/Poisonleaf/f3957052afa162615e0dbffe9caa28b6

![6mgjlp3 - imgur](https://user-images.githubusercontent.com/10499876/26997381-8611423a-4d79-11e7-8229-16e9c0177593.png)
![cv1ai8v - imgur](https://user-images.githubusercontent.com/10499876/26997380-860e020a-4d79-11e7-916e-b463b9181f27.png)

**Comment by lineagedr** [comment]
Compile under debug.

**Comment by Inifield** [comment]
You disabled vmaps from what I can see

**Comment by Poisonleaf** [comment]
Ill double check that, enable it when needed and restart once again.

**Comment by Inifield** [comment]
open them in a command line and see if you get any error

**Comment by Poisonleaf** [comment]
No errors shows when I start them with a command line.
Going to compile in debug soon, What am I looking for then?

**Comment by Inifield** [comment]
honestly i'm not quite sure

**Comment by Poisonleaf** [comment]
Apart from Auth.log and server.log just showing the crash in textform (exactly the same) all the other logs are empty. Atm it's compiled in debug and in CMD it also does not show an error.

**Comment by talamortis** [comment]
post an image of your directory

**Comment by Subtixx** [comment]
Don't know if I have the same crash, but it crashes at the same position (Authserver: Updating realm list)
VS is saying bind is a nullptr.

https://i.imgur.com/QQ4kM8j.png
