### ISSUE TITLE
Wetlands Mottled Raptor and Highland Raptor Loottables Incorrect

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5094]
Wetlands Mottled Raptor and Highland Raptor Loottables Incorrect

## CURRENT BEHAVIOUR:

The raptors currently drop a full array of blues. If you farm there for 20-30 mins you will gain 50-100 blue items.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Each raptor only drops a couple blues listed on sources below. It should be less drops, and less items.

## SOURCE:

https://classic.wowhead.com/npc=1020/mottled-raptor

https://classic.wowhead.com/npc=1015/highland-raptor

## STEPS TO REPRODUCE THE PROBLEM:

1. Go to Whelgar's Excavation in Wetlands
2. Farm Raptors for 5-10 mins.
3. Observe many blues.

**Comment by warcrafter16** [comment]
Hi if this problem still isn't fixed can I try working on it? Im new to OS and would like to try.
