### ISSUE TITLE
Incorrect respawn timer for the restoration buff in Battlegrounds  [$15]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5098]
WHAT CLIENT DO YOU PLAY ON?

enUS

FACTION

Alliance
Horde

CONTENT PHASE:

Generic
1-19
20-29
30-39

CURRENT BEHAVIOUR:

Restauration buff respawn timer in battlegrounds is several minutes.
EXPECTED BLIZZLIKE BEHAVIOUR:

Restauration buff respawn timer in battlegrounds should be 20 seconds.

evidence link from wowhead:
https://classic.wowhead.com/guides/classic-wow-warsong-gulch-advanced-intro-rules-timers-wsg

tl;dr screenshot of the relevant part from the evidence link above:
https://i.gyazo.com/0b52b1922f39bec5afeefd3eade914f0.png
STEPS TO REPRODUCE THE PROBLEM:

    Join a battleground (for example, Warsong Gulch)
    Take a restauration buff (for exemple, inside the hut in Warsong Gulch)
    Notice how the respawn of the restauration buff takes several minutes instead of the expected 20 seconds.

EXTRA NOTES:

Spellid link for the restauration buff:

https://classic.wowhead.com/spell=23493/restoration
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@9d4eebc
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot
    mod-eluna-lua-engine
    lua-LevelUpReward

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

from

https://github.com/chromiecraft/chromiecraft/issues/325

**Comment by JamesGent** [comment]
Further info;

Wowpedia has
"Power-ups
There are three types of power-ups found in Warsong Gulch. To use them, simply walk up to one. They will respawn after a short period of time. "

from 2009. This is kinda useless because "short period of time" doesn't help us determine if it should be 2 minutes or 20 seconds.

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/f11d3a5402904984339d4166c45fc4e2bca549dd/src/server/worldserver/worldserver.conf.dist#L2883

**Comment by FrancescoBorzi** [comment]
@Si1ker if the default `Battleground.BuffRespawn ` is not correct then this is a valid issue. We didn't change it in Chromie

**Comment by Helias** [comment]
the BUFF_RESPAWN_TIME conf is applied only to warsong gulch and to all buffs, I suggest to delete this conf and put different times or use multiple conf for BG respawn times
