### ISSUE TITLE
Feature: Login and register from the website!! 

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#5104]
**Describe your feature request or suggestion in detail**

Hi, I don't understand the new structure of account table and how can I register or login from the website. 

**Describe a possible solution to your Feature or Suggestion in detail**

How can I encrypt the account password with PHP? 

**Additional context**

After the update:
485f7e76391a5bbf1af6b3219d27db721af38440
My website stop working, I use a self modify version of FusionCMS.

**Comment by Err0r1** [comment]
if you have modified fusion yourself, you should also be able to copy paste the SRP6 branch :)

Can be closed, no azerothcore feature

**Comment by skxawng-cu** [comment]
I found this https://github.com/TrinityCore/TrinityCore/issues/25157
Very helpful, I am updating my webpage, thanks.

**Comment by FrancescoBorzi** [comment]
This can also help:

https://stackoverflow.com/questions/66783717/how-to-make-salt-hash-using-php-to-register-new-account-from-web
