### ISSUE TITLE
Feature: Adjust maximum allowed players in instances

### ISSUE THREAD

**Issue by ReynoldsCahoon** [azerothcore/azerothcore-wotlk#5105]
**Describe your feature request or suggestion in detail**
I would like the ability to modify the maximum allowable number of players in any given instance. Perhaps this is already possible, but [it is not clear where to find these values](https://stackoverflow.com/questions/65309733/locating-file-controlling-instance-maxplayers).

**Describe a possible solution to your Feature or Suggestion in detail**
Other [emulators](https://github.com/cmangos/issues/wiki/Instance_template) have an extra entry in the `instance_template` table called `maxPlayers` which allows for modifying this value.

**Additional context**
[AzerothCore `instance_templace`](https://www.azerothcore.org/wiki/instance_template)
[CMangos `instance_template`](https://github.com/cmangos/issues/wiki/Instance_template)

After reviewing the differences in these table structures, it appears it would be useful to also include a `minLevel` and `maxLevel` value for that dungeon as well. Some of these values exist within the `dungeon_access_template` but it isn't clear to me that these relate to actual instance level requirements, rather than Dungeon Finder queue capability requirements.

**Comment by 55Honey** [comment]
You need to modify a .dbc file for this. I think it's map_difficulty if i remember correctly.

**Comment by ReynoldsCahoon** [comment]
> You need to modify a .dbc file for this. I think it's map_difficulty if i remember correctly.

Ah, you are correct. However, the feature request still stands, as modifying the database is a much easier endeavor than modifying `.dbc` files.

**Comment by T1ti** [comment]
There is already a map dbc table in the database, I think i works so you are free to fill it, it should overwrite DBC files

**Comment by ReynoldsCahoon** [comment]
> There is already a map dbc table in the database, I think i works so you are free to fill it, it should overwrite DBC files

Oh! I see how this works. The table shares the structure of the DBC and values in here will overwrite values from the dbc file?

This is certainly workable, but requires a user to open a dbc to determine the format of entries. It would be more convenient if these were all populated here, so they could be viewed and modified without external tools.

**Comment by ReynoldsCahoon** [comment]
The process currently, as described, is to extract a dbc, find the entry you want (referenced by it's `MapID`) and insert a row into the `mapdifficulty_dbc` table that has the modified `MaxPlayers` value.

An example of some functionality that this feature would allow:
```sql
-- Increase the number of players allowed in all dungeons by 5
UPDATE instance_template
  SET maxPlayers = maxPlayers + 5
  WHERE maxPlayers < 20;
```

For comparison, a query like this from CMangos
```sql
-- Turn Shadowfang Keep into a higher level dungeon, with an increased player capacity.
UPDATE instance_template
  SET maxPlayers = 10, levelMin = 42
  WHERE script = 'instance_shadowfang_keep';
```
In the current implementation, so far as I can tell, you'll need to reference the `dungeon_access_template` to find the `map_id` of the dungeon (or dungeons) you want to modify. You then need to insert an entry into `mapdifficulty_dbc` (referencing the current values from a dbc file) for each dungeon you want to modify. Then, I am guessing, that the minimum level is to be adjusted by updating the entry in `dungeon_access_template` table.

```sql
-- Turn Shadowfang Keep into a higher level dungeon, with an increased player capacity.
INSERT INTO mapdifficulty_dbc VALUES (7,33,0,"","","","","","","","","","","","","","","","",16712156,0,5,""); 

UPDATE dungeon_access_template
  SET min_level = 42
  WHERE `map_id` = 33;
```

Is there a reason why the dbc values can't (at the very least) be inserted by default into the mapdifficulty_dbc? That would remove one barrier to modification.

I see the value in referencing the dbc values by default, but having no template to reference from the database alone results in the StackOverflow questions that led to this feature request.

**Comment by T1ti** [comment]
you want to update your client map.dbc too, and just replacing the file in your server folder is easier

**Comment by ReynoldsCahoon** [comment]
> you want to update your client map.dbc too, and just replacing the file in your server folder is easier

Oof, it has to be modified on the client as well to work at all?

**Comment by T1ti** [comment]
For this change specifically, I don't think so(it might be needed to change the number of players on the icon near the minimap though) but for other map.dbc chanegs yes

**Comment by 55Honey** [comment]
Server-Side only works. I can run 25 in 5man heroics with a standard client just fine.

**Comment by PiotrKrzyzek** [comment]
I also would love a none file-editing way to adjust these settings :) (as the DBC file editor tool only runs on windows and is old)

**Comment by 55Honey** [comment]
Try this table: mapdifficulty_dbc

**Comment by heyitsbench** [comment]
Is this issue still valid given the proposed solutions?

**Comment by 55Honey** [comment]
I think there is a working solution already. Thanks for bringing it up bench!

**Comment by Wartem** [comment]
This worked for me:

Workaround for DrePack / MySQL 8: Increasing MaxPlayers for all instances via mapdifficulty_dbc

For anyone using DrePack or a similar repack where map_template does not exist and mapdifficulty_dbc is empty by default, here is a working solution to increase the player cap for all instances.

DrePack uses dungeon_access_template instead of the standard access_requirement table, so the approach described earlier in this thread needs to be adapted.

Run this SQL query against your acore_world database:

sql
INSERT INTO acore_world.mapdifficulty_dbc 
    (ID, MapID, Difficulty, Message_Lang_Mask, RaidDuration, MaxPlayers)
SELECT 
    (@row := @row + 1) as ID,
    map_id,
    difficulty,
    0,
    604800,
    40
FROM acore_world.dungeon_access_template, (SELECT @row := 0) r;

This inserts one row per instance/difficulty combination sourced from dungeon_access_template, setting MaxPlayers = 40 for all of them. Adjust the value as needed.

Note: MySQL 8 will produce deprecation warnings about the @row variable syntax — these are harmless.

After running the query, a full server restart is required. A .reload is not sufficient as DBC tables are loaded at startup.

Confirmed working on DrePack with MySQL 8.0.45.
