### ISSUE TITLE
(Core/Spell): Charge with spell ID 55317 is not working

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#5108]
## CURRENT BEHAVIOUR:

[Charge](https://www.wowhead.com/spell=55317/charge) which is used by [Deathcharger Steed](https://wowgaming.altervista.org/aowow/?npc=16067#abilities) is broken or not working ("You're too close" warning, no matter the distance)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Spell should be usable as a normal charge spell

## SOURCE:

[Spell on Wowhead](https://www.wowhead.com/spell=55317/charge)
[NPC which uses the spell on aowow](https://wowgaming.altervista.org/aowow/?npc=16067#abilities)

## STEPS TO REPRODUCE THE PROBLEM:

1. Go in front a monster
2. .cast 55317
3. Get "You're too close" warning

## AC HASH/COMMIT:

85d2133

## OPERATING SYSTEM:

Wdinwos10

## MODULES:

N/A

## CUSTOMIZATIONS:

N/A

**Comment by T1ti** [comment]
I am able to use it without any issue

**Comment by T1ti** [comment]
https://i.gyazo.com/ad88559dbe32dfc036f56e90e2dfd7f2.mp4

**Comment by Si1ker** [comment]
Forgot to re-run updates for DB, is working.
