### ISSUE TITLE
Warlock's Imp keeps Phase shift in combat

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#5111]
## CURRENT BEHAVIOUR:
-Imp will not lose the phase shift buff when it attacks.
-It will never be attackable by creature even if it has max threat, the creature will always go for the master because phase shift makes the imp immune.
![image](https://user-images.githubusercontent.com/40864460/113466058-10277480-9439-11eb-8d13-3c62c981957f.png)

## EXPECTED BLIZZLIKE BEHAVIOUR:
-Imp should lose phase shift when it attacks and enters combat  
![image](https://user-images.githubusercontent.com/40864460/113466086-4238d680-9439-11eb-9f79-2893bd6bc8bf.png)

## STEPS TO REPRODUCE THE PROBLEM:

1. Summon your imp as a warlock, activate phase shift. 
2. make it attack a creature and see if it loses the buff and if creature can attack it

## AC HASH/COMMIT:
85d21335da425de8f3a1488ad75753e2cfa1529e

**Comment by markvetx** [comment]
Can confirm this on ecfeecb

**Comment by Kitzunu** [comment]
I can see if I can do anything about it

**Comment by Kitzunu** [comment]
Fixed https://github.com/azerothcore/azerothcore-wotlk/pull/5960
