### ISSUE TITLE
Imp regens mana while casting

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#5113]
## CURRENT BEHAVIOUR:
-Casting doesn't stop the imp mana regen, the Imp has unlimited mana right now because of that

## EXPECTED BLIZZLIKE BEHAVIOUR:
-Imp shouldn't regen when casting, it should have to wait 5 second before being able to regen like all other entities in the game

## STEPS TO REPRODUCE THE PROBLEM:

1. get your imp to spam firebolt on a creature and look at its mana

## AC HASH/COMMIT:
85d21335da425de8f3a1488ad75753e2cfa1529e

**Comment by T1ti** [comment]
bump, pretty important issue imp is busted atm

**Comment by Kitzunu** [comment]
I can party reproduce this issue.

Testing with an 80 imp using Firebolt Rank 9 it regenerates ~62 mana once per cast.

However, it does not give it unlimited mana
![image](https://user-images.githubusercontent.com/24550914/119246098-ec51f680-bb7e-11eb-9356-2f2b668336bc.png)

So this is not totally broken, but something is weird

**Comment by T1ti** [comment]
I tested it at low level and the regen was higher than the cost
Still it doesn't matter, it shouldn't regen while casting that's the main point

**Comment by T1ti** [comment]
bump, this is pretty important imo

**Comment by FrancescoBorzi** [comment]
@UltraNix can you please have a look at this?

**Comment by UltraNix** [comment]
@T1ti Any source that Imp should not regen its mana while casting? It's a pet, not just a creature. As I know, pets have very similar regen to players.

**Comment by UltraNix** [comment]
@T1ti Some source that Imp should not regen its mana while casting?
The main problem is the formula - right now it is calculated based on spirit stat (and creature stats are incompleted and mostly wrong - especially for pets). I don't know if it is right - maybe pets should use the same formula as for players?

**Comment by T1ti** [comment]
> @T1ti Some source that Imp should not regen its mana while casting?
> The main problem is the formula - right now it is calculated based on spirit stat (and creature stats are incompleted and mostly wrong - especially for pets). I don't know if it is right - maybe pets should use the same formula as for players?

you seem to be right, it looks like a WOTLK change I wasn't aware of https://github.com/dalaranwow/dalaran-wow/issues/3216
