### ISSUE TITLE
Flurry Shaman Talent give wrong percentages.

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5115]
Related TO: https://github.com/azerothcore/azerothcore-wotlk/issues/4723

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Flurry Shaman Talent currently works with these wrong percentages:
**6/12/18/24/30%**
**Flurry:** [Rank 1](https://wowgaming.altervista.org/aowow/?spell=16256)  **6%**
**Flurry:** [Rank 2](https://wowgaming.altervista.org/aowow/?spell=16281) **12%**
**Flurry:** [Rank 3](https://wowgaming.altervista.org/aowow/?spell=16282) **18%**
**Flurry:** [Rank 4](https://wowgaming.altervista.org/aowow/?spell=16283) **24%**
**Flurry:** [Rank 5](https://wowgaming.altervista.org/aowow/?spell=16284) **30%**

This is the description of the Shaman's Flurry talent:
`Increases your attack speed by 25% for your next 3 swings` **after dealing a critical strike.**

This is the description of the Warrior's Flurry talent:
`Increases your attack speed by 25% for your next 3 swings` **after dealing a MELEE critical strike.**

So these 2 descriptions suggest that the Warrior's "critical strike" is of "Melee" nature.
Instead, the shaman's critical strike description suggests is a simple critical strike (General) not necessarily of Melee nature

##### EXPECTED BLIZZLIKE BEHAVIOUR:

World of Warcraft Client Patch 3.1.0 - (2009-04-14)
-
> **Shaman**
> 
> - **Flurry: Now provides 5/10/15/20/25% haste instead of 10/15/20/25/30%.**

**5/10/15/20/25%**
**Flurry:** [Rank 1](https://wowgaming.altervista.org/aowow/?spell=16256)  **5%**
**Flurry:** [Rank 2](https://wowgaming.altervista.org/aowow/?spell=16281) **10%**
**Flurry:** [Rank 3](https://wowgaming.altervista.org/aowow/?spell=16282) **15%**
**Flurry:** [Rank 4](https://wowgaming.altervista.org/aowow/?spell=16283) **20%**
**Flurry:** [Rank 5](https://wowgaming.altervista.org/aowow/?spell=16284) **25%**

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Plasmashield** [comment]
https://www.bluetracker.gg/wow/topic/us-en/24038450835-upcoming-enhancement-buff/
https://www.mmo-champion.com/threads/731266-Enh-Flurry-30
https://www.mmo-champion.com/threads/717750-Flurry-buff-improvement
Fixed in 3.3.5, patch notes on Wowpedia are incorrect 
Make it 30% as it should

**Comment by Shineslippers** [comment]
Have to reopen it because of https://github.com/chromiecraft/chromiecraft/issues/2709 Look like wrong fix.
