### ISSUE TITLE
(DB/POI): Your Fortune Awaits You - Wrong POI end

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#5126]
Originally reported on ChromieCraft's discord by this guy:

![image](https://user-images.githubusercontent.com/61223313/113515936-b015f880-9534-11eb-9612-3590c4d46e56.png)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [x] other (esES)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

POI end for quest [Your Fortune Awaits You...](https://wotlkdb.com/?quest=7944) is not right
Current PO ending:
![image](https://user-images.githubusercontent.com/61223313/113516421-798dad00-9537-11eb-8664-9fc10f16264e.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As seen from wowhead the POI ending should mark here:

![image](https://user-images.githubusercontent.com/61223313/113515972-f8cdb180-9534-11eb-9b51-9d75bd0ff6a0.png)
https://www.wowhead.com/quest=7944/your-fortune-awaits-you

##### STEPS TO REPRODUCE THE PROBLEM:

1. .add 19443
2. Accept the quest
3. Click on the question mark in the quest log and check where you have to go
4. Get wrong location

##### EXTRA NOTES:

Just found this but is not gonna resolve the issue
https://github.com/TrinityCore/TrinityCore/blob/1d04d5859a59caf286d71f78a18ec4ed05feb7c2/sql/old/6.x/world/02_2015_11_08/2015_11_01_13_world_from_335.sql#L2595

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/9d4eebc61fec3b9701ae94292e8d40962804b676

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Si1ker don't forget the label + project so we keep track of these ;)
