### ISSUE TITLE
can you provider the CrossFactionBG?

### ISSUE THREAD

**Issue by SymCore** [azerothcore/azerothcore-wotlk#513]
**Description**:
can you provider the CrossFactionBG? like tc's CrossFactionBG!
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
please stop opening bug reports for questions that should be asked on the forums or chat
