### ISSUE TITLE
(LOS/Spell): Blackrock Summoner cast behind pillar/walls

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#5131]
## CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/61223313/113517161-9cba5b80-953b-11eb-867b-753257b1bbe1.png)
![image](https://user-images.githubusercontent.com/61223313/113517185-a5129680-953b-11eb-99b1-b513eef9aa91.png)
![image](https://user-images.githubusercontent.com/61223313/113517190-ac39a480-953b-11eb-8cb0-7a2a7fb96f66.png)

## EXPECTED BLIZZLIKE BEHAVIOUR:

LOS

## SOURCE:

LOS sense?

## STEPS TO REPRODUCE THE PROBLEM:

1. .go c id 4463
2. Go behind a wall/pillar
3. Spells will land on you behind stuff

## OPERATING SYSTEM:

win10

## MODULES:

no

## CUSTOMIZATIONS:

no

**Comment by wizzymore** [comment]
I don't know about Wrath Retail, but on classic wow it is the same.

**Comment by Helias** [comment]
yep, I heard that this kind of LoS is "blizzlike", even through the trees.

If we can fix it is better ofc, but probably the structure of these kind of "3d object" are not a "wall" for the spells, so may we could not even fix them for the nature of the 3d models properties

**Comment by Si1ker** [comment]
Good enough, closing..
