### ISSUE TITLE
Melee spells with 1s GCD getting affected by Casting Speed Debuffs

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#5136]
## CURRENT BEHAVIOUR:
The global cooldown of physical spells that have 1s GCD are getting affected by spells that increases casting speed (Curse of Tongues, Rogue Mind Numbing Poison, Snake Trap Mind Numbing Poison, mage arcane Slow, Hunter BM pet Lava Breath, etc). 

The GCD is the same, but after using a physical spell, you need to wait ~0.3 sec before being able to use another spell, even though the GCD is gone already.

Physical spells with 1.5s GCD dont suffer from this problem.

## EXPECTED BLIZZLIKE BEHAVIOUR:
Should be able to use spells after the GCD is reseted, not needing to wait ~0.3 sec. 

## SOURCE:
Video that i recorded:
https://www.youtube.com/watch?v=SIzNYvK59JQ
Check the Stopwatch in the left, you can see that first without Curse of Tongues, i can use 10 Mangle (Cat) in 11 seconds. 
Then, with Curse of Tongues i have this weird GCD which makes me only being able to use 9 Mangle (Cat) in 12 seconds. Meaning one less GCD and 1 second more.

## STEPS TO REPRODUCE THE PROBLEM:
1.  Get a druid with Cat Form.
2.  Type .mod energy 50000.
3.  Test GCD of physical spells (Mangle, Rake, Shred, Swipe, etc)
4.  Now type .aura 11719 on yourself and test the spells again, theres a weird delay to be able to use spells after the GCD.

## EXTRA NOTES:
Maybe these debuffs shouldn't increase the GCD of spells (physical or magic), and should only increase the casting speed.
But i dont have any proof.

## AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/d20a15355c1a

## OPERATING SYSTEM:
Windows 10

**Comment by laasker** [comment]
After more tests i found that every melee spell with 1s gcd suffers from this problem.
So, basically (as far as i remember) every spell from Rogue, Druid Cat Form(melee spells), Dk in Unholy Presence and Warrior Overpower.

I believe spells with 1.5s GCD dont suffer from this problem because of the max GCD cap in spell.cpp

**Comment by Shineslippers** [comment]
The issue is existing. Just need to confirm this is not normal behavior

https://user-images.githubusercontent.com/85256266/141643627-da53856c-69ad-42f3-9ac0-a29158275b93.mp4

**Comment by laasker** [comment]
> The issue is existing. Just need to confirm this is not normal behavior.
> 
>  2021-11-13.15-21-10.mp4 
> `Cast time` debuffs doesn't affecting instant `spell` casts on Priests and etc. So it should not affecting any of rogue's and etc casts because all ot if instant also. Even regardless of source.
> 
>  2021-11-13.16-08-20.mp4

Thanks for the testings, i appreciate
