### ISSUE TITLE
[Dungeon] Gundrak - Gal'darah's Rupture after death

### ISSUE THREAD

**Issue by Alegrum** [azerothcore/azerothcore-wotlk#514]
**Description**:
Currently after you kill the boss, if Rupture spell is still active it will stay until it wears off.

**Expected behaviour**: After the boss dies Rupture must disappear.

**Steps to reproduce the problem**:
1.  Engage Gal'darah
2.  Get hit by Rupture
3.  Kill the boss

**Branch**: master

**AC hash/commit**:

**Comment by HeartWell** [comment]
Why rupture aura needs reset?

**Comment by HeartWell** [comment]
https://youtu.be/gkCf1ZcOkQU

**Comment by Alegrum** [comment]
You have a point.

**Comment by talamortis** [comment]
This issue is invalid. Tested on retail to be on the safe side and the debuff stays on when boss dies.
