### ISSUE TITLE
SPELL_AURA_PREVENT_DURABILITY_LOSS (289) is unusued 

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#5147]
SPELL_AURA_PREVENT_DURABILITY_LOSS (289) is unusued, probably in past we didn't know that the aura 289 was this kind of aura, we need to implement it (look TC to see how it works).

**Comment by Kitzunu** [comment]
```cpp
void Player::DurabilityPointsLoss(Item* item, int32 points)
{
    if (HasAuraType(SPELL_AURA_PREVENT_DURABILITY_LOSS))
        return;
```

**Comment by Kitzunu** [comment]
Only place used

**Comment by Helias** [comment]
yep, exactly, it's easy to import ;-)
don't forget to update `SpellAuraEffects.cpp` too, line 351 with
```C++
    &AuraEffect::HandleNoImmediateEffect,                         //289 SPELL_AURA_PREVENT_DURABILITY_LOSS implemented in Player::DurabilityPointsLoss

```

**Comment by Kitzunu** [comment]
Yea, ik, thought that was obvious :D

**Comment by Kitzunu** [comment]
Done
