### ISSUE TITLE
Quest Item "Incendia Agave" Not Spawning Underwater

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#5152]
https://github.com/chromiecraft/chromiecraft/issues/344

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

The level 27 Horde quest "Sacred Fire" requires you to collect 10 units of a herb called Incendia Agave. This is supposed to be found in and around the Boiling Pools at 36, 36 in Thousand Needles. WH classic link to the quest is here:

https://classic.wowhead.com/quest=5062/sacred-fire

The problem is that the Agave is not spawning underwater in the pools. There are 2 or 3 nodes that spawn around the edges on dry land, but for some reason, none seem to be spawning underwater. The quest is currently finishable thanks to the spawns on dry land, but takes much longer than it should because you need to wait for the same couple of spawns to refresh.

I first thought that maybe someone had harvested all the underwater nodes, so went away and came back 20 minutes later, and Agave was still only spawning above water. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Expected behaviour is that most of the Agave spawns are underwater. To quote from the Wowhead Classic link above:

"Most of the plants needed are underwater."
"A couple of the plants are on land and the rest are in the water. "
"I swear there are more plants in the actual water than above it..."

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept quest "Sacred Fire" from Motega Firemane (https://classic.wowhead.com/npc=10428/motega-firemane)
2. Go to Boiling Pools around 36, 36.
3. Look for sparkling clumps of Agave. There will be some on the edge of the pools, but none underwater.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
I would add:
there are only 5 spawns of the object to gather the quest item, while the quest ask for 10 quest items, moreover, wowhead also shows more than 5 spawns.

**Comment by FrancescoBorzi** [comment]
I would add the project :D
