### ISSUE TITLE
[Warrior] Victory Rush does not allow for use if Victory Rush was used as the Killing blow

### ISSUE THREAD

**Issue by iEmpress** [azerothcore/azerothcore-wotlk#5156]
## CURRENT BEHAVIOUR:
 If Victory Rush is used as the killing blow on a target it is not available for use afterwards.

## EXPECTED BLIZZLIKE BEHAVIOUR:
 Victory Rush should always be available for use after a target dies, even if Victory Rush was used as the killing blow.

## SOURCE:
Proof from Classic TBC beta: https://youtu.be/imySyB3cOO0?t=209

## AC HASH/COMMIT:
  AzerothCore rev. ee1918a3e9bc

## CUSTOMIZATIONS:
 ChromieCraft customizations.

**Comment by Stump876** [comment]
I can confirm it's acting that way. I can't find any evidence if that is blizzlike behavior. All I find is it proc's "after a killing blow on an enemy that yields exp or honor" To me that means even if that ability was used to land the killing blow. 

That video made me dizzy and I can't *really* tell what happened without looking at the combat log. There is so much damage going on there. I do see it proc twice in close proximity, but I can't see if there was a swing, or something in between. There is also some debate on if it actually did a 15% heal in Wrath and upped to 20% in 4.0. The current tooltip doesn't say anything about a heal, but it does say it's useable "after you kill an enemy"  Killing an enemy with victory rush is still killing an enemy. I believe this is valid

**Comment by necropola** [comment]
I agree 100%. I could not find any source that would say that **Victory Rush** can't be the **Killing Blow** itself. And why shoudln't it? I'd consider this a valid bug report even if it were on retail.

**Comment by Kitzunu** [comment]
about the 15/20% this comment states it was upped in cata as I understand it https://www.wowhead.com/spell=34428/victory-rush#comments:id=1096042

**Comment by necropola** [comment]
It didn't have a heal before cata at all.
This is from Wowpedia just before cata release.:
https://wowpedia.fandom.com/wiki/Victory_Rush?oldid=2519660

**Comment by aradep** [comment]
This is broken again on https://github.com/azerothcore/azerothcore-wotlk/commit/df82d1be97ec25e909f581c1460990d893113ca1
