### ISSUE TITLE
Brutal Assault debuff remaining after Warsong Gulch ends

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5157]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/179

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

All

##### SMALL DESCRIPTION:

Spell: [Brutal Assault](https://www.wowhead.com/spell=46393/brutal-assault) will sometimes remain on the flag carrier after Warsong Gulch ends and they leave.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Brutal Assault (and Focused Assault) should be removed upon leaving Warsong Gulch

##### CURRENT BEHAVIOUR:

I had the Brutal Assault debuff after a Warsong Gulch ended and I teleported back to Orgrimmar. It ended 0-0 after 25 minutes and I was in bear form and jumping around in the area where you capture the flag when it ended.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Enter Warsong Gulch
Step 2 Have both teams hold the flag until Brutal Assault
Step 3 Wait for Warsong Gulch to end, possibly be shapeshifted, jumping, or in flag area as it ends.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Could be fixed with my PR. Couls you test if it would fix it?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4990

**Comment by Stifler82** [comment]
> #4990


@Kitzunu 
I wold like, but idk how i should test it, because (if i understood it right), this issue is a "Random" bug, and in more i should join a BG for test it and i can't in my local, I would need "Players" for test..

**Comment by Kitzunu** [comment]
You could .debug bg and then aura the spell on you and see if it stays or not

**Comment by Stifler82** [comment]
> You could .debug bg and then aura the spell on you and see if it stays or not

ok, I'll try

**Comment by Stifler82** [comment]
@Kitzunu  when the aura should disappear exactly?

**Comment by Kitzunu** [comment]
If I understand your issue correctly, the aura persists when you leave the BG. If my PR would solve this issue, it should remove when you exit the BG.

If not it's fine, then this is just another issue

**Comment by Stifler82** [comment]
OK give me a sec, I'll make a Video for you..

**Comment by Kitzunu** [comment]
I dont have the ability to watch videos rn. Would prefer if you just tell me if it solves this issue or not :P

**Comment by Stifler82** [comment]
Fixed!
-
**Video Test:** [Brutal Assault Without my Fix](https://youtu.be/BB6wFEorAZE)
**Video Test:** [Brutal Assault with my Fix](https://youtu.be/sHs_AYOsZIo)
