### ISSUE TITLE
Instant random death from fall damage while on flat ground.

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#517]
**Description**:
Instant random death from fall damage while on flat ground.

**Current behaviour**:
Sometimes you die from fall damage while you didn't fall at all.
I've read it happened on classic mangos servers like Nostalrius too.

It seems to be similar to this : 
https://www.youtube.com/watch?v=o8LnjGTF-WY&t=4m21s

**Expected behaviour**:
No fall damage.

**Steps to reproduce the problem**:
No idea how to reproduce, a player reported it to me like this "the undercity elevator bugged out and i got crushed between platform and door wtf"
Look at the video above instead.

**Branch(es)**: master (1.04+)

**AC hash/commit**:  

**Operating system**: 
Debian 8

**Other Customizations**:
Permadeath system, so it's very annoying for my case :P

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
me and @Inifield  can not repoduce this issue
