### ISSUE TITLE
Map extractor Compile error / ACore update doesn't contain updated maps

### ISSUE THREAD

**Issue by Inversed98** [azerothcore/azerothcore-wotlk#5179]
Error: https://pastebin.com/h7KYKmYf
https://pastebin.com/3jn2Dw2A

## CURRENT BEHAVIOUR:

Unable to compile the maps extractor. Can't compile the core without the maps. The new update doesn't contain updated maps.
After this https://github.com/azerothcore/azerothcore-wotlk/commit/0528e0b4855331572d65237198e1510444fe2cec commit the server won’t start. Data v9 from here https://github.com/wowgaming/client-data/tags vmaps are not longer compatible and the extractors are not compiling so there is no way to create the maps. If somebody has them can you share a link ?

## STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

## AC HASH/COMMIT:
 a298803

## OPERATING SYSTEM:
 Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
Debian 10

**Comment by Kitzunu** [comment]
Use gist or pastebin

**Comment by FrancescoBorzi** [comment]
what do you mean by `The new update doesn't contain updated maps.` ? where do you expect them to be "contained"?

I don't understand your issue, the new maps worked fine for me

**Comment by Inversed98** [comment]
> what do you mean by `The new update doesn't contain updated maps.` ? where do you expect them to be "contained"?
> 
> I don't understand your issue, the new maps worked fine for me

I just edited the post I hope it makes sense now. Check the second link to pastebin.

**Comment by FrancescoBorzi** [comment]
>  Data v9 from here https://github.com/wowgaming/client-data/tags vmaps are not longer compatible 

you need v10 now, from the same URL
