### ISSUE TITLE
Vmap issues: Invisible collision + creature spawn

### ISSUE THREAD

**Issue by Footman** [azerothcore/azerothcore-wotlk#5180]
## CURRENT BEHAVIOUR:

After integration of pull request #4922 by @UltraNix there are some new issue. In the client there are some invisible collisions like the one on the screenshot. This collision is there to prevent players to cover NPC on this place.
The problem is that those NPCs cant spawn at this place anymore and fall throw the floor.

![image](https://user-images.githubusercontent.com/136351/113920364-5a1faa00-97ed-11eb-8ec5-4aa7aaca234f.png)

## EXPECTED BLIZZLIKE BEHAVIOUR:

- Need to remove invisible collision from vmap / mmap
- Or make it possible NPC spawns to ignore it

## STEPS TO REPRODUCE THE PROBLEM:

1. .go xyz 4938 2389 327 631
2.  See that NPCs are not there (they are under the floor)

## AC HASH/COMMIT:

a298803

**Comment by UltraNix** [comment]
It's not because of new vmaps/mmaps, but wrong phase mask implementation/handling for destructibles. Will look at this tomorrow.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/113962746-dc928300-985a-11eb-8322-0e73fe118679.png)
Players don't fall when they stand here

**Comment by skxawng-cu** [comment]
I can confirm this issue, I have the same problem after update the core and download client data v10.

**Comment by FrancescoBorzi** [comment]
@skxawng-cu please test the fix to this issue: https://github.com/azerothcore/azerothcore-wotlk/pull/5188

and let us know how it goes
