### ISSUE TITLE
Demoralizing Roar is not revealing stealth / prowl

### ISSUE THREAD

**Issue by Drakelol** [azerothcore/azerothcore-wotlk#5181]
Demoralizing Roar is not revealing stealth / prowl

The demoralizing roar spell does not remove the stealth
https://wotlkdb.com/?spell=99#see-also

When the druid is in the battle against a rogue and he uses Demoralizing Roar, the sneak does not come out of the rogue.

STEPS TO REPRODUCING THE PROBLEM:

1. Druid vs Rogue Duel
2. Rogue uses Stealth spell
3. Druid uses Demoralizing Roar spell near rogue
Does not remove Stealth

 

rev. 11ff55e0759a

@Kitzunu sorry!

**Comment by Kitzunu** [comment]
Please do not ignore the issue template

**Comment by Kitzunu** [comment]
Okay so close, but still missing rev

**Comment by Drakelol** [comment]
I added the rev, thanks!

**Comment by Kitzunu** [comment]
fixed https://github.com/azerothcore/azerothcore-wotlk/compare/master...Kitzunu:fix-Demoralizing-Roar?expand=1

**Comment by FrancescoBorzi** [comment]
> fixed #5197

@Drakelol please test it

**Comment by Drakelol** [comment]
I applied the change, and it's working!
Thanks!
