### ISSUE TITLE
WordServer starts with some Modules configuration errors

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#5208]
## CURRENT BEHAVIOUR:

> Config: Missing name Gambler.Announce in config, add "Gambler.Announce = 1"
> Config: Missing name Gambler.Amount1 in config, add "Gambler.Amount1 = 1"
> Config: Missing name Gambler.Amount2 in config, add "Gambler.Amount2 = 2"
> Config: Missing name Gambler.Amount3 in config, add "Gambler.Amount3 = 3"
> Config: Missing name Gambler.Amount4 in config, add "Gambler.Amount4 = 4"
> Config: Missing name Gambler.Amount5 in config, add "Gambler.Amount5 = 5"
> Config: Missing name Gambler.Jackpot in config, add "Gambler.Jackpot = 50"
> Config: Missing name Gambler.MoneyType in config, add "Gambler.MoneyType = 3"
> Config: Missing name Gambler.EnableGold in config, add "Gambler.EnableGold = 1"
> Config: Missing name Gambler.EnableSilver in config, add "Gambler.EnableSilver = 1"
> Config: Missing name Gambler.EnableCopper in config, add "Gambler.EnableCopper = 1"
> Config: Missing name Gambler.MessageTimer in config, add "Gambler.MessageTimer = 44940"
> Config: Missing name Gambler.MessageTimer in config, add "Gambler.MessageTimer = 60000"
> Config: Missing name DungeonAccessRequirements.PrintMode in config, add "DungeonAccessRequirements.PrintMode = 1"
> Config: Missing name DungeonAccessRequirements.PortalAvgIlevelCheck in config, add "DungeonAccessRequirements.PortalAvgIlevelCheck = 0"
> Config: Missing name DungeonAccessRequirements.LFGLevelDBCOverride in config, add "DungeonAccessRequirements.LFGLevelDBCOverride = 0"
> Config: Missing name DungeonAccessRequirements.OptionalStringID in config, add "DungeonAccessRequirements.OptionalStringID = 0"

## EXPECTED BLIZZLIKE BEHAVIOUR:
These errors should not exist

## STEPS TO REPRODUCE THE PROBLEM:
Use the current AC version and add these modules, then use cmake../ -dcmake_install_prefix =/ WWW /game/server/ -dcmake_cxx_compiler ="clang" -dcmake_cxx_compiler ="clang++" -dwith_warnings = 1-dtools = 1-dscripts = 1-denable_extras =1 to compile it

## AC HASH/COMMIT:
cc48695

## OPERATING SYSTEM:
Ubuntu18

## MODULES:
mod-anticheat
mod-cfbg
mod-duel-reset
mod-eluna-lua-engine
mod-npc-gambler
mod-transmog
mod-weekend-xp
mod-world-chat

**Comment by ErnestoGonzalezC** [comment]
@yuanf225  In the config folder there must be both the .conf.dist and .conf configuration files.

**Comment by yuanf225** [comment]
![微信图片_20210409235951](https://user-images.githubusercontent.com/43561197/114208660-4ceef080-9990-11eb-94e7-8aa1a6e538d4.png)
At the same time there is

**Comment by Kitzunu** [comment]
@azerothcore/modules is this an issue within the core or with the respective modules?

**Comment by HerrPony** [comment]
I've had the same problem with solocraft but i'm not using it anymore.
Every other module loads just perfectly

**Comment by Nyeriah** [comment]
The modules that cause this need to be fixed, not a core issue. Closing.
