### ISSUE TITLE
Blackfathom Deeps is locked/ended if you wipe on the Torches event.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5213]
https://github.com/chromiecraft/chromiecraft/issues/220

## CURRENT BEHAVIOUR:

Blackfathom Deeps is locked/ended if you wipe on the Torches event.

## EXPECTED BLIZZLIKE BEHAVIOUR:

The mobs should not despawn. They should chill in a huddle until you respawn and attempt them again.

## SOURCE:

Wipe at 3:38

2nd attempt at 11:00

https://www.youtube.com/watch?v=cUJXEj8hIdM

Cata live footage from the time.

-----

Source 2

Wipe at 55:50

Second attempt at 56:00ish.

https://youtu.be/snSTzDUNO-s?t=3350

WoW Classic footage

## STEPS TO REPRODUCE THE PROBLEM:

1. Enter BFD
2. Light all the torches like a smoothbrain
3. Wipe
4. Attempt to continue the dungeon

## EXTRA NOTES:

**We are not 100% sure what the intended behaviour is.** The above video sources are great, probably good enough, but they're not from vanilla, tbc, or wotlk. They're from 2020 wow classic and Catacalysm.

"The Fire of Aku'mai event is a small event after Lord Kelris that is required to open the door to the final boss of BFD, 
All 4 braziers and subsequently all 4 waves must be conquered before the door to Aku'Mai's lair opens..."

This is a quote from the dungeon guide. It implies you must pass the event to finish the dungeon. To me, personally, it reads like a wipe "fails the event" and fails the dungeon.

![image](https://user-images.githubusercontent.com/61194190/114242930-98e76880-9983-11eb-92c0-8483d0e4e801.png)

In 2005 a guy got wrecked by a group of idiots lighting all torches. He says about what he thinks is up ahead, implying the wipe stopped them from progressing further. To me this supported the idea that wiping at the torches = no door opens. It could just mean his group disbanded and quit, it could, maybe.

I'm putting the priority as low. The dungeon is completeable and working if you don't light all 4 torches at once and wipe. It teaches new players a valuable lesson with consequences if they light all 4 at once and wipe. Personally I prefer the current behaviour, but I do think that Blizzlike is shown by the two source videos above.

There are no WoWHead comments that explicitly say "if you fail the torch room, you are locked out". People even complained about not being able to swim as ghosts (lmao just aim down and swim). They would've complained, I think.

Guides from 2005-2009 era do not warn "if you fail the event, the dungeon ends". An absense of evidence isn't necessarily evidence, but you'd think there'd be a mention or note of how it works if this was the case.

https://cdn.discordapp.com/attachments/788063060430290948/830213075432112160/JPEG_20210409_185020.jpg

https://www.wow-pro.com/20-27-blackfathom-deeps-guide/

We're not 100% sure how it works, but I'm 95% sure the mobs should stay and you can attempt it again. **There is more evidence on this side.**

Related: https://github.com/chromiecraft/chromiecraft/issues/220

## AC HASH/COMMIT:

AzerothCore rev. 9d4eebc 2021-04-01

## MODULES:

CFBG

**Comment by orfaze** [comment]
Confirmed

**Comment by eTzmNcbkrng** [comment]
Nothing here indicates it was ever the case that wiping on this event caused the dungeon to need to be reset.
https://wowpedia.fandom.com/wiki/Blackfathom_Deeps#Patch_changes
https://wowwiki-archive.fandom.com/wiki/Blackfathom_Deeps#Patches_changes

The text "[Right-click these one at a time because a small group of mobs is summoned from the adjacent doors every time you do. Defeat these one at a time to avoid death.](https://wowwiki-archive.fandom.com/wiki/Blackfathom_Deeps?oldid=1778260#Walkthrough)" was added 18/Feb/2009 (8 days after the release of Patch 3.0.9) and remained unchanged until present day. It never mentioned wiping would cause the dungeon to be uncompletable.

**Comment by Kitzunu** [comment]
@Stifler82 it is very useful if you leave coments to why an issue gets closed.

Both for the author to understand the reason and fpr pther staff members to not be confused. Especially when all comments proves this is a bug.

Thanks =)

**Comment by eTzmNcbkrng** [comment]
@FrancescoBorzi There is no reason for failing this event to cause Blackfathom Deeps to be uncompletable.

We've provided actual video footage of it working the way we're saying it should be, from two different periods (Classic and Cata).
There's no documentation that it was changed to this state and then back again, which is a pretty big change and you would think that info would exist somewhere.

We're being asked to prove a negative, when there's no evidence for it to be the way it is now either.

**Comment by Kitzunu** [comment]
I am going to reopen this as it seems valid to me and nothing proving otherwise.

**Comment by Stifler82** [comment]
The reason is that they've come to "Cry" multiple times for this reason, calling this mechanic a "Bug" each time.
BUT!
They never have a shred of proof that this is a Bug, they ONLY provide links where they say: "There are no references that the Dungeon needs to be reset if wiped".

Yes, maybe that's true, but there aren't even references that say the opposite, so 50% and 50%.

**So for me the rule applies:**
**(NOT GUILTY) until proven otherwise.**
IN THIS CASE:
**(NOT BUGGED) until proven otherwise.**

Because the fact that there are no references on WIPE does not constitute tangible proof but only "CLUE".
And the same is true in reverse:

If they wipe, because they are not able / good to finish the event, it is not our fault.

**Comment by Stifler82** [comment]
Now i left the comment/reason...

**Comment by Stifler82** [comment]
Ok @FrancescoBorzi  changed my mind about the problem because he showed me the problem from a different perspective that I hadn't considered.

This however does not change my previous reasons, it only changes the result..

**Comment by Stifler82** [comment]
Theoretically, the last Boss should be the "reward" for running the entire Dungeon correctly, so you can proceed to the next step (ONLY IF) you have also finished the "Boss Event".

If you fail the boss event, you cannot proceed to the next step.
In CLASSES and in TBC many dungeons have this "Behavior" / "Mechanics".

So I'm still undecided on this issue.

**Comment by Kitzunu** [comment]
As I havent tested this yet, only read the issue what I get from it is that if you fail the boss the entire dungeon resets to 0, if thst is correct then I believe it to be a bug.

As far as my knowledge goes only that encounter should reset, not the entire dungeon.

Did I understand the issue correctly?

**Comment by eTzmNcbkrng** [comment]
No, the issue in question is not a boss.
After you defeat [Twilight Lord Kelris](https://wowpedia.fandom.com/wiki/Twilight_Lord_Kelris) there is a door behind him that can only be opened after completing this event.
There are four torches that need to be lit, each torch summons a wave of enemies that must be defeated.
Currently, if you wipe during this event, the mobs despawn and you cannot relight the torches, making the door to the final boss impossible to open.

**Comment by Stifler82** [comment]
> As I havent tested this yet, only read the issue what I get from it is that if you fail the boss the entire dungeon resets to 0, if thst is correct then I believe it to be a bug.
> 
> As far as my knowledge goes only that encounter should reset, not the entire dungeon.
> 
> Did I understand the issue correctly?

No, then ..
The event referenced in the issue is this:
**Video Test:** [Blackfathom Deeps](https://youtu.be/xgVKFQIBJq0)
this is the penultimate Boss (which is an event).

If you fail this event, you cannot finish (The Last Boss)
this is a known behavior in both Classic and TBC.
So the dungeon can do it all, but if you DON'T finish the event that is there before the last boss, you can't finish it

**Comment by Stifler82** [comment]
@Kitzunu 
The point is:
- The boss is behind the door.
- If you don't finish the Boss event, the door won't open.
- If the door doesn't open (OBVIOUSLY) you can't get to the last Boss

So in fact: The Dungeon is correct like this.

**Comment by Kitzunu** [comment]
Ah okay then we're on the same page.

Really strange that I never heard of this behaviour before. But then I have mostly only cared about wotlk content...

I mean stright out of the box it only make sense that only the event would reset. But I can see where Stiffler is coming from if it works like this somewhere else too. (Could you provide me with an example, that way I can more easily look into this)

Tomorrow i can check if I can find something about it.

**Comment by Stifler82** [comment]
@Kitzunu 
And if you see my video i can get it better..

**Comment by Stifler82** [comment]
@Kitzunu 
The last Boss is a: "Reward" because you finished the event boss (In fact they put there a "Closed" door there)..
(IF) you get the Door (OPEN) you can get the  last Boss..

**Comment by Kitzunu** [comment]
Yea no misunderstanding there

**Comment by Stifler82** [comment]
For this reason for me this is not a bug..
Because the killing of the Boss is based on the ability of the players to finish the previous boss event.

**Comment by Kitzunu** [comment]
Yea I get that view and I agree so far.
What I want to investigate is if the entire dungeom should reset if you wipe to it. It's like if ICC reset if you wiped on Sindragosa pre event.

Maybe Blizzard did that back in the day, but just hearing it without prior knowledge of the dungeon it seems weird.

It is a prerequisite to finish it before the last boss, as any other boss/event before it. We just need to figure out if only the event should restart/reset or if the dungeon should be started from 0. As I understand it

**Comment by Stifler82** [comment]
@Kitzunu 
Do you suggest making the torches retriggerable so that players can retry the event until they succeed?

**Comment by Kitzunu** [comment]
That is what I want to find out. If the event can be redone if failed

**Comment by Stifler82** [comment]
Well, regardless of your research, we could do it anyway, because in any case the purpose of the event is to "Deserve" the chance to kill the last Boss and thus get his loot, if after 10 attempts **(to say)** in the end they manage to do it, in any case it is a deserved thing, so it would be fine for me too.
For me is fair enough in this way..

**Comment by Kitzunu** [comment]
I totally agree and it is more logical thst way too, so you dont have to redo the entire dungeon due to wiping at specific event.

I will put this issue as confirmed and anyone that fixes it should do it as mentioned above.

**Comment by T1ti** [comment]
I've already wiped on this event in Classic, the mobs will stay and you just have to beat them, it is not locked

**Comment by ReynoldsCahoon** [comment]
Another example from a Classic playthrough, that the torches are lit (this group wipes) they return to the room, and the mobs are still present. Once killed, the door opens. [Timestamp of their return after the wipe: 1:17:56](https://youtu.be/-K6N_Pagwcc?t=4676).

I will hop on my classic character at some point and test if there's a despawn timer, or if they remain indefinitely.

For sure the braziers light only once, and remain lit for the remainder of that instance's lifetime.

**Comment by Stifler82** [comment]
OK, then..
There is one thing to understand here, a point that (from what I read from the comments) eludes everyone..
- **New WoW Classic** = **Is Not (THE SAME) Old WoW Classic**
- **New WoW TBC** = **Is Not (THE SAME) Old WoW TBC**
and when they will make:
- **New WoW WOTLK** = **it will Not (THE SAME) Old WoW WOTLK**

This because they are making those **"New"** expansion as a **"Re-Make"**
So, them will have some different.
Them will be the same but at same time **they will not.**

**Is it clear it now?**

Therefore, the indications of Blizzard's current WoW Expansions **are NOT RELIABLE.**

Plus, also **(IF)** the dungeon is a **"Classic"** dungeon **(ALWAYS REMEMBER)** that the **(CURRENT)** expansion **is WOTLK!**
And as **(ALL) "should" know**, with each expansion there are changes in the **Zones / Dungeons / BG / etc..**

So as a **"Reference" you cannot use "the true Classic" (OLD)** because this expansion **is WOTLK!**

**Comment by ReynoldsCahoon** [comment]
Your point is taken. Unless we have video footage from actual Wrath of the Lich King, we cannot conclude this with certainty.

However, assuming this functionality works this way in both Classic, and TBC Classic, and there is no footage that can be retrieved showing it working differently, I think the burden of proof actually rests on you to provide details for why it should work the way that it does, as all evidence we have available indicates that it works differently than it does here.

**Comment by Stifler82** [comment]
> Your point is taken. Unless we have video footage from actual Wrath of the Lich King, we cannot conclude this with certainty.
> 
> However, assuming this functionality works this way in both Classic, and TBC Classic, and there is no footage that can be retrieved showing it working differently, I think the burden of proof actually rests on you to provide details for why it should work the way that it does, as all evidence we have available indicates that it works differently than it does here.

I DO NOT HAVE to prove anything, for the simple reason that I did NOT open the report (Claiming) that the Dungeon is Bugged.

Plus, I've been a WoW player since 2007 and I know how WoW mechanics worked back then.

To be honest I haven't done this dungeon many times, and all the times I've done it with high level guild PCs helping me, so I've never done Wipe.

But what I know is that I have seen (in other Dungeons / instances) this mechanic that, (IF) you don't kill the Boss Event you can't go to the next step, (The Last Boss)

So, I hope that this is clear now, because I can't explain this better than that, because otherwise the only chance I have left is to find someone who speaks fluent moron..

**Comment by ReynoldsCahoon** [comment]
I'm not sure what I said that merited hostility.

**Comment by Stifler82** [comment]
> I'm not sure what I said that merited hostility.

In fact i wasn't speak directly with you..(in general)

**Comment by Stifler82** [comment]
So nothing personal..
Let's say that when I find myself explaining a concept after 999 times to 1000 times I get impatient..
After all, I'm human too..

**Comment by T1ti** [comment]
> OK, then..
> There is one thing to understand here, a point that (from what I read from the comments) eludes everyone..
> 
> * **New WoW Classic** = **Is Not (THE SAME) Old WoW Classic**
> * **New WoW TBC** = **Is Not (THE SAME) Old WoW TBC**
>   and when they will make:
> * **New WoW WOTLK** = **it will Not (THE SAME) Old WoW WOTLK**
> 
> This because they are making those **"New"** expansion as a **"Re-Make"**
> So, them will have some different.
> Them will be the same but at same time **they will not.**
> 
> **Is it clear it now?**
> 
> Therefore, the indications of Blizzard's current WoW Expansions **are NOT RELIABLE.**
> 
> Plus, also **(IF)** the dungeon is a **"Classic"** dungeon **(ALWAYS REMEMBER)** that the **(CURRENT)** expansion **is WOTLK!**
> And as **(ALL) "should" know**, with each expansion there are changes in the **Zones / Dungeons / BG / etc..**
> 
> So as a **"Reference" you cannot use "the true Classic" (OLD)** because this expansion **is WOTLK!**

Classic is 99.99% the same as vanilla 1.12...
The core mechanics are the same, and the database and scripts are unchanged, there is absolutely 0 reason for it to work differently in classic than in vanilla 1.12

**Comment by eTzmNcbkrng** [comment]
Do you not think that if there was a mechanic that made the dungeon unable to be completed that it would be well documented from the moment someone first discovered it?
We have video evidence of it working a particular way 1 expansion later, with no patch notes/guides saying that it was changed.
We have video evidence of the remake of the original working the same way.

All the documentation from time advises to light one torch at a time *so you don't die*, if it was the case that lighting more than one torch completely scuffed the ability to get to the final boss, wouldn't that be ALL over the internet?

**Comment by Stifler82** [comment]
> > OK, then..
> > There is one thing to understand here, a point that (from what I read from the comments) eludes everyone..
> > 
> > * **New WoW Classic** = **Is Not (THE SAME) Old WoW Classic**
> > * **New WoW TBC** = **Is Not (THE SAME) Old WoW TBC**
> >   and when they will make:
> > * **New WoW WOTLK** = **it will Not (THE SAME) Old WoW WOTLK**
> > 
> > This because they are making those **"New"** expansion as a **"Re-Make"**
> > So, them will have some different.
> > Them will be the same but at same time **they will not.**
> > **Is it clear it now?**
> > Therefore, the indications of Blizzard's current WoW Expansions **are NOT RELIABLE.**
> > Plus, also **(IF)** the dungeon is a **"Classic"** dungeon **(ALWAYS REMEMBER)** that the **(CURRENT)** expansion **is WOTLK!**
> > And as **(ALL) "should" know**, with each expansion there are changes in the **Zones / Dungeons / BG / etc..**
> > So as a **"Reference" you cannot use "the true Classic" (OLD)** because this expansion **is WOTLK!**
> 
> Classic is 99.99% the same as vanilla 1.12...
> The core mechanics are the same, and the database and scripts are unchanged, there is absolutely 0 reason for it to work differently in classic than in vanilla 1.12

Oh sorry, do you work to Blizzard?
Sorry i didn't know it..

**Comment by T1ti** [comment]
Do you work at blizzard to know it is changed ?

I'm active in the vmangos emulator, Classic has been investigated a LOT, it's very clear that classic scripts and database are all exactly the same as vanilla

**Comment by ReynoldsCahoon** [comment]
This comment from a [Thottbot user during patch 2.0.1.2](https://classic.wowhead.com/npc=4832/twilight-lord-kelris#comments:id=2811498) supports the functionality being asked for in this report

> Well after kelris our other lv 24 hunter had to leave... so that left just the lv 23 warrior, the lv 22 pally and me to kill aku'mai. We lit the first 2, of course at seperate times, and were able to kill those minions. The turtles gave us some trouble, but we were able to do it in the end. The third candel gave us trouble. Those two elite water elements kept using that massive magic spell on us and killed the warrior in 2 hits. I tried to keep up, but I was to slow. **We died quickly the first time, the second time I got hit pretty badly so i had to heal myself at the same time. We died again... but th ethird time we tried, we were able to almsot kill 1 of them, but in the end we all died.** We were disappointed, but I totally forgot that kelris was the one who was supose to drop the staff, not aku'mai. Kelris didn't drop the staff, so that to was disapointing. Well I will be heading back there this afternoon for another room.

This confirms that the mobs survived through three separate attempts, and because they could not kill the mobs, they could not proceed.

All braziers must be touched, and all mobs that spawn must be killed, or the door will not open.
The mobs do not despawn (or if they do, it's a very long timer).
The braziers do not extinguish.

**Comment by Stifler82** [comment]
> Do you work at blizzard to know it is changed ?
> 
> I'm active in the vmangos emulator, Classic has been investigated a LOT, it's very clear that classic scripts and database are all exactly the same as vanilla

No, I don't work there. as it seems you do.
But I notice things, and I wonder "Why" Blizzard made the "OLD" DB of "Wowhead" disappear and "Why" is doing it all over again (if they already had the data) why do it again ?.

Unfortunately some people have the brain as a divider for their ears.

Instead, I use it to reason..

**Comment by Stifler82** [comment]
> This comment from a [Thottbot user during patch 2.0.1.2](https://classic.wowhead.com/npc=4832/twilight-lord-kelris#comments:id=2811498) supports the functionality being asked for in this report
> 
> > Well after kelris our other lv 24 hunter had to leave... so that left just the lv 23 warrior, the lv 22 pally and me to kill aku'mai. We lit the first 2, of course at seperate times, and were able to kill those minions. The turtles gave us some trouble, but we were able to do it in the end. The third candel gave us trouble. Those two elite water elements kept using that massive magic spell on us and killed the warrior in 2 hits. I tried to keep up, but I was to slow. **We died quickly the first time, the second time I got hit pretty badly so i had to heal myself at the same time. We died again... but th ethird time we tried, we were able to almsot kill 1 of them, but in the end we all died.** We were disappointed, but I totally forgot that kelris was the one who was supose to drop the staff, not aku'mai. Kelris didn't drop the staff, so that to was disapointing. Well I will be heading back there this afternoon for another room.
> 
> This confirms that the mobs survived through three separate attempts, and because they could not kill the mobs, they could not proceed.
> 
> All braziers must be touched, and all mobs that spawn must be killed, or the door will not open.
> The mobs do not despawn (or if they do, it's a very long timer).
> The braziers do not extinguish.

2007/04/28 (Patch 2.0.12)

Yeah! great proof!
What expansion are we?
Can you refresh my mind?

**Comment by T1ti** [comment]
> > Do you work at blizzard to know it is changed ?
> > I'm active in the vmangos emulator, Classic has been investigated a LOT, it's very clear that classic scripts and database are all exactly the same as vanilla
> 
> No, I don't work there. as it seems you do.
> But I notice things, and I wonder "Why" Blizzard made the "OLD" DB of "Wowhead" disappear and "Why" is doing it all over again (if they already had the data) why do it again ?.
> 
> Unfortunately some people have the brain as a divider for their ears.
> 
> Instead, I use it to reason..

blizzard deosn't make wowhead ? lol
wowhead is a private company

**Comment by eTzmNcbkrng** [comment]
> 
> 
> > This comment from a [Thottbot user during patch 2.0.1.2](https://classic.wowhead.com/npc=4832/twilight-lord-kelris#comments:id=2811498) supports the functionality being asked for in this report
> > > Well after kelris our other lv 24 hunter had to leave... so that left just the lv 23 warrior, the lv 22 pally and me to kill aku'mai. We lit the first 2, of course at seperate times, and were able to kill those minions. The turtles gave us some trouble, but we were able to do it in the end. The third candel gave us trouble. Those two elite water elements kept using that massive magic spell on us and killed the warrior in 2 hits. I tried to keep up, but I was to slow. **We died quickly the first time, the second time I got hit pretty badly so i had to heal myself at the same time. We died again... but th ethird time we tried, we were able to almsot kill 1 of them, but in the end we all died.** We were disappointed, but I totally forgot that kelris was the one who was supose to drop the staff, not aku'mai. Kelris didn't drop the staff, so that to was disapointing. Well I will be heading back there this afternoon for another room.
> > 
> > 
> > This confirms that the mobs survived through three separate attempts, and because they could not kill the mobs, they could not proceed.
> > All braziers must be touched, and all mobs that spawn must be killed, or the door will not open.
> > The mobs do not despawn (or if they do, it's a very long timer).
> > The braziers do not extinguish.
> 
> 2007/04/28 (Patch 2.0.12)
> 
> Yeah! great proof!
> What expansion are we?
> Can you refresh my mind?

The point is, there is nothing, anywhere, that says there was a change to this dungeon that caused a single pull to make the dungeon uncompletable if you fail it.
That's a massive change to the design of the dungeon and it just doesn't exist.

**Comment by ReynoldsCahoon** [comment]
Your temperament is concerning. I am doing my best to provide as many details as I can in regards to this report.

> I've been a WoW player since 2007 and I know how WoW mechanics worked back then.
> 
> To be honest I haven't done this dungeon many times, and all the times I've done it with high level guild PCs helping me, so I've never done Wipe.
> 
> But what I know is that I have seen (in other Dungeons / instances) this mechanic that, (IF) you don't kill the Boss Event you can't go to the next step, (The Last Boss)

These are quotes from you, admitting that you've never seen how this works, yet are claiming authority on how it should work.

**Comment by Stifler82** [comment]
> > > Do you work at blizzard to know it is changed ?
> > > I'm active in the vmangos emulator, Classic has been investigated a LOT, it's very clear that classic scripts and database are all exactly the same as vanilla
> > 
> > 
> > No, I don't work there. as it seems you do.
> > But I notice things, and I wonder "Why" Blizzard made the "OLD" DB of "Wowhead" disappear and "Why" is doing it all over again (if they already had the data) why do it again ?.
> > Unfortunately some people have the brain as a divider for their ears.
> > Instead, I use it to reason..
> 
> blizzard doesn't make wowhead ? lol
> wowhead is a private company

Ah ok, I get it, so they don't cooperate with Blizzard.
They do their own thing, without even consulting with the blizzard right?

So you are basing your thesis that "should" disprove mine on the basis of partnerships and company policies and business techniques, cool..

**Comment by T1ti** [comment]
Blizzard had released many dev blogs and made a whole blizzcon pnnel about Classic's developement, they converted the 1.12 database from a backup and the source code, they didn't make custom values 4 funz

People have tried very hard to prove classic had wrong data because it was too easy, they all got crushed and were proven false, nobody has found 1 inconsistency in classic's database and all the scripts are perfect

**Comment by Stifler82** [comment]
> These are quotes from you, admitting that you've never seen how this works, yet are claiming authority on how it should work.

Yeah and there are also my quotes where I say that I am still undecided about this problem because I am not sure, as (I am NOT SURE) that it is as you say (OR) as I say.

So I'm not saying it's 100% like I say, I'm just saying in my experience usually wow mechanics work like this.

> So I'm still undecided on this issue.
https://github.com/azerothcore/azerothcore-wotlk/issues/5213#issuecomment-817015147

**Comment by Stifler82** [comment]
https://www.toxicgaming.us/wow/vanilla-patch-notes/

https://www.toxicgaming.us/wow/tbc-patch-notes/

https://www.toxicgaming.us/wow/wrath-patch-notes/

if you don't find your proof here, you can't find them in no where

**Comment by ReynoldsCahoon** [comment]
Patch notes do not outline changes to dungeon encounters unless they are actually changed from their original implementation.

> **Patch 1.3.1**
> Characters dying in the instanced portions of Blackfathom Deeps, Scholomance, Maraudon, Onyxia's Lair, and Ragefire Chasm will now correctly receive a corpse marker in the minimap and see the message letting them know that they need to enter the instance before they will be able to resurrect.

> **Patch 1.9.0**
> The Altar of the Deeps in Blackfathom Deeps will now give players the Blessing of the Deeps.

> **Patch 2.2.0**
> Blackfathom Deeps: Several creatures will no longer permanently flee.

> **Patch 2.4.0**
> Female Draenei can no longer become stuck under a root in the tunnels leading to Blackfathom Deeps, Ashenvale.

**Comment by Stifler82** [comment]
this is an example:

- Molten Core
      - Added in-game voice for Ragnaros and Majordomo Executus.
      - Fixed an issue that was causing the first Firelord to stop moving.
      - Garr will now lose his enrage buff when he leaves combat.
      - Majordomo Executus will now make the Flamewaker Healers immune to polymorph at the appropriate time, even after failed attempts.
      - Bringing Flamewaker Healers too far away from Majordomo Executus will now result in the Healers becoming immune to Polymorph.
      - Line of Sight checks removed from many creature abilities in Molten Core. 
      ==========
      **- Sons of Flame now despawn when everyone wipes.**
      **- Ragnaros will reset properly if the raid wipes while submerged.**
      ==========

**Comment by ReynoldsCahoon** [comment]
Below are all references to Blackfathom Deeps in [pre-release patch notes](https://wowpedia.fandom.com/wiki/Patch/0.x).

> **Patch 0.6**
> Dungeons
> - Blackfathom Deeps, a level 20 - 27 dungeon is now opened and itemized in Northern Ashenvale.

> **Patch 0.9**
> Blackfathom Deeps:
> - Ghamoo-ra is now a constant spawn instead of a rare.
> - Miscellaneous polish to associated quests.

> **Patch 0.12**
> Blackfathom Deeps has been moved to the Zoram Strand in Ashenvale forest near the border of Darkshore.

**Comment by ReynoldsCahoon** [comment]
> this is an example:
> PATCH 1.3.1
> 
>   **- Sons of Flame now despawn when everyone wipes.**
>   **- Ragnaros will reset properly if the raid wipes while submerged.**

This is an example of a mechanic from a raid.

**Comment by Stifler82** [comment]
> Blizzard had released many dev blogs and made a whole blizzcon pnnel about Classic's developement, they converted the 1.12 database from a backup and the source code, they didn't make custom values 4 funz
> 
> People have tried very hard to prove classic had wrong data because it was too easy, they all got crushed and were proven false, nobody has found 1 inconsistency in classic's database and all the scripts are perfect


Oh yes?
no inconsistency?
So this MOB (and many others I have found) have all these spells?
https://classic.wowhead.com/npc=1934/tirisfal-farmer#abilities
https://tbc.wowhead.com/npc=1934/tirisfal-farmer#abilities

I don't think so..

**Comment by FrancescoBorzi** [comment]
Ok, let's end this discussion.

My final verdict: **it should be unlocked**.

Reason: it seems the majority of sources (as we as contributors here) are in favour of unlocking it, even if we are not 100% sure. If later we found out this was a wrong decision, we can always revert.

**Comment by necropola** [comment]
On **AzerothCore** the creatures that need to be killed are spawned via `creature_summon_groups` by the 4 game objects `GO_FIRE_OF_AKU_MAI_1..4` with `summonerIds` 21118, 21119, 21120 and 21121.
```SQL
SELECT * FROM `creature_summon_groups` WHERE `summonerId` IN (21118, 21119, 21120, 21121);
+------------+--------------+---------+-------+------------+------------+------------+-------------+------------+------------+
| summonerId | summonerType | groupId | entry | position_x | position_y | position_z | orientation | summonType | summonTime |
+------------+--------------+---------+-------+------------+------------+------------+-------------+------------+------------+
|      21121 |            1 |       1 |  4978 |    -862.43 |   -154.937 |    -25.871 |        0.06 |          4 |      60000 |
|      21121 |            1 |       1 |  4978 |   -775.404 |   -174.132 |    -25.871 |       3.185 |          4 |      60000 |
|      21120 |            1 |       1 |  4823 |   -862.193 |   -174.251 |    -25.871 |       6.182 |          4 |      60000 |
|      21120 |            1 |       1 |  4823 |    -862.43 |   -154.937 |    -25.871 |        0.06 |          4 |      60000 |
|      21120 |            1 |       1 |  4823 |   -775.404 |   -174.132 |    -25.871 |       3.185 |          4 |      60000 |
|      21120 |            1 |       1 |  4823 |   -775.431 |   -153.853 |    -25.871 |       3.207 |          4 |      60000 |
|      21119 |            1 |       1 |  4977 |   -862.193 |   -174.251 |    -25.871 |       6.182 |          4 |      60000 |
|      21119 |            1 |       1 |  4977 |    -862.43 |   -154.937 |    -25.871 |        0.06 |          4 |      60000 |
|      21119 |            1 |       1 |  4977 |   -775.404 |   -174.132 |    -25.871 |       3.185 |          4 |      60000 |
|      21119 |            1 |       1 |  4977 |   -775.431 |   -153.853 |    -25.871 |       3.207 |          4 |      60000 |
|      21118 |            1 |       1 |  4825 |   -862.193 |   -174.251 |    -25.871 |       6.182 |          4 |      60000 |
|      21118 |            1 |       1 |  4825 |    -862.43 |   -154.937 |    -25.871 |        0.06 |          4 |      60000 |
|      21118 |            1 |       1 |  4825 |   -775.404 |   -174.132 |    -25.871 |       3.185 |          4 |      60000 |
|      21118 |            1 |       1 |  4825 |   -775.431 |   -153.853 |    -25.871 |       3.207 |          4 |      60000 |
+------------+--------------+---------+-------+------------+------------+------------+-------------+------------+------------+
14 rows in set (0.000 sec)
```
The corresponding part in the TC-3.3.5 instance script looks like this:
https://github.com/TrinityCore/TrinityCore/blob/6c5b641dd44a8d174d9bb8da36200e81b16f9ae8/src/server/scripts/Kalimdor/BlackfathomDeeps/instance_blackfathom_deeps.cpp#L132-L171

The main difference is that the TC-3.3.5 implementation via script uses `summonType = TEMPSUMMON_CORPSE_TIMED_DESPAWN = 6` and `summonTime = 5min = 300000ms` whereas the AC implementation uses `summonType = TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT= 4` and `summonTime = 1min = 60000ms`. TC-3.3.5 also seems to spawn 10 **Murkshallow Softshell (4977)** instead of just 4 like on AC:

An easy fix would be to adjust the `summonType` and `summonTime` according to TC-3.3.5 and to ignore the different number of Softshells being spawned, i. .e
```SQL
UPDATE  `creature_summon_groups`
SET `summonType`=6, `summonTime`=300000
WHERE `summonerId` IN (21118, 21119, 21120, 21121);
 ```
