### ISSUE TITLE
Darkmoon Faire Prizes are empty [$10]

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5216]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/351

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enUS

##### FACTION

- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic

##### CURRENT BEHAVIOUR:

Type here.

Upon receiving Darkmoon Faire prizes (Minor Darkmoon Prize - https://classic.wowhead.com/item=19298/minor-darkmoon-prize), the package enters my bag. When clicking on it to get a prize, no rewards are given. The bags are empty. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should provide a prize, as per the list here - https://classic.wowhead.com/item=19298/minor-darkmoon-prize

##### STEPS TO REPRODUCE THE PROBLEM:

1. Obtain Darkmoon Faire tickets turning in Blacksmithing items
2. Purchased the Minor Darkmoon Prize from Gelvas Grimegate
3. Opened prize in storage
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by bronzato** [comment]
tested and is working, got two items "Willow branch of the Owll" and "Fortified cloak of the bear" some of them came empty, but all items has a chance to drop, its all about your lucky
