### ISSUE TITLE
Searing Totem attacks neutral target

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5217]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/366

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Searing totem attacks all neutral in range.
It can even attack low level npc like rats/rabbits...

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Searing totem should only attack hostile, or neutral if in combat with the shaman.
https://wowwiki-archive.fandom.com/wiki/Searing_Totem (Thanks mdawx)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a neutral
2. Use Searing totem in range of neutral
3. Searing totem will attack the neutral

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?spell=3599

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Related spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=3606

**Comment by Kitzunu** [comment]
https://github.com/TrinityCore/TrinityCore/commit/c8fdda7f86f5dbe90525636a7291186fe603f61d

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5434
