### ISSUE TITLE
[Raid] [NPC] Lurker from below not spawning

### ISSUE THREAD

**Issue by mikey4901** [azerothcore/azerothcore-wotlk#522]
I'm not entirely sure if this is something new, but i'm gonna report it anyway, so the Lurker from Below in serpentshire cavern doesn't spawn when i fish him up,i still get the achievement and i can hear the sound effect, he just doesn't spawn.

**Comment by ShinDarth** [comment]
please edit your report following the guidelines:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by cshaaa** [comment]
I also have met the problem. And that is my core info:
commit: ac06be129d874
system: Debian 8.6

**Comment by comix1988** [comment]
confirmed by @gtao725

here his report:


SMALL DESCRIPTION:

2nd Boss in Serpent Shrine Cavern does not spawn after fishing him up. The achievement pops but the fight just doesn't start.
EXPECTED BLIZZLIKE BEHAVIOUR:

https://wow.gamepedia.com/The_Lurker_Below
https://www.youtube.com/watch?v=JhWuAKAwTaw
CURRENT BEHAVIOUR:

You fish, then when you successfully fish it up you see "enter combat", then immediately you see "out of combat", the lurker never spawns.
STEPS TO REPRODUCE THE PROBLEM:

    Enter Serpentshrine Cavern.
    Go to the Strange Pool. #2 from this map: http://mywow.wikidot.com/ssc. Stand anywhere on the circular enclosure around the Strange Pool (Glowing Light)
    Start fishing, you might get some random fish catches, that is fine. You know when you fished up boss when you see enter combat.
    Then you will see yourself immediately out of combat without ever seeing the boss spawn.

EXTRA NOTES:
BRANCH(ES):

master
AC HASH/COMMIT:

dfd0343
OPERATING SYSTEM:

Win 7/10/Server 2016
MODULES:

N/A
OTHER CUSTOMIZATIONS:

N/A
