### ISSUE TITLE
npc is absolutely bugged out [$15]

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5224]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/380

Kel'gash the Wicked in ghostlands does not follow you when you line of sight him with a column, just stays still, unsure of the pathing. He also shoots instant chain lightnings WHILE casting lightning bolt. Chain Lightning is definitely a spell with cast time. I am suspicious that this npc is bugged.
1. It should follow me when it cant cast because of line of sight
2. it should not be throwing random chain lightnings whenever he feels like it.

~Sapish

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
![feba3ae4ddbc00e85a3a3d531384c000](https://user-images.githubusercontent.com/39674406/114037578-67867400-9881-11eb-836e-d28dd99c2bf4.jpg)

**Comment by Stifler82** [comment]
https://github.com/chromiecraft/chromiecraft/issues/303
https://github.com/azerothcore/azerothcore-wotlk/issues/5022

**Comment by Mitradis** [comment]
need to check this place with hunter pet, if pet ok then problem in this mob.

**Comment by claudiodfc** [comment]
Confirmed. He only chases player when out of mana, almost if as long he has mana he will try to get to line of sight and wait for a spell even to be available.

**Comment by patou01** [comment]
His chain lightning is instant according to wowhead [database ](https://tbc.wowhead.com/spell=28900/chain-lightning) and [comments](https://tbc.wowhead.com/npc=16358/kelgash-the-wicked#comments:id=2797478).

He should not however throw an instant while casting. Maybe we have some form of spell batching? I will check when I find the time but someone might know better.

Pathing is probably same issue as already linked to this one.

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/8648
Potentionally fixes
