### ISSUE TITLE
Terenthis (Auberdine, Darkshore) gossip text is missing

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5227]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/392

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Terenthis (https://wowgaming.altervista.org/aowow/?npc=3693) has an incorrect gossip text, he says the generic "Greetings, [NAME]". 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

According to user 588010 on Wowhead, he should say: "The corruption of Teldrassil and our surrounding lands really concerns the druids of the Cenarian Circle, and all Night Elves". (Source: https://www.wowhead.com/npc=3693/terenthis#comments)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Talk to NPC Terenthis (NPC id 37097; Entry 3693).

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?npc=3693
https://www.wowhead.com/npc=3693/terenthis#comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Stifler82 why Generic? isn't this 1-19 ?

**Comment by Stifler82** [comment]
> @Stifler82 why Generic? isn't this 1-19 ?

Because beyond the area / npc level, the problem is a generic problem that I have seen in other issues, a problem related to "Gossip" that is also found in other "Level-Range".

**Comment by FrancescoBorzi** [comment]
> > @Stifler82 why Generic? isn't this 1-19 ?
> 
> @FrancescoBorzi
> Because beyond the area / npc level, the problem is a generic problem that I have seen in other issues, a problem related to "Gossip" that is also found in other "Level-Range".

in this case, it would be generic if this bug would be addressed by a generic fix (e.g. a C++ core change) but if we have to fix them one by one with SQL, this seems pretty specific to me.

Anyway, this is just labelling, the most important thing is to fix them :)
