### ISSUE TITLE
Server Crash - Raise Ally Spell.

### ISSUE THREAD

**Issue by MurinaGo** [azerothcore/azerothcore-wotlk#523]
**Description**:
Crashing the server when using a specific order of spells.
**Current behaviour**: Tell us what happens
Crashes the server. ( because you can resurrect a risen (raise ally) player )

EDIT:
Apparently can't be reproduced but the player should NOT be able to get resurrected when it was previously Raised as Ally.

**Expected behaviour**: Tell us what should happen instead
Should not crash the server. ( Player should not be able to get resurrected after the player was 'risen' by Raise ally.
**Steps to reproduce the problem**:

1. Kill a friendly player.
2. Use Raise ally (spell:61999) on that friendly player.
3. Use ANY ressurect such as (spell:50765) on that friendly player.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  
commit/f353f9b5bb08cde4d75b13c1c1c33ae35da971b4
**Operating system**:  
WIN10.
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
can you please add the commit hash ?

**Comment by MurinaGo** [comment]
Updated.

**Comment by Inifield** [comment]
I cannot reproduce the issue, see [here](https://streamable.com/tsfxw) as discussed with MurinaGo, you shouldn't be able to ressurect someone under the effect of Raise Ally

**Comment by talamortis** [comment]
i cant reproduce either, will close unless reported again
