### ISSUE TITLE
Warlock succubus cast is instant if the pet gotta move for casting the spell

### ISSUE THREAD

**Issue by nethw** [azerothcore/azerothcore-wotlk#5231]
## CURRENT BEHAVIOUR:
Warlock succubus has a weird bahaviour.
When you cast Seduction and that the target is out of range or not in LoS, she gotta move.
And when the pet has finally the range and los for casting, the spell does not have a casting time.
Seduction is just instant

## EXPECTED BLIZZLIKE BEHAVIOUR:
The seduction cast must not be instant

## SOURCE:
this is actually easy to reproduce this

## STEPS TO REPRODUCE THE PROBLEM:
1. pick a warlock and try seduction on a monster that can be seduced (or another player)
2. you will notice it works if you are in range/LoS
3. if you arent, the pet will move and cast instantly seduction

## AC HASH/COMMIT:
master

## OPERATING SYSTEM:
ubuntu (docker)

## MODULES:
no

## CUSTOMIZATIONS:
no

**Comment by laasker** [comment]
Can confirm, bugged for me aswell 

commit https://github.com/azerothcore/azerothcore-wotlk/commit/d20a15355c1a

**Comment by laasker** [comment]
Can someone take a look at this?
as pointed out by OP, the cast is only instant if Succubus is out of range or in los, then she walks till she has range/line of sight, and casts Seduction instantly

I recorded 2 videos showing the behavior (without glyph/succubus talent)
https://www.youtube.com/watch?v=CqdvRg88L5w
https://www.youtube.com/watch?v=kjv-sHr_KgQ

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers can anyone check this please?

> Can someone take a look at this? this bug is pretty broken in PvP
