### ISSUE TITLE
Guild Announcements Not Working! :( [$25]

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5232]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/390

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

## CURRENT BEHAVIOUR:

Custom guild announcements using the calendar do not work. (Not talking about the message of the day.) They do not show up at all! Which is super sad because I was trying to get my guild together for a GUILD BANK GIVEAWAY EXTRAVAGANZA!

## EXPECTED BLIZZLIKE BEHAVIOUR:

I would just like the messages to show up in guild chat when they're scheduled to do so! :D

## STEPS TO REPRODUCE THE PROBLEM:

1. make guild announcement for X time using the calendar
2. wait for X time to appear
3. announcement does not appear when it's time

## EXTRA NOTES:

Creating event:
![image](https://user-images.githubusercontent.com/81375770/114282152-897b2480-9a42-11eb-841e-e1966c09168d.png)

Nothing happened:
![image](https://user-images.githubusercontent.com/81375770/114282174-ab74a700-9a42-11eb-834e-fb46c0bd702c.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Mesielecat** [comment]
Which text need to be send it here?

**Comment by UltraNix** [comment]
How it should look like ingame?

**Comment by FrancescoBorzi** [comment]
> How it should look like ingame?

@azerothcore/bug-triaging can anyone please assist @UltraNix

**Comment by temperrr** [comment]
As far as I am aware, it just shows on the calendar and nothing else. It will blink your calendar button if you havent looked at it.. This seems to be the correct behaviour. https://wowpedia.fandom.com/wiki/Calendar doesnt say anything special either

**Comment by Knindzagxg** [comment]
Events or Announcements will remain only into calendar until Cataclysm.
During Cata Pre-Patch, there was first improvement to Guild tab where you could see Guild experience, tasks or events as reminder.

There were no messages during CLC/TBC/WOTLK about those unless you used some addon to filter it out.

**Comment by Knindzagxg** [comment]
Nope, it's working as supposed.
We can maybe maybe module or something to have it into config to enable messages before event as reminder.

**Comment by UltraNix** [comment]
Okay.
