### ISSUE TITLE
Core/Creature: Guards do not attack a non-moving target [$10]

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#524]
**Description**: Neutral guards don't protect players attacked by a player that is not moving.

**Current behaviour**: NEUTRAL guards in booty bay, light's chapel hope etc, won't do anything if you attack another player while not moving yourself. If the guards are near you and standing still, htey won't do anything. But if they move, they will notice it. If you move, they will also notice it.
It has something to do with the guard AI not updating when not moving, and when the player is not moving, something is missing in the AI. (If a guard is moving, he will notice the player though)

It means you can abuse this very easily with ranged attacks, with your pet, or by simply attacking someone in melee without moving.

**Expected behaviour**: The guards should immediately attack you, no matter if they are moving, or standing.

**Steps to reproduce the problem**:

1. Take two characters (alliance and horde)
2. .tele bootybay
3. Go in a place with standing guards, not patrolling.
4. Attack one character without moving.
5. Nothing happens until you move, or until a patrolling guard comes near.

Tested these with @talamortis on my server and on his server.

**Branch(es)**: master (1.0.x+)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
2 people tested it (barbz and talamortis) so we can consider this confirmed

**Comment by BarbzYHOOL** [comment]
Same thing on TC demo server (without mmaps enabled but I bet it's the same behaviour).

**Comment by poszer** [comment]
Interesting

**Comment by poszer** [comment]
Looks like issue with movement. Same with other creatures, if you stand near them without moving they wont attack you, ofc until you move.

**Comment by BarbzYHOOL** [comment]
i had said it already

**Comment by BarbzYHOOL** [comment]
It's not the guardAI, it's just about every NPC in the game

If you don't move, it doesn't update. The NPC does not know you exist. You can start casting a long spell, you can buff up, you can eat, you can drink. You can even unstealth right in front of a boss and he won't move. (unless scripted event)
