### ISSUE TITLE
[Un'goro Crater] Double Rich Thorium Vein Spawn (and more)

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5242]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/401

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Two Rich Thorium Veins are spawned next to  eachother.
GUID 17507 and 18421
![thorium](https://user-images.githubusercontent.com/80769357/114297963-24f8ad80-9ab4-11eb-82d8-de9f74c785d3.jpg)

Small thorium veins (GuiD 317) spawned too deep
![deepspawn](https://user-images.githubusercontent.com/80769357/114301741-62fecd00-9ac6-11eb-9c96-835432d66ded.jpg)

Cluster of three Small thorium Veins Very close with one more on the side. Veins this close should not be all spawned at the same time
GUID 120263, 120770, 286
![triplets](https://user-images.githubusercontent.com/80769357/114301776-7ca01480-9ac6-11eb-9827-a997c8ec601d.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Veins should not spawn inside or close next to each other.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID and see vein spawns

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
I am removing the rich thorium duplicate, moving the small thorium vein spawn in the wrong position and deleting only one of the 3 small thorium vein.
I think that finding 2 small thorium is not so bad.
