### ISSUE TITLE
Pet dash does not increase movement speed. [$35]

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#5250]
related to https://github.com/chromiecraft/chromiecraft/issues/406

The issue is not related properly to the Dash spell but it's related to the Pet behavior, when the Pet is in combat this issue does not happen.

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

Pet's dash ability (https://wowgaming.altervista.org/aowow/?spell=61684) does not increase movement speed by 80%. I can run alongside my pet when it is active, and mobs can outrun him. My pet is a wolf, level 29.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

80% is a considerable speed boost and mobs shouldnt be able to out-run my pet when I am kiting them.

##### STEPS TO REPRODUCE THE PROBLEM:
1. cast pet dash (.aura 61684) and /petattack at a distance from target when the pet is not in combat
2. run along side pet and you'll see for yourself :)

##### EXTRA NOTES:
probably the error is related to PetAI.cpp

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
There should be no issues in theory as it flat applies (SPELL_AURA_MOD_INCREASE_SPEED), value = 80

```
ID - 61684 Dash
=================================================
Description: Increases your pet's movement speed by $s1% for $d.
ToolTip: Increases movement speed by $s1%.
Category = 0, SpellIconID = 959, activeIconID = 0, SpellVisual = (2276,0), SpellPriority = 0
Family SPELLFAMILY_HUNTER, flag [0] 0x00000000 [1] 0x30000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
AttributesEx1: 0x00000020 (SPELL_ATTR1_NOT_BREAK_STEALTH)
=================================================
Skill (Id 203) "Pet - Spider"
    ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00
RecoveryTime: 32000 ms, CategoryRecoveryTime: 0 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
Duration: ID (387)  16000, 0, 16000
Power POWER_FOCUS, Cost 30
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 80
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 31 (SPELL_AURA_MOD_INCREASE_SPEED), value = 80, misc = 0 (0), miscB = 0, periodic = 0
```

So my guess that this is something more pet-related than spell related

**Comment by mnclaras** [comment]
Can this piece of code be related to this?
https://github.com/azerothcore/azerothcore-wotlk/blob/c49f687668a19ff6c7ecf38012d0085d4f6b1475/src/server/game/Entities/Unit/Unit.cpp#L13710-L13732

**Comment by Kitzunu** [comment]
Could be

**Comment by mnclaras** [comment]
> Could be

Maybe it should execute different code when the pet has **SPELL_AURA_MOD_INCREASE_SPEED** aura. For example, here in **void Unit::SetInCombatState(bool PvP, Unit* enemy, uint32 duration)* method, the pet speed is recalculated with force as true:

https://github.com/azerothcore/azerothcore-wotlk/blob/c49f687668a19ff6c7ecf38012d0085d4f6b1475/src/server/game/Entities/Unit/Unit.cpp#L13001-L13006

As I could test, the bug dissapears (and pet speed works well) just when the pet enter in combat (hit for the first time an enemy).

Maybe it deserves a try, but I don't know when *void Unit::SetSpeed(UnitMoveType mtype, float rate, bool forced)* is exactly called.

**Comment by Helias** [comment]
> There should be no issues in theory as it flat applies (SPELL_AURA_MOD_INCREASE_SPEED), value = 80
> 
> ```
> ID - 61684 Dash
> =================================================
> Description: Increases your pet's movement speed by $s1% for $d.
> ToolTip: Increases movement speed by $s1%.
> Category = 0, SpellIconID = 959, activeIconID = 0, SpellVisual = (2276,0), SpellPriority = 0
> Family SPELLFAMILY_HUNTER, flag [0] 0x00000000 [1] 0x30000000 [2] 0x00000000
> 
> SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> =================================================
> AttributesEx1: 0x00000020 (SPELL_ATTR1_NOT_BREAK_STEALTH)
> =================================================
> Skill (Id 203) "Pet - Spider"
>     ReqSkillValue 1, Forward Spell = 0, MinMaxValue (0, 0), CharacterPoints (0, 0)Spell Level = 0, base 0, max 0, maxTarget 0
> 
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange: (Id 1) "Self Only":
>     MinRange = 0, MinRangeFriendly = 0
>     MaxRange = 0, MaxRangeFriendly = 0
> 
> CastingTime (Id 1) = 0,00
> RecoveryTime: 32000 ms, CategoryRecoveryTime: 0 ms
> StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
> Duration: ID (387)  16000, 0, 16000
> Power POWER_FOCUS, Cost 30
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> =================================================
> Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 80
> Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
> Aura Id 31 (SPELL_AURA_MOD_INCREASE_SPEED), value = 80, misc = 0 (0), miscB = 0, periodic = 0
> ```
> 
> So my guess that this is something more pet-related than spell related

yep, as I said in the issue description :grin: , dash is ok, probably when the pet is not in combat it goes slow, so the code that @mnclaras mentioned can be the responsible of this

**Comment by Helias** [comment]
I've found this comment that can affect this behavior

https://github.com/azerothcore/azerothcore-wotlk/blob/c49f687668a19ff6c7ecf38012d0085d4f6b1475/src/server/game/Entities/Unit/Unit.cpp#L13570

**Comment by mnclaras** [comment]
> I've found this comment that can affect this behavior
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/c49f687668a19ff6c7ecf38012d0085d4f6b1475/src/server/game/Entities/Unit/Unit.cpp#L13570

Maybe we have to check if pet has **SPELL_AURA_MOD_INCREASE_SPEED** aura active (I don't know if it's possible to check how much percentage does it have) and then limit to this quantity?
