### ISSUE TITLE
Please do PR again for PR 5144

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5252]
This commit should not modify the original SQL directly
He should submit a new PR to modify dungeon access Requirements table
Otherwise, the commit is invalid,this SQL will not be executed
Because the launch of this commit(https://github.com/azerothcore/azerothcore-wotlk/pull/5144) is too late, most people have implemented 03_ 29_ 01.sql

**Comment by Kitzunu** [comment]
Doesnt matter. It is just for future support of the sql file.

In theory you would need to update every table we have, as I modified all the base files. Or just dump the DB and reapply it.

I can tell you dumping and reapplying will ve much easier. But unless you live in the future you dont need to worry about it
