### ISSUE TITLE
Core/Map: Cannot ressurect in "olo"

### ISSUE THREAD

**Issue by Facira** [azerothcore/azerothcore-wotlk#526]
**Description**: The bug is that after the death on the OLO in FFA mode does not work the resurrection

**Expected behaviour**: A character appears near the angel and a count timer should appear

**Steps to reproduce the problem**:

1. Open worldserver.conf
2. To find there the line GameType
3. And set GameType = 16 FFA
4.Go to the battlefield OLO and die

**Branch(es)**:  master 

**AC hash/commit**: commit/ f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Operating system**:  Debian 8

**Modules**:  No

**Other Customizations**: No

**Comment by ShinDarth** [comment]
please add the commit hash

**Comment by BarbzYHOOL** [comment]
You could fix it by editing the specific spell in the dbc I guess. This is not what we want, but just saying.

**Comment by Facira** [comment]
@BarbzYHOOL, and it is possible more in detail

**Comment by Kitzunu** [comment]
Gonna close this as there is no "OLO" battleground or arena
