### ISSUE TITLE
BG Alterac Valley - impossible to loot NPC or Gameobject

### ISSUE THREAD

**Issue by pagimu** [azerothcore/azerothcore-wotlk#5261]
## CURRENT BEHAVIOUR:
Creature and Gameobject can't be looted.

The LootID is filled in and when I'm set the LootID to 0 then skinning (Wolf) is possible. Because there is nothing to loot.
Creature ID 10981 (Wolf) or 10982 (Vermin) for exampl.
I found an old Trinity "Issue" with exactly the same problem.
https://github.com/TrinityCore/TrinityCore/issues/3515. That Hack works for the Creature

The same problem exist with Gameobject. I can't loot the Items (Gobject 178784). As a GM I can see the name (Mouseover) but nothing happen when I'm click on it. Without GM access I can't see the name and it is unvailable to interact with it.
I had check with a new compiled server without any mods. But the same problem exist. 

## EXPECTED BLIZZLIKE BEHAVIOUR:
It should be possible to loot any NPC for quest Item and also the gameobject after after the mine was conquered.

## STEPS TO REPRODUCE THE PROBLEM:

1. Go BG Alterac Valley
2. Kill any NPC (Creature ID 10981 (Wolf) or 10982 (Vermin)) and try to loot
3. Go to the mine and kill the named NPC.
4. After you conquered the mine, try to loot the supplies  (Gobject 178784)

## AC HASH/COMMIT:
c0bcff9

## OPERATING SYSTEM:
Windows 10 x64 20H2

## MODULES:
None

## CUSTOMIZATIONS:
None

**Comment by FrancescoBorzi** [comment]
@pagimu thanks for your report, however you should not delete the template but instead fill it

![image](https://user-images.githubusercontent.com/75517/114407592-d4af4780-9ba8-11eb-9a74-fd62b391fdbc.png)

**Comment by pagimu** [comment]
I'm sorry. I hope now is ok.

**Comment by FrancescoBorzi** [comment]
yes, thanks @pagimu

**Comment by pagimu** [comment]
The problem still exist with a new compiled Core. 
AzerothCore rev. de23266f04e5+ 2021-05-03 13:14:22 +0200 (master branch) (Win64, Release) (worldserver-daemon) ready...

**Comment by Nyeriah** [comment]
why was this closed? you still can't loot npcs in AV

**Comment by pagimu** [comment]
I'm sorry, Was a mistake.
