### ISSUE TITLE
Quest of Bodley without AllowableClasses Setting

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#5269]
## CURRENT BEHAVIOUR:

All Classes can accept 4 Quest with Same Title "Components of Importance"  and  quests followed with the same problem.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Only 1 Quest should be displayed

## STEPS TO REPRODUCE THE PROBLEM:

1. go  -7533.8 -1215.0 285.4 0
2. q a 8961
3. q c 8961
4. talk with NPC Bodley（visible with GM Mode）
5. with 4 same quest displayed
## AC HASH/COMMIT:

01c830

## OPERATING SYSTEM:

Ubuntu 20

## CUSTOMIZATIONS:

with fix:
```sql
UPDATE `quest_template_addon` SET `AllowableClasses` = 1090 WHERE (`ID` = 8989);
UPDATE `quest_template_addon` SET `AllowableClasses` = 9 WHERE (`ID` = 8990);
UPDATE `quest_template_addon` SET `AllowableClasses` = 144 WHERE (`ID` = 8991);
UPDATE `quest_template_addon` SET `AllowableClasses` = 260 WHERE (`ID` = 8992);
 UPDATE `quest_template_addon` SET `AllowableClasses` = 9 WHERE (`ID` = 8985);
UPDATE `quest_template_addon` SET `AllowableClasses` = 1090 WHERE (`ID` = 8986);
UPDATE `quest_template_addon` SET `AllowableClasses` = 144 WHERE (`ID` = 8987);
UPDATE `quest_template_addon` SET `AllowableClasses` = 260 WHERE (`ID` = 8988);
 UPDATE `quest_template_addon` SET `AllowableClasses` = 129 WHERE (`ID` = 8966);
UPDATE `quest_template_addon` SET `AllowableClasses` = 1280 WHERE (`ID` = 8967);
UPDATE `quest_template_addon` SET `AllowableClasses` = 12 WHERE (`ID` = 8968);
UPDATE `quest_template_addon` SET `AllowableClasses` = 82 WHERE (`ID` = 8969);
UPDATE `quest_template_addon` SET `AllowableClasses` = 129 WHERE (`ID` = 8962);
UPDATE `quest_template_addon` SET `AllowableClasses` = 1280 WHERE (`ID` = 8963);
UPDATE `quest_template_addon` SET `AllowableClasses` = 12 WHERE (`ID` = 8964);
UPDATE `quest_template_addon` SET `AllowableClasses` = 82 WHERE (`ID` = 8965);
```

**Comment by FrancescoBorzi** [comment]
hi @betayi thanks for the report and for the provided fix, can you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it? so we can merge it

**Comment by betayi** [comment]
Is this PR result right ? it shows "Review required" and "Merging is blocked";
and , my PR create procedure is totally as same as the  "open a PR" Docs

**Comment by FrancescoBorzi** [comment]
@betayi hey, thanks a lot for contributing! yes, your PR is correct.

I just left a small suggestion about codestyle, please have a look at it ;)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/4e6fdecaa003fa77dd53b27f1a45b9c4311cc999
