### ISSUE TITLE
Default accounts don't work in a fresh AC install

### ISSUE THREAD

**Issue by Pyromanihack** [azerothcore/azerothcore-wotlk#5271]
## CURRENT BEHAVIOUR:
After a fresh install of AzerothCore on Windows 10 using Docker, everything works except the pre-made accounts test1, test2, test3, etc....

When trying to log in using one of them, I get an error like my pass is wrong and in the worldserver console I get:

![errorTest1](https://user-images.githubusercontent.com/82369562/114558918-77c89580-9c6b-11eb-8a2f-ffc626f41f5a.jpg)

## EXPECTED BLIZZLIKE BEHAVIOUR:
The accounts should work out of the box

## STEPS TO REPRODUCE THE PROBLEM:

1. Install a fresh AzerothCore
2. Try to log in with "test1" password "a"

## EXTRA NOTES:

It works if you create a NEW account and log that one in

## AC HASH/COMMIT:
53ce87d0f7db456231b662d298d1c2cc7add37f9

## OPERATING SYSTEM:
Windows 10 using Docker

## MODULES:

None

## CUSTOMIZATIONS:

None

**Comment by Si1ker** [comment]
After this PR https://github.com/azerothcore/azerothcore-wotlk/pull/4827 you have to manually set the password
**.account set password test1 a a**

**Comment by FrancescoBorzi** [comment]
> After this PR #4827 you have to manually set the password
> **.account set password test1 a a**

has the wiki been updated with this? so people will know about it

**Comment by FrancescoBorzi** [comment]
I think it would be better to make them work out of the box, and  if there is no way to do it, I wonder if it makes more sense to just delete them

cc @UltraNix

**Comment by Kitzunu** [comment]
Personally I lean towards deleting them as it is very simple and fast to create your own

**Comment by FrancescoBorzi** [comment]
> Personally I lean towards deleting them as it is very simple and fast to create your own

ok for me, just don't forget to align all tutorials that we have

**Comment by Kitzunu** [comment]
You mean the one I am rewriting :P Easy ^^

**Comment by FrancescoBorzi** [comment]
> You mean the one I am rewriting :P Easy ^^

there and in any other place where that is possibly mentioned

**Comment by KristianS2314** [comment]
This issue exists when following the "classic setup" guide for Windows. The Getting started with AzerothCore page (azerothcore.org/wiki/getting-started) states "join your own server using the test1 account with password a (yes, one-letter password). This account is already GM" implying the account is created automatically somewhere in the process but it is not.

**Comment by FrancescoBorzi** [comment]
@KristianS2314 please open a new report

**Comment by Kitzunu** [comment]
We dont have default accounts and the wiki has been updated.

**Comment by KristianS2314** [comment]
> @KristianS2314 please open a new report

For what? The Getting started with AzerothCore page has been updated and no longer contains the false info.
