### ISSUE TITLE
[CRASH] in Unit::MeleeDamageBonusTaken

### ISSUE THREAD

**Issue by n4ndo** [azerothcore/azerothcore-wotlk#5272]
## CURRENT BEHAVIOUR:
I'm not sure why, but this is the line in the core: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp#L12595 

## EXPECTED BLIZZLIKE BEHAVIOUR:
 Not to crash

## SOURCE:
N/A

## STEPS TO REPRODUCE THE PROBLEM:

1. Not sure, probably some empty spell o missing Icon?

## EXTRA NOTES:

https://gist.github.com/n4ndo/ac666c9fe5f5fc66dea6d8985b846074
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp#L12595 

## AC HASH/COMMIT:
c05fa1a0a915ab90e8d7731ad0f8f3b2ff2e7731

## OPERATING SYSTEM:
Centos 8x64

## MODULES:

![image](https://user-images.githubusercontent.com/820868/114582347-1d690e00-9c46-11eb-8472-531d80bc9eeb.png)

## CUSTOMIZATIONS:
None

**Comment by Kitzunu** [comment]
How do I reproduce this?

If you haven't already, can you build in RelWithDebInfo or Debug and attach a full crashlog from that?

**Comment by FrancescoBorzi** [comment]
@n4ndo all I can do is a shoot in the dark: https://github.com/azerothcore/azerothcore-wotlk/pull/5303

Please test that PR and let us know if the problem is solved.

https://www.azerothcore.org/wiki/How-to-test-a-PR

**Comment by n4ndo** [comment]
Hello @FrancescoBorzi thank you very much for this, i'm sorry answer until now, but i didnt see any notification on this.

I go to compile with this and tell you the results very soon.

**Comment by FrancescoBorzi** [comment]
thanks @n4ndo . when you are ready, please post your feedback here: https://github.com/azerothcore/azerothcore-wotlk/pull/5303

**Comment by FrancescoBorzi** [comment]
@n4ndo any news?
