### ISSUE TITLE
Herb Node Too Close To Stonetalon Peak Alliance Hub

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5275]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/413
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bruiseweed DBID 3716 - spawn is almost inside the mailbox at the Alliance quest hub in Stonetalon Peak. Not sure if its blizzlike, but I imagine blizzard didnt put herb spawns this far inside the quest hub area.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Unsure. Removing the herb spawn or removing the ability for herbs to spawn inside the alliance quest hub area would seem more blizzlike.

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go object 3716

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by branel** [comment]
For all the information I could find the bruiseweeed location doesn't seem to be completly inaccurate. While it might be currently suffocating inside of a wall on my revision - most reports I could find of herb locations seem to indicate that there is supposed to be one around the hub. [This was posted around 2007.](https://www.wow-professions.com/images/herbalism_maps/stonetalon_mountains_herbalism_map.jpg) [I know its not reliable but this is how it is in classic.](https://classic.wowhead.com/object=1622/bruiseweed)
