### ISSUE TITLE
Deviate Guardian mob in Weiling Caverns wrong mechanic

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5276]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/418

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Deviate Guardian mobs in Weiling Caverns run away when low HP just like humanoid mobs. They should be the Beast type without run at low HP mechanic.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The only mechanic the Deviate Guardian mob should have is to cry for help for other nearby mobs when at low HP. They should not run away.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Waiting Caverns
2. Attach Deviate Guardian until it's at low HP
3. Watch it run in fear like a humanoid.
4.

##### EXTRA NOTES:

![WoWScrnShot_041321_190310](https://user-images.githubusercontent.com/80955822/114609254-e3782600-9c9e-11eb-8baf-ce34e197bb93.jpg)

![image](https://user-images.githubusercontent.com/81375770/114610705-82515200-9ca0-11eb-8250-bca283ed5ab4.png)

source: https://wowpedia.fandom.com/wiki/Wailing_Caverns
> Be warned - the raptors will call for help when almost dead

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
The range for their "call to help" is.. h u g e.

https://youtu.be/xeW3Nl9akYA?t=1430
In this video, another mob is called from around 40 yards, it comes from the top-mid part of the screen

Fix = LINK
