### ISSUE TITLE
Buggy escort NPC and spawned mobs during Supplies to Auberdine quest

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5295]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/395

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

1. NPC Feero Ironhand DB ID 32783 is the NPC you escort during the [quest](https://wotlkdb.com/?quest=976).
He behaved all right on first wave (https://youtu.be/nMTC_x942FY?t=149) but ignored second (https://youtu.be/nMTC_x942FY?t=292) and third wave (https://youtu.be/nMTC_x942FY?t=461).

2. About halfway through the escort, after second wave, he started walking underground (https://youtu.be/nMTC_x942FY?t=310)
 and then levitating (https://youtu.be/nMTC_x942FY?t=336)
##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. Escort NPC should help fighting ambushers. 
2. NPC shouldn't be levitating and going underground. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 32783
2. add and complete prerequisite quest 973
3. take escort quest from Feero Ironhand

##### EXTRA NOTES:

https://www.youtube.com/watch?v=nMTC_x942FY

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Pathing issue is here https://github.com/azerothcore/azerothcore-wotlk/issues/4904

But I will leave this issue up for the wave thing

**Comment by mdawx** [comment]
> Pathing issue is here #4904
> 
> But I will leave this issue up for the wave thing

I should have checked better. At least I recorded it :)

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Stifler82** [comment]
I just checked the quest and it works, it no longer has the bug.
So I close.

**Comment by Kitzunu** [comment]
@Stifler82 pls check DM on discord
