### ISSUE TITLE
Double Bruiseweed Spawn in Barrens

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5299]
## CURRENT BEHAVIOUR:

A pair of Bruiseweed herbs (https://wowgaming.altervista.org/aowow/?object=3730) overlap in the southern Barrens:
Guid 3703 -> Guid 14486, distance 0.48 units.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Herbs should be spaced more evenly, and not overlapping.

## SOURCE:

![WoWScrnShot_041521_234626](https://user-images.githubusercontent.com/81782124/114887068-41477200-9e47-11eb-83be-e63c11a0f352.jpg)

## STEPS TO REPRODUCE THE PROBLEM:

1. .go o 3703
2. Observe.

## AC HASH/COMMIT:

rev. 33aeadf8 2021-04-15 14:16:39 +0200

## OPERATING SYSTEM:

Ubuntu 20.10

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by Hacaw** [comment]
This is interesting. 
I tried to reproduce it on d6490a06. Even though I can teleport to both of them, I am only able to loot one.

**Comment by JamesGent** [comment]
![Desktop 12-09-2021 17-55-24-354](https://user-images.githubusercontent.com/61194190/132996135-dd8f75b2-3a8a-441d-8adf-1bd0ed7b1d6d.png)

GUID 3703 doesn't exist anymore, is this safe to close?
