### ISSUE TITLE
where is the directory "Custom"

### ISSUE THREAD

**Issue by hero2880** [azerothcore/azerothcore-wotlk#53]
The directory "Custom" in souce is lost,if i want to add a new scripit,where to put?
##

**Comment by rynnokung** [comment]
Its in src\server\scripts\custom if thats what you are looking for.

**Comment by Yehonal** [comment]
This folder has been removed since we're publishing a guide on how to add
custom modules to create real "plugins" for AzerothCore , instead of modify
project sources.

It will be available very soon

P.S. would be nice if you use forum for this kind of discussion next time

2016-08-11 11:20 GMT+02:00 rynnokung <notifications@github.com>:

**Comment by Yehonal** [comment]
I've restored the custom folder with a more flexible approach 

https://github.com/azerothcore/azerothcore-wotlk/tree/master/modules/acore/scripts-wotlk/Custom

however i'm finishing to write the guide for module creation, if you are interested you can try it and leave me a feedback:

https://docs.google.com/document/d/1wkBJq44ow99CgHKl3wFYj8tUbqbpaNjg-fND0mdTtVQ/edit#heading=h.g0wkutglgdzh

**Comment by hero2880** [comment]
Leave a comment

**Comment by hero2880** [comment]
I will try the way which you provided to increase custom_ scripts; Also yesterday, compiling a V1 version, many mistakes: mainly CORE logo (a few large characters,in main.cpp...) related to malformed, and pathrandomgenerator.cpp errors. Can not generate the worldserver.

I am now using version before the big change,After Fixed cmakelist.txt and main.cpp file, the compiler success.

DOC you provided above I can not open, can you provide a MEGA network disk file?

**Comment by Yehonal** [comment]
@hero2880 please use latest version from master,  you can create a custom script in custom folder or a module. I suggest you latest one
