### ISSUE TITLE
[.wp show info #pathid] can crash the server

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#530]
**Description**: Typing this command can crash the server.

**Current behaviour**: If you type this command without selecting a target, it will crash.

**Expected behaviour**: It should warn the GM that no creature is selected (this happens when you type only ".wp show info" without the pathID).

**Steps to reproduce the problem**:

1. Log on your character and select nothing
2. .wp show info 131660
131660 is a valid path, but you can type anything, it will crash
3.  crash

**Branch(es)**: master

**AC hash/commit**:  1521451529c1cae72a19248068da041c5bb2efbf

**Operating system**:  debian 8

**Modules**:  Anticheat

**Comment by Facira** [comment]
![image](https://user-images.githubusercontent.com/30197485/28822198-6127a314-76c9-11e7-82d8-da66b5bad8de.png)
is working

**Comment by Erotes** [comment]
@Facira first of all, select nothing, unfocus from your target, type .wp show info 131660 and it should reproduce the crash.

**Comment by Inifield** [comment]
Confirmed, will submit fix soon
