### ISSUE TITLE
Gathering: Herb: Bruiseweed node inside Northwatch Hold tower near Ratchet, Barrens

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5302]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/427

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bruiseweed located indoors, inside Northwatch Hold tower

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herb nodes are not typically found inside buildings, most likely does not belong here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go o 3538
2.  Find bruiseweed on the ramp heading upstairs
- 3538 (Entry: 1622) - [Bruiseweed X:-2087.0 Y:-3654.0 Z:68.425003 MapId: 1]

##### EXTRA NOTES:

Screenshot:

![image](https://user-images.githubusercontent.com/7005291/114935462-836ab680-9e3b-11eb-9b06-e8609d2025c6.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by alchem1ster** [comment]
```sql
DELETE FROM 
  `gameobject` 
WHERE 
  `id` = 1622 
  AND `position_x` = -2087 
  AND `position_y` = -3654 
  AND `position_z` = 68.425;

```
