### ISSUE TITLE
Feature:  acore.sh command to import the SQL version of DBC

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#5316]
**Describe your feature request or suggestion in detail**
 
We need to provide a command to download [this sql](https://github.com/wowgaming/client-data/releases/tag/dbc_sql_v1) file automatically, such as we already do for the client map. The SQL must be downloaded inside the data/sql folder so that can be processed by the db_assembler.

Moreover, we need to integrate this command with the pipeline to download and import the SQL before applying the updates.
It is needed to check that our updates do not run any `INSERT INTO` query that can be in conflict with the already existing data.

**Additional context**

Would be better to wait for [this PR](https://github.com/azerothcore/azerothcore-wotlk/pull/4488), to write that command in typescript

**Comment by Yehonal** [comment]
IMPORTANT NOTE: Somehow this SQL should be imported even before the spell_dbc base data. Otherwise, it will overwrite the existing data on AC that should have the priority instead

**Comment by Yehonal** [comment]
We do not need this feature anymore. [This tool](https://github.com/wowgaming/node-dbc-reader) will be used to provide a safe way to manually DBC to SQL by also keeping schema in sync with the AC. 
A proper documentation on AC wiki will be provided

**Comment by Kitzunu** [comment]
I will close this as you say it is not needed anymore. If I'm wrong, just reopen
