### ISSUE TITLE
Core/Command: npc set movetype

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#532]
**Description**: Improving the command for easier development

**Current behaviour**: If you type this command without selecting a target, but using the guid, it will require a reboot, while if you do it selecting a target, it will not require a reboot because it respawns/reset the NPC.
Also, the explanation is confusing on the NODEL thing.

**Expected behaviour**: It should work the same way with or without target selected and the description should mention to write "NODEL" but actually it says to write "[NODEL]" which is confusing.

**Steps to reproduce the problem**:

1. .go creature 13578
2.  DO NOT SELECT THE WORG AND TYPE : .npc set movetype 13578 stay NODEL
3.  the worg continues his path but if you reboot he will stay in place (to revert you type .npc set movetype 13578 way NODEL)

4. Now select the worg, and type : .npc set movetype stay NODEL
5. Go to the small house, the worg will be here standing still

**Branch(es)**: master

**AC hash/commit**:  1521451529c1cae72a19248068da041c5bb2efbf

**Operating system**:  debian 8

**Modules**:  Anticheat

**Comment by Hacaw** [comment]
Hi @BarbzYHOOL & @FrancescoBorzi it's been 3 years since this issue has been opened, should this still this be opened ?

**Comment by Kitzunu** [comment]
Going on Hacaws track and close it as it has been stale for 4 years now without any reports from anyone else with the same issue.

If anyone comes across the issue, comment or make a new issue =)
