### ISSUE TITLE
[Quest] Amongst the Ruins

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5323]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/430

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The quest [Amongst the Ruins](https://wowgaming.altervista.org/aowow/?quest=6921) requires to loot the fathom core in the water below the Moonshrine Ruins within Blackfathom Deeps. When looting the first time, it spawns a mini-boss [Baron Aquanis](https://wowgaming.altervista.org/aowow/?npc=12876). However, the core does not respawn, limiting the completion of the quest to one member of the group only.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The core should respawn shortly when looted, allowing the group to complete the quest. However, the boss only spawns once independet on the number of interactions with the core.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept the quest as Horde at the Zoram Strand
2. Go to Blackfathom Deeps to the Moonshrine Ruins, search the waters for the interactable core
3. Loot it, kill the miniboss, wait for the respawn which does not happen within reasonable time (waited for ~15 mins)

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Stifler82** [comment]
Fixed!
-
https://user-images.githubusercontent.com/1884642/119543853-065f2500-bd89-11eb-8e3a-2acd9f359309.mp4
