### ISSUE TITLE
Deviate creeper disapearing in the air right after pulling it.

### ISSUE THREAD

**Issue by Ziedge** [azerothcore/azerothcore-wotlk#5327]
## CURRENT BEHAVIOUR:

A deviate creeper disapearing in the air right after pulling him.
https://wowgaming.altervista.org/aowow/?npc=3632

## EXPECTED BLIZZLIKE BEHAVIOUR:

The mob should aggro the player, attack him and stay in front of the player.

## SOURCE:

https://user-images.githubusercontent.com/82708448/115115217-7c56bc00-9f93-11eb-8b61-4d76902fe1e3.mp4

## STEPS TO REPRODUCE THE PROBLEM:

.gm on
.go xyz -714 -2046 65
.gm off
pull Deviate Creeper in front of you and see him fly vertically

## AC HASH/COMMIT:

8c8bc61b40b3dae847261a0e4021160daa90deb8

## OPERATING SYSTEM:

Windows 10

**Comment by Sedatyf** [comment]
I reproduced this bug with him on a local world server
