### ISSUE TITLE
Sharing Horde quests to the Alliance

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5328]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/431

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Both of these quests may be shared with an Alliance player but the quest givers are Horde characters.
https://wowgaming.altervista.org/aowow/?quest=1014
https://wowgaming.altervista.org/aowow/?quest=1098

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Alliance players are never supposed to be able to hold these Horde quests.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a Horde character get the quests.
2. Queue into a random dungeon group.
3. Share quest with some Alliance players.

##### EXTRA NOTES:

These two quests seems to be "faction neutral" unlike https://wowgaming.altervista.org/aowow/?quest=1013
It would only happen whenever there is crossfaction enabled.
Quests are provided by these two Horde NPC.
https://wowgaming.altervista.org/aowow/?npc=1938
https://wowgaming.altervista.org/aowow/?npc=1952

![WoWScrnShot_041721_084605](https://user-images.githubusercontent.com/22718174/115113938-c66f7b80-9f5a-11eb-809d-cd32c97a1728.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
```sql
UPDATE `quest_template` SET `AllowableRaces` = 690 WHERE `id` IN (1014,1098);
```
