### ISSUE TITLE
Feature: implement send mass mail

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#533]
**Description**: Adding these two commands could help.

**Cheat casttime can be taken from TC :**
--------------------------------------------------
cheat casttime | 2 | Syntax: .cheat casttime [on/off] Enables or disables your character's spell cast times.

You can spam your spells with that.

**Send mass mail/message is a new subcommand :**
----------------------------------------------
Just add an "all" option to these commands : 
send items
send mail (but it might be a problem with the security level)
send message
send money

Or create a new command like this : .send mass items "#subject" "#text" itemid1[:count1] itemid2[:count2]

**Comment by Demonid** [comment]
Mangos has Send Mass Mail if anyone is interested.

**Comment by BarbzYHOOL** [comment]
@Viste :P

**Comment by Viste** [comment]
@BarbzYHOOL when have some more time out of work open PR for it all is done but don't have time for it
Now all free time goes to wife and  renovation of house, excuse me guys

**Comment by BarbzYHOOL** [comment]
no problem!

**Comment by Si1ker** [comment]
https://github.com/mangostwo/server/blob/master/src/game/ChatCommands/MailCommands.cpp#L104

https://github.com/mangostwo/server/blob/982efdd77b42e5d08a23c204f6a9c47a07ab3940/src/game/WorldHandlers/MassMailMgr.cpp

https://github.com/mangostwo/server/blob/ffc60e5d0aaf5d84161ced512ec00fcd233cf7da/src/game/WorldHandlers/MassMailMgr.h

https://github.com/mangostwo/server/blob/ffc60e5d0aaf5d84161ced512ec00fcd233cf7da/src/game/WorldHandlers/Mail.h#L30

**Comment by Nyeriah** [comment]
It might be just me but maybe a send mail all is not a very good idea? Some databases got over 50k characters, would it be convenient to send 50k mails?

**Comment by Kitzunu** [comment]
We have a system good enough for this imo
