### ISSUE TITLE
[Quest] Raene's Cleansing

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5339]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/432

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Iron Pommel required to complete the quest (https://classic.wowhead.com/quest=1027/raenes-cleansing) drops from the Rotting Slimes (https://classic.wowhead.com/npc=3928/rotting-slime) as well as the small chest that they drop upon death.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Iron Pommel should only be found in the chest that appears on the corpse of a rotten slime. It is not a drop from a rotten slime. 

See: https://classic.wowhead.com/quest=1027/raenes-cleansing#comments:id=1219

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Raene Wolfrunner in Astranaar (GUID 32646)
2. Accept https://classic.wowhead.com/quest=1024/raenes-cleansing (Requires the player to complete https://classic.wowhead.com/quest=991/raenes-cleansing beforehand)
3. Progress through the questline until you have to get the Iron Pommel
4. Kill a slime, now you are able to pick it up either from the corpse of the slime or the chest. It should only be lootable from the chest the slime drops on the ground upon death

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Stifler82** [comment]
Fixed!
-
according with Wowhead loot page, i removed this loot from [Rotting Slime](https://wowgaming.altervista.org/aowow/?npc=3928) .

![image](https://user-images.githubusercontent.com/1884642/119550705-a1a7c880-bd90-11eb-81e0-611aee5aa568.png)
