### ISSUE TITLE
[Database] Floating Corpse DK Starting/Scarlet Infantryman missing weapons

### ISSUE THREAD

**Issue by Kizarr** [azerothcore/azerothcore-wotlk#534]
**Description**:
Missing weapons scarlet crusador and floating corpse patchfix.

**Current behaviour**: Tell us what happens
Floating Corpse DK Starting area

**Expected behaviour**: Tell us what should happen instead
There should be know floating corpse at the death knight starting area.

**Patchfix**:
Issue link and patchfix: https://github.com/TrinityCore/TrinityCore/issues/6631

Patchfix: https://github.com/Aokromes/TrinityCore/commit/662d1e17e6424cf76d725dcc3ba63c4173e9f8e6

Patchfix: https://github.com/TrinityCore/TrinityCore/commit/39b20b4431a1a67446e9cc4c2221fd42cc907291

Issue and patchfix:
https://github.com/TrinityCore/TrinityCore/issues/18508

Patchfix:
Location: In creature_equip_template database

-- Scarlet Infantryman
UPDATE creature_equip_template SET ItemID1= 38721, ItemID2= 12932 WHERE CreatureID= 28609;
UPDATE creature_equip_template SET ItemID1= 38723, ItemID2= 12932 WHERE CreatureID= 28896;

**Steps to reproduce the problem**:

1.  Create a deathknight.
2.  Login the character
3.  By the stairs there is a floating corpse.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  
 f353f9b
**Operating system**: 
Debian Linux

**Modules**:  Are you using modules? if yes, list them
VASAutobalance Module, Anticheat Module, Premium account, Transmog Module, Duel Reset and RandomEnchants Module.

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
N/A

**Comment by ShinDarth** [comment]
please open PRs with those fixes so they can be tested and then merged

**Comment by Kizarr** [comment]
@ShinDarth Sorry about that I have created a pull request.

**Comment by StygianTheBest** [comment]
I don't see this Pull Request

**Comment by ShinDarth** [comment]
however, PR or not, the bug report should stay open until the fix has been merged to the master branch.

**Comment by Yehonal** [comment]
I've reopened and fixed the PR aswell: https://github.com/azerothcore/azerothcore-wotlk/pull/539

i'll test it today

**Comment by Inifield** [comment]
fixed in https://github.com/azerothcore/azerothcore-wotlk/commit/d388a36cf177a9936beb98151463e7b671ca6400
