### ISSUE TITLE
Master Looter skinning/herbalism/mining cant loot

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5340]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/434

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

While in Master Looter Group the non "Master Looter" can't skin, herb or mine, maybe even more. I asume its any kind of "loot" not looted by the master looter. When you press the skinned loot, the window closes and no leather is taken. Same for herbalism and mining.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I dont know, i assume the skinner, miner and herbalism should get the loot from the object.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a group
2. Set loot as Master Looter
3. Herb, skin or mine as non Groupleader and try to "loot" it.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mpfans** [comment]
@UltraNix  This is the legacy bug

**Comment by UltraNix** [comment]
@mpfans @Stifler82 Fixed in #5389.
