### ISSUE TITLE
Makrura Clacker bugged

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5341]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/435

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bugged Makrura Clacker at 59.01, 81.59. Hes spinning around with perma evade.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal Mob behavior. :-D

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to 59.01, 81.59. 

##### EXTRA NOTES:

Maybe its after restart fixed but it will bug again, i saw "him" multiple times.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
why Generic?  Makrura Clacker is spawned only in Durotar: https://classic.wowhead.com/npc=3103/makrura-clacker

shouldn't it be 1-19?

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Stifler82** [comment]
@FrancescoBorzi 
This is a Pathfinding issue the same of https://github.com/azerothcore/azerothcore-wotlk/issues/5748

**Comment by UltraNix** [comment]
Already fixed.
