### ISSUE TITLE
Plate BOA heirloom items are RED to level 1 gnome warrior

### ISSUE THREAD

**Issue by electricmessiah** [azerothcore/azerothcore-wotlk#535]
**Description**:
Plate BOA heirloom items are RED to level 1 gnome warrior

**Current behaviour**: Tell us what happens
I created a vendor and gave them all of the heirlooms. When my L1 Gnome warrior goes to buy, the plate items listed are red, but they can still be purchased and worn.

**Expected behaviour**: Tell us what should happen instead
Obviously, they shouldn't be red.

**Steps to reproduce the problem**:

1. Create a vendor creature 
2. Give them heirloom items
3. Attempt to buy on L1 Gnome warrior

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master

**Comment by electricmessiah** [comment]
Not even an explanation? What kind of development community is this?

**Comment by talamortis** [comment]
well it's a dumb thing tbh u shouldn't be able to buy the armor from a level 1 in the 1st place as u need level 80 badges for them

**Comment by electricmessiah** [comment]
BOA Plate items were created for L1 characters. If I send my L1 Warrior the BOA 2H Axe they can use it, so heirlooms shouldn't be colored red based on normal weapon requirements that do not apply to heirloom weapons and armor. The only thing that would make sense are class-specific requirements, but Gnome warriors apparently can't wear plate heirlooms and that's incorrect. It's a TINY bug.

**Comment by talamortis** [comment]
when the plate mail is brought by the level 80 and then send to a level 1 warrior the BOA instant gets turned to mail until the warrior reaches level 40 she  he acquired plate spell

**Comment by electricmessiah** [comment]
that makes sense and is a much better answer. i forgot about that detail.
