### ISSUE TITLE
Book has incorrectly formatted HTML text

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5352]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/302

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When reading the book Lament of the Highborne, the text is displayed as HTML and not human readable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Book should be legible by a human.

##### STEPS TO REPRODUCE THE PROBLEM:

~~`.additem 30632`~~ Edit: False report, my bad :(

Be at least Level 15
Go to [Sylvanas](https://wotlkdb.com/?npc=10181): `.go cr 32039`
Accept the first [quest](https://wotlkdb.com/?quest=9175) from the [item](https://wotlkdb.com/?item=22597) that starts the chain: `.additem 22597`
Turnin the quest: `.quest reward 9175`
Add the followup [quest](https://wotlkdb.com/?quest=9180): `.quest add 9180`
Turnin the quest at Sylvanas
Talk to [Ambassador Sunsorrow](https://wotlkdb.com/?npc=16287) (standing to Sylvanas' Right) to get the book.

Here is a video of me reproducing the bug on a local install showing that book obtained from GM command is fine, but the book from the quest is broken.
https://www.youtube.com/watch?v=XyUjCNjXFMY

##### EXTRA NOTES:

Looks like it might have been a straight copy-pasta from Wowhead without checking how it displayed in game.
Might be worth checking the database for other books that have HTML tags in them, I have no idea what the SQL for that might be though.

![image](https://user-images.githubusercontent.com/26512802/112716634-5c137e80-8f4c-11eb-8566-c0e591697ef5.png)
![image](https://user-images.githubusercontent.com/26512802/112716639-62a1f600-8f4c-11eb-9f90-a102e52c42b7.png)
![image](https://user-images.githubusercontent.com/26512802/112716642-66357d00-8f4c-11eb-9181-be3729506262.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Relevant comment
https://github.com/chromiecraft/chromiecraft/issues/302#issuecomment-819388061

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/115203251-90b3c980-a0f7-11eb-8452-44f4367fece6.png)

Works on 0528e0b4855331572d65237198e1510444fe2cec and Chromie is 1 month old... 

Also, it should be able to display HTML, as it does above.

**Comment by Stifler82** [comment]
Have you read the comments here: https://github.com/chromiecraft/chromiecraft/issues/302 ?

**Comment by Kitzunu** [comment]
Edit: This was after I got it by command, but I can't figure out what requirements I need for the NPC to give it to me as the reproduce steps above don't work

**Comment by Stifler82** [comment]
with .add ti work.
instead if you get it through the quest, it doesn't works..

**Comment by Kitzunu** [comment]
> but I can't figure out what requirements I need for the NPC to give it to me as the reproduce steps above don't work

**Comment by Branel** [comment]
You have to be a Blood Elf to receive this book, a crucial step that was not included. I was able to reproduce
