### ISSUE TITLE
[NPC] Pathing of Blackwater Deckhand

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5353]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/437

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Inbetween the Zones Arathi Highland [33.82|92.97] or Wetlands [40.97|08.07] a NPC named "Blackwater Deckhand" bugs out of the cliffs on the side of Arathi Highland. Then procedes to float over the water and bug into the cliffs in Wetlands.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC "Blackwater Deckhand" should be stationary or at least moving around in Faldir's Cove in Arathi Highlands.

https://wowpedia.fandom.com/wiki/Blackwater_Deckhand

https://classicdb.ch/?npc=2636#comments

https://de.wowhead.com/npc=2636/deckmatrose-der-schwarzmeerr%C3%A4uber#english-comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Mentioned Spot in the Arathi Highlands at [33.82|92.97].
2. Wait for the floating NPC "Blackwater Deckhand".
3. Be amazed.
4. Wonder where the NPC continues with his journey.

##### EXTRA NOTES:

https://wowpedia.fandom.com/wiki/Blackwater_Deckhand

https://classicdb.ch/?npc=2636#comments

https://de.wowhead.com/npc=2636/deckmatrose-der-schwarzmeerr%C3%A4uber#english-comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
according to wowhead [Blackwater Deckhand](https://tbc.wowhead.com/npc=2636/blackwater-deckhand) is only spawned in Arathi Highlands so this is 30-39 and not Generic

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Azcobu** [comment]
See https://github.com/azerothcore/azerothcore-wotlk/pull/5758 which probably resolves this too.

**Comment by Stifler82** [comment]
I cannot reproduce it, probably it was fixed with some "Generic Fix" about Pathfinding.
So i Close
