### ISSUE TITLE
Copper Ore Node is impossible to mine

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5354]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/440

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

This Copper Ore Node is impossible to obtain on its angle.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Shouldn't spawn here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find this copper node and try to mine it
2. 
3. 
4.

##### EXTRA NOTES:

Type here.
![WoWScrnShot_041821_122335](https://user-images.githubusercontent.com/3758326/115156430-83d49e80-a041-11eb-88bd-e22f63760a78.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Hacki95 are you planning to work on this? if not, please unassign yourself

**Comment by Hacki95** [comment]
I get all ore issues assigned to me, I am still working on it but it has a lower prio then the MC issues. We can talk on discord if you need an ETA etc.
