### ISSUE TITLE
[NPC] Skinning of Serpentbloom Snake

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5355]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/441

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ X ] enUS
- [ ] other (specify)

##### FACTION

- [ X ] Alliance
- [ X ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ X ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Serpentbloom Snakes which spawn after picking Serpentblooms also have a low chance of dropping Light Hides, Medium Leather, and Red Whelp Scales.

https://classic.wowhead.com/npc=3680/serpentbloom-snake#comments

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This mob should only be dropping Ruined Leather Scraps and Light Leather from skinning.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Accept the Quest Serpentbloom (https://classic.wowhead.com/quest=962/serpentbloom).
2. Go to the Wailing Caverns Predungeon or Dungeon.
3. Pick Serpentbloom (https://www.wowhead.com/object=13874/serpentbloom)
4. Serpentbloom Snake spawns (https://www.wowhead.com/spell=6195/serpentbloom-snake).
5. Skin Serpentbloom Snake (https://www.wowhead.com/npc=3680/serpentbloom-snake).

##### EXTRA NOTES:

Similiar Bug to the issue with the Mangy Nightsabers and Young Thistle Boars (https://github.com/chromiecraft/chromiecraft/issues/368).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Stifler82 are you still planning to work on this?

**Comment by Stifler82** [comment]
pleafter some research I reconsidered this and I think the loot is probably correct the way it is, unless someone can prove that it should be different on 3.3.5
