### ISSUE TITLE
A Vengeful Fate Quest flagged as "both" factions, should just be horde.

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5356]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/442

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

In a dungeon with horde, I was able to have the quest A Vengeful Fate shared with me. I even received the quest item for it. The quest turn in is for an npc in Thunderbluff. 

https://wotlkdb.com/?quest=1102 (I know its not chromie, but wotlkdb also lists this as "both" factions, which I think is incorrect)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Alliance should not be able to receive this quest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be alliance
2. Have a member of the horde share this quest with you (chromie specific -- but I wonder if an alliance person could get this quest from the quest giver if they corpse ran to them?)
3. Accept quest

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by alchem1ster** [comment]
```
UPDATE quest_template
SET 
    allowableraces = 690
WHERE
    (id = 1102) AND (logtitle = "A Vengeful Fate");
```
But I'm not exactly sure that's right =)

**Comment by Kitzunu** [comment]
The preferred way would to just use ID and not logtitle

**Comment by Kitzunu** [comment]
Feel free to open a PR =)

**Comment by FrancescoBorzi** [comment]
@alchem1ster https://www.azerothcore.org/wiki/How-to-create-a-PR

**Comment by Kitzunu** [comment]
Just added it to my already open PR
