### ISSUE TITLE
Realm First Achievements being awarded multiple times [$25]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#5357]
## CURRENT BEHAVIOUR:

Realm First! Achievements are being awarded multiple times, including:

Realm First! Level 80
Realm First! Class
Realm First! Race
Realm First! Profession
Realm First! Raid Kills

See images:

https://imgur.com/sKkY3Tr <- Character 1, Vox - getting 3 RF achievements: Level 80, Level 80 Human, Level 80 Rogue

https://imgur.com/2aEMo0m <- Character 2, Othervox, also getting the same achievements even though it was leveled after.

https://imgur.com/O4lcPuW <- Character 2, Othervox waiting outside of Naxx - Character 1 receives the realm first here (see chat)

https://imgur.com/gdHHCiU <- Character 1, Vox, waiting outside of Naxx - Character 2 receives the realm first here even though Character 1 just got it 5 minutes ago.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Realm First! achievements should only be rewarded once.

## STEPS TO REPRODUCE THE PROBLEM:

1. Create a character, any race or class
2. .level 79 (to hit 80)
3. Create a new character of the same race/class, or dual box another account
4. Repeat 1 & 2

You will receive the Realm First Level 80, Race and Class achievements as you did on the first character.

Optional for further testing:

.learn all recipes blacksmithing/jewelcrafting etc on two separate characters - you will receive the same grand master profession realm first.  Obviously, do it on one character before doing it on the other.

Go into a raid on two separate characters in two separate instances, kill any following bosses to achieve the Realm First achievement:

Naxx: Kel'Thuzad 25
EoE: Malygos 25
OS: Sartharion 25
Uld: Yogg0 & Algalon 25
ToC: Anub'arak 25HC w/ 50 attempts remaining
ICC: Lich King 25HC

Again:  Do this on one character before doing it on the other.

## AC HASH/COMMIT:

9997fa792404

## OPERATING SYSTEM:

Win10

**Comment by Voxstrasza** [comment]
@Kitzunu fix it

**Comment by Voxstrasza** [comment]
[bounty](https://www.bountysource.com/issues/97909158-realm-first-achievements-being-awarded-multiple-times)

**Comment by UltraNix** [comment]
Check with normal (not gm) account - it should be okay. Realm first are saved only for player accounts.

**Comment by UltraNix** [comment]
@Voxstrasza Because GMs might achiev some realm firsts by command and should not block these for "normal" players - that's why realm firsts achieved by GMs are not saved. If player do it, then realm first is not available to anybody (including GMs).
