### ISSUE TITLE
GM's Command ".add" needs a little fix to the code

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5361]
## Everything is explained here:
**In the video I show the difference in using the command between TC and AC**
P.S.
active audio

https://user-images.githubusercontent.com/1884642/115255872-a12f6880-a126-11eb-818a-ee490c1ebe43.mp4

**Comment by Stifler82** [comment]
**It should works like works on TC!**
-

**Comment by Stifler82** [comment]
@FrancescoBorzi @Helias

**Comment by FrancescoBorzi** [comment]
we should look into this, nice report. However: you are using a TC from 2014 which is **7 years old**.

It would be nice if you, or someone else, can test the same on a recent TC 3.3.5 so we can double-check and import the code from there.

**Comment by Kitzunu** [comment]
TC and AC code is identical when it comes to adding items. For count it uses int32 which means you should be allowed to request 2147483647 as the maximum count, or at least default to that if anyone tries to request more.

But as I mentioned, TC is identical to AC in this regard.

The only difference is how it is removed, a failsafe for GMs so they are not scammed by any player. (Which isn't the issue presented anyways)

**Comment by Stifler82** [comment]
> TC and AC code is identical when it comes to adding items. For count it uses int32 which means you should be allowed to request 2147483647 as the maximum count, or at least default to that if anyone tries to request more.
> 
> But as I mentioned, TC is identical to AC in this regard.
> 
> The only difference is how it is removed, a failsafe for GMs so they are not scammed by any player. (Which isn't the issue presented anyways)

So @Kitzunu, beyond the concept that the maximum count is `2147483647`.

(As I hope you have noticed)
That TC server (from 2014) that I have, accepts the command `.add "itemID" 99999999999 (or) -99999999999.`
And most importantly, it doesn't crash after that..

So, I don't care how "at home TC" (currently) works, I care how that code "at my home" (AC) works.
**(I don't know if you know, what I mean).**

What I expect to happen when I use a number that goes beyond `(2147483647)` is that the CORE in chat tells me: `"you can't use beyond that number"`, **BUT!** in any case it must execute my request and add that ID in my bag **(as long as there is space in the bags)** and delete each guid of that ID from my bag **(until the last one)**. 

Because if I'm not mistaken this project is called: `"Azeroth Core"`.
Otherwise I think they would have called it: `"TC - C.A.P."` **(TC - COPY AND PASTE)**

**Comment by Kitzunu** [comment]
Why you can't do -99999999999 is because of a request by some server owners to add a scam safe against players. As for why you can do 99999999999 on TC and not on AC I can't tell you atm as for handling adding AC == TC which means that the issue might not be in the command itself, but somewhere else

**Comment by Stifler82** [comment]
> Why you can't do -99999999999 is because of a request by some server owners to add a scam safe against players.

I didn't understand what you mean at this point.
Could you please explain the concept better to me?

**Comment by Kitzunu** [comment]
This is what was requested by some GMs/Owners etc
```
Add check if player has 0 items to be destroyed
Add check if player has less than items trying to be destroyed
This will prevent players being able to scam Admins and GameMasters since the staff always will know if the player has the item when destroying or if they have less items than what should be destroyed
```

Was all done https://github.com/azerothcore/azerothcore-wotlk/pull/2898 a year ago

**Comment by Stifler82** [comment]
> This is what was requested by some GMs/Owners etc
> 
> ```
> Add check if player has 0 items to be destroyed
> Add check if player has less than items trying to be destroyed
> This will prevent players being able to scam Admins and GameMasters since the staff always will know if the player has the item when destroying or if they have less items than what should be destroyed
> ```
> 
> Was all done #2898 a year ago

Ok, then, to this PR of yours, you could insert exceptions to the rules you entered in the code.
where the accounts (above a certain account level) then: >0
they ignore that rule.

**Comment by FrancescoBorzi** [comment]
> @Kitzunu
> Ok, then, to this PR of yours, you could insert exceptions to the rules you entered in the code.
> where the accounts (above a certain account level) then: >0
> they ignore that rule.

I think this is a valid suggestion that would make it more developer-friendly. @Kitzunu can you please take care of it?

**Comment by Kitzunu** [comment]
Not right now, maybe later today or later in the week

**Comment by Kitzunu** [comment]
I just tested `.add 44614 999999999999999999999999999` and my server does not crash. So I cannot confirm your bug.

--

I will fix the account level for removing later in the weekend, didn't get around to it today

**Comment by Stifler82** [comment]
> I just tested `.add 44614 999999999999999999999999999` and my server does not crash, also it fills my bags with the item. So I cannot confirm your bug.
> 
> --
> 
> I will fix the account level for removing later in the weekend, didn't get around to it today

I apologize about the crash report, my bad, basically I clicked on the console window and put the CORE "on pause" **(I didn't notice)** consequently it seemed like a server crash was a wrong click.

**Comment by Kitzunu** [comment]
Weird, anyhow I will fix your suggestion 👍

**Comment by Stifler82** [comment]
@Kitzunu 
> Weird

Not weird it always works like this (on Windows OS) 

https://user-images.githubusercontent.com/1884642/115540504-02297e80-a296-11eb-96ff-f03caabb6d22.mp4

>anyhow I will fix your suggestion 👍

Thank you so much for that. ❤👍

**Comment by Stifler82** [comment]
@Kitzunu can you unblock me on Discord pls?
thank you

**Comment by Kitzunu** [comment]
Not blocked, I just dont accept PMs from non-friends, add you =)
