### ISSUE TITLE
[Quest] A Cry For Help - Cowlen's reaction is not scripted

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5368]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/446

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When reaching the destination of the escort quest A Cry For Help (https://www.wowhead.com/quest=9528/a-cry-for-help) only the daughter - Magwin - is scripted.  Her father Cowlen sits there doing nothing.

https://user-images.githubusercontent.com/81375770/115316159-188de800-a179-11eb-83e6-b50c431b4234.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Cowlen also says one line and gets up when Magwin reaches him. 
https://www.wowhead.com/quest=9528/a-cry-for-help#comments:id=662675

Full video of the quest from TBC classic is also online, timestamp pointing to the missing event
https://youtu.be/PILIuPCUz40?t=372

See also the quotes for Cowlen available in the wowgaming database:
https://wowgaming.altervista.org/aowow/?npc=17311

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept the quest from Magwin (https://wowgaming.altervista.org/aowow/?quest=9528)
2. Complete the quest
3. Notice that Cowlen at the end just sits there.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Branel** [comment]
I will look into this.

**Comment by Helias** [comment]
fix https://github.com/TrinityCore/TrinityCore/pull/18026/files

**Comment by DavuKnight** [comment]
Chromie Craft Version of this Bug is still Open. Please Close
https://github.com/chromiecraft/chromiecraft/issues/446

**Comment by Helias** [comment]
Done, thank you
