### ISSUE TITLE
Realm First! achievements from raids should announce name of guild to server [$35]

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#5369]
## CURRENT BEHAVIOUR:
When you achieve a Realm First! from raids, the following messages are broadcast to the server:
```
name has earned the achievement [Realm First! xyz]
name2 has earned the achievement [Realm First! xyz]
name3 has earned the achievement [Realm First! xyz]
```
etc (how many are in the raid that get the achievement - up to 25 times)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Essentially, the broadcast should use the guild name for the sake of the server-wide spam.  If you are in the raid and close proximity to the players getting the achievements, it should look like this:

```
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
Player1 has earned the achievement [The Fall of Naxxramas]!
player1 has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
Player2 has earned the achievement [The Fall of Naxxramas]!
player2 has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
Player3 has earned the achievement [The Fall of Naxxramas]!
player3 has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
```

For the rest of the server, it looks like this:

```
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
```

This should be the behavior on only the following achievements:

[Realm First! Obsidian Slayer](https://wotlkdb.com/?achievement=456)
[Realm First! Conqueror of Naxxramas](https://wotlkdb.com/?achievement=1402)
[Realm First! Magic Seeker](https://wotlkdb.com/?achievement=1400)
[Realm First! Celestial Defender](https://wotlkdb.com/?achievement=3259)
[Realm First! Death's Demise](https://wotlkdb.com/?achievement=3117)
[Realm First! Grand Crusader](https://wotlkdb.com/?achievement=4078)
[Realm First! Fall of the Lich King](https://wotlkdb.com/?achievement=4576)

## SOURCE:

https://i.imgur.com/BTtayWL.jpg -- In this screenshot, the guild names are Doesnt look like Amiye and Did it for Whitney - screenshot is from July 2010 and was taken from someone not in the raid

Video, same source as the screenshot above: https://youtu.be/IrEyrMw6IlY - Pause at 8:50 and play at .25% speed, it's hard to catch.  screenshot from video if you miss it: https://i.imgur.com/Bv5k9UU.png

CUTIES ONLY guild downing Algalon for the first time, video from 2009 - pause at 6:32 and play at .25% speed https://www.youtube.com/watch?v=yzZ8LTGcMVI - screenshot: https://i.imgur.com/RTWZis0.png

noxa guild downing Anub'arak w/ 50 attempts remaining, video from 2009 - pause at 9:12 and play at .25% speed https://youtu.be/aN6at_DO_N8 - screenshot: https://i.imgur.com/oc3H5uE.png

Wowhead comments:

https://www.wowhead.com/achievement=3259/realm-first-celestial-defender#comments:id=655280 - "Like all Realm First raid achievements, you will recieve a title for slaying the final boss in the raid. In this case, the title is: "The Celestial Defender". Not only do you get the title, but a nice **server-wide message stating your guild is broadcasted**!"

https://www.wowhead.com/achievement=3259/realm-first-celestial-defender#comments:id=655681 - "the message says "guild name" has earned the achievement [ Realm First: Celestial Defender] x25 not player names."

https://www.wowhead.com/achievement=1400/realm-first-magic-seeker#comments:id=726513

https://www.wowhead.com/achievement=1400/realm-first-magic-seeker#comments:id=676363

## STEPS TO REPRODUCE THE PROBLEM:
1. Create a character and create a guild
2. Create another character, on a separate account to watch the chatbox
3. On your first character, kill a boss that yields these achievements
4. Go to your second character and read the chatbox
5. The broadcast will contain the PLAYER NAME, not the guild name 

## EXTRA NOTES:
No other server has this right - it's really a forgotten mechanic.  I've been meaning to post this issue for a long time, but getting confirmation that it's real is a pain in the ass.

## AC HASH/COMMIT:
9997fa7

## OPERATING SYSTEM:
Win10

**Comment by Voxstrasza** [comment]
[bounty](https://www.bountysource.com/issues/97910266-realm-first-achievements-from-raids-should-announce-name-of-guild-to-server)

**Comment by HerrPony** [comment]
What would be the correct behavior when the raid has no guild in it?
Let's say there are 25 guildless player. Will there be no Broadcast at all?

Or what would be the behavior when two guilds work together? Would both guilds be broadcasted?

**Comment by Branel** [comment]
iirc ~80% of the radio has to be composed of one guild to be eligible for the achievment.

**Comment by HerrPony** [comment]
If someone can confirm that behavior i can try to implement this feature

**Comment by Branel** [comment]
https://wowwiki-archive.fandom.com/wiki/Guild_achievements
![image](https://user-images.githubusercontent.com/41377234/115853436-78121f00-a429-11eb-9952-639cf67564c7.png)

**Comment by UltraNix** [comment]
@Voxstrasza Please, test #5409

**Comment by Voxstrasza** [comment]
> 
> 
> https://wowwiki-archive.fandom.com/wiki/Guild_achievements
> ![image](https://user-images.githubusercontent.com/41377234/115853436-78121f00-a429-11eb-9952-639cf67564c7.png)

These are guild achievements introduced in patch 4.0.3, not character realm first achievements from WotLK.

**Comment by Voxstrasza** [comment]
> 
> 
> What would be the correct behavior when the raid has no guild in it?
> Let's say there are 25 guildless player. Will there be no Broadcast at all?
> 
> Or what would be the behavior when two guilds work together? Would both guilds be broadcasted?

I'm not sure what it would say when the raid has no guild - presumably it will substitute the character name instead of the guild - but people wouldn't normally do these raids without being in a guild.  The only confirmation I've seen of any of these raid achievements being pugged (multiple guilds) is Obsidian Slayer, which makes sense because it is the easiest boss.  

Yes, multiple guilds doing it - all should be broadcast.  See the screenshots I linked under source.
