### ISSUE TITLE
Mithril Bound Trunk stays in inventory after opening

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5372]
Orignally reported https://github.com/chromiecraft/chromiecraft/issues/444

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

https://wowgaming.altervista.org/aowow/?item=21228

Below screenshot should show:

1. I opened mithril bound trunk (see chat and bolt of runecloth i recieved)
2. Mithril bound trunk is still in my inventory
3. This only happens when you have Find fish ability learnt (thanks to @necropola)

![image](https://user-images.githubusercontent.com/68826689/115258515-49750b00-a0ee-11eb-87de-532df59be04f.png)

A video opening boxes with find fish ability learnt:
https://user-images.githubusercontent.com/81375770/115385520-861d3100-a1d8-11eb-9228-a29c257909cf.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Mithril bound trunk should disappear on use

##### STEPS TO REPRODUCE THE PROBLEM:
1. Learn ablity find fish (need 100 fishing)
2. Fish up mithril bound trunk (from Booty Bay oil blackmouth fishing pool, if it matters)
3. Open mithril bound trunk

##### EXTRA NOTES:

Used commands to learn fishing to 100 and ability "find fish" add 20 Mithril Bound Trunk
.setskill 356 100 150
.learn 43308
.additem 21228 20

Useful comment by @necropola 

> You need to learn the book that teaches "Find Fish"  (Weather-Beaten Journal 34109) which can be looted from those trunks (and requires fishing 100). This seems to prevent the book from being looted again (a recent change which now triggers the bug) and it has the effect that chests that would contain (only?) this book now stay as unlootable objects in your inventory.
> 
> I assume that this mechanic is somewhere buried in the `conditions` table, but I haven't found it, yet.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
I probably found the reason why the trunk stays in the inventory. It contains the **Weather-Beaten Journal (34109)** which is a BoP recipe the player already knows and then the following code prevents it from being shown to the player:
https://github.com/azerothcore/azerothcore-wotlk/blob/0079034d7300d53d6cdc0eb0ef7d2ae24b46500a/src/server/game/Loot/LootMgr.cpp#L436-L438
