### ISSUE TITLE
No water walking when died in dungeon

### ISSUE THREAD

**Issue by vtihomirov** [azerothcore/azerothcore-wotlk#5376]
## CURRENT BEHAVIOUR:

At the moment if you die outside of a dungeon you benefit from water walking, but if you die inside a dungeon you don't benefit from water walking while being ghost.
Found the bug while playing on ChromieCraft and I was able to reproduce it on AC master.

I was able to reproduce it with LFG.
I was able to reproduce it with normal group.
I was able to reproduce it when soloing any instance.
I was able to reproduce it by dying inside each of these dungeons:  `Wailing Caverns`, `Dead Mines`, `Scholomance`, `Coilfang: Steam Vault` and `Azjol Nerub`.

Also found this [TC issue](https://github.com/TrinityCore/TrinityCore/pull/11885) about the same thing.

## EXPECTED BLIZZLIKE BEHAVIOUR:

When you die inside a dungeon you benefit from water walking while being ghost.

## SOURCE:

![2021-04-20 02-08-01](https://user-images.githubusercontent.com/10816895/115440394-5b52cd00-a218-11eb-82d7-1ed19984dc2b.gif)

## STEPS TO REPRODUCE THE PROBLEM:

1. Enter a dungeon that has nearby water pool.
2. Kill you character inside `.die`.
3. Try to walk on the pool of water outside the dungeon.
(You should not be able to)

## AC HASH/COMMIT:

master commit [f8777b64](https://github.com/azerothcore/azerothcore-wotlk/commit/f8777b645a00cda9e9f312fd00abdb80eaef0995)

## OPERATING SYSTEM:

ubuntu docker

## MODULES:

No

## CUSTOMIZATIONS:

No

**Comment by Si1ker** [comment]
Confirmed that indeed you cannot walk on water when dead on a dungeon.

![image](https://user-images.githubusercontent.com/61223313/115482363-c4801380-a20b-11eb-8c2a-f0c9cea75853.png)

On the other hand, there are dungeon entrances that are underwater so, I may think this is blizzlike behavior.
Do you have any source that it should works as it does when outside a dungeon?

(pls ping me when replying, otherwise won't notice the answer)

**Comment by vtihomirov** [comment]
@Si1ker I was only able to find this https://youtu.be/bsknzvE63kk?t=3297.

**Comment by vtihomirov** [comment]
I was able to reproduce it in `Sunken Temple` as well.

**Comment by wizzymore** [comment]
Hi,

I can confirm the bug.
Also, if you are water walking and want to go underwater you need to look down and you will dive in.

**Comment by alchem1ster** [comment]
@Si1ker
If I'm not mistaken, you can still dive when walking on water, as @wizzymore pointed out in his response. At least that's how it should work regardless of the place of death: in the dungeon or outside of it. So I think not being able to walk on water after dying in a dungeon is a bug after all.

**Comment by Si1ker** [comment]
@vtihomirov @wizzymore @alchem1ster 
Thank you all for the feedback and comments, fixed in #5393
