### ISSUE TITLE
Druid Caster Form replaced with Cat Form model [$15]

### ISSUE THREAD

**Issue by mdawx** [azerothcore/azerothcore-wotlk#5382]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/425

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I play a druid and sometimes after a while my humanoid form disappears and my cat form replaces my humanoid form. Means i can cast nature spells while im still in cat form (just visually though i am not really in cat form)
 or when riding mounts its just my cat form on top of my mount. Here are some pictures to better Visualize. 
![download](https://user-images.githubusercontent.com/82536162/114758222-036e1f00-9d5d-11eb-90bd-a79648876c0a.png)
![download](https://user-images.githubusercontent.com/82536162/114758439-429c7000-9d5d-11eb-9377-7ddef883c627.png)

Other forms are also possible:
![2021-04-21_01-50_1](https://user-images.githubusercontent.com/81375770/115477969-65d78b80-a245-11eb-97d7-a1c1ae534c66.png)
![2021-04-21_01-48](https://user-images.githubusercontent.com/81375770/115477977-67a14f00-a245-11eb-9644-905ccd2916c6.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Well, you should get back into caster form after leaving get form. I dont think any Evidence is needed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enable module mod-cfbg
2. Join Arathi Basin battleground with 2 Night Elves druids being in cat form
3. Leave bg in the same form
4. Druid which had his faction changed returns bugged as described and showed on pictures

Demonstrating video:

https://user-images.githubusercontent.com/81375770/115478404-5b69c180-a246-11eb-8a43-bcaedeb05808.mp4

##### EXTRA NOTES:

It might be useful to change minimum number of players per team for arathi basin bg with this sql command:
```sql
update battleground_template set MinPlayersPerTeam = 1 where ID = 3;
```

To revert it back:
```sql
update battleground_template set MinPlayersPerTeam = 5 where ID = 3;
```

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
@mdawx Test https://github.com/azerothcore/mod-cfbg/pull/62
