### ISSUE TITLE
[GM's Commands]: GM's Commands need a little tweaking / fix

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5388]
##### AC SERVER REV:
- [x] `rev. f40ef6de4d00+`

##### UPDATED TO:
- [x] `2021-04-21`

##### ISSUE DESCRIPTION:

- GM's commands need a general fix, below I will illustrate the following points to fix:
  - GM's commands do not interact properly with the account level set for the related GM command.
  - There are some obsolete GM's commands in the DB that are no longer in use. **(I'm not sure, but probably just 1)**
  - There are GM's commands that do not have the syntax description on how to execute them correctly.
  - GM's commands need a better Design for a clearer reading of both the description and the syntax.
  - Appropriate arrangement of the **"more harmless"** commands to be provided to Players for higher quality feedback relating to Bugs and for some **(personal) account settings**; eg: `".account password $old_password $new_password $new_password"`
  ****[Note]: This command changes the password only for the account you are (currently) using / logged, it cannot be used to change the password of other accounts..****

##### EXTRA NEEDED ELEMENTS TO UNDERSTAND THE ISSUE:

****Video:****

https://user-images.githubusercontent.com/1884642/115526349-d6070100-a287-11eb-97bc-74643218f8f6.mp4

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
I dont agree to by default give players certain commands, that should be up to every server by themself.

As for the other points, good. I even know we handle a command that we dont have a command assigned to it ^°^

**Comment by Stifler82** [comment]
> I dont agree to by default give players certain commands, that should be up to every server by themself.
> 
> As for the other points, good. I even know we handle a command that we dont have a command assigned to it ^°^

I understand what you mean, but I believe that some "harmless" commands, such as:
`.npc info`
`.gobject target`
`.distance`
`.gps`
etc, etc ...
I don't think these are "harmful commands".
and they could greatly improve the quality of reports by players who sometimes write things, which are neither in heaven nor on earth.

**Comment by FrancescoBorzi** [comment]
I agree with the idea, in fact, in ChromieCraft we have enabled commands like `gobject near` and `npc info`

I don't think it does any harm to allow such harmless commands and each server admin is still free to disable them if he/she really wants
