### ISSUE TITLE
Goblin and Gnomish engineering accessible at same time

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5390]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/443

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

As an engineering  225 you can learn both Goblin and Gnomish engineering at the same .

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Only one engineering option should be train-able at the time. having both goblin and gnomish engineering should not be possible.

https://wowpedia.fandom.com/wiki/Gnome_Engineering?oldid=2299320
https://wowpedia.fandom.com/wiki/Goblin_Engineering

> From patch 3.2.0 until Cataclysm, Gnomish Engineers and Goblin Engineers could switch profession specializations for 150g by visiting Narain Soothfancy's hut in northeast Tanaris and interacting with the book on the table. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Level a char to 20+ and a minimum of 205 engineering. 
2. .go c 387 - this gets you to Oglethorpe Obnoticus in Booty Bay, who is the gnomish eng trainer. Learn all his recipes.
3. .go c 23414 - this takes you to Nixx Sprocketspring, goblin eng trainer in Gadgetzan. He will also teach you all goblin recipes without any pre-req quests done
4. Now you have access to both sets:
![WoWScrnShot_041921_212305](https://user-images.githubusercontent.com/81782124/115233911-a2c55480-a157-11eb-813e-ce31474c6b62.jpg)

##### EXTRA NOTES:

Thanks for reproduction steps and extended discussion to @Azcobu and @necropola

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b9ae587b6b37355448c30301f7cccd50175117cd

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
might be worth checking this comment: https://github.com/chromiecraft/chromiecraft/issues/443#issuecomment-825745777

**Comment by Kitzunu** [comment]
This will be fixed when trainer port is done

**Comment by FrancescoBorzi** [comment]
@Kitzunu have you checked that comment?

**Comment by Kitzunu** [comment]
Yes

**Comment by T1ti** [comment]
It's an issue with missing daram in column "spell trainer" of creature_template 


Litterally only armor smith and weaponsmith have data in this column right now 

I bet leather working has the same issue.

**Comment by FrancescoBorzi** [comment]
@Kitzunu are you still planning to fix this?

**Comment by Kitzunu** [comment]
I am still working on the PR to refactor it. About down to 500 errors now.

But last two weeks before graduation so I need to lay focus elsewhere
