### ISSUE TITLE
[Maraudon] Landslide

### ISSUE THREAD

**Issue by Branel** [azerothcore/azerothcore-wotlk#5391]
## CURRENT BEHAVIOUR:

Theradrim Shardling does not despawn once Landslide dies.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Theradrim Shardling should despawn once Landslide dies

## SOURCE:

https://classic.wowhead.com/guides/maraudon-classic-dungeon-strategy#landslide

## STEPS TO REPRODUCE THE PROBLEM:

1. .go c id 12203
2. Let Landslide spawn Theradrim Shardling
3.  Kill Landslide

## AC HASH/COMMIT:

2c5cb29ad490

## OPERATING SYSTEM:

Windows 10

## MODULES:

N/A

## CUSTOMIZATIONS:

N/A

**Comment by Si1ker** [comment]
Confirmed.
Fixed in #5395
