### ISSUE TITLE
[Maraudon] Princess Theredras

### ISSUE THREAD

**Issue by Branel** [azerothcore/azerothcore-wotlk#5392]
## CURRENT BEHAVIOUR:

Currently she only uses Repulsive Gaze, Thrash and correctly spawns Zaetar's Spririt upon death.
She does not stand still while casting Dust Field.

## EXPECTED BLIZZLIKE BEHAVIOUR:

She should also be using Dust Field, correctly.

## SOURCE:

https://classic.wowhead.com/guides/maraudon-classic-dungeon-strategy#princess-theradras

## STEPS TO REPRODUCE THE PROBLEM:

1. .go c id 12201
2.  Test the mechanics

## AC HASH/COMMIT:

2c5cb29ad490

## OPERATING SYSTEM:

Windows 10

## MODULES:

N/A

## CUSTOMIZATIONS:

N/A

**Comment by Branel** [comment]
I am interested in scripting her, I most likely have to delete most of her SmartAI script and do all of it as a .cpp file.

**Comment by Si1ker** [comment]
Boulder is working correctly. Remember it is a hostile-targeted ability meaning if you go with just one person, it will not occur.
![image](https://user-images.githubusercontent.com/61223313/115613877-3313ae80-a2aa-11eb-955e-0677c0bfa281.png)

The problem is only with Dust Field.

**Comment by T1ti** [comment]
pretty sure she's suppsoed to cast boulder when you solo her, it's wha makes it not too easy to solo her

**Comment by Si1ker** [comment]
> pretty sure she's suppsoed to cast boulder when you solo her, it's wha makes it not too easy to solo her

Yep, just checked, she uses it to any hostile in the spell range so no problem, ignore my last comment.
![image](https://user-images.githubusercontent.com/61223313/115615028-a669f000-a2ab-11eb-97bf-e9ba76bac17a.png)

But yeah only Dust Field is not being cast and as far as I can see the line of SAI is correct..  : s

**Comment by Si1ker** [comment]
Update:

I can use
.aura 21909
to any other mob around like the turtles so you can see the effect but it cannot be used on her.

Exmaple:

![image](https://user-images.githubusercontent.com/61223313/115615378-1d9f8400-a2ac-11eb-958e-711fa4d4a462.png)

**Comment by Branel** [comment]
Interesting, for me I couldn't get boulder to work. Nevertheless I appreciate the testing and confirmation. Let's see what we can find about the spell. I will help you investigate tomorrow morning.
