### ISSUE TITLE
Windows Compile Error 

### ISSUE THREAD

**Issue by Synz75** [azerothcore/azerothcore-wotlk#5396]
![Screenshot_2](https://user-images.githubusercontent.com/11411617/115612771-9eb14800-a2b9-11eb-89ca-6707e8f59205.png)
![Screenshot_3](https://user-images.githubusercontent.com/11411617/115612774-9f49de80-a2b9-11eb-9820-0e64d3742809.png)
My errors

**Comment by FrancescoBorzi** [comment]
hello and welcome to AzerothCore @Synz75 , please read this:

https://www.azerothcore.org/wiki/How-to-ask-for-help

if something is not clear and you need further assistance, please reach us on Discord
