### ISSUE TITLE
Jangdor Swiftstrider - Missing Greeting Text

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5400]
## CURRENT BEHAVIOUR:

The leatherworking supplier Jangdor Swiftstrider (https://wotlkdb.com/?npc=7854) in Camp Mojache has 'MISSING TEXT' as his greeting.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Looking at an old Youtube video suggests his greeting text should be: "Welcome to Camp Mojache, brave \<classname\>. How may I assist you this day?"

## SOURCE:

Screnshot showing missing text:
![WoWScrnShot_042221_165258](https://user-images.githubusercontent.com/81782124/115673229-8e699d80-a38b-11eb-94a5-a4ab51e73965.jpg)

## STEPS TO REPRODUCE THE PROBLEM:

1. .go c 50996 will take you to Jangdor. Click to see missing text.

## AC HASH/COMMIT:

rev. 4a8faafaff27+ 2021-04-22 02:42:46 +0000 

## OPERATING SYSTEM:

Ubuntu 20.10

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by Si1ker** [comment]
Confirmed.
Fixed in #5402
