### ISSUE TITLE
 Shadowmeld does not absorb damage from spells.

### ISSUE THREAD

**Issue by ErnestoGonzalezC** [azerothcore/azerothcore-wotlk#5407]
## CURRENT BEHAVIOUR:

If the enemy casts, for example, [Lava Burst] on you, when the spell is about to hit you when casting [Shadowmeld], the damage should be absorbed.

## EXPECTED BLIZZLIKE BEHAVIOUR:

When casting [Shadow Fusion] while the spell is about to hit you, the damage should be absorbed.

## STEPS TO REPRODUCE THE PROBLEM:

1.  Log in with a shaman and a night elf, launch a lava blast on the elf and when the spell is about to hit, cast [Shadowmeld] and you will notice that it does not absorb damage.

## AC HASH/COMMIT:

c95d1f72a879b9b0c430431325a9d3b92d46604b

## OPERATING SYSTEM:

Linux (Ubuntu 20.04) and Windows 10.

## MODULES:

Without Modules.

**Comment by JamesGent** [comment]
You need to add evidence/a source that shows this behaviour.

**Comment by ErnestoGonzalezC** [comment]
@JamesGent  I have not found evidence of this but nobstante in warmane it works like this and what sense does it have that if they throw you a power and you make yourself invisible the power gives you anyway? Excuse me, but it doesn't make sense.

**Comment by Kitzunu** [comment]
I agree with James here, this sounds very weird that you could resist damage in that way and something I have never heard about before.

It's not even mentioned here https://wowwiki-archive.fandom.com/wiki/Shadowmeld so I'd love some actual article or video from retail that shows this behaviour

**Comment by ErnestoGonzalezC** [comment]
> Estoy de acuerdo con James aquí, suena muy extraño que puedas resistir el daño de esa manera y algo de lo que nunca había oído hablar antes.
> 
> Ni siquiera se menciona aquí [https://wowwiki-archive.fandom.com/wiki/Shadowmeld,](https://wowwiki-archive.fandom.com/wiki/Shadowmeld) así que me encantaría algún artículo o video real del comercio minorista que muestre este comportamiento

I have been playing this game for 9 years and for me pvp is the most important thing, if I had the opportunity I would look for evidence but I can not contribute anything other than my word and that in warmane it works like that. In my opinion, what doesn't make sense is that if 1 power is thrown at you and you become invisible, the power will not only bring you out of the invisible but will also do the damage.

**Comment by Kitzunu** [comment]
Does it work the same way for vanish, stealth, prowl? Is shadowmeld the only one not working in this way?

**Comment by ErnestoGonzalezC** [comment]
> ¿Funciona de la misma manera para desaparecer, sigilo, acechar? ¿Shadowmeld es el único que no funciona de esta manera?

Stealth works the way I explain, if you cast the invisibility spell when they are about to hit you with another power, that spell is absorbed.

**Comment by bronzato** [comment]
i understand what @ErnestoGonzalezC is trying to say and i confirmed that, i'll open a new issue with evidences.

**Comment by ErnestoGonzalezC** [comment]
> i understand what @ErnestoGonzalezC is trying to say and i confirmed that, i'll open a new issue with evidences.

Please do so, I need to know the truth :)
