### ISSUE TITLE
Aldaron the Reckless Falling Through Floor [$15]

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5410]
## CURRENT BEHAVIOUR:

Aldaron the Reckless (GUID: 56994) in Eversong (target of Wretched Ringleader quest, https://wotlkdb.com/?quest=9076) can be made to fall through the floor he's standing on by hiding behind a pillar while he's casting. He'll run around a bit to get line of sight, and clip through the floor. It did take a while to get it to happen, though.

The original poster on CC did say they could still kill him and collect his head for the loot, so it's not game-breaking, just aesthetic.

Original CC report is https://github.com/chromiecraft/chromiecraft/issues/453

## EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs shouldn't fall through the floor.

## SOURCE:

![WoWScrnShot_042321_134246](https://user-images.githubusercontent.com/81782124/115872638-301ee680-a481-11eb-9f77-981914b929cf.jpg)

## STEPS TO REPRODUCE THE PROBLEM:

1. .go c  56994 and start combat with Aldaron.
2. Use pillar to obstruct line of sight.
3. Watch Aldaron fall through the floor.

## AC HASH/COMMIT:

rev. b385878e4a5b 2021-04-22 22:25:19.

## OPERATING SYSTEM:

Ubuntu 20.10

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by Azcobu** [comment]
Quick note, Aldaron is a lvl 8 NPC, so guessing 1-19 tag is more appropriate, not sure why the original CC poster had it on 20-29.

**Comment by FrancescoBorzi** [comment]
thanks @Azcobu , done!

**Comment by UltraNix** [comment]
@Azcobu Do you have mmaps enabled?
I cannot reproduce it with mmaps - without them, it's doable.

**Comment by Azcobu** [comment]
Sorry, I don't know - is there a command to find out? 

My AC instance is vanilla, with no mods or other changes, just what you get from working through the instructions here - https://www.azerothcore.org/wiki/ac-dashboard-core-installation.

If it helps, I was under the impression that a lot of 'mobs falling through floors' issues had been mitigated, although not entirely fixed, by https://github.com/azerothcore/azerothcore-wotlk/pull/5778, so problems reproducing this issue might be because of that.

**Comment by UltraNix** [comment]
Just type ingame command `.mmap loc`

**Comment by Azcobu** [comment]
.mmap loc output:
![WoWScrnShot_052321_225938](https://user-images.githubusercontent.com/81782124/119262484-93d03700-bc1a-11eb-9a32-bb644a0d24d4.jpg)

I'll try making that file and retesting.

**Comment by Azcobu** [comment]
No luck getting the mmaps_generator working. I'm on Linux rather than Windows so guessing I need to compile MapBuilder.cpp. However, it's throwing various dependency errors, and AC wiki and Discord don't have any info, so I'm stuck. Is there a copy of that .mmtile file I could download somewhere and put in the right place?

**Comment by UltraNix** [comment]
You have loaded mmaps already. Just try to reproduce again.

**Comment by Azcobu** [comment]
Tested again, working much better. He did fall through the floor a couple of times, but he at least recovers from it now.

https://user-images.githubusercontent.com/81782124/119266312-7191e580-bc29-11eb-8a41-49aa57d5b102.mp4

When I was hiding behind pillars on the same plane as him, he was doing much better than before. although there was one hitch when he just stopped fighting and stood there doing nothing without trying to move or regain LOS. But moving down the ramp a bit made him glitch through the floor fairly consistently. However, moving near him made him pop back up onto the floor, so that's an improvement.

**Comment by UltraNix** [comment]
I can't even reproduce it like you did. 10 min tests and no single fall under floor.

**Comment by Azcobu** [comment]
If you stay on his level he's basically fine, apart from stopping casting and just standing there every now and then. Running down the ramp and using that to break LOS is what triggered it for me.

**Comment by UltraNix** [comment]
I tried everything (breaking LoS, jumping down/up from that platform/ramp) - still looks okay.

**Comment by UltraNix** [comment]
@Azcobu https://imgur.com/a/aj5r8Gw
This is how it looks like on my local.

**Comment by Azcobu** [comment]
Logged in to test something else and found my character still on the tower, so had another look and within 20-30 seconds he'd fallen through the floor again. This is on rev. ea764812d14a 2021-05-24 00:52:56 +0700 (master branch).

![WoWScrnShot_052421_201953](https://user-images.githubusercontent.com/81782124/119336982-75774380-bccd-11eb-846c-27589544afff.jpg)

**Comment by UltraNix** [comment]
So I can't help you with this as you can see how it works on my local.

**Comment by Azcobu** [comment]
I think more likely you just weren't standing in the right place to trigger it. Running up and down the length of the ramp, as in your Imgur gif, wouldn't have caused him to glitch even a few weeks ago when I first tried it. 

If you try standing just at the beginning of the ramp, as in my video, you might have more luck. But you must be fairly tired of Aldaron by now, so certainly wouldn't blame you if you had other things to do with your time other than chase after one fairly obscure bug. Thanks for trying.

**Comment by speedrunz** [comment]
@UltraNix I can confirm what @Azcobu said. This mob is indeed falling to the floor when you walk to the spiral way.

**Comment by IceNet** [comment]
Why not remove the map system when more and more errors become known in this regard?

**Comment by UltraNix** [comment]
Already fixed.
