### ISSUE TITLE
[CI] macOS build unable to save the cache

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5411]
Rev: https://github.com/azerothcore/azerothcore-wotlk/commit/970d371442b450782f3fcc4c34e1afe0f848672d

```
Post job cleanup.
/usr/bin/tar -cz -f /Users/runner/work/_temp/52a3eb09-1334-42c7-9926-9689d911b43e/cache.tgz -C /Users/runner/.ccache .
tar: could not chdir to '/Users/runner/.ccache'

Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 1
```

![image](https://user-images.githubusercontent.com/75517/115875189-3f803e80-a445-11eb-94dd-2022f54d19dc.png)

example: https://github.com/azerothcore/azerothcore-wotlk/runs/2418419179

This results in non-cached macOS builds that take more than 30 minutes to run. Because of that our builds queue is congested.

**Comment by FrancescoBorzi** [comment]
cc @Rochet2 @locus313

**Comment by Rochet2** [comment]
From the CI logs under build you can see it caches to `~/Library/Caches/ccache` but the cache in the workflow file is set to `~/.ccache`.
Seems ccache has changed its default folder location or something: https://github.com/ccache/ccache/blob/master/doc/NEWS.adoc
> On macOS, the fallbacks are `~/Library/Caches/ccache`

ccache should maybe be fixed to a specific version if its not already fixed.
Other than that, updating the path we use in the github cache action step probably fixes the issue.

**Comment by locus313** [comment]
ill look at updating the workflow

**Comment by Rochet2** [comment]
Testing already stuff here if interested. https://github.com/azerothcore/azerothcore-wotlk/compare/fix-mac-ci
use it or not as you want

**Comment by locus313** [comment]
i actually seen that there is some tar related bugs on the `actions/cache` action that have been fixed. Currently the mac build is using `actions/cache@v1.1.2` going to test changing to `actions/cache@v2` and updating the path.

**Comment by FrancescoBorzi** [comment]
thanks guys! you're amazing
