### ISSUE TITLE
[EVENT] Halloween decorations and NPCs in Silvermoon during August

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#542]
Description: There are pumpkins, hanging ghosts, and masked NPCs standing in front of the AH in Silvermoon. The NPCs are wearing masks, yet their dialogue references the Lunar Festival. Pumpkins can also be seen places throughout the city. It's August!

Expected behaviour: Obviously this should only show during the Halloween event. The NPC dialogue should reference the correct holiday.

Steps to reproduce the problem:
It's currently 2017-08-09, so you may need to login soon and look at Silvermoon. Who knows if it will disappear in the future.

Branch:
Master
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by ShinDarth** [comment]
can you please edit your report and add the commit hash ? 

for example: 6aff74cd1760b4fd170f8869cc625741e83a9b23
