### ISSUE TITLE
Silvermoon City - Brewfest Banners Still Visible

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5422]
Original report: https://github.com/chromiecraft/chromiecraft/issues/459

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Brewfest banners are up outside of Silvermoon and it's April.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should only be up during Brewfest.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 56871 - this teleports you to a guard standing right next to one of the banners.
2. The other banner is just down the road a bit.

## SOURCE:

![WoWScrnShot_042421_160605](https://user-images.githubusercontent.com/81782124/115949877-15974c80-a517-11eb-94e2-bb12770df27a.jpg)
![WoWScrnShot_042421_160632](https://user-images.githubusercontent.com/81782124/115949883-1b8d2d80-a517-11eb-963d-f36337744e26.jpg)

## AC HASH/COMMIT:

rev. ecb59db05095 2021-04-23 13:47:16 -0700

## OPERATING SYSTEM:

Ubuntu 20.10

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by Helias** [comment]
fixed, thanks :wink:
