### ISSUE TITLE
[Searing Gorge] Multiple Mining Veins Spawns

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5424]
Original report: https://github.com/chromiecraft/chromiecraft/issues/450

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Multiple Spawns in same location:
GUID 373, 10214 (Small Thorium, Dark Iron)
GUID 33606, 34816 (Gold, Mithril)
GUID 10004, 35299 (Mithril, Truesilver)
GUID 5850, 7234, 9535, 58117 (Gold, Mithril, Truesilver, Dark Iron)

Still Spawned in the ground beneath rocks (wasn't fixed yet):
GUID 154 (Small Thorium)

Nodes spawned too close to each other (probably all possible spawn locations are spawned at the same time)

Included screenshots so you can judge distances.

GUID 5942, 31959 (Gold, Mithril)
![WoWScrnShot_042421_170425](https://user-images.githubusercontent.com/81782124/115951448-e933fe00-a51f-11eb-82d7-9b418b1e7381.jpg)

GUID 9380, 244 (Truesilver, Small Thorium)
![WoWScrnShot_042421_170455](https://user-images.githubusercontent.com/81782124/115951451-ed601b80-a51f-11eb-899b-49075ed3f7c5.jpg)

GUID 9595, 9596 (Truesilver)
![WoWScrnShot_042421_170515](https://user-images.githubusercontent.com/81782124/115951454-efc27580-a51f-11eb-84cd-e25f302e2746.jpg)

GUID 6143, 33139 (Iron)
![WoWScrnShot_042421_170547](https://user-images.githubusercontent.com/81782124/115951456-f2bd6600-a51f-11eb-8cb7-05c886644a69.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Veins should not spawn inside eachother, or simultaneously close to each other.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have mining and track minerals on to see veins on map
2. Teleport to provided GUIDs

## AC HASH/COMMIT:

rev. ecb59db05095 2021-04-23 13:47:16 -0700 (

## OPERATING SYSTEM:

Ubuntu 20.10

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by markvetx** [comment]
This issue was discussed in #4928. If someone can, take a look at the comments.

**Comment by alchem1ster** [comment]
`Truesilver` and `Iron` from your issue will be removed in [this PR](https://github.com/azerothcore/azerothcore-wotlk/pull/5415)

**Comment by Hacki95** [comment]
> 
> 
> `Truesilver` and `Iron` from your issue will be removed in [this PR](https://github.com/azerothcore/azerothcore-wotlk/pull/5415)
> The remaining objects need to be moved to another location :)

They should only be removed it they spawn on top of each other. If they are near each other like it that means that those objects are simply missing their pooling data.

**Comment by FrancescoBorzi** [comment]
@Hacki95 are you still planning to work on this?
