### ISSUE TITLE
[Docker] functions.sh: line 119 command not found when using docker compose

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5429]
## CURRENT BEHAVIOUR:

The assembler does not work when using [docker compose run](https://docs.docker.com/engine/reference/commandline/compose_run/) instead of [docker-compose run](https://docs.docker.com/compose/reference/run/)

## EXPECTE BEHAVIOUR:

It should work with both, they are supposed to be equivalent.

## STEPS TO REPRODUCE THE PROBLEM:

1. `docker compose up -d ac-database` 
2. `docker compose run --rm ac-dev-server`

You'll get the following error:

```
/azerothcore/apps/db_assembler/includes/functions.sh: line 119: MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';: command not found

```

## EXTRA NOTES:

Using `docker-compose` instead of `docker compose` works.

## AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/26a477dd126c68a46f265b97dd439d9982bba1d1

## OPERATING SYSTEM:

macOS

## MODULES:

None

## CUSTOMIZATIONS:

None

**Comment by Yehonal** [comment]
DOCKER_DB_EXTERNAL_PORT this only changes the external port (the one exposed to the host), the internal one remains the same. I'll try and let you know

**Comment by FrancescoBorzi** [comment]
@Yehonal I've updated the original issue, my bad, the env variable had nothing to do with the problem.
