### ISSUE TITLE
DB/Quest: A Pawn on the Eternal Board

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#543]
**Description:** 

Anachronos sends you to Silithus to learn what you can about the AQ gate. After clicking the crystalline tear the event starts. When the event completes, the vision of Anachronos says, "You now know all there is to know." and he disappears. He doesn't turn into his dragon form, and the quest does not complete.

I tested this three times. **The first two times** Anachronos did not return to his dragon form and the quest did not complete. One of those times the fire surrounding the fighting elves/insects never went away, so that could be the entry point for the bug. 

**The third time** (i destroyed the book 'War of the Shifting Sands ID: 20415) in my inventory before clicking the crystalline tear to start the event (this may have nothing to do with it) and everything worked as it should, the insects/elves despawned and Anachronos turned into his dragon form then disappeared. The quest then completed correctly. The Charge of the Dragonflights was now available from Anachronos after completing Pawn on the Eternal Board, but there was no quest text for this quest in his dialogue.

**Expected behavior:** 
The description of the 3rd test it how the event should work every time. Perhaps there's some kind of  bug that occurs at random during the event which is the cause of the insects/elves not being despawned and making the quest fail.

**Steps to reproduce the problem:**

Get the quest from Anachronos and watch the event in Silithus. Return to Anachronos at the Caverns of Time.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by FrancescoBorzi** [comment]
Confirmed by @comix1988

here his report:

------
**DESCRIPTION:**

Quest "A Pawn on the Eternal Board" has a some bugs:
1- it's impossible to complete;
2- has various graphic bugs;

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The quest is part of a long chain of the Brood of Nozdormu faction. it's simple to complete, you just have to watch an animation outside the doors of Ahn'Quiraj and then deliver it.

https://www.youtube.com/watch?v=YL4YQWtK5Ao   example 1
https://www.youtube.com/watch?v=V_wU8PhIIWU    example 2


**CURRENT BEHAVIOUR:**
I try to expose the various bugs:
1- the conversation in the movie does't get to the end, it ends at this point "The sands of time will halt, but only for a moment! I will conjure the barrier."This does't allow the quest to complete.

![discorso](https://user-images.githubusercontent.com/22867608/52532293-ab71a300-2d22-11e9-8250-dc125cb46922.png)

2- visually the dragons fly incorrectly, you need to review the waypoints;
3- visually the dragon spells don't apply anything to the mobs;
4- visually the gate door of Ahn'Quiraj does't appear;

https://youtu.be/I4zavAx4XdQ video link

**STEPS TO REPRODUCE THE PROBLEM:**

1- .modify reputation 910 42000
2- .quest add 8303
3- .go -8234 -4640 2.3 1  complete quest and take "long forgotten memories" quest
4- .go -8027 1542 2.6 1 complete quest and take "A Pawn on the Eternal Board"  quest
5- wait for the end of the movie

**BRANCH(ES):**
staging

**AC HASH/COMMIT:**
commit [987095e](https://github.com/azerothcore/azerothcore-wotlk/commit/987095e2c9da04b6ac9efcd2639a012cc72552d7)

**OPERATING SYSTEM:**
linux

**MODULES:
OTHER CUSTOMIZATIONS:**

**Comment by Endeffect-AT** [comment]
##### SMALL DESCRIPTION:


See the screenshots below. Quest can not be finished sometimes.

##### EXPECTED BLIZZLIKE BEHAVIOUR:


The battle of the scarabs and the Anubisath Conqueror should look more pleasant, some npc's are missing. The waypoints of the dragons are horrible.

Look this video: **https://www.youtube.com/watch?v=V_wU8PhIIWU**

##### CURRENT BEHAVIOUR:


- Position of the dragons & waypoints

![WoWScrnShot_020820_131555](https://user-images.githubusercontent.com/55922592/74085560-427a5380-4a7a-11ea-9758-1688f76288e1.jpg)

- Some NPCs 15424 Anubisath Conqueror are missing

![WoWScrnShot_020820_135240](https://user-images.githubusercontent.com/55922592/74085581-9d13af80-4a7a-11ea-9b21-6e6dfadebaca.jpg)


- Mouseover gate bug: 

![2020-02-08 13_48_31-Window](https://user-images.githubusercontent.com/55922592/74085537-13fc7880-4a7a-11ea-9c16-022b5e947db3.png)


- I had the problem that with my main non-gm char the quest didn't finished (Tried 3 times). I also tried the same quest using the steps above and it finished as expected. I don't know why but this is strange.

##### STEPS TO REPRODUCE THE PROBLEM:


1. Preparation: .q rem 8305, .q a 8305, .q c 8305
2. .go -8025.437500 1539.031250 2.609403 1
3. Accept the following quest 8519 and look at the event

##### EXTRA NOTES:

Quest id 8519
##### BRANCH(ES):


master


##### AC HASH/COMMIT:


eadbd40d5e82+

##### OPERATING SYSTEM:


Windows 10 pro x64

##### MODULES:


- Auction House Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:


- Max skill on  levelup








<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/88253663-quest-a-pawn-on-the-eternal-board-is-buggy-and-can-not-be-completed?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by heyitsbench** [comment]
Currently grabbing a sniff in WotLK Classic for this questline. Still processing, but [here's a link to a recording I did while sniffing](https://www.youtube.com/watch?v=RMs_VByK70U) (I recorded while listening to videos, feel free to mute the video.)

**Comment by Kitzunu** [comment]
Closing in favor for https://github.com/azerothcore/azerothcore-wotlk/issues/12783
