### ISSUE TITLE
[Docker] unix2dos permission error

### ISSUE THREAD

**Issue by EddyBuhler** [azerothcore/azerothcore-wotlk#5430]
## CURRENT BEHAVIOUR:
When running 

./acore.sh docker build

on Linux (in this case Arch), the process fails at the very end with: 

```
Fixing EOL...
dos2unix: converting file /azerothcore/env/dist/etc/authserver.conf to Unix format...
dos2unix: converting file /azerothcore/env/dist/etc/authserver.conf.dist to Unix format...
dos2unix: Failed to change the owner and group of temporary output file /azerothcore/env/dist/etc/d2utmpcspzOa: Operation not permitted
dos2unix: problems converting file /azerothcore/env/dist/etc/authserver.conf.dockerdist
dos2unix: converting file /azerothcore/env/dist/etc/worldserver.conf to Unix format...
dos2unix: converting file /azerothcore/env/dist/etc/worldserver.conf.dist to Unix format...
dos2unix: Failed to change the owner and group of temporary output file /azerothcore/env/dist/etc/d2utmphVuqDa: Operation not permitted
dos2unix: problems converting file /azerothcore/env/dist/etc/worldserver.conf.dockerdist
ERROR: 1
```

## EXPECTED BLIZZLIKE BEHAVIOUR:

The process succeeds with:

```
Fixing EOL...
dos2unix: converting file /azerothcore/env/dist/etc/authserver.conf to file /azerothcore/env/dist/etc/authserver.conf.dist in Unix format...
dos2unix: converting file /azerothcore/env/dist/etc/authserver.conf.dockerdist to file /azerothcore/env/dist/etc/worldserver.conf in Unix format...
dos2unix: converting file /azerothcore/env/dist/etc/worldserver.conf.dist to file /azerothcore/env/dist/etc/worldserver.conf.dockerdist in Unix format...
```

## SOURCE:
N/A or follow the Azerothcore Docker Install guide.

## STEPS TO REPRODUCE THE PROBLEM:
Follow the AzerothCore Docker Install guide until the above-mentioned step.

## EXTRA NOTES:
Googling the issue brought up this redhat link: https://access.redhat.com/solutions/3168671

Indeed, the solution given here (to use the -n flag) works, i.e. changing the last line in 

https://github.com/azerothcore/azerothcore-wotlk/blob/master/bin/acore-docker-build

to

dos2unix -n "$ENV_PATH/dist/etc/"*

resolves the issue.

## AC HASH/COMMIT:
26a477dd126c68a46f265b97dd439d9982bba1d1

## OPERATING SYSTEM:
Arch Linux

## MODULES:
No

## CUSTOMIZATIONS:
No, was first install

**Comment by locus313** [comment]
I was able to reproduce this on Arch Linux. Just to note, I was not able to reproduce it on Ubuntu

**Comment by locus313** [comment]
when checking the ownership on the files I noticed the group id is being set to 1000:
![image](https://user-images.githubusercontent.com/4015312/115978014-9ebb7d00-a531-11eb-8dab-b216ea2b9cb7.png)
This is due to the group id we are setting in the docker container. But it looks like Arch Linux doesn't start the group id's at 1000. Here is an example:
![image](https://user-images.githubusercontent.com/4015312/115978128-5486cb80-a532-11eb-85d0-863ed97e68d5.png)

**Comment by EddyBuhler** [comment]
What would be a good solution? script-writing the current user's group id into a ".env" file?

**Comment by EddyBuhler** [comment]
Also, my initially proposed fix doesn't work, it just fails differently.

**Comment by Yehonal** [comment]
check the PR I have created
