### ISSUE TITLE
Bug npc ins trial of the champion

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5435]
CURRENT BEHAVIOUR:

Trial of the Champion npc bug

EXPECTED BLIZZLIKE BEHAVIOUR:

These 3 NPCs should not work these spells
(Hex)(Stune)(feayer) And ...
As you can see in the picture, it is frozen

SOURCE:
![WoWScrnShot_042421_231502](https://user-images.githubusercontent.com/80007195/115969888-8741bb80-a554-11eb-8401-496b1e16277b.jpg)

STEPS TO REPRODUCE THE PROBLEM:

Entry NPC = 34701
Entry NPC = 34705
Entry NPC = 34657

EXTRA NOTES:
AC HASH/COMMIT:

rev. cb0fb719db05+ 2021-03-19 11:23:01 +0100

OPERATING SYSTEM:
Ubuntu 20.10

MODULES:
N/A.

CUSTOMIZATIONS:
N/A.

**Comment by Si1ker** [comment]
You have 24h to edit this issue and fulfill the template you deleted.

**Comment by poryagholami1374** [comment]
I did not notice, my dear, that I did not touch anything, I reported a bug, I still have a bug, I report, fix it

**Comment by poryagholami1374** [comment]
> You have 24h to edit this issue and fulfill the template you deleted.

Where is the problem? Tell me to edit

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5436 fixed

**Comment by poryagholami1374** [comment]
> #5436 fixed

Delete this post now?

**Comment by Kitzunu** [comment]
no, it will be closed once merged

**Comment by poryagholami1374** [comment]
Not completely fixed
These pipes are still working

[Cyclone]
[Hammer of Justice]
and ...

The last boss
When Pet throws
The pet is underground
We have to walk to get out
Some bosses also go to the ground
I think the problem is with vmap

**Comment by poryagholami1374** [comment]
Sorry this
Report canceled
Or is it going to be fixed?

**Comment by Sedatyf** [comment]
> Sorry this
> Report canceled
> Or is it going to be fixed?

It is closed because it was already fixed
