### ISSUE TITLE
[Quest] Scalding Mornbrew Delivery Autocompletes

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5439]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/460

The dwarf quest Scalding Mornbrew Delivery (https://wowgaming.altervista.org/aowow/?quest=3364) is instantly marked as completed after pickup and no timer is present. 

Also, if you do wait for more than five minutes, nothing happens, and you can still successfully turn in the quest.

![WoWScrnShot_042521_111701](https://user-images.githubusercontent.com/81782124/115977791-53997c80-a5ba-11eb-97d8-8d92e538c3bb.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The quest should be timed (5 min) and complete after you reach the required position.
https://classic.wowhead.com/quest=3364/scalding-mornbrew-delivery#videos:id=166317

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 965 and pick up quest.
2. Look at quest status.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Did some more checking and found a comment at https://www.wowhead.com/quest=3364/scalding-mornbrew-delivery#comments:id=926999 that says this quest was no longer timed as of patch 3.3. If this is accurate, and the other comments don't dispute it, then this quest is actually behaving correctly and the wording is just a bit ambiguous.

I'll leave this open for a day or so in case anyone else has comments and then close the issue as Working As Intended.

**Comment by Helias** [comment]
reading your last comment, I think ew can close this, do you agree?

**Comment by Azcobu** [comment]
Agreed, closing.
