### ISSUE TITLE
[QUEST] The Charge of the Dragonflights has no quest text

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#544]
**Description:**  The Charge of the Dragonflights quest has no quest description text. After turning in Eternal Pawn on the Board, the dialogue is blank and it's slightly confusing that you need to talk to Anachronos once again.

**Expected:**
The questdescription and logdescription fields are blank for this quest and should say something along the lines of, "Speak with Anachronos ... " to indicate the next step instead of being blank.

**Steps to reproduce the problem:**
Complete 'Pawn on the Eternal Board' if you don't get a bugged event.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by StygianTheBest** [comment]
I've noticed this behavior on two different quests now, so it may be something with how the core is working. When completing a quest, the dialog should go to the next quest's text or be finished. Instead, it's showing a dialogue that's got a blank description and then you have to talk to the npc again to get the next quest. Either that extra dialogue box needs to be removed, or it needs to actually show the next quests information.

**Comment by Viste** [comment]
in fact it can be missing db data

**Comment by Viste** [comment]
https://github.com/TrinityCore/TrinityCore/issues/13074

**Comment by pondaveia** [comment]
https://www.youtube.com/watch?v=zFy91PkhfsY 

_7:56 min_
After you click on read quest you get instantly the complete quest log. There are no objectives to this.

I'll take care of this one when I finish my current one.

**Comment by poszer** [comment]
Yeah, it's a blank. Maybe we should use it like this, just so people can know what's the next step to do.

`UPDATE `quest_template` SET `QuestDescription`='You have to go in the Tanaris, Caverns of the Time. Find Anachronos and speak with him.' WHERE `ID`=8555;`

**Comment by poszer** [comment]
As the default it's empty. Closing this
