### ISSUE TITLE
Broken vmaps?

### ISSUE THREAD

**Issue by ErnestoGonzalezC** [azerothcore/azerothcore-wotlk#5442]
## CURRENT BEHAVIOUR:

- During the tests that I carry out of the powers to make corrections I have noticed that there are several powers that make the characters sink to the ground, I guess this is a bug in the vmaps.
PD: I have tried with data extracted from my client and the official azerothcore.

## EXPECTED BLIZZLIKE BEHAVIOUR:

- The collision should work fine.

## STEPS TO REPRODUCE THE PROBLEM:

1. Watch the video.

https://user-images.githubusercontent.com/80600689/115984082-084f8180-a55a-11eb-9380-d7b4eb2f9939.mp4

https://user-images.githubusercontent.com/80600689/115984091-1f8e6f00-a55a-11eb-9892-cf8bb30e56c3.mp4

## AC HASH/COMMIT:
 765660b

## OPERATING SYSTEM:

- Windows 10 and Ubuntu 20.04

## MODULES:

- None.

**Comment by ErnestoGonzalezC** [comment]
https://user-images.githubusercontent.com/80600689/116109785-f78e3100-a669-11eb-8916-46c279990fb7.mp4

**Comment by T1ti** [comment]
probably vmaps, not mmaps
mmaps are mostly for creatures

**Comment by UltraNix** [comment]
@ErnestoGonzalezC Try implement this fix https://gist.github.com/UltraNix/772f14a2085014ce36dffcebe16b0182 and give me your feedback.

**Comment by ErnestoGonzalezC** [comment]
> @ErnestoGonzalezC Try implement this fix https://gist.github.com/UltraNix/772f14a2085014ce36dffcebe16b0182 and give me your feedback.

It works wonderfully although in my opinion it should be tested by more people or on a server with more people since these types of errors are often difficult to reproduce.
