### ISSUE TITLE
[Docker] error when using build:clean command

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#5443]
## CURRENT BEHAVIOUR:

Get the following error when trying to use the `./acore.sh docker build:clean` command:
![image](https://user-images.githubusercontent.com/4015312/115985326-42238680-a560-11eb-9da9-61898fa50cc8.png)

## STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

## OPERATING SYSTEM:

windows

**Comment by Yehonal** [comment]
Confirmed, this happens only on windows and git-bash.

If you use linux or windows with wsl the error cannot be reproduced.

I'm preparing the fix
