### ISSUE TITLE
[Trinket] Gnomish Universal Remote Does Not Work [$5]

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5447]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/463

The Engineer trinket, Gnomish Universal Remote, does not work properly. When it succeeds at mind controlling a mechanical target, you cannot attack, use abilities, or even manually cancel the effect. My engineering skill is 225/225.

A pet bar does appear, with Control Machine and Cancel options, but neither button does anything. An Attack button also appears on the main toolbar, but again, it doesn't work. Even right-clicking the Control Machine buff in the top right of the screen doesn't cancel it. Right clicking enemy mobs to auto-attack while controlling the robot also fails.

Screenshot showing Attack button active but doing nothing:

![WoWScrnShot_042521_213041](https://user-images.githubusercontent.com/81782124/115992979-946fb080-a60f-11eb-8a89-4a73c369c87d.jpg)

![WoWScrnShot_042521_215252](https://user-images.githubusercontent.com/81782124/115993175-c7667400-a610-11eb-8a8e-f79302d093b5.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When successful at mind controlling a mechanical target, you should be able to attack, use abilities, and manually cancel the mind control effect of the target.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to any location where mechanical targets exist. (Gnomergan, Venture Co. Base camp in STV, etc)
2. Equip the Gnomish Universal Remote Trinket.
3. Use the trinket while in range of a mechanical target.
4. Upon a successful mind control of the mechanical target, you will not be able to attack or use the abilities of the mind controlled target, or even manually cancel the effect unless you move the target far away.

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?item=7506
https://www.wowhead.com/item=7506/gnomish-universal-remote#comments

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/b8b5f68f98ff8771a6ec87ea6805ceced91c406a

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Azcobu thanks for your contributions! What is your Discord username?

**Comment by Azcobu** [comment]
I'm Excidium#8395 on the AC/CC Discords.
