### ISSUE TITLE
New database column settings for creatures Aggro.(and rework the leash/aggro systems) [$30]

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#5455]
## CURRENT BEHAVIOUR:

There is not a single settting for creatures aggro at all, they are all hardcoded and use the same generic valeus in the core.

## EXPECTED BLIZZLIKE BEHAVIOUR:

This is based on a screenshot of Blizzard's creature tool editor from late 2009 I was able to find 
![image](https://user-images.githubusercontent.com/40864460/116001168-7a27d980-a5f3-11eb-85a6-9d26c623412a.png)

This confirms that we need settings for : 

- **Detection** : This is the range at which creatures detect and see players

- **Pursuit** : The most hard to guess. I believe this is the initial aggro radius around the creature's original position, in which he will never reset

- **Call for help** : This is the radius of the creature's "call for help" mechanic when it's aggroed, all creatures in 50 yards around it will aggro with it.

- **Timeout** : This is a timer, it sets in seconds how long will it take for the creature to reset (outside the pursuit radius). If set to 0 creature will never stop chasing, it's set to 0 for all creatures in instances.

- **Leash** : I believe this is for the hardset leashes distance for some creatures, this is not widely used, it's mostly used for world bosses so you can't kite them to stormwind, like Kazzak. If 0 then the creature deosn't use this
They do set some premade templates that they reuse, I believe there just are a few generic templates for dungeons mobs, dungeon bosses, world bosses, raid bosses etc...

**### NOTE : Currently the AC leash/Aggro system works very differently, I had already made an issue about how to make it blizzlike, this picture further proofs I was right and Blizz use a timeout system for the leash.**
https://github.com/azerothcore/azerothcore-wotlk/issues/5116
![image](https://user-images.githubusercontent.com/40864460/116001458-d50e0080-a5f4-11eb-856b-d827b474cda0.png)

## SOURCE:

![image](https://user-images.githubusercontent.com/40864460/116001472-e5be7680-a5f4-11eb-9136-14638beec3b1.png)
and the research I did in https://github.com/azerothcore/azerothcore-wotlk/issues/5116

## STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

## AC HASH/COMMIT:

d11d021f38e0e0db27e7c74da801402e7e5f17d9

**Comment by Winfidonarleyan** [comment]
Hmm, time to port https://github.com/TrinityCore/TrinityCore/pull/19930 maybe

**Comment by T1ti** [comment]
> Hmm, time to port [TrinityCore/TrinityCore#19930](https://github.com/TrinityCore/TrinityCore/pull/19930) maybe

this  completely unrelated, my post is about the aggro radius system(how creatures aggro, and how do they stop aggroing), not the threat system

**Comment by T1ti** [comment]
The only core that has a blizzlike creature aggro system is vmangos, not TC

They had already done the work of analysing how Classic behaves and implemented it.

**Comment by Yehonal** [comment]
> The only core that has a blizzlike creature aggro system is vmangos, not TC
> 
> They had already done the work of analysing how Classic behaves and implemented it. I believe TC uses the same non blizzlike system without a timer like AC

do you have the link to their implementation commit?

**Comment by T1ti** [comment]
> > The only core that has a blizzlike creature aggro system is vmangos, not TC
> > They had already done the work of analysing how Classic behaves and implemented it. I believe TC uses the same non blizzlike system without a timer like AC
> 
> do you have the link to their implementation commit?

https://github.com/vmangos/core/commit/7d2f1e2923734ea1b983eeaa0208cfd158d4af02#diff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658 
It was already using the timer system before this commit, this commit updated some features to further match Classic : 
- extend leash on any spell hit, not only when mob is damaged
- extend leash when mob stands still while chasing
- link leash timer of mobs on initial assist
- 
The original timer implementation seems very old, from nostalrius era

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/116002525-6c298700-a5fa-11eb-94e3-2d7a045803b9.png)

In their database : 
![image](https://user-images.githubusercontent.com/40864460/116002556-924f2700-a5fa-11eb-891b-862bb35a9eca.png)

**Comment by Hacki95** [comment]
Is this the same as #5116 ?

**Comment by Krejza9** [comment]
It's the same, only in this incident it's more detailed

**Comment by Krejza9** [comment]
I have already started working on rewriting the aggro distance from Vmangos to AC
https://github.com/Krejza9/azerothcore-wotlk/commit/2b7249f85dffd0dc1984ab1aaa567d9e036bda92

If there is some good soul who would collaborate with me to redesign this functionality I would be very happy.

**Comment by ChromieCraftServer** [comment]
> I have already started working on rewriting the aggro distance from Vmangos to AC
> [Krejza9@2b7249f](https://github.com/Krejza9/azerothcore-wotlk/commit/2b7249f85dffd0dc1984ab1aaa567d9e036bda92)
> 
> If there is some good soul who would collaborate with me to redesign this functionality I would be very happy.

thanks for working on this, we have added 30$ bounty

![image](https://user-images.githubusercontent.com/48177002/119906878-64d60000-bf4f-11eb-92aa-3cec24b909d0.png)

**Comment by T1ti** [comment]
as some extra info, based of some of vmangos research : 
creatures in starting zones have 8 yards radius, all creatures in later zones seem to have 16

Mostly raid creatures/bosses seem to have higher than that, they will have to be manually tuned.
There's also a popular belief that mechanical creatures like harvest watchers in westfall have a higher detection radius, I don't know if that's true or not

![image](https://user-images.githubusercontent.com/40864460/119923312-c313da80-bf71-11eb-8524-68a5f6ba393e.png)

**Comment by Krejza9** [comment]
I discovered a strange behavior on AC when calculating the distance vector.
I'm trying to manually set the Creature::GetAggroRange return to 7.0f. Then each creap should aggro at 7 yards 
but creatures aggroing on 9.2yards
![image](https://user-images.githubusercontent.com/5585555/119993646-17e43f00-bfcc-11eb-9c04-bb06c67f1cb8.png)

**Comment by T1ti** [comment]
Are you the same level as the creature ?

**Comment by Krejza9** [comment]
If you are talking about the mechanism inside the function GetAggroRange(Unit const* target)
,where the calculation is performed, I have overridden it for testing purposes with the value 7.0f

**Comment by Krejza9** [comment]
It may be time to implement this for better position calculation
https://github.com/vmangos/core/commit/2d1f7d20d42ebb7fb764fb914395c3869f78800f

**Comment by Krejza9** [comment]
Okay, so I finally found it.
The problem is the bounding radius, that's why AC adds the radius to the final value, that's why it doesn't match the distances.
Here's the fix they made on Vmangos
https://github.com/vmangos/core/commit/af745365e9bd7f0963734510452c0ac957fb1424

**Comment by Krejza9** [comment]
@FrancescoBorzi  Can I ask the developers to collaborate with the implementation of https://github.com/vmangos/core/commit/af745365e9bd7f0963734510452c0ac957fb1424. Then I will add my fix for aggro distance.

**Comment by FrancescoBorzi** [comment]
thank you @Krejza9

**Comment by Krejza9** [comment]
I created a pull request for bounding radius for aggro distance checks 
https://github.com/azerothcore/azerothcore-wotlk/pull/6179 <-- (I am currently looking for someone to help me with porting this.)
This fix is required for correct deployment of "Port aggro distance from VMangos"
