### ISSUE TITLE
Worldserver error BigNumber.cpp

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#5462]
After the last update the error is occurring on the worldserver

Below is a picture of the problem:
![image](https://user-images.githubusercontent.com/67213916/116002748-8e5adf00-a5d1-11eb-9701-f8aca732beb6.png)

STEPS TO REPRODUCING THE PROBLEM:
1. Last core update  d11d021f38e0

2. Compile solution
3. Run worldserver.exe
4. Attention to the following error: C: \ server \ Acore \ src \ common \ Cryptography \ BigNumber.cpp: 191 in BigNumber :: GetBytes Assertion Failed: res> 0
Buffer of size 0 is too small to hold bignum with 0 bytes.

rev.   d11d021f38e0

**Comment by Kitzunu** [comment]
There is no such creature in our DB

**Comment by Kitzunu** [comment]
Anyhow, do you have any crashlog?

**Comment by WillzDevs** [comment]
> Anyhow, do you have any crashlog?
> 
> Actually build in RelWithDebInfo or Debug, a crashlog from Release is useless

do you say this crashlog?
![image](https://user-images.githubusercontent.com/67213916/116005289-b0a62a00-a5dc-11eb-8e8e-b4f71133adca.png)

**Comment by WillzDevs** [comment]
@Kitzunu 
I got correction following an old correction.
The correction is https://github.com/UltraNix/azerothcore-wotlk/commit/c7cb69fa7575f3aaa56fac4e3a5bc024b38cf84b

Now it's working!
