### ISSUE TITLE
Feature: Specific Probility and Scale for each creature's display ID

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#5463]
**Describe your feature request or suggestion in detail**

Currently : 
- There is only 1 scale setting, which applies to all displays. 
- There is no probability settings, all displays have equal chance.

**Describe a possible solution to your Feature or Suggestion in detail**

_secondary : -There should be a scale setting for EACH display_
-There should be a probability for each display, allowing to ahve a higher chance to ahve a specific display. Like 60% chance display 1, 40% chance display 2.

In sniffs they even send them : 
![image](https://user-images.githubusercontent.com/40864460/116002830-c6771780-a5fb-11eb-8d7c-68f8f009a2e1.png)
**Display scale seems optional, blizz doesn't even seem to use it and always defaults it, but it's in their database.**
But display specific probability is commonly used, there are many case in sniffs were some displays ahve higher probabiltiy than others.
![image](https://user-images.githubusercontent.com/40864460/116003016-9419ea00-a5fc-11eb-8798-6ba82b48a95d.png)

And it can be seen in their editor tool here : display specific probability is here, but there doesn't seem to be display specific scale
![image](https://user-images.githubusercontent.com/40864460/116002909-19e96580-a5fc-11eb-959c-70d086a34255.png)

**Additional context**

**Comment by Gultask** [comment]
This is how it's displayed in parsed sniffs:
```
DisplayIdCount: 4
TotalProbability: 1
[0] DisplayId0: 18722
[0] DisplayScale0: 1
[0] DisplayProbability0: 1
[1] DisplayId1: 6633
[1] DisplayScale1: 1
[1] DisplayProbability1: 0
[2] DisplayId2: 7350
[2] DisplayScale2: 1
[2] DisplayProbability2: 0
[3] DisplayId3: 11091
[3] DisplayScale3: 1
[3] DisplayProbability3: 0
```

After the removal of the modelid field of the creature table, it'd also remove the need to workaround bad IDs by using SAI

**Comment by heyitsbench** [comment]
For the record, [this is the TC commit](https://github.com/TrinityCore/TrinityCore/commit/9d210476e57949094fdd286001ef4900564edca5) (master branch) that added support for display probabilities.

**Comment by Gultask** [comment]
https://github.com/chromiecraft/chromiecraft/issues/4803

**Comment by avarishd** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/17118
https://www.wowhead.com/wotlk/npc=22123/rip-blade-ravager#models
