### ISSUE TITLE
World server running without response

### ISSUE THREAD

**Issue by au-top** [azerothcore/azerothcore-wotlk#5470]
## CURRENT BEHAVIOUR:

```

root@debian:~/azeroth-server/bin# ./authserver
Wrong Loggers configuration. Review your Logger config section.
Creating default loggers [root (Error), server (Info)] to console
root@debian:~/azeroth-server/bin# ./worldserver
Wrong Loggers configuration. Review your Logger config section.
Creating default loggers [root (Error), server (Info)] to console
root@debian:~/azeroth-server/bin#

```

## EXPECTED BLIZZLIKE BEHAVIOUR:

server run 

## STEPS TO REPRODUCE THE PROBLEM:

```

git clone source code

mkdir build

cmake ../ -DCMAKE_ INSTALL_ PREFIX=$HOME/azeroth-server/ -DCMAKE_ C_ COMPILER=/usr/bin/clang -DCMAKE_ CXX_ COMPILER=/usr/bin/clang++ -DWITH_ WARNINGS=1 -DTOOLS=0 -DSCRIPTS=1

make -j 6

make install
 

mysql -uroot < /sql/create/create_mysql.sql


bash apps/db_assembler/db_assembler.sh   // 5


wget https://github.com/wowgaming/client-data/releases/download/v10/data.zip

cd ~/azeroth-server
mkdir data
cp  ~/data .
unzip data.zip

cp  authserver.conf.dist authserver.conf

cp  worldserver.conf.dist worldserver.conf

./authserver

./worldserver


```

## EXTRA NOTES:

More information

#5370 

directory structure is

```

root@debian:~/azeroth-server# tree -L 2
.
├── bin
│   ├── authserver
│   └── worldserver
├── data
│   ├── Cameras
│   ├── dbc
│   ├── maps
│   ├── mmaps
│   └── vmaps
└── etc
    ├── authserver.conf
    ├── authserver.conf.dist
    ├── worldserver.conf
    └── worldserver.conf.dist

8 directories, 6 files
root@debian:~/azeroth-server#

```

## AC HASH/COMMIT:

```
commit b8b5f68f98ff8771a6ec87ea6805ceced91c406a (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Mon Apr 19 06:49:48 2021 +0000

    chore(DB): import pending SQL update file

    Referenced commit(s): 9d6a0412a472c815b0c2921afcaa62f6389cc46e

```

## OPERATING SYSTEM:

Debian10 or Debian10 in Docker

## MODULES:

Not MODULES

**Comment by ErnestoGonzalezC** [comment]
If you have the resources I would recommend using Ubuntu 20, I use it in my day to day and I have never had problems, I regret not being able to contribute something about debian since I do not use it :(

**Comment by au-top** [comment]
> If you have the resources I would recommend using Ubuntu 20, I use it in my day to day and I have never had problems, I regret not being able to contribute something about debian since I do not use it :(
Thanks , let me try. Under Ubuntu, are you using manual compilation or something

**Comment by ErnestoGonzalezC** [comment]
Packages: apt-get install git cmake make gcc g++ clang libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mysql-server libace-6.* libace-dev
To Compile: cmake ../Core -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS=0 -DSCRIPTS=1

**Comment by au-top** [comment]
> Packages: apt-get install git cmake make gcc g++ clang libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mysql-server libace-6.* libace-dev
> 
> To Compile: cmake ../Core -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS=0 -DSCRIPTS=1


Thanks, I'm downloading Ubuntu server 20 :)

Is my directory structure correct


```

root@debian:~/azeroth-server# tree -L 2
.
├── bin
│   ├── authserver
│   └── worldserver
├── data
│   ├── Cameras
│   ├── dbc
│   ├── maps
│   ├── mmaps
│   └── vmaps
└── etc
    ├── authserver.conf
    ├── authserver.conf.dist
    ├── worldserver.conf
    └── worldserver.conf.dist

8 directories, 6 files
root@debian:~/azeroth-server#


```

**Comment by ErnestoGonzalezC** [comment]
Apparently it is correct.

**Comment by ErnestoGonzalezC** [comment]
@au-top In your steps to solve the problem what I saw is that you never configure the worldserver.conf or authserver.conf files, are you sure they are pointing correctly to your database?

**Comment by au-top** [comment]
> @au-top In your steps to solve the problem what I saw is that you never configure the worldserver.conf or authserver.conf files, are you sure they are pointing correctly to your database?

yes my use  Default database user acore passwd acore

**Comment by ErnestoGonzalezC** [comment]
> > @au-top In your steps to solve the problem what I saw is that you never configure the worldserver.conf or authserver.conf files, are you sure they are pointing correctly to your database?
> 
> yes my use Default database user acore passwd acore

And did you make sure to create the user `` acore `` `` acore `` in your database?

**Comment by au-top** [comment]
> > > @au-top In your steps to solve the problem what I saw is that you never configure the worldserver.conf or authserver.conf files, are you sure they are pointing correctly to your database?
> > 
> > 
> > yes my use Default database user acore passwd acore
> 
> And did you make sure to create the user `acore` `acore` in your database?

emmm my use command test 
![image](https://user-images.githubusercontent.com/44134842/116020220-6ffbee80-a678-11eb-920a-fadf65d47040.png)

**Comment by ErnestoGonzalezC** [comment]
you can try to use.
```
DROP USER IF EXISTS 'acore'@'127.0.0.1';
CREATE USER 'acore'@'127.0.0.1' IDENTIFIED BY 'acore';
GRANT ALL PRIVILEGES ON * . * TO 'acore'@'127.0.0.1' WITH GRANT OPTION;
```
But the truth seems like one more problem on the part of the operating system.

**Comment by au-top** [comment]
is my config

cat authserver.conf
![image](https://user-images.githubusercontent.com/44134842/116020334-a8033180-a678-11eb-93fe-afb1484cd95a.png)
![image](https://user-images.githubusercontent.com/44134842/116020342-ad607c00-a678-11eb-9611-d2d1de07c922.png)


---
cat worldserver.conf
![image](https://user-images.githubusercontent.com/44134842/116020459-e1d43800-a678-11eb-8a06-4f2a843522ab.png)

**Comment by au-top** [comment]
> you can try to use.
> 
> ```
> DROP USER IF EXISTS 'acore'@'127.0.0.1';
> CREATE USER 'acore'@'127.0.0.1' IDENTIFIED BY 'acore';
> GRANT ALL PRIVILEGES ON * . * TO 'acore'@'127.0.0.1' WITH GRANT OPTION;
> ```
> 
> But the truth seems like one more problem on the part of the operating system.

my run command is ok , but  the problem remains

**Comment by ErnestoGonzalezC** [comment]
I think I have found the problem, at no time did he tell him where the data is.
Reemplace ``DataDir = "."``
For this ``DataDir = "../data"``

**Comment by au-top** [comment]
> I think I have found the problem, at no time did he tell him where the data is.
> Reemplace `DataDir = "."`
> For this `DataDir = "../data"`
my edit over
...

---

tree
![image](https://user-images.githubusercontent.com/44134842/116021010-ef3df200-a679-11eb-850f-368f934ff2e3.png)

----

but 
![image](https://user-images.githubusercontent.com/44134842/116020745-80609900-a679-11eb-9d97-84cac7030191.png)
![image](https://user-images.githubusercontent.com/44134842/116020795-9706f000-a679-11eb-801b-8d1d1834dcc9.png)

**Comment by ErnestoGonzalezC** [comment]
Try creating a directory called ``logs`` in `` /azeroth-server`` and in the worldserver.conf and authserver.conf settings 
point  ``LogsDir = "../ logs``
Also try to give read write and execute permissions to everything `` chmod -R 755 * `` while in ``/azeroth-server``

**Comment by au-top** [comment]
config
![image](https://user-images.githubusercontent.com/44134842/116021549-fca7ac00-a67a-11eb-9770-5dd4da543082.png)
![image](https://user-images.githubusercontent.com/44134842/116021562-03362380-a67b-11eb-9d35-6545e95bb02e.png)

---
res

![image](https://user-images.githubusercontent.com/44134842/116021603-1b0da780-a67b-11eb-8c30-0fee6778ae8c.png)

**Comment by ErnestoGonzalezC** [comment]
It must definitely be something related to the operating system, when you are using Ubuntu 20 I am sure you will not have these problems if you apply what I recommended above :)
You can contact me by discord if you have any other problem ``KiK0#8511``

**Comment by au-top** [comment]
> It must definitely be something related to the operating system, when you are using Ubuntu 20 I am sure you will not have these problems if you apply what I recommended above :)
> You can contact me by discord if you have any other problem `KiK0#8511`

Thanks I'll test it
