### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5471]
Compilation error
![image](https://user-images.githubusercontent.com/18187177/116018510-bf402000-a674-11eb-9604-0205fde13f1f.png)

## STEPS TO REPRODUCE THE PROBLEM:
1. Update to the latest version
https://github.com/azerothcore/azerothcore-wotlk/commit/f4c226423dc0811efccf8135b46bc7ff46aab940
2.Add mod-antichat module
2. Then compile

## AC HASH/COMMIT:
f4c226423dc0811efccf8135b46bc7ff46aab940

## OPERATING SYSTEM:
ubuntu 20.04

## MODULES:
mod-antichat

**Comment by mpfans** [comment]
`git reset --hard 28ce1e921921a1d04f718056583c9b62dc219edf`

Compile OK

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/116019136-1db9ce00-a676-11eb-8f81-68c61c6ce8d5.png)

**Comment by rogerc66** [comment]
same error here

**Comment by UltraNix** [comment]
I'm working on it.
