### ISSUE TITLE
[Spell] Rank 1 Flamestrike Shares Cooldown With All Explosives [$5 awarded]

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5475]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/466

When a dynamite/bomb is used, flamestrike will share a cooldown with them (1min)
The cd is not shown on flamestrike;
You'll see "Spell is not ready yet"

When I tested this, I tried all 12 bombs available to engineers at lvl 225 with every rank of Flamestrike. Only rank 1 Flamestrike was affected. All 12 bombs caused the 1 min cooldown, even Explosive Sheep.

![WoWScrnShot_042621_125141](https://user-images.githubusercontent.com/81782124/116025299-4f8b5e80-a68f-11eb-9b64-6f601981754f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Flamestrike should not share a cd with these explosives.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use a dynamite/bomb from Engineering
2. Use Flamestrike rank 1.

##### EXTRA NOTES:

Bombs tried:
[Mithril Frag Bomb]
[Big Iron Bomb] 
[Big Bronze Bomb] 
[Small Bronze Bomb] 
[Large Copper Bomb] 
[Rough Copper Bomb]
[Solid Dynamite] 
[Heavy Dynamite] 
[Coarse Dynamite]
[Ez-Thro Dynamite] 
[Rough Dynamite]
[Explosive Sheep]

https://wowgaming.altervista.org/aowow/?spell=2120

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
So this is caused by spell category 24 that those items use, but flamestrike deosn't seem to use this category in either the DBC or the spell_dbc db this is weird

**Comment by UltraNix** [comment]
But some rank 1 spells are used by items and that's why they triggers cooldowns.

**Comment by Azcobu** [comment]
Just had a report from CC (linked above) that this was causing problems again, and verified it. This is trying to cast Flamestrike rank 1 after using a bomb:

![WoWScrnShot_100121_224903](https://user-images.githubusercontent.com/81782124/135634361-47ae85cd-95a3-47ed-87d3-0af1d2925e9f.jpg)
![WoWScrnShot_100121_232931](https://user-images.githubusercontent.com/81782124/135634368-d5f3aa52-663f-42a0-be5b-c128c04c78fd.jpg)

Also tested linked issue https://github.com/azerothcore/azerothcore-wotlk/issues/6324 by using Crystalized Mana Residue and then trying to cast rank 2 Lesser Heal, and that is also back to not working.

**Comment by UltraNix** [comment]
@Azcobu Now it's okay. My bad.
