### ISSUE TITLE
NPC equipment does not work

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/azerothcore-wotlk#5476]
## CURRENT BEHAVIOUR:
Hi, today I compile a clean installation of Azeroth Core wotlk  and Equip Template Table for NPC doesn't seem to work at all
I checked the table creature_equip_template, it's okay, but there's nothing to see in the game. 
https://ibb.co/5YsCB8Q
https://ibb.co/266CwPD
https://ibb.co/1fYc5nL

## EXPECTED BLIZZLIKE BEHAVIOUR:
Northshire Guard, Deputy Willem, Northshire Peasant,Kobold Worker and many more NPC must have items in their hand.

## STEPS TO REPRODUCE THE PROBLEM:

1. Compile
2. Run

## OPERATING SYSTEM:
Debian 20.04

## MODULES:
No

## CUSTOMIZATIONS:
No

**Comment by Kitzunu** [comment]
Have you used creature_template_addon.Bytes2? You choose there if weapon is prepared or not

**Comment by Kitzunu** [comment]
@UltraNix could this be due to ObjectGUID implementation?

**Comment by Voxstrasza** [comment]
Might be related to Darkshire NPCs not being able to unsheathe their weapons if there is a ranged weapon equipped.

**Comment by UltraNix** [comment]
@Kitzunu I don't think so, but you can debug `Creature::LoadEquipment` function to be sure that is working okay.

**Comment by Kitzunu** [comment]
@UltraNix not due to your PR, Krej confirmed it was bugged before

**Comment by Krejza9** [comment]
Something very bad happened to me today. I downloaded the WoW client from Chromiecraf just in case and the NPC items are working.
So I dug out an old WoW WOTLK GB DVD installation and after installing 20 patches the items are functional.
i.e. my original version of Wow where items don't work was probably broken
I apologize for the inconvenience

**Comment by FrancescoBorzi** [comment]
@Krejza9 do not use the enGB client as it has been proved to be buggy
