### ISSUE TITLE
[NPC] "Insane Ghoul" Wrong Spawn Location and Behavior

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5480]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X ] enUS
- [ ] other (specify)

##### FACTION

- [X ] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/468

NPC stands in place without moving on wrong location.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be spawned in church at the Tranquil Gardens Cemetery or be found walking around the church, instead he stands in place at the cemetery without moving.

Link to the classic wow db: https://classic.wowhead.com/npc=511/insane-ghoul#comments
Link to the youtube video: https://www.youtube.com/watch?v=H-tsD6NGN9k

![image](https://user-images.githubusercontent.com/81812276/116096873-ecf38c00-a6a9-11eb-9f03-250ce9f6858f.png)

![WoWScrnShot_042721_001723](https://user-images.githubusercontent.com/81782124/116103181-82b10a80-a6ee-11eb-8739-7cfc7675e9b7.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 4444 will teleport you to him directly - though you might need to run away and let him reset to see his non-aggroed behaviour.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
fixed ;-)
