### ISSUE TITLE
[NPC] Franclorn Forgewright is visible to LIVE players.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#549]
**Description:** 
The ghost of Franclorn Forgewright is visible to LIVE players.

**Expected behavior:** 
The ghost of Franclorn Forgewright should only be visible to DEAD players.

**Steps to reproduce the problem:**
Visit the central area of Blackrock Mountain alive and go to his tomb.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by STARRHELD** [comment]
```SQL
-- Franclorn Forgewright SAI
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 8888;

-- Table smart_scripts
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 8888);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(8888, 0, 0, 0, 11, 0, 100, 1, 0, 0, 0, 0, 11, 10848, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Franclorn Forgewright - On Respawn - Cast \'Shroud of Death\'');
```

**Comment by Viste** [comment]
offtopic:
Unconfirmed -- what is this

**Comment by StygianTheBest** [comment]
Just tested this and the NPC is still visible to live players.

**Comment by Viste** [comment]
try this
UPDATE `creature_template` SET `npcflag`=32771, `AIName`='' WHERE `entry`=8888;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 8888  AND `source_type` = 0;
UPDATE `creature_template_addon` SET `auras`=10848 WHERE `entry` IN (8888);

**Comment by StygianTheBest** [comment]
This appears to have fixed the issue. He is now invisible to live players and visible to dead players. The quest can be picked up while dead.

**Comment by Viste** [comment]
@StygianTheBest you can open PR and add this fix to repository. But its hackfix, need some core improvments to do it right

**Comment by BarbzYHOOL** [comment]
why is it hackfix?

**Comment by Viste** [comment]
can't explain it on eng my world pool is small

**Comment by StygianTheBest** [comment]
> can't explain it on eng my world pool is small

We can all understand C++. Give it a shot.

**Comment by Viste** [comment]
@StygianTheBest funny but you say you understand C++ but no do anything(issue doesn't count) and i sure not all of peoples who read  this is understand C++

**Comment by BarbzYHOOL** [comment]
Issues count, and he understands C++. Stop fighting for nothing.

**Comment by Viste** [comment]
@BarbzYHOOL блять иди нахуй, об ошибках могут и игроки написать. Если он знает С++ где помощь по коду ? только разговоры ни о чем и 0 помощь в исправлении чего-либо.

**Comment by StygianTheBest** [comment]
@Viste The two people that are reading this are asking you to elaborate on your proposed solution. You, on the other hand, are just being an asshole whiny fucking child. How about this. Don't bother responding to any more of these threads. Nobody has time to deal with you when your pussy starts hurting. If you can't be civil and answer simple questions, then just go somewhere else and pretend to be special.

**Comment by ShinDarth** [comment]
Please stop this fight now....

`(issue doesn't count)`

of course they do. Reporting issues COUNTS.

Also please use english because not everyone can understand Russian

**Comment by Viste** [comment]
@StygianTheBest и ты иди нахуй бомж вокзальный, нихуя толку с тебя нет кроме разведения базаров.

**Comment by Viste** [comment]
@ShinDarth sorry man but this idiot @StygianTheBest hated by me with he first post adressed to me so i don't stop in fucking him mother :D

**Comment by StygianTheBest** [comment]
@ShinDarth It should be clear to everyone that with @Viste's statement of, "issues don't count" he believes, for reasons unknown (he's lonely? misunderstood? has special needs?), that he is somehow superior to other members of this community. He became extremely offended when I originally asked him to elaborate on his vastly ignorant comment "everything is broken" by posting something constructive that could be followed up on. Instead, he continues to incite arguments and display himself as a fully developed douche canoe. If issues don't count, his superiority platform of being a "fixer" is negated, and thus his own perception of himself being special ceases to exist. I mean.. that's how stupid this kid is. I digress..

**Comment by Viste** [comment]
almost all vanilla stuff is not everything lol  ну и прежде чем писать хуйню про конструктивность , посмотри что я обычно делаю и как и только после этого пиши свои тупые комментарии про детей и прочие. Про то, что задачи не считаются это мое личное мнение, на которое я имею право, как и ты на свое убогое тоже. Поэтому потеряйся полудурок )

**Comment by Yehonal** [comment]
@Viste said that it's an hack just because he copied this kind of fix from trinitycore: https://github.com/TrinityCore/TrinityCore/issues/16041

where people discussing about this "small hack"

However i'll delete all not related comment, please stop this kind of flame here

**Comment by Yehonal** [comment]
However, this is the sniff posted by Aokromes, retrieved on retail server:

```
ServerToClient: SMSG_AURA_UPDATE_ALL (0x0495) Length: 15 ConnectionIndex: 0 Time: xx/xx/2010 xx:xx:xx.xxx Number: 83380
GUID: Full: xxxxxxxxx Type: Unit Entry: 8888 Low: 1658
[0] Slot: 0
[0] Spell ID: 10848
[0] Flags: EffectIndex0, NotCaster, Positive (25)
[0] Level: 60
[0] Charges: 0
```

[0] Spell ID: 10848 -> the aura should be fine

**Comment by Viste** [comment]
@Yehonal don't read this issue.  and yes copy it from tc but from commit.  and i see it a hacky way to do this
