### ISSUE TITLE
The Forge Of Souls Problem canceling spell boss

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5493]
CURRENT BEHAVIOUR:
The Forge Of Souls
Devonurer of Souls Boss

EXPECTED BLIZZLIKE BEHAVIOUR:

The Forge Of Souls Problem canceling spell boss

Please fix this, thank you

SOURCE:
![WoWScrnShot_042721_123600](https://user-images.githubusercontent.com/80007195/116214417-ec1b3280-a75b-11eb-808d-ac63a61da8d2.jpg)

STEPS TO REPRODUCE THE PROBLEM:

Entry NPC : 36502

Entry Spell :28730
Entry Spell :10308
and ...

EXTRA NOTES:
AC HASH/COMMIT:

rev. 26a477d 2021-04-24 10:42:48 +0000

OPERATING SYSTEM:
Ubuntu 20.10

MODULES:
N/A.

**Comment by Sedatyf** [comment]
I don't understand the problem. Can Devourer of Souls be interrupted or not? Because Phantom Blast should be interruptible

**Comment by poryagholami1374** [comment]
> I don't understand the problem. Can Devourer of Souls be interrupted or not? Because Phantom Blast should be interruptible

Is it possible to bass in a cast?
Shouldn't it be like this?

**Comment by Sedatyf** [comment]
Not all boss are interruptible, but this one is definitively interruptible. Please see this : https://www.wowhead.com/spell=68982/phantom-blast#comments

**Comment by poryagholami1374** [comment]
> Not all boss are interruptible, but this one is definitively interruptible. Please see this : https://www.wowhead.com/spell=68982/phantom-blast#comments

Even Paladin Province?
This paladin spell should no longer work

**Comment by Sedatyf** [comment]
What do you mean by Paladin Province? You mean [Hammer of Justice](https://tbc.wowhead.com/spell=853/hammer-of-justice)?

**Comment by poryagholami1374** [comment]
> What do you mean by Paladin Province? You mean [Hammer of Justice](https://tbc.wowhead.com/spell=853/hammer-of-justice)?

YES

**Comment by poryagholami1374** [comment]
Even ice and many other lulls cause this

**Comment by r-o-b-o-t-o** [comment]
> > What do you mean by Paladin Province? You mean [Hammer of Justice](https://tbc.wowhead.com/spell=853/hammer-of-justice)?
> 
> YES

Please take a look at this video: https://youtu.be/wtv4yMHSkLQ?t=11
You can see the player use Hammer of Justice, and the scrolling battle text on the right says "Interrupt! (Phantom Blast)". So yes, you can definitely interrupt it with Hammer of Justice.

**Comment by Sedatyf** [comment]
Hammer of Justice is meant to cancel cast on bosses. It's written in the [spell description](https://wotlkdb.com/?spell=10308)
![image](https://user-images.githubusercontent.com/59012307/116218401-c76a8f00-a74a-11eb-92ea-f3d16af7dc7b.png)

Now, you have to be precise on what spell can interrupt because I don't know what you meant with "ice"

**Comment by ErnestoGonzalezC** [comment]
I agree with @Sedatyf that the behavior is correct.
