### ISSUE TITLE
Vault Of Archavon Orb problem

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5494]
CURRENT BEHAVIOUR:
Vault Of Archavon

EXPECTED BLIZZLIKE BEHAVIOUR:

When we could not pull the boss
orb is still there

Please fix this, thank you

SOURCE:
![WoWScrnShot_042721_144854](https://user-images.githubusercontent.com/80007195/116228272-4f13c600-a76a-11eb-9041-d2b305c3d23c.jpg)

STEPS TO REPRODUCE THE PROBLEM:

Entry NPC : 38456

EXTRA NOTES:
AC HASH/COMMIT:

rev. 26a477d 2021-04-24 10:42:48 +0000

OPERATING SYSTEM:
Ubuntu 20.10

MODULES:
N/A.

**Comment by Sedatyf** [comment]
If I understand it correctly, if you pull Toravon the Ice Watcher and then your raid die, his Frozen Orbs don't disappear? 
Did you try pulling him again and see if they disappear at this moment?

**Comment by Si1ker** [comment]
![image](https://user-images.githubusercontent.com/61223313/116278945-34c6f180-a744-11eb-9a99-fce3efc86c3a.png)

I confirmed the orbs despawn after combat or at wipe.

Use a translator or whatever you want to write a proper report or this will be closed.

**Comment by poryagholami1374** [comment]
> I confirmed the orbs despawn after combat or at wipe.
> 
> Use a translator or whatever you want to write a proper report or this will be closed.

When the Orb comes
For example
If everyone dies
Orb is there
It does not disappear

**Comment by poryagholami1374** [comment]
> If I understand it correctly, if you pull Toravon the Ice Watcher and then your raid die, his Frozen Orbs don't disappear?
> Did you try pulling him again and see if they disappear at this moment?

If he dies himself
Or we die
orb is there

The truth is that it must be eliminated

**Comment by poryagholami1374** [comment]
This also has a problem, please fix it, thank you

**Comment by Kitzunu** [comment]
Confirmed on https://github.com/azerothcore/azerothcore-wotlk/commit/970d371442b4 (6days) && e02d5f4

How to reproduce:

1. .go c id 38433
2. Wait until boss spawns "Frozen Orb"
3. Kill the boss
4. See that "Frozen Orb" does not despawn as the boss has been killed.
5. Note also that if you kill yourself after the boss has died, the "Frozen Orb" will remain alive too.

**Comment by poryagholami1374** [comment]
> Confirmed on [970d371](https://github.com/azerothcore/azerothcore-wotlk/commit/970d371442b4) (6days) && [e02d5f4](https://github.com/azerothcore/azerothcore-wotlk/commit/e02d5f4ae4be07c8996981b7abfbb16c79b30a1a)
> 
> How to reproduce:
> 
> 1. .go c id 38433
> 2. Wait until boss spawns "Frozen Orb"
> 3. Kill the boss
> 4. See that "Frozen Orb" does not despawn as the boss has been killed.
> 5. Note also that if you kill yourself after the boss has died, the "Frozen Orb" will remain alive too.
> 
> ![image](https://user-images.githubusercontent.com/24550914/116541788-316e6a00-a8ec-11eb-9b81-3f21a4188935.png)


If you destroy the boss
If you do not destroy the boss
In both cases
orb remains

**Comment by francovilla** [comment]
I have the fix, I upload it soon
