### ISSUE TITLE
Can't revive dead people in Halls of Stone

### ISSUE THREAD

**Issue by Sedatyf** [azerothcore/azerothcore-wotlk#5497]
## CURRENT BEHAVIOUR:

If people from your party die against [Krystallus](https://wotlkdb.com/?npc=27977) you can't revive them with a revive spell like Paladin's Redemption
EDIT: As @Si1ker mentioned it, it is not only on Krystallus but everywhere else in the instance. Please, take a look at [his comment](https://github.com/azerothcore/azerothcore-wotlk/issues/5497#issuecomment-827752492)

## EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to revive dead people like every instance.

## SOURCE:

https://user-images.githubusercontent.com/59012307/116248199-f04f4c00-a76b-11eb-962c-f9c43553230e.mp4

## STEPS TO REPRODUCE THE PROBLEM:

1. ``.gm on``
2. Group with another account
2. ``.go c Krystallus``
3. ``.group summon``
4. Let your other character die
5. Try to revive him

## EXTRA NOTES:

I checked with Paladin's **Redemption** and Priest's **Ressurection** but I didn't try with other class/spell

## AC HASH/COMMIT:

310f856932609c777985ea797b649e8d8fbd0440

## OPERATING SYSTEM:

Tested on server on Linux 5.10.23-1-MANJARO x86_64 21.0.2 and Windows 10

**Comment by Si1ker** [comment]
@Sedatyf my question is.. why do you say that it is when dying against Krystallus??

The behaviour of not being able to resurrect another player through a spell is something from 2-3 years ago, is in the instance itself (everywhere within).

First room when entering instance:
![image](https://user-images.githubusercontent.com/61223313/116279859-48268c80-a745-11eb-9365-6a346011f354.png)

**Comment by Sedatyf** [comment]
Oh really? I was not aware of that. So you can't revive someone in the Halls of Stone? 
To be honest with you, it was an issue (https://github.com/azerothcore/azerothcore-wotlk/issues/5492) that I "translated" in order to be inspected or fixed

**Comment by Si1ker** [comment]
it is indeed an issue, but it is all over the instance. First time I saw this was 3 years ago.
No auras present on the body that could prevent the spell from being executed, I never figured out what it is.
Maybe someone like @Kitzunu may have some thoughts on where to look.

**Comment by Sedatyf** [comment]
Okay, so should I close this issue? Or just modify issue's description?

**Comment by Branel** [comment]
I'd keep it open, a edit is suffice. It does seem like a very interesting issue though.

**Comment by Sedatyf** [comment]
Done, thanks @Branel!

**Comment by Hacki95** [comment]
I edited the title for you if you see that as more fitting.

**Comment by Sedatyf** [comment]
Perfect @Hacki95 forgot about it. Thanks

**Comment by Branel** [comment]
I can confirm this bug, priest resurrect works fine but seemingly paladin doesn't. Will investigate root cause but maybe we should round up which ones work and which doesn't

**Comment by Sedatyf** [comment]
> I can confirm this bug, priest resurrect works fine but seemingly paladin doesn't. Will investigate root cause but maybe we should round up which ones work and which doesn't

You could revive someone with a priest? I couldn't on Krystallus when I tested it
