### ISSUE TITLE
[QUEST] Ironfel is not placed into the statues hand after Dark Iron Legacy quest turn-in.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#550]
**Description:** 
After turning in the quest, Dark Iron Legacy, the statue model does not update and display the Ironfel hammer.

**Expected behavior:** 
The statue model should show the hammer in the hand of the statue after turning in the quest.

**Steps to reproduce the problem:**
Turn in the quest at the statue. 

**Reference**
http://db.vanillagaming.org/?quest=3802#.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by BarbzYHOOL** [comment]
lol

**Comment by StygianTheBest** [comment]
What's so funny? :) Nice chat the other day. I hope you get that server revived. I like a lot of your ideas.

**Comment by BarbzYHOOL** [comment]
You are really into details :p 
Do you just remember this from retail or did you investigate ? Btw I guess it might be fixable with smart_scripts, not sure

**Comment by StygianTheBest** [comment]
I remember it from retail (I'm a Loremaster) and I ran the quest the other day. These details add a lot to the game, the story, and the quests. Quests like this, with marbled text, and other special quests should be preserved as they were in the original game. Not doing so would be a travesty IMO. Check the links and you'll see the hammer in the statue's hand.

**Comment by poszer** [comment]
Confirmed, he's right. There should be hammer in hand after quest complete https://youtu.be/hjuWgUxJ9ZA?t=340
