### ISSUE TITLE
Vehicles unable to be moved

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5507]
CURRENT BEHAVIOUR:

wintergrasp

EXPECTED BLIZZLIKE BEHAVIOUR:

Tanks do not work
Harrow tanks can not move
And the cannon fail

SOURCE:
![WoWScrnShot_042821_103308](https://user-images.githubusercontent.com/80007195/116355201-c3a04080-a80e-11eb-8b31-21e1cfc905fb.jpg)

STEPS TO REPRODUCE THE PROBLEM:

EXTRA NOTES:
AC HASH/COMMIT:

rev. 360c1b6383b3+ 2021-04-27 12:39:06 +0000

OPERATING SYSTEM:
Ubuntu 20.10

MODULES:
N/A.

CUSTOMIZATIONS:
N/A.

**Comment by GMKyle** [comment]
my guess.... You are trying to use other player vehicle xD

**Comment by poryagholami1374** [comment]
![WoWScrnShot_042821_234643](https://user-images.githubusercontent.com/80007195/116461808-f1709e00-a87d-11eb-9dea-32b909511d3d.jpg)
Test them all broken
Can not be shaken

**Comment by poryagholami1374** [comment]
> my guess.... You are trying to use other player vehicle xD

Anything like that
The player is unable to move it

**Comment by poryagholami1374** [comment]
This is a very important issue
please follow up

**Comment by r-o-b-o-t-o** [comment]
Hi, I can confirm that Wintergrasp vehicles and ToC5 horses are unable to move.
Tested on e02d5f4a on Windows 10 client and server

**Comment by poryagholami1374** [comment]
> Hi, I can confirm that Wintergrasp vehicles and ToC5 horses are unable to move.
> Tested on [e02d5f4](https://github.com/azerothcore/azerothcore-wotlk/commit/e02d5f4ae4be07c8996981b7abfbb16c79b30a1a) on Windows 10 client and server


So there is a problem?

**Comment by r-o-b-o-t-o** [comment]
> So there is a problem?

Looks like there is, yes!

**Comment by poryagholami1374** [comment]
> > So there is a problem?
> 
> Looks like there is, yes!


I said that there is an important problem
Nobody listens to me
They just make fun

**Comment by Sedatyf** [comment]
It's not the right place to have this conversation but on 5 issues, only one 2 are good issues (and one was hard to understand you). The other 3 were false report (and it was easy to check). So maybe there is a reason why we don't take you seriously

**Comment by poryagholami1374** [comment]
> It's not the right place to have this conversation but on 5 issues, only 2 are good issues (and one was hard to understand you). The other 3 were false report (and it was easy to check). So maybe there is a reason why we don't take you seriously


Other reports have been true
You did not test nicely
Out of 4 cases, I said only 1 wrong

**Comment by Sedatyf** [comment]
> Other reports have been true
> You did not test nicely
> Out of 4 cases, I said only 1 wrong

You want to have this conversation? Alright, let's have it.
1. Your issue about cutting casting spell on Forge of Souls: it was written on Hammer of Justice spell's description. As simple as that
2. Your issue about Body and Heart for Druid. We tested it on our own and we gave you video from 15 years ago on original Vanilla, and it showed that behavior on CC matches behavior on video.
3. Your issue about Archavon. Someone else checked about it. He said that there was nothing to worry about and you didn't give us more proof about what you said. Furthermore, a tons of Druid on CC did, are doing, or will do this quest without any problems. Coincidence? Doubt it

So how we didn't test it correctly and how could you be right?

**Comment by FrancescoBorzi** [comment]
which commit has broken this?

**Comment by Kitzunu** [comment]
works on https://github.com/azerothcore/azerothcore-wotlk/commit/970d371442b4 (6days)

Broken on https://github.com/azerothcore/azerothcore-wotlk/commit/e02d5f4ae4be07c8996981b7abfbb16c79b30a1a

Vehicles instantly throw me off, not even allowed to sit in them

**Comment by FrancescoBorzi** [comment]
can you guys please keep trying until you find the faulty commit?

`git checkout COMMIT_HASH` then recompile

**Comment by r-o-b-o-t-o** [comment]
It's not only for Wintergrasp vehicles and ToC horses, all vehicles seem to be broken.
@Kitzunu you need to grab a lance from the rack and equip it, otherwise the horse throws you off.

**Comment by Kitzunu** [comment]
Was other vehicles, I didnt test any toc. But it is generic for all vehicles

**Comment by r-o-b-o-t-o** [comment]
Huh, weird. On my server, I can sit on them but can't move

**Comment by Kitzunu** [comment]
Yea my bad, was missing aura on wintergrasp vehicle xD

Still confirm, stuck no movement

**Comment by Kitzunu** [comment]
Culprit https://github.com/azerothcore/azerothcore-wotlk/commit/f4c226423dc0811efccf8135b46bc7ff46aab940

AzerothCore rev. f4c226423dc0 2021-04-25 22:18:03 +0200 (HEAD branch) (Win64, RelWithDebInfo) (worldserver-daemon) ready.

CC @UltraNix

**Comment by Winfidonarleyan** [comment]
https://github.com/WarheadCore/WarheadBand/commit/847df113f1e0ed9ead2213704731f6efca7929aa#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067L24901

**Comment by r-o-b-o-t-o** [comment]
> [WarheadCore/WarheadBand@847df11#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067L24901](https://github.com/WarheadCore/WarheadBand/commit/847df113f1e0ed9ead2213704731f6efca7929aa#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067L24901)

I can confirm that reverting just this line fixes the vehicles issue.

**Comment by FrancescoBorzi** [comment]
> > [WarheadCore/WarheadBand@847df11#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067L24901](https://github.com/WarheadCore/WarheadBand/commit/847df113f1e0ed9ead2213704731f6efca7929aa#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067L24901)
> 
> I can confirm that reverting just this line fixes the vehicles issue.

very well! please send a PR ;)

**Comment by Winfidonarleyan** [comment]
#5540
