### ISSUE TITLE
wander_distance does not work

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/azerothcore-wotlk#5512]
## CURRENT BEHAVIOUR:
in creature table there is value wander_distance
but you don't use this value in the code at all and instead default value
The wander_distance value controls how far away the creature can walk from its spawn point if its MovementType = 1.

## STEPS TO REPRODUCE THE PROBLEM:

1.    spawn creature
2.   set MovementType = 1
3.    set wander_distance to 1
4.   creature always walk 5 yards

## AC HASH/COMMIT: 
0a571973d74554eaa5b0ac4e9d4468844a477ebe

## OPERATING SYSTEM:
Ubuntu 20.04

## MODULES:
No

## CUSTOMIZATIONS:
No

**Comment by Kitzunu** [comment]
The maximum distance that the creature may spawn from its spawn point. Also controls how far away the creature can walk from its spawn point if its MovementType = 1.

marking as invalid as you do not provide any type of creature or if they have MovementType = 1

**Comment by Krejza9** [comment]
I thing it is global problem for all NPCs
but if you can specific NPC then
Eastvale Lumberjack in Eastvale Logging Camp

**Comment by Krejza9** [comment]
I think I found where it can be fixed

in file
https://github.com/azerothcore/azerothcore-wotlk/blob/ca1f518b7fed75deec51392df81e03da305c61bb/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.h#L21

change to
> RandomMovementGenerator(float wanderDistance = **10.0f**) : _nextMoveTime(0), _moveCount(0), _wanderDistance(wanderDistance), _pathGenerator(nullptr), _currentPoint(RANDOM_POINTS_NUMBER)

and 

https://github.com/azerothcore/azerothcore-wotlk/blob/ca1f518b7fed75deec51392df81e03da305c61bb/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp#L215


chnge to
>  _wanderDistance = std::max((creature->GetWanderDistance() == _wanderDistance && creature->GetInstanceId() == 0) ? (creature->CanFly() ? MIN_WANDER_DISTANCE_AIR : MIN_WANDER_DISTANCE_GROUND) : 0.0f, **creature->GetWanderDistance()**);


Please @Kitzunu for verification or consultation, thank you

**Comment by Kitzunu** [comment]
Why do you default wanderDistance to 10.0f?

**Comment by Krejza9** [comment]
I think the random distance on the blizz server is limited to 10.
You can give any value you want, but it has to be different from 0 or completely rewrite the whole randomgenerator class

**Comment by Krejza9** [comment]
I do not claim that the repair is complete, but it serves its purpose.
