### ISSUE TITLE
[MINING] Double Node (Tin/Silver) in Silverpine Forest

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5513]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/474

Double Node of Tin Vein and Silver Vein at [59,50|75,50] in Silverpine Forest.

Node GUIDS are 35547 and 42971.

![WoWScrnShot_042821_201838](https://user-images.githubusercontent.com/81782124/116392144-405b0b00-a85f-11eb-93af-14b01137a06d.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No double Node spawn.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go o 42971
2.  Observe.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by ErnestoGonzalezC** [comment]
Which of the two should be removed? or just change the location of one?

**Comment by Azcobu** [comment]
Checking WH Classic's map of silver veins in Silverpine Forest shows veins in that general area, but no silver veins at 59.5, 75.5. (and only 8 silver veins in total there - see https://classic.wowhead.com/object=1733/silver-vein)

So I'd probably move it to one of the other nodes listed on that map, if there's not going to be further overlaps as a result. Is that doable, or does it involve more checking of nodes to avoid potential doubling?

**Comment by ErnestoGonzalezC** [comment]
> Checking WH Classic's map of silver veins in Silverpine Forest shows veins in that general area, but no silver veins at 59.5, 75.5. (and only 8 silver veins in total there - see https://classic.wowhead.com/object=1733/silver-vein)
> 
> So I'd probably move it to one of the other nodes listed on that map, if there's not going to be further overlaps as a result. Is that doable, or does it involve more checking of nodes to avoid potential doubling?


I think the right thing to do would be to eliminate it

**Comment by Azcobu** [comment]
Well that certainly eliminates the chance of further doubling up, so sure, go for it.

**Comment by ErnestoGonzalezC** [comment]
@Azcobu Please, when I can test this https://github.com/azerothcore/azerothcore-wotlk/pull/5514

**Comment by Azcobu** [comment]
Sorry, I'm not sure what you mean. I'm mostly triaging issues on CC, and I'm fairly new, so I might not be the right person to ask about approving a PR or whatever.

**Comment by ErnestoGonzalezC** [comment]
@Azcobu Dont worry. Anyway if you want to learn you can consult https://www.azerothcore.org/wiki/How-to-test-a-PR

**Comment by Azcobu** [comment]
@ErnestoGonzalezC thanks, that's next on my (large and growing) reading list.

**Comment by FrancescoBorzi** [comment]
@Azcobu thanks for your help! please note:

wrong: `[ X ]`
wrong: `[ X]`
wrong: `[X ]`

correct: `[X]`

**Comment by Azcobu** [comment]
Fixed, cheers.
