### ISSUE TITLE
[BUG] Movespline.cpp Assertion Failed

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#552]
**Description**:
Anyone ever get this error? (Movespline.cpp Assertion Failed)? Unfortunately, I can't supply logs for this crash. Server was idle as far as I remember. I left it running and went to sleep. Never seen the issue before, but it's listed as still an issue on Trinity as of December 2016.

**Current behaviour**: Tell us what happens
The server randomly crashes. 

**Reference**
Screenshot of error: http://i.imgur.com/WPejUkB.png
Reported on TrinityCore: https://github.com/TrinityCore/TrinityCore/issues/14194

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Operating system**:  
Win 7 x64 inside VMWare Workstation 12

**Modules**:  Are you using modules? if yes, list them
Transmog, RandomEnchant, DuelReset, and a few custom I created that are NPC related.

**Comment by Viste** [comment]
`diff --git a/src/server/game/Movement/Spline/MoveSpline.h b/src/server/game/Movement/Spline/MoveSpline.h
index 2eb6db6..b3a8188 100644
--- a/src/server/game/Movement/Spline/MoveSpline.h
+++ b/src/server/game/Movement/Spline/MoveSpline.h
@@ -83,7 +83,7 @@ namespace Movement
     public:
         int32 timeElapsed() const { return Duration() - time_passed; }	// xinef: moved to public for waypoint movegen
         int32 timePassed() const { return time_passed; }				// xinef: moved to public for waypoint movegen
-        int32 Duration() const { return spline.length(); }
+        int32 Duration() const { if (!spline.empty()) return spline.length(); else return 0; }
         MySpline const& _Spline() const { return spline; }
         int32 _currentSplineIdx() const { return point_Idx; }
         void _Finalize();`
try this

**Comment by Kaev** [comment]
I haven't applied Viste's patch yet but i got this error too after letting the server idling for like 2 months with only a few logins from time to time. No modules. Luckily i compiled with debug info so i can deliver a log.
[fca0bfdb1ff8_worldserver.exe_[10-2_22-47-17].txt](https://github.com/azerothcore/azerothcore-wotlk/files/1738045/fca0bfdb1ff8_worldserver.exe_.10-2_22-47-17.txt)

**Comment by Viste** [comment]
windows dump is soooooo inform >_< plz use linux for servers its better, windows is a desktop system :D  try my fix from gist, should help

**Comment by a4501150** [comment]
@Viste this fix would result Server hang-out(fake dead)

```
MoveSpline::UpdateResult MoveSpline::_updateState(int32& ms_time_diff)
{
    if (Finalized())
    {
        ms_time_diff = 0;
        return Result_Arrived;
    }

    UpdateResult result = Result_None;

    int32 minimal_diff = std::min(ms_time_diff, segment_time_elapsed());
    if (minimal_diff < 0)
        minimal_diff = 0;

    ASSERT(minimal_diff >= 0);
    time_passed += minimal_diff;
    ms_time_diff -= minimal_diff;
```
this hack fix is better because `ms_time_diff ` can be zero and the rest of original code can handle that

**Comment by BarbzYHOOL** [comment]
Some info from @a4501150 for a future correct fix

```
it happens when there's a map that needs to be updated, but it has already been unloaded, then it crashes
It's a rare case
-----
One of the problem is that segment_time_elapsed() returns a negative
But it requires to read the whole system to find actually where the bug occurs
```
