### ISSUE TITLE
Logging Out/Dying Inside SFK as an Alliance Player Teleports You To The Sepulcher

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5520]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/479

I was soloing SFK and at the end of the instance I used /camp to log back in outside the instance. I was teleported to the middle of the Sepulcher where the spirit healer is. This is a Horde town and I'm an Alliance player. 

I didn't recently participate in any BG and wasn't in queue. I was just in a party with my other Alliance character manually entering the instance. Though at one point on a third account I made a new Undead character, ran it to SFK, and invited it to the party so I could summon one of my characters back after I hearthed to vendor stuff. However, that character was logged out and not in the party at the time I logged out my characters from the instance and got teleported to the Sepulcher when logging back in. And the character, being level 1, never stepped inside the instance with the party. But I think the character was in the party while my other two characters were in the instance for a little while, just not when we exited.

(tester here - /camp did not produce this effect for me, but dying did. There was also no Spirit Healer available either.)

![camp](https://user-images.githubusercontent.com/8137930/116323062-441d5d80-a78b-11eb-99c7-b3c9da0d3a14.png)

![WoWScrnShot_042821_230718](https://user-images.githubusercontent.com/81782124/116415048-3265b400-a878-11eb-8e8d-5d999858c792.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

See extra notes.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to SFK (not through dungeon finder), enter the instance and logout (or die.)

##### EXTRA NOTES:

I'm not quite sure how this works in WotLK. In Vanilla it teleported you directly outside the instance right in front of the portal, but someone in Discord mentioned it teleports you to the nearest hub. Even if it is supposed to teleport you to the nearest hub, is the intended behavior that it teleports you to the nearest hub no matter what faction it is, or that it teleports you to the nearest hub belonging to your faction? Apologies if this is invalid, but I've been doing research and can't find any answers for Wrath specifically. Just reporting in case it is a bug and someone can confirm it. If this is indeed a bug, I assume this applies to all instances and not just SFK, so that is why I selected Generic. 

(Tester - my opinion is that porting to a hostile faction graveyard is clearly incorrect. I don't think it follows that it applies to all instances, however. I thought at first this bug would have something to do with the cross-faction system, but it reproduced on my test system, which is baseline AC.)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Azcobu why "Generic"? shouldn't this be 1-19 ?

**Comment by apav** [comment]
> @Azcobu why "Generic"? shouldn't this be 1-19 ?

I made my issue that this is based on generic because I didn't know if this behavior applies to instances or only SFK. But please feel free to change it if you think that's necessary.

**Comment by Azcobu** [comment]
SFK is 20-29 so it should be that if anything, but I thought the original post's argument that it could be a generic bug affecting more than just SFK to be persuasive, until we know more in any case. But 20-29 is probably equally valid until we know that other instances are affected.

**Comment by FrancescoBorzi** [comment]
fair enough, thanks guys!
