### ISSUE TITLE
{Crash}

### ISSUE THREAD

**Issue by Slash96** [azerothcore/azerothcore-wotlk#553]
**Description**: this crash happens when a lot of players start joining BG at the same time

**Branch(es)**:  master 

**AC hash/commit**:  f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Operating system**:  Ubuntu Trusty

**Modules**:  Transmogrify

Crash Logs:

http://paste.ubuntu.com/25312344/
http://paste.ubuntu.com/25312345/
http://paste.ubuntu.com/25312349/
http://paste.ubuntu.com/25312350/

**Comment by Viste** [comment]
you get 0 in group leader need more info about core. Do you use some mods?

**Comment by Demonid** [comment]
These crashes were caused by custom code.

**Comment by ShinDarth** [comment]
please try to reproduce it without your customisations
