### ISSUE TITLE
Server stuck

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5535]
## CURRENT BEHAVIOUR:
The server will be stuck in about 4-5 hours

After 4 hours of run
![image](https://user-images.githubusercontent.com/18187177/116504757-a8efc980-a8eb-11eb-8f98-481e0259e8a0.png)
After 5 hours of run
![image](https://user-images.githubusercontent.com/18187177/116504773-b1480480-a8eb-11eb-8053-18e9a507e553.png)

![image](https://user-images.githubusercontent.com/18187177/116504817-cf156980-a8eb-11eb-8c5e-44dc5d9a6cb0.png)

## STEPS TO REPRODUCE THE PROBLEM:
1. run worldserver
2. Maybe you need a lot of players online

## AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/28ce1e921921a1d04f718056583c9b62dc219edf

## OPERATING SYSTEM:
ubuntu 20.04

## MODULES:
mod-anticheat
mod-multi-client-check

Maybe it's because of this commit
https://github.com/azerothcore/azerothcore-wotlk/commit/4af4cbd3d966a05c584f4b6c63f69517dad0677d

Because I tested it before https://github.com/azerothcore/azerothcore-wotlk/commit/b2861be1cd623182fd9e900c9ccfe8e063f28d8e For a week, no problem was found

It was upgraded from b9e84d8 to 28ce1e9 that the server stuck

**Comment by mpfans** [comment]
After restarting the server, it ran for 2 hours. Memory usage increased from 5% to 58.9%
![image](https://user-images.githubusercontent.com/18187177/116513123-b1e89700-a8fb-11eb-9d71-4c697d14a1e2.png)
There is not much difference in the number of players online
![image](https://user-images.githubusercontent.com/18187177/116513228-d5134680-a8fb-11eb-840c-58ebd354940d.png)

**Comment by mpfans** [comment]
After restarting the server, it ran for 3.5 hours. Memory usage increased from 5% to 85.9%
![image](https://user-images.githubusercontent.com/18187177/116522987-553fa900-a908-11eb-9f3d-ff950f802c4c.png)

**Comment by FrancescoBorzi** [comment]
@UltraNix can you please have a look at this? I'm not sure if one of the big reworks done lately is causing this

**Comment by FrancescoBorzi** [comment]
also @Winfidonarleyan please check the following:

Maybe it's because of this commit
https://github.com/azerothcore/azerothcore-wotlk/commit/4af4cbd3d966a05c584f4b6c63f69517dad0677d

Because I tested it before https://github.com/azerothcore/azerothcore-wotlk/commit/b2861be1cd623182fd9e900c9ccfe8e063f28d8e For a week, no problem was found

It was upgraded from b9e84d8 to 28ce1e9 that the server stuck

**Comment by UltraNix** [comment]
It might be everything.
@mpfans Maybe consider running with Valgrind?

**Comment by mpfans** [comment]
> unning with Valgri

Please show me how to use Valgrind in discord

**Comment by Hacki95** [comment]
Might be worth knowing, how many players were online?

**Comment by mpfans** [comment]
> Might be worth knowing, how many players were online?

The picture above shows the number of players online

**Comment by Hacki95** [comment]
> 
> 
> > Might be worth knowing, how many players were online?
> 
> The picture above shows the number of players online

You are right, oversaw that.

**Comment by mpfans** [comment]
After restarting the server, it ran for 4.5 hours. Memory usage increased from 5% to 92%

![image](https://user-images.githubusercontent.com/18187177/116531698-0a2a9380-a912-11eb-8134-c66704f9cbd9.png)


Now players have been randomly kicked out of the server, and then log in again will be stuck

**Comment by Kitzunu** [comment]
Mem leak somewhere I guess

**Comment by Winfidonarleyan** [comment]
Bad query, bad db api, mod anticheat :/

**Comment by UltraNix** [comment]
@Winfidonarleyan I think that might be related to latest changes to threading.

**Comment by UltraNix** [comment]
I found some memleaks, but they are quite old. Tomorrow another shot.

**Comment by UltraNix** [comment]
It seems that it's been fixed. 4-5 hours more and I will convert it to normal PR.
