### ISSUE TITLE
Rooting a fleeing NPC teleports that unit to its target location

### ISSUE THREAD

**Issue by chaodhib** [azerothcore/azerothcore-wotlk#5538]
## CURRENT BEHAVIOUR:

Rooting an NPC (using a mage's Nova for example) when that NPC is fleeing leads to the NPC being teleported to its target location (another NPC to ask for help).

## EXPECTED BLIZZLIKE BEHAVIOUR:

Rooting a NPC shouldn't cause any teleport. 

## STEPS TO REPRODUCE THE PROBLEM:

1. Fight with a NPC that has allies nearby and that has a fleeing mechanic when its HP is low enough.
2. Damage the NPC until it flees
3. Then root the NPC. That NPC will teleport.

## EXTRA NOTES:

The behavior was observed in the current version of ChromieCraft (91081f4ad8fed98d7bdc9c0ae13d05c86032df9f)

**Comment by Si1ker** [comment]
![image](https://user-images.githubusercontent.com/61223313/116645250-9fd61b00-a932-11eb-9ae7-102aa741d6da.png)

Confirmed.. wtf  O_o !
