### ISSUE TITLE
Shadowmeld Sets PVP Flag in Alliance Territories [$5]

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5541]
## CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/483

Using Night Elf's Shadowmeld racial spell (https://wowgaming.altervista.org/aowow/?spell=58984) flags the player for PvP in Alliance capital cities and starting zones. It's not 100% consistent, as documented below - small parts of Darnassus and Azuremyst Isle did not trigger this - but almost everywhere in any of the Alliance green zones usually did.

Tested in:
Alliance capital cities -  Darnassus, Stormwind, Ironforge, Exodar
Newbie zones - Teldrassil, Elwynn Forest, Dun Morogh, Azuremyst Isle 

Behavior recorded while inside / outside Stormwind:
https://youtu.be/A-XKpimBUl4
https://youtu.be/Ab9Ndtl5jS4

Further notes from @Tachtzehn:
Was actually experiencing this yesterday while leveling in Teldrassil before creating my GitHub account. After testing with at least 30 attempts, mostly in zones Teldrassil and Darnassus, the bug occurs regardless of character class/gender, and doesn't seem to be affected by whether or not the player is targeting something.

It does appear to trigger based on the player's location, but it's not necessarily related to the zone or minimap header, as there are areas in Teldrassil and Darnassus that will both trigger and not trigger the bug, and also sections of the map with the same header where the bug will trigger and not trigger ("Shadowglen" header at the player's starting location vs. "Shadowglen" header on the road leading to the starting area's exit south of Aldrassil).

In Darnassus, it's harder to find a place where Shadowmeld doesn't flag you for pvp, though I did find that standing between these 2 NPCs in the east Temple Gardens room before using Shadowmeld doesn't trigger the bug, while standing on the top step of the entryway will trigger it, as referenced by these screenshots.
![WoWScrnShot_042921_011855](https://user-images.githubusercontent.com/83389835/116520631-96987000-a898-11eb-9ed4-33d781895abe.jpg)
![WoWScrnShot_042921_020747](https://user-images.githubusercontent.com/83389835/116520664-a021d800-a898-11eb-99b4-8dda40432ddc.jpg)

Thanks to @NidaleeLiadrin and @Tachtzehn for documenting this.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Shadowmeld should not flag you for PVP.

## SOURCE:

N/A.

## STEPS TO REPRODUCE THE PROBLEM:

1. create a new Night Elf character
2. run forward until the minimap header text changes to "Aldrassil" (for some reason, there's a radius around the starting location where this bug will not occur, that's why running forward is necessary.)
3. now use Shadowmeld and you will now be flagged for PVP:

![WoWScrnShot_042921_222045](https://user-images.githubusercontent.com/81782124/116553418-41606b00-a939-11eb-9a25-3ac3b6df63ba.jpg)

## EXTRA NOTES:

N/A.

## AC HASH/COMMIT:

rev. e02d5f4ae4be 2021-04-29 01:31:17 -0700 

## OPERATING SYSTEM:

Linux Mint 20.1

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by Branel** [comment]
Confirmed
