### ISSUE TITLE
[NPC] SFK - Haunting Spirits AI Glitch

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5542]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/485

The [Haunted Servitor](https://wotlkdb.com/?npc=3875) mobs in SFK cast the [Haunting Spirits](https://wotlkdb.com/?spell=7057) curse, which occasionally summons [spirits](https://wotlkdb.com/?npc=4958) to attack you. However despite being hostile, they don't attack unless they are first attacked, so they effectively act like neutral mobs. 

Tester notes - confirmed this, the spirit will just stand there and do nothing as long as you don't move. However, if you move out of melee range, they will follow you and suddenly start attacking, as if being forced to move resets them somehow. Their nameplate/selection ring colour is red the whole time, so they are hostile.

![haunting spirits](https://user-images.githubusercontent.com/8137930/116530549-28f63f00-a8ac-11eb-85c2-8d1559981248.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Haunting Spirits should immediately attack you when summoned.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to SFK and have the curse applied on you. Wait for these spirits to get summoned.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Probably was occasionated by https://github.com/azerothcore/azerothcore-wotlk/pull/4893
But a small SAI addition should make it work a little bit more accurately, nothing too complicated.
