### ISSUE TITLE
db-assembler don't override default options with the user defined settings

### ISSUE THREAD

**Issue by jordigil** [azerothcore/azerothcore-wotlk#5553]
## CURRENT BEHAVIOUR:

The db-assembler don't override the default options "conf/dist/config.sh" with the user settings located at "conf/config.sh"

## EXPECTED BLIZZLIKE BEHAVIOUR:

The db-assembler should override default options (conf/dist/config.sh) with the user defined options (conf/config.sh)

## SOURCE:

N/A

## STEPS TO REPRODUCE THE PROBLEM:

1. Copy "conf/dist/config.sh" to "conf/config.sh"
2. Modify some values, like mysql port
3. See the db-assembler using only the default values.

## EXTRA NOTES:

Can someone test if it occurs in unix systems?

## AC HASH/COMMIT:

2d1e2f255f2feea79507ef259dc0232f4e1cc8b7

## OPERATING SYSTEM:

Windows 10 Pro 64-bit + Git For Windows

## MODULES:

None

## CUSTOMIZATIONS:

I'm using non-standard port for mysql.

**Comment by Yehonal** [comment]
Can you upload your /conf/config.sh file? (remove sensible information first)

**Comment by jordigil** [comment]
its just the same as /conf/dist/config.sh but with port changed from 3306 to 3307

[config.sh.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6408576/config.sh.txt)

**Comment by Yehonal** [comment]
Do not use variable substitution there, assign the string directly

Il sab 1 mag 2021, 02:26 Jordi Gil ***@***.***> ha scritto:
