### ISSUE TITLE
[DB] Loading Game Event Creature Data error

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#557]
**Description:** 
On startup of worldserver.exe this error is displayed in red text.

> Loading Game Event Creature Data...
`game_event_creature` game event id (71) is out of range compared to max event id in `game_event`

**Expected behavior:** 
I want a clean startup with no red errors. I think every release forward should start with no errors.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by ShinDarth** [comment]
`I want a clean startup with no red errors.`

that sounds a bit imperative ;D

`I think every release forward should start with no errors.`

but I agree, and I don't understand why during the recent years people stopped caring about it. After all most of them can be resolved quite easily.

The ideal condition is to not have **any** startup error, and always check that any DB content or core change does not add any startup errors.

**Comment by StygianTheBest** [comment]
> that sounds a bit imperative ;D

I'm guessing most users would want the same thing! :)

> The ideal condition is to not have any startup error, and always check that any DB content or core change does not add any startup errors.

Agreed. You would think if a change caused an error like this it would be resolved before it was accepted.

**Comment by Yehonal** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/1903bfc43d53bc9b6e129129966ca9c0c22a4d97

closed
