### ISSUE TITLE
Sometimes command .account set gmlevel  does not work

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5574]
I'm not exactly sure how to reproduce this but it happened to me 3 times already:

Using the `.account set gmlevel` command has no effect and it does not save the account in the `account_access` table.

Maybe it has to do with the account being offline/online in a certain moment, I haven't investigated this too much but there is definitely something wrong here and not necessarily easy to reproduce.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

**Comment by Kitzunu** [comment]
Hmm Ive never encountered anything like it

**Comment by Sedatyf** [comment]
Hmmm me neither I think

**Comment by FrancescoBorzi** [comment]
I noticed that when you use the command, the `account_access` table does not get updated

**Comment by Kitzunu** [comment]
cannot reproduce
![image](https://user-images.githubusercontent.com/24550914/152608250-9436c1c6-16cb-4c36-b652-129980cefd8f.png)
