### ISSUE TITLE
[DB] Loading Creature loot templates error

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#558]
**Description:** 
On startup of worldserver.exe this error is displayed in red text.

> Loading Creature loot templates...
Table 'creature_loot_template' entry 1 isn't creature entry and not referenced from loot, and then useless.
Table 'creature_loot_template' entry 1175 isn't creature entry and not referenced from loot, and then useless.

**Expected behavior:** 
I want a clean startup with no red errors. I think every release forward should start with no errors.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by ShinDarth** [comment]
just remove that entry from the table.

The warning means that there is a loot for creature with entry 1, but actually there isn't any creature with that id.

I guess something like: `DELETE FROM creature_loot_template WHERE entry = 1` should do the trick

**Comment by StygianTheBest** [comment]
@ShinDarth I wanted to post all of these so they could be tracked and so other users could make sense out of it. Thanks for the tip. I did investigate, but I didn't want to make a change before I loaded a clean master database and made sure it wasn't something specific to my sandbox.

**Comment by ShinDarth** [comment]
yes I agree with reporting those issues, I just suggested a way to fix :D

**Comment by StygianTheBest** [comment]
Removing this entry creates more SourceGroup errors. Quite a few actually. Might not be the best route to fix.
