### ISSUE TITLE
[Movement] Malygos does not land & Brann Bronzebeard falls off of Algalon's Bridge during initial RP

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#5582]
## CURRENT BEHAVIOUR:
1. Malygos does not land to engage the raid during phase 1 of his encounter.  Instead he flies down and remains in his flying animation while fighting players.
2. When you open the door to Algalon's room, Brann Bronzebeard falls through the bridge.

## EXPECTED BLIZZLIKE BEHAVIOUR:
1. Malygos is supposed to land and act as if he is on the ground during phase 1 of his encounter.
2. Brann Bronzebeard is supposed to walk over to the bridge and do some roleplay.

## STEPS TO REPRODUCE THE PROBLEM:
1. .tele nexus
2. go into Eye of Eternity and begin the fight
3. Watch P1
4. .tele ulduar
5. go into ulduar and start the Algalon roleplay
6. watch brann fall through the floor

## AC HASH/COMMIT:

2d609e9e48b2

**Comment by Kitzunu** [comment]
Report only one issue per report. Especially when it is about two different encounters

**Comment by Voxstrasza** [comment]
> 
> 
> Report only one issue per report. Especially when it is about two different encounters

It's the same thing.  I'm not opening another one.  Close if you want to.

**Comment by Kitzunu** [comment]
The reason why we do not report several issues within one report is because it's harder to track what is done.
