### ISSUE TITLE
Node spawns in Thousand Needles

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#5584]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

These node spawns are too close and can spawn simultaneously:
![image](https://user-images.githubusercontent.com/71938210/116794764-f2007300-aacf-11eb-87b3-6748fdc5e328.png)
![image](https://user-images.githubusercontent.com/71938210/116794826-6e935180-aad0-11eb-9d01-15ee6edaf740.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should be pooled or one removed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Second image is invalid in my side...

### GUID 4690

![image](https://user-images.githubusercontent.com/61223313/116822382-bf8c5f80-ab3b-11eb-972a-aa917ce737bb.png)


### GUID 5397

![image](https://user-images.githubusercontent.com/61223313/116822397-cf0ba880-ab3b-11eb-902a-324d7a2f0de2.png)

**Comment by 55Honey** [comment]
GUID 5397 > i think it says 5347 in my picture

**Comment by Si1ker** [comment]
Ups 😹 

Ok, so..

### GUID 5347
![image](https://user-images.githubusercontent.com/61223313/116822622-03cc2f80-ab3d-11eb-9150-bd3db47918ef.png)


### GUID 4690

![image](https://user-images.githubusercontent.com/61223313/116822643-1f373a80-ab3d-11eb-801c-349976cf96af.png)

**Comment by 55Honey** [comment]
That's strange, they were Like 5m apart in ChromieCraft *shrug*
