### ISSUE TITLE
Feign Death Not Clearing Target If Partied With Attacker [$5]

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5586]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/502

When using [Feign Death](https://wowgaming.altervista.org/aowow/?spell=5384) the player that is targetting you won't lose their target if they are in a party with you. The combat log for the attacker still shows "\<playername\> died" but they keep attacking.

In more normal cases, such as PVP or duels where you are not in a party with your attacker, Feign Death works correctly.

[Video Proof](https://www.youtube.com/watch?v=Lllj_4JiB6Y)

![WoWScrnShot_050221_124108](https://user-images.githubusercontent.com/81782124/116800849-cd45e300-ab43-11eb-8071-6cc5b9dfe828.jpg)

Feign working correctly in PVP:
![WoWScrnShot_050221_123448](https://user-images.githubusercontent.com/81782124/116800875-0716e980-ab44-11eb-9c59-a686adf8063c.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Feign should work in parties just like it works everywhere else.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Party with a hunter and attack/cast on him
2. Make him use Feign Death
3. See how the cast/attack goes through

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Helias do not forget the project :)

**Comment by UltraNix** [comment]
Source from Blizz?
It's clientside that Feign Death causes deselection.

**Comment by Azcobu** [comment]
"This will cause other players to drop you as their target" and "players will lose targeting if they have you targeted when you feign" (https://wowpedia.fandom.com/wiki/Feign_Death?oldid=3034835) Can't see any exemptions about party members in the article. Think I'd want to see a source that says it should work differently in this one specific case to the way it works everywhere else. Otherwise, isn't the default assumption that it is consistent?

Also found an interesting article talking about the 2019 mechanics of FD where they compared the vanilla implementation to the 2019 one. Obviously not directly applicable to AC, but interesting to see the approach: https://www.icy-veins.com/forums/topic/45921-major-feign-death-bug-hotfixed/

**Comment by UltraNix** [comment]
I think that comments are about enemy players/NPCs, as using FD against friendly players is useless.

**Comment by Azcobu** [comment]
Well, I did find one comment in a old thread here where someone agrees with you: https://github.com/ccshiro/cc-buglist/issues/2002#issuecomment-171449315

There's no evidence or sources given, but whoever this person is, they did seem to think it worked the way you say. Normally I'd say evidence from some random person with no details, no verification and the wrong time period was entirely worthless, but thought I should mention it.
