### ISSUE TITLE
NOTICE: file <.../conf/config.sh> has not been found, you should create and configure it.

### ISSUE THREAD

**Issue by suprsokr** [azerothcore/azerothcore-wotlk#5587]
## CURRENT BEHAVIOUR:

When following https://www.azerothcore.org/wiki/Install-with-Docker after cloning azerothcore-wotlk commit aee1351f1282cb0e6ee902b19423a4210fed056e on Windows 10 and running this command:
`./acore.sh docker client-data`
this notice occurs:
`NOTICE: file <.../conf/config.sh> has not been found, you should create and configure it.`

## EXPECTED BLIZZLIKE BEHAVIOUR:

This notice should not occur.

## FIX
Currently, the config.sh file is in /conf/dist/config.sh and just needs to be moved up to /conf in order for Docker/the script to discover the file. Doing this removed the notice for me.

## AC HASH/COMMIT:

aee1351f1282cb0e6ee902b19423a4210fed056e

## OPERATING SYSTEM:

Windows 10

## MODULES:

No

## CUSTOMIZATIONS:

No

**Comment by FrancescoBorzi** [comment]
cc @Yehonal

**Comment by suprsokr** [comment]
Now that I have worked with this project more, I understand that this is apart of how configuration files work broadly in the project. The idea is that /conf/dist/config.sh is the provided defaults, and you can override those defaults by creating a /conf/config.sh. This warning is perhaps a bit terse, but this is not a bug.

More information about how configuration files work here: https://www.azerothcore.org/wiki/how-to-work-with-conf-files
