### ISSUE TITLE
[DB] Loading Skinning Loot template error

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#559]
**Description:** 
On startup of worldserver.exe this error is displayed in red text.

>Loading Skinning Loot templates...
Table 'skinning_loot_template' entry 80102 isn't creature skinning id and not referenced from loot, and then useless.

**Expected behavior:** 
I want a clean startup with no red errors. I think every release forward should start with no errors.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by ShinDarth** [comment]
same as the other one, this time the table is `skinning_loot_template` and the entry is `80102`

**Comment by StygianTheBest** [comment]
> same as the other one, this time the table is skinning_loot_template and the entry is 80102

Deleting that entry triggers many more errors to SourceGroup 1. That source group ID is used quite a bit in the table, so I'm not sure this is the best route.
