### ISSUE TITLE
Faction change: Quests completeable twice

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#5592]
## CURRENT BEHAVIOUR:

The current `player_factionchange_quests` contains only quest ids from 7163 and up.
Currently on ChromieCraft people do the quests https://wotlkdb.com/?quest=3636 and https://wotlkdb.com/?quest=3341 which belong to opposing factions.

## EXPECTED BLIZZLIKE BEHAVIOUR:

The quests should exclude each other from being completed.

## STEPS TO REPRODUCE THE PROBLEM:

1. Complete https://wotlkdb.com/?quest=3636
2. Faction change
3. Complete https://wotlkdb.com/?quest=3341
4. Get both rewards.

## EXTRA NOTES:

Found this:
![image](https://user-images.githubusercontent.com/71938210/116809795-362b5c00-ab40-11eb-876b-725391f614b8.png)

Source: https://wowpedia.fandom.com/wiki/Faction_Change#Quests_and_Achievements

https://xpoff.com/threads/worn-running-boots-question.7884/

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Kitzunu there is a problem with the github-actions bot about flagging issues like this as invalid while the commit hash is here (it's just from another fork). Mind having a look at this?

**Comment by Kitzunu** [comment]
On the original edit there were no hash

**Comment by Kitzunu** [comment]
See https://github.com/azerothcore/azerothcore-wotlk/actions/runs/804291968 for https://github.com/azerothcore/azerothcore-wotlk/issues/5595 didn't fail. so nothing wrong

**Comment by FrancescoBorzi** [comment]
aaah ok, nevermind then. Thanks
