### ISSUE TITLE
Need to restart the server to spawn new Gameobject 

### ISSUE THREAD

**Issue by Miithrandiir** [azerothcore/azerothcore-wotlk#5597]
## CURRENT BEHAVIOUR:

i've a problem with the gameobject spawn, in fact when i spawn a gameobject it doesn't appear, and the message when i spawn this GO is about another GO which is already spawn in the map. (Coord are goods but the GUID is already taken (See SOURCE))

## EXPECTED BLIZZLIKE BEHAVIOUR:

The normal behavior will be to spawn the wanted gameobject where the player is 

## SOURCE:

![image](https://user-images.githubusercontent.com/30532637/116814756-aa72f900-ab5a-11eb-9be1-08e397c236ea.png)
Nothing where my player is
![image](https://user-images.githubusercontent.com/30532637/116814782-c1b1e680-ab5a-11eb-8c90-5c9121c25d16.png)

## STEPS TO REPRODUCE THE PROBLEM:

1. Search for a gameobject you want to spawn (.lo go chair)
2. .gob add 112265

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5996

**Comment by arielcami** [comment]
> #5996

Thank you, i didn't know it was already posted.

**Comment by arielcami** [comment]
Confirmed.

**Comment by FrancescoBorzi** [comment]
@arielcami can you please test https://github.com/azerothcore/azerothcore-wotlk/pull/6001 ?

**Comment by arielcami** [comment]
> @arielcami can you please test #6001 ?

Ok I'll test it now.

**Comment by arielcami** [comment]
> @arielcami can you please test #6001 ?

Tested #6001
Worked flawlessly.
[AzerothCore rev. 147a3e1fcc37 2021-05-22 10:32:19 +0200 (pr-6001 branch)

Right before running .gobject add command
![WoWScrnShot_052221_070302](https://user-images.githubusercontent.com/71854140/119225881-07176300-bacc-11eb-9826-5ca63fe1f343.jpg)

After running the command
![WoWScrnShot_052221_070318](https://user-images.githubusercontent.com/71854140/119225890-11396180-bacc-11eb-8aa5-a33361efff4d.jpg)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/8ac74e475f26f24329129d7cc32088c4af88c862
