### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by hero2880** [azerothcore/azerothcore-wotlk#56]
**Description**:yesterday, compiling a V1 version, many mistakes

**Current behaviour**: mainly CORE logo (a few large characters,in main.cpp...) related to malformed, and pathrandomgenerator.cpp errors,Can not generate the worldserver.

**Branch(es)**: 1.x / 2.x (Select the branch(es) affected by this issue) 

**AC hash/commit**:  

**Modules**:  Are you using modules? if yes, list them

**Operating system**:  win10

**Comment by Yehonal** [comment]
Please fill all fields and provide a pastebin with errors

This issue is not written properly, closed

**Comment by Yehonal** [comment]
Moreover, I've successfully compiled on both windows and linux. Please
clean your build
