### ISSUE TITLE
Cannot Create Map Extraction Tools on Linux

### ISSUE THREAD

**Issue by vratam** [azerothcore/azerothcore-wotlk#5600]
## CURRENT BEHAVIOUR:

I have been using the same vmaps since September or so of last year, when I extracted them from the client using the tools gained through compiling the source. Once I had the tools, I disabled the flag (i.e., DTOOLS=0) for all further compilations. Recently, having newly compiled, everything went fine, but when I started the world server, I got this:

`VMap file '/home/cycas/games/wotlk/azerothcore/maps/vmaps/000.vmtree' is missing or points to wrong version of vmap file. Redo vmaps with latest version of vmap_assembler.exe.`

First I should state, that the directory is correct AND the 000.vmtree file exists. So I figured I would do as it commands and redo the vmaps with the latest version of vmap_assembler.exe. I turned on the flag, which resulted in:

```
...
[ 22%] Linking CXX executable mapextractor
/usr/bin/ld: CMakeFiles/mapextractor.dir/System.cpp.o: in function `ExtractCameraFiles(int, bool)':
System.cpp:(.text+0x6868): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: CMakeFiles/mapextractor.dir/System.cpp.o: in function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
System.cpp:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x8f): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/tools/map_extractor/CMakeFiles/mapextractor.dir/build.make:192: src/tools/map_extractor/mapextractor] Error 1
...

```
This shows the first error, more follow, but obviously the tools are not being generated and halting the compile. Extraction tools should be produced, yes?

## SOURCE:

`AzerothCore revision            : d04488351347+ 2021-04-19 15:18:17 +0200 (master branch)
`
## STEPS TO REPRODUCE THE PROBLEM:

`cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS=1 -DSCRIPTS=1
`
## EXTRA NOTES:

cmake v3.20.1
clang v7.0.1

## AC HASH/COMMIT:

Best I could tell: 47378ad

## OPERATING SYSTEM:

GNU/Linux, Debian 10

## MODULES:

none

## CUSTOMIZATIONS:

none

**Comment by Nolin7777** [comment]
Try this https://github.com/azerothcore/azerothcore-wotlk/pull/5446

**Comment by vratam** [comment]
@Nolin7777 - I assume that you mean to try and compile Winfidonarleyan's repo, which I did. Receiving essentially the same errors...

```
...
[ 22%] Linking CXX executable mapextractor
/usr/bin/ld: CMakeFiles/mapextractor.dir/System.cpp.o: in function `ExtractCameraFiles(int, bool)':
System.cpp:(.text+0x6868): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: CMakeFiles/mapextractor.dir/System.cpp.o: in function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
System.cpp:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x8f): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/tools/map_extractor/CMakeFiles/mapextractor.dir/build.make:194: src/tools/map_extractor/mapextractor] Error 1
make[1]: *** [CMakeFiles/Makefile2:899: src/tools/map_extractor/CMakeFiles/mapextractor.dir/all] Error 2
...
```

**Comment by Winfidonarleyan** [comment]
What version clang?

**Comment by vratam** [comment]
@Winfidonarleyan - I have gcc v8.3.0 installed (both GNU C & C++).

**Comment by catlinux** [comment]
I have some problem.

Distro: Debian buster
Kernel: 4.19.0-16-amd64
cmake: 3.18.4
gcc: (Debian 8.3.0-6) 8.3.0
g++: (Debian 8.3.0-6) 8.3.0
clang: 7.0.1-8+deb10u2

**Comment by Methatronc** [comment]
Same here, same config than catlinux

**Comment by Winfidonarleyan** [comment]
https://stackoverflow.com/questions/66223241/how-to-install-clang-11-on-debian

**Comment by Helias** [comment]
debian 8 it's really old :S I strongly recommend you to use debian 10.

Debian 8 has been released 5 years ago, it's a bit old :sweat_smile:

**Comment by Methatronc** [comment]
@Winfidonarleyan Thanks, I'll try that, the wiki said clang 7 so I'll update it if that was the culprit.
@Helias debian buster = 10, the 8 is the gcc version, but I approve debian 8 is quite outdated ;)

**Comment by Winfidonarleyan** [comment]
Please use the newest OS and the newest clang

**Comment by Methatronc** [comment]
By newest OS you mean Sid ? I'd prefer to stay on stable :/

**Comment by Methatronc** [comment]
Tried with clang version 11.1.0 : 
`cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -DWITH_WARNINGS=1 -DTOOLS=1 -DSCRIPTS=1`
Still the same error on my latest os stable release

**Comment by Kitzunu** [comment]
Works
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/5705185539/job/15459572907
