### ISSUE TITLE
Ritual Channeling Spells Infinite Cooldown

### ISSUE THREAD

**Issue by Gozzim** [azerothcore/azerothcore-wotlk#5603]
## CURRENT BEHAVIOUR:

- The cooldown of the spells Ritual of Souls, Ritual of Doom and Ritual of Refreshment does not get reset if the channeling time runs out and the spell casting fails.

## EXPECTED BLIZZLIKE BEHAVIOUR:

- The cooldown should be reset if the channeling and therefore spell cast finally fails.

## SOURCE:

https://youtu.be/wq363nXr9Tg

## STEPS TO REPRODUCE THE PROBLEM:

1. Cast one of the 3 affected ritual/channeling spells.
2. Wait until the channeling runs out.
3. Check cooldown/Try casting again.

## EXTRA NOTES:

I haven't finished debugging, but have my guesses.
- It might just be a visual issue on the client side due to the initial and then never overriden infinity cooldown. Especially with no spell in the chain counting as aura and a relog fixing the state.
- The cooldown might never start or get canceled due to the spell never gaining the finished or canceled state. Indication for this is the cooldown not being able to get reset in any case.
- Was also going to look deeper into the ProhibitSpellCooldown and RecoveryTime sections, but haven't gotten to that so far.

## AC HASH/COMMIT:

719b541e10ce2194c4b1282a0631f088f4317780

## OPERATING SYSTEM:

Debian 10

## MODULES:

None

## CUSTOMIZATIONS:

- Clean server clone
- Removed any client modifications

**Comment by Tereneckla** [comment]
Still happening on https://github.com/azerothcore/azerothcore-wotlk/commit/23f58016d078e922ebbc378f28223d6d0a19693d
