### ISSUE TITLE
Orphan Week - You Scream, I Scream - Ice Cream Vendor not Phased in

### ISSUE THREAD

**Issue by PerryCS** [azerothcore/azerothcore-wotlk#5606]
## CURRENT BEHAVIOUR:

Get Quest, Pop out Orphan using the whistle, go to Mage Area in Stormwind, the vendor to buy Ice Cream is not outside the Blue Recluse.

## EXPECTED BLIZZLIKE BEHAVIOUR:

The Vendor is right outside the Blue Recluse.

## SOURCE:

A youtube video showing where the vendor is...

https://www.youtube.com/watch?v=k5oeo_XWyi8

## STEPS TO REPRODUCE THE PROBLEM:

1. Get Orphan Quests near Cathedral
2. Do 3-4 quests before getting You Scream, I Screem, go to mage area, go to Blue Recluse.
3. Vendor is not there

## AC HASH/COMMIT:

commit 8b45f2520d5966b53508c06b55b06482837af9e0 (grafted, HEAD -> master, origin/master, origin/HEAD)

## OPERATING SYSTEM:

Ubuntu 20.04.2 LTS

## MODULES:

no

## CUSTOMIZATIONS:

no

**Comment by Si1ker** [comment]
@PerryCS The video you linked is from 2015, that seems to be another patch/content.

Wowhead classic states the location we have is correct.

Classic Wowhead:

![image](https://user-images.githubusercontent.com/61223313/116922889-30527b00-ac13-11eb-8328-9a74bac5fe9d.png)
source: https://classic.wowhead.com/npc=14481/emmithue-smails



AzerothCore:

![image](https://user-images.githubusercontent.com/61223313/116922877-29c40380-ac13-11eb-92d8-73e6b5eb5b7f.png)
![image](https://user-images.githubusercontent.com/61223313/116923008-50823a00-ac13-11eb-97cd-e1b300be2dc5.png)

**Comment by PerryCS** [comment]
OH!   Had no idea.  I'll be more careful in the future before posting.  Thank you!   

I don't know where to find information like this so I guess I'll ask here...   one quick question not related to the problem I had above... I noticed there is a TON of game problems after around say Nov 2020 or maybe before that date.  Seemed to be an explosion of problems in the game (based on the massive number of tickets I see).  I remember reading months earlier someone wanted to redo the databases or streamline the code to make moving forward easier... I know sweeping changes like that can cause problems and introduce errors as the codebase is fine tuned again...

How is the project now?  Is it playable?  I'm scared to update to the latest Master.  The one I am on right now seems to work 99.99% of the time.  Minor glitches where people walk through the floor but most things work it seems.

How playable is the latest Master?  I am also curious what triggered the massive flood of problems in the game (from the pages and pages of problems being posted and unfixed as of this writing)... and it seemed to happen after 2-3 pages of some big change all from 1 person months ago.

Thank you for your time.

**Comment by Kitzunu** [comment]
Master is good, several servers uses the latest master.

But if you update you need to think of 2 things.

- Get the new maps, some work for vmaps or whatever has been done to be better
- The DB has been squashed which means you first have to follow https://www.azerothcore.org/wiki/Upgrade-from-pre-3.0.0-to-latest-master
