### ISSUE TITLE
[DB] Loading Scripts error

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#561]
**Description:** 
On startup of worldserver.exe this error is displayed in red text.

> Loading Scripts..
Script named 'spell_gen_crab_disguise' does not have a script name assigned in database.

**Expected behavior:** 
I want a clean startup with no red errors. I think every release forward should start with no errors.

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by DarkmoonRabbit** [comment]
Improve in...

**Comment by StygianTheBest** [comment]
> Improve in...

What is this supposed to mean?

**Comment by Inifield** [comment]
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (46337, 'spell_gen_crab_disguise');

**Comment by sucofog** [comment]
> What is this supposed to mean?

Give me some love daddy!!
