### ISSUE TITLE
[Quest] The Missing Diplomat - Spawned NPCs Not Attacking

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5610]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/510

The quest 'The Missing Diplomat' (quest 1447, https://wotlkdb.com/?quest=1447) spawns 2 Old Town Thugs (https://wotlkdb.com/?npc=4969) as the fight begins. However, they just stand there during the fight despite being in easy aggro range. If you move even closer towards them they will aggro though.

![](https://cdn.discordapp.com/attachments/800766186694377483/838342067167690762/unknown.png)

![WoWScrnShot_050321_230521](https://user-images.githubusercontent.com/81782124/116883351-acc17a00-ac64-11eb-9d94-b0b888f71f43.jpg)

It reminded me of this issue - https://github.com/azerothcore/azerothcore-wotlk/issues/5542 - where spawned mobs were also ignoring the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Youtube video - https://www.youtube.com/watch?v=otbvMtInvNc - shows the thugs spawning closer to the player and attacking immdiately.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 1246 (the one before the problem one, to talk to Dashel Stonefist)
2. Find him (unfortunately .go c 4961, his creature entry guid, doesn't seem to work for some reason.)
3. Start the quest he offers.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
seems related to the known issue where npcs ignore players until they move

**Comment by Si1ker** [comment]
I was able to fix some stuff but is not completely blizzlike yet. 😭 
(better than before tho) 🐱
