### ISSUE TITLE
Feralas is missing Ore Pooling

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#5619]
## CURRENT BEHAVIOUR:

- All Ore nodes in Feralas are currently not pooled, they all spawn simultaneously.

## EXPECTED BLIZZLIKE BEHAVIOUR:

- They should all be in a pool and only a certain amount of them should spawn at a time.

## STEPS TO REPRODUCE THE PROBLEM:

1. Check the Chests in Feralas
2. 
3. 

## AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/0a571973d74554eaa5b0ac4e9d4468844a477ebe

## OPERATING SYSTEM:

Ubuntu 20.04

**Comment by Azcobu** [comment]
Also see https://github.com/azerothcore/azerothcore-wotlk/issues/6099
