### ISSUE TITLE
serious problem Going Into The Ground npc

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5622]
## CURRENT BEHAVIOUR:

Many npcs
They go underground
This is a bug
Not just in this instance
In more than these instances
There is this problem

## EXPECTED BLIZZLIKE BEHAVIOUR:

That's right
NPCs should not
Go underground

## SOURCE:

![WoWScrnShot_050421_103638](https://user-images.githubusercontent.com/80007195/116966747-22116700-acc6-11eb-8146-56d5ef3bfe68.jpg)
![WoWScrnShot_050421_103647](https://user-images.githubusercontent.com/80007195/116966751-2473c100-acc6-11eb-8998-86c054415889.jpg)
![WoWScrnShot_050421_103710](https://user-images.githubusercontent.com/80007195/116966756-250c5780-acc6-11eb-90e8-5ef58bca0afb.jpg)

## STEPS TO REPRODUCE THE PROBLEM:

Inside toc
10 people and 25 people
Go and test this problem

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:

mod-transmog
mod-cfbg
mod-duel-reset
mod-guildhouse
mod-mall-teleport
mod-dynamic-xp

**Comment by Kitzunu** [comment]
Cc @Yehonal

**Comment by Yehonal** [comment]
I tried ToC with a GM, is there any procedure to reproduce the problem at 100%? Otherwise it's difficult to debug

**Comment by poryagholami1374** [comment]
> I tried ToC with a GM, is there any procedure to reproduce the problem at 100%? Otherwise it's difficult to debug

It may be from the map file
Send me a healthy map file to try again

**Comment by Yehonal** [comment]
just download the files here: https://github.com/wowgaming/client-data/releases/tag/v10

you can even use the following command: `./acore.sh client-data` , it will download and extract them for you

**Comment by poryagholami1374** [comment]
> just download the files here: https://github.com/wowgaming/client-data/releases/tag/v10
> 
> you can even use the following command: `./acore.sh client-data` , it will download and extract them for you

Because I'm from the same version
I use v10
That you put on the site
Isn't it fixed>?

**Comment by Yehonal** [comment]
if you are using those ones so it's fine and probably we have that bug, I'll try to reproduce it. Meanwhile I hope someone else can confirm it as well

**Comment by poryagholami1374** [comment]
> I tried ToC with a GM, is there any procedure to reproduce the problem at 100%? Otherwise it's difficult to debug

you can
TOC test 5
 dk When the bird is thrown, the man must go to heaven
But the man goes to the ground
Even npc that set up bass
Goes to earth

**Comment by poryagholami1374** [comment]
![WoWScrnShot_050421_161851](https://user-images.githubusercontent.com/80007195/116999198-88ad7980-acf4-11eb-8b91-5db8e9bc42d4.jpg)

**Comment by ilsonlojr** [comment]
On ICC Raging Spirits from LK also sometimes goes underground and suddenly they reappear.

Also if u step on a shadowtrap and fly outside the platform while aggroed by Shambling or Ghouls they will go underground following you dropping.

**Comment by poryagholami1374** [comment]
![WoWScrnShot_050521_023703](https://user-images.githubusercontent.com/80007195/117076010-fc7a7100-ad4a-11eb-8856-2f682ca377ed.jpg)

**Comment by tkn963** [comment]
I can confirm this. Had this happen a few times in various dungeons. The most noticable was Razorfen Kraul. Not entierly sure what triggered it but a mob was hitting me and I couldn’t see it, then while I was moving around the mob suddenly appeared again. Had it happen in SM: Cathedral too.

**Comment by AndyRisn** [comment]
The same is true of Malygos in The Eye of Eternity

**Comment by Delcidx** [comment]
I can confirm this too. On Shadowfang Keep had this issue.
![image](https://user-images.githubusercontent.com/75182283/117499547-994e3180-af38-11eb-92b7-13ea68ff89a7.png)

**Comment by Err0r1** [comment]
Confirmed. LK and LK ghouls

**Comment by Helias** [comment]
did you encounter this with https://github.com/azerothcore/azerothcore-wotlk/pull/4879 ?

**Comment by poryagholami1374** [comment]
> did you encounter this with #4879 ?

What is this about?
This is what they mean
That of the wall inverter
Can it be damaged?
 Or does Level Blink work mage?

**Comment by Err0r1** [comment]
> did you encounter this with #4879 ?

the problem also exists with the PR

**Comment by speedrunz** [comment]
Bump.

**Comment by syssneck** [comment]
I didn't really have this issue in the last two months or so on Chromiecraft. Maybe it's not completely gone, but not as frequent and as bad, as the screenshots make it out to be.

**Comment by UltraNix** [comment]
I thinks it's already gone and fixes by recent fixes to vmaps/mmaps.
