### ISSUE TITLE
Juvenile Snow Leopard Clipping/Pathing Issues

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5629]
## CURRENT BEHAVIOUR:

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/517 and  https://github.com/chromiecraft/chromiecraft/issues/516

A juvenile snow leopard (https://wotlkdb.com/?npc=1199) in Dun Morogh (GUID 3596) spawns and moves towards the nearby road, clipping and stuttering through the treetops. When it reaches the mode, it then follows the local road patrol route and wanders up and down the road exactly like the nearby guards, only deviating to chase critters.

https://user-images.githubusercontent.com/81782124/116997320-cbcf1300-ad1b-11eb-8e98-57229f1d0a6d.mp4

Screenshot showing guard and leopard marching overlaid. Didn't bother to video it because it's ~6 minutes to go back and forth.
![WoWScrnShot_050421_205403](https://user-images.githubusercontent.com/81782124/116997352-d5f11180-ad1b-11eb-8e15-0a030fca5383.jpg)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Less clipping and acting like a guard, more staying on the ground and roaming randomly.

## SOURCE:

Looking at the wotlkdb.com map for this NPC shows no kills on the road or near Kharanos, suggesting it is not meant to be found in that area.

## STEPS TO REPRODUCE THE PROBLEM:

1. .go c 3596 will get you to the right area, although seeing it actually glitch took a few minutes.

## AC HASH/COMMIT:

rev. de23266f04e5 2021-05-03 13:14:22 +0200

## OPERATING SYSTEM:

Linux Mint 20.1

## MODULES:

N/A.

## CUSTOMIZATIONS:

N/A.

**Comment by Si1ker** [comment]
Confirmed with
.go c 3596

![image](https://user-images.githubusercontent.com/61223313/117355688-224d6600-ae70-11eb-8bde-d0603b4a91ca.png)
