### ISSUE TITLE
[FirstKill] Malygos give more firstkills

### ISSUE THREAD

**Issue by TiberiumX** [azerothcore/azerothcore-wotlk#563]
Description:

After a group obtains the first kill to realm the eye of eternity the following Raids continue to obtain this first kill achievement.

I have moved this achievement to disables as output.

Ubuntu 16 LTS
Only use transmorf module and zero scripts or customs

**Comment by ShinDarth** [comment]
where is the commit hash ? please add it

**Comment by poszer** [comment]
Tested, can't confirm this. Anyway thanks for report
