### ISSUE TITLE
[Quest] Galen's Escape - Galen and Enemies Ignore Each Other

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5630]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/522

The escort quest Galen's Escape (https://wotlkdb.com/?quest=1393) has you escort Galen (https://wotlkdb.com/?npc=5391  GUID 40210) from out of a camp of enemies. However, he does not fight his way out, nor does he get attacked during his escort quest.

![WoWScrnShot_050421_215044](https://user-images.githubusercontent.com/81782124/117002948-62eb9900-ad23-11eb-93de-4d51fe166504.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be attacked by nearby enemies, as with any escprt quest. https://www.youtube.com/watch?v=Uxvm_uQvQhQ shows how it should go.

Here are some glorious wowhead comments... :)

_Worst escort quest ever, this guy went right into the encampment, aggroed 4-5 mobs and died... all in like 30 seconds._

_Worst escort ever, no matter what you do he WILL find some way to commit suicide._

_If you release him he runs headlong into any and every mob nearby, and will die in seconds._

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 40210, accept quest.
2. Enjoy a peaceful stroll in the swamp.

##### EXTRA NOTES:

.npc info output:
![WoWScrnShot_050421_214016](https://user-images.githubusercontent.com/81782124/117002052-3b480100-ad22-11eb-926c-802353afc301.jpg)

Quest: https://wowgaming.altervista.org/aowow/?quest=1393
NPC to escort: https://wowgaming.altervista.org/aowow/?npc=5391

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
possible fix https://github.com/ipriver/TrinityCore/commit/0656852081d7d08b50d0527735e04e4dc7d42c24

**Comment by grimgravy** [comment]
@Helias, open a PR and fix it.
