### ISSUE TITLE
[Quest] "Recover the Cargo!" - Objectives Persist After Collection

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5632]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/523

The quest 'Recover the Cargo!' (https://wowgaming.altervista.org/aowow/?quest=11140) needs you click on Shipwreck Debris (https://wowgaming.altervista.org/aowow/?object=186283) using a Salvage Kit. However, when you click Debris, it doesn't go away. So you can finish the entire quest by repeatedly clicking the one piece of debris.

https://user-images.githubusercontent.com/81782124/117005946-fb374d00-ad26-11eb-93f0-6705a5323329.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Debris should disappear upon being collected. https://www.youtube.com/watch?v=S28r-OIzHcc shows the quest on live.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 18595 takes you to the questgiver, get the quest. (quest id is 11140)
2. Get the Salvage Kit from "Renn's Supplies" (given by the quest).
3. Swim under a "Burning Wreckage" down to a Shipwreck Debris.
4. Use the Salvage Kit.
5. Repeat step 4.

##### EXTRA NOTES:

Quest: https://wowgaming.altervista.org/aowow/?quest=11140
Shipwreck Debris: https://wowgaming.altervista.org/aowow/?object=186283
Salvage Kit: https://wowgaming.altervista.org/aowow/?item=33044

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
possible fix https://github.com/TrinityCore/TrinityCore/commit/89c998c08d5360c383bc8d89e417cf99bf1335aa
