### ISSUE TITLE
Attacks Against Sitting Enemy Players Do Not Crit

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5635]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/524

When you use a melee ability on an enemy player that is sitting it does not guarantee a critical strike.

Tester's notes - had two of my characters duel, one sitting down after every second attack while the other one kept melee attacking.

Auto attacks showed no variation between sitting and standing:
![WoWScrnShot_050421_224918](https://user-images.githubusercontent.com/81782124/117009965-7569d080-ad2b-11eb-8d6c-7c5baa3896aa.jpg)

The report specified melee abilities, which means auto-attack might not count. so tried with Ravage:
![WoWScrnShot_050421_230103](https://user-images.githubusercontent.com/81782124/117011264-cfb76100-ad2c-11eb-9283-34f38812e06d.jpg)

And then Mangle:
![WoWScrnShot_050421_230132](https://user-images.githubusercontent.com/81782124/117011298-d80f9c00-ad2c-11eb-91d2-b2ca9790f50b.jpg)

As you can see, there's no difference between any of the attacks, although every second one was against a sitting target. (Also, feral druids can apparently use Prowl while in combat in duels now, which may need another ticket.)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you use a melee ability (something like backstab or shred) or an melee autoattack on a target that is sitting down it should give that one melee strike a 100% crit chance.

From https://wowpedia.fandom.com/wiki/Sit?oldid=1656296:
"Melee attacks against a sitting target automatically hit and cause double damage. The first damage taken while sitting will cause a target to immediately stand. The double damage registers as a critical hit in the combat log, but does not trigger abilities as a normal crit would (such as the Fury Warrior talent: Enrage)"

##### STEPS TO REPRODUCE THE PROBLEM:

best way to reproduce would be dueling i guess
1. Duel another player
2. Tell him to sit down. 
3. Use any melee ability on that target
4. proceed to not get a crit with that ability

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Maxproz** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5872

**Comment by claudiodfc** [comment]
@FrancescoBorzi This issue has been fixed on PR mentioned above

**Comment by Azcobu** [comment]
Mostly fixed. See https://github.com/azerothcore/azerothcore-wotlk/issues/5986
