### ISSUE TITLE
Scatter shot in WSG makes you fall through ground

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#5639]
related of https://github.com/chromiecraft/chromiecraft/issues/536

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Using scattershot in WSG, specifically in the horde flag room in the upper part above the tunnel causes the effected player to fall through terrain, video [here](https://www.youtube.com/watch?v=PwNFqCXby2k)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nobody should fall through the ground (づ◔ ͜ʖ◔)づ

##### STEPS TO REPRODUCE THE PROBLEM:

1. In WSG scatter shot a player near the frame of the arc shown in the video and watch them fall through the ground

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
@UltraNix did you work recently on something that can affect this? may you know the cause...?

**Comment by UltraNix** [comment]
@Helias https://gist.github.com/UltraNix/e7225f924ef77008f48ac9526ce0c64b
Try this one and give me your feedback.

**Comment by Helias** [comment]
I'll test when I have the time, thank you

anyways, the reporter posted also this video https://github.com/chromiecraft/chromiecraft/issues/536#issuecomment-833098478

**Comment by ChromieCraftServer** [comment]
@Helias any news?

**Comment by UltraNix** [comment]
Should be fixed by 6496a7918c.

**Comment by Helias** [comment]
@UltraNix are you sure? we can close this?

**Comment by UltraNix** [comment]
It's the same code as I gave you to test 26 days ago.
