### ISSUE TITLE
The Violet Eye reputation quests - Archmage Leryda

### ISSUE THREAD

**Issue by BuildingOutLoud** [azerothcore/azerothcore-wotlk#5641]
**CURRENT BEHAVIOUR:**
At each reputation level Archmage Leryda gives you a ring via a quest. The yellow question mark shows up, but when you right click her nothing happens.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
When you right click Archmage Leryda she should present you a quest based on your reputation level.

**SOURCE:**
https://www.wowhead.com/npc=18253/archmage-leryda#starts

**STEPS TO REPRODUCE THE PROBLEM:**

1. Make new character and .level 79
2. .tele kara
3. Turn around and zone out of Karazhan
4. .mod rep 967 3000
5. Right click Archmage Leryda - Yellow ? above head, but nothing happens. Should give you a ring for being friendly.
6. .mod rep 967 9000
7. Right click Archmage Leryda - Yellow ? above head, but nothing happens. Should give you a ring for being honored.
8. .mod rep 967 21000
9. Right click Archmage Leryda - Yellow ? above head, but nothing happens. Should give you a ring for being revered.
10. .mod rep 967 42000
11. Right click Archmage Leryda - Yellow ? above head, but nothing happens. Should give you a ring for being exalted.

**AC HASH/COMMIT:**
545a045273b8cea9dfcf8e51e263732d1f7c281a

**OPERATING SYSTEM:**
ubuntu 20.04

**MODULES:**
none-fresh install using bash shell

**CUSTOMIZATIONS:**
none-fresh install using bash shell

**Comment by BeefSteaker** [comment]
cant figure out how to fix it, but if you disable her gossip entirely, the quests start working again

**Comment by w5860363** [comment]
DELETE FROM `npc_text` WHERE `ID` = 10884;
DELETE FROM `gossip_menu` WHERE `MenuID`=8441 AND `TextID`=10884; 
from tdb

**Comment by FallenDev** [comment]
Fix mentioned by w5860363 can be referenced here:
https://github.com/TrinityCore/TrinityCore/issues/16389
And
https://github.com/TrinityCore/TrinityCore/issues/16214
