### ISSUE TITLE
Horde Bug - Flight Pathing between Eastern and Western Plaguelands

### ISSUE THREAD

**Issue by Griffo76** [azerothcore/azerothcore-wotlk#5646]
**CURRENT BEHAVIOUR:**

Playing as a Horde character when you use the flight path from Light's Hope Chapel, Eastern Plaguelands to The Bulwark, Tirisfal, you will always be taken past The Bulwark back to the Undercity first before flying back out again.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

This should be a direct route with no returning to Undercity.

**SOURCE:**

There is no source. This is an in-game feature.

**STEPS TO REPRODUCE THE PROBLEM:**

1. HORDE ONLY - Travel to Light's Hope Chapel, Eastern Plaguelands either by flight or on foot.
2. Use the Horde Flight Master and select The Bulwark, Tirisfal.
3. Watch as you fly to the location and then continue to The Undercity before the flight pathing brings you back again.

**EXTRA NOTES:**

No.

**AC HASH/COMMIT:**
 
AzerothCore rev. SF_Official 2021-04-05 00:00:00 +0000 (AC_Solo_1.4.04052021) (Win64, Release) (worldserver-daemon)

**OPERATING SYSTEM:**

Windows 10.

**MODULES:**

No.

**CUSTOMIZATIONS:**

No,

**Comment by Kitzunu** [comment]
Which hash are you on?

**Comment by Griffo76** [comment]
@Kitzunu Thank you for your response. You'll have to forgive me. I'm inexperienced when it comes to this stuff. How do I find the hash?

**Comment by Kitzunu** [comment]
When you start your worldserver you will see something like this

AzerothCore rev. 82c80b626f03+ 2021-05-03 19:09:06 +0000 (soamehi branch) (Win64, RelWithDebInfo) (worldserver-daemon)

Copy that and paste it under AC HASH/COMMIT:

**Comment by Griffo76** [comment]
@Kitzunu I have copied and pasted what is there but there is no rev. code or hyperlink similar to yours?

**Comment by Kitzunu** [comment]
Did you build AzerothCore from this repo or did you download it precompiled somewhere?

**Comment by Griffo76** [comment]
It was precompiled. I don't know if I'm allowed to post links in here? I imagine if its precompiled there's no fix possible unless carried out by the original creator?

**Comment by Kitzunu** [comment]
Nope no fixing, as well as we do not support repacks.

My suggestion for you is to compile AzerothCore from the start. https://www.azerothcore.org/wiki/Installation

**Comment by Griffo76** [comment]
@Kitzunu That's great thank you for your time and help.
