### ISSUE TITLE
The Green Tower Shield - Proc Does Not Work

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5649]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/531

The Equip on the lvl 36 item The Green Tower does not proc. https://wowgaming.altervista.org/aowow/?item=1204

Tester's notes - The proc is only a 1% rate anyway, but tried this with an 80 warrior wearing the shield vs a fast-hitting lvl 20 druid cat, and let the cat melee the warr for about 10 mins, delivering about 600 melee attacks. No procs were seen before the warr died, so it does seem pretty likely the proc is not working.

![WoWScrnShot_050521_231513](https://user-images.githubusercontent.com/81782124/117151050-db238e80-adf7-11eb-9d99-a27156f82d7a.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

" When struck in combat has a 1% chance of raising a thorny shield that inflicts 3 Nature damage to attackers when hit and increases Nature resistance by 50 for 30 sec." 

The spell it should cast is https://wowgaming.altervista.org/aowow/?spell=18097

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have a high level character with the shield duel a low level character (so they don't do much damage)
2. Gather a few hundred melee strikes.

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?item=1204

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Maxproz** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5682

**Comment by Tony931023** [comment]
@Nyeriah Can it be closed now?, solved in https://github.com/azerothcore/azerothcore-wotlk/commit/dfa5da00b1253a944884d86796577dddcc799255
