### ISSUE TITLE
Giant Clam - Incorrect Blue Pearl Drop Rate

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5650]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/533

Object "Giant Clam" in the Vile Reef in STV doesn't drop Blue Pearl at expected droprate.
I looted 12 Giant Clams and got only 1 Blue Pearl.
Classic wowhead link: https://classic.wowhead.com/object=2744/giant-clam
Wowhead link: https://www.wowhead.com/object=2744/giant-clam

Tester's notes - spawned a few dozen clams:
![WoWScrnShot_050521_234649](https://user-images.githubusercontent.com/81782124/117156932-50de2900-adfd-11eb-9b3b-07804d40b2ac.jpg)

Results after opening:
![WoWScrnShot_050521_235323](https://user-images.githubusercontent.com/81782124/117157072-6c493400-adfd-11eb-9fb5-a92fa0a53ea0.jpg)

Getting 1 pearl out of 12 still seems very unlucky, but they should be 100% drop rate.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Giant Clam should drop Blue Pearl at droprate of 100% 
Screenshot from wowhead link linked before:
![image](https://user-images.githubusercontent.com/81812276/116941702-7be74200-ac70-11eb-9840-fce6b26654e8.png)

Also backed up for Wrath specifically here: https://wotlkdb.com/?object=2744

##### STEPS TO REPRODUCE THE PROBLEM:

1. .gobject add temp 2744, spam repeatedly
2. Loot.

##### EXTRA NOTES:

Notes from @necropola:

Only those found in **The Vile Reef** are supposed to drop **Blue Pearls**. 
I'm currently doing some pearl diving on my local AC and I have found one **Giant Clam** in '**The Vile Reef** (almost instant respawn) which appears to have an equal chance to drop either 1 **Blue Pearl** or 1 **Giant Clam Meat**. 

**Update:** Found 5 (spawn points) so far within **The Vile Reef**. All with `Entry=2744, LootID(Data1)=2264` and a 50% chance to drop a **Blue Pearl**

There are 4 different **Giant Clam** objects in the game
```
MariaDB [acore_world]> select entry, Data1, name from gameobject_template where name like '%Giant Clam%';
+--------+-------+------------+
| entry  | Data1 | name       |
+--------+-------+------------+
|   2744 |  2264 | Giant Clam |
|  19017 |  2954 | Giant Clam |
|  19018 |  2959 | Giant Clam |
| 179264 |     0 | Giant Clam |
+--------+-------+------------+
4 rows in set (0.009 sec)
```

Only `entry=2744, Data1=2264` has a (50%) chance to drop **Blue Pearls**.
```
MariaDB [acore_world]> select entry, item, chance, groupid, comment from gameobject_loot_template where entry in (2264, 2954, 2659, 0);
+-------+------+--------+---------+-----------------------------------+
| entry | item | chance | groupid | comment                           |
+-------+------+--------+---------+-----------------------------------+
|  2264 | 4611 |      0 |       2 | Giant Clam - Blue Pearl           |
|  2264 | 4655 |      0 |       2 | Giant Clam - Giant Clam Meat      |
|  2954 | 5498 |    0.5 |       0 | Giant Clam - Small Lustrous Pearl |
|  2954 | 5500 |    0.5 |       0 | Giant Clam - Iridescent Pearl     |
|  2954 | 5503 |      0 |       2 | Giant Clam - Clam Meat            |
|  2954 | 5504 |      0 |       2 | Giant Clam - Tangy Clam Meat      |
+-------+------+--------+---------+-----------------------------------+
6 rows in set (0.000 sec)
```

Maybe you were looking at the wrong place or were extremely unlucky to only get **1 Blue Pearl** from **12 Giant Clams** at a drop chance of 50%?

Also maybe the Chance/GroupId should be adjusted to increase the drop rate to 100%?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by LukasVolgger** [comment]
Confirm

**Comment by YunataSavior** [comment]
This is an extremely simple SQL update to perform; why hasn't this been done yet and ported to ChromieCraft?
