### ISSUE TITLE
Target Dummies Giving Ranged Weapon Skillups

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5651]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/534

Training Dummies are giving skill points to ranged weapons.

Tester's notes - the original report was for the lvl 40 Cute Training Dummy - however, tested on all those available in Orgrimmar (Expert, Master, Grandmaster and Heroic dummies) and they all did it.  I couldn't find a Cute Dummy in Orgrimmar, as it was probably not macho enough for orcs.

Skills affected were: Bows:
![WoWScrnShot_050321_224357](https://user-images.githubusercontent.com/33559707/116962893-9d175500-aca7-11eb-9062-56134e5f4815.jpg)

Wands: (thanks to @anglerf1sh):
![WoWScrnShot_050421_175234](https://user-images.githubusercontent.com/82279027/117032336-b220d200-ad01-11eb-958e-77bbc0d755b1.jpg)

Guns:
![WoWScrnShot_050621_002743](https://user-images.githubusercontent.com/81782124/117164198-8c7bf180-ae03-11eb-9872-bf38123767a3.jpg)

Thrown Weapons:
![WoWScrnShot_050621_003129](https://user-images.githubusercontent.com/81782124/117164220-9140a580-ae03-11eb-9c35-2fbf11c55546.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Training dummies should not give weapon skill.

Wowpedia seems to disagree re: melee attacks, but agrees that ranged should not benefit:
"You can gain melee Weapon skill by fighting dummies and hitting them with special melee abilities [...] Ranged weapon skill cannot benefit from this."
https://wowpedia.fandom.com/wiki/Training_Dummy?oldid=2351369

##### STEPS TO REPRODUCE THE PROBLEM:

1. Equip a ranged weapon below max level skill and wait for skill ups

 [08:20:09] Found near gameobjects (distance 10.000000): 0 
[08:20:14] Player selected NPC
[08:20:14] DB GUID: 3110366, current GUID: 3110366.
[08:20:14] Faction: 7.
[08:20:14] npcFlags: 0.
[08:20:14] Entry: 1111003.
[08:20:14] DisplayID: 28047 (Native: 28047).

##### EXTRA NOTES:

At the moment this only seems to work with bows (or ranged weapons in general, haven't tested others as I've already got guns to max), however I did try with melee weapons (sword and dagger) for a a few minutes and it didn't give any skill points, so it may be just certain weapons or only ranged ones.

Tester: This seems mostly right. I tried spamming special melee attacks at a target for a bit and got no skillups, but one auto-attack at the very start of combat did give a single point. I wasn't able to reproduce that however, and it never repeated.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Fixed https://github.com/azerothcore/azerothcore-wotlk/pull/5961

**Comment by fendwe** [comment]
This seems to be working correctly now.
