### ISSUE TITLE
WP is missing in Eastvale Logging Camp

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/azerothcore-wotlk#5654]
**CURRENT BEHAVIOUR:**
In location Eastvale Logging Camp , WP is missing

**EXPECTED BLIZZLIKE BEHAVIOUR:**
On the blizz server some NPCs have WP and animation chopping + voice speaking

**SOURCE:**
video from blizz server
https://youtu.be/WcU4mbcrZvQ

**STEPS TO REPRODUCE THE PROBLEM:**
teleport to Eastvale Logging Camp

1.  .tele Eastvale Logging Camp

**AC HASH/COMMIT:**
caf9140dca6bacd337fcb9957d2219c12ceb60f2

**OPERATING SYSTEM:**
Ubuntu

**MODULES:**
none

**CUSTOMIZATIONS:**
none

**Comment by Kitzunu** [comment]
Which NPC ID's?

**Comment by Krejza9** [comment]
@Kitzunu 
11328 - Eastvale Peasant
10616 - Supervisor Raelen
1975 - Eastvale Lumberjack
+ random movement for kids
798 - Solomon
799 - Kevin
800 - Kyle
801 - Eric
802 - Jay
