### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5659]
**CURRENT BEHAVIOUR:**
When you fly in a plane, pull the angle of view to the farthest (/script SetCVar("cameraDistanceMaxFactor"，50)),Then look at the distance while flying,The client will crash in about a few minutes

![image](https://user-images.githubusercontent.com/18187177/117238988-810ae380-ae60-11eb-9438-62c4748cd3cb.png)

**AC HASH/COMMIT:**
3f343830fb61aad9ba12c0c908b6b18fc9eafd83

**OPERATING SYSTEM:**
ubuntu 20.04

**MODULES:**
none

**Comment by Si1ker** [comment]
Why a client crash is reported to a project hosting a server application? :s

**Comment by Mitradis** [comment]
if you use HD models you must apply 4GB path to wow client.

**Comment by Kitzunu** [comment]
Can someone reproduce this with a clean client?

**Comment by mpfans** [comment]
This may be a blizzard bug
