### ISSUE TITLE
[QUEST] New Recruit | ID 13143

### ISSUE THREAD

**Issue by sucofog** [azerothcore/azerothcore-wotlk#566]
**Description**: [QUEST] New Recruit | ID 13143

**Current behaviour**: The quest is not working properly, when you cast 
http://www.wowhead.com/spell=58151/
spell of item http://www.wowhead.com/item=43315
over a Subdued Lithe Stalker, the minion is created, then you go to the top of the rocks northeast of the Rise of Suffering, and the minion remains till the aura removes, and nothing happens

**Expected behaviour**: 

Watch video:

https://www.youtube.com/watch?v=xfPIrf_Aihc

**Steps to reproduce the problem**:

1. Take quest on NPC http://www.wowhead.com/npc=30944
2. Use http://www.wowhead.com/item=43315 on a Subdued Lithe Stalker
3. Take it to northeast of the Rise of Suffering.
4. Nothing happens

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  7cef10a653ce3187bce2648e5eec9a99b16842f8

**Operating system**:  Debian

**Modules**:  Transmog, Mod-anticheat, Duel-reset

**Other Customizations**: None

**Comment by Yehonal** [comment]
I'm working on it, please next time use wowgaming.org for links if possible: https://wowgaming.altervista.org/aowow/

**Comment by Yehonal** [comment]
tested and it works, you just have to go in right position (near the Gelst Return Bunny i think, it's visible only by GM) 

As you can see in screenshot:

![image](https://user-images.githubusercontent.com/147092/29494590-e8f71d04-85ad-11e7-8c53-218176fbace0.png)
