### ISSUE TITLE
[Swamp of Sorrows][Herbalism] Multiple Herb Node Clusters

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5664]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/540

Multiple Herb nodes spawn in the same area.  

Issue especially visible after a server restart - might be that dynamic pooling does not kick in until after the initial spawn is gathered.

64040 (Entry: 2043) - [Khadgar's Whisker X:-10338.099609 Y:-2849.280029 Z:24.649099 MapId:0] 
8089 (Entry: 2043) - [Khadgar's Whisker X:-10345.000000 Y:-2842.000000 Z:23.749001 MapId:0] 
64039 (Entry: 2043) - [Khadgar's Whisker X:-10331.000000 Y:-2819.580078 Z:24.928900 MapId:0] 
8013 (Entry: 2043) - [Khadgar's Whisker X:-10304.000000 Y:-2850.000000 Z:26.697500 MapId:0] 
Found near gameobjects (distance 30.000000): 5 

![WoWScrnShot_050521_090434](https://user-images.githubusercontent.com/47978220/117106132-ffe01d80-ad87-11eb-8ce5-5ace538d6f7f.jpg)

7571 (Entry: 2042) - [Fadeleaf X:-10366.799805 Y:-2989.790039 Z:21.830601 MapId:0] 
16348 (Entry: 142143) - [Blindweed X:-10352.000000 Y:-3004.000000 Z:19.421000 MapId:0] 
7645 (Entry: 2042) - [Fadeleaf X:-10366.000000 Y:-2982.860107 Z:22.409700 MapId:0] 
7570 (Entry: 2042) - [Fadeleaf X:-10373.700195 Y:-2983.719971 Z:22.442499 MapId:0] 

![WoWScrnShot_050521_090731](https://user-images.githubusercontent.com/47978220/117106159-09698580-ad88-11eb-8d64-8bd8b9704696.jpg)

[03:43:00] 8185 (Entry: 2043) - [Khadgar's Whisker X:-10544.000000 Y:-4180.000000 Z:23.434999 MapId:0] 
[03:43:00] 8186 (Entry: 2043) - [Khadgar's Whisker X:-10555.000000 Y:-4170.000000 Z:22.503000 MapId:0] 
[03:43:00] 16317 (Entry: 142143) - [Blindweed X:-10539.000000 Y:-4149.000000 Z:23.400000 MapId:0] 

![WoWScrnShot_050521_090731](https://user-images.githubusercontent.com/47978220/117226506-7844ee00-ae1d-11eb-8908-fb03e28738b3.jpg)

Tester's notes - deliberately restarted my server and checked the nodes, and found rather less herbs than depicted - they seemed abundant, but not excessively so for a low-pop zone. 

Nodes at above points after server restart:
![WoWScrnShot_050621_223527](https://user-images.githubusercontent.com/81782124/117303804-459e0280-aebc-11eb-9495-63322a68f781.jpg)

However, the OP's screenshots do seem to show that on Chromie at least, there is a pooling issue with SoS, and if or when a Swamp of Sorrows herb pool ticket is created, this might be handy.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herb nodes should not be this abundant.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Travel to Swamp of Sorrows
2.  Advance to the provided coordinates
3.  Notice the herb spawn
4. Be happy you picked up Herbalism as a profession :)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Syntax =
Blue: ON
Red: OFF

* First set, pooling is working correctly, I only saw 1 active at the time:

![image](https://user-images.githubusercontent.com/61223313/117350410-c1bb2a80-ae69-11eb-86a5-4118b218ed7d.png)


* Second set, pooling working correctly, those 4 were inactive in my server so another nearby was active instead of those.

![image](https://user-images.githubusercontent.com/61223313/117350708-1c548680-ae6a-11eb-9c1b-038727ffc126.png)


* Third set, pooling working correctly, those 3 were not active on my server so other must have been active at the moment.

![image](https://user-images.githubusercontent.com/61223313/117350871-4dcd5200-ae6a-11eb-994f-dfdddff7072f.png)

Conclusion, pooling and gobs are ok, your server got the chance to have them active.

**Comment by FrancescoBorzi** [comment]
@Si1ker don't forget to close the original issue as well

**Comment by mturca** [comment]
that works for me - but imo it's a constant chance on chromie for all to be active as i encountered the behavior 3 times so far.
