### ISSUE TITLE
Move hardcoded texts of zone_dragonblight to the Database

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5669]
**Edit by Shin**

The script: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/zone_dragonblight.cpp#L39

has hardcoded texts which should be moved to the DB instead.

**CURRENT BEHAVIOUR:**
Inserted localized data does not work

![image](https://user-images.githubusercontent.com/18187177/117320509-e2619f80-aebe-11eb-8b71-daf3ec346851.png)

```
DELETE FROM creature_text_locale WHERE CreatureID =26648 AND Locale = 'zhCN';
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','0','0','zhCN','小小$n，为什么召唤我？你和这里的巨魔在策划什么阴谋？你想要杀死我，夺取我的力量吗？');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','1','0','zhCN','你是卡鲁亚克氏族的朋友？我对此持保留意见。如果你想让我为他们占卜的话，就先证明自己的忠诚吧。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','2','0','zhCN','我要你做的事也不算太过分。当着我的面跳入深海吧，这样你才能与我的精神融合，以此表达你的诚意。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','3','0','zhCN','虽说我提出了要求，不过你可以选择跳或是不跳。我给你20秒做决定。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','4','0','zhCN','如果你没有看到这一点且没有跳入到水中，我很好奇会发生什么');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','5','0','zhCN','很好，$n。你充分表达了自己的诚意。我会如约告诉你关于卡鲁亚克氏族的命运，请转告他们吧。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','6','0','zhCN','请你转告卡鲁亚克海象人，逃亡是没有出路的。一旦选择逃亡，他们的灵魂将被诺森德滋生的邪灵毁灭。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','7','0','zhCN','告诉秘法师，卡鲁亚克氏族必须与部落和联盟并肩战斗，共同抵抗玛里苟斯和巫妖王的军队。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','8','0','zhCN','现在你的使命已经达成，游回去吧。尽你所能地帮助他们，$r。');
INSERT INTO `creature_text_locale` (`CreatureID`, `GroupID`, `ID`, `Locale`, `Text`) VALUES('26648','9','0','zhCN','很好，$n你拒绝了我的要求。那么我也拒绝占卜卡鲁亚克氏族的命运。在你鼓起勇气接受挑战之前，别再召唤我！');
```

You can change your local language
Check the Wiki and find that the wiki is not updated
https://www.azerothcore.org/wiki/creature_text_locale

**STEPS TO REPRODUCE THE PROBLEM:**
1. INSERT INTO a line data to creature_text_locale table
2. restart worldserver

**AC HASH/COMMIT:**
3f343830fb61aad9ba12c0c908b6b18fc9eafd83

**OPERATING SYSTEM:**
ubuntu 20.04

**Comment by Bogir** [comment]
we use broadcast_text_locale instead of some _locale tables

**Comment by Kitzunu** [comment]
This needs to be fixed. broadcast_text should only contain sniffed data

**Comment by mpfans** [comment]
The localized text is already in the database. You can get it through the following SQL statement
```SELECT * FROM broadcast_text_locale WHERE ID IN ( 25854,25863,25864,25865,25866,25867,25868,25869,25870)```

**Comment by mpfans** [comment]
@avarishd Can you take a look?
