### ISSUE TITLE
worldserver crashes after more than one DB connection attempt

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5674]
The functionality introduced by this PR is useful to reproduce the bug (even though the bug affects master as well): https://github.com/azerothcore/azerothcore-wotlk/pull/5673

**CURRENT BEHAVIOUR:**

Both the `authserver` and `worldserver` should correctly start once MySQL is available.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Only the `authserver` works, the `worldserver` crashes on `Loading acore strings`

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. stop mysql
2. run authserver and worldserver
3. start mysql

result: `authserver` will connect, `worldserver` will connect and then crash

Authserver:
![image](https://user-images.githubusercontent.com/75517/117355309-b4765e00-aeb2-11eb-989c-5b815ae9120a.png)

Worldserver:

![image](https://user-images.githubusercontent.com/75517/117355377-ca841e80-aeb2-11eb-9410-1034a1afae4d.png)

**AC HASH/COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

**OPERATING SYSTEM:**
macOS

**Comment by FrancescoBorzi** [comment]
closing as it seems @Winfidonarleyan cannot reproduce it, probably something wrong with my specific setup. If someone else has this, we can reopen.

**Comment by Winfidonarleyan** [comment]
https://cdn.discordapp.com/attachments/534503351803445291/839950125039878154/Server_test.log
