### ISSUE TITLE
Can't run db_assembler.sh on CentOS

### ISSUE THREAD

**Issue by aleigood** [azerothcore/azerothcore-wotlk#5685]
It support CentOS before, but now get error:
[root@VM-4-11-centos db_assembler]# ./db_assembler.sh 
/opt/acore/src/conf/dist/config.sh: line 108: readarray: -d: invalid option
readarray: usage: readarray [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]

**Comment by Krejza9** [comment]
This is not bug
Azeroth core  is for Ubuntu and Debian

https://www.azerothcore.org/wiki/linux-requirements

**Comment by FrancescoBorzi** [comment]
> This is not bug
> Azeroth core is for Ubuntu and Debian
> 
> https://www.azerothcore.org/wiki/linux-requirements

wrong, AC should work on as many linux distributions as possible :)

so this is a valid bug report

cc @Yehonal

**Comment by Viste** [comment]
> > > This is not bug
> > > Azeroth core is for Ubuntu and Debian
> > > https://www.azerothcore.org/wiki/linux-requirements
> > 
> > 
> > wrong, AC should work on as many linux distributions as possible :)
> > so this is a valid bug report
> > cc @Yehonal
> 
> I can't test it with CentOS, db_assembler is only tested with Ubuntu and Debian. Normally such kind of errors derive by a different version of the dependencies used by our bash system. In future probably we will switch our bash system to Deno, but until then, I strongly suggest to you docker btw.
> 
> Otherwise, if you know how to fix, please open a PR

no fix needed, just need run it correctly `sh db_assembler.sh` or `bash db_assembler.sh`

**Comment by Viste** [comment]
Centos7/8/Fedora will have same behevior
![Снимок экрана от 2021-05-08 22-53-19](https://user-images.githubusercontent.com/281977/117551733-4071bc80-b050-11eb-847a-c551969359a6.png)
