### ISSUE TITLE
Hunter pet's not saved. [$10]

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#57]
**Description**: Hunter pet's not saved.

**Current behaviour**: On the Linux operating system hunter pets are not saved, but windows everything works perfectly.

**Expected behaviour**: When pet leveling level level should save, but it is reset when the log.

**Branch(es)**: 1.x / 2.x (Select the branch(es) affected by this issue) 

**AC hash/commit**:  [c9610ca](https://github.com/azerothcore/azerothcore-wotlk/commit/c9610ca0b5c6bbffcb443e1cc1dd698c53bada16)

**Operating system**:  OC Linux
##

**Comment by mik1893** [comment]
working on it

**Comment by Yehonal** [comment]
We placed a bounty on it

**Comment by talamortis** [comment]
is this bug only on linux?, seems to be fine on my core, pets are saving dont run away and keeping their level.

**Comment by DevRival** [comment]
The only problem on Linux.

**Comment by mik1893** [comment]
it is due to the async load system - the bug is is not actually in saving the pet, but in loading the pet back, at least that's what it looks like.,
setting up the trinitycore LoadPetFromDB seems to work... still i really wonder why it does this on linux only.

**Comment by DevRival** [comment]
I connect to the discus . Surprisingly to debug the kernel behaves the same as in Linux and on Windows , but somehow miraculously , a request to insert changes in Linux , but rather change all the parameters level , talents and so on. I have the impression that somewhere banal error register , because Linux is very picky about this .

**Comment by DevRival** [comment]
Any news?

**Comment by ShinDarth** [comment]
Can you please update your core and try this again after https://github.com/ShinDarth/azerothcore-wotlk/commit/527bbf80d53d2ba2b79ca7e91436d03e04d19f56 ?

**Comment by DevRival** [comment]
Don't fix.

**Comment by ShinDarth** [comment]
unfortunately I'm unable to reproduce it, on Mac OS X it just works and here I don't have any other machine.

I will setup a virtual machine with linux when I can

**Comment by Yehonal** [comment]
@mik1893 added a workaround here: https://github.com/azerothcore/azerothcore-wotlk/commit/6f933d1385043a067b790d92f5d8bae81497268f

we tried it and should be ok for now, don't you?

**Comment by boom8866** [comment]
@Yehonal  Not resolved

**Comment by DevRival** [comment]
Any news?

**Comment by talamortis** [comment]
@DevRival i know it maybe a long shot but try a recompile with different SQL (one it has on wiki)

**Comment by DevRival** [comment]
@talamortis What's in it for me? I have one such error?

**Comment by DevRival** [comment]
Maybe who fix this?

**Comment by HeartWell** [comment]
confirm, news?

**Comment by ShinDarth** [comment]
@HeartWell please can you include your commit hash when you confirm an issue? thanks

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-comment-an-issue

**Comment by HeartWell** [comment]
Very interestin.
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Pet/Pet.cpp#L213-L214

**Comment by HeartWell** [comment]
Mew information, the problem is not only hunters, but even the fake players. do not load the data name and location and level, just unknown. Is the problem of discharging base?

**Comment by justdothings** [comment]
im using sunwellcore not azerothcore but i used release version and pets saved normaly but now i compiled on debug mode for some reasons and now pets have same problem when you level up pet and mount and than unmount pet will be 75 level again. same on relog

**Comment by HeartWell** [comment]
Any idea?

**Comment by justdothings** [comment]
I asked to developer  if he will fix it i will share

**Comment by sucofog** [comment]
Pets working perfect on Windows compile.

**Comment by HeartWell** [comment]
Any news for Linux?

**Comment by HeartWell** [comment]
https://github.com/RaphaelSunwell/Sunwell-BugTracker/issues/16
The problem is solved.

**Comment by Maczuga** [comment]
@HeartWell  I was a main developer of that server - you want a fix:
https://bitbucket.org/maczuga/sunwellcore/commits/8c0aea4430c377a9bfe4dc153a163a83738f187c#Lsrc/server/game/Handlers/PetHandler.cppT179

Just that 1 line. Go ahead and take more of fixes, just do not merge struct and mmap changes.
Waiting for my bounty.

**Comment by Maczuga** [comment]
https://bitbucket.org/maczuga/sunwellcore/commits/8c0aea4430c377a9bfe4dc153a163a83738f187c#Lsrc/server/game/Handlers/PetHandler.cppF179

There you have it. Someone here removed my post here, dunno why. Go ahead, take all you want. The repo that you linked - all the fixes was mine.

Just don't merge struct and mmaps. 

Waiting for my reward.

**Comment by ShinDarth** [comment]
@Maczuga thanks but please [open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) with your fix

**Comment by Yehonal** [comment]
@Maczuga the reward from bountysource can be taken only if you test, fix and send us the code via PR
A link is useless

so if you want the bounty money...

Waiting for your work

**Comment by Maczuga** [comment]
Then I really do not care about that 10 bucks. If any1 wants it - go ahead. It works, tested on server with 2,5k Players. I don't have time to do it.

**Comment by ShinDarth** [comment]
@Maczuga you linked a huge diff, most of it is surely unrelated with this bug. Can you at least provide a clean diff?

**Comment by Maczuga** [comment]
This is just 1 line that I linked directly. Created that pull request.

**Comment by boom8866** [comment]
@Maczuga  Thank you for your sharing

**Comment by HeartWell** [comment]
I accidentally deleted( through the application ios( sorry(

**Comment by HeartWell** [comment]
I didn't want to, thank you @Maczuga

**Comment by Blumfield** [comment]
Fix is correct, but I suspect they might be more "incidental" bugs...

**Comment by Maczuga** [comment]
There is a lot of that stuff inside. The most (and for me the only) advantage of SunwellCore is performace. Take a look at my repo - I know that diffs are huge sometimes, but you'll find there many such things.

**Comment by ShinDarth** [comment]
@Maczuga Thank you. It would be nice if you can PR all the other improvements that you've implemented.

@ghost1988 @boom8866 and the others that have this issue, can you please test the PR and let us know if it solves the problem for you?

- Link to the PR:  https://github.com/azerothcore/azerothcore-wotlk/pull/248
- How to test a PR: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request

**Comment by Yehonal** [comment]
@Maczuga please claim the bounty: https://www.bountysource.com/issues/36880340-hunter-pet-s-not-saved
