### ISSUE TITLE
can not keep update with docker bash

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#5705]
**CURRENT BEHAVIOUR:**

installed with docker  before , display err message follow the step guild of "Docker setup -> How to keep your AzerothCore updated with the latest changes"

Err message:
azerothcore-wotlk/conf/dist/config.sh: line 108: readarray: -d: invalid option 
readarray: usage: readarray [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]

the source code of the line is
-- convert from comma separated list to an array.
--This is needed to support environment variables
readarray -td, DATABASES <<<"$DBLIST";

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. git pull
2. ./acore.sh docker build

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
014816065922

**OPERATING SYSTEM:**

CentOS 7
**MODULES:**

**CUSTOMIZATIONS:**

**Comment by FrancescoBorzi** [comment]
@betayi what is your bash version?

**Comment by betayi** [comment]
> @betayi what is your bash version?

# bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by betayi** [comment]
I find that this command has a new arg (-d) at bash manual:
http://www.gnu.org/software/bash/manual/bash.html#index-readarray
maybe i should update my bash to the latest version
if it's the reason cause error, it shoud be updated with Dockerfile,i guess

**Comment by FrancescoBorzi** [comment]
> GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

@betayi that's too old, you need at least version 5 or higher. Please update your bash version.

More in general: never use outdated dependencies unless you have a really good reason to.
