### ISSUE TITLE
Feature: Replace isLarge with visibilityDistanceType

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#5714]
cherry-pick https://github.com/trinitycore/trinitycore/commit/d1c3ee9579 to get more choices of how far a unit can be seen instead of a set bool isLarge

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9180

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/de6af87bd37ce063e08633eca28bf7d644d83bd2
