### ISSUE TITLE
Armor Crate's Green Loot Doesn't Prompt Party Loot Roll

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5724]
**CURRENT BEHAVIOUR:**

Original report: https://github.com/chromiecraft/chromiecraft/issues/567

There is an Armor Crate in Scarlet Monastery Armory, GUID 32254, entry 3703. (https://wotlkdb.com/?object=3703) It is unique, being the only member of its class. The problem is that if someone is in a party, opens it and finds a green or better, the loot doesn't get rolled for, unlike greens from chests.

![WoWScrnShot_050521_184912](https://user-images.githubusercontent.com/22718174/117517632-9ec46f80-af6a-11eb-91d7-5aaeb89896ff.jpg)

This may be because they are not supposed to drop any green items at all according to TBC Wowhead. (WOTLKDB disagrees and gives a long list of greens they drop.) If the crate was only supposed to have grey items only, that would explain why it doesn't prompt a party loot roll.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Either the crate can contain green loot items, and they should be rolled for the group just like the greens from any chests. Or the crate should only contain greys, which don't prompt a loot roll. 

**SOURCE:**

If it should contain greens - https://wotlkdb.com/?object=3703

if not: "There's nothing interesting inside those crates, only crap gray items." - https://tbc.wowhead.com/object=3660/armor-crate#comments:id=140611 - note this is patch 2.1.3, not 3.3.5.

**STEPS TO REPRODUCE THE PROBLEM:**

1. Be in a group with party loot (greens and higher).
2. Loot the Armor Crate (32254, entry 3703).
3. Notice the green won't be rolled if there is one.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
rev. 3c763786a0bd 2021-05-07 21:53:46 +0000

**OPERATING SYSTEM:**

Linux Mint 20.1

**MODULES:**

N/A.

**CUSTOMIZATIONS:**

N/A.

**Comment by Kitzunu** [comment]
You can change as party leader what quality is lowest to roll on, right-click the character in the top right of the screen

**Comment by Azcobu** [comment]
When testing, I had party loot set like this: 
![WoWScrnShot_050821_234104](https://user-images.githubusercontent.com/81782124/117542250-00620800-b057-11eb-9ef1-58a876373347.jpg)

Which is the default setting anyway I think. That should prompt a party loot roll on any green item, shouldn't it?

**Comment by d3tr0l** [comment]
Sorry for the intervention, I am not even contributing nor participating. But try the DB and check the flags for that particular lootable object (crate, chest, box, etc.). I believe there used to be some flags or types for lootable objects defining whether it is only a "first come, first served" or a "group loot affected" object. Also, I might be wrong or this is some stuff from 4.0.1+.

I am glad people are still working and contributing to this project, it brings back some good memories :)

Here is a potato just for the lulz:
![potato](https://user-images.githubusercontent.com/10038463/117546052-bfeb9580-b028-11eb-8a84-4650e4269bf3.jpg)
