### ISSUE TITLE
worldserver can't run

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5725]
**CURRENT BEHAVIOUR:**
worldserver can't run

**STEPS TO REPRODUCE THE PROBLEM:**
1. updated https://github.com/azerothcore/azerothcore-wotlk/commit/3c763786a0bdf1b7e88ce99ca86a84a39a159642
2. Compilation complete
3. ./worldserver
![image](https://user-images.githubusercontent.com/18187177/117543313-dc9ac400-b04e-11eb-992f-48b2472b4fdf.png)

**EXTRA NOTES:**
Because of this PR, it can't run
https://github.com/azerothcore/azerothcore-wotlk/pull/5438

After I restore this PR, it works normally
**AC HASH/COMMIT:**
3c763786a0bdf1b7e88ce99ca86a84a39a159642

**OPERATING SYSTEM:**
ubuntu20.04

**Comment by Kitzunu** [comment]
I can't reproduce this on Windows

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan

**Comment by Kitzunu** [comment]
You have a whitespace in your config file on line 1

**Comment by Winfidonarleyan** [comment]
Need use config files without whitespace

**Comment by mpfans** [comment]
I have not changed the configuration file, just restore the PR to work properly.
Can you explain to me why?

This image shows me using a new configuration file, just removing the suffix dist
![image](https://user-images.githubusercontent.com/18187177/117547918-bc75ff80-b064-11eb-842e-96632751910f.png)

**Comment by Winfidonarleyan** [comment]
Try use https://github.com/jannek/tws
And for linux need use `LF` end lines

**Comment by r0m1ntik** [comment]
Confirm @mpfans

![Снимок экрана 2021-05-08 в 23 46 50](https://user-images.githubusercontent.com/40755539/117554419-cfce9e00-b057-11eb-823f-6587c80a694d.png)
![Снимок экрана 2021-05-08 в 23 47 13](https://user-images.githubusercontent.com/40755539/117554421-d0ffcb00-b057-11eb-811f-945e9c42ce71.png)
![Снимок экрана 2021-05-08 в 23 47 19](https://user-images.githubusercontent.com/40755539/117554422-d1986180-b057-11eb-9e3c-e788a68b4bc8.png)

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5761 fixed
