### ISSUE TITLE
Hunter's Spirit Bond Talent Not Generating Threat

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5739]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/574

The hunter talent Spirit Bond (https://wotlk.evowow.com/?spell=20895) doesn't cause any threat.

Screenshot showing Omen - the combat log shows Spirit Bond ticking, but Omen shows no threat generated by the pet.
![WoWScrnShot_050921_132444](https://user-images.githubusercontent.com/81782124/117560156-76538700-b0ca-11eb-9529-d16af539e003.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should cause some threat, enough to hold several mobs with correct use of feign death in order to reset threat on hunter.

"It seems to generate some threat on your pet. (You shouldnt have taken any damage for the tic to affect you, thus removing the possibility of gaining any aggro from this buff.)" - https://wowpedia.fandom.com/wiki/Spirit_Bond_(hunter_talent)?oldid=2220313

##### STEPS TO REPRODUCE THE PROBLEM:

1. Learn Spirit Bond
2. send your pet
3. check if your pet is generating threat on other targets

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eronox** [comment]
Seems to be caused by the spell having `SPELL_AURA_OBS_MOD_HEALTH` and the following PR removes threat generation from every spell using it 

https://github.com/azerothcore/azerothcore-wotlk/pull/7291/files

**Comment by Eronox** [comment]
says here it's not supposed to generate threat
https://tbc.wowhead.com/spell=20895/spirit-bond

![image](https://user-images.githubusercontent.com/20321723/144760166-4a007324-fe25-4224-9644-a6b798199b49.png)

**Comment by Kitzunu** [comment]
I want to correct you. for learning purposes.

Thatr is not "in Azerothcore", that's in the DBC files.

Anyhow I will close as the DBC contradicts this and "seems" is just vague

**Comment by Eronox** [comment]
Yeah, in Azerothcore i meant as the Azerothcore project 😄

**Comment by FrancescoBorzi** [comment]
we should not forget to close the CC issue too when we manually close it here
