### ISSUE TITLE
Compile error observed with latest commit 9c276b39b6e0334e79b44ce945487ac7963a4891

### ISSUE THREAD

**Issue by rogerc66** [azerothcore/azerothcore-wotlk#5740]
**CURRENT BEHAVIOUR:**
![image](https://user-images.githubusercontent.com/4217584/117560213-4b633600-b0be-11eb-82f5-8222ee4e52bc.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**Should compile flawlessly

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. git pull latest repo
2. compile by "./acore.sh docker build"
3. error generated.

**EXTRA NOTES:**

**AC HASH/COMMIT:**commit 9c276b39b6e0334e79b44ce945487ac7963a4891
 

**OPERATING SYSTEM:**ubuntu 18

**MODULES:**clean build, no modules.

**CUSTOMIZATIONS:**None

**Comment by Kitzunu** [comment]
CI passes.

**Comment by FrancescoBorzi** [comment]
@rogerc66 what is your compiler version? also, have you tried a clean build?
