### ISSUE TITLE
Player Buffs Not Affecting NPCs

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5745]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/581

Buffs that can be applied to NPCs should provide them with the buff. However, at least with stamina altering buffs it does not effect them at all. I would assume this would apply to other stats as well.
![image](https://user-images.githubusercontent.com/68164076/117559654-ff6fad00-b03b-11eb-8485-82d8fda3edfe.png)
![image](https://user-images.githubusercontent.com/68164076/117559661-0e565f80-b03c-11eb-821e-5730ad4f51b2.png)

![image](https://user-images.githubusercontent.com/68164076/117559719-86248a00-b03c-11eb-8b6e-c1e82649869b.png)
![image](https://user-images.githubusercontent.com/68164076/117559711-76a54100-b03c-11eb-976d-6bc084412e3f.png)

Tester's notes - ran around Org throwing Mark of the Wild at various NPCs, and it didn't affect any of them. Most named NPCs were immune to the buff and it wouldn't even appear on their status bars. For unnamed NPCs like Orgrimmar Grunts, the buff did show up on their status bar, but it did not affect their health at all.

Seems pretty trivial, but in certain situations like escort quests, the ability to buff an NPC might be quite valuable.

Oddly enough, while searching for related issues I found https://github.com/azerothcore/azerothcore-wotlk/issues/4581, which suggests that buffing NPCs was working as recently as mid-February.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Power infuses the target, increasing their stamina"
[https://classic.wowhead.com/spell=10938/power-word-fortitude](https://classic.wowhead.com/spell=10938/power-word-fortitude)
"Places a blessing on the friendly target, incresing total stats by 10%"
[https://classic.wowhead.com/spell=20217/blessing-of-kings](https://classic.wowhead.com/spell=20217/blessing-of-kings)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Try buffing random NPCs I know we've all buffed the auctioneer or banker accidently at some point.

##### EXTRA NOTES:

I like turtles

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
That's because on Classic NPCs do have stats like strength, stamina etc... This is not implemented on any private server and is pretty much impossible to figure out

**Comment by Si1ker** [comment]
Just as @T1ti said above.. nothing we can do, closing.
