### ISSUE TITLE
LK & LK mobs fall through the map 

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/azerothcore-wotlk#5747]
**CURRENT BEHAVIOUR:**
LK and the spawned mobs fall / run through the ground 

**EXPECTED BLIZZLIKE BEHAVIOUR:**
they should run normally 

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to ICC
2. Go to LK
3. Fight

**EXTRA NOTES:**
https://vid.dragonwrath.net/v/rSCnWv

**AC HASH/COMMIT:**
44babc3c3a52e8fad4cbeff36cc51192edac059d

**OPERATING SYSTEM:**
Debian 10

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by speedrunz** [comment]
Tested this and confirmed

**Comment by speedrunz** [comment]
any updates on this please.

**Comment by poryagholami1374** [comment]
> any updates on this please.

https://github.com/azerothcore/azerothcore-wotlk/issues/5747#issuecomment-846500957

**Comment by poryagholami1374** [comment]
This is a map problem
And this is not a new issue
I have already sent this report and this repetition has been reported

It is better before reporting
See also other posts
So that the reports do not increase

**Comment by poryagholami1374** [comment]
It is better to close this report
And take the tested photo
Add to my report

**Comment by Err0r1** [comment]
Error reported here:
https://github.com/azerothcore/azerothcore-wotlk/issues/5622

Priority high!
