### ISSUE TITLE
NPCs cannot swim in water and conflicts with their Pathfinding.

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5748]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

**The video explains the problem very well.**

https://user-images.githubusercontent.com/1884642/117583497-54c0c280-b0ff-11eb-8c7a-7123fc270e9e.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
@Kitzunu I don't think it's related to **System: Movement and Pathfinding**
The problem was just this:
![image](https://user-images.githubusercontent.com/1884642/117583972-2395c180-b102-11eb-80bc-9153f614cecc.png)

**Comment by Stifler82** [comment]
I was wrong @Kitzunu, it's a Pathfinding problem.


@FrancescoBorzi Give a look at this, we have still Pathfinding Issues..
**Video Test:** [Pathfinding](https://youtu.be/xU27sYtMdp0)

So the Fix I made doesn't fix anything. 
However, in any case the fix I made is correct because pets should be able to swim in the water anyway.

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi Give a look at this, we have still Pathfinding Issues...
> **Video Test:** [Pathfinding](https://youtu.be/xU27sYtMdp0)

tagging @Yehonal and @Footman as they've worked on it lately. Can you guys have a look at that?

**Comment by Stifler82** [comment]
https://user-images.githubusercontent.com/1884642/118380898-87762980-b5dd-11eb-8153-df35f41d9e0c.mp4

**Comment by FrancescoBorzi** [comment]
@Stifler82 that's bad indeed, please open a new bug report with it.

**Comment by Stifler82** [comment]
> @Stifler82 that's bad indeed, please open a new bug report with it.

@FrancescoBorzi 
it is the same EXACT BUG, it does not matter that the subject in question is different, both the PET and the NPC are affected by the same BUG it is not a different bug, only the subject changes.

**Comment by FrancescoBorzi** [comment]
@Stifler82 ok then I've just reopened this one and changed the title.

@Footman @Yehonal please have a look at this

**Comment by eTzmNcbkrng** [comment]
Test link to CC Issue: https://github.com/chromiecraft/chromiecraft/issues/81

**Comment by UltraNix** [comment]
Can't reproduce problems with pets - please retest.
