### ISSUE TITLE
.pinfo bug , tested in 2 server release 21/08 and release 25/08

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/azerothcore-wotlk#575]
Gm Genie command spy crash the server

When you do spy a char the server crash, segmentation fault
tested 2 times.

**Steps to reproduce the problem**:

1. install addon gm genie
2. use the option spy a character

AzerothCore rev. a8166c386825 2017-08-21 11:51:27 +0200 (master branch) (Unix, Release) (worldserver-daemon)

**Comment by Inifield** [comment]
I guess it has to do with ipnation, your addon might not support it

**Comment by ShinDarth** [comment]
however the server shouldn't crash

**Comment by Nemepy** [comment]
i will replicate the action and post screnshots our video here. i just cant do it right now.

**Comment by ShinDarth** [comment]
that's ok

**Comment by Nemepy** [comment]
https://youtu.be/56j8DzcAqzw
Server output
ERROR: Could not fetch prepared statement 66 on database `world`, connection type: synchronous.

/home/wow/azerothcore/modules/worldengine/nucleus/src/Database/MySQLConnection.cpp:240 in _Query ASSERTION FAILED:
  m_mStmt
./worldserver(_ZN15MySQLConnection5QueryEP17PreparedStatement+0x3a) [0xfcd87a]
./worldserver(_ZN18misc_commandscript18HandlePInfoCommandEP11ChatHandlerPKc+0x1291) [0x16d8ea1]
./worldserver(_ZN11ChatHandler21ExecuteCommandInTableERKSt6vectorI11ChatCommandSaIS1_EEPKcRKSs+0x3e4) [0xa59324]
./worldserver(_ZN11ChatHandler13ParseCommandsEPKc+0xb9) [0xa5ef79]
./worldserver(_ZN12WorldSession23HandleMessagechatOpcodeER11WorldPacket+0x305) [0xf9d4c5]
./worldserver(_ZN12WorldSession6UpdateEjR12PacketFilter+0x667) [0xd88307]
./worldserver(_ZN5World14UpdateSessionsEj+0x1be) [0xe2afae]
./worldserver(_ZN5World6UpdateEj+0x234) [0xe2cca4]
./worldserver(_ZN13WorldRunnable3runEv+0x1c1) [0xa09cf1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb6970) [0x7f754a538970]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064) [0x7f754a795064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f7549ca862d]

Segmentation fault

**Comment by Nemepy** [comment]
this time no addon used
command .pinfo character also crash the server, same server output message.

**Comment by Nemepy** [comment]
i has made a new server new release new databases everything , the .pinfo char bug is real, the server crash when you do .pinfo charname , modules installed anticheat premium vas autobalance transmorg

**Comment by StygianTheBest** [comment]
I just confirmed this on my end.

http://imgur.com/a/izlxm

**Comment by Yehonal** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/b450ba35d86de2e6099146abdbf91d4640a10b95

please test it and tell me if it fixes your issue
