### ISSUE TITLE
Scorn, Scourge Invasion boss, still spawning.

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5750]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Scorn Is still spawning in the Scarlet Monastery grave yard even though the Scourge Invasion event is over.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After the Scourge Invasion even of 1.11 All of the added instance bosses including Scorn should have been removed.
[https://wowwiki-archive.fandom.com/wiki/Scorn](https://wowwiki-archive.fandom.com/wiki/Scorn)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele grandvest
2. enter the graveyard
3. Kill Bloodmage Thalnos
4. Walk back to the entrance of the courtyard and he will have spawned

##### EXTRA NOTES:

Original Chromiecraft report [https://github.com/chromiecraft/chromiecraft/issues/587](https://github.com/chromiecraft/chromiecraft/issues/587)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/61223313/117598741-9fddd400-b105-11eb-9f4e-2dba17205ff9.png)

Fixed in #5754
