### ISSUE TITLE
[BUG] Line of Sight Issue in the "Hillsbrad Foothills" at [30.10|42.40]

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5762]
WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

other (specify)

FACTION

- [ ] Alliance
- [X] Horde

CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

CURRENT BEHAVIOUR:

"Hillsbrad Councilman" is not able to follow the Player into the main building/ city hall of the Subzone "Hillsbrad Fields" at [30.11|42.42] to reestablish Line of Sight.
EXPECTED BLIZZLIKE BEHAVIOUR:

"Hillsbrad Councilman" should be able to follow the Player into the main building/ city hall and reestablish Line of Sight.
STEPS TO REPRODUCE THE PROBLEM:

    Go to the main building/ city hall at [30.11|42.42] in the "Hillsbrad Foothills".
    Leave the Building and procede to aggro a "Hillsbrad Councilman".
    Reenter the Building and hide from Line of Sight.
    Wait for it... wait for it...

EXTRA NOTES:

https://de.classic.wowhead.com/npc=2387/ratsherr-von-hillsbrad
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@91081f4
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot
    mod-eluna-lua-engine
    mod-server-auto-shutdown
    lua-LevelUpReward
    lua-CarbonCopy

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/478"

Confirmed and reproduced on a local AC server :

![WoWScrnShot_051021_133135](https://user-images.githubusercontent.com/82579073/117646763-d3b40a80-b194-11eb-90af-def314c64ccc.jpg)
![WoWScrnShot_051021_133148](https://user-images.githubusercontent.com/82579073/117646779-d878be80-b194-11eb-9756-feb3d21c4454.jpg)
![WoWScrnShot_051021_133222](https://user-images.githubusercontent.com/82579073/117646792-db73af00-b194-11eb-8632-01791e206b24.jpg)
![WoWScrnShot_051021_133635](https://user-images.githubusercontent.com/82579073/117646800-ddd60900-b194-11eb-94b3-00d221767791.jpg)

**Comment by Synful-Syn** [comment]
This looks fixed. AzerothCore rev. 1ad79e19011d 2022-05-11 11:41:00 +0000 (master branch)
I'm not closing it since I don't know how the bounty should be handled.

https://user-images.githubusercontent.com/22718174/168499052-5bb91e9d-3bc9-4a2c-9d75-030d201e0c75.mp4

**Comment by sudlud** [comment]
still working correctly as of ef6db03e1
