### ISSUE TITLE
[BUG] Line of Sight Issue in the Ghostlands [40.20|49.30] 

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5764]
WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

other (specify)

FACTION

- [ ] Alliance
- [X] Horde

CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

CURRENT BEHAVIOUR:

Line of Sight issue with the NPC "Deatholme Darkmage" at the "Howling Ziggurat" in the Ghostlands at [40.20|49.30]. The NPC isn't able to follow the player into the "Howling Ziggurat".
EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC should e able to follow the player into the "Howling Ziggurat".
STEPS TO REPRODUCE THE PROBLEM:

    Go to the "Howling Ziggurat" in the Ghostlands at [40.20|49.30].
    Procede to aggro the "Deatholme Darkmage" outside.
    Go into the "Howling Ziggurat".
    Observe.

EXTRA NOTES:

https://www.wowhead.com/npc=16318/deatholme-darkmage
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@91081f4
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot
    mod-eluna-lua-engine
    mod-server-auto-shutdown
    lua-LevelUpReward
    lua-CarbonCopy

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/486"

Confirmed and reproduced on a local AC server :

![WoWScrnShot_051021_135313](https://user-images.githubusercontent.com/82579073/117648792-563dc980-b197-11eb-9652-27b5e4a812d0.jpg)
![WoWScrnShot_051021_135337](https://user-images.githubusercontent.com/82579073/117648800-5938ba00-b197-11eb-9250-97255acee17d.jpg)

**Comment by malcrom** [comment]
I can't duplicate this.
