### ISSUE TITLE
[STORY] Creatures falling into the ground and wrong Z calculation

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#5765]
Recently several people reported issues with creatures and players falling into the textures

We tried to collect some of them here: https://github.com/azerothcore/azerothcore-wotlk/projects/16 but I'm not sure anymore it's related to the movement/pathfinding since some people also noticed that certain creatures are just spawned under the floor.

In [this PR](https://github.com/pulls?q=is%3Apr+author%3AYehonal+archived%3Afalse+is%3Aclosed) I worked a lot to make the Z calculation working in every case and generating proper normalized paths. One of the dozens of tests I made was with the quest called "Unexpected Results" where some creatures are spawned far away from the target and they had to reach the target that was on a different ground level. Before my PR those creatures were just flying towards the target, while after they calculated the Z coord correctly.

Recently, however, people started to report a lot of issues with the Z coord, and eventually that quest was bugged again and needed to be fixed with "a workaround" I'd say: https://github.com/azerothcore/azerothcore-wotlk/pull/5072

This seems like a generic issue that must be fixed at the core level, we are not supposed to fix all the **coords inside the DB.**

@Footman worked on these PR https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+author%3AFootman+is%3Aclosed

while @UltraNix worked on these ones:
https://github.com/azerothcore/azerothcore-wotlk/pull/4879
https://github.com/azerothcore/azerothcore-wotlk/pull/5114
https://github.com/azerothcore/azerothcore-wotlk/pull/4855

I'm not sure if everyone else also introduced other changes, if so, please report them here.

I think now we should:

1) comment this story with all the evidence of this bug in order to properly test it. Please provide all the instructions!
2) trying to spot which were the PR that caused this issue
3) Provide a PR as soon as possible since this bug is ruining the game experience in the entire world

Unfortunately, I'm not available to work on it at the moment but I can provide all the help needed by chat and here. 

I'd like that everyone contributes to this issue by adding more information

**Comment by Yehonal** [comment]
**By Wotex:**

ultranix made change to Z by removing collisionheight and setting it to 2
i kept on my server collisionheight 


https://github.com/azerothcore/azerothcore-wotlk/pull/4909


i am not sure if its because of this
he takes only 0.5 above ground here
even in old ac it was 2
in tc it is collision height
![image](https://user-images.githubusercontent.com/147092/117689271-dc6b0780-b1b9-11eb-92bc-d4c139e660a5.png)

thats what i am using
i have GetCollisionHalfHeight
instead of full height
![image](https://user-images.githubusercontent.com/147092/117689293-dffe8e80-b1b9-11eb-9d88-cf10d7933e56.png)

i use it everywhere like this
for the case its very small creature i kept Z_OFFSET_FIND_HEIGHT for max
i dont get reports with this about falling throw ground. only with confused movement but it was fixed by him

**Comment by Footman** [comment]
hey look screenshots please that Yehonal has posted. i added GetCollisionHalfHeight in my code for this.

**Comment by Footman** [comment]
> > hey look screenshots please that Yehonal has posted. i added GetCollisionHalfHeight in my code for this. To trace to the ground already half-height of the creature is enough.
> 
> What's the reason behind the fact that half-height would work and the full height doesn't? Also, TC is using the GetCollisionHeight() on master and Z_OFFSET_FIND_HEIGHT on 3.3.5
> 
> Where Z_OFFSET_FIND_HEIGHT is 1.5f in their case (0.5f on AC)
> 
> To be honest, I'd like to find a universal global solution to this problem, I don't like to just tune up constants to fix most of the cases (but not all of them).

The reason ultarnix changed it from collisionheight to 0.5 was that some creatures were climbing floors. half height solves it.

**Comment by UltraNix** [comment]
I think this one has been resolved some time ago.
