### ISSUE TITLE
Firemane Flamecaller Spawning Inside Wall

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5766]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/594

There's a Firemane Flamecaller spawning inside the wall next to Emberstrife's cavern in Dustwallow Marsh. The GUID is 30504.

![WoWScrnShot_051021_213646](https://user-images.githubusercontent.com/81782124/117657169-675afa80-b1d8-11eb-834f-ec1825f46784.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It shouldn't spawn inside a wall

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 30504
2. There should be a Firemane Flamecaller inside the wall to the right of Emberstrife's cavern

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/61223313/117743912-f3fbbd80-b1c4-11eb-939f-e2325ad516b7.png)
