### ISSUE TITLE
Blink in Multiple Cave Systems Clipping to Roof

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5768]
**CURRENT BEHAVIOUR:**

Originally reported: @karakter222 on Discord.

Mage blink is currently clipping through the walls of at least two identified cave systems and onto the roof. The areas accessed this way are unfinished, untextured, and definitely not meant to be seen by players. 

The two cave systems are Stonesplinter cave in Loch Modan, and Coldridge cave in Dun Morogh. Others that share this model may also be affected.

https://user-images.githubusercontent.com/81782124/117684543-40aabd00-b1f4-11eb-9050-befdfc11407e.mp4

(Note that the faster run speed was turned off later in case it was affecting Blink somehow, and it made no difference.)

https://user-images.githubusercontent.com/81782124/117687544-0db5f880-b1f7-11eb-9cfa-4ab96d26dfca.mp4

Shot from @karakter222 from within Chromie:
![karak-blink1](https://user-images.githubusercontent.com/81782124/117684962-a8610800-b1f4-11eb-8132-0f43e60f4a03.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Blink should not teleport you through walls.

**SOURCE:**

I don't think this claim is controversial.

**STEPS TO REPRODUCE THE PROBLEM:**

1. To access Stonesplinter, .go c 9264. That will port you to a random mob halfway through the cave.
2. Run around spamming Blink. Stoneplinter is much the easier of the two caves to get this to work in.

For Coldridge - .go c 1502 will take you to the boss. Coldridge is harder to glitch, but karakter got it to work from here:
![karak-blink2](https://user-images.githubusercontent.com/81782124/117685161-d0506b80-b1f4-11eb-8cd2-9d88aebff483.png)

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
rev. 0079034d7300 2021-05-10 00:58:22 -0600

**OPERATING SYSTEM:**

Linux Mint 20.1

**MODULES:**

N/A.

**CUSTOMIZATIONS:**

N/A.

**Comment by Eldarix** [comment]
Confirmed in both caves, with a gnome BTW :)

Stonesplinter:

![WoWScrnShot_051121_014248](https://user-images.githubusercontent.com/82579073/117733835-e95c1b00-b1fa-11eb-874c-2cf5373676c4.jpg)
![WoWScrnShot_051121_014636](https://user-images.githubusercontent.com/82579073/117733843-ebbe7500-b1fa-11eb-85dc-ec8096a0ef50.jpg)
![WoWScrnShot_051121_014741](https://user-images.githubusercontent.com/82579073/117733848-ed883880-b1fa-11eb-8584-42a0f77e7a51.jpg)

Coldridge:

![WoWScrnShot_051121_014555](https://user-images.githubusercontent.com/82579073/117733903-0a247080-b1fb-11eb-9414-6f70b2295b6e.jpg)
![WoWScrnShot_051121_014601](https://user-images.githubusercontent.com/82579073/117733906-0b559d80-b1fb-11eb-8bbe-ebad58d56f68.jpg)
![WoWScrnShot_051121_014610](https://user-images.githubusercontent.com/82579073/117733910-0d1f6100-b1fb-11eb-8912-00dcf7f4eda3.jpg)

**Comment by Azcobu** [comment]
Tested Skull rock in Durotar, and Splithoof Crag in Thousand Needles.
Both are also affected:

https://user-images.githubusercontent.com/81782124/117808227-c6357800-b29b-11eb-8387-28c025476608.mp4

https://user-images.githubusercontent.com/81782124/117808242-cafa2c00-b29b-11eb-9c65-43c678aa7d53.mp4

**Comment by karakter222** [comment]
This also hapens in Render's rock in a lot of places


![image](https://user-images.githubusercontent.com/54365532/118829790-b5e65400-b8be-11eb-942b-7827ba4499de.png)
