### ISSUE TITLE
[DUNGEON] Trial of the Champion enemies don't walk into the coliseum.

### ISSUE THREAD

**Issue by Alastyr** [azerothcore/azerothcore-wotlk#577]
**Description**: Trial of the Champion's champion bosses appear suddenly instead of walking into the coliseum

**Current behaviour**: When you start first boss at ToC 5(n/h don't care), faction champions apper suddenly into the coliseum.

**Expected behaviour**: You speak with Arelas Brighstar (npc=35005 if ally) or Jaeren Sunsworn (npc=35004 if horde). He walks away. Enemies enter from the gate.

**Steps to reproduce the problem**:

1. Go to ToC
2. Speak with Arelas Brighstar/Jaeren Sunsworn
3. Watch enemies appear suddenly

Watch few second of video from better understanding: https://www.youtube.com/watch?v=SE2aOA2f0zM

**Branch(es)**: Master(?)

**AC hash/commit**:  31174b6d4907 2017-06-07 01:41:26 +0200 (custom branch) 

**Operating system**:  I'm playing on AzerothShard server with its os.

**Modules**:  Donnow what are you talking about.

**Other Customizations**: AzerothShard custom implementations.

**Comment by Jagermaister95** [comment]
Hello then looks sorry but the report you made is incorrect as on our server you can start Toc in two ways. The first one is the one that also appears in the complete event video, the second is the "fast" one where the npcs appear instantly without event. Reporting is therefore not valid.

**Comment by StygianTheBest** [comment]
Close the issue if it's an error on your part.

**Comment by Alastyr** [comment]
That's my fail. I'm sorry for this mistake. You can close this issue.

**Comment by ShinDarth** [comment]
no problem @Alastyr , I appreciate your help
