### ISSUE TITLE
[NPC] Lord Thorval creature_text error

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#578]
**Description**: This error is reported by worldserver when a new death knight is created. The error repeats several times. I do not remember this being an error on  f353f9b5bb08cde4d75b13c1c1c33ae35da971b4.

>CreatureTextMgr: Could not find Text for Creature(Lord Thorval) Entry 28472 in '
creature_text' table. Ignoring.

**Expected behavior:** 
No errors!

**Steps to reproduce the problem:**
Create a Death Knight. 

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Karitoswow** [comment]
Fixed ErrorDB Lord Thorval creature_text error
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','0','0','As disciples of blood, you strive to master the very lifeforce of your enemies.','12','0','100','1','0','0','29867','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','1','0','Be it by blade or incantation, blood feeds our attacks and weakens our foes.','12','0','100','1','0','0','29868','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','2','0','True masters learn to make blood serve more than just their strength in battle.','12','0','100','1','0','0','29869','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','3','0','Stripping energy from our foes, both fighting and fallen, allows us to persevere where lesser beigns falls exhausted.','12','0','100','1','0','0','29870','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','4','0','And every foe that falls, energy sapped and stolen, only further fuels our assault.','12','0','100','1','0','0','29871','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','5','0','As masters of blood, we know battle without end...','12','0','100','1','0','0','29872','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','6','0','We know hunger never to be quenched...','12','0','100','1','0','0','29873','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','7','0','We know power never to be overcome...','12','0','100','1','0','0','29874','0','Lord Thorval');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `broadcasttextid`, `textRange`, `comment`) values('28472','8','0','As masters of blood, we are masters of life and death itself. Agains us, even hope falls drained and lifeless.','12','0','100','1','0','0','29875','0','Lord Thorval');

**Comment by ShinDarth** [comment]
@Karitoswow please [open a Pull Request](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request)

**Comment by Karitoswow** [comment]
ok tq

**Comment by Karitoswow** [comment]
Hello my friend
  Thank you for updating the project every day ,Please keep in mind the
essential daily schedule , We need to be strong and strong against Attak
Server(DDOS)
I sincerely appreciate your cooperation Happy Day

**Comment by STARRHELD** [comment]
```SQL
-- Lord Thorval
SET @ENTRY := 28472;
DELETE FROM `creature_text` WHERE `entry`=@ENTRY;
INSERT INTO `creature_text` (`entry`,`groupid`,`id`,`text`,`type`,`language`,`probability`,`emote`,`duration`,`sound`,`comment`, `BroadcastTextId`) VALUES
(@ENTRY, 0, 0, 'As disciples of blood, you strive to master the very lifeforce of your enemies.',                                       12, 0, 100, 1, 0, 0, 'Lord Thorval', 29867),
(@ENTRY, 1, 0, 'Be it by blade or incantation, blood feeds our attacks and weakens our foes.',                                          12, 0, 100, 1, 0, 0, 'Lord Thorval', 29868),
(@ENTRY, 2, 0, 'True masters learn to make blood serve more than just their strength in battle.',                                       12, 0, 100, 1, 0, 0, 'Lord Thorval', 29869),
(@ENTRY, 3, 0, 'Stripping energy from our foes, both fighting and fallen, allows us to persevere where lesser beigns falls exhausted.', 12, 0, 100, 1, 0, 0, 'Lord Thorval', 29870),
(@ENTRY, 4, 0, 'And every foe that falls, energy sapped and stolen, only further fuels our assault.',                                   12, 0, 100, 1, 0, 0, 'Lord Thorval', 29871),
(@ENTRY, 5, 0, 'As masters of blood, we know battle without end...',                                                                    12, 0, 100, 1, 0, 0, 'Lord Thorval', 29872),
(@ENTRY, 6, 0, 'We know hunger never to be quenched...',                                                                                12, 0, 100, 1, 0, 0, 'Lord Thorval', 29873),
(@ENTRY, 7, 0, 'We know power never to be overcome...',                                                                                 12, 0, 100, 1, 0, 0, 'Lord Thorval', 29874),
(@ENTRY, 8, 0, 'As masters of blood, we are masters of life and death itself. Agains us, even hope falls drained and lifeless.',        12, 0, 100, 1, 0, 0, 'Lord Thorval', 29875);
```
