### ISSUE TITLE
Prospecting Thorium doesn't always yield a gem

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5781]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original issue from Chromiecraft
[https://github.com/chromiecraft/chromiecraft/issues/600](https://github.com/chromiecraft/chromiecraft/issues/600)
Occasionally when prospecting thorium you get a blank window instead of actually getting a gem. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[https://wowwiki-archive.fandom.com/wiki/Prospecting](https://wowwiki-archive.fandom.com/wiki/Prospecting)
As of patch 2.1.0 prospecting always yields at least 1 gem

##### STEPS TO REPRODUCE THE PROBLEM:

1. .additem 10620 300
2. set your prospecting to a number key and start tapping
3. 

##### EXTRA NOTES:
Prospected 300 of all ores that can be prospected, and I've only found thorium to give a blank.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
@dillyns @FrancescoBorzi Not fixed.
Roughly a 10% chance of not getting anything, but you don't get any TBC gems either. Maybe this is related.

**Comment by Kitzunu** [comment]
Only reason to why something does not drop in a bag/prospecting/whatever is if the total chance != 100 somewhere in either the main loot template or reference

**Comment by necropola** [comment]
Group 0 only contains the reference table for TBC gems at a 10% chance
Group 1 has all Vanilla gems with combined chance of 90%.

**Comment by Kitzunu** [comment]
My bad :D
