### ISSUE TITLE
[Herb] Out of place herb nodes in the Barrens 

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#5782]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Wild Steelbloom spawns 4198 and 4252 are located in an out of place position on a high ledge on the boundary of the Barrens (see the minimap). 

![WoWScrnShot_050921_181020](https://user-images.githubusercontent.com/39011611/117579114-c98d0000-b0f1-11eb-8679-d0721bcad102.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The nodes should be moved lower where they're more easily accessible. Their current position is a bit difficult to access, and I don't think players are meant to walk around up there to begin with.

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.go o 4198`
2. `.go o 4252`
3. `.gobject near 20` to show both nodes

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/588"

Confirmed and reproduced on a local AC server :

![WoWScrnShot_051121_102032](https://user-images.githubusercontent.com/82579073/117775294-0b798b80-b243-11eb-9b8e-2ac196c34d4d.jpg)
![WoWScrnShot_051121_102155](https://user-images.githubusercontent.com/82579073/117775301-0ddbe580-b243-11eb-9420-b58775577b93.jpg)
![WoWScrnShot_051121_102227](https://user-images.githubusercontent.com/82579073/117775322-12080300-b243-11eb-88b8-2093906180b7.jpg)

**Comment by FrancescoBorzi** [comment]
@Eldarix thanks for this report. Just one minor note: this bug affects a specific zone (The Barrens) so it's not a "generic" issue :)

**Comment by Eldarix** [comment]
I thought that for being herbs related; the level didn't matter, got it ;)
