### ISSUE TITLE
Bad implementation of Root Samples quest negatively affects the drop rate of Swiftthistle from herbs in the Barrens zone

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#5792]
This has to do with the quest Root Samples (quest id 866). According to https://classic.wowhead.com/quest=866/root-samples, the herbs Silverleaf, Earthroot, Peacebloom, Mageroyal, Briarthorn, Bruiseweed in the Barrens zone should have a chance of containing 1 Root Sample, while the quest is active and in the correct stage. According the comments, this chance is 100% (the drop rates under https://classic.wowhead.com/item=5056/root-sample#gathered-from-object are wrong). Because only Barrens herbs are meant to be affected, each of the herbs listen above should have 2 variations: 
  1. one that only spawns in the Barrens and can drop Root Samples
  2. one that spawns everywhere else and does not contain Root Samples. 
This should not affect the drop rate of Swiftthistle, which is a secondary drop of Briarthorn and Mageroyal plants.

**CURRENT BEHAVIOUR:**
 - (a) herbs of variation 2 spawn inside the Barrens (tested)
 - (b) herbs of variation 1 might spawn outside the Barrens (not tested)
 - (c) the loot tables are absolutely messed up: 
    - variation 1 of Briarthorn and Mageroyal never contain Swiftthistle
    - variation 1 of Briarthorn never contains Root Sample
    - both variations of herbs (apart from Briarthorn) contain Root Sample
    - variation 1 herbs should contain 1-3 primary drops instead of 2-2

Current loot table: (output of https://pastebin.com/Rrmhuc6k)
```
+---------+------------+---------+--------------+-----+---+-----+-----+
| gobt_id | gobt       | item_id | item         | %   | q | min | max |
+---------+------------+---------+--------------+-----+---+-----+-----+
|    1617 | Silverleaf |     765 | Silverleaf   | 100 | 0 |   1 |   3 |
|    1617 | Silverleaf |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    1618 | Peacebloom |    2447 | Peacebloom   | 100 | 0 |   1 |   3 |
|    1618 | Peacebloom |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    1619 | Earthroot  |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    1619 | Earthroot  |    2449 | Earthroot    | 100 | 0 |   1 |   3 |
|    1620 | Mageroyal  |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    1620 | Mageroyal  |    2452 | Swiftthistle |  20 | 0 |   1 |   2 |
|    1620 | Mageroyal  |     785 | Mageroyal    | 100 | 0 |   1 |   3 |
|    1621 | Briarthorn |    2452 | Swiftthistle |  40 | 0 |   1 |   2 |
|    1621 | Briarthorn |    2450 | Briarthorn   | 100 | 0 |   1 |   3 |
|    1622 | Bruiseweed |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    1622 | Bruiseweed |    2453 | Bruiseweed   | 100 | 0 |   1 |   3 |
|    3724 | Peacebloom |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3724 | Peacebloom |    2447 | Peacebloom   | 100 | 0 |   2 |   2 |
|    3725 | Silverleaf |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3725 | Silverleaf |     765 | Silverleaf   | 100 | 0 |   2 |   2 |
|    3726 | Earthroot  |    2449 | Earthroot    | 100 | 0 |   2 |   2 |
|    3726 | Earthroot  |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3727 | Mageroyal  |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3727 | Mageroyal  |     785 | Mageroyal    | 100 | 0 |   2 |   2 |
|    3729 | Briarthorn |    2450 | Briarthorn   | 100 | 0 |   2 |   2 |
|    3730 | Bruiseweed |    2453 | Bruiseweed   | 100 | 0 |   2 |   2 |
|    3730 | Bruiseweed |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
+---------+------------+---------+--------------+-----+---+-----+-----+
```

**EXPECTED BLIZZLIKE BEHAVIOUR:**
 See first paragraph.

Output of above sql should be this (according to data from https://classic.wowhead.com/):
```
+---------+------------+---------+--------------+-----+---+-----+-----+
| gobt_id | gobt       | item_id | item         | %   | q | min | max |
+---------+------------+---------+--------------+-----+---+-----+-----+
|    1617 | Silverleaf |     765 | Silverleaf   | 100 | 0 |   1 |   3 |
|    1618 | Peacebloom |    2447 | Peacebloom   | 100 | 0 |   1 |   3 |
|    1619 | Earthroot  |    2449 | Earthroot    | 100 | 0 |   1 |   3 |
|    1620 | Mageroyal  |    2452 | Swiftthistle |  20 | 0 |   1 |   2 |
|    1620 | Mageroyal  |     785 | Mageroyal    | 100 | 0 |   1 |   3 |
|    1621 | Briarthorn |    2452 | Swiftthistle |  40 | 0 |   1 |   2 |
|    1621 | Briarthorn |    2450 | Briarthorn   | 100 | 0 |   1 |   3 |
|    1622 | Bruiseweed |    2453 | Bruiseweed   | 100 | 0 |   1 |   3 |
|    3724 | Peacebloom |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3724 | Peacebloom |    2447 | Peacebloom   | 100 | 0 |   1 |   3 |
|    3725 | Silverleaf |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3725 | Silverleaf |     765 | Silverleaf   | 100 | 0 |   1 |   3 |
|    3726 | Earthroot  |    2449 | Earthroot    | 100 | 0 |   1 |   3 |
|    3726 | Earthroot  |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3727 | Mageroyal  |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
|    3727 | Mageroyal  |    2452 | Swiftthistle |  20 | 0 |   1 |   2 |
|    3727 | Mageroyal  |     785 | Mageroyal    | 100 | 0 |   1 |   3 |
|    3729 | Briarthorn |    2450 | Briarthorn   | 100 | 0 |   1 |   3 |
|    3729 | Briarthorn |    5056 | Root Sample  | 100 | 1 |   1 |   3 |
|    3729 | Briarthorn |    2452 | Swiftthistle |  40 | 0 |   1 |   2 |
|    3730 | Bruiseweed |    2453 | Bruiseweed   | 100 | 0 |   1 |   3 |
|    3730 | Bruiseweed |    5056 | Root Sample  | 100 | 1 |   1 |   1 |
+---------+------------+---------+--------------+-----+---+-----+-----+
```

**STEPS TO REPRODUCE THE PROBLEM:**

 1. `.quest add 866`
 3. `.setskill 182 300 300`
 3. `.learn 2366` 
 4. pick some of the mentioned herbs, both inside and outside the Barrens, and observe the flaws listed above.

**EXTRA NOTES:**
How to fix:
As far as I can tell there is no simple way to determine which zone a gob belongs to; there is an undocumented `zoneId` column in `gameobject` but it only has 10 distinct values so that can't be it. The only solution I can think of is a https://en.wikipedia.org/wiki/Point_in_polygon algorithm (the z axis can be ignored so we're working in 2D space). The exact boundary coordinates can probably be extracted from the dbc somehow, but we don't need to be super-duper precise with this.

 - construct rough bounding polygon of the Barrens zone
 - on the Kalimdor map, replace all occurences of variation 2 herbs on the plane with their variation 1 counterparts - fixes (a)
 - on the Kalimdor map, replace all occurences of variation 1 herbs on the plane with their variation 2 counterparts - fixes part of (b)
 - on all other maps, replace all occurences of variation 1 herbs with their variation 2 counterparts - fixes part of (b) 
 - fix the loot tables - fixes (c)

I'd be willing to allocate some time to this if needed.

**AC HASH/COMMIT:**
0079034

**Comment by anguaive** [comment]
I did some research and it turns out the worldserver is able to fill in the `areaId` and `zoneId` columns of gameobjects on startup by enabling `Calculate.Creature.Zone.Area.Data` in the config (there's a separate config entry for creatures too). If the data this spits out is correct then all that's left to do is writing the SQL update. 

## To do:
- [ ] document what areaId and zoneId mean and how to obtain them (currently undocumented)
- [ ] fix the loot tables
- [ ] swap herb variants where necessary

**Comment by T1ti** [comment]
area id and zone id come from aretable.dbc
You can use Noggit to visualzie them better, zone ID is the whole zone (like duskwood) and area id is a part of the zone(like raven hill)

areas IDs have zone IDs set as parent area IDs
ID 10 is duwkwood
![image](https://user-images.githubusercontent.com/40864460/119269101-4b068700-bbf6-11eb-8b1f-16c63fac5bc2.png)

ID 492 Raven Hill cemetary is an area of duskwood, it has Duskwood(10) set as the parent ID(zone ID)
![image](https://user-images.githubusercontent.com/40864460/119269126-696c8280-bbf6-11eb-91f6-dd6d4f8e338c.png)

![image](https://user-images.githubusercontent.com/40864460/119269175-aafd2d80-bbf6-11eb-9f4c-c8e2961faf8c.png)

**Comment by T1ti** [comment]
Also it seems that blizz do store that data for each sapwns in their database, they probably use that for zone/area specific loots and effects
This comes from a sniff 
![image](https://user-images.githubusercontent.com/40864460/119269264-08917a00-bbf7-11eb-9e81-2b47ac55d3af.png)

**Comment by anguaive** [comment]
Thanks! Haven't heard about Noggit yet. Looks pretty cool
