### ISSUE TITLE
Ornate Spyglass Not Extending Resource Tracking Distance

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5793]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/607

Engineering Item: Ornate Spyglass is supposed to extend view distance and show mobs and players at a further distance, and gathering nodes at a further distance on the minimap when used

Tester's notes: tried this by running to away from a resource node until it just barely disappeared, then looking at it with the Spyglass. The node did not reappear on the minimap.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Ornate Spyglass is supposed to extend view distance and show mobs and players at a further distance, and gathering nodes at a further distance on the minimap when used.

**SOURCE:**

One example of it loading players at a longer view distance https://youtu.be/TJnCIeWIBrc?t=70

"Out of battlegrounds, it does load in extra players and objects."

"very useful item, extends the range of all tracking abilities. so zoom out you mini map to max range, use the spyglass and all nodes herbs and what not show up."

"Your track abilities/professions will see FURTHER on minimap, i use this all the time to see inside mines without ever going close, just look in direction and clicky, you can track things about twice as far as normal, in direction you are facing."

"I find it extremely useful for mining. If you zoom in with it, you can look for minerals much better. Under normal circumstances, you can only "see" minerals near you. When you use the spyglass, you field of vision increases, and you can detect minearals much further away." (all from https://classicdb.ch/?item=5507#comments)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Find a gather node,,, 
2.  Run away from it until it disappears from your minimap
3.  Look in it's direction with the Spyglass
4. It should appear on the minimap. It does not because its broken.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
I need info about that view distance? Is it 100 yards or maybe more/less? In battleground it's different?

**Comment by UltraNix** [comment]
@Azcobu 
I need info about that view distance? Is it 100 yards or maybe more/less? In battleground it's different?

**Comment by Azcobu** [comment]
The Longsight effect the items uses (https://tbc.wowhead.com/spell=12883/longsight) says 100 yard range on the tooltip, and I don't have any info to contradict that.

As for battlegrounds, it's the usual contradictory mess. One person in comments claims "it doesn't load in players or objects that you normally wouldn't have been able to see" in BGs but everyone else seems to disagree with them. There's a screenshot (https://i352.photobucket.com/albums/r353/kevin902/bilde1.jpg) taken from AB's lumber mill looking at the farm that clearly shows players a long way off. The ability to spy n BGs was also a big selling point for this item. So on balance I think the behaviour is probably the same in BGs as outside it.
