### ISSUE TITLE
Stranglekelp Nodes Too Far Inland

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5794]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [ ] Horde
- [x] Both

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/608

Stranglekelp grows either underwater or on the shoreline. I noticed a bunch of nodes relatively far inland high up on a hill.

Identified nodes are: 
```
8570 (Entry: 2045) - [Stranglekelp X:-1335.000000 Y:-3707.000000 Z:95.588997 MapId:1]
8382 (Entry: 2045) - [Stranglekelp X:-1294.000000 Y:-3688.000000 Z:103.042000 MapId:1]
8231 (Entry: 2045) - [Stranglekelp X:-1160.000000 Y:-3677.000000 Z:93.194000 MapId:1]
8466 (Entry: 2045) - [Stranglekelp X:-1179.000000 Y:-3662.000000 Z:96.897003 MapId:1]
8452 (Entry: 2045) - [Stranglekelp X:-1178.000000 Y:-3668.000000 Z:95.043999 MapId:1]
```

Tester's notes: visited all these, can confirm they are much too far away from the sea.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[Stranglekelp can be found underwater in coastal areas. It can also be obtained rarely by Fishing.](https://wowwiki-archive.fandom.com/wiki/Stranglekelp?oldid=2383592)

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.go obj $asAbove`
2.  Observe

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by jamadaha** [comment]
Tested on local server(AC dd833a25a) 
There are actually a few more:
|In Land (guid)| A bit off coast (guid)|
| ----- | ----- |
|8231|8282|
|8382|8294|
|8383|8296|
|8384|8347|
|8425|8448|
|8426|8504|
|8452|8505|
|8466|8508|
|8507|
|8570|

These were found using the command
SELECT * FROM \`pool_gameobject\` WHERE \`description\` LIKE \'%Stranglekelp,Zone 17%\' AND \`guid\` < 10000;

Zone 17 is the Barrens
Stranglekelp with guid under 10000 are those which are not underwater (In this zone. It is different in other zones e.g. 8325)

Those in the left column are wrong, while those on the right are debatable.
