### ISSUE TITLE
Searing Gorge - Multiple Node Spawns On Same Spot

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5795]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Original report: https://github.com/chromiecraft/chromiecraft/issues/611

In Searing Gorge is a spot with least 4 node spawns at the same spot.

![grafik](https://user-images.githubusercontent.com/83700197/117813479-6a4efd00-b263-11eb-806f-f597b71d59d3.png)
![WoWScrnShot_051221_001732](https://user-images.githubusercontent.com/81782124/117836361-c479ad80-b2b7-11eb-99ea-72616c0e33f0.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should not spawn into each other.

##### STEPS TO REPRODUCE THE PROBLEM:
At least 4 different Ores in one Spot spawning:

1. .go o 5850
2. Observe a rare triple node spawn.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
I would merge this issue with https://github.com/azerothcore/azerothcore-wotlk/issues/5424

**Comment by Azcobu** [comment]
I'll close this one as the relevant nodes were reported there, my mistake.
