### ISSUE TITLE
Mobs clipping through Ziggurats

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5796]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mobs are clipping through Ziggurats in Ghostlands. This seems to happen on all ziggurats. I tested Bleeding and Howling ziggurats as well as the ones in Deatholme to the south. I couldn't really tell with the ones from the plaguelands, they were melee mobs inside.

![image](https://user-images.githubusercontent.com/68164076/117911777-34297180-b293-11eb-9986-6c2c36b4c12c.png)
![image](https://user-images.githubusercontent.com/68164076/117911829-4c00f580-b293-11eb-8e06-d99f063ebf28.png)
![image](https://user-images.githubusercontent.com/68164076/117911882-5f13c580-b293-11eb-8040-cc3293706ba8.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Aggro'd mobs should walk out of the entrance like normal dark-art enthusiasts. Not go through walls like the Koolaid man.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele bleeding zig
2. Mark up a few mobs and aggro
3. Run outside and watch the marked mobs scramble around before walking around from the side of the ziggurat.
4. You can run across the way and check the howling ziggurat as well if you want.

##### EXTRA NOTES:

Original report form Chromicraft [https://github.com/chromiecraft/chromiecraft/issues/622](https://github.com/chromiecraft/chromiecraft/issues/622)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by malcrom** [comment]
Can't duplicate.
