### ISSUE TITLE
Alliance druid quest "Lessons Anew" uses Horde completion text 

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#5799]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Title is pretty self-explanatory. NPC Dendrite Starblaze uses the completion text for the Horde (Tauren) version of this quest for Alliance (Night Elf) players.

![WoWScrnShot_051121_033723](https://user-images.githubusercontent.com/83389835/117892734-df7bfb80-b27e-11eb-8471-cf816ce7a381.jpg)

wowgaming database has incorrect text too https://wowgaming.altervista.org/aowow/?quest=6121

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC should use the Alliance text for Alliance players and Horde text for Horde players

https://tbc.wowhead.com/quest=6121/lessons-anew has correct completion text for Alliance

##### STEPS TO REPRODUCE THE PROBLEM:

1. Reach level 14 on a Night Elf Druid, then accept the quest "Lessons Anew" from the class trainer in Darnassus (may have to do lv.10 bear form quest first, idk)
2. Teleport to Moonglade and talk to the NPC you turn the quest into (Dendrite Starblaze)
3. Read the text, and notice it talks about Crossroads/The Barrens when Auberdine/Darkshore is the area of focus for this quest

##### EXTRA NOTES:

text differences between alliance and horde versions of the quest:
<img width="694" alt="Screenshot (347)A" src="https://user-images.githubusercontent.com/83389835/117894603-51a20f80-b282-11eb-9e7a-d8cc34d436b6.png">

<img width="695" alt="Screenshot (346)H" src="https://user-images.githubusercontent.com/83389835/117894622-5ebefe80-b282-11eb-9e8a-acbfaa086c03.png">

.npc info for NPC who says the text:
![WoWScrnShot_051121_181219](https://user-images.githubusercontent.com/83389835/117895871-edcd1600-b284-11eb-8dd9-c7f995ac492d.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/625"

Confirmed and reproduced on a local AC server :

![WoWScrnShot_051221_123356](https://user-images.githubusercontent.com/82579073/117953318-967b8400-b31e-11eb-851b-6249d8a95ee9.jpg)
![WoWScrnShot_051221_123437](https://user-images.githubusercontent.com/82579073/117953346-9b403800-b31e-11eb-9ab4-1a5c44f2b36e.jpg)

**Comment by Kitzunu** [comment]
I can fix this in the afternoon

**Comment by Kitzunu** [comment]
fixed for both ally and horde
