### ISSUE TITLE
[SERVER] PlayerStart.AllReputation not working as intended.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#580]
**Description**: The worldserver.conf.dist custom server option 'PlayerStart.AllReputation' is not working as intended. I tested by setting the option to on and off and was met with the same result.

> PlayerStart.AllReputation
        Description: Players will start with most of the high level reputations that are needed
                     for items, mounts etc.
        Default:     0 - (Disabled)
                     1 - (Enabled)
PlayerStart.AllReputation = 1

**Expected behavior:** 
The player should start with most of the main city factions at Exalted status to allow the purchase of items, mounts, etc.

**Steps to reproduce the problem:**
Set PlayerStart.AllReputation = 1 in worldserver.conf.dist

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Inifield** [comment]
I fixed it on my side, however I propose to move all custom settings in one cpp easier to maintain in the future, thought ?

**Comment by ShinDarth** [comment]
can you please open a PR?

**Comment by BarbzYHOOL** [comment]
From inifield https://cdn.discordapp.com/attachments/284323424032129024/351314733686849537/reputation.patch (i post it to save the link)
