### ISSUE TITLE
Kul Tiras Marine Falling Through Floor

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5800]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/597

[Youtube Video - Too Large To Upload To Github](https://www.youtube.com/watch?v=jxeGD2jqiEw)
[Second Video - Shows clipping through wall](https://www.youtube.com/watch?v=7xLSmA6vMAg)
I ran .npc info and all the relevant information can be found in the following new clip:
[Third Video - Including Npc Info](https://www.youtube.com/watch?v=9x_uP0RU6Bs)

As can be seen in the video provided the Kul Tiran Marine at the entrance of the ruined keep spawns underground.

Tester's notes: GUID is 12341. The interesting thing is he's not spawning underground, he's falling there from upstairs. This was impossible to replicate on my own test server, eventually had to go to the live CC server to see him.

Laser pointer showing his usual spawn point upstairs:
![WoWScrnShot_051221_002957](https://user-images.githubusercontent.com/81782124/117967020-c13bfb80-b363-11eb-9541-77c6d11ac229.jpg)

Marine lurking underground on CC:
![WoWScrnShot_051221_204407](https://user-images.githubusercontent.com/81782124/117967699-8090b200-b364-11eb-9ca8-ad8776a4da22.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC shouldn't fall through the floor.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 12392 will take you to a mob right outside the door.
2. Notice mob Kul Tiran Marine wondering underground.

If you're testing on a newly-started AC server, he probably won't be bugged yet. This seems to be another one of the clipping errors that needs the server to run for some time before occurring.

##### EXTRA NOTES:

Out of 3 spawns I've encountered 2 were underground and 1 was both underground and aboveground clipping through the walls.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5778#issuecomment-837632280
