### ISSUE TITLE
Scarlet Key Dropping From Mobs

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5806]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/618

When inside the library dungeon, we were getting scarlet key drops. We seemed to only get them off of monks however, so probably just a miss tagged loot table.

Tester's notes: checked Keira, and Scarlet Monks (4540), Chaplains (4299) and Diviners (4291) all have the Scarlet Key (ID 7146) in their loot tables, albeit at 0.02% drop.

Screenshot attached of the drop:
![WoWScrnShot_051121_123614](https://user-images.githubusercontent.com/26581194/117860990-88623080-b256-11eb-903e-6b6d91e12303.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The key should only come out of the chest after Doan in library, not off random mobs.

"You get the key from a chest after finishing the Library wing in SM." (https://classic.wowhead.com/item=7146/the-scarlet-key#comments:id=52)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Kill mobs in library, I have not seen this before tho, but it happened twice in 1 run.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
I needed to clear the dungeon 4 times but I certainly found it (Local AC setup):

![WoWScrnShot_051221_170746](https://user-images.githubusercontent.com/82579073/117989421-fab13e80-b344-11eb-8118-5c60006f8566.jpg)
![WoWScrnShot_051221_170753](https://user-images.githubusercontent.com/82579073/117989447-00a71f80-b345-11eb-9cda-e58556a92b0c.jpg)
