### ISSUE TITLE
[SERVER] GM cannot summon players to instances

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#581]
**Description**: A change by "pussywizard" (somehow I doubt he was) prevents GMs from summoning players to instances. Trinity allows this, so maybe they fixed the issue he was trying to prevent with locks, but I think the GM should be able to pull a player into a dungeon if he desires. I'm sure there's a way to have the best of both worlds. I've commented out this section to remove the issue.

>// pussywizard: prevent unbinding normal player's perm bind by just summoning him >_>
                if (!target->GetSession()->GetSecurity())
                {
                    handler->PSendSysMessage("Only GMs can be summoned to an instance!");
                    handler->SetSentErrorMessage(true);
                    return false;
                }

**Expected behavior:** 
As with Trinity, the GM has the power to teleport players into an instance. I suggest we make it so that only players currently in the group with the GM be able to be summoned, but perhaps there's a better solution.

**Steps to reproduce the problem:**
Try to summon a player while in a dungeon.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Yehonal** [comment]
could you try to comment that code and see what issue does it cause? 
We dunno if TC fixed it because TC always permitted it.

Anyway, you can workaround it using .groupsummon command, in fact groupsummon requires that you're in that party/raid and maybe it's more safe

**Comment by StygianTheBest** [comment]
I didn't even know about that command. I'll uncomment that block and see if it allows them to be summoned into an instance. I've had it commented out for a while and haven't noticed anything strange, but my server hosts less than 50 players.

**Comment by Viste** [comment]
GMs are fucking idiots in allmost all servers so its nice option. In fact we can add a conf option for this

**Comment by StygianTheBest** [comment]
01010110 01101001 01110011 01110100 01100101 00100000 01101001 01110011 00100000 01100001 00100000 01100100 01101111 01110101 01100011 01101000 01100101

**Comment by Inifield** [comment]
You shouldn't summon players in a instance, this is more a feature than a bug, we should add a feature label or custom one

**Comment by StygianTheBest** [comment]
@Inifield The .groupsummon command is also blocked from pulling players into the instance. I like the ability to port dead players back into the instance alive without them having to do a corpse run and waste everyone's time. So yeah, that's why I didn't label it as a bug. It's more of a QOL feature and should only work on players that are part of the instance lock they are being ported into.
