### ISSUE TITLE
Dying in certain areas in EPL results in being sent to Acherus Graveyard 

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5815]
WHAT CLIENT DO YOU PLAY ON?

enGB
[X ] enUS

    other (specify)

FACTION

    [X ] Alliance

    Horde

CONTENT PHASE:

Generic
1-19
20-29
[X ] 30-39
40-49

    50-59

CURRENT BEHAVIOUR:

Dying in approximately this spot brings you to the spirit healer in Acherus. There is no way to rez without spirit healing.

Abuse case for hunters is ability to buy level 40-65 bullets in vicinity of EPL, saving time while farming.
Abuse case for plate wearers is being able to buy white-quality armor. It is not 'good', but is otherwise inaccessible in current bracket.
EXPECTED BLIZZLIKE BEHAVIOUR:

Only DKs can access this zone, as stated by this comment on WoWhead:
image
STEPS TO REPRODUCE THE PROBLEM:

    Die in approximately this location:
    image
    Release and your spirit should be in Acherus.

EXTRA NOTES:

Type here.
AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@6947789
OPERATING SYSTEM:

Ubuntu 20.04
MODULES:

    mod-cfbg
    mod-duel-reset
    mod-desertion-warnings
    mod-ah-bot
    mod-eluna-lua-engine
    mod-server-auto-shutdown
    lua-LevelUpReward
    lua-CarbonCopy
    mod-pvp-titles

OTHER CUSTOMIZATIONS:

None.
SERVER:

ChromieCraft

https://github.com/chromiecraft/chromiecraft/issues/631

**Comment by FrancescoBorzi** [comment]
@JamesGent please click on "edit" of the original report and copy-paste the **raw** text (markdown):

![image](https://user-images.githubusercontent.com/75517/118121050-28ec5800-b3f1-11eb-96ed-ab549afacc8e.png)

so it will look much better.

Also about checkboxes:

![image](https://user-images.githubusercontent.com/75517/118121120-3dc8eb80-b3f1-11eb-9408-ec651748b37e.png)
