### ISSUE TITLE
Visual glitch on Ironforge library museum plates

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5819]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I have noticed that in the Library of Ironforge, there are some information plates that do not appear visually correct.

When looking at it from the front it disappears completely and when you turn the camera you see only the edge.
##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should appear correctly visible.
##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Ironforge Library.
2. Look at the info plates.
3. See if the described issue exist.

##### EXTRA NOTES:
![WoWScrnShot_051221_195214](https://user-images.githubusercontent.com/82579073/118089206-cb481380-b3d0-11eb-93b8-ba86ee24dcb0.jpg)
![WoWScrnShot_051221_195222](https://user-images.githubusercontent.com/82579073/118089252-d307b800-b3d0-11eb-8f0f-998e12751564.jpg)
![WoWScrnShot_051221_195230](https://user-images.githubusercontent.com/82579073/118089291-d8650280-b3d0-11eb-84b9-580c437aeef2.jpg)

##### AC HASH/COMMIT:

ff2737fee8d022e90298a63baaa4751d599f6564

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

Chromiecraft

**Comment by Si1ker** [comment]
Isn't this already fixed by #4924 ???

**Comment by Kitzunu** [comment]
I can confirm this on ff2737fee8d022e90298a63baaa4751d599f6564 (with those PR changes)

**Comment by UltraNix** [comment]
Already fixed.
