### ISSUE TITLE
The walls of Duncan's Textiles can disappear if you look at them from the inside #633

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#5820]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

"Originally reported https://github.com/chromiecraft/chromiecraft/issues/633"

At a specific angle and zoom level you can see through the walls of Duncan's Textiles in Stormwind's Mage quarter

![image](https://user-images.githubusercontent.com/54365532/118039884-1df1e300-b371-11eb-8e9e-120a2d5bf101.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Walls should disappear. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Duncan's Textiles in Stormwind
2. Walk up the stairs
3.  Stand here and zoom in about to this level of zoom
![image](https://user-images.githubusercontent.com/54365532/118040140-7d4ff300-b371-11eb-93fc-f0750ac1d583.png)
4. Slowly adjust the camera until the walls and your character disappear and you can see outside. You need to roughly look in the direction of the wooden pillar texture, or if you zoomed one level more then you need to look a bit to the right

##### EXTRA NOTES:

Zoomed out picture to better see the spot where you need to stand: 
![image](https://user-images.githubusercontent.com/54365532/118040481-dae43f80-b371-11eb-8f56-e3714cdd05dc.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server :

![WoWScrnShot_051321_101241](https://user-images.githubusercontent.com/82579073/118091687-c9338400-b3d3-11eb-8dd7-8325eccc1017.jpg)
![WoWScrnShot_051321_100904](https://user-images.githubusercontent.com/82579073/118091703-cd5fa180-b3d3-11eb-9074-c52c7a2ffc3f.jpg)

**Comment by Kitzunu** [comment]
Nothing we can do. This is a Blizzard issue that exists to this Day
