### ISSUE TITLE
Swamp of Sorrows - Multiple Mobs Spawned Underground

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5826]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/635

Some mobs in Swamp of Sorrows are spawned underground.
GUID 35251
![undeground1](https://user-images.githubusercontent.com/80769357/118102160-b8d1d800-b3d8-11eb-8254-dbf1c15ba856.jpg)

GUID 34164 & GUID 37376
![underground2](https://user-images.githubusercontent.com/80769357/118102220-ce470200-b3d8-11eb-8339-7d7e01bde21e.jpg)

Tester: confirmed - teleporting to the mobs  got me stuck underground every time.
![WoWScrnShot_051321_225158](https://user-images.githubusercontent.com/81782124/118131966-50b5dd00-b43e-11eb-8a31-75182561ce47.jpg)
![WoWScrnShot_051321_225220](https://user-images.githubusercontent.com/81782124/118131985-56132780-b43e-11eb-97e5-74f439240d7b.jpg)
![WoWScrnShot_051321_225619](https://user-images.githubusercontent.com/81782124/118132078-72af5f80-b43e-11eb-90f1-47e6592df7d5.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should not be spawned underground.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID and observe spawn point.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacki95** [comment]
Related to https://github.com/azerothcore/azerothcore-wotlk/issues/5765 and https://github.com/azerothcore/azerothcore-wotlk/pull/5778. The DB values seem to be correct.
