### ISSUE TITLE
`server togglequerylog`, skip.

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#5827]
**CURRENT BEHAVIOUR:**

When executing a command in the terminal, the following message appears

![togglequerylog](https://user-images.githubusercontent.com/2810187/118133447-3b599800-b3d7-11eb-915b-460ec85ac895.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

This message should not appear.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

Execute some command by terminal.

1. `server info` or `saveall` ...

**EXTRA NOTES:**

**AC HASH/COMMIT:**

https://github.com/azerothcore/azerothcore-wotlk/commit/5a950f0edf0604fe7260adc53473733d0820ac88

**OPERATING SYSTEM:**

- Windows 10

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by pangolp** [comment]
If it is confirmed, and no one opened a pull request, I will find out.

**Comment by Winfidonarleyan** [comment]
@pangolp can make PR with delete this command?

**Comment by pangolp** [comment]
> @pangolp can make PR with delete this command?

Yes, of course. No problem.
