### ISSUE TITLE
[QUEST] En-Ay-Es-Tee-Why doesn't work as intended.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#583]
**Description**: This quest requires retrieving spire spider eggs in Blackrock Spire by clicking the egg sacks found in the Skitterweb Tunnels. In retail there's a chance that clicking these releases several small spiders that I recall having fast attacks with high damage. This is not happening in AC and the eggs can be farmed easily without interference.

**Expected behavior:** 
There should be a chance with every egg sack click that instead of getting eggs several small spire spiders appear and attack the player.

**Steps to reproduce the problem:**
Get the quest from Flame Crest and go farm some eggs.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Gargarensis** [comment]
I could not find additional information about this spiderling!
Do you remember their name/number and, roughly, the probability?

**Comment by StygianTheBest** [comment]
I could be wrong, it's been A LONG TIME. I'll see if I can dig anything up.

**Comment by BarbzYHOOL** [comment]
any one can confirm nowadays ?

**Comment by Dootz** [comment]
there's missing trap object in SC db. You can find if on TC. Spell used by trap to summon spiders - 16453.

**Comment by wetbrownsauce** [comment]
This issue still exists with other gameobjects that have linked traps as well. 

An example of this can also be seen with the Bone Collector quest in descolace. 

Some kodo bones should spawn an angry kodo, but none do. The linked trap does not exist in the database as far as I see. I added the one from current trinitycore but it still wouldn't work. Perhaps I did something wrong?

**Comment by StygianTheBest** [comment]
Thanks for the update. Please link the Trinity fix @wetbrownsauce.

**Comment by wetbrownsauce** [comment]
I don't have a fix.  

Many trap gameobjects which are referenced by their parent gameobject in the gameobject-template table just don't exist.  

I tried adding the missing gameobjects using trinity's db as reference, but that didn't work. I may have done something wrong as it was late, but I'll look into it more today.

**Comment by BarbzYHOOL** [comment]
2012 is very very old lol

what we have:
```
        case GAMEOBJECT_TYPE_TRAP:                          //6
        {
            GameObjectTemplate const* goInfo = GetGOInfo();
            if (goInfo->trap.spellId)
                CastSpell(user, goInfo->trap.spellId);

            m_cooldownTime = World::GetGameTimeMS()+(goInfo->trap.cooldown ? goInfo->trap.cooldown :  uint32(4))*IN_MILLISECONDS;   // template or 4 seconds

            if (goInfo->trap.type == 1)         // Deactivate after trigger
                SetLootState(GO_JUST_DEACTIVATED);

            return;
        }
```

What the PR was about in 2012
```
        case GAMEOBJECT_TYPE_TRAP:                          //6
        {
            GameObjectTemplate const* goInfo = GetGOInfo();
            if (goInfo->trap.spellId)
                CastSpell(user, goInfo->trap.spellId);
            m_cooldownTime = time(NULL) + (goInfo->trap.cooldown ? goInfo->trap.cooldown :  uint32(4));   // template or 4 seconds
            if (goInfo->trap.type == 1)         // Deactivate after trigger
                SetLootState(GO_JUST_DEACTIVATED);
            return;
        }
```

**Comment by poszer** [comment]
Nah, this can be simply fixed by importing one gameobject, but how i can see in the wotlk bases, it's triggered by looting 175588 (and we have just one object in this instance with that entry.)
Others are 175606, there are more of these, but they don't summon these spiders on loot.
So, i'll post fix soon, for this one. Also, checked on yb some old videos, just some of them summon spiders, not all objects.
