### ISSUE TITLE
cmake install compile "permission denied" problem

### ISSUE THREAD

**Issue by rogerc66** [azerothcore/azerothcore-wotlk#5832]
**EXPECTED BLIZZLIKE BEHAVIOUR:**
![image](https://user-images.githubusercontent.com/4217584/118177982-ff214880-b465-11eb-9e5c-ced6999836de.png)

**STEPS TO REPRODUCE THE PROBLEM:**

1.  Clean up docker 
2. Build project

**AC HASH/COMMIT:**
Lastest head: commit 5a950f0edf0604fe7260adc53473733d0820ac88

**OPERATING SYSTEM:**
Ubuntu

**MODULES:**
Eluna, Transmogrification, solo-lfg, ahbot

**Comment by Branel** [comment]
Please post on the https://stackoverflow.com/questions/ask?tags=azerothcore for support.
