### ISSUE TITLE
NPC gossip menu does not show localization

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5835]
**CURRENT BEHAVIOUR:**
all inn npc(example:id 27950 guid 26623) does not show localization

**EXPECTED BLIZZLIKE BEHAVIOUR:**
show localization  gossip menu

**STEPS TO REPRODUCE THE PROBLEM:**
1. go c 26623
2. talk npc

**EXTRA NOTES:**
npc 27950 gossip menu id = 9628,and ScriptName =npc_innkeeper
![image](https://user-images.githubusercontent.com/18187177/118224634-20aa2080-b4b6-11eb-8988-cc804d44825e.png)
gossip menu  9628
![image](https://user-images.githubusercontent.com/18187177/118224766-5f3fdb00-b4b6-11eb-944e-5b490c6d8b12.png)
gossip_menu_option_locale 9628
![image](https://user-images.githubusercontent.com/18187177/118224815-77175f00-b4b6-11eb-9e46-cb37108e14b7.png)

npc_innkeeper
![image](https://user-images.githubusercontent.com/18187177/118224905-9f06c280-b4b6-11eb-8068-d7466803ad5b.png)

**AC HASH/COMMIT:**
5a950f0edf0604fe7260adc53473733d0820ac88
**OPERATING SYSTEM:**
ubuntu20.04
**MODULES:**
none

**Comment by Kitzunu** [comment]
Duplicate, I cant link the issue atm cuz I am on phone. But there is an open PR to fix this

**Comment by mpfans** [comment]
> Duplicate, I cant link the issue atm cuz I am on phone. But there is an open PR to fix this

I find it
https://github.com/azerothcore/azerothcore-wotlk/pull/5811

**Comment by pangolp** [comment]
> > Duplicate, I cant link the issue atm cuz I am on phone. But there is an open PR to fix this
> 
> I find it
> #5811

Try updating the emulator, and you should see the texts in your client's language.
