### ISSUE TITLE
Server frozen after "Delete GameObject ... Crash possible later."

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5838]
**CURRENT BEHAVIOUR:**

The server has frozen with the following:

```
Delete GameObject (GUID Full: 0xf110007458002a17 Type: Gameobject Entry: 29784  Low: 10775 Entry: 29784 SpellId 818 LinkedGO 31442) that lost references to owner GUID Full: 0x00000000000058fd Type: Player Low: 22781 GO list. Crash possible later.
Delete GameObject (GUID Full: 0xf110007458002986 Type: Gameobject Entry: 29784  Low: 10630 Entry: 29784 SpellId 818 LinkedGO 31442) that lost references to owner GUID Full: 0x0000000000007800 Type: Player Low: 30720 GO list. Crash possible later.
Delete GameObject (GUID Full: 0xf1100074580027e9 Type: Gameobject Entry: 29784  Low: 10217 Entry: 29784 SpellId 818 LinkedGO 31442) that lost references to owner GUID Full: 0x0000000000007800 Type: Player Low: 30720 GO list. Crash possible later.
5239968.904518 [Thread 0x7fff99dfe700 (LWP 29291) exited]Delete GameObject (GUID Full: 0xf11002ace80020ac Type: Gameobject Entry: 175336  Low: 8364 Entry: 175336 SpellId 16072 LinkedGO 0) that lost references to owner GUID Full: 0x000000000000735d Type: Player Low: 29533 GO l                                                   "chromiegame" 08:29 14-May-21ist. Crash possible later.
Delete GameObject (GUID Full: 0xf1100074580020e0 Type: Gameobject Entry: 29784  Low: 8416 Entry: 29784 SpellId 818 LinkedGO 31442) that lost references to owner GUID Full: 0x0000000000006c56 Type: Player Low: 27734 GO list. Crash possible later.
```

restarting the server fixed the issue but this should not happen.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

Unable to reproduce, needs investigation

**AC HASH/COMMIT:**
 

8dd58ebb5bea

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

**Comment by Kitzunu** [comment]
Just frozen or do you get a crashlog?

**Comment by FrancescoBorzi** [comment]
no crashlog, just frozen

**Comment by Kitzunu** [comment]
@FrancescoBorzi Has this occurred anymore?

I have not seen any other reports or mentions about this.

**Comment by FrancescoBorzi** [comment]
not that I'm aware of, cc @Nyeriah

**Comment by Kitzunu** [comment]
In that case I think we can close this until we can get more info or it happens again

**Comment by LannyE** [comment]
FYI: I get this error whenever I put down and use a campfire (GO) to cook food then either log off or restart the server.

**Comment by Kitzunu** [comment]
@FrancescoBorzi @LannyE enable https://github.com/azerothcore/azerothcore-wotlk/blob/87f76587d808245b6ebab91f9c6be35898bab8a5/src/server/worldserver/worldserver.conf.dist#L457 to force crash if frozen. That way we can debug it

**Comment by Nyeriah** [comment]
@Kitzunu we have the freezedetector enabled, but honestly I have not seen such freeze ever. Maybe it got fixed with the trap rewrite.

**Comment by LannyE** [comment]
My server doesn't crash or freeze it just puts out this error after I deploy a basic campfire to cook food.  The error pops up in the console for each campfire I had deployed during my session whenever I log out or restart the server.   It does not repeat after subsequent log outs.  It only errors once per campfire I had deployed.  

This image is when I deployed two campfires and then logged out a little while later.  This was last night.  Using 
AzerothCore rev. cfb171efda7e 2022-02-05 16:32:25 -0500 (master branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon).  
![image](https://user-images.githubusercontent.com/65646022/152797520-0aaa8727-0a69-4032-b84d-9afcdc466252.png)

**Comment by Nyeriah** [comment]
I haven’t checked but this error sounds bogus to me. The player spawns the bonfire and the reference is lost once they relog that is totally expected and completely fine

**Comment by LannyE** [comment]
I agree, so far I haven't seen any negative issues spawn from it but I have just only noticed it lately since I don't normally use campfires.

**Comment by Nyeriah** [comment]
No words about this for a long time, closing as it's been a year without issues
