### ISSUE TITLE
Karazhan （Bosses_Opera）  BUG

### ISSUE THREAD

**Issue by Mycadi** [azerothcore/azerothcore-wotlk#585]
Karazhan （Bosses_Opera） BUG

1、player death Unable to disengage from combat。
2、BOSS death Unable to disengage from combat。

**Comment by ShinDarth** [comment]
invalid report, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by StygianTheBest** [comment]
I ran Kara the other day and it went fine for me. I got the Oz scene.

**Comment by talamortis** [comment]
@Mycadi  which boss was it?
