### ISSUE TITLE
Forsaken Rogue Quest Chain "The Deathstalkers" Displays Inaccurate Quest Objective Text

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5851]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/644

The Forsaken/Undead rogue class quest chain "The Deathstalkers" displays incorrect/misleading location text in the Objective pane during several steps of the chain (I noticed 3). Text in the quest log, as well as map marker locations are correct, only the Objective text is incorrect. Locations for the following Undercity NPCs are inaccurate: (Note GUIDs in screenshots)
1. Andron Gant
![WoWScrnShot_051321_202236](https://user-images.githubusercontent.com/83389835/118215668-9a4ef980-b437-11eb-9c0a-5ccbe9999a48.jpg)
![WoWScrnShot_051321_202255](https://user-images.githubusercontent.com/83389835/118215680-a044da80-b437-11eb-9610-4dc117ff6b0f.jpg)

2. Mennet Carkad
![WoWScrnShot_051321_202517](https://user-images.githubusercontent.com/83389835/118215691-a76be880-b437-11eb-95d5-2a835da8c178.jpg)
![WoWScrnShot_051321_202539](https://user-images.githubusercontent.com/83389835/118215723-b783c800-b437-11eb-93c1-301b27cf4399.jpg)

3. Aleric Hawkins
![WoWScrnShot_051321_202844](https://user-images.githubusercontent.com/83389835/118215744-c4082080-b437-11eb-9e20-a1cde9251068.jpg)
![WoWScrnShot_051321_202900](https://user-images.githubusercontent.com/83389835/118215750-c8ccd480-b437-11eb-8ebd-a0fdba1d6d14.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Objective text should be consistent with the information from other sources (state that the NPCs are found in the Undercity rather than Tirisfal/Silverpine/Alterac).

Tester's notes: ran through chain and confirmed that the objective text is incorrect:
![WoWScrnShot_051521_144231](https://user-images.githubusercontent.com/81782124/118348893-633e2c80-b58c-11eb-8ab5-ac5957b90cf5.jpg)
![WoWScrnShot_051521_144121](https://user-images.githubusercontent.com/81782124/118348894-6507f000-b58c-11eb-924e-e86b93de6ad9.jpg)
![WoWScrnShot_051521_144216](https://user-images.githubusercontent.com/81782124/118348895-65a08680-b58c-11eb-96cf-95c373331bc4.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Reach level 10 on an undead rogue, then accept the first quest in the chain (https://wotlkdb.com/?quest=1885) with .quest add 1885
2. Complete all steps of the quest chain until you are asked to speak with Andron Gant in the Undercity
3. Look at the objective text. It will say he is found at Lordamere Lake in Alterac Mountains, even though he's found in the Apothecarium in Undercity.
4. Each subsequent quest of this chain will have incorrect information for the target NPCs (Mennet Carkad and Aleric Hawkins). Note these as well.

##### EXTRA NOTES:

I think this issue might have something to do with Undercity's unique zoning situation, as the only capital city that has sections that are **vertically adjacent to multiple zones.** If so, there might be other quests with NPC targets in Undercity that will have similar issues. I'm not an expert and that's just my theory though.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by claudiodfc** [comment]
Can't reproduce this issue on the latest version of Azerothcore. Can you update master and try again? I did check another issue that I'm going to fix.

**Comment by Azcobu** [comment]
Just tested again on rev. 5787d00d545a and it's still showing incorrect quest objective text. Despite all the NPCs being in UC, it kept saying objectives were in Lordamere Lake in Alterac or the Ruins of Tirisfal, even though it showed correct positions on the map. I'm using a pure vanilla client for testing, so no quest tracking mods/Carbonite or anything.

![WoWScrnShot_062121_203157](https://user-images.githubusercontent.com/81782124/122752768-7ef5ca80-d2d0-11eb-85a3-2331f187e3e4.jpg)
![WoWScrnShot_062121_203243](https://user-images.githubusercontent.com/81782124/122752775-80bf8e00-d2d0-11eb-8cba-abbf0a264348.jpg)
![WoWScrnShot_062121_203307](https://user-images.githubusercontent.com/81782124/122752785-84ebab80-d2d0-11eb-8f2b-e17edc9de056.jpg)
![WoWScrnShot_062121_203323](https://user-images.githubusercontent.com/81782124/122752799-87e69c00-d2d0-11eb-8b80-3d699e16176f.jpg)
![WoWScrnShot_062121_203336](https://user-images.githubusercontent.com/81782124/122752807-8c12b980-d2d0-11eb-9e35-9b5e8a8f9d6d.jpg)
![WoWScrnShot_062121_203419](https://user-images.githubusercontent.com/81782124/122752815-8f0daa00-d2d0-11eb-81d3-07aaa1219015.jpg)

**Comment by claudiodfc** [comment]
forget what I said, I added the Vanilla quest which was supposed to be deprecated.
