### ISSUE TITLE
Quest buge  [Leave No One Behind]

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5853]
## CURRENT BEHAVIOUR:
 [Leave No One Behind]
When I bring this npc, the quest must be solved here
But from 3 to 2 npc can be solved, one of them has a problem

## EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.wowhead.com/quest=12512/leave-no-one-behind

## SOURCE:

![WoWScrnShot_051421_170202](https://user-images.githubusercontent.com/80007195/118352476-e81e4b80-b576-11eb-803c-dc43eed095fe.jpg)

## STEPS TO REPRODUCE THE PROBLEM:
.go cre 88305

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by Si1ker** [comment]
#3674

**Comment by poryagholami1374** [comment]
> #3674

Is this quest fixed?
