### ISSUE TITLE
[NPC] Buff not applied after killing King Gorduk.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#586]
**Description**: The 'King of the Gordok' buff is not being applied to the player.

**Expected behavior:** 
Mizzle the Crafty (in Dire Maul) will cast this on you and your party when you defeat the last boss King Gordok. It'll make you friendly with any remaining ogre inside the instance.

**Steps to reproduce the problem:**
Kill King Gorduk

**Reference:**
http://www.wowhead.com/spell=22799/king-of-the-gordok#comments

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Gargarensis** [comment]
It did work for me on: b450ba35d86de2e6099146abdbf91d4640a10b95

http://imgur.com/a/Hrg4O

**Comment by ShinDarth** [comment]
please update to latest master and try again

**Comment by StygianTheBest** [comment]
Why close this until it's confirmed? That makes zero sense to me. Also.. my hash is a later build than the testers or am I missing something?

**Comment by ShinDarth** [comment]
because the hash of @Gargarensis is more recent than yours, can you please try it again in latest master? feel free to reopen if the bug is still there

**Comment by StygianTheBest** [comment]
I will, but would this assume a stealth fix was possibly applied that's not being listed in the commit? I didn't see anything about it getting fixed, and that would avoid this back/forth in the future.

**Comment by ShinDarth** [comment]
yes that's possible
