### ISSUE TITLE
[AC progression system] Zero: disable everything from later phases from a clean AC [$100]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5861]
This is part of the AzerothCore progression system, please refer to the EPIC for the main guidelines https://github.com/azerothcore/azerothcore-wotlk/issues/5248

-----------------------------------

The scope of the Zero step is disabling/removing all the contents that are NOT supposed to be available.

There is **NO** need for disabling professions and races(Dranei, Blood Elves). This is mostly about limiting contents such as loots and dungeons.

There is already some minimal work done [here](https://github.com/azerothcore/classic-mode) which can be used as a base.

What needs to be done is tasks such as:

- disabling all TBC/WOTLK dungeons and raids (using `disables`)
- removing all items lootable in the Classic world that come from TBC or WOTLK. For example, in Deadwind Pass there are some NPCs in front of the Kharazan entrance that are dropping TBC items
- removing world bosses that belong to a later season
- disabling all PvP vendors from later seasons
- and so on....

**Comment by JamesGent** [comment]
Darkmoon Faire sells TBC and WOTLK materials at the exotic goods vendors.

**Comment by FrancescoBorzi** [comment]
Also in Tanaris and other places they sell high-level PvP items. Those should be of course removed.
