### ISSUE TITLE
[AC progression system] Classic: Ahn'Qiraj

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5865]
This is part of the AzerothCore progression system, please refer to the EPIC for the main guidelines https://github.com/azerothcore/azerothcore-wotlk/issues/5248

-----------------------------------

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5248#issuecomment-1694558152
