### ISSUE TITLE
Blizzard spell animation continues play for a long time after the channeling is cancelled. (Low repro)

### ISSUE THREAD

**Issue by Maxproz** [azerothcore/azerothcore-wotlk#5870]
1. Cast Blizzard
2. Cancel it during the start of the cast
3. Observe blizzard continues to play afterwards for a long time

**EXTRA NOTES:**
I believe that the spell animation is cancelled on server but not replicated back to the client. 

In the attached screenshot, you can see a blizzard spell raining down on my screen.
That is from when I was channeling it over a minute ago, but you can see me drinking water on screen.

**AC HASH/COMMIT:**
 
chromiecraft@8dd58ebb5bea

**OPERATING SYSTEM:**

English Client - Ryzen - 1060 - Windows 10

**CUSTOMIZATIONS:**

No addons

![image](https://user-images.githubusercontent.com/18764168/118371028-59520480-b55f-11eb-939e-59c6872ec0ae.png)

**Comment by Kitzunu** [comment]
There is already an open issue about it. But I cant check which one now.

**Comment by Kitzunu** [comment]
Found it, even has a bounty on it :) https://github.com/azerothcore/azerothcore-wotlk/issues/2901

**Comment by Maxproz** [comment]
Ahh rain of fire too, allright

**Comment by Kitzunu** [comment]
Been an issue from 2012 :D
