### ISSUE TITLE
Wall of the dead is set to proc on ranged attacks, other shields are not. 

### ISSUE THREAD

**Issue by Maxproz** [azerothcore/azerothcore-wotlk#5871]
**CURRENT BEHAVIOUR:**
Skullflame shield and Green tower auras only proc on melee attacks.
Wall of the dead is set to also proc on ranged attacks.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Not sure, but I feel like they should be consistent behavior.
Feel free to close issue if disagree.

I feel like since the proc chance on these abiltities is so low. 
We should set them to the same settings as wall of the dead.
So they all proc on ranged auto attacks.

**STEPS TO REPRODUCE THE PROBLEM:**
Inconsistent proc types between shields equip aura effects.

1. Open WoW spell editor of AzerothCore current DB
2. Go to aura spell for the green tower Shield   18097 - Observe Procs only set to melee
3. Go to aura spell for Skullflame Shield            18815 - Observe Procs only set to melee
4. Got to aura spell for Wall of the dead Shield 19409 - Observe Procs Include ranged

**AC HASH/COMMIT:**
chromiecraft/azerothcore-wotlk@8dd58eb

**OPERATING SYSTEM:**
Windows 10 

**MODULES:**
No addons
![image](https://user-images.githubusercontent.com/18764168/118372315-e4ce9400-b565-11eb-9418-ad1f45d55fe6.png)
![image](https://user-images.githubusercontent.com/18764168/118372328-f31cb000-b565-11eb-9464-8df0b1b1bff7.png)

**Comment by UltraNix** [comment]
If data comes from DBC, then it is okay like in this case.
