### ISSUE TITLE
[BG] Warsong Gulch's doors dont disappear 

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#5873]
**CURRENT BEHAVIOUR:**

Doors do not disappear after opening
![WoWScrnShot_051521_210904](https://user-images.githubusercontent.com/31663279/118375503-51777c00-b5c2-11eb-8c45-0591749abed7.jpg)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

all Warsong Gulch doors must disappear after opening.
https://youtu.be/QvThZsswY08?t=209
https://youtu.be/QvThZsswY08?t=838

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. go in BG
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:** chromiecraft/azerothcore-wotlk@8dd58eb
 

**OPERATING SYSTEM:**

Ubuntu 20

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
is gob issue same as https://github.com/azerothcore/azerothcore-wotlk/issues/5771

**Comment by Maurowin** [comment]
it takes into account the Warsong Gulch?

**Comment by Branel** [comment]
Yes because 

> Something might have broken the invisibilityType check.

**Comment by Maurowin** [comment]
so, be free to close this issue.
