### ISSUE TITLE
Dodged and parried strikes do not raise weapon skill

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5882]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

While I believe the chance to receive a skill up is accurate, dodge and parry do not give skill points. Additionally attacks made on critters do not give points either.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

[https://classic.wowhead.com/guides/classic-wow-weapon-skills](https://classic.wowhead.com/guides/classic-wow-weapon-skills)
[https://wowwiki-archive.fandom.com/wiki/Weapon_skill](https://wowwiki-archive.fandom.com/wiki/Weapon_skill)
 "Each attack that is not evaded has a chance to increase weapon skill" So any miss, dodge, parry, or hit should give a chance at skill up, initially it being at or near 100% dropping to about 50% when reaching 10% of cap. This should include also attacks on critters (rats, rabbits, snakes, etc...) as this is still an attack on something killable.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .setskill of a weapon to 1 
2. Attack a mob roughly the same level of below with that weapon to level it, each swing (block, miss, dodge, parry) should count as 1 skill point initially and get less frequent the closer to the skill cap of the level you get.
3. Pay closer attention to the dodge and parry swings. Testing I did not see those raise a skill point.

##### EXTRA NOTES:
--

Weapon skills were removed in Cataclysm. Any info found would be from 3.3.5 or earlier

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Maxproz** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5895
