### ISSUE TITLE
Silverpine Forest - Herb nodes spawning inside buildings

### ISSUE THREAD

**Issue by sij1nk** [azerothcore/azerothcore-wotlk#5884]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bruiseweed nodes 2944 and 3069 are located inside buildings. (Bug found on Chromie, screenshots from local server)
![WoWScrnShot_050921_174843](https://user-images.githubusercontent.com/39011611/117579498-5c7a6a00-b0f3-11eb-957b-aa25318fdaf0.jpg)
![WoWScrnShot_050921_174807](https://user-images.githubusercontent.com/39011611/117579500-61d7b480-b0f3-11eb-9e0e-51d386f0abda.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Resource nodes shouldn't spawn inside buildings like this.

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.go o 3069` 
2. `.go o 2944`
3. `.gobject near` if they're not spawned and you want to be sure

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Shineslippers** [comment]
Original report: https://github.com/chromiecraft/chromiecraft/issues/589
