### ISSUE TITLE
Running "./acore.sh docker attach ac-worldserver" returns "the input device is not a TTY." in GitBash

### ISSUE THREAD

**Issue by suprsokr** [azerothcore/azerothcore-wotlk#5886]
**Describe the bug**
```
$ ./acore.sh docker attach ac-worldserver

Deno version check:
Version 1.9.1 is already installed
>>>>> Running: docker-compose ps ac-worldserver
>>>>> Running: docker attach acore_ac-worldserver_1
NOTE: you can detach from a container and leave it running using the CTRL-p CTRL-q key sequence.
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

**To reproduce**
Windows 10, GitBash, azerothcore-wotlk commit f8abece0d56964b0109ccee6dac31a911b39dfff

1. Follow instructions at https://www.azerothcore.org/wiki/Install-with-Docker until Step 4
2. `./acore.sh docker attach ac-worldserver` while using GitBash

**Expected behavior**
User should be attached to the worldserver.

**Fix**
This command works in GitBash: ` winpty docker attach acore_ac-worldserver_1` where acore_ac-worldserver_1 is the name of your worldserver container (use `docker-compose ps ac-worldserver` to find its name).

Not sure how this could be integrated such that the `./acore.sh` command works.

**Comment by Yehonal** [comment]
I moved this issue under the azerothcore-wotlk repo to add it within the docker project

**Comment by suprsokr** [comment]
Great, thanks.

I poked around the internet and found that this issue has been discussed on the Docker for Windows issue tracker for over two years with no official response: https://github.com/docker/for-win/issues/1588. The opinion there is to either use winpty, or some program other than GitBash.

If we are stuck using winpty, then we could either update the wiki to tell people to use winpty more consistently (its mentioned at the bottom of the Install With Docker instructions, but not under https://www.azerothcore.org/wiki/Install-with-Docker#installation Step 4, for example) or have some kind of environment detection in docker-command.ts that will prefix winpty to the attach command.

**Comment by temperrr** [comment]
The wiki  has been updated for this,
