### ISSUE TITLE
Quest Buge [The Drakkensryd]

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5891]
## CURRENT BEHAVIOUR:
[The Drakkensryd]
When I ride a dragon, I attack the npc
They do not eat damage
It only works on one of them. When they go around a few times, the dragons disappear and become bugs

## EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.wowhead.com/quest=12886/the-drakkensryd

## SOURCE:
![WoWScrnShot_051621_170831](https://user-images.githubusercontent.com/80007195/118397700-8a6b2b80-b66a-11eb-8b07-d57d1990404f.jpg)

## STEPS TO REPRODUCE THE PROBLEM:
.go cre 97128
.q add 12886

Hit the item and ride the dragon
And attack
You see, he does not attack

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by poryagholami1374** [comment]
I can not damage it
says that
out of range
![WoWScrnShot_052321_162652](https://user-images.githubusercontent.com/80007195/119259549-0376ff80-bbe4-11eb-8cfa-6c177aea43a6.jpg)

**Comment by poryagholami1374** [comment]
This effort is very important
If they do not complete this
They can no longer try
If you have free time
Take a look at this post

**Comment by Azcobu** [comment]
Confirming this quest is not working at the moment.

Just to recap, you are supposed to use a harpoon to jump from one drake to another, kill the Hyldsmeet Drakerider on the new drake, and repeat 10 times. The problem with this quest as implemented are numerous:

- when you jump to a drake, the rider cannot be attacked. The usual message is that you are out of range or the target is invalid. This happens whether you are using melee or ranged attacks. This makes it impossible to finish the quest chain as far as I can tell:
![WoWScrnShot_060921_215247](https://user-images.githubusercontent.com/81782124/121353473-0fe1b300-c96d-11eb-93c7-6b5f0238ee32.jpg)

- the drakes don't enforce shapeshifting limits the way all other mounts do, so my druid was able to fly one in bear/cat forms:
![WoWScrnShot_060921_214915](https://user-images.githubusercontent.com/81782124/121353885-7ff03900-c96d-11eb-9b34-9b02a74c4784.jpg)

- the riders are sitting backwards on the drakes, which looks ridiculous.
- the camera angle seems messed up - it's below the drake by default, and you can't zoom out much at all, so seeing the other drakes is hard.

I did not encounter the other error @poryagholami1374 mentioned where "the dragons disappear and become bugs", but that was about the only thing that didn't bug.

A guide to the quest on retail is here, where you can see how it's supposed to go: https://www.youtube.com/watch?v=oCcyIi7sqZE

**Comment by Sedatyf** [comment]
Thank you again @Azcobu 🚀

**Comment by Sedatyf** [comment]
Can you specifiy on which revision you tested this issue @Azcobu ? As the initial issue came from a very old revision, it could be interesting to have a recent one

**Comment by Azcobu** [comment]
Sure, this was on AzerothCore rev. 8417dadb6e7f 2021-06-09 08:51:04 +0000

**Comment by Azcobu** [comment]
@UltraNix comments on duplicate https://github.com/azerothcore/azerothcore-wotlk/issues/5929:
63a2735 is the cause.
The problem here is the order of processed packets. It should be like this:
launching spline (entering vehicle) --> triggerring CMSG_MOVE_CHNG_TRANSPORT --> serverside spline finished --> triigering CMSG_SPLINE_DONE. But now its: launching spline --> serverside spline finished --> CMSG_MOVE_CHNG_TRANSPORT --> CMSG_SPLINE_DONE. It's something that packets received from client are delayed.

**Comment by FrancescoBorzi** [comment]
> @UltraNix comments on duplicate #5929:
> [63a2735](https://github.com/azerothcore/azerothcore-wotlk/commit/63a273507c753e6d130e8ae2dd7d9d15bf2dd02b) is the cause.
> The problem here is the order of processed packets. It should be like this:
> launching spline (entering vehicle) --> triggerring CMSG_MOVE_CHNG_TRANSPORT --> serverside spline finished --> triigering CMSG_SPLINE_DONE. But now its: launching spline --> serverside spline finished --> CMSG_MOVE_CHNG_TRANSPORT --> CMSG_SPLINE_DONE. It's something that packets received from client are delayed.

@Winfidonarleyan

**Comment by Footman** [comment]
> @UltraNix comments on duplicate #5929:
> [63a2735](https://github.com/azerothcore/azerothcore-wotlk/commit/63a273507c753e6d130e8ae2dd7d9d15bf2dd02b) is the cause.
> The problem here is the order of processed packets. It should be like this:
> launching spline (entering vehicle) --> triggerring CMSG_MOVE_CHNG_TRANSPORT --> serverside spline finished --> triigering CMSG_SPLINE_DONE. But now its: launching spline --> serverside spline finished --> CMSG_MOVE_CHNG_TRANSPORT --> CMSG_SPLINE_DONE. It's something that packets received from client are delayed.

i don't have this packet handling and still have this bug with "too far away"

**Comment by bgcfb** [comment]
I have same bug with "too far away"**

**Comment by mspzyzh** [comment]
I have same problem

**Comment by zqgmzq** [comment]
same problem https://github.com/azerothcore/azerothcore-wotlk/commit/8871ce24e62c429389a1d92130a5e893de6aa028

**Comment by zqgmzq** [comment]
@AzerothCoreDev pls fix it

**Comment by Heitortadeu** [comment]
I have the same problem.

**Comment by Heitortadeu** [comment]
Fix, plissss!

**Comment by lingxDEV** [comment]
Can confirm it’s bugged on latest.

**Comment by Heitortadeu** [comment]
> Pode confirmar que está bugado no último.

yes, it's buggy!

**Comment by tkn963** [comment]
It's not possible to complete the quest, that doesn't mean the quest is important or a must in any way. Yes, the idea is to fix all these issues but frankly I can't see why this is so very important. A comment saying that this is a must for any character and therefore must be fixed as soon as possible is false advertisement. I don't remember specifically what the enchant gives you, but I highly doubt it's a must for anyone who wants to do raids, let alone dungeons. It probably helps you, but a brain will outweigh an enchant any day in my opinion.

**Comment by Ravenguard13** [comment]
> 

I was very specific when I explained why it's so important. In WotLK, especially on low rate servers, everything that may help you in raid still counts. What's next you say, not using glyphs is alright too? I smell casual here

**Comment by Kitzunu** [comment]
People work on what they want to work on. Thats the thing of open source.

Now stop discussing things that doesnt provide value to the issue itself.

**Comment by Ravenguard13** [comment]
Unfortunatele, #9803   doesn't make difference, the problem remains

**Comment by Voidx** [comment]
No info about this?

**Comment by heyitsbench** [comment]
> No info about this? 

It's been closed for years.
