### ISSUE TITLE
Scarlet Monastery - Tigerstrike Mantle should not drop

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#5892]
**CURRENT BEHAVIOUR:**
Original report: https://www.reddit.com/r/wowservers/comments/ndct5u/how_do_wow_private_servers_work_and_why_you/gya4qvz/
Tigerstrike Mantle sometimes drops in the Scarlet Monastery.

Didn't test in-game but the loot tables confirm this:
```
SELECT ct.name AS creature_name, it.name AS item_name
FROM 
    `item_template` it
    JOIN `reference_loot_template` rlt ON rlt.Item = it.entry
    JOIN `creature_loot_template` clt ON clt.Reference = rlt.Entry
    JOIN `creature_template` ct ON ct.entry = clt.Entry
WHERE 
    ct.name LIKE '%Scarlet%'
    AND it.name = 'Tigerstrike Mantle';

+------------------+--------------------+
| creature_name    | item_name          |
+------------------+--------------------+
| Scarlet Gallant  | Tigerstrike Mantle |
| Scarlet Diviner  | Tigerstrike Mantle |
| Scarlet Adept    | Tigerstrike Mantle |
| Scarlet Chaplain | Tigerstrike Mantle |
| Scarlet Torturer | Tigerstrike Mantle |
| Scarlet Monk     | Tigerstrike Mantle |
+------------------+--------------------+
```

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Tigerstrike Mantle shouldn't drop in the Scarlet Monastery.

**SOURCE:**
https://classic.wowhead.com/item=13108/tigerstrike-mantle

**STEPS TO REPRODUCE THE PROBLEM:**

1. Look at the loot tables

**EXTRA NOTES:**

Would be glad to receive more input about this from seasoned players - wowhead has been wrong in the past. 

Other drops may also be wrong.

**Comment by Helias** [comment]
from classic and tbc wowhead it is not lootable from scarlet monastery, I don't think that in wotlk the blizzard changed this, so it should be fine to remove it
