### ISSUE TITLE
[bash] [db-assembler] capital letters in scheme names cause errors

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#5893]
**CURRENT BEHAVIOUR:**

![image](https://user-images.githubusercontent.com/71938210/118400471-03b25080-b662-11eb-8286-d38161b4ddce.png)
If a scheme name in config.sh starts with a capital letter, the above errors occurs while using
`7) import-updates: Assemble & Import only updates`

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Use a scheme name starting with a capital letter
2. do `7) import-updates: Assemble & Import only updates`

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
6947789622de+ 2021-05-06 13:41:39

**OPERATING SYSTEM:**

Windows 10

**MODULES:**

mod-chromie-xp
mod-eluna-lua-engine
mod-pvpstats-announcer

**CUSTOMIZATIONS:**

**Comment by FrancescoBorzi** [comment]
maybe Lord Bash @locus313 can help :)

**Comment by Kitzunu** [comment]
Deprecated
