### ISSUE TITLE
[RDF] Being last in a party and ghost prevents resurrection from entering portal [$35]

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#5896]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I died inside WC during an RDF group. They probably kicked me as I rage quit and did an alt-f4. When I returned, I walked to the instance portal and expected to get resurrected upon entering. I was however teleported inside as a ghost. I had to walk to my "corpse" inside the instance (which was shown on the mini-map). When I arrived at my corpse, I could not see a body. The resurrect prompt did come up, but clicking on the accept button did nothing. I had to go to the spirit healer to resurrect.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As stated before, I should have resurrected upon entering the WC portal as a ghost.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Die inside an instance.
2. Force close the program.
3. Get vote kicked by group members (I assume, not entirely sure as I was offline when this happened)
4. Move into the instance when returning after being kicked
5. This should reproduce the same bug I had

##### EXTRA NOTES:

No extra notes. I hope it's reproduceable and fixable

CC issue: https://github.com/chromiecraft/chromiecraft/issues/577

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by 55Honey** [comment]
From https://github.com/tabakisp:

> I can confirm this.
> 
> The steps to replicate it are:
> 
> Join an RDF group. RDF is essential.
> 
> Finish the dungeon by killing the last boss. Or not, I don't think it matters but I haven't tested it without finishing the dungeon, should work too I guess.
> 
> Don't leave the instance or the party and let everyone else leave the party. You are now alone in the instance.
> 
> While in the instance, die from an npc and release spirit. Upon releasing you will hear the characteristic sound of when you leave the RDF queue and by that you know that you will experience the bug.
> 
> Run back to the instance you died, you will see that entering the instance won't revive you. You now have to find your body, there's an indicator in your minimap.
> 
> Running back to your body will make the resurrect-dialog appear but clicking accept will not trigger anything, leaving you with the only choice to resurrect to the Spirit Healer.
> 
> I think step 4 should be patched, if you die in an instance and you were in a RDF queue it shouldn't remove you from that RDF when you release spirit until you leave it while alive, or a better approach is upon entering any instance it should revive you instantly no matter the case, except required level or raid conditions.

**Comment by Branel** [comment]
Common trinitycore bug, exists in almost every private server, even across different expansions.

**Comment by r-o-b-o-t-o** [comment]
I tested this and I can confirm that the reproduction steps you described are correct @55Honey.
Tested on my archlinux server on ea764812d.
Note: I had to wait until the character appeared as offline before logging back in, otherwise it would teleport the corpse back to where I was before joining the RDF invite.

**Comment by necropola** [comment]
So better not try (and fail) to solo a rare spawn after everyone left. Learned it the hard way. Very annoying bug, indeed.

**Comment by necropola** [comment]
@r-o-b-o-t-o :tada: Thank you!
