### ISSUE TITLE
Halls of Stone Object doors always open

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#59]
Bug in Halls of Stone. Door Always open.
https://ctrlv.cz/shots/2016/04/13/0R1p.png
id doors 191295

**Comment by DevRival** [comment]
After that they should be opened?

**Comment by ShinDarth** [comment]
Missing core rev, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/69142946-f05c0e80-0ad8-11ea-9d66-8091ba8cb637.png)
Door is still open
The door should only open after killing Lady Deathwhisper
Revision ded3bd8900e1+ 18.11.2019 @ 18:05

**Comment by gengarshadowball** [comment]
This isn't a bug, the Halls of Stone's doors aren't meant to be closed. Checked on many videos on youtube and they never do.

**Comment by FrancescoBorzi** [comment]
thanks @gengarshadowball for your feedback

**Comment by Bogir** [comment]
Here is a confirmation. Door present and works
https://youtu.be/b9Ly9jQzYqg

**Comment by gengarshadowball** [comment]
So the door should only open after Maiden of Grief is killed? what about the doors that dollow that one?

**Comment by Bogir** [comment]
> So the door should only open after Maiden of Grief is killed?
Correct. 
Krystallus and Maiden of Grief bust bee killed befor this door will be opened.

The Next door to Sjonnir The Ironshaper will be opened by Brann Bronzebeard if he will be saved (Tribunal of the Ages passed).
