### ISSUE TITLE
[EVENT] Stratholme rat trap even doesn't start.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#590]
**Description**: The rat trap even in Stratholme doesn't start.

**Expected behavior:** 
Is about the two places in Stratholme where players enter a corridor with two gates/grid closing at each end and numerous plagued rats spawning and attacking the players (see https://youtu.be/opFRb4Y0WzM?t=1m4s). After a timer expires, the gates open again.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Gargarensis** [comment]
Additional useful information can be found here: https://github.com/classicdb/database/issues/631

**Comment by StygianTheBest** [comment]
Tested: Rat traps function as intended.
