### ISSUE TITLE
Flare debuff/effect doesn't work as blizzard intended 

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#5908]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/650

##### CURRENT BEHAVIOUR:

Flare currently will remove stealthers from stealth and prevent re-stealth only after the animation of the flare itself is done, in other words only when the flare travels through the entire vector to the selected area.

Flare [Spell](https://wowgaming.altervista.org/aowow/?spell=1543)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This behavior is incorrect as the flare debuff is applied IMMEDIATELY as it is launched, this appears to be a common issue on WOTLK private servers as I've found 2 more github issues from 2011 and 2014 with associated proof from blizzard retail WOTLK live realms and blizzard official Arena Tournament realm from the same period.

https://github.com/TrinityCore/TrinityCore/issues/1331
https://github.com/TrinityCore/TrinityCore/issues/1331

Videos & comment taken from the last github report:

> How it should work:
> The effect of the spell should start on use, not when it lands. The landing of the flare is only visual. It should reveal stealthed units while flying and when landed and break stealth.
> 
> http://www.warcraftmovies.com/movieview.php?id=163895
> Stop the movie at 1:20, and watch rogues debufs. Flare is used, but not landed and he has the debuf already.
> At 3:22 you can see the same thing, flare has not landed, but the mage has the debuf.
> At 13:27 you can see rogue has been revealed by the flare which is in the air.
> 
> This one is taken from blizz TournamentRealm: http://www.youtube.com/watch?v=a74AeUDLwQI
> Stop the movie at 7:42. You can see that rogue, warlock and shaman gets the debuf before flare lands.

##### STEPS TO REPRODUCE THE PROBLEM:

Simply find an hostile target and shoot flare on it's feet, you will see the debuff will be applied only after the entire animation is done rather than instantly.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8dd58ebb5bea6a8aada54c830d06974d3ecd1353

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 1b6c200):

![WoWScrnShot_051721_163057](https://user-images.githubusercontent.com/82579073/118497554-d8953300-b72d-11eb-9769-78c53cd40f78.jpg)
![WoWScrnShot_051721_163108](https://user-images.githubusercontent.com/82579073/118497580-dd59e700-b72d-11eb-9e09-511afc1b4253.jpg)
![WoWScrnShot_051721_163114](https://user-images.githubusercontent.com/82579073/118497600-e21e9b00-b72d-11eb-811a-b5870d7577a4.jpg)
![WoWScrnShot_051721_163134](https://user-images.githubusercontent.com/82579073/118497619-e6e34f00-b72d-11eb-9da9-695720a1eb57.jpg)
![WoWScrnShot_051721_163149](https://user-images.githubusercontent.com/82579073/118497633-eba80300-b72d-11eb-9d07-1b9c0074c2c4.jpg)
![WoWScrnShot_051721_163155](https://user-images.githubusercontent.com/82579073/118497649-f06cb700-b72d-11eb-8e02-4cab3f307ae0.jpg)

**Comment by FrancescoBorzi** [comment]
@Eldarix thanks for your contributions! don't forget to apply the [ChromieCraft Generic] label ;)

**Comment by Eldarix** [comment]
Thought that when it was a class problem it was not necessary, understood :) !!

**Comment by anguaive** [comment]
Overriding `speed` to 0 on the Flare spell seems to fix this - the aruas activates instantly upon casting the spell. Disconnecting the spell effect from the visuals (the actual "flare" hitting the ground) feels *wrong* to me, but if this is how Blizz intended it to work then who am I to judge.

I did not do thorough testing so I'm not sure if it introduces any unwanted behavior.

**Comment by FrancescoBorzi** [comment]
> Thought that when it was a class problem it was not necessary, understood :) !!

the general rule is: all bugs coming from ChromieCraft should be either in a content projects (e.g. 1-19, 20-29, etc..) or in [ChromieCraft Generic] otherwise.

bugs coming from other users which also affects a specific content can also be part of content projects
