### ISSUE TITLE
Transmogrif problem

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#591]
There was a problem with transmogrification from tissue into armor and others.
If you can only wear cloth, then there is no way to re-chain mail and so on, as well as with weapons.
Included parameters:
Transmogrification.AllowMixedArmorTypes = 1
Transmogrification.AllowMixedWeaponTypes = 1

**Comment by talamortis** [comment]
please post it in the module and not the main soruce
