### ISSUE TITLE
Lesser Bloodstone Deposit slow respawn rate 

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5912]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/634

##### CURRENT BEHAVIOUR:

Type here.
There aren't enough Lesser Bloodstone Deposits in Drywhisker Gorge (Arathi Highlands), and the respawn rate is way too slow. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Type here.
Normally when go to Drywhisker Gorge, there are always 3-4 Lesser Bloodstone Deposits which you can start mining right away, and the respawn rate is pretty fast (I don't know the exact number).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the quest called Favor for Krazek in Stranglethorn Vale. (optinal)
2. Go to Arathi Highlands and locate Drywhisker Gorge (it is a cave in the northeastern part of the map).
3. Look for a Lesser Bloodstone Deposit.
4. Mine it and wait for respawn.

##### EXTRA NOTES:

Type here.
https://classic.wowhead.com/object=2653/lesser-bloodstone-deposit

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
On my local AC server on the contrary, the respawn time was null:

![WoWScrnShot_051721_173707](https://user-images.githubusercontent.com/82579073/118508061-80632e80-b737-11eb-849a-2ec68f907694.jpg)
![WoWScrnShot_051721_173855](https://user-images.githubusercontent.com/82579073/118508076-83f6b580-b737-11eb-94d0-e87905d3c8f5.jpg)
![WoWScrnShot_051721_173913](https://user-images.githubusercontent.com/82579073/118508081-85c07900-b737-11eb-8de1-6a2cd6461394.jpg)
![WoWScrnShot_051721_173933](https://user-images.githubusercontent.com/82579073/118508090-878a3c80-b737-11eb-9e3e-410a4bd1ecc1.jpg)

The dwarf was able to mine the 4 items needed for the quest in the same node.

**Comment by anguaive** [comment]
The nodes respawn immediately because you're in GM mode.

I did some digging and their actual respawn time is 15 minutes:
```
SELECT DISTINCT gt.name, g.spawntimesecs
FROM
    `gameobject_template` gt 
    JOIN `gameobject` g ON g.id = gt.entry
WHERE 
    g.id = "2653";

+---------------------------+---------------+
| name                      | spawntimesecs |
+---------------------------+---------------+
| Lesser Bloodstone Deposit |           900 |
+---------------------------+---------------+
```

However they're also pooled with other minerals... at least the ones I checked (and the pools are further pooled into more pools). Here's an example:
```
SELECT * from `pool_gameobject` WHERE `pool_entry` = 3494;

+-------+------------+--------+---------------------------------------------+
| guid  | pool_entry | chance | description                                 |
+-------+------------+--------+---------------------------------------------+
| 70364 |       3494 |      0 | Spawn Point 295 - Mithril                   |
| 70365 |       3494 |     25 | Spawn Point 295 - Lesser Bloodstone Deposit |
| 70366 |       3494 |     10 | Spawn Point 295 - Silver                    |
| 70367 |       3494 |     10 | Spawn Point 295 - Gold                      |
| 70368 |       3494 |      5 | Spawn Point 295 - Truesilver                |
+-------+------------+--------+---------------------------------------------+
```

```
SELECT * FROM `pool_template` WHERE `entry` = 3494;

+-------+-----------+------------------------------------+
| entry | max_limit | description                        |
+-------+-----------+------------------------------------+
|  3494 |         1 | Spawn Point 295 - Arathi Highlands |
+-------+-----------+------------------------------------+
```

These nodes are all in the same spot and only one is active at a time, so when you harvest a deposit, there's a chance a different type spawns in its place. If you find no Bloodstone Deposits in the cave, you can basically "force" them to spawn by mining other types of minerals in the area.

**Comment by Eldarix** [comment]
I didn't know that for the GM mode, I've seen a lot of aspects that gets affected by, but I didn't know that also to the time of respawns, thanks for the accurate info.

**Comment by Eldarix** [comment]
Checking it again ;)

**Comment by Eldarix** [comment]
![WoWScrnShot_051721_185943](https://user-images.githubusercontent.com/82579073/118524354-bbb92980-b746-11eb-85f7-8587e4e7c170.jpg)
![WoWScrnShot_051721_192025](https://user-images.githubusercontent.com/82579073/118524359-be1b8380-b746-11eb-812b-96188337098b.jpg)
![WoWScrnShot_051721_193229](https://user-images.githubusercontent.com/82579073/118524368-bfe54700-b746-11eb-88b9-15f5f3878b92.jpg)

Now without GM mode I have certainly waited more than half an hour, and the node has not reappeared, at least not in the same place

**Comment by Eldarix** [comment]
1,5 hours later, still no respawn of any node in the whole cave:

![WoWScrnShot_051721_202902](https://user-images.githubusercontent.com/82579073/118531736-d2fc1500-b74e-11eb-8d61-6a7c2cbe7daa.jpg)

**Comment by claudiodfc** [comment]
Gameobject pooling isn't working properly. Common issue here. Waiting for the dynamic spawn to fix the nodes

**Comment by PerryCS** [comment]
I'm on chromei craft LIVE right now... been hanging around for hours and no ore spawning for this quest at all.  Cleared the caves a couple of times.  Left, came back... no ore...
