### ISSUE TITLE
Death Knight Hearthstone error 'unused scourgestone'

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5919]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

##### CURRENT BEHAVIOUR:

I'm testing and experimenting a little bit with the starter zone / quests of the death knight class, and I've found that the hearthstone is not usable, this is the text of the tooltip: 

![WoWScrnShot_051721_205417](https://user-images.githubusercontent.com/82579073/118537441-9e3f8c00-b755-11eb-860f-6acb3d0b1114.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There is always a functional hearthstone.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make a DK.
2. See if the Hearthstone at the initial starting area works.

##### EXTRA NOTES:

--

##### AC HASH/COMMIT:

1b6c2004ce05

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

Local AzerothCore Installation

**Comment by Eldarix** [comment]
I don't know if it's useful, or if it counts as a duplicate, but I just found this: 

https://github.com/azerothcore/azerothcore-wotlk/issues/3121

**Comment by Kitzunu** [comment]
Should probably revert my commit
