### ISSUE TITLE
[RAID] MC Magmadar's core hound groups do not revive if the pack is not killed.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#592]
**Description**: The core hound packs that must be killed before reaching Magmadar do not revive themselves as they should if the pack is not killed in the proper manner.

**Expected behavior:** 
Core Hounds that have been dead for a short while should respawn if the entire pack of hounds has not been killed. The correct mechanic requires all hounds in the pack to be taken to low health and killed off with an AOE attack. If the pack is not killed entirely, dead hounds will respawn and rejoin the battle.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Gargarensis** [comment]
More detailed here: https://github.com/azerothcore/azerothcore-wotlk/issues/620

**Comment by StygianTheBest** [comment]
Just tested this. The core hounds do revive, but there are a few details that aren't ideal. 

1. When the pack is killed, each hound revives and dies again. The hounds that are dead should stay dead and not revive at all.
2. The hounds that die seem to have a slight breathing animation which isn't blizzlike, and it could be tied to the reason they come back to life and dying AFTER the pack is killed off.
3. The mobs need to be flagged as DEAD and then come back to life. It seems like they are being flagged as sleeping or something. 
4. The mobs are listed as "Core Hounds" when they should be "Ancient Core Hounds" if I recall.

**Comment by ShinDarth** [comment]
@StygianTheBest same here

**Comment by StygianTheBest** [comment]
btw - Everyone appreciates the effort put into these fixes, and all others that are submitted by contributors. Just wanted to put that out there since I loaded up that last comment. 👍

**Comment by Gargarensis** [comment]
Thank you for the feedback Stygian :)
I think that 90% of the problem are there because I could not find the correct aura that they originally use.
I'm looking for it, but for the fact that they are still attackable: I saw some videos where the core hound that were "dead" could still be attacked so I did them this way. Can it be that the video I watched was from an unofficial server or it might be correct this behaviour?

**Comment by StygianTheBest** [comment]
I was thinking we could try this.. If a core hound is alive, and it's been alive for X seconds, it attempts to revive/resurrect any dead hounds. This would allow the mob to actually die, and avoid the "sleeping" state, but also bring them back into the fight properly as long as one core hound is still alive. I'll see if I can find a video that gives more detail.

**Comment by Gargarensis** [comment]
Yep, it would be also easier to script, but since I saw that video where the "dead" core hounds could still be hit, i had to find another way to do it.
