### ISSUE TITLE
Server list

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#5921]
**CURRENT BEHAVIOUR:**

It is impossible to load the list of servers until you have logged in with at least one character

**EXPECTED BLIZZLIKE BEHAVIOUR:**

We need to be able to display the list of servers without having to connect to a character first.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. connect into your account
2. try to open server list
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:** b2ab5dba79c1+
 

**OPERATING SYSTEM:** ubuntu 20.04

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by mpfans** [comment]
my server don't have this issue

**Comment by Kitzunu** [comment]
It is useful if you add the rev you are on when confirming or denying issues @mpfans

**Comment by mpfans** [comment]
> It is useful if you add the rev you are on when confirming or denying issues @mpfans

681c3237dfaf46bcad02f00ce717b97bdd899f40

**Comment by Maurowin** [comment]
ChromieCraft have same issue, tested with frFR and enUS client.

**Comment by FrancescoBorzi** [comment]
@Maurowin a fix has been merged today in AC/CC

**Comment by FrancescoBorzi** [comment]
@Maurowin you can always check the AC version of CC here: https://github.com/chromiecraft/azerothcore-wotlk/commits/master

**Comment by Maurowin** [comment]
Yesterday it didn't work, now it works properly :)

**Comment by Maurowin** [comment]
just to keep track (fixed by) : https://github.com/azerothcore/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b
