### ISSUE TITLE
what's wrong with db_assembler.sh

### ISSUE THREAD

**Issue by libxengine** [azerothcore/azerothcore-wotlk#5923]
$ ./db_assembler.sh
NOTICE: file </d/azerothcore-wotlk-master/conf/config.sh> has not been found, you should create and configure it.
Deno version check:
Checking https://github.com/denoland/deno/releases/download/v1.9.1/deno-x86_64-pc-windows-msvc.zip
23.7 MiB / 23.7 MiB (100.0%)
Deno is upgrading to version 1.9.1
Upgraded successfully
1) all: Assemble all
2) bases: Assemble only bases
3) updates: Assemble only updates
4) customs: Assemble only customs
5) import-all: Assemble & Import all
6) import-bases: Assemble & Import only bases
7) import-updates: Assemble & Import only updates
8) import-customs:  Assemble & Import only customs
9) quit: Exit from this menu
[Please enter your choice]: 5
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
Generating /d/azerothcore-wotlk-master/env/dist/sql/auth_base ...
Searching on /d/azerothcore-wotlk-master/data/sql/base/db_auth/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/auth_updates ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/db_auth/ ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/pending_db_auth/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/auth_custom ...
Searching on /d/azerothcore-wotlk-master/data/sql/custom/db_auth/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-ah-bot/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-anticheat/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-buff-command/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-guildhouse/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-learn-spells/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-money-for-kills/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-buffer/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-enchanter/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-premium/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/auth/base/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/characters_base ...
Searching on /d/azerothcore-wotlk-master/data/sql/base/db_characters ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/characters_updates ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/db_characters/ ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/pending_db_characters/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/characters_custom ...
Searching on /d/azerothcore-wotlk-master/data/sql/custom/db_characters/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-ah-bot/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-anticheat/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-buff-command/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-guildhouse/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-learn-spells/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-money-for-kills/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-buffer/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-enchanter/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-talent-template/sql/characters/base ...
Searching on /d/azerothcore-wotlk-master/modules/mod-premium/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/characters/base/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/world_base ...
Searching on /d/azerothcore-wotlk-master/data/sql/base/db_world/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/world_updates ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/db_world/ ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/pending_db_world/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/world_custom ...
Searching on /d/azerothcore-wotlk-master/data/sql/custom/db_world/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-ah-bot/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-anticheat/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-buff-command/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-guildhouse/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-learn-spells/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-money-for-kills/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-buffer/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-enchanter/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-talent-template/sql/world/base ...
Searching on /d/azerothcore-wotlk-master/modules/mod-premium/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/world/base/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
Creating DB acore_auth ...
Creating User acore@localhost identified by acore...
Granting user privileges on: acore_auth ...
Flush privileges
Creating DB acore_characters ...
Creating User acore@localhost identified by acore...
Granting user privileges on: acore_characters ...
Flush privileges
Creating DB acore_world ...
Creating User acore@localhost identified by acore...
Granting user privileges on: acore_world ...
Flush privileges
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
acore_auth seems empty
importing AUTH - base ...
acore_characters seems empty
importing CHARACTERS - base ...
acore_world seems empty
importing WORLD - base ...
importing AUTH - updates ...
importing CHARACTERS - updates ...
importing WORLD - updates ...
importing AUTH - custom ...
importing CHARACTERS - custom ...
importing WORLD - custom ...
=====           DONE            =====
1) --skip-column-names
2) bases: Assemble only bases
3) updates: Assemble only updates
4) customs: Assemble only customs
5) import-all: Assemble & Import all
6) import-bases: Assemble & Import only bases
7) import-updates: Assemble & Import only updates
8) import-customs:  Assemble & Import only customs
9) quit: Exit from this menu
[Please enter your choice]: 5
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
Generating /d/azerothcore-wotlk-master/env/dist/sql/auth_base ...
Searching on /d/azerothcore-wotlk-master/data/sql/base/db_auth/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/auth_updates ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/db_auth/ ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/pending_db_auth/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/auth_custom ...
Searching on /d/azerothcore-wotlk-master/data/sql/custom/db_auth/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-ah-bot/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-anticheat/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-buff-command/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-guildhouse/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-learn-spells/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-money-for-kills/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-buffer/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-enchanter/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-premium/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/auth/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/auth/base/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/characters_base ...
Searching on /d/azerothcore-wotlk-master/data/sql/base/db_characters ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/characters_updates ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/db_characters/ ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/pending_db_characters/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/characters_custom ...
Searching on /d/azerothcore-wotlk-master/data/sql/custom/db_characters/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-ah-bot/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-anticheat/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-buff-command/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-guildhouse/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-learn-spells/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-money-for-kills/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-buffer/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-enchanter/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-talent-template/sql/characters/base ...
Searching on /d/azerothcore-wotlk-master/modules/mod-premium/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/characters/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/characters/base/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/world_base ...
Searching on /d/azerothcore-wotlk-master/data/sql/base/db_world/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/world_updates ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/db_world/ ...
Searching on /d/azerothcore-wotlk-master/data/sql/updates/pending_db_world/ ...
Generating /d/azerothcore-wotlk-master/env/dist/sql/world_custom ...
Searching on /d/azerothcore-wotlk-master/data/sql/custom/db_world/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-ah-bot/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-anticheat/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-buff-command/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-guildhouse/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-learn-spells/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-money-for-kills/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-buffer/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-enchanter/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-talent-template/sql/world/base ...
Searching on /d/azerothcore-wotlk-master/modules/mod-premium/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/world/base/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/world/base/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
acore_auth database exists
acore_characters database exists
acore_world database exists
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
acore_auth is not empty, base importing skipped
acore_characters is not empty, base importing skipped
acore_world is not empty, base importing skipped
importing AUTH - updates ...
importing CHARACTERS - updates ...
importing WORLD - updates ...
importing AUTH - custom ...
importing CHARACTERS - custom ...
importing WORLD - custom ...
ERROR 1062 (23000) at line 131: Duplicate entry '55009' for key 'creature_template.PRIMARY'

The code was just downloaded.
run db_assembler.sh is error....

**Comment by Eldarix** [comment]
I'm not sure, but I would say it's not the right place to put all this :)
