### ISSUE TITLE
quest:The Thane of Voldrune(id 12255 and id 12259) Script bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5926]
**CURRENT BEHAVIOUR:**
When the alliance get quest 12255(horde get quest 12259),Then get to the quest location.Talk the `Flamebringer`(id 27292),If you're on a mount, you'll see another `Flamebringer` out,If you talk to it many times, it will refresh infinitely
![image](https://user-images.githubusercontent.com/18187177/118579140-12af1500-b7c0-11eb-972c-02cfed162e99.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
When the alliance get quest 12255(horde get quest 12259),Then get to the quest location.Talk the `Flamebringer`(id 27292),If you're on a mount, will prompt "you are on Mount, please dismount mount",there won't be any other `Flamebringer` spawn

**STEPS TO REPRODUCE THE PROBLEM:**

1. get quest 12255(horde get quest 12259)
2. .go c 110538
3. cast a Mount
4. talk with Flamebringer
5. talk with Flamebringer
6. talk with Flamebringer
7. talk with Flamebringer
8. talk with Flamebringer
9. talk with Flamebringer
10. ....

**AC HASH/COMMIT:**
681c3237dfaf46bcad02f00ce717b97bdd899f40
**OPERATING SYSTEM:**
ubuntu 20.04
**MODULES:**
none

**Comment by Eldarix** [comment]
Could you please pay a little attention to the details as well as not delete the necessary categories to fill in?

Thank you.

**Comment by mpfans** [comment]
> Could you please pay a little attention to the details (you have paste 6 times 'talk with Flamebringer') as well as not delete the necessary categories to fill in?
> 
> Thank you.

yes... repetition dialogue

**Comment by Eldarix** [comment]
Now that I have read it again I seem a bit lacking in sympathy, English is not my original language and sometimes I tend to think of literal translations that in Castilian would not sound so bad, sorry :P

**Comment by Eldarix** [comment]
I was trying to mean that without the categories filled out, It is difficult to know in what ranges of levels it is for the labels,  and It would be better summarized for example 'talk with Flamebringer x6' than write it six times :D

But hey, I'm new here, and the last thing I want is to look like I want to mark what is correct and what is not, take care and thanks !!
