### ISSUE TITLE
Final event in Wailing Caverns not splitted in waves

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#5927]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/664

##### CURRENT BEHAVIOUR:

During the final event (where you try to save Naralex) 3 waves of mobs should appears. The second one should come in once you defeated the first one and so on. At the moment they are "timed": even if you didn't finish clearing the previous wave after a certain amount of time the next one appears (the same goes for the final boss, [Mutanus](https://wowgaming.altervista.org/aowow/?npc=3654))

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once you cleared a wave of mobs the next one should appear

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Defeat the 4 druid bosses of Wailing Caverns
2. Talk with the [Disciple of Naralex](https://wowgaming.altervista.org/aowow/?npc=3678) at the entrance of the instance
3.  Escort him to the Naralex area
4.  As soon as the first wave appears do nothing, after a while the second wave will appear 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/0d699222de92185681f9a78822a0e5d9898294f4

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: b2ab5db):

![WoWScrnShot_051821_054319](https://user-images.githubusercontent.com/82579073/118583178-517fa380-b79d-11eb-9e30-0562faa0fd01.jpg)
![WoWScrnShot_051821_054721](https://user-images.githubusercontent.com/82579073/118583196-5a707500-b79d-11eb-9cc7-ed999eaecea8.jpg)
![WoWScrnShot_051821_054903](https://user-images.githubusercontent.com/82579073/118583200-5c3a3880-b79d-11eb-8c6e-01d236532f1f.jpg)
![WoWScrnShot_051821_054922](https://user-images.githubusercontent.com/82579073/118583203-5e9c9280-b79d-11eb-8897-4ea5eb91cdac.jpg)
![WoWScrnShot_051821_054929](https://user-images.githubusercontent.com/82579073/118583210-60feec80-b79d-11eb-99ef-8d620a0708a4.jpg)

**Comment by Hacki95** [comment]
I investigated this one before, its not that the fight doesn't have any phases, the timers are just WAY too low. There are many videos which show this: https://youtu.be/BngS6ojTFf0?t=520

A fix should be as easy as: 1) Watch a few videos. 2) Try to align the timers.

The script is fully done in SAI.

**Comment by gabryatfendor** [comment]
@Eldarix  I see that this is labeled Priority - Low. I would tend to disagree, since at the moment it's REALLY hard to defeat the last boos of Wailing Caverns with this bug up :-)

**Comment by FrancescoBorzi** [comment]
small correction: Waling Cavers is 1-19, not 20-29. As it's correctly available at 19 with RDF.

**Comment by gabryatfendor** [comment]
@Hacki95 I tested the event on Classic Wow. There seems to be no timer, the next wave doesn't spawn until you killed the last mob of the previous one (I waited ~5 minutes per wave). Moreover there's a bit of pause betweene the waves, to allow players to eat/drink (seems to me ~15 seconds the first break and ~25 seconds for the second one) . Linking video for reference: https://www.youtube.com/watch?v=zScO80lIfBM

**Comment by Hacki95** [comment]
> 
> 
> @Hacki95 I tested the event on Classic Wow. There seems to be no timer, the next wave doesn't spawn until you killed the last mob of the previous one (I waited ~5 minutes per wave). Moreover there's a bit of pause betweene the waves, to allow players to eat/drink (seems to me ~15 seconds the first break and ~25 seconds for the second one) . Linking video for reference: https://www.youtube.com/watch?v=zScO80lIfBM

Ohh thats interesting... I don't think this is possible to do with SAI...

**Comment by necropola** [comment]
@Hacki95 @Stifler82 What's the status of this bug?
Was this fixed by #6059, too, or not?

**Comment by Hacki95** [comment]
As I see it its not possible to do this encounter fully Blizzlike in SAI. We either need to add new functions to SAI or we need to redo this boss in C++. I see no other way to fix it currently.

**Comment by necropola** [comment]
@Hacki95 Woudl that help? Looks like TC-3.3.5 has it scripted in C++:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Kalimdor/WailingCaverns/wailing_caverns.cpp

**Comment by Hacki95** [comment]
Sure

**Comment by necropola** [comment]
Though it looks like in the TC script the waves are on fixed timers, too. At least I can't find anything that checks whether the summoned creatures have been killed or not. Just an `eventTimer` which is set for each state of `eventProgress`  and decreased on every call of `UpdateAI()` which then triggers the next stage as soon as it reaches zero (`<= diff`).

**Comment by claudiodfc** [comment]
I'm working on a core change that will allow waves to spawn after each wave is defeated. This change is needed for Zul'farrak's pyramid event aswell.

**Comment by necropola** [comment]
What is the stategy or preferred method to implement stuff like this?
- (A) Use `smart_scripts` and `summon_groups`, etc. 
- (B) Write the script in C++ entirely

Is there a tool to make the DB heavy variant (A) easier to read and maintain?
I personally find it a lot easier to read an event script entrely written in C++ even though I hate C++ with apassion.

**Comment by claudiodfc** [comment]
Nothing should be Scripted in C++ for a simple reason, maintainability/stability. People usually script stuff in C++ due to lack of knowledge how to implement a certain mechanic for the SmartAI. If there's a script that needs a specific behavior such as, spawning a wave after the previous wave was defeated, chances are this event should be happening somewhere else and is hardcoded in the core or badly/not scripted.

The solution should be to implement this on SmartAI to allow devs for better and more scripting tools for certain events. Blizzard uses a tool for writing scripted events that is upgraded as they need more and different behaviors and this should be the approach we use for new scripts aswell.

We shouldn't be living under the shadow of Trinitycore for these type of changes as Azerothcore is an independent project.

**Comment by necropola** [comment]
So, which tools are you using to generate the SmartAI Script (which is basically a bunch of rows in a database table)? Keira3, an standard SQL Frontend or is there something else specifically made for SmartAI?

**Comment by claudiodfc** [comment]
Keira3 should be the only tool to develop for AzerothCore since it's tailored in according to It's tables. Any changes need to be made anyone can simply open a PR with an improvement.

**Comment by necropola** [comment]
I fully agree that event scripts shouldn't be coded in C++ and compiled into the core. There should be  layer of abstraction between the functions provided by the core and the event you want to implement. This could be an actual "scripting language" specifically made to script events, but this does not exist.
Instead some tables of an SQL database are  "abused" to store "code" written in a "language" for which neither a grammar nor a compiler (compile time checks) nor an IDE exists. If this is the solution then I want my problem back.

**Comment by T1ti** [comment]
> Keira3 should be the only tool to develop for AzerothCore since it's tailored in according to It's tables. Any changes need to be made anyone can simply open a PR with an improvement.
> 
> However, for this 'wave after wave' behavior still needs to be developed on the core, just not hardcoded of course.

waiting for a previous action to be completed or requiring a wave tobe dead to trigger enxt actino seems like some basic/core feature of a script/event editor liek smartai

**Comment by T1ti** [comment]
btw we should probably check how blizzard actually scripts this, I bet they use spells to summon the adds and stuff

**Comment by necropola** [comment]
My bet woudl be that they have some sort of event scripting language specifically designe to do these kind of things and an IDE to easily browse and pick pick spells, creatures, game_objects,... needed in the script.

**Comment by T1ti** [comment]
wow scripted spells and events are done in LUA
![image](https://user-images.githubusercontent.com/40864460/123849582-3fa32b80-d919-11eb-8d8b-b96b3e32f080.png)

**Comment by necropola** [comment]
While we are at it. Have there ever been thoughts about ditching the SQL backend for the World DB entirely and use something like JSON, YAML, TOML, ...

- World DB contents are read-only (static) at run time. The server never needs to write it.
- Quite a few tables are more or less abused to store non-relational data
- Structured data is much more easily represented in one of the above formats
- Changes to a World DB in one of the above formats would show up as proper diffs in git and woudl be revertable (without re-creating from scratch)
