### ISSUE TITLE
Hearthstone channeling uninterrupted by monsters

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5928]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I was just looking at some details in wailing caverns for another bug and when I was about to leave, I used the hearthstone 2 seconds before they attacked me, the channeling ended and I returned to the city without problems, not sure if to reproduce the error it has to be just before they attack you with a precise timing.

![WoWScrnShot_051821_060418](https://user-images.githubusercontent.com/82579073/118584759-4712d900-b7a0-11eb-97f0-a308ff8dc6b0.jpg)
![WoWScrnShot_051821_061625](https://user-images.githubusercontent.com/82579073/118584917-98bb6380-b7a0-11eb-8fa8-2dae8120fb15.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Channeling must be interrupted.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have a Hearthstone.
2. Use it just before being attacked.
3. Observe if the channeling completes.

##### EXTRA NOTES:

--

##### AC HASH/COMMIT:

b2ab5db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

Local AC setup

**Comment by UltraNix** [comment]
I believe you just completed casting hearthstone before it melee attacked you.

**Comment by Helias** [comment]
cannot reproduce
