### ISSUE TITLE
Error on the consol server

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#5930]
**CURRENT BEHAVIOUR:**

AC>> Config: Missing name PacketLogFile in config, add "PacketLogFile = "

**EXPECTED BLIZZLIKE BEHAVIOUR:**

It seems that "PacketLogFile = " is missing in the conf file

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Run the server
2. create/connect char
3. Wait few minutes
4. see on the consol

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
b2ab5dba79c1

**OPERATING SYSTEM:**

Ubuntu 20.04

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
@Winfidonarleyan

**Comment by mpfans** [comment]
Confirmed
