### ISSUE TITLE
Error DB

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#5932]
**CURRENT BEHAVIOUR:**

SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 11680 SourceType 0 EventType 4 TargetType 7 using non-existent Text id 0 for talker 3819, ignored.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

no error
**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. idk, maybe just wait few minutes
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
b2ab5dba79c1
**OPERATING SYSTEM:**

ubuntu 20.04
**MODULES:**

**CUSTOMIZATIONS:**

**Comment by avarishd** [comment]
@Kitzunu 
Cannot reproduce, GUID 11680 (Entry 446 - Redridge Basher) has correct creature_text / SAI and current target type is 1, not 7.
I'm a bit confused about `using non-existent Text id 0 for talker 3819,` creature 3819 doesn't talk in SAI.
