### ISSUE TITLE
Undercity - Jumping on descending elevator damages player

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#5936]
Original report: https://github.com/chromiecraft/chromiecraft/issues/668

#### WHAT CLIENT DO YOU PLAY ON?

- [X] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Player character dies when jumping on any elevator in the Undercity. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Player character shouldn't die simply by jumping on a elevator.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Jump on a elevator in the Undercity.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Reproduced on d0a259d, enUS client:

https://user-images.githubusercontent.com/39011611/118694066-f5079d00-b80b-11eb-84bd-861328846a93.mp4

**Comment by Stump876** [comment]
Please add elevators in Gnomeregan, The Great Lift in the south barrens, and Freewind Post in Thousand Needles and Shattrath City. I'd wager there are more, but I can't remember everywhere that has elevators. These were the only ones I could think of off the top of my head. So far the ones in Thunderbluff are the only ones I've found that do not damage when jumping.
