### ISSUE TITLE
Error starting Authserver.exe

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#5937]
When I started Auth Server.exe right after the last update I made to Azerothcore, the following error started to appear;

![image](https://user-images.githubusercontent.com/67213916/118741733-58ea8f80-b825-11eb-959b-64a72b665367.png)

STEPS TO REPRODUCING THE PROBLEM:

1. Update the repository
2. Compile the solution
3. Open Authserver.exe, the error appears and closes authserver.exe

rev. 633dbb9d9450

**Comment by Kitzunu** [comment]
Update your database

**Comment by WillzDevs** [comment]
> Update your database

Is giving error to generate the DB_Assembler
![image](https://user-images.githubusercontent.com/67213916/118747078-bd125100-b82f-11eb-9002-938375939aea.png)
