### ISSUE TITLE
Console display error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#5938]
**CURRENT BEHAVIOUR:**
![image](https://user-images.githubusercontent.com/18187177/118749075-650b3700-b88f-11eb-8aa1-e63d82e363aa.png)

**STEPS TO REPRODUCE THE PROBLEM:**
1. I don't know how to reproduce this error. This data is not written into the database 

**AC HASH/COMMIT:**
681c3237dfaf46bcad02f00ce717b97bdd899f40

**OPERATING SYSTEM:**
ubuntu 20.04

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/118751565-1ca24800-b894-11eb-9355-41b88dff07e3.png)
This error is also displayed

**Comment by Kitzunu** [comment]
Closing as there have been no mentions of this error in over 2 years.

If it comes up again just open a new issue
