### ISSUE TITLE
when importting custom mysql file.there is a mistake, there is no prompt for which library

### ISSUE THREAD

**Issue by libxengine** [azerothcore/azerothcore-wotlk#5939]
when importting custom mysql file.there is has a mistake, but that no prompt for which library
like this:
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-free-professions/sql/world/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-gambler/sql/world/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-services/sql/world/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-npc-talent-template/sql/world/base ...
Searching on /d/azerothcore-wotlk-master/modules/mod-reward-shop/sql/world/ ...
Searching on /d/azerothcore-wotlk-master/modules/mod-world-chat/sql/world/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
Creating DB acore_auth ...
Creating User acore@localhost identified by acore...
Granting user privileges on: acore_auth ...
Flush privileges
Creating DB acore_characters ...
Creating User acore@localhost identified by acore...
Granting user privileges on: acore_characters ...
Flush privileges
Creating DB acore_world ...
Creating User acore@localhost identified by acore...
Granting user privileges on: acore_world ...
Flush privileges
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
acore_auth seems empty
importing AUTH - base ...
acore_characters seems empty
importing CHARACTERS - base ...
acore_world seems empty
importing WORLD - base ...
importing AUTH - updates ...
importing CHARACTERS - updates ...
importing WORLD - updates ...
importing AUTH - custom ...
importing CHARACTERS - custom ...
importing WORLD - custom ...
ERROR 1136 (21S01) at line 576: Column count doesn't match value count at row 1

**Comment by Kitzunu** [comment]
I will close this.

Open a new **bug** report. Not a feature request and fill in the template you are given then.

Possibly even provide what line 576 says.
