### ISSUE TITLE
Sunscale Lashtail group not wandering when idle

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#5940]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde 

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original CC report [https://github.com/chromiecraft/chromiecraft/issues/673](https://github.com/chromiecraft/chromiecraft/issues/673)
3 (marked) Sunscale Lashtail mobs just southeast of Crossroads are fixed in place and not exhibiting normal wandering behavior for their mob type. There is a 4th (unmarked) member of the group that is wandering as normal.
![WoWScrnShot_051821_194935](https://user-images.githubusercontent.com/83389835/118743084-48331d00-b817-11eb-832a-637a82f1e5b0.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mobs that are fixed in place should wander around while not in combat

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go creature 40493, 40495, and 40496
2. Observe 

##### EXTRA NOTES:

When aggro'd and then running out of combat the skull will start to wander as intended. The other two go right back to spawn points.
![image](https://user-images.githubusercontent.com/68164076/118750855-220c7d80-b815-11eb-81a9-a1e727f247b3.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Sunscale Lashtail specimens 40489 - 40496 are all like this, and their respawn time is significantly lower too. I assume this is incorrect. 19809 - 19817 behave normally as you'd expect.

```
SELECT `guid`, `modelid`, `spawntimesecs`, `wander_distance`, `curhealth`, `movementtype` FROM `creature` WHERE `id` = 3254;

+-------+---------+---------------+-----------------+-----------+--------------+
| guid  | modelid | spawntimesecs | wander_distance | curhealth | movementtype |
+-------+---------+---------------+-----------------+-----------+--------------+
| 19809 |    1744 |           275 |               5 |       178 |            1 |
| 19810 |    1744 |           275 |               5 |       178 |            1 |
| 19811 |    1744 |           275 |               5 |       178 |            1 |
| 19812 |    1744 |           275 |               5 |       178 |            1 |
| 19813 |    1744 |           275 |               5 |       178 |            1 |
| 19814 |    1744 |           275 |               5 |       178 |            1 |
| 19815 |    1744 |           275 |               5 |       178 |            1 |
| 19816 |    1744 |           275 |               5 |       178 |            1 |
| 19817 |    1744 |           275 |               5 |       178 |            1 |
| 40489 |       0 |           120 |               0 |         1 |            0 |
| 40490 |       0 |           120 |               0 |         1 |            0 |
| 40491 |       0 |           120 |               0 |         1 |            0 |
| 40492 |       0 |           120 |               0 |         1 |            0 |
| 40493 |       0 |           120 |               0 |         1 |            0 |
| 40494 |       0 |           120 |               0 |         1 |            0 |
| 40495 |       0 |           120 |               0 |         1 |            0 |
| 40496 |       0 |           120 |               0 |         1 |            0 |
+-------+---------+---------------+-----------------+-----------+--------------+
```
