### ISSUE TITLE
Quest item problem

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5946]
## CURRENT BEHAVIOUR:
More quests
They have a problem
The item does not quest
Even if it is his chance
Be at 100

## EXPECTED BLIZZLIKE BEHAVIOUR:
Must be found in npc quest item

## SOURCE:
![WoWScrnShot_051921_163657](https://user-images.githubusercontent.com/80007195/118810777-838a2600-b8c1-11eb-9341-620c1ff1bf3f.jpg)
![WoWScrnShot_051521_130815](https://user-images.githubusercontent.com/80007195/118810808-8b49ca80-b8c1-11eb-8d70-7c6d70a5cc5c.jpg)

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by Sedatyf** [comment]
Which quest are you talking about?

**Comment by poryagholami1374** [comment]
> Which quest are you talking about?

Most quests
They have a problem with the quest item
Nothing can be found inside npc

**Comment by Sedatyf** [comment]
You're saying that every quest from a specific area have a problem with their quest item?

**Comment by poryagholami1374** [comment]
> You're saying that every quest from a specific area have a problem with their quest item?

Many attempts
By killing npc
They drop the search items
But now these efforts
It does nothing to kill npc
And the effort is unresolved
This is not just an attempt
I even set the item to 100 but nothing opens

**Comment by tkn963** [comment]
I just tested the quests shown in the screenshots and they do function as intended. I'm curious to know if the person reporting this was using the command !die.

**Comment by Sedatyf** [comment]
> I just tested the quests shown in the screenshots and they do function as intended. I'm curious to know if the person reporting this was using the command !die.

Did you finished those quests @tkn963?
 
You know @poryagholami1374, @tkn963 is right. You have to kill them the normal way because they won't be any loot with ``die`` command

**Comment by poryagholami1374** [comment]
> Did you finished those quests @tkn963?
> 
> You know @poryagholami1374, @tkn963 is right. You have to kill them the normal way because they won't be any loot with `die` command

I also tested with a normal account
It has a problem

**Comment by Sedatyf** [comment]
Alright, no problem, I was just wondering

**Comment by Sedatyf** [comment]
Can you give me quests name @tkn963? I'll check too. Because he's saying there is a problem, and you're saying no, so we need a third opinion to settle this

**Comment by poryagholami1374** [comment]
> Can you give me quests name @tkn963? I'll check too. Because he's saying there is a problem, and you're saying no, so we need a third opinion to settle this

 [Get the Key]

**Comment by tkn963** [comment]
@Sedatyf Did you manage to test the quest?

**Comment by Sedatyf** [comment]
yes indeed. But I couldn't loot quest item either. On what revision are you on? Did you make specific action before looting it?

**Comment by poryagholami1374** [comment]
> @Sedatyf Did you manage to test the quest?

You try to test with an ordinary hero
 Test with gm for damage
Resolved
img 1

**Comment by poryagholami1374** [comment]
> yes indeed. But I couldn't loot quest item either. On what revision are you on? Did you make specific action before looting it?

He must have said the first quest because testing with a gm account
There was no problem, but test the first quest with a normal hero
Nothing is solved

**Comment by tkn963** [comment]
I'm going to log onto a non-GM account and test this a couple of times. I'll be using !quest add 12949 and killing Instructor Hroegar. I'm going to be using 46e853e3c3626bc9142c908a56a121916e766c5d to test hit too. Will return with my findings.

**Comment by Sedatyf** [comment]
> I'm going to log onto a non-GM account and test this a couple of times. I'll be using !quest add 12949 and killing Instructor Hroegar. I'm going to be using [46e853e](https://github.com/azerothcore/azerothcore-wotlk/commit/46e853e3c3626bc9142c908a56a121916e766c5d) to test hit too. Will return with my findings.

Alright, keep me updated. I tested it with a GM account but GM mode turned off. With revision d3fcebaac5c84d87bcc5b6c0ac5de888b0edb9de which is one commit behind yours, and it confirmed the bug. 
And I did what you said : 
- !quest add 12949
- Killing Instructor Hroegar
- Nothing dropped

**Comment by tkn963** [comment]
Okay, I have come to a conclusion. The issue exists on the Alliance side. I tried a total of 6 times, 3 as Alliance and 3 as Horde. The key drops every time as Horde, but never as Alliance.

**Comment by Sedatyf** [comment]
Oh that's the cause. You're the man @tkn963 
Can you make a detailed issue with proper information? And link this one? (I can make it later but I can't do it right now)

**Comment by tkn963** [comment]
@Sedatyf I'm honestly not quite sure what you mean by making a detailed issue.

I think it would be best to run through some quests to see that they're not faulty as well, since the author said they had issues with several quests. Maybe the person could give a list of the quests that they found faulty and I'll go through them.

**Comment by Sedatyf** [comment]
I think it could be a good thing to make an issue with all information at once, a new one, with all your findings, instead of this one with a lot of comments and a description which doesn't mean anything.

If we find other bugged quests like this, we'll link them together, but one issue per quest is better imo

@poryagholami1374 if you have other bugged quest like this, please tell us

**Comment by poryagholami1374** [comment]
> I think it could be a good thing to make an issue with all information at once, a new one, with all your findings, instead of this one with a lot of comments and a description which doesn't mean anything.
> 
> If we find other bugged quests like this, we'll link them together, but one issue per quest is better imo
> 
> @poryagholami1374 if you have other bugged quest like this, please tell us

Send here or open a new post?

**Comment by tkn963** [comment]
@Sedatyf I created the new issue, hope it's up-to-code.
@poryagholami1374 List them here and I'll go through them.

**Comment by poryagholami1374** [comment]
> @Sedatyf I created the new issue, hope it's up-to-code.
> @poryagholami1374 List them here and I'll go through them.

It is not just the Alliance that has two factions

**Comment by Sedatyf** [comment]
> It is not just the Alliance that has two factions

I tend to believe @tkn963 has he tried several times and did a complete investigation on it. Furthermore, on your screenshots, you have an Alliance character.

**Comment by tkn963** [comment]
I hate to say it but I'm not quite sure what @poryagholami1374 is saying, two factions? My tests were pretty basic, no leveling up to 80 of course, starting values of reputation, different races for each faction and the results were all identical. If you have a suggestion on other tests @poryagholami1374 please do let me know I'll be happy to test them

**Comment by poryagholami1374** [comment]
> I hate to say it but I'm not quite sure what @poryagholami1374 is saying, two factions? My tests were pretty basic, no leveling up to 80 of course, starting values of reputation, different races for each faction and the results were all identical. If you have a suggestion on other tests @poryagholami1374 please do let me know I'll be happy to test them

My server is all hordes, all of them had this problem

**Comment by poryagholami1374** [comment]
Try to test with Hero GM, but command Damage and do not use this kind of thing. Use Hero Spell for damage.

**Comment by poryagholami1374** [comment]
> I hate to say it but I'm not quite sure what @poryagholami1374 is saying, two factions? My tests were pretty basic, no leveling up to 80 of course, starting values of reputation, different races for each faction and the results were all identical. If you have a suggestion on other tests @poryagholami1374 please do let me know I'll be happy to test them

https://github.com/azerothcore/azerothcore-wotlk/issues/5856

**Comment by Sedatyf** [comment]
> Okay, I have come to a conclusion. The issue exists on the Alliance side. I tried a total of 6 times, 3 as Alliance and 3 as Horde. The key drops every time as Horde, but never as Alliance.

It's weird @tkn963 I couldn't loot the key from Instructor Hroegar as a Horde. Tested 3 times as well and none looted keys

**Comment by tkn963** [comment]
@Sedatyf That's really strange. I can't seem to trigger the issue as Horde. This is a strange issue then.

**Comment by Sedatyf** [comment]
Oh you can't now finished quest as a Horde? It is strange indeed. Can you modify your issue then? (if it's not already done by now)

**Comment by Kitzunu** [comment]
Can someone go back in commits and try to find the faulty one?

**Comment by Sedatyf** [comment]
> Can someone go back in commits and try to find the faulty one?

You think it's a faulty commit that cause difference between our test?

**Comment by Kitzunu** [comment]
Well something broke dropping items that have QuestRequired = 1

**Comment by Sedatyf** [comment]
Alright, I'll search the faulty commit as soon as possible. I'll get back to you if I find something relevant

**Comment by Sedatyf** [comment]
I tried to go back in commits until 40f2e5e8c11cbb580ec37ac083b49b28a2663d35 but then I couldn't run my ``authserver`` and my ``worldserver``. Maybe because we changed a lot of things in the core?

Here is my error:
```
[ERROR]: In mysql_stmt_prepare() id: 13, sql: "SELECT a.id, a.locked, a.lock_country, a.last_ip, aa.gmlevel, a.salt, a.verifier, a.token_key FROM account a LEFT JOIN account_access aa ON (a.id = aa.id) WHERE a.username = ?"
[ERROR]: Unknown column 'a.token_key' in 'field list'
Closing down DatabasePool 'acore_auth'.
Asynchronous connections on DatabasePool 'acore_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool 'acore_auth' closed.
Could not prepare statements of the Login database, see log for details.
Closing down DatabasePool 'acore_auth'.
```

**Comment by Sedatyf** [comment]
Can somebody help with this?

**Comment by tkn963** [comment]
@Sedatyf I'm not sure it would be a good idea to go that far back, sounds like it's about when salt was added and I have no idea if it's easy enough to revert accounts to that. If there are no accounts, it's just a matter of re-importing the database without newer updates to the tables - no?

**Comment by Sedatyf** [comment]
I went that far gradually, so it's an old problem. And as @poryagholami1374 found it on a really old revision, I don't think it could be this answer

**Comment by tkn963** [comment]
Well, looking at the updates the token_key was dropped in the 2021-05-13 update.

https://github.com/azerothcore/azerothcore-wotlk/blob/c74bb4b88a7452de49dfbcc1a9d9623318fb002a/data/sql/updates/db_auth/2021_05_13_00.sql#L311

**Comment by Sedatyf** [comment]
Hmmm... I'm not sure but I think I came back further than that. Between this and the one I talked before

**Comment by tkn963** [comment]
And it's not a revert of the database on your end too? Basically what I'm asking is if you 'reset' the database and applied the updates up until the point you're at?

**Comment by Sedatyf** [comment]
You make me doubt now 😂 
I'll take a look at it again. If you have time, I won't be against a second pair of eye for this

**Comment by tkn963** [comment]
I sure don't mind helping if I can 😄

**Comment by syssneck** [comment]
Is this still an issue? What actually is the issue here? Quest items sometimes don't drop for Alliance characters?

**Comment by Sedatyf** [comment]
I don't know if it's still an issue. I couldn't tested it again recently. But yes, quest item doesn't drop on Alliance characters

**Comment by tkn963** [comment]
I'll give it a go within the next few days. I'll try my best to test each race to see if it's related only to specific races or the entire faction. I'm not sure what to expect, but the number of times I've done this quest as horde it has always dropped. I never play as Alliance, more or less, so I haven't done much testing there (yet).

**Comment by UltraNix** [comment]
@tkn963 @Sedatyf @poryagholami1374

**Comment by UltraNix** [comment]
No response  - close it.
