### ISSUE TITLE
[RAID] MC Ragnaros' hammer falls facing the wrong direction.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#595]
**Description**: The hammer is falling so the side of the hammer is not visible to the player after Raganros is killed. Having farmed this countless times in retail, and claimed the Eye of Sulfuras myself, I know this is wrong.

**Expected behavior:** 
When the hammer falls, it should land in the lava with the side facing the players giving a full view of the epic hammer from the fight start position. This is the same direction Ragnaros is facing when the fight starts. A bit hard to describe, but if you go check the image you'll see what I mean. 

Right: https://www.flickr.com/photos/erocsid/4021735116/in/album-72157622608658698/
Wrong: https://imgur.com/a/Xi2t8

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Gargarensis** [comment]
I tried to fix this again, and the solution would be to set Ragnaros' facing to 4.0f at the moment he dies.
The problem is: we cannot do it because otherwise his death animation will suck (player kills him and he just rotates randomly). Does someone has an idea?

**Comment by Pondaveia** [comment]
What if Ragnaros would be summoned in the correct position for the hammer to fall where it is suposed to? NPCs tend to turn to their home position.

**Comment by StygianTheBest** [comment]
> What if Ragnaros would be summoned in the correct position for the hammer to fall where it is suposed to? NPCs tend to turn to their home position.

If you did that, Ragnaros would not be facing the party during the fight. He's in the correct position, the problem is the direction he is facing. @Gargarensis was on the right track I think, but this would need trial and error testing to solve.

**Comment by Pondaveia** [comment]
It is possible to change the home position without changing the boss orientation just update its home mid fight i believe. At the start of the fight when he enter combat just updating should do the trick.

**Comment by StygianTheBest** [comment]
Write it up, test it, and post a screenshot if it works.
