### ISSUE TITLE
Quest item for Get the Key does not drop for Alliance characters

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#5951]
**CURRENT BEHAVIOUR:**

Instructor Hroegar (entry: 29915) does not drop the quest item called Key to Vaelen's Chains for quest Get the Key (ID: 12949) for Alliance characters, but drops it for Horde characters.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

It should drop for both factions.

**SOURCE:**

https://github.com/azerothcore/azerothcore-wotlk/issues/5946

**STEPS TO REPRODUCE THE PROBLEM:**

1. Create a character on the Alliance side on a non-GM account
2. Accept the quest (!quest add 12949)
3. Teleport to the creature (!go creature 4763)
4. Kill the instructor and check the loot

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
a9e3d8d13ac6177772aff130ceef3570174bc3df

**OPERATING SYSTEM:**

All

**MODULES:**

None

**CUSTOMIZATIONS:**

None

**Comment by Sedatyf** [comment]
Perfect! Thank you @tkn963

**Comment by IntelligentQuantum** [comment]
It work fine for me

Arch Linux - AzerothCore rev. 556d91a2ea8d 2021-08-19 00:20:07 +0200 (master branch)

https://imgur.com/mbcVM9Y
https://imgur.com/WKkAGSG

**Comment by FrancescoBorzi** [comment]
closing unless someone can reproduce the issue again, thanks @IntelligentQuantum
