### ISSUE TITLE
Quest Buge [Jormuttar is Soo Fat...]

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5955]
## CURRENT BEHAVIOUR:
This phase for
The player does not show
But in gm on mode
You can only see
And it does not bear meat
When I use

## EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.wowhead.com/quest=13011/jormuttar-is-soo-fat

## SOURCE:
![WoWScrnShot_052021_011344](https://user-images.githubusercontent.com/80007195/118882205-2c0fa880-b909-11eb-82ba-b419df238760.jpg)

## STEPS TO REPRODUCE THE PROBLEM:
EXTRA NOTES:
AC HASH/COMMIT:
2021-05-15 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by Sedatyf** [comment]
A make a new issue with better description and explanation @poryagholami1374
I'm closing this one but you can see #5956
