### ISSUE TITLE
Jormuttar is Soo Fat... doesn't loot bear flank when knife is used

### ISSUE THREAD

**Issue by Sedatyf** [azerothcore/azerothcore-wotlk#5956]
## CURRENT BEHAVIOUR:

When you try to use the provided knife from the quest on a dead bear, you don't loot any bear flank in order to toss it in the crater

## EXPECTED BLIZZLIKE BEHAVIOUR:

Those mobs should loot a Bear Flank when you use quest's knife

## SOURCE:

https://www.wowhead.com/quest=13011/jormuttar-is-soo-fat#comments:id=504606

## STEPS TO REPRODUCE THE PROBLEM:

1. ``.quest add 13011``
2. ``.go c 1973077``
3. If the bear is dead, skin him or wait for a respawn
4. Notice the error message "Invalid Target"

## EXTRA NOTES:

![image](https://user-images.githubusercontent.com/59012307/118886111-d16e5080-b8f8-11eb-9071-2e6055f55666.png)

It seems that you can have a bear flank from them with a character on GM mode on. I didn't test it in game but it was reported in #5955 

## AC HASH/COMMIT:
 

d3fcebaac5c8

## OPERATING SYSTEM:

Windows 10

**Comment by Sedatyf** [comment]
Reported in #5955 but wasn't descriptive enough

**Comment by Sedatyf** [comment]
I don't know if this issue is linked to #5946 but if it does, we'll have to check if this one is also fixed by the PR

**Comment by avarishd** [comment]
Works as of rev. df6dcd8888cd8cb90216b4f3d1212e1e0cc24726

https://user-images.githubusercontent.com/46330494/219599460-8d7debc9-9a50-453a-ab46-2e932ccb1e58.mp4
