### ISSUE TITLE
[NPC] Flamewalker Protector outside Molten Core missing waypoints

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#596]
**Description**: 

> WaypointMovementGenerator::LoadPath: creature Flamewaker Protector (Entry: 12119
 GUID: 1992101) doesn't have waypoint path id: 566060
>WaypointMovementGenerator::LoadPath: creature Flamewaker Protector (Entry: 12119
 GUID: 1992102) doesn't have waypoint path id: 566070

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by poszer** [comment]
Duplicate, closing
https://github.com/azerothcore/azerothcore-wotlk/issues/864
