### ISSUE TITLE
Unable to disable 2FA

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#5970]
**CURRENT BEHAVIOUR:**

Updated the core to the latest revision, which automatically enabled 2FA for some reason and made it impossible to log in. Commands are unsuccessful at disabling the feature

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Being able to log in

**SOURCE:**

https://youtu.be/pYyzhw0v3xA

**STEPS TO REPRODUCE THE PROBLEM:**

1. Start the server
2. Log in

**EXTRA NOTES:**

The command 'account set 2fa <account> off' claims it's been successfully disabled but the pop-up keeps happening. Newly created accounts have the same issue. I did a full reset of the database to make sure and it produced the same results. TOTP settings in the configs are all blank

**AC HASH/COMMIT:**
 
dd69dcb1d87b8df455c46d0b6cc800dc774b51a0

**OPERATING SYSTEM:**

Ubuntu 20.04

**MODULES:**

None

**CUSTOMIZATIONS:**

None

**Comment by Kitzunu** [comment]
Reverted the breaking commit. Master works now. 

I will close this issue as it is invalid for current master =)
