### ISSUE TITLE
[Auth] cant login to Server

### ISSUE THREAD

**Issue by Ruok-Capsule** [azerothcore/azerothcore-wotlk#5977]
**CURRENT BEHAVIOUR:**
All Accounts need authenticator digit code , nothing work nobody can login to server

**EXPECTED BLIZZLIKE BEHAVIOUR:**
???

**SOURCE:**
???

**STEPS TO REPRODUCE THE PROBLEM:**
Try to login into the server

**AC HASH/COMMIT:**
AzerothCore rev. dd69dcb1d87b+ 2021-05-20 17:25:46 +0000 (master branch) (Unix, Release) (worldserver-daemon) ready...

**OPERATING SYSTEM:**
Ubuntnu 18.04

**Comment by Kitzunu** [comment]
Update your core, it was already fixed
