### ISSUE TITLE
Cannot get another Tome of Valor if destroyed, need item to start [quest=1649]

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5979]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/676

##### CURRENT BEHAVIOUR:

Cannot get another tome of valor from Duthorian Rall if i delete the one on inventory

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC should provide a replacement for the same item. 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Talk to [npc=6171]
2.  Complete [quest=1793]
3.  Delete item [item=6776]

##### EXTRA NOTES:

Some extra data here:

https://wotlkdb.com/?quest=1793

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: a9e3d8d13ac6):

![WoWScrnShot_052121_043411](https://user-images.githubusercontent.com/82579073/119069225-68690480-b9ee-11eb-9a4d-8b1f02bd5b56.jpg)
![WoWScrnShot_052121_043715](https://user-images.githubusercontent.com/82579073/119069358-af56fa00-b9ee-11eb-8073-fb1b7757f8ac.jpg)

I would add that seems that the same happens to the tome of divinity:

![WoWScrnShot_052121_043901](https://user-images.githubusercontent.com/82579073/119069477-e0cfc580-b9ee-11eb-8f59-7416752d8cd4.jpg)
![WoWScrnShot_052121_043917](https://user-images.githubusercontent.com/82579073/119069486-e4634c80-b9ee-11eb-9d35-57b569dd5e60.jpg)

**Comment by Kitzunu** [comment]
EXPECTED BLIZZLIKE BEHAVIOUR:

**Comment by Ragelezz** [comment]
What gossip text from npc you should have when you delete the item ? Cannot seem to find anything

**Comment by Shineslippers** [comment]
I guess there is should not be text. Same as for The Tome of Divinity https://github.com/azerothcore/azerothcore-wotlk/issues/8746. Need to make 1793 and 1794 are repeatable. On 1649 complete it should not be available anymore.

**Comment by temperrr** [comment]
This has been fixed by previous PRs
