### ISSUE TITLE
Feared mobs walking through closed doors

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5980]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/677

##### CURRENT BEHAVIOUR:

Inside scarlet monastery cathedral,
when a mob gets feared by any source
and the cathedral's door is closed,
if the mob walks towards the door
it will keep walking through and pull everything on the other side.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Feared mobs should not walk through closed doors.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Scarlet Monastery Cathedral
2. Progress until the closed door
3. Have any mob near the door and have it feared (warlock's or warrior's spells, or low hp)
4. Repeat from 3 until a mob's random fear movement makes it walk through the door

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

I have tried to reproduce it on a local AC server (AC HASH/COMMIT: a9e3d8d):

![WoWScrnShot_052121_050924](https://user-images.githubusercontent.com/82579073/119072178-bf250d00-b9f3-11eb-96dd-969bf800dd1a.jpg)
![WoWScrnShot_052121_050959](https://user-images.githubusercontent.com/82579073/119072187-c1876700-b9f3-11eb-974b-eb0c5917efa8.jpg)
![WoWScrnShot_052121_051136](https://user-images.githubusercontent.com/82579073/119072196-c3e9c100-b9f3-11eb-8bea-f9e4911fee47.jpg)

But the most I have achieved is for one of them to go through the door, without bringing the mobs from inside.

**Comment by Azcobu** [comment]
Replicated. Here's a clip showing a low-health enemy running through the door, and coming back with friends:

https://user-images.githubusercontent.com/81782124/119213804-1d8be180-bb01-11eb-95ab-1c13dceb6bce.mp4

It does seem to be low HP rather than fear that does it. Tried with a warrior spamming AoE fear and although one or two did run through the door, they never brought friends back.
