### ISSUE TITLE
Wands should que up instantly before the GCD is over.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5981]
#### WHAT CLIENT DO YOU PLAY ON?

- [X] enGB
- [ ] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/521

##### CURRENT BEHAVIOUR:

Cant que up my wand after any spell that gives a GCD.

For testing purposes, these are the exact item and spell i used.

https://wowgaming.altervista.org/aowow/?item=11287
and
https://wowgaming.altervista.org/aowow/?spell=589

##### EXPECTED BLIZZLIKE BEHAVIOUR:

In classic wow and until wotlk i could que up my wand right after any spell that gave the GCD

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get a wand
2. Cast shadow word pain
3. as soon as that goes off press your wand
4. fail to que up instantly/makes you wait

##### EXTRA NOTES:

You shouldnt have to wait for the GCD to be over, you should instantly be able to que up your wand before the GCD is over. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: a9e3d8d):

![WoWScrnShot_052121_052735](https://user-images.githubusercontent.com/82579073/119073267-a0277a80-b9f5-11eb-8713-9dc15b580590.jpg)
![WoWScrnShot_052121_052816](https://user-images.githubusercontent.com/82579073/119073278-a3226b00-b9f5-11eb-8930-274ce6adca97.jpg)

'Ability is not ready yet' appeared for a few seconds after casting 'shadow word pain'

**Comment by syssneck** [comment]
Yeah, wands shouldn't share the GCD. Classic Video: [Spells do not set the Wand on the GCD, as it should be](https://www.youtube.com/watch?v=vRmldX9Mc00). This can inhibit the levleing/killing speed of priests, mages and warlocks quite a bit.

**Comment by UltraNix** [comment]
Classic is not wotlk.
https://www.mmo-champion.com/threads/660190-Global-Cooldown-on-wand
