### ISSUE TITLE
Stealthed Attacks Against Sitting/Prone Enemy Players Do Not Crit

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#5986]
**CURRENT BEHAVIOUR:**

See also: https://github.com/azerothcore/azerothcore-wotlk/pull/5872

The majority of attacks vs sitting players do crit now, thanks to the above ticket. However, attacks from stealth, such as a feral druid's Ravage, still do not automatically crit vs a sitting or prone target.

Combat log showing multiple Ravages from stealth failing to crit vs a sitting enemy player:
![WoWScrnShot_051821_214827](https://user-images.githubusercontent.com/81782124/119142573-d280b880-ba85-11eb-91d6-64220d3b6ce3.jpg)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Attacks from stealth should crit vs. sitting players. 

**SOURCE:**

This is not controversial.

**STEPS TO REPRODUCE THE PROBLEM:**

1. Duel another player.
2. Have them sit or lie down.
3. Go into Prowl/Stealth and attack them from behind.
4. Note the non-critical hit inflicted.

**AC HASH/COMMIT:**
 
rev. 5b9415be5a8b 2021-05-21 10:25:13 +0000

**OPERATING SYSTEM:**

Linux Mint 20.1

**MODULES:**

N/A.

**CUSTOMIZATIONS:**

N/A.

**Comment by claudiodfc** [comment]
Melee swings should crit but should Melee spells also crit?

**Comment by Azcobu** [comment]
If you mean melee abilities rather than just auto-attacks, I think so. The relevant Wowpedia article (https://wowpedia.fandom.com/wiki/Sit?oldid=1656296) simply says "melee attacks." Besides, with fix https://github.com/azerothcore/azerothcore-wotlk/pull/5872, it would be rather odd and inconsistent to have melee abilities guaranteed to crit while not in stealth, but not guaranteed to crit while in stealth.

Besides, any retail druid or rogue player can tell you how much fun a stealthed Ravage or Ambush against a eating/drinking target is, precisely because of the guaranteed crit.
