### ISSUE TITLE
The Scarlet Apocalypse QUEST BUG

### ISSUE THREAD

**Issue by Seigneur-fantome** [azerothcore/azerothcore-wotlk#5990]
CURRENT BEHAVIOUR:
The liche king is "under" black support and not "on" the black support
![119159759-db5a9580-ba57-11eb-8688-b855a57b07e2](https://user-images.githubusercontent.com/79913664/119161855-0b0a9d00-ba5a-11eb-9730-fa8a0934570c.png)

EXPECTED BLIZZLIKE BEHAVIOUR:
the liche king is on black support
![119160078-2e344d00-ba58-11eb-924d-1fcb64fc05ff](https://user-images.githubusercontent.com/79913664/119161867-0e9e2400-ba5a-11eb-9440-33892b1ef081.png)

SOURCE:
https://fr.wowhead.com/quest=12778/l-apocalypse-%C3%A9carlate

**STEPS TO REPRODUCE THE PROBLEM:**
1) just create death knight
2) use this command ".quest add 12778"
3) go to black support

AC HASH/COMMIT:
azerothcore-wotlk 3.0.0build20210306 x64

OPERATING SYSTEM:
Windows 10 x64

MODULES:
-mod-anticheat ( https://github.com/azerothcore/mod-anticheat )
-mod-eluna-lua-engine ( https://github.com/azerothcore/mod-eluna-lua-engine )
-mod-multi-client-check ( https://github.com/azerothcore/mod-multi-client-check )
-mod-pvp-titles ( https://github.com/azerothcore/mod-pvp-titles )

**Comment by Kitzunu** [comment]
`AC HASH/COMMIT:`

dont ignore the template

**Comment by Seigneur-fantome** [comment]
i will post Hash after next update. sorry for this problem sir.

ty for your patience

**Comment by Kitzunu** [comment]
azerothcore-wotlk 3.0.0build20210306 x64

this is not right. you should get a commit number. post that

Like this
```
AzerothCore rev. 3cacd0f50721+ 2021-05-20 02:47:20 +0200 (skills branch) (Win64, RelWithDebInfo) (worldserver-daemon)

**Comment by Seigneur-fantome** [comment]
i know, i will update next time for that ^^

**Comment by poryagholami1374** [comment]
This is not a mistake
Cache file
Clear the game
And try again
I command lk
.npc moves
I guided him to the front of the stairs

**Comment by Seigneur-fantome** [comment]
Same but. Same without cache

**Comment by poryagholami1374** [comment]
![Uploading WoWScrnShot_052221_005651.jpg…]()

**Comment by poryagholami1374** [comment]
![WoWScrnShot_052221_005651](https://user-images.githubusercontent.com/80007195/119194673-ade20c00-ba98-11eb-9f72-14169d86779a.jpg)

**Comment by poryagholami1374** [comment]
> Same but. Same without cache

From command
.npc moves
Use it
Guide to the front of the stairs

**Comment by Seigneur-fantome** [comment]
Ok. I lls update my server next Times and i say if i have the same bug

**Comment by Seigneur-fantome** [comment]
Your mixture. It s server tokay?

**Comment by poryagholami1374** [comment]
> Your mixture. It s server tokay?

No, there is no place for advertising, if you have a problem, say so
From the command
.npc moves
Use No need to update due to minor issues

**Comment by Kitzunu** [comment]
I will close as no real rev is shown
