### ISSUE TITLE
Must restart the server so gameobjects can spawn and be usable.

### ISSUE THREAD

**Issue by arielcami** [azerothcore/azerothcore-wotlk#5996]
**CURRENT BEHAVIOUR:**

When I add a gameobject, I have to restart the server for it to take effect, because it doesn't spawn right away.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Gameobjects must spawn at the time you write the command.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

- .gobject add 191014  (Portal to Shattrath)

**EXTRA NOTES:**

- I tried relogging, deleting cache, typing /reload, adding other objects,  nothing worked, only a server restart.

**AC HASH/COMMIT:**
 
AzerothCore rev. 63a273507c75

**OPERATING SYSTEM:**

Windows10 x64

**MODULES:**

No modules

Screenshot:
Before typing the command:
![write](https://user-images.githubusercontent.com/71854140/119210177-942cce80-ba70-11eb-8288-314356ecae3f.jpg)

After typing the command.
![enter](https://user-images.githubusercontent.com/71854140/119210192-a60e7180-ba70-11eb-892d-da228fc19290.jpg)

**Comment by Kitzunu** [comment]
deuplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/5597
