### ISSUE TITLE
[NPC] Creature 18948, 18950, 18972, 18986 waypoint errors

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#600]
**Description**: 
>SmartAI::StartPath: Creature entry 18948 wanted to start waypoint movement while in combat, ignoring.
>SmartAI::StartPath: Creature entry 18950 wanted to start waypoint movement while in combat, ignoring.
>SmartAI::StartPath: Creature entry 18972 wanted to start waypoint movement while in combat, ignoring.
>SmartAI::StartPath: Creature entry 18986 wanted to start waypoint movement while in combat, ignoring.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by talamortis** [comment]
These are all the creatures spawned inside the dark portal right?

**Comment by Middel** [comment]
These ones show up ALOT in my console. 

SmartAI::StartPath: Creature entry 18950 wanted to start waypoint movement while in combat, ignoring.
SmartAI::StartPath: Creature entry 18970 wanted to start waypoint movement while in combat, ignoring.
SmartAI::StartPath: Creature entry 18972 wanted to start waypoint movement while in combat, ignoring.

Its about the following creatures/npc's:

18972 = Orgrimmar Shaman
18970 = Darkspear Axe Thrower
18950 = Orgrimmar Grunt
18986 = IronForge Paladin
18948 = Stormwind Soldier

Those 5 entries show as error in the Console alot. just like @StygianTheBest has reported.

**Comment by BarbzYHOOL** [comment]
Maybe there is something wrong with the Smart_scripts

For creature_template 18950:

```
Orgrimmar Grunt - On Timed Event - Start WP
SMART_EVENT_TIMED_EVENT_TRIGGERED
event id 1 ## I don't know which event isthis
```

**Comment by poszer** [comment]
Is this confirmed? For months, i didnt get errors like these

**Comment by poszer** [comment]
Same problem again >.<

http://prntscr.com/n9bfu2
http://prntscr.com/n9bgs0

18972 - Orgrimmar Shaman
18970- Darkspear Axe Thrower
18950 - Orgrimmar Grunt

Re-opening this ..

**Comment by poszer** [comment]
The errors are from Dark Portal
http://prntscr.com/n9bpm2
http://prntscr.com/n9bpw8

Duno what's changed here, but this event is reported that is triggered once the player is in the area, and a few minutes later, we see the creatures arrive.
But what activate it now, there is no players here lol

https://github.com/azerothcore/azerothcore-wotlk/issues/1376

**Comment by Stoabrogga** [comment]
I'll look into this
