### ISSUE TITLE
Feature: ICC Buff Choice

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/azerothcore-wotlk#6017]
**Describe your feature request or suggestion in detail**
It would be great if **the players** could choose the percentage of the buff at the beginning of ICC 

**Describe a possible solution to your Feature or Suggestion in detail**
You could add another gossip at Tirion or Garrosh, where you can choose 5%, 10%, etc. 

**Additional context**

**Comment by Maurowin** [comment]
You can already do this in worldserver conf file.

![image](https://user-images.githubusercontent.com/31663279/119255554-c0556600-bbbc-11eb-8423-c5a2d2751746.png)

**Comment by Err0r1** [comment]
> You can already do that in worldserver conf file.
> 
> ![image](https://user-images.githubusercontent.com/31663279/119255554-c0556600-bbbc-11eb-8423-c5a2d2751746.png)

It would be great if the players could choose it themselves

**Comment by heyitsbench** [comment]
I think this is better suited as a module rather than something core-side.

**Comment by Winfidonarleyan** [comment]
> I think this is better suited as a module rather than something core-side.

Agreed

**Comment by Kitzunu** [comment]
Module.
