### ISSUE TITLE
Brew of the Month Club, no rewards or purchaseable items

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6024]
**CURRENT BEHAVIOUR:**

The Npc gives you nothing after completing the quest and earning the achievement.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Should give you options to buy.

**SOURCE:**

https://www.wowhead.com/quest=12420/brew-of-the-month-club#comments

**STEPS TO REPRODUCE THE PROBLEM:**

1. Add the quest item and start the event.
2. Complete the quest and get the achievement.
3. See if there are rewards.

**EXTRA NOTES:**

![WoWScrnShot_052421_093114](https://user-images.githubusercontent.com/82579073/119306437-d0c81800-bc72-11eb-9afd-63ffcd0408cf.jpg)

![WoWScrnShot_052421_091326](https://user-images.githubusercontent.com/82579073/119305277-33b8af80-bc71-11eb-920a-1022ab0da0c3.jpg)
![WoWScrnShot_052421_091343](https://user-images.githubusercontent.com/82579073/119305321-4206cb80-bc71-11eb-8894-dcb5cae3da7d.jpg)
![WoWScrnShot_052421_091352](https://user-images.githubusercontent.com/82579073/119305351-4fbc5100-bc71-11eb-83d9-38bc76a3202f.jpg)
![WoWScrnShot_052421_091434](https://user-images.githubusercontent.com/82579073/119305393-5c40a980-bc71-11eb-81ba-668362b57b74.jpg)

**AC HASH/COMMIT:**
 
ea76481
**OPERATING SYSTEM:**

AC on docker in Windows 10 20H2
**MODULES:**

**CUSTOMIZATIONS:**

No.

**Comment by UltraNix** [comment]
Gossip is shown if you have at least one Prize Token.
