### ISSUE TITLE
Hunter Pet's 'Furious Howl' Ability Incorrectly Buffs Entire Party At Rank 1

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6027]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/691

Hunter's wolf pet ability Furious Howl (https://wotlkdb.com/?spell=24604) incorrectly applies the buff to other party members.

Tester's note - this applies to Rank 1 Furious Howl only. Tested all other ranks and they were fine.

Screenshot showing druid party member being affected:
![WoWScrnShot_052421_230515](https://user-images.githubusercontent.com/81782124/119355539-8bdcc980-bce4-11eb-9224-b79939debf35.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

_Increases melee and ranged attack power by 18 for_ **the wolf and its master** _for 20sec._ Should only apply buff to master and its pet. 

Tester's notes: There is confusion over this because the spell changed in patch 3.1, from affecting the whole party/raid, to just the hunter + pet. See https://wowpedia.fandom.com/wiki/Furious_Howl?oldid=2378669

Also, for a contemporary source, Petopia's page on Wolf pets is here: https://web.archive.org/web/20100510154824/http://www.wow-petopia.com:80/html/skills/skills_furioushowl.html - Cata was released on 12th October 2010, so this snapshot from May 2010 is as close as we can get to contemporary data. This also supports the claim that only the hunter and pet should be affected.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be hunter class.
2. Have Wolf pet.
3. Be in a party with other characters. Be close to them. 
4. Use pet ability: Furious Howl. 
5. Notice as buff applies to whole party members. 

##### EXTRA NOTES:

Link: https://wowgaming.altervista.org/aowow/?spell=24604

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
fixing
