### ISSUE TITLE
Various packet issues

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#6028]
**CURRENT BEHAVIOUR:**

Incoming heals from other players no longer show up in any healing addon, which makes raid healing a bit messy. Occasionally characters run in place but I can't seem to find a reliable way to replicate that yet. There are errors printed in the console when trying to perform actions like healing, attacking etc which sometimes is accompanied by a melee class not being able to attack

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Players using healing addons should be able to see incoming heals from other players, assuming they also have libhealcomm or anything that uses that lib. The issue with running in place I can't replicate enough to prove it's there. Melee shouldn't get errors about line of sight when there is no actual issue

**SOURCE:**

https://imgur.com/a/50SZ0hX

**STEPS TO REPRODUCE THE PROBLEM:**

1. Install a healing addon (like VuhDo)
2. Log in using at least 2 characters
3. Make one of them take damage
4. Start casting a heal, or HoT, on that character using the other one

**EXTRA NOTES:**

I have tested every commit from the last week up until and including 63a273507c753e6d130e8ae2dd7d9d15bf2dd02b and found that the issue started after that commit

**AC HASH/COMMIT:**
 
ea764812d14a494f8f7bbbfb270f0dd3ebbb2bef

**OPERATING SYSTEM:**

Ubuntu 20.04

**MODULES:**

None

**CUSTOMIZATIONS:**

None

**Comment by Sedatyf** [comment]
It's maybe related to #5617
I tested it but unfortunately I was alone for that

**Comment by Sedatyf** [comment]
If you checkout your branch before this commit, can you reproduce this behavior?

**Comment by tkn963** [comment]
I tested every commit from 40ed3a575ba4ba3eff9d218d018de6a20b6e29db up to ea764812d14a494f8f7bbbfb270f0dd3ebbb2bef one by one and the issues started with 63a273507c753e6d130e8ae2dd7d9d15bf2dd02b which is the one you linked

**Comment by Sedatyf** [comment]
It does make sense. @Winfidonarleyan can you have a look on that? We have an issue related to your changing of packet handling (#5617)

**Comment by tkn963** [comment]
The whole incoming heal from other players is obviously not game breaking in any way, shape or form but more of a convenience. I don't notice the LoS issues much since I don't play those much, but I noticed a few things more. While I was testing these issues, I used a GM character with GM off - used gm fly to go up and then gm fly off to drop down and take damage. After landing, a character that tries to heal the GM at that point got errors about LoS too which is where those errors in the console were from when I took the screenshot. After the healer moved, LoS errors were gone. I need to test using a regular account and just dismount from a flying mount to take the damage instead

**Comment by tkn963** [comment]
Actually, I found that the healer gets a message that he/she can't cast that while moving even though they are perfectly still. Very strange.

**Comment by Winfidonarleyan** [comment]
I'll try to fix it in the near

**Comment by Viste** [comment]
ахахаххах сука хорошо!!!!! аааа

**Comment by Winfidonarleyan** [comment]
Try #6051

**Comment by tkn963** [comment]
> 
> 
> Try #6051

I tried it. Since I can't replicate the other issues reliably, I could only test the incoming heals from other players issue and the issue unfortunately persists.

**Comment by Winfidonarleyan** [comment]
> > Try #6051
> 
> I tried it. Since I can't replicate the other issues reliably, I could only test the incoming heals from other players issue and the issue unfortunately persists.

Can make video? I don't understand how to reproduce this.

**Comment by tkn963** [comment]
Two characters, at least one that can heal. Both must have a healing addon with libhealcomm. I prefer VuhDo - it has healcomm built-in. One of the characters takes damage, one of the characters heals that character (no need to finish the heal, just interrupt it before it finishes) and the other character (the one that is NOT casting the heal) should see the health bar in VuhDo of the damaged character have some faded health showing to show incoming heals. The character that casts the heal will always see it. Video linked below to hopefully clear up what I just wrote.

https://youtu.be/CpkJsiTVrFQ

**Comment by tkn963** [comment]
For the sake of it, he's overheal and healing over time: https://youtu.be/ibUr6XHtE9g

I should say that incoming heals will not show on the first character when the second character is healing the first character - you can see that in the video. The female druid is casting on the male druid and it's not showing up on the male druid which is the character recorded.

**Comment by Winfidonarleyan** [comment]
Closed via pr #6051
