### ISSUE TITLE
Redridge Mountains - Redridge Mongrel drops Easter Dress

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#6029]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Redrige mongrel, a Redrige mountains gnoll, just dropped an Easter dress.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I think no mobs should drop this at any point.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Maybe it's a one time thing, but mobs there do have a chance to drop this items.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Can confirm

```sql
SELECT clt.* FROM `item_template` it JOIN `creature_loot_template` clt ON it.Entry = clt.Item WHERE it.name = "Easter Dress";
```
```
+-------+------+-----------+----------+---------------+----------+---------+----------+----------+---------------------------------+
| Entry | Item | Reference | Chance   | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment                         |
+-------+------+-----------+----------+---------------+----------+---------+----------+----------+---------------------------------+
|   423 | 7809 |         0 | 0.384986 |             0 |        1 |       0 |        1 |        1 | Redridge Mongrel - Easter Dress |
+-------+------+-----------+----------+---------------+----------+---------+----------+----------+---------------------------------+
```

**Comment by Eldarix** [comment]
Original report: https://github.com/chromiecraft/chromiecraft/issues/692

;)
