### ISSUE TITLE
Core/Script: Wintergrasp - Goblin Workshops

### ISSUE THREAD

**Issue by Sindrax** [azerothcore/azerothcore-wotlk#603]
**Description**:  http://wowwiki.wikia.com/wiki/Wintergrasp - Goblin Workshops part

**Current behaviour**:  After Wintergrasp Keep has been captured, or successfully defended, the four outside workshops(Sunken, Broken Temple, Westspark and Eastspark) are not automatically captured based on the result of the battle. 

**Expected behaviour**: Sunken WS and Broken Temple WS should be automatically captured by the controlled side after the Battle for Wintergrasp has just concluded
Westspark WS and Eastspark WS should be automactically captured by the attack side after the Battle for Wintergrasp has just concluded.

**Steps to reproduce the problem**:

1.  Join Wintergrasp Battle
2.  Win
3. Click M and see Current behaviour above

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue): Master

**AC hash/commit**:   b450ba3

**Operating system**:   Window Server 2016

**Modules**:  Are you using modules? if yes, list them
Transmog, anticheat

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Sindrax** [comment]
Somehow this is pretty hard to make it works

**Comment by Viste** [comment]
i try to fix it in april but fucked up and forgot

**Comment by Sindrax** [comment]
I tried too, but it pretty different with trinitycore or other 335a source :/

**Comment by Si1ker** [comment]
Still bugged.  ;c 

![image](https://user-images.githubusercontent.com/61223313/110224797-650cb500-7ea4-11eb-9235-41a5614391fa.png)

**Comment by alexandru58** [comment]
Still not fixed?

**Comment by FrancescoBorzi** [comment]
> Still not fixed?

@alexandru58 you can test it on the latest AC and let us know whether it's still bugged or not ;)

**Comment by Alexander990608** [comment]
It's still bugged! Please fix it.
