### ISSUE TITLE
Stormwind PVP NPC with bugged question mark

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6031]
**CURRENT BEHAVIOUR:**

The quest reward 'Sentinel Basic Care Package' doesn't remove the question mark when completing it.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

I'm not a pvper but I suppose that as in any mission, when completing it, the question mark should disappear.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to the Stormwind's Champion's Hall without having completed the mentioned quest.
2. Talk to the npc and complete it.
3. See if the question mark disappears. 

**EXTRA NOTES:**

![WoWScrnShot_052421_224007](https://user-images.githubusercontent.com/82579073/119399879-1b34ad80-bce2-11eb-8a7d-1da28f47bd6d.jpg)
![WoWScrnShot_052421_224018](https://user-images.githubusercontent.com/82579073/119399917-2a1b6000-bce2-11eb-8e05-66c1ed07d3a3.jpg)
![WoWScrnShot_052421_224030](https://user-images.githubusercontent.com/82579073/119399971-39021280-bce2-11eb-8db0-167376c15618.jpg)

**AC HASH/COMMIT:**
 

ChromieCraft AzerothCore e50754d80498

**OPERATING SYSTEM:**

Windows 10 20H2

**MODULES:**

The ones at the Chromie server.

**CUSTOMIZATIONS:**

**Comment by UltraNix** [comment]
It looks okay to me on my local. Need confirmation.

**Comment by FrancescoBorzi** [comment]
@azerothcore/bug-triaging please check this

**Comment by IntelligentQuantum** [comment]
It works fine for me
