### ISSUE TITLE
'The missing diplomat' speak to Mikhail part buged

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6032]
**CURRENT BEHAVIOUR:**

You cannot continue the quests.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

You should be able to complete it.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Complete the quest chain until you reach that part.
2. See if you can complete it.

**EXTRA NOTES:**

I have seen that there are several reports open about this chain of quests, but none about the specific error that I have encountered.

![WoWScrnShot_052421_231805](https://user-images.githubusercontent.com/82579073/119403750-816fff00-bce7-11eb-849d-2c04d8e49ff4.jpg)
![WoWScrnShot_052421_232027](https://user-images.githubusercontent.com/82579073/119403797-92b90b80-bce7-11eb-9193-c58c2c1bcdcb.jpg)

**AC HASH/COMMIT:**
 

ChromieCraft AzerothCore e50754d

**OPERATING SYSTEM:**

Windows 10 20H2

**MODULES:**

The ones at the Chromie server.

**CUSTOMIZATIONS:**

**Comment by Stump876** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5780 
Duplicate
