### ISSUE TITLE
(Scripts/Ulduar): Flame Leviathan hard mode boss fight issue

### ISSUE THREAD

**Issue by xclid** [azerothcore/azerothcore-wotlk#6033]
**CURRENT BEHAVIOUR:**

Unable to start encounter Flame Leviathan hard mode boss fight, after talking with Lore Keeper of Norgannon.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

After talking with Lore Keeper of Norgannon, it should encounter Flame Leviathan hard mode boss fight.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. .go c 136605
2. talk to Lore Keeper of Norgannon
3. do the Flame Leviathan boss fight

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
a9e3d8d13ac6177772aff130ceef3570174bc3df

**OPERATING SYSTEM:**

win10

**MODULES:**

mod-ah-bot
mod-anticheat
mod-cfbg
mod-eluna-lua-engine
mod-individual-xp
mod-transmog

**CUSTOMIZATIONS:**

**Comment by bgcfb** [comment]
fix:
C++:in instance_ulduar.cpp line 127

                m_leviathanTowers[i] = true;//change frome false

SQL:DB:acore_world

DELETE FROM `smart_scripts` WHERE (`entryorguid` = 33686) AND (`source_type` = 0) AND (`id` IN (9));
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(33686, 0, 9, 16, 61, 0, 100, 0, 10477, 0, 0, 0, 0, 83, 1, 0, 0, 0, 0, 0, 10, 136253, 33579, 0, 0, 0, 0, 0, 0, 'Lore Keeper of Norgannon - On Gossip Option 0 Selected - Remove Npc Flags Gossip');



INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(33686, 0, 16, 0, 61, 0, 100, 0, 10477, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 10, 136253, 33579, 0, 0, 0, 0, 0, 0, 'Lore Keeper of Norgannon - On Gossip Option 0 Selected - Set Data 1 1');

**Comment by FrancescoBorzi** [comment]
@bgcfb hey, can you please [create a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with your fix?

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/5e7166977e1a360ce8cb5d0af1ed5bfd9d6f73fc
