### ISSUE TITLE
Blood Fury (Orc racial ability) stat display issue

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6036]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/693

##### CURRENT BEHAVIOUR:

The Orc racial active ability Blood Fury (https://wowgaming.altervista.org/aowow/?spell=20572) incorrectly displays the number of Attack Power granted as 6 - the base amount for a lvl 1 character - both in the spellbook and when moused over on the skill bar. The active buff icon, however, displays the correct amount. Confirmed with another orc warrior. Not certain about the Spell Power version of the ability.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Self-explanatory.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be orc warrior above level 1 (Blood Fury amount of AP increased scales with character level)
2. check spellbook

##### EXTRA NOTES:

Screenshots:

Incorrect amount displayed in spell book: https://ibb.co/qs8YnRZ
Correct amount displayed on buff icon: https://ibb.co/sjVJ7dR

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/e50754d804987ec93792b6a4d113913ab018189b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: ea76481):

![WoWScrnShot_052521_090103](https://user-images.githubusercontent.com/82579073/119447113-17cc1100-bd38-11eb-96e0-a1939858a19d.jpg)
![WoWScrnShot_052521_090108](https://user-images.githubusercontent.com/82579073/119447223-434efb80-bd38-11eb-9898-7dc3ddf0d5a8.jpg)
![WoWScrnShot_052521_090114](https://user-images.githubusercontent.com/82579073/119447328-69749b80-bd38-11eb-9f7c-60ea434f7dd0.jpg)

**Comment by Eldarix** [comment]
It's something missing here to add it to the 'to do' list ?

**Comment by FrancescoBorzi** [comment]
@Eldarix no, I should just have missed this. Thanks for reminding
