### ISSUE TITLE
Manual Crowd Pummeler cooldown can be bypassed

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6054]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Manual Crowd Pummeler](https://wowgaming.altervista.org/aowow/?item=9449) cooldown can be reset.

Link to CC original report. [https://github.com/chromiecraft/chromiecraft/issues/702](https://github.com/chromiecraft/chromiecraft/issues/702)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should have a 60 minute cooldown on use

##### STEPS TO REPRODUCE THE PROBLEM:

1. .add item 9449 (Manual Crowd Pummeler)
2. Equip and "use" the item
3. Unequip, then re-equip
4. Log out and back in
5. Observe roughly 21 seconds left on cooldown
6. Apparently this can also happen through RDF zoning as well, though I can't verify solo.

##### EXTRA NOTES:

![image](https://user-images.githubusercontent.com/68164076/119601284-b2ab0680-bd9d-11eb-9cfd-89f5c2054475.png)
After following steps above:
![image](https://user-images.githubusercontent.com/68164076/119601348-dc642d80-bd9d-11eb-82a5-a8595d54a7b4.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Added to my long todo list

**Comment by Stump876** [comment]
Looks like this is not just for this item in particular.
