### ISSUE TITLE
Difficulty flying with the bird to other maps

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6056]
## CURRENT BEHAVIOUR:
I released this
But I can not use them to go to other cities
May
More than half of the birds
Are disabled

## SOURCE:
![WoWScrnShot_052621_122303](https://user-images.githubusercontent.com/80007195/119624333-46241c00-be1e-11eb-9e42-bc4dcb7bce27.jpg)
![WoWScrnShot_052621_122504](https://user-images.githubusercontent.com/80007195/119624344-49b7a300-be1e-11eb-9dbd-bf7da098d9bf.jpg)

## STEPS TO REPRODUCE THE PROBLEM:
.go cre 88154
.go cre 115297

## AC HASH/COMMIT:
rev. 579dbe1e5ffc+ 2021-05-31 17:05:09

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by poryagholami1374** [comment]
https://user-images.githubusercontent.com/80007195/120111043-84ef0480-c185-11eb-9918-7a025cac967d.mp4

The use of flyers is difficult
After relog
This symbol appears on npc again
And some of them do not work at all
They do not allow flying

**Comment by avarishd** [comment]
@Kitzunu Wrong/Fixed

![northrendfp (2)](https://user-images.githubusercontent.com/46330494/168450247-d436681c-0ca2-4806-8b77-54728ec02a3e.jpg)


Green exclamation mark doesn't show again for already learned taxi location

https://user-images.githubusercontent.com/46330494/168450156-f436a97f-8272-4bed-ae26-fdb05888ad61.mp4
