### ISSUE TITLE
fix crash issue that happens randomly when I explore the world? C0000005 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by AndrewQ91** [azerothcore/azerothcore-wotlk#6060]
[50adcf206567+_worldserver.exe_[26-5_23-38-44].txt](https://github.com/azerothcore/azerothcore-wotlk/files/6548273/50adcf206567%2B_worldserver.exe_.26-5_23-38-44.txt)

**STEPS TO REPRODUCE THE PROBLEM:**

- there are a couple areas in my build that produce the crash. when I visit the weapon master in Orgrimmar.
- when I enter the mage trainer's room in the Human starting zone.
- when I jump off the top of barrack in durotar, where Lieutenant Benedict spawns

**EXTRA NOTES:**
I have tried recompiling the build with no custom modules but the crash still happens

**OPERATING SYSTEM:**
Windows 10

**MODULES:**
Yes, but then I re compiled with no modules... issue happens in both cases

**CUSTOMIZATIONS:**
Yes/no, same as above... I have also changed some cells in the database (heidisql)

**Comment by Kitzunu** [comment]
Please resolve these two issues:

1. Nobody wants to download files, copy the contents of your file into a PasteBin or https://gist.github.com and attach that link
2. Do not ignore parts of the issue template, more specifically: What rev are you on?

**Comment by Kitzunu** [comment]
I couldnt reproduce it yesterday.
