### ISSUE TITLE
Problem when trying to turn on the emulator

### ISSUE THREAD

**Issue by pangolp** [azerothcore/azerothcore-wotlk#6062]
**CURRENT BEHAVIOUR:**

For some unknown reason, when I added the boots library, the authserver did not work.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Before the addition of the library, you could compile the emulator without any problems.

**SOURCE:**

https://www.azerothcore.org/wiki/windows-requirements

**STEPS TO REPRODUCE THE PROBLEM:**

1. Clone or update the repository.
2. Attempt to run the authserver

**EXTRA NOTES:**

I think it could be the version of the library, so I have installed 1.70.0 and 174.0 but with both, I get the same result.

**AC HASH/COMMIT:**

https://github.com/azerothcore/azerothcore-wotlk/commit/78e1719c80e8c3174461dcee3a25bcd77438b450

**OPERATING SYSTEM:**

Windows 10

**MODULES:**

I have no modules.

**CUSTOMIZATIONS:**

A small modification in adding a custom race, but it is not the problem, because previously it could be compiled without problems.

![1 70 0](https://user-images.githubusercontent.com/2810187/119713486-1d108500-be38-11eb-9c32-6a267d46ef5c.png)

![1 74 0](https://user-images.githubusercontent.com/2810187/119713498-21d53900-be38-11eb-9911-968a7c2bb3ab.png)

**Comment by arielcami** [comment]
I confirm this.

**Comment by Winfidonarleyan** [comment]
Try https://github.com/azerothcore/azerothcore-wotlk/pull/5626

**Comment by tkn963** [comment]
This is not an issue on Ubuntu 20.04 for me, perhaps it's a Windows-related issue?

**Comment by pangolp** [comment]
> This is not an issue on Ubuntu 20.04 for me, perhaps it's a Windows-related issue?

Only with Windows for the moment, but you have to test the PR mentioned above.

**Comment by tkn963** [comment]
> 
> 
> > This is not an issue on Ubuntu 20.04 for me, perhaps it's a Windows-related issue?
> 
> Only with Windows for the moment, but you have to test the PR mentioned above.

I don't use Windows for anything server-related, but I'll test that PR on Ubuntu

**Comment by Winfidonarleyan** [comment]
This problem only in win. In other platforms normal
