### ISSUE TITLE
npcs that They are broken And they knock on the wall

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6064]
## CURRENT BEHAVIOUR:
Use npc
They have problems in all maps
They hit the ground against the wall
They seem to be crazy

## EXPECTED BLIZZLIKE BEHAVIOUR:
NPC moves must be corrected
He taught them the right way

## SOURCE:

https://user-images.githubusercontent.com/80007195/119717396-7cdc4f80-be7b-11eb-8755-9e0b6084724c.mp4

## STEPS TO REPRODUCE THE PROBLEM:
.go cre 78387

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by pangolp** [comment]
From what I see, you are using a revision from about a month ago, did you check if that problem was not fixed? I would try to update the emulator.

**Comment by poryagholami1374** [comment]
> From what I see, you are using a revision from about a month ago, did you check if that problem was not fixed? I would try to update the emulator.

I have seen it many times since a few months ago

**Comment by poryagholami1374** [comment]
There are many of them now, I will definitely provide photos of other films

**Comment by Sedatyf** [comment]
We already told you to upgrade @poryagholami1374 
@pangolp is right, you should check again with an up to date server

**Comment by poryagholami1374** [comment]
> We already told you to upgrade @poryagholami1374
> @pangolp is right, you should check again with an up to date server

Well, you try this, I saw it much earlier
And I manually entered the vip script into the source
I have to build the module
So I can update

**Comment by poryagholami1374** [comment]
https://user-images.githubusercontent.com/80007195/119720636-78199a80-be7f-11eb-8a94-27f0e5286181.mp4

**Comment by poryagholami1374** [comment]
https://user-images.githubusercontent.com/80007195/119726108-f9742b80-be85-11eb-883f-4659cfb99bd3.mp4

This is why it goes to earth
Is it earthworm?

**Comment by poryagholami1374** [comment]
https://user-images.githubusercontent.com/80007195/119729011-60dfaa80-be89-11eb-9929-1ed0b7f5f02f.mp4

Sorry
Should these be 2 to 2?

**Comment by tkn963** [comment]
> 
> 
> We already told you to upgrade @poryagholami1374
> @pangolp is right, you should check again with an up to date server

I can confirm that the Shattered Sun Sentry at Isle of Quel'Danas have this issue. They are trying to attack creatures that are flying high above but can't reach them so they do some weird dance and just follow their target while doing so. Some moonwalk, spin around, then moonwalk again.

This occurs when using 78e1719c80e8c3174461dcee3a25bcd77438b450

Sources of these specific creatures:
https://youtu.be/w-2kM1gpruY
https://youtu.be/BQrR_Q-kCes

**Comment by Sedatyf** [comment]
Thanks a lot @tkn963 for verifying this

**Comment by Gultask** [comment]
Still an issue as of https://github.com/azerothcore/azerothcore-wotlk/commit/324112ff4fcb52416dea7444c9c80a7781b57ebf

Shattered Sun Sentry, at least 2 of them, have crazy waypoints it seems.
