### ISSUE TITLE
Can't revive dead people in Halls of Lightning

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6066]
### CURRENT BEHAVIOUR:
If people in your party die against Crystal, you can't revive them with a spell like Paladin's Redemption.
Edit: As @ Si1ker pointed out, this problem is only in the part of the inn where the last bass is. Please, take a look at his opinion

### EXPECTED BLIZZLIKE BEHAVIOUR:
You should be able to revive dead people like every instance.

### SOURCE:

https://user-images.githubusercontent.com/80007195/119741117-511c9200-be9a-11eb-8987-462f3c11e235.mp4

### STEPS TO REPRODUCE THE PROBLEM:
.go cre 126985
Go there and wait until you die
Then try to revive that hero with another hero

### AC HASH/COMMIT:
rev. 40f2e5e+ 2021-05-09 03:33:01

### OPERATING SYSTEM:
Windows Server 2019 Standard

### MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by poryagholami1374** [comment]
This post
Should I close?

**Comment by Sedatyf** [comment]
It will be closed when it will be merged, don't worry

**Comment by poryagholami1374** [comment]
> It will be closed when it will be merged, don't worry

Thanx you
