### ISSUE TITLE
[RAID] UBRS  The fire runes are not always extinguished

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#607]
**Description**: Each room at the beginning has a fire rune on the floor. These runes are supposed to go out when the mobs are killed. I've seen it work, but I've also seen it not work. I've ran the dungeon several times.

**Expected**
> The first room is divided in 7 little chambers, in each of these chambers 4 orcs which you must defeat to unlock the runes. Once the seven runes are unlit, the door to the next room opens. 
http://wow-pro.com/dungeon_and_raid_guides/60_jame039s_upper_blackrock_spire_guide_ubrs

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by StygianTheBest** [comment]
Nothing fancy, just ran in and lit up all the mobs in each room. As stated, a few times I'd see some of the runes still lit. It didn't happen every time. I remember back in retail there was sometimes a mob hidden in a corner that didn't get pulled, but I checked that too. I'll run a few more tests and close this if I can't reproduce it in 3 runs.

**Comment by Gargarensis** [comment]
Very strange, I checked the code and it seems correct, the check on which group has been killed is repeated every 3 seconds.

**Comment by poszer** [comment]
Tested 5 times. Runes are on the floor. The every room have some mobs inside, while killing them, the Fire Rune is activated for each room. When all rooms are cleaned the doors are opened.

Closing
