### ISSUE TITLE
Barrens - Double mining node spawns

### ISSUE THREAD

**Issue by sij1nk** [azerothcore/azerothcore-wotlk#6070]
Original report: https://github.com/chromiecraft/chromiecraft/issues/712

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

GUID 5067 & GUID 15496
![double1](https://user-images.githubusercontent.com/80769357/119775712-470f8900-bec4-11eb-9fe3-194375a27a3f.jpg)

GUID 4780 $ GUID 15009
![double2](https://user-images.githubusercontent.com/80769357/119775734-4c6cd380-bec4-11eb-9aee-743874be5974.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Veins should not be spawn next to eachoter/inside eachother.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2. See double spawn

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Can confirm on local AC server (78e1719)

![WoWScrnShot_052721_093914](https://user-images.githubusercontent.com/39011611/119785972-0158bd80-bed0-11eb-92f4-1449aae0c2ae.jpg)

![WoWScrnShot_052721_093937](https://user-images.githubusercontent.com/39011611/119785981-03228100-bed0-11eb-8ba1-195a45581f4b.jpg)

**Comment by poryagholami1374** [comment]
It is better to put it in only one post because I saw several times how many posts have been created in this case
If we do this, the number of posts will decrease
And your focus will be on the fixer

**Comment by Kitzunu** [comment]
This is fine. No need to make reports huge

**Comment by poryagholami1374** [comment]
> This is fine. No need to make reports huge


That is, to create a new post for every 4 stones?

**Comment by Kitzunu** [comment]
Go ahead, will be easier to keep track instead of new people commenting in one post making it super long and possible to miss stuff

**Comment by poryagholami1374** [comment]
> Go ahead, will be easier to keep track instead of new people commenting in one post making it super long and possible to miss stuff

Isn't it better to put them all together and fix them together?
I know most of them

**Comment by poryagholami1374** [comment]
![WoWScrnShot_052721_122515](https://user-images.githubusercontent.com/80007195/119787952-f8271b00-bee6-11eb-83cb-a9e0c1afdbb9.jpg)

**Comment by poryagholami1374** [comment]
> Go ahead, will be easier to keep track instead of new people commenting in one post making it super long and possible to miss stuff

If it is one meter away, is it wrong or should they just be too close?

**Comment by poryagholami1374** [comment]
![WoWScrnShot_052721_130300](https://user-images.githubusercontent.com/80007195/119793706-12172c80-beec-11eb-9aa0-61367ff7fa9c.jpg)

**Comment by poryagholami1374** [comment]
![WoWScrnShot_052721_133900](https://user-images.githubusercontent.com/80007195/119799160-1134c980-bef1-11eb-88b0-d18d1909dd88.jpg)

**Comment by poryagholami1374** [comment]
![WoWScrnShot_052721_144612](https://user-images.githubusercontent.com/80007195/119809468-66290d80-befa-11eb-80a7-d52f280eacc3.jpg)

**Comment by jamadaha** [comment]
Should note that some of these duplicates have been fixed with this PR https://github.com/azerothcore/azerothcore-wotlk/pull/7430
