### ISSUE TITLE
Wrong aggro distance calculation

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/azerothcore-wotlk#6079]
**CURRENT BEHAVIOUR:**
Currently the distance calculation is solved using a pattern that is not blizzlike.
The only really functional solution is in the VMangos project.
https://github.com/vmangos/core/commit/9f50e90ac9ed7db233a7343b324c559e021bb5b3
I attach a picture from Vmangos creature_template DB
 The detection_range item is no longer global but separate for each creature type.
![image](https://user-images.githubusercontent.com/5585555/119868305-2b859c00-bf1f-11eb-8466-b52a65214476.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
The calculation is solved in AC using the formula 20 yards at the same level + - 1 yard per creature level difference
Correctly the base at the same level should be scalable according to the creature type

I am attaching a video from blizz server where you can see that with a difference of 7lv where the player has more level
The aggro distance should be 11 yards
https://youtu.be/Jhk-U7AFhxU

https://youtu.be/Uk497yffb-Y

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1.  .tele deadmines
2.  Set the same level as in the video
3. Try the aggro distance
4. Creature will be aggroed much earlier than on the blizz server.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
c1e96064e9d8d1c7bcfe870fc5a47afbbd79e24c

**OPERATING SYSTEM:**
Ubuntu 20.04

**MODULES:**
none

**CUSTOMIZATIONS:**
none

**Comment by Krejza9** [comment]
I have already started working on rewriting the aggro distance from Vmangos to AC
https://github.com/Krejza9/azerothcore-wotlk/commit/2b7249f85dffd0dc1984ab1aaa567d9e036bda92

**Comment by T1ti** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5455
