### ISSUE TITLE
Booty Bay's Goblins NPCs near Dun Morogh sea cabin

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6083]
**CURRENT BEHAVIOUR:**

First time i see these npcs there, not even in previous versions of azerothcore they existed.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

That has always been an empty abandoned place within the category 'wow secrets' (like the river of elwynn that you cross in griffin, the Ironforge airport, the forest with mushrooms of Tirisfal, etc).

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to the location.
2. See if the npcs are there.

**EXTRA NOTES:**

![WoWScrnShot_052821_094349](https://user-images.githubusercontent.com/82579073/119942790-e56e1e00-bf9a-11eb-8cef-d37016797100.jpg)
![WoWScrnShot_052821_094410](https://user-images.githubusercontent.com/82579073/119942843-f28b0d00-bf9a-11eb-93f8-753a70320e3d.jpg)
![WoWScrnShot_052821_094419](https://user-images.githubusercontent.com/82579073/119942881-ff0f6580-bf9a-11eb-8df7-ed24ede8bb25.jpg)
![WoWScrnShot_052821_094451](https://user-images.githubusercontent.com/82579073/119942931-0afb2780-bf9b-11eb-901d-e2f12d7dbe89.jpg)
![WoWScrnShot_052821_094628](https://user-images.githubusercontent.com/82579073/119942987-1b130700-bf9b-11eb-9a24-08453eb44172.jpg)

Funny note, that 'Shelly' has a gnome voice.

**AC HASH/COMMIT:**
 

AzerothCore ea764812d14a

**OPERATING SYSTEM:**

Windows 10 20H2

**MODULES:**

No.

**CUSTOMIZATIONS:**

No.

**Comment by anguaive** [comment]
I think they're supposed to be there 

https://www.wowhead.com/npc=26081/high-admiral-shelly-jorrik

**Comment by Eldarix** [comment]
Wow !! fast and effective, you are ubiquitous in everything lately ^^

Thanks pal, I close it then !! (I'm pretty sure that in previous AC versions they weren't there, I imagine then that in this case they fixed it to be blizzlike and before it wasn't)

Have a nice weekend !!
