### ISSUE TITLE
Warlock Imp's Phase Shift is not canceled when it attacks

### ISSUE THREAD

**Issue by necropola** [azerothcore/azerothcore-wotlk#6085]
Original Report: https://github.com/chromiecraft/chromiecraft/issues/198 by @Trevis77

**Additional info by @necropola** 
It also happens on a  clean **enUS** client on stock AC at any level bracket and regardless of faction. 
Tested on AC hash/commit https://github.com/azerothcore/azerothcore-wotlk/commit/8ee35817e52163c09fcd739ef00900867fdef1c6

You can leave **Phase Shift** on auto and let your **Imp** attack a creature. Since **Phase Shift** isn't automatically canceled as it should (see below) or rather it's recast while in combat the creature immediately attacks the **Warlock** and not the **Imp**.

https://wowpedia.fandom.com/wiki/Phase_Shift_(imp_ability)?oldid=2366104
> If the Imp attacks another creature, Phase Shift is automatically cancelled; furthermore, it has a ten-second cooldown and cannot be cast while in combat. If you wish the Imp to stay phased, set it to Passive mode.

#### WHAT CLIENT DO YOU PLAY ON?
- [x] enGB
- [ ] enUS
- [ ] other (specify)

##### ISSUE: FACTION SIDE:
- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:
- [x] Generic
- [ ] 1-19
- [ ] 20-29

##### SMALL DESCRIPTION:
Spell: [[Phase Shift]](https://classic.wowhead.com/spell=4511/phase-shift)
The imp is still unattackable after it attacked.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The imp should be attackable after it attacked.

##### CURRENT BEHAVIOUR:
The imp is still unattackable after it attacked.

##### STEPS TO REPRODUCE THE PROBLEM:
Step 1 : Turn off Phase Shift auto-cast.
Step 2 : Make the imp manually attack a mob out of range.
Step 3 : While he is walking to get in range, use Phase Shift manually.
Step 4 : The imp can now cast Firebolts while staying unattackable.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Hmm I guess EnterCombat wasnt good enough
https://github.com/azerothcore/azerothcore-wotlk/commit/b48309484061ad520177491ee100444b31297ad2

**Comment by Kitzunu** [comment]
I think I found the actual cause of this, so we don't even need that creature script

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/6087 fixed, I found the root problem for the issue so now we wont need to script anymore =)

**Comment by necropola** [comment]
Maybe we need both. The script cancels the aura when entering combat (correct), but the Imp immediately recasts it which your patch will prevent. Curerntly compiling your PR. Lets see ..

**Comment by Kitzunu** [comment]
Nope it won't be needed. Because some smartass thought it was fun excluding permanent auras/spells from the CanBeUsedInCombat() check in PetAI... Which is wrong

**Comment by Kitzunu** [comment]
Which allowed you to recast it in combat

**Comment by necropola** [comment]
But what/who will cancel the aura on entering combat when the script is removed?

**Comment by Stifler82** [comment]
And Fixed! 😁
-
https://user-images.githubusercontent.com/1884642/119965723-7bf20d80-bfa2-11eb-8e06-dc605f2f5817.mp4

**Comment by Kitzunu** [comment]
CanBeUsedInCombat())

**Comment by Stifler82** [comment]
The problem was here:
![image](https://user-images.githubusercontent.com/1884642/119966105-e0ad6800-bfa2-11eb-94aa-2c5430a6e974.png)

**Comment by Kitzunu** [comment]
Well I guess you can see that as part of it, but it is not neccessary

**Comment by Kitzunu** [comment]
The actual problem was the PetAI itself who allowed spells with SPELL_ATTR0_CANT_USED_IN_COMBAT to be cast in combat

**Comment by Stifler82** [comment]
@Kitzunu 
It may be, but the logic was totally wrong.
Because how can the aura of "Phase Shift" (On Melee Attack) break, if the MOB is in "Phase Shift" mode (can't be hit)?

So (it makes more sense) that the IMP will remove the Phase Shift aura when casting begins, because: Casting = Start of combat.

**Comment by Stifler82** [comment]
@Kitzunu 
The spell already has that Flag
![image](https://user-images.githubusercontent.com/1884642/119967082-e6f01400-bfa3-11eb-8e26-49e88cea6482.png)

**Comment by Kitzunu** [comment]
I know, but Core handles it wrong

**Comment by Kitzunu** [comment]
look at my PR and you will understand what the faulty part of the core's handling was in PetAI.

But I don't mind if you make a PR to fix InterruptFlags as well

**Comment by Stifler82** [comment]
> I know, but Core handles it wrong

And then the rule must be removed from the CORE because it conflicts with the DBCs

**Comment by Kitzunu** [comment]
Look at my PR

**Comment by Stifler82** [comment]
> Look at my PR, I already did that

I've seen the PR, it sounds good.

Can we also include my Fix in your PR?

**Comment by Stifler82** [comment]
Can I edit your PR? (in the SQL Part)?

**Comment by necropola** [comment]
Tried your (original) PR with Phase Shift on auto and it only fixed it every other attempt. Sometimes the Imp was still/again shifted when attacking. There appears to be something (colldown related?) still mssing.

**Comment by Kitzunu** [comment]
So I am actually dumb, forget everything I said, my PR doesn't affect this issue but it is valid anyways.

But now when I test without any script the imp works as it should :shrug:

**Comment by Kitzunu** [comment]
> @Kitzunu
> Can I edit your PR? (in the SQL Part)?

make a new PR mines doesn't affect this

**Comment by Kitzunu** [comment]
No my PR has nothing to do with this

**Comment by Stifler82** [comment]
> No my PR has nothing to do with this

ok, ok..

**Comment by Kitzunu** [comment]
I can explain quickly why:

CanBeUsedInCombat() is called like this return !HasAttribute(SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL);

Which means it will never be called for PhaseShift as it has SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL

**Comment by Kitzunu** [comment]
Sorry for wasting your time xD I was so sure I found it.

I will go digging deeper into the PetAI to try and figure out where the logic is ass

**Comment by necropola** [comment]
Back on current master doing some more tests. The following additional findings might be useful:
- The bug (obviously) only occurs when **Phase Shift** is **not on cooldown**, i. e . you have to wait a bit (10 seconds) between attempts to reproduce it.
- When **Phase Shift** is on auto you can see that the **Imp** loses **Phase Shift** very briefly when commanded to attack but recasts it immediately.
- When you try to do this manually, you have **very little time** to enable **Phase Shift** before the Imp casting Fireballs will prevent it, i. e. you either get an **Another action is in progress* or **Your Pet is in combat** error.
- So the aura is canceled and can't be recast while in combat, but there appears to be a **small time frame** between canceling the aura and entering combat in which it can be recast. Which the Imp reliably manages to do with **Phase Shift** on auto (when it's not on CD of course).

Hope this helps.

**Comment by necropola** [comment]
@Stifler82 @Kitzunu Now that I took my PvE goggles off:
Doesn't this bug have huge abuse potential in PvP? I mean, I could put my Imp on aggressive, leave Fireballs and Phase Shift on auto and let him harrass other players without them being able to fight back?

This combined with #5113 (almost unfinite mana) is quite a combo.
