### ISSUE TITLE
[RAID] UBRS Rookery eggs are respawning FAST.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#609]
**Description**:  It's been a while, but these eggs seem to respawn a lot faster than I remember. They respawn fast enough that there is an endless supply of them to open. The party should be able to clear a good portion of the room and have a bit of time to perform other tasks before the eggs start to respawn. I am happy to report that the Leeeeeeroy achievement is working and gives the title.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by Gargarensis** [comment]
The respawn time currently set is 2 minutes, can you find some official videos or other sources to get what the correct time should be?

**Comment by StygianTheBest** [comment]
I looked but can't find anything to verify. 2 minutes seems about right. Gonna close this one and if any info arises will re-open.
