### ISSUE TITLE
Area Near Maraudon Portal Flagged As Underwater

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6093]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/719

We were in Maraudon outside the dungeon, going for the 3rd Khan, and somehow while walking on the ground  we entered an "underwater" zone where a breathing bar showed up.
It was on the way to the 3rd Khan, coming from Cavindra. Jump down and there should be the "underwater" zone.
Confirmed by multiple party members (but unfortunately in my haste I did not screenshot it).

Tester's notes: Confirmed. .go c 26947 will take you to a mob in the right area. There's water in the area, in small pools, but they're so shallow they shouldn't need underwater breathing anyway.

![WoWScrnShot_052921_020250](https://user-images.githubusercontent.com/81782124/120015317-5c9ac500-c022-11eb-8f78-1d9624162302.jpg)
![WoWScrnShot_052921_020320](https://user-images.githubusercontent.com/81782124/120015320-5dcbf200-c022-11eb-9eb6-f07a95ce5d1c.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There shouldn't be a breathing bar :).

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 26947
3. See the breathing bar

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by damnablebear** [comment]
Confirmed still an issue 8/25/2023 on Chromie's PTR. Using the .go c 26947 command easily shows the issue.
