### ISSUE TITLE
The Test of Righteousness (3)

### ISSUE THREAD

**Issue by cts17** [azerothcore/azerothcore-wotlk#6096]
**CURRENT BEHAVIOUR:**
Quest is auto-completed and able to be handed in without any RP.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Jordan Stilwell should actually craft your beautiful hammer on the anvil

**SOURCE:**
https://www.youtube.com/watch?v=Q8ZwKGah1LI&ab_channel=LilPerry1990LilPerry1990
https://wowwiki-archive.fandom.com/wiki/Quest:The_Test_of_Righteousness_(3)

**STEPS TO REPRODUCE THE PROBLEM:**

1. Complete Test of Righteousness
2. Watch Jordan Stillwell just stand there
3. cry for lack of RP

**EXTRA NOTES:**

**AC HASH/COMMIT:**
Chromiecraft live server
rev 3716ddf3e4e1

**Comment by Azcobu** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/7097
