### ISSUE TITLE
Pets/Guardians not getting catchup speed

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6098]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/716

##### CURRENT BEHAVIOUR:

The demons should get more movement speed the farther he is then the players,atm it has the same movement speed..usuly when a player jumps from a higher ground the pet walks back the path to follows him at the same speed but because the players still runs foward it may result in the demon being a very long way behind or in some cases desummoning(ofc depends on how high the jump is and how long the path back is ) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The demons should get a bonus movement speed when not in combat ofc and the player get at a certain distance(think 5-8 yards idk tbh :( ) and also the movement  bonus should stop when the player or the demon gets into combat 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get to the mage tower in SW ,on the top of the platform that leads to mage trainers
2.  Jump down and run to the trade distric in SW
3. the demon should run back the path and be with u by the time u get to the tailoring / herbalism trainer 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: ea76481):

![WoWScrnShot_052921_055311](https://user-images.githubusercontent.com/82579073/120056109-e5c1f400-c042-11eb-8823-4e0d891b5509.jpg)
![WoWScrnShot_052921_055345](https://user-images.githubusercontent.com/82579073/120056119-f2dee300-c042-11eb-8d28-d37c9d1ca92e.jpg)
![WoWScrnShot_052921_055408](https://user-images.githubusercontent.com/82579073/120056127-fecaa500-c042-11eb-826d-7c0f30998cd7.jpg)

It certainly takes longer to reach you than it should, the demon.

**Comment by francovilla** [comment]
I need data such as how many yrds the increase occurs and how much it is :)

**Comment by Toniculus** [comment]
> I need data such as how many yrds the increase occurs and how much it is :)

Always  as long as player or pet its not in combat (when entering in combat the movement should not continue) and i belive  its 20% movement increase or 30 %

**Comment by Toniculus** [comment]
> I need data such as how many yrds the increase occurs and how much it is :)

Always as long as player or pet its not in combat (when entering in combat the movement should not continue) and i belive the movement speed bonus its 30%

**Comment by Toniculus** [comment]
> > I need data such as how many yrds the increase occurs and how much it is :)
> 
> Always as long as player or pet its not in combat (when entering in combat the movement should not continue) and i belive the movement speed bonus its 30%

as it says in the patch 1.5.0 of vanilla wow
