### ISSUE TITLE
Pit of Saron

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#61]
Instance The Pit of Saron has the missing starting Npcs depending on faction even quest starters for factions (Jaina: Alliance; Sylvannas: Horde) Missing Scourgelord Tyranus Starting Event at the entrace of the Dungeon, and Boss Figthing Starting Event has missing spawns regarding Alliance or Horde Sides, and when Scourgelord Tyranus Dies, missing ending Event are not included
Best Regards

**Comment by ShinDarth** [comment]
Missing core rev, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
