### ISSUE TITLE
Intercept spell doesn't work if target is Immune

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#6110]
Original report: https://github.com/chromiecraft/chromiecraft/issues/728

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If target is Immune your intercept doesnt let u charge to the enemyplayer but still goes on CD.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You simply should charge in enemys face even tho he is immune and cant get stunned

##### STEPS TO REPRODUCE THE PROBLEM:

1. Pally --> bubble
2. Warrior --> Intercept on the bubbled Pally

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Can confirm on 8ee3581. 


https://user-images.githubusercontent.com/39011611/120070312-1e38f080-c08a-11eb-9103-7d2704cdbb51.mp4

**Comment by Dexra** [comment]
thanks for testing !

**Comment by ErnestoGonzalezC** [comment]
This is casued by (SPELL_ATTR0_NO_ACTIVE_DEFENSE)

**Comment by anguaive** [comment]
> This is casued by (SPELL_ATTR0_NO_ACTIVE_DEFENSE). Here #6421

This issue was opened before #6421. Or do you mean #6421 also fixed this?
