### ISSUE TITLE
Port Belfry Bats spawns and event from vmangos

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#6126]
**CURRENT BEHAVIOUR:**

There is no belfry bat spawn

**EXPECTED BLIZZLIKE BEHAVIOUR:**

https://classic.wowhead.com/npc=10716/belfry-bat#comments

12 of these bats spawn on top of Brill's clocktower at the same time as the tower's bell starts tolling (every hour at XX:00). The bell startles them, and they fly away, playing sound 
BatsInFlight. They fly in the direction of the zeppelin tower, play the sound again mid-path, and land on the roof of that small building at the base of the tower. After most of them land, they play the sound yet again and despawn

Commit from vmangos(based on sniffs)

https://github.com/vmangos/core/commit/373845acac72dad03cf25c8ce587ee675a0bdd64

**SOURCE:**

credits to vmangos

**STEPS TO REPRODUCE THE PROBLEM:**

1. 
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
a9ed64e60011c53786f611f11028d8a9f7ff0048

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by schell244** [comment]
The sniffed bat creature guids are currenlty used in azerothcore database for some custom creature spawns. First step would be to free those guids (and respawn the custom creature spawns with their correct guid).
```sql
DELETE FROM `creature` WHERE `guid`=8493; -- Mill Worker
DELETE FROM `creature` WHERE `guid`=8494; -- Mill Worker
DELETE FROM `creature` WHERE `guid`=8495; -- Foreman Tionn
DELETE FROM `creature` WHERE `guid`=8496; -- Mill Worker
DELETE FROM `creature` WHERE `guid`=8497; -- Mill Worker
DELETE FROM `creature` WHERE `guid`=8498; -- Mill Worker
DELETE FROM `creature` WHERE `guid`=8499; -- Mill Worker
DELETE FROM `creature` WHERE `guid`=8500; -- Scorchscale Drake
DELETE FROM `creature` WHERE `guid`=8501; -- Scorchscale Drake
DELETE FROM `creature` WHERE `guid`=8502; -- Scorchscale Drake
DELETE FROM `creature` WHERE `guid`=8503; -- Mudsprocket Bruiser
DELETE FROM `creature` WHERE `guid`=8504; -- Mudsprocket Bruiser
```

**Comment by Nyeriah** [comment]
GUIDS are not sniffed, they're entirely server side and chosen based on whatever entry is unused. Clearing those mobs is not required, just choose another batch of free GUIDs to spawn the bats.

**Comment by schell244** [comment]
I thought VMangos was catching/using GUIDS from sniffs as well, but I'm not too deep into that. I try to port it with a set of different GUIDS then 👍

**Comment by acidmanifesto** [comment]
> I thought VMangos was catching/using GUIDS from sniffs as well, but I'm not too deep into that. I try to port it with a set of different GUIDS then 👍

Just further information on guids and sniffing. Guids are never the same, and show different to individual players and change up as well with each login with retail. It is the main culprit in why we get dupes at times when they are parsed into the db.
