### ISSUE TITLE
Mage Talent 'Fiery Payback' Activating When Not Specced

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6127]
**CURRENT BEHAVIOUR:**

The 35 point mage fire tree talent Fiery Payback (https://wotlkdb.com/?spell=64353, https://wotlkdb.com/?spell=64357) has a 5%/10% chance to disarm an attacker's main hand and ranged weapons. Right now it is proccing even when not actually equipped.

No talents equipped on mage, and 0/2 on Fiery Payback:
![WoWScrnShot_053021_155306](https://user-images.githubusercontent.com/81782124/120095223-e9996780-c163-11eb-89e0-f4460d04ec71.jpg)

Enemy warr shooting procs FP anyway:
![WoWScrnShot_053021_160513](https://user-images.githubusercontent.com/81782124/120095538-b3f57e00-c165-11eb-850d-d3b0b515f589.jpg)

Melee:
![WoWScrnShot_053021_160250](https://user-images.githubusercontent.com/81782124/120095546-bd7ee600-c165-11eb-9afd-a15368073092.jpg)

Thrown:
![WoWScrnShot_053021_155247](https://user-images.githubusercontent.com/81782124/120095640-1f3f5000-c166-11eb-8dde-8f91ea2fdd98.jpg)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Talents should not activate unless they have points put into them.

**SOURCE:**

This is not controversial.

**STEPS TO REPRODUCE THE PROBLEM:**

1. Have a lvl 45+ mage. I tested on both a lvl 80 and a lvl 45 and it worked on both. I'm deriving lvl45 from the fact it's a 35 point talent.
2. Get into PVP with another character.
3. Have that character attack and wait for the 10% proc to go off.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
rev. a9ed64e60011 2021-05-30 03:46:04 +0200

**OPERATING SYSTEM:**

Linux Mint 20.1

**MODULES:**

N/A.

**CUSTOMIZATIONS:**

N/A.

**Comment by UltraNix** [comment]
@Azcobu Got only one spec? Maybe you added/removed that talent recently?

**Comment by Azcobu** [comment]
The mage I was testing on was a brand-new character I'd actually made to check something else (I don't remember what, it was a while ago.) But while testing I noticed this as well, so filed it as another report. He would have had only one spec, and no talents points spent or equipped at all. (As you can see from the first screenshot, where it shows 71 talent points free.) I hadn't added and then removed the talent, because I hadn't ever spent any talent points - he was mostly there as a target dummy.

**Comment by UltraNix** [comment]
I cannot reproduce it on my local anyway.

**Comment by Azcobu** [comment]
Yep, brand new 80, no talents spent.

Just tried it again with 2 different characters and reproduced it:

Lvl 80 mage, no talents, cheats off so he could take damage:
![WoWScrnShot_072721_215910](https://user-images.githubusercontent.com/81782124/127153843-490821ec-6fa1-428f-8dbe-acd42c96513a.jpg)

Lvl 1 hunter plinking away with autoshot:
![WoWScrnShot_072721_215858](https://user-images.githubusercontent.com/81782124/127153991-7f16dcb0-732f-41d1-bb8f-1f80e2f782cf.jpg)
![WoWScrnShot_072721_220318](https://user-images.githubusercontent.com/81782124/127154366-f85998a5-91bc-4502-b1b4-5fc95ca6070c.jpg)

This was in the Gurubashi Arena, don't know if that makes a difference.

**Comment by UltraNix** [comment]
Have you used `.learn all my class` command?

**Comment by Azcobu** [comment]
I usually use `learn all my spells` when setting up a test character rather than `class` but can't rule it out. I'll test again with a mage who hasn't used either.

**Comment by UltraNix** [comment]
That's why it is bugged. Do not use it.

**Comment by Azcobu** [comment]
Yep, testing with a character who hasn't used either doesn't proc Payback. Cheers for the info, closing this accordingly.
