### ISSUE TITLE
OSX + Docker Desktop, ./acore.sh docker dev:build produces "clang: error: unable to execute command: Killed"

### ISSUE THREAD

**Issue by suprsokr** [azerothcore/azerothcore-wotlk#6130]
**CURRENT BEHAVIOUR:**
Running `./acore.sh docker dev:build` OSX with Docker Desktop produces the following error:

```
...
[100%] Linking CXX executable worldserver
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:227: src/server/worldserver/worldserver] Error 254
make[1]: *** [CMakeFiles/Makefile2:1160: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

real	61m36.996s
user	6m38.412s
sys	14m12.481s
ERROR: 2
error: Uncaught (in promise) Error: Failed with error: 2, however,
            it's not related to this Deno script directly. An error occurred within
            the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///Users/lappy/dev/acore/apps/docker/docker-cmd.ts:290:17)
    at async Promise.all (index 0)
    at async file:///Users/lappy/dev/acore/apps/docker/docker-cmd.ts:240:5
```

**EXPECTED BEHAVIOUR:**
No error should occur, and compiling should complete successfully.

**STEPS TO REPRODUCE THE PROBLEM:**
11.4 OSX
Docker version 20.10.6, build 370c289

Follow https://www.azerothcore.org/wiki/Install-with-Docker, complete step 2 under installation, and then run `./acore.sh docker dev:build`

**AC HASH/COMMIT:**
a9ed64e60011c53786f611f11028d8a9f7ff0048

**OPERATING SYSTEM:**
11.4 OSX

**MODULES:**
No.

**CUSTOMIZATIONS:**
No.

**Comment by suprsokr** [comment]
Solution:

Increase memory from 2gb default to something higher by using the Docker Desktop interface, instructions [here](https://docs.docker.com/docker-for-mac/#:~:text=Memory%3A%20By%20default%2C%20Docker%20Desktop,swap%20file%20size%20as%20needed.).

**Comment by FrancescoBorzi** [comment]
@suprsokr thanks for sharing the solution, however it would be nice if you could post this Question & Answer on StackOverflow, so we have documented there:

https://stackoverflow.com/questions/tagged/azerothcore

in case you're wondering:

https://stackoverflow.com/help/self-answer

https://stackoverflow.blog/2011/07/01/its-ok-to-ask-and-answer-your-own-questions/
