### ISSUE TITLE
Docker: Deno reinstalls constantly

### ISSUE THREAD

**Issue by suprsokr** [azerothcore/azerothcore-wotlk#6131]
**CURRENT BEHAVIOUR:**
Deno is constantly reinstalling itself when running almost any Docker command.

Example: `./acore.sh docker start:app`
```
NOTICE: file <.../dev/acore/conf/config.sh> has not been found, you should create and configure it.
**Deno version check:
.../dev/acore/apps/bash_shared/deno.sh: line 18: ./deps/deno/bin/deno: cannot execute binary file: Exec format error
Installing Deno...
######################################################################## 100.0%
Archive:  .../dev/acore/deps/deno/bin/deno.zip
  inflating: .../dev/acore/deps/deno/bin/deno
Deno was installed successfully to .../dev/acore/deps/deno/bin/deno
Run 'deno --help' to get started**
>>>>> Running: docker-compose run --rm ac-dev-server bash acore.sh compiler build
Creating acore_ac-dev-server_run ... done
**Deno version check:
/azerothcore/apps/bash_shared/deno.sh: line 18: ./deps/deno/bin/deno: cannot execute binary file: Exec format error
Installing Deno...
######################################################################## 100.0% #=#=-#   #
Archive:  /azerothcore/deps/deno/bin/deno.zip
  inflating: /azerothcore/deps/deno/bin/deno
Deno was installed successfully to /azerothcore/deps/deno/bin/deno
Manually add the directory to your $HOME/.bash_profile (or similar)
  export DENO_INSTALL="/azerothcore/deps/deno"
  export PATH="$DENO_INSTALL/bin:$PATH"**
Run '/azerothcore/deps/deno/bin/deno --help' to get started
**Deno version check:
Checking https://github.com/denoland/deno/releases/download/v1.9.1/deno-x86_64-unknown-linux-gnu.zip
30.1 MiB / 30.1 MiB (100.0%)
Deno is upgrading to version 1.9.1
Archive:  /tmp/.tmpvejBW6/deno.zip
  inflating: deno
Upgraded successfully**
Running hooks: HOOKS_MAP_ON_AFTER_OPTIONS
...
```
"Deno version check" ran and installed Deno three times before compiling even started!

Another example: `./acore.sh docker start:app` installs Deno on world server and auth server. 

**EXPECTED BLIZZLIKE BEHAVIOUR:**
A Deno version should be packaged with the app, just like every other dependency in the project.

**STEPS TO REPRODUCE THE PROBLEM:**
1. Fresh Docker install following these instructions: https://www.azerothcore.org/wiki/Install-with-Docker#installation
2. Run commands `./acore.sh docker dev:build` or `./acore.sh docker start:app`

**AC HASH/COMMIT:**
a9ed64e60011c53786f611f11028d8a9f7ff0048

**OPERATING SYSTEM:**
OSX 11.4

**MODULES:**
None

**CUSTOMIZATIONS:**
None

**Comment by suprsokr** [comment]
cc @Yehonal

**Comment by Yehonal** [comment]
Please try to rebuild your docker image. This commit should have fixed this issue: https://github.com/azerothcore/azerothcore-wotlk/commit/e564994b37e0c0c88d020d1e32d3c8077b957ebe#diff-57d46ee46504455dc66eeb243f1c2c55ee061c7a0b39eb126a78b239e7af7639

Can anyone else confirm it?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/c43e1b8c0c3a17e48f1559bdfe13018aaab5008a
