### ISSUE TITLE
[RAID] UBRS Finkle Einhorn is not released after skinning The Beast

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#614]
**Description**:  Finkle Einhorn is standing at the far back of the area where The Beast is located. There are two orcs near him that never engage the player until approached. He should not appear until The Beast is skinned by a player.

**Expected**:
> Finkle Einhorn is a gnomish inventor and explorer. As a level 60 elite quest giver was found at The Furnace in Upper Blackrock Spire within The Beast's stomach and was released when The Beast was killed and skinned.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by BarbzYHOOL** [comment]
UBRS seems like the worst instance actually lol

**Comment by StygianTheBest** [comment]
@BarbzYHOOL To be fair, it had bugs in retail, but none like the ones I've listed. Same with Blackwing Lair. I've ran through that one too and have a bunch of bugs in my log book I'll post once I make my second attempt. I always run things 2-3 times before posting the bugs.

**Comment by Gargarensis** [comment]
The worst instances are BRD, BRS, ZA, Karazhan, HS and all the vanilla raids since they were not rewritten by the original Sunwell's team.

**Comment by StygianTheBest** [comment]
@Gargarensis The upshot is they can all be completed despite some broken events and other small nuances.
