### ISSUE TITLE
CRASH C0000005 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by AndrewQ91** [azerothcore/azerothcore-wotlk#6145]
**CURRENT BEHAVIOUR:**

[7f90f41ba6e3+_worldserver.exe_[31-5_13-2-19].txt](https://github.com/azerothcore/azerothcore-wotlk/files/6567894/7f90f41ba6e3%2B_worldserver.exe_.31-5_13-2-19.txt)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Not crash? attack quilboar as normal

**SOURCE:**
whenever I attack the quilboars in durotar, and other random spots

**STEPS TO REPRODUCE THE PROBLEM:**
whenever I attack the quilboars in durotar, and other random spots

**OPERATING SYSTEM:**
Windows 10

Commit 7f90f41ba6e3

**MODULES:**
AHbot
Anticheat
CFBG
Eluna lua
transmog
Weapon visual
weekend XP

**CUSTOMIZATIONS:**
Classless system Astoriacore

**Comment by Kitzunu** [comment]
Upload the crash to pastebin or gist, I will not download anything.

**Comment by AndrewQ91** [comment]
gistfile1.txt

**Comment by AndrewQ91** [comment]
https://gist.githubusercontent.com/AndrewQ91/acc59204a1a75f977d818cf7be7192eb/raw/c2456fd1756b022105fb3dd6bcf82dee1c0f2755/gistfile1.txt

**Comment by Kitzunu** [comment]
Can you test this on a clean AC?

**Comment by Helias** [comment]
the crashdump shows something related to `switch (cleanDamage->attackType)` in `Unit.cpp line 812`

**Comment by AndrewQ91** [comment]
https://gist.github.com/AndrewQ91/e7006e4b3fc9be3727fe407ca48eaca7

This is my Unit.cpp code... I did edit the rage generation fyi

**Comment by Kitzunu** [comment]
I cant see how it would crash in the switch statement as all variables are null checked as well.

But it needs to be tested on a clean install of AC.

**Comment by Viste** [comment]
Ah boys, you're clinging to line numbers instead of thinking.
@FrancescoBorzi 
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp#L719
change to 
```
uint32 rage_damage = damage + ((cleanDamage != 0) ? cleanDamage->absorbed_damage : 0);
```
or (but first better i think)
```
uint32 rage_damage = damage + (cleanDamage ? cleanDamage->absorbed_damage : 0);
```

nullptr in this case generate ACCESS_VIOLATION @AndrewQ91 try plz

**Comment by Kitzunu** [comment]
Ah cool 👍

**Comment by Viste** [comment]
> Ah cool +1

Нет. Это вообще не круто. Это полная хуйня. Надо иногда думать, а не менять NULL -> nullptr автозаменой.

**Comment by Kitzunu** [comment]
You know I dont speak Russian D:

**Comment by Viste** [comment]
> You know I dont speak Russian D:

Yes, I know, but I'm too lazy to think how to translate it properly into English. So you can ask Winfi for a translation

**Comment by Kitzunu** [comment]
hahahaha, Nice xD

**Comment by lineagedr** [comment]
> https://gist.github.com/AndrewQ91/acc59204a1a75f977d818cf7be7192eb

Line: 808 you using the OR operator is causing the crash.

```
if (attacker && cleanDamage && damagetype == DIRECT_DAMAGE && attacker != victim && attacker->getPowerType() == POWER_RAGE || attacker != victim && victim->getPowerType() == POWER_MANA)
```

After the OR operator You're not checking if cleanDamage is valid.

```
|| attacker != victim && victim->getPowerType() == POWER_MANA)
```

**Comment by AndrewQ91** [comment]
He guys, Thanks for all the feedback and the help.

I resolved the issue, it was due to the damage and power generation... I'm running a custom class system and needed to generate rage, and wrote the code wrong, here is the fix.

(attacker && cleanDamage && damagetype == DIRECT_DAMAGE && attacker != victim && attacker->getPowerType() == POWER_RAGE || attacker && cleanDamage && damagetype == DIRECT_DAMAGE && != victim && victim->getPowerType() == POWER_MANA)
