### ISSUE TITLE
server list issue

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6149]
**CURRENT BEHAVIOUR:**
Unable to select server list after logging in to server
![image](https://user-images.githubusercontent.com/18187177/120162434-f46aff80-c22a-11eb-9cae-1b6446694730.png)

**STEPS TO REPRODUCE THE PROBLEM:**

1. login your server
2. "change realmd"
![image](https://user-images.githubusercontent.com/18187177/120162616-25e3cb00-c22b-11eb-99cc-6f73681e4666.png)

**EXTRA NOTES:**
https://github.com/azerothcore/azerothcore-wotlk/issues/5921
https://github.com/azerothcore/azerothcore-wotlk/issues/6132

**AC HASH/COMMIT:**
8ee35817e52163c09fcd739ef00900867fdef1c6

**OPERATING SYSTEM:**
ubuntu20.04
**MODULES:**
none

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan

**Comment by poryagholami1374** [comment]
I did not understand you
That is, when you want to select another server
Nothing comes
I ran the server
But there is no such thing as a problem

**Comment by mpfans** [comment]
updated to d72375c4ebe8ba132ec81ec87baeb71c3cf13ff7

issue solved
