### ISSUE TITLE
[sChinese translate]Gems & Glyphs

### ISSUE THREAD

**Issue by Remberance** [azerothcore/azerothcore-wotlk#6150]
**CURRENT BEHAVIOUR:**
many Gems and Glyphs simple Chinese name&color&description wrong.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**
see appendix.

**STEPS TO REPRODUCE THE PROBLEM:**

1. use zhCN Client, apply SQL,
2. restart or reload item_template_local
3. relog

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

[gems&glyphs.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6569132/gems.glyphs.txt)

**Comment by mpfans** [comment]
The problems mentioned in the attachment are not found

![image](https://user-images.githubusercontent.com/18187177/120175888-3e5ae200-c239-11eb-93a3-a6b12db49ff4.png)
![image](https://user-images.githubusercontent.com/18187177/120175928-49ae0d80-c239-11eb-8f82-a900b4a91100.png)

No need to fix

**Comment by Sedatyf** [comment]
Thank you @mpfans

**Comment by Remberance** [comment]
> The problems mentioned in the attachment are not found
> 
> ![image](https://user-images.githubusercontent.com/18187177/120175888-3e5ae200-c239-11eb-93a3-a6b12db49ff4.png)
> 
> Did not execute SQL, query the current data
> ![image](https://user-images.githubusercontent.com/18187177/120175928-49ae0d80-c239-11eb-8f82-a900b4a91100.png)
> 
> No need to fix

i just check this before 15/3/2021, not check it one by one, because i'm poor in CODE, so if you can, plz help me check this which are no need to fix.

**Comment by mpfans** [comment]
> > The problems mentioned in the attachment are not found
> > ![image](https://user-images.githubusercontent.com/18187177/120175888-3e5ae200-c239-11eb-93a3-a6b12db49ff4.png)
> > Did not execute SQL, query the current data
> > ![image](https://user-images.githubusercontent.com/18187177/120175928-49ae0d80-c239-11eb-8f82-a900b4a91100.png)
> > No need to fix
> 
> i just check this before 15/3/2021, not check it one by one, because i'm poor in CODE, so if you can, plz help me check this which are no need to fix.

You can upgrade to the latest code for testing
