### ISSUE TITLE
Silverpine Forest - Rot Hide Plague Weavers not attacking

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#6155]
Original report: https://github.com/chromiecraft/chromiecraft/issues/748

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After casting Curse of Thule and Posion Cloud, Rot Hide Plague Weavers do not attack the player and instead just stand around awkwardly. They only attack if the target is in melee range.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should try to stay in melee range and use melee attacks when not casting spells.

##### SOURCE:

https://classic.wowhead.com/npc=1940/rot-hide-plague-weaver
https://www.youtube.com/watch?v=zg3Kx3kbbGI&t=285s

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.tele Fenris`
2. Get into a fight with Plague Weavers and stay out of melee range

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by anguaive** [comment]
Can confirm on 8ee3581.

![WoWScrnShot_053121_131835](https://user-images.githubusercontent.com/39011611/120187872-ad264400-c215-11eb-92b4-e21c3d46f068.jpg)

**Comment by vtihomirov** [comment]
Here a video source of the Rot Hide plague weavers: https://www.youtube.com/watch?v=wp2-ryEEJG0.

**Comment by benjymansy123** [comment]
Can confirm, issue still occuring as of https://github.com/chromiecraft/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273
