### ISSUE TITLE
Problem npc dalaran

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6162]
### CURRENT BEHAVIOUR:
When I walk here
It throws me up
That npc that my target has a problem with

### SOURCE:

https://user-images.githubusercontent.com/80007195/120217977-5ab54980-c24e-11eb-94da-dfaff74d3d50.mp4

### STEPS TO REPRODUCE THE PROBLEM:

.go 5782.738770 696.853271 619.276978

### AC HASH/COMMIT:
rev. 40f2e5e+ 2021-05-09 03:33:01

### OPERATING SYSTEM:
Windows Server 2019 Standard

### MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by Stump876** [comment]
I couldn't get that one to work, but this is something I've noticed as well on several servers running AC, and on my local test server. It does the same thing if you walk passed them into the pet relief area next to it, also in the sewer pipe- but only if you're mounted. Those 2 areas are the same guard doing the porting. I tagged her with a skull.

You can also split the guards and get into the alliance Inn if you're mounted and jump into the doorway. 

https://user-images.githubusercontent.com/68164076/120224015-6de8fa80-c1f7-11eb-88c0-6b20b7dea2d2.mp4


https://user-images.githubusercontent.com/68164076/120224037-7a6d5300-c1f7-11eb-9731-3e3bc6af9a55.mp4


https://user-images.githubusercontent.com/68164076/120224300-1008e280-c1f8-11eb-8f47-f25cb183d66b.mp4

**Comment by poryagholami1374** [comment]
> I couldn't get that one to work, but this is something I've noticed as well on several servers running AC, and on my local test server. It does the same thing if you walk passed them into the pet relief area next to it, also in the sewer pipe- but only if you're mounted. Those 2 areas are the same guard doing the porting. I tagged her with a skull. GUID 102392
> 
> You can also split the guards and get into the alliance Inn if you're mounted and jump into the doorway.
> 
>  Pet.relief.mp4 
>  Pipe.mp4 
>  Alliance.inn.mp4

Going to an alliance is different
That I said is for everyone
It should not get stuck

**Comment by poryagholami1374** [comment]
I updated the source and tested it, it does not have this problem, so
I will close this post
