### ISSUE TITLE
[WORLD] some enemies npc don't attack

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#617]
**Description**: Some enemies npc on the world don't attack when i'm attacking them.

**Current behaviour**: All kinds of monsters are concerned. It's totally random. When I attack certain eniemies either for quests or to farmer some do not react when I attack them. Their life goes up on their own if I do not kill them quickly.

**Expected behaviour**: Instead, these monsters must attack when we attack them

**Steps to reproduce the problem**:

1. attack enemies (as in the zone of departure of the undead, by dint of killing (+ - 5min of game) one can see from time to time zombies that does not attack when we attack them. This can happen even after a revive of the monsters already killed)

2. attack enemies (in another area, when I'm at the entrance to a cave but outside some monster refuses to get out of the cave after I attacked them)

3. attack enemies

**Branch(es)**: 1.x / AzerothCore  2017-09-10 19:57:43 +0200 (master branch) (Unix, Release)

**AC hash/commit**:  2aedf1359377

**Operating system**:  Ubuntu Server 16.04.3 LTS (4.4.0-93-generic)

**Modules**:  no custom modules, just default module present on the source of core

**Other Customizations**: no custom, just default on the source of core

**Comment by ShinDarth** [comment]
missing `AC hash/commit:`

**Comment by Maurowin** [comment]
Where i found it?

**Comment by StygianTheBest** [comment]
Make sure GM mode is not enabled.

**Comment by Maurowin** [comment]
no GM mode enabled. it's player account with no grant access any commands.

I just reproduced the bug always the same way. I attacked a wolf without any reaction from him as if I was in GM but without being.

**Comment by StygianTheBest** [comment]
What zone? What creature ID?

**Comment by Maurowin** [comment]
Creature entry : 1508

But it is a deeper problem I think because it is not restricted to a monster but to all the monsters. It's totally random.

**Comment by Gargarensis** [comment]
Were you in a place where the monster could not reach you? The monsters will behave exactly in the way you descripted if they cannot reach you while you attack them.

**Comment by Maurowin** [comment]
No, just in front the enter.

**Comment by Maurowin** [comment]
They are stuck, they target me but they can't run.

**Comment by Dilemmast** [comment]
in latest branch can't confirm this bug.
@ShinDarth close this
