### ISSUE TITLE
[SERVER] The GOSSIP_ICON_DOT causes gossip menu options to go out of whack.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#618]
**Description**:  If I use several GOSSIP_ICON_DOT (10) icons for gossip menu items it will cause the submenus to use icons from the main menu instead of the dots. I've tried this using other icons and it works fine, but if I use the dots the behavior occurs. I have tried using both the definition and the number with the same effect.

Here's what both menus look like only changing the icon reference.
https://imgur.com/a/PTNoX

Here's a snip of the menu code. As in the image example, when this submenu is called and the first two icons will be icons used in the main menu instead of the icons I've set here. If I change the 10 to a 6 the icons work as intended as seen in the image. Seems to be a bug.

>
			player->ADD_GOSSIP_ITEM(7, "Back..", GOSSIP_SENDER_MAIN, 50);
			player->ADD_GOSSIP_ITEM(4, "Previous..", GOSSIP_SENDER_MAIN, 51);
			player->ADD_GOSSIP_ITEM(10, "Owl", GOSSIP_SENDER_MAIN, 140);
			player->ADD_GOSSIP_ITEM(10, "Raptor", GOSSIP_SENDER_MAIN, 15);
			player->ADD_GOSSIP_ITEM(10, "Ravager", GOSSIP_SENDER_MAIN, 16);
			player->ADD_GOSSIP_ITEM(10, "Scorpid", GOSSIP_SENDER_MAIN, 17);
			player->ADD_GOSSIP_ITEM(10, "Serpent", GOSSIP_SENDER_MAIN, 18);
			player->ADD_GOSSIP_ITEM(10, "Spider", GOSSIP_SENDER_MAIN, 19);
			player->ADD_GOSSIP_ITEM(10, "Strider", GOSSIP_SENDER_MAIN, 20);
			player->ADD_GOSSIP_ITEM(10, "Turtle", GOSSIP_SENDER_MAIN, 21);
			player->ADD_GOSSIP_ITEM(10, "Wasp", GOSSIP_SENDER_MAIN, 22);

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by ShinDarth** [comment]
shouldn't this stuff be handled with SmartAI ?

**Comment by Rochet2** [comment]
Commonly known client bug. Never heard or seen anyone claim different.
Fix would be to edit client that we cant do.

**Comment by StygianTheBest** [comment]
@Rochet2 Thanks for the info. Closing this one.
