### ISSUE TITLE
Too fast respawn of Peacebloom in Elwynn

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6181]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/757

##### CURRENT BEHAVIOUR:

A Peaceobloom node in Elwynn Forest is respawning in exact same spot every 1 min.
![WoWScrnShot_060121_155114](https://user-images.githubusercontent.com/7814954/120335628-eaf89a80-c2f1-11eb-903d-a1bdf4497ed3.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not really sure, but as far as I know, nodes shouldn't respawn in the same location and definetly not every minute.

##### STEPS TO REPRODUCE THE PROBLEM:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: beb4df9d3ef1):

![WoWScrnShot_060221_051706](https://user-images.githubusercontent.com/82579073/120414514-c557a980-c362-11eb-911f-3b53218d6391.jpg)
![WoWScrnShot_060221_051715](https://user-images.githubusercontent.com/82579073/120414554-d4d6f280-c362-11eb-88b2-6a503fad0336.jpg)

**Comment by necropola** [comment]
@syssneck This is kinda weird. The Peacebloom with `guid=26813` and `id=1618` is a member of `pool _entry = 993` in `pool_gameobject`.
The only Peacebloom (`1618` and `3724`) spawns I found which are not in a pool are:
```SQL
select s.guid, s.id, s.spawntimesecs, p.pool_entry, p.chance, p.description from gameobject s left join pool_gameobject p on s.guid = p.guid where s.id in (1618, 3724) and p.pool_entry is null;
+-------+------+---------------+------------+--------+-------------+
| guid  | id   | spawntimesecs | pool_entry | chance | description |
+-------+------+---------------+------------+--------+-------------+
|  1371 | 1618 |           900 |       NULL |   NULL | NULL        |
| 13545 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13546 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13547 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13549 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13550 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13551 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13552 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13553 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13554 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13555 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13556 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13557 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13558 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13560 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13561 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13562 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13563 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13564 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13565 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13566 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13567 | 3724 |           900 |       NULL |   NULL | NULL        |
| 13568 | 3724 |           900 |       NULL |   NULL | NULL        |
| 63421 | 3724 |           900 |       NULL |   NULL | NULL        |
| 63422 | 3724 |           900 |       NULL |   NULL | NULL        |
| 86351 | 3724 |          3600 |       NULL |   NULL | NULL        |
| 86352 | 3724 |          3600 |       NULL |   NULL | NULL        |
| 86353 | 3724 |          3600 |       NULL |   NULL | NULL        |
| 86354 | 3724 |          3600 |       NULL |   NULL | NULL        |
| 86355 | 3724 |          3600 |       NULL |   NULL | NULL        |
| 87484 | 3724 |          3600 |       NULL |   NULL | NULL        |
+-------+------+---------------+------------+--------+-------------+
31 rows in set (0.016 sec)

```

**Comment by syssneck** [comment]
Hi, I was able to pick up this specific peacebloom (guid=26813) up to 6 times in a row with respawn times of less than three seconds in between (local AC, 2x speed).

https://user-images.githubusercontent.com/68868567/126162314-697801c8-28f1-485b-b796-2972973f7161.mp4

**Comment by necropola** [comment]
Not sure where the pool `max_limit` applies to. Total number of spawns or spawsn per type (id).
There are 47 Peaceblloms (1618) in the pool and 82 Silverleaf (1617) and ...

**Comment by necropola** [comment]
@syssneck And then I remembered what sometimes takes place in the area around this herb spawn.
```SQL
 select s.guid, s.eventEntry, e.description
 from game_event_gameobject s inner join game_event e
 on e.eventEntry = abs(s.eventEntry)
 where s.guid=26813;
+-------+------------+--------------------------------+
| guid  | eventEntry | description                    |
+-------+------------+--------------------------------+
| 26813 |         -4 | Darkmoon Faire (Elwynn Forest) |
+-------+------------+--------------------------------+
```
A negative `eventEntry` value in `game_event_gameobject` means that the gameobject is supposed to be despawned during the event. And I conclude that this also means that it is **spawned** when the event is **not active**, like at the moment.

Which does still not explain, why it does not occur on CC anymore, but I now have a working theory why it might be respawned every 60 seconds on our local AC servers.
