### ISSUE TITLE
Core/Spell: Blink

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#619]
**Description**: A micro fall occurs whenever blink is used.

**Current behaviour**: Tell us what happens
With each use of the spell Blink, the character undergoes a micro fall at the end of the teleportation

**Expected behaviour**: Tell us what should happen instead
We should normally teleport to the ground

**Steps to reproduce the problem**:

1. Create Mage
2. Use blink
3. And see a micro fall

**Branch(es)**: Master

**AC hash/commit**:  2aedf1359377

**Operating system**:  Ubuntu server 10.04.3

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by GeForceBG** [comment]
@Maurowin Caused by https://github.com/azerothcore/azerothcore-wotlk/commit/fea7cc7775e4bce5aa9a6e304a0b18bad381916a

**Comment by Maurowin** [comment]
it will be fix next release or something else?

**Comment by ShinDarth** [comment]
@Maurowin this project is led by the community. Everyone is free to work on what the would like. We help each other in learning how to work on WoW emulation while helping each other. So feel free to work on that feature so your work can be included in the next release!

**Comment by Maurowin** [comment]
Up

**Comment by FrancescoBorzi** [comment]
@kvipka can you please have a look at this?

**Comment by Si1ker** [comment]
Tested 100 times in different maps [Spell 1953], there is no problem with it. If you meant the 0.1 seconds ""fall"", is because the spell teleports the player to a 1 pixel above after the max distance is reached. Nothing to be worried about ._.
