### ISSUE TITLE
Feature: Vip Account

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6194]
## Describe your feature request or suggestion in detail

It can be said that this is a money bank
With this module, they can buy donuts through the site and
Activate
And they also pay for it
It also has a significant effect on the development of players

https://github.com/mangosxx/trinitycore-patches/blob/master/TrinityCore/11222-VIP-Accounts.patch

You must convert this file to a module
And new features will be added to it, including chat with golden color
Rate xp honor
Rate Xp work
Rate Xp Reputiton
Eliminate saves
Use the command to be teleported to Dalaran

## Default
```
1 - (Rate.XP.Kill.Premium )
1 - (Rate.XP.Quest.Premium )
1 - (Rate.XP.Explore)
```

## Premium               
```
Rate.XP.Kill.Premium    - 15
Rate.XP.Quest.Premium   - 15
Rate.XP.Explore.Premium - 3
Rate.Reputation.Premium - 5
Rate.Honor.Premium      - 4
Rate.work.Premium       - 4
```

## Premium command
``.home``: Teleport To dalaran
``.i``: you all Delete Save instance
``.repair``: repair item

**Comment by function87** [comment]
Very good suggestion, but i have already developed the same things with Eluna, and much more.

**Comment by Winfidonarleyan** [comment]
Just make module for this

**Comment by poryagholami1374** [comment]
> Just make module for this

Many things may be added to the sentence
Rate Xp Druop item
Rate Xp Druop gold
And ...
The source itself has this
But this is for special accounts
They have to pay

**Comment by Kitzunu** [comment]
There is a VIP/Premium module already

**Comment by poryagholami1374** [comment]
> There is a VIP/Premium module already

But it does not have any of these

**Comment by Nyeriah** [comment]
Yes, please create a module for this. Closing.
