### ISSUE TITLE
Focused Assault Debuff Persisting After WSG Ends

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6195]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/738

The Focused Assault debuff https://wowgaming.altervista.org/aowow/?spell=46392 stays after the WSG battleground ends in certain circumstances.

<a href="https://ibb.co/6rT8t31"><img src="https://i.ibb.co/BcQG6Xr/CCbug.jpg" alt="CCbug" border="0"></a>

Tester's notes: Confirmed. This issue was originally raised in https://github.com/azerothcore/azerothcore-wotlk/issues/5157, where it was fixed in most cases. However, there do seem to be rare edge cases where it persists. To get it to break in this case involved two druids, CFBG, and bear form - see reproduction steps for details. Somewhat unexpectedly, it's the druid who was not faction changed that was affected.

![WoWScrnShot_060221_220852](https://user-images.githubusercontent.com/81782124/120481802-a3583880-c3ef-11eb-815e-0838568511c0.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Focused Assault should not remain on your character after the battleground ends. I can't find any evidence about this issue specifically, but patch notes at the bottom of this page: https://wowpedia.fandom.com/wiki/Warsong_Gulch state that the timer for the debuff should reset when both flags are returned to their bases, which I assume happens when a battleground ends. Also it just doesn't make sense for it to remain when you don't have the flag anymore.

##### STEPS TO REPRODUCE THE PROBLEM:

1. join WSG with two druids of the same faction
2. CFBG will assign one to the opposite faction
3. Go bear and carry flag until you get debuffed with Focused Assault (or use .aura 46392 on BOTH characters)
4. wait until battleground ends
5. observe the debuff still being there. Weirdly, the affected druid in my case was the non faction-changed one.

As a note, this took days to reproduce, and I'm not confident it's distilled down to exactly the elements that are causing it to fail. It's a combination of CFBG, bear form, and maybe other buffs. But for anyone trying to reproduce this, don't try once, fail, and declare that it's not happening. Like I said, this took days.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Could probably easily be solved by RemoveAuraDueToSpell in the exit function. For anyone who wants to do it

**Comment by UltraNix** [comment]
@Azcobu I cannot reproduce it with CFBG.

**Comment by UltraNix** [comment]
Still no confirmation?

**Comment by Azcobu** [comment]
I'll have another look at some stage. The only way for this bug to appear is if the BG times out, and that takes 20 minutes each time, which makes testing a bit slow. Do you know a command or a way to stop WSG without capping the flags (which makes the debuff vanish) or waiting out the full 20 minutes every time? I can't see anything in the GM commands - even .bf start/stop seems to be for Wintergrasp rather than BGs.

**Comment by UltraNix** [comment]
No.

**Comment by FrancescoBorzi** [comment]
> Do you know a command or a way to stop WSG without capping the flags

we should probably implement it

**Comment by UltraNix** [comment]
@Azcobu Any results here? Can be closed?

**Comment by Azcobu** [comment]
I've tried it a few more times with no results, and the lack of any other reports for this in the 4 months since this was reported suggests we can close this.
