### ISSUE TITLE
Creature Aggro Range Problem

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#62]
I haven't tested a lot, but from the little I have I know that the creature aggro does not function correctly at all, no matter enabled, disabled, set at 0.5, 0.1, etc.

#
#    Rate.Creature.Aggro
#        Description: Aggro radius percentage.
#        Default:     1   - (Enabled, 100%)
#                     1.5 - (Enabled, 150%)
#                     0   - (Disabled, 0%)

Rate.Creature.Aggro = 0
This value is in the worldserver.conf on Sunwell, but not Trinitycore. I would love to see it work correctly, but no matter what you set it at it still defaults to 1.

#
#    Rate.Mining.Amount
#        Description: Rate for minimum/maximum times a deposit can be used.
#        Default:     1

Rate.Mining.Amount = 4

**Comment by boom8866** [comment]
Determine invalid

**Comment by dunjeon** [comment]
It's too bad this is closed because Aggro range is broken.  Aggro in this core is not working as intended.  Anyone who has used it would tell you the same.

**Comment by Yehonal** [comment]
it's closed because issue doesn't follow guidelines, must be created another issue with correct information
