### ISSUE TITLE
DB/Creature: Core Hound formation

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#620]
**Description**: The Core Hound should be linked. Let me explain: if one of the group is alive, if it is not killed within a given time, the others will each turn up.

**Current behaviour**: Tell us what happens
When a Core Hound is still alive in the small group that is connected to it, those already on the ground do not stand up.

**Expected behaviour**: Tell us what should happen instead
As long as all Core Hounds are not dead after a specified time others should revive.

[https://www.youtube.com/watch?v=0yMd6Toe9wQ](url)
Watch from 15min how a fight unfolds. The AOEs are there to make sure that the monsters are dying in the same time or in the specified time. 

![capture](https://user-images.githubusercontent.com/31663279/30271109-5dcf386c-96ef-11e7-8f44-407c7f3e3bd9.PNG)

**Steps to reproduce the problem**:

1. kill just one and see if he will be revive
2. 
3. 

**Branch(es)**: Master 

**AC hash/commit**: 2aedf1359377

**Operating system**: Ubuntu server 16.04.3 LTS

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Gargarensis** [comment]
See also: https://github.com/azerothcore/azerothcore-wotlk/issues/592

**Comment by Maurowin** [comment]
I seen it's now fixed. 
"Molten Core fixes #604"

But is it now available? Because i have downloaded and compiled yesterday.

**Comment by ShinDarth** [comment]
@Maurowin that Pull Request has not been merged to the master branch yet, if that's what you were asking. It would be nice if you can [test it](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request) and give your feedback, so the fix can be accepted and the PR merged to master branch.

**Comment by Maurowin** [comment]
How can I test? I guess I have to download the .cpp, but where do I apply them?
/home/username/azerothcore/src/scripts/Custom ??

**Comment by Maurowin** [comment]
I'm following instructions but i have issue : 
@Arthas:~/test$ git remote add Gargarensis https://github.com/GARGARENSIS/azerothcore-wotlk.git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by ShinDarth** [comment]
try with: `git remote add gargarensis https://github.com/Gargarensis/azerothcore-wotlk.git`

**Comment by ShinDarth** [comment]
also you need to run it from your repository directory

**Comment by Maurowin** [comment]
i'm noob with Git ^^

**Comment by ShinDarth** [comment]
@Maurowin  I really suggest to learn it: it is widely used in every programming context

**Comment by Maurowin** [comment]
I'm not developper :(

But i can participate with bugs reports :)

**Comment by ShinDarth** [comment]
@Maurowin no problem, that helps too :)

However learning how to use git does not require any programming skill, and it's relatively easy. You can give it a try :)  You'll need it to help testing the fixes that developers make for the reported issues.

**Comment by Maurowin** [comment]
Of course ! I wanted to say that I could not do bug fixes because I do not know how to develop. As a matter of fact, I will inquire about git so that I can test the fixes.

**Comment by Maurowin** [comment]
@ShinDarth @Gargarensis i can now compile your fixes Gargarensis. I'm compiling your pull.

I will make feedback tomorrow of your all fixes on molten core.

**Comment by Maurowin** [comment]
@Gargarensis Core Hound script doesn't work 
c714f0cbb127

**Comment by Yehonal** [comment]
It should have been fixed in one of these commits: https://github.com/azerothcore/azerothcore-wotlk/commits?author=sanctum32 feel free to reopen it if still needed
