### ISSUE TITLE
Clusters of herbs spawning in Felwood

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6203]
Original report from Chromiecraft [https://github.com/chromiecraft/chromiecraft/issues/762](https://github.com/chromiecraft/chromiecraft/issues/762)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Herbs in very close proximity. 
![image](https://user-images.githubusercontent.com/68164076/120588104-7570f500-c3eb-11eb-9197-da1da96eff11.png)While 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should not spawn that close together

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go object 19879
2. .learn 2383 (find herbs) and activate
3. Count the number of herbs 

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by poryagholami1374** [comment]
![WoWScrnShot_060321_164301](https://user-images.githubusercontent.com/80007195/120643062-ed422c80-c48a-11eb-9f0c-46f3080405ec.jpg)
In the Source of Azeroth
This problem does not exist
You can fix this

**Comment by Ragelezz** [comment]
Cannot reproduce, only 3 appear onto my map. Probably fixed?

**Comment by FrancescoBorzi** [comment]
@Stump876 can you please give this another try on latest AC?
