### ISSUE TITLE
Automated unban of accounts for temp bans is broken

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#6205]
**CURRENT BEHAVIOUR:**

When an account was temporarily banned, the `active` column in `ac_auth.account_banned` is not reset from 1 to 0 for that account. As a result, the account can log in but is instantly disconnected upon reaching character list.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The temporary ban should expire properly.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. `account create test111 55` 
2. `ban account test111 60s test`
3. log in with account test111 and password 55 when the minute has passed -> "You have been disconnected from the server."
4. `SELECT * FROM ac_auth.account_banned WHERE banreason = "test";` -> See how active is still 1

**EXTRA NOTES:**

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by poryagholami1374** [comment]
> **CURRENT BEHAVIOUR:**
> 
> When an account was temporarily banned, the `active` column in `ac_auth.account_banned` is not reset from 1 to 0 for that account. As a result, the account can log in but is instantly disconnected upon reaching character list.
> 
> **EXPECTED BLIZZLIKE BEHAVIOUR:**
> 
> The temporary ban should expire properly.
> 
> **SOURCE:**
> 
> **STEPS TO REPRODUCE THE PROBLEM:**
> 
> 1. `account create test111 55`
> 2. `ban account test111 60s test`
> 3. log in with account test111 and password 55 when the minute has passed -> "You have been disconnected from the server."
> 4. `SELECT * FROM ac_auth.account_banned WHERE banreason = "test";` -> See how active is still 1
> 
> **EXTRA NOTES:**
> 
> ##### AC HASH/COMMIT:
> [chromiecraft@3716ddf](https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001)
> 
> ##### OPERATING SYSTEM:
> Ubuntu 20.04
> 
> ##### MODULES:
> * [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
> * [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
> * [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
> * [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
> * [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
> * [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
> * [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
> * [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
> * [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
> * [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
> * [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
> 
> ##### OTHER CUSTOMIZATIONS:
> None.
> 
> ##### SERVER:
> ChromieCraft
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98898399-automated-unban-of-accounts-for-temp-bans-is-broken?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).

I did not understand what you meant
What is the problem now?
The title you say is not for Time
For the text of what the offender has done that has been blocked

**Comment by poryagholami1374** [comment]
I did not understand what you meant
What is the problem now?
The title you say is not for Time
For the text of what the offender has done that has been blocked

**Comment by Winfidonarleyan** [comment]
I fix this with replace ace

**Comment by UltraNix** [comment]
@Winfidonarleyan @55Honey Should be fixed?

**Comment by 55Honey** [comment]
Tested for accounts, IPs, and characters. Works confirmed.
