### ISSUE TITLE
Young Wetlands Crocolisk in the middle of the road

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6209]
**CURRENT BEHAVIOUR:**

Is in the middle of the road.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Younglings should be able to cross the wetlands with the only fear that the aggro will be activated from afar.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to the wetlands, coordinates on the map.
2. Check if the crocolisk is in the middle of the road.

**EXTRA NOTES:**

![WoWScrnShot_060321_153810](https://user-images.githubusercontent.com/82579073/120650855-d8639a00-c486-11eb-987d-dfe3b28eced2.jpg)
![WoWScrnShot_060321_160938](https://user-images.githubusercontent.com/82579073/120650998-f7fac280-c486-11eb-9604-c902f95f129d.jpg)

**AC HASH/COMMIT:**
 

ChromieCraft on AzerothCore rev. 3716ddf3e4e1

**OPERATING SYSTEM:**

Windows 10 20H2

**MODULES:**

The ones on the Chromie server.

**CUSTOMIZATIONS:**

-

**Comment by poryagholami1374** [comment]
With a command you can move it wherever you want
In my opinion, spend your time only on more important issues

.npc move

**Comment by Sedatyf** [comment]
> With a command you can move it wherever you want
> In my opinion, spend your time only on more important issues
> 
> .npc move
> 
> Or gps it npc
> Change

That's why the priority is Low. But @Eldarix is right, all issues should be reported and treated

**Comment by poryagholami1374** [comment]
> > With a command you can move it wherever you want
> > In my opinion, spend your time only on more important issues
> > .npc move
> > Or gps it npc
> > Change
> 
> That's why the priority is Low. But @Eldarix is right, all issues should be reported and treated

You are right
But it does not matter
GPS can change the body
And instead of reporting
In the correction list
To be placed

I think this person
Be skilled in fixing

**Comment by Sedatyf** [comment]
That's not how it works here @poryagholami1374 
Everything have to be documented and done here in Github so everyone, including you, will benefit it. If we start to patch only on server, we'll loose open source spirit and what we're working for. 

So no Eldarix doesn't lack skills. If you think it's easy, patch it yourself the correct way

**Comment by poryagholami1374** [comment]
> That's not how it works here @poryagholami1374
> Everything have to be documented and done here in Github so everyone, including you, will benefit it. If we start to patch only on server, we'll loose open source spirit and what we're working for.
> 
> So no Eldarix doesn't lack skills. If you think it's easy, patch it yourself the correct way

Little by little I have posts that
 I will fix what I left
Wait, I'll fix this, I'll post it

**Comment by poryagholami1374** [comment]
![WoWScrnShot_060421_022304](https://user-images.githubusercontent.com/80007195/120717008-1a6afb00-c4dc-11eb-993a-656fafbc14d0.jpg)

**Comment by poryagholami1374** [comment]
insert into `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) values('10859','1417','0','0','0','1','1','1035','0','-3134.426582','-1878.890381','6.172008','5.060332','300','10','0','531','0','1','0','0','0','','0');

**Comment by poryagholami1374** [comment]
Fixed
Good luck

**Comment by Sedatyf** [comment]
Can you make a PR out of it? So we can test it, validate it, and finally merge it

**Comment by Eldarix** [comment]
Thx Sedatyf :)

And yes poryagholami1374 mate, you don't decide what i do with my time thanks ^^

**Comment by poryagholami1374** [comment]
> Can you make a PR out of it? So we can test it, validate it, and finally merge it

I do not know this
You can if you can
Put this

**Comment by poryagholami1374** [comment]
> Thx @Sedatyf :)
> 
> And yes @poryagholami1374 mate, you don't decide what i do with my time thanks ^^ I just passed by and saw it, and it doesn't cost anything to make a report.
> 
> We seek perfection in the details, from the general to the particular and from the small to the large.
> 
> Nice old school 4:3 screen format btw :D

We are friends
No one is superior
I told you
Instead of reporting small issues
Easily fix them
And replace with corrections
You are a fixer
If he was a novice, I would not say this

**Comment by Eldarix** [comment]
Thanks for the suggestions but i will keep doing whatever i decide :)

And i'm a tester, a player, a writer and some other things, but not a fixer.
Take care.
