### ISSUE TITLE
[WORLD] Random blood elf voice talking to you in Shattrath

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#621]
**Description**:  I saw this over at TC and it's also happening in AC.

>While you're in Shattrath there is an omnipotent Blood Elf voice that says things to you at random about every 30 seconds or so.

> "Not very intelligent are you?"
"You waste my time."
and a few others

I don't know if this is supposed to be for a quest where you're berated by a blood elf but it's certainly not normal.

https://github.com/TrinityCore/TrinityCore/issues/19427

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by ShinDarth** [comment]
can you please link the issue report of TC ?

**Comment by StygianTheBest** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19427

**Comment by ShinDarth** [comment]
so it looks like that there's the fix already, please try it and open a pull request:

https://github.com/TrinityCore/TrinityCore/commit/f7bb1d899da27b62a54193e158c1400ef107015a

remember to give credits to the original author in the commit
