### ISSUE TITLE
Various NPC Pets Despawn on Master's Death

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6211]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/767

Currently, killing Razormane Hunter while his Razormane Wolf is still alive makes the Wolf disappear out of thin air.
Video recorded on ChromieCraft: https://youtu.be/vh3VBQRHpCM
Razormane Hunter: https://wowgaming.altervista.org/aowow/?npc=3265
Razormane Wolf: https://wowgaming.altervista.org/aowow/?npc=3939

Tester's notes: Also checked some other pet NPCs, the Skullsplitter Hunters in STV, and the Sons of Cenarius in Stonetalon, and both their pets despawn when the master is killed too. Probably this is just scratching the surfaces and lots of others are affected. Still looking for more evidence that this isn't Blizzlike though.

Razormane Hunters from Wow Classic: https://youtu.be/DFJUFwg524s?t=284 and https://youtu.be/-r_Ots0t77c?t=536
Son of Cenarius:- https://youtu.be/K9kV7eLGrdE?t=121
Skullsplitter Hunter: https://youtu.be/o61USvLPDUY?t=238

Also a comment from TBC about Skullsplitter Hunters:
Don't kill the pet first or else it'll be resummoned in a few seconds. Also, **kiling the hunter doesn't not mean his pet despawns, it will keep eating you.** Enjoy. (https://www.wowhead.com/npc=669/skullsplitter-hunter#comments:id=201589)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Wolf should not disappear, it should stay in the open world.

##### SOURCE:

This is from Classic Wow (the retail one that released late August 2019): https://youtu.be/p_mlzteluTE?t=2854
At 47:34 the player engages a Razormane Hunter and kills the hunter, the Wolf stays alive and then dies. The Wolf does not disappear when the Razormane Hunter dies.
Sorry for the very bad quality, I'll try to find another better quality source.
It is not WotLK but there should be no reason why this kind of behaviour would be changed ?

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Barrens, near 55 ; 26, and find a Razormane Hunter.
2. Kill the Razormane Hunter while not killing the Wolf.
3. See the Razormane Wolf disappear as the Hunter dies.

##### EXTRA NOTES:

As stated, evidence is from Classic Wow. I do not think that this behaviour would have been changed when retail went to WotLK but I could be wrong.

Tester: It seems fairly clear pets did not despawn on their master's death in Classic and TBC-era Wow, but some more evidence for Wrath would certainly be nice. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by arielcami** [comment]
Confirmed, I would also add:

If you range-attack the Master (in this case, Razormane Hunter) and ignore the pet, sometimes the pet stays out of combat.

In a ranged fight, pets must got right at who is attacking its master. 
A better example happens in Tanaris (.go xyz -7616.42 -4303.95 11.35 1 0.63) pets never attack the player unless the player attacks them.

rev 40cf7b46d22

**Comment by poryagholami1374** [comment]
It's almost like this post
But this post is your npc
My post is about heroes

issues/6065

**Comment by Azcobu** [comment]
@arielcami - It may be worth reporting that as a separate issue, or re-opening the old ticket for it. It has been reported in the past - see https://github.com/azerothcore/azerothcore-wotlk/issues/4952, but that was apparently fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/5171, which has been merged. If it's still doing it, and your video looks like clear proof that it is, then that's probably the best approach towards getting it fixed.

**Comment by arielcami** [comment]
> @arielcami - It may be worth reporting that as a separate issue, or re-opening the old ticket for it. It has been reported in the past - see #4952, but that was apparently fixed in #5171, which has been merged. If it's still doing it, and your video looks like clear proof that it is, then that's probably the best approach towards getting it fixed.

Issued new report.

**Comment by T1ti** [comment]
I've noticed this too, pets respawn when master dies on AC, that never happens on classic
