### ISSUE TITLE
Fatal error during compilation using Docker when updating

### ISSUE THREAD

**Issue by mserajnik** [azerothcore/azerothcore-wotlk#6224]
**CURRENT BEHAVIOUR:**

I'm running AzerothCore on a freshly installed Debian 10 host using Docker, following the [_Install with Docker_](https://www.azerothcore.org/wiki/Install-with-Docker) article.

I've just tried updating from 196f74fdad977d534b222a5bf6ba9f68c59ec609 to 3b207d149f544e73a2ff395192e23e8c01faf5f3 via the method described [in the article](https://www.azerothcore.org/wiki/Install-with-Docker#how-to-keep-your-azerothcore-updated-with-the-latest-changes):

```shell
$ git pull origin master
$ ./acore.sh docker build
```

During the compilation, a fatal error occurs. Here's the full output from `docker-compose run --rm ac-build bash apps/docker/docker-build-dev.sh` (which is run when executing `./acore.sh docker build`): https://gist.github.com/mserajnik/8a23f5961af640eb51b2fd42b20031a8

And here's just the relevant part with the errorr: 

```log
fatal error: file '/azerothcore/src/common/Configuration/Config.h' has been modified since the precompiled header '/azerothcore/var/build/obj/src/server/authserver/CMakeFiles/authserver.dir/cmake_pch.hxx.pch' was built: size changed
note: please rebuild precompiled header '/azerothcore/var/build/obj/src/server/authserver/CMakeFiles/authserver.dir/cmake_pch.hxx.pch'
1 error generated.
make[2]: *** [src/server/authserver/CMakeFiles/authserver.dir/build.make:109: src/server/authserver/CMakeFiles/authserver.dir/Server/AuthSocket.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
fatal error: file '/azerothcore/src/common/Configuration/Config.h' has been modified since the precompiled header '/azerothcore/var/build/obj/src/server/authserver/CMakeFiles/authserver.dir/cmake_pch.hxx.pch' was built: size changed
note: please rebuild precompiled header '/azerothcore/var/build/obj/src/server/authserver/CMakeFiles/authserver.dir/cmake_pch.hxx.pch'
1 error generated.
make[2]: *** [src/server/authserver/CMakeFiles/authserver.dir/build.make:79: src/server/authserver/CMakeFiles/authserver.dir/Main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1003: src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

The commit that modified `src/common/Configuration/Config.h` is c568bdcc42efce7de5ca543cc38f9c6f01914d01 (which is between 196f74fdad977d534b222a5bf6ba9f68c59ec609, which I started at, and 3b207d149f544e73a2ff395192e23e8c01faf5f3, which I tried updating to).

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The compilation should complete successfully, unless this is expected behavior and can be ignored.

**STEPS TO REPRODUCE THE PROBLEM:**

1. Start with a fresh installation, check out 196f74fdad977d534b222a5bf6ba9f68c59ec609
2. Build and run the server according to [the article](https://www.azerothcore.org/wiki/Install-with-Docker)
3. Check out 3b207d149f544e73a2ff395192e23e8c01faf5f3 and try updating according to [the article](https://www.azerothcore.org/wiki/Install-with-Docker#how-to-keep-your-azerothcore-updated-with-the-latest-changes)

**EXTRA NOTES:**

I ran `docker-compose down` before attempting the update. However, I believe that shouldn't matter, as the volumes containing the build cache are still kept (I didn't run `docker system prune` or anything like that manually).

I was also previously (a few days ago) able to successfully update in the same manner without encountering errors when there were changes in the code that required a (partial) re-compilation (but I don't remember the exact commits).

I can also confirm that a fresh installation using 3b207d149f544e73a2ff395192e23e8c01faf5f3 directly (so not updating from a previous version) compiles just fine. But based on the error message, it was obvious that a clean compilation without any cache wouldn't encounter that issue anyway.

**AC HASH/COMMIT:**

3b207d149f544e73a2ff395192e23e8c01faf5f3

**OPERATING SYSTEM:**

Debian 10 host (kernel version 4.19.0-16-amd64), Docker version 20.10.7

**MODULES:**

- [mod-autobalance](https://github.com/azerothcore/mod-autobalance)

**CUSTOMIZATIONS:**

None.

**Comment by FrancescoBorzi** [comment]
try a clean build (delete your build files)

**Comment by mserajnik** [comment]
I did, which worked. I'm closing this issue then since it seems like this is expected to happen at times and just requires deleting the build files, as you say (or at least, that's what I'm reading from your answer).

That should probably be explained in the article since less tech-savvy people will stumble over this and won't know what to do.

**Comment by FrancescoBorzi** [comment]
@mserajnik glad that you solved the problem, thanks for letting us know

**Comment by overflowz** [comment]
may I know how can I remove the build cache? I'm facing the same issue right now.
