### ISSUE TITLE
Burning Steppes - Black Drakes Having Various Pathing Issues

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6227]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/779

The Black Drakes in Burning Steppes (https://wowgaming.altervista.org/aowow/?npc=7044):

GUID 5505 missing patrol pattern, is stationary
![5505nopath](https://user-images.githubusercontent.com/80769357/120839064-c8bc8200-c568-11eb-9436-26726cd2e2eb.jpg)

GUID 3298 clipping through the ground while patroling. He goes up above the ground for a portion of the path, then clips back through ground
![3298](https://user-images.githubusercontent.com/80769357/120839177-eab60480-c568-11eb-83e9-c9cc73db113d.jpg)

GUID 3299 clipping through the ground while patroling. He goes up above the ground for a portion of the path, then clips back through ground
![3299](https://user-images.githubusercontent.com/80769357/120839200-f3a6d600-c568-11eb-96c3-aab5891e3e3a.jpg)

Tester's notes: Confirmed on all three. Also note this is very similar to https://github.com/azerothcore/azerothcore-wotlk/issues/6040 - same issue, just different mobs.

![WoWScrnShot_060521_112948](https://user-images.githubusercontent.com/81782124/120876810-1e893c80-c5f2-11eb-8f97-c77d0bcb2d3d.jpg)
![WoWScrnShot_060521_113100](https://user-images.githubusercontent.com/81782124/120876816-2812a480-c5f2-11eb-9256-f8a57dc1fb5f.jpg)
![WoWScrnShot_060521_113248](https://user-images.githubusercontent.com/81782124/120876820-2ea11c00-c5f2-11eb-9e3b-9269cad0faa1.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Drakes should patrol around, and not clip through the ground.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2.  Observe the patrol pattern of two drakes, and stationary nature of the third

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by vtihomirov** [comment]
Here a TBC Classic recording of the drake paths: https://youtu.be/oYzsjSeNS2M
