### ISSUE TITLE
solace of the defeated / solace of the fallen don't proc on penance heal tick.

### ISSUE THREAD

**Issue by lineagedr** [azerothcore/azerothcore-wotlk#624]
**Description**:
solace of the defeated / solace of the fallen don't proc on penance heal tick.
**Current behaviour**: Tell us what happens
solace of the defeated / solace of the fallen don't proc on penance heal tick.
**Expected behaviour**: Tell us what should happen instead
All penance heal ticks should proc the solace trinket
**Steps to reproduce the problem**:
Have Solace Trinket Equipped
Cast Penance
It procs on cast but not after the heal ticks.
1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master
**AC hash/commit**:  
9d2395e1d379e539bd6da0138cb425532c848cb6
**Operating system**:  
win64
**Modules**:  Are you using modules? if yes, list them
no
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
no

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
can you please fix your issue report? add the commit hash at least...

**Comment by lineagedr** [comment]
done

**Comment by ShinDarth** [comment]
I reopened the issue.

However remember that the more details you give, and the easier would be for other people to understand where the problem is = more chances to get it fixed.

Honestly I personally don't get much context from just:

> solace of the defeated / solace of the fallen don't proc on penance heal tick.
