### ISSUE TITLE
Fresh DB installation results in a mix of collations error

### ISSUE THREAD

**Issue by Dranni21312** [azerothcore/azerothcore-wotlk#6242]
**CURRENT BEHAVIOUR:**
After following the installation guide, the initial attempt at import-all results in an error when processing AUTH updates:

Version 1.9.1 is already installed
1) all: Assemble all                                4) customs: Assemble only customs                   7) import-updates: Assemble & Import only updates
2) bases: Assemble only bases                       5) import-all: Assemble & Import all                8) import-customs:  Assemble & Import only customs
3) updates: Assemble only updates                   6) import-bases: Assemble & Import only bases       9) quit: Exit from this menu
[Please enter your choice]: 5
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
Generating /home/osboxes/azerothcore/env/dist/sql/auth_base ...
Searching on /home/osboxes/azerothcore/data/sql/base/db_auth/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/auth_updates ...
Searching on /home/osboxes/azerothcore/data/sql/updates/db_auth/ ...
Searching on /home/osboxes/azerothcore/data/sql/updates/pending_db_auth/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/auth_custom ...
Searching on /home/osboxes/azerothcore/data/sql/custom/db_auth/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/characters_base ...
Searching on /home/osboxes/azerothcore/data/sql/base/db_characters ...
Generating /home/osboxes/azerothcore/env/dist/sql/characters_updates ...
Searching on /home/osboxes/azerothcore/data/sql/updates/db_characters/ ...
Searching on /home/osboxes/azerothcore/data/sql/updates/pending_db_characters/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/characters_custom ...
Searching on /home/osboxes/azerothcore/data/sql/custom/db_characters/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/world_base ...
Searching on /home/osboxes/azerothcore/data/sql/base/db_world/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/world_updates ...
Searching on /home/osboxes/azerothcore/data/sql/updates/db_world/ ...
Searching on /home/osboxes/azerothcore/data/sql/updates/pending_db_world/ ...
Generating /home/osboxes/azerothcore/env/dist/sql/world_custom ...
Searching on /home/osboxes/azerothcore/data/sql/custom/db_world/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
acore_auth database exists
acore_characters database exists
acore_world database exists
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
acore_auth seems empty
importing AUTH - base ...
acore_characters seems empty
importing CHARACTERS - base ...
acore_world seems empty
importing WORLD - base ...
importing AUTH - updates ...
**ERROR 1267 (HY000) at line 437: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='**

Running import-updates after that completes without an issue

**AC HASH/COMMIT:**
dba0c3c

**OPERATING SYSTEM:**
Ubuntu Server 21.04 Hirsute Hippo

**MODULES:**
None

**CUSTOMIZATIONS:**
None

**Comment by FrancescoBorzi** [comment]
@Kitzunu

**Comment by Kitzunu** [comment]
I cannot find the issue if I don't know file name because importing works for me without any issues

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/36a6d04156214b207d7b1f286ff8f365c733a557/data/sql/updates/db_auth/2021_05_13_00.sql#L76

Try add ) DEFAULT CHARSET=utf8mb4;
