### ISSUE TITLE
error in configuration process, project files may be invalid

### ISSUE THREAD

**Issue by Remberance** [azerothcore/azerothcore-wotlk#6246]
**CURRENT BEHAVIOUR:**
when cmake, it disappeared: error in configuration process, project files may be invalid

**EXPECTED BLIZZLIKE BEHAVIOUR:**
NONE

**STEPS TO REPRODUCE THE PROBLEM:**

1. pull the lastest code
2. run cmake
3. configer, "error in configuration process"
4. check error.log, i find: not found pthread.h.
![image](https://user-images.githubusercontent.com/4078506/120919591-f8949280-c6ec-11eb-93af-71d91213fc13.png)

BEFORE 15/3/2021, cmake and build worked perfect.

**EXTRA NOTES:**
VS 2019
CMAKE 3.20.3
BOOST 1.72.0
GIT 2.27.0.1
MYSQL 5.7.25
OPENSSL 1.1.1

**AC HASH/COMMIT:**
07d0f654d56e6b9aaffa6a2998dc9fb1d50cc747

**OPERATING SYSTEM:**
WIN10   VS2019

**MODULES:**
account achievement
ah bot
autobalance
bgreward
eluna
instance reset
learn spell
npc beastmaster
npc buffer
npc enchanter
pvp titles
transmog

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
Try delete CMake cache and configure/generate it again

**Comment by Remberance** [comment]
> Try delete CMake cache and configure/generate it again

delete cache time and time again, but all fail. :(

**Comment by Kitzunu** [comment]
Please show the entire error log in CMake

**Comment by Remberance** [comment]
> Please show the entire error log in CMake

Determining if the include file pthread.h exists failed with the following output:
Change Dir: D:/AzerothCoreR/Build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Micorsoft Visual Studio/MSBuild/Current/Bin/MSBuild.exe cmTC_9d52b.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.10.0+4242f381a

版权所有(C) Microsoft Corporation。保留所有权利。



  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30037 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  CheckIncludeFile.c

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9d52b.dir\Debug\\" /Fd"cmTC_9d52b.dir\Debug\vc142.pdb" /external:env:EXTERNAL_INCLUDE /external:W1 /Gd /TC /errorReport:queue D:\AzerothCoreR\Build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

D:\AzerothCoreR\Build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [D:\AzerothCoreR\Build\CMakeFiles\CMakeTmp\cmTC_9d52b.vcxproj]

**Comment by Kitzunu** [comment]
:shrug: There should not be such file.

Try again on latest master and without any modules

**Comment by Remberance** [comment]
> 🤷 There should not be such file.
> 
> Try again on latest master and without any modules

Determining if the include file pthread.h exists failed with the following output:
Change Dir: D:/AzerothCoreR/Build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Micorsoft Visual Studio/MSBuild/Current/Bin/MSBuild.exe cmTC_fd991.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.10.0+4242f381a

版权所有(C) Microsoft Corporation。保留所有权利。



  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30037 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  CheckIncludeFile.c

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_fd991.dir\Debug\\" /Fd"cmTC_fd991.dir\Debug\vc142.pdb" /external:env:EXTERNAL_INCLUDE /external:W1 /Gd /TC /errorReport:queue D:\AzerothCoreR\Build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

D:\AzerothCoreR\Build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [D:\AzerothCoreR\Build\CMakeFiles\CMakeTmp\cmTC_fd991.vcxproj]

it seems still wrong.

**Comment by Kitzunu** [comment]
p:VisualStudioVersion=16.0 your VS is out of date, you need at least 16.4

check https://www.azerothcore.org/wiki/windows-requirements

**Comment by Remberance** [comment]
> p:VisualStudioVersion=16.0 your VS is out of date, you need at least 16.4
> 
> check https://www.azerothcore.org/wiki/windows-requirements

![image](https://user-images.githubusercontent.com/4078506/121159611-e8f88380-c87d-11eb-9a10-7f06f6636e9d.png)
16.10.0, why? :(

**Comment by Remberance** [comment]
> p:VisualStudioVersion=16.0 your VS is out of date, you need at least 16.4
> 
> check https://www.azerothcore.org/wiki/windows-requirements

![image](https://user-images.githubusercontent.com/4078506/121507125-ef6e3300-ca16-11eb-96d4-fb145d429e6f.png)
 when i check updates in vs2019, then display this message. v16.10.1. Ah... whats wrong.

**Comment by jordigil** [comment]
I'm compiling with win10 64-bits (latest version)
VS 16.10.1
cmake 3.20.3
etc...

And all process is fine, I think this issue can be closed, if anyone have the same error just delete cache and configure&generate again.

**Comment by Remberance** [comment]
because BOOST is not lastest. not include libs-msvc-14.0
