### ISSUE TITLE
Difficulty switching from ranged -> melee auto attack on hunter

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6248]
Original Chrimiecraft report [https://github.com/chromiecraft/chromiecraft/issues/795](https://github.com/chromiecraft/chromiecraft/issues/795)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Auto shot switching to auto attack allows one melee hit before it stops attacing altogether.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should switch into melee auto attack in melee range (and back to auto shot if out) and continue attacking unless told to do otherwise.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Make sure auto attack/auto shot is checked in the combat tab of the interface
2. R click to start combat with ranged
3. When the mob gets close enough, the hunter does one swing with melee and stops attacking.

##### EXTRA NOTES:

https://user-images.githubusercontent.com/68164076/120938892-fb31c080-c6c9-11eb-941d-9f3a2fbfe38b.mp4

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
This used to work on CC, hence my guess is that it's a regression caused by the rather recent PR #6169.
@Ultranix What do you think?

**Comment by UltraNix** [comment]
Yep, that's it. I'm on fire.
