### ISSUE TITLE
[CORE][CONFIG] start lvl 80

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#625]
**Description**: 
I recompile the core today and I notice that despite the fact that the option  is to start lvl 1, we systematically start level 80.

**Current behaviour**: Tell us what happens
start lvl 80 dispite of option is to start lvl 1

**Expected behaviour**: Tell us what should happen instead
start lvl 1

**Steps to reproduce the problem**:

1. compil + make sure start level is 1
2. create character
3. look your level

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  
9d2395e1d379

**Operating system**:  ubuntu server 16.04.3 LTS

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Inifield** [comment]
that's because you're on a gm account

**Comment by sucofog** [comment]
Lol
