### ISSUE TITLE
Hillsbrad Foothills NPC not displayed correctly

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#6253]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

NPC George Candarte ( https://wowgaming.altervista.org/aowow/?npc=2698 ) in Hillsbrad Foothills (coord: 91.9 ; 38.2) is invisible ; only his dagger and vial are visible.
NPC is still clickable, but not sure if you can interract with him as I am Alliance.
![WoWScrnShot_040721_175101](https://user-images.githubusercontent.com/81818678/113896221-0780c680-97ca-11eb-99ae-4bf459f9f9cf.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should be fully visible : https://classic.wowhead.com/npc=2698/george-candarte

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.go c id 2698`                      Go to Hillsbrad Foothills near the northenmost part of Thoradin's Wall, coords 91.9 ; 38.2
2. See the NPC

##### EXTRA NOTES:

CC issue: https://github.com/chromiecraft/chromiecraft/issues/367

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Confirmed from a Horde perspective. I was able to interact with him quite normally. On rev 0a7017a40836, and running a pure vanilla client, so no model packs or anything like that.

![WoWScrnShot_060721_221053](https://user-images.githubusercontent.com/81782124/121021212-4ccc6f00-c7e0-11eb-9df5-206f12433333.jpg)

**Comment by Krejza9** [comment]
I found out that sometimes it works and sometimes it doesn't after restarting the server
![image](https://user-images.githubusercontent.com/5585555/121225965-53afbc00-c88a-11eb-8398-4549abfaaaeb.png)
