### ISSUE TITLE
Various NPCs Not Dismounting Players On Daze

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6256]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/803

I was hanging around in Tirisfal Glades and ran through some mobs who dazed me. Mobs were below level 10, and I was level 39.
I got dazed but I stayed on my mount.
Here is a video:
https://youtu.be/gnyFnymrjXw
Sorry for the bad quality, I updated OBS and forgot to set the output resolution.
Here is a screenshot of the "Daze":
![WoWScrnShot_060721_121123](https://user-images.githubusercontent.com/81818678/121000977-19132a00-c78b-11eb-9379-8e3e368fe39e.jpg)

Not displayed but I cross checked with my paladin and other mobs in the area (zombies, low level scarlet crusade members)

Tester's notes: Tried with the Darkhounds, and they never dismount you. Sat there for a while in case it was just a low percentage chance, but no result. These Ravenous Darkhounds use a variety of Daze with a spell id of 13946. A search to find others found 44 NPC types of a wide level range that use this version of Daze. 
```
SELECT ct.name
FROM  `creature_template` ct
JOIN `smart_scripts`ss ON ct.entry = ss.entryorguid   
WHERE ss.action_param1 = 13496
```
```
+-------+----------------------------+----------+
| entry | name                       | maxlevel |
+-------+----------------------------+----------+
|  1935 | Tirisfal Farmhand          |        6 |
|  1128 | Young Black Bear           |        6 |
|  1199 | Juvenile Snow Leopard      |        6 |
|  1547 | Decrepit Darkhound         |        6 |
| 15655 | Rotlimb Cannibal           |        7 |
|  1934 | Tirisfal Farmer            |        7 |
|  1201 | Snow Leopard               |        8 |
|  1543 | Vile Fin Puddlejumper      |        8 |
|  1548 | Cursed Darkhound           |        8 |
|   822 | Young Forest Bear          |        9 |
|  1537 | Scarlet Zealot             |        9 |
|  1549 | Ravenous Darkhound         |       10 |
|    36 | Harvest Golem              |       12 |
|  1770 | Moonrage Darkrunner        |       12 |
|  1869 | Ravenclaw Champion         |       15 |
|   114 | Harvest Watcher            |       15 |
|  1972 | Grimson the Pale           |       15 |
|     3 | Flesh Eater                |       25 |
|  2248 | Cave Yeti                  |       31 |
|  4130 | Silithid Searcher          |       33 |
|  4872 | Obsidian Golem             |       37 |
|  2723 | Stone Golem                |       39 |
|  2735 | Lesser Rock Elemental      |       39 |
|  2473 | Granistad                  |       40 |
|  2347 | Wild Gryphon               |       40 |
|  2474 | Kurdros                    |       40 |
|    92 | Rock Elemental             |       40 |
|  2780 | Caretaker Nevlin           |       41 |
|  2781 | Caretaker Weston           |       41 |
|  2782 | Caretaker Alaric           |       41 |
|  5253 | Woodpaw Brute              |       42 |
|  2736 | Greater Rock Elemental     |       44 |
|  5292 | Feral Scar Yeti            |       44 |
|  5300 | Frayfeather Hippogryph     |       44 |
|  8447 | Clunk                      |       44 |
|  5246 | Zukk'ash Worker            |       45 |
|  5293 | Hulking Feral Scar         |       46 |
|  5853 | Tempered War Golem         |       47 |
|  5850 | Blazing Elemental          |       47 |
|  5461 | Sea Elemental              |       49 |
|  7032 | Greater Obsidian Elemental |       57 |
|  9219 | Spirestone Butcher         |       57 |
| 11698 | Hive'Ashi Stinger          |       58 |
|  9218 | Spirestone Battle Lord     |       58 |
+-------+----------------------------+----------+
44 rows in set (0.05 sec)
```
There was a comment on TBC Wowhead that claimed that mobs use different versions of Daze depending on whether the target is mounted or not (see https://tbc.wowhead.com/spell=1604/dazed#comments:id=272586). No idea if that's true or not, but perhaps these mobs are using the wrong type of Daze.

![WoWScrnShot_060821_000623](https://user-images.githubusercontent.com/81782124/121041272-c0c34300-c7f1-11eb-9b68-a2ef1de7b29f.jpg)

![WoWScrnShot_060821_000722](https://user-images.githubusercontent.com/81782124/121041304-c882e780-c7f1-11eb-93a1-ea3a175933f2.jpg)

![WoWScrnShot_060821_003556](https://user-images.githubusercontent.com/81782124/121041232-b9039e80-c7f1-11eb-8911-11af47f110e4.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I didn't play WotLK but I expect all daze to dismount me.

##### SOURCE:

"Creature daze is a 50% snare debuff, which often forces its target to dismount if mounted." (https://wowpedia.fandom.com/wiki/Daze?oldid=2374988)

"If you get dazed while mounted, your mount is dispelled."  (https://tbc.wowhead.com/spell=1604/dazed#comments:id=210850)

"If anyone doesnt know this also dismounts you" (https://tbc.wowhead.com/spell=1604/dazed#comments:id=2770406)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be high level strong character (for instance level 39) on your favorite mount
2. Run through a low level mob to get dazed
3. Admire as you are still on your mount

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Note that this is **not** the core daze of 3 seconds but an additional custom daze of 10s (funny enough it's the daze proc effect from **Mug'O'Hurt** https://wowgaming.altervista.org/aowow/?spell=13496) which is inflicted via SmartAI.

The **Core Daze** (which is what the above mentioned sources are talking about)  also has some addtional properties like **noob protection** and takes level and defense/attack skill differences into account. Which the unconditional daze from SmartAI does not.

See also #4571 (https://github.com/chromiecraft/chromiecraft/issues/61).
This SmartAI daze was initially even applied from the front.

**Comment by UltraNix** [comment]
It's not a bug. Only generic "Dazed" dismount you (and all mobs have a chance to use it).
But some mobs in addition use different types of that spell and should not dismount you.
