### ISSUE TITLE
Bug Naxxramas Boss Kel'Thuzad

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6259]
### CURRENT BEHAVIOUR:
All npcs fall in the middle
This is a bug

### EXPECTED BLIZZLIKE BEHAVIOUR:
This is correct
One by one expression

### SOURCE:

https://user-images.githubusercontent.com/80007195/121066366-0a566280-c7df-11eb-8493-e448925762f1.mp4

### STEPS TO REPRODUCE THE PROBLEM:
.go cre 133933

### AC HASH/COMMIT:
rev. 579dbe1+ 2021-05-31 17:05:09

### OPERATING SYSTEM:
Windows Server 2019 Standard

### MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by steenburgh** [comment]
Here's a video of the expected behavior:
https://youtu.be/nM0NFpmi9X0

**Comment by poryagholami1374** [comment]
> Here's a video of the expected behavior:
> https://youtu.be/nM0NFpmi9X0

https://www.youtube.com/watch?v=PCteaDafYF0

**Comment by steenburgh** [comment]
Confirmed on 725f1cbda08d28d2c717fe02119f731489dd11a7

**Comment by steenburgh** [comment]
@poryagholami1374 would you mind updating the title to be a little more descriptive so folks can quickly get an idea of what's wrong without watching the video - something like:
> Naxxramas - Kel'Thuzad: Adds spawn much too quickly

**Comment by poryagholami1374** [comment]
> @poryagholami1374 would you mind updating the title to be a little more descriptive so folks can quickly get an idea of what's wrong without watching the video - something like:

the problem is that
npc all together
They attack

**Comment by meowcpp** [comment]
Well I tested it and mobs that are spawned (in corners) at the beggining of encounter should not attack but all of them are aggressive so they start to attack immediately. I just have to know how should mobs in corners respond to player's attack – should they stay passive, should they start attacking and also these mobs (in corners) should disappear at the end of first phase but I don't know if these mobs (in corners) should also disappear if someone attacked them during first phase or they should then stay there. If someone is gonna tell me how it should work I can fix this bug.

**Comment by steenburgh** [comment]
Are there similar bosses you can look at the behavior for? I know Ignis does something similar with his adds. This also might still be available on retail if someone has an account

**Comment by steenburgh** [comment]
For more details, see the following duplicate issues 
* #6930 
* #6862

**Comment by Si1ker** [comment]
In my Naxxramas work, it was working just fine, I left the entire instance 99% perfect, and the KT encounter was working perfectly.
[fix(scripts/Naxx): The art of Naxxramas (1/2)](https://github.com/azerothcore/azerothcore-wotlk/pull/4076)
[fix(scripts/Naxx): The art of Naxxramas (2/2)](https://github.com/azerothcore/azerothcore-wotlk/pull/5057)

Recent changes must have broken it. 🐱

**Comment by Kitzunu** [comment]
It's a map bug

**Comment by steenburgh** [comment]
My guess is that it's pathfinding related

**Comment by FrancescoBorzi** [comment]
cc @Yehonal @UltraNix

**Comment by UltraNix** [comment]
But what is the bug here? 
Bug about spawning too many mobs is not related to map guys...

**Comment by betayi** [comment]
Confirm, my old version at April is running good. but after updated 2 days ago , it running with this bug

**Comment by iyasenai** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5065

**Comment by Si1ker** [comment]
@poryagholami1374 
@steenburgh 
@betayi 

Try this https://github.com/azerothcore/azerothcore-wotlk/pull/7650/files and let us know the result in the PR

**Comment by betayi** [comment]
it worked!
