### ISSUE TITLE
Herbs spawning in doubles/groups

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6264]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Various clusters/double spawns of herbs found all throughout Azeroth. This is a known issue that is caused by missing pooling data and is on the list to be worked on.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herbs typically should not spawn in groups. 

##### STEPS TO REPRODUCE THE PROBLEM:

Individual reports linked from Chromiecraft to this.
1. .go gobject `GUID` (shown below)
Arathi Highlands
[3859, 3151](https://github.com/chromiecraft/chromiecraft/issues/796)
Eastern Plaguelands
[19536, 19537, 19428](https://github.com/chromiecraft/chromiecraft/issues/801)
Tirissal Glades
[2014, 35473, 32216](https://github.com/chromiecraft/chromiecraft/issues/802)
Barrens
[1742, 63422](https://github.com/chromiecraft/chromiecraft/issues/766)

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
Other reported pairings:
Alterac Mountains:
- [7675 & 7738](https://github.com/azerothcore/azerothcore-wotlk/issues/6254)

Should also note that a long list of other herb nodes within 3 units of each other in the open world is [here](https://github.com/Azcobu/azcore-dupenodes).

**Comment by Eldarix** [comment]
A report that I had lost in the void and I just recovered and checked:

https://github.com/chromiecraft/chromiecraft/issues/966

I imagine that it is unnecessary to upload a screenshot of each one of them, but I can confirm that all those that appear in the report are certainly double.
