### ISSUE TITLE
The problem of teleportation Naxxramas

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6266]
### CURRENT BEHAVIOUR:
This portal should open when you play the whole boss
But it goes straight to
Sapphire boss

### SOURCE:

https://user-images.githubusercontent.com/80007195/121137452-e54c0900-c84b-11eb-9eb3-73a09d8cf94a.mp4

### STEPS TO REPRODUCE THE PROBLEM:
.go 3675.62465 -1263.841431 243.887665
Open a Raide
And go inside
And go up
As in the clip

### AC HASH/COMMIT:
rev. 579dbe1+ 2021-05-31 17:05:09

### OPERATING SYSTEM:
Windows Server 2019 Standard

### MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by poryagholami1374** [comment]
> In 3.3.5a this is blizzlike

They say they should kill the whole boss
Then they can go upstairs

**Comment by Kitzunu** [comment]
Doing a bit of research you will find this
![image](https://user-images.githubusercontent.com/24550914/121152727-bf236a80-c845-11eb-9cf8-5e77d4770802.png)

Implying that after 3.3.0 you no longer need to clear all 4 quarters
