### ISSUE TITLE
Contagion of Rot spell self spreading and stacking

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6276]
Original report from Chromiecraft [https://github.com/chromiecraft/chromiecraft/issues/811](https://github.com/chromiecraft/chromiecraft/issues/811)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Fetid corpse casts [Contagion of Rot](https://classic.wowhead.com/spell=7102/contagion-of-rot#used-by-npc) "5% chance to spread to allies" However, when infected it can spread to yourself with this version of [Contagion of Rot](https://www.wowhead.com/spell=7102/contagion-of-rot#used-by-npc) "10% chance to spread to allies" This version appears to stack on itself and the version cast by the Fetid Corpse. I'm not exactly sure which version is correct, or if they are both correct and this is how the spell acts. But the bug is the stacking and self spreading.
![image](https://user-images.githubusercontent.com/68164076/121285293-fbc98300-c892-11eb-81d8-98b0459697ed.png)
![image](https://user-images.githubusercontent.com/68164076/121285342-169bf780-c893-11eb-9574-9c9ecbe86f4e.png)
![image](https://user-images.githubusercontent.com/68164076/121285252-eb190d00-c892-11eb-94c6-9a8a2a019fd0.png)
Tested by attacking a Spider.
![image](https://user-images.githubusercontent.com/68164076/121287622-be66f480-c896-11eb-8d51-b9db99389961.png)
##### EXPECTED BLIZZLIKE BEHAVIOUR:

The disease should just refresh, as it does with the version casted by Fetid Corpse, not stack. And it should only spread to allies as the tooltip says, not to self.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go creature 6077
2. Aggro and wait for the disease to be applied.
3. go attack something, preferably something other than a fetid corpse to prove that it's proccing from you and not just being recast.
4. Wait for it to spread to you.

##### EXTRA NOTES:

NPC: Fetid Corpse (npc=1270)
SPELL: Contagion of Rot (spell=7102)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
I second this bug. I encountered it today on CC and it is very hard to complete the quest "Totem of Infliction" as a melee character, because "Contagion of Rot" stacked 6 times on me and my attackspeed was reduced to 11 s. 
It would be really nice, if someone could make a fix for it. Ty!
