### ISSUE TITLE
[CORE] The corpses of the monsters disappear too fast

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#628]
**Description**: The corpses of the monsters disappear too fast (all monsters in all azeroth). If we die and the cemetery finds it far away, the corpse will have already disappeared. In the official the bodies remained much longer.

**Current behaviour**: Tell us what happens
 The corpses of the monsters disappear too fast. 

**Expected behaviour**: Tell us what should happen instead
In the official the bodies remained much longer.

**Steps to reproduce the problem**:

1. kill monster 
2. look your chrono
3. 

**Branch(es)**: Master

**AC hash/commit**:  9d2395e

**Operating system**: Ubuntu server 16.04.03 LTS  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by boom8866** [comment]
Corpse.Decay.NORMAL
  Corpse.Decay.RARE
  Corpse.Decay.ELITE
  Corpse.Decay.RAREELITE
  Corpse.Decay.WORLDBOSS

Adjust CONF Solution

**Comment by Maurowin** [comment]
Ohh nice thank you !

It will be necessary to set by default the value 300 for the normals on source code.

**Comment by ShinDarth** [comment]
> In the official the bodies remained much longer

do you mean in the wotlk official or in the current one?

**Comment by Maurowin** [comment]
i don't remenber but i think the corpses in retail wotlk stay more time, correct me if i wrong

**Comment by poszer** [comment]
1 minute is fine as normal. If you need more time, set it in your world configuration.
Also, check respawn time of creatures, if creature respawn < corpse decay, respawn time is in advantage.

#        Description: Time (in seconds) until creature corpse will decay if not looted or skinned.
#        Default:     60   - (1 Minute, Corpse.Decay.NORMAL)
#                     300  - (5 Minutes, Corpse.Decay.RARE)
#                     300  - (5 Minutes, Corpse.Decay.ELITE)
#                     300  - (5 Minutes, Corpse.Decay.RAREELITE)
#                     3600 - (1 Hour, Corpse.Decay.WORLDBOSS)

Closing this.
