### ISSUE TITLE
Core/Scripts: Mimiron's Spinning Up + Mine Issues [$30]

### ISSUE THREAD

**Issue by xclid** [azerothcore/azerothcore-wotlk#6281]
**CURRENT BEHAVIOUR:**

Full video here
https://youtu.be/450PUVQn-2M

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The mine should be released in an arc.
Spinning should work correctly, Issues appears on P2 and P4.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. .gm on
2. .go c 137630
3. start encounter

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
361fd86416c5267dacc33701196afc7ce95140dd

**OPERATING SYSTEM:**

win10

**MODULES:**

mod-ah-bot
mod-anticheat
mod-cfbg
mod-eluna-lua-engine
mod-individual-xp
mod-transmog

**CUSTOMIZATIONS:**

**Comment by xclid** [comment]
Add $30 for these issues

**Comment by meowcpp** [comment]
Well, I could reproduce mines bug and can fix that but spinning works just fine on my server – can someone else test it please?

**Comment by xclid** [comment]
Spinning spell vision and damage are out of sync
Please try to test with multiple characters
I will provide more test information after work

**Comment by Ragelezz** [comment]
Whats left to do here exactly ? The spinning issue since the mine's were mentioned in a PR already.
