### ISSUE TITLE
[Maraudon] Princess Theradras missing spells

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#6285]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Princess Theradrass in Maraudon does currently not cast [Dust Field](https://www.wowhead.com/?spell=21909): Shake the ground nearby, damaging nearby enemies and knocking them back and also not [Thrash](https://www.wowhead.com/?spell=3391). 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
She should cast both spells, dealing incresed melee damage and knocking nearby enmies back. 

A video of her fight on AC is on [this video at 19:15](https://www.twitch.tv/videos/1050704615?t=00h19m14s)

##### SOURCE:

Source: https://wowpedia.fandom.com/wiki/Princess_Theradras_(tactics)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Maraudon Pristine Waters
2. Fight Princess and watch her spells

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by buddiman** [comment]
[Trash](https://www.wowhead.com/?spell=3391) seems to work on https://github.com/azerothcore/azerothcore-wotlk/commit/7106e6642135fe30c8c927bef0f0c01ffe782062.
![grafik](https://user-images.githubusercontent.com/10009755/121358721-1c491a00-c933-11eb-8778-339770c77c51.png)

[Repulsive Gaze](https://www.wowhead.com/?spell=21869) gets casted.

[Boulder](https://www.wowhead.com/spell=21832/boulder) and [Dust Field](https://www.wowhead.com/spell=21909/dust-field) were not cast by Princess Theradras.
