### ISSUE TITLE
[CORE][DATABASE] wrong count characters on server list

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#629]
**Description**: When we create a character, we play and one day we want to erase it or even play God create one to erase it! The server always counts 1 character even if we have already erased everything.

**Current behaviour**: Tell us what happens
The server always counts 1 character even if we have already erased everything.

**Expected behaviour**: Tell us what should happen instead
Counts 0 character and put population to " new players" instead of "low"

**Steps to reproduce the problem**:

1. create character (only one an realm)
2. delete 
3. look your server list and see 1 character
![wowscrnshot_091217_140842](https://user-images.githubusercontent.com/31663279/30401891-1e28fa42-98dc-11e7-8187-d2c7027c8439.jpg)

**Branch(es)**: Master

**AC hash/commit**:  9d2395e

**Operating system**:  Ubuntu server 16.04.03 LTS

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
I think this was inherited from mangos or trinitycore, or it's a client issue. Not sure.

**Comment by Maurowin** [comment]
It is in the database because we set the value to 0 manually, in the game, it regulates the problem of quantification but not the worry with New Players instead of low
