### ISSUE TITLE
Clamlette Magnifique

### ISSUE THREAD

**Issue by Muhblizzlike** [azerothcore/azerothcore-wotlk#6293]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The well fed effect from the consumable item [Clamlette Magnifique] (Item Id 33004) doesn't give ranged attack power but only melee attack power.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The well fed buff should apply to both melee and ranged attack power.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 
4.

##### EXTRA NOTES:

I'm assuming this is a bug because at wotlk Attack Power buffs, buffs both melee and ranged attack power.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by mserajnik** [comment]
@Muhblizzlike Please fill out the other sections from the issue template as well, especially the _AC Hash/Commit_.

If this is on ChromieCraft, you can just [copy this issue template](https://github.com/chromiecraft/chromiecraft/issues/new) which has the technical information prefilled.

**Comment by anguaive** [comment]
Can confirm.

**Comment by Kitzunu** [comment]
It always just says attack power (never defined for any foodbuff if it is range or melee), and I find nowhere that it should give range attackpower.

It also already has 3 aura types, so it is impossible that it should or could have another one.

<details><summary>SpellWork Details</summary>

```
ID - 64057 Well Fed
=================================================
ToolTip: Attack power increased by $s1 and spell power increased by $s2.
Category = 0, SpellIconID = 59, activeIconID = 0, SpellVisual = (0,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x08000000 (SPELL_ATTR0_CASTABLE_WHILE_SITTING)
AttributesEx2: 0x80000000 (SPELL_ATTR2_FOOD_BUFF)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00
Duration: ID (42)  3600000, 0, 3600000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 24 Bonus = 1,00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 99 (SPELL_AURA_MOD_ATTACK_POWER), value = 24, misc = 2 (2), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 14 Bonus = 1,00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 13 (SPELL_AURA_MOD_DAMAGE_DONE), value = 14, misc = 126 (126), miscB = 0, periodic = 0

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 14
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 135 (SPELL_AURA_MOD_HEALING_DONE), value = 14, misc = 126 (126), miscB = 0, periodic = 0
```
</details>
