### ISSUE TITLE
HoR Quest bug fix for alliance side.

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#63]
Here is a problem to alliance quest: http://www.wowhead.com/quest=24500/wrath-of-the-lich-king.

Why always ally? /cry

Anyway,,, I found

/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.h

NPC_ARCHMAGE_ELANDRA = 37774,

was wrong. Its not her.

Actually its him. http://www.wowhead.com/npc=37582/archmage-koreln

Its more blizzlike by profit to .cpp

Or if you dont wanna compile.

Here is queries.

INSERT INTO creature_queststarter VALUES (37774, 24500);
UPDATE creature_template SET npcflag = 2 WHERE entry IN (37774, 37809);

Entry 37809 is the heoric mode's entry number of ARCHMAGE_ELANDRA(37774).

**Comment by ShinDarth** [comment]
Missing core rev, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
