### ISSUE TITLE
Shaman auto-attack stops when a totem dies

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6306]
Original Chrimiecraft report https://github.com/chromiecraft/chromiecraft/issues/805

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Auto attack stops once a totem expires on it's own or is destroyed. However, it does not happen not when using totemic recall

https://user-images.githubusercontent.com/68164076/121620568-68718880-ca1f-11eb-82ae-72e012e9aacd.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Auto attack should not be tied to the totem's fate

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a shaman
2. .level 55 (or any level)
3. .learn all my spells
4. .additem 46978 and equip
5. head to a training dummy or creature of your choice
6. Drop any totem and auto attack (stoneclaw totem works well as it has a short lifespan)
7. When the totem expires auto attack stops.
8. Repeat with other totems for verification

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
@Stump876 I cannot reproduce it with any of totem.

**Comment by Stump876** [comment]
Retesting with a current AC setup, it seems to have resolved itself. I can't reproduce it anymore. I wonder if it was tied into another fix. I guess we're good to close this?

**Comment by Helias** [comment]
I think so
