### ISSUE TITLE
Karazhan Bosses Opera BUG [$10]

### ISSUE THREAD

**Issue by Mycadi** [azerothcore/azerothcore-wotlk#631]
**Description:**
Karazhan Boss Opera kill Unable to disengage from combat.

**Steps to reproduce the problem:**

1. Get into Karazhan.
2. attack  Boss Opera.
3.kill Opera Unable to disengage from combat.

**Branch(es):** Master

**AC hash/commit:** 9d2395e1d379e539bd6da0138cb425532c848cb6

**Operating system:** Windows 64

**Modules:** Karazhan/Bosses_Opera.cpp

**Comment by ShinDarth** [comment]
please change:

> AC hash/commit: Last Rev

with the actual hash value,  ...simply because it will no longer be "last rev" as soon as other commits will be pushed :D

**Comment by talamortis** [comment]
Please can you provide which boss is causing the error so i can fix? Thanks.

**Comment by Mycadi** [comment]
Karazhan - opera - boss

**Comment by talamortis** [comment]
I know that it I wouldn't ask just wondering if it's a specific event like big bad wolf, Romeo and Juliet? or it's all the bosses

**Comment by Mycadi** [comment]
All the bosses in the opera. 
Players cannot disengage from combat when all the bosses are killed, which result to the players died in the combat cannot get into Karazhan again.

**Comment by xDevICCI** [comment]
up !

**Comment by disclosurez** [comment]
can confirm issue still exists.

**Comment by milestorme** [comment]
Can also confirm this issue

**Comment by Viste** [comment]
you all can try #2163

**Comment by Viste** [comment]
Please send bounty to @FrancescoBorzi 5$ and @Winfidonarleyan 5$ 
because i dont have the way to get it(God bless America and PayPal) xDD

**Comment by FrancescoBorzi** [comment]
@Viste you're too generous!

@Winfidonarleyan please claim it

**Comment by Winfidonarleyan** [comment]
@Viste big thanks, @FrancescoBorzi done
