### ISSUE TITLE
Searing Totem - Various Issues With Neutral NPCs

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6310]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/830

Searing Totem doesn't engage with neutral targets even if im attacking them, on agressive mobs it works as intended

Tester's notes: This is half right. It doesn't engage if you use ranged attacks. (Earth Shock, Lightning Bolt, etc.) If you use melee attacks, it engages correctly. Demonstration here - while I'm only using ranged attacks, the totem doesn't activate. Only when I use melee does it attack.

https://user-images.githubusercontent.com/81782124/121676114-68db5380-caf3-11eb-8e83-a4334cc498dc.mp4

However, against other neutral mobs, like Magram Centaurs, it attacks immediately. Here's a screenshot vs a neutral centaur where it attacked without me doing anything aggressive at all.

![WoWScrnShot_061121_203215](https://user-images.githubusercontent.com/81782124/121676813-3d0c9d80-caf4-11eb-84b3-3d6208afff8b.jpg)

See also https://github.com/azerothcore/azerothcore-wotlk/pull/5434

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Totem should only attack neutral mobs if the player has first engaged with the target. And if the player has engaged, whether with ranged or melee, the totem should then attack.

##### SOURCE:

"Also note that the totem only engages hostile targets on its own; it ignores neutral targets, unless you engage them first." - https://wowwiki-archive.fandom.com/wiki/Searing_Totem

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find a neutral mob - i used turtles near Revantusk.
2. Engage with the neutral mob using ranged attacks
3. Place Searing Totem 
4. Searing Totem will NOT attack the neutral mob

Alternatively:
1. Find a Gelkis or Magram centaur.
2. place totem, watch it attack without you doing anything.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Weird, cuz this should definetly take care of it

https://github.com/azerothcore/azerothcore-wotlk/blob/e82731001d2bfd54097805dc7bc292c0b1ae57a8/src/server/game/AI/CoreAI/TotemAI.cpp#L79-L82

Sounds more to me that the player isn't properly set in combat if a ranged ability is used, but I might be wrong.

I will add it to my todo list and see if I can figure it out

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/127342379-be634cad-e37c-4ecb-8dc0-6338185470a6.png)
？？？

**Comment by pklloveyou** [comment]
Right click on the creature and the totem starts fighting
