### ISSUE TITLE
Quest "Testing the Tonic" Missing Final Event

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6311]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/831

After quest turn-in, nothing event-wise happens.

Tester: confirmed. 

Enlightening screenshot of nothing happening:
![WoWScrnShot_061121_204136](https://user-images.githubusercontent.com/81782124/121678250-1c454780-caf6-11eb-8482-dfb42a1dd60b.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After quest turn-in, event text pops up where quest giver drinks the tonic and turns into wretched.

On handin she should say: 
Excellent, it appears that everything is here. Now, all I have to do is mix everything together and give it a try. If this tonic does what my research indicates it should do, I may have discovered a way to lessen the effects of my people's magic addiction.

You're about to witness history in the making, \<name\>. Just think, without your help, this wouldn't have been possible.

After the quest is completed, the following occurs:
<Magistrix Elosai removes the reagents from the crate and mixes portions of each in a flask.>
Magistrix Elosai says: I've endured much hardship to complete my research and with your help, \<name\>, I've finally done it. Here's to a brighter future!
Magistrix Elosai says: I feel... lightheaded... What's... happening to me?
Magistrix Elosai says: No, this can't be! This tonic... it was supposed to reverse my addiction, not hasten my descent into the ranks of the Wretched!
Magistrix Elosai says: All those years of research... and for nothing! Perhaps they were right, perhaps this is something we must learn to live with.

##### SOURCE:

https://wowwiki-archive.fandom.com/wiki/Quest:Testing_the_Tonic

https://wowwiki-archive.fandom.com/wiki/Quest:Testing_the_Tonic

Helpful info on fixing it may also be here: https://github.com/TrinityCore/TrinityCore/commit/16765a186d4359b752c6f3dd9f0a1d2ff2674d84

##### STEPS TO REPRODUCE THE PROBLEM:

1. Turn in the quest.
2. Wait for roleplay.
3. 
##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by vtihomirov** [comment]
Here a TBC Classic recording of the event: https://www.youtube.com/watch?v=XXw-6_VhbtY. Also Wizlo Bearingshiner the quest giver of Testing the Tonic is missing gossip hello text see the video.
