### ISSUE TITLE
Quest "Kodo Roundup" - Further Issues

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6313]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

On the quest Kodo Roundup, if you get too far away from the Kodo, the Kodo will leash back to its spawn point and remain friendly.  The Kodo will remain untargetable by the quest item until server restart (presumably, haven't confirmed).  This issue was brought up [here](https://github.com/chromiecraft/chromiecraft/issues/509#issuecomment-835394811), but I don't think it was addressed in the PR, so resubmitting.  You will then have the debuff from the quest item for 5 minutes, and if you attempt to tame another Kodo before it wears off, it will attack you.

Tester's notes: Confirmed on both counts. Leashing the kodo resets it and it is thereafter untameable:
![WoWScrnShot_061121_211718](https://user-images.githubusercontent.com/81782124/121681821-6b8d7700-cafa-11eb-9659-9dd9bd3427cd.jpg)

And the other kodos will try to attack you if you tame them with the buff active:
![WoWScrnShot_061121_211250](https://user-images.githubusercontent.com/81782124/121681913-88c24580-cafa-11eb-950c-73bb01162f58.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Kodo should follow you no matter how far away you get, as noted [here](https://classic.wowhead.com/quest=5561/kodo-roundup#comments:id=3193496) on WoWhead.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be on quest [Kodo Roundup](https://wotlkdb.com/?quest=5561)
2. Use [Kodo Kombobulator](https://wotlkdb.com/?item=13892) on a neutral Kodo
3. Run far away from Kodo
4. Kodo will leash and remain friendly, unable to be tamed again

##### EXTRA NOTES:

Found many friendly Kodo in the area so it looks like someone else had this happen and the issue persists until the server is restarted.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by avarishd** [comment]
rev b263f45
Could NOT reproduce.
Went to to the other side of Desolace and back. Tried both while having the area unloaded and loaded(with another character).
Same result, creature stops if YOU are out of visibility range, but will always continue to follow when you get back. Never reseted as well.

<details>

https://user-images.githubusercontent.com/46330494/220879387-08d1bb32-53ed-471e-8630-a41bddbd5747.mp4

</details>

**Comment by damnablebear** [comment]
I tested this on the Chromie PTR just now and the kodo follows me to the end of the earth (out of visual range and then follows me back in.) If I go to Scrabblescrew's Camp, I can still turn it in, and it still counts toward the quest requirement.
