### ISSUE TITLE
 Some objects know how to speak.

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#632]
**Description**: Some objects know how to speak.

**Current behaviour**: Tell us what happens

![wowscrnshot_091417_123112](https://user-images.githubusercontent.com/31663279/30448338-cf69da44-998e-11e7-8ee1-ad9a502e1ee5.jpg)

**Expected behaviour**: Tell us what should happen instead
Don't open text window

**Steps to reproduce the problem:**

1. right clic
2. 
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

**Comment by poszer** [comment]
You must to have [Quest](https://www.wowhead.com/quest=12718/more-skulls-for-brew) to see object window.
Also, the creature who speak is [Noth the Plaguebringer](https://www.wowhead.com/npc=28919/noth-the-plaguebringer) while doing these two quests : 
[Noth's Special Brew](https://www.wowhead.com/quest=12717/noths-special-brew)
[The Plaguebringer's Request](https://www.wowhead.com/quest=12716/the-plaguebringers-request)
Also, take a look on this [VIDEO](https://www.youtube.com/watch?v=uhhg6Op1rIM)
Closing this.

**Comment by Maurowin** [comment]
@poszer you have this window only if you have quest. in other case, object don't show window.
