### ISSUE TITLE
Deserter Agitator NPC Positioned at Wrong Angle (GUID: 31046)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#6320]
**CURRENT BEHAVIOUR:**

Deserter Agitator NPC Positioned at Wrong Angle. He's looking at a building and speaking to someone he can't see.

![WoWScrnShot_061121_215513](https://user-images.githubusercontent.com/61194190/121748060-46036c00-cb00-11eb-91ae-eb17baebc1cf.jpg)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Angle him around 15 degrees to the left so he's facing the person he's talking to.

**SOURCE:**

https://wowpedia.fandom.com/wiki/Deserter_Agitator

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to the NPC ID (GUID: 31046)
2. Observe incorrect angle.
3. Hydrate

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

AzerothCore rev. cb1aaec4af13 2021-06-10 11:12:23 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**OPERATING SYSTEM:**

**MODULES:**

ChromieCraft modules (CFBG etc)

**CUSTOMIZATIONS:**

**Comment by Fewmade** [comment]
Hi, I reproduce it on local server 8f640a1 and everything looks good, so I think the issue can be closed

![image](https://user-images.githubusercontent.com/34547317/123219206-4ecb4900-d4d5-11eb-847c-935a60543446.png)

**Comment by Hacaw** [comment]
@Zenslash I could reproduce the issue on 0f57da93. 
I will also a provide a DB fix for it.
