### ISSUE TITLE
Theramore Combat Dummies Chase/Attack Players

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#6321]
**CURRENT BEHAVIOUR:**

![WoWScrnShot_061121_220215](https://user-images.githubusercontent.com/61194190/121748564-1f920080-cb01-11eb-920d-3bd3c14770c0.jpg)

Theramore Combat Dummies Chase/Attack Players which is HILARIOUS but not Blizzlike. They are stationary Target Dummies and should follow Target Dummy behaviour.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

They are stationary Target Dummies and should follow Target Dummy behaviour.

**SOURCE:**

https://wowpedia.fandom.com/wiki/Theramore_Combat_Dummy

This source says they can be attacked but do not take damage and function as a dummy. Given WOTLK changed a lot of Dummy behaviour and added practice DPS dummies to all cities, this is the correct behaviour.

https://classic.wowhead.com/npc=4952/theramore-combat-dummy

However, this Classic source say they cannot be attacked. WOTLK > Classic sources priority for this core.

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to Theramore.
2. Taunt the dummies with a nondamaging attack and watch them chase you until leashed.
3. Cackle.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

AzerothCore rev. cb1aaec 2021-06-10 11:12:23 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Azcobu** [comment]
Rather regret fixing this. Perhaps we can bring aggressive target dummies back in an event some day.

![WoWScrnShot_061421_174642](https://user-images.githubusercontent.com/81782124/121893989-c377e800-cd5d-11eb-9d14-60aa1a77a6fb.jpg)
