### ISSUE TITLE
[Glyphs] Incorrect Spell Tooltip for Cleave after applying Glyph of Cleaving

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6323]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/840

##### CURRENT BEHAVIOUR:

After applying Glyph of Cleaving, the tooltip for spell Cleave doesn't reflect the changes made by the glyph. Glyph of Cleaving increases the number of targets that the Cleave hits by 1. While the ability works as intended and Cleave does indeed hit 3 targets, the tooltip for the spell stays unchanged. 

![WoWScrnShot_061121_102807](https://user-images.githubusercontent.com/84775498/121667103-3ce7b000-caaa-11eb-8af0-e4528afb04db.jpg)
![WoWScrnShot_061121_102815](https://user-images.githubusercontent.com/84775498/121667109-3eb17380-caaa-11eb-9652-84e3d7631b02.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After applying Glyph of Cleaving, the tooltip for spell Cleave should say the following: A sweeping attack that does your weapon damage plus X to the target and his two nearest allies.

##### STEPS TO REPRODUCE THE PROBLEM:

1. As a warrior, apply Glyph of Cleaving
2. Check the tooltip for the Cleave

##### EXTRA NOTES:

Glyph of Cleaving: https://wowgaming.altervista.org/aowow/?item=43414
Cleave: https://wowgaming.altervista.org/aowow/?spell=845#modified-by

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 28664a2):

![WoWScrnShot_061221_074552](https://user-images.githubusercontent.com/82579073/121765369-0f0a7600-cb53-11eb-9ac4-7a6ef1b059df.jpg)
![WoWScrnShot_061221_074721](https://user-images.githubusercontent.com/82579073/121765379-1c276500-cb53-11eb-9b64-c230fc41513b.jpg)
![WoWScrnShot_061221_074758](https://user-images.githubusercontent.com/82579073/121765389-29dcea80-cb53-11eb-9cd9-63b37c9b1a54.jpg)

**Comment by claudiodfc** [comment]
This isn't possible to fix without modifying the client. The server handles the spell **58366** which is the glyph spell for cleave but, the client has no idea how to change the tooltip.

**Comment by claudiodfc** [comment]
Actually there might be a way to fix this. I'm gonna test something
