### ISSUE TITLE
Lesser Heal (Rank 2) sharing a cooldown with items

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6324]
Original report from Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/845

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

[Crystalized Mana Residue](https://wowgaming.altervista.org/aowow?item=23354) and [Cracked Power Core](https://wowgaming.altervista.org/aowow/?item=23334), apparently not only share a cooldown with each other but also share a cooldown with the priest's lesser heal rank 2. Other ranks seem to work fine. Just rank 2 has the problem.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Lesser Heal should not share a cooldown with any item. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .learn 2052
2. .additem 23334
3. .additem 23354
4. Use one of the items, then try to cast Lesser Heal rank 2
5. Repeat as necessary.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
Related to
- PR https://github.com/azerothcore/azerothcore-wotlk/pull/6191
- AC issue https://github.com/azerothcore/azerothcore-wotlk/issues/5475,
- CC issue https://github.com/chromiecraft/chromiecraft/issues/466

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/dafef5bd7859b330cc5c835ee463107944cc915f

**Comment by necropola** [comment]
🎵 We don't need no automation 🎵
