### ISSUE TITLE
Items Still Showing as Tradeable After Shaman Buffs Applied

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6325]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/843

First bug entry here. Please let me know if I forgot something.

Imbuing a still tradeable weapon with shamans flametongue, frostbrand or rockbiter rightfully brings up the dialogue, that the item will not be any longer tradeable after imbued. 
However, if I click "Okay", the item will still state (teal text) that it is tradeable (not tested if it really is). 
Afterwards, the dialogue will still pop up, when I want to imbue the weapon again, so I have to click "Okay" over and over again.
The issue still occurs after deleting the Cache folder and restarting Wow.

As expected, after the initial two-hour loot trading window for the weapon, the issue is no longer present.

https://user-images.githubusercontent.com/68868567/121743725-10f81900-cb02-11eb-84c0-ed62d7d5fd2e.mp4

Tester's notes: Confirmed. The item is not tradeable after the enhancement has been added, which is correct. But the server isn't correctly setting the item to be non-tradeable, as it still shows as tradeable in the inventory even when it's not. As a result it asks you if you're sure you want to add a buff every time you cast one, for the two hours that the weapon tradeability is active.

Adding Frostbrand to a new staff:
![WoWScrnShot_061221_163528](https://user-images.githubusercontent.com/81782124/121768396-2bcb9b80-cb9d-11eb-8a74-d0ba1268d512.jpg)

Same item in inventory shows Frostbrand added, but also says it can still be traded with party members:
![WoWScrnShot_061221_163537](https://user-images.githubusercontent.com/81782124/121768409-3c7c1180-cb9d-11eb-93b2-feca38f95ce5.jpg)

However, trying to do so fails (correctly)
![WoWScrnShot_061221_163555](https://user-images.githubusercontent.com/81782124/121768454-751beb00-cb9d-11eb-9886-36e27ebee500.jpg)

Adding windfury pops up the same message again:
![WoWScrnShot_061221_163608](https://user-images.githubusercontent.com/81782124/121768470-8533ca80-cb9d-11eb-819d-0e5072e534fb.jpg)

Manually deleting the enhancement and then trading the item works (which is also incorrect):
![WoWScrnShot_061221_173319](https://user-images.githubusercontent.com/81782124/121769752-8d433880-cba4-11eb-976f-fe667760a052.jpg)
![WoWScrnShot_061221_173330](https://user-images.githubusercontent.com/81782124/121769757-903e2900-cba4-11eb-86cf-c455f0de06e5.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After clicking "Okay" and imbuing the tradeable weapon, the dialogue should not come up again and the item should therefore not be tradeable any longer.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Loot a weapon that is tradeable
2. Imbue it with any of the shaman weapon spells
3. Click on "Okay", when the dialogue pops up
4. See if the dialogue pops up again, when a new imbue gets applied
5. See if the weapon is still tradeable with the group members

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
Hey, thanks for testing my issue!
Did you also try to manually remove the enhancement and trade it then? (It shouldn't work) 
Thank you

**Comment by Azcobu** [comment]
Thanks for the suggestion, I hadn't tried that. Did it just then, and the trade worked, which as you say, it should not have.

**Comment by syssneck** [comment]
Sorry, I deleted the comment, as I'm not 100 % sure if that is the correct behavior. But yes, I still think it shouldn't be tradeable, even after removing the enhancement.

**Comment by Azcobu** [comment]
The initial popup message you get when applying the buff says the item will not be tradeable afterwards, so that's good enough for me. I had a look for third party data on this to confirm (Wowpedia, Wowhead, etc) but couldn't find any other info on it though.
