### ISSUE TITLE
alliance tag

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#633]
**Description**: I have the tag of the alliance when I make my starting quests of the DK. 

**Current behaviour**: Tell us what happens
when i'm in the enemies city, i get alliance taf on my portrait.

**Expected behaviour**: Tell us what should happen instead
I do not normally at this stage of advancement of the game any liaisaon with the alliance

![wowscrnshot_091417_123507](https://user-images.githubusercontent.com/31663279/30448591-4c28db98-998f-11e7-8e4f-6c1ba70ebe55.jpg)

**Steps to reproduce the problem**:

1. play DK 
2. go on the city of enemies
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

**Comment by poszer** [comment]
AreaTable.dbc

https://image.prntscr.com/image/a9D7FmJaSKaHUn7ZS3zzqw.png
https://image.prntscr.com/image/_Y6_qe9YRs2TWN9a1A-tkg.png

**Comment by Maurowin** [comment]
@poszer you right but look your, you have not horde tag nor alliance you have scourge tag

**Comment by Maurowin** [comment]
we need to have scourge icon : 
![image](https://user-images.githubusercontent.com/31663279/99259981-16ff7300-281b-11eb-9309-86402cb3b3e9.png)
despite of horde or aly icon : 
![image](https://user-images.githubusercontent.com/31663279/99260000-22529e80-281b-11eb-816d-514c92bc8d89.png)

**Comment by Maurowin** [comment]
@Kitzunu can u untag blizzlike tag pls ?

**Comment by Voxstrasza** [comment]
it seems to me that this scourge icon that you have is either a custom addition or something that was removed from the final game, and remains in the files.

here is a video of the DK quest chain from 2009: https://www.youtube.com/watch?v=1Mj-LW5NU1g&ab_channel=stevoman16

you can see the alliance faction badge there, and every other video I've found (from 2008 to 2015) of the DK quest chain, there is no sign of this scourge badge.
