### ISSUE TITLE
Quest: Ending the Bloodcurse- possible to destroy the Statue of Queen Azshara multiple times

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6331]
Original report from Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/848

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Statue of Queen Azshara can be destroyed multiple times when doing the quest 'Ending the Bloodcurse'. 
Each occurrence will spawn another Atoph the Bloodcursed.
All Atoph the Bloodcursed will stand idle behind the statue. which is not the correct place for him to spawn.

![Screenshot from 2021-06-11 21-40-16 copy](https://user-images.githubusercontent.com/85800188/121782708-3b51e100-cbab-11eb-8a5d-c5726352efad.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When Atoph the Bloodcused is spawned, the statue should be in flames, and it should not be possible to click the statue again until he is killed/ despawns. 

##### SOURCE:

https://youtu.be/pWmAazW3ULo?t=159
##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 9683 (Ending the Bloodcurse)
2. .go object 044734
3. R click the statue
4. R click the statue again
5. Notice 2 spawns of Atoph the Bloodcursed behind the statue, and the statue not on fire waiting to be clicked atain

##### EXTRA NOTES:

Related to https://github.com/azerothcore/azerothcore-wotlk/issues/4085

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Stump876 why 1-19 **and** Generic?

**Comment by Stump876** [comment]
Certainly not because I wasn't paying attention. 🙄I was doing it to see if you were, yeah that's it. You passed my test. Well done!

**Comment by FrancescoBorzi** [comment]
> Certainly not because I wasn't paying attention. 🙄I was doing it to see if you were, yeah that's it. You passed my test. Well done!

hahaha thank you!
