### ISSUE TITLE
Priest's Mind Control Basic Attack Not Working

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6333]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/851

Basically when you mind control a humanoid, you have access to all its skills but when it comes to using it's basic it does nothing.

Tester's notes: Confirmed. The other attacks all seem to work fine, but the melee base attack accessible through the 1 key, or by running up to an enemy and right clicking on them, doesn't work at all.

https://user-images.githubusercontent.com/81782124/121795834-6db71900-cc53-11eb-9f57-c5a1e3820776.mp4

##### EXPECTED BLIZZLIKE BEHAVIOUR:

To be able to basic attack.

##### STEPS TO REPRODUCE THE PROBLEM:

1. /use Mind Control
2. Press 1

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
Should be fixed by #7043
