### ISSUE TITLE
visual effect 

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#634]
**Description**: the object after pickup always shines

**Current behaviour**: Tell us what happens
the object after pickup always shines

**Expected behaviour**: Tell us what should happen instead
no longer shine

![wowscrnshot_091417_123720](https://user-images.githubusercontent.com/31663279/30450197-591a1c84-9991-11e7-9ca5-336aa614bc46.jpg)

**Steps to reproduce the problem**:

1. do a quest
2. 
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

**Comment by STARRHELD** [comment]
Could you please refer to a specific quest cause quests like:
http://www.wowhead.com/quest=4402/galgars-cactus-apple-surprise work just fine.

However the Cactus Apple objects despawn upon picking them up, but like the Cauldron is not despawned since it's the only item for the quest amiright?

**Comment by Maurowin** [comment]
The Cauldron doesn't be despawned, juste the light effect around it

**Comment by poszer** [comment]
Please, give us more details about this. What is this quest, where is this?
