### ISSUE TITLE
Rain in Dun Morogh

### ISSUE THREAD

**Issue by mserajnik** [azerothcore/azerothcore-wotlk#6341]
**CURRENT BEHAVIOUR:**

It's currently possible to rain in ~~Coldridge Valley (and probably the rest of Dun Morogh too)~~ Dun Morogh (**Edit:** I was able to reproduce it in Kharanos too, and based on how weather is assigned to zones, I'm now positive this affects all of Dun Morogh), despite it being a snowy area where only snowfall should occur.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

It shouldn't rain in Coldridge Valley/Dun Morogh, but it should snow instead.

**SOURCE:**

- https://wowpedia.fandom.com/wiki/Weather_effects#Zones_with_weather
- https://wowpedia.fandom.com/wiki/Dun_Morogh#Geography_2 (_"Snowfall is common"_)

**STEPS TO REPRODUCE THE PROBLEM:**

1. Travel to Dun Morogh
2. Wait for it to rain

I'm sure there is a nicer/faster way to reproduce this just by checking what weather effects are assigned to the zone.

**EXTRA NOTES:**

Screenshot showing the rain:

![rain](https://user-images.githubusercontent.com/80664890/121814687-a4e8f280-cc72-11eb-8ed7-883e78072fcd.png)

And another, separate occurence with a different test character in Kharanos:
 
![rain2](https://user-images.githubusercontent.com/80664890/121926469-49843680-cd3e-11eb-9150-80f6ba217cd5.png)

**AC HASH/COMMIT:**

e82731001d2bfd54097805dc7bc292c0b1ae57a8

**OPERATING SYSTEM:**

Debian 10 host (kernel version 4.19.0-16-amd64), Docker version 20.10.7

**MODULES:**

- [mod-autobalance](https://github.com/azerothcore/mod-autobalance)

**CUSTOMIZATIONS:**

None.

**Comment by mserajnik** [comment]
I've tried looking into this myself, but I think instead of a data issue, this might be a bug in the code.

Unless I'm doing something wrong, Dun Morogh seems to be zone 1. The data suggests it shouldn't be able to rain there (and those values look ok to me in general):

```sql
mysql> SELECT * FROM game_weather WHERE zone = 1;
+------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+------------------+------------------+-------------------+--------------------+--------------------+---------------------+------------+
| zone | spring_rain_chance | spring_snow_chance | spring_storm_chance | summer_rain_chance | summer_snow_chance | summer_storm_chance | fall_rain_chance | fall_snow_chance | fall_storm_chance | winter_rain_chance | winter_snow_chance | winter_storm_chance | ScriptName |
+------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+------------------+------------------+-------------------+--------------------+--------------------+---------------------+------------+
|    1 |                  0 |                 25 |                   0 |                  0 |                 15 |                   0 |                0 |               25 |                 0 |                  0 |                 25 |                   0 |            |
+------+--------------------+--------------------+---------------------+--------------------+--------------------+---------------------+------------------+------------------+-------------------+--------------------+--------------------+---------------------+------------+
1 row in set (0.00 sec)
```

**Comment by Shineslippers** [comment]
It's general issue to all zones i guess. Whe you're comming from zone with one weather to zone where should not exist this weather effect.

![WoWScrnShot_112221_180710](https://user-images.githubusercontent.com/85256266/142887017-c591e8e1-42b4-4247-b1da-5fe660d2d3de.jpg)

### Steps to reproduce the problem

.go c 6338
.wchange 2 1
run to Loch Modan

**Comment by UltraNix** [comment]
@Shineslippers You can't use commands - it always force to whatever you typed.

**Comment by UltraNix** [comment]
I can't reproduce it.

**Comment by acidmanifesto** [comment]
weather is usually cycled on a one hour timer with the % being the occurance per a hour. to confirm if the issue is valid, we will have to sit and wait in the zone for 1 hour, we will need a exact .gps to better meet the testing enviroments

**Comment by Shineslippers** [comment]
I'm forcing weather in a different zone. In my case `.go c 6338` in Dun Morogh. Just to skip waiting for ocasion
`Map: 0 (Eastern Kingdoms) Zone: 1 (Dun Morogh) Area: 806 (South Gate Outpost) Phase: 1`.

Waiting 5-10 seconds to changes. Going through tunnel to Loch Modan and snow is stil there. On zone change should be force to change weather. Isn't it?
`Map: 0 (Eastern Kingdoms) Zone: 38 (Loch Modan) Area: 924 (Valley of Kings) Phase: 1`

After relog weather is ok.

https://user-images.githubusercontent.com/85256266/144738639-65e734fd-4695-4184-b2c9-fcfc7393ec07.mp4

**Comment by UltraNix** [comment]
No. Every zone has own timer (default 10 mins) when the weather is updated. Changing zone does not change weather.
Forcing weather by command is not a proper way of testing this bug. The problem should be somewhere in updating the weather.
