### ISSUE TITLE
Cannot use the same glyph on 2 specs

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6342]
**CURRENT BEHAVIOUR:**
It is not able to activate the same glyph in the 2 specs, it says it is already active in the other spec. 

**EXPECTED BLIZZLIKE BEHAVIOUR:**
The right thing would be to be able to activate in the 2 specs the same glyph.

**SOURCE:**

**STEPS TO REPRODUCING THE PROBLEM:**
1.Activate a glyph on a spec
2. Try activating the same glyph on the other spec.
3. It won't work, it says it's already active in another spec.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
dafef5bd7859

**OPERATING SYSTEM:**
Windows

**MODULES:**
[mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine) 

**OTHER CUSTOMIZATIONS:**
None.

**Comment by Kitzunu** [comment]
Dont delete the issue template.

**Comment by WillzDevs** [comment]
> Dont delete the issue template.

Right? sorry
