### ISSUE TITLE
Quest "The Corrupter Pt. 3" Missing End Event

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6344]
<!Quest: The Corruptor (Part 3) missing roleplay>

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/856

After turning in the quest The Corruptor (Part 3) to Maurin Bonesplitter at Ghost Walker Post in Desolace, where you gather an Oracle Crystal from naga in Desolace, there is supposed to be a short roleplaying event.

Tester: confirmed, the NPC just stands there. His GUID is 29068.

![WoWScrnShot_061421_130231](https://user-images.githubusercontent.com/81782124/121835702-0b245280-cd11-11eb-8182-479e49baff21.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After completing the quest, there should be a short roleplaying encounter where images of the orc warlock Jug'kar Grimrod and his master Lord Azrethoc appear and speak a few lines of dialogue:

Maurin Bonesplitter says: This should only take a moment, \<name\>.
Maurin Bonesplitter says: [Demonic] X amir rikk zila parn Amanalar Ante rikk thorje xi no
Jugkar Grim'rod's Image says: Pathetic forsaken weakling. You wish to see my master? So be it.
Lord Azrethoc's Image says: [Demonic] Kar refir xi raka no shi
Lord Azrethoc's Image says: [Demonic] Rethule
Lord Azrethoc's Image says: [Demonic] Parn Parn xi rikk mannor no shi rikk
Maurin Bonesplitter says: An interesting turn of events.
Jugkar Grim'rod's Image says: Yes, come. My master and I shall be waiting.

##### SOURCE:

https://wowpedia.fandom.com/wiki/The_Corrupter_(3)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 1482
2. .additem [oracle crystal]
3. .go c 29068 to hand in.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/121992903-cea13700-cda2-11eb-858e-90c65599308b.png)


vmangos has this event scripted

**Comment by vtihomirov** [comment]
Here a video source from TBC Classic: https://youtu.be/ii3qN6e3O7k
