### ISSUE TITLE
Creatures EvadeMode lose auras

### ISSUE THREAD

**Issue by Krejza9** [azerothcore/azerothcore-wotlk#6348]
**CURRENT BEHAVIOUR:**

If an NPC enters into EvadeMode, he loses all his Auras.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
NPCs never lose his already active auras.
https://youtu.be/KFVNX0Ynrw8

**SOURCE:**
4532ef4c7a9dda1e5b4ade7e6a94f13d76e7851b

**STEPS TO REPRODUCE THE PROBLEM:**

1.  .go c 90286
2.  aggro NPC
3.  Switch NPCs to evade mode (.gm on or Or run out of range)

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

**OPERATING SYSTEM:**
Ubuntu 20.04

**MODULES:**
no

**CUSTOMIZATIONS:**
no

**Comment by Kitzunu** [comment]
Could test to change the cluster fuck in Unit.cpp to
```cpp
    if (IsCharmedOwnedByPlayerOrPlayer()) // if it is a player owned creature it should not remove the aura
        return;

    // don't remove vehicle auras, passengers aren't supposed to drop off the vehicle
    // don't remove clone caster on evade (to be verified)
    RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE, SPELL_AURA_CLONE_CASTER);
```

**Comment by Kitzunu** [comment]
Okay while testing this I found something interesting, if you do `.gm on` he actually does not evade, as if you do `.debug threat` you will still see that you are still in his threatlist.

And this wouldn't be the case if he entered Evade as _EnterEvadeMode() calls DeleteThreatList()

**Comment by Krejza9** [comment]
So it means rewriting the functions RemoveEvadeAuras() , RemoveAllAurasExceptType
Xinef, he made a good point // We should not remove passive auras on evade, if npc has player owner (scripted one cast auras)

**Comment by Krejza9** [comment]
So I got it, the problem is that auras assigned by ScriptedAI are probably not considered as aura->IsPassive().
The key is to add to 
` if (aura->GetSpellInfo()->HasAura(SPELL_AURA_CONTROL_VEHICLE) || aura->GetSpellInfo()->HasAura(SPELL_AURA_CLONE_CASTER) || (aura->IsPassive() && GetOwnerGUID().IsPlayer()))`
Auras added by ScriptedAI

**Comment by Krejza9** [comment]
```c++
  if (aura->GetSpellInfo()->HasAura(SPELL_AURA_CONTROL_VEHICLE) || aura->GetSpellInfo()->HasAura(SPELL_AURA_CLONE_CASTER) || (aura->GetSpellInfo()->IsSelfCast() || (aura->IsPassive() && GetOwnerGUID().IsPlayer()))

```

Adding **(aura->GetSpellInfo()->IsSelfCast()** fix whole problem

I have to create a PR, is that ok for you @Kitzunu  ?
