### ISSUE TITLE
[Barrens] Wrong dialog for Jorn Skyseer at Camp Taurajo

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6354]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/865

##### CURRENT BEHAVIOUR:

NPC Jorn Skyseer ( https://wowgaming.altervista.org/aowow/?npc=3387 ) has wrong gossip text: https://youtu.be/rbrq9sRo1z8
I also don't think this gossip text should be available since I have not completed the quest chain yet.
DB GUID: 13949

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Correct gossip text. I can't find it online, will post a comment and update the issue if I do.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Camp Taurajo in Southern Barrens and chat with him ( ".go creature 13949" )

##### EXTRA NOTES:

I checked "10-19" but maybe it should be 20-29 since southern Barrens are a bit higher level?

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 5330cd9 ) :

![WoWScrnShot_061521_024143](https://user-images.githubusercontent.com/82579073/121972265-4eb7a480-cd83-11eb-953e-e0d1b71abcc8.jpg)
![WoWScrnShot_061521_024150](https://user-images.githubusercontent.com/82579073/121972299-62630b00-cd83-11eb-9038-3e80ac4d7d6e.jpg)

**Comment by claudiodfc** [comment]
Missing condition on his gossip option.
