### ISSUE TITLE
PNJ Quest

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#636]
**Description**:The pnj displays the quote performer symbol while normally it is awaiting completion

**Current behaviour**: Tell us what happens
The pnj displays the quote performer symbol while normally it is awaiting completion
![wowscrnshot_091417_163601](https://user-images.githubusercontent.com/31663279/30449795-81fbee4e-9990-11e7-9347-9d7ac461093a.jpg)

**Expected behaviour**: Tell us what should happen instead
don't show : ! 
but
show : ?

**Steps to reproduce the problem**:

1.  accept the quest
2. 
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

**Comment by STARRHELD** [comment]
I cannot reproduce.

**Comment by STARRHELD** [comment]
Note: There are more than one quest named with that name, and I didn’t go through the quest-chain. 

We can keep it closed for now and if this issue reappears, we can keep this as a reference thread.
