### ISSUE TITLE
"Hints of a new plague" escort quest's NPC Kinelory not attacking mobs

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6365]
Original Chromiecraft report: https://github.com/chromiecraft/chromiecraft/issues/846

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

For the escort part of the questline "Hints of a new Plague" in Arathi Highlands, NPC Kinelory in will not fight mobs the player aggros, but will fight mob she herself aggros.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should fight any mobs attacking either the player or herself. 
https://www.youtube.com/watch?v=3sKVUdK4OfM at 2:38 the player will aggro and she turns around to assist.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go creature 14653
2. .quest add 657 (not the escort but the one before it) 
3. Turn it in and begin the escort quest when ready (quest 660)
4. Aggro a few orcs and watch her ignore them. But when she pulls, she will attack.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Windows 10 20H2

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by damnablebear** [comment]
Tested today on the Chromie PTR. If I aggro an enemy and pull it toward Kinelory, she'll run toward me and help me attack, from a fair distance away.
