### ISSUE TITLE
Shaman "Far Sight" camera not working properly on multiple casts

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6368]
Original report(s) combined from Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/870 

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There seems to be several issues with Far Sight. When double casting it to jump to far away or out of direct line of sight locations. First during the second cast the camera jumps back to your character before going to the desired location. 

Second, if you don't interrupt the channeling and let it run out, your camera stays to where you previously used Far Sight- you're first cast point- and you're stuck there unless you cast it again and interrupt to reset the camera https://youtu.be/jj3B8W1mW5o

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Far Sight should cast and recast without jumping back to the player. https://youtu.be/CTnTtXcqTHU
Once the channeling run out it should reset your camera back to the player's character.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use Far Sight
2. Use Far Sight again while the current one is still being channeled
3. Notice the camera
4. Let the second cast run out
5. Notice the camera
6. Cast again and interrupt to reset the camera

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Additionally, some camera issues while using sentry totem. https://github.com/chromiecraft/chromiecraft/issues/1019

**Comment by UltraNix** [comment]
About the 1st problem, seems to be blizz.
https://www.youtube.com/watch?v=db3sYKRf_AQ It's Eagle Eye, but it's the same mechanic.
