### ISSUE TITLE
DK Grab

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#637]
**Description**: DK grab doesn't work correctly

**Current behaviour**: Tell us what happens
The spell does not work properly when we pull with the Grab spell. The PNJ can cast a spell during a grib

![wowscrnshot_091417_200545](https://user-images.githubusercontent.com/31663279/30449887-a6380ce8-9990-11e7-9678-82e3e6206bfb.jpg)

**Expected behaviour**: Tell us what should happen instead

wait animation end before cast

**Steps to reproduce the problem**:

1. pull with grab
2. 
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

**Comment by talamortis** [comment]
can confirm

**Comment by Maurowin** [comment]
@ShinDarth Someone esle confirm this bug.
