### ISSUE TITLE
Morja the Darkmoon NPC have a bugged question mark

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6382]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/822

##### CURRENT BEHAVIOUR:

The Npc have the typical question mark yellowed like when you have a quest completed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should be none question mark or a grey one.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Darkmoon faire in Elwynn
2. Look for Morja
3. See if the described issue exists

##### EXTRA NOTES:

![WoWScrnShot_060921_105820](https://user-images.githubusercontent.com/82579073/121316595-260e5580-c912-11eb-9f33-4ee7de52f80b.jpg)
![WoWScrnShot_060921_105830](https://user-images.githubusercontent.com/82579073/121316700-4211f700-c912-11eb-9ef0-4fcfbe38225e.jpg)
![WoWScrnShot_060921_105843](https://user-images.githubusercontent.com/82579073/121316787-59e97b00-c912-11eb-9ee0-b2321a6fb4eb.jpg)

##### AC HASH/COMMIT:

466cdb68d635 

##### OPERATING SYSTEM:

Windows 10 21H1

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

I confirmed it myself after waiting 8 days withous any interactions.

**Comment by pangolp** [comment]
The problem is that you have the wrong QuestType.

![quest_7946](https://user-images.githubusercontent.com/2810187/122321649-94e34400-cefa-11eb-83d3-f54d40773d45.png)

I will compile the emulator, and test, but it should be 2, not 0.

```
### QuestType

Accepted values: 0, 1, 2 or 3. Their meaning is described in table below.

| Value | Result                                                                                                   |
|-------|----------------------------------------------------------------------------------------------------------|
| 0     | Quest is enabled, but it is auto-completed when accepted; this skips quest objectives and quest details. |
| 1     | Quest is disabled (not yet implemented in the core).                                                     |
| 2     | Quest is enabled (does not auto-complete).                                                               |
| 3     | Quest is a World Quest.                                                                                  |
```
