### ISSUE TITLE
Food Buff's Stacking 

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6383]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/731

##### CURRENT BEHAVIOUR:

The Food buff's from https://wowgaming.altervista.org/aowow/?item=33004 and https://wowgaming.altervista.org/aowow/?item=13931 and possibly many others are currently stacking with one another.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Food buff's should not stack with each other. I was able to find some evidence from comments here during retail WOTLK: https://www.wowhead.com/forums/topic/i-need-a-buff-stacking-guide-69716. Although it is not from 3.3.5a patch specifically, I could not find any information about food buff's ever being able to stack. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. eat https://wowgaming.altervista.org/aowow/?item=33004 for buff
2. eat https://wowgaming.altervista.org/aowow/?item=13931 for buff
3. Observe both buffs stacking

##### EXTRA NOTES:

https://wowgaming.altervista.org/aowow/?item=33004
https://wowgaming.altervista.org/aowow/?item=13931
https://www.wowhead.com/forums/topic/i-need-a-buff-stacking-guide-69716

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 466cdb68d635 ) :

![WoWScrnShot_061721_053056](https://user-images.githubusercontent.com/82579073/122322267-e2c56f80-cf2d-11eb-8d46-fefa6ae30cbe.jpg)
![WoWScrnShot_061721_053100](https://user-images.githubusercontent.com/82579073/122322314-f375e580-cf2d-11eb-9f40-70ed054862b2.jpg)
![WoWScrnShot_061721_053122](https://user-images.githubusercontent.com/82579073/122322353-04265b80-cf2e-11eb-8ef4-f34e8c7d099d.jpg)
![WoWScrnShot_061721_053136](https://user-images.githubusercontent.com/82579073/122322399-14d6d180-cf2e-11eb-9fc9-8300448a31e8.jpg)

It seems that some colleagues were quite sure that it is a bug but they did not dare to create the report so here it is :)

**Comment by Kitzunu** [comment]
going to close in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/10257 as the author is not deleted 😅
