### ISSUE TITLE
Innkeepers still selling perfume/cologne bottles

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6385]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Several innkeepers are still selling perfume and cologne bottles that should only be available during the "Love is in the Air" event. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

These should not be sold outside of the event.

##### SOURCE:

https://www.wowhead.com/item=21829/perfume-bottle#comments
##### STEPS TO REPRODUCE THE PROBLEM:

1. As Horde .go creature 24772 (Thunderbluff) 38407 (Undercity), 4661 (Orgrimmar)
2. As Alliance .go creature 79841 (Stormwind)
3. Check innkeepers for Perfume and Cologne
4.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Eldarix** [comment]
Confirmed in Razor Hill too:

![WoWScrnShot_061721_074745](https://user-images.githubusercontent.com/82579073/122333186-7011bf80-cf40-11eb-891e-9cc3e9acb3c9.jpg)

**Comment by Kitzunu** [comment]
Yes but no. They were removed from the game in Patch 3.3.0

https://wowpedia.fandom.com/wiki/Perfume_Bottle
https://wowpedia.fandom.com/wiki/Cologne_Bottle

**Comment by Eldarix** [comment]
So, it's not just that it's not temporarily adjusted to the event, but it shouldn't even exist, right?

**Comment by Kitzunu** [comment]
Exactly, there is an open PR for it =)

**Comment by Stump876** [comment]
Oh yeah, look at that. That actually explains the supposed bug with the "Flirt with Disaster" achievement I couldn't do back in Feb. If the perfume shouldn't exist then it probably was not giving the buff needed to complete the achievement.
