### ISSUE TITLE
Searing Gorge - Heavy War Golem Clipping Scenery

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6393]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/881

There is a Heavy War Golem in a bad position in the Slag Pit.
DB GUID: 5687
![WoWScrnShot_061721_085704](https://user-images.githubusercontent.com/81818678/122355374-20d48a80-cf52-11eb-8f43-af6f3889b78b.jpg)
![WoWScrnShot_061721_085711](https://user-images.githubusercontent.com/81818678/122355395-2500a800-cf52-11eb-8b65-0bbe1e2ce0bf.jpg)

Tester: Confirmed, he's wedged into that pillar pretty badly in his resting position, though he can move out of it:

![WoWScrnShot_061721_204920](https://user-images.githubusercontent.com/81782124/122387169-be10dc80-cfad-11eb-9fab-845d8835622a.jpg)

![WoWScrnShot_061721_205229](https://user-images.githubusercontent.com/81782124/122387444-05976880-cfae-11eb-9ea8-e2bb5da803d0.jpg)

Update: A second one inthe lava, GUID: 5608.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Maybe he should be on the bridge.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Slag pit, but easiest way would be ".go creature 5687"

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by syssneck** [comment]
This issue was mentioned again in: [chromiecraft/issues/#1189](https://github.com/chromiecraft/chromiecraft/issues/1189)
