### ISSUE TITLE
The Exodar - Festive Kegs Spawned

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6396]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
Original report: https://github.com/chromiecraft/chromiecraft/issues/882

Various Festive Keg, with entry ID 180699, are present at the main entrance of The Exodar.
![image](https://user-images.githubusercontent.com/62886727/122357271-e1a73900-cf53-11eb-80ba-2c7e7303f20b.png)

Tester: confirmed, these appear to be left over from Brewfest? Keg object IDs are 91481-91482, 91487 to 91492, and 91494.

![WoWScrnShot_061721_210430](https://user-images.githubusercontent.com/81782124/122390143-d20a0d80-cfb0-11eb-8baa-5420aef1be97.jpg)
![WoWScrnShot_061721_210736](https://user-images.githubusercontent.com/81782124/122390154-d46c6780-cfb0-11eb-9980-da0b9bf48f65.jpg)
![WoWScrnShot_061721_210751](https://user-images.githubusercontent.com/81782124/122390158-d504fe00-cfb0-11eb-9c3a-06fb7e2dc6ff.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The kegs should only be present on festivities, like 4th of July, or New Year. 

##### SOURCE:
Comments on https://www.wowhead.com/object=180699/festive-keg 
https://wowpedia.fandom.com/wiki/Festive_Keg

##### STEPS TO REPRODUCE THE PROBLEM:

1. go o 91494

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment]
There are party-tables, haybales and festive-kegs at Exodar entrance. 
They are leftovers from: https://github.com/azerothcore/azerothcore-wotlk/pull/4367 
They were removed from event 7 and have no event associated. They have a verified-build column value of 21742.

Looks like it works only if you activate event 0,1,24 but if the server start with none of those events active the gameobjects are enabled by default. 
I found no entries in conditions/smart-ai table. @Helias 
@LannyE have you got any tips about this ?

<details>
<summary>
This should have been the fix, but it's not enough. 
</summary>
```mysql 
INSERT INTO `game_event_gameobject`(`eventEntry`, `guid`)
VALUES -- New Year's Eve
    (0, 91326),
    (0, 91328),
    (0, 91481),
    (0, 91482),
    (0, 91487),
    (0, 91488),
    (0, 91489),
    (0, 91490),
    (0, 91491),
    (0, 91492),
    (0, 91494),
    (0, 92045),
    (0, 92047),
    (0, 92048),
    (0, 92051),
    (0, 92052),

    -- Midsummer Fire Festival
    (1, 91326),
    (1, 91328),
    (1, 91481),
    (1, 91482),
    (1, 91487),
    (1, 91488),
    (1, 91489),
    (1, 91490),
    (1, 91491),
    (1, 91492),
    (1, 91494),
    (1, 92045),
    (1, 92047),
    (1, 92048),
    (1, 92051),
    (1, 92052),

    -- Brewfest
    (24, 91326),
    (24, 91328),
    (24, 91481),
    (24, 91482),
    (24, 91487),
    (24, 91488),
    (24, 91489),
    (24, 91490),
    (24, 91491),
    (24, 91492),
    (24, 91494),
    (24, 92045),
    (24, 92047),
    (24, 92048),
    (24, 92051),
    (24, 92052);
```

</details>

**Comment by Stump876** [comment]
FYI, still there during midsummer event. I'll edit after the event is over on CC to see if they despawn with decorations
