### ISSUE TITLE
Blasted Lands - Flying Gromsblood Node

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6398]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/883

Found a Gromsblood node chilling in the air:D
![Screenshot_24](https://user-images.githubusercontent.com/85901661/122369028-83378600-cf66-11eb-8e74-38f9e66df93d.png)

Tester's notes: Confirmed, Note that the GUID is NOT the one shown in the user's screenshot. That is a second, normal Gromsblood node that was just nearby. The correct GUID is 16504. It wasn't spawned when I visited, but teleporting to the node put me well above the ground, so that's confirmation.

![WoWScrnShot_061721_212750](https://user-images.githubusercontent.com/81782124/122392460-0aaae680-cfb3-11eb-85f2-b80e0f629f34.jpg)
![WoWScrnShot_061721_212815](https://user-images.githubusercontent.com/81782124/122392468-0bdc1380-cfb3-11eb-9467-173d0f98e998.jpg)
The green smoke is the location of the other node, 32304
![WoWScrnShot_061721_212820](https://user-images.githubusercontent.com/81782124/122392470-0c74aa00-cfb3-11eb-9678-de72c06dee5f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Plants can't fly

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go o 16504

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Related to https://github.com/azerothcore/azerothcore-wotlk/issues/6367  At first I thought it was a duplicate, but no. Apparently there are a lot of those in blasted lands.
