### ISSUE TITLE
Un'Goro Crater - Baron Charr and Guards Moving Too Quickly

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6399]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/885

Baron Charr (https://wowgaming.altervista.org/aowow/?npc=14461) and his guards are moving along their patrol path very fast

Tester: Confirmed. I could just barely overtake him in cheetah form (+40% speed), so he's going at something like +35% faster than normal run speed. Looking at Charr's speed_walk entry in the DB, it's set to 3.54 for some reason, a typical value is 1 to 2.5 or so. 

![WoWScrnShot_061721_213414](https://user-images.githubusercontent.com/81782124/122395399-1946cd00-cfb6-11eb-842e-1c8223fe5137.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Baron Char and his guards should move slower
https://www.youtube.com/watch?v=Ick6P28rIvc

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 247200
2. Go out of combat and observe his movement speed

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
this is the speed his guards should have so 1 and 1 
![image](https://user-images.githubusercontent.com/40864460/122426126-484a4800-cf90-11eb-8abf-541e767cc8e0.png)

I don't have any data for the baron

**Comment by Azcobu** [comment]
Cheers, is that from TC or something? 

The Blazing Invaders are escorting the Baron, so 1/1 for him as well sounds reasonable I guess.

**Comment by T1ti** [comment]
it's from sniffs from official classic
