### ISSUE TITLE
Sometimes when you create a character it will not show in character select screen.

### ISSUE THREAD

**Issue by lineagedr** [azerothcore/azerothcore-wotlk#640]
**Description**:
Sometimes when you create a character it will not show in character select screen. untill you refresh realmlist.
**Current behaviour**: Tell us what happens
Sometimes when you create a character it will not show in character select screen. untill you refresh realmlist.
**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. It happens sometimes
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
mastter
**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/9d2395e1d379e539bd6da0138cb425532c848cb6
**Operating system**:  
Win64
**Modules**:  Are you using modules? if yes, list them
None
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by StygianTheBest** [comment]
I've created at least a hundred characters on two different clients during my tests and I've never seen this issue.

**Comment by Viste** [comment]
@StygianTheBest its a character migration tool bug )

**Comment by Viste** [comment]
I have fix for sunwell but need test it for AC

**Comment by lineagedr** [comment]
@Viste When was it fixed in AC?

**Comment by Viste** [comment]
@lineagedr in this week i guess

**Comment by lineagedr** [comment]
> I have fix for sunwell but need test it for AC

@Viste Can you show?

**Comment by lineagedr** [comment]
Found what was causing it: In worldserver.conf

CharDatabasaWorkerThreads was set ot 5

CharacterDatabase.WorkerThreads = 5

After changing it to 1 never experienced this issue again.
