### ISSUE TITLE
Warrior - Intercept damage & stun can be dodged

### ISSUE THREAD

**Issue by anguaive** [azerothcore/azerothcore-wotlk#6400]
Original report: https://github.com/chromiecraft/chromiecraft/issues/864

Can confirm, if the target dodges the caster still charges towards it, but no damage is done and the target doesn't get stunned. Tested dodge only but I assume parrying and blocking works the same way. Same applies to the Charge spell.

 intercept getting dodged/parried and target doesn't get stunned anymore

#### WHAT CLIENT DO YOU PLAY ON?

- [x] enUS

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
 https://wotlk.evowow.com/spell=20252

intercept sometimes gets dodged/parried in pvp. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

intercept should not be dodged/parried or blocked by players or mobs, because it is **NOT** a melee attack.

##### STEPS TO REPRODUCE THE PROBLEM:

1. intercept an enemy player multiple times, sometimes they will dodge/parry as shown in the screenshot

##### EXTRA NOTES:

I haven't noticed dodges on charge yet, but will update it if I do
![Screenshot_21](https://user-images.githubusercontent.com/85901661/121946355-84499700-cd5d-11eb-87a1-81e0025b24ce.png)
![Screenshot_5](https://user-images.githubusercontent.com/85901661/121973441-e5856080-cd85-11eb-88f1-3cd407834b9b.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by laasker** [comment]
i think its because of https://github.com/azerothcore/azerothcore-wotlk/pull/5298
also, it is going through Deterrence if remember correctly

**Comment by T1ti** [comment]
test removing the custom spell_dbc changes that were done before to those abilities
