### ISSUE TITLE
Warrior/Priest Disarm Abilities Ineffective vs Ranged NPCs

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6404]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/886

After disarming NPC, they would lose their ability to use the main hand and ranged weapon.
When disarming NPC that has ranged weapon, they use their hands to fire their ranged weapon to do ranged damage.

Tester: confirmed. Ranged NPCs continue to use ranged abilities and special attacks even after being disarmed, and make no attempt to close to melee. Also note the priest ability Psychic Horror also suffers from this problem. Psycic Horror specififcally mentions that it disarms ranged weapons in the tooltip, but it doesn't stop ranged mobs from shooting arrows.
 
https://user-images.githubusercontent.com/81782124/122405466-3b911880-cfbf-11eb-9c18-ce8013364a1f.mp4

Screenshot showing a Beastmaster shooting 3 times and using a special ability while Psychic Horror had them disarmed. Note that the first line that says "Psychic Horror dissipates..." is referring to the fear/cower effect, not the disarm effect. The disarm ending is the second line.
![WoWScrnShot_061821_205913](https://user-images.githubusercontent.com/81782124/122554403-14e2e880-d078-11eb-91d5-f12a6da00415.jpg)

However, Disarm does work against other players. Here's the result of trying it in a duel:

![WoWScrnShot_061721_225340](https://user-images.githubusercontent.com/81782124/122405861-8ad74900-cfbf-11eb-869d-dffcca03ca96.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

After disarming NPC that has ranged weapon, they should move towards the aggro holding player to hit them with fists.

Wowpedia notes that as of patch 3.1.0 (2009-04-14): Disarm now disarms ranged weapons as well. 

##### SOURCE:

https://wowpedia.fandom.com/wiki/Disarm?oldid=2392024

##### STEPS TO REPRODUCE THE PROBLEM:

1. Find any mob that has a ranged weapon. Scarlet Monastery Libary for example has few ranged mobs right at the start of the dungeon.
2. Disarm them 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by claudiodfc** [comment]
Doesn't surprise me since NPCs don't use weapons, they are there for display purposes but use spells instead.

**Comment by Azcobu** [comment]
Yes, that seems likely to be the root cause of the problem. But however the attacks are implemented in the game engine, they should still temporarily stop once the NPC has been disarmed.

**Comment by claudiodfc** [comment]
not really, the server has to check for these spells and disable them on smartscripts

**Comment by Kitzunu** [comment]
Should be handled by core, not sai

**Comment by claudiodfc** [comment]
Yea that's what I meant, Smart scripts the c++ hooks that check for spell conditions

**Comment by T1ti** [comment]
seems to happen for melees too now
