### ISSUE TITLE
Close Silverleaf spawns in Durotar

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6409]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Spawning too close.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The plants should not be that close to each other.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Durotar, near Sen'Jin Village ( coordinates 55,7 // 68,6 aprox. )
2. See if there are Silverleaf herbs spawned too close.

##### EXTRA NOTES:

![WoWScrnShot_061721_223226](https://user-images.githubusercontent.com/82579073/122463206-ff10ed00-cfbd-11eb-8a60-c60a74becb29.jpg)
![WoWScrnShot_061721_223238](https://user-images.githubusercontent.com/82579073/122463257-1223bd00-cfbe-11eb-82e1-e46de1c03b46.jpg)
![WoWScrnShot_061721_223303](https://user-images.githubusercontent.com/82579073/122463316-236cc980-cfbe-11eb-9e01-067216c1c307.jpg)

##### AC HASH/COMMIT:

466cdb6

##### OPERATING SYSTEM:

Windows 10 21H1

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft & confirmed on AC

**Comment by Stump876** [comment]
We have a general link for this issue open [here](https://github.com/azerothcore/azerothcore-wotlk/issues/6264) if you just want to add to it.

**Comment by Eldarix** [comment]
Sorry pal, i'm not that technical, if you explain to me i'll do it, seems that i do only wrong things latelly ^^

**Comment by Eldarix** [comment]
We're all here trying to help, not making a doctorate, for you maybe that others do thousands things per day it's an inspiration, for me it's not and i'm happy doing my little contributions for now thanks :)
