### ISSUE TITLE
Zul'Farrak Gahz'Rilla Despawns in 3 seconds

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#6422]
**CURRENT BEHAVIOUR:**

NPC ID 7273 despawns instantly when killed.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Normal despawn time so you can loot body, take photos with friends, etc.

**SOURCE:**

https://classic.wowhead.com/npc=7273/gahzrilla#comments

**STEPS TO REPRODUCE THE PROBLEM:**

1. Kill Gahz'rilla
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

AzerothCore rev. 34da0cda5195 2021-06-15 

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by pangolp** [comment]
The truth is that I tried to reproduce the problem but I couldn't, the NPC was more than 3 minutes in front of me. I am using this commit: https://github.com/azerothcore/azerothcore-wotlk/commit/2ba258a88

![WoWScrnShot_061821_174407](https://user-images.githubusercontent.com/2810187/122614505-28348a80-d05d-11eb-97f2-4f2c993afdc8.jpg)

For a moment, it had a strange visual effect, as if it was sticking its head in the ground, but then, it would return to its original position.

![WoWScrnShot_061821_174254](https://user-images.githubusercontent.com/2810187/122614562-4601ef80-d05d-11eb-9bb1-cb4037faade7.jpg)

**Comment by claudiodfc** [comment]
Can't confirm either on commit AzerothCore rev. 483ecffcf449
![image](https://user-images.githubusercontent.com/54484196/123086835-cb99ec80-d41b-11eb-8ff1-0a9118c290c1.png)
