### ISSUE TITLE
Zul'Farrak Stairs Event NPC Dialogue Gossip Broken / Duplicated

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6425]
**CURRENT BEHAVIOUR:**

Zul'Farrak Stairs Event NPC Dialogue Gossip Broken / Duplicated

1x offered before it should be offered:

![WoWScrnShot_061821_203404](https://user-images.githubusercontent.com/61194190/122613867-778ab300-d07d-11eb-88a6-7fd97b2d47d1.jpg)

2x offered at end:

![WoWScrnShot_061821_204040](https://user-images.githubusercontent.com/61194190/122613844-6d68b480-d07d-11eb-88e3-8bcc028d880c.jpg)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Dialogue should work correctly and be available at the correct time (see video/event)

**SOURCE:**

https://www.youtube.com/watch?v=mtBuWdd2EHk

https://wowpedia.fandom.com/wiki/Zul%27Farrak

https://www.alteredgamer.com/wow-instances/7167-world-of-warcraft-zulfarrak-mini-guide-pt-3/

**STEPS TO REPRODUCE THE PROBLEM:**

1. Do Zul'Farrak Stairs
2. Observe dialogue available when stuck in cages
3. Observe double dialogue near end of event

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

AzerothCore rev. 34da0cda5195 2021-06-15 12:02:03 

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by avarishd** [comment]
@Kitzunu Fixed by #7855
![c97703366e6f3169b37face6c8d09371](https://user-images.githubusercontent.com/46330494/168463274-63370932-542d-458b-a4dd-edefbcdfba09.jpg)
![99d074d3b2919b05e9736e7c0580275e](https://user-images.githubusercontent.com/46330494/168463277-4829e610-17ae-4087-bbad-1ac92646b259.jpg)
