### ISSUE TITLE
Striped Nightsaber mount incorrectly tied to GCD

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6437]
Original Cromiecraft report https://github.com/chromiecraft/chromiecraft/issues/903

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Striped Nightsaber shares the global cooldown with skills/spells 
![image](https://user-images.githubusercontent.com/68164076/122651962-ece39b80-d0f0-11eb-897b-eba2e5fe9b71.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mounts should not share the GCD

##### SOURCE:

Compare this mount's behavior to various other mounts. No others share the GCD

##### STEPS TO REPRODUCE THE PROBLEM:

1. .set skill 762 75
2. .add item 8629 and 8631 learn both and place on cast the bar
3. Cast any instant spell which triggers the Global Cooldown. Blink for example.
4. Observer the Cooldown timer on the mount. If you try to use the Striped Nightsaber mount – you will get an error message saying it's not ready yet.
5. Repeat this test with various other mounts to observe the correct behaviour.

##### EXTRA NOTES:

N/A

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by avarishd** [comment]
Spells that are 78 (SPELL_AURA_MOUNTED) with StartRecoveryCategory (Global Cooldown Recovery) of 133 all observe the same behavior.

<details>
<summary> List </summary>

---
| id | spellname0 | StartRecoveryCategory | 
| ---: | --- | ---: | 
| 459 | Gray Wolf | 133 | 
| 471 | Palamino | 133 | 
| 578 | Black Wolf | 133 | 
| 579 | Red Wolf | 133 | 
| 581 | Winter Wolf | 133 | 
| 3363 | Nether Drake | 133 | 
| 6896 | Black Ram | 133 | 
| 6897 | Blue Ram | 133 | 
| 8980 | Skeletal Horse | 133 | 
| 10787 | Black Nightsaber | 133 | 
| 10788 | Leopard | 133 | 
| 10790 | Tiger | 133 | 
| 10792 | Spotted Panther | 133 | 
| 10793 | Striped Nightsaber | 133 | 
| 10795 | Ivory Raptor | 133 | 
| 10798 | Obsidian Raptor | 133 | 
| 29059 | Naxxramas Deathcharger | 133 | 
| 32345 | Peep the Phoenix Mount | 133 | 
| 32420 | Old Crappy McWeakSauce | 133 | 
| 42363 | Dan's Steam Tank Form | 133 | 
| 42387 | Dan's Steam Tank Form (Self) | 133 | 
| 42667 | Flying Broom | 133 | 
| 42668 | Swift Flying Broom | 133 | 
| 42680 | Magic Broom | 133 | 
| 42683 | Swift Magic Broom | 133 | 
| 42692 | Rickety Magic Broom | 133 | 
| 48023 | Headless Horseman's Mount | 133 | 
| 48024 | Headless Horseman's Mount | 133 | 
| 51617 | Headless Horseman's Mount | 133 | 
| 51621 | Headless Horseman's Mount | 133 | 
| 55293 | Amani War Bear | 133 | 
| 58819 | Swift Brown Steed | 133 | 
| 58997 | Big Blizzard Bear | 133 | 
| 58999 | Big Blizzard Bear | 133 | 
| 61289 | Borrowed Broom | 133 | 
| 61983 | Dan's Test Mount | 133 | 
| 64992 | Big Blizzard Bear [PH] | 133 | 
| 64993 | Big Blizzard Bear [PH] | 133 | 
| 66122 | Magic Rooster | 133 | 
| 66123 | Magic Rooster | 133 | 
| 66124 | Magic Rooster | 133 | 
| 71343 | Big Love Rocket | 133 | 
| 71344 | Big Love Rocket | 133 | 
| 71345 | Big Love Rocket | 133 | 
| 71346 | Big Love Rocket | 133 | 
| 71347 | Big Love Rocket | 133 | 
| 72281 | Invincible | 133 | 
| 72282 | Invincible | 133 | 
| 72283 | Invincible | 133 | 
| 72284 | Invincible | 133 | 
| 74854 | Blazing Hippogryph | 133 | 
| 74855 | Blazing Hippogryph | 133 | 
| 75617 | Celestial Steed | 133 | 
| 75618 | Celestial Steed | 133 | 
| 75619 | Celestial Steed | 133 | 
| 75620 | Celestial Steed | 133 | 
| 76153 | Celestial Steed | 133 | 

</details>
