### ISSUE TITLE
DB/Quest: The Battle For The Ebon Hold

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#644]
**Description**: 
-the knights of death with us do not attack enimies when they approach them.
-the abominations instantly throw their hooks

**Current behaviour**: Tell us what happens
-the knights of death with us do not attack enimies when they approach them.
-the abominations instantly throw their hooks

**Expected behaviour**: Tell us what should happen instead
-the DK must attack when enemies approching
-the abominations must cast their hook like video below
https://www.youtube.com/watch?v=QHWpZexZODY

**Steps to reproduce the problem**:
```
.go creature id 31084
.gm off
.mod phase 488 (use this even if you do .gm on and .gm off in a second time)
.quest add 13166
```
- Use the purple platform to go downstairs and do the quest

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by poszer** [comment]
Looks like wrong flags. Can you try to run this query and than test that quest @Maurowin 
```sql
UPDATE `creature_template` SET `unit_flags`='557056' WHERE  `entry`=31094;
```

**Comment by Maurowin** [comment]
@poszer Sorry I was not noticed for your replay, I'll test that tonight.

**Comment by Helias** [comment]
How to test properly:
```
.go creature id 31084
.gm off
.mod phase 488 (use this even if you do .gm on and .gm off in a second time)
.quest add 13166
```
- Use the purple platform to teleport you downstairs

I confirm the issue.

**Comment by Helias** [comment]
The fix proposed didn't work, I am creating a PR with another one.
