### ISSUE TITLE
Progression - Arena Season 6 Items Prematurely Available For Purchase

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6441]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/905

It is already possible on ChromieCraft to buy Arena Season 6 items (Furious Gladiator) from the pvp vendor at Gadgetzan.
In fact, you can buy Season 7 and 8 items, too, but those require Arena Points which we cannot get yet.
Links to the pvp vendors:
https://wotlk.evowow.com/?npc=34093
https://wotlk.evowow.com/?npc=33939
https://wotlk.evowow.com/?npc=33935
https://wotlk.evowow.com/?npc=33929

Tester: confirmed. As the original poster points out, this isn't actually an issue with AC but with CC. However, it ties into the progression system (see https://github.com/azerothcore/azerothcore-wotlk/issues/5861) so linking it accordingly.

![WoWScrnShot_062021_111221](https://user-images.githubusercontent.com/81782124/122659741-f4bb4280-d1b9-11eb-94d3-70129733ce1d.jpg)
![WoWScrnShot_062021_111227](https://user-images.githubusercontent.com/81782124/122659745-f5ec6f80-d1b9-11eb-9b11-1ba257617d59.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It works correctly for a 3.3.5a server. However, these items should not be obtainable yet on chromiecraft, because if we start the level 80 bracket with only naxx patch, that means only Deadly Gladiator (Season 5) items should be the highest ones available for purchase. In theory, one could already gather the honor points needed for the Furious Gladiator gear and buy it.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Gadgetzan
2.  Talk to the PVP vendors by the "arena" in the middle of the town.

##### EXTRA NOTES:

This is NOT an AzerothCore bug or a problem with other 3.3.5a servers, like I said it's only an oversight that should be addressed on ChromieCraft itself due to the way content is gradually unlocked.
I apologize if I should've reported a problem of such nature somewhere else.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Perhaps better to report it in the right repository https://github.com/azerothcore/progression-system

**Comment by Azcobu** [comment]
Done: https://github.com/azerothcore/progression-system/issues/18
