### ISSUE TITLE
Quest drops still visible after requirements fulfilled

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6442]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/902

##### CURRENT BEHAVIOUR:

After collecting all required quest items from mobs, those items will incorrectly continue to drop (or remain visible) under two circumstances: (a) the player's quest items are in their bank; (b) the player killed multiple mobs before looting.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once a player has collected all dropped items for a quest (even if they are stored in the bank), they should never see extra copies of these items on mobs. These extra item drops should also not prevent skinning.

##### SOURCE:

I've looked for a while and I'm not sure I can find a source for this one. AoE videos either don't show looting, or they've already completed the relevant quests prior to filming. Most players don't usually store quest items in their bank, but the progressive level cap on ChromieCraft is a unique circumstance. Having played multiple AoE classes (which would encounter this specific situation regularly) throughout various retail expansions including 3.3.5, I can't recall having ever encountered this issue on an official server. This is absolutely a bug, but not an urgent one.

Players with skinning can work around this issue by deleting a quest item from their bag, looting the mob, and then skinning it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Accept any quest to collect drops from mobs, especially skinnable mobs (e.g. Singing Blue Shards from Crank Fizzlebub in Booty Bay).
2. Collect all but one of the required items (e.g. 9/10).
3. Kill multiple mobs before looting any. You should see extra items, but be unable to loot them after fulfilling the quest requirement (this incorrectly prevents skinning).
4. Put all these quest items in your bank and continue killing the same mobs. You should be able to incorrectly collect additional quest items.

##### EXTRA NOTES:

This appears to affect a large number of quests; although there a handful of specific quest issues listed here on github, I did not see a generic bug report for all quest drops. Apologies if this is a known issue.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 466cdb6) :

![WoWScrnShot_062021_053228](https://user-images.githubusercontent.com/82579073/122660493-b9ede600-d18a-11eb-85c0-e9a7b05fba79.jpg)
![WoWScrnShot_062021_053427](https://user-images.githubusercontent.com/82579073/122660496-cbcf8900-d18a-11eb-8da1-48278604ba62.jpg)
![WoWScrnShot_062021_053444](https://user-images.githubusercontent.com/82579073/122660501-db4ed200-d18a-11eb-963e-0bc1111a9ec9.jpg)
![WoWScrnShot_062021_053612](https://user-images.githubusercontent.com/82579073/122660506-ebff4800-d18a-11eb-866b-0059d1ce6fc6.jpg)
![WoWScrnShot_062021_053732](https://user-images.githubusercontent.com/82579073/122660534-f883a080-d18a-11eb-9c73-fb996cce0393.jpg)
![WoWScrnShot_062021_053737](https://user-images.githubusercontent.com/82579073/122660550-0afdda00-d18b-11eb-9b52-8291ed9f2048.jpg)

**Comment by T1ti** [comment]
pretty sure b is blizzlike, that happens all the time on classic

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/122662176-3aafe080-d191-11eb-8130-f4f07bc5dafc.png)
this is what happens on classic with b), it's still in their loot but red

**Comment by T1ti** [comment]
seems like you are right for a) though 
![image](https://user-images.githubusercontent.com/40864460/122662456-67fd8e00-d193-11eb-93cb-05e2ceebb097.png)

I only looted a bunch of empty tigers

**Comment by UltraNix** [comment]
@T1ti About b) - so in that case that item in in the corpse, so player cannot skin?

**Comment by FrancescoBorzi** [comment]
ping @T1ti

**Comment by UltraNix** [comment]
@T1ti Are you there?

**Comment by FrancescoBorzi** [comment]
Earth calls @T1ti

**Comment by T1ti** [comment]
I'll test it

**Comment by T1ti** [comment]
> @T1ti About b) - so in that case that item is in the corpse, so player cannot skin?
> And one more question - quest can be completed by items in bank?

- yeah can't skin it, it has loot though you can just delete  in your inventory, loot it and skin
- can't complete with items in banks

**Comment by UltraNix** [comment]
So:
In case A: items should not be visible (and then mob is not skinnable?)
In case B: items should be red and then mob is not skinnable

**Comment by T1ti** [comment]
> So:
> In case A: items should not be visible (and then mob is not skinnable?)
> In case B: items should be red and then mob is not skinnable

no, for A they are lootable, but empty. Once you loot them and close the loot menu, they appear as if they have no loot after (and are now skinnable)

**Comment by UltraNix** [comment]
Okay.
