### ISSUE TITLE
server crash log

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6443]
**CURRENT BEHAVIOUR:**
server crash 

**STEPS TO REPRODUCE THE PROBLEM:**
I don't know how to reproduce it,It crash in about 4-6 hours

**EXTRA NOTES:**
[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6681692/gdb.txt)

**AC HASH/COMMIT:**
8519429e4603776be63357259c81983a69c41534
(pr 6378)
**OPERATING SYSTEM:**
ubuntu 20.04
**MODULES:**
mod-anticheat
mod-multi-client-check-master

**Comment by mpfans** [comment]
@UltraNix  please help me!

**Comment by UltraNix** [comment]
@mpfans You ask - you got.

**Comment by mpfans** [comment]
new crash log
[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6687966/gdb.txt)

**Comment by UltraNix** [comment]
@mpfans Create a new topic.
