### ISSUE TITLE
Stonetalon - Sentinel Amarassan Missing Patrol Pattern

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6451]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/918

Sentinel Amarassas (https://wowgaming.altervista.org/aowow/?npc=5916) is missing her patrol pattern, she is stationary.

![standing](https://user-images.githubusercontent.com/80769357/122670451-67c8b700-d1c2-11eb-9f81-c970388f5bb2.jpg)

Tester: confirmed. She doesn't even randomly wander, just stands there.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

She should be patroling as per comment: "She walks back and forth along the path to The Talon Den (dotted line path on the map)" - https://tbc.wowhead.com/npc=5916/sentinel-amarassan#comments:id=222936

"Sentinel Amarassan was a level 27 elite rare mob night elf found in southern Stonetalon Peak in the Stonetalon Mountains. She could be found patrolling the route between the ruins at the center of Stonetalon Peak and the entrance to Talon Den." - https://wowpedia.fandom.com/wiki/Sentinel_Amarassan

##### SOURCE:

https://wowpedia.fandom.com/wiki/Sentinel_Amarassan

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to Sentinel Amarassan (GUID 51888)
2. Observe her stationary nature

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by damnablebear** [comment]
Confirming that this is still an issue as of 8/29/2023.
