### ISSUE TITLE
Crash in SpellMgr.h

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#6452]
```
Thread 16 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f9c1f5f7700 (LWP 11295)]
0x00000000012d3252 in Acore::Assert (file=0x13bb99e "/root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/SpellMgr.h", line=690, function=0x13bb9e9 "AssertSpellInfo", debugInfo=..., message=0x13bb9f9 "spellId < GetSpellInfoStoreSize()") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:64
64	        Crash(formattedMessage.c_str());
#0  0x00000000012d3252 in Acore::Assert (file=0x13bb99e "/root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/SpellMgr.h", line=690, function=0x13bb9e9 "AssertSpellInfo", debugInfo=..., message=0x13bb9f9 "spellId < GetSpellInfoStoreSize()") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:64
#1  0x00000000005c2317 in SpellMgr::AssertSpellInfo (this=<optimized out>, spellId=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/SpellMgr.h:690
#2  0x000000000054bb0f in Player::RemoveArenaSpellCooldowns (this=0x7f9bb6e1c6c0, removeActivePetCooldowns=true) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Player/Player.cpp:4418
#3  0x000000000054abe2 in Player::TeleportTo (this=0x7f9bb6e1c6c0, mapid=559, x=4027.6001, y=2972.78003, z=12.0723, orientation=0, options=0, target=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Player/Player.cpp:2437
#4  0x00000000007c4313 in WorldSession::HandleBattleFieldPortOpcode (this=0x7f9be2718200, recvData=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/BattleGroundHandler.cpp:469
#5  0x00000000008f380c in WorldSession::Update (this=0x7f9be2718200, diff=10, updater=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:348
#6  0x0000000000ab89e1 in World::UpdateSessions (this=0x7f9c78888000, diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/World/World.cpp:2727
#7  0x0000000000ab64f7 in World::Update (this=0x7f9c78888000, diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/World/World.cpp:2259
#8  0x00000000004572e1 in WorldRunnable::run (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/WorldThread/WorldRunnable.cpp:48
#9  0x00007f9c7b22cd84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f9c7b346609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f9c7af1a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
8451358.841125 [Thread debugging using libthread_db enabled]
8451358.841136 Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
```

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Passing a SpellID that is not 100% valid which is weird because why would RemoveArenaSpellCooldowns try to remove a spell that is not valid

**Comment by Kitzunu** [comment]
Do you have any more information about what class was in the arena?

We need to debug RemoveArenaSpellCooldowns

**Comment by Kitzunu** [comment]
Maybe time to also port https://github.com/TrinityCore/TrinityCore/commit/e70790576414dde16b56fd828d52a79ef540d3e9 to allow rewriting RemoveArenaSpellCooldowns
