### ISSUE TITLE
Warrior - Intercept/Charge Issues

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6453]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/917

If you use charge on target A then intercept target B while still charging to target A, target B will just take damage/get stunned, but your character will remain in the position of your first target.

Demo here: https://youtu.be/KqYU27mvCCA

Tester: confirmed, going both ways. First, charge then intercept:

https://user-images.githubusercontent.com/81782124/122675233-ab99db80-d217-11eb-8505-d3203ff6597f.mp4

Then using the second macro, intercept then charge. Sorry for the horrible crash zoom, but charge doesn't produce a nice visible damage number, only a swirly stun animation, and needed to make sure that was visible.

https://user-images.githubusercontent.com/81782124/122675340-177c4400-d218-11eb-83db-e78c4b02eb81.mp4

Note there has been some work done on Charge/Intercept recently in https://github.com/azerothcore/azerothcore-wotlk/pull/6421, but that doesn't seem to be related, it was about making them impossible to dodge/parry/block.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This should not happen.
Every time you charge/intercept a target, your character must start charging towards that target.

##### SOURCE: 

don't think I need a source for this, it's pretty obvious it's not working as intended.

##### STEPS TO REPRODUCE THE PROBLEM:

1. You need 2 dummies in a straight line Dummy A and Dummy B
2. Set Dummy A as your focus target (target it and type /focus)
3. Target Dummy B, be in Battle Stance and spam this macro, it should be really easy to reproduce the bug 

/cast [@focus] Charge
/cast berserker stance
/cast intercept

##### EXTRA NOTES:

Can't test if the same happens if you reverse the spell order because I don't have the Juggernaut talent to be able to charge in combat, so please make sure you test that too.
To do that, learn bloodrage ability and use this macro

/cast [@focus] intercept
/cast battle stance
/cast charge

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by disclosurez** [comment]
confirmed issue
