### ISSUE TITLE
Divine Shield and Avenging Wrath are not activating Forbearance!!

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6468]
**CURRENT BEHAVIOUR:**
When you use the spell Divine Shield or Avenging Wrath none of them are activating Forbearance, so you can use both spells at the same time.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
When you use Divine Shield you get a buff called Forbearance that doesn't let you use Avenging Wrath for 30 seconds, and divine protection or hand of protection for 2 minutes.
The same is true when using Avenging Wrath.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Train spells (paladin)
2. Use Avenging Wrath or Divine Shield
3. The Forbearance buff won't appear, so you can use Divine Shield and Avenging Wrath at the same time.

**EXTRA NOTES:**

**AC HASH/COMMIT:**

> 5787d00d545a

**OPERATING SYSTEM:**
Windows

**MODULES:**
Mod-Anticheat
Mod-BgReward
Mod-CFBG
Mod-Eluna-Lua-Engine
Mod-PvpTitles
Mod-NpcBeastmaster
Mod-Transmog

**CUSTOMIZATIONS:**

**Comment by Stump876** [comment]
Thanks for the report. Actually I'm unable to duplicate this. Are there any other details you might have overlooked? Do you have a screenshot or video of this happening by chance? 
The spell [avenging wrath](https://wowwiki-archive.fandom.com/wiki/Avenging_Wrath_(retribution)) does not cause forbearance. That was removed in 3.0.8  However, it cannot be used within 30 seconds of [Divine Shield](https://wowwiki-archive.fandom.com/wiki/Divine_Shield) or [Divine Protection](https://wowwiki-archive.fandom.com/wiki/Divine_Protection). Both of which do cause forbearance 
![image](https://user-images.githubusercontent.com/68164076/122715907-72189e80-d21e-11eb-827b-60ba677a0c05.png)
![image](https://user-images.githubusercontent.com/68164076/122716023-970d1180-d21e-11eb-83d9-3af7983fbe92.png)
I tried all ranks of Divine Protection

**Comment by WillzDevs** [comment]
> Thanks for the report. Actually I'm unable to duplicate this. Are there any other details you might have overlooked? Do you have a screenshot or video of this happening by chance?
> The spell [avenging wrath](https://wowwiki-archive.fandom.com/wiki/Avenging_Wrath_(retribution)) does not cause forbearance. That was removed in 3.0.8 However, it cannot be used within 30 seconds of [Divine Shield](https://wowwiki-archive.fandom.com/wiki/Divine_Shield) or [Divine Protection](https://wowwiki-archive.fandom.com/wiki/Divine_Protection). Both of which do cause forbearance
> ![image](https://user-images.githubusercontent.com/68164076/122715907-72189e80-d21e-11eb-827b-60ba677a0c05.png)
> ![image](https://user-images.githubusercontent.com/68164076/122716023-970d1180-d21e-11eb-83d9-3af7983fbe92.png)
> I tried all ranks of Divine Protection

Hello, here are the photos of the 2 spells, None of them activating Forbearance:
![image](https://user-images.githubusercontent.com/67213916/122774386-82ad3100-d27f-11eb-8314-67ac52480949.png)
![image](https://user-images.githubusercontent.com/67213916/122774440-8f318980-d27f-11eb-8a7e-c893a65d120d.png)
![image](https://user-images.githubusercontent.com/67213916/122774499-9c4e7880-d27f-11eb-9ff8-48fcf0d2a324.png)

**Comment by Sedatyf** [comment]
@WillzDevs Are you sure this is the correct hash/revision of your server?
Are you sure you're using the right spells? Some spells are wrong because of wrong spell ids

Furthermore, we have a lot of paladins in CC, I think this bug would have been reported by now. 
Can you give us more information on how you reproduce this?

**Comment by WillzDevs** [comment]
> @WillzDevs Are you sure this is the correct hash/revision of your server?
> Are you sure you're using the right spells? Some spells are wrong because of wrong spell ids
> 
> Furthermore, we have a lot of paladins in CC, I think this bug would have been reported by now.
> Can you give us more information on how you reproduce this?

Hello yes I have ctz which is the latest version, I updated yesterday.
And the spell is right, the way I reproduce it is the one I reported

![image](https://user-images.githubusercontent.com/67213916/122776710-b9844680-d281-11eb-9c4c-5c510a19bd40.png)

**Comment by HannibalRoG** [comment]
@WillzDevs you use a gm account, maybe that is the problem.

**Comment by Sedatyf** [comment]
I tested it on my Paladin on Chromie Craft, and every shield give me Forbearance. Avenger Wrath doesn't give forbearance. So I think I will close this

**Comment by WillzDevs** [comment]
> I tested it on my Paladin on Chromie Craft, and every shield gave me Forbearance. Avenger Wrath doesn't give forbearance. So I think I will close this

my dear, you're right, corrected, but forgot to close the issue...thanks a lot @Sedatyf my dear, you're right, corrected, but forgot to close the issue...thanks a lot @Sedatyf my dear, you're right, corrected, but forgot to close the issue...thanks a lot @Sedatyf
