### ISSUE TITLE
Midsummer fest double spawning NPC's

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6469]
Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/928

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There are a lot of NPC's double spawning for the fire festival event. Anyone can feel free to add to this as they encounter more. 
Additionally some humans are labeled as "Goblin Commoner" and have beer mugs and talk about gathering colored eggs. as well as goblins with human masks with beer mugs saying the same thing. I don't think these should be spawned at all. This is all kinds of incorrect. (second screenshot)
![image](https://user-images.githubusercontent.com/68164076/122705301-48ee1300-d20a-11eb-8a8c-29cbb756da00.png)
![image](https://user-images.githubusercontent.com/68164076/122705364-6a4eff00-d20a-11eb-9095-4add6eab12d3.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should not be doubled up. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wild shore Area, Stranglethorn Vale: .go creature: 96711, 23791, 16412, 94603, 94550, 94555, 94551, 16433, 94553, 94552, 94786, 94781, 94694, 94653, 94656, 94693, 94489, 94518, 94654, 94711, 94710, 94655
2. Booty Bay (these are general "Goblin commoner" with mugs and talking about gathering eggs, sometimes there are three: .go creature: 93646, 93762, 93763, 93652, 725, 93587, 93913, 724, 93764, 16433, 727, 93734, 93639, 726, 93610, 
3. Burning Steppes: .go creature: 245649, 248581

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
Also https://github.com/chromiecraft/chromiecraft/issues/935

**Comment by Stump876** [comment]
Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/936 and https://github.com/chromiecraft/chromiecraft/issues/937

Darnassus:
GUID 94747, 94739

Arathi Highlands:
GUID 94704, 94636
GUID 94556, 94637
GUID 94635, 94557
GUID 94634, 94605

**Comment by Azcobu** [comment]
Further instances:

Mulgore: reported in https://github.com/chromiecraft/chromiecraft/issues/940
GUID 248583, 245692 - also Mulgore is missing tents and braziers

Azuremyst Island: reported in https://github.com/chromiecraft/chromiecraft/issues/942
GUID 248584, 245645 - other midsummer festival NPCs are missing/not spawned

Bloodmyst Isle: reported in https://github.com/chromiecraft/chromiecraft/issues/943
GUID 245648, 248585 - missing tent and other npcs

Feralas - Feathermoon Stronghold: reported in https://github.com/chromiecraft/chromiecraft/issues/944
There is an additional set of Festival Decorations and NPC (GUID 248582) at the Forgotten Coast (46.6,44.2), but no fire.
At the correct location east of Feathermoon Stronghold, some decorations are missing, but the fire is in place.

Silithus: reported in https://github.com/chromiecraft/chromiecraft/issues/945
GUID 94649, 94575
GUID 94697, 94738
GUID 86704, 86716
GUID 94580, 94700
GUID 94579, 94699

**Comment by gurveleg** [comment]
I checked Outland Midsummer locations on local AC so they can be fixed too when working on fixing the old world locations - or they'll be brought up next time when TBC is unlocked on Chromiecraft and Midsummer active:

Zangarmarsh:
Alliance: Double Flame Warden GUID 245669, 248589, Missing other NPCs and Decorations

Nagrand:
Alliance: Double Flame Warden GUID 245660, 248590, Missing other NPCs and Decorations

Terrokar Forrest:
Alliance: Double Flame Warden GUID 245664, 248586, Missing other NPCs and Decorations

Shadowmoon Valley:
Alliance: Double Flame Warden GUID 245662, 248588, Missing other NPCs and Decorations

Horde: Double Flame Warden GUID 245694, 248587, Missing other NPCs and Decorations

Blades Edge Mountains:
Alliance: Double Flame Warden GUID 248591, 245646, Missing other NPCs

Horde: Double Flame Warden GUID 245682, 248592, Missing other NPCs

Netherstorm:
Horde: Double Flame Warden GUID 245675, 248594, Missing other NPCs and Decorations

Alliance: Double Flame Warden GUID 245670, 248593, Missing other NPCs and Decorations


AzerothCore rev. 3b58f5602928
