### ISSUE TITLE
Incorrect gold rewards for fire festival 

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6470]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/929

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

It seems like the reward scales per zone, not per level, 
Rewards in Goldshire at 1 and 80 (including max level gold bump) GUID 245655
![image](https://user-images.githubusercontent.com/68164076/122711258-bef87700-d216-11eb-8f98-db326a4895b4.png)

![image](https://user-images.githubusercontent.com/68164076/122711164-91abc900-d216-11eb-9375-3b7fe70fbdba.png)

Rewards in Stranglethorn at level 1 and 80 (including max level gold bump) GUID 245672, and 245677
![image](https://user-images.githubusercontent.com/68164076/122708903-147e5500-d212-11eb-895d-5aafda2572a1.png)
![image](https://user-images.githubusercontent.com/68164076/122710806-e3078880-d215-11eb-86a6-a99f1cf73e54.png)

Rewards at level 1 and 80 (including max level gold bump) in Burning steppes GUID's 245683, and 245649
![image](https://user-images.githubusercontent.com/68164076/122710589-75f3f300-d215-11eb-9b1a-e588bc0fc1ce.png)

![image](https://user-images.githubusercontent.com/68164076/122710131-83f54400-d214-11eb-9fbb-596a2bd90143.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I can't find exactly how it should scale fore a level 1, but https://www.wowhead.com/news/midsummer-fire-festival-2009-june-21-july-5-quest-guide-information-103454 "If you visit one of your faction's bonfires, you can speak to the nearby Flame Keeper (or Flame Warden) to Honor the Flame, which will reward you with Burning Blossom x5 and 6G 63S at level 80. If you visit one of the opposing faction's bonfires, you can right-click to Desecrate this Fire!, which will extinguish the flame and will reward Burning Blossom x10 and 13G 23S at level 80." I tried a few fires in Northrend and it looks like the max gold matches Burning Steppes' But if a low level can manage to get to a fire in a higher level zone it would give more gold. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Experiment with different fires and see gold differences per zone. GUIDs for the flame keepers of ones I checked are above.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
Everything works here okay. This is not the same quest, but different quests on different levels - that's why you can see different amount of gold contains in reward list when you accept the quest.
