### ISSUE TITLE
Thousand Needles - Quest "Free at Last" Missing Final NPC Dialog

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6471]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/922

At the end of the escort quest "Free at Last" ( https://wowgaming.altervista.org/aowow/?quest=4904 ), Lakota Windsong leaves without saying anything, once you reach the end of the escort path.

Tester: confirmed. 

Screenshot of her doing nothing but fade away:
![WoWScrnShot_062121_201107](https://user-images.githubusercontent.com/81782124/122750204-61733180-d2cd-11eb-9d06-93b96211bc1e.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Lakota should say thanks and tell you that she can go back home by herself: https://youtu.be/iQQBpUo49LI?t=4151
You can see the dialog text in the chat window (this is from retail Classic WoW).

Lakota: Finally, free at last... I must be going now, thanks for helping me escape. I can get back to Freewind Post by myself.

##### SOURCE:

https://youtu.be/iQQBpUo49LI?t=4151
You can see the dialog text in the chat window (this is from retail Classic WoW).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Lakota Windsong ( ".go creature 21594").
2. Do the escort quest.
3. See her leave without saying thanks.

##### EXTRA NOTES:

N/A

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by vtihomirov** [comment]
Here a source video from TBC Classic: https://youtu.be/0ws5JMRDulk
