### ISSUE TITLE
[PVP BUG] Feral charge share same DR of Entangling Roots

### ISSUE THREAD

**Issue by cbanovanta** [azerothcore/azerothcore-wotlk#648]
**Description**:When a druid use the **Feral Charge** it will reduce the time of the next Entangling Roots and the Feral Charge Effect too is already with DR.

**Current behaviour**: The first **Entangling Roots** hit the target for **9** seconds, the **Feral Charge** (for bug already got the DR) instead **4** seconds is of **2** seconds, and at this point the **next Entangling Roots** is only **2** seconds instead **4** seconds so the 3th cast will be already "immune" on the target.

**Expected behaviour**: **The Feral Charge should not create DR with Entangling Roots** and the time of those controls is: Entangling Roots: 9s , Feral Charge Effect: 4s , Entangling Roots: 4s , Entangling Roots: 2s: Entangling Roots: Immune

**Steps to reproduce the problem**:

1. Cast EntanglingPRoots on a Player 
2. Use Feral Charge on the Player
3. Cast again Entangling Roots on the Player

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hashNo modified was applied on AzerothCore AzerothCore

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Maurowin** [comment]
we need to known AC hash.
It's like azerothcore rev. 994fczef68464 on your promp command when you lunch authserver or worldserver

**Comment by lineagedr** [comment]
Confirm.

**Comment by lineagedr** [comment]
Also: this fix works for me https://github.com/Looking4Group/L4G_Core/commit/92dfcc58267060ac13de8fe457f2e1371548c9c5

**Comment by ShinDarth** [comment]
@lineagedr good, it would be nice if you can open a PR with that fix (remember to give credit to the original author as well).

**Comment by Inifield** [comment]
Maybe consider some kind of generic solution
