### ISSUE TITLE
Core/Spell: Nature's Grasp replace the Entangling Roots.

### ISSUE THREAD

**Issue by cbanovanta** [azerothcore/azerothcore-wotlk#649]
**Description**:
Entangling Roots is released from Nature's Grasp. Nature's Grasp got 3 stacks and each of those stack will afflicts the Player that hit the Druid, with Entangling Roots.

Of Course Entangling Roots got DR like the whole other Controls in the game.

The malfunctions of this talent  follows:

1. Entangling Roots, released from Nature's Grasp, if already up on the Player that hit the Druid should not be replaced from the second Entangling Roots if the duration of the first Roots is still more than the second Roots with DR.  The duration of each stack with dr is: 9s 4s 2s.

2. Judgement of Paladins should not activate Entangling Roots by hit the druid while under effect of Nature's Grasp.

**Current behaviour**: Nature's Grasp when is up and someone Player hit the druid fast it will afflicts the damage dealer with Entangling Roots and when he hit again the 9 seconds Entangling Roots will be replaced istant with the second Entangling Roots of 4 seconds and if hit again will be replaced another time with the tirdh of 2 second

**Expected behaviour**: When the Entangling Roots on the Player that hit the Drood is more than 4 seconds should not be replaced from the second Roots and the last will not replace the second stack or the first stack if is more than 2 seconds. Nature's Grasp still will consume the stacks even if the entangling roots  dont replace the before one.

**Steps to reproduce the problem**:

1. Acrivate Nature's Grasp
2. Hit the Druid
3.Entangling Roots will be replaced by the next Roots

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/8d6207430fe4105970d1e42b90b4c5333173a916

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
@cbanovanta please add the commit hash

**Comment by lineagedr** [comment]
@cbanovanta So it should never consume a stack if the attack already has been rooted?

**Comment by cbanovanta** [comment]
yes it will consume a stack but the entangling roots just will be replaced from another entangling roots just if is being dispelled so not anymore on the attack or if the second entangling that should be of 4 second is more thant the first that already is 3 second for example.

**Comment by lineagedr** [comment]
@cbanovanta Like this or? https://www.youtube.com/watch?v=BYo40_MSdq4  It will be really useful if you can provide a video of how it should work. Or try to explain it better.

**Comment by cbanovanta** [comment]
i can make a video soon

**Comment by lineagedr** [comment]
@cbanovanta How soon? Also Judgement of Paladins should proc nature's grasp.

**Comment by cbanovanta** [comment]
http://178.33.198.169/check-commit.php is the commit hash

**Comment by cbanovanta** [comment]
https://www.sendspace.com/file/ho4087 
This is how works on Azeroth with bugs.

**Comment by cbanovanta** [comment]
https://www.sendspace.com/file/hy67jz
This is how works without any bugs.

**Comment by ShinDarth** [comment]
@cbanovanta that's not the hash commit, that's a web page that **contains** the hash commit. You should copy and paste it when you report an issue, because the values in the page will change with time and we need the exact revision number of the core when you tested

**Comment by cbanovanta** [comment]
8d6207430fe4105970d1e42b90b4c5333173a916

**Comment by lineagedr** [comment]
@cbanovanta Is this correct? https://www.youtube.com/watch?v=_OKFxsJAvaI

**Comment by cbanovanta** [comment]
no is not correct because the last stack should apply a new entangling roots, because the first of 9 second is ok the second one will just be wasted cuz is already up the first one that still got 5 second left, so cant be replaced from the 4 second roots, but the last instead of 2 second will be of 4 second because is the third that got dr with the first now. so when the first will be with 2 second left the last nature grasp stack will apply the 4 second roots

**Comment by cbanovanta** [comment]
is different when u will dispel it or hit slow that will be first stack 9 sec second stack 4 sec third 2 sec

**Comment by cbanovanta** [comment]
and guess a miss should not consume stacks giving to the paladin the entangling roots

**Comment by lineagedr** [comment]
@cbanovanta This? https://www.youtube.com/watch?v=uZBTI43vr8Q

**Comment by lineagedr** [comment]
@cbanovanta This? https://www.youtube.com/watch?v=FGK2UKRPMl4

**Comment by cbanovanta** [comment]
yes ;)

**Comment by cbanovanta** [comment]
what about judgement? is not melee solved that too?

**Comment by lineagedr** [comment]
@cbanovanta 
Blizzard Patch Notes: http://us.battle.net/wow/en/game/patch-notes/3-2-0

Judgements: Some of these attacks were considered ranged and some melee. They are all now considered melee attacks that can’t be dodged, parried or blocked.

**Comment by cbanovanta** [comment]
Never saw it got the roots in 1 server before ;)

**Comment by BarbzYHOOL** [comment]
Add the hash in the initial ISSUE, not in the comments, please. Thank you for reporting.

**Comment by Inifield** [comment]
@lineagedr Could you submit a PR please

**Comment by lineagedr** [comment]
https://github.com/TrinityCore/TrinityCore/commit/5e2c5a52cd8a4ce12e189034df66b42d0d0b2c01

**Comment by shaszun** [comment]
It's still not replacing it or the bug just changed a bit. Currently you can apply 2 roots doing double damage this way. You either cast Nature's Grast first and then cast Roots or vise verse. It should replace the previous roots.

https://imgur.com/bhabDn3
