### ISSUE TITLE
new server crash  [$30]

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6491]
CURRENT BEHAVIOUR:
server crash

STEPS TO REPRODUCE THE PROBLEM:
I don't know how to reproduce it,It crash in about 4-6 hours

EXTRA NOTES:
[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6690206/gdb.txt)

AC HASH/COMMIT:
47b09f27671d9d04e86cfc996085207c8b5ac177

OPERATING SYSTEM:
ubuntu 20.04
MODULES:
mod-anticheat
mod-multi-client-check-master

**Comment by mpfans** [comment]
@UltraNix  tyvm

**Comment by mpfans** [comment]
[1.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699090/1.txt)
[2.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699091/2.txt)
[3.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699092/3.txt)
[4.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699093/4.txt)
[5.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699094/5.txt)
[6.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699095/6.txt)
[7.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699096/7.txt)
[8.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699097/8.txt)
[9.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699099/9.txt)
[10.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699100/10.txt)
[11.txt](https://github.com/azerothcore/azerothcore-wotlk/files/6699101/11.txt)


@FrancescoBorzi @UltraNix  Please pay attention to it

**Comment by UltraNix** [comment]
All of them look weird.

**Comment by Winfidonarleyan** [comment]
Please use https://gist.github.com/ next time

**Comment by rogerc66** [comment]
I'm having random crash as well.

**Comment by Kitzunu** [comment]
Post a crashlog if you get a crash

**Comment by rogerc66** [comment]
<img width="441" alt="截屏2021-06-24 下午8 47 30" src="https://user-images.githubusercontent.com/4217584/123265339-8665df80-d52d-11eb-982b-aa5a00507636.png">
it just crash without a sign, I have see some segment fault with exit code 139 from console though, but I get no crash log output.

**Comment by Kitzunu** [comment]
That looks like an issue with simple-restarter

**Comment by rogerc66** [comment]
> That looks like an issue with simple-restarter

Any suggestion on how to fix that?

**Comment by mpfans** [comment]
https://gist.github.com/mpfans/05c5a133f9cf5b0b48d30284dcec027c

new crash log

**Comment by mpfans** [comment]
https://gist.github.com/mpfans/67d34bac5d4bbcf1e0508d3067673617

new crash log too

**Comment by ChromieCraftServer** [comment]
added a 30$ bounty

cc @UltraNix @Winfidonarleyan

**Comment by UltraNix** [comment]
Crash happens on Eye of Eternity.
```
They're fighting Malygos, and then they all die. His soul enters the eye of eternity, and then he resurrects.. but instead of being on the stage, he keeps falling down, and then dies. He enters the eye of eternity again, and then resurrects again, and then falls down again.. then the server crashes
```

**Comment by rogerc66** [comment]
This is by far the most annoying problem in the top list issue, once you starting playing in a dungeon, server will crash a few minutes interval.

**Comment by UltraNix** [comment]
@rogerc66 Send a crashlog.

**Comment by FrancescoBorzi** [comment]
> 

please provide a crashlog, otherwise we can't help you. You can read [this](https://www.azerothcore.org/wiki/how-to-restart-and-debug) to find out how

**Comment by mpfans** [comment]
new crash log tooo

https://gist.github.com/mpfans/0bee6b36fe9dce8b6ca0f3a8ff3c3e04

**Comment by mpfans** [comment]
https://gist.github.com/mpfans/0a6fefc1ce56e94677616bc67f1776ec

new crash log tooo

**Comment by rogerc66** [comment]
I found out the root cause of server crash, at least for myself, the culprit is mod-gain-honor-guard, once you killed an elite in dungeon, it 's very likely crashed the server at moment deposit the honor.

After I removed the mod and recompiled the source, it's fine now.

**Comment by rogerc66** [comment]
> @rogerc66 Again - provide a crashlog.

I tried, I have followed the link provided by FrancescoBorzi, and followed steps instructed by docker procedure to enable GDB, but when I go to back to docker logs folder, there are no crash dump log generated, I have no idea why.
