### ISSUE TITLE
Error duplicate key when inserting into character_queststatus_seasonal

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#6497]
```
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (22172, 11808, 0)
 [ERROR]: [1062] Duplicate entry '22172-11808' for key 'character_queststatus_seasonal.PRIMARY'
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (22029, 11922, 0)
 [ERROR]: [1062] Duplicate entry '22029-11922' for key 'character_queststatus_seasonal.PRIMARY'
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (22029, 11922, 0)
 [ERROR]: [1062] Duplicate entry '22029-11922' for key 'character_queststatus_seasonal.PRIMARY'
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (43102, 11922, 0)
 [ERROR]: [1062] Duplicate entry '43102-11922' for key 'character_queststatus_seasonal.PRIMARY'
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (22029, 11922, 0)
 [ERROR]: [1062] Duplicate entry '22029-11922' for key 'character_queststatus_seasonal.PRIMARY'
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (34523, 11584, 0)
 [ERROR]: [1062] Duplicate entry '34523-11584' for key 'character_queststatus_seasonal.PRIMARY'
SQL(p): INSERT INTO character_queststatus_seasonal (guid, quest, event) VALUES (37652, 11740, 0)
 [ERROR]: [1062] Duplicate entry '37652-11740' for key 'character_queststatus_seasonal.PRIMARY'
 ```

Unfortunately I don't know how to reproduce this, just saw it spamming in the worldserver console.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Helias** [comment]
11922 is the [Torch Tossing](https://wowgaming.altervista.org/aowow/?quest=11922) quest, so this error logs are related to the Midsummer event (ID: 1).

**Comment by UltraNix** [comment]
@FrancescoBorzi Does it happen with other events?

**Comment by FrancescoBorzi** [comment]
@UltraNix unfortunately I don't know anything more about this one

**Comment by markvetx** [comment]
Hey, guys. Brewfest started on AC yesterday, and there is the same bug with seasonal quests. Basically, when you're completing a non-repeatable seasonal quest, you're getting a reward and quest is completed.. but after logging out and in you can take (or sometimes just turn-in the quest) and get your reward repeatedly.

**Comment by UltraNix** [comment]
@markvetx https://github.com/azerothcore/azerothcore-wotlk/issues/6623 It's the same problem. Add your comment there.
