### ISSUE TITLE
Instant logout fix

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#65]
in MiscHandler.cpp find:
bool instantLogout = (GetSecurity() > SEC_PLAYER || GetPlayer()->HasFlag(PLAYER_FLAGS, PLAYER_FLAGS_RESTING) && !GetPlayer()->IsInCombat()) || GetPlayer()->IsInFlight();

and replace with:

bool instantLogout = (GetPlayer()->HasFlag(PLAYER_FLAGS, PLAYER_FLAGS_RESTING) && !GetPlayer()->IsInCombat()) ||
 GetPlayer()->IsInFlight() || GetSecurity() >= AccountTypes(sWorld->getIntConfig(CONFIG_INSTANT_LOGOUT)) ||
                         GetPlayer()->GetMapId() == 1 || GetPlayer()->GetZoneId() == 5695 ||
                         GetPlayer()->GetMapId() == 0 || GetPlayer()->GetZoneId() == 2037 ||
                         GetPlayer()->GetMapId() == 0 || GetPlayer()->GetZoneId() == 1537 ||
                         GetPlayer()->GetMapId() == 530 || GetPlayer()->GetZoneId() == 3487 ||
                         GetPlayer()->GetMapId() == 571 || GetPlayer()->GetZoneId() == 394 ||
                         GetPlayer()->GetMapId() == 732 || GetPlayer()->GetZoneId() == 5389 ||
                         GetPlayer()->GetMapId() == 732 || GetPlayer()->GetZoneId() == 5095;

**Comment by sunshitwowsucks** [comment]
lol

**Comment by Yehonal** [comment]
what is this XD freaking bad

**Comment by DevRival** [comment]
Very hack))

**Comment by ShinDarth** [comment]
sorry, this is too hacky

also please read the documentation about how to contribute:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute
