### ISSUE TITLE
[PVP  BUG] Spell reflect DR on Spells

### ISSUE THREAD

**Issue by cbanovanta** [azerothcore/azerothcore-wotlk#650]
**Description**:When a Player use a spell like a Control (es. Cyclone, Fear, Poly etc.) on Spell Reflection, the spell should create the DR of the control on the player that use the spell and got it reflected.

**Current behaviour**:Spell used and reflected dsnt create DR on who is the spell. 

Es: if a mage use Polymorph on Warrior Spell Reflection Mage take first 9 seconds of Polymorph than on the second Spell reflection again 9 seconds of it.

**Expected behaviour**: Spell Reflected should create DR. 

Es: if a Mage use Polymorph on the Spell Reflection of the Warrior, Mages should take first 9 seconds Polymorph than on the second Spell Reflection the Poly on mages should be of 4 seconds.

**Steps to reproduce the problem**:

1. Use Spell Reflection of Warrior and cast Cyclon or all other spells with dr on consecutive spells.
2. Use again Spell Reflection of Warrior and take another Cyclon into reflect to see.
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:   No modified was applied on AzerothCore AzerothCore

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by lineagedr** [comment]
This fixes the issue https://github.com/elecyb/TrinityCore/commit/f09e348f50e6c32de6cfc2e48c8a50ba8c257f72

After the applying the fix: https://www.youtube.com/watch?v=AHrOVvjE3Xg

**Comment by ShinDarth** [comment]
@lineagedr as I said in the other issue, it would be nice if you could import those fixes to AzerothCore by opening a PR.

**Comment by cbanovanta** [comment]
http://178.33.198.169/check-commit.php

**Comment by cbanovanta** [comment]
the video show it in the correct way

**Comment by ShinDarth** [comment]
@cbanovanta you should not use that link directly! because the hash will change as soon as someone updates the server.  Just copy and paste the hash in the issue report.

**Comment by lineagedr** [comment]
@cbanovanta Do you hav any more PvP bugs to report?

**Comment by cbanovanta** [comment]
yes i will report it from next month
