### ISSUE TITLE
Midsummer Festival - No Festival Scorchling NPC in Eversong Woods

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6500]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/953

Although the quest [Incense for the Festival Scorchlings](https://wowgaming.altervista.org/aowow?quest=11966) points to the location (46,50) in Eversong Woods, there is no scorchling NPC there.

Tester: confirmed. Also note that two of the celebrants at the Eversong festivities are Allies, a dwarf (GUID 202743) and a human (GUID 202744).

Screenshot showing map pointing to scorchling-less location, and on the right, two Ally gatecrashers.
![WoWScrnShot_062221_225716](https://user-images.githubusercontent.com/81782124/122933189-8d65e400-d3ad-11eb-9739-717fa22840ee.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should be a [Festival Scorchling NPC](https://tbc.wowhead.com/npc=26520/festival-scorchling) near the bonfire at (46, 50) in Eversong Woods.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get the [Incense for the Festival Scorchlings](https://wowgaming.altervista.org/aowow?quest=11966) quest
2. Go to Eversong Woods and check the quest map
3. Go to the location (46,50)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
@sudlud found one for you :D

**Comment by sudlud** [comment]
> @sudlud found one for you :D

Already on my list 😃 

Still busy with gameobjects, creatures are next
