### ISSUE TITLE
DB/Creature: Halloween spawns

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#651]
**Description**:

> There should be commoners informing players of Pirate's Day in all of the capital cities.

**Current behaviour**: Tell us what happens

> There are no commoners in any of the capital cities.

**Expected behaviour**: Tell us what should happen instead

> Commoners should be located in each major city.

**Steps to reproduce the problem**:

1. Go to any capital city on Pirate's Day 

**AC hash/commit**:  
 
> a4d090a06475

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

>Master/Staging Master

**Operating system**:  

>VMWare Workstation 12 running Win7x64

**Modules**:  Are you using modules? if yes, list them

>None

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

>None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by SasukeAg** [comment]
Same issue on my server, can you guys fix it? we need to change the event on the game calendar in order to have it done, any ideas about what i can do to fix this?

thx,

**Comment by STARRHELD** [comment]
I can see Orc Commoners in Orgrimmar, can anyone confirm?
