### ISSUE TITLE
playercreateinfo_skills

### ISSUE THREAD

**Issue by Dude100** [azerothcore/azerothcore-wotlk#6510]
**CURRENT BEHAVIOUR:**

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. 
2. 
3. 

**EXTRA NOTES:**

after update missing racial,for now Troll mage Undead Mage https://postimg.cc/3y36584v 
missing language:
You cannot speak that language

Only Old characters 

**AC HASH/COMMIT:**
 
AzerothCore rev. 20a67cbfcf78+ 2021-06-22 16:27:03 +0200 (master branch) (Unix, Release, Static) (worldserver-daemon) ready...

**OPERATING SYSTEM:**

Debian 10 
**MODULES:**

mod-cfbg  mod-pvp-titles
**CUSTOMIZATIONS:**

no

**Comment by Kitzunu** [comment]
I cannot reproduce this. Everything works as it should

**Comment by Dude100** [comment]
after pull to last rev. 77ad79c9288e+ Old character are without racial spell and language 
new character are not affected

https://postimg.cc/3y36584v

**Comment by Kitzunu** [comment]
I still cant reproduce that

**Comment by Dude100** [comment]
Character GUID Full: 0x000000000000000c Type: Player Low: 12 has skill 38 that does not exist.
Character GUID Full: 0x000000000000000c Type: Player Low: 12 has skill 39 that does not exist.
Character GUID Full: 0x000000000000000c Type: Player Low: 12 has skill 125 that does not exist.
Character GUID Full: 0x000000000000000c Type: Player Low: 12 has skill 253 that does not exist.
Character GUID Full: 0x000000000000000c Type: Player Low: 12 has skill 756 that does not exist.

**Comment by Kitzunu** [comment]
Unless I can reproduce it, I cannot fix it. And on mine all previous chars work

**Comment by Dude100** [comment]
any ideas ?
