### ISSUE TITLE
(Spells): No pushback from certain spells

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#6512]
**CURRENT BEHAVIOUR:**

Currently, Razormane Hunters have a shoot spell that doesn't have any pushback.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Pushback when spellcasting

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1.  Casting Shadowbolt at a Razormane hunter gets no pushback

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
Happens on ChromieCraft

**OPERATING SYSTEM:**

Windows 10

**MODULES:**

**CUSTOMIZATIONS:**

Models

**Comment by Kitzunu** [comment]
Add hash
