### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by Dude100** [azerothcore/azerothcore-wotlk#6514]
**CURRENT BEHAVIOUR:**

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. 
2. 
3. 

**EXTRA NOTES:**

https://pastebin.com/AE1BQ3K5
Log : https://pastebin.com/1xNQTqDT
**AC HASH/COMMIT:**
 
5991b2769acc2f7c1959f1850a36a22c968bb45c
**OPERATING SYSTEM:**

Debian 10 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux

**MODULES:**

no
**CUSTOMIZATIONS:**

no

**Comment by Sedatyf** [comment]
Please give us more information. A blank template won't help us to help you

**Comment by Dude100** [comment]
now test on Ubuntu 18 clean core 

==== ACORE COMPILER ====
Cleaning build files in /home/niki/azerothcore-wotlk/var/build/obj
Build path: /home/niki/azerothcore-wotlk/var/build/obj
DEBUG info: OFF
Compilation type: Release
CCache: false
-- CMake version: 3.16.7
-- The CXX compiler identification is Clang 10.0.0
-- The C compiler identification is Clang 10.0.0
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at conf/dist/config.cmake:28 (message):
  The value (ON) of your SCRIPTS variable is invalid! Allowed values are:
  none;static;dynamic;minimal-static;minimal-dynamic.  Set static
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "/home/niki/azerothcore-wotlk/var/build/obj/CMakeFiles/CMakeOutput.log".

5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

after this commit linux compile fail Debian 10 + Ubuntu 

https://github.com/azerothcore/azerothcore-wotlk/commit/5991b2769acc2f7c1959f1850a36a22c968bb45c

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/962447979 ci for normal build passes.

Maybe you use Eluna or Transmog module and they are broken atm

**Comment by Kitzunu** [comment]
Ah no, delete you cmake cache and run cmake

**Comment by Dude100** [comment]
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at conf/dist/config.cmake:28 (message):
  The value (1) of your SCRIPTS variable is invalid! Allowed values are:
  none;static;dynamic;minimal-static;minimal-dynamic.  Set static
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "/home/niki/azerothcore-wotlk/build/CMakeFiles/CMakeOutput.log".

delete cache and nothing
will try on Debina

**Comment by Dude100** [comment]
Debian is out too 

==== ACORE COMPILER ====
Build path: /root/azerothcore-wotlk/var/build/obj
DEBUG info: OFF
Compilation type: Release
CCache: false
-- CMake version: 3.20.0
CMake Error at conf/dist/config.cmake:28 (message):
  The value (ON) of your SCRIPTS variable is invalid! Allowed values are:
  none;static;dynamic;minimal-static;minimal-dynamic.  Set static
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "/root/azerothcore-wotlk/var/build/obj/CMakeFiles/CMakeOutput.log".
root@dragonfirebg:~/azerothcore-wotlk#

**Comment by Kitzunu** [comment]
Try restarting the system. Or if you manually can set SCRIPT to Static in Cmake

**Comment by Dude100** [comment]
after set static compile happy now :)

# Log a error when the value of the SCRIPTS variable isn't a valid option.
if(SCRIPTS)
  list(FIND SCRIPTS_AVAILABLE_OPTIONS "${SCRIPTS}" SCRIPTS_INDEX)
  if(${SCRIPTS_INDEX} EQUAL -static)
    message(FATAL_ERROR "The value (${SCRIPTS}) of your SCRIPTS variable is invalid! "
            "Allowed values are: ${SCRIPTS_AVAILABLE_OPTIONS}. Set static")
  endif()
endif()

# Log a error when the value of the SCRIPTS variable isn't a valid option.
if(MODULES)
  list(FIND MODULES_AVAILABLE_OPTIONS "${MODULES}" MODULES_INDEX)
  if(${MODULES_INDEX} EQUAL -static)
    message(FATAL_ERROR "The value (${MODULES}) of your MODULES variable is invalid! "
            "Allowed values are: ${MODULES_AVAILABLE_OPTIONS}. Set static")
  endif()
endif()
