### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6516]
**CURRENT BEHAVIOUR:**
I updated but when compiling gave the errors below:
![image](https://user-images.githubusercontent.com/67213916/123020657-057ddb00-d3a9-11eb-9cd5-3fb7e671be51.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
NO ERROR , 0 failures

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1.Update to latest version
2. Generate Cmake
3. Build solution

**EXTRA NOTES:**

**AC HASH/COMMIT:**

> 77ad79c9288e

**OPERATING SYSTEM:**
Windows

**MODULES:**
Mod-Anticheat
Mod-BgReward
Mod-CFBG
Mod-Eluna-Lua-Engine
Mod-PvpTitles
Mod-NpcBeastmaster
Mod-Transmog

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
Delete cmake cache
Run camke
Compile

Works for me and CI without errors

**Comment by WillzDevs** [comment]
> Delete cmake cache
> Run camke
> Compile
> 
> Works for me and CI without errors

I cleared the chace, generated cmake and opened build solution, the error continues
![image](https://user-images.githubusercontent.com/67213916/123022692-8d191900-d3ac-11eb-8ea4-ade9571df622.png)

**Comment by WillzDevs** [comment]
@Kitzunu  Even after deleting the cache, the error continues, until I restarted the computer, haha
