### ISSUE TITLE
AC Compilation Failing: Invalid Scripts Variable Value

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6520]
**CURRENT BEHAVIOUR:**

Attempting to compile AC after a new update gives the following error:
```
CMake Error at conf/dist/config.cmake:28 (message):
 The value (ON) of your SCRIPTS variable is invalid! Allowed values are:
  none;static;dynamic;minimal-static;minimal-dynamic.  Set static
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```
This on on a system using the Bash dashboard setup. The base compiler command is ./acore.sh compiler all, which through a couple of intermediaries ends up at functions.sh. Line 69 there ("-DSCRIPTS=$CSCRIPTS") looks like it could be changed to fix this, but that didn't work for me.

Roboto on Discord says it can be fixed if you use -DSCRIPTS=static instead of -DSCRIPTS=1 in the Cmake cmd.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

It should compile cleanly.

**STEPS TO REPRODUCE THE PROBLEM:**

**EXTRA NOTES:**

Also noted here: https://github.com/azerothcore/azerothcore-wotlk/pull/5346

**AC HASH/COMMIT:**
 
Unavailable, as the server won't compile.

**OPERATING SYSTEM:**

Linux Mint 20

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
-DSCRIPTS=static

**Comment by FrancescoBorzi** [comment]
@Kitzunu I can reproduce this in a Dashboard setup using Ubuntu 20.04

> Put -DSCRIPTS=static

this should be fixed in our scripts as well, please remember that not everyone are using the Traditional setup (which would indeed benefit from the manual fix you suggested).

**Comment by Kitzunu** [comment]
Too many ways to install 😓

**Comment by Kitzunu** [comment]
for future:

```
AC HASH/COMMIT:

Unavailable, as the server won't compile.
```

Is never unavailable, it is the last commit you pulled

**Comment by anguaive** [comment]
```diff
diff --git a/conf/dist/config.sh b/conf/dist/config.sh
index 93f04861f..52fbe6716 100644
--- a/conf/dist/config.sh
+++ b/conf/dist/config.sh
@@ -60,7 +60,7 @@ CDEBUG=OFF
 # * MinSizeRel: same as Release but optimizing for size rather than speed.
 CTYPE=${CTYPE:-Release}
 # compile scripts
-CSCRIPTS=${CSCRIPTS:-ON}
+CSCRIPTS=${CSCRIPTS:-static}
 # compile unit tests
 CBUILD_TESTING=OFF
 # compile server
```

**Comment by FrancescoBorzi** [comment]
> ```diff
> diff --git a/conf/dist/config.sh b/conf/dist/config.sh
> index 93f04861f..52fbe6716 100644
> --- a/conf/dist/config.sh
> +++ b/conf/dist/config.sh
> @@ -60,7 +60,7 @@ CDEBUG=OFF
>  # * MinSizeRel: same as Release but optimizing for size rather than speed.
>  CTYPE=${CTYPE:-Release}
>  # compile scripts
> -CSCRIPTS=${CSCRIPTS:-ON}
> +CSCRIPTS=${CSCRIPTS:-static}
>  # compile unit tests
>  CBUILD_TESTING=OFF
>  # compile server
> ```

ah, I did not notice your message before, that's indeed the solution. Thanks anyway @anguaive !
