### ISSUE TITLE
Character crashes when changing SPEC

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6527]
**CURRENT BEHAVIOUR:**
When you change the SPEC on the character it crashes, you can't speak "You cannot speak that language."
And with that you can't change the SPEC again and most of the SPELLS disappear.
Below is the video with the problem;
[https://vimeo.com/566824445](url)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Can change SPEC without crashing the character.
Can speak normally.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Enter character with 2 SPECs
2. change SPEC
3. Character crashes, doesn't speak, doesn't change SPEC again

**EXTRA NOTES:**

**AC HASH/COMMIT:**

> 065d403b729a+

**OPERATING SYSTEM:**
Windows

**MODULES:**
Mod-Anticheat
Mod-BgReward
Mod-CFBG
Mod-PvpTitles
Mod-NpcBeastmaster
Mod-Transmog

**CUSTOMIZATIONS:**

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/6015 It's caused here

**Comment by WillzDevs** [comment]
> #6015 It's caused here

Obrigado por avisar 😁

**Comment by WillzDevs** [comment]
> #6015 It's caused here

thanks for letting me know 😁

**Comment by FrancescoBorzi** [comment]
> #6015 It's caused here

@Kitzunu

**Comment by Kitzunu** [comment]
I will look tonight

**Comment by WillzDevs** [comment]
> I will look tonight

I don't know if I could comment on this here, but the eluna engine module after this update along with the npc free professions module also stopped working.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/6561 fixed

**Comment by Kitzunu** [comment]
> > I will look tonight
> 
> I don't know if I could comment on this here, but the eluna engine module after this update along with the npc free professions module also stopped working.

Modules was not broken with this, another commit broke that and it is being worked on

**Comment by WillzDevs** [comment]
> > > I will look tonight
> > 
> > 
> > I don't know if I could comment on this here, but the eluna engine module after this update along with the npc free professions module also stopped working.
> 
> Modules was not broken with this, another commit broke that and it is being worked on

Thanks @Kitzunu !!

**Comment by WillzDevs** [comment]
> #6561 fixed

Got Fixed?? I did the update and nothing changed :cry:

**Comment by Kitzunu** [comment]
its in a PR. Waiting on someone to test it before it can be committed into master

**Comment by WillzDevs** [comment]
> its in a PR. Waiting on someone to test it before it can be committed into master

wonderful, thank you!
