### ISSUE TITLE
Feature: [Suggestion] Docker Setup Shell Should Determine if Deno,DockerImage etc has been downloaded

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#6533]
**Describe your feature request or suggestion in detail**

for kinds of reasons, it's hard to download all kinds of package in once shell execution, cause of long connection break.
just a little package was not download success, it should be repeat download a huge package again in a long duration.
why not the docker setup shell determine should be download  or not by the result of work has done before ?
--I Repeat the DockerSetup For almost 2 Days, and still not installed successed ,  waste huge time to repeat download the same package such as deno,mysql slowly.
it should be a more efficient method to enhance this Shell.  
**Describe a possible solution to your Feature or Suggestion in detail**

**Additional context**

014816065922+

**Comment by betayi** [comment]
it's weird that the repeat download procedure disappeared without anything changed!
hard to understand...
but it breaks with coming err:

Downloading client data in: /azerothcore/env/dist/data/data.zip ...
/azerothcore/apps/installer/includes/functions.sh: line 245: /azerothcore/env/dist/data/data.zip: Permission denied

**Comment by Helias** [comment]
@Yehonal

**Comment by Yehonal** [comment]
Working on it. It will be available soon

**Comment by Sedatyf** [comment]
Does this has been fixed by Yehonal? If no, why closing it?

**Comment by FrancescoBorzi** [comment]
@betayi

**Comment by Araiguma90** [comment]
Some news related to the issue?
`/azerothcore/apps/installer/includes/functions.sh: line 245: /azerothcore/env/dist/data/data.zip: Permission denied`

**Comment by Araiguma90** [comment]
> it's weird that the repeat download procedure disappeared without anything changed!
> hard to understand...
> but it breaks with coming err:
> 
> Downloading client data in: /azerothcore/env/dist/data/data.zip ...
> /azerothcore/apps/installer/includes/functions.sh: line 245: /azerothcore/env/dist/data/data.zip: Permission denied

I had to remove all docker volumes to get rid of this error
