### ISSUE TITLE
[Orgrimmar] Character getting stuck while runing to the second floor of a building.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6537]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [x] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/949

##### CURRENT BEHAVIOUR:

Character getting stuck while getting to the 2nd floor of  an Orgrimmar building.
Build
![WoWScrnShot_062121_145238](https://user-images.githubusercontent.com/82708448/122765889-4094e700-d2a1-11eb-8b9b-f2410e950f28.jpg)
ind localization is 41,62

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should just run and go up without anything stucking you.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the 41,62 building in Orgri (the one you go to get to the West of the city)
2. Run through the "stairs" to go up
3. Stick to the right when going up
4. You will encounter an invisible wall stucking you.

##### EXTRA NOTES:

The character seems to get into the floor then getting stuck by the beam beneath the "stairs".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 2a2e54d) :

![WoWScrnShot_062421_125256](https://user-images.githubusercontent.com/82579073/123243193-74634d00-d4eb-11eb-88f0-59ad0a2f8ce2.jpg)
![WoWScrnShot_062421_125305](https://user-images.githubusercontent.com/82579073/123243253-82b16900-d4eb-11eb-8281-8083fc0a0387.jpg)

**Comment by UltraNix** [comment]
Clientside textures - nothing we can do with it.
