### ISSUE TITLE
The Barrens - Brontus Missing Patrol Pattern

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6539]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/968

Brontus is stationary in his spawn point.
![brontus](https://user-images.githubusercontent.com/80769357/123086875-3818e980-d424-11eb-945f-8d4ffcc6a684.jpg)

Tester: confirmed.
![WoWScrnShot_062421_195548](https://user-images.githubusercontent.com/81782124/123247780-62eb6680-d526-11eb-9a8d-a4312b143708.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be moving around. 
Going by wowhead comments, he should be patrolling around with a group of 3 other kodos.
https://classic.wowhead.com/npc=5827/brontus#comments
https://www.wowhead.com/npc=5827/brontus#comments

presumably one of these groups that patrols in barrens:
northern one
![barrenskodos](https://user-images.githubusercontent.com/80769357/123086401-ae691c00-d423-11eb-9c0f-f0010cae73b4.jpg)
GUID 15144 for Wooly Kodo

southern one:
![kodos2](https://user-images.githubusercontent.com/80769357/123087347-bb3a3f80-d424-11eb-8f45-40480a7b0871.jpg)

GUID 15139 (one of the kodos)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 51815
2. Observe his stationary nature

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by neifion-00000000** [comment]
I have spent the past days researching this at @hanabi5 's request.  All of the following is/will be available to the sniff database at some point after the 43861 sniffer is retired.  Thanks to @malcrom used your tools to make this data usable.  And ofc to the people who make the sniffer run to that point.

Stuff I'm 100% sure of is in bold.

**There is a path that roams from the Northeastern corner of Blackthorn Ridge to a point in Bramblescar.  This path has a group of 4 kodos that run south to north on it are friendly to each other (when in close range, there is a major issue on Blizzard servers with pathing mobs when players are not in range to keep them together, blizzlike, if only for the fact its like that but I really don't think it was always this way.... i digress).

This pack I've witnessed respawn anywhere from instantly to 45 mins and does seem impacted by population (respawns average faster on high zone population). 

This pack appears to spawn one of three distinct ways.  More often than not, it spawns a pack of 4 regular kodo beast NPCs.  I have seen the following configurations which would translate into 3 pools of 4 creatures:  4 Barrens Kodos (3236), which is the most frequent configuration, 

The second most frequent configuration is a mix of 0-4 Barrens Kodo (3236) 1-2 Wooly Kodo that never lead the pack (3237) and 1-2 Greater Barrens Kodo (3235).**

**The least common configuration**  (I don't have a for sure count on this, but 1 in 10 might be a good guess, it might be more common though) **spawns in only one witnessed way, Brontus (5827) and 1 of each Kodo type (3235-3237) with the Wooly Kodo in front leading the pack.**  I am fairly confident the mob that spawns at -3787.7153, -1848.3755, 93.918015 should be the lead mob as I also believe the only time the Wooly Kodo leads the pack is on the Brontus spawn.  This could be incorrect but it has occurred every time I have captured it.

**This is the pathing data parsed for both packs.  Note SQL may need fixing my waypoint creator may be out of date:

-- Pathing for  Entry: 3237
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `wander_distance`=0,`MovementType`=2,`position_x`=-3780.6667,`position_y`=-1879.9966,`position_z`=94.51902 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`visibilityDistanceType`,`auras`) VALUES (@NPC,@PATH,0,0,1,0,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,-3780.6667,-1879.9966,94.51902,0,0,0,0,100,0),
(@PATH,2,-3765.317,-1912.2642,92.659584,0,0,0,0,100,0),
(@PATH,3,-3743.7683,-1944.3379,93.25019,0,0,0,0,100,0),
(@PATH,4,-3718.9587,-1949.9241,94.24338,0,0,0,0,100,0),
(@PATH,5,-3674.7666,-1972.0784,92.34276,0,0,0,0,100,0),
(@PATH,6,-3633.491,-1962.7506,91.96043,0,0,0,0,100,0),
(@PATH,7,-3604.3447,-1934.8683,93.6461,0,0,0,0,100,0),
(@PATH,8,-3574.0989,-1917.8884,94.641045,0,0,0,0,100,0),
(@PATH,9,-3543.6143,-1922.9417,93.78076,0,0,0,0,100,0),
(@PATH,10,-3514.391,-1891.8881,96.05839,0,0,0,0,100,0),
(@PATH,11,-3482.7354,-1879.4718,95.54532,0,0,0,0,100,0),
(@PATH,12,-3447.3694,-1879.2826,94.04059,0,0,0,0,100,0),
(@PATH,13,-3419.4883,-1883.6552,93.07612,0,0,0,0,100,0),
(@PATH,14,-3401.6602,-1915.7799,93.66566,0,0,0,0,100,0),
(@PATH,15,-3377.1729,-1946.9575,91.91544,0,0,0,0,100,0),
(@PATH,16,-3359.4075,-1987.9889,93.354164,0,0,0,0,100,0),
(@PATH,17,-3351.847,-2020.0239,93.34684,0,0,0,0,100,0),
(@PATH,18,-3347.3481,-2061.3584,96.55564,0,0,0,0,100,0),
(@PATH,19,-3337.5916,-2084.593,91.86515,0,0,0,0,100,0),
(@PATH,20,-3305.2717,-2097.2861,91.791664,0,0,0,0,100,0),
(@PATH,21,-3264.5898,-2110.5752,93.58816,0,0,0,0,100,0),
(@PATH,22,-3221.6958,-2091.54,92.918495,0,0,0,0,100,0),
(@PATH,23,-3175.735,-2081.8813,91.791664,0,0,0,0,100,0),
(@PATH,24,-3131.3293,-2093.495,91.81647,0,0,0,0,100,0),
(@PATH,25,-3093.5208,-2117.2578,93.19572,0,0,0,0,100,0),
(@PATH,26,-3050.1245,-2119.8708,93.09464,0,0,0,0,100,0),
(@PATH,27,-3005.5127,-2109.9685,92.291664,0,0,0,0,100,0),
(@PATH,28,-2967.4277,-2095.7334,91.791664,0,0,0,0,100,0),
(@PATH,29,-2936.955,-2117.254,91.791664,0,0,0,0,100,0),
(@PATH,30,-2908.1777,-2144.7766,93.2714,0,0,0,0,100,0),
(@PATH,31,-2871.219,-2160.007,92.05509,0,0,0,0,100,0),
(@PATH,32,-2853.049,-2161.5356,91.791664,0,0,0,0,100,0),
(@PATH,33,-2835.0942,-2182.703,95.2443,0,0,0,0,100,0),
(@PATH,34,-2795.9773,-2209.954,95.784584,0,0,0,0,100,0),
(@PATH,35,-2758.5547,-2238.7458,92.954506,0,0,0,0,100,0),
(@PATH,36,-2721.4429,-2257.816,91.791664,0,0,0,0,100,0),
(@PATH,37,-2681.0037,-2258.5547,91.95255,0,0,0,0,100,0),
(@PATH,38,-2673.5525,-2282.2383,91.791664,0,0,0,0,100,0),
(@PATH,39,-2647.4885,-2312.194,92.01603,0,0,0,0,100,0),
(@PATH,40,-2624.1008,-2319.0713,92.736,0,0,0,0,100,0),
(@PATH,41,-2583.4438,-2317.825,91.791664,0,0,0,0,100,0),
(@PATH,42,-2553.0298,-2291.6404,93.56666,0,0,0,0,100,0),
(@PATH,43,-2522.4128,-2288.3354,95.39027,0,0,0,0,100,0),
(@PATH,44,-2480.3079,-2292.0088,94.91757,0,0,0,0,100,0),
(@PATH,45,-2440.1282,-2314.39,94.61803,0,0,0,0,100,0),
(@PATH,46,-2414.875,-2342.5525,91.83561,0,0,0,0,100,0),
(@PATH,47,-2396.1902,-2380.3955,91.791664,0,0,0,0,100,0),
(@PATH,48,-2380.417,-2413.0195,92.82902,0,0,0,0,100,0),
(@PATH,49,-2353.339,-2423.769,95.19796,0,0,0,0,100,0),
(@PATH,50,-2310.5186,-2422.7778,95.587776,0,0,0,0,100,0),
(@PATH,51,-2293.4502,-2402.058,93.38322,0,0,0,0,100,0),
(@PATH,52,-2295.2888,-2370.951,92.66499,0,0,0,0,100,0),
(@PATH,53,-2286.9407,-2341.9426,93.4555,0,0,0,0,100,0),
(@PATH,54,-2252.9795,-2320.2158,93.7934,0,0,0,0,100,0),
(@PATH,55,-2207.6965,-2319.8152,93.1684,0,0,0,0,100,0),
(@PATH,56,-2185.574,-2344.3398,94.98741,0,0,0,0,100,0),
(@PATH,57,-2207.6965,-2319.8152,93.1684,0,0,0,0,100,0),
(@PATH,58,-2252.9795,-2320.2158,93.7934,0,0,0,0,100,0),
(@PATH,59,-2286.9407,-2341.9426,93.4555,0,0,0,0,100,0),
(@PATH,60,-2295.2888,-2370.951,92.66499,0,0,0,0,100,0),
(@PATH,61,-2293.4502,-2402.058,93.38322,0,0,0,0,100,0),
(@PATH,62,-2310.5186,-2422.7778,95.587776,0,0,0,0,100,0),
(@PATH,63,-2353.339,-2423.769,95.19796,0,0,0,0,100,0),
(@PATH,64,-2380.417,-2413.0195,92.82902,0,0,0,0,100,0),
(@PATH,65,-2396.1902,-2380.3955,91.791664,0,0,0,0,100,0),
(@PATH,66,-2414.875,-2342.5525,91.83561,0,0,0,0,100,0),
(@PATH,67,-2440.1282,-2314.39,94.61803,0,0,0,0,100,0),
(@PATH,68,-2480.3079,-2292.0088,94.91757,0,0,0,0,100,0),
(@PATH,69,-2522.4128,-2288.3354,95.39027,0,0,0,0,100,0),
(@PATH,70,-2553.0298,-2291.6404,93.56666,0,0,0,0,100,0),
(@PATH,71,-2583.4438,-2317.825,91.791664,0,0,0,0,100,0),
(@PATH,72,-2624.1008,-2319.0713,92.736,0,0,0,0,100,0),
(@PATH,73,-2647.4885,-2312.194,92.01603,0,0,0,0,100,0),
(@PATH,74,-2673.5525,-2282.2383,91.791664,0,0,0,0,100,0),
(@PATH,75,-2681.0037,-2258.5547,91.95255,0,0,0,0,100,0),
(@PATH,76,-2721.4429,-2257.816,91.791664,0,0,0,0,100,0),
(@PATH,77,-2758.5547,-2238.7458,92.954506,0,0,0,0,100,0),
(@PATH,78,-2795.9773,-2209.954,95.784584,0,0,0,0,100,0),
(@PATH,79,-2835.0942,-2182.703,95.2443,0,0,0,0,100,0),
(@PATH,80,-2853.049,-2161.5356,91.791664,0,0,0,0,100,0),
(@PATH,81,-2871.219,-2160.007,92.05509,0,0,0,0,100,0),
(@PATH,82,-2908.1777,-2144.7766,93.2714,0,0,0,0,100,0),
(@PATH,83,-2936.955,-2117.254,91.791664,0,0,0,0,100,0),
(@PATH,84,-2967.4277,-2095.7334,91.791664,0,0,0,0,100,0),
(@PATH,85,-3005.5127,-2109.9685,92.291664,0,0,0,0,100,0),
(@PATH,86,-3050.1245,-2119.8708,93.09464,0,0,0,0,100,0),
(@PATH,87,-3093.5208,-2117.2578,93.19572,0,0,0,0,100,0),
(@PATH,88,-3131.3293,-2093.495,91.81647,0,0,0,0,100,0),
(@PATH,89,-3175.735,-2081.8813,91.791664,0,0,0,0,100,0),
(@PATH,90,-3221.6958,-2091.54,92.918495,0,0,0,0,100,0),
(@PATH,91,-3264.5898,-2110.5752,93.58816,0,0,0,0,100,0),
(@PATH,92,-3305.2717,-2097.2861,91.791664,0,0,0,0,100,0),
(@PATH,93,-3337.5916,-2084.593,91.86515,0,0,0,0,100,0),
(@PATH,94,-3347.3481,-2061.3584,96.55564,0,0,0,0,100,0),
(@PATH,95,-3351.847,-2020.0239,93.34684,0,0,0,0,100,0),
(@PATH,96,-3359.4075,-1987.9889,93.354164,0,0,0,0,100,0),
(@PATH,97,-3377.1729,-1946.9575,91.91544,0,0,0,0,100,0),
(@PATH,98,-3401.6602,-1915.7799,93.66566,0,0,0,0,100,0),
(@PATH,99,-3419.4883,-1883.6552,93.07612,0,0,0,0,100,0),
(@PATH,100,-3447.3694,-1879.2826,94.04059,0,0,0,0,100,0),
(@PATH,101,-3482.7354,-1879.4718,95.54532,0,0,0,0,100,0),
(@PATH,102,-3514.391,-1891.8881,96.05839,0,0,0,0,100,0),
(@PATH,103,-3543.6143,-1922.9417,93.78076,0,0,0,0,100,0),
(@PATH,104,-3574.0989,-1917.8884,94.641045,0,0,0,0,100,0),
(@PATH,105,-3604.3447,-1934.8683,93.6461,0,0,0,0,100,0),
(@PATH,106,-3633.491,-1962.7506,91.96043,0,0,0,0,100,0),
(@PATH,107,-3674.7666,-1972.0784,92.34276,0,0,0,0,100,0),
(@PATH,108,-3718.9587,-1949.9241,94.24338,0,0,0,0,100,0),
(@PATH,109,-3743.7683,-1944.3379,93.25019,0,0,0,0,100,0),
(@PATH,110,-3765.317,-1912.2642,92.659584,0,0,0,0,100,0),
(@PATH,111,-3780.6667,-1879.9966,94.51902,0,0,0,0,100,0),
(@PATH,112,-3802.9849,-1847.3167,94.4449,0,0,0,0,100,0);
-- 0x204CB0002003294000001C00001E1E9F .go xyz -3780.6667 -1879.9966 94.51902 **



**Brontus Pack spawnpoints, SQL may need fixed:
(XXXXXX, 3237, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3787.7153, -1848.3755, 93.918015, 2.55345463752746582, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3787.7153 -1848.3755 93.918015 Leader 
(XXXXXX, 5827, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3814.7678, -1845.9219, 93.61283, 0.949117600917816162, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3814.7678 -1845.9219 93.61283  Brontus Spawnpoint**
(XXXXXX, 3235, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3798.8208, -1829.7017, 94.17238, 4.366050243377685546, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3798.8208 -1829.7017 94.17238 These last two are real spawn points, but they might not be correct for Brontus and might be swapped, would need to dig deeper into the parse, but this would be a silly minor detail as we rarely have the fortune to capture proper patrol spawns anyway,  I'll make sure if you really want tho.
(XXXXXX, 3236, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3807.5981, -1865.3707, 92.56358, 1.319851279258728027, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3807.5981 -1865.3707 92.56358

**Mixed Pack spawnpoints, SQL may need fixed: 
(XXXXXX, 3235, 3236, 0, 1, 0, 0, 1, 1, 0, 0, -3787.7153, -1848.3755, 93.918015, 2.55345463752746582, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3787.7153 -1848.3755 93.918015 Leader
(XXXXXX, 3237, 3236, 0, 1, 0, 0, 1, 1, 0, 0, -3814.7678, -1845.9219, 93.61283, 0.949117600917816162, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3814.7678 -1845.9219 93.61283 
(XXXXXX, 3237, 3236, 0, 1, 0, 0, 1, 1, 0, 0, -3798.8208, -1829.7017, 94.17238, 4.366050243377685546, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3798.8208 -1829.7017 94.17238
(XXXXXX, 3235, 3236, 0, 1, 0, 0, 1, 1, 0, 0, -3807.5981, -1865.3707, 92.56358, 1.319851279258728027, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3807.5981 -1865.3707 92.56358
**

**Barrens Kodo version, SQL may need fixed:
(XXXXXX, 3236, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3787.7153, -1848.3755, 93.918015, 2.55345463752746582, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3787.7153 -1848.3755 93.918015 Leader
(XXXXXX, 3236, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3814.7678, -1845.9219, 93.61283, 0.949117600917816162, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3814.7678 -1845.9219 93.61283 
(XXXXXX, 3236, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3798.8208, -1829.7017, 94.17238, 4.366050243377685546, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3798.8208 -1829.7017 94.17238
(XXXXXX, 3236, 0, 0, 1, 0, 0, 1, 1, 0, 0, -3807.5981, -1865.3707, 92.56358, 1.319851279258728027, 300, 0, 0, 1, 0, 0, 0, 0, 0, '', 0), -- .go xyz -3807.5981 -1865.3707 92.56358
**

**Comment by neifion-00000000** [comment]
https://youtu.be/21hbJnBoXfU
https://youtu.be/1C-XxIn5dvg
https://youtu.be/WPW3VEKgZpc

While not terribly useful, here are some videos I took, one of them I believe contains Brontus.  They show some but not all of the spawning behaviors listed above, though there's also a lot of dead space in at least one of them cuz I forgot I was recording.
