### ISSUE TITLE
[RAID] Ulduar

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#654]
**Description**: a lot of mana in the air

**Current behaviour**: Tell us what happens
 lot of mana in the air
![wowscrnshot_091717_164754](https://user-images.githubusercontent.com/31663279/30631820-f7529662-9de5-11e7-8a2e-7506cffb648f.jpg)
npc invisible
![wowscrnshot_091717_164650](https://user-images.githubusercontent.com/31663279/30632020-e08d9ebc-9de6-11e7-98ad-d88cffb0acd6.jpg)

**Expected behaviour**: Tell us what should happen instead
less mana
see npc

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: Master 

**AC hash/commit**:   944cfd077ece

**Operating system**:  ubuntu server 16.04

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by farsidesoul** [comment]
I'm not sure what the issue is here.  these are supposed to be shot down by the demolishers and siege engines.

**Comment by Maurowin** [comment]
yeah, but we have to much here. It's not blizzlike
and invisible NPC bronzebeard

**Comment by Si1ker** [comment]
@Maurowin Thanks for your report, we are gonna continue the problem in #2825  as this has more information and also includes other issues within Ulduar.
