### ISSUE TITLE
[warrior] Last 3 rend ticks don't proc taste for blood correctly

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6542]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/963

##### CURRENT BEHAVIOUR:

Glyphed Rend has a duration of 21 seconds and should do damage 7 times.

Each number in the list under is a rend tick. 1 being first rend damage and 7 the last one(when rend debuff expires from the target after doing damage one last time)

1 procs taste of blood correctly
2 taste of blood is on cd
3 procs taste of blood correctly
4 Taste of blood is on cd
5 NO PROC - we should see a taste of blood proc now
6 shouldn't proc now, it's been 9 seconds since last taste of blood/rend damage.
7 No proc - we should see the last proc now, not at number 6

Video demo: https://www.youtube.com/watch?v=c3u0vKu-EZ4
--- means taste of blood is on cd and it doesn't proc from rend damage.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Taste of blood should proc on 5th & 7th rend tick, and it should not proc on 6th rend tick.
##### STEPS TO REPRODUCE THE PROBLEM:

1.  get a warrior, level it it up to have at least 18 talent points
2. spend your points in arms tree and get 3/3 taste of blood
3.  get glyph of rending
4. use rend on a target dummy.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 2a2e54d) :

![WoWScrnShot_062421_143007](https://user-images.githubusercontent.com/82579073/123256958-3883b400-d4fa-11eb-9ca5-1ec6126c23ce.jpg)
![WoWScrnShot_062421_143937](https://user-images.githubusercontent.com/82579073/123257011-49ccc080-d4fa-11eb-9a2e-3a214f969fca.jpg)
![WoWScrnShot_062421_143945](https://user-images.githubusercontent.com/82579073/123257063-5a7d3680-d4fa-11eb-974b-40ea31538a01.jpg)
![WoWScrnShot_062421_143951](https://user-images.githubusercontent.com/82579073/123257109-68cb5280-d4fa-11eb-9ea8-50e21a15597c.jpg)

**Comment by necropola** [comment]
A combat log with time stamps would be even better.

**Comment by Eldarix** [comment]
omw

**Comment by Eldarix** [comment]
![WoWScrnShot_062421_143205](https://user-images.githubusercontent.com/82579073/123258329-ed6aa080-d4fb-11eb-8aae-23411e1dbc2d.jpg)
![WoWScrnShot_062421_143502](https://user-images.githubusercontent.com/82579073/123258400-fd828000-d4fb-11eb-8c4d-83bb7108e4ff.jpg)
![WoWScrnShot_062421_143535](https://user-images.githubusercontent.com/82579073/123258446-0d9a5f80-d4fc-11eb-8e35-7506a45b655b.jpg)

**Comment by Eldarix** [comment]
Not sure if it helps, that's what i've been able to reproduce :)

**Comment by necropola** [comment]
Hmm, you might need a different dummy on your local AC, e. g. the low level dummies from CC, or a higher level character in order to never miss a rend tick.

Also, Time stamps in Combat Log (Everything) would be nice.
![image](https://user-images.githubusercontent.com/7461137/123261528-28b6a080-d4f7-11eb-9b3b-6823611ef331.png)

**Comment by Eldarix** [comment]
Thx mate, i wasnt sure as well about the level difference, never played too much warrior in lich king.

**Comment by Eldarix** [comment]
If you can add the missing info necessary for the issue i'll be grateful :)

**Comment by necropola** [comment]
Gonna try this on my local AC, too. Later tonight that is.

**Comment by necropola** [comment]
@tbcxd @Eldarix Took a while, but here are teh combat logs for 5 tries each. Left side is with **Glyph of Rend** and the right side without it.

![Taste for Blood](https://user-images.githubusercontent.com/7461137/123422383-69c5b800-d5be-11eb-8a58-115f44529712.png)

**Comment by Eldarix** [comment]
awesome pal, thx for the further investigation :)
