### ISSUE TITLE
Feralas - Mobs Spawning Inside Trees

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6545]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/982

Ironfur bear GUID 50650 is spawned inside a tree.
![treebear](https://user-images.githubusercontent.com/80769357/123234265-17f83180-d4db-11eb-9d4c-dff3f023004c.jpg)

Longtooth Runner GUID 50875 is spawned inside a tree trunk
![treewolf](https://user-images.githubusercontent.com/80769357/123237585-1419de80-d4de-11eb-8919-8e9c31c4503b.jpg)

Tester: confirmed.

![WoWScrnShot_062421_224439](https://user-images.githubusercontent.com/81782124/123270239-e44ef300-d53e-11eb-848a-655d62637e5a.jpg)
![WoWScrnShot_062421_224611](https://user-images.githubusercontent.com/81782124/123270246-e5802000-d53e-11eb-93ac-e6f4573d23de.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should not spawn inside trees.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to provided GUID
2.  Observe his spawn point inside a tree

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Einkatzi** [comment]
I tested it. On my server (version of yesterday ~16:00 GMT) the Ironfur Bear spawns clearly and repeatedly besides the tree.
![WoWScrnShot_062421_172521](https://user-images.githubusercontent.com/60810320/123290835-dfc01580-d511-11eb-9903-77627eef03ea.jpg)
The same with the Longtooth Runner:
![WoWScrnShot_062421_173156](https://user-images.githubusercontent.com/60810320/123291511-768cd200-d512-11eb-8c3d-4b5fcb3e511a.jpg)

Operating System:
Windows 10

Modules:
none (that I know of)

Server:
AzerothCore (in Docker)

**Comment by Azcobu** [comment]
This is because you were inside the big trees when you took your screenshots. 

Objects in Wow don't show textures on their inner surfaces, so when you took the screenshots, it looked like you were standing in open forest. But if you had run a few meters in any direction, you would have clipped through the tree object's geometry and seen you were actually inside an object. Also, if you look at your screenshot of the Longtooth Runner, it clearly shows the clipping planes in the top/top right that shows it was also taken inside an object.
