### ISSUE TITLE
Mortal Strike doesn't reduce lay on hands healing.

### ISSUE THREAD

**Issue by lineagedr** [azerothcore/azerothcore-wotlk#655]
**Description**:
Mortal Strike doesn't reduce lay on hands by 50%
**Current behaviour**: Tell us what happens
Paladin has mortal strike debuff then casts lay on hands and his hp gets fully restored.
**Expected behaviour**: Tell us what should happen instead
Paladin has mortal strike debuff then casts lay on hands and his hp should be restored by half because of the mortal strike debuff
**Steps to reproduce the problem**:

1. 
Get Mortal Strike Debuff on your paladin
2. 
Cast Lay on hands.
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master
**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/421def048facabeb5dd5b7faa981bdefe120f302
**Operating system**:  
win64
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by xDevICCI** [comment]
what happen here?
