### ISSUE TITLE
[Hillsbrad Foothills] Gray Bear spawned underground

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6564]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/998

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [ ] enUS
- [X] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When you run toward a certain spot, a bear suddently aggro you from under the floor.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mob should be on the floor and visible, not under.

##### STEPS TO REPRODUCE THE PROBLEM:

DB GUID: 15226, current GUID: 9473.
Position: 217.498993 -982.937988 77.075996.

1. Run to Position: 217.498993 -982.937988 77.075996.
2. When you walk to the spot, the bear, that is inside the floor, will aggro you
3. bear will start to attack and comes out of the ground
![WoWScrnShot_062521_001051](https://user-images.githubusercontent.com/82708448/123338916-e79bac00-d549-11eb-8210-5d7c892903ad.jpg)
![WoWScrnShot_062521_001052](https://user-images.githubusercontent.com/82708448/123338933-ed918d00-d549-11eb-8234-7b5ae434f653.jpg)

##### EXTRA NOTES:

When this happens it seems that the bear stays here, like it should be, but at some point, he disapears on the ground.

EDIT: After a while the bear goes under the floor again but I still can see his name
![WoWScrnShot_062521_001417](https://user-images.githubusercontent.com/82708448/123339122-4f51f700-d54a-11eb-936a-8d5ce03659db.jpg)

Tester note: Bear is spawned underground, x 214.547623 y -983.760681 , 78.767494 is closest location above ground
![image](https://user-images.githubusercontent.com/20357406/123378846-8eee0280-d58d-11eb-8bb0-113b66e95cf1.png)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment]
I have a fix for this. I will try to open a PR.
