### ISSUE TITLE
DockerSetup Failure

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#6566]
Fresh New Host
Step by step with DockerSetup

**CURRENT BEHAVIOUR:**

WARNING: Image for service ac-build was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating azerothcore-wotlk_ac-database_1 ... done
Creating azerothcore-wotlk_ac-build_run  ... done
Deno version check:
Checking https://github.com/denoland/deno/releases/download/v1.9.1/deno-x86_64-unknown-linux-gnu.zip
30.1 MiB / 30.1 MiB (100.0%)
Deno is upgrading to version 1.9.1
Archive:  /tmp/.tmpTqGrnD/deno.zip
  inflating: deno                    
error: Permission denied (os error 13)
Installing Deno...
Warning: Failed to create the file /azerothcore/deps/deno/bin/deno.zip:       % #=#=-#   #                                                                   
Warning: Permission denied
                                                                           0.0%curl: (23) Failed writing body (0 != 1397)

ERROR: 23
error: Uncaught (in promise) Error: Failed with error: 23, however,
            it's not related to this Deno script directly. An error occurred within
            the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///data/azerothcore-wotlk/apps/docker/docker-cmd.ts:290:17)
    at async Promise.all (index 0)
    at async file:///data/azerothcore-wotlk/apps/docker/docker-cmd.ts:240:5

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. 
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

**OPERATING SYSTEM:**

Ubuntu18.04

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by betayi** [comment]
The First Step of Install Core：
./acore.sh docker client-data

**Comment by Kitzunu** [comment]
Dont ignore the template

**Comment by Kitzunu** [comment]
Closing, no update after 11 days.

Feel free to update your issue to follow the template and we will reopen it :)
