### ISSUE TITLE
[DB] Missing Tables/Fields from data/sql/base/db_world?

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#657]
**Current behavior**: Tell us what happens
 
>world.exe will not start due to missing database tables and fields. These tables are not on GIT.
https://github.com/azerothcore/azerothcore-wotlk/tree/master/data/sql/base/db_world

**Expected behaviour**: Tell us what should happen instead

> Missing Tables
>> gameobject_questitem
>> creature_questitem
>> quest_template_addon
>>

> Missing columns in table
>> creature_text
>> quest_template
>> pet_levelstats

After replacing this data, it complains about transmog tables, which arn't part of the base build right? It also complains about a lot of NPC scripts missing. I'm done for now, going back to my database!

**Steps to reproduce the problem**:

1. Run world.exe after using the db_assembler.

**AC hash/commit**:  
 
> dc15319625d4d6667f6d180b7816ba050dd03918

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

> Master

**Operating system**:  

>VMWare Workstation 12 running Win7x64

**Modules**:  Are you using modules? if yes, list them

> None

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

> None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by luisforte** [comment]
Same issue here, last revision.

**Comment by Yehonal** [comment]
If all tables are missing then you have not configures db assembler.
Otherwise please specify which are the missing tables

Il 02 Ott 2017 08:13, "luisforte" <notifications@github.com> ha scritto:

**Comment by luisforte** [comment]
Same tables 
Missing Tables

gameobject_questitem
creature_questitem
quest_template_addon
Missing columns in table

creature_text
quest_template
pet_levelstats

I used Navicat to import the WORLD_UPDATE and sql trow 2 erros (Missing procedure), after this i used HeidSQL and executed directly... Voilá no errors, but i see in console alot of missing creature_text ALOT.

Thanks

**Comment by Yehonal** [comment]
can you try to import sql via db_assembler directly? with assemble & import
option

2017-10-02 22:48 GMT+02:00 luisforte <notifications@github.com>:

**Comment by luisforte** [comment]
I will try today, i have compiled the new fix and i will replace the world DB with the new one

**Comment by STARRHELD** [comment]
I can't reproduce this error at all, must be with your local world_base.sql / world_updates.sql. Try to clone our repo from a fresh start and run db_assembler once again.
