### ISSUE TITLE
DB/Spell: Deep Freeze Immunity State proc

### ISSUE THREAD

**Issue by Dude100** [azerothcore/azerothcore-wotlk#6570]
**CURRENT BEHAVIOUR:**

The spell is triggered by https://wotlkdb.com/?spell=71761 (deep freeze immunity)
Basically if you use deep freeze (44572) and the target is immuned to freeze, deep freeze wil cast that spell that does 1k6 instead
For some reason, the spell is procing from every mage spell

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. make new character and test arcane and frost spec (all spec  affected of Deep freez)
2. cast Arcane blast and see whats happen https://postimg.cc/vDT686zy
2. 
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
AzerothCore rev. 2701ab447191+ 
**OPERATING SYSTEM:**

Debian 10 
**MODULES:**

no modules
**CUSTOMIZATIONS:**

no

**Comment by Meramaf** [comment]
[Deep Freeze Spell](https://wotlkdb.com/?spell=44572)

Video:  https://www.youtube.com/watch?v=FW8tVlrZI7w

**Comment by pklloveyou** [comment]
confirm

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/6015
It's caused here

**Comment by pklloveyou** [comment]
And the mount can't fly
And (headless knight) mount can't fly

**Comment by pklloveyou** [comment]
Fireball release will also trigger Deep Freeze Spell

**Comment by SoHigh495** [comment]
Death Knights wich are new created can't open the rune enchant book as well.

**Comment by Meramaf** [comment]
https://youtu.be/KX_bzwQxVW8   DK Spell Bug

**Comment by Kitzunu** [comment]
I will look but next time dont ignore the issue template and fill it out.

**Comment by T1ti** [comment]
The spell id that is triggering is 71757, not 44572 as stated above

**Comment by Kitzunu** [comment]
I was just about to comment that too, and that spell is triggered by https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=71761 which the mage learns on login/creation, which is correct behavior. The issue is that it should not proc the Deep Freeze effect.

It works on TC, so I am trying to figure out what differs. Because when it comes to learning it, it's the same on AC & TC

**Comment by T1ti** [comment]
The spell is triggered by https://wotlkdb.com/?spell=71761 (deep freeze immunity)
Basically if you use deep freeze (44572) and the target is immuned to freeze, deep freeze wil cast that spell that does 1k6 instead
For some reason, the spell is procing from every mage spell

**Comment by T1ti** [comment]
I have a theory, spell id 71761 is permanantly applied to the player from the skillLineAbility.dbc loader

**Comment by Kitzunu** [comment]
Works the same on TC, and I confirmed there that it is not proccing, but the player does learn it at creation

**Comment by T1ti** [comment]
.unlearn 71761 fixes it

**Comment by Kitzunu** [comment]
Well yes because then you remove Deep Freeze Immunity State. But there should be another way to do it as it works correctly on TC. I haven't had the time to investigate it yet

**Comment by T1ti** [comment]
Is the spell supposed to be learned or not ?
Not sure how the skillLineability loader works, maybe lvl 0 spells shouldn't be learnt?

**Comment by Kitzunu** [comment]
The skill line ability table contains definitions for skills, spells and the required dependencies. Like what spell superceeds the next one, if it is learned from trainer, when a skill is obtained or if it is used for racial spells.

What it really does is determining the players initial spells.

And as far as I can see it works as it should. All the correct spells are learned. And I am cross-referencing it to how it works on TC and in the regard of learning spells/skills on creation it is the exact same. Mages on TC also learns 71761, however it is not proccing on every spell. So my thinking right of the bat is that it has nothing to do with reading from skilllineability but instead with some other core mechanic of perhaps what the core classes as "permanently immune to stuns"

**Comment by Kitzunu** [comment]
I will test something

**Comment by T1ti** [comment]
_but instead with some other core mechanic of perhaps what the core classes as "permanently immune to stuns"_

regardless, it should only proc from deep freeze, not another spell

**Comment by Kitzunu** [comment]
I think I fixed it. Will test

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/6598 here, test it =)

**Comment by pklloveyou** [comment]
(headless knight) mount can't fly

**Comment by SKingOWN** [comment]
> Death Knights wich are new created can't open the rune enchant book as well.

This is not the issue for DK but I can confirm this. the new DK that learn the spell 53428 Rune Forge not work

**Comment by WillzDevs** [comment]
@Kitzunu @T1ti  is happening to you guys from Deep Freeze after the fix is ​​very high damage? Full gear PVP Furious at critical damage 8.6k from Deep Freeze.
Does the same thing happen to you?
![IMG-20210627-WA0019](https://user-images.githubusercontent.com/67213916/123550599-a28f9980-d744-11eb-9b4b-62f3732fbc81.jpg)

**Comment by SKingOWN** [comment]
I can confirm this. Now Deep Freeze don't Cast with every spell but It ignore the inmunity and make a very hight damage to all targets

**Comment by WillzDevs** [comment]
> I can confirm this. Now Deep Freeze don't Cast with every spell but It ignore the inmunity and make a very hight damage to all targets

@SKingOWN Comment on issue #6616 I opened it to report this issue
