### ISSUE TITLE
Shredder Operating Manual pages drop for the Alliance

### ISSUE THREAD

**Issue by Efymer** [azerothcore/azerothcore-wotlk#6572]
**Originally reported**: https://github.com/chromiecraft/chromiecraft/issues/1001

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Currently Shredder Operating Manual pages will drop for Alliance players, tested on Foulweald furbolgs (Warrior/Totemic).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They shouldn't.

##### SOURCE:

From https://wowpedia.fandom.com/wiki/Shredder_Operating_Manual_-_Page_1:
>Patch 1.8.0 (2005-10-10): Shredder Operating Manual pages will no longer drop for the Alliance.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to DB GUID=32947 as an Alliance character.
2. Kill some nearby Foulweald furbolgs like Warriors and Totemics.
3. Confirm the issue.

##### EXTRA NOTES:

Foulweald Warrior: https://wowgaming.altervista.org/aowow/?npc=3743
Foulweald Totemic: https://wowgaming.altervista.org/aowow/?npc=3750

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Hacaw** [comment]
I will work on this to provide a solution.

**Comment by necropola** [comment]
I'm wondering whether setting the `HORDE_ONLY` bit in `item_template.FlagsExtra` for all `Shredder Operating Manual - Page %`  items solves it.

### Before
```SQL
SELECT `entry`, `name`, `FlagsExtra` FROM `item_template` WHERE `name` LIKE 'Shredder Operating Manual - Page %' ORDER BY entry;
+-------+-------------------------------------+------------+
| entry | name                                | FlagsExtra |
+-------+-------------------------------------+------------+
| 16645 | Shredder Operating Manual - Page 1  |          0 |
| 16646 | Shredder Operating Manual - Page 2  |          0 |
| 16647 | Shredder Operating Manual - Page 3  |          0 |
| 16648 | Shredder Operating Manual - Page 4  |          0 |
| 16649 | Shredder Operating Manual - Page 5  |          0 |
| 16650 | Shredder Operating Manual - Page 6  |          0 |
| 16651 | Shredder Operating Manual - Page 7  |          0 |
| 16652 | Shredder Operating Manual - Page 8  |          0 |
| 16653 | Shredder Operating Manual - Page 9  |          0 |
| 16654 | Shredder Operating Manual - Page 10 |          0 |
| 16655 | Shredder Operating Manual - Page 11 |          0 |
| 16656 | Shredder Operating Manual - Page 12 |          0 |
+-------+-------------------------------------+------------+
12 rows in set (0.000 sec)

```

**Comment by Zenslash** [comment]
Hi, I just tried this, but the loot still dropped out. Maybe I did something wrong ...

> I'm wondering whether setting the `HORDE_ONLY` bit in `item_template.FlagsExtra` for all `Shredder Operating Manual - Page %` items solves it.
> 
> ### Before
> ```sql
> SELECT `entry`, `name`, `FlagsExtra` FROM `item_template` WHERE `name` LIKE 'Shredder Operating Manual - Page %' ORDER BY entry;
> +-------+-------------------------------------+------------+
> | entry | name                                | FlagsExtra |
> +-------+-------------------------------------+------------+
> | 16645 | Shredder Operating Manual - Page 1  |          0 |
> | 16646 | Shredder Operating Manual - Page 2  |          0 |
> | 16647 | Shredder Operating Manual - Page 3  |          0 |
> | 16648 | Shredder Operating Manual - Page 4  |          0 |
> | 16649 | Shredder Operating Manual - Page 5  |          0 |
> | 16650 | Shredder Operating Manual - Page 6  |          0 |
> | 16651 | Shredder Operating Manual - Page 7  |          0 |
> | 16652 | Shredder Operating Manual - Page 8  |          0 |
> | 16653 | Shredder Operating Manual - Page 9  |          0 |
> | 16654 | Shredder Operating Manual - Page 10 |          0 |
> | 16655 | Shredder Operating Manual - Page 11 |          0 |
> | 16656 | Shredder Operating Manual - Page 12 |          0 |
> +-------+-------------------------------------+------------+
> 12 rows in set (0.000 sec)
> ```

Hi, I just tried this, but the loot still dropped out. Maybe I did something wrong ...

```sql
UPDATE `item_template` SET `FlagsExtra` = 1 WHERE `entry` BETWEEN 16642 AND 16656;
```

**Comment by necropola** [comment]
They are **not** identical. One is a **Chapter** and the other is a **Page**.

**Comment by Zenslash** [comment]
> @Zenslash They are **not** identical. One is a **Chapter** and the other is a **Page**.
> Did you restart your `worldserver` after making the change to force a DB reload?

No, I only reloaded the use ```.reload all``` in the game and also tried to clear the cache and restart the game.
I'll try to restart ```worldserver``` now

**Comment by Zenslash** [comment]
It looks like everything is working fine now

**Comment by necropola** [comment]
@Zenslash WTF!

**Comment by Zenslash** [comment]
> @Zenslash WTF!

I already deleted mine, so everything is fine. There was a misunderstanding)
