### ISSUE TITLE
Scarlet Monastery: Cathedral, indirect pulling does not trigger room wide

### ISSUE THREAD

**Issue by iEmpress** [azerothcore/azerothcore-wotlk#6575]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When you pull pull Scarlet Commander Mograine(https://wotlkdb.com/?npc=3976), in the Cathedral of Scarlet Monastery he should and does pull the entire Cathedral.

However, if you pull him by proximity of a fleeing mob this behaviour is not shown. Instead he pulls unchained to the rest of the mobs allowing you to bypass clearing out the Cathedral.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

No matter mob proximity or a direct pull he should pull the rest of the mobs.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Pull 3-4 mobs in the pack before the boss in cathedral.
2. Let them flee into the boss without chasing.
3. Boss runs into the group solo.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
hi @iEmpress , you can use [this template](https://raw.githubusercontent.com/chromiecraft/chromiecraft/main/issue_template.md) to report bugs found on ChromieCraft, so it will have all technical details already filled in ;)

for more info about how we handle the bug reporting and triaging for both players and volunteers, please read: https://github.com/chromiecraft/chromiecraft#for-players-how-to-report-bugs

cc @azerothcore/bug-triaging

**Comment by Shineslippers** [comment]
The issue is confirmed.

https://user-images.githubusercontent.com/85256266/146373474-e401c4b7-dd0a-4d26-868e-2535f0a909c7.mp4

.
