### ISSUE TITLE
Eversong Woods: (Dead Scar) multiple mobs not wandering when idle

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6585]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1004

##### CURRENT BEHAVIOUR:

Multiple mobs located along the Dead Scar in Eversong Woods are fixed in place and not exhibiting normal wandering behavior for their mob type, even after resetting aggro.

### Mobs affected (marked in screenshots):
**Plaguebone Pillager**- Entry: 15654

DBGUID: 
- Skull: 56058
- X: 56059

**Angershade**- Entry: 15656

DBGUID: 
- Star: 56086

**Rotlimb Marauder**- Entry: 15658

DBGUID:
- Circle: 56127
- Square: 56160
- Triangle: 56162
- Diamond: 56125
- Moon: 56123
- Skull: 56166
- X: 56150

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mobs that are fixed in place should wander around while not in combat

##### SOURCE:

Countless other mobs nearby of the same type that wander when idle
##### STEPS TO REPRODUCE THE PROBLEM:

1. .go creature (DBGUID#)
2. aggro each mob and run away until they drop out of combat/leash back to their spawn point
3. observe that the mobs remain fixed in place while idle, unlike others of their kind that will wander around

##### EXTRA NOTES:

Plaguebone Pillager https://wowgaming.altervista.org/aowow/?npc=15654 Marked: Skull and X
![WoWScrnShot_062521_204613](https://user-images.githubusercontent.com/83389835/123500604-e4192b00-d604-11eb-8ba6-c00e6b7d9ad6.jpg)

Angershade https://wowgaming.altervista.org/aowow/?npc=15656 Marked: Star (yellow)
Rotlimb Marauder https://wowgaming.altervista.org/aowow/?npc=15658 Marked: Circle and Square
![WoWScrnShot_062521_211250](https://user-images.githubusercontent.com/83389835/123500632-2478a900-d605-11eb-993a-b52a6ddcbf41.jpg)

Rotlimb Marauder cont. Marked: Triangle
![WoWScrnShot_062521_212127](https://user-images.githubusercontent.com/83389835/123500650-3fe3b400-d605-11eb-8898-ccab37a0ef4b.jpg)

Marked: Diamond (purple) and Moon
![WoWScrnShot_062521_212437](https://user-images.githubusercontent.com/83389835/123500659-54c04780-d605-11eb-839a-1064cf3708da.jpg)

Marked: Skull
![WoWScrnShot_062521_213025](https://user-images.githubusercontent.com/83389835/123500675-69044480-d605-11eb-8e05-3510516fdb71.jpg)

Marked: X
![WoWScrnShot_062521_222111](https://user-images.githubusercontent.com/83389835/123500685-6f92bc00-d605-11eb-9943-2764b292beb0.jpg)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 2a2e54d) :

![WoWScrnShot_062621_071457](https://user-images.githubusercontent.com/82579073/123501657-354e0c80-d64f-11eb-99fb-7d6223dcdc03.jpg)
![WoWScrnShot_062621_071542](https://user-images.githubusercontent.com/82579073/123501672-46971900-d64f-11eb-87ad-53a56175e50b.jpg)
![WoWScrnShot_062621_071653](https://user-images.githubusercontent.com/82579073/123501683-57478f00-d64f-11eb-93c6-db61888e573f.jpg)
![WoWScrnShot_062621_071714](https://user-images.githubusercontent.com/82579073/123501696-68909b80-d64f-11eb-864b-314dcfb40c5c.jpg)
![WoWScrnShot_062621_071743](https://user-images.githubusercontent.com/82579073/123501704-76462100-d64f-11eb-97dc-02433925e73f.jpg)
![WoWScrnShot_062621_071801](https://user-images.githubusercontent.com/82579073/123501710-865e0080-d64f-11eb-9612-1d02d3a32071.jpg)
![WoWScrnShot_062621_071822](https://user-images.githubusercontent.com/82579073/123501722-970e7680-d64f-11eb-9c1b-f6076cf81b08.jpg)
![WoWScrnShot_062621_071852](https://user-images.githubusercontent.com/82579073/123501730-a8f01980-d64f-11eb-9614-09fa90cbb1cc.jpg)
![WoWScrnShot_062621_071927](https://user-images.githubusercontent.com/82579073/123501738-b907f900-d64f-11eb-88eb-3519ce19e663.jpg)
![WoWScrnShot_062621_072004](https://user-images.githubusercontent.com/82579073/123501746-c91fd880-d64f-11eb-980c-98e4a24ff50f.jpg)

**Comment by Cold-Martijn** [comment]
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56058;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56059;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56086;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56127;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56160;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56162;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56125;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56123;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56166;
UPDATE `creature` SET `wander_distance` = 5 WHERE `guid` = 56150;

You can also run this just incase some of them don't have movementtype 1 enabled:
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56058;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56059;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56086;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56127;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56160;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56162;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56125;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56123;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56166;
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 56150;
