### ISSUE TITLE
"The Affray" warrior quest bugged

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6587]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Cannot be completed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should be completed when the last Npc is defeated.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Make a level 30 warrior.
2. .quest add 1719 (or in a classic way accepting and completing the previous (the islander) from the npc trainer of warriors in stormwind.
3. Try to complete the combat event.
4. See if it the quest is finished.

##### AC HASH/COMMIT:

2a2e54d

##### OPERATING SYSTEM:

Windows 10 21H1 

##### MODULES:

No.

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

AzerothCore Local

The problem came right after completing the previous quest "The Islander" (i suppose doing a .quest add will make the same) :

![WoWScrnShot_062621_075053](https://user-images.githubusercontent.com/82579073/123502443-308c5700-d655-11eb-975b-686ddd60b9bf.jpg)
![WoWScrnShot_062621_075105](https://user-images.githubusercontent.com/82579073/123502445-413ccd00-d655-11eb-8331-bd99651620b9.jpg)
![WoWScrnShot_062621_075121](https://user-images.githubusercontent.com/82579073/123502457-5285d980-d655-11eb-9e82-d8ea3e5ca701.jpg)

As you can see, I was able to enter the ring without problem, but after defeating 'Big Will', the battle phase is reset and you have to defeat all the NPCs again, including a clone of the original 'Big Will' :

![WoWScrnShot_062621_075146](https://user-images.githubusercontent.com/82579073/123502543-e061c480-d655-11eb-86f7-b1657f22c918.jpg)
![WoWScrnShot_062621_075336](https://user-images.githubusercontent.com/82579073/123502549-f079a400-d655-11eb-8e09-22d30418f689.jpg)
![WoWScrnShot_062621_075556](https://user-images.githubusercontent.com/82579073/123502553-fff8ed00-d655-11eb-9593-b3bc27a939a5.jpg)
![WoWScrnShot_062621_075605](https://user-images.githubusercontent.com/82579073/123502565-0edf9f80-d656-11eb-90a1-30fe2135d784.jpg)
![WoWScrnShot_062621_075727](https://user-images.githubusercontent.com/82579073/123502571-1dc65200-d656-11eb-875d-5b32706d7ec3.jpg)

After that, the mission simply fails and the counter reaches zero:

![WoWScrnShot_062621_075736](https://user-images.githubusercontent.com/82579073/123502593-49493c80-d656-11eb-82f6-ea6fbe0af137.jpg)
![WoWScrnShot_062621_080223](https://user-images.githubusercontent.com/82579073/123502602-582fef00-d656-11eb-9867-c00eea722845.jpg)

**Comment by Eldarix** [comment]
I wasn't sure about making a separate report, but since they're linked quests, I considered it correct so, suggest me otherwise and I'll fix it without problem.

**Comment by IntelligentQuantum** [comment]
![Screenshot_20210908_203447](https://user-images.githubusercontent.com/14080516/132545244-18121d72-f4ca-4f67-bd98-6f0f3dbbb6ac.png)
![Screenshot_20210908_203501](https://user-images.githubusercontent.com/14080516/132545945-777cd0af-12fe-4092-9354-d662fe1194b7.png)

It works fine for me
