### ISSUE TITLE
Mail system problem

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/azerothcore-wotlk#659]
When sending mail with more than one item and the receiver and sender are from the same acount only one item arrive. the rest of the item remain in the db table mail_item.

Some times it happens also on chars of different account 

All te item are received by the receiver,

**Steps to reproduce the problem**:

1. Open your account select char send mail with 3 items to one char of your same account
2. Logout 
3. Receive mail.

master

AzerothCore rev. efbcb8f65d35 2017-09-23 11:30:22 +0200 (master branch) (Unix, Release) (worldserver-daemon)

DEBIAN 9 

ANTICHEAT
PREMIUM
TRANSMOG
DUELRESET

clang  report many unused variables during compilation

**Comment by avatar789** [comment]
I confirm the problem. Stacks do not come

**Comment by Inifield** [comment]
Fixed in https://github.com/azerothcore/azerothcore-wotlk/commit/a2957f53b09027d00a4d513fb8ff8ec4e6fd79d0
