### ISSUE TITLE
Mage with very high damage from spells, even without any items equipped

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6597]
**CURRENT BEHAVIOUR:**
Mage with very high damage from spells, even without any items equipped. Character without any spell bonus hitting as if with high gear.
Below is the video showing the damage of spells:
https://youtu.be/bPHdB6j_w7U

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Low damage without item

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**
1. Create a mage and train spells
2. find a dummy to test
3. Use spells, you'll see massive damage

**EXTRA NOTES:**

**AC HASH/COMMIT:**

> 27b20261aeb9+

**OPERATING SYSTEM:**
Windows

**MODULES:**
mod-anticheat
mod-bg-reward
mod-cfbg
mod-eluna-lua-engine
mod-npc-beastmaster
mod-npc-free-professions
mod-pvpstats-announcer
mod-spell-regulator
mod-transmog

**CUSTOMIZATIONS:**

**Comment by Dude100** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6570

**Comment by T1ti** [comment]
video is not working

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/123527974-249ba600-d6e4-11eb-944f-b3f167ae9e1d.png)
confirmed, mage spells proc a "deep freeze" spell

**Comment by T1ti** [comment]
this is extremly high priority the class is broken

**Comment by Kitzunu** [comment]
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6570

**Comment by WillzDevs** [comment]
> video is not working

try looking again please
