### ISSUE TITLE
Core/Mechanic: Hit / Armor penetration

### ISSUE THREAD

**Issue by Dilemmast** [azerothcore/azerothcore-wotlk#660]
**Description**: Spell hit + armor pen not working in PvP / PvE

**Current behaviour**: Class must be in hit cap to not miss spells but now in AC with 0 spell hit i tests with a Priest shadow cast over 20 spells (include instant or with cast time) but not miss any spells.

**Steps to reproduce the problem**:

1. create shadow priest
2. add items but save spell hit on 0 hit
3. target any thing you behavior  
4. see not miss or ressist
5. can check armor pen too . is equal damage in items with armor pen gems and  with out armor pen

i thing this is new bug because all thing is working good before https://github.com/azerothcore/azerothcore-wotlk/commit/b32a9b244bcbc3938b92b65c6e4162a83e22a717
**Branch(es)**: master 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
> i thing this is new bug because all thing is working good before b32a9b2

finally a good report!

**Comment by Dilemmast** [comment]
@ShinDarth thanks bro . New updates makes source with lot of bugs . I try to report important of that.

**Comment by ShinDarth** [comment]
@Dilemmast that happens when you don't have many testers for PRs, unfortunately.

Thanks for your help!

**Comment by Yehonal** [comment]
That commit you linked is not related with armor penetration. It is a fix for tenacity in WG and does not impact outside of that battlefield.

Could you do a deeper test to understand if it change really from that commit?

**Comment by Dilemmast** [comment]
@Yehonal i told all think like armor pen or hit working good before that commit my old source is before that commit. I not say this changed on that commit it should be change in an update after that commit . I have source before that and a latest source in latest not working but in old working good

**Comment by Yehonal** [comment]
Ok thanks then i ll check, however you missed the hash of your current
commit, please update the issue

Il 26 Set 2017 10:20, "Dilemmast" <notifications@github.com> ha scritto:

**Comment by Dilemmast** [comment]
@Yehonal guy i find my source version :
My core version : master 2017/06/10
We must check commits after https://github.com/azerothcore/azerothcore-wotlk/commit/b32a9b244bcbc3938b92b65c6e4162a83e22a717 and before 2017/06/10

**Comment by Yehonal** [comment]
So is that commit your current commit? If yes please update to the latest master revision if you can.

**Comment by Dilemmast** [comment]
@Yehonal i now really cant update . But i test latest after 3~4 hour

**Comment by lineagedr** [comment]
Actually it's a Sunwell bug. I've just tested on a Sunwell core, and out of 20 spell casts on 0 hit rating I only got 1 miss if lucky. There has been times where 20 spells would hit and not a single miss on 0 hit rating.

**Comment by farsidesoul** [comment]
Were you testing on the target dummies? 

I noticed the other day the boss target dummy cannot be missed, however real world mobs take hit/expertise into account.

**Comment by Dilemmast** [comment]
@farsidesoul  i tested on dummies characters and etc . not working in Azerothcore

**Comment by Si1ker** [comment]
Cannot confirm, spell hit will be variable on char level vs npc/boss level.
