### ISSUE TITLE
Core/Player: Rogues not getting runeforging skill when learning

### ISSUE THREAD

**Issue by SKingOWN** [azerothcore/azerothcore-wotlk#6604]
**CURRENT BEHAVIOUR:**

New DKs after make the quest that teach spell 53428 can't open It.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Create a new DK
2. Make quest until you learn spell 53428
3. Try to open it

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
634fceabe1698071a42b1c0e5da349e5b03b254b

**OPERATING SYSTEM:**

Ubuntu 20.04

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Meramaf** [comment]
Confirm

**Comment by Kitzunu** [comment]
Fix here https://github.com/azerothcore/azerothcore-wotlk/pull/6612
