### ISSUE TITLE
BUG：Does not support dual lines

### ISSUE THREAD

**Issue by q67732897** [azerothcore/azerothcore-wotlk#661]
After compiling the latest azerothcore
Can not use two lines
http://i4.bvimg.com/610535/ffe5f0696625d52f.jpg
http://i4.bvimg.com/610535/a5cb3718a2128866.jpg
Old azerothcore will not have that problem
The latest azerothcore will have this problem

**Comment by ShinDarth** [comment]
please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
