### ISSUE TITLE
Core/Spell: Deep Freeze deals dmg to non-stun immune targets

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6616]
**CURRENT BEHAVIOUR:**
The spell Deep Freeze is with very high damage follow the photo below;
![IMG-20210627-WA0019](https://user-images.githubusercontent.com/67213916/123551494-6827fb80-d748-11eb-8f32-6ab0b5c7c0a7.jpg)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
The damage has to be based on blizzlike, Below is the spell;
https://wotlk.evowow.com/?spell=58534

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Creates a mage with spec frost
2. Go to a dummy to test
3. Use the spell, and you'll see the high damage.

**EXTRA NOTES:**

**AC HASH/COMMIT:**

> 27b2026

**OPERATING SYSTEM:**
Windows

**MODULES:**
mod-anticheat
mod-bg-recompensa
mod-cfbg
mod-eluna-lua-engine
mod-npc-beastmaster
mod-npc-free-professions
mod-pvpstats-announcer
mod-spell-regulator
mod-transmog

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
and what is blizzlike?

**Comment by Kitzunu** [comment]
Also in the photo is a critical strike. What gear is your character using, gems, glyphs? Or is this a naked level 80? Please give more information

**Comment by WillzDevs** [comment]
> and what is blizzlike?

Sorry, the way I expressed it was wrong =)
I wanted to say that the damage would have to be according to the original of the spell that is on the link below

**Comment by WillzDevs** [comment]
> Also in the photo is a critical strike. What gear is your character using, gems, glyphs? Or is this a naked level 80? Please give more information

That's what I said, the character has Furious PVP gear, it's not for damage to be like that.

**Comment by Kitzunu** [comment]
Please test it on a naked level 80 with no talents, no nothing. My guess is that you have spellpower or something

**Comment by WillzDevs** [comment]
Ok

**Comment by WillzDevs** [comment]
> Please test it on a naked level 80 with no talents, no nothing. My guess is that you have spellpower or something

I tested it with the naked character, and it appeared...but I think I found the problem, the high damage happens when activating the talent Fingers of Frost in the Frost spec, it is not reducing cast and damage is increasing when activated.
I recorded 2 videos, one using Deep Freeze without fingers of Frost and another video using fingers activated. I will link the videos below...

[https://youtu.be/BO6lvxkkH-s](url)

[https://youtu.be/6De9Nj5kimA](url)

**Comment by Kitzunu** [comment]
@azerothcore/testers can someone look at this...

**Comment by WillzDevs** [comment]
@T1ti can you tell me if this problem is happening to you?
Looking at the videos I left above =)

**Comment by T1ti** [comment]
Nope, damages are completely normal for me with figners of frost active !
it deosn't reduce cast time btw, are you thinknig of icy veins ?

**Comment by T1ti** [comment]
Also it deosn't show if you crit or not, 9300 crit if it does 5920 non crit looks normal

**Comment by Kitzunu** [comment]
In the screenshot it shows 8000 crit. And imho it looks okay.

**Comment by WillzDevs** [comment]
I just did the test with the nude character, and created 6k of Deep Freeze, and before to test, updated the core and databases...

**Comment by T1ti** [comment]
test without modules, especially mod-spell-regulator

**Comment by WillzDevs** [comment]
> test without modules, especially mod-spell-regulator

Even without modifying the spellregulator table can it affect?

**Comment by T1ti** [comment]
I don't know this module, it's up to you to figure it

**Comment by WillzDevs** [comment]
V I will test without the modules

**Comment by Dude100** [comment]
i confirm 
video: https://youtu.be/8Z4bJHhS3rI
 [https://postimg.cc/N9W0Z9Hw](url)

hash: 2701ab447191

**Comment by WillzDevs** [comment]
> i confirm
> video: https://youtu.be/8Z4bJHhS3rI
> [https://postimg.cc/N9W0Z9Hw](url)

Thanks!! I thought I was going crazy hahaha

**Comment by T1ti** [comment]
how is this confirming anything?

**Comment by WillzDevs** [comment]
Deep Freeze hitting a critical hit of 10k with Furious gear, or almost 6k with a naked character, I think that should confirm something, doesn't it?

**Comment by T1ti** [comment]
no ? he does 2700 base which seems completely normal with a few freeze talents (he has water elemental)
I'm doing ~2500 without any frost dmg talent.
Deep freeze is rougly ~1605dmg base(there's a 273 rng roll, it's up to 1741) + 45dmg per lvl after 60 (+900 at lvl 80)
So deep freeze should be doing **up to 2500 naked without any frost talent**

Which perfectly matches my testing, I was doing 2400ish and he does 2700 with some frost talents.
Spells crits do 150% dmg base(so up to 3750) , 200% if you have the shatter talent(up to 5000)

The numbers i'm seeing in those vids look normal, shatter has a 2.143 spell scaling coeff so 9k ish with vicious gear seems normal ?

**Comment by WillzDevs** [comment]
So hitting 9k from Deep Freeze is normal with Furious gear?
I'm finding it strange because before the update that gave the problem that kitzunu solved the Freeze finger by activating every spell, it was normal, there was no damage, you understand?

**Comment by T1ti** [comment]
it's very simple math, you can do it yourself

**Comment by T1ti** [comment]
taht's for the dmg aprt though, now isn't deepf reeze dmg only suppposed to proc vs targets permanently immune to stuns ? which players aren't
Imo the dmg is only supposed to proc vs bosses, not players who aren't stun immune

**Comment by T1ti** [comment]
because I don't think it should proc vs players and small creatures, it's supposed to only do dmg vs bosses imo

**Comment by WillzDevs** [comment]
but if the server is based on PvP how will I do it then? proc vs player damage is pretty high

**Comment by T1ti** [comment]
> but if the server is based on PvP how will I do it then? proc vs player damage is pretty high

if it's confirmed then it should get fixed. I'm not sure of that I don't main mage, but to me it seems pretty clear it shouldn't do damage vs players
![image](https://user-images.githubusercontent.com/40864460/123839543-8723ba80-d90d-11eb-9cc8-ec000b4dfa31.png)

**Comment by Kitzunu** [comment]
sounds reasonable

**Comment by T1ti** [comment]
seems related again to players learning the permanant stun immune spell on creation from the new skillineability loader

gotta check if that bug existed before

**Comment by WillzDevs** [comment]
Thank you so much for paying attention to this, I thank you from my heart!!

**Comment by Kitzunu** [comment]
The spell isnt scripted anywhere, so it would have the same behaviour

**Comment by WillzDevs** [comment]
> The spell isnt scripted anywhere, so it would have the same behaviour
So what is going on? Because I've tested it in many ways, called friends who play with the class for years and actually everyone said the damage was too high =(

**Comment by WillzDevs** [comment]
> The spell isnt scripted anywhere, so it would have the same behaviour


@Kitzunu  can you ask me a question? Below I'm going to link 2 photos of Deep Freeze Talent..1 I removed it from the site and the other one is on my server...can you tell me which one is right? both have the same ID.
But the damage values ​​are different...
![Screenshot_20210630-210947-970](https://user-images.githubusercontent.com/67213916/124046661-da1e7000-d9e8-11eb-9386-a896ca322254.png)

![IMG_20210630_211522162_HDR](https://user-images.githubusercontent.com/67213916/124046679-e0ace780-d9e8-11eb-9466-9f6fe6f66495.jpg)

**Comment by WillzDevs** [comment]
Somebody?

**Comment by Kitzunu** [comment]
I will lock this conversation as nothing useful is being added.


Bug: Deep Freeze proc dmg on targets that are not permanently immune to stuns.

**Comment by Kitzunu** [comment]
Fixed https://github.com/azerothcore/azerothcore-wotlk/pull/6787
