### ISSUE TITLE
Warrior's One-Handed Weapon Specialization isn't increasing Thunderclap dmg

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6617]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1018

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Currently the Warrior's Thunderclap skill is not effected by putting talent points into One-handed Weapon Specialization.
![image](https://user-images.githubusercontent.com/68164076/123554084-46704980-d733-11eb-9c74-5564a128d2c2.png)
After putting 5/5 into 1H Weapons
![image](https://user-images.githubusercontent.com/68164076/123554103-63a51800-d733-11eb-9116-8c001b3d3c9d.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

https://wowgaming.altervista.org/aowow/?spell=16542
One-Handed Weapon Specialization is a protection talent which increase the physical damage dealt by the warrior when an one-handed weapon is equipped by 10% at 5/5 level.
Thunderclap's damage should be increased by the talent mentioned above as it is a physical damage skill

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use thunderclap
2. Spec 5/5 One-Handed Weapon Specialization
3. Use thunderclap again
4. The damage of second thunderclap will be the same as the first one.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
What? Thunder Clap's damage is based on weapon damage? Never heard about it.

**Comment by UltraNix** [comment]
Stump876  
What? Thunder Clap's damage is based on weapon damage? Never heard about it.

**Comment by UltraNix** [comment]
@Stump876  
What? Thunder Clap's damage is based on weapon damage? Never heard about it.

**Comment by Stump876** [comment]
I don't think it's based off weapon damage, but it's still physical damage, correct? 
![image](https://user-images.githubusercontent.com/68164076/127747966-192cf1dd-f4f5-4d38-a2a2-1817a3c1367f.png)
1 handed spec increases all physical damage. 
![image](https://user-images.githubusercontent.com/68164076/127747886-8c6bc25a-0fc4-423c-9e1e-5dbdaad0a24c.png)

**Comment by UltraNix** [comment]
Many spells are physical, but not weapon-based.
Description of that talent is misleading - it does not increase all the damage you done, but only that is done by 1h weapon (or spells requires/based on 1h weapon)

**Comment by syssneck** [comment]
The tooltip is pretty clear to me. The damage of Thunder Clap (physical) should be increased by 2/4/6/8/10% when a 1H weapon is equipped.
It is correct, that the ability is not weapon-based. A weak and strong 1h weapon will deal the same damage with Thunder Clap, as long as the attack power is unaffected.
This issue has nothing to do with weapon-based or not. It is simply a condition, that checks if a 1h weapon is equipped and then adds the right percentage to the multiplier for all physical damage.

**Comment by UltraNix** [comment]
So what about other physical spells, like Cleave or Overpower? They all are not affected by this bonus.

**Comment by syssneck** [comment]
I didn't test it, but if this is the case, then they should also do more damage The physical damage buff shouldn't be applied to each spell individually, but instead like an invisible aura (passive) that boosts all physical damage, so that there is no need to change every spell with One-Handed Weapon Specialization.

I just saw, that the spell got changed sometime between Vanilla and TBC:
In Vanilla/Classic it says: "Increases the damage you deal with One-Handed Melee weapons by 2%." [Here](https://classic.wowhead.com/spell=16542/one-handed-weapon-specialization)
And it changed too: "Increases physical damage you deal when a one-handed melee weapon is equipped by 2%." [Here](https://tbc.wowhead.com/spell=16542/one-handed-weapon-specialization)

It seems like this is some residue from MaNGOS that went unnoticed until now?

**Comment by UltraNix** [comment]
Okay.

**Comment by T1ti** [comment]
Don't base it of tooltips, get in game proof from blizzard servers
