### ISSUE TITLE
Aspect of the Cheetah: not dazed when taking fire damage from bonfires

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6618]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1022

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Currently, having Aspect of the Cheetah ( https://wowgaming.altervista.org/aowow/?spell=5118 ) on and taking damage from a bonfire or campfire will not get your dazed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All sources of damage should get you dazed.

##### SOURCE:

This is from retail Classic WoW: https://youtu.be/MZ95-1ggpfU?t=18300
The hunter has Aspect of the Cheetah on, then gets close to the campfire and gets dazed.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a hunter, activate Aspect of the Cheetah.
2. Run to a campfire or bonfire (for instance I remember that the bonfire at the base of Orgrimar flight tower used to daze me).
3. Witness not getting dazed.

##### EXTRA NOTES:

I don't think the spell changed with TBC, but the description changed, it now says "when struck". Nonetheless, someone from the Classic WoW/TBC Classic hunter discord server confirmed that you should still get dazed.
I suspect the same issue happens with Aspect of the Pack.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by sergeyburnos** [comment]
This is not anymore applicable starting from TBC, found it https://www.youtube.com/watch?v=dtuJG6vedkA time 12:00. I did tested on my WoW classic TBC account as well, it is not dazed anymore, as it was on wow classic.
Edit: also comments on wowhead
https://tbc.wowhead.com/spell=5118/aspect-of-the-cheetah#comments
