### ISSUE TITLE
Spell Reflection [Warrior]

### ISSUE THREAD

**Issue by Dilemmast** [azerothcore/azerothcore-wotlk#662]
**Description**: Warrior Spell Reflection not working with all feature. 

**Current behaviour**: When Warrior Cast spell Reflection and a DK cast Deathgrip on warrior must be Dk go on warrior and reflect this spell. but not working

**Expected behaviour**: Can you check trinitycore -> https://github.com/TrinityCore/TrinityCore/commit/f0772eea98c66f7fd2e745c0cfb8599d6c21ef19

**Steps to reproduce the problem**:

1. Create warrior 
2. duel with a dk
3. cast Spell reflection and dk cast spell DeathGrip on warrior . See Not reflect

**Branch(es)**: master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/0a03149432a969cbd7aa4904b64accfe6f88cb99

**Operating system**:  Se7en

@ShinDarth @Yehonal :)

**Comment by ShinDarth** [comment]
> AC hash/commit: Latest

"latest" is not a valid information, please copy and paste the actual value

**Comment by ShinDarth** [comment]
no I mean that even if your commit it actually the "latest", as soon as another developer commits something else, your issue will no longer be tested on "latest". So just avoid writing "latest" but put the actual value instead ;)

Thanks for your help!

**Comment by Dilemmast** [comment]
@ShinDarth i changed commit after you . Sorry for fault

**Comment by Dilemmast** [comment]
@ShinDarth i changed commit after you told . Sorry for my faullt

**Comment by Dilemmast** [comment]
@ShinDarth i changed commit after you told . Sorry for my fault

**Comment by lineagedr** [comment]
Are you sure it doesn't reflect Death Grip? Also this https://github.com/TrinityCore/TrinityCore/commit/f0772eea98c66f7fd2e745c0cfb8599d6c21ef19 is not related to reflecting spells. It reflects dispels and removes a buff from caster that casted dispel on the warrior.

**Comment by Dilemmast** [comment]
Update to latest . Fix this issue . Close
