### ISSUE TITLE
Feature: Queue arena with opposite faction

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#6620]
**Describe your feature request or suggestion in detail**
Allow for players to queue ranked/skirmish arenas with the opposite faction on the same team, through a option in worldserver.conf, just like we already have with action house, raids, guild.

**Describe a possible solution to your Feature or Suggestion in detail**
Maybe its better to do it through a module.

**Additional context**
I think with a feature like that, players could enjoy the game more. 
  Lets say you have a friend that only has one character in the opposite faction and want to do arenas, with this feature/module you could play with your friend without needing to change faction.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/mod-cfbg Either it is already done there, or it should be done there. Arenas are a type of Battleground
