### ISSUE TITLE
[Inscription] Skill up with grey Minor Inscription Research

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6626]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/155

##### ISSUE: FACTION SIDE:

![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png) & ![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:

Any phase, I'd think.

##### SMALL DESCRIPTION:

I earned a profession skill level from a gray recipe, namely Minor Inscription Research.
![Profession Increase on Gray Recipe](https://user-images.githubusercontent.com/78349628/110222038-28858d00-7e95-11eb-9c5c-07a929cd20e8.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Gray recipes should never give a skill increase.
[Wowwiki Page](https://wowwiki-archive.fandom.com/wiki/Gray#Gray_Recipes)

I saw a lot of other posts that said as much, but mostly as comments on wowhead and profession guides.

##### CURRENT BEHAVIOUR:

I did my Minor Inscription Research today and got a skill up. This is the first time I've noticed it and that recipe has been gray for me for quite a while. Not sure if this would impact other, non-cooldown, recipes. I haven't noticed any when making inks or anything.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1. Give yourself inscription. 
Step 2. Remove the cooldown for professions.
Step 3. Perform several Minor Inscription Research and see if you get any skill ups. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/c2f274e06dcf85c6ccc0ab282dd6f23e8ce49c8f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
@FrancescoBorzi What `SkillChance.Grey` is set in Chromie server in worldserver config?

**Comment by Helias** [comment]
I think the default one, I'll check later

**Comment by UltraNix** [comment]
So it's weird.

**Comment by UltraNix** [comment]
So it's weird.

**Comment by UltraNix** [comment]
Did anybody encounter that bug?

**Comment by FrancescoBorzi** [comment]
@azerothcore/bug-triaging can anyone help here?

**Comment by Asthalor** [comment]
Im trying to replicate the issue. Looks like she crafted a Scroll of Protection II (1478) but i cant find the recipee to craft that on the trainer. Is that the recipee that triggered it or she just happened to buy it before the screenshot?

**Comment by Asthalor** [comment]
Not every glyph increase the skill. I learned then Glyph of the penguin, glyph of frost armor, glyph of shakle undead and not a single skill point added.

Glyph of shadow protection added 1 skill point too.

![image](https://user-images.githubusercontent.com/87535580/131388005-978d137d-4d84-4365-9378-8c1fa820b6d3.png)

**Comment by UltraNix** [comment]
It's not the scrolls updating your skills, but learned glyphs - there is some chance to update skill. I don't see a bug here. If you didn't get new skill points by Minor Inscription Research, you wouldn't learn new glyphs because of low skill.
