### ISSUE TITLE
Fishing will occasionally fish up a blank loot screen

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6633]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1030

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Occasionally when fishing when you click the bobber a blank loot window will pop up. 

This has nothing to do with skill, to eliminate that argument I gave myself every fishing buff I could think of as well as max fishing while testing this. So I should 100% catch a fish and not have it vendor trash.
![image](https://user-images.githubusercontent.com/68164076/123732854-6563fe00-d84f-11eb-8924-38a9922886c4.png)
I still fished up a blank. 
![image](https://user-images.githubusercontent.com/68164076/123734879-04d6c000-d853-11eb-9b98-1ba6d11009b6.png)

https://wowwiki-archive.fandom.com/wiki/Fishing "As of 3.1, there is no longer a minimum skill requirement to fish in any zone, and **all casts will catch something and award a chance for a skill-up**. However, if your skill level is too low for a zone, you will catch mostly vendor trash items. The skill level required to guarantee "no junk" catches is equivalent to the old "no get away" level."

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Using Fishing skill and properly reeling should always rewards the player with something as follows:
- if the player has enough skill in Fishing, assigned to the zone they fish, they should get proper fish from that area with according chance for a skill up
- if the player has not enough skill in Fishing, assigned to the zone they fish, they should get junk catches with also according chance for a skill up

##### SOURCE:
https://wowwiki-archive.fandom.com/wiki/Fishing 

##### STEPS TO REPRODUCE THE PROBLEM:

1. train fishing
2. .set 356 450
3. .additem 19970, 19971, 7996, 50287, 6553 5, 38802
4. .cast 59645 (Hungry Tuskarr) This should out level fishing for all of 3.3.5 (600 is max for MOP)
5. Turn off auto loot and fish.
6. Eventually you will get a blank. It only took me a minute or two in the Dalaran sewers.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
It's a DB bug - there is a condition for reference that contains that item: https://www.wowhead.com/item=45328/bloated-slippery-eel#comments. That's why player cannot see this item without quest.
