### ISSUE TITLE
Mount can't fly

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#6634]
Mount can't fly

**CURRENT BEHAVIOUR:**
.c 48025
.c 72286
.c 75614
Mount can't fly

**EXPECTED BLIZZLIKE BEHAVIOUR:**
fly

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**
.c 48025
.c 72286
.c 75614
Mount can't fly

**EXTRA NOTES:**
It's caused here
https://github.com/azerothcore/azerothcore-wotlk/pull/6015

**AC HASH/COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Kitzunu** [comment]
fixed https://github.com/azerothcore/azerothcore-wotlk/pull/6671
