### ISSUE TITLE
Feature: Reduce spam for BG queue announcer [$20]

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#6637]
**Describe your feature request or suggestion in detail**

Despite the recently added config options in https://github.com/azerothcore/azerothcore-wotlk/pull/6114, the BG queue announcer can still be spammy in certain situations. For example, when a BG ends, most players instantly join the queue only a few seconds apart. This will result in a line posted per player to join the queue in the chat currently.

For example...
```
Warsong 19-39: 1/4
Warsong 19-39: 2/4
Warsong 19-39: 3/4
Warsong 19-39: 4/4
Warsong 19-39: 5/4
Warsong 19-39: 6/4
Warsong 19-39: 7/4
```
... when 7 players re-join.

**Describe a possible solution to your Feature or Suggestion in detail**

I'm suggesting adding a timer (per BG and bracket), which starts running instead of posting the queue update instantly. When the timer (**a configurable value**, for example 15 seconds) is up, the BG queue announcer posts one single line. So instead of the above, there would be only...

```
Warsong 19-39: 7/4
```
...in the chat.

**Additional context**

**Comment by Winfidonarleyan** [comment]
If I have time, I'll try to do it this weekend

**Comment by Winfidonarleyan** [comment]
What should happen after the player has joined the queue?

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan for example, imagine 3 players join one after each other. This is what should happen:

`TIMER = 500ms` (configurable value in milliseconds)

1) Player 1 queues, a timer starts and nothing gets printed until the timer goes to `0`

2) Player 2 queues after `200ms`, the timer resets to `0`

3) Player 3 queues after `300ms`, the timer resets to `0`

4) The timer reaches `500ms`, so the BG queue announcement is printed, only the one from the last event. In this case only `3/4` gets printed

This is called **Debouncing**

![debounce](https://rxjs.dev/assets/images/marble-diagrams/debounce.png)

in this case `b` doesn't get printed because `c` happens right after it

https://rxjs.dev/api/operators/debounce

**Comment by FrancescoBorzi** [comment]
@55Honey what you described is **throttling**, which is very similar to **debouncing** and I guess both would work for our case

A visual representation:

http://demo.nimius.net/debounce_throttle/

I still think debounce is a bit better for our case, as there could be cases where throttling doesn't prevent all the spam.

For example, let's suppose we set the timer to 500ms and the following queues happen at the given time:

- 100ms
- 400ms
- 600ms

With debouncing (what I described),  we would have only 1 queue message (delayed of 500ms). While with throttling (what @55Honey described), we would have 2 queue messages (the one after 400ms and then right after it the one which happened at 600ms).

The only "downside" of debouncing is that all queue messages will be delayed, but the delay is not much so I don't think it is really a downside.

**Comment by 55Honey** [comment]
I thought of a 30-second timer for the throttling :)

The real scenario is this:
Let's say a BG just ended. 10 players were inside it and all re-join the q. 
- Two join 1 second after the BG ended, clicking leave/queue immeadiately.
- Four players join after 3 seconds due to a longer loading screen
- Player 7+8 join the queue after 7 seconds. They had a brief look at the BG stats before leaving.
- Player 9+10 take a detailed look at the stats and leave the bg after 20 seconds, immediately re-joining.

With a debounce method of -lets say- 1000ms, there are 4 messages in the chat now.
With a throttling, there would be exactly one message after -again config example- 30 seconds. It's impossible to become more spammy than that.

While the debounce system might work now, it requires very good tuning for 
- low pop times (longer timer)
- high pop times (shorter timer)
With a longer debounce config flag we run a large risk of the queue being never announced or way too late. With a too low debounce we have the same spam as it is now.

What I could think of, is a debounce system with high thresholds (maybe 10000 ms) **and** a limiter (no more debounce past 60000ms). -> If we forbid the timer to go past 1 minute total from the first join, we'd have a guaranteed print, even tho people keep joining/leaving.

**Comment by FrancescoBorzi** [comment]
@55Honey makes sense, alright then. We can have this with a simple throttling timer that is configurable (default to 0 seconds).

cc @Winfidonarleyan
