### ISSUE TITLE
You can use mount inside Grom'gol Base Camp Inn.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6640]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other frFR

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1033

##### CURRENT BEHAVIOUR:

When you run inside Grom'gol Base Camp Inn, you're not dismounted.
You can also get on your mount when you're inside the Inn.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you enter the inn you're supposed to be dismount and not be able to use the mount inside.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Grom'gol Base Camp
2. Mount
3. Go inside the inn
4. You're still mounted inside and can unmount & cast it again.

https://user-images.githubusercontent.com/82708448/123773841-38563080-d8cd-11eb-9f93-f213074d07d6.mp4

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 53ab534) :

![WoWScrnShot_062921_142355](https://user-images.githubusercontent.com/82579073/123789569-f84f7780-d8e5-11eb-9560-8676844bc0f0.jpg)
![WoWScrnShot_062921_142408](https://user-images.githubusercontent.com/82579073/123789615-08ffed80-d8e6-11eb-814c-4eba9bd391c9.jpg)
![WoWScrnShot_062921_142427](https://user-images.githubusercontent.com/82579073/123789665-14ebaf80-d8e6-11eb-9c36-556d54dc2552.jpg)

**Comment by UltraNix** [comment]
It's not a bug. If client allows to mount up, it's intended.
