### ISSUE TITLE
Fishliver Oil inscreases spell haste

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6641]
**CURRENT BEHAVIOUR:**

Using Fishliver Oil (quest reward https://wowgaming.altervista.org/aowow/?item=1322 ) will grant 100 spell haste, while the tooltip says that it only increases melee haste.
![WoWScrnShot_062921_132513](https://user-images.githubusercontent.com/81818678/123789726-c3d7bd80-d8dd-11eb-9a1b-ed9651a29998.jpg)
In the screenshot you can see that Greater Heal cast time is now reduced from 3 seconds. Also, it is correctly displayed in the character sheet.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Fishliver Oil should only increase melee haste.

**SOURCE:**

See tooltip.

**STEPS TO REPRODUCE THE PROBLEM:**

1. Use Fishliver Oil as a caster ( .additem 1322 )
2. See that your spell cast speed are reduced

**EXTRA NOTES:**

N/A.

**AC HASH/COMMIT:**
 

AzerothCore rev. 63b48a906d17 + 2021-06-29 08:58:28 +0000 (master branch)

**OPERATING SYSTEM:**

Windows 10

**MODULES:**

None? I've only followed the steps from https://www.chromiecraft.com/how-to-install-a-wow-server-on-your-own-computer/

**CUSTOMIZATIONS:**

None.

**Comment by FrancescoBorzi** [comment]
@pop-pig don't forget to apply the content label :)

e.g. "generic", "1-19", "20-29", etc...

**Comment by pop-pig** [comment]
Sorry didn't know if it should be labeled as Generic or something else ^^

**Comment by Einkatzi** [comment]
I guess you (pop-pig) went by this description https://tbc.wowhead.com/spell=7396/fishliver-oil where only melee hasting is mentioned.
However, https://wowpedia.fandom.com/wiki/Haste#Patches_and_hotfixes says that for WotLK (3.0.2+), "Haste Rating now modifies both melee attacks and spells."
So I'd say: no bug.

**Comment by pop-pig** [comment]
I checked again on wowhead and came across this comment: https://www.wowhead.com/item=1322/fishliver-oil#comments:id=523804
So maybe it's not a bug, but the phrasing implies that it only affects melee haste.

**Comment by Einkatzi** [comment]
Yes, that comment was written after Patch 3.0.2 came out, so the change was already in effect. Maybe Blizz forgot to adapt the tooltip in the client to reflect the change - it still says "melee haste".

**Comment by pop-pig** [comment]
I'll close the issue then, thanks!
