### ISSUE TITLE
If you join a guild whilst a Guild Charter is in your bags, it locks/breaks the guild charter.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#6642]
**CURRENT BEHAVIOUR:**

If you join a guild whilst a Guild Charter is in your bags, it locks/breaks the guild charter. You cannot activate or open the charter anymore.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

I don't know what the behaviour SHOULD be, but it shouldn't create a bricked/broken item in your bags.

**SOURCE:**

https://classic.wowhead.com/item=5863/guild-charter

**STEPS TO REPRODUCE THE PROBLEM:**

1. Create guild charter and get 1 signature
2. Join a guild
3. Leave the guild
4. Observe broken/bricked charter item

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

AzerothCore rev. cecbd604d3f5 2021-06-29 00:45:12 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by claudiodfc** [comment]
Don't really agree with this one. When opening a bug report it means you know what should be happening instead, which you don't so that's a pretty red flag. How are we supposed to fix something that we don't even know is a bug?

**Comment by JamesGent** [comment]
There's no way on Earth that it's blizzlike for items to Brick out and become undeleteable objects that do nothing.

The correct behaviour is "this doesn't happen".

**Comment by Kitzunu** [comment]
I believe you shouldnt be able to join a guild if you own a guild charter

**Comment by UltraNix** [comment]
Hmm, having guild charter does not mean you are already in guild, so joining to other guild in my opinion should be able.
