### ISSUE TITLE
[Mage] [Gnome female] Cone of Cold not oriented "forward"

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6643]
**CURRENT BEHAVIOUR:**

I was going around in the world on a local AC server and thought that my female gnome mage's Cone of Cold looked weird.
It looks like she is Cone of Colding out of her left hand, which makes the gust of wind go left instead of forward.
Here is a video (sorry speed was set on 3): https://youtu.be/Cbd5fmfr3Io

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Cone of Cold should make the wind go forward.

**SOURCE:**

Here is a video from retail classic WoW, of a female gnome mage using Cone of Cold: https://youtu.be/kMonp1ZYHkQ?t=13

**STEPS TO REPRODUCE THE PROBLEM:**

1. Create a female gnome mage
2. ".levelup 79"
3. ".learn all my class"
4. Use Cone of Cold (in the Frost spells)

**EXTRA NOTES:**

N/A.

**AC HASH/COMMIT:**
 

AzerothCore rev. 63b48a9 + 2021-06-29 08:58:28 +0000 (master branch)

**OPERATING SYSTEM:**

Windows 10

**MODULES:**

None.

**CUSTOMIZATIONS:**

None.

**Comment by UltraNix** [comment]
Cannot reproduce it.

**Comment by FrancescoBorzi** [comment]
@pop-pig can you please help to reproduce this issue?

**Comment by UltraNix** [comment]
@pop-pig Are you there?

**Comment by pop-pig** [comment]
Hi, sorry I haven't been very active lately, I've been very busy with IRL.
I'll try to re-reproduce the issue and update the issue.
Thanks!

**Comment by UltraNix** [comment]
@pop-pig Any results?

**Comment by pop-pig** [comment]
Hi,
Sorry I still have not been able to find the time to test this again, but if you can't reproduce it I suggest we close the issue for now, and if/when I can reproduce the issue I'll reopen it.
