### ISSUE TITLE
recent clang change broke builds on raspios (Raspberry Pi 4)

### ISSUE THREAD

**Issue by pythonicca** [azerothcore/azerothcore-wotlk#6645]
**AC HASH/COMMIT:**
3b58f56

**STEPS TO REPRODUCE THE PROBLEM:**

1. Install raspios_lite_arm64 on Raspberry Pi 4 (8GB)
2. Follow guide for Linux: https://www.azerothcore.org/wiki/installation
3. receive cmake clang error:

> CMake Error at src/cmake/compiler/clang/settings.cmake:20 (message):
  Clang: AzerothCore requires version 10.0.0 to build but found 7.0.1

**EXTRA NOTES:**
Building (and running) AzerothCore on the Raspberry Pi 4 (8GB) worked previously (2021-05) but broke recently when you changed the clang requirement to Clang 10 from Clang 7. Clang 10 isn't available for raspios_arm64; the requirement change has effectively blocked success builds for anyone using this configuration.

Is there a specific feature of Clang 10 that you're using for AzerothCore that doesn't exist in Clang 9 (which _is_ available on raspios_arm64)?

I ask because other projects (both mangos & cmangos) still compile without problems.

reference:
https://www.azerothcore.org/wiki/linux-requirements

text as of 2021-06-29:

> **Your clang version MUST be 7** or higher (here you can check the versions that run in our Github Actions pipeline, we recommend to use one of those versions).

conflicting text, (same page) as of 2021-06-29:

> MySQL ≥ 5.7.0
> Boost ≥ 1.67
> CMake ≥ 3.16
> **Clang ≥ 10**

**OPERATING SYSTEM:**
Raspberry Pi OS 64bit
https://downloads.raspberrypi.org/raspios_lite_arm64/images/

**Comment by Kitzunu** [comment]
@FrancescoBorzi

**Comment by Winfidonarleyan** [comment]
Hah, you can fork this repo and change min clang support. Now we don't support Raspberry.

**Comment by FrancescoBorzi** [comment]
@pythonicca thanks for your report. Unfortunately supporting older versions of clang was slowing down our developers from time to time and we realised it was not really worth it.

> Is there a specific feature of Clang 10 that you're using for AzerothCore that doesn't exist in Clang 9 (which is available on raspios_arm64)?

@Winfidonarleyan can probably tell you more about this

**Comment by pythonicca** [comment]
@ Zanthed Thank you, that worked.

For anyone else that needs it here's what you need:

`sudo nano /etc/apt/sources.list`

_append this to the end:_

`deb http://deb.debian.org/debian buster-backports main`

_save and exit nano_

`sudo apt update`
`sudo apt install -t buster-backports clang-11`

**Comment by FrancescoBorzi** [comment]
@pythonicca thanks for confirming that it worked for you
