### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Dilemmast** [azerothcore/azerothcore-wotlk#665]
**Description**: Memory Leak

**Current behaviour**: World server eating ram after 5-6 hours . you must restart System.

**Expected behaviour**: i thing 10 gb ram is perfect for 6 - 10 players online :)

**Branch(es)**: master

**AC hash/commit**:  my commit https://github.com/azerothcore/azerothcore-wotlk/commit/100da17e85225503caaae5d136c8e49dfe392c96

**Operating system**:  Windows Server 2012 R2 64bit
RAM : 10 GB

**Modules**:  anticheat - transmog - premium

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
> Branch(es): 0.x / 1.x / master

so you tried all branches or just too lazy to replace the template with your actual branch? :D

**Comment by Dilemmast** [comment]
:| @ShinDarth i forget to choose my branch and you are so clever :)

**Comment by Inifield** [comment]
Unconfirmed, try without anticheat

**Comment by Dilemmast** [comment]
@Inifield okay i try to check without anticheat but this problem is possible of my operating system? this is Windows server 2012 ?

**Comment by Maurowin** [comment]
I played alone during 5h and i haven't memory leak with commit 6b08fd2f6136+ i used 1247Mo of memories.
Acutally i'm disconnecter and i used 513Mo.

**Comment by lineagedr** [comment]
https://github.com/TrinityCore/TrinityCore/commit/a3faa57f3b623cfb7eafa56745d93d66061e2f35

**Comment by fmrmx** [comment]
This is a very serious issue, the memory keeps increasing over and over.

**Comment by Rochet2** [comment]
If someone wants to analyse what is wrong, see these linux tools:
- Valgrind https://youtu.be/fvTsFjDuag8
- ASan, LSan: https://github.com/google/sanitizers/blob/master/README.md

**Comment by Viste** [comment]
this can help partially https://github.com/TrinityCore/TrinityCore/commit/fc852181c578e2ab8644bebfef13199a7897ebe9

**Comment by Viste** [comment]
here we have memory leak to if need i can make PR

**Comment by fmrmx** [comment]
@Viste does it worked for you?

**Comment by BarbzYHOOL** [comment]
@ShinDarth Viste said it's a partial fix

**Comment by Sdyess** [comment]
The core is easily filled with memory leaks, it's a massive code base maintained by amateurs & hobbyists with a ton of old code. Issue should stay closed, could be reopened with a valgrind log or something similar.

**Comment by BarbzYHOOL** [comment]
Only few people have experience with it there (and I'm not one of them)

**Comment by fmrmx** [comment]
Memory leak is still present and very critical, core start eating memory slowly , but it will never stop, no matter how many ram you have it will eat all eventually.
![ramus](https://user-images.githubusercontent.com/5169055/38183681-f99e56e4-3607-11e8-8ad2-23c620dd1aab.png)

**Comment by Sdyess** [comment]
Show me a higher RAM usage first. 2.3GB used isn't much, cells will start to load as the server is used. Until someone posts a valgrind log and does this without modules, this probably won't be looked at.

**Comment by fmrmx** [comment]
Yes it is a high usage, TrinityCore Uses less than 1.6 GB with 30+ online, but the problem is not the 2.3 Ram The Problem is that it still keeps growing forever, any other text written is only excuses.

**Comment by BarbzYHOOL** [comment]
I also had same concerns when switching from TC, but finally, no.

**Comment by FrancescoBorzi** [comment]
## AzerothCore ram usage explanation

http://www.azerothcore.org/wiki/Memory-Usage
