### ISSUE TITLE
Vendor NPC's with Gossip are not displaying their Gossip 

### ISSUE THREAD

**Issue by Efymer** [azerothcore/azerothcore-wotlk#6651]
**CURRENT BEHAVIOUR:**

There seems to be a general issue displaying Gossips for NPCs under certain conditions.
Right now, NPCs only will show their Gossip + Vendor option if they also have a quest to offer.
Let me explain:

If you filter creature_template with this query:

`SELECT entry, npcflag, gossip_menu_id FROM creature_template WHERE npcflag = 385`

You get a list of NPCs that should have this attributes: GOSSIP, VENDOR and VENDOR_AMMO.

However, if you visit them one by one ingame, you will notice that none of them shows the gossip, but instead it just sells stuff directly, even though they have a `gossip_menu_id` in place.

In the other hand,

Now, if you filter by: 
`SELECT entry, npcflag, gossip_menu_id FROM creature_template WHERE npcflag = 387`

You get a list of NPCs that should have this attributes: GOSSIP, VENDOR, VENDOR_AMMO AND **they are also QUEST_GIVERS**

And what's my surprise? SOME of them will show the gossip ONLY if they have a quest to offer.

Example:

**Quartermaster Lewis** - NPC ID 491 with npcflag = 387

![WoWScrnShot_062821_215535](https://user-images.githubusercontent.com/79163132/123696069-9fd39800-d85b-11eb-94a3-25e6b10dde43.jpg)

**Quartermaster Lymel** - NPC ID: 16187 with npcflag = 387 WITHOUT a quest (quest not showing because of requirements and she should show a gossip accordingly https://wowpedia.fandom.com/wiki/Quartermaster_Lymel)

![WoWScrnShot_062821_215717](https://user-images.githubusercontent.com/79163132/123696759-63546c00-d85c-11eb-9660-d741dc722309.jpg)

So its weird, npcs will only show their gossip if they have a quest to offer as well......

**EXPECTED BLIZZLIKE BEHAVIOUR:**

- The NPCs should display the Gossip and the option to see the items they are selling.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1.  Described above.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
[8f640a1ce9d0](https://github.com/azerothcore/azerothcore-wotlk/commit/8f640a1ce9d0ec286cab52f15cff1317c518d50d)

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Raelorasz** [comment]
If an NPC only has **one** gossip option that is not GOSSIP_OPTION_GOSSIP ( so most vendors, trainers, flightmasters ) the client automatically picks that option for you. To fix that one only needs to add FORCE_GOSSIP flag to `type_flags` in `creature_template` and delete the client's Cache folder. 
The problem is identifying which NPCs need this flag, I've noticed there's quite a lot of them.

**Comment by iraizo** [comment]
> If an NPC only has **one** gossip option that is not GOSSIP_OPTION_GOSSIP ( so most vendors, trainers, flightmasters ) the client automatically picks that option for you. To fix that one only needs to add FORCE_GOSSIP flag to `type_flags` in `creature_template` and delete the client's Cache folder.
> The problem is identifying which NPCs need this flag, I've noticed there's quite a lot of them.

Shouldnt that be quite easy when it only happens to the ones that only have one gossip option

**Comment by Raelorasz** [comment]
> Shouldnt that be quite easy when it only happens to the ones that only have one gossip option

I don't think so since I think this is also going to affect quests which count as "options" as well. Also I have no idea which behaviour is blizzlike, since the FORCE_GOSSIP thing seems to be... forced :] and right now there's only 7 NPCs that have that flag on.

**Comment by claudiodfc** [comment]
must check if these npcs have flag gossip

**Comment by Raelorasz** [comment]
> 
> 
> must check if these npcs have flag gossip

Of these 7 NPCs that have FORCE_GOSSIP only 3 also have npcflag GOSSIP

**Comment by UltraNix** [comment]
On TC there is 17 NPCs (on AC - 16). `type_flags` are taken from sniffs so I believe they are correct. 
I don't see bug here unless got an evidence from retail.

**Comment by Efymer** [comment]
> On TC there is 17 NPCs (on AC - 16). `type_flags` are taken from sniffs so I believe they are correct.
> I don't see bug here unless got an evidence from retail.

@UltraNix 
This report was made based on an investigation of https://github.com/azerothcore/azerothcore-wotlk/issues/6614
And according to wowpedia the NPC should have a gossip https://wowpedia.fandom.com/wiki/Eralan


It was also mentioned in Discord when I asked a few months ago, according to @claudiodfc it could have broken by him  https://discord.com/channels/217589275766685707/284323424032129024/859774487653122078 because this used to work in AzerothCore.

**Comment by UltraNix** [comment]
@Efymer Checked that commit and it's not the cause of these problems.

**Comment by Efymer** [comment]
@UltraNix but that's not how it should be no?

From TBC Classic:

![WoWScrnShot_090321_174006](https://user-images.githubusercontent.com/79163132/132032040-768fb782-36db-4e88-b58f-98e5ec46432b.jpg)

**Comment by UltraNix** [comment]
Maybe they changed that in classic? Or that NPC have that flag. We don't have sniffs from Classic, so not sure about it.

**Comment by Efymer** [comment]
Well, we do have sniffs from Classic. 

Another example:

NPC flags (same as AzerothCore btw):

![Captura](https://user-images.githubusercontent.com/79163132/132038372-ea4535fc-dd5f-4078-8e47-52e1fd79a56e.PNG)

Classic TBC:

![WoWScrnShot_090321_182619](https://user-images.githubusercontent.com/79163132/132038433-89c1dbea-4985-4654-9c70-f26a1dc89bea.jpg)

AzerothCore:

https://streamable.com/spizzs

**Comment by UltraNix** [comment]
@Efymer Where I can find these sniffs?

**Comment by Efymer** [comment]
@UltraNix check AzerothCore Discord, I tagged you.
