### ISSUE TITLE
Quest credit messages for quest completion missing

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#6652]
**EXPECTED BLIZZLIKE BEHAVIOUR:**

Whenever you complete the requirements for quests such as talking to a non playable character or whenever you explore a mine in Elwyn Forest, you should get a yellow message on the top of the screen displaying the quest completion status.

**CURRENT BEHAVIOUR:**

Whenever you get a requirement complete, there's no message to the player which can lead to confusion. The best example I can remember is the Elwyn Forest quest for exploring the mine, which is credited by an area trigger or the `Liutenant's Insigna` quest that Thrall gives you to provoke Neeru Fireblade.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. .q a 5727
2. Talk to Neeru Fireblade and see that on quest completion, there's no yellow message about quest completion status, but on the log it's registered as complete.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
33c271cc7c19

**OPERATING SYSTEM:**

Windows 10

**MODULES:**

None

**CUSTOMIZATIONS:**

Legion models

**Comment by Efymer** [comment]
Added as Confirmed since when I started playing in ChromieCraft I also noticed that.
