### ISSUE TITLE
Asynchronous connections on DatabasePool terminated. Proceeding with synchronous connections.

### ISSUE THREAD

**Issue by Greyisttot** [azerothcore/azerothcore-wotlk#6654]
AzerothCore rev. 63b48a906d17+ 2021-06-29 08:58:28 +0000 (master branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
                                 ██████╗ ██████╗ ██████╗ ███████╗
                                ██╔════╝██╔═══██╗██╔══██╗██╔════╝
                                ██║     ██║   ██║██████╔╝█████╗
                                ██║     ██║   ██║██╔══██╗██╔══╝
                                ╚██████╗╚██████╔╝██║  ██║███████╗
                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

     AzerothCore 3.3.5a  -  www.azerothcore.org

> Using configuration file       configs/worldserver.conf.
> Using SSL version:             OpenSSL 1.1.1j  16 Feb 2021 (library: OpenSSL 1.1.1  11 Sep 2018)
> Using Boost version:           1.72.0
> Using ACE version:             6.5.10

Process priority class set to HIGH
Opening DatabasePool '1_auth'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool '1_auth' opened successfully. 2 total connections running.
 
Opening DatabasePool '1_characters'. Asynchronous connections: 1, synchronous connections: 2.
DatabasePool '1_characters' opened successfully. 3 total connections running.
 
Opening DatabasePool '1_world'. Asynchronous connections: 1, synchronous connections: 1.
DatabasePool '1_world' opened successfully. 2 total connections running.
 
Closing down DatabasePool '1_auth'.
Asynchronous connections on DatabasePool '1_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool '1_auth' closed.
Could not prepare statements of the Login database, see log for details.
Closing down DatabasePool '1_world'.
Asynchronous connections on DatabasePool '1_world' terminated. Proceeding with synchronous connections.
All connections on DatabasePool '1_world' closed.
Closing down DatabasePool '1_characters'.
Asynchronous connections on DatabasePool '1_characters' terminated. Proceeding with synchronous connections.
All connections on DatabasePool '1_characters' closed.
Closing down DatabasePool '1_auth'.
Asynchronous connections on DatabasePool '1_auth' terminated. Proceeding with synchronous connections.
All connections on DatabasePool '1_auth' closed.

**Comment by Kitzunu** [comment]
Don't ignore the issue template
