### ISSUE TITLE
[Warrior] Victory Rush is spammable if it is used as the killing blow [$30]

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6657]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I noticed how Victory rush is still bugged. I can infinitly use it. First I kill a mob, then the second mob my last hit would be [Execute] but instead of using [Execute] I use [Victory Rush]. Because of that there will be a problem occuring in codes making me infinitly use it. 
![image](https://user-images.githubusercontent.com/86686088/123856828-d7a51300-d921-11eb-85ed-c7c96bbb5efe.png)
as seen in the picture above tested with my friend. 

Here is a badly recorded video on a local AC server: https://youtu.be/drGbSmA_7A8?t=77
( AzerothCore rev. 63b48a906d17 + 2021-06-29 08:58:28 +0000 (master branch) )

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Using Victory Rush as the killing blow should not let you spam Victory Rush over and over afterwards.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to any mob that holds experience or honor nearby.
2. Kill that mob and make sure you have victory rush.
3. Go to the second mob and hit it till its 1%HP (or very low health).
4. Kill the 2nd mob with victory rush.

##### EXTRA NOTES:

Originally reported https://github.com/chromiecraft/chromiecraft/issues/1039

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
@claudiodfc Is this a regression caused by https://github.com/azerothcore/azerothcore-wotlk/pull/6349?

**Comment by claudiodfc** [comment]
My PR is definitely the issue, I'm looking at it right now
