### ISSUE TITLE
[SPELL] Stealth rogue

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#666]
**Description**:
The thief's futivity is bugged. 

**Current behaviour**: Tell us what happens
Indeed, when one approaches too much of a monster one aggro it directly.

**Expected behaviour**: Tell us what should happen instead
Normally, one should surprise the monster that turns towards our direction indicating that if one gets closer he will see us.

**Steps to reproduce the problem**:

1. play rogue
2. use Stealth
3. walk near a monster

**Branch(es)**: Master 

**AC hash/commit**:  6b08fd2f6136

**Operating system**:  Win10 and ubuntu server 16.04

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by cmsimike** [comment]
I feel the same way about stealth.

**Comment by farsidesoul** [comment]
Aggressive mobs that can see a rogue in stealth will attack the rogue, not simply turn towards it.  I'm not sure what the issue is here.

**Comment by STARRHELD** [comment]
I think this issue is referring to the slight move a creature does when the player is within a certain range of the creature while in stealth. This usually happens when the creature got blue swirly thing above its head, like guards in major capital cities.

**Comment by dunjeon** [comment]
I can confirm that stealth is not working as intended... in fact, the entire aggro system is broken and the rogue stealth could just be a representation of the aggro bug.

**Comment by BarbzYHOOL** [comment]
Duplicate
