### ISSUE TITLE
[Warrior] Killing a target with Intercept makes you unable to auto-attack other targets

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6669]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you kill a target with intercept you cannot attack another target with melee attacks until you charge or intercept again.

Here is a video, reproduced on a local AC server: https://youtu.be/xQTTALFsAX8
AzerothCore rev. c8a4b8190cb6+ 2021-06-30 22:47:41 +0000 (master branch)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should not disjoint your location.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Select a level 1 target as a higher level warrior.
2. Intercept the mob killing it.
3. Try to auto-attack a new target.

**EXTRA NOTES:**

Originally reported https://github.com/chromiecraft/chromiecraft/issues/1045

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**CURRENT BEHAVIOUR:**

**EXPECTED BLIZZLIKE BEHAVIOUR:**

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. 
2. 
3. 

**AC HASH/COMMIT:**
 

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by Azcobu** [comment]
Note the exact same issue also affects the warlock's Felguard pet when it uses Intercept, as detailed in https://github.com/azerothcore/azerothcore-wotlk/issues/6065. (Ignore the irrelevant issue name, it's about Intercept.)

**Comment by disclosurez** [comment]
confirmed same issue
