### ISSUE TITLE
[MONSTERS] WOLF

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#667]
**Description**:
aggro of monsters neutral

**Current behaviour**: Tell us what happens
When you right click too close to a neutral watch without knocking it on the aggro it is those who are close

![wowscrnshot_092817_001117](https://user-images.githubusercontent.com/31663279/31030809-f0678236-a556-11e7-8252-58ba71dd596f.jpg)

**Expected behaviour**: Tell us what should happen instead
Right click without aggro a neutral monster and so do not attract its neutral neighbors also

**Steps to reproduce the problem**:

1. create human
2. right clic near a wolf
3. and see

**Branch(es)**: Master 

**AC hash/commit**:  6b08fd2f6136

**Operating system**:  Win10 and ubuntu server 16.04

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
DELETE FROM `creature_template` WHERE `entry` = 69;
DELETE FROM `creature_template` WHERE `entry` = 299;

INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Health_mod`, `Mana_mod`, `Armor_mod`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES 
(69, 0, 0, 0, 0, 0, 31048, 0, 0, 0, 'Diseased Timber Wolf', NULL, NULL, 0, 2, 2, 0, 32, 0, 1, 0.85714, 1, 0, 2, 2, 0, 26, 1, 2000, 2000, 1, 0, 2048, 0, 1, 0, 0, 0, 0, 1, 1, 100, 1, 1, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13060, 0, 0, 0, '', 1, 1, 1, 1, 1, 1, 0, 100, 1, 0, 2, '', 12340),
(299, 0, 0, 0, 0, 0, 31049, 0, 0, 0, 'Diseased Young Wolf', '', NULL, 0, 1, 1, 0, 32, 0, 1, 0.85714, 1, 0, 2, 2, 0, 24, 1, 2000, 2000, 1, 0, 2048, 0, 1, 0, 0, 0, 0, 1, 1, 100, 1, 1, 299, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13059, 0, 0, 0, '', 1, 1, 1, 1, 1, 1, 0, 100, 1, 0, 2, '', 12340);


please test this fix and let me know

**Comment by BarbzYHOOL** [comment]
Don't use that horrible query above, use this instead
    UPDATE creature_template SET flags_extra =+ 2 WHERE entry IN (69,299);

It does the same thing and yes, it fixes the issue. I don't know if it's the proper way but it fixes these damn wolves.

Someone should make a PR of it or add to the repo directly @talamortis

**Comment by fmrmx** [comment]
Your query is too horrible.

Use: UPDATE `creature_template` SET `flags_extra` =+ 2 WHERE `entry` IN (69,299);
