### ISSUE TITLE
[Tauren] Cultivation Racial not being applied after log off and back on

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6670]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I am currently playing a Tauren druid "Keir" level 13. When I started yesterday I trained in herbalism and saw that I got the extra 15 point due to my racial. Putting me at 16 and rank 1 herbalism completed at a skill of 90. I leveled it up a bit as I was leveling yesterday and logged off to head in to work.

Once I logged back in again I went to pick a herb "earthroot that has a skill of 15 and was promptly unable to pick the herb due to not having enough skill.

With that I unlearned the skill trained again, attempted to pick the level 15 herb and was successful gaining 1 point in my skill to 16 with a max skill being able to be raised to 90. I logged out and then back in and checked my skill and it was at a skill of 2 with a max skill of 75.

It is as if the Tauren race bonus is not being applied..

Confirmed the issue on a local AC server: https://youtu.be/MFsoQpU8vg4
AzerothCore rev. c8a4b8190cb6+ 2021-06-30 22:47:41 +0000 (master branch)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Tauren race gets a 15 point skill bump for herbalism. 15 skill to start and a max skill for 315 at 60. I do not have any video proving it but I have seen it discussed many times... Here is one example
https://www.reddit.com/r/classicwow/comments/b74r82/what_is_the_purpose_of_the_tauren_racial/

##### SOURCE:

https://wowwiki-archive.fandom.com/wiki/Cultivation
https://wotlk.evowow.com/?spell=20552

##### STEPS TO REPRODUCE THE PROBLEM:

Originally reported https://github.com/chromiecraft/chromiecraft/issues/1046

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by necropola** [comment]
If I understand this correctly, then PR #6015 forgot to load `SkillTiers.dbc` entirely which lead to **loads** of skills scaling with level (although they shouldn't).  The hackfix "fixed" this, but this also means we never really tested the PR with `SkillTiers.dbc` being loaded ...
- :green_circle: Gnome Engineering racial bonus seems to be ok (does not disappear on relog)
- :green_circle:  Draenei Jewelcrafting racial bonus seems to be ok (does not disappear on relog)
- :green_circle:  Bloodelf Enchanting racial bonus seems to be ok (does not disappear on relog)
- :red_circle:  Tauren Herbalism racial bonus is bugged (disappears on relog)

**Comment by claudiodfc** [comment]
It's another one of these dbcs that need to be implemented and tested way harder before merges.

**Comment by necropola** [comment]
### Good News!

I searched a bit (actually quite a while) for differences in how TC-3.3.5 handles this and found it!
PR with this fix incoming ...

```diff
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index ddb835cb6..311bc65b7 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -26008,6 +26008,7 @@ void Player::_LoadSkills(PreparedQueryResult result)
     // SetPQuery(PLAYER_LOGIN_QUERY_LOADSKILLS,          "SELECT skill, value, max FROM character_skills WHERE guid = '%u'", m_guid.GetCounter());

     uint32 count = 0;
+    std::unordered_map<uint32, uint32> loadedSkillValues;
     if (result)
     {
         do
@@ -26073,7 +26074,7 @@ void Player::_LoadSkills(PreparedQueryResult result)

             mSkillStatus.insert(SkillStatusMap::value_type(skill, SkillStatusData(count, SKILL_UNCHANGED)));

-            learnSkillRewardedSpells(skill, value);
+            loadedSkillValues[skill] = value;

             ++count;

@@ -26085,6 +26086,12 @@ void Player::_LoadSkills(PreparedQueryResult result)
         } while (result->NextRow());
     }

+    // Learn skill rewarded spells after all skills have been loaded to prevent learning a skill from them before its loaded with proper value from DB
+    for (auto& skill : loadedSkillValues)
+    {
+        learnSkillRewardedSpells(skill.first, skill.second);
+    }
+
     for (; count < PLAYER_MAX_SKILLS; ++count)
     {
         SetUInt32Value(PLAYER_SKILL_INDEX(count), 0);
```
