### ISSUE TITLE
Tamra Stormpike attacks up to 4 times in a single strike

### ISSUE THREAD

**Issue by Efymer** [azerothcore/azerothcore-wotlk#6675]
**Originally reported:**  https://github.com/chromiecraft/chromiecraft/issues/1051

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

NPC with DB GUID 90783, Entry 14275 Tamra Stormpike (https://wowgaming.altervista.org/aowow/?npc=14275) attacks upwards of 4 times in a row (Thrash ability https://wowgaming.altervista.org/aowow/?spell=12787). This makes is almost impossible to kill her when she can take half of your health bar in what should be a single strike, not 4 in a row.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC should attack only once.

##### SOURCE:
DB GUID 90783
Entry 14275 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Dun Garok in Hillsbrad foothills
2. Find that rare NPC inside (She should be on the top floor)
3. See how many times she attacks in a single strike

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
No sniff available for this npc but in vmangos he deosn't have any spell

**Comment by Efymer** [comment]
> No sniff available for this npc but in vmangos he deosn't have any spell

Yep, also checked that, the only thing I could find is in Classic Wowhead, and it has some "Dazed" abilities https://classic.wowhead.com/npc=14275/tamra-stormpike#abilities

**Comment by Azcobu** [comment]
Note that this is a specific instance of a wider issue here: https://github.com/azerothcore/azerothcore-wotlk/issues/6118 where creatures have Thrash when they shouldn't.

**Comment by T1ti** [comment]
we managed to sniff him, I can confirm he doesn't have a thrash aura

**Comment by jivetolkein** [comment]
I added a comment to the bug, but I think she just hits too hard for a 30sih rare - not even Elite AFAIK - as we were getting one shot every time.
