### ISSUE TITLE
[QUEST] ID :11586 (Hellscream's Vigil)

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#668]
**Description**: png give two same quest

**Current behaviour**: Tell us what happens
png give two same quest

![wowscrnshot_092217_120956](https://user-images.githubusercontent.com/31663279/31031651-7f50ceba-a559-11e7-878d-88e1c9eea39e.jpg)
![wowscrnshot_092217_121019](https://user-images.githubusercontent.com/31663279/31031630-6c136ec0-a559-11e7-80ca-f025fec5c130.jpg)

**Expected behaviour**: Tell us what should happen instead
just give one quest

**Branch(es)**: Master 

**AC hash/commit**:  6b08fd2f6136

**Operating system**:  Win10 and ubuntu server 16.04

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by STARRHELD** [comment]
"There are two versions of this quest, with different completion texts. The first one has Garrosh spitting in disgust at your evident fear. This one, in which he is kinder to you, happens if you have completed the Greatmother questline in Nagrand."

> I would assume that you'd have a missing condition for checking that "http://www.wowhead.com/quest=10172/there-is-no-hope" is completed.


```SQL
--
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND (`SourceEntry`=11586 OR `SourceEntry`=11585);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceEntry`,`ConditionTypeOrReference`,`ConditionValue1`,`Comment`) VALUES 
(19, 11585, 14, 10172, "Accept quest 11585 - Quest 10172 needs to be incomplete"),
(19, 11586, 8, 10172, "Accept quest 11586 - Quest 10172 needs to be rewarded");

UPDATE `quest_template_addon` SET `ExclusiveGroup`=11585 WHERE  `ID`IN(11585,11586);
```

**Comment by Maurowin** [comment]
hummm i don't know, i toke both and it's same objectif speak to an pnj

**Comment by STARRHELD** [comment]
Can anyone confirm so we can make PR and close this?
