### ISSUE TITLE
Amani Berserker - Frenzy buff increasing output incorrectly

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6688]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1057

##### CURRENT BEHAVIOUR:

When the Amani Berserker enrages, it gains a buff called Frenzy, which is supposed to increase damage by 50%, as per this screenshot.

![image](https://user-images.githubusercontent.com/23312332/124340368-a2f8bc00-dbac-11eb-902d-f847d3e5d58d.png)

What is actually happening:

![image](https://user-images.githubusercontent.com/23312332/124340407-f10dbf80-dbac-11eb-9722-35444fdad642.png)

I get a feeling that there's an extra 0 in there. That's 500% damage, not 50% more.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Obviously the output of the mob's damage under the effect should match the multiplier in the tooltip.

##### SOURCE:

The tooltip for the buff. And obviously a mob four-shotting you in 3 seconds isn't intended behavior at that level.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Tor'Watha or Zeb'Watha in Eversong Woods.
2. Bring an Amani Berserker to low HP (<30%?).
3. Get destroyed.

##### EXTRA NOTES:

NPC Link: https://wowgaming.altervista.org/aowow/?npc=15643

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 3b58f5602928 ) :

![WoWScrnShot_070321_095105](https://user-images.githubusercontent.com/82579073/124346020-1f0ef600-dbe5-11eb-8e16-618a4a50978c.jpg)
![WoWScrnShot_070321_095129](https://user-images.githubusercontent.com/82579073/124346036-377f1080-dbe5-11eb-8c26-36e61458b089.jpg)
![WoWScrnShot_070321_100247](https://user-images.githubusercontent.com/82579073/124346140-e0c60680-dbe5-11eb-998e-a9e7534263b5.jpg)

**Comment by T1ti** [comment]
The spell effect is 50 + 2 per level which explains why this happens

The correct spell he should use is https://tbc.wowhead.com/spell=8599/enrage according to classic wowhead
