### ISSUE TITLE
[NPC] Warlocks pet Felhound can devour buffs from neutral NPCs -> neutral NPC attack the Felhound.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6691]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1059

##### CURRENT BEHAVIOUR:

Felhounds Devour Magic - https://wowgaming.altervista.org/aowow?spell=19505
 - Felhound can cast Devour Magic on neutral NPCs in Booty Bay while they are buffed with player buffs, even when NOT at war with the faction -> NPCs attack the Felhound - NOT player.
 - NPC in question - https://wowgaming.altervista.org/aowow?npc=4624

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Neutral NPCs should NOT be attackable while not at war with them. -> Felhound shouldn't be able to use Devour Magic https://wowgaming.altervista.org/aowow?spell=19505 on neutral NPCs while not at war with them. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Buff the Booty Bay bruiser NPC (while having reputation neutral - don't know about friendly and above). (Happened with Paladin using Blessing of Kings)
2. Cast Devour Magic from Felhounds petbar
3. ????
4. Felhound dies :( (gives no Soul Shard back)

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 3b58f56 ) :

![WoWScrnShot_070321_121133](https://user-images.githubusercontent.com/82579073/124349535-34415000-dbf8-11eb-8605-d584a0b6e56a.jpg)
![WoWScrnShot_070321_121156](https://user-images.githubusercontent.com/82579073/124349561-52a74b80-dbf8-11eb-8eb1-43bdea5fd0c9.jpg)
![WoWScrnShot_070321_121219](https://user-images.githubusercontent.com/82579073/124349579-68b50c00-dbf8-11eb-92a2-3c3ee267abed.jpg)
![WoWScrnShot_070321_121238](https://user-images.githubusercontent.com/82579073/124349601-7b2f4580-dbf8-11eb-8c0d-5c7fae88e0bd.jpg)
![WoWScrnShot_070321_121638](https://user-images.githubusercontent.com/82579073/124349618-9f8b2200-dbf8-11eb-977e-8c7721764881.jpg)

**Comment by TheMurtos** [comment]
Yea I felt the same way as the female in the third picture.
