### ISSUE TITLE
Core/spell: Deep freeze dealing damage instead of stun

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#6692]
**CURRENT BEHAVIOUR:**
Spell Deep freeze is dealing damage to targets that can be stunned

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Deep freeze only deals damage to targets that are immune to stun, which in this case would be boss, Counter players is for stun only as players are not immune to stun.
![Screenshot_20210703-085414-592](https://user-images.githubusercontent.com/67213916/124353343-49a88100-dbdc-11eb-92cf-e3bcf6f31c43.png)

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. create a mage
2. Training all frostduelae skills
3. Duel with another player, use Deep freeze and see that it will stun and also deal damage, the right thing is just stun.

**EXTRA NOTES:**

**AC HASH/COMMIT:**

> 27b2026

**OPERATING SYSTEM:**
Windows

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by WillzDevs** [comment]
@Kitzunu I had to open another issue because in another issue #6616, You Blocked conversations and I could not say about the subject or close

**Comment by claudiodfc** [comment]
This subject has been discussed on that thread. Players are getting hit by damage due to learning a skill that makes them immune to deep freeze stun.

**Comment by WillzDevs** [comment]
As the topic was blocked, I need to explain about it, because it was not well explained. The problem being that it's causing damage, where it should just stun...
I hope you can solve

**Comment by claudiodfc** [comment]
There's nothing to be explained, thread was blocked because Kitzunu said what was the issue:

https://github.com/azerothcore/azerothcore-wotlk/issues/6616#issuecomment-872572248

**Comment by WillzDevs** [comment]
@Kitzunu sorry to bring up the subject again, but related to issue #6616, Do you have any related correction news?
I can't talk about the issue because it was blocked!
Thank you very much in advance!

**Comment by Kitzunu** [comment]
It will be fixed when someone wants to fix it. Like any other issue in the repository

**Comment by WillzDevs** [comment]
> It will be fixed when someone wants to fix it. Like any other issue in the repository

Nice!
