### ISSUE TITLE
Casting hunter's ability "Volley" turns player towards last target

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6695]
Originally Reported: https://github.com/chromiecraft/chromiecraft/issues/1062

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Channeling Volley makes the hunter look at the target selected, even if its dead. This makes you look backwards/sideways
EDIT: video of what happens on azerothcore: https://youtu.be/5YuPVfeK1y0

##### EXPECTED BLIZZLIKE BEHAVIOUR:

 
Channeling Volley should keep hunter facing the direction of the Volley's mark or at least not to whatever you are targetting.
EDIT: See https://youtu.be/8kulUEU9i3g?t=132

##### SOURCE:

https://youtu.be/vxUeCb3sfgc?t=123 -> Sorry for the music. As you can see hunter is not looking directly at the target, but it does atm on AC and CC
https://wotlk.evowow.com/?spell=42245

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be at least lvl 40 hunter. Learn Volley ability
2. Cast the Volley.
3. Target someone behind you, or next to you
4. Cast volley and see that you look at the target.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by UltraNix** [comment]
Voller is an AOE spell, so there is no "Volley's Mark".
@temperrr In that videos hunter is looking at his target all the time - I don't see if this is an evidence.

**Comment by FrancescoBorzi** [comment]
ping @temperrr

**Comment by temperrr** [comment]
https://www.youtube.com/watch?v=8kulUEU9i3g

This video (please mute if you dont like vengaboys) shows clearly that they are not facing the target targetted, but instead face the volley mark *marker* that you target on the floor.

**Comment by UltraNix** [comment]
@temperrr No - targeting that troll does not mean he has to face it. He could just left clicked on it or auto-targeted by client because that mob is attacking him. He never turned to that mob to attack him. The hunter is looking in front of him all the time.

**Comment by temperrr** [comment]
Exactly what I mean... On Chromie, you will face whatever target you target even if you point volley behind your back and the troll is right of you.

**Comment by UltraNix** [comment]
You misunderstood me. That troll is only attacking that hunter, nothing more. It's not facing.

**Comment by temperrr** [comment]
> he hunter is looking in front of him all the time.

This is not happening on chromiecraft. I'll grab a screenshot...

**Comment by temperrr** [comment]
https://user-images.githubusercontent.com/20357406/128537652-4b2eb466-0950-4f71-a304-1d9c00e7421b.mp4

**Comment by UltraNix** [comment]
Can you show me your combat log?

**Comment by UltraNix** [comment]
I jus tested on my local and my hunter is not turning to mobs behind me.

**Comment by temperrr** [comment]
select the trolls behind you, the volley somewhere else, you will start to face whatever is selected.

**Comment by UltraNix** [comment]
Yep - you are right. There is something weird about it.

**Comment by temperrr** [comment]
Sorry I should've made the video in the original report.

**Comment by UltraNix** [comment]
There is a clientside attribute in that spell that make you facing the selected target. So I'm afraid there is nothing I can do with it because it's clientside - it's not a serverside problem.

**Comment by UltraNix** [comment]
https://classic.wowhead.com/forums/topic/volley-and-facing-problems-146473
Looks like blizzlike bug.

**Comment by temperrr** [comment]
Hmm, that's sad to know, though only visually. Weird that it doesnt happen with other channeled spells, like blizzard or hurricane

**Comment by UltraNix** [comment]
It's all because of that clientside attribute - `SPELL_ATTR0_CAST_TRACK_TARGET`. Blizzard/Hurricane does not have it.

**Comment by temperrr** [comment]
Ok, so we close then due to clientside?

**Comment by UltraNix** [comment]
Yes.
