### ISSUE TITLE
Felhunter Devour Magic

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#67]
Felhunter dispells only friendly target on enemy it doesnt work

**Comment by justdothings** [comment]
confirm

**Comment by ShinDarth** [comment]
please can you include your rev when you report/confirm bugs?

thanks

**Comment by justdothings** [comment]
im using https://github.com/callmephil/SunWellCore this version of sunwell core but iknow that its bugged, i searched fix in your commits and cant find anything about that also i can share fix that im using for my server.

**Comment by ShinDarth** [comment]
@justdothings any kind of contribution is welcome

we also imported to AzerothCore all improvements that @callmephil made

**Comment by DevRival** [comment]
Maybe this pull [13751](https://github.com/TrinityCore/TrinityCore/pull/13751/files)?

**Comment by ShinDarth** [comment]
Just tested on https://github.com/azerothcore/azerothcore-wotlk/commit/d641365b3b8e and seems to work for me, I tested by using the spell against an enemy player in duel and it removes the buff from the enemy

compiled on mac os x with clang

can anyone test it again?

**Comment by talamortis** [comment]
i have had no problem with this issue, tested my fel hunter and works fine, also heals as it should @ShinDarth  can close if you are not gaining errors :)

**Comment by ShinDarth** [comment]
@talamortis closing, thanks

shall anyone have again this problem, please comment here.

**Comment by lineagedr** [comment]
Devour magic is working properly however, If you have a duel area (A Sanctuary) and two players dueling in that Sanctuary. Devour magic will not work this is because Xinef has added a check to disable deveour magic search for: Xinef: do not allow to cast on hostile targets in sanctuary and you can comment his code to make devour magic work in sanctuaries.
