### ISSUE TITLE
Core/Misc: Unique item trading

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#670]
*Current behavior**: Tell us what happens

>Trading a unique item to a player that already has the item produces the message "Partner does not have enough free bag slots." Not a huge deal, but this message is a bit misleading if they have free bag slots. This message may also occur if they have the item equipped instead of in their bag, but I didn't test for it.

**Expected behavior**: Tell us what should happen instead

>It should report a message that accurately describes the issue. ie - "Partner already possesses this unique item."

**Steps to reproduce the problem**:

1. Have a player equip a unique item.
2. Try to trade that unique item to them.

**AC hash/commit**:  
 
> dbd2f9931262+

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

> Master

**Operating system**:  

>VMWare Workstation 12 running Win7x64

**Modules**:  Are you using modules? if yes, list them

> None

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

> None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Nefertumm** [comment]
Something that can work:
https://github.com/azerothcore/azerothcore-wotlk/blob/b9e122dfdfa1a42119653eac671bf964dfccf00a/src/server/game/Handlers/TradeHandler.cpp#L305  https://github.com/azerothcore/azerothcore-wotlk/blob/b9e122dfdfa1a42119653eac671bf964dfccf00a/src/server/game/Handlers/TradeHandler.cpp#L320  at these lines add:
```c++
if ((item->GetTemplate()->Flags & ITEM_PROTO_FLAG_UNIQUE_EQUIPPED) && trader->HasItemCount(item->GetEntry(), 1, true))
    {
        SendNotification(LANG_TRADE_PARTNER_UNIQUE_ITEM);
        trader->GetSession()->SendNotification(LANG_TRADE_PARTNER_UNIQUE_ITEM);
        my_trade->SetAccepted(false);
        his_trade->SetAccepted(false);
        return;
    }
```

You should create the LANG_TRADE_PARTNER_UNIQUE_ITEM in order to this to work. I didn't tested it, so if you wanna try it, go ahead.

**Comment by Kitzunu** [comment]
Should probably just be
EQUIP_ERR_CANNOT_TRADE_THAT                  = 79,
