### ISSUE TITLE
[REST] inn's rest

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#671]
**Description**:  as soon as we leave an inn we keep the buff

**Current behaviour**: Tell us what happens
i use my hearthstone  and when i leave inn i keep rest status
disconnect and reconnect debuff rest status or rest stay +-20 or 30sec before go away.

![wowscrnshot_093017_175150](https://user-images.githubusercontent.com/31663279/31048314-e1fc5cb6-a61a-11e7-8fe9-8fdfb90c1ab0.jpg)

**Expected behaviour**: Tell us what should happen instead
disappear when we left inn

**Steps to reproduce the problem**:

1. enter in inn
2. exit inn
3. 

**Branch(es)**: Master 

**AC hash/commit**:  a2957f53b090

**Operating system**:  Win10 and ubuntu server 16.04

**Comment by Maurowin** [comment]
@poszer do you think you can fix this bug?

**Comment by poszer** [comment]
> @poszer do you think you can fix this bug?

Hmm, what is the name of this buff, how it's triggered, in zone? @Maurowin

**Comment by Maurowin** [comment]
> 
> 
> > @poszer do you think you can fix this bug?
> 
> Hmm, what is the name of this buff, how it's triggered, in zone? @Maurowin

Hummmm, i don't know but you can leave all inns, you still keep "zzz" during some time instead of print your level and you can disconnect instantly like in inns.

Can you confirm that? Because, it's same trouble with most recent release.

**Comment by Maurowin** [comment]
up :)

**Comment by Kitzunu** [comment]
This is wrong.
Read https://wowwiki.fandom.com/wiki/Rest?oldid=2331121 (ID From 2010 WotLK era)

The issue described in this ticket is invalid.

**Comment by Kitzunu** [comment]
> When rested, your XP bar will turn blue, and a notch will appear indicating exactly how rested you are. You will earn double XP from killing monsters while rested until your XP bar fills to the notch. A rested character earns double combat XP until this rest state is consumed, at which point the message
>
>You no longer feel rested.
appears and you resume normal XP gains for kills.

**Comment by Maurowin** [comment]
@Kitzunu This issue is true issue and not blizzlike.

Iam not talking about rest bar but effect zone.
![image](https://user-images.githubusercontent.com/31663279/99257284-17960a80-2817-11eb-857e-ac3db2ee3d31.png)

When one leaves an inn, the small "zzz" must disappear and one should not either out of an inn or capital disconnect instantaneously.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/3712
