### ISSUE TITLE
[Dungeon][Sunken Temple] Serpent statue missing - bonus boss (Atal'alarion) not accessible. 

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6710]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1074

##### CURRENT BEHAVIOUR:

Serpent statue missing - bonus boss (Atal'alarion) not accessible.

- Link for the walkthrough -> https://wowwiki-archive.fandom.com/wiki/Temple_of_Atal%27Hakkar/Old_walkthrough

Each of the highlighted platform should have an interactive statue and a puzzle (they need to be activated in order) to spawn an extra boss in the Basement part of the dungeon 

![image](https://user-images.githubusercontent.com/47978220/124370380-ad37ba80-dc7f-11eb-8136-e4c2daece123.png)

Order for the puzzle 
![image](https://user-images.githubusercontent.com/47978220/124370410-17505f80-dc80-11eb-9f68-f5d5f4bb73cb.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Interactive Statues should be present and interactable in order to solve the puzzle for the last boss

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter Sunken Temple
2. advance to the upper floor 
3. kill the mini-bosses present on each platform 
4. No Interactive statue for the puzzle completion present on the platform

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 3b58f56 ) :

![WoWScrnShot_070421_083333](https://user-images.githubusercontent.com/82579073/124374319-e897b080-dca2-11eb-9c21-5fd10d1d6727.jpg)
![WoWScrnShot_070421_083422](https://user-images.githubusercontent.com/82579073/124374324-f51c0900-dca2-11eb-81cf-8bde89517e07.jpg)
![WoWScrnShot_070421_083503](https://user-images.githubusercontent.com/82579073/124374328-0238f800-dca3-11eb-9b6a-36ecf814644a.jpg)

**Comment by pop-pig** [comment]
Hum, I think the report is incorrect, the statues are in ST but not on the upper level.
I went there on a local AC server before bracket 40-49 went live, and the statues are working and are there, but this is not the right level. They are "right above where Atalalarion is".
Will provide a screenshot in a sec

**Comment by pop-pig** [comment]
Here is a video (sorry I always forget the order for the statues) : https://youtu.be/tJcwOFPTNXE

**Comment by Eldarix** [comment]
You're right friend, I thought that was correct sorry, so first you have to kill the npc's and then activate the statues in the correct order?

**Comment by pop-pig** [comment]
Yes, but the statues are NOT at the 6 troll mini-bosses balconies. The 6 trolls need to be killed to be able to kill another boss (Jammal'an).
See the Classic Wow guide for ST: https://classic.wowhead.com/guides/temple-of-atalhakkar-sunken-temple-classic-dungeon-strategy

**Comment by T1ti** [comment]
you can just check a classic wow video https://youtu.be/VGtKRUTk8WA?t=482
your issue is wrong indeed, there is another floor where the statues are

**Comment by claudiodfc** [comment]
Can this be closed then, or is it still bugged?
