### ISSUE TITLE
[Badlands] Report to Helgrum

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6720]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1082

##### CURRENT BEHAVIOUR:

Quest [Report to Helgrum](https://tbc.wowhead.com/quest=1420/report-to-helgrum) is available to players without [Neeka Bloodscar](https://tbc.wowhead.com/quest=1418/neeka-bloodscar) completed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Neeka Bloodscar is 1st quest in series, Report to Helgrum 2nd in series. 

##### SOURCE:

Wowhead.

##### STEPS TO REPRODUCE THE PROBLEM:

Visit badlands and take Report to Helgrum without Neeka Bloodscar completed.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: dc76e6b1878d) :

![WoWScrnShot_070421_161722](https://user-images.githubusercontent.com/82579073/124386579-c5d9bc00-dce3-11eb-9305-11d77e060478.jpg)

**Comment by eTzmNcbkrng** [comment]
Test link to CC issue 1082: chromiecraft/chromiecraft#1082
