### ISSUE TITLE
Feralas - Quest "Wandering Shay" Not Completing, Missing Scripted Text

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6722]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1083

The escort quest Wandering Shay (https://wowgaming.altervista.org/aowow/?quest=2845) does not complete upon reaching the end destination.

Shay Leafrunner (https://wotlk.evowow.com/?npc=7774) Is also missing her scripted text lines, also her movement speed is too fast judging by classic WoW video.
GUID 50144

Tester: Confirmed the above. Also, she doesn't wander off, which seems to be half the point of the quest. (It's an escort quest, and she gives you a bell to ring when she wanders off to call her back.) When I ran it, she behaved like a pet, just following me constantly and not wandering off at all. While this made the quest rather more pleasant, it was not Blizzlike.

Looking at the DB, Shay does have a number of events set in SmartAI that are supposed to trigger once she gets within 10 yards of Rockbiter (the quest goal NPC), so not sure why they aren't activating. Rockbiter, who is supposed to end the quest, doesn't have any scripts running at all.

Quest handin not possible despite having brought her to the right spot and having the bell:
![WoWScrnShot_070421_230720](https://user-images.githubusercontent.com/81782124/124387292-19b4c700-dd1d-11eb-9b95-ef27efd1ec71.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest should complete upon reaching the end destination.
Shay Leafrunner should be using her scripted text lines during the escort, and should have episodes of wandering randomly until called back by the bell.

##### SOURCE:

https://youtu.be/sb3H2P1yT5U?t=1329
https://classic.wowhead.com/quest=2845/wandering-shay#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 50144
2. Accept the quest Wandering Shay and loot the bell from the box nea her feet
3. Escort her to Rockbiter camp and see it does not complete
4. Observe no scripted text from her

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by JamesGent** [comment]
Related 

https://github.com/azerothcore/azerothcore-wotlk/issues/1535
