### ISSUE TITLE
Boss Razorscale & malygos Not started

### ISSUE THREAD

**Issue by Nephelion** [azerothcore/azerothcore-wotlk#673]
Razorscale: when u speak with Expedition Commander and click web are ready to help ! 
razor move new location but nothing happen...

1. when u speak with Expedition Commander
2.  click web are ready to help ! 
3. razor move new location but nothing happen...
----
malygos: when u enter instance and use Key on The Focusing Iris (object)  nothing happen

1. enter instance
2.  use  Key to the Focusing Iris
3. nothing happened

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
https://github.com/azerothcore/azerothcore-wotlk/commit/a2957f53b09027d00a4d513fb8ff8ec4e6fd79d0

**windows7 local**:  

**Modules**:  Nothing

**Other Customizations**: No

**Comment by talamortis** [comment]
did you kill 1st boss?

**Comment by SQLfix** [comment]
@talamortis  yes i kill 1st boss
and malygoss is 1st boss

**Comment by Krath** [comment]
Cannot reproduce, both bosses are working fine. He's probably starting the bosses with GM mode ON..

Rev: [https://github.com/azerothcore/azerothcore-wotlk/commit/a2957f53b09027d00a4d513fb8ff8ec4e6fd79d0](url)

**Comment by SQLfix** [comment]
i downloaded data file from wiki   [https://mega.nz/#F!ZMpFgQaL!RpgaplKnm4YGekDcZfGg9w]

maybe my problem from this data files ? maybe old 

All others is defualt

OR : when i complie Source i have this error from All files more that 1000 error
[warning C4267: 'return': conversion from 'size_t' to 'uint32', possible loss of data]

**Comment by Nephelion** [comment]
recompile source - reinstall database on new OS windows server 2008 and again test in defualt source
not started 2 boss

i use data files in wiki ! https://mega.nz/#F!ZMpFgQaL!RpgaplKnm4YGekDcZfGg9w
is not problem ? maybe datas is old 

I have very target lines unit . some time unit stop and dont attack player is not line of sight

**Comment by Slash96** [comment]
Reza PJ to hanooz zendei? 
To k balad nisti, chera miai khaye mali kharejia oskol
farghe ano Az goosht koobide nemitooni tashkhis bedi mikhai baz sv bezani? RIDI...
mythicwow et ham mesle 20ta server e Qablit over mishe

krasus-wow ( 2 bar over )
molten-wow
arax-game
wizard-wow
va hala mythic.... :))

**Comment by ShinDarth** [comment]
@Slash96 please speak English

**Comment by Nephelion** [comment]
@shindarth  this member Insulting me with  Persian language 
he is a newcomer member use Azeroth source

and my problem solved with extracting Data files with extractor .i think download data is broken or old
