### ISSUE TITLE
[Searing Gorge] Suntara Stones escort quest - Dorious going too fast, no scripted rests, missing text

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6735]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1090

##### CURRENT BEHAVIOUR:

Quest Suntara stones (https://wowgaming.altervista.org/aowow/?quest=3367)

When escorting Dorius Stonerender GUID 6823  (https://wowgaming.altervista.org/aowow/?npc=8284), he is going too fast, he is missing the scripted escort events, resting, saying his scripted lines.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should move slower. He should be saying his scripted lines at certain locations/in combat/when dying at the end.

##### SOURCE:

https://classic.wowhead.com/quest=3367/suntara-stones
https://classic.wowhead.com/npc=8284/dorius-stonetender

https://www.youtube.com/watch?v=s8qTBCDPJIU

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 6823 and accept the quest
2. Escort Dorius and observe him

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: dc76e6b), but only the missing rests and texts, normal velocity all along the way from the dwarf NPC:

![WoWScrnShot_070521_073304](https://user-images.githubusercontent.com/82579073/124418435-24467f00-dd64-11eb-8042-f16d55f42e6c.jpg)
![WoWScrnShot_070521_073625](https://user-images.githubusercontent.com/82579073/124418464-31636e00-dd64-11eb-992d-d743aa608a99.jpg)
![WoWScrnShot_070521_073645](https://user-images.githubusercontent.com/82579073/124418494-404a2080-dd64-11eb-8b6e-2ea9d5a8b478.jpg)
![WoWScrnShot_070521_073657](https://user-images.githubusercontent.com/82579073/124418514-4f30d300-dd64-11eb-8676-99a9ed84e69a.jpg)

**Comment by ntrna** [comment]
To add to this, the NPC's brother (Curator Thorius) to whom you deliver his dying letter, used the /sob emote, but makes the sound & animation of laughing when you inform him of his brother's death.
