### ISSUE TITLE
Avenger's Shield No Target Jumps

### ISSUE THREAD

**Issue by luisforte** [azerothcore/azerothcore-wotlk#674]
**Description**:
Paladin Spell Avenguers Shield Hit only one target instead of 3

**Current behaviour**: Tell us what happens
When player cast the Avenguer's Shield the "shield" not jump do additional targets, tested with glyph, no changes.

**Expected behaviour**: Tell us what should happen instead
The skill Avenguers Shield need to jump to aditional targets 3 insted of only 1

**Steps to reproduce the problem**:

1.  Cast the spell on closer targets, no bounces only one hit.
2. 
3. 

**Branch(es)**: AzerothCore rev. a2957f53b090 2017-09-30 13:06:38 +0200 (master branch) (Win64, Release)

**AC hash/commit**:  

**Operating system**:  Windows Server 2012 R2 64Bit

**Modules**:  No

**Other Customizations**: Nothing

**Comment by farsidesoul** [comment]
When you say tested with glyph, what do you mean?  The Glyph of Avenger shield prevents it from jumping to additional targets, and will only hit the first one.

**Comment by luisforte** [comment]
only activated Glyph of Avenger and deleted to see if problem still. And Still one target with/without Glyph of Avenger

**Comment by fmrmx** [comment]
Try .unaura all and test it again.

**Comment by STARRHELD** [comment]
I can't replicate this, the shield will jump between targets if it's close enough.
