### ISSUE TITLE
Weegli Blastfuse's land mines playing incorrect voiceline

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6740]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/1093

##### CURRENT BEHAVIOUR:

When one of the [Goblin Land Mines](https://wowgaming.altervista.org/aowow/?npc=7527#sounds) summoned by [Weegli Blastfuse](https://wowgaming.altervista.org/aowow/?npc=7607) detonates, it plays a voiceline of [Avatar of Hakkar](https://wowgaming.altervista.org/aowow/?sound=5871)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I'm not exactly sure what the correct sound it should play is, but it should play some sort of fiery explosion sound, not scream die, mortals!

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Zul'Farrak
2. Start stairs event
3. Have Weegli fight mobs and plant a bomb
4. Listen for the bomb to scream "Die, mortals!"

##### EXTRA NOTES:

This is a funny bug, I wonder how it got here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: dc76e6b) (Can't upload audio ATM)

**Comment by claudiodfc** [comment]
*Die MORTALS* 🤣
