### ISSUE TITLE
[Dungeon][Utgarde Pinnacle] Skadi Encounter is missing freezing cloud emote

### ISSUE THREAD

**Issue by buddiman** [azerothcore/azerothcore-wotlk#6741]
**CURRENT BEHAVIOUR:**
During the Skadi encounter in Utgarde Pinnacle, when Grauf uses his flame breath ability, no emote is shown.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
When Grauf uses his flame breath ability, the emote "Grauf takes a deep breath" should be sent to the player.

**SOURCE:**
https://wowpedia.fandom.com/wiki/Skadi_the_Ruthless

**STEPS TO REPRODUCE THE PROBLEM:**
1.  `.tele utgarde`
2.  Enter Utgarde pinnacle
3.  Start the Skadi encounter
4.  Observe the fight, especially when Grauf uses his flame breath.

**EXTRA NOTES:**
![grafik](https://user-images.githubusercontent.com/10009755/124447591-ce80cf80-dd81-11eb-8175-4fac9ea70d20.png)

**AC HASH/COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/5cf5ff4d6b46f5b85edfbdb45e8e27cddbe4678d

**OPERATING SYSTEM:**
Win10 x64

**MODULES:**
N/A

**CUSTOMIZATIONS:**
N/A

**Comment by syssneck** [comment]
Hi, I can confirm this bug on my local AC (458469e):
![unknown_2021 07 07-17 20](https://user-images.githubusercontent.com/68868567/124788364-8d3b1c00-df49-11eb-8bff-a2d22120f061.png)
Is his ability really called "Flame Breath"? My combat log says it is "Freezing Cloud".

**Comment by buddiman** [comment]
You are right @syssneck 
It is indeed a frost breath, not a fire breath 😅

**Comment by syssneck** [comment]
Okay, it would be really cool, if you could change it in the title to Freezing Cloud. I can't do it, thank you!

**Comment by buddiman** [comment]
It should be changed in the code too.
![grafik](https://user-images.githubusercontent.com/10009755/124822744-98557280-df70-11eb-8ac9-5a65b8721d01.png)
That's why I assumed it was a flame breath.

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/ac8a6b432805593eeb33ccacab94838808d7f50c fixed it
