### ISSUE TITLE
[Dungeon][Utgarde Pinnacle] Grauf is spawned in the floor

### ISSUE THREAD

**Issue by buddiman** [azerothcore/azerothcore-wotlk#6742]
**CURRENT BEHAVIOUR:**
Grauf (The dragon from Skadi encounter) seems to be spawned a bit too low and half of the creature is inside the floor.
Also take a look at the screenshot.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
No source, but I think Grauf should be spawned above the floor and not inside it

**SOURCE:**
N/A

**STEPS TO REPRODUCE THE PROBLEM:**
1. `.tele utgarde`
2. Enter Utgarde Pinnacle
3. Go to Skadi and look at the spawn position of Grauf

**EXTRA NOTES:**
![WoWScrnShot_070521_111741](https://user-images.githubusercontent.com/10009755/124448499-ce350400-dd82-11eb-969d-56c74af271fc.jpg)

**AC HASH/COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/5cf5ff4d6b46f5b85edfbdb45e8e27cddbe4678d

**OPERATING SYSTEM:**
Win10 x64

**MODULES:**
N/A

**CUSTOMIZATIONS:**
N/A

**Comment by Remberance** [comment]
confirm, Grauf is spawned in the floor, the same to screenshot.
