### ISSUE TITLE
Eversong Woods - Wretched Captive Is Facing the Wrong Direction

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6744]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original source: https://github.com/chromiecraft/chromiecraft/issues/1100

![WoWScrnShot_070521_172140](https://user-images.githubusercontent.com/25198252/124448930-85e30980-ddb5-11eb-94e9-cd2f079d79f7.jpg)

The Wretched Captive (npc=16916) is not facing Sergeant Kan'ren (npc=16924).

![WoWScrnShot_070521_195956](https://user-images.githubusercontent.com/81782124/124458268-ea10c800-ddcb-11eb-84b4-ed69c29d4058.jpg)

Tester: Confirmed. GUID of Captive is 58691.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Wretched Captive (npc=16916) should be facing Sergeant Kan'ren (npc=16924).

##### SOURCE:

I've played on various WOTLK private servers (Warmane, Winter-wow, etc.). In all of them, the Wretched Captive is always facing Sergeant Kan'ren. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 58691
2. Witness the RP event between Wretched Captive and Sergeant Kan'ren. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by claudiodfc** [comment]
I noticed this too when scripting his event but I completely forgot 😅

**Comment by Efymer** [comment]
I was checking it and the orientation seems fine in the DB.. then I fixed the MovementType and it looks correct.

Opening a PR 🤖
