### ISSUE TITLE
Maraudon Purple - Meshlok The Harvester, Low Spawn Chance

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6745]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1098

So i and many others tried to farm this rare spawn myself 10 runs of purple crystals and a few others 30 runs and 50 runs but he doesn't seem to pop up. maybe an incorrect spawn rate?

Tester: Went and checked on his spawn and he was up, so he does appear:
![WoWScrnShot_070521_200826](https://user-images.githubusercontent.com/81782124/124459166-06f9cb00-ddcd-11eb-9b56-6fecd6a645dc.jpg)

But that's on a freshly started server. Checking the DB shows he has a respawn timer of 1 day, and on top of that, when he spawns he runs a script that has an 85% chance of immediately despawning himself. And as @anguaive points out, that's not even taking pooling into account (see https://github.com/azerothcore/azerothcore-wotlk/issues/6658.) So it does seem as if the respawn timer/despawn chance means he's much too rare compared to retail. A 1 day respawn * 15% chance of staying spawned means he's appearing about once a week.

His GUID is 203506.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I understand he's a rare spawn and he won't spawn every single time but watching countless youtube videos in the specified location and checking pristine waters, Purple crystals and even Orange crystals none of them will trigger Meshlok to show up. maybe a broken spawn cycle, According to wowhead it should be a 50% spawn chance but it seems like 0% and even so its so very low compared to the blizzard spawn rate.

Tester: only definite quote I could find was from TBC WH: "From my experience, he does appear to spawn about 50% of the time." - https://tbc.wowhead.com/npc=12237/meshlok-the-harvester#comments:id=2808527

##### SOURCE:

https://tbc.wowhead.com/npc=12237/meshlok-the-harvester#comments:id=2808527

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 203506

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by T1ti** [comment]
This is due to the pool indeed, in addition to having a 85% chance to despawn from SAI, he only has a 30% chance to spawn from pool. He is spawned with some weird unused placeholders
![image](https://user-images.githubusercontent.com/40864460/124643690-a97b8200-de91-11eb-9922-96f3941d1d25.png)
As a fix I recommend to just drop the pool

**Comment by T1ti** [comment]
Here's the fix
```
DELETE FROM `pool_creature` WHERE  `pool_entry`=1211;
DELETE FROM `pool_template` WHERE  `entry`=1211;
```

**Comment by anguaive** [comment]
Thanks, I'll apply those.

Based off of anecdotal evidence from wowhead comments, his current despawn chance is more-or-less correct. Only one comment hints at 50% (sample size of 7 so I guess they got really lucky).
