### ISSUE TITLE
Haste rating scaling

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#675]
there is wrong scaling of the speed rating at the speed rating of 668 spell castes goes as on 1200

Steps to reproduce the problem:

Create caster class use item with haste rating 

AzerothCore rev. efbcb8f 2017-09-23 11:30:22 +0200 (master branch) (Unix, Release) (worldserver-daemon)

DEBIAN 8.9

ANTICHEAT
TRANSMOG
DUELRESET

clang report many unused variables during compilation

**Comment by Ercules76** [comment]
could you give us some extra info? I can not find official sources about it. thank you

**Comment by avatar789** [comment]
@Ercules76 Let's say create frost mage use frostbolt 1 level the spell will be instantly cast although casting time 0.86 seconds hence the casting time is also knocked down in the remaining spells, they are casting faster. The same problem with other casters here video 
https://youtu.be/DWeJ19pESXs

**Comment by Ercules76** [comment]
I try to reproduce the bug with your setting, it seems right
![haste_mage](https://user-images.githubusercontent.com/6338975/31625943-304791b2-b2a8-11e7-8f44-7c77805627fc.png)

**Comment by avatar789** [comment]
@Ercules76 Dress the hastes around 1000 and it will instantly cast

**Comment by Ercules76** [comment]
Now i'm at 1001 haste :)
![mage_haste](https://user-images.githubusercontent.com/6338975/31677766-1f7908f6-b36c-11e7-903b-9b00a71adfea.png)

**Comment by avatar789** [comment]
@Ercules76 if you download these spells, then this bug is valid and the frostbolt 1 level is instantly cast
http://screenshot.ru/upload/image/SfA0
http://screenshot.ru/upload/image/SfAK
http://screenshot.ru/upload/image/SfAL

**Comment by Ercules76** [comment]
I used your own talent points, but I don't have the instant spell
![mage_frost](https://user-images.githubusercontent.com/6338975/31779209-e55b1672-b4f2-11e7-85cf-21adc3a1d241.jpg)

**Comment by avatar789** [comment]
@Ercules76 What is your version of the parasites? Would you be able to throw off your base world as well as dbs?
if you want to test you can go here wowsoul.org I'll show you a bug.

**Comment by Nefertumm** [comment]
Is this still happening?
