### ISSUE TITLE
Wintergrasp

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#676]
at the end of the battle for wintergrasp regardless of who wins the flag is always under control alliance

Steps to reproduce the problem:

Win wintergrasp horde

AzerothCore rev. efbcb8f 2017-09-23 11:30:22 +0200 (master branch) (Unix, Release) (worldserver-daemon)

DEBIAN 8.9

ANTICHEAT
TRANSMOG
DUELRESET

clang report many unused variables during compilation

**Comment by gengarshadowball** [comment]
Can't reproduce this issue.

**Comment by BarbzYHOOL** [comment]
i close but it can be reopened if wrongly closed
