### ISSUE TITLE
server is frozen 2

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6762]
### Current Behaviour

server is frozen,Login game shows `connected`,Typing`.server restart 10` does not execute correctly,and pressing 'Ctrl + C' will not end the process
![20210706080132](https://user-images.githubusercontent.com/18187177/124525310-64bffe80-de31-11eb-99ac-31de85f0ce6e.jpg)
![20210706080328](https://user-images.githubusercontent.com/18187177/124525313-68538580-de31-11eb-968f-566a58c188e9.jpg)
![20210706075940](https://user-images.githubusercontent.com/18187177/124525318-6b4e7600-de31-11eb-9a6c-ba1f72d384d3.jpg)

### Expected Blizzlike Behaviour

no frozen

### Steps to reproduce the problem

I don't know how to reproduce it

### AC rev. hash/commit

47b09f27671d9d04e86cfc996085207c8b5ac177

### Operating system

ubuntu20.04

**Comment by Kitzunu** [comment]
Looks to me that it is due to someone sending malformed packets to the server

@Winfidonarleyan @Helias any thoughts?

**Comment by mpfans** [comment]
My server is very powerful. I've seen this wrong packet before, but it won't cause the server to freeze

**Comment by T1ti** [comment]
I also see that hapen quite a lot on my server (malformed apckets), and only a few friends play it

**Comment by FrancescoBorzi** [comment]
> I also see that hapen quite a lot on my server (malformed apckets), and only a few friends play it (doesn't make it crash either)

I haven't seen this happening lately on ChromieCraft with 200-600 players online. Do you know how to reproduce the issue?

**Comment by HerrTrigger** [comment]
"Client sent malformed packets" is an old & widespread 'issue', with topics dating back to 2010:
https://www.google.com/search?q=client+sent+malformed+packet&hl=nl-BE&gbv=2&sei=abvkYMr5MoLnsAfH_paYCw
https://github.com/cmangos/issues/issues/2098#issuecomment-605513086

Explained:
https://community.trinitycore.org/topic/14087-error-client-sent-malformed-packet/
https://community.trinitycore.org/topic/15420-malformed-packet/

**Comment by Viste** [comment]
> "Client sent malformed packets" is an old & widespread 'issue', with topics dating back to 2010:
> https://www.google.com/search?q=client+sent+malformed+packet&hl=nl-BE&gbv=2&sei=abvkYMr5MoLnsAfH_paYCw
> [cmangos/issues#2098 (comment)](https://github.com/cmangos/issues/issues/2098#issuecomment-605513086)
> 
> Explained:
> https://community.trinitycore.org/topic/14087-error-client-sent-malformed-packet/
> https://community.trinitycore.org/topic/15420-malformed-packet/

It could be anything to world/auth socket ports. Not just a port scan. It could also be a 'hacker attack' to find a vulnerability. And if the hacker guesses it, it could easily freeze the server, or crash it.
A good idea is to take all packages and break them down into two types:
Rubbish
Client packets
Trash should be cut off at once and client packets should be additionally checked for validity.

**Comment by SKingOWN** [comment]
My server logs malformed packet with everyone (me included) :) and sometimes freeze too. 

Commit hash: a8b858ec92831b6bde4fb1c48638ed62fd0ac5d9

**Comment by Voidx** [comment]
Do you continue to have these problems?

**Comment by Winfidonarleyan** [comment]
@mpfans

**Comment by mpfans** [comment]
Not in the last two weeks

**Comment by Winfidonarleyan** [comment]
> Not in the last two weeks
> 
> 

Okay, close this.
