### ISSUE TITLE
NPCs will still cast spells that require a melee weapon even when disarmed

### ISSUE THREAD

**Issue by thenewblock** [azerothcore/azerothcore-wotlk#6764]
### Current Behaviour

When you disarm an NPC, it will still cast a spell that requires a melee weapon (for example Heroic Strike) even when disarmed.

### Expected Blizzlike Behaviour

When an NPC is disarmed, any spells that require a melee weapon should not be castable until the disarm is over.

### Steps to reproduce the problem

1. Start combat with any NPC capable of casting an ability that requires a melee weapon (I tested Scarlet Captain [28611]).
2. Disarm the enemy.
3. They will still cast the ability even if it requires a melee weapon.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f
### Operating system

Windows 10

**Comment by Azcobu** [comment]
See also https://github.com/azerothcore/azerothcore-wotlk/issues/6404 for this same issue with NPC ranged attacks.
