### ISSUE TITLE
Pygmy Tide Crawler doesn't interact correctly with terrain.

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6765]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
NPC DB GUID 38518 moves erratically, seems to fall up and down along the slope and sometimes clips through the terrain.

![Screenshot from 2021-06-14 20-27-45 copy](https://user-images.githubusercontent.com/85800188/121943923-5c086b00-cd52-11eb-97c7-f9a38a086d4f.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPC should move as its fellow crawlers and not pass through the world terrain.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Observe NPC DB GUID 38518 move through its patrol pattern. 

##### EXTRA NOTES:

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/863

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
See also https://github.com/azerothcore/azerothcore-wotlk/issues/6171 and https://github.com/azerothcore/azerothcore-wotlk/issues/6541 for what looks to be much the same problem with other aquatic creatures.

**Comment by claudiodfc** [comment]
From my investigation, we are not transitioning from walk state to swim state properly. TC fixed this on their code but haven't checked can't commits. The problem is very like how we use the Z axis to get a possible viable position.  If we fix the Z axis we also might fix the bug where if mages blink submerged they getting sent to the bottom of the water body.

**Comment by T1ti** [comment]
This NPC doesn't even patrol or do a ground/water transition

His spawn point is bugged and is clipped inside the rock 
![image](https://user-images.githubusercontent.com/40864460/124645351-9f5a8300-de93-11eb-93c6-755c97a70172.png)

He has a random wander radius around that spawn point

**Comment by T1ti** [comment]
After slightly moving his spawn point away from inside the cliff, he seems to wander properly now

**Comment by claudiodfc** [comment]
#9272 probably fixes this

**Comment by acidmanifesto** [comment]
Closes due to fix: https://github.com/azerothcore/azerothcore-wotlk/pull/9272
