### ISSUE TITLE
[CORE] Error Creating Character

### ISSUE THREAD

**Issue by Dilemmast** [azerothcore/azerothcore-wotlk#677]
**Description**: Error Creating Character

**Current behaviour**: Player::Create: Possible hacking-attempt: Account %u tried creating a character named '%s' with an invalid race/class pair (%u/%u) - refusing to do so.

**Expected behaviour**: i think this help https://github.com/TrinityCore/TrinityCore/pull/20139

**Branch(es)**: master 

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/34682ecc2c15a1fc3f5c6507e75c8b2c2219198f
**Operating system**:  seven

**Modules**:  Anticheat-Transmog-Premium
**Other Customizations**: no

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by lineagedr** [comment]
Are you sure they're not using a custom patch?

**Comment by SQLfix** [comment]
when players have some custom patch like {all class all race} for funservers this error occored

**Comment by Dilemmast** [comment]
@Nephelion . @Lineagedr not have custom patch related with race/class

**Comment by Nephelion** [comment]
@Dilemmast  Is Not your Custom Patch
Player Client Custom patch . and dont worry about this error

**Comment by BarbzYHOOL** [comment]
I think they are right, and I think it can be closed.

**Comment by talamortis** [comment]
Player has custom patch for like "ARAC" tested and works correctly issue can be closed.
