### ISSUE TITLE
Quest "Stranglethorn Fever" won't trigger the summon for "Mokk"

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6774]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If you talk to unbagwa and he tries to summon mokk he'll get stuck trying to summon him.

Tester screenshot:
![Screenshot from 2021-07-06 17-52-09](https://user-images.githubusercontent.com/20357406/124630678-f4da6400-de82-11eb-97dd-e42de4c4d250.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Unbagwa should be able to summon mokk without a hitch.

##### SOURCE:

https://classic.wowhead.com/quest=348/stranglethorn-fever

##### STEPS TO REPRODUCE THE PROBLEM:

Tester notes:
1. I managed to get him stuck in the summoning loop by handing in the fang
2.  kill all monsters without him engaging
3.  hand in for a second time on the same char
4. no gorillas were summoned, he's stuck in casting animation and can no longer start the event again.

##### EXTRA NOTES:

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/1065

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Shineslippers** [comment]
> Right now in this very moment 17.11.2021 - the quest is bugged. I'm right next to the guy, but right clicking him does nothing. I got 9 fangs and what's stranger is that I've done this quest on all my alts so far and never had a problem.
> 
> ![image](https://user-images.githubusercontent.com/88625031/142231590-40339c9d-8ff7-4a26-bc9d-087060f65e13.png)

1. If you don't kill apes that summoning Unbagwa and will wait for despawn of it - Witch Doctor will stack with unable to start quest again
2. Summoned apes doesn't attack Unbagwa and Witch Doctor doesn't attack apes

**Comment by temperrr** [comment]
Quote from linked issue:
This bug is caused by some id*ot starting the event and not finishing it, because the SAI requires Mokk to die to trigger default state

**Comment by Shineslippers** [comment]
https://github.com/chromiecraft/chromiecraft/issues/1065#issuecomment-988705554

Just tested this on the retail tbc PTR, also sniffed some data.
- The Gorillas should actually run to the back of the cave, not just Infront of it.
- if no one gets aggro on them or kills them, they will fight Witch Doctor Unbagwa instead and if they kill him, they will stay in the back of the cave for around 60 seconds before despawning.
- The Witch Doctor's faction should be default 35, then set to 495 during the event and back to 35 after.
- The Witch Doctor's respawn time is about 5 minutes.

**Comment by FrancescoBorzi** [comment]
Somehow I managed to start the quest on ChromieCraft, but the quest item hasn't been dropped. Tried twice.

So I can confirm this quest is still bugged.
