### ISSUE TITLE
[Redridge Mountains] Deputy Feldon (Alliance) does not engage nearby Horde players

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#6775]
### Current Behaviour

The alliance guard Deputy Feldon near the alliance flightpoint in Redridge Mountains does not engage nearby Horde players. He does however attack back, if he gets attacked first.

![Screenshot 2021-07-06 17 39 24](https://user-images.githubusercontent.com/68868567/124630492-c52b5c00-de82-11eb-898d-cdfa142e52fb.png)

Edit: I just found out, that he is a questgiver. If this is the normal behavior for questgivers, then please close this one. Thank you!

### Expected Blizzlike Behaviour

He should attack nearby Horde players, like the other guards do.

### Steps to reproduce the problem

1. Be a Horde character
2. Go to Redridge Mountains
3. Find Deputy Feldon
4. See that he does not attack, when you go near him

### AC rev. hash/commit

AzerothCore rev. a8b858ec9283+ 2021-07-01 14:58:34 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using ACE version: 6.5.10
Using Boost version: 1.74.0
Using MySQL version: 80025
Using CMake version: 3.21.0-rc2
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2196365052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_01_01
Using Character DB Revision: 2021_06_30_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Windows 10 x64

**Comment by Hacaw** [comment]
@syssneck  this is not an issue.
As stated in: https://wowpedia.fandom.com/wiki/Quest_giver?oldid=2341345 quest giver shouldn't attack the opposite factions.
