### ISSUE TITLE
[CORE] Glyph NOT Working

### ISSUE THREAD

**Issue by Dilemmast** [azerothcore/azerothcore-wotlk#678]
**Description**: Glyph not working after change faction

**Steps to reproduce the problem**:

1. create character
2. learn a glyph
3. do change faction see NOT working that glyph

**Branch(es)**: master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/34682ecc2c15a1fc3f5c6507e75c8b2c2219198f
**Operating system**:  seven

**Modules**:  anticheat - premium - transmog

**Other Customizations**: NO

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by pklloveyou** [comment]
Glyph of Vice talent does not work

**Comment by pklloveyou** [comment]
Quit a game into the game can learn Glyph

**Comment by pklloveyou** [comment]
Is it a mechanism that should be added?
Save all glyphs and reload glyph status while switching second genres

**Comment by d3tr0l** [comment]
Can not reproduce. Either invalid issue OR transmog module issue.
