### ISSUE TITLE
Unable to close battleground

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6781]
### Current Behaviour

In `battleground_template` table limits the character level, but you can still press the' H ' key to queue and enter the battleground. (use .gm off)
![20210707093553](https://user-images.githubusercontent.com/18187177/124687370-5512e980-df07-11eb-8983-cfd0e819ebfe.jpg)
![20210707093804](https://user-images.githubusercontent.com/18187177/124687375-593f0700-df07-11eb-8d73-99e005c31c58.jpg)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1.`UPDATE battleground_template SET MinLvl ='81',MaxLvl='80'  WHERE ID IN (1,9,30,32)`
2.restart server
3.enter game
4.press `H` key,choice `Random Battleground` or `Alterac Valley`
5.you can join that

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

### Operating system

ubuntu20.04

**Comment by syssneck** [comment]
Hi, I made the appropriate changes, but after I changed the MinLvl to 81 and restarted the server, I wasn't able to join the battlegrounds as you did. I was only able to join Warsong Gulch and Arathi Basin, because I made no changes to the MinLvl there.

**Comment by Helias** [comment]
the minLevle to see what you see typing `H` is handled by `PvPDifficulty.dbc`, so the client can still send the join command to the server, but ofc it's a bug of the server that you can join for real and enter to the battleground :(

**Comment by mpfans** [comment]
> Hi, I made the appropriate changes, but after I changed the MinLvl to 81 and restarted the server, I wasn't able to join the battlegrounds as you did. I was only able to join Warsong Gulch and Arathi Basin, because I made no changes to the MinLvl there.

what's your server AC rev. hash/commit ?

**Comment by syssneck** [comment]
My local AC is 458469e

**Comment by mpfans** [comment]
> My local AC is [458469e](https://github.com/azerothcore/azerothcore-wotlk/commit/458469ec01f1653b1c5b3b238afaf24da67366b8)

You tested it in this 458469ec01f1653b1c5b3b238afaf24da67366b8 ?
modify minlvl = 81 and can't join the battlefield?

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/458469ec01f1653b1c5b3b238afaf24da67366b8

The commit was merged at 17:30 yesterday, and your test results were submitted at 16:44

**Comment by syssneck** [comment]
This is my local AC rev. hash/commit: AzerothCore rev. 458469ec01f1+ 2021-07-07 09:31:43 +0000 (master branch) (Win64, RelWithDebInfo, Static)

The changes in battleground_template:
![grafik](https://user-images.githubusercontent.com/68868567/124903399-38001880-dfe4-11eb-8dd6-6c4a768dd185.png)

I can't join the battlegrounds, where I changed the MinLvl to 81 with a lvl 80 char (as expected):
https://user-images.githubusercontent.com/68868567/124904160-fe7bdd00-dfe4-11eb-95fd-b1fe83d3bb37.mp4



Did I miss something?

**Comment by mpfans** [comment]
> This is my local AC rev. hash/commit: AzerothCore rev. [458469e](https://github.com/azerothcore/azerothcore-wotlk/commit/458469ec01f1653b1c5b3b238afaf24da67366b8)+ 2021-07-07 09:31:43 +0000 (master branch) (Win64, RelWithDebInfo, Static)
> 
> The changes in battleground_template:
> ![grafik](https://user-images.githubusercontent.com/68868567/124903399-38001880-dfe4-11eb-8dd6-6c4a768dd185.png)
> 
> I can't join the battlegrounds, where I changed the MinLvl to 81 with a lvl 80 char (as expected):
> https://user-images.githubusercontent.com/68868567/124904160-fe7bdd00-dfe4-11eb-95fd-b1fe83d3bb37.mp4
> 
> Did I miss something?

I didn't see any hint in your chat window. I'm not sure, because I can join here

**Comment by mpfans** [comment]
> This is my local AC rev. hash/commit: AzerothCore rev. [458469e](https://github.com/azerothcore/azerothcore-wotlk/commit/458469ec01f1653b1c5b3b238afaf24da67366b8)+ 2021-07-07 09:31:43 +0000 (master branch) (Win64, RelWithDebInfo, Static)
> 
> The changes in battleground_template:
> ![grafik](https://user-images.githubusercontent.com/68868567/124903399-38001880-dfe4-11eb-8dd6-6c4a768dd185.png)
> 
> I can't join the battlegrounds, where I changed the MinLvl to 81 with a lvl 80 char (as expected):
> https://user-images.githubusercontent.com/68868567/124904160-fe7bdd00-dfe4-11eb-95fd-b1fe83d3bb37.mp4
> 
> Did I miss something?

try maxlvl =81 ?

**Comment by syssneck** [comment]
Yepp, that was it! MinLvl and MaxLvl to 81 and I can join the battleground as a lvl 80 ...

**Comment by mpfans** [comment]
> Yepp, that was it! MinLvl and MaxLvl to 81 and I can join the battleground as a lvl 80 ...

ok,This is a bug.

**Comment by IntelligentQuantum** [comment]
You can close BG with this command.
`.disable add battleground 1 0 Alterac Valley (battleground)`
