### ISSUE TITLE
Makrura Clacker and Surf Crawler buggy movement and sometimes freezing inside the water

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6784]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1115

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The mobs called Makrura Clacker and Surf Crawler have a buggy movement on the location Echo Isles in Durotar. Sometimes during a fight with them they go down in the water and sometimes freeze in one place and you can attack them without them coming to you. As well as that, some of them just move left to right without stopping and it says "Evade" when you try to attack these ones.

Makrura clacker: https://wotlkdb.com/?npc=3103
Surf crawler: https://wotlkdb.com/?npc=3107

### Expected Blizzlike Behaviour

They just should have a normal movement like any other mobs you fight and not freeze at one place at times.

### Source

I don't have screenshots but if you teleport to Echo Isles and go to the waters you will instantly see these NPC's are buggy.

### Steps to reproduce the problem

Just teleport to npc's called Makrura Clacker and Surf Crawler.

### Extra Notes

I provided links above for the NPC's.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

### Operating system

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: dc76e6b) :

![WoWScrnShot_070721_045516](https://user-images.githubusercontent.com/82579073/124689081-8d530180-dee0-11eb-8df1-61e426434549.jpg)
![WoWScrnShot_070721_045803](https://user-images.githubusercontent.com/82579073/124689099-96dc6980-dee0-11eb-9f8f-190a18c2a93a.jpg)

**Comment by claudiodfc** [comment]
#9272 probably fixes this

**Comment by acidmanifesto** [comment]
Closes due to fix: https://github.com/azerothcore/azerothcore-wotlk/pull/9272

**Comment by Pyromanihack** [comment]
I reopened this issue because it's still bugged, I'm on a2018edade7e 2022-12-29

**Comment by Gultask** [comment]
Will be fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/13705

**Comment by heyitsbench** [comment]
By the way, (if I'm not mistaken) if an issue was closed from a merged PR/commit, a new issue would be created rather than re-opening the old one.
