### ISSUE TITLE
Console error messages

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6785]
### Current Behaviour

![20210707084845](https://user-images.githubusercontent.com/18187177/124689841-d53b4e00-df0b-11eb-9291-44388a356692.jpg)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. update to 341d65c1db0d99c0603e04edbe2fc37314cf20dc
2. It appeared after a few hours of operation

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

### Operating system

ubuntu20.04

**Comment by SKingOWN** [comment]
I have the same problem, with a realm with more than 1000 players online it spam the console
