### ISSUE TITLE
Console error messages 2

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6786]
### Current Behaviour

![20210707105708](https://user-images.githubusercontent.com/18187177/124693606-54cc1b80-df12-11eb-91f3-551e424e8845.jpg)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

I don't know why it appears. It's rolling all the time

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

### Operating system

ubuntu20.04

**Comment by mpfans** [comment]
After asking the player, the macro was executed
`/run if(not LW)then CreateFrame("Frame","LW",UIParent);end LW:SetScript("OnUpdate",function() local a=GetWintergraspWaitTime();if(not a or a<900) then BattlefieldMgrQueueRequest(1);if(a)then LW:SetScript("OnUpdate",nil);end end end);message("Enable delay to join Wintergrasp");`

**Comment by SKingOWN** [comment]
I have the same problem sometimes

**Comment by FrancescoBorzi** [comment]
> I have the same problem sometimes

@SKingOWN are you on Discord?

**Comment by SKingOWN** [comment]
> > I have the same problem sometimes
> 
> @SKingOWN are you on Discord?

@FrancescoBorzi no
I can read and write in english so so but I speak spanish :)

**Comment by FrancescoBorzi** [comment]
> > > I have the same problem sometimes
> > 
> > 
> > @SKingOWN are you on Discord?
> 
> @FrancescoBorzi no
> I can read and write in english so so but I speak spanish :)

@skingown it would be nice if you can join our Discord so we can chat and help each other

**Comment by Kitzunu** [comment]
I cannot reproduce it with the steps given
