### ISSUE TITLE
RDF party disbands after player leaving during looking for more

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6790]
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/804

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There was only 3 of us left in Deadmines. We could not re-queue and we were no longer in the RDF system it seemed (no indicator on the minimap to teleport out). We wiped on Smite from him pulling the pirates on the platform (known bug). After running back as a ghost, we could not enter the instance or revive. The message "Map cannot be entered at this time." kept displaying. We each attempted a logout for 1 minute at least twice, but could still not enter the instance or revive outside the instance.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normally it should either let us in the instance to revive or revive us right outside the instance with the message saying we can't enter.

##### STEPS TO REPRODUCE THE PROBLEM:

1. 1 person left while queued for RDF and in the instance.
2. The 3 of us left couldn't re-queue or teleport out of the instance.
3. Wiped on Smite.
4. Ghost ran back to enter instance.
5. Repeatedly got the message "Map cannot be entered at this time."
6. Logged out for a minute and tried to enter on re-log with the same result.
7. Repeated step 6.

##### EXTRA NOTES:

Not sure if it makes a difference, 2 of us were alliance and the 3rd was horde. Again we were no longer part of the RDF system (no queue or teleport), but still had the buff.

Roboto noted:

The real issue is: when someone leaves the RDF group, and the group decides to search for another member to replace the one that left, if another member leaves during the search, it will "disband" the RDF group, which prevents remaining members from entering the instance again.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Azcobu** [comment]
See also https://github.com/chromiecraft/chromiecraft/issues/1322 for what looks to be the same issue.

**Comment by r-o-b-o-t-o** [comment]
@FrancescoBorzi I think we should keep this one open, UltraNix's commit fixes the revive issue but it doesn't fix the core problem (the fact that RDF parties get disbanded)
