### ISSUE TITLE
new crash log 

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6797]
### Current Behaviour

logs

https://gist.github.com/mpfans/25c45261780818ad8961d6fab2b05efd

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. 019884c7d479+ 2021-07-06 19:00:29 +0800 (pr-6378 branch) (Unix, RELWITHDEBINFO, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using ACE version: 6.4.5
Using Boost version: 1.71.0
Using MySQL version: 80025
Using CMake version: 3.16.3
Compiled on: Linux 
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/data/vmaps. Total size: 658638902 bytes
mmaps directory located in /home/data/mmaps. Total size: 2196401108 bytes
Using World DB: ACDB 335.3
Using World DB Revision: 2021_07_06_00
Using Character DB Revision: 2021_07_06_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

ubuntu 20.04

**Comment by Kitzunu** [comment]
You are running a PR branch... Why?

**Comment by FrancescoBorzi** [comment]
@Kitzunu yet another assert which takes down the entire server.... we should replace it with an error log instead

**Comment by Kitzunu** [comment]
Maybe it is due to the PR he is running.

Is this happening on latest master?

**Comment by mpfans** [comment]
> Maybe it is due to the PR he is running.
> 
> Is this happening on latest master?

master: 341d65c1db0d99c0603e04edbe2fc37314cf20dc

**Comment by mpfans** [comment]
@UltraNix  help!!!!!!please!

**Comment by UltraNix** [comment]
```
WorldSession::HandlePetActionHelper at /home/polly/azerothcore/src/server/game/Handlers/PetHandler.cpp:556
```
```
 ObjectAccessor::GetPlayer (u=..., guid=...) at /home/polly/azerothcore/src/server/game/Globals/ObjectAccessor.cpp:220
 ```

But there is no such code there 
```
if (Unit* owner = pet->GetOwner())
```

**Comment by mpfans** [comment]
> ```
> WorldSession::HandlePetActionHelper at /home/polly/azerothcore/src/server/game/Handlers/PetHandler.cpp:556
> ```
> 
>  ```
>  ObjectAccessor::GetPlayer (u=..., guid=...)
> ```
> 
> But there is no such code there
> 
> ```
> if (Unit* owner = pet->GetOwner())
> ```
> 
> @mpfans
> Did you modify that file?

no modify..

![image](https://user-images.githubusercontent.com/18187177/124844801-d336c500-dfc7-11eb-9a06-0406e73e5941.png)

 my server this file 556 line..
![image](https://user-images.githubusercontent.com/18187177/124844953-3b85a680-dfc8-11eb-93cc-1ecb8d8867df.png)

this is ac core
https://github.com/azerothcore/azerothcore-wotlk/blob/f8139ba00a68e642ca8c6e9a1e85ebef0f497751/src/server/game/Handlers/PetHandler.cpp#L556

**Comment by Kitzunu** [comment]
Latest master 
https://github.com/azerothcore/azerothcore-wotlk/blob/bf139c3d34c09eeabafe8f22ca64a670e203c075/src/server/game/Handlers/PetHandler.cpp#L556
Line 556 is empty

**Comment by mpfans** [comment]
crash again

https://gist.github.com/mpfans/2718aeda76a0fcbc000e181c3fc5377e

**Comment by mpfans** [comment]
Crash after accepting PR 6805

https://gist.github.com/mpfans/98e827f52819e6cc17ccc09f7a416c7a

**Comment by UltraNix** [comment]
So this is something fucked up in the core.
`_player` is in world, but got no map???

**Comment by Viste** [comment]
> So this is something fucked up in the core.
> `_player`/`pet` is in world, but got no map???
its could be also wpe manipulations i guess

**Comment by lineagedr** [comment]
@mpfans  Did you apply https://github.com/azerothcore/azerothcore-wotlk/pull/6805/commits/94ebd40e7419b2951400417b4d7e9840417904f4 or only https://github.com/azerothcore/azerothcore-wotlk/pull/6805/commits/8f79ba8120beddbe20af54e923c205f1a60675da

**Comment by mpfans** [comment]
> @mpfans Did you apply [94ebd40](https://github.com/azerothcore/azerothcore-wotlk/commit/94ebd40e7419b2951400417b4d7e9840417904f4) or only [8f79ba8](https://github.com/azerothcore/azerothcore-wotlk/commit/8f79ba8120beddbe20af54e923c205f1a60675da)

updated to 94ebd40e7419b2951400417b4d7e9840417904f4

It's been running for 16 hours without a crash
