### ISSUE TITLE
DB/Quest fix: Translation to Ello - Add Endevent

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#68]
Commit: TrinityCore/TrinityCore@222ba50
TrinityCore/TrinityCore#16514

Quest: http://www.wowhead.com/quest=252/translation-to-ello

fix:

-- DB/Quest: Translation to Ello
DELETE FROM waypoints WHERE entry=412;
INSERT INTO waypoints (entry, pointid, position_x, position_y, position_z) VALUES 
(412, 1, -10290.1, 73.7148, 38.849),
(412, 2, -10290.4, 81.547, 38.7702),
(412, 3, -10283.2, 86.6661, 38.7694),
(412, 4, -10271.1, 83.5772, 39.1122),
(412, 5, -10266, 76.0585, 39.4047),
(412, 6, -10272.4, 65.7703, 39.524),
(412, 7, -10283.4, 59.1681, 40.6902),
(412, 8, -10300.2, 45.8306, 47.3053),
(412, 9, -10315.3, 45.1015, 48.0097),
(412, 10, -10324.4, 38.7441, 47.3935),
(412, 11, -10330.2, 27.0829, 50.5753),
(412, 12, -10335.3, 13.4164, 50.1259),
(412, 13, -10342.2, 3.3501, 51.1675),
(412, 14, -10354.6, -13.0266, 47.1154),
(412, 15, -10379.4, -27.1456, 49.2841),
(412, 16, -10401, -30.8108, 48.1353),
(412, 17, -10416.5, -28.4794, 48.4772),
(412, 18, -10436.4, -34.2376, 46.5064),
(412, 19, -10468.7, -38.8985, 48.7035),
(412, 20, -10500.2, -44.6662, 45.882),
(412, 21, -10539.1, -39.3422, 43.0622),
(412, 22, -10568, -35.1434, 37.2048),
(412, 23, -10585.6, -37.5056, 37.4296),
(412, 24, -10606.3, -51.7202, 36.0713),
(412, 25, -10629.2, -64.211, 32.6163),
(412, 26, -10645.9, -73.4561, 32.7337),
(412, 27, -10671, -81.8316, 35.6535),
(412, 28, -10687.6, -85.57, 34.1549),
(412, 29, -10702.8, -89.2772, 37.9242),
(412, 30, -10709.1, -97.5837, 37.892),
(412, 31, -10725.6, -101.348, 34.5892),
(412, 32, -10748, -99.1517, 38.2323),
(412, 33, -10759.9, -93.0657, 38.5876),
(412, 34, -10774.9, -89.8001, 34.8007),
(412, 35, -10788.6, -86.7376, 33.4988),
(412, 36, -10802.7, -88.6347, 29.0679),
(412, 37, -10811.5, -97.1736, 29.2451),
(412, 38, -10821.4, -121.335, 30.142),
(412, 39, -10826.2, -134.391, 31.7845),
(412, 40, -10830.6, -148.284, 31.7985),
(412, 41, -10835.3, -164.201, 33.8299),
(412, 42, -10840.4, -182.63, 34.0254),
(412, 43, -10843.3, -193.104, 35.8227),
(412, 44, -10848.7, -215.175, 37.7986),
(412, 45, -10851.7, -235.779, 38.6853),
(412, 46, -10857.4, -264.019, 38.0974),
(412, 47, -10866.6, -293.454, 37.9429),
(412, 48, -10882.9, -332.562, 37.9688),
(412, 49, -10900, -365.26, 39.4542),
(412, 50, -10904.1, -393.833, 41.0451),
(412, 51, -10905.7, -431.964, 42.7237),
(412, 52, -10908, -461.901, 46.7191),
(412, 53, -10911.2, -510.492, 52.0594),
(412, 54, -10915.1, -533.78, 53.8047),
(412, 55, -10927, -565.685, 54.042),
(412, 56, -10936.5, -581.62, 53.8887),
(412, 57, -10950.1, -597.371, 55.177),
(412, 58, -10957.9, -619.554, 55.0689),
(412, 59, -10958.8, -637.183, 55.2047),
(412, 60, -10954.3, -652.46, 55.4423),
(412, 61, -10931.8, -681.568, 55.3955),
(412, 62, -10916.9, -710.733, 55.6988),
(412, 63, -10902.9, -734.1, 55.1313),
(412, 64, -10878.3, -760.091, 55.5638),
(412, 65, -10851.1, -787.76, 56.1885),
(412, 66, -10831.9, -818.655, 56.2795),
(412, 67, -10825.2, -833.223, 55.5758),
(412, 68, -10808.3, -873.497, 55.9567),
(412, 69, -10796.7, -912.719, 55.8731),
(412, 70, -10796.1, -934.562, 56.2303),
(412, 71, -10800.5, -949.721, 56.5614),
(412, 72, -10807.1, -969.027, 56.2941),
(412, 73, -10806.8, -992.166, 53.8349),
(412, 74, -10804.6, -1030.41, 47.0768),
(412, 75, -10801.3, -1047.26, 44.0233),
(412, 76, -10787.8, -1074.49, 37.7652),
(412, 77, -10783.3, -1095.07, 33.6488),
(412, 78, -10781.2, -1112.66, 30.3863),
(412, 79, -10763.6, -1138.91, 27.0977),
(412, 80, -10738, -1158.02, 26.4475),
(412, 81, -10705.3, -1179.29, 26.3723),
(412, 82, -10682.3, -1190.45, 27.2793),
(412, 83, -10662.5, -1193.06, 28.2884),
(412, 84, -10641.6, -1189.92, 28.5594),
(412, 85, -10615.7, -1182.78, 28.5022),
(412, 86, -10586.8, -1177.32, 28.3931),
(412, 87, -10576.4, -1179.26, 28.1946),
(412, 88, -10566.7, -1189.27, 27.8756),
(412, 89, -10557, -1192.38, 28.0606),
(412, 90, -10550.4, -1185.71, 27.8428),
(412, 91, -10554.4, -1167.97, 27.5984);

-- Lord Ello Ebonlocke SAI
SET @ENTRY := 263;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY;
DELETE FROM smart_scripts WHERE entryorguid=@ENTRY AND source_type=0;
INSERT INTO smart_scripts (entryorguid,source_type,id,link,event_type,event_phase_mask,event_chance,event_flags,event_param1,event_param2,event_param3,event_param4,action_type,action_param1,action_param2,action_param3,action_param4,action_param5,action_param6,target_type,target_param1,target_param2,target_param3,target_x,target_y,target_z,target_o,comment) VALUES
(@ENTRY,0,0,0,1,0,100,0,20000,30000,120000,120000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Lord Ello Ebonlocke - Out of Combat - Say Line 0"),
(@ENTRY,0,1,0,20,0,100,0,252,0,0,0,12,412,3,3600000,0,0,0,8,0,0,0,-10290.171875,72.781136,38.881119,4.801499,"Lord Ello Ebonlocke - On Quest 'Translation to Ello' Finished - Summon Creature 'Stitches'");

-- Stitches SAI
SET @ENTRY := 412;
UPDATE creature_template SET AIName="SmartAI" WHERE entry=@ENTRY;
DELETE FROM smart_scripts WHERE entryorguid=@ENTRY AND source_type=0;
INSERT INTO smart_scripts (entryorguid,source_type,id,link,event_type,event_phase_mask,event_chance,event_flags,event_param1,event_param2,event_param3,event_param4,action_type,action_param1,action_param2,action_param3,action_param4,action_param5,action_param6,target_type,target_param1,target_param2,target_param3,target_x,target_y,target_z,target_o,comment) VALUES
(@ENTRY,0,0,0,0,0,100,0,6900,12100,3500,11300,11,3106,0,0,0,0,0,2,0,0,0,0,0,0,0,"Stitches - In Combat - Cast 'Aura of Rot'"),
(@ENTRY,0,1,2,54,0,100,0,0,0,0,0,48,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stitches - On Just Summoned - Set Active On"),
(@ENTRY,0,2,0,61,0,100,0,0,0,0,0,53,1,412,0,0,0,2,0,0,0,0,0,0,0,0,"Stitches - On Just Summoned - Start Waypoint"),
(@ENTRY,0,3,0,40,0,100,0,47,412,0,0,1,0,0,0,0,0,0,19,468,200,0,0,0,0,0,"Stitches - On Waypoint 47 Reached - Say Line 0"),
(@ENTRY,0,5,6,40,0,100,0,50,412,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stitches - On Waypoint 50 Reached - Say Line 0"),
(@ENTRY,0,6,0,61,0,100,0,50,412,0,0,1,1,0,0,0,0,0,19,468,200,0,0,0,0,0,"Stitches - On Waypoint 50 Reached - Say Line 1"),
(@ENTRY,0,7,8,40,0,100,0,91,412,0,0,101,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stitches - On Waypoint 91 Reached - Set Home Position"),
(@ENTRY,0,8,0,61,0,100,0,91,412,0,0,89,20,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stitches - On Waypoint 91 Reached - Start Random Movement");

DELETE FROM creature_text WHERE entry IN (468, 412);
INSERT INTO creature_text (entry, groupid, id, text, type, language, probability, emote, duration, sound, comment) VALUES 
(468, 0, 0, 'An abomination of the undead is approaching!', 14, 0, 100, 0, 0, 0, 'Guard'),
(468, 1, 0, 'The abomination has overrun the Night Watch camp! Quickly, we must intercept it before it reaches town!', 14, 0, 100, 0, 0, 0, 'Guard'),
(412, 0, 0, 'ROARRRRR!!', 14, 0, 100, 0, 0, 0, 'Stitches'),
(412, 0, 1, 'DARKSHIRE... I HUNGER!!', 14, 0, 100, 0, 0, 0, 'Stitches');

-- We need to local patch..

**Comment by ShinDarth** [comment]
please open a PR, read https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute

**Comment by BarbzYHOOL** [comment]
@bungisk if you want to test after all this time :P
