### ISSUE TITLE
CI: Login to Docker Hub failing

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#6803]
The build `docker-build / docker-build-n-deploy ` is always failing the `Login to Docker Hub` step **in all PRs** with:

```
Error: Username and password required
```
**NOTE**: it still passes on `master`

Example: https://github.com/azerothcore/azerothcore-wotlk/pull/6800/checks?check_run_id=3013239052

**Comment by FrancescoBorzi** [comment]
@locus313 can you please have a look at this?

**Comment by locus313** [comment]
@FrancescoBorzi this pr https://github.com/azerothcore/azerothcore-wotlk/pull/6716 should address it

**Comment by FrancescoBorzi** [comment]
@locus313 looks like still failing: https://github.com/azerothcore/azerothcore-wotlk/pull/6838/checks?check_run_id=3027868722

**Comment by locus313** [comment]
@FrancescoBorzi ok, ill look further into this.
