### ISSUE TITLE
reload conf report error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6806]
### Current Behaviour

`reload conf`  report error
![image](https://user-images.githubusercontent.com/18187177/124878566-d0a39200-dffe-11eb-8ac6-fc4fa996273a.png)

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1.start worldserver
2.Enter `reload conf` in the console

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc
### Operating system

ubuntu 20.04

**Comment by Helias** [comment]
already fixed here https://github.com/azerothcore/azerothcore-wotlk/pull/6705

**Comment by mpfans** [comment]
> already fixed here #6705

ok,tyvm!
