### ISSUE TITLE
New server crash

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#6808]
```
Thread 16 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7feef07ff700 (LWP 17996)]
0x0000000001402c22 in Acore::Assert (file=0x14f317c "/root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Object/Object.h", line=941, function=0x14f3fe8 "GetMap", debugInfo=..., message=0x14f3fef "m_currMap") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:64
64	        Crash(formattedMessage.c_str());
#0  0x0000000001402c22 in Acore::Assert (file=0x14f317c "/root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Object/Object.h", line=941, function=0x14f3fe8 "GetMap", debugInfo=..., message=0x14f3fef "m_currMap") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:64
#1  0x0000000000d760a5 in WorldObject::GetMap (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Object/Object.h:941
#2  ObjectAccessor::GetPlayer (u=..., guid=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Globals/ObjectAccessor.cpp:220
#3  0x0000000000f03bcb in WorldSession::HandlePetActionHelper (this=0x7fee574f9100, pet=0x7fee4e23d000, guid1=..., spellid=<optimized out>, flag=<optimized out>, guid2=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/PetHandler.cpp:556
#4  0x0000000000f02f25 in WorldSession::HandlePetAction (this=<optimized out>, recvData=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/PetHandler.cpp:450
#5  0x000000000102cd7c in WorldSession::Update (this=0x7fee574f9100, diff=10, updater=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:347
#6  0x00000000012252f1 in World::UpdateSessions (this=0x7fef48e52000, diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/World/World.cpp:2696
#7  0x00000000012226d6 in World::Update (this=0x7fef48e52000, diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/World/World.cpp:2234
#8  0x0000000000459231 in WorldRunnable::run (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/WorldThread/WorldRunnable.cpp:48
#9  0x00007fef4b8aad84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fef4b9c4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007fef4b598293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@UltraNix this might be similar to the one reported by @mpfans 

the core is a clean one, with no modifications (only those modules added)

**Comment by mpfans** [comment]
> @UltraNix this might be similar to the one reported by @mpfans
> 
> the core is a clean one, with no modifications (only those modules added)

Confirm that the cause of the crash is the same
