### ISSUE TITLE
Missing Movement - Dart, Dustwallow Marsh

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6820]
Original report: https://github.com/chromiecraft/chromiecraft/issues/981

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Dart (https://wowgaming.altervista.org/aowow/?npc=14232) GUID 200145, is stationary in his spawn point.

Tester: Confirmed, movementType = 0. Relevant YT video shows he should be moving.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dart should be running around in a circle around the location where Bloodfen screechers are.

##### SOURCE:

https://classic.wowhead.com/npc=14232/dart#comments

https://youtu.be/v48zpFGzDFk

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 200145
2. Observe him stationary

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
More info: Dart has wrong spawn timer. its currently set to 5 minutes! where it should be 5-8h.
source World of Warcraft Atlas
![Raretimers](https://user-images.githubusercontent.com/80769357/126553797-8046bf94-2196-4956-8851-abc85e4b5b9e.jpg)
![dart](https://user-images.githubusercontent.com/80769357/126553800-968af382-3500-4ac7-8109-ac98d53cc60c.jpg)

**Comment by T1ti** [comment]
> More info: Dart has wrong spawn timer. its currently set to 5 minutes! where it should be 5-8h.
> source World of Warcraft Atlas
> ![Raretimers](https://user-images.githubusercontent.com/80769357/126553797-8046bf94-2196-4956-8851-abc85e4b5b9e.jpg)
> ![dart](https://user-images.githubusercontent.com/80769357/126553800-968af382-3500-4ac7-8109-ac98d53cc60c.jpg)

Do you have this book in digital format ? I am very interested in it
