### ISSUE TITLE
Missing Movement - Kassk, Desolace

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6821]
Original report: https://github.com/chromiecraft/chromiecraft/issues/991#issuecomment-867789140

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/991#issuecomment-867789140

Kassk (https://wowgaming.altervista.org/aowow/?npc=14226), GUID 51850,  Is missing movement pattern.

Tester: confirmed, MovementType = 0.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Kassk should be moving around his spawn area.

##### SOURCE:

https://youtu.be/sCRV0gB0hcs?t=318

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 51850
2. Observe no movement

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
More info. Kaskk also has wrong respawn timer. Its set to 2h 45 min when it should be 32 - 48h.
Source World of Warcraft Atlas
![Raretimers](https://user-images.githubusercontent.com/80769357/126551232-722e7323-e172-455c-802c-86337899be9c.jpg)
![kaskk](https://user-images.githubusercontent.com/80769357/126551236-afb0fd35-8bdf-488d-9c2a-13f3cffdd871.jpg)

He currently only spawns at 1 point, but wowhead has 5-6 possible listed
https://classic.wowhead.com/npc=14226/kaskk#map
