### ISSUE TITLE
Missing Movement - Omgron the Lost, Tanaris

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6825]
Original report: https://github.com/chromiecraft/chromiecraft/issues/992#issuecomment-872203218

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Omgron the Lost is stationary in his current spawn point in Dunmaul Compound.

Tester: confirmed. Judging from YT/maps, he looks like he should have a proper circular patrol around the ruins, so just fixing movement/wander_dist won't be enough for this one.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Omgron the Lost GUID 51831 (https://wowgaming.altervista.org/aowow/?npc=8201) should be patrolling around one of the tree locations he spawns.
<html><body>
<div class="comment-header">

By therio on 2005/02/11 (Patch 1.2.1) |   |  
-- | -- | --

</div><div class="text comment-body comment-high-rating" lang="en"><span class="comment-imported-subject">Subject: <span>"&lt;Blank&gt;"</span></span>Omgorn
 walks around the outer edges of the Eastmoon and Southmoon ruins, and 
the edges of the Dunemaul Compound in Tanaris.  I killed him at the 
Eastmoon ruins first.  He respawned at the Southmoon ruins, and I killed
 him again.  Both times, he was found circling the ruins in a clockwise 
direction.<br><br>He appears identical to a Dunemaul Brute.  Both times, he was wielding a two-handed axe.</div>
</body>
</html>

##### SOURCE:

https://classic.wowhead.com/npc=8201/omgorn-the-lost#comments

https://www.youtube.com/watch?v=Oy8sfxP9zNI

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 51831
2. Observe no mvement

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by gurveleg** [comment]
More info. Omgron the lost has wrong respawn timer, currently 2h 45 min, should be 10.5-16h.
Source World of Warcraft atlas
![Raretimers](https://user-images.githubusercontent.com/80769357/126562223-d5cd3740-313e-46e3-af38-16bfd5ca44fa.jpg)
![omgron](https://user-images.githubusercontent.com/80769357/126562224-3c58d6f1-b1b3-4f2d-a6f4-a3d36731ff07.jpg)
