### ISSUE TITLE
Using a portal while mounted leaves your pet behind [$15]

### ISSUE THREAD

**Issue by necropola** [azerothcore/azerothcore-wotlk#6830]
Original report https://github.com/chromiecraft/chromiecraft/issues/1132 by @necropola

#### WHAT CLIENT DO YOU PLAY ON?
- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION
- [x] Alliance
- [x] Horde

##### CONTENT PHASE:
- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
When using a (custom) City Portal on CC or a Mage Portal or a City portal in Shattrath/Dalaran (local AC) as a Warlock or Hunter while mounted, you are dismounted on arrival and your pet is left behind. The pet's nameplate is grayed out and when you go back (CC city portal) your pet is still there.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pets should always follow their master through portals. Also when mounted.

##### SOURCE:
Obvious.

##### STEPS TO REPRODUCE THE PROBLEM:
- As a Warlock or Hunter summon/call your pet
- Mount up
- Go through a portal
- Observe that you pet was left behind

##### EXTRA NOTES:
I had this also happen on my Hunter when teleported to an RDF dungeon while on a flight path, i. e. I had to do the whole dungeon without my pet (which was probably having a blast flying over Azeroth without its master).

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@necropola stop closing issues without reason
