### ISSUE TITLE
Malygos in The Eye of Eternity

### ISSUE THREAD

**Issue by kokutek** [azerothcore/azerothcore-wotlk#6835]
### Current Behaviour

Malygos visual bug, when the boss flyes down, hes still stucked in fly movement type.

### Expected Blizzlike Behaviour

Malygos should not fly when the boss it self is attacking from ground.

### Steps to reproduce the problem

Just enter the instance The Eye of Eternity.

### Extra Notes

The creature it self has the right MovementType in creature table (7), but has a wrong one in creature_template, this query should fix it.
Update creature_template set MovementType=7 Where entry=28859

### AC rev. hash/commit

No needed.

### Operating system

Debian 10 x64

**Comment by Kitzunu** [comment]
Don't ignore the template.
