### ISSUE TITLE
Worldserver crashing

### ISSUE THREAD

**Issue by Voorh** [azerothcore/azerothcore-wotlk#6842]
### Current Behaviour

I exported all the SQL to the database and even so errors are happening during the execution of the worldserver, I'll leave the error link below;
[https://gist.github.com/Voorh/689f1f1d3ba30e317b4c6f5cd08e2a9a#file-worldserver-crashing](https://gist.github.com/Voorh/689f1f1d3ba30e317b4c6f5cd08e2a9a#file-worldserver-crashing) 

### Expected Blizzlike Behaviour

Don't make mistakes

### Steps to reproduce the problem

1. compile the core
2. Run authserver.exe and worldserver.exe
3. The error happens

### AC rev. hash/commit

> 439a940

### Operating system

Windows

**Comment by Kitzunu** [comment]
What MySQL version do you use? 

Can you run these three queries and post the result
```sql
SELECT * FROM version_db_world WHERE DATE ORDER BY DATE DESC LIMIT 1;
SELECT * FROM version_db_characters WHERE DATE ORDER BY DATE DESC LIMIT 1;
SELECT * FROM version_db_auth WHERE DATE ORDER BY DATE DESC LIMIT 1;
```

**Comment by Voorh** [comment]
> What MySQL version do you use?
> 
> Can you run these three queries and post the result
> 
> ```sql
> SELECT * FROM version_db_world WHERE DATE ORDER BY DATE DESC LIMIT 1;
> SELECT * FROM version_db_characters WHERE DATE ORDER BY DATE DESC LIMIT 1;
> SELECT * FROM version_db_auth WHERE DATE ORDER BY DATE DESC LIMIT 1;
> ```

Mysql5.7

**Comment by Kitzunu** [comment]
Run the queries

**Comment by WillzDevs** [comment]
> Execute as consultas

SELECT * FROM version_db_world WHERE DATE ORDER BY DATE DESC LIMIT 1;
SELECT * FROM version_db_characters WHERE DATE ORDER BY DATE DESC LIMIT 1;
SELECT * FROM version_db_auth WHERE DATE ORDER BY DATE DESC LIMIT 1;
+---------------------+--------------+---------------+---------------+
| sql_rev             | required_rev | date          | 2021_07_08_03 |
+---------------------+--------------+---------------+---------------+
| 1622194253034538200 | NULL         | 2021_07_08_03 | NULL          |
+---------------------+--------------+---------------+---------------+
1 row in set (0.05 sec)

1146 - Table 'world.version_db_characters' doesn't exist
1146 - Table 'world.version_db_auth' doesn't exist

**Comment by Voorh** [comment]
I managed to solve the problem, worldserver working
