### ISSUE TITLE
[Mount] The "Riding Turtle" does not increase swim speed by 60 %

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#6844]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: [chromiecraft/issues/#1130](https://github.com/chromiecraft/chromiecraft/issues/1130)

##### CURRENT BEHAVIOUR:

The Riding Turtle mount from TCG (item shop) does not increase swimming speed to 60%

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The mount is supposed to increase your swim (mounted) speed by 60% in water.

##### SOURCE:

https://warcraftmounts.com/mounts/ridingturtle.php
https://aminoapps.com/c/wow/page/blog/riding-turtle-sea-turtle-how-to/o3Mc_duqqGxggorZoN6b1nglV05QpY8
https://www.reddit.com/r/wow/comments/7wzlzz/the_riding_turtle_does_not_note_this_in_the/

##### STEPS TO REPRODUCE THE PROBLEM:

1. Buy riding turtle
2. Mount up
3. Swim mounted
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed on local AC(458469e)

**Comment by Kitzunu** [comment]
No. You are wrong.

https://wowwiki-archive.fandom.com/wiki/Riding_Turtle?oldid=2170229

Riding turtle is just for looks, at least in Wrath. 

https://wowwiki-archive.fandom.com/wiki/Sea_Turtle_(mount)?oldid=2464648

Sea Turtle is the mount that increases your swim speed

**Comment by syssneck** [comment]
Whups, my bad. The information on the original linked websites were misleading.

**Comment by TheDiscordian** [comment]
I was wondering why the Riding Turtle TCG mount didn't give a 100% speed boost in water (https://www.wowhead.com/wotlk/item=23720/riding-turtle#comments:id=208582  & https://www.wowhead.com/wotlk/item=23720/riding-turtle#comments:id=8863:reply=426377  indicate the turtle increases speed in water).

But then I saw this issue.

This video [here](https://youtu.be/JgrAVh6fi4Y?si=iv9T8QjUE47VQQwg&t=596) says the Riding Turtle was granted a movement speed buff after the Sea Turtle was introducted in WotLK, which matches the timeline of the two comments on WoWHead's edit/post dates.

To me, this is evidence enough that's how the turtle worked during WotLK ([Daldain](https://www.wowhead.com/wotlk/user=Daldain) is extremely reliable). Is there any chance the issue can get re-opened? (though I find conflicting comments about 60% or 100% speed, and haven't been able to find any videos of anyone actually swimming with the turtle on WotLK yet, it seems to me like it was more than a 0% increase by 3.3.5a. I'm leaning on 100% though as anything I read saying 60% seems to be newer...)
