### ISSUE TITLE
Incorrect behaviour for Felwood Corrupted Flowers

### ISSUE THREAD

**Issue by eTzmNcbkrng** [azerothcore/azerothcore-wotlk#6845]
ChromieCraft issue: https://github.com/chromiecraft/chromiecraft/issues/1134

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Cleansing a [Corrupted Songflower](https://classic.wowhead.com/objects/quests/name:Corrupted+Songflower) causes it to despawn and a [Cleansed Songflower](https://classic.wowhead.com/objects/interactive-objects/name:Cleansed+Songflower) to take its place.
Interacting with a Cleansed Songflower causes it to instantly disappear.

Cleansing a [Corrupted Night Dragon](https://classic.wowhead.com/objects/quests/name:Corrupted+Night+Dragon) does not despawn it and only sometimes causes a [Cleansed Night Dragon](https://classic.wowhead.com/objects/interactive-objects/name:Cleansed+Night+Dragon) to spawn in the same location.
If a [Cleansed Night Dragon](https://classic.wowhead.com/objects/interactive-objects/name:Cleansed+Night+Dragon) does successfully spawn, it only despawns after about 30 minutes and in this time can be looted endlessly to grant an infinite number of [Night Dragon's Breath](https://classic.wowhead.com/item=11952/night-dragons-breath)

[Corrupted Whipper Root](https://classic.wowhead.com/objects/quests/name:Corrupted+Whipper+Root) and [Cleansed Whipper Root](https://classic.wowhead.com/objects/interactive-objects/name:Cleansed+Whipper+Root) have the same problem granting an endless supply of [Whipper Root Tuber](https://classic.wowhead.com/item=11951/whipper-root-tuber)
[Corrupted Windblossom](https://classic.wowhead.com/objects/quests/name:Corrupted+Windblossom) and [Cleansed Windblossom](https://classic.wowhead.com/objects/interactive-objects/name:Cleansed+Windblossom) have the same problem granting an endless supply of [Windblossom Berries](https://classic.wowhead.com/item=11950/windblossom-berries)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When a Corrupted Flower is cleansed, it should respawn after 25 minutes.
When a Cleansed Flower is spawned, it should despawn after 15 minutes.
- This point is contentious, I found some videos that showed completing the quest gives the buffs and some videos didn't get the buff. I'm inclined to believe it may have been a private server bug and the Cleansed Flower always needs to be clicked after completing the quest.

Corrupted Flowers seem to be intended to be used by only one person, but, in WoW Classic, if multiple people click them at the same time they will all get reward (confirmed with Songflower buff, unconfirmed with the item rewards).
Once a Cleansed Flower has been interacted with, it should dim, cease to be interactive and remain visible for an **_as yet undetermined amount of time_**

##### SOURCE:

The Songflower is the most documented (only) of these four flowers because it provides a very beneficial world buff in Classic, I am assuming that all 4 flowers behave the same.

This video shows multiple people receving the buff from Songflower and the Cleasned Songflower does not despawn immediately - https://www.youtube.com/watch?v=Esi7SgvxHRM
Similar video but shows Songflower was still visible at least 19 seconds after it was used to grant a buff - https://www.youtube.com/watch?v=7JvKNDwMCkY

A few things of note in [this](https://gamerjournalist.com/wow-classic-world-buff-cooldowns) article, unfortunately no citation is provided

- Each Songflower respawns in ~20 minutes.
- [Also talking about Corrupted Songflower] Cooldown: 25 minutes
- These often spawn cleansed but if one has not been activated in a while, it will be corrupted.

##### STEPS TO REPRODUCE THE PROBLEM:

`.additem 11516 100`
Complete quests.

##### EXTRA NOTES:

Just had someone in game (ChromieCraft) complain after they cleansed a songflower, the corrupted object disappeared but the cleansed one did not appear. On the third attempt it showed up, but only after moving.
I, as a GM, was able to see the Cleansed object but it disappeared when I typed `.gm off`.
There is something weird with the objects not showing and sometimes moving away a very short distance seems to fix it

SQL query to get the GUID of all the spawns:
```SQL
select obj.name, obj.entry, spawn.guid from gameobject_template obj
join gameobject spawn on spawn.id = obj.entry
where obj.name IN ('Corrupted Night Dragon','Corrupted Songflower','Corrupted Windblossom','Corrupted Whipper Root')
```
Output pasted in comment below

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@eTzmNcbkrng thanks for triaging this bug. For next time, please don't forget to add the content label and project too (in this case 40-49)

**Comment by eTzmNcbkrng** [comment]
Results of checking each GUID:

name|entry|guid|teleportcommand|comment
--|--|--|--|--|
Corrupted Night Dragon|164885|48848|`.go obj 48848`|Yes but no despawn
Corrupted Night Dragon|173324|48849|`.go obj 48849`|Yes but no despawn
Corrupted Night Dragon|174608|48847|`.go obj 48847`|Yes but no despawn
Corrupted Night Dragon|174684|48850|`.go obj 48850`|Yes but no despawn
Corrupted Songflower|164886|48943|`.go obj 48943`|Instant Despawn?
Corrupted Songflower|171939|48852|`.go obj 48852`|Instant Despawn?
Corrupted Songflower|171942|48924|`.go obj 48924`|Instant Despawn?
Corrupted Songflower|174594|48929|`.go obj 48929`|Instant Despawn?
Corrupted Songflower|174595|48955|`.go obj 48955`|Instant Despawn?
Corrupted Songflower|174596|48851|`.go obj 48851`|Instant Despawn?
Corrupted Songflower|174598|48952|`.go obj 48952`|Instant Despawn?
Corrupted Songflower|174712|48942|`.go obj 48942`|Instant Despawn?
Corrupted Songflower|174713|48957|`.go obj 48957`|Instant Despawn?
Corrupted Whipper Root|164888|48844|`.go obj 48844`|After teleport
Corrupted Whipper Root|173284|48935|`.go obj 48935`|After teleport???
Corrupted Whipper Root|174605|48845|`.go obj 48845`|After teleport
Corrupted Whipper Root|174606|48915|`.go obj 48915`|After teleport
Corrupted Whipper Root|174607|48846|`.go obj 48846`|After teleport
Corrupted Whipper Root|174686|48843|`.go obj 48843`|After teleport
Corrupted Windblossom|164887|48928|`.go obj 48928`|Nothing
Corrupted Windblossom|173327|48856|`.go obj 48856`|After Teleport
Corrupted Windblossom|174599|48858|`.go obj 48858`|Nothing
Corrupted Windblossom|174600|48854|`.go obj 48854`|After moving
Corrupted Windblossom|174601|48857|`.go obj 48857`|Nothing (was in combat)
Corrupted Windblossom|174602|48914|`.go obj 48914`|Nothing
Corrupted Windblossom|174603|48855|`.go obj 48855`|Nothing
Corrupted Windblossom|174604|48951|`.go obj 48951`|After moving
Corrupted Windblossom|174708|48853|`.go obj 48853`|Nothing
Corrupted Windblossom|174709|48936|`.go obj 48936`|Nothing
