### ISSUE TITLE
Core/Misc: Creature Equipment

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#687]
**Description**: Creature Equipment

**Current behaviour**: Some creatures do not load their equipment.

**Expected behaviour**: Load their equipment correctly.

**Steps to reproduce the problem**:

1. .tele thefrozenhalls
2. Look at **Ebon Blade Commander**.
3. 

**Branch(es)**: Master

**AC hash/commit**:  612e996209ef+

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by STARRHELD** [comment]
Do you mean the Ebon Blade Commander (37967)?

**Comment by ShinDarth** [comment]
Please read [this](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue) and open a proper report.

**Comment by STARRHELD** [comment]
Like @ShinDarth says, please refer to the guidelines in the future when opening a ticket. @Mitradis

**Comment by Yehonal** [comment]
Have you read issue instructions? This issue does not follow our
guidelines. We cannot fix wrong issues

Il 17 Ott 2017 16:41, "Kevin Starrheld" <notifications@github.com> ha
scritto:
