### ISSUE TITLE
[Arathi Highlands] [Stormgarde Keep] Syndicate Conjuror continues casting "Bright Campfire" when attacked

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#6888]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: [chromiecraft/issues/#1142](https://github.com/chromiecraft/chromiecraft/issues/1142)

##### CURRENT BEHAVIOUR:

The Caster Mobs "Syndicate Conjurer" cast randomly "Camp Fire" when in Idle Mode.
They dont stop/cancle that when getting attacked.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Normal behaviour would be cancling the Camp Fire cast and start Attacking/Casting the Attacker.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go Stormgarde Keep
2. Wait near a Stormgarde Conjurer until he Casts "Camp Fire"
3. See that he doesnt recognize that he is getting attacked and dont cancle the Cast.
4. His Minion (Void Walker) is functioning well and will attack the Attacker

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed on local AC (458469ec01f1+).
Okay, now I can confirm this issue. I waited pretty long for him to cast the "Bright Campfire" and when I attacked him, he first finished casting the "Bright Campfire" (10 s cast), before he attacked me. The cast was not interrupted by my attack. He should cancel the cast and attack me right away:

Test 1: https://user-images.githubusercontent.com/68868567/125190109-c6baa280-e23b-11eb-8baf-8eaf91a47295.mp4

Test 2: https://user-images.githubusercontent.com/68868567/125190486-b1467800-e23d-11eb-90fe-51546aff8772.mp4

**Comment by Efymer** [comment]
But should a Syndicate Conjuror be casting a campfire in the first place? 😮
