### ISSUE TITLE
 undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#6889]
### Current Behaviour

There are some weird issues while recompiling with Dashboard.
It was working fine, until i changed to clang 11.

For some unknown reason, during recompile, it wasn't able to find scripts in filesystems, even tho it's included in Updater.cpp

```
 undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)'
 ```

Except pastebin link bellow, i'm not sure what else to provide.

https://pastebin.com/df2r33ey

### Expected Blizzlike Behaviour

Compile / Recompile should work.

### Steps to reproduce the problem

1. Update your clang to 11 - Debian 10.
2. Try to compile / recompile trough Bash Dashboard.

### AC rev. hash/commit

AzerothCore revision: 2e8a7498d747+ 2021-07-10 17:18:23 +0200 (master branch)

### Operating system

Debian 10 x64

### Custom changes or Modules

No modules - Removed them.
Tried with clean build as well.

**Comment by FrancescoBorzi** [comment]
@Viste @UltraNix any clue about this?

**Comment by Krejza9** [comment]
this is boost problem
You must start compiling boost libraries first.

**Comment by Kitzunu** [comment]
Why would it be an issue with Boost? We dont use boost::filesystem, we use std::filesystem

**Comment by iraizo** [comment]
This is an issue because of the standard library from your system, its outdated and does not have the C++17 filesystem headers

**Comment by Viste** [comment]
`ldd --version`

**Comment by FrancescoBorzi** [comment]
Thanks @Viste 

@Knindzagxg installed gcc-10 and that apparently solved the issue for him. I guess we can close this

**Comment by iraizo** [comment]
> Thanks @Viste
> 
> @Knindzagxg installed gcc-10 and that apparently solved the issue for him. I guess we can close this

Yep the gcc package automatically depends on the standard lib that also includes those.

**Comment by necropola** [comment]
Or just just add one line to fix the build on debian instead of installing an entire package which isn't even in debian stable:
``` diff
diff --git a/src/common/CMakeLists.txt b/src/common/CMakeLists.txt
index 7a2997089..2db021ce5 100644
--- a/src/common/CMakeLists.txt
+++ b/src/common/CMakeLists.txt
@@ -62,6 +62,7 @@ target_link_libraries(common
     openssl
     threads
     jemalloc
+    stdc++fs
     fmt)

 set_target_properties(common
```

**Comment by FrancescoBorzi** [comment]
> Or just just add one line to fix the build on debian instead of installing an entire package which isn't even in debian stable (nor in backports):
> 
> ```diff
> diff --git a/src/common/CMakeLists.txt b/src/common/CMakeLists.txt
> index 7a2997089..2db021ce5 100644
> --- a/src/common/CMakeLists.txt
> +++ b/src/common/CMakeLists.txt
> @@ -62,6 +62,7 @@ target_link_libraries(common
>      openssl
>      threads
>      jemalloc
> +    stdc++fs
>      fmt)
> 
>  set_target_properties(common
> ```
> 
> Since `gcc-10` is not even in `buster-backports` you would need to install it from `unstable (sid)` which is something you should avoid like the plague on debian. See https://wiki.debian.org/DontBreakDebian
> 
> Honestly, **ditch debian and install ArchLinux instead** is a more sensible suggestion than to encourage users to break their stable debian system.
> 
> Maybe the following helps to fix the build system:
> 
> * https://stackoverflow.com/questions/58545562/what-is-the-correct-way-to-link-c17-filesystem-with-cmake
> * https://gitlab.kitware.com/cmake/cmake/-/issues/17834
> * https://github.com/lethal-guitar/RigelEngine/blob/master/cmake/Modules/FindFilesystem.cmake
>   and in particular
> * [lethal-guitar/RigelEngine@cc9ad05#diff-69184b861b92077b0ba169875df97f53c172a40e4de8a495b3e960a6564e478d](https://github.com/lethal-guitar/RigelEngine/commit/cc9ad058139ff213f4fce4deb92c94b7e90755b1#diff-69184b861b92077b0ba169875df97f53c172a40e4de8a495b3e960a6564e478d)

what about merging that to master? can you open a PR with it?
