### ISSUE TITLE
new crash

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6892]
### Current Behaviour

apply https://github.com/azerothcore/azerothcore-wotlk/pull/6805

It crashed after 75 hours of run

and then new crash log

https://gist.github.com/mpfans/61b177c8a1e1882bb25f80ac70366c1f

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

+ 

https://github.com/azerothcore/azerothcore-wotlk/pull/6805

### Operating system

ubuntu 20.04

**Comment by FrancescoBorzi** [comment]
@UltraNix  can you please have a look at this ?

**Comment by UltraNix** [comment]
Still some problems with map and teleport. Something fucked up recently.

**Comment by FrancescoBorzi** [comment]
> Something fucked up recently with pets/minions.

@Kitzunu @Winfidonarleyan were there recent changes in that area?

**Comment by mpfans** [comment]
new crash now
https://gist.github.com/mpfans/ff6eafa1fc655d1f1f88b92dee5bc4a2

**Comment by Kitzunu** [comment]
Still valid?

**Comment by mpfans** [comment]
I'm not sure, but I suggest close
