### ISSUE TITLE
[Quest] Candy Bucket - Hallow's End 

### ISSUE THREAD

**Issue by dd667** [azerothcore/azerothcore-wotlk#690]
**Description**: Server crashes after few minutes. Pumpkin quest might be the issue (hallow's end event) as it crashes when you open and loot goodie bag (**Handful of Candy (37586)**  from pumpkin quest (**Candy Bucket**).
DB is up to date ( AzerothCore rev. d0af1c812bf4 2017-10-17 01:37:03 +0200 (master branch) (Win64, Release) )

**Current behaviour**: Core crash when looting items. Producing error:

```
2017-10-18 13:09:59 AzerothCore rev. d0af1c812bf4 2017-10-17 01:37:03 +0200 (master branch) (Win64, Release) (worldserver-daemon) ready...
2017-10-18 13:10:59 Average update time diff: 10. Players online: 0.
2017-10-18 13:11:59 Average update time diff: 11. Players online: 0.
2017-10-18 13:12:59 Average update time diff: 10. Players online: 1.
2017-10-18 13:13:14 ERROR: Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
```

**Expected behaviour**: Do not crash?

**Steps to reproduce the problem**:

1. Start server, tele to a place with hollow's end event in progress ( Goldshire and Stormwind in my case)
2. Complete the pumpkin quest and receive goodie bag reward.
3. Open your bags and open the goodie bag, as soon as you start looting items, the core crashes with error listed above.

**Branch(es)**:  master

**AC hash/commit**:  d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Operating system**:  Win7

**Modules**:  random-enchants

**Other Customizations**: ----

**Comment by sucofog** [comment]
You're probably missing updates, no problem here, NOT confirmed

**Comment by dd667** [comment]
It is a fresh DB, updated to the latest SQL update on github. Don't know what more I can do...

**Comment by STARRHELD** [comment]
I have tested both as Alliance and Horde, I cannot reproduce this crash.

**Comment by STARRHELD** [comment]
I'm on Windows production-wise.
Currently
