### ISSUE TITLE
Character Statistics - Average Gold Earned Per Day Incorrect

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6901]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1168

In the statistics tab, the average gold earned per day does not scale with time.

Picture from Chromiecraft:
![image](https://user-images.githubusercontent.com/82000605/125200258-93433c80-e26a-11eb-9018-0f5438bda305.png)

@jamadaha adds:
The same thing occurs on my character. (Unedited Chromiecraft instance on active server)
![image](https://user-images.githubusercontent.com/53914190/125202542-5419e900-e274-11eb-8d28-e78926a73e94.png)

Tester: confirmed, same issue on various characters I checked.

![WoWScrnShot_071221_222124](https://user-images.githubusercontent.com/81782124/125290536-91a77080-e35f-11eb-9247-4168bb98773b.jpg)
![WoWScrnShot_071221_221646](https://user-images.githubusercontent.com/81782124/125290539-92d89d80-e35f-11eb-9608-6f33824ba3c3.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Average gold earned per day should be total gold aquired divided by the number of days since your character was created.

##### SOURCE:

![image](https://user-images.githubusercontent.com/82000605/125200234-6c850600-e26a-11eb-8159-07d7f5cb2973.png)
Picture from Retail

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have a character older than 1 day.
2. View statistics -> Wealth.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by heyitsbench** [comment]
This issue is due to the achievement flag `ACHIEVEMENT_FLAG_AVERAGE` not being implemented at all. It would need to grab the creation date of the character from the characters table/DB, have the criteria divided by the days since that date (since it's stored in timestamp) and send it to the client that way. The criteria (I don't think) can't be stored in the DB, since according to the Achievement.DBC, this particular statistic shares its criteria with the total gold earned statistic as well.

**Comment by heyitsbench** [comment]
Worth pointing out, this issue also applies to the statistics [Average daily quests completed per day](https://www.wowhead.com/wotlk/achievement=759) and [Average quests completed per day](https://www.wowhead.com/wotlk/achievement=95).

**Comment by ZhengPeiRu21** [comment]
This will be fixed in https://github.com/azerothcore/azerothcore-wotlk/pull/12255 once all details are resolved.
