### ISSUE TITLE
Core/Gossip: Showing Greetings $N when gossip is not available

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#6902]
### Current Behaviour

Celebras the Redeemed (ID 13716) "Greetings $N" for dialogues.

![WoWScrnShot_071221_120350](https://user-images.githubusercontent.com/61194190/125307309-dca59180-e327-11eb-8a8d-ba5c8af48e07.jpg)

### Expected Blizzlike Behaviour

https://classic.wowhead.com/npc=13716/celebras-the-redeemed

https://wowpedia.fandom.com/wiki/Celebras

"Greetings, $N" isn't correct for any NPC. You can find his dialogues in these links.

### Source

https://classic.wowhead.com/npc=13716/celebras-the-redeemed

https://wowpedia.fandom.com/wiki/Celebras

"Greetings, $N" isn't correct for any NPC. You can find his dialogues in these links.

### Steps to reproduce the problem

1. Do Maraudon
2. Redeem Celebras
3. Observe 5 dialogue options which say "Greetings"

### AC rev. hash/commit

chromiecraft@7c21d56

### Operating system

Windows 10

### Custom changes or Modules

CFBG/ChromieCraft setup.

**Comment by Kitzunu** [comment]
Maybe you are missing something to see his gossip, I haven't checked the Database though.

But Greetings %N is somehow the standard for gossips that you cannot see due to missing requirements (Why? I don't know, it isn't defined anywhere in the core or DB). And I cannot find how to remove it.
