### ISSUE TITLE
"ColdFlame" Lord Marrowgar Damage Possible Bug

### ISSUE THREAD

**Issue by SoHigh495** [azerothcore/azerothcore-wotlk#6906]
### Current Behaviour

The ColdFlame Spell of marrowgar deals to much damage.

![image](https://user-images.githubusercontent.com/8340034/125347327-15ab2980-e35b-11eb-849f-88a12fb885c1.png)

12568 is the actual damage tick the flame does. 

### Expected Blizzlike Behaviour

https://wotlkdb.com/?spell=69146
https://wotlk.evowow.com/?spell=69146

should deal less damage per second as you can see 

### Steps to reproduce the problem

1.Pull Lord Marrowgar
2.Be stupid and walk trough the cold flame 
3.Take a lot of damage

### Extra Notes

I'll do a boost update to 1.74 after i posted this and will update cmake to 3.19.5 where we use 3.16 atm.

Tested also on Windows: Looks like working as intended.

### AC rev. hash/commit

Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using ACE version: 6.4.5
Using Boost version: 1.71.0
Using MySQL version: 100329
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-77-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/azero/WoWZull-ACore/env/dist/bin/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/azero/WoWZull-ACore/env/dist/bin/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/azero/WoWZull-ACore/env/dist/bin/data/mmaps. Total size: 2196365032 bytes
Using deDE DBC Locale as default. All available DBC locales: deDE, enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_12_01

### Operating system

Ubuntu 20.04

### Custom changes or Modules

Tested without modules
Actual installed:
mod-1v1-arena
mod-account-mounts
mod-ah-bot
mod-autobalance
mod-cfbg
mod-eluna-lua-engine
mod-emblem-transfer
mod-learn-spells
mod-npc-codebox
mod-premium
mod-pvp-titles
mod-server-auto-shutdown
mod-solo-lfg
mod-starter-guild
mod-transmog
mod-weekend-xp
mod-world-chat

**Comment by Kitzunu** [comment]
Which mode? Did your character have any armor? Have you tested without modules? My bet is that probably mod-autobalance
could be the reason

**Comment by SoHigh495** [comment]
@Kitzunu tested without modules. on windows tested with and without autobalance. Worked both. Mode: 10 Players NHC

**Comment by SoHigh495** [comment]
Had no Rev line but i always use the latest one.

**Comment by Kitzunu** [comment]
"latest" is not valid
![image](https://user-images.githubusercontent.com/24550914/125352038-18108200-e361-11eb-84b4-2297069f1082.png)

**Comment by Kitzunu** [comment]
But this issue is only on Ubuntu?

**Comment by SoHigh495** [comment]
AzerothCore rev. 915b2d05303a 2021-07-12 16:47:37 +0200 (main branch) (Unix, Release, Static)

**Comment by SoHigh495** [comment]
this issue was for me on Debian 10 and Ubuntu 20.04
i only tested windows and there everything worked well.

**Comment by SoHigh495** [comment]
testes again with autobalance removed! It was autobalance and i dont know why. as it only should downscale and not upscale things
