### ISSUE TITLE
NPC Rousch has no script

### ISSUE THREAD

**Issue by eTzmNcbkrng** [azerothcore/azerothcore-wotlk#6912]
### Current Behaviour

NPC [Rousch ](https://www.wowhead.com/npc=16090) has no script associated with him, he simply stands looking at the [In Loving Memory](https://wowpedia.fandom.com/wiki/In_Loving_Memory) monument

### Expected Blizzlike Behaviour

Every 30 seconds Rousch should do the following:
`/kneel` for 20 seconds.
Stand up.
Wait 1-3 seconds - This is speculative, in some videos he salutes immediately, some he waits a few seconds
`/salute`

### Source

https://youtu.be/4lmNUi4OePI
https://youtu.be/KrwEFze-Y4g

### Steps to reproduce the problem

`.go cr rousch`
Observe, Rousch does not move, he simply stands in place.

### AC rev. hash/commit

Witnessed on ChromieCraft:
AzerothCore rev. 7c21d567d591 2021-07-11 11:39:13 +0200 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by FrancescoBorzi** [comment]
@eTzmNcbkrng don't forget to add the project as well :)

**Comment by Nefertumm** [comment]
Closed by b7665c45c6d9df464e24e5e9226a88c2f3bcb6f1
