### ISSUE TITLE
[Quest] Slagtree's Lost Tools should have multiple spawn points. Not just one.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6915]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1175

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Slagtree's Lost Tools (46420) for the Quest [Vilebranch Hooligans] (7839) should have multiple spawn points, not just one.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should have 5 different spawn points.
53.3, 38.8
57.5, 52.6
66.4, 44.7
71.0, 48.6
72.6, 53.0

##### SOURCE:

https://tbc.wowhead.com/item=19033/slagtrees-lost-tools#comments
Comments from wowhead for classic realms.

https://www.wowhead.com/object=179908/slagtrees-lost-tools#comments
Comment from 2009 for patch 3.2 where the location still differs from the single spawn on AzerothCore.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Add Quest (7839) to Quest Log
2. Go to object or coordinates.
46420 (Entry: 179908) - [Slagtree's Lost Tools X:374.858002 Y:-3784.889893 Z:169.835007 MapId:0] 
3. Confirm this is the single spawn.

Alternative:
1. Check Database table gameobject
2. filter by objectid 46420
3. Count out 1 single spawn, not 5.

##### EXTRA NOTES:

46420 (Entry: 179908) - [Slagtree's Lost Tools X:374.858002 Y:-3784.889893 Z:169.835007 MapId:0] 
https://www.wowhead.com/object=179908/slagtrees-lost-tools#comments
https://tbc.wowhead.com/item=19033/slagtrees-lost-tools#comments

https://wowgaming.altervista.org/aowow/?quest=7839

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 05bbf4a8589c) :

![WoWScrnShot_071321_102504](https://user-images.githubusercontent.com/82579073/125410152-49229e00-e3c5-11eb-8589-02be201cd988.jpg)
![WoWScrnShot_071321_102528](https://user-images.githubusercontent.com/82579073/125410171-4f187f00-e3c5-11eb-86cc-4f53c8dc0967.jpg)

I tried to take the quest, abandon it and accept it again with several characters and the item always comes out at the same point certainly.

**Comment by Eldarix** [comment]
You mean this ?

![hjkvgiyhi](https://user-images.githubusercontent.com/82579073/125478882-0bfbc8dd-db28-48e4-a1fd-1c0b9c1303a8.PNG)

I thought you meant something else when you told me the other day about the projects, in that case, I will look at it always in detail before doing anything, thanks !!

**Comment by FrancescoBorzi** [comment]
> You mean this ?

yes! :)
