### ISSUE TITLE
Floating herbs (summary)

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6918]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Diverse plants reported from Chromiecraft developing their roots antigravitationally in the middle of the air.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Herbs should not spawn in the air. 

##### SOURCE:

Virtual physics. 

##### STEPS TO REPRODUCE THE PROBLEM:

.go object (GUID provided in the reports)

##### EXTRA NOTES:

-

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

AzerothCore & ChromieCraft

**Comment by Eldarix** [comment]
https://github.com/chromiecraft/chromiecraft/issues/1180

**Comment by Eldarix** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6367

**Comment by Eldarix** [comment]
Following the example of other general threads that you have created, and seeing that there was no specific one for the topic of plant levitation, I leave it here already prepared ;)

Take care and enjoy folks.

**Comment by Azcobu** [comment]
Closing as the two linked issues have been resolved.
