### ISSUE TITLE
Unrelenting assault on target

### ISSUE THREAD

**Issue by Narcof** [azerothcore/azerothcore-wotlk#692]
**Description:** can't view unrelenting assault on target.
**Current behaviour:** When a warrior with "Taste of Blood" hits a target during a cast, with overpower, he can't see the debuff "Unrelenting assault"  on target that he have hit
**Expected behaviour:** When a warrior with "Taste of Blood" hits a target during a cast, with overpower, he should see the debuff on target that he have hit
**Steps to reproduce the problem**:
1. use a warrior
2. let proc Taste of Blood
3. use Overpower on target during a cast
4. see "unrelenting assault" debuff on target
**Branch(es)**: Master
**AC hash/commit**: d0af1c812bf4ea15204cad37b39ff27ff6bae339
**Operating system**: Linux

![hino](https://user-images.githubusercontent.com/32717748/31789737-638d75d8-b513-11e7-8afa-90a7cc2c0e1b.png)

![spit](https://user-images.githubusercontent.com/32717748/31789740-659b8932-b513-11e7-90ee-83e41ddf9478.PNG)

**Comment by Yehonal** [comment]
You can't see it as you said, it means that the buff has not been applied or just a visual issue?

I would test it on staging server

**Comment by lineagedr** [comment]
Works for me. Disable all addons try again. @Narcof

**Comment by Narcof** [comment]
@lineagedr i've tested this problem with @Yehonal . He will fix that bug

**Comment by Yehonal** [comment]
Tested on our official staging server with @Narcof 

![image](https://user-images.githubusercontent.com/147092/31830661-34a9f1ca-b5c1-11e7-9cb3-39bebf55f547.png)
![image](https://user-images.githubusercontent.com/147092/31830684-40a7b0ca-b5c1-11e7-8968-94827609cba6.png)

As you can see in screens the warrior sees the debuff "smaller" than other, i think that the server uses a wrong caster, maybe the target itself.

Must be checked.

**Comment by Yehonal** [comment]
Spells involved:

https://wowgaming.altervista.org/aowow/?spell=46860

https://wowgaming.altervista.org/aowow/?spell=56638

https://wowgaming.altervista.org/aowow/?spell=7384

**Comment by Yehonal** [comment]
i think i've fixed, testing...

**Comment by Narcof** [comment]
now it works

**Comment by Nefertumm** [comment]
If it works, this can be closed :)
