### ISSUE TITLE
Tree of life / Moonkin Form - Snare effects

### ISSUE THREAD

**Issue by Narcof** [azerothcore/azerothcore-wotlk#693]
**Description**:Druid can't remove snare effect if he switch Tree of life form into Tree of life again, with this macro: /cast !TreeofLife . This happens with Moonkin form too
**Current behaviour**: While a druid switch from Tree of life into Tree of life form again,with /cast !TreeofLife he can't remove all snare effect

**Expected behaviour**:  While a druid switch from Tree of life into Tree of life form again,with /cast !TreeofLife , he should remove all snare effect,

**Steps to reproduce the problem**:

1. Use a druid in Tree of Life 
2. let someone snare you
3. Switch from Tree of life in Tree of life again with this macro: /cast !TreeofLife
4. Show your debuff 

**Branch(es)**: Master

**AC hash/commit**:  d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Operating system**:  Linux

**Comment by Yehonal** [comment]
Confirmed

By clicking normally twice on spell icon instead it works. 
The same macro works for other forms except Tree and Moonkin.

It's a common druid macro called "Powershift"

**Comment by lineagedr** [comment]
SpellAuraEffects.cpp

void AuraEffect::HandleAuraModShapeshift(AuraApplication const* aurApp, uint8 mode, bool apply) const
Line 1772: if (!(mode & AURA_EFFECT_HANDLE_REAL))

Change to: if (!(mode & AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK))

Correct me if this is not the right way to fix it.

**Comment by sucofog** [comment]
You have tested @lineagedr ?

**Comment by lineagedr** [comment]
@sucofog Yes.

**Comment by sucofog** [comment]
And it solved the issue @lineagedr ?

**Comment by lineagedr** [comment]
@sucofog Yes.

**Comment by Yehonal** [comment]
i've updated this issue with a new label "feedback-patchfix" 

in this way we can keep note about issue with a possible fix inside. However lineagedr, could you open a PR with this small change please? 

This commit must have your name..

**Comment by lineagedr** [comment]
@Yehonal Can you open the PR, I don't have AzerothCore.
