### ISSUE TITLE
 Hack & Slash Rogue Talent not proccing on abilities

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#6935]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/1169

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Hack & Slash the Rogue Talent is currently only proccing from pure Autoattacks not from Sinister Strike or other instant hitting rogue Abilities.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Hack & Slash  should be proccing from other Instant Cast Rogue abilites such as Sinister Strike and Eviscerate since theyre also using the weapon.
below is a 40 minute example of me afk hitting a Targetdummy, showing the right Procc chance!
Also one Screenshot of me using Sinister Strike and Slice and Dice for 15 Minutes, showing a greatly decreased proccrate(Can also reprodruce sample if needet).

##### SOURCE:

https://wowwiki-archive.fandom.com/wiki/Hack_and_Slash
![WoWScrnShot_071121_163030](https://user-images.githubusercontent.com/87269487/125200588-144f0380-e26c-11eb-8b92-adb333b7748c.jpg)
![WoWScrnShot_071121_171102](https://user-images.githubusercontent.com/87269487/125200597-1a44e480-e26c-11eb-9875-00dfc6772fd6.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1.  start auto attacking Targetdummy
2.  keep document of procc rates
3. 
4.

##### EXTRA NOTES:

can start to document all my Dungeon runs from here on and keep screenshots of Proccrates to provide further information.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@temperrr thanks for triaging this, don't forget to apply the right content-label. In this case it's `[ChromieCraft Generic]`

**Comment by UltraNix** [comment]
Hmm. Sinister Strike and Eviscirate starts melee combat so there might be a proc chain: Sinister Strike -> proc extra attack -> melee attack started by sinister stike -> proc extra attack. So we got 1 Sinister strike, 1 melee and 2 extra attacks - this is okay @temperrr ?
