### ISSUE TITLE
[Placeholder] Dupe vulnerability bug [$55]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#6939]
Apparently, there is a dupe vulnerability affecting AC, I'm opening this as a placeholder to place a bounty on it.

**Comment by jasonmbrown** [comment]
I don't suppose you have any details or idea where it might be located in the code?

**Comment by iraizo** [comment]
> I don't suppose you have any details or idea where it might be located in the code?

There is a literal PR linked to this issue
