### ISSUE TITLE
dismount at storm peaks

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#694]
Description: when fly around x 40.8 y 68.5 at storm peaks, the mount disappears and fall down. If player dead and release spirit, he resurrect at cemetery at sentinel hill in westland ( only for alliance player)

Current behaviour: described above

Expected behaviour: mount must not disappears

Steps to reproduce the problem:
 1-fly around x 40.8 y 68.5 at storm peaks
 2-release spirt after deadly fall

Branch(es): Master 
AC hash/commit:  d0af1c812bf4ea15204cad37b39ff27ff6bae339
Operating system:  Linux
--

**Comment by ShinDarth** [comment]
please edit your issue and add the commit hash

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by comix1988** [comment]
i added the information

**Comment by lineagedr** [comment]
Can you add more specific coordinates?

like .go xyz

**Comment by comix1988** [comment]
.go 6938x -1054y 889z

**Comment by Yehonal** [comment]
The correct command should be: 

.go xyz  6938 -1054 889 571

where 571 is the map

**Comment by comix1988** [comment]
I have tested again today and the problem is solved.

BRANCH(ES):
staging

AC HASH/COMMIT:
commit 987095e

OPERATING SYSTEM:
linux

**Comment by FrancescoBorzi** [comment]
thank you @comix1988
