### ISSUE TITLE
[QUEST] Going Bearback

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#695]
**Description**: This quest is the 13th of the son of hodir's chain in this quest, you mount on a bear (veicle) and hit with the bomb of the veicle giant and wolf 

**Current behaviour**: 
1) The aura present in the Brunnhildar village (55012) should last for all this quest as it gets off approaching Brijanna this causes the nearby bears to become enemies and attack throughout the quest.
2) The path is different from the official one
3) Bears supporting the quest are many more (I think)
4) The mobs to hit in quest are friends (green) and not enemies (red)
Quest is NOT POSSIBLE

**Expected behaviour**: Mount on the bear and go to the map in front of at hit giant and wolf

**Steps to reproduce the problem**:

1. Complete chain quest of sons until going bearback
2. Mount bear
3. Try to hit mob of the quest

Quest: http://www.wowhead.com/quest=12851/going-bearback
Video: https://www.youtube.com/watch?v=GmOQtOsfXEk&feature=youtu.be

**Comment by Franklampardst** [comment]
confirmed!

**Comment by FrancescoBorzi** [comment]
@Franklampardst thanks for the confirmation.

Anyone that wants to have a look at this? On TC there are only CLOSED issues about this quest, so there is a good chance that it's working there and we can import it:

https://github.com/TrinityCore/TrinityCore/issues?q=is%3Aissue+Going+Bearback+is%3Aclosed

@Viste @poszer @Winfidonarleyan @Stoabrogga @xDevICCI

**Comment by Franklampardst** [comment]
@FrancescoBorzi i can't find any issue like this from trinitycore but i tested a thing for this quest if we change faction of npcs to 2121 can use spell for them but when server restart all settings restore and npc faction gets to 35

**Comment by Franklampardst** [comment]
there is no idea to fix this problem?!

**Comment by Franklampardst** [comment]
@FrancescoBorzi Test with latest db , i thing this guy change the npc flags but he don't know when do server restart restore this bug
![wowscrnshot_013119_230658](https://user-images.githubusercontent.com/22575447/52080596-6c6a8180-25ad-11e9-9feb-972f87476507.jpg)
![wowscrnshot_013119_230703](https://user-images.githubusercontent.com/22575447/52080602-72606280-25ad-11e9-9170-9b5cf4bc7b6b.jpg)

**Comment by comix1988** [comment]
I don't change any flags.
I have only completed every quest on quest-line.

**Comment by Viste** [comment]
@comix1988 dont lie. If you do all quest in chain quest by quest npc got correct flag... @Franklampardst

**Comment by poszer** [comment]
Fixed in https://github.com/azerothcore/azerothcore-wotlk/commit/337820db0fb4207ee07b6dae4e2712a39b714d9e
