### ISSUE TITLE
Some Chinese translation errors

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#6952]
### Current Behaviour

Some Chinese translation errors

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

341d65c1db0d99c0603e04edbe2fc37314cf20dc

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
> -- fixed Chinese translation errors
> UPDATE `item_template_locale` SET `Name` = '凶残角斗士的恐怖板甲头盔' ,`Description` = '' WHERE `ID` = '40817' AND `locale` = 'zhCN';
> UPDATE `item_template_locale` SET `Name` = '完美辉光茶晶石' , `Description` = '对应红色或黄色插槽。' WHERE `ID` = '41494' AND `locale` = 'zhCN'; 
> 
> -- add `Pillar of Diamond`(id 2842) Chinese translation
> DELETE from `gameobject_template_locale` where `entry` = 2842 AND `locale` = 'zhCN';
> INSERT INTO `gameobject_template_locale` (`entry`, `locale`, `name`, `castBarCaption`, `VerifiedBuild`) VALUES ('2842', 'zhCN', '钻石石柱', '', '18019'); 
> 
> -- add `Pillar of Opal`(id 2848) Chinese translation
> DELETE from `gameobject_template_locale` where `entry` = 2848 AND `locale` = 'zhCN';
> INSERT INTO `gameobject_template_locale` (`entry`, `locale`, `name`, `castBarCaption`, `VerifiedBuild`) VALUES ('2848', 'zhCN', '玛瑙石柱', '', '18019'); 
> 
> -- add `Pillar of Amethyst`(id 2858) Chinese translation
> DELETE from `gameobject_template_locale` where `entry` = 2848 AND `locale` = 'zhCN';
> INSERT INTO `gameobject_template_locale` (`entry`, `locale`, `name`, `castBarCaption`, `VerifiedBuild`) VALUES ('2858', 'zhCN', '紫水晶石柱', '', '18019');

**Comment by mpfans** [comment]
@FrancescoBorzi  Please help make a PR

**Comment by iraizo** [comment]
> @FrancescoBorzi Please help make a PR

Whats the issue here?

**Comment by mpfans** [comment]
> > @FrancescoBorzi Please help make a PR
> 
> Whats the issue here?

I found some mistranslations and then gave the fix SQL

**Comment by iraizo** [comment]
> > > @FrancescoBorzi Please help make a PR
> > 
> > 
> > Whats the issue here?
> 
> I found some mistranslations and then gave the fix SQL

Alright if you want to do a PR please read the wiki page on it https://www.azerothcore.org/wiki/how-to-create-a-pr

**Comment by FrancescoBorzi** [comment]
> Alright if you want to do a PR please read the wiki page on it https://www.azerothcore.org/wiki/how-to-create-a-pr

that's indeed what we normally require but, as @mpfans is busy enough testing PRs with hundreds of players online, I'll open it for him :)
