### ISSUE TITLE
Floating "Large Termite Mound" (45874, entry 177464)

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#6954]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1202

That "Large Termite Mound" (45874, entry 177464) is floating.
![WoWScrnShot_071421_224555](https://user-images.githubusercontent.com/22718174/125720137-1bc9cb85-7e67-4a7c-a7dd-00fb62c2f24a.jpg)

### Expected Blizzlike Behaviour

Put it into the ground.

### Steps to reproduce the problem

Find it, notice it's superiority over you by levitating above the ground.

### Extra Notes
Note by original commentor:
I HATE TERMITES!

Note by tester:
Tested on b68067004

**Comment by LukasVolgger** [comment]
Your extra notes... haha xD
