### ISSUE TITLE
[Tanaris] Kregg Keelhaul (rare) not using any abilities.

### ISSUE THREAD

**Issue by iraizo** [azerothcore/azerothcore-wotlk#6955]
### What client do you play on?

frFR

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Kregg Keelhaul (DB GUID: 51834) is not using any abilities, auto attacks only.

### Expected Blizzlike Behaviour

Kregg Keelhaul should use his abilities : Leaping Cleave, Slippery Suds, Slippery Suds.

### Source

https://fr.classic.wowhead.com/npc=8203/kregg-keelhaul#abilities
https://wowpedia.fandom.com/wiki/Kregg_Keelhaul#Abilities

### Steps to reproduce the problem

1. Port to DB GUID: 51834
2. Aggro the rare
3. Observe nothing else but auto attacks (from visual & combat log)

https://user-images.githubusercontent.com/82708448/125672395-08c5a7d3-e297-41f4-a5b7-072474b5e23b.mp4

### Extra Notes

Original report https://github.com/chromiecraft/chromiecraft/issues/1197

### AC. Rev Hash/Commit
chromiecraft@7c21d56

**Comment by Kitzunu** [comment]
Add Hash/Commit

**Comment by iraizo** [comment]
> Add Hash/Commit

of https://github.com/chromiecraft/azerothcore-wotlk ?

**Comment by Kitzunu** [comment]
or chromie

**Comment by iraizo** [comment]
well what i linked is the fork of azerothcore on chromies org

**Comment by Kitzunu** [comment]
Yes, should always be in the issue =)

**Comment by iraizo** [comment]
Now that i know i will add it! ^^
