### ISSUE TITLE
 [Rogue] Kick Cannot Interrupt Curse of Thule

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6956]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1201

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Kick (https://wowgaming.altervista.org/aowow/?spell=1766) cannot interrupt Curse of Thule (https://wowgaming.altervista.org/aowow/?spell=3237). 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Kick should be able to interrupt Curse of Thule.

##### SOURCE:

 https://wowwiki-archive.fandom.com/wiki/Vanish

Kick ability mechanics: 
https://wowgaming.altervista.org/aowow/?spell=1766
https://wowwiki-archive.fandom.com/wiki/Kick
Basically, "it **interrupts** spellcasting." 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a rogue that has Kick.
2. Go to Fenris Isle (https://wowpedia.fandom.com/wiki/Fenris_Isle).
3. Fight some Rot Hide Brutes (https://wowgaming.altervista.org/aowow/?npc=1939).
4. Kick them while they cast Curse of Thule.

##### EXTRA NOTES:

https://user-images.githubusercontent.com/25198252/125722464-6a3e8f23-9347-4571-abe0-81f5b4b02c8f.mp4

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/7c21d567d59153b37978756a5bf02daf6998e665

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 05bbf4a) :

![WoWScrnShot_071521_113557](https://user-images.githubusercontent.com/82579073/125758126-c5c8729e-6f7a-416b-84a2-55c46338e7cd.jpg)

Since the cast bar of the ability doesn't have the typical shield symbol indicating that it cannot be interrupted, I assume that it's certainly a bug.

**Comment by lineagedr** [comment]
It should be intended? the spell 
`[Curse of Thule]`

has `SPELL_PREVENTION_TYPE_SILENCE`

**Comment by Kitzunu** [comment]
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
