### ISSUE TITLE
Shattered Sun Marksman Quel'Danas

### ISSUE THREAD

**Issue by Crypticaz** [azerothcore/azerothcore-wotlk#696]
![sun marksman server](https://user-images.githubusercontent.com/25990459/31854010-1898f3ea-b658-11e7-9845-e9a84a4e8310.png) Server Version

**Description**: There are Shattered Sun Marksman in Quel'Thalas that are using the wrong animation for the bow and missing their correct equipment.
**Current behaviour**: Doesn't have the correct equipment id/gear and is shooting like the npc is using a gun, but in-fact is using a bow.
**Expected behaviour**: Supposed to have the correct equipment id/gear and should be shooting with bow animation. Here is a link to wowhead. http://www.wowhead.com/npc=24938/shattered-sun-marksman

**Steps to reproduce the problem**:

1. Login
2. Goto Quel'Thalas `.go creature 24938`
3. Find Shattered Sun Marksman and look at their animation/gear

**Branch(es)**: Master(es)

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Operating system**:  Windows 10

**Modules**:  Solorcraft, npcenchanter, transmog, congratsonlevel, moneyforkills, randomenchants

**Other Customizations**: Added in cata->mop->wod models, items etc. With patches for it.

![sun marksman](https://user-images.githubusercontent.com/25990459/31854009-1195471a-b658-11e7-8b46-76dcf8e997db.png) Retail Version

**Comment by Crypticaz** [comment]
Top Picture is the server. Last one is retail.

**Comment by ShinDarth** [comment]
does it refer to the latest retail version or the original 3.3.5 retail version?

**Comment by Crypticaz** [comment]
Latest retail verison, but I assume it should still be bow shooting animation

**Comment by BarbzYHOOL** [comment]
First of all, the issue was not well documented, so I checked 5 creatures and none looked like the first screenshot. They were all missing their bow.

Then I tested the PR from @Pondaveia and it added the bows. So I don't know if issue is closed but it's already a good improvement

**Comment by BarbzYHOOL** [comment]
I add this to original issue `.go creature 24938`
