### ISSUE TITLE
FAQ "Where are the etc and logs folders of my server?" points to incorrect directory

### ISSUE THREAD

**Issue by suprsokr** [azerothcore/azerothcore-wotlk#6961]
**Describe the bug**
The current FAQ states:

> Where are the etc and logs folders of my server?
> By default they are located in env/docker/authserver/ and env/docker/worldserver/.

However, on my fresh Docker for Windows & azerothcore-wotlk install (f8abece0d56964b0109ccee6dac31a911b39dfff), they are located at `env/docker/etc` and `env/docker/logs`, not nested inside `/authserver` or `/worldserver`.

**To reproduce**
1. Follow installation instructions at https://www.azerothcore.org/wiki/Install-with-Docker up to Step 3
2. Navigate to `env/docker/`

You will see your logs and etc folder.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Kitzunu** [comment]
Is this still an issue?

**Comment by temperrr** [comment]
The wiki has been updated some time ago to reflect this.
