### ISSUE TITLE
Venomhide Eggs Quest not bound to prerequisite Quest

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6962]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1208

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

When you speak to Mor'vek NPC ( https://wowgaming.altervista.org/aowow/?npc=11701 ) he has the following quest available:
- Toxic Tolerance (https://wowgaming.altervista.org/aowow/?quest=13850) is the 1st quest of then Chain
- Venomhide Eggs (https://wowgaming.altervista.org/aowow/?quest=13887) is the 2nd quest of then Chain

If you accept one of them the other one is not listed as available anymore.
When you complete Venomhide Eggs quest the 3rd quest of the chain (https://wowgaming.altervista.org/aowow/?quest=13906 - They Grow up so Fast) become available.

### Expected Blizzlike Behaviour

The only quest available from Mor'vek NPC should be "toxic tolerance". After its completion the second quest "Venomhide eggs" should become available.
Wowhead comments describe this behavior: https://www.wowhead.com/npc=11701/morvek#comments

### Steps to reproduce the problem

Teleport at coords 71.2, 73.7 to Mor'vek (should be guid 11701) in Un'Goro and speak with him to see the available quests.
Both the 1st and the 2nd quests of the chain are available.

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=11701 ( Mor'vek)
https://wowgaming.altervista.org/aowow/?quest=13850 ( Toxic Tolerance - 1st quest)
https://wowgaming.altervista.org/aowow/?quest=13887 ( Venomhide Eggs - 2nd quest)

AC HASH/COMMIT:

chromiecraft/azerothcore-wotlk@7c21d56

OPERATING SYSTEM:

Ubuntu 20.04

MODULES:

mod-ah-bot
mod-cfbg
mod-chromie-xp
mod-desertion-warnings
mod-duel-reset
mod-eluna-lua-engine
mod-ip-tracker
mod-low-level-arena
mod-multi-client-check
mod-pvp-titles
mod-pvpstats-announcer
mod-queue-list-cache
mod-server-auto-shutdown
lua-CarbonCopy
lua-LevelUpReward
lua-send-and-bind
lua-Zonecheck

OTHER CUSTOMIZATIONS:

None

SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 05bbf4a) :

It certainly has both initially available:

![WoWScrnShot_071521_170931](https://user-images.githubusercontent.com/82579073/125803221-87393df6-6c88-4ff8-8ff8-32074bf5d176.jpg)

But when you complete the third, the first no longer appears:

![WoWScrnShot_071521_171122](https://user-images.githubusercontent.com/82579073/125803571-df2c74d4-46b6-4818-9690-b370ff361e69.jpg)
![WoWScrnShot_071521_171154](https://user-images.githubusercontent.com/82579073/125803657-2a539f96-215a-4183-b4eb-99c031c2969c.jpg)

Both in wowhead and wowgaming the 3 quests of the chain appear in order:

![fvyiu](https://user-images.githubusercontent.com/82579073/125803924-83f0e9d6-cc61-48a7-9cad-961550fbbc27.PNG)
![iyfviyhi](https://user-images.githubusercontent.com/82579073/125803929-162d14d2-6619-4464-9c5f-3806fe2b0c3f.PNG)

**Comment by Mitradis** [comment]
can be close
