### ISSUE TITLE
(BRD/Dungeon) Ambassador Flamelash encounter

### ISSUE THREAD

**Issue by markvetx** [azerothcore/azerothcore-wotlk#6964]
### Current Behaviour

Burning Spirits doesn't chase Ambassador Flamelash during the encounter, they just stay in their initial summon point.

### Expected Blizzlike Behaviour

Burning Spirits must chase the boss, if they are succeed, boss will grant [Burning Spirit] buff.

### Source

https://www.youtube.com/watch?v=VC039Lty50E

### Steps to reproduce the problem

1. `.go c ambassador_flamelash`
2. Pull the boss

### AC rev. hash/commit

05bbf4a8589c

### Operating system

Arch Linux 5.12

### Custom changes or Modules

mod-account-achievements
mod-autobalance
mod-buff-command
mod-solo-lfg
mod-transmog

**Comment by syssneck** [comment]
Here is another Classic video of the encounter: https://youtu.be/QoEwUz7Bdq8?t=953
The respawns of the Burning Spirits are already working on AC, but I'm not sure, if the timing is correct, but it looks okay to me. The Fireguard Destroyer in the video of this issue are not part of the encounter. They somehow pulled them up to the boss^^
So basically make the adds move towards the boss and assist him.
