### ISSUE TITLE
Demons for the hunter epic quest

### ISSUE THREAD

**Issue by pop-pig** [azerothcore/azerothcore-wotlk#6966]
### Current Behaviour

For their epic lvl 60 bow, hunters have to kill 4 demons to complete a quest.
The four demons are:
- Klinfran / Franklin: https://wowgaming.altervista.org/aowow/?npc=14529 / https://wowpedia.fandom.com/wiki/Klinfran_the_Crazed
- Artorius: https://wowgaming.altervista.org/aowow/?npc=14531 / https://wowpedia.fandom.com/wiki/Artorius_the_Doombringer
- Solenor / Nelson: https://wowgaming.altervista.org/aowow/?npc=14536 / https://wowpedia.fandom.com/wiki/Solenor_the_Slayer
- Simone: https://wowgaming.altervista.org/aowow/?npc=14527 / https://wowpedia.fandom.com/wiki/Simone_the_Seductress
The four demons have several issues:
- they are all static ;
- they do not transform when attacked / when a "non aggressive spell" has been casted on them (for instance, Hunter's mark) ;
- they do not have a gossip option.

### Expected Blizzlike Behaviour

The demons should be patrolling in their respective areas.
They should have a dialog option (they can be interracted with in their humanoid form).
They should transform into their demon form when attacked.

### Source

Patrol paths: 
- https://classic.wowhead.com/npc=14529/franklin-the-friendly
- https://classic.wowhead.com/npc=14531/artorius-the-amiable
- https://classic.wowhead.com/npc=14527/simone-the-inconspicuous
- https://classic.wowhead.com/npc=14536/nelson-the-nice

Transformation & dialog option (see the mouse icon when hovered over the demon): https://youtu.be/OCUzUP97UWQ?t=158

### Steps to reproduce the problem

Go see each demon:
".go c id 14259"
".go c id 14531"
".go c id 14527"
".go c id 14536"

### AC rev. hash/commit

AzerothCore rev. 4d6766d6a997+ 2021-07-15 15:52:19 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by vtihomirov** [comment]
Hey guys, I have some source videos that I recorded of the mentioned npc(mainly pathing):
[Artorius](https://youtu.be/UUl8qDWUYnU)
[Simone](https://youtu.be/wi2Krnrx25I)
[Franklin](https://youtu.be/vUIFA5JAeNc)
[Nelson](https://youtu.be/C1NdozH80Yw)

My intention was to work on this issue, but it seems that my desire to get it fixed passed some time ago.
Also I would like to point some other videos of the actual fights that I found useful:
https://www.youtube.com/watch?v=adz-VM7wzo4
https://www.youtube.com/watch?v=CDXJgNWm0nA
https://www.youtube.com/watch?v=OCUzUP97UWQ
https://www.youtube.com/watch?v=whvbpIy36gs
https://www.youtube.com/watch?v=9fR6KhxpGQE
and to pass a notion that the mentioned mobs are also missing fight reset and weakness mechanics.

**Comment by Nefertumm** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/commit/12b195e1165f392fc144535afee11b8c4dec0576
