### ISSUE TITLE
Seduction on Spell Reflection

### ISSUE THREAD

**Issue by Narcof** [azerothcore/azerothcore-wotlk#697]
**Description**: Succubus cast "Seduction" on  warrior with Spell Reflection, the succubus reflect the Seduction spell on it. It shouldn't happen because Succubus isn't a Humanoid

**Current behaviour**: When a succubus cast "seduction" on a warrior with Spell reflection, the succubus reflect this spell on it

**Expected behaviour**: When a succubus cast "seduction" on a warrior with Spell reflection, the seduction spell shouldn't return on Succubus

**Steps to reproduce the problem**:

1. let cast your succubus a seduction on a warrior with spell reflection
2. See the debuff on succubus

**Branch(es)**: Master

**AC hash/commit**:  d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Operating system**:  Linux

![wowscrnshot_100117_215034](https://user-images.githubusercontent.com/32717748/31864021-d388b43e-b756-11e7-92db-9c6de2b883ea.jpg)

**Comment by lineagedr** [comment]
Can you provide proof that it shouldn't return on succubus?

**Comment by Yehonal** [comment]
@lineagedr one proof should be that the spell can only be casted on humanoid, instead the succubus is a demon. But i'm not sure

**Comment by Narcof** [comment]
@lineagedr it's simple, 

1. when a succubus cast "seduction" it stay in cast ( like a channeling spell ). if succubus take seduction it can't continue to cast this spell

2. Seduction can only be casted on humanoid, succubus is a demon

**Comment by lineagedr** [comment]
@Narcof @Yehonal 
Fair point, I have a fix but it's very hacky.

**Comment by Yehonal** [comment]
i'm curious :)

**Comment by lineagedr** [comment]
> if (m_caster->IsPet())
> 		{
> 			CreatureTemplate const* ci = sObjectMgr->GetCreatureTemplate(m_caster->GetEntry());
> 			switch (ci->family)
> 			{
> 				case CREATURE_FAMILY_SUCCUBUS:
> 				{
> 					if (m_spellInfo->SpellIconID != 694) // Soothing Kiss
> 						cancel();
> 				}
> 				break;
> 				return;
> 			}
> 		}

**Comment by lineagedr** [comment]
@Yehonal https://pastebin.com/e66rdHCB add below 

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/game/Spells/Spell.cpp#L2397

**Comment by BarbzYHOOL** [comment]
Is it logic to reflect the spell seduction? for me it's not but if blizzard said so, then...

**Comment by BarbzYHOOL** [comment]
Seduction must only target humanoids, it would solve all issues

**Comment by pak3935** [comment]
any news

**Comment by Pondaveia** [comment]
Can't reproduce this issue, spell reflected and sucubus wasn't charmed.

**Comment by talamortis** [comment]
cant reproduce either.

**Comment by BarbzYHOOL** [comment]
If someone reopens this, plz add the commands to easy test like ".cast xxxxx" etc
