### ISSUE TITLE
Undercity Paladin Trainer uses Alliance language text instead of Horde when Horde Paladins speak to her

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6971]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1212

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Champion Cyssa Dawnrose's main page text is in an Alliance language (Common I think) when viewed by Paladins, making her unable to be understood.
![WoWScrnShot_071521_095350](https://user-images.githubusercontent.com/83389835/125811392-7012ac79-796c-4e59-a2b8-56a4e06a2b88.jpg)
Note DBGUID in screenshot chat

### Expected Blizzlike Behaviour

She is a Horde character, so she should speak Orcish, making the text appear in English (or primary game language) to players.

### Source

Cyssa's text when non-paladins speak to her, as well as Horde paladin trainers in other cities.

### Steps to reproduce the problem

1. Be a Blood-Elf Paladin
2. R-click to talk to the NPC
3. Look at the text

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 42f27af83c4f) :

![WoWScrnShot_071621_061355](https://user-images.githubusercontent.com/82579073/125886296-cbe77fa4-542c-44a3-b9d9-0720f560b793.jpg)

**Comment by Asthalor** [comment]
It seems that shes speaking this line:

![image](https://user-images.githubusercontent.com/87535580/126039460-3d41caf8-625e-4248-9aab-d5a2fc46cbfd.png)

I dont know if thats the correct line, seems very shamanistic,

Looking it up seems to be the line of Farseer Umbrua.

![image](https://user-images.githubusercontent.com/87535580/126039557-dc4cb60b-af02-497c-b3f2-1633cb99413a.png)


The original text should be Leave me, <class>. I must attend to my duties with Ambassador Sunsorrow, dull as they are. 
Source : https://wowpedia.fandom.com/wiki/Champion_Cyssa_Dawnrose

We will have to change the gosspi line for the one mentioned, i will look into it
