### ISSUE TITLE
[Stranglethorn Fishing Extravaganza] Master Angler quest resets if server restart during the event, allowing for multiple winners on the same day

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6973]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1028

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If server restart happens during the Stranglethorn Fishing Extravaganza, after the winner has been selected, another player can deliver 40 Speckled Tastyfish required for Quest:Master Angler and be another winner on the same day, obtaining one of the rewards and achievement.

Despite the rare environment, this may open a window for easy achievement and quest rewards from the Quest:Master Angler. Quest also resets for the previous winner so the same person can get two rewards on the same day if they are 'lucky'.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Server restart should not affect the Quest:Master Angler and reset its completion once the winner is selected for the day.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait till the Stranglethorn Fishing Extravaganza event is up
2. Collect 40 Speckled Tastyfish https://wowgaming.altervista.org/aowow/?item=19807
3. Approach Riggle Bassbait <Fishmaster> https://wowgaming.altervista.org/aowow/?npc=15077 in Booty Bay
4. Wait until someone completes Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
5. Trigger/Wait for server restart while the Stranglethorn Fishing Extravaganza event is still up
6. Log in as fast as possible
7. Try to complete Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
8. Inspect your achievements for Master Angler of Azeroth https://wowgaming.altervista.org/aowow/?achievement=306

##### EXTRA NOTES:
The same issue may be also affecting Kalu'ak Fishing Derby https://wowgaming.altervista.org/aowow/?quest=24803 in Northrend where rewards from the event are even more lucrative.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 42f27af) 

Effectively lets 2 characters get the achievement on the same day after a server reset;

![WoWScrnShot_071621_073401](https://user-images.githubusercontent.com/82579073/125892844-0ed4f7a9-c9cd-41a9-91ae-737b8006b309.jpg)
![WoWScrnShot_071621_073721](https://user-images.githubusercontent.com/82579073/125892875-5b54a155-7514-44cc-b763-152fc6351359.jpg)

The player who made the report has explained it very well, but just in case, looking for info in old forums, they all confirm that being a competition, it makes no sense that more than one player wins it, I consider this extract the most clarifying:

![ruwubww](https://user-images.githubusercontent.com/82579073/125893176-c862cbe4-32c4-4be7-8ae8-0551ad53a21c.PNG)

**Comment by UltraNix** [comment]
The problem here is that every server crash/restart means restarting the event. And the server does not know if it happened because of restart or just the event has begun.

**Comment by schell244** [comment]
Maybe the system from VMangos can be used. They store the completion time of quest Master Angler, and when server restarts the Master Angler quest will only become available if last completion time is longer than a day ago.

https://github.com/vmangos/core/blob/8f2af5dff4c61ec58b118bd15399a5dfd775e83a/src/scripts/world/npcs_special.cpp#L1423

**Comment by schell244** [comment]
I've just noticed that VMangos has a functionallity which is currently not present in Azerothcore:
`void ObjectMgr::SetSavedVariable(uint32 index, uint32 value, bool autoSave)`
https://github.com/vmangos/core/blob/3f3459e05407e46c42ad7e4aa3cece6f30b07ed2/src/game/ObjectMgr.cpp#L569
With this method it's possible to store world varibales in the database. The Master Angler quest state is stored by this. It is also used for counting the items which have been gathered for aq-war effort. Might be useful to port.
