### ISSUE TITLE
[Burning Steppes] Thauris Balgarr (rare) has no "Shoot" ability

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#6979]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

Original report: [chromiecraft/issues/1218](https://github.com/chromiecraft/chromiecraft/issues/1218)

### Current Behaviour

The npc Thauris Balgarr doesn't use his "Shoot" ability.
![WoWScrnShot_071521_170845](https://user-images.githubusercontent.com/22718174/125858328-a1e22a20-a102-436d-bd38-88fd92b1c052.jpg)

### Expected Blizzlike Behaviour

He should use his shooting ability.

### Source

NPC: https://wowgaming.altervista.org/aowow/?npc=8978
His "Shoot" ability: https://wowgaming.altervista.org/aowow/?spell=6660

### Steps to reproduce the problem

Attack in range!

### Extra Notes

Confirmed on local AC (114d55d).
He is indeed not using his "Shoot" ability and just stands at range doing nothing but casting his "Net" and "Dark Iron Land Mine" from time to time. He is a level 57 rare mob and at this moment way too easy to farm for characters with range abilities.
![unknown_2021 07 16-13 22](https://user-images.githubusercontent.com/68868567/125940857-d3f1b838-01f6-4989-8c1f-fbf64500f7d9.jpg)

**Comment by iraizo** [comment]
The weird thing is, in his smartai it is defined that he does use autoshoot

**Comment by syssneck** [comment]
Maybe he needs a ranged weapon equipped for that?

**Comment by Asthalor** [comment]
I checked it, but he has the ranged weapon with id 2552 as you can see here.

![image](https://user-images.githubusercontent.com/87535580/125996147-61653978-e8f2-410b-8631-61855acddb3b.png)

I checked another creatures that use the shoot skill, and instead of a 'SKILL' event they have as '0- UPDATE_IC'. Im still testing to see if its that only.

**Comment by Asthalor** [comment]
Ok, i managed to fix it. Doing the Pull request in a minute
