### ISSUE TITLE
Bug proc judgement of wisdom/light

### ISSUE THREAD

**Issue by comix1988** [azerothcore/azerothcore-wotlk#698]
**Description**: when cast JoW or JoL  is applied a buff on enemy target that granting attacks made aganist the judged enemy a chance to restore mana or heal.

**Current behaviour**: buff restore mana or heal only on melee or ranged attacks. Spell attacks does not return mana or heal

**Expected behaviour**: buff restore mana or heal also with spell attacks

**Steps to reproduce the problem**:

1. casta judgement og light or judgement of wisdom on enemy target 
2. attack target with a spell (any caster in gruop with a paladin)
3. 

Branch(es): Master

AC hash/commit: d0af1c812bf4ea15204cad37b39ff27ff6bae339

Operating system: Linux

**Comment by Yehonal** [comment]
This should be the fix:

`UPDATE `spell_proc_event` SET `procFlags` = '1048576' WHERE `entry` IN('20185','20186');`

please try it, you can use .reload spell_proc_event on a running server, to restore old value instead you've just to set to 0

**however, are there any similar spell of other classes with the same issue?**

**does someone know which is the formula to calculate proc chance with spells? is it the same of melee?**

**Comment by Yehonal** [comment]
i've opened judgement of light with spellwork to see its internal flags

![image](https://user-images.githubusercontent.com/147092/31930526-517dcec0-b8a0-11e7-8758-96b5abe090d9.png)

and it has the correct spell proc flags, it's strange then the core is not able to make them work...does anyone have an idea?

**Comment by Atos-2017** [comment]
I link this video from old 3.3.5 retail to show how it should work. If you set the video resolution to 1080p and change video speed on 0.25, you can see the Judgement of Wisdom procs in the log in the low-left corner, starting from 0:33 to 1:59. 
Procs are those 87/88 numbers:

https://www.youtube.com/watch?v=0Y88l_tVXAk

As you can see, there are times when the JoW procs double (like on minute 1:05 or 1:18) on the dummy and in 86 seconds (1 minute and 26 seconds) you can count 36-37 procs, 24-25 just in 1 minute. This behaviour does not happen ever in the actual state. You will never have double procs and in 1 minute you'll just have a fixed 14-15 procs.

**Comment by Yehonal** [comment]
@Atos-2017 From 3.0.2 patch note:

> Judgement has been replaced with 3 new spells; Judgement of Light, Judgement of Wisdom, and Judgement of Justice. All Judgement spells are considered ranged attacks for purposes of how they hit and how they critically hit. All cause damage based on attack power and spell power.
> 
> **Judgement of Light** now heals based on the Paladin's attack power and spell power, the effect can not trigger more than once ever 4 seconds.
> **Judgement of Justice** will no longer prevent Fear effects, but will only prevent NPCs from fleeing (e.g. at low health).
> **Judgement of Wisdom** now restores mana based on the Paladin's attack power and spell power, the effect can not trigger more than once every 4 seconds.

"The effect can not trigger more than once every 4 seconds" so Judgement of Light and Judgement of Wisdom has a fixed 15 PPM 

I'll looking for other changes in patch notes after 3.0.2 and before 3.3.5a. But probably that video is wrong someway.

**Comment by Atos-2017** [comment]
It can't be wrong, it's from retail. 
You can see it by release date (21 August 2010), the comments of the author below the video and also by another screen taken during retail era: 
http://i600.photobucket.com/albums/tt82/svirve/WoWScrnShot_102009_174226.jpg 
(source: http://www.wowhead.com/forums&topic=126643/seal-judgement-of-wisdom)
So double procs should happen. 
Probably there were other changes between patches. Also because those patch notes say Judgements are ranged attacks, while in 3.3.5 they are considered melee attacks.

P.S. I discoverd another topic that could help: https://github.com/dalaranwow/dalaran-wow/issues/2979

**Comment by ahuraa** [comment]
any news?

**Comment by Yehonal** [comment]
Try query in my previous post please



Il 10 Nov 2017 08:48, "موسی الرضا" <notifications@github.com> ha scritto:

**Comment by FrancescoBorzi** [comment]
is this still an issue? can anyone double check on latest AC ?

**Comment by Yehonal** [comment]
It requires a totally rework of spell system, so i guess it's still an issue

**Comment by GMKyle** [comment]
@FrancescoBorzi @comix1988 Hello guys!!
```sql
UPDATE `spell_proc_event` SET `SchoolMask`=0, `procFlags`=1048576 WHERE `entry` IN (20185,20186);
```
this will do the trick xD @Yehonal the two spells has SchoolMask=1 (Physical)  I run a few test and with 0 procFlags they only procs on direct damage so it's better using yours.

**Comment by FrancescoBorzi** [comment]
@GMKyle thanks a lot, can you please [open a PR](http://www.azerothcore.org/wiki/Contribute#how-to-create-a-pull-request) with that ? So it can be properly checked, tested and then merged.
