### ISSUE TITLE
Worldserver crash on shutdown 80000003 libmysql.dll

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#6983]
### Current Behaviour

When exiting the worldserver using ctrl + c the worldserver crashed with 
exception code 80000003 BREAKPOINT
fault adress 00007FFC301451C2 01:00000000000641C2 E:\build-azeroth\bin\RelWithDebInfo\libmysql.dll

full crashlog https://gist.github.com/Kitzunu/874cee8a559eaab63816f24dc1f46ee2

### Expected Blizzlike Behaviour

Should be shut down properly.

### Steps to reproduce the problem

1. start worldserver and let it initialize 
2. Exit with Ctrl + c

### AC rev. hash/commit

AzerothCore rev. c20440bfc705+ 2021-07-16 15:57:32 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 80025
Using CMake version: 3.20.5
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/build-azeroth/bin/RelWithDebInfo/data/maps. Total size: 252191207 bytes
vmaps directory located in E:/build-azeroth/bin/RelWithDebInfo/data/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/build-azeroth/bin/RelWithDebInfo/data/mmaps. Total size: 2196365052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_16_01
Using Character DB Revision: 2021_07_08_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Windows 11 Home Version

**Comment by Krejza9** [comment]
Windows 11 is still not officially released and a lot can change between now and then. Does it work on Windows 10 ?

**Comment by Kitzunu** [comment]
Most likely not, this is not a windows specific one but has to do with how the databasepool is closed I think

**Comment by Viste** [comment]
you need to add Windows symbols to the Windbg symbols path.

**Comment by Kitzunu** [comment]
@Viste Okay, how do I do that? If I figure it out I can do it tomorrow or Friday

**Comment by Viste** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-symbol-and-source-paths-in-windbg

**Comment by Kitzunu** [comment]
No more crashes with Ctrl C on https://github.com/azerothcore/azerothcore-wotlk/commit/292e15d023dc63decadbb6cc28a6e172321a6dbc
