### ISSUE TITLE
[Quest]Protecting the Shipment

### ISSUE THREAD

**Issue by banehammer** [azerothcore/azerothcore-wotlk#6985]
### Current Behaviour

Miran [1379] is running

### Expected Blizzlike Behaviour

Miran [1379] should be walking

### Source

https://www.youtube.com/watch?v=qiWg1Qx0uA4

### Steps to reproduce the problem

1. .quest add 309
2. do the quest

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6e082e351393ab56993025e5cf0e12557e81fdf3

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
Please add the Commit Hash you are using =)

**Comment by banehammer** [comment]
@Kitzunu Done
