### ISSUE TITLE
Improved Succubus ( Seduction )

### ISSUE THREAD

**Issue by Narcof** [azerothcore/azerothcore-wotlk#699]
**Description**: The talent: Improved Succubus, doesn't reduce the cast of Seduction spell ( id: 6358 )

**Current behaviour**: When a Succubus cast Seduction ( id: 6358 ) with this talent: "Improved Succubus" its cast remains 1.5

**Expected behaviour**: When a Succubus cast Seduction ( id:6358 ) with this talent: "Improved Succubus" its cast should be reduced by 66%, so the cast should be: around 0.50

**Steps to reproduce the problem**:

1. Improve this talent: "Improved Succubus"
2. Cast Seduction ( id:6358 ) 
3. See the seduction cast 

**Branch(es)**: Master

**AC hash/commit**: d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Operating system**: Linux
![seduction](https://user-images.githubusercontent.com/32717748/32056222-65665662-ba64-11e7-9fdc-84835059fd49.PNG)

**Comment by ShinDarth** [comment]
@Narcof can you try this? https://github.com/TrinityCore/TrinityCore/pull/15763

**Comment by Narcof** [comment]
probably is like this issue: https://github.com/TrinityCore/TrinityCore/issues/1543

**Comment by lineagedr** [comment]
Can't reproduce.

**Comment by Narcof** [comment]
probably is a problem for my server, 1 week ago it didn't happen

**Comment by Narcof** [comment]
@lineagedr You should try to cast Seduction with Improved Succubus, because the valour on spell icon is corret ( it show 0.51 with talent ) but when you will cast Seduction, the real cast is 1.5 sec

**Comment by Yehonal** [comment]
Tested on AzerothCore staging server and bug can be reproduced

**Comment by Yehonal** [comment]
I think i've found the commit that bugged it: 

https://github.com/azerothcore/azerothcore-wotlk/commit/10eddae70087cdb8b2f6ce9e5208cc061ef682fc#diff-fe4911c7f8df768f8e6c8c82fb74b27d

@Ercules76 seems that your commit breaks succubus (maybe considered as a pet) i'll check deeper
