### ISSUE TITLE
Quest TImbermaw Ally is currently repeatable for way too much rep gain.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6990]
### Current Behaviour

Nobody will report this because it benefits them to use it. 

There's two quests, Timbermaw Ally (1st) and Timbermaw Ally (repeatable)

It also gives too much rep on both quests.  Sources have very very low numbers for these quests but on Acore its like 1000 rep a go.

https://wotlk.evowow.com/?quest=8460

https://wotlk.evowow.com/?quest=6131

### Expected Blizzlike Behaviour

Less rep

### Source

https://vanillawowdb.com/?quest=6131

https://classic.wowhead.com/quest=8460/timbermaw-ally

https://www.wowhead.com/quest=8460/deprecated-timbermaw-ally

### Steps to reproduce the problem

1. Do timbermaw ally
2. Observe obscene rep gain
3. Do it again
4. Same

### Extra Notes

pls give me exalted for reporting and not abusing this

### AC rev. hash/commit

AzerothCore rev. 4d6766d6a997 2021-07-15 15:52:19 

### Operating system

win 10

**Comment by syssneck** [comment]
Vanilla/Classic sources don't count. The reputation per kill/quest got at least two times heavily adjusted to make the reputation farm less tedious (Idk the exact patches). The first quest of Timbermaw Ally gives [1400 rep](https://wowgaming.altervista.org/aowow/?quest=8460). Every follow-up completion of Timbermaw Ally gives then [1000 rep](https://wowgaming.altervista.org/aowow/?quest=6131).
