### ISSUE TITLE
[Barrens][Quest] No Fail Condition For "Apothecary Zamah" After Logging Out For The Duration Of The Countdown 

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#6991]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1217

The fail condition for Apothecary Zamah (https://wowgaming.altervista.org/aowow/?quest=853) doesn't trigger if you log out during the whole countdown and then log in when the timer has reached zero (0), allowing you to complete the quest even if the timer has reached zero (0).

### Expected Blizzlike Behaviour

The fail condition must **always** trigger when the timer has reached zero, regardless if you logged out during the whole countdown.

### Source

Basic timed quest mechanics.

### Steps to reproduce the problem

1. Accept the quest "Apothecary Zamah" (https://wowgaming.altervista.org/aowow/?quest=853).
2. Stay logged out for the duration of the countdown (45 minutes).
3. Log in again.
4. Notice that the fail condition did not trigger and you can still complete the quest even when the timer is zero.

### Extra Notes

I reproduced this problem 3 times just to make sure.

![WoWScrnShot_071621_022443](https://user-images.githubusercontent.com/25198252/125838514-44d84a48-8c03-4b53-9a18-af0cf98dbbc1.jpg)

Another user had also experienced this issue months ago:
https://github.com/chromiecraft/chromiecraft/issues/57
It was marked **invalid** because the triager misunderstood the problem since the bug reporter explained it very poorly. 
The triager only logged out for a few seconds. Note that you need to stay logged out for the duration of the countdown (45 minutes).

Tested on: c17ce009d

**Comment by xubpwg** [comment]
Looks like generic problem for all quests with non-zero timer. For example, https://wowgaming.altervista.org/aowow/?quest=3522  has the same behavior (but much more reasonable 5 min timer)

**Comment by sudlud** [comment]
Can confirm, also had this happen to me while doing the quest.

- take quest
- log out for > 45min
- log in - quest "complete", no timer showing anymore
- relog - quest "failed"
