### ISSUE TITLE
.clang-formatter formatting wrong

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#6995]
### Current Behaviour

```cpp
class spell_gen_knock_away : public SpellScriptLoader
{
  public:
    spell_gen_knock_away()
        : SpellScriptLoader("spell_gen_knock_away") {}
```

### Expected Blizzlike Behaviour

```diff
  class spell_gen_knock_away : public SpellScriptLoader
  {
-    public:
+ public:
-    spell_gen_knock_away()
-        : SpellScriptLoader("spell_gen_knock_away") {}
+    spell_gen_knock_away() : SpellScriptLoader("spell_gen_knock_away") { }
```

### Steps to reproduce the problem

Use .clang-formatter

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6e082e351393ab56993025e5cf0e12557e81fdf3

### Operating system

w11

**Comment by Kitzunu** [comment]
@iraizo

**Comment by iraizo** [comment]
The class idention will be a easy fix but as i already stated im not sure about the functions, this is a weird issue with binpack, but ill research for a bit and try to come up with a fix!

**Comment by Kitzunu** [comment]
Nice, because this breaks scripts

**Comment by iraizo** [comment]
How so if i may ask?

**Comment by Kitzunu** [comment]
I don't know the how, but it wouldn't build without errors lol

**Comment by iraizo** [comment]
Alright, I'll look into it.

**Comment by iraizo** [comment]
The first issue is that the access modifiers dont have a certain offset this is fixed by setting `AccessModifierOffset` to -4 (since the current idention is 4 spaces). Im going to look for a fix to the line breaks now.

**Comment by iraizo** [comment]
<img src="https://i.imgur.com/hsiGb3w.png">

@Kitzunu What do you have to say about this formatting?

**Comment by Kitzunu** [comment]
that looks good, is it possible to get the {} on line 4 to have a space between? Trivial but if possible we could do that

**Comment by iraizo** [comment]
Im pretty sure theres a option for that, i will snoop around to find it

**Comment by iraizo** [comment]
There is `SpacesInSquareBrackets: ` which counts for `[]` but none for `{}` :/
