### ISSUE TITLE
NPC ID 39106 Nibby the Almighty has "greetings $N" text.

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6999]
### Current Behaviour

NPC ID 39106 Nibby the Almighty has "greetings $N" text.

![Uploading WoWScrnShot_010121_204407.jpg…]()

### Expected Blizzlike Behaviour

https://classic.wowhead.com/npc=14469/niby-the-almighty

https://wowpedia.fandom.com/wiki/Niby_the_Almighty

text that is here

### Source

https://classic.wowhead.com/npc=14469/niby-the-almighty

https://wowpedia.fandom.com/wiki/Niby_the_Almighty

### Steps to reproduce the problem

1. appear to this npc
2. speak to this npc
3. click dialogues

### AC rev. hash/commit

AzerothCore rev. 4d6766d6a997 2021-07-15 15:52:19 +0000 

### Operating system

win10

### Custom changes or Modules

chromiecraft

**Comment by Kitzunu** [comment]
Duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/6902
