### ISSUE TITLE
[VANILLA][QUEST] Investigate the Blue Recluse

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#70]
You cannot use an item ID 7247
##

**Comment by DantestyleXD** [comment]
Spell ID - 9082 Create Containment Coffer
    Requires Spell Focus 183

Gameobject Entry 103708 (Mana Rift Disturbance)
    Type: 8
    Data0: 183

Gameobject already correctly spawn but spell can't be casted.
Probably, this isn't a DB problem.

Like issue #34, this is the second similar issue

----------------------------
Server: Local (Repo AzerothCore)
Last commit hash tested: 0ba91d7c3ee994607a6e0437ab47c2c79ba1ab0a
O.S.: Windows 10
Compiler: MS Visual Studio 2013

**Comment by Viste** [comment]
reopen plz not working

**Comment by sucofog** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12561

**Comment by Stoabrogga** [comment]
This also affects "Investigate the Alchemist Shop" (https://wowgaming.altervista.org/aowow/?quest=1960). I tried to play around a bit with the appropriate entries within tables smart_scripts, conditions and gameobject_template but could not solve this.

**Comment by talamortis** [comment]
It was closed because the author didn't use the correct template.
