### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Dude100** [azerothcore/azerothcore-wotlk#7003]
### Current Behaviour

Compile

### Expected Blizzlike Behaviour

no

### Steps to reproduce the problem

no compile 

### Extra Notes

https://pastebin.com/uyttUppp

### AC rev. hash/commit

ca6483dbfc1333e8d8e47acf218aa0a6901b8421

### Operating system

Debian 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux

### Custom changes or Modules

mod-cfbg  mod-duel-reset  mod-pvp-titles

**Comment by Kitzunu** [comment]
Fixed https://github.com/azerothcore/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

**Comment by Dude100** [comment]
==== ACORE COMPILER ====
Build path: /root/progressive/azerothcore-wotlk/var/build/obj
DEBUG info: OFF
Compilation type: Release
CCache: false
-- CMake version: 3.20.0
> Warning: module using deprecated add config file api
> Warning: module using deprecated add config file api
> Warning: module using deprecated add config file api
-- Running cmake hook: AFTER_LOAD_CONF
-- No hooks registered for AFTER_LOAD_CONF
-- Enabled С++17 support
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/clang
-- Clang: Minimum version required is 10.0.0, found 13.0.0 - ok!
-- Clang: Detected from_chars bug for 64-bit integers, workaround enabled
-- Clang: All warnings enabled
-- Running cmake hook: AFTER_LOAD_CMAKE_MODULES
-- No hooks registered for AFTER_LOAD_CMAKE_MODULES
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmariadb.so
-- Found MySQL headers: /usr/include/mariadb
-- Found MySQL executable: /usr/bin/mysql
-- Found git binary : /usr/bin/git

* AzerothCore revision            : c7129fa0dd7b 2021-07-17 11:41:36 +0200 (master branch)
* AzerothCore buildtype           : Release

* Install core to                 : /root/progressive/azerothcore-wotlk/env/dist
* Install libraries to            : /root/progressive/azerothcore-wotlk/env/dist/lib
* Install configs to              : /root/progressive/azerothcore-wotlk/env/dist/etc

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build map/vmap tools            : No  (default)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show all warnings               : Yes
* Use coreside debug              : No  (default)
* Use unix gperftools             : No  (default)
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : No (For UNIX default)

CMake Error at src/cmake/macros/FindFilesystem.cmake:240 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  deps/stdfs/CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/progressive/azerothcore-wotlk/var/build/obj/CMakeFiles/CMakeOutput.log".
See also "/root/progressive/azerothcore-wotlk/var/build/obj/CMakeFiles/CMakeError.log".

@Kitzunu a little help

**Comment by iraizo** [comment]
That needs more info, what OS are you running and what version of clang?

**Comment by Dude100** [comment]
Debian 10 
-- Clang: Minimum version required is 10.0.0, found 13.0.0 - ok!
clang 13.0.0

**Comment by iraizo** [comment]
@necropola A case for you?
