### ISSUE TITLE
[Felwood] Olm the Wise (rare) missing movement pattern

### ISSUE THREAD

**Issue by iraizo** [azerothcore/azerothcore-wotlk#7012]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Olm the Wise GUID 51897 (https://wowgaming.altervista.org/aowow/?npc=14343) is stationary in his spawn.

### Expected Blizzlike Behaviour

He should be moving around in a pattern per wowhead comment.

By jbricks on 2008/03/22 (Patch 2.3.3)

Re: Olm the Wise"
Like one of the posts above, I hunted him and I got him!<br><br>
...I rode up to where I had found him 
(thanks to the coords found here) just knowing someone had already tamed
 or killed him but...there he was, flying the same pattern I had seen almost 4 hours earlier.

### Source

https://tbc.wowhead.com/npc=14343/olm-the-wise

https://www.youtube.com/watch?v=evs3q3xk_fs
https://youtu.be/WEg1X9Cs6eg?t=9
https://youtu.be/dkk3VDeS-LU?t=2

### Steps to reproduce the problem

1. Teleport to GUID 51897
2. Observe no movement

### Extra Notes

Only videos I found are from cataclysm or later, but since the spawn location of the mob did not change through patches (only model changed) its safe to assume it followed same patrol pattern in early patches. The videos show 3 different spawn locations and Olm is moving around in all of them in sort of circular pattern from his spawn.

Original report: https://github.com/chromiecraft/chromiecraft/issues/1224

#### AC HASH/COMMIT:
https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

**Comment by gurveleg** [comment]
Might aswell correct spawn time while at it - its listed as 2h45 min currently where it should be 21-32h.
Source: World of Warcraft Atlas
![Raretimers](https://user-images.githubusercontent.com/80769357/126544677-dd03f9ea-d8c0-43a2-a4eb-3f5c7624e8cf.jpg)
![olmwise](https://user-images.githubusercontent.com/80769357/126544680-7fb81cd2-6a16-4a66-923d-59056f4676c3.jpg)
 Sorry for late addition, just got my hands on the atlas today.
