### ISSUE TITLE
Waterlogged Letter either doesn't respawn or doesn't respawn correct timer

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#7021]
### Current Behaviour

Sitting on the location for over an hour no respawn or spawn. 

### Expected Blizzlike Behaviour

The respawn time for most quest objects is either 5 minutes or instant. 15 mins is considered a long respawn time.

### Source

https://wotlk.evowow.com/?object=2656#contains

https://classic.wowhead.com/quest=637/sully-balloos-letter

### Steps to reproduce the problem

1. Go to arathi under thandol span
2. Find the dwarf body crushed
3. Check letter spawn time

### AC rev. hash/commit

AzerothCore rev. c7129fa0dd7b 2021-07-17 11:41:36 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Con

### Operating system

win10

### Custom changes or Modules

chromiecraft

**Comment by JamesGent** [comment]
Checking the DB it's on a 2 hour respawn timer. That means realistically 10 people can do the quest per day which is obnoxious. 

Imagine questing with a friend or two in a party and needing to wait 2 hours to both have the same quest?

DELETE FROM `gameobject` WHERE (`id` = 2656) AND (`guid` IN (14656));
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES
(14656, 2656, 0, 0, 0, 1, 1, -2362.47, -2461.07, -20.8913, 2.30383, 0, 0, 0.913545, 0.406737, 600, 100, 1, '', 0);

This sets it to a 10 minute respawn timer, which is the longest respawn timer that quest objects usually have. 

https://wowwiki-archive.fandom.com/wiki/Spawn

https://www.wowhead.com/object=2656/waterlogged-letter#comments

**Comment by Asthalor** [comment]
I just created the PR using your fix, thanks.
Of course i named you so they know the fix was your idea.
Because the only value being changed was the spawntimesecs i made it as an UPDATE query.

**Comment by JamesGent** [comment]
Thank you Asthalor!
