### ISSUE TITLE
Dark Iron Pillow respawn too slow

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#7022]
### Current Behaviour

Long respawns, 8 pillows, you need 20, so you need to completely empty the zone of pillows 3 times to do the quest. This is bad if alone, and would be insufferable on a populated server.

If there's 25 players competing for this quest, each player would have to wait 25x3x10 = 750 minutes (12 hours).

### Expected Blizzlike Behaviour

Lower respawn time. I'd say a couple minutes, or 5 minutes at absolute maximum.

It's described as a "very fast respawn" from patch 3.1.0 here. 

### Source

https://www.wowhead.com/item=18943/dark-iron-pillow#comments

https://www.youtube.com/watch?v=S1lPtS-GkwA

Described as a "very fast respawn" from patch 3.1.0 here. 

This video from the time shows at least 6 pillows in a very small area of the beds, we could extrapolate from this video that there could be 10 total pillows given he only shows a tiny area of the total beds.

### Steps to reproduce the problem

Accept pillow quest
TP to pillows
Pick up pillows x8, then wait for respawn, then x8 again, then respawn, then x8 again.

### Extra Notes

Spawning 2 extra pillows would mean each player only needs to wait for 2 respawns, not 3, reducing the traffic/wasted time by 33%. 

### AC rev. hash/commit

AzerothCore rev. c7129fa 2021-07-17 11:41:36 +0200 (master branch) (Unix, RelWithDebInfo, Static)
Con

### Operating system

win10

### Custom changes or Modules

chromiecraft

**Comment by Kitzunu** [comment]
I can see if I can find my fix I did years ago for this. However, I dont have any spare time until Thursday to do it
