### ISSUE TITLE
akama crash

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#7027]
### Current Behaviour

npc 22845 (https://www.wowhead.com/npc=22845/ashtongue-stormcaller)
smarti ai summon 22849 cast 32911 (https://www.wowhead.com/spell=32911)
server crash

### Expected Blizzlike Behaviour

boss done

### Source

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L848
sScriptMgr->OnRemoveAuraScaleTargets(this, *itr, m_auraScaleMask, needErase); crash

This is not consistent with TC's basic code

https://github.com/TrinityCore/TrinityCoreCustomChanges/blob/2cea7d000c2205ed06ca3263e61dee51b11a5b0b/src/server/game/Spells/Spell.cpp#L807

### Steps to reproduce the problem

1.go instance 
2.start boss
3.summon npc
4.server crash

### Extra Notes

//sScriptMgr->OnRemoveAuraScaleTargets(this, *itr, m_auraScaleMask, needErase);
It can be solved temporarily, but I don't know if it's right

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e5f1104849a714a3afce43ff0900d976122a7c23

### Operating system

Windows 10 x64

### Custom changes or Modules

not custom

**Comment by Kitzunu** [comment]
Add the crashlog

**Comment by FrancescoBorzi** [comment]
@w5860363 please add the crashlog using GDB or similar

**Comment by Shybuia** [comment]
7e6727c12adb684b6b6239beb3673e694669c0db did whole fight without crash

**Comment by SoHigh495** [comment]
had the same issue on my life server. Can Confirm.

**Comment by SoHigh495** [comment]
> had the same issue on my life server. Can Confirm.

but no error logs sry.
