### ISSUE TITLE
[Felwood] Jadefire Shadowstalker missing Shadowstalker Stealth Rank 1 ability

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7056]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

Original report: [Chromiecraft issue#1226](https://github.com/chromiecraft/chromiecraft/issues/1226)

### Current Behaviour

Jadefire Shadowstalkers (https://wowgaming.altervista.org/aowow/?npc=7110) are using the ability Sneak (https://wowgaming.altervista.org/aowow/?spell=11013) which doesnt actually put them into stealth and are clearly visible from far away. 

![jadefire](https://user-images.githubusercontent.com/80769357/126059815-b80252de-7f9e-47d4-97ef-041338f2773a.jpg)

### Expected Blizzlike Behaviour

They should be using Sneak rank 1 ability per wowhead, and videos clearly show them being properly stealthed.

### Source

https://tbc.wowhead.com/npc=7110/jadefire-shadowstalker#abilities

https://youtu.be/BTP42cFGsT8?t=48
https://youtu.be/f78IXO87pVU?t=59

### Steps to reproduce the problem

1. Teleport to GUID 40743 for example
2. Observe the Jadefire Shadowstalkers

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (fab0fc4).
He is only using sneak but does not go into stealth, because he is missing the Shadowstalker Stealth Rank 1 ability [wotlkdb](https://wotlkdb.com/?npc=7110).
This way, he is clearly visible:
![unknown_2021 07 21-11 54](https://user-images.githubusercontent.com/68868567/126470280-6bc15d09-2876-49dd-9bc1-bc7289f46820.png)

**Comment by necropola** [comment]
I've imported the vmangos classic sniff data that got recently published into a local DB and then ran the following query on it:
```SQL
SELECT c.entry, c.name, s.spell_id 
FROM spell_unique_caster s INNER JOIN creature_template_wdb  c
ON s.caster_id = c.entry WHERE caster_id=7110;
+-------+------------------------+----------+
| entry | name                   | spell_id |
+-------+------------------------+----------+
|  7110 | Jadefire Shadowstalker |     1604 |
|  7110 | Jadefire Shadowstalker |     7939 |
|  7110 | Jadefire Shadowstalker |     7992 |
|  7110 | Jadefire Shadowstalker |    13578 |
|  7110 | Jadefire Shadowstalker |    22766 |
+-------+------------------------+----------+
```
- 1604: https://wowgaming.altervista.org/aowow/?spell=1604
That's just the core daze that all creatures can apply from behind
- 7939:  Not found in `aowow`, but in here:  https://classic.wowhead.com/spell=7939/sneak
A (weird) Sneak ability which stealthes the caster but slows movement speed to 1%
- 7992: https://wowgaming.altervista.org/aowow/?spell=7992
Slowing Poison
- 13578: https://wowgaming.altervista.org/aowow/?spell=13578
Jadefire
22766: https://wowgaming.altervista.org/aowow/?spell=22766
A Sneak ability which stealthes the caster but slows movement speed by 50%

This is obviously not data from WotLK times, but probably still the best we have at the moment.
