### ISSUE TITLE
 Searing Gorge - Quest "Gaining Acceptance" Not Repeatable

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7061]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1235

Currently Gaining Acceptance could be turned in only once.

Tester: confirmed. The SpecialFlags field in `quest_template_addon` for this quest is set to 0 when it should be 1 for a repeatable quest.

Note PR https://github.com/azerothcore/azerothcore-wotlk/pull/1777 - this issue was raised before in 2019, but the Gaining Acceptance quest remained unrepeatable afterwards.

Also the quest text description is missing:

![WoWScrnShot_072221_002625](https://user-images.githubusercontent.com/81782124/126510870-3f61a768-7282-4525-87e5-9cc6925deb1d.jpg)

### Expected Blizzlike Behaviour

Quest is supposed to be repeatable, allowing players to turn in less than 100 Dark Iron Residues.

"This quest is repeatable up to Honored." according to Wowpedia.

### Source

https://classic.wowhead.com/quest=7737/gaining-acceptance
https://wowpedia.fandom.com/wiki/Gaining_Acceptance

### Steps to reproduce the problem

1. .modify reputation 59 5000 - gives you Friendly rep with Thorium Brotherhood. 
2. .quest add 13662
3. .go c 5589
4. .additem [Dark Iron Residue] 4
5. Hand in - the quest will not be offered again.

#### CC Hash
c7129fa

**Comment by Azcobu** [comment]
Reopening after reading the linked PR more carefully, as it doesn't seem to be correct.

**Comment by JamesGent** [comment]
```SQL
UPDATE `quest_template_addon` SET `SpecialFlags` = 1 WHERE (`ID` = 13662);
```
