### ISSUE TITLE
[Hunters] can auto attack while channeling Volley 

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7067]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

Original report: [Chromiecraft issue#1257](https://github.com/chromiecraft/chromiecraft/issues/1257)

### Current Behaviour

So i don't know if its supposed to happen but i assume it isn't since you're channeling the volley itself and it should cancel out any other action during said channeling. you press auto attack first then use "volley" right after. my swing timer seems to catch it and i can see the auto attack itself too provided in my screenshot below.

### Expected Blizzlike Behaviour

I assume the volley should override the auto attack entirely and begin with volley and only volley unless stunned or otherwise.

### Steps to reproduce the problem

1.press "auto attack" then use volley and if it's too hard to tell even further download a swing timer to show you said actions.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

I can confirm it on my local AC (d187ba1).
As you said, I needed to autoattack first and Volley instantly afterwards. Autoattack should normally cancel the channeling.
Volley + autoattack test:

https://user-images.githubusercontent.com/68868567/126618381-c0663200-e503-4feb-b84d-b546651e5957.mp4

Older video with Volley and no autoattack while channeling Volley: 
[Volley without autoattack blizzlike](https://youtu.be/vxUeCb3sfgc?t=117)

**Comment by UltraNix** [comment]
No. Volley do not reset autoshot due to `SPELL_ATTR2_NOT_RESET_AUTO_ACTIONS` attribute.

**Comment by UltraNix** [comment]
@Shineslippers Open a new ticket about this. It's something different.
