### ISSUE TITLE
Timer On Rogue's Sap Pauses When Out of Sight of Target

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7069]
### What client do you play on?

frFR

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1244

When you're in a dungeon and you sap a npc, you can run away from it to lose sight and when you come back, you can observe that the npc is still sapped and the timer runs again like it was paused.

You can see in chat the time : **18:08:35** when about to **lose sight with 22s remaining on the sap**
![WoWScrnShot_071921_180840](https://user-images.githubusercontent.com/82708448/126192871-ae1a836d-cac8-476c-b270-281a247b7ded.jpg)
Then you see the time after a few killed mobs : **18:09:11**, that's already **36s from first screen**
![WoWScrnShot_071921_180917](https://user-images.githubusercontent.com/82708448/126192886-56859eee-2b6c-46ee-9fea-19d0ed64fc0e.jpg)

Then when I come back the npc was still sapped and I guess the timer kept running again when I was in his sight.

https://user-images.githubusercontent.com/82708448/126192761-931b2c41-4922-45f7-ba4a-3d8610c6e020.mp4

Tester: confirmed. You have to go far enough away that you lose the target, but that appears to stop the timer completely. This seems to be a dungeon-only issue. I tested in open world, and the sap timer kept going even when the target was out of sight.

There are 4 ranks of Sap (rank 1 = spell ID 6770, rank 2 = 2070, rank 3 = 11297, rank 4 = 51724) and all four tested displayed this problem.

4.5 minutes sap in SM:
![WoWScrnShot_072221_212016](https://user-images.githubusercontent.com/81782124/126635363-a84547de-605a-45ad-a60b-5fa600e4cb8c.jpg)

2.5 min sap, Maraudon:
![WoWScrnShot_072221_213557](https://user-images.githubusercontent.com/81782124/126636578-928e458e-28c0-4070-9097-d17bc350c30f.jpg)

Working fine in open world:
![WoWScrnShot_072221_214045](https://user-images.githubusercontent.com/81782124/126637141-2c9325bf-1183-4220-be6d-cccda7a604af.jpg)

### Expected Blizzlike Behaviour

Sap timer (25/35/45/60 secs depending on rank) should end normally either if you're in sight of the mob or not.

### Source
No direct source, but this doesn't seem a controversial claim.

### Steps to reproduce the problem

1. Enter a dungeon as a rogue.
2. Sap a npc.
3. Run away from him, and check the remaining time on the debuff while losing sight.
4. Take your time out of sight (more time than the remaining debuff obviously).
5. Come back and observe the npc still sapped with the remaining timer running as soon as you enter his sight.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
it's the same in open world. It's just grids that are going deactivated when there is no player around. It's normal.

**Comment by Azcobu** [comment]
Closing as per above.
