### ISSUE TITLE
Hammer of Justice Interrupt Works Despite Missing

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7073]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1255

Missing with Paladin's spell Hammer of Justice (https://wowgaming.altervista.org/aowow/?spell=853) on non-player entity that is in the middle of their interruptable cast, does not stun it but still interrupts the cast.
So far was able to find three mob NPCs that are affected by the issue:
- Withered Ancient https://wowgaming.altervista.org/aowow/?npc=3919
- Nightbane Shadow Weaver https://wowgaming.altervista.org/aowow/?npc=533
- Rogue Flame Spirit https://wowgaming.altervista.org/aowow/?npc=4036

but it does not mean that the problem couldn't be global.

![HoJ stun miss but interrupts 2](https://user-images.githubusercontent.com/71841180/126404905-350a5b95-b5eb-4ce9-bda3-2a4da7101dbb.png)
![HoJ stun miss but interrupts](https://user-images.githubusercontent.com/71841180/126404907-0db1b82b-5bfb-4dbc-9650-ad0ae9a92e6f.png)
![HoJ stun miss but interrupts3](https://user-images.githubusercontent.com/71841180/126407598-e6dc2bf5-06c7-41b6-b074-32bb0fc20077.png)

Tester's notes: Confirmed, and for more than these 3 listed NPCs. I tried with a couple of others with cast times (Oracles in Ulda, Winterspring Shamans) and they all did it too. 

https://user-images.githubusercontent.com/81782124/126652336-e2e7d336-0dad-4236-b97d-4ec25b41a40c.mp4

It looks as if the interrupt effect in the combat log is treated as auto-hit on cast, whether the parent spell hits or not.
![WoWScrnShot_072221_231147](https://user-images.githubusercontent.com/81782124/126652907-05f015f0-60ac-4b60-abf4-001f21daef2d.jpg)

### Expected Blizzlike Behaviour

Missing with the stun from Hammer of Justice also does miss with cast's interruption.

### Source
This doesn't seem controversial.

### Steps to reproduce the problem

1. Have a paladin with learnt Hammer of Justice spell
2. For better results make sure paladin has a 0 hit rating and is level 19
2. Travel to the location with one of the mob NPCs mentioned in the current behaviour
3. Engage combat with mob
4. Wait for the mob to start casting its interruptable spell
5. While mob is still casting use HoJ spell on it, paying attention if stun effect was applied or not
6. If stun was not applied, verify if mob's cast is still proceeding

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
It's blizzlike. Even if stun from Hammer of Justice is missed, it still can interrupt spell casting thanks to `SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER`
