### ISSUE TITLE
[Wands] It is possible to (fast) switch with a wand/melee weapon, without resetting the swingtimer

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7074]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: [Chromiecraft issue#1246](https://github.com/chromiecraft/chromiecraft/issues/1246)

### Current Behaviour

While using a Wand, if you get in melee range, you can attack with Wand and then press 1 to attack with Melee. The attacks are almost simultaneous and result in constant high dmg. It is basically the same as attacking 2 times in a row, only this can be done continuously.

It would best be shown in the video I attached

https://user-images.githubusercontent.com/87674808/126230907-de13ca0c-d736-412f-8ee9-ba82f891c44a.mp4

### Expected Blizzlike Behaviour

As far as I  know.
The moment I attack I should get an attack Cooldown that's either = to the Cooldown of the WAnd or Melee weapon.

### Steps to reproduce the problem

1. Get a Wand
2. Getting into Melee range
3. Put Melee and range attacks on 1 and 2 hotkeys for fast switch
4. Attack with  wand
5. Attack with Melee

### Extra Notes

I would like to NOTe, that the only reason I think this is a bug, is because it deals crazy dmg, more then any Melee class can do as a ranged.

There is still a slight delay sometimes between attacks but it's at most 0.3-0.5 secs, which is still to fast.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (d187ba1).
I believe, switching from a wand to a melee weapon should reset the swingtimer of the melee weapon, but on AC the melee swingtimer keeps going, even when I already switched to my wand, so that I can do melee attacks with wand attacks in-between. This can heavily be abused with a fast melee weapon and a fast wand (see second part of the video) for increased damage output.
Test video (I did not always get it right. Sometimes I switched too fast, sometimes too slow):

https://user-images.githubusercontent.com/68868567/126654418-b51003cb-6e0d-423b-aaec-fc716c2cec90.mp4

**Comment by UltraNix** [comment]
I need an evidence from retailt, because for me it's not a bug.

**Comment by UltraNix** [comment]
@syssneck And about hunters changing autoshot to melee attack? Autoshoot should also reset their melee attack timer? So when hunter wants to change from autoshoot to melee he should wait?

**Comment by syssneck** [comment]
Yepp ... after looking at it all again, I'm not so sure that it is a bug anymore.

**Comment by UltraNix** [comment]
For me it's not a bug too.

**Comment by FrancescoBorzi** [comment]
> Yepp ... after looking at it all again, I'm not so sure that it is a bug anymore.

cc @azerothcore/bug-triaging @Si1ker @Maurowin @Knindzagxg

can anyone please confirm?

**Comment by Knindzagxg** [comment]
Will check today once im back home.

**Comment by Knindzagxg** [comment]
There should be GCD / SWT for sure.
It's happening way faster then it's supposed.

Not sure where to look for formula, but something is wrong xP

**Comment by UltraNix** [comment]
What is SWT?
"something is wrong" is not a argument for me

**Comment by Knindzagxg** [comment]
SwingTimer mate xD

**Comment by Knindzagxg** [comment]
And what i mean with "something is wrong" -> I don't know where to look for GCD/SWT formula to see if i can find the problem.
Even mentioned it above xP

**Comment by UltraNix** [comment]
The main problem is to confirm that this bug. I wrote my concerns about hunter's autshoot as it is the same mechanic as wands.

**Comment by Knindzagxg** [comment]
It's a little different tho.
Main issue for me is that instant melee swings and back to wandshoot instantly after as well.

**Comment by UltraNix** [comment]
Yes. But we are not sure it this is an intended behaviour. Because it's just switching from authshoot ability to automelee ability just like hunters do.

**Comment by syssneck** [comment]
I did a bit more testing:
1.) Attacking with ranged doesn't reset the melee SWT (correct)
2.) Attacking with melee doesn't reset the ranged SWT (correct)
3.) Switching between melee and ranged does not allow me to attack faster than each individual SWT. E.g. a staff with a 2.0 attackspeed has (at least) 2 s between each melee swing and a wand with a 1.3 attackspeed has (at least) 1.3 s between each wand attack (correct)
4.) A wand that is as fast or faster than the melee weapon allows for one ranged attack in between the melee SWT. If the wand is more than twice as fast, it would even be possible to get two ranged attacks in between the melee SWT (correct)

Sorry for creating this issue. We can close this one from my perspective.

**Comment by iraizo** [comment]
Better safe than sorry
