### ISSUE TITLE
[Blasted Lands] Ravage (rare) moving too fast

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7079]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

Orignal report: [Chromiecraft#1276](https://github.com/chromiecraft/chromiecraft/issues/1276)

### Current Behaviour

Ravage GUID 38303 (https://wowgaming.altervista.org/aowow/?npc=8300) has very fast roaming speed. His walk speed is set to 2.5 currently.

### Expected Blizzlike Behaviour

He should walk a lot slower.

### Source

https://www.youtube.com/watch?v=mnkFxjufGRo

### Steps to reproduce the problem

1. Teleport to Ravage ( GUID 38303)
2. Observe his movement speed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (d187ba1). Ravage is walking too fast.

**Comment by JamesGent** [comment]
```SQL
UPDATE `creature_template` SET `speed_walk` = 1 WHERE (`entry` = 8300);
```
