### ISSUE TITLE
Build Failed, Cmake errors

### ISSUE THREAD

**Issue by justdothings** [azerothcore/azerothcore-wotlk#708]
**Description**: Build failed getting error also in cmake
"Running cmake hook: AFTER_WORLDSERVER_CMAKE
No hooks registered for AFTER_WORLDSERVER_CMAKE
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD"

**Current behaviour**: Build failed (cant build worldserver.exe and mmaps extractor)

**Expected behaviour**: Tell us what should happen instead -> you know what should happen instead

**Steps to reproduce the problem**:

1. update core to 17802ab6e5135f0220efcd8f4e460f8202a4c047
2. try to compile with tools
3.  19 success and 3 failed

**Branch(es)**: master

**AC hash/commit**:  17802ab6e5135f0220efcd8f4e460f8202a4c047

**Operating system**:  Win 10

**Modules**:  no

**Other Customizations**: no

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Inifield** [comment]
Those are not error

**Comment by Rochet2** [comment]
https://travis-ci.org/azerothcore/azerothcore-wotlk/builds/302187581#L1436-L1446
https://travis-ci.org/azerothcore/azerothcore-wotlk/builds/302187581#L1010-L1021
These are. Travis not passing.
The last commit should be reverted or fixed. It seems the dep had things that were used in core and when removed or changed cause these errors. (changed function signature, missing constant variables)

**Comment by sucofog** [comment]
@Rochet2 A PR is pending to apply, i'll merge it now.

**Comment by sucofog** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/c75ec13191ee5e6525d8fcf963cc7adcaf979739

Fixes the build.
