### ISSUE TITLE
[Blasted Lands] Dreadscorn (rare) wrong respawn timer

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7080]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

Original report: [Chromiecraft#1275](https://github.com/chromiecraft/chromiecraft/issues/1275)

### Current Behaviour

Dreadscorn GUID 3902 (https://wowgaming.altervista.org/aowow/?npc=8304) has wrong respawn timer. It's currently set to 15 minutes.

### Expected Blizzlike Behaviour

Dreadscorn should have respawn time of  5-8 hours.

### Source

World of Warcraft Atlas:
![Raretimers](https://user-images.githubusercontent.com/80769357/126751595-32105bc9-532f-496d-a538-213cd7b03c99.jpg)
![dreadscorn](https://user-images.githubusercontent.com/80769357/126751597-d0e51fe9-6b3a-4867-9d31-b907f9f09794.jpg)

https://tbc.wowhead.com/npc=8304/dreadscorn#comments
https://www.wowhead.com/npc=8304/dreadscorn#comments

### Steps to reproduce the problem

1. Teleport to Dreadscorn and kill him, wait 15 min and he respawns
2. or Check his spawn time in database

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed in db:
```SELECT `spawntimesecs` FROM `creature` WHERE `guid` = 3902``` will show the `spawntimesecs` of 900 s (15 min).

**Comment by JamesGent** [comment]
```SQL
DELETE FROM `creature` WHERE (`id` = 8304) AND (`guid` IN (3902));
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(3902, 8304, 0, 0, 0, 1, 1, 7844, 1, -11431.6, -2626.02, 39.1104, 0.85454, 18000, 0, 1, 3758, 0, 2, 0, 0, 0, '', 0);
```
