### ISSUE TITLE
[Blasted Lands] Clack the Reaver (rare) is moving too fast

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7082]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

Original report: [Chromiecraft#1277](https://github.com/chromiecraft/chromiecraft/issues/1277)

### Current Behaviour

Clack the Reaver (https://wowgaming.altervista.org/aowow/?npc=8301)  is moving around too fast. His walking speed is set to 2.6

https://user-images.githubusercontent.com/80769357/126761320-f3a17e0e-02dc-4900-93af-1267a14cf13b.mp4

### Expected Blizzlike Behaviour

His walking speed should be normal, like other scorpiods.

### Source

https://www.youtube.com/watch?v=QKVkxyoHbw8

### Steps to reproduce the problem

1. Teleport to Clack the Reaver -  entry 8301
2. Observe his movement speed

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC(d187ba1). 
Clack the Reaver (rare) is moving too fast

**Comment by JamesGent** [comment]
UPDATE `creature_template` SET `speed_walk` = 1 WHERE (`entry` = 8301);
