### ISSUE TITLE
Fix > GO Matrix Punchograph 3005-D (142696) on gnomeregan 

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#71]
It does not work. there is no gossip option.
So, I'd checked to .sql update and founded to a error.

Here is fix queries. I'd checked to these on my server. and Its worked properly (even learn spell - Discombobulator Ray.)

DELETE FROM conditions WHERE SourceTypeOrReferenceId=15 AND SourceGroup=1050;
INSERT INTO conditions VALUES (15, 1052, 0, 0, 0, 2, 0, 9281, 1, 0, 0, 0, 0, '', 'Display option if player has red card');
INSERT INTO conditions VALUES (15, 1052, 1, 0, 0, 2, 0, 9281, 1, 0, 0, 0, 0, '', 'Display option if player has red card');
INSERT INTO conditions VALUES (15, 1052, 1, 0, 0, 2, 0, 9327, 1, 0, 0, 0, 0, '', 'Display option if player has delta card');
INSERT INTO conditions VALUES (15, 1052, 1, 0, 0, 25, 0, 3959, 0, 0, 1, 0, 0, '', 'Display option if player has no Discombobulator Ray spell');

**Comment by ShinDarth** [comment]
Please open a PR, read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute
