### ISSUE TITLE
Crash in WorldSession::SendPacket

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#7100]
### Current Behaviour

https://gist.github.com/Kitzunu/5320e4372612b285718ce066acf33f5a

Unhandled exception thrown: read access violation.
**this** was nullptr.

(L#206)

https://github.com/azerothcore/azerothcore-wotlk/blob/59c8f7276eb7a578789360c5cfc8087c9f549969/src/server/game/Server/WorldSession.cpp#L197-L207

### Expected Blizzlike Behaviour

not null :D

### Steps to reproduce the problem

1. .reload page

### AC rev. hash/commit

59c8f7276eb7a578789360c5cfc8087c9f549969

### Operating system

win11

**Comment by lineagedr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/59c8f7276eb7a578789360c5cfc8087c9f549969/src/server/game/Server/WorldSession.cpp#L692

You could try.
```c++
if (format && format[0]) 
```

**Comment by Kitzunu** [comment]
dont work
