### ISSUE TITLE
Ulduar Teleporter: Some options teleport the player to the wrong location

### ISSUE THREAD

**Issue by steenburgh** [azerothcore/azerothcore-wotlk#7108]
![image](https://user-images.githubusercontent.com/9411156/126890478-039e96a6-2144-4db5-a58a-d196510ad06e.png)

### Current Behaviour

* The "Teleport to the Spark of Imagination" option incorrectly teleports the player to the Descent into Madness
* The "Teleport to the Descent into Madness" option incorrectly teleports the player to the Spark of Imagination

### Expected Blizzlike Behaviour

* The "Teleport to the Spark of Imagination" option should teleport the player to... the Spark of Imagination
* The "Teleport to the Descent into Madness" option should teleport the player to... the Descent into Madness

### Source
https://wowpedia.fandom.com/wiki/Ulduar_Teleporter

### Steps to reproduce the problem
Unlock the Spark of Imagination and Descent Into Madness teleport options, then try using them
1. Kill Flame Leviathan
    * `.go creature 202501`
    * `/target Flame`
    * `.die`
2. Engage Mimiron. You must *engage him*, don't just kill him immediately or the teleporter option will not unlock
    * `.go creature 137630 Mimiron`
    * `/target Mimiron`
    * `/startattack`
3. Kill General Vezax 
    * `.go creature 137581`
    * `/target General`
    * `.die`
4. Go to any Ulduar Teleporter `.go object 34223`
5. Try using the "Teleport to the Spark of Imagination" option. Look at your map and check what zone you're in
6. Try using the "Teleport to the Descent into Madness" option. Look at your map and check what zone you're in

### Extra Notes
I looked in the `smart_scripts` table and the spells associated with each option are correct, but when I cast the spells manually, they take me to the wrong location. To fix this, I need to swap the teleport locations in the `spell_target_position` table

Here are the spells associated with each option for reference:
  * "Teleport to the Spark of Imagination": [Halls of Invention Teleport](https://www.wowhead.com/spell=64025/halls-of-invention-teleport)
  * "Teleport to the Descent Into Madness": [Prison of Yogg-Saron Teleport](https://www.wowhead.com/spell=65042/prison-of-yogg-saron-teleport)

Here's a SQL script that seems to fix this. I just need to test it against the latest production build + get a PR out
```
-- Fix location for spell: 'Halls of Invention Teleport'
UPDATE spell_target_position
    SET PositionX = 2518.22, PositionY = 2569.11, PositionZ = 412.69, Orientation = 3.10668
    WHERE ID = 64025;

-- Fix location for 'Prison of Yogg-Saron Teleport'
UPDATE spell_target_position
    SET PositionX = 1854.8, PositionY = -11.46, PositionZ = 334.57, Orientation = 4.79266
    WHERE ID = 65042;
```

### AC rev. hash/commit

2e6f78bdddbc

Note: I have an ancient commit, so I need someone to confirm that this is still an issue in production. I'm 99% sure it is as I haven't seen any issues open that seem related, and all the references to the teleport spells in the SQL patches or the `base/db_world/` files use the wrong teleport locations in `spell_target_position`

### Operating system

Windows 10

### Custom changes or Modules

mod-autobalance custom build with role-based scaling
mod-ah-bot (custom build from https://github.com/steenburgh/mod-ah-bot/pull/1)
mod-individualxp
mod-1v1-arena

**Comment by steenburgh** [comment]
So the plot thickens... I think the spells are actually correct in the DB but behaving incorrectly
* The 'Teleport to the Spark of Imagination" option casts [Halls of Invention Teleport](https://www.wowhead.com/spell=64025/halls-of-invention-teleport), but the spell teleports you to Descent Into Madness
* The 'Teleport to the Descent Into Madness" option casts [Prison of Yogg-Saron Teleport](https://www.wowhead.com/spell=65042/prison-of-yogg-saron-teleport), but the spell takes you to the Spark of Imagination

I also found a spell on wowhead called [Descent Into Madness Teleport](https://www.wowhead.com/spell=64027/descent-into-madness-teleport), which might actually be what we want to use for the "Teleport to Descent Into Madness" option, but when I cast it it plays the teleport animation but does nothing

**Comment by steenburgh** [comment]
Yep, it's the spell locations that are wrong, not the spell choice. I can just update the `spell_target_position` table. PR incoming next time I get some free time

**Comment by FrancescoBorzi** [comment]
> PR incoming next time I get some free time

that's nice! good job

**Comment by steenburgh** [comment]
Just confirmed on the latest commit, bbc071
