### ISSUE TITLE
Long wait on login

### ISSUE THREAD

**Issue by 36li** [azerothcore/azerothcore-wotlk#711]
**Description**:I can't login. I need to wait for tens of minutes

**Current behaviour**: Console message:"Instance ID reset occurred, sending updated calendar and raid info to all players!"

**Expected behaviour**: Getting  list of characters,Message box disappears after tens of minutes.Console message:"Instance ID reset occurred, sending updated calendar and raid info to all players!"

**Steps to reproduce the problem**:

1. Install a new server and start the server

**Branch(es)**: master

**AC hash/commit**:  AzerothCore rev. c4622096e973+ 2017-11-17 00:26:19 +0100 (master branch)

**Operating system**:  Windows 10 x64

**Modules**:  nothing

**Other Customizations**: nothing

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Yehonal** [comment]
cannot confirm, maybe you have some issues on your network?

that console message is not related

**Comment by sucofog** [comment]
Can't confirm

**Comment by 36li** [comment]
After a long time, I can play the game.But the same problem happens when you rebuild a characters database

**Comment by talamortis** [comment]
Can not confirm try a recompile closing issue unless someone else can confirm.

**Comment by Furrazzlhf** [comment]
Hello , i have the same problem , i'v to wait a long time during characters login and haven't got any problem on my network ...

**Comment by talamortis** [comment]
are you using any modules?

**Comment by Furrazzlhf** [comment]
I'm using the transmog module

**Comment by Trystanosaurus** [comment]
I know this issue has been closed but I've had the same issue using commit dd463b30b613

Heidi SQL shows one of Azeroth Cores threads trying to run the query "instance_reset SET resettime = ? WHERE mapid = ? AND difficulty = ?" which doesn't seem to want to run but that's using up the thread so the client ends up stuck on retrieving character list.

I'm using SQL 5.6.28, InnoDB.

**Comment by Inifield** [comment]
ok I confirmed the issue, i'll try to fix it soonish

**Comment by Yehonal** [comment]
I can confirm it, please try truncating instance_reset table and restart worldserver

**Comment by Kron4ek** [comment]
Confirm it. Problem disappears after truncating instance_reset.

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/9db1d639fcbbb9fc72803150cf073178a3516636/src/common/Database/Implementation/CharacterDatabase.cpp

https://github.com/azerothcore/azerothcore-wotlk/blob/dd300003e27ea6b5e8060d9f2adb8bf4cd7e913d/src/server/game/Instances/InstanceSaveMgr.cpp

**Comment by Deku** [comment]
Please continue the discussion in #877 and #880 

Closing this to avoid duplicates.
