### ISSUE TITLE
[Paladin] Immunity to HoJ's stun prevents from cast interruption

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#7110]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Using Paladin's spell Hammer of Justice (https://wowgaming.altervista.org/aowow/?spell=853) on non-player entity that is in the middle of their interruptable cast, but is immune to stun effects, fails to interrupt that cast.
So far was able to find on mob NPC that is affected by the issue:
- Befouled Water Elemental https://wowgaming.altervista.org/aowow/?npc=3917

but it does not mean that the problem couldn't be global.
![HoJ interrupt fail due to stun immune](https://user-images.githubusercontent.com/71841180/126416446-89b87816-4b4e-4310-a5a1-18bd7922d9ca.png)

On Wowiki for Hammer of Justice, we can find "Patch 3.0.3 (04-Nov-2008): (...) In addition, the interrupt will now work on targets immune to stun."

### Expected Blizzlike Behaviour

Paladin can still perform cast interruption on non-player entity with Hammer of Justice spell even if the entity is immune to the stun effect, as long as the targetted cast is interruptable.

### Source

https://wowwiki-archive.fandom.com/wiki/Hammer_of_Justice

### Steps to reproduce the problem

1. Have a paladin with learnt Hammer of Justice spell
2. Travel to the location with the mob NPC mentioned in the current behaviour
3. Engage combat with mob
4. Wait for the mob to start casting its interruptable spell
5. While mob is still casting use HoJ spell on it
6. Verify if mob's cast is not proceeding

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/1258

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
That mob is immuned to all interrupt spells.
The HoJ interrupt mechanic works okay.

**Comment by UltraNix** [comment]
The only question is: should that mob be immuned to cast interruption?

**Comment by Azcobu** [comment]
Checked for info on this - https://wowpedia.fandom.com/wiki/Befouled_Water_Elemental?oldid=2686732 has a couple of immunities listed, but they're just mage frost spells. Someone on TBC Wowhead claims they're immune to poisons too (https://tbc.wowhead.com/npc=3917/befouled-water-elemental#comments:id=1223:reply=1304629) but no mention of interrupts. Checked Youtube for quest videos, but couldn't find any where anyone used interrupts. So couldn't find any data to say either way.
