### ISSUE TITLE
[Arathi Basin] Music only loops the first minute of the drum part and doesn't continue

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7111]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: [Chromiecraft issue#1252](https://github.com/chromiecraft/chromiecraft/issues/1252)

### Current Behaviour

So it seems like this has either gone un-noticed or no one cares but the arathi basin OST seems to loop the very first minute of the drum part and thats it for the entire match. it doesn't continue to the full soundtrack or anything, it either stops or repeats the drum part when you revive. it's either my client(which mind you i downloaded and redownloaded 3 times already) or something is wrong.

### Expected Blizzlike Behaviour

After the first initial drum part it should continue on to the full soundtrack and derive to the winning part of it if possible.

### Steps to reproduce the problem

1.Hop in Arathi Basin map and listen to the soundtrack
2,continue to listen to see if it repeats or not

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7129fa0dd7b9951589599654fe83cdcd2a55d7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (d187ba1).
The music loops again after one minute. 
I can't find a source for the original OST at the moment (not the reworked one), but I'm pretty sure, that it was longer than only one minute.

**Comment by UltraNix** [comment]
It's totally clientside.
