### ISSUE TITLE
mails sent via SOAP have no subject shown in the minimap mailbox icon

### ISSUE THREAD

**Issue by speedrunz** [azerothcore/azerothcore-wotlk#7114]
### Current Behaviour

When you send an email or items via SOAP. It only shows "you have unread email". It is a bug. Check the screenshot below.

https://imgur.com/a/bWoxHHl

### Expected Blizzlike Behaviour

It should work like this image
https://imgur.com/a/hjSfe6F

### Steps to reproduce the problem

1. Use the sample PHP soap script below and replace the following.
```
  'soap_uri' => 'urn:AC',
  'soap_host' => 'serverip',
  'soap_port' => '7878',
  'account_name' => 'gmaccountlevel3',
  'account_password' => 'gmaccountpassword'
  
  CharacterName
```

```
<?php

$soap_connection_info = array(
  'soap_uri' => 'urn:AC',
  'soap_host' => 'serverip',
  'soap_port' => '7878',
  'account_name' => 'gmaccountlevel3',
  'account_password' => 'gmaccountpassword'
);

function RemoteCommandWithSOAP($username, $password, $COMMAND)
{
    global $soap_connection_info;
    $result = '';

    try {
        $conn = new SoapClient(NULL, array(
            'location' => 'http://' . $soap_connection_info['soap_host'] . ':' . $soap_connection_info['soap_port'] . '/',
            'uri' => $soap_connection_info['soap_uri'],
            'style' => SOAP_RPC,
            'login' => $username,
            'password' => $password
        ));
        $result = $conn->executeCommand(new SoapParam($COMMAND, 'command'));
        unset($conn);
    } catch (Exception $e) {

        $result = "Have error on soap!\n";

        if (strpos($e, 'There is no such command') !== false) {
            $result = 'There is no such command!';
        }
    }
    return $result;
}

echo RemoteCommandWithSOAP($soap_connection_info['account_name'], $soap_connection_info['account_password'], '.send items CharacterName"Thank you for your Support" "Here\'s your free item" 50016');

?>
```

### Extra Notes

make sure php-soap is enabled according to your php version.

### AC rev. hash/commit

2e32a80f249c

### Operating system

Ubuntu 20.04

### Custom changes or Modules

mod-cfbg
mod-anticheat
mod-premium
mod-transmog

**Comment by Kitzunu** [comment]
Because mails from GMs dont have that.

**Comment by speedrunz** [comment]
@Kitzunu mails from GM do have that. I tried the same command via in-game and via SOAP using the same gm account. In-game works as intended. SOAP on the other hand doesn't. Will you be able to get someone who can work on this? i'll pitch some $.

**Comment by FrancescoBorzi** [comment]
> Will you be able to get someone who can work on this? i'll pitch some $.

@speedrunz you can easily invest money on an issue by [using bountysource](http://www.azerothcore.org/wiki/Bountysource)

**Comment by Nyeriah** [comment]
It's because of this: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_misc.cpp#L2683-L2684

Mails sent from console don't have senders, because they're not linked to any specific player. Thus, in-game it doesn't show anything in the minimap notification icon where normally it'd show the sender's name, as it normally does when you send a mail from a GM character.

**Comment by Helias** [comment]
so, from your point of view @Nyeriah we can close this issue? or is there a way to show the subject even if there is no char as sender?

**Comment by Nyeriah** [comment]
> so, from your point of view @Nyeriah we can close this issue? or is there a way to show the subject even if there is no char as sender?

I found some issues processing the mail packet as well, I'll submit a pull request shortly.

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/8065 
https://github.com/azerothcore/azerothcore-wotlk/pull/8064

Applying both of those will fix this issue
