### ISSUE TITLE
Initial quests for each race do not work

### ISSUE THREAD

**Issue by corsairs** [azerothcore/azerothcore-wotlk#7123]
### Describe your feature request or suggestion in detail

Initial quests for each race do not work in a Russian client
The quest is not taken.

**Comment by Kitzunu** [comment]
Open a new report using the proper bug report template instead.

**Comment by Bogir** [comment]
@Kitzunu many NPC-questgivers in world.creature_template had in field npcflag value "2" (QuestGiver). 
About 3-4 months ago somebody changed bitmask flag to 3 (1 = Gossip, 2 = QuestGiver) and broke quests.

**Comment by corsairs** [comment]
> Open a new report using the proper bug report template instead.

do it yourself I do not understand this.

**Comment by Bogir** [comment]
It was db_world update 2021_02_13_03.sql
@Kitzunu

**Comment by corsairs** [comment]
> @Kitzunu many NPC-questgivers in world.creature_template had in field npcflag value "2" (QuestGiver).
> About 3-4 months ago somebody changed bitmask flag to 3 (1 = Gossip, 2 = QuestGiver) and broke quests.

@Bogir I changed all the data in the database where the number 3 is in the npcflag section, it did not work.

**Comment by Bogir** [comment]
@corsairs 
It was db_world update 2021_02_13_03.sql
You can change npcflag from 3 to 2 for Questgivers

**Comment by corsairs** [comment]
> @corsairs
> It was db_world update 2021_02_13_03.sql
> You can change npcflag from 3 to 2 for Questgivers

And where to change it?
i changed directly in the database it didn't work and i can't find the file 2021_02_13_03.sql

**Comment by Bogir** [comment]
Delete Cache folder before each start of client

**Comment by corsairs** [comment]
@Bogir but where is this folder, I can not find it?

**Comment by Bogir** [comment]
ok, forget about it.
Test something else...

**Comment by corsairs** [comment]
> ok, forget about it.
> Test something else...

I cleared the client's cache does not work, the quest is not taken.
probably it's not just world.creature_template
