### ISSUE TITLE
Call of Water (Draenei Shaman) 5/6 - Not behaving Blizzlike

### ISSUE THREAD

**Issue by Mindary-Warlock** [azerothcore/azerothcore-wotlk#7139]
### Current Behaviour

There is still the Problem, that the spawning Waterelementals are not help killing Tel'athion... whereby it is nearly impossible to kill Tel'athion on your own if youre not at least a level 29+ Dreanei because of the high amount of damage Tel'athion is making. So i would say its very important to fix this quest as intendet.

Quest: https://wowgaming.altervista.org/aowow/?quest=9508

Moreover spawned Waterelementals do not despawn so after a while there are a bunch of unspawned waterelementals - doing noting.

I would like to relate here to the closed issue: https://github.com/azerothcore/azerothcore-wotlk/issues/4830

Thank you very much :-)

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=gd_7Wv9zHLc

### Source

ChromieCraft Server (26.07.2021)

### Steps to reproduce the problem

Create a shaman level 20 and try to finish the quest Call of Water 5/6 on your own - notice that it is not possible without the help of the waterelementals.

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@3d4befd

### Operating system

Ubuntu 20.04

**Comment by Shineslippers** [comment]
Original report: https://github.com/chromiecraft/chromiecraft/issues/810

The issue is confirmed. If you able to do damage to [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) right after spawn it could lead to stacked elementals.

https://user-images.githubusercontent.com/85256266/142323567-327b1d6a-29db-48d7-b9fa-cf7650c6f84f.mp4

![WoWScrnShot_111821_025842](https://user-images.githubusercontent.com/85256266/142323680-a2ab269f-3102-480e-90e4-72d93a79fb5d.jpg)

**Comment by savowe** [comment]
I confirm the issue on CC.
However, on a local installation of AC the quest seems to work as intended.

Spawn of nonattacking water elementals on CC:

https://user-images.githubusercontent.com/38558793/142769293-dab82856-d429-48cf-ba53-edcee8a2c96c.mp4

local running AC server (61c7488698d4) with attacking water elementals:

https://user-images.githubusercontent.com/38558793/142769336-03dea63a-eedb-4ed7-bc92-37c5d61b265f.mp4

**Comment by chennik** [comment]
<img width="959" alt="callofwater 1" src="https://user-images.githubusercontent.com/29061686/147740002-90b4afdf-8590-4196-bdee-72f1df5024f6.png">
elementals spawned before clicking barrel. 

i killed the elementals with hopes of new ones spawning after spawning telathion, they did spawn but just stood there not acting.
