### ISSUE TITLE
Quest accepted before [Accept] button pressed

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#7148]
### Current Behaviour

Quest accepted by clicking on it's name in gossip menu before [Accept] button was pressed
![изображение](https://user-images.githubusercontent.com/25766571/127157248-c35c3b41-9b7c-4501-8e0c-57bcc3827d18.png)

### Expected Blizzlike Behaviour

Quests must be accepted only if  [Accept] button pressed

### Steps to reproduce the problem

1. Create new character
2. cpme to any nearest QuestGiver and click on him
3. Click on any quest name. Quest automatically will be accepted

### AC rev. hash/commit

a8b858ec9283 from 2021-07-01
47f7c46f960 last rev.

### Operating system

Windows 7 x64

### Custom changes or Modules

-

**Comment by Philomathus** [comment]
That's intended behavior. In wotlk, quests in starting areas get accepted automatically.
