### ISSUE TITLE
You cannot take the starting quests of any race.

### ISSUE THREAD

**Issue by corsairs** [azerothcore/azerothcore-wotlk#7149]
### Current Behaviour

The quest cannot be taken or completed

### Expected Blizzlike Behaviour

Must accept the quest

### Steps to reproduce the problem

Create an initial character of any race and take the very first quest

### Extra Notes

Use the client WOW in the Russian version

### AC rev. hash/commit

no

### Operating system

Windows 10/7

**Comment by banehammer** [comment]
Not true. I can accept initial quests.... Please refer to your commit next time, and dont simply write "no"!

**Comment by Bogir** [comment]
Not confirm. Just tested today
https://github.com/azerothcore/azerothcore-wotlk/issues/7148

**Comment by T1ti** [comment]
Guys read the full issue : 
**_"Use the client WOW in the Russian version"_**

**Comment by Bogir** [comment]
> 
> 
> Guys read the full issue :
> **_"Use the client WOW in the Russian version"_**
1 min

**Comment by Bogir** [comment]
![изображение](https://user-images.githubusercontent.com/25766571/127193560-5617b7b6-e9af-4f4a-8c2e-29a83917cf49.png)

**Comment by Bogir** [comment]
Sometime it works. Sometime - no

**Comment by Kitzunu** [comment]
Add hash or commit. Else it will be closed.

**Comment by corsairs** [comment]
> Add hash or commit. Else it will be closed.

Disable auto-acceptance of the quest in the config and quests will not work for you

**Comment by Kitzunu** [comment]
Thats not what I asked for...

**Comment by banehammer** [comment]
I have read the complete Issue. I used the Russian Version and it still works. Also Disabled Auto-Acceptance and everything... :D

**Comment by Bogir** [comment]
Confirm. Quests are not accepted if `Quests.IgnoreAutoAccept = 1`

**Comment by Kitzunu** [comment]
Someone, either the one confirming or the author. Add the rev/hash. I will give it one more day before I close.
