### ISSUE TITLE
Raid bosses retain their auras after exiting combat

### ISSUE THREAD

**Issue by iyasenai** [azerothcore/azerothcore-wotlk#7153]
### Current Behaviour

Currently many raid bosses retain the auras gained in combat after exiting combat resulting in what can be seen in the video.
Please watch the complete video.
https://www.youtube.com/watch?v=hb2Tuv-blwI

### Expected Blizzlike Behaviour

Raid bosses must disappear briefly after exiting combat and clearing their auras.

### Source

https://www.youtube.com/watch?v=3kvpRJPGx8c  (3:21 ---> 3:30)
https://www.youtube.com/watch?v=-jWBa33m8FE ( 2:54 ---> 3:04)
https://www.youtube.com/watch?v=j3KvFCmmsqM (6:15 ---> 6:27)
https://www.youtube.com/watch?v=54ynIY7Ntwo (1:50 ---> 2:18)

### Steps to reproduce the problem

1. go to one of the bosses in the video.
2. wait for the boss to gain some aura.
3. to go out of combat or die.

### Extra Notes

When I reverted #6379 the raid bosses worked as usual.
Maybe reversing it for a while until a solution is found would be a good idea.

### AC rev. hash/commit

4332a7a

### Operating system

Windows 10 x64

### Custom changes or Modules

No.

**Comment by Krejza9** [comment]
Not reversing but rewriting it.

**Comment by bgcfb** [comment]
Yes,so I add code for these BOSS:

` void Reset() override
        {
            BossAI::Reset();
            events.Reset();
            summons.DespawnAll();
            /deleteAura
            me->RemoveAllAuras();
            //deleteAura
//.................
`

**Comment by Krejza9** [comment]
I've got that same fix ready, but it's on hold for now.
It is necessary to think what effect it will have on the boss who has an aura from the beginning.
For example, some shield that protects him before the raid starts.

**Comment by bgcfb** [comment]
> I've got that same fix ready, but it's on hold for now.
> It is necessary to think what effect it will have on the boss who has an aura from the beginning.
> For example, some shield that protects him before the raid starts.

I just fixed BOSS in Northrend
maexxna/sindragosa/sapphiron/fearlina

**Comment by Krejza9** [comment]
Yes, I know, but we'll have to release a fix for all bosses using positive auras.

**Comment by Krejza9** [comment]
I talked to @Hacki95 about this fix two days ago, but I'm afraid we'll need @Yehonal for some consultation.

**Comment by Kitzunu** [comment]
Make a pr and I will review

**Comment by Si1ker** [comment]
Expected Blizzlike Behaviour
Raid bosses must disappear briefly after exiting combat and clearing their auras.

Source
https://www.youtube.com/watch?v=3kvpRJPGx8c (3:21 ---> 3:30)

Iyasenai provided how the real fix should be, idk why going for "yee, ma' fix seems funny im gonna add RemoveAllAuras n.n "

**Comment by Krejza9** [comment]
nobody here is saying that the fix is wrong, it just needs to be checked

**Comment by FrancescoBorzi** [comment]
@sanctum32 can you please look into this?

**Comment by lyo3d** [comment]
Some ICC bosses are having the same behavior of sticking with the 3rd phase aura after wiping the band.
* Professor Putricide
* Blood Queen Lana'thel
* Sindragosa
---------------------------------------------------------------------------------------------------------------------------------------------
Core: I have the last update of the date 07/09/2021
---------------------------------------------------------------------------------------------------------------------------------------------
Modules: None, it is a core without any modules
---------------------------------------------------------------------------------------------------------------------------------------------
Sources: A short video of Professor Putricide's involvement
[https://youtu.be/ryamUUEQIoA](url)

**Comment by steenburgh** [comment]
It sounds like reverting #6379 fixes this. Which would be worse, reverting #6379 or leaving this issue until we can create a proper fix? There was some discussion of a proper fix a while ago, but we seem to have no concrete solution yet. IMO I'd like to revert #6379, and we can prepare a full blown fix later, as right now we're leaving a significant amount of endgame content broken, and #6379 was only a 2 line change so it'd be an easy revert. I'd be happy to make a PR to do so if I get the ok

**Comment by steenburgh** [comment]
As far as rewriting the fix for #6348, it looks to me like the reason the fix broke so many bosses is that those bosses rely on their self-cast auras being cleared when the boss enters evade mode before resetting. After seeing just how many creatures it negatively affected, I don't think the approach taken in the PR - making a system-wide behavioral change that affects all creatures - is one we should move forward with, as fully implementing it without breaking existing content it would also require us to review - and likely re-test - pretty much *every single scripted creature* which is not going to be easy. 

I'd instead recommend re-implementing #6379 in a way that does not affect existing scripted creatures. One way to do this might be to fix affected creatures 1-by-1 by adding the missing auras back on reset, but I'm not familiar enough with SmartAI to know if this is a reasonable ask

**Comment by Si1ker** [comment]
### Track this issue on https://github.com/azerothcore/azerothcore-wotlk/issues/7795
