### ISSUE TITLE
Accepting BG/RDF Summon While Flying Kills Hunter Pets

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7159]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1302

When i accept BG or RDF queue during flight, my pet appears dead.

Tester: Couldn't confirm for RDF as we have no way to set a debug mode for that. However, with .debug BG I could test BGs, and confirmed this. If you have a live hunter pet and are in flight when the BG queue pops, the pet will be dead when you spawn into the BG. Tried with both WSG and AB and they both did it. 

Rezzing;
![WoWScrnShot_072821_235222](https://user-images.githubusercontent.com/81782124/127340503-283de9e1-b5b0-460e-8698-abb5dae30040.jpg)

### Expected Blizzlike Behaviour

Pet is not dead

### Source

This isn't controversial.

### Steps to reproduce the problem

1. Check that pet is alive
2. Get to BG/RDF queue
2. Start flying to another town
3. Accept the queue
4. Voila -> pet is dead

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Wait a minute.
```
If you have a live hunter pet and are in flight
```
How the heck you got pet beside you in flight?

**Comment by UltraNix** [comment]
@Azcobu 
Wait a minute.
```
If you have a live hunter pet and are in flight
```
How the heck you got pet beside you in flight?

**Comment by UltraNix** [comment]
@Azcobu 
Cannot confirm it.
