### ISSUE TITLE
Holy Concentration (priest talent) Talent Bug

### ISSUE THREAD

**Issue by Szone** [azerothcore/azerothcore-wotlk#716]
**Description**: Holy Concentration (priest talent) 

**Current behaviour**: the restored hand is less than it should give

**Expected behaviour**: your mana regeneration from spirit is increased by 50% for 8 sec after you critically heal with flash heal, greater heal or empowered renew .

**Steps to reproduce the problem**:

1. Cast flash heal 
2. Talent must activate
3. And mana must regen 50% of character spirit

**Branch(es)**: master 

**AC hash/commit**: >AzerothCore rev. b8e5208e3380+ 2017-11-16 02:26:15 +0100 (master branch) (Unix, Release)

**Operating system**:  ubuntu server 16.04.3

**Modules**:  anticheat,transmog,reward,duelreset

**Other Customizations**: -
![capture](https://user-images.githubusercontent.com/2180820/33041696-e31e9190-ce47-11e7-84da-589c38ee7b18.PNG)

Thank you!

**Comment by talamortis** [comment]
on a level 20 priest without aura 
https://cdn.discordapp.com/attachments/217589275766685707/398616250110181431/unknown.png
with aura - so can not reproduce.
https://cdn.discordapp.com/attachments/217589275766685707/398616382905909248/unknown.png

**Comment by Szone** [comment]
I`ve checked now on last azerothcore revision and it is ok. Thank you! (issue can be closed)
