### ISSUE TITLE
NPC 'Olm the Wise' Spawning Multiple Times Concurrently

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7167]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1306

So i was running around felwoods and noticed an Olm The Wise rare in one part of the felwood overworld map and thought it was cool then as i went even further i saw a second one and a third and got confused i don't think there's supposed to be two rare mobs out at the same time, If at all. i was under the impression only one maybe be up at any given time. first time i seen this with my own eyes. screenshots provided below taken at the same time a few seconds apart. and another i just caught recently.

Tester: confirmed. Olm (ID 14343) has 3 spawns, 51897, 301303, and 301304. Checking the pool_creature table shows that none of the three are pooled as they should be:
```
mysql> SELECT * FROM pool_creature WHERE guid IN (51897, 301303, 301304);
Empty set (0.15 sec)
```

To correct this he needs 3 entries created in pool_creature linking these 3 spawns to a common pool ID, and then another entry in pool_template limiting the maximum spawn size of that pool to 1. The next available pool ID that is unused in either table is 365.

### Expected Blizzlike Behaviour

Only one rare of any specific rare is supposed to be up at any given time is what i assume is supposed to happen but i could be wrong i couldn't find anything about three rares of the same kind being up

### Source

This is not controversial.

### Steps to reproduce the problem

1. .go c 51897, 301303, or 301304

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
Yes, happened since https://github.com/azerothcore/azerothcore-wotlk/pull/7039 because i wanted to add more spawns to match the heat map of kills as the source said that he had multiple spawns.
I forget to increase the spawn time too, so i might fix it while im at it.
