### ISSUE TITLE
Core/Script: Strand of The Ancients - Ship Bug [$15]

### ISSUE THREAD

**Issue by Narcof** [azerothcore/azerothcore-wotlk#718]
**Description**: In the second round of Strand of Ancients one of the two ships does not start.
**Current behaviour**: In the second round the ship that should arrive to the green gate doesn't start to sail.

**Expected behaviour**: At the beginning of each round, every ship have to sail

**Steps to reproduce the problem**:

1.  Play Strand of The Ancients
2. Wait for the second round
3. Stay in the left ship ( that should arrive to green gate )
4. It doesn't start to sail

**Branch(es)**: Master

**AC hash/commit**:  d0af1c812bf4ea15204cad37b39ff27ff6bae339
Tested on 626630f0f68998d784c61fbb3779f292f97dc5a8 too

**Operating system**:  Linux 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51824080)](https://www.bountysource.com/issues/51824080-strand-of-the-ancients-ship-bug?utm_source=51824080&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Yehonal** [comment]
Can someone confirm it please?

**Comment by ShinDarth** [comment]
I don't know the exact steps to reproduce this issue, however it happened to me more than once when I was playing on trinitycore/azerothcore-based servers. So further investigations are indeed needed.

**Comment by talamortis** [comment]
Since there is two rounds in this battle ground which 1 causing the issue, is it just round 2?

**Comment by sucofog** [comment]
The problem here, is that our Vehicle system is way outdated, the players are not being correctly registered to the transports, transporte system needs a rewritte

**Comment by ShinDarth** [comment]
@Narcof are you sure that the steps that you mentioned **always** reproduce the issue? We need to know the exact sequence that systematically leads to this bug in order to locate it in the code.

**Comment by Narcof** [comment]
@ShinDarth I've tried this bug 5 times, always in the 2 round. The steps always reproduced that bug

**Comment by Irome** [comment]
I confirm, I never saw that ship arrive at the second round.

**Comment by talamortis** [comment]
Ok can anyone tell if its faction specific ?

**Comment by sucofog** [comment]
It's not faction related @talamortis

**Comment by Yehonal** [comment]
https://github.com/raczman/TrinityCore/commit/2887864dc96178c8583aaef46acdc2e61e4fbc65

**Comment by Yehonal** [comment]
imported this fix: https://github.com/azerothcore/azerothcore-wotlk/commit/300847920a2d1c0549659cdb4d15fb382142c931

but unfortunately it doesn't solve this issue, i'll investigate better

**Comment by Yehonal** [comment]
Moreover it happened to me at first round at battleground start

So i think it's randomic (?)

**Comment by pklloveyou** [comment]
Sunwell 测试一个小时 没有这个问题  两条船都是同时到达
There was no problem with testing for one hour. Both boats arrived at the same time
Windows 7/64

![image](https://user-images.githubusercontent.com/18535853/34105525-976e742e-e42f-11e7-8ff1-e6e23b66af82.png)


![image](https://user-images.githubusercontent.com/18535853/34105590-e13ed9d6-e42f-11e7-848d-ffe55d55b406.png)

**Comment by ShinDarth** [comment]
@pklloveyou what is the version of your server when you did the test?

**Comment by pklloveyou** [comment]
@ShinDarth Sunwellcore

**Comment by ShinDarth** [comment]
@pklloveyou can you test it on AzerothCore?

**Comment by pklloveyou** [comment]
@ShinDarth I'll give it a try   I compare to find the possible problems

**Comment by ShinDarth** [comment]
@pklloveyou  thanks a lot

**Comment by pklloveyou** [comment]
@ShinDarth Very strange two code is not bad word,
This passage is a translator translator I poor in English do not know if you can understand

**Comment by ShinDarth** [comment]
@pklloveyou thanks for your help, so does it work on AzerothCore for you or not?

**Comment by pklloveyou** [comment]
@ShinDarth Yes, I translated successfully! The same code word is not bad.

**Comment by Inifield** [comment]
您是否使用了内核而不进行任何修改？

**Comment by pklloveyou** [comment]
@Inifield AZ BattlegroundSA.cpp BattlegroundSA.h and Sunwell BattlegroundSA.cpp BattlegroundSA.h same!same!same! Three important things to say HOHO!

**Comment by sucofog** [comment]
I don't understand chinese xD

**Comment by talamortis** [comment]
is this intermittent as I've test like 10 times and seems to be working fine.

**Comment by Gargarensis** [comment]
Tested also by me on 4158d2a0d8a38286eb3c4ff38e147a99252f6f07 and it seems to work at the moment.. there are other conditions to met in order to reproduce the bug?

**Comment by Narcof** [comment]
Look this screenshot, made by Narcof in 21/01/2018 on 84949746e1d0dcbfaca2108024b17a044a9ef8b9  @Gargarensis 
see this 
![2018-01-21 3](https://user-images.githubusercontent.com/32717748/35197654-9c2350b6-fee2-11e7-9eb6-be0165a00e53.png)

**Comment by Viste** [comment]
@Narcof  when you test something, do it from player account! GM account can make a random bugs on bg or instance and with some quest to

**Comment by Narcof** [comment]
This ( 84949746e1d0dcbfaca2108024b17a044a9ef8b9 ) is a test server, we can use GM spells
I can only test this bug on 84949746e1d0dcbfaca2108024b17a044a9ef8b9 because in our main server SOTA is closed

**Comment by talamortis** [comment]
Issue don't seem to happen on windows going to compile on Linux vps see if i still run into the same problem

**Comment by Gargarensis** [comment]
The important thing is that you are gm and dev off, then it does not (often) really matter if you are using gm commands.
Let us know @talamortis, I only tested it on windows actually.

**Comment by Maurowin** [comment]
hello, look here, in TC some player said they have a little bugs and others said no. i don't know dev and read correctly a code.
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Battlegrounds/Zones/BattlegroundSA.h
and
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp

**Comment by Deku** [comment]
I haven't get this issue reported in our live server (100 players average). I think that the steps to reproduce the error are too generic, maybe specify number of members per team? types of accounts used (GM/player)?  etc.

For the moment, I can't confirm this issue.

**Comment by FrancescoBorzi** [comment]
Has anyone been able to reproduce this issue recently? I think this issue might still be there but it's very hard to reproduce
