### ISSUE TITLE
Feature: Help for Change [Autobroadcast] Text

### ISSUE THREAD

**Issue by Kingswow** [azerothcore/azerothcore-wotlk#7192]
### Describe your feature request or suggestion in detail

hi guys , i need help , how can i change [Autobroadcast] text ? 
sry for my bad english pls see picture for more, thank you

![broad-cast](https://user-images.githubusercontent.com/150390/127746010-ae94d4da-e6e0-410c-ac89-c1ccc7f4fc32.jpg)

[https://s19.picofile.com/file/8438776526/broad_cast.jpg](url)

**Comment by Kitzunu** [comment]
SELECT * FROM acore_string WHERE content_default LIKE '%Autobroadcast%'

Entry 11000
