### ISSUE TITLE
Culling of Stratholme Instance

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#72]
Ive noticed a few problems with this instance, as Uther enters Culling of Stratholme he attack around 5 people before he starts the Senario, Then as he goes through the secrect passage way to the next part He runs and attacks a few more zombies, Uther casts exorcism to many times (tested on heroic mode) and when you stop for a rest you are not at the correct point.

**Comment by talamortis** [comment]
ive fixed this.

Update Creature_template where ID= 28341, 28169 
Set faction = 190

That should fix the start enternce
------------------------------------------------------------------------------------

Update script_waypoint where entry = 26499 & pointid = 47
set location_x = 2512.36, location_y = 1325.44, location_z = 131.915

that will fix the resting point in the firehall.
-------

**Comment by ShinDarth** [comment]
Missing core rev, please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
