### ISSUE TITLE
 ERROR: Unit::HandleDummyAuraProc: Spell 58642

### ISSUE THREAD

**Issue by Nemepy** [azerothcore/azerothcore-wotlk#720]
**Description**:
Segmentantion fault after
2017-11-24 12:56:59 ERROR: Unit::HandleDummyAuraProc: Spell 58642 has non-existing triggered spell 4294967295

**Current behaviour**: Tell us what happens
Server crash

**Expected behaviour**: Tell us what should happen instead
Server dont crash :)
**Steps to reproduce the problem**:
I found servers go down check log i found
2017-11-24 12:56:59 ERROR: Unit::HandleDummyAuraProc: Spell 58642 has non-existing triggered spell 4294967295
Segmentation fault.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
Last core 22/11/17

**AC hash/commit**:   37e9160

**Operating system**:  
Debian 9
**Modules**:  Are you using modules? if yes, list them
premium, duelreset
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
no customization

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
can you please fill in your `AC hash/commit:`  ?

**Comment by Sdyessdev** [comment]
Are you sure it went down after that message? Or maybe just happened to be the last message it recorded in the log before it crashed? Any other time stamps?

**Comment by lineagedr** [comment]
Linux issue?

**Comment by Nemepy** [comment]
yes it was the last message in console windows. and in logs.debian 9


2017-11-24 15:21 GMT-03:00 lineagedr <notifications@github.com>:

**Comment by Yehonal** [comment]
You must provide a crash dump, console error are not always usefull

**Comment by talamortis** [comment]
Closing issue unless crash dump can be provided.

**Comment by Nefertumm** [comment]
He didn't provide the crash dump. Close this thread. :)
