### ISSUE TITLE
Various Tanaris NPCs Giving Incorrect Gadgetzan Reputation

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7207]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1321

[Listed NPCs](https://wowgaming.altervista.org/aowow/?npcs&filter=cr=42;crs=369;crv=0;na=Wastewander) granting incorrect amount of reputation on kill.

Tester: confirmed. Checking the DB shows a number of Tanaris NPCs giving incorrect Gadgetzan rep:

- Andre Firebeard - 25, correct
- Caliph Scorpidsting - gives 25, should be 15 stopping at Honored - [source](https://tbc.wowhead.com/npc=7847/caliph-scorpidsting)
- Wastewander NPCs - gives 10, should be 5, stopping at Friendly - [source](https://tbc.wowhead.com/npc=5618/wastewander-bandit)
- Baron Longshore - 25 Ratchet, 12.5 Gadget - correct
- Southsea Dock Worker, Freebooter, Pirate, Swashbuckler - gives 5 Gadget, correct

Note that all rewards should be halved and given to the rest of the Steamwheedle cities as well. So for example, Wastewanders should give 2.5 rep to Booty Bay, Everlook, and Ratchet as well.

### Expected Blizzlike Behaviour

Reputation of Wastewander NPCs should be +5 (Gadgetzan) and +2.5 (Booty Bay, Everlook, Ratchet) for non Humans.

### Source

[Source](https://wowwiki-archive.fandom.com/wiki/Mobs_which_affect_reputation_with_Steamwheedle_Cartel#:~:text=on%20vendor%20purchases.-,Gadgetzan,-Mobs%20killable%20for)
![wastewander-rep](https://user-images.githubusercontent.com/81782124/127870998-7ca66bf3-5146-449a-9091-51f9e5e70ccb.PNG)

This is backed by TBC Wowhead which lists the same rep rewards for each NPC, for example [Wastewander Bandit](https://tbc.wowhead.com/npc=5618/wastewander-bandit)

There is a slight constradiction in Wowpedia's page [here](https://wowpedia.fandom.com/wiki/Wastewander?oldid=2395162) that contains this figure:
![wastewander-rep-wowpedia](https://user-images.githubusercontent.com/81782124/127871607-d9df53ff-5b70-4cc0-bed6-8aa9642b90d4.PNG)

This shows 5 rep as well, but continuing through Honored and stopping at Revered. This contradicts WowWiki and Wowhead, so can only guess it's an error, as I haven't found any evidence of patches changing this rep.

### Steps to reproduce the problem

Kill NPCs and check out gained reputation.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
I found an old WotLK video for the [Southsea Pirates](https://youtu.be/nGx44JFvd8k?t=83). Unfortunately, we don't know, what his reputation with Gadgetzan is, but the video basically confirms the rest of the table from Wowhead.

What I found even more interesting is, that the 2.5 rep for Ratchet, Booty Bay & Everlook is sometimes 2 and sometimes 3 rep in the video. I didn't know this, but 2.5 rep seems to be a 50% chance for 2 rep and 50% chance for 3 rep.

**Comment by Shineslippers** [comment]
No, no, no. It's not a random you can see rotation. Kill +2, next kill +3, then again 2. So it's how the game is counting 2.5

**Comment by Azcobu** [comment]
One inconsistency I've noticed while fixing this in the DB is that Wowhead says rep gain from Wastewanders stops at Friendly (which to be as clear as poossible, I take to mean rep stops when going from Neutral to Friendly.) Whereas WowWiki says it continues through Friendly and stops at Honoured. Not to mention Wowpedia claiming it goes through Honoured as well and stops at Revered. Not sure which to believe at this point, although Wowhead at least appears to be a modern source. 

Also found a quote from Wrath-era WH - "note that gadgetzan rep isn't issued if you are friendly or above with them" ([source](https://www.wowhead.com/npc=5616/wastewander-thief#comments:id=777480)) which seems to confirm Wowhead as being correct.
