### ISSUE TITLE
Overlapping entries in guards gossip menu (locale Client)

### ISSUE THREAD

**Issue by staircrusher** [azerothcore/azerothcore-wotlk#7209]
### Current Behaviour

When a guard is asked for directions, some overlapping entries without text are displayed in the gossip menu:

![grafik](https://user-images.githubusercontent.com/3681763/127879038-99efa7ad-9075-4139-a600-64e397abeb04.png)

### Expected Blizzlike Behaviour

Entries should not overlapp:

![grafik](https://user-images.githubusercontent.com/3681763/127882112-42954c81-f2a8-4187-80e4-eed25f38e50b.png)

### Steps to reproduce the problem

1. Go to any city and ask any guard

### Extra Notes

Client: deDE

### AC rev. hash/commit

AzerothCore rev. 498e01e7fcb4+ 2021-07-29 12:18:36 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1j  16 Feb 2021 (library: OpenSSL 1.1.1j  16 Feb 2021)
Using Boost version: 1.74.0
Using MySQL version: 100510
Using CMake version: 3.18.4
Compiled on: Linux 5.11.0-25-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/gameserver/azeroth-server/Data/maps. Total size: 252191207 bytes
vmaps directory located in /home/gameserver/azeroth-server/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/gameserver/azeroth-server/Data/mmaps. Total size: 2196365052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS deDE
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_29_04
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Ubuntu 21.04 x64

### Custom changes or Modules

mod-ah-bot
mod-autobalance
mod-new-character-perks
mod-pocket-portal (https://github.com/milestorme/mod-pocket-portal)
mod-solo-lfg (https://github.com/milestorme/mod-solo-lfg)

Custom changes for mod-solo-lfg:
/src/server/game/DungeonFinding/LFGMgr.cpp
/src/server/game/DungeonFinding/LFGMgr.h
/src/server/game/DungeonFinding/LFGQueue.cpp

**Comment by staircrusher** [comment]
I checked the database for missing entries, but it seems ok after running this query:
`SELECT a.MenuID, a.OptionID, a.OptionText, b.OptionText
FROM gossip_menu_option a LEFT JOIN gossip_menu_option_locale b ON (a.MenuID = b.MenuID AND a.OptionID = b.OptionID AND b.Locale = "deDE")
WHERE a.MenuID IN (Select MenuID FROM gossip_menu_option WHERE OptionText LIKE "Class Trainer")
;`

**Comment by Seigneur-fantome** [comment]
when it's update and fixed? :o

**Comment by FrancescoBorzi** [comment]
@Seigneur-fantome when someone provides a fix for it :) you can speed it up by [placing a bounty on it](http://www.azerothcore.org/wiki/Bountysource)

**Comment by LukasVolgger** [comment]
I'm already working on it. Give me some time

**Comment by LukasVolgger** [comment]
DB in GMO 1951 and others is fine! All entries are there, sonething else except the db is wrong

**Comment by Siid9741** [comment]
the problem is also present with the gossip frFR 
![image](https://user-images.githubusercontent.com/65017695/136656976-370231b5-d5f8-42c1-9ae2-b1910e7e4784.png)

**Comment by patou01** [comment]
For what I have found so far, the text simply is not present on the creatures, so they're sending empty text. I'll dig further into how that text is passed to the npcs... Either it's not loaded from the db (special characters somewhere maybe?) or it gets lost along the way

**Comment by patou01** [comment]
If I add the following in the code:
![image](https://user-images.githubusercontent.com/2592673/136671210-b7b6c475-6621-4145-b43b-e373de85b058.png)

I get 
![image](https://user-images.githubusercontent.com/2592673/136671215-191f4b6a-afdd-45fe-a734-59ddb28417c3.png)


I think an extra ward is needed above to make the `if(locale != DEFAULT_LOCALE)` an else statement of the whole thing above. But I need to look into that broadcast thingy to see what it's trying to fetch. 

It looks like we're able fetching something from the `broadcast_text_locale` but it is empty. Adding this bit in line ~170 in playergossip 
![image](https://user-images.githubusercontent.com/2592673/136671444-ede66aae-0fdc-455a-ac91-257ce0a23593.png)

results in
![image](https://user-images.githubusercontent.com/2592673/136671472-c34ea927-1a31-465b-a567-4a47cc9215e0.png)


So.... looking for these entries in the database:
`SELECT * FROM `broadcast_text` WHERE `ID` IN (4888, 6720, 80000, 4893, 80001, 80002, 80003, 80004, 8521, 80005, 80006, 45376, 6792, 6793, 32998);`
![image](https://user-images.githubusercontent.com/2592673/136671522-0c7031ad-20d8-420c-ba68-b2e682b46ef3.png)

and in locale (with extra filter to frFR)
![image](https://user-images.githubusercontent.com/2592673/136671541-90d0cba3-eea9-490c-914b-fc38e601ca6b.png)


So there's several things:

- Entries are missing in the broadcast_text_locale,
- or they are not where they should,
- or we are not looking at the right place and the core needs some fixing to search for the right entry instead


@LukasVolgger , feedback appreciated if you know how these tables are structured and how we try to work with them.
