### ISSUE TITLE
Having a timed quest in you test log will "lock out" other times quests

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7214]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1003 Credit to Roboto for figuring it out.

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
You cannot accept a quest that has a timer if you already have a quest with a timer in your quest log, whether you completed/failed said quest or not. No notice is given and is causing invalid bug reports such as the initial one linked.

### Expected Blizzlike Behaviour

After some extensive searching from multiple triage people over on CC. We don't know what is blizzlike when accepting multiple timed quests, and thats why it's taken so long to get this linked. It was decided just to present what we have with our solution ideas. Either multiple quest timers should work together, or only one works at a time and an error pops up in red letters saying "You are already on a timed quest!" when the player tries to accept another timed quest. I think Azcobu put it best- A fix of some kind, even if we can't prove it's Blizz-like, is still better than silently failing and blocking the quest as it does now.

### Steps to reproduce the problem

Again Credit to Roboto:

* Create an alliance character
* `.char level 30`
* `.go c id 2696`
* Verify that the NPC gives the quest "MacKreel's Moonshine" (quest with a timer), but don't take it
* `.q add 257` (another quest with timer)
* The NPC doesn't give the quest anymore

### Extra Notes

N/A

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Blizzlike - you can have only one timed quest.
