### ISSUE TITLE
[Westfall] Defias Pillager's melee swings come instantly after his fireball cast

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7216]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: [Chromie issue#1320](https://github.com/chromiecraft/chromiecraft/issues/1320)

When the Defias Pillager finishes its cast it does a auto attack straight after.

### Expected Blizzlike Behaviour

there should be a delay before auto attack happens.

### Steps to reproduce the problem

Just get in a fight with the Defias Pillager

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC(15013d2).
The melee swing after his cast should take the attackspeed of his staff into account.

https://user-images.githubusercontent.com/68868567/127992742-034f236a-9c25-4760-86fb-2dd34e0382c5.mp4

**Comment by syssneck** [comment]
This issue is probably related to: [the bug that allows the abuse of staff + wand switch](https://github.com/azerothcore/azerothcore-wotlk/issues/7074)

**Comment by T1ti** [comment]
That's an issue with msot spells afaik, it works the same way for players

**Comment by UltraNix** [comment]
This one is not a bug.

**Comment by T1ti** [comment]
> This one is not a bug.

wrong, it is a bug
I recorded on classic, spells are supposed to reset swing timer, it's pretty common knowledge
https://streamable.com/qgzxjz

**Comment by UltraNix** [comment]
@T1ti So what about https://github.com/azerothcore/azerothcore-wotlk/issues/8899 this one?
