### ISSUE TITLE
Hunter's beast heart talent spell (34692) error

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#7217]
### Current Behaviour

The hunter uses the beast heart talent spell (34692), uses the spell 19574 to view the character change, safely exits the game, re-enter the game, uses the spell 19574 to view the character change, and you will find that the talent spell (34692) has no effect. Switch to the second talent, switch to the first talent again, and you will find that the talent spell (34692) works.

### Expected Blizzlike Behaviour

Talent spell (34692), should always be effective.

### Steps to reproduce the problem

The hunter uses the beast heart talent spell (34692), uses the spell 19574 to view the character change, safely exits the game, re-enter the game, uses the spell 19574 to view the character change, and you will find that the talent spell (34692) has no effect. Switch to the second talent, switch to the first talent again, and you will find that the talent spell (34692) works.

### AC rev. hash/commit

15013d2

### Operating system

win10 x64

**Comment by UltraNix** [comment]
I can't reproduce it. Everytime works okay.
