### ISSUE TITLE
Feature: allow defining riding skill-based mounts through the database

### ISSUE THREAD

**Issue by cthu1hoo** [azerothcore/azerothcore-wotlk#7219]
I was trying to add a custom mount which "changes based on your riding skill" and apparently a fixed list of those (with hardcoded spell IDs) is defined in `spell_generic.cpp`.

In my opinion, adding a database lookup for linked spell Ids in this situation would provide a better approach without a need to recompile world server for every new adaptive mount which server operator might want to add. 

I suppose one new database table would be needed which defines relationship between main dummy mount spell and linked spells defined for each riding skill, and a database lookup implemented when mounting.

Additionally, in my opinion, considering all 310% mount spells as adaptive, would also be useful behavior, optionally, to prevent making all those spells for every mount.

**Comment by Krejza9** [comment]
this is a case that does not fit with the core implementation but with the module
https://github.com/azerothcore/skeleton-module

**Comment by cthu1hoo** [comment]
Thanks, I forgot about modules. Can you tell me if I'm thinking in the right direction here, overall?

- Module adds a spell script which does the choosing based on whatever criteria (either database lookup or, for example, algorithmic based on spell ID sequences, etc.)
- Spell script is assigned to the dummy mount spell in the database (`spell_script_names` table)
- When spell is cast by player, script runs, and casts correct mount spell instead

Sorry if its the wrong place to ask.

**Comment by cthu1hoo** [comment]
In the end, I didn't want to add multiple spells for each mount, so I used a different approach, which was good enough for me, I'm going to link it here in case someone else finds it useful: https://github.com/cthu1hoo/mod-mount-autoselect
