### ISSUE TITLE
Instance Reset Crashes the server

### ISSUE THREAD

**Issue by Middel** [azerothcore/azerothcore-wotlk#723]
**Description**: Have to say that when you play one instance, and you reset that instance without having done multiple it won't crash the server. however if you for example do The Forge of Souls, then Pit of Saron then Halls of reflection, and after you want to do Forge of Souls again, and you reset the instance it freezes the server or crashes it. (now i've noticed this doesn't always happen) however it does most of the time.

**Current behaviour**: Resetting instances when done multiple crashes the server.

**Expected behaviour**: it shouldn't crash the server.

**Steps to reproduce the problem**:

1. Do multiple instances. (for example the 3 icecrown citadel dungeon)
2. Right click your portrait.
3. Click Reset all instances.

**Branch(es)**: Master branche 

**AC hash/commit**:   -37e9160e88b4- <-Revision

**Operating system**:  Windows 7

**Modules**:  using the following modules - NPC Giftbox, NPC Gambling, Transmorg NPC, Spells mod.

**Other Customizations**: no

Crash Report right here: https://gist.github.com/Middel/0f29d68ab010a819d0118d3b391d66cb
[crashdump.zip](https://github.com/azerothcore/azerothcore-wotlk/files/1506413/crashdump.zip)

**Comment by sucofog** [comment]
Not under Unix

**Comment by Middel** [comment]
Since Azeroth Core supports both Linux/Unix and Windows i assume. i'm allowed to make a issue report based on Windows as well.

**Comment by ShinDarth** [comment]
@Middel yes of course. The comment of @sucofog is useful to determine that this bug is windows-only, which helps the developer but it does not mean that's less important to be fixed.

**Comment by STARRHELD** [comment]
I would like to have someone without all of the modules to test if it's crashing on Windows still.

**Comment by Middel** [comment]
since not any off those modules have anything to do with instances. i assume it does. plus i delivered the crashlog and crashdump. file i'm sure you can find the answer as to why it crashes in there.

**Comment by Kaev** [comment]
Cannot confirm on Windows. Cleared all 3 instances and resetted afterwards and did this ~10 times in a row. Never had any issue.

**Comment by Middel** [comment]
then perhaps is someone able to look through the crashlog / crashdump?, and tell me what is going on? since i can't read it. but i would love to know the reason for the crash so i can do something about it.

**Comment by talamortis** [comment]
your crash log is incorrect it looks like you have compiled in release use debug then supply the crash log

**Comment by Kaev** [comment]
I tried to load your crashdump in Visual Studio but it's an older, not supported version. Not sure if it is because of Windows 10 or because of Visual Studio 2017.

**Comment by STARRHELD** [comment]
```CODE

Dump Summary
------------
Dump File:	37e9160e88b4_worldserver.exe_[26-11_19-44-13].dmp : C:\Users\Kevin Starrheld\AppData\Local\Temp\Rar$DIa5260.10020\37e9160e88b4_worldserver.exe_[26-11_19-44-13].dmp
Last Write Time:	26/11/2017 19:44:13
Process Name:	worldserver.exe : C:\TheReunionReborn\worldserver.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Not Present

System Information
------------------
OS Version:	6.1.7601
CLR Version(s):	

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
worldserver.exe	C:\TheReunionReborn\worldserver.exe	0.0.0.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.1.7601.18247
kernel32.dll	C:\Windows\System32\kernel32.dll	6.1.7601.18409
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.1.7601.18409
libmysql.dll	C:\TheReunionReborn\libmysql.dll	5.5.38.0
secur32.dll	C:\Windows\System32\secur32.dll	6.1.7601.18741
sspicli.dll	C:\Windows\System32\sspicli.dll	6.1.7601.18741
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.7601.17744
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.1.7601.18532
advapi32.dll	C:\Windows\System32\advapi32.dll	6.1.7601.18247
sechost.dll	C:\Windows\System32\sechost.dll	6.1.7600.16385
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.1.7601.17514
nsi.dll	C:\Windows\System32\nsi.dll	6.1.7600.16385
libeay32.dll	C:\TheReunionReborn\libeay32.dll	1.0.2.13
gdi32.dll	C:\Windows\System32\gdi32.dll	6.1.7601.18577
user32.dll	C:\Windows\System32\user32.dll	6.1.7601.17514
lpk.dll	C:\Windows\System32\lpk.dll	6.1.7601.18177
usp10.dll	C:\Windows\System32\usp10.dll	1.626.7601.18454
msvcr120.dll	C:\Windows\System32\msvcr120.dll	12.0.40649.5
ace.dll	C:\TheReunionReborn\ace.dll	0.0.0.0
mswsock.dll	C:\Windows\System32\mswsock.dll	6.1.7601.18254
IPHLPAPI.DLL	C:\Windows\System32\IPHLPAPI.DLL	6.1.7601.17514
winnsi.dll	C:\Windows\System32\winnsi.dll	6.1.7600.16385
netapi32.dll	C:\Windows\System32\netapi32.dll	6.1.7601.17887
netutils.dll	C:\Windows\System32\netutils.dll	6.1.7601.17514
srvcli.dll	C:\Windows\System32\srvcli.dll	6.1.7601.17514
wkscli.dll	C:\Windows\System32\wkscli.dll	6.1.7601.17514
MSVCP140D.dll	C:\Windows\System32\MSVCP140D.dll	14.11.25325.0
VCRUNTIME140D.dll	C:\Windows\System32\VCRUNTIME140D.dll	14.11.25325.0
ucrtbased.dll	C:\Windows\System32\ucrtbased.dll	10.0.16299.15
api-ms-win-core-localization-l1-2-0.dll	C:\Windows\System32\api-ms-win-core-localization-l1-2-0.dll	10.0.10240.16390
api-ms-win-core-processthreads-l1-1-1.dll	C:\Windows\System32\api-ms-win-core-processthreads-l1-1-1.dll	10.0.10240.16390
api-ms-win-core-file-l1-2-0.dll	C:\Windows\System32\api-ms-win-core-file-l1-2-0.dll	10.0.10240.16390
api-ms-win-core-timezone-l1-1-0.dll	C:\Windows\System32\api-ms-win-core-timezone-l1-1-0.dll	10.0.10240.16390
api-ms-win-core-file-l2-1-0.dll	C:\Windows\System32\api-ms-win-core-file-l2-1-0.dll	10.0.10240.16390
api-ms-win-core-synch-l1-2-0.dll	C:\Windows\System32\api-ms-win-core-synch-l1-2-0.dll	10.0.10240.16390
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.1.7601.17514
imm32.dll	C:\Windows\System32\imm32.dll	6.1.7600.16385
msctf.dll	C:\Windows\System32\msctf.dll	6.1.7600.16385
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.1.7601.18741
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.1.7600.16385
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.1.7600.16385
nlaapi.dll	C:\Windows\System32\nlaapi.dll	6.1.7601.17964
NapiNSP.dll	C:\Windows\System32\NapiNSP.dll	6.1.7600.16385
pnrpnsp.dll	C:\Windows\System32\pnrpnsp.dll	6.1.7600.16385
dnsapi.dll	C:\Windows\System32\dnsapi.dll	6.1.7601.17570
winrnr.dll	C:\Windows\System32\winrnr.dll	6.1.7600.16385
WLIDNSP.DLL	C:\Program Files\Common Files\Microsoft Shared\Windows Live\WLIDNSP.DLL	7.250.4311.0
psapi.dll	C:\Windows\System32\psapi.dll	6.1.7600.16385
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.1.7601.17514
rasadhlp.dll	C:\Windows\System32\rasadhlp.dll	6.1.7600.16385
WSHTCPIP.DLL	C:\Windows\System32\WSHTCPIP.DLL	6.1.7600.16385
FWPUCLNT.DLL	C:\Windows\System32\FWPUCLNT.DLL	6.1.7601.18283
powrprof.dll	C:\Windows\System32\powrprof.dll	6.1.7600.16385
setupapi.dll	C:\Windows\System32\setupapi.dll	6.1.7601.17514
cfgmgr32.dll	C:\Windows\System32\cfgmgr32.dll	6.1.7601.17514
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.1.7601.18640
ole32.dll	C:\Windows\System32\ole32.dll	6.1.7601.17514
devobj.dll	C:\Windows\System32\devobj.dll	6.1.7600.16385
```

**Comment by Middel** [comment]
@STARRHELD thank you for attempting to help me.

Could you please be so kind to explain me what that means if you can and want? that would be greatly appreciated. and is there maybe like a sorta website where i can get to know more about these type of codes? so for the future i can try to find out myself so that i won't have to waste the time of you people. i'm sorry for wasting your time if it does... (english isn't my first language, i hope i'm clear in what i mean)

**Comment by Middel** [comment]
also @talamortis sorry i didn't see your reaction before. otherwise i would have responded sooner. but the core is not compiled in Release. it is using the Debug already.

**Comment by Middel** [comment]
nobody able to explain me how i can fix whatever the CrashDump said?

**Comment by Rochet2** [comment]
> nobody able to explain me how i can fix whatever the CrashDump said?

When compiling in debug mode .pdb files are created. Did you have them in your server folder when you ran the core and crashed? They should be there.

**Comment by Middel** [comment]
@Rochet2 no i did not had those file in the actual folder where the core is run from...... (i feel so retarded now) i have them in there now though, so the next time the server crashes because of this issue. i'll deliver a good dump file.

**Comment by talamortis** [comment]
ill close the issue till then.
