### ISSUE TITLE
Stormstrike and Lava Lash consume flurry stacks

### ISSUE THREAD

**Issue by Theblomb** [azerothcore/azerothcore-wotlk#7237]
### Current Behaviour

The two melee abilities stormstrike and lava lash both currently consume flurry stacks
Stormstrike consumes two stacks and lava lash consumes one

### Expected Blizzlike Behaviour

Auto attack melee swings is the only thing that should consume flurry stacks

### Source

www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137804-guide-enhancment-shaman.html
Under the stormstrike section

### Steps to reproduce the problem

1. Proc flurry from a critical strike
2. Use stormstrike or lava lash (make sure it doesn't crit)
3. See your flurry stacks disappear into the void

### AC rev. hash/commit

What?

### Operating system

Windows 7

**Comment by T1ti** [comment]
Your source is from Burning crusade.

**Comment by Theblomb** [comment]
I don't see why it would have changed. Having an attack speed increase stacks get consumed by abilities that don't care about attack speed does not seem right.

**Comment by Kitzunu** [comment]
Add Has/Commit

**Comment by Theblomb** [comment]
I don't know how, never used this before.

**Comment by FrancescoBorzi** [comment]
@Theblomb it's the version of AC you're using, you can copy-paste it from the output of `server info` or get it using tools like Keira3
