### ISSUE TITLE
Master's Call not removing Roots if the pet is rooted aswell

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#7239]
### Current Behaviour

Hunter ability Master's Call is not removing freeze effects such as frost nova, entangling roots if both the Hunter and the Pet are frozen. The pet gets out of nova and ''charges'' to the hunter, but does not remove the hunter freeze.

It, however, removes the Hunter freeze effect if only the Hunter is being affected by a root effect.

### Expected Blizzlike Behaviour

Master's Call should always remove Hunter's nova if both the pet and the hunter are affected by Freeze/root spells.

### Steps to reproduce the problem

Step 1. Create a mage and get near a hunter and his pet
Step 2. Cast Frost Nova
Step 3. Use Master's Call

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

**Comment by FrancescoBorzi** [comment]
@laasker do you have your own AC running locally?

**Comment by laasker** [comment]
> @laasker do you have your own AC running locally?

Yes sir, i do

**Comment by laasker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/7294 has fixed this issue.

**Comment by Kitzunu** [comment]
Do not close before a PR has been merged.
