### ISSUE TITLE
Temporary pets doesn't save autocast toggle spells

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#7263]
### Current Behaviour

Temporary pets that have a pet bar such as Water Elemental, Shadowfiend, Feral Spirit, Force of Nature are not saving the spells if you toggle/untoggle autocast or change pet state (follow, stay, agressive, passive, etc).

This only happens to temporary/guardian pets, normal pets does not have this problem.

### Expected Blizzlike Behaviour

All pets should save the bars if you toggle autocast or change spell positions of pet bar.

### Steps to reproduce the problem

1. Create a shaman, and spend points on enhancement build till you have Feral Spirit
2. Use Feral Spirit and untoggle autocast of spells and change to passive
3. Dismiss pets
4. Reset Feral Spirit cooldown (.cooldown on yourself)
5. use Feral Spirit again and look at the pet bar

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
No. Temporary pets should not save its pet bars.
