### ISSUE TITLE
Ghostlands - Dar'Khan Clipping/Pathing Issues

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7268]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1363

Killing the enemy Dar'Khan for the Ghostlands quest "The Traitor's Destruction" is complicated by him running through the wall to his immediate left if you do not stay within melee range of him. Attempting to kite him around his room and using LOS to stop his Shadowbolt casting will result in him running through a wall or up into the ceiling and onto a different floor. He will then be in proximity to other enemies hostile to the player yet he does not end up pulling them to the player. Being a Paladin I had to run behind the railing immediately to your left as you enter his room, pop out and run over to the wall he goes into, cast Consecration, and run back behind the railing. Dar'Khan would then run back through the wall, take ~5% damage total HP from the Consecration and I had to rinse and repeat until he died.

Tester: confirmed, Dar'Khan is clipping through the rear wall pretty frequently.

Demo at 2x speed:

https://user-images.githubusercontent.com/81782124/128718174-ff9d027b-2a3d-4025-a592-45eb6aca45c4.mp4

### Expected Blizzlike Behaviour

Dar'Khan does not run through walls or other level geometry. Enemy engages the player in combat and respects normal LOS rules.

### Source

This is not controversial.

### Steps to reproduce the problem

1. .go c 84102
2. Engage Dar'Khan in combat.
3. Run behind the railing immediately to your left after entering his room while still in combat with him.
4. Witness Dar'Khan's true form of wall.

### Extra Notes

https://wotlkdb.com/?quest=9167

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
I can't duplicate this behavior. User may not have had mmaps enabled.
