### ISSUE TITLE
[SPELL] Touch of the Val'kyr doesn't work properly

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#727]
**Description**:
Touch of the Val'kyr doesn't work properly.

**Current behaviour**: Tell us what happens

 This spell do 0 damage and the monster stop chaneling in the middle of his casting bar.

![wowscrnshot_120517_192007](https://user-images.githubusercontent.com/31663279/33650751-a0abf078-da63-11e7-9d4e-1181e32850ba.jpg)

**Expected behaviour**: Tell us what should happen instead

do damage and the monster don't stop chaneling 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 2979fd6c1f7d+ Master

**AC hash/commit**:  

**Operating system**:  windows10

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by BarbzYHOOL** [comment]
is it the right spell? maybe it's another spell that must be used

**Comment by poszer** [comment]
Tested, can't confirm. The creature cast spell correctly, and dmg is applied also.
Closing this issue 
http://prntscr.com/nwg9bk
