### ISSUE TITLE
Faction change and reward: Corruption of Earth and Seed

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#7273]
### Current Behaviour

Can be completed twice after faction change.

Rewards 7 reputation for Cenerion Circle.

### Expected Blizzlike Behaviour

Rewards 500 reputation.

Should be exclusive to the other quest.

Related: https://github.com/azerothcore/azerothcore-wotlk/issues/5592

### Source

https://classic.wowhead.com/quest=7065/corruption-of-earth-and-seed

classic says 150 rep

https://wowpedia.fandom.com/wiki/Corruption_of_Earth_and_Seed_(quest)

tbc db/pedia from pre-cata says 1000 rep

https://wotlk.evowow.com/?quest=7065

other 3.3.5 databases have it as 500 rep

### Steps to reproduce the problem

1. start quest 7064
2. complete quest (observe rep reward)
3. faction change
4. start quest 7065
5. complete quest 

### Extra Notes

fix included

fix may not be valid/correct as not 100% sure on exlusivegroup SQL functionality + first fix by reporter in keira3

```
faction change:
UPDATE quest_template_addon SET ExclusiveGroup = 7065 WHERE (ID = 7064);
UPDATE quest_template_addon SET ExclusiveGroup = 7064 WHERE (ID = 7065);
rewards:
UPDATE quest_template SET RewardFactionValue1 = 500 WHERE (ID = 7065);
UPDATE quest_template SET RewardFactionValue1 = 500 WHERE (ID = 7064);
```

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@36a1777

### Operating system

win10

### Custom changes or Modules

    mod-ah-bot
    mod-cfbg
    mod-chromie-xp
    mod-desertion-warnings
    mod-duel-reset
    mod-eluna-lua-engine
    mod-ip-tracker
    mod-low-level-arena
    mod-multi-client-check
    mod-pvp-titles
    mod-pvpstats-announcer
    mod-queue-list-cache
    mod-server-auto-shutdown
    lua-CarbonCopy
    lua-CustomWorldboss
    lua-LevelUpReward
    lua-send-and-bind
    lua-Zonecheck
    lua-TempAnnouncements

**Comment by JamesGent** [comment]
https://github.com/chromiecraft/chromiecraft/issues/1372

**Comment by baranzadeoglu** [comment]
> Rewards 7 reputation for Cenerion Circle.

This is wrong. Here is how it works (from Wiki).
"
RewardFactionValueId1

This field is used for reputation lookup in QuestFactionReward.dbc if quest_template#RewardFactionValueId is 0. Value X in this field indicates RepX column of QuestFactionReward.dbc. If RewardRepValueId is positive, reputation from the first row of QuestFactionReward.dbc will be used, for negative values the second row is used.
"
So the value 7 at the database is probably correct. Couldn't manage to read QuestFactionReward.dbc for some reason but it has fields below;
![image](https://user-images.githubusercontent.com/84640316/131339880-d0c341c0-c4cd-4c57-a556-1ae5868d37b7.png)
so RweardFactionValueId1= "7" is probably true. (that it rewards the appropriate 500 rep)
