### ISSUE TITLE
Entering Arena with Pet can bug Arena Frames

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#7277]
### Current Behaviour

Sometimes when a hunter/warlock/death knight accepts Arena Queue with the pet active, they can bug their friends Enemy Arena Frames. 

Instead of showing only enemies Arena Frames, it will show a frame with a question mark and a pet (of your friend) and then two arena frames (on 2x2). 
Sometimes it only shows one enemy arena frame and the other one is a question mark. When this happens it makes impossible to target both enemy arena frames.

Here's a video that i recorded showing the problem:
https://www.youtube.com/watch?v=QAX7VOkWvXo

### Expected Blizzlike Behaviour

Party friend pets shouldn't be on the enemy arena frames.

### Steps to reproduce the problem

1. Enter Arena queue with a warlock/hunter/death knight
2. Make sure the pet is active before entering arena (as a warlock/hunter/dk)
3. Enter arena/accept the queue before your warlock/hunter/DK partner
4. Look at the Arena Frames

### Extra Notes

This does not happen all the time, i would say it happens ~30% of the time. 
This bug can easily be avoided if you dismiss your pet before entering arena, but not everyone knows that.
An easy fix would be to remove pets when players enters arena.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
I cannot reproduce it. 
Tried +10 times with different pets.

**Comment by laasker** [comment]
I will have to try again later, maybe it has something with the order of the people that enters arena? (in the video that i recorded, the hunter entered the arena by last, first one person of one team, then two person of the other team, then the hunter of first team)  or maybe it doesn't matter, i will have to make more tests

**Comment by laasker** [comment]
Tested again, it seems like it's random.
Out of 5 times i tested, it happened 2 times. The class with pet should be the last person of the same team to enter arena for the bug to happen.

https://user-images.githubusercontent.com/79991768/131441619-46d75d81-037b-4aef-9725-051f477e2c9d.mp4

**Comment by laasker** [comment]
Also, i forgot about this, but you need to have the interface option to see Arena Enemy Frames, at Interface > Unitframes > Arena Enemy Frames

**Comment by laasker** [comment]
i cant reproduce it anymore, some pr fixed this i think
