### ISSUE TITLE
Monster in dalaran

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#728]
**Description**:
Top

**Current behaviour**: Tell us what happens
This monster it's like spinning top 
![wowscrnshot_120517_182712](https://user-images.githubusercontent.com/31663279/33650950-595f033a-da64-11e7-931c-0b3f602c70c5.jpg)

**Expected behaviour**: Tell us what should happen instead

waypoint and stop be like spinning top 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: **Branch(es)**: 2979fd6c1f7d+ Master

**AC hash/commit**:  

**Operating system**:  windows10

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
this pet is supposed to follow the npc hunter around just needs to be defined in creature_formations ill assign this to me.

**Comment by sucofog** [comment]
@talamortis And it follows the owner, the thing is that he stuck in some places.

**Comment by talamortis** [comment]
the creature has its own assigned waypoint where it shouldn't have it should be at the side of the orc (hunter) ive done the sql just need to push

**Comment by Maurowin** [comment]
Nice :)

**Comment by Gargarensis** [comment]
Is this fixed?

**Comment by Middel** [comment]
@talamortis have you pushed the SQL yet?

**Comment by BarbzYHOOL** [comment]
need that sql @talamortis 

it's probably using formation or group for waypoints in the world db

**Comment by Winfidonarleyan** [comment]
Fixed in https://github.com/azerothcore/azerothcore-wotlk/commit/13d3d4b26f23c7ca5a572be09c5efaf5e08eaa49. Thanks @Trystanosaurus for test.
