### ISSUE TITLE
compile warning

### ISSUE THREAD

**Issue by Kingswow** [azerothcore/azerothcore-wotlk#7280]
hi , i have compile warning

[Warning is here](https://gist.github.com/Kingswow/08c45cb86d50ba410dc0b1fc70d7926f)

AC rev. hash/commit 21b2cd351859 ( last revision ) with #6378 and [mod-anticheat](https://github.com/azerothcore/mod-anticheat/pull/32)

win10 64bit

sorry for my bad english

**Comment by Kitzunu** [comment]
Warnings are not super critical.

Also dont ignore the issue template and there is no such hash/commit
