### ISSUE TITLE
Paladin Ability "Hand of Protection" Blocking Bandaging

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7286]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1368

When using the Hand of Protection skill (https://wowgaming.altervista.org/aowow/?spell=10278), you cannot use bandages. It gives you a message that you cannot do that while invulnerable.

Tester: confirmed that bandages don't work while this spell is active. 

![WoWScrnShot_081021_220633](https://user-images.githubusercontent.com/81782124/128869475-d91bf941-94e8-4393-8ee5-de481e7f809d.jpg)

### Expected Blizzlike Behaviour

You should be able to use bandages while under effect of Hand Of Protection.

Tester: I initially thought this was expected behaviour. HoP says the affected party member "cannot attack or use physical abilities", and if you go and look in a spell editor, bandaging is a physical school spell. (i.e. check spell 3275, Linen Bandage.) So you shouldn't expect it to work. 

However, we've found various sources, and in one case a Youtube clip of people bandaging while under HoP (or its close relative Blessing of Protection), so it seems there was an exception for First Aid.

### Source

"Sometimes it seems I take damage through it (more often than not) and I can't seem to bandage at all when it's up without someone damaging me all before the duration is up." - https://www.mmo-champion.com/threads/621242-What-s-with-the-Hand-of-Protection?p=5821996&viewfull=1#post5821996 - 2008-10

"Against rogues, if they have any stacks of deadly poison on the target you protect, a rogue can still use Envenom to damage the target because it is a Nature damage attack, not physical (its a rare thing but it can interrupt something like a bandage or be potentially lethal if you aren't careful." - https://wowpedia.fandom.com/wiki/Hand_of_Protection?oldid=2232036 - which clearly implies that the protected target could be bandaging.

As of Patch 3.0.2 this ability replaces the former [Blessing of Protection] and works in the same way, but uses the Hand system to prevent conflicts with Blessings. See here for someone bandaging while under the BoP effect:

https://youtu.be/Wdt0d8vrreI?t=129

### Steps to reproduce the problem

1. be a paladin lvl 10+
2. Learn one of the Hand of protection spells https://wowgaming.altervista.org/aowow/?search=hand+of+protection
3. Have some bandages (any https://wowgaming.altervista.org/aowow/?search=bandage#professions)
4. Use Hand of Protection on yourself and then try to bandage

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
also found this:
Patch 1.7.0 (2005-09-13): Effects that make players immune to physical will no longer be immune to the "Recently Bandaged" effect from First Aid. 
Perhaps after this change it was possible to use bandages during blessing of protection, but before it was not possible?

**Comment by syssneck** [comment]
I understand the patch note more in the sense, that before 1.7.0 bandaging did not trigger the debuff "Recently Bandaged", when used during physical immunity. Before the patch, it was possible to use bandages during blessing of protection and then shortly after again.

**Comment by UltraNix** [comment]
I don't think that bug report is valid.
The video is from classic (2019).

```
 (its a rare thing but it can interrupt something like a bandage or be potentially lethal if you aren't careful." - https://wowpedia.fandom.com/wiki/Hand_of_Protection?oldid=2232036 - which clearly implies that the protected target could be bandaging.
 ```
 It means that using bop on target might interrupt their bandaging.

```
...and I can't seem to bandage at all when it's up...
```
So he cannot use bandages under BoP effect.

```
Patch 1.7.0 (2005-09-13): Effects that make players immune to physical will no longer be immune to the "Recently Bandaged" effect from First Aid.
```
That means that debuff will always apply and not be immuned to it. It says nothing about bandaging itself.

That bandaging blocking comes from client (because of `UNIT_FLAG_PACIFIED`), so I believe it's blizzlike.

**Comment by FrancescoBorzi** [comment]
@Azcobu @syssneck @gurveleg

**Comment by syssneck** [comment]
Hand of Protection prevents one from using physical abilities and [bandages belong to the physical school](https://tbc.wowhead.com/spell=7928/silk-bandage). Yeah, I guess it already works blizzlike.

**Comment by Azcobu** [comment]
> I don't think that bug report is valid.
> The video is from classic (2019).

Yep, but it shows the same spell, with the same limitation on physical spells, making an exception for First Aid. 

> ```
>  (its a rare thing but it can interrupt something like a bandage or be potentially lethal if you aren't careful." - https://wowpedia.fandom.com/wiki/Hand_of_Protection?oldid=2232036 - which clearly implies that the protected target could be bandaging.
> ```
> 
> It means that using bop on target might interrupt their bandaging.

No, the sentence means that a rogue using Nature damage can get through the HoP shield to stop bandaging. 'It' in this sentence is referring to the subject of the sentence, which is the venom attack, not HoP. 

> ```
> ...and I can't seem to bandage at all when it's up...
> ```
> 
> So he cannot use bandages under BoP effect.

No, that's not an accurate reading at all. The sentence is "I can't seem to bandage at all when it's up **without someone damaging me**..." They're complaining because spell damage gets through the bubble, not that they can't bandage. It's like someone saying "I can't leave the house without it raining." They can leave the house, they're just complaining that when they do it rains. Same here. If they couldn't bandage at all, the sentence wouldn't make any sense. They're complaining because when they do bandage it gets interrupted.

> ```
> Patch 1.7.0 (2005-09-13): Effects that make players immune to physical will no longer be immune to the "Recently Bandaged" effect from First Aid.
> ```
> 
> That means that debuff will always apply and not be immuned to it. It says nothing about bandaging itself.

That's true, this one is a bit circumstantial. Though you have to ask how they got the 'Recently Bandaged' debuff if they couldn't bandage under HoP in the first place. 

> [TrinityCore/TrinityCore#19014](https://github.com/TrinityCore/TrinityCore/issues/19014)
> 
> That bandaging blocking comes from client (because of `UNIT_FLAG_PACIFIED`), so I believe it's blizzlike.

This was my position at first, but the sources above show people using bandages while under the effect, so clearly something changed somewhere.

**Comment by gurveleg** [comment]
I can get bandaged by other people while having Hand Of Protection active, so It seems I just cannot bandage myself while under the effect of it. I asked a guildmate who plays a paladin on TBC classic to test it and he could use blessing of protection and bandage himself.
https://imgur.com/I4hqAVK
![I4hqAVK](https://user-images.githubusercontent.com/80769357/129470753-0ad42032-8a78-4dfc-9f54-dcf31e6a30cd.png)

**Comment by UltraNix** [comment]
But it's still TBC Classic.

**Comment by lineagedr** [comment]
@gurveleg Blessing of protection isn't the same as hand of protection. The wotlk client blocks bandaging while having hand of protection. While having blessing of protection it does no such thing.

![close](https://user-images.githubusercontent.com/12139798/130073813-5671180a-b374-49c2-8f90-c41981761a85.png)

I think we can close this issue.

**Comment by gurveleg** [comment]
Blessing of Protection was just renamed to Hand of Protection in Wotlk, the spell and everything else is exactly the same. The spell Blessing of Protection listed in Wotlk DB (41450) is not the same spell paladins used in Vanilla and TBC so Its not a valid comparison.

But I agree if it is a client side thing it can be closed as there's noting you can do about it, as you have said. They must have changed somethining in Wotlk client then or maybe they changed something with bandages, because in vanilla client you can bandage yourself, and in classic & TBC you can do the same.

I cans till get bandaged by others or I can bandage someone I put HoP on so theres that.
