### ISSUE TITLE
[SPELL] Bladestorm

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#729]
**Description**:
Stuned on bladestorm

**Current behaviour**: Tell us what happens
in the forge of souls when i'm using bladestorm spell, i can be stun with lethargy. I don't know if other spell can stun me when i'm using bladestorm.

![wowscrnshot_120217_084654](https://user-images.githubusercontent.com/31663279/33651279-82020700-da65-11e7-9338-0b8d02c67a77.jpg)
![wowscrnshot_120217_084754](https://user-images.githubusercontent.com/31663279/33651280-82192a7a-da65-11e7-9ece-7aa91dbdc617.jpg)

**Expected behaviour**: Tell us what should happen instead

under bladestorm it's impossible to be stun.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: **Branch(es)**: 2979fd6c1f7d+ Master

**AC hash/commit**:  

**Operating system**:  windows10

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
issue invalid https://wotlk.evowow.com/?spell=46924 - look at the mechanic immune effect 

Apply Aura: Mechanic Immunity Mask (Charmed, Disarmed, Rooted, Pacified, Asleep, Ensnared) 

does not say anything about stun.

**Comment by Maurowin** [comment]
No, in retail no one can stun me when i'm under bladestorm. Read last line : you cannot be stopped unless killed.
It's a valide bug

**Comment by ShinDarth** [comment]
@Maurowin I'm not sure about the specific issue, but generally speaking we should always consider 3.3.5a retail and not the current retail

**Comment by Maurowin** [comment]
yeah, i'm speaking about that

**Comment by Maurowin** [comment]
in pvp if you can interrup bladestorm with some stuns nobody will use this spell.
https://www.youtube.com/watch?v=TSwgffEtH-Y
under bladestorm no spell can stop us just death

**Comment by Irome** [comment]
I know the warrior very well, and I confirm what @Maurowin said

**Comment by talamortis** [comment]
I thought disarm could stop bladestorm? or did that introduced in a different patch?

**Comment by talamortis** [comment]
https://wow.gamepedia.com/Bladestorm#Patches_and_hotfixes

**Comment by Irome** [comment]
In 3.3.5a with disarm the bladestorm spell should not be interrupted, if I remember correctly, the disarm should only remove the weapon from the warrior while the bladestorm is in progress. Correct me if I'm wrong.

**Comment by Maurowin** [comment]
you're right Irome

**Comment by talamortis** [comment]
ill fix later to ignore stun.

**Comment by talamortis** [comment]
https://youtu.be/1Kd5fmDYR2E - feedback will be nice before i push the fix.

**Comment by Maurowin** [comment]
yeah, it's look like video. Nice work!
