### ISSUE TITLE
Teleportation rune at Winterspring does not work

### ISSUE THREAD

**Issue by baranzadeoglu** [azerothcore/azerothcore-wotlk#7295]
### Current Behaviour

Nothing happens when standing on the rune

### Expected Blizzlike Behaviour

The rune in the cave teleports you to rune in the mountains near Haleh and vice versa

### Source

https://classic.wowhead.com/npc=10929/haleh#comments
first comment

### Steps to reproduce the problem

Go to winterspring
Go into the cave
Stand on the rune
Observe nothing happens

### Extra Notes

Tested with 49 level character, maybe there is a level limit but if so no text appears to indicate there is a level limit.

### AC rev. hash/commit

This was tested a at least 4-5 days ago.

### Operating system

Linux mint 20.04

**Comment by Nawakland** [comment]
### Current Behaviour
I figured out the same problem.
The Rune of Mazthoril in Winterspring (the lower one in the cave) does not trigger the teleport spell to the top of mountain close to Haleh (https://www.wowhead.com/wotlk/npc=10929/haleh).

### Expected Blizzlike Behaviour
The rune in the cave teleports you to rune in the mountains near Haleh.

###Source
https://classic.wowhead.com/npc=10929/haleh#comments
first comment

### Extra Notes
gameobject_template:
- entry=176164
- name=Rune of Mazthoril LT
- spell=17159 (https://www.wowhead.com/wotlk/spell=17159/port-to-haleh)

gameobject:
- GUID=49001

### 
AC rev. hash/commit
https://github.com/azerothcore/azerothcore-wotlk/commit/23606bcba0d22a073224eb3503932ae43fede9bf

### Operating system
Debian 12 Bookworm

### Custom changes or Modules
None

**Comment by Kitzunu** [comment]
open a new issue
