### ISSUE TITLE
Randomly Generated Item Stats Not Stacking Correctly

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7299]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1377

Revelosh's boots by default give +10 Stam, then their enchant modifier adds additional stats. I have of the bear type which adds +9 stam +9 str however, the +stams are separated, presumably they should be added together to be a total of +19 Stam

![WoWScrnShot_081121_013609](https://user-images.githubusercontent.com/5192790/128975504-b87d9674-65af-4c0d-be9c-6e33f1a2b777.jpg)

Tester: confirmed. 

![WoWScrnShot_081121_223433](https://user-images.githubusercontent.com/81782124/129035197-ba6271c3-87f5-4b53-abed-cff93c1a08c4.jpg)

Tried some other random items, and they also failed to stack their stats correctly:

![WoWScrnShot_081121_225032](https://user-images.githubusercontent.com/81782124/129036629-e04056b7-3060-4db2-9aaf-16f686d0b58f.jpg)
![WoWScrnShot_081121_225157](https://user-images.githubusercontent.com/81782124/129036637-ee33b5b8-44a9-4e61-b04a-abf125210817.jpg)

### Expected Blizzlike Behaviour

The numbers should be added together to be +19stam

### Source

Cannot find any source to show this, just going off of memory. But it does make sense that stats would be aggregated.

### Steps to reproduce the problem

1. Obtain Revelosh's Boots [Item id 9387]
2. Spawn or loot until of the bear variant is looted

### Extra Notes

Did confirm this is not a client UI mod related issue, ElvUI in particular. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

ElvUI

### Server

ChromieCraft

**Comment by UltraNix** [comment]
No bug - it's okay (clientside).
https://youtu.be/T9wg6Wf7Tf0?t=51
