### ISSUE TITLE
Not working Deathbringer Saurfang outro death scene

### ISSUE THREAD

**Issue by BungiSk** [azerothcore/azerothcore-wotlk#73]
Hi, does not work the scene after killing Deathbringer. Thus it should work
https://www.youtube.com/watch?v=S6wF_8LGp_E but after killing nothing happens ..

**Comment by ShinDarth** [comment]
Hi, thanks for your reports. But you  have to insert your revision. Please read this and edit all your reports accordingly :

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue
