### ISSUE TITLE
[SPELL/MAGE] mirror image

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#730]
**Description**: this spell doesn't work properly

**Current behaviour**: Tell us what happens
- images don't follow me when i'm going away 
- attack automaticly when i select enemy target without attack
- when her target is dead 
- they take position before attacking
- i pulled one target and target another before summon, they attack the target
- they don't attack if you haven't target even if we have pull before
- when we have more than one target, they waiting you to hit it before attack
- name of mirror image is wrong

![wowscrnshot_120617_092559](https://user-images.githubusercontent.com/31663279/33651899-b222ab5e-da67-11e7-9c52-29aa38e1f80d.jpg)
![wowscrnshot_120617_092648](https://user-images.githubusercontent.com/31663279/33651900-b235c2c0-da67-11e7-8aa7-cbfdd107ab09.jpg)

they cast again and stop in the final because their target is dead.

**Expected behaviour**: Tell us what should happen instead

- [x] -no attack when i'm just targeting enemy
- [x] - no cast when her target is dead
- [x] - follow me
- [ ] - as soon as they appear, they attack like a video https://www.youtube.com/watch?v=KTC7Tz-AXko
- [x] - they must attack the first one target and not attack second target because i'm not in fight with it
- [x] - they must attack even if we are lost target
- [x] - after the first one target was died they must attack second directly
- [x] - name of mirror image must be same of player who summon it

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 2979fd6c1f7d+ Master

**AC hash/commit**:  

**Operating system**:  windows10  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
can confirm

**Comment by Szone** [comment]
Confirm

**Comment by Irome** [comment]
this is a very important bug to fix, i confirm the issue

**Comment by talamortis** [comment]
I Will fix this later

**Comment by talamortis** [comment]
Quick question with this i thought mirror image attacked the targets your selecting didn't matter if you was in combat with or not

**Comment by talamortis** [comment]
https://youtu.be/-tQ6EDMMZY4

**Comment by pklloveyou** [comment]
@talamortis 
Tested passed
Follow the player after the first attack
Stop casting immediately after the target dies
When I just selected the enemy will not be attacked

**Comment by Maurowin** [comment]
@pklloveyou yeah talamortis has fixed some bugs but there are still some

**Comment by talamortis** [comment]
4cb370e1923058053c89d3e2073b9530d90877ff

**Comment by talamortis** [comment]
@Maurowin  @pklloveyou  could you test the latest fixes and let me know, if i can close <3

**Comment by Maurowin** [comment]
Hello ! atm i can't, i don't have so much time but i will try next monday

what do you have fixes? to test it?

let me a message here or check the checkbox

**Comment by lineagedr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Pet/pet_mage.cpp#L153

Find:
```C++
if (selection)
{
   me->getThreatManager().resetAllAggro();
   me->AddThreat(selection, 1000000.0f);

   if (owner->IsInCombat())
           AttackStart(selection);
}
```
Replace with:


```C++
if (selection && me->CanStartAttack(selection))
{
	me->getThreatManager().resetAllAggro();
	me->AddThreat(selection, 1000000.0f);
	me->AI()->AttackStart(selection);
}
```

Should fix this:
- as soon as they appear, they attack like a video https://www.youtube.com/watch?v=KTC7Tz-AXko

**Comment by Maurowin** [comment]
@talamortis lets me know when you need another test

**Comment by BarbzYHOOL** [comment]
Give a medal to this man

**Comment by pklloveyou** [comment]
@talamortis Perfect work

**Comment by BarbzYHOOL** [comment]
@talamortis one bullet point left :P

**Comment by talamortis** [comment]
changing priority to low now as most of the issues have been fixed, will work on the last bullet point later
