### ISSUE TITLE
Incorrect running animation when slowed

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#7301]
### Current Behaviour

Players have a wrong animation when they are running slowed, instead of running at reduced movement speed, the animation is just as if they were walking with the / keybind (walk mode)

### Expected Blizzlike Behaviour

You should run at reduced speed, instead of just walking

### Source

Here is a video that i recorded:
https://www.youtube.com/watch?v=6L65WPQq1hI

Here is how the animation should be (drake dog video on retail https://www.youtube.com/watch?v=joCFkj15zR0 at 7:10)
https://gyazo.com/473d4e3b7deb38991471f4aaff672c8e

Another video/angle: 

https://user-images.githubusercontent.com/79991768/129042644-7dc1ae7e-9e98-44e1-bc92-b3d29fafdbef.mp4

Here's on retail on ATR (https://www.youtube.com/watch?v=NnvfJ4baehk&ab_channel=WoundmanTV at 6:55)
https://gyazo.com/e032de464f9b8f78699cb6a2144844fb (small clip of the video)

Another video, now in Blizzcon arena tournament https://www.youtube.com/watch?v=AkMCw_FJMg4
At 0:37 and at 13:05 its clear the animation is very different

### Steps to reproduce the problem

1. Get slowed from hamstring, cone of cold or any spell that reduces move speed by 30~70%
2. See the animation

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
It's completely clientside how the player's movement looks like when slowed down.

**Comment by laasker** [comment]
I don't think it is, i logged on a russian server (dont know if i can say the server name here) to test. 
My wow client is En/Us and the animation is different when slowed:

https://user-images.githubusercontent.com/79991768/129456016-08630abf-5619-4a46-be06-0f8398bbc8d3.mp4


Now on my local server:

https://user-images.githubusercontent.com/79991768/129456024-62d1cba1-bd6c-4493-97cc-30ef9da8ede9.mp4
