### ISSUE TITLE
[AC-Core] .reset all command is missing

### ISSUE THREAD

**Issue by LightDestory** [azerothcore/azerothcore-wotlk#7305]
### Current Behaviour

Trying to run ".reset all spells" will returns: "There is not such command"

### Expected Blizzlike Behaviour

As cited on https://www.azerothcore.org/wiki/gm-commands

".reset all [...]" should trigger a reset of spells or talents for all characters at next login.

### Steps to reproduce the problem

1. Write command: ".reset all spells"

### AC rev. hash/commit

328184f0c442

### Operating system

Unix (Using the ChromieCraft test server)

**Comment by LightDestory** [comment]
I went to read the code and seems like .reset all is a reserved command for LVL 4 (= Console). Closing.

**Comment by Winfidonarleyan** [comment]
:/
