### ISSUE TITLE
"Rescue the Survivors" quest PVP flags and enters into combat.

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7308]
Original report from Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/1386

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Casting [Gift of the Naaru](https://wowgaming.altervista.org/aowow/?spell=59544) on [Draenei Survivor](https://wowgaming.altervista.org/aowow/?npc=16483) causes you to enter combat and become flagged for pvp. This action is required for the quest [Rescue the Survivors!](https://wowgaming.altervista.org/aowow/?quest=9283).

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=Wwo5P1TqmR4 From TBC Classic shows the character getting flagged.
This one from Cataclysm https://www.youtube.com/watch?v=izNT_nQ8ieA and this one from TBC classic https://www.youtube.com/watch?v=S1Kgld1YBlk along with many others show not getting flagged. I ended up having to research and explain why one showed flagging, and the only solution that made any sense to me is that one was a PVP server.

I believe this quest reflects the type of server that is being played. PVP servers would tend to flag PVP in open world, where PVE would not. I had a similar issue in https://github.com/azerothcore/azerothcore-wotlk/issues/6053 NPC's would flag when interacted with on a PVP server, (healed or attacked) and not when on a PVE server. 

Not to be overlooked, but using gift of the Naaru should not enter the player into combat.

### Source

Shown above

### Steps to reproduce the problem

1. Create a Draenei
2. .go creature 57194
3. Use gift of the Naaru
4. Enter into combat and get flagged

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Gultask** [comment]
This is a faction issue. There's missing implementation where the player shouldn't be flagged for healing/attacking certain flagged creatures.
