### ISSUE TITLE
Hex Lord Malacrass

### ISSUE THREAD

**Issue by kokutek** [azerothcore/azerothcore-wotlk#7309]
### Current Behaviour

Hex Lord Malacrass (boss in Zul Aman instance), has a wrong/unworking equip_template (weapon), its showing a white/blue cube in hand instead of staff.
![image](https://user-images.githubusercontent.com/87150722/129183274-6cab491d-a3c6-4d12-a867-cf13b724bbf1.png)

### Expected Blizzlike Behaviour

Should looks like this one.
![image](https://user-images.githubusercontent.com/87150722/129183372-e09be983-5148-4953-a1dc-0def323ea07c.png)

### Source

![image](https://user-images.githubusercontent.com/87150722/129183401-6eb19255-9781-434c-b1f3-e3f5185fd07a.png)

### Steps to reproduce the problem

1. type .tele ZA
2. open the doors by typing .gobject activate 18539
3. Go straight forward to the way where is the last boss called Zul Jin and you might find the boss Hex Lord Malacrass before him.

### Extra Notes

No idea whats wrong, the item ID seems correct.

### AC rev. hash/commit

No error.

### Operating system

Debian 10 x64

### Custom changes or Modules

Anticheat, Antifarming, boss announcer, cfbg, character tools, duelreset, npc beastmaster, pvp titles, spellregulator, transmog, weapon visual, world chat.

**Comment by benjymansy123** [comment]
![Screenshot 2021-08-12 192726](https://user-images.githubusercontent.com/38561765/129282535-83e28070-c4c9-46a6-a41e-81b2beba7a6a.png)

Also getting this issue on rev. 8522809bb35c+.

**Comment by JamesGent** [comment]
Do you know what his equipped weapon ID should be?

**Comment by heyitsbench** [comment]
TC (Specifically Killyana) has resolved this issue in [this commit](https://github.com/TrinityCore/TrinityCore/commit/5856f520bbd8dded42f7742277839587b0645dde).
