### ISSUE TITLE
Core/SmarScript: SMART_EVENT_FLAG_WHILE_CHARMED

### ISSUE THREAD

**Issue by OlegVintage88** [azerothcore/azerothcore-wotlk#731]
`SMART_EVENT_FLAG_WHILE_CHARMED` should be implemented

**Comment by ShinDarth** [comment]
please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by FrancescoBorzi** [comment]
Import: https://github.com/TrinityCore/TrinityCore/commit/96f90381e3ed696861354ea4ddf4ac0c495031c5

**Comment by FrancescoBorzi** [comment]
I opened a PR here: https://github.com/azerothcore/azerothcore-wotlk/pull/1431

It needs to be carefully tested since it's a big change, so please help us by testing it.
