### ISSUE TITLE
new crash(2021-08-13)

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#7318]
### Current Behaviour

update to da1fd680f3d6b2063952fc650cc13410f4afdcd2
and test PR #7306 + PR #7307
https://gist.github.com/mpfans/03f07923299609c520bd79127714acee

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

da1fd680f3d6b2063952fc650cc13410f4afdcd2

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
@FrancescoBorzi @Viste @UltraNix

**Comment by mpfans** [comment]
again
https://gist.github.com/mpfans/7c84ee583ecb53def3d19bfe5c6f8067

**Comment by lineagedr** [comment]
> again
> https://gist.github.com/mpfans/7c84ee583ecb53def3d19bfe5c6f8067

This is clearly related to the PR https://github.com/azerothcore/azerothcore-wotlk/pull/7306

**Comment by Viste** [comment]
> > again
> > https://gist.github.com/mpfans/7c84ee583ecb53def3d19bfe5c6f8067
> 
> This is clearly related to the PR #7306

yes, need to redo some shit

**Comment by mpfans** [comment]
Restored pr7306 and pr7307. no crash...
