### ISSUE TITLE
worldserver: segfault crash on exit

### ISSUE THREAD

**Issue by Ammako** [azerothcore/azerothcore-wotlk#7319]
### Current Behaviour

On Ctrl+C to stop worldserver, I get 176 lines of `Map::~Map: WorldObject TypeId is not a corpse! (3)`, then the connections to the databases are stopped as normal. But instead of exiting cleanly, it crashes with:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Caught signal 6
Segmentation fault (core dumped)
```

It doesn't really seem to affect functionality while the server is running, and it's probably not a big deal, but it would probably be better if the server could exit cleanly instead of crashing.

### Expected Blizzlike Behaviour

Who knows how Blizzard would have done it, but it should probably exit cleanly without error, like authserver does.

### Steps to reproduce the problem

1. Build AzerothCore
2. Run worldserver
3. Ctrl+C to stop worldserver

### Extra Notes

Data extracted from the client linked at https://www.azerothcore.org/wiki/client-setup, if that matters. Same happens with the Full data (v11) linked at https://www.azerothcore.org/wiki/server-setup

### AC rev. hash/commit
```
AzerothCore rev. 5c1b1299e74b 2021-08-13 13:25:08 +0200 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.76.0
Using MySQL version: 100604
Using CMake version: 3.21.1
Compiled on: Linux 5.10.56-1-lts
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/ammako/.local/bin/azerothcore/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/ammako/.local/bin/azerothcore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/ammako/.local/bin/azerothcore/data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_08_13_00
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00
```
### Operating system

Arch Linux x64

### Custom changes or Modules

https://github.com/azerothcore/mod-autobalance (49deb69f2905)

**Comment by mpfans** [comment]
Confirm, that the same error will appear when using the command `server shutdown 10`

**Comment by drozco** [comment]
Confirmed on two different machines on Ubuntu 20.04 LTS, and Windows 10, however the error on Windows is: Caught signal 22.
Fresh install, built with no modules.

**Comment by Bogir** [comment]
You can simply comment out this line
https://github.com/azerothcore/azerothcore-wotlk/blob/faef417d92313f3b787a5f9be24c363515a5cabf/src/server/game/Maps/Map.cpp#L56

![изображение](https://user-images.githubusercontent.com/25766571/129458717-d9e8b35b-68cc-44e0-b2f0-02b8d233739e.png)

**Comment by Ammako** [comment]
That prevents the error message from showing up, but it doesn't prevent it from crashing on exit with a segfault. The crash might be unrelated, that being said.

**Comment by Kitzunu** [comment]
That errror is not a part of why it is crashing. Also, for future crash reports, please include a crashlog
