### ISSUE TITLE
Section in Ghostlands missing mob population

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7325]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1381

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

No mobs present in a section of ghostlands highlighted below
![image](https://user-images.githubusercontent.com/68164076/129431177-a45fe0c5-5bdd-4b81-ba42-3aa083bf61f1.png)

### Expected Blizzlike Behaviour

It should be populated with [Vampiric Mistbat](https://tbc.wowhead.com/npc=16354/vampiric-mistbat) and [Ghostclaw Lynx](https://tbc.wowhead.com/npc=16348/ghostclaw-lynx)

### Source

https://youtu.be/dt7f8Atk0-Y
https://tbc.wowhead.com/quest=9159/curbing-the-plague

### Steps to reproduce the problem

1. .go creature 145290
2. Walk east and check the section outlined above
3. Notice no mobs

### Extra Notes

Going to the same spot as in the Video, shows no mobs
![image](https://user-images.githubusercontent.com/68164076/129431356-07d7225e-b048-4e4f-8d7c-0aa70ab7b259.png)
![image](https://user-images.githubusercontent.com/68164076/129431590-d68d3ad6-b650-42d8-bf65-56d338bb8dee.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
Compared area to official. Spawning is correct.
