### ISSUE TITLE
Azuremyst Isle Ravager Specimens spawn in pairs

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7327]
Oringinal CHromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1395
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Ravager Specimens](https://wowgaming.altervista.org/aowow/?npc=17199), which are needed for the quest [Beasts of the Apocalypse!](https://wowgaming.altervista.org/aowow/?quest=9560) spawn in pairs and are almost impossible to pull singly, unless both are at opposite extremes of their pathing.

### Expected Blizzlike Behaviour

Only one ravager should spawn at each spawn point. 

### Source

[Video from TBC Classic server](https://www.youtube.com/watch?v=pK1I4jnBKpY) showing a shaman easily fighting just one at a time.

The same location as 1:10 in the video on CC:
![WoWScrnShot_081221_212956](https://user-images.githubusercontent.com/10586372/129297161-6f3b966f-4c5a-401a-b34a-0e58e9547ac6.jpg)

### Steps to reproduce the problem

1. .go creature 61250
2. notice pairs wandering in roughly the same areas.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
closed per PR https://github.com/azerothcore/azerothcore-wotlk/pull/10377
