### ISSUE TITLE
Haunting NPCs\Pets twitching when follow up target

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#7330]
### Current Behaviour

Original post: https://github.com/chromiecraft/chromiecraft/issues/1391

Haunting NPCs\Pets twitching when follow up target. Enemy NPCs twitch(?) in air when follow (attack) pet:
https://user-images.githubusercontent.com/21084600/129193686-0ab1f78e-87ab-4dfb-8f01-b610bc9d0abe.mp4
This applies to any case pet->npc\npc->pet\npc->npc.

### Expected Blizzlike Behaviour

smoothly move

### Steps to reproduce the problem

with pet attack any ground NPC and say pet follow back.
or observe how any npc should attack another npc.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6ff9b21b736c5bbf506a1ffa439caadb42c5dbdf

### Operating system

Windows 10 x64

**Comment by Azcobu** [comment]
Bad timing, I've just created the same ticket in https://github.com/azerothcore/azerothcore-wotlk/issues/7331. Closing this as a duplicate.
