### ISSUE TITLE
Desolace - Gelkis/Magram Centaur Reputation Mechanics Incorrect

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7339]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Originally reported: https://github.com/chromiecraft/chromiecraft/issues/1406

Mobs gives wrong rep amount, currently they give 100 per kill and decrease by 500. Once reputation towards one of the clans farmed to honored it won't decrease if you kill mobs from that faction. This allows to get both factions Gelkis and Magram to be farmed to honored.

Short clip of how killing a npc doesn't decrease reputatoin from it's faction:
https://youtu.be/MKczMKKGgS4

Tester: confirmed. The 5x rep gains are bad enough, but that the reputation losses from killing one faction stop when you get that faction to Honoured is arguably worse.

Kill with 0/neutral rep showing incorrect amounts:
![WoWScrnShot_081421_233938](https://user-images.githubusercontent.com/81782124/129449018-6e7b7c3c-fbd1-4139-aff3-085ca132ad8f.jpg)

Using a GM command set to Gelkis rep to Honoured, and then killing one does not lower Gelkis standing. The Magram increase is there, but the decrease isn't:
![WoWScrnShot_081421_231119](https://user-images.githubusercontent.com/81782124/129448292-e6f9e415-edcf-4810-b635-8e16133f04e2.jpg)

Likewise for Magram.

See for a complete listing of affected NPCs:
[Magram Clan Centaur](https://wowgaming.altervista.org/aowow/?faction=93)
[Gelkis Clan Centaur](https://wowgaming.altervista.org/aowow/?faction=92)

### Expected Blizzlike Behaviour

Mobs should give 20 rep per kill for opposing clan and decrease by 100 reputation from which killed mob is.

### Source

"20 reputation with Gelkis Clan Centaur (stops at Friendly)
-100 reputation with Magram Clan Centaur" - https://tbc.wowhead.com/npc=4645/magram-mauler

"For instance, if you kill a magram centaur, you will gain 20 points of reputation from the gelkis, but will lose 100 points from the magram." - https://wowwiki-archive.fandom.com/wiki/Reputation

"In order to be deemed worthy of the Gelkis' trust, adventurers must gain reputation with the tribe by slaying members of the Magram until they reach Friendly status with the Gelkis. Each kill gives 5/20/25 reputation to the Gelkis faction and lowers the reputation of the Magram by 25/100/125." - https://wowwiki-archive.fandom.com/wiki/Gelkis_clan

"Each kill gives 22 reputation to the Magram faction and lowers the reputation of the Gelkis by 100." ([source](https://wowpedia.fandom.com/wiki/Magram_clan?oldid=2375988)) - this says 22 rep instead of 20, but that's probably a human character with their 10% rep bonus. 

### Steps to reproduce the problem

Gelkis rep is 92, Magram is 93. So .modify reputation 92/93 9001 (to get to 1 point into Honoured) to test the problem with rep decreases stopping on kills.

1. Start and Complete on of the following quest chains: [Strange Alliance](https://wowgaming.altervista.org/aowow/?quest=1382) or [Brutal Politics](https://wowgaming.altervista.org/aowow/?quest=1385)
2. Get reputation of one of the factions to honored (this is what i did, aka i didn't stopped once i have completed the quests towards one of the factions)
3. Once honored and completed quests towards one of both factions start killing npc from the faction you just had honored and you should notice that they only increase reputation towards opposing faction without decreasing rep to which killed mobs are.

### Extra Notes

I don't know if simply getting friendly and quickly completing the quests would trigger this issue.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by gurveleg** [comment]
Theres one topic about the reputation, but just for the incorrect values https://github.com/azerothcore/azerothcore-wotlk/issues/6526, but any fix to them would close both Imo.

**Comment by Azcobu** [comment]
Yeah, forgot to search first - would close this but the weird rep mechanics aren't in the other one. Fixing the rep numbers is easy enough, but haven't yet found what's stopping the penalty past Honoured, though it's probably something in `conditions`.
