### ISSUE TITLE
[IDEA] Ep/Gp in Guild fron mSQL+Lua

### ISSUE THREAD

**Issue by Wokwer** [azerothcore/azerothcore-wotlk#734]
Hello!
I'm very bad at English.
I can not program, everything is at the level of instructions and copying.
I'll tell the essence of the idea from the user of the player, the master of the guild.
I'm sure that having implemented this idea here, the project azerothcore will be more attractive, for players who organize a group game in guilds.
You all know the guild distribution system **EpGp** or **DKP**. The data for this and I propose to make it into the table **mSQL**, in the bases **world** and **characters**.

1. It is required to make the following data automatically by default:
1.1. The effort point **(EP)** for the killing of a Bose is equivalent to the value of its extraction level by ilvl
1.2. Equipment points **(GP)** are the same as in the addon **EPGP**.
1.3. Bad game points **(BP)**

2. From the side of the addon azerothcore **Lua**:
2.1 To give an opportunity to make charges to the guild master and the officers of the guild.
2.2. Give the option of using a production distribution system as usual or azerothcore
2.3 To enable the guildmaster to select the built-in system of the azotorcore or to adjust the values ​​of **EP**, **GP**, **BP** creating his own system **EpGp** and **DKP**
2.4 Make it possible to correct the guild to the master cost **(EP)** for killing bosses

3. Bad points **(BP)** or good **(EP)** games that will be credited by the guild master or officer on the proposed data if it does not fix its own:
3.1. Afk = 20 BP
3.2 Incorrect game = 50 BP
3.3 Actions led raid to doom = 500 BP
3.4 Refusal to participate in the campaign = 2000 PB
3.5 Quick access to the raid = 100 EP
3.5 End of the raid = 100 EP
3.6 Good game = 50 EP

4. Priority Points **(PR)** can be calculated by the formula: **Ep/(Gp+Bp)**

As a result, the system of distribution of production from the player's chase will look like usual, and from the guild of the master with the help of the addon will appear the expanded menu of the guild

p.s. If you did not write correctly or not, please do not scold.
p.s.s If the idea is interesting, but you need clarification, please ask.

Всем привет!
Я не умею програмировать, все на уровне инструкций и копирования.
Раскажу суть идеи со стороны пользователя игрка как ГМа гильдии.
Уверен что внедрив эту идею, проэкт будет более привлекателен, в глазах игроков которые организовывают групповую игру в гильдиях.
Вы все знаете систему распределения добычи в гильдиях **EpGp** или **DKP**. Данные для этого и предлагаю внести в таблици **mSQL**, в базах **world** и **characters**.

1. Требуется вносить следующие данные автоматически по умолчанию:
1.1.  Очки усилий **(EP)** за убийство боса равнозначное со значением уровня его добычи по илвл
1.2. Очки экипировки **(GP)** одинаковое как в аддоне **EPGP**.
1.3. Очки плохой игры **(BP)**

2. Со стороны аддона azerothcore **Lua**:
2.1 Дать возможность производить начисления гильд мастеру и офицерам гильдии.
2.2 Дать возможность выбора использовать систему распределения добычи как обычно или azerothcore
2.3 Дать возможность гильдмастеру выбрать встроенную систему азероткоре или корректировать значения **EP**, **GP**, **BP** создавая свою собственную систему **EpGp** или **DKP**
2.4 Дать возможность коррегтировать гильд мастеру стоимость **(EP)** за убийство босов

3. Очки плохой **(BP)** или хорошей **(EP)** игры которые будет начислять гильд мастер или офицер по предложенным данным если не устоновит собственные:
3.1. Афк = 50 BP
3.2 Некорректная игра = 50 BP
3.3 Действия привели рейд к гибели = 500 BP
3.4 Отказ от участия в походе = 2000 PB
3.5 Быстрый вход в рейд = 100 EP
3.5 Окончание рейда = 100 EP
3.6 Хорошая игра = 50 EP

4. Очки приоритета **(PR)** расчитывать по формуле: **Ep/(Gp+Bp)**

В итоге, система распределения добычи со сотроны игрока будет выглядеть как обычно, а со стороны гильд мастера при помощи аддона появится расширенное меню гильдии

з.ы. Если написал не правильно или не туда пожалуйста не ругайте.
з.ы.ы. Если идея интересна, но требуется уточнения, пожалуйста спрашивайте.

![guild_epgp](https://user-images.githubusercontent.com/34383846/33799574-a6f38340-dd58-11e7-9520-87f541a9df2b.png)

**Comment by talamortis** [comment]
Sorry we are not working on custom content, as the core is blizzlike.

**Comment by Wokwer** [comment]
This is not the core, it's the idea for the module. If not there wrote an idea for the module, I apologize.

**Comment by BarbzYHOOL** [comment]
Ok, maybe you could post it on the forum to keep a track of it?

I would not use this module myself but maybe someone will find the idea interesting in the future

**Comment by Wokwer** [comment]
Unfortunately I do not know how to do it. (
