### ISSUE TITLE
Gromsblood spawn in Azuremyst Isle

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7344]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1417

A single node of [Gromsblood](https://wowgaming.altervista.org/aowow/?object=142145) spawns inside Stillpine Hold in Northern Azuremyst Isle. Judging by the database link, it appears there's also a spawn in Durotar that shouldn't be there.

![WoWScrnShot_081221_222242](https://user-images.githubusercontent.com/10586372/129446758-84ba5090-09de-4478-8783-b1ffb9a1b278.jpg)

Tester's note:
I think the one in Durotar is the Gromsblood with GUID of 47871. It is actually in Ashenvale, but is listed as in durotar. Here is the map of me standing on it:
![image](https://user-images.githubusercontent.com/53914190/129452110-6a3e0887-c9cd-4e63-9678-0cd3da12186f.png)

### Expected Blizzlike Behaviour

Gromsblood should spawn in level 40-50 zones, with a few outliers in certain areas of level 30 zones.

### Source

[Wowhead TBC link](https://tbc.wowhead.com/object=142145/gromsblood)

### Steps to reproduce the problem

Enter Stillpine Hold and travel north along the lower path until you reach the red crystal where [Search Stillpine Hold](https://wowgaming.altervista.org/aowow/?quest=9565) is turned in.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
The one in the cave is GUID: 16531 
Should we delete it or move it elsewhere?
