### ISSUE TITLE
PDUMP command broken due to magic number in PlayerDump.cpp incorrect field ID

### ISSUE THREAD

**Issue by drozco** [azerothcore/azerothcore-wotlk#7346]
### Current Behaviour

pdump write command fails with Deleted character error message, even if character is not deleted.
This is likely due to a magic number '74' being in the code to check if character is deleted within PlayerDump.cpp:
This is expecting to see the 'deleteInfos_Account' field in position 74, but it is not.  It is actually at position 76, likely due to some database update.
Position 74 is the 'order' field.
                if (result->Fetch()[74].GetUInt32())        // characters.deleteInfos_Account - if filled error
                    return false;

Tested on AzerothCore rev. 6ff9b21b736c+ 2021-08-13 15:49:13 +0000 (master branch) (Unix, Release, Static)

### Expected Blizzlike Behaviour

None - this is AzerothCore feature only.

### Source

Changed code to below and pdump worked successfully.  However the use of magic numbers in code is not recommended.
TrinityCore searches for the field by name, so this could be a better solution.  I will upload a PR if requested.

Fix:

    case DTT_CHARACTER:
    {
        if (result->GetFieldCount() <= 76)          // avoid crashes on next check
            LOG_FATAL("entities.player.dump", "PlayerDumpWriter::DumpTable - Trying to access non-existing or wrong positioned field ('deleteInfos_Account') in 'characters' table.");

            if (result->Fetch()[76].GetUInt32())        // characters.deleteInfos_Account - if filled error
                return false;
                break;
            }

TrinityCore method:

    case DTT_CHARACTER:
    if (result)
    {
         // characters.deleteInfos_Account - if filled error
         int32 index = GetColumnIndexByName(tableStruct, "deleteInfos_Account");
         ASSERT(index != -1); // checked at startup

         if ((*result)[index].GetUInt32())
            return false;
     }
     break;

### Steps to reproduce the problem

1. console or in-game Admin level account
2. type pdump write filename charactername or GUID
3. Error about deleted characters cannot be dumped

### AC rev. hash/commit

AzerothCore rev. 6ff9b21b736c

### Operating system

Ubuntu 20.04 LTS

**Comment by FrancescoBorzi** [comment]
@drozco thanks for your report, can you please [create a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with your fix?

**Comment by Kitzunu** [comment]
Magic numbers, we love them
