### ISSUE TITLE
Muting players does not work when they're offline

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#7350]
### Current Behaviour

When muting a character with `.mute $name $time $reason`, the data of the mute is properly written to the database in `auth.account_muted` and there is a message saying, that the player's chat was disabled, "effective at the player's next login".

However, when the player logs in, there seems to be no check for existing mutes.

### Expected Blizzlike Behaviour

Mutes need to work!

### Steps to reproduce the problem

Make sure a character is offline.
Mute the character.
Log the character back in. It can chat. The mute does not work.

### Extra Notes

Re-logging does not lift the mute. It seems to be related to the mute being applied while the player is offline.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5 for linux
e8fbd03c7734 for windows

### Operating system

Ubuntu 20.04 as well as Windows 10 x64

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

**Comment by Winfidonarleyan** [comment]
Need rework this system

**Comment by FrancescoBorzi** [comment]
@55Honey don't forget to apply the `[ChromieCraft Generic]` label and add the issue to the `ChromieCraft generic bugs` Project
