### ISSUE TITLE
Frost trap activating at long distance

### ISSUE THREAD

**Issue by WillzDevs** [azerothcore/azerothcore-wotlk#7356]
### Current Behaviour

The trap is activating with the player far away, without even stepping on it

### Expected Blizzlike Behaviour

It should activate when the player steps on it.Below video of how it is.
[https://youtu.be/LhuclJHjS-Q](https://youtu.be/LhuclJHjS-Q) 

### Steps to reproduce the problem

1. Use Frost trap on an enemy
2. See her activating long distance
3. It activates if far away

### AC rev. hash/commit

> faef417d9231+

### Operating system

Windows

**Comment by WillzDevs** [comment]
@Nefertumm thanks for reopening!!

**Comment by UltraNix** [comment]
@WillzDevs Any proof it should be lower?

**Comment by UltraNix** [comment]
@WillzDevs

**Comment by UltraNix** [comment]
Closing.
