### ISSUE TITLE
Gluth ignore tank

### ISSUE THREAD

**Issue by xojld0** [azerothcore/azerothcore-wotlk#736]
Description:

There is a problem with the boss in Naxxramas gluth.

Current behaviour: Tell us what happens

When there are zombie boss runs to them ignoring the agro tank

Expected behaviour: Tell us what should happen instead

After the appearance of the zombie, the gluth should react to the agro tank if there is

Steps to reproduce the problem:

1. Go to Naxxramas
2. Start killing the gluth
3. Waiting for the appearance of zombies

Branch(es): 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

Last revision b527073, master

AC hash/commit:  

Operating system:  Linux, Ubuntu 16.04

Modules:  Anticheat, Transmogrification, Premium account

Other Customizations: Made 2 vendors

**Comment by talamortis** [comment]
so does the boss ignore the tank or does the zombies? as far as I can remember with this boss the zombies walk to the boss and if zombie is within range he "eats" them

**Comment by xojld0** [comment]
when a zombie appears, the boss immediately runs to him, no matter at what distance is the zombie

**Comment by Maurowin** [comment]
it's wrong. the zombie are kitted by hunter.
look https://www.youtube.com/watch?v=GAGjSdlGM6E at 1:00

**Comment by pondaveia** [comment]
> Zombie Chows have 1,000,000 hit points each. Two will spawn every 10 seconds from the grates near where you jump out of the pipe into Gluth's lair. These move at run speed. Vulnerable to all snares and roots.
> Infected Wound - Applied on a melee hit, increases physical damage taken by the target by 100. Stacks up to 99 times. Forces zombies to be kited rather than tanked.
> When Zombie Chows are hit by decimate they will immediately stop attacking and run towards Gluth. Should be rooted and AoE'd down. They will have approximately 50,000 hit points at this stage.

Source:

http://wowwiki.wikia.com/wiki/Gluth

**Comment by Maurowin** [comment]
Decimate do domage to all players and zombies.

**Comment by a7x00** [comment]
It's okay, Xojld0, Gluth must eat the zombies to recover HP, but he goes to them only when they're in range.
"Devour Zombie - Gluth will emote, "Gluth spots a nearby Zombie to devour!" and move towards any zombies that get near him. This will heal him by 5% of maximum HP."
So, he must ignore the tank.
