### ISSUE TITLE
LBRS War Master Voone scripting/abilities incorrect

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7362]
### Current Behaviour

Lower Blackrock Spire Boss War Master Voone He starts out with `Throw Axe`, `Snap Kick` and `Mortal Strike`. Around 90% he will add `Uppercut` to his abilities, and do the entire fight with just these abilities. I should mention during one of my runs I saw him use `Cleave`. But it was only one time, and did not pay attention to his health % at the time.

### Expected Blizzlike Behaviour

**Stage One: The Thrasher**
War Master Voone attacks quickly, assaulting his enemies relentlessly.

[Thrash](https://www.wowhead.com/spell=3391/thrash) — Gives the caster 2 extra attacks. 
[Throw Axe](https://www.wowhead.com/spell=16075/throw-axe) — Hurls a massive axe at a random enemy, dealing 1750 damage and stunning them for 2 sec. 

**Stage Two: The Brawler**
When War Master Voone reaches 65% remaining health, he changes his stance, attacking with more ferocity.

[Cleave](https://www.wowhead.com/spell=15284/cleave) — Inflicts 110% of normal melee damage to an enemy and its nearest allies, affecting up to 3 targets. 
[Mortal Strike](https://www.wowhead.com/spell=16856/mortal-strike) — Inflicts 300% weapon damage and leaves the target wounded, reducing the effectiveness of any healing by 50% for 5 sec. 

**Stage Three: The War Master**
When War Master Voone reaches 40% remaining health, he begins his final assault, holding nothing back.

[Snap Kick](https://www.wowhead.com/spell=15618/snap-kick) — Inflicts 4 damage to an enemy, stunning it for 2 sec. 
[Uppercut](https://www.wowhead.com/spell=10966/uppercut) — Inflicts normal damage plus 50 to an enemy, knocking it back. 
[Pummel](https://www.wowhead.com/spell=15615/pummel) — Pummels an enemy for 45 damage and interrupts the spell being cast for 5 sec.

### Source

https://wowpedia.fandom.com/wiki/War_Master_Voone
https://www.wowhead.com/npc=9237/war-master-voone#abilities;mode:normal
WOW Classic LBRS Walkthrough https://youtu.be/3bKwDcQqINM?t=706

### Steps to reproduce the problem

`.go c 45840`
begin the fight
watch the combat log

### AC rev. hash/commit

 faef417d9231

### Operating system

Windows 10

**Comment by Nyeriah** [comment]
One thing is not clear to me: the abilities get added on top of each other or he switches phases? (stops using previous set of abilities)

**Comment by Shineslippers** [comment]
@Nyeriah based on [this](https://youtu.be/nA8emnau2sg?t=992) and some others video atm i could say:
He is using Throw Axe when changing stances. And you can see at the end he doesn't have weapons in hands at all.
