### ISSUE TITLE
LBRS Urok Doomhowl encounter discrepancy

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7364]
### Current Behaviour

Lower Blackrock Spire optional boss Urok Doomhowl encounter is slightly off. When the event is started, waves of elite ogres spawn and begin attacking players. They all have yellow name plates. 

When Urok spawns he only uses the abilities Rend and Strike

### Expected Blizzlike Behaviour

When the Ogres spawn they should immediately aggro to the pike with the head. If they succeed in destroying it Urok will not spawn. 
In addition to rend and strike, Urok should also use the ability [Intimidating Roar](https://www.wowhead.com/spell=16508/intimidating-roar)

As a side note there should be [spire scorpids](https://tbc.wowhead.com/spell=16452/kill-urok-minion) in the broken wall sections right after this encounter. On some videos players will get feared into them. (see below)

### Source

https://www.wowhead.com/npc=10584/urok-doomhowl#abilities;mode:normal
https://www.wowhead.com/npc=10584/urok-doomhowl#comments;mode:normal
https://wowpedia.fandom.com/wiki/Urok_Doomhowl
WOW classic https://youtu.be/AY-m_3lGiqg?t=97

### Steps to reproduce the problem

.add item 12533
.additem 12534
.go o 99791
"use" the head in your bag
Stand aside and watch them all come after you.

### AC rev. hash/commit

 faef417d9231

### Operating system

Windows 10

**Comment by patou01** [comment]
You wrote .add item 12533. could you correct to .additem 12533? Took me a while to figure out :D 

- Adding the cast of fear on a semi-random as is done for other scrips is straightforward, somehow it's missing in the cpp script. However it seems it doesn't break on taking damage. (but that'd be a spell issue?)
- The yell at start is wrong.
- the mobs are seen as neutral. 
I can probably fix these 3. The mobs going for the pike however, I have no idea. Would you know another event in game where NPCs attack an object that has no hp and works on our servers? Then I can try to look there to see if I can take inspiration there.

Alternatively, it would currently reset if people wipe I believe, which is "not good" but works? Makes it slightly harder.

**Comment by patou01** [comment]
Remaining task from here is only:
When the Ogres spawn they should immediately aggro to the pike with the head. If they succeed in destroying it Urok will not spawn.

I close this issue as we move it to https://github.com/azerothcore/azerothcore-wotlk/issues/9023 as a summary of the remaining issues relating to this boss.
