### ISSUE TITLE
LBRS Gizrul the Slavener only uses basic attacks

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7365]
### Current Behaviour

Pretty much as the title says. Lower Blackrock Spire boss Gizrul the Slavener only uses basic attacks. 

### Expected Blizzlike Behaviour

He should use [Fatal bite](https://www.wowhead.com/spell=7938/fatal-bite), [Infected bite](https://www.wowhead.com/spell=16128/infected-bite), and [Frenzy](https://www.wowhead.com/spell=8269/frenzy)

### Source

https://www.wowhead.com/npc=10268/gizrul-the-slavener#abilities;mode:normal
https://wowpedia.fandom.com/wiki/Gizrul_the_Slavener

### Steps to reproduce the problem

.go c 40245
Kill Halycon to spawn Gizrul
Begin battle with Gizrul
Watch your combat log

### AC rev. hash/commit

 faef417d9231

### Operating system

Windows 10

**Comment by wizzymore** [comment]
Can confirm
