### ISSUE TITLE
LBRS Quatermaster Zigris scripting is off

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7366]
### Current Behaviour

Lower Blackrock Spire boss Quatermaster Zigris exhibits odd behavior. At ranged he will stutter step while shooting and try to get into melee range. He will only use his [Stun Bomb](https://www.wowhead.com/spell=16497/stun-bomb) ability and melee attack unless the tank runs to ranged for him to shoot.

https://user-images.githubusercontent.com/68164076/129519515-477b88cb-a240-432a-a8c1-f1ffddced853.mp4

Lastly he does not drop a blue item. I tried 3 kills and he did not drop a blue at any time.
![image](https://user-images.githubusercontent.com/68164076/129521078-e13ce7ad-2d88-4628-8163-3899879db88f.png)

### Expected Blizzlike Behaviour

He should use [Hooked net](https://www.wowhead.com/spell=15609/hooked-net) and prefer ranged attacking, and running to ranged when hooked net is used. Not run purposely into melee range. He should also [Drink a health potion](https://www.wowhead.com/spell=15504/drink-healing-potion) during the battle.
He should chance drop items listed here https://wowwiki-archive.fandom.com/wiki/Quartermaster_Zigris

### Source

https://wowwiki-archive.fandom.com/wiki/Quartermaster_Zigris
Wow classic walkthrough https://youtu.be/3bKwDcQqINM?t=918

### Steps to reproduce the problem

.go c 45749
Move to a ranged position and pull him
Watch the stutter step shooting
Count how many times he uses `Hooked net` 
Damage him down and see if he uses a health potion

### AC rev. hash/commit

 faef417d9231

### Operating system

Windows 10

**Comment by wizzymore** [comment]
Currently i can only confirm the following loot drops that are missing:
![image](https://user-images.githubusercontent.com/25827787/129727961-0a93c12c-16cc-472d-9635-62c951de4d50.png)

The others are as following:
![image](https://user-images.githubusercontent.com/25827787/129728043-55afad30-397d-4c2f-b8bb-4497b2cfac9c.png)

**Comment by wizzymore** [comment]
Also, now after testing and looking inside the script, i can confirm he is not using healing potion and not using any hooknets
