### ISSUE TITLE
[Un'Goro Crater] Blazing Invaders despawn moments after spawning

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7369]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: [Chromie issue#1440](https://github.com/chromiecraft/chromiecraft/issues/1440)

Blazing Invaders (https://wowgaming.altervista.org/aowow/?npc=14460) that are spawning during Elemental invasion in Un'goro, despawn a second or less after they appear from the portal. Unless they manage to hit your, or you hit them they will despawn no matter what, even if they do aggro. Only way to kill them is to stand next to portals and wait for respawn so they can aggro/hit you,/you hit them before they have a chance to despawn.

Here I am standing inside its aggro range, but far enough that the Invader couldnt damage me before despawning.
![invader](https://user-images.githubusercontent.com/80769357/129521713-6f7786b6-832c-4d4f-8a67-af48a663b507.jpg)

**Videos:**
https://user-images.githubusercontent.com/80769357/129528426-a518ce6b-6f3a-44a7-8d2a-7c7e9b470935.mp4
https://user-images.githubusercontent.com/80769357/129529179-d78a33d3-8342-42a2-9985-006f5e0f969a.mp4

### Expected Blizzlike Behaviour

After the Invaders spawn, they should stay spawned until killed

### Source

https://wowwiki-archive.fandom.com/wiki/Elemental_Invasions

https://tbc.wowhead.com/npc=14460/blazing-invader#comments

https://www.youtube.com/watch?v=cjFn67eTWE4

### Steps to reproduce the problem

1. Go to Un'gor During Elemental Invasion
2.  Wait near one of the spawning portals (but far away to not aggro) and wait for invader to spawn
3. See the Blazing Invader Despawn in moments

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (da1fd68). I wonder if there is some sort of creature limit, that checks the amount of creatures and despawns the last spawned in the area.

**Comment by syssneck** [comment]
Same as in: [#7417](https://github.com/azerothcore/azerothcore-wotlk/issues/7417) and [#7418](https://github.com/azerothcore/azerothcore-wotlk/issues/7418)

**Comment by Ragelezz** [comment]
More info about this? Found those infos, are those accurate or ?
https://wowgaming.altervista.org/aowow/?npc=14460#abilities
https://wowgaming.altervista.org/aowow/?object=179666#comments
Check SmartAI for both.

**Comment by Ragelezz** [comment]
Nvm, found that this website its based on AC db, not a trusty one such wowhead or older parsed wowheads.

**Comment by yuzifc** [comment]
Fixed by #9372
