### ISSUE TITLE
Invalid command syntax/params leads to a kick instead of a invalid syntax/params warning

### ISSUE THREAD

**Issue by LightDestory** [azerothcore/azerothcore-wotlk#7374]
### Current Behaviour

improperly usage of ".modify mount" command will led to a kick from the server.

The wiki cites: 
`.modify mount #id #speed => Display selected player as mounted at #id creature and set speed to #speed value.`

If you use an improper ID you will get kicked from the server. If you use a not existing ID you will get a invalid ID message.

### Expected Blizzlike Behaviour

Get the "invalid ID" message for both cases

### Steps to reproduce the problem

- .modify mount 232323 100 => "There is not such mount"
- .modify mount 1 100 => Kick from the server

### AC rev. hash/commit

328184f

### Operating system

Unix (Using the ChromieCraft test server)

**Comment by Kitzunu** [comment]
Need to check if the id exists, just a nullcheck that is missing in the script

**Comment by LightDestory** [comment]
> Need to check if the id exists, just a nullcheck that is missing in the script

Hmm I don't think so, I don't have a general knowledge of the WoW core scripting but I checked the code and found out that there is a check based on a switch statement that check if the entered ID is "usable" and it is unlisted the default case will run with the print of "LANG_NO_MOUNT" (https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_modify.cpp#L944)

For my example, I used the ID: 232323 which triggered the default case, but I used the ID: 1 too, which is listed and should execute the relative case: mId = 14340; (https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_modify.cpp#L737)

So I think that we got a DB issue rather then a script issue. I read the entire command and it seems legit. Maybe rather then a nullcheck we need to check the validity of these hard-coded IDs.

It is just a suggestion, I am still learning the core basics.

**Comment by Kitzunu** [comment]
Why there even are hardcoded stuff I don't know, it shouldn't be there. I will check if I can rewrite the script

**Comment by LightDestory** [comment]
> Why there even are hardcoded stuff I don't know, it shouldn't be there. I will check if I can rewrite the script

It seems that the intent was a sort of mapping, maybe the original idea was using a custom listing instead of original IDs

**Comment by Kitzunu** [comment]
Yea, I am importing TC's way of handling. I will test the fix and if it works I will make a PR

**Comment by LightDestory** [comment]
Yep, I checked TC's script too and it was good. I didn't want to open a PR because I didn't want to copy-paste TC code :(

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/7413 this works like a charm =)
