### ISSUE TITLE
Tanaris - Close ore node spawns

### ISSUE THREAD

**Issue by jmdha** [azerothcore/azerothcore-wotlk#7383]
### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1267

As can be seen in images, these nodes spawn very close to each other:
GUID: 5845 & 357
![image](https://user-images.githubusercontent.com/53914190/129583078-126723bb-9ed3-46fa-b692-183082bcd1fa.png)
GUID: 6581 & 17480
![image](https://user-images.githubusercontent.com/53914190/129583090-c89175db-9c0f-488d-acb6-f5285128bf54.png)

### Expected Blizzlike Behaviour

Nodes should not spawn too close to each other. Moreover, these should properly be in a pool, which they are not at the moment.

### Steps to reproduce the problem

1. .go o 5845
2. .go o 6581

### AC rev. hash/commit

28a764641

### Operating system

Windows 10 x64

**Comment by heyitsbench** [comment]
Resolved by https://github.com/azerothcore/azerothcore-wotlk/commit/25797238026ca87a9a3906add11ebfc9cc9802d4.
