### ISSUE TITLE
[Core]Glyph of the second talent can not be used

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#739]
Description: Glyph of the second talent can not be used

Current behavior: You can not use the glyphs in the first game unless you learn the second talent unless you return to the game again

Expected behavior: Glyphs must be learned simultaneously with two talents and two talents online

Steps to reproduce the problem:

1. Learn double Kai Fu use glyphs,
2. Switch the second talent using the same glyph
3. Glyphs can not be used

**AC hash/commit**:  AzerothCore rev [4bc2124](https://github.com/azerothcore/azerothcore-wotlk/commit/4bc2124632fd6f7120a6b5d6539ec0ad4795c142)

Operating system: Windows Se7en / 64bit

Modules: not used

1.Learn the second talent

2.Use Glyphs for Talents

3.Switch the second talent to use glyphs  >>>>>>>>>>Wrong Tip: You have learned some glyphs

4.Back to the role of choice to enter the game again ....Glyph normal use

**Comment by pklloveyou** [comment]
May be the problem here can not remove the old Glyph of aura
Player.cpp
    for (uint8 slot = 0; slot < MAX_GLYPH_SLOT_INDEX; ++slot)
        if (uint32 glyphId = m_Glyphs[GetActiveSpec()][slot])
            if (GlyphPropertiesEntry const* glyphEntry = sGlyphPropertiesStore.LookupEntry(glyphId))
                RemoveAurasDueToSpell(glyphEntry->SpellId);

**Comment by ShinDarth** [comment]
please add your  `AC hash/commit:` value

**Comment by pklloveyou** [comment]
@ShinDarth 
Thanks for reminding

**Comment by pklloveyou** [comment]
Old problems?

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/411#issuecomment-405388696
