### ISSUE TITLE
The Missing Diplomat - Private Hendel

### ISSUE THREAD

**Issue by wizzymore** [azerothcore/azerothcore-wotlk#7390]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Quest: https://wowgaming.altervista.org/aowow/?quest=1266
Quest start: https://wotlkdb.com/?npc=4967
Quest end: https://wotlkdb.com/?npc=4966

For this quest you're supposed to talk to Private Hendel in order to complete the quest. The problem is that he is standing there, being hostile(when he shouldn't be) and the 2 npc guards that stand close to him are attacking him(when they shouldn't be). He then kills them, because on top of being hostile he is also not dying, then they respawn again and the same thing keeps happening indefinitely. And if you try to go near him he will attack you which doesn't lead to anything besides you having to run away from him to reset him and not die from him. I'm pointing out those details just incase they are a factor of importance, the only actual problem I believe is him being hostile.

### Expected Blizzlike Behaviour

You are supposed to find Private Hendel and then talk to him in order to complete the quest. 
https://wowwiki-archive.fandom.com/wiki/Quest:The_Missing_Diplomat_(15)

### Steps to reproduce the problem

Get to the part of the quest chain before this quest, which is https://wowwiki-archive.fandom.com/wiki/Quest:The_Missing_Diplomat_(14). After taking the next quest teleport to NPC "Private Hendel" and you will see that he is hostile.
DB GUID: 31274, current GUID: 19225

### Extra Notes

This bug might be happening, because of the next part of the quest where you need to subdue Private Hendel. Something must be going wrong there with the guard npcs that are involved.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Related to https://github.com/chromiecraft/chromiecraft/issues/2019

Issue still exist. If Hendel able to kill player while script is going on - It makes NPC invulnerable. Players can not continue quest or repeat it.

https://user-images.githubusercontent.com/85256266/142657864-f4d10439-5174-48af-8abb-f86496cdd77f.mp4

**Comment by wizzymore** [comment]
```sql
(4966, 0, 4, 0, 2, 1, 100, 1, 0, 20, 300, 500, 0, 80, 496601, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Private Hendel - Between 0-20% Health - Run Script (Phase 1) (No Repeat)'),
```
Based on this, the npc will never be invulnerable, you just died too fast, he will stay hostile, that's for sure, but not invulnerable

**Comment by Shineslippers** [comment]
Well i did 100k damage while has 1.3k hp. I used wrong word? Anyway you can't kill him or finish quest. Need wait restart of server.

**Comment by wizzymore** [comment]
You used everything properly, when doing dmg to him and getting him to 1% please make sure you also are in combat with him, to assure you are not dieing you can use god mode.

**Comment by Shineslippers** [comment]
Sure. It was in 1st video, but not hard to repeat.

https://user-images.githubusercontent.com/85256266/142680945-01ee5aca-fcaa-4560-8947-574c90f859c1.mp4

**Comment by wizzymore** [comment]
Thanks for the additional videos, seems like this guy doesn't like to work properly.

**Comment by RetroDisko** [comment]
Hi there, today I am trying to do this quest and from distance I just see Hendel and the guards fighting. I waited until the guards all died then approached him, he was hostile the whole time, and when I dropped him to 1 hp, there's still no rp or anything. Like he doesn't die, and I still cannot interract with him. Thank you for your time!

**Comment by Gultask** [comment]
Seems like a similar thing happened again: https://github.com/chromiecraft/chromiecraft/issues/3442

Apparently he'll be "tagged" but otherwise friendly to Alliance players, but they won't be able to interact with him to turn-in quests or whatnot. I've tried logging in my Horde character but he was invincible, stuck at 1 hp, so it wasn't possible to reset him that way.

**Comment by Gultask** [comment]
> @Gultask I just confirmed the issue: it is linked to the issue meantioned above.
> 
> If you fight him and his guards he doesnt get subdued and doesnt switch his status to the follow-up quest He is friendly but i am still in combat
> 
> ![WoWScrnShot_050422_100901](https://user-images.githubusercontent.com/43603807/166644606-411861b9-b58f-4b59-96d4-850cef083c89.jpg)

Tested it too and it seems quest 1324 progression is bugged and Hendel doesn't get 'subdued'. Tested with a local AC.

**Comment by Alarine** [comment]
Private Hendel is still bugged I can't turn in the quest before with him. Is there a way to complete the quest please?

**Comment by Gultask** [comment]
@Alarine 
You can try opening a ticket in Discord under the channel #support-ticket and "Request help with your account/character" and the GMs should be able to help you out.

**Comment by 55Honey** [comment]
We can not help with quest completion for bugged quests, sadly. It would be an overwhelming amount of work to start this.

**Comment by heyitsbench** [comment]
This issue still occurs as of https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1.
![image](https://user-images.githubusercontent.com/38561765/184471185-b4ea7df8-4cb3-4939-9d1f-67b1b669a52a.png)
