### ISSUE TITLE
[Animation error] No pick displayed when approaching a vein in druid form

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7399]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1448

When mining an ore vein, pick is not displayed on character and it does the movement with the arms but without any tool. This only occurs when the mining animation is started while on druid form. Of course, unlike with herbalism, upon starting mining some vein the druid form aura should get cancelled, but that doesn't mean pick should disappear. If we manually cancel any druid form before starting mining, pick will appear perfectly.

Testers note:
This also occurs in ghost wolf form.
Image:
![image](https://user-images.githubusercontent.com/53914190/129701181-3c04143b-cb62-4380-ae5d-291d4ac619f9.png)
![image](https://user-images.githubusercontent.com/53914190/129701195-5dc1cea9-6b21-4b54-95df-2edd10eb1e8f.png)

### Expected Blizzlike Behaviour

When starting to mine some vein, any druid form / aura should get cancelled and our character should start mining. On this animation, pick should show in the hands of the character.

### Steps to reproduce the problem

Have Mining profession on a druid player
While on druid form (bear, dire bear, travel form…), approach a mineral vein
Click on vein so it starts mining
Druid form aura will get cancelled and mining animation will start
Animation doesn't show any pick or tool
Mining process is completed successfuly

### Extra Notes

![Uploading  2021-08-17 at 09.56.59.png…]()

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
It's completely clientside visual.
