### ISSUE TITLE
Fix Pit of saron Scene

### ISSUE THREAD

**Issue by talamortis** [azerothcore/azerothcore-wotlk#74]
**Description**:
Pit of saron Start
**Current behaviour**: Tell us what happens
As you enter pit of saron the NPC dont run out the portal and the content dont start

**Expected behaviour**: Tell us what should happen instead
As a player enters the instance they should spawn all the mobs to gain the senario

For this to work, you have attak one of the npc channeling.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
Master 

Fix
in instance_pit_of_saron.cpp

void OnPlayerEnter(Player* plr)
{
            instance->LoadGrid(LeaderIntroPos.GetPositionX(), LeaderIntroPos.GetPositionY());

           if (Creature* c = instance->GetCreature(GetData64(DATA_LEADER_FIRST_GUID)))
               c->AI()->SetData(DATA_START_INTRO, 0);
}

**Comment by Yehonal** [comment]
Please could you open a PR with that fix? and link to this issue

**Comment by ShinDarth** [comment]
see https://github.com/azerothcore/azerothcore-wotlk/pull/75
