### ISSUE TITLE
Lower Ranked Spells not Learnt automatically

### ISSUE THREAD

**Issue by immvp** [azerothcore/azerothcore-wotlk#740]
**Description**:
The function doesn't work correctly
**Current behaviour**: Tell us what happens
When learning a high rank spell without having leant the lower ranks (i.e learning Frostbolt Rank 9 without Rank 8, 7, 6 etc.....) you simply get Frostbolt Rank 9, and not the previous ranks.
**Expected behaviour**: Tell us what should happen instead
Upon learning, in this example Frostbolt Rank 9, you should learn ALL the previous ranks aswell if they are not already leant.
**Steps to reproduce the problem**:

1. Learn a higher rank spell without having the lower ranks in your spellbook.
2. Check your spellbook.

**Branch(es)**: master

**AC hash/commit**:  8ad38858dd3cc7971ced56ae248abc033fe14533

**Operating system**:  Linux Ubuntu 14.04

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Maurowin** [comment]
not confirm in a0d17509a2c0+
![wowscrnshot_122217_214909](https://user-images.githubusercontent.com/31663279/34312118-0afcfbb0-e762-11e7-87eb-d1c0e5942fa0.jpg)

**Comment by immvp** [comment]
You seem to have misunderstood the bug. Use a GM command to learn a spell, and then if it's a high rank (rank 9 frostbolt for example) you won't learn the previous ranks (rank 8, 7, 6 etc.)

**Comment by Maurowin** [comment]
Gm can do everything he want ^^

**Comment by Maurowin** [comment]
Oh ok, doesn't test yet.

**Comment by pklloveyou** [comment]
@immvp This is normal, GM command authority is high!

**Comment by talamortis** [comment]
This is not an issue anyway as all spells from trainer require previous ranks, as @pklloveyou said only gms can do this.
