### ISSUE TITLE
Profession spells are learnt twice

### ISSUE THREAD

**Issue by jarrodjeffi** [azerothcore/azerothcore-wotlk#7415]
**CURRENT BEHAVIOUR:**
Profession spells are learnt twice.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Only one instance of a spell should be learnt.

**STEPS TO REPRODUCE THE PROBLEM:**
1. Learn a profession such as First Aid
2. You will learn two instances of every spell such as Linen Bandage
3. This can be confirmed by checking your spellbook

**AC HASH/COMMIT:**
c7ee70ea75ff4d6729d8cfc0cbb4ac4d01ac67ee

**OPERATING SYSTEM:**
Ubuntu 20.04 LTS

**MODULES:**
`mod-autobalance`

**CUSTOMIZATIONS:**
Max player level is 19.

**Comment by jarrodjeffi** [comment]
After some testing I've localised the problem to 3487973c0e9802990e91ba52d38f59a4999ee45b. Built against 5c1b1299e74b97a2820d5a00655f8a9e685ded7e for now where the bug doesn't exist. Will sit on that commit until there's some action on this issue.

**Comment by wizzymore** [comment]
Hi @jarrodjeffi, please use the Bug Report template to report a bug and also put the Hash your server is using.

Nonetheless, i can confirm this is happening.

To test this:
.go c 46192 and learn herbalism, you will get 2 Find Herb spells until you relog.

**Comment by Kitzunu** [comment]
are the spellid's the same?

**Comment by jarrodjeffi** [comment]
Sorry, new to posting issues and such. Updated my opening post.

**Comment by wizzymore** [comment]
> 
> 
> are the spellid's the same?
> 
> Also feel free to open a new report the proper way if the author doesn't update this in time

Same id

**Comment by IntelligentQuantum** [comment]
![Screenshot_20210920_120843](https://user-images.githubusercontent.com/14080516/133970162-6f656043-fb64-4b7c-8f6a-ce0643b0e6e3.png)

This problem did not exist before .....

**Comment by LukasVolgger** [comment]
> ![Screenshot_20210920_120843](https://user-images.githubusercontent.com/14080516/133970162-6f656043-fb64-4b7c-8f6a-ce0643b0e6e3.png)
> 
> This problem did not exist before .....
> But when you relog it back to normal

Confirm.

**Comment by 55Honey** [comment]
This issue is linked to https://github.com/chromiecraft/chromiecraft/issues/1624 which seems quite game-breaking to me.
In short: Players keep the spells from an unlearnt profession, like stamina from mining, crit from skinning and lifeblood from herbalism, when they unlearn the profession.
