### ISSUE TITLE
[Winterspring] Watery Invaders despawn shortly after spawning

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7418]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: [Chromie issue#1455](https://github.com/chromiecraft/chromiecraft/issues/1455)

Watery Invaders (entry 14458) (https://wowgaming.altervista.org/aowow/?npc=14458)  in winterspring despawn shortly after they spawn.

https://user-images.githubusercontent.com/80769357/129850016-f03ee1ff-cbf5-49e1-a935-ea54d077af80.mp4

https://user-images.githubusercontent.com/80769357/129850057-a3943b34-22dd-48b2-a8eb-78a3632863bd.mp4

### Expected Blizzlike Behaviour

Watery Invaders should stay spawned untill killed.

395025 on 2009/06/19 (Patch 3.1.3)
They spawn as part of the old Elemental Invasions with an Elemental Prince/Princess, which in this case is Princess Tempestria. Curiously, after she's been killed, these will linger around indefinitely until they're killed. After she's been killed, they won't respawn until she respawns.

### Source

https://tbc.wowhead.com/npc=14458/watery-invader#comments

https://www.wowhead.com/npc=14458/watery-invader#comments

### Steps to reproduce the problem

1. GO to Lake Kel'Theril in Winterspring during elemental invasion
2. Observe the Watery Invaders spawning

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend[(https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (da1fd68).

**Comment by syssneck** [comment]
Same as in: [#7369](https://github.com/azerothcore/azerothcore-wotlk/issues/7369) and [#7417](https://github.com/azerothcore/azerothcore-wotlk/issues/7417)

**Comment by gurveleg** [comment]
Same thing as the other two invasions:
First it doesnt work at all, all mobs despawning immediately, then starts working, spawning mobs left and right, then these same mobs some time later start despawning. No one was killing any.
![awadad](https://user-images.githubusercontent.com/80769357/129886295-d48b7500-4028-4213-9d31-583c08c4d415.jpg)

**Comment by Si1ker** [comment]
Cannot repro, waited for a minute, no despawn
commit a97e73e

![image](https://user-images.githubusercontent.com/61223313/132401179-55b2741f-46c0-4e46-a601-2d1e389e5e31.png)

**Comment by Ragelezz** [comment]
Check SmartAI section:
https://wowgaming.altervista.org/aowow/?npc=14458#summoned-by-object
https://wowgaming.altervista.org/aowow/?object=179665

**Comment by UltraNix** [comment]
@Ragelezz ??
