### ISSUE TITLE
Core/Aura: Mechanics are faulty.

### ISSUE THREAD

**Issue by immvp** [azerothcore/azerothcore-wotlk#743]
**Description**:
Aura Rules doesn't work.
**Current behaviour**: Tell us what happens
Slow Effects currently Stack.
**Expected behaviour**: Tell us what should happen instead
When a stronger slow effect is applied, for example Hamstring, on a target that has a weaker slow effect, for example Frostbolt, then the stronger slow effect should overwrite it.
Evidence: Gif generated from [this](https://www.youtube.com/watch?v=RQKhiRTWRX8&t=166s) video:
https://gyazo.com/2c53408b80cb8865819780c8d711b131
**Steps to reproduce the problem**:

1. Apply Frostbolt to Target.
2. Apply Hamstring to Target.
3. Look at targets debuffs. It now has both Frostbolt and hamstring on.

**Branch(es)**: master

**AC hash/commit**:  fca0bfd

**Operating system**:  Linux Ubuntu 14.04

**Modules**:  None.

**Other Customizations**: None.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by immvp** [comment]
Bump, still an issue

**Comment by talamortis** [comment]
does the slow effect stack?

**Comment by immvp** [comment]
@talamortis No it does not. It's not supposed to, either. It currently prioritizes stronger slows over weaker ones, instead of just removing the weaker ones all together.

**Comment by talamortis** [comment]
i understand that but the debuff of all slow effects should still be shown on targets since if Hamstring has like 5 seconds left and frostbolt has 10 seconds it should go straight to the frostbolt effect.

**Comment by immvp** [comment]
@talamortis You can say that, but if you look at the gif which was taken from a video which was recorded on retail back in 3.3.5a, Hamstring overwrote Frostbolt, making Frostbolt dissapear from the target.

**Comment by immvp** [comment]
https://gyazo.com/2c53408b80cb8865819780c8d711b131

**Comment by Kaev** [comment]
The video you posted was made in WotLk beta, not in 3.3.5. Is there any 3.3.5 source?

**Comment by immvp** [comment]
3.3.5 source:
https://gyazo.com/91ef36ddc114e9276fa360fc4654fcb2

gif generated from:
https://www.youtube.com/watch?v=BCrMwouzzFA
at time stamp **1:06**

**Comment by Nefertumm** [comment]
It seems to be something that pussywizard or xinef did intentionally. In the original SC description they wrote: 

> If required, allows to have multiple auras applied that shouldn't stack with each other. In such situations only the strongest effects of all the auras are working.
Maybe this is one of these "situations".

**Comment by immvp** [comment]
@Nefertumm Perhaps. Doesn't matter if they did it intentionally tho'. Not relevant at all. What matters is what is Blizzlike. And Frostbolt and Hamstring being on the same target at the same time is not Blizzlike.

**Comment by Nefertumm** [comment]
I'm not saying that. This needs to be fixed.

**Comment by temperrr** [comment]
This has been fixed meanwhile
