### ISSUE TITLE
Ghost Mushroom spawing inside ores

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7432]
### Current Behaviour

On local server(AC a43d76ede)
As can be seen in the picture below, a mushroom had the same spawn position as two ores.
![image](https://user-images.githubusercontent.com/53914190/129934374-d1f44068-f4f4-4771-b325-a512842178c9.png)

### Expected Blizzlike Behaviour

I don't have a source stating that it shouldn't be possible, but I don't think it is a controversial opinion.

### Steps to reproduce the problem

.go o 16436

### AC rev. hash/commit

a43d76ede

### Operating system

Windows 10 x64

**Comment by FrancescoBorzi** [comment]
don't forget the project too @jamadaha
