### ISSUE TITLE
Command Instance Unbind

### ISSUE THREAD

**Issue by mtgcores** [azerothcore/azerothcore-wotlk#7434]
### Current Behaviour

When using the command .i u all or .instance unbind all the server closes and receives error log

### Expected Blizzlike Behaviour

Use the .i or all command
https://media.discordapp.net/attachments/284406375495368704/877363921655316540/unknown.png

### Steps to reproduce the problem

Use the .i or all command

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a43d76ede4d13a904c7416d1bda698b8dc1d0fe8

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
```
Command: .i u all [Player: Awd (GUID Full: 0x0000000000000007 Type: Player Low: 7) (Account: 11) X: 5777.391602 Y: 692.016724 Z: 642.976440 Map: 571 (Northrend) Area: 4613 (Dalaran City) Zone: Dalaran Selected:  (GUID Full: 0x0000000000000000 Type: None Low: 0)]
```

Works with no crash and no error.

could you paste the content of `.server debug` please

**Comment by mtgcores** [comment]
You can close it. it was my installed command module that was causing the problem

Was solved
