### ISSUE TITLE
[IDEA] Implement a custom RBAC system

### ISSUE THREAD

**Issue by Deku** [azerothcore/azerothcore-wotlk#746]
_RBAC = Role-Based Access Control_

I open this issue so we can discuss the implementation of a custom RBAC system, different from what's currently used in TrinityCore.

**Background**
I've been around gaming servers for many years, on the player side and on the admin side, having experience managing servers for WoW, Mu Online and Minecraft.

Currently I'm migrating the WoW server where I colaborate from TrinityCore to AzerothCore for "reasons", and we used the RBAC system that TC had, so obviously, I was asked to implement it again. @Yehonal and @Irome  saw that and asked if I could push those changes to AC's repo. While doing that, I noticed that the static-defined permissions used by TC would give some trouble with the modularity that defines AC, given the following:

- Mod developers might need to patch the enum defined in RBAC.h (alternative is defining a local module enum)
- There could be conflicts between modules defining permissions in the same number range
- There's no centralized catalog/index to synchronize modules developed for AzerothCore

Hence, I propose the following.

**Proposal**
Implement a RBAC system that uses role inheritance (check [NIST Hierarchical RBAC Model](https://csrc.nist.gov/CSRC/media/Publications/conference-paper/2000/07/26/the-nist-model-for-role-based-access-control-towards-a-unified-/documents/sandhu-ferraiolo-kuhn-00.pdf)), to group users under roles, and assign permissions to those roles. 

![ac_rbac_implementation 2](https://user-images.githubusercontent.com/800655/34420814-03bf9afe-ebe2-11e7-871b-3878fcaeea57.png)

- The user could be assigned to one or more roles.
- Roles could inherit permissions from one or more roles.
- Admin can define a default role for new users.
- Roles can have ranks to facilitate promotion/demotion.
- Permissions can be assigned to roles.
- Permissions can be allowed or denied from roles (allow by default). This means, if _by inheritance_ role **"X"** has permission **"Y"**, you can _deny_ access to "Y" for "X", overriding the inheritance.

To ensure a flexible way of defining permissions I think that using the Minecraft-way could be an option, this means, using strings to define dot-separated namespaces.

Examples: 
- core.accounts.create - Permission to create accounts
- core.login.skipqueue - To skip waiting in the queue to log in
- mod.transmog.use.legendary - Allow use of legendary items in the Transmog module
- mod.duelreset.use - Allow use of module DuelReset

**What else could be added?** _(not to be considered on first stage)_
- Timed permission: give a permission with expiration time
- Timed roles: give a role with expiration time
- Include "*" wildcard to grant all sub permissions in the namespace

Further reading and source of inspiration: [PermissionsEx plugin for Minecraft](https://github.com/PEXPlugins/PermissionsEx/wiki)

**Comment by Rochet2** [comment]
How the ranks would work if a user can have multiple roles, each with different id and rank? You wouldn't then be really able to see if player X < Y using ranks, unless rank is part of the ID in some way.
User cannot directly have a permission without role?

**Comment by Deku** [comment]
@Rochet2 you are right about ranks. An option could be to add a "path" attribute to the roles, so they could reference a linear succession of roles but that would be an optional use case and we could let ranks out for the moment.

Now, for user permissions, from experience I would not advice to allow that since it doesn't help to maintain a clean permissions structure. But if the AC team decided to include it, then it can be done.

**Comment by Deku** [comment]
I'm going to work this RBAC system as a module, and propose a more dynamic option for the core.
