### ISSUE TITLE
(Uldaman/Ironaya): Pets can pull Ironaya through the closed door

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7465]
### Current Behaviour

If you are a Hunter, you can use growl from your Pet, to aggro Ironaya through the closed door, so that the staff is not needed if you have a Hunter in the group. I'm not sure, if this could be more of a general issue with growl, than for this specific boss.

https://user-images.githubusercontent.com/68868567/130196593-73461e67-c2f9-4a4b-87a1-0239a2cfa6a9.mp4

### Expected Blizzlike Behaviour

- Pets shouldn't walk through closed doors/walls.
- You should only be able to engage Ironaya, if you have the staff and start the event

### Steps to reproduce the problem

1. Be a Hunter and have a pet
2. `.tele Uldaman`
2. Walk up to the closed door where Ironaya resides
3. Target Ironaya and use Growl on her
4. See your pet walking through the closed door and aggroing her
5. Use Follow from your Pet now, to pull her through the closed door

### AC rev. hash/commit

AzerothCore rev. 888549bcdc26 2021-08-20 14:41:26 +0200 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 80025
Using CMake version: 3.21.0-rc2
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_08_20_01
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Win 10 x64

**Comment by JamesGent** [comment]
Can you check if you can taunt her in other ways, such as Warrior Taunt, or AOE casting?

We had an issue in WSG where walls/windows were treated as though you could cast through them, it might be that same issue.

**Comment by syssneck** [comment]
Okay, it is not only with Growl. It also works with Rake and Claw. No Success with Warrior taunts.

**Comment by Si1ker** [comment]
Still doable with any pet from hunters/warlocks.

![2021-09-14 20_05_56-World of Warcraft](https://user-images.githubusercontent.com/61223313/133443295-0451f1b4-d302-4df8-b4ee-0baa02b9c676.png)

Source of how it should be initiated: https://youtu.be/GHsytWhHKNA?t=575
