### ISSUE TITLE
[Dungeon Finder] Roll Rules for classic dungeons

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#7467]
### What client do you play on?

ruRU

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Now classes can only roll their own type of armor in classic dungeons. For example, druid healers can only roll leather, but cannot roll cloth.

### Expected Blizzlike Behaviour

Items that do not exceed level 70 should not have class restrictions on the type of armor. For example 35 ilvl cloth can roll paladins, shamans, druids.

### Source

Blue post:
https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

> The player’s class must be able to equip the item, either at the time of the roll or at a later level. For example: A level 38 shaman would able to roll "Need" on a level 42 mail item; however, he or she would not be able to roll "Need" on a plate item.
The armor proficiency of the player’s class must not be higher than the item being rolled on. If it is, the player will unable to roll “Need.” For example: A level 75 warrior would unable to roll "Need" on certain mail items. **(This restriction will only come into play for items with an iLevel above 70.)**
If a player’s class is pure melee, he or she will be unable to roll "Need" on spell power items. Pure melee classes include rogues and warriors. Druids, paladins, death knights, and shaman may still roll "Need" on spell power items, provided that the above two conditions are met.

Video:
3:09 - paladin can roll leather
https://youtu.be/tTwgdv53FrU?t=190 

upd
2:50 - Shaman press "Need" Cloth Hands
https://youtu.be/546hZW_ohzg?t=170

6:02-6:04 - Shaman press "Need" Cloth Head
https://youtu.be/G2lbPy6VN_M?t=360

upd
8:50 - Shaman Greenar press "Need" Cloth Wrist
https://youtu.be/-3Sr-0pcZkg?t=531

7:10 - 7:37 - Druids Saine and Romane press "Need" Cloth Head
https://youtu.be/86CqyD7NfeU?t=430

upd

2:26 - Resto Shaman can press "Need" Cloth Chest and do it. This is cross server party consists of prot war, **resto shaman, mage**, hunter and rogue.
https://youtu.be/s2VokcGf3M8?t=146

### Steps to reproduce the problem

Queue for a dungeon finder.

### Extra Notes

Original Report: https://github.com/chromiecraft/chromiecraft/issues/1460

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Additionally, if I'm not mistaken, rule one from the blue post is also not in place (yet):

"The player’s class must be able to equip the item, either at the time of the roll or at a later level. For example: A level 38 shaman would able to roll "Need" on a level 42 mail item; however, he or she would not be able to roll "Need" on a plate item."

I was not able to roll on plate with my warrior before lvl 40. The same goes for paladins (can't roll on plate before lvl 40 but should be able to) and shamans and hunters for mail.
