### ISSUE TITLE
Extremely Loud Noise bug Garr boss (Molten Core)

### ISSUE THREAD

**Issue by Middel** [azerothcore/azerothcore-wotlk#747]
**Description**:

In Molten Core at the boss called Garr, there is a extremely loud sound bug going on. it is for sure tied to the boss. because when it dies it stops. also the adds that are supposed to surround the boss are not surrounding the boss.

See this video i've recorded to show this bug: https://youtu.be/_RrFhayULwk

**Current behaviour**: Tell us what happens

Whenever you get near the boss. there is this loud noise like its indicating adds are stuck underneath the ground.

**Expected behaviour**: Tell us what should happen instead

No sound like this, and the adds need to surround the boss

**Steps to reproduce the problem**:

1. Go into molten core (Raid)
2. Go towards the boss Garr
3. enjoy loud noises.

**Branch(es)**: Master branche

**AC hash/commit**:  -37e9160e88b4- <-Revision

**Operating system**:  Windows 7

**Modules**:  NPC Giftbox, Anti-Cheat, Transmorg NPC, Spells mod.

**Other Customizations**: No

**Comment by Inifield** [comment]
Could be bad sound insert in DB, corrupted client or  problems in locales

**Comment by Middel** [comment]
I think we can rule out the corrupted client part. because we noticed it initially when we where running it with players on the server. and everyone was able to hear it. (talking about 8 people). all using enUS locales. now about the database part i have no idea. so i'll await a response from the azerothcore team.

**Comment by pklloveyou** [comment]
zhCN NO,,,,

**Comment by talamortis** [comment]
I will take a look later see if I can see anything

**Comment by Inifield** [comment]
Cannot confirm on windows 10, on a0d17509
https://streamable.com/7pz7v
