### ISSUE TITLE
GM Command .modify speed does not affect targeted player as expected

### ISSUE THREAD

**Issue by drozco** [azerothcore/azerothcore-wotlk#7473]
### Current Behaviour

Targeting a player and attempting .mod speed x instead applies the speed modification to the GM character.

### Expected Blizzlike Behaviour

Expectation is to modify the target player's speed, as defined in the GM commands list:

Modify the running speed of the selected player to "normal base run speed"= 1. If no player is selected, modify your speed. $speedtypes may be fly, all, walk, backwalk, or swim. #rate may range from 0.1 to 50.

### Source

Within the file cs_modify.cpp:
It would appear that there's an extra check if the player is a GM account which then sets the target to the GM, even if it had a target already:

    Player* target = handler->getSelectedPlayerOrSelf();
    if (AccountMgr::IsGMAccount(handler->GetSession()->GetSecurity()))
        target = handler->GetSession()->GetPlayer();

This check is repeated within all the speed related commands.  Other modify commands do not seem to have this.  I don't know why this extra check is there.  Removing it fixes the command, but don't know if it's checking something additional, so I need clarification before a PR.

### Steps to reproduce the problem

1. Get on a GM account at least level 2
2. Target a player in game that is not a GM
3. Issue command .mod speed 4
4. Observe that the GM's speed is modified, not the target player

### AC rev. hash/commit

AzerothCore rev. ff7d6d2daeb4+ 2021-08-20 00:01:48 +0200 (master branch) (Unix, Release, Static)

### Operating system

Ubuntu 20.04 LTS

### Custom changes or Modules

None relating to this.

**Comment by Eronox** [comment]
Maybe it was done like this to prevent GM abuse. But for us I suppose it doesn't matter if we allow it or not, I'd vote on allowing it

**Comment by Nyeriah** [comment]
> Maybe it was done like this to prevent GM abuse. But for us I suppose it doesn't matter if we allow it or not, I'd vote on allowing it

Feel free to PR it, I do believe it might be a Sunwell leftover

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9474/files#diff-028f5f9992c728ceca08b689a9e95f3fbccf51d2e1cb16878b9209e45540e525L637
