### ISSUE TITLE
[Ghostlands] Many Sentinel Spy mobs missing movement

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7474]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: [Chromie issue#1476](https://github.com/chromiecraft/chromiecraft/issues/1476)

Many Sentinel Spy (https://wowgaming.altervista.org/aowow/?npc=16330) in Ghostlands are missing movements.

GUIDs: 82136, 82137, 82139, 82144, 82135, 82142, 82144, 82149, 82151, 82150, 82153, 82154, 82721, 82722

### Expected Blizzlike Behaviour

Those Sentinel Spies who are spawned at tents should remain stationary, others should be roaming around.

### Source

https://youtu.be/E_k7PGkHyL4?t=1231

### Steps to reproduce the problem

1. Teleport to provided GUIDs
2. Observe

### Extra Notes

Following GUIDs should remain stationary: 82140, 82143, 82146, 82152, 82148, 82156, 82155
These are the Sentinels spawned at the tents and they should be stationary going by TBC footage.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (888549b).

**Comment by malcrom** [comment]
Fixed here https://github.com/azerothcore/azerothcore-wotlk/pull/9696
