### ISSUE TITLE
[Ghostland] Phantasmal Watcher missing movement

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7483]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1489

Phantasmal Watchers are stationary. (https://wowgaming.altervista.org/aowow/?npc=16311)

 GUID 82448, 82699, 82727, 82728, 82733

### Expected Blizzlike Behaviour

There only are 5 spawned currently, but TBC map shows many points (81) so presumably these mobs should patrol around a bit further instead of a short roam around spawn to cover that area. They are a bit clustered together, while the TBC map shows them all around Dead Scar between the two roads

https://tbc.wowhead.com/npc=16311/phantasmal-watcher#map

Testers note:
Looking through the provided videos, it is possible to see at least three of them patrolling along the scar. I spotted two patrolling along the edge in a pattern similar to this:
![image](https://user-images.githubusercontent.com/53914190/130327323-befb6df4-bd34-4898-b42b-7d7530731c98.png)

Although, I'm not certain that it's that exact route.

### Source

https://youtu.be/E_k7PGkHyL4?t=4302 
https://youtu.be/oIfd-9fdGxM?t=148
https://youtu.be/oIfd-9fdGxM?t=234
TBC classic videos, but you can see the Phantasmal Watchers moving around the Dead Scar.

### Steps to reproduce the problem

1. Teleport to GUIDs
2. Observe no movement.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@jamadaha don't forget the project too ;)

**Comment by acidmanifesto** [comment]
Closed via PR https://github.com/azerothcore/azerothcore-wotlk/pull/9818 
Not entire sure why it did not auto close the issue
