### ISSUE TITLE
Core/Spell: Gouge can't be blocked.

### ISSUE THREAD

**Issue by immvp** [azerothcore/azerothcore-wotlk#749]
**Description**:
Gouge can't be blocked.
**Current behaviour**: Tell us what happens
Gouge isn't being blocked, even when the Warrior has Shield Block up (which increases block chance by 100%)
**Expected behaviour**: Tell us what should happen instead
When casting Gouge on a target that has Shield Block up then it should be blocked. Gouge in general SHOULD be blockable.
**Steps to reproduce the problem**:

1. Cast Shield Block on a Warrior.
2. Cast Gouge on that Warrior.
3. Watch Gouge go through the Shield Block every single time.

**Branch(es)**: master

**AC hash/commit**:   b669d24

**Operating system**:  Ubuntu 14.04

**Modules**:  Are you using modules? No.

**Other Customizations**: None.

**Comment by Kitzunu** [comment]
Werid, it has this attribute SPELL_ATTR3_BLOCKABLE_SPELL so it should work.

Guess debugging is in order :D

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/102703048-4d8d3b00-426a-11eb-9fac-01cbb699b0e4.png)

Can't reproduce.
