### ISSUE TITLE
Azshara - Incorrect Respawn Timer For Gatekeeper Rageroar 

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7500]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1500

Gatekeeper Rageroar GUID 36519 (https://wowgaming.altervista.org/aowow/?npc=6651) is on a 2h respawn timer.

Tester: confirmed 2h respawn.

### Expected Blizzlike Behaviour

Gatekeeper Rageroar is listed as semi-rare and thus should be on a 10.5-16h respawn timer.

![rageroar](https://user-images.githubusercontent.com/80769357/130336790-9bf8a440-d5db-44be-877d-74cf21d05fae.jpg)

### Source

World of Warcraft Atlas

### Steps to reproduce the problem

1. Check Gatekeeper Rageroar spawn timer in DB

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Tr1v1an** [comment]
I took the liberty to look into this as my first initial issue and it seems the column in table `creature_template` that is used for `corpse decay` and `respawn time` is called `rank`.

![image](https://user-images.githubusercontent.com/89851300/131519318-1af32537-0877-4588-a5d7-18253cc39462.png)

If you see the above image, AzerothCore handles 5 different ranks starting from 0. I connected to the SQL database and noticed that the rank for Gatekeeper Rageroar is `4`.

I used this command to check it:
`SELECT * FROM creature_template WHERE NAME = "Gatekeeper Rageroar"`

I don't know if AzerothCore maintains a different respawn timer matrix than the original game. Perhaps someone from the development team can verify?

**Comment by Asthalor** [comment]
Hello @Tr1v1an !

You can check the spawn timers on the table `creature`. You will need the id of Gatekeeper Rageroar to check his data.
The timers of the spawn is listed in seconds, so if its needed to change the spawn rate its important to check from hours and then transform into seconds.

**Comment by Azcobu** [comment]
Hey @Tr1v1an, welcome to the project.

The rank for this NPC is 4 as you say, but for the vast majority of NPCs in the database, respawn times are handled by the `spawntimesecs` field of the `creature` table, which overrides the default values you show above. If you go to `creatures` and have a look at `guid` 36519 you will find the single instantiation of this particular NPC with the 7200 sec spawn time mentioned above.

**Comment by Tr1v1an** [comment]
Hi @Asthalor and @Azcobu,

Thank you for the quick response! I've managed to update the database with the new timer and will check later this evening if the actual time is implemented on my local system and afterwards make a PR to the main project.

Do you guys have any tips for new contributors?

**Comment by Azcobu** [comment]
I found the AC wiki's [SQL Standards](https://www.azerothcore.org/wiki/sql-standards) page handy when I was starting out. You've probably also looked at the wiki page on [how to create a PR](https://www.azerothcore.org/wiki/how-to-create-a-pr) but if you're doing a simple SQL fix then there's a page on [How to create a DB PR via GitHub](https://www.azerothcore.org/wiki/how-to-create-a-db-pr) which might also be useful for you. 

As for other tools and tips - are you using [Keira3](https://github.com/azerothcore/Keira3)? If not it's worth a look, as it's designed by by AC's lead devs as a DB editor specifically targeting AzerothCore. The AC and CC Discords are also both worth checking out - the AC leaning more towards devs, while CC is for everyone but also hosts Chromie's player community. Hope some of that helps.

**Comment by Tr1v1an** [comment]
I've created my first pull request, I hope I filled everything in and tested accordingly. I wasn't going to wait 10.5 hours for it to respawn but it seems `.npcinfo` did the trick. Looking forward to picking up more challenging items!

Thanks for the initial info!
