### ISSUE TITLE
[Quest/Mining] "The Spectral Chalice" should not be available to non-miners, also wrong position

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7502]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1504

The quest "The Spectral Chalice" is available to non-miners.
![image](https://user-images.githubusercontent.com/22718174/130339112-001f007d-5557-4582-a986-928d07a22ab2.png)

Testers note:
Tried following the steps, could complete the quest, but couldn't complete the part where you get the skill on a char without mining.

### Expected Blizzlike Behaviour

The quest "The Spectral Chalice" should only be available to miners with 230 or higher mining.

### Source

> The quest is only offered if you're a miner. I think you might also need to be 230, not positive but I dont remember being offered the quest til 230+

https://classic.wowhead.com/quest=4083/the-spectral-chalice#comments:id=71298

The quick facts on this page shows 230 mining and gives no skill point when smelted.
https://classic.wowhead.com/spell=14891/smelt-dark-iron

> This quest teaches those with 230 mining skill how to smelt [Dark Iron Ore] into bars.

https://wowpedia.fandom.com/wiki/The_Spectral_Chalice

### Steps to reproduce the problem

Bring a 230 or higher miner.
Let the miner speak to Gloom'rel, it will make the Spectral Chalice appears next of Anger'rel (should have been next of Gloom'rel).
Let the non-miner interact wth the Spectral Chalice.

### Extra Notes

The Spectral Chalice should spawn next of Gloom'rel due to the following quotes.
> Player: Gloom'rel, tell me your secrets!
The Spectral Chalice spawns beside him.
You wish to learn the old craft? You wish to smelt dark iron?
Appease me, < race >. Show me a sacrifice and I will consider it

https://wowpedia.fandom.com/wiki/Gloom%27rel

![image](https://user-images.githubusercontent.com/22718174/130339480-e67b51f8-c490-45f4-b482-6c3652504788.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
Im on it. Looks like only changing the skill required is not enough, because while testing the gossip option is not even present, and the place of the Spectral chalice is in the wrong place.
Source https://youtu.be/kvbHzgA-sxg?t=254
