### ISSUE TITLE
[Ghostlands] Multiple Deatholm Acolyte and Fallen Ranger missing movements

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7505]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1509

Deatholm Acolytes (https://wowgaming.altervista.org/aowow/?npc=16315):

GUID 82528, 82514, 82531, 82540, 82529, 82544, 82547, 82545

and Fallen Rangers (https://wowgaming.altervista.org/aowow/?npc=16314):

GUID 82523, 82525, 82530, 82532, 82526, 82534, 82533, 82543, 82546

are stationary.

Testers note:
Haven't checked whether they should all be moving, but here are all the GUIDs of those with missing movement:
guid | id | wander_distance | MovementType
-- | -- | -- | --
82523 | 16314 | 0 | 0
82525 | 16314 | 0 | 0
82526 | 16314 | 0 | 0
82530 | 16314 | 0 | 0
82532 | 16314 | 0 | 0
82533 | 16314 | 0 | 0
82534 | 16314 | 0 | 0
82535 | 16314 | 0 | 0
82543 | 16314 | 0 | 0
82546 | 16314 | 0 | 0
82514 | 16315 | 0 | 0
82528 | 16315 | 0 | 0
82529 | 16315 | 0 | 0
82531 | 16315 | 0 | 0
82540 | 16315 | 0 | 0
82544 | 16315 | 0 | 0
82545 | 16315 | 0 | 0
82547 | 16315 | 0 | 0

### Expected Blizzlike Behaviour

They should all be moving around.

Deatholm Acvolyte GUID 82514 should have a proper patrol route from the entrace (his current spawn) to the tower and back.

### Source

https://youtu.be/iUj39iEBKYY?t=189

TBC Classic, you can see all of mobs moving, no stationaries, and you can see that 1 Acolyte patroling on the road to tower and back down.

### Steps to reproduce the problem

1. Teleport to provided GUIDs
2. Observe no movement

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Closed via PR https://github.com/azerothcore/azerothcore-wotlk/pull/9818 
Not entire sure why it did not auto close the issue
