### ISSUE TITLE
[DB] Scholomance torch

### ISSUE THREAD

**Issue by tea91** [azerothcore/azerothcore-wotlk#751]
**Description**:
Door problem. 

**Current behaviour**: Tell us what happens
The Door(Go entry id =175610) must open when worked a torch at Jandice Barov's room

**Expected behaviour**: Tell us what should happen instead
Active secret torch -> Open door -> get items from a chest, behind of the door. 

**Steps to reproduce the problem**:

```SQL
REPLACE INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES (177385,1,0,1,70,0,100,0,2,0,0,0,9,0,0,0,0,0,0,14,43178,175610,0,0,0,0,0,'Torch - On Gossip Hello - Set Gameobject State'),(177385,1,1,0,61,0,100,0,0,0,0,0,106,16,0,0,0,0,0,20,176944,200,0,0,0,0,0,'Torch - On Gossip Hello - Remove Gameobject Flag');
```

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/b669d24a1f6c622737d68be3069a2cfbca5bbfc2

**Operating system**:  
win10 64bit

**Comment by BarbzYHOOL** [comment]
Hey tea91, @knindza tested the issue and the fix, it's working fine

Would you be okay to open a Pull Request out of it?
