### ISSUE TITLE
worldserver closes  (areatrigged db missing)

### ISSUE THREAD

**Issue by ladiszlai** [azerothcore/azerothcore-wotlk#752]
I just compiled a fresh azerothcore and I imported the database and the updates too. And the world server at the end says: ERROR: Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders. 
ERROR: Table "acore_world.areatrigger" doesn't exist

**Comment by ShinDarth** [comment]
have you imported all the required sql dumps?

https://github.com/azerothcore/azerothcore-wotlk/wiki/Installation#6-setting-up-the-database

this looks more a help request than a bug report
