### ISSUE TITLE
GM Command: Learn All Languages command not working properly

### ISSUE THREAD

**Issue by Tinywolf69** [azerothcore/azerothcore-wotlk#7529]
### Current Behaviour

When the **"Learn All Lang"** command is imputed in-game, the character only gets **"Titan"** and **"Draconic"** added. Also, after restarting the client, when attempting to type any other messages, the message **"You cannot speak that language"** is displayed. Then, I proceeded to select a language from the chat options and the only languages listed are **"Titan"** and **"Draconic"**.

![GM_Command-LearnAllLang1](https://user-images.githubusercontent.com/83475687/130542714-b092e542-7d79-4c81-91dd-004608a56a7c.JPG)
![GM_Command-LearnAllLang2](https://user-images.githubusercontent.com/83475687/130542731-d19004f6-6292-43df-a8cb-98508ef5e113.JPG)
![GM_Command-LearnAllLang3](https://user-images.githubusercontent.com/83475687/130544066-26ad5713-af76-41ef-bbfa-5c931f725d5a.JPG)

### Expected Blizzlike Behaviour

When the **"Learn All Lang"** command is imputed, the character should receive all the languages and when the client is restarted, there should be no restrictions to typing.

### Steps to reproduce the problem

Step 1. Create a new character
Step 2. Level the character to level 80 by using the **"Char Level"** command
Step 3. Grant all languages to character by using the **"Learn All Lang"** command
Step 4. Verify the list of languages via the "Character Info" window
Step 5. Restart client
Step 6. Attempt to type a message in the chat window
Step 7. Select a language via the chat options

### AC rev. hash/commit

AC> server debug
AzerothCore rev. 6ff9b21b736c 2021-08-13 15:49:13 +0000 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1k  25 Mar 2021 (library: OpenSSL 1.1.1k  25 Mar 2021)
Using Boost version: 1.74.0
Using MySQL version: 80026
Using CMake version: 3.21.1
Compiled on: Windows 10.0.19042
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/AzerothCore/Build/bin/RelWithDebInfo/Data/maps. Total size: 252191207 bytes
vmaps directory located in C:/AzerothCore/Build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/AzerothCore/Build/bin/RelWithDebInfo/Data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_08_13_01
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00
AC>

### Operating system

Windows 10 Pro

### Custom changes or Modules

None

**Comment by Tinywolf69** [comment]
Greetings,

This issue still present with the current version. I tested the command with several races and the result is the same. The character looses the common language and besides the racial language, if any, the only languages available are **Titan** & **Draconic**.

**Comment by AnchyDev** [comment]
Tested in-game, the errors produced in the console are because the spell_id needs to be checked before trying to learn each language since not all languages have an associated spell_id (LANG_ADDON, LANG_UNIVERSAL, etc..).

Trying to learn the languages manually produces the same result as the `.learn all lang` command.
