### ISSUE TITLE
GM Command .gm list is available to lower security level than Wiki indicates

### ISSUE THREAD

**Issue by drozco** [azerothcore/azerothcore-wotlk#7560]
### Current Behaviour

A GM of security level 2 is allowed to use the .gm list command, which is a potential security risk, as they can see the rank 3 GM account names.

This is caused in cs_gm.cpp line 36:

    { "list",           SEC_GAMEMASTER,      true,  &HandleGMListFullCommand,          "" },

Should read:

    { "list",           SEC_ADMINISTRATOR,      true,  &HandleGMListFullCommand,          "" },

**Edit:**  This is actually in the world DB table 'command' not in the code.  Not sure why it's specified in a command table AND the database, however.

### Expected Blizzlike Behaviour

Should not be able to list all GM accounts, as per wiki page https://www.azerothcore.org/wiki/gm-commands

### Source

<html>
<body>

gm list | 3 | .gm list | Display a list of all Game Masters accounts and security levels.
-- | -- | -- | --

</body>
</html>

### Steps to reproduce the problem

1. Login GM rank 2 character
2. Type .gm list
3. See all GM accounts on the server

### Extra Notes

If agreed that the wiki is correct, I will submit a PR for this fix.

### AC rev. hash/commit

3b356f2

### Operating system

Ubuntu 20.04 LTS

**Comment by Eronox** [comment]
> Also, to potentially answer your question about why the security level defined in the code is being ignored, it looks like the value defined in the code is the _default_ value, and then it's _overridden_ if the command also exists in the `commands` table

This is correct. Also for the issue itself, the fix is to change the security levels to correspond to our wiki or the other way around 

![image](https://user-images.githubusercontent.com/20321723/147862483-a3b7435e-49ab-4ac2-bcc3-17358142951f.png)

**Comment by Nyeriah** [comment]
I'm not certain about the severity of this, as the level 2 is the highest GM security level before level 3 (administrator), but sure, we could change it, not a problem at all as I see it.

The above assumptions are correct, the database always overrides the value assigned at the core on this, so we'd need the entry @ world.commands updated to reflect the changes as well as the script file updated.

**Comment by Eronox** [comment]
We've agreed to adjust it to follow the wiki
