### ISSUE TITLE
[Localization ruRU] City Guards - some gossip translations are missing

### ISSUE THREAD

**Issue by Santaria94** [azerothcore/azerothcore-wotlk#7569]
### Current Behaviour

Some gossip translations are missing. This can be seen in the screenshot.
<details>
<summary>Screenshot</summary>

![collage](https://user-images.githubusercontent.com/32459796/130989287-79955076-955d-442c-a9b7-79b3f28704d0.jpg)
</details>

### Expected Blizzlike Behaviour
--------------------------------------------------------

Orgrimmar - NPC ID 3296 https://wotlkdb.com/?npc=3296
<details>
<summary>Missed strings and translation</summary>

- Guild Master -> Регистратор гильдий
- Mailbox -> Почтовый ящик
- Auction House -> Аукционный дом
- Zeppelin Master -> Хозяин дирижабля
- Weapon Master -> Эксперт по оружию
- Officers’ Lounge -> Дом офицеров
- Battlemaster -> Военачальник
</details>

--------------------------------------------------------

Silvermoon City - NPC ID 16222 https://wotlkdb.com/?npc=16222
<details>
<summary>Missed strings and translation</summary>

- Auction House -> Аукционный дом
- Guild Master -> Регистратор гильдий
- Mailbox -> Почтовый ящик
- Weapon Master -> Эксперт по оружию
</details>

--------------------------------------------------------

Thunder Bluff - NPC ID 3084 https://wotlkdb.com/?npc=3084
<details>
<summary>Missed strings and translation</summary>

- Guild Master -> Регистратор гильдий
- Mailbox -> Почтовый ящик
- Auction House -> Аукционный дом
- Weapon Master -> Эксперт по оружию
- Battlemaster -> Военачальник
- Zeppelin Master -> Хозяин дирижабля
</details>

--------------------------------------------------------

Undercity - NPC ID 36213 https://wotlkdb.com/?npc=36213
<details>
<summary>Missed strings and translation</summary>

- Auction House -> Аукционный дом
- Guild Master -> Регистратор гильдий
- Battlemaster -> Военачальник
- Mailbox -> Почтовый ящик
- Weapon Master -> Эксперт по оружию
- Zeppelin Master -> Хозяин дирижабля
</details>

--------------------------------------------------------

Stormwind City - NPC ID 68 https://wotlkdb.com/?npc=68
<details>
<summary>Missed strings and translation</summary>

- Auction House -> Аукционный дом
- Guild Master -> Регистратор гильдий
- Officers’ Lounge -> Дом офицеров
- Battlemaster -> Военачальник
</details>

--------------------------------------------------------

Ironforge - NPC ID 5595 https://wotlkdb.com/?npc=5595
<details>
<summary>Missed strings and translation</summary>

- Auction House -> Аукционный дом
- Guild Master -> Регистратор гильдий
- Mailbox -> Почтовый ящик
- Battlemaster -> Военачальник
</details>

--------------------------------------------------------

Darnassus - NPC ID 4262 https://wotlkdb.com/?npc=4262
<details>
<summary>Missed strings and translation</summary>

- Auction House -> Аукционный дом
- Guild Master -> Регистратор гильдий
- Mailbox -> Почтовый ящик
- Battlemaster -> Военачальник
</details>

--------------------------------------------------------

Exodar - NPC ID 16733 https://wotlkdb.com/?npc=16733
<details>
<summary>Missed strings and translation</summary>

- Auction House -> Аукционный дом
- Guild Master -> Регистратор гильдий
- Mailbox -> Почтовый ящик
- Weapon Master -> Эксперт по оружию
</details>

--------------------------------------------------------

### Source

The above is the translation used on Russian-speaking private servers.

### Steps to reproduce the problem

1) Run client with ruRU locale.
2) Teleport to any guard.

### Extra Notes

Server ChromieCraft

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Windows 7

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by FrancescoBorzi** [comment]
@Viste @Winfidonarleyan

**Comment by LukasVolgger** [comment]
Same with deDE

**Comment by LukasVolgger** [comment]
The gossips aren't missing. The DB in GMO like 10769 has all entries for example but the gmo is still messed up.

I can't fix this in DB

**Comment by LukasVolgger** [comment]
Also closing this because it affects all locales and there is already an open issue https://github.com/azerothcore/azerothcore-wotlk/issues/7209
