### ISSUE TITLE
Typo in world update sql

### ISSUE THREAD

**Issue by jllllll** [azerothcore/azerothcore-wotlk#757]
**Description**: World update file 2017_12_08_00.sql at line 8:
COLUMN_NAME = 2017_12_08_00 should be 2017_11_21_00

**Current behaviour**: This prevents recent world updates from applying correctly on a fresh db

**Steps to reproduce the problem**:

1. Start with a fresh db
2. Run db_assembler and assemble and import all
3. Attempt to run worldserver. Will receive an error stating that areatrigger table doesn't exist.
This table is created in world update 2018_08_01_02

**Branch(es)**: master

**AC hash/commit**:
90ed254  

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Nefertumm** [comment]
It's already on my PR #753 waiting for merge.

**Comment by ShinDarth** [comment]
@jllllll maybe you can test the PR so I can merge it

**Comment by jllllll** [comment]
PR works great
