### ISSUE TITLE
Gordunni Shamans cast Healing Wave too often (SmartAI)

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7572]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: [Chromie issue#1548](https://github.com/chromiecraft/chromiecraft/issues/1548)

Link: https://wowgaming.altervista.org/aowow/?npc=5236
Mob heals themselves without timer.

https://user-images.githubusercontent.com/31207969/130994735-55795623-614c-487b-b1d6-5bd9fc1a1c43.mp4

### Expected Blizzlike Behaviour

 It should be heal themselves below %40 health at every 14 - 21 seconds.

### Steps to reproduce the problem

NPC Info
```
DB GUID: 50243, current GUID: 13160.
Faction: 45.
npcFlags: 0.
Entry: 5236.
DisplayID: 11559 (Native: 11559).
Level: 44.
EquipmentId: 1 (Original: 1).
Health (base): 1712. (max): 1712. (current): 1712.
Unit Flags: 0.
Unit Flags 2: 2048.
Dynamic Flags: 0.
Faction Template: 45.
SpawnTime: Full:5m Remain:0s
Loot: 5236 Pickpocket: 5236 Skinning: 0
InstanceID: 0
Phasemask: 1
Armor: 2527
Position: -5467.840820 1280.123413 22.367174.
AIName: SmartAI ScriptName: 
MechanicImmuneMask: 0
SpellSchoolImmuneMask: 0
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (888549b).
The Gordunni Shamans cast Healing Wave too often. They have two events for their Healing Wave in SmartAI, but one should only trigger if a friendly target is near and has lost health (event `14 - Friendly Health`). The self cast is supposed to have at least 14 sec between each Healing Wave (they sometimes cast Healing Wave quickly two times in a row), so it seems like the Shamans can also heal on the Friendly Health event (which shouldn't be the case, I believe).

**Comment by syssneck** [comment]
Testing a shaman, he heals himself four times in a very short time:
https://user-images.githubusercontent.com/68868567/131506526-d049bac9-70d8-45cf-8875-ac35a7b2f6e3.mp4

So for me this is still an issue, and it would be nice to have someone look at the actual SmartAI event  `14 - Friendly Health` as this event (according to the name?) shouldn't trigger on himself, but only on friendly units.

**Comment by Asthalor** [comment]
He heals himself when the hp is lower than 40% and then another time when his hp is lower that 450. Between this 2 casts the cooldown reset, so he can keep casting them.
For me the fix should be removing the self heal(event 2 HEALTH-PCT), being that the SmartAI event 14 - Friendly Health already heal him when low, but we dont know if this behaviour is blizzlike or not. The video that Si1ker post https://www.youtube.com/watch?v=w8fS4qfdwyw&t=242s dont show the full combat as the mage kill them too fast, so we can ony assume.

**Comment by Efymer** [comment]
Also the video provided is not even from Classic WoW.

Classic released 26th August 2019.
Video is from 29th of January 2019.

**Comment by Si1ker** [comment]
There you go https://youtu.be/iAmvyD9ryNU?t=365

note: if you're trying to kill npcs with melee attacks only, you're gonna have a hard time with tons of npcs.

**Comment by syssneck** [comment]
What argument are you trying to make, and what has this to do with this issue?

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/7647 bye

**Comment by Asthalor** [comment]
Returning to the conversation what should be the protocol here?
I agree that casting the healing on himself and on allies with 2 events is way too much, and we can see it on video.
We can try to add more time between the 2 casts, so at best he will only cast 2 heals before getting killed. The other is removing the self healing event, because with the friendly event he already heal himself.
Or a 3 option, still hidden.
Im open to ideas, so maybe we can put a Need feedback so other developers can share their toughts.

**Comment by Efymer** [comment]
@Asthalor to help a bit, I went to the TBC Classic PTR (which is free and it doesn't require a subscription to play) and I recorded this:

https://www.youtube.com/watch?v=XiqwoaPoksw _(HD version should be there soon)_

**Comment by Asthalor** [comment]
Wow, really nice info @Efymer 
For what i could se the first time he casted the spell to heal him was at 0:20, and i think it the second time he heals himself was at around 1:50. So thats a cd of 1:30 between self heals. As you noticed it started when below 50% HP.

The other thing was the friendly heals, wich happened when they were at least at 500hp. It was first done at 0:58 and then at 1:27. So at least arounf 30 seconds CD.

So much easy this way, good one. I will go on it right now.

**Comment by syssneck** [comment]
Wow, thank you @Efymer!
Let me quickly recap, the four heals, that I saw:
0:18 - self heal
0:58 - heal on friendly target
1:28 - heal on friendly target (30 seconds diff for friendly heal?)
1:54 - self heal

Even if we just change the cooldown of both events -- the shamans would still be able to heal themselves with the "friendly" event.

**Comment by Asthalor** [comment]
Good point @syssneck 
Yeah, i had to redo the target and condition. Please take a look at the PR  when you could. I think is pretty good, but maybe we can do better.
