### ISSUE TITLE
[Blackfathom Deeps] Deep Pool Threshfin can walk on ground (maps related bug?)

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7573]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: [Chromie issue#1533](https://github.com/chromiecraft/chromiecraft/issues/1533)

Only happened to me once but the party agroed and these guys took a detour and come out of the water to fight us. Needs proper testing.

### Expected Blizzlike Behaviour

They stay in the water.

### Source

![WoWScrnShot_072721_203657](https://user-images.githubusercontent.com/89538610/130842903-8b41a78a-1728-43cc-acc7-6482eb7763d6.jpg)

### Steps to reproduce the problem

1. Agro them standing on the ground (might need to get agro from other player tho)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed while playing on Chromiecraft two days ago:
Video: https://user-images.githubusercontent.com/68868567/131021366-328421f4-f84f-47ff-8371-b3cadf84dcbb.mp4

**Comment by avarishd** [comment]
fixed as of rev. df6dcd8888cd8cb90216b4f3d1212e1e0cc24726

Cannot gain aggro from other players (that are in the water) if you're standing on ground.

<details>

https://user-images.githubusercontent.com/46330494/219689148-5f5e3bf6-5b8e-4f09-bc45-8e1784583f3b.mp4

https://user-images.githubusercontent.com/46330494/219690277-127b65f2-721a-4810-b769-0801a64a8c6c.mp4

</details>
