### ISSUE TITLE
server crash (0827)

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#7577]
### Current Behaviour

logs 

https://gist.github.com/mpfans/520b05858e9ab5c1bd0dd6573c95c37d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

5c97632cc358b865008d0b2861317081685a1295  + PR 6378

### Operating system

ubuntu 20.04

### Custom changes or Modules

mod-anticheat + PR 32

**Comment by Helias** [comment]
Looking at the crash log is the assert that make it crash, we could comment it or write a log
Considering that it checks `ASSERT(ConditionTarget < MAX_CONDITION_TARGETS);`, we could  return false if the ConditionTarget is greater or equal than MAX_CONDITION_TARGETS.

**Comment by Helias** [comment]
I made a PR, @mpfans feel free to import it and give us some feedback ;-)

**Comment by mpfans** [comment]
> I made a PR, @mpfans feel free to import it and give us some feedback ;-)

My server hasn't crashed since August 31

**Comment by mpfans** [comment]
![image](https://user-images.githubusercontent.com/18187177/132173355-a5a71718-c6e2-4f1d-b39b-a92a1d99532e.png)
