### ISSUE TITLE
Core/Script: Mind Control - Raid 

### ISSUE THREAD

**Issue by Narcof** [azerothcore/azerothcore-wotlk#759]
**Description**: In ICC, Mind Controlled people become Friendly, you can easily test the Lady or Queen, this really simplifies the fight.

**Current behaviour**: When Mind Control happens for the mechanics of the boss, for a few seconds the players are actually considered enemies, but after a short time (or it would seem after receiving any type of Crowd Control (such as fear, stun etc.) are friendly, go to the boss and no longer do any spell to Raid, they can not be damaged and / or controlled. This simplifies things a lot, Mind Control should be one of the deadliest weapons in the Lady 25 HC.

**Expected behaviour**: Whoever suffers Mind Control should look for the duration of the effect of attacking their Raid teammates as they are Enemy due to Control. in the period in which one is not Friendly, then one is actually Enemy, the controlled player should cast spell

**Steps to reproduce the problem**:

1. become Mind Controlled by the Lady or Queen
2. Note that after a while you become Friendly at Raid; the player can not yet control his character but does not damage the Raid and can not receive them.

**Branch(es)**: Master

**AC hash/commit**:  29f4a1e090338bc033ebdecb0d71ee45cde6f66f

**Operating system**:  Linux

**Comment by Szone** [comment]
Confirm.

**Comment by ShinDarth** [comment]
@Szone thanks for confirming, however it's useful to also attach your own hash commit version when confirming issues

**Comment by Si1ker** [comment]
While I tested the PhasedRespawn I notice it was working good Sept 2021 , closing.
