### ISSUE TITLE
cmake error in linux 

### ISSUE THREAD

**Issue by cnmir2** [azerothcore/azerothcore-wotlk#76]
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Detected 64-bit platform
UNIX: Using jemalloc
UNIX: Using default configuration directory
UNIX: Using default library directory
UNIX: Configuring uninstall target
UNIX: Created uninstall target
UNIX: Detected compiler: /usr/bin/cc
GCC: Enabled c++11 support
GCC: SFMT enabled, SSE2 flags forced
Using mysql-config: /usr/local/mysql/bin/mysql_config
Found MySQL library: /usr/local/mysql/lib/libmysqlclient.so
Found MySQL headers: /usr/local/mysql/include
Found Readline library: /usr/lib64/libreadline.so
Include dir is: /usr/include
Found git binary : /usr/bin/git
fatal: Not a git repository (or any of the parent directories): .git

    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* AzerothCore revision   : unknown 1970-01-01 00:00:00 +0000 (Archived branch)
* AzerothCore buildtype  : Release

* Install core to        : /home/azeroth-server/ 
* Install libraries to   : /home/azeroth-server/ /lib
* Install configs to     : /home/azeroth-server/ /etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : No  (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Use GIT revision hash  : Yes

Loading module: modules/acore
Running cmake hook: BEFORE_ACORE_LOAD
No hooks registered for BEFORE_ACORE_LOAD
Running cmake hook: AFTER_ACORE_LOAD
No hooks registered for AFTER_ACORE_LOAD
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE

Running cmake hook: AFTER_WORLDSERVER_CMAKE
No hooks registered for AFTER_WORLDSERVER_CMAKE
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ACE_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/framework
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/modules/acore/world-engine/collision
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/game
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/authserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/scripts
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
   used as include directory in directory /home/azerothcore-wotlk-master/src/worldserver
ACE_LIBRARY (ADVANCED)
    linked by target "shared" in directory /home/azerothcore-wotlk-master/modules/acore/framework
    linked by target "authserver" in directory /home/azerothcore-wotlk-master/src/authserver
    linked by target "worldserver" in directory /home/azerothcore-wotlk-master/src/worldserver

Configuring incomplete, errors occurred!
See also "/home/azcorebuild/CMakeFiles/CMakeOutput.log".
See also "/home/azcorebuild/CMakeFiles/CMakeError.log".

**Comment by cnmir2** [comment]
i  use cmake on trinitycore in linux have no error why?

**Comment by ShinDarth** [comment]
because you haven't installed ACE

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ACE_INCLUDE_DIR (ADVANCED)

read: https://github.com/AzerothCore/azerothcore-wotlk/wiki/Requirements
