### ISSUE TITLE
The flying mount cannot fly

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#7606]
### Current Behaviour

The flying mount cannot fly

### Expected Blizzlike Behaviour

After get the quest(id 13413), you can fly and kill ` scaleshorn elite`

### Steps to reproduce the problem

1. Don't be on a mount
2. .quest add 13414,talk `Corastrasza`(id 32548) and on a mount `Wyrmrest Skytalon` (npc id 32535)
3. `Wyrmrest Skytalon` cannot fly

### Extra Notes

It may be caused by this commit,bug that only appears after this week's update
e35e47c

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5c97632cc358b865008d0b2861317081685a1295

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
@UltraNix  tyvm

**Comment by zanzaqtlol** [comment]
I have the same problem.

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/7008  From here

**Comment by lineagedr** [comment]
@pklloveyou 

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Creature/Creature.cpp#L3105

```diff
SetSwim(CanSwim() && Swim);

+// xinef: summoned vehicles are treated as always in air, fixes flying on such units
+if (IsVehicle() && !GetSpawnId())
+   isInAir = true;

if (info->InhabitType & INHABIT_AIR)
{
    if (isInAir && !IsFalling())
    {
        if (info->InhabitType & INHABIT_GROUND)
```

**Comment by pklloveyou** [comment]
@lineagedr 
![image](https://user-images.githubusercontent.com/18535853/131234337-837277a9-928c-4009-b0a6-70c396891a3a.png)

**Comment by UltraNix** [comment]
```
 // Do not update movement flags if creature is controlled by a player (charm/vehicle)
    if (m_movedByPlayer)
        return;
```
That check should've done this.

**Comment by pklloveyou** [comment]
yes,But it doesn't work. Maybe it's a different way to summon creatures

**Comment by mpfans** [comment]
quest 13413,work.
quest 13414 not work.

**Comment by pklloveyou** [comment]
![image](https://user-images.githubusercontent.com/18535853/131438718-09020381-87a6-4b0b-bf62-7f9d4bda9e29.png)
.go c 100211
Bone dragons walked in the air. It was flying before the merger

**Comment by UltraNix** [comment]
![WoWScrnShot_083121_214812](https://user-images.githubusercontent.com/80540499/131567226-917e0638-f5b7-4c08-835c-ee81cc12bb3f.jpg)
Looks okay on my local.
