### ISSUE TITLE
Incorrect Mageroyal drops from mobs

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7609]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1560

564 mobs have mageroyal in their loot table.

Testers note:
Looking at the drop chances of some of these herbs, specifically those that are confirmed by [Wowhead](https://tbc.wowhead.com/item=785/mageroyal#dropped-by;0-2-10-9+1), the drop rate seems off. The lowest drop rate on there is 0.4% while in the DB it is currently around 0.011%. Moreover, some of the mobs which are in both, have different drop rates e.g. eversong tender 10% vs  2.9376%.

### Expected Blizzlike Behaviour
Testers note: 
They should only drop from the 78 mobs displayed on [Wowhead](https://tbc.wowhead.com/item=785/mageroyal#dropped-by;0-2-10-9+1). As it is a vanilla herb, it is unlikely to have changed much in what mobs drop it, but the current 500+ seem incorrect.

### Source

78 mobs according to
https://tbc.wowhead.com/item=785/mageroyal#dropped-by;0-2-10-9+1

### Steps to reproduce the problem

Query database. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
WowHead is not the best source of % drop chance.

**Comment by jamadaha** [comment]
Really? I did not know that.
