### ISSUE TITLE
Lady Deathwhisper Major Bugs

### ISSUE THREAD

**Issue by Nooblydone** [azerothcore/azerothcore-wotlk#761]
**Description**: Lady Deathwhisper currently has many Bugs during both Phases.

**Current behaviour**: 
Phase 1
- Empowered Cult Adherents are NOT immune to interrupt effects.
- You can "interrupt" Dark Martyrdom casts with Stuns and with knockback effects such as Thunderstorm / Typhoon.
- If Dark Martyrdom cast is successful, the Reanimated add spawns with a many seconds delay.

Phase 2
- Adds dying from Dark Martyrdom in Phase 2 are NOT reviving as Reanimated.

**Expected behaviour**: 
- Empowered Cult Adherents definitely should be immune to interrupts.
- The only way to "interrupt" Dark Martyrdom is killing the mob before the cast is over. That means they should be immune to Stuns, and not suffering knockbacks.
- Adds dying from Dark Martyrdom should almost istantly spawn as Reanimated, even during Phase 2.

**Steps to reproduce the problem**:

1. Try to interrupt Empowered Cult Adherents and notice it actually works.
2. Try to stun adds during Dark Martyrdom cast and see it actually stuns them.
3. Notice how adds who could successfully cast Dark Martyrdom may take many seconds to spawn as Reanimated.
4. During Phase 2 adds are not spawning as Reanimated AT ALL.

**Branch(es)**: Master

**AC hash/commit**:  29f4a1e090338bc033ebdecb0d71ee45cde6f66f

**Operating system**:  Linux

**Comment by Nefertumm** [comment]
Confirm. 
Related to immune problems: Somehow, the adds have mechanic_immune_mask data but it's not working. 
Related to delay and Dark Martyrdom in phase 2: Changing [this](https://github.com/azerothcore/azerothcore-wotlk/blob/84949746e1d0dcbfaca2108024b17a044a9ef8b9/src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp#L582) line to some like this 
```c++
void SetGUID(uint64 guid, int32)
{
    _reanimationQueue.push_back(guid);
    events.ScheduleEvent(EVENT_REANIMATE_CULTIST, 1);
}
```
will fix the problem. However, this might be a little hacky and we need a better solution.

**Comment by Nefertumm** [comment]
About my previous comment, it's wrong.
According to wowwiki: All types of adds can be CC'd and during phase 2 the adds should NOT spawn at Reanimated or empowered. [source](http://wowwiki.wikia.com/wiki/Lady_Deathwhisper)
However, the delay must be changed.

**Comment by Nooblydone** [comment]
Yeah, adds can be CC'd but I was thinking there was some immunity to them while casting Dark Martyrdom, maybe I'm wrong, I'm trying to find infos on that.

Why during Phase 2 adds should not spawn at reanimated? Lady doesn't cast Animate Dead anymore (And yeah, you're right about this bug, I didn't notice it) but if a Dark Martyrdom cast is successful in Phase 2 the add should still transform. Otherwise you can simply kite adds away, wait til they die by themselves casting Dark Martyrdom, and you're done. Everyone with a decent tactic in mind would do that, considering you can tunnel DPS the boss all the time and just have 1 Tank to kite away adds. In the Paragon Lady Kill for example, DPS are focusing Adds in p2. That would have been a total waste of DPS if adds weren't becoming reanimated after Dark Martyrdom cast. I don't think Paragon would make such a mistake :P
(https://www.youtube.com/watch?v=YMaNM3FQ7TM)

**Comment by Nefertumm** [comment]
Yeah, i think i messed up myself with Dark Martyrdom and Empowered Cultists, in fact my first comment really fix the problem with the second phase. I'm working to fix the other bug that i mentioned and another one who's related to the lady's intro. :)

**Comment by Nefertumm** [comment]
I found something (not really sure if it's from retail):

> - Dark Martyrdom = a spell cast by living adds; the add that is casting must be either stunned, gripped, or kited away from others

**Comment by Nooblydone** [comment]
Ow, I see! No worries.
Thank you by the way, I'm really trying to find infos about Dark Martyrdom being "interruptable" by stuns or knockback effects. I'm sceptic because I can't find vids from retail where the add is actually being stunned on the Dark Martyrdom cast, which I consider essential if it was possible.

I don't understand what does it mean with "kited away from others". He can't move while casting, so how would you actually kite? The tactic I remember was: you either burst the add down before the cast is complete or you run away from it avoiding the AoE damage. I really can't recall it being stunnable. But as I've been stating few times already (I guess I became annoying at this point) I'm trying to collect as much informations about it as possible

**Comment by Nefertumm** [comment]
No problem. I'll see what mechanic_immune_mask trinity has because they have it 100% from retail. First i need to change the npc info to provide information about the actual mechanic_immune_mask.
I think that means run away from npc :P

**Comment by Nefertumm** [comment]
Update: Adds should not be able to cast Dark Martyrdom in 2nd phase and while an add is casting Dark Martyrdom it's impossible to interrupt.
