### ISSUE TITLE
Celebras the Redeemed - bugged dialog

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#7612]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1567

After talking to Celebras, the only thing he says is "Greetings, [Player Name].". The same thing happens after clicking on any dialog option.

### Expected Blizzlike Behaviour

You can see the correct dialog options in this wowpedia link under the Quotes section: https://wowpedia.fandom.com/wiki/Celebras

### Source

![WoWScrnShot_071621_191045](https://user-images.githubusercontent.com/84775498/131218785-19710d1b-8a82-4e8d-8ea4-86ebedf2c6ab.jpg)
![WoWScrnShot_071621_191055](https://user-images.githubusercontent.com/84775498/131218787-299c0601-9b16-4905-a852-d72de6b31f56.jpg)

### Steps to reproduce the problem

1. Go to dungeon Maraudon and kill boss Celebras the Cursed
2. Talk to him
3. Observe

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
Im looking into it.
The problem is that from all the videos ive seen in not one the gossip is showed.
If they have a quest to complete the quest popup filled the entire page, so even tho in https://wowpedia.fandom.com/wiki/Celebras are the gossip options some of the gossips we have will be deleted. 
All our gossip options are wrong according to that, im going to replicate the data from https://wowpedia.fandom.com/wiki/Celebras, but i dont know if its a blizlike pure webpage.
