### ISSUE TITLE
missing water chunk(i think?) in sw canals

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7616]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1575

at 57,1 64,1 In the stormwind canal there is a missing chunk of water if you can call it that basicly if you swim normaly around and cross through it you will start falling as if water dont exist 

Testers note:
As seen here, I don't get the breath bar
![image](https://user-images.githubusercontent.com/53914190/131240658-f3a4898f-6fca-43b9-86b8-9b80e16cc4fc.png)
Whereas if I move a little to the side
![image](https://user-images.githubusercontent.com/53914190/131240666-656b960f-0798-4280-bfed-48eab40b2a5d.png)

### Expected Blizzlike Behaviour

to be able to swim through 57,1 64,1

### Steps to reproduce the problem

1.remove your mount(You can use it with mount but will be much obivous without) 
2,swim throught/around The coirdenates 57,1 64,1 | .go zonexy 57 64 1519
3,you will notice random falling if you let it fall you can kinda stand normaly under water and cast spells and without the need to breathe under water
4,?????
5.profit

### Extra Notes

not really a gamebreaking one or anything but hey it exist

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Maelthyrr** [comment]
I've check and it's closed with recent map updates. Probably with: https://github.com/azerothcore/azerothcore-wotlk/pull/10947
