### ISSUE TITLE
Webwood spiders are aggressive

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7627]
Original Chormiecraft report https://github.com/chromiecraft/chromiecraft/issues/1581

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Webwood spiders are hostile (red)

### Expected Blizzlike Behaviour

The spiders and the named, Githyiss the Vile, should be yellow as of patch 3.3.3
This is the case for all beginner zones with mobs that used to be hostile, it just seems this one was overlooked.

### Source

https://www.wowhead.com/quest=917/webwood-egg#comments

### Steps to reproduce the problem

1. .go c 47055, 47350
2. .gm off

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by JamesGent** [comment]
This is an invalid report.

https://www.wowhead.com/npc=1986/webwood-spider#comments

<html><body>
<div class="comment-header">

By Delvara on 2009/02/22 (Patch 3.0.9) |   |  


</div><div class="text comment-body" lang="en">Also to be noted, this is usually the first aggressive creature that Night Elves meet.</div>
</body>
</html>

**Comment by T1ti** [comment]
The starting areas mobs becoming neutral was a patch 3.3.0 change
https://wowpedia.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)
![image](https://user-images.githubusercontent.com/40864460/131388007-7c401467-a3bf-4d35-a0f0-cf6975e66722.png)
