### ISSUE TITLE
server crash (0830) 

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#7629]
### Current Behaviour

logs
https://gist.github.com/mpfans/d0ba7f91077028b9bcf34b64e0ff435d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

5c97632 + PR 6378

### Operating system

ubuntu 20.04

### Custom changes or Modules

mod-anticheat + PR 32

**Comment by mpfans** [comment]
@UltraNix

**Comment by Winfidonarleyan** [comment]
Anticheat logs :/

**Comment by mpfans** [comment]
again
https://gist.github.com/mpfans/81958d1bb956431fa66a4420f00b2cdf

**Comment by Winfidonarleyan** [comment]
Just delete this module

**Comment by mpfans** [comment]
> Just delete this module

ok! tyvm..

I waited for @UltraNix  to wake up

**Comment by mpfans** [comment]
it's not related to current AC, but to module anticheat

**Comment by Winfidonarleyan** [comment]
Next time, if module crash - open issues in module repo

**Comment by mpfans** [comment]
> Next time, if module crash - open issues in module repo

I can't tell what caused the crash

**Comment by Winfidonarleyan** [comment]
Bad logging
