### ISSUE TITLE
Professor Putricide Unbound Plague

### ISSUE THREAD

**Issue by Nooblydone** [azerothcore/azerothcore-wotlk#763]
**Description**: Professor Putricide Unbound Plague's mechanic is broken.

**Current behaviour**: Unbound Plague is being cast totally randomly. Sometimes not even once during the whole fight, or it is simply cast once at a random Phase (notice that it's always cast on the Tank for some unknown reason)

**Expected behaviour**: Unbound Plague should be cast during the whole fight, from the first phase to the last. It may also happen that you have to handle it during interphases.

**Steps to reproduce the problem**:

1.  Engage Professor Putricide and notice that Unbound Plague is never cast or once randomly in the fight (when it is cast, it pops out on the current Tank, should be a random raid target)

**Branch(es)**: Master

**AC hash/commit**:  29f4a1e090338bc033ebdecb0d71ee45cde6f66f

**Operating system**:  Linux

**Comment by Nefertumm** [comment]
Confirm. I'm working on a fix.

**Comment by Gargarensis** [comment]
Nice! Can you open a PR so we can merge it? :D

**Comment by Gargarensis** [comment]
I've opened a PR for you :)
