### ISSUE TITLE
Warrior "Sweeping Strikes" Ability - Secondary Target Damage Bugged

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7636]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1580

When the buff "Sweeping Strikes" is up on the warrior (Arms talent ability) the five attacks that strike an additional opponent deal different damage (always lower) than the main attack they copy. I found the same exact bug a couple years ago on another server named TrueWow and helped to fix it. It behave like the armor of the "additional nearby opponent" is further reducing the damage of the sweeping strike hit -which is not correct because the damage of the hit that will be "copied" is already reduced by the first opponent's armor.

Tester: confirmed. Tried this for a bit and the secondary target damage was always less than the primary, and always by the same percentage ratio. It looks like the secondary target's armour is being counted twice, as was the case for the similar issue involving the rogue Blade Flurry skill - see https://github.com/azerothcore/azerothcore-wotlk/issues/6900

![WoWScrnShot_083021_211256](https://user-images.githubusercontent.com/81782124/131334634-931060aa-9cee-4124-905c-07c8b29f67be.jpg)
![WoWScrnShot_083021_211231](https://user-images.githubusercontent.com/81782124/131334640-3bccc174-5264-4fa3-becb-3774af10af4c.jpg)
![WoWScrnShot_083021_211233](https://user-images.githubusercontent.com/81782124/131334642-3181db72-fa5a-4790-8915-ed1c4fd33f75.jpg)
![WoWScrnShot_083021_211236](https://user-images.githubusercontent.com/81782124/131334644-247f2929-7cc4-451c-a8a6-7b99fccb6ca3.jpg)
![WoWScrnShot_083021_211253](https://user-images.githubusercontent.com/81782124/131334648-081c3ce2-d198-4dd7-be53-cc1d8cb6b721.jpg)

### Expected Blizzlike Behaviour

When the buff "Sweeping Strikes" is up on the warrior (Arms talent ability) the five copied attacks should be of the exact amount of damage of the original hit.

"It tries to copy your direct damage attacks to a secondary target, exactly like the rogue Blade Flurry talent, except SS is limited to only 5 attacks. ... Basically, SS will copy the instant damage of a skill but not the effect. SS + hamstring will do 50ish damage on both targets but only hamstring the primary target, for instance."

"Sweeping Strikes only duplicates the damage from your hits." - https://www.mmo-champion.com/threads/602307-Sweeping-Strikes-and-Mortal-Strike?p=5521686&viewfull=1#post5521686

### Source

https://hilbert.wordpress.com/sweeping-strikes-guide (Classic, but mechanics are the same.)
https://wowpedia.fandom.com/wiki/Sweeping_Strikes?oldid=2378895

### Steps to reproduce the problem

1) Activate Sweeping Strikes with an Arms Warrior
2) Need two-three enemies to hit in order to make Sweeping Strikes hit a nearby opponent
3) Observe the difference in damage between the original hit and the sweeping strike hit copied.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by laasker** [comment]
Damage is still really weird.. should i post here or open a new issue?

to explain, i tested in pvp with 2 warlocks with same resilience, armor, talents, etc and it kinda looks like that:
if damage is more than 3500 then sweeping strikes deals more damage
if damage is less than 3000~3500 then sweeping strikes deals same or less damage


![WoWScrnShot_112121_003214](https://user-images.githubusercontent.com/79991768/144180750-bb2c05bf-2d91-408d-ab19-4e4624e973fe.jpg)

![WoWScrnShot_112121_003219](https://user-images.githubusercontent.com/79991768/144180899-409ca08c-21b6-4b5d-9061-568acbba583b.jpg)

![WoWScrnShot_112121_003340](https://user-images.githubusercontent.com/79991768/144180912-206dd178-bb6f-4132-a0cc-8383afc1c18c.jpg)

Second target is getting hit by 7k, its possible to hit for 9~10k if if you manage to crit 7k+ on main target

all prints here:
https://imgur.com/a/QZJP2Jb

**Comment by Azcobu** [comment]
Thanks for the update. I've confirmed variation in Sweeping Strikes damage, so will reopen this issue. Feel free to post any more info here rather than in a new ticket.

For my test, I spawned 2 x Unkillable Target Dummies, ID 1000, so totally identical NPCs. My understanding is that the Sweeping Strikes damage should be copied across to the second target, so should be identical, but that was not the case - the second strike varied quite a bit, and was sometimes even higher than the original, which definitely isn't correct:

Note here the primary target is taking less damage than the secondary:
![WoWScrnShot_120221_004925](https://user-images.githubusercontent.com/81782124/144251650-8252f5e4-b6a7-400e-b547-77658ba35f40.jpg)

**Comment by UltraNix** [comment]
@Azcobu My tests look okay:
![image](https://user-images.githubusercontent.com/80540499/144274764-41857480-10bb-409b-839f-2f49e772de03.png)

**Comment by UltraNix** [comment]
Heroic Strike (2 hits with Blood Frenzy):
![image](https://user-images.githubusercontent.com/80540499/144275740-36a1a25c-92b6-45ac-8b63-7ee27b2b563e.png)

For me everything works okay. @Azcobu Please confirm it.

**Comment by laasker** [comment]
> Heroic Strike (2 hits with Blood Frenzy): ![image](https://user-images.githubusercontent.com/80540499/144275740-36a1a25c-92b6-45ac-8b63-7ee27b2b563e.png)
> 
> For me everything works okay. @Azcobu Please confirm it.

is there a scalling or something in sweeping strikes? the last screenshot of my post shows what im talking about, i crit a mortal strike for 5383 on one target and the secondary target/sweeping strikes target gets hit for 7034 with same armor, resilience, gear buffs etc

**Comment by UltraNix** [comment]
@laasker But your second target has Blood Frenzy as I can see.

**Comment by Azcobu** [comment]
If there's no scaling, is it other talents/procs/effects causing the damage difference?

I deleted and remade a warr to make sure no leftover talents were causing problems, added just enough talents to get Sweeping Strikes so no other talents would interfere, and had him attack some dummies (started using Hellfire Dummies ID 17578 as they don't fight back and mess up the log) and I'm still seeing variation in SS damage for both Slam and Heroic Strike:

![WoWScrnShot_120221_233300](https://user-images.githubusercontent.com/81782124/144427727-b3f3e1f3-058c-4d7c-8334-2bb54ccaf611.jpg)
![WoWScrnShot_120221_233413](https://user-images.githubusercontent.com/81782124/144427857-52659482-a95a-4dac-b503-157eb659b4c9.jpg)

Also saw instances where ordinary white auto-attacks weren't consuming stacks of Sweeping Strikes at all. No idea why I'm getting different results, will go and rebuild everything and see if that helps.

**Comment by UltraNix** [comment]
I don't know. You can alsotype `.unaura` on all targets and war and then activate SS and see what happens.

**Comment by Azcobu** [comment]
.unaura seems to need a spell ID to remove, so I used `.debug setaurastate = 0` which I hope does the same thing. I'm still getting uneven results for Slam/Heroic Strike even after using that on the two targets + warr.

**Comment by UltraNix** [comment]
@Azcobu Show me these results.

**Comment by Azcobu** [comment]
This is using `.unaura all`, I've also checked warr's talents and there aren't any debuffs being applied in combat that I'm aware of, like armour reduction or whatever.

![WoWScrnShot_120621_024615](https://user-images.githubusercontent.com/81782124/144754680-71784ddc-1bd8-45ed-a27a-200388c0033b.jpg)
![WoWScrnShot_120621_024638](https://user-images.githubusercontent.com/81782124/144754682-d246b051-55f9-4bfb-9b96-0128239ccd6c.jpg)
![WoWScrnShot_120621_025106](https://user-images.githubusercontent.com/81782124/144754683-f2446a98-7014-43d8-a56d-5ca447106bc5.jpg)
![WoWScrnShot_120621_025127](https://user-images.githubusercontent.com/81782124/144754684-19a1aef1-598c-4bef-858f-15fb96fc9114.jpg)

**Comment by UltraNix** [comment]
Still can't reproduce on my local :/

**Comment by Azcobu** [comment]
If you can't reproduce it then I'll close the issue, it's more likely to be me missing something.

**Comment by bonfax4** [comment]
https://web.archive.org/web/20110612030818/http://www.wowhead.com:80/spell=12328

> By [ZarDoom](https://web.archive.org/web/20110612030818/http://www.wowhead.com/user=ZarDoom) (2·20) [on 2010/09/07](https://web.archive.org/web/20110612030818/http://www.wowhead.com/spell=12328) (Patch 3.3.5)
> Using cleave while under the effect of Sweeping Strikes will consume two charges, and make two additional attacks. So if you're fighting two ennemies, Sweeping Strikes + Cleave = 2 hits on each.
> 
> Profit.
> 
> That being said, Whirlwind (or one second of bladestorming) will only consume ONE charge per spin, not 4 (maximum number of targets of whilrwind = 4), hitting an additional target per whrilwind, not per ennemy hit by the whirlwind.
> 
> (Sorry for my bad english, I'm really doing my best.)
> Last edited by [ZarDoom](https://web.archive.org/web/20110612030818/http://www.wowhead.com/user=ZarDoom) on 2010/09/11 (Patch 3.3.5)

Now the interaction with execute not exactly sure, [wowwiki ](https://wowwiki-archive.fandom.com/wiki/Sweeping_Strikes?direction=prev&oldid=2378895)says execute dmg is not transfered if the target isn´t  < 20% health , but the wowhead i linked above does say execute dmg is cleaved but it cleaves the damage as if it was a normal atack, wich seems to be how sweeping seemed to work since vanilla ( [Patch 1.1](https://wowwiki-archive.fandom.com/wiki/Patch_1.10.0#Warriors) - "Execute - This ability will now work with Sweeping Strikes again. If the second victim is below 20% health, they will be hit with the full Execute amount. If the second victim is not below 20% health, they will be hit with normal melee swing damage." ).
