### ISSUE TITLE
The problem with the Sindragosa

### ISSUE THREAD

**Issue by corsairs** [azerothcore/azerothcore-wotlk#7638]
### Current Behaviour

The problem with the Sindragosa event is when she arrives and kills everyone, players are resurrected, fly back and teleport to her zone, then she immediately aggravates and the battle begins, this should not be!
[sindragosa](https://www.wowhead.com/npc=36853/sindragosa)

### Expected Blizzlike Behaviour

Sindragosa must stand still

### Steps to reproduce the problem

after you kill 2 dragons and Sindragosa flies in to die from her breath, come back to the dungeon and when teleporting to her floor, she immediately aggravates and all members of the raid will fight!

### AC rev. hash/commit

AzerothCore rev. 8388578cecba+ 2021-08-27

### Operating system

windos 7/10

**Comment by Kitzunu** [comment]
Add hash/commit number

**Comment by corsairs** [comment]
I don't know how to do it

**Comment by Kitzunu** [comment]
Do `.server debug` in the console and copy all output and paste it under the AC rev. hash/commit title

**Comment by corsairs** [comment]
> Do `.server debug` in the console and copy all output and paste it under the AC rev. hash/commit title

`AzerothCore rev. 8388578cecba+ 2021-08-27 ...`
so ok

**Comment by bgcfb** [comment]
It relate to an aura
fixed by #7793
