### ISSUE TITLE
Проблема с точностью персонажей

### ISSUE THREAD

**Issue by corsairs** [azerothcore/azerothcore-wotlk#7639]
### Describe your feature request or suggestion in detail

The problem with the accuracy of the characters, namely from the magic damage, that is, with a 14% cap rating, characters still miss when attacking or pronouncing spells!

### Describe a possible solution to your feature or suggestion in detail

there should be no misses

**Comment by Kitzunu** [comment]
Open a real bugreport not a suggesation

**Comment by Kitzunu** [comment]
Okay. But please open a bug report then and fill in all the asked details.

This was a suggestion report. Wrong one :)

**Comment by Winfidonarleyan** [comment]
@corsairs Юзай название ишью на английском и всё описание, так же не скипай шаблон и самое главное коммит, нужны скрины и прочее, больше инфы пожалуйста.
