### ISSUE TITLE
Dalaran Arena - Players not getting pushed out of the start zone

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#7642]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original post: https://github.com/chromiecraft/chromiecraft/issues/927

Players don't get pushed out of dalaran arena start zone as it should, my partner got pushed out, but somehow I didnt.
If you try to replicate the bug, please try to get in the same position as I am in this screenshot.
I only got to test it once, I tried queueing again for arena, but we didn't get into dalaran arena again. 
![Screenshot_51](https://user-images.githubusercontent.com/85901661/122689387-ec4f2000-d22a-11eb-98e2-7ede40432f24.png)
![Screenshot_50](https://user-images.githubusercontent.com/85901661/122689390-f113d400-d22a-11eb-8bd1-cf0107a986e8.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

As stated here, you should be pushed out of the start zone
''Players start in pipes at the side of the central area. A little while after the match starts, water shoots both teams out as to prevent camping. ''
https://wowpedia.fandom.com/wiki/Dalaran_Arena

##### STEPS TO REPRODUCE THE PROBLEM:

1. queue into dalaran arena and stay in the position I did
2. 
3. 
4.

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
hey @IntelligentQuantum please don't forget to apply the correct Label + Project (in this case it's "Generic")
