### ISSUE TITLE
Southshore Guards are neutral towards horde

### ISSUE THREAD

**Issue by Efymer** [azerothcore/azerothcore-wotlk#7654]
**Originally reported:** https://github.com/chromiecraft/chromiecraft/issues/1591

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Southshore Guards (https://wowgaming.altervista.org/aowow/?npc=2386) in Southshore are currently neutral to horde characters.
![guards](https://user-images.githubusercontent.com/80769357/131484279-90ad4486-8b3f-4d29-81f8-1ef7a7d5e6f5.jpg)

### Expected Blizzlike Behaviour

Southshore Guards should be hostile towards horde characters.

### Source

https://wotlk.evowow.com/?npc=2386
https://tbc.wowhead.com/npc=2386/southshore-guard#comments
https://wowwiki-archive.fandom.com/wiki/Southshore_Guard
https://wowpedia.fandom.com/wiki/Alliance_Guard_(Hillsbrad_Foothills)

### Steps to reproduce the problem

1. Be horde and Teleport to any NPC entry 2386
2. observe them being neutral

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Efymer don't forget to set the Project as well
