### ISSUE TITLE
Boss The Lich King reset bug

### ISSUE THREAD

**Issue by ladiszlai** [azerothcore/azerothcore-wotlk#767]
When I start the encounter with Tirion's gossip item and after the intro event while tirion freezes into ice lock the whole encounter will reset: Tirion goes back to the middle of the platform and LK goes up too.
I tried it a lot, but everytime I encountered this issue.

**Comment by Nefertumm** [comment]
Make sure that you don't have .gm on active.

**Comment by talamortis** [comment]
Please this is not an issue! all other bosses have to be defeated before the encounter will start correctly.

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/323
