### ISSUE TITLE
The problem with the accuracy of skills during the attack

### ISSUE THREAD

**Issue by corsairs** [azerothcore/azerothcore-wotlk#7672]
### Current Behaviour

Each class has its own rating cap, namely what the player is going to what characteristics, for melee it is 6% and then the white color of the attack, that is, ordinary attacks (auto attacks) do not miss, with 8% of misses, there are no even the spells that you use that is, yellow is the color of the attack! RDD's hit rating cap is 14%, that is, it will not miss at all when dealing damage with spells, but at 17% + accuracy we still have misses :frowning:

![screenshot](https://i.postimg.cc/byV2VBGQ/unknown.png)
![screenshot2](https://i.postimg.cc/rq7n3f42/unknown-1.png)

### Expected Blizzlike Behaviour

There should be no misses with such attacks.

### Steps to reproduce the problem

1. Create a mage class
2. Give him gear that gives accuracy
3. Try to hit any boss

### AC rev. hash/commit

AC rev. 8388578cecba+
`AC rev. 8388578cecba+`

### Operating system

windwos 7/10

**Comment by corsairs** [comment]
You can fix it as quickly as possible or tell me how to fix it @Kitzunu

**Comment by syssneck** [comment]
I can't confirm this bug. I tried with 454 hit rating (17,31 %) and spammed Fire Blast without cooldown on ICC bosses for multiple minutes and didn't have a single miss.
