### ISSUE TITLE
[Raid/Ulduar] Boss Freya aura won't reset after combat finished 

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#7673]
### Current Behaviour

Boss Freya in combat for some time then cast SPELL_BERSERK(entry 47008),
all players died,the combat finished,but boss Freya still has this aura ,last for 30 minutes

### Expected Blizzlike Behaviour

Boss should reset status after combat finished as combat not started

### Steps to reproduce the problem

1. .cheat god
2. .go c id 32906
3. keep live for 600 seconds until the boss cast a spell  last for 30 minutes
4. .cheat god (off) ,and die, leave combat
5.  watch Freya's Status 

### AC rev. hash/commit

b3dde3825e4b+

### Operating system

Ubuntu 20.04

**Comment by Si1ker** [comment]
Know issue / Ref #7153
