### ISSUE TITLE
Crash boost::beast::websocket::detail::service::impl_type::remove

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#7686]
```
Thread 1 "worldserver" received signal SIGSEGV, Segmentation fault.
boost::beast::websocket::detail::service::impl_type::remove (this=0x7ff938c1e020) at /usr/include/boost/beast/websocket/detail/service.ipp:36
36	    auto& other = *svc_.v_.back();
#0  boost::beast::websocket::detail::service::impl_type::remove (this=0x7ff938c1e020) at /usr/include/boost/beast/websocket/detail/service.ipp:36
#1  boost::beast::websocket::stream<boost::beast::basic_stream<boost::asio::ip::tcp, boost::asio::executor, boost::beast::unlimited_rate_policy>, true>::~stream (this=0x7ff938c02048) at /usr/include/boost/beast/websocket/impl/stream.hpp:47
#2  0x00007ff93f005660 in ?? ()
#3  0x00007ff938c02010 in ?? ()
#4  0x0000000000000000 in ?? ()
```

##### AC VERSION

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by iraizo** [comment]
Any details when this happens?

**Comment by Kitzunu** [comment]
Which boost version do you use?
Do you know how to reproduce it?

**Comment by Winfidonarleyan** [comment]
Just incorrect module

**Comment by Kitzunu** [comment]
Why Close?

**Comment by FrancescoBorzi** [comment]
> Why Close?

Apparently the issue was just something wrong in a module, not in AC
