### ISSUE TITLE
Quest "Red Snapper - Very Tasty!" - Rare Cosmetic Bug

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7690]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1604

During quest "Red Snapper - Very Tasty!" (9452) using item "Draenei Fishing Net" (23654) to tap "School of Red Snapper" (181616) Once tapped it persists.

Tester: this seems half-right. The school appears to persist, but as it cannot be fished from again, it seems to be a purely visual bug. it is also quite rare and difficult to replicate, as it seems to be based on being the exact right distance away from the fish school. Standing as far back as possible is what seems to trigger this, if you stand on the fish school it works every time.

https://user-images.githubusercontent.com/81782124/131847990-fe49cd80-a1d8-4c32-880d-549c011f219a.mp4

Inidentally the fish school is actually a spell focus (game object type 8).

### Expected Blizzlike Behaviour

Once tapped it should despawn.

### Source

Honestly. its going to be quite difficult for me to "prove" something like this with gameplay videos or similar, but what is stated above should be the expected behaviour.

Tester - no arguments here.

### Steps to reproduce the problem

1. .go c 82949
2. Accept quest, head to quest location and use the net. You need to stand as far back from the fish as you can for this to happen.
3. if a murloc doesn't spawn, notice effect.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10 pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
@Azcobu Can you try again? on last rev

it works fine for me.

**Comment by Azcobu** [comment]
Just tried on rev. 916d2b16aca5 and reproduced it:

https://user-images.githubusercontent.com/81782124/136373776-96423147-e5e1-481b-a0c2-adfa585908e7.mp4

Looking at it again, the problem seems to be overlapping fish schools - objects 22043 and 22049 are very close to each other. I checked the other snapper schools and didn't find any others that were doubled up like this. I don't know why fishing from one school would block you from fishing from the second one though.

![WoWScrnShot_100721_213400](https://user-images.githubusercontent.com/81782124/136373887-5aa3fc33-58d9-4dce-ac9c-a5c8e7eebeca.jpg)

**Comment by Azcobu** [comment]
@IntelligentQuantum Tested, your fix corrected the issue:

https://user-images.githubusercontent.com/81782124/136537960-9a3dcdb8-251b-4c16-925a-69cf0f6bc575.mp4
