### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zanzaqtlol** [azerothcore/azerothcore-wotlk#7695]
### Current Behaviour

After I updated my core to the latest revision, I started to get an error while compiling in MapMethods.h line '198'.

Error image below
![image](https://user-images.githubusercontent.com/23637989/131946251-6209eeee-5c68-469b-9a26-a3da6cfc86be.png)

### Expected Blizzlike Behaviour

This error shouldn't appear, just update and it happened

### Steps to reproduce the problem

1. Update to last revision
2. Generate CMAKE
3. Start the compilation, and look at the error list, "MapMethods.h"

### AC rev. hash/commit

> edb5f78c7448+

### Operating system

Windows

### Custom changes or Modules

Mod-Eluna
Mod-Transmog
Mod-Anticheat

**Comment by Kitzunu** [comment]
Cannot reproduce on https://github.com/azerothcore/azerothcore-wotlk/commit/42073163bb5717f3dbd93818d0412d04af99b059
========== Build: 9 succeeded, 0 failed, 9 up-to-date, 0 skipped ==========

CI Passes.

You probably did something wrong or have custom changes that is causing it.
Try pulling clean again and delete your CMake cache

**Comment by SaidKing** [comment]
> ### Current Behaviour
> After I updated my core to the latest revision, I started to get an error while compiling in MapMethods.h line '198'.
> 
> Error image below
> ![image](https://user-images.githubusercontent.com/23637989/131946251-6209eeee-5c68-469b-9a26-a3da6cfc86be.png)
> 
> ### Expected Blizzlike Behaviour
> This error shouldn't appear, just update and it happened
> 
> ### Source
> _No response_
> 
> ### Steps to reproduce the problem
> 1. Update to last revision
> 2. Generate CMAKE
> 3. Start the compilation, and look at the error list, "MapMethods.h"
> 
> ### Extra Notes
> _No response_
> 
> ### AC rev. hash/commit
> > [edb5f78](https://github.com/azerothcore/azerothcore-wotlk/commit/edb5f78c74481663248d10652c26d72ab2e111d3)+
> 
> ### Operating system
> Windows
> 
> ### Custom changes or Modules
> Mod-Eluna
> Mod-Transmog
> Mod-Anticheat

This error is related to the Eluna module, just remove this module that the problem stops
