### ISSUE TITLE
[Azuremyst] [Quest] "Tree's Company" missing chat bubbles and a bit too fast

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7704]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

On this [quest](https://tbc.wowhead.com/quest=9531/trees-company) we need to use a [tree disguise](https://tbc.wowhead.com/item=23792/tree-disguise-kit) to witness an encounter and conversation to uncover a traitor.

Upon using the disguise, we turn into a tree and get rooted at the beach. NPCs come and have a dialogue. However, some things are a bit off.

### Expected Blizzlike Behaviour

1) The Tree disguise does root us on the ground, but if placed close enough to the water, we should still be able to fish. Currently we can't do that because we are "Stunned".

2) Conversation runs between the gnome and the goblin. However, only the part said by the gnome is displayed on a bubble over the character. Whole dialogue should appear on speaking bubbles, as can be seen [here](https://youtu.be/THFUktBG2-U?t=171). The timers could be adjusted, too, since conversation should be around 10 seconds longer.

### Source

https://tbc.wowhead.com/quest=9531/trees-company#comments

### Steps to reproduce the problem

Quest 9531 - Use Tree Disguise Kit at beach marked on map and witness events

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (edb5f78c74).
Chat bubbles are missing for Geezle over his head. The whole event is a bit too fast-paced and could be slowed down. It can be hard to keep track of the conversation.

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/145864815-41a5fcf1-0013-4f03-921a-14c2867bf316.png)
Can we reconfirm if the issue is still present? I am currently now seeing the issue. @Nefertumm @syssneck
