### ISSUE TITLE
Tethyr boss in Dustwallow Harbor swims into the ground instead of onto the surface of the water

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#7713]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original post: https://github.com/chromiecraft/chromiecraft/issues/1621

The Alliance quest "Take Down Tethyr!" spawns a monster in the waters just off Theramore Harbor, where it swims up to shore to combat. Instead of swimming to the water's surface, it clips mostly into the ground.

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=56uc9X2jO8Q

### Steps to reproduce the problem

1. Start quest "Take Down Tethyr!"

### Extra Notes

idk what rev. hash/commit or modules are

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
@acidmanifesto same with this one!

**Comment by acidmanifesto** [comment]
I need a quest ID or a NPC ID and Propper Name of the npc for me to figure out if that is the case

**Comment by acidmanifesto** [comment]
Alrighty. I was getting some conflict with searching up the quest as it was redone in cata. But i did identify the id which is 23899. Creature is handled by the the Inhabit Removal PR that is pending a upcoming merge.

**Comment by avarishd** [comment]
rev. 7f36c5f
Works fine
