### ISSUE TITLE
Scripts/TrialOfTheChampion

### ISSUE THREAD

**Issue by Pensukdeath** [azerothcore/azerothcore-wotlk#772]
**Description**:
Hello everybody! Azeroth's Core does not work properly TrialOfTheChampion! Is there anyone wishing to fix Trinity (version)?   
**Current behaviour**: Tell us what happens
Wrong script (horde + alliance)
- Horde should go to the far side of the hall
- The alliance must go to the near side of the hall
- Lack of sounds!
**Expected behaviour**: Tell us what should happen instead
https://www.youtube.com/watch?v=EH9Q8DQ2OHI
**Steps to reproduce the problem**:
I ask to make changes https://github.com/TrinityCore/TrinityCore/pull/14938

**Comment by talamortis** [comment]
Im confused are you asking us to fix the azerothcore trial of the champion or asking us to fix the trinitycore?

**Comment by Pensukdeath** [comment]
Sorry for my English... I'm from Russia) to Fix AzerothCore! A finished script is already on TrinityCore.

**Comment by ShinDarth** [comment]
> A finished script is already on TrinityCore.

maybe you can help the project and import it to azerothcore in a PR?

**Comment by Pensukdeath** [comment]
I am just a beginner. I can try, but I still need help)

**Comment by ShinDarth** [comment]
@Pensukdeath then you came to the right place, this is a learning project :)

**Comment by pondaveia** [comment]
@Pensukdeath you need to be more accurate with what's not working as intended and how is it supposed to work aswell. You must fill in the issue report with as much information as possible so our testers know what and where to look for problems. I suggest you to edit this with every issue you find with **_Trial of the champion_** so our devs can also work on them after they are confirmed.

**Comment by FrancescoBorzi** [comment]
closing as it's an old issue without enough details
