### ISSUE TITLE
BRD - Emperor Dagran Thaurissan Doesn't Aggro Room If Pulled Via Moira

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7725]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1629

Pulling "Princess Moira Bronzebeard" will let you fight "Emperor Dagran Thaurissan" without having to clear the whole room.
![WoWScrnShot_090421_154050](https://user-images.githubusercontent.com/22718174/132106471-fc30b7d1-1c65-49ee-afd8-51254e778edc.jpg)

Tester: confirmed. Only cleared one side of the room and pulled Moira + Emperor. The mobs on the other half of the room didn't react at all.

Fighting the two. Unaggroed NPCs in background:
![WoWScrnShot_090521_112627](https://user-images.githubusercontent.com/81782124/132112654-3ea2bb83-a492-49a8-aa52-2e6c23ef8026.jpg)

Shots afterwards showing all the NPCs nearby who didn't respond:
![WoWScrnShot_090521_112712](https://user-images.githubusercontent.com/81782124/132112655-901e57fb-904b-481f-b1eb-2bd574d9dfae.jpg)
![WoWScrnShot_090521_112717](https://user-images.githubusercontent.com/81782124/132112657-40131629-00c4-4934-97e1-0d8ca800b3c5.jpg)

### Expected Blizzlike Behaviour

If "Emperor Dagran Thaurissan" gets into combat, the whole room should come at his aid. He should also yell "Come to aid the Throne!"

### Source

"All of the mobs in the seat of the room will aggro with the Emperor. " - https://wowpedia.fandom.com/wiki/Dagran_Thaurissan?oldid=2351363

"Fair warning would to be to clear all adds in the room. They will aggro if you do not kill them. This includes the adds on the top of stairways as well." - https://www.wowhead.com/npc=9019/emperor-dagran-thaurissan#comments:id=102705

"Also, be sure to clear EVERYTHING in the room before the emperor." - https://www.wowhead.com/npc=9019/emperor-dagran-thaurissan#comments:id=300856

### Steps to reproduce the problem

Pull Princess Moira Bronzebeard from afar. an eaasy way to get into the room without porting to the Emperor is to go to a mob near the entrance - I went with NPC 90614, a random Senator. That gets you in the room without immediately aggroing everything.

### Extra Notes

https://www.wowhead.com/npc=9019/emperor-dagran-thaurissan
https://classic.wowhead.com/npc=8929/princess-moira-bronzebeard

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
Ive been working on this issue for a while trying to change from the script to SAI, but im getting blocked on 2 things. One is that i cant get the boss to talk when a creature dies near him, and another i increased the aggro radious to pull the whole room, but top floors still get a bit bugged.
If someone is going to work on this, or is willing to lend me a hand, i can link the work ive done or can message me on discord. Its not complete but maybe can help. I dont know if by myself im going to be able to fix those things.

**Comment by Azcobu** [comment]
Well, for the second problem of pulling the room, it might be worth looking at the [creature_formations](https://www.azerothcore.org/wiki/creature_formations) table. If you set the Emperor as the leader, and the other NPCs in the room as members, and made it type 1 (the member aggroes if the leader aggroes), that sounds like it should work. The only downside is the very large number of NPCs you would need to add to the formation. Perhaps if you only added the ones who don't aggro now it would be more manageable.

I'm no expert and perhaps this isn't the proper way to do this, but it seems this is what that table is for.

**Comment by syssneck** [comment]
This command gives you all the ids and guids in the throne room (excluding Emperor Dagran Thaurissan and Moira).
````
SELECT `id`, `guid` FROM `creature` WHERE (`position_x` > 1331 AND `position_x` < 1430 AND `position_y` > -847 AND `position_y` < -713 AND `guid` not IN (47613, 47217));
```
Yes, it's not pretty and it works. 53 in total, I counted them. :D
I hope this helps somehow.

**Comment by Asthalor** [comment]
Thanks a lot both, i will take a look on this

**Comment by Asthalor** [comment]
Awesome, 2 part working!

https://streamable.com/nx81yw

I will take a look on the last thing which is him talking when any of those die and i think this part is done!

**Comment by Asthalor** [comment]
I have my repo bad synchronised, so im putting this the fix being this a high priority so any of you can add it to a PR.

```
-- Add thaurissan to a formation as leader of the whole throne, so when pulled all will come to the aid
DELETE FROM `creature_formations` WHERE `leaderGUID` = 47613;
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(47613, 47613, 300, 0, 1, 0, 0),
(47613, 47217, 300, 0, 2, 0, 0),
(47613, 47478, 300, 0, 1, 0, 0),
(47613, 47561, 300, 0, 1, 0, 0),
(47613, 47562, 300, 0, 1, 0, 0),
(47613, 47563, 300, 0, 1, 0, 0),
(47613, 47564, 300, 0, 1, 0, 0),
(47613, 47565, 300, 0, 1, 0, 0),
(47613, 47566, 300, 0, 1, 0, 0),
(47613, 47568, 300, 0, 1, 0, 0),
(47613, 47569, 300, 0, 1, 0, 0),
(47613, 47586, 300, 0, 1, 0, 0),
(47613, 47587, 300, 0, 1, 0, 0),
(47613, 47588, 300, 0, 1, 0, 0),
(47613, 47589, 300, 0, 1, 0, 0),
(47613, 47590, 300, 0, 1, 0, 0),
(47613, 47591, 300, 0, 1, 0, 0),
(47613, 47592, 300, 0, 1, 0, 0),
(47613, 47593, 300, 0, 1, 0, 0),
(47613, 47594, 300, 0, 1, 0, 0),
(47613, 47595, 300, 0, 1, 0, 0),
(47613, 47598, 300, 0, 1, 0, 0),
(47613, 47599, 300, 0, 1, 0, 0),
(47613, 47601, 300, 0, 1, 0, 0),
(47613, 47602, 300, 0, 1, 0, 0),
(47613, 47603, 300, 0, 1, 0, 0),
(47613, 47606, 300, 0, 1, 0, 0),
(47613, 47611, 300, 0, 1, 0, 0),
(47613, 47612, 300, 0, 1, 0, 0),
(47613, 90596, 300, 0, 1, 0, 0),
(47613, 90597, 300, 0, 1, 0, 0),
(47613, 90598, 300, 0, 1, 0, 0),
(47613, 90599, 300, 0, 1, 0, 0),
(47613, 90600, 300, 0, 1, 0, 0),
(47613, 90601, 300, 0, 1, 0, 0),
(47613, 90602, 300, 0, 1, 0, 0),
(47613, 90603, 300, 0, 1, 0, 0),
(47613, 90604, 300, 0, 1, 0, 0),
(47613, 90605, 300, 0, 1, 0, 0),
(47613, 90606, 300, 0, 1, 0, 0),
(47613, 90607, 300, 0, 1, 0, 0),
(47613, 90608, 300, 0, 1, 0, 0),
(47613, 90609, 300, 0, 1, 0, 0),
(47613, 90610, 300, 0, 1, 0, 0),
(47613, 90611, 300, 0, 1, 0, 0),
(47613, 90612, 300, 0, 1, 0, 0),
(47613, 90613, 300, 0, 1, 0, 0),
(47613, 90614, 300, 0, 1, 0, 0),
(47613, 90615, 300, 0, 1, 0, 0),
(47613, 90616, 300, 0, 1, 0, 0),
(47613, 90617, 300, 0, 1, 0, 0),
(47613, 90618, 300, 0, 1, 0, 0),
(47613, 90619, 300, 0, 1, 0, 0),
(47613, 90620, 300, 0, 1, 0, 0),
(47613, 90621, 300, 0, 1, 0, 0);
```

Ive added moira to that formation too, with group ai 2 (The leader aggroes if the member aggroes) in case some hunter can taunt her from afar.

**Comment by FrancescoBorzi** [comment]
@Asthalor thanks for the fix. Maybe opening PRs using the browser could help your case? https://www.azerothcore.org/wiki/how-to-create-a-db-pr
