### ISSUE TITLE
Dragon Orb (spellid 19869) Has no effect on Razorgore the Untamed

### ISSUE THREAD

**Issue by Barborica-Alexandru** [azerothcore/azerothcore-wotlk#7729]
### Current Behaviour

Using the spell Dragon Orb/Clicking on the Orb of Domination in Blackwing Lair has no effect. Instance cannot be finished because of current behavior.

### Expected Blizzlike Behaviour

Using the spell Dragon Orb/Clicking on the Orb of Domination in Blackwing Lair should cast Mind Control on Razorgore the Untamed.

### Source

https://www.youtube.com/watch?v=Iir2J0YtYlY

### Steps to reproduce the problem

1.Enter Blackwing Lair
2.Right Click on Orb of Domination
3.???
4.Profit

### Extra Notes

There is a missing visual effect on the orb of domination but that should be of no consequence. Restoration of basic functionality is more essential.

### AC rev. hash/commit

AzerothCore rev. 728839b84952+ 2021-09-05 10:02:31 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 2.
Server uptime: 1 day(s) 9 hour(s) 37 minute(s) 45 second(s).
Update time diff: 10ms, average: 10ms.
ACDB 335.4-dev
World DB Revision: 2021_09_04_02
Character DB Revision: 2021_07_21_00
Auth DB Revision: 2021_06_17_00

### Operating system

Debian 10.10

### Custom changes or Modules

Initial modules enabled were:
mod-ah-bot
mod-autobalance
mod-solo-lfg
mod-transmog
mod-weapon-visual-master
mod-ARAC

However, I removed all the modules and patches, emptied the world database, and rebuild server. Issue persisted.

EDIT: While looking at how this is done on trinitycore, I noticed that instead of spellid 19869, they use spellid 42013 (QAE Charm) which when used with .cast does indeed lead to the correct behavior of possessing Razorgore.

**Comment by FrancescoBorzi** [comment]
@Barborica-Alexandru please include the AC version (commit hash), you can check it with `.server info`

**Comment by Barborica-Alexandru** [comment]
AzerothCore rev. 728839b84952+ 2021-09-05 10:02:31 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 2.
Server uptime: 1 day(s) 9 hour(s) 37 minute(s) 45 second(s).
Update time diff: 10ms, average: 10ms.

**Comment by mpfans** [comment]
Confirmed.`Razorgore the Untamed` BOOS cannot click the jewel to control

**Comment by FrancescoBorzi** [comment]
@mpfans thanks for confirming and don't forget the [Confirmed] label in this case ;)

**Comment by mpfans** [comment]
well. A PR will be submitted soon by @UltraNix

**Comment by Barborica-Alexandru** [comment]
Sorry I wasn't able to test, I've been swamped lately. Thank you all for your work.
