### ISSUE TITLE
Core/Script: Halls of Reflection

### ISSUE THREAD

**Issue by Pensukdeath** [azerothcore/azerothcore-wotlk#773]
**Description**:
A wrong script in the halls of reflection.
**Current behaviour**: Tell us what happens
When you enter the dungeon, triggered the script and it is not correct!
The sound and text don't match. The text was from the opposite faction.
Example: a Jaina approach to Uther and the conversation (script) triggered an appeal to Silwan.
After the murder of "Marvin" should be assigned the quest:
Alliance: http://wowhead.com/quest=24500 - Auto acceptance
Horde: http://wowhead.com/quest=24802 - Auto acceptance
Missing text and sounds:
- Stupid girl! The one you seek is long dead! Now he is a shadow ... (Something like this) :-)

Простите за мой англиский! :-) 
Sorry for my English! :-)

**Comment by Middel** [comment]
ehhh i've done the instance today on my azerothcore server, and it worked correctly. also when killing marwyn it pops up that quest. as a matter of fact if you deny that quest at that point, then later in the instance it will pop another time.

**Comment by Pensukdeath** [comment]
@Middel After your words, gathered last AzerothCore.
- Nothing has changed!
- The text in General does not coincide with the sounds!
- Some text is absent!
You go into the dungeon and run text "What is that! Up ahead! Could it be? Heroes, at my side!".
Should run: "The chill of this place... I can feel my blood freezing.".
The whole text is shifted of 1...
- After all, during a conversation with Uther, run a random text. 
Talks to Jaina, in the middle of the text with Silwan.

**Comment by talamortis** [comment]
please can you correctly fill out the template also provide creatureID and any other information that is useful.

**Comment by cvvmusic** [comment]
Несоответствие реплик в таблице "creature_text", беда в том, что там чутка не правильно указаны обращения к "broadcast_text", когда активируется Скрипт, Джайна должна начать говорить реплику "30591", а говорит "30592", и там короче говоря перемешано! Я сейчас пытаюсь реализовать работоспособность этой реплики, если получится, сделаю Dump.

**Comment by Knindzagxg** [comment]
This happens if u enter HoS to test it.
To have it correctly, do previous quests and see what happens.
I will do it myself tomorrow.

**Comment by Knindzagxg** [comment]
Update: Had free time and tested -> Report is valid.
Even trough all quests, wrong NPC spawn when u enter Halls (Previous Dungeon quests and spawns are ok tho)

You can test your self folks -> Starting quest ID 24510 (For Alliance) : For Horde 24506
https://www.wowhead.com/quest=24510/inside-the-frozen-citadel

Video link bellow -> You can see i have completed all quests that lead to Frostmourne.

https://www.youtube.com/watch?v=cKCSjpHLkRA

**Comment by BarbzYHOOL** [comment]
Thank you Knindza, I updated the tags at least

**Comment by Knindzagxg** [comment]
I would put prio to higher tho xD
You can't start / complete dungeon while wrong ID's are spawned.

**Comment by talamortis** [comment]
No this is incorrect, you entered the instance with .gm on so the horde NPC will spawn. please do preq then enter again

**Comment by BarbzYHOOL** [comment]
?? so??

**Comment by talamortis** [comment]
if you enter with GM mode on & your alliance it will give the horde NPC as the default NPC for that instance is alliance.

**Comment by Knindzagxg** [comment]
I will double re-check, since i did all quests from start, and u can see on video i posted.
Will do it again once i'm home today.

**Comment by Ragelezz** [comment]
Still available?

**Comment by avarishd** [comment]
rev. df6dcd8888cd8cb90216b4f3d1212e1e0cc24726
Tested the entire quest chain from start to the end for both factions.
Horde: ✅ No issues whatsoever.
Alliance: RP speech is broken, out of order and sync for the entire dungeon, this includes the end of HoR (escape part).
