### ISSUE TITLE
[Terokkar Forest] Spirit Towers

### ISSUE THREAD

**Issue by alexandru58** [azerothcore/azerothcore-wotlk#7733]
### Current Behaviour

After 6 hours, the towers stays to the faction that captured last time, for example if Alliance took the 5 towers after 6 hours it's still 5 towers captured, instead of 0..

### Expected Blizzlike Behaviour

It should be all of them neutral, like it suppose to be..

### Source

https://wowpedia.fandom.com/wiki/Spirit_Tower

### Steps to reproduce the problem

After you captured all 5 towers, wait 6 hours and after see all of them it's captured by the faction that it took them.

Second problem is: if for example a faction took all the towers, when the server restarts, the timer won't be there and it can be captured once again (the timer should be here instead of capturing them again).

### Extra Notes

-

### AC rev. hash/commit

-

### Operating system

-

### Custom changes or Modules

-

I have a screenshot too:
https://i.postimg.cc/GmZRYLNp/Wo-WScrn-Shot-090521-122805.jpg

**Comment by Kitzunu** [comment]
Add Hash/Commit
