### ISSUE TITLE
Certain Flightpaths and Zones Revert back to undiscovered upon user Logout.

### ISSUE THREAD

**Issue by entity713** [azerothcore/azerothcore-wotlk#7737]
### Current Behaviour

Discovered Flight Paths and Zones revert to undiscovered upon user logout.

Current Example

Nutral - Flight Master in Shattrath City.  (Flight Path) (Terokkar Forest)
Ruins of Lordaron (Zone) (Tirisfal Glades)
Narzyn Skybreaker - Flight Master in Agmar's Hammer (Flight Path) (Dragonblight)
Celea Frozenmane - Flight Master in Camp Winterhoof (Flight Path) (Howling Fjord)

### Expected Blizzlike Behaviour

The zones / flightpaths should stay discovered after user logout.

### Steps to reproduce the problem

1. Create a character
2. .tele Shattrath
3. click on nutral and get flight path.
4. logout
5. log back in
6. Green exclamation mark is above Nutral.

### Extra Notes

It appears that there's at least 1 zone or flight master in each zone affected by this.

### AC rev. hash/commit

AzerothCore rev. 728839b84952 2021-09-05 10:02:31 +0000 (master branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

1v1arena
ahbot
AutoBalance
CFBG
mod-double-xp-weekend

**Comment by enVias** [comment]
Confirmed. Also happening with Baldruc, the Alliance flight master in Theramore.

**Comment by JamesGent** [comment]
Can you also check the Troll flightmaster in Hinterlands? My mage somehow lost that flightpath.

**Comment by schell244** [comment]
I can confirm this issue for zone/map discovery with 79ad100 

1. create new human character -> start area is Northshire Valley
2.  move charater to Northshire Vineyards
4. relog 
5. parts which have not been visted are discovered on map

<img width="365" alt="issue" src="https://user-images.githubusercontent.com/9536270/142760218-8a7e79c1-1f3f-4244-978c-1a10f1ab71d3.PNG">

**Comment by Kitzunu** [comment]
According to https://github.com/azerothcore/azerothcore-wotlk/pull/10083#issuecomment-1019074936 fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/6d7f58e6ed0f460332cf45b76d879d4a05bb6e24
