### ISSUE TITLE
Feature: clang-format action

### ISSUE THREAD

**Issue by iraizo** [azerothcore/azerothcore-wotlk#7738]
### Describe your feature request or suggestion in detail

The commits of every PR should be checked if formatted correctly according to `.clang-format` based on an github app/action. 

### Describe a possible solution to your feature or suggestion in detail

https://github.com/marketplace/actions/git-clang-format-check-per-commit

### Additional context

I will try to make a pr for this, but im not sure if it is correct due to my first time using any CI really.

**Comment by iraizo** [comment]
@Kitzunu @Winfidonarleyan Can one of you help me out to find the issue with the workflow crying about
```

Error : .github#L1
every step must define a `uses` or `run` key

```

https://github.com/iraizo/azerothcore-wotlk/blob/fix-issue-7738/.github/workflows/codestyle.yml

**Comment by patou01** [comment]
I'm not experienced with github actions, but with some google-fu I find the following:
https://github.com/einaregilsson/beanstalk-deploy/issues/2

And it seems you are doing something similar? Also might want to swap the "name" with the "uses" so the name comes first in the step, though it probably doesn't matter.
![image](https://user-images.githubusercontent.com/2592673/133888400-044c34a5-1229-4f60-b147-05aabdd4c598.png)


Maybe you could check that if nobody has given you more input?

**Comment by iraizo** [comment]
That has already been fixed, im still searching for an action that fullfils its correct purpose.

**Comment by Kitzunu** [comment]
closing as we dropped clang-format

**Comment by iraizo** [comment]
> closing as we dropped clang-format

Why is that?

**Comment by Kitzunu** [comment]
because it only caused problems and changed code around to things that were not our standard. https://github.com/azerothcore/azerothcore-wotlk/pull/9934

It was introduced before being ready and up to the job of our standards. Until then, having to always press ctrl z to remove what it does just isn't time efficient

**Comment by iraizo** [comment]
Good job to the nice workflow you and others introduced that allowed the merge then if it wasnt that ready even you literally reviewed it to be "ready".
