### ISSUE TITLE
[Dustwallow Marsh] Young Murk Threshers pathing

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7741]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1627

Young Murk Threshers, when attacked with a ranged attack from a player swimming along the surface of the water, do not path directly to the player, but rather swim laterally along the same Z-axis level they're at, and then ascend the Z-axis to the player's level directly below them.

### Expected Blizzlike Behaviour

The mobs should take the most direct path (X,Y,Z) to the attacking player, provided such a path exists, and go into Evade if such a path to the player does not exist (like if they're on land or something)

### Steps to reproduce the problem

Head to Theramore
Head into the water, and attack a Young Murk Thresher from the surface of the water
Watch it path strangely

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Tester confirmed on local AC (edb5f78).

They even stay on the ground sometimes, not moving up at all. Only when I get below the water surface, can they come up to me. The pathing with mobs, that can't walk on land, seems to be off, when the character is on or above the surface:

https://user-images.githubusercontent.com/68868567/132204720-7c5fe37b-1d0f-43c8-97c2-abfb66e31962.mp4

**Comment by Nefertumm** [comment]
@acidmanifesto can you check this with your inhabittype pr? :D

**Comment by acidmanifesto** [comment]
> @acidmanifesto can you check this with your inhabittype pr? :D

My PR does handle this creature's inhabit.
![image](https://user-images.githubusercontent.com/16887899/147882566-9ed240d5-e0ba-4781-80fa-30cfc6718f5f.png)

**Comment by acidmanifesto** [comment]
Closes due to fix: https://github.com/azerothcore/azerothcore-wotlk/pull/9272
