### ISSUE TITLE
[Mage] Portal: Darnassus, Portal: Thunder Bluff are trainable at lvl 40

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7743]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1631

The spell Portal: Darnassus (spell 11419) is trainable at 40 with the cost of a level 50 skill (base 3g20s). 

### Expected Blizzlike Behaviour

The spell should not be trainable until 50. If the intention is to have it trainable at 40, the cost of the ability should match other level 40 spells.

### Source

https://wowgaming.altervista.org/aowow/?spell=11419
https://tbc.wowhead.com/spell=11419/portal-darnassus
https://legacy-wotlk.com/?spell=11419

### Steps to reproduce the problem

* Take a level 40 mage
* Travel to the Darnassus portal trainer
* Train the skill (and notice the higher cost)

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=11419
https://tbc.wowhead.com/spell=11419/portal-darnassus
https://legacy-wotlk.com/?spell=11419

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Tester confirmed on local AC (edb5f78).
![unknown_2021 09 06-13 12](https://user-images.githubusercontent.com/68868567/132209038-cfe8eefb-2c73-48ee-8e8b-0751b6990d61.png)

It's the same on my local AC, so I assume, that this is indeed not a feature of Chromiecraft, but a bug.
If this is somehow intended and not a bug, then please let me know and close this issue.

**Comment by cachocarne** [comment]
Should only be available at 50 and cost 3g 20s. 
https://legacy-wotlk.com/?spell=11419

35 - Portal: Theramore / Stonard (1g 50s)
40 - Portal: Stormwind / Ironforge / Exodar / Orgimmar / Undercity / Silvermoon (1g 50s)
50 - Portal: Darnassus / Thunder Bluff (3g 20)
65 - Portal: Shattrath (15g)
74 - Portal: Dalaran (10g)

**Comment by Kitzunu** [comment]
Just to educate... legacy-wotlk or any other page like it are not good sources as they are made for private servers. Better is wowwiki wowpedia, when you go back in history. and sometimes wowhead. But wowhead do be lying sometimes too.

as for this one, I don't really have an opinion. Just keep that in mind =)
