### ISSUE TITLE
Elder Ashenvale Bear Wedged In Place

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7746]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1639

Elder Ashenvale Bear GUID 34360 gets stuck in ground and stops moving around.

![elderbear](https://user-images.githubusercontent.com/80769357/132137112-d716741c-59b9-4d99-8954-b808f42f83a3.jpg)

Tester: He's not stuck in the sense that if you aggro him, he can eventually find his way out and come chase you. However, he's not moving at all, half the model is clipping through the slope, and he's wedged into a 60 degree angle between a cliff and a tree which looks silly. So moving him a few meters to a better spot seems sensible.

### Expected Blizzlike Behaviour

Probably the spawn point should be adjusted so he doesn't get stuck and stops moving.

### Source

This isn't radical. Or even controversial.

### Steps to reproduce the problem

1. Teleport to GUID 34360
2. Observe him moving around until he moves into the hill side
3. He gets stuck there and stops roaming

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Si1ker** [comment]
?????????? , you cannot change game data just because or by preference.

![image](https://user-images.githubusercontent.com/61223313/132398226-5437b79d-c00c-4bc3-b9a5-113178c4cfea.png)
