### ISSUE TITLE
Licence links

### ISSUE THREAD

**Issue by Rochet2** [azerothcore/azerothcore-wotlk#775]
None of the license links work.
If you go see any file and test the license link you can see that the link is dead.

GPL directs to
https://github.com/azerothcore/azerothcore-wotlk/LICENSE-GPL2
and the correct one is for example this (or any other working link)
https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-GPL2
Example file: https://github.com/azerothcore/azerothcore-wotlk/blob/403ed2600f39c1105b6641086808a6cdafbca1c5/src/tools/map_extractor/System.cpp

And for AGPL they direct to
http://github.com/azerothcore/azerothcore-wotlk/LICENSE-AGPL
and the correct one is for example
http://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
Example file: https://github.com/azerothcore/azerothcore-wotlk/blob/cc89d773db33dc9188d9a0a3267f9cceb8ad1e21/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h

**Comment by Re3os** [comment]
This trash is not needed.There is used auto-move to https.

**Comment by Rochet2** [comment]
> There is used auto-move to https.

Not sure what you mean.
How is http/https related to this issue?
