### ISSUE TITLE
[Tanaris Quest] Rescue OOX-17/TN! still requires (old) escort to Steamwheedle Port

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#7760]
Original Report: https://github.com/chromiecraft/chromiecraft/issues/1648

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

ALthough the quest text indicates that you will escort the robo chicken to the Caverns of Time, the actual quest takes you to Steamwheedle Port, as it did prior to this change in Wrath.

### Expected Blizzlike Behaviour

After only 1 ambush, not the 2 from Vanilla, and before the Wastewander camps on the way to Steamwheedle, the robo chicken (https://www.wowhead.com/npc=7784/homing-robot-oox-17-tn) can activate its rocket boots & fly away, completing the escort.

### Source

https://www.wowhead.com/quest=648/rescue-oox-17-tn#comments:id=16412:reply=117838

https://www.wowhead.com/quest=648/rescue-oox-17-tn#comments:id=800067

### Steps to reproduce the problem

1. Loot yourself https://tbc.wowhead.com/item=8623/oox-17-tn-distress-beacon, use to start quest
2. Go to 60, 64 (https://tbc.wowhead.com/quest=351/find-oox-17-tn)
3. Turn on RP walk & complete very slow escort

### Extra Notes

Detailed description of how the encounter should go:
https://wowpedia.fandom.com/wiki/Rescue_OOX-17/TN! 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by dr-j** [comment]
https://github.com/TrinityCore/TrinityCore/commit/8c303e4f979cff5c34f228054cea4e81bb70c11c that rescripts all 3 including shorter paths and take off as it stands not sure if this will work on azc as believe can still use sai but not sure about summon groups

**Comment by IntelligentQuantum** [comment]
> [TrinityCore/TrinityCore@8c303e4](https://github.com/TrinityCore/TrinityCore/commit/8c303e4f979cff5c34f228054cea4e81bb70c11c) that rescripts all 3 including shorter paths and take off as it stands not sure if this will work on azc as believe can still use sai but not sure about summon groups

It works fine on Ac, I tried all these.
But I do not know if this Quest is fixed correctly or not [Homing Robot OOX-09/HL SAI](https://github.com/TrinityCore/TrinityCore/commit/8c303e4f979cff5c34f228054cea4e81bb70c11c#diff-4dc7705d71c66584f052b976cd582289f87ee8aee76f0636e36533e9c59e4f27R89)
[Issue](https://github.com/azerothcore/azerothcore-wotlk/issues/6738#issuecomment-914949748)
