### ISSUE TITLE
[Class ability] [Druid] Feral Charge (Cat) not correctly scripted

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#7762]
Original report:  https://github.com/chromiecraft/chromiecraft/issues/1642
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
There are several issues:
- Positioning
- Dazing

POSITIONING:
When performing Feral Charge - Cat we jump over the enemy, right at the spot where it is, without any particular direction. Sometimes we get to be behind it, sometimes facing him, sometimes facing somewhere else. This is a very confusing and problematic error.
When enemies are in movement the effect happens but is not so obvious, since we move towards the spot the enemy was occupying a second ago and we get to be behind them. 
However, when we jump on a stationary enemy, we don't get ourselves BEHIND him.

Test done on Target Dummy
Before using Feral Charge and After using Feral Charge from the front:
![ 2021-09-06 at 10 39 10](https://user-images.githubusercontent.com/77953030/132180067-0cce806b-f6e8-4a78-9695-fc384bf51cdc.png)
![ 2021-09-06 at 10 39 18](https://user-images.githubusercontent.com/77953030/132180169-738d6417-d0e6-41a9-ac79-2948f3d9a8f6.png)

Before using Feral Charge and After using Feral Charge from the side:
![ 2021-09-06 at 10 52 04](https://user-images.githubusercontent.com/77953030/132180513-7dad2863-1c94-4f2b-bde3-48eab1bab07a.png)
![ 2021-09-06 at 10 52 07](https://user-images.githubusercontent.com/77953030/132180536-18fe7476-0c33-40da-a445-5f5bf6965f89.png)

Before using Feral Charge and After using Feral Charge from behind:
![ 2021-09-06 at 10 53 29](https://user-images.githubusercontent.com/77953030/132180707-2f5fc705-51c1-4e7d-b3dd-ed9bb18d625e.png)
![ 2021-09-06 at 10 53 33](https://user-images.githubusercontent.com/77953030/132180735-abe771f6-80f2-49ad-80ae-4be9c1eb2e26.png)

![ 2021-09-06 at 11 25 19](https://user-images.githubusercontent.com/77953030/132185359-10741b9d-5a37-4dce-8fcd-f76f3928aa6b.png)
![ 2021-09-06 at 11 25 30](https://user-images.githubusercontent.com/77953030/132185368-cd4f863b-c597-4013-8f4d-d71627241ac8.png)

DAZING:
**After** using Charge and landing on an enemy, it should get [dazed](https://wotlk.evowow.com/?spell=50259) and its speed reduced to 50% for 3 seconds. This is currently not working properly, as the debuff is applied the moment we USE the skill and not when we reach the mob, losing a big % of the Daze while we are still on the air. 

### Expected Blizzlike Behaviour

Using Feral Charge - Cat should happen in the following way:
1 - jump from the distance
2- land behind target
3- daze target for 3 seconds (apply snare 50% speed)
4 - keep our character right BEHIND the enemy (either if it is moving or not) and facing his back, ready to shred or whatever, and NEVER right on top of it or facing it.

Using Feral Charge - Bear should make us move towards the enemy, immobilizing and interrupting but not placing us behind it.

### Source

https://wotlkdb.com/?spell=49376

CHARGE: https://wotlk.evowow.com/?spell=49376
DAZE: https://wotlk.evowow.com/?spell=50259

you can see plenty of kitty jumps on this video to see how it should be working:
https://www.youtube.com/watch?v=OwTaLBTSd3M
https://www.youtube.com/watch?v=0rMqXH0A1I8

Charge (Bear):
https://wotlk.evowow.com/?spell=49377

### Steps to reproduce the problem

1 - Get a druid to at least lvl 20
2 - Learn Feral Charge - Cat (id 49376)
3 - Use Feral Charge - Cat on some enemy or Target dummy

### Extra Notes

Triager notes; Tested with duel, indeed, got the same issue as you: Daze effect starts immidiately, when stationary I get in front of target always, when moving it appears to be getting behind the target.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
In these videos you can see that the daze is applied on use, not on reach. 
https://youtu.be/0rMqXH0A1I8?t=3
Set to 0.25 - you can see the dazed effect on enemy right after use, not on reach.
