### ISSUE TITLE
[Find Herbs] and [Lifeblood] (Rank 4) remained in SpellBook after removing Herbalism

### ISSUE THREAD

**Issue by Samsequel** [azerothcore/azerothcore-wotlk#7764]
### What client do you play on?

ruRU

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Find Herbs] and [Lifeblood] (Rank 4) remaine in SpellBook after removing Herbalism.

### Expected Blizzlike Behaviour

[Find Herbs] and [Lifeblood] (Rank 4) must be removed along with Herbalism

### Source

You can check my character. Nickname: Santaria
I use ruRu client, sorry for the screenshot.
<details>
<summary>Screenshot</summary>

![34235](https://user-images.githubusercontent.com/32459796/132096496-b6d02783-3c3f-4411-b88d-cd76c3e1773a.jpg)
</details>

### Steps to reproduce the problem

1. Learn Herbalism and upgrade 300/300
2. Remove Herbalism
3. Learn any other profession. In my case tailoring.
4. Check [Find Herbs] and [Lifeblood] in SpellBook

### Extra Notes

Triager: Does not appear to stay when relogging, but it does stay in book after unlearning (and useable). (but user claims they still have it, I cant test that or replicate it) Possibly also other professions.  Does not happen 100% of the time, about 50% of the time. Maybe has to do something with https://github.com/azerothcore/azerothcore-wotlk/issues/7415
Also, happened before:
https://github.com/azerothcore/azerothcore-wotlk/pull/7290

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Can't reproduce it. Need to know what exactly to do to have these spells in spellbook.

**Comment by IntelligentQuantum** [comment]
Confirm https://github.com/azerothcore/azerothcore-wotlk/commit/792b99cbc9a6eac43c564993e80e02ac8333cc9f

But when you LogOut/Login, the spell does not exist anymore.

**Comment by UltraNix** [comment]
@IntelligentQuantum So tell me in steps how to reproduce it.

**Comment by IntelligentQuantum** [comment]
@UltraNix 
```
1. .go c 98866
2. Learn herb
3. .setskill 182 300 300
4. Unlearn herb
5. Then still you have  [Find Herbs] and  [Lifeblood]
```
