### ISSUE TITLE
[Waypoint Script][Creature 8256]Curator Thorius & [Creature 1692]Gorlorn Frostbeard

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#7766]
### Current Behaviour

Curator Thorius (ID: 8256) and Gorlorn Frostbeard (ID: 1692) have all waypoints added but they arent scripted in a blizzlike manner.

They are missing orientations, and respective emotes while walking their waypoints.

### Expected Blizzlike Behaviour

They should be proper scripted within their waypoint.

### Source

Possible Fix (?) can be found here: 
https://github.com/TrinityCore/TrinityCore/issues/18779

### Steps to reproduce the problem

1. .go creature 8256/1692
2. See their faulty script

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/21bf2e5380d0044e3fa377ca0f416330afabc13c

### Operating system

Windows 10 x64

**Comment by Eronox** [comment]
Confirmed, emotes are missing. Also yes their orientiation are weird during the path
