### ISSUE TITLE
Aggro is broken

### ISSUE THREAD

**Issue by dunjeon** [azerothcore/azerothcore-wotlk#777]
**Description**:
Aggro is not working as intended.

**Current behavior**: Tell us what happens
Mobs pull and link at greater distances and with more sensitivity then they should.  (The configuration file setting is ignored too:  (Line 1652 worldserver.conf: Rate.Creature.Aggro = 1)

**Expected behavior**: Tell us what should happen instead
Aggro should have a maximum range of 45 according to source code Entities -> Creature -> Creatures.cpp line nuber 2706 " // The maximum Aggro Radius is capped at 45 yards (25 level difference)"
And a minimum 20 according to source (cited above) line number 2710 "// The base aggro radius for mob of same level"

**Steps to reproduce the problem**:

1.  A good example is to run  the stockade dungeon
2. While in the hallway mobs will aggro from all rooms instead of none.
3. The issue is not isolated to dungeons it is world wide
4. Try to edit Line 1652 worldserver.conf: "Rate.Creature.Aggro = 1" to a 0.5 or 0 (It won't matter, nothing will fix the aggro)

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master

**AC hash/commit**:  
403ed26

**Operating system**:  
Windows 10 x64

**Modules**:  Are you using modules? if yes, list them
None

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
No Customization

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Trystanosaurus** [comment]
I've tried stockades and it seemed relatively blizzlike to me, I recall that place being a pain in the ass.

I think the fix for the creature aggro rate in the config is fairly straight forward. 

In the function you'd found for aggro (\server\game\Entities\Creature\Creature.cpp - line 2697). You should be able to make the aggro setting work by adding the following in just before the aggro range is returned (e.g. line 2731). I'm afraid I'm a noob when it comes to how this core works so it might not be best practice or whatnot, it might work though.

`aggroRadius *= sWorld->getRate(RATE_CREATURE_AGGRO);`

I've tested it quickly and it seems to work.

The assist radius from the config file does seem to be being used, so if you want less adds when pulling you should be able to reduce that.

**Comment by talamortis** [comment]
could you do a PR please then we can test

**Comment by Trystanosaurus** [comment]
I've made a PR (hopefully). It's the first time I've made one so let me know if any details are missing.

**Comment by dunjeon** [comment]
While the solution for the conf file from Trystanosaurus is viable it is only part of a required solution..

(I have not tested this, but I am sure that the above solution if set to 0 will not result in a zero aggro radius. Why does this matter? If the minimum values don't function correctly then the maximum values will also fail to be accurate -- try to do a strategic mob pull of any kind) 

I will put together and example of how aggro should function vs how it is working.

**Comment by dunjeon** [comment]
1) The picture with the range in white is correct (not azerothcore) Rate  in configuration file  = 1

2) The other picture is incorrect (azerothcore-WoTLK) Rate  in configuration file  = 1 (after PR update from Trystanosaurus applied)

Azerothcore aggro is  ~5 (+ or -) more sensitive than it should be and this also applies to family links.  The issue is world wide and not isolated to instances.  

![aggro_wrong](https://user-images.githubusercontent.com/30352875/35772147-9716aa5c-08fe-11e8-9c6b-5cd908dd2af5.png)
![correct_aggro](https://user-images.githubusercontent.com/30352875/35772148-972b789c-08fe-11e8-8644-ba201bc86403.png)

**Comment by Trystanosaurus** [comment]
I can confirm that with my tweak to use the config file modifier creatures still aggro if you walk through them when the setting is 0.

I've done a bit of digging to see if I can find out what's going on. The bit that's working out if a creature is in aggro range is line 1508 of creature.cpp

```
    if (!assist)
        if (IsNeutralToAll() || !IsWithinDistInMap(who, GetAggroRange(who) + m_CombatDistance)) // pussywizard: +m_combatDistance for turrets and similar
            return false;
```

Since GetAggroRange has to be returning 0 (anything * the conf setting of 0 = 0) I thought it might be adding in m_combatDistance that was doing it but removing that temporarily had the same result, the creature goes hostile when you touch it's target ring pretty much.

This is because the within distance function (_IsWithinDist line 1063 of Object.cpp) adds the size of both objects to the distance to check, so it's essentially cheking from the edge of your targeting ring to the edge of the enemies (rather than centre to centre). 

```
    float sizefactor = GetObjectSize() + obj->GetObjectSize();
    float maxdist = dist2compare + sizefactor;
```

I tested removing the size factor and that seemed to sort it. Now with the conf setting on 0 you could walk through creatures without them aggroing. 

So that's where you'd look but I couldn't say if this a problem that needs a fix or not. Making aggro so it was 20 yards centre to centre (rather than edge to edge as it is now) is fine for human sized targets but in raids you need to add in the size factor or you'd never pull a big mob until you were standing in it.

You'd need to find some videos of people playing live Lich King servers with a distance mod on.

**Comment by dunjeon** [comment]
Good find here, Trystanosaurus.

I can confirm, after testing, that making the changes to sizefactor does seem --SEEM-- to solve the aggro issue -- without altering the default of min 20, max 45 and leaving the RATE_CREATURE_AGGRO as 1.

Testing on a large scale mob, Omor the Unscarred (Ramparts) aggros at the expected distance or 20 at least within ~2 of 20. (This result is a little confusing because it is safe to assume it would require a closer distance to pull due to the removal of  sizefactor).

I don't think commenting out sizefactor is the solution we want to use because it must be there for a reason?

float maxdist = dist2compare; //+ sizefactor;

**Comment by Trystanosaurus** [comment]
Yes, commenting our sizefactor I think would be a terrible idea. That function is used for almost all distance calculations.

I personally think it's working correctly as it is. 

I tested the 20 yard aggro with a mage (as fire blast is 20 yards). If the mage is one level higher than the target they can just get in range for a fire blast before body pulling. If the mage is one level lower they can't get in range before body pulling, which is what you'd expect.

The only thing with the current system I can see is that the config Rate.Creature.Aggro says that 0 disables aggro but you do still body pull if you're walking over the target.

If that's a problem a better solution than changing _IsWithinDistance would be to put something into CanStartAttack in creature cpp to disable body pulling when the config setting is 0.

Something along the lines of changing line 1509 to:

`if (IsNeutralToAll() || sWorld->getRate(RATE_CREATURE_AGGRO == 0 || !IsWithinDistInMap(who, GetAggroRange(who) + m_CombatDistance)) // pussywizard: +m_combatDistance for turrets and similar`

That disables body pulling (when the setting is 0) without changing any core functions.

**Comment by Inifield** [comment]
Rate.Creature.Aggro isn't implemented afaik

**Comment by dunjeon** [comment]
@Inifield, Trystanosaurus  has a PR that implements Rate.Creature.Aggro (very easy fix)

@Trystanosaurus, I have been doing aggro tests with an addon called rangedisplay.  The default settings of the core seem to be a ~little to sensitive. Ultimately, it could be "close enough" for some, but it just doesn't feel right to me and I have a feeling that the slight difference is having an impact on rogue stealth being "off." (To me, the error is on the high end of accurate... 19.5 instead of 20.0 etc).

Also, I don't think that an aggro rate of 0 should result in zero aggro? I think 0 would result in 0 yards to trigger aggro -- which is why we still pull on touch.  My example of 0 in the post above wasn't very well thought out. (You have been a big help, thanks!).

**Comment by Inifield** [comment]
TC rewrote aggro calculation, could maybe solve our problem

**Comment by dunjeon** [comment]
@Inifield Right you are.  This week I am going to look into and test the solutions presented by other cores.  This is delicate because different doesn't mean better, and sunwell does so many things better.

**Comment by Trystanosaurus** [comment]
The working out aggro range seems to be almost identical between TC and AC, so it might be that the difference might be more fundamental, things like how distances are calculated (though from a quick look both cores do end up using the same _IsWithinDist function in object.cpp with the size factor added in).

Current AC aggro range function (excludes the small config file fix in my PR):
```
float Creature::GetAggroRange(Unit const* target) const
{ 
    // Determines the aggro range for creatures
    // Based on data from wowwiki due to lack of 3.3.5a data

    uint32 targetLevel = target->getLevelForTarget(this);
    uint32 myLevel = getLevelForTarget(target);
    int32 levelDiff = int32(targetLevel) - int32(myLevel);
    
    // The maximum Aggro Radius is capped at 45 yards (25 level difference)
    if (levelDiff < -25)
        levelDiff = -25;

    // The base aggro radius for mob of same level
    float aggroRadius = 20.0f;

    // Aggro Radius varies with level difference at a rate of roughly 1 yard/level
    aggroRadius -= (float)levelDiff;

    // detect range auras
    aggroRadius += GetTotalAuraModifier(SPELL_AURA_MOD_DETECT_RANGE);

    // detected range auras
    aggroRadius += target->GetTotalAuraModifier(SPELL_AURA_MOD_DETECTED_RANGE);

    // Just in case, we don't want pets running all over the map
    if (aggroRadius > MAX_AGGRO_RADIUS)
        aggroRadius = MAX_AGGRO_RADIUS;

    // Minimum Aggro Radius for a mob seems to be combat range (5 yards)
    // hunter pets seem to ignore minimum aggro radius so we'll default it a little higher
    float minRange = IsPet() ? 10.0f : 5.0f;
    if (aggroRadius < minRange)
        aggroRadius = minRange;

    return aggroRadius;
}
```

Current TC aggro range function
```
float Creature::GetAttackDistance(Unit const* player) const
{
    float aggroRate = sWorld->getRate(RATE_CREATURE_AGGRO);
    if (aggroRate == 0)
        return 0.0f;

    uint32 playerlevel   = player->getLevelForTarget(this);
    uint32 creaturelevel = getLevelForTarget(player);

    int32 leveldif       = int32(playerlevel) - int32(creaturelevel);

    // "The maximum Aggro Radius has a cap of 25 levels under. Example: A level 30 char has the same Aggro Radius of a level 5 char on a level 60 mob."
    if (leveldif < - 25)
        leveldif = -25;

    // "The aggro radius of a mob having the same level as the player is roughly 20 yards"
    float RetDistance = 20;

    // "Aggro Radius varies with level difference at a rate of roughly 1 yard/level"
    // radius grow if playlevel < creaturelevel
    RetDistance -= (float)leveldif;

    if (creaturelevel+5 <= sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL))
    {
        // detect range auras
        RetDistance += GetTotalAuraModifier(SPELL_AURA_MOD_DETECT_RANGE);

        // detected range auras
        RetDistance += player->GetTotalAuraModifier(SPELL_AURA_MOD_DETECTED_RANGE);
    }

    // "Minimum Aggro Radius for a mob seems to be combat range (5 yards)"
    if (RetDistance < 5)
        RetDistance = 5;

    return (RetDistance*aggroRate);
}
```

**Comment by dunjeon** [comment]
The TC aggro, shown above,  is also the same used by Nostalrius

**Comment by dunjeon** [comment]
@Trystanosaurus
In testing I can confirm an aggro error of 1.2799.  I have a solution in place (along side some additions to your Creature.cpp PR -- beyond the suggestion I made on that PR).  But I will withhold until I have done a bit more testing because my sample size is very small currently!
