### ISSUE TITLE
(Core/Creature): Mob health not reset when you take dungeon queue

### ISSUE THREAD

**Issue by Si1ker** [azerothcore/azerothcore-wotlk#7771]
Original report at https://github.com/chromiecraft/chromiecraft/issues/1651

### Current Behaviour

If you leave the world in the middle of a fight to take a dungeon finder queue the monster's health is not reset.

I was in Redrige in a cave, I attacked a gnoll and took a queue to a Stockades run, when I returned the gnoll I had taken down to ~30% was in aggro range and still at 30% health when it ran at me. I was in the dungeon for 10-15 minutes.

### Expected Blizzlike Behaviour

Monsters should completely reset back to their original status when you take dungeon queues.

### Steps to reproduce the problem

Queue for any dungeon
Be in a fight when the popup to enter the dungeon comes up
(I suppose having nobody else encounter the mob during this time is needed)
Finish or leave the dungeon

### AC rev. hash/commit

dd0b964

### Operating system

Windows 10

**Comment by FrancescoBorzi** [comment]
@Si1ker don't forget the Project too ;)
