### ISSUE TITLE
[Draenei/emote] The female Draenei /flirt emote only use 2 sound files

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#7774]
https://github.com/chromiecraft/chromiecraft/issues/1586

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

The /flirt emote of the female Draenei only use these 2 commands.
```
/run PlaySoundFile("Sound/character/Draenei/DraeneiFemaleFlirt07.wav")
/run PlaySoundFile("Sound/character/Draenei/DraeneiFemaleFlirt08.wav")
```

### Expected Blizzlike Behaviour

It should have a chance to use that commands instead of the flirt 07 and flirt 08.
```
/run PlaySoundFile("Sound/character/Draenei/DraeneiFemaleFlirt10.wav")
```

There are 2 other commands. However, on a 6.1.2 wowhead comment, it says that they were removed.
https://www.wowhead.com/draenei#comments:id=2159532

(Note: be ready, it is scary.)
```
/run PlaySoundFile("Sound/character/Draenei/DraeneiFemaleFlirt01.wav")
/run PlaySoundFile("Sound/character/Draenei/DraeneiFemaleFlirt02.wav")
```

### Source

The sound files are already available in the game client.
This link shows the quotes that each races get to say: https://wowpedia.fandom.com/wiki/Flirt

### Steps to reproduce the problem

Make a female space goat.
Do `/flirt`.
Listen.
Repeat.

### Extra Notes

Let's just add the flirt 10, we don't need the 01 and 02. :)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by lineagedr** [comment]
These were removed after wotlk beta.

**Comment by Kitzunu** [comment]
if that's true, then please close the issue

**Comment by JamesGent** [comment]
> 
> 
> These were removed after wotlk beta.

Can you provide a source? @lineagedr

**Comment by gurveleg** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Flirt
In addition, several Draenei female flirts were removed in Beta. These included:

    "You have heard of the Exodar? I will show you the Sexodar!"
    "Okay, for mating ritual, we will need four... No, five sheep, one gnome, and Staff of Domination. Put gnome in bag, beat bag with staff, and meet me after gnome is tenderized."
    "I want you to *lick and splat* my *gurgling noises* *slurping noises*"
    "Oh darling, I love it when you say *indistinct growling* *repeated yell*"
    
https://wowpedia.fandom.com/wiki/Flirt - says several were removed in beta, lists only the Sexodar one.
https://wowwiki-archive.fandom.com/wiki/Flirt - also says the above were removed in wotlk beta, but the last 3 were added back in Legion, only Sexodar one not.

**Comment by UltraNix** [comment]
This is completely clientside.
