### ISSUE TITLE
[Blackrock Depths - Boss] Summoner's Tomb/ The Seven Event too fast

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#7776]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

### Current Behaviour

When you get to Summoner's Tomb and when you pull the event. Bosses that should spawn every 45 seconds or so, but here they spawn every 20 sec or so, might be wrong, never counted. But everyone in multiple runs (over 20) stated that they spawn faster than expected leading to fight 3 bosses at once instead max 2.
https://classic.wowhead.com/npc=9039/doomrel#drops;mode:normal

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=wW84027e2JU&ab_channel=Chou-chiChang

At lower levels in BRD you on Blizzlike WoW have time to kill 1 by 1 boss, while here bosses spawns so fast that you get 3 at some point even with BiS lvl 49 gear and so fast killing with WoTLK talents. Our spawn times are insane.

### Steps to reproduce the problem

1. Enter BRD and get to Summoner's Tob (Near the end of BRD full run)
2. Start the event by talking to one of bosses (straight forward when you enter door)
3. Bosses spawning so fast, literally 20 sec or 25, get 3 bosses at some point to handle.

### Extra Notes
Original Report: https://github.com/chromiecraft/chromiecraft/issues/1659
Triager notes:
https://www.youtube.com/watch?v=QoEwUz7Bdq8

24:41 Anger'rel 
25:18 Seeth'rel (killed before next one activated)
25:40 Dope'rel (killed before next one activated)
26:03 Gloom'rel (killed before next one activated)
26:26 Vile'rel (killed before next one activated)
26:51 Hate'rel (killed before next one activated)
27:12 Doom'rel 

Right now, they spawn in 14-20 seconds on CC.
They should either spawn on a timer, or when they are too quickly die, the next one should activate.
https://wowpedia.fandom.com/wiki/The_Seven
`All of the mobs in the encounter are immune to curses. Also the event is entirely on a timer. After a set amount of seconds, the next mob will release and aggro the first player it sees.`

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
Currently it should be 15s if the code is doing what it says, give or take the update timestep. 

The video you sent suggests it's closer to 30s (combat start at 00:20, 2nd mob at 00:50 as you can see her start casting, next one is seen running to them at 1:20.
