### ISSUE TITLE
Mount aura remains when teleporting out of RDF and on a flight

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#7778]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1661

Even though i'm dismouted i'm getting mount bonus speed buff. (see steps to reproduce the problem).

### Expected Blizzlike Behaviour

When you get dismounted you should not get mount speed bonus.

### Steps to reproduce the problem

1 - Get on a gryphon, flying heading toward anywhere location
2 - While flying start RDF and search for a dungeon where you can mount inside of (zul' farrak)
3 - Once your are inside an instance, get on your mount
4 - Teletrasport outside using the eye button near the minimap (the rdf button)
5 - Once your gryphon arrives at destination you should have mount speed bonus without actually mounting

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Tester confirmed on local AC (a97e73e59).
I tested it in Zul'Farrak. I was on a flight before, got into Zul'Farrak through the dungeon finder, mounted up and teleported out again:
![unknown_2021 09 08-10 25](https://user-images.githubusercontent.com/68868567/132474819-9e9f4454-a05f-4291-88f9-aa661e462ef1.png)
![unknown_2021 09 08-10 27](https://user-images.githubusercontent.com/68868567/132474825-3e545960-e06e-4f98-8ec7-29483c09a798.png)
The mount aura remains, without being on a mount.

**Comment by IntelligentQuantum** [comment]
it really odd, there is a problem with the Warman and Wowcircle server.

The only way I can think of is when the player is teleporting out has to be dismount, But i have no clue if it’s a right to do or not.
Just when player was riding a Gryphon Master

**Comment by syssneck** [comment]
Reminds me of this issue here, which was already fixed: https://github.com/azerothcore/azerothcore-wotlk/issues/7240

**Comment by IntelligentQuantum** [comment]
```diff
@@ -9704,6 +9704,11 @@ void Player::ContinueTaxiFlight()
        RemoveAurasByType(SPELL_AURA_MOD_SHAPESHIFT);
    }

    if (IsMounted())
    {
        RemoveAurasByType(SPELL_AURA_MOUNTED);
    }

    GetSession()->SendDoFlight(mountDisplayId, path, startNode);
}

}
```

@syssneck It can be done, but I do not know if it is the right thing to do

**Comment by UltraNix** [comment]
@IntelligentQuantum Make a PR about it.
