### ISSUE TITLE
[Maraudon] Rock Worms, Rock Borers, and Vile Larva giving Light Leather on skinning

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7779]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1666

Rock Worm (NPC 11788) - Level 41-42
Rock Borer (NPC 11787) - Level 40-41
Vile Larva (NPC 12218) - Level 44

All of these mobs are granting Light Leather/Hide on skinning, as if they were level 15-20 mobs.

### Expected Blizzlike Behaviour

All 3 mobs should be dropping leather equivalent to other level 40+ beasts. ie - Heavy/Thick leather, Thick/Heavy Hides

OR

They should not be skinnable at all. There seems to have been a change between TBC and WOTLK where some DBs started to accumulate skinning data for them, but none of the versions of wowhead (classic, classic TBC, live, or PTR) have any skinning data for any of them, suggesting they aren't skinnable on any version of live. 

Testers note:
I could not find any primary source, which states them as skinable, so I'd go with removing their skinning table. They are made of rocks, right?

### Source

https://tbc.wowhead.com/npc=11788/rock-worm (no skinning data)
https://wotlkdb.com/?npc=11788#skinning (skinning data)
https://vanillawowdb.com/?npc=11788 (no skinning data)
https://wowgaming.altervista.org/aowow/?npc=11788#skinning (skinning data)

### Steps to reproduce the problem
1. .go c 26974
2. Kill it
3. Skin it

Kill any of these mobs
Skin them
Notice the leather being granted isn't the right level

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by awshew** [comment]
made of rocks / gross larval tissue - definitely shouldn't be skinnable!
