### ISSUE TITLE
Feature: World PvP event

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#7789]
### Describe your feature request or suggestion in detail

(Courtesy of @Hacki95)
A certain zone can be flagged as a "conquested zone", all players who enter this zone will be flagged for PVP.
Players are encouraged to "hold" a certain point within the zone, let's say Crossroads in The Barrens (although neutral hubs to hold would be preferable).

Players would then either need to hold the area for a certain time or gather a certain number of spawning objects (as something like points, players would need to stand still to collect them so it's only possible if one faction "wins" at the moment and no fight is ongoing).

After a certain amount of time, maybe an hour, the event would be done and the side with the most points/time hold would win. Players participating could be counted by players which were for longer than 5-10 minutes in the zone while the event was going on or players who helped collect objects etc.

### Describe a possible solution to your feature or suggestion in detail

In general, I am thinking of this as a C++ module.

There would be a new table in the DB that holds the possible zones which can be used for the conquest event with "zone id" and "area-id". The zone id would be used for the zone which flags the player for PVP, and the areaid is for the area which needs to be attacked/defended.

If the win condition would be done via gameobject collecting then there would also need to be a new table with possible spawn points for these objects. (Maybe an already existing SAI table could be used, not sure)

In general, I would think a timed system works best here. It should be possible to set up this system to trigger at certain times a day, certain days a week. For example make a schedule that randomly makes an area conquerable 3x a week once at 9 am, once at 9 pm, and once at 6 pm (just an example). 

It should also be possible to manually start an event via GM command.

Implementation wise not all features would be needed for a first version.,

### Additional context

A minimum version would need to contain:
- A few predefined areas, either in DB or script.
- A GM command which can start/stop the event.
- Fitting RP broadcast messages which urge players to join the fight.
- A win condition such as holding the point for collectively 15mins without a fight (a fight pauses the counter).

**Comment by iraizo** [comment]
Currently implemented/going to be implemented:
- [x] Kill goal
- [ ] GM commands (50%)
- [x] Broadcast
- [x] Leaderboard broadcast
- [ ] Collectable objects/points (later on with the help of @55Honey )
- [x] Configureable kill goal and announcement delay.
- [ ] Default zones/areas (im not creative i need a little bit of help with this)
- [ ] Timed start (still need to think of a way to do this)
- [ ] Timed end (read above)
- [ ] Automatic flagging of pvp  (50%) (player can still be unflagged by doing it manually: this needs a custom hook)
- [x] Random zone/area based on the configuration.

**Comment by iraizo** [comment]
Nearly everything has been implemented now, the only big thing that is left before testing would be 
```
If the win condition would be done via gameobject collecting then there would also need to be a new table with possible spawn points for these objects. (Maybe an already existing SAI table could be used, not sure)
```
which i would need help with accomplishing

**Comment by 55Honey** [comment]
I suggest a new table for such data per module/per purpose. We can add an SQL query to the module, which creates a new table and fills it with the required data. It would be mandatory to execute it.

What info would be required for these gameobjects? Only `map id` and `x,y,z`coordinates? Or also different types? Something else?

**Comment by 55Honey** [comment]
A lot of work was done already, please check https://github.com/azerothcore/mod-pvp-zones/issues if you want to help completing this.

**Comment by Kitzunu** [comment]
Can this be closed?
