### ISSUE TITLE
Core/Script: Karazhan Chess Event [$250]

### ISSUE THREAD

**Issue by Jagermaister95** [azerothcore/azerothcore-wotlk#779]
**Description**:The karazhan chess event does not work

**Current behaviour**: 
If you try to enter and talk to the king of your faction, the event does not start

**Expected behaviour**: Speaking to the king of his own faction, the event should start correctly allowing each player in the raid to take possession of a piece on the board to properly perform the fight.(post a video demonstration of how it should work) https://www.youtube.com/watch?v=b496Mc9A4U0

**Steps to reproduce the problem**:
1. enter karazhan
2. try to start the event by talking to the king of his own faction

**AC hash/commit**: 29f4a1e

**Operating system**: Linux

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=54545022)](https://www.bountysource.com/issues/54545022-bug-chess-event?utm_source=54545022&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/702

**Comment by Maurowin** [comment]
Hello, i don't know if that work, but i put it here if you can analyse a code : 
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp

**Comment by jhonatansm** [comment]
hi brother
 how to send 25usd to fix problem?

**Comment by BarbzYHOOL** [comment]
What do you mean?

**Comment by Maurowin** [comment]
@jhonatansm i don't want bounty, i had just some research on google.

**Comment by jhonatansm** [comment]
how to send money to Jagermaister95 for fix problem?

**Comment by BarbzYHOOL** [comment]
Jhonatansm, that's not how it works. Jagermaister95 has put a 25$ bounty for someone to fix this, so he wants to fix it like you. We need to find someone to fix it.

Maybe could add another bounty to this? I don't know how it works though

**Comment by jhonatansm** [comment]
LoL Understand Thanks

**Comment by BarbzYHOOL** [comment]
But that means we are missing something here, we could have bigger bounties if we put money together on an issue. We just didn't look into this at the moment

**Comment by BarbzYHOOL** [comment]
Some scripts to test https://mega.nz/#F!5vpTXQzL!2k7SuQCQMHl3MgCMSqogfg

Related PR https://github.com/azerothcore/azerothcore-wotlk/pull/702
