### ISSUE TITLE
Pets on stay dont move to use spells on friends if its out of Range or LoS

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#7790]
### Current Behaviour

If the pet is put on stay, and you try to use a pet spell on a _friendly_ target which is out of Range or Line of Sight, it won't move.
But if its an _enemy_, the pet does move (walks till it has range or line of sight) and cast the spell.

Tested with Warlock Felhunter with Devour Magic and Hunter pet Crab with Roar of Sacrifice/Intervene.

Recorded a video showing the behavior:
https://www.youtube.com/watch?v=ozhZLrE0aWo

I forgot to record the problem if the pet is out of line of sight (even if its close/in range), but the pet doesn't move.

### Expected Blizzlike Behaviour

The pet should move till it has range/LoS to cast the helpful spell.

### Source

I found this retail video:
https://www.youtube.com/watch?v=tqeLs1DbhOY

At 3:40, you can see the warlock gets feared by the priest, and the warlock pet is out of range on stay, then the warlock uses a macro to cast pet Devour Magic on him(to remove the Fear) and the pet starts moving closer to warlock till it has range and casts Devour Magic on warlock (you can see the animation/cd).

### Steps to reproduce the problem

1. Create a warlock, and cast Summon Felhunter (.add 6265 and .cast 691)
2. Create a macro to cast Devour Magic on yourself (/cast [@player] Devour Magic)
3. Set the pet on stay and move out of range or line of sight from the pet
4. Put a Magic Debuff on yourself (.aura 172)
5. Use the macro

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/186346a244b1

### Operating system

Windows 10 x64

**Comment by laasker** [comment]
Can someone reopen this please?

**Comment by Azcobu** [comment]
Reopened. This was closed as an act of vandalism by a disgruntled ex-contributor, and we're in the process of restoring everything now.

**Comment by laasker** [comment]
@UltraNix can you take a look please?

**Comment by UltraNix** [comment]
Okay.
