### ISSUE TITLE
Trial Of The Crusader Loot bug

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#7804]
### Current Behaviour

See this video https://vimeo.com/601676400

Sometimes it happens on all of the bosses

### Expected Blizzlike Behaviour

When the player's loot is closed, the player must be able to look at the loot again.

### Steps to reproduce the problem

1. .tele  TrialOfTheCrusader
2. Go to the inc
3. Kill Icehowl && Anub'arak
4. Loot the boss
5. Close the loot
6. You Can't loot it again

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5fba063fdf67faafd2940d36dcad92354a57197a

### Operating system

Arch linux x64

**Comment by Err0r1** [comment]
Confirmed.
Test the pull requests before you pull/merge them!

It has happened quite often lately that changes are not tested at all
It is completely ignored whether it causes other issues

**Comment by UltraNix** [comment]
It's not generic bug, but bad code within ToC bosses.

**Comment by darkenam** [comment]
confirm

bosses drop item hord for alliance and drop item alliance for hord!

player can't drop item request!

**Comment by UltraNix** [comment]
@darkenam Open a new issue ticket if it's still valid bug.
