### ISSUE TITLE
Piercing Blow seems to be ranged, when to my knowledge it should be melee range

### ISSUE THREAD

**Issue by im663** [azerothcore/azerothcore-wotlk#7813]
### Current Behaviour

When casting Piercing Blow it allows for users to cast from ranged rather than melee distance. Not entirely sure if this is the correct behavior.

### Expected Blizzlike Behaviour

To only allow melee ranged.

### Source

https://wotlkdb.com/?spell=49749

### Steps to reproduce the problem

1. Cast Piercing Blow
2. It allows ranged
3. Is this the correct behavior?

### AC rev. hash/commit

AzerothCore rev. 1f3a09776111 2021-07-25 19:44:16 +0200 (1f3a09776111fdcfb6c7317577964a214dbadee8 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80026
Using CMake version: 3.16.3
Compiled on: Linux 4.19.0-17-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_25_01
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Debian 10

**Comment by Kitzunu** [comment]
Add hash/commit.

**Comment by im663** [comment]
@Kitzunu updated, sorry about that.

**Comment by JamesGent** [comment]
Do you have a source that isn't a private server database?

**Comment by T1ti** [comment]
0 range means unlimited, melee abilities have 5

**Comment by Kitzunu** [comment]
@im663 from what range can you cast it? Use .dist on the target to get exact numbers

**Comment by im663** [comment]
Okay so while in Swindlegrin's Den, NPCs are using piercing blow from absurd distances, I will attatch 3 screenshots. My apologies about the dela
![Screenshot_2021-10-05_14-46-33](https://user-images.githubusercontent.com/22891065/136107706-47600915-1811-4771-bdef-476e083b83a9.png)
![Screenshot_2021-10-05_14-45-48](https://user-images.githubusercontent.com/22891065/136107715-e12d8c10-5308-4588-95ad-a1a23a6fe73c.png)
![Screenshot_2021-10-05_14-45-18](https://user-images.githubusercontent.com/22891065/136107719-4216aca8-7dc5-4837-830f-ff04064a4160.png)
y.

**Comment by im663** [comment]
https://www.youtube.com/watch?v=TrV65rKIFyg

around 1 minute in he starts aggroing mobs on a flying mount
he only takes damage when next to a mob
piercing blow damage is represented by purple text
notice how there is no purple text appearing on him while out of range

**Comment by im663** [comment]
Additionally, the nerubian skitterers in front of warsong hold in borean tundra also know piercing blow and cast it like a ranged spell too. i haven't noticed other melee spells with this behavior.
