### ISSUE TITLE
Booty Bay mailbox was moved to wrong position.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#7821]
### Current Behaviour

![WoWScrnShot_091121_122243](https://user-images.githubusercontent.com/61194190/132946248-7ad69dc6-01d3-4c8c-b2e6-66197f0eb737.jpg)

Currently its here.

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=4VqtRbOlj2M

https://external-preview.redd.it/853GqqymYSq2X3w5-EaAjD2bIGEBXmuJLe8VYPh-hBA.jpg?auto=webp&s=4528e6cebe687ba3ec2f4ac21fb5e07d5a67907d

It should be here.

### Source

Sources above.

### Steps to reproduce the problem

Go to Booty Bay
Observe the mailbox.

### Extra Notes

I don't know when it changed, but it recently moved.

### AC rev. hash/commit

AzerothCore rev. fafb06d3df76 2021-09-01 16:32:33 +0000 (temp-revert branch) (Unix, RelWithDebInfo, Static)

### Operating system

Linux

### Custom changes or Modules

ChromieCraft modules

**Comment by Kitzunu** [comment]
This commit doesnt exist https://github.com/azerothcore/azerothcore-wotlk/commit/fafb06d3df76

**Comment by syssneck** [comment]
@Kitzunu it's copied from the playermap: https://www.chromiecraft.com/playermap/ (current CC branch)

**Comment by JamesGent** [comment]
Ah my bad. Good to know it was moved on purpose.
