### ISSUE TITLE
Multiple warnings & error messages

### ISSUE THREAD

**Issue by Madera95** [azerothcore/azerothcore-wotlk#7823]
### Current Behaviour

In my last compile, after adding 2 modules (unchanged), error messages occurred at the end of the compile. Without these modules, it compiles completely. However, the warnings remain.

> [ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Com                                          mandLine/CliRunnable.cpp.o
In file included from /home/worldt/azerothcore/src/server/worldserver/CommandLin                                          e/CliRunnable.cpp:18:
In file included from /home/worldt/azerothcore/src/server/game/Maps/MapManager.h                                          :12:
In file included from /home/worldt/azerothcore/src/server/game/Maps/Map.h:15:
In file included from /home/worldt/azerothcore/src/common/Collision/Models/GameO                                          bjectModel.h:11:
In file included from /home/worldt/azerothcore/deps/g3dlite/include/G3D/AABox.h:                                          21:
In file included from /home/worldt/azerothcore/deps/g3dlite/include/G3D/Plane.h:                                          16:
/home/worldt/azerothcore/deps/g3dlite/include/G3D/Vector3.h:131:14: warning: def                                          inition of implicit copy constructor for 'Vector3' is deprecated because it has                                           a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& operator=(const Vector3& rkVector) = default;
             ^
/home/worldt/azerothcore/deps/g3dlite/include/G3D/Vector3.h:240:20: note: in imp                                          licit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
In file included from /home/worldt/azerothcore/src/server/worldserver/Main.cpp:1                                          7:
In file included from /home/worldt/azerothcore/src/server/game/Battlegrounds/Bat                                          tlegroundMgr.h:10:
In file included from /home/worldt/azerothcore/src/server/game/Battlegrounds/Bat                                          tleground.h:12:
In file included from /home/worldt/azerothcore/src/server/game/Entities/GameObje                                          ct/GameObject.h:12:
In file included from /home/worldt/azerothcore/deps/g3dlite/include/G3D/Quat.h:1                                          7:
/home/worldt/azerothcore/deps/g3dlite/include/G3D/Vector3.h:131:14: warning: def                                          inition of implicit copy constructor for 'Vector3' is deprecated because it has                                           a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& operator=(const Vector3& rkVector) = default;
             ^
/home/worldt/azerothcore/deps/g3dlite/include/G3D/Vector3.h:240:20: note: in imp                                          licit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
1 warning generated.
1 warning generated.
[100%] Linking CXX executable worldserver
/usr/bin/ld: ../scripts/libscripts.a(ScriptLoader.cpp.o): in function `AddScripts()':
/home/worldt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:72: undefined reference to `Addmod_cfbg_masterScripts()'
/usr/bin/ld: /home/worldt/azerothcore/build/src/server/scripts/gen_scriptloader/static/ScriptLoader.cpp:73: undefined reference to `Addmod_transmog_masterScripts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/build.make:191: src/server/worldserver/worldserver] Error 1
make[1]: *** [CMakeFiles/Makefile2:1063: src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

### Expected Blizzlike Behaviour

The compile should run through. The warnings do not matter for the time being.

### Steps to reproduce the problem

The compile works without modules. The error occurs with modules.

### AC rev. hash/commit

the newest

### Operating system

Debian 10x64

### Custom changes or Modules

Used modules:
 - CFBG
 - Transmog
 - Individual XP

**Comment by Kitzunu** [comment]
Make an issue in the module that made the build break
