### ISSUE TITLE
A Visit to the Doctor

### ISSUE THREAD

**Issue by im663** [azerothcore/azerothcore-wotlk#7827]
### Current Behaviour

Doctor Sabnok kills "Patches," breaking the second credit flag for the quest.

### Expected Blizzlike Behaviour

"Patches" attacks Doctor Sabnok for several seconds before Doctor Sabnok is scripted to die.

When I attack Sabnok and take aggro until Sabnok falls to the script threshold, the death script actually goes through fine or at least appears to. Player intervention appears to break the second credit flag the same between azerothcore and retail
You should try just editing "Patches" HP later to something high enough that he can survive against Doctor Sabnok by himself.
Even 50k might be enough. It's less un-blizzlike to change that to ensure the script functions properly. That's the only time "Patches" is ever used as far as I know, and you aren't supposed to ever battle him yourself.
Probably overall easier to edit HP as a fix to that quest than to fuck around with the scripting.

### Source

https://wotlkdb.com/?quest=13152

"Patches" the ghoul actually does do the scripted kill if he survives long enough, but the problem is that requires player intervention and player intervention breaks the credit flag the same as "Patches" dying to Doctor Sabnok.

### Steps to reproduce the problem

1. Accept "A Visit to the Doctor."
2. Travel to Sanctum of Reanimation, a cave in the Fleshwerks subzone.
3. Walk in and find "Patches," a ghoul.
4. Click the chain post world object next to "Patches."
5. Doctor Sabnok will spawn.
6. "Patches" fights Doctor Sabnok for several seconds. Doctor Sabnok is expected to die from a script, but "Patches" dies before this can happen.

### Extra Notes

Players are not expected to help "Patches" kill Doctor Sabnok as suggested by the quest objective. Player intervention breaks this quest on retail as well. "Patches" is meant to survive on its own until Doctor Sabnok dies from the quest script.

### AC rev. hash/commit

AzerothCore rev. 1f3a09776111 2021-07-25 19:44:16 +0200 (1f3a09776111fdcfb6c7317577964a214dbadee8 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80026
Using CMake version: 3.16.3
Compiled on: Linux 4.19.0-17-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_25_01
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Debian 10

### Custom changes or Modules

N/A

**Comment by JamesGent** [comment]
Is the quest completeable, or fully broken?

**Comment by im663** [comment]
> Is the quest completeable, or fully broken?

The quest is not comparable, and the scripting appears to not be working correctly.

**Comment by JamesGent** [comment]
```
UPDATE `creature_template` SET `HealthModifier` = 10 WHERE (`entry` = 30993);
```

Here is a hackfix that increases his HP from 12,000 to 120,000. You cited 50k as probably being enough to survive. 99.9% of players won't notice that his HP has 1 extra 0.

**Comment by im663** [comment]
> ```
> UPDATE `creature_template` SET `HealthModifier` = 10 WHERE (`entry` = 30993);
> ```
> 
> Here is a hackfix that increases his HP from 12,000 to 120,000. You cited 50k as probably being enough to survive. 99.9% of players won't notice that his HP has 1 extra 0.
> 
> I will wait a week for someone more skilled to do a better fix. If not, I will PR this hackfix.

Wonderful, thanks so much. Appreciate you, and the AzerothCore project.
