### ISSUE TITLE
Rested XP indicator not showing

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#7834]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1684

When logged back into the game, the xp bar is filled up with blue color, indicating rested xp. However, the little vertical bar that indicates how far the rested xp goes is missing. The vertical bar will show up once you gain xp the first time after logging in.

Tested on Local AC:
When you log in you can see the colored bar with rested XP, but theres no marker showing where it ends
![rested1](https://user-images.githubusercontent.com/80769357/132819327-46b0c125-46a3-4a44-9135-43b303e771f3.jpg)

After you do a /reload it shows up
![rested2](https://user-images.githubusercontent.com/80769357/132819363-c698bf32-7916-4102-88d1-4f326ab526a8.jpg)

### Expected Blizzlike Behaviour

https://wowwiki-archive.fandom.com/wiki/Rest When rested, your XP bar will turn blue, and a notch will appear indicating exactly how rested you are.

### Source

https://wowwiki-archive.fandom.com/wiki/Rest

### Steps to reproduce the problem

Log a char out of the game for some time and log back in.

### AC rev. hash/commit

https://grithub.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 7

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by JamesGent** [comment]
I can confirm this also. enUS client.

**Comment by UltraNix** [comment]
It is clientside thing - that indicator always shows up after 10 sec after got `PLAYER_FLAG_RESTING`
