### ISSUE TITLE
Some Waypoints are not smooth

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#7838]
### Current Behaviour

In the current state. NPCs are not quite walking smoothly from each waypoint to another.

They are always taking a very short "break" before continuing.

### Expected Blizzlike Behaviour

Waypoints should be smooth without any stutter

### Steps to reproduce the problem

1. Just search up an NPC with a stuttery waypoint

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/1ae8e7eca50d2d213a614ad45cefe6b6220e3161

### Operating system

Windows 10

**Comment by banehammer** [comment]
https://github.com/TrinityCore/TrinityCore/commit/28050f338dfc66e0c40b6a3915bf96e38e0613e5
https://github.com/TrinityCore/TrinityCore/issues/13467
https://github.com/TrinityCore/TrinityCore/pull/18888
https://github.com/TrinityCore/TrinityCore/pull/18020

Could be used as reference

**Comment by banehammer** [comment]
Update!
This is a weird issue. Some NPCs are stuttering and bugging around but some are not!

**Comment by heyitsbench** [comment]
I believe this is the same issue as https://github.com/azerothcore/azerothcore-wotlk/issues/10096.

**Comment by heyitsbench** [comment]
Closing in favor of #10096.
