### ISSUE TITLE
Logging into a character who is mid-flight can cause you to not join general chat for that zone

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#7842]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

I took a flight path from Stormwind to Lakeshire, and logged off of the character shortly into the flight. When I logged back in, on the bird, my character did not join general chat for either Elwynn Forest or for Stormwind (nor trade chat). See screenshot.

This does seem like a bug, but it also seems harmless. If you're flying, chances are you will be arriving at a new zone soon enough anyway and join that general channel.

### Expected Blizzlike Behaviour

Even on a flightpath, when you log in to a character, you should join the general chat of the zone your character is in, even while they are flying over it.

### Steps to reproduce the problem

Hop on a flight path.
Log off, perhaps it needs to be soon after crossing the border into another zone.
Log back on, see if you are entered into general chat for the zone.

### Extra Notes

You can see the yellow text messages showing that I just logged on, and the white text of the travelling merchant NPC who patrols on the ground along the path that the flight path takes from Stormwind to Goldshire, and you can see that my character joins world chat as /1, and no other chat.
![Screenshot (60)](https://user-images.githubusercontent.com/89823720/133000577-85b27d37-7139-4130-93d0-44710dacc92f.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

https://github.com/chromiecraft/chromiecraft/issues/1711

**Comment by UltraNix** [comment]
It's something clientside and I don't know what is the reason. The server correctly sees you on channel.
