### ISSUE TITLE
[Ashenvale] Akkrilus (rare) moving to fast and wrong respawn timer

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#7843]
### Current Behaviour

Akkrilus (https://wowgaming.altervista.org/aowow/?npc=3773) has his walking speed set to 1.81 and his spawn timer is set to 2h45min.

https://user-images.githubusercontent.com/80769357/133069162-3e8357c3-138f-4e95-a47f-caef9e1abc90.mp4

### Expected Blizzlike Behaviour

Akkrilus should be on a 21-32h spawn timer.
As for his walking speed, I'm not sure what is the correct value but current one is clearly too high.

### Source

https://wowwiki-archive.fandom.com/wiki/Akkrilus

![akkrilus](https://user-images.githubusercontent.com/80769357/133069352-a892e3ef-0655-4722-ba85-c6318c05e157.jpg)

### Steps to reproduce the problem

1. Teleport to guid 51883
2. observe his walk speed
3. check walk speed and spawn timer in DB

### AC rev. hash/commit

 AzerothCore rev. 26aee27f600d

### Operating system

Windows 7 x64

**Comment by Asthalor** [comment]
Yes. According to this classic video he should move way slower
https://youtu.be/9-pn8esjcrg?t=280

**Comment by gurveleg** [comment]
That video is not from a classic wow but from another private server. You can easily identify real WoW Classic videos because they have clock under minimap, and have voicechat icon at the top of the chat.

**Comment by Asthalor** [comment]
> That video is not from a classic wow but from another private server. You can easily identify real WoW Classic videos because they have clock under minimap, and have voicechat icon at the top of the chat.

Oh, didnt know that. I will see if we have any sniffs or find a classic video at least.

**Comment by gurveleg** [comment]
I always search for videos for my reports, but I couldn't find any for this particular mob that was relevant for Wotlk.

**Comment by T1ti** [comment]
most of those "rare classic mbo" videos on youtube are from private servers, make sure to check 
![image](https://user-images.githubusercontent.com/40864460/133161169-6e073e44-73ce-4a82-a7bf-c58475a1faea.png)

**Comment by T1ti** [comment]
I am currently looking at him on the classic PTR and he is not patroling at all so I can't check his walk speed
![image](https://user-images.githubusercontent.com/40864460/133162779-10bad376-2b81-4326-abf7-3a3da34a107a.png)
He might have different spawns points.
His run speed looks normal, I'd say set him to 1 run 1 walk
