### ISSUE TITLE
Core/Script: Icecrown Citadell 10 HC bugs

### ISSUE THREAD

**Issue by Szone** [azerothcore/azerothcore-wotlk#786]
**Description**: ICC 10 HC bugs

**Current behaviour**: 
~~**Marrowgar**: In bonestorm does not target the furthest target~~
**Gun Ship**: Muradine stacks do not scale down as much as @ dmg
**Rotface**: The oases change the target too easily
**Critic - Prof Putricide**: Abomination does not give Dmg and drink too fast paces / Green oaza dmg too much to the link and the one who is immobile gets dmg from slime
**Critic - Bloodprince council**: Conjure Empowered Flame gives a full dump to the explosion. It does not reduce its damage during it. It has to be consumed until it reaches the target and then explodes with the dmg left in it

(Icc 10 HC was tested live with 10 players)

**Expected behaviour**: 

**Steps to reproduce the problem**:

1. Start the fight
2. 
3. 

**Branch(es)**: 1.x 

**AC hash/commit**:  AzerothCore rev. 7696bd355e06+ 2018-02-02 00:52:49 +0200 (master branch) (Unix, Release)

**Operating system**:  Ubuntu server 16.04 x64

**Modules**:  Anticheat ,Transmog and duelreset

**Other Customizations**:-

Thank you!

**Comment by pondaveia** [comment]
Please do open one issue for each and everyone of these bosses if you please.

**Comment by a4501150** [comment]
can someone translate to better English?... and probably more accurate description so we can.. fix it

**Comment by a4501150** [comment]
Critic - Prof Putricide: Abomination does not give Dmg and drink too fast paces / Green oaza dmg too much to the link and the one who is immobile gets dmg from slime

Umm can we have this one more detailed/better organized?

**Comment by Kitzunu** [comment]
> While in his Bone Storm Lord Marrowgar will randomly target and charge a raid member. When he reaches them he stops moving for around six seconds before targeting another random raid member. 
https://wowwiki.fandom.com/wiki/Lord_Marrowgar

Bonestorm should pick random targets as it does. No bug here.
https://github.com/azerothcore/azerothcore-wotlk/blob/a6a7cbf887915b7441de19db38dfceff2a9bb182/src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp#L212

**Comment by qwe900** [comment]
> > While in his Bone Storm Lord Marrowgar will randomly target and charge a raid member. When he reaches them he stops moving for around six seconds before targeting another random raid member.
> > https://wowwiki.fandom.com/wiki/Lord_Marrowgar
> 
> Bonestorm should pick random targets as it does. No bug here.
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/a6a7cbf887915b7441de19db38dfceff2a9bb182/src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp#L212

just want to say this ist wrong the first target is the farthest away from lord, the next ones are random, I raidedt this alot as maintank in retail and can tell u the correct way

**Comment by Err0r1** [comment]
> > > While in his Bone Storm Lord Marrowgar will randomly target and charge a raid member. When he reaches them he stops moving for around six seconds before targeting another random raid member.
> > > https://wowwiki.fandom.com/wiki/Lord_Marrowgar
> > 
> > 
> > Bonestorm should pick random targets as it does. No bug here.
> > https://github.com/azerothcore/azerothcore-wotlk/blob/a6a7cbf887915b7441de19db38dfceff2a9bb182/src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp#L212
> 
> just want to say this ist wrong the first target is the farthest away from lord, the next ones are random, I raidedt this alot as maintank in retail and can tell u the correct way

Then show a proof. Anyone can claim anything

"I had thunderfury on my rogue twice on retail"
"I raided with it a lot"

It's still not true :kek:

**Comment by qwe900** [comment]
> > > > While in his Bone Storm Lord Marrowgar will randomly target and charge a raid member. When he reaches them he stops moving for around six seconds before targeting another random raid member.
> > > > https://wowwiki.fandom.com/wiki/Lord_Marrowgar
> > > 
> > > 
> > > Bonestorm should pick random targets as it does. No bug here.
> > > https://github.com/azerothcore/azerothcore-wotlk/blob/a6a7cbf887915b7441de19db38dfceff2a9bb182/src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp#L212
> > 
> > 
> > just want to say this ist wrong the first target is the farthest away from lord, the next ones are random, I raidedt this alot as maintank in retail and can tell u the correct way
> 
> Then show a proof. Anyone can claim anything
> 
> "I had thunderfury on my rogue twice on retail" "I raided with it a lot"
> 
> It's still not true :kek:

then just look for old kill or guide videos on youtube and you can  see it yourself 
Like these Just watch old videos from Lord like these:
https://www.youtube.com/watch?v=b7lGWk6V-74
