### ISSUE TITLE
What do you want to do with this link in the installation instructions?

### ISSUE THREAD

**Issue by ss958** [azerothcore/azerothcore-wotlk#787]
https://github.com/azerothcore/azerothcore-wotlk/wiki/Hooks-Cmake

我在 cmake 的时候每次都是因为这些问题自动停止

**Comment by Middel** [comment]
Please use the Issue system for reporting of bugs within AzerothCore source.

You can ask this question and other questions on our the AzerothCore Discord server
Invite Link: [https://discord.gg/gzncqWH](url)

**Comment by DarkmoonRabbit** [comment]
什么问题？我cmake正常的

**Comment by ss958** [comment]
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY


Do you know why these mistakes?
