### ISSUE TITLE
[Brewfest] Issues with Brewfest Revelers

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#7871]
### Current Behaviour

Brewfest Revelers Entry 24484  (https://wowgaming.altervista.org/aowow/?npc=24484) of horde or ally race are all set to friendly for Horde characters and neutral for alliance characters.

![revelerally](https://user-images.githubusercontent.com/80769357/133223213-1bb8db66-4b56-4b36-ba49-7211a7a02d94.jpg)
![revelerhorde](https://user-images.githubusercontent.com/80769357/133223216-fac081b2-9fc5-4891-945f-db4db00fec19.jpg)
![aaa](https://user-images.githubusercontent.com/80769357/133232491-74dfae90-5130-4335-848b-95dedadc2b37.jpg)
![bbb](https://user-images.githubusercontent.com/80769357/133232496-5a98587c-587b-4e32-a92e-e7918731fd27.jpg)

Doing /drink emote on Brewfest revelers does not award buff called Brewfest Toast.

Also, it seems that Brewfest Revelers are mising the RP scripts, they are all just standing still (with expcetion of two who are dancing).

https://user-images.githubusercontent.com/80769357/133233629-8786d041-c735-48da-8526-d29ea8bfc6ca.mp4

You can see that they don't have mugs, they don't cheer/drink

### Expected Blizzlike Behaviour

Brewfest Revelers of horde races should be friendly towards horde characters and neutral towards allaince characters.
Brewfest Revelers of alliance races should be firendly to alliance characters and neutral towards horde chartacters.

When doing a /drink emote on a brewfest reveler, you should get a 30 min 15 stamina buff called Brewfest Toast (https://wowgaming.altervista.org/aowow/?spell=41586)

Brewfest Revelers should have scripted RP, should talk/cheer/drink as shown in screenshots and videos linked in sources.

### Source

https://wowpedia.fandom.com/wiki/Brewfest_Reveler
https://tbc.wowhead.com/spell=41586/brewfest-toast#comments

https://youtu.be/nggjFT4GTTE?t=40 - video from 2009, shows alliance char in horde brewfest area, when hoovering over brewfest revelers there a sword appears

https://youtu.be/vmNIIGo5EzM?t=201 - video from 2010 brefest, you can see the revelers in Dun Morogh friendly towards alliance character

https://tbc.wowhead.com/npc=24484/brewfest-reveler#screenshots

### Steps to reproduce the problem

1. .event start 24
2. Go to Brewfest locations infront of Orgrimmar or Ironforge
3. Observe the revelers as ally and horde char at both locations

### AC rev. hash/commit

AzerothCore rev. 26aee27f600d

### Operating system

Windows 7 x64

**Comment by Asthalor** [comment]
They are using a script called npc_brewfest_reveler

According to the code they cast Brewfest Toast not when they are selected with /drink, but with /dance. Changing in `brewfest.cpp` line 39 `TEXT_EMOTE_DANCE` with `TEXT_EMOTE_DRINK` should do the trick i think.

**Comment by UltraNix** [comment]
@gurveleg @Asthalor Test with #8026

**Comment by Shineslippers** [comment]
Related to https://github.com/chromiecraft/chromiecraft/issues/1862

The issue is still exist. After invasion event Brewfest Revelers in Dun Morogh became neutral to Allince players. Probably they have wrong faction `775`. Should be `774`
![WoWScrnShot_111921_181353](https://user-images.githubusercontent.com/85256266/142646763-08703294-8553-46b8-adea-02abc720be18.jpg)
