### ISSUE TITLE
[Brewfest] Dark Iron attack not working properly

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#7872]
### Current Behaviour

When the Dark Iron attack starts, the Brewfest Revelers do not flee the area.
The Dark Iron Guzzlers (https://wowgaming.altervista.org/aowow/?npc=23709) move too fast and are glitchy, starting to glide after drink animation.

https://user-images.githubusercontent.com/80769357/133238727-71d3cb07-545a-4b0b-a465-653870d86100.mp4

https://user-images.githubusercontent.com/80769357/133238747-9de2ece2-85ba-4d6d-935a-d448c97264ad.mp4

Haven't check Horde side yet.

### Expected Blizzlike Behaviour

Brewfest revelers should flee the area of the attack before the Dark Iron attack starts.
Dark Iron Dwarves should move slower and should not glitch to gliding after doing drink animation.

### Source

https://youtu.be/vmNIIGo5EzM?t=653

https://youtu.be/QSwCSD9t_BI?t=28

https://tbc.wowhead.com/npc=23709/dark-iron-guzzler#comments
https://wowpedia.fandom.com/wiki/Dark_Iron_Guzzler
https://wowwiki-archive.fandom.com/wiki/Dark_Iron_Guzzler

### Steps to reproduce the problem

1. .event start 24
2. observe the Dark Iron attack (happens every hour at half hour time, like 5.30, 6.30 etc)

### AC rev. hash/commit

AzerothCore rev. 26aee27f600d

### Operating system

Windows 7 x64

**Comment by Stump876** [comment]
Every 30 minutes there is an invasion. 5:30. 6:00, 6:30. I can confirm on Horde side everything said above. I would also add kegs to not have a "broken" animation, it's hard to tell what ones are still standing if you're trying to defend. Also for horde, only the `Drohn's Distillery Barker` (GUID 88944) seems to toss new mugs for the event. Even if you are standing right next to another barker. The closest barker should toss you a new mug.
https://user-images.githubusercontent.com/68164076/133375981-5071d426-2547-4e6a-8ff9-7ac127280e87.mp4


Also the Dark Iron Sabotage Plans are always present in Durotar. You can see it in the video above on the ground. This gives the Quest [Seek the Saboteurs](Quest:Seek the Saboteurs) quest. This should have been removed from the game in favor of the Cog with the repeatable daily. (See comments from 3.0.1 in the link) If you had someone with the quest already it was shareable.

**Comment by gurveleg** [comment]
With dwarves moving so fast you need 15+ people there to be able to defeat the attack, makes doing the daily near impossible without premade raid group.

**Comment by UltraNix** [comment]
@Stump876 Make a new report with every single bug not related to Dark Iron Event.
