### ISSUE TITLE
Spell Cooldown Modifier did not work after#7559

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#7877]
### Current Behaviour

After this commit,Talent Spell Modifier and Glyph did not work!
Just like Improved Judgements(spell id :25957)
Judgements should be 8s but now still 10s
Please check again

It's normal Before PR#7559

### Expected Blizzlike Behaviour

Cooldown modifier should work

### Source

#7559 change the spell cooldown system

### Steps to reproduce the problem

Create a paladin@lv80
Learn all spells
Learn Talent Improved Judgements(spell id :25957)
Use Judgements
Spell shows 8s cooldown but 2s more

### AC rev. hash/commit

AzerothCore rev. 85553974912e
commit:7406a01ac303ef1ee68b698b9c4ebf2c6b1666a2

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
Dont close vebefore the fix has been merged
