### ISSUE TITLE
Some auras are missing from creatures

### ISSUE THREAD

**Issue by Asthalor** [azerothcore/azerothcore-wotlk#7879]
### Current Behaviour

According to some sniffs and vmangos info we have some creatures that are missing auras.
So far the ones ive seen are:

Defias Night Blade(id: 909) missing aura 8601(Slowing Poison) and having the wrong cast on smartAi.
Webwood Spider(id: 1986) missing aura 6752(Weak Poison Proc) to posion player.
Shadra(id: 2707) missing aura 8601(Slowing Poison) and 13299(Poison Proc)
Mangy Silvermane(id: 2923) missing aura 18847(Fevered Fatigue) and instead is casted on smartAI
Lady Anacondra <Fanglord> (id: 3671) missing aura 13236(Nature Channeling)
Bleakheart Satyr(id: 3765) missing aura 6947(Curse of the Bleakheart Proc)
Fardel Dabyrie(id: 4479) missing aura 8876(Thrash) and instead is casted on smartAI
Nightmare Scalebane(id: 5277) missing aura 12099(Shield Spike)
Lord Azrethoc(id: 5760) missing aura 7974 (Azrethoc's Flight) and 15097(enrage)

### Expected Blizzlike Behaviour

They should have the auras accordingly

### Source

Sniffs provided on https://www.mediafire.com/file/0avyiccqzh2zo4h/classic_combined_sniff_db_31727_to_36935_kittnz_mantislord_brotalnia.rar/file

### Steps to reproduce the problem

Go to any of those creatures and check with .npc info that they lack auras.
Can check on keira3 for more ease.

### Extra Notes

I took the info from the sniffs with a grain of salt so im not picking every data ive seen, but the ones i think should have no trouble debating.

### AC rev. hash/commit

AzerothCore rev. 7e782d41a89d 2021-09-05 19:18:13 +0200 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10

**Comment by Asthalor** [comment]
I used the commit https://github.com/vmangos/core/pull/1279/files to get some examples, and checked on the source sniff and in our database to check that they were truly missing on our end.

I checked some of the data there but some were Classic only, so we could add another part if this is correct to fix the rest of creatures that they saw.

**Comment by Kitzunu** [comment]
Many creatures lack auras. And/or have some flags in DB instead of Auras.

There are plenty of commits in TC that coreects this.

Nice issue :)

**Comment by vtihomirov** [comment]
Here a video source from TBC Classic of the Bleakheart satyrs: https://www.youtube.com/watch?v=ikl1eG59Dx0
