### ISSUE TITLE
Unique loot roll and despawn bug

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#7896]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1730

In a Maraudon Pristine water run, https://classic.wowhead.com/item=17780/blade-of-eternal-darkness  dropped from the last boss https://classic.wowhead.com/npc=12201/princess-theradras
Two people rolled for the item, one of them won but they already had a copy of the same dagger. As a result of the dagger being unique, they were not able to loot the item. The rest of the party was never able to see or loot the item from the boss. The boss remained on the ground with the loot stuck in it until it eventually despawned with no one in the party ever able to see or loot the item. 

Testers note:
![image](https://user-images.githubusercontent.com/53914190/133460945-9b32ff3c-4bef-4f1e-8d7c-b7fa0c604233.png)

### Expected Blizzlike Behaviour

There are two irregularities here. First is that people who have a copy of the unique item drop should not be able to roll need on the mentioned item. So if a person owns the mentioned unique dagger, they should not be able to roll for it. There is a big difference between "unique" and "unique-equipped". You can own several copies of unique-equipped items, and if they are BoE even trade them. But "unique" items you can only own 1 copy regardless of what you do, even if you place it in bank you should not be able to roll on the item. This is bug nr1. The second issue is that regardless if they won the roll or not, if the person who won the roll leaves the group, or after a certain amount of time passes, before the boss despawns it should be available for the remaining players to loot the item.

Many comments under this thread will make it clear that if you own a unique item, you can't roll for it been in the game since classic. https://us.forums.blizzard.com/en/wow/t/classic-loot-bug-ninja-looter/374479

### Source

![Screenshot_52](https://user-images.githubusercontent.com/90768734/133430202-eee3f161-eef0-4e8d-bd49-fb0d615aa43c.png)
![unknown-2](https://user-images.githubusercontent.com/90768734/133430223-8e9bed9e-83ec-4ea4-a9fe-1bf78688103c.png)
![unknown](https://user-images.githubusercontent.com/90768734/133430232-51cd8088-b177-4cbf-9e59-9e0e2ec167d2.png)

### Steps to reproduce the problem

Steps to reproduce:
1) Kill Maraudon Princess and have unique dagger drop
2) 2 people tries to roll for it, one with the unique dagger already on them, and one without. (they should not be able to roll in the first place)
3) One of them (the one who already has the dagger) wins the need roll 
4) Tries to loot the item to trade, but is not able to
5) Wait until corpse despawns and check with the other characters in the party that you are never able to see or loot the boss until the moment of despawn 

### Extra Notes

Unique item owners should not be able to roll on items they already own. Unique is not the same as unique-equipped items and should be treated differently. 

Even if someone wins a roll, the boss should be available to be looted by the entire party before it de-spawns in the event of someone leaving.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
"The second issue is that regardless if they won the roll or not, if the person who won the roll leaves the group, or after a certain amount of time passes, before the boss despawns it should be available for the remaining players to loot the item."
Would you have any source for this?

I believe the other part should be decently easy to fix, I'll have a look during the week.

**Comment by jamadaha** [comment]
Hmmm... no, I do not have a source for that. I believe that's but one possible solution, proposed by the original issue writer, more so than the factual solution.
