### ISSUE TITLE
[Quest Bug] - Giant Softshell Clam Unlootable

### ISSUE THREAD

**Issue by scott-grimes** [azerothcore/azerothcore-wotlk#7907]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

While completing [Clam Bait](https://wowgaming.altervista.org/aowow/?quest=6142) none of the [Giant Softshell Clam](https://wowgaming.altervista.org/aowow/?object=177784) are lootable. They do correctly get the sparkle animation while you have the quest, but are not click-able. 

### Expected Blizzlike Behaviour

[Giant Softshell Clam](https://wowgaming.altervista.org/aowow/?object=177784) should be clickable and drop [Soft-Shelled Clam](https://wowgaming.altervista.org/aowow/?item=15874)

### Steps to reproduce the problem

1. .quest add 6142. 
2. .go o 31973 (maybe 177784, unclear which item is the object id, see screenshot)
3. Attempt to loot any sparkly giant clam in the area

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft
Originally reported https://github.com/chromiecraft/chromiecraft/issues/1746

### Screenshot
![pic1](https://user-images.githubusercontent.com/6396416/133536427-8c444d0a-040a-44b9-9460-247e84b0a259.jpg)
![pic2](https://user-images.githubusercontent.com/6396416/133536429-7e46d59f-71af-4d7a-899e-f36b7006cf78.jpeg)

**Comment by jamadaha** [comment]
Why did you open this as an issue on both AzerothCore and ChromieCraft?

**Comment by syssneck** [comment]
Thanks for the report! I close this one, as we have two issues now. We continue in https://github.com/azerothcore/azerothcore-wotlk/issues/7908

**Comment by scott-grimes** [comment]
@jamadaha was working down the instructions on https://www.azerothcore.org/wiki/guide-to-triaging , step 7 was to copy and backlink issue from CC. Lmk if further issues can just be raised directly here! I was not able to apply tags, presumably because of permissions settings. Thanks for reviewing!

**Comment by jamadaha** [comment]
@scott-grimes You are welcome to post directly on the AC issues, if you test it on a local instance of AC. CC issues are for issues not yet found/reproduced on a local AC.
There is really no reason to post on CC, if you could post on AC (Assuming you have tested it on local AC) In that sense triaging your own bugs, makes no sense, as you would have to test them on a local instance of AC anyway.
