### ISSUE TITLE
Quest/Crushing the Crown

### ISSUE THREAD

**Issue by pak3935** [azerothcore/azerothcore-wotlk#791]
Crushing the Crown
**Description**:

**Current behaviour**: Snagglebolt's Khorium Bomb does not work. Writes: It is not yet possible

**Expected behaviour**: Snagglebolt's Khorium The bomb must blow up the cart

**Steps to reproduce the problem**:

1. 
2. 
3.

**Comment by Motorheadx** [comment]
Replace if (m_CastItem) with if (m_CastItem && m_spellInfo-> Id! = 71024) in Spell.cpp try it but it's not very good
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L3415

**Comment by ShinDarth** [comment]
Please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/fbbc70e3187f0f6f5b9ff36e1aff613923ea69e4
