### ISSUE TITLE
Elwynn Forest Longsnout

### ISSUE THREAD

**Issue by Cold-Martijn** [azerothcore/azerothcore-wotlk#7917]
### Current Behaviour

Missing NPC in Elwynn Forest https://classic.wowhead.com/npc=119/longsnout

### Expected Blizzlike Behaviour

 NPC in Elwynn Forest https://classic.wowhead.com/npc=119/longsnout

### Source

 https://classic.wowhead.com/npc=119/longsnout

### Steps to reproduce the problem

select*from creature where id = 119
returns empty table, this NPC does not exist

### AC rev. hash/commit

444383a58543

### Operating system

win10

**Comment by patou01** [comment]
Both 
```
SELECT * FROM `creature_template` WHERE (`name` LIKE '%longsnout%') LIMIT 50
```

```
SELECT * FROM `creature_template` WHERE (id = 119) LIMIT 50
```

seem to have a return value. It seems he has no spawns and patrol (or should he wander?) however.

**Comment by Cold-Martijn** [comment]
> Both
> 
> ```
> SELECT * FROM `creature_template` WHERE (`name` LIKE '%longsnout%') LIMIT 50
> ```
> 
> ```
> SELECT * FROM `creature_template` WHERE (id = 119) LIMIT 50
> ```
> 
> seem to have a return value. It seems he has no spawns and patrol (or should he wander?) however.

Should have movementtype = 1 (wandering) and a couple of spawns. I just do not know yet how to spawn NPC's and set them to a proper spawnpoint with an SQL. I do know how to spawn do it ingame, but idk if thats any usefull.

**Comment by patou01** [comment]
I don't know if you're interested in making the PR yourself. If so, you should be able to use Keira3 (look on the wiki) to get the sql request.

You would open the creature section, search for longsnout, then you open his spawns and add whatever should be done. After that you copy the lines at the top of the window and that's basically the sql request for the PR.

Alternatively, if you know the number of positions and positions, I can see if I'm able to make the PR :)

**Comment by Ragelezz** [comment]
He had no spawns, done that.
