### ISSUE TITLE
Various NPCs Incorrectly Dropping Plaguebloom

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7925]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1742

Plaguebloom drops from 123 mobs (99 non-elementals)

Tester: confirmed. Queries below.

<details>
<summary>List of NPCs</summary>

---
| entry | name | maxlevel | chance | 
| ---: | --- | ---: | ---: | 
| 1783 | Skeletal Flayer | 51 | 0.02 | 
| 1784 | Skeletal Sorcerer | 52 | 0.02 | 
| 1785 | Skeletal Terror | 54 | 0.02 | 
| 1791 | Slavering Ghoul | 52 | 0.02 | 
| 1793 | Rotting Ghoul | 55 | 0.02 | 
| 1796 | Freezing Ghoul | 56 | 0.04 | 
| 1802 | Hungering Wraith | 58 | 0.02 | 
| 1804 | Wailing Death | 57 | 0.02 | 
| 1806 | Vile Slime | 55 | 0.02 | 
| 1812 | Rotting Behemoth | 56 | 0.02 | 
| 1813 | Decaying Horror | 57 | 0.42 | 
| 1816 | Diseased Grizzly | 56 | 0.08 | 
| 1821 | Carrion Lurker | 53 | 0.02 | 
| 1822 | Venom Mist Lurker | 51 | 0.02 | 
| 1824 | Plague Lurker | 55 | 0.08 | 
| 1833 | Scarlet Knight | 55 | 0.02 | 
| 1884 | Scarlet Lumberjack | 56 | 0.02 | 
| 4472 | Haunting Vision | 58 | 0.02 | 
| 4474 | Rotting Cadaver | 54 | 0.04 | 
| 4475 | Blighted Zombie | 53 | 0.02 | 
| 7086 | Cursed Ooze | 50 | 0.1 | 
| 7092 | Tainted Ooze | 52 | 0.02 | 
| 7098 | Ironbeak Screecher | 53 | 0.02 | 
| 7099 | Ironbeak Hunter | 51 | 0.02 | 
| 7100 | Warpwood Moss Flayer | 53 | 0.02 | 
| 7101 | Warpwood Shredder | 54 | 0.02 | 
| 7104 | Dessecus | 56 | 0.42 | 
| 7105 | Jadefire Satyr | 49 | 0.04 | 
| 7106 | Jadefire Rogue | 51 | 0.02 | 
| 7107 | Jadefire Trickster | 53 | 0.02 | 
| 7108 | Jadefire Betrayer | 53 | 0.02 | 
| 7109 | Jadefire Felsworn | 51 | 0.02 | 
| 7110 | Jadefire Shadowstalker | 52 | 0.02 | 
| 7111 | Jadefire Hellcaller | 54 | 0.02 | 
| 7112 | Jaedenar Cultist | 52 | 0.02 | 
| 7113 | Jaedenar Guardian | 51 | 0.02 | 
| 7132 | Toxic Horror | 54 | 0.02 | 
| 7135 | Infernal Bodyguard | 54 | 0.12 | 
| 7136 | Infernal Sentry | 53 | 0.04 | 
| 7137 | Immolatus | 56 | 0.34 | 
| 7138 | Irontree Wanderer | 53 | 0.02 | 
| 7139 | Irontree Stomper | 53 | 0.02 | 
| 7149 | Withered Protector | 56 | 0.14 | 
| 7153 | Deadwood Warrior | 49 | 0.02 | 
| 7154 | Deadwood Gardener | 49 | 0.02 | 
| 7155 | Deadwood Pathfinder | 50 | 0.02 | 
| 7156 | Deadwood Den Watcher | 54 | 0.02 | 
| 7157 | Deadwood Avenger | 55 | 0.02 | 
| 7158 | Deadwood Shaman | 54 | 0.02 | 
| 8519 | Blighted Surge | 54 | 0.02 | 
| 8520 | Plague Ravager | 56 | 0.02 | 
| 8521 | Blighted Horror | 57 | 0.02 | 
| 8523 | Scourge Soldier | 54 | 0.02 | 
| 8524 | Cursed Mage | 55 | 0.02 | 
| 8525 | Scourge Warder | 56 | 0.02 | 
| 8527 | Scourge Guard | 58 | 0.02 | 
| 8528 | Dread Weaver | 59 | 0.02 | 
| 8529 | Scourge Champion | 60 | 0.02 | 
| 8530 | Cannibal Ghoul | 55 | 0.02 | 
| 8532 | Diseased Flayer | 59 | 0.02 | 
| 8534 | Putrid Gargoyle | 56 | 0.1 | 
| 8535 | Putrid Shrieker | 58 | 0.22 | 
| 8539 | Eyeless Watcher | 58 | 0.04 | 
| 8540 | Torn Screamer | 55 | 0.02 | 
| 8541 | Hate Shrieker | 57 | 0.02 | 
| 8542 | Death Singer | 59 | 0.02 | 
| 8543 | Stitched Horror | 58 | 0.02 | 
| 8545 | Stitched Golem | 60 | 0.02 | 
| 8546 | Dark Adept | 59 | 0.02 | 
| 8550 | Shadowmage | 60 | 0.02 | 
| 8555 | Crypt Stalker | 54 | 0.06 | 
| 8556 | Crypt Walker | 56 | 0.12 | 
| 8557 | Crypt Horror | 58 | 0.32 | 
| 8558 | Crypt Slayer | 59 | 0.02 | 
| 8560 | Mossflayer Scout | 58 | 0.04 | 
| 8561 | Mossflayer Shadowhunter | 59 | 0.02 | 
| 8562 | Mossflayer Cannibal | 59 | 0.02 | 
| 8596 | Plaguehound Runt | 54 | 0.04 | 
| 8597 | Plaguehound | 56 | 0.06 | 
| 8598 | Frenzied Plaguehound | 58 | 0.08 | 
| 8600 | Plaguebat | 55 | 0.04 | 
| 8601 | Noxious Plaguebat | 56 | 0.08 | 
| 8602 | Monstrous Plaguebat | 58 | 0.1 | 
| 8603 | Carrion Grub | 55 | 0.04 | 
| 8605 | Carrion Devourer | 57 | 0.04 | 
| 8956 | Angerclaw Bear | 48 | 0.06 | 
| 8957 | Angerclaw Grizzly | 52 | 0.08 | 
| 8958 | Angerclaw Mauler | 50 | 0.08 | 
| 8959 | Felpaw Wolf | 48 | 0.04 | 
| 8960 | Felpaw Scavenger | 50 | 0.06 | 
| 8961 | Felpaw Ravager | 52 | 0.02 | 
| 9447 | Scarlet Warder | 54 | 0.02 | 
| 9878 | Entropic Beast | 52 | 0.1 | 
| 9879 | Entropic Horror | 54 | 0.07 | 
| 10580 | Fetid Zombie | 56 | 0.03 | 
| 10605 | Scarlet Medic | 54 | 0.02 | 
| 10801 | Jabbering Ghoul | 54 | 0.04 | 
| 10816 | Wandering Skeleton | 55 | 0.04 | 
| 10817 | Duggan Wildhammer | 55 | 0.42 | 
| 10916 | Winterfall Runner | 57 | 0.02 | 
| 11076 | Cauldron Lord Razarch | 56 | 0.02 | 
| 11077 | Cauldron Lord Malvinious | 55 | 0.04 | 
| 11078 | Cauldron Lord Soulwrath | 58 | 0.06 | 
| 11291 | Unliving Mossflayer | 55 | 0.02 | 
| 11458 | Petrified Treant | 59 | 0.78 | 
| 11459 | Ironbark Protector | 59 | 0.94 | 
| 11461 | Warpwood Guardian | 58 | 0.94 | 
| 11465 | Warpwood Stomper | 58 | 0.78 | 
| 11897 | Duskwing | 60 | 0.08 | 
| 12250 | Zaeldarr the Outcast | 55 | 0.06 | 
| 12339 | Demetria | 61 | 0.54 | 
| 13021 | Warpwood Crusher | 56 | 0.74 | 
| 13118 | Crimson Bodyguard | 58 | 0.36 | 
| 13196 | Phase Lasher | 55 | 0.86 | 
| 13197 | Fel Lash | 56 | 0.72 | 
| 13279 | Discordant Surge | 58 | 0.02 | 
| 13285 | Death Lash | 58 | 0.88 | 
| 14303 | Petrified Guardian | 59 | 0.42 | 
| 14340 | Alshirr Banebreath | 54 | 0.12 | 
| 16135 | Rayne | 60 | 5.4 | 
| 16141 | Ghoul Berserker | 60 | 0.02 | 
| 16298 | Spectral Soldier | 60 | 0.02 | 
| 16299 | Skeletal Shocktrooper | 60 | 0.02 | 

</details>

### Expected Blizzlike Behaviour

Plaguebloom should not drop from mob (especially non-elemental ones)

"Plaguebloom can be found in the Eastern Plaguelands, Felwood and the Western Plaguelands. Requires 285 Herbalism to gather."

"Plaguebloom only grows in three zones: Eastern Plaguelands, Western Plaguelands and Felwood, ...[]... Plaguebloom requires a skill level of 285 in Herbalism in order to pick it."

### Source

https://tbc.wowhead.com/item=13466/plaguebloom#dropped-by
https://wowwiki-archive.fandom.com/wiki/Sorrowmoss?oldid=2343674 (note Sorrowmoss is the post-Cata name for Plaguebloom. It's a 2010 article, but uses the modern name.)
https://classicguides.org/plaguebloom-farming-routes-classic/

### Steps to reproduce the problem

```SQL
SELECT ct.entry, ct.name, ct.maxlevel, clt.chance
FROM `creature_template` ct
JOIN `creature_loot_template` clt ON ct.lootid = clt.Entry
WHERE clt.Item = 13466
```

Non elementals:

```SQL
SELECT ct.entry, ct.name, ct.maxlevel, clt.chance
FROM `creature_template` ct
JOIN `creature_loot_template` clt ON ct.lootid = clt.Entry
WHERE clt.Item = 13466
AND ct.`type` <> 4
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
These mobs seem to have a bunch of shit dropping from them. Since you have the query already, are you making the fixes ?
![image](https://user-images.githubusercontent.com/2592673/133663745-618bb03a-c03f-4b6c-8d68-ac4a827e3154.png)
![image](https://user-images.githubusercontent.com/2592673/133664021-f79e1555-cad4-42af-83fe-dc39edbbb031.png)
As well as mountain silversage (13465)
Else I can spend some time this week-end cleaning it up, but I feel that this could be adressed in a decently broad fashion on the DB, since the "loot with herbalism" that implements a possibility to get plants is on a different table?

**Comment by Azcobu** [comment]
Yep, happy to make the fixes. However, for at least some of the low-level herbs like Earthroot/Liferoot/Fadeleaf, Wowhead does show many NPCs dropping them (128 for Earthroot, 94 for Liferoot, 41 for Fadeleaf) so I'd be a lot more cautious about removing those from drop tables. The high level herbs like Plaguebloom, Black Lotus and Icecap have no or very few correct drops, so they're much easier to deal with. And you're correct, the NPC herbalism/harvesting of dead nature mobs is handled through the skinning loot template table I believe.
