### ISSUE TITLE
The mod-reward-system may be invalid.

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#793]
The mod-reward-system may be invalid.

**Comment by Rochet2** [comment]
I attempted to fix all issues here: https://github.com/azerothcore/mod-reward-system/pull/3
One of those issues match what you are having? Or do you have a different kind of issue.

**Comment by talamortis** [comment]
repull from my fork :) i did a update on it

**Comment by talamortis** [comment]
https://github.com/talamortis/reward-system
