### ISSUE TITLE
[Raid/Ulduar] Thorim Summon Creature's count shuld diffrent at 10Man mode and 25Man mode

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#7931]
### Current Behaviour

Boss Thorim in 10Man mode will SpawnArenaNPC 7+2 creature every  few seconds after the arena channal door to Thorim is opened

### Expected Blizzlike Behaviour

Only in 25Man mod should SpawnArenaNPC 7+2 creature;
In 10Man Mod should SpawnArenaNPC 4+1 creature;

### Steps to reproduce the problem

1. go c id 32865
2. clear all creatures in arena
3. open the door
4. wait and count creature's jumped into arena from top

### AC rev. hash/commit

ce4fad930f4b+

### Operating system

Ubuntu 20.04

**Comment by Si1ker** [comment]
![image](https://user-images.githubusercontent.com/61223313/133703245-64404956-b4e4-418b-950c-4b7f9bc943c9.png)
sad.

**Comment by elthehablo** [comment]
Closed but no PR linked? Was this ever a good issue then?
