### ISSUE TITLE
quest 24652 Crushing the Crown, Horde Side Doesn't work 

### ISSUE THREAD

**Issue by LKArthas** [azerothcore/azerothcore-wotlk#794]
**Description**:
The quest 24652 Crushing the Crown Can't Be completed

**Current behaviour**: Tell us what happens
item=50130 Doesn't allow to use the spell when you manually do .cast 71024 the spell works perfectly and the credit works, possible wrong conditions for the use of the item
**Expected behaviour**: Tell us what should happen instead
When click on the item should cast the spell and complete the quest
**Steps to reproduce the problem**:

1. With an horde player do a .quest add 24652 
2. Go to crystalsong forest on Event Love is in the air
3. Go near Chemical Wagons there and try to use the item

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Middel** [comment]
first of all try filling out the entire template when reporting issues.
its not really clear what revision / commit you are using.

eitherway. talamortis has pushed a commit 3 days ago regarding that quest. if you havent gotten it yet, you should probably pull the latest AZCore updates.

https://github.com/azerothcore/azerothcore-wotlk/commit/fbbc70e3187f0f6f5b9ff36e1aff613923ea69e4

**Comment by talamortis** [comment]
Tested and fixed will close since this issue has already been completed.

**Comment by Motorheadx** [comment]
Horde or Alliance it does not matter ID the spell the same
