### ISSUE TITLE
vmap4assembler.exe does not work on Win10

### ISSUE THREAD

**Issue by stoudtlr** [azerothcore/azerothcore-wotlk#7940]
### Current Behaviour

When running vmap4assembler it gets to the below point and then stops.
![image](https://user-images.githubusercontent.com/36058236/133805898-83ed7d86-b358-408c-968a-733d9d4db56a.png)

No errors are given as seen in screenshot, it just stops processing any more files.  vmaps folder size is only 166mb as a result.

### Expected Blizzlike Behaviour

vmap4assembler should continue running until all files have been processed resulting in a folder size of ~627mb

### Source

compare vmaps data from the data.zip file on the wiki to vmaps data you get when extracting on your own to see the difference.

### Steps to reproduce the problem

1. Build on Windows
2. run vmap4extractor.exe to generate Buildings folder
3.  run "vmap4assembler.exe Buildings vmaps" to create vmaps
4. console output will match screenshot above showing assembler stops before it's finished

### Extra Notes

I do not know how long this has been broken as I usually use the data.zip from the website instead of extracting files on my own.

### AC rev. hash/commit

606ea325a

### Operating system

Windows 10 x64

### Custom changes or Modules

None

**Comment by stoudtlr** [comment]
@Kitzunu what exactly are your results since you also mentioned issues with the extractors? I ran the vmaps one half a dozen times and always got the results I showed above.  I rebooted my PC before running some errands and tried again now that I'm back and getting something different now.

The vmap assembler completed successfully a couple times:
![image](https://user-images.githubusercontent.com/36058236/133830852-fd31ec6a-794e-4a52-9196-66b56ce445e0.png)

In-between the two successful ones I had a couple that failed, but at a different place than I was originally seeing:
![image](https://user-images.githubusercontent.com/36058236/133831622-eebf8e0e-8d4a-4ecc-a066-3e4260d180bd.png)

This issue is weird since it seems to sometimes work and sometimes doesn't. Makes it hard to troubleshoot as well since there aren't any error messages when it fails.

**Comment by T1ti** [comment]
I never had issues with it

**Comment by FrancescoBorzi** [comment]
can anyone else reproduce this issue?

**Comment by Kitzunu** [comment]
Perhaps I have mistaken myself, the extractors provided with TOOLS works. It's if you try to compile with MESHEXTRACTORS the build fails

**Comment by stoudtlr** [comment]
Why was this reopened if I'm the only one seeing this issue? Probably just a config issue on my end.

**Comment by Nyeriah** [comment]
@stoudtlr We are sorry, after an unexpected turn of events, a lot of issues were closed without reason so we had to reopen them manually one by one. It seems yours was reopened by mistake, but seeing how you believe it's just an issue on your end I'll go ahead and close it again. Thanks!

**Comment by stoudtlr** [comment]
No worries. I've been away from the AC repo and github for a few weeks so I missed all the drama.  Keep up the good work!
