### ISSUE TITLE
Feature: Ignore account wide

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/azerothcore-wotlk#7947]
### Describe your feature request or suggestion in detail

Based on latest Blizzard changes, latest PTR patch allows that when players ignores other character, this will be applied to all the acount. This will be a very nice feature for WotLK, considering that actual behaviour only applies per character.

### Additional context

> User Interface and Accessibility
>
>    Improved Chat Reporting Feedback
>        /ignore now blocks all characters on the ignored player’s WoW account.

[Source](https://us.forums.blizzard.com/en/wow/t/ptr-915-development-notes/1082616/12)

**Comment by UltraNix** [comment]
It's completely clientside and not supported by Wotlk client.
