### ISSUE TITLE
Twilight Disciple and Twilight Thug are silent

### ISSUE THREAD

**Issue by vtihomirov** [azerothcore/azerothcore-wotlk#7963]
### Current Behaviour

Twilight Disciple and Twilight Thug don't speak any text.

### Expected Blizzlike Behaviour

Twilight Disciple and Twilight Thug should have a big chance of saying a text line when engaged in combat and on defeat.

### Source

https://www.youtube.com/watch?v=RhDWu085COI

### Steps to reproduce the problem

1. `.go creature id 2338`
2. Start a fight with any of the Twilight mobs there.
3. Check if any of them are speaking anything.

### AC rev. hash/commit

606ea325a2ea

### Operating system

Arch Linux

**Comment by Ragelezz** [comment]
I can confirm and reproduce the issue.
