### ISSUE TITLE
Bash scripts are not runnable (chmod +x)

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#797]
**Description**:
The scripts can't be run (like db_assembler)

**How to fix:**
chmod +x db_assembler
chmod +x db_export
etc

I tried to do it and push the fix, but I don't know why, it doesn't change on my local computer.

**Branch(es)**: master

**AC hash/commit**:  426fa5bc60bd3d64a82ceb6cc6dc5bb37b0353f7

**Operating system**:  debian and ubuntu

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by ShinDarth** [comment]
what is exactly the error that you get?

**Comment by BarbzYHOOL** [comment]
No error, it's just that if you try to run the script alone it doesn't start on my debian because it requires the +x bit set with chmod and newbies won't know that

**Comment by luisforte** [comment]
It is why i always use Ubuntu and Sudo user trough my ssh key              xD

**Comment by BarbzYHOOL** [comment]
Makes no sense, it's not related.

**Comment by Deku** [comment]
I don't have this issue. Used the db_assembler script on Ubuntu Server 16.04 without problems.

**Comment by BarbzYHOOL** [comment]
once you chmod it, it obviously doesn't need to change the permission again
Now i'm speaking of the db_assembler since the whole directory rework etc... Before that I had no problem

**Comment by BarbzYHOOL** [comment]
Is it possible that it's because of my git config set to ignore permission changes? :D

**Comment by BarbzYHOOL** [comment]
Yes, I think it's because I've put my config to filemode = false
