### ISSUE TITLE
guild event displays the wrong date of it when it was made 

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#7977]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1792

small bug but when i create a guild event it always displays the wrong date, it always says it was made jan 1s 2000 at midnight which is impossible since wow itself was not even a thing back then 
![WoWScrnShot_091221_091421](https://user-images.githubusercontent.com/85977970/133910199-dbcce087-5323-4819-aedc-84ce40b550fa.jpg)

### Expected Blizzlike Behaviour

the guild event displays the right date of when it was created

### Steps to reproduce the problem

1. create a guild event 
2. check to see when you made it
3. it will display jan 1s 2000 at midnight

### Extra Notes

none

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
It's not the creation date that is displayed wrong, it's just the "invite response date"

Whenever the invite status is updated, the time when it was last updated changes, but currently it does not, defaulting at that date back in 2000s.

I don't know what date should it be displaying by default, I really doubt we'll ever find that kind of information though, at least not any time soon. It's too trivial to have any kind of reference at most knowledge databases I assume.
