### ISSUE TITLE
undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by Stabatha** [azerothcore/azerothcore-wotlk#798]
**Description**: Receiving compile errors with Ubuntu 16.04

**Current behaviour**: While compiling you receive the error below

[ 39%] Linking CXX executable authserver
/usr/bin/ld: /usr/local/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/server/authserver/CMakeFiles/authserver.dir/build.make:229: recipe for target 'src/server/authserver/authserver' failed
make[2]: *** [src/server/authserver/authserver] Error 1
CMakeFiles/Makefile2:991: recipe for target 'src/server/authserver/CMakeFiles/authserver.dir/all' failed
make[1]: *** [src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Expected behaviour**:  make should complete compile

**Steps to reproduce the problem**:

1.  running the make command

**Branch(es)**:  Master branch

**AC hash/commit**:  426fa5bc60bd3d64a82ceb6cc6dc5bb37b0353f7

**Operating system**:  Ubuntu 16.04
openssl version: OpenSSL 1.0.2g 1 Mar 2016
cmake --version: cmake version 3.5.1
g++ --version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

**Modules**:  none

**Other Customizations**: none

**Comment by talamortis** [comment]
if you are using linux please use the install.sh file included.

**Comment by Re3os** [comment]
@Stabatha update OpenSSL to 1.1.0f

**Comment by ShinDarth** [comment]
feel free to reopen this if the problem persists

**Comment by innobankServer** [comment]
receive err yet with:
[ 96%] Linking C executable wifidatagather
/usr/bin/ld: /usr/local/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

any solution except update openssl to laster version? my SDK use openssl 1.0.2g, so need help, 3ks

**Comment by sdsjServer** [comment]
> **Description**: Receiving compile errors with Ubuntu 16.04
> 
> **Current behaviour**: While compiling you receive the error below
> 
> [ 39%] Linking CXX executable authserver
> /usr/bin/ld: /usr/local/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> src/server/authserver/CMakeFiles/authserver.dir/build.make:229: recipe for target 'src/server/authserver/authserver' failed
> make[2]: *** [src/server/authserver/authserver] Error 1
> CMakeFiles/Makefile2:991: recipe for target 'src/server/authserver/CMakeFiles/authserver.dir/all' failed
> make[1]: *** [src/server/authserver/CMakeFiles/authserver.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> **Expected behaviour**: make should complete compile
> 
> **Steps to reproduce the problem**:
> 
> 1. running the make command
> 
> **Branch(es)**: Master branch
> 
> **AC hash/commit**: [426fa5b](https://github.com/azerothcore/azerothcore-wotlk/commit/426fa5bc60bd3d64a82ceb6cc6dc5bb37b0353f7)
> 
> **Operating system**: Ubuntu 16.04
> openssl version: OpenSSL 1.0.2g 1 Mar 2016
> cmake --version: cmake version 3.5.1
> g++ --version: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
> 
> **Modules**: none
> 
> **Other Customizations**: none

hi, issue solved now? need your help,3ks
