### ISSUE TITLE
Unable to Unlearn Tribal Leatherworking

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7987]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1774

I found no way unlearning Tribal Leatherworking. The tribal trainer only gives me recipes and the Gnome north of Steamweadle has the "soothsaying" book, but this only displays some text but no option to actually unlearn the tribal spec. (Still showing as Tribal LW in my spell book) Now I visited the other 2 specialization trainers and all normal LW trainers for horde and no option to unlearn. Only unlearning the whole profession in the "C" menu is possible but I want to avoid that at 265 skill.

Tester: confirmed. Learned Tribal LW and talked to the tribal trainer for Horde, Se'Jib, and he only wants to teach recipes and doesn't have a gossip option to pay a fee to unlearn TLW. 
![WoWScrnShot_091921_210804](https://user-images.githubusercontent.com/81782124/133926429-bca5cdb7-709a-4c7b-82cc-5160896ee576.jpg)

Also visited the "Soothsaying For Dummies" book, but that doesn't give any options either:
![WoWScrnShot_091921_210837](https://user-images.githubusercontent.com/81782124/133926437-09d36721-c3e1-4291-8588-572f3180b5b3.jpg)

### Expected Blizzlike Behaviour

There is a bit of confusion in the sources because before patch 2.13, you had to totally unlearn the profession, train up to 225 again and could then re-choose a specialty. After 2.13 the system was changed so that you could pay a fee to the trainer who had originally taught you, as described here:
![lwspec2](https://user-images.githubusercontent.com/81782124/133926574-5c4a3d83-e5dd-44c1-8be7-b537ecf4ad5b.PNG) ([source](https://wowwiki-archive.fandom.com/wiki/Leatherworking?oldid=2389532))

![lwspec](https://user-images.githubusercontent.com/81782124/133926345-6131b876-badd-4245-a7bb-9cb225917d4b.PNG) ([source](https://www.wow-professions.com/tbc/leatherworking-specializations-tbc-classic#changing))

Specifically, Se'jib should have a gossip menu with a greeting of "How you doin' mon?" and two options, "I would like to train" and "I wish to unlearn Tribal Leatherworking!"

### Source

["How to change Leatherworking Specializations in TBC Classic | WoW TBC Leatherworking Guides"](https://youtu.be/yozQJdqJI3g?t=58) - video of someone demonstrating on TBC Classic retail
https://wowwiki-archive.fandom.com/wiki/Leatherworking?oldid=2389532
https://www.wow-professions.com/tbc/leatherworking-specializations-tbc-classic#changing
https://tbc.wowhead.com/quest=5148/tribal-leatherworking#comments
https://tbc.wowhead.com/npc=7871/sejib

### Steps to reproduce the problem

1. Get Leatherworking to at least 225 (.setskill 165 225) or even higher.
2. Go to Se'jib - .go c 540
3. Accept the Tribal Leatherworking quest from him.
4. .additem [Wild Leather Vest]
5. .additem [Wild Leather Helmet]
6. Hand in. 
7. Now decide Tribal Leatherworking is not for you and try to talk to him again.
8. You can also visit "Soothsaying For Dummies" for all the good it will do, .go o 17316

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

win 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Cynthetik** [comment]
This is happening on the alliance side as well.
