### ISSUE TITLE
Brewfest Vendor Selling Multiple "Brew of the Month" Forms

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#7998]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1801

NPC Blix Fixwidget, token redeemer on Brewfest sells 3 of "same" Club membership forms, so maybe there is difference between them, closer look is needed.

![WoWScrnShot_092021_072146](https://user-images.githubusercontent.com/80590226/133960830-1a7ecb8b-4498-4fd0-aba5-550d1c93ad3d.jpg)

Tester: confirmed.

![WoWScrnShot_092021_230119](https://user-images.githubusercontent.com/81782124/134011519-02ebb3d6-5666-464c-b3b0-90cc3f480441.jpg)

Looking at the DB, he is selling:
- 1 x item [37599](https://tbc.wowhead.com/item=37599/brew-of-the-month-club-membership-form), leading to quest [12306](https://tbc.wowhead.com/quest=12306/brew-of-the-month-club)
- and 2 x item [37737](https://tbc.wowhead.com/item=37737/brew-of-the-month-club-membership-form), leading to quest 12421, which doesn't have a Wowhead link as it's apparently removed or deprecated.

### Expected Blizzlike Behaviour

The vendor should only sell a single BotM form.

### Source

https://wowpedia.fandom.com/wiki/Blix_Fixwidget?oldid=2340984 - Wrath-era inventory for this vendor shows only one BotM form for sale.
https://wowpedia.fandom.com/wiki/%22Brew_of_the_Month%22_Club_Membership_Form is same, and he sells only one of those.

### Steps to reproduce the problem

1. .go c 152120
2. Talk to NPC 
3. He is selling 3 of same items.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Yehonal** [comment]
Check this out: https://github.com/azerothcore/azerothcore-wotlk/pull/8029#issuecomment-968670617
