### ISSUE TITLE
Venomtail Console error spam (Fix inside)

### ISSUE THREAD

**Issue by Middel** [azerothcore/azerothcore-wotlk#800]
**Description**:

Console Error Spam

**Current behaviour**:

The Console spam the following error ALOT

CreatureTextMgr: Could not find Text for Creature(Venomtail Scorpid) Entry 3127 in 'creature_text' table. Ignoring.

**Expected behaviour**: 

That error shouldn't show up, because in this case the Venomtail isn't supposed to speak. but the grunt attacking it is.

This is a Fix that works (has been tested and confirmed working by myself)

The fix is in the TXT file. including quotations and such.

UPDATE `smart_scripts` SET `action_param3`=1 WHERE `entryorguid`=3296 AND `source_type`=0 AND `id`=1;

[fix.txt](https://github.com/azerothcore/azerothcore-wotlk/files/1760434/fix.txt)

**Steps to reproduce the problem**:

1.  Start Server
2.  Behold Console spam
3. 

**Branch(es)**: Master 

**Operating system**:  Windows Server 2008

**Modules**:  Transmorg, Anti-Cheat, Individual XP

**Other Customizations**: no

**Comment by ShinDarth** [comment]
thanks for the issue report and for your fix, can you please [open a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) including your fix? so it can be tested & merged

**Comment by Middel** [comment]
@ShinDarth feel free to do it, i get hella confused reading that. my brain can't follow it.

**Comment by Middel** [comment]
after some further tests, it doesnt really fix anything. sorry for the troubles. i'll keep trying.
