### ISSUE TITLE
acore.sh client-data Doesn't Get v12 Data

### ISSUE THREAD

**Issue by chriswaterbury** [azerothcore/azerothcore-wotlk#8018]
### Current Behaviour

using acore.sh script to download client-data doesn't download v12

### Expected Blizzlike Behaviour

Should download v12 data

### Source

azerothcore-wotlk/apps/installer/includes/functions.sh
```
function inst_download_client_data {
    # change the following version when needed
    local VERSION=v11

    echo "#######################"
    echo "Client data downloader"
    echo "#######################"
```
VERSION should be updated to v12 do downloads latest data from https://github.com/wowgaming/client-data/releases/download/v12/data.zip

### Steps to reproduce the problem

1. Run acore.sh client-data
2. Attempt to run world server
3. Get map version error

### AC rev. hash/commit

51aac38f5993064a015e548b6968a7b973158aee

### Operating system

Ubuntu 20.04

### Custom changes or Modules

mod-autobalance
modified some boss scripts to support small group sizes

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/8000
