### ISSUE TITLE
The database connection failed!

### ISSUE THREAD

**Issue by ss958** [azerothcore/azerothcore-wotlk#802]
PrepareStatement(LOGIN_SEL_IP2NATION_COUNTRY, "SELECT c.country FROM ip2nationCountries c, ip2nation i WHERE i.ip < ? AND c.code = i.country ORDER BY i.ip DESC LIMIT 0,1", CONNECTION_SYNCH);

The new version of more than the above statement, I have been connected to the database has been wrong, excuse me, why is this?

**Comment by talamortis** [comment]
please apply all sql updates.
