### ISSUE TITLE
Wrong model for Captain Halyndor

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8032]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1813

Captain Halyndor model is a goblin pirate
![Captain Halyndor](https://user-images.githubusercontent.com/91145640/134252995-c78ade28-1237-483d-abad-3e522f804d8c.jpg)
.

### Expected Blizzlike Behaviour

The NPC's should an undead pirate.
![55276-captain-halyndor](https://user-images.githubusercontent.com/91145640/134253053-bf15253d-0e3a-456e-bb19-a4dc32e2fafd.jpg)

### Source

https://classic.wowhead.com/quest=290/lifting-the-curse
https://classic.wowhead.com/npc=1160/captain-halyndor

### Steps to reproduce the problem

1. NPC is located in Wetlands "15.6, 23.4" , in the deck of the sinking ship.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
So I pulled and built, he was undead. I rebuilt from scratch and he turned goblin. Yet neither should affect him since this would be DB related. 
When I .npc add temp 1160 I indeed spawn a gob. How would we find the right model to apply? He is listed as undead correctly, so I think it's purely the modelid that is wrong.

**Comment by zxcnxc** [comment]
> 
> 
> So I pulled and built, he was undead. I rebuilt from scratch and he turned goblin. Yet neither should affect him since this would be DB related.
> When I .npc add temp 1160 I indeed spawn a gob. How would we find the right model to apply? He is listed as undead correctly, so I think it's purely the modelid that is wrong.
> 
> As a funny note, it seems Truewow had this issue 5 years ago. https://truewow.org/forum/viewtopic.php?t=13005&start=150

it's happening to me right now, i thought change faction to '20' makes him to an undead, so i try and it's works but after restarting worldserver 2-3x, he turns back to goblin again. Weird

**Comment by Nyeriah** [comment]
> edit again:
> hmm, i thinks this one that makes this bug
> ![image](https://user-images.githubusercontent.com/44707108/134389994-ae97021d-2d95-47a6-8e1d-4f9d66601d4d.png)

DisplayID_Other_Gender is the issue, yeah. Same as that pirate in Deadmines, that also used to be an issue before.

**Comment by patou01** [comment]
Interesting, why would he spawn as different genders? Weird.

**Comment by Nyeriah** [comment]
> Interesting, why would he spawn as different genders? Weird.

Because having that value set is what defines whether creatures have gender variants or not, from that point onwards it operates just like any other creature, e.g random mobs, pirates, etc. that have gender variants.
