### ISSUE TITLE
Quest [Bark for the Barleybrews] triggers not working properly.

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#8035]
### Current Behaviour

![WoWScrnShot_092221_172610](https://user-images.githubusercontent.com/61194190/134384076-6e3927ce-6c5d-4625-bdf2-407875388177.jpg)

I screamed out like 10-20 times which is very spammy, and despite this my quest log wasn't marked as progressed.

### Expected Blizzlike Behaviour

1) If you reach the threshhold, it should mark it as complete.

2) No spam.

### Source

https://www.wowhead.com/quest=11293/bark-for-the-barleybrews

### Steps to reproduce the problem

Pickup quest.
Run to Ironforge and clip/miss the correct path.
Spam the speech by accident.
Don't progress.

### Extra Notes

pls can i have the brew of the month club as i can't afford to buy brew of the month as compensation for this report as i can't actually do the dailies to buy it

### AC rev. hash/commit

AzerothCore rev. 7e2e6f8ee85f+ 2021-09-13 14:16:29 +0000 (master branch) 

### Operating system

win10

### Custom changes or Modules

chromiecraft modules

**Comment by JamesGent** [comment]
Might be linked to being in a group?

**Comment by JamesGent** [comment]
Tested it more. The quest completion triggers don't go off if you're in a raid group. There's nothing about being in a raid that would help with this quest, but obviously mass-spamming the bark message 3-4 times per second would be detrimental to a public city like Ironforge.

**Comment by UltraNix** [comment]
That spam comes from being in raid as well. Just leave the raid.
