### ISSUE TITLE
Battle of Hillsbrad [part 7] incorrect quest tracker location

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#8061]
### Current Behaviour

Quest tracker says to 
"Return to Bragor Bloodfist at Lordamere Lake in Silverpine  Forest"

### Expected Blizzlike Behaviour

It should say 
"Take Darthalia's Sealed Commendation to Bragor Bloodfist in the Undercity" 

(as you have never been there before)

### Source

https://classic.wowhead.com/quest=550/battle-of-hillsbrad

### Steps to reproduce the problem

.quest add 550
see quest tracker for described problem

### Extra Notes

On chromiecraft

### AC rev. hash/commit

chromiecraft/azerothcore-wotlk@7e2e6f8

### Operating system

Ubuntu 20.04

### Custom changes or Modules

mod-ah-bot
mod-cfbg
mod-chromie-xp
mod-desertion-warnings
mod-duel-reset
mod-eluna-lua-engine
mod-ip-tracker
mod-low-level-arena
mod-multi-client-check
mod-pvp-titles
mod-pvpstats-announcer
mod-queue-list-cache
mod-server-auto-shutdown
lua-carbon-copy
lua-custom-worldboss
lua-level-up-reward
lua-recruit-a-friend
lua-send-and-bind
lua-temp-announcements
lua-zonecheck

**Comment by Ragelezz** [comment]
Already like that.

**Comment by Kitzunu** [comment]
why was this closed
