### ISSUE TITLE
worldserver.exe crash

### ISSUE THREAD

**Issue by ssdphp** [azerothcore/azerothcore-wotlk#8063]
### Current Behaviour

Crashlog see following link.
https://gist.github.com/ssdphp/4143e0c4fbd66651016be8d3283e763e

### Expected Blizzlike Behaviour

worldserver Shouldn't crash

### Source

Compile Server on RelWithDebInfo
Manage Database
Run auth and worldserver
![QQ图片20210924205404](https://user-images.githubusercontent.com/16387049/134677441-88afa73a-08f7-492a-ab02-6833ba12ee67.jpg)

### Steps to reproduce the problem

Sorry, I can’t get the error steps

### Extra Notes

After running for 10 hours, there are about 30 players

### AC rev. hash/commit

![QQ图片20210924205404](https://user-images.githubusercontent.com/16387049/134679473-3ff87432-f4be-41a2-b87b-8c808b1006ce.jpg)

### Operating system

Windows 10 x64

### Custom changes or Modules

Eluna module
mod-transmog module

**Comment by Kitzunu** [comment]
Closing as hash/commit has not been provided and stated as Unknown in the images.

To me looks like eluna error

**Comment by Winfidonarleyan** [comment]
Unk revision, ace... default
