### ISSUE TITLE
Guild creation trouble

### ISSUE THREAD

**Issue by wlasser** [azerothcore/azerothcore-wotlk#807]
Hello!
There is have some trouble with petition signs for guild creation.
When player try to sign petition - his sign is not accept.
First player name is showing in petition, but next time - is disappear.
And when you are send petition for a sign - there is no guild master name for player, who want to sign. And show for master of petition.

**Steps to reproduce the problem**:
1.  Get petition from guild creator NPC
2.  Try to get some signs from players

**Branch(es)**: master

**AC hash/commit**:  43498cc

**Operating system**:  Debian Jessie 8.1

**Modules**: 
custom-login
transmog
duel-reset
reward-system
VAS-autobalance
Solocraft
congrats-on-level

**Other Customizations**: 
portal master from Rochet2
azeroth-fly

**Comment by Sdyessdev** [comment]
I'm unable to reproduce that the guild master and guild name don't show up. It doesn't do that on windows, but this person is on Debian. I don't currently have time to setup a debian environment to test this, but if someone else does, let me know and I can probably fix that too.

**Comment by wlasser** [comment]
There is next:
Signed charter is now showing good - guild master name and signed character, but something still wrong and weird.
1) Master of petition get wrong signed character name
2) If you login on new character and try to sign it - that doesn;t work - This character is signed, but not signed - getting error (client side).
On screenshots showed what happens. And one more - character Люцифер, doesn;t sign this charter. 

![wowscrnshot_031118_103837](https://user-images.githubusercontent.com/1104525/37251416-55502e82-2518-11e8-88bf-e0e4e1111e1b.jpg)
![wowscrnshot_031118_103843](https://user-images.githubusercontent.com/1104525/37251417-5587f25e-2518-11e8-8c15-45a3649aadcb.jpg)
![wowscrnshot_031118_103902](https://user-images.githubusercontent.com/1104525/37251418-55b59d08-2518-11e8-83d0-ea21ee0cb815.jpg)

**Comment by Sdyessdev** [comment]
Just to check, each signature you are attempting is on a different account, right? Signatures are unique to an account, so 2 characters from the same account cannot sign it.

**Comment by wlasser** [comment]
Ok. There is next. With other account it work at half. When character is sign - all info go good. But on master of charter - showed wrong character.
![wowscrnshot_031118_105418](https://user-images.githubusercontent.com/1104525/37251528-7592fd30-251a-11e8-8165-ce93e7712309.jpg)
![wowscrnshot_031118_105425](https://user-images.githubusercontent.com/1104525/37251529-75c210ca-251a-11e8-9996-2acd404ea2d8.jpg)
