### ISSUE TITLE
build failing for HMAC_CTX_new deprecation

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#8083]
```
In file included from /Users/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/common/Cryptography/Authentication/AuthCrypt.cpp:10:
/Users/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/common/Cryptography/HMAC.h:39:45: fatal error: 'HMAC_CTX_new' is deprecated [-Wdeprecated-declarations]
        static HMAC_CTX* MakeCTX() { return HMAC_CTX_new(); }
                                            ^
/usr/local/opt/openssl/include/openssl/hmac.h:33:1: note: 'HMAC_CTX_new' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 HMAC_CTX *HMAC_CTX_new(void);
^
/usr/local/opt/openssl/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/local/opt/openssl/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
```

### Source
https://github.com/azerothcore/azerothcore-wotlk/pull/8081/checks?check_run_id=3707972579

### Steps to reproduce the problem

run the pipeline

### AC rev. hash/commit

any commit on master

### Operating system

the pipeline shows the deprecation for the Mac OS build

**Comment by Helias** [comment]
@Winfidonarleyan any clue?

**Comment by Winfidonarleyan** [comment]
Need use openssl 1.1, not 3.0

**Comment by Winfidonarleyan** [comment]
https://github.com/TrinityCore/TrinityCore/issues/21350#issuecomment-363150020

**Comment by Kitzunu** [comment]
3.0 not supported

**Comment by FrancescoBorzi** [comment]
> Need use openssl 1.1, not 3.0

> 3.0 not supported

this is a warning we are getting in version 1.1 because that thing WILL be deprecated in version 3.0

so this is not about "just don't use 3.0 yet", we need to address this deprecation so in future it will be easier to migrate to 3.0 when it's time

@UltraNix can you please have a look at this?

**Comment by UltraNix** [comment]
@Winfidonarleyan is right - you are using OpenSSL 3.0.

**Comment by Kitzunu** [comment]
> this is a warning we are getting in version 1.1 because that thing WILL be deprecated in version 3.0

Yes, but the warning does not fail the build. that is due to using an unsupported version

> so this is not about "just don't use 3.0 yet", we need to address this deprecation so in future it will be easier to migrate to 3.0 when it's time

Yes. But until then, dont use 3.0 or you will get the build failing
