### ISSUE TITLE
Venomhide Hatchling missing RP emotes when eating Silithid Meat #1871 

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8107]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1871

When doing [Gorishi Grub](https://wowgaming.altervista.org/aowow/?quest=13903) daily quest, you feed [Silithid Meat](https://wowgaming.altervista.org/aowow/?item=46380) to your [Venomhide Hatchling](https://wowgaming.altervista.org/aowow/?npc=34320), he eats it (and quest credit is properly given) but he does no emote at all.

### Expected Blizzlike Behaviour

He performs emotes (telling how he eats his foodin one gulp or how he looks at you wanting more, etc).

### Source

In [this video](https://www.youtube.com/watch?v=JrwH8gGN1Ak), he performs the emotes listed on [his Wowgaming/Altervista page](https://wowgaming.altervista.org/aowow/?npc=34320).

It's a WoD video however, I am not sure if it counts as a legit source.
I can try to find other sources if needed.

### Steps to reproduce the problem

1. Go to Un'Goro Crater (anywhere in Un'Goro will do);
2. Add quest 13903 (the daily);
3. Add item 46362 and use it (to summon him);
4. Add item 46380 and use it (to feed him);
5. Notice how he just eats it silently.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by VFaleiro** [comment]
Forgot to mention (in the original report) there are 2 other dailies where you feed your hatchling:
- For [Hungry, Hungry Hatchling](https://wowgaming.altervista.org/aowow/?quest=13889), you feed him some [Fresh Dinosaur Meat](https://wowgaming.altervista.org/aowow/?item=46367);
- For [Poached, Scrambled, Or Raw?](https://wowgaming.altervista.org/aowow/?quest=13904), you feed him some [Silithid Egg](https://wowgaming.altervista.org/aowow/?item=46382)

In all 3 cases he should perform the same emotes.

**Comment by Shineslippers** [comment]
Have to reopen because of https://github.com/chromiecraft/chromiecraft/issues/2488

### Current Behaviour

Using [Silithid Egg](https://wowgaming.altervista.org/aowow/?item=46382) and [Fresh Dinosaur Meat](https://wowgaming.altervista.org/aowow/?item=46367) fed player instead of [Venomhide Hatchling](https://wowgaming.altervista.org/aowow/?npc=34320)

https://user-images.githubusercontent.com/85256266/144822995-2842c904-4114-4ba0-9d39-cb9b5aa5c268.mp4


### Expected Blizzlike Behaviour

Should fed pet as it's doing [Silithid Meat](https://wowgaming.altervista.org/aowow/?item=46380)

### Steps to reproduce the problem

.tel gadget
.cast 65183
.additem 46382
.additem 46367
fed pet
