### ISSUE TITLE
Dead as a ghost

### ISSUE THREAD

**Issue by r-o-b-o-t-o** [azerothcore/azerothcore-wotlk#8111]
### Current Behaviour

> While in a solo instance of Ragefire Chasm I died and was ported to the graveyard outside of Orgrimmar after hitting release spirit. After loading into the overworld I was still dead, but as a ghost, could not move or interact with the spirit healer. I logged out to the character screen which still showed me as a ghost but after logging back in I was alive with half hp/mana like I had recovered my body normally.

### Expected Blizzlike Behaviour

> You shouldn't be able to die as a ghost? Releasing from a dungeon should put you in ghost form at the spirit healer to move around and recover your body.

### Steps to reproduce the problem

> Cleared RDF, let the other party members leave the dungeon and died inside. Ran back normally and zoned into a fresh instance, died again and was ported to the spirit healer as a ghost.

### Extra Notes

Originally reported here https://github.com/chromiecraft/chromiecraft/issues/1672 by @RolyNuki

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by syssneck** [comment]
I had the same happen to me, when I tested something solo in BRD on my local AC. Seems like it has something to do with dying solo in a dungeon.

**Comment by r-o-b-o-t-o** [comment]
Yes, there are working repro steps in this issue, copied from the original issue's last comment

**Comment by JamesGent** [comment]
This reminds me of this issue. Being both dead and alive at the same time.

https://github.com/azerothcore/azerothcore-wotlk/issues/4768
