### ISSUE TITLE
[Dungeon Finder] Requeueing with a group from inside a dung doesn't teleport all to the new dung

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#8121]
### Current Behaviour

After completing a dungeon and requeueing from inside the dungeon only teleports the group leader to the new dungeon. The other group members need to leave the completed dungeon via the eye and enter the new dungeon via the eye.

### Expected Blizzlike Behaviour

All players should be teleported to the new dungeon if they accept the dungeon finder pop up.

### Steps to reproduce the problem

1. complete a dung via rdf
2. stay inside the dungeon
3. Requeue for a new dungeon via rdf
4. see that only the leader gets automatically teleported to the new dung

### AC rev. hash/commit

792b99cbc9a6eac4

### Operating system

Win 10 x64

**Comment by UltraNix** [comment]
@syssneck The new dungeon is the same map?

**Comment by syssneck** [comment]
What do you mean by same map (=same dungeon, new id?). We had it happen with the same dungeon, but I believe also with a different dungeon, but I'll test again to be sure.

**Comment by syssneck** [comment]
Tested on local AC and everything works fine there ...  
Maybe we were jumping on CC, so the teleport was not triggered (not teleported when jumping, falling, swimming). I will close this now, as I can't reproduce it locally.

**Comment by syssneck** [comment]
Nvm it's still an issue on CC. No jumping or anything involved. 2 of 3 party members were teleported, the third not.
