### ISSUE TITLE
Darkshore Threshers stays at the bottom of the sea

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8125]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1875

[Darkshore Threshers](https://wowgaming.altervista.org/aowow/?npc=2185) stays at the bottom of the sea and won't attack if you attack it with ranged attack while keeping character's head over surface

![WoWScrnShot_092721_225308](https://user-images.githubusercontent.com/9262857/134976944-7eb4bf07-d6a7-4ca8-9d00-4ca03f2a8d26.jpg)

![WoWScrnShot_092721_225315](https://user-images.githubusercontent.com/9262857/134976949-a7d97e21-d0ba-4c3e-835e-126cc71ed42f.jpg)
.

### Expected Blizzlike Behaviour

The mob should swim up and attack.

### Steps to reproduce the problem

1. Pick a ranged class (I used female night elf druid)
2. Find a Darkshore Thresher (off shore from Auberdine)
3. Keep head above surface (do not dive).
4. Attack the mob (I used wrath)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
Same as https://github.com/azerothcore/azerothcore-wotlk/issues/7741
Something is wrong with the pathfinding of water-only creatures.

**Comment by acidmanifesto** [comment]
Closes due to fix: https://github.com/azerothcore/azerothcore-wotlk/pull/9272
