### ISSUE TITLE
Free Action Potion should not be purgeable/dispellable/spellstealable

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#8126]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1880

According to some players, priests, shamans and mages are able to remove the effect of [Free Action Potion](https://www.wowhead.com/item=5634/free-action-potion). This could happen at patch 1.7 as you can see [here](https://wowwiki-archive.fandom.com/wiki/Free_Action_Potion).

However, since patch 2.3 this shouldn't be possible, since the effect of this potion is a buff of Physical School and not magic.
https://wotlk.evowow.com/?spell=6624

Also check [this](https://github.com/ccshiro/cc-buglist/issues/1790).

### Expected Blizzlike Behaviour

The Free Action Potion effect should not be purgable in any way.

[Free Action Potion]: The buff from this potion can no longer be dispelled or taken via Spellsteal. (patch 2.3.0 notes)

### Source
https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0

https://www.wowhead.com/item=5634/free-action-potion#comments

### Steps to reproduce the problem

Use Free Action Potion
Fight a Mage / Priest / Shaman
Get your buff Spellstealed / Dispelled / Purged
/Cry

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by bonfax4** [comment]
This should be the case to every potion btw according to [this](https://wowwiki-archive.fandom.com/wiki/Patch_3.3.3).

"Potions: All the buffs from potions that were incorrectly considered magic effects and thus dispellable by Dispel Magic are no longer considered magic."

**Comment by Ragelezz** [comment]
Could not confirm. Tried: mass dispell, purge, spellsteal but its not taking the buff from me.

**Comment by Kitzunu** [comment]
<details><summary>SpellWork</summary>

ID - 6615 Free Action
=================================================
Description: Makes you immune to Stun and Movement Impairing effects for the next $d.   Does not remove effects already on the imbiber.
ToolTip: Free Action.
Category = 4, SpellIconID = 1356, activeIconID = 0, SpellVisual = (7119,0), SpellPriority = 0
Family SPELLFAMILY_POTION, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x28000000 (SPELL_ATTR0_CASTABLE_WHILE_SITTING, SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 4
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00
RecoveryTime: 0 ms, CategoryRecoveryTime: 60000 ms
StartRecoveryCategory = 0, StartRecoveryTime = 0,00 ms
Duration: ID (9)  30000, 0, 30000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 77 (SPELL_AURA_MECHANIC_IMMUNITY), value = 1, misc = 11 (11), miscB = 0, periodic = 0

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 1
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 77 (SPELL_AURA_MECHANIC_IMMUNITY), value = 1, misc = 7 (7), miscB = 0, periodic = 0

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 77 (SPELL_AURA_MECHANIC_IMMUNITY), value = 1, misc = 12 (12), miscB = 0, periodic = 0

=================================================
Items using this spell:
   5634: Free Action Potion 

</details>

DispelType = 0 (DISPEL_NONE)

Closing, it's impossible to dispel this as it has the type above.
