### ISSUE TITLE
Gameobject info command doesn't show gameobject GUID

### ISSUE THREAD

**Issue by LordArcanine** [azerothcore/azerothcore-wotlk#8129]
### Current Behaviour

When i use .gob info i dont get the gameobject id from the command but i see all the rest of the info

### Expected Blizzlike Behaviour

only to work as intended

### Source

![WoWScrnShot_092821_094123](https://user-images.githubusercontent.com/3597399/135088974-ec2b2948-57f6-4bf3-8afd-b7e6fe208368.jpg)
![WoWScrnShot_092821_094135](https://user-images.githubusercontent.com/3597399/135088990-d27ff0a9-173c-480f-a67f-527934e561e8.jpg)

### Steps to reproduce the problem

only use the command on any gameobject

### AC rev. hash/commit

![WoWScrnShot_092821_094354](https://user-images.githubusercontent.com/3597399/135089214-b086c0f8-6ab5-47ce-b9c4-cb9c14405f6d.jpg)

### Operating system

Debian 10 x64

### Custom changes or Modules

![image](https://user-images.githubusercontent.com/3597399/135089377-49f9ebf2-215e-47b2-bb97-36b1a5333a24.png)

**Comment by Nyeriah** [comment]
This is the ID you're looking fo
![Skärmbild 2021-09-28 094748](https://user-images.githubusercontent.com/47818697/135089970-358c9809-f395-4ef2-8aa2-b90ff6ecf253.png)
r

**Comment by LordArcanine** [comment]
did you ever read the image? its guid not id
i cant despawn a gob without the guid

**Comment by Nyeriah** [comment]
> did you ever read the image? its guid not id i cant despawn a gob without the guid

I'm sorry, but your report makes no mention of **GUID**, what it says is: 

> When i use .gob info i dont get the gameobject **id** from the command but i see all the rest of the info

I acknowledge the issue. Try using .gob near meanwhile, it'll show the GUID of the nearest objects.

**Comment by Kitzunu** [comment]
I dont know what you want to change?

.gobject info clearly states it gives the info for the gameobject. It should not list every spawned gob and their GUIDs

that is something .lookup gobject should do

**Comment by Nyeriah** [comment]
> I dont know what you want to change?
> 
> .gobject info clearly states it gives the info for the gameobject. It should not list every spawned gob and their GUIDs
> 
> that is something .lookup gobject should do

I don't think that's the idea, but it displays information for the targeted object: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_gobject.cpp#L628-L633

It wouldn't hurt to have it display the target's GUID there as well, if an object is selected.

**Comment by Kitzunu** [comment]
target, that's fine. Just should not list every spawn =)

**Comment by LordArcanine** [comment]
yeah was my error sorry, the problem its gob info dont give the guid

**Comment by LordArcanine** [comment]
> > I dont know what you want to change?
> > .gobject info clearly states it gives the info for the gameobject. It should not list every spawned gob and their GUIDs
> > that is something .lookup gobject should do
> 
> I don't think that's the idea, but it displays information for the targeted object: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_gobject.cpp#L628-L633
> 
> It wouldn't hurt to have it display the target's GUID there as well.

in fact tc always showed the guid on gob info
