### ISSUE TITLE
MaxWhoListReturns = 49 No effect

### ISSUE THREAD

**Issue by pklloveyou** [azerothcore/azerothcore-wotlk#813]
**Description**:

**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by talamortis** [comment]
Are these issue templates here just for nothing? Please fill them out

**Comment by BarbzYHOOL** [comment]
I think he's chinese though

**Comment by talamortis** [comment]
translate.google.com

**Comment by Middel** [comment]
he can speak english perfectly fine, he has other issues opened on AC repo where he fills out the form properly. so he can do it. and so he should.

**Comment by w5860363** [comment]
@BarbzYHOOL I think he wanted to say that MaxWhoListReturns amd CONFIG_MAX_WHO does not exist in world. cpp world.h But it exists in worldserver.conf Excuse me for my English. I am Asian
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/World/World.cpp
https://github.com/TrinityCore/TrinityCore/blob/317b0a4fb3169962e84aea24e98cdd59de08646c/src/server/game/World/World.cpp#L1344

**Comment by w5860363** [comment]
@talamortis The problem is that the original code exists from Sunwell and the configuration is invalid.
