### ISSUE TITLE
Core compilation failed error

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#8135]
### Current Behaviour

OS： Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)
core：azerothcore b2f0893
modules：mod-eluna-lua-engine bf79100
CMake version: 3.16.3

link ：https://gist.github.com/yuanf225/3a112654c02c53aa1e8f8f8c6012d73e

### Expected Blizzlike Behaviour

Can complete core compilation normally

### Steps to reproduce the problem

use core：b2f0893+modules：bf79100

cmake ../ -DCMAKE_INSTALL_PREFIX=/home/server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS=1 -DSCRIPTS=static

make -j 8

### AC rev. hash/commit

b2f0893

### Operating system

Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)

### Custom changes or Modules

mod-eluna-lua-engine bf79100

**Comment by Kitzunu** [comment]
CLang/GCC version? (I have no idea which is used as I don't use Linux)

However, CI passes so something is wrong on your end

**Comment by yuanf225** [comment]
clang version 10.0.0-4ubuntu1 
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Is it because the clang/gcc version is too low?

**Comment by Kitzunu** [comment]
nope they are supported. see https://github.com/azerothcore/azerothcore-wotlk/security/policy

try to delete the cmake cache, pull the latest master and rebuild again

**Comment by yuanf225** [comment]
Can’t compile successfully because the module is used: mod-eluna-lua-engine
If you do not use this module, there will be no errors

**Comment by yuanf225** [comment]
module: mod-eluna-lua-engine I am also the latest submission (bf79100)

**Comment by Kitzunu** [comment]
Okay, make an issue on that repository.
