### ISSUE TITLE
Worldserver.exe crashes log

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#814]
[Crashes_2018-03-19.zip](https://github.com/azerothcore/azerothcore-wotlk/files/1824235/Crashes_2018-03-19.zip)
I don't know why this problem occurs. >_<

**Comment by Rochet2** [comment]
Need debug crashlog and more information.

**Comment by ShinDarth** [comment]
please provide the crashlog when using DEBUG mode so we can be able to help you
