### ISSUE TITLE
SQLs won't import if region locale is not English US

### ISSUE THREAD

**Issue by okcanien** [azerothcore/azerothcore-wotlk#815]
**Description**: If your region locale is set to anything other than English (US), then you will get errors when attempting to import the SQLs into the databases

**Current behaviour**: SQLs won't import and get errors
**Expected behaviour**: SQLs import without any errors

**Steps to reproduce the problem**:

1. Set region locale to anything other than English (US)
2. Attempt to import SQLs to databases

**Branch(es)**: master 

**AC hash/commit**:  3cd8da7

**Operating system**:  Windows 7 Ultimate 64 bit SP1

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by DarkmoonRabbit** [comment]
I come from China.
I can import it! Please set UTF-8 encoding.

**Comment by pklloveyou** [comment]
UTF-8

**Comment by Viste** [comment]
Please read about encoding types and then try again.
ru_RU all is ok

**Comment by HamedMohsenavi** [comment]
ERROR 2006 (HY000) at line 155: MySQL server has gone away

**Comment by pondaveia** [comment]
When creating your databases make sure they are UTF-8 encoded change the settings to avoid future errors.

**Comment by HamedMohsenavi** [comment]
CREATE SCHEMA `world1` DEFAULT CHARACTER SET utf8 ;

mysql -uroot -proot world1 < world_base.sql

done

mysql  --protocol=tcp --host=localhost --user=root --port=3306 --default-character-set=utf8 --comments --database=world1  < "/home/hamed/Wotlk/env/dist/sql/world_update.sql"

ERROR 2006 (HY000) at line 155: MySQL server has gone away

**Comment by Deku** [comment]
Not related to the core. Confirmed by others that languages are working OK (I use spanish in my own server)
