### ISSUE TITLE
Feature: confs should be optional and smarter

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#8158]
### Describe your feature request or suggestion in detail

We should avoid continuing forcing our user to create and keep configuration files updated with their  .dist, unless they are using wrong configurations properties or name.

At the beginning AzerothCore worked even without the .conf file. Now instead AC is forcing to have a manually created conf file and that this conf file must include all the configurations that you have inside the dist file. I'm wondering if there's any reason behind this approach.

This instead reduces the maintainability and generates unexpected error in server logs if an user did not imported a new conf from dist to its own file, after a core update. 

### Describe a possible solution to your feature or suggestion in detail

The solution would be to:

1. Make the `.conf` file optional
2. Only check if the user inserted a non existent conf name or a non valid value. In that case the server should not start at all, or, if it happens during the ".reload conf", do not execute the function and logging an error in the chat as well.

In this way the users should only maintain the configuration properties that they want to change... And if we change the name to a conf after a PR...our users will be notified by the system that they have a wrong conf.

I hope it makes sense to you

Feel free to comment it

### Additional context

This is also more or less the same strategy the linux applications use for their software

**Comment by Kitzunu** [comment]
But .conf is optional?

I haven't updated my .conf anything since I installed AC 2 years ago with exceptions to stuff I actually wanted to change. Anything new is just read from .conf.dist.

So I don't really understand what's the issue?

**Comment by Winfidonarleyan** [comment]
Hmm, i think I got it.
