### ISSUE TITLE
Twilight torment Sartharion 25 Man

### ISSUE THREAD

**Issue by Morgarr** [azerothcore/azerothcore-wotlk#816]
**Description**: Twilight torment take too much damage to the raid

**Current behaviour**: When we try to do Sartharion with 3 drakes alive , when Vesperon appearing and summoning his portal , the spell twilight torment take too much damage at all the raid and make a one shot (above 45k damage) and we haven't got time to enter in the portal before taking the one shot.

**Expected behaviour**: The spell twilight torment no damage all the raid with ~40k+.

**Steps to reproduce the problem**:

1.  Start Sartharion with 3 drakes
2. Kill the 2 first and wait for Vesperon arrival 
3. Wait the Vesperon portal pop and after 2-3sec , all raid one shot by the Twilight torment. 

**Branch(es)**:  master

**AC hash/commit**:  3cd8da7

**Operating system**:  Debian 9.1

**Modules**:  Transmog module

**Other Customizations**: /

**Comment by talamortis** [comment]
`UPDATE creature_template SET MovementType = 0, InhabitType = 9 WHERE entry IN ( 30641, 31521);`

**Comment by Yehonal** [comment]
@talamortis what does it fix exactly?

**Comment by talamortis** [comment]
the creature that the spell spawns shouldn't move it should be rooted and yes it should do this much damage but because it moves it does the damage to the raid.

**Comment by Yehonal** [comment]
Could you commit this fix then?

**Comment by talamortis** [comment]
Yes i will do once @Morgarr  has tested.

**Comment by Morgarr** [comment]
I tested alone and that should be work , but can't test with a raid at the moment , so i'm not certain.

**Comment by Morgarr** [comment]
I have more informations , actually the Twiligh torment debuff stack at the number of characters in the raid so if we are 25 , we have 25 stacks of the Twilight torment and 1 attack does 40k damages, and he shouldn't do that. Normaly only one 1 stack of the torment on all players of the raid.

So , the problem doesn't come from the Void blast for your SQL request.

**Comment by Morgarr** [comment]
I'v fixed it , we have to replace the   SPELL_TWILIGHT_TORMENT_SARTHARION = 58853, line 44 in obisdian_sanctum.h by SPELL_TWILIGHT_TORMENT_SARTHARION = 58835

**Comment by talamortis** [comment]
Please can you open a PR for people to test

**Comment by Yehonal** [comment]
i'll test it asap

**Comment by Morgarr** [comment]
Sorry i'm in Holidays , i'll try to create a PR when i come back home in few days

**Comment by Morgarr** [comment]
Okay thank's Yehonal , i'v just finish to fix the SQL request for the twilight fissure , i try to fix the debuff when entering in a portal do unaura the player and Sartharion will perfectly fixed i mean

**Comment by Morgarr** [comment]
-- For the fix of the Twilight fissure : --

UPDATE `creature_template` SET `MovementType` = 0 , `InhabitType` = 8 , `ScriptName` = "trigger_periodic" WHERE `entry` IN(30641,31521);

-- For Fix the debuff when enter in portal : --

DELETE FROM smart_scripts WHERE (source_type = 1 AND entryorguid = 193988);
INSERT INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) VALUES
(193988, 1, 0, 0, 64, 0, 100, 0, 0, 0, 0, 0, 28, 58835, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, '');
