### ISSUE TITLE
Hodir not dropping Hodirs Sigil in 10 man Hardmode

### ISSUE THREAD

**Issue by pe93** [azerothcore/azerothcore-wotlk#8165]
### Current Behaviour

Hodir is not dropping hodirs sigil in 10man Hardmode. I checked Cache of Winter and Rare Cache of Winter and it wasnt in there. 

### Expected Blizzlike Behaviour

Hodir drops the Sigil after beating him in Hardmode

### Steps to reproduce the problem

1. Go to Ulduar, set Raid to 10 man and enter instance
2. kill all the Bosses and go to Hodir
3. Start the encounter and kill him in less than 3 minutes for Hardmode.

### AC rev. hash/commit

 AzerothCore rev. b2f08934bcc6 2021-09-27 22:15:03 +0000 (master branch) (Uni
x, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar
2020)
Using Boost version: 1.71.0
Using MySQL version: 80026
Using CMake version: 3.16.3
Compiled on: Linux 5.4.72-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207
 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 6581307
21 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365
032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_09_27_04
Using Character DB Revision: 2021_09_25_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Win 10 running with docker

### Custom changes or Modules

no modules

**Comment by Ravenguard13** [comment]
Confirming the problem.
No sigils on 10 and 25 modes both.

The Cache of Winter is there but there's no sigil inside.

Also, the achievement "I Could Say That This Cache Was Rare" , both 10/25 can't be completed though all the conditions are done.
https://wotlkdb.com/?achievement=3184
https://wotlkdb.com/?achievement=3182

Which means, no furthee Algalon boss fight, no proto mounts too.

Please fix it.

**Comment by pe93** [comment]
Also it seems that when u make ulduar 10 man and you kill hodir he drops 25 man loot and when you make ulduar 25 man you get 10 man loot.
