### ISSUE TITLE
Can not enter Ulduar after someone teleport in combat

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8167]
### Current Behaviour

RT

### Expected Blizzlike Behaviour

Boss should reset after no victim

### Steps to reproduce the problem

1.go c 137630
2.Start combat
3.Use teleport command or hearthstone(and Divine Shield) to get out Ulduar
4.Now you cannot enter Ulduar

### AC rev. hash/commit

52aa0e9

### Operating system

Windows 10 x64

**Comment by Nyeriah** [comment]
Creature 137630 is Mimiron, this issue is related to that specific encounter, not a generic issue.

**Comment by bgcfb** [comment]
> Creature 137630 is Mimiron, this issue is related to that specific encounter, not a generic issue.

It also happened with Freya and Algalon the Observer many times

**Comment by Nyeriah** [comment]
Attempting to reproduce this issue with the steps provided produces the following crash: 

```Exception code: C0000005 ACCESS_VIOLATION
Call stack:
Address   Frame     Function      SourceFile
00007FF63D75655D  000000938B5FE260  LinkedListElement::hasNext+1D  C:\Users\andre\Desktop\Azeroth-Core\Source\src\common\Dynamic\LinkedList.h line 27
00007FF63D756834  000000938B5FE2A0  LinkedListElement::next+14  C:\Users\andre\Desktop\Azeroth-Core\Source\src\common\Dynamic\LinkedList.h line 31
00007FF63D7567CB  000000938B5FE2E0  Reference<Unit,ThreatMgr>::next+1B  C:\Users\andre\Desktop\Azeroth-Core\Source\src\common\Dynamic\LinkedReference\Reference.h line 73
00007FF63D756814  000000938B5FE310  HostileReference::next+14  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Combat\ThreatMgr.h line 96
00007FF63E681573  000000938B5FE380  HostileRefMgr::deleteReferences+33  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Combat\HostileRefMgr.cpp line 108
00007FF63E42A127  000000938B5FE420  Map::RemovePlayerFromMap+47  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 887
00007FF63E438A99  000000938B5FE450  InstanceMap::RemovePlayerFromMap+29  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 2967
00007FF63DFEE117  000000938B5FEC20  Player::TeleportTo+15D7  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Entities\Player\Player.cpp line 1508
00007FF63D7A1558  000000938B5FECA0  Player::TeleportTo+C8  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Entities\Player\Player.h line 1043
00007FF63E4C3376  000000938B5FF230  Player::Update+1926  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Entities\Player\PlayerUpdates.cpp line 416
00007FF63E42A9A7  000000938B5FF600  Map::Update+2C7  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 747
00007FF63E438BBE  000000938B5FF640  InstanceMap::Update+2E  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 2956
00007FF63E9D85CA  000000938B5FF680  MapUpdateRequest::call+4A  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\MapUpdater.cpp line 32
00007FF63E9D60FD  000000938B5FF6F0  MapUpdater::WorkerThread+7D  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\MapUpdater.cpp line 148
00007FF63E9D6EAE  000000938B5FF720  std::invoke<void (__cdecl MapUpdater::*)(void),MapUpdater *>+1E  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits line 1610
00007FF63E9D699B  000000938B5FF790  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+7B  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\thread line 56
00007FFB432E4C7C  000000938B5FF7F0  _register_onexit_function+EC
00007FFBE50654E0  000000938B5FF820  BaseThreadInitThunk+10
00007FFBE5DE485B  000000938B5FF8A0  RtlUserThreadStart+2B```

**Comment by bgcfb** [comment]
> Attempting to reproduce this issue with the steps provided produces the following crash:
> 
> ```
> Call stack:
> Address   Frame     Function      SourceFile
> 00007FF63D75655D  000000938B5FE260  LinkedListElement::hasNext+1D  C:\Users\andre\Desktop\Azeroth-Core\Source\src\common\Dynamic\LinkedList.h line 27
> 00007FF63D756834  000000938B5FE2A0  LinkedListElement::next+14  C:\Users\andre\Desktop\Azeroth-Core\Source\src\common\Dynamic\LinkedList.h line 31
> 00007FF63D7567CB  000000938B5FE2E0  Reference<Unit,ThreatMgr>::next+1B  C:\Users\andre\Desktop\Azeroth-Core\Source\src\common\Dynamic\LinkedReference\Reference.h line 73
> 00007FF63D756814  000000938B5FE310  HostileReference::next+14  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Combat\ThreatMgr.h line 96
> 00007FF63E681573  000000938B5FE380  HostileRefMgr::deleteReferences+33  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Combat\HostileRefMgr.cpp line 108
> 00007FF63E42A127  000000938B5FE420  Map::RemovePlayerFromMap+47  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 887
> 00007FF63E438A99  000000938B5FE450  InstanceMap::RemovePlayerFromMap+29  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 2967
> 00007FF63DFEE117  000000938B5FEC20  Player::TeleportTo+15D7  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Entities\Player\Player.cpp line 1508
> 00007FF63D7A1558  000000938B5FECA0  Player::TeleportTo+C8  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Entities\Player\Player.h line 1043
> 00007FF63E4C3376  000000938B5FF230  Player::Update+1926  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Entities\Player\PlayerUpdates.cpp line 416
> 00007FF63E42A9A7  000000938B5FF600  Map::Update+2C7  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 747
> 00007FF63E438BBE  000000938B5FF640  InstanceMap::Update+2E  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\Map.cpp line 2956
> 00007FF63E9D85CA  000000938B5FF680  MapUpdateRequest::call+4A  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\MapUpdater.cpp line 32
> 00007FF63E9D60FD  000000938B5FF6F0  MapUpdater::WorkerThread+7D  C:\Users\andre\Desktop\Azeroth-Core\Source\src\server\game\Maps\MapUpdater.cpp line 148
> 00007FF63E9D6EAE  000000938B5FF720  std::invoke<void (__cdecl MapUpdater::*)(void),MapUpdater *>+1E  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits line 1610
> 00007FF63E9D699B  000000938B5FF790  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+7B  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\thread line 56
> 00007FFB432E4C7C  000000938B5FF7F0  _register_onexit_function+EC
> 00007FFBE50654E0  000000938B5FF820  BaseThreadInitThunk+10
> 00007FFBE5DE485B  000000938B5FF8A0  RtlUserThreadStart+2B```
> ```

It may relate to #8099 
I just patched with pr 8160

**Comment by UltraNix** [comment]
Might be related to 4dc642d530e3d. Encounters are reset after 20 sec.

**Comment by bgcfb** [comment]
I think so, if there is no player in the instance ,It won't reset

**Comment by bgcfb** [comment]
> Might be related to [4dc642d](https://github.com/azerothcore/azerothcore-wotlk/commit/4dc642d530e3d4aa66f9b3a6bbb941392553d7b9). Encounters are reset after 20 sec.

comfirmed,it related to #7828 ,i change the time to zero ,the issue solved

**Comment by UltraNix** [comment]
@Si1ker Due to `Reset` is called after 20 sec, and then in case of the wipe, door are closed, combat remains and encounter is still in progress. I think we should call `Reset` and only toggle invisibility options.

**Comment by Si1ker** [comment]
> @Si1ker Due to `Reset` is called after 20 sec, and then in case of the wipe, door are closed, combat remains and encounter is still in progress. I think we should call `Reset` and only toggle invisibility options.

@UltraNix that's why I placed a reset before sending the boss to the Invisibility, but then I reworked it based on Footman's input, I'm currently with IRL stuff so see if you can add it, and should work.

**Comment by UltraNix** [comment]
@Si1ker So restore it. Call `Reset` and then for these bosses do your code.

**Comment by mpfans** [comment]
This is the mine called by `Mimiron`. It hasn't disappeared. It takes about half an hour to disappear

**Comment by mpfans** [comment]
CC @UltraNix
