### ISSUE TITLE
Hodir 10 man Hardmode loot

### ISSUE THREAD

**Issue by pe93** [azerothcore/azerothcore-wotlk#8168]
### Current Behaviour

When you kill Hodir in 10 man Hardmode he spawns the Rare Cache of Winter. However in the Chest is 25 man Hardmode loot, and not the 10 man loot.

### Expected Blizzlike Behaviour

When you kill him in 10 man Hardmode you get 10 man Hardmode loot and nor 25.

### Steps to reproduce the problem

Enter ulduar 10 man
Kill Hodir in Hardmode
Loot Rare Cache of Winter

### AC rev. hash/commit

 AzerothCore rev. b2f08934bcc6 2021-09-27 22:15:03 +0000 (master branch) (Uni
x, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar
2020)
Using Boost version: 1.71.0
Using MySQL version: 80026
Using CMake version: 3.16.3
Compiled on: Linux 5.4.72-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207
 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 6581307
21 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365
032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_09_27_04
Using Character DB Revision: 2021_09_25_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Win 10 running with docker

### Custom changes or Modules

noone

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10844 fixed it
