### ISSUE TITLE
On the problem of worldserver.exe collapse

### ISSUE THREAD

**Issue by ss958** [azerothcore/azerothcore-wotlk#818]
On the problem of worldserver.exe collapse

Loading Dump File [J:\AzerothCore\core-cpp\bin\RelWithDebInfo\93cf5edd57cd+_worldserver.exe_[26-3_18-24-52].dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: J:\AzerothCore\core-cpp\bin\RelWithDebInfo
Executable search path is: J:\AzerothCore\core-cpp\bin\RelWithDebInfo
Windows Version 7601 (Service Pack 1) MP (2 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
Debug session time: Mon Mar 26 18:24:52.000 2018 (GMT+8)
System Uptime: not available
Process Uptime: 0 days 0:49:27.000
.....................................................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(510.6b0): C++ EH exception - code e06d7363 (first/second chance not available)
Unable to load image C:\Windows\System32\ntdll.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ntdll.dll
*** ERROR: Module load completed but symbols could not be loaded for ntdll.dll
ntdll+0x6a57a:
00000000`7745a57a c3              ret
0:006> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

Unable to load image D:\WOWserver\core\worldserver.exe, Win32 error 0n2
*** WARNING: Unable to verify timestamp for worldserver.exe
*** ERROR: Module load completed but symbols could not be loaded for worldserver.exe
Unable to load image C:\Windows\System32\msvcp140.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for msvcp140.dll
*** ERROR: Module load completed but symbols could not be loaded for msvcp140.dll
Unable to load image C:\Windows\System32\VCRUNTIME140.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for VCRUNTIME140.dll
*** ERROR: Module load completed but symbols could not be loaded for VCRUNTIME140.dll
Unable to load image C:\Windows\System32\ucrtbase.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ucrtbase.dll
*** ERROR: Module load completed but symbols could not be loaded for ucrtbase.dll
Unable to load image D:\WOWserver\core\ace.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ace.dll
*** ERROR: Module load completed but symbols could not be loaded for ace.dll
*** WARNING: Unable to verify timestamp for kernel32.dll
*** ERROR: Module load completed but symbols could not be loaded for kernel32.dll
***** OS symbols are WRONG. Please fix symbols to do analysis.

*** WARNING: Unable to verify checksum for libeay32.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for libeay32.dll - 
Unable to load image C:\Windows\System32\ole32.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ole32.dll
*** ERROR: Module load completed but symbols could not be loaded for ole32.dll
*** WARNING: Unable to verify checksum for libmysql.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for libmysql.dll - 
Unable to load image C:\Windows\System32\mswsock.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for mswsock.dll
*** ERROR: Module load completed but symbols could not be loaded for mswsock.dll
Unable to load image C:\Windows\System32\ws2_32.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for ws2_32.dll
*** ERROR: Module load completed but symbols could not be loaded for ws2_32.dll

FAULTING_IP: 
KERNELBASE+1a06d
000007fe`fd10a06d 4881c4c8000000  add     rsp,0C8h

EXCEPTION_RECORD:  ffffffffffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 000007fefd10a06d (KERNELBASE+0x000000000001a06d)
   ExceptionCode: e06d7363 (C++ EH exception)
  ExceptionFlags: 00000001
NumberParameters: 4
   Parameter[0]: 0000000019930520
   Parameter[1]: 000000000a2bf7c0
   Parameter[2]: 0000000140b6be50
   Parameter[3]: 000000013f920000
Unable to load image C:\Windows\System32\msvcrt.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for msvcrt.dll
*** ERROR: Module load completed but symbols could not be loaded for msvcrt.dll
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Your debugger is not using the correct symbols                 ***
***                                                                   ***
***    In order for this command to work properly, your symbol path   ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: msvcrt!EHExceptionRecord                      ***
***                                                                   ***
*************************************************************************

PROCESS_NAME:  worldserver.exe

FAULTING_MODULE: 00000000773f0000 ntdll

DEBUG_FLR_IMAGE_TIMESTAMP:  0

ERROR_CODE: (NTSTATUS) 0xe06d7363 - <Unable to get error code text>

IP_ON_HEAP:  00000000763c2a30
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

FRAME_ONE_INVALID: 1

LAST_CONTROL_TRANSFER:  from 00000000763c2a30 to 000007fefd10a06d

STACK_COMMAND:  ~6s; .ecxr ; kb

FOLLOWUP_IP: 
KERNELBASE+1a06d
000007fe`fd10a06d 4881c4c8000000  add     rsp,0C8h

SYMBOL_STACK_INDEX:  0

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: worldserver

IMAGE_NAME:  worldserver.exe

SYMBOL_NAME:  worldserver.exe

FAULTING_THREAD:  00000000000006b0

DEFAULT_BUCKET_ID:  WRONG_SYMBOLS

PRIMARY_PROBLEM_CLASS:  STACK_CORRUPTION

BUGCHECK_STR:  APPLICATION_FAULT_STACK_CORRUPTION_CODE_RUNNING_ON_STACK

FAILURE_BUCKET_ID:  X64_APPLICATION_FAULT_STACK_CORRUPTION_CODE_RUNNING_ON_STACK_worldserver.exe

BUCKET_ID:  X64_APPLICATION_FAULT_STACK_CORRUPTION_CODE_RUNNING_ON_STACK_worldserver.exe

Followup: MachineOwner
---------

0:006> lmvm worldserver
start             end                 module name
00000001`3f920000 00000001`40d80000   worldserver T (no symbols)           
    Loaded symbol image file: worldserver.exe
    Image path: D:\WOWserver\core\worldserver.exe
    Image name: worldserver.exe
    Timestamp:        Sat Mar 24 00:56:50 2018 (5AB531D2)
    CheckSum:         00000000
    ImageSize:        01460000
    File version:     0.0.0.0
    Product version:  0.0.0.0
    File flags:       0 (Mask 3F)
    File OS:          40004 NT Win32
    File type:        1.0 App
    File date:        00000000.00000000
    Translations:     0000.04b0 0000.04e0 0409.04b0 0409.04e0
0:006> lmvm ntdll
start             end                 module name
00000000`773f0000 00000000`7758f000   ntdll    T (no symbols)           
    Loaded symbol image file: ntdll.dll
    Image path: C:\Windows\System32\ntdll.dll
    Image name: ntdll.dll
    Timestamp:        Mon Jan 01 10:20:02 2018 (5A499AD2)
    CheckSum:         001A4D04
    ImageSize:        0019F000
    File version:     6.1.7601.24000
    Product version:  6.1.7601.24000
    File flags:       0 (Mask 3F)
    File OS:          40004 NT Win32
    File type:        2.0 Dll
    File date:        00000000.00000000
    Translations:     0000.04b0 0000.04e0 0409.04b0 0409.04e0
0:006> lmvm worldserver
start             end                 module name
00000001`3f920000 00000001`40d80000   worldserver T (no symbols)           
    Loaded symbol image file: worldserver.exe
    Image path: D:\WOWserver\core\worldserver.exe
    Image name: worldserver.exe
    Timestamp:        Sat Mar 24 00:56:50 2018 (5AB531D2)
    CheckSum:         00000000
    ImageSize:        01460000
    File version:     0.0.0.0
    Product version:  0.0.0.0
    File flags:       0 (Mask 3F)
    File OS:          40004 NT Win32
    File type:        1.0 App
    File date:        00000000.00000000
    Translations:     0000.04b0 0000.04e0 0409.04b0 0409.04e0
0:006> g
       ^ No runnable debuggees error in 'g'

May I ask what the problem is caused by this problem?

**Comment by ShinDarth** [comment]
Invalid issue report. Please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

Also please wrap your output in blockquotes to make it readable.

Thank you.
