### ISSUE TITLE
worldserver failed to start

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#8202]
### Current Behaviour

use：./worldserver

The sql file of mod-weapon-visual will not be updated automatically
Error message：
Initializing Scripts...
> Loading C++ scripts
 
[1146] Table 'characters.mod_weapon_visual_effect' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
Caught signal 6
Segmentation fault (core dumped)

After manually importing the sql file of mod-weapon-visual, it starts to report an error
Error message：
Initialize data stores...

/home/azerothcore-wotlk/src/common/DataStores/DBCFileLoader.h:75 in getString ASSERTION FAILED:
  stringOffset < file.stringSize

Segmentation fault (core dumped)
root@VM-0-8-ubuntu:/home/server/bin# 

### Expected Blizzlike Behaviour

Start worldserver normally

### Steps to reproduce the problem

1.Use module: mod-weapon-visual
2.Completely compile and create a database

### AC rev. hash/commit

https://github.com/tbcstar/azerothcore-wotlk/commit/8be919af77e4a871a5f15e783d613fb54f153a14

### Operating system

Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)

### Custom changes or Modules

https://github.com/tbcstar/mod-weapon-visual/commit/f8d914da737034ee9e80280aa39f4c95a887f15a

**Comment by Winfidonarleyan** [comment]
Need correct module :/
