### ISSUE TITLE
Paladin Seals procs from multiple sources not just melee hits

### ISSUE THREAD

**Issue by Ragelezz** [azerothcore/azerothcore-wotlk#8207]
### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1925

Paladin seals procs from spells which are not supposed to do so, like AoE spells or ranged spells.

### Expected Blizzlike Behaviour

Seals should proc only from melee hits not (or spells which give melee hit) currently they proc from any form of damage.

### Source

https://wowgaming.altervista.org/aowow/?spell=20375 > Tooltips of spells "melee attacks..."

### Steps to reproduce the problem

Infuse your paladin with a seal, perform a spell which is ranged or aoe, seal procs. (divine storm or judgement as original report said also tested)

### AC rev. hash/commit

local server, latest commits applied.

### Operating system

8.1

**Comment by laasker** [comment]
I dont know about Seal of Command, but Seal of Righteousness should proc the seal when you use judgement

Retail video:
https://www.youtube.com/watch?v=xummB-b9nDE at 5:40, his judgement hits 2499 and his seal proc, doing 980 damage
at 5:49 he uses judgement again and the seal proc, at 6:24 he uses divine storm and the seal proc, at 6:26 he uses crusader strike and the seal procs

So i think atleast for the Seal of Righteousness its working as intended

**Comment by phonkala** [comment]
Yes judgement definitely should proc the effects, it's a single target hitting ability.
https://wowwiki-archive.fandom.com/wiki/Seal_of_Command_(old)

**Comment by Ragelezz** [comment]
What about divine storm?

**Comment by phonkala** [comment]
> What about divine storm?

Many pservers do have divine storm proccing SoC too but I don't think that should proc it as it hits multiple enemies, the tooltip states it should only proc from single targets abilities or attacks.

**Comment by Nyeriah** [comment]
Blizzard considers Divine Storm a single target spell that hits multiple targets, similar to Hammer of Righteousness. Both proc seal effects.

> This ability can proc seal effects.

https://vanilla-wow-archive.fandom.com/wiki/Divine_Storm

**Comment by UltraNix** [comment]
As stated above - not a bug.
