### ISSUE TITLE
Druid class can't need on alchemy recipes anymore

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8226]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1939

Haven't been able to need on alchemy recipes anymore on my druid in dungeon groups for a while. I do have alchemy 300/300. The need button is grayed out, hovering mouse over it shows "Your class may not roll need on this item".

I do think I remember being able to need alchemy recipes when I was leveling up to perhaps lvl 30-40 so could be that some patch/update changed this, not sure though. Also not sure if this only happens in dungeons, been doing just RDF for a long time now.

![alchemy-druid-need](https://user-images.githubusercontent.com/43609330/135730291-5640032b-f497-4a8e-897a-9992bd5108ef.jpg)

### Expected Blizzlike Behaviour

Profession recipes should not be class specific.

### Steps to reproduce the problem

1. Play druid.
2. Join group (RDF) and grind mobs until some alchemy recipe drops.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@IntelligentQuantum Cannot reproduce it. More info needed or test it again.

**Comment by IntelligentQuantum** [comment]
@UltraNix This only happens in RDF, did you join RDF?

**Comment by UltraNix** [comment]
@IntelligentQuantum ?

**Comment by IntelligentQuantum** [comment]
> @IntelligentQuantum ?

yeah, sorry

**Comment by IntelligentQuantum** [comment]
@UltraNix 
![Screenshot_20211101_211510](https://user-images.githubusercontent.com/14080516/139716821-ec66af5e-f808-4d0f-ab43-31bcb4d4b2f2.png)

**Comment by UltraNix** [comment]
And you don't know/learn that recipe yet?

**Comment by syssneck** [comment]
"Plans: Thorium Armor" is a blacksmithing recipe.

**Comment by UltraNix** [comment]
But you do have Blacksmithing skill?

**Comment by IntelligentQuantum** [comment]
> But you do have Blacksmithing skill?
I forgot to update the source. it works fine.
