### ISSUE TITLE
[Scholomance] Spectral Projections giving more reputation than intended

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8230]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1948

Spectral Projections are NPCs that are summoned by another NPC, so summoned minions with lower hp stats etc..
They give 10 reputation for each kill which is a bit overmuch they should give +1 per kill as they're being summoned often by trash in this dungeon
![WoWScrnShot_100221_201433](https://user-images.githubusercontent.com/80590226/135744381-7404dddb-27e0-44b7-892f-344eac61cab7.jpg)
![WoWScrnShot_100221_201430](https://user-images.githubusercontent.com/80590226/135744382-22db821c-028a-44bd-91e7-633be83b1509.jpg)

### Expected Blizzlike Behaviour

Should give +1 rep per kill as they're summoned NPCs

### Steps to reproduce the problem

1. Go to Scholomance
2. Kill Spectral Tutor
3. He will summon Spectral Adds
4. Get +10 rep per kill

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by syssneck** [comment]
I don't want to doubt this, but do we have a source for this?

> Patch 2.2.0 (2007-09-25): The following old-world factions have had their acquisition rate significantly increased: Cenarion Circle, Argent Dawn and Timbermaw Hold. 
https://wowpedia.fandom.com/wiki/Argent_Dawn#Patch_changes

10 rep doesn't seem unreasonable compared to the (minimum) 20 rep we get for a furbolg kill with the Timbermaw Hold.

**Comment by patou01** [comment]
It's a non-elite that spawns on death of an elite. The other elites give 10 (I believe?) rep. It doesn't seem realistic that this single elite should amount for half the pack (10 + 3*10, while the total pack is 70 if we count these potentially bugged ones)
