### ISSUE TITLE
SMART_ACTION_CALL_AREAEXPLOREDOREVENTHAPPENS doesn't work when the SAI source is a GO and the player is in group

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#8237]
### Current Behaviour

When players are in group, the core checks if they're in range of the "source" to know if they can be awarded the quest or not. Here: https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/AI/SmartScripts/SmartScript.cpp#L685

Source being the creature or gameobjected scripted. 

It just happens that to perform the range check, the code currently uses ***me**  as parameter to call the function (it's an instance of creature)

So once the action gets called by something that isn't a creature (a gameobject...) it returns null, failing to properly credit players as the "range check" doesn't happen.

### Expected Blizzlike Behaviour

The SAI action should work regardless of being called by a GO or creature

### Source

N/A

### Steps to reproduce the problem

1.quest add 4285
2.join a group
3.go gob 17598 (Northern Pylon)
4.Check if you get credit when selecting the gossip

### Extra Notes

Original report:
https://github.com/chromiecraft/chromiecraft/issues/1932

<hr>
Can´t examine the pylons in Un´Goro Crater. Quest will not be completed after clicking on pylon and dialog. The sceenshot is from the North pylon. It is the same in East and West.

![WoWScrnShot_100221_170101](https://user-images.githubusercontent.com/90547104/135722452-75feecff-6ef6-46c7-94f3-8dcc39017106.jpg)
![WoWScrnShot_100221_170110](https://user-images.githubusercontent.com/90547104/135722454-a62374ec-cc63-432a-9b2f-cdcb09bd306f.jpg)
t.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6e2c87b35eb6feb41f7587a8e57ec586f473622c

### Operating system

Win11 x64

**Comment by ntrna** [comment]
I am not in a party, nor running any addons, yet I cannot complete the Northern Pylon. Haven't yet tried east/west
![image](https://user-images.githubusercontent.com/89823720/135768489-67328e77-a040-4ad7-b39e-18704c80c9bc.png)

**Comment by Nyeriah** [comment]
I'm not sure what issue were you experiencing, but I tried repeatedly to reproduce this issue and I could never do so when not in a group.

![Skärmbild 2021-10-03 163623](https://user-images.githubusercontent.com/47818697/135768912-c4f4ec87-c6e0-41ae-9a21-47bd4d702c59.jpg)
