### ISSUE TITLE
[Scholomance] Adds for Alexei barov don't respawn and are slow to join fight.

### ISSUE THREAD

**Issue by patou01** [azerothcore/azerothcore-wotlk#8239]
### Current Behaviour

The mobs aren't linked to his reset apparently.
![image](https://user-images.githubusercontent.com/2592673/135762180-bd66bafa-252c-45fc-871f-5f35978ba12b.png)

Triggered by killing one, enabling GM mode (or FD, but was on my mage) and toggling again

### Expected Blizzlike Behaviour

Both adds should respawn on reset

### Steps to reproduce the problem

1. Go to scholo / alexei barov (.go c 48863 )
2. aggro, kill one add, evade fight (FD, GM, invisiblity, vanish), ...
3. mob doesn't respawn.

creature ID: 10504 and 10489. Maybe fixable through formation?

### AC rev. hash/commit

dcd2bbabb420 (my dev branch but that's latest master and I haven't touched scholo)

### Operating system

win 10 x64

**Comment by sudlud** [comment]
Tested.

.go c 48863
.gm off
engage `Lord Alexei Barov`

kill one or both `Risen Guard` adds
walk away and disengage fight with `.combat` or `.gm on`

before PR
- adds do not respawn

after PR
- both adds instantly respawn after disengaging fight
