### ISSUE TITLE
Server does not compile with modules

### ISSUE THREAD

**Issue by Regrad** [azerothcore/azerothcore-wotlk#8242]
### Current Behaviour

When compiling a server with any modules, compilation fails. I've already tried everything that is possible. Replaced all software, compiled on two different computers. Everything compiled fine two months ago.

Ошибка	LNK2019	ссылка на неразрешенный внешний символ "void __cdecl Addmod_ah_bot_masterScripts(void)" (?Addmod_ah_bot_masterScripts@@YAXXZ) в функции "void __cdecl AddScripts(void)" (?AddScripts@@YAXXZ).	worldserver	D:\aaa\azerothcore-wotlk-build\src\server\worldserver\scripts.lib(ScriptLoader.obj)	1	

### Expected Blizzlike Behaviour

The server must compile.

### Steps to reproduce the problem

1) Connect modules.
2) Try to compile.

### Extra Notes

boost_1_74_0-msvc-14.2-64
cmake-3.21.3-windows-x86_64
Git-2.33.0.2-64-bit
mysql-installer-community-5.7.35.0
Win64OpenSSL-1_1_1L (A,G)
Visual Studio 2019

### AC rev. hash/commit

06e50a9690f7708dc7134c98807f58f1bb445035

### Operating system

Windows 8.1 and 10

### Custom changes or Modules

Any

**Comment by Nefertumm** [comment]
Can't confirm. I've just compiled a fresh core with boss_announcer, a module of my own and emblem_transfer. Make sure your VS version is above 16.4

**Comment by Winfidonarleyan** [comment]
Please use git clone

**Comment by Regrad** [comment]
> Can't confirm. I've just compiled a fresh core with boss_announcer, a module of my own and emblem_transfer. Make sure your VS version is above 16.4

16.11

**Comment by Winfidonarleyan** [comment]
> > Can't confirm. I've just compiled a fresh core with boss_announcer, a module of my own and emblem_transfer. Make sure your VS version is above 16.4
> 
> 16.11

17

**Comment by Regrad** [comment]
> > > Can't confirm. I've just compiled a fresh core with boss_announcer, a module of my own and emblem_transfer. Make sure your VS version is above 16.4
> > 
> > 
> > 16.11
> 
> 17

I have Visual Studio 2019 6.11
Do I need to use Visual Studio 2022?

**Comment by Regrad** [comment]
VS 2022, modules renamed, but error again =(

**Comment by syssneck** [comment]
Get a "fresh" git clone of AC in a new folder (don't use your updated branch!), delete your build folder, delete Cache in cmake, configure, generate, right click on ALL BUILD in VS and choose clean, then build.

**Comment by Regrad** [comment]
> Rename the module folder if you copied it manually (remove the -master at the end). I had the same problem a few days ago. I'm using VS 2019 16.11 and it works just fine.

Ok, ok. It's work for me! Ty! (not all modules, but it's work!)

**Comment by patou01** [comment]
The CI seems to struggle.
![image](https://user-images.githubusercontent.com/2592673/136075067-266aff7e-6a60-4681-bd8f-ff19dbe5722a.png)

![image](https://user-images.githubusercontent.com/2592673/136075218-09a1ed52-199e-4fda-b80e-aed415282baf.png)

**Comment by Kitzunu** [comment]
CI passing
