### ISSUE TITLE
"Argent Dawn Commission" Quests Are Not Faction-Locked

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8253]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1959

Alliance Argent Officer Pureheart offers repetable quests for Horde players (including Argent Dawn Commission)

Tester: confirmed. There are two versions of this quest, [ID 5401](https://classic.wowhead.com/quest=5401/argent-dawn-commission) for the Alliance and [ID 5405](https://classic.wowhead.com/quest=5405/argent-dawn-commission) for the Horde. Both have AllowableRaces set to 0, i.e. no restrictions. There is a third version of the quest, [ID 5593](https://tbc.wowhead.com/quest=5503/argent-dawn-commission) which is faction-neutral, which is perhaps where the error came from.

![WoWScrnShot_100421_172908](https://user-images.githubusercontent.com/81782124/135807449-67b97844-8e3e-4b76-8164-376860730e10.jpg)

### Expected Blizzlike Behaviour

Horde's Argent Dawn Commission quest should not be available at Alliance's quest giver.

"Horde should talk to Argent Officer Garush
Alliance should talk to Argent Officer Pureheart" ([source](https://classic.wowhead.com/item=12846/argent-dawn-commission#comments:id=65609))

### Source

https://tbc.wowhead.com/quest=5401/argent-dawn-commission
https://tbc.wowhead.com/quest=5405/argent-dawn-commission
https://tbc.wowhead.com/item=12846/argent-dawn-commission

### Steps to reproduce the problem

1. Horde 50+ character
2. .go c 45241
3. Check if he offer quest to opposing faction

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
My Everyquest addon says it could be available for horde.
![WoWScrnShot_100521_154738](https://user-images.githubusercontent.com/85256266/136025552-9cbac48e-cd1a-4ceb-b683-6298d7925f90.jpg)
