### ISSUE TITLE
Scholomance - Lady Illucia Barov Loot Issues

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8255]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1896

Drops a green or better item at 30% chance with equal chance to each.

![image](https://user-images.githubusercontent.com/84640316/135467183-bb4e5faf-fa26-43b2-bb2d-5fc217988e90.png)

Tester: This NPC uses RLT 35031, which contains 27 blue items and is shared by 6 bosses in Scholo. 

This table shows the recorded drop rates on TBC Wowhead vs derived drop rates on AC. This shows the first 16 T0 items have drop rates about 3 times lower than they should be.

  Item ID | Item Name                | iLvl| WH Drp | AC Drp |  Diff  | AC RLT
  ---|---|---|---|---|---|---
  20520 | Dark Rune                |  55 | 13.91% | 48.00% | 34.09% | Direct
  12753 | Skin of Shadow           |   1 |  4.91% | 19.00% | 14.09% | Direct
  12843 | Corruptor's Scourgestone |   1 | 89.01% | 100.00% | 10.99% | Direct
  14047 | Runecloth                |  50 |  9.80% | 17.00% |  7.20% | Direct
  14620 | Deathbone Girdle         |  61 |  4.02% |  1.11% |  2.91% | 35031
  14615 | Bloodmail Gauntlets      |  61 |  4.01% |  1.11% |  2.90% | 35031
  14632 | Necropile Leggings       |  61 |  3.99% |  1.11% |  2.88% | 35031
  14636 | Cadaverous Belt          |  61 |  3.92% |  1.11% |  2.81% | 35031
  14640 | Cadaverous Gloves        |  61 |  3.88% |  1.11% |  2.77% | 35031
  14638 | Cadaverous Leggings      |  61 |  3.88% |  1.11% |  2.77% | 35031
  14612 | Bloodmail Legguards      |  61 |  3.87% |  1.11% |  2.76% | 35031
  14631 | Necropile Boots          |  61 |  3.87% |  1.11% |  2.76% | 35031
  14621 | Deathbone Sabatons       |  61 |  3.80% |  1.11% |  2.69% | 35031
  14622 | Deathbone Gauntlets      |  61 |  3.74% |  1.11% |  2.63% | 35031
  14633 | Necropile Mantle         |  61 |  3.69% |  1.11% |  2.58% | 35031
  14614 | Bloodmail Belt           |  61 |  3.68% |  1.11% |  2.57% | 35031
  14629 | Necropile Cuffs          |  61 |  3.67% |  1.11% |  2.56% | 35031
  14641 | Cadaverous Walkers       |  61 |  3.65% |  1.11% |  2.54% | 35031
  14623 | Deathbone Legguards      |  61 |  3.58% |  1.11% |  2.47% | 35031
  14616 | Bloodmail Boots          |  61 |  3.56% |  1.11% |  2.45% | 35031
  18681 | Burial Shawl             |  61 |  1.53% |  1.11% |  0.42% | 35031
  18682 | Ghoul Skin Leggings      |  61 |  1.46% |  1.11% |  0.35% | 35031
  23200 | Totem of Sustaining      |  65 |  0.78% |  1.11% |  0.33% | 35031
  18680 | Ancient Bone Bow         |  61 |  1.42% |  1.11% |  0.30% | 35031
  18684 | Dimly Opalescent Ring    |  61 |  1.35% |  1.11% |  0.24% | 35031
  14624 | Deathbone Chestplate     |  61 |  1.35% |  1.11% |  0.24% | 35031
  18683 | Hammer of the Vesper     |  61 |  1.33% |  1.11% |  0.22% | 35031
  14626 | Necropile Robe           |  61 |  1.30% |  1.11% |  0.19% | 35031
  14637 | Cadaverous Armor         |  61 |  1.26% |  1.11% |  0.15% | 35031
  14611 | Bloodmail Hauberk        |  61 |  1.25% |  1.11% |  0.14% | 35031
  23201 | Libram of Divinity       |  65 |  0.99% |  1.11% |  0.12% | 35031

Also note Wowhead contains 245 other items that do not appear on AC's drop tables. 

Standard disclaimer, we all know Wowhead isn't fully reliable. However, the listed WH data is from just under 23K kills of this NPC, which seems like a large enough number to be pretty reliable.

### Expected Blizzlike Behaviour

Probably what needs to be is the 16 T0 set items need to be in a reference loot table with 16x5= 80% drop rate and remaining 10 items another reference loot table with 10x2=20% percent chance (i.e. 2 reference loot tables should have the same group ID).

Tester: I agree about creating 2 RLTs, as the drop rates between the two item sets are so different. However, the 5%/2% numbers above are not accurate. If you sum Wowhead's blue item drops, they only come to 75%, so we probably shouldn't be rewriting the RLTs to produce that effect. Instead, if you average the 16 T0 items' drop rates, you get 3.8% x 16 items = 61% droprate for the RLT that contains them. The other 11 have an average on WH of 1.27% x 11 = 14% drop rate for their RLT. The two RLTs then sum to 75%, which matches WH. This would produce a maximum deviation from WH data of 0.2%, assuming no manual tweaking of individual item droprates.

### Source

https://tbc.wowhead.com/npc=10502/lady-illucia-barov#drops

### Steps to reproduce the problem

keira 3 or mysql

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
Currently Loot table Matches up with UDB (Universale Database) that is established for loot based on verified sniffs and not wowhead or website database scrapes.
In our table we have the following hits on the creature_loot_template:

![image](https://user-images.githubusercontent.com/16887899/148101530-c4db5e77-f9dc-46e8-82e5-6820bb500d36.png)

With references to reference loot table:
35031when it comes to groups.

Loot tables are concurrent and matching exactly to UDB.

Loot tables are not 100% drop on items with every kill regardless of rarity of creature type\boss type.
Reference Loot Tables were not 100% either on older wow expansions as well contrary to popular belief due to adjustments in much later expansions.
