### ISSUE TITLE
OpenSSL 1.1

### ISSUE THREAD

**Issue by HamedMohsenavi** [azerothcore/azerothcore-wotlk#827]
[Core/Crypto: Transitional Cryptography update for OpenSSL 1.1](https://github.com/TrinityCore/TrinityCore/commit/efef6b5e36a8cd8eca023b8aa6a5d8cbd532ca68)

[Buildsystem: Fixed finding openssl 1.1 libs](https://github.com/TrinityCore/TrinityCore/commit/1dd44207bd4a50b1ad159d77dd940f876276d74b)

**Comment by ShinDarth** [comment]
@HamedMohsenavi can you please [provide a PR](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request) with those changes?

**Comment by HamedMohsenavi** [comment]
Hi

**Comment by BarbzYHOOL** [comment]
@HamedMohsenavi test the pull request https://github.com/azerothcore/azerothcore-wotlk/pull/840 with openssl 1.1 please and we can probably merge it

**Comment by BarbzYHOOL** [comment]
Fixed thanks viste and hamed!
https://github.com/azerothcore/azerothcore-wotlk/commit/53364abcd7822617b2a63c03b015967d33f14614
