### ISSUE TITLE
Various quests available to a players without pre-quests complete.

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8275]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/1979

1. [Nathanos Blightcaller](https://tbc.wowhead.com/npc=11878/nathanos-blightcaller) ofrreing quests what shouldn't be available without pre-quests. Also he is oferring 2xThe Call to Command  quest.
![WoWScrnShot_100521_041717](https://user-images.githubusercontent.com/85256266/135945479-4be68226-b554-4dd4-832d-efd81ba53bbc.jpg)

2.  [Lady Sylvanas Windrunner](https://www.wowhead.com/npc=10181/lady-sylvanas-windrunner) offering The Crimson Courier quest without pre-quests.

### Expected Blizzlike Behaviour

![Untitled](https://user-images.githubusercontent.com/85256266/135926637-18b8a20e-1057-4cc2-944b-2abce0776f63.png)

### Source

[Wowwiki](https://wowwiki-archive.fandom.com/wiki/Quest:To_Kill_With_Purpose#Quest_progression) To kill with Purpose quest page for example.
[Wowhead](https://tbc.wowhead.com/quest=6144/the-call-to-command#comments:id=3158426) The Call to Command quest comment:

> By MantiKore on 2019/09/25 (Classic)
> When you get to Nathanos, this quest won't be available. You will need to do the following:
> 
> 1. To Kill With Purpose
> 2. Un-Life's Little Annoyances
> 3. The Ranger Lord's Behest (you may need a group of 2/3 people for this one).
> 
> Then, you hand those in and he will offer you the following quests:
> 
> 4. Duskwing, Oh How I Hate Thee...
> 5. The Corpulent One
> 
> You definitely need a group for the elites, especially Borelgore. He hits like a freight train and has a huge amount of HP.

### Steps to reproduce the problem

Speak to Sylvanna and Nathanos Blightcaller

### Extra Notes

There is something what i don't understand how to should be.
The Call to Command quest have [ID6144](https://wowgaming.altervista.org/aowow/?quest=6144) and [ID14349](https://wowgaming.altervista.org/aowow/?quest=14349). The Crimson Courier quest have [ID6145](https://wowgaming.altervista.org/aowow/?quest=6145) or [ID14350](https://wowgaming.altervista.org/aowow/?quest=14350). I don't know which version should be used but [comment ](https://www.wowhead.com/quest=14349/the-call-to-command#comments:id=863167) about higher quest id saying:
> By 164918 on 2009/10/10 (Patch 3.2.2) 
>Added in 3.3 so Horde players can continue these quests, that would cease to exist for Horde players post-Wrath Gate.

Also [wowwiki](https://wowwiki-archive.fandom.com/wiki/Quest:The_Call_to_Command):

>Note: This quest chain was recently reinstated with Patch 3.3; it was previously unavailable after Varimathras' demise during H [74] The Battle For The Undercity.

Probably should be used quests with higher IDs if we have 3.3.5 core

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
We still have quests for Varimathras even though this NPC doesn't exist in WOTLK, that's why there's two quest IDs for the same quest, just different ender.
