### ISSUE TITLE
An Unusual Patron

### ISSUE THREAD

**Issue by helicopter12** [azerothcore/azerothcore-wotlk#828]
**Description**: The quest "An Unusual Patron" is bugged as the spell to spawn Naias does not work. The spell doesn't cast because it says it requires the Alter of Naias even though it is in range.

**Current behaviour**: The creature Naias does not spawn as the spell is bugged

**Expected behaviour**: You use item "Gift of Naias" (ID: 23680) to spawn Naias when next to the Alter of Naias gameobject

**Steps to reproduce the problem**:

1. Get the quest
2. Try to spawn Naias with "Gift of Naias"

**Branch(es)**:  master 

**AC hash/commit**:  842ac4c14c0f0b650f2efa863ca81ff59866128c

**Operating system**:  Windows 10

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Dootz** [comment]
https://github.com/Aokromes/TrinityCore/commit/7cbb8847bbd2b10676f03ee25a9b4999a11ab171

**Comment by Cillez** [comment]
Tested, and can confirm it's not working. 

Tested on AzerothCore rev. 8481eec5beac 2018-06-08 23:05:10 -0300

```-- Naias
UPDATE `event_scripts` SET `x`= -12132.446289, `y`=964.982422, `z`= 5.194236, `o`= 5.130559 WHERE `id`=10554;
SET @ENTRY := 17207;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `source_type`=0 AND `entryorguid`=@ENTRY;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,5000,5000,12000,13000,11,37054,0,0,0,0,0,2,0,0,0,0,0,0,0,'Naias - IC - cast Water Bolt'),
(@ENTRY,0,1,0,0,0,100,0,2000,6000,10000,14000,11,34828,0,0,0,0,0,2,0,0,0,0,0,0,0,'Naias - IC -cast Water Shield'),
(@ENTRY,0,2,0,54,0,100,0,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,'Naias - just summoned - say line1');

DELETE FROM `creature_text` WHERE `entry`=17207;
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(17207, 0, 0, 'Who challenges Naias? Puny $r, you are little better than those mindless trolls I have played against each other like so many pieces on a game board!', 12, 0, 100, 0, 0, 0, 13560, 0, 'Naias'); 
```

This fixed the issue for me.

**Comment by Nefertumm** [comment]
Thanks, can you open a PR?

**Comment by Cillez** [comment]
I can give it a shot when i get home in 1 hour ish. Haven't done it before but I assume there is a guide for it somewhere :)
