### ISSUE TITLE
Feature: Minimizing headers in include files

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#8281]
### Describe your feature request or suggestion in detail

Make the amount of `#include` to minimum

### Describe a possible solution to your feature or suggestion in detail

Best example file - https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Scripting/ScriptMgr.h

I've already started to do it in PR #6873

**Comment by Kitzunu** [comment]
I would think this is pretty much done
