### ISSUE TITLE
Congrats module

### ISSUE THREAD

**Issue by phulo** [azerothcore/azerothcore-wotlk#829]
**Description**:Congrats on lvl do not work properly

**Current behaviour**:  The module announce when the player gain a level but there is no reward every 10 lvls.

**Expected behaviour**: 
# Set what the player receives at each level
# M: Gold 
# S: SpellID to be cast on the player
# 1: First ItemID to be given to the player
# 2: Second ItemID to be given to the player

At lvl 10
# Level 10
# 1 Gold / Blessing of Kings
# Red Rose / TCG: Foam Sword Rack
Congrats.L10M = 1;
Congrats.L10S = 20217
Congrats.L101 = 3419
Congrats.L102 = 45062

**Comment by Deku** [comment]
Please open an issue in the corresponding repository. This is the repo for the core, so just WotLK stuff. See: https://github.com/azerothcore/mod-congratsonlevel
