### ISSUE TITLE
[SPELL/WARRIOR]sword-specialization

### ISSUE THREAD

**Issue by Remberance** [azerothcore/azerothcore-wotlk#8301]
### Current Behaviour

BUG : sword-specialization only occoured 1 damage!!!

![image](https://user-images.githubusercontent.com/4078506/136168515-a9661cd8-bf4f-4b9c-b926-b0b714e23538.png)

### Expected Blizzlike Behaviour

sword-specialization's damage as weapon damage.

for exmple, when i equiped 34247, sword-specialization should occoured 404-607 damage, not 1 .

### Steps to reproduce the problem

1. create a warrior.
2. open N add point to 5/4 sword-specialization 5/5(12812 12812 12814 12815 lv2-5).
3. go to damage dummy to swings or cast any spell.
4. see sword-specialization's percent of all damage.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5af98783c9f61f059914b3304bb26785502a6924

### Operating system

WIN10

**Comment by Shineslippers** [comment]
Sword Specialization is working correct
![WoWScrnShot_120221_190616](https://user-images.githubusercontent.com/85256266/144458903-bb5c809b-3882-429e-8869-511985e6a108.jpg)
![WoWScrnShot_120221_190702](https://user-images.githubusercontent.com/85256266/144458920-6969c0a1-3ebc-4dca-8663-f6e3a9b7bda4.jpg)
