### ISSUE TITLE
UBRS The beast: Unexpected mobs, Finkle spawned and missing spells

### ISSUE THREAD

**Issue by patou01** [azerothcore/azerothcore-wotlk#8312]
### Current Behaviour

There's mobs spawned in front of the Beast which probably shouldn't be there.
![image](https://user-images.githubusercontent.com/2592673/136250196-8d6c70fc-7f81-499a-88cc-bab635627609.png)

The 2 orcs I believe are meant to be chomped by the beast once we get there or something like that.

Also, Finkle is spawned ahead of time for some reason.

Finally, seems like there's spells missing as well.

Edit: His spell doesn't hit melee range, if you let him attack you, you will not be in range for the aoe blast.

### Expected Blizzlike Behaviour

Not sure about the orcs. Based on wowpedia I think they are supposed to be eaten by the beast, the yell says "we're doomed", so probably something about the beast breaking free and munching some orcs? 
https://classic.wowhead.com/npc=10317/blackhand-elite#comments;mode:normal 

Finkle should only spawn once the beast is dead and skinned. Seeing as he's spawned already but the script seems okay, I think he just needs his spawn removed from the DB?

### Source

https://youtu.be/vri9bt0OQGk?t=1033
https://classic.wowhead.com/npc=10317/blackhand-elite#comments;mode:normal
https://wowpedia.fandom.com/wiki/The_Beast

### Steps to reproduce the problem

Go to UBRS, get to the beast and check. 
.go c 137969

I don't know if there's any event that should trigger first for it to initialize, I don't see anything on the mobs or in the code

### Extra Notes

hash is my local dev but I haven't touched this event...

### AC rev. hash/commit

9d16b9eb6038

### Operating system

win 10 x64

**Comment by patou01** [comment]
Yes it's my own dev branch... It takes me 20 minutes to compile if I pull the master again, and nobody touched this dungeon afaik. I could have written the latest master but that'd be lying 🤷🏼‍♂️. It takes 2 minutes on the ptr to go there and see.

**Comment by patou01** [comment]
Actually partial duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/1878 it seems.

**Comment by iraizo** [comment]
I've never wasted anybodies time, if you simply cannot read that is not my issue.
