### ISSUE TITLE
Double doors inside Karazhan

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#8319]
### Current Behaviour

There are two doors (Gatehouse Door) at the very beginning of Karazhan, just as you zone in. The second door is not clickable, although you can walk to the side of it to get past it.

### Expected Blizzlike Behaviour

The second door shouldn't be there.

### Steps to reproduce the problem

1. Add the required key with .additem 24490
2. Go to the instance using .tele karazhan
3. Open the Portcullis and zone into the raid
4. Click the Gatehouse Door to see the second one behind it.

### Extra Notes

This is how it currently looks: https://imgur.com/a/j2zAf30

### AC rev. hash/commit

b82b4ca

### Operating system

Ubuntu 21.04

**Comment by Nyeriah** [comment]
Confirmed, that door was supposed to be spawned outside instead (the non-instanced area), but for some reason we got it spawned inside the instance.

**Comment by tkn963** [comment]
> 
> 
> Confirmed, that door was supposed to be spawned outside instead (the non-instanced area), but for some reason we got it spawned inside the instance.
> 
> Also please note that you can just drag pictures into GitHub messages to upload them, it makes browsing reports easier ;)

Oh, I had no idea about the picture thing. I'll use that next time!
