### ISSUE TITLE
To conflagrate is not Instant Warlock to Spell Conflagrate

### ISSUE THREAD

**Issue by diegobfl** [azerothcore/azerothcore-wotlk#832]
Description: To conflagrate is not Instant Warlock to Spell Conflagrate

Current Behavior: When the warlock uses a spell (Immolate) a spell is released (Conflagrate = 17962), however it is taking between 1 to 2 seconds to spell Conflagrate to be released to attack.

Expected Behavior: When using Spell Immolate instantly it was released a Conflagrate spell for attack, however it is taking seconds to release.

Steps to reproduce the problem:

With the active talent to conflagrate, make the following rotation
Use "Immolate" or "Shadowflame"
And finally "Conflagrate"

AC hash / commit: `[https://github.com/azerothcore/azerothcore-wotlk/commit/783003f0e8d4e51f1f8afbabbacd5c2b292f6fb2]

Operating System: Windows 8
``
Modules: none

Other customizations: none

**Comment by Deku** [comment]
That's an intended behaviour for the spell to be "blizzlike" (?). You can fix that by changing the check at https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp#L3916

**Comment by lineagedr** [comment]
https://www.youtube.com/watch?v=yq3N1fP3a24&feature=youtu.be&t=194 Intended

**Comment by talamortis** [comment]
This has already been open and closed. will close again since duplicate. this is not intended by blizzard.
