### ISSUE TITLE
NPC Daphne Stilwell despawns after "Tome of Valor" quest completion.

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#8323]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1978

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

After completing the Paladin quest "The Tome of Valor"  Daphne Stilwell despawns and does not respawn for 5 minutes

### Expected Blizzlike Behaviour

She shouldn't despawn at all, but continue roaming her orchard.

### Source
https://youtu.be/xsehGRGIlx0?t=209
https://youtu.be/02oHynd015c?t=180
https://youtu.be/73F_9Q28gk4?t=246
From WOW classic
### Steps to reproduce the problem

1. Be an alliance paladin min level 20
2. .quest add 1650
3. .go c 66979
4. Turn in and accept the chained quest. 
5. Defend her however you wish and complete the quest
6. Notice she does not move and will despawn after a minute
7. Wait 5 minutes for respawn.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Hey @malcrom this was fixed too in your PR too, wasn't it? We might have forgot to close it
