### ISSUE TITLE
[Faction] Argent Dawn quests giving incorrect amount of reputation.

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8325]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/2000

**_ALL_** Argent Dawn [quests](https://wowgaming.altervista.org/aowow/?quests&filter=cr=1;crs=529;crv=0) giving half of reputation.

### Expected Blizzlike Behaviour

Amount of reputation for quests should be doubled.

### Source

Wowpedia [Patch 2.2.0](https://wowpedia.fandom.com/wiki/Patch_2.2.0#World_Environment)
> The following old-world factions have had their acquisition rate significantly increased: Cenarion Circle, Argent Dawn, Timbermaw Hold.

You can choose 3 random quests from list above and read in comments about reputation changes. Let me try 1st.
[Above and Beyond](https://www.wowhead.com/quest=5263/above-and-beyond)
> By 172375 on 2010/09/13 (Patch 3.3.5)
1000 rep for this quest, 500 and then 1000 for the short follow ups.

> By 7784 on 2008/10/17 (Patch 3.0.2)
This quest actually gives 1,000 Argent Dawn rep, contrary to the 350 posted above.

[Dead Man's Plea](https://www.wowhead.com/quest=8945/dead-mans-plea)

> By mattous on 2008/02/23 (Patch 2.3.3)
Completing this quest also gives you 1000 reputation with the Argent Dawn

[Target: Felstone Field](https://www.wowhead.com/quest=5229/target-felstone-field)
> By 119934 on 2008/04/26 (Patch 2.4.1)
now it is 500 reputation with argent dawn

### Steps to reproduce the problem

Idk

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ragelezz** [comment]
Where I can find the comments for the rest of the quests? On wowhead tbc\normal wowhead can't seem to find some. If you can post all the quests that should have their exp reward recalculate that would be great!
