### ISSUE TITLE
[Dungeon Finder] 5 players premade should behave like normal groups (loot/buffs/kicks, etc.)

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#8339]
### Current Behaviour

If a full group of 5 players queue and enter a LFG/LFD instance, they can't change the loot mode.

### Expected Blizzlike Behaviour

If a full group of 5 players queue and enter a LFG/LFD instance, they should be able to change the loot mode.

### Steps to reproduce the problem

1. Gather a full group of 5 players
2. Queue for a LFG/LFD dungeon and enter it
3. Try to change the loot mode

### Extra Notes

I have been searching for so many hours to try to find a source to back up this claim, but I myself don't have any videos from back then and there's nothing to be found anywhere about this specific issue.

I am absolutely certain it worked like that back in retail WotLK because I ran so many dungeons using LFG/LFD with my multiboxing teams back then.

I'm hoping someone else might be able to back me up and confirm it.

### AC rev. hash/commit

a5db11f

### Operating system

Ubuntu 21.04

**Comment by Santaria94** [comment]
https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

>Note: Premade groups of five which use the Dungeon Finder to queue will function more or less like a normal group. The group leader will retain the ability to remove other group members and set the group’s looting rules. The difference is that these groups, unlike normal groups, will be able to earn daily random dungeon rewards and access the dungeon teleportation system. Certain features and benefits, however, like the Vote Kick system and "Luck of the Draw" buff (detailed below), will not be available for these group types.

**Comment by tkn963** [comment]
> 
> 
> @tkn963 What about LFG group inside dungeon when the run is over and then requed?

Are you asking what happens in that situation? Queuing as a full group keeps the group as it is, and queuing again would just be the same situation. I was looking at the source for that a while back, but as a newbie in C++ I realized the code deletes the old group and creates a new one for LFG which imo it shouldn't do at all IF it's a 5/5 group.

**Comment by tkn963** [comment]
I have absolutely no idea how the code works, but maybe the group info could somewow be copied over to the LFG group with some kind of flag to tell the system it's a full group so it needs the normal rules rather than the stricter LFG rules.
