### ISSUE TITLE
Core/Script: Zul'Gurub

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#834]
**Description**: 
There a a few things with bosses in Zul'Gurub that aren't quite working.

**Current behaviour**: 
High Priest Venoxis (14507)  should pull with the 4 snakes on his platform (Razzashi Cobra 11373) at the moment you can pull them seperately. They're set to the same faction so I'm not sure why they don't pull together.

High Priestess Jeklik's (14517) flying adds (Frenzied Bloodseeker Bat 14965) in phase two come to the ground and mob the players. They should stay in the air and only throw bombs.

I fixed this by disabling their movement but that's probably a bit too hacky.

boss_jeklik.cpp - line 211
+ me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE|UNIT_FLAG_DISABLE_MOVE);

Bloodlord Mandokir (11382) Isn't reseting properly after a party wipe. He keeps his enrage if you'd killed Oghan and he was only resetting his kill count if he was at the top of the ziggurut he starts on (z>140)

```
@@ -104,13 +104,13 @@ class boss_mandokir : public CreatureScript
             {
                 if (me->GetPositionZ() > 140.0f)
                 {
-                    
-                    killCount = 0;
                     events.ScheduleEvent(EVENT_CHECK_START, 1000);
                     if (Creature* speaker = ObjectAccessor::GetCreature(*me, instance->GetData64(NPC_VILEBRANCH_SPEAKER)))
                         if (!speaker->IsAlive())
                             speaker->Respawn(true);
                 }
+                killCount = 0;
+                instance->SetBossState(DATA_OHGAN, NOT_STARTED);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC|UNIT_FLAG_IMMUNE_TO_NPC);
                 summons.DespawnAll();
                 me->Mount(MODEL_OHGAN_MOUNT);
```

**Expected behaviour**: 
As above, Venoxis should pull with the 4 snakes on his platform, Jeklik's phase 2 adds should stay in the air and through bombs and Mandokir shouldn't auto-enrage after a wipe where you killed Oghan.

**Steps to reproduce the problem**:

1. Enter Zul'Gurub
2. Attempt Venoxis (pulling one of the adds)
3. Get Jeklik to phase 2 and watch the bats
4. Engage Mandokir, kill Oghan then wipe and see he enrages immediately on your next attempt.

**Branch(es)**: master

**AC hash/commit**:  842ac4c

**Operating system**: Windows 10

**Modules**:  VAS Autobalance

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by pondaveia** [comment]
Can someone confirm this issue?

**Comment by Ragelezz** [comment]
Issue 2 and 3 still there. Still working on this ? @peti446
