### ISSUE TITLE
UBRS Stealthed mobs break stealth on aggro and random mobs are stealthed

### ISSUE THREAD

**Issue by patou01** [azerothcore/azerothcore-wotlk#8352]
### Current Behaviour

The mobs (eg blackhand assassin) drop stealth before running to you and fighting you when they aggro from range.

![image](https://user-images.githubusercontent.com/2592673/136597998-6a854bf9-d661-45c9-a928-57b2c1ae754e.png)

Other mobs, wearing plate and a shield, are walking around stealthed (and attack when removing GM), npc 10319. 

![image](https://user-images.githubusercontent.com/2592673/136597826-e80087a6-38b8-4a5e-b608-e72be639ad5d.png)

### Expected Blizzlike Behaviour

I expect they shouldn't drop stealth until they take damage or hit a player.
Plate wearers are also not capable of stealth, it's reserved to cats with their silent paws and rogues.

### Source

That's how other assassins work at least in TBC, so I'm not sure this was a general behaviour as I can't see a cheap shot or similar spell on them.

https://classic.wowhead.com/npc=10319/blackhand-iron-guard#abilities;mode:40player

### Steps to reproduce the problem

.go c 137979 

.go c 137990

### AC rev. hash/commit

9b1dc38c0371f711bab64161f28d8da5bd293095

### Operating system

win10

**Comment by temperrr** [comment]
I dont see the plate weares being stealthed, but I do indeed notice the assasins not attacking from stealth.

**Comment by temperrr** [comment]
Indeed found the sneaking plate wearer. Thanks for showing me patou!
