### ISSUE TITLE
Mux Manascrambler - Incorrect Dialogue

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8361]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2021

[Mux Manascrambler](https://tbc.wowhead.com/npc=16014/mux-manascrambler) shows two dialogue options that shouldn't be there.
![image](https://user-images.githubusercontent.com/36058236/136553472-7158cce7-bbd5-42d0-aa9b-2c9340e03bb0.png)
First option is from quest "Return to Deliana"
Second option is from quest "Hunting for Ectoplasm"

Tester: confirmed:

![WoWScrnShot_100921_160124](https://user-images.githubusercontent.com/81782124/136645445-ecc42918-f019-4758-a59e-59f345cfaa6f.jpg)

### Expected Blizzlike Behaviour

Dialogue options should only be there if you have the relevant quests and lost the quest item.

### Source

https://wowpedia.fandom.com/wiki/Mux_Manascrambler
https://tbc.wowhead.com/npc=16014/mux-manascrambler

### Steps to reproduce the problem

1.  .go c 23723
2.  speak with Mux
3.  you'll see both dialogue options even though you don't have either of the quests

checked on clean build of AC and issue present there as well
![image](https://user-images.githubusercontent.com/36058236/136557466-9a745a6f-0047-4be9-ac2d-c6b7550b7915.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Win10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
And also gossips exist, but doesn't work. even if relevant quest active.

**Comment by Shineslippers** [comment]
Can we get some fix to it because of https://github.com/chromiecraft/chromiecraft/issues/2448

Gossips doesn't work.

Wowhead [Extra-Dimensional Ghost Revealer](https://www.wowhead.com/item=22115/extra-dimensional-ghost-revealer#comments:id=5394)
> By pigmonkey on 2006/12/03 (Patch 1.12.1)
If you ever drop or lose your revealer, just pay a visit back to Mux Manascrambler in Tanaris and he will provide you with another.
Last edited by Skosiris on 2010/03/07 (Patch 3.3.2)
