### ISSUE TITLE
Feature: GM clear inventory command

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#8365]
### Describe your feature request or suggestion in detail

When testing, I often find myself in a situation, where I have full bags and I don't want to delete every item one by one. Especially, when the items are blue or above, and I have to type "delete" each time.
I'm sorry, if there already is such a command or solution for it. If not, it would be nice, to have something like this implemented.

Implement a GM feature to clear the (own) inventory to get bag space.
For example, there could be multiple instances of that command:

`.clear inv hard` = Deletes all items from the inventory (maybe not hearthstone)
`.clear inv med` = Only deletes items with Uncommon quality or below and keeps quest items
`.clear inv soft` = Only deletes gray and white items and keeps quest items

**Comment by Azcobu** [comment]
Well, this macro will nuke everything, including hearthstone:
```
/run for b=0,4 do for s=1,36 do n=GetContainerItemLink(b,s);if n then PickupContainerItem(b,s);DeleteCursorItem();end;end;end;
```
If I was going to use it for real I'd probably set the for loop to skip one of the bags and keep stuff you want to preserve in that one. For a slightly more nuanced approach there's some more selective macros [here](https://www.thebuddyforum.com/threads/req-macro-del-all-gray-item-in-bag-wow.124891/) although they don't preserve quest items.
