### ISSUE TITLE
crash 20211009

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#8374]
### Current Behaviour

crash logs

https://gist.github.com/mpfans/8498c1b077b8d818e6594a526a944c0c

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/8ef6355aadc7b6c3240904237093c91858b74344  + PR 8219 +PR 7851

### Operating system

ubuntu 20.04

**Comment by mpfans** [comment]
crash again

https://gist.github.com/mpfans/75e49325f2b136ddfe256c8b41875eb3

**Comment by Nyeriah** [comment]
For reference, I advise trying https://github.com/azerothcore/azerothcore-wotlk/pull/8322/files

The same crash will also show up in other places, like here: https://github.com/azerothcore/azerothcore-wotlk/issues/8321

**Comment by mpfans** [comment]
updated #8376 crash again

https://gist.github.com/mpfans/1ee284f7d905c2882e8e6658aae32a7d
