### ISSUE TITLE
Bleeding Hollow Tormentor casts Fear on himself

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/azerothcore-wotlk#838]
**Description**:
The ability "Fear" of the Bleeding Hollow Tormentor is not working correctly.

**Current behaviour**:
The Bleeding Hollow Tormentor (NPC 19424) on Hellfire Peninsula casts his ability "Fear" (Spell 33924) on himself if more than 1 attacker is involved.

**Expected behaviour**:
According to table "smart_scripts" he should cast Fear on the second entry in the threat list.

**Steps to reproduce the problem**:
Attack the NPC with more than 1 attacker (tested with a pet).

It can be fixed by assigning another spell which does the same, e.g. 12542:
`update smart_scripts set action_param1 = 12542 where entryorguid = 19424 and action_param1 = 33924;`
But this doesn't explain why the default spell 33924 for this NPC is not working.

**Branch(es)**: master

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/783003f0e8d4e51f1f8afbabbacd5c2b292f6fb2

**Operating system**: Ubuntu 16.04

**Modules**:
https://github.com/azerothcore/mod-vas-autobalance
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster

**Other Customizations**: none

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by h0lysp4nk** [comment]
That definitely sounds weird, as you said changing the SPELLID to another Fear SPELLID fixes the problem. So could it possibly be that the default SPELLID is specifically targeting himself? I am pretty sure that some abilities do that.

I would suggest using a different Fear SPELLID that has the same duration.
