### ISSUE TITLE
Shadowmourne  Proc Mechanic Cooldown 30 Second 

### ISSUE THREAD

**Issue by Algorak** [azerothcore/azerothcore-wotlk#8389]
### Current Behaviour

Hello dear Devs, at the moment there is a bug that causes problems for shadowmourne players. As soon as you change your weapon as a warrior, paladin or death knight, Shadowmourne gets a 30 second cooldown on the soul fragment mechanics.

When exchanging trinkets and weapons outfight, procctrinkets and weapon effects such as trauma, SM, Val'Anyr etc. should not fall on IGCD.W

Infight, Proccs of weapons like SM / Trauma / Val'Anyr should not have an IGCD when changing weapons, but here they do.
If you play with Krieger, for example, with SM and go for Reflect in Shield / 1h, then afterwards the shadow fragment of SM doesn't proc for 30 seconds, which shouldn't be.
As a result, SM is much weaker than normal in classes with weapon changes.

But that shouldn't be this cooldown should only affect jewelry that can be activated.

Furthermore, I would ask you to check whether the following spells trigger the fragments correctly
https://gyazo.com/c8dbb462776a8350998c8149c00c3108
https://wowwiki-archive.fandom.com/wiki/Shadowmourne

### Expected Blizzlike Behaviour

Correct behavior should be that the soul fragments disappear when changing weapons and immediately pile up again when the weapon is armed

https://www.youtube.com/watch?v=yXJkrIygXXs
Here you can see the stack behavior with the Paladin. offi!

And here Warrio Offi!
https://youtu.be/hKGuz3azzcY?t=61 
The warrior changes his Sm to his one-handed and shield combo changes back to his Sm during the Bladestorm and stacks directly with the whirlwind without having to cooldown for 30 seconds. You can see when the player arrives that he has 4 stacks!

### Steps to reproduce the problem

Put on SM and do autohits you will see you do not get the stacks immediately, change your weapon to no matter which one and which one you only get his fragment after 30 seconds.

### Operating system

Windows 10

**Comment by Algorak** [comment]
?!

**Comment by Algorak** [comment]
no one ?!

**Comment by Kitzunu** [comment]
You are using a core that is a year old. Update and test again.

Until then I don't think anybody will look at it

**Comment by Algorak** [comment]
It is a pity that the ticket is no longer paid attention to. The core needs a lot of important fixes ... And things like Npcs drop wrong items or ores and plants appear wrong are not core elements ..

Bosses who have wrong Dmg values ​​or generally run wrong on the core are sometimes simply ignored xD ... so also the bug that air battle cannons only do 940 dmg instead of 1500 dmg. And things like the monstro at Prof who generally doesn't do the damage it should do and let alone that it doesn't even make car hits ...

**Comment by laasker** [comment]
can confirm it happens for me aswell

commit https://github.com/azerothcore/azerothcore-wotlk/commit/03c470d8bb6b

**Comment by Algorak** [comment]
Push Push @Kitzunu ?!

**Comment by Algorak** [comment]
@Kitzunu  hat man sich das Problem schon angeguckt wie gesagt 03c470d hat das selbe Problem.

**Comment by Algorak** [comment]
Push Push @Kitzunu

**Comment by Kitzunu** [comment]
closed in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/19030
