### ISSUE TITLE
Crash at Dynamic/LinkedList.h

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#8405]
```
0x0000000000b722de in LinkedListElement::hasNext (this=0x154e13cfa548) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Dynamic/LinkedList.h:27
27	    [[nodiscard]] bool hasNext() const { return (iNext && iNext->iNext != nullptr); }
#0  0x0000000000b722de in LinkedListElement::hasNext (this=0x154e13cfa548) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Dynamic/LinkedList.h:27
#1  LinkedListElement::next (this=0x154e13cfa548) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Dynamic/LinkedList.h:31
#2  Reference<Unit, ThreatMgr>::next (this=0x154e13cfa540) at /root/env/chromiecraft/azerothcore-wotlk/src/common/Dynamic/LinkedReference/Reference.h:73
#3  HostileReference::next (this=0x154e13cfa540) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Combat/ThreatMgr.h:96
#4  HostileRefMgr::deleteReferences (this=<optimized out>, removeFromMap=true) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Combat/HostileRefMgr.cpp:108
#5  0x0000000000ff6f84 in Map::RemovePlayerFromMap (this=0x1551550f2440, player=0x154e72902ac0, remove=false) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/Map.cpp:885
#6  0x0000000000c953bc in Player::TeleportTo (this=0x154e72902ac0, mapid=<optimized out>, x=<optimized out>, y=<optimized out>, z=<optimized out>, orientation=<optimized out>, options=<optimized out>, target=<optimized out>, newInstance=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Player/Player.cpp:1505
#7  0x0000000000f74391 in WorldSession::HandleAreaTriggerOpcode (this=0x154e2eb31600, recv_data=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/MiscHandler.cpp:811
#8  0x00000000010c68e6 in WorldSession::Update (this=0x154e2eb31600, diff=18, updater=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:340
#9  0x0000000000ff5cde in Map::Update (this=0x1551550f2440, t_diff=0, s_diff=18) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/Map.cpp:732
#10 0x000000000101270c in MapUpdateRequest::call (this=0x154e5942a5c0) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:31
#11 0x000000000101209a in MapUpdater::WorkerThread (this=0x1ce3010 <MapMgr::instance()::instance+216>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:146
```

### AC Version

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Kitzunu** [comment]
Why close?

**Comment by FrancescoBorzi** [comment]
the problem was already solved, but we were a bit behind with the AC rev
