### ISSUE TITLE
[NPC] Venomhide Hatchling size

### ISSUE THREAD

**Issue by Ragelezz** [azerothcore/azerothcore-wotlk#8409]
### Current Behaviour

Original report https://github.com/chromiecraft/chromiecraft/issues/1965

Venomhide Hatchling doesn't "increase" in size (change model) with Venomhide Baby Tooth's count (47196).

### Expected Blizzlike Behaviour

He should ground depending on how many baby tooth's you have.
Since people are saying different values of that item we can take as assumption this calculation:
- ( X < 6 ) = Baby
- ( X >= 6 and X < 11 ) = Bigger baby with reptile eyes
- ( X >= 11 and X < 16 ) = Adolescent raptor
- ( x >= 16 ) = Full-grown raptor

And some pictures for every stage:
baby---baby size, no picture needed, this is the first model tho
bigger baby with reptire eyes - [difference here](https://wow.zamimg.com/uploads/screenshots/normal/141101-they-grow-up-so-fast.jpg).
adolescent raptor - [like this](https://wow.zamimg.com/uploads/screenshots/normal/141296-venomhide-hatchling-venomhide-raptor-hatchling-day-11.jpg).
full-grown raptor - like any normal venomhide raptor in ungoro or around azeroth

### Source

https://github.com/chromiecraft/chromiecraft/issues/1965 comments from various sources inside this report

### Steps to reproduce the problem

.quest add 13906 and spawn him via quest item and add 47196 x18 for example, use the item again to make him despawn and spawn him after, no changes in his model.

### AC rev. hash/commit

local server

### Operating system

8.1

**Comment by Shineslippers** [comment]
There is something happend to this fix. https://github.com/chromiecraft/chromiecraft/issues/2473

### Current Behaviour

[Venomhide Hatchling](https://wowgaming.altervista.org/aowow/?item=46362). 3rd and 4th evolution is too big right now. 

<details><summary>Spoiler</summary>

![WoWScrnShot_120521_091233](https://user-images.githubusercontent.com/85256266/144735941-4c3bb97d-cddf-4b40-9936-46a6f45a357c.jpg)
![WoWScrnShot_120521_091251](https://user-images.githubusercontent.com/85256266/144735944-b82aaf25-5bd3-42e8-b2f1-de91b35fab1a.jpg)
![WoWScrnShot_120521_091307](https://user-images.githubusercontent.com/85256266/144735947-dcad0a6d-72f7-442d-bf2f-72d9d80728f0.jpg)
![WoWScrnShot_120521_091316](https://user-images.githubusercontent.com/85256266/144735949-3af5c5d9-cd64-4485-89ac-beb0e5dbfbc5.jpg)

</details>

### Expected Blizzlike Behaviour

<details><summary>Spoiler</summary>

![123](https://wow.zamimg.com/uploads/screenshots/normal/141296-venomhide-hatchling-venomhide-raptor-hatchling-day-11.jpg)
![qweqw](https://wow.zamimg.com/uploads/screenshots/normal/176576-venomhide-hatchling.jpg)

</details>
