### ISSUE TITLE
The "Tauren Chieftains" band in Blackrock Depths is missing.

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#8411]
### Current Behaviour

No drums setup in BRD, and no band playing at 8:00 

### Expected Blizzlike Behaviour

Every night at 8:00 PM server time, The Tauren Chieftains perform a five-minute concert inside Blackrock Depths' Grim Guzzler. Anyone who has  [Direbrew's Remote] from the Brewfest event can trigger a performance here at any time by talking to the roadie in charge, [Ognip Blastbolt](https://wowpedia.fandom.com/wiki/Ognip_Blastbolt).
https://youtu.be/BlrkSmyIQXo

Doing a /cheer to any band member will give you the `Pumped up` buff (42741) that increases starts for 5 min 

### Source

https://wowpedia.fandom.com/wiki/Elite_Tauren_Chieftain
https://wowpedia.fandom.com/wiki/Patch_2.4.3_(undocumented_changes) under NPCs
https://tbc.wowhead.com/npc=23619/bergrisst
https://tbc.wowhead.com/spell=42741/pumped-up#comments

### Steps to reproduce the problem

1. .go c 46625
2. Notice no drums, no roadies, no performance.

### AC rev. hash/commit

198552766ddb

### Operating system

windows 10

**Comment by heyitsbench** [comment]
Getting a sniff for this as well as a recording.
