### ISSUE TITLE
Magic shields not absorbing instant magic damage

### ISSUE THREAD

**Issue by jmdha** [azerothcore/azerothcore-wotlk#8412]
### What client do you play on?

esES

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2053

The skill Power Word: Shield of the priest not absorb magic demage in various mobs

Tester: Confirmed. No "Magic" shield absorb any instant magic damage. Tested both priest and mage: [PWS](https://tbc.wowhead.com/spell=17/power-word-shield), [IB](https://tbc.wowhead.com/spell=17/power-word-shield) and [MS](https://tbc.wowhead.com/spell=1463/mana-shield).
@Gloomy-priest adds video demonstration [here](https://drive.google.com/file/d/1JJNqfG--Wd11QLmf9FcJ8s8aWeV_0BEl/view?usp=sharing).

@Shineslippers adds:
> Even combat text and combat log saying it's absording while it doesn't
![image](https://user-images.githubusercontent.com/53914190/136725285-e906b5a7-812f-49e7-a20b-088129d1e0ca.png)

@RolyNuki adds:
> It seems to be a bug with all absorb shields. On my mage anything other than a basic auto attack is going through all my shields.Ice Barrier, Mana Shield, and all my elemental wards. Even just ranged shots from npcs are going through the same way, dealing damage to my HP as well as my shield, though my shield is breaking after 'absorbing' the correct amount of damage.
Edit: Tested a little more, damage over time effects seem to absorb properly, though any kind of 'hit' other than a basic auto seems to be going through.

The above I have confirmed on local AC. Seen below:
![image](https://user-images.githubusercontent.com/53914190/136725615-99a00629-cd12-4a67-84f2-842554194864.png)
![image](https://user-images.githubusercontent.com/53914190/136725844-ce672137-5de9-4ff6-842f-e69525bdb55c.png)

I have also confirmed that damage over time, which get correctly absorbed.

### Expected Blizzlike Behaviour

The skill Power Word: Shield absorb all damage, physical and magical

Tester note:
@Gloomy-Prist adds:
> [This page](https://tbc.wowhead.com/spell=17/power-word-shield) does have it state is absorbs all schools of magic and lists them in the spell details table when you scroll down. I did play during retail wrath and it did absorb all types of damage. The tooltip in the game also doesn't specify only physical damage while things like [Hand of Protection](https://www.wowhead.com/spell=66009/hand-of-protection) do specify physical only.

@Daedalus007 adds:
>Here's your proof, from the wowpedia page:
>>Patch 1.6.0 (2005-07-12): Damage absorption now absorbs damage from mana burn effects like Lava Shield.

>Spell damage should be absorbed, not just physical. Any school of magic. Again on the same page this doesn't prevent the debuff portion from getting through (silence, slow, stun, etc) with an exception for preventing 'Dazed'.

>>Power Word: Shield absorbs damage only. Most other effects attached to a damaging attack, such as a debuff that the attack applies or a spell interrupt will ignore the shield even if the attack deals no damage. Exceptions are [Dazed] effects from being attacked from behind and spell pushback, which are both prevented.

>I hope this bug is fixed; kinda glad I didn't roll a Priest right away.

All sources also in Source

### Source

https://tbc.wowhead.com/spell=17/power-word-shield
>Apply Aura: Absorb Damage (Arcane, Fire, Frost, Holy, Nature, Physical, Shadow)

https://tbc.wowhead.com/spell=27131/mana-shield
>Apply Aura: Absorb Damage - Mana Shield (Arcane, Fire, Frost, Holy, Nature, Physical, Shadow)

https://tbc.wowhead.com/spell=11426/ice-barrier
>Apply Aura: Absorb Damage (Arcane, Fire, Frost, Holy, Nature, Physical, Shadow)

https://wowpedia.fandom.com/wiki/Power_Word:_Shield?oldid=2562574
>Patch 1.6.0 (2005-07-12): Damage absorption now absorbs damage from mana burn effects like Lava Shield. 

>Power Word: Shield absorbs damage only. Most other effects attached to a damaging attack, such as a debuff that the attack applies or a spell interrupt will ignore the shield even if the attack deals no damage. Exceptions are [Dazed] effects from being attacked from behind and spell pushback, which are both prevented.

### Steps to reproduce the problem
1. Get two characters in duel
2. One of them have a shield e.g. spell Mana Shield (```.learn 43020```)
3. Get the other to cast any instant magic damage i.e. not DOT

### Extra Notes

None

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by mpfans** [comment]
`Power Word: Shield`  same bug

**Comment by 55Honey** [comment]
Not saying it's right or wrong, but we're going to need a new issue with a blizzlike source for it, if it's a bug.
