### ISSUE TITLE
[Wetlands] Mottled Screechers' call for help gets ignored by fellow raptors

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#8417]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2024

The Mottled Screechers in Wetlands call for help once they are low on health.

While the respective emote gets displayed in chat...

_Mottled Screecher lets out a high pitched screech, calling for help!_

...the call itself apparently gets completely ignored by their fellow raptors.

It's possible that other kinds of raptors who share the ability to call for help may also be affected.

**Testers note:**
The call for help works, but the range is very short! If you fight them on the appropriate level (around lvl 25), you would aggro them nonetheless and if you pull one out, the others do not notice.

### Expected Blizzlike Behaviour

Nearby raptors should heed the call for help and aggro the player.

### Steps to reproduce the problem

1. Engage a Mottled Screecher in Wetlands close to one of their fellow raptors.
2. Notice that once they are low on health they will call for help (emote!), but nearby raptors won't aggro the player.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Ragelezz** [comment]
https://www.wowhead.com/npc=41342/mottled-screecher are we talking about this, right ? Added in patch 4.0.1.12984

**Comment by Ragelezz** [comment]
confirmed, also there is no spell at all, just a smart_script which should have handled this but.. didn't worked, moved the script into c++ and its fine. If there are more "call for help" issues make a new topic.

**Comment by T1ti** [comment]
all you have to do is replace last action invoker by self
![image](https://user-images.githubusercontent.com/40864460/137638556-f202abe5-b27e-4e75-9301-cb116aa6f46e.png)

```
 -- Mottled Screecher smart ai
SET @ENTRY := 1021;
DELETE FROM `smart_scripts` WHERE `source_type` = 0 AND `entryOrGuid` = @ENTRY;
UPDATE `creature_template` SET `AIName` = 'SmartAI', `ScriptName` = '' WHERE `entry` = @ENTRY;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(@ENTRY, 0, 0, 1, 2, 0, 100, 1, 0, 20, 0, 0, 39, 20, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'When health between 0%-20%% (check once) - Self: Call for help within 20 yards'),
(@ENTRY, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'When health between 0%-20%% (check once) - Self: Talk 0 to invoker');
```

**Comment by Ragelezz** [comment]
I saw 20% :-? 
SAI is not really my thing so.. :v
