### ISSUE TITLE
Minions and pets from Mobs not despawning after their master is dead

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#8419]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1995

Ok, I might be wrong on this, but never saw or expected this behavior before.
There have been several reports concerning Voidwalkers and other minions from mobs, mostly about how they don't attack players unless directly attacked or how they agro and follow beyond the boundaries of the map.
I've been experiencing another big issue about them, and it's the fact that **they stay alive and attacking us even after their masters are dead**. This has been tested on low lvl areas such as The Barrens as well as some from last brackets, such as Blasted Lands.

This level 12 Razormane wolf is still alive and attacking even after the hunter is dead.
![ 2021-09-27 at 21 43 09](https://user-images.githubusercontent.com/77953030/136076328-a0f610b4-9f16-463c-b2b3-8aa3c215f991.png)

This warlock lvl 22 is dead but his imp is still alive and attacking.
![ 2021-09-23 at 10 44 16](https://user-images.githubusercontent.com/77953030/136076510-ac48d78c-7dd4-4bf6-a78b-42dfad3c91cc.png)

Here image I have on target the dead warlock level 53, yet his pet is still alive and attacking me.
![ 2021-10-05 at 11 07 24](https://user-images.githubusercontent.com/77953030/136076069-c7298615-4990-49e7-9347-0aab5e59d7d5.png)

### Expected Blizzlike Behaviour

Minions and pets should despawn / disappear after their master/summoner is dead.

### Source

I have trouble finding a specific source for this, but I NEVER saw this behavior happening.
So far I found this on official Classic forums that confirm that pets despawn shortly after being hit, but I will try to find something better.

![ 2021-10-06 at 08 37 29](https://user-images.githubusercontent.com/77953030/136148038-77bbc837-705a-4c5c-b2ca-6de548f84f18.png)

### Steps to reproduce the problem

Face an enemy who controls a minion / pet
Focus and kill summoner/master instead of minion / pet
Pet will remain summoned / alive and will follow you and attack you

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

This definitely happens on Chromiecraft, but I'm not 100 % sure, what the intended behavior here is, so I'm putting it here to discuss it first. Shuguen (see source above) might be right with his comment for all that I know.

**Comment by T1ti** [comment]
https://wowdev.wiki/DB/SummonProperties

despawning when owner dies is actually a flag in summonproperties.dbc, which ilmplies they should obviously not despawn by default, resolved.

**Comment by heyitsbench** [comment]
For the record on Wrath Classic, it seems that killing e.g. a succubus minion and shadowmelding, the succubus runs to the summoner (where it would go if the summoner were still alive) and then despawns. This may need to be looked into again.
