### ISSUE TITLE
Stop The Fires & Let The Fires Come gold reward too high

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#8440]
### Current Behaviour

Reward for completing these quests is stuck at 7g 40 s (which is level 79 gold reward)

### Expected Blizzlike Behaviour

Reward should scale between 35s to 7g 40s depending on (edit: Character!) level

### Source

https://wowpedia.fandom.com/wiki/Stop_the_Fires!_(Alliance)
https://wowpedia.fandom.com/wiki/Stop_the_Fires!_(Horde)

### Steps to reproduce the problem

1. event start 12
2. .tele kharanos
3. Take event quest
4. complete event (is bugged now) (.quest complete 11131 (for alliance) .quest complete 11219 (for horde)
5. notice u gain a lot of gold.

### Extra Notes

Quest IDs 11131, 11219, 12135, 12139

### AC rev. hash/commit

 bc451d2ec

### Operating system

W11

### Custom changes or Modules

None

**Comment by temperrr** [comment]
apparently we need to figure out what the formula is for the gold reward per character level. Anyone has some info on that?

**Comment by Stump876** [comment]
One thing I think I should note. `Let the fires come` should not be acceptable from players under level 10. `Stop the fires` is 1-80 but the rewards stay the same which can't be correct. It doesn;t make sense that level 1 gets 35s and level 10 also gets 35s depending on the quest they accepted.

I can find nothing on the algorithm, gold reward seems to be all over the place.  Source above says 35s-7g 40s. Which I'm assuming is the base gold reward, as level 80 gives 13g 23s total
Wowhead says:
![image](https://user-images.githubusercontent.com/68164076/137602105-ef8308f1-f76d-433d-8166-a679ada207d5.png)
![image](https://user-images.githubusercontent.com/68164076/137602114-cb6d01a8-cf4b-46e1-a997-afb56f704ee7.png) 
Depending on which quest you look at, horde or alliance. I believe this was based on the level of the person reporting it to wowhead. 

[TBC wowhead](https://tbc.wowhead.com/quest=11131/stop-the-fires) has this
![image](https://user-images.githubusercontent.com/68164076/137603422-e89d9dfe-47ec-4838-a355-aac87cff394d.png)
But TBC had it's horseman on a 4 hour timer with no 'Let the fires come' quest to summon. I don't believe this is accurate for Wrath

Video [here, 5 seconds in,](https://youtu.be/vvQNsd03nEk?t=5) has a reward of 90s at level 58, but not fom 3.3.5
[This one](https://youtu.be/PkEckJDayEg?t=99) has a reward of 75s at level 52 but also not from 3.3.5

The quest is available at 10 and rewards 35s,  80 reward is 7g40s (plus bonus G for max level) The math doesn't really add up. 
 (7g40s00c) 74000/80= 9s 25c per level, meaning level 10 would give you 92s 50c. Going the other way 35s00C 3500/10= 3s50c per level. Neither is correct. I believe the gold per level increases as the player levels. 

I have a solution, though I doubt it's blizzlike, and it's better than guessing. I'd like to see if you agree.
`TLDR take the players level -10, then multiply that by 1007.142857142857 then add 3500 that will equal the amount of coin in copper to give` The breakdown is below.

Doing it percetange 0 being 3500 and 100% being 74000
74000-3500= 70500.  70500/70=1007.142857142857, roughly 10s07c. This should equal coin gained per (level-10) +3500 the level 10 minimum coin gained. Level 80 would get an additonal 58300 added for the exp bonus
 so:
level 1 to 10 = 0 +3500= 35s 00c
level 11= 1x1007.142857142857 then +3500= 4507.14857   45s 07c
level 20= 10x1007.142857142857 then +3500= 13571.429  1g 35s 71c
level 29= 19x1007.142857142857 then +3500= 22635.71   2g 26s 35c (see wowhead reward)
level 35= 25x1007.142857142857 then +3500= 28678.57  2g 86s 79c
level 52= 42x1007.142857142857 then +3500= 45799.99  4g 58s 00c
level 65= 55x1007.142857142857 then +3500=58892.857   5g 88s 93c (see wowhead reward)
level 79= 69x1007.142857142857 then +3500= 72992.857   7g 29s 93c
level 80= 70x1007.142857142857 then +3500 = 73999.99   7g 40s 00c Plus max level G bonus

Feel free to not use, I'm not going to be insulted. I don't claim this to be the right formula, but I think it gets us within a few silver, of repored amounts, and it's better than dishing out the max G per quest. I just hate not have *some* kind of solution.

**Comment by UltraNix** [comment]
Okay. I checked `QuestMoneyReward` from higher expansion and got 100% correct data. I will adapt and implement that dbc file to quest with QuestLevel = -1.

**Comment by Stump876** [comment]
Was I even close?

**Comment by UltraNix** [comment]
More or less.
