### ISSUE TITLE
Lock and Load No longer procs from Explosive Trap, Immolation Trap, or Black Arrow.

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8457]
### Current Behaviour

After PR #8177 Lock and Load No longer procs from Explosive Trap, Immolation Trap, or Black Arrow.

### Expected Blizzlike Behaviour

 Lock and Load should procs from Explosive Trap, Immolation Trap, or Black Arrow.
It has 2%/4%/6% chance

### Source

src/server/scripts/Spells/spell_hunter.cpp L1392

### Steps to reproduce the problem

Use a hunter and test Explosive Trap, Immolation Trap, or Black Arrow.
You can see Lock and Load never proc

### AC rev. hash/commit

cb19dbf

### Operating system

Windows 10 x64

**Comment by Nyeriah** [comment]
@bgcfb I understand, but it's related to the same issue and it'll be fixed by the same thing, could you please check https://github.com/azerothcore/azerothcore-wotlk/pull/8441/files and see if the issue you've encountered still persists?
