### ISSUE TITLE
Cannot complete quest 1960 "Investigate the Alchemist Shop"

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/azerothcore-wotlk#846]
**Description**:
The mage only quest 1960 "Investigate the Alchemist Shop" is currently broken.

**Current behaviour**:
Cannot use item 7247 (Chest of Containment Coffers) on a stunned rift spawn ("You can't do that yet").

**Expected behaviour**:
Get a filled containment coffer after using the item on a stunned rift spawn.

**Steps to reproduce the problem**:
- get quest 1960 and take the items
- proceed to the Apothecarium, near the alchemist
- use "Cantation of Manifestation" and fight a rift spawn until it is stunned
- try to use "Chest of Containment Coffers" on the stunned rift spawn

This seems to also affect the Alliance version of the quest "Investigate the Blue Recluse" (1920). See https://github.com/azerothcore/azerothcore-wotlk/issues/70

**Branch(es)**: master

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/b449a5ab4a72f9ff1cde6554f3af42939fe23d69

**Operating system**: Ubuntu 16.04

**Modules**:
https://github.com/azerothcore/mod-vas-autobalance
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster

**Other Customizations**: none

**Comment by Motorheadx** [comment]
https://pastebin.com/Mn1v2Zg2

**Comment by BarbzYHOOL** [comment]
ty motorheadx, but why not making a pull request? We have a guide on the wiki and I can help you if you want on the discord

**Comment by Motorheadx** [comment]
we must do better than this hack and at the core they are so many

**Comment by Stoabrogga** [comment]
I've tested this and it works fine. Should I create a pull request for this? Or just ignore it because it's a hack... I personally prefer working quests, no matter if it's a hack or not. So far it seems nobody could fix it in a better way, the issues on Trinitycore are still open.

**Comment by Motorheadx** [comment]
well I'll make the request

**Comment by Stoabrogga** [comment]
Great, thanks. If there's a better solution in the future it should be easy to revert these changes.

**Comment by Motorheadx** [comment]
=))

**Comment by Stoabrogga** [comment]
Hey, hope dies last ;-)
