### ISSUE TITLE
Divine Shield not preventing damage from lightning shield

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#8461]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2076

Lightning Shield damages through Divine Shield on Dust Stormer mob in Silithus

![WoWScrnShot_101221_195428](https://user-images.githubusercontent.com/92397743/137013896-997fc07a-ddd0-4bc2-bcbf-21d3af762008.jpg)

Tester: Confirmed AzerothCore rev. 792b99c
Dust Stormers (https://wowgaming.altervista.org/aowow/?npc=11744)  Lightning shield (https://wowgaming.altervista.org/aowow/?spell=19514#used-by-npc) damages through divine shield

![dshield](https://user-images.githubusercontent.com/80769357/137026416-22fca89a-d005-46b9-9538-9051daa5613e.jpg)

### Expected Blizzlike Behaviour

No damage should go through Divine Shield

### Source
Skill description. (https://wowgaming.altervista.org/aowow/?spell=642)

### Steps to reproduce the problem

Aggro Dust Stormer (entry 11744)
Use Divine Shield
Attack Dust Stormer

### Extra Notes

My discord's username is Frxd and so is my character's name, ya'll can contact me

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nefertumm** [comment]
This is a general issue with immunities... We should partially port some of this
https://github.com/TrinityCore/TrinityCore/commit/50a3ce5703bdaa4fe16e2e773eabafa9a4818083
https://github.com/TrinityCore/TrinityCore/commit/ca1c4525c7da320da2c0a55bfd803879e3cf60b2
