### ISSUE TITLE
[Quest NPC] "Dirty" Michael Crowe in Theramore stuck in continuous animation loop

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#8462]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2077

"Dirty" Michael Crowe in Theramore seems to be stuck in a continuous "enrage" animation loop.

I looked up some photos and Youtube videos starring him and - while I couldn't find any as old as WotLK - none of them showed him doing this strange animation. 

Instead he's always shown in an idle position, facing the harbor.

Tester: Confirmed AzerothCore rev. 792b99cbc9a6
"Dirty" Michael Crowe (https://wowgaming.altervista.org/aowow/?npc=23896) gets stuck in animation loop after you talk to him. You can accept/turn in quest and use him as a vendor, but he is constantly doing the animation.

https://user-images.githubusercontent.com/80769357/137029230-12b618ba-f0c7-4a7d-af7a-3ccb1c5d0805.mp4

### Expected Blizzlike Behaviour

He should probably just be standing in an idle position, facing the harbour.

### Source

https://www.youtube.com/watch?v=Kfbb8nMfnsM
https://www.youtube.com/watch?v=9lWHH0YlvJ4
https://www.youtube.com/watch?v=qafE35zsRvU

### Steps to reproduce the problem

1. Stand near "Dirty" Michael Crowe in Theramore.
2. Watch him do his thing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

macOS Catalina + Wine

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
It's due to him having an action in one of his waypoints. (Pretty sure he shouldn't have any waypoints to begin with)
```sql
SELECT * FROM waypoint_data WHERE id=306490
```
