### ISSUE TITLE
server crash 20211013(low probability)

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8469]
### Current Behaviour

crash log: https://gist.github.com/bgcfb/0f3603ac92420af3ea7151f6b0897c6d

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

none

### AC rev. hash/commit

c8ff0bc

### Operating system

Windows 10 x64

**Comment by bgcfb** [comment]
Not crash for 72 hours,maybe it is low probability

**Comment by UltraNix** [comment]
@bgcfb Can be closed?

**Comment by bgcfb** [comment]
> @bgcfb Can be closed?

yeah,it did not crash again,close it
