### ISSUE TITLE
DB/Creature: Spiteful Apparition causing Error

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#848]
From Log:

2018-05-04 18:13:44 CRASH ALERT: Unit (Entry 36551) is trying to delete its updating MG (Type 5)!
2018-05-04 18:13:44 CRASH ALERT: Unit (Entry 36551) is trying to delete its updating MG (Type 1)!

**Description**: If i'm corect, NPC in FoS, once they activate and after u kill them, they try to delete for some reason. It's SmartAI, so would be nice to someone check it.

**Current behaviour**: Error every single time player kills NPC.

**Expected behaviour**: Script, SAI is kinda ok except last past when it tries to delete.

**Operating system**:  Linux

**Modules**:  Premium Module, Congrats on level.

**Other Customizations**: Nothing at all.

Hash: 7696bd3

**Comment by BarbzYHOOL** [comment]
You forgot the commit number

**Comment by Knindzagxg** [comment]
Debian 9
Forgot to mention that, soz.

**Comment by BarbzYHOOL** [comment]
and the commit hash?

you can see it with git log

**Comment by Deku** [comment]
Is this still an issue? Haven't had this problem in my server

**Comment by Knindzagxg** [comment]
Yeah, its still up - Every single time players kill this npc(s) in Forge of Souls.

**Comment by Motorheadx** [comment]
incomprehensibly

**Comment by pondaveia** [comment]
Can someone confirm this issue?

**Comment by poszer** [comment]
> 
> 
> Can someone confirm this issue?

Yes, confirmed on windows
http://prntscr.com/lfoa7n
