### ISSUE TITLE
Rank 1 Spell Lock Not Silencing Target

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8484]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2026

Warlock Felhunter pet ability Rank 1 [Spell Lock](https://tbc.wowhead.com/spell=19244/spell-lock#comments) is currently only interrupting spellcasting and not silencing the target.

I recorded a short video with demonstration: https://www.youtube.com/watch?v=KGab_piyI58

Tester: confirmed for Rank 1. The only other rank for Spell lock, rank 2 at lvl 52, seems to work fine.

For reference: correctly working Rank 2 Spell Lock looks like this from the target's view. Target is debuffed, silenced, and combat log shows 'is afflicted by'
![WoWScrnShot_101421_001953](https://user-images.githubusercontent.com/81782124/137148059-3cc1a181-044f-425d-975f-427b67dbc1a4.jpg)

Now rank 1 - no debuff shown, combat log does not show 'is afflicted by', target is able to cast spells with no problems:
![WoWScrnShot_101421_003224](https://user-images.githubusercontent.com/81782124/137148384-bd5a9b81-d7fa-4272-9b1e-ade7865aef91.jpg)

Target casting Frost Nova without any problems well within the 3 second silence. It does interrupt spell casting in progress though.
![WoWScrnShot_101421_004250](https://user-images.githubusercontent.com/81782124/137150500-a2bb0b54-61ad-4097-aa14-bce13ed4fdf3.jpg)

### Expected Blizzlike Behaviour

"Spell Lock" should silence it's target alongside interrupting current spellcast.

Current ability tooltip: https://i.imgur.com/acd4fhB.png
Wowhead comment talking about the silence effect: https://i.imgur.com/XA9w3tV.png

### Source

https://www.wowhead.com/spell=19647/spell-lock
+in game tooltip https://i.imgur.com/acd4fhB.png

https://wowpedia.fandom.com/wiki/Spell_Lock?oldid=2378800

### Steps to reproduce the problem

1. Cast Rank 1 "Spell Lock" on any target
2. Silence effect does not appear

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Artix OpenRC

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
Also https://github.com/azerothcore/azerothcore-wotlk/blob/92a7f8b5bd0c50d739b2166e2a26c0acebec2281/src/server/game/Spells/SpellEffects.cpp#L3745-L3747

This is how rank 2 is hack fixed
