### ISSUE TITLE
Boss Mimiron Ulduar

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#852]
Description: The script of Mimiron in Ulduar 10 and 25 man not work properly with Debian 9.4

Current behaviour:      Phase 1 : During the MKII phase , the script doesn't work , the boss doesn't use all abilities : Spell Plasma Blast , Shock Blast and Proximity Mines
                                    Phase 4 : The script doesn't work too because all abilities of the MKII and the VX-001 are missing and the 3 parts of the boss doesn't merge correctly , the lower part : MKII run and is not merged with he other parts.

Expected behaviour:      Phase 1 : The boss have to use all of these abilities during the fight.
                                       Phase 4 : The 3 parts of the boss must be merged , MKII must use the Shock blast and Proximity Mines , the VX-001 must use Hand-Pulse.

Steps to reproduce the problem:

1.  Go to Ulduar 10 or 25 Man
2.  Start Mimiron fight
3.  Problems occurs in P1 and P4

Branch(es):  master

AC hash/commit:  b449a5a

Operating system:  Linux Debian

Modules:  Mod-Transmog

Other Customizations: /

**Comment by Motorheadx** [comment]
This boss works fine, I can't confirm there's something wrong with him =))

**Comment by Dreaxxx** [comment]
I just try on Windows OS and work perfectly , but in Linux Debian , we have some problems.

**Comment by Viste** [comment]
work perfect cant confrim

**Comment by Motorheadx** [comment]
I checked this on Linux systems no problems found=)

**Comment by BarbzYHOOL** [comment]
Maybe retry carefully @Dreaxxx ?

**Comment by Dreaxxx** [comment]
Huuuum , okay , so i don't know why i'v this problem ... Probably an SQL modification ...
Thank's all for your reply

**Comment by BarbzYHOOL** [comment]
I think both testers are on Linux but not on Debian though

**Comment by boom8866** [comment]
Perfect job. No problem

**Comment by BarbzYHOOL** [comment]
Hmm many people said no issue, so I'll close it.
