### ISSUE TITLE
Various NPCs Incorrectly Dropping Blood of the Mountain

### ISSUE THREAD

**Issue by Edgardiez7** [azerothcore/azerothcore-wotlk#8530]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

<html>
<body>
<h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Current Behaviour</h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://wowgaming.altervista.org/aowow/?item=11382" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">Blood of the Mountain</a></p>

name | entry | chance
-- | -- | --
Firegut Brute | 7035 | 0,02
War Reaver | 7039 | 0,02
Scalding Broodling | 7048 | 0,02
Anvilrage Footman | 8892 | 0,02
Warbringer Construct | 8905 | 0,02
Fireguard Destroyer | 8911 | 0,02
Twilight's Hammer Torturer | 8912 | 0,02
Bloodhound | 8921 | 0,02
Krom'Grul | 8977 | 0,02
Molten Giant | 11658 | 0,02
Molten Destroyer | 11659 | 7,1259
Lava Annihilator | 11665 | 0,02
Firewalker | 11666 | 0,02
Firelord | 11668 | 0,02
Ancient Core Hound | 11673 | 0,02
Lava Reaver | 12100 | 0,02
Lava Surger | 12101 | 0,02

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Steps to reproduce the problem</h3><div class="highlight highlight-source-sql position-relative overflow-auto" style="box-sizing: border-box; position: relative !important; overflow: visible !important; margin-bottom: 16px; background-color: rgb(13, 17, 23); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><pre style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; margin-top: 0px; margin-bottom: 0px; overflow-wrap: normal; padding: 16px; overflow: auto; line-height: 1.45; background-color: var(--color-canvas-subtle); border-radius: 6px; word-break: normal;"><span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">SELECT</span> <span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">creature_template</span>.<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">name</span>, <span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">creature_loot_template</span>.<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">entry</span>, <span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">creature_loot_template</span>.<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">chance</span>
<span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">FROM</span> creature_loot_template <span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">JOIN</span> creature_template
<span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">ON</span> <span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">creature_loot_template</span>.<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">Entry</span><span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">=</span><span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">creature_template</span>.<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">lootid</span>
<span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">WHERE</span> <span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">creature_loot_template</span>.<span class="pl-c1" style="box-sizing: border-box; color: var(--color-prettylights-syntax-constant);">item</span><span class="pl-k" style="box-sizing: border-box; color: var(--color-prettylights-syntax-keyword);">=</span><span class="pl-s" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);"><span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span>11382<span class="pl-pds" style="box-sizing: border-box; color: var(--color-prettylights-syntax-string);">"</span></span></pre></div><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Extra Notes</h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><em style="box-sizing: border-box;">No response</em></p><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AC rev. hash/commit</h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e/hovercard" href="https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; font-weight: 400;">chromiecraft/azerothcore-wotlk@<tt style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">b2f0893</tt></a></p><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Operating system</h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Ubuntu 20.04</p><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Modules</h3><ul style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-ah-bot" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-ah-bot</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-cfbg" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-cfbg</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-chromie-xp" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-chromie-xp</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-desertion-warnings" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-desertion-warnings</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-duel-reset" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-duel-reset</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-eluna-lua-engine" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-eluna-lua-engine</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-ip-tracker" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-ip-tracker</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-low-level-arena" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-low-level-arena</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-multi-client-check" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-multi-client-check</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-pvp-titles" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-pvp-titles</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-pvpstats-announcer" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-pvpstats-announcer</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-queue-list-cache" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-queue-list-cache</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/azerothcore/mod-server-auto-shutdown" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">mod-server-auto-shutdown</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/Acore_CarbonCopy" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-carbon-copy</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/Acore_CustomWorldboss" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-custom-worldboss</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/Acore_LevelUpReward" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-level-up-reward</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/Acore_RecruitAFriend" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-recruit-a-friend</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/Acore_SendAndBind" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-send-and-bind</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/Acore_TempAnnouncements" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-temp-announcements</a></li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;"><a href="https://github.com/55Honey/acore_Zonecheck" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">lua-zonecheck</a></li></ul><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Customizations</h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">None</p><h3 style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Server</h3><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ChromieCraft</p>
</body>
</html>

### Link to ChromieCraft issue
https://github.com/chromiecraft/chromiecraft/issues/2090

**Comment by Santaria94** [comment]
I would also like to add that the droprate from "Dark Iron Deposit" is too high (5%).
Wowhead stats say droprate is approximately 0.8%. Comments generally confirm this:

От 4336 10.12.2006 (Обновление 2.0.1)		
They are mined from dark iron deposits and they have a drop rate of about 0.5%. Theyre used for rep with the Thorium Brotherhood, and for various Thorium Brotherhood recipes. Its also used for the enchanting recipe Smoking Heart of the Mountain.
