### ISSUE TITLE
[Quest/POI] Some Barrens quests opens Durotar's map despite being only in The Barrens.

### ISSUE THREAD

**Issue by Edgardiez7** [azerothcore/azerothcore-wotlk#8531]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
There are some quests that opens Durotar's map despite being in the Barrens from the beginning to the end.

https://wowgaming.altervista.org/aowow/?quest=890
The quest "The Missing Shipment" opens Durotar's map.

https://wowgaming.altervista.org/aowow/?quest=892
The second part of the quest "The Missing Shipment" also opens Durotar's map.

https://wowgaming.altervista.org/aowow/?quest=896
The quest "Miner's Fortune" opens Durotar's map, no matter if the objective has been completed.

https://wowgaming.altervista.org/aowow/?quest=888
The quest "Stolen Booty", when the objective is not completed, opens Durotar.
Collecting only the "Telescopic Lens" (5077) lets you click the "Show Map" to open Durotar, but you cannot see where is the "Shipment of Boots" (5076) unless you navigate.
When the objective is completed, it shows Durotar.

https://wowgaming.altervista.org/aowow/?quest=887
The quest "Southsea Freebooters", when the objective is completed, doing "Show Map" opens Durotar's map instead of The Barrens.

I have also found, in addition to the original post, that the samophlange quests behave the same way (opening Durotar map). IDs 894, 900, 901, 902. The last quest (id 3924) opens The Barrens map though, so thats weird.

### Expected Blizzlike Behaviour
Clicking "Show Map" should opens the map of The Barrens.

### Source
No response

### Steps to reproduce the problem
Get the mentionned quests.
Click "Show Map".

### Extra Notes
No response

### AC rev. hash/commit
chromiecraft/azerothcore-wotlk@b2f0893

### Operating system
Ubuntu 20.04

### Modules
mod-ah-bot
mod-cfbg
mod-chromie-xp
mod-desertion-warnings
mod-duel-reset
mod-eluna-lua-engine
mod-ip-tracker
mod-low-level-arena
mod-multi-client-check
mod-pvp-titles
mod-pvpstats-announcer
mod-queue-list-cache
mod-server-auto-shutdown
lua-carbon-copy
lua-custom-worldboss
lua-level-up-reward
lua-recruit-a-friend
lua-send-and-bind
lua-temp-announcements
lua-zonecheck
Customizations
None

### Server
ChromieCraft

### Linked ChromieCraft Issue
https://github.com/chromiecraft/chromiecraft/issues/2100

**Comment by Voxstrasza** [comment]
@Edgardiez7 please check out #9584
