### ISSUE TITLE
Algalon Reply Code Alpha

### ISSUE THREAD

**Issue by pe93** [azerothcore/azerothcore-wotlk#8535]
### Current Behaviour

When you kill algalon and get the Item Reply Code Alpha you cant get the quest form the object. It says you do not meet the requirements for this quest. 

### Expected Blizzlike Behaviour

Xou should be able to get the quest.

### Steps to reproduce the problem

Enter Ulduar 10 man
Kill Algalon 
Get the Item Reply Code Alpha

### AC rev. hash/commit

AzerothCore rev. b2f0893

### Operating system

Win 10 running server with docker

**Comment by Shineslippers** [comment]
[All Is Well That Ends Well](https://wowgaming.altervista.org/aowow/?quest=13631) require [Algalon](https://wowgaming.altervista.org/aowow/?quest=13614) and [Heroic: All Is Well That Ends Well](https://wowgaming.altervista.org/aowow/?quest=13819) require [Heroic: Algalon](https://wowgaming.altervista.org/aowow/?quest=13818).

Can't find anything what point to it. I guess it should not requare any pre-quest.
Wowhead [Heroic: All Is Well That Ends Well](https://www.wowhead.com/quest=13819/heroic-all-is-well-that-ends-well#comments:id=714754)
> By Tyrsenus on 2009/05/13 (Patch 3.1.1)
Defeat Algalon the Observer, enabling All Is Well That Ends Well.
