### ISSUE TITLE
Curses not affected by warlock talent contagion

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#8539]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2095

https://wowgaming.altervista.org/aowow/?spell=30064
This talent seems that don't reduce the chance of dispelling any affliction (helpful and damaging) spells

Tester: Semi-confirmed. It works as intended on magic debuffs, but not on curses. Tried dispelling curse of weakness 40+ tines with druid remove curse. Never failed.
Original reporter also mentioned dispell not failing on fear, but I couldn't reproduce this. (It failed to dispell)

### Expected Blizzlike Behaviour

Like is described on talent, at rank 5, the chance of dispelling any affly dot or buff on caster(like nightfal or eradication) have an additional 30% chace to fail

Testers note:
See [here](https://tbc.wowhead.com/spell=30060/contagion#modifies) for list of spells it should affect. It seems to be things of dispell type 'curse' that do not function, whereas things with dispell type 'magic' works as intended.

### Source

https://wowgaming.altervista.org/aowow/?spell=30064

### Steps to reproduce the problem
1. Have both a druid and warlock in pvp
2. Have druid try to dispell warlock curse of weakness, while they have the talent contagion
3. Currently the dispell never fails, while it should fail 30% of the time

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Closing this as it seems to be blizzlike.
