### ISSUE TITLE
Seasonal bosses can kill and gain loot indefinitely

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#8540]
### Current Behaviour

Through dungeonfinder seasonal bosses can kill and gain loot indefinitely

### Expected Blizzlike Behaviour

Everyone can only get booty once a day,If you don't get anything, you can only pick it up the next day

### Steps to reproduce the problem

1.event start 24
2.join dungeonfinder
3.killed boss
4.join dungeonfinder
5.killed boss
Repeat 2 and 3

### AC rev. hash/commit

3c42a7d72d374df3aede3bcf371c4bb22b0c563e

### Operating system

ubuntu 20.04

**Comment by UltraNix** [comment]
What? You can loot from corpses everytime you kill the boss.
Rewards from RDF are something different.

**Comment by temperrr** [comment]
It's a change I think that happened at patch 3.2 if I recall correctly
