### ISSUE TITLE
Close spawns of Copper Vein & Silverleaf

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#8541]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2105

There are currently 4 entities spawned. 

Tester: confirmed
![image](https://user-images.githubusercontent.com/53914190/137496985-bcaff7c3-1d95-4c51-b539-ca9c7cd610b1.png)

The GUIDs are for the silverleaf = (627, 1150) and the copper = (5080, 120294).

### Expected Blizzlike Behaviour

There should only be 2 entities spawned.

Testers note:
I think it's blizzlike for 2 to potentially spawn close, but the ores spawn everytime, which they shouldn't.
The herbs are already in pool 992, so those should either be moved or ignored.
The ores are not in a pool, so should be added to a pool, deleted (one of them) or moved

### Source

None.

### Steps to reproduce the problem

1.) Go to Tiragarde Keep 
2.) Get to the back of Keep and its Walls (near the ocean by the half sinked/ashored ship)
3.) You'll see the dupes. 

### Extra Notes

![unknown](https://user-images.githubusercontent.com/3145839/137478970-d6c8a8b2-1ade-42e1-ad25-41f8e59cde84.png)

Heres a screenshot.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
rev. 05161a9ffe5cd69832305657f17e0eaafda0c363
The GUIDs no longer exist and the spot is correctly pooled.
