### ISSUE TITLE
DB/Quest: Assault by Air

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#855]
**Description**: Quest is not working sadly, missing target SAI i think.

**Current behaviour**: Flying with plane working perfectly, but once u use spell (Suppresion Charge) on turrets, there is no quest progress. I tried to add invisible stalker for credit, but nothing happening.

**Expected behaviour**: SAI should be fixed, i'm not sure how at the moment.

**Operating system**:  Linux, Debian 9

**Modules**:  Premium and Congrats on level

**Other Customizations**: Not at all

Hash: 7696bd3

Link to quest - http://www.wowhead.com/quest=13309/assault-by-air#comments
Video from YT - https://www.youtube.com/watch?v=QocqIwmiMpk

**Comment by pondaveia** [comment]
Most likely the npc is missing a kill credit.

**Comment by Knindzagxg** [comment]
NPC is friendly i tried to add trigger under object, but nothing happens.

**Comment by poszer** [comment]
Can you try again this quest, i can complete both (A & H) without problem @Knindzagxg

**Comment by Helias** [comment]
any update? @Knindzagxg ?

**Comment by peti446** [comment]
Was able to use the spell correctly and it still completed the quest.

![image](https://user-images.githubusercontent.com/4162295/100788640-43b3ad00-340d-11eb-9cb5-318c48b7e838.png)

Tested on https://github.com/azerothcore/azerothcore-wotlk/commit/003fa8773144dede989e67448bd2ffdee5222d36
