### ISSUE TITLE
Dungeon Queue - Not working

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#856]
**Description**: Was checking old issues and found towards this one - https://github.com/azerothcore/azerothcore-wotlk/issues/468

For some reason it's not fixed, people still have to leave group and remake it after completing dungeons.

**Current behaviour**: Unable to requeue again.

**Expected behaviour**: People should be able to queue again, after last boss is killed.

**Steps to reproduce the problem**: Not sure.

**Hash**: 7696bd3
**Operating system**:  Linux, Debian 9

**Modules**:  Premium, Congrats on level.

**Other Customizations**: No.

**Comment by Deku** [comment]
Confirmed

**Comment by Motorheadx** [comment]
Confirmed

**Comment by AyaseCore** [comment]
Have we tried to solve this problem before?
I didn't find the relevant records.
In this PR:#574. no relevant fix code was found.

**Comment by AyaseCore** [comment]
```
case LFG_STATE_FINISHED_DUNGEON:
            if (grp && grp->isLFGGroup())
                joinData.result = LFG_JOIN_PARTY_NOT_MEET_REQS;
            break;
```
If it is in the LFG, the state is LFG_STATE_FINISHED_DUNGEON. It will not enter the lfg.

I've forgotten.
What is the normal LFG process.
Can anyone explain that?

**Comment by pklloveyou** [comment]
Can enter but the instance is not reset

**Comment by AyaseCore** [comment]
This may be why the pussywizard does not allow you to requery LFG.
It may be due to a defect in reset instance processing (which needs to be confirmed). Maybe you should open a new issue @pklloveyou

**Comment by Refuge89** [comment]
On clear sunwell core work Perfect LFG ;)

**Comment by boom8866** [comment]
Non reset problem
1.When a instance ends, proceed to the next random.
2.When random access to the same instance, instance is not reset correctly.

**Comment by BarbzYHOOL** [comment]
Open new issue @boom8866
