### ISSUE TITLE
"Draconic For Dummies" Chapters Drop Without Quest

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8575]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2124

Quest items [Draconic for Dummies](https://wowgaming.altervista.org/aowow/?item=21104)(ID21104) and [Draconic for Dummies](https://wowgaming.altervista.org/aowow/?item=21105)(ID21105) available to players without [The Only Prescription](https://wowgaming.altervista.org/aowow/?quest=8620).
![WoWScrnShot_101721_015510](https://user-images.githubusercontent.com/85256266/137604007-8b5b7cb0-51db-4bc0-9fcb-8a19a91b719c.jpg)

Tester: confirmed. Checking the DB shows the following NPCs are dropping various chapters of Draconic for Dummies without the quest flag set:

| Entry | name | entry | name | 
| ---: | --- | ---: | --- | 
| 15552 | Doctor Weavil | 21103 | Draconic for Dummies | 
| 8716 | Dreadlord | 21104 | Draconic for Dummies | 
| 8717 | Felguard Elite | 21104 | Draconic for Dummies | 
| 12396 | Doomguard Commander | 21104 | Draconic for Dummies | 
| 7461 | Hederine Initiate | 21105 | Draconic for Dummies | 
| 7463 | Hederine Slayer | 21105 | Draconic for Dummies | 
| 10184 | Onyxia | 21108 | Draconic for Dummies | 
| 11502 | Ragnaros | 21110 | Draconic for Dummies | 

Also DFD items 21106, 21107 and 21109 don't appear to be dropped by anything at all.

### Expected Blizzlike Behaviour

Quest items usually aren't available to players without quest.

### Source

Wowwiki [Draconic for Dummies](https://wowwiki-archive.fandom.com/wiki/Draconic_for_Dummies)
> The chapters will only drop if someone in the killing group has the quest N [60] The Only Prescription.

Other chapters aren't available without quest. Checked on local AC.
(Tester - checked as well, there's only 1 like that I could find, 21108 dropped by Onyxia (1) ID 36538)

### Steps to reproduce the problem

Kill listed NPCs and check out Draconic for Dummies

### Extra Notes

Find the incorrectly-set items with this query:

```SQL
SELECT ct.Entry , ct.name, it.entry, it.name
FROM `creature_loot_template` clt
JOIN `creature_template` ct ON ct.lootid = clt.Entry
JOIN `item_template` it ON clt.Item = it.entry
WHERE it.name = 'Draconic for Dummies'
AND clt.QuestRequired = 0
ORDER BY it.entry
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
> Also DFD items 21106, 21107 and 21109 don't appear to be dropped by anything at all.

It drop from object. There is everything good
![WoWScrnShot_101721_105538](https://user-images.githubusercontent.com/85256266/137617565-4911d20b-842a-4568-aeb9-2a6e8ffc9897.jpg)

> Other chapters aren't available without quest. Checked on local AC.
(Tester - checked as well, there's only 1 like that I could find, 21108 dropped by Onyxia (1) ID 36538)

I mean Doctor Weavil, Ragnaros and Onyxia. There is also ok.
![WoWScrnShot_101721_105745](https://user-images.githubusercontent.com/85256266/137617726-a9ceea77-ccc8-454b-93ac-6df9668f60c9.jpg)
![WoWScrnShot_101721_105857](https://user-images.githubusercontent.com/85256266/137617728-bd9176ef-9f2e-48da-b6d8-36708027b18f.jpg)
![WoWScrnShot_101721_105954](https://user-images.githubusercontent.com/85256266/137617731-41f5d03b-6e10-4864-a59f-95bed48c72ec.jpg)

**Comment by Nefertumm** [comment]
I'm closing this issue as it is not present in local AC. It's only present with mod-progression.

**Comment by Nefertumm** [comment]
Actually hold up. I got confused for a moment. This is indeed a valid issue but only with 2 items. And then we have an issue with the Onyxia one with mod-progression. Fixing them right now
