### ISSUE TITLE
Debian compile azerothcore failed

### ISSUE THREAD

**Issue by kncxstudio** [azerothcore/azerothcore-wotlk#858]
**Description**:
Debian 8 x64 and Debian 9 x64 compile azerothcore failed
**Current behaviour**: 
[ 39%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
src/server/scripts/CMakeFiles/scripts.dir/build.make:54: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_shaman.cpp.o] Error 4
CMakeFiles/Makefile2:1095: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Expected behaviour**:
compile without errors

**Steps to reproduce the problem**:
Just execute 'make' command

**Branch(es)**: 
master

**AC hash/commit**:  
commit 86a9decf4c8b4d4d85b73c0e69041f4dfd0c090e

**Operating system**:  
Debian 8 x64 and Debian 9 x64 

**Modules**:  Are you using modules? if yes, list them
(empty)

**Other Customizations**: 
(empty)

**Comment by Viste** [comment]
can't confrim works fine on debian 8, centOS 7, ubuntu 16-18.04 and fedora 25

**Comment by Viste** [comment]
`c++: internal compiler error: Segmentation fault (program cc1plus)`
according to this i think you don't have free memory or CPU resources to finish build

**Comment by kncxstudio** [comment]
Thx.It works when I upgraded my virtual machine.

**Comment by BarbzYHOOL** [comment]
Possibly can happen also when your virtual machine has too few disk space
