### ISSUE TITLE
cmake hook AFTER_LOAD_CONF not work 

### ISSUE THREAD

**Issue by AyaseCore** [azerothcore/azerothcore-wotlk#859]
**Description**:
I found a problem when I was writing a module for ahbot.
the cmake hook:AFTER_LOAD_CONF is not work. 
Because executing this hook is before the module is loaded.
We need to load the module before this hook.

**Current behaviour**: 
in the module.
```
CU_ADD_HOOK(AFTER_LOAD_CONF"${CMAKE_CURRENT_LIST_DIR}/cmake/after_load_conf.cmake")
```
the file after_load_conf.cmake not run.

**Expected behaviour**: 
This file [after_load_conf. cmake] can be run properly here at hook(AFTER_LOAD_CONF).

**Steps to reproduce the problem**:

1. add a file: mod-ahbot/CMakeLists.txt
```
CU_SET_PATH("CMAKE_MOD_AHBOT_DIR" "${CMAKE_CURRENT_LIST_DIR}")
CU_ADD_HOOK(AFTER_LOAD_CONF "${CMAKE_CURRENT_LIST_DIR}/cmake/after_load_conf.cmake")
```
2. add a file: mod-ahbot/cmake/after_load_conf.cmake
```
message("[mod-ahbot] the hook AFTER_LOAD_CONF is running!")
```
3. Cmake again.  AFTER_LOAD_CONF  not work.

**Branch(es)**: 
master 

**AC hash/commit**:  
86a9decf4c8b4d4d85b73c0e69041f4dfd0c090e

**Operating system**: 
win7 x64 vs2017

**Modules**:  
none

**Other Customizations**: 
none

**Comment by BarbzYHOOL** [comment]
Added in eluna compatibility PR
