### ISSUE TITLE
Hunter's Snake Trap did not attack victim

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8590]
### Current Behaviour

Snake will follow player

### Expected Blizzlike Behaviour

Snake should attack victim

### Source

#7959 broken this

### Steps to reproduce the problem

Use Snake Trap

### AC rev. hash/commit

429823a

### Operating system

Windows 10 x64

**Comment by T1ti** [comment]
summons are awful, they are all hardcoded with scripts instead of having properly implemented summonproperties flags

snakes are supposed to use this flag 
![image](https://user-images.githubusercontent.com/40864460/137652737-5b280060-4e51-473b-908b-5eaead07cafa.png)
