### ISSUE TITLE
Creatures can't have respawn timer lower than 5 minutes

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#8591]
### Current Behaviour

Any spawntimesecs lower than 5 minutes gets overwriten by corpseDelay @ https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Creature/Creature.cpp#L1787

![Skärmbild 2021-10-17 233644](https://user-images.githubusercontent.com/47818697/137660927-f2e2407e-900a-4a2b-a547-b5ad5b73ba51.jpg)

### Expected Blizzlike Behaviour

You should be able to set creatures to respawn with timers lower than 5 minutes if you want/need to

### Steps to reproduce the problem

quest add 9740
go creature id 17886
Use the crystals
Notice the triggers (red beam visuals) only respawn after 5 minutes and 33 seconds, despite their respawn time only being 33 seconds @ DB

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a1a878d55c983584df27169f40e712290b997647

### Operating system

Win11 x64

**Comment by UltraNix** [comment]
That respawntime is about timer between corpse despawn and respawning.  It's never been about timer between die and respawn.

**Comment by Nyeriah** [comment]
@UltraNix I understand that, but whoever set the spawntimesecs of those creatures to 35 seconds probably expected them to respawn in half a minute, and not 5 minutes. Honestly, I'm not certain if this is an issue, or how we should address it, but it needs to be somehow more explictly mentioned that.

Anyway, I seem to have worked around this with the SAI force despawn implementation. so I'll leave this one up to your judgement wether to close it or not.

**Comment by UltraNix** [comment]
It depends how you wanna to despawn that trigger. If kill is used, then corspe delay is added. If simple despawn, then respawn timer is okay. If creature should be despawn, then use always `DespawnOrUnsummon` instead of `Unit::Kill`
