### ISSUE TITLE
Not work quest id 12730

### ISSUE THREAD

**Issue by Chrisjiajun** [azerothcore/azerothcore-wotlk#86]
cannot use an item ID 39566
position 6448.51 -4475.81 451.447 571

**Comment by ShinDarth** [comment]
Please read https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

> the description of the bug, including any useful links and IDs/GUIDs/names of any related entities (NPCs, spells, gameobjects, etc..)

> the core revision (commit hash) of the AzerothCore you are running on, do not write just "latest version" even if you have just updated your core

**Comment by DevRival** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/34

**Comment by ShinDarth** [comment]
ok, then this is a duplicate

**Comment by Chrisjiajun** [comment]
sorry no search look
