### ISSUE TITLE
Can't resurrect opposite faction when already released

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#8600]
### Current Behaviour

You can't resurrect a player from the opposite faction, if he/she already clicked on "release spirit". It works fine for the same faction. This is a known bug on Chromiecraft, but I couldn't find a bug report for it on AC.
I tested it on the latest master branch, and the issue still persists.
I'm not sure if that is only an issue with the dungeon finder, but I believe it's a general issue.

### Expected Blizzlike Behaviour

We should be able to resurrect each other in a crossfaction group.

### Steps to reproduce the problem

1. be in a group with the opposite faction
2. try to resurrect a player from the opposing faction after he already released.
3. See that you can't

### AC rev. hash/commit

67ebf7b0923caa986ff4b154

### Operating system

Win 10 x64

### Custom changes or Modules

All crossfaction options enabled in the worldserver config.

**Comment by UltraNix** [comment]
All resurrection spells have `TARGET_FLAG_CORPSE_ALLY`, so you can only target your own faction corpses. Corpse faction is handled clientsiede (based on race on corpse creation) and there is nothing I can do with it.

**Comment by patou01** [comment]
@Ultranix Wouldn't we be able to make a spell override?

**Comment by UltraNix** [comment]
No.
