### ISSUE TITLE
Item "Of Nature's Wrath" Affix Does Not Provide Correct Bonus

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#8606]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1890

Items with "Of Nature's Wrath" affix do not provide the bonus stated in the item description. Other affixes do not display this issue.

![image](https://user-images.githubusercontent.com/80938499/135285921-3f5f1015-3aeb-4971-9a70-5c82ad764e9c.png)

Tester: Confirmed. 
I only checked +13, but for that it grants incorrectly +9. I assume that it is the same for the others, but in either case it is wrong for +13.
@VFaleiro Provided a list of the suffixes, from [wowwiki](https://web.archive.org/web/20100817023145/http://www.wowwiki.com/SuffixId#of_Nature.27s_Wrath):
<details>
<summary>List of nature's wrath suffixes</summary>
<html><body>

SuffixID | Bonus
-- | --
1989 | +1 Nature Spell Damage
1990 | +3 Nature Spell Damage
1991 | +4 Nature Spell Damage
1992 | +6 Nature Spell Damage
1993 | +7 Nature Spell Damage
1994 | +9 Nature Spell Damage
1995 | +10 Nature Spell Damage
1996 | +11 Nature Spell Damage
1997 | +13 Nature Spell Damage
1998 | +14 Nature Spell Damage
1999 | +16 Nature Spell Damage
2000 | +17 Nature Spell Damage
2001 | +19 Nature Spell Damage
2002 | +20 Nature Spell Damage
2003 | +21 Nature Spell Damage
2004 | +23 Nature Spell Damage
2005 | +24 Nature Spell Damage
2006 | +26 Nature Spell Damage
2007 | +27 Nature Spell Damage
2008 | +29 Nature Spell Damage
2009 | +30 Nature Spell Damage
2010 | +31 Nature Spell Damage
2011 | +33 Nature Spell Damage
2012 | +34 Nature Spell Damage
2013 | +36 Nature Spell Damage
2014 | +37 Nature Spell Damage
2015 | +39 Nature Spell Damage
2016 | +40 Nature Spell Damage
2017 | +41 Nature Spell Damage
2018 | +43 Nature Spell Damage
2019 | +44 Nature Spell Damage
2020 | +46 Nature Spell Damage
2021 | +47 Nature Spell Damage
2022 | +49 Nature Spell Damage
2023 | +50 Nature Spell Damage
2024 | +51 Nature Spell Damage
2025 | +53 Nature Spell Damage
2026 | +54 Nature Spell Damage

</body>
</html>
</details>

### Expected Blizzlike Behaviour

Items provide a bonus equal to that in the item description.

### Steps to reproduce the problem

Items with "Of Nature's Wrath" do not give correct damage according to item description. Have tested with multiple items.

### Extra Notes

https://github.com/azerothcore/azerothcore-wotlk/issues/8147

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
I tested with +30 and worked okay. Need another test.

**Comment by Shineslippers** [comment]
@UltraNix i tested and look like it's issue with multiplier somewhere. [Lightning Bolt(Rank 10)](https://wowgaming.altervista.org/aowow/?spell=15208) is getting max damage, but [Lightning Bolt(Rank 1)](https://wowgaming.altervista.org/aowow/?spell=403) doesn't getting anything. Hier rank more bonus damage.

**Comment by UltraNix** [comment]
Because different ranks get different % of that bonus.

**Comment by Shineslippers** [comment]
So i guess it's invalid report
