### ISSUE TITLE
[ERROR] Console - waypoint

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#8627]
### Current Behaviour

After running the server few moment later we get an error : 
![image](https://user-images.githubusercontent.com/31663279/137990869-6170b37c-dcd0-419b-a050-8334c96aa26b.png)

### Expected Blizzlike Behaviour

no error

### Steps to reproduce the problem

1. run the server
2. wait

### AC rev. hash/commit

407ee3045e11

### Operating system

ubuntu server 20.04

**Comment by Maurowin** [comment]
@Kitzunu this one too ?

**Comment by Kitzunu** [comment]
No. 👍
