### ISSUE TITLE
[ERROR] console - SmartScript

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#8628]
### Current Behaviour

Error print in the console : SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 11680 SourceType 0 EventType 4 TargetType 7 using non-existent Text id 0 for talker 3823, ignored.
![image](https://user-images.githubusercontent.com/31663279/137991375-07d30703-9dd5-4fe0-bb01-c8764fd2e9a5.png)

### Expected Blizzlike Behaviour

no error

### Steps to reproduce the problem

1. run the server
2. wait few minute

### AC rev. hash/commit

407ee3045e11

### Operating system

ubuntu server 20.04

**Comment by Shineslippers** [comment]
```
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 11680 SourceType 0 EventType 4 TargetType 7 using non-existent Text id 0 for talker 3819, ignored.
SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 11680 SourceType 0 EventType 4 TargetType 7 using non-existent Text id 0 for talker 3823, ignored.
```
Don't think Horde Scouts should saying `Never cross Dark Iron`. Saw similar report on TC. Can't find any source regarding to it.
