### ISSUE TITLE
Creature_text - SQL Fixes

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#863]
**Description**: Some creatures missing text, and keep spamming about it. Here's the fix for those which i have in my Logs at least.

**Current behaviour**: Missing text - Nothing special.

**Expected behaviour**: They should tell something, tho some of them, like Horses and invisible NPC's shouldn't, and that's why you will see that some of them have only "..." but chance for sayin' that is 0.

**Steps to reproduce the problem**: Check link bellow for fix, still new to hub, dunno how to make em easier to see.

https://pastebin.com/hF62Z6JC

**Operating system**:  Linux, Debian 9
**Hash**: 7696bd3
**Modules**:  Premium, Congrats on level
**Other Customizations**: No

**Comment by pondaveia** [comment]
@Knindzagxg 

To create a fix for any issue simply create a branch on your fork with a self explanatory title for example:
_"CreatureName SAI"_

Then proceed to create a pending versioned sql file. To learn this simply check this wiki reference:
_https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files#1-creating-a-versioned-pending-sql-file--recommended-_

Then create a pull request where you refer to the bug and apply the pending versioned sql file. This is how you should contribute to fixing SQL bugs and not pasting pastebin fixes on links.
If you still don't understand something text me on Discord and I shall help you.

**Comment by Knindzagxg** [comment]
After i fixed those, there no issues anymore.
Tho new one appear when more players doing quests, and i will fixe them as well in next few days.

**Comment by BarbzYHOOL** [comment]
Where are the creatures located?

**Comment by Knindzagxg** [comment]
All around.
Had errors for Northshire NPCs up to Northrend ones. 
It's nothing special or to worry about, i'm fixing them slowly.

**Comment by poszer** [comment]
Closing this, since these rows already exist in db, and issue is fixed. Thanks anyway
