### ISSUE TITLE
Feature: Hallows end, replace hardcoded strings.

### ISSUE THREAD

**Issue by arnaucastellvi** [azerothcore/azerothcore-wotlk#8631]
### Describe your feature request or suggestion in detail

The event of Hallows end have hardcoded strings, would be good to replace it for text of broadcast_text and broadcast_text_locale. Like this it could be modified and localised.

**Comment by Kitzunu** [comment]
1. Open a bug report
2. If possible, find these hardcoded texts in the core and link them. See https://github.com/azerothcore/azerothcore-wotlk/projects/15#card-52081050 for already opened bug reports
