### ISSUE TITLE
Hallows end, replace hardcoded strings.

### ISSUE THREAD

**Issue by arnaucastellvi** [azerothcore/azerothcore-wotlk#8632]
### Current Behaviour

The event of Hallows end (`hallows_end.cpp`) have hardcoded strings, would be good to replace it for text of broadcast_text and broadcast_text_locale.

### Expected Blizzlike Behaviour

You can modify and locate the text via DDBB.

### Source

Example of hardcoded text in src/server/scripts/Events/hallows_end.cpp

`me->MonsterYell("Prepare yourselves, the bells have tolled! Shelter your weak, your young and your old! Each of you shall pay the final sum! Cry for mercy; the reckoning has come!", LANG_UNIVERSAL, 0);`

` player->MonsterSay("Horseman rise...", LANG_UNIVERSAL, 0);`

### Steps to reproduce the problem

1- Modify text in acore_world.broadcast_text and acore_world.broadcast_text_locale where id =22695 (example text)
2- Restart worldserver and start event..
3- The modification is not appear in game.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/ba719f0feb70827beaebb40ff5095f75e2fd4302

### Operating system

Debian 10

**Comment by Kitzunu** [comment]
Fyi for the one taking this on. There are a lot of spells that needs to be scripted for this. Look at TC's file for reference =)

**Comment by v-mstrs** [comment]
Completed as of https://github.com/azerothcore/azerothcore-wotlk/commit/6e39ffa64e323f8b2cf3bb24b34c0ae41a2b701d

**Comment by Nyeriah** [comment]
Thanks!
