### ISSUE TITLE
Docker install error on ./acore.sh docker client-data

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#8637]
Clean docker install on W10 and on W11.
When installing Azerothcore using normal docker setup, at step 

./acore.sh docker client-data

Error received:

> Deno version check:
> Version 1.9.1 is already installed
> >>>>> Running: docker-compose run --rm ac-build bash acore.sh client-data
> unexpected character ";" in variable name near "; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';\n\nDB_CHARACTERS_CONF=MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';\n\nDB_WORLD_CONF=MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';\n\n#\n# SIMPLE RESTARTER\n#\nAC_RESTARTER_BINPATH=\nAC_RESTARTER_BINFILE=\nAC_RESTARTER_WITHGDB=\n"
> error: Uncaught (in promise) Error: Failed with error: 15, however,
>             it's not related to this Deno script directly. An error occurred within
>             the script called by the command itself
>           throw new Error(`Failed with error: ${status.code}, however,
>                 ^
>     at Command.<anonymous> (file:///D:/Azerothcore/azerothcore-wotlk/apps/docker/docker-cmd.ts:290:17)
>     at async Promise.all (index 0)
>     at async file:///D:/Azerothcore/azerothcore-wotlk/apps/docker/docker-cmd.ts:240:5
> 

Multiple people have this issue.
Tried on 2 computers.
If you need more info, please say, i'll provide it quickly

**Comment by purebaba** [comment]
seems not to be fixed...



NOTICE: file </Volumes/Extend/Other/azerothcore-wotlk/conf/config.sh> has not been found, you should create and configure it.
Deno version check:
Version 1.9.1 is already installed
>>>>> Running: docker-compose run --rm ac-build bash acore.sh client-data
unexpected character ";" in variable name near "; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';\n\nDB_CHARACTERS_CONF=MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';\n\nDB_WORLD_CONF=MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';\n\n#\n# SIMPLE RESTARTER\n#\nAC_RESTARTER_BINPATH=\nAC_RESTARTER_BINFILE=\nAC_RESTARTER_WITHGDB=\n"
error: Uncaught (in promise) Error: Failed with error: 15, however,
            it's not related to this Deno script directly. An error occurred within
            the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///Volumes/Extend/Other/azerothcore-wotlk/apps/docker/docker-cmd.ts:290:17)
    at async Promise.all (index 0)
    at async file:///Volumes/Extend/Other/azerothcore-wotlk/apps/docker/docker-cmd.ts:240:5

**Comment by purebaba** [comment]
![image](https://user-images.githubusercontent.com/14145814/139661101-c5d974cd-0ace-4b7a-853d-5a7fd3e7b134.png)

I removed the blanks, and it worked.
But I didn't read the code seriously. Just a hint

**Comment by pappons** [comment]
I had the same issue on Win10 using GitBash. Seemed to solve it by adding quotation marks like below:
 
```
DB_AUTH_CONF="MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';"

DB_CHARACTERS_CONF="MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';"

DB_WORLD_CONF="MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';"
```

**Comment by FlamePrince** [comment]
> I had the same issue on Win10 using GitBash. Seemed to solve it by adding quotation marks like below:
> 
> ```
> DB_AUTH_CONF="MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';"
> 
> DB_CHARACTERS_CONF="MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';"
> 
> DB_WORLD_CONF="MYSQL_USER='root'; MYSQL_PASS='password'; MYSQL_HOST='ac-database'; MYSQL_PORT='3306';"
> ```

This isn't a genuine confirmation as i modified my docker-compose.yml to have certain values from ac-docker's git's docker-compose.yml, but as soon as i modifed my env.ac in conf/dist/ to have quotes (as seen in any other file that references these values) it began to work as intended.
