### ISSUE TITLE
Glyph of Prayer of Healing not proc

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8645]
### Current Behaviour

Glyph of Prayer of Healing not proc

### Expected Blizzlike Behaviour

Glyph of Prayer of Healing should proc

### Steps to reproduce the problem

1.learn 55680
2.cast 48072

### AC rev. hash/commit

429823a

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
Indeed. [Glyph of Prayer of Healing](https://wowgaming.altervista.org/aowow/?item=42409)
![WoWScrnShot_110421_223135](https://user-images.githubusercontent.com/85256266/140407563-e1c9fbe2-fd26-495b-ae39-ec96272903dd.jpg)
