### ISSUE TITLE
Cold Iron Pick - not doing additional frost damage

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#8651]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2152

'Cold Iron Pick' only does physical damage.

Tester: Confirmed. See picture below
![image](https://user-images.githubusercontent.com/53914190/138124551-08e01b31-49a1-4c0c-93f9-cbff360f8704.png)
Also tested whether the frost damage was counted as physical; it isn't.
![image](https://user-images.githubusercontent.com/53914190/138125273-80f3160b-7659-4dd0-9a94-2e6797eecdbd.png)
This was tested by changing the damage of the pick from frost to physical, which increased the damage done (In combat log)

### Expected Blizzlike Behaviour

'Cold Iron Pick' does additional frost damage.

### Source

I am attaching relevant screenshots. It is written in the item description that it does '1-5 Frost Damage'.
When I tested it, I verified that it does not. Only physical damage.

A screenshot of item description from the game:
![WoWScrnShot_101921_194358](https://user-images.githubusercontent.com/8825036/137955294-2036059e-4040-4a2d-bbf8-8c7cccef9043.jpg)

A screenshot of a combat log, where I have fought a raptor using this 'Cold Iron Pick' and no Frost Damage was done.
![WoWScrnShot_101921_194351](https://user-images.githubusercontent.com/8825036/137955287-0e4918fe-a3d2-44ba-b9d7-bdb3482780da.jpg)

Also a link to a DB with item description: https://wotlkdb.com/?item=1959

Hope this will suffice as proof.

### Steps to reproduce the problem

1. Get the 'Cold Iron Pick' equiped.
2. Use 'Cold Iron Pick' to attack the mobs.
3. Verify in combat log, if weapon does Frost Damage or not.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by aradep** [comment]
[This does appear to be blizzlike.](https://us.forums.blizzard.com/en/wow/en/wow/t/weapons-with-frost-damage-or-any-other-school-dont-work/569190/7) Closing.
