### ISSUE TITLE
Quel'Dalar

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#868]
**Description**: http://www.wowhead.com/npc=37158/queldelar - Everything working perfect, except loot part, once u kill NPC. Event is pretty nice.

**Current behaviour**: Once u kill Quel'Delar, you are unable to loot item for quest.

**Expected behaviour**: Should be able to loot item.

**Steps to reproduce the problem**: Not sure - Should an easy SQL fix, but i will leave it up to someone who have much more xp with this.

**NPC Link** http://www.wowhead.com/npc=37158/queldelar
**Quest Link** http://www.wowhead.com/quest=24480/the-halls-of-reflection

**AC hash/commit**:  7696bd3

**Operating system**:  Linux, Debian 9

**Modules**: Premium, Congrats of level

**Other Customizations**: No

**Comment by pondaveia** [comment]
Can you provide screenshots and/or the error message? Would make it easier instead of having to re-test it.
Also be more careful with descriptive reproduction steps:

1. Get the quest
2. Go to quest location 
3. Kill the guy
4. Loot the guy
5. Validate the bug

A good practice is also adding commands in between steps to help reproduce the issue, for example:
1. Add quest _0000_
2. Tele _somewhere_

**Comment by Knindzagxg** [comment]
There's no error message or anything (Sometimes NPC get bugged in stay in place tho - waypoint error)
But this one is - When NPC move to corner and u kill it, it's kinda glow like there is something to loot, but unable to target and loot afterwise for some weird reason. 
Killing while in groups is one way to fix it, but when ppl tried solo they have same issue always.

**Comment by Cillez** [comment]
If it is supposed to drop 100% even when running solo, this fixed it for me:
```UPDATE `creature_loot_template` SET `ChanceOrQuestChance` = '100' WHERE `entry` = '37158' AND `item` = '50254';```
Anyways, I have no knowledge of this quest and how its supposed to work, so i suggest someone testing this before opening a PR. Hope it becomes useful, and i apologize if it's not how its supposed to work. 

Unfortunately i do not have enough time to test the quest chain ingame myself, so consider this as a suggested fix. If it's good, I'll open a PR tomorrow.

I did test to spawn the npc, kill it, and as @Knindzagxg said, no loot. Then i executed the SQL above, and did the same, this time i could loot it.

**Comment by Knindzagxg** [comment]
I will check later tonight mate.

**Comment by Cillez** [comment]
Did you get to test it, @Knindzagxg ?

**Comment by Knindzagxg** [comment]
Yeah, sorry i forgot to answer.

It's still the same sometimes - You can see there's glow effect like when there's loot but can't click on NPC to loot it.
Loot drop chance was fine even before btw.

**Comment by Cillez** [comment]
Yeah i realize it was fine before, but i was unable to reproduce the issue after i used that sql query, so i had to know before moving forward with this bug. Thanks :)

**Comment by Knindzagxg** [comment]
No worries :)

**Comment by Cillez** [comment]
Ive tested approx 20 times without the sql query, didnt drop a single time in solo, then i tested 20 times after the sql query, and it dropped everytime. In other words, im unable to reproduce the bug that youre able to produce after sql has been added. Therefore i am unable to fix it, sorry.

**Comment by Knindzagxg** [comment]
It's just visual bug mate, loot was there always.
I think it's because sometimes Sword itself bug, and stay in one place.

**Comment by Hir0shi** [comment]
CONFiRM

**Comment by Pondaveia** [comment]
The issue with this bug is that the NPC doesn't have a model to display. I confirm:

https://imgur.com/a/3Olh4zj

**Comment by Pondaveia** [comment]
I fixed this on my side by simply downloading a new Client. You can download a new client at Warmane and the files will be updated. You will find that most of your NPCs don't have an equipment on them.

Here's proof that it is working: https://imgur.com/a/T1AuA3A

**Comment by BarbzYHOOL** [comment]
Yeah, I tested too no bug
