### ISSUE TITLE
"Immol'thar" can be pet pulled via wall

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8702]
### What client do you play on?

enUS

### Faction

- [x] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2171

Boss can be pulled without destroying crystals, hunters or warlocks can pull him with pet. Dungeon done in 3 mins of starting.
![shot1](https://user-images.githubusercontent.com/80590226/138547898-dd64818d-ff7e-435f-a640-e707e669643a.jpg)

Tester:

The issue is confirmed. You have to attack one of Summoner 1st and then can pull the boss with same trick.

https://user-images.githubusercontent.com/85256266/138554498-2f8c14de-44f6-4424-8e50-5b73eb304ce0.mp4

### Expected Blizzlike Behaviour

Wowhead [Immol'thar](https://classic.wowhead.com/npc=11496/immolthar)
[Youtube](https://www.youtube.com/watch?v=uVT1hnEcV1Q&ab_channel=WaifuSimulator27) (Non wotlk or classic video, but explains that you need to destroy 5 crystals, and here you can just pet pull, lock/hunter etc.)

### Source

X

### Steps to reproduce the problem

.go o 29746 - teleport to one of near crystal
use pet attack on summoner
use pet attack on boss

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e9c71c8ebefc067e3119a2a1a63b74c3239cc55c

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
Got a question, should the summoners also not aggro until immol'thar is ready? Or what's the deal with them?

**Comment by Shineslippers** [comment]
Summoners and Immor'thal under dome. When you disable dome they will attack immor'thal. Other pylons at the entrance

**Comment by patou01** [comment]
Thanks. I realized when looking through the DB they were far away. I'll check if I can do the summoners easily... Should be fine.
