### ISSUE TITLE
POI of "Augustus' Receipt Book" shows Western Plaguelands instead of Eastern Plaguelands

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8713]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2175

Doing "Show Map" on the quest "Augustus' Receipt Book" (id 6164) opens Western Plaguelands map while both the objective and completion are in Eastern.

Tester:

The issue is confirmed. [Quest Augustus' Receipt Book](https://wowgaming.altervista.org/aowow/?quest=6164). "Show Quest Map" open Western Plaguelands map
![WoWScrnShot_102421_001304](https://user-images.githubusercontent.com/85256266/138571765-92221aba-ea58-4da1-ad39-c4bb8f1b7589.jpg)

### Expected Blizzlike Behaviour

Doing "Show Map" on the quest "Augustus' Receipt Book" (id 6164) opens Eastern Plaguelands map.

### Source

[Youtube](https://youtu.be/jXcTdwgMnZI?t=9)

### Steps to reproduce the problem

.q a 6164

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by CraftedRO** [comment]
```sql
UPDATE `quest_poi` SET `WorldMapAreaId` = 23 WHERE `QuestID` = 3655;
```

**Comment by CraftedRO** [comment]
```sql
UPDATE `quest_poi` SET `WorldMapAreaId` = 23 WHERE `QuestID` = 6164;
```

**Comment by Voxstrasza** [comment]
@Shineslippers please check out #9584
