### ISSUE TITLE
Looking for someone who can write tutorials or articles

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#872]
I'm looking for someone who can write tutorials for AzerothCore (for the wiki notably) and maybe 1 "blog article". Also need some help to improve the Readme

I wanted to do this myself but I don't have enough time so if you are not a contributor yet, or just occasionally stumbling upon this github issue, it's an occasion to help the project !

I will guide you with what we need to write, so hit me up on the discord channel https://discord.gg/PaqQRkd

**Comment by Helias** [comment]
if this is still valid (I think so), you could open it in the forum.

**Comment by FrancescoBorzi** [comment]
@Helias you can transfer issues from one repo to another

![image](https://user-images.githubusercontent.com/75517/87881073-239fc600-c9f7-11ea-95bc-5886609f5a0c.png)
