### ISSUE TITLE
Duthorian Rall don't offer "The Symbol of Life" quest

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8724]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1894

When I accept the 5th part (https://classic.wowhead.com/quest=1781/the-tome-of-divinity) of the chain, I am not provided Symbol of Life (https://classic.wowhead.com/item=6866/symbol-of-life) to ress Henze Faulk (https://classic.wowhead.com/npc=6172/henze-faulk) in Elwynn Forest.

Other people does not seem to have any trouble with it. I believe it started bugging (not providing me 'Symbol of Life') after I discarded the item accidentally, before accepting the quest again at a later time.

Tester:

The issue is confirmed. [Duthorian Rall](https://wowgaming.altervista.org/aowow/?npc=6171) don't offer repetable [The Symbol of Life](https://wowgaming.altervista.org/aowow/?quest=1790) quest after [The Tome of Divinity](https://wowgaming.altervista.org/aowow/?quest=1786)(part 6) quest accept in case if [Symbol of Life](https://wowgaming.altervista.org/aowow/?item=6866) was destroyed
![WoWScrnShot_102421_224524](https://user-images.githubusercontent.com/85256266/138610246-fbc4fdff-42b4-4c19-b6a2-be8d38e17542.jpg)

### Expected Blizzlike Behaviour

Accept of "The Tome of Divinity"(part 6) should enable "The Symbol of Life"

### Source

Check out Dwarf's [The Tome of Divinity](https://wowgaming.altervista.org/aowow/?quest=1783)(part 6) quest
![WoWScrnShot_102421_224429](https://user-images.githubusercontent.com/85256266/138610214-174c0902-ed5d-4b83-a6dc-3fa0b837f9e5.jpg)

### Steps to reproduce the problem

.go c id 6171
.q a 1786
chek out symbol of life repetable quest

### Extra Notes

Same is there https://github.com/chromiecraft/chromiecraft/issues/409 https://github.com/chromiecraft/chromiecraft/issues/964

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/8757
