### ISSUE TITLE
.gitattributes more complete

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#873]
The auto setting is good but to be sure, here is a more complete .gitattributes to avoid conflicts between OSes (sometimes it caused really annoying bugs with the db_assembler.sh for example)

I added Lua because of Eluna module, I don't know if it should be there or elsewhere.

```
## AUTO-DETECT
##   Handle line endings automatically for files detected as
##   text and leave all files detected as binary untouched.
##   This will handle all files NOT defined below.
*   text=auto eol=lf

# Text
*.conf
*.conf.dist
*.txt
*.md
*.cmake

# Bash
*.sh text

# Lua
*.lua

# SQL
*.sql

# C++
*.c text
*.cc text
*.cxx text
*.cpp text
*.c++ text
*.hpp text
*.h text
*.h++ text
*.hh text

# Compiled Object files
*.slo binary
*.lo binary
*.o binary
*.obj binary

# Precompiled Headers
*.gch binary
*.pch binary

# Compiled Dynamic libraries
*.so binary
*.dylib binary
*.dll binary

# Compiled Static libraries
*.lai binary
*.la binary
*.a binary
*.lib binary

# Executables
*.exe binary
*.out binary
*.app binary

# Graphics
*.png binary
*.jpg binary
*.jpeg binary
*.gif binary

```

Please, tell me what you think about it, if it can be added or not. I copy pasted some directly for C++, not very useful probably.

Graphics are for Readme.md documentation pictures

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL what is this exactly doing?

I understand what `*   text=auto eol=lf` does, and the other associations like `format type`.. but for example what does `*.lua` alone do?

**Comment by Kitzunu** [comment]
going to close as no updates for over 2 years
