### ISSUE TITLE
[Script] Rend Blackhand and UBRS Gaunlet Event

### ISSUE THREAD

**Issue by iEmpress** [azerothcore/azerothcore-wotlk#8731]
### Current Behaviour

1. Event does not properly end upon wipe.
2. NPCs spawned by the event do not properly despawn upon ending the event.
3. Door should be closed before starting the event, 
4. Waves spawn too fast. In addition, they are not spawning upon the death of the current wave.
5. Rend did not use his abilities

### Expected Blizzlike Behaviour

1. Event resets once no player left in the dungeon is reachable nor in combat.
2. Once the event resets, it should despawn any spawned adds connected to it.

4. The next wave should spawn upon killing the previous wave.
5. Rend should a {Mortal Strike, Whirlwind, Cleave, Enrage, Daze}

### Source

3. https://youtu.be/asKYQoMPbks?t=200
4. https://youtu.be/asKYQoMPbks?t=230
5. https://youtu.be/asKYQoMPbks?t=347 video showing Cleave and Whirlwind.

### Steps to reproduce the problem

1. Enter UBRS ``.tele ubrs`` or ``.go creature 137968``
2. Navigate to the gauntlet (Jump down if teleported to Rend)
3. Check the specific bugs listed.

### Extra Notes

I am missing some sources. Refute or provide sources as you know/find them.
I search sources by google with refined search period:
![image](https://user-images.githubusercontent.com/82000605/138762206-4273ae21-5106-40ff-9e85-941c2b9391bb.png)

### AC rev. hash/commit

AzerothCore rev. d3bbaa918368

### Operating system

Windows 10

### Custom changes or Modules

Eluna

**Comment by Nyeriah** [comment]
It's unclear to me what door this report is refering to, the entrance to the arena?
The video seems to be from a private server? Nefarius doesn't use any of his lines during the waves, and he's kinda known for those.
