### ISSUE TITLE
[CONF] Missing options in config file

### ISSUE THREAD

**Issue by Winfidonarleyan** [azerothcore/azerothcore-wotlk#874]
**Missing options in config file**: worldserver.conf.dist and authserver.conf.dist

**Current behaviour**: Nothing special. The default options specified in the file **world.cpp**.

**Expected behaviour**: Options, at least by default, must be in the configuration file

**Steps to reproduce the problem**:

## 1. worldserver.conf.dist
* DisconnectToleranceInterval = 0
* MonsterSight = 50.000000
* GuarderSight = 50.000000
* StrictChannelNames = 0
* Instance.SharedNormalHeroicId = 0
* Instance.ResetTimeRelativeTimestamp = 1135814400
* TeleportTimeoutNear = 25
* TeleportTimeoutFar = 45
* MaxAllowedMMRDrop = 500
* EnableLoginAfterDC = 1
* DontCacheRandomMovementPaths = 1
* RealmName = "X"
* FreeDualTalentSpecialization = 0
* MoveMaps.Enable = 1
## 2. authserver.conf.dist
* LoginDatabase.SynchThreads = 1

**Branch**: Master.

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/c3ba1a6425c1fb9293475067b2f15f660f541b7b

**Operating system**:  Linux, Ubuntu 14.04 and Windows 10.

**Modules**:  No.

**Other Customizations**: No.

**Comment by BarbzYHOOL** [comment]
We have the code for these options? I suppose so

Damn nice catch 

You could open a pull request for this too (like for the module). You can even do it directly on github by clicking on the file and editing it with a pencil (but there are 2 files for this issue)

You can also join us on discord :)

**Comment by Deku** [comment]
Realm name is set in the `auth.realmlist` table

**Comment by Winfidonarleyan** [comment]
@Deku, yes, there are options in this list that are not needed at all :D
