### ISSUE TITLE
[Instance/Zul'A man]Halazzi dont have texts in DB

### ISSUE THREAD

**Issue by Remberance** [azerothcore/azerothcore-wotlk#8744]
###What client do you play on?
zhCN

###Faction
 Alliance

###Content Phase:
70

### Current Behaviour

when you combat with Halazzi, he didnot say anything texts.

and DBErrors LOGS show :

CreatureTextMgr: Could not find Text for Creature(Halazzi) Entry 23577 in 'creature_text' table. Ignoring.
CreatureTextMgr: Could not find Text for Creature(Halazzi) Entry 23577 in 'creature_text' table. Ignoring.

### Expected Blizzlike Behaviour

he will say some text when he aggro, split, combine, melee, berserk.

### Source

https://tbc.wowhead.com/npc=23577/halazzi#sounds

### Steps to reproduce the problem

1. .go c 86195
2. combat with Halazzi
3. he didnot say anything

### Extra Notes

no

### AC rev. hash/commit

04143658ab406106ff2650e944592d1421987e21

### Operating system

WIN10

### Custom changes or Modules

account achi
ah bot
autobalance
eluna
solo lfg

**Comment by Si1ker** [comment]
@Ragelezz label is wrong, Zul'Amanis TBC
