### ISSUE TITLE
Paladin's "Tome of Divinity" quests doesn't close "The Tome of Divinity" quests

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8746]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1225

after finishing the quest of the paladin to unlock detect undead and ressurect hability, the tomes what are given to you in the begining of the quest still on your inventory with the mark of "!" and when you click it they show a message telling you dont meet the quallifications to start the quest, but you can finish the quest anyway, so its just confuse i just trow it out of my inventory when i was out doing minning so was fine

Tester:

One of issues is confirmed. Accept one of Dwarf's Tome of Divinity([ID2997](https://wowgaming.altervista.org/aowow/?quest=2997), [ID2999](https://wowgaming.altervista.org/aowow/?quest=2999), [ID3000](https://wowgaming.altervista.org/aowow/?quest=3000)) doesn't close The Tome of Divinity [ID1645](https://wowgaming.altervista.org/aowow/?quest=1645). Accept one of Human's Tome of Divinity([ID2998](https://wowgaming.altervista.org/aowow/?quest=2998), [ID3681](https://wowgaming.altervista.org/aowow/?quest=3681)) doesn't close The Tome of Divinity [ID1641](https://wowgaming.altervista.org/aowow/?quest=1641)

![WoWScrnShot_102621_144129](https://user-images.githubusercontent.com/85256266/138871414-ee6ffcea-0fde-4516-a37c-686fd4eae779.jpg)
![WoWScrnShot_102621_144621](https://user-images.githubusercontent.com/85256266/138871435-cfffa279-9491-4484-81fb-59dad9ed8ef2.jpg)

### Expected Blizzlike Behaviour

Accepting one of starting Tome of Divinity should close The Tome of Divinity.

### Source

X

### Steps to reproduce the problem

Humans
.go c id .go c id 6171
.q a 2998
observer Duthorian Rall quests

Dwarfs
.go c id 6179
.q a 2997
observe Tiza Battleforge quests

### Extra Notes

Can't find issues with tome of Valor. When you accepting quest from item it disapear. Idk how manage to leave it in bags.
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
Due to https://github.com/chromiecraft/chromiecraft/issues/2295 prio high

**Comment by Shineslippers** [comment]
New issue. Complete 2997, 2999, 3000 doesn't open 1646.

**Comment by malcrom** [comment]
So do we want 
Show quest 1645 if player has not taken quest 1785 or quest 2997?
or
Show quest 1645 if player has quest 1785 or quest 2997 rewarded?

**Comment by malcrom** [comment]
I don't know why this is considered high. It will not stop you from completing the quest its just visual

**Comment by Shineslippers** [comment]
1785 is last quest. It should not be linked to anything. It's high because complete 2997, 2999 and 3000 doesn't open 1647 adn you can not continue quest for redemption. In this case you can not also start 1646.

1. Show 1645 if has not taken 2997, 2999 or 3000
2.  Complete 2997, 2999, 3000 should open 1647

**Comment by Nyeriah** [comment]
@malcrom about this quest:

![Skärmbild 2021-11-19 100420](https://user-images.githubusercontent.com/47818697/142627409-fabec3c8-88f6-4dc8-a802-36d5cb3ffe08.jpg)

The story goes as it follows:
- The trainer tells you about his duties as chief paladin and gives you a book to study
- You receive the book, and the book gives you a quest to "let the guy know" you've studied

I might be wrong, but shouldn't the *first* quest be conditioned instead? It doesn't make sense to have the book if you can't pick up the following quest, you can't do anything with the book.

**Comment by Nyeriah** [comment]
More research:

https://user-images.githubusercontent.com/47818697/142729552-e1b01c5a-b103-45f8-99f8-8c4ba8e416ee.mp4

**Comment by Shineslippers** [comment]
Same here
https://youtu.be/VN0mxOYPHrs?t=19
2998 doesn't close 1641. You have to start quest from book.

So probably problem with 2997, 2999, 3000 - it's close 1646 from accept. And my old post is wrong.

**Comment by Nyeriah** [comment]
Ironforge seems to be working fine for me, I can't follow the chain unless I complete the quest from the book.
Stormwind seems to be broken, the next quest in the chain is offered before I complete the quest from the book.

**Comment by Shineslippers** [comment]
Ironforge as i mentioned it in discrod: if you're turn in 2997, 2999, 3000 before quest of book 1645 - you can't accept 1646 quest from book.

**Comment by Nyeriah** [comment]
> Same here: https://youtu.be/VN0mxOYPHrs?t=19
> 
> * 2998, 3681 should not close 1641, 1642 and should not open 1643
> * 2997, 2999, 3000 should not close 1645, 1646 and should not open 1647
> * You have to start quest only from book
> * 1641 should be repetable. In case of destroy of book, but not available after 1642 complete.
> * 1645 should be repetable. In case of destroy of book, but not available after 1646 complete.
> 
> Well, look like this and I'm sorry. My bad. Hope this one is correct. @Nyeriah can you approve it?

Those numbers are confusing to me, they don't really mean anything and all of those quests have the same name.

* Humans have quests in Ironforge and Goldshire that send them to Stormwind to pick up the book
* Dwarves have quests in Stormwind and Kharanos that send them to Ironforge to pick up the book
* The quest that offers the book is always available
* The quest you accept *from* the book can always be turned in
* The next quest in the chain only shows up *after* you turn in the quest *from* the book

**Comment by Shineslippers** [comment]
Well, used numbers because of the same reason - same names. Those quest just sending paladins to trainer. 5 quests total 2 for humans and 3 for pdwarfs. Looks like it doesn't matter already. Fix doesn't broke anything. Good job. Just need to make Quests for obtaining book repetable in case of destroy book.
