### ISSUE TITLE
Server crash 20211026

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8756]
### Current Behaviour

crash log: https://gist.github.com/bgcfb/dd55b527a26e5ac8feb31928fdfb9178

Call stack:
Address   Frame     Function      SourceFile
00007FF6125D8E50  00000095679FEF00  Object::GetGuidValue+40  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Entities\Object\Object.h line 160
00007FF612C299FC  00000095679FF400  Player::_SaveInventory+9EC  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Entities\Player\PlayerStorage.cpp line 7400
00007FF612C17926  00000095679FF450  Player::SaveInventoryAndGoldToDB+46  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Entities\Player\PlayerStorage.cpp line 7199
00007FF612D711E2  00000095679FF650  Player::Update+EF2  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Entities\Player\PlayerUpdates.cpp line 325
00007FF612D49D4F  00000095679FF730  Map::Update+12F  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Maps\Map.cpp line 757
00007FF61305079D  00000095679FF760  MapUpdateRequest::call+1D  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Maps\MapUpdater.cpp line 43
00007FF6130501D3  00000095679FF790  MapUpdater::WorkerThread+E3  D:\UPDATECORE\azerothcore-wotlk\src\server\game\Maps\MapUpdater.cpp line 159
00007FF61304FB9F  00000095679FF7C0  std::thread::_Invoke<std::tuple<void (__cdecl MapUpdater::*)(void),MapUpdater *>,0,1>+F  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\thread line 56
00007FF8F6B41BB2  00000095679FF7F0  _configthreadlocale+92
00007FF8F8407034  00000095679FF820  BaseThreadInitThunk+14
00007FF8F8EE2651  00000095679FF8A0  RtlUserThreadStart+21

### Expected Blizzlike Behaviour

none

### Source

PlayerStorage.cpp line 7400

### Steps to reproduce the problem

none

### AC rev. hash/commit

8d54fac

### Operating system

Windows 10 x64

**Comment by Voidx** [comment]
@bgcfb do you have more crashes?

**Comment by Kitzunu** [comment]
Will close as there has been no more activity here or anywhere else with the same logs.

Reopen if it still happens
