### ISSUE TITLE
Stuck at "Retrieving character list" for 5 minutes

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#877]
**Description**:

Irregularly, but often enough, when we launch AzerothCore we are stuck at "retrieving character list" just after login on our account. This concerns all the people logging in (players).

**Current behaviour**:

We are stuck during 2 minutes to 5 minutes (maybe more, sometimes we are stuck for more and it times out - this is not verified). Once we are able to choose our characters and enter the game, it never happens again (see **Remarks** below).

**Expected behaviour**:

This should never happen

**Remarks**:

- This has been noticed by MANY people in the discord, by me personally, by AyaseCore too.
- @AyaseCore told me this didn't occur on SunwellCore. This need to be verified (same for mangos, cmangos, trinitycore etc)
- It happened to me only when I didn't start my server for months. Or switched to another unused for a while database (like an older characters db). **So I think this is related to some MySQL cache or something like that** - need opinions on this.

**Steps to reproduce the problem**:

I don't know, it seems like people here have a similar issue (not sure if it's the same) https://github.com/azerothcore/azerothcore-wotlk/issues/711#issuecomment-362535892

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
On windows or on linux, same thing

PS: I started writing this issue and noticed the other issue afterwards so I let this one to refresh the problem https://github.com/azerothcore/azerothcore-wotlk/issues/711#issuecomment-362535892

**Comment by AyaseCore** [comment]
Yes.I'm sure there is indeed this problem.
Before last year or even earlier.
I build AZEROTHCORE several times.It will appear this situation.
I once asked if some of my friends had this problem. They said they did not pay attention.
So I always thought I was in a special situation. Others would not have this problem.
Until BarbzYHOOL talks about it.
I realized I wasn't the only one.

**Comment by Viste** [comment]
don't have this shit on SunwellCore and when use AC for tests or make pull same  just login to world for seconds.

**Comment by Viste** [comment]
and for fix it need more info >_<

**Comment by lineagedr** [comment]
@Viste Actually it's the same on Sunwell Core.

**Comment by AyaseCore** [comment]
This issue is in the database table instance_reset.
Truncation tables can avoid this problem.

src\server\game\Instances\InstanceSaveMgr.cpp
void InstanceSaveManager::Update()
```
void InstanceSaveManager::Update()
{
    time_t now = time(NULL);
    time_t t;
    bool resetOccurred = false;

    while (!m_resetTimeQueue.empty())
    {
        t = m_resetTimeQueue.begin()->first;
        if (t >= now)
            break;

        InstResetEvent &event = m_resetTimeQueue.begin()->second;
        if (event.type)
        {
            // global reset/warning for a certain map
            time_t resetTime = GetResetTimeFor(event.mapid, event.difficulty);
            bool warn = event.type < 5;
            _ResetOrWarnAll(event.mapid, event.difficulty, warn, resetTime);
            if (warn)
            {
                // schedule the next warning/reset
                ++event.type;
                ScheduleReset(resetTime - ResetTimeDelay[event.type-1], event);
            }
            else
                resetOccurred = true;
        }
        m_resetTimeQueue.erase(m_resetTimeQueue.begin());
    }
```

src\server\game\Instances\InstanceSaveMgr.cpp
void InstanceSaveManager::_ResetOrWarnAll(uint32 mapid, Difficulty difficulty, bool warn, time_t resetTime)
```
        // calculate the next reset time
        uint32 diff = sWorld->getIntConfig(CONFIG_INSTANCE_RESET_TIME_HOUR) * HOUR;

        uint32 period = uint32(((mapDiff->resetTime * sWorld->getRate(RATE_INSTANCE_RESET_TIME))/DAY) * DAY);
        if (period < DAY)
            period = DAY;

        uint32 next_reset = uint32(((resetTime + MINUTE) / DAY * DAY) + period + diff);
        SetResetTimeFor(mapid, difficulty, next_reset);
        SetExtendedResetTimeFor(mapid, difficulty, next_reset + period);
        ScheduleReset(time_t(next_reset-3600), InstResetEvent(1, mapid, difficulty));

        // update it in the DB
        PreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GLOBAL_INSTANCE_RESETTIME);
        stmt->setUInt32(0, next_reset);
        stmt->setUInt16(1, uint16(mapid));
        stmt->setUInt8(2, uint8(difficulty));
        CharacterDatabase.Execute(stmt);
```
```
  if (t >= now)
            break;
```
Before t >= now.
It will repeat the task to the mysql thread.(CHAR_UPD_GLOBAL_INSTANCE_RESETTIME)
So it gets stuck.

It's not a big number for each update instance_reset.If the database resetTime and the real time difference are huge, it will take a long time to make t > now.
```
 uint32 next_reset = uint32(((resetTime + MINUTE) / DAY * DAY) + period + diff);
```

So we have several solutions.
Is to update an SQL. Truncation table instance_reset.
or clean up the different data before instance_reset.For example, the database data of 60 days ago.
or other.

**Comment by Viste** [comment]
@lineagedr use sunwell for 2 YEARS AND DON'T GET IT look on your custom code

**Comment by BarbzYHOOL** [comment]
Viste, check out on discord "retrieving character list", it happened to several people (also on other emulators like TC). So it's confirmed, no need to discuss this

**Comment by FALL1N1** [comment]
This does not happen on TrinityCore or Sunwell, either way there are shitload of issues with both sunwell/azeroth, first one for example is the 'rewritten from scratch' shit everywhere that sunwell did, some of the stuff is cool but other is plain wrong. For example i can give you a hint, start you server, explore all the continents (fly around, fight for a little) then logout and leave it like that for 7-10 days, log back again and see the magic, up to 2-3k ms delay. There are issues with thread handling, opcode processing and what not, too long to explain (out of my develpoment skills as well). Found most that issues while "implementing" the voice chat feature as i had to run trough the "bones" of the source code.

**Comment by BarbzYHOOL** [comment]
Sunwell ran 3k daily when it closed. There is a server running 1.6k in cuba too. So what you're saying is very unlikely.

"explore all the continents (fly around, fight for a little) then logout and leave it like that for 7-10 days" this is not accurate to reproduce.

Also you can open a new issue if you really care.

**Comment by FALL1N1** [comment]
Thats why they said 'no easter eggs' inside. Do you really think that sunwell ran on windows? So why did we had to replace the pet loading from UInt8 to 16 in order to "load" pets properly from the database, i'm pretty sure sunwell didn't ran like this for 10+ years.

**Comment by Motorheadx** [comment]
We have on the server was a chapel in 100 people on a processor 6 stack 2.00 GHz, 8 gigs operators diff did not above 11 on this nonsense say that diff jumps on such a powerful processor as i7 it has a frequency of 4-5k Ghz I do not believe it

**Comment by AyaseCore** [comment]
This issue is also available at sunwellcore. It's just not obvious. Or people don't realize it.
Execute SQL script characters db:
```
 update instance_reset set resettime = 12345;
```
Restart worldserver.Login the game.You'll find it takes a long time to get into the game.

**Comment by BarbzYHOOL** [comment]
@FALL1N1 Everything you said is very inaccurate, I have counter examples for everything you said. I know how Northcraft worked too, I know one of their developer (maybe you were too? not only on Firefly ? I don't know where you take your numbers from, my only bet is Northcraft but that's a really bad example). If you really wish to contribute to an open source project like this, we would gladly welcome you, but please, be more respectful in regards to the time we spend on it.

Let's focus on that issue instead.

**Comment by Viste** [comment]
@AyaseCore ok i try reproduce

**Comment by AyaseCore** [comment]
In my second reply above, I have already analyzed why this problem appears. @BarbzYHOOL  @Viste 
Mysql thread is blocked.This is why the player can log in, but playercan't Get the characters  list.
Because the login is handled by authserver.
 mysql thread blocked in worldserver, so you need to wait while you query character.
In fact, the issue rarely appears.(if you often open worldserver)

**Comment by FALL1N1** [comment]
'being a proud leecher', eh? anyway, good luck with your sunwellcore fork

**Comment by Viste** [comment]
@FALL1N1 good luck with your bla bla bla without proof or help :)

**Comment by Motorheadx** [comment]
I use Azerothcore it from the beginning and especially no problems were not thanks to all the developers and who helps with this project my respect for you! bla bla bla xDD

**Comment by ShinDarth** [comment]
We need more code and less drama

**Comment by AyaseCore** [comment]
@FALL1N1 My approach is that the diff time is greater than the two reset cycles and will not execute the SQL command.
It can effectively reduce the number of SQL command executions.

**Comment by talamortis** [comment]
@ShinDarth  Nice comment, Maybe you could help find the issue :D

**Comment by pondaveia** [comment]
One way to reproduce this issue is when you first try to launch an AC server when fresh installed everything.
This happens to me every single time.
