### ISSUE TITLE
POI of quests "The Spirits of Southwind" and "Hive in the Tower" shows Un'goro Crater instead of Silithus

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8770]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2200

Doing "Show Map" on the quest "The Spirits of Southwind" (1125) when completed opens the Un'Goro map.
The same happens with the quest "Hive in the Tower" (1126).

Tester:

The issues is confirmed. [The Spirits of Southwind](https://wowgaming.altervista.org/aowow/?quest=1125) showing always incorrect POI while [Hive in the Tower](https://wowgaming.altervista.org/aowow/?quest=1126) only with complete credit.

![WoWScrnShot_102721_133917](https://user-images.githubusercontent.com/85256266/139051201-f3f01048-6285-42ce-b18e-37381c4776bd.jpg)
![WoWScrnShot_102721_134024](https://user-images.githubusercontent.com/85256266/139051237-bdd81255-0eed-410d-9861-c9cc634440c2.jpg)

### Expected Blizzlike Behaviour

Because the hand-over NPC is in Silithus, doing "Show Map" should open Silithus's map.

### Source

X

### Steps to reproduce the problem

.q a 1125
click "Show quest Map"
.q a 1126
.q c 1126
click "Show quest Map"

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Voxstrasza** [comment]
@Shineslippers please check out #9584
