### ISSUE TITLE
 Maraudon Noxious Hollow: Spore Cloud

### ISSUE THREAD

**Issue by dunjeon** [azerothcore/azerothcore-wotlk#878]
**Description**:
Within Maraudon's Noxious Hollow instance, the Spore Cloud debuff as applied by the belching fungi crashes the world server.

**Current behaviour**: Tell us what happens
Within Maraudon's Noxious Hollow instance, the Spore Cloud debuff as applied by the belching fungi crashes the world server.

**Expected behaviour**: Tell us what should happen instead
The Spore Cloud debuff should be applied to the character without crashing the server.

**Steps to reproduce the problem**:

0. Only tested with Paladin so far
1. Maradon
2. Noxious Hollow
3. Near the first boss
4. Hang out near one of the belching fungi  and acquire the Spore Cloud debuff

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
AZeroThCore -WOTLK Master

**AC hash/commit**:  
Honestly, don't know and I don't think it applies here

**Operating system**:  
Windows x64, Linux

**Modules**:  Are you using modules? if yes, list them
VAS

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please None
![scd](https://user-images.githubusercontent.com/30352875/40238293-671aa8fa-5a78-11e8-88d3-b2eb07a1d6ac.png)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Motorheadx** [comment]
I cannot confirm this

**Comment by dunjeon** [comment]
What class did you test it with?

**Comment by Motorheadx** [comment]
Pale Female

**Comment by FALL1N1** [comment]
mind pasting the crash log or just 'confirming' it is enough?

**Comment by dunjeon** [comment]
I will post crashlog

**Comment by Motorheadx** [comment]
I don't have that but I don't use any modules in the test

**Comment by dunjeon** [comment]
Looking at crash logs with a debug/release build I was able to track down the error.  is is module based and I will be working on a solution.
