### ISSUE TITLE
Feature: Multi IP Server Support

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8783]
### Current Behaviour

Realmid is unique in realmlist
Can not use same Realmid but different IP address

### Expected Blizzlike Behaviour

Old version authserver support same realmid and working fine

### Source

RealmList.cpp
RealmList.h
Realm.h

### Steps to reproduce the problem

none

### AC rev. hash/commit

a25eae3

### Operating system

Windows 10 x64

**Comment by Meltie2013** [comment]
@Maurowin Are you talking about a fail-over realm?

**Comment by Maurowin** [comment]
> @Maurowin Are you talking about a fail-over realm?

Nop, Iam trying to understand that @bgcfb want to explain.

**Comment by bgcfb** [comment]
@Maurowin There is only one gameserver run@realmid 1
Server have two or more ip and gateway
Authserver did not support same realmid in database
