### ISSUE TITLE
MySQL versions out of sync server/client

### ISSUE THREAD

**Issue by dantav** [azerothcore/azerothcore-wotlk#8787]
### Current Behaviour

This is mainly an issue only with docker containerized applications. As of right now I get this error when starting up my containers:
<img width="1278" alt="Screen Shot 2021-10-27 at 8 10 33 PM" src="https://user-images.githubusercontent.com/22668627/139180060-2dfc2de3-2a7e-4117-b4bb-e067a85f992f.png">

This is due to the fact that [docker-compose](https://github.com/azerothcore/azerothcore-wotlk/blob/a6cbe8aa57fecb7464e0ce28ebae4f09667bd975/docker-compose.yml#L60) is using that latest MySQL 8 image which happens to now be recently changed to 80027 when the client is still using 80026.

### Expected Blizzlike Behaviour

Nothing to do with Blizzlike Behavior expect the fact the server cannot start.

### Source

N/A

### Steps to reproduce the problem

This should happen to anyone who restarts their containers, regardless of code version. Assuming you didn't alter the docker-compose mysql image source.

- 

### Extra Notes

Right now [this](https://github.com/azerothcore/azerothcore-wotlk/blob/a6cbe8aa57fecb7464e0ce28ebae4f09667bd975/src/server/database/Database/DatabaseWorkerPool.cpp#L69) is a work around:
`bool isSameClientDB = true;`
I tried to use `8.0.26` image but I got some errors thrown for unhealthy container as you cannot downgrade it.

### AC rev. hash/commit

AzerothCore rev. 166d0adf06c7+ 2021-10-27 01:17:01 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80027
Using CMake version: 3.16.3
Compiled on: Linux 5.10.47-linuxkit
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /azerothcore/env/dist/data/maps. Total size: 252191207 bytes
vmaps directory located in /azerothcore/env/dist/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /azerothcore/env/dist/data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_09_30_00
Using Character DB Revision: 2021_09_25_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Mac OS X, with standard Azerothcore docker builds

**Comment by Kitzunu** [comment]
I'll close this. Basically you need to use the same library version as the server was compiled with.

So in your case, it was compiled with 80027 which means you need to swap out your library 80026 to 80027

**Comment by cromlish4** [comment]
I don't know if this is the right place to ask but how would you go about finding this library and where would you put it for docker on linux? I've tried looking up how to do this but can't find anything information for linux. I have the same versions as the original poster.
