### ISSUE TITLE
[Dungeon finder] Issue with 5-man premade

### ISSUE THREAD

**Issue by syssneck** [azerothcore/azerothcore-wotlk#8812]
### Current Behaviour

When we run dungeons as a 5-man group with the dungeon finder, the last one in the dungeon, that is not in the group anymore, can't leave the dungeon via the df eye and instead gets teleported to the nearest graveyard after 60 seconds (or he can use hearthstone).

### Expected Blizzlike Behaviour

Everyone that queued up via the dungeon finder, should be able to teleport out of the dungeon via the df eye, no matter if it's 5-man premade or not.

### Steps to reproduce the problem

1. Queue up as a 5-man group (random or specific)
2. Do your thing in the dungeon
3. Let everyone else leave the group
4. See that the df eye is not at the minimap anymore
5. See that a message pops up, that says, that your group disbanded and that you will be teleported to the nearest graveyard in 60 s

### AC rev. hash/commit

420ca2e2b57216b90f9

### Operating system

Win 10 x64

**Comment by syssneck** [comment]
@UltraNix: Tested again with PR #8948, but still happens.
The last player will be kicked from the dungeon instead of being able to use the eye to leave it:
![grafik](https://user-images.githubusercontent.com/68868567/140639736-093b4fd0-3dc4-40c7-b284-f9ad44e77af8.png)

**Comment by UltraNix** [comment]
That PR does not resolve this problem.
