### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by Heitortadeu** [azerothcore/azerothcore-wotlk#8819]
### Current Behaviour

![image](https://user-images.githubusercontent.com/58153179/139461364-f53fd909-1159-4ae2-a063-e1dfe667a39c.png)

### Expected Blizzlike Behaviour

erro

### Steps to reproduce the problem

I compiled the current source and ran

### AC rev. hash/commit

Photo

### Operating system

Debian 10 x64

**Comment by acidmanifesto** [comment]
Ah the field should be 18 not 19. I must of fat fingered it before the push on the last pr. I can put in a pr in a hr when i get home
