### ISSUE TITLE
Shadowmelt not work like it shut do

### ISSUE THREAD

**Issue by NoM0Re** [azerothcore/azerothcore-wotlk#8838]
### Current Behaviour

When u use it it does really nothing in a raid, the boss is attacking u when ur in the shadows.
But when u fighting open world against npcs they leave combat.

Also u cannot break a sheep with Shadowmeld

### Expected Blizzlike Behaviour

I think going Out of Combat, like early before
Shut break Sheep and more.

### Source

[Breaked Combat](https://www.youtube.com/watch?v=N0Gj0YncFKg)

### Steps to reproduce the problem

1. Be a Nightelf
2. Go into Combat in ICC/ToC with a Boss
3. Use Shadowmeld
4. See nothing happens

### Extra Notes

Hard to Proof i dont find some material about this.

Thats prob the commit that fucked it: [@ad73b56](https://github.com/azerothcore/azerothcore-wotlk/commit/ad73b564bc6f24c14dd3077fcea9a19c6ce06051)
And
[@ad73b56](https://github.com/azerothcore/azerothcore-wotlk/commit/8c20978449d1bc92a65ab04d02d71e381f2e0691)

### AC rev. hash/commit

b0d4f19

### Operating system

-

### Custom changes or Modules

-

**Comment by Shineslippers** [comment]
Wowwiki [Shadowmeld ](https://wowwiki-archive.fandom.com/wiki/Shadowmeld?oldid=2371539#Patch_changes)
> World of Warcraft: Wrath of the Lich King Patch 3.0.8 (2009-01-20): This ability will now properly restore threat when it is canceled. In addition, it will correctly **remove a player from combat** if it is active when that **player is the last person** left alive that the creature hates.

https://user-images.githubusercontent.com/85256266/139533332-a905885a-99cb-4e26-bbe9-c1f3ab795bdf.mp4

**Comment by NoM0Re** [comment]
Ok, i accept that. 
But when u are a Nightelf Cat u are with a group in combat, u use Shadowmelt go catform then cat stealth then it he shut not see you?

**Comment by Shineslippers** [comment]
Same wiki. Using stealth doesn't break combat as feight death.
> Using shadowmeld will temporarily remove you from combat. When you cancel the effect, all aggro that was held towards you is restored.
With timing and attention to patterns, many mob patrols may be evaded in Shadowmeld. Hunters can combine the skill with Feign Death (to break combat) to solo instances, while Rogues and Druids could simply stealth.

**Comment by NoM0Re** [comment]
Ok i just hate that change :) Patch 3.0.8 was better...

**Comment by NoM0Re** [comment]
What about that:
With timing and attention to patterns, many mob patrols may be evaded in Shadowmeld. Hunters can combine the skill with Feign Death (to break combat) to solo instances, while Rogues and Druids could simply stealth.

**Comment by NoM0Re** [comment]
Anyway i delete it

**Comment by Shineslippers** [comment]
Well it's sounds like ingame mechanic, If you spending a lot of time to something this is feels like blizzlike. Anyway i can't nothing to do just with words. Need more research.
