### ISSUE TITLE
NPCs aren't attacking while Aggro

### ISSUE THREAD

**Issue by NoM0Re** [azerothcore/azerothcore-wotlk#8839]
### Current Behaviour

Go to NPC with SightAggro(not every). He will not attack u until u attack him.
Tested in Northend.

https://user-images.githubusercontent.com/1629787/139532443-a8d7e929-eeb7-4c5b-91cf-6eae18812612.mp4

### Expected Blizzlike Behaviour

Attack Player when in Aggrorange.

### Steps to reproduce the problem

1. Go to NPC with SightAggro (not every)
2. He will not attack u unitly u attack him.

### AC rev. hash/commit

b0d4f19

### Operating system

-

### Custom changes or Modules

-

**Comment by Shineslippers** [comment]
Idk what is Sight Aggro. Can you explain? Which mobs has it? I'm unable to reproduce it on local AC

https://user-images.githubusercontent.com/85256266/139543302-823312c7-43f5-4a56-b6e0-c388f23512b5.mp4

**Comment by NoM0Re** [comment]
Do u have the newest?

**Comment by Shineslippers** [comment]
29/10 14:05

**Comment by NoM0Re** [comment]
Ok. So its a Server Problem then. Thanks for Testing it.

**Comment by Shineslippers** [comment]
Let me know if it will happen after update. That's interesting issue.
