### ISSUE TITLE
[Druid/Spell]Moonkin Form have half chance proc mana restore when not equip two hands weapon

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8851]
### Current Behaviour

RT

### Expected Blizzlike Behaviour

chance should be same

### Steps to reproduce the problem

1.Use a Druid and Cast Moonkin Form
2.Equip double hand weapon
3.Combat with Heroic Training Dummy
4.See mana restore proc

5.Equip one hand or main hand weapon and offhand
6.Combat with Heroic Training Dummy
7.See mana restore proc

### AC rev. hash/commit

a25eae3

### Operating system

Windows 10 x64

**Comment by bgcfb** [comment]
It's an old problem and confirmed

**Comment by Shineslippers** [comment]
I would say invalid
<details>
<summary>Spoiler</summary>

![WoWScrnShot_103121_153755](https://user-images.githubusercontent.com/85256266/139584234-1e0c2258-5d63-4443-8420-cb21d928f598.jpg)
![WoWScrnShot_103121_153851](https://user-images.githubusercontent.com/85256266/139584238-bdb68ae3-fd0e-49c8-8b08-0aa10f419d47.jpg)
![WoWScrnShot_103121_154004](https://user-images.githubusercontent.com/85256266/139584241-18f5939b-c359-42da-95af-b3ac25534a1a.jpg)
![WoWScrnShot_103121_154135](https://user-images.githubusercontent.com/85256266/139584243-fa5db5f5-ef7c-4724-a753-f9b082aab1cc.jpg)
![WoWScrnShot_103121_154316](https://user-images.githubusercontent.com/85256266/139584244-dcfc993d-4359-4d69-934f-dea966185821.jpg)
![WoWScrnShot_103121_154424](https://user-images.githubusercontent.com/85256266/139584247-a67a936f-02f3-4cb5-aefb-3d4dbc43a4d6.jpg)
![WoWScrnShot_103121_154527](https://user-images.githubusercontent.com/85256266/139584248-c4d45cd1-5265-4675-9f3f-90120d36295f.jpg)
![WoWScrnShot_103121_154622](https://user-images.githubusercontent.com/85256266/139584249-470ee8c2-e7a7-4710-9688-149ce59cb9ff.jpg)
![WoWScrnShot_103121_154720](https://user-images.githubusercontent.com/85256266/139584250-a803d608-651b-4cf8-bb03-13197e530601.jpg)




</details>

**Comment by bgcfb** [comment]
@Shineslippers not mana restoring per time,you should test it's chance

**Comment by bgcfb** [comment]
@Shineslippers Your crit chance is 422% guy~
I tested with My druid which is only 29% crit chance

**Comment by bgcfb** [comment]
@Shineslippers And I could see you use cheat cooldown,it's affected the test result.

**Comment by Shineslippers** [comment]
1. Amount of restored mana is in direct dependence of procs. Mana = Procs.
2. 422% crit just mean every my Wrath is crit. We're testing proc chance of Monkin form. We're not testing my luck to get crit.
> Single target **spell critical strikes** in this form have a chance to instantly regenerate 2% of your total mana.
3. Cheats not affecting the Test. It's gimme ability to do test faster.

**Comment by bgcfb** [comment]
@Shineslippers NO,Cheats affecting cooldown,the mana restore proc seems have cooldown

**Comment by Shineslippers** [comment]
I added label "Help Wanted". If someone will check it also we can decide what to do next. I could be wrong when saying my test is correct, but right now i don't think so.

**Comment by bgcfb** [comment]
@Shineslippers pls look at this

![image](https://github.com/bgcfb/image/blob/master/17-1885.png?raw=true)
![image](https://github.com/bgcfb/image/blob/master/17.png?raw=true)
**one hand weapon with 17 crit and 1885 mana restored???**
================================================
![image](https://github.com/bgcfb/image/blob/master/31-93.png?raw=true)
![image](https://github.com/bgcfb/image/blob/master/31.png?raw=true)
**two hands weapon with 31 crit and 9392 mana restored**

**Comment by bgcfb** [comment]
It's comfirmed by many player in different servers

**Comment by Shineslippers** [comment]
Ok, more tests without extras. Only [Moonkin](https://wowgaming.altervista.org/aowow/?spell=24858) and [Wrath](https://wowgaming.altervista.org/aowow/?spell=48461). No talents, items and etc. Overal something like +30% to proc chance with two-handed.

<details>
<summary>Spoiler</summary>

![WoWScrnShot_103121_173346](https://user-images.githubusercontent.com/85256266/139589195-c43848b0-ace2-454d-9a9c-6f3e16d93905.jpg)
![WoWScrnShot_103121_173802](https://user-images.githubusercontent.com/85256266/139589202-7d1d7563-4c85-4fee-bf15-78dcb72c7a2e.jpg)
![WoWScrnShot_103121_174020](https://user-images.githubusercontent.com/85256266/139589204-fc950d1a-4b6e-4da3-bdde-5555b37551e9.jpg)
![WoWScrnShot_103121_174048](https://user-images.githubusercontent.com/85256266/139589206-e4775018-aacb-4058-a5da-f6b9643651d1.jpg)
![WoWScrnShot_103121_174127](https://user-images.githubusercontent.com/85256266/139589207-cd9b5129-c28a-4b01-9abf-b9b8f0e51dcb.jpg)
![WoWScrnShot_103121_174204](https://user-images.githubusercontent.com/85256266/139589209-1d60c667-6438-4349-a9d5-cb8860d97133.jpg)
![WoWScrnShot_103121_174234](https://user-images.githubusercontent.com/85256266/139589210-93a8d7fd-0ccf-4ec0-9c91-85ac860b8ad5.jpg)
![WoWScrnShot_103121_174307](https://user-images.githubusercontent.com/85256266/139589211-48762fd7-6243-4121-8086-4ee0c12c5468.jpg)
![WoWScrnShot_103121_174334](https://user-images.githubusercontent.com/85256266/139589213-66daf68f-40fd-4add-ad85-e4e78ef17881.jpg)
![WoWScrnShot_103121_174402](https://user-images.githubusercontent.com/85256266/139589214-478c66f3-de71-4e16-9b6f-121e01422983.jpg)
![WoWScrnShot_103121_174514](https://user-images.githubusercontent.com/85256266/139589215-813b659f-78d7-4eda-9c17-a8c96f417d82.jpg)
![WoWScrnShot_103121_174537](https://user-images.githubusercontent.com/85256266/139589216-1124448f-4be2-402f-8566-374b0ac0ed53.jpg)
![WoWScrnShot_103121_174615](https://user-images.githubusercontent.com/85256266/139589217-a34af0a5-767e-46e4-860e-5c62cea4bf6a.jpg)
![WoWScrnShot_103121_174644](https://user-images.githubusercontent.com/85256266/139589218-43225f9e-751f-46af-acdf-5c9508a91129.jpg)
![WoWScrnShot_103121_174712](https://user-images.githubusercontent.com/85256266/139589219-3ef414a5-13a5-4216-a2dc-77df7d10a40e.jpg)
![WoWScrnShot_103121_174750](https://user-images.githubusercontent.com/85256266/139589222-2eeab8f2-7e2e-4442-924b-be64aaf4db23.jpg)
![WoWScrnShot_103121_174821](https://user-images.githubusercontent.com/85256266/139589223-5f1f144c-0534-4827-92cf-f521e1e63c50.jpg)


</details>

**Comment by bgcfb** [comment]
@Shineslippers thx for your test

**Comment by UltraNix** [comment]
@bgcfb @Shineslippers So what is the problem here: the chance of mana restor or the amount of restore mana???

**Comment by Shineslippers** [comment]
@UltraNix Chance. It's have less procs for the same amount of crits

**Comment by UltraNix** [comment]
Weird -weapon type should not have any infuence on that.

**Comment by Shineslippers** [comment]
Well idk. Look to my screenshots. ~100 crits gives more mana with two-handed, while amount of proc 129 everywhere.

**Comment by UltraNix** [comment]
It's impossible. 100x129 is always the same :P

**Comment by UltraNix** [comment]
Really - I don;t what and how to test it. I don't understand that bug at all :P

**Comment by UltraNix** [comment]
Hmm, as I can see there is a pmm set to it - 15.

**Comment by Shineslippers** [comment]
Look [Moonkin Form](https://wowgaming.altervista.org/aowow/?spell=24858)
> Single target spell critical strikes in this form have a chance to instantly regenerate 2% of your total mana

.aura 24858
make 100% crit - i added crit to ring
now every wrath is crit
.cast 5176 ~ 100 times
total amount of restored mana = times of aura proc
more mana = more procs
