### ISSUE TITLE
[Scholomance] Kirtonos the Herald is unattackable

### ISSUE THREAD

**Issue by jamadaha** [azerothcore/azerothcore-wotlk#8852]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2221

[Kirtonos the Herald](https://classic.wowhead.com/npc=10506/kirtonos-the-herald) in Scholomance has been bugged for a few days now. A week ago I killed him twice and everything was alright, but when you summon him now, he cannot be attacked. He's just [flying around](https://imgur.com/a/qvbLzmV) killing everyone in the party.

@Shineslippers Adds:
> Yea, old script worked cool. Now you getting combat while using object and Kirtonos instead of following script flying to you. Because script is not finished you can't attack him.

https://user-images.githubusercontent.com/85256266/139576487-97a38818-4737-4abb-bbf5-57e5a43f125b.mp4

Tester: Confirmed

### Expected Blizzlike Behaviour

Kirtonos can only be summoned if a person in your group has Blood of Innocents. First, you have to light the torch. Then, after a short cutscene, he comes up and starts attacking the group.

### Source

https://classic.wowhead.com/
https://tbc.wowhead.com/

### Steps to reproduce the problem

1. .tele Scholomance
2. Use [Blood of Innocents](https://tbc.wowhead.com/item=13523/blood-of-innocents) on the torch
3. Wait for Kirtonos to come up

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
On the bright side, the PR that was supposed to improve this boss is not merged yet. I'll have a look if it's present there and do a short investigation if needed. https://github.com/azerothcore/azerothcore-wotlk/pull/8401
