### ISSUE TITLE
Loot while stealthed (rogue + druid)

### ISSUE THREAD

**Issue by lingxDEV** [azerothcore/azerothcore-wotlk#8853]
### Current Behaviour

You can enter Stealth / Prowl and loot a mob without Stealth / Prowl being cancelled.

### Expected Blizzlike Behaviour

When looting Stealth should be cancelled.

### Source

![image](https://user-images.githubusercontent.com/62337627/139578167-5d5ca600-07f5-4614-adf0-92f6769e1430.png)

https://wowpedia.fandom.com/wiki/Stealth

Test on any retail version of the game. It's always been the case.

### Steps to reproduce the problem

1. Kill an NPC
2. Enter Stealth / Prowl
3. Loot NPC
4. Stealth / Prowl is not cancelled

### AC rev. hash/commit

39bfe880f49f

### Operating system

Win 10 x64

### Custom changes or Modules

None

**Comment by Shineslippers** [comment]
Indeed



https://user-images.githubusercontent.com/85256266/139581436-0545a7e1-cd21-41a8-b755-9e87657aee48.mp4


,
