### ISSUE TITLE
[Uldar]10 man Raid team got first blood title Death's Demise and Celestial Defender

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8854]
### Current Behaviour

Title 158 and 159 can get in 10man Raid with out achievement Realm First! Celestial Defender and Realm First! Death's Demise

### Expected Blizzlike Behaviour

Title Death's Demise and Celestial Defender should Only gain in 25manRaid  Uldar and from Achievement Realm First! Celestial Defender and Realm First! Death's Demise

### Steps to reproduce the problem

1.Kill 10man yogg and 10man algalon

### AC rev. hash/commit

a25eae3

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
That's confirmed. You can get Realm First and not being Real First.

**Comment by avarishd** [comment]
@Kitzunu Old/Fixed
The 2 achievements are only given in 25m
Criteria ID  -- Achievement ID
10279 -- [Yogg 3117](https://db.rising-gods.de/?achievement=3117)
10698 -- [Algalon 3259](https://db.rising-gods.de/?achievement=3259)
![42dfbdb8dedbdc9e245350b0a9db1c5b](https://user-images.githubusercontent.com/46330494/169695221-bfd630e1-85a1-40c7-962f-1536f0d43ec8.png)

![e967b57c18064a036a912cd53e42fc94](https://user-images.githubusercontent.com/46330494/169696249-8bf0b71b-4f39-4ad2-8549-6ed13128f371.png)
![ae06f4e7fbef80e4d381f0f648297b79](https://user-images.githubusercontent.com/46330494/169696271-c160f742-6092-4adb-b81b-d73ebed9f542.png)
