### ISSUE TITLE
Need to improve VMAPS\MMAPS (CORE\MAPS)

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#8857]
### Current Behaviour

**VMaps** ("Virtual Maps") calculate the possibility of line-of-sight, as an example. Based on their content, the server can (for example) calculate if spell casts are possible (e.g. if a wall is in between the target and caster or not).

**MMaps** are optional, but HIGHLY recommended. To further physical boundaries, MMaps ("Movement Maps") enforce physical boundaries on non-player characters, e.g. NPCs, as their collision is not handled by the client. They also improve path generation. Even though our mmaps are decent currently althought slightly out of date, they can not be generated without vmaps. Our current issue is with vmaps.

Currently a few issues and spells are brough up dealing with undermeshing issues, namely any spell that relies on vmaps and los, such as warriors charge, druids charge, and most infamaniously BLINK.

They suffer various issues such as undermeshing, not being able to perform above high elevations over and facing lower evelation and vice versa, or the issue dealing with water involved., and facing the wrong way. 

**Reported Issues:** https://github.com/azerothcore/azerothcore-wotlk/issues/6232 https://github.com/azerothcore/azerothcore-wotlk/issues/6427 https://github.com/azerothcore/azerothcore-wotlk/issues/7072

**Users Valrous attempt at PR:** https://github.com/azerothcore/azerothcore-wotlk/pull/8692 
Although the attempts for spot fixes to correct them is highly admirable the approach is wrong and doesnt address the underlying issues of VMaps needing to be addressed and updated along with proper map calculation handling in the core.

A private attempt i used before only in tc based projects was a pr i have done dealing with corrected vmap calculations.
**My Map Calculation PR:** https://github.com/azerothcore/azerothcore-wotlk/pull/8775

However, even though this fully corrects, warriors charge, druid charge, and blink in many aspects, the vmaps are not up to date dealing with line of sight gameobjects which was needed if a spell cast is to be limited or restricted due to such thing as a wall and other stuff.

TL:DR:
VMAPS deals with LOS map caluation spells and needs improvements or any and all fixes dealing with vmaps spells will only become spot fixes that does not fix the underlying issues of vmap related caluated spells and ability in not working properly when dealing with terran and water and elevation.

### Expected Blizzlike Behaviour

We need improvements to VMaps dealing with line-of-sight gameobjects objects to prevent further undermeshing of toons using select vmap reliant spells\abilities.

### Source

https://github.com/azerothcore/azerothcore-wotlk/pull/8775

### Steps to reproduce the problem

1. Using my PR on a VS windows compile https://github.com/azerothcore/azerothcore-wotlk/pull/8775
2. Test Warriors charge\Druid blink in various terrain scenarios
3. test blink in various terran scenario
4. take notes of improvements and regression dealing with teleporting vmap base spell (Blink) and physical movement vmap base spell (Warrior\Druid charge).
5. Notice blink is hte only one that meshes and clips thru game objects, most noticible spots, blink towards a building or on the stone bridge of stromwind.  

### Extra Notes

Currently our vmaps are 4.6 https://github.com/azerothcore/azerothcore-wotlk/blob/667c294557e6bfbcc3ca63bbc6dcb0f4cef30988/src/common/Collision/VMapDefinitions.h#L26 
compared to tc 4.8 https://github.com/TrinityCore/TrinityCore/blob/e4430cd2bedf2079961bd1a30ba9f5f1de93af82/src/common/Collision/VMapDefinitions.h#L27.

Currently our mmap versions are v12 
https://github.com/azerothcore/azerothcore-wotlk/blob/667c294557e6bfbcc3ca63bbc6dcb0f4cef30988/src/common/Collision/Maps/MapDefines.h#L16
compared to tc mmap versions are v15
https://github.com/TrinityCore/TrinityCore/blob/e4430cd2bedf2079961bd1a30ba9f5f1de93af82/src/common/Collision/Maps/MapDefines.h#L25

The many private tc projects i been involved with uses a minimal of vmaps 4.8 and mmaps 8 at the earliest. for my calculations to be fully sucessiful at a minimal.

In other words, we need the vmaps moved up in AZ case.

### AC rev. hash/commit

667c294 stock is where the issues are currently.
bfd197f is the current pr i have addressing the issues which fixes all issues except for the issues with blink undermeshing due to vmaps.

### Operating system

Windows 10 x64 Pro

### Custom changes or Modules

None outside of my PR which is pretty much stock with my map calculation changes https://github.com/azerothcore/azerothcore-wotlk/pull/8775

**Comment by FrancescoBorzi** [comment]
cc @Yehonal @Winfidonarleyan @Footman @FALL1N1

**Comment by patou01** [comment]
Are bugs like this one https://drive.google.com/file/d/1VQoMll-s8y3EdbQs6g6KOlvh5rSoQyb3/view?usp=sharing expected to be fixed through this or do we expect to have issues in the pathfinding algorithms on top of it?

**Comment by acidmanifesto** [comment]
> Are bugs like this one https://drive.google.com/file/d/1VQoMll-s8y3EdbQs6g6KOlvh5rSoQyb3/view?usp=sharing expected to be fixed through this or do we expect to have issues in the pathfinding algorithms on top of it?

Im to understand that is a mmap issue, most pathfinding are usually adjusted with using recast demo from my understanding. I could more or less be lacking a few more details on that particular matter.

**Comment by sschepens** [comment]
My PR fixing warrior's charge fixes a bunch of issues which I think are not related to VMaps.

Like land correctly facing the target.

I think both changes are necessary.

**Comment by acidmanifesto** [comment]
> My PR fixing warrior's charge fixes a bunch of issues which I think are not related to VMaps.
> 
> Like land correctly facing the target.
> 
> I think both changes are necessary.

currently the map calculations does have the warriors charge land correctly and facing the target with no further alterations.

**Comment by acidmanifesto** [comment]
@FrancescoBorzi @sschepens 
Current this is how it looks with my map calculations PR https://github.com/azerothcore/azerothcore-wotlk/pull/8775
Show casing Warrior's charge and Blink below:

Warriors Charge:
https://youtu.be/znHdW1R_9zM

Blink with the vmap issues at the end:
https://youtu.be/lOamL5nAveU

So far only blink suffers the issues as we need to have the vmaps be in line with version 4.8

**Comment by FALL1N1** [comment]
Can you paste the output of ".gps" from the bridge as well as the place you blink at, please?

We had issues before with the groundZ coord which is from the vmaps and it did not work at some places.

**Comment by acidmanifesto** [comment]
> Can you paste the output of ".gps" from the bridge as well as the place you blink at, please?
> 
> We had issues before with the groundZ coord which is from the vmaps and it did not work at some places.

you need a .gps before and after blink?
and do you need me perform it from the bridge to the water? off the bridge? into the bridge?
Let me know please, i will be more then happy to do a vid recording, i just want to make sure i cover what you need to look at.

**Comment by FALL1N1** [comment]
A screenshot would be more than enough, one ".gps" at the top of the bridge and another after you blink inside the water.

**Comment by acidmanifesto** [comment]
> A screenshot would be more than enough, one ".gps" at the top of the bridge and another after you blink inside the water.


On top of bridge before blink:
![image](https://user-images.githubusercontent.com/16887899/139705375-72c02a66-5287-40c4-ae12-7bbabac009fa.png)
After blink:
![image](https://user-images.githubusercontent.com/16887899/139705447-a6434c98-7d70-47b7-af84-ddc16fb8bb4e.png)

**Comment by acidmanifesto** [comment]
Before blink in the water:
![image](https://user-images.githubusercontent.com/16887899/139705743-de6d3ad2-bc0d-4a56-bbcf-947b279fdaaa.png)

After blink from water position:
![image](https://user-images.githubusercontent.com/16887899/139705833-43154f92-b4fc-4ba0-b194-ea0c1240aa1b.png)

**Comment by FALL1N1** [comment]
Yes, it looks like there's missing mesh or w/e it's called at that exact spot, the "Ground" shouldn't be "-1000000"

**Comment by sschepens** [comment]
> currently the map calculations does have the warriors charge land correctly and facing the target with no further alterations from any other pr.

@acidmanifesto this PR does not fixes Charge entirely, my PR is still necessary, look at this behaviours:
https://youtu.be/AgYmph0wXto
https://youtu.be/K6SxpTHsVTQ

This issues are not related to V/Mmaps but to current issues in pathfinding.

**Comment by acidmanifesto** [comment]
> > currently the map calculations does have the warriors charge land correctly and facing the target with no further alterations from any other pr.
> 
> @acidmanifesto this PR does not fixes Charge entirely, my PR is still necessary, look at this behaviours: https://youtu.be/AgYmph0wXto https://youtu.be/K6SxpTHsVTQ
> 
> This issues are not related to V/Mmaps but to current issues in pathfinding.

Can you provide me the guid of those creature for me to check out

**Comment by sschepens** [comment]
`.go c 10904`
`.go c 10904`

**Comment by sschepens** [comment]
The issues with those creatures appear unrelated to your changes.

In the first one, the current pathing mechanism Charge is using is selecting a weird point of contact, which causes us to charge through the target into that position we selected. When in fact, what should be done is select a point of contact in a valid path towards the target.

The second one is actually a bug in a couple a places first of all PathGenerator which is not building shortcuts when units are floating on top of water and a bug in `Unit::canSwim` which makes it return false inappropriately.

This is why I think my PR is still necessary.

**Comment by acidmanifesto** [comment]
So currently i can see what you mean by facing the wrong direction. with my end of test.
I am however seeing a parry being done on my end.
https://youtu.be/e-2dB4Z9lys

Now as for the murlocs in the water:
https://youtu.be/tyVTCwTyvRY

However my case on the calculations was mainly for undermeshing issues. Im not entirely certain if i caugh all the scenarios you showed in your video, but let me know so we can try to target different things together.

**Comment by sschepens** [comment]
Yes, you reproduced both cases correctly. The murloc case is when you get No Path Available when charging from the top of the water to a creature underwater, that shouldn't happen.

But as I said, those are not mapping issues, they are pathing issues and are already addressed on my PR.

Let me know if I can help you with anything, I think my PR is ready and fixes those issues as well as some undermeshing, but only charge related.

**Comment by acidmanifesto** [comment]
Point me a link to your prs and i will test them tomorrow with the map calculations and see if we can stomp out the issues finally.

**Comment by sschepens** [comment]
@acidmanifesto this is my PR https://github.com/azerothcore/azerothcore-wotlk/pull/8692

I should probably change the title since it's actually fixing a bunch of Charge issues and not only clipping.

**Comment by Mitradis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/2207 including refers to this problem

**Comment by sschepens** [comment]
@acidmanifesto why don't we just update our maps to TC maps?

**Comment by UltraNix** [comment]
No need to have multiple opened issues about the same.
