### ISSUE TITLE
NPC reset and health regeneration

### ISSUE THREAD

**Issue by lingxDEV** [azerothcore/azerothcore-wotlk#8861]
### Current Behaviour

When an NPC resets with, it will slowly regenerate health instead of going to max health instantly.

### Expected Blizzlike Behaviour

When an NPC resets it should get full hp instantly.

### Source

You can test this on any version of the game on retail, always worked like this.

### Steps to reproduce the problem

1. Go to an NPC attack it down to 20% hp
2. .gm on
3. Notice when the NPC resets it will slowly regain it's health over a few seconds

### Extra Notes

Here is a related PR that fixed this exact issue on TC. Also describes it in more detail.
https://github.com/TrinityCore/TrinityCore/commit/62e7d7042cece5561f6ff7b9011c5553c6cd4741

### AC rev. hash/commit

39bfe880f49f

### Operating system

Win 10 x64

### Custom changes or Modules

None

**Comment by T1ti** [comment]
From my experience on Classic versions they slowly regen and your PR is for Master TC which is for retail versions

**Comment by T1ti** [comment]
https://gyazo.com/c0fbe693e02544fa67c17657ca280bca TBC classic

**Comment by malcrom** [comment]
SetFullHealth(); if required in script for a transform to entry. Other than that it is normal.
