### ISSUE TITLE
Crash on Blessing of Ancient Kings + Renew spells

### ISSUE THREAD

**Issue by AipNooBest** [azerothcore/azerothcore-wotlk#8864]
### Current Behaviour

Server instantly crashes. I couldn't obtain any logs, the console writes only one line: `Segmentation fault (core dumped)` and nothing else even with Debug build
![image](https://user-images.githubusercontent.com/47401054/139607865-ea99a371-b15b-467f-ab03-ab81f4870753.png)

### Expected Blizzlike Behaviour

Not to crash?

### Steps to reproduce the problem

Just cast two spells: Blessing of Ancient Kings(64411) and Refresh(48068)
```
.cast 64411
.cast 48068
```

### AC rev. hash/commit

[`667c294`](https://github.com/azerothcore/azerothcore-wotlk/commit/667c294557e6bfbcc3ca63bbc6dcb0f4cef30988)

### Operating system

Ubuntu 20.04

**Comment by Kitzunu** [comment]
Need crashlog

**Comment by AipNooBest** [comment]
Here's the crashlog
https://gist.github.com/AipNooBest/2d6eb3ee3f7b25ef8c96166474a9fbbe
