### ISSUE TITLE
Crash on startup (debug mode)

### ISSUE THREAD

**Issue by Cinnamohn** [azerothcore/azerothcore-wotlk#8865]
### Current Behaviour

The worldserver crashes on startup.
![worldserver_UqL8Im4UEj](https://user-images.githubusercontent.com/51275113/139608830-8750bd88-16e7-4c50-a7e0-6bc732e5d5bf.png)

### Expected Blizzlike Behaviour

It shouldn't.

### Source

![worldserver_33SQRskgnp](https://user-images.githubusercontent.com/51275113/139608950-f700b754-0d01-49b0-84de-34960271de19.png)

### Steps to reproduce the problem

I don't know what the exact conditions are for this to occur.

### Extra Notes

Here is a snippet of my crash log. This line of code was implemented with #6243
![notepad++_ZixM7Haagj](https://user-images.githubusercontent.com/51275113/139608995-81d75e85-d224-45e6-b006-a084cf239bae.png)

Reverting to the commit prior resolved the issue.

### AC rev. hash/commit

9ef0aa8

### Operating system

Windows 10 x64

**Comment by w5860363** [comment]
Confirmation
The spell_custom_attr database does not currently support debug mode
Only Release can be used to start
According to the error message, the assignment exceeds the number of columns

**Comment by Cinnamohn** [comment]
Learn something new everyday. Swapping to RelWithDebInfo, as is clearly written in the installation guide, fixed it.

**Comment by Kitzunu** [comment]
@Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
Need fix this
```
TOTAL_AURAS must be at least 397, spellIndex 78142
TOTAL_AURAS must be at least 375, spellIndex 78142
TOTAL_AURAS must be at least 376, spellIndex 78142
TOTAL_SPELL_EFFECTS must be at least 168, spellIndex 78951
TOTAL_AURAS must be at least 332, spellIndex 79342
TOTAL_SPELL_TARGETS must be at least 119, spellIndex 79579
```
