### ISSUE TITLE
[Spell/Hunter]SnakeTrap does'nt work

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#8866]
### Current Behaviour

After SnakeTrap was triggered , snakes always followed with hunter.

### Expected Blizzlike Behaviour

snake should attack around the trigger one, until combat finish.

### Steps to reproduce the problem

1. get  a hunter with spell snaketrap
2. place the trap under a target who can trigger it
3. run everywhere and watch the snake ,

### AC rev. hash/commit

109672b7c505+

### Operating system

Ubuntu 20.04

**Comment by SKingOWN** [comment]
Confirmed

**Comment by bgcfb** [comment]
Duplicated #8590

**Comment by Shineslippers** [comment]
Duplicate. I will close this report accordingly.
