### ISSUE TITLE
[Core/unit] Warrior - No Rage generation with blocks / parry / dodges

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#8867]
### Current Behaviour

Warriors do not generate rage when blocks / parry / dodges.

http://www.wowwiki.com/1.3.0
`Fixed a bug where rage was not being generated when normal melee attacks were parried, dodged, and blocked.`

### Expected Blizzlike Behaviour

Warriors should generate rage when blocks / parry / dodges.

### Steps to reproduce the problem

Get Warrior
Get Damage Hits
blocks / parry / dodge the hits
no rage

### Extra Notes

None

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/192360a3a583162c6cb8fabdc09adbaa70018788

### Operating system

Windows 10 x64,

### Custom changes or Modules

None

**Comment by Shineslippers** [comment]
Do you mean in general or [Shield Specialization]( https://wowgaming.altervista.org/aowow/?spell=12298). Talant is working correct.

**Comment by w5860363** [comment]
@Shineslippers 
http://www.wowwiki.com/1.3.0
It has nothing to do with talant and spell. Weapon attacks are parried at present and will not gain any rage. This is inconsistent with the patch in 1.3, and no subsequent patch has been found to change it
