### ISSUE TITLE
First Sergeant Hola'mahi selling more items than should

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8869]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2225

Both PvP set vendors made available for the classic PvP set also offer the lvl 58 melee ring and lvl 58 1hand sword - but with prices different from the adjusted prices they are offered at the other vendors.
Ring is 3k honor cheaper, Sword is 5k more expensive
![WoWScrnShot_110121_080520](https://user-images.githubusercontent.com/12682004/139634694-14f9b622-c5bf-4afe-a90b-718c53110332.jpg)
![WoWScrnShot_110121_080529](https://user-images.githubusercontent.com/12682004/139634699-a6a20813-459e-45a4-aba9-bdafd28f1ac9.jpg)
![WoWScrnShot_110121_080540](https://user-images.githubusercontent.com/12682004/139634700-f2d88498-8413-498e-9924-6fd3afb2bd1f.jpg)

Tester:

The issue is confirmed on Horde side. First Sergeant Hola'mahi selling ring and sword. It has different prices compare to other vendor.

### Expected Blizzlike Behaviour

[First Sergeant Hola'mahi](https://wowgaming.altervista.org/aowow/?npc=12795) should not selling [Legionnaire's Band](https://wowgaming.altervista.org/aowow/?item=19510) and [Legionnaire's Sword](https://wowgaming.altervista.org/aowow/?item=19550)

### Source

X

### Steps to reproduce the problem

.go c id 12795

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Asthalor** [comment]
Looks like it was fixed.
Tested on AzerothCore rev. d25992da5f5e 2021-11-26 01:18:27 -0300 (master branch) (Win64, RelWithDebInfo, Static) ingame and checked the DB with `SELECT * FROM `npc_vendor` WHERE (`entry` = 12795) AND item IN(19510, 19550);`

**Comment by Shineslippers** [comment]
No, it's not. I made report to AC instead of progression module. Still issue to CromieCraft server.

**Comment by Asthalor** [comment]
Weird, i checked on the AC server and i could not find those items. Does the progression module runs on other database?

**Comment by Shineslippers** [comment]
Well i'm not dev. I can link you description xD https://github.com/azerothcore/mod-progression-system
> It allows to load scripts and sql files automatically dependent on level brackets. It means that once you defined in config which level brackets should be present, all c++ scripts from these brackets are loaded and replaced with "normal" scripts in AzerothCore.
