### ISSUE TITLE
Energy tick speed

### ISSUE THREAD

**Issue by Err0r1** [azerothcore/azerothcore-wotlk#8870]
### Current Behaviour

At the moment, energy increases by 20 per tick (2 seconds)

### Expected Blizzlike Behaviour

Energy should increase by 1 per decisecond

### Source

https://wowwiki-archive.fandom.com/wiki/Energy

### Steps to reproduce the problem

Create a rogue
Go to a dummy
Cast Sinister Strike
Look at energy

### AC rev. hash/commit

7c363c904071099f009572c1b160247bfd4e9650

### Operating system

Debian 10

**Comment by Shineslippers** [comment]
Wowwiki [Energy](https://wowwiki-archive.fandom.com/wiki/Energy?oldid=2326753#Patch_changes)
> World of Warcraft: Wrath of the Lich King Patch 3.0.3 (04-Nov-2008):  Regeneration went from 20 energy per tick to 1 energy per decisecond.
