### ISSUE TITLE
Module issues - Premium and Transmog 

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#888]
**Description**: There are few small issues with Premium '''email''' and Transmog when people have enchants on.

**Current behaviour**:
1. When player trying to use in-game email via Premium command, nothing happen. U can't send or receive mail items or etc trough premium option.
2. Really weird issue with Transmog - When players try to enchant their gear, stats not going up at all. It only happen if an item is transmogged.

**Expected behaviour**: 
1. Mail should work any other out there.
2. Strats should change - Its not big issue cause players can de-transmog enchanted item.

**Steps to reproduce the problem**:
1. Not sure, will leave to module makers.

**AC hash/commit**:  7ec74c2

**Operating system**:  Linux, Debian 9

**Modules**: Premium, Congrats on level, Transmog

**Other Customizations**: No

**Comment by Deku** [comment]
Please open these issues on each of the corresponding repositories. This repo (azerothcore/azerothcore-wotlk) it's only for issues related to the core (vanilla game).
