### ISSUE TITLE
Change of target interrupt Volley channeling

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8883]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1912

Hunter Volley gets interrupted by Auto-Shot when switching targets while channeling the spell. Auto-Shot should not be triggering / breaking Volley cast when channeling and switching targets, no matter if you have Auto-Shot on in Interface > Combat settings.

It is possible to bypass this problem by macroing it with /stopattack before /cast Volley or just turning Auto-Shot completely off from settings but I believe it is still bug, though not game-breaking.

Tester:
The issue is confirmed. Change of target while [Volley](https://wowgaming.altervista.org/aowow/?spell=1510) interrupt channeling of it.

https://user-images.githubusercontent.com/85256266/139760452-95b49d3e-df8a-47f3-a5b4-701af739d7cf.mp4

### Expected Blizzlike Behaviour

Switching targets should not let Auto-Shot be cast and break Volley cast while channeling. 

### Source

Well if we decided Auto Attack is ok to Volley(https://github.com/azerothcore/azerothcore-wotlk/issues/7067). So probably change of target should not affect Volley.

### Steps to reproduce the problem

1. Start Auto-Attacking a target, for example training dummy.
2. Start channeling Volley.
3. Switch target to any other target that you are able to attack from where you are channeling.

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Hunter cannot use auto shot with Volley. #7067 is already fixed.

**Comment by Shineslippers** [comment]
I don't understand. Isn't https://github.com/azerothcore/azerothcore-wotlk/issues/7067 mean you can use it while volley? Do you wanna say autoshot before volley not the same? Whatever. then i  interpreted your words wrong, You can close it then.

**Comment by UltraNix** [comment]
#7067 is okay now - Volley interrupts Auto shot.

**Comment by Shineslippers** [comment]
@UltraNix Same as you i don't know. I can just assume. 

- When you trying to Auto Attack while channeling it's saying: "Can't attack while channeling"

https://user-images.githubusercontent.com/85256266/141655250-867d0510-3cc3-4880-a363-2db341eb8332.mp4

- When you trying to Auto Shot while channeling it's interrupting channeling

https://user-images.githubusercontent.com/85256266/141655262-204ee6bc-1654-40d3-b0c9-fe76266e37a6.mp4

My guess there: AA and AS shoudl work the same. But one more opinion on this will be good.
