### ISSUE TITLE
Jero'me something is wrong with gossip, second answer is wrong

### ISSUE THREAD

**Issue by b0bzzter** [azerothcore/azerothcore-wotlk#8888]
### Current Behaviour

When you talk to Jero'me https://wowgaming.altervista.org/aowow/?npc=19882 it seems like second answer is missing
![WoWScrnShot_102821_165137](https://user-images.githubusercontent.com/92752311/139804643-4d67974c-a3f2-4824-af3d-2b0e06d4d100.jpg)
.

### Expected Blizzlike Behaviour

Both answers should be clearly visible.

### Steps to reproduce the problem

1. go to Jero'me at Silvermoon City entrance and talk to him,
2. check the answers

### AC rev. hash/commit

AzerothCore rev. 2f25323456f7

### Operating system

ArchLinux lts kernel

### Custom changes or Modules

mods:
mod-account-achievements
mod-ah-bot
mod-autobalance
mod-solocraft
mod-solo-lfg

**Comment by Shineslippers** [comment]
Confirmed. There is should be 2nd gossip "NO". Atm it also unclickable.
![WoWScrnShot_110221_181903](https://user-images.githubusercontent.com/85256266/139876520-ba082fd6-780b-4c12-bada-f9a56887c6d2.jpg)
