### ISSUE TITLE
"Demon's Blood" Trinket Missing Stats

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#8891]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2028

Reward from really really long chain quest https://classic.wowhead.com/quest=3628/you-are-rakhlikh-demon , tried to equip it, it is not just visual bug that it doesn't show stats but doesn't apply to my defense rating and other. Just trinekt without stats atm.

Tester: Confirmed, the [Demon's Blood](https://tbc.wowhead.com/item=10779/demons-blood) trinket is missing stats on AC.

![WoWScrnShot_110221_213233](https://user-images.githubusercontent.com/81782124/139835150-68d9e895-dd46-499e-bbff-13a4ea078fb7.jpg)

The missing stats are Blizz-like behaviour, as of patch 3.3.3 (23rd March 2010) when some glitch caused the item to lose its stats. However, as AC has the general policy of fixing obvious bugs even if they are Blizz-like where possible, this should be addressed. (See https://github.com/chromiecraft/chromiecraft/issues/2226#issuecomment-956264565 for sources for this policy.)

### Expected Blizzlike Behaviour

As explained above, we are deviating from Blizz-like behaviour here in order to correct the problem.

https://classic.wowhead.com/item=10779/demons-blood
The item gives this buff: https://tbc.wowhead.com/spell=12956/demon-armor

### Source

https://tbc.wowhead.com/item=10779/demons-blood
https://wowpedia.fandom.com/wiki/Demon's_Blood?direction=prev&oldid=2367677 (pre-glitch)
https://wowpedia.fandom.com/wiki/Demon's_Blood?direction=prev&oldid=2454873 (post-glitch)

### Steps to reproduce the problem

.additem 10779

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by IntelligentQuantum** [comment]
@Azcobu 

Patch 3.3.3 (2010-03-23): Undocumented change.
All bonuses from the item have disappeared for unknown reasons.

**Comment by Azcobu** [comment]
@IntelligentQuantum 

That's correct. If you read more of the ticket, I explained why this is still an issue:

>The missing stats are Blizz-like behaviour, as of patch 3.3.3 (23rd March 2010) when some glitch caused the item to lose its stats. However, as AC has the general policy of fixing obvious bugs even if they are Blizz-like where possible, this should be addressed. (See chromiecraft/chromiecraft#2226 (comment) for sources for this policy.)
