### ISSUE TITLE
Witch Doctor Uzer'i missing dialogue text

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8893]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2243

[Witch Doctor Uzer'i](https://wowgaming.altervista.org/aowow/?npc=8115) is an NPC in Feralas, that gives several quests. When you talk to him there is a dialogue option **Tell me more about muisek** <[screenshot](https://pasteboard.co/LgHN5rEwY1yj.png)>.

When you click on it however the text is missing. There's a generic greeting line instead.
[Screenshot](https://pasteboard.co/wyyZH7EJCKR7.png).

Tester:

The issue is comnfirmed. [Witch Doctor Uzer'i](https://wowgaming.altervista.org/aowow/?npc=8115) is missing dialogue text.
![WoWScrnShot_110221_143329](https://user-images.githubusercontent.com/85256266/139838907-6d305fb5-8396-4370-9ffb-7f5dfc9ade0e.jpg)

### Expected Blizzlike Behaviour

He should have this quote:
>Existing in this area are many creatures considered allies of the night elves. The elves have had access to the power within each of these creatures: it is time that the horde be allowed this same satisfaction. I have devised a way that this power can be captured and used for our benefit.
Do not doubt what I tell you, `name`. Help me, and you shall see that I speak truth.

### Source

Wowpedia [Witch Doctor Uzer'i](https://wowpedia.fandom.com/wiki/Witch_Doctor_Uzer%27i?oldid=2357413)

### Steps to reproduce the problem

.go c id 8115
speak with doctor

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
```
DELETE FROM `gossip_menu` WHERE `MenuID` IN (1289);
INSERT INTO `gossip_menu` (`MenuID`,`TextID`) VALUES (1289,1924);
```
