### ISSUE TITLE
Water/underwater incorrect pathing

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8896]
### What client do you play on?

other

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2244

So this npc i ve pulled it from the boat in the quest in strangle near booty bay mall and he wasnt able to attack me as you can see in this video 
https://youtu.be/VZbno0GxtCo

Tester:

The issue is confirmed. In some uncertain circumstances NPCs choosing ground paths.

https://user-images.githubusercontent.com/85256266/139852235-79365d38-709b-4875-a8e7-6cce3559ea40.mp4

https://user-images.githubusercontent.com/85256266/139852262-1b4a8815-1cd0-450d-b978-b35aae8a5e63.mp4

### Expected Blizzlike Behaviour

NPCs should always choose swimming if player in water.

### Source

X

### Steps to reproduce the problem

.go c 2607 - teleport to blood sail pirate on the boat
agro some NPCs and jump to water

### Extra Notes

https://classic.wowhead.com/npc=4505/bloodsail-deckhand

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/2d4e17fd16326b27f100977ac8a542ad56d57934
