### ISSUE TITLE
First miss attack provoke NPC in combat mode

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#8900]
### Current Behaviour

First miss attack provoke NPC in combat mode and start attack player.

https://user-images.githubusercontent.com/21084600/139868575-823e15b8-c4d0-4287-8d8d-715e55f2b129.mp4

### Expected Blizzlike Behaviour

First miss attack do not provoke NPC in combat mode and attack player.

### Steps to reproduce the problem

Try attack NPC for first hit must be miss.

### AC rev. hash/commit

2d38f36555e59e00131c5813da7b300a0a85179a

### Operating system

windows 10

**Comment by Shineslippers** [comment]
Same there. Can we get some sources?

**Comment by Mitradis** [comment]
hm i see two big video and did not notice a single miss, it says something
https://www.youtube.com/watch?v=Yv0cPuseynQ
https://www.youtube.com/watch?v=zQqHxO2ZL-c

**Comment by Mitradis** [comment]
I can't watch these stupid videos on youtube. The only option is to wait for the release LK.

**Comment by Maurowin** [comment]
All version of wow its like that. For me is not a bug. Same in classic and retail.
