### ISSUE TITLE
NPCs what is giving Experience on kill has incorrect color of level

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8904]
### What client do you play on?

other

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

NPCs what is giving Experience on kill has grey color of level.

https://user-images.githubusercontent.com/85256266/139886898-dd555d2d-3a82-483c-b366-6202372dfbc3.mp4

### Expected Blizzlike Behaviour

If NPCs on kill granting Expirience the color of level should be some sort of green

### Source

Wowwiki [Experience point](https://wowwiki-archive.fandom.com/wiki/Experience_point?oldid=2381937#Mob_gray_level)

![Untitled](https://user-images.githubusercontent.com/85256266/139895726-f8f424b5-ede6-47c5-a4f9-84c29d4fbead.png)

### Steps to reproduce the problem

find NPC what should give XP
look to color of level

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
You say 

> find NPC what should give XP
look to color of level

But isn't the issue the other way around? The mob is 45, you're 57, it should be grey, but gives xp? 

Or is the claim right now only "there's a mismatch"?

**Comment by patou01** [comment]
Well I don't know how to fix that. I can't seem to be able to find any code related to this that is actually executed.

**Comment by Shineslippers** [comment]
That's ok. One more clien side issue. but anyway i ahve to report it to know =)

**Comment by UltraNix** [comment]
Completely clientside.
