### ISSUE TITLE
Various "Gordunni" NPCs missing their weapons

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8912]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2245

This is a [list of quests](https://wowgaming.altervista.org/aowow/?search=gordunni#quests) in Feralas, which send you to kill some Ogres. While doing them I noticed something was off with the way the mobs looked.

Turns out half of them have the wrong weapons equipped. The rest seemed ok. Abilities and quotes seem to be ok as well, but I did limited testing on that one.

Tester:

The issue is confirmed. [Gordunni Mage-Lord](https://wowgaming.altervista.org/aowow/?npc=5239), [Gordunni Mauler](https://wowgaming.altervista.org/aowow/?npc=5234), [Gordunni Shaman](https://wowgaming.altervista.org/aowow/?npc=5236), [Gordunni Warlock](https://wowgaming.altervista.org/aowow/?npc=5240) have wrong weapons.

### Expected Blizzlike Behaviour

<details>
<summary>Spoiler</summary>

[Gordunni Mage-Lord](https://classic.wowhead.com/npc=5239/gordunni-mage-lord)
![qweqwe](https://wow.zamimg.com/uploads/screenshots/normal/38185-gordunni-mage-lord.jpg)

[Gordunni Mauler](https://classic.wowhead.com/npc=5234/gordunni-mauler)
![acwfe](https://wow.zamimg.com/uploads/screenshots/normal/76934-gordunni-mauler.jpg)

 [Gordunni Shaman](https://classic.wowhead.com/npc=5236/gordunni-shaman)
![segvec](https://wow.zamimg.com/uploads/screenshots/normal/76937-gordunni-shaman.jpg)

[Gordunni Warlock](https://classic.wowhead.com/npc=5240/gordunni-warlock)
![awcf](https://wow.zamimg.com/uploads/screenshots/normal/76936-gordunni-warlock.jpg)

</details>

### Source

[Longer video](https://youtu.be/kzB3LJLY85s?t=752) showing some of the ogres and their proper weapons.
[Another one at the exact time.](https://youtu.be/76kSPDZ2_vQ?t=1668)

### Steps to reproduce the problem

.tele ruinsofisildien

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
Sniff incoming tonight. TC values are also wrong polluted with 434 values.
