### ISSUE TITLE
ICC Saurfang combat start dialog with Muradin Bronzebeard are broken

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#8921]
### Current Behaviour

ICC Saurfang combat start dialog Muradin Bronzebeard are broken

### Expected Blizzlike Behaviour

ICC Saurfang combat start dialog Muradin Bronzebeard is ok

### Steps to reproduce the problem

Go ICC
Start batle with Saurfang

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/bfe290477ce4c4787555671021a1a280daf00be7

### Operating system

Debian 10

**Comment by Shineslippers** [comment]
I guess he is mixing Horde/Allince text
![WoWScrnShot_110421_185130](https://user-images.githubusercontent.com/85256266/140372612-836006af-d312-4589-b138-b97b072378ca.jpg)

Wowwiki [Saurfang quotes](https://wowwiki-archive.fandom.com/wiki/Deathbringer_Saurfang?oldid=2386527#Quotes)

**Comment by Ravenguard13** [comment]
Another thing is - the ending of the fight is broken too. 

After he dies, the Big Saurfang has to show up and take his son's body. Unfortunately, this script is absent, for both factions.

Not sure if i'm supposed to make a new topic about this or just say it here

**Comment by Ravenguard13** [comment]
@Azcobu  it's "Content 80", not 60 ))))

**Comment by Shineslippers** [comment]
It's auto. Don't understand. I labled it 80.

**Comment by pangolp** [comment]
If I make this query
```sql
UPDATE `creature` SET `id1`=37200 WHERE `guid`=200982;
```
The dialogue in the alliance is perfect.
Although I will surely fail in the horde.

I'm not saying that should be the answer.
But it's funny, how when you make that change, it "fixes itself"
I think the problem is in the `Creature::UpdateEntry`.
But I have already tried several times to find the solution and I have not been able to.

**Comment by pangolp** [comment]
Another change I made was this.

```cpp
uint32 Criatura::GetScriptId() constante
{
     if (CreatureData const* criaturaData = GetCreatureData())
         if (uint32 scriptId = criaturaData->ScriptId)
             devolver scriptId;

     devolver sObjectMgr->GetCreatureTemplate(GetEntry())->ScriptID;
}
```

For this

```cpp
uint32 Criatura::GetScriptId() constante
{
     devolver sObjectMgr->GetCreatureTemplate(GetEntry())->ScriptID;
}
```

In this way, I have managed to ensure that the gossip is read properly.

![WoWScrnShot_050224_141513](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/951b444d-db6f-4c42-822d-35140a698f76)

![WoWScrnShot_050224_141530](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/6522c860-a527-4a2a-80f2-a8954a9aebb7)

**Comment by pangolp** [comment]
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/e142c465-bec4-4516-9416-2b248b523721

![WoWScrnShot_050224_142407](https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/c167d747-13fa-4e8b-a4eb-ba5175bc3db3)

**Comment by pangolp** [comment]
I really don't know what else to try. On top of that I have a core from a few years ago, and this mechanic works well. I'm sure it has something to do with when the 3 ids were added to the creature table. But I have no way to reproduce the problem. I've already given up hope of being able to really track down the problem.
