### ISSUE TITLE
Error at server start up with fresh install.

### ISSUE THREAD

**Issue by Heisen59** [azerothcore/azerothcore-wotlk#8922]
### Current Behaviour

Worldserver crash at start when loading Spell custom attributes

Crash report : https://gist.github.com/Heisen59/3b02c49943b1557e750898fb88d9070f

### Expected Blizzlike Behaviour

Should start.

### Steps to reproduce the problem

1. Clean install
2. Start the server
3. Crash

### AC rev. hash/commit

Can't start the server.

### Operating system

windows 10

### Custom changes or Modules

None

**Comment by Nyeriah** [comment]
Hello,

Thank you for taking the time to report this, but this issue has been reported here: https://github.com/azerothcore/azerothcore-wotlk/issues/8865 and is being looked into.

I'll close this as a duplicate, thanks once again.

For the time being, try to build in Release or RelWithDebugInfo modes.
