### ISSUE TITLE
vmap4extractor & vmap4assembler errors

### ISSUE THREAD

**Issue by zqgmzq** [azerothcore/azerothcore-wotlk#8928]
### Current Behaviour

./vmap4extractor
Extracting <Empty>\Kl_Onyxiaslair.wmo
No such file.
Couldn't open RootWmo!!!

./vmap4assembler Buildings vmaps
Cannot open vmaps/000.vmtree
error converting Abandonedorcbarracks.wmo
exit with errors

### Expected Blizzlike Behaviour

no errors

### Steps to reproduce the problem

./vmap4extractor
./vmap4assembler Buildings vmaps

### Extra Notes

![Снимок1](https://user-images.githubusercontent.com/45689766/140165817-fb0f4f68-cf16-44a2-8890-d7e1ec538ad2.PNG)

![Снимок2](https://user-images.githubusercontent.com/45689766/140165864-523f58b7-0a1b-468f-9015-c648759dcf73.PNG)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/cde621f9ebf0edc012eeed53f0b1e28a0985b909

### Operating system

Debian 10

### Custom changes or Modules

no

**Comment by Kitzunu** [comment]
> ./vmap4extractor
Extracting \Kl_Onyxiaslair.wmo
No such file.
Couldn't open RootWmo!!!

**Comment by Kitzunu** [comment]
> ./vmap4extractor
Extracting \Kl_Onyxiaslair.wmo
No such file.
Couldn't open RootWmo!!!

Is just a warning, don't worry about it.

> ./vmap4assembler Buildings vmaps
Cannot open vmaps/000.vmtree
error converting Abandonedorcbarracks.wmo
exit with errors

Did you run vmap4extractor first, and then vmap4assambler?

**Comment by zqgmzq** [comment]
> Did you run vmap4extractor first, and then vmap4assambler?

yep

**Comment by Kitzunu** [comment]
just ran them without issue.

**Comment by zqgmzq** [comment]
> just ran them without issue.

OS?

**Comment by xlla** [comment]
similar issue here.

<pre>
Extracting World\Wmo\Transports\Transport_Zeppelin\Transport_Zeppelin.wmo
Extracting <Empty>\Kl_Onyxiaslair.wmo
No such file.
Couldn't open RootWmo!!!
Extracting World\Wmo\Transports\Transport_Ship_Ne\Transportship_Ne.wmo
Extracting World\Wmo\Band\Final_Stage.wmo
No such file.
Couldn't open RootWmo!!!

... many other Extracting ...

Done!

Extract V4.00 2012_02. Work complete. No errors.
</pre>

**Comment by Sebi1moi** [comment]
Similar issue here too ... 
`Extracting World\Wmo\Band\Final_Stage.wmo
No such file.
Couldn't open RootWmo!!!
Done!`
