### ISSUE TITLE
LBRS Urok Ogre Magus has range issues

### ISSUE THREAD

**Issue by patou01** [azerothcore/azerothcore-wotlk#8930]
### Current Behaviour

If you are in a "deadzone", he casts the spell but it never fires nor seems to hit.

### Expected Blizzlike Behaviour

The spell should hit, or the mob move closer.

### Steps to reproduce the problem

.go c 40508
.additem 12533
.additem 12534

Start the event, stay far enough from a mage.

### AC rev. hash/commit

cde621f9ebf0edc012eeed53f0b1e28a0985b909

### Operating system

win10 x64

**Comment by Shineslippers** [comment]
Idk. They are moving. Can't reproduce bug.

https://user-images.githubusercontent.com/85256266/140334262-001d6b84-3772-452b-ad7f-f504922b2d98.mp4

**Comment by patou01** [comment]
You're LOS-ing them. Try walking without breaking line of sight. When you're close, they cast the bolt and it fires. Then at some point they cast the spell but no bolt to be seen. And even further out and then they start walking.

**Comment by Shineslippers** [comment]
Done. Confirmed. Also, i don't like their yellow health bars. Maybe they have wrong faction?

https://user-images.githubusercontent.com/85256266/140339590-ebcd3e8d-d713-41da-862f-3157bbad3dff.mp4

.

**Comment by patou01** [comment]
Yeah the health bars are being fixed elsewhere, should be up towards the end of the week-end I hope.
