### ISSUE TITLE
Failed Build

### ISSUE THREAD

**Issue by darkenam** [azerothcore/azerothcore-wotlk#8931]
### Current Behaviour

build failed : error list

/usr/bin/ranlib: libscripts.a: No space left on device
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:9758: src/server/scripts/libscripts.a] Error 1
make[2]: *** Deleting file 'src/server/scripts/libscripts.a'
make[1]: *** [CMakeFiles/Makefile2:1162: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/cde621f9ebf0edc012eeed53f0b1e28a0985b909

### Operating system

ubuntu 64

### Custom changes or Modules

cfgbg

**Comment by patou01** [comment]
Is this a github actions build or what?

I think it's unlikely that the build has an infinite loop that eats the entire disk. Looks like you compile on something that has little to no space?

**Comment by acidmanifesto** [comment]
/usr/bin/ranlib: libscripts.a: No space left on device
make[2]: ***
Ensure your partition or vm has enough space availabke

**Comment by darkenam** [comment]
@acidmanifesto

how to fixed

**Comment by patou01** [comment]
@darkenam you need to make space on the disk that you are using. So either have a bigger disk, increase size of the disk for the VM, or delete unnecessary files that are on the disk.
How much of those 15g are free?

**Comment by darkenam** [comment]
What should I delete?

**Comment by patou01** [comment]
You should never have your disk full anyway as it's bad, you need to find a way to get a few GB free on the disk that you use to compile. I'm not familiar with linux to guess what all of those are.

**Comment by darkenam** [comment]
thank you , resolved.

**Comment by Ragelezz** [comment]
closed
