### ISSUE TITLE
World doors doesn't have reset of lockpick(skill up) timer or this timer is too long

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8936]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2256

Currently the Armory Door's <https://wowgaming.altervista.org/aowow/?object=101851> Pick Lock <https://wowgaming.altervista.org/aowow/?spell=1804> level up is not resetting properly.

Tester:

The issue is confirmed. Regardless of time when door was lockpick rogues can't get skill up. Waited atleast 30 minutes. 

### Expected Blizzlike Behaviour

Doors should have comparable to boxes timers. As will be mention below something around 5m.

### Source

Wowwiki [Lockpicking (leveling)](https://wowwiki-archive.fandom.com/wiki/Lockpicking_(leveling)?oldid=2473900#Pickable_locks)
>Skill gains on doors not inside an instance are on a timer. They cannot be picked repeatedly for skill. A certain amount of time (about 5 min) must elapse before skill gains may be realized again. As of 5 August 2008, doors within instances must also be given time to cool down before getting another skill point, even if you reset the instance

[Youtube](https://youtu.be/XMKCTfAqgOg?t=129). Old video saying you while timer is resetting you can pickpocket 3 NPCs. It's taking definitely less than 30 min.

### Steps to reproduce the problem

.go c 45195 - tele to scarlet guard near doors
.setskill 633 175

### Extra Notes

Idk. Do you need all objects ids? Let me know.  Huge list tbh. Don't wanna do it without reason.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@Shineslippers https://www.aetherflask.com/rogue-lockpicking-guide-for-classic-wow/ It says 20 min.

**Comment by Shineslippers** [comment]
What about different mechanic. Cooldown is 20 minutes but actions in instance can decrease this timer.

Wowwiki [Lockpicking (leveling)](https://wowwiki-archive.fandom.com/wiki/Lockpicking_(leveling)#Pickable_locks)
> As of 16 December 2007, there seems to be a 50/50 chance that picking a junkbox will reset the skill gain timer on either or both Scarlet Monastery doors. Zoning into any of the four instances and pickpocketing at least three mobs also seems to give a 50/50 chance of reseting the SM door timer on both doors.

Wowhead [comment](https://www.wowhead.com/forums/topic/116181#p1351876)
> By Crimor on 2009/08/25 at 3:40 PM (Patch 3.2.0)
Not quite right.
There are actions which you can conduct which will reset the timers on doors. Pickpocketing NPC is one of those actions.
Example: You can level LP on Scarlett Monastery doors leading to Cathedral/Armory, from lvl 175 lockpicking. You open both doors, enter any instance, pickpocket a few NPCs there (taking about a minute) and go back to doors - you WILL gain skill again on both doors.
Pretty similar with BRD locks but there you need to reset the instance in order to make the doors locked again.

**Comment by UltraNix** [comment]
No - it has not. There is not timer at the moment.

**Comment by Shineslippers** [comment]
Well then without sniffs everything will be just assumptions. I didn't found clear info only those comments.

**Comment by UltraNix** [comment]
I will set it to 5 mins.
