### ISSUE TITLE
Door's levers available to use while it's already open

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8937]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

You can use door's levers while it's already open. It will bug out doors and makes always open.

https://user-images.githubusercontent.com/85256266/140230916-12bb0e5c-ada4-4ea1-89e8-ce91e3193e9b.mp4

### Expected Blizzlike Behaviour

Levers should open doors.

### Steps to reproduce the problem

.go o 45428
open door
use torch

### Extra Notes

Idk. Do you need all objects ids? Let me know. Huge list tbh. Don't wanna do it without reason

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
In this particular case, it looks like that torch is using smart script to activate the door... So we can probably find all the other similar cases by making a proper sql query.

Potential fix is to set the door from the torch reset.  But I think it might make it close faster, and then we somewhat loose the "timer" of the door. Though it could just be used as a backup.

````
UPDATE `gameobject_template` SET `AIName` = 'SmartGameObjectAI' WHERE `entry` = 176767;

DELETE FROM `smart_scripts` WHERE (`source_type` = 1 AND `entryorguid` = 176767);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(176767, 1, 0, 1, 70, 0, 100, 0, 2, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 14, 45427, 174626, 0, 0, 0, 0, 0, 0, 'Torch - On Gameobject State Changed - set GO state'),
(176767, 1, 1, 0, 61, 0, 100, 0, 3000, 3000, 0, 0, 0, 202, 0, 0, 0, 0, 0, 0, 14, 45427, 174626, 0, 0, 0, 0, 0, 0, 'Torch - Link - Set GO state closed');
````

**Comment by Nyeriah** [comment]
> In this particular case, it looks like that torch is using smart script to activate the door... So we can probably find all the other similar cases by making a proper sql query.
> 
> Potential fix is to set the door from the torch reset. But I think it might make it close faster, and then we somewhat loose the "timer" of the door. Though it could just be used as a backup.
> 
> ```
> UPDATE `gameobject_template` SET `AIName` = 'SmartGameObjectAI' WHERE `entry` = 176767;
> 
> DELETE FROM `smart_scripts` WHERE (`source_type` = 1 AND `entryorguid` = 176767);
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
> (176767, 1, 0, 1, 70, 0, 100, 0, 2, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 14, 45427, 174626, 0, 0, 0, 0, 0, 0, 'Torch - On Gameobject State Changed - set GO state'),
> (176767, 1, 1, 0, 61, 0, 100, 0, 3000, 3000, 0, 0, 0, 202, 0, 0, 0, 0, 0, 0, 14, 45427, 174626, 0, 0, 0, 0, 0, 0, 'Torch - Link - Set GO state closed');
> ```

If we go for this solution, we could also use a condition to check if the linked gameobject is already open and prevent running SAI if it is so
