### ISSUE TITLE
Battlegrounds, trap of resurrect

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8958]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1633

It doesn't happen that much often, nor happened to many people as there is really low chance that you die same moment when they assault your base in Arathi Basin.
What happened is that I got teleported to the zone that was mine (Gold Mine), when I died Gold mine got assaulted and because of that, mob that ressurects people dissapeared, leaving me without ressurection.
Solution: Wait for my BG friends to assault or defend that part of Arathi Basin or walk to any other friendly base which takes 2 mins or more.
Again happens very rare as it is low chance that in same moment when you die base get's assaulted
On a screenshot you can see me on graveyard after I died, Outplayed assaulted Gold Mine and was not a Horde teritory anymore, my spirit healer dissapeared and I couldn't ressurect.
![WoWScrnShot_090421_222115](https://user-images.githubusercontent.com/80590226/132115734-85be97fc-39a2-4243-9336-98a7163d3c4d.jpg)

Testre:

The issue is confirmed. If you press button "Release spirit" while capture of base will be in ~0.5 seconds or less it will teleport you to captured base's graveyard. You can't ressurect here and have run to your corpse.

https://user-images.githubusercontent.com/85256266/140427866-380b39b9-bdab-46d9-bad9-c8dc413b7154.mp4

https://user-images.githubusercontent.com/85256266/140427847-726ed9fd-6199-4db2-b2e1-c1314cd84700.mp4

### Expected Blizzlike Behaviour

Should be immediately teleported at any other nearest graveyard if die when base is assaulted.
Again teleporting to other graveyard works perfectly if base is assaulted. BUT IF base is assaulted SAME moment when you die, it doesn't work.

Tester:

I believe it could be blizzlike. I'm leaving it as suggestion.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
Tested: ✔
- Alliance assaulting Alterac Valley when horde Releases Spirit in less than 0.5s sends the Horde player to another graveyard.
- Horde assaulting Alterac Valley when Alliance Releases Spirit in less than 0.5s sends the Alliance player to another graveyard.
