### ISSUE TITLE
Mount Hyjal: Archimonde Unkillable (without cheating)

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#896]
**Description**:
Archimonde is casting Hand of Death in phase 2 (after 10% hp), wiping the raid.

**Current behaviour**: Tell us what happens
At the moment Archimonde (id 17968) can not be killed normally. At 10% he casts Protection of Elune (38528) correctly on the raid but also enrages, spam casting Hand of Death (35354) on the raid. The damage from this goes through the protection and wipes the raid before the wisps can kill him.

**Expected behaviour**: Tell us what should happen instead
He should start casting Finger of Death (31984) which looks flashy but doesn't get through the protection. 60 seconds after he enters phase 2 the wisps kill him.

What seems to be happening is that he's enraging at the start of phase 2 (which causes the Hand of Death). Commenting out that "Enraged = true;" makes him killable, though ideally he should be casting Finger of Death instead.

boss_archimonde.cpp - Line 545
```
            if (BelowTenPercent)
            {
                if (!HasProtected)
                {
                    me->GetMotionMaster()->Clear(false);
                    me->GetMotionMaster()->MoveIdle();

                    //all members of raid must get this buff
                    DoCastVictim(SPELL_PROTECTION_OF_ELUNE, true);
                    HasProtected = true;
                    Enraged = true;
                }
```

**Steps to reproduce the problem**:

1. Engage Archimonde (I'm afraid I don't know a way to get him to turn visible without doing all the waves in the rest of the dungeon).
2. Get him to 10% and see Protection of Elune is on.
3. Die to Hand of Death

**Branch(es)**: master

**AC hash/commit**:  825a62b

**Operating system**:  Windows 10

**Modules**:  VAS Autobalance

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Branel** [comment]
@FrancescoBorzi this is fixed right, it can be closed?

**Comment by Kitzunu** [comment]
Will close this as the PR says "Closes".
