### ISSUE TITLE
Bug with dot snapshot and bonus damage aura

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#8962]
### Current Behaviour

Currently, damage over time spells are not doing bonus damage if you refresh a dot _after_ getting a aura that increases your damage.
Examples: Rake and Savage Roar, Shadow Word: Pain and Shadow Form, Seal of Vengeance and Avenging Wrath.

So, if you cast a dot, then get a bonus damage buff and refresh the dot, the damage is the same. 
But if you wait the dot to end, then cast dot with bonus damage buff, the DoT will do increased damage.

It only happens with aura that increases damage, tested with trinket proc (bonus spell power or attack power) and its fine.
Also tested with heal over time and aura that increases heal or spell power, and both works fine.

### Expected Blizzlike Behaviour

The damage of the DoT should increase when you refresh it with a aura that increases damage.

### Steps to reproduce the problem

1. summon dummy (.npc add 32667).
2. cast Shadow Word: Pain (.cast 48125) and see the damage.
3. cast Shadowform (.cast 15473) and refresh Shadow Word: Pain (.cast 48125). The damage is the same.
4. now wait for Shadow Word: Pain to end and cast again (.cast 48125) with Shadowform. The damage is increased.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/bfe290477ce4

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-npc-talent-template
mod-racial-trait-swap

**Comment by Shineslippers** [comment]
Everything is truth.

**Comment by laasker** [comment]
Also i would like to point out that the issue only happens with positive auras that give bonus damage, negative auras, like Curse of the Elements (+13% magic damage taken) works fine, it increases the damage of dots without needing to reapply/refresh.
