### ISSUE TITLE
Alt+Tab could prevent game loading textures

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#8963]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1663

(This is not in windowed mode.) When my character lands from a flight path into Ironforge while I am looking at the other program, I click back into wow from the taskbar and my character has fallen through the map. I have not noticed this at other flight paths.
Also, although most sound will continue in the background, the sound of my character striking the anvil usually does not. The sounds of smelting & of completing a craft, when it is added to my bags, do continue in the background.

Tester:

 The issue is confirmed. I have 100% success for route Wetlands - Ironforge. Can't reproduce it for other routes Like Westfal- Stormwind.
![WoWScrnShot_110521_031533](https://user-images.githubusercontent.com/85256266/140438516-365581e0-7b7f-428c-a7b0-3fe05e7feb09.jpg)

### Expected Blizzlike Behaviour

Should be able to alt-tab while in flight, and not tab back into your character falling thru the map to their death.

Should be able to hear all sounds in the background while alt-tabbed.

### Steps to reproduce the problem

- game should runing in fullscreen
- .go c 9648
- take fly from Wetlands to IF and press alt+tab immediately
- wait 2m
- click on WoW app

### Extra Notes

My guess it's somehow related to textures loading at zone-zone change. Idk how working zone loading. It's just my speculations. 
I can't reproduce it when tried to alt+tab near IF.
@jamadaha have to say about sound. Didn't get it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
To me looks like a client issue

**Comment by UltraNix** [comment]
Yep - it's clientside.

**Comment by Shineslippers** [comment]
Ok. Close it then.
