### ISSUE TITLE
Start quests dont work

### ISSUE THREAD

**Issue by MysterioPRM** [azerothcore/azerothcore-wotlk#8977]
### Current Behaviour

Good time of day. NPCs in almost all starting locations have stopped working. That is, one of the NPCS gives a quest, the next one, like in the screenshot, does not complete the task when accessing it. there are no errors in the server log

Start quest NPC:
![image](https://user-images.githubusercontent.com/79892747/140545215-381a643a-d344-4a95-a405-f5263e23fe0c.png)

End Quest NPC:
![image](https://user-images.githubusercontent.com/79892747/140545312-4e07468e-10bf-4677-a8ef-035b21af1021.png)
the screenshot shows that the NPCs have no reaction, and this happens for every race/ class

In other starting locations it is impossible to take a quest at all
![image](https://user-images.githubusercontent.com/79892747/140546295-e1b1dac6-0cb6-4b52-a99b-10eea26fb4b2.png)

### Expected Blizzlike Behaviour

The quest must be completed at the NPC

### Steps to reproduce the problem

1. Log in to the game
2. Create character
3. take a quest

### Extra Notes

The initial location of the Orcs - all quests work

### AC rev. hash/commit

AzerothCore rev. d80f7d467d47+ 2021-11-05 07:47:08 -0300 (master branch) (Win64, Release, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

  |- mod_npc_promotion
  |- mod_quest_status
  |- SkipDKModule
  |- SoloLfg
  |- Solocraft
  |- mod_startguild
  |- transmog.conf
  |- mod-double-xp-weekend
  |- who-logged
  |- WorldChat

**Comment by patou01** [comment]
Can you provide which commit you were using before this happened?

**Comment by MysterioPRM** [comment]
clean build last source with/without modules

**Comment by MysterioPRM** [comment]
The initial location of the Blood Elves - the quest of the Keeper of the Solanian Well does not work
![image](https://user-images.githubusercontent.com/79892747/140575165-97ebf715-046b-480d-9170-71c9f755444b.png)

The initial location of the Blood Elves - The initial location of the Blood Elves - the quest of the Wizard Itanas does not work
![image](https://user-images.githubusercontent.com/79892747/140575262-6a481a12-1be7-4760-ad30-f33ef3dc6633.png)

**Comment by MysterioPRM** [comment]
The initial location of the Tauren- works

**Comment by patou01** [comment]
Please provide npc and/or quest ids, I don't know all of them and it takes forever to find everything. Nothing seems broken on my server, I suspect it's a module.

**Comment by MysterioPRM** [comment]
I wrote the name of the NPC in the locations. some quests work, some don't. I was building a server with modules, without modules. the result is the same

**Comment by Shineslippers** [comment]
Same here. Cna't reproduce. Everything is working.

**Comment by MysterioPRM** [comment]
The problem is solved. Non-working quests are related to which client is running. Apparently something is wrong with the packages. (on a clean client from blizzard does not work)
