### ISSUE TITLE
[Dungeon/TOC]Boss can not killed

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#8980]
### Current Behaviour

At end of the 1st wave encounter,one of three champion npc boss keep attacking players with 1 hp.and then the Black Knight on Hawk float on air can not be attacked . the dungeon is totally can not play

### Expected Blizzlike Behaviour

champion npc boss won't attack player after be "killed" with 1 hp left. and Black Knight boss should be  attackable.

### Steps to reproduce the problem

1. go to dungeon TOC
2. start combat
3. "Kill" all challenger npc include the 3 champion
4. watch the champion

### AC rev. hash/commit

d80f7d467d47+

### Operating system

Ubuntu 20.04

**Comment by Ravenguard13** [comment]
or more like - the champions show up one by one and at some point one of them attacks the group before the rest championsh are on the arena, which probably breaks the script. when it happens, you can't use any of the attack abilities, the game sais "target can't be attacked". 

Same is with Black Knight. When he appears, he does a full circle around the arena top, but breaks it and attacks the group. His muunt attacks too.  Both can't be attacked at all

Suggest high priority

**Comment by Maurowin** [comment]
@Ravenguard13 Do you confirme this issue?

**Comment by Ravenguard13** [comment]
> @Ravenguard13 Do you confirme this issue?

Yes, but with a quick note:
There are 2 ways to summon champions, First option is when they appear one after another and this is when it's messed up. The second option is to skip the foreplay and all the champions appear at the same moment. In this case you can fight them.

The Black Knight issue - well it cant be avoided

**Comment by betayi** [comment]
this dungeon works well just about one or two weeks ago ,btw

**Comment by Ravenguard13** [comment]
> this dungeon works well just about one or two weeks ago ,btw

well, all the issues I have found after last update - those were working just fine several month ago

**Comment by Mitradis** [comment]
there were big changes and fixes. Apparently the code associated with this problem was originally written incorrectly.

**Comment by SKingOWN** [comment]
I have the same problem in 3b3bef5f95112a8c1d0a61ee38acce9f0caa979e

**Comment by SKingOWN** [comment]
Any ideas what was the change that broke that dungeon?

I have been reviewing all the changes from a couple of months ago but I have not been able to detect which one the problem originated from.
