### ISSUE TITLE
Worldserver Is Down

### ISSUE THREAD

**Issue by VincentVanclef** [azerothcore/azerothcore-wotlk#8983]
### Current Behaviour

Hi there, just recently updated to: https://github.com/azerothcore/azerothcore-wotlk/commit/26486db2e618cf6bc75f2947636996a988191d28

And whenever i login on any character, even a new one, this shows:

![image](https://user-images.githubusercontent.com/541084/140566631-73dc6976-4128-4d55-8a2d-a302377d8081.png)

Ive enabled all logs, but nothing is showing. 

Last thing shown in worldserver console is:

AC> Starting up Auction House Listing thread...

nothing more after that

Anyone have any idea what is causing this?

Thank you

### Expected Blizzlike Behaviour

Should be able to login

### Steps to reproduce the problem

Update to https://github.com/azerothcore/azerothcore-wotlk/commit/26486db2e618cf6bc75f2947636996a988191d28
Login

### AC rev. hash/commit

26486db2e618cf6bc75f2947636996a988191d28

### Operating system

windows 10 x64

**Comment by VincentVanclef** [comment]
UPDATE:

Seriously... you added a config "World.RealmAvailability" - that is without a doubt the stupidest thing ive ever seen, why have a config that disables you from entering the world - what is the point of that? xD Why even have the worldserver running then? If you want to prevent people from logging in, just change the allowed security level?

**Comment by Nyeriah** [comment]
Someone requested such feature. But it should be disabled by default. Did you manage to solve your issue?

**Comment by VincentVanclef** [comment]
Its not disabled by default corewise, here its set to "false":

    // Realm Availability
    m_bool_configs[CONFIG_REALM_LOGIN_ENABLED] = sConfigMgr->GetOption<bool>("World.RealmAvailability", false);

Which meant that if the config isnt in worldserver.conf, you cant enter the game.

AGAIN absolutely worthless feature.

**Comment by Meltie2013** [comment]
@VincentVanclef What is the configuration set to in `worldserver.conf`?

**Comment by Maurowin** [comment]
No, this is not a useless feature. You should measure your words before writing. 

It is used to reserve a character nickname without players being able to log in because for some reason the world should not be accessible like blizzard did when they released the game. Whether it is for the official release or for the classic versions.

This feature was released long before the hash you put in your topic. 
Does anyone else encounter this problem of world server down ?

**Comment by VincentVanclef** [comment]
I just did a git pull to update, so it wasnt in my worldserver.conf - after some debugging i found that new config. Ive set it to 
World.RealmAvailability = 1 and everyone can log in again. 

But this shouldnt be set to auto disabled in world.cpp

**Comment by patou01** [comment]
> What is the configuration set to in `worldserver.conf`?

My understanding is that if you just pull the source, you don't update worldserver.conf... So you get false by default.

**Comment by Kitzunu** [comment]
Agreed. It should be enabled by default.

**Comment by VincentVanclef** [comment]
> No, this is not a useless feature. You should measure your words before writing.
> 
> It is used to reserve a character nickname without players being able to log in because for some reason the world should not be accessible like blizzard did when they released the game. Whether it is for the official release or for the classic versions.
> 
> This feature was released long before the hash you put in your topic. Does anyone else encounter this problem of world server down ?

Wtf? "reserve a name" ???? Have you even seen the table reserved_name in characters table? Also you can still login, create a character, and thus take a name. So what is your point exactly? 

Again, if you wish to prevent people from logging in, just set the allowed security level to > 0 ... >.< Stop implementing useless features that is not needed and can already be solved by existing handlers.

**Comment by Meltie2013** [comment]
> > What is the configuration set to in `worldserver.conf`?
> 
> My understanding is that if you just pull the source, you don't update worldserver.conf... So you get false by default.

That is intended.

**Comment by Kitzunu** [comment]
Thats wrong. We should never by default restrict the access to the worldserver.

**Comment by VincentVanclef** [comment]
> Thats bad. We should never by default restrict the access to the worldserver.

Exactly. Also this config is about as stupid as having a "World.AutoShutdownOnStart = 1" configuration.

**Comment by Maurowin** [comment]
> 
> 
> > No, this is not a useless feature. You should measure your words before writing.
> > It is used to reserve a character nickname without players being able to log in because for some reason the world should not be accessible like blizzard did when they released the game. Whether it is for the official release or for the classic versions.
> > This feature was released long before the hash you put in your topic. Does anyone else encounter this problem of world server down ?
> 
> Wtf? "reserve a name" ???? Have you even seen the table reserved_name in characters table? Also you can still login, create a character, and thus take a name. So what is your point exactly?
> 
> Again, if you wish to prevent people from logging in, just set the allowed security level to > 0 ... >.< Stop implementing useless features that is not needed and can already be solved by existing handlers.

So, explain to me how players can reserve a character name for example without having a website that allows to fill the reserved_name table.

**Comment by Nyeriah** [comment]
There’s no problem with the feature at all. It’s just that all features that eventually lead the server to became differently than normally expected should be disabled by default.

**Comment by Meltie2013** [comment]
> Thats bad. We should never by default restrict the access to the worldserver.

Just change it if it is bother you that much. It was a port from vMangos anyways, did it was a request.

**Comment by VincentVanclef** [comment]
> > > No, this is not a useless feature. You should measure your words before writing.
> > > It is used to reserve a character nickname without players being able to log in because for some reason the world should not be accessible like blizzard did when they released the game. Whether it is for the official release or for the classic versions.
> > > This feature was released long before the hash you put in your topic. Does anyone else encounter this problem of world server down ?
> > 
> > 
> > Wtf? "reserve a name" ???? Have you even seen the table reserved_name in characters table? Also you can still login, create a character, and thus take a name. So what is your point exactly?
> > Again, if you wish to prevent people from logging in, just set the allowed security level to > 0 ... >.< Stop implementing useless features that is not needed and can already be solved by existing handlers.
> 
> So, explain to me how players can reserve a character name for example without having a website that allows to fill the reserved_name table.

With this configuration, they can still log in, and create a character. So how does this config stop that?

**Comment by VincentVanclef** [comment]
Anywho, closing this, do what you want.

**Comment by Maurowin** [comment]
@Meltie2013 The problem is not the feature, Blizzard uses it too. It's just that by default it should allow connection. 

But some users prefer to yell because they don't understand that it's an official and critical feature while they bring nothing to the project.
