### ISSUE TITLE
.editorconfig tutorial

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#899]
We need a small .editorconfig tutorial so people use it to its full extent

I just open the issue so to keep it in mind for later or if someone wants to do it

**Comment by AyaseCore** [comment]
this? https://editorconfig.org/

**Comment by BarbzYHOOL** [comment]
yes

**Comment by Helias** [comment]
I think the wiki is the right repo for this kind of issue https://github.com/azerothcore/wiki/issues/264
