### ISSUE TITLE
[LBRS] Many patrols are missing waypoints

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#8998]
### Current Behaviour

Several of the patrols are missing their waypoints, trivilizing parts of the dungeons where you have to watch out for them.

### Expected Blizzlike Behaviour

They should have waypoints

### Source

Testing / Checking classic videos

### Steps to reproduce the problem

1. Go to LBRS
2. See many patrols not walking

### AC rev. hash/commit

faef417

### Operating system

Win 10

**Comment by Yehonal** [comment]
Why is it closed? can't we collect more info on what waypoints are missing and open a PR for it?

**Comment by Hacki95** [comment]
Because it was commented by the devs that its useless without the missing patrols. And as I just got this report and don't know which ones are specifically supposed to be bugged I closed it again for someone else to take a look at.
