### ISSUE TITLE
make warning

### ISSUE THREAD

**Issue by cshaaa** [azerothcore/azerothcore-wotlk#90]
when make，i got this，how to solve it please?or just let it be?
“
......
[  9%] Built target sharedPCH.cpp_dephelp
Built target collisionPCH.cpp_dephelp
--
    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"
[  9%] Built target revision.h
......
”

**Branch(es)**:  master

**AC hash/commit**:  e2daeebd989e7b64d97118a9b0f0b15d20fe3cc5

**Modules**:  no

**Operating system**:  debian 8

**Comment by ShinDarth** [comment]
did you clone the repository using git?

**Comment by cshaaa** [comment]
yes,I use git clone, not download the zip.

**Comment by cshaaa** [comment]
when I cmake config，it also show

--
    Could not find a proper repository signature (hash) - you may need to pull tags with git fetch -t
    Continuing anyway - note that the versionstring will be set to "unknown 1970-01-01 00:00:00 (Archived)"

* AzerothCore revision   : unknown 1970-01-01 00:00:00 +0000 (Archived branch)
* AzerothCore buildtype  : Release

**Comment by ShinDarth** [comment]
did you try `git fetch -t` ?

**Comment by DevRival** [comment]
Chek plz https://github.com/azerothcore/azerothcore-wotlk/pull/91

**Comment by cshaaa** [comment]
it's ok. thankyou!!

**Comment by DevRival** [comment]
@cshaaa My helped pull?

**Comment by cshaaa** [comment]
another question.plz


TC>Can't set worldserver process priority class, error: Permission denied
Starting up Auction House Listing thread...
Max allowed socket connections 65536
AzerothCore rev. 146f1476769d+ 2016-08-14 20:23:39 +0200 (master branch) (Unix, R
ease) (worldserver-daemon) ready...

**Comment by cshaaa** [comment]
@DevRival, your commit solve my cmake and make warning.

**Comment by ShinDarth** [comment]
@cshaaa open a separate issue for that, please
