### ISSUE TITLE
The Eye: High Astromancer Solarian runs into the sky

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#900]
**Description**:
If the spell Wrath of the Astromancer (42783) sends High Astromancer Solarian's (18805) current target into the air she will run upwards towards the target and won't come down until the next time she teleports with her adds.

**Current behaviour**: Tell us what happens
The High Astromancer periodically casts Wrath of the Astromancer on a random target. This spell after 6 seconds does damage to everyone near the target and bounces them into the air. This spell is working perfectly.

However if the Astromancers current target gets shot into the air High Astromancer Solarian runs up into the sky after them and doesn't come down again until the next time she teleports.

**Expected behaviour**: Tell us what should happen instead
Solarian should stay on the ground. I tried looking to see if there was a flag that should be set that only lets her move on the ground but couldn't find anything. It's also funny that she'll run upwards but never runs down again.

**Steps to reproduce the problem**:

1. Got to the eye .tele theeye
2. Go to High Astromancer Solarian .go creature id 42783
3. Engage and wait for the tank to get the Wrath of the Astromancer debuff.

**Branch(es)**: Master

**AC hash/commit**: 825a62b

**Operating system**:  Windows 10

**Modules**:  VAS Autobalance

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Kitzunu** [comment]
Can't reproduce on https://github.com/azerothcore/azerothcore-wotlk/commit/3bc7880d0a3df3af6bdf34a0a9da0b46e3b51548
