### ISSUE TITLE
Drakkisath Room Patrol - 

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9000]
### Current Behaviour

Currently a pack of mobs sits entirely still instead of moving in a formation.

![image](https://user-images.githubusercontent.com/1082884/140612546-12f19e09-6ece-4de0-a262-2cec3f557d85.png)

### Expected Blizzlike Behaviour

The following mobs should be linked together and patrol in a formation:

DB GUID 137859 (This mob should be in the center of the formation)
DB GUID 137954
DB GUID 137865
DB GUID 137958
DB GUID 137952

### Source

https://youtu.be/BlFFaLzqYr4?t=7928

### Steps to reproduce the problem

Teleport to 15, -269, 111 position and view mobs.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
Add hash/commit
