### ISSUE TITLE
General Drakkisath - MOB ID - 10363

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9003]
### Current Behaviour

Incorrectly level 62 and not "Boss" level - 
![image](https://user-images.githubusercontent.com/1082884/140612354-1080f0e7-7739-4156-a083-ac4fb0d939b1.png)

When boss resets after a wipe, Chromatic Elite Guards do not properly respawn.

Drakkisath currently spams his Conflagrate ability. permanently CCing your tank. 

### Expected Blizzlike Behaviour

Drakkisath should be a Boss level mob.

Chromatic Elite Guards should respawn if the encounter resets.

There should be a reasonable cast order gap between spells - maybe 15 second cd? Need to find logs for this.

### Steps to reproduce the problem

Engage combat on Drakkisath

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
Add hash/commit

**Comment by Nyeriah** [comment]
Some information about conflagration:

The first cast happens after 15 seconds, and then it's repeated every 18 seconds.
It currently targets a random player.

**Comment by patou01** [comment]
Can I mention an additional issue with the adds here @Nyeriah ? The adds are linked to each other but slow to aggro drakkisath.

https://drive.google.com/file/d/1N3v6NXwSdFhDjHwajvzXX_W3sUQnBjuW/view?usp=sharing

**Comment by Nyeriah** [comment]
> Can I mention an additional issue with the adds here @Nyeriah ? The adds are linked to each other but slow to aggro drakkisath.
> 
> https://drive.google.com/file/d/1N3v6NXwSdFhDjHwajvzXX_W3sUQnBjuW/view?usp=sharing

I will rework that with creature_formations and use minion data so they respawn on wipes, but that part might be interesting for you to research since you were looking into that a while ago - the call happens on EnterCombat(), so it seems EnterCombat() is not called on aggro right away.

**Comment by Nyeriah** [comment]
Scrap that, I found this while looking:

![Skärmbild 2021-11-06 201620](https://user-images.githubusercontent.com/47818697/140626604-8a7a0e8e-f99c-48f1-8274-3dc6ed7e5d9e.jpg)

His script used the same creature ID when trying to search for him & the guards...

**Comment by T1ti** [comment]
His level might have changed in WOTLK as wrath reworked dungeons to be easier for the dungeon finder, can't use wow classic stuff for this

**Comment by T1ti** [comment]
> > Can I mention an additional issue with the adds here @Nyeriah ? The adds are linked to each other but slow to aggro drakkisath.
> > https://drive.google.com/file/d/1N3v6NXwSdFhDjHwajvzXX_W3sUQnBjuW/view?usp=sharing
> 
> I will rework that with creature_formations and use minion data so they respawn on wipes, but that part might be interesting for you to research since you were looking into that a while ago - the call happens on EnterCombat(), so it seems EnterCombat() is not called on aggro right away.

there has recently been implemented a creature_formation flag to respawn adds on wipes if leader is alive btw

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/140630790-775c6d2d-6fe3-4a85-834d-7be01a55a70f.png)
Found it

**Comment by Nyeriah** [comment]
> > > Can I mention an additional issue with the adds here @Nyeriah ? The adds are linked to each other but slow to aggro drakkisath.
> > > https://drive.google.com/file/d/1N3v6NXwSdFhDjHwajvzXX_W3sUQnBjuW/view?usp=sharing
> > 
> > 
> > I will rework that with creature_formations and use minion data so they respawn on wipes, but that part might be interesting for you to research since you were looking into that a while ago - the call happens on EnterCombat(), so it seems EnterCombat() is not called on aggro right away.
> 
> there has recently been implemented a creature_formation flag to respawn adds on wipes if leader is alive btw

Thanks. I wasn't aware of this, the wiki has no mention of it.

**Comment by Nyeriah** [comment]
> Some information about conflagration:
> 
> The first cast happens after 15 seconds, and then it's repeated every 18 seconds. It currently targets a random player.

@Kurthos I need feedback on this, is it correct?

**Comment by Shineslippers** [comment]
https://youtu.be/uovM9ebuys0?t=2543
10s

**Comment by T1ti** [comment]
Almost all timers are randomized on blizzlike, its usualy something like 10-15sec initial, 20-25sec repeat (example)

**Comment by T1ti** [comment]
Also it's clearly 12/13sec in your video, not 10

**Comment by Plasmashield** [comment]
Also:
-Conflagration should drop aggro
-Boss should be taunt immune

**Comment by Nyeriah** [comment]
Could use some source on the taunt immunity. I was under the impression that was a vanilla thing.

**Comment by Plasmashield** [comment]
> 
> 
> Could use some source on the taunt immunity. I was under the impression that was a vanilla thing.

yeah, maybe they removed it when they changed level from boss-level to 62

**Comment by unspecifiedperson2916** [comment]
https://youtu.be/5FXIMI7uVnc?t=2852 its tauntable

source wow classic

**Comment by Plasmashield** [comment]
Yeah, i was wrong :c
