### ISSUE TITLE
Damage Breaks Crowd Control

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9004]
### Current Behaviour

Currently, damage seems to break crowd controls early regardless of their type.

Current spells that end early based on damage: 
https://classic.wowhead.com/spell=16790/knockdown

### Expected Blizzlike Behaviour

Stuns should never end early due to incoming damage, this seems to be a feature of some crow control like roots, fears, but has carried over to other spells.

### Steps to reproduce the problem

Find a mob with a crowd control and get beat on for a while.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Kurthos** [comment]
As I find more spells that function this way incorrectly, I'll add them.

**Comment by Shineslippers** [comment]
Can't confirm this spell. Am i doing something wrong?

https://user-images.githubusercontent.com/85256266/142726118-a6b4c453-8922-4c75-a6c4-3f15e59a88f4.mp4
