### ISSUE TITLE
Alterac Valley trinkets available without any requirements

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9010]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2272

When you finish the quest (https://wowgaming.altervista.org/aowow?quest=7162) to get the Stormpike Insignia rank 1 (https://wowgaming.altervista.org/aowow?item=17691) you can immediately complete the next quests to get the rank 2 (https://wowgaming.altervista.org/aowow?item=17900), rank 3 (https://wowgaming.altervista.org/aowow?item=17901), rank 4 (https://wowgaming.altervista.org/aowow?item=17902), rank 5 (https://wowgaming.altervista.org/aowow?item=17903) and rank 6 insignias (https://wowgaming.altervista.org/aowow?item=17904).
![imagen_2021-11-06_112649](https://user-images.githubusercontent.com/74146346/140616719-a1714754-81f6-495a-8f64-1c3cbe3cede8.png)

Tester:

The issue is confirmed.
Allince, [Stormpike Guard](https://wowgaming.altervista.org/aowow/?faction=730):
1. [Rise and Be Recognized](https://wowgaming.altervista.org/aowow/?quest=7168), [Honored Amongst the Guard](https://wowgaming.altervista.org/aowow/?quest=7169), [Earned Reverence](https://wowgaming.altervista.org/aowow/?quest=7170), [Legendary Heroes](https://wowgaming.altervista.org/aowow/?quest=7171), [The Eye of Command](https://wowgaming.altervista.org/aowow/?quest=7172) doesn't requaire reputation to complete.
2. Earned Reverence, Legendary Heroes, The Eye of Command for some reason repetable.

Horde, [Frostwolf Clan](https://wowgaming.altervista.org/aowow/?faction=729):
1. [Rise and Be Recognized](https://wowgaming.altervista.org/aowow/?quest=7163), [Honored Amongst the Clan](https://wowgaming.altervista.org/aowow/?quest=7164), [Earned Reverence](https://wowgaming.altervista.org/aowow/?quest=7165), [Legendary Heroes](https://wowgaming.altervista.org/aowow/?quest=7166), [The Eye of Command](https://wowgaming.altervista.org/aowow/?quest=7167) doesn't requaire reputation to complete.
2. Honored Amongst the Clan, Legendary Heroes, The Eye of Command for some reason repetable.
3. Honored Amongst the Clan, Earned Reverence, available without pre-quest.

https://user-images.githubusercontent.com/85256266/140619282-fcd3d01a-017e-4a39-8c6a-47b986fab9da.mp4

### Expected Blizzlike Behaviour

You should get the quest and the opportunity to upgrade your trinket once you reach a reputation bracket.
- Friendly - Insignia Rank 2
- Honored - Insignia Rank 3
- Revered - Insignia Rank 4
- Exalted - Insignia Rank 5
- Exalted 999/1000 - Insignia Rank 6

### Source

Wowhead [Proving Grounds](https://www.wowhead.com/quest=7161/proving-grounds#comments:id=86610)
> By 53461 on 2007/05/21 (Patch 2.0.12) | By 53461 on 2007/05/21 (Patch 2.0.12)
This trinket is upgraded as you gain reputation with the Frostwolf Clan.
Neutral: Rank 1 (http://www.wowhead.com/?item=17690)
Friendly: Rank 2 (http://www.wowhead.com/?item=17905)
Honored: Rank 3 (http://www.wowhead.com/?item=17906)
Revered: Rank 4 (http://www.wowhead.com/?item=17907)
Exalted: Rank 5 (http://www.wowhead.com/?item=17908)

### Steps to reproduce the problem

.go c 16989 - allince
.q a 7162
.q c 7162
speak to npc and complete quests

.go c 16575 - horde
.q a 7161
.q c 7161
speak to npc and complete quests

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
I'm feeling like it's repeat to https://github.com/azerothcore/azerothcore-wotlk/issues/8395, but i added horde side issues.

**Comment by patou01** [comment]
Just leave it open, it's linked to the other one anyway so whoever fixes any of them just copy/pastes the fix for these too.
