### ISSUE TITLE
Characters : Unknown column 'c.order' in 'order clause'

### ISSUE THREAD

**Issue by lostsnow** [azerothcore/azerothcore-wotlk#9022]
### Current Behaviour

```
In mysql_stmt_prepare() id: 17, sql: "SELECT c.guid, c.name, c.race, c.class, c.gender, c.skin, c.face, c.hairStyle, c.hairColor, c.facialStyle, c.level, c.zone, c.map, c.position_x, c.position_y, c.position_z, gm.guildid, c.playerFlags, c.at_login, cp.entry, cp.modelid, cp.level, c.equipmentCache, cb.guid, c.extra_flags FROM characters AS c LEFT JOIN character_pet AS cp ON c.guid = cp.owner AND cp.slot = ? LEFT JOIN guild_member AS gm ON c.guid = gm.guid LEFT JOIN character_banned AS cb ON c.guid = cb.guid AND cb.active = 1 WHERE c.account = ? AND c.$eleteInfos_Name IS NULL ORDER BY c.order, c.guid"                                            
Unknown column 'c.order' in 'order clause'
```

After upgrade to ebe255d6c0aab6ebdb370aa3ad02ef4d7728b412, some field missing

### Expected Blizzlike Behaviour

This commit https://github.com/azerothcore/azerothcore-wotlk/commit/43ebc5f24a6073803332ae459933ff18dac9de9c only change the base sql, no updates

### Steps to reproduce the problem

upgrade from old version, then restart

### AC rev. hash/commit

ebe255d6c0aab6ebdb370aa3ad02ef4d7728b412

### Operating system

Ubuntu 20.04

**Comment by lostsnow** [comment]
```
In mysql_stmt_prepare() id: 34, sql: "SELECT guid, account, name, race, class, gender, level,
xp, money, skin, face, hairStyle, hairColor, facialStyle, bankSlots, restState, playerFlags,
position_x, position_y, position_z, map, orientation, taximask, cinematic, totaltime, leveltime,
rest_bonus, logout_time, is_logout_resting, resettalents_cost, resettalents_time, trans_x,
trans_y, trans_z, trans_o, transguid, extra_flags, stable_slots, at_login, zone, online, 
death_expire_time, taxi_path, instance_mode_mask, arenaPoints, totalHonorPoints, todayHonorPo$nts,
yesterdayHonorPoints, totalKills, todayKills, yesterdayKills, chosenTitle, knownCurrencies, 
watchedFaction, drunk, health, power1, power2, power3, power4, power5, power6, power7, instance_id,
 talentGroupsCount, activeTalentGroup, exploredZones, equipmentCache, ammoId, knownTitles,
  actionBars, grantableLevels, innTriggerId FROM characters WHERE guid = ?"            
Unknown column 'innTriggerId' in 'field list'
```

```
In mysql_stmt_prepare() id: 54, sql: "SELECT spell, category, item, time, needSend FROM character_spell_cooldown WHERE guid = ?"                                                          
Unknown column 'category' in 'field list'  
```

```
In mysql_stmt_prepare() id: 75, sql: "INSERT INTO mail(id, messageType, stationery, mailTemplateId,
sender, receiver, subject, body, has_items, expire_time, deliver_time, money, cod, checked,
auctionId) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"                       
Unknown column 'auctionId' in 'field list'
```

```
In mysql_stmt_prepare() id: 217, sql: "INSERT INTO characters (guid, account, name, race, class, 
gender, level, xp, money, skin, face, hairStyle, hairColor, facialStyle, bankSlots, restState, 
playerFlags, map, instance_id, instance_mode_mask, position_x, position_y, position_z, 
orientation, trans_x, trans_y, trans_z, trans_o, transguid, taximask, cinematic, totaltime, 
leveltime, rest_bonus, logout_time, is_logout_resting, resettalents_cost, resettalents_time, 
extra_flags, stable_slots, at_login, zone, death_expire_time, taxi_path, arenaPoints, totalHonorPoints, 
todayHonorPoints, yesterdayHonorPoints, totalKills, todayKills, yesterdayKills, chosenTitle, 
knownCurrencies, watchedFaction, drunk, health, power1, power2, power3, power4, power5, 
power6, power7, latency, talentGroupsCount, activeTalentGroup, exploredZones, equipmentCache, 
ammoId, knownTitles, actionBars, grantableLevels, innTriggerId) VALUES (?,?,?,?,?,?,?,?,
?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"                                                      
Unknown column 'innTriggerId' in 'field list'
``

```
In mysql_stmt_prepare() id: 218, sql: "UPDATE characters SET name=?,race=?,class=?,gender=?,
level=?,xp=?,money=?,skin=?,face=?,hairStyle=?,hairColor=?,facialStyle=?,bankSlots=?,restState=?,
playerFlags=?,map=?,instance_id=?,instance_mode_mask=?,position_x=?,position_y=?,position_z=?,
orientation=?,trans_x=?,trans_y=?,trans_z=?,trans_o=?,transguid=?,taximask=?,cinematic=?,
totaltime=?,leveltime=?,rest_bonus=?,logout_time=?,is_logout_resting=?,resettalents_cost=?,
resettalents_time=?,extra_flags=?,stable_slots=?,at_login=?,zone=?,death_expire_time=?,taxi_path=?,
arenaPoints=?,totalHonorPoints=?,todayHonorPoints=?,yesterdayHonorPoints=?,totalKills=?,
todayKills=?,yesterdayKills=?,chosenTitle=?,knownCurrencies=?,watchedFaction=?,drunk=?,health=?,
power1=?,power2=?,power3=?,power4=?,power5=?,power6=?,power7=?,latency=?,talentGroupsCount=?,
activeTalentGroup=?,exploredZones=?,equipmentCache=?,ammoId=?,knownTitles=?,actionBars=?,
grantableLevels=?,innTriggerId=?,online=? WHERE guid=?"
Unknown column 'innTriggerId' in 'field list'
```

```
In mysql_stmt_prepare() id: 291, sql: "SELECT id, messageType, sender, receiver, subject, body, 
expire_time, deliver_time, money, cod, checked, stationery, mailTemplateId, auctionId FROM
mail WHERE receiver = ? AND deliver_time <= ? ORDER BY id DESC"
Unknown column 'auctionId' in 'field list'
```

**Comment by Nyeriah** [comment]
What install method are you using? Classic?

We had a database squash recently (https://github.com/azerothcore/azerothcore-wotlk/commit/43ebc5f24a6073803332ae459933ff18dac9de9c). If you had an older version of the core and skipped straight to the latest commit, several files were moved to the archive folder before they had the chance to be executed by the autoupdater.

The procedure here must be followed (bottom of the page): https://www.azerothcore.org/wiki/database-squash

feat(DB): release ACDB 4.0.0 (#8494) …

***ATTENTION***
- To avoid mistakes need to update the core to 9e39492 to add support correct archive dir and after can merge to actual commit

**Comment by lostsnow** [comment]
> 
> 
> What install method are you using? Classic?
> 
> We had a database squash recently ([43ebc5f](https://github.com/azerothcore/azerothcore-wotlk/commit/43ebc5f24a6073803332ae459933ff18dac9de9c)). If you had an older version of the core and skipped straight to the latest commit, several files were moved to the archive folder before they had the chance to be executed by the autoupdater.
> 
> The procedure here must be followed (bottom of the page): https://www.azerothcore.org/wiki/database-squash
> 
> feat(DB): release ACDB 4.0.0 (#8494) …
> 
> _**ATTENTION**_
> 
>     * To avoid mistakes need to update the core to [9e39492](https://github.com/azerothcore/azerothcore-wotlk/commit/9e3949232cc0ad1703eb4b8bba66dd54b4246ceb) to add support correct archive dir and after can merge to actual commit

follow steps from https://www.azerothcore.org/wiki/database-squash, there are still errors

```
In mysql_stmt_prepare() id: 5, sql: "SELECT entry, pointid, position_x, position_y, position_z, orientation, delay FROM waypoints ORDER BY entry, pointid"
Unknown column 'orientation' in 'field list'
```

**Comment by lostsnow** [comment]
Resetting the entire acore_world database solves this problem
