### ISSUE TITLE
LBRS Urok Doomhowl encounter issues

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9023]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

[Urok Doomhowl](https://wowgaming.altervista.org/aowow/?npc=10584), [Urok's Tribute Pile](https://wowgaming.altervista.org/aowow/?object=175621), [Roughshod Pike](https://wowgaming.altervista.org/aowow/?item=12533), [Omokk's Head](https://wowgaming.altervista.org/aowow/?item=12534)

1. The mobs don't attack the Pike with Head
2. The boss is despawning after appear
3. Urok's Tribute Pile with Pike and Head doesn't disapear

### Expected Blizzlike Behaviour

1. The mobs should attack the pike if there is no players around
2. The boss should not despawning after summon
3. Urok's Tribute Pile with Pike and Head should disapear after Urok appear

### Source

Wowhead [Urok Doomhowl](https://www.wowhead.com/npc=10584/urok-doomhowl#comments):
> By Xenomech on 2008/09/10 (Patch 3.0.1)
If you wipe after planting the head on the pike, you don't get a second chance. You'll have to get the head and pike and try all over again.

> By 146568 on 2008/10/26 (Patch 3.0.2)
If you wipe while fighting Urok himself, he'll stay there. So you can wipe safely after the waves of ogres, killing urok later.

> By TwoGlassEyes on 2008/11/01 (Patch 3.0.2)
Also important to note, if you let the spawns take down the pike, they stop spawning and Urok will NOT spawn.

https://youtu.be/2RqoKtMHavk?t=2692
https://youtu.be/L8a-9CYQk1g?t=4165

### Steps to reproduce the problem

.go game 99791
.additem 12533
.additem 12534

### Extra Notes

Related to https://github.com/azerothcore/azerothcore-wotlk/issues/8712 https://github.com/azerothcore/azerothcore-wotlk/issues/7364

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
While riding my bike I had one more clarification needed on behaviour, to be sure everybody's on the same page. What should happen if the group wipes but Urok is spawned and some adds are still spawned?

Or should he only spawn after the last add dies? I'm pretty sure in the videos he spawns before all mobs are dead.

**Comment by Shineslippers** [comment]
There is question about should adds despawn or not. I don't think we can find Wrath videos on it. Classic Orok despawning and ads too. Since Wrath urok should not despawn it leading to ads not despawn too after Urok's Tribute Pile disapear. This is just my assumption.

**Comment by UltraNix** [comment]
What is the status of this? What problems remain?

**Comment by Shineslippers** [comment]
There is need dev to solve this @patou01 said he can't solve it.

**Comment by UltraNix** [comment]
`This` - means?

**Comment by Shineslippers** [comment]
This issue/report:
1. The mobs should attack the pike if there is no players around
2. The boss should not despawning after summon
3. Urok's Tribute Pile with Pike and Head should disapear after Urok appear

**Comment by UltraNix** [comment]
Okay

**Comment by patou01** [comment]
The part that I don't know how to do is `mobs should attack the pike`. If we have an example of an event where we do it, I can probably try to copy that. 

The rest should be decently simple logic once the edge case of "the group wipes after Urok has spawned but there's still adds". Because that could lead to a bizarre scene in game. The vector containing all the needed mobs is already present `UrokMobs`

**Comment by UltraNix** [comment]
`The boss should not despawning after appear`
For me it works okay. Boss did not despawn on wipe.

**Comment by patou01** [comment]
@Ultranix, apparently I forgot to make him set the event to failed when he despawns, leading to it not being possible to restart the event.

**Comment by UltraNix** [comment]
`The mobs don't attack the Pike with Head` I need more info about that part.
I see in the video that mobs start attacking that pile, but this is just a gameobject - it cannot be killed. I don't what is this

**Comment by patou01** [comment]
If you can make them attack the pile and count the swings, then we can set a limit on the number of swings on the pike.

Else, maybe we can make them attack an invisible dummy? But that would probably be visible in the target of target.

**Comment by UltraNix** [comment]
I don't think so there is some dummy target.

**Comment by patou01** [comment]
Maybe there's some other event like this where we can find inspiration, but I can't think of any.

**Comment by Shineslippers** [comment]
To be clear. I'm already not sure about possibility or resummon like saying https://github.com/azerothcore/azerothcore-wotlk/issues/8712. There is no proofs to it. Found this comment also:
>223389 on 2009/03/26 (Patch 3.0.9)
The first wave, 3 ogres, one attacked the pike, I got a server message "Urok Enforcer attacks the pike!". I didn't know how this quest played out so I just killed all the ogres. **_It seems the pike is gone, there remains a circle of rocks._** What am I suposed to do? Protect the pike? It seemed like they killed the pike very fast. Also, whe I initiated the event, there were several blue glowing spots on the floor, any idea what that was for? They went away when the event was over. But no summon :( Any help?

About the object issue. Violet Hold event. NPCs casting something to object.

**Comment by UltraNix** [comment]
Casting is possible, ut gameobject is not a living object, so cannot be killed. I think this might be just an animation of hitting that pile.

**Comment by patou01** [comment]
Yes, so we need to count the time that they're within that gameobject "hitting" it and not having another target. That should do the trick, then it's figuring out how long is allowed, and I guess they also shouldn't aggro anyone in range (ie they need to be attacked to engage combat)

**Comment by UltraNix** [comment]
Yes. On spawn should move towards to that pike and try to attack it. And your task is to aggro and protect..
