### ISSUE TITLE
[UBRS] Rend Door

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9026]
### Current Behaviour

Door currently open regardless of status of Rend Encounter.
![image](https://user-images.githubusercontent.com/1082884/140649880-1d72c306-06c4-45d9-9204-fd6d1ff4800a.png)

### Expected Blizzlike Behaviour

Door should remain shut until the Rend encounter has been defeated by the players.

### Source

can produce if required.

### Steps to reproduce the problem

Goto
![image](https://user-images.githubusercontent.com/1082884/140649945-c838d382-6ad6-433c-bed0-e55ed0157e54.png)

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
Also after General Drakkisath death doors in his room stil closed 
![image](https://user-images.githubusercontent.com/85256266/140660312-3d18ba2c-1a90-4879-a570-83d54886e458.png)
