### ISSUE TITLE
Crowd Control DR in PVE

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9028]
### Current Behaviour

Currently, players experience crowd control in some encounters that appears to be subject to diminishing returns as if the spell were applied from a player.

Spells identified so far:
https://classic.wowhead.com/spell=18798/freeze

### Expected Blizzlike Behaviour

Stuns and CC from NPC's should never have reduced durations after consecutive applications.

### Steps to reproduce the problem

Get in combat with a mob that has a potential spell such as a stun which could be on the diminishing return.

Have the mob apply the debuff multiple times to your character.

Notice the spell duration reduce in consecutive applications.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Kurthos** [comment]
Will add more spells if noticed.

**Comment by Shineslippers** [comment]
Can confirm. [Freeze](https://classic.wowhead.com/spell=18798/freeze) spell doesn't have DR. Should share it with stuns. 
> [By Norrinir on 2009/03/21 (Patch 3.0.9) ](https://www.wowhead.com/item=942/freezing-band#comments:id=650555)
The proc is indeed regular stun, comparable to Deep Freeze. The target cannot control their character (just like any other stun) and is considered frozen for entire duration. However, although it is indeed proc effect, this stun shares DR category of normal, player-controlled stuns.
Note: Normally, proc based stuns (such as Impact pre 3.1 patch) share their own DR category.

https://user-images.githubusercontent.com/85256266/142727082-071ffe2e-73a4-4498-886c-0007403ce924.mp4

**Comment by UltraNix** [comment]
@Shineslippers ?? @Kurthos says that stuns and freeze from NPCS spells are applying DR(and should not). And then you confirm the bug, that this spell has not applied DR???

**Comment by Shineslippers** [comment]
@UltraNix I'm sorry. Idk what about i thought when created this comment. I will open new report for Freezing Band.

Talking about subject of issue. https://github.com/chromiecraft/chromiecraft/issues/1266

### Current Behaviour

In Maraudon, there are Packs of 3-4 [Subterranean Diemetradons ](https://wowgaming.altervista.org/aowow/?npc=13323) that cast an [AoE silence.](https://wowgaming.altervista.org/aowow/?spell=8281). Those silence affected by DR.

### Expected Blizzlike Behaviour

https://youtu.be/5cqjAlVAAUw?t=6086
https://youtu.be/DV8gbTxmYpo?t=6045

**Comment by UltraNix** [comment]
SO what about that DR? It should not be there is spells are caste by mobs? DR is only for PvP?
