### ISSUE TITLE
[UBRS] Goraluk Anvilcrack

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9029]
### Current Behaviour

Currently, Anvilcrack (NPC ID - 10899) is marked as a Rare Mob, he doesnt always appear to be spawning.

### Expected Blizzlike Behaviour

Goraluk Anvilcrack is not a rare mob and should always be available.

### Source

Can produce if required.

### Steps to reproduce the problem

![Uploading image.png…]()

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
I guess same as https://github.com/azerothcore/azerothcore-wotlk/issues/7643. Wowhead [comments](https://www.wowhead.com/npc=10899/goraluk-anvilcrack#comments) seems like agree

**Comment by Winfidonarleyan** [comment]
@Kurthos please re-uploading image
