### ISSUE TITLE
[BWL] Grethok (Razorgore encounter)

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9030]
### Current Behaviour

Grethok mind control is 3 second cast time
Grethok Mind Control is interruptable
Grethok only channels arcane missile for 1 tick
Grethok is vulnerable to all crowd control (tested stun, blind, polymorph, fear)

### Expected Blizzlike Behaviour

Grethok mind control should be 2 second cast, but is 3 second
Grethok Mind Control should not be interruptable
Grethok only channels arcane missile for 1 tick
Grethok should be immune to all crowd control (tested stun, blind, polymorph, fear)

### Source

Can produce if required.

### Steps to reproduce the problem

Engage Grethok, watch his behavior.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Eronox** [comment]
i can't reproduce this part of the issue 

> Grethok mind control is 3 second cast time


See video below, an example of myself casting the spell to see its exact timer. _(Yes, i've also waited on Grethok to cast it on me to see the timing)_

https://user-images.githubusercontent.com/20321723/147946036-93a55c80-02c6-4775-957e-6c006dccb3a6.mp4
