### ISSUE TITLE
[UBRS] Seal of Ascension Door

### ISSUE THREAD

**Issue by Kurthos** [azerothcore/azerothcore-wotlk#9032]
### Current Behaviour

Currently, the door is stuck open as if someone with the seal of ascension has opened it.

### Expected Blizzlike Behaviour

https://gyazo.com/c76222998a69f6208f174f46355fdd11

The door serves an important purpose - it prevents players from progressing into the first entry level raid content until they've completed their seal of ascension which grants access to UBRS.

This is a major milestone early in a guild's lifespan and builds social bonds with players.

### Source

https://classic.wowhead.com/quest=4742/seal-of-ascension

### Steps to reproduce the problem

Zone into UBRS, go left.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/97effd83d141419c00227833c7887c58e6598113

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
[Wowhead](https://www.wowhead.com/quest=4742/seal-of-ascension#comments:id=584335) 
>By shlomi on 2009/01/28 (Patch 3.0.8)
As of patch 3.0.8 the door to UBRS is open and the Seal of Ascension no longer required.
