### ISSUE TITLE
LBRS Quartermaster Zigris issues

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9033]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

[Quartermaster Zigris](https://wowgaming.altervista.org/aowow/?npc=9736)

1. Right now he don't patrolling room.
2. When player making LoS he is doing nothing even if player goes much far from his range.
3. He don't using [Hooked Net](https://wowgaming.altervista.org/aowow/?spell=15609) or [Drink Healing Potion](https://wowgaming.altervista.org/aowow/?spell=15504)

https://user-images.githubusercontent.com/85256266/140651215-06a8f418-0787-4496-9d94-51f511f463b8.mp4

### Expected Blizzlike Behaviour

1. He should patrol room
2. He should following to players in LoS
3. He should use all his spells

### Source

https://youtu.be/bcMPIdeqa74?t=2546
https://youtu.be/nA8emnau2sg?t=2418
https://youtu.be/jAY2FAWUngk?t=2228

### Steps to reproduce the problem

..go c 45749

### Extra Notes

Related to https://github.com/azerothcore/azerothcore-wotlk/issues/7366

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Need info on his potion casts, is it cast only once? What is the timer? Need more info.

**Comment by Shineslippers** [comment]
Did not find something usefull. Based on videos he is using it at 50% of his hp.

**Comment by Nyeriah** [comment]
> Did not find something usefull. Based on videos he is using it at 50% of his hp once.

Awesome, I was under that impression too. Thanks

**Comment by Shineslippers** [comment]
@Nyeriah Still not patrolling room. Can you check it when you will able?

**Comment by Nyeriah** [comment]
> @Nyeriah Still not patrolling room. Can you check it when you will be able?

Yes, soon (tm).

I'm working on that.
