### ISSUE TITLE
LBRS Overlord Wyrmthalak's adds disapear after death of boss

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9034]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

[Overlord Wyrmthalak](https://wowgaming.altervista.org/aowow/?npc=9568)'s adds disapear after death of boss.

https://user-images.githubusercontent.com/85256266/140652522-7136a9f2-4d90-4f54-b597-b5b3824b4660.mp4

### Expected Blizzlike Behaviour

They should stay alive

### Source

https://youtu.be/bcMPIdeqa74?t=3482
https://youtu.be/nA8emnau2sg?t=3101
https://youtu.be/jAY2FAWUngk?t=3322

### Steps to reproduce the problem

.go c 45757

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
What behaviour do we want if the group wipes after the boss died?

**Comment by Shineslippers** [comment]
Adds spawning not near boss we can keep them alive but they have to go back to spawn point.

**Comment by patou01** [comment]
I've put them to spawn roughly where we can seem them here, but I think with 3.3.5 damage the boss is gonna be dead before the adds make it.
![image](https://user-images.githubusercontent.com/2592673/140656696-23cbc8f6-a207-41e5-8291-c4d78b864d22.png)

**Comment by patou01** [comment]
I noticed we're also missing the "calls for help", so I'll add that while we're at it...

**Comment by Shineslippers** [comment]
Did you keep them alive or they will disappear after some time? I think we have to do there same as in other places. Can't remember where is the same situations going on.

**Comment by patou01** [comment]
It's the final boss anyway, but based on the code they should despawn 5 minutes later. On a boss reset they will desapwn instantly however.
![image](https://user-images.githubusercontent.com/2592673/140795944-73718d06-7732-4200-a7d1-ced470bdbfdf.png)
