### ISSUE TITLE
Black Temple - Illidan Stormrage leaves combat

### ISSUE THREAD

**Issue by Ravenguard13** [azerothcore/azerothcore-wotlk#9038]
### Current Behaviour

1 - during the fight, Illidan never changed into his demon form
2 - at final phase of fight, when Illidan Stormrage casts Shadow Prison ( https://wotlkdb.com/?spell=40647 ), he leaves the combat, restores all health. Can't be beaten. 

### Expected Blizzlike Behaviour

After Illidan casts the cage, he should still be there, then Maev Shadowsong shows up and the fight continues

As shown in video below:

### Source

https://youtu.be/0Gbd_9w-Drw
2:17

### Steps to reproduce the problem

1 - kill all the bosses, get to Illidan floor
2 - talk to Akama to start a fight
3 - hit him till phase 4

### Extra Notes

Problem with shadow prison needs to be doubleckecked more. I had this problem in a raid group, but when I went there solo, everything was fine.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d35c6b602234dfc313066a2de9db74eb97798c75

### Operating system

Debian 10 x64

**Comment by Meramaf** [comment]
Confirmed

**Comment by kissingers** [comment]
I test it today and it still doesn't look like it's fixed, can this bug be fixed?

**Comment by frizar** [comment]
still broken and unplayable

**Comment by benjymansy123** [comment]
@frizar, a better way to say what you said would be "Still not working as of commit [commit you're using]". Going to three separate issues and saying "Not fixed yet" doesn't do almost anything.

**Comment by Fireevil** [comment]
this error still continues in the new revision I already tested it and it is still a bug

**Comment by kissingers** [comment]
Disengagement because this code:
 me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
As soon as move to the last line of this judgment (originally in the third line), it almost never get out of the battle, I fix this myself,but not the final solution:
                case EVENT_PHASE_5_START:
                    if (me->HealthBelowPct(20))
                    {
                        me->CastSpell(me, SPELL_SHADOW_PRISON, true);
                        me->SendMeleeAttackStop(me->GetVictim());
                        Talk(SAY_ILLIDAN_MAIEV1);
                        events.Reset();
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000);
                        _me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);_
                        break;

**Comment by Dr-Arayashiki** [comment]
> Disengagement because this code: me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE); As soon as move to the last line of this judgment (originally in the third line), it almost never get out of the battle, I fix this myself,but not the final solution: case EVENT_PHASE_5_START: if (me->HealthBelowPct(20)) { me->CastSpell(me, SPELL_SHADOW_PRISON, true); me->SendMeleeAttackStop(me->GetVictim()); Talk(SAY_ILLIDAN_MAIEV1); events.Reset(); events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000); events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000); events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000); events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000); events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000); _me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);_ break;

the interesting thing is that if you remove the me->CastSpell(me, SPELL_SHADOW_PRISON, true); the boss does not reset and Maieve is summoned normally.... however it would be wrong as he must cast the Shadow Prison spell

**Comment by kissingers** [comment]
> > Disengagement because this code: me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE); As soon as move to the last line of this judgment (originally in the third line), it almost never get out of the battle, I fix this myself,but not the final solution: case EVENT_PHASE_5_START: if (me->HealthBelowPct(20)) { me->CastSpell(me, SPELL_SHADOW_PRISON, true); me->SendMeleeAttackStop(me->GetVictim()); Talk(SAY_ILLIDAN_MAIEV1); events.Reset(); events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000); events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000); events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000); events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000); events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000); _me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);_ break;
> 
> the interesting thing is that if you remove the me->CastSpell(me, SPELL_SHADOW_PRISON, true); the boss does not reset and Maieve is summoned normally.... however it would be wrong as he must cast the Shadow Prison spell

Yes,  2 mouth before, I move  events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000); me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);   to laster line, it's almost ok, but 2 mouth ago,  it also  can not work,   only delete me->CastSpell(me, SPELL_SHADOW_PRISON, true) can.  so I have to delete total  phase 5 now.

**Comment by kissingers** [comment]
So I think if it can be fixed such as Archimonde, It is work for Archimonde out of combat.   need test.
https://github.com/azerothcore/azerothcore-wotlk/pull/15128/commits/3f9c8a889ffb3866bcadb3236dc85662385511f8


        void Reset() override
        {
            me->SetReactState(REACT_AGGRESSIVE);
            TargetGUID.Clear();
            ChangeTargetTimer = 5000;
        }

        if (me->HealthBelowPct(20)) 
        {
            me->SetReactState(REACT_PASSIVE);
            ......

**Comment by kissingers** [comment]
I dont know how to pull a fix request, so who can do it?

**Comment by Dr-Arayashiki** [comment]
> I dont know how to push a fix request, so who can do it?

If you want, you can send me the cpp file that you fixed, I'll see how it's working and post the correction (if it's working correctly). I give the credits to you. But first of all, test this fix in every possible way to make sure everything is working fine. By the way, there are more things wrong with this boss... I even suggest fixing something else that has a problem at once 😄

**Comment by kissingers** [comment]
[boss_illidan.zip](https://github.com/azerothcore/azerothcore-wotlk/files/11752185/boss_illidan.zip)

**Comment by kissingers** [comment]
me->SetReactState(REACT_AGGRESSIVE);

**Comment by kissingers** [comment]
[illidan crash.zip](https://github.com/azerothcore/azerothcore-wotlk/files/11752232/illidan.crash.zip)

**Comment by AnchyDev** [comment]
> [illidan crash.zip](https://github.com/azerothcore/azerothcore-wotlk/files/11752232/illidan.crash.zip)

Please use [gist](https://gist.github.com/) if you are going to share logs or source files.

**Comment by kissingers** [comment]
Here can't use gist ,  replace with pastebin
https://pastebin.com/bkkNBgZ8

crash condition: me->SetReactState(REACT_PASSIVE); add before  SPELL_SHADOW_PRISON and    me->SetReactState(REACT_AGGRESSIVE); add after finish  SPELL_SHADOW_PRISON. 

            case EVENT_PHASE_5_START:
                if (me->HealthBelowPct(30))
                {
                    me->SetReactState(REACT_PASSIVE);
                    me->CastSpell(me, SPELL_SHADOW_PRISON, true);
                    me->SendMeleeAttackStop(me->GetVictim());
                    me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                    Talk(SAY_ILLIDAN_MAIEV1);
                    events.Reset();
                    events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000);
                    events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000);
                    events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000);
                    events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000);
                    events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000);
                    break;
                }

            case EVENT_PHASE_5_SCENE5:
                me->SetTarget(me->GetVictim()->GetGUID());
                me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                me->SetReactState(REACT_AGGRESSIVE);

if add after   me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE); and before  me->CastSpell(me, SPELL_SUMMON_MAIEV, true);  no crash till now.

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/33601959/d3f4075e-229e-4fc0-bbec-b9b6139a6efa)

**Comment by kissingers** [comment]
after this self fix 
never  out of combat  \ reset boss can not attack \ can not dialogue akama \  after kill boss, can not out ouf combat \server crash

> [boss_illidan.zip](https://github.com/azerothcore/azerothcore-wotlk/files/11752185/boss_illidan.zip)

**Comment by Dr-Arayashiki** [comment]
> Here can't use gist , replace with pastebin https://pastebin.com/bkkNBgZ8
> 
> crash condition: me->SetReactState(REACT_PASSIVE); add before SPELL_SHADOW_PRISON and me->SetReactState(REACT_AGGRESSIVE); add after finish SPELL_SHADOW_PRISON.
> 
> ```
>         case EVENT_PHASE_5_START:
>             if (me->HealthBelowPct(30))
>             {
>                 me->SetReactState(REACT_PASSIVE);
>                 me->CastSpell(me, SPELL_SHADOW_PRISON, true);
>                 me->SendMeleeAttackStop(me->GetVictim());
>                 me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
>                 Talk(SAY_ILLIDAN_MAIEV1);
>                 events.Reset();
>                 events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000);
>                 events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000);
>                 events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000);
>                 events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000);
>                 events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 30000);
>                 break;
>             }
> 
>         case EVENT_PHASE_5_SCENE5:
>             me->SetTarget(me->GetVictim()->GetGUID());
>             me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
>             me->SetReactState(REACT_AGGRESSIVE);
> ```
> 
> if add after me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE); and before me->CastSpell(me, SPELL_SUMMON_MAIEV, true); no crash till now.
> 
> ![image](https://user-images.githubusercontent.com/33601959/245983342-d3f4075e-229e-4fc0-bbec-b9b6139a6efa.png)

I see, what you posted gave me direction and it worked, the boss is no longer resetting. I'm going to take advantage and solve the problem that the boss has to fly and doesn't fly. After finishing everything, part of the credit goes to you :)

NOTE: As far as I've seen, you don't need me->SetReactState(REACT_PASSIVE); . Just leave the me->SetReactState(REACT_AGGRESSIVE); in case EVENT_PHASE_5_SCENE1:

**Comment by Dr-Arayashiki** [comment]
@kissingers this boss's problems are already being solved, and there are a few more besides those mentioned here. I'll check them all at once so I don't have to open pulls all the time. You are to be congratulated, thanks to your code I managed to discover a few more bugs besides the current one 😄

**Comment by kissingers** [comment]
Thanks for your fix work, but It try test sometimes, it seems not same as you test.

If only add  me->SetReactState(REACT_AGGRESSIVE) in case EVENT_PHASE_5_SCENE1: will out of combit.
and if only add me->SetReactState(REACT_AGGRESSIVE); after me->CastSpell(me, SPELL_SHADOW_PRISON, true); sometimes out of combit.

only  me->SetReactState(REACT_PASSIVE) add after me->CastSpell(me, SPELL_SHADOW_PRISON, true);  and add  me->SetReactState(REACT_AGGRESSIVE) in case EVENT_PHASE_5_SCENE1 will all times ok.

**Comment by Dr-Arayashiki** [comment]
> Thanks for your fix work, but I try test sometimes, it seems not same as you test.
> 
> If only add me->SetReactState(REACT_AGGRESSIVE) in case EVENT_PHASE_5_SCENE1: will out of combit. and if only add me->SetReactState(REACT_AGGRESSIVE); after me->CastSpell(me, SPELL_SHADOW_PRISON, true); sometimes out of combit.
> 
> only me->SetReactState(REACT_PASSIVE) add after me->CastSpell(me, SPELL_SHADOW_PRISON, true); and add me->SetReactState(REACT_AGGRESSIVE) in case EVENT_PHASE_5_SCENE1 will all times ok.

correct, rest assured because we also discovered that there is the question of the probability of the boss resetting and not resetting. We are already investigating here 😄

**Comment by Dr-Arayashiki** [comment]
@kissingers 
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/122452427/e17f4bd2-ddeb-4b1f-b4ec-87dc3d4ec10e)
for now, put it like this and test

**Comment by kissingers** [comment]
> @kissingers ![图像](https://user-images.githubusercontent.com/122452427/246629565-e17f4bd2-ddeb-4b1f-b4ec-87dc3d4ec10e.png) 现在，像这样放置并测试

test false.  after finish  SPELL_SHADOW_PRISON  , then use .gm on simulation all player died, the boss will still fight with maiev never finished.  

So must SetReactState(REACT_AGGRESSIVE) before all player died.  set at EVENT_PHASE_5_SCENE1 is good point.

**Comment by cavalierfly** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/20485107/9b088aed-edf5-4bd5-a817-e1b429e516fd)
@kissingers @Dr-Arayashiki this works well.
Another 2 problems:
1. Parasitic Shadowfiend(ID:23498) start attack immediately, players have no time to kill them
2. In phase 2, when Illidan flied, player cast spell "Divine Shield"(ID: 642), boss will reset directly...

**Comment by kissingers** [comment]
> ![image](https://user-images.githubusercontent.com/20485107/248566112-9b088aed-edf5-4bd5-a817-e1b429e516fd.png) @kissingers @Dr-Arayashiki this works well. Another 2 problems:
> 
> 1. Parasitic Shadowfiend(ID:23498) start attack immediately, players have no time to kill them
> 2. In phase 2, when Illidan flied, player cast spell "Divine Shield"(ID: 642), boss will reset directly...

1 only less then 4 player will happen, more than 4 will never happen, and the player can not move else will more Shadowfiend to himself.
2  also less then 2 player test

**Comment by kissingers** [comment]
case EVENT_PHASE_5_START:
                    if (me->HealthBelowPct(20))
                    {
                        me->SendMeleeAttackStop(me->GetVictim());
                        me->SetUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                        me->CastSpell(me, SPELL_SHADOW_PRISON, true);
						me->CastSpell(me, SPELL_SUMMON_MAIEV, true);
						me->SetReactState(REACT_PASSIVE);
                        Talk(SAY_ILLIDAN_MAIEV1);
                        events.Reset();
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE1, 9000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE2, 18000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE3, 24000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE4, 27000);
                        events.ScheduleEvent(EVENT_PHASE_5_SCENE5, 31000);
                        break;
                    }
                    events.ScheduleEvent(EVENT_PHASE_5_START, 1000);
                    break;
                case EVENT_PHASE_5_SCENE1:
                    break;
                case EVENT_PHASE_5_SCENE2:
                    Talk(SAY_ILLIDAN_MAIEV2);
                    break;
                case EVENT_PHASE_5_SCENE3:
                    if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                        maiev->AI()->Talk(SAY_MAIEV_SHADOWSONG_ILLIDAN2);
                    break;
                case EVENT_PHASE_5_SCENE4:
                    if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                        maiev->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                    break;
                case EVENT_PHASE_5_SCENE5:
					me->SetReactState(REACT_AGGRESSIVE);

`                    //me->SetTarget(me->GetVictim()->GetGUID());
                    DoMeleeAttackIfReady();
`
                    me->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                    if (Creature* maiev = summons.GetCreatureWithEntry(NPC_MAIEV_SHADOWSONG))
                    {
                        maiev->SetReactState(REACT_AGGRESSIVE);
                        maiev->RemoveUnitFlag(UNIT_FLAG_NOT_SELECTABLE);
                        maiev->AI()->AttackStart(me);
                    }
                    ScheduleNormalEvents(5);
                    break;

**Comment by Dr-Arayashiki** [comment]
This boss has some problems, although we have given some solutions, but at least now you can kill him, before you couldn't even kill him because he was restarting. It's that thing.... you have to go through the squeegee with Ymir anyway hahaha

> ![image](https://user-images.githubusercontent.com/20485107/248566112-9b088aed-edf5-4bd5-a817-e1b429e516fd.png) @kissingers @Dr-Arayashiki this works well. Another 2 problems:
> 
> 1. Parasitic Shadowfiend(ID:23498) start attack immediately, players have no time to kill them
> 2. In phase 2, when Illidan flied, player cast spell "Divine Shield"(ID: 642), boss will reset directly...

This boss has some problems, although we have given some solutions, but at least now you can kill him, before you couldn't even kill him because he was restarting. It's that thing.... you have to go through the squeegee with Ymir anyway hahaha 😃 

But speaking specifically about these issues.... it's a boss that you have to test with at least 5 people to clarify some things. When testing alone, any ability that makes him immune will likely reset the boss as he won't have another player to attack, so I don't know if the Divine Shield issue would be a real issue. 😸 

The important thing is that we are fixing it little by little lol 😄

**Comment by NostraDavid** [comment]
For those [running via docker-compose](https://github.com/azerothcore/acore-docker): I am using 7.0.0-dev.1 (Last pushed 2 months ago) and the bug is still there.

This comment is purely meant for users trying to figure out if it's been fixed for a certain version or not :)

PS: I am running a multibox with 5 accounts, if that matters.

**Comment by kissingers** [comment]
It seems in fixing
https://github.com/azerothcore/azerothcore-wotlk/pull/18601

I do my fix here, just can run and kill the boss
https://github.com/azerothcore/azerothcore-wotlk/commit/58aecdceac361a12e59c147120937598112c1d20

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/19574
