### ISSUE TITLE
Escape Through Force - Quest

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#905]
Description: While escorting and selecting "Force option, since there is Stealth as well" attacking Owls should appear and you will have to fight your way out.

Current behaviour: There are no attacking Owls at all, which should come in waves once u trigger event.

Expected behaviour: Owl (Attacking) NPCs should appear. Waypoints and movement are good tho.

Steps to reproduce the problem: Will leave to someone with more exp - SAI problem.

Quest ID - 994
AC hash/commit: 778cd9a

Operating system: Linux, Debian 9

Modules: Congrats on level, Premium

Other Customizations: No.

**Comment by Knindzagxg** [comment]
Quest work, but there should be attacking NPC's that come during escort.
At the moment, you just follow him and complete quest.

**Comment by BarbzYHOOL** [comment]
tried the fix?
