### ISSUE TITLE
POI of An Unholy Alliance has wrong location

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9054]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2285

Quest [An Unholy Alliance (Part 1)](http://wotlk.cavernoftime.com/quest=6522) started by the [Small Scroll](https://classic.wowhead.com/item=17008/small-scroll) looted from last boss at Razorfern dungeon, get us visiting a npc in Undercity.
Text from quest is very clear about it:
"Quest Objectives: Take the Small Scroll to Bragor Bloodfist in the Undercity"
However, upon opening map or clicking on "Show map" button to locate quest turn in, we get to see this: "Return to Bragor Bloodfist at Lordamere Lake in Silverpine Forest"
![ 2021-11-07 at 20 53 45](https://user-images.githubusercontent.com/77953030/140689204-9b979a14-e958-496e-ad9e-adecc6e900f8.png)
which can be very misleading, making players to actually swim to the lake and search for Bragor at the waters north of Fenris Isle. 

Tester:

The issue is confirmed. Quest mark of [An Unholy Alliance](https://wowgaming.altervista.org/aowow/?quest=6522) is located not in undercity.

![WoWScrnShot_110821_125759](https://user-images.githubusercontent.com/85256266/140721841-7ec6adba-4b17-44ef-a0a1-9666ca32f2aa.jpg)

### Expected Blizzlike Behaviour

Quest Turn-in marker should appear in Undercity Map when consulting map and when selecting quest from log and clicking on the "Show map" button. Quest description should indicate that NPC Bragor Bloodfist is actually in Undercity, not "at Lordamere Lake in Silverpine Forest".

### Source

This is probably another of those "blizzlike" bugs that were not corrected on tiem and later in Cataclysm quest was removed anyway. It's noticeable that this quests used to be turned it at a completely different NPC, Varimathras, a demon standing next to Lady Sylvanas, but was later changed for an orc, who then starts part 2 of the quest. This was done to keep consistence since during WotLK we actually get to kill Varimathras during the Wrathgate/Battle for Undercity event. 
Perhaps during those changes the error slipped and information got messed up.
"Patch 3.3.0 (08-Dec-2009): Bragor Bloodfist replaces Varimathras as the questgiver."

Since it's been stated already that blizzard bugs would be fixed/corrected on AC, I thought it would be good to get this one fixed too.

https://wowwiki-archive.fandom.com/wiki/Quest:An_Unholy_Alliance
https://mmo4ever.com/wow/quest.php?id=6522
http://wotlk.cavernoftime.com/quest=6522

### Steps to reproduce the problem

.q a 6522
click "show in map"

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Voxstrasza** [comment]
This one was confusing at first because the quest is now `14352` and not `6522` - it appears 6522 was deprecated when Varimathras was removed from the game without being tagged as such.  I have a fix ready.

**Comment by Voxstrasza** [comment]
@Shineslippers #9585
