### ISSUE TITLE
Priest's levitate doesn't remove properly in some case

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9056]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2286

Casting and quickly removing the Levitate buff right before you land causes player to be stuck in a floating Levitate-state, without actually having the buff. The effect doesn't cause slow fall, lasts forever, and doesn't get removed when mounting or taking damage, but does prevent jumping and causes janky behaviour when running down steep hills. Re-casting and removing Levitate returns player to normal state
Video: [Link](https://www.youtube.com/watch?v=_1DTnAJlYTw)

Tester:

The issue is confirmed. Casting [Levitate](https://wowgaming.altervista.org/aowow/?spell=1706) near ground and removing it at the same time could leave aura's effect on player.

https://user-images.githubusercontent.com/85256266/140770037-19b7c100-2e3f-4e87-b073-4efb05e81162.mp4

### Expected Blizzlike Behaviour

Removing Levitate buff returns player to normal state

### Steps to reproduce the problem

jump down
near ground
.aura 1706
.unaura 1706

### Extra Notes

Levitate has animation of bounce after grounding. Could be related to https://github.com/azerothcore/azerothcore-wotlk/issues/7090

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Ragelezz** [comment]
You levitate if you move around ? If aura is removed i highly doubt the effect is still present.

**Comment by Shineslippers** [comment]
Yea, you will keep being under levitate effect and can't jump and etc.
