### ISSUE TITLE
Running acore.sh on ARM64 keeps redownloading Deno (Exec format error)

### ISSUE THREAD

**Issue by digsgg** [azerothcore/azerothcore-wotlk#9071]
### Current Behaviour

Every time acore.sh is executed, it encounters an Exec format error due to Deno not being compatible with ARM64.

Since [this installer](https://deno.land/x/install/install.sh) (that is downloaded and run from ./apps/bash_shared/deno.sh) does not contain a specific condition for ARM64, Deno just installs the default 'unknown Linux' binary and gives the Exec format error.

### Expected Blizzlike Behaviour

Ideally, installing a generic ARM64 binary (such as the one encountered [here](https://github.com/LukeChannings/deno-arm64/releases), which runs perfectly on ARM64) would suffice.

A custom installer that detects ARM64 and points it to a proper binary would need to be made instead of downloading the currently used installer from denoland.

### Steps to reproduce the problem

1. Compile the server, for example
2. Run the server from acore.sh

### Extra Notes

Link to current installer script: https://deno.land/x/install/install.sh
Link to ARM64 deno builds: https://github.com/LukeChannings/deno-arm64/releases

### AC rev. hash/commit

a062653c0eee

### Operating system

Ubuntu Server 20.04.3 LTS ARM64

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/c43e1b8c0c3a17e48f1559bdfe13018aaab5008a
