### ISSUE TITLE
RDF Dungeon XP Reward Lost if Dead

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9082]
### What client do you play on?

enUS

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2289

When you are dead during the final encounter of a RDF dungeon, you do not get rewarded with experience. The chat message that you received the experience appears but your experience bar does not change.

Dicovered this already two times in Ragefire Chasm and in Scarlet Monastery Cathedral. My yesterdays group confirmed that they experienced the same in the past.

Tester: confirmed this after RDF runs in both RFC and Deadmines. In both cases, the bonus XP you get for doing a random dungeon shows up in the chat window, but is not added to the dead player's XP. Even /reloadui or logging out and back in again doesn't change the displayed XP, so it's not a display bug. 

Deadmines: 3050 RDF XP awarded, XP bar shows 2535 XP for mobs killed during the run, but the 3050 XP is not counted. (And the character didn't level up during this either, which is the only thing that could hide the xp.) The 3050 XP is missing.
![WoWScrnShot_110921_221614](https://user-images.githubusercontent.com/81782124/140920756-2fabaf2f-e2d9-43c2-8e1c-699d8e73940a.jpg)

RFC run - killed boss, only 1050 RDF XP shown this time as it wasn't the first run of the day, but XP bar is completely empty. Checked with macro as well and that also showed no XP earned despite the chat message.
![WoWScrnShot_110921_222539](https://user-images.githubusercontent.com/81782124/140920788-6fb0bc68-7e75-458a-93c7-379090ee0980.jpg)
![WoWScrnShot_110921_224123](https://user-images.githubusercontent.com/81782124/140922099-259a084d-e768-46f7-a854-ba89c9de6447.jpg)

### Expected Blizzlike Behaviour

The RDF bonus XP should be awarded even if you are dead. This is distinct from the boss kill XP, which you might not get if you hadn't damaged them or something.

### Source
I didn't find specific sources saying RDF bonus XP should be awarded to dead players, but if the XP is being shown as awarded in your chat window, which it is, then basic consistency says it should actually be awarded, not lost.

### Steps to reproduce the problem

1. Do not be max level.
2. Finish a RDF dungeon when being dead.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/27b880876dd411b2433ec227d69f6f79dc0c3ce4

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Toledoakailyena** [comment]
I confirm this bug happening to me today @ 11:50 am BRT, the rdf reward is shown in chat log and "consumed" if it's your first dungeon of the day, however you get no xp at all
