### ISSUE TITLE
Warlock's Drain Soul gives Soul Shards even if target doesn't yields experience or honor

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9083]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2292

Drain Soul is currently making warlocks gain a Soul Shard every single time enemy dies, even when enemy is so low that doesn't yield any experience or honor.
As you can clearly see on these images, I can obtain Soul Shards from mobs that are 8 levels and more below me and which give no experience. This is working all the time, on every mob, even 10+ levels lower.
![ 2021-11-09 at 14 04 48](https://user-images.githubusercontent.com/77953030/140913175-025992e6-ccbe-444d-b09e-5cfac67ec607.png)
![ 2021-11-09 at 14 04 53](https://user-images.githubusercontent.com/77953030/140913213-a8a31c0c-b144-4576-9340-5bf7e5ff1e62.png)

Tester:

The issue is confirmed. Using [Drain Soul](https://wowgaming.altervista.org/aowow/?spell=1120) create [Soul Shards](https://wowgaming.altervista.org/aowow/?item=6265) even if target doesn't yields experience or honor.

https://user-images.githubusercontent.com/85256266/140923007-bb7dc965-48ed-4e05-a84b-a2bd8c84577f.mp4

### Expected Blizzlike Behaviour

Drain Soul should give shards as description of spell saying: only when target yields experience or honor

### Source

Wowwiki [Drain Soul](https://wowwiki-archive.fandom.com/wiki/Drain_Soul?oldid=2293891)

### Steps to reproduce the problem

create warlock
.chal lev60
.learn all my class
cast drain soul to someone around

.cast 1120

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by patou01** [comment]
@nyeriah, I think this might be the result of https://github.com/azerothcore/azerothcore-wotlk/pull/8144 ?
