### ISSUE TITLE
Black Temple - Shade of Akama problem

### ISSUE THREAD

**Issue by Ravenguard13** [azerothcore/azerothcore-wotlk#9095]
### Current Behaviour

When Shade of Akama approaches Akame - he leaves combat and returns to his starting position, stealthed, with dialogue option. 
The Shade of Akama stays at the spot where he reached Akama, and can't be put into target.
The mob packs from both door keep showing up and it seems that they see through Akama's stealth, cuz they attack him

As shown here:  https://youtu.be/0KP1EL3ZkJE

### Expected Blizzlike Behaviour

You should kill all channeler mobs aound Shade of Akama. When Akama shots the red beam at the Shade of Akame he starts to walk towards him, and they fight, The group should help Akama deheat the shade while protecting him from packs of mobs that come out of doors one wave after another

### Source

https://youtu.be/mK5N7OAzPfQ

### Steps to reproduce the problem

1 - Kill all mobs in the room besides those around the Shade of Akama
2 - Talk to Akama to begin the encounter
3 - Quickly kill all the channeler mobs around the Shade
4 - Try to quickly kill mobs that come for Akama 
5 - Watch when the Shade of Akama approaches Akama

### Extra Notes

Can't see any consistency in this bug, I did kill mobbs as quick as possible, maybe that was the case, but it shouldn't be

### AC rev. hash/commit

github.com/azerothcore/azerothcore-wotlk/commit/d35c6b602234dfc313066a2de9db74eb97798c75

### Operating system

Debian 10 x64

**Comment by Selyria** [comment]
I can confirm
