### ISSUE TITLE
AzerothCore logo not showing correctly

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#910]
**Description**: The logo when starting the auth and world server is showing up as question marks.

**Current behaviour**: When you start the server the logo shows up as question marks.
![ac](https://user-images.githubusercontent.com/25745474/41030017-a08d3fa8-697d-11e8-9235-128a8b57ccaf.jpg)

Visual studio gives the warning following warnings
```
14>WheatyExceptionReport.cpp
14>.\src\server\worldserver\Master.cpp(121): warning C4566: character represented by universal-character-name '\u2588' cannot be represented in the current code page (1252)
14>.\src\server\worldserver\Master.cpp(121): warning C4566: character represented by universal-character-name '\u2557' cannot be represented in the current code page (1252)
14>.\src\server\worldserver\Master.cpp(122): warning C4566: character represented by universal-character-name '\u2588' cannot be represented in the current code page (1252)
14>.\src\server\worldserver\Master.cpp(122): warning C4566: character represented by universal-character-name '\u2554' cannot be represented in the current code page (1252)
etc (there's one for each character).
```

**Expected behaviour**: It should show the logo correctly. I'm pretty sure it was working in 825a62b
This isn't very important but I thought I'd point it out, also I don't know if it'd cause problems for anyone using non-roman characters in other parts of the core.

**Steps to reproduce the problem**:

1. Compile e222cbb
2. Run the server and check the top of the log
3. 

**Branch(es)**: master

**AC hash/commit**:  e222cbb

**Operating system**:  Windows 10, compiled with Visual Studio 15 2017 Win64

**Modules**:  VAS autobalance, Individual XP
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Winfidonarleyan** [comment]
I'm thinking necessary change encoding to UTF-8 no BOM

**Comment by Winfidonarleyan** [comment]
Yes, it is. 
![image](https://user-images.githubusercontent.com/18329778/41036697-19467c56-69bb-11e8-9dd2-256c2c7c8441.png)

**Comment by Trystanosaurus** [comment]
Closed by https://github.com/azerothcore/azerothcore-wotlk/pull/911
Thanks Winfidonarleyan
