### ISSUE TITLE
Hunter Spell - Auto Shot with Steady Shot

### ISSUE THREAD

**Issue by Huntard69** [azerothcore/azerothcore-wotlk#9107]
### Current Behaviour

As you can see in the video, while casting steady shot the hunter stops auto shot.

https://user-images.githubusercontent.com/94045087/141087854-46110e7e-9c1a-4246-8cc6-a1a72e4090b6.mp4

### Expected Blizzlike Behaviour

In wotlk auto shot should never stop while casting steady shot.

### Source

Video - Ensidia vs Algalon World first
At 3.28 you can see how it should work.
https://www.youtube.com/watch?v=uv_b1-bsN5o

### Steps to reproduce the problem

Pretty straightforward.

### AC rev. hash/commit

AzerothCore rev. 12e92b58082d 2021-11-09 10:00:44 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10

**Comment by Shineslippers** [comment]
Could be same as https://github.com/azerothcore/azerothcore-wotlk/issues/8883

**Comment by Huntard69** [comment]
They look different issues to me but i might be wrong.
Regardless, this is a huge issue because at end game, the marksman rotation includes 4 steady shots in a row and its a big dps loss. Not to mention that the talent wild quiver doesn't proc too because not casting auto shots.

**Comment by Algorak** [comment]
It's best to test it out for all classes. Melee and range. I often have the feeling that Paladins Dks etc also interrupt their automatic attack.

However, since quite a few players have linked Start Automatic Attack in spells, it is not so noticeable.
