### ISSUE TITLE
[Molten Core] Gehennas Add Flamewaker debuff doesn't stack properly

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9116]
### Current Behaviour

Flamewaker add uses sunder armor, other flamewaker add uses it on same target, duration resets

### Expected Blizzlike Behaviour

Duration should reset, and debuff should stack.

### Source

https://classic.wowhead.com/guides/gehennas-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Gehennas
get both adds on you
adds refresh sunder armor on you, instead of stacking
get 1 add on you
sunder armor properly stacks

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by unspecifiedperson2916** [comment]
https://youtu.be/ChGg2ZNIDDQ?t=1963 at this time in the video the tank has aggro on both adds and they stack sunder on him

video footage is from wow classic
