### ISSUE TITLE
[Molten Core] Garr Antimagic Pulse not working correctly

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9117]
### Current Behaviour

Antimagic pulse removes buff from targetted player only

### Expected Blizzlike Behaviour

Garr lets out anti-magic pulses, removing a beneficial effect from players in the raid. e.g. should target more than 1 player at a time.

### Source

https://classic.wowhead.com/guides/magmadar-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Garr
Stack up on tank
Notice tank only get debuff removed.

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by Nyeriah** [comment]
The spell works fine, it just happens to miss sometimes. Should it be able to miss?

```
Garr's Antimagic Pulse fails to dispel Dakiris's Arcane Intellect.
```

**Comment by temperrr** [comment]
Hmm, from my experience during Vanilla/Classic it should be nearly always, but I can't find a source.

**Comment by unspecifiedperson2916** [comment]
reviewing footage from wow classic, it can miss

https://youtu.be/SD5E2YaCZ3k?t=3819

garr casts his antimagic pulse and it does not take away any buffs from this player at this time stamp

**Comment by Nyeriah** [comment]
Ok, that video is from retail for certain and I see that  the pulse happens and nothing gets dispelled a few times, so I think this is fine as it is
