### ISSUE TITLE
[Molten Core] Sulfuron Harbinger issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9118]
### Current Behaviour

- [x] Can be pulled with sheep, resulting in not the full group aggroing, this way you can pull only the boss when sacrificing a few mages.
- [x] Dark mending is possibly healing further than 60 yards (not sure if bug)
- [x] Dark strike appears not to be working (needs to be checked)
- [x] Inspire appears only on Sulfuron himself, is not casted on adds.

### Expected Blizzlike Behaviour

- [ ] If you pull 1, whole group should aggro
- [ ] Dark mending has a max range of 60 yards according to wowhead (may be wrong)
- [ ] dark strike should add extra damage to next melee hit
- [ ] Inspire should be casted on adds.

### Source

https://classic.wowhead.com/guides/sulfuron-harbinger-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Sulfuron Harbinger

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by UltraNix** [comment]
@temperrr Everything from here is done?

**Comment by unspecifiedperson2916** [comment]
"If you pull 1, whole group should aggro"
 https://youtu.be/SD5E2YaCZ3k?t=6177
This is correct

"Dark mending has a max range of 60 yards according to wowhead (may be wrong)"
https://www.youtube.com/watch?v=7WyGnfithns&ab_channel=Sean
Skull is being dragged away and can't be healed by the other three priests.

"Dark strike appears not to be working (needs to be checked)"
"dark strike should add extra damage to next melee hit"
https://classic.wowhead.com/npc=12098/sulfuron-harbinger#abilities;mode:40player
Dark strike is not an ability used by Sulfuron or the priests

"Inspire should be casted on adds."
https://classic.warcraftlogs.com/reports/6gHW23Y4VFMvPzKm#fight=37&type=casts&hostility=1&source=129&ability=19779
This is correct

**Comment by Nefertumm** [comment]
Inspire is casted on adds, can't reproduce that one.
https://www.youtube.com/watch?v=gbPfL8DMzQw
