### ISSUE TITLE
[Molten Core] Golemagg Issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9119]
### Current Behaviour

- [x] Golemagg's Trust isn't active on adds when they are close to boss
- [x] Magmasplash is not being used on tanks
- [x] Golemagg is using Enrage (Not listed on wowhead)
- [x] Earthquake at 10% is not happening, or not doing AOE damage.
- [ ] When Golemagg dies, the Adds die

### Expected Blizzlike Behaviour

- [ ] Golemagg's trust needs to be active on adds when tanked too closely
- [ ] Magmasplash should be used on the tanks
- [ ] Golemagg should not use enrage
- [ ] Earthquake needs to happen at 10% and should deal area damage (this is the enrage)
- [ ] When golemagg dies, adds should despawn so no loot is there.

### Source

https://classic.wowhead.com/guides/golemagg-the-incinerator-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Golemagg

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by T1ti** [comment]
_When Golemagg dies, the Adds die_

That's blizzlike
