### ISSUE TITLE
[Molten Core] Majordomo Issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9120]
### Current Behaviour

- [x] When pulling the boss group with sheep, you can cause the adds to be seperate and resetting from the group, so you can tank sulfuron alone, with no adds
- [x] Blastwave is being used on Majordomo and Adds (not listed on Wowhead, may be wrong)
- [x] Aegis of Ragnaros is used on Majordomo
- [x] The adds had loot, when they all died, the corpses disappeared
- [x] Threat is dropping from tanks randomly

### Expected Blizzlike Behaviour

- [x] The whole pack should be pulled no matter what
- [x] Blastwave should not be used (not listed on wowhead at least, I could be wrong)
- [x] Aegis of Ragnaros should be casted on adds, not on Majordomo
- [x] Damage shield should be used on Majordomo
- [x] Magic Reflection should be used
- [x] Threat should not be randomly dropping from tanks
- [x] The adds should either have no loot, or should not despawn when fight ends.

### Source

https://classic.wowhead.com/guides/majordomo-executus-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Majordomo

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by UltraNix** [comment]
@temperrr Everything from here is done?

**Comment by UltraNix** [comment]
@temper
`When pulling the boss group with sheep, you can cause the adds to be seperate and resetting from the group, so you can tank sulfuron alone, with no adds`
Cannot reproduce it - Just used poly on add, immuned and the whole pack aggroed on me.

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Majordomo_Executus
`Blast Wave – A damaging area of effect flame attack which hits nearby players with moderate fire damage.`

**Comment by unspecifiedperson2916** [comment]
"Blastwave should not be used (not listed on wowhead at least, I could be wrong)"
https://youtu.be/uoE_LPuDi_4?t=5577
Blastwave is being used by majordomo and the adds in this video

"The adds should either have no loot, or should not despawn when fight ends."
https://i.imgur.com/65KZL0u.png
Evidence from classic wow where adds can drop loot on majordomo

"Threat should not be randomly dropping from tanks"
https://youtu.be/Tr0xmpm2aiw?t=5075
Majordomo does a threat drop every time a player is teleported to the burning coals in the center of the area. All aggro does not reset, only Majordomo.

"Magic Reflection should be used"
In previous two videos, magic reflection is being used

"Damage shield should be used on Majordomo"
https://youtu.be/Tr0xmpm2aiw?t=5073
Majordomo is absorbing damage in this video timestamp

"Aegis of Ragnaros should be casted on adds, not on Majordomo"
Can't find any evidence to support that, seen many videos in classic wow and the ability says that its a self-cast.

"The whole pack should be pulled no matter what"
"When pulling the boss group with sheep, you can cause the adds to be seperate and resetting from the group, so you can tank sulfuron alone, with no adds"
The elites should be immune to sheep. The healers should be susceptible to sheep. Sheeping one of the healers should pull everything else.

**Comment by T1ti** [comment]
I did this report for domo when testing it a while ago

_Majordomo : 
- https://classic.wowhead.com/spell=21086/encouragement is missing, Majordomo should cast it whenever an add dies, it will buff all the adds. buff should reset on wipe
- healing mechanic is missing, whenever all adds except 1 dies, the last add should heal to full and become buffed
I believe it comes from this spell : https://classic.wowhead.com/spell=21090/champion
but it's missing in the 3.3.5 DBC
-when only 4 adds remain, he should cast https://classic.wowhead.com/spell=21087/immunity (also missing in dbc) which makes the remaining adds immune to fear and polymorph
-teleport's visual is missing 
https://classic.wowhead.com/spell=19484/majordomo-teleport-visual
-he is missing the separation anxiety mechanic, this is the standard anti abuse mechanic, when adds are too far, make them enrage and immune to cc
https://classic.wowhead.com/spell=21095/separation-anxiety
triggered by https://classic.wowhead.com/spell=21094/separation-anxiety

-he should use aegis of ragnaros on pull on himself and say text

-teleport isn't working at all atm(after after filling the missing spell_target_position data in db) and doesn't do anything.

-he has two teleport spells, one which teleport the tank, another which teleports a random player. he should cast one of the two, similar to gehennas' shadow bolt. His teleport should also reset the tank threat(only the tank tp ?)

-majordomo shouldn't sue the spell "blast wave", only the Elites use it

-his defeat event is pretty lame, he just despawns, he should use some teleport spells with visuals
https://classic.wowhead.com/spell=19484/majordomo-teleport-visual_
