### ISSUE TITLE
[Molten Core] Shazzrah doesn't blink

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9121]
### Current Behaviour
 
Shazzrah is not blinking

### Expected Blizzlike Behaviour

Shazzrah should blink into casters, dropping all aggro.

### Source

https://classic.wowhead.com/guides/shazzrah-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Shazzrah 

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by Nyeriah** [comment]
Uhm, I might have tested this https://github.com/azerothcore/azerothcore-wotlk/pull/8942/files wrong then, because right now it teleports the players in instead of the boss teleporting himself to players

**Comment by patou01** [comment]
>  Blink
Shazzrah teleports on top of a random player, clearing all threat in the process. This is cast roughly every 30 seconds, but times can vary.
    This is Shazzrah's most dangerous ability for a couple of reasons: He wipes all threat on him on blinking, he will continue casting Arcane Explosion consistently after blinking, and unlike the other abilities, he can Blink at random times through the fight.
    The tanks must be ready to get to Shazzrah's new position and establish threat once more immediately after the Blink.
    After a Blink, all raid members must stop DPS and let the tanks establish aggro before attacking again. If you're the target Shazzrah used Blink on, run to the tanks and then away from Shazzrah once they pick aggro.
    This ability is also why the raid must be spread out and not stacked, so Arcane Explosion deals the least damage possible after a Blink.

This is what wowhead guide says...
