### ISSUE TITLE
[UBRS] The Beast Issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9127]
### Current Behaviour
 
The beast can walk over the firewall
The beast casts fireball and then directly fireblast always
The RP doesn't always work, with the two guards not running away and dieing, the beast does come out usually.

### Expected Blizzlike Behaviour

The beast should deaggro when walking over the firepit walls and reset.
The beast should not use fireball and then blastwave at the same time, this should be more random
The RP should work, where the two guards near the beast should run away, and then get killed by him, then he should walk around the room (only last part works correctly 100% of the time at the moment)

### Source

https://www.wowhead.com/npc=10430/the-beast#comments

### Steps to reproduce the problem

Go to UBRS
Walk in the room before the beast at normal speed to observe
dont immidiately teleport to the beast.

### AC rev. hash/commit

06bc64d1c370

### Operating system

Win64

### Custom changes or Modules

Eluna

**Comment by UltraNix** [comment]
@temperrr `The RP doesn't always work, with the two guards not running away and dieing, the beast does come out usually.`
It activates when enter the areatrigger near the firewall

**Comment by temperrr** [comment]
> @temperrr `The RP doesn't always work, with the two guards not running away and dieing, the beast does come out usually.` It activates when enter the areatrigger near the firewall

On local AC it works, but on CC I have yet to see the guards die properly.
