### ISSUE TITLE
Elemental Wand Damage Affected By Physical Damage Debuff

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9130]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2298

I have a wand [Gravestone Scepter] equipped. The wand deals shadow damage. While questing in Duskwallow Marsh I fighted the spiders at the cave north of Brackenwall village. During fighting with my wand the wand dealt about 30 to 50 damage in average. Then I got infected by the poison "Debilitating Poison" which reduces my physical damage dealt by 75%. This also affected my wands damage. See combat logs.

![WoWScrnShot_111021_142129](https://user-images.githubusercontent.com/62797536/141121956-87c914b8-33ad-4a30-81c2-7e59022022ba.jpg)
I get infected by the poison and my wand deals between 11 and 14 damage non-crit.

![WoWScrnShot_111021_142133](https://user-images.githubusercontent.com/62797536/141122109-c56208c1-81e3-40e5-b05f-5cd60738babd.jpg)
After the poison fades my wands damage goes up to between 36 and 56 damage. The log also says that the wand deals shadow damage.

I was not able to test this with other magical wands. This needs some further investigation to maybe identify a general problem with magical wands dealing physical damage.

Tester: confirmed. Tested with the Sceptre and `aura 43133` and the damaged increased markedly when the debuff wore off:

![WoWScrnShot_111121_220150](https://user-images.githubusercontent.com/81782124/141291365-40ca2208-f584-4e8e-bdfa-1c0459ee04a5.jpg)

@gurveleg comments:
>Wands are not considered spells so they arent affected by any spell modifiers. Wands however do elemental damage (or physical damage in the case of pearl wand) and that should not be affected by a physical damage reduction (except pearl wand), even tho the shoot ability itself is considered phyical ability. Its about damage.
Mobs that are immune to shadow or fire damage wont take any damage from fire or shadow damage wands for example.
>
>So the physical damage rduction poison reducing a shadow damage wand damage is defiantely a bug.

@Nyeriah comments:
> Both statements are correct. Yes, this bug happens because the Shoot ability is physical and we just edit the school of the damage dealt during execution according to the wand type, without checking for the rest.

Also see discussion on TC here: https://github.com/TrinityCore/TrinityCore/issues/16058

### Expected Blizzlike Behaviour

Wand with magical damage (shadow, frost, fire, holy, ...) should not be affected by physical damage lowering debuffs since it is magical damage.

Physical damage lowering debuffs should only affect physical damage wands like [Pearled Wand].

### Source

https://wowpedia.fandom.com/wiki/Wand?oldid=2356128

### Steps to reproduce the problem

1. .additem [Gravestone Scepter]
2. cast `.aura 43133` on yourself.
3. Wand damage gets reduced

### Extra Notes

Gravestone Scepter: https://wowgaming.altervista.org/aowow/?item=7001
Debilitating Poison: https://wowgaming.altervista.org/aowow/?spell=43133

Pearled Wand (physical wand example): https://wowgaming.altervista.org/aowow/?item=36655

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
Just to add to this: I believe the issue is that the damage calculations already happened by the time we change the schooltype, it might seem like an obvious conclusion, but perhaps it helps looking into it later
