### ISSUE TITLE
UBRS - Blackhand dreadweaver shadow bolt mana cost

### ISSUE THREAD

**Issue by Nyeriah** [azerothcore/azerothcore-wotlk#9148]
### Current Behaviour

*** Issue reported by @Kurthos

The spell costs too much mana, the mob goes oom after 4-5 casts.

### Expected Blizzlike Behaviour

The mob shouldn't go oom so fast.

### Steps to reproduce the problem

Engage the mobs
Notice they oom after 4-5 casts.

### Extra Notes

The spell they cast - Shadow Bolt - 12739 has SPELL_ATTR0_LEVEL_DAMAGE_CALCULATION, so the mana cost scales with caster level.

At level 60, it costs average 400-450 mana

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellInfo.cpp#L2412-L2421

Not sure what's the correct way to address this, but I don't think they should oom so fast, so something might be wrong

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b1f038336dbe146190702743990b6b17864eeded

### Operating system

Win11 x64

**Comment by T1ti** [comment]
Only the spell dmg should scale, not the cost ? 
The official name of this flag is 
![image](https://user-images.githubusercontent.com/40864460/141513864-37a9e1da-c190-4992-b8ea-ddc177c3bdfb.png)

**Comment by Nyeriah** [comment]
> Only the spell dmg should scale, not the cost ? The official name of this flag is ![image](https://user-images.githubusercontent.com/40864460/141513864-37a9e1da-c190-4992-b8ea-ddc177c3bdfb.png)

Yes, that's also what I was thinking, but TC also has the mana scaling so it left me wondering

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellInfo.cpp#L3228-L3234

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/141515862-b241b1cd-ac67-467f-a612-f5ce1432444b.png)
on vmangos it is defined as dmg only

**Comment by Nyeriah** [comment]
> ![image](https://user-images.githubusercontent.com/40864460/141515862-b241b1cd-ac67-467f-a612-f5ce1432444b.png) on vmangos it is defined as dmg only

Yes, but they still use it to calculate power cost

https://github.com/vmangos/core/blob/b14e54e2aade2882de45d0df7035f6ef85773427/src/game/Spells/Spell.cpp#L7449-L7450

**Comment by T1ti** [comment]
In the AC formula : 
GtNPCManaCostScalerEntry const* spellScaler = sGtNPCManaCostScalerStore.LookupEntry(SpellLevel - 1) = **1** (1 for lvl 20)
            GtNPCManaCostScalerEntry const* casterScaler = sGtNPCManaCostScalerStore.LookupEntry(caster->getLevel() - 1) = **4,048** (lvl 59)
            if (spellScaler && casterScaler)
                powerCost *= casterScaler->ratio / spellScaler->ratio;
powerCost = 4,048 / 1 = 4,048

95 (base mana cost) * 4,048 = 384.56 mana

- On vmangos :   powerCost = int32(powerCost / (1.117f * spellInfo->spellLevel / caster->GetLevel() - 0.1327f));

95 / (1.117 * 20 / 59 - 0.1327) = 386.26

So both seem to return about the same value

**Comment by T1ti** [comment]
Vid from Classic https://youtu.be/-RwYweWFJlw?t=318

His mana goes from 2369 to 2059, so 310 mana per cast

**Comment by Nyeriah** [comment]
Thanks a lot @T1ti , so we are just slightly off

**Comment by T1ti** [comment]
My current guess : 
1:my video is from classic vanilla 
2: since that DBC (npcmanacostscaler) was added in tbc, the pre tbc system was different 
3:vmangos used the tbc+ valued as reference and they are wrong for their version 
4: we need footage of tbc+ to compare.

**Comment by T1ti** [comment]
Ok so I went on the TBC Classic PTR and tested https://tbc.wowhead.com/npc=7667/lady-sevine#abilities who has the same level and uses the same shadow bolt spell
From my testing she spends 364 mana per cast, which seems to match our values

So it does indeed seem that the formula changed from Vanilla to TBC.
AC is currently 100% blizzlike with the value I tested on TBC classic : **90 * 4.048 = 364.32**

**Comment by Nyeriah** [comment]
Okay, so this is a non-issue, closing it, thank you

**Comment by T1ti** [comment]
I also checked their manapool, it is correct so it's 100% blizzlike, in TBC/Wotlk mobs spend more mana than in Vanilla.
with 2369 mana they should go oom in 6 casts (6.49)
