### ISSUE TITLE
Battered chest (ID: 2843) incorrect loot tables

### ISSUE THREAD

**Issue by schell244** [azerothcore/azerothcore-wotlk#9158]
### Current Behaviour

Battered chest id: 2843 can be found in start areas and should contain loot for level 1-5, but currently they contain loot for level 5-10.
Loot tables seem to be equal with Battered chest id: 106318:
https://vanilla-twinhead.twinstar.cz/?object=106318

### Expected Blizzlike Behaviour

Correct loot tables (and spawn points):
https://classic.wowhead.com/object=2843/battered-chest

### Source

https://classic.wowhead.com/object=2843/battered-chest
https://classic.wowhead.com/object=106318/battered-chest

Related commits from other Projects:
Loot tables (VMangos):
https://github.com/vmangos/core/commit/b159a1cdf32417cdf3d36eaaf6389577f12fc427

Spawn locations and pools(CMangos):
https://github.com/cmangos/classic-db/commit/2230752558dba612cfaeef72cb0f4f202114f7d7
https://github.com/cmangos/classic-db/commit/0ac8aa13372861d8d9f2a3cf573462c78eda1ff2

### Steps to reproduce the problem

.go gameobject 1397 -> check loot

### AC rev. hash/commit

10841cf

### Operating system

Win10

**Comment by T1ti** [comment]
- For clarification, this chest https://classic.wowhead.com/object=2843/battered-chest#contains;0+2-19+1 should only be in lvl 1-5 starter noob areas(like Northshire) and contain only lvl 1-5 items

- And this one should be in starting zones outside of the noob area (level 5-10 like Elwynn) and contain level 5-10 items https://classic.wowhead.com/object=106318/battered-chest#contains;0+2-19+1
