### ISSUE TITLE
Item Deviate Fish - missing effect "Party Time" & spell Rejuvenation

### ISSUE THREAD

**Issue by schell244** [azerothcore/azerothcore-wotlk#9159]
### Current Behaviour

Deviate Fish is missing spell rejuvenation and spell effect party time

### Expected Blizzlike Behaviour

Deviate Fish should trigger those spells when eating it:

https://classic.wowhead.com/spell=8070/rejuvenation
https://classic.wowhead.com/spell=8067/party-time

### Source

https://github.com/TrinityCore/TrinityCore/pull/25802
https://classic.wowhead.com/item=6522/deviate-fish

### Steps to reproduce the problem

1) .additem 6522
2) check effects

or look into code:
https://github.com/azerothcore/azerothcore-wotlk/blob/10841cf9e43e9ef7e23aba8df14a122246f44a04/src/server/scripts/Spells/spell_item.cpp#L2012

### AC rev. hash/commit

10841cf

### Operating system

Win10

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9163
