### ISSUE TITLE
[CRASH.LOG] Linux [BUGED]

### ISSUE THREAD

**Issue by irgc** [azerothcore/azerothcore-wotlk#916]
I found a crash bug and need to crash.log for report!

I built the server Linux on debug mode

cmake ../ -DCMAKE_INSTALL_PREFIX=/home/debug/server/ -DTOOLS=0 -DSCRIPTS=1 -DWITH_COREDEBUG=1

I started the server with  ./worldserver   OR    screen -S css_1 -d -m ./worldserver

i login and will to crashed server by bug and  worldserver dump freeze close.

iwant see more details and send report by crash.log  ! but icant on linux

Crash.log file will not be created !

Branch(es):
master

AZ rev. hash/commit:
https://github.com/azerothcore/azerothcore-wotlk/commit/8481eec5beac5a2e65052f95a6ff6aa22c5db981

Operating system:
Linux, ubuntu 17.10 SERVER

MY MODUELS:
mod-transmog

**Comment by Viste** [comment]
for get crashdump tune your worldserver.conf and run through gdb

**Comment by irgc** [comment]
Take a sample!

**Comment by Viste** [comment]
```
#! /bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR
cd $DIR
echo "run\n" > gdbcommands
echo "shell echo -e \"SERVERCRASHEVENT\"        " >> gdbcommands
echo "shell echo -e \"\nCRASH ON\" `date`       " >> gdbcommands
echo "info program                              " >> gdbcommands
echo "shell echo -e \"\nBACKTRACE\n\"           " >> gdbcommands
echo "bt                                        " >> gdbcommands
echo "shell echo -e \"\nBACKTRACE FULL\n\"      " >> gdbcommands
echo "bt full                                   " >> gdbcommands
echo "shell echo -e \"\nTHREADS\n\"             " >> gdbcommands
echo "info threads                              " >> gdbcommands
echo "shell echo -e \"\nTHREADS BACKTRACE\n\"   " >> gdbcommands
echo "thread apply all bt full                  " >> gdbcommands
chmod +x gdbcommands
while :
do
    echo "starting worldserver";
    #./worldserver
    mkdir -p crashes
    gdb worldserver --batch -x gdbcommands | tee crashes/current
    FILE=$(date +%s)
    sed -i '1,/SERVERCRASHEVENT/d' crashes/current
    mv crashes/current crashes/$FILE".crash"
    find crashes/ -name '*.crash' -and -size -10k -delete
    echo "worldserver stopped";
    sleep 1
done
``` 
i'm use that script and run wordserver ./name-what-you-chose-for-script

**Comment by Viste** [comment]
OMG please install windows
