### ISSUE TITLE
[Item] Many Tome of Conjure Mana Gem exists as some different items

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#9165]
### Current Behaviour

There are various items that are supposed to be some Tome of Conjure Mana Gem. However, they are different.

|Item ID|wowgaming.altervista.org/aowow|TBC wowhead|An already existing item with the same name|
|---|---|---|---|
|4145|[NPC Equip 4145](https://wowgaming.altervista.org/aowow/?item=4145)|[Tome of Conjure Mana Gem](https://tbc.wowhead.com/item=4145/tome-of-conjure-mana-gem)|Not found
|8840|[Renegade Boots](https://wowgaming.altervista.org/aowow/?item=8840)|[Tome of Conjure Mana Gem II](https://tbc.wowhead.com/item=8840/tome-of-conjure-mana-gem-ii)|9864: Renegade Boots [wowgaming.altervista.org/aowow](https://wowgaming.altervista.org/aowow/?item=9864) [TBC wowhead](https://www.wowhead.com/item=9864/renegade-boots)
|8861|[NPC Equip 8861](https://wowgaming.altervista.org/aowow/?item=8861)|[Tome of Conjure Mana Gem III](https://tbc.wowhead.com/item=8861/tome-of-conjure-mana-gem-iii)|Not found|
|8889|[NPC Equip 8889](https://wowgaming.altervista.org/aowow/?item=8889)|[Tome of Conjure Mana Gem IV](https://tbc.wowhead.com/item=8889/tome-of-conjure-mana-gem-iv)|Not found|

### Expected Blizzlike Behaviour

They should all be some Tome of Conjure Mana Gem shown on the table above.

### Steps to reproduce the problem

`.additem 4145`
`.additem 8840`
`.additem 8861`
`.additem 8889`
Then compare each of them to wowhead.

### Extra Notes

Beside the Renegade Boots 9864, none of them are obtainable via normal means.

### AC rev. hash/commit

AzerothCore rev. 863455736eeb 2021-11-09 14:38:59 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by UltraNix** [comment]
Resolved by f332b8ef6b
