### ISSUE TITLE
[BUG] Hunter Pet's

### ISSUE THREAD

**Issue by irgc** [azerothcore/azerothcore-wotlk#917]
Description: If you creat hunter class and full tier 9 set + train or talent.

After taking the pet, i will to tested and isee full dps pet is buged

damages:
112
147
212
120
134
Highest attack = 245

http://tinypic.com/r/9laiyg/9

Branch(es):
master

AZ rev. hash/commit:
8481eec

Operating system:
Linux

MY MODUELS:
mod-transmog

sry bad en...

**Comment by Nefertumm** [comment]
Please... Use a translator.............

**Comment by irgc** [comment]
updated and add image

**Comment by talamortis** [comment]
please feed your pet then retest

**Comment by irgc** [comment]
hi

@talamortis 


tested and screen

http://tinypic.com/r/29yjdd5/9

**Comment by talamortis** [comment]
Tested, formula for damage reduction on enemy aswell as damage per second, everything seems correct.
http://wowwiki.wikia.com/wiki/Damage_reduction
http://wowwiki.wikia.com/wiki/Damage_per_second
