### ISSUE TITLE
Eye of Kilrogg Unable to Attack

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9171]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2312

Warlock ability "Eye of Kilrogg" seems to be a bit bugged.
At the moment the Eye is summonable and movement and behavior are normal. Aggro radius is pretty small (probably like it was on retail) but **it's unable to attack**.

It also has quite some HP. I couldn't find any source for the right values but it was possible to stand quite a lot of hits.

Tester: confirmed that the Eye is unable to attack. The HP issue is more difficult to find sources for, and is not confirmed. However, the AC Eye also has a mana bar, which is not correct. This seems to be because its `ManaModifier` is set to 1.

### Expected Blizzlike Behaviour

Eye should be able to attack when summoned/controlled.

### Source

"Most mobs will not attack the eye unless it's used to attack them first."
"If you use it to attack an instance boss, the boss may do some of their custom emotes"
"As of lately, it appears the Eye has more health and can attack." - https://wowpedia.fandom.com/wiki/Eye_of_Kilrogg_(warlock_ability)?oldid=2293875

By Psyblade1st on 2009/03/11 (Patch 3.0.9)		
Warlock: Eye of Kilrogg, attack!
(Eye of Kilrogg hits Rabbit for 114) - https://www.wowhead.com/spell=126/eye-of-kilrogg#comments:id=638011

By Yukazi on 2007/12/03 (Patch 2.3.0)
"Something that I just noticed is that the Eye of Kilrogg can actually attack!
One of my friends got ahold of me and told me that he summoned it and it was able to kill a rabbit. Yeah, I know, kill a rabbit, but that would mean that it has the ability to attack!
So I got on my character and gave it a try outside of Stormwind.

Eye of Kilrogg hits Defias Bandit for 106.
Eye of Kilrogg hits Rat for 146.

It's not that great of damage and it is slow, but I had no idea that it could actually do anything other than spy." - https://www.wowhead.com/spell=126/eye-of-kilrogg#comments:id=195062

Source for no mana bar and >1 HP - https://youtu.be/rRcg6TI86oM?t=65, shot September 2010, so 3.3.5 source.

### Steps to reproduce the problem

Get a warlock to lvl 22 and learn skill Eye of Kilrogg
Cast Eye on Kilrogg and approach a mob
Try attacking an enemy or neutral mob (won't be aggroed anyway)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/12e92b58082dfda8b73b50aa97b98b9479bb7629

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by lingxDEV** [comment]
In regards to the HP value: https://wowpedia.fandom.com/wiki/Eye_of_Kilrogg_(warlock_ability)

Check the patch notes at the bottom. States it should have 1 HP.

**Comment by Shineslippers** [comment]
You can find some videos from newer patches where i definitely have more hp, but change log doesn't poinint to it.

**Comment by Azcobu** [comment]
>In regards to the HP value: https://wowpedia.fandom.com/wiki/Eye_of_Kilrogg_(warlock_ability)
>Check the patch notes at the bottom. States it should have 1 HP.

You're assuming that patch list is complete, which given the later line in the [2010 version](https://wowpedia.fandom.com/wiki/Eye_of_Kilrogg_(warlock_ability)?oldid=2293875) of the article where it says "as of lately, it appears the Eye has more health" means there's a contradiction somewhere. 

Given we have video from 3.3.5 showing it taking multiple hits from mobs, i don't see how it could have 1 HP - could it be buffed by party members? I wouldn't have thought so, but it's the only other thing I can think of to explain it surviving multiple hits.

**Comment by Shineslippers** [comment]
One more thing. Eye has `Mana: 3,994` while `Health: 427`. That's not normal.

**Comment by Azcobu** [comment]
If you look in Keira, it has a HealthModifier of 0.1, but the ManaModifier is 1 when it should probably be 0. The ArmorModifier is 1 as well which also seems iffy, don't think it should have armour.
