### ISSUE TITLE
[Chat sanitary check] Players can link a fake completed achievement

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#9183]
### Current Behaviour

It is possible to link a completed achievement which isn't actually completed.
In the following video, I have linked the achievement using UnderAchiever 3.3.5b,
https://www.curseforge.com/wow/addons/underachiever

https://user-images.githubusercontent.com/22718174/141663362-d22c2a1e-8d7d-49e0-90b3-9a5885210e76.mp4

### Expected Blizzlike Behaviour

Maybe Activion-Blizzard didn't protect themselves from linking a fake completed achievement back on 3.3.5a, but it does feels wrong to be able to link an completed achievement which is actually not completed. I think whenever someone sends an achievement link, it should link with the actual progression of the achievement.

### Steps to reproduce the problem

Get UnderAchiever 3.3.5b.
https://www.curseforge.com/wow/addons/underachiever
Link any non-completed achievement.

### AC rev. hash/commit

AzerothCore rev. 863455736eeb 2021-11-09 14:38:59 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

**Comment by Kitzunu** [comment]
This is blizzlike. Blizzard didnt patch this until 9.1.5 (which is the latest patch of retail)

**Comment by Nyeriah** [comment]
Oh, I always thought this was taken care here: https://github.com/TrinityCore/TrinityCore/commit/e858706270c3059acf6915e7cf655eed0f7e88bb#diff-56b141374cf0384a2887c9fd490c6a79a3d2f31fb020ee0e423a5685344b59d3

But I also think this is blizzlike, ja, there are even addons to send fake achievements (some people used them to fake cutting edge/ahead of the curve to get easier invites f.e)
