### ISSUE TITLE
Effects of Root may interrupt spells casting

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9187]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2319

[https://db.rising-gods.de/?npc=11551](https://db.rising-gods.de/?npc=11551) have a root spell. When a player is affected by the spell (when it applies, not during the duration) as well as when the debuff fades, spellcasting is interrupted.

Tester:

The issue is confirmed. Effects of Root on fade interrupting spells casting

https://user-images.githubusercontent.com/85256266/141676931-bd827829-b4e9-4fcf-9ce3-f6ab638ac5f6.mp4

### Expected Blizzlike Behaviour

Being affected by root effects should not interrupt spellcasting

### Source

Wowpedia [Root](https://wowpedia.fandom.com/wiki/Root?oldid=2291593)
> A root effect differs from a stun effect in that the target is still able to use abilities, spells or melee/ranged attacks, but cannot move from its location as long as the effect is active.

### Steps to reproduce the problem

.aura 12494 or 15474 or 64804
.cast 2060 or 64843

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/9e3332dc208215f60d62b6eef3c9e804464708da

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by laasker** [comment]
Mage Frost Nova and Druid Entangling Roots have this same problem
