### ISSUE TITLE
Omen of Clarity Not Proccing From Various Spells

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9196]
### What client do you play on?

enUS

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2265

Omen of clarity (unless i just have bad rng) does not proc of
barkskin
mark/gift of the wild
nature's grasp
feral faerie fire

Tester: confirmed for the above. Also Cyclone, Hurricane, Innervate, Tranquility, Thorns, Typhoon and Nature's Swiftness didn't proc it for me either.

See also https://github.com/azerothcore/azerothcore-wotlk/issues/4286 which deals with Maul only. 

### Expected Blizzlike Behaviour

"It causes all of your spells and auto-attacks to give a chance to grant you a Clearcasting buff, which reduces the mana, rage, or energy cost of your next damage or healing spell or offensive ability to zero. Despite what the tooltip says, virtually any spell cast can trigger the Clearcasting, including ones with no mana cost, though not all spells will benefit from it.

Essentially everything except shapeshifting can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.

Patch 3.0.2 (14-Oct-2008): Now a passive spell. Now also procs on damage and healing spells, yet no longer procs on feral abilities(only auto-attacks proc it). Proc rate is roughly 6% with a 10 second internal cooldown." ([source](https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity?oldid=2301804)) - note the 10 sec internal cd is disputed by other sources that say it has no cd, so not sure if this was removed later. 

To expand on this, OoC should proc from:
1. Successful melee attack ( white damage )
2. Successful cast positive magic spell
3. Successful damage from harmful magic spell cast - https://github.com/azerothcore/azerothcore-wotlk/issues/2133#issuecomment-515725205

So all of the spells listed in the original report should proc it.

@VFaleiro comments:
I believe anything can/should proc it, literally. From laying campfires to using profession skills. Yes, it is totally ridiculous. You can see a lot of that on Wowhead [edited to remove joke comments]

[lordkarthas on 2008/10/22 (Patch 3.0.2)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409904:reply=356110)
> It procs off crafting bandages as well.

[370776 on 2009/06/23 (Patch 3.1.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=756418)
> Other people have mentioned this can proc when doing professions.
> Omen of Clarity can also proc when switching talent sets.

[613298 on 2010/06/07 (Patch 3.3.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=1054317)
> Since the buff procs off of each application of a spell, its an almost guarantee that casting Typhoon or Gift of the Wild while in a raid will proc it. Idk about mana efficiency, but boom there goes ur Tier ten 2-piece bonus :3

[kojiroh on 2008/10/17 (Patch 3.0.2)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=409095)
> I think I might have found a bug, or a glitch with this. This spell procs for EVERY spell, including crafting spells, such as Heavy Clefthoof Boots (Spell).
> I've found that out when I crafted these. I wasn't looking at the screen at the time, and when I heard the sound of the clearcasting state activating, I've turned my eyes at the screen and seen the "<Clearcasting>" text scrolling up.
> I still wonder if it's a known-case or a bug or something.

[289894 on 2009/01/01 (Patch 3.0.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=540774)
> Hurricane has a change to proc on each tick, which make hurricane spam close to mana free in pve!

[296637 on 2009/01/17 (Patch 3.0.3)](https://www.wowhead.com/spell=16864/omen-of-clarity#comments:id=566125)
> Just had it proc today while cooking :p

[Wowwiki: Feral DPS Guide (archived in Oct/2010)](https://web.archive.org/web/20101010040647/http://www.wowwiki.com/Feral_DPS_guide)
> 6. If you have less than 35 Energy, use [Tiger's Fury] (or [Nature's Grasp] - which can proc [Omen of Clarity]).

it should proc off all these abilities 
https://www.youtube.com/watch?v=WuWOFtk6JS4&t=135s&ab_channel=ZybakTV
(at 2:02 barkskins the rogues opener and omen of clarity procs)
https://www.youtube.com/watch?v=4gyy3GSokm0&t=10s&ab_channel=Xk 
(gift of the wild pre pull to proc omen of clarity) 
https://www.youtube.com/watch?v=KFMPEECCAP0&ab_channel=KnifeOfLinoleum
another video of pre casting gift of the wild to save a proc for the fight

### Source
https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity?oldid=2301804

### Steps to reproduce the problem

use feral faerie fire on a target dummy with omen of clarity and it doesnt proc in my testing
activate barkskin and no proc
activate natures grasp and no proc
cast mark/gift of the wild and no proc

### Extra Notes

This could just be all bad rng but i dont think 5 minutes of testing on a target dummy without a single omen proc is just bad rng.  The proc rate should be roughly 6% 

See also https://github.com/SunwellTracker/issues/issues/2500 for further discussion.

Also, in comment [here](https://github.com/blackfrost-server/BlackFrost-Server/issues/16#issuecomment-650278291) a fix for this is proposed.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Never6** [comment]
Legend :D

**Comment by laasker** [comment]
for some reason its hardcoded to not proc those spells, check spell_dru_omen_of_clarity in spell_druid.cpp

i removed it to test, and clearcasting proc even from switching druid forms

**Comment by laasker** [comment]
> for some reason its hardcoded to not proc those spells, check spell_dru_omen_of_clarity in spell_druid.cpp
> 
> i removed it to test, and clearcasting proc even from switching druid forms

Ok so i think i know why someone did that

its maybe to prevent OOC from proccing too much with Improved Leader of the Pack and some consumables
https://github.com/SunwellTracker/issues/issues/2897

https://github.com/SunwellTracker/issues/issues/3459

But we can just make those spells not proc Omen of Clarity and its fine imo. 
I tested and those are the things that can be broken/make it proc too much: 

34299 Improved Leather of the Pack = feral druid party aura, when someone melee crit, they heal themselves for 4% of their HP, and this heal has a chance to proc Omen of Clarity/Clearcasting
43733 Stormchops = Cooking consumable which does AoE damage, can proc clearcasting
15851 Dragonbreath Chili = Cooking consumable which does damage occasionally, can proc clearcasting
11351 Oil of Immolation = Consumable that does fire AoE damage every 3 seconds, can proc clearcasting
28715 Flame Cap = chance to do fire damage on hit, can proc clearcasting
14795 Venomhide Poison, some mobs can enchant your weapon for 5m when you kill them, this can proc clearcasting

I tested weapons enchants and none would proc OOC (even fiery weapon didnt). 

How i tested:
Removed the PPM from OOC and increased the proc chance to 100% and removed the auto attack chance, so it only procs on spells
