### ISSUE TITLE
Core/Worldserver: Priority class dennied

### ISSUE THREAD

**Issue by cshaaa** [azerothcore/azerothcore-wotlk#92]
TC>Can't set worldserver process priority class, error: Permission denied
Starting up Auction House Listing thread...
Max allowed socket connections 65536
AzerothCore rev. 146f1476769d+ 2016-08-14 20:23:39 +0200 (master branch) (Unix, R
ease) (worldserver-daemon) ready...

Branch(es): master

AC hash/commit: 146f1476769d

Modules: no

Operating system: debian 8

**Comment by Yehonal** [comment]
You must run server with root privileges to allow process priority configuration

**Comment by HeroPD** [comment]
This error occured in docker container

**Comment by Stoabrogga** [comment]
Don't know much about docker, but on Ubuntu I had to grant permission to the user which runs AC to reduce the nice value for it's processes:
Edit ```/etc/security/limits.conf``` and add something like this (here as example for the user "ac_user"):
```
ac_user               -       nice            -15
```

**Comment by BarbzYHOOL** [comment]
Even as root, I get this message `Can't set worldserver process priority class, error: Permission denied`

**Comment by Viste** [comment]
It's just my opinion:
nice it's not a priority, but rather a recommendation to the kernel. I don't see the point in this Linux functionality at all.

**Comment by BarbzYHOOL** [comment]
doesn't help xD

**Comment by BarbzYHOOL** [comment]
Tried Stoabrogga's solution on a non-root user, same error:

```
AC>Starting up Auction House Listing thread...
Can't set worldserver process priority class, error: Permission denied
Starting up anti-freeze thread (50 seconds max stuck time)...
```

**Comment by locus313** [comment]
adding "privileged: true" to the docker-compose.yml under the ac-worldserver section can address this issue. Here is  

````
AC>Starting up Auction House Listing thread...
worldserver process priority class set to -15
Max allowed socket connections 1048576
AzerothCore rev. 5edab2eaa76f+ 2020-08-12 23:51:27 -0700 (master branch) (Unix, Release) (worldserver-daemon) ready...
```

**Comment by gengarshadowball** [comment]
Is this fixed?

**Comment by FrancescoBorzi** [comment]
@gengarshadowball  on Docker yes, not sure if it still affects the traditional setups

**Comment by locus313** [comment]
hey guys,
I was recently doing some testing on ubuntu 20.04 using the bash dashboard setup and was able to get this working:

![image](https://user-images.githubusercontent.com/4015312/109376229-0332c680-7878-11eb-9cf2-853f235d8022.png)

First I changed the ownership of the worldserver executable to root:

`sudo chown root:root env/dist/bin/worldserver`

![image](https://user-images.githubusercontent.com/4015312/109376386-f367b200-7878-11eb-9725-ca92a6490b59.png)

Then set the SUID bit on the worldserver executable:

`sudo chmod u+s env/dist/bin/worldserver`

![image](https://user-images.githubusercontent.com/4015312/109376488-a1735c00-7879-11eb-9e4d-96e607e9860b.png)


Now I can just run the bash dashboard command to setup the worldserver as a regular user:

`./acore.sh run-worldserver`

![image](https://user-images.githubusercontent.com/4015312/109376519-d8497200-7879-11eb-9f7d-647722ee6bbb.png)

Can you guys give this a try and see if it works for you as well?

**Comment by Kitzunu** [comment]
> @gengarshadowball on Docker yes, not sure if it still affects the traditional setups

If Windows is a traditional setup, then I can tell you that this is not an issue there

```
worldserver process priority class set to HIGH
Starting up Auction House Listing thread...
Max allowed socket connections 1024
AzerothCore rev. 3c786b52e9a6+ 2021-03-26 16:55:30 +0100 (master branch) (Win64, Debug) (worldserver-daemon) ready...
```
