### ISSUE TITLE
[DB/Quest] Basic Chemistry & Neutralizing the Plague cannot complete

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#9206]
### Current Behaviour

use the gameobject（Pustulant Spinal Fluid） on target( GameObject: Plague Cauldron KC Bunny) , and killed the creature summoned, it won't complete this quest. 

### Expected Blizzlike Behaviour

it should complete quest after creature killed.

### Steps to reproduce the problem

1. .q a (13279/13295)
2. .go gameobject id  193580
3. use gameobject to it
4. kill the creature summoned
5. quest not complete

### AC rev. hash/commit

d80f7d467d47+

### Operating system

Ubuntu 20.04

**Comment by IntelligentQuantum** [comment]
https://www.youtube.com/watch?v=aefkQfpxQ4c

use this item  [Pustulant Spinal Fluid] multitime

it works fine for me.
