### ISSUE TITLE
[Creature]Creature on air after killed can not fall to earth

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#9207]
### Current Behaviour

creature on air killed, and the corpse float on air, can not loot.

### Expected Blizzlike Behaviour

it should fall down to earth.

### Steps to reproduce the problem

1. .go c id 33201/29753
2. .kill
3. watch the corpse

### AC rev. hash/commit

d80f7d467d47+

### Operating system

Ubuntu 20.04

**Comment by Shineslippers** [comment]
I guess fixed

https://user-images.githubusercontent.com/85256266/148585567-24f369d3-962c-4afe-9565-be7b9fa8ab71.mp4

https://user-images.githubusercontent.com/85256266/148585704-4c8b9150-35b2-41b5-9eee-22ffcb93727a.mp4
