### ISSUE TITLE
Soap cannot start

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#9211]
### Current Behaviour

Enable SOAP in worldserver.conf and set the website's IP to start worldserver, an error will appear。

Error message:WORLD: World initialized in 0 minutes 5 seconds
 
ACSoap: couldn't bind to 172.16.0.9:7878

/home/azerothcore-wotlk/src/server/shared/Network/SocketMgr.h:35 in ~SocketMgr ASSERTION FAILED:
  !_threads && !_acceptor && !_threadCount
StopNetwork must be called prior to SocketMgr destruction

Segmentation fault (core dumped)

### Expected Blizzlike Behaviour

Start worldserver smoothly

### Steps to reproduce the problem

1.SOAP.Enabled = 1
2.SOAP.IP = "X.X.X.X"
3.Start the worldserver

### AC rev. hash/commit

https://github.com/tbcstar/azerothcore-wotlk/commit/bae48375884c6af6ce5f5c62a35795e4971b09e9

### Operating system

 Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)

### Custom changes or Modules

https://github.com/azerothcore/mod-eluna-lua-engine/commit/21a191f801017f8d13e5473ca708947a0dbe3cc3

**Comment by Michael-Reich** [comment]
What was the error?
