### ISSUE TITLE
AoE DoTs Incorrectly Interrupting Flag Capping

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9225]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1731

Mage spell Blizzard (https://wowgaming.altervista.org/aowow/?spell=10#see-also) interrupts flag capping in AB.

https://user-images.githubusercontent.com/80769357/133420832-4d5891b5-0b9d-491d-bd66-8d04419da157.mp4

Tester: Confirmed. Tried Blizzard, Rain of Fire, Starfall, Drain Life, and various dots. Blizz, Rain of Fire and Starfall all incorrectly interrupted flag capping. The other spells like Drain Life, Corruption and Curse of Agony didn't, which is fine.

https://user-images.githubusercontent.com/81782124/142201793-8237cee8-bd5b-4d38-ada7-6b7c634d209b.mp4

### Expected Blizzlike Behaviour

Blizzard like other AOE or DoTs without direct damage component (for example flamestrike intial hit interrupts, dot ticks don't) should not interrupt casting when capping/defending the flag. 

### Source
Note these sources are mostly for Classic rather than Wrath. Couldn't find Wrath sources, but also didn't see any evidence that things had changed.

>Only direct damage interrupts a flag cap. Blizzard does not count, never has. 
>Channeled spells, including Blizzard do not stop flag capping. Nor do dots. Gotta actually hit the guy with something direct. 
 (https://us.forums.blizzard.com/en/wow/t/not-stopping-flag-caps/471095/2)

>AoE casted at range has generally not interrupted flag capping. This has nothing to do with absorbs, but the fact that placing a blizzard over a flag simply doesn’t interrupt casting. (https://us.forums.blizzard.com/en/wow/t/please-stop-absorbs-from-blocking-interruption-on-flags/225014/6)

> DoTs don’t tend to interrupt flag capping unless there is a direct damage component (eg. Moonfire) and ‘drop and forget’ abilities like Rain of Fire and Blizzard also do not interrupt flag caps.
(https://us.forums.blizzard.com/en/wow/t/stopping-flags-being-capped/379911/18)

>By althras on 2006/09/13 (Patch 1.12.0) 
>However, Blizzard at any rank doesn't work for stopping flag turners in AB and AV, so don't bother. (https://tbc.wowhead.com/spell=10/blizzard#comments:id=166)

### Steps to reproduce the problem

1. Enter AB
2. Start capping a flag and have mage cast blizzard on your location
3. See it interrupts

### Extra Notes

If anyone has any info on the topic that would suggest otherwise, please do comment.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
can you give me the spellid for the flag capping?

**Comment by Azcobu** [comment]
I don't clearly understand how flag capping works so this could be totally wrong.

There's a 'Capturing' spell on TBC Wowhead here - https://tbc.wowhead.com/spell=349794/capturing - but it's not listed on WowGaming or in spell.dbc so apparently flag capping on AC works differently.

On AC it looks like the capture spell might be https://wowgaming.altervista.org/aowow/?spell=21651, along with https://wowgaming.altervista.org/aowow/?spell=24390 or https://wowgaming.altervista.org/aowow/?spell=24391, which provides the swirly visual effect.

Wowgaming does show these two spells for AB, but they seem to be for after the flag is capped:
neutral -> Horde: https://wowgaming.altervista.org/aowow/?spell=32439
neutral > Alliance: https://wowgaming.altervista.org/aowow/?spell=32440

But like I said, this is mostly guesswork and could be completely wrong.
