### ISSUE TITLE
NPCs falling through the ground

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/azerothcore-wotlk#923]
**Description**:
Sometimes NPCs fall through the ground while attacking.

**Current behaviour**:
When attacking NPCs which are moving over a hill, they sometimes fall through the ground and attack you from below.

**Expected behaviour**:
The NPCs should just run/walk normally above the ground.

**Steps to reproduce the problem**:
Example:
Teleport to the following location:
`.go xyz -3067.45 -4308.53 0.300854 1`
Attack the Defias Rummager on the other side of the small hill and pull him on top of the hill. He will fall through the ground.

I don't know if it is related, but sometimes NPCs with waypoint or random movement "float" or "hop" to their destination when running up or down a hill.

**Branch(es)**: master

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/8481eec5beac5a2e65052f95a6ff6aa22c5db981

**Operating system**: Ubuntu 16.04

**Modules**:
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster
https://github.com/azerothcore/mod-vas-autobalance

**Other Customizations**: none

**Comment by BarbzYHOOL** [comment]
Same happens with your pet, it's for all mobs. It's probably a mmap problem

**Comment by Nefertumm** [comment]
This maybe is related with #862.

**Comment by FALL1N1** [comment]
bad mmaps, edges aren't calculated properly, you can see with .mmap path that the path is ok-ish till it reaches edges or road bumps like rocks, fences etc

**Comment by FALL1N1** [comment]
Alright, so i did some testing and with stock trinity mmaps everything looks ok. http://prntscr.com/jugb3s

https://mega.nz/#!28ZEkI5Q!x4wIJ9Z4G63g098H9kcDzfuBWcC-sbe030hhlaowJnc try with these mmaps (this contains just the small isle of STV, not the entire game), test and let me know if it works

**Comment by Stoabrogga** [comment]
I tried to identify the essential changes Trinitycore did to the tools and aggregated them into PR #926.
