### ISSUE TITLE
New core compilation error

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/azerothcore-wotlk#9239]
### Current Behaviour

[<script src="https://gist.github.com/yuanf225/a3f2b30fd65ee3562354e44df24efdcb.js"></script>](https://gist.github.com/yuanf225/a3f2b30fd65ee3562354e44df24efdcb)

### Expected Blizzlike Behaviour

By compiling

### Steps to reproduce the problem

1.cmake ../ -DCMAKE_INSTALL_PREFIX=/home/server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DWITH_WARNINGS=1 -DTOOLS=1 -DSCRIPTS=static
2.make -j 8

### AC rev. hash/commit

https://github.com/tbcstar/azerothcore-wotlk/commit/b7b4dcab3ef4130253b67a1f1f3c82fb0dd241eb

### Operating system

 Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-77-generic x86_64)

### Custom changes or Modules

Eluna module

**Comment by Winfidonarleyan** [comment]
Please read wiki before create issue
