### ISSUE TITLE
Missing spanish translations (esES, esMX) for Orgrimmar auctioneers. (FIX INCLUDED IN THE TICKET)

### ISSUE THREAD

**Issue by quilumipe2** [azerothcore/azerothcore-wotlk#9240]
### Current Behaviour

There's only german translations por NPCs wntries = 9856, 8673 and 8724

### Expected Blizzlike Behaviour

They should be named in spanish when connecting from a Spanish WOW Client.

I've fixed it (SQL script included down below) but I have 0 clue of how to make a pull request, if someone can tell me how to do it or do it for me I would appreciate it. Thank you!

### Source

DELETE FROM `creature_template_locale` WHERE entry = 8673 AND locale = 'esES';
INSERT INTO `creature_template_locale` (entry, locale, NAME, Title, VerifiedBuild) VALUES (8673, 'esES', 'Subastador Thathung', '', 18019);
DELETE FROM `creature_template_locale` WHERE entry = 8673 AND locale = 'esMX';
INSERT INTO `creature_template_locale` (entry, locale, NAME, Title, VerifiedBuild) VALUES (8673, 'esMX', 'Subastador Thathung', '', 18019);

DELETE FROM `creature_template_locale` WHERE entry = 9856 AND locale = 'esES';
INSERT INTO `creature_template_locale` (entry, locale, NAME, Title, VerifiedBuild) VALUES (9856, 'esES', 'Subastador Grimful', '', 18019);
DELETE FROM `creature_template_locale` WHERE entry = 9856 AND locale = 'esMX';
INSERT INTO `creature_template_locale` (entry, locale, NAME, Title, VerifiedBuild) VALUES (9856, 'esMX', 'Subastador Grimful', '', 18019);

DELETE FROM `creature_template_locale` WHERE entry = 8724 AND locale = 'esES';
INSERT INTO `creature_template_locale` (entry, locale, NAME, Title, VerifiedBuild) VALUES (8724, 'esES', 'Subastador Wabang', '', 18019);
DELETE FROM `creature_template_locale` WHERE entry = 8724 AND locale = 'esMX';
INSERT INTO `creature_template_locale` (entry, locale, NAME, Title, VerifiedBuild) VALUES (8724, 'esMX', 'Subastador Wabang', '', 18019);

### Steps to reproduce the problem

Step 1: Connect to AzerothCore using a Spanish WoW client.
Step 2: go to Orgrimmar auction house.
Step 3: Read the NPC names. (Very obvious I know)

### AC rev. hash/commit

I don't know for sure, but the core was compiled being the last commit made to the repository: 2bcd78041eef081c1a60b929af88b3f3d94665c5

### Operating system

Linux Ubuntu Server 20.04

**Comment by patou01** [comment]
To create a PR, you can follow the guide here https://www.azerothcore.org/wiki/how-to-create-a-db-pr , but I've made this one for you (hopefully without messing up,  as I refactored a bit). 
Feel free to make others if you come across issues for other places!

**Comment by quilumipe2** [comment]
thanks a lot! I will follow the guide and send some fixes for wrong translations I've found.

**Comment by patou01** [comment]
We also normally only close an issue once the corresponding pull request has been merged into master, else in case it doesn't get merged we risk losing the issue :)

**Comment by quilumipe2** [comment]
Didn't know that, thakyou again :D
