### ISSUE TITLE
NPC's buffs doesn't follow player's buffs rules

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9249]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2353

Each time you return to Shadow Priestess Vandis at The Bulwark in Tirisfal after completing a cauldron quest in Western Plaguelands, Shadow Priestess Vandis buffs you with Power Word: Fortitude after completing any of the "Return to the Bulwark" quests.
If you have buffed yourself with Power Word: Fortitude, you get a second Power Word: Fortitude buff after completing the quests.
![WoWScrnShot_111821_100452](https://user-images.githubusercontent.com/62797536/142470283-40b17f06-5f66-4f44-af99-e91bffe6a8c2.jpg)

Tester:

The issue is confirmed. NPC's buffs doesn't follow player's buffs rules

![image](https://user-images.githubusercontent.com/85256266/142493494-171b110a-f6e5-49ce-b137-e73b24931cc4.png)

### Expected Blizzlike Behaviour

Buffs of NPCs should follow same rules as player's buffs:
- One `family` buff
- Most powerful buff should stay or apply

### Source

Wowwiki [Buffs](https://wowwiki-archive.fandom.com/wiki/Buff?oldid=2289875)
> Most buffs do not stack with other similar buffs. One prominent exception is heal over time spells

> For the most part, what this change means is that many buffs and debuffs that were previously allowed to stack together no longer can

### Steps to reproduce the problem

.cast 23947 - npc's buff
.cast 23948 - npc's buff
.cast 10937 - player's buff
.cast 10938 - player's buff

.cast 16878 - npc's buff
.cast 24752 - npc's buff 
.cast 39233 - npc's buff
.cast 9885 - player's buff
.cast 26990 - player's buff

### Extra Notes

Shadow Priestess Vandis: https://wowgaming.altervista.org/aowow/?npc=11055

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Nyeriah** [comment]
I'm not entirely sure about this. Those are not player spells, there's nothing that implies player spells shouldn't stack with npc spells, they're completelly different

**Comment by T1ti** [comment]
She litterally casts the same spell as the one player priests have https://tbc.wowhead.com/spell=23947/power-word-fortitude

**Comment by Shineslippers** [comment]
That's the point. It's not about unranked spells

**Comment by UltraNix** [comment]
Guys - I need a proff from retail. It does no matter if it is the same spell, but who is the caster.

**Comment by Shineslippers** [comment]
I found this video. Player have some sort of Stamina buf and complete of quest doesn't apply second or refresh current
https://youtu.be/X6xCkI4psTk?t=2332
