### ISSUE TITLE
Archmage Arugal missing Arugal's Curse spell

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9251]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Archmage Arugal](https://wowgaming.altervista.org/aowow/?npc=4275) from [Shadowfang Keep](https://wowgaming.altervista.org/aowow/?zone=209) doesn't cast [Arugal's Curse](https://wowgaming.altervista.org/aowow/?spell=7621)

| CreatureID | Index | Spell | VerifiedBuild | 
| ---: | ---: | ---: | ---: | 
| 4275 | 0 | 22709 | 12340 | 
| 4275 | 1 | 7803 | 12340 | 

### Expected Blizzlike Behaviour

Archmage Arugal should cast this spell. He even have it in SAI

### Source

Wowhead Archmage Arugal
> By Bose on 2009/10/01 (Patch 3.2.2)
Just soloed him as a lvl 26-27 pally (dinged 27 midway through the instance) in full Heirloom gear. Doable, but only with a bit of luck. His MC missed 3 times in a row and even then I still ended the fight at about 300 health.

>By 390201 on 2009/08/24 (Patch 3.2.0)
We managed to clear most of the instance with no problem. Arugal though, was a completely different ballgame. After getting him down to about 75% hp he mc'd me, and I killed the 17 priest almost immediately. Since I was mc'd, I no longer had aggro, so he targeted the rogue after he teleported and made short work of him. After that, I managed to grab aggro and got him down to 50% hp. He mc'd me again, but luckily the 22 priest shielded and took off running. This happened 3 more times before we finally managed to kill him. My mana was gone, and my hp was almost gone as well, so it was a very close fight.

### Steps to reproduce the problem

```sql
SELECT *
FROM creature_template_spell
WHERE creatureid LIKE '%4275%'
```

### Extra Notes

2 month ago this spell was there

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/03c84db04dd7bce2a8aa5e527aeec2640c6fa7eb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
rev. 0b308b1a7f5f2e68e44214a9a73ce58a5e03ab3f

Spell is there and it works.
<details>

![ee9044475574ae39d3eab564b0c021be](https://user-images.githubusercontent.com/46330494/222979309-1464e9cb-6b94-4210-b27d-49916cc8df91.jpg)

</details>

**Comment by elthehablo** [comment]
looks like resolved to me then?
