### ISSUE TITLE
acore_characters.updates.state enum missing type of module

### ISSUE THREAD

**Issue by overflowz** [azerothcore/azerothcore-wotlk#9257]
### Current Behaviour

when the worldserver is starting, in the console I see this log:
```
[1265] Data truncated for column 'state' at row 1
Unhandled MySQL errno 1265. Unexpected behaviour possible.
```

while debugging, I realized it was because `acore_characters.updates.state` column had value of ENUM (with values RELEASED, ARCHIEVED, CUSTOM).

after changing it to a string, I found out that it was trying to set state as `module` (screenshot attached).
![image](https://user-images.githubusercontent.com/7758774/142722199-bccf112b-1673-4b8e-8bda-b31855609f6d.png)

### Expected Blizzlike Behaviour

It should update sql properly without errors.

### Steps to reproduce the problem

1. add mod-transmog module
2. build
3. acore.sh docker start:app

### AC rev. hash/commit

AzerothCore rev. e747716230ef

### Operating system

Windows 10, WSL2 with Docker

### Custom changes or Modules

mod-transmog

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/70d8b88f3be6da17fe65e34c19e6e8ac8977a3d4
