### ISSUE TITLE
Camera not always adjusted to the same height on mount up

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9261]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/593

When activating the native draenei mount there are times when the pitch of the camera does not adjust as it should, leaving it at the center and not a little higher as it normally does.

Tester:

The issue is confirmed. Camera not always adjusted to the same height.

https://user-images.githubusercontent.com/85256266/142731639-f69f6afa-217a-443e-bbbc-8502cc44a66b.mp4

### Expected Blizzlike Behaviour

It should just always work as expected.

### Source

https://github.com/azerothcore/azerothcore-wotlk/issues/2207#issuecomment-907773747

### Steps to reproduce the problem

.setskill 762 300
.additem 18789
while mounting press mount again 

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Also there is similar to it, but i can't confirm. https://github.com/chromiecraft/chromiecraft/issues/1002

**Comment by T1ti** [comment]
This seems like a client issue, I don't think server side changes player camera

**Comment by Shineslippers** [comment]
Once again @UltraNix https://github.com/azerothcore/azerothcore-wotlk/issues/2207#issuecomment-907773747
> The one you linked might be indeed related to server, because there should be SMSG_COLLISION_HEIGHT packet send.
There are only three cases when this packet is sent: mounting up, changing scale and shapeshifts. The rest are clientside.

**Comment by UltraNix** [comment]
Nothing's changed. It is as I said - Clientside.

**Comment by Mitradis** [comment]
not client. Stop responding like this all the time. It's not funny anymore.

**Comment by UltraNix** [comment]
Totally clientside.

**Comment by Unkn87** [comment]
its not clientside. See Cmangos server. He have fix for this.

**Comment by Unkn87** [comment]
need reopen.
