### ISSUE TITLE
Server Crash Pit of Saron 

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/azerothcore-wotlk#9269]
### Current Behaviour

Pit of Saron Tunnel event produces server Crash

![pot](https://user-images.githubusercontent.com/76571216/142760674-cd71331b-034a-42b8-965e-f15a4e3d8aae.jpg)

Crashlog is Empty 

![Zwischenablage01222](https://user-images.githubusercontent.com/76571216/142760422-0297cd0e-7d06-4f83-bb70-7855183a294f.gif)

### Expected Blizzlike Behaviour

When starting an event, the server should not crash

### Steps to reproduce the problem

1. Go to Pit of Saron https://wotlkdb.com/?zone=4813
2. Enters Tunnel

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/efe999309a4a0bb1716c54c2393974352d76c0ad

### Operating system

Windows 10 x64, Ubuntu 20

### Custom changes or Modules

AC Clean with Eluna

**Comment by Shineslippers** [comment]
Well, it's not the event itself. nothing on clean AC.

![image](https://user-images.githubusercontent.com/85256266/142759981-e7bd8298-b59a-4edc-a3fc-4403e7806b70.png)

**Comment by Meramaf** [comment]
> Well, it's not the event itself. Nothing on clean AC.
> 
> ![image](https://user-images.githubusercontent.com/85256266/142759981-e7bd8298-b59a-4edc-a3fc-4403e7806b70.png)

Hm... have you tested this in heroic mode?

**Comment by Shineslippers** [comment]
I have issue with script start, but no crashes with or without event.
![image](https://user-images.githubusercontent.com/85256266/142760877-9fdda51e-2036-4e27-a842-6dc7fef4b38b.png)

**Comment by Meramaf** [comment]
![image](https://user-images.githubusercontent.com/76571216/142760927-12c036e8-d8a5-4a89-b87e-b1ce49b60fab.png)
here ist AzerothCore Clean without Module and Custom and Clean Database.

**Comment by Shineslippers** [comment]
Now i see
![image](https://user-images.githubusercontent.com/85256266/142762834-6d613d2a-b573-4783-88a4-dd1b87b0f9fb.png)

**Comment by acidmanifesto** [comment]
@Shineslippers can you provide a .gps for us please?

**Comment by acidmanifesto** [comment]
actually. i just had it crash in the same spot. i thought i had debugger attached but i did now. im going to reattach it and see what we got.

**Comment by Shineslippers** [comment]
No crash wiouth event. Just checked it again.
![WoWScrnShot_112121_205754](https://user-images.githubusercontent.com/85256266/142773521-6b9931ac-6849-49ea-97e8-32886a1faf99.jpg)

**Comment by acidmanifesto** [comment]
im trying to reproduce it. so far i only got it to crash once. and it gave me a message of signal 22. which i have zero idea what that means. so i am trying to reproduce it

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/142774071-b4d645b7-e963-42d7-b5fb-d73ac5e1df39.png)
Caught the crash in debugger. looking into it now

**Comment by acidmanifesto** [comment]
creature script npc_pos_tyrannus_events
Somewhere after https://github.com/azerothcore/azerothcore-wotlk/blob/61c7488698d45b3a24d65acce822a7e9580edb49/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp#L664

The issue is, i can NOT get this to trigger consistently.

**Comment by acidmanifesto** [comment]
ok. disregard what i said above, turns out its the icicle spells.

https://github.com/azerothcore/azerothcore-wotlk/blob/61c7488698d45b3a24d65acce822a7e9580edb49/src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp#L886

I was not able to get a crash when i commit out the whole void UpdateAI. everything points to that. But how to correct it i am not entirely certain.

So in debugger i got the error of it saying there was a spell focus being casted by a guid 0 summon, with a target that returned NULL.

**Comment by acidmanifesto** [comment]
ok. so further investigation. removing or commiting out this https://github.com/azerothcore/azerothcore-wotlk/commit/efe999309a4a0bb1716c54c2393974352d76c0ad fixes the issues.

**Comment by UltraNix** [comment]
@acidmanifesto Just post the crashlog.

**Comment by acidmanifesto** [comment]
> @acidmanifesto Just post the crashlog.

thats the unqiue thing. got zero crash logs as the person earlier stated.

**Comment by UltraNix** [comment]
So show me the Call Stack in debugger

**Comment by acidmanifesto** [comment]
will have to do that later on when i am back home, i literally just left a few minutes ago. but if u have time you can easily run thru it and get it replicated, just gotta pretty much just stand in the tunnel of the instance with the icicles falling and it will crash same spot i posted earlier.

**Comment by acidmanifesto** [comment]
https://www.mediafire.com/file/zzvky1iagyuixme/worldserverPitOfSoran2.dmp/file
I got the dmp with heap uploading remotely for now. should be availble in like 10 or 15 minutes.

**Comment by Vearodev** [comment]
I confirm. The bug is present, occurs in the cave of the Pit of Saron.
