### ISSUE TITLE
Absorb Shields Stopping Interrupts While Flag Capping

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9270]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1726

Absorbed damage doesn't stop flag capping in Arathi Basin (PVP)

Tester: Confirmed. Tested with priest and mage absorb shields with a warr hitting both, and neither was interrupted by the attacks.

https://user-images.githubusercontent.com/81782124/142760394-f6d218ad-c73d-45a6-bdda-98820188d5a6.mp4

Reported by Trinity as well: https://github.com/TrinityCore/TrinityCore/issues/6222 - a fix is also described there.

### Expected Blizzlike Behaviour

Taking direct damage, even if absorbed by a priest shield for example, should stop capping a flag.
It makes priest very strong at capping...

### Source

>By Lodum on 2010/04/25 at 9:41 AM (Patch 3.3.3) 
Even while shielded, they still get interrupted when dealing with the flag, afaik. At least, I always seem to. - - https://www.wowhead.com/forums/topic/disc-priest-pvp-how-to-interrupt-a-flag-capper-153563#p2008269

From the same thread (since deleted so needed to use an old screenshot):

![76090136-52268280-5fbb-11ea-9c01-fe854a752c15](https://user-images.githubusercontent.com/81782124/142759702-eea7088e-4e92-48f5-9722-95bea9e2b1c8.png)

https://youtu.be/ZYb5SVo4dz0?t=75 

### Steps to reproduce the problem

Enter Arathi, pop a shield of some kind, and attempt to cap a flag while a second player applies direct (not DoT) damage. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Algorak** [comment]
Class CC are not interrupted when absorbing. Rogue stuns etc
