### ISSUE TITLE
Halls of Reflection: Lich King freezes after Event start

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/azerothcore-wotlk#9286]
### Current Behaviour

Lich king stops after Escape event start. 

![image](https://user-images.githubusercontent.com/76571216/142916158-967347aa-ac13-47e2-abc9-78bad82639d2.png)

VIDEO HERE: https://youtu.be/8qRl8qyIf58

### Expected Blizzlike Behaviour

https://www.youtube.com/watch?v=izx-lkkSKA4

### Steps to reproduce the problem

1. Go to Halls of Reflection https://wotlkdb.com/?zone=4820
2. Reach last phase

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4099c380726b04761f345c8561fb14a0c5626b59

AzerothCore rev. d302b4abd531 2021-11-22 16:14:26 +0100 (main branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1h  22 Sep 2020 (library: OpenSSL 1.1.1h  22 Sep 2020)
Using Boost version: 1.74.0
Using MySQL version: 50731
Using CMake version: 3.22.0-rc3
Compiled on: Windows 10.0.19043
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/Release/data/maps. Total size: 252191207 bytes
vmaps directory located in C:/Release/data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/Release/data/mmaps. Total size: 2196365032 bytes
Using deDE DBC Locale as default. All available DBC locales: deDE
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_11_22_01
Using Character DB Revision: 2021_10_14_00
Using Auth DB Revision: 2021_10_14_00

### Operating system

Windows 10 x64, Ubuntu 20.04

### Custom changes or Modules

AutoBalance
SoloLFG
Custom Race

**Comment by Vearodev** [comment]
i confirm

**Comment by acidmanifesto** [comment]
Can we get a .gps of the location or guid of the lich king so i can look at it more quickly? Also a .npc info to identify a npc scriptname if possible/available?

**Comment by Meramaf** [comment]
@acidmanifesto 
Npc Info Lich King:
![image](https://user-images.githubusercontent.com/76571216/142972450-9c0b95d8-7871-4c95-b326-e5921a89ec19.png)
GPS:
![image](https://user-images.githubusercontent.com/76571216/142972513-950dbe95-e14c-4440-922b-922e1413da89.png)

**Comment by acidmanifesto** [comment]
@Meramaf now is that the .npc info for the exact lich king that is not moving?
We actually have a few ai's of the lich king in this case.
Can u please confirm its the same npc info for the one that "freezes" because i suspect a case, but its not the lich king script you ss.

**Comment by Meramaf** [comment]
@acidmanifesto yes this is correct npc Info from lk in hor. 

https://github.com/azerothcore/azerothcore-wotlk/blob/a0002afe07363c8ae4b4cb0bd4d79fb748df85f9/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp#L1488

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/a0002afe07363c8ae4b4cb0bd4d79fb748df85f9/src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp#L1489
Stops moving until 255 kills are met? is this correct? or am i misreading this?

**Comment by Meramaf** [comment]
i set reqKillCount to 15 and its dont work....=(

**Comment by Meramaf** [comment]
Broke after this commit https://github.com/azerothcore/azerothcore-wotlk/pull/9180/commits/48746726a84af8fda85b0b03f47e0e165f935b00

**Comment by Kitzunu** [comment]
is it still broken?

**Comment by acidmanifesto** [comment]
> Broke after this commit https://github.com/azerothcore/azerothcore-wotlk/pull/9180/commits/48746726a84af8fda85b0b03f47e0e165f935b00 @acidmanifesto 

Which part of the commit broke the script? This issue was reported before that commit was even merged.

**Comment by Meramaf** [comment]
> > Broke after this commit [4874672](https://github.com/azerothcore/azerothcore-wotlk/commit/48746726a84af8fda85b0b03f47e0e165f935b00) @acidmanifesto
> 
> Which part of the commit broke the script? This issue was reported before that commit was even merged.

sorry for wrong commit. I have found the right one and tested it https://github.com/azerothcore/azerothcore-wotlk/commit/70fbaefa8eaaa2a100eb1c3ce9b7ed3cc62baf99# @UltraNix whithout this, work movement from LK correctly
