### ISSUE TITLE
Feature: Item restoration

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#9289]
### Describe your feature request or suggestion in detail

Currently, there is no way (except loading a database backup) to find accidentally deleted/sold items.

### Describe a possible solution to your feature or suggestion in detail

The core should keep entries in `item_instance` with an empty `owner_guid` on sale/deletion. This does require a new column similar to the `deleteInfos_Account` in `characters`

There should be a config flag for
- the min quality to keep an item (default rare/blue)
- the duration to keep them

There should be a GM command (default level 3) to restore an item by its guid.

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L3079 ?

**Comment by 55Honey** [comment]
Thanks for the pointer!
What about the restoration part? Is It manual currently?

**Comment by Nyeriah** [comment]
Closed in: https://github.com/azerothcore/azerothcore-wotlk/pull/9538
