### ISSUE TITLE
Pet falls through the wall and pulls mobs

### ISSUE THREAD

**Issue by overflowz** [azerothcore/azerothcore-wotlk#9290]
### Current Behaviour

When you climb a mountain(s), the pet falls down and pulls every mob on its way.

I captured video (gif) but was too large, I uploaded it here instead and you can check it out: https://gofile.io/d/Z8EkHz

### Expected Blizzlike Behaviour

Ideally, pets should not go through the walls at all, at least should not fall down.

### Steps to reproduce the problem

1. Go to Hinterlands
2. Find "Skull Rock"
3. Summon your pet
4. Climb from behind (where two white mushrooms are)
5. Your pet will fall down and pull all the mobs underground.

### AC rev. hash/commit

AzerothCore rev. 3aec503ab41f

### Operating system

Windows 10, WSL2 with Docker

### Custom changes or Modules

mod-transmog

**Comment by Shineslippers** [comment]
I guess it's the same as https://github.com/azerothcore/azerothcore-wotlk/issues/9254
