### ISSUE TITLE
Not work quest id 11543

### ISSUE THREAD

**Issue by Chrisjiajun** [azerothcore/azerothcore-wotlk#93]
Description: Quest:Keeping the Enemy at Bay
Error condition:item no burning ship

**Comment by ShinDarth** [comment]
please read: https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue

your revision is missing

**Comment by Chrisjiajun** [comment]
AzerothCore rev.  f81ec2b
