### ISSUE TITLE
Unable to skinning NPCs while quest items in bank

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9318]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1923

Quest: Apes of Un'Goro is complete, the hides are in the bank for turn in when next bracket releases.
Clearing the gorilla caves of Un'Goro Gorillas for leather and thorium ore.
Found that dead apes show skinnable but say "Creature must be looted first" when skinning attempted.
confirmed on multiple mobs that there was no loot, not even quest items.
Suspected it was related to the quest
Abandoned quest (thereby deleting the hides in the bank) and the apes are immediately skinnable again.

Tester:

The issue is confirmed. When you have items in your bank you can not use [skinning](https://wowgaming.altervista.org/aowow/?spell=8613)

https://user-images.githubusercontent.com/85256266/143294105-c6120ff8-d974-40bc-92f5-25b77f1f5502.mp4

### Expected Blizzlike Behaviour

When quest is completed it should not prevent from skinning

### Steps to reproduce the problem

.q a 4289
.q c 4289
.char check bank
move  quest items to bank
.go c 24064
.setskill 393 300
.additem 7005
.cast 8613

### Extra Notes

I did check for [mining](https://wowgaming.altervista.org/aowow/?spell=2575)/[gathering](https://wowgaming.altervista.org/aowow/?spell=2366) and it's ok for me, but anyway need to double check it from dev side.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6442#issuecomment-910994500

**Comment by Shineslippers** [comment]
@UltraNix why same rule doesn't work for mining or herbalism?

**Comment by UltraNix** [comment]
@Shineslippers Check that mob and it is the same as skinning mobs - can't gather herbs.

**Comment by Shineslippers** [comment]
@UltraNix If you're killing it without combat it doesn't allow you to gather it, but kill with combat broke the rule.

https://user-images.githubusercontent.com/85256266/145082111-cf7cf8e0-b34e-4aef-8896-825836dc5069.mp4

**Comment by UltraNix** [comment]
Nope - it does not matter if it was in combat before. Just tested on my local and works both ways the same.
