### ISSUE TITLE
New character unable to move

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#9321]
### Current Behaviour

It's the second time I've created a new character for testing purposes and I'm unable to move. When I checked the server there's this message;

`Player Aveia requests non-existing seer GUID Full: 0xf1300000010006f6 Type: Creature Entry: 1  Low: 1782`

### Expected Blizzlike Behaviour

Movement allowed.

### Steps to reproduce the problem

Can't reproduce every single time but it happens.

### AC rev. hash/commit

140374e3e0e83cb5f254df631ff50d7e215b3da3

### Operating system

Windows 10

**Comment by Meltie2013** [comment]
This seems to be from canceling cinematic at characters' first login. Not sure if that is the case.

Here are some references
https://github.com/TrinityCore/TrinityCore/commit/1417f624537f2bf7a57dd8762332d0b684727aa1
https://github.com/TrinityCore/TrinityCore/commit/1e2d55acf0c10fd9dd83e3cd075466702ba733db

**Comment by claudiodfc** [comment]
I did cancel the cinematic @Meltie2013

**Comment by Nyeriah** [comment]
I can confirm that this happens if you cancel the cinematic.

**Comment by acidmanifesto** [comment]
We had this issue on several private projects. The reason being with the stuck animation is something dealing with the first stance of the player model being set as the default before the world fully loads durning new creation cinematics. We did a delay of a couple seconds forcing a "emote" to play. This is also visible on blizzard retail, namly the remade cata + undead zone where at times you will see you newly created undead in deathkneel stand before going to lay down in rigior mortis state for the first quest.

**Comment by claudiodfc** [comment]
@acidmanifesto very interesting take on the subject. We should implement this aswell!

**Comment by UltraNix** [comment]
I can't reproduce it.

**Comment by Nyeriah** [comment]
> I can't reproduce it.

Did you cancel the cinematics? It shows an error on console, "tried to attach to unknown seer" or something.

**Comment by Kitzunu** [comment]
I cant either

**Comment by TheLegendaryKingdom** [comment]
What is different here bitween manually cancelling the cinematic and skipping the cinematic in worldserver.conf ? I disabled cinematics on my server to make dev easier, and had never encounter this issue without cinematics playing.

I tried enabling it again and created a few toons, manually cancelling cinematics at creation each time: none of them had this issue.
Seems a bit random.

**Comment by UltraNix** [comment]
> > I can't reproduce it.
> 
> Did you cancel the cinematics? It shows an error on console, "tried to attach to unknown seer" or something.

Yes, I did cancel. No error in console.

**Comment by Nyeriah** [comment]
Just tried a blood elf and after canceling the cinematics I can't move
![Skärmbild 2021-12-07 175626](https://user-images.githubusercontent.com/47818697/145104979-3e0f0974-a3a4-4f9a-acff-0abb13c21b50.jpg)

**Comment by acidmanifesto** [comment]
> Just tried a blood elf and after canceling the cinematics I can't move ![Skärmbild 2021-12-07 175626](https://user-images.githubusercontent.com/47818697/145104979-3e0f0974-a3a4-4f9a-acff-0abb13c21b50.jpg)

what class?

**Comment by acidmanifesto** [comment]
I have a adjustment i testing out and got no issue. was this for all new players or just select ones?
![image](https://user-images.githubusercontent.com/16887899/145110517-e0194a6f-5e85-4bb1-90fb-38ad84e6bd3c.png)

**Comment by Shineslippers** [comment]
Don't think it's related for class or race. I'm seeing this issue almost every day here and there.

**Comment by Shineslippers** [comment]
No resolved.Got twice today. AzerothCore rev. 4a36897873ae 2022-01-01 02:28:21
