### ISSUE TITLE
Lieutenant's insigna drop rate is 100%

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#9326]
### Current Behaviour

Lieutenant's insigna drop rate is 100%

### Expected Blizzlike Behaviour

Creature | Chance %
--- | ---
Burning Blade Apprentice | 10 | 
Burning Blade Fanatic | 5 |  

### Source

https://classic.wowhead.com/item=14544/lieutenants-insignia

### Steps to reproduce the problem

.q a 5727
.go c id 3197
kill and loot quest item

### AC rev. hash/commit

60d90aee3da4

### Operating system

Windows 10

**Comment by Shineslippers** [comment]
It shows for me on local AC

| entry | name | Item | chance | 
| ---: | --- | ---: | ---: | 
| 3197 | Burning Blade Fanatic | 14544 | 20 | 
| 3198 | Burning Blade Apprentice | 14544 | 20 |

**Comment by claudiodfc** [comment]
On Chromie I got it the first kill, so I'm assuming it's 100%. Didn't check on AC.

**Comment by acidmanifesto** [comment]
Quest items is not 100% drop rate at all for everything. Wowhead uses a form of data mining thru addons to gather it's rates which gets diluted thru private server play with inaccuracies. The only way to get a garuntee loot drop rate is looting 1k to 10k from the game object or creature npc in a single session as determined thru our internal sniff collective on tc and the guide I put up as well [Here](https://dev.trinitycore.info/en/install/Sniffs). Although WoWhead provides a good basis to work with, it is never ideal to accept it fully as fact. If we believed full statics from mining then we will would have to adjust strider meat to be obtained from mining copper ore,[Here]( https://www.wowhead.com/item=5469/strider-meat#mined-from-object/)

**Comment by claudiodfc** [comment]
I'll check vmangos later

**Comment by claudiodfc** [comment]
On vmangos the chance is also at 20% so I'll close the issue here since It's working as expected.
