### ISSUE TITLE
[MC] Lava Surger: Surge not working correctly

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9329]
### Current Behaviour

Surge targets a random target in range

### Expected Blizzlike Behaviour

Surge should target the furthest target on its threat list 

Clarifying : he should target the furthest player by distance that has threat, not the lowest threat.

### Source

https://www.youtube.com/watch?v=gFyl6G-PoUM
https://wowpedia.fandom.com/wiki/Lava_Surger

### Steps to reproduce the problem

1. go to MC
2. Have multiple chars
3. Engage a surger
4. all spread out
5. all damage him
5. he should target the furthest threat list target, but he doesn't.

### AC rev. hash/commit

3b1b80cbaae3

### Operating system

Unix

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by T1ti** [comment]
Your wording is pretty unclear.
Clarifying : he should target the furthest player by distance that has threat, not the lowest threat.

**Comment by temperrr** [comment]
> Your wording is pretty unclear. Clarifying : he should target the furthest player by distance that has threat, not the lowest threat.

Thanks for this clarification, I added it.
