### ISSUE TITLE
[MC] Golemagg adds not linked to Golemagg

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9330]
### Current Behaviour

You can pull golemagg without its adds.
Pulling 1 add will pull the other add

### Expected Blizzlike Behaviour

If you pull golemagg, the adds should pull, too

### Source

https://youtu.be/yIcn2AOox5o?t=159

### Steps to reproduce the problem

1. go to MC
2. pull golemagg
3. notice adds not engaging

### AC rev. hash/commit

3b1b80cbaae3

### Operating system

Unix

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Nyeriah** [comment]
@Nefertumm this is a regression from https://github.com/azerothcore/azerothcore-wotlk/commit/2eb422885e476531296cc486399e13ffb5a3c155

Please take a look into this when you have the time

**Comment by Nefertumm** [comment]
@Nyeriah yeah, my bad. I thought it already had creature_formations that could handle this.

**Comment by Nyeriah** [comment]
I think the formations can do the exact same thing that piece of code does, so it might be worth checking. However, also check that if you can't single out the adds when pulling them (hunter fd pull f.e)

**Comment by Nefertumm** [comment]
https://user-images.githubusercontent.com/19627365/143611693-56c0832b-782f-4d95-a216-3ff7ad40b73f.mp4

I can't reproduce it on 625b392ffe530e261242ba8c0675f5caf221a718

**Comment by Nefertumm** [comment]
Oops, I found another bug. Nevermind, I'm restoring the old code 🤣
