### ISSUE TITLE
[MC] MC Formation Issues

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9333]
### Current Behaviour

Any Boss group in formation with adds (for instance Gehennas, Majordomo, Sulfurun Harbinger etc) can be broken when people start to die. sometimes the adds just return back to spawn location, leaving the boss (and sometimes other adds) still engaged.

### Expected Blizzlike Behaviour

I'm not 100% certain, but I feel like whenever you are engaging such a boss, the adds should be kept engaged.  Further research maybe required.

### Steps to reproduce the problem

1. go to MC
2. Have multiple chars
3. Engage any of the bosses with adds (For instance Gehennas)
4. Start wiping after a while,
5. sometimes adds return back to original location, sometimes they dont.

### AC rev. hash/commit

3b1b80cbaae3

### Operating system

Unix

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Hacki95** [comment]
Isn't this most likely a generic issue with formations? I am also pretty sure the adds should keep engaged. 

@T1ti do you have any info per chance?

**Comment by Nyeriah** [comment]
I had the idea of implementing a combat-pulse formation flag to keep all members engaged, just no idea if that's a blizzlike behavior, haven't tested it myself

**Comment by Hacki95** [comment]
> I had the idea of implementing a combat-pulse formation flag to keep all members engaged, just no idea if that's a blizzlike behavior, haven't tested it myself

There is a mechanic where NPCs which are pulled together get linked in a chain, but I am not 100% sure how this mechanic works. I read a bunch about it a while ago though.

Maybe I can find the information again somewhere.

**Comment by 55Honey** [comment]
Wouldn't it be possible to just add 1 point of threat to any and all players in the map for all NPCs starting combat in a raid/dungeon?

**Comment by Nyeriah** [comment]
I make https://github.com/azerothcore/azerothcore-wotlk/pull/9649 should fix, need test
