### ISSUE TITLE
Culling of Stratholme - Accepting Dispelling Illusions does not show crate dispel progress.

### ISSUE THREAD

**Issue by avarishd** [azerothcore/azerothcore-wotlk#9337]
### Current Behaviour

Accepting  [Dispelling Illusions] (first quest from Chromie), does not show the plague progress on top of the screen. ~~nor is it possible to complete the quest. She will in fact whisper you in the end, but the quest won't be completed.~~

### Expected Blizzlike Behaviour

After accepting the quest, the create progress should show and dispelling 5 crates should complete it.

### Steps to reproduce the problem

1. .tele culling
2. Speak with Chromie and accept Dispelling Illusions [13149]
3. Notice that there is no crate progress.
4. Attempt to dispel plague creates.

### Extra Notes

This is from a recent change, worked fine a month ago. Could perhaps be #9006.
Teleporting (After finish the 2 quests) also does not work.

The wave number & timer work properly.

**EDIT: Reverting to previous version of _culling_of_stratholme.cpp_ fixed all issues for me.**

### AC rev. hash/commit

29f49108a5f8

### Operating system

Windows 10 

### Custom changes or Modules

None

**Comment by Shineslippers** [comment]
You can complete [Dispelling Illusions](https://wowgaming.altervista.org/aowow/?quest=13149), but progression bar indeed doesn't work. `.go c id 26527` `.q a 13149`
Also there is something with Cromie gossips. She doesn't teleport you after Illusion conflict complete.
![WoWScrnShot_112621_194506](https://user-images.githubusercontent.com/85256266/143611528-c2889897-8bcf-4ed0-a4b7-e02629f8d913.jpg)

**Comment by avarishd** [comment]
Yeah my bad, the quest does in fact complete.
