### ISSUE TITLE
Hunter: Wrong pet attack speed

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#9351]
### Current Behaviour

When I played in classic, I used Petopia to find the right pet at the moment with decent attack speed to generate more threat while leveling. Sadly the pet that I used, `Savanah Huntress` has the wrong attack speed.
I'm not sure if this is a generic problem for most pets or not so they should be checked at least the most important beasts.

### Expected Blizzlike Behaviour

Instead of 2.0 Attack speed, Savanah Huntress should have 1.5 Attack Speed. You can find the resources down bellow.

### Source

[Petopia](https://www.wow-petopia.com/classic/attackspeed.php)

### Steps to reproduce the problem

1. Tame a Savanah Huntress
2. Check attack speed

### AC rev. hash/commit
44de147a9bc6eb4522f4e92572d7b6b91d0854fe
### Operating system

Windows 10

**Comment by Shineslippers** [comment]
https://www.wow-petopia.com/classic_bc/attackspeed.php

**Comment by claudiodfc** [comment]
Buck Flizzard.
