### ISSUE TITLE
Worldserver suddencly closes (NPC Vicious Geist outside ICC)

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#9353]
### Current Behaviour

About 3 minutes after using .tele icecrowncitadel, some kind of event starts outside ICC, and they cause worldserver to close and the crashlog is empty.

It happens when the NPC Vicious Geist gets close to Pustulent horror

Check at 2:50:
https://www.youtube.com/watch?v=JU-Q41j8gQ8

### Expected Blizzlike Behaviour

No crashes

### Steps to reproduce the problem

1. .tele icecrown citadel
2. wait 3 minutes
3. watch the undead npcs fighting

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/35fc95312f74

### Operating system

Windows 10 x64

### Custom changes or Modules

none

**Comment by digsgg** [comment]
Confirmed here.
Tested on a clean build as well, reproduced the exact same steps, server crashed after a few minutes.

**Comment by 0xCiBeR** [comment]
Can confirm this also with clean build, the crash happens right after the fight begins.

**Comment by Kitzunu** [comment]
here's the callstack from the crash =) https://gist.github.com/Kitzunu/1182ea1433393e2afe7c03ea04c6329e

**Comment by Nyeriah** [comment]
Supposedly fixed in: https://github.com/azerothcore/azerothcore-wotlk/commit/36fc50e1a8b95202d5be2ede4ac21fb52dfada5a

Did it not fix it?

**Comment by Kitzunu** [comment]
Let me check. Just realized my pull fucked up so didn't get the commits from the past day

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/36fc50e1a8b95202d5be2ede4ac21fb52dfada5a

**Comment by Nyeriah** [comment]
Cool, thanks for checking it!
