### ISSUE TITLE
Dead animated NPCs does not stand when they attack you

### ISSUE THREAD

**Issue by overflowz** [azerothcore/azerothcore-wotlk#9354]
### Current Behaviour

When there are any NPCs that have `creature_addon.bytes1` flag set to 7 (which is `Shows health bar as empty (combine with the state dead emote to make a creature look dead)`) the flag is not changed after aggroed and NPC animation looks like they're attacking you while dead.

### Expected Blizzlike Behaviour

NPC should stand up when attacking you.

### Steps to reproduce the problem

1. .go creature 93209
2. attack it
3. NPC will attack you while laying down (dead) -- this is an animation issue.

### AC rev. hash/commit

AzerothCore rev. 3aec503ab41f

### Operating system

Windows 10, WSL2 with Docker

**Comment by Shineslippers** [comment]
Confirmed.
https://user-images.githubusercontent.com/85256266/143609934-2c66116e-0660-4584-b841-96c13dba9633.mp4

**Comment by overflowz** [comment]
worth mentioning, this happens to ALL NPCs that have that flag set, not only the one shown in the video.

**Comment by malcrom** [comment]
There is nothing wrong with the flag. The creature is missing scripting. The creature in the video is missing gossip also. I have this mostly complete. Will get a sniff today and complete.

**Comment by overflowz** [comment]
What I meant is that, I found two NPCs who had that same flag (I'm not really aware of the codebase, just guessing) and they had the same behavior.

Another NPC I found is in a shadowfang keep dungeon, but forgot the ID.
To reproduce, go to shadowfang keep dungeon, free the prisoner, and when he opens the door (or you open it as a GM) there's an undead lying down dead animated (same flag set) and when you attack it (you must be alliance to do that), it acts the same way as this NPC shown in the video.

Cheers.

**Comment by Shineslippers** [comment]
Shadowfang NPC is blizzlike

**Comment by overflowz** [comment]
Kinda confused, it should not stand up when it attacks you?

**Comment by Shineslippers** [comment]
No, i mean different. My mistake. Anyway it's reported there https://github.com/azerothcore/azerothcore-wotlk/issues/8716

**Comment by malcrom** [comment]
Works now

**Comment by malcrom** [comment]
NPC's that do not stand to fight, when they should, will need to be reported individually. Fixing will require individual scripting.

**Comment by overflowz** [comment]
Noted, thanks!
