### ISSUE TITLE
Deathly Usher NPC (Blasted Lands 48,22) not porting player when dead

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#9356]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

On the quest [You Are Rakh'likh, Demon], Deathly Usher NPC (Blasted Lands 48,22) is not porting the dead player back to the top of the hill (where player died) in order to ress. 

Only way to ress is at spirit healer. 

### Expected Blizzlike Behaviour

Deathly Usher should port the player with the quest [You Are Rakh'likh, Demon] whether dead or alive.

### Source

https://github.com/chromiecraft/chromiecraft/issues/2401

### Steps to reproduce the problem

Have the quest [You Are Rakh'likh, Demon] : 

1. Go to Blasted Lands
2. Die
3. Go to 48,22
4. Speak to Deathly Usher
5. Click on "I wish to face the defiler"

![Annotation 2021-11-25 201714](https://user-images.githubusercontent.com/72312283/143487947-1f2b8e8a-aa6d-4a81-963d-b4c54af3598b.png)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
So he can't cast spell on dead player.

**Comment by malcrom** [comment]
ID - 12885 Teleport to Razelikh
AttributesEx2: 0x00000001 (SPELL_ATTR2_CAN_TARGET_DEAD)

Spell handling issue
