### ISSUE TITLE
[Greater Wind Stone] Baron Kazum issues

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9366]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60  

### Current Behaviour

[Baron Kazum](https://wowgaming.altervista.org/aowow/?npc=15205) has boadcast text issues

![WoWScrnShot_112621_163808](https://user-images.githubusercontent.com/85256266/143589319-1f15f5fb-97da-4a4e-9483-f81881281d9e.jpg)

### Expected Blizzlike Behaviour

Broadcast text without `$`

### Source

[Wowhead Baron Kazum](https://www.wowhead.com/npc=15205/baron-kazum)

### Steps to reproduce the problem

.go c 42971
.additem 20406
.additem 20407
.additem 20408
.additem 20422
.additem 20451
.additem 20449
wear items
use [Greater Wind Stone] near

.npc add 15205

### Extra Notes

```sql
-- Baron Kazum
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=15205;
DELETE FROM `smart_scripts` WHERE `entryorguid`=15205 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(15205,0,0,0,0,0,100,0,3000,6000,13000,16000,11,25056,0,0,0,0,0,1,0,0,0,0,0,0,0,"Baron Kazum - In Combat - Cast Stomp"),
(15205,0,1,0,0,0,100,0,7000,10000,15000,28000,11,19129,0,0,0,0,0,1,0,0,0,0,0,0,0,"Baron Kazum - In Combat - Cast Massive Tremor"),
(15205,0,2,0,0,0,100,0,12000,15000,15000,18000,11,17547,0,0,0,0,0,2,0,0,0,0,0,0,0,"Baron Kazum - In Combat - Cast Mortal Strike");

DELETE FROM `creature_text` WHERE `CreatureID`=15205 AND `ID`>0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(15205,0,1,"You dare!  Outrageous!  I curse you, $c.  I curse you with... death!",14,0,100,0,0,0,10806,0,"Baron Kazum"),
(15205,0,2,"What?  Such a small, frail thing beckons me?  I shall add your bones to my throne, $r!!",14,0,100,0,0,0,10807,0,"Baron Kazum"),
(15205,0,3,"Killing you and your cohorts, $c, will amuse me.  I shall make it quick.",14,0,100,0,0,0,10810,0,"Baron Kazum");
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
Where are these SAI's from?

**Comment by Shineslippers** [comment]
TC

**Comment by malcrom** [comment]
OK, I can see that there is missing code to make it fully blizzlike. I have them copied and will work on them.
