### ISSUE TITLE
Silithus Wind stone objects doesn't have despawn/respawn mechanic

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9368]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60  

### Current Behaviour

[Wind stones](https://wowgaming.altervista.org/aowow/?search=wind+stone#objects) in Silithus doesn't despawn after usage

### Expected Blizzlike Behaviour

Wind stones should despawn/respawn:
- Lesser Wind Stone probably `5 minutes`
- Wind Stone probably `15 minutes`
- Greater Wind Stone probably `3 hours`

### Source

Wowpedia [Wind stone](https://wowpedia.fandom.com/wiki/Wind_stone?oldid=2245862)
> The respawn time on the Wind stones seems to be approximately 15 minutes

Wowhead [Greater Wind Stone](https://www.wowhead.com/object=180466/greater-wind-stone#comments:id=438172)
> By 139036 on 2008/11/11 (Patch 3.0.3)
anyone know if there's a respawn timer on these things? i went to the 3 camps and none of them were there. farmed for 2 hours and saw that none of the stones respawned yet.

Wowhead [Lesser Wind Stone](https://www.wowhead.com/object=180456/lesser-wind-stone#comments:id=351425)
>By 43448 on 2008/08/13 (Patch 2.4.3)
These seem to have about a five minute reset timer before they can be activated again. Worth knowing if you've stocked up on a bunch of twilight sets.

https://youtu.be/zvHNPnQ8E8E?t=32
https://youtu.be/65ZLfNHtC78?t=9

### Steps to reproduce the problem

.go c 42971
.additem 20406
.additem 20407
.additem 20408
.additem 20422
.additem 20451
wear items
use [Greater Wind Stone] near

.go c 42972
.additem 20406
.additem 20407
.additem 20408
.additem 20422
wear items
use [Wind Stone] near

.go c 42955
.additem 20406
.additem 20407
.additem 20408
wear items
use [Lesser Wind Stone] near

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
Working on this
