### ISSUE TITLE
Basic Campfire could be stacked on top of each other

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9369]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60  

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2402

It is currently possible to ,literally, stack on top of each other using the "campfire" spell off the "cooking" secondary profession; which allows players to possibly reach restricted places I guess?
![WoWScrnShot_112521_193755](https://user-images.githubusercontent.com/95049444/143490993-19c2b9cc-71ab-4bc5-b95a-23592b8b07e8.jpg)

Tester:

The issue is confirmed. You can stacking [Basic Campfire](https://wowgaming.altervista.org/aowow/?spell=818) on top of each other. Levitate spell help you do it faster. talented players can create something beatuful or bannable

![WoWScrnShot_112621_185350](https://user-images.githubusercontent.com/85256266/143605978-26bb655c-4abf-48a3-bd4d-e1ea38626817.jpg)

### Expected Blizzlike Behaviour

Idk, but there is something wrong.

### Source

X

### Steps to reproduce the problem

.aura 1706
.cast 818

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
A note, hodir's mage can also cast toasty fires on top of each others. Might be related.

**Comment by malcrom** [comment]
> A note, hodir's mage can also cast toasty fires on top of each others. Might be related.

Spell id?

**Comment by malcrom** [comment]
Will script spell after I receive a sniff I requested.

**Comment by malcrom** [comment]
So campfire has a 5 min cool down. There is no way for one person to do this. As for preventing multiple players we would need to fix Gameobject casting first so player can get Cozy fire aura to use as a cast spell prevention check.

**Comment by Shineslippers** [comment]
Aren't players able to remove aura? Atleast for some time.

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/143779876-3c2dd3bc-24c5-4447-a4a2-d0b169af07c9.png)
i am loving how very well endow you are @Shineslippers with the camp fires.

**Comment by claudiodfc** [comment]
> So campfire has a 5 min cool down. There is no way for one person to do this. As for preventing multiple players we would need to fix Gameobject casting first so player can get Cozy fire aura to use as a cast spell prevention check.

Wouldn't that prevent players from casting Campfires? afaik you could cast it even when you add the aura, they should just clip but not stack, from what I can recall at least.

**Comment by Nyeriah** [comment]
The spells that spawn gameobjects like campfire and fish feast should check absolute Z position and not relative, so they always spawn on ground and not on top of other objects

**Comment by UltraNix** [comment]
> The spells that spawn gameobjects like campfire and fish feast should check absolute Z position and not relative, so they always spawn on ground and not on top of other objects. I also think checking for the aura is wrong, you can spawn fires near each other, yeah

Nope. Imagine spawn campfire on other gameobjects, e.g. ToC platform or on ship/zeppelin. It mustbe done as it is now.
