### ISSUE TITLE
[Raid]Onyxia encounter won't enter P2

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#9376]
### Current Behaviour

as title
Onyxia stay on ground in whole battle , without Phase 2.

### Expected Blizzlike Behaviour

after it's health down to 65% , should fly up enter phase 2 then enter p3 while down to 40% health.

### Steps to reproduce the problem

.cheat god
.go c id 10184
reduce boss health low than 65%

### AC rev. hash/commit

06a81758056a+

### Operating system

Ubuntu 20.04

**Comment by Nyeriah** [comment]
I can't reproduce this
![Skärmbild 2021-11-27 022135](https://user-images.githubusercontent.com/47818697/143669140-d5e334ff-c2b4-4137-b4cf-f30f3e750123.jpg)

**Comment by betayi** [comment]
what's your AC rev ? it's normal before one or two weeks ago, after recent update, it doesn't work normally

**Comment by betayi** [comment]
it's resloved , by #9367 , thanks
