### ISSUE TITLE
Feature: Make GameObject worldobject

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#9387]
### Describe your feature request or suggestion in detail

Turn AI into worldobject and allow Gobs to be scripted like creatures.

Currently this prevents us from using RegisterGameObjectAIWithFactory

TC did this long ago.

**Comment by Nyeriah** [comment]
New macro works with objects now?

**Comment by Kitzunu** [comment]
Sudlud have been using them so I assume so

**Comment by Kitzunu** [comment]
Disclaimer (I believe it is sudlud)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/0f82c8e8dd64df839df57e88073709c93f9c6ca0#diff-9292be7b5310dc5bfaee486fe9ebe853c2e808214135b5c8cd1b12d224855dd6R205 Yup he uses them so I assume they work 100%

**Comment by sudlud** [comment]
Nice
