### ISSUE TITLE
Core/DB MISS scriptname

### ISSUE THREAD

**Issue by w5860363** [azerothcore/azerothcore-wotlk#9393]
### Current Behaviour

https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Outland/zone_shattrath_city.cpp#L266
npc id(25967) user smartAI not use scrtipname
Is this intentional?

### Expected Blizzlike Behaviour

Clean up useless code or apply correct C + + code

### Steps to reproduce the problem

1.go cr 94504
2.modify rep 989 36000
3.gossip appears

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/05a2d5baa8da9bf3d82cdb2294e415c50b43133b

### Operating system

Windows 10 x64,

**Comment by Nyeriah** [comment]
You must be checking the wrong database. She does not use SAI on AzerothCore.

```sql
entry,difficulty_entry_1,difficulty_entry_2,difficulty_entry_3,KillCredit1,KillCredit2,modelid1,modelid2,modelid3,modelid4,name,subname,IconName,gossip_menu_id,minlevel,maxlevel,exp,faction,npcflag,speed_walk,speed_run,detection_range,scale,rank,dmgschool,DamageModifier,BaseAttackTime,RangeAttackTime,BaseVariance,RangeVariance,unit_class,unit_flags,unit_flags2,dynamicflags,family,trainer_type,trainer_spell,trainer_class,trainer_race,type,type_flags,lootid,pickpocketloot,skinloot,PetSpellDataId,VehicleId,mingold,maxgold,AIName,MovementType,InhabitType,HoverHeight,HealthModifier,ManaModifier,ArmorModifier,ExperienceModifier,RacialLeader,movementId,RegenHealth,mechanic_immune_mask,spell_school_immune_mask,flags_extra,ScriptName,VerifiedBuild, 25967,0,0,0,0,0,19282,0,0,0,Zephyr,,,9205,70,70,1,1779,1,1,1.14286,20,1,1,0,4.6,2000,2000,1,1,1,0,2048,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,,0,1,1,1,1,1,1,0,0,1,0,0,2,npc_zephyr,12340
```
