### ISSUE TITLE
Complete of task by pet doesn't count to progression of "They're Alive! Maybe..." quest

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9410]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2428

As a hunter, if I send my pet to attack the cocoons that hold the Expedition Researchers, if the pet "breaks" the cocoon and an Expedition Research appears, it will not count towards quest progress.

Tester:

The issue is confirmed. Quets [They're Alive! Maybe...](https://wowgaming.altervista.org/aowow/?quest=9670). If your pet kill the [Webbed Creature](https://wowgaming.altervista.org/aowow/?npc=17680) and will freed [Expedition Researcher](https://wowgaming.altervista.org/aowow/?npc=17681) it doesn't count to quest progression.

https://user-images.githubusercontent.com/85256266/143877153-1e5bce16-b8a3-4b5e-9f45-3873c4edc3c9.mp4

### Expected Blizzlike Behaviour

I would expect that quest progress based off damage to an in-game object should register for the character even for the pets of classes with pets.

### Source

X

### Steps to reproduce the problem

.q a 9670
.go c 94982
.pet create
attack Webbed Creature

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Azcobu** [comment]
Possibly related to https://github.com/azerothcore/azerothcore-wotlk/issues/8157, which is also about pets killing a quest objective and not properly advancing the quest, although it was an NPC rather than a gameobject in that case.
