### ISSUE TITLE
NPCs after taunt/growl of pets keep moving toward Player position

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9421]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2435

It's not always repeatable but sometimes, when you aggro a mob and send your pet to attack, after generating threat and doing a taunt macro, the enemy npc keeps moving to my position when I taunted.

Tester:

The issue is confirmed. From time to time(i would say 50/50) NPCs after taunt/growl of pets keep moving toward Player position. Looks like something related to animation of NPC attack.

https://user-images.githubusercontent.com/85256266/144039758-d56d4940-d977-44fe-9e13-91113699c9fc.mp4

### Expected Blizzlike Behaviour

Enemy NPC no moving towards the Hunter and staying focus the pet.

### Steps to reproduce the problem

.go c 19874
.pet create
attack some NPC from range
use growl/taunt when pet will be near/behind NPC

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@Shineslippers I can't reproduce it. Can you test it again with some threat addon so I can see it's not a problem with threat?

**Comment by Shineslippers** [comment]
For some reason i'm not able to reproduce it with cat, but strider. Idk why. Maybe try `.go c 19363` `.pet create`

https://user-images.githubusercontent.com/85256266/145269166-87e0acdc-9ac6-4824-a645-3726039a44ad.mp4

**Comment by UltraNix** [comment]
In the 2nd videos, as you can see, the mob run towards to you until your pet cause some aggro on that mob.

**Comment by Shineslippers** [comment]
Yes, probably you're right. 2nd video with Omerty Strider not the issue. Anyway existing delay betwwen taunt and agro.

1st video with Witchwing Roguefeather more representative. She is still moving even when agro already builded.
