### ISSUE TITLE
Hand of Justice Trinket Not Proccing From Various Melee Abilities

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9423]
### What client do you play on?

enGB

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2433

https://imgur.com/a/zrtGUGP

You can see from the pics that i posted that it doesn't proc if you just spam crusader strike without auto attacking. Only tested on paladin, feel free to test on warriors and rogues too. If you think it's just rng because i got only 2 procs autoattacking, it's not the first time i spammed crusader to see if it procs.

Tester: confirmed for Crusader Strike - I used the suggested macro and went long past the point where RNG could explain it not working. 

Also tested with a warrior using Heroic Strike and a rogue using Mutilate, but both of those worked fine with the trinket:

![WoWScrnShot_113021_233422](https://user-images.githubusercontent.com/81782124/144054434-91ac8b07-253b-4c41-9e57-471389ae14f7.jpg)
![WoWScrnShot_113021_234125](https://user-images.githubusercontent.com/81782124/144054438-8486fd52-b19d-418c-b1e2-bcab7bbeb6fc.jpg)

(Also note minor typo "Name's gains", not sure if that can be fixed.)

The trinket says "Chance on melee hit to gain 1 extra attack." So it appears to come down to whether Crusader Strike should be regarded as a melee hit, and I don't see any reason why it wouldn't be. It deals physical damage in the combat log.

Update: further testing with warr's Slam and various druid abilities. Slam was very strange, as it would sometimes (it seemed much rarer than 2%) proc the visual effect, but with no entry in the combat log or a second melee swing. I found similar behaviour with a druid bear's Mangle, with a visual effect but nothing in the combat log and no extra swing. The first pseudo-proc only came after the combat log was 3600 lines long - even at 3 lines per Mangle, that's a lot rarer than 2%. The other bear abilities like Swipe, Lacerate and Maul all didn't seem to proc it at all. You might think druids shouldn't proc HoJ as they're not weapon users, but various comments on Wowhead say they did.

Procs but nothing in log and no second swing for both Slam and Mangle:
https://user-images.githubusercontent.com/81782124/144230191-dfe7f561-d4ca-4556-bf6a-b1da22a8b422.mp4

### Expected Blizzlike Behaviour

The trinket should work for any melee hits.

### Source

https://www.youtube.com/watch?v=6O6dcPX_IPA

This is on classic. Only MH weapon is equipped and you can clearly see the HoJ animation after the first sinister strike and a white hit right after.)

Would prefer a Wrath source over Classic, and something more related to Crusader Strike, but haven't found any direct sources to say CS should work with the trinket, so we're kind of relying on interpreting the tooltip properly, and on consistency - Heroic Strike/Mutilate seem to be in the same class of attacks, and they work.

For druids: https://tbc.wowhead.com/item=11815/hand-of-justice#comments:id=3159683
> This CAN proc in druid forms. I saw a lot of conflicting information on whether or not it would but I just finally got and tested it: https://i.imgur.com/nGiSFwX.png

> as long as it's not on the weapon itself, on-hit effects DO work for druid forms.

> It's just down to the wording. It can be on the weapon, but it has to say "on hit" or "On melee hit". If it says "On weapon hit" it won't work in feral.

### Steps to reproduce the problem

1. Just auto attack and you'll see the trinket proccing.
2. Make a stopattack macro for an ability (/cast crusader strike /stopattack) so you don't auto attack. You'll see the trinket not proccing.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by immersionnn** [comment]
btw, check with slam too. psure it doesn't proc off it from my experience. (didn't test but didn't see really proccing while playing my warrior, maybe i'm just wrong)
