### ISSUE TITLE
Vanilla nodes for mining using sniffed data

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#9431]
## IMPORTANT - About Pooling
Important to remember that pooled gameobjects currently don't respawn and that this should be fixed along side with dynamic spawn.

### Current Behaviour

Currently our veins or nodes, are not sniffed data and therefor, very inaccurate.

I'm opening this issue to keep track of the zones that I'll be working on using Brotalnia's sniffs from Classic and crossing with VMangos data.

### Expected Blizzlike Behaviour

1-10 (Mostly Copper)
- [ ] Elwyn Forest
- [ ] Dun Morogh
- [ ] Teldrassil
- [ ] Durotar
- [ ] Mulgore
- [ ] Tirisfal Glades

10-20 (Silver, Tin and Copper)
- [ ] Westfall
- [ ] Loch Modan
- [ ] Darkshore
- [ ] Barrens
- [ ] Silverpine Forest

20-30
- [ ] Redridge Mountains 
- [ ] Ashenvale
- [ ] Stonetalon Mountains
- [ ] Wetlands
- [ ] Duskwood
- [ ] Hillsbrad Foothills

30-40
- [ ] Stranglethorn Vale
- [ ] Thousand Needles
- [ ] Desolace
- [ ] Arathi Highlands

40-50
- [ ] Badlands
- [ ] Dustwallow Marsh
- [ ] Tanaris
- [ ] The Hinterlands
- [ ] Feralas
- [ ] Searing Gorge

50-60
- [ ] Blasted Lands
- [ ] Un'Goro Crater
- [ ] Azshara
- [ ] Felwood
- [ ] Winterspring
- [ ] Burning Steppes
- [ ] Western Plaguelands
- [ ] Eastern Plaguelands

### Source

Brotalnia's Sniffs and VMangos data crossed for accuracy

### Steps to reproduce the problem

Fix the nodes

### AC rev. hash/commit

e6b755d467f9

### Operating system

Windows 10

**Comment by Shineslippers** [comment]
@claudiodfc Hey yo! is it still `WIP`? What's going on with this topic?

**Comment by claudiodfc** [comment]
This is on standby until someone Implements Dynamic Spawn

**Comment by benjymansy123** [comment]
May I ask why this was closed?

**Comment by hanabi5** [comment]
Well, I have no idea how to implement dynamic spawned gameobjects and I need it for a complete fix. Since I don't have the solution yet or until someone implements it, I'll think about fixing the veins.
