### ISSUE TITLE
Newly created characters do not trigger their first login events at their actual first login

### ISSUE THREAD

**Issue by TheLegendaryKingdom** [azerothcore/azerothcore-wotlk#9439]
### Current Behaviour

As I create a new character and enter the game with it, it does not cast the warrior battle stance or deathknight blood presence.
More, the module "custom login" does not trigger on first login neither (actually none of my modules seem to proceed their first login) (and I assume the first login event may globally be unavailable). Though, when you create a toon, its "at_login" in DB characters.characters is 32 (correct one I guess, the issue does not seem related to this).
It was correctly working before I update my AC source (and I had to edit the 2021_11_30_2.sql db_world update in order for the core to apply it and launch itself correctly).

### Expected Blizzlike Behaviour

Newly created warriors and Deathknight should cast their stance/presence at first time login, and OnFirstLogin event should trigger correctly ?

### Steps to reproduce the problem

1°) Create a new character
2°) Login with it

### Extra Notes

Maybe something on my core is broken ?
Using MariaDB by the way.

### AC rev. hash/commit

AzerothCore rev. **5aa16be9133a** 2021-12-01 06:39:18 +0100 (dev branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 100331
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-91-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/northrend/TheLegendaryKingdom/Server/data/maps. Total size: 252190703 bytes
vmaps directory located in /home/northrend/TheLegendaryKingdom/Server/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/northrend/TheLegendaryKingdom/Server/data/mmaps. Total size: 2196365032 bytes
Using frFR DBC Locale as default. All available DBC locales: frFR
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_11_30_02
Using Character DB Revision: 2021_10_14_00
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

Ubuntu 20.04.3

### Custom changes or Modules

mod-autobalance
mod-bg-reward
mod-cfbg
mod-character-tools
mod-custom-login
mod-eluna-lua-engine
mod-bg-reward
mod-cfbg
mod-character-tools
mod-custom-login
mod-eluna-lua-engine
mod-learn-spells
mod-learn-spells
mod-npc-buffer
mod-pvp-titles
mod-skip-dk-starting-area
mod-solocraft
mod-transmog

I forked all the modules I use and actually edited some of them (mod-custom-login, mod-skip-deathknight-starting-area, mod-transmog).

I also edited SpellAuraEffects.cpp, SpellEffects.cpp and Unit.h on my AC fork

**Comment by TheLegendaryKingdom** [comment]
### I tried compîling a _fresh AC up-to-date and unedited_

 **The issue persists**. Actually, warriors and deathknights **do not cast their stances at first login after character creation** (battle stance and blood presence) and I assume a more global issue is behind and **the whole first login process may not correctly be done**.

**Comment by acidmanifesto** [comment]
I opened up a PR implementing the feature and table. However i will require independent testing from my self before it is considered for merging into the master branch. @TheLegendaryKingdom

**Comment by TheLegendaryKingdom** [comment]
Tested it, works like a charm ! Warriors and DK now correctly cast their stance/presence on first login after character creation, like it was intended and like it was before it was not anymore (let me hit the joint again, my sentences becoming better and better XD)
