### ISSUE TITLE
Various issues with Great-father Winter is Here! quest

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9440]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

1. [Whulwert Copperpinch](https://wowgaming.altervista.org/aowow/?npc=13431) doesn't spawned anywhere
2. Quests Great-father Winter is Here! [ID7024](https://wowgaming.altervista.org/aowow/?quest=7024) and [ID7021](https://wowgaming.altervista.org/aowow/?quest=7021) questender in Ironforge instead of Orgrimmar [Great-father Winter](https://wowgaming.altervista.org/aowow/?npc=13445)
3. Text of Great-father Winter is Here!(6961, 7021, 7024) is refering to `Greatfather`

![WoWScrnShot_120121_172553](https://user-images.githubusercontent.com/85256266/144251910-3d41a6a9-ce8d-4ac1-a8c0-b043925cd017.jpg)

### Expected Blizzlike Behaviour

1. Whulwert Copperpinch Should be spawned in Thunder Bluff `42-43 55-58`. Somewhere here near tree
2. Questender should be in Orgrimmar for horde faction
3. Quest text should refer to `Great-father`

### Source

Wowhead [Whulwert Copperpinch](https://tbc.wowhead.com/npc=13431/whulwert-copperpinch)
![awfce](https://wow.zamimg.com/uploads/screenshots/normal/66087-whulwert-copperpinch-old-model.jpg)

Wowhead [Great-father Winter is Here!](https://www.wowhead.com/quest=7021/great-father-winter-is-here#comments)

Wopedia [Whulwert Copperpinch](https://wowpedia.fandom.com/wiki/Whulwert_Copperpinch?oldid=2332805)
> Whulwert Copperpinch is a vendor located on the Lower Rise in the tauren city of Thunder Bluff [42.0, 55.7] during the Feast of Winter Veil event.
Wowwiki [Quest:Great-father Winter is Here!](https://wowwiki-archive.fandom.com/wiki/Quest:Great-father_Winter_is_Here!?oldid=2332844)
>There are actually three quest givers who can give this quest:
In Orgrimmar, it is Kaymard Copperpinch (53,66) in the Valley of Strength
In Thunder Bluff, it is Whulwert Copperpinch (43,58) on the Lower Rise
In Undercity, it is Nardstrum Copperpinch(68, 39)

### Steps to reproduce the problem

.event start 2

.q a 7021 as allince
.q a 7024 as allince
.go c id 13444

.go c id 13431

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9465
