### ISSUE TITLE
Dark Iron Kidnapper is missing SAI

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9443]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Dark Iron Kidnapper](https://wowgaming.altervista.org/aowow/?npc=15692) is missing SAI
![image](https://user-images.githubusercontent.com/85256266/144289537-5d3bdc63-e3b1-45cd-a809-8bdd5b81a54f.png)

### Expected Blizzlike Behaviour

They shoud have some text

### Source

Wowhead [Dark Iron Kidnapper](https://www.wowhead.com/npc=15692/dark-iron-kidnapper)
> By Chaosangel on 2006/12/19 (Patch 2.0.1)
These are the evildoers that kidnapped Metzen the Reindeer and held him hostage in the Searing Gorge.
As you fight them, they say "Let me give you my regards for Greatfather Winter, scum."

### Steps to reproduce the problem

.event start 2
.go c id 15692

### Extra Notes

TC fix

```sql
-- Dark Iron Kidnapper SAI (Source: Movies)
SET @ID := 15692;
UPDATE `creature_template` SET `AIName` = "SmartAI" WHERE `entry` = @ID;
DELETE FROM `smart_scripts` WHERE `entryorguid` = @ID AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ID,0,0,0,4,0,15,0,0,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,0,"Dark Iron Kidnapper - On Aggro - Say Line 0");

DELETE FROM `creature_text` WHERE `CreatureID` = @ID;
INSERT INTO `creature_text` (`CreatureID`,`GroupID`,`ID`,`Text`,`Type`,`Language`,`Probability`,`Emote`,`Duration`,`Sound`,`BroadcastTextId`,`TextRange`,`comment`) VALUES
(@ID,0,0,"Ye'll be feasting on me blade this Winter Veil!  Yeargh!",12,0,100,0,0,0,11397,0,"Dark Iron Kidnapper"),
(@ID,0,1,"No scallywag $c is taking our Winter Veil plunder!  Get 'em!",12,0,100,0,0,0,11398,0,"Dark Iron Kidnapper"),
(@ID,0,2,"These land lubbers are here for the reindeer!  Give 'em the shank!",12,0,100,0,0,0,11399,0,"Dark Iron Kidnapper"),
(@ID,0,3,"It's a rescue attempt!  Let no one escape!",12,0,100,0,0,0,11400,0,"Dark Iron Kidnapper"),
(@ID,0,4,"Let me give you my regards for Greatfather Winter, scum...",12,0,100,0,0,0,11401,0,"Dark Iron Kidnapper"),
(@ID,0,5,"Humbug!  Die!",12,0,100,0,0,0,11402,0,"Dark Iron Kidnapper"),
(@ID,0,6,"It's a rescue attempt!  Slay them all!",12,0,100,0,0,0,11403,0,"Dark Iron Kidnapper"),
(@ID,0,7,"The only thing Metzen is going to be doing this Winter Veil is roasting on a spit!",12,0,100,0,0,0,11404,0,"Dark Iron Kidnapper");
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9461
