### ISSUE TITLE
Grobbulus doesn't aggro his room

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#945]
Description: Grobbulus doesn't aggro the room

Current behaviour: When we pull Grobbulus , if trash are alive in his room , they don't come with the boss

Expected behaviour: When we pull Grobbulus , trash alive should come with the boss.

Steps to reproduce the problem:

1. Go to Naxxramas , after Patchwerk
2. Let alive all the trash in the Grobbulus room
3. Then pull Grobbulus

Branch(es): master

AC hash/commit:  7329ad4

Operating system:  Linux

Modules:  /

Other Customizations: /

**Comment by Nefertumm** [comment]
I think this got fixed with 2b37ea11a97c9c2640da37c23e7e12889835bbd9
