### ISSUE TITLE
Intercept Affected By Crowd Control Incorrectly

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9454]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2449

If an warrior Intercepts a druid that has Nature's grasp  on him, warrior is rooted BEFORE reaching the druid.
This is also happening with frost mage. If Frostbite activate in the moment that warrior press Charge/Intercept warrior freeze in initial place.

Tester: confirmed for Nature's Grasp. Couldn't check Frostbite as the timing is a bit tricky for one person.

The Nature's Grasp problem is even worse than stated. The intercept fails, NG procs, and the warrior is rooted, although the druid target is stunned and debuffed. Once the roots fade, the warr seems to attack (no animation, but a "Miss" above the druid at the 10 second mark), which then procs NG for a second time.

https://user-images.githubusercontent.com/81782124/144391200-5e9ee5e9-44e9-4fda-b837-d9a60b211549.mp4

### Expected Blizzlike Behaviour

If a warrior Intercepts a druid that has Nature's grasp on him, warrior should be rooted AFTER warrior reach the druid.
If Frostbite activate in the moment that warrior press Charge/Intercept warrior MUST freeze AFTER he reach mage.

https://wowgaming.altervista.org/aowow/?spell=20252

### Source

Didn't find any details on direct interactions between Intercept and Nature's Grasp, but don't think the expected behaviour above is controversial, at least for NG. https://wowpedia.fandom.com/wiki/Nature's_Grasp?oldid=2336204 does say "Procs off melee only, does not proc off spells or ranged attacks." 

### Steps to reproduce the problem

1. Your druid target must have Nature's Grasp active on him
2. Use berserk stance and use INTERCEPT
3. Warrior don't reach druid, he's being rooted on initial place
4. Also with mage is harder to reproduce, mage must cast frostbolt on you and when warrior charge/intercept and frostbolt reach warrior and Frostbite is activated warrior remain in the place when frostbite activated instead of reaching the mage.
5. I think second issue will be solved with first one, because seems to be the same mechanics and be a charge/intercept issue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
The problem here is that Intercept is doing the damage before the charge is over. The question is: that damage should be done once warrior reached the target or it is okay now?

**Comment by UltraNix** [comment]
@Azcobu The problem here is that Intercept is doing the damage before the charge is over. The question is: that damage should be done once warrior reached the target or it is okay now?

**Comment by UltraNix** [comment]
@Azcobu Are you here?

**Comment by Azcobu** [comment]
I'm not currently working on AC, and haven't researched Intercept damage, so don't have an opinion to offer on that.

**Comment by UltraNix** [comment]
@azerothcore/testers Anyone?

**Comment by Shard-MW** [comment]
Hello,
This looks like gamebreaking in PvP to me, so I would set a High Priority to this
As a PvP player, I don't remember Intercept damages proccing spells like Frost Bite, or other received-dmg-based procs

@UltraNix No, intercept damage shouldn't be done after the warrior reached the target.
Here you can see some Warrior vs Mage in arena (TBC Classic) : https://www.youtube.com/watch?v=UaJ-mTrnNH8
Everytime the warrior uses Intercept, damages are occuring instantly, so, before he reaches his target. I think we're good here

I also took a look at Intercept spell (https://tbc.wowhead.com/spell=25275/intercept) + checked in our DBCs if it was still the same (yes it does). It **triggers** the spell that is responsible of the inflicted stun and damages : https://tbc.wowhead.com/spell=25274/intercept-stun

So maybe triggered spells shouldn't trigger a proc even if they have "SPELL_ATTR2_ACTIVE_THREAT" attribute ?

@Azcobu 
> Once the roots fade, the warr seems to attack (no animation, but a "Miss" above the druid at the 10 second mark), which then procs NG for a second time.

About this, I have absolutely no idea why there is a melee attack at 25m. It may not be related to only warrior issue
