### ISSUE TITLE
Faerlina Frenzy timer 

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#946]
Description: Faerlina Frenzy timer 

Current behaviour: Faerlina Frenzy timer isn't blizzlike with urand 60000 80000 and wrong delay after the first Frzney

Expected behaviour: During Faerlina fight , Faerlina should become Frenzy after 1 minute of fight and all 1 minute after removal effect

Steps to reproduce the problem:

1. Go to Naxxramas , after Anub'rekhan
2. Engage Faerlina fight
3. See the timer and the delay of the Frenzy

Branch(es): master

AC hash/commit: 7329ad4

Operating system: Linux

Modules: /

Other Customizations: /

**Comment by talamortis** [comment]
This issue is invalid, your surposed to control one of her warlock minions and use the arcane explosion to dispell her enrage.

**Comment by Dreaxxx** [comment]
Wrong source wowikia , tested in retail , and i tell you about the timer , not the dispell method ^^
She should frenzy 1 minute after the start of the fight and every 1 minute after dispell effect

**Comment by talamortis** [comment]
Can you please provide proof?
