### ISSUE TITLE
Clearcasting of Omen of Clarity can proc from shapeshifting

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9467]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2455

Seems Clearcasting is proccing when you /cancelform from druid forms into caster form. Found this out when swimming in aquatic form and going to land (it auto cancels the aquatic form), but it seems to also proc when using /cancelform from any druid forms.

Tester:

The issue is confirmed. [Clearcasting](https://wowgaming.altervista.org/aowow/?spell=16870) of [Omen of Clarity](https://wowgaming.altervista.org/aowow/?spell=16864) can proc from  shapeshifting

https://user-images.githubusercontent.com/85256266/144449645-92e0e82c-5c97-46b1-8fdb-3e01e047c16c.mp4

### Expected Blizzlike Behaviour

Should not proc from shapeshifting

### Source

Wowwiki [Omen of Clarity](https://wowwiki-archive.fandom.com/wiki/Omen_of_Clarity?oldid=2301804)
> Essentially **_everything except shapeshifting_** can cause Clearcasting with this ability, regardless of whether it's a druid ability or not. The herbalist ability Lifeblood can trigger it.

### Steps to reproduce the problem

.cast 9634.
/cancelform

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Salehyn** [comment]
It seems /cancelform might have been fixed but shapeshifting itself can still proc Omen https://github.com/chromiecraft/chromiecraft/issues/4356
