### ISSUE TITLE
Noth Teleport Timer and Location

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#947]
Description: Noth Teleport Timer and Wrong location for Balcony

Current behaviour:

1. Noth Teleport to Balcony after 110000 (1min50) and back to the ground after 70000(1min10) , this timer are not blizzlike

2. Actually , the boss not teleport when the balcony phase appear , just enter in non targetable mod and stay at the same place
 

Expected behaviour: 

1. Noth should teleport to Balcony after 1min30 (90000) and back to the ground with the same timer (1min30).

2. When Noth teleport balcony , he sould teleport to : 
X: 2631.361572 Y: -3529.794189 Z: 274.039093 O: 0.005942

Steps to reproduce the problem:

1.Go to Naxxramas , Noth first boss of Plague quarter
2. Engage Noth fight
3. See the timer and the delay of the teleport Balcony and Ground

Branch(es): master

AC hash/commit: 7329ad4

Operating system: Linux

Modules: /

Other Customizations: /

**Comment by BarbzYHOOL** [comment]
@FALL1N1 you wanted some naxxramas issues :P

**Comment by talamortis** [comment]
im sure i fixed his teleport thing a while ago? can anyone else confirm this?

**Comment by talamortis** [comment]
could you please provide proof of this as 
http://wowwiki.wikia.com/wiki/Noth_the_Plaguebringer says the timer is correct, I know this is not reliable source from wowwiki but its the only thing we can go off for most encounters.

**Comment by Si1ker** [comment]
>When Noth teleport balcony , he sould teleport to X: 2631.361572 Y: -3529.794189 Z: 274.039093 O: 0.005942
### This is actually happening

>Actually , the boss not teleport when the balcony phase appear , just enter in non targetable mod and stay at the same place
### False

- - - -
**Timers** are correct in the script as http://wowwiki.wikia.com/wiki/Noth_the_Plaguebringer suggest.

Closing this old issue as is totally invalid on fresh AC cores
