### ISSUE TITLE
Nature's Grasp doesnt have ICD

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#9475]
### Current Behaviour

Nature's Grasp (rank 8) does not have an Internal Cooldown for the charges at the moment. If you get attacked very fast, you lose all stacks and the target gets rooted by 5s, instead of 10 (it refresh the root and get Diminish Return).

### Expected Blizzlike Behaviour

Nature's Grasp should have a small 1~2 seconds of internal cooldown.

### Source

https://www.bluetracker.gg/wow/topic/us-en/23425763051-natures-grasp-question/

''Nature's Grasp is a self buff that causes things that hit you to become rooted. That effect now has 3 charges. There is a small internal cooldown in between roots to keep say a rogue who hits you twice very quickly from wasting two charges. In your example, both the DK and pet should get rooted. If the DK breaks the roots and gets on you again, they will get rooted again (subject to the 45 sec duration).''

### Steps to reproduce the problem

1. cast nature's grasp .cast 53312 with one char
2. get a rogue with 2 fast daggers (1.8 and 1.4 speed)
3. on the rogue, cast hemmorhage (.cast 48660)
4. watch nature's grasp stacks and root duration on rogue

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/f0a10fd3c10a9063713dd60a943be59cf7b6e757

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
The issue is confirmed. Info about duration of internal CD is hard to find. From place to place 1-3 seconds.

**Comment by Kitzunu** [comment]
Give me the spell id that should have icd and I'll fix it

**Comment by Shineslippers** [comment]
Nature's Grasp family https://wowgaming.altervista.org/aowow/?search=Nature%27s+Grasp start from 16689

**Comment by Kitzunu** [comment]
Ok. I can look Monday/Tuesday unless someone already has

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9519
