### ISSUE TITLE
ChromieCraft PTR Freeze/Crash 03/12/2021

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9477]
See log here
https://pastebin.com/22yq3ww6

AzerothCore rev. 5877261bb703 2021-12-03 11:47:15 +0000 (pr-9124 branch)
(pr-9124 branch) -> We are testing the vmaps update on CC PTR. I don't know if it could be related to that.

**Comment by Kitzunu** [comment]
How to reproduce?
Does it happen on a clean core? If no. Then it's most likely due to the PR and you should post it there

**Comment by acidmanifesto** [comment]
I'm seeing a stuck core error based on conf?
https://github.com/azerothcore/azerothcore-wotlk/blob/5df73f668052ec932545ed3d160e39f71ca349f6/src/server/worldserver/Main.cpp#L641-L646
![image](https://user-images.githubusercontent.com/16887899/144687605-56b700f8-5461-4366-a30b-a89186d808e1.png)

**Comment by Nyeriah** [comment]
@acidmanifesto Yes, this is a freeze, not a typical crash. The first couple of threads you see in the crash logs will always print useless information, because it's the forced crash that happens once the freeze detector notices the server is stuck (e.g in a dead loop)

**Comment by temperrr** [comment]
Ok we reverted the PR, and we'll see if it happens again, else I'll report on the PR. Ty.

**Comment by temperrr** [comment]
Ok on master it still freezes

https://pastebin.com/tP09Y9Jm

modules
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Kitzunu** [comment]
Are you able to reproduce it or is it "random"?
Does it happen on a clean core. Aka no modules?

**Comment by temperrr** [comment]
It appears to be related to ah module

**Comment by temperrr** [comment]
Probably configuration fault. So I'll close this. Thanks for your time

**Comment by Nyeriah** [comment]
Reopening this, user mistakes/bad config shouldn’t be the cause of freezes/crashes, so the issue still needs to be identified and addressed

**Comment by Eronox** [comment]
If I read the freeze log correctly, then it seems to be caused by map updater failing to query the database. But then this is also my first attempt ever reading a freeze log, which is known to be obscure most cases

@temperrr what are you doing ingame, any way for us to reproduce manually? 

I don't think it's the AH since what I understand from the stacktrace, is that it solely notifies us about the deliberated sleep 

>  std::this_thread::sleep_for(1ms); @ Main.cpp:764

**Comment by Nyeriah** [comment]
Yes, the auction house runs on a thread of its own so it's natural that it shows the thread exiting in the crash log prints.

**Comment by temperrr** [comment]
Well, since it's a PTR, lot's of things can be going on, but it's weird that after removing ah module it didn't happen anymore. 
We also still have the vmaps PR listed above removed, and it did freeze once with same info as above after we removed it.
I am sorry that I can't give more details on this.

**Comment by temperrr** [comment]
If there is a log or anything that could help, please do say and I'll see if I can find it

**Comment by Kitzunu** [comment]
Are you just playing around when it happens, or do you so something similar everytime it freezes?

**Comment by temperrr** [comment]
I don't play at the time, it happens like clockwork every +-30 minutes. Server has been up for 12+ hours now with no issue.

**Comment by Kitzunu** [comment]
Nye explained how it worked. Thanks

**Comment by temperrr** [comment]
Keeps freezing, but less frequent;

https://pastebin.com/r0kbTCPL

**Comment by temperrr** [comment]
https://pastebin.com/VFXWMG3M

**Comment by Eronox** [comment]
Can this be related? 

> <error reading variable soap (value of type `soap' requires 164336 bytes, which is more than max-value-size)>

**Comment by Kitzunu** [comment]
@Nyeriah @temperrr @Winfidonarleyan

**Comment by temperrr** [comment]
We no longer have these crashes, sorry for not closing it. Can't remember what fixed it.
