### ISSUE TITLE
Kel'Thuzad Phase 1 undermap mobs

### ISSUE THREAD

**Issue by Dreaxxx** [azerothcore/azerothcore-wotlk#948]
Description: Kel'Thuzad Phase 1 undermap mobs

Current behaviour: During Phase 1 in Kel'thuzad fight , mobs who appears in doodad_kelthuzad_window_portal01 and doodad_kelthuzad_window_portal02 are often in Undermap when  they move to targeted player , so players can't kill them.

Expected behaviour:  I think that's wrong position on waypoints in the mobs way or wrong position spawn under the ground.

Steps to reproduce the problem:

1.Go to Naxxramas , Kel'Thuzad last boss
2. Engage Kel'thuzad enter in the blue round 
3. Wait adds appear in the Portal 01 and 02 at the left of Kel'Thuzad when we are facing him.

Branch(es): master

AC hash/commit: 7329ad4

Operating system: Linux

Modules: /

Other Customizations: /

**Comment by FALL1N1** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/923 will fix it

**Comment by BarbzYHOOL** [comment]
This needs to be retested with the new commits and mmaps

**Comment by dunjeon** [comment]
The new maps did not correct the issue.  Banshees are *sometimes half in the floor. (although you can fight them now).

**Comment by FALL1N1** [comment]
@dunjeon try to spawn dummies or a random npc  then .mmap path from 1 angle of the room to the opposite and post a screenshot here

**Comment by dunjeon** [comment]
Understood. I should have it done this afternoon.

**Comment by dunjeon** [comment]
I may have it corrected. 4 test runs and all mobs are on the floor where they should be.  I want to do a few more tests and then I will post a PR.

**Comment by dunjeon** [comment]
Can I get some eyes on this?

**Youtube Video LInk:**
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Gs44jqOOV9A/0.jpg)](https://www.youtube.com/watch?v=Gs44jqOOV9A)

**Comment by dunjeon** [comment]
Confirmed (By the way) and still an issue after latest commit and fresh map build

**Comment by BarbzYHOOL** [comment]
@Dreaxxx and @Knindzagxg told me it looked fine from the video, but didn't test. Should we test now?

**Comment by dunjeon** [comment]
No =) I need to adjust it after the latest commit. I will finish it up this weekend

**Comment by Knindzagxg** [comment]
Everything works pretty good now.

**Comment by dunjeon** [comment]
Map Issue

![kt_path](https://user-images.githubusercontent.com/30352875/43746181-5cdc473a-99a8-11e8-97ec-23745ff2bff5.png)

**Comment by Nefertumm** [comment]
#1021 someone try this error with this vmaps, maybe related?

**Comment by Pondaveia** [comment]
This issue is related to [this forum post](https://github.com/azerothcore/forum/issues/25)

**Comment by Gierlappen** [comment]
Btw i did Naxx on this commit  9a9308a and i cannot reproduce this issue.
10 and 25 tested

**Comment by LukasVolgger** [comment]
I tried agian on this commit https://github.com/azerothcore/azerothcore-wotlk/commit/2788d495f9e861d5e6b7bf69378f9600bea513c4 and everything is fine here

**Comment by Si1ker** [comment]
This is still active is a concrete point of the vmap, where the mobs get under it, still active, PR linked to this issue seems to fix it and others as well.

**Comment by LukasVolgger** [comment]
@Si1ker Show me a screenshot where this happen?! I tried to reproduce this issue many Times and all is fine...
