### ISSUE TITLE
Instance Portals Not Working

### ISSUE THREAD

**Issue by Razzdazz11** [azerothcore/azerothcore-wotlk#9480]
### Current Behaviour

When walking into any instance portal, player character simply runs through the portal into the invisible barrier behind the portal.  Instance does not load and character can walk freely between the portal and the barrier behind. 

### Expected Blizzlike Behaviour

Characters should phase into instance upon touching portal.

### Steps to reproduce the problem

1. Go to any instance portal (5 man, raid, doesn't matter)
2. Walk in

### AC rev. hash/commit

2789d5b

### Operating system

Win10

### Custom changes or Modules

N/A

**Comment by Dude100** [comment]
I confirm
rev. 5df73f668052+

**Comment by Shineslippers** [comment]
Haapend to me after 2789d5b87784f2fb87eaa6c9ecdd79e92568faec. So probably issue pop up with some december updates.

**Comment by acidmanifesto** [comment]
Checking revision 5df73f6 which is absolute current at the time of me writing this:
Can not enter instances as well.

**Comment by Nyeriah** [comment]
Script library is not loading if you haven't got Eluna enabled.

**Comment by dantav** [comment]
This also affects Darnassus teleports.

**Comment by Nyeriah** [comment]
We are aware of this issue and we have managed to isolate it to https://github.com/azerothcore/azerothcore-wotlk/commit/51adbffae43aaf56e268e1cf2d39057f5c6a17c7

We have identified that unless you have the Eluna module enabled, most scripts will not load properly. That includes instance portals, training dummies, creature/boss scripts and so on.

We're working to address it as soon as possible.
