### ISSUE TITLE
Midsummer hostile for horde

### ISSUE THREAD

**Issue by zabiksandbox** [azerothcore/azerothcore-wotlk#949]
**Description**: NPC name = "Midsummer Celebrant" must have faction "35". Now event npc's is hostile for horde. 
In current DB faction = 84, it is  friendly for alliance, not for horde.
Same NPC spawned for alliance and horde, but faction set to 35 (alliance friendly).

**Current behaviour**: NPC  hostile for Horder

**Expected behaviour**: NPC Friendly for All (faction=35)

**Steps to reproduce the problem**:
1.  Go to Midsummer event in "Tranquillien" in Ghostlands 
2. See hostile npc

**Branch(es)**:  origin/master

**AC hash/commit**:   7329ad4  

**Operating system**:  Linux version 2.6.32-042stab126.2  (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Dec 6 18:08:29 MSK 2017

**Comment by Dreaxxx** [comment]
Confirmed

**Comment by pklloveyou** [comment]
DELETE FROM `creature_template` WHERE `entry` = "16781";
DELETE FROM `creature_template` WHERE `entry` = "25535";
INSERT INTO `creature_template` VALUES (25535, 0, 0, 0, 0, 0, 21955, 17612, 0, 0, '[DNT] 投掷火炬目标假人', '', '', 0, 60, 60, 0, 35, 0, 1, 1.14286, 1, 0, 104, 138, 0, 252, 1, 2000, 2000, 1, 33554944, 2048, 0, 0, 0, 0, 0, 0, 72, 106, 26, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 4, 1, 1.35, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 128, 'npc_midsummer_torch_target', 12340);
INSERT INTO `creature_template` VALUES (16781, 0, 0, 0, 0, 0, 16412, 16431, 16413, 16432, '仲夏节庆司仪', '', NULL, 9148, 40, 70, 0, 35, 1, 1, 1.14286, 1, 0, 252, 357, 0, 304, 1, 2000, 2000, 1, 32768, 2048, 0, 0, 0, 0, 0, 0, 215, 320, 44, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, '', 12340);

**Comment by pklloveyou** [comment]
DELETE FROM `creature_template` WHERE `entry` = "16781";
INSERT INTO `creature_template` VALUES (16781, 0, 0, 0, 0, 0, 16412, 16431, 16413, 16432, '仲夏节庆司仪', '', NULL, 9148, 40, 70, 0, 35, 1, 1, 1.14286, 1, 0, 252, 357, 0, 304, 1, 2000, 2000, 1, 32768, 2048, 0, 0, 0, 0, 0, 0, 215, 320, 44, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, '', 12340);

**Comment by zabiksandbox** [comment]
@pklloveyou, are you know about "UPDATE" oprator in mysql, or something?
Delete row for value of one column - is something like stupid.

**Comment by zabiksandbox** [comment]
@pklloveyou maybe u want "update `creature_template`  set `faction`='35' where `entry`='16781'"
why dell? :)

**Comment by pklloveyou** [comment]
@zabiksandbox My bad habits

**Comment by zabiksandbox** [comment]
@pklloveyou "LP - breaking the habbit" :)

**Comment by pklloveyou** [comment]
@zabiksandbox  LOL

**Comment by Stoabrogga** [comment]
Created PR #951 to fix the issue

**Comment by BarbzYHOOL** [comment]
How did this happen?? I think it was working before
