### ISSUE TITLE
Various Issues With Shellfish Traps in Desolace

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9496]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2469

Shellfish Traps in Desolace have an red crystal inside indicating that they are "bad" traps with an enemy spawning after clicking it.

![shellfish_trap](https://user-images.githubusercontent.com/62797536/144710948-7f7852ef-4063-49e6-a382-cebf4184dda2.jpg)

Tester: confirmed. Also, when you open one of these trapped cages, an empty loot window appears, and the enemy that spawns is neutral and doesn't attack you. Also, the red crystal respawns before the cage does.

The related quest is https://tbc.wowhead.com/quest=5421/fish-in-a-bucket.

https://user-images.githubusercontent.com/81782124/144713543-1c4c9690-ea16-474b-8840-adc67f19f934.mp4

Possibly a side effect of PR https://github.com/azerothcore/azerothcore-wotlk/pull/8572.

### Expected Blizzlike Behaviour

Shellfish Traps should stay empty even if they are "bad", no loot window should appear, and the spawned NPC should be hostile.

### Source
YouTube video from Classic shows empty trapped cage, no loot window appearing, and an immediately hostile NPC.
https://youtu.be/UvVaWEpuLww?t=71

### Steps to reproduce the problem

1. Dive in the coast near Shadowprey Village in Desolace
2. Watch out for red crystals in traps

### Extra Notes

Shellfish Trap Link 1: https://wowgaming.altervista.org/aowow/?object=176582
Shellfish Trap Link 2: https://wowgaming.altervista.org/aowow/?object=176635

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
Similar to https://github.com/azerothcore/azerothcore-wotlk/issues/8973
