### ISSUE TITLE
[Quest] Spinal Dus / Rotting Hearts

### ISSUE THREAD

**Issue by zabiksandbox** [azerothcore/azerothcore-wotlk#950]
**Description**: Quest items are not highlighted in the bag. When you hover over creature in the tooltip not highlighted the progress of the task.
This sql query: "UPDATE item_template SET bonding='4',  BagFamily='16384' WHERE entry='22642' OR entry='22641'" - add highlight to item in bag, but not add tooltip on creature.

Quest: 

**Expected behaviour**: Highlighted in bag like quest item, presence in the tooltip

**Steps to reproduce the problem**:
1. Take quest "Spinal Dus" or "Rotting Hearts"
2. Go kill.

**Branch(es)**:  origin/master

**AC hash/commit**:   7329ad4  

**Operating system**:  Linux version 2.6.32-042stab126.2  (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Wed Dec 6 18:08:29 MSK 2017

**Comment by imagionationeditor** [comment]
It was tested and there is no problem just drop rate to low

**Comment by BarbzYHOOL** [comment]
We don't understand your issue, edit it and I will reopen it.
