### ISSUE TITLE
Thwarting Kolkar Aggression objectives leave particles even if destroyed

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9513]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2468

During the quest "Thwarting Kolkar Aggression" in Durotar, when another player loots the quest objects right before you, the POI sparkles of the objects do not disappear with the object.
Tested with the item [Attack Plan: Sen'jin Village].
![kolkar_aggression_attak_plans](https://user-images.githubusercontent.com/62797536/144710616-26b260e9-3445-4781-bf02-31c3c7d0058e.jpg)
POI sparkles without quest object

Tester:

The issue is confirmed. Particles of objects is exist without objects. Quest [Thwarting Kolkar Aggression](https://wowgaming.altervista.org/aowow/?quest=786). Objects `3189`, `3190`, `3192`

@Nyeriah [commented](https://github.com/chromiecraft/chromiecraft/issues/2468#issuecomment-986205600) 
>This has to do with how objects are spawned I think. They don't despawn, they just become inactive. We probably need dynamic spawns to fix this.

![WoWScrnShot_120521_130344](https://user-images.githubusercontent.com/85256266/144742097-8af0b26b-0e29-4305-829a-721278435934.jpg)

### Expected Blizzlike Behaviour

After looting quests objects during the quest "Thwarting Kolkar Aggression", the objects POI sparkles should disappear for other playes on the quest and re-appear with the objects respawn.

### Steps to reproduce the problem

.go ga 12390
use object
.q a 786

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
Has to do with Dynamic Spawning. Since we don't destroy gameobject but re-use their properties only disabling them, the client knows there's something there, just the player can't see it.
Implementing Dynamic spawn will solve this and many other problems such as gameobject/creature's pooling.

**Comment by UltraNix** [comment]
Dynamic spawning has nothing to do with it. When you click on it, the object in real does not disappear, but only changes visual and it seems to be invisible.

**Comment by Nyeriah** [comment]
> Dynamic spawning has nothing to do with it. When you click on it, the object in real does not disappear, but only changes visual and it seems to be invisible.

Yes, that's what he meant, we currently don't "despawn" gameobjects, they just go invisible. Once we get dynamic spawns we'll be able to properly despawn them (destroy and remove from world completely until another instance of the object is created during respawn)

**Comment by UltraNix** [comment]
Not in this case, because this object should not be despawned.

**Comment by UltraNix** [comment]
@azerothcore/testers Does anybody can test it on retail?
