### ISSUE TITLE
[boss] drop bug

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#954]
buged ! drop item  [Emblem of Triumph] on 10 and 25 man instance the obsidian sanctum

boss:

http://www.wowhead.com/npc=30449/vesperon

http://www.wowhead.com/npc=30452/tenebron

http://www.wowhead.com/npc=30451/shadron

Branch(es): master

AC hash/commit: 7329ad4

Operating system: Windows server 2012

**Comment by Dreaxxx** [comment]
That's not a bug since the 3.3 release.

**Comment by Hir0shi** [comment]
give me for information ? since is 3.3.5! need to fixed for dro

**Comment by FALL1N1** [comment]
you need to handle this trough the core since the emblem rewarding is dynamic, e.g 3alive drakes + sapph = 3 emblems, 2 drakes = 2.. etc

**Comment by Dreaxxx** [comment]
You have to add a new Insert in the creature loot template with the lootid of the drake in 25 , here entry of vesperon 25 is the field "difficulty_entry_1" so 31535
