### ISSUE TITLE
/Data/maps/0004331.map' is from an incompatible clientversion. Please recreate using the mapextractor

### ISSUE THREAD

**Issue by zhangran2616** [azerothcore/azerothcore-wotlk#9545]
### Current Behaviour

![image](https://user-images.githubusercontent.com/6472032/144965876-55bbb8b0-fd3a-4d47-b82c-052b9f2d8df3.png)

### Expected Blizzlike Behaviour

successful

### Steps to reproduce the problem

run worldserver script

### AC rev. hash/commit

![image](https://user-images.githubusercontent.com/6472032/144965923-bf413419-d81d-492e-a321-22932fcf7fdd.png)

### Operating system

ubuntu20.04

**Comment by zhangran2616** [comment]
![image](https://user-images.githubusercontent.com/6472032/144966014-9a65a6d3-a989-4a6d-8e54-940cbaba6928.png)

download from here

**Comment by Eronox** [comment]
Just guessing: 
I think you're on a older core version trying to use newer maps. 
Try update the core or test with older map version download

**Comment by zhangran2616** [comment]
> Just guessing:
> I think you're on a older core version trying to use newer maps.
> Try update the core or test with older map version download

thank you 。 I just solved the problem
