### ISSUE TITLE
Custom modules are not executing

### ISSUE THREAD

**Issue by jarrodjeffi** [azerothcore/azerothcore-wotlk#9575]
### Current Behaviour

It appears custom modules are not being executed when I use my custom item as seen in https://youtu.be/2UVxelGeQZc.

### Expected Blizzlike Behaviour

Before the latest merge of AzerothCore into my server's branch the item would execute its `OnUse` behaviour distributing the items it contains (it is not a container) and then deleting one instance of the item.

### Steps to reproduce the problem

Create a custom module such as an `ItemScript` which can be reproduced as follows:
1. Create an item with a corresponding `ItemScript`.
2. Link that `ItemScript` to the `item_template` using the `ScriptName` field.
3. On use the item's script doesn't run.

### AC rev. hash/commit
Last commit merged: 846487acaa9f4b604af0628bca5685be6815f9ba

```
AzerothCore rev. 94b93cd94c8e 2021-12-05 08:50:44 +1100 (wobgob branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80027
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-81-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_12_04_03
Using Character DB Revision: 2021_09_25_00
Using Auth DB Revision: 2021_06_17_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-colonist
- mod-hardcore
- mod-level-up
- mod-loot-box
- mod-player-settings
```

### Operating system

Ubuntu 20.04

### Custom changes or Modules

Modules are listed in the AC rev. hash/commit section. All modules have been made in-house. Custom changes is allowing multiple resource tracking.

**Comment by jarrodjeffi** [comment]
It doesn't appear any of my modules are working. I'll investigate further.

**Comment by adink1** [comment]
Is mod-custom-login invalid because of this?

**Comment by jarrodjeffi** [comment]
> Is mod-custom-login invalid because of this?

I assume so as all our custom modules are invalid.

**Comment by jarrodjeffi** [comment]
There's now a $30 bounty on this issue https://www.bountysource.com/issues/103810507-custom-modules-are-not-executing

**Comment by jarrodjeffi** [comment]
Just an update, we found some modules working like `mod-level-up` which gives level up rewards to players, `mod-player-settings` which adjusts dungeon difficulty based on number of players are working, but `mod-hardcore` which applies a hardcore aura at character creation, and `mod-loot-box` which is an `ItemScript` as described in the issue don't work. You can find our custom modules at https://github.com/wobgob/azerothcore-wotlk/tree/wobgob/modules.

**Comment by acidmanifesto** [comment]
@jarrodjeffi Azerothcore staffer here, we are aware of the issue. Its due to our current wip progress we are making with moving the core forward. It will be working pretty soon. Please revoke the bounty as unfortunate as this moment is inbetween commits, it is being worked on by fellow azerotcore devs.

**Comment by Winfidonarleyan** [comment]
@jarrodjeffi can test with #9598?

**Comment by yuanf225** [comment]
hi @Winfidonarleyan   #9598 Can it also solve the problem that AIO cannot be used? If it can, I can test it soon
