### ISSUE TITLE
[BUG] Quest  [It's All Fun and Games]

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#958]
remove - there is no problem

**Comment by Dreaxxx** [comment]
Can't reproduce the bug

**Comment by imagionationeditor** [comment]
@Hir0shi  It was tested and there is no problem

**Comment by Hir0shi** [comment]
yes  i so sry ! this is fixed!

**Comment by Vynel** [comment]
exactly, i tested and there is no problem friends
