### ISSUE TITLE
Runecloth Donation Quests Incorrectly Available Without Prerequisites

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#9591]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2508

Currently, all four cloth donation quests in the capital cities are available.

![WoWScrnShot_120821_095556](https://user-images.githubusercontent.com/62797536/145179003-86571229-cdd5-4f07-a68c-b409fe81e7ba.jpg)
Screenshot from ChromieCraft

Tester: confirmed - checked cloth quartermasters on both sides and they all offered the Runecloth quest immediately.
Affected quest IDs are ID 7795, 7800, 7805, 7811, 7818, 7823, 7824, 7836, 10357, 10362. None have a previous quest ID set, although for these where the pre-req is a group of 3, not sure it would use that in any case.

![WoWScrnShot_120821_233332](https://user-images.githubusercontent.com/81782124/145214250-6e9d291d-9137-4539-82ce-587293e6c6c4.jpg)
![WoWScrnShot_120821_233407](https://user-images.githubusercontent.com/81782124/145214258-47ffa1db-63f3-4c2e-aa10-e7b89a4826bd.jpg)
![WoWScrnShot_120821_233452](https://user-images.githubusercontent.com/81782124/145214263-47cd2fac-754b-4e4b-aa7c-2af784ce2adc.jpg)
![WoWScrnShot_120821_234310](https://user-images.githubusercontent.com/81782124/145214509-d846a043-4a1f-48a9-aff8-37658893ba58.jpg)
![WoWScrnShot_120821_234345](https://user-images.githubusercontent.com/81782124/145214515-50d5cdf8-def2-4b3d-99db-1f5c4bfa4dfc.jpg)
![WoWScrnShot_120821_234420](https://user-images.githubusercontent.com/81782124/145214520-dc686324-7d4a-4dcf-ab59-3bc8e6dbca34.jpg)

### Expected Blizzlike Behaviour

The quests "A Donation of Runecloth" should only be available after you have completed the quests for Wool, Silk and Mageweave for that corresponding faction.

After you have done "A Donation of Runecloth", you unlock the repeatable Runecloth quests.

### Source

Screenshot from official TBC Classic:
![WoWScrnShot_120821_095634](https://user-images.githubusercontent.com/62797536/145179534-e4c9aefd-db3f-427b-98c6-d0399123eb74.jpg)

"Just a heads up, you need to complete the wool, silk, mage weave in order to unlock the rune cloth,." - https://tbc.wowhead.com/quest=7818/a-donation-of-runecloth#comments:id=5211706

"Also note that you cannot receive this quest until you have completed the first 3 he has to offer. A Donation of Wool, A Donation of Silk, and A Donation of Mageweave. After completing these 3, the runecloth quest will become available." - https://tbc.wowhead.com/quest=7800/a-donation-of-runecloth#comments:id=15125

"As people have said: You have to complete the three other donations, (Wool - Silk - Mageweave) Before you can donate Runecloth." - https://tbc.wowhead.com/quest=7800/a-donation-of-runecloth#comments:id=136519

More evidence can be found on Wowhead:
https://classic.wowhead.com/quest=7795/a-donation-of-runecloth#comments

Even more evidence in a factsheet
http://www.giddygamer.com/wow/content/reputation/cloth_quests.pdf

### Steps to reproduce the problem

1. Go to a cloth quartermaster in any capital city where you have not done any cloth donation quests.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Underminus** [comment]
I presume ChromieCraft are trying to back patch the 3.3.5a server? If not then from 3.0.2 the requirement was removed.

**Comment by Kitzunu** [comment]
AzerothCore is going for 3.3.5a

**Comment by Kitzunu** [comment]
Please dont use TBC or Classic as sources for these types of things.

**Comment by FrancescoBorzi** [comment]
> I presume ChromieCraft are trying to back patch the 3.3.5a server? If not then from 3.0.2 the requirement was removed.

yes, but for everything that is NOT supposed to be on 3.3.5a (default AC) we have a separate repository:

https://github.com/azerothcore/mod-progression-system

this way we keep default AzerothCore to 3.3.5a and use the other repo to allow servers (such as ChromieCraft) to easily change the content patch
