### ISSUE TITLE
[Quest] Bug  [Shadow Vault Decree]

### ISSUE THREAD

**Issue by Hir0shi** [azerothcore/azerothcore-wotlk#961]
BUG QUEST!
http://www.wowhead.com/quest=12943/shadow-vault-decree

Cant attack target faction is bug! and can not use spell item quest  [Shadow Vault Decree] to target!

http://i64.tinypic.com/jl5tfp.png

Branch(es): master

AC hash/commit: 80f81d7

**Comment by Dreaxxx** [comment]
I haven't got problem with the quest

**Comment by BarbzYHOOL** [comment]
0 valid issue for Hiroshi until now

**Comment by Hir0shi** [comment]
this Dreaxxx  fak user!?

dreaxx ? what is u version AZ!

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/258

**Comment by BarbzYHOOL** [comment]
@Hir0shi test this https://github.com/azerothcore/azerothcore-wotlk/issues/258 and report on that issue please
