### ISSUE TITLE
Stonard Explorer is flying over water instead of walking

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9619]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2512

Stonard Explorers that patrol through the Swamp of Sorrows begin jumping as soon as they are walking into water.
I discovered this NPC near the coast of the zone.

![WoWScrnShot_120821_170453](https://user-images.githubusercontent.com/62797536/145243179-e2656139-ce4d-4649-95c8-36daa4659b47.jpg)

Tester:

The issue is confirmed. [Stonard Explorer](https://wowgaming.altervista.org/aowow/?npc=862) is flying over water instead of walking
`DB GUID: 37598, current GUID: 3183.Entry: 862.`

![WoWScrnShot_120921_203313](https://user-images.githubusercontent.com/85256266/145448032-cf6dd145-c176-4bfb-a65d-5e414713aa14.jpg)

### Expected Blizzlike Behaviour

Stonard Explorers should walk through water on their patrol.

### Steps to reproduce the problem

.go c 37598

### Extra Notes

NPC: https://wowgaming.altervista.org/aowow/?npc=862

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by avarishd** [comment]
As of rev. df6dcd8888cd8cb90216b4f3d1212e1e0cc24726 this seems to be fixed

<details>

https://user-images.githubusercontent.com/46330494/219794224-debab4da-d758-4de4-a17f-73dad2908ed8.mp4

https://user-images.githubusercontent.com/46330494/219794228-4e69ab38-dfa9-4cce-8df3-b8f6d8a96f82.mp4

</details>
