### ISSUE TITLE
Deep Wounds does not proc when you crit with ranged weapons

### ISSUE THREAD

**Issue by fragcamp** [azerothcore/azerothcore-wotlk#962]
**Description**:
Deep wounds does not proc if you crit with a ranged weapon (thrown, bow, gun)
**Current behaviour**: Tell us what happens
If your ranged attack crits and you have the deep wounds talent, the deep wounds will not proc on your target.
**Expected behaviour**: Tell us what should happen instead
Deep wounds should proc with ranged weapons.
**Steps to reproduce the problem**:

1. Make a warrior
2. Skill Deep Wounds talent
3. Equip a ranged weapon
4. Attack an enemy player with the ranged weapon and wait for a crit
5. When you crit you'll see that deep wounds did not proc on your target.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/dd291e0de69a40130473fb54f6088096059d5e32
**Operating system**:  
Win64
**Modules**:  Are you using modules? if yes, list them
None
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by BarbzYHOOL** [comment]
https://github.com/TrinityCore/TrinityCore/issues/20148

**Comment by lineagedr** [comment]
@BarbzYHOOL Seems valid, http://www.wowhead.com/forums&topic=83191/should-all-prot-warriors-be-specced-in-deep-wounds#p902697

**Comment by dunjeon** [comment]
DBC Spell ID 12834:

Deep Wounds
**Requires Melee Weapon**
Your critical strikes cause the opponent to bleed, dealing 16% of your **melee** weapon's average damage over 6 sec.

There isn't anything to suggest that it should work with a ranged weapon.

**Comment by BarbzYHOOL** [comment]
Yes, I think this issue is... invalid

**Comment by BarbzYHOOL** [comment]
well so, not suitable for blizzlike, but okay for a custom server, make a module :P
