### ISSUE TITLE
Eliza not spawning (quest Bride of the Embalmer)

### ISSUE THREAD

**Issue by chrooti** [azerothcore/azerothcore-wotlk#9623]
### Current Behaviour

The quest to make her spawn (Digging through the dirt) can be completed, but Eliza and her guards don't spawn.

### Expected Blizzlike Behaviour

Eliza and her guards spawn.

### Steps to reproduce the problem

1. Go to the quest location (Duskwood  near Abercrombie's shack)
2. Complete the digging through the dirt quest
3. Eliza doesn't spawn

### AC rev. hash/commit

chromiecraft@fc4b5a9

### Operating system

Arch Linux x64 (client)

**Comment by Shineslippers** [comment]
This issue is not related to quest itself. It's about update of script loader

https://user-images.githubusercontent.com/85256266/145626372-ce3895b2-7c72-42b7-8a1f-24ca73590a9d.mp4
