### ISSUE TITLE
Mage's Fingers of Frost talent is proc on hit

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9634]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2537

FoF right now is both proccing and consuming on-hit rather than on-cast. This might not mean a lot at first glance but it should allow mages to react and plan quicker when a proc occurs, specially in pve where travel distances can be huge, resulting in the loss of the FoF "Ghost Charge" uses since you can't really predict when the consumes happen.

Tester:

The issue is confirmed. Mage's [Fingers of Frost](https://wowgaming.altervista.org/aowow/?spell=44543) talent is proc and consume on hit

https://user-images.githubusercontent.com/85256266/145609471-a2384f37-a377-4b3c-9d31-2a80f8f123b7.mp4

### Expected Blizzlike Behaviour

**_Both the trigger and the consume should be consumed on cast_**. Just a reminder that the cast that procs FoF should not consume nor benefit from it (unless the cast that procs the talent isn't casted during a previous FoF I'd assume). 

Keep in mind that the famous Ghost charge should still be possible even wit this change, meaning a 3rd instant spell should benefit from FoF if this spell is casted right after the spell that consumes the last stack of the talent. Getting the ghost charge to work seems like the tricky part because from what I read it happened either due to latency or maybe the spell queue system that prob snapshotted the buff (wich doesn't seem to be implemented here at all).

**Retail video of the Proc happening on cast can be seen [here](https://youtu.be/8ET2Ct9_Ma8?t=24), it happens @ 26 seconds just slow down the video to 0.25 secs.** If you go further along the video there's plenty of examples of the talent being triggered and consumed on cast.

 Example of ghost charge use: frostbolt (procs fingers) > frostbolt (consumes 1/2 FoF) > frostbolt + ice lance/deep freeze/brain freeze (consumes last stack while both benefitting from the crit increase).

### Source

https://web.archive.org/web/20101204052143/http://www.worldofwarcraft.com/patchnotes/patch3p3.html
Patch 3.3 "Fingers of Frost: This talent now triggers immediately on casting a spell rather than being delayed until the spell strikes the target."

https://www.mmo-champion.com/threads/677129-Fingers-of-Frost-Change
"Also, it wont affect the ghost charge because this is already how the removal of the buff works. The buff fades on spell cast, not hit. Ghost charge is all latency."

### Steps to reproduce the problem

.go c 48335
.aura 44545
.cast 116

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=44545

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
Can we even do on cast right now? I believe https://github.com/azerothcore/azerothcore-wotlk/issues/9177 is needed to fix all of these things
