### ISSUE TITLE
Hunter's quiver replace melee weapon model on bow usage and it's disappear on loot

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9636]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2520

After looting mobs, all equipped weapons on my lvl 9 female Orc Hunter disappear (as an animation) in Eversong Woods until I attack another mob or press "Z". The bow, arrows, and melee weapon all are hidden while/after looting. 

Tester:

The issue is confirmed. If target is killed by range weapon after loot there is no weapon model shown. On video from TBC you can see instead of quiver there is always MH weapon model.

https://user-images.githubusercontent.com/85256266/145622621-ebd68aab-a157-43da-9505-fd3323b9590e.mp4

### Expected Blizzlike Behaviour

Equipped weapon is visible on back or in hand while/after looting. 

### Source

https://youtu.be/kM4YjdL2lF8?t=11210

### Steps to reproduce the problem

create hunter
kill something in starter zone from bow
loot killed creature

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
@Shineslippers Can you find an evidence from Wotlk retail? That problem looks like clientside  and maybe Blizz fixed that later - that's why I need a video from wotlk era.

**Comment by Shineslippers** [comment]
My bad. It's directly related to bow and quiver. Crossbows behavior is ok. Quiver is replacing Melee Weapon model and after loot it's disapear. There is now quiver in this video at all https://youtu.be/31OlMogSrkM?t=52

https://user-images.githubusercontent.com/85256266/145645001-14fb962d-ceaa-4478-a275-3ffe2ddd5f67.mp4

**Comment by UltraNix** [comment]
There is nothing I can do with it - it's clientside. Client send Sheathe opcode to server and this is how it looks.
