### ISSUE TITLE
Item Annihilator 

### ISSUE THREAD

**Issue by Plasmashield** [azerothcore/azerothcore-wotlk#9646]
### Current Behaviour

https://wowgaming.altervista.org/aowow/?spell=16928
https://wowgaming.altervista.org/aowow/?spell=16928
Procs from different players doesn't stack. The debuff from one player just overwrites by the proc from a second player.
Also, not sure but proc rate feels strange. After getting 3 stack i lose them in next 45 seconds, spamming auto attack and devastate every gcd. Maybe it didn't proc by some abilities or maybe im wrong.

### Expected Blizzlike Behaviour

Procs from different players should stack into one debuff 

### Source

I cannot find convincing videos, only some comments or forums. Rather, it is an obvious mechanic. 

### Steps to reproduce the problem

1 find two players with Annihilator 
2 attack someone

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

win10

**Comment by Plasmashield** [comment]
Also, these items has the same mechanics:
https://wowgaming.altervista.org/aowow/?item=13204
https://wowgaming.altervista.org/aowow/?item=13286
It have the same debuff, so it should also stack with each other
But i didn't test them yet

**Comment by Luckdemon2** [comment]
Both of them do also have the same bug where other players overwrite the already built stacks on an enemy.
