### ISSUE TITLE
Either Heroic instances aren't resetting when they should, or the calendar is not displaying reset dates correctly

### ISSUE THREAD

**Issue by oblivion-hymns** [azerothcore/azerothcore-wotlk#966]
**Description**: As an example, this morning I had several Heroic 5-man instance locks scheduled to expire, according to my calendar, at 4:59 AM. I logged in at 6 AM only to find that the reset time had extended to (time of log in). This happens every time I log in and out or restart the server -- the time just keeps extending infinitely. The only way I can reset my Heroic instance locks is to use the GM command.

I have been digging around in the source quite a bit, and if I clear the tables myself it does seem to clear the instance locks, however the `instance_reset` table continuously resets itself -- not sure if that behavior is intended but it seems like in the current scenario, instance locks will just keep expiring forever.

I am a professional software engineer (but not a professional QA! lol), so if you would like to point me in the direction of where I might be able to fix this I would be willing to give it a go in my free time.

**Current behaviour**: When logging in, Heroic instance locks seem to extend to the time at which I logged in. They never actually expire. This happens regardless of whether the server is down or up when the instance locks should be expiring. If they do expire, it's not displayed on the calendar.

**Expected behaviour**: When Heroic instance locks reach their time of expiry, those instances should expire.

**Steps to reproduce the problem**:

1. Get yourself locked to a Heroic instance
2. Wait until the time displayed on your calendar (or cheat and set your server's time to some time after that value)
3. Log in to the game
4. Heroic instance expiry times have updated to the time at which you just logged in (for example, this morning for me they had all updated to 6:01 AM, although I have been testing this and playing around with it for several days now).

**Branch(es)**: master

**AC hash/commit**:  Still happening in c15444a18e9ddd6b297acbbbff2e51d1782a96d7

**Operating system**:  Windows 10

**Modules**:  Only azerothcore/mod-vas-autobalance

**Other Customizations**: None

**Comment by BarbzYHOOL** [comment]
Maybe related to this recent commit :( https://github.com/azerothcore/azerothcore-wotlk/pull/880

**Comment by oblivion-hymns** [comment]
Funnily enough, the last piece of code mentioned in that thread:

```
while (t < now)
               t = uint32(((t + MINUTE) / DAY * DAY) + period + diff);
```

Is exactly the piece I was suspecting most. However without knowing anything about the codebase, I wasn't about to just change it because I have little idea what might happen.

**Comment by oblivion-hymns** [comment]
I can confirm that this does indeed fix the problem. The loop I mentioned in the post above, referenced in #880 , is what is causing this to happen. I removed the loop in a custom build, built for release, changed absolutely nothing else other than just deleting that loop, and now it works fine. Tested by running Heroic Azjol-Nerub to completion (causing it to expire as expected, tomorrow at 4:59 AM). I then shut down my client and world server, set the server's and client's time to 7:00 AM tomorrow, and ran the worldserver again. It immediately found and reset the instances correctly.

**Comment by oblivion-hymns** [comment]
Oh no, wait, I started the server and now the bug is back! I guess it's not totally fixed, then.

**Comment by BarbzYHOOL** [comment]
np, it can be useful

**Comment by AyaseCore** [comment]
Yes, that's why I suggested another way at #880

**Comment by BarbzYHOOL** [comment]
Any news?

**Comment by Stoabrogga** [comment]
Sorry, had no time to do any further tests the past few days. But today I restarted the server and still the heroic instance did not reset, same message "Your instance lock is scheduled to expire in .". Reset time in the DB now said 1537761600, which should be 24th September... something's really wrong here.

**Comment by BarbzYHOOL** [comment]
tala's commit has been tested :)

**Comment by Rochet2** [comment]
@BarbzYHOOL @talamortis Hmm looks to me like https://github.com/azerothcore/azerothcore-wotlk/commit/c4a6445a232a3cd8fe8d1e636f91b98c68900943 deletes all instance reset timers, which means resettime is not taken into account at all after restart.
In practice that means that restart instances are completely reset: no extensions, no warnings etc.
All DB data is deleted on startup, so basically makes the DB table useless.. hmm.
While this would fix the issue with things not resetting, it introduces an issue where restarting will do a hard reset. Not sure if that is something people want.

**Comment by talamortis** [comment]
Its used for this conf option as ive used this table before - https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/worldserver/worldserver.conf.dist#L2324

**Comment by BarbzYHOOL** [comment]
Reverted :(

**Comment by a4501150** [comment]
From my investigation...

In core, it assumes that the server IS running when reset datetime(instance.reseHour) was reached. 
InstanceSaveMgr.cpp:

```
 // calculate new global reset times for expired instances 
and those that have never been reset yet

InstanceSaveManager::LoadResetTimes() 
```

Thus it supposes not to reset heroic/raid instances when the server started after desired reset datetime. and simply re-schedule resetting at next available DateTime. (this is terrible if the server crashed just before reset hour and you re-start server after reset hour, then your playes has new fresh instance CDs)

the raid reset seems good however the heroic 5-man instance resetting totally fucked up and may need update whole save system..(it would always extend if you logged out)

**Comment by BarbzYHOOL** [comment]
Just a note, this is not a critical issue because it mostly occurs when we keep rebooting the server (as in development or playing in solo)

**Comment by Nefertumm** [comment]
Why we are not doing what trinity did? https://github.com/TrinityCore/TrinityCore/blob/42edba699dc8f47084756a4e3ab7d85ea96e81fb/src/server/game/Instances/InstanceSaveMgr.cpp#L416

**Comment by FrancescoBorzi** [comment]
@Nefertumm feel free to import that :)
