### ISSUE TITLE
OnFirstLogin hook not executing

### ISSUE THREAD

**Issue by jarrodjeffi** [azerothcore/azerothcore-wotlk#9663]
### Current Behaviour

Our hardcore module which applies an aura using an `OnFirstLogin` script doesn't execute.

### Expected Blizzlike Behaviour

`OnFirstLogin` scripts should execute.

### Steps to reproduce the problem

1. Create a `PlayerScript` with an `OnFirstLogin` script
2. Login with a fresh character
3. The script does not execute

### AC rev. hash/commit
Latest commit: b0a98b6ec9b4a94cb133a19163b6bec6f511e963

AzerothCore rev. 0c046c8466d7 2021-12-12 08:46:14 +1100 (wobgob branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80026
Using CMake version: 3.16.3
Compiled on: Linux 5.4.72-microsoft-standard-WSL2
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS deDE zhTW esES
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_12_11_07
Using Character DB Revision: 2021_10_14_00
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-colonist
- mod-hardcore
- mod-level-up
- mod-loot-box
- mod-player-settings

### Operating system

Ubuntu 20.04

### Custom changes or Modules

Modules are listed in the AC rev. hash/commit section. All modules have been made in-house. Custom changes is allowing multiple resource tracking.

**Comment by adink1** [comment]
#9281 After that, mod-custom-login has been unavailable. I thought #9598 can fix this problem, but it still doesn't work..

**Comment by hahalmtdhl** [comment]
Through the test, the print value of the newly created character is 0, not 32, but characters at_ login=32。
std::cout << pCurrChar->m_atLoginFlags << std::endl;

**Comment by Nyeriah** [comment]
Thanks for the headsup. Please try it: https://github.com/azerothcore/azerothcore-wotlk/pull/9686
