### ISSUE TITLE
[windows] CMake not finding boost on certain generators

### ISSUE THREAD

**Issue by iraizo** [azerothcore/azerothcore-wotlk#9664]
### Current Behaviour

This behaviour is only happening on windows, when generating the project files using CMake with a different generator on windows other than VS2019 (or VS in general, i havent tested the other versions), it will not find boost. I tried this out with make and ninja now and it works fine on linux so this seems to be a windows only bug.

### Expected Blizzlike Behaviour

CMake should find boost not dependant on the generator used.

### Steps to reproduce the problem

1. `cmake -G "Ninja"`

### AC rev. hash/commit

24a56938e555c107c63fe8ebd875cab8ff5a4dd5

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
iirc we don't handle finding boost. That is left to the one that is shipped with CMake install.

So might just be an issue with CMake itself.

cc @Winfidonarleyan

**Comment by Kitzunu** [comment]
What version of CMake do you use?

**Comment by iraizo** [comment]
> iirc we don't handle finding boost. That is left to the one that is shipped with CMake install.
> 
> So might just be an issue with CMake itself.
> 
> cc @Winfidonarleyan

Well if boost wouldn't be found with cmake on other generators im pretty sure this wouldve already been handled is my guess

**Comment by iraizo** [comment]
> What version of CMake do you use?

the newest one available

**Comment by Winfidonarleyan** [comment]
Please use guide for install boost for win

**Comment by iraizo** [comment]
That.. has nothing to do with the issue described

**Comment by Winfidonarleyan** [comment]
> That.. has nothing to do with the issue described

What version of Boost do you have installed?

**Comment by Kitzunu** [comment]
AzerothCore does not handle the way CMake finds Boost.

TC removed it here https://github.com/TrinityCore/TrinityCore/commit/e5b12a76dcd3348ff5ddc3e79da4d4a9f6837351
 to rely on the one CMake ships with. And thus, we never ported it as CMake does takes care of it.

So, this is an issue with CMake and nothing we can do about it.
