### ISSUE TITLE
Taste for blood procs when rend damage is absorbed.

### ISSUE THREAD

**Issue by fragcamp** [azerothcore/azerothcore-wotlk#967]
**Description**:
Taste for blood procs when rend damage is absorbed
**Current behaviour**: Tell us what happens
Taste for blood procs when rend damage is absorbed
**Expected behaviour**: Tell us what should happen instead
Taste for blood should only proc if it does damage to target.
**Steps to reproduce the problem**:

1. Cast Rend on a target with a shield spell on
2. See that taste for blood procs when rend is absorbed.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 
master

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/2c7485c11c4e62479a61d3b2e28fd84677e2fe40
**Operating system**:  
Win64
**Modules**:  Are you using modules? if yes, list them
None
**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.
None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by BarbzYHOOL** [comment]
Which class uses rend?

**Comment by talamortis** [comment]
warrior

**Comment by fragcamp** [comment]
Also here's retail confirmation: https://youtu.be/vFQl7JStwu4?t=161

**Comment by talamortis** [comment]
can not reproduce. Will close unless reported again.
