### ISSUE TITLE
Phase 1 DK Quest Line - Lich King Whispers Not Scripted

### ISSUE THREAD

**Issue by Voxstrasza** [azerothcore/azerothcore-wotlk#9679]
### Current Behaviour

Lich King doesn't whisper players engaging in combat with Citizen of Havenshire (NPCs 28576, 28577) during quest If Chaos Drives, Let Suffering Hold The Reins (ID 12678). 

### Expected Blizzlike Behaviour

According to sniffs, The Lich King (NPC 28765) whispers the player one of 16 possible line and has audio attached to it.  This NPC is invisible and spawned into a grain silo nearby the quest area.  Also according to sniffs, this is handled by spells (https://www.wowhead.com/search?q=LichKingDK0#uncategorized-spells)

What's supposed to happen:  When the player is on the quest 12678 and attacks creatures 28576 and 28577, The Lich King will whisper the player and play an audio file (I have added these in SQL below).   I believe it to be on a cooldown so that the Lich King won't whisper you every time, rather every other time.  Video data can help confirm timing.

As this NPC is supposed to be invisible and only spawned in for the sake of whispering/taunting the player, he shouldn't have a visible aura pointing to its existence (it's visible underneath the building it's spawned in) - SQL below removes it

Potentially handled a similar way to this issue: TrinityCore/TrinityCore#25683

But this is not handled on a timer, rather when the player engages Citizen of Havenshire.

<details>
<summary> Sniff </summary>

> ServerToClient: SMSG_QUERY_CREATURE_RESPONSE (0x2914) Length: 138 ConnIdx: 1 Time: 11/19/2021 10:42:11.735 Number: 24690
> Entry: 28765
> Leader: False
> [0] Name: The Lich King
> Type Flags: 36 (BossMob, MoreAudible)
> Creature Type Flags 2: 0
> CreatureType: 10 (NotSpecified)
> CreatureFamily: 0 (None)
> Classification: 1 (Elite)
> [0] ProxyCreatureID: 0
> [1] ProxyCreatureID: 0
> DisplayIdCount: 2
> TotalProbability: 1
> [0] CreatureDisplayID: 169
> [0] DisplayScale: 1
> [0] Probability: 0
> [1] CreatureDisplayID: 23767
> [1] DisplayScale: 1
> [1] Probability: 1
> HpMulti: 2000
> EnergyMulti: 1
> QuestItems: 0
> CreatureMovementInfoID: 0
> HealthScalingExpansion: 2 (WrathOfTheLichKing)
> RequiredExpansion: 0 (WorldOfWarcraft)
> VignetteID: 0
> UnitClass: 1 (Warrior)
> CreatureDifficultyID: 30826
> WidgetSetID: 0
> WidgetSetUnitConditionID: 0
> 
> ServerToClient: SMSG_SPELL_START (0x2C3A) Length: 128 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43861
> (Cast) CasterGUID: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CasterUnit: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CastID: Full: 0xBC30F04C2038D943003513000297C8FF Cast/3 R3132/S13587 Map: 609 Low: 43501823
> (Cast) OriginalCastID: Full: 0x0
> (Cast) SpellID: 58213 (58213)
> (Cast) (Visual) SpellXSpellVisualID: 0
> (Cast) (Visual) ScriptVisualID: 0
> (Cast) CastFlags: 10
> (Cast) CastFlagsEx: 1048576
> (Cast) CastTime: 0
> (Cast) (MissileTrajectory) TravelTime: 0
> (Cast) (MissileTrajectory) Pitch: 0
> (Cast) Ammo.DisplayID: 0
> (Cast) DestLocSpellCastIndex: 0
> (Cast) (Immunities) School: 0
> (Cast) (Immunities) Value: 0
> (Cast) (Predict) Points: 0
> (Cast) (Predict) Type: 0
> (Cast) (Predict) BeaconGUID: Full: 0x0
> (Cast) HitTargetsCount: 0
> (Cast) MissTargetsCount: 0
> (Cast) HitStatusCount: 0
> (Cast) MissStatusCount: 0
> (Cast) RemainingPowerCount: 0
> (Cast) HasRuneData: False
> (Cast) TargetPointsCount: 0
> (Cast) (Target) Flags: 2 (Unit)
> (Cast) (Target) HasSrcLocation: False
> (Cast) (Target) HasDstLocation: False
> (Cast) (Target) HasOrientation: False
> (Cast) (Target) hasMapID : False
> (Cast) (Target) Unit: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> (Cast) (Target) Item: Full: 0x0
> (Cast) (Target) Name: 
> 
> ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 139 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43862
> (Cast) CasterGUID: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CasterUnit: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CastID: Full: 0xBC30F04C2038D943003513000297C8FF Cast/3 R3132/S13587 Map: 609 Low: 43501823
> (Cast) OriginalCastID: Full: 0x0
> (Cast) SpellID: 58213 (58213)
> (Cast) (Visual) SpellXSpellVisualID: 0
> (Cast) (Visual) ScriptVisualID: 0
> (Cast) CastFlags: 264
> (Cast) CastFlagsEx: 1048592
> (Cast) CastTime: 954803809
> (Cast) (MissileTrajectory) TravelTime: 0
> (Cast) (MissileTrajectory) Pitch: 0
> (Cast) Ammo.DisplayID: 0
> (Cast) DestLocSpellCastIndex: 0
> (Cast) (Immunities) School: 0
> (Cast) (Immunities) Value: 0
> (Cast) (Predict) Points: 0
> (Cast) (Predict) Type: 0
> (Cast) (Predict) BeaconGUID: Full: 0x0
> (Cast) HitTargetsCount: 1
> (Cast) MissTargetsCount: 0
> (Cast) HitStatusCount: 1
> (Cast) MissStatusCount: 0
> (Cast) RemainingPowerCount: 0
> (Cast) HasRuneData: False
> (Cast) TargetPointsCount: 0
> (Cast) (Target) Flags: 2 (Unit)
> (Cast) (Target) HasSrcLocation: False
> (Cast) (Target) HasDstLocation: False
> (Cast) (Target) HasOrientation: False
> (Cast) (Target) hasMapID : False
> (Cast) (Target) Unit: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> (Cast) (Target) Item: Full: 0x0
> (Cast) (Target) Name: 
> (Cast) [0] HitTarget: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> (Cast) [0] HitStatus: 0
> 
> ServerToClient: SMSG_SPELL_START (0x2C3A) Length: 128 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43863
> (Cast) CasterGUID: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CasterUnit: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CastID: Full: 0xBC30F04C2038D7C3003513000317C8FF Cast/3 R3132/S13587 Map: 609 Low: 51890431
> (Cast) OriginalCastID: Full: 0x0
> (Cast) SpellID: 58207 (58207)
> (Cast) (Visual) SpellXSpellVisualID: 0
> (Cast) (Visual) ScriptVisualID: 0
> (Cast) CastFlags: 10
> (Cast) CastFlagsEx: 1048576
> (Cast) CastTime: 0
> (Cast) (MissileTrajectory) TravelTime: 0
> (Cast) (MissileTrajectory) Pitch: 0
> (Cast) Ammo.DisplayID: 0
> (Cast) DestLocSpellCastIndex: 0
> (Cast) (Immunities) School: 0
> (Cast) (Immunities) Value: 0
> (Cast) (Predict) Points: 0
> (Cast) (Predict) Type: 0
> (Cast) (Predict) BeaconGUID: Full: 0x0
> (Cast) HitTargetsCount: 0
> (Cast) MissTargetsCount: 0
> (Cast) HitStatusCount: 0
> (Cast) MissStatusCount: 0
> (Cast) RemainingPowerCount: 0
> (Cast) HasRuneData: False
> (Cast) TargetPointsCount: 0
> (Cast) (Target) Flags: 2 (Unit)
> (Cast) (Target) HasSrcLocation: False
> (Cast) (Target) HasDstLocation: False
> (Cast) (Target) HasOrientation: False
> (Cast) (Target) hasMapID : False
> (Cast) (Target) Unit: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> (Cast) (Target) Item: Full: 0x0
> (Cast) (Target) Name: 
> 
> ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 139 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43864
> (Cast) CasterGUID: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CasterUnit: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> (Cast) CastID: Full: 0xBC30F04C2038D7C3003513000317C8FF Cast/3 R3132/S13587 Map: 609 Low: 51890431
> (Cast) OriginalCastID: Full: 0x0
> (Cast) SpellID: 58207 (58207)
> (Cast) (Visual) SpellXSpellVisualID: 0
> (Cast) (Visual) ScriptVisualID: 0
> (Cast) CastFlags: 264
> (Cast) CastFlagsEx: 1048592
> (Cast) CastTime: 954803809
> (Cast) (MissileTrajectory) TravelTime: 0
> (Cast) (MissileTrajectory) Pitch: 0
> (Cast) Ammo.DisplayID: 0
> (Cast) DestLocSpellCastIndex: 0
> (Cast) (Immunities) School: 0
> (Cast) (Immunities) Value: 0
> (Cast) (Predict) Points: 0
> (Cast) (Predict) Type: 0
> (Cast) (Predict) BeaconGUID: Full: 0x0
> (Cast) HitTargetsCount: 1
> (Cast) MissTargetsCount: 0
> (Cast) HitStatusCount: 1
> (Cast) MissStatusCount: 0
> (Cast) RemainingPowerCount: 0
> (Cast) HasRuneData: False
> (Cast) TargetPointsCount: 0
> (Cast) (Target) Flags: 2 (Unit)
> (Cast) (Target) HasSrcLocation: False
> (Cast) (Target) HasDstLocation: False
> (Cast) (Target) HasOrientation: False
> (Cast) (Target) hasMapID : False
> (Cast) (Target) Unit: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> (Cast) (Target) Item: Full: 0x0
> (Cast) (Target) Name: 
> (Cast) [0] HitTarget: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> (Cast) [0] HitStatus: 0
> 
> ServerToClient: SMSG_PLAY_OBJECT_SOUND (0x275A) Length: 38 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43865
> SoundId: 14776 (14776)
> SourceObjectGUID: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> TargetObjectGUID: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> Position: X: 2170.866 Y: -5740.302 Z: 101.57286
> BroadcastTextID: 0
> 
> ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 80 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43866
> UpdateAll: False
> AurasCount: 1
> [0] Slot: 12
> [0] HasAura: True
> [0] CastID: Full: 0xBC30F04C2038D7C3003513000317C8FF Cast/3 R3132/S13587 Map: 609 Low: 51890431
> [0] SpellID: 58207 (58207)
> [0] (Visual) SpellXSpellVisualID: 0
> [0] (Visual) ScriptVisualID: 0
> [0] Flags: 4 (Duration)
> [0] ActiveFlags: 1
> [0] CastLevel: 30
> [0] Applications: 0
> [0] ContentTuningID: 869
> [0] HasCastUnit: True
> [0] HasDuration: True
> [0] HasRemaining: True
> [0] HasTimeMod: False
> [0] PointsCount: 0
> [0] EstimatedPoints: 0
> [0] HasContentTuning: False
> [0] CastUnit: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> [0] Duration: 11000
> [0] Remaining: 11000
> UnitGUID: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> 
> ServerToClient: SMSG_UPDATE_OBJECT (0x27B7) Length: 78 ConnIdx: 1 Time: 11/19/2021 10:55:44.469 Number: 43867
> NumObjUpdates: 1
> MapID: 609 (609)
> HasRemovedObjects: True
> DestroyedObjCount: 1
> RemovedObjCount: 1
> (Destroyed) [0] ObjectGUID: Full: 0x2C30F04C20BA37C0003513000017C6A3 GameObject/0 R3132/S13587 Map: 609 Entry: 190687 Low: 1558179
> Data size: 46
> [0] UpdateType: Values
> [0] Object Guid: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> [0] Target: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> [0] Flags: 34079488
> 
> ClientToServer: CMSG_LATENCY_REPORT (0x3772) Length: 65 ConnIdx: 1 Time: 11/19/2021 10:55:44.485 Number: 43868
> |-------------------------------------------------|---------------------------------|
> | 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F | 0 1 2 3 4 5 6 7 8 9 A B C D E F |
> |-------------------------------------------------|---------------------------------|
> | 00 00 00 00 03 00 00 00 53 00 01 01 13 35 00 5D | . . . . . . . . S . . . . 5 . ] |
> | 26 E9 38 7D 01 00 00 00 00 00 00 53 00 01 01 07 | & . 8 } . . . . . . . S . . . . |
> | 00 0C 5D 26 E9 38 7D 01 00 00 02 00 00 00 00 00 | . . ] & . 8 } . . . . . . . . . |
> | 00 00 00 00 21 7C 2B E9 38 7D 01 00 00 10 00 00 | . . . . ! | + . 8 } . . . . . . |
> | 00                                              | .                               |
> |-------------------------------------------------|---------------------------------|
> 
> ClientToServer: CMSG_TIME_SYNC_RESPONSE (0x3A3A) Length: 8 ConnIdx: 1 Time: 11/19/2021 10:55:44.485 Number: 43869
> Counter: 479
> Ticks: 582080407
> 
> ServerToClient: SMSG_CHAT (0x2BAD) Length: 85 ConnIdx: 0 Time: 11/19/2021 10:55:44.641 Number: 43870
> SlashCmd: 15 (MonsterWhisper)
> Language: 0 (Universal)
> SenderGUID: Full: 0x2030F04C201C17400035130000179AEE Creature/0 R3132/S13587 Map: 609 Entry: 28765 Low: 1546990
> SenderGuildGUID: Full: 0x0
> WowAccountGUID: Full: 0x0
> TargetGUID: Full: 0x0811C0000000000000000000090D34C1 Player/0 R1136/S0 Map: 0 Low: 151860417
> TargetVirtualAddress: 16842759
> SenderVirtualAddress: 16842835
> PartyGUID: Full: 0x0
> AchievementID: 0
> DisplayTime: 0
> ChatFlags: 32
> HideChatLog: False
> FakeSenderName: False
> Unk801_Bit: False
> HasChannelGUID: False
> Sender Name: The Lich King
> Receiver Name: 
> Addon Message Prefix: 
> Channel Name: 
> Text: No survivors.

</details>

### Source

https://youtu.be/585PbyJAxys?t=89

https://www.wowhead.com/quest=12678/if-chaos-drives-let-suffering-hold-the-reins

### Steps to reproduce the problem

1. create DK
2. get to quest If Chaos Drives, Let Suffering Hold The Reins (ID 12678)
3. attack Citizen of Havenshire (NPCs 28576, 28577)

### Extra Notes

Whispers, capitalization and removing an aura attached to the invisible NPC:
```sql
/* Lich King 'If Chaos Drives, Let Suffering Hold the Reins' Quest Whispers
*/

DELETE FROM `creature_text` WHERE `CreatureID`=28765 AND `GroupID`=0 AND `ID`=0;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(28765, 0, 0, 'No mercy.', 15, 0, 100, 0, 0, 14771, 28771, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 1, 'Kill them all.', 15, 0, 100, 0, 0, 14772, 28772, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 2, 'Mercy is for the weak.', 15, 0, 100, 0, 0, 14773, 28773, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 3, 'End it.', 15, 0, 100, 0, 0, 14774, 28774, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 4, 'Finish it.', 15, 0, 100, 0, 0, 14775, 28775, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 5, 'No survivors.', 15, 0, 100, 0, 0, 14776, 28776, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 6, 'Kill or be killed, $N.', 15, 0, 100, 0, 0, 14777, 28777, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 7, 'Do not hesitate.', 15, 0, 100, 0, 0, 14778, 28778, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 8, 'Harness your rage and focus!', 15, 0, 100, 0, 0, 14779, 28779, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 9, 'Strike it down!', 15, 0, 100, 0, 0, 14780, 28780, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 10, 'Suffering to the conquered!', 15, 0, 100, 0, 0, 14781, 28781, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 11, 'Show it the meaning of terror.', 15, 0, 100, 0, 0, 14782, 28782, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 12, 'End its miserable life.', 15, 0, 100, 0, 0, 14783, 28783, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 13, 'Give in to the darkness, death knight.', 15, 0, 100, 0, 0, 14784, 28784, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 14, 'Do you think it would hesitate to kill you? A monster like you?', 15, 0, 100, 0, 0, 14785, 28785, 0, 'Lich King - Ebon Hold - Phase 1 Whispers'),
(28765, 0, 15, 'Living or dead, you will serve me.', 15, 0, 100, 0, 0, 14786, 28786, 0, 'Lich King - Ebon Hold - Phase 1 Whispers');

/* Capitalization
*/

UPDATE `broadcast_text` SET `MaleText`='Kill or be killed, $N.' WHERE `ID`=28777;

/* Remove Path of Frost Aura from this entry (it is an invisible creature spawned in a grain silo to whisper players and the aura is able to be seen)
*/

DELETE FROM `creature_addon` WHERE (`guid` IN (129882));
UPDATE `creature_template_addon` SET `auras` = '' WHERE (`entry` = 28765);
```

### AC rev. hash/commit

23dd1d2

### Operating system

Win10

**Comment by Voxstrasza** [comment]
Even though I opened this issue I have been working on it in my spare time and I am convinced that cpp might be required to handle this event - SAI can get it working but not properly.

**Comment by fangshun2004** [comment]
This is easy to do using an ASI script, but the problem is that there are now 2 Lich Kings underneath the granary. Which Lich King should be used to whisper to the player？
