### ISSUE TITLE
Deterrence vs Shield Bash

### ISSUE THREAD

**Issue by Vynel** [azerothcore/azerothcore-wotlk#969]
Steps To Reproduce Bug:
1. Hunter Use Deterrence and cast Revive Pet
2. Warrior use Shield Bash
3. Shield Bash is penetrating deterrence

System: Window 64

**Comment by Vynel** [comment]
https://ibb.co/k2kw1o

**Comment by talamortis** [comment]
please fill out the template provided.

**Comment by Vynel** [comment]
please remove, sorry :(

**Comment by Vynel** [comment]
I forgot to follow the template correctly

**Comment by BarbzYHOOL** [comment]
You can copy this and edit your issue https://raw.githubusercontent.com/azerothcore/azerothcore-wotlk/master/issue_template.md

**Comment by BarbzYHOOL** [comment]
Reopen the issue correctly please
