### ISSUE TITLE
crash when reseting instances

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#9695]
https://pastebin.com/TV0SrhE5

### Current behaviour

There has been a crash while I was testing PR #8169.

Since I don't think It's related, I'll leave it here.

### Steps to reproduce the issue
1. Go into ulduar
2. Get out
3. Reset instances

### AC rev. hash/commit

b4a1421

### Operating system

Windows 10

**Comment by Kitzunu** [comment]
Dont Ever paste a txt. Nobody will download it.

Use gist or pastebin as the github template says please

**Comment by Kitzunu** [comment]
Also dont ignore the template. How to reproduce?

**Comment by claudiodfc** [comment]
There

**Comment by Kitzunu** [comment]
Good job

**Comment by Shineslippers** [comment]
I can;t reproduce it on AC. So probably it's test PR
