### ISSUE TITLE
POI area of A New Plague quest is not big enought

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9703]
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2553

The Quest _A New Plague_ seems not to be implemented according to retail. 

Indeed, the quest implies to collect 5 Vials of Darkhound Blood. I use Carbonite 3.34 and the area for collecting such Vials  is pretty large. On other 3.3.5. servers, like sindragosa (ex Sunwell, Warmane) the area seems to match with the carbonite region proposed by Carbonite. 

But here it seems that the region is very restricted to only a small certain portion of the map Carbonite proposes for this quest. Furthermore, the drop rate is pretty rare and you will have to kill numerous darhounds to retrieve those 5 Vials. 

Tester:

The issue is confirmed. POI area of [A New Plague](https://wowgaming.altervista.org/aowow/?quest=367) quest is not covering all spots

![WoWScrnShot_121421_210047](https://user-images.githubusercontent.com/85256266/146055698-84666d98-d611-49b2-8bd9-1279a1e8f829.jpg)

### Expected Blizzlike Behaviour

Probably area of POI should be much bigger

![Capture](https://user-images.githubusercontent.com/85256266/146056002-724d921b-5fcd-46a3-8279-ddaf1b6a6d2c.PNG)

### Source

Wowhead [A New Plague](https://www.wowhead.com/quest=367/a-new-plague)

### Steps to reproduce the problem

.q a 367
show quest map

### Extra Notes

Drop rate of `Darkhound Blood` is 35% and there is no sources why it should be adjusted.
| name | entry | Item | chance | 
| --- | ---: | ---: | ---: | 
| Decrepit Darkhound | 1547 | 2858 | 35 | 
| Cursed Darkhound | 1548 | 2858 | 35 | 
| Ravenous Darkhound | 1549 | 2858 | 35 | 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
POI is from sniff. No one is editing it.

**Comment by claudiodfc** [comment]
It could be that these creatures are spawned with too many entries too... Wowhead isn't very accurate source of information.
