### ISSUE TITLE
PvP trinkets remove PX-238 Winter Wondervolt buff

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9719]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2580

Costume is required for 50 HKs achievement, upon entering BG I had that transform on me, but when I used trinket to get out of stun my costume/buff went off.

Tester:

The issue is confirmed. [PvP trinkets](https://wowgaming.altervista.org/aowow/?spell=42292#used-by-item) remove [PX-238 Winter Wondervolt](https://wowgaming.altervista.org/aowow/?search=PX-238+Winter+Wondervolt#spells) buffs

https://user-images.githubusercontent.com/85256266/146171343-7874a89f-7839-43e9-8e99-7167f4d9e5c1.mp4

### Expected Blizzlike Behaviour

Insignias should dispel only unfriendly spells not personal buffs

### Steps to reproduce the problem

.aura 26157
.cast 42292

### Extra Notes

Achievement [With a Little Helper from My Friends](https://wowgaming.altervista.org/aowow/?achievement=252)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
it's because this is considered a polymorph

Mechanic = 17 (MECHANIC_POLYMORPH)

<details><summary>SpellWork</summary>

```
ID - 26272 PX-238 Winter Wondervolt
=================================================
ToolTip: Happy Holidays!
Category = 0, SpellIconID = 976, activeIconID = 0, SpellVisual = (7435,0), SpellPriority = 0
Family SPELLFAMILY_UNK1, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000100 (SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
=================================================
Spell Level = 1, base 1, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 17 (MECHANIC_POLYMORPH)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0,00
Duration: ID (30)  1800000, 0, 1800000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0 Bonus = 1,00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 56 (SPELL_AURA_TRANSFORM), value = 1, misc = 15838 (15838), miscB = 0, periodic = 0

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT

```

</details>

**Comment by lingxDEV** [comment]
https://user-images.githubusercontent.com/62337627/146690568-5a7b5ac3-1835-45ce-b2a0-944f5032a424.mp4

From retail Classic.

**Comment by Kitzunu** [comment]
Perhaps they patched it there.

But per the wotlk dbc's this seems blizzlike.

**Comment by lingxDEV** [comment]
There will be edge cases like this though. I really think you should reconsider on this one. I remember doing this achievement in WotLK myself.

**Comment by Kitzunu** [comment]
I missed the fact that it was for a PVP achievement. Let me dig a bit

**Comment by Kitzunu** [comment]
I can't find anything on it. But in this case it only makes sense that it should stay on.
