### ISSUE TITLE
command /afk doesnt remove players from arena match

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#9730]
### Current Behaviour

When typing /afk to leave an arena match, nothing happens, you just get the ''You are now Away: Away'' message.

Its possible to use the minimap button to leave, but its faster to type /afk.

### Expected Blizzlike Behaviour

Should remove you from the current arena match.

### Source

https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/136220-question-leave-arena-bg-macro.html
https://www.mmo-champion.com/threads/2207618-anyone-got-a-surrender-macro-arena-script
https://us.forums.blizzard.com/en/wow/t/leaving-arena/862254

### Steps to reproduce the problem

1. enter an arena match
2. type /afk in chat

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Windows 10 x64

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/cbdc39ce1e2383b86712103e93633475647ea38c

Works fine for me
![Screenshot_20211216_094711](https://user-images.githubusercontent.com/14080516/146318548-d8fc6999-fb3d-4154-ad0f-9d2ba52a7551.png)
.

**Comment by laasker** [comment]
> [cbdc39c](https://github.com/azerothcore/azerothcore-wotlk/commit/cbdc39ce1e2383b86712103e93633475647ea38c)
> 
> Works fine for me ![Screenshot_20211216_094711](https://user-images.githubusercontent.com/14080516/146318548-d8fc6999-fb3d-4154-ad0f-9d2ba52a7551.png) .

you are right, just tested in BGs and it works, but in arena it doesnt

**Comment by IntelligentQuantum** [comment]
@laasker https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L1256

Change !InArena() to InArena()

**Comment by laasker** [comment]
> @laasker https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L1256
> 
> Change !InArena() to InArena()

It works!

**Comment by IntelligentQuantum** [comment]
@Shineslippers Is it Blizzlike?

**Comment by Shineslippers** [comment]
I would say say yes. Don't see difference between arena and battleground. There is existing command `/run LeaveBattlefield()` that work for bg and arena.

**Comment by FrancescoBorzi** [comment]
@Shineslippers don't forget the project ;)
