### ISSUE TITLE
MoltenCore hounds are not 100% blizzlike

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#974]
##### SMALL DESCRIPTION:

An issue taken from here https://github.com/azerothcore/azerothcore-wotlk/issues/592

##### CURRENT BEHAVIOUR:

- When a core hound is killed, it instantly lays on the ground without playing a death animation. This isn't blizzlike. They should go through their normal death animation and stay dead only reviving if the timer expires before the all mobs in the group are killed.
- When the pack is killed, each hound that's currently "sleeping" goes into the death animation and stays dead. The hounds that are dead should stay dead and not revive at all if the pack is killed off before their timer expires.
- The hounds that die seem to have a slight breathing animation which isn't blizzlike, and it could be tied to the reason they come back to life and dying AFTER the pack is killed off.
- The mobs need to be flagged as DEAD and then come back to life. It seems like they are being flagged as sleeping or something. They can still be attacked when they are "dead".
- Some of the hounds in a pack do not attack and sit idle.
- The mobs are listed as "Core Hounds" when they should be "Ancient Core Hounds"

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to molten core
2. Test the hounds following the above list

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/07a451e1402cf8a7c24cf6196d541d304f5dcff2

**Comment by BarbzYHOOL** [comment]
Related PR: https://github.com/azerothcore/azerothcore-wotlk/issues/620

**Comment by Nefertumm** [comment]
Some updates about those items:

- I can't reproduce the first one. For me, the hounds did the complete death animation. (test with 334a0f3e2c5c43be448be8dbcfc9d6dffeb64266)
- The last item is wrong. The ancient core hounds are differents npcs. The Core Hounds has 47k of life instead of the Ancient Core Hound which has 113k of life.
- Some of the hounds in a pack do not attack because there isn't any creature_formations data. Adding each pack in this table should work.
- About the others, you're right.

**Comment by Nefertumm** [comment]
Here is the creature_formations data (probably it needs to be improved):
```sql
-- angle isn't blizzlike, a random value.
INSERT INTO `creature_formations` VALUES (56634,56634,0,0,3,0,0);
INSERT INTO `creature_formations` VALUES (56634,56637,10,45,3,0,0);
INSERT INTO `creature_formations` VALUES (56634,56635,10,90,3,0,0);
INSERT INTO `creature_formations` VALUES (56634,56638,10,135,3,0,0);
INSERT INTO `creature_formations` VALUES (56634,56636,10,180,3,0,0);

INSERT INTO `creature_formations` VALUES (56629,56629,0,0,3,0,0);
INSERT INTO `creature_formations` VALUES (56629,56631,10,45,3,0,0);
INSERT INTO `creature_formations` VALUES (56629,56633,10,90,3,0,0);
INSERT INTO `creature_formations` VALUES (56629,56632,10,135,3,0,0);
INSERT INTO `creature_formations` VALUES (56629,56630,10,180,3,0,0);

INSERT INTO `creature_formations` VALUES (56639,56639,0,0,3,0,0);
INSERT INTO `creature_formations` VALUES (56639,56640,10,45,3,0,0);
INSERT INTO `creature_formations` VALUES (56639,56643,10,90,3,0,0);
INSERT INTO `creature_formations` VALUES (56639,56642,10,135,3,0,0);
INSERT INTO `creature_formations` VALUES (56639,56641,10,180,3,0,0);

INSERT INTO `creature_formations` VALUES (56646,56646,0,0,3,0,0);
INSERT INTO `creature_formations` VALUES (56646,56644,10,45,3,0,0);
INSERT INTO `creature_formations` VALUES (56646,56648,10,90,3,0,0);
INSERT INTO `creature_formations` VALUES (56646,56649,10,135,3,0,0);
INSERT INTO `creature_formations` VALUES (56646,56647,10,180,3,0,0);

INSERT INTO `creature_formations` VALUES (56652,56652,0,0,3,0,0);
INSERT INTO `creature_formations` VALUES (56652,56653,10,45,3,0,0);
INSERT INTO `creature_formations` VALUES (56652,56650,10,90,3,0,0);
INSERT INTO `creature_formations` VALUES (56652,56651,10,135,3,0,0);
INSERT INTO `creature_formations` VALUES (56652,56654,10,180,3,0,0);
```

**Comment by T1ti** [comment]
> * The hounds that die seem to have a slight breathing animation which isn't blizzlike, and it could be tied to the reason they come back to life and dying AFTER the pack is killed off.
> * The mobs need to be flagged as DEAD and then come back to life. It seems like they are being flagged as sleeping or something. They can still be attacked when they are "dead".

Not true, on blizzlike they don't die, they stay at like 2hp and become unkillable until all are dead, you can still do damage to them and warriors abuse this to generate threat.

> * The mobs are listed as "Core Hounds" when they should be "Ancient Core Hounds"

Ancient core hounds are the big ones in the rest of the instance, those packs are the normal core hounds.

**Comment by T1ti** [comment]
and you shouldn't use the creature formation system to link them
