### ISSUE TITLE
NPCs with empty loot not skinable

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9741]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2611

Observed weird thing about skining beasts at the moment when killed dozens of them in barrens this morning to increase skill in skining. The point is some mobs which probably dont drop loot cannot be skinned. This is my and other players who whispered me theory.
![WoWScrnShot_121721_115554](https://user-images.githubusercontent.com/25100993/146539544-cae2e63c-fb55-4d42-b68e-1a8884cfd664.jpg)
![WoWScrnShot_121721_115600](https://user-images.githubusercontent.com/25100993/146539550-a9f3b83e-7d85-4cf5-a6e4-df42a0d2c60d.jpg)
![WoWScrnShot_121721_120143](https://user-images.githubusercontent.com/25100993/146539559-60468cb3-208b-4d47-a16e-b357e2ca8b5a.jpg)
 
Tester:

The issue is confirmed. NPCs with empty loot not skinable

https://user-images.githubusercontent.com/85256266/146555546-8b756238-da08-4d60-9252-337c5eb7feaf.mp4

### Expected Blizzlike Behaviour

Make lootless uniteractive corpses of skinnable creatures actaully skinnable.

### Steps to reproduce the problem

.additem 7005
.setskill 393 450
.go c 19255
kill striders around until someone will be without loot
.cast 50305

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by temperrr** [comment]
@UltraNix Could you take a look at this?

**Comment by buddiman** [comment]
I was testing this for like 15 minutes, I could skin every beast around the given location whether it had loot or not.
My rev is still on https://github.com/azerothcore/azerothcore-wotlk/commit/6fa91dbe1f2a55ccaa22130a3a4bbaa0d210786a

**Comment by temperrr** [comment]
Yea, probably broken recently

**Comment by buddiman** [comment]
I'm building the newest rev right now to check it, the only PR I found regarding Loot or Creatures would be https://github.com/azerothcore/azerothcore-wotlk/pull/9723. Maybe I can track it down further.

**Comment by buddiman** [comment]
Definitely broke with https://github.com/azerothcore/azerothcore-wotlk/pull/9723.
After reverting the changes skinning works again as intended. I looked into it, but I can't find why it's producing this side effect.

**Comment by Kitzunu** [comment]
cc @Nyeriah

**Comment by Nyeriah** [comment]
I'll leave this one with @UltraNix because I didn't do much other than what I was asked to do and I'm not sure what has changed about skinning.
