### ISSUE TITLE
Warlock's Chaos Bolt doesn't pierces through all absorption effects and could be resisted by higher level targets

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9742]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2609

Warlock level 60 Destruction talented ability Chaos Bolt https://wowgaming.altervista.org/aowow?spell=50796 is being resisted, when it should not.
![Chaos Bolt resisted (2)](https://user-images.githubusercontent.com/95250546/146490132-cec80d62-980a-4414-a91f-aaf4680b78fc.png)

Tester:

Some issues is exist. [Chaos Bolt](https://wowgaming.altervista.org/aowow/?spell=50796)

1. Absorbing auras is affecting Chaos Bolt
2. High level targets resisting part of Chaos Bolt damage even if have 0 resistance
 
![WoWScrnShot_121721_182653](https://user-images.githubusercontent.com/85256266/146567762-fdc57937-dab5-4374-931f-9ca34fb0144d.jpg)

### Expected Blizzlike Behaviour

1. Absorbing auras like Mana Shield, Anti-Magic Shell, Power Word: Shield and etc. should not affect Chaos Bolt
2. Not sure is this issue. Maybe it's some kind of damage reduction by higher level targets. Anyway description of spell saying `Chaos Bolt cannot be resisted`. If target have same level as user of Chaos Bolt i can't get `resisted` or `partially resisted` combat log lines

### Source

Spell description
> Chaos Bolt cannot be resisted, and pierces through all absorption effects.

Wowwiki [Chaos Bolt](https://wowwiki-archive.fandom.com/wiki/Chaos_Bolt?oldid=2299174#Tips_and_tactics)

https://youtu.be/RFR4cNYzB6A?t=34
This includes a copy of the blue post issued by "ghostcrawler" greg street former Lead Systems Designer at the time.

### Steps to reproduce the problem

.aura 48066 on target
.cast 50796

make targer 20+ levels higher
.cast 50796

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
Can't reproduce 1st problem with absorp auras - works okay to me.

**Comment by Shineslippers** [comment]
AzerothCore rev. 74640b2a4709 2021-12-17 11:22:41 +0000 (master branch)
https://user-images.githubusercontent.com/85256266/146650427-1482f99a-985e-461e-ba1d-8c8fb1fbb011.mp4

**Comment by UltraNix** [comment]
Have you use `.unaura all` command?

**Comment by Shineslippers** [comment]
No only `.aura` like `Steps to reproduce the problem`.

**Comment by UltraNix** [comment]
![sd](https://user-images.githubusercontent.com/80540499/146650968-dc05a2a4-f699-4c3b-8585-424d88237173.png)

**Comment by UltraNix** [comment]
Type ingame `.list auras` and check if you have `Chaos Bolt Passive`

**Comment by Shineslippers** [comment]
No i don't
![Capture](https://user-images.githubusercontent.com/85256266/146651209-3e976664-da00-4954-80e9-9a0bc821c4f4.PNG)

**Comment by UltraNix** [comment]
That's why. I don't why you don't have it, but you should.

**Comment by Shineslippers** [comment]
Well i learned spell through talents and no issue. Hm, fixed

**Comment by UltraNix** [comment]
It's passive aura - should be from the very start. Create a new warlock, level up to 80 and then see.

**Comment by Shineslippers** [comment]
Well, my bad. Next time to avoid this i will test class issues by using that class
