### ISSUE TITLE
NPCs from time to time doesn't show vendor window

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9745]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2604

When talking to a vendor, sometimes their menu doesn't appear, but the game still thinks you are "shopping" with them, and you need to walk away from them until the menu would normally close, and then initialize a conversation with them again. sometimes happens more than once, seems to only happen when initializing conversation when moving

Tester: 

The issue is confirmed. Sometimes when you running to NPCs and right-click on them it doesn't show vendor's window. NPCs is sticking to player like when vendor's window is open. `Esc` or `Rgihr-click again` doesn't help. Only out of range can reset it. It's hard to reproduce. Didn't find pattern.

https://user-images.githubusercontent.com/85256266/146576715-1f34cb9f-99e9-4fec-b5d0-9184891df209.mp4

### Expected Blizzlike Behaviour

Talking to a vendor should pull up their menu all the time without failiure.

### Source

X

### Steps to reproduce the problem

.go c 37605
run and right-click on vendor

### Extra Notes

Does not happen with just Kaita Deepforge, thats just the NPC i tested it with and noticed it first.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Meramaf** [comment]
Vendors on the latest revision work fine

**Comment by Shineslippers** [comment]
Still able to reproduce it on 74640b2a47098220f2e13c90fd74ebc2da1b0586

**Comment by UltraNix** [comment]
Can't reproduce it with spamming Interact keybind (as with right mouse).

**Comment by Shineslippers** [comment]
Well, nothing i can do more. 2nd video 10s. Maybe client-side.

**Comment by UltraNix** [comment]
I believe so. Nothing a big deal.

**Comment by Shineslippers** [comment]
@UltraNix sorry, but can you look at it again. Maybe it's about some delay

[14:00] Temper: hey
[14:00] Temper: did you see an issue for that vendors etc take slow to load
[14:00] Temper: needing multiple clicks to open
[14:02] ShineSlippers: mmm right now i'm working on winter veil, but can confirm the issue on CC
[14:02] Temper: I found it on local too
[14:02] Temper: so was wondering if somebody reported it already
[14:03] Temper: I am very busy with testing another pr
[14:03] Temper: with the save system so cant check 😉
[14:04] ShineSlippers: ok i will report it
[14:04] Temper: thanks 🙂
[14:04] Temper: yea sorry very busy 😦
[15:40] ShineSlippers: I don't see it clear on local AC. Is it related to https://github.com/azerothcore/azerothcore-wotlk/issues/9745 ?
[15:41] Temper: Yea
[15:41] Temper: I tried the vendor in orgrimmar
[15:41] Temper: For event
[15:41] ShineSlippers: OK i will reopen it then, but ultranix on vacation xD

**Comment by djsozo** [comment]
Still an issue, but not just this one NPC although it does happen with her a lot. the Gryphon Master in Stormwind also did it to me today.

**Comment by KCorruption** [comment]
Can confirm this still happens frequently for me, as well. It tends to happen when I attempt to open the dialogue box with any vendor/service npc, when just entering range to do so. This happens most frequently with flight masters, and vendor npcs, though I've had it happen with profession & skill tutors as well. A work-around is to either approach, stop briefly, then interact, or to just exit service range then re-enter it & try again.

**Comment by acidmanifesto** [comment]
Looks to be either deadlock or a thread priority issue i assume. Seen something like this before with other projects. I will do a comparison tomorrow when i wake up to see if i can spot anything different.

**Comment by Kitzunu** [comment]
If you reopen an issue. Please remove the invalid label or it risks being closed again.
