### ISSUE TITLE
Feature: Reintroduce removed command shortcuts

### ISSUE THREAD

**Issue by iEmpress** [azerothcore/azerothcore-wotlk#9748]
### Describe your feature request or suggestion in detail

I have always used .ad as shorthand for .additem.  Unfortunately, a recent update brought an unintended regression this was changed so that the whole thing needs to be typed out.

The two alternatives for .ad to autocomplete is .additem and .additemset where .additemset should have a lower usage rate.

As such I recommend that .ad should be able to be used as an alternative to .additem once again.

### Describe a possible solution to your feature or suggestion in detail

Have all abbreviations of .additem go into .additem and have .additemset be required to be typed out, as the use-case is in a much smaller degree.

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/0c1880f69457d2057da3233e6e0ce5d2273778a5
