### ISSUE TITLE
Missing Undercity's Alliance Graveyard

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#9755]
### Current Behaviour

As an Alliance player, releasing after dying in Undercity did not teleport me to a graveyard. I also didn't have a cooldown.

https://user-images.githubusercontent.com/22718174/146624656-87772fcd-cbd4-4a84-bb5b-4dbc526169e8.mp4

### Expected Blizzlike Behaviour

I should at least get teleported to a graveyard in Tirisfal Glades.

### Steps to reproduce the problem

Create an Alliance character.
Get in Undercity.
Die.
Click "Release".

### AC rev. hash/commit

First seen on ChromieCraft.
AzerothCore rev. 24f4e08708c2 2021-12-17 00:27:59 -0300 (master branch) (Unix, RelWithDebInfo, Static)

Also reproducible on the ChromieCraft PTR 1.
AzerothCore rev. 6defa027bb70+ 2021-12-17 10:52:51 +0000 (HEAD branch) (Unix, Debug, Static)

Did on a clean local AzerothCore server.
AzerothCore rev. cbdc39ce1e23 2021-12-15 21:46:16 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Unix, also did on Windows 10 x64

**Comment by Shineslippers** [comment]
Did check of all capital cities. Valid only for Undercity.
