### ISSUE TITLE
spell 'Racer Rocket Slam' seems broken

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#9757]
### Current Behaviour

Spell [Racer Rocket Slam](https://tbc.wowhead.com/spell=49297) ( item id 37710 [Crashin' Thrashin' Racer Controller](https://tbc.wowhead.com/item=37710) or item id 54343 Blue Crashin' Thrashin' Racer Controller) is not works  then pressed or if triggered, it does not increase the [Racer Kill Counter](https://tbc.wowhead.com/spell=49444)
 
 It needs for event Winter Veil - Crashin' & Thrashin' 
![изображение](https://user-images.githubusercontent.com/25766571/146628896-70d3adbd-13b0-4421-897b-053213ddd704.png)

### Expected Blizzlike Behaviour

If the Racer crashes under the influence of a spell, the crash counter should increase 

### Steps to reproduce the problem

1. .additem 37710
2. Launch it
3. Drive it and hit to wall or to other Racer by pressing "1"

Nothings happens.

### AC rev. hash/commit

6defa027bb70e324a268bf748fe5f33ec8ada2bd

### Operating system

Win x64

### Custom changes or Modules

clear core

**Comment by Shineslippers** [comment]
Work for me. Need more info

https://user-images.githubusercontent.com/85256266/146636187-236995ec-63a1-4101-a0f8-c3424d7b486d.mp4

**Comment by Bogir** [comment]
I found reason. Red must hit Blue. Never mind...
It works!
