### ISSUE TITLE
[Molten Core] Ragnarok targetting dead player, whilst still attacking main target

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9775]
### Current Behaviour

Sometimes Ragnarok targets a dead player, whilst still attacking the main melee target

### Expected Blizzlike Behaviour

Ragnarok should not be targetting dead players.

### Source

~ 

### Steps to reproduce the problem

It is rare that this happens, but it involves someone dying and tank being in melee range. The target that died was a ranged player.

### AC rev. hash/commit

de49c3bead5f+ 

### Operating system

Linux

### Custom changes or Modules

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Eronox** [comment]
@temperrr  do we know what attack Ragnaros uses on the dead player?

**Comment by temperrr** [comment]
He actually doesn't attack the player, only his target of target shows he is targeting a dead player.
