### ISSUE TITLE
[Molten Core] Monsters should stop respawning when their Mother/Father boss has been killed

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9776]
### Current Behaviour

Monsters keep respawning even after their mother/father boss has been killed

### Expected Blizzlike Behaviour

For instance, when Garr is slain, all earth elementals should stop respawning.
Or Magmadar for Core Hounds.

While we are at it, we should look into respawn timers of these monsters too,

`Some trash mobs respawned every hour or every two hours, but others had a much shorter respawn. Lava Surgers respawned every 28 minutes. Ancient Core Hounds respawned every 18 minutes. Fire Imps (i.e., the imps in the Imp Cave) respawned every 8 minutes. That's not a typo.`

### Source

[here ](https://www.engadget.com/2014-08-16-wow-archivist-the-classic-molten-core-experience.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAN4wt9eSa-uUPvJavpzaCjgMeB1Bq5PTgh4bqn7Jif6jG8QSYTWa3ajlKDfA2saFiuA2kPinz5Ws1nSte1QQLrcJX4150JavnXYB5-sae9bn07_JOSv7nGeKRH3iYdFTYDInbxRh7nivNnSPpgwrErERK5_HA1Hq_I59FcI1AA0Z)

### Steps to reproduce the problem
~ 

### AC rev. hash/commit

de49c3bead5f+ 

### Operating system

Linux

### Custom changes or Modules

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by claudiodfc** [comment]
There's other issues like this, where creatures aren't summoned on the masters respawn. I assume their appearance, since depending on the master, should be done via SmartAI.

**Comment by claudiodfc** [comment]
The issue with that solution is if the master dies, the creature summon resets and if the master respawns, there's duplication.

**Comment by Nyeriah** [comment]
I tried this on retail, and it doesn't seem to be "all elementals" but only specific ones. For example, after Garr dies **Lava Surgers** stop respawning, but Lava Anihilators (the ones in the side packs) seem to respawn normally.
