### ISSUE TITLE
[Item drops] Bloodkelp, wrong drop rates, should also drops from Strashaz Myrmidon and Tidelord Rrurgaz

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#9785]
### Current Behaviour

Doing this SQL query gives this result.
```sql
SELECT *
FROM creature_loot_template
WHERE Item = 22094
```
![image](https://user-images.githubusercontent.com/22718174/146686368-d673e239-3a4f-469e-acb8-58b3494bc3ab.png)

### Expected Blizzlike Behaviour

The drop rates should be these.
https://classic.wowhead.com/item=22094/bloodkelp
![image](https://user-images.githubusercontent.com/22718174/146686433-cd2d1b29-260f-46a9-9664-0c24edff5632.png)

https://tbc.wowhead.com/item=22094/bloodkelp
![image](https://user-images.githubusercontent.com/22718174/146686453-098ff5a7-c829-448d-9446-50ebd2a3d477.png)

### Source

wowpedia also mention that they drop from 6 mobs: https://wowpedia.fandom.com/wiki/Bloodkelp
On 26th November: https://wowpedia.fandom.com/wiki/Bloodkelp?oldid=2524008

### Steps to reproduce the problem

Weirdly, these Myrmidons also have the quest tag to them.
![image](https://user-images.githubusercontent.com/22718174/146687673-27c1ab36-196c-4472-acbf-047ed08213dc.png)

### AC rev. hash/commit

AzerothCore rev. cbdc39ce1e23 2021-12-15 21:46:16 -0300 (master branch) (Win64, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

None.

**Comment by malcrom** [comment]
Why do you feel 20% is wrong. If they sometimes drop 2 that would up the percentage to between 25% and 30% on these tables.

**Comment by Synful-Syn** [comment]
The chance of dropping 2 Bloodkelp is a fair point.
With the cache (WBD) proving that Myrmidons never had the drop, how about [Tidelord Rrurgaz](https://classic.wowhead.com/npc=16072/tidelord-rrurgaz)? He also shows he has a quest objective but his loot is missing from his table.
![image](https://user-images.githubusercontent.com/22718174/147494955-3b78c2c2-a807-4d9d-a007-49c32170b441.png)

**Comment by acidmanifesto** [comment]
> The chance of dropping 2 Bloodkelp is a fair point. With the cache (WBD) proving that Myrmidons never had the drop, how about [Tidelord Rrurgaz](https://classic.wowhead.com/npc=16072/tidelord-rrurgaz)? He also shows he has a quest objective but his loot is missing from his table. ![image](https://user-images.githubusercontent.com/22718174/147494955-3b78c2c2-a807-4d9d-a007-49c32170b441.png)

Currently I do not see that reflecting in the current Azerothcore database? Where is that reflecting at? Is it on chromie craft? Or is it a older database?
