### ISSUE TITLE
Feature: .gm fly toggle

### ISSUE THREAD

**Issue by lingxDEV** [azerothcore/azerothcore-wotlk#9787]
### Describe your feature request or suggestion in detail

Often times you will be using .gm fly on/off a lot. Instead of having to macro both on/off, it would be nice if we could have a single command to toggle the mode.

.gm fly toggle

### Additional context

I think it would be useful to a lot of testers.

**Comment by Shineslippers** [comment]
That will be good. As `.cheat` commands doesn't require on/off
