### ISSUE TITLE
Various NPC that have to use stealth don't using it on ChromieCraft

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9804]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original reports: https://github.com/chromiecraft/chromiecraft/issues/2630 https://github.com/chromiecraft/chromiecraft/issues/2592 https://github.com/chromiecraft/chromiecraft/issues/2111

While I was on the quest chain, I did had to use the [Extra-Dimensional Ghost Revealer](https://www.wowhead.com/item=22115/extra-dimensional-ghost-revealer) to see [Bodley](https://www.wowhead.com/npc=16033/bodley). Now that I've completed the whole quest chain, I went back for a regular UBRS and I've noticed that he was visible and interactable, despite I had no buff. I was in a raid, and the fellow next to me was in my raid. I don't know if he had the buff or not (maybe he had it and somehow affected me?)
![Screenshot 2021-12-20 074750](https://user-images.githubusercontent.com/88677774/146744496-7d953cc9-151d-46d7-b3e4-87998c598e7f.png)

[Blackhand Assassin](https://wowgaming.altervista.org/aowow/?npc=10318) again broken, they were fixed for whole UBRS on lvl 59 phase, but now in raid grp they're all seen.
![image](https://user-images.githubusercontent.com/80590226/146248256-c69ef3f6-4f04-4ff2-9a20-e89d8d6bde5d.png)

When you take the quest [Call of Earth](https://wowgaming.altervista.org/aowow/?quest=1517) (part 2) you are sent to a shrine in the nearby hills. There you need to drink the quest item [Earth Sapta](https://wowgaming.altervista.org/aowow/?item=6635) to be able to see the npc [Minor Manifestation of Earth](https://wowgaming.altervista.org/aowow/?npc=5891) and some little earth elementals (can't click on those or see their name to give you a link)

Tester:

The issues is confirmed. Various NPC that have to use stealth don't using it on ChromieCraft

### Expected Blizzlike Behaviour

NCPs that have stealth should use it

### Source

X

### Steps to reproduce the problem

.go c id 16033
.go c id 5891
.go c id 10318

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
Oh so this is a major issue. How to replicate on local?

**Comment by Shineslippers** [comment]
I have no idea. Same as was with scripts. On local AC it works.

**Comment by claudiodfc** [comment]
So most likely it's some problem with a module 🤔

**Comment by Shineslippers** [comment]
Bodley got gossip update and this can remove his hide ability. Blackhand Assassin and Minor Manifestation of Earth has stealth in SAI

**Comment by Nyeriah** [comment]
This needs to be updated. Bodley issue is far gone and had to do with the PR that broke auras. Could someone check this again? @Shineslippers @temperrr

**Comment by UltraNix** [comment]
Yes - it' fixed.
