### ISSUE TITLE
Trial of the Crusader Faction champion Death Knight - Grip

### ISSUE THREAD

**Issue by HAANAAE** [azerothcore/azerothcore-wotlk#982]
Hi

Problem:
The instance Trial of the Crusader All Raid Difficulty!
The player Class "Death Knights" can not use spell [Death Grip] For Boss in Faction Champs Pvp Fight.
if use spell = Miss.

information:
Tanking classes can use taunt, but it only lasts until the NPC's drop aggro (which is all the time), and is susceptible to diminishing returns. Fixate taunts, Death Knights are very good at pinning down melee with Chains of Ice, Dark Command, and "Death Grip".

Reference: http://wowwiki.wikia.com/wiki/Faction_Champions

I tried to fix it but failed.

Os: Windows ServeR 2016

Rev Az: https://github.com/azerothcore/azerothcore-wotlk/commit/02d14df9b8d366ab4685442b4ececf5041c8f035

Moudels: Anticheat,Duel Reset

**Comment by Hir0shi** [comment]
Oh, tested

ConfirM!

need to fixed!

**Comment by talamortis** [comment]
wait, so is the npc error is is this a player error?

**Comment by HAANAAE** [comment]
Hi

@talamortis 

Don't Work  and  if  player class "death Knights" use spell [Death grip] server will to crashed!

Crash Log.
<details>

--- DEBUG: --- START

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff483e700 (LWP 14053)]
[New Thread 0x7ffff3c3d700 (LWP 14056)]
[New Thread 0x7ffff2abc700 (LWP 14060)]
[New Thread 0x7fffb4b3b700 (LWP 14063)]
[New Thread 0x7fffa5f3a700 (LWP 14064)]
[New Thread 0x7fffa5339700 (LWP 14065)]
[New Thread 0x7fffa4738700 (LWP 14066)]
[New Thread 0x7fffa3b37700 (LWP 14067)]
[New Thread 0x7fffa2f36700 (LWP 14068)]
[New Thread 0x7fffa2735700 (LWP 14069)]

Thread 5 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb4b3b700 (LWP 14063)]
0x00007fff9e7e8300 in ?? ()

--- DEBUG: BACKTRACE FULL

#0  0x00007fff9e7e8300 in ?? ()
No symbol table info available.
#1  0x000000000115d8a8 in spell_dk_death_grip::spell_dk_death_grip_SpellScript::HandleBaseDummy (this=0x7fff874c5000) at /home/azerothcore-wotlk/src/server/scripts/Spells/spell_dk.cpp:1614
        caster = 0x7fffa5384e80
        target = <optimized out>
        baseTarget = 0x7fff87a52000
        targetCreature = <optimized out>
#2  0x0000000000c7199f in Spell::CallScriptEffectHandlers (this=<optimized out>, effIndex=<optimized out>, mode=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:8060
        hookType = SPELL_SCRIPT_HOOK_EFFECT_HIT
#3  0x0000000000c668b6 in Spell::HandleEffects (this=0x7fff96035000, pUnitTarget=<optimized out>, mode=SPELL_EFFECT_HANDLE_HIT_TARGET, pItemTarget=<optimized out>, pGOTarget=<optimized out>, i=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:5256
No locals.
#4  Spell::DoSpellHitOnUnit (this=<optimized out>, unit=<optimized out>, effectMask=<optimized out>, scaleAura=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3095
No locals.
#5  0x0000000000c64faf in Spell::DoAllEffectOnTarget (this=0x7fff96035000, target=0x7fff94565b50) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:2616
        missInfo2 = <optimized out>
        effectUnit = 0x7fff87a52000
        caster = <optimized out>
        mask = 1 '\001'
        missInfo = <optimized out>
        spellHitTarget = <optimized out>
        procAttacker = <optimized out>
        procVictim = <optimized out>
        procEx = <optimized out>
#6  0x0000000000c6e6ac in Spell::handle_immediate (this=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3862
No locals.
#7  0x0000000000c6c69d in Spell::_cast (this=<optimized out>, skipCheck=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3793
        modOwner = <optimized out>
#8  0x0000000000c682bc in Spell::cast (this=0x7fff96035000, skipCheck=255) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3596
        modOwner = 0x7fffa5384e80
        lastMod = <optimized out>
#9  Spell::prepare (this=0x7fff96035000, targets=<optimized out>, triggeredByAura=0x0) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3514
        result = <optimized out>
#10 0x0000000000bb46df in WorldSession::HandleCastSpellOpcode (this=0x7fffa1779000, recvPacket=...) at /home/azerothcore-wotlk/src/server/game/Handlers/SpellHandler.cpp:445
        castCount = <optimized out>
        castFlags = <optimized out>
        mover = 0x7fffa5384e80
        spellInfo = <optimized out>
        targets = {m_targetMask = 2, m_objectTarget = 0x7fff87a52000, m_itemTarget = 0x0, m_objectTargetGUID = 17379391540184657766, m_itemTargetGUID = 0, m_itemTargetEntry = 0, m_src = {_position = {<Position> = {m_positionX = 567.199524, m_positionY = 96.9548874, m_positionZ = 394.741516, m_orientation = 0.525786638}, m_mapId = 4294967295}, _transportGUID = 0, _transportOffset = {m_positionX = 0, m_positionY = 0, m_positionZ = 0, m_orientation = 0}}, m_dst = {_position = {<Position> = {m_positionX = 567.199524, m_positionY = 96.9548874, m_positionZ = 394.741516, m_orientation = 0.525786638}, m_mapId = 4294967295}, _transportGUID = 0, _transportOffset = {m_positionX = 0, m_positionY = 0, m_positionZ = 0, m_orientation = 0}}, m_elevation = 0, m_speed = 0, m_strTarget = <incomplete type>, m_dstChannel = {_position = {<Position> = {m_positionX = 0, m_positionY = 0, m_positionZ = 0, m_orientation = 0}, m_mapId = 4294967295}, _transportGUID = 0, _transportOffset = {m_positionX = 0, m_positionY = 0, m_positionZ = 0, m_orientation = 0}}, m_objectTargetGUIDChannel = 0}
        spell = 0x7fff96035000
#11 0x0000000000c2ebad in WorldSession::Update (this=<optimized out>, diff=<optimized out>, updater=...) at /home/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:279
        _startMSTime = <optimized out>
        processedPackets = 0
        movementPacket = <optimized out>
        packet = 0x7fffa1746db0
#12 0x0000000000bcd1ee in Map::Update (this=<optimized out>, t_diff=<optimized out>, s_diff=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Maps/Map.cpp:669
        session = 0x7fff87a52000
        updater = {<PacketFilter> = {_vptr$PacketFilter = 0x133b8e0 <vtable for MapSessionFilter+16>, m_pSession = 0x7fffa1779000}, <No data fields>}
        player = 0x1b
        mapId = <optimized out>
        updater = <optimized out>
#13 0x0000000000bd29d0 in InstanceMap::Update (this=0x7fff98942980, t_diff=0, s_diff=0) at /home/azerothcore-wotlk/src/server/game/Maps/Map.cpp:2672
No locals.
#14 0x0000000000bda18e in MapUpdateRequest::call (this=0x7fff94566fb0) at /home/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:57
No locals.
#15 0x0000000000db84f9 in DelayExecutor::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/common/Threading/DelayExecutor.cpp:53
        rq = 0x7fff94566fb0
#16 0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
No symbol table info available.
#17 0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
No symbol table info available.
#18 0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
No symbol table info available.
#19 0x00007ffff62a0494 in start_thread (arg=0x7fffb4b3b700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7fffb4b3b700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736225064704, 2331853856394137676, 0, 140737488347583, 0, 140737354125376, -2332018131658125236, -2331874023190474676}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#20 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

--- DEBUG: INFO REGISTERS

rax            0x1b	27
rbx            0x7fffb4b3b700	140736225064704
rcx            0x22	34
rdx            0x0	0
rsi            0xffffffdc	4294967260
rdi            0x7fff87a52000	140735469133824
rbp            0x0	0x0
rsp            0x7fffb4b39800	0x7fffb4b39800
r8             0xfffffffffffffff8	-8
r9             0x7fffb4b39f48	140736225058632
r10            0x0	0
r11            0x0	0
r12            0x0	0
r13            0x7fffffffe1bf	140737488347583
r14            0x0	0
r15            0x7ffff7ffd040	140737354125376
rip            0x7ffff5541acf	0x7ffff5541acf <clone+63>
eflags         0x10216	[ PF AF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0

--- DEBUG: CALLS (x/32i $pc)

=> 0x7ffff5541acf <clone+63>:	mov    %rax,%rdi
   0x7ffff5541ad2 <clone+66>:	callq  0x7ffff55115e0 <__GI__exit>
   0x7ffff5541ad7 <clone+71>:	mov    0x2b039a(%rip),%rcx        # 0x7ffff57f1e78
   0x7ffff5541ade <clone+78>:	neg    %eax
   0x7ffff5541ae0 <clone+80>:	mov    %eax,%fs:(%rcx)
   0x7ffff5541ae3 <clone+83>:	or     $0xffffffffffffffff,%rax
   0x7ffff5541ae7 <clone+87>:	retq   
   0x7ffff5541ae8:	nopl   0x0(%rax,%rax,1)
   0x7ffff5541af0 <lseek64>:	mov    $0x8,%eax
   0x7ffff5541af5 <lseek64+5>:	syscall 
   0x7ffff5541af7 <lseek64+7>:	cmp    $0xfffffffffffff001,%rax
   0x7ffff5541afd <lseek64+13>:	jae    0x7ffff5541b00 <lseek64+16>
   0x7ffff5541aff <lseek64+15>:	retq   
   0x7ffff5541b00 <lseek64+16>:	mov    0x2b0371(%rip),%rcx        # 0x7ffff57f1e78
   0x7ffff5541b07 <lseek64+23>:	neg    %eax
   0x7ffff5541b09 <lseek64+25>:	mov    %eax,%fs:(%rcx)
   0x7ffff5541b0c <lseek64+28>:	or     $0xffffffffffffffff,%rax
   0x7ffff5541b10 <lseek64+32>:	retq   
   0x7ffff5541b11:	nopw   %cs:0x0(%rax,%rax,1)
   0x7ffff5541b1b:	nopl   0x0(%rax,%rax,1)
   0x7ffff5541b20 <__umount>:	xor    %esi,%esi
   0x7ffff5541b22 <__umount+2>:	jmpq   0x7ffff5541b30 <umount2>
   0x7ffff5541b27:	nopw   0x0(%rax,%rax,1)
   0x7ffff5541b30 <umount2>:	mov    $0xa6,%eax
   0x7ffff5541b35 <umount2+5>:	syscall 
   0x7ffff5541b37 <umount2+7>:	cmp    $0xfffffffffffff001,%rax
   0x7ffff5541b3d <umount2+13>:	jae    0x7ffff5541b40 <umount2+16>
   0x7ffff5541b3f <umount2+15>:	retq   
   0x7ffff5541b40 <umount2+16>:	mov    0x2b0331(%rip),%rcx        # 0x7ffff57f1e78
   0x7ffff5541b47 <umount2+23>:	neg    %eax
   0x7ffff5541b49 <umount2+25>:	mov    %eax,%fs:(%rcx)
   0x7ffff5541b4c <umount2+28>:	or     $0xffffffffffffffff,%rax

--- DEBUG: THREAD APPLY ALL BACKTRACE

Thread 11 (Thread 0x7fffa2735700 (LWP 14069)):
#0  0x00007ffff55420c3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff747c670 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#2  0x00007ffff747da9b in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.3.3.so
#3  0x00007ffff747f005 in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#4  0x00007ffff74bd272 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000c3981f in ReactorRunnable::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Server/WorldSocketMgr.cpp:160
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7fffa2735700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffa2f36700 (LWP 14068)):
#0  0x00007ffff55420c3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff747c670 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#2  0x00007ffff747da9b in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.3.3.so
#3  0x00007ffff747f005 in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#4  0x00007ffff74bd272 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000c3981f in ReactorRunnable::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Server/WorldSocketMgr.cpp:160
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7fffa2f36700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffa3b37700 (LWP 14067)):
#0  0x00007ffff62a97dd in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000db8bdb in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/thread:323
#2  ACORE::Thread::Sleep (msecs=<optimized out>) at /home/azerothcore-wotlk/src/common/Threading/Threading.cpp:110
#3  0x00000000009704da in AuctionListingRunnable::run (this=<optimized out>) at /home/azerothcore-wotlk/src/server/worldserver/WorldThread/WorldRunnable.cpp:119
#4  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff62a0494 in start_thread (arg=0x7fffa3b37700) at pthread_create.c:333
#6  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffa4738700 (LWP 14066)):
#0  0x00007ffff55420c3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff747c670 in ACE_Dev_Poll_Reactor::work_pending_i(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#2  0x00007ffff747da9b in ACE_Dev_Poll_Reactor::handle_events_i(ACE_Time_Value*, ACE_Dev_Poll_Reactor::Token_Guard&) () from /usr/lib/libACE-6.3.3.so
#3  0x00007ffff747f005 in ACE_Dev_Poll_Reactor::handle_events(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#4  0x00007ffff74bd272 in ACE_Reactor::run_reactor_event_loop(ACE_Time_Value&, int (*)(ACE_Reactor*)) () from /usr/lib/libACE-6.3.3.so
#5  0x000000000096ae84 in RARunnable::run (this=<optimized out>) at /home/azerothcore-wotlk/src/server/worldserver/RemoteAccess/RARunnable.cpp:68
#6  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff62a0494 in start_thread (arg=0x7fffa4738700) at pthread_create.c:333
#8  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffa5339700 (LWP 14065)):
#0  0x00007ffff553a3c3 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff776e27b in ?? () from /lib/x86_64-linux-gnu/libreadline.so.7
#2  0x00007ffff776e504 in rl_read_key () from /lib/x86_64-linux-gnu/libreadline.so.7
#3  0x00007ffff7756513 in readline_internal_char () from /lib/x86_64-linux-gnu/libreadline.so.7
#4  0x00007ffff7756d65 in readline () from /lib/x86_64-linux-gnu/libreadline.so.7
#5  0x0000000000969fda in CliRunnable::run (this=<optimized out>) at /home/azerothcore-wotlk/src/server/worldserver/CommandLine/CliRunnable.cpp:148
#6  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff62a0494 in start_thread (arg=0x7fffa5339700) at pthread_create.c:333
#8  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffa5f3a700 (LWP 14064)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e11a in ACE_Condition<ACE_Thread_Mutex>::wait() () from /usr/lib/libACE-6.3.3.so
#2  0x0000000000bd9d42 in MapUpdater::wait (this=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:111
#3  0x0000000000bd91ac in MapManager::Update (this=<optimized out>, diff=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Maps/MapManager.cpp:266
#4  0x0000000000cbfd01 in World::Update (this=0x7ffff4ea4008, diff=11) at /home/azerothcore-wotlk/src/server/game/World/World.cpp:2080
#5  0x0000000000970253 in WorldRunnable::run (this=<optimized out>) at /home/azerothcore-wotlk/src/server/worldserver/WorldThread/WorldRunnable.cpp:44
#6  0x00007ffff5dcce6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff62a0494 in start_thread (arg=0x7fffa5f3a700) at pthread_create.c:333
#8  0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffb4b3b700 (LWP 14063)):
#0  0x00007fff9e7e8300 in ?? ()
#1  0x000000000115d8a8 in spell_dk_death_grip::spell_dk_death_grip_SpellScript::HandleBaseDummy (this=0x7fff874c5000) at /home/azerothcore-wotlk/src/server/scripts/Spells/spell_dk.cpp:1614
#2  0x0000000000c7199f in Spell::CallScriptEffectHandlers (this=<optimized out>, effIndex=<optimized out>, mode=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:8060
#3  0x0000000000c668b6 in Spell::HandleEffects (this=0x7fff96035000, pUnitTarget=<optimized out>, mode=SPELL_EFFECT_HANDLE_HIT_TARGET, pItemTarget=<optimized out>, pGOTarget=<optimized out>, i=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:5256
#4  Spell::DoSpellHitOnUnit (this=<optimized out>, unit=<optimized out>, effectMask=<optimized out>, scaleAura=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3095
#5  0x0000000000c64faf in Spell::DoAllEffectOnTarget (this=0x7fff96035000, target=0x7fff94565b50) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:2616
#6  0x0000000000c6e6ac in Spell::handle_immediate (this=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3862
#7  0x0000000000c6c69d in Spell::_cast (this=<optimized out>, skipCheck=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3793
#8  0x0000000000c682bc in Spell::cast (this=0x7fff96035000, skipCheck=255) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3596
#9  Spell::prepare (this=0x7fff96035000, targets=<optimized out>, triggeredByAura=0x0) at /home/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3514
#10 0x0000000000bb46df in WorldSession::HandleCastSpellOpcode (this=0x7fffa1779000, recvPacket=...) at /home/azerothcore-wotlk/src/server/game/Handlers/SpellHandler.cpp:445
#11 0x0000000000c2ebad in WorldSession::Update (this=<optimized out>, diff=<optimized out>, updater=...) at /home/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:279
#12 0x0000000000bcd1ee in Map::Update (this=<optimized out>, t_diff=<optimized out>, s_diff=<optimized out>) at /home/azerothcore-wotlk/src/server/game/Maps/Map.cpp:669
#13 0x0000000000bd29d0 in InstanceMap::Update (this=0x7fff98942980, t_diff=0, s_diff=0) at /home/azerothcore-wotlk/src/server/game/Maps/Map.cpp:2672
#14 0x0000000000bda18e in MapUpdateRequest::call (this=0x7fff94566fb0) at /home/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:57
#15 0x0000000000db84f9 in DelayExecutor::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/common/Threading/DelayExecutor.cpp:53
#16 0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#17 0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#18 0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#19 0x00007ffff62a0494 in start_thread (arg=0x7fffb4b3b700) at pthread_create.c:333
#20 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7ffff2abc700 (LWP 14060)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f9bf in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096e661 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4e9e280, first_item=@0x7ffff2aba678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000dbcb03 in DatabaseWorker::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/common/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7ffff2abc700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7ffff3c3d700 (LWP 14056)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f9bf in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096e661 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4e9e140, first_item=@0x7ffff3c3b678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000dbcb03 in DatabaseWorker::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/common/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7ffff3c3d700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7ffff483e700 (LWP 14053)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff746e1b5 in ACE_Condition<ACE_Thread_Mutex>::wait(ACE_Thread_Mutex&, ACE_Time_Value const*) () from /usr/lib/libACE-6.3.3.so
#2  0x000000000096f9bf in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::wait_not_empty_cond (this=<optimized out>, timeout=<optimized out>) at /usr/include/ace/Message_Queue_T.cpp:1776
#3  0x000000000096e661 in ACE_Message_Queue<ACE_MT_SYNCH, ACE_System_Time_Policy>::dequeue_head (this=0x7ffff4e9e000, first_item=@0x7ffff483c678: 0x0, timeout=0x0) at /usr/include/ace/Message_Queue_T.cpp:1968
#4  0x00007ffff74527a5 in ACE_Activation_Queue::dequeue(ACE_Time_Value*) () from /usr/lib/libACE-6.3.3.so
#5  0x0000000000dbcb03 in DatabaseWorker::svc (this=<optimized out>) at /home/azerothcore-wotlk/src/common/Database/DatabaseWorker.cpp:30
#6  0x00007ffff74cdf6d in ACE_Task_Base::svc_run(void*) () from /usr/lib/libACE-6.3.3.so
#7  0x00007ffff74cee86 in ACE_Thread_Adapter::invoke_i() () from /usr/lib/libACE-6.3.3.so
#8  0x00007ffff74ceda9 in ACE_Thread_Adapter::invoke() () from /usr/lib/libACE-6.3.3.so
#9  0x00007ffff62a0494 in start_thread (arg=0x7ffff483e700) at pthread_create.c:333
#10 0x00007ffff5541acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7fe2f00 (LWP 14042)):
#0  0x00007ffff62a16cd in pthread_join (threadid=140735977596672, thread_return=0x0) at pthread_join.c:90
#1  0x00007ffff5dcd0f7 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000db8aef in ACORE::Thread::wait (this=0x7fffffffe6d0) at /home/azerothcore-wotlk/src/common/Threading/Threading.cpp:46
#3  0x0000000000972f96 in Master::Run (this=<optimized out>) at /home/azerothcore-wotlk/src/server/worldserver/Master.cpp:302
#4  0x0000000000971749 in main (argc=<optimized out>, argv=<optimized out>) at /home/azerothcore-wotlk/src/server/worldserver/Main.cpp:137

--- DEBUG: --- STOP
</details>

**Comment by talamortis** [comment]
@HAANAAE could you please change line 1614 to this

`if (targetCreature && (targetCreature->isWorldBoss() || targetCreature->IsDungeonBoss() && targetCreature->GetEntry() != EntryCheck(targetCreature->GetEntry())))` as im guessing this is a Linux problem as im not getting any error on windows machine.

**Comment by HAANAAE** [comment]
i changed to https://github.com/azerothcore/azerothcore-wotlk/commit/4e27109cea5aa7e85afbf3b1730abc1286f75caa

worked. thank you.
