### ISSUE TITLE
Warsong lumber camp, Horde scouts refer to themselves as Dark Iron

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#9820]
Noticed on Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/2635 Confirmed on a clean Local.
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Occasionally refers to themselves as Dark Iron when aggrod
![image](https://user-images.githubusercontent.com/68164076/146852575-991f703a-1359-4c2c-9f3a-82b34e29a8ef.png)
![image](https://user-images.githubusercontent.com/68164076/146853092-b58b3995-9e15-42f0-ad31-1861b580e623.png)

### Expected Blizzlike Behaviour

They shouldn't say anything. At least, nothing I found in my research. They are obviously not Dark Iron.

### Source

https://wowpedia.fandom.com/wiki/Horde_Scout WOWpedia will give any chat said by npc's, this had none.
For example: https://wowpedia.fandom.com/wiki/Edwin_VanCleef_(tactics)#Quotes
https://wowpedia.fandom.com/wiki/Defias_Messenger#Quotes

### Steps to reproduce the problem

Be alliance
.go c 32979, 32978, 33000, 33001, 33002, there are more but you get the idea.
.gm off
.gm on
Repeat as nessecary until the Scout says it.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
Guys it would be helpful if you supplied creature entry with your issues so we don't have to go find them.

**Comment by malcrom** [comment]
```SELECT * FROM `creature_text` WHERE `CreatureID` IN (11680);```
Gives one creature text "Time to die, $c!"

**Comment by Stump876** [comment]
Will do. Where would I find that?

**Comment by patou01** [comment]
I searched for the text in broadcast_text, found the ID to be 1934, checked the following
` SELECT * FROM `creature_text` WHERE `BroadcastTextId` = 1934; `
![image](https://user-images.githubusercontent.com/2592673/147407743-06659f6c-8dce-45b0-8724-d3a3ed86a2d7.png)

This gives the horde scout. 
![image](https://user-images.githubusercontent.com/2592673/147407752-b5d15018-7810-4839-b5c1-3747ecc3e7f1.png)

The creature entry you get in .npc info, you can see in your screenshot the "Entry 11680" part.

So I guess the fix is to correct the broadcasttextid. Could be worth checking who the Jailor Marlgen and Captain Beld are, just in case they need fixed too.

broadcasttext normally has precedence over creature_text, so the correct value needs to be found and the npc corrected.
