### ISSUE TITLE
Various zones is spawn double-triple veins

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9821]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2613

Entering this zone I found that every single tin/silver node, had both ore types spawned on top of each other and there were LOTS of these all over, allowing players to accumulate way too much silver and gems (which drop more frequently from silver).

See this brief video of the double nodes (and I even saw one with copper, tin, and silver all stacked):

https://www.screencast.com/t/8Cm7Gem0lj

Additionally, it appears that many normally Copper nodes spawn as tin and silver as well. The zone is dominated by ludicrous amounts of silver. Using data from gathermate, and displaying this data in Carbonite map, it seems to confirm that normally copper nodes are incorrectly spawning tin/silver. There are some copper nodes, but not many.

Tester:

The issue is confirmed. Atleast in 2 zones is spawning double-triple veins. Loch Modan, Hillsbard Foothills

![WoWScrnShot_122121_134648](https://user-images.githubusercontent.com/85256266/146917620-3c0188ab-b494-433f-907d-3a15ee364d7d.jpg)
![WoWScrnShot_122121_134719](https://user-images.githubusercontent.com/85256266/146917627-1b302773-c7ab-4d03-8bac-c596894e9a3a.jpg)

### Expected Blizzlike Behaviour

Should spawn only 1n vein

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by claudiodfc** [comment]
This is a known issue. No point in opening up more issue reports like this once since I have an issue open to import all the vanilla nodes. Until someone with a bigger brain helps me import Dynamic spawning, not much can be done to fix this issue.

**Comment by Shineslippers** [comment]
That's new one i assume. It wasn't exist a while ago.

**Comment by claudiodfc** [comment]
Refer to #9431
