### ISSUE TITLE
Cheap Shot focus macro not working

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#9822]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2638

When using a `/cast [target=focus] cheap shot` macro it forces you to change targets to your focus target.

Tester:

The bug is confirmed after testing on local AC.

### Expected Blizzlike Behaviour

A `/cast [target=focus]` macro should cast the spell at your focus target while maintaining your current target.

### Source

On chromiecraft
`/cast [target=focus] Gouge`
and
`/cast [target=focus] Kick`
work as intended as do several other focus macros but cheap shot does not.

### Steps to reproduce the problem

1. `.learn 1833 all` for Cheap Shot
2. `.learn 1766 all` for Kick
3. `/focus` on an enemy
4. target another enemy

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
Same with Sinister Strike.

**Comment by UltraNix** [comment]
It might be very hard to fix it as client on its own selects the focus and starts attacking (mainly because of clientside attr `SPELL_ATTR1_INITIATE_COMBAT`)
@ishidinho Do you have any video of this from wotlk era?

**Comment by UltraNix** [comment]
Jus tested on warmane (@keldinx said it works okay there) and it works the same as here. So I don't see a bug here.
