### ISSUE TITLE
EscortAI Console error

### ISSUE THREAD

**Issue by Meramaf** [azerothcore/azerothcore-wotlk#9841]
### Current Behaviour

EscortAI script: npc_azure_captain, creature entry 30666 attempts to Start while in combat
EscortAI script: npc_azure_sorceror, creature entry 30667 attempts to Start while in combat

![image](https://user-images.githubusercontent.com/76571216/147054869-3a3f0fcd-8662-468d-b425-25fd8139e547.png)

hm... after server restart no errors....

### Expected Blizzlike Behaviour

no errors

### Steps to reproduce the problem

1. .go c 102911
2. Reach Azure Captain, Azure Sorceror
3. Check Console

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3c571121784272b968a7af93aab338f6c7e5ac9e

### Operating system

Windows 10 x64, Ubuntu 20

**Comment by Shineslippers** [comment]
Can you provide more info? Do they start attack door or when it happend?
