### ISSUE TITLE
Winter Veil: Gifts available too early

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9853]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2658

I was able to open the gifts in Ironforge at 09:20, December 23rd, and get the achievement [He knows if you've been naughty](https://wowgaming.altervista.org/aowow/?achievement=1689).

Tester:

The issue is confirmed. [Winter Veil: Gifts](https://wowgaming.altervista.org/aowow/?event=52) event `Start: 12/23 at 06:00`

| eventEntry | start_time | end_time | length | description | 
| ---: | --- | --- | ---: | --- | 
| 52 | 2015-12-25 12:00:00 | 2030-12-31 12:00:00 | 11700 | Winter Veil: Gifts | 

### Expected Blizzlike Behaviour

The Winter Veil: Gifts event should start on December 25 and lasts up to 2nd january

### Source

Wowpedia [Feast of Winter Veil](https://wowpedia.fandom.com/wiki/Feast_of_Winter_Veil?oldid=2335323#Winter_Veil_presents])
> Near the end of the Feast of Winter Veil (December 25th through January 2nd), various gifts are available underneath the trees near Greatfather Winter in Ironforge, and Great-father Winter in Orgrimmar.

Experience and some comments on the wikis:
[Ticking Present](https://classic.wowhead.com/item=21327/ticking-present)
[A Festive Gift](https://classic.wowhead.com/quest=8803/a-festive-gift)
[Carefully Wrapped Present](https://classic.wowhead.com/item=21191/carefully-wrapped-present)
[Gently Shaken Gift](https://classic.wowhead.com/item=21270/gently-shaken-gift)
[Gaily Wrapped Present](https://classic.wowhead.com/item=21310/gaily-wrapped-present)

### Steps to reproduce the problem

```sql
SELECT ge.eventEntry, ge.start_time, ge.end_time, ge.length, ge.description
FROM `game_event` ge
WHERE evententry = 52
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by UltraNix** [comment]
2016 and 2020 were leap yers - that's why.
