### ISSUE TITLE
It's never work for me in months when i bash (always the same sql error but no fix)

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#9855]
### Current Behaviour

`Applying update "2021_11_30_02.sql" '06A3ED6'...
ERROR 1064 (42000) at line 4: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE `attributes` & @flag = @flag);

UPDATE version_db_world SET date = '...' at line 18

Applying of file '/home/azerothcore/data/sql/updates/db_world/2021_11_30_02.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.`

### Expected Blizzlike Behaviour

bash /home/azerothcore/apps/db_assembler/db_assembler.sh
cannot work

### Steps to reproduce the problem

get the newest version, rebuild project, when run bash /home/azerothcore/apps/db_assembler/db_assembler.sh

### AC rev. hash/commit

bash /home/azerothcore/apps/db_assembler/db_assembler.sh

### Operating system

ubuntu 20, mysql  Ver 15.1 Distrib 10.3.32-MariaDB

**Comment by Nyeriah** [comment]
MariaDB versions lower than 10.5 are not supported, you must update to at least 10.5

**Comment by yuanf225** [comment]
It is best to upgrade to mariadb 10.6
