### ISSUE TITLE
[NPC/Profession] High Marshal Whirlaxis is not skinnable

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#9863]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2661

NPC [High Marshal Whirlaxis](https://wowgaming.altervista.org/aowow/?npc=15204#skinning) is not skinnable.
Try to skin with skinning 315, skinning icon shows up when mouseover, but skinning interaction does not work.

Tester:

The issue is confirmed.

![WoWScrnShot_122321_175719](https://user-images.githubusercontent.com/62797536/147272891-d93e1c66-164d-4ca0-84ab-208bd1aedf50.jpg)
Skinning symbol on mouseover and tooltip shows that it should be skinnable.

![WoWScrnShot_122321_175734](https://user-images.githubusercontent.com/62797536/147272945-45aeca3f-8ddf-4d76-9eb8-b97cc0ed575d.jpg)
After right-clicking you target the corpse, but no skinning is happening.

### Expected Blizzlike Behaviour

NPC should be skinnable with skinning 315.

### Steps to reproduce the problem

1. `.setskill 393 405`
2. `.learn 50305`
3. `.additem 12709`
4. `.go gameobject 49452`
5. `.additem 20406`
6. `.additem 20407`
7. `.additem 20408`
8. `.additem 20422`
9. `.additem 20451`
10. Equip these five items
11. Summon boss on Wind Stone

### Extra Notes

NPC: https://wowgaming.altervista.org/aowow/?npc=15204#skinning

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c70cc855ff3d2724a0e0a3866b6a43db1f2faddb

### Operating system

Ubuntu

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
The issue is there is no Skinning Loot table associated with the NPC. WIll confer to a few sniffs.

**Comment by acidmanifesto** [comment]
Ok. so a follow up. Reviewing of Datamining records and sniffs. This npc was never lootable to begin with and never was in any of the expansions. PR has been put in the correct the flag and remove the loot table and should no longer give the skinning icon.
The referencing link was to a pserver with none blizzlike and custom loot tables of various kinds to better suit their play style of sorts with their population but was not at all in line with the BlizzLike approach.
