### ISSUE TITLE
Updates characters trinitycore

### ISSUE THREAD

**Issue by luldev1** [azerothcore/azerothcore-wotlk#987]
Kind time of day for everyone, not long ago discovered the problem of transferring character bases from Trinity to Azeroth, the problem consists in displaying the nickname and the ability to write to the chat, so the character can not be found through the pin and change his reason, faction, nickname or appearance

**Comment by luldev1** [comment]
In this case, all the updates were filled, the server started without errors

**Comment by pedroevil51** [comment]
How did you transfer from trinity to az?

**Comment by BarbzYHOOL** [comment]
I don't think many people can help you with this, but if you manage to do it, please describe it here
