### ISSUE TITLE
Server is not showing visual effect of buffs/debuffs in some circumstances

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9870]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2403

Noted inside warsong gulch, but apparently it affects players in istance too
It happens casually and, apparently without any cause, that you can't see any buff/debuff on ally and enemy players.
This affect the graphical effect on the characters, as an example the flag carrier appears without the flag and the ally rogue in stealth appear without the 'transparent/spectral' effect.
Also some buff/debuff can persist and you see a character with mounted-ground run animation or someone alive but with death debuff and death effect on.
This isn't a client side problem, infact seems casual, like a problem on sincronization of auras ( i don't know exactly).
Also appears to affect players out bg too
I have some suspect that is connected to the phase system of players

Tester:

The issue is confirmed. Server is not showing visual effect of buffs/debuffs in some circumstances. In this case if player's target out of view(distance).

https://user-images.githubusercontent.com/85256266/147358453-44bfe2fc-6afd-4210-8d6a-a4c0841b11e7.mp4

### Expected Blizzlike Behaviour

Just dispaly buff/debuff and effect correctly

### Steps to reproduce the problem

join warsong

target 
.go xyz 1172.485718 1459.140381 309.199585

player
.go xyz 1166.926270 1459.909424 310.260986
.aura 31224 on target
.go xyz 933.330994 1433.719971 345.536011
.go xyz 1166.926270 1459.909424 310.260986

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Algorak** [comment]
I can only confirm that buffs like Bok Bom etc are active, but we often don't get to see them ourselves!


Buffs on bosses also currently have the problem that the consequences of their own spells are also incorrect.

Blizzard ranked it so that the spells with the longest durations were always number 1, and the shorter the duration, the further down they were ranked! The same spells as live bomb mages were always kept fairly active so it was always in 2-3 spots. Would be great if you guys could fix the problem of buffs and de-buffs in general. Class auras can also often be stacked multiple times!


This causes bugs where your own class buffs don't show up or 2-3 times!
