### ISSUE TITLE
Wind Stone summons issues

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9872]
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2619

1. Abyssal Council summoned boss does not automatically engage in combat with summoner.
2. Abyssal Council summons (Templars, Dukes, Lords) are not automatically tagged for the summoner and his group, which enables outside players to steal the tag and waste summoner's materials.
3. Abyssal Council summons do not despawn when a wipe occurs (mob resets by being kited too far or because group dies).

TBC screenshots:
<details><summary>Spoiler</summary>

Proof that summoner is targeted when combat starts (hand mouseover icon turns to sword), from long range and mob is greyed out with 100% hp (tagged for summoner)
![proofs0](https://user-images.githubusercontent.com/65633456/146686494-178d0de5-b27c-463c-b79d-1e482f042406.JPG)
![proofs1](https://user-images.githubusercontent.com/65633456/146686513-afd8cd05-5e24-47be-a0ea-933cf9d55816.JPG)
![proofs2](https://user-images.githubusercontent.com/65633456/146686524-bbe945c0-06d6-432c-8356-ececbcb7820f.JPG)

hard to tell from here, but mob despawns when reset (kited too far from leash, mob drops target in 2nd pic, despawn in 3rd)
i can record despawn on death but at this point i hope it isnt necessary
![proofs3](https://user-images.githubusercontent.com/65633456/146686938-2010a3a9-9af0-40e9-8242-a746992503c0.JPG)
![proofs4](https://user-images.githubusercontent.com/65633456/146686941-66b3234e-2844-43c1-818b-edc997356f5c.JPG)
![proofs5](https://user-images.githubusercontent.com/65633456/146686944-c307115f-b309-4421-9f09-efa70d61c6de.JPG)

</details>

Tester:

1. Abyssal Council summoned boss automatically engage in combat with summoner without delay for his short RP
2. Abyssal Council summoned boss doesn't tagged for the summone/ group. Another player/group could steal summon
3. Abyssal Council summons do not despawn

NPC to check:'
<details><summary>Spoiler</summary>

https://wowgaming.altervista.org/aowow/?npc=15203
https://wowgaming.altervista.org/aowow/?npc=15204
https://wowgaming.altervista.org/aowow/?npc=15205
https://wowgaming.altervista.org/aowow/?npc=15206
https://wowgaming.altervista.org/aowow/?npc=15207
https://wowgaming.altervista.org/aowow/?npc=15208
https://wowgaming.altervista.org/aowow/?npc=15209
https://wowgaming.altervista.org/aowow/?npc=15211
https://wowgaming.altervista.org/aowow/?npc=15212
https://wowgaming.altervista.org/aowow/?npc=15220
https://wowgaming.altervista.org/aowow/?npc=15305
https://wowgaming.altervista.org/aowow/?npc=15307

</details>

https://user-images.githubusercontent.com/85256266/147361704-f955fbb5-1289-4507-b5b6-75ff26d14406.mp4

### Expected Blizzlike Behaviour

1. When a player summons a templar, duke or lord via Wind Stone in Silithus, the summoned boss should automatically engage in combat with the summoner, but after his short RP.

2. The summoned boss should be automatically tagged for the summoner (and his group) when boss engages in combat.

3. When the summoned boss resets, the boss should immediately despawn - players only get one chance to defeat it.

### Source

Tested on retail TBC Classic, behaviour will be the same all throughout the game versions.

### Steps to reproduce the problem

.go c 42955
.additem 20406
.additem 20407
.additem 20408
.additem 20419
wear items
use [Lesser Wind Stone] near

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by malcrom** [comment]
These are not windstone summon issues. the npc summons fine. These are creature AI issues.

**Comment by 55Honey** [comment]
We need a quick solution for it, i don't mind If it's somewhat sorry for now, as long as it solves the issues of
1) the mob tag being possibly stolen
2) Grace period before Combat Starts
3) variable re-spawn time of wind Stones (not mentioned in the original issue)
Wowhead comments state the spawn time is irregular. The best guess based on the available references is, it should be randomized between 3-4h instead of fixed to 3h.

**Comment by Eronox** [comment]
@55Honey Accordingly to wowwiki, it is correct as it is set today, for the greater wind stones:

> The Greater Wind stone will respawn in 3 hours from when you summon a Royal.

**Comment by 55Honey** [comment]
Thanks for checking on this Eronox. I've been looking at https://classic.wowhead.com/object=180466/greater-wind-stone#comments
,W
where specific timers were measured.
