### ISSUE TITLE
build error:'ElunaEventMgr.h' file not found

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#9875]
### Current Behaviour

i already get the newest version, but cannot build 

[ 96%] Building CXX object modules/CMakeFiles/modules.dir/mod-eluna-lua-engine/src/ElunaLuaEngine_SC.cpp.o
/home/azerothcore/modules/mod-eluna-lua-engine/src/ElunaLuaEngine_SC.cpp:19:10: fatal error: 'ElunaEventMgr.h' file not found
#include "ElunaEventMgr.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:160: modules/CMakeFiles/modules.dir/mod-eluna-lua-engine/src/ElunaLuaEngine_SC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1256: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
root@cc:/home/azerothcore/build# 
root@cc:/home/azerothcore/build# cd ../
root@cc:/home/azerothcore# cd modules/mod-eluna-lua-engine
root@cc:/home/azerothcore/modules/mod-eluna-lua-engine# git checkout master
M       conf/dist/config.sh
Already on 'master'
Your branch is up to date with 'origin/master'.
root@cc:/home/azerothcore/modules/mod-eluna-lua-engine# cd LuaEngine
root@cc:/home/azerothcore/modules/mod-eluna-lua-engine/LuaEngine# git checkout master
M       conf/dist/config.sh
Already on 'master'
Your branch is up to date with 'origin/master'.
root@cc:/home/azerothcore/modules/mod-eluna-lua-engine/LuaEngine# git pull
Already up to date.

### Expected Blizzlike Behaviour

build

### Steps to reproduce the problem

build

### AC rev. hash/commit

OK

### Operating system

ubuntu 21

**Comment by Nyeriah** [comment]
Please rerun CMAKE and try again. You must rerun it whenever you add or remove a module, such as Eluna.

**Comment by 5266869** [comment]
> 

i did that so many times. alse cannot work

**Comment by yuanf225** [comment]
Check if the eluna file exists, because the file path is changed

**Comment by 5266869** [comment]
> Check if the eluna file exists, because the file path is changed

it helps me. it is changed.
