### ISSUE TITLE
[Raid/Ulduar] Boss Hodir Can not Be Killed

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#9876]
### Current Behaviour

In raid Ulduar , Encount of Boss Hodir(32845)
Q1:player cannot see the chest after hodir 
Q2:hunter make a fake death then both 2 chest appeared even in 10 man mode .
Q3:after enter combat a whilel boss cast two large ice circle ,after ice falled, player whereever was forzen , then boss get evade.

### Expected Blizzlike Behaviour

1.player should see  chest after hodir before enter combat
2.only 1 chest should be visible in 10 man mode
3.player on the circle where the big two ice falled, should not be frozen;

### Steps to reproduce the problem

1.get a hunter character
2.go c id 32845 , in 10 man and 25 man mode
3.see chest behind hodir
4.in combat and make a fake death , see chest behind hodir
5.keep fight for a while and walk on the large ice circle after big ice falled , while hodir cast freez, see if player on ice circle  be frozen, and boss reset.

### AC rev. hash/commit

51a9efa577c2+

### Operating system

Ubuntu 20.04

**Comment by claudiodfc** [comment]
It's true, I confirm this.

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/e2d7dc9bd7fc636469e46b82587a92f43e7825d9  no this bug
