### ISSUE TITLE
acore_world.spellitemenchantment_dbc do not work

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#9878]
### Current Behaviour

INSERT INTO `spellitemenchantment_dbc` (`ID`, `Charges`, `Effect_1`, `Effect_2`, `Effect_3`, `EffectPointsMin_1`, `EffectPointsMin_2`, `EffectPointsMin_3`, `EffectPointsMax_1`, `EffectPointsMax_2`, `EffectPointsMax_3`, `EffectArg_1`, `EffectArg_2`, `EffectArg_3`, `Name_Lang_enUS`, `Name_Lang_enGB`, `Name_Lang_koKR`, `Name_Lang_frFR`, `Name_Lang_deDE`, `Name_Lang_enCN`, `Name_Lang_zhCN`, `Name_Lang_enTW`, `Name_Lang_zhTW`, `Name_Lang_esES`, `Name_Lang_esMX`, `Name_Lang_ruRU`, `Name_Lang_ptPT`, `Name_Lang_ptBR`, `Name_Lang_itIT`, `Name_Lang_Unk`, `Name_Lang_Mask`, `ItemVisual`, `Flags`, `Src_ItemID`, `Condition_Id`, `RequiredSkillID`, `RequiredSkillRank`, `MinLevel`)
VALUES
	(9001, 0, 5, 0, 0, 230, 20, 20, 230, 20, 20, 36, 29, 30, '+230 Haste Rating', '2301', '2302', '2303', '2304', '2305', '2306', '2307', '2308', '2309', '2310', '2311', '2312', '2313', '2314', '2315', 16712190, 0, 0, 0, 0, 0, 0, 0);

i made a new enchantment, +230 Haste Rating is worked, but it donot displayed on the equipment or weapon.
what can i do let it display, thx.

### Expected Blizzlike Behaviour

display

### Steps to reproduce the problem

enchant

### AC rev. hash/commit

enchant

### Operating system

ubuntu 21

**Comment by Winfidonarleyan** [comment]
Need make path for client
