### ISSUE TITLE
Feature:  (Core\Creature\Waypoint) Implement Smooth Transition Waypoint System

### ISSUE THREAD

**Issue by acidmanifesto** [azerothcore/azerothcore-wotlk#9879]
### Describe your feature request or suggestion in detail

Cherry-pick from TC CPP as it is the only core that has it working. It allows npc movement per waypoint id to be either smooth or current. Smooth Transition will work like how flight travel between flight managers are currently, not momentary pause when you hit waypoints.

### Describe a possible solution to your feature or suggestion in detail

Following Commits referencing it seems doable but very VERY indepth and will require some additional core modifications based on the slight differences between the two cores and structures.
Commits identified are as followed:
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/c808b981f7ae0e3ac6f0b879223bc73e3afa3ef2
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/d5f9b8c26f50e2fa085de28d8da1cc4c169ea2ae
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/e2237624f6a190f78d980d63952348e51ee94704
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/b236bd39df6710783f64c6c6339b7ca4e4cf98a2

**Comment by Kitzunu** [comment]
Will close in favor of https://github.com/azerothcore/azerothcore-wotlk/issues/10096 as it contains way more commits :)
