### ISSUE TITLE
All levels of spells consume the same mana

### ISSUE THREAD

**Issue by adink1** [azerothcore/azerothcore-wotlk#9883]
### Current Behaviour

All levels of spells consume the same mana, Only some level 1 mana costs are displayed correctly.

### Expected Blizzlike Behaviour

The mana cost of different levels should be different.

### Source

Just learn a few magic, you will find that the mana cost of level 1 is actually the same as that of level 5.

### Steps to reproduce the problem

1. Upgrade to level 20
2. Learn spells
3. Open the skill book and check the mana cost

### AC rev. hash/commit

AzerothCore rev. d2950b21b913 2021-12-25 20:09:15 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 50734
Using CMake version: 3.16.3
Compiled on: Linux 5.11.0-43-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in data/maps. Total size: 252191207 bytes
vmaps directory located in data/vmaps. Total size: 658130721 bytes
mmaps directory located in data/mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE zhTW
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_12_25_03
Using Character DB Revision: 2021_10_14_00
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Ubuntu20.04

**Comment by patou01** [comment]
I believe this is what you're after, so unless that's been removed, it's not a bug.
https://www.wowhead.com/forums/topic/mana-changes-no-more-downranking-36678
