### ISSUE TITLE
eluna CastSpell error: can not cumulative

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#9885]
### Current Behaviour

for i=1, 9000, 9 do player:CastSpell(player, 19984) end
two months ago i can use this add 9000 strength
but now it is only add 9 strength
it look like do not cumulative
why is that ? i want to add 9000, what should i do?
thanks.

### Expected Blizzlike Behaviour

9000

### Steps to reproduce the problem

9000

### AC rev. hash/commit

9000

### Operating system

ubuntu 21

**Comment by Kitzunu** [comment]
Add commit hash
