### ISSUE TITLE
eluna CastSpell error: can not cumulative

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#9890]
### Current Behaviour

for i=1, 9000, 9 do player:CastSpell(player, 19984) end
two months ago i can use this add 9000 strength
but now it is only add 9 strength
it look like do not cumulative
why is that ? i want to add 9000, what should i do?
thanks.

### Expected Blizzlike Behaviour

add 9000 strength but 9

### Steps to reproduce the problem

newest version build

### AC rev. hash/commit

commit 08b147765f5c8d72d5e2cd204745a4a9f7a7de7d (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Wed Aug 11 00:17:26 2021 +0000

    chore(DB): import pending files
    
    Referenced commit(s): 166ccc4f4f6ddbca9b11f6d4be31fb86638a28b1

this worked, but the newest do not.

### Operating system

ubuntu 21

**Comment by Shineslippers** [comment]
I guess it's related to this fix. So there is no issue.

**Comment by Shard-MW** [comment]
It's not an issue, this spell isn't cumulative (doesn't stacks). So it works as intendend.
