### ISSUE TITLE
Core/Threading: Rewrite Threading system [$150]

### ISSUE THREAD

**Issue by Yehonal** [azerothcore/azerothcore-wotlk#99]
I open this issue to keep trace of the status for threading system rewriting

In few words we need to switch from ACE to c++11 libraries ( not boost ) 

cmangos do it 1 year ago with following main commits:
- [ ]  [thread rewriting](https://github.com/cmangos/mangos-wotlk/commit/b73488d94303fa0c23005f802e749300217fb398) 
- [x]  [atomic types](https://github.com/cmangos/mangos-wotlk/commit/835e2a02b11a5f4e511461b7ff790190b3f83de3)
- [ ]  [mutexes and locks](https://github.com/cmangos/mangos-wotlk/commit/8ae67274a754f821f0bea6a5f771eab3df764a57)

I hope someone can help
##

**Comment by Eliminationzx** [comment]
any news?

**Comment by Pondaveia** [comment]
People are still deciding if we need boost or not for sockets. There's a discussion going on about C++11 vs Boost. Right @FrancescoBorzi

**Comment by Eliminationzx** [comment]
My suggestion - **AzerothCore**  should support **boost**.
This will allow us to easily import some commits from TrinityCore and also **boost** have many features that we can use for code optimization.  But it will require a lot of work.

**Comment by FrancescoBorzi** [comment]
I'm not against Boost. My opinion is just to use standard modern C++ wherever possible instead of other libs. I understand this is not always easy or possible so in some cases we might still need Boost and/or another lib to replace ACE.

**Comment by Viste** [comment]
Don't need a boost like that in trinity. Only for some elements

**Comment by Viste** [comment]
with C++14 i think boost not needed at al

**Comment by FrancescoBorzi** [comment]
Commits from @namreeb at CMaNGOS might be useful for this task: https://github.com/cmangos/mangos-wotlk/commits?after=b1ad3bb4e616537a167b9abd191a3a55499d7b50+69&author=namreeb

**Comment by FrancescoBorzi** [comment]
Commits from @leak at TrinityCore also might be useful: https://github.com/TrinityCore/TrinityCore/commits?author=leak&before=16b39a448acbe8ace88550a367be8e6bf565b00d+105

For example: https://github.com/TrinityCore/TrinityCore/commit/eb36acd1522a2e5b8a7d2b4b4a67fc34fc777f03 and https://github.com/TrinityCore/TrinityCore/commit/d39a013b6b979a5158bf86c37a197cb902b2c2f9
