### ISSUE TITLE
db_assembler: readarray option -d is invalid

### ISSUE THREAD

**Issue by Bogir** [azerothcore/azerothcore-wotlk#9902]
### Current Behaviour

in addition to [Can't run db_assembler.sh](https://github.com/azerothcore/azerothcore-wotlk/issues/5685)

I still have this error.

![изображение](https://user-images.githubusercontent.com/25766571/147550369-cab019ae-817c-4f3e-b479-226c887f30b4.png)

![изображение](https://user-images.githubusercontent.com/25766571/147550594-597d6d86-63af-45b7-9f48-65f9f6773cfc.png)

### Expected Blizzlike Behaviour

?

### Steps to reproduce the problem

1. open db_assempler app folder
2. 
![изображение](https://user-images.githubusercontent.com/25766571/147551098-744b23b2-6788-490b-b263-cf5909e98ca8.png)
3. drag-n-drop db_assembler.sh into bash window and press Enter

### AC rev. hash/commit

AzerothCore rev. 7192896e2f20

### Operating system

OS Windows 7 x64

**Comment by Bogir** [comment]
I found the revision after which the file stopped working. 

22.04.2021 12:57:05 ** Feat(Docker/bash): docker-compose system rework (#4488)**

When I used config.sh which was before this revision, db_assembler starts normally.

![изображение](https://user-images.githubusercontent.com/25766571/147578872-9571b306-7ccd-4b52-93ee-86043bfa1edd.png)

Typed 5 - assemble & import all. 
Result - all base tables was imported and all updates too
![изображение](https://user-images.githubusercontent.com/25766571/147584245-f2cd9870-95eb-43e8-8d9b-bb9ba40511db.png)

**Comment by Kitzunu** [comment]
Maybe -d was deprecated in git bash. Because if you look at the syntax for readarray you don't gave -d as a variable to pass.

**Comment by PatricNox** [comment]
I think it's a typo here

> readarray -td, DATABASES <<<"$DBLIST"

```
-t     Remove a trailing delim (default newline) from each line read.

-d     The first character of delim is used to terminate each input line, rather than newline
```

So, maybe, the line is supposed to have a space inbetween the `d` option and the followed comma?

`readarray -td , DATABASES <<<"$DBLIST"`

Don't take my word for it, I gathered this through browsing by phone. Needs some testing/verification

**Comment by Eronox** [comment]
I think it's a typo here

> readarray -td, DATABASES <<<"$DBLIST"

```
-t     Remove a trailing delim (default newline) from each line read.

-d     The first character of delim is used to terminate each input line, rather than newline
```

So, maybe, the line is supposed to have a space inbetween the `d` option and the followed comma?

`readarray -td , DATABASES <<<"$DBLIST"`

Don't take my word for it, I gathered this through browsing by phone. Needs some testing/verification

**Comment by Bogir** [comment]
no... 

error the same

![изображение](https://user-images.githubusercontent.com/25766571/148425166-05bc3242-173a-48f6-a4ed-513ec7f76f9e.png)

**Comment by Eronox** [comment]
> no...
> 
> error the same
> 
> ![изображение](https://user-images.githubusercontent.com/25766571/148425166-05bc3242-173a-48f6-a4ed-513ec7f76f9e.png)

Then kitzunu is correct about the bash version as git bash is a windows port of GNU bash which is a POSIX-compatible shell. I doubt git bash deprecated it though, instead i believe youre on a older version or similar 

do try update it

**Comment by Kitzunu** [comment]
@Bogir update?

**Comment by Bogir** [comment]
> @Bogir update?

![изображение](https://user-images.githubusercontent.com/25766571/156250586-a78c7d7b-dcdf-474c-b8d8-ab511d2ffd25.png)

**Comment by Bogir** [comment]
> do try update it

I'm using the last version which I have found

**Comment by Bogir** [comment]
I still use db_assembler from 22.04.2021 on win7 :)

**Comment by Bogir** [comment]
Now db_assembler is deprecated app. So I'm closing this issue.
