### ISSUE TITLE
Vmap & Descriptor Issue

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#991]
After server release everything was pretty fine.
But, after almost 13 hours, those errors started and auth was locked.
Restarting Auth didn't help - Had to restart world as well -> No errors since  (Almost 7 hours)

I'm not sure what actually triggered, since there was 30+ players online.
Some of the objects are in Hellfire Peninsula, around Dark Portal or etc, and there is no players at all.
Also, i had few DDoS attacks (I'm checking with Host company about details as i'm typing)

https://pastebin.com/QdMmDqtb - Log link

How to reproduce: No idea sadly, i was away from PC when it happened.

System: Debian 9
Modules: Premium Account
Modifications: Nothing custom
AzerothCore rev. 07a451e1402c+ 2018-07-13 21:07:47 +0200 (master branch)

**Comment by BarbzYHOOL** [comment]
We have got a leak. If you run worldserver and type:

    ls -al /proc/*/fd/* 2>/dev/null | egrep ".*log$"

You will see a huge list of worldserver logs opened for no reason. I had 700 DBERRORS.log opened


Temporary fix is to increase your file descriptor limit (look up google for that)

**Comment by Winfidonarleyan** [comment]
I found a mistake, and I think I fixed it.
