### ISSUE TITLE
Various issues with Enslave Demon

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/azerothcore-wotlk#9916]
### Current Behaviour

After successfully casting [Enslave Demon](https://wowgaming.altervista.org/aowow/?spell=11726) while out of combat, you may mount up.
You may bring a demon outside of its fighting range, then it will have some weird behavior.

(I cut some walking with the demon in the video)

https://user-images.githubusercontent.com/22718174/147680305-5135fec2-5f2d-4f6c-a5be-70086d27bfbc.mp4

You may auto attack a demon that you currently own with [Enslave Demon](https://wowgaming.altervista.org/aowow/?spell=11726) (I saw a similar behavior with [Mind Control](https://wowgaming.altervista.org/aowow/?spell=605)).

https://user-images.githubusercontent.com/22718174/147680207-c69da943-fa08-4b40-8dd7-cea72781af60.mp4

### Expected Blizzlike Behaviour

If you successfully cast `Enslave Demon` while out of combat, I believe you should be in combat against the demon you just enslaved because it should want you dead.

When the `Enslave Demon` expires or get dismissed, I believe it should want to fight the warlock until death or until the leash timer expires if outside of the aggressive area (see extra notes).

If you have the melee auto attack enabled on said demon, once enslaved, you should not be able to auto attack it (unless it is from an ennemy player). I saw a similar behaviour with Mind Control.

### Steps to reproduce the problem

`/cast Enslave Demon`
Use the pet's `Attack` on something then use the pet's `Follow` to cancel its attack command.
"Dismiss" the pet/let the control (Enslave Demon) expire away from its area that he'd usually fight the player.

### Extra Notes

Parts of this bug report might be related to [Creatures leash system not blizzlike (#5116)](https://github.com/azerothcore/azerothcore-wotlk/issues/5116).

### AC rev. hash/commit

Reproduced on a local AC: AzerothCore rev. c6be653f9a8c 2021-12-27 17:15:40 +0000 (master branch) (Win64, RelWithDebInfo, Static)

Also seen on ChromieCraft: AzerothCore rev. 1a75b3ef0d4e 2021-12-29 09:23:34 -0300 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10 x64

### Custom changes or Modules

Only this one.
[mod-eluna-lua-engine](https://www.azerothcore.org/catalogue-details.html?id=131435473)

**Comment by UltraNix** [comment]
`You may auto attack a demon that you currently own with [Enslave Demon](https://wowgaming.altervista.org/aowow/?spell=11726)` Works okay now.
Also, you can bring charmed creature outside its spawn area and behaves correctly.

**Comment by UltraNix** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12496#issuecomment-1193167708
You can mount up while charming.
