### ISSUE TITLE
Balance of Itens

### ISSUE THREAD

**Issue by LipeBreno** [azerothcore/azerothcore-wotlk#993]
Good Night to all, running away a little of the issues I have a question regarding the balancing of Items, is there any fixed equation to balance items? if someone knows some or some method of balancing item show me or send me. Thank you very much in advance!

**Comment by dunjeon** [comment]
This ins't an issue? 
Maybe try your luck on Discord:
https://discord.gg/MDTjCd

**Comment by BarbzYHOOL** [comment]
Ask this on discord or on ac-web.org or somewhere else, we only take issues here.
