### ISSUE TITLE
Flying chairs in Stonetalon Mountains

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9930]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2700

There are flying wooden chairs in stonetalon mountains - grimtotem post, location 75/88
![cc_grimtotem post](https://user-images.githubusercontent.com/29784358/147744442-0e7731f9-1345-47a6-b18c-66bed549238b.png)

Tester:

The issue is confirmed. Flying chairs in Stonetalon Mountains

```
11766 (Entry: 2413) - [Wooden Chair X:39.096802 Y:-425.746002 Z:44.691200 MapId:1] 
11765 (Entry: 2413) - [Wooden Chair X:41.165199 Y:-426.865997 Z:44.686001 MapId:1] 
11768 (Entry: 2413) - [Wooden Chair X:27.678600 Y:-427.690002 Z:47.636902 MapId:1] 
11767 (Entry: 2413) - [Wooden Chair X:25.757999 Y:-425.837006 Z:47.636902 MapId:1] 
11769 (Entry: 2413) - [Wooden Chair X:25.248199 Y:-433.104004 Z:47.636902 MapId:1] 
```
![WoWScrnShot_123021_172232](https://user-images.githubusercontent.com/85256266/147760168-ff37a2b3-d568-4dfc-bf33-7e055bce85eb.jpg)

### Expected Blizzlike Behaviour

No flying wooden chairs in that area

### Steps to reproduce the problem

.go xyz 38 -420 42 1 4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
awesome. These spawns are sniffed right @malcrom @acidmanifesto 🤣

**Comment by Kitzunu** [comment]
Doing some cross reference to TC. These GUID's and ID's do exist. However they are spawned in Map 30 with the same chords. So we just have to change the map

**Comment by acidmanifesto** [comment]
Give me like a hour and i will look into it. But as far as i am aware these chairs didnt come our current sniff team

**Comment by Kitzunu** [comment]
I was joking :P They belong in AV as far as TDB is, with the same chords and everything. So I believe that whoever spawned them in AC just used the wrong map id
