### ISSUE TITLE
Crash on character creation

### ISSUE THREAD

**Issue by tkn963** [azerothcore/azerothcore-wotlk#9945]
### Current Behaviour

Creating a new character, specifically an Orc, as any class other than Warrior or Rogue causes the server to crash.

### Expected Blizzlike Behaviour

The server shouldn't crash.

### Steps to reproduce the problem

1. Compile and start the server
2. Log onto the server
3. Create a new character
4. Select Orc as race
5. Select any class EXCEPT Warrior and Rogue
6. Click accept
7. Profit

### Extra Notes

I have been doing a fair bit of research on this issue to find when it started happening. According to my results, the 24ab999 commit is when it started. It could be one or two commits after, if I made a mistake somewhere. I do know for a fact that 53a6fb7 works as it should.

Other races may have issues too, I only tested Human, Tauren, Troll and Orc and only Orc had this issue.

### AC rev. hash/commit

d54af70

### Operating system

Windows 11 x64, Debian 11 x64

**Comment by Kitzunu** [comment]
@Nyeriah could you have a look please

**Comment by Shineslippers** [comment]
![image](https://user-images.githubusercontent.com/85256266/147829748-ef212704-3a45-42a8-8162-2884d4440193.png)

**Comment by acidmanifesto** [comment]
This was something that was happening to me last night with my orc hunter. i figure it was maybe it was a me messing up something with a custom client, but i will see what hits in debugger with the breaks and see what i can find out.

**Comment by Nyeriah** [comment]
Yes, i already know about it. Working on something to fix it
