### ISSUE TITLE
Delete server motd

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#995]
Kind time of the day tell me which file. Raise this text
This server runs on azerothcore

https://ibb.co/n8EOYz

**Comment by lineagedr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/ccb3e8c2a4d711d5239b7e6b8c351f009ea09b46/src/server/game/World/World.cpp#L479

**Comment by ShinDarth** [comment]
why do you want to remove the credits?

**Comment by BarbzYHOOL** [comment]
This is not supported. Without this message we have less visibility and so, less contributors, and less bug fixes so everybody is losing in the end
