### ISSUE TITLE
[Spell] Mind Control - You do not get out of combat after target dies

### ISSUE THREAD

**Issue by ishidinho** [azerothcore/azerothcore-wotlk#9980]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2683

So, when you mind control a mob and it, and any other involved mob in the fight, dies (basically, when the battle is over) you keep the combat state, you can’t drink or get on the mount
And the battle is over there’s no other mob attacking you

Tester:

The issue is confirmed.

https://user-images.githubusercontent.com/62797536/147914082-d7eb777f-b4ee-42d9-8013-00718a8a7363.mp4

### Expected Blizzlike Behaviour

You should get out of combat after your mind controlled target dies.

### Steps to reproduce the problem

Original reporter:
1. Get a lvl 40 priest
2. Go to Elwynn forest
3. Mind control a bandit
4. Cancel the mc and kill it
5. Congratulations, now you can’t get on the mount :D

Steps by tester:
1. `.go creature 80690`
2. `.character level <name> 40`
3. Cast Mind Control on target
4. Cancel Mind Control
5. Kill target

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/33673bc1c2864cf9dd86209bd915d4529ec83f00

### Operating system

Ubuntu

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Kitzunu** [comment]
I might have a fix. Can check tonight or tomorrow

**Comment by Eronox** [comment]
> I might have a fix. Can check tonight or tomorrow

is it cus of this? 
https://github.com/azerothcore/azerothcore-wotlk/pull/8733

**Comment by Kitzunu** [comment]
That is my working theory, and I have a fix if that's the case. But I dont get to my PC until tonight or tomorrow

**Comment by Kitzunu** [comment]
Actually I dont believe that, because SetCharmedBy() and RemoveCharmedBy() has nothing to do with you charming
