### ISSUE TITLE
Great father Winter's Helper is present after end of Winter Veil: Gifts event

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9981]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2716

![image](https://user-images.githubusercontent.com/80590226/147887631-e60e0ddd-e343-49fb-8fff-716c220f5b7c.png)

Great-Father Winter's Helper is still present in Orgrimmar even tho his friends are gone since event is gone.
NOTE: Hadn't checked other cities.

Tester:

The issue is confirmed. [Great-father Winter's Helper](https://wowgaming.altervista.org/aowow/?npc=15746) and [Greatfather Winter's Helper](https://wowgaming.altervista.org/aowow/?npc=15745) are present after end of [Winter Veil: Gifts](https://wowgaming.altervista.org/aowow/?event=52) event
![WoWScrnShot_010322_142137](https://user-images.githubusercontent.com/85256266/147925634-8c45d554-e732-4d4a-b1cf-38672f7baf78.jpg)

![WoWScrnShot_010322_141803](https://user-images.githubusercontent.com/85256266/147925624-ed7b9d5d-0669-4957-9e95-d89fb6190259.jpg)

### Expected Blizzlike Behaviour

Should appear and disappear with Winter Veil: Gifts

### Source

Wowhead [Great-father Winter's Helper](https://www.wowhead.com/npc=15746/great-father-winters-helper)
> By Midgetpower on 2011/12/27 (Patch 4.3.0)
Stands next to Great-father Winter from Dec 25th until the end of Winter Veil yelling:
Presents for everyone! Father Winter's put gifts under the tree for all.

Wowhead [Greatfather Winter's Helper](https://www.wowhead.com/npc=15745/greatfather-winters-helper)

### Steps to reproduce the problem

.go c id 15745
.go c id 15746

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1a75b3ef0d4e7a31d3691cbe22f30af048efa68b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by Bogir** [comment]
Confirm
![изображение](https://user-images.githubusercontent.com/25766571/147936266-09702ef5-9faf-4aa8-9245-247aaef83ae1.png)
