### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#9995]
### Current Behaviour

warlock summon a imp, then mount,and unmount ,the imp won't apear and summon another pet such as voidwalker
then crash 

### Expected Blizzlike Behaviour

won't crash

### Steps to reproduce the problem

1.warlock cast summon imp
2.mount
3.unmount 
4.summon void walker

### AC rev. hash/commit

235fea9ce569+

### Operating system

Ubuntu 20.04

**Comment by betayi** [comment]
it seemed be relate with #9712

**Comment by betayi** [comment]
![7a2b081382831b21e3aaa609f39d146](https://user-images.githubusercontent.com/37472600/148040290-0c01d751-699c-4f8e-bdd6-feb605b222df.png)

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan please have a look at this

**Comment by Kitzunu** [comment]
Hello, thank you for your report.

For us to investigate it further we would appreciate if you could attach a crashlog via either Github Gist or PasteBin so we can see the callstack up to this crash.

**Comment by Kitzunu** [comment]
I cannot reproduce this either on f593f624b019 Is it possible that you use custom code?

**Comment by betayi** [comment]
well, i’ll try to get crashlog , i am not sure how to get that, many times, and thank you for all above

**Comment by Winfidonarleyan** [comment]
@betayi Can you record a video?

**Comment by Kitzunu** [comment]
If you have compiled in RelWithDebInfo or Debug you should find a crashlog within the crash folder. It might be a gdb file in ubuntu if im not misstaken

**Comment by betayi** [comment]
i got this
[gdb.txt](https://github.com/azerothcore/azerothcore-wotlk/files/7811315/gdb.txt)
and btw,i ever use item 21044 for mount after last update, then crash while mount

**Comment by Kitzunu** [comment]
Could you upload the content of the txt file onto Gist or PasteBin. That way we dont need to download it

**Comment by betayi** [comment]
https://gist.github.com/betayi/380683ef30f44c1b4b5a429ec423dca2

**Comment by Winfidonarleyan** [comment]
@betayi can test #10025?

**Comment by betayi** [comment]
> @betayi can test with #10025?

I Cmake the core with the 2 files change, and crash again.
here is the log
https://gist.github.com/betayi/31522c4f62c8987a85f61e98f3ee9aae

**Comment by betayi** [comment]
and again
https://gist.github.com/betayi/6d47ce84644c6386d3e79c1994d30871

**Comment by anzz1** [comment]
The pet system seems currently broken, I think it's better to revert to an older patch. In version https://github.com/azerothcore/azerothcore-wotlk/commits/e5d650c5f3e35973b8b9acfbab31857c9a1c4134 everything is still working fine.

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9712 this PR?

**Comment by Winfidonarleyan** [comment]
> #9712 this PR?

Can test #10025

**Comment by SKingOWN** [comment]
> > #9712 this PR?
> 
> Can test with this #10025 ?

I am testing this, but when you mount and dismount your pet appear with low health.

**Comment by mpfans** [comment]
I revert #9712 PR ,not crash...

Cannot test now#10025,I can test it in two days

#9712 on mount and then dismount. Pet's health and magic value are only 68%

**Comment by UltraNix** [comment]
@Winfidonarleyan https://github.com/TrinityCore/TrinityCore/issues/25478 Have you tried this? It's the same crash.

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan [TrinityCore/TrinityCore#25478](https://github.com/TrinityCore/TrinityCore/issues/25478) Have you tried this? It's the same crash.

Thanks
